### ISSUE TITLE
Failed to pull image, 403 Forbidden

### ISSUE THREAD

**Issue by frbimo** [goharbor/harbor#10004]
**Describe the issue**
Failed when pulling image from private repository.

**Version of harbor**:
Version v1.9.3-c80751b8

**What happened**:
`kubectl describe po` returns 
`... no available registry endpoint: failed to fetch oauth token: unexpected status: 403 Forbidden`

**What you expected to happen**:
Success pulling image from private repository.

**What else we need to know**:
Secret contains `.dockerconfigjson` of related pod has been created 
I have double-check credentials details( url, user, password, etc) inside secret and re-decoded it to make sure it's correct but problem still happened.

**Comment by heww** [comment]
Can you pull images by docker cli when uses this credential?

**Comment by frbimo** [comment]
> Can you pull images by docker cli when uses this credential?

yes i can.  i was using harbor v1.8.3 but found no this kind of problem.

**Comment by frbimo** [comment]
after changing container runtime to docker, now is working.
