### ISSUE TITLE
Harbor HA use F5 asload balancer issue

### ISSUE THREAD

**Issue by xcjing** [goharbor/harbor#10033]
dear support:

I have a Harbor HA environment base on v1.8.3. which have two node:
server1: 10.43.10.111
server2: 10.43.10.112. 
I use F5 as load balancer, which IP is 10.43.10.150.
below command is ok.
docker push 10.43.4.111/aaa/demo2
docker push 10.43.4.112/aaa/demo2

but when I run:
docker push 10.43.10.150/aaa/demo2
I get error:
unauthorized: authentication required

if I shutdown server1 or server2. only keep on server up. 
docker push 10.43.10.150/aaa/demo2 is also ok.

I think maybe this is F5 forword issue. so I run docker login -u admin -p Harbor12345 10.43.10.150 several time. the result is below.
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

**Login Succeeded**
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://10.43.10.150/v2/ failed with status: 401 Unauthorized
# docker login -u admin -p Harbor12345 10.43.10.150
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

**Login Succeeded**

from above, you can see some time login is succeed, some time is fail.
when login succeed, then run docker push 10.43.10.150/aaa/demo2 again
I still get the same error.

**Comment by smekkley** [comment]
Looks like a session persistence issue on F5 side.
I guess sessions are stored on redis, so unless your harbor setup is cluster ready(shared data dir, postgres, redis), it won't work without session persistence on F5 side.

**Comment by linkt** [comment]
I have a same iissue ,two node use share redis and postgresql, and the data dir is NFS。
