### ISSUE TITLE
Database replacement (harbor v1.5-->v1.9),psql --> mysql

### ISSUE THREAD

**Issue by huyifanstar** [goharbor/harbor#10044]
Server Version: 19.03.5   ， harbor：v1.9.0 
Now we need to migrate the data from PostgreSQL back to mysql and how to change the default PostgreSQL (v1.9) to mysql database in Harbor.yml.

Now that we downloaded the latest 1.9 and upgraded it from version 1.5 to V1.9, the container initialization failed (harbor-db: v1.9.0)

**Comment by reasonerjt** [comment]
@huyifanstar 
v1.9 does not work with mysql.

**Comment by huyifanstar** [comment]
> @huyifanstar
> v1.9 does not work with mysql.

What about db data(mysql)?

**Comment by wy65701436** [comment]
please follow the path to upgrade your harbor. v1.5->v1.6->v1.8-v1.9.

**Comment by huyifanstar** [comment]
> 请按照以下路径升级您的港口。v1.5-> v1.6-> v1.8-v1.9。
Can you choose mysql? 
![image](https://user-images.githubusercontent.com/15685376/69857729-7fcca300-12cb-11ea-81f5-99ed90e729dd.png)

**Comment by xaleeks** [comment]
> please follow the path to upgrade your harbor. v1.5->v1.6->v1.8-v1.9.

we need to think about shortening this chain, so any version can be upgraded to the newest in 2 steps

**Comment by reasonerjt** [comment]
@xaleeks the chain can be shortened to 2 steps now, it's just not verified in CI, it's not realistic to verify all combinations
