### ISSUE TITLE
Project quotas management

### ISSUE THREAD

**Issue by huzhengchuan** [goharbor/harbor#1005]
I use the harbor 0.4 as private container-image repository. it works very good. I see the image can manage with a project.  But I not know the size of image in project. and whether can set the capacity of the project. when the size of images in project  more than the capacity, it can not allow push image to the project.   
is there any blueprint about the project quotas management?

**Comment by reasonerjt** [comment]
Thanks for the input, it's a valid request we'll investigate.
A few gaps before we can implement such feature.
1)We need to figure out how much space does a project really take on the storage.
2)We need to implement a mechanism to reject such request, with current architecture of Harbor, the rejection are sent by registry when the token is invalid which may not be suitable for this use case.

**Comment by huzhengchuan** [comment]
thanks very much,  I will continue to keep an eye on this.

**Comment by govindkailas** [comment]
Was there any update on enabling quota management?

**Comment by xaleeks** [comment]
released in 1.9
