### ISSUE TITLE
Implement OCI registry

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10058]
The OCI registry handles all OCI registry APIs

**Comment by reasonerjt** [comment]
All the handling of requests to "/v2/*" will be covered under this item

**Comment by reasonerjt** [comment]
Please make sure this handler can handle the case when registry is host https.

**Comment by reasonerjt** [comment]
Please also double check if the current middleware framework can handle proxying request to blobs APIs.

Also explore other options for reverseproxy, improve the performance in the reverseproxy + interceptors should also be part of this Epic.
