### ISSUE TITLE
Harbor被设置为只读模式，在此模式下，不能删除仓库、标签及推送镜像。

### ISSUE THREAD

**Issue by Arthur666** [goharbor/harbor#10055]
大概出现以下日志以后，harbor就被设置为了只读模式，原因未知。

Oct 23 19:22:05 bogon core[1052]: 2019/10/23 11:22:05 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:22:14 bogon core[1052]: 2019/10/23 11:22:14 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:22:25 bogon core[1052]: 2019/10/23 11:22:25 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:22:59 bogon core[1052]: 2019/10/23 11:22:59 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:23:11 bogon core[1052]: 2019/10/23 11:23:11 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:23:20 bogon core[1052]: 2019/10/23 11:23:20 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 23 19:23:30 bogon core[1052]: 2019/10/23 11:23:30 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/readonly/hanlder.go:44#033[0m
Oct 24 08:00:09 bogon core[1052]: 2019-10-24T00:00:09Z [WARNING] [/core/middlewares/readonly/hanlder.go:39]: The request is prohibited in readonly mode, url is: /v2/paas/file-service/manifests/sha256:1670aa33d2820b7f47f2488f3bfe36fc88a24de24390204a4ed314c47a5fb782
Oct 24 08:00:09 bogon core[1052]: 2019-10-24T00:00:09Z [ERROR] [/common/api/base.go:195]: failed to delete tag 5358: http error: code 403, message {"errors":[{"code":"DENIED","message":"The system is in read only mode. Any modification is prohibited.","detail":"The system is in read only mode. Any modification is prohibited."}]}

**Comment by wy65701436** [comment]
Did you create a GC schedule? Also, you can disable the `read-only` by UI or by API, just follow the user guide.

**Comment by melotusme** [comment]
When GC schedule is done, will the read-only mode be disabled without manual setting？
