### ISSUE TITLE
Upgrade&Migration for OCI work

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10069]
- [ ] Upgrade the database schema
- [ ] Populate the detail info for the existing artifacts

**Comment by wy65701436** [comment]
Fro the migration, we should consider the following tow paths:
1, from a version without artifact to artifact_2
2, from a version with artifact to artifact_2

The data of artifact is inserted by the quota migrater, this should be a big hassel.

**Comment by ywk253100** [comment]
Done
