### ISSUE TITLE
Verify against the popular registry client after introducing the OCI work

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10071]
- [x] Docker - P0
- [ ] containerd - P0
- [ ] Podman - P1
- [ ] Skopeo - P1

**Comment by xaleeks** [comment]
what does verifying against podman and skopep mean?  verify we can push images that are produced from podman (as long as they are oci compatible) to Harbor?  @ywk253100

**Comment by xaleeks** [comment]
tracking this here now https://github.com/goharbor/harbor/issues/10914
