### ISSUE TITLE
many images size were  0B and creation time marked 1/1/01, 8:05 AM

### ISSUE THREAD

**Issue by tan-chao** [goharbor/harbor#10078]
**Expected behavior and actual behavior:**
I used the harbor API to clean up the image file and found that many images were 0B and creation time marked ` 1/1/01, 8:05 AM`
<img width="1439" alt="harbor" src="https://user-images.githubusercontent.com/1840856/69938092-5ef88d80-1517-11ea-9ed1-3055774c2ff4.png">

<img width="704" alt="WeChat9d7482fe18476f3508d95aafdb5651a4" src="https://user-images.githubusercontent.com/1840856/69938731-fe6a5000-1518-11ea-8a09-a48921ace88d.png">

**registry/docker/registry/v2/repositories/REPO-NAME/_manifests/revisions/sha256** Many file directories do not have **link** file

**Versions:**
- harbor version: [1.7.2]

**Comment by jhondom** [comment]
i have the same problem as many images size were 0B and creation time marked 1/1/01, 8:05 AM。when this is occurred, docker login is error:
![image](https://user-images.githubusercontent.com/37328297/126417589-84c87a9d-f45c-4b90-ad09-de823529d146.png)
or docker push is error:
![image](https://user-images.githubusercontent.com/37328297/126417668-3e26f0d8-5ba8-4d13-8664-9e33ee1fc2b4.png)

Versions:

harbor version: [1.7.1]
