### ISSUE TITLE
upgrade error from 1.9.3 to v1.10.0

### ISSUE THREAD

**Issue by insightcloud** [goharbor/harbor#10085]
Hello I`m trying to upgrade Harbor from 1.9.3 to v1.10.0,  but install.sh is failing witj error

IsADirectoryError: [Errno 21] Is a directory: '/config/log/logrotate.conf' 

`[root@xxxx harbor]# ./install.sh

[Step 0]: checking if docker is installed ...
✖ Need to upgrade docker package to 17.06.0+.

[Step 1]: checking docker-compose is installed ...

Note: docker-compose version: 1.18.0

[Step 2]: loading Harbor images ...
Loaded image: goharbor/harbor-migrator:v1.10.0
Loaded image: goharbor/prepare:v1.10.0
Loaded image: goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.0
Loaded image: goharbor/harbor-jobservice:v1.10.0
Loaded image: goharbor/notary-signer-photon:v0.6.1-v1.10.0
Loaded image: goharbor/harbor-portal:v1.10.0
Loaded image: goharbor/harbor-log:v1.10.0
Loaded image: goharbor/clair-adapter-photon:v1.0.1-rc2-v1.10.0
Loaded image: goharbor/harbor-db:v1.10.0
Loaded image: goharbor/harbor-registryctl:v1.10.0
Loaded image: goharbor/nginx-photon:v1.10.0
Loaded image: goharbor/notary-server-photon:v0.6.1-v1.10.0
Loaded image: goharbor/clair-photon:v2.1.0-v1.10.0
Loaded image: goharbor/chartmuseum-photon:v0.9.0-v1.10.0
Loaded image: goharbor/harbor-core:v1.10.0
Loaded image: goharbor/redis-photon:v1.10.0

[Step 3]: preparing environment ...

[Step 4]: preparing harbor configs ...
prepare base dir is set to /app/harbor
WARNING:root:WARNING: HTTP protocol is insecure. Harbor will deprecate http protocol in the future. Please make sure to upgrade to https
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 42, in main
    prepare_log_configs(config_dict)
  File "/usr/src/app/utils/log.py", line 26, in prepare_log_configs
    **config_dict)
  File "/usr/src/app/utils/jinja.py", line 8, in render_jinja
    with open(dest, 'w') as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/log/logrotate.conf'
`

**Comment by ninjadq** [comment]
You can remove the `./common/config/log/logrotate.conf` in your harbor installation dir and try again?

Could you provide the steps you upgrade harbor?

**Comment by insightcloud** [comment]
i moved my /harbor/ installation directory to a backup location then i unzip new harbor version offline package and run the ./install.sh inside the new /harbor installation directory, the /data directory where the database is remains untouched,   i  don`t see the point to run the "migration" container as i already have and harbor.yml file available in version 1.9.3, for me the upgrade/migration procedure is totally outdated.

**Comment by ninjadq** [comment]
before installation. you need to run the migration script to upgrade your `harbor.yml`
