### ISSUE TITLE
status: 503 Service Unavailable

### ISSUE THREAD

**Issue by chinaboy007** [goharbor/harbor#10082]
docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

centos 7.6 
-----------------------------------------------------------
docker login harbor.gaosu.com -u admin -p 123456
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to http://harbor.gaosu.com/v2/ failed with status: 503 Service Unavailable

**Comment by wy65701436** [comment]
what's your harbor version? how did you setup harbor? and please also provide logs.

**Comment by chinaboy007** [comment]
> what's your harbor version? how did you setup harbor? and please also provide logs.

harbor 1.9.2 
I see  https://github.com/goharbor/harbor/blob/master/docs/configure_https.md to install.

so i delete  /etc/docker/daemon.json   "insecure-registries": ["0.0.0.0/0"],  
**503 Service Unavailable**  has not exists.

but have new error:
docker login harbor.gaosu.com -u admin -p 123456
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get **https**://harbor.gaosu.com/v2/: Service Unavailable
