### ISSUE TITLE
make tag listing vertically scrollable

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10093]
<img width="351" alt="Screen Shot 2019-11-12 at 5 30 28 PM" src="https://user-images.githubusercontent.com/51319901/70020758-f54ea280-155b-11ea-8d17-d7f7eb7f3d84.png">

I vote make this vertical scrollable, instead of multiple pages.

**Comment by reasonerjt** [comment]
Let's increase the default page size of tag grid to 50, and make sure there's scroll in data grid.

**Comment by zhoumeina** [comment]
@jwangyangls , let's increase the default pagesize to 50. Have an option to select different page size. 
<clr-dg-pagination #pagination [clrDgPageSize]="pageSize">
          <clr-dg-page-size [clrPageSizeOptions]="[10,20,50,100]">
            {{ 'management.administration.quotas.label.usersPerPage' | translate }}
          </clr-dg-page-size>
          {{ pagination.firstItem + 1 }} - {{ pagination.lastItem + 1 }} {{ 'pks.label.of' | translate }} {{ pagination.totalItems
          }} {{ 'management.administration.quotas.label.users' | translate }}
        </clr-dg-pagination>
