### ISSUE TITLE
move all actions to left panel in list view for robot accounts

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10097]
<img width="806" alt="Screen Shot 2019-11-24 at 6 15 28 PM" src="https://user-images.githubusercontent.com/51319901/70021087-66428a00-155d-11ea-91c8-01bcbb38e7b9.png">

see comment in ss

**Comment by reasonerjt** [comment]
Let's revisit when in 1.11 timeframe.

**Comment by xaleeks** [comment]
do we have a consistent experience now? or should we another fit and finish review on this? @AllForNothing

**Comment by AllForNothing** [comment]
@xaleeks    See #11079.

**Comment by reasonerjt** [comment]
We'll keep it as is.
