### ISSUE TITLE
scan job item listing should not be variable

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10094]
please see issue described on the screenshot

<img width="1523" alt="Screen Shot 2019-11-19 at 4 13 18 AM" src="https://user-images.githubusercontent.com/51319901/70020831-4bbbe100-155c-11ea-8bf1-c6b04abcdf0b.png">

**Comment by reasonerjt** [comment]
This is irrelevant to scan.

We should make sure the order of the tags stay unchanged.
