### ISSUE TITLE
remove 'PUSH IMAGE' docker cli instructions

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10102]
<img width="692" alt="Screen Shot 2019-11-26 at 11 28 03 PM" src="https://user-images.githubusercontent.com/51319901/70021364-79098e80-155e-11ea-9ba5-602e3386f1e7.png">

this is essentially an instruction set, maybe 'push image' can be renamed to something else, or we can get rid of it entirely.  opinions?

also there's a small UI enhancement needed, see comment in ss
<img width="350" alt="Screen Shot 2019-11-26 at 11 34 06 PM" src="https://user-images.githubusercontent.com/51319901/70021427-b8d07600-155e-11ea-8fb1-9cc439fd4501.png">

**Comment by reasonerjt** [comment]
The title "PUSH IMAGE" is confusing we should refine the label, adjust font.

**Comment by zhoumeina** [comment]
What about call it "Command References..."， modify it to a tooltip, and we can have a look.

**Comment by xaleeks** [comment]
Not sure about 'command references', I think also difficult to understand. 

how about ' push image docker command'

**Comment by xaleeks** [comment]
the other thing is we should be consistent, make sure other places also have these instructions where applicable
