### ISSUE TITLE
retagged image shows up only AFTER manual refresh

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10105]
see comment in ss, basically user should not have to refresh page manually to see retagged images

<img width="1351" alt="Screen Shot 2019-12-03 at 11 18 12 AM" src="https://user-images.githubusercontent.com/51319901/70021629-54fa7d00-155f-11ea-969d-ec06c5438b9b.png">

**Comment by jwangyangls** [comment]
The current implementation on the UI is to retag the page when the current repository is retagged
