### ISSUE TITLE
move actions for replication rules to the side as an expandable drop down for each replication rule

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10106]
<img width="1313" alt="Screen Shot 2019-12-03 at 11 23 49 AM" src="https://user-images.githubusercontent.com/51319901/70021657-6e032e00-155f-11ea-869a-413b9c958aba.png">

this is the same idea as moving actions to the side for each robot account.  It's awkward to hit 'edit' or 'delete' at the top.  Also this is confusing when you've selected multiple replication rules

**Comment by jwangyangls** [comment]
you can only select single rule,because it is a radio not checkbox

**Comment by zhoumeina** [comment]
@xaleeks , I don't think it will be better if all actions in the grid. Let's see what can be improve in 1.11.
