### ISSUE TITLE
deleting multiple tags sharing digest should first generate warning

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10104]
<img width="1339" alt="Screen Shot 2019-12-03 at 11 14 24 AM" src="https://user-images.githubusercontent.com/51319901/70021529-064ce300-155f-11ea-8d85-a8bc37797143.png">

see comment in ss, basically if there are 100 tags sharing a digest and user deletes one of them, all are deleted with no warning.  This is not great experience for new users of Harbor and there's also no way to know which tags share a digest right now

**Comment by reasonerjt** [comment]
For 1.10
We can add a warning dialog regardless if there are images sharing the same digest or not.

**Comment by zhoumeina** [comment]
@jwangyangls , let's add a confirmation box when delete all tags in 1.10.
