### ISSUE TITLE
disallow 'deletion' of immutable images in harbor web console UI

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10103]
see comment in ss, a little small but basically better to grey out the 'delete' on UI for immutable images

<img width="1283" alt="Screen Shot 2019-12-03 at 11 02 46 AM" src="https://user-images.githubusercontent.com/51319901/70021471-d3a2ea80-155e-11ea-9b16-15b4555edf36.png">

**Comment by reasonerjt** [comment]
It probably won't exist in 1.11

**Comment by jwangyangls** [comment]
I think it could close, it has been added in tag list
