### ISSUE TITLE
notary remove not working

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor#10113]
**Expected behavior and actual behavior:**
In order to delete a signed repository, it requires signed data to be deleted first. So I ran `notary remove -p <image> <tag>` and the command executed successfully. However the image still shows in Harbor as signed and it cannot be deleted.

**Steps to reproduce the problem:**
1. Push an image with DOCKER_CONTENT_TRUST=1 so the image gets signed.
2. Run `notary remove -p <image> <tag>` to remove the trust data
3. The image still shows as signed in Harbor UI. As a result the image cannot be deleted.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.3
- Installed on Kubernetes using helm chart v1.2.3

**Comment by reasonerjt** [comment]
@shen3lu4 could you please specify what commands did you use to reproduce this problem and turn on the verbose flag when you issue `notary` command?

Currently the usage of notary is quite tricky I just wanna make sure this is not a usage error.

**Comment by shen3lu4** [comment]
$ notary -D remove -p harbor.xxxxxxx.com/devops/b 1
DEBU[0000] Using the following trust directory: /home/cloud-user/.docker/trust
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] Making dir path: /home/cloud-user/.docker/trust/tuf/harbor.xxxxxxx.com/devops/b/changelist
DEBU[0000] Removing target "1"
Removal of 1 from harbor.xxxxxxx.com/devops/b staged for next publish.
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] Making dir path: /home/cloud-user/.docker/trust/tuf/harbor.xxxxxxx.com/devops/b/changelist
Auto-publishing changes to harbor.xxxxxxx.com/devops/b
DEBU[0000] entered ValidateRoot with dns: harbor.xxxxxxx.com/devops/b
DEBU[0000] found the following root keys: [560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704]
DEBU[0000] found 1 valid leaf certificates for harbor.xxxxxxx.com/devops/b: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking root against trust_pinning config for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking trust-pinning for cert: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000]  role has key IDs: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] verifying signature for key ID: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] root validation succeeded for harbor.xxxxxxx.com/devops/b
DEBU[0000] entered ValidateRoot with dns: harbor.xxxxxxx.com/devops/b
DEBU[0000] found the following root keys: [560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704]
DEBU[0000] found 1 valid leaf certificates for harbor.xxxxxxx.com/devops/b: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking root against trust_pinning config for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking trust-pinning for cert: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000]  role has key IDs: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] verifying signature for key ID: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] root validation succeeded for harbor.xxxxxxx.com/devops/b
Enter username: admin
Enter password:
DEBU[0011] 200 when retrieving metadata for root
DEBU[0011] updating TUF client
DEBU[0011] Loading timestamp...
DEBU[0011] 200 when retrieving metadata for timestamp
DEBU[0011] timestamp role has key IDs: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0011] verifying signature for key ID: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0011] timestamp role has key IDs: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0011] verifying signature for key ID: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0011] successfully verified downloaded timestamp
DEBU[0011] Loading snapshot...
DEBU[0011] cached snapshot is invalid (must download): sha256 checksum for snapshot did not match: expected b9b11194f44740e677de8dd5a5536e95c808af21b8ff8f5220e9551bd2c6aea3
DEBU[0011] 200 when retrieving metadata for snapshot.b9b11194f44740e677de8dd5a5536e95c808af21b8ff8f5220e9551bd2c6aea3
DEBU[0011] snapshot role has key IDs: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0011] verifying signature for key ID: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0011] snapshot role has key IDs: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0011] verifying signature for key ID: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0011] successfully verified downloaded snapshot.b9b11194f44740e677de8dd5a5536e95c808af21b8ff8f5220e9551bd2c6aea3
DEBU[0011] Loading targets...
DEBU[0011] targets role has key IDs: 630aeaa79f00975952c453a254d6bb3921fb505fa013d322908f525ed281fc2d
DEBU[0011] verifying signature for key ID: 630aeaa79f00975952c453a254d6bb3921fb505fa013d322908f525ed281fc2d
DEBU[0011] successfully verified cached targets
DEBU[0011] Loading targets/notary_lu...
DEBU[0011] targets/notary_lu role has key IDs: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0011] verifying signature for key ID: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0011] successfully verified cached targets/notary_lu
DEBU[0011] Loading targets/releases...
DEBU[0011] targets/releases role has key IDs: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0011] verifying signature for key ID: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0011] successfully verified cached targets/releases
DEBU[0011] changelist remove: 1
DEBU[0011] No yubikey found, using alternative key storage: no library found
DEBU[0011] No yubikey found, using alternative key storage: no library found
DEBU[0011] applied 1 change(s)
DEBU[0011] signing snapshot...
DEBU[0011] sign called with 1/1 required keys
DEBU[0011] No yubikey found, using alternative key storage: no library found
DEBU[0011] Client does not have the key to sign snapshot. Assuming that server should sign the snapshot.
Successfully published changes for repository harbor.xxxxxxx.com/devops/b


however, after this the image still shows as signed:
$ notary -D list harbor.xxxxxxx.com/devops/b
DEBU[0000] Using the following trust directory: /home/cloud-user/.docker/trust
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] Making dir path: /home/cloud-user/.docker/trust/tuf/harbor.xxxxxxx.com/devops/b/changelist
DEBU[0000] entered ValidateRoot with dns: harbor.xxxxxxx.com/devops/b
DEBU[0000] found the following root keys: [560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704]
DEBU[0000] found 1 valid leaf certificates for harbor.xxxxxxx.com/devops/b: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking root against trust_pinning config for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking trust-pinning for cert: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000]  role has key IDs: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] verifying signature for key ID: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] root validation succeeded for harbor.xxxxxxx.com/devops/b
DEBU[0000] entered ValidateRoot with dns: harbor.xxxxxxx.com/devops/b
DEBU[0000] found the following root keys: [560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704]
DEBU[0000] found 1 valid leaf certificates for harbor.xxxxxxx.com/devops/b: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking root against trust_pinning config for harbor.xxxxxxx.com/devops/b
DEBU[0000] checking trust-pinning for cert: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000]  role has key IDs: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] verifying signature for key ID: 560d12c1c18f61c88a2b64c8345ace01e4404e50e8d87b4b2e3fea9f2b019704
DEBU[0000] root validation succeeded for harbor.xxxxxxx.com/devops/b
DEBU[0000] updating TUF client
DEBU[0000] Loading timestamp...
Enter username: admin
Enter password:
DEBU[0007] 200 when retrieving metadata for timestamp
DEBU[0007] timestamp role has key IDs: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0007] verifying signature for key ID: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0007] timestamp role has key IDs: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0007] verifying signature for key ID: 538a5bb2ff20c64187fa89c62d2a971173dad27824158915ae4df0533a417b61
DEBU[0007] successfully verified downloaded timestamp
DEBU[0007] Loading snapshot...
DEBU[0007] cached snapshot is invalid (must download): sha256 checksum for snapshot did not match: expected 00808bf39a8effbc451810dfee6a3ab85ec3349917cd2ff08edec9ab80865a80
DEBU[0007] 200 when retrieving metadata for snapshot.00808bf39a8effbc451810dfee6a3ab85ec3349917cd2ff08edec9ab80865a80
DEBU[0007] snapshot role has key IDs: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0007] verifying signature for key ID: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0007] snapshot role has key IDs: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0007] verifying signature for key ID: 667a472200ac20d1a355cef58bf817b49718ff28fe9285d3b820a2b081874ffc
DEBU[0007] successfully verified downloaded snapshot.00808bf39a8effbc451810dfee6a3ab85ec3349917cd2ff08edec9ab80865a80
DEBU[0007] Loading targets...
DEBU[0007] targets role has key IDs: 630aeaa79f00975952c453a254d6bb3921fb505fa013d322908f525ed281fc2d
DEBU[0007] verifying signature for key ID: 630aeaa79f00975952c453a254d6bb3921fb505fa013d322908f525ed281fc2d
DEBU[0007] successfully verified cached targets
DEBU[0007] Loading targets/notary_lu...
DEBU[0007] targets/notary_lu role has key IDs: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0007] verifying signature for key ID: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0007] successfully verified cached targets/notary_lu
DEBU[0007] Loading targets/releases...
DEBU[0007] targets/releases role has key IDs: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0007] verifying signature for key ID: 0040335ed560c37dd1fb40baf9bd3fa98c07e39242927c36ac8a41efd0834f2f
DEBU[0007] successfully verified cached targets/releases
NAME    DIGEST                                                              SIZE (BYTES)    ROLE
----    ------                                                              ------------    ----
1       74f634b1bc1bd74535d5209589734efbd44a25f4e2dc96d78784576a3eb5b335    527             targets/notary_lu

**Comment by shen3lu4** [comment]
I think the problem is because the image was signed with a delegation key. Today I removed the delegation key used to sign the image and the image becomes unsigned. Here is the command used:
docker trust signer remove <signer name> <gun>

The 'notary remove -p <gun> <tag>' command works on image not signed by a delegation key.

**Comment by geekzeng** [comment]
I had the same situation

The best way is to do 
`docker trust revoke <gun>:<tag>`

Otherwise you can also remote entire Trust Collection with
`notary  delete <gun> --remote`
But this will remove signature to all tag for this image

Kind regards
