### ISSUE TITLE
Harbor should use golang 1.14 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#10123]
Due to a regression issue in golang 1.13 <https://github.com/golang/go/issues/35722>, there is a performance degradation when using TLS 1.3.

**Comment by reasonerjt** [comment]
@renmaosheng 
We'll have to evaluate 1.14 before bumping up.

**Comment by reasonerjt** [comment]
golang 1.14 is not yet GAed, and per  golang/go#35722 it is fixed on the java side, so we probably should delay the bump up.

**Comment by wy65701436** [comment]
promote version to v1.14.5, https://github.com/goharbor/harbor/pull/12489
