### ISSUE TITLE
rename function issue

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#10120]
The function of rename is very strange, why can't I change it back to admin. If it is connected to the outside, is there a clearer prompt?
![image](https://user-images.githubusercontent.com/29826789/70106719-5de27000-167f-11ea-86d3-f5fbbbfe4498.png)

**Comment by reasonerjt** [comment]
This was introduced due to a historical issue that one customer has a user called `admin` in his LDAP, and he wants a workaround.
