### ISSUE TITLE
replication of private projects doesn't work

### ISSUE THREAD

**Issue by jbuamw** [goharbor/harbor#10161]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Whenever try to replicate private project between two Harbor instances it finishes with status Success - no resources need to be replicated. Once I make the project to be public, I'm able to replicate all repositories in that project. 
Source Harbor uses OIDC method for authentication. 

**Steps to reproduce the problem:**
1. Setup registry endpoint with user who has administrator rights in source Harbor or with robot account created with pull permissions on the project you want to replicate. Provider: Harbor
2. Make sure registry endpoint  status is Healthy. 
3. Create replication rule 
a) Source resource filter
- <source_project_name>/** or <source_project_name>/<repo_name>
- tag: empty
- label: empty
- resource: both
b) destination namespace: empty (empty project with the same name as source project exists on destination Harbor)
c) Trigger Mode: Manual
d) checked-in "Override" and "Enable rule" check-boxes
4) Run manually the replication rule
5) See the Status: Success - no resources need to be replicated

Once I make the project to be public, I'm able to replicate all repositories in that project. 

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.3]
- docker engine version: [18.09.2]

**Comment by marcelhintermann** [comment]
I have exactly the same problem.
If i look into the harbor log files, it seems like the listing of private repositories is not working.

For public repositories i see lines like:
`[DEBUG] [/replication/filter/filter.go:135]: "public_test/ubuntu" doesn't match the pattern "private_test/a*" of name filter, skip`

I don't see any similar message for private repositories.

**Comment by jarnfast** [comment]
I'm also facing this issue. Replication of private projects for OIDC backed users does not work.

**Comment by reasonerjt** [comment]
Fixed in https://github.com/goharbor/harbor/pull/12596

You'll be able to do the replication using the username you set for the OIDC user and the CLI secret.
