### ISSUE TITLE
using a certificate in Red Hat 7.7 with SELinux

### ISSUE THREAD

**Issue by finkr** [goharbor/harbor#10163]
disclaimer: I use docker 1.13.1 (not officially supported) shipped with Red Hat 7.7, with SELinux enabled

**Expected behavior**

running "prepare" should succeed when using a certificate

**Actual behavior:**

Running `bash prepare` fails with error (see full log below):

    FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/foo.exemple.com.key'

By running `bash -x prepare` , i noticed the failing command is:

    docker run --rm -v /root/HARBOR/harbor/input:/input:z -v /data:/data:z -v /root/HARBOR/harbor:/compose_location:z -v /root/HARBOR/harbor/common/config:/config:z -v /data/secret:/secret:z -v /:/hostfs:z goharbor/prepare:v1.9.3

**Steps to reproduce the problem:**
Follow the procedure [Configuring Harbor with HTTPS Access as described](https://github.com/goharbor/harbor/blob/master/docs/configure_https.md).

or simply:

    # docker run   -ti --rm  -v /:/hostfs:z busybox  ls -l /hostfs
    ls: can't open '/hostfs': Permission denied
    total 0

**Workarounds**

2 possible workarounds: 

- Modify `prepare` to execute docker with `--privileged`  [option](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/running_super_privileged_containers)
- Disable SELinux before running `prepare` (using `setenforce 0`)

**Versions:**
Please specify the versions of following systems.

- harbor version: harbor-online-installer-v1.9.3.tgz
- docker engine version: Docker version **1.13.1**, build 7f2769b/1.13.1  => (Red Hat 7.7)
- docker-compose version: 1.24.1, build 4667896b

**Additional context:**

harbor.yml file contains:

    https:
      # https port for harbor, default is 443
      port: 443
      # The path of cert and key files for nginx
      certificate: /data/cert/foo.exemple.com.crt
      private_key: /data/cert/foo.exemple.com.key

**Full log of `prepare` execution :**

    # bash prepare
    Clearing the configuration file: /config/log/logrotate.conf
    Clearing the configuration file: /config/log/rsyslog_docker.conf
    Generated configuration file: /config/log/logrotate.conf
    Generated configuration file: /config/log/rsyslog_docker.conf
    Traceback (most recent call last):
      File "main.py", line 64, in <module>
        main()
      File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "main.py", line 36, in main
        prepare_nginx(config_dict)
      File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
        render_nginx_template(config_dict)
      File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
        prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
      File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
        shutil.copy2(host_ngx_cert_key_path, real_key_path)
      File "/usr/lib/python3.6/shutil.py", line 257, in copy2
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/foo.exemple.com.key'

**Comment by anyuan95** [comment]
I got the same issue and I'm using 1.9.3 on CentOS 7.6.
I executed 'setenforce 0' but it still cannot mount "/" into the container.
Only 'docker run -privileged' works for me.
I wonder why 1.8.0 didnt need mount "/" but 1.9.0 do?
And, is this a bug?
