### ISSUE TITLE
support online non-blocking garbage collection (no need to be placed in read-only mode)

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10167]
We want to deliver this in 1.11, some key requirements include

- GC runs standard mark and sweep procedure and ensures nothing in use will be deleted
- GC will remove blobs(layers and manifests) from registry that are no longer referenced by an image manifest
- GC will remove untagged/dangling manifests（ie previous redis:latest sha image xxx is now replaced by image sha yyy after pushing new redis:latest, so xxx is now untagged and should get picked up by GC) - will this be part of our GC?
- can preview or ‘dry run’ GC to see how much disk space would be freed up and estimation of running time
- can run GC without setting Harbor in read-only mode, this means that user can still push / pull / delete images to that harbor instance.  There is no effect to end user in terms of performing operations on Harbor and no chance of any kind of image corruption
- drastically improve the performance of GC in terms of running time
- allow manual execution as well as scheduled tasking 
- allow disabling GC so it never runs
- support setting a time limit on the GC job so it never exceeds xx minutes 
- provide way for harbor admin to check if GC job is running (doesn't have to be in web console)
- keeps logs of GC jobs, with each showing #blobs deleted along with their digests

**Comment by xaleeks** [comment]
prd: https://docs.google.com/document/d/1oJpyiiTeAxC81ql6i30XpvCnn4QZEOQgtPpJQyRW-ew/edit

**Comment by xaleeks** [comment]
link to spec:
https://github.com/goharbor/community/pull/133

**Comment by xaleeks** [comment]
https://github.com/goharbor/harbor/issues/11534

**Comment by wy65701436** [comment]
close it as non-blocking GC is introduced in v2.1.0.
