### ISSUE TITLE
清理GC

### ISSUE THREAD

**Issue by xingxing9688** [goharbor/harbor#10160]
What can we help you?
你好，在清理gc 的时候，发现多了一个_uploads 这个目录，如果gc 清理碰到这个目录就会停止，这个目录可以自动清理么

**Comment by xingxing9688** [comment]
registry 的存储配置如下
storage:
  cache:
    blobdescriptor: redis
  $storage_provider_info
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true

**Comment by wy65701436** [comment]
please just refer to distribution document to enable purge, then to restart harbor, the registry will clean the `_uploads` regularly.
