### ISSUE TITLE
[Feature Request] Support multiple ldap domains for authentication.

### ISSUE THREAD

**Issue by pgkulkarn** [goharbor/harbor#10187]
Harbor currently supports LDAP authentication but for only one domain.
Can we please support authentication via multiple LDAP domains?

E.g. If we can configure following two LDAP domains:
LDAP domain 1 - ldap://ldap1.myCompany.com:3268
LDAP domain 2 - ldap://ldap2.myCompany.com:3268

Then users from both domains should be able to login.
Thank you!

**Comment by JerryCurl** [comment]
+1

**Comment by ludwig235** [comment]
Also this should make Harbor high available when this is used as secondary ldap server

**Comment by titou10titou10** [comment]
Seems similar to #6878
