### ISSUE TITLE
[QUESTION] how to use healthcheck api 

### ISSUE THREAD

**Issue by divramod** [goharbor/harbor#10205]
Hey, 

thx for the awesome project!

I don't know if its ok to post questions here, but i hope so.
Can someone give me a hint / direction or a link to the documentation of the new health check api?
i setup harbor in kubernetes and like to check if the different services are healthy.

thx in advance!

**Comment by wy65701436** [comment]
did you refer to the swagger?

**Comment by divramod** [comment]
hey, 

i am not really sure. i like to get to know / learn about the harbor api.
i need to create robots, projects, accounts and curl the health api.

i think swagger could tell me about all of that.

is there a officially deployed swagger instance for harbor somewhere or do i have to install harbor locally and configure swagger to know which api endpoints are in existance?

i also could not find something on https://goharbor.io/docs/

**Comment by divramod** [comment]
basically i need to know how to do curl requests against the api and how to set the auth tokens

**Comment by divramod** [comment]
i was able to find it under /devcenter

can be closed, thx
