### ISSUE TITLE
failed to get gc result: Failed to start GC: 500

### ISSUE THREAD

**Issue by zhanghan12** [goharbor/harbor#10203]
```
2019-12-09T06:28:09Z [INFO] [/jobservice/job/impl/gc/job.go:87]: start to run gc in job.
2019-12-09T06:28:12Z [ERROR] [/jobservice/job/impl/gc/job.go:90]: failed to get gc result: Failed to start GC: 500
```

```
harber version : 1.9.4
使用 阿里 oss 存储
```

```
# registryctl.log
```
<img width="954" alt="f60cecc81977a85a9135b273703d8fe" src="https://user-images.githubusercontent.com/24913492/70414129-1cddc780-1a94-11ea-91ca-593d19ad53d4.png">
<img width="948" alt="72e7e16b1df351c66614ba502b7fd55" src="https://user-images.githubusercontent.com/24913492/70414134-1fd8b800-1a94-11ea-9e64-395879850c31.png">

**Comment by zhanghan12** [comment]
harbor 1.7.4 升级到 1.9.4 出现的 500 ,  1.7.4 版本没有这个问题, 是  `failed to mark: oss: oss: failed to retrieve tags unknown repository` 导致的的吗, harbor 中这个库之前清理过.

**Comment by zhanghan12** [comment]
将 failed repository push 到 harbor 后可以执行 GC, 现在不确定是不是升级导致的, 感觉像是清理镜像时没有在数据库中删除对应的项目导致的.

**Comment by wy65701436** [comment]
can you refer to https://github.com/goharbor/harbor/issues/7945#issuecomment-498123934 and provide results?

**Comment by zhanghan12** [comment]
```sudo -E -u \#10000 registry garbage-collect --delete-untagged=true /etc/registry/config.yml```
执行这个命令, 发现有部分镜像没有 ,重新推送后, 可以继续CG
多谢

**Comment by ATAO-Y** [comment]
> `sudo -E -u \#10000 registry garbage-collect --delete-untagged=true /etc/registry/config.yml` 执行这个命令, 发现有部分镜像没有 ,重新推送后, 可以继续CG 多谢

@zhanghan12 你执行这个命令对现有harbor服务有影响，会出现服务不可用的情况吗
