### ISSUE TITLE
Field name displayed on the web portal

### ISSUE THREAD

**Issue by jixuju** [goharbor/harbor#10213]
After upgrading harbor from 1.6.0 to 1.7.0, field names will appear on the web portal, and then after upgrading from 1.7.0 to 1.9.3, more field names will appear on the web portal. Field names are all web portal elements added after 1.6.0, , as shown below:
![image](https://user-images.githubusercontent.com/16171790/70451423-4ae8f900-1ae0-11ea-9913-57efd52dd03d.png)
![image](https://user-images.githubusercontent.com/16171790/70451608-a1563780-1ae0-11ea-965b-3c9a1375675b.png)

**Steps to reproduce the problem:**
In harbor version, upgrade from 1.6.0 to 1.7.0 according to migration guide.md in release-1.7.0, and then upgrade from 1.7.0 to 1.9.3 according to migration guide.md in release-1.9.0

**Versions:**
- harbor version: v1.9.3-c80751b8
- docker engine version: 18.03.0-ce
- docker-compose version: 1.19.0

**Comment by wy65701436** [comment]
try to clean your browser's cache

**Comment by jixuju** [comment]
After clearing the cache, the problem is solved. Thank you
