### ISSUE TITLE
is that possible to expose harbor with context path

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#10227]
What can we help you?
hi,  we did some ingress configuration to expose harbor to sub-domain based as below, that works

harbor.domain.com

Now, we need to change it to context sub path like below, but it does not work from portal, could you give some advise if that could possible? thanks.

abc.com/harbor/

**Comment by danielzhanghl** [comment]
hi, Harbor is not ware of any context path, harbor portal access server endpoint /styles*   /runtime*  /images/* etc. for static resources. also it access API endpoint to interactive with Harbor server:

/api/  --> harbor core

/service/   ->harbor core

/chartrepo/  ->harbor core

etc.

if harbor portal could be award of its context path, for example, when harbor deployed under "myharbor":
abc.com/myharbor/


could portal request the static resource/API with a prefix of "myharbor"? like:

myharbor/styles*
myharbor/images*
myharbor/api/

**Comment by danielzhanghl** [comment]
hi Harborer, is there any comment on this request? 
it helps user to use a control nginx  proxy to distribute the request, when harbor is deployed together with other applications.

**Comment by vxavictor513** [comment]
Any update on this? Is it supported yet?

**Comment by danielzhanghl** [comment]
no need right now.
