### ISSUE TITLE
confused log in clair container

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#10222]
There are some confused logs `ls: /harbor_cust_cert: No such file or directory` for clair when it started.

Maybe these logs also exist in others containers.

**Comment by irLinja** [comment]
Same here!

**Comment by lazzio7** [comment]
hi,, same issue:

`[root@harbor-test harbor]# docker-compose ps
      Name                     Command                  State                                      Ports
---------------------------------------------------------------------------------------------------------------------------------------
chartmuseum         ./docker-entrypoint.sh           Exit 255
clair               ./docker-entrypoint.sh           Up (healthy)   6060/tcp, 6061/tcp
clair-adapter       /clair-adapter/clair-adapter     Exit 255
`

`[root@harbor-test harbor]# docker container ls|grep clair
10bcc1585351        goharbor/clair-photon:v2.1.1-v1.10.1                      "./docker-entrypoint…"   About an hour ago   Up 31 minutes (healthy)   6060-6061/tcp                                                         clair
`


`[root@harbor-test harbor]# cat clair.log
Feb 12 14:59:40 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
Feb 12 14:59:40 172.18.0.1 clair[9428]: {"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-02-12 13:59:40.709121"}
Feb 12 14:59:43 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
Feb 12 14:59:43 172.18.0.1 clair[9428]: {"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-02-12 13:59:43.862883"}
Feb 12 14:59:45 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
Feb 12 14:59:45 172.18.0.1 clair[9428]: {"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-02-12 13:59:45.453106"}
Feb 12 14:59:46 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
Feb 12 14:59:46 172.18.0.1 clair[9428]: {"Event":"pgsql: could not open database: dial tcp 172.19.0.2:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-02-12 13:59:46.937366"}
Feb 12 14:59:49 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
`

**Comment by lazzio7** [comment]
hi,

same here:



> [root@harbor-test harbor]# grep -w "ls: /harbor_cust_cert:" *
chartmuseum.log:Feb 12 14:59:36 172.18.0.1 chartmuseum[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 14:59:40 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 14:59:43 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 14:59:45 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 14:59:46 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 14:59:49 172.18.0.1 clair[9428]: ls: /harbor_cust_cert: No such file or directory
clair.log:Feb 12 15:39:08 172.18.0.1 clair[943]: ls: /harbor_cust_cert: No such file or directory
registryctl.log:Feb 12 14:59:34 172.18.0.1 registryctl[9428]: ls: /harbor_cust_cert: No such file or directory
registry.log:Feb 12 14:59:36 172.18.0.1 registry[9428]: ls: /harbor_cust_cert: No such file or directory

>

**Comment by lazzio7** [comment]
update:
when i move /etd/docker/key.json to ~ .. then stop-start docker-compose... clair is healthy also container, but  key.json was recreated probably, is there

`[root@harbor-test docker]# ll /etc/docker/
total 4
drwxr-xr-x 3 root root  35 Feb 12 14:43 certs.d
-rw------- 1 root root 244 Feb 12 16:29 key.json
`

**Comment by lazzio7** [comment]
solved,, turn off proxy or no_proxy in systemd conf...

**Comment by hicaro** [comment]
@lazzio7 I am having the same problem. I added my hostname to the `NO_PROXY` config in systemd. I followed this https://docs.docker.com/config/daemon/systemd/#httphttps-proxy process. 
The issue is still happening. Did you do anything else?

**Comment by lazzio7** [comment]
for http harbor:

> [root@harbor ~]# cat /etc/docker/daemon.json

{
"insecure-registries" : ["harbor.xxx.xx", "0.0.0.0"]
}


>[root@harbor ~]# cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://xxx.xxx.xxx.xxx:8888/"
Environment="no_proxy=harbor.xxx.xx"


for https harbor.. i had to turn off proxy ...
i have not findout, how to fix yet..
