### ISSUE TITLE
Log record lost after upgrade 1.6.3

### ISSUE THREAD

**Issue by jixuju** [goharbor/harbor#10236]
After upgrading from `1.4.0` or `1.5.0` according to `release-1.6.0/docs/migration_guide.md` to `1.6.3`, the projects, users, repository and other data are available, but the logs data is missing. For example, below:
![image](https://user-images.githubusercontent.com/16171790/70671865-79213100-1cb8-11ea-8022-b14d9362f0b7.png)

In the database backup of 1.4.0 and 1.5.0, logs are available, such as the following figure:
![image](https://user-images.githubusercontent.com/16171790/70671636-ac16f500-1cb7-11ea-8793-b99d5625bc07.png)

**Steps to reproduce the problem:**
According to the document of `release-1.6.0/docs/migration_guide.md`
upgrade harbor 1.4.0 directly to 1.6.3
or
Upgrade harbor 1.4.0 to 1.5.0, and then upgrade from 1.5.0 to 1.6.3

**Versions:**
- harbor version: 1.6.3
- docker engine version: 1.13.1
- docker-compose version: 1.19.0

**Additional context:**
The upgrade of harbor 1.1.2 to 1.3.0, then to 1.4.0, then to 1.5.0 does not cause this problem

**Comment by reasonerjt** [comment]
I'm sorry but this version is quite old that I don't think we have bandwidth to reproduce and fix it.
Marking it as `help wanted` to see if any community users have a clue.

**Comment by jixuju** [comment]
It has been resolved that the error of insert into is caused by the change of the field order in the access log. Adjust the field order of the old version of the table structure before migration:
```
alter table access_log modify username varchar(255) after log_id;
```
