### ISSUE TITLE
New SSL Certs for AWS RDS

### ISSUE THREAD

**Issue by KISStian** [goharbor/harbor#10235]
We have deployed Harbor via Helm with the use of RDS as the external database.  Currently SSL is not enabled and we want to turn it on.  However, AWS is rolling out new SSL certificates that will be applied to all instances if not done by end users prior to March 5, 2020.  I assume that the Harbor images will need to be updated with the new root CA certificates in order to accommodate this, if they haven't been already.  The AWS information regarding this change can be reviewed here: 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by reasonerjt** [comment]
Thanks @KISStian I'll double check to make sure the CA is in the truststore of the base image

**Comment by reasonerjt** [comment]
Still pending on photon dev team for confirmation, who is mostly in vacation

**Comment by reasonerjt** [comment]
I double checked with photon dev team seems the photon only plans to trust CA in "Mozilla CA Certificate Store":
https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/

I quickly checked it seems the root cert of RDS is not in the list.

@KISStian 
Could you clarify if you have tried enable RDS SSL before the rotation?  

In next version we plan to support inject any CA cert to any container in Harbor but that's not in the scope of 1.10.x

**Comment by KISStian** [comment]
To be honest, we did not enable SSL prior to the rotation.  I can do some testing with it to see if there are any issues, and if so, we will just leave it disabled for now.  Being able to inject any CA cert into the Harbor containers is a great feature and should solve the problem at hand.

**Comment by reasonerjt** [comment]
Thanks @KISStian
