### ISSUE TITLE
restart of Redis server will cause the restart of jobservice

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#10244]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Restart Redis, the jobservice will be restarted. actually it should not.

**Steps to reproduce the problem:**

Restart the Redis server

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
None.

**Comment by steven-zou** [comment]
The code work is done, pending for PR review.

Move to next SP 78

**Comment by reasonerjt** [comment]
Open till the change is cherry picked to 1.10.x
