### ISSUE TITLE
Error response from daemon:login attempt to http://XXX failed with status:502 Bad Gateway

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#10240]
I tried to add --insecure-registries=""to my configure file, and docker info:
Insecure Registries:
      192.168.149.123
but, when i docker login 192.168.149.123, it failed, and show 502

**Comment by tongying123456** [comment]
``docker info
Containers: 19
 Running: 9
 Paused: 0
 Stopped: 10
Images: 237
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-70-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.924GiB
Name: ubuntu
ID: OHIP:KPAU:ZY2I:ZAVV:SY4B:CLP4:FJ46:2S4C:REOM:S5YG:SH3Z:L5XL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 192.168.149.128
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false

WARNING: No swap limit support
root@ubuntu:/home/ty/Downloads/harbor3/make# docker login 192.168.149.128
Username: admin
Password: 
Error response from daemon: login attempt to http://192.168.149.128/v2/ failed with status: 502 Bad Gateway
????????????????????why

**Comment by demobin8** [comment]
@tongying123456 check harbor registry is running
`docker ps | grep registry`
`docker start registry`
