### ISSUE TITLE
go.mod file should be in upper folder

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#10251]
currently file go.mod is in src folder, which is not standard, it should be in root folder, or when other project import harbor project, it also need add src in module path
vendor folder also need move to root folder
cmd entrance should be moved out too
other things like web and tools also have their suggested folder name

a golang reference layout is https://github.com/golang-standards/project-layout

**Comment by reasonerjt** [comment]
I see this is a problem way more complicated than moving the content in `src/` and `go.mod` to the root.

We probably should first make sure the paths within `src/` have a better organization inside `src/` and sort out the folders out of `src/` according to a best practice, and then, move everything in `src/` to root.
