### ISSUE TITLE
Harbor v1.9.2  replicate registry from Ali cloud registry  to Harbor unsuccessful 

### ISSUE THREAD

**Issue by stefiane** [goharbor/harbor#10266]
replicate registry from Ali cloud registry  to Harbor through harbor ui.
error is below:
failed to fetch image: [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Connect timeout. Please set a valid ConnectTimeout. caused by: Get http://cr.cn-beijing.aliyuncs.com/repos: dial tcp 182.92.29.46:80: i/o timeout

**Comment by reasonerjt** [comment]
ali-cloud uses http?  Could you double check the setting?

**Comment by stefiane** [comment]
> ali-cloud uses http? Could you double check the setting?

no,use https.I configure endpoint registry use https。This url occur in the progress replicate registry

**Comment by stefiane** [comment]
> ali-cloud uses http? Could you double check the setting?

the replcation is always in progress。the image size is 100M，It's been a day

**Comment by bitsf** [comment]
Ali replicationadapter is provided by community effort, that we haven't test much. Can you send a test token to me that I can have a try.

**Comment by kofj** [comment]
@stefiane Hi, PLS check can you access cr.cn-beijing.aliyuncs.com in the `core` container via curl:

```
curl -v cr.cn-beijing.aliyuncs.com
```

If it is work, check your destination's configure:

![image](https://user-images.githubusercontent.com/3346673/71099922-10bddc80-21ef-11ea-8bdf-b56ff858d89f.png)

#### ⚠️NOTE: The **Access ID** field MUST  be `Access Key ID` and the **Access Secret** filed MUST be `Access Key Secret`

1. You can use the Access Key pair of the main account, which can be obtained from your aliyun user center page.

1. Or use a key pair of a sub-account in the [RAM (Resource Access Management)](https://ram.console.aliyun.com/), and the sub-account MUST have permissions: **AliyunContainerRegistryFullAccess**, **AliyunContainerRegistryReadOnlyAccess**.

I'll write a document/blog for the AliACR provider this weekend in detail.

**Comment by stefiane** [comment]
@kofj 
I check in the core container via curl:
![image](https://user-images.githubusercontent.com/23471111/71341884-20924380-2596-11ea-8797-ac6332ba64a3.png)
and,if I use sub-account in the ARM,the sub-account have permissions:AliyunContainerRegistryFullAccess, AliyunContainerRegistryReadOnlyAccess,the error is 
![image](https://user-images.githubusercontent.com/23471111/71342038-97c7d780-2596-11ea-9bc7-12c879bb5d0b.png)

and, I espect your blog .

**Comment by kofj** [comment]
Maybe same to this: #10331 .

**Comment by stefiane** [comment]
@kofj Yes, same situation, ‘In progress’ occur in my issue.
