### ISSUE TITLE
Unable to delete images from ECR

### ISSUE THREAD

**Issue by sanyu** [goharbor/harbor#10264]
**Expected behavior and actual behavior:**
Harbor 1.9.3 is setup to replicate images to ECR (and to delete images if these are deleted from Harbor). Replication works fine, but when I delete a tag, the tag is deleted from Harbor but deletion from ECR fails:

```
2019-12-14T10:53:33Z [INFO] [/replication/transfer/image/transfer.go:95]: client for source registry [type: harbor, URL: http://harbor-harbor-core, insecure: true] created
2019-12-14T10:53:33Z [INFO] [/replication/transfer/image/transfer.go:105]: client for destination registry [type: aws-ecr, URL: https://api.ecr.us-west-2.amazonaws.com, insecure: false] created
2019-12-14T10:53:33Z [ERROR] [/replication/transfer/image/transfer.go:367]: failed to delete the manifest of image XXX/releases/pause:3.1 on the destination registry: http error: code 404, message 404 page not found
```

Verified that the image existed in ECR:

```
$ aws ecr list-images  --repository-name 'XXX/releases/pause' --region us-west-2
{
     "imageIds": [
        {
            "imageTag": "3.1",
            "imageDigest": "sha256:fcaff905397ba63fd376d0c3019f1f1cb6e7506131389edbcb3d22719f1ae54d"
        }
    ]
}
```

Also verified that the image can be deleted using the same AWS credentials as Harbor:
```
$ aws ecr batch-delete-image --repository-name XXX/releases/pause --image-ids imageTag=3.1
{
    "failures": [],
    "imageIds": [
        {
            "imageTag": "3.1",
            "imageDigest": "sha256:fcaff905397ba63fd376d0c3019f1f1cb6e7506131389edbcb3d22719f1ae54d"
        }
    ]
}

$ aws ecr list-images  --repository-name 'XXX/releases/pause' --region us-west-2 
{
    "imageIds": []
}
```

**Steps to reproduce the problem:**

- Setup replication to ECR for one repository
- Push a new image/tag to that repository => tag is successfully replicated to ECR 
- Delete tag from Harbor => 404 Not found, image is not deleted from ECR

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.3

**Comment by bitsf** [comment]
I can reproduce this, will check it

**Comment by reasonerjt** [comment]
It's possible the access key does not have sufficient permission in IAM.

**Comment by sanyu** [comment]
@reasonerjt if you check my original comment, you'll see that I tested deleting the image using awscli with the same access key used by Harbor to verify that IAM permissions were ok. As you can see, it doesn't seem to be an IAM issue.

**Comment by bitsf** [comment]
yes, it doesn't IAM issue, it seems ECR not implement OCI registry delete API well, that when we call delete manifest API (describe as https://github.com/opencontainers/distribution-spec/blob/master/spec.md#delete-manifest), it will return 404.

![image](https://user-images.githubusercontent.com/188115/71886387-161ba080-3177-11ea-913f-ee2b7a188e05.png)
![image](https://user-images.githubusercontent.com/188115/71886415-203d9f00-3177-11ea-9c43-1345472c0f8f.png)
