### ISSUE TITLE
 jobservice log ---> Serve http request 'GET /' failed with error

### ISSUE THREAD

**Issue by spwangxp** [goharbor/harbor#10263]
[ERROR] [/jobservice/api/router.go:75]: Serve http request 'GET /' failed with error: {"code":10011,"message":"unauthorized","details":"header 'Authorization' missing"}

actually all function works very well, but i find there was a ERROR in jobservice.log. 
there was an confusing sign, **web ui contains two language at the same time**，no matter how i restart harbor. 

I‘ve trapped for two weeks,hope someone colud give me some advise, thanks all

Versions:
Please specify the versions of following systems.

    harbor version: [v1.9.3]
    docker engine version: [19.03.5~3]
    docker-compose version: [1.25.0]

Additional context:
None

**Comment by reasonerjt** [comment]
@spwangxp why does this error impact your work?  It looks like you try to curl jobservice API?  This is not allowed in Harbor's installation.

**Comment by spwangxp** [comment]
thank for your reply, actually I didn't try to curl this api. i just want to split harbor to different hosts. it works well, but the error appeared. 
and when i use cliar , https://github.com/bitnami/charts/issues/1543 also appeared. may i know when will it be fixed?

**Comment by reasonerjt** [comment]
That error in jobservice may be expected because the `HEALTHCHECK` calls `http://127.0.0.1:8080/api/v1/stats`.  

Not sure if jobservice the log of jobservice is responding this request.

I'll let @ywk253100 and @steven-zou comment.

**Comment by spwangxp** [comment]
thanks，it did solved my issue.
and “web ui contains two language at the same time” due to the browser cache.

**Comment by reasonerjt** [comment]
OK thanks, I'm closing this one.
