### ISSUE TITLE
Would it be possible to make obfuscation of registry access_secrets configurable?

### ISSUE THREAD

**Issue by bt-lemery** [goharbor/harbor#10279]
I'm currently working on a Puppet type and provider to manage Harbor registry endpoints (https://github.com/bt-lemery/puppet-harbor/tree/feature/add_harbor_registry_type_provider).  Because the API always returns '*****' for a registry's access secret, each time Puppet runs it wants to update the access_secret parameter for each of my defined registry endpoint resources.  I'm not quite sure what to do about this.  Would it be possible to add a configuration setting that would allow Harbor to bypass the 'hideAccessSecret' function (https://github.com/goharbor/harbor/blob/master/src/core/api/registry.go#L158) when returning registry data via API call?

**Comment by ywk253100** [comment]
No, the password/secret shouldn't be returned back for the security issue

**Comment by bt-lemery** [comment]
I understand the security implications, which is why I was suggesting it be made a setting to explictly opt-in.  For the time being I've updated my type/provider to allow the setting of a username/password at resource creation and then not managing the credentials after that point.  Thanks.
