### ISSUE TITLE
Change has_admin_role in json response

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#10274]
Previously, there is a json field: has_admin_role
It is changed to
sysadmin_flag || admin_role_in_auth

The sysadmin_flag indicate the user is authorized with admin role in Harbor DB
the admin_role_in_auth indicate the user is authorized with the admin in external authenticator, LDAP etc.

Related Issue: #10012

And the user information should only display the privilege grant in Harbor DB (sysadmin_flag)

<img width="1018" alt="Screen Shot 2019-12-16 at 5 32 37 PM" src="https://user-images.githubusercontent.com/2696760/70895609-38b01300-202a-11ea-99fb-995c12a74bfa.png">

**Comment by reasonerjt** [comment]
@stonezdj how about we leave the `has_admin_role` and introduce a new one?  It will require less change in the UI.

In particular, I think using `has_admin_role` to represent the **combined** maybe make more sense here

**Comment by jwangyangls** [comment]
1.administrition list : sysadmin_flag || admin_role_in_auth;
2.sysadmin_flag
![image](https://user-images.githubusercontent.com/29826789/70964999-18836100-20c9-11ea-88fb-7dc318657500.png)

**Comment by jwangyangls** [comment]
fix in #10340
