### ISSUE TITLE
replication does not work

### ISSUE THREAD

**Issue by ysicing** [goharbor/harbor#10273]
Two instances, one hosted in aliyun, one in the Intranet.

After configuring the replication rules, aliyun does not appear to be synchronized

```
internal.hub.com --(replication)--> external.hub.com (aliyun)

version: v1.10.0
```

## internal.hub.com

![image](https://user-images.githubusercontent.com/8605565/70891178-b15ea180-2021-11ea-9a85-06d66e63987b.png)

![image](https://user-images.githubusercontent.com/8605565/70891398-1fa36400-2022-11ea-832d-6d4bb041dfa2.png)

## external.hub.com

nothing

**Comment by reasonerjt** [comment]
@ysicing is the Harbor instance running in aliyun using aliyun oss?
Could you check the storage to confirm if the blobs are uploaded?

**Comment by ysicing** [comment]
@reasonerjt storage using aliyun NFS.There's some blobs in the storage, but no docker images in harbor

**Comment by bitsf** [comment]
#10266 also ali replicator problem

**Comment by ysicing** [comment]
@bitsf  the reasons seem to be different.

**Comment by bitsf** [comment]
@kofj please have a look first, I tested with 1.10, seems auth not work

**Comment by kofj** [comment]
@bitsf It different to #10266.

@ysicing Can you show we the config of destination registry in Harbor ? Maybe you mistaken configured adapter of the destination registry.

**Comment by ysicing** [comment]
![image](https://user-images.githubusercontent.com/8605565/71080558-59ae6a80-21c8-11ea-8004-42f09608eb3d.png)

![image](https://user-images.githubusercontent.com/8605565/71080642-85c9eb80-21c8-11ea-9ecd-267014e3093d.png)

![image](https://user-images.githubusercontent.com/8605565/71080680-9b3f1580-21c8-11ea-8e04-4d0177763312.png)

![image](https://user-images.githubusercontent.com/8605565/71080775-c88bc380-21c8-11ea-94c4-57401429a989.png)

**Comment by ysicing** [comment]
@kofj 资源过滤器是否配置结果都一样。但是如果配置资源过滤器`library/`,同步任务为0，不配置同步状态如刚开始的issue一样

**Comment by kofj** [comment]
> @reasonerjt storage using aliyun NFS.There's some blobs in the storage, but no docker images in harbor

According this, maybe the `Docker Registry` component NOT notified or notify harbor's core failed. So, you can not find any repository in the portal.
Pls check core's log, if Registry notify core success, you can find  access log like this:
![image](https://user-images.githubusercontent.com/3346673/71103115-7e203c00-21f4-11ea-96e7-a83b70463dac.png)

**Comment by ysicing** [comment]
@kofj 

```
Dec 19 11:14:33 bogon core[411]: 2019/12/19 03:14:33 #033[1;44m[D] [server.go:2774] |   192.168.64.7|#033[42m 200 #033[0m|    902.843µs|   match|#033[46m POST    #033[0m /service/notifications   r:/service/notifications#033[0m
Dec 19 11:14:33 bogon core[411]: 2019/12/19 03:14:33 #033[1;44m[D] [server.go:2774] |   192.168.64.9|#033[42m 200 #033[0m|   32.32613ms|   match|#033[44m GET     #033[0m /v2/common/nginx/manifests/centos-201911081550   r:/v2/*#033[0m
Dec 19 11:14:33 bogon core[411]: 2019/12/19 03:14:33 #033[1;44m[D] [server.go:2774] |   192.168.64.7|#033[42m 200 #033[0m|    997.227µs|   match|#033[46m POST    #033[0m /service/notifications   r:/service/notifications#033[0m
```

![image](https://user-images.githubusercontent.com/8605565/71141999-f3215f00-2250-11ea-88f5-f436c794eea3.png)

Is the source as normal as the target?

**Comment by bitsf** [comment]
Is this issue fixed ?

**Comment by ysicing** [comment]
@bitsf  It doesn't seem to solve the issue.

**Comment by ysicing** [comment]
Internal network problem
