### ISSUE TITLE
Improvement of API for creating replication policy

### ISSUE THREAD

**Issue by BIAOXYZ** [goharbor/harbor#10272]
As discussions in this [slack thread](https://app.slack.com/client/T08PSQ7BQ/CC1E09J6S/thread/CC1E09J6S-1575828714.401100), I found that creating a replication policy via Harbor API requires that you must ***explicitly*** include `id of the destination registry` in json data. This seems neither convenient nor intuitive. So I suggest to make id an ***optional*** item.

# without id

> harbor2:~ # curl -u admin:Harbor12345 -X POST -H 'Content-Type: application/json' --data '{"name":"replicationpolicy1", "dest_registry":{"name":"harbor4", "type":"harbor", "url":"http://30.0.1.34", "credential":{"type": "basic", "access_key":"admin", "access_secret":"Harbor12345"}}, "enabled": false, "trigger": {"type": "manual"}}' harbor2/api/replication/policies
>> {"code":400,"message":"src_registry, dest_registry one of them should be empty and the other one shouldn't be empty \n"}

# with id

> harbor2:~ # curl -u admin:Harbor12345 -i -X POST -H 'Content-Type: application/json' --data '{"name":"replicationpolicy1", "dest_registry":{"id":1, "name":"harbor4", "type":"harbor", "url":"http://30.0.1.34", "credential":{"type": "basic", "access_key":"admin", "access_secret":"Harbor12345"}}, "enabled": false, "trigger": {"type": "manual"}}' harbor2/api/replication/policies
>>
  ```console
  HTTP/1.1 201 Created
  Server: nginx
  Date: Sat, 14 Dec 2019 06:08:32 GMT
  Content-Length: 0
  Connection: keep-alive
  Location: /api/replication/policies/3
  Set-Cookie: sid=20e1091022191f7e5c05ec771f3b8a4e; Path=/; HttpOnly
  X-Frame-Options: DENY
  Content-Security-Policy: frame-ancestors 'none'
  
  harbor2:~ # 
  ```

**Comment by bitsf** [comment]
we should consider query registry id from name auto in order to make the api more ease and consistent, or at least make the error code more accurate.
Even we don't want to auto set the id, we still need to verify the id and the name consistency, so the query step should not be cut off

**Comment by reasonerjt** [comment]
If id is required in the request body we should only need id to avoid inconsistency.

**Comment by BIAOXYZ** [comment]
I agree that at least at present, the error message is actually inaccurate. So the smallest change is to make the error message more clear. For other changes, I do not know a lot about their implementation difficulty (now I am just in the level of using harbor), or I can try to make some contribution w.r.t this?

**Comment by MaxRink** [comment]
This is still the case with Harbor 2.0.2

**Comment by pierrevanrensburg** [comment]
I agree that this is inconvenient and not intuitive!  Harbor what is the state of this?
