### ISSUE TITLE
Move to Chart Museum v0.11.0

### ISSUE THREAD

**Issue by jkjell** [goharbor/harbor#10298]
The new version of Chart Museum will allow the storage of Helm v3 (v2 API) charts in chart museum.  Currently that functionality doesn't exist.

https://github.com/helm/chartmuseum/releases/tag/v0.11.0

**Comment by reasonerjt** [comment]
As in v2.0 we will suggest h3 user to push chart as oci artifact.
This is no longer a P0 for 2.0

**Comment by geneliu** [comment]
I use goharbor/chartmuseum-photon:v2.3.0 and get the error of helm v3 push. I wonder anybody knows what version of chartmuseum is in goharbor/chartmuseum-photon:v2.3.0 ?
