### ISSUE TITLE
Notary multisignature 

### ISSUE THREAD

**Issue by dar9468** [goharbor/harbor#10297]
Hello!

I would like to know how it is possible to create certificates for each user so that notaries check. By default there is only one certificate.

**Comment by ywk253100** [comment]
Don't get your point, could you explain it with more detail?

**Comment by dar9468** [comment]
I need each user to have their own signature

**Comment by dar9468** [comment]
After creating user certificates based on rutovye from harbor, docker images are signed only root
![Screenshot from 2019-12-18 13-14-27](https://user-images.githubusercontent.com/17763421/71077401-661acf00-2198-11ea-8685-f1d5450d94a2.png)

**Comment by dar9468** [comment]
![Screenshot from 2019-12-18 13-21-49](https://user-images.githubusercontent.com/17763421/71077923-6bc4e480-2199-11ea-8c5c-b38ac1069a44.png)

**Comment by dar9468** [comment]
Login was made with this use

**Comment by dar9468** [comment]
After added DOCKER_CONTENT_TRUST and DOCKER_CONTENT_TRUST_SERVER
![Screenshot from 2019-12-18 13-28-26](https://user-images.githubusercontent.com/17763421/71078403-6320de00-219a-11ea-9139-7beeaa2be15c.png)

**Comment by dar9468** [comment]
Config Harbor:
![Screenshot from 2019-12-18 13-31-41](https://user-images.githubusercontent.com/17763421/71078612-ce6ab000-219a-11ea-993e-897c48138648.png)

**Comment by dar9468** [comment]
It seems the problem has been resolved, but now the question is how in (Notari) Harbor you can delete the initialization keys. The keys were deleted from the local machine. And now the error

ERRO[0000] couldn't remove target from targets: could not find necessary signing keys, at least one of these keys must be available
