### ISSUE TITLE
where can i see the image id in UI

### ISSUE THREAD

**Issue by rasine** [goharbor/harbor#10293]
Can i see the docker image id in UI
![image](https://user-images.githubusercontent.com/5775306/70988661-35398c00-20fd-11ea-824e-31b522b8466a.png)

![image](https://user-images.githubusercontent.com/5775306/70988760-569a7800-20fd-11ea-92b7-00c47d63cd38.png)

**Comment by ywk253100** [comment]
The image ID if the digest of config layer, you cannot see it in harbor UI. You can get the digest of the image by clicking the `COPY DIGEST` button, but it isn't the image ID
