### ISSUE TITLE
But an error occurred when I pushed the mirror to the private repository

### ISSUE THREAD

**Issue by binxiao1981** [goharbor/harbor#10309]
I deployed private harbor and can login to the harbor.i has disabled port(443) and https in the harbor.yml file.  
at the same time, I had add { "insecure-registries": [ "192.168.40.130:8080"] } to /etc/docker/daemon.json.
[root@lc002 harbor]# cat /etc/docker/daemon.json
{ "insecure-registries": [ "192.168.40.130:8080"] }
[root@lc002 harbor]# docker login 192.168.40.130:8080
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

[root@lc002 ~]# docker push 192.168.40.130/dev/nginx:v1
The push refers to repository [192.168.40.130/dev/nginx]
Get https://192.168.40.130/v2/: dial tcp 192.168.40.130:443: connect: connection refused.

But an error occurred when I pushed the mirror to the private repository,ERROR WRITING INITBPS
The push refers to repository [192.168.40.130/dev/nginx]
Get https://192.168.40.130/v2/: dial tcp 192.168.40.130:443: connect: connection refused.

How can I solve this error?

**Comment by ywk253100** [comment]
Missing the port `8080` when pushing?
