### ISSUE TITLE
install harbor 1.9.3 [Step 2]: preparing environment ... errors

### ISSUE THREAD

**Issue by sunhuaxu** [goharbor/harbor#10308]
docker version: Docker version 18.09.9, build 039a7df9ba
docker-compose version: 1.25.0
set harbor.yml  complete

./install.sh --with-clair

[Step 2]: preparing environment ...
prepare base dir is set to /data/harbor
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 32, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 91, in parse_yaml_config
    config_dict['cert_path'] = https_config["certificate"]
KeyError: 'certificate'

**Comment by ninjadq** [comment]
did you set the `certificate` in the https section?

**Comment by sunhuaxu** [comment]
mkdir -p /etc/harbor
cd  /etc/harbor

openssl req \
    -newkey rsa:4096 -nodes -sha256 -keyout harbor.key \
    -x509 -days 3650 -out harbor.crt \
    -subj "/C=CN/ST=HangZhou/L=XS/O=k8s/OU=System/CN=harbor"

openssl req \
    -newkey rsa:4096 -nodes -sha256 -keyout harbor-key.key \
    -out harbor-key.csr \
    -subj "/C=CN/ST=HangZhou/L=XS/O=k8s/OU=System/CN=192.168.123.106"

harbor.yaml
certificate: /etc/harbor/harbor.crt
private_key: /etc/harbor/harbor-key.key

**Comment by ninjadq** [comment]
please check the spaces in your YAML file.

**Comment by iqoyyiml** [comment]
follow this [link](https://www.techrepublic.com/article/how-to-install-harbor-on-ubuntu-server-18-04/) to create self signed certificate and make sure harbor.yaml look like this

`hostname: myharbor.id

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 80

# https related config
https:
  # https port for harbor, default is 443
  port: 443
  # The path of cert and key files for nginx
  certificate: /home/admin/xxx/cert/ca.crt
  private_key: /home/admin/xxx/cert/ca.key
`
