### ISSUE TITLE
chart version summary design

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#10301]
The display of the table in dark mode is very strange, can you help us design its color matching.
env:https://10.192.162.161
![image](https://user-images.githubusercontent.com/29826789/71056064-d7578380-2192-11ea-902e-7a3a3a77aa49.png)
![image](https://user-images.githubusercontent.com/29826789/71056071-df172800-2192-11ea-8812-2477629f4ada.png)

**Comment by catchups** [comment]
What kind of harbor version do you use?
