### ISSUE TITLE
"invalid bearer token format" when replicating from quay.io with robot-account

### ISSUE THREAD

**Issue by mfld** [goharbor/harbor#10317]
Hello,

My attempts to replicate images from quay result in "invalid bearer token format".
My apologies if I am missing something obvious.

harbor Version v1.10.0-6b84b62f
docker-compose version 1.24.1, build 4667896b

Steps to reproduce.
registries settings:
-  Provider: quay.io
- Name: my quay
- Endpoint URL: https://quay.io
- Access ID: myorganization+user
- Access Secret: my-secret

Replications:
- Name: my quay
- Source registry: my quay-https://quay.io
- Source resource filter: quay.io/myorganization/repository/**
- Tag: **
- Resource: Image
- destination namespace: myorganization
- trigger mode: manual
- override and enable rule ticked.

The result is "invalid bearer token format" even when Access ID omits "myorganization+", encapsulating the entire field with quotes,  or escaping the plus-character with \. However when leaving the Access ID field blank, the result is successful, but no images are replicated.

==> /var/log/harbor/core.log <==
Dec 19 11:39:17 172.29.0.1 core[11160]: 2019-12-19T10:39:17Z [ERROR] [/replication/operation/controller.go:108]: the execution 112 failed: failed to fetch image: http error: code 401, message {"error": "Invalid bearer token format"}

Perhaps the documentation could be more clear?

Please advice.
Best regards.

**Comment by chlins** [comment]
@mfld The reasons for this problem is due to the quay pull mirror interface and create organizations use different interface and different authorization, maybe you can use docker-registry adapter as replacement with your repository robot account.
