### ISSUE TITLE
Problems with Upgrading from v1.9.3 to v.1.10.0

### ISSUE THREAD

**Issue by MatthiasHertel** [goharbor/harbor#10318]
hi there,

I upgraded harbor from v1.9.3  to v1.10.0 but the migration is not working correctly? it occurse some failures in locale settings , i guess that comes from the database cause the migration failed on it ? (see screenshot below).

![image](https://user-images.githubusercontent.com/8426566/71169336-ff111f00-2258-11ea-9b20-0de70274a76b.png)

i did the following steps, it works but the migration step (see no.5 in https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md#upgrading-harbor-and-migrating-data) failed with:

```
$ docker run -it --rm -v harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.10.0 --cfg up
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Skip cfg up as no harbor.cfg in the path.
```

for further informations i did the following upgrade procedure from https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md

here are all commands from the history:
```
# stop the containers
$ docker-compose down

# backup whole /data directory (database included)
$  mkdir -p /backup/harbor/data
$  cp -r /data /backup/harbor/data/data_2019_12_19
$  du -sh /backup/harbor/data/data_2019_12_19

# backup harbor directory
$  mv harbor harbor_2019_12_19

# fetch new version
$ tar xf harbor-offline-installer-v1.10.0.tgz
$ cd harbor
$ docker image load -i harbor/harbor.v1.10.0.tar.gz

# tailored the harbor.yml (setup version to _version:v.1.10)
$ diff harbor/harbor.yml harbor_2019_12_19/harbor.yml
$ cp harbor/harbor.yml harbor/harbor.yml_orig
$ cp harbor_2019_12_19/harbor.yml harbor/harbor.yml
$ vi harbor/harbor.yml

# run migration via harbor-migrator
$ docker run -it --rm -v harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.10.0 --cfg up

# reinstall harbor
$ ./install.sh --with-clair --with-chartmuseum
$ docker-compose ps
$ watch -x docker-compose ps
```

how can i be sure that the migration was successful?
and why is it so difficult to upgrade a minor version ?
i guess the migration should be handled by the application itselfs and not over an external app (harbor-migrator) or did i something wrong ?

thanks for help
sincerly
matthias

**Comment by MatthiasHertel** [comment]
ok the issue with l10n was a simple client cache problem (maybe a manifest file to prevent cache issues like that)

the failing migration is still weird

**Comment by ywk253100** [comment]
@MatthiasHertel Please use the doc on 1.10 branch: https://github.com/goharbor/harbor/blob/release-1.10.0/docs/migration_guide.md

@ninjadq I think the fix should be cherry-picked into master branch? https://github.com/goharbor/harbor/pull/10212

**Comment by cafeliker** [comment]
@ywk253100 the doc on 1.10 branch: https://github.com/goharbor/harbor/blob/release-1.10.0/docs/migration_guide.md says " This guide covers upgrade and migration to version 1.9.0." - is it for 1.10.0?

**Comment by MatthiasHertel** [comment]
whoops your are absolutely right .... this guide does not refer to an upgrade from 1.9.3 to 1.10 ... 

but is there something to know if i want upgrade from 1.9.3 to 1.10 ... so i can setup the new version tags in the rendered docker-compose.ym and run a simple docker-compose pull and docker-compose build ?

i guess a **general upgrade guide** to keep the community on the head is a good approach.

and rename this guide to a special upgrade cause of breaking changes ....

**Comment by olcayseker** [comment]
Upgraded from 1.8.X to 1.10 and now some part of UI become useless. Here is some screenshots.
Any suggestions about how to fix this?

![hrbr_issue1](https://user-images.githubusercontent.com/776387/71464853-ef9b5400-27cb-11ea-94b5-8203218e63aa.png)
![hrbr_issue2](https://user-images.githubusercontent.com/776387/71464854-f2964480-27cb-11ea-9f01-7831c5f0bfc8.png)
![hrbr_issue3](https://user-images.githubusercontent.com/776387/71464855-f4f89e80-27cb-11ea-89ff-cf27d3cf1684.png)
![hrbr_issue4](https://user-images.githubusercontent.com/776387/71464857-f6c26200-27cb-11ea-8a80-4cf8c2a7d232.png)

**Comment by MatthiasHertel** [comment]
@olcayseker  for me it works with disable cache reload, the problem is that the static files are cached and reload the site fix this for me.

**Comment by olcayseker** [comment]
Couldnt find any info about disabling cache reload. Can you point me out how i can do that?

**Comment by MatthiasHertel** [comment]
the cache failure is on the clientside ... u can simply remove all cache from client or test it with open the website in inknognito modus in your browser

**Comment by olcayseker** [comment]
@MatthiasHertel  Doh! Thanks for the info. Everything seems ok now.

**Comment by ninjadq** [comment]
Please refer to the doc on version 1.10
