### ISSUE TITLE
Consider not deprecating http

### ISSUE THREAD

**Issue by smekkley** [goharbor/harbor#10310]
With the latest harbor you get the following if https is disabled.
`WARNING:root:WARNING: HTTP protocol is insecure. Harbor will deprecate http protocol in the future. Please make sure to upgrade to https`

Let's not deprecate it for the following reasons.  I am talking about only core components, namely core and portal.
1. HSTS
2. LB setup where LB terminates HTTPS.
3. For testing purpose without certificate.

**Comment by xaleeks** [comment]
we have had a lot of discussions around this and this be will an option just not recommended, especially for production environments.  Your 3. is the main reason we are keeping it.  It's also a cncf mandated best practice that no transmission of hashes (ie digests) be carried out over non https.  @smekkley

**Comment by smekkley** [comment]
Thanks a lot for sharing the info. @xaleeks
