### ISSUE TITLE
 get token error from  harbor using OAuth2

### ISSUE THREAD

**Issue by damozhiying** [goharbor/harbor#10316]
[Docker Registry v2 authentication using OAuth2](https://github.com/docker/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/auth/oauth.md)

get token error from harbor using oauth2,error info is harbor xsrf prevent get token

![QQ截图20191219210010](https://user-images.githubusercontent.com/10277950/71175450-8d5dc300-22a2-11ea-955d-86a98f135346.png)

![image](https://user-images.githubusercontent.com/10277950/71162199-c0de2480-2285-11ea-87a9-4615d6b2168a.png)

**Comment by damozhiying** [comment]
@reasonerjt 
@heww

**Comment by ywk253100** [comment]
Remove the cookie header

**Comment by damozhiying** [comment]
@ywk253100 
http header not contain cookie
![image](https://user-images.githubusercontent.com/10277950/71223091-be271200-230d-11ea-9528-fa48e05cf551.png)

**Comment by damozhiying** [comment]
use harbor swagger api  test after login
![image](https://user-images.githubusercontent.com/10277950/71225069-56bf9100-2312-11ea-97f3-734a043b4035.png)

**Comment by damozhiying** [comment]
@ywk253100  can you give some suggest or  demo code

**Comment by damozhiying** [comment]
@reasonerjt i guess harbor not achieve **Docker Registry v2 authentication using OAuth2** api,
[Docker Registry v2 authentication using OAuth2](https://github.com/docker/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/auth/oauth.md)
