### ISSUE TITLE
After upgrade to version 1.10, scan failed with error: "scan controller: scan: create report: check existence of report: pq: column t0.requester does not exist"

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#10328]
harbor Version v1.10.0-6b84b62f 

I have upgrade Harbor to 1.10 release version last week, but looks scan request can't be sand to adapter. by tracking core log. I have below error message :
2019-12-23T02:18:23Z [DEBUG] [/core/service/notifications/registry/handler.go:252]: receive an event:
----ID: 3755f3c2-5cc6-43b0-a7f0-8ae926591379
----target: goharbor/harbor-core:dev
----digest: sha256:70355085a5c40a0d917e0ced9c7f0b77fed8ca8f42920570c43386bc1e563b6d
----action: pull
----mediatype: application/vnd.docker.distribution.manifest.v2+json
----user-agent: harbor-registry-client
2019/12/23 02:18:23 [D] [server.go:2774] |  172.20.234.70| 200 |   3.279254ms|   match| POST     /service/notifications   r:/service/notifications
2019/12/23 02:18:25 scan controller: scan: create report: check existence of report: pq: column t0.requester does not exist
**2019-12-23T02:18:25Z [ERROR] [/common/api/base.go:233]: scan API: scan: scan controller: scan: create report: check existence of report: pq: column t0.requester does not exist: create report: check existence of report: pq: column t0.requester does not exist
2019-12-23T02:18:25Z [ERROR] [/common/api/base.go:73]: POST /api/repositories/goharbor/harbor-core/tags/dev/scan failed with error: {"code":500,"message":"Internal Server Error"}
2019/12/23 02:18:25 scan controller: scan: create report: check existence of report: pq: column t0.requester does not exist**
2019/12/23 02:18:25 [D] [server.go:2774] | 172.20.233.248| 500 | 2.183336393s|   match| POST     /api/repositories/goharbor/harbor-core/tags/dev/scan   r:/api/repositories/*/tags/:tag/scan

does that means DB upgrade failed? how to fix it...

**Comment by cafeliker** [comment]
Is there a tool to valid if the database and schema is good or not?

**Comment by steven-zou** [comment]
Obviously, the database schema is not upgraded correctly. Please check if your upgrading process is aligned with the upgrading document.

@cafeliker

**Comment by steven-zou** [comment]
> Is there a tool to valid if the database and schema is good or not?

@cafeliker 

Not get your point. I think if the migration is successfully down, it should confirm the schema is upgraded. An additional validation tool may not be necessary.

**Comment by steven-zou** [comment]
@cafeliker 

For the upgrading, could you please provide more information?  From which version to 1.10? What are the operations(commands) you did for upgrading? Any problems or errors occurred?

**Comment by MaGaoju** [comment]
I'm using helm upgrade. there is NO ERROR during upgrade process. old version is Version v1.10.0-eba1a01a . new version : Version v1.10.0-6b84b62f

**Comment by MaGaoju** [comment]
Hi guys, update DB based on the https://github.com/goharbor/harbor/blob/master/make/migrations/postgresql/0015_1.10.0_schema.up.sql

update scan_report table, add the "requester" and apply below changes:
/* Add revision and status code columns for admin job table */
ALTER TABLE admin_job ADD COLUMN revision BIGINT DEFAULT 0;
ALTER TABLE admin_job ADD COLUMN status_code INTEGER DEFAULT 0;

everything works now. 


thanks!
