### ISSUE TITLE
Full scan of huge number of images finally fails with "parse token error, token is expired by 3m5s"

### ISSUE THREAD

**Issue by kumy** [goharbor/harbor#10325]
When launching a full clair scan of all our images (> 25000), only the first images scanned in the first ~30min are processed. Then all remaining images scan fails with errors:
```
 2019/12/20 10:00:51 #033[1;44m[D] [server.go:2774] |    172.16.4.30|#033[42m 200 #033[0m|    2.87953ms|   match|#033[46m POST    #033[0m /service/notifications   r:/service/notifications#033[0m
 2019/12/20 10:00:51 #033[1;44m[D] [server.go:2774] |    172.16.4.29|#033[42m 200 #033[0m|  17.222827ms|   match|#033[46m POST    #033[0m /service/notifications/jobs/scan/fafd8c17-230a-11ea-8310-0242ac100433   r:/service/notifications/jobs/scan/:uuid#033[0m
 2019/12/20 10:00:51 #033[1;44m[D] [server.go:2774] |    172.16.4.31|#033[43m 401 #033[0m|  56.651688ms|   match|#033[44m GET     #033[0m /v2/xxxxx/manifests/sha256:96915dbcdfba2eed45dbd0694aef541af62f3408f73b1297437d3266a3xxxxxx   r:/v2/*#033[0m
 2019-12-20T10:00:51Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is expired by 3m6s
 2019-12-20T10:00:51Z [ERROR] [/core/middlewares/regtoken/handler.go:51]: failed to decode reg token: token is expired by 3m6s, the error is skipped and round the request to native registry.
```

**Expected behavior and actual behavior:**
All images should be processed, if the token is expired it should be renewed for the process to continue

**Steps to reproduce the problem:**
* have many images in registry
* Go to Administration -> Interrogation Services -> Vulnerability
* click "scan"

**Versions:**
- harbor version: 1.10.0
- docker engine version: 18.09.2

**Comment by wy65701436** [comment]
it must be caused by the expiration of the robot account used by the scanner, it's 30 mins.

@steven-zou, can we set the expiration at somewhere? I suppose that it's not hard coded.

**Comment by kumy** [comment]
Raising the expiration time is in my opinion only a workaround, as it must be re-evaluated regularly as the number of images increase. An automatic token refresh would be a better solution as we'll don't have to worry about it.

**Comment by steven-zou** [comment]
> Raising the expiration time is in my opinion only a workaround, as it must be re-evaluated regularly as the number of images increase. An automatic token refresh would be a better solution as we'll don't have to worry about it.

Agree refreshing token would be a better solution! @kumy 

But that's not as simple as we're thinking, we need to check the relevant details of the option.

**Comment by steven-zou** [comment]
> it must be caused by the expiration of the robot account used by the scanner, it's 30 mins.
> 
> @steven-zou, can we set the expiration at somewhere? I suppose that it's not hard coded.

@wy65701436 

The Clair scanner is using the bearer token whose expiration time is configured at the system configurations.

@heww 
Let's take a look and see if we can find a better way to refresh the token automatically.
