### ISSUE TITLE
Replication between Harbors

### ISSUE THREAD

**Issue by dar9468** [goharbor/harbor#10323]
Hello!
You can find out how soon it will be possible to unite the religion between the two Harbor using self-signed certificates.

**Comment by xaleeks** [comment]
I'm not sure what this means, I'll leave it open for a bit if you want to chime in @dar9468

**Comment by dar9468** [comment]
I want Harbor to trust each other with self-signed certificates

**Comment by dar9468** [comment]
Harbor 1.8 version

**Comment by chlins** [comment]
You could uncheck the `Verify Remote Cert` when set up the registry endpoint.
