### ISSUE TITLE
Helm values suggestion

### ISSUE THREAD

**Issue by DerrickMartinez** [goharbor/harbor#10320]
We have a lot of comments in some of our charts, along with optional values, etc. Would it be possible to add another button with the raw yaml output? 

Key Values Pairs | YAML File | Raw

**Comment by ywk253100** [comment]
What's the difference between the yaml file and raw?

**Comment by ywk253100** [comment]
Currently, the yaml file and key value pairs are both the content of `values.yaml`

**Comment by DerrickMartinez** [comment]
It's missing all of the comments. We should either fix the yaml file to show comments or just render it as a text. For example:

Actual values.yaml:

# Set true if you need this because of... 
someKey: true

What you see in Harbor:
someKey: true
