### ISSUE TITLE
Improve Harbor UI : scan report icon looks strange in this version

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#10335]
Harbor Version: Version v1.10.0-6b84b62f
Scan report result icon changed in this version, it looks not that good as before. 

expected: if report has High Vulnerabilities as below, better make the icon the same size as the number which is following the icon. a little big confusing. 
one more suggestion is make sure the icon has the same standard everywhere. 

![image](https://user-images.githubusercontent.com/13995442/71405085-5ce5a280-266f-11ea-9701-c23243b68f45.png)

**Comment by cafeliker** [comment]
And what's mean of "0 Fixable" here?

**Comment by steven-zou** [comment]
> Harbor Version: Version v1.10.0-6b84b62f
> Scan report result icon changed in this version, it looks not that good as before.
> 
> expected: if report has High Vulnerabilities as below, better make the icon the same size as the number which is following the icon. a little big confusing.
> one more suggestion is make sure the icon has the same standard everywhere.
> 
> ![image](https://user-images.githubusercontent.com/13995442/71405085-5ce5a280-266f-11ea-9701-c23243b68f45.png)

`if report has High Vulnerabilities as below, better make the icon the same size as the number which is following the icon. a little big confusing.`

I think it does work as designed. The icon indicates the overall severity with a remarkable style to let users easily get what severity it is. It cannot match everyone's taste in the UX, we'll keep it as it is now.


Did not get what does this mean `make sure the icon has the same standard everywhere.`?
You mean the CSS style or something else?

@MaGaoju

**Comment by steven-zou** [comment]
> And what's mean of "0 Fixable" here?

The vulnerable package may have a fixed version, that means it's fixable.  You can refer to the related CVE standards.

@cafeliker
