### ISSUE TITLE
Can't see the error effect intuitively when deleting project or images fails

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#10348]
When I delete a project that contains images, it should show that it cannot be deleted at this time. The error message is placed in the EVENT LOGS, but I only see a small number in the upper right corner. If my eyesight is not good, it may be more difficult to observe. When a digital prompt appears, the previous plan was to pop up the EVENT LOGS directly. Is it now changed to pop up if an error occurs, or add an error prompt elsewhere in the page?

![image](https://user-images.githubusercontent.com/29826789/71471173-ae299980-2809-11ea-994a-bb0272e3ffaf.png)

**Comment by xaleeks** [comment]
yea that's not great.  Can you work on standardizing these kinds of error messages? @lweitzman
