### ISSUE TITLE
harbor on docker login  156.119.190.112 failed

### ISSUE THREAD

**Issue by sada2406** [goharbor/harbor#10353]
Get https://156.119.190.112/v2/: Get https://156.119.190.112:8433/service/token?account=kube-deploy&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 156.119.190.112:8433: connect: connection refused

Also did as below setting
{"insecure-registries": ["registry:5000","156.119.56.118","156.119.190.112"]}

CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                   PORTS                                                                 NAMES
3b77fcc72fa1        goharbor/clair-adapter-photon:v1.0.1-v1.10.0              "/clair-adapter/cl..."   2 days ago          Up 2 minutes (healthy)   8080/tcp                                                              clair-adapter
737df4551c92        goharbor/notary-server-photon:v0.6.1-v1.10.0              "/bin/sh -c 'migra..."   2 days ago          Up 2 minutes                                                                                   notary-server
6aa13e2e94f2        goharbor/nginx-photon:v1.10.0                             "nginx -g 'daemon ..."   2 days ago          Up 2 minutes (healthy)   0.0.0.0:4443->4443/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   nginx
37d44fda14ab        goharbor/harbor-jobservice:v1.10.0                        "/harbor/harbor_jo..."   2 days ago          Up 2 minutes (healthy)                                                                         harbor-jobservice
f948a4c01158        goharbor/notary-signer-photon:v0.6.1-v1.10.0              "/bin/sh -c 'migra..."   2 days ago          Up 2 minutes                                                                                   notary-signer
71afa72b3b54        goharbor/harbor-core:v1.10.0                              "/harbor/harbor_core"    2 days ago          Up 2 minutes (healthy)                                                                         harbor-core
965e1ba5e0e4        goharbor/clair-photon:v2.1.1-v1.10.0                      "./docker-entrypoi..."   2 days ago          Up 2 minutes (healthy)   6060-6061/tcp                                                         clair
41afac989c12        goharbor/harbor-portal:v1.10.0                            "nginx -g 'daemon ..."   2 days ago          Up 2 minutes (healthy)   8080/tcp                                                              harbor-portal
23d0c43ce91e        goharbor/harbor-registryctl:v1.10.0                       "/home/harbor/star..."   2 days ago          Up 2 minutes (healthy)                                                                         registryctl
36397ddff9e7        goharbor/harbor-db:v1.10.0                                "/docker-entrypoin..."   2 days ago          Up 2 minutes (healthy)   5432/tcp                                                              harbor-db
0596c0bc664c        goharbor/redis-photon:v1.10.0                             "redis-server /etc..."   2 days ago          Up 2 minutes (healthy)   6379/tcp                                                              redis
01843b0b1166        goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.0   "/home/harbor/entr..."   2 days ago          Up 2 minutes (healthy)   5000/tcp                                                              registry
9c924cabcae4        goharbor/chartmuseum-photon:v0.9.0-v1.10.0                "./docker-entrypoi..."   2 days ago          Up 2 minutes (healthy)   9999/tcp                                                              chartmuseum
bc0c51c1213e        goharbor/harbor-log:v1.10.0                               "/bin/sh -c /usr/l..."   2 days ago          Up 2 minutes (healthy)   127.0.0.1:1514->10514/tcp``

**Comment by ywk253100** [comment]
Seems you configured the wrong port `8443`?

**Comment by sada2406** [comment]
What is the solution ?

**Comment by ywk253100** [comment]
Configure the `hostname` as ` https://156.119.190.112` without port in `harbor.yml`

**Comment by sada2406** [comment]
Thanks it worked
