### ISSUE TITLE
401 Unauthorized when using multiple Harbors behind HAproxy

### ISSUE THREAD

**Issue by doruksonmez** [goharbor/harbor#10352]
Hi,

I am currently trying to deploy 3 identical Harbors (replications) behind an HAproxy instance and achieve a load balance and HA architecture. I was able to resolve login issue with following this commit:  https://github.com/goharbor/harbor/issues/6405#issuecomment-444538943. Currently, I can login to my registry from a browser but I can not login to my registry via `docker login myreg.com` command from the terminal. When I check /var/log/harbor/proxy.log, it only shows the below logs:

```
xxx.xx.xx.xx - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.002 0.004 .
xx.xxx.xx.xxx - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 911 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.016 0.016 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.000 .
xxx.xx.xx.xx- "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.004 0.004 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.001 0.000 .
y[863]: 127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.001 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.003 0.004 .
172.31.35.52 - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.002 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.004 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.000 .
127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.000 0.004 .
xxx.xx.xx.xx - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.002 0.004 .
xx.xxx.xx.xxx - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 910 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.014 0.016 .
xxx.xx.xx.xx - "GET /v2/ HTTP/1.1" 200 2 "-" "docker/18.09.7 go/go1.10.1 git-commit/2d0083d kernel/4.9.140-tegra os/linux arch/arm64 UpstreamClient(Docker-Client/18.09.7 \x5C(linux\x5C))" 0.002 0.004 .
```
If I configure the harbor.cfg for just one replication instance, there is no problem. I can login and pull images without any problem. But when I increase the replication instance number to 2 or 3, I can't even login to harbor registry. What is preventing me from login to my registry via `docker login` terminal command? I can login via a web browser.

**Comment by reasonerjt** [comment]
`docker pull` essentially access the token endpoint to fetch a token and use that token to access v2 api, it's possible that the private key to sign the token and the public key to verify the signature mismatch.

It does not work if you simply create multiple instances and setup one ha-proxy, there are quite a few details.  You'll have to figure out the how it works under the hood and do proper customization.

**Comment by doruksonmez** [comment]
I've resolved the issue by configuring the load balance parameter properly for my HA infrastructure setup. Thanks.
