### ISSUE TITLE
Harbor UI displays time zone issues

### ISSUE THREAD

**Issue by xiaoluhong** [goharbor/harbor#10357]
Hi,

I changed the time zone of the original image to CST by rebuilding the image. When the harbor was up and running, I looked at the time zones of all the containers and the timestamps of the container logs which were CST time zones. However, the harbor UI is always in UTC. 

Excuse me, how can I change the time zone? I didn't find the configuration to change the time zone. Thank you.

**Comment by AllForNothing** [comment]
@xiaoluhong you can switch your language into Chinese, Harbor UI will change the time zone to CST(UTC+8) accordingly.

**Comment by reasonerjt** [comment]
@xiaoluhong the timezone on UI is determined by the client side, i.e. the timezone setting on your OS where the browser is run.  
Updating the timezone of the image has ABSOLUTELY NO USE.

**Comment by xiaoluhong** [comment]
Hi，
@AllForNothing  @reasonerjt 

Thank you for your colleagues' help me ,the cause of the issue has been found. 

If the time zone is not passed when connecting to the database, the database configuration must be set to utc. but my database has to be set to `Shanghai` timezone for some reason.

Excuse me, how to pass the time zone when connecting to the database? thank you.

**Comment by AllForNothing** [comment]
@xiaoluhong I'm not good at database. Maybe, you  can ask a pro DBA for help.

**Comment by xiaoluhong** [comment]
Hi,
"If the time zone is not passed when connecting to the database, the database configuration must be set to utc. "  This is a hint from your colleagues.

By this logic, if my database is not set to a UTC time zone, the harbor needs to pass the time zone parameter when connecting to the database. However, the harbor does not appear to have a time zone configuration. Some community users modified the harbor source code to specify the time zone parameters when connecting to the database.

**Comment by AllForNothing** [comment]
@heww can you offer any help for this?

**Comment by hqq-get** [comment]
are you resloved it？
