### ISSUE TITLE
Middleware enhancement

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10355]
Currently most of the middlewares apply to the requests sent to the backed docker registry, but after we introduce the `Harbor tag`, some of the operations won't call any request to docker registry, such as deleting tag and artifact, so we need to enhance all these middlewares to cover all cases.

**Comment by ywk253100** [comment]
Seems that all middlewares should be put in the beego router rather than the subrouter only handles the registry requests

**Comment by reasonerjt** [comment]
If this is the case do we need middleware for V2 handlers?  I mean the middlewares should be executed before the request reaches the V2 handler?
