### ISSUE TITLE
The harbor.yml.tmpl should be rename to harbor.yml when packaged into the installer

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10368]
Currently I extract the latest build the configuration file is `harbor.yml.tmpl`

Is there a reason for this change?  It's like unnecessarily breaks the existing workflow ...

**Comment by bitsf** [comment]
I don't think so, It is suggested to copy from harbor.yml.tmpl to harbor.yml by user himself, and change the value accordingly.
You can find most software deployed with a configure template, unless user can directly use it as a default configure, but obviously harbor.yml.tmpl is not.

**Comment by reasonerjt** [comment]
@bitsf

I got your point but I don't think this is a valid argument.

Even we provide a work-by-default .yml file, most users still need to edit it before installing.  

 Any downstream installer leveraging Harbor offline installer will break due to this change.

**Comment by bitsf** [comment]
So I think we can rename this file when package the offline installer, but not rename it directly in git code, or it will always be modified in our workspace

**Comment by bitsf** [comment]
I just find an example that works similar
https://github.com/quay/clair/blob/master/config.yaml.sample

**Comment by reasonerjt** [comment]
We'll accept this change but please make sure doc is updated.

**Comment by bitsf** [comment]
doc change PR #11017

**Comment by bitsf** [comment]
open #11053 to track doc change
