### ISSUE TITLE
OIDC doc fix

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#10377]
Comment from @reasonerjt about OIDC:

Daniel Jiang 10:50 AM
I saw in oidc prvoider that groupname is not exactly the same as the value in token
for example
Need to create a mapper under client, Mapper Type: Group Membership, can set the token claim name.
Full group path set to true and the group will look like "/group1"
Full group path set to false and the group will look like "group1"
this is the note I took when I verify Harbor against keycloak
I think it looks good.  The tricky thing is that the group name has to be the same has the group name in the id_token mapped to the group claim.

**Comment by rrey** [comment]
Hi there, I currently working on plugging Harbor with Keycloak and I after I configured the OIDC I saw that groups were disabled in Harbor.
I did not find anything in the user guide about group management with OIDC enabled.

Would you need information that I could provide regarding keycloak ?
