### ISSUE TITLE
Refresh project quotas list at regular time since it's a statistic list

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#10373]
Project quotas list should be refreshed at a regular time, because when GC is triggered, harbor is in read-only state and some of storage will be released, project quotas statistic information is changing along with it, so it's better to have a refresh automatically.

**Comment by jwangyangls** [comment]
Does the project contain other parts that need to be refreshed during GC, I think the changes here need to be changed here. Meetings need to be discussed to see if this is necessary.

**Comment by reasonerjt** [comment]
Closoing as won't fix
