### ISSUE TITLE
webhooks 2.0

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10388]

**Comment by xaleeks** [comment]
【P0】Replicating OCI artifact - one webhook triggered per replication job at the end (whether success or not) and the status of the replication job is determined by Harbor jobservice.  A failure is defined as the failure of the replication job which can be caused by attempting to replicate immutable artifact, network loss, or quota exceeded among others.  

【P1】Delete artifact
This is triggered by every single deletion of an artifact.  So if during the course of a tag retention job, 1000 artifacts are deleted, then 1000 of these webhooks will be fired.  But user has the ability to turn off this webhook so only a single webhook will be fired per tag retention job.

【P0】Tag retention  
This is a single webhook to be triggered by every tag retention policy execution, see details in section (**) below

【P0】Quotas threshold exceeded
    This is triggered when exceeding 85% of disk space threshold set in project quotas 

【P0】Interrogation service monitoring
This is triggered every time the health status changes from ‘healthy’ to ‘unhealthy’ for any configured scanner, so leverage the current heartbeat monitoring all configured scanners

【P0】Registries endpoint monitoring
This is triggered every time the health status changes from ‘healthy’ to ‘unhealthy’ for any configured registry, so leverage the current heartbeat monitoring all configured registries

**Comment by reasonerjt** [comment]
Closing as a dup of #10469
