### ISSUE TITLE
harbor 1.8.2 tag 无法删除, 大小显示为0B, 并且时间显示为 1/1/1

### ISSUE THREAD

**Issue by szlyunnan** [goharbor/harbor#10396]
harbor 1.8.2 tag 无法删除, 大小显示为0B, 并且时间显示为 1/1/1

![hb](https://user-images.githubusercontent.com/12928768/71710942-8f468b00-2e39-11ea-8ac6-54e50a6a7513.png)

**Comment by heww** [comment]
Which storage driver do you use ?

**Comment by szlyunnan** [comment]
@heww 

> Which storage driver do you use ?

Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true

**Comment by doctormacky** [comment]
Same issue here. This is an very critial issue which would cause sync issue between harbors.

**Comment by heww** [comment]
> @heww
> 
> > Which storage driver do you use ?
> 
> Storage Driver: overlay2
> Backing Filesystem: extfs
> Supports d_type: true
> Native Overlay Diff: true

@szlyunnan  Sorry, my mistake. Which storage driver do you use for harbor to store the image, filesystem, s3 or others?

@doctormacky Which storage driver do you use for harbor to store the image?

**Comment by szlyunnan** [comment]
@heww 

> @szlyunnan Sorry, my mistake. Which storage driver do you use for harbor to store the image, filesystem, s3 or others?
filesystem

**Comment by heww** [comment]
> @heww
> 
> > @szlyunnan Sorry, my mistake. Which storage driver do you use for harbor to store the image, filesystem, s3 or others?
> > filesystem

This is a know issue in distribution, maybe you need to delete the manifest manually.

In version 2.0, harbor will prevent manifest which size is zero puushed to the registry. 
After upgrade to 2.0, you can delete the image which size is zero. But there is a bad news that only harbor 1.9 and 1.10 can upgrade to 2.0.

**Comment by xaleeks** [comment]
See my response to this issue here https://github.com/goharbor/harbor/issues/10846.  It's likely the same issue.  And this should be fixed in latest v2.0 release

For removing existing corrupt images, workaround is to push a dummy image with the same tag to occupy that tag, and delete that dummy image on UI.  Can you try this and let us know if it works?

**Comment by liwuzhi666** [comment]
harbor 1.8.2 tag cannot be deleted, the size is 0B, and the time is 1/1/1
To solve this problem, you can find another version of the image to achieve the 0B tag again, and then upload it to the harbor to delete, you can solve this problem, notice that the page deletes the version of the two tags together, it is better to find a useless tag

**Comment by liwuzhi666** [comment]
harbor 1.8.2 tag cannot be deleted, the size is 0B, and the time is 1/1/1
To solve this problem, you can find another version of the image to achieve the 0B tag again, and then upload it to the harbor to delete, you can solve this problem, notice that the page deletes the version of the two tags together, it is better to find a useless tag
