### ISSUE TITLE
docker push issue

### ISSUE THREAD

**Issue by lawrence191** [goharbor/harbor#10398]
I've built the harbor. But I can't use docker push to push the image into the repository.
The following is the basic information of my host.
kernel：4.4.207-1.el7.elrepo.x86_64
CPU：4
memory：4GB
harbor：v1.9.4
The error log I checked from /var/log/message is:
`msg="Failed to check for presence of layer sha256:195be5f8be1df6709dafbba7ce48f2eee785ab7775b88e0c115d8205407265c5 (sha256:bdbbaa22dec6b7fe23106d2c1b1f43d9598cd8fc33706cc27c1d938ecd5bffc7) in myhub.com/library/busybox" error="missing content-length header for request: https://myhub.com/v2/library/busybox/blobs/sha256:bdbbaa22dec6b7fe23106d2c1b1f43d9598cd8fc33706cc27c1d938ecd5bffc7" msg="Pushing layer: sha256:195be5f8be1df6709dafbba7ce48f2eee785ab7775b88e0c115d8205407265c5"
Jan  4 17:35:18 gitlab dockerd: time="2020-01-04T17:35:18.057850505+08:00" level=error msg="Upload failed, retrying: received unexpected HTTP status: 200 OK"
`
and when I run the command “docker push”. and will report the error：received unexpected HTTP status: 200 OK. I search all over the web and there was no solution. So please understand the problem, please explain the trouble and help to solve it. thanks you.

**Comment by stonezdj** [comment]
what is the Harbor logs?

**Comment by lawrence191** [comment]
> what is the Harbor logs?

I checked the log of the relevant docker container, but there was no error.I just found the error log on message and could not execute the docker push command.

**Comment by fuchicorp-manage** [comment]
What was the solution to fix this issue?
