### ISSUE TITLE
Password saved in plain text in configuration of Registry

### ISSUE THREAD

**Issue by m1ch41** [goharbor/harbor#10392]
Registries -> Example server (Added Earlier) -> EDIT 

After we clicked EDIT we have configuration form, we have label password label field with asterisk.
when we will change in code (using Developer Tools) type of this field from password to text we are able to see password.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/58170730/71670546-7920c800-2d70-11ea-991a-95ddb1f114dd.png">

So... password is stored in plain text. Please fix it.

**Comment by steven-zou** [comment]
@bitsf @jwangyangls 

Please confirm the issue is really existing.

I remembered for editing no real password is retrieved to the frontend.

**Comment by jwangyangls** [comment]
The displayed password is not a real password, it just has a placeholder effect.
