### ISSUE TITLE
Investigation on swagger-ts-generator to auto generate frontend code base on swagger. 

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#10407]
Need investigation how to generate code base on swagger file.

**Comment by AllForNothing** [comment]
After investigation , i found  swagger-ts-generator was not able to apply to Harbor.  Because swagger-ts-generator  has strict requirements for swagger.yaml schema,  when auto generate code with Harbor's 
swagger.yaml,  an  error  occurs
