### ISSUE TITLE
[bug]harbor helm charts push image success but registry database has no col about image

### ISSUE THREAD

**Issue by Okabe-Kurisu** [goharbor/harbor#10404]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
there are 499 images start with test-1/ but only one repo can be find in harbor
![image](https://user-images.githubusercontent.com/16147105/71793427-c30ef400-3077-11ea-8410-cea986c53bf0.png)
also have `manifest for image xxx is not ready, retry after xxms` infinite loop problem
![image](https://user-images.githubusercontent.com/16147105/71793550-44ff1d00-3078-11ea-8adc-0780734a6f92.png)

**Steps to reproduce the problem:**
1. depoly harbor helm chart in k8s
2. push images to harbor ( 80 Concurren total 40k images， clean job set every hour）
3. harbor registry instance oom, postgres master oom after 4 hours
4. push images sucess but no repo in harbor database

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10

**Comment by heww** [comment]
This [script](https://docs.openstack.org/developer/performance-docs/test_plans/container_repositories/plan.html#measuring-performance-of-container-repositories) was used to push the images in this issue.
