### ISSUE TITLE
Locked on with duplicate key value violates unique constraint "harbor_user_email_key"

### ISSUE THREAD

**Issue by SergeAlexandre** [goharbor/harbor#10400]
Hi all,

May be I missed something, but I think I got a logical issue with Harbor/LDAP integration.

**Expected behavior and actual behavior:**

When removing an existing user in an ldap server, there is no way to remove its counterpart in Harbor.
Beside having 'zombi' users, this prevent to re-use its email address, due to unicity constraint.

**Steps to reproduce the problem:**

- Have an Harbor instance with properly configured ldap connection.
- Create a user in ldap: For example uid=jclark, email=jim.clark@lotus.com
- Log in harbor interface with this user
- This user is now displayed in the user pane. Which is readonly, as authentication is configured with ldap.
- Remove this user in ldap server.
- Create another one with same email. For example: uid=clarkj, email=jim.clark@lotus.com
- Unable to log using this new user. Digging in core.log, we can see:

Jan  5 16:21:16 172.18.0.1 core[6020]: 2020-01-05T16:21:16Z [ERROR] [/core/controllers/base.go:109]: Error occurred in UserLogin: pq: duplicate key value violates unique constraint "harbor_user_email_key"

Same error when trying to use this new user as a project member.

And without a way to delete this old user (Excepting of course hacking the DB), this email adresse is unusable anymore..

Beside the ability to cleanup Zombi user, I am wondering why there is this unicity constraint on email value ? It is quite frequent to have several account using the same email (As they generally refer to the same humain being).

**Versions:**

- harbor version: 1.10.0
- docker engine version: 18.09.7
- docker-compose version:  1.18.0,

**Additional context:**

Tested against a Freeipa LDAP server. But I don't think this has something to do with ldap server type.

Thanks.

**Comment by stonezdj** [comment]
You can refer the wiki to cleanup old user:
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#ldap
```
docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user;
 delete from harbor_user where user_id > 2;
```

**Comment by stonezdj** [comment]
Email unique constraint can not be ignored.

**Comment by stonezdj** [comment]
When the email attribute is empty in LDAP, the email in the Harbor DB should be NULL instead of an empty string, it is doesn't break the unique constraint
