### ISSUE TITLE
cannot replicate helm charts, but images replication works well.

### ISSUE THREAD

**Issue by spwangxp** [goharbor/harbor#10415]
as title says, when i deployed the harbor instance , it's most func works well, even the images repliacation, but the charts replication.
![image](https://user-images.githubusercontent.com/24298044/71876978-072af300-3163-11ea-8c47-268d4f006d36.png)

LOG-INFO:
Jan  7 15:07:11 192.168.249.46 web.chartmuseum[912]: {"L":"WARN","T":"2020-01-07T07:07:11.137Z","M":"[17983] Request served","path":"/api/library/charts/airflow/5.2.2","comment":"","latency":"1.11476ms","clientIP":"172.18.0.5","method":"GET","statusCode":404,"reqID":"087d9692-2f65-4b83-8713-90ee9b3eb047"}
Jan  7 15:07:11 192.168.249.46 web.core[912]: 2020-01-07T07:07:11Z [ERROR] [/common/api/base.go:200]: fail to get chart version: http error: code 404, message no chart name found
Jan  7 15:07:11 192.168.249.46 web.core[912]: 2020-01-07T07:07:11Z [ERROR] [/common/api/base.go:73]: GET /api/chartrepo/library/charts/airflow/5.2.2 failed with error: {"code":404,"message":"no chart name found"}
Jan  7 15:07:11 192.168.249.46 web.core[912]: 2020/01/07 07:07:11 #033[1;44m[D] [server.go:2774] |   198.19.15.48|#033[43m 404 #033[0m|  24.564977ms|   match|#033[44m GET     #033[0m /api/chartrepo/library/charts/airflow/5.2.2   r:/api/chartrepo/:repo/charts/:name/:version#033[0m
Jan  7 15:07:11 192.168.249.46 web.proxy[912]: 198.19.15.48 - "GET //api/chartrepo/library/charts/airflow/5.2.2 HTTP/1.1" 404 45 "-" "harbor-replication-service" 0.025 0.024 .

JOBSERVICE-LOG:
2020-01-07T07:08:51Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying stable/airflow:5.2.2(source registry) to stable/airflow:5.2.2(destination registry)...
2020-01-07T07:08:51Z [ERROR] [/replication/transfer/chart/transfer.go:156]: failed to download the chart stable/airflow:5.2.2: http error: code 500, message {"code":500,"message":"Internal Server Error"}

RELATED-CODE: https://github.com/goharbor/harbor/blob/release-1.9.0/src/replication/adapter/harbor/chart_registry.go#L142

**Comment by ywk253100** [comment]
Could you provide more context? Are both the source and destination instance Harbors? What's the version? How did you set the replication rule? Is it pull mode or push mode?

**Comment by ywk253100** [comment]
Can you download the chart `library/airflow:5.2.2` on web portal? How about the API `GET /api/chartrepo/library/charts/airflow/5.2.2`?

**Comment by spwangxp** [comment]
thanks for ur reply, it works after restart harbor.  the both instance is harbor 1.9.3. but sometimes  connection test succeed when replication fail.

**Comment by xaleeks** [comment]
@reasonerjt can you please look into this?  I'm adding a fc tag so it doesn't slip through on our next triage meeting.

**Comment by ywk253100** [comment]
@xaleeks According to the reply of @spwangxp, the replication works after restarting 

@spwangxp The connection testing only tests the connection and credential, the replication failure can be caused by many other causes.

**Comment by renmaosheng** [comment]
Thanks Wenkai fixing this.  Please reopen if you hit it again.
