### ISSUE TITLE
ldap group parsing error

### ISSUE THREAD

**Issue by nthaler-github** [goharbor/harbor#10418]
I recently setup harbor 1.9.4 (online install) using Docker v19.03.5 and docker-compose 1.25.0 and am running into issues trying to get LDAP-based authentication working.  All containers are healthy.  

The ldap authority is a Windows 2012-based AD forest, which I'm binding to over LDAPs.   The connection tests successfully, I can add import groups w/o error, but the core logs contain:

failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax and user logins 

... and when I try to login as an ldap user I get:

 [ERROR] [/core/controllers/base.go:110]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Not found an entry'

I have this as an LDAP group filter:  objectclass=group  ## based on the advise of folks running into similar issues.

LDAP group membership is listed as : memberof

Thanks,
Nathan

**Comment by stonezdj** [comment]
The LDAP group config doesn't related to the LDAP user logins.
The related error is :
```
[ERROR] [/core/controllers/base.go:110]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Not found an entry'
```

Can you please try to search the user with the same LDAP settings?
