### ISSUE TITLE
harbor delete error in UI error 504 Gateway Time-out

### ISSUE THREAD

**Issue by shaojielinux** [goharbor/harbor#10417]
api api/repositories/oms-protoss/tder/pro-o/tags/03641474 504  gateway
Some can be deleted, some can't

**Comment by stonezdj** [comment]
can you please provide more detail logs, the `oms-protoss` is the projectname and the `tder/pro-o` is the repository name?

**Comment by shaojielinux** [comment]
What logs are provided?

**Comment by shaojielinux** [comment]
![image](https://user-images.githubusercontent.com/28892865/72069871-1789cc00-3323-11ea-9b24-6badf7f9f625.png)

**Comment by shaojielinux** [comment]
nginx log 2020/01/09 13:09:25 [error] 9#0: *24019 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.37.10, server: , request: "DELETE /api/repositories/oms-protoss/test/protoss-oms/tags/99f29e06 HTTP/1.1", upstream: "http://172.19.0.8:8080/api/repositories/oms-protoss/test/protoss-oms/tags/99f29e06", host: "har.test.com", referrer: "https://har.tessts.com/harbor/projects/9/repositories/oms-protoss%2Ftrader%2Fprotoss-oms"
