### ISSUE TITLE
Webhook to send slack notification 

### ISSUE THREAD

**Issue by govindkailas** [goharbor/harbor#10422]
We have created a webhook to send a notification to Slack. We see that it got triggered during the image pull, but it did not reach Slack.  

![image](https://user-images.githubusercontent.com/6698224/71944908-3dac5080-31eb-11ea-8bb3-558fbe2620ac.png)

![image](https://user-images.githubusercontent.com/6698224/71944939-57e62e80-31eb-11ea-9c3d-628ce33aba6c.png)

We don't see anything in the logs other than the image pull.
![image](https://user-images.githubusercontent.com/6698224/71945115-e195fc00-31eb-11ea-891e-cd33196d8daf.png)

**Comment by xaleeks** [comment]
please advise on how to implement this and why it's unsupported natively atm.  @steven-zou

**Comment by ywk253100** [comment]
The notification data structure sent by Harbor isn't recognized by every receivers. Slack is the case. 
So the solution is that you can provide your own server, receive the notification data from Harbor and convert it to the structure recognized by Slack and send it to Slack

**Comment by xaleeks** [comment]
please watch this - https://github.com/goharbor/harbor/issues/10464 @govindkailas

**Comment by steven-zou** [comment]
I think our community contributors @mmpei is doing this work.

**Comment by xaleeks** [comment]
@govindkailas  can you try again now, this was not supported at the time you filed the ticket but it is now

**Comment by govindkailas** [comment]
We are not using `harbor 2.0` yet, I see the Helm release for `2.0` is available now. I shall upgrade our stage instance and test this out!!

**Comment by mmpei** [comment]
it is supported in release 2.0
