### ISSUE TITLE
Project log access for Limited Guest Role

### ISSUE THREAD

**Issue by mhuangpivotal** [goharbor/harbor#10438]
The [Limited Guest Role](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#rbac) introduced in 1.10.0 specifies that

```
they cannot see logs or the other members of a project
```

However, project logs are still returned in `/api/logs`, as well as the "Logs" page in the UI.

**Comment by renmaosheng** [comment]
the code is merged. will cherry-pick to master.
