### ISSUE TITLE
GCR replication only works with override namespace, causing issue with image path

### ISSUE THREAD

**Issue by rvennam-lbg** [goharbor/harbor#10431]
We are using Harbor and GCR as part of our build environments and are syncing images from Harbor and GCR. To get the sync working we have override Destination namespace parameter. But once this is enabled we are not able to retain the paths used in the Harbor registry i.e.

harbor.test.io/plt_tools/jenkins/jenkins:lts --> synced as -->  eu.gcr.io/project_id/jenkins:lts

This causes the helm charts to fail as the image paths are no longer retained. 

Can you please help on this issue

**Comment by rvennam-lbg** [comment]
@ reasonerjt is this something you can check the feasibility of?

**Comment by bitsf** [comment]
hi @rvennam-lbg , not quite get what you mean, can you show me the case what you think it should be ?

**Comment by rvennam-lbg** [comment]
Hi @bitsf  as override is needed for push/pull based replication for a GCR to work and once it's provided the whole paths are considered to be overridden. Currently, the replication configured is removing all the paths when we configure sync

Below are the images of sync configured and the one from GCR of the images synced where we are missing the path. The ask is to retain path on sync as long as there is only project_id specified with no paths in override retain the paths during sync. 

A suggestion is to check if the override has `/` in it and only if it does then remove the paths if not retain as is 

![image](https://user-images.githubusercontent.com/49170697/72993438-49a03100-3ded-11ea-99c6-cc7788eb3f9b.png)

![image](https://user-images.githubusercontent.com/49170697/72993512-6e94a400-3ded-11ea-9ed9-4623460025cc.png)

![image](https://user-images.githubusercontent.com/49170697/72993723-c7fcd300-3ded-11ea-87d1-261b3587a657.png)

![image](https://user-images.githubusercontent.com/49170697/72993615-9552da80-3ded-11ea-9e6a-97bce33a4707.png)

**Comment by rvennam-lbg** [comment]
Hi @bitsf can you please check and let me know of the feasibility for this to be implemented?

**Comment by bitsf** [comment]
Not sure if I understand correctly from your description, do you mean
when you setup source pattern as "platform/**",
there maybe some different images with different namespace, such as platform/AA/busybox, platform/BB/busybox,
and your destination namespace is mgmt-spi
currently two busybox images will be both replicate as mgmt-spi/busybox, so one is overwritten,
you hope they should be two seperated with origin namespace as mgmt-spi/AA/busybox and mgmt-spi/BB/busybox

**Comment by rvennam-lbg** [comment]
@bitsf  yes you are correct

**Comment by bitsf** [comment]
@steven-zou @ywk253100 this should be a general requirement for replication, how do you think if we should keep the sub namespace when doing replication.
if do so, we may need to to extract the sub namespace from ** pattern, and create them before do jobservice

**Comment by steven-zou** [comment]
Involve @xaleeks here too.

**Comment by rvennam-lbg** [comment]
@steven-zou @bitsf I don't see this being picked up as part of the new 2.0 RC releases, is this being looked into ?

**Comment by chlins** [comment]
Close the issue as resolved by `Use the Destination Flattening`, docs: https://goharbor.io/docs/2.5.0/administration/configuring-replication/create-replication-rules/
