### ISSUE TITLE
Harbor core always redirect to port 8080

### ISSUE THREAD

**Issue by haeiven** [goharbor/harbor#10430]
Hi,

I'm trying to install Harbor on a fresh system, with everything updating and by following the tutorial. I can connect to Harbor, add what i want, but when I'm trying to access https://mydomain.com/v2 or /api, etc..., i'm redirected to http://mydomain.com:8080/v2 or /api

Here is my harbor.yml : https://paste.soleria.eu/noxalituno.shell

I tried the thing at the end of the wiki and removed the lines in the nginx config, still not working. I tried to change the host name, adding :8080 to the end of the external url, but nothing to do.

I still can't access to /v2 or /api with the IP, it's redirecting to IP:8080/v2

Did I missed something?

Best regards,

**Comment by huangyisan** [comment]
I have faced the same problem.

my environment:
goharbor/chartmuseum-photon                                                       v1.10.5               15bf0f2455c7        5 days ago          178MB
goharbor/harbor-migrator                                                          v1.10.5               2639e4402e6a        5 days ago          357MB
goharbor/redis-photon                                                             v1.10.5               0dd9b668acc7        5 days ago          126MB
goharbor/clair-adapter-photon                                                     v1.10.5               64440a987bd7        5 days ago          61.2MB
goharbor/clair-photon                                                             v1.10.5               c33d6d224990        5 days ago          171MB
goharbor/notary-server-photon                                                     v1.10.5               0b6247f2db07        5 days ago          142MB
goharbor/notary-signer-photon                                                     v1.10.5               892ce0ca3f27        5 days ago          139MB
goharbor/harbor-registryctl                                                       v1.10.5               25f235d03b94        5 days ago          102MB
goharbor/registry-photon                                                          v1.10.5               2b7d36d631a2        5 days ago          84.5MB
goharbor/nginx-photon                                                             v1.10.5               f6c62e4d680f        5 days ago          43.6MB
goharbor/harbor-log                                                               v1.10.5               33db4a5cc8a0        5 days ago          82.1MB
goharbor/harbor-jobservice                                                        v1.10.5               4ec89c99c23f        5 days ago          143MB
goharbor/harbor-core                                                              v1.10.5               b8e6992fd50b        5 days ago          129MB
goharbor/harbor-portal                                                            v1.10.5               e7a0334355f8        5 days ago          51.7MB
goharbor/harbor-db                                                                v1.10.5               17c49d4226a3        5 days ago          164MB
goharbor/prepare                                                                  v1.10.5               71386ea24d9b        5 days ago          172MB

**Comment by siikanen** [comment]
Seems like this is issue is still present on version v1.10.17. Installing Harbor with install.sh will incorrectly forward to from port 80 to 8080 at /v2 url.

**Comment by agwidarsito** [comment]
We are having this problem too... exactly as above. Installing Harbor with install.sh will incorrectly forward to from port 80 to 8080 at /v2 url. Note that if there's a trailing slash it's okay?

**Comment by KernelSailor** [comment]
I have the same Problem. Is there any fix?

**Comment by crossRT** [comment]
hi there, i also had the same problem.
my harbor instance running behind a reverse proxy (nginx), and i terminate the SSL on the reverse proxy instead of harbor nginx.
when i do `docker login` and `docker pull`, it seems like using the HTTP endpoint instead of HTTPS endpoint of my harbor.

**SOLUTION:**
make sure u configure `external_url` in ur `harbor.yml`, run `./prepare` to regenerate the configurations.

references:
https://goharbor.io/docs/2.12.0/install-config/configure-yml-file/
