### ISSUE TITLE
XSRF protection doesn't work for http.Handler that bind to beego router directly

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10454]
The XSRF protection only works for beego.Controller:
https://github.com/astaxie/beego/blob/develop/router.go#L775
https://github.com/astaxie/beego/blob/develop/router.go#L798
https://github.com/astaxie/beego/blob/develop/router.go#L819

**Comment by ywk253100** [comment]
I come up two solutions:
1. Wrap the `http.Handler` into `beego.Controller`
2. Use other XSRF protection solution, such as https://github.com/gorilla/csrf

**Comment by reasonerjt** [comment]
This will have to target later sprints as we don't have a good solution.  I'm moving it to SP81

**Comment by reasonerjt** [comment]
Fixed in #10937
