### ISSUE TITLE
harbor ui时间与数据库时间不一致

### ISSUE THREAD

**Issue by kevin-hao** [goharbor/harbor#10459]
在系统为CentOS 7.6.1810 内核版本为3.10.0-957.el7.x86_64上部署harbor 1.10.0。数据库中的时间是正确的，和系统一致，但是在harbor ui上显示的时间是不一致的。容器的时间和系统时间也是一致正确的。
harbor ui时间
![image](https://user-images.githubusercontent.com/14213577/72254204-5333d700-363e-11ea-8448-a7378cae4331.png)

数据库中的时间

![image](https://user-images.githubusercontent.com/14213577/72254224-62b32000-363e-11ea-95ab-a2cdf616b4ec.png)

**Comment by AllForNothing** [comment]
@kevin-hao 可否提供api接口返回的json 中 的push_time 字段的值？

**Comment by AllForNothing** [comment]
@kevin-hao  "push_time": "2020-01-15T21:08:06.378246+08:00", 转化为北京时间后为”2020/1/15 下午9:08:06“， 这与web上显示的值是一致的。
数据库中的”2020-01-15 13:08:06.353488“ 这个时间显示的是UTC标准时间，转化为UTC+8后为”2020-01-15T21:08:06.378246+08:00“， 也是没有问题的，相差的零点零几毫秒，因该是程序执行时间导致的一点误差。

**Comment by kevin-hao** [comment]
那就有一个问题了，现在是2020年1月15日下午5点56分，2020/1/15 下午9:08:06这个时间点还没到，为什么会是这个时间点呢

**Comment by AllForNothing** [comment]
@kevin-hao 那就是存入数据的值有问题， 但是api 获取值和UI 显示值，和数据库一直，没有问题

**Comment by kevin-hao** [comment]
应该是程序无论是什么时间时区，都加了8个小时。

**Comment by bjzqhe** [comment]
我也遇到这个问题了  部署的harbor是1.10.1   ui上创建的项目的时间不对（如我晚上20点创建的显示是4点 ）

**Comment by bjzqhe** [comment]
`
![4D737EED-2E08-4917-A7E0-58CA4B508D46](https://user-images.githubusercontent.com/16338685/80099501-211d0400-85a1-11ea-81fe-3e8550cfabb6.png)
`

**Comment by hqq-get** [comment]
我也遇到这个问题了

**Comment by mlrsyz** [comment]
这个问题我通过复制宿主机的/etc/localtime   命令如下
docker cp -L /usr/share/zoneinfo/Asia/Shanghai  "容器名":/etc/localtime
完成了9大容器的时间不准确     然后产生了很突兀的bug    只要重启了harbor容器就无法使用争取的账号登录了
Linux 4.18.0-193.28.1.el8_2.x86_64 x86_64

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:11 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by mansoncui** [comment]
这个问题我也遇到了，你们是怎么解决的
