### ISSUE TITLE
Support event selector in webhook

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#10465]

**Comment by mmpei** [comment]
curl "http://XXXXX:8080/api/projects/3/webhook/policies" -H "Accept: application/json, text/plain, */*" -H "Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2" --compressed -H "X-Xsrftoken: EijzafJAxAqLroS32TxpikXV2km5Cizp" -H "Content-Type: application/json" -H "Origin: http://XXXXX:8080" -H "Connection: keep-alive" -H "Referer: http://10.219.192.61:8080/harbor/projects/3/webhook" -H "Cookie: sid=6f1f3984acd83e24164c767048ffc2a2; rem-username=admin; _xsrf=RWlqemFmSkF4QXFMcm9TMzJUeHBpa1hWMmttNUNpenA=|1579251372575130246|e75bad9ec0b3c4bcd7c8901a5c0b0728c3bd1527" --data "{""targets"":[{""type"":""http"",""address"":""http://59.111.92.135:48081/ccr/test/webhook/"",""skip_cert_verify"":true}],""event_types"":[""downloadChart"",""deleteChart"",""uploadChart"",""deleteImage"",""pullImage"",""pushImage"",""scanningFailed"",""scanningCompleted"",""projectQuota""],""enabled"":true}"

evnet_type is a string list. and support selectable.

**Comment by reasonerjt** [comment]
@mmpei is this for UI or backend?

**Comment by wy65701436** [comment]
close it as PR merged.
