### ISSUE TITLE
Support `Replicating OCI artifact` and `Tag retention` events

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#10462]

**Comment by xaleeks** [comment]
I didn't see this in the rc build.  Is tag retention still in 2.0? @wy65701436  @mmpei

**Comment by renmaosheng** [comment]
@mmpei could you please take a look? thanks.

**Comment by mmpei** [comment]
we work on this feature and believe that we could bring it into v2.0.

**Comment by xaleeks** [comment]
If this was delivered, please add docs and close it out.  @mmpei

**Comment by reasonerjt** [comment]
Closing as the code has been merged.
