### ISSUE TITLE
auto scan image invalid for project

### ISSUE THREAD

**Issue by duyanghao** [goharbor/harbor#10479]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: When `Automatically scan images on push` option of a project turns on, harbor scan image once an image push happens. 
Actual behavior: harbor does not scan image at all when push image of that project.

**Steps to reproduce the problem:**
1. turn on `Automatically scan images on push` option of a project
2. push a new image of that project

**Versions:**
- harbor version: 1.7.0

harbor core log:
`2020-01-14T07:06:05Z [INFO] The Vulnerability data is not ready in Clair DB, the auto scan will be skipped.%!(EXTRA <nil>)`

Addition: When I click scan icon for an image tag, the scan happens.

**Comment by steven-zou** [comment]
I think the log has exposed the cause 'The Vulnerability data is not ready in Clair DB, the auto scan will be skipped.%!(EXTRA <nil>)'

@duyanghao

**Comment by duyanghao** [comment]
> I think the log has exposed the cause 'The Vulnerability data is not ready in Clair DB, the auto scan will be skipped.%!(EXTRA )'
> 
> @duyanghao

@steven-zou I don't get your point.

**Comment by catchups** [comment]
Since Clair DB is updated with an online batch, I think it should be done.

**Comment by xaleeks** [comment]
@duyanghao he's referring to the log showing db was not ready at the time it was pushed, did you do this immediately after setting up harbor with clair?  because it takes 10-15 minutes for db to get fully populated.  In that window, you won't get a scan triggered.

BTW, please upgrade from 1.7, it is not officially supported anymore : )
