### ISSUE TITLE
Chartmuseum permission issue

### ISSUE THREAD

**Issue by volatilemolotov** [goharbor/harbor#10484]
What can we help you?
As explained in user guide: 

https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#add-harbor-to-the-repository-list

There seems to be a mode of access that aggregates all the charts that a user has permission throughout the projects but this is only possible if the user has admin priviledges. 
Is this by design or?

**Comment by steven-zou** [comment]
The root index which aggregates all the project indexes are aligned with design. And then only admin has the permissions to access it.

@volatilemolotov

**Comment by volatilemolotov** [comment]
I still do not understand why just admin can do this. It would be a great feature for users to just add one repo and have access to charts across projects that they are in. Or am i missing something?

**Comment by coutantal** [comment]
It would be useful indeed.
