### ISSUE TITLE
Harbor Migration tool fails to run

### ISSUE THREAD

**Issue by prahaladdarkin** [goharbor/harbor#10488]
**Background**
I have a Harbor 1.9.0 installation that I wish to upgrade to Harbor 1.10.0. I downloaded the migration container image and run the command as below
`docker run -it --rm -v /home/harbor/harborinstaller/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.10.0-dev --cfg --version 1.10.0 --output up`
The tool returns with an error : `Migrator fail to execute, err: coercing to Unicode: need string or buffer, bool found`

**Expected behavior and actual behavior:**

*Expected Behavior** : The tool should run successfully and migrate 1.9.0 to 1.10.0
**Actual Behavior** : The tool produces the following output:

`Please backup before upgrade,
Enter y to continue updating or n to abort: y
Migrator fail to execute, err: coercing to Unicode: need string or buffer, bool found`

**Steps to reproduce the problem:**
1. Deploy v1.9.0 of Harbor
2. Run the migration tool using the command above

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.0]
- docker engine version: [`Docker version 18.09.7, build 2d0083d`]
- docker-compose version: [`docker-compose version 1.24.1, build 4667896b`]

**Additional context:**

- **Harbor config files:** 

[harbor.yml.zip](https://github.com/goharbor/harbor/files/4063194/harbor.yml.zip)

Contents of Harbor installation tools directory:
`harbor@kube-worker:~/harborinstaller/harbor$ ls -ltrh .
<img width="1435" alt="Screen Shot 2020-01-15 at 10 51 07 AM" src="https://user-images.githubusercontent.com/30070908/72407277-fb53b800-3784-11ea-82eb-6fb895de1de2.png">

- **Log files:** NA since this would be an external tool. Please let me know if there are any additional locations where the logs are created for the migrator tool

**Comment by ninjadq** [comment]
@prahaladdarkin please ref doc to upgrade. upgrade command looks like this
```
docker run -it --rm -v ${harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:[tag] --cfg up
```

**Comment by prahaladdarkin** [comment]
@ninjadq  thank you for the update on this ticket. Was curious to know how ${harbor_yml} resolves to the correct values

**Comment by ninjadq** [comment]
It's just a place holder, replace it with your real path of `harbor.yml` file on you host

**Comment by prahaladdarkin** [comment]
@ninjadq The command now works correctly and my harbor instance appears to have upgraded to 1.10.0. 
However, I have a question i see in the source code for the migration tool a number of options available which allow the user to specify the version and which also allow an output. Basically the below piece of code in `migrator.py`
`parser = argparse.ArgumentParser(description='migrator of harbor') 
        parser.add_argument('--db', action="store_true", dest='is_migrate_db', required=False, default=False, help='The flag to upgrade db.')
        parser.add_argument('--cfg', action="store_true", dest='is_migrate_cfg', required=False, default=False, help='The flag to upgrede cfg.')
        parser.add_argument('--version', action="store", dest='target_version', required=False, default='', help='The target version that the harbor will be migrated to.')         
        parser.add_argument('--output', action="store_true", dest='output', required=False, default=False, help='The path of the migrated harbor.cfg, if not set the input file will be overwritten.') `
It appears that the error occurs when specifying other options during upgrade
