### ISSUE TITLE
Not able to push to the registry

### ISSUE THREAD

**Issue by Oliverq755** [goharbor/harbor#10483]
## Issue Description
When login to the registry, I am able to successfully login to my registry. However, when trying to push something, I am getting few errors listed below:

1. received unexpected HTTP status: 500 Internal Server Error
I am getting above error when I am trying to ```docker push localhost:80/nodemodules_v1```
2. denied: requested access to the resource is denied
I am getting above error when I am trying to ```docker push localhost/library/dms```

Sometimes, I am getting stuck in scenario [attachment] which is resulting infinite retry.

### CASE 1
```
[root@dockerregistry ~]# docker push localhost:80/nodemodules_v1
The push refers to repository [localhost:80/nodemodules_v1]
41b22d31c285: Preparing
9c0492e429eb: Preparing
cfa0b06b8188: Preparing
b8f881f4b566: Preparing
026d2b9bf4a2: Preparing
a443938b940b: Preparing
bc586eccaac6: Preparing
3a718ecbfcb3: Preparing
138222e9d08c: Preparing
1bae99a6eec3: Preparing
332e0c635fad: Preparing
869bde90e3a4: Preparing
d83a7432005c: Preparing
cd5209a136b2: Preparing
489256b1b7f0: Preparing
5977b863bcc9: Preparing
a5387f260fb3: Preparing
817c08e7256c: Preparing
c265e93c15fe: Preparing
d2735ee35508: Preparing
6732b9f7998a: Preparing
787d5e073b3b: Preparing
cf89a35c5209: Preparing
d3b9488b6e82: Preparing
fe3c3b14401d: Preparing
5bde9130a522: Preparing
90098d7f033a: Preparing
f0d7b4bb8a3b: Preparing
a36ade9ef966: Preparing
904ea782c9f7: Preparing
b932d686377d: Preparing
8d76d3fcf0c4: Preparing
b7fa8b0e56ef: Preparing
6ad176de999e: Preparing
53e7e5a0e12d: Preparing
b73846102982: Preparing
1fe58155a0c8: Preparing
dec130f078c7: Preparing
5d854d5bb833: Preparing
857cb14a5e35: Preparing
8db283d9cffd: Preparing
4287ed0fcd3d: Preparing
b4c2484d0b9b: Preparing
a206474fca4d: Preparing
ff5b93476693: Preparing
043ae7be0d28: Preparing
189453f831cb: Preparing
646fc475e208: Preparing
4b588c4e187e: Preparing
e644b8d5aef8: Preparing
2be8e13fe028: Preparing
040168a3566f: Preparing
974ca6dae953: Preparing
a2c9135ce50c: Preparing
026d2b9bf4a2: Retrying in 1 second
7f0b08a6183e: Waiting
683078461a66: Waiting
ac40b057df65: Waiting
a93919637629: Waiting
5477078e2dc5: Waiting
d7969b4e7aa5: Waiting
8107d60ce014: Waiting
fda50e7c783d: Waiting
9bd5c991a921: Waiting
548102ac7ebc: Waiting
750bcc5e56c4: Waiting
615560b60e97: Waiting
b1d11ea39286: Waiting
a9e4f47f5910: Waiting
1de5bbd78fe9: Waiting
d4e027055865: Waiting
5f9e25187d02: Waiting
3ed0a8a09292: Waiting
4cf6a3e33af3: Waiting
3db6da1e653a: Waiting
8cc50e519744: Waiting
1808b36e341d: Waiting
ea7cd9be6069: Waiting
7a1fbdf95adb: Waiting
d5a2baeeed4c: Waiting
3d78b85885cd: Waiting
42202a181277: Waiting
42f1767bbda3: Waiting
09546073dc63: Waiting
c8054c1289e2: Waiting
2f1c65b8f8b3: Waiting
fdde19b119ef: Waiting
aae019a8c241: Waiting
1c90f63f73ac: Waiting
bc73310cca57: Waiting
d69483a6face: Waiting
received unexpected HTTP status: 500 Internal Server Error
```
### CASE 2
```
[root@dockerregistry ~]# docker push localhost/library/dms
The push refers to repository [localhost/library/dms]
553b7d0bb633: Preparing
b810a8ddc93b: Preparing
7bebf934a08e: Preparing
6f1b3a3d86d9: Preparing
b74976efe19d: Preparing
03f6cebccbf2: Waiting
ef2be7b555d9: Waiting
4d3c6593b2c9: Waiting
e95a0a961946: Waiting
ceaf9e1ebef5: Waiting
9b9b7f3d56a0: Waiting
f1b5933fe4b5: Waiting
denied: requested access to the resource is denied
```
#### URGENT SUPPORT AND ANY SUGGESTION IS APPRECIATED

**Comment by yogeshmallik** [comment]
@Oliverq755 I am also facing the same issue. I am expecting some urgent support.

**Comment by steven-zou** [comment]
@Oliverq755 

Please provide the related context, like what's the version of Harbor, Docker etc. And maybe you can check and provide the related logs which may contain the concrete error message for the occurring errors.

**Comment by yogeshmallik** [comment]
@steven-zou In my case. Here are the complete details for the error I am getting.

Jan 13 10:42:49 172.19.0.1 core[1203]: 2020-01-13T05:12:49Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:49 172.19.0.1 core[1203]: 2020-01-13T05:12:49Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:49 172.19.0.1 core[1203]: 2020-01-13T05:12:49Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:49 172.19.0.1 core[1203]: 2020-01-13T05:12:49Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:49 172.19.0.1 core[1203]: 2020-01-13T05:12:49Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:54 172.19.0.1 core[1203]: 2020-01-13T05:12:54Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:54 172.19.0.1 core[1203]: 2020-01-13T05:12:54Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:54 172.19.0.1 core[1203]: 2020-01-13T05:12:54Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1
Jan 13 10:42:54 172.19.0.1 core[1203]: 2020-01-13T05:12:54Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: nodemodules_v1


Harbor version: '2.3'
Docker version 19.03.5

**Comment by Oliverq755** [comment]
@yogeshmallik I have found the solution for this issue, you can check it out.
You have to configure the external end point in your harbor configuration file. Your configuration file will be located at ```/harbor/common/config/core```.
In side your environment folder, your external end point (```EXT_ENDPOINT```) should be same as your host ip address provided at ```harbor.yml``` file. 
Also check ```/harbor/common/config/registry/config.yml```: The **realm** ip address should contain the same host-name specified before.

Hope this will solve your issue.
