### ISSUE TITLE
Harbor tile testing against OpsMan

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10492]
Please test harbor tile 1.9.5 and harbor tile 1.10.1 against OpsManager 2.8

**Comment by renmaosheng** [comment]
@stonezdj is the harbor tile concourse pipeline ready for this? when do you expect we can complete this? thanks.

**Comment by stonezdj** [comment]
We are going to verify the Ops Manager 2.8 with the customer success env.

**Comment by stonezdj** [comment]
Done
