### ISSUE TITLE
Failed to ping endpoint (registry zalando-stups/pierone)

### ISSUE THREAD

**Issue by finkr** [goharbor/harbor#10509]
**Expected behavior and actual behavior:**

I want to replicate a public registry (https://registry.opensource.zalan.do/acid/postgres-operator), which is running  [zalando-stups/pierone](https://github.com/zalando-stups/pierone) docker image registry .

**Steps to reproduce the problem:**

* Open Harbor menu  administration > registries
* Add a registry
* Provider: docker-registry (or any other)
* Name: Zalando
* Endpoint URL: https://registry.opensource.zalan.do/
* Click test

error message on screen:  **Failed to ping endpoint.** 

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.2 and 1.9.4
- docker engine version: 18.09.1
- docker-compose version: 1.21.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

In the core.log  log file:
```
$ tail -n -f *.log
==> registryctl.log <==
Jan 17 00:18:21 172.28.0.1 registryctl[6804]: 127.0.0.1 - - [16/Jan/2020:23:18:21 +0000] "GET /api/health HTTP/1.1" 200 9

==> portal.log <==
Jan 17 00:18:22 172.28.0.1 portal[6804]: 127.0.0.1 - - [16/Jan/2020:23:18:22 +0000] "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0"

==> registry.log <==
Jan 17 00:18:22 172.28.0.1 registry[6804]: 127.0.0.1 - - [16/Jan/2020:23:18:22 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"

==> core.log <==
Jan 17 00:18:22 172.28.0.1 core[6804]: 2020/01/16 23:18:22 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    990.995µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m

==> proxy.log <==
Jan 17 00:18:22 172.28.0.1 proxy[6804]: 127.0.0.1 - "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0" 0.001 0.004 .

==> portal.log <==
Jan 17 00:18:22 172.28.0.1 portal[6804]: 172.28.0.10 - - [16/Jan/2020:23:18:22 +0000] "GET / HTTP/1.1" 200 693 "-" "curl/7.59.0"

==> registry.log <==
Jan 17 00:18:26 172.28.0.1 registry[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:26 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"

==> registryctl.log <==
Jan 17 00:18:26 172.28.0.1 registryctl[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:26 +0000] "GET /api/health HTTP/1.1" 200 9

==> portal.log <==
Jan 17 00:18:26 172.28.0.1 portal[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:26 +0000] "GET / HTTP/1.1" 200 693 "-" "Go-http-client/1.1"

==> core.log <==
Jan 17 00:18:33 172.28.0.1 core[6804]: 2020-01-16T23:18:33Z [WARNING] [/common/utils/registry/auth/tokenauthorizer.go:266]: Schemas [] are unsupported
Jan 17 00:18:33 172.28.0.1 core[6804]: 2020-01-16T23:18:33Z [WARNING] [/common/utils/registry/auth/tokenauthorizer.go:315]: empty realm, skip
Jan 17 00:18:33 172.28.0.1 core[6804]: 2020-01-16T23:18:33Z [ERROR] [/replication/adapter/native/adapter.go:143]: failed to ping registry https://registry.opensource.zalan.do: http error: code 404, message 
Jan 17 00:18:33 172.28.0.1 core[6804]: 2020-01-16T23:18:33Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Jan 17 00:18:33 172.28.0.1 core[6804]: 2020/01/16 23:18:33 #033[1;44m[D] [server.go:2774] |     172.28.0.1|#033[43m 400 #033[0m| 128.205652ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m

==> proxy.log <==
Jan 17 00:18:33 172.28.0.1 proxy[6804]: 172.28.0.1 - "POST /api/registries/ping HTTP/1.1" 400 26 "http://localhost/harbor/registries" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" 0.129 0.128 .

==> registry.log <==
Jan 17 00:18:36 172.28.0.1 registry[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:36 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"

==> portal.log <==
Jan 17 00:18:36 172.28.0.1 portal[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:36 +0000] "GET / HTTP/1.1" 200 693 "-" "Go-http-client/1.1"

==> registryctl.log <==
Jan 17 00:18:36 172.28.0.1 registryctl[6804]: 172.28.0.8 - - [16/Jan/2020:23:18:36 +0000] "GET /api/health HTTP/1.1" 200 9

```

**Comment by drzero42** [comment]
I am also facing this issue trying to setup replication for the registry.opensource.zalan.do/teapot/external-dns image. I can't add the registry.
I am running Harbor 1.10.2.

**Comment by fredgate** [comment]
I have similar issue trying to add Azure Container Registry in Harbor 2.0.0.
I tried several settings :
- **https**://contoso.azurecr.io with valid credentials : ping fail :-\
- **https**://contoso.azurecr.io without credentials : ping is fine :-\
- **http**://contoso.azurecr.io with valid credentials : ping is fine. A replication succeeds. But the images are not present on the ACR !
- **http**://contoso.azurecr.io with invalid credentials : ping is fine :-\
- **http**://contoso.azurecr.io without credentials : ping is fine :-\

The first scenario, and only the first, should succeed. But it is not the case. All scenarios are incoherent.
I have the problem with a ACR. I also tested authentication with Docker hub and a private docker registry, and this is ok.
