### ISSUE TITLE
Failed to ping endpoint when New Registry Endpoint on Harbor Version v1.9.4-49eb397c

### ISSUE THREAD

**Issue by YuLimin** [goharbor/harbor#10508]
**Expected behavior and actual behavior:**
New Registry Endpoint from Registries menu, then got Failed to ping endpoint error message

**Steps to reproduce the problem:**
http://192.168.200.135/harbor/registries
Registries ==> New Endpoint ==>> Provider : harbor, 
Endpoint URL : http://192.168.200.231
Access ID : admin
Access Secret : Harbor12345
Verify Remote Cert : No Check

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.9.4-49eb397c]
- docker engine version: [19.03.5]
- docker-compose version: [1.25.1, build a82fef07]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

will issue **### no such host** ERROR message in the core.log

[ERROR] [/replication/adapter/native/adapter.go:143]: failed to ping registry http://192.168.200.231: Head http://192.168.200.231/v2/: Get http://registry.java2class.net/service/token?service=harbor-registry: dial tcp: lookup registry.java2class.net on 127.0.0.11:53: **### no such host**

# On host
cat /etc/resolv.conf 
```
nameserver 8.8.8.8
```
# Go into core container
docker ps | grep core
docker exec -u root -it harbor-core bash
cat /etc/resolv.conf 
```
nameserver 127.0.0.11
options ndots:0
```
cat /etc/hosts
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.4      b4cd4da88cb3
```

# Workaround
on core container, append ip dns mapping in /etc/hosts
`echo "192.168.200.231 registry.java2class.net" >> /etc/hosts`

Then Test Connection will get message "Connection tested successfully. "

**Comment by reasonerjt** [comment]
@YuLimin I think this error is expected, the hostname `registry.jave2class.net` probably cannot be resolved by `8.8.8.8` as the IP `192.x.x.x` is a private IP?

**Comment by gentoox** [comment]
We had this issue, because the containers cant resolve the hostname. Thats work from the host itself. Workaround is to modify the /etc/hosts on all containers. Solution will be a variable in harbor.yml for extra_hosts that can be set over docker-compse extra_hosts for all containers. Is that possible?

**Comment by Kawsar060** [comment]
> We had this issue, because the containers cant resolve the hostname. Thats work from the host itself. Workaround is to modify the /etc/hosts on all containers. Solution will be a variable in harbor.yml for extra_hosts that can be set over docker-compose extra_hosts for all containers. Is that possible?

Adding extra_host works like a charm. thanks a lot 👍

**Comment by adeebsaied** [comment]
> Adding extra_host works

can you please share how this works ?
