### ISSUE TITLE
New api design is missing error log for viewing scan results

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#10529]
in the https://github.com/goharbor/community/pull/111/files  ,I cannot find the api that error log for viewing scan results
![image](https://user-images.githubusercontent.com/29826789/72675437-15600400-3abf-11ea-9f9e-53cd5985c5ee.png)

**Comment by smclinden** [comment]
This also appears to be an issue with the Harbor UI from version 1.11. There is no option to drill down on the vulnerabilities detected by the scanners.

Would downgrading correct this?

**Comment by heww** [comment]
Closed by #11001
