### ISSUE TITLE
Use controller rather than manager in the API handler and middleware

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10552]

**Comment by wy65701436** [comment]
close it as PR merged. https://github.com/goharbor/harbor/pull/10652

**Comment by ywk253100** [comment]
Let's reopen it as there are still some middleware/handlers consuming pkg mgr directly:
https://github.com/goharbor/harbor/blob/master/src/server/middleware/manifestinfo/manifest_info.go#L7
https://github.com/goharbor/harbor/blob/master/src/server/v2.0/handler/artifact.go#L26

**Comment by ywk253100** [comment]
Done
