### ISSUE TITLE
Vulnerability count summer UI does not proper update on manual scan

### ISSUE THREAD

**Issue by andysnowden** [goharbor/harbor#10559]
When manually triggering a image scan for a tag in the UI the vulnerability count summary is appended to, not replaced.

For example if on first load a tag has 16 high, 26 medium, 19 low, 1 unknown.  After hitting "Scan" and letting it complete it will now read "32 high, 52 medium, 38 low, 2 unknown".  I believe this is just a simple issue within the UI.  The actual API return from the scan contains the proper data.

To reproduce just go to a image tag with vulnerabilities and hit "Scan" you should see the counts duplicate after the scan has finished.

**Versions:**
- harbor version: [1.9.3]
- docker engine version: [17.09.0-ce]
- docker-compose version: [1.24.1]

This is a Harbor deployment on kubernetes.

**Comment by xaleeks** [comment]
@AllForNothing @heww  please look into this, this is an urgent fix if verified

**Comment by reasonerjt** [comment]
@AllForNothing Let's double check if this is an issue in 1.10.x or 2.0.x if it's not it's a non-issue.

**Comment by AllForNothing** [comment]
Duplicated with #9425
