### ISSUE TITLE
image delete error

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#10557]
Hello.

I am using harbor 1.10.0 on the kubernetes.

I tried to delete image, it has hundreds of tags, but there's errors.
Look at below capture. 
It failed (but some tags are deleted and some are left) and main page shows gateway time-out error. (it can be related with ingress.)
if we need to wait long time, how about process in back-ground this delete action.

![image](https://user-images.githubusercontent.com/1247030/72806958-a8549600-3c99-11ea-8597-afe428a81bfc.png)

Thanks,

**Comment by ywk253100** [comment]
This should be fixed in 2.0
