### ISSUE TITLE
Adminsitration - Groups shows all the groups membership of loged in user

### ISSUE THREAD

**Issue by ntkellner** [goharbor/harbor#10556]
we´ve made an update from v1.8.2 to v1.9.4.
Now all the groups are shows, where the logged in user is a member.

It´s displayed like: "CN=Domänen-Admins,CN=Users,DC=TST,DC=xxxx,DC=de   LDAP  cn=domänen-admins,cn=users,dc=tst,dc=xxxx,dc=de"

In v1.8.2 I never saw all the member groups.
What can I do to hide this group-information?

Thanks for help

**Comment by julia0x00f** [comment]
Can confirm this issue. Recently implemented 1.9.0 and 1.10 and both shown this bug. 

When logging, harbor brings all groups user is in and sets them as groups in Harbor.

**Comment by wsg911024** [comment]
When will the bug be fixed ？

**Comment by xaleeks** [comment]
"brings all groups user is in and sets them as groups in harbor" - This is going to be a problem if verified @reasonerjt @steven-zou
