### ISSUE TITLE
admin login fail

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#10565]
Hello.

I upgraded to 1.10.0.

When my harbor URL is harbor.company.com,
access harbor.company.com (using Chrome) and 
input ID : admin and PW
but can't login.
Error message is "Invalid user name or password."

At that time, press F5 for refresh, and then
input ID : admin and PW, now I can log in.
I don't know what is F5 magic.

So now if I want to login as admin, access my harbor and then refresh one more, type ID and PW.
I don't know which part is related with this problem.

Thanks,

**Comment by pakozdy** [comment]
same like this https://github.com/goharbor/harbor/issues/9779
in 1.10 bug still persist

**Comment by Hokwang** [comment]
after cache remove, there's no problem, I will close.

**Comment by ozdemiremrah81** [comment]
> after cache remove, there's no problem, I will close.

Did you mean browser cache ? Because it solved my problem. Thanks!
