### ISSUE TITLE
The VERSIONTAG in prepare script is not set in install.sh

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10569]
Currently in the latest build of master branch.

If I run install.sh the tags of `docker-compose.yml` is set to `dev`

seems due to this line:
https://github.com/goharbor/harbor/blob/master/make/prepare#L62

I have to export VERSIONTAG before running install.sh
```
export VERSIONTAG=v1.11.0-build.2854
```

In previous versions this is not necessary.

**Comment by bitsf** [comment]
yes, it's a regression bug
we should fix this version or add a version file when package the installer
