### ISSUE TITLE
need postgresql tuning

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#10564]
Hello.

I experienced with postgresql error when I tried to replicate repository which has so many images and tags with other harbor.
```
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
<snip> (same messages continue)
```

So I googled about tuning and found out these.
http://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
https://stackoverflow.com/a/14191857/6128380
https://github.com/jfcoz/postgresqltuner

Can I edit /var/lib/postgresql/data/postgresql.conf file in harbor-prod-harbor-database-0 pod directly? (without harbor.yaml)
How to change that file easily? no vi, sed command in container. Should I use cat command?
How to change kernel.shmmax ? there's no /etc/sysctl.conf file and sysctl command.

Do you have plan for provide these tuning?

Thanks,

**Comment by wglambert** [comment]
For the running container you could try `apt update && apt install vim` and edit the config, then reload it with `psql -U postgres -c "SELECT pg_reload_conf();"`
https://github.com/docker-library/postgres/issues/217#issuecomment-413088665
And it would probably reload those settings, unless they do require a restart.

For any new container editing the postgresql.conf being supplied should also work

**Comment by Hokwang** [comment]
I changed to external postgresql so close this issue.
