### ISSUE TITLE
Unable to Verify the LDAP ssl crt

### ISSUE THREAD

**Issue by cindy-zimmerman** [goharbor/harbor#10568]
When connecting to the LDAP server in without ssl, the configuration works well.  Able to “Verify the LDAP Certificate”.  After attempting to add the Certificate in both the trusted ca-certificates and harbor.yml file, Harbor still can’t “Verify the LDAP Certificate”.  

Steps to reproduce:
1.	Add the certificate in both places
2.	Restart Harbor
3.	Navigate to the Habor Configuration page
4.	Add the credentials and click on “LDAP Verify Certificate”
5.	Click “Test LDAP Server” – The test seems to fail silently because no error message appears

Note: everything works if you don’t click on “LDAP Verify Certificate”

![Screenshot_2020-01-23 Harbor(1)](https://user-images.githubusercontent.com/3160373/73009064-cd522180-3ddd-11ea-9cf8-f49ee7dfb0bd.png)

**Comment by cindy-zimmerman** [comment]
Note: This is not a self-signed certificate

**Comment by stonezdj** [comment]
Could you please upload the /var/log/harbor/core.log ?

**Comment by cindy-zimmerman** [comment]
[core.log](https://github.com/goharbor/harbor/files/4226734/core.log)
