### ISSUE TITLE
PushedTime reset after upgrade

### ISSUE THREAD

**Issue by pakozdy** [goharbor/harbor#10570]
after upgrade all tags PushedTime are reset to same time (upgrade start time )
versions 1.7.1 -> 1.10
bad sideefect is : tag retention  is wrong because of tags  sorting by PushedTime with same value, then by Created oldest first. So newest tags are deleted when  rule is _retain most recently N# pushed_

**Comment by zeed-w-beez** [comment]
The default sorting should be `Desc by tag name`, cause most images are generated using tools such as Jenkins with incrementing IDs.

**Comment by xaleeks** [comment]
This should not be happening fyi @heww @wy65701436

**Comment by reasonerjt** [comment]
Closing as in 1.10 -> 2.1.0 upgrade this is not reproduced.
