### ISSUE TITLE
Build Releases for ARM platforms

### ISSUE THREAD

**Issue by Josua-SR** [goharbor/harbor#10578]
ARM Processors often offer lower power and cheaper processing per watt and dollar. In recent years their compute power has increased a lot and arm cpus are starting to get serious use in data-centers.

It would be really nice if Harbor could be deployed on any architecture the knowing user may want to choose. In particular I am proposing to add aarch64 to the released binaries - including the container images on dockerhub.

There appear to be only few steps required for enabling this:
- Switch to PhotonOS 3.0 which introduced support for arm64
- Build `goharbor/*-base` containers for aarch64
- Build goharbor itself on any aarch64 device (avoids the need for qemu integration)

**Comment by hzliangbin** [comment]
someone  has a solution?

**Comment by AGSaidi** [comment]
Is there anything we can do to unblock this?  Is the harbor team willing to take patches to enable testing and artifact building via Travis (because there good support) @xaleeks?

**Comment by hzliangbin** [comment]
@AGSaidi I tested some images by myself. https://github.com/hzliangbin/harbor-arm64

**Comment by tferic** [comment]
With more ARM systems coming into market, this topic is becoming more significant.
(Apple Silicon, Huawei Kunpeng, Raspberry Pi)

**Comment by pbk8s** [comment]
@tferic I second that. It would be really helpful to have an arm64 based harbor binary, especially for edge use cases.

**Comment by pugna0** [comment]
We need to run harbor containers on Kylin OS(aarch64), please offer official images on ARM, it is troubling to build images personally in a protected network area.

**Comment by jnschaeffer** [comment]
This would be a huge plus for me as well; I am currently unable to deploy Harbor in my current ARM environment.

**Comment by morlay** [comment]
Hi guys. need your help to test the arm64 images version.

use the images under https://hub.docker.com/u/harbortest (tag `dev`). see more in the linked PR

**Comment by dcharbonnier** [comment]
@morlay could you build also the arm image versions ?

**Comment by morlay** [comment]
@dcharbonnier 
nope, only aarch64（i only test on arm/v8 device, arm/v7 with 64 bit may work）, aarch32 not provided by the upstreams, like `photon:3.0`

**Comment by xaleeks** [comment]
Thanks a lot for this @morlay

**Comment by xaleeks** [comment]
Can everyone provide some datapoints in terms size of deployments and adoption rate of arm vs x86 in your companies.  Unfortunately, we as the harbor team have very little data so looking for external feedback here.

**Comment by morlay** [comment]
`aarch64:x86_64` in my clusters is `1:1` or `2:1`. (aarch64 host is cheaper)
application layer is not really care about cpu arch .

Howerever, mine is not a general needs. I may deploy whole solution to aarch64 or x86_64 cluster, from k3s for small to k8s for large cluster.

so I need to prepare multi-arch image for my applications in the solution.

modern programming languages provide cross compiling.
with docker buildx's help, i coud be easy to build the multi-arch image.

**Comment by amoravek** [comment]
Hi there. Our company would much appreciate the multiarch - we have 17 arm64 nodes per cluster and also plan to use the new Amazon Graviton2 instances. I think ARM is on rise and its support should be considered. Our planned volume for this year is to deliver tenths of our clusters and also to switch our infrastructure to cheaper and more powerful ARM cloud instances.

**Comment by blackliner** [comment]
still getting `exec ./docker-entrypoint.sh: exec format error` for `goharbor/chartmuseum-photon:v2.6.1` :-(
