### ISSUE TITLE
The status of endpoint is unhealthy in Registries

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#10583]
I am trying to add the endpoint in Registries but the status of the endpoint is unhealthy.
The test connect was successful.

Service has two Registry VMs, 2 ScalableLB, 1 PostgreSQL and 1 Redis.

Could you please help

**Comment by AyushCloud** [comment]
![Issue](https://user-images.githubusercontent.com/53472266/73256073-45a65180-41e7-11ea-9b1c-d98b449a6589.PNG)

**Comment by xaleeks** [comment]
@steven-zou

**Comment by AyushCloud** [comment]
[ERROR] [/replication/adapter/native/adapter.go:143]: failed to ping registry URL: http error: code 401, message

**Comment by AyushCloud** [comment]
[ERROR] [/core/filter/security.go:434]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'

**Comment by AyushCloud** [comment]
Could you please let me know if any more information is required regarding the issue.

The replication seems to b working on 1 Scalable LB, 1 Registry , 1 PostgreSQL, 1 Redis VM but not with the above HA pattern.

**Comment by AyushCloud** [comment]
I have same /data/secret/registry/root.crt and /data/secret/core/private_key.pem. Does the /data/secret nedds to be same ?

**Comment by steven-zou** [comment]
@AyushCloud 

The credential provided when adding your registry is correct? From the log, it seems the cred is a valid one.

@ywk253100 may give more info about this issue.

**Comment by AyushCloud** [comment]
The issue is resolved. I have sync the /data/secrets on both the Harbor VMs
