### ISSUE TITLE
no administration menu on harbor gui

### ISSUE THREAD

**Issue by vmanyushin** [goharbor/harbor#10585]
i'm install fresh installation using harbor-helm v1.3.0, first harbor-core (v.1.10.0) can't start with message:
`
2020-01-28T22:22:42Z [INFO] [/core/main.go:181]: configurations initialization completed                                                                                                                 │
│ 2020-01-28T22:22:42Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-registry2-harbor-database port-5432 databse-registry sslmode-"disable"                                  │
│ 2020-01-28T22:22:42Z [INFO] [/common/dao/base.go:89]: Register database completed                                                                                                                        │
│ 2020-01-28T22:22:42Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...                                                                                                                   │
│ 2020-01-28T22:22:42Z [ERROR] [/common/dao/pgsql.go:124]: Failed to upgrade schema, error: "file does not exist"                                                                                          │
│ 2020-01-28T22:22:42Z [FATAL] [/core/main.go:188]: failed to initialize database: file does not exist
`

no luck with v.1.10.0-dev, same error.

when i'm set dev tag for harbor-core image, pod started. Then i login to GUI as admin and i can't see any admin settings from menu.

https://yadi.sk/i/0GmLGN-S47B5dw

how to fix this issue?

**Comment by bitsf** [comment]
what's your full helm command ?

**Comment by cjstetson** [comment]
I have sam issue using helm and images tagged v1.10.0

**Comment by cjstetson** [comment]
I pulled down helm chart tagged version 1.10.0 and its working

**Comment by catchups** [comment]
> I pulled down helm chart tagged version 1.10.0 and its working

@cjstetson Did you solve this problem?

**Comment by bitsf** [comment]
current helm release is 1.3.1, should have a try on this.
And if yo are fresh install, it should not say "Failed to upgrade schema", you can "kubectl get pvc " to check if there're old volumes and delete them before retry

**Comment by cjstetson** [comment]
It did, plus will pull down latest chart 1.3.1 and test as well

--
Chris
