### ISSUE TITLE
RFE: Configure Deployment security and Vulnerability scanning when creating projects

### ISSUE THREAD

**Issue by konstruktoid** [goharbor/harbor#10582]
**Is your feature request related to a problem? Please describe.**
When creating a project it would be convenient to have the options to set Deployment security and Vulnerability scanning on the project level. This so you don't have to configure every repository afterwards, this especially when replication is used.  

**Describe the solution you'd like**
When clicking Projects -> New Projects -> Deployment security and Vulnerability scanning, in addition to Storage quota, should be available as configuration options.

**Comment by xaleeks** [comment]
Not understanding, these are already at the project level.  It's the exact workflow you described in your desired solution.  Feel free to reopen if I'm misunderstanding requirement.  If you're talking about do this at the repo level, it's not happening, there's no driver for it.
