### ISSUE TITLE
gpg verification does not work on Mac OSX

### ISSUE THREAD

**Issue by governmentissueprogrammer** [goharbor/harbor#10584]
When I run gpg -v --keyserver hkps://keyserver.ubuntu.com --verify harbor-online-installer-v1.9.4.tgz.asc, I expect to see verification.  Instead, I get the following:

gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.

I am running the gpg command on a MacOSX.  I am using the 1.9.4 versions of harbor, both offline and online installers.

**Comment by governmentissueprogrammer** [comment]
This does in fact work on MacOSX.  The error was a user error.

**Comment by VictorMBalves** [comment]
I have the same problem in Ubuntu 18.04.4 LTS
