### ISSUE TITLE
Doc links are broken

### ISSUE THREAD

**Issue by sudhakarau1** [goharbor/harbor#10593]
The doc links leading from https://github.com/goharbor/harbor/blob/master/docs/user_guide.md are broken, https://github.com/goharbor/harbor/blob/master/docs/1.10/index.md returns a 404

**Comment by xaleeks** [comment]
@stuclem Hey Stuart, please look into this, since there are quite a few doc related change requests being worked on right now.

**Comment by stuclem** [comment]
The index.html file has been renamed and its contents removed. This must be related to the migration to Netlify. I have contacted the people responsible for the migration to ask them to bring the harbor docs index back online.

**Comment by stuclem** [comment]
This has been fixed, so that the links from the old pages now point to https://github.com/goharbor/harbor/tree/master/docs/1.10.

See https://github.com/goharbor/harbor/blob/master/docs/user_guide.md for an example.
