### ISSUE TITLE
Allow setting project default configuration

### ISSUE THREAD

**Issue by ajchiarello** [goharbor/harbor#10599]
**Is your feature request related to a problem? Please describe.**
Every time I need to create a new project, I need to change several settings in the Configuration page (such as 'Automatically scan images on push'). This grows tedious, and is prone to be overlooked, resulting in inconsistent configuration.

**Describe the solution you'd like**
I would like to be able to define a default configuration for a project, so that new projects are already configured as desired.

**Comment by xaleeks** [comment]
I don't envision doing this, it's easy to enable these in project config, just a few clicks.  If you're doing bulk project creation, I'd be more interested in why and if we can improve tenancy model to cover this

**Comment by ajchiarello** [comment]
@xaleeks It's not about bullk creation - it's about providing defaults that match our internal policies. I manage our harbor instance, but it is used by a pool of developers who make projects as they need them, but often forget to change the settings to match our standards. I would like to be able to configure Harbor to automatically configure those items, so that we don't need to run regular reports and rectifications.

**Comment by stacylacy6** [comment]
I agree with @ajchiarello, we have a similar situation.  We need to be able to have defaults set to enable scanning and set a few other setting to make thing easier.  We are keeping the flexibility of letting developers create their own projects and manage them, but need to have them at least start with the "right" defaults.

**Comment by xaleeks** [comment]
Sorry guys, this doesn't have enough buy in from other users and our team.  The notion that this can meaningfully reduce redundancy is a dubious one at best
