### ISSUE TITLE
Is there any solution for 504 Gateway time out error.

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#10590]
Is there any solution for 504 Gateway time out error. There are multiple tasks (replication/repo deletion/rest api) are getting failed due to this error.

<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>

**Comment by dbenduga** [comment]
Harbor registry is not configured behind any proxy.  Is there any settings in nginx.conf file to fix gateway timeout issue?

**Comment by wglambert** [comment]
Duplicate of https://github.com/goharbor/harbor/issues/9535

Are you getting this error intermittently or on startup? Is there a specific action that triggers this like in https://github.com/goharbor/harbor/issues/8037

**Comment by dbenduga** [comment]
getting this error intermittently. Normally error occurred during image push and  replication  and sometime while login.
Is it related to jobservice "max_job_workers" ? As of now, I have set max_job_workers to 100. I am using 6 CPU, 26 GB RAM and 10GB network port

This is my assumption, If  all job workers utilized system unable to serve request therefore we are getting this error... please correct me if i am wrong here

**Comment by xiaochonghao** [comment]
i meet this question too.....
