### ISSUE TITLE
Link to installation guide from home page is broken.

### ISSUE THREAD

**Issue by acolombi** [goharbor/harbor#10609]
![2020-01-31 15 10 30](https://user-images.githubusercontent.com/707331/73580830-eab96800-443b-11ea-9e2b-7faf0e3f7e20.gif)

**Comment by fengjihu** [comment]
Yes，It's 404 error。

**Comment by gurayyildirim** [comment]
Same as #10593.

The documentation is being formatted and newly merged. There are some PRs to fix this issue. In the meantime; that link is active (append underscore before `index.md` in URI [Docs](https://github.com/goharbor/harbor/blob/master/docs/1.10/_index.md)

**Comment by acolombi** [comment]
Yeah, I found that page, but it didn't seem like much of an improvement over the 404.

![image](https://user-images.githubusercontent.com/707331/73597330-a41d4980-44df-11ea-8845-d46df3f2db5d.png)

**Comment by wy65701436** [comment]
thanks @acolombi , we will fix the link soon.

**Comment by jonasrosland** [comment]
I’ll get the links fixed tomorrow. For now, just use the folder https://github.com/goharbor/harbor/tree/master/docs/1.10 and go to the subfolders you’re interested in.

**Comment by lachlanmunro** [comment]
FYI with the new look at https://goharbor.io/ the following links result in some flavour of not found:

* Getting started (hot button and menu item)
* Harbor Installation and Configuration
* Harbor Administration

**Comment by jonasrosland** [comment]
Thanks for the ping @lachlanmunro , will fix!
