### ISSUE TITLE
Jobservice continually running scan for missing objects after upgrade to v1.10.0

### ISSUE THREAD

**Issue by stephenwolfe1** [goharbor/harbor#10611]
**Expected behavior and actual behavior:**
Expected: Missing objects from deleted tags are purged. Image scanning completes successfully. Jobservice shows appropriate activity and resource usage when nothing is running.

Actual: Prior to upgrading from v1.7.5 to v1.10.0 there were many 0kb tags orphaned from being deleted in the UI. Didn't happen on every delete but the orphaned tags could not be removed. After upgrade, the Scan Now button was greyed out in the UI and showed a spinning progress for days. Setup a daily cron for scanning, but the UI never showed them completing. Scan cron has been disabled, but jobservice has consistently high CPU usage and logs are flooded with INFO and ERROR messages for IMAGE_SCAN "object is not found". Containers have been restarted and cron has been disabled for a few days now, no change in jobservice activity.

**Steps to reproduce the problem:**
Delete tags in a previous version, v1.7.5 should work
Once there are orphaned tags that don't delete and show 0kb, upgrade to v.1.10.0
Tail jobservice logs, or run a scan and tail logs

**Versions:**
- harbor version: [v1.10.0]
- docker engine version: [18.09.9-ce]
- kubernetes version: [v1.14.9]

**Additional context:**
Harbor v1.10.0 deployed to kubernetes using harbor helm chart
- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
Sample attached, jobservice log is streaming the same messages for various object id's
[jobservice.log](https://github.com/goharbor/harbor/files/4143166/jobservice.log)

**Comment by steven-zou** [comment]
@stephenwolfe1 

The "not found" in the job error means the relevant job stats are missing, not related to the 0 size image.

That's high probably an error job repeating bug. I'll take a look.

A simple workaround fix approach:

- Stop all the cron jobs
- Make sure other jobs are completed
- Connect to redis db and remove the following keys
  - {harbor_job_service_namespace}:jobs:IMAGE_SCAN
  - {harbor_job_service_namespace}:retry
- restart the jobserevice


Then check if there are still the not found errors.

**Comment by steven-zou** [comment]
@heww 

Base on our new artifact data model in 2.0, I think this will not be an issue anymore, right?

If it is still existing, then I suggest adding extra artifact validation logic before launching the scan job to avoid subsequent problems.

**Comment by rob8714** [comment]
Facing a similar issue with the Scan Now butting greyed out and the UI and showing a spinning progress for days in v1.10.1, however cannot stop the cron... getting the below error:

```
==> jobservice.log <==

Mar 15 07:44:13 172.23.0.1 jobservice[75447]: 2020-03-15T07:44:13Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/f20197e40ef772dfd650a48d' error: 500 {"code":10006,"message":"stop job failed with error","details":"no valid periodic job policy found: f20197e40ef772dfd650a48d:1561475649"}

 

==> core.log <==

Mar 15 07:44:13 172.23.0.1 core[75447]: 2020-03-15T07:44:13Z [ERROR] [/common/api/base.go:233]: http error: code 500, message {"code":10006,"message":"stop job failed with error","details":"no valid periodic job policy found: f20197e40ef772dfd650a48d:1561475649"}

Mar 15 07:44:13 172.23.0.1 core[75447]: 2020-03-15T07:44:13Z [ERROR] [/common/api/base.go:73]: PUT /api/system/scanAll/schedule failed with error: {"code":500,"message":"Internal Server Error"}

Mar 15 07:44:13 172.23.0.1 core[75447]: 2020/03/15 07:44:13.886 #033[1;44m[D]#033[0m [server.go:2774]  |  172.16.114.72|#033[97;41m 500 #033[0m|   3.079076ms|   match|#033[97;43m PUT     #033[0m /api/system/scanAll/schedule   r:/api/system/scanAll/schedule
```

**Comment by stephenwolfe1** [comment]
Same issue after clearing redis keys. Started a new scan once everything was clean and it stalls about half way and jobservice is spewing logs again. It's enough logging that it is crashing the fluentd collector we use and causing host issues.
