### ISSUE TITLE
Generate challenge for GET /v2 in Harbor

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10610]
Currently when CLI sends "ping /v2" request to Harbor, the request was proxied to registry, which will return a response recognizable by the CLI.

However, there may be scenario in future that the auth mode in Harbor is not the same as the setting in registry.  Hence, ideally the challenge header should be generated in Harbor's middleware.

We may probably defer this to post 2.0 when the auth section is implemented in the distribution-spec.

**Comment by ywk253100** [comment]
Done
