### ISSUE TITLE
Harbor is set to read-only mode, Deleting repository, tag and pushing image will be disabled under read-only mode.

### ISSUE THREAD

**Issue by shashank-k** [goharbor/harbor#10615]
What can we help you?
I am not sure how to come our of this issue. I restarted the harbor using docker compose commands, but it is still giving me the same issue. Harbor version is 1.9

**Comment by shashank-k** [comment]
I think one of the GC is struck. 

![image](https://user-images.githubusercontent.com/7534403/73629279-96e79280-4678-11ea-9616-4e185f4a7827.png)

Is there a way to force stop it.

**Comment by shashank-k** [comment]
Fixed.

**Comment by jaekwonpark-flo** [comment]
i have same Issue. how to fix it?

**Comment by shashank-k** [comment]
May I know which version you are using? 
In the configuration there is an option. You can uncheck it

![image](https://user-images.githubusercontent.com/7534403/74807711-20e95980-530f-11ea-9865-82f0b3560720.png)

**Comment by jaekwonpark-flo** [comment]
Thanks to reply 

as you know,   i've unchecked that option.  and problem solved. 

Thanks
