### ISSUE TITLE
Clair output has no details in 1.10.0

### ISSUE THREAD

**Issue by titpetric** [goharbor/harbor#10613]
**Expected behavior and actual behavior:**

I've set up harbor 1.10 with `./install --with-clair`, and modified it to run behind a https proxy (reconfigured auth and core/env to use https:// links to the registry and removed X-Forwarded-Proto in proxy nginx.conf). So far so good.

Looking at the docs [here](https://github.com/goharbor/harbor/blob/master/docs/1.10/administration/vulnerability-scanning/scan-individual-image.md) I see that there should be some level of detail to the clair scanning (e.g. number of detected packages and so on.).

![image](https://user-images.githubusercontent.com/233360/73609363-2f283d80-45cd-11ea-880b-b2bbb87a819b.png)

I only get a "No vulnerability" message, both in the image detail view, and on the image tags view. I tried enabling debug output for clair but there isn't any error output in the logs. Each layer seeminly gets pushed to clair and analyzed.

Looking at the API calls made in the browser (the manual /scan endpoint):

![image](https://user-images.githubusercontent.com/233360/73609506-a1e5e880-45ce-11ea-92bb-1178f63e85c5.png)

I've also verified that the vulnerability database is downloaded and stored in harbor-db. There are no usable errors in the /var/log/harbor log files, even after increasing the harbor output to `debug` level.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.0
- docker engine version: 18.09.5
- docker-compose version: 1.24.0

**Comment by titpetric** [comment]
Additionally, high cpu usage is noticed on the `clair` process, while no scanning is active.

**Comment by titpetric** [comment]
It seems this started working after hours of uptime (today I'm getting results for debian based images, alpine images are still reported with no details). I suppose it's gonna resolve itself with time. Leaving open because some warning should be printed here, and not "No vulnerability" (misleading).

**Comment by steven-zou** [comment]
@titpetric 

Clair scanning depends on the CVE database which needs a while to be downloaded from the internet. There will be no CVE data for a harbor fresh installation. Without data, the scanning report will be shown as no vulnerability.

As it works as designed. I'll close this issue now.

**Comment by titpetric** [comment]
Is there a way to improve this behavior:

- could we have a status indicator if clair has it's database downloaded fully?
- is it possible to have a progress bar for clair downloads?

From what limited output there is in the docker log output, clair should have downloaded all the data relatively fast, and I can't reasonably guess why it would take 12hr+ for the vulnerability data to show up. I was honestly thinking this is a browser caching issue, but didn't figure it out :(
