### ISSUE TITLE
move from SHA1 to a decent hash algorithm

### ISSUE THREAD

**Issue by tronicum** [goharbor/harbor#1061]
Please move to a decent hash algorithm. 
( https://www.schneier.com/blog/archives/2005/02/sha1_broken.html )

yes, your hashes are salted, but SHA1 sould be exchanged with something safer, e.g.  SHA512 (like SHA512_256). The code change would be minimal, just replace sha1.New with Sha512_256.New.

To make migration easy I would suggest to prepend the hash with the hashing algo used like
{SHA1}oldhashes
{SHA512_256}newhashes
and add a migration script that adds {SHA1} to all old hashes.

**Comment by tronicum** [comment]
there might be safer other hash algorithms that might be available with other go dependencies

**Comment by reasonerjt** [comment]
@tronicum 
Thanks for pointing out, but based on by investigation a couple of months ago, the collision issue of SHA1 has little impact on  the security of HMAC-SHA1?

**Comment by tronicum** [comment]
https://mathiasbynens.be/notes/pbkdf2-hmac
http://crypto.stackexchange.com/questions/26510/why-is-hmac-sha1-still-considered-secure

it is complicated, true. I still would recomend not using is, as the amount of crypto attacks on sha1 is growing, it's like using MD5 forever because it is so easy to implement.

**Comment by tronicum** [comment]
Based on the above link, even PBKDF2-HMAC-SHA256 might be bad.

**Comment by tronicum** [comment]
I guess something like SHA3 would be nice https://godoc.org/golang.org/x/crypto/sha3

**Comment by tronicum** [comment]
I added an example with sha3.ShakeSum256 @ PR #1060

**Comment by jcmartins** [comment]
My suggest is Blake2 it's very fast
https://godoc.org/golang.org/x/crypto/blake2b

See more details
https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/
