### ISSUE TITLE
Link shared gives 404 Error

### ISSUE THREAD

**Issue by aslam711** [goharbor/harbor#10616]
If you are reporting a problem, please make sure the following information are provided:

https://github.com/goharbor/harbor/blob/master/docs/1.10/index.md.

above link does not work.

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by xaleeks** [comment]
Hi, where is this link shared?

**Comment by xaleeks** [comment]
@stuclem please watch for this

**Comment by stuclem** [comment]
@xaleeks this must be related to the migration to Netlify. I will investigate.

**Comment by stuclem** [comment]
The index.html file has been renamed and its contents removed. This must be related to the migration to Netlify. I have contacted the people responsible for the migration to ask them to bring the harbor docs index back online.

**Comment by jonasrosland** [comment]
I’ll get the links fixed tomorrow. For now, just use the folder https://github.com/goharbor/harbor/tree/master/docs/1.10 and go to the subfolders you’re interested in.
