### ISSUE TITLE
Request Entity Too Large?

### ISSUE THREAD

**Issue by ruanshudong** [goharbor/harbor#10621]
I push a big docker images, about 2G:

then I got: 
error parsing HTTP 413 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

harbor version:1.9.4

**Comment by bitsf** [comment]
I push a 3G image successfully.
Do you have any special setting

**Comment by catchups** [comment]
Under what circumstances are you operating the harbor? Increase Nginx's proxy body size
