### ISSUE TITLE
Make sure docker volume plugin supported after change to basic auth

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10620]
Verify change to basic auth takes care of docker volume plugin push as discussed here https://github.com/goharbor/harbor/issues/1532

**Comment by reasonerjt** [comment]
There's issue in artifact controller to return failure when pushing the docker plugin. 

I opened issue https://github.com/goharbor/harbor/issues/10811

I'll keep this open until e2e works.

**Comment by reasonerjt** [comment]
I verified I can push to latest dev build:
```
# docker plugin push jt-dev.local.goharbor.io/library/sshfs:latest
The push refers to repository [jt-dev.local.goharbor.io/library/sshfs]
ce2b7a99c5db: Pushed
latest: digest: sha256:1d3c3e42c12138da5ef7873b97f7f32cf99fb6edde75fa4f0bcf9ed277855811 size: 519
```

Note we don't have a resolver for docker plugin so Harbor cannot know the type of this artifact, but I think this works as design.

Closing
