### ISSUE TITLE
How to use company Wildcard certificates for harbor ssl connection

### ISSUE THREAD

**Issue by ifoyil** [goharbor/harbor#10642]
What can we help you?
Hi,

Is there any possibility to use wildcard.pfx certificate for SSL connection on docker harbor,
We have windows active directory environment and we have secure domain, for internally connection can we do ssl secure for docker harbor ? we used openssl for converting pfx to *.crt & *.key But docker harbor doesn't work properly nginx container has always tring to restarting itself 
If you assist me I can be appreciate

1252106c9688        goharbor/nginx-photon:v1.9.4                             "nginx -g 'daemon of…"   10 minutes ago      Restarting (1) 6 seconds ago                               nginx

**Comment by bitsf** [comment]
When install harbor, you can setup crt and key in harbor.yml https section.

If nginx always restart, you can check /var/log/harbor/proxy.log, maybe helpful

**Comment by ifoyil** [comment]
Thank you bitsf,
I checked as like error messages but I am sure convert to wildcard.pfx to requral *.crt and *.key files

nginx: [emerg] cannot load certificate key "/etc/cert/server.key": PEM_read_bio_PrivateKey() failed (SSL: error:0906D06C:PEM routines:PEM_read_bi$

**Comment by bitsf** [comment]
if you check the docker-compose.yml, you'll find /etc/cert/server.key is actually mounted from /data/secret/cert/server.key, and you should check if this file is exists now, and whether the permission is correct

![image](https://user-images.githubusercontent.com/188115/74130731-b30da580-4c1d-11ea-9707-8cdbfae165d2.png)

![image](https://user-images.githubusercontent.com/188115/74130658-86f22480-4c1d-11ea-96b8-cf953da8d4df.png)

**Comment by ifoyil** [comment]
Hi  @bitsf  you're right I have convert problem Wildcard.pfx  to  requral *.crt  *.key file 
I did as below of the links, after that I put certificates to related paths, and SSL Docker harbor has been worked properly.
Thanks a lot somuch
https://www.markbrilman.nl/2011/08/howto-convert-a-pfx-to-a-seperate-key-crt-file/
