### ISSUE TITLE
harbor-adminserver is always restart when upgrade 1.5.4 to 1.6.3

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#10641]
Expected behavior and actual behavior:
a67029c7b30a        goharbor/harbor-adminserver:v1.6.3       "/harbor/start.sh"       5 minutes ago       Restarting (1) 34 seconds ago

Steps to reproduce the problem:
upgrade from 1.5.4 to 1.6.3
then docker-compose up

Versions:
Please specify the versions of following systems.

harbor version: 1.6.3
docker engine version: 18.06.1-ce
docker-compose version: 1.24.0
Additional context:

Harbor config files: You can get them by packaging harbor.yml and files in the same directory, including subdirectory.
Log files: You can get them by package the /var/log/harbor/ .

Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] initializing system configurations...
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] Upgrading schema for pgsql ...
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] No change in schema, skip.
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] Register database completed
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [INFO] the path of key used by key provider: /etc/adminserver/key
Feb  5 13:34:53 172.25.0.1 adminserver[882]: 2020-02-05T05:34:53Z [FATAL] [main.go:46]: failed to initialize the system: pq: null value in column "id" violates not-null constraint
Feb  5 13:35:53 172.25.0.1 adminserver[882]: 2020-02-05T05:35:53Z [INFO] initializing system configurations...
Feb  5 13:35:53 172.25.0.1 adminserver[882]: 2020-02-05T05:35:53Z [INFO] Upgrading schema for pgsql ...
Feb  5 13:35:53 172.25.0.1 adminserver[882]: 2020-02-05T05:35:53Z [INFO] No change in schema, skip.
Feb  5 13:35:53 172.25.0.1 adminserver[882]: 2020-02-05T05:35:53Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"

**Comment by bitsf** [comment]
@reasonerjt Do you still remember if there's known upgrade problem in 1.6

**Comment by liy516** [comment]
> @reasonerjt Do you still remember if there's known upgrade problem in 1.6

I resloved this problem,Because the description field in the repository table leaded to this!

**Comment by FirstEncounter** [comment]
> > @reasonerjt Do you still remember if there's known upgrade problem in 1.6
> 
> I resloved this problem,Because the description field in the repository table leaded to this!

Hoow did you resloved it? Thanks

**Comment by timgriffiths** [comment]
Well this is frustrating ... how do we get past this I am hitting this as well
