### ISSUE TITLE
API endpoint for Vulnerability details returns 404

### ISSUE THREAD

**Issue by Sudneo** [goharbor/harbor#10659]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior**

Querying this API endpoint should return an object such as

```
[
  {
    "version": "string",
    "description": "string",
    "package": "string",
    "id": "string",
    "fixedVersion": "string",
    "severity": 0
  }
]
```

**Actual behavior:**

Querying the endpoint returns 404.
![screenshot](https://user-images.githubusercontent.com/12257584/73945809-901d8180-48fd-11ea-804f-da7543e916f4.png)

**Steps to reproduce the problem:**

Execute the query from Swagger UI or execute the same query via CLI.

```
curl -X GET "https://$HARBOR_URL/api/repositories/$REPOSITORY/tags/$TAG/vulnerability/details" -H "accept: application/json" -H "authorization: Basic $BASIC_BASE64" -H "X-Xsrftoken: $TOKEN" 
```

**Versions:**

- harbor version: 1.10.0
- docker engine version: Docker version 19.03.5, build 633a0ea838
- docker-compose version: docker-compose version 1.25.3, build d4d1b42b

**Additional context:**

I am running Harbor behind Haproxy, everything else works fine (Docker pull/push, other API endpoints, WebUI etc.). Clair is installed, Vulnerability databases are downloaded, scans run successfully and I can explore the vulnerabilities from UI.

I managed to get the result I wanted by checking what the browser normally requests to Harbor. I noticed that when loading a tag page (meaning the details for a specific tag for a repository in a project), the browser made a request to `/api/repositories/$REPOSITORY/tags/$TAG/scan`.

In order to get this query to work I had both to change the endpoint and to also add headers.

```
Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0
Content-Type: application/json
```

Resulting in the following query:

```
curl -X GET "https://[redacted]/api/repositories/[redacted]/tags/latest/scan" -H "Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0" -H"Content-Type: application/json" -H "authorization: Basic [redacted]" -H "X-Xsrftoken: [redacted]" >> resp.json
```

- **Log files:** 

From proxy.log

```
Feb  6 14:18:16 192.168.192.1 proxy[7161]: 192.168.192.1 - "GET /api/repositories/[redacted]/tags/latest/vulnerability/details HTTP/1.1" 404 515 "https://[redacted]/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" 0.005 0.008 .
```

From `core.log`

```
Feb  6 14:18:16 192.168.192.1 core[7161]: 2020/02/06 14:18:16 #033[1;44m[D] [server.go:2774] |  192.168.192.1|#033[43m 404 #033[0m|    5.08863ms| nomatch|#033[44m GET     #033[0m /api/repositories/antivirus/tags/latest/vulnerability/details#033[0m
```

No other log gets generated with this request at the best of my knowledge.

- **Additional Info:**

It might be that the issue is a simple as from incomplete/incorrect swagger documentation.

**Comment by steven-zou** [comment]
@Sudneo 

High probably a swagger API bug.

The endpoint `https://$HARBOR_URL/api/repositories/$REPOSITORY/tags/$TAG/vulnerability/details` should not be available anymore in the laetst version.

Get the vulnerability report should be via `https://[redacted]/api/repositories/[redacted]/tags/latest/scan`.
