### ISSUE TITLE
Error  based on pull_based mode replication policy

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#10677]
What can we help you?
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_gcc_web' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_gcc_web/tags: read tcp 172.18.0.7:48038->192.168.56.102:80: read: connection reset by peer
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_ccc_manager' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_ccc_manager/tags: read tcp 172.18.0.7:48062->192.168.56.102:80: read: connection reset by peer
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_es_query' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_es_query/tags: read tcp 172.18.0.7:48014->192.168.56.102:80: read: connection reset by peer
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_ppc_uniproxy' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_ppc_uniproxy/tags: read tcp 172.18.0.7:48086->192.168.56.102:80: read: connection reset by peer
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_pcc_aa_flow' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_pcc_aa_flow/tags: read tcp 172.18.0.7:48156->192.168.56.102:80: read: connection reset by peer
Feb  7 22:31:22 172.18.0.1 core[52838]: 2020-02-07T14:31:22Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'zongbu_newcs_cs/cs_gcc_send_sms' error: Get http://192.168.56.102/api/repositories/zongbu_newcs_cs/cs_gcc_send_sms/tags: read tcp 172.18.0.7:48102->192.168.56.102:80: read: connection reset by peer

Resource filter:
{zongbu_iom_test,zongbu_jxc_prod,zongbu_jxc_test,zongbu_migrationshow_test,zongbu_newcs01_test,zongbu_newcs02_test,zongbu_newcs03_test,zongbu_newcs04_test,zongbu_newcs05_test,zongbu_newcs06_test,zongbu_newcs07_test,zongbu_newcs08_test,zongbu_newcs09_test,zongbu_newcs10_test,zongbu_newcs11_test}/**

**Comment by steven-zou** [comment]
replication between harbor to harbor?

I suggest you can check if the registry you're pulling images from is connected. 
`read: connection reset by peer`

**Comment by liy516** [comment]
yes,it's replication between harbor to harbor!
