### ISSUE TITLE
Unable to create robot account via API

### ISSUE THREAD

**Issue by vpecinka** [goharbor/harbor#10672]
**Expected behavior and actual behavior:**
I would like to create a robot account via API, however it always ends with the error:

`{"code":400,"message":"push action of repository resource not exist in project my_project"}`

no matter if I try push or pull action. I am using swagger ui (authorized with my LDAP account, not robot account, and being owner of the project_id 24) and posting this json

```json
{
  "access": [
    {
      "action": "pull",
      "resource": "repository"
    }
  ],
  "name": "test",
  "description": "testik"
}
```

the curl command is (sensitive info removed):

`curl -X POST "https://<sensitive>/api/projects/24/robots" -H "accept: application/json" -H "authorization: Basic <sensitive>" -H "Content-Type: application/json" -d "{ \"access\": [ { \"action\": \"pull\", \"resource\": \"repository\" } ], \"name\": \"test\", \"description\": \"testik\"}"`

**Versions:**
- harbor version: 1.9.0

**Comment by RajkumarRajangam** [comment]
You have to specify the project id in the resource field as below.
{
  "access": [
    {
      "action": "pull",
      "resource": **"/project/24/repository"**
    }
  ],
  "name": "test",
  "description": "testik"
}

**Comment by vpecinka** [comment]
Thanks, that works.

**Comment by aldosr** [comment]
Reopening this to request more information. I'm following the exact flow described by @vpecinka, using this configuration:
```
{
  "access": [
    {
      "action": "pull",
      "resource": "repository"
    }
  ],
  "name": "test",
  "description": "testik"
}
```

and this curl command:
```
curl -X POST "https://<sensitive>/api/projects/test/robots" \
-H "accept: application/json" \
-H "authorization: Basic <sensitive>" \
-H "Content-Type: application/json" \
-d '{
  "access": [
    {
      "action": "pull",
      "resource": "project/test/repository"
    }
  ],
  "name": "robot-test",
  "description": "test"
}'

```
However, this does not work when using the project name in the resource field: `"resource": "project/test/repository"`.

It only works when using the project ID, e.g.,`"resource": "project/4/repository"`.

Is it not possible to use the project name in the resource field?
