### ISSUE TITLE
How to get rid of the project name when replication happens in AWS ECR

### ISSUE THREAD

**Issue by shashank-k** [goharbor/harbor#10692]
**Harbor Version used : 1.10**

When we are replicating to ECR from harbor, the project name is added in AWS ECR

For example, if my project name is `test`, the images will be tagged like `<harbor>test/nginx:v1` in harbor. 
When I replicate to ECR, I expect only `<aws_ECR>/nginx:v1` and not `<aws_ECR>/test/nginx:v1`

This works fine for GCR but not for AWS ECR. 

How to get rid of the project name when replication happens.

**Comment by bitsf** [comment]
you can set the target "Destination namespace" in replication rule

**Comment by shashank-k** [comment]
So can you please let me know what should go into the destination namespace.

**Comment by bitsf** [comment]
no, you don't need add account number in namespace, in ECR we can resolve it with your AK.
you can just enter any name you like.
![image](https://user-images.githubusercontent.com/188115/74344835-24994f80-4de8-11ea-89b3-a741e258b93f.png)
![image](https://user-images.githubusercontent.com/188115/74344880-3549c580-4de8-11ea-935a-8efceeabe9e0.png)

**Comment by bitsf** [comment]
GCR is a special case, it has to use account id as namespace.
Current harbor design is when destination is empty, it will use the source namespace. So currently it can't  meet your expect.
I'm not sure if you use "library" as destination namespace can work, you can have a try first.

**Comment by shashank-k** [comment]
Sure
Thanks for the reply.
