### ISSUE TITLE
Common error enhancement

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10691]
Some suggestions for comment error from @steven-zou  https://github.com/goharbor/harbor/pull/10626#pullrequestreview-355725293

Let's revisit the error handling when we have efforts then @wy65701436

**Comment by renmaosheng** [comment]
PR is submitted from Yan wang, waiting for code-review.

**Comment by wy65701436** [comment]
Close it as PR merged. https://github.com/goharbor/harbor/pull/10994
