### ISSUE TITLE
Installing v1.10.0 via Helm results in strange localizations "SCANNER.SCANNER"

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [goharbor/harbor#10708]
**Expected behavior and actual behavior:**
Several GUI items do not seem to have the US English localized strings, i.e. the title says **SCANNER.SCANNER** not "Scanner" as well as **SIDE_NAV.SYSTEM_MGMT.INTERROGATION_SERVICES** for the title.

**Steps to reproduce the problem:**
I used the HELM Chart v1.3.0 which installs Harbor v1.10

![Screen Shot 2020-02-11 at 2 33 40 PM](https://user-images.githubusercontent.com/28016731/74271807-861fc800-4cdb-11ea-8e3d-be96592a8b8d.png)

**Versions:**
Please specify the versions of following systems.
![Screen Shot 2020-02-11 at 2 35 24 PM](https://user-images.githubusercontent.com/28016731/74271953-c4b58280-4cdb-11ea-9b0d-a3f976ae49a9.png)

- harbor version: [1.10.0]

**Comment by renmaosheng** [comment]
Shijun, 
     could you please take a look? thanks.

**Comment by AllForNothing** [comment]
@Eric-Fontana-Bose I newly installed a harbor of the same version to yours.  And everything looks fine.  
I believe your issue occurred in the period of upgrading or re-installing. The static files of UI  were  not overrided properly.  If needed , you can fix this by below steps:
 1.  clear up  the  "portal containner" and your browser cache
 2.  re-install harbor
