### ISSUE TITLE
update dockerfile for harbor-log

### ISSUE THREAD

**Issue by hyy0322** [goharbor/harbor#10704]
Hello! Could you please cherry-pick this PR https://github.com/goharbor/harbor/pull/6647 to release-1.7.0. Or PTAL My same PR https://github.com/goharbor/harbor/pull/10703.
This issue have been fixed in master, but not in branch release-1.7.
Issue Related: https://github.com/goharbor/harbor/issues/6643.

**Comment by renmaosheng** [comment]
Hi Yiyang,
     Harbor will support n-2 releases, currently we are at 1.10, so only 1.8.* and 1.9.* will be supported, could you please upgrade to the latest version? thanks.

**Comment by hyy0322** [comment]
@renmaosheng Hi, I'm sorry, we have use harbor 1.7 in prod env. It is quite stable now. For now, we 
are not preparing to upgrade. We can't simply upgrade to the latest version. It is too risky for us.
