### ISSUE TITLE
aliyun replication adapter healthcheck always successful

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#10702]
aliyun replication adapter healthcheck always successful, no matter what access id/key input

**Comment by bitsf** [comment]
this is because error is eaten when call `credential.Modify(req)` in src/common/utils/registry/auth/util.go:62

**Comment by renmaosheng** [comment]
let's fix this in 2.0 first and then back port to 1.10.* patches if needed. thanks.

**Comment by bitsf** [comment]
already fixed in 2.0 with new registry client
