### ISSUE TITLE
Properties should not contain dot for objects defined in swagger.yaml 

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#10701]
What can we help you?
![image](https://user-images.githubusercontent.com/30999793/74222491-9a6dc000-4cef-11ea-9def-8b7c071a1b5b.png)

**Comment by renmaosheng** [comment]
is this a blocker for you? please ping Wenkai directly if so.

**Comment by AllForNothing** [comment]
> is this a blocker for you? please ping Wenkai directly if so.

@renmaosheng No,t isn't . Wenkai and I are fixing it.
