### ISSUE TITLE
Where configure clair Scanner in config harbor?

### ISSUE THREAD

**Issue by patsevanton** [goharbor/harbor#10717]
I installed harbor by rpm.
https://github.com/MrMEEE/harbor-rpm-ansible/pull/4

I dont know where configure clair Scanner in config harbor.

```
[root@harbor-apatsev harbor]# pwd
/etc/harbor
[root@harbor-apatsev harbor]# grep -R clair-adapter .
[root@harbor-apatsev harbor]# 
```
I dont found clair-adapter in /etc/harbor.

**Comment by renmaosheng** [comment]
the installation guide is not maintained by Harbor, could you please try the docker-compose or helm installation format?

**Comment by catchups** [comment]
This can be done by editing the /etc/config/config.yaml file inside the Clair container.
