### ISSUE TITLE
remove ability to reset pw 

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#10712]
In it's current implementation, on a password reset email request, harbor will return different responses if an email exists or not in the database. This is not good practice as it would allow an attacker to check a list of users to see if they have access or not. Either we align the responses or get rid of it altogether.  

For most enterprise users not using local db for auth, this is an unnecessary feature and introduces risk and user can always contact admin for reset as a workaround.  We should vote on whether to deprecate this and make note of this break change in documentation and release notes.

**Comment by or-hub** [comment]
Removing this takes away a very useful component from Harbor.
It is very sad that the "need for more security" cripples an anotherwise good product like Harbor !
Besides - It seems some parts are still present - so only the sign in option was removed ?

More security could have been achieved by leaving  the feature in and just not giving out any information whether an account was indeed present - Many many many other application out there offer this without excessively exposing them.

I d very much like to see this feature to return really - or allow for it to be turned on optionally !

**Comment by harrishcris** [comment]
I agree with @or-hub, this is a very useful expected feature to have and to simply add a response that says "If you have an account then you will shortly recieve a password reset email" would have been a very simple solution to this.
