### ISSUE TITLE
Escape passwords to be reset

### ISSUE THREAD

**Issue by toslunar** [goharbor/harbor#10726]
**Expected behavior and actual behavior:**
Harbor did not reset password correctly via the "Forgot password" link for some passwords.  If I input `Abcd+123`, then the new password will be `Abcd 123`.

The "Change Password" link worked as expected.

**Steps to reproduce the problem:**
Forgot password → Reset password → Set password to `Abcd+123` → Login with `Abcd 123`.

**Possible causes:**
There seems an escaping issue either in Harbor (maybe `src/portal/src/app/account/password-setting/password-setting.service.ts`) or in Angular (maybe https://github.com/angular/angular/issues/18261).

**Comment by renmaosheng** [comment]
which harbor version did you hit this issue?  @AllForNothing to take a look.

**Comment by toslunar** [comment]
The version is `Version v1.8.1-16b59c41`.  Thanks!

**Comment by xaleeks** [comment]
keep in mind that we are most likely removing this feature in the next minor release of Harbor for security purposes.  Please see issue described here https://github.com/goharbor/harbor/issues/10712

**Comment by AllForNothing** [comment]
close as #10712 closed
