### ISSUE TITLE
not able push image to harbor project

### ISSUE THREAD

**Issue by lazzio7** [goharbor/harbor#10721]
Hi ,

i install harbor with http also with https ..add users and so on via AD.

i want to push image via cmd but:

> [xxx@harbor-test ~]$ docker push harbor-test.xxx.xx/test/wiki:test
> The push refers to repository [harbor-test.xxx.xx/test/wiki]
> Get https://harbor-test.xxx.xx/v2/: Service Unavailable
> [xxx@harbor-test ~]$

any idea?

Thanks

**Comment by esantoro** [comment]
logs ?

**Comment by lazzio7** [comment]
well, only:

> [root@harbor-test log]# tail -f messages | grep -i "docker\|push"
>Feb 13 15:24:42 harbor-test dockerd[22837]: time="2020-02-13T15:24:42.563446000+01:00" level=info msg="Attempting next endpoint for push after error: Get https://harbor-test.skilab.sk/v2/: Service Unavailable"
>Feb 13 15:25:43 harbor-test dockerd[22837]: time="2020-02-13T15:25:43.092266500+01:00" level=info msg="Attempting next endpoint for push after error: Get https://harbor-test.skilab.sk/v2/: Service Unavailable"
>Feb 13 15:25:55 harbor-test dockerd[22837]: time="2020-02-13T15:25:55.534373900+01:00" level=info msg="Attempting next endpoint for push after error: Get https://harbor-test.skilab.sk/v2/: Service Unavailable"

in harbor /var/log/harbor i do not find nothing relevant,,

**Comment by renmaosheng** [comment]
Hi, 
       have you added the harbor certificate in your docker client? thanks.

**Comment by renmaosheng** [comment]
https://docs.docker.com/engine/security/certificates/

**Comment by lazzio7** [comment]
Hello,

i go through the:  [https://github.com/goharbor/harbor/blob/master/docs/1.10/install-config/configure-https.md](url)

>[root@harbor-test ~]# ll -lR /etc/docker/certs.d/
>/etc/docker/certs.d/:
>total 0
>drwxr-xr-x 2 root root 87 Feb 12 14:44 harbor-test.xxx.xx

>/etc/docker/certs.d/harbor-test.xxx.xx:
>total 12
>-rw-r--r-- 1 root root 2053 Feb 12 14:44 ca.crt
>-rw-r--r-- 1 root root 2122 Feb 12 14:44 harbor-test.xxx.xx.cert
>-rw------- 1 root root 3243 Feb 12 14:44 harbor-test.xxx.xx.key


>[root@harbor-test ~]# systemctl status docker
>● docker.service - Docker Application Container Engine
>   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
>  Drop-In: /etc/systemd/system/docker.service.d
>           └─http-proxy.conf
>   Active: active (running) since Fri 2020-02-14 08:49:12 CET; 3 days ago
>     Docs: https://docs.docker.com
> Main PID: 1172 (dockerd)
>    Tasks: 64
>   Memory: 55.4M
>   CGroup: /system.slice/docker.service
>           ├─1172 /usr/bin/dockerd -H fd://
>           ├─4589 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4443 -container-ip >172.18.0.4 >
>           ├─4614 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip >172.18.0.4 ->
>           ├─4633 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip >172.18.0.4 -c>
>           └─4736 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 1514 -container-ip >172.18.0.>

>Feb 14 14:02:51 harbor-test.xxx.xx dockerd[1172]: time="2020-02-14T14:02:51.323867100+01:00" level=info ms>
>Feb 14 14:04:23 harbor-test.xxx.xx dockerd[1172]: time="2020-02-14T14:04:23.702872100+01:00" level=error m>

**Comment by lazzio7** [comment]
maybe i forget mentioned that i am not able login to harbor:

[ZZZ@harbor-test ~]$  docker login https://harbor-test.xxx.xx -u ZZZ
Password:
Error response from daemon: Get https://harbor-test.xxx.xx/v2/: Service Unavailable

**Comment by lazzio7** [comment]
solved,

in my lab i have to turn off proxy and now its working...
