### ISSUE TITLE
Add oidc_admin_group to OIDC authentication like LDAP has

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [goharbor/harbor#10724]
**Adding admin groups for OIDC Auth**
The LDAP configuration allows for configuring what groups are admins, this is missing in the 
OIDC authentication.

**Describe the solution you'd like**
Please add `oidc_admin_group` which selects the group that users would become Admins from.

**Comment by renmaosheng** [comment]
@xaleeks please take a look at this requirement.

**Comment by xaleeks** [comment]
This is the same issue we came across for klm.  @reasonerjt  Based on your investigation, it is oidc vendor dependent and there's possibility that changing groups (on the oidc side) is not correctly refreshed right, but we still have a way to invalidate it afterwards.  Can we have further discussions to see how this feature might be enabled?

**Comment by xaleeks** [comment]
can we achieve parity with the LDAP Group Admin DN'?  Is this something that certain or all OIDC IDP provides out of the box?  The LDAP admin group is a native concept of LDAP I'm assuming? Would be good to add this in v2.2 if possible @reasonerjt

**Comment by xaleeks** [comment]
ignore my previous comment, I misunderstood.  This is a construct entirely within harbor and I vote in favor of this for v2.2.

**Comment by Morriz** [comment]
We use keycloak to normalize OIDC claims incoming, and we are missing out now on an admin group, and have to wait for individuals to login first and then as admin make them admin also. Very cumbersome.

Please allow us to designate a group name to give all members admin privileges.

**Comment by reasonerjt** [comment]
This dev work and follow up discussion will be tracked in #13113

**Comment by reasonerjt** [comment]
Closing as fixed.
It will be shipped in v2.2.0
