### ISSUE TITLE
wrong Log configurations in harbor.yml causes the registry container to restart repeatedly

### ISSUE THREAD

**Issue by goldwinner** [goharbor/harbor#10731]
**Steps to reproduce the problem:**
1.modify harbor.yml
At `Log configurations` section，change the value of `level`，from `info` to `warning`
2.restart harbor
docker-compose down -v && ./prepare && docker-compose up -d
3.wait 15s
`docker-compose ps` show Registry container restarts repeatedly

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.4]
- docker engine version: [19.03.6]
- docker-compose version: [1.25.1]

**Additional context:**
no
- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
```
# Log configurations
log:
  # options are debug, info, warning, error, fatal
  level: warning
```
- **Log files:** You can get them by package the `/var/log/harbor/` .
[registry.log](https://github.com/goharbor/harbor/files/4203878/registry.log)

**Comment by renmaosheng** [comment]
could you please change 'warning' to 'warn', it seems a typo in the comment, thanks.

**Comment by ninjadq** [comment]
hi @goldwinner this is a bug already fixed in 
https://github.com/goharbor/harbor/commit/057bc34703a2c0e219dcb15e4cefcfff9492b1fa

could you upgrade your harbor to the latest release, or change the `warning` in registry's config file  to `warn` manually

**Comment by goldwinner** [comment]
> could you upgrade your harbor to the latest release, or change the `warning` in registry's config file to `warn` manually
after change registry's config file manually, it worked fine
