### ISSUE TITLE
Time zone problem in harbor1.9.4

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#10732]
Harbor1.9.4
When I set cron schedule in replication policy, I have to set "0 0 3 * * *"  triggered  it runs at 11:00 CST,But display in UI is 19:00 CST.
2827
scheduled
2020/2/14 下午7:00
6m30s
100%
4975
Succeed

**Comment by renmaosheng** [comment]
Hi yangyang,
      the Cron job is UTC time zone based, you need to some adjustment to your own timezone. thanks.

**Comment by renmaosheng** [comment]
Yang Wang, could we add some help text to let user know the crob job is UTC time based?

**Comment by liy516** [comment]
> ou need to some adjustment to your own timezone. thanks.

thanks

**Comment by jwangyangls** [comment]
I suggest adding some text to the cron prompt to let users know that the cron job is based on UTC time,
@xaleeks , do you think it is reasonable to achieve this?

**Comment by xaleeks** [comment]
@jwangyangls Agreed.  Can you please add a tooltip on the replication tab for this?

**Comment by jwangyangls** [comment]
![image](https://user-images.githubusercontent.com/29826789/79820615-3afef100-83bf-11ea-82ce-104d0adcdc0c.png)
