### ISSUE TITLE
Request ID is not usable

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10740]
https://github.com/goharbor/harbor/blob/master/src/server/middleware/requestid/requestid.go

Currently the Request ID is added to the header of request, with this approach there's no way to propagate the ID to other request.

We should also consider to dump request ID in some log messages.  
Currently I don't think the code really leverages this req id.

**Comment by reasonerjt** [comment]
First let's make sure the req ID is propagated in subsequent requests to other components.

I'll open another issue to track log messages.

**Comment by heww** [comment]
Now we can get logger from the ctx and the logger will log the request id when it exists.

**Comment by heww** [comment]
I will close this issue now.
