### ISSUE TITLE
OCI Distribution Conformance Tests

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#10749]
There's an on going test framework for OCI in opencontainers/distribution-spec, we can continue to use it to test the OCI compatibility.

https://github.com/opencontainers/distribution-spec/tree/master/conformance

usage: 
git clone https://github.com/opencontainers/distribution-spec
cd conformance
export OCI_ROOT_URL="https://harbor-ip"
export OCI_NAMESPACE="testproject/testrepo" 
export OCI_USERNAME="admin"
export OCI_PASSWORD="Harbor12345"
export OCI_DEBUG="true"
go test .

**Comment by bitsf** [comment]
test framework commit:2ce66de1cd5234a4b5e6721c8439c5fc435d977f
harbor commit: e5eb7118271f73a91300d85e93342f85f686ec66

=== RUN   TestConformance
Running Suite: OCI Distribution Conformance Tests
=================================================
Random Seed: 1581951193
Will run 28 of 28 specs

••••
------------------------------
• Failure [0.488 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Blob Upload Monolithic
  /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:12
    POST request with digest and blob should yield a 201 [It]
    /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:21

    Expected
        <int>: 202
    to equal
        <int>: 201

    /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:31
------------------------------
• Failure [0.502 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Blob Upload Monolithic
  /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:12
    GET request to blob URL from prior request should yield 200 [It]
    /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:34

    Expected
        <int>: 404
    to equal
        <int>: 200

    /github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:38
------------------------------
•••
------------------------------
• Failure [1.026 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Blob Upload Chunked
  /github.com/opencontainers/distribution-spec/conformance/04_blob_upload_chunked_test.go:12
    Out-of-order blob upload should return 416 [It]
    /github.com/opencontainers/distribution-spec/conformance/04_blob_upload_chunked_test.go:13

    Expected
        <int>: 202
    to equal
        <int>: 416

    /github.com/opencontainers/distribution-spec/conformance/04_blob_upload_chunked_test.go:28
------------------------------
••
------------------------------
• Failure [0.234 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Manifest Upload
  /github.com/opencontainers/distribution-spec/conformance/05_manifest_upload_test.go:13
    GET nonexistent manifest should return 404 [It]
    /github.com/opencontainers/distribution-spec/conformance/05_manifest_upload_test.go:14

    Expected
        <int>: 500
    to equal
        <int>: 404

    /github.com/opencontainers/distribution-spec/conformance/05_manifest_upload_test.go:19
------------------------------
••••••
------------------------------
• Failure [0.309 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Error codes
  /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:12
    400 response body should contain OCI-conforming JSON message [It]
    /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:13

    Expected
        <int>: 404
    to equal
        <int>: 400

    /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:20
------------------------------
• Failure [0.472 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Error codes
  /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:12
    Response from DELETE request to manifest URL (tag) should have OCI-conforming code [It]
    /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:29

    Expected
        <[]string | len:15, cap:15>: [
            "BLOB_UNKNOWN",
            "BLOB_UPLOAD_INVALID",
            "BLOB_UPLOAD_UNKNOWN",
            "DIGEST_INVALID",
            "MANIFEST_BLOB_UNKNOWN",
            "MANIFEST_INVALID",
            "MANIFEST_UNKNOWN",
            "MANIFEST_UNVERIFIED",
            "NAME_INVALID",
            "NAME_UNKNOWN",
            "SIZE_INVALID",
            "TAG_INVALID",
            "UNAUTHORIZED",
            "DENIED",
            "UNSUPPORTED",
        ]
    to contain element matching
        <string>: UNKNOWN

    /github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:40
------------------------------
• Failure [0.551 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Manifest Delete
  /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:13
    DELETE request to manifest URL (tag) MUST fail [It]
    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:14

    Expected
        <int>: 500
    to be <
        <int>: 500

    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:20
------------------------------
•
------------------------------
• Failure [0.541 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Manifest Delete
  /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:13
    DELETE request to manifest URL (digest) should yield 202 response [It]
    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:31

    Expected
        <int>: 500
    to equal
        <int>: 202

    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:35
------------------------------
•
------------------------------
• Failure [0.539 seconds]
OCI Distribution Conformance Tests
/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Manifest Delete
  /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:13
    GET request to tags list should reflect manifest deletion [It]
    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:45

    Expected
        <int>: 4
    to be <
        <int>: 4

    /github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:54
------------------------------
••HTML report was created: /github.com/opencontainers/distribution-spec/conformance/report.html
JUnit report was created: /github.com/opencontainers/distribution-spec/conformance/junit.xml


Summarizing 9 Failures:

[Fail] OCI Distribution Conformance Tests Blob Upload Monolithic [It] POST request with digest and blob should yield a 201 
/github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:31

[Fail] OCI Distribution Conformance Tests Blob Upload Monolithic [It] GET request to blob URL from prior request should yield 200 
/github.com/opencontainers/distribution-spec/conformance/03_blob_upload_monolithic_test.go:38

[Fail] OCI Distribution Conformance Tests Blob Upload Chunked [It] Out-of-order blob upload should return 416 
/github.com/opencontainers/distribution-spec/conformance/04_blob_upload_chunked_test.go:28

[Fail] OCI Distribution Conformance Tests Manifest Upload [It] GET nonexistent manifest should return 404 
/github.com/opencontainers/distribution-spec/conformance/05_manifest_upload_test.go:19

[Fail] OCI Distribution Conformance Tests Error codes [It] 400 response body should contain OCI-conforming JSON message 
/github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:20

[Fail] OCI Distribution Conformance Tests Error codes [It] Response from DELETE request to manifest URL (tag) should have OCI-conforming code 
/github.com/opencontainers/distribution-spec/conformance/07_error_codes_test.go:40

[Fail] OCI Distribution Conformance Tests Manifest Delete [It] DELETE request to manifest URL (tag) MUST fail 
/github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:20

[Fail] OCI Distribution Conformance Tests Manifest Delete [It] DELETE request to manifest URL (digest) should yield 202 response 
/github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:35

[Fail] OCI Distribution Conformance Tests Manifest Delete [It] GET request to tags list should reflect manifest deletion 
/github.com/opencontainers/distribution-spec/conformance/08_manifest_delete_test.go:54

Ran 28 of 28 Specs in 18.798 seconds
FAIL! -- 19 Passed | 9 Failed | 0 Pending | 0 Skipped
--- FAIL: TestConformance (18.81s)

**Comment by bitsf** [comment]
test case in https://github.com/opencontainers/distribution-spec/tree/master/test will fail at the first auth step, because we only support basic auth, while it expects bear token auth

**Comment by ywk253100** [comment]
According to the conformance test result against docker registry, we should focus on the following failure cases:
Manifest Upload(1 case)
Manifest Delete(3 cases)

**Comment by reasonerjt** [comment]
```
test case in https://github.com/opencontainers/distribution-spec/tree/master/test will fail at the first auth step, because we only support basic auth, while it expects bear token auth
```
Can we open an issue to the oci repo or submit a PR to fix it?

**Comment by wy65701436** [comment]
closed as PR merged. https://github.com/goharbor/harbor/pull/10972
