### ISSUE TITLE
Unable to install harbor-1.10.1 using offline installer: PermissionError: [Errno 1] Operation not permitted: '/data/psc'

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#10779]
Unable to install harbor-1.10.1 using offline installer: PermissionError: [Errno 1] Operation not permitted: '/data/psc'

./install.sh 

[Step 0]: checking if docker is installed ...

Note: docker version: 19.03.5

[Step 1]: checking docker-compose is installed ...

Note: docker-compose version: 1.25.4

[Step 2]: loading Harbor images ...
Loaded image: goharbor/clair-adapter-photon:v1.0.1-v1.10.1
Loaded image: goharbor/harbor-jobservice:v1.10.1
Loaded image: goharbor/redis-photon:v1.10.1
Loaded image: goharbor/notary-server-photon:v0.6.1-v1.10.1
Loaded image: goharbor/clair-photon:v2.1.1-v1.10.1
Loaded image: goharbor/harbor-log:v1.10.1
Loaded image: goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.1
Loaded image: goharbor/notary-signer-photon:v0.6.1-v1.10.1
Loaded image: goharbor/chartmuseum-photon:v0.9.0-v1.10.1
Loaded image: goharbor/harbor-registryctl:v1.10.1
Loaded image: goharbor/nginx-photon:v1.10.1
Loaded image: goharbor/harbor-migrator:v1.10.1
Loaded image: goharbor/prepare:v1.10.1
Loaded image: goharbor/harbor-portal:v1.10.1
Loaded image: goharbor/harbor-core:v1.10.1
Loaded image: goharbor/harbor-db:v1.10.1

[Step 3]: preparing environment ...

[Step 4]: preparing harbor configs ...
prepare base dir is set to /Users/bj151v/harbor-1_10_1_offline
WARNING:root:WARNING: HTTP protocol is insecure. Harbor will deprecate http protocol in the future. Please make sure to upgrade to https
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 44, in main
    prepare_core(config_dict, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/core.py", line 18, in prepare_core
    prepare_dir(psc_dir, uid=DEFAULT_UID, gid=DEFAULT_GID)
  File "/usr/src/app/utils/misc.py", line 105, in prepare_dir
    recursive_chown(absolute_path, uid, gid)
  File "/usr/src/app/utils/misc.py", line 125, in recursive_chown
    os.chown(path, uid, gid)
PermissionError: [Errno 1] Operation not permitted: '/data/psc'

**Comment by balonik** [comment]
make sure you have rw permissions to /data/psc

**Comment by bjethwan** [comment]
Thanks @balonik 
I actually entered /data/psc in docker > preferences
I remember once trying it with sudo too but this issue won't go.
 
> make sure you have rw permissions to /data/psc

![image](https://user-images.githubusercontent.com/5045325/74964040-b46a7980-5438-11ea-85a4-a3491330d600.png)

**Comment by renmaosheng** [comment]
could you please list the permission of the directory? thanks.

**Comment by bjethwan** [comment]
@renmaosheng 
I see the issue now. The /data and all the subdirectories are owned by root:wheel (it's a macOS), while I was logged in as a domain user on this machine. 

Hence, I made a few quick changes in the harbor.yml file.

hostname: <<machine name>>
data_volume: /Users/<<username>>/data
log:
    location: /Users/<<username>>/var/log/harbor

Is this fine? Would it create any problems later?

You know, later on, I am going to use this docker-compose mechanism to install harbor on multiple nodes and then configure a load balancer to route traffic to those harbor instances. Hence, I am bit worried if the above edits to harbor.yml are fine.

**Comment by bjethwan** [comment]
@renmaosheng 

I was trying to install harbor on ubuntu 18.04 LTS based ec2 instance.

And I again ran into a similar issue:
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/harbor/common/config/registryctl/env'
[14576] Failed to execute script docker-compose

I noticed that the script created common sub-directory and docker-compose.yaml with root ownership. Is this normal?

$ ls -la /home/ubuntu/harbor
total 662164
drwxrwxr-x 4 ubuntu ubuntu      4096 Feb 25 11:41 .
drwxr-xr-x 6 ubuntu ubuntu      4096 Feb 25 11:31 ..
-rw-r--r-- 1 ubuntu ubuntu     16384 Feb 25 11:05 .harbor.yml.swp
-rw-r--r-- 1 ubuntu ubuntu     11347 Feb 10 06:18 LICENSE
drwxrwxr-x 2 ubuntu ubuntu      4096 Feb 25 11:29 certs
drwxr-xr-x 3 root   root        4096 Feb 25 11:40 common
-rw-r--r-- 1 ubuntu ubuntu      3398 Feb 10 06:18 common.sh
-rw-r--r-- 1 root   root        5344 Feb 25 11:41 docker-compose.yml
-rw-r--r-- 1 ubuntu ubuntu 677974489 Feb 10 06:19 harbor.v1.10.1.tar.gz
-rw-r--r-- 1 ubuntu ubuntu      5913 Feb 25 11:31 harbor.yml
-rwxr-xr-x 1 ubuntu ubuntu      2284 Feb 10 06:18 install.sh
-rwxr-xr-x 1 ubuntu ubuntu      1749 Feb 10 06:18 prepare






Full Trace:
$ ./install.sh 

[Step 0]: checking if docker is installed ...

Note: docker version: 18.09.7

[Step 1]: checking docker-compose is installed ...

Note: docker-compose version: 1.25.4

[Step 2]: loading Harbor images ...
47a4bb1cfbc7: Loading layer [==================================================>]  34.26MB/34.26MB
c2d9cf7a4eaf: Loading layer [==================================================>]  9.056MB/9.056MB
32b7eca4f03e: Loading layer [==================================================>]   9.71MB/9.71MB
5d104292391f: Loading layer [==================================================>]   9.71MB/9.71MB
Loaded image: goharbor/clair-adapter-photon:v1.0.1-v1.10.1
0039915754c6: Loading layer [==================================================>]  12.83MB/12.83MB
0a4ba5bc8bc2: Loading layer [==================================================>]  49.37MB/49.37MB
Loaded image: goharbor/harbor-jobservice:v1.10.1
db95a8bece9e: Loading layer [==================================================>]  78.32MB/78.32MB
f9aa9f9a3393: Loading layer [==================================================>]  3.072kB/3.072kB
f0baa86a6ccd: Loading layer [==================================================>]   59.9kB/59.9kB
2b8f0a44b78f: Loading layer [==================================================>]  61.95kB/61.95kB
Loaded image: goharbor/redis-photon:v1.10.1
a9f6374f6301: Loading layer [==================================================>]   9.05MB/9.05MB
b3c39a738965: Loading layer [==================================================>]  6.239MB/6.239MB
dce1aa68054e: Loading layer [==================================================>]  16.04MB/16.04MB
612aac9b538e: Loading layer [==================================================>]  28.24MB/28.24MB
8612386fb841: Loading layer [==================================================>]  22.02kB/22.02kB
53883649d694: Loading layer [==================================================>]  50.52MB/50.52MB
Loaded image: goharbor/notary-server-photon:v0.6.1-v1.10.1
f3967aa0de5f: Loading layer [==================================================>]  115.8MB/115.8MB
42fd590be962: Loading layer [==================================================>]  12.14MB/12.14MB
096b03f3e32b: Loading layer [==================================================>]  3.072kB/3.072kB
aa66bf3b8224: Loading layer [==================================================>]  49.15kB/49.15kB
8e76391190c9: Loading layer [==================================================>]  3.584kB/3.584kB
131573c722d5: Loading layer [==================================================>]  13.02MB/13.02MB
Loaded image: goharbor/clair-photon:v2.1.1-v1.10.1
69e43242ff64: Loading layer [==================================================>]  50.39MB/50.39MB
5a3a8e835993: Loading layer [==================================================>]  3.584kB/3.584kB
4dff480c159c: Loading layer [==================================================>]  3.072kB/3.072kB
2be454a39481: Loading layer [==================================================>]   2.56kB/2.56kB
d6b4877d5c4e: Loading layer [==================================================>]  3.072kB/3.072kB
609537197cce: Loading layer [==================================================>]  3.584kB/3.584kB
b52d06cad304: Loading layer [==================================================>]  12.29kB/12.29kB
Loaded image: goharbor/harbor-log:v1.10.1
badcf9296df7: Loading layer [==================================================>]  9.056MB/9.056MB
8b17ed0102b2: Loading layer [==================================================>]  3.584kB/3.584kB
4d1cd50b8d4f: Loading layer [==================================================>]  3.072kB/3.072kB
491c41e50d6a: Loading layer [==================================================>]  21.76MB/21.76MB
0101dc4148c7: Loading layer [==================================================>]  22.59MB/22.59MB
Loaded image: goharbor/registry-photon:v2.7.1-patch-2819-2553-v1.10.1
77965b8f534b: Loading layer [==================================================>]  14.61MB/14.61MB
940bf05c9601: Loading layer [==================================================>]  28.24MB/28.24MB
7ca206eb72e3: Loading layer [==================================================>]  22.02kB/22.02kB
9898774a5bad: Loading layer [==================================================>]  49.09MB/49.09MB
Loaded image: goharbor/notary-signer-photon:v0.6.1-v1.10.1
86340c56281e: Loading layer [==================================================>]  9.055MB/9.055MB
8ac45c34690f: Loading layer [==================================================>]  42.31MB/42.31MB
4aa70453f992: Loading layer [==================================================>]  3.072kB/3.072kB
6cbc6ab111b2: Loading layer [==================================================>]  3.584kB/3.584kB
d6d7b70c18b5: Loading layer [==================================================>]  43.14MB/43.14MB
Loaded image: goharbor/chartmuseum-photon:v0.9.0-v1.10.1
07efa003923d: Loading layer [==================================================>]  9.056MB/9.056MB
96dd65c291de: Loading layer [==================================================>]  3.584kB/3.584kB
802a1397679e: Loading layer [==================================================>]  21.76MB/21.76MB
92c283f6895a: Loading layer [==================================================>]  3.072kB/3.072kB
8b61b91240a6: Loading layer [==================================================>]  8.662MB/8.662MB
1fd753477b6f: Loading layer [==================================================>]  31.24MB/31.24MB
Loaded image: goharbor/harbor-registryctl:v1.10.1
48cda078e98d: Loading layer [==================================================>]  10.89MB/10.89MB
Loaded image: goharbor/nginx-photon:v1.10.1
2c00d9af2c3f: Loading layer [==================================================>]  34.31MB/34.31MB
0e4ae15c3d4e: Loading layer [==================================================>]  339.9MB/339.9MB
27810c9ff1a9: Loading layer [==================================================>]  135.2kB/135.2kB
Loaded image: goharbor/harbor-migrator:v1.10.1
93e0577272a9: Loading layer [==================================================>]  34.24MB/34.24MB
fb3507ff707e: Loading layer [==================================================>]  117.4MB/117.4MB
f59c6315bf8a: Loading layer [==================================================>]  42.32MB/42.32MB
5c5501748347: Loading layer [==================================================>]   2.56kB/2.56kB
3710d94e58dd: Loading layer [==================================================>]  1.536kB/1.536kB
06e0f1585c01: Loading layer [==================================================>]  166.4kB/166.4kB
bf5ac9b9c61c: Loading layer [==================================================>]   3.01MB/3.01MB
Loaded image: goharbor/prepare:v1.10.1
9ea2dad46741: Loading layer [==================================================>]  10.89MB/10.89MB
b280b9e7ca3b: Loading layer [==================================================>]  7.696MB/7.696MB
a1ce7c1130ee: Loading layer [==================================================>]  223.2kB/223.2kB
3b0492a7358b: Loading layer [==================================================>]  195.1kB/195.1kB
c64d6e6c80dd: Loading layer [==================================================>]  15.36kB/15.36kB
ace4e9064f06: Loading layer [==================================================>]  3.584kB/3.584kB
Loaded image: goharbor/harbor-portal:v1.10.1
b74d8257d4e7: Loading layer [==================================================>]  12.83MB/12.83MB
92f141040819: Loading layer [==================================================>]   42.5MB/42.5MB
33c99383fac5: Loading layer [==================================================>]  5.632kB/5.632kB
2bacc160d10f: Loading layer [==================================================>]  40.45kB/40.45kB
f51bed904fbe: Loading layer [==================================================>]   42.5MB/42.5MB
Loaded image: goharbor/harbor-core:v1.10.1
a2ffdaaa3434: Loading layer [==================================================>]  63.56MB/63.56MB
5745ac9e0297: Loading layer [==================================================>]  54.44MB/54.44MB
dc1d24cbb1d5: Loading layer [==================================================>]  5.632kB/5.632kB
4280f2f98340: Loading layer [==================================================>]  2.048kB/2.048kB
0f9279b20eec: Loading layer [==================================================>]   2.56kB/2.56kB
8b9162d25131: Loading layer [==================================================>]   2.56kB/2.56kB
50ad7481e5af: Loading layer [==================================================>]   2.56kB/2.56kB
54b809bfb5ec: Loading layer [==================================================>]  10.24kB/10.24kB
Loaded image: goharbor/harbor-db:v1.10.1


[Step 3]: preparing environment ...

[Step 4]: preparing harbor configs ...
prepare base dir is set to /home/ubuntu/harbor
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Generated configuration file: /config/db/env
Generated configuration file: /config/jobservice/env
Generated configuration file: /config/jobservice/config.yml
Generated and saved secret to file: /secret/keys/secretkey
Generated certificate, key file: /secret/core/private_key.pem, cert file: /secret/registry/root.crt
Generated configuration file: /compose_location/docker-compose.yml
Clean up the input dir

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 65, in project_from_options
  File "compose/cli/command.py", line 141, in get_project
  File "compose/config/config.py", line 411, in load
  File "compose/config/config.py", line 511, in load_services
  File "compose/config/config.py", line 490, in build_services
  File "compose/config/config.py", line 490, in <listcomp>
  File "compose/config/config.py", line 482, in build_service
  File "compose/config/config.py", line 888, in finalize_service
  File "compose/config/config.py", line 688, in resolve_environment
  File "compose/config/environment.py", line 43, in env_vars_from_file
  File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/harbor/common/config/registryctl/env'
[14574] Failed to execute script docker-compose


[Step 5]: starting Harbor ...
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 65, in project_from_options
  File "compose/cli/command.py", line 141, in get_project
  File "compose/config/config.py", line 411, in load
  File "compose/config/config.py", line 511, in load_services
  File "compose/config/config.py", line 490, in build_services
  File "compose/config/config.py", line 490, in <listcomp>
  File "compose/config/config.py", line 482, in build_service
  File "compose/config/config.py", line 888, in finalize_service
  File "compose/config/config.py", line 688, in resolve_environment
  File "compose/config/environment.py", line 43, in env_vars_from_file
  File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/harbor/common/config/registryctl/env'
[14576] Failed to execute script docker-compose

**Comment by bjethwan** [comment]
@renmaosheng Please ignore my previous comment. It is working fine now. I missed sudo when starting install.sh

**Comment by wy65701436** [comment]
thanks @bjethwan , I will close it and feel free to reopen if it still doesn't work for you.
