### ISSUE TITLE
Harbor会朝直接支持CI/CD应用发展吗？

### ISSUE THREAD

**Issue by openstack-test** [goharbor/harbor#1077]
Harbor，以其优异特性，目前已经深受市场和用户好评。在实际的软件研发测试活动中，常有这样的一种强烈需求，即：

当开发人员提交code到GitLab系统上后，jenkins执行一系列的单元测试、镜像构建、镜像部署、集成测试，并将镜像push到开发或测试Registry中，如果在集成测试阶段，验证通过了，则系统自动将镜像push到生产Registry中。

从某种角度而言，当有了这些需求功能后，足以博得更广泛的市场和用户。请问，Harbor考虑朝这方面发展吗？

谢谢
—— 一个喜欢Harbor的用户

**Comment by yhua123** [comment]
we used Travis service for CI
you can find .travis.yml under root directory.
support UT and part of IT

**Comment by hainingzhang** [comment]
This feature will be achieved by tagging an image and replicate to a production registry. This is in roadmap. @openstack-test
