### ISSUE TITLE
Broken doc link: github.com/goharbor/harbor/blob/master/docs/1.10/download-installer.md

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#10777]
I was on https://github.com/goharbor/harbor/blob/master/docs/1.10/install-config/installation-prereqs.md and at the end of the document, there's a link saying What to Do Next: Download the Harbor Installer and that "Download the Harbor Installer" link is broken.

**Comment by renmaosheng** [comment]
I check the latest version has fixed this. thanks for reporting.
