### ISSUE TITLE
Installing/Running two harbor versions in parallel

### ISSUE THREAD

**Issue by hammahtyp** [goharbor/harbor#10775]
Dear Harbor commumity,

Thank you for the fantastic software that is Harbor! We're using it extensively, and
nothing comes even close to its feature set. Well done! 

We have deployed Harbor in multiple geographical locations and are successfully replicating
from a central Harbor instance to them. We're planning to move to the latest
Harbor version though, but we can't simply upgrade our central instance (v1.7.6),
because replication will probably break.

We had the idea to install a second Harbor instance on our central host with 1.10.1,
using the same SSL certificate but a different HTTPS port, so that we can migrate
our images and instances gradually. Once all images exist in both registries, we can update (or reinstall) the "satellite" locations and move replication configs one by one to the newer Harbor instance. That's the plan...

When I try to spin up a 1.10.1 instance side by side with the existing 1.7.6 instance the installer
exits with an error when it wants to start harbor, because the containers it wants to start,
have the same name as the already running ones. I tried changing the names in 
the docker-compose.yml file, but they keep getting overwritten with defaults when the
installer starts.

So the question is: Is there a way to force the installer to use different container
names, so that two Harbor instances can run in parallel? Does anyone have a different
idea how we could gradually switch all our locations to a newer Harbor version?

Thanks in advance!

**Comment by bjethwan** [comment]
@hammahtyp 
I am not an expert...still just a thought....try using docker stack...that gives each deploy a prefix...Let me know if it works for you.

**Comment by hammahtyp** [comment]
Thanks @bjethwan 
Didn't know this existed, so it is definitely an idea. 

A quick test revealed, that I would have to "upgrade" all docker-compose.yml
files to make this work though, because the present ones are v2, but docker stack only accepts v3 files. When I have more time, I'll give it another shot.

**Comment by Okabe-Kurisu** [comment]
we export sql and all images in 1.7.9。then import there to a new 1.9.2 instance 。its looks like when harbor core find database structure generated by old version，core will update database structure automatic。

**Comment by Okabe-Kurisu** [comment]
we export sql and all images in 1.7.9。then import there to a new 1.9.2 instance 。its looks like when harbor core find database structure generated by old version，core will update database structure automatic。
