### ISSUE TITLE
Unable to complete oidc onboarding due to '_xsrf' argument missing in the POST request

### ISSUE THREAD

**Issue by atosatto** [goharbor/harbor#10780]
Dear all, I am running 

- harbor version: v1.10.1-f3e11715
- docker engine version: 19.03.5
- docker-compose version: 1.25.4

on Debian Buster and having some issues to configure correctly the integration between Harbor and my OIDC provider.

In particular, logging in for the first time to Harbor, both myself and my co-worker are prompted with the "Set OIDC Username" indicating, according to my understanding the completion of the OIDC authentication

<img width="643" alt="Screenshot 2020-02-19 at 10 59 41" src="https://user-images.githubusercontent.com/871302/74853095-b7cd0a80-533d-11ea-9819-3f5acea7e981.png">

However, when clicking the "Save" button on my computer, the following request is sent by the browser (`Firefox 72.0.2`) to Harbor

```
POST /c/oidc/onboard HTTP/1.1
Host: <harbor-hostname>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Xsrftoken: K6cyJjVTy27uvEQieJ3C9j6iTiOpJQeD
Content-Type: application/json
Content-Length: 29
Origin: https://<harbor-hostname>
DNT: 1
Connection: keep-alive
Referer: https://<harbor-hostname>/oidc-onboard?username=
Cookie: sid=310d88eb9a8195c4a1155d6ee3ec752c; _xsrf=SzZjeUpqVlR5Mjd1dkVRaWVKM0M5ajZpVGlPcEpRZUQ=|1582128853593175746|7994e5e839d500203f34777cb0d448174cfcf6c77fba2a5218f3a459dc7a83d6
Pragma: no-cache
Cache-Control: no-cache

{"username":"andrea.tosatto"}
```

In my case Harbor is correctly completing the OIDC onboarding and logging me in.

However, with both my co-worker's browsers (`Chrome 79.0.3945.130` and `Firefox 72.0.2`) the following request is sent by the brower

```
POST /c/oidc/onboard HTTP/1.1
Host: <harbor-hostname>
Connection: keep-alive
Content-Length: 48
Accept: application/json, text/plain, */*
DNT: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/json
Origin: https://<harbor-hostname>
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: https://<harbor-hostname>/oidc-onboard?username=
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: sid=36830960dedb54dfd247fd8fd859b16a; _xsrf=RGZ0RUIxdU9kOFRTVWZqVExoMVcyZWFwdFkwUlcwZlg=|1582128068841281368|ce6a964986cf0bdcec251a0be517c56146e163832f48232d30f5d7b8fa6bd55a

{"username":"coworker.username"}
```

As you might notice, the request is missing the `X-Xsrftoken` header resulting in Harbor failing the Cross-Site-Requests-Forgery prevention check with the following error 

```
422 Unprocessable Entity

<br>The page you have requested is forbidden.<br>Perhaps you are here because:<br><br><ul><br>‘_xsrf’ argument missing from POST</ul>
<a href="/" title="Home" class="button">Go Home</a><br />
<br>Powered by beego 1.12.1
```

The expected result would be to see the `X-Xsrftoken` being set correctly by the browser also on my co-worker's request.

Note that this issue is impacting several of my co-workers (luckily, not all of them!).
While we continue with our investigation, we're opening this ticket to keep track of our findings and look for recommendations and hints on root-causes and / or potential fixes.

Thanks for this great community project!

**Comment by renmaosheng** [comment]
Meina， could you please take a look at this problem? thanks.

**Comment by zhoumeina** [comment]
@atosatto , both you and your co-worker using the same server?Does he visit the old version of harbor before? Clean the cache and login again? Did he try that?

**Comment by atosatto** [comment]
Hi @zhoumeina, yes we're visiting the same harbor instance and we've been trying with different browsers, anonymous tabs and cleaning up the cache.

However, if you have any specific experiment you want us to do, we're happy to do so.

**Comment by jwangyangls** [comment]
Hi @atosatto  
When the login is missing the xsrf token, will the second click of the save button throw the same error?

**Comment by jwangyangls** [comment]
close it by #10901
