### ISSUE TITLE
[Nightly Test] Registry edit criteria is not strict enough

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#10788]
In nightly test, Registry edit case passed, but delete case failed, the fact is the registry was not edit at all, please verify it more strict.

![image](https://user-images.githubusercontent.com/44018302/74905864-50b95f80-53ea-11ea-9690-1d0d800c8049.png)

**Comment by renmaosheng** [comment]
I can not delete the repo in my local env as well, thanks.

**Comment by YangJiao0817** [comment]
This issue no longer exists in the new version of harbor, so close it.
