### ISSUE TITLE
1.10 compile issue with GOPATH

### ISSUE THREAD

**Issue by josh626** [goharbor/harbor#10785]
When running the compile command ,make install GOBUILDIMAGE=golang:1.12.5 COMPILETAG=compile_golangimage, I receive this error when attempting to compile the source code and create the config file. First time trying to run harbor from the source code and not the installers. Any ideas?

2020/02/20 01:42:12 executed template asset:serverDoc
2020/02/20 01:42:12 Generation completed!

For this generation to compile you need to have some packages in your GOPATH:

	* github.com/go-openapi/runtime
	* github.com/jessevdk/go-flags

You can get these now with: go get -u -f src/server/v2.0/...
compiling binary for core (golang image)...
/harbor
# github.com/goharbor/harbor/src/internal/error
../internal/error/errors.go:152:5: undefined: errors.As
../internal/error/errors.go:170:11: undefined: errors.As
Makefile:330: recipe for target 'compile_core' failed
make: *** [compile_core] Error 2

**Comment by renmaosheng** [comment]
could you please try with go version > 1.13? thanks.
