### ISSUE TITLE
while replicating the whole harbor to another instance, if the image name is too long then failed.

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#10786]
while replicating the whole harbor to another instance, if the image name is too long then failed.
![image](https://user-images.githubusercontent.com/9589048/74899372-b3553000-53d7-11ea-80ea-7055bd83e596.png)

**Expected behavior and actual behavior:**
Expected behavior:   replicate success.
actual behavior:   replicate failed.

**Steps to reproduce the problem:**
push several images with long name in a repository, then replicate this project.

**Versions:**

- harbor version: [1.8.2]
- docker engine version: [18.06]
- docker-compose version: [1.24.1]

I solve this problem by alter the length of related column in pgsql.
`alter table replication_task alter column src_resource type character varying(1024) `
`alter table replication_task alter column dst_resource type character varying(1024)  `

**Comment by renmaosheng** [comment]
ziming,
      could you please fix this? thanks.

**Comment by bitsf** [comment]
I wonder if it is reasonable that the image name + tag name would be longer than 256 ?
And how long should this suppose to be ?

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/75343433-6db2ce80-58d3-11ea-9343-5902ec1635be.png)

And here you can see the docker client also has such 255 limitation, even we enlarge the db column, and make the replication work, it still not possible to pull the image down.
So I suggest still keep current limit, it is supposed to be the design before.

**Comment by louyiping** [comment]
@bitsf 
In my situation, the single image name + tag name is not  longer than 256.
Please notice that I replicated the whole harbor to another in manual trigger and there may be several tags in one repository. 
And I found field src_resource/dst_resource will contain 5 tags if replicate a repository and there are more than 5 tag in this repository.
So the length is not enough if the image name + tag name is longer than 60 in this situation.

**Comment by louyiping** [comment]
And here is a example，one row in my database that src_resource/dst_resource  is longer than 256 ： 
fe/kjl-site-standalone:[s56-zhongli-growth-log7493c3ef86f7880eac182
33bb92eb5fb83e2cc1e,c2d-designer673fc44ad05ab6511f3f0a926456cb78d4d57a56,brandcenter-coupon-detail-bugfix8e3
9ba7ffcb7b63e0729a2ff18bb64ae83bef1d4,s56-zhongli-hotfix-notice1e0d483a5fdebc1dabd10eadce9d5b988954dc1c,s56-
zhongli-limit-discountd4b4d3e0dcd055138adfade310d831038fc00541 ... 23 in total]

**Comment by bitsf** [comment]
It is said this is fixed in master now, right ? @ywk253100
