### ISSUE TITLE
Harbor 1.10.1 can not support mysql db?

### ISSUE THREAD

**Issue by ZPerling** [goharbor/harbor#10791]
When I use mysql as harbor external_database, the harbor servier is not work for me, log message:
<pre>
Feb 20 17:12:10 172.19.0.1 core[13234]: 2020-02-20T09:12:10Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'
Feb 20 17:13:10 172.19.0.1 core[13234]: 2020-02-20T09:13:10Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'
Feb 20 17:14:10 172.19.0.1 core[13234]: 2020-02-20T09:14:10Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'
Feb 20 17:15:11 172.19.0.1 core[13234]: 2020-02-20T09:15:11Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'
Feb 20 17:16:11 172.19.0.1 core[13234]: 2020-02-20T09:16:11Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'
</pre>

so the harbor not support and only support postgresql?

**Comment by louyiping** [comment]
only support postgresql..
I also want to use mysql because not familiar with pgsql.

**Comment by ZPerling** [comment]
> only support postgresql..
> I also want to use mysql because not familiar with pgsql.

wuwuwu..  thks

**Comment by bjzqhe** [comment]
I want to change the database to mysql5.7 seems to have an error

**Comment by bjzqhe** [comment]
Have you solved the problem
