### ISSUE TITLE
Store the repository name in artifact table to reduce the database query

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10805]
Currently, most of our cases for artifacts are using repository name rather than ID, storing the repository name in artifact table can reduce lots of queries for database

**Comment by renmaosheng** [comment]
I saw the PR is merged, could we close this issue? thanks.

**Comment by ywk253100** [comment]
As we store the repository name in artifact model, a lot of queries for repository aren't needed anymore. Let it open until we remove the useless repository querying code

**Comment by wy65701436** [comment]
only scheme change has been merged, the query code should be updated.

**Comment by ywk253100** [comment]
Done
