### ISSUE TITLE
"Select Your Harbor TLS Certificate", it is a chooseList, but it is keeping empty.

### ISSUE THREAD

**Issue by hanjie0** [goharbor/harbor#10801]
I have installed harbor from the rancher -->catalogs. 
And on "Configuration Options"-->"EXPOSE SERVICE OPTIONS" --> "Select Your Harbor TLS Certificate", it is a chooseList, but it is keeping empty.
I have create a secret on namespace default and harbor with my own tls.key and tls.crt
But the chooseList is always empty....
What I should do?

<img width="667" alt="harborInstall-rancherError" src="https://user-images.githubusercontent.com/6020966/75014300-ecb59a80-54c0-11ea-8314-2c43417b1d95.PNG">

**Comment by renmaosheng** [comment]
could you please contact with rancher‘s community? it seems a bug from that UI but not a harbor bug. thanks.

**Comment by xaleeks** [comment]
@hanjie0 Rancher is shipping Harbor but we are not involved in all their implementation details.  Feel free to include me on any correspondence you may have with rancher team on these integration points.  My email - xalex@vmware.com
