### ISSUE TITLE
The artifact controller should accept unrecognized mediatypes 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10811]
When I try to push a plugin I see such error and API returns 500

```
Feb 22 04:20:26 172.28.0.1 core[5870]: 2020-02-22T04:20:26Z [ERROR] [/server/error/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"descriptor for media type application/vnd.docker.plugin.v1+json not found"}]}
```

Considering the artifact can be anything I think we must support the basic management for unrecognized artifact .

Another more general issue is that the controller should wrap the error and provide more info the the error message, only printing the error in the error package lose the context.

**Comment by ywk253100** [comment]
The fix is included in https://github.com/goharbor/harbor/pull/10736
