### ISSUE TITLE
harbor upgrade from 1.4.0 to 1.9.4 ,when pull images, Handler crashed with error net/http: abort Handler

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#10813]
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] the request url is  /v2/common/nginx/blobs/sha256:bc51dd8edc1b1132bb97827ed6bd16aac332b03fb03d4c02d2088067a5fbb499#033[0mFeb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] the request url is  /v2/common/nginx/blobs/sha256:60041be5685b819d9fc3896cae4eb4418899fc16a5049623c865c39b52b5d287#033[0mFeb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] Handler crashed with error net/http: abort Handler#033[0mFeb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /usr/local/go/src/runtime/panic.go:522#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /usr/local/go/src/net/http/httputil/reverseproxy.go:309#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] Handler crashed with error net/http: abort Handler#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/registryproxy/handler.go:60#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /usr/local/go/src/runtime/panic.go:522#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /harbor/src/core/middlewares/countquota/handler.go:55#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;44m[D] [server.go:2774] |   10.172.48.48|#033[43m 401 #033[0m|   11.52082ms|   match|#033[44m GET     #033[0m /v2/common/nginx/blobs/sha256:55c440ba1ecbc2d762462d11bd214c7b50c6a5a8e8e949c073923a9786e9167e   r:/v2/*#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] /usr/local/go/src/net/http/httputil/reverseproxy.go:309#033[0m
Feb 22 17:05:42 192.168.48.1 core[2551]: 2020/02/22 09:05:42 #033[1;35m[C] [panic.go:522] the request url is  /v2/common/nginx/blobs/sha256:60041be5685b819d9fc3896cae4eb4418899fc16a5049623c865c39b52b5d287#033[0m

docker version 18.06.1-ce
harbor version 1.9.4

**Comment by renmaosheng** [comment]
@liy516 could you please upload the whole log file? thanks.

**Comment by liy516** [comment]
> 
> 
> @liy516 could you please upload the whole log file? thanks.
I would like to add that we have deployed two independent harbors without sharing redis and PGSQL. When downloading the image, we resolved the IP of the two harbor nodes through the domain name

**Comment by liy516** [comment]
> 
> 
> @liy516 could you please upload the whole log file? thanks.


[log.zip](https://github.com/goharbor/harbor/files/4242927/log.zip)

**Comment by wy65701436** [comment]
can you tell the upgrade path you did? For your case, the correcnt path should be `1.4.0 -> 1.6* -> 1.8.* -> 1.9.4`.

**Comment by mmpei** [comment]
we encounter a similar issue in version 1.7.1.
with log,
```
2020-04-02T07:53:41Z [DEBUG] [handler.go:153]: receive an event:
----ID: 9419a5a3-a2ed-4c02-8ba6-6012faa2766f
----target: library/XXXXXXXXXXXX:
----digest: sha256:XXXX
----action: pull
----mediatype: application/octet-stream
----user-agent: docker/18.06.3-ce go/go1.10.3 git-commit/d7080c1 kernel/3.10.0-862.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)
2020/04/02 07:53:41 [C] [asm_amd64.s:522] the request url is  /v2/library/XXXXXXXXXX/blobs/sha256:XXXXXXXXXX
2020/04/02 07:53:41 [C] [asm_amd64.s:522] Handler crashed with error net/http: abort Handler
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /usr/local/go/src/runtime/asm_amd64.s:522
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /usr/local/go/src/runtime/panic.go:513
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /usr/local/go/src/net/http/httputil/reverseproxy.go:284
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /go/src/github.com/goharbor/harbor/src/core/proxy/interceptors.go:262
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /go/src/github.com/goharbor/harbor/src/core/proxy/interceptors.go:230
2020/04/02 07:53:41 [C] [asm_amd64.s:522] :0
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /go/src/github.com/goharbor/harbor/src/core/proxy/interceptors.go:220
2020/04/02 07:53:41 [C] [asm_amd64.s:522] :0
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /go/src/github.com/goharbor/harbor/src/core/proxy/interceptors.go:153
2020/04/02 07:53:41 [C] [asm_amd64.s:522] :0
2020/04/02 07:53:41 [C] [asm_amd64.s:522] /go/src/github.com/goharbor/harbor/src/core/proxy/interceptors.go:168
```
i have checked the code and found that it occured when doing `p.copyResponse(rw, res.Body)` while there are enough memery.
