### ISSUE TITLE
harbor upgrade from 1.4.0 to 1.9.4,harbor no response

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#10812]
core.log

Feb 22 01:22:33 172.24.0.1 core[2545]: 2020/02/21 17:22:33 #033[1;44m[D] [server.go:2774] | 10.125.128.109|#033[42m 200 #033[0m| 1.051486897s|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositories#033[0m
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020/02/21 17:22:33 #033[1;44m[D] [server.go:2774] | 10.125.128.109|#033[42m 200 #033[0m| 903.459797ms|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositories#033[0m
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020/02/21 17:22:33 #033[1;44m[D] [server.go:2774] | 10.125.128.109|#033[42m 200 #033[0m| 1.049801936s|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositories#033[0m
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of common/zookeeper-cluster-v1: Get http://registry:5000/v2/common/zookeeper-cluster-v1/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of monitor/cadvisor: Get http://registry:5000/v2/monitor/cadvisor/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of js_zt_prod/zipkin: Get http://registry:5000/v2/js_zt_prod/zipkin/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of sichuan_rightsoperation_prod/authsso: Get http://registry:5000/v2/sichuan_rightsoperation_prod/authsso/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of monitor/elasticsearch_exporter: Get http://registry:5000/v2/monitor/elasticsearch_exporter/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address
Feb 22 01:22:33 172.24.0.1 core[2545]: 2020-02-21T17:22:33Z [ERROR] [/core/api/repository.go:192]: failed to list tags of monitor/prometheus-webhook: Get http://registry:5000/v2/monitor/prometheus-webhook/tags/list: dial tcp 172.24.0.5:5000: connect: cannot assign requested address

docker version 18.06,1-ce
harbor version 1.9.4

**Comment by renmaosheng** [comment]
Hi, could you please share how to do the upgrade? did you upgrade directly from 1.4.0 -> 1.9.4? @wy65701436 to share the jump upgrade methods, thanks.

**Comment by liy516** [comment]
> Hi, could you please share how to do the upgrade? did you upgrade directly from 1.4.0 -> 1.9.4? @wy65701436 to share the jump upgrade methods, thanks.

upgrade process ,1.4.0->1.6.3->1.8.1->1.9.4

**Comment by reasonerjt** [comment]
@liy516 Did you verify the  success of upgrades in 1.6.3 and 1.8.1?

**Comment by liy516** [comment]
> 
> 
> @liy516 Did you verify the success of upgrades in 1.6.3 and 1.8.1?

Verified, can open UI normally, log also not see wrong

**Comment by xaleeks** [comment]
we need to minimize the steps for upgrade to latest so it never takes more than, say, 3 steps.  Is there any backend like db schemas or api change that would prevent him going from a very old version like 1.4 directly to a current-2 release?  We should document all of these.  @wy65701436 @reasonerjt

**Comment by SandyLing** [comment]
I upgrade have a problem.
my harbor version is 1.4.0 
I upgrade in 1.6.0
/harbor-migration/db/util/mysql_pgsql_1_5_0.sh: line 24:   116 Killed                  python /harbor-migration/db/util/mysql_pgsql_data_converter.py /harbor-migration/db/schema/registry.mysql /harbor-migration/db/schema/registry_insert_data.pgsql

**Comment by footlegger** [comment]
I have the same problem, have to update 1.4.0 to latest 2.10.x
Has this been resolved?
Should there be an additional step between 1.8.1 and 1.9.4 in order for the upgrade to work?
