### ISSUE TITLE
Why does my harbor use TCP protocol to push and pull images? HTTP and HTTPS protocols can't

### ISSUE THREAD

**Issue by Aaron-23** [goharbor/harbor#10829]
Why does my harbor use TCP protocol to push and pull images? HTTP and HTTPS protocols can't
I can use IP plus port to push and pull the image normally, but HTTP and HTTPS cannot

**Comment by ninjadq** [comment]
could you provide more details and log?

**Comment by Aaron-23** [comment]
I solved this problem. https://github.com/SUSE/Portus/issues/1584，Thank you
