### ISSUE TITLE
"Retention error: The system is in read only mode. Any modification is prohibited." in Harbor which is NOT in read only mode

### ISSUE THREAD

**Issue by annkam** [goharbor/harbor#10835]
`2020-02-25T00:00:11Z [INFO] [/pkg/retention/job.go:192]: Retention error for artifact image:portal_epaas/epaas_forms/dev:68744 : http error: code 403, message {"code":403,"message":"{\"errors\":[{\"code\":\"DENIED\",\"message\":\"The system is in read only mode. Any modification is prohibited.\",\"detail\":\"The system is in read only mode. Any modification is prohibited.\"}]}\n"}
`

Tag retention started to work correctly after I checked and immediately unchecked "Repository Read Only" in Configuration.

**Expected behavior and actual behavior:**
Tag retention jobs should have worked correctly as Harbor was actually not in read only mode - images could be pushed and deleted and "Repository Read Only" was NOT set in Configuration

**Steps to reproduce the problem:**
I am not sure how to reproduce this problem. I don't know when it appeared and I can't check tag retention job logs earlier than Feb 24 because I get error 500 and error 404 in jobservice logs (is it another bug? for how long those job logs are stored?) but I am absolutely sure that I have not toggled the repository read only setting.

**Versions:**
Please specify the versions of following systems.

- harbor version: [ v1.9.3-c80751b8]
- docker engine version: [18.06.3-ce]
- docker-compose version: [1.24.1]

**Comment by bitsf** [comment]
When registry is doing GC job, it will be in read only mode, please check if you have schedule GC job at same time with retention job

**Comment by annkam** [comment]
Yes, that was the problem! Thank you very much!

**Comment by yogeek** [comment]
@bitsf when we choose "daily" for the GC and "daily" for the retention job, the default time is 1:00 A.M in both case hence the error.
Maybe it would be convenient to change the default time of either the GC or the retention ? Otherwise, every new user will have this problem by default before understanding that the cron job time has to be changed to a custom value to avoid collision...

**Comment by ysicing** [comment]
@bitsf  gc job is done.Why push docker images doesn't work ?
