### ISSUE TITLE
Whether the installation package of arm architecture can be provided

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#10849]
Whether the installation package of arm architecture can be provided

**Comment by ninjadq** [comment]
yes, but the manifest list is not ready. it will support in harbor v2.0

**Comment by Iverson-lena** [comment]
Thanks.
When is v2.0 planned to be released?

**Comment by xaleeks** [comment]
@Iverson-lena  2.0 rc will most likely be early April.

**Comment by ninjadq** [comment]
sorry @Iverson-lena , I get your question wrong. the manifest list will be supported in harbor 2.0 in which image can containing multiple architectures. But harbor itself only provided in x86  arch

**Comment by xaleeks** [comment]
I'm consolidating all requests to this one https://github.com/goharbor/harbor/issues/10578, please comment here.
