### ISSUE TITLE
Docker Image sign with notary and StepCA

### ISSUE THREAD

**Issue by Lyrwon** [goharbor/harbor#10843]
Hi, 

I've spent a lot of time with trying to include a private certificate in my harbor project and my conclusion is:
There must be an easier way to include certificates from a private CA.
Can someone please show me the right way?

My Setup:
 Ubuntu 18.04.4 LTS
 CPU: 2
 Total Mem: 4 GB

Docker
 Server Version: 19.03.6
 Storage Driver: overlay2

Docker-compose
 docker-compose version 1.25.3, build d4d1b42b

Harbor-release-1.10.0
 --with-notary
 --with-clair

The docker-images will be built and pushed out of my gitlab CI.

**Comment by ninjadq** [comment]
did you mean to put your private ca-cert into harbor containers?

**Comment by Lyrwon** [comment]
Finally, we used Smallstep Ca to sign
