### ISSUE TITLE
Helm installation documentation improvements

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#10845]
From @xaleeks via email:

This is based on our current helm installation guide.  I feel like it could be a lot more user-friendly for the first time Harbor user, especially for someone with little experience with helm.  Can you try to make some changes based on below and @Wenkai Yin or @Yan Wang can assist where needed.  

@ywk253100, please help Stuart with any questions that he might have.

Trying to use the demo server via
https://github.com/goharbor/harbor/blob/master/docs/1.10/install-config/demo-server.md#access-the-demo-server. 

- Right now there is no "Sign up for an account" link like it says in the instructions.  This is becuase we’ve disabled self-registration by default so this won’t show up whenever we upgrade demo environment to a new version.  Documentation needs to reflect this and that you can use it once you log in and turn on self-registration in ‘configuration’ tab

Trying to install harbor helm now via instructions in
https://github.com/goharbor/harbor-helm 

1. "Configure the chart" 
-	I'm not sure what the syntax would be to opt for NodePort using --set.  It would be helpful to link to https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of-set.
-	I gather the syntax is --set name=value, which leaves me wondering what value to use with NodePort, e.g. --set NodePort=true, --set NodePort=on, --set NodePort=, etc.

2. "Configure the external URL"
-	This section doesn't make it clear how to actually perform the configuration. How should I use --set parameters if I prefer not to download and edit the Helm chart? Can I just skip it and take the defaults?  
-	This section tells me what value to use for domain, but not for protocol or port. It doesn't give me any help, such as a link, for how to find the IP address of a Kubernetes node (for the NodePort case).

Then it says ‘if expose the service via NodePort, the domain should be the IP address of one Kubernetes node’ 
-	The wording "the IP address of one Kubernetes node" is rather confusing. How should I decide which node to pick? (And what happens to the Harbor instances running on other nodes - are they simply unused or do they "federate" with the instance on the node I pick in some way?)

Finally, the last sentence "If Harbor is deployed behind the proxy, set it as the URL of proxy." 
-	made me wonder exactly what I would have to do in that case. Maybe it would be obvious to someone who is used to using a proxy, but not clear to a first time user.

3. "Configure the way how to persistent data" (should be "Configure how to persist data")
-	Again, how should I use --set parameters to configure this if I prefer not to download and edit the Helm chart? Can I just skip it and take the defaults?
-	The section was also too vague. I would probably choose "Disable" for simplicity, but it wasn't clear how to set that option.

4. "Configure the secrets" 
-	Once again, how should I use --set parameters to configure this if I prefer not to download and edit the Helm chart? Can I just skip it and take the defaults?

5. "Install the chart"
-	It would be really helpful to provide a way of validating that the installation has been successful and of getting me to the point where I can push my first image.  

6. "Configuration"
-	This section looks like great reference material, but doesn't really help me get started, especially as it wasn't referred to earlier in the document.  Maybe think about breaking this up and mixing it in with the rest

**Comment by xaleeks** [comment]
@stuclem  Hi Stuart, Let's keep 'self registration' on by default so demo users can always register for an account, so the documentation is correct here.  It's incumbent on the harbor team to make sure that self-registration is flipped on after every upgrade of Demo server.  The alternative is to enable it by default and we don't want that due to issue discovered last time.

**Comment by martinwoods** [comment]
@stuclem & @xaleeks - self registration is still switched off, are you guys still working on this? Has the demo server been upgraded recently? Cheers
