### ISSUE TITLE
GC is unable to start

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#10855]
Hi Team,

I am trying to start the GC both automatic and manually but it is failing to start.
In the jobservice.log, i could see the below error.
 **jobservice[2292]: 2020-02-26T07:44:56Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'IMAGE_GC:ffbd99a5c07328bc5787945e' exit with error: http error: code 500, message {"code":500,"message":"Internal Server Error"}** 

Thanks,
Ayush

**Comment by AyushCloud** [comment]
Harbor 1.9.3
Please let me know if any more information is required.

**Comment by ninjadq** [comment]
could you provide the logs of your harbor?

**Comment by AyushCloud** [comment]
Do you need any specific log files from /var/log/harbor or all the log files ?

**Comment by AyushCloud** [comment]
[jobservice.log](https://github.com/goharbor/harbor/files/4259670/jobservice.log)
Job Service Logs

**Comment by AyushCloud** [comment]
[jobservice.log](https://github.com/goharbor/harbor/files/4259671/jobservice.log)
jobservice.log

**Comment by AyushCloud** [comment]
[jobservice.log](https://github.com/goharbor/harbor/files/4259702/jobservice.log)

**Comment by AyushCloud** [comment]
[jobservice.log](https://github.com/goharbor/harbor/files/4259910/jobservice.log)

**Comment by AyushCloud** [comment]
Feb 27 05:21:37 IP jobservice[2292]: 2020-02-27T05:21:37Z [INFO] [/jobservice/logger/sweeper_controller.go:97]: 40 outdated log entries are sweepped by sweeper *sweeper.FileSweeper 
Feb 27 05:27:55 IP jobservice[2292]: 2020-02-27T05:27:55Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/7e7a31a4b8e44725e3c60e57/log' error: 404 {"code":10010,"message":"object is not found","details":"7e7a31a4b8e44725e3c60e57"} 
Feb 27 05:28:05 IP jobservice[2292]: 2020-02-27T05:28:05Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/7e7a31a4b8e44725e3c60e57/log' error: 404 {"code":10010,"message":"object is not found","details":"7e7a31a4b8e44725e3c60e57"} 
Feb 27 05:28:12 IP jobservice[2292]: 2020-02-27T05:28:12Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/7e7a31a4b8e44725e3c60e57/log' error: 404 {"code":10010,"message":"object is not found","details":"7e7a31a4b8e44725e3c60e57"} 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"IMAGE_GC","id":"53eb22389905faa405162a57","t":1582783463,"args":null,"unique":true} 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [INFO] [/common/registryctl/client.go:41]: initializing client for reigstry http://registryctl:8080 ... 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Feb 27 06:04:25 IP jobservice[2292]: 2020-02-27T06:04:25Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'IMAGE_GC:53eb22389905faa405162a57' exit with error: http error: code 500, message {"code":500,"message":"Internal Server Error"}

**Comment by AyushCloud** [comment]
The Service has 2 Scalable LB(Active-Active), 2 Harbor (Active-Active), 1 PostgreSQL() and 1 Redis VM

**Comment by wy65701436** [comment]
please refer to the [comments](https://github.com/goharbor/harbor/issues/7945#issuecomment-498123934), and provide the results

**Comment by AyushCloud** [comment]
I already refer the comments before opening the issue. Tried the command sudo -E -u \#10000 registry garbage-collect --delete-untagged=true /etc/registry/config.yml but it did not throw any error.

**Comment by catchups** [comment]
You need to check the Registry log at that time. I think it would be better if you also had Redis logs.

**Comment by AyushCloud** [comment]
I have checked all the registry log files but find relevant information only in the jobservice.log, which i already shared.
**redis .log** doesn't have any error.
7589:M 09 Mar 2020 05:41:58.061 * Background saving started by pid 26602 
26602:C 09 Mar 2020 05:41:58.070 * DB saved on disk 
26602:C 09 Mar 2020 05:41:58.070 * RDB: 2 MB of memory used by copy-on-write 
7589:M 09 Mar 2020 05:41:58.161 * Background saving terminated with success 
7589:M 09 Mar 2020 05:46:59.095 * 10 changes in 300 seconds. Saving... 
7589:M 09 Mar 2020 05:46:59.096 * Background saving started by pid 27435 
27435:C 09 Mar 2020 05:46:59.105 * DB saved on disk 
27435:C 09 Mar 2020 05:46:59.105 * RDB: 2 MB of memory used by copy-on-write 
7589:M 09 Mar 2020 05:46:59.197 * Background saving terminated with success 
7589:M 09 Mar 2020 05:52:00.047 * 10 changes in 300 seconds. Saving... 
7589:M 09 Mar 2020 05:52:00.049 * Background saving started by pid 28016 
28016:C 09 Mar 2020 05:52:00.058 * DB saved on disk 
28016:C 09 Mar 2020 05:52:00.058 * RDB: 2 MB of memory used by copy-on-write 
7589:M 09 Mar 2020 05:52:00.149 * Background saving terminated with success 
7589:M 09 Mar 2020 05:57:01.068 * 10 changes in 300 seconds. Saving... 
7589:M 09 Mar 2020 05:57:01.069 * Background saving started by pid 28612 
28612:C 09 Mar 2020 05:57:01.078 * DB saved on disk 
28612:C 09 Mar 2020 05:57:01.079 * RDB: 2 MB of memory used by copy-on-write

**Comment by wy65701436** [comment]
can you set the log level to debug? and please the logs？ package all of the logs into a tgz is helpful for debugging.
