### ISSUE TITLE
harbor version 1.10  ，Pull mirror and try again

### ISSUE THREAD

**Issue by shaojielinux** [goharbor/harbor#10866]
harbor version 1.10  ，pull mirror has been resting
<img width="778" alt="docker  retrying" src="https://user-images.githubusercontent.com/28892865/75423944-bd000a00-597a-11ea-9e63-af47cacdcfa4.png">

**Comment by xaleeks** [comment]
@shaojielinux  Sorry is your local machine pulling from harbor?  Can't really tell from the screen you posted.  Can you detail what you are trying to do.  Based on this alone, it could even be a network issue.  There's really not enough to help troubleshoot this.

**Comment by catchups** [comment]
Many people will be able to help you if you attach the environment, version, and log data that are running Harbor. There are so many things that can bring up that screen.
