### ISSUE TITLE
Login status expired after 1 day when using oidc(DEX) authentication

### ISSUE THREAD

**Issue by joeyjy** [goharbor/harbor#10865]
Hi harbor team，

we are using harbor in prod environment for a auto building service, we find that pushing process always fails due to auth problem after 1 day, so we must manully sign in once every day.

want to know where we can configure this expiration time? we use DEX as oidc provider.

Thanks!

**Comment by reasonerjt** [comment]
As we discussed offline, the expiration is tied to id token you can update that in oidc provider, closing.
