### ISSUE TITLE
Retention job failed due to below error

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#10862]
Feb 27 11:58:02 10.104.1.1 jobservice[2020]: 2020-02-27T06:28:02Z [INFO] [/pkg/retention/job.go:113]: Retention error for artifact image:core-remedy-nightly/coreremedy-1911/9.1-r/201910261441/remedy/smart-reporting:201910261441 : http error: code 500, message {"code":500,"message":"{\"errors\":[{\"code\":\"InternalError\",\"message\":\"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned\",\"detail\":\"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned\"}]}\n"}

**Comment by dbenduga** [comment]
more logs----
55576d00c1' exit with error: mismatch status for running job: expected <Running <> got Running
Feb 27 12:02:44 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:44Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"RETENTION","id":"d91a6561632d8a929d9bf119","t":1582785163,"args":null,"fails":2,"err":"mismatch status for running job: expected \u003cRunning \u003c\u003e got Running","failed_at":1582785132}
Feb 27 12:02:44 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:44Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'RETENTION:d91a6561632d8a929d9bf119' exit with error: mismatch status for running job: expected <Running <> got Running
Feb 27 12:02:47 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:47Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"RETENTION","id":"a08bb6d116b3c96f09a7cc10","t":1582785165,"args":null,"fails":2,"err":"mismatch status for running job: expected \u003cRunning \u003c\u003e got Running","failed_at":1582785116}
Feb 27 12:02:47 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:47Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'RETENTION:a08bb6d116b3c96f09a7cc10' exit with error: mismatch status for running job: expected <Running <> got Running
Feb 27 12:02:47 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:47Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"RETENTION","id":"bc8827e7f981068aac7e9b0a","t":1582785166,"args":null,"fails":2,"err":"mismatch status for running job: expected \u003cRunning \u003c\u003e got Running","failed_at":1582785108}
Feb 27 12:02:47 10.104.1.1 jobservice[2020]: 2020-02-27T06:32:47Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"RETENTION","id":"fa7e598226f9ef69c1694b95","t":1582785166,"args":null,"fails":2,"err":"mismatch status for running job: expected \u003cRunning \u003c\u003e got Running","failed_at":1582785108}

**Comment by bitsf** [comment]
@dbenduga which version are you using?
@wy65701436 I remember this is a known issue?

**Comment by CptDaniel** [comment]
I get this error as well. I'm currently using version 1.10.1, but had this issue as well with version 1.9.4. Is there any workaround or something? I don't use quotas at all.
