### ISSUE TITLE
Web: Cannot log in after upgrade from 1.8.x to 10.10.1

### ISSUE THREAD

**Issue by hactar** [goharbor/harbor#10880]
I upgraded Harbor 1.8 via the upgrade instructions (running the migration docker image, etc). After the upgrade, I cannot log in pre-upgrade users via the web. I receive a `Invalid user name or password.` message. I have tried multiple users. Logging these users in via docker login works, and I can still push/pull from the repository. If I create a new user via sign up (I can't log in the admin), this new user can log in fine.

Core log when an "old" user logs in:

```
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/filter/security.go:232]: OIDC CLI modifier only handles request by docker CLI or helm CLI
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/filter/security.go:459]: can not get user information from session
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/filter/security.go:514]: user information is nil
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/filter/security.go:528]: using local database project manager
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/filter/security.go:530]: creating local database security context...
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/common/dao/user.go:277]: Check if user old.user is super user
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/auth/authenticator.go:139]: Current AUTH_MODE is db_auth
Feb 28 02:24:28 172.26.0.1 core[1199]: 2020-02-28T01:24:28Z [DEBUG] [/core/auth/authenticator.go:152]: Login failed, locking old.user, and sleep for 1.5s
Feb 28 02:24:30 172.26.0.1 core[1199]: 2020-02-28T01:24:30Z [ERROR] [/core/controllers/base.go:109]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'
```

A new user:
```
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:232]: OIDC CLI modifier only handles request by docker CLI or helm CLI
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:459]: can not get user information from session
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:514]: user information is nil
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:528]: using local database project manager
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:530]: creating local database security context...
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/common/dao/user.go:277]: Check if user moemoe is super user
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/auth/authenticator.go:139]: Current AUTH_MODE is db_auth
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020/02/28 01:27:03.428 #033[1;44m[D]#033[0m [server.go:2774]  |  84.112.250.31|#033[97;42m 200 #033[0m|  18.601809ms|   match|#033[97;46m POST    #033[0m /c/login   r:/c/login
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/sessionchecker.go:22]: Mark the request as no-session
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:232]: OIDC CLI modifier only handles request by docker CLI or helm CLI
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:462]: got user information from session
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:468]: using local database project manager
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020-02-28T01:27:03Z [DEBUG] [/core/filter/security.go:470]: creating local database security context...
Feb 28 02:27:03 172.26.0.1 core[1199]: 2020/02/28 01:27:03.478 #033[1;44m[D]#033[0m [server.go:2774]  |  84.112.x.x|#033[97;42m 200 #033[0m|   3.747505ms|   match|#033[97;44m GET     #033[0m /api/users/current   r:/api/users/:id
```

As the log does not contain anything useful I'm at a loss, any help would be appreciated.

**Comment by rafis** [comment]
Is master secret key /data/secret/keys/secretkey preserved?

**Comment by hactar** [comment]
Yes, the /data folder is stored to the local file system, the /data/secret/keys/secretkey is preserved.

**Comment by hactar** [comment]
I was able to log in by setting the admin's username, salt and password version to that of one of the new users. One thing I noticed is that the old users have a "sha1" password version, the new users have a sha256 password version, could this be the issue?

**Comment by gravcat** [comment]
Also experiencing this coming from `v1.8.4` to `v1.10.1`. `docker login` can use the creds just fine, but web auth fails. 

Nothing too exciting in my logs, but on the frontend I do observe the following
![image](https://user-images.githubusercontent.com/15221447/76985121-bdeae280-690d-11ea-8f25-bbb5030666cc.png)

though `core` is stuck in 'unhealthy` state, trying to figure out why

**Comment by prima101112** [comment]
are you using https://goharbor.io/docs/1.10/administration/upgrade/ @hactar 
and make sure you backup your db before migration?

**Comment by hactar** [comment]
@prima101112 I did follow these instructions and ran the migrator, yes. Whether I ran it correctly is a different story, I find the instructions confusing (after unpacking I have two harbor.ymls, mine and the one from unzipping the new version) which one do I pass to the migrator script? Also I'm always worried as I have customizations in the docker-compose file so that harbor works with my traefik reverse proxy, so I recustomize it after running.

Harbor has an unusually complicated upgrading process for a docker image - where usually its just enough to recreate the container after pulling :latest...

Confused as to how this would help? according to the link you provided DB schemes are upgraded during booting of the image, not by the migrator tool itself?

**Comment by prima101112** [comment]
yes it is confusing but this is what we have now.
i will try to reproduce it and see if there is some thing i could found and may be fix the docs

**Comment by frankfil** [comment]
Apologies for commenting on an old closed issue but I've just run into this very same problem but found a solution that worked for me.

Like @hactar I was upgrading from 1.8 to 1.10 (with the added intention of then upgrading to 2.2) and struck this very same issue where LDAP users could not login after upgrading from 1.8 to 1.10.

After a bit a research I went back to my 1.8 backup and decided to "walk" the upgrade to 1.10 by upgrading to 1.9 first and seeing if the issue appeared there.

It didn't and then when upgrading from 1.9 to 1.10 the LDAP login issue was not present and I was subsequently able to successfully upgrade to 2.2.

I can only suspect something in the upgrade process in 1.10 was different to the upgrade process in 1.9 that triggered the LDAP user issue - I've not looked into that at all.

Just thought I'd post here in case someone else hits this same problem as this method may work for them too.
