### ISSUE TITLE
Harbor bad architecture does not support large repositories

### ISSUE THREAD

**Issue by rafis** [goharbor/harbor#10885]
**Is your feature request related to a problem? Please describe.**
We are using Harbor with large data 2TB. We are always receiving errors like 504
#6876 
#3446
queued job hangs and et cetera. Today we got all Clair reports got deleted:
![image](https://user-images.githubusercontent.com/3502395/75520267-3567d900-5a16-11ea-9c14-93a1a730da32.png)

**Describe the solution you'd like**
Implement load testing, stress testing and other non-functional testing. Run them periodically or integrate them into your Continuous Integration process (many companies like Google and Yandex does that).
Refactor architecture, implement CQRS patterns and increase timeouts. Nginx by default has timeout of 60s.

**Comment by reasonerjt** [comment]
@rafis 
Please clarify what version are you using, how do you deploy it?  What storage do you use?

When you say 504 could you clarify what requests are receiving 504?  What's the load when you start seeing problems?

By 2TB do you mean the total size of images are 2TB or 1 image with 2TB?

**Comment by heww** [comment]
Since v2.0.0 the information of the artifact (image) is stored in the database, the APIs to list the repositories won't be timeout easily now.

For the queued status of the scanning job, you can try to increase the `max_job_workers` of the job service.
