### ISSUE TITLE
Can image replication support the replication of images under multiple repositories at the same time?

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#10888]
Can image replication support the replication of images under multiple repositories at the same time?

For example, copy the following two images at the same time.
 repoA/nginx:1 and repoB/tomcat:2

**Comment by xaleeks** [comment]
I'm not sure if I understand your requirement correctly, are they replicated to the same endpoint?  you can configure multiple replication rules to run at the same time @Iverson-lena

**Comment by catchups** [comment]
Are there multiple departures? Or are there multiple endpoints?
