### ISSUE TITLE
API: search user by email

### ISSUE THREAD

**Issue by lvisterin** [goharbor/harbor#10891]
I am trying to search a user by their email using the `/users/search` API endpoint. However, when I only enter an email to search by it will return a 400 Bad Request:

```
{"code":400,"message":"username is required"}
```

This can be reproduced using the Swagger UI. I am on Harbor v1.10.1.

It would be nice if you could search a user by their email without having to know the username.

**Comment by catchups** [comment]
I'm using Harbor v1.8
on v1.8, API /users/search username value is not required value.
I can only return results with an Email value.

Request :
curl -X GET "https://harbor.local/api/users/search?email=hyucksu.jang%40samsung.com" -H "accept: application/json"

Response :
[
  {
    "user_id": 18,
    "username": "hyucksu.jang"
  }
]

**Comment by xaleeks** [comment]
Seems this has been resolved.  Thanks for the help @catchups

**Comment by alexandre-k** [comment]
With Harbor version v2.0 and above the same problem happens, we cannot search by email.

**Comment by alexandre-k** [comment]
I answer to myself:
With the search function we cannot search users with email from v2.0 but a workaround is to list users and filter with a query string.
Example with the Python client:
` 
api_response = api_instance.list_users(q="email=joh.doe@email.com")
`
