### ISSUE TITLE
tag retetion for OCI, whether delete untagged image

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#10906]
Option 1: default delete all untagged images when retention rule match the repo
Option 2: default keep all untagged images when retention rule match the repo
Option 3: add a checkbox to determine whether keep untagged when retention rule match the repo
Option 4: add a rule to match the untagged images and determine the retention behavior

**Comment by reasonerjt** [comment]
@bitsf please clarify which option is chosen.

**Comment by bitsf** [comment]
pr #10922
use option 3, with default keep old untagged images when upgrade to v2.0
