### ISSUE TITLE
unable to push images to harbor

### ISSUE THREAD

**Issue by posina** [goharbor/harbor#10912]
I am running buildkit in kubernetes cluster and trying to build images using  buildctl command and push images to harbor its showing 404 error does anyone facing similar kind of issue

**Comment by wglambert** [comment]
Could you post log output and the commands you're using?

And are you able to ping it from your cluster?

**Comment by posina** [comment]
Hello @wglambert  i am building the images inside the buildkit container 
buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=<artifactory name>
/proj-sant-devops/test15,push=true
this is the error i am facing while pushing the images to harbor  
error: failed to solve: rpc error: code = Unknown desc = failed to do request: Head <registry name>/v2/buildkit/test15/blobs/sha256:423ae2b273f4c17ceee9e8482fa8d071d90c7d052ae208e1fe4963fceb3d6954: Not Found
Yes i am able to ping inside the cluster

**Comment by catchups** [comment]
Many people will be able to help you if you attach the environment, version, and log data that are running Harbor.

**Comment by xaleeks** [comment]
closing for now
