### ISSUE TITLE
Matrix for supported artifacts and cli

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10914]

**Comment by xaleeks** [comment]
v2.0 support comprehensive list here - https://docs.google.com/document/d/14M-f5Q_5lxQu4Cd3pNn7E--mzbQeq2lBJ-QNiEVbT74/edit

This will be constantly evolving as we test various client tooling.  quick summary on planned support for the 2.0 release

supported artifacts include : Docker images, Docker manifest lists / OCI indexes, Helm charts, CNAB thin bundles, CNAB thick bundles.
unsupported artifacts : anything besides listed above, arbitrary mediaTypes

client tooling:
Docker images / manifest lists - docker client
helm charts - helm3, chartmuseum, ORAS
CNAB bundles - CNAB to OCI, ORAS, Docker app, Porter
OPAs - ORAS, conftest

**Comment by xaleeks** [comment]
We are also looking for anyone in community to help us test some of the more advanced features of harbor with these artifact types.  Or any other OCI compliant artifact type that is of interest to you.  If anyone is interested, please let me know!

**Comment by habrlesni** [comment]
@xaleeks , could you share https://docs.google.com/document/d/14M-f5Q_5lxQu4Cd3pNn7E--mzbQeq2lBJ-QNiEVbT74/edit , now it cannot be accessed. Thanks a lot
