### ISSUE TITLE
Provide option to configure OIDC from config file

### ISSUE THREAD

**Issue by cten** [goharbor/harbor#10910]
It would benefit those who use GitOps to be able to configure OIDC from configuration file and/or env vars instead of through UI only.

**Comment by bjethwan** [comment]
Can we create a Postgres SQL script to dump and later load that config data (only if exposing this in harbor.yml is too much of a task)?

**Comment by reasonerjt** [comment]
@cten

I don't think we will support the configurations that are modifiable by API to be set via file, otherwise there will be issue when the process restarts.
You need to call the API to modify the OIDC settings.

**Comment by xaleeks** [comment]
I think I see the workflow you have in mind for gitops and why you need this, but can you expand a little bit?   @cten

**Comment by cten** [comment]
What if instead a Harbor operator was created that watched ConfigMaps/Secrets and updated Harbor through the API based on the configs in said ConfigMaps/Secrets. I know this is K8s specific so this might not be the best place to bring this feature request up.

**Comment by reasonerjt** [comment]
@cten the OIDC settings are stored in DB, not in CM.

**Comment by xaleeks** [comment]
it's not a high priority issue for us, but feel free to submit a proposal or a PR on this, closing this for now

**Comment by zillani** [comment]
we are desperately looking for this feature as well.
