### ISSUE TITLE
[Question] How to verify artifact information of helm chart file

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#10935]
I've scripting push helm chart file API test, my question is how to verify if artifact information return from API is right? Is digest is a target to verify?

**Helm chart Command:**  
        helm3 chart push $registry/project-1583309992137/harbor_api_test:0.2.0
**Return:** 
        The push refers to repository [$registry/project-1583309992137/harbor_api_test]
        ref:     10.92.103.227/project-1583309992137/harbor_api_test:0.2.0
        digest:  c72423f3d5eb8f8f2d0731581f2f2a93acbc901a7b374b3e3d2291084ed183cc
        size:    15.9 KiB
        name:    harbor
        version: 0.2.0
        0.2.0: pushed to remote (1 layer, 15.9 KiB total)

**API Return:**

({'addition_links': {u'dependencies': {u'absolute': False,
                                      u'href': u'/api/v2.0/projects/project-1583309992137/repositories/harbor_api_test/artifacts/sha256:50c4d920a6ad9f2f37d57c00b1a2c2a407519217caa73cafbbfe3de654d59e6c/additions/dependencies'},
                    u'readme.md': {u'absolute': False,
                                   u'href': u'/api/v2.0/projects/project-1583309992137/repositories/harbor_api_test/artifacts/sha256:50c4d920a6ad9f2f37d57c00b1a2c2a407519217caa73cafbbfe3de654d59e6c/additions/readme.md'},
                    u'values.yaml': {u'absolute': False,
                                     u'href': u'/api/v2.0/projects/project-1583309992137/repositories/harbor_api_test/artifacts/sha256:50c4d920a6ad9f2f37d57c00b1a2c2a407519217caa73cafbbfe3de654d59e6c/additions/values.yaml'},
                    u'vulnerabilities': {u'absolute': False,
                                         u'href': u'/api/v2.0/projects/project-1583309992137/repositories/harbor_api_test/artifacts/sha256:50c4d920a6ad9f2f37d57c00b1a2c2a407519217caa73cafbbfe3de654d59e6c/additions/vulnerabilities'}},
 'annotations': {},
 'digest': 'sha256:50c4d920a6ad9f2f37d57c00b1a2c2a407519217caa73cafbbfe3de654d59e6c',
 'extra_attrs': {u'apiVersion': u'v1',
                 u'appVersion': u'1.5.0',
                 u'dependencies': [{u'name': u'redis',
                                    u'repository': u'https://kubernetes-charts.storage.googleapis.com',
                                    u'version': u'3.2.5'}],
                 u'description': u'An Enterprise-class Docker Registry by VMware',
                 u'home': u'https://github.com/vmware/harbor',
                 u'icon': u'https://github.com/vmware/harbor/blob/master/docs/img/harbor_logo.png',
                 u'keywords': [u'vmware', u'docker', u'registry', u'harbor'],
                 u'maintainers': [{u'email': u'huh@vmware.com',
                                   u'name': u'Jesse Hu'},
                                  {u'email': u'username.taken@gmail.com',
                                   u'name': u'paulczar'}],
                 u'name': u'harbor',
                 u'sources': [u'https://github.com/vmware/harbor/tree/master/contrib/helm/harbor'],
                 u'version': u'0.2.0'},
 'id': 6,
 'labels': None,
 'manifest_media_type': 'application/vnd.oci.image.manifest.v1+json',
 'media_type': 'application/vnd.cncf.helm.config.v1+json',
 'project_id': 27,
 'pull_time': datetime.datetime(1, 1, 1, 0, 0, tzinfo=tzlocal()),
 'push_time': datetime.datetime(2020, 3, 4, 8, 18, 19, 614100, tzinfo=tzlocal()),
 'references': None,
 'repository_id': 6,
 'scan_overview': None,
 'size': 17193,
 'tags': [{'artifact_id': 6,
           'id': 6,
           'immutable': False,
           'name': '0.2.0',
           'pull_time': datetime.datetime(1, 1, 1, 0, 0, tzinfo=tzlocal()),
           'push_time': datetime.datetime(2020, 3, 4, 8, 18, 20, 76414, tzinfo=tzlocal()),
           'repository_id': 6,
           'signed': False}],
 'type': 'CHART'}

**Comment by ywk253100** [comment]
Double checked that the digest returned by helm command is the digest of layer not the artifact. So check the existence by tag is ok
