### ISSUE TITLE
denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by crazy-canux** [goharbor/harbor#10936]
Do we limit tag numbers for one repository?

I can't push images to harbor with error: "denied: requested access to the resource is denied".
After check, I have 150 tags on this repository.
So, I remove some tags and push back to normal.

**Comment by wglambert** [comment]
Yeah it seems previously it would give a 500 error and it was changed to a 400 when a quota is exceeded
https://github.com/goharbor/harbor/issues/8688

**Comment by crazy-canux** [comment]
So, it's not configurable on harbor_1.8?
Looks I have to upgrade to 1.10.
