### ISSUE TITLE
There are a lot of problems with link 404

### ISSUE THREAD

**Issue by lanyuange** [goharbor/harbor#10943]
https://github.com/goharbor/harbor/tree/master/docs/1.10
for example:
  https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/create-robot-accounts.md
   https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/configure-webhooks.md
  https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/configure-project-whitelist.md
  https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/implementing-content-trust.md
  https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/working-with-images.md
  
 also there are 404 problems with the pictures

**Comment by jonleopard** [comment]
Yah I think there are a couple PR's addressing this - and it really needs to be fixed. Could anyone review those PR's or post the correct links ? I'm still searching for this one:
https://github.com/goharbor/harbor/blob/master/docs/1.10/working-with-projects/pulling-pushing-images.md

**Comment by xaleeks** [comment]
All of these are have been fixed or done away with.  Please navigate from the website https://goharbor.io/ for all your doc needs.  Let me know on this ticket if you find any others, closing now
