### ISSUE TITLE
Groups which are auto-created have the DN name instead of the attribute value which we have provided in "LDAP Group GID"

### ISSUE THREAD

**Issue by kmk371661** [goharbor/harbor#10940]
**Expected behavior** 

We have set under the Harbor LDAP Configuration field "LDAP Group GID" to "cn"

Example:
DN: CN=MA_PKS-Admin,OU=MA,OU=Application,OU=Groups,OU=Global,OU=Production,DC=user,DC=com

Group name in harbor - MA_PKS-Admin( expected)

The description of "LDAP Group GID" says: "the group in Harbor is named with this attribute by default". And this is what would actually expect.

 **actual behavior:**

Plenty of groups which are not named like below are added under group in harbor.

 "CN=MA_PKS-Admin,OU=GA,OU=Application,OU=Groups,OU=Global,OU=Production,DC=User,DC=com". (basically group name == DN)

However the majority of groups that are around, got "autocreated" in the wrong way with "group name" == "DN", which is not as we configured.

**Versions:**

Harbor 1.9.3-build.2

**Additional context:**

If we add a group manually via "New Group" -> (Import LDAP Group) we can specify LDAP DN and Name. In this way we can set "DN" and "name" accordingly / correctly and everything is fine.

Harbor Authentication configured against LDAP (Opsman: LDAP - Login Harbor with LDAP Users).
Authentication is working fine generally.

**Comment by stonezdj** [comment]
Should fix in 
https://github.com/goharbor/harbor/blob/master/src/core/auth/ldap/ldap.go#L115

**Comment by kmk371661** [comment]
It seems that Harbor LDAP is automatically adding few groups including the DN which we are adding manually.

We do not want all these groups automatically added, for security reasons.

We found user who is part of manually added DN are also part of automatically added groups.

**Comment by reasonerjt** [comment]
@kmk371661 you consider this a security issue because we show the DN in UI?  Or because the groups are added?

**Comment by kmk371661** [comment]
@reasonerjt because the groups are getting added, user in other groups can login to the Harbor.

**Comment by reasonerjt** [comment]
@kmk371661 
user in other groups can login to the Harbor even the groups are not added.

**Comment by tleveille** [comment]
@reasonerjt we got the same issue. Other membership group of one user are also added which mean people from these groups can log on even if these groups should have been filtered out. In our case it added groups that were not within the same level as our base dn search.
