### ISSUE TITLE
GET /repositories/{repo_name}/tags returns data with placeholder dates

### ISSUE THREAD

**Issue by Dominick-Peluso-Bose** [goharbor/harbor#10950]
I'm trying to get a list of tags with the Harbor API that are ordered by date (I'm essentially looking for the latest tag). But it seems that the tags from these calls come in alphabetical order. I think the only option available to me is to sort the array by date, but given I only need the tag value, I'd like to use `detail=false` to reduce the size of the payload. When I include `detail=false`, the date values appear to be some placeholder value which cannot be used to sort the tags.

**Expected behavior and actual behavior:**
When I call `GET /repositories/{repo_name}/tags?detail=true`, I see results with correct date values:
```js
[
  {
    "digest": "sha256:ac73cbaf16cd93437c169bd97d83b32f554b9c017373f316931f2f623e9936aa",
    "name": "fix-badges.4.1",
    "size": 36636022,
    "architecture": "amd64",
    "os": "linux",
    "os.version": "",
    "docker_version": "17.12.1-ce",
    "author": "redacted",
    "created": "2020-03-02T19:07:08.636545833Z",
    "config": {
      "labels": {
        "maintainer": "redacted"
      }
    },
    "immutable": false,
    "signature": null,
    "scan_overview": { /* redacted */ },
    "labels": [],
    "push_time": "2020-03-02T19:46:08.131158Z",
    "pull_time": "0001-01-01T00:00:00Z"
  },
/* ... */
```
But when I call `GET /repositories/{repo_name}/tags?detail=false`, all of the date values say "0001-01-01T00:00:00Z":

```js
[
  {
    "digest": "",
    "name": "fix-badges.4.1",
    "size": 0,
    "architecture": "",
    "os": "",
    "os.version": "",
    "docker_version": "",
    "author": "",
    "created": "0001-01-01T00:00:00Z",
    "config": null,
    "immutable": false,
    "signature": null,
    "labels": null,
    "push_time": "0001-01-01T00:00:00Z",
    "pull_time": "0001-01-01T00:00:00Z"
  },
/* ... */
```
I would expect the fields `created`, `push_time`, and `pull_time` to return real date values the same was `detail=true` does.

**Steps to reproduce the problem:**
Call `GET /repositories/{repo_name}/tags?detail=false`

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.10.0-6b84b62f
- docker engine version: 17.12.1-ce
- docker-compose version: N/A

**Comment by catchups** [comment]
If detail = false, always returns the default value except the name value. Use detail = true if you want a normal return for other values.
