### ISSUE TITLE
Pushing with podman fails in sizequota handler 

### ISSUE THREAD

**Issue by rbtr** [goharbor/harbor#10952]
**Expected behavior and actual behavior:**
Expected: I should be able to push an image with podman or other OCI compatible tools.
Actual: Anything but Docker (in my testing) errors in the quota middleware and fails with an HTTP 500 error to the client.

**Steps to reproduce the problem:**
Build and push an image using podman.

**Versions:**
- harbor version: [1.10.1]

**Additional context:**
Harbor is deployed in Kubernetes from the latest harbor-helm release.

**Logs**
harbor-core: 
```
2020/03/05 16:30:23.131 [D] [server.go:2774]  |   72.83.31.122| 201 |  34.043681ms|   match| PUT      /v2/dev/x/blobs/uploads/4993ccec-7042-4050-a3a0-dc86026cb5e8   r:/v2/*
2020-03-05T16:30:23Z [WARNING] [/core/middlewares/sizequota/handler.go:48]: Error occurred when to handle request in size quota handler: unsupported content type for manifest: application/vnd.oci.image.manifest.v1+json
2020/03/05 16:30:23.192 [D] [server.go:2774]  |   72.83.31.122| 500 |   1.991334ms|   match| PUT      /v2/dev/x/manifests/y   r:/v2/*
```

**Comment by ninjadq** [comment]
OCI registry is not supported in version 1.10.1. This feature will be included in harbor 2.0
