### ISSUE TITLE
Make jobservice's sweeper duration configurable

### ISSUE THREAD

**Issue by annkam** [goharbor/harbor#10958]
**Is your feature request related to a problem? Please describe.**
I wanted to check tag retention job logs but found out that they are available only for 1 day as it's hardcoded in jobservice [configuration](https://github.com/goharbor/harbor/blob/v1.10.1/make/photon/prepare/templates/jobservice/config.yml.jinja)
Even in harbor-helm it's set to 14 days which is more applicable.
I understand I can change it manually after running prepare script, but I would like it to be configurable option in harbor.yml

**Describe the solution you'd like**
Add jobservice.sweeper_duration parameter to harbor.yml

**Comment by bitsf** [comment]
@steven-zou @xaleeks have a look about this.

**Comment by xaleeks** [comment]
makes sense to me @ninjadq
