### ISSUE TITLE
failed to ping email server: 504 Unrecognized authentication type.

### ISSUE THREAD

**Issue by aalloosshh** [goharbor/harbor#10964]
In my company where I work, my Manager decide to try Harbor Repository.
Now I faced a problem with email authentication:
Client: Docker Engine: 19.03.6
Server: Docker Engine: 19.03.6
docker-compose version 1.25.4
harbor-offline-installer-v1.10.1.tgz

core.log
Mar  6 13:37:24 172.17.5.1 core[79460]: 2020-03-06T13:37:24Z [ERROR] [/core/api/email.go:113]: failed to ping email server: 504 Unrecognized authentication type.
Mar  6 13:37:24 172.17.5.1 core[79460]: 2020-03-06T13:37:24Z [ERROR] [/common/api/base.go:73]: POST /api/email/ping failed with error: {"code":400,"message":"failed to ping email server"}

In Harbor
Authentication : Datebase

I realized something, when I try to connect with smtp-server without username and password, that every time I delete the password from password-field, I got new one (Why?)

**Comment by ninjadq** [comment]
Are your email configuration correct?
password in the password field is a fake password. This filed only passed to backend when you changed it.

**Comment by aalloosshh** [comment]
yes it is  correct, I found that my email server didn't accept AUTH as PLAIN, and that what Harbor used. since Harbor don't use other Authentication type, i can't use Email service.
Now i get other problem too, i tried to push helm chart to Harbo repo, helm v2,16 exist in my k8s v1.16 and Harbor on other separate VMs in same Networks, and i get authentication error 404 too,
did you have any idea, where should start searching to understand what that mean....
thx

**Comment by ninjadq** [comment]
Currently, email service only supports plain auth.
other question you can open a new issue with your logs
