### ISSUE TITLE
k8s单节点系统重启后harbor十几个小时都还不能正常运行

### ISSUE THREAD

**Issue by pog2g** [goharbor/harbor#10965]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.1
- docker engine version: 19.03.6

**Additional context:**
1.  k8s单节点使用helm安装harbor成功(pvc为使用已经存在的hostpath pvc)；
2.  重启服务器；
3.  harbor再以不能恢复正常(10个小时下来依然报错)，重新安装5次,重启后出问题pod依然是这几个
![image](https://user-images.githubusercontent.com/48884933/76096676-6ee5a900-6001-11ea-8041-ff3d439f4eb8.png)

3. 关键日志如下
```
{"Event":"pgsql: could not open database: dial tcp 10.111.186.238:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-03-06 14:07:22.688146"}
```
4. 或者ping db错误(即使我数据库使用外置的还是会提示该消息)

# 其他问题
* 不明白harbor就这么经不起折腾吗？？？系统重启都扛不住吗？？？
* 使用docker-composer安装重启后部分容器不能启动还有办法解决。而k8s就只能重装了。难不成每次停电我就要重装一次吗？？？？而且重装了有时错误提示还是和上面一样(即重装也会出现不正常的pod一直无法恢复)
* 不管什么服务重启系统后都能恢复正常，但harbor不管是k8s还是docker-compoer安装重启系统都会存在不正常的情况，如果这个不能解决，很难让人相信harbor系统的可靠性和稳定性

**Comment by reasonerjt** [comment]
@pog2g looks like they failed to connect to Database, could you look at the output of each of the pods to double check ?

Did you use helm chart to install Harbor?  Is the DB running?

**Comment by pog2g** [comment]
@pog2g 我试了两种，一个是db外置，一个是db内置，重启后都会那样。我确定是用helm安装的。我就在values.yml里面修改数据库信息的

**Comment by reasonerjt** [comment]
Did you see this error when using internal DB?
```
{"Event":"pgsql: could not open database: dial tcp 10.111.186.238:5432: connect: connection refused","Level":"fatal","Location":"main.go:97","Time":"2020-03-06 14:07:22.688146"}
```


Did you hard code IP in values.yml?
