### ISSUE TITLE
The package name "error" is confusing.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10976]
We have `src/internal/error`, `src/server/error`.
`error` is a type in golang, we should avoid using such name as a package name?

**Comment by catchups** [comment]
Agree. It might be a good idea to change the package name to just "errors" something like that.

**Comment by reasonerjt** [comment]
1. src/..../error ->  src/..../errors
2. Remove src/pkg/scan/errs

**Comment by heww** [comment]
Closed by #11347
