### ISSUE TITLE
[BUG] Generate Infinite logs after a success push from a robot account.

### ISSUE THREAD

**Issue by OrwillT** [goharbor/harbor#10974]
**Expected behavior and actual behavior:**
Generate Infinite logs after a success push from a robot account.

**Steps to reproduce the problem:**
Push radom image to that registry with my robot account.

**Versions:**
- harbor version: v1.10.1-f3e11715
- K3s version : 1.17.3+k3s1

![image](https://user-images.githubusercontent.com/21377465/76160392-f3047180-6164-11ea-92a8-ad1e3912b655.png)

**Comment by OrwillT** [comment]
And also you can't push anything to it after this happend. you will get no error and blobs are been pushed and show, but there is no images shows.

**Comment by reasonerjt** [comment]
@OrwillT do you see same problem when you push using non-robot account?

Could you attach the complete log files as attachment, please do not paste content in the issue.

**Comment by OrwillT** [comment]
> @OrwillT do you see same problem when you push using non-robot account?
> 
> Could you attach the complete log files as attachment, please do not paste content in the issue.

As I said before, this also happend with non-robot user.

Which container should I attach to for the complete log?

**Comment by reasonerjt** [comment]
@OrwillT `core` and `registry`

How did you install Harbor?

**Comment by OrwillT** [comment]
I installed harbor with offical helm chart, values file see [vaule.yaml.txt](https://github.com/goharbor/harbor/files/4323829/vaule.yaml.txt)

And here are logs start with a pipeline:
[registryctl.log](https://github.com/goharbor/harbor/files/4323827/registryctl.log)
[core.log](https://github.com/goharbor/harbor/files/4323823/core.log)
[registry.log](https://github.com/goharbor/harbor/files/4323824/registry.log)

**Comment by OrwillT** [comment]
@reasonerjt Any update for this issue?

**Comment by reasonerjt** [comment]
Hi sorry for the late response.  Seems this is the root cause, in registry.log:

```
time="2020-03-12T11:05:08.949433158Z" level=error msg="retryingsink: error writing events: httpSink{http://registry-harbor-core/service/notifications}: error posting: Post http://registry-harbor-core/service/notifications: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying"
```

When an image is pushed/pulled `registry` sends a notification to `core` and `core` adds the access log record when receiving the notification.

Now, in your case core receives the notification and added the record but registry did not receives the success response, so it keeps trying again and again.

Could you check your network and see why such timeout happens?

**Comment by OrwillT** [comment]
Slove after add flannel to trusted zone.

Thanks for your help.
