### ISSUE TITLE
There should be a conventional way to inject CA to call containers in Harbor

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10977]
As we discussed if we treat Harbor as a whole.  
Would it be more convenient for both user and implementation, that we provide a consistent way for user to set CA, and once it's set all containers will trust it?

If there's no convenient way to do that , we should at least handle this:
https://github.com/goharbor/harbor/issues/10235

**Comment by ninjadq** [comment]
Harbor currently can inject custom ca bundles
