### ISSUE TITLE
"unauthorized: authentication required" after using nginx

### ISSUE THREAD

**Issue by wydream** [goharbor/harbor#1097]
I use nginx to proxy the request, but push the images failed.

```
Login Succeeded
The push refers to a repository [myurl:2000/library/harbor-log]
158f11ffc16f: Pushing [==================================================>] 3.072 kB
0d7242ab30ac: Pushing [==================================================>] 3.072 kB
65ce47a56ad1: Pushing [==================================================>] 3.584 kB
6103217a6963: Pushing [==================================================>] 62.68 MB
dd60b611baaa: Pushing [==================================================>] 127.5 MB/127.5 MB
unauthorized: authentication required
```

in registry.log I found this:
```
Nov 16 05:09:20 172.18.0.1 registry[2939]: time="2016-11-16T10:09:20.293044048Z" level=debug msg="authorizing request" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=ef365e7a-60e9-4644-af82-df5962d55564 http.request.method=GET http.request.remoteaddr="172.18.0.6:55372" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=f16ada54-8a1f-4474-9e9e-bbb48b55ac76 service=registry version=v2.5.0
Nov 16 05:09:20 172.18.0.1 registry[2939]: time="2016-11-16T10:09:20.293149343Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=ef365e7a-60e9-4644-af82-df5962d55564 http.request.method=GET http.request.remoteaddr="172.18.0.6:55372" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=f16ada54-8a1f-4474-9e9e-bbb48b55ac76 service=registry version=v2.5.0
```

all request is http.
is that nginx not transmit the token? or something else.

**Comment by reasonerjt** [comment]
yes probably, 
also check the comment in our nginx.conf template, you may need some modification.

We didn't test the scenario to setup Harbor behind a proxy very much.

**Comment by hainingzhang** [comment]
Please check at the end of the below document about a possible solution to configure an Nginx:

https://github.com/vmware/harbor/blob/dev/docs/installation_guide.md

When setting up Harbor behind an nginx proxy or elastic load balancing, look for the line below, in make/config/nginx/nginx.conf and remove it from the sections if the proxy already has similar settings: location /, location /v2/ and location /service/.

proxy_set_header X-Forwarded-Proto $scheme;

@wydream

**Comment by wydream** [comment]
here is my nginx.conf, have no config of "proxy_set_header"
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    upstream harbor {
        ip_hash;
        server 10.57.18.236;
        server 10.57.18.120;
    }

    server{
        listen 80;
        location / {
            proxy_pass http://harbor;
        }
    }
}
```

**Comment by wydream** [comment]
And is there any other way to maintain HA harbor?

**Comment by wydream** [comment]
I compared logs between the directly connection and proxy connection
in the logs of the successful case(directly),it's
`http.request.method=HEAD`
in the logs of proxy one, it's
`http.request.method=POST `

**Comment by bn0ir** [comment]
Hello,
@wydream may be you want to change 
```auth->token->realm```
file
```config/registry/config.yml```

In my case (external nginx proxy https to http) problem was there.

**Comment by mibsen** [comment]
@bn0ir This fixed my problem. thx.

**Comment by ramalhais-sky** [comment]
It's a shame that even with all the "automation" done on rancher, this is so difficult to setup with SSL offloading/proxying.

This is what i did to work-around it:

VOL=$(docker volume ls | grep project-harbor_etcregistry| sed -e 's/.*\ //g')
VOLDIR=$(docker volume inspect $VOL -f '{{.Mountpoint}}')
sed -i -e 's/realm: http:/realm: https:/g' $VOLDIR/config.yml
CONTAINER=$(docker ps|grep project-harbor-registry | sed -e 's/.*\ r-/r-/g')
docker restart $CONTAINER

**Comment by reasonerjt** [comment]
Closing as this is answered.
