### ISSUE TITLE
API Test Case: Add test steps for scan test case since trivy function involved.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#10990]
Trivy as a default scanner has been installed into harbor, so API test for  scan image should be updated.
Please add test steps after step of scan image by default scanner Trivy, after it, should switch scanner to Clair and scan image again.

It also fixed a duplicate issue #10768.

**Comment by danfengliu** [comment]
For now, scan image returned error due to error bellow, after we have solution for this,  scripting will be continued.

**Error Log:**
Mar 10 19:51:54 172.18.0.1 trivy-adapter[15767]: {“addr”:“:8080",“level”:“warning”,“msg”:“Starting API server without TLS”,“time”:“2020-03-11T02:51:54Z”}
Mar 10 19:53:52 172.18.0.1 trivy-adapter[15767]: {“exit_code”:1,“image_ref”:“core:8080/project-1583895213795/docker@sha256:70b9b6b35c3a9e07cdb9bc1cefc1abcda4571318bbd5c8de012910d786ed106d”,“level”:“error”,“msg”:“Running trivy failed”,“std_err”:“”,“std_out”:“2020-03-11T02:53:51.028Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2020-03-11T02:53:51.029Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2020-03-11T02:53:52.233Z\t\u001b[31mFATAL\u001b[0m\tfailed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 66.170.99.2. (But here’s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 4m33s]\n”,“time”:“2020-03-11T02:53:52Z”}
Mar 10 19:53:52 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan failed”,“time”:“2020-03-11T02:53:52Z”}
Mar 10 19:53:55 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan job failed”,“scan_job_id”:“499f93ceb664b03591c1e880”,“time”:“2020-03-11T02:53:55Z”}
Mar 10 19:55:10 172.18.0.1 trivy-adapter[15767]: {“exit_code”:1,“image_ref”:“core:8080/project-1583895213795/docker@sha256:70b9b6b35c3a9e07cdb9bc1cefc1abcda4571318bbd5c8de012910d786ed106d”,“level”:“error”,“msg”:“Running trivy failed”,“std_err”:“”,“std_out”:“2020-03-11T02:55:08.529Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2020-03-11T02:55:08.530Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2020-03-11T02:55:10.795Z\t\u001b[31mFATAL\u001b[0m\tfailed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 66.170.99.2. (But here’s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 3m14s]\n”,“time”:“2020-03-11T02:55:10Z”}
Mar 10 19:55:10 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan failed”,“time”:“2020-03-11T02:55:10Z”}
Mar 10 19:55:10 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan job failed”,“scan_job_id”:“7811d198b58a2e95217aa388”,“time”:“2020-03-11T02:55:10Z”}
Mar 10 19:56:34 172.18.0.1 trivy-adapter[15767]: {“exit_code”:1,“image_ref”:“core:8080/project-1583895213795/docker@sha256:70b9b6b35c3a9e07cdb9bc1cefc1abcda4571318bbd5c8de012910d786ed106d”,“level”:“error”,“msg”:“Running trivy failed”,“std_err”:“”,“std_out”:“2020-03-11T02:56:32.716Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2020-03-11T02:56:32.717Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2020-03-11T02:56:34.058Z\t\u001b[31mFATAL\u001b[0m\tfailed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 66.170.99.2. (But here’s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 1m52s]\n”,“time”:“2020-03-11T02:56:34Z”}
Mar 10 19:56:34 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan failed”,“time”:“2020-03-11T02:56:34Z”}
Mar 10 19:56:34 172.18.0.1 trivy-adapter[15767]: {“error”:“running trivy wrapper: running trivy: exit status 1: “,”level”:“error”,“msg”:“Scan job failed”,“scan_job_id”:“2d671c3680d2513646926bb3”,“time”:“2020-03-11T02:56:34Z”}

**Comment by renmaosheng** [comment]
Daniel P has submitted a PR to allow users to acquire a token which has larger request per hour, need to do code review to merge it to fix this problem.
