### ISSUE TITLE
The "deleting tag" operation cannot be replicated to other non-harbor registries

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10999]
As "deleting tag" isn't part of registry API, it isn't supported by other non-harbor registries, this means the "deleting tag" operation cannot be replicated to other registries.

Maybe this will be the limitation of replication

**Comment by xaleeks** [comment]
Yep this is confirmed now, it is only supported if the replication target registry is docker Harbor 2.0.  For all other target registries, only the operation of 'adding tag' is replicated on the target, not deleting tag.  

This is a limitation of the target registry, most of the 3rd party registries do not support adding or deleting tags without impacting other tags referenced by the same digest.  Harbor 2.0 can now add or delete tag freely to an artifact as it's treated purely as metadata.
