### ISSUE TITLE
Plan when to support online GC? that is, do not affect the upload image function.

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#11005]
Plan when to support online GC? that is, do not affect the upload image function.

Thanks!

**Comment by ninjadq** [comment]
Probably, this feature will realise with harbor 2.0

**Comment by reasonerjt** [comment]
@Iverson-lena there will be a proposal in `goharbor/community` repo for review, there's some technical details we need clarify so it won't be in 2.0.
