### ISSUE TITLE
Is Harbor compatible with distributed file system (HDFS) as an external storage  ?  

### ISSUE THREAD

**Issue by Pradyumnakashyap** [goharbor/harbor#11012]
A running application has HDFS as storage, I would want to use the same to store my images of my registry on, is there any scope to directly store them on such storage using Harbor  ( Harbor running on Kubernetes) ?  

-HDFS in place of Postgres

Suggestions highly appreciated.

**Comment by reasonerjt** [comment]
Harbor relies on docker distribution for storing images.
AFAIK there's no storage driver for HDFS in docker distribution.

So the answer is no.

**Comment by Pradyumnakashyap** [comment]
Thank you for the quick response
