### ISSUE TITLE
New behaviour for the quota checking in Harbor 2.0

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11020]
We introduce the quota per project feature in harbor 1.9.

In this version when push blob/manifest to harbor, the quota checking will try to sum the quota usage and the resoruces required and then compare the result with the quota limitation.

The pushing is rejected when the result exceeded the limitation. The quota usage is updated to the result of the sum and the pushing is allowed when the result not exceeded. When the pushing is failed in the next stage, the quota usage will subtract with the resources required at the beginning.

Before to compute the resources required when push blob/manifest, the quota checking will require a lock by the digest of the blob/manifest. When push two blobs their digests are same, the first blob which required the key success will continue the pushing request and the second blob will block until the first pushing request was finished to release the lock.

When there is only one count resource left for the project, this behaviour will make the two pushing of same manifest both success.

In harbor 2.0, we change the implement of the quota checking to sum the quota usage and the resources required and then compare the result with the quota limitation, when the result not exceeded the limitation, then reserve the resources, refreshes quota usage after the request successfully, unreserve the resources at finally.

When there is only one count resource left for the project, this behaviour will make the two pushing of same manifest first one success and second one failed. Then push again both success.

**Comment by heww** [comment]
The new behaviour will these issues #9781 #10346

**Comment by renmaosheng** [comment]
it seems not 2.0 is more accurate than 1.9.

**Comment by reasonerjt** [comment]
I think the implementation in 2.0 is better.

**Comment by xaleeks** [comment]
I don't see an issue or request here, seems its a placeholder for something we wanted to discuss at some point.  closing
