### ISSUE TITLE
No feedback when testing incorrect LDAP connection settings

### ISSUE THREAD

**Issue by techgnosis** [goharbor/harbor#11034]
**Expected behavior and actual behavior:**
I found this bug while watching a customer at the keyboard so I don't have screenshots.
We were following these steps
https://github.com/goharbor/harbor/blob/master/docs/1.10/administration/configure-authentication/ldap-auth.md

When you are setting up Harbor LDAP integration, there is a button that says "Test LDAP Server"

**Expected Behavior**: If the settings are wrong, the user is notified the settings are wrong. If the settings are correct, the user is notified that the settings are correct.

**Actual Behavior**: If the settings are wrong, nothing happens. If the settings are correct, the user is notified that the settings are correct.

This means the customer has no idea if they are doing it right until they do it right. With no feedback when the settings are incorrect, the customer might think the settings are correct and waste time trying to use the LDAP integration that is in fact incorrect.

**Steps to reproduce the problem:**
Go to Administration -> Configuration -> Authentication
Select LDAP
Enter in your LDAP connection settings into the fields
Push "Test LDAP Server"

**Versions:**
- harbor version: 1.10.1
- docker engine version: unrelated
- docker-compose version: unrelated

**Additional context:**
This is purely a UX bug. We eventually got the LDAP settings correct which caused us to be informed by the UI that we got the settings correct. If we never got them correct we would have always been wondering if the settings were correct or not.

**Comment by kkothapelly** [comment]
James,
as discussed, we have updated the below ldap configuration settings in Harbor and then we are able to add the groups and login to Harbor.

Updated fields:
LDAP Search DN : Complete DN of the service account
LDAP Filter : objectclass=user
LDAP UID: sAMAccountName

LDAP Group Filter: objectclass=group
LDAP Group GID: sAMAccountName


Daojun: you can close this issue.

**Comment by xaleeks** [comment]
@zhoumeina This is a pretty big issue, we need a way to reflect that connection test failed.

**Comment by stonezdj** [comment]
<img width="1280" alt="Screen Shot 2020-03-27 at 10 30 26 AM" src="https://user-images.githubusercontent.com/2696760/77715331-49532a80-7016-11ea-8842-6c8a0fe84d79.png">
from the screenshot, there is 500 error returned, but the UI doesn't prompt the error message. or fail the connection testing.

**Comment by jwangyangls** [comment]
I will fix it before harbor2.0
