### ISSUE TITLE
Understand replication override option

### ISSUE THREAD

**Issue by ninjaslothx** [goharbor/harbor#11035]
Hey,
I'm just trying to understand the override option with replications. 
"Override checkbox to force replicated resources to replace resources at the destination with the same name"

If for example we are only replicating the tag "latest" and we disable this option, does this mean if there is an update to "latest" it will not be updated/overridden preventing updates?

Like wise if we have a '**' replication rule that might contain 300+ tags, would the override option cause every single one of these to be pulled fresh every time it runs?

Id just like to make sure I understand this setting so I am not replicating unnecessarily every time a replication job runs.

**Comment by catchups** [comment]
If the override option is not checked, replication will not be performed if a tag with the same name exists.

**Comment by ninjaslothx** [comment]
Thanks for the clarification :)
