### ISSUE TITLE
OIDC configuration file

### ISSUE THREAD

**Issue by Pulz** [goharbor/harbor#11036]
I connected goHarbor with Keycloak as OIDC provider on a K8s cluster through the GUI but would like to save the authentication settings and credentials in a possible config file. However I have been unable to locate where the settings are being saved. I tried monitoring the logs while changing the settings but nothing came up.

My pods: 

```
NAME                                            READY   STATUS    RESTARTS   AGE
testing-harbor-chartmuseum-66869699d9-2rshq     1/1     Running   0          96m
testing-harbor-clair-7f7b68456b-98vgz           1/1     Running   1          96m
testing-harbor-core-6684fd4d9f-psqps            1/1     Running   0          96m
testing-harbor-database-0                       1/1     Running   0          96m
testing-harbor-jobservice-54df8d9687-zhq6m      1/1     Running   2          96m
testing-harbor-notary-server-849768d4c4-llpvh   1/1     Running   2          96m
testing-harbor-notary-signer-78f69fb7bd-746rj   1/1     Running   2          96m
testing-harbor-portal-67c8c6bd5d-9jq2f          1/1     Running   0          96m
testing-harbor-redis-0                          1/1     Running   0          96m
testing-harbor-registry-59574bb775-4fnrj        2/2     Running   0          96m
```

Where do I find them?

**Comment by stonezdj** [comment]
The OIDC settings can be changed with the configuration in Harbor web console, they are stored in database.

**Comment by Pulz** [comment]
Would you mind telling me in which table they are being saved? I looked through the list (76 tables and sequences) but had no luck.

**Comment by xaleeks** [comment]
It seem this has been resolved, so closing this.  Let us know if you run into more issues @Pulz
