### ISSUE TITLE
There should be a way for user to setup proxy for Trivy.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11032]
Trivy pulls the data from internet. 
We need to allow user to set proxy for trivy-adapter.  It can reuse the existing attributes in `harbor.yml` and in Harbor helm chart.

**Comment by knqyf263** [comment]
You can use the environment variable `HTTP_PROXY`.

**Comment by zapalotta** [comment]
This may work with helm now, but with install.sh/docker-compose it is still broken. 

```
[root@myhost harbor]# grep -i proxy common/config/trivy-adapter/env
HTTP_PROXY=
HTTPS_PROXY=
NO_PROXY=

```
Adding the values manually of course won't help either as they get overwritten by prepare.

**Comment by danielpacak** [comment]
@zapalotta Are you saying that the proxy set in harbor.yaml is ignored and not added to the common/config/trivy-adapter/env? https://github.com/goharbor/harbor/blob/master/make/harbor.yml.tmpl#L189

**Comment by zapalotta** [comment]
@danielpacak Exactly. 
The proxy settings are correct in harbor.yml. They were used with clair in the former 2.1 (which is gone in 2.2.0) and they are used by harbor itself for syncing. 

This is the result after running ./install.sh --with-trivy --with-chartmuseum

```
[root@myhost harbor]# grep -r PROXY
common/config/core/env:PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE=docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay
common/config/core/env:HTTP_PROXY=http://obfuscated:3128
common/config/core/env:HTTPS_PROXY=http://obfuscated:3128
common/config/core/env:NO_PROXY=exporter,.local,core,notary-server,127.0.0.1,log,chartmuseum,trivy-adapter,.internal,postgresql,localhost,jobservice,db,portal,.mylocaldomain,redis,nginx,registryctl,registry,notary-signer
common/config/jobservice/env:HTTP_PROXY=http://obfuscated:3128
common/config/jobservice/env:HTTPS_PROXY=http://obfuscated:3128
common/config/jobservice/env:NO_PROXY=exporter,.local,core,notary-server,127.0.0.1,log,chartmuseum,trivy-adapter,.internal,postgresql,localhost,jobservice,db,portal,.mylocaldomain,redis,nginx,registryctl,registry,notary-signer
common/config/trivy-adapter/env:HTTP_PROXY=
common/config/trivy-adapter/env:HTTPS_PROXY=
common/config/trivy-adapter/env:NO_PROXY=
```

**Comment by danielpacak** [comment]
Got it. It looks like regression. I'll try to investigate and see how we can fix that.
