### ISSUE TITLE
Add icon for OPA bundle

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11042]
For the response of artifact:
```
[{
	"id": 1,
	"type": "OPENPOLICYAGENT",
	"media_type": "application/vnd.cncf.openpolicyagent.config.v1+json",
	"manifest_media_type": "application/vnd.oci.image.manifest.v1+json",
....
```

Note type  `"type": "OPENPOLICYAGENT"`, please use the logo of opa as icon:
https://openpolicyagent.org/

**Comment by xaleeks** [comment]
Checking with CNCF on legality of using OPA's logo as found on their repository

**Comment by xaleeks** [comment]
Checked w/ cncf that it's ok to use @reasonerjt
