### ISSUE TITLE
harbor 2.0 add replication fail

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11049]
harbor.v2.0.0-build.3064

![image](https://user-images.githubusercontent.com/188115/76513023-9b317780-6490-11ea-8457-01b782aed721.png)
![image](https://user-images.githubusercontent.com/188115/76513056-a97f9380-6490-11ea-998d-c5134ba531e3.png)

/api/v2.0/registries/3/info

**Comment by ywk253100** [comment]
The version of source Harbor registry isn't 2.0?

**Comment by bitsf** [comment]
source is 1.8.x

**Comment by ywk253100** [comment]
The replication isn't supported anymore for different versions of Harbor

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/11302
