### ISSUE TITLE
harbor机房迁移，需要把老harbor下大数据迁移到新集群，发现操作系统不支持255个字符的名称

### ISSUE THREAD

**Issue by swq499809608** [goharbor/harbor#11041]
1.  现有机房的即将退出历史舞台，新机房部署了harbor，老的版本是1.2.2，新的版本1.8.5

1. 老集群harbor 存储方式采用 ceph 存储，协议是swift 协议 进行数据存储

**配置如下**
# The default data volume
data_volume: /data

 
storage_service:
  ca_bundle:
  swift:
    tenant: harbor
    username: harbor:swift
    password: Al21uKOJctw9xxx
    authurl: http://xxx.in.xxx.com.cn/auth/v1
    container: harbor
    rootdirectory: /swift/object/name/prefix
  cache:
    layerinfo: inmemory
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disabled: false

1. 通过S3CMD SYNC 命令进行下载
                       DIR   s3://harbor/docker/ 已下载
                       DIR   s3://harbor/files/ 已下载
                       DIR   s3://harbor/segments/ 下载异常

1.  S3CMD SYNC  同步本地报错
 s3cmd  --acl-public sync 

s3://harbor/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f612d6f6e652f63656e746f732f5f75706c6f6164732f30613339646630392d386365622d343332302d623361662d6633613238356537373561312f6461746150a63a47a6e28a038f5245e385cd150d9dde54b095bd7fcf3ad9160a84f9e6b7da39a3ee5e6b4b0d3255bfef95601890afd80709/ /ceph-bak/harbor/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f612d6f6e652f63656e746f732f5f75706c6f6164732f30613339646630392d386365622d343332302d623361662d6633613238356537373561312f6461746150a63a47a6e28a038f5245e385cd150d9dde54b095bd7fcf3ad9160a84f9e6b7da39a3ee5e6b4b0d3255bfef95601890afd80709/

ERROR: [Errno 36] File name too long: '/ceph-bak/harbor/segments/2f6/46f636b65722f72656769737472792f76322f7265706f7369746f726965732f612d6f6e652f63656e746f732f5f75706c6f6164732f30613339646630392d386365622d343332302d623361662d6633613238356537373561312f6461746150a63a47a6e28a038f5245e385cd150d9dde54b095bd7fcf3ad9160a84f9e6b7da39a3ee5e6b4b0d3255bfef95601890afd80709/'

**Comment by reasonerjt** [comment]
So this is an env issue, I don't think there's anything we can do in Harbor...

**Comment by swq499809608** [comment]
Is there a good solution?

**Comment by reasonerjt** [comment]
I haven't tried swift, I suggest you check the code to understand why the file name is so long, if you cannot change it.

Could you check is the swift or OS throwing this error

**Comment by swq499809608** [comment]
Thank you very much， I have found the method, can be downloaded, can also be uploaded operation, the method is very simple, the file downloaded to the local intercept 250 characters, the script to download into the configuration file, upload the destination address and source address can be exchanged
