### ISSUE TITLE
harbor1.8.0 or harbor1.10.1 replication not working

### ISSUE THREAD

**Issue by dingchenghong** [goharbor/harbor#11057]
When the trigger is scheduled，the cron string "0 15 5 * * *" not working，but "0 0/15 * * *" working，so how to designate it in hour.
Has anyone ever been in this situation?

**Comment by reasonerjt** [comment]
When you say the cron is not working?  what do you expect and what happened?

Please also let us know the version of Harbor

**Comment by catchups** [comment]
At what point did you set up cron?

**Comment by dingchenghong** [comment]
@reasonerjt @catchups 
I want to trigger it at some point in time
example:
trigger it at 5 o'clock very day, so cron string is "0 0 5 * * *" but it not working
![33](https://user-images.githubusercontent.com/4938801/76599225-7fd17580-653f-11ea-8a3c-e6340dab44f7.png)
I tried harbor1.8.0 and harbor1.10.0
