### ISSUE TITLE
Upload chart with helm command, Error 404，  helm version 1.10

### ISSUE THREAD

**Issue by shaojielinux** [goharbor/harbor#11056]
pushing chart 'test' to repository 'https://harbor.test.dev/chartrepo/library' ...
Error: fail to push chart 'test' to repository 'https://harbor.test.dev/chartrepo/library': repository returns error Not Found: <!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>
<style>

**Comment by reasonerjt** [comment]
Please provide more details,
Harbor's version?  How it's installed?  What commands did you use?

**Comment by shaojielinux** [comment]
Version v1.10.1 ， 
Use command for helm push test ./test
