### ISSUE TITLE
harbor 1.8.5版本镜像复制功能筛选写法问题

### ISSUE THREAD

**Issue by lileitongxue** [goharbor/harbor#11054]
1.8.5版本的两个harbor之间，使用镜像复制功能push模式，填写过滤源仓库过滤功能时候，按照官方文档的写法library/** 无法复制镜像成功，改为library/* 成功。
官方说明文档写法如下：
![image](https://user-images.githubusercontent.com/22284655/76542846-92589a00-64c0-11ea-9559-64705cc5130b.png)

**Comment by reasonerjt** [comment]
请问不可复制成功是出错还是什么，能提供job和core的log吗？
