### ISSUE TITLE
Got `csrf token invalid` issue in http mode

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11074]
1. Install harbor (the latest build from master branch) in http mode.
2. Login in portal.
3. Got `{“errors”:[{“code”:“FORBIDDEN”,“message”:“CSRF token invalid”}]}` .

**Comment by reasonerjt** [comment]
The csrf cookie by default turns on `secure` flag.  
I'll make it adapt to configuration.

**Comment by reasonerjt** [comment]
@jwangyangls with the change in PR I can login via HTTP on safari but Chrome still fails, it seems the cookie is not set successfully, I have set the `SameSite=strict`. 

Could you also investigate if there's some magic on the browser side?

**Comment by h4wkmoon** [comment]
Hi, 
Sorry to bother, 
does this affect fresh helm installs with tls-enabled ingress ?

**Comment by aperullo** [comment]
@h4wkmoon it would seem to, I'm experiencing the same issue. I'm not sure if its also whats causing my nodes to be unable to pull images. My nodes get a `no basic auth credentials` error, but I can `docker pull` manually on them and it works.

**Comment by shaobo322** [comment]
I have the same problem, {“errors”:[{“code”:“FORBIDDEN”,“message”:“CSRF token invalid”}]}, with version v2.0.0

**Comment by Purushotham233** [comment]
Ran into the same issue on v2.0.0. In my case http:// prefix to the externalUrl was missing. After adding scheme it started working.

**Comment by mattjamese** [comment]
v2.1.0m if your external url is core.harbor.domain in values.yml, run below command and wait for few mins. 

helm upgrade local-harbor harbor/harbor --set externalURL=http://core.harbor.domain

**Comment by hjkl950217** [comment]
> v2.1.0m if your external url is core.harbor.domain in values.yml, run below command and wait for few mins.
> 
> helm upgrade local-harbor harbor/harbor --set externalURL=http://core.harbor.domain

I encountered a similar problem. I solved it by setting 'external_url: http://xxx' in 'harbor.yml'. Setting only the IP address was invalid. Thanks
