### ISSUE TITLE
ux of project quota is not consistent with other configuration. 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11079]
changing the project quota user experience is hidden in vertical '...' , but other operation all have the dropdown actions. we should make them be a consistent experience.

**Comment by AllForNothing** [comment]
@xaleeks Replace  '...'  with dropdown actions?

**Comment by xaleeks** [comment]
<img width="1306" alt="Screen Shot 2020-03-18 at 12 38 39 AM" src="https://user-images.githubusercontent.com/51319901/76926081-d7f6d780-68b1-11ea-8da3-34588201d28f.png">

**Comment by xaleeks** [comment]
This is indeed the only place where it uses '...' and the only action is 'edit'.  please change this to and 'edit' button at the top to be consistent with all the other panels @AllForNothing
