### ISSUE TITLE
Cannot change tag retention schedule - v1.10.1

### ISSUE THREAD

**Issue by rob8714** [goharbor/harbor#11083]
Whenever I try to update the schedule for tag retention rules, I get an internal server error. The tag retention rules and schedule were set for the first time while on v1.10.1

Issue looks similar to what was reported in #7868

Below are the logs for when the error happens:

```
==> jobservice.log <==

Mar 15 07:39:13 172.23.0.1 jobservice[75447]: 2020-03-15T07:39:13Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/680d1e1161c9bc0449a766eb' error: 500 {"code":10006,"message":"stop job failed with error","details":"mismatch job status for stopping job: 680d1e1161c9bc0449a766eb, job status Error is behind Running"}


==> core.log <==

Mar 15 07:39:13 172.23.0.1 core[75447]: 2020-03-15T07:39:13Z [ERROR] [/common/api/base.go:233]: status behind error

Mar 15 07:39:13 172.23.0.1 core[75447]: 2020-03-15T07:39:13Z [ERROR] [/common/api/base.go:73]: PUT /api/retentions/1 failed with error: {"code":500,"message":"Internal Server Error"}

Mar 15 07:39:13 172.23.0.1 core[75447]: 2020/03/15 07:39:13.460 #033[1;44m[D]#033[0m [server.go:2774]  |  172.16.114.72|#033[97;41m 500 #033[0m|   5.952569ms|   match|#033[97;43m PUT     #033[0m /api/retentions/1   r:/api/retentions/:id
```

**Comment by guillaumelfv** [comment]
FYI got the same error in 1.10.1 when switching from daily to hourly. It failed with Internal System Error.

**Comment by cmur2** [comment]
I'm also getting this error in 1.10.1 when trying to modify or delete a replication.

**Comment by rob8714** [comment]
is there some workaround for this issue please?

**Comment by sasskinn12** [comment]
Same issue here with v1.10.1 :(

**Comment by titou10titou10** [comment]
Same issue here... Can't find more logs than @rob8714 set in this ticket

**Comment by sasskinn12** [comment]
Is it possible to fix that issue in next release?

**Comment by xaleeks** [comment]
Is this fix in v2.0 as well? and cherry picked to 1.10? That's a lot of +1s.  Is this for any switching btw hourly, daily, weekly, and custom cronjob?  @steven-zou @wy65701436

**Comment by rob8714** [comment]
I was having this issue for any switching.
I noticed that the same error in jobservice.log has been reported recently in #11894

**Comment by steven-zou** [comment]
We'll try to fix it in the upcoming patch release.

**Comment by steven-zou** [comment]
@bitsf 

For tag retention, we can refer to the similar fix solution with replication.

**Comment by steven-zou** [comment]
As a workaround, you may need to connect to the database and then delete the item by `delete from admin_job where job_uuid='680d1e1161c9bc0449a766eb';`. After that, you can reset the schedule.

**Comment by bitsf** [comment]
@steven-zou will do some enhancement in jobservice framework
