### ISSUE TITLE
Enable TLS for Trivy scanner/adapter

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11087]
Enable with the unified TLS solution we're working on

**Comment by danielpacak** [comment]
Currently the adapter service can be configured to enable TLS by providing public/private keys and setting the port with the following environment variables:

- SCANNER_API_SERVER_ADDR
- SCANNER_API_SERVER_TLS_CERTIFICATE
- SCANNER_API_SERVER_TLS_KEY

@ninjadq Do we need to provide a way to configure custom certificate authorities as well?

**Comment by ninjadq** [comment]
@danielpacak I enabled TLS on the trivy-adapter server by set those variables.

thx, I think currently no need to provide trust CA

**Comment by ninjadq** [comment]
done in #10998
