### ISSUE TITLE
Add more details of scanning results for OCI index in the top index level 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11082]
could we add more details info to explain the percentage of scanning results in the index detailed page for OCI index?

**Comment by renmaosheng** [comment]
![image](https://user-images.githubusercontent.com/14900967/76697816-e210ae80-66d6-11ea-931b-c6b40975fb85.png)

**Comment by renmaosheng** [comment]
![image](https://user-images.githubusercontent.com/14900967/76697832-066c8b00-66d7-11ea-889b-4f500d0c0031.png)

**Comment by xaleeks** [comment]
I would add this in parentheses underneath the last line showing percentage. 'scan completed percentage is calculated as # of successfully scanned images / total number of images referenced within the image index not including the index file itself'  @AllForNothing
