### ISSUE TITLE
Replication process is not working with Active-Active Harbor

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#11093]
Hi Team,

I am trying to replicate between to HA harbor instance.
The replication process failed in the first attempt but passed in the second attempt.

In the jobservice.log, i could see the below error
50Z [ERROR] [/replication/transfer/image/transfer.go:166]: failed to check the existence of the manifest of image image:name on the destination registry: http error: code 401, message

Could you please let me know if it is related to the replication process.

Thanks

**Comment by reasonerjt** [comment]
@AyushCloud 

Seems to me it may be the reason the first attempt failed, but more context will be helpful.

Did you remove some information from the log message deliberately? like image name and tag or the hostname of the registry?

**Comment by AyushCloud** [comment]
Yes, i remove the image and tag name from the message.

**Comment by AyushCloud** [comment]
In the registry.log i could see the below error as well.
Mar 17 06:11:45 IP registry[2467]: time="2020-03-17T06:11:45.253451701Z" level=error msg="response completed with error" auth.user.name=harbor-jobservice err.code="manifest unknown" err.detail="unknown tag=latest" err.message="manifest unknown" go.version=go1.12.12 http.request.host="core:8080" http.request.id=d8acb8eb-4333-4d37-819a-755c189bd3fb http.request.method=HEAD http.request.remoteaddr=172.23.0.8 http.request.uri="/v2/test2/ubuntu/manifests/latest" http.request.useragent=harbor-replication-service http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.974558ms http.response.status=404 http.response.written=96 vars.name="test2/ubuntu" vars.reference=latest

The replication process failed in the first attempt but still able to replicate 4 images and successful in the second attempt replicating all the images.

**Comment by AyushCloud** [comment]
Service has 2 Active-Active Scalable LB, 2 Active-Active Harbor, 1 Active PostgreSQL and 1 Active Redis VM.
The jobservice.log shows the below
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:60]: client for source registry [type: harbor, URL: <URL>, insecure: false] created 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:60]: client for destination registry [type: harbor, URL: http://core:8080, insecure: true] created 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:81]: copying test2/httpd:[latest](source registry) to test2/httpd:[latest](destination registry)... 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:142]: copying test2/httpd:latest(source registry) to test2/httpd:latest(destination registry)... 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:160]: pulling the manifest of image test2/httpd:latest ... 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:160]: the manifest of image test2/httpd:latest pulled 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:142]: the image test2/httpd:latest already exists on the destination registry, skip 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/replication/transfer/image/transfer.go:81]: copy test2/httpd:[latest](source registry) to test2/httpd:[latest](destination registry) completed 
Mar 17 06:12:01 IP jobservice[2467]: 2020-03-17T06:12:01Z [INFO] [/jobservice/runner/redis.go:61]: |^_^| Job 'REPLICATION:27a45f821f7bd6a7bfb897f8' exit with success 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"REPLICATION","id":"1ff1cbfe3a8d2211d5eb6b05","t":1584425551,"args":null,"fails":1,"err":"http error: code 401, message ","failed_at":1584425505} 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/jobservice/runner/redis.go:118]: |*_*| Retrying job REPLICATION:1ff1cbfe3a8d2211d5eb6b05, revision: 1584425551 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://core:8080/api/internal/configurations 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:60]: client for source registry [type: harbor, URL: <URL>, insecure: false] created 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:60]: client for destination registry [type: harbor, URL: http://core:8080, insecure: true] created 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:81]: copying test2/consul:[latest](source registry) to test2/consul:[latest](destination registry)... 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:142]: copying test2/consul:latest(source registry) to test2/consul:latest(destination registry)... 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:160]: pulling the manifest of image test2/consul:latest ... 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:160]: the manifest of image test2/consul:latest pulled 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:142]: the image test2/consul:latest already exists on the destination registry, skip 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/replication/transfer/image/transfer.go:81]: copy test2/consul:[latest](source registry) to test2/consul:[latest](destination registry) completed 
Mar 17 06:12:31 IP jobservice[2467]: 2020-03-17T06:12:31Z [INFO] [/jobservice/runner/redis.go:61]: |^_^| Job 'REPLICATION:1ff1cbfe3a8d2211d5eb6b05' exit with success 
Mar 17 06:15:03 IP jobservice[2467]: 2020-03-17T06:15:03Z [INFO] [/jobservice/logger/sweeper_controller.go:97]: 108 outdated log entries are sweepped by sweeper *sweeper.FileSweeper 

It shows that it exit with success.

**Comment by AyushCloud** [comment]
The issue us that the two Active Active Harbor VM have the jobservoce container, so when i stopped the container on one VM then it is working fine. 
How to handle this scenario as i want the replication job to be handled by one one VM?

**Comment by AyushCloud** [comment]
Could you please help me with the issue?

**Comment by steven-zou** [comment]
@AyushCloud 

As Active-Active, do you mean you configure bidirectional replication policies? And those two harbors are having separate storage and database?

`The issue us that the two Active Active Harbor VM have the jobservoce container, so when i stopped the container on one VM then it is working fine.`
