### ISSUE TITLE
api /chartrepo/{repo}/charts/{name}/{version} error

### ISSUE THREAD

**Issue by weihai4099** [goharbor/harbor#11092]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

the api return not found and code 404.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.x] & [1.10..x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

----------------------
when I upload a chart file to library(default) chat repo,  call api is success . 
After 20 minutes . call api will return 404 not found.
And api `/chartrepo/{repo}/charts/{name}`  is ok.
![image](https://user-images.githubusercontent.com/15811933/76738414-8c570780-67a5-11ea-8f26-9c834459dc15.png)
![image](https://user-images.githubusercontent.com/15811933/76738444-97aa3300-67a5-11ea-8fd3-ad9a68176084.png)

But , create a new project named helm-repo. and upload chart file too, It's been okay for the past two days。

**Comment by reasonerjt** [comment]
What version are you using and what API was returning 404?

**Comment by weihai4099** [comment]
1.9 and 1.10.1


/api/chartrepo/library/charts/nginx/5.1.5   {"code":404,"message":"not found"}
/api/chartrepo/helm-repo/charts/nginx/5.1.5   is ok 

`two helm repo` and  `same chart file`.
