### ISSUE TITLE
Harbor added warehouse, test connection failed.

### ISSUE THREAD

**Issue by kangning1** [goharbor/harbor#11101]
hi:
Test connection failed while adding warehouse. See the screenshot for details. The log is as follows.

![image](https://user-images.githubusercontent.com/26712312/76815561-ee148180-6838-11ea-9ed3-785f689971c1.png)

version: 1.8.0
External network address：10.254.198.77
Intranet address： 10.24.63.9

core.log:
Mar 17 10:09:15 172.18.0.1 core[58706]: 2020-03-17T02:09:15Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://10.254.198.77: Head http://10.254.198.77/v2/: Get http://10.24.63.9/service/token?service=harbor-registry: dial tcp 10.24.63.9:80: getsockopt: connection timed out
Mar 17 10:09:15 172.18.0.1 core[58706]: 2020-03-17T02:09:15Z [ERROR] [/common/api/base.go:69]: POST /api/registries/ping failed with error: {"code":400,"message":""}

**Comment by catchups** [comment]
Check your firewall for port 80 of 10.24.63.9.

**Comment by reasonerjt** [comment]
Looks like misconfiguration.

how do you setup `10.254.198.77`  why it points to `10.24.63.9` for auth token?

**Comment by kangning1** [comment]
10.254.198.77 and 10.24.63.9 are the same host, 10.254.198.77 is the external access address of the host, and 10.24.63.9 is the internal LAN address。
Why does harbor return internal address when adding warehouse? Where is the value obtained?

**Comment by kangning1** [comment]
10.254.198.77 is the external access address of the host, and 10.24.63.9 is the internal LAN address。
Port 80 is on, and the source host can only communicate with the target harbor through an external address.

**Comment by catchups** [comment]
Check the connetion by typing "telnet 10.24.63.9 80" in container

**Comment by kangning1** [comment]
The network in the container cannot be connected. You must use an external network address. The address returned by harbor is the intranet address. Is this the configuration of the target harbor that needs to be modified?

**Comment by reasonerjt** [comment]
`Why does harbor return internal address when adding warehouse? Where is the value obtained?` 
It's in `config.yml` of docker registry.  It's for docker cli to fetch token so it has to be accessible from outside.

The value is populated from harbor.yml, for details see the prepare script.

So you setup 2 Harbors on one host and replicate?

**Comment by kangning1** [comment]
The synchronization strategy is implemented on two machines.

**Comment by kangning1** [comment]
The domain name is configured in the configuration file.
harbor.yml:hostname: harbor.ecpaas2.com

**Comment by reasonerjt** [comment]
I assume you are using docker-compose to install "10.254.198.77"?

**Comment by kangning1** [comment]
Yes, it was installed using docker compose.

**Comment by reasonerjt** [comment]
@kangning1 I believe there has to be some misconfiguration in your installation.  if you set the hostname in `harbor.yml` the hostname should be propagated to config.yml of registry.


Could you show me the config.yml of registry on 10.254.198.77?
you can find it in 
`$harbor_base/common/config/registry`

**Comment by kangning1** [comment]
Thank you very much. You can connect by changing the IP in config.yml to domain name.
