### ISSUE TITLE
Wrong redirect if deployed behind external proxy

### ISSUE THREAD

**Issue by lz006** [goharbor/harbor#11100]
If harbor is deployed behind external proxy, setting **externalURL** isn't enough. 

When docker establishes a connection to harbor it first gets a http 301. But **location** header of this response wrongly contains address defined in **ingress.hosts.core**, which is typically not accessible in such a reverse proxy scenario.

We couldn't find any flag that controls this behavior, so we had to fix this at reverse proxy site by using following haproxy config:

http-response replace-header Location http(s?):\\/\\/(.\*?)\\/(.\*) <EXTERNAL_URL>/\\3

It might help someone out.

We experienced this problem using 

**harbor-helm**
**version v1.3**

**Comment by reasonerjt** [comment]
Could you open an issue in goharbor/harbor-helm?

**Comment by reasonerjt** [comment]
@lz006 I think this is the right thing to do, nothing should be fixed on the chart

**Comment by lz006** [comment]
@reasonerjt As your suggestion I opened an issue on the chart. But I guess problem is caused by harbor core source actually. So chart guys might won't be able to fix this.

https://github.com/goharbor/harbor-helm/issues/536

**Comment by reasonerjt** [comment]
We also maintain the helm chart
