### ISSUE TITLE
change repo description via API - 422 error: Unprocessable Entity if session cookie present

### ISSUE THREAD

**Issue by christian-korneck** [goharbor/harbor#11115]
**Expected behavior and actual behavior:**
On demo.goharbor.io I'm trying to change the description of a private repo. My user has admin privileges on that repo. I'm running:

```
# PUT https://demo.goharbor.io/api/repositories/myproject/myrepo
curl --location --request PUT 'https://demo.goharbor.io/api/repositories/myproject/myrepo' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46cGFzc3dvcmQ=' \
--data-raw '{
	"description": "some string"
}'
```

- Expected result: HTTP success response code (2xx)   
- Actual result: HTTP 422 error: Unprocessable Entity

Just to say: I can access other endpoints fine, such as `GET https://demo.goharbor.io/api/repositories/myproject/myrepo/tags`

**Versions:**
I'm running this on the `demo.goharbor.io` demo system as of 18-Mar-2020.
- harbor version: v1.10.1-f3e11715

**Comment by catchups** [comment]
I think it would be more helpful to attach the log.

**Comment by christian-korneck** [comment]
I think I figured it out (at least at the surface). It's a session cookie issue. If you accept cookies you're receiving a `sid` cookie with your first api request against the harbor server. After that it seems GET calls still work but changing calls (I tried a couple of PUT and DELETE calls) fail with HTTP 422 error. If your api client ignores cookies everything works fine. (Side note: You also receive a `_csrf` cookie, but it doesn't seem related to this problem).

I ran into this because I was using [postman](https://www.postman.com) as api client which by default accepts cookies. Just for the docs / if anyone ends up here with the same problem: It seems you can't disable cookies in postman but you can delete them directly after a request by adding a `Tests` postscript to your request:

```
// remove cookies
const jar = pm.cookies.jar();
jar.clear(pm.request.url, function (error) {
  // error - <Error>
});
```

I'm not sure if this is intended behaviour or a bug - that's why I leave this issue open. (Ignoring cookies solves it for me, feel free to close it).

**Comment by reasonerjt** [comment]
The fact is a bit complicated.
Because your request carries an `sid` so the handler suspects it's CSRF attack so it requires for `xsrf` token.

In your case you don't have the csrf token so you see the `422`

Glad the problem's fixed.  I'm closing this issue.

**Comment by christian-korneck** [comment]
@catchups @reasonerjt thank you!
