### ISSUE TITLE
harbor-online-installer-v1.10.1.tgz.asc does not exist

### ISSUE THREAD

**Issue by GarageDeveloper** [goharbor/harbor#11133]
Hi,
the gpg signature for the online installer tarball does not exist although it is listed on the release page. The offline one seems to be ok.
Release page:
https://github.com/goharbor/harbor/releases/tag/v1.10.1

harbor-online-installer-v1.10.1.tgz.asc is 232 bytes long and contains this:
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: harbor-releases/release-1.10.0/harbor-online-installer-v1.10.1.tgz.asc</Details></Error>

Thanks,
Raph

**Comment by bitsf** [comment]
The file like harbor-online-installer-v1.10.2-build.3474.tgz.asc is actually uploaded to cloud, but harbor-online-installer-v1.10.2.tgz.asc is not exists. This should be a manual mistake when do copy at release time.
@wy65701436 will enhance his release script to help fix this

**Comment by wy65701436** [comment]
@GarageDeveloper the signature has already been updated, please help to check. And I have double confirmed the release pipeline, thanks for pointing it. 

I'll close it and feel free to reopen if you still encoutner it.
