### ISSUE TITLE
Harbor Upgrade fails - finding cfg

### ISSUE THREAD

**Issue by senthil13** [goharbor/harbor#11132]
Hi - We are trying to upgrade from harbor version v1.8.1 to v1.10.1, its a offline install so we download file and untar the file. when we try to run the upgrade migrator we are getting below error. Need assistance on this please. 

```
docker image load -i harbor/harbor.v1.10.1.tar.gz

docker run -it --rm -v ${harbor_yml}:/apps/harbor/harbor.yml goharbor/harbor-migrator:v1.10.1 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
Skip cfg up as no harbor.cfg in the path.
```

**Comment by reasonerjt** [comment]
@senthil13 you need to mount your harbor.cfg into the container instead of copy and paste the sample command in doc

**Comment by senthil13** [comment]
I don't have harbor.cfg as it v1.8.1 and only has harbor.yml. So i mounted that as `${harbor_yml}:/apps/harbor/harbor.yml`, not sure it will show any success message or failure. not sure its upgraded or not. It showed me the message that `Skip cfg up as no harbor.cfg in the path.`

**Comment by rob8714** [comment]
If it helps, had submitted this clarification to the upgrade procedure: #10893

**Comment by senthil13** [comment]
The clarification is good, but the migrator not showing any success or failure, when i run. For my installation the harbor,yml is in `/apps/harbor/harbour.yml` so i supplied like below
```
docker run -it --rm -v ${harbor_yml}:/apps/harbor/harbor.yml goharbor/harbor-migrator:v1.10.1 --cfg up
```
But it never gave me an success message apart from skip message. Do i need to proceed to install step?
