### ISSUE TITLE
Is there any plan or have done something for multi arch for harbor.  for example support arm64

### ISSUE THREAD

**Issue by yuzp1996** [goharbor/harbor#11138]
Hello, Is there any plan or anything you have done for harbor image to support multi arch. for example support x86 and arm64.

I want some suggest from you. Thank you very much

**Comment by reasonerjt** [comment]
In Harbor 2.0 there will be a better support for manifest list.  We've demoed on the community meeting.

**Comment by yuzp1996** [comment]
hello  Sorry I think  I did not make the question clear

what I want to say is if there any plan for harbor image for example  harbor-db support arch arm64 not only amd64
![image](https://user-images.githubusercontent.com/23007448/77500178-4417a380-6e8f-11ea-93dc-f21223d355d6.png)

**Comment by xaleeks** [comment]
We've gotten a bunch of these requests for ARM over the past year but ARM as a whole hasn't garnered enough attention to be considered mainstream.  Maybe that has changed, I'm really curious how you are using Harbor in ARM, or registry requirements for ARM in general.  Is this an edge kubernetes deployment?

**Comment by xaleeks** [comment]
I'm consolidating all requests to this one https://github.com/goharbor/harbor/issues/10578, please comment here.
