### ISSUE TITLE
Allow robot accounts to have access to multiple projects

### ISSUE THREAD

**Issue by jacekn** [goharbor/harbor#11130]
** Problem **

Currently robot accounts are created under projects and each robot account can have access to one project only.

At the same time docker only allows for 1 auth config for host:port pair. In practice this means that it impossible to use docker with robot accounts if it needs access to more than one project.

An example where this limitation is problematic are CI systems. Those systems often build and publish images to multiple projects and currently there is no good way to allow that with harbor.

**Describe the solution you'd like**

I think ideally robot accounts should be global and their access should be configured in the same way as access for regular users is configured. This would let me create 1 robot account and grant it access every project it needs access to.

**Additional context**

It's still possible to create local, LDAP or OpenID accounts for CI systems and grant those accounts access to relevant resources but those solutions have security implications.

Docker supports `--config` flag which can be used to work around the problem. It's possible to create multiple docker config directories and point docker at relevant one depending on image being pulled/pushed. This works but it adds significant management overhead.

**Comment by xaleeks** [comment]
@jacekn Hi this is well understood and being tracked here https://github.com/goharbor/harbor/issues/10774
