### ISSUE TITLE
[Nightly Test] Add pipeline for internal_tls feature.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11139]
What can we help you?

**Comment by reasonerjt** [comment]
Can we verify this in nightly for 2.0.0 ?

**Comment by danfengliu** [comment]
Internal TLS  has been enabled as a default configuration in nightly pipelines.
There is a switch for this configuration in nightly pipeline for nightly flexibility.
![image](https://user-images.githubusercontent.com/44018302/78896909-e6e13c00-7aa3-11ea-9d30-2bdc938b661d.png)
