### ISSUE TITLE
deployment security for manifest list / OCI index

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11136]
As dictated by the OCI spec, when pulling an OCI index, it will pull image referenced by the index that matches the OS of the client.  CNAB however does not use the OCI index the way it was intended, which is meant to be a bundling of different versions (platforms) of the same image.  CNAB is an arbitrary bundling of different images and its client does not check for OS or platform information during pulls, it just pulls the whole thick bundle.  

How this impact Harbor 2.0 image scanning

Harbor has ‘deployment security’ which can prevent images from being pulled if vulnerabilities are discovered.  For pulling indexes, ‘deployment security’ should apply this at the individual image level and not on the index as a whole.  This means when pulling Redis for ARM for ex., it is not impacted by whether Redis for amd64 has CVEs.  This applies to CNABs as well, so if a scan on a CNAB bundle returns 4 clean images and 6 vulnerable images, pulling the CNAB will only pull down the 4 clean images, thus changing the bundle.  This guarantees consistency across all artifacts using the OCI index and no customizations are needed on harbor server side to accommodate artifacts like CNAB

**Comment by renmaosheng** [comment]
Hi Alex,
      won't it break the CNAB bundle usage? I think we should either allow or disallow the whole bundle, but not part of it. thanks.

Steven

**Comment by xaleeks** [comment]
@renmaosheng 
We discussed pros and cons extensively, so this follows from a couple of arguments. 
1. we want to build a consistent experience for OCI, otherwise customizing for each artifact is too costly.  CNAB is using the lax guidelines of OCI to build something unique and other artifact vendors will likely do the same.  
2. if we apply this across the entire bundle which means all child images need to be vulnerability free in order to be pulled, this is counter-intuitive for pulling regular indexes because it's only pulling one image and not all of them.  
3. we can try this approach first and iterate off community's feedback.  It is _possible_ to force pull all-or-nothing for indices on harbor server side, if we use a whitelist basically

**Comment by xaleeks** [comment]
This is fully outlined in docs now, https://github.com/goharbor/harbor/pull/11897/files
