### ISSUE TITLE
Clair scans never complete

### ISSUE THREAD

**Issue by stephenwolfe1** [goharbor/harbor#11135]
**Expected behavior and actual behavior:**
Since upgrading to 1.10.0 vulnerability scans do not complete. Job stalls a little over half way and stops showing progress.

**Steps to reproduce the problem:**
Upgrade to v1.10. Click scan button. Wait.

**Versions:**
- harbor version: [1.10.0]
- kubernetes: [1.14.9]

**Additional context:**
This scan was started ~18hours ago and stopped showing progress ~15hours ago

<img width="791" alt="Screen Shot 2020-03-18 at 12 40 37 PM" src="https://user-images.githubusercontent.com/38081080/77000738-18883c80-6916-11ea-89ed-62d7ac95f826.png">

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by catchups** [comment]
In general, Clair scanning ends quickly. First you need to check if a request has been received by the Clair pod.

**Comment by steven-zou** [comment]
First, scan all will scan all the images at the registry, more time may be needed.
Second, some failed jobs will be retried (max retry 3)
Third, suggest upgrading to the latest 1.10.X, we have introduced some fix of job service to make sure the status sync is more reliable.

**Comment by steven-zou** [comment]
No further comments, I'll close this issue.

If needed, you can reopen or create new issues.
