### ISSUE TITLE
UX: Auth config

### ISSUE THREAD

**Issue by kav** [goharbor/harbor#11150]
When enabling OIDC Harbor OIDC scope is required however nothing on the page clarifies the expected format or content. Certain scopes are always required and should be defaulted sensibly.

Clicking More Info takes the user to a general OIDC page rather than the relevant Harbor docs.

When entering scope incorrectly the error is unhelpful and doesn't describe the format required:
Field is required and should be in scope format.

A lot of the tooltips are a bit unhelpful, they either repeat the name of the field without context or they explain the basic functionality (how a drop down works, e.g. select LDAP for LDAP).

**Comment by reasonerjt** [comment]
```
When entering scope incorrectly the error is unhelpful and doesn't describe the format required:
Field is required and should be in scope format.
```

Could you give a concrete example?

Configuring OIDC correctly does require some background, so you better work with you admin of IDP to do the configuration.

Do you think reading the admin guide or user guide helpful? 
https://goharbor.io/docs/1.10/administration/configure-authentication/oidc-auth/

**Comment by kav** [comment]
Yeah, the guide is great. Perhaps that should be the more info link?

A concrete example of what? If you put in anything that isn't valid you get:
`Field is required and should be in scope format.`
For example
> foo,bar

That error should describe or provide an example of "scope format"
