### ISSUE TITLE
Invalid user name or password - harbor.v1.10.1.

### ISSUE THREAD

**Issue by glucky009** [goharbor/harbor#11168]
Guys had an issue with Harbor v1.10.1. Successfully installed harbor on a virtualbox vm(CentOS 7). The way I install harbor was this command :
# ./install.sh --with-clair

Here is the last output of the installation : 
Creating network "harbor_harbor" with the default driver
Creating network "harbor_harbor-clair" with the default driver
Creating harbor-log ... done
Creating harbor-db     ... done
Creating registryctl   ... done
Creating harbor-portal ... done
Creating registry      ... done
Creating redis         ... done
Creating clair         ... done
Creating harbor-core   ... done
Creating clair-adapter     ... done
Creating harbor-jobservice ... done
Creating nginx             ... done
✔ ----Harbor has been installed and started successfully.----

Note: No login issue with Harbor v1.2.0

When logging-in to the UI portal I got this error message: Invalid user name or password. Credentials use : 

username: admin
password: Harbor12345

On the web browser here is error : 
502 Bad Gateway
![image](https://user-images.githubusercontent.com/22044883/77230191-8c606880-6be6-11ea-8d56-52c1111fad3d.png)

Here is the status of my containers :  (Note : why clair and harbor are restarting?)

![image](https://user-images.githubusercontent.com/22044883/77230231-ee20d280-6be6-11ea-8d5f-e1d1df26c2bd.png)

Logs: /var/log/harbor/core.log
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/core/config/config.go:100]: key path: /etc/core/key
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/core/config/config.go:73]: init secret store
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/core/config/config.go:76]: init project manager based on deploy mode
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/core/config/config.go:145]: initializing the project manager based on local database...
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/core/main.go:181]: configurations initialization completed
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Mar 22 01:31:45 172.26.0.1 core[3018]: 2020-03-21T15:31:45Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host
Mar 22 01:31:47 172.26.0.1 core[3018]: 2020-03-21T15:31:47Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host
Mar 22 01:31:49 172.26.0.1 core[3018]: 2020-03-21T15:31:49Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host
Mar 22 01:31:51 172.26.0.1 core[3018]: 2020-03-21T15:31:51Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host
Mar 22 01:31:54 172.26.0.1 core[3018]: 2020-03-21T15:31:54Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host
Mar 22 01:31:56 172.26.0.1 core[3018]: 2020-03-21T15:31:56Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on 127.0.0.11:53: no such host

Logs : var/log/harbor/proxy.log
Mar 22 01:27:47 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:28:17 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:28:47 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.002 0.002 .
Mar 22 01:29:17 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:29:47 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:30:18 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.002 0.002 .
Mar 22 01:30:48 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:31:18 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:31:48 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:32:18 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.002 .
Mar 22 01:32:48 172.26.0.1 proxy[3018]: 127.0.0.1 - "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0" 0.000 0.000 .
Mar 22 01:32:54 172.26.0.1 proxy[3018]: 2020/03/21 15:32:54 [error] 7#0: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /c/login HTTP/1.1", upstream: "http://172.26.0.8:8080/c/login", host: "localhost:8080", referrer: "http://localhost:8080/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects"
Mar 22 01:32:54 172.26.0.1 proxy[3018]: 10.0.2.2 - "POST /c/login HTTP/1.1" 502 552 "http://localhost:8080/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.000 0.000 .
Mar 22 01:33:02 172.26.0.1 proxy[3018]: 2020/03/21 15:33:02 [error] 7#0: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.2, server: , request: "POST /c/login HTTP/1.1", upstream: "http://172.26.0.8:8080/c/login", host: "localhost:8080", referrer: "http://localhost:8080/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects"
Mar 22 01:33:02 172.26.0.1 proxy[3018]: 10.0.2.2 - "POST /c/login HTTP/1.1" 502 552 "http://localhost:8080/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.000 0.000 .

Logs : /var/log/harbor/portal.log
Mar 22 01:32:18 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:32:18 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:32:45 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:32:45 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:32:48 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:32:48 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:33:15 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:33:15 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:33:18 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:33:18 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:33:45 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:33:45 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:33:49 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:33:49 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:34:15 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:34:15 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:34:19 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:34:19 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:34:45 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:34:45 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:34:49 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:34:49 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:35:15 172.26.0.1 portal[3018]: 127.0.0.1 - - [21/Mar/2020:15:35:15 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"
Mar 22 01:35:19 172.26.0.1 portal[3018]: 172.26.0.9 - - [21/Mar/2020:15:35:19 +0000] "GET / HTTP/1.1" 200 718 "-" "curl/7.59.0"

**Comment by glucky009** [comment]
Guys, any updates on this? Thanks in advance...

**Comment by reasonerjt** [comment]
based on the output, it seems the db is not started, you need to find the reason why db is not started.
