### ISSUE TITLE
I upgrade harbor 1.4.0 to 1.6.0 ,mysql => PostgreSQL failed

### ISSUE THREAD

**Issue by SandyLing** [goharbor/harbor#11164]
I upgrade harbor 1.4.0 to 1.6.0 ,mysql => PostgreSQL have a problem.
mysql upgrade PostgreSQL failed.
`Performing upgrade 1.5.0...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
1.5.0 (head)
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
1.5.0 (head)
Upgrade performed.
/harbor-migration/db/util/mysql_pgsql_1_5_0.sh: line 24:   108 Killed                  python /harbor-migration/db/util/mysql_pgsql_data_converter.py /harbor-migration/db/schema/registry.mysql /harbor-migration/db/schema/registry_insert_data.pgsql`

**Comment by wadefelix** [comment]
1 directly export data from the old version with csv format
2 make a shell script to covert the mysql tables to postgresql tables
3 import the tables into postgresql

I updated a deploy to version 1.8.5 with this method.

**Comment by wadefelix** [comment]
## 数据库导入1.8.5笔记
1. 基本只需要导入`user`->`harbor_user`, `project`, `project_member`, `repository`即可。使用`csv`格式即可，这几表都不大。`access_log`表巨大，可以只导出其中的create和push记录，自己决定吧。
2. `harbor_user`表没有变化。
3. `project`表则是把`public`属性移除挪动到了`project_metadata`表，使用`name`=`public`属性进行管理，前版本是1或0，新值是字符串true false。
4. `project_member`增加了`id`和`entity_type`两列，`id`就是递增主键，`entity_type`则是一个只有`u`和`g`两个字符值的属性，分别标识是用户还是用户组，用户组是后来加进来的概念，所以原来的数据直接赋值`u`即可。
5. `repository`没有变化。`pull_count`列原数据也丢了，不过还可以从`access_log`表格中重新计算得到，不恢复也无所谓。
6. 导入后要重设下pg各表的自增id

```bash
# `user`->`harbor_user`
SRC=user.csv
DST=pg_harbor18_user.csv
sed '1iuser_id,username,email,password,realname,comment,deleted,reset_uuid,salt,sysadmin_flag,creation_time,update_time' $SRC >$DST

# `project`
SRC=project.csv
DST=pg_harbor18_project.csv
DST_meta=pg_harbor18_project_metadata.csv
sed 's/\(.*\)\(,"[01]"\)/\1/' $SRC > $DST
sed -i '1iproject_id,owner_id,name,creation_time,update_time,deleted' $DST
sed 's/"\([0-9]\+\)",\(.*\),"\([0-9]\+\)"/\1,public,\3/;s/,1/,true/;s/,0/,false/' $SRC > $DST_meta
sed -i '1iproject_id,name,value' $DST_meta


# `repository`
SRC=repository.csv
DST=pg_harbor18_repository.csv
split -l 8000 $SRC ${DST}.
for x in ${DST}.*; do
  sed -i '1i"repository_id","name","project_id","description","pull_count","star_count","creation_time","update_time"' $x
done

# `project_member`
SRC=project_member.csv
DST=pg_harbor18_project_member.csv
sed 's/"\([0-9]\+\)","\([0-9]\+\)","\([0-9]\+\)",\(.*\)/\1,\2,\3,u/' $SRC >$DST
sed -i '1iproject_id,entity_id,role,entity_type' $DST

# `access_log`
SRC=access_log.csv
DST=pg_harbor18_access_log.csv
split -l 8000 $SRC ${DST}.
for x in ${DST}.*; do
  sed -i '1i"log_id","username","project_id","repo_name","repo_tag","guid","operation","op_time"' $x
done
```
