### ISSUE TITLE
[UI Search] Project log search speed is very low 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11171]
There are 2 entries to reproduce this search speed issue:
1. Log tab:
![image](https://user-images.githubusercontent.com/44018302/77276634-2400ac80-6cf6-11ea-8923-ec3b53902d7d.png)

2. Advanced search:
![image](https://user-images.githubusercontent.com/44018302/77276805-76da6400-6cf6-11ea-9771-c286f0b33504.png)

**Comment by danfengliu** [comment]
![image](https://user-images.githubusercontent.com/44018302/77288437-c9297e00-6d12-11ea-9ea0-7b891d14ae60.png)

**Comment by AllForNothing** [comment]
It is because of #11522
