### ISSUE TITLE
There will be many robot accounts in the audit log that cannot be queried

### ISSUE THREAD

**Issue by kebyn** [goharbor/harbor#11175]
![image](https://user-images.githubusercontent.com/9145323/77280556-a17cea80-6cff-11ea-92f9-1ae093d84f73.png)
1. This `robot$c5f3088a-6cb4-11ea-aa48-9677b9780cb8` account is not my established user, nor can it be found in the robot account of the project
2. There are a lot of account logs like this, and all the images will be pulled at 8 o'clock every day

**Comment by wy65701436** [comment]
hi, which build are you playing?

**Comment by wy65701436** [comment]
these logs are generated by the scan all job, it needs to create robot account to pull image and do scan.

**Comment by kebyn** [comment]
> hi, which build are you playing with?

```
~$ helm version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
~$ helm -n harbor ls
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
harbor	harbor   	1       	2020-03-20 19:27:40.116738942 +0800 CST	deployed	harbor-1.3.1	1.10.1
``

**Comment by kebyn** [comment]
> these logs are generated by the scan all job, it needs to create robot account to pull image and do scan.

This behavior has completely polluted the audit log, resulting in a large number of useless logs in the audit log.

**Comment by reasonerjt** [comment]
@kebyn 
I don't think this is polluted, the audit log should record all access to the artifact, in this case, for scanning the image was pulled, the audit log is doing the right thing to keep this record.

@wy65701436 one valid improvement is create the robot account with some recognizable pattern and it can be filtered.

**Comment by kebyn** [comment]
> @kebyn
> I don't think this is polluted, the audit log should record all access to the artifact, in this case, for scanning the image was pulled, the audit log is doing the right thing to keep this record.
> 
> @wy65701436 one valid improvement is create the robot account with some recognizable pattern and it can be filtered.

But too many such logs have overwritten other normal audit logs, more than half of the more than 100,000 logs are such useless logs, if I can choose to hide such logs, I think it will be more friendly

**Comment by xaleeks** [comment]
Agree with Daniel.  Can we add an identifier to the log to distinguish regular robot accounts vs special robots created for pulling images for image scanners at the very least.  @wy65701436
