### ISSUE TITLE
Auth middleware should treat Head request as action Push not Pull

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11188]
We found that, during docker app to push a CNAB, it trys to head a untagged manifest. 

1,  Against Harbor, it returns a 200 for a public one, but 404 for a private one.
2, Against Docker-hub, it always returns a 404.

Docker client will define whether to use the auth header in the following request base on the response code.

**Comment by reasonerjt** [comment]
If you you treat is as push you see problem when pulling the public artifacts

**Comment by reasonerjt** [comment]
@wy65701436 @heww can we open an issue to `docker app` ?
Based on my understanding I don't think they are doing the right thing?

**Comment by ywk253100** [comment]
Seems docker app useds cnab-to-oci as a library, cnab-to-oci has the same issue

**Comment by wy65701436** [comment]
@reasonerjt I don't think it's an issue of docker app as we found that Helm v3 has the same issue. 
https://github.com/goharbor/harbor/issues/11271

**Comment by reasonerjt** [comment]
Fixed by #11406 
Verified `docker app push` to a public project in build ` v2.0.0-42801b76`
