### ISSUE TITLE
Can somebody please explain use of Registry Certificate in detail

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#11182]
Harbor documentation has very less iformation on Registry Certificate.

**Comment by reasonerjt** [comment]
Please provide more context to help us understand your question

**Comment by arsulesandy** [comment]
I wanted to understand the importance of ca.crt which is obatained after clicking registry certificate button.
![image](https://user-images.githubusercontent.com/8274052/77311520-43afc900-6d26-11ea-8c09-709ab93932f6.png)

**Comment by reasonerjt** [comment]
This is for downloading the root cert of Harbor, which is helpful in case it's hosted using a self-signed certificate.

**Comment by arsulesandy** [comment]
thank you team
