### ISSUE TITLE
UI throws internal error when I navigate to "interrogation service"

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11187]
In my setup, if I don't enable any scanner.  
If I navigate to "interrogation service", click "Vulnerabilities".  
I see UI shows error "internal server error"
![Screen Shot 2020-03-24 at 10 18 29 AM](https://user-images.githubusercontent.com/2390463/77381621-5d4e2080-6db9-11ea-9ec8-8ac542d22041.png)

**Comment by AllForNothing** [comment]
It's surely from back-end api

**Comment by heww** [comment]
@AllForNothing  Please ensure that /api/v2.0/system/scanAll/schedule and /api/v2.0/scans/schedule/metrics APIs only request when there exists scanners in the system.

**Comment by AllForNothing** [comment]
Back-end API should provide more meaningful  error info

**Comment by AllForNothing** [comment]
Fixed by #11355
