### ISSUE TITLE
[Quotas After GC] Quotas was not released after GC

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11193]
Project quotas was not released after GC operation.

**Test Step:**
  1. Create a project with 200M storage quotas;
  2. Push a size of  over 300M image into the project;
  3. Fail to push image as expected;
  4. Perform GC operation;
  5. Quotas should release all, but it releases nothing, stays same.

![image](https://user-images.githubusercontent.com/44018302/77381765-a4d4ac80-6db9-11ea-81f6-bde03f098f43.png)

![image](https://user-images.githubusercontent.com/44018302/77381643-6a6b0f80-6db9-11ea-8714-991507839abc.png)

/api/v2.0/system/gc/1/log

![image](https://user-images.githubusercontent.com/44018302/77381855-df3e4980-6db9-11ea-9687-bed7784717b4.png)

**Harbor Version : v2.0.0-4187b375**

**Comment by wy65701436** [comment]
duplicate with https://github.com/goharbor/harbor/issues/11190
