### ISSUE TITLE
The data shown in the tag tooltip is not consistent with the tag view in the detail page

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11199]
<img width="927" alt="Screen Shot 2020-03-24 at 11 20 14" src="https://user-images.githubusercontent.com/5753287/77384892-8a063600-6dc1-11ea-8f4b-6ce109c03439.png">

Suggest keeping consistent to avoid confusion

**Comment by reasonerjt** [comment]
@steven-zou could you elaborate what's not consistent and what's confusing?
