### ISSUE TITLE
A refresh button should be provided in the artifact detail page

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11192]
for refreshing data, not via refresh the page by browser

**Comment by jwangyangls** [comment]
the artifact tag and addition  already have refresh and it  no need to add for  extra attribute

**Comment by jwangyangls** [comment]
![image](https://user-images.githubusercontent.com/29826789/78098457-c107c780-7411-11ea-89e2-a553f77bc05f.png)

**Comment by xaleeks** [comment]
Btw,new tags or removed tags should be immediately reflected after 'add tag' and 'remove tag' without having to manually refresh.  Same with cves after a scan is performed.  But adding this is better for consistency with other features within web console.

**Comment by jwangyangls** [comment]
This issue can be closed after discussion with StevenZ and Alex
