### ISSUE TITLE
Rename the `scan complete percent` in the scan summary report tip

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11197]
<img width="1178" alt="Screen Shot 2020-03-24 at 11 07 32" src="https://user-images.githubusercontent.com/5753287/77384233-d3558600-6dbf-11ea-8a89-b411c6e0b90e.png">

-> `Limited Success (Scan performing on some artifacts are failed or not supported): 80%`?

**Comment by AllForNothing** [comment]
Fixed by PR #11332
