### ISSUE TITLE
The columns of artifact list view should be adjusted 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11194]
<img width="1173" alt="Screen Shot 2020-03-24 at 10 47 03" src="https://user-images.githubusercontent.com/5753287/77383061-e87ce580-6dbc-11ea-8e6e-02a7610ba7ba.png">

- add a `docker pull command column`
- move the `annotation`, `pull time` and `push time` to the `overview` of tag detail page
- wider the `label` column
- wide the `tag` column

**Comment by reasonerjt** [comment]
Different artifacts will have different pull commands, we need to be careful with that.

**Comment by reasonerjt** [comment]
Pending on the input from @xaleeks

**Comment by xaleeks** [comment]
I think push time, pull time are useful in this view so you can see it right away
the width is adjustable so it's not a huge issue.  Maybe make tag wider on first page refresh, and labels a bit narrower if possible.

**Comment by xaleeks** [comment]
here are changes discussed today
1. move annotations into details page
2. add docker pull command column
3. keep push time and pull time in repo since this is the push/pull time of the artifact and not the tags, there's currently nowhere else where this info is kept
@jwangyangls

**Comment by jwangyangls** [comment]
@xaleeks  Different types of artifacts have different commands. Just add commands of type image?

**Comment by reasonerjt** [comment]
Let's add pull commands for following artifacts:

1. helm chart (v3)
2. CNAB
