### ISSUE TITLE
Project default quota can be changed in Read-Only mode

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11205]
**Expected behavior and actual behavior:**
The project default quota can not be edit when repository is read only mode

**Steps to reproduce the problem:**
1. Change repo to read only mode.
2. Go to "Administration" ->"Project Quota" --> Select "Default artifact count per project"  set the count to 100 and click "OK", the default quota saved.

Expect result:
The default quota settings can not be changed when repository is read only mode.

<img width="1251" alt="Screen Shot 2020-03-24 at 11 38 33 AM" src="https://user-images.githubusercontent.com/2696760/77386160-22ea8080-6dc5-11ea-877d-453deb3b1455.png">
<img width="1251" alt="Screen Shot 2020-03-24 at 11 38 41 AM" src="https://user-images.githubusercontent.com/2696760/77386164-254cda80-6dc5-11ea-9457-b1765907ef9c.png">

**Comment by wy65701436** [comment]
close it as it works as design.
