### ISSUE TITLE
Add meaningful artifact kind prefix before the artifact digest in navigation bar/page title

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11209]
To easily understand.

<img width="667" alt="Screen Shot 2020-03-24 at 12 36 48" src="https://user-images.githubusercontent.com/5753287/77388909-6d233000-6dcc-11ea-97c8-f8d83852be84.png">

**Comment by reasonerjt** [comment]
Need decision on how to render the UI.
