### ISSUE TITLE
Children artifacts of a manifest list can be scanned via UI hack

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11207]
<img width="1173" alt="Screen Shot 2020-03-24 at 12 15 13" src="https://user-images.githubusercontent.com/5753287/77387771-3bf53080-6dc9-11ea-9b0e-f03e16ad561e.png">

**Comment by wy65701436** [comment]
the action should be disabled for the untagged manifest of index.

**Comment by steven-zou** [comment]
checked with @xaleeks , it's allowed

Close this issue
