### ISSUE TITLE
Authentication way of Clair adapter returned in the scanner metadata is still Bearer token

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11204]
I think we have switched to the robot account way

<img width="1140" alt="Screen Shot 2020-03-24 at 11 38 27" src="https://user-images.githubusercontent.com/5753287/77385866-537dea80-6dc4-11ea-90f8-5938e0674827.png">

@heww Please confirm

**Comment by heww** [comment]
This is the issue of clair adapter.

**Comment by heww** [comment]
After the discussion, we still keep the bearer token type authorization support in harbor. 

Closed by #11505
