### ISSUE TITLE
[Quotas Count] Push an existing image within  a repository didn't trigger quotas count

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11217]
Push an existing image within a repository by docker CLI didn't trigger quotas count, but if copy the same image into this repository will trigger quotas count, and count for the previous image pushed by docker CLI.

**Test Step:**
docker tag alpine:latest 1.1.1.1/test/alpine:latest
docker push 1.1.1.1/test/alpine:latest
docker tag alpine:latest 1.1.1.1/test/alpine2:latest
docker push 1.1.1.1/test/alpine2:latest

Expectation count is 2, but actually is 1

![image](https://user-images.githubusercontent.com/44018302/77395373-656b8780-6ddc-11ea-9a0a-8e0e1dbca1fb.png)

**Harbor Version : v2.0.0-4187b375**

**Comment by heww** [comment]
Closed by #11445 because count resource not support in quota now.
