### ISSUE TITLE
Message tips for creating duplicated tags under the repository is not very clear

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11218]
<img width="1161" alt="Screen Shot 2020-03-24 at 14 46 00" src="https://user-images.githubusercontent.com/5753287/77396205-42da6e00-6dde-11ea-908c-2d771ad32cb8.png">

Repo number ID may be replaced by the name/current repository?

**Comment by jwangyangls** [comment]
This message is returned from the backend，

**Comment by ywk253100** [comment]
UI has added logic to check the existence of the name under the same repository
