### ISSUE TITLE
sometimes replication failed with MANIFEST_UNKNOWN error

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11219]
harbor 2.0
build 3158

![image](https://user-images.githubusercontent.com/188115/77396488-d318b300-6dde-11ea-9e9b-d9047896ecb3.png)

![image](https://user-images.githubusercontent.com/188115/77396362-9cdb3380-6dde-11ea-938d-663f801a8c0f.png)

**Comment by ywk253100** [comment]
Cannot reproduce this issue.
