### ISSUE TITLE
Kinds of NOT FOUND errors returned when deleting the specified artifacts (re-push and re-delete)

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11224]
<img width="1160" alt="Screen Shot 2020-03-24 at 15 19 12" src="https://user-images.githubusercontent.com/5753287/77398621-dd3cb080-6de2-11ea-8e6e-6433ae1f3887.png">

<img width="1177" alt="Screen Shot 2020-03-24 at 15 14 39" src="https://user-images.githubusercontent.com/5753287/77398358-512a8900-6de2-11ea-8526-bd82b7b57557.png">

OPERATIONS:

- helm chart push 10.92.222.13/testingday/nginx:sz
- check artifact list to make sure it's there
- delete it - ok
- helm chart push 10.92.222.13/testingday/nginx:sz (re-push)
- check artifact list to make sure it's there
- delete it (artifact with digest xxxx not found)
- helm chart push 10.92.222.13/testingday/nginx:sz (re-push)
- check artifact list to make sure it's there
- delete it (tag is not found)

**Comment by ywk253100** [comment]
This is an UI issue. When I try to delete the artifact the second time, two delete requests are sent,
the third time three delete requests are sent:

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/5835782/77534143-181e1180-6ed3-11ea-89be-eda263286517.png">
