### ISSUE TITLE
Failed to get log when GC triggered by cron

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11226]
What can we help you?

**Comment by wy65701436** [comment]
After having an investigation, it should be an issue of jobservice, the cron job will generate a log with name like `6ca39099ba856921ee1fc4d0@1585035359`. When core tries to use the name to get log content, jobsservice throws an error: 

`Mar 24 07:47:59 172.30.0.1 jobservice[19235]: 2020-03-24T07:47:59Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/6ca39099ba856921ee1fc4d0@1585035359/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"invalid length of log identify"}`
