### ISSUE TITLE
The failure seemed to be ignored while combining the scan report for an index.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11228]
pushed the hello world CNAB using `docker app`:
https://github.com/docker/app/tree/master/examples/hello-world

If I scan this CNAB artifact using trivy, it will fail to scan one of the images:

![Screen Shot 2020-03-24 at 4 13 59 PM](https://user-images.githubusercontent.com/2390463/77402994-7de29e80-6dea-11ea-8ba3-bc7cdf3eb15a.png)

However this is not reflected on the scan report of the cnab artifact.

![Screen Shot 2020-03-24 at 4 15 59 PM](https://user-images.githubusercontent.com/2390463/77403166-c9954800-6dea-11ea-8e6b-a4ea76f32021.png)

If it's ignored there will be problem when applying the vulnerability policy check when the artifact is pulled.

**Comment by reasonerjt** [comment]
First clarified that there will be no issue for applying vuln policy.

For the situation in this issue, we should refine the UI to explicitly warn user about the limited success.

**Comment by AllForNothing** [comment]
Fixed by PR #11332
