### ISSUE TITLE
Pull time is always empty in Tag Retention Dry-run report 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11236]
<img width="1265" alt="Screen Shot 2020-03-24 at 4 52 34 PM" src="https://user-images.githubusercontent.com/2696760/77406761-1af40600-6df0-11ea-87f7-66082610d803.png">
<img width="1270" alt="Screen Shot 2020-03-24 at 4 51 08 PM" src="https://user-images.githubusercontent.com/2696760/77406783-234c4100-6df0-11ea-9572-ab19953af5af.png">

The actual pull time in database:
<img width="1209" alt="Screen Shot 2020-03-24 at 4 51 42 PM" src="https://user-images.githubusercontent.com/2696760/77406828-32cb8a00-6df0-11ea-986d-b7e082ddd3c4.png">

**Comment by xaleeks** [comment]
I'm seeing non null 'PulledTime' in latest 2.0 release now.  For null values, I prefer we display 'null' to '0001/01/01 00:00:00'.  Can we fix this in this release? @wy65701436 @bitsf

**Comment by bitsf** [comment]
Already fixed in 2.0-rc2 build
![image](https://user-images.githubusercontent.com/188115/81134921-d62fc300-8f88-11ea-8189-ee20ac7d376e.png)
