### ISSUE TITLE
Replication doesn't work for CNAB

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11233]
`I have a replication rule, like`

![image](https://user-images.githubusercontent.com/2841473/77406225-4aeed980-6def-11ea-8170-2579c71cd8db.png)

`and the source project has things like:`

![image](https://user-images.githubusercontent.com/2841473/77405945-d9169000-6dee-11ea-976a-0ffcaa98b246.png)

`but after I replicate, I just get three artifacts, others seem missed.`

![image](https://user-images.githubusercontent.com/2841473/77406039-fcd9d600-6dee-11ea-9a08-3312ba5ce6e3.png)

**Comment by ywk253100** [comment]
Checked with @wy65701436, the artifacts that aren't replicated have no tags while the replication rule sets tag filter as "**" which filters untagged artifacts out
