### ISSUE TITLE
UX issues in webhook dialog 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11232]
![Screen Shot 2020-03-24 at 4 37 12 PM](https://user-images.githubusercontent.com/2390463/77405449-31995d80-6dee-11ea-9098-3d5e1e00c0f9.png)

These capital labels of webhook is not quite usable.
1. More meaningful text is needed, would better if there's explanation, like `QUOTA_WARNING`, we should let user know what are the threshold
2.Events should be better organized

**Comment by AllForNothing** [comment]
@xaleeks Can you provide the explaining text for each event type?

**Comment by AllForNothing** [comment]
"Events should be better organized":  it has been fixed

**Comment by xaleeks** [comment]
I would use the following, one per line

Artifact pulled
Artifact pushed 
Artifact deleted
Chart downloaded
Chart uploaded
Chart deleted
Quota exceeded
Quota near threshold
Scanning finished
Scanning failed
Replication finished

**Comment by xaleeks** [comment]
does replication finished include replication failed? @wy65701436  @mmpei

**Comment by xaleeks** [comment]
@lweitzman please help update the UI, it's quite messy right now

**Comment by lweitzman** [comment]
Updated mockup https://www.figma.com/proto/cPY9Lh8LbIQawAJSGmi1KA/Harbor-v2.0?node-id=22%3A12961&viewport=758%2C611%2C0.09731162339448929&scaling=min-zoom
![Screen Shot 2020-04-01 at 2 56 03 PM](https://user-images.githubusercontent.com/626032/78175474-f10e9500-7428-11ea-89bb-c4842dd6fc38.png)
