### ISSUE TITLE
[UI] Add  artifact statistic for CNAB or manifest type of artifact

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11237]
In repository view,  there is artifact statistic, but CNAB or manifest list artifact view, no artifact statistic for the artifact achieves, I think there should be statistic for artifact achieves.

![image](https://user-images.githubusercontent.com/44018302/77406885-4971e100-6df0-11ea-928b-340d9b1d7aa4.png)

![image](https://user-images.githubusercontent.com/44018302/77406289-61953080-6def-11ea-8a16-e81df2ede96d.png)

**Comment by jwangyangls** [comment]
I am not sure if I need to do this, and if so, do I need to add detailed content to the api repository list @x
 @ywk253100

**Comment by reasonerjt** [comment]
in v2.0.0 we will not show the number of children of an index.
