### ISSUE TITLE
The selection for scan in the artifact list view should not be limited to single one

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11238]
The scan should be allowed when multiple artifacts are selected

Exactly like delete action

<img width="658" alt="Screen Shot 2020-03-24 at 17 01 26" src="https://user-images.githubusercontent.com/5753287/77407465-209e1b80-6df1-11ea-9fc6-42a40b651774.png">

**Comment by AllForNothing** [comment]
fixed
