### ISSUE TITLE
[UI] Add "Remove All" in CVE white list configuraion

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11240]
Currently, both Clair and Trivy scanners  have been supported by harbor, and also CVE white list are different for Clair and Trivy scanners. When using Clair,  CVE White list was set for Clair, then switch scanner to Trivy, user has to remove all current setting one by one for CVE White list, then all a bunch of new CVE ID, it's not friendly at all.

**Comment by jwangyangls** [comment]
new feature for nightly

**Comment by xaleeks** [comment]
@danfengliu I'm not sure what this is referring to, can you elaborate?  I just tried switching scanner within a project and the system CVE list is still in effect, no need to remove and re-enter.  However, it is missing a 'remove all' button for CVE whitelists however
