### ISSUE TITLE
Push time is incorrect in the tag retention Dry-Run report

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11244]
After update the push time to 2019-x-x and run a tag retention dry-run the report push time is incorrect.
<img width="1191" alt="Screen Shot 2020-03-24 at 7 05 03 PM" src="https://user-images.githubusercontent.com/2696760/77419045-bee6ad00-6e02-11ea-92fe-1c134b9ff6e7.png">
<img width="1269" alt="Screen Shot 2020-03-24 at 7 03 16 PM" src="https://user-images.githubusercontent.com/2696760/77419060-c60dbb00-6e02-11ea-942e-41a6b3081a42.png">

**Comment by bitsf** [comment]
you should modify table tag
