### ISSUE TITLE
harbor 2.0 quota count is hard to define now

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11241]
when docker push an image, such as busybox:latest, because there're actually several sub artifacts in it in order to distinguish different OS/arch, so the quota will count this busybox:latest as N.
This may be difficult for user to define quota with count in future.

**Comment by reasonerjt** [comment]
If we don't consider the number of artifact something need to be controlled we can remove it, but I don't think the way we count it is wrong.

**Comment by wy65701436** [comment]
To count artifact makes the logic and code sample, I prefer to use `N` instead of `1` for an index.

**Comment by reasonerjt** [comment]
@xaleeks pending on your input.

**Comment by reasonerjt** [comment]
Overall preference is to remove the count quota, pending for final decision

**Comment by xaleeks** [comment]
We can keep this if we can reach a consensus on how this should be defined so it fits the use cases for all the different artifacts leveraging OCI index.  I am not averse to deprecating this altogether and guiding users to use quota through disk space, for the following reasons
 
1. The most natural definition we are inclined towards is when pushing an index containing k referenced images (digests), we treat quota diff as +k, and -k when deleting.  However, different OCI artifact implementations roll different things together into an index, things that were not intended to have an affect on quota.  ie the OCI index itself containing the referenced images is not treated as +1 even though it is backed by a harbor artifact object.  The invocation image within CNAB is another example.  There are other approaches being considered for signatures in notary v2
 
2. We are lacking visibility as to how users are actually using the quota count,  I imagine most use disk space to keep projects from blowing up.  We will do some due diligence to find out
 
3. It's difficult to count number of artifacts in repo view.  The ambiguity around how this is defined for indexes leads to diminishing returns from using this quota count. 

Curious as to what the community thinks about this

**Comment by michmike** [comment]
if we were to deprecate artifact count, how will we "upgrade" projects that potentially have that defined?
can we detect this during an upgrade and issue them a warning, but not fail the upgrade. this can go into a special upgrade log as well.

I am supportive to deprecate this functionality now, and as we learn more in the future, we can reintroduce it in a way that makes sense

**Comment by xaleeks** [comment]
@bitsf @wy65701436  So let's remove this.  For upgrades, display a warning to users listing current projects where project quota count is activated and recommend that he set a new quota based on disk space to compensate.

**Comment by cmur2** [comment]
> set a new quota based on disk space to compensate

I was actually an active user of the tag count quota feature exactly because I have the impression that it cannot be compensated with disk space quotas (e.g. many small Docker images pushed under many tags that do not run into disk space quotas).

How would you define a disk space quota for a multi-tenant Harbor instance where users can (without oversight) push many small Docker images?
