### ISSUE TITLE
Postgres Error while trying to import offline database

### ISSUE THREAD

**Issue by mkuendig** [goharbor/harbor#11249]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Trying to import offline clair-database. Have started an internet connected harbor setup. Waited until database was synchronised and ready. Exported it with the commands from here:

https://goharbor.io/docs/1.10/administration/vulnerability-scanning/import-vulnerability-data/

**Steps to reproduce the problem:**

1.  start an ubuntu VM on GCP
2. quickinstall harbor
3. wait roughly 30 minutes
4. export the vulnerability database
5. go to offline harbor
6. import the clear.sql and vulnerability.sql files with pgdump

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.1
- docker engine version: don't know as managed
- docker-compose version: don't know as managed

**Additional context:**

- **Harbor config files:**

standard helm

- **Log files:** You can get them by package the `/var/log/harbor/` .

COPY 38
COPY 34725
COPY 7
COPY 6
COPY 204450
COPY 234914
ERROR:  relation "public.feature_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.feature_id_seq', 34725, tru...
                                 ^
ERROR:  relation "public.keyvalue_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.keyvalue_id_seq', 7, true);
                                 ^
ERROR:  relation "public.namespace_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.namespace_id_seq', 38, true...
                                 ^
ERROR:  relation "public.vulnerability_fixedin_feature_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.vulnerability_fixedin_featu...
                                 ^
ERROR:  relation "public.vulnerability_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.vulnerability_id_seq', 2044...

**Comment by rajesh-ivd** [comment]
I hope this message finds you well. I'm currently facing an issue when trying to import a PostgreSQL database backup, and I'm seeking assistance to resolve it.

The problem I'm encountering is as follows:

Error Message: 
![Screenshot (4)](https://github.com/dbeaver/dbeaver/assets/147796821/01254e94-d75e-4125-92f9-ffb83cebecbc)
![Screenshot (5)](https://github.com/dbeaver/dbeaver/assets/147796821/a491ecf9-dd61-4737-a84c-4875da3314c7)
![Screenshot (6)](https://github.com/dbeaver/dbeaver/assets/147796821/617d60e9-77ca-44e4-b50c-f70c592ab95f)
![Screenshot (7)](https://github.com/dbeaver/dbeaver/assets/147796821/3915d053-d646-4141-9ce8-71abd4e4376b)
![Screenshot (8)](https://github.com/dbeaver/dbeaver/assets/147796821/3da4aa39-53e6-48d9-becd-b373c70282f1)

The error seems to indicate that I'm performing a data-only restore, and I may be missing schema objects. I would like to restore both data and schema objects, and I'm unsure how to proceed.

Any suggestions, insights, or explanations on how to address this issue would be highly valuable. Thank you in advance for your help!
