### ISSUE TITLE
Scan Layer with .jar

### ISSUE THREAD

**Issue by Lyrwon** [goharbor/harbor#11247]
|     | Version |
|---|---------|
| **Harbor** | 1.10.0 |
| **docker engine** | 19.03.6 |
| **docker-compose** | 1.25.3, build d4d1b42b |

Is it able to find vulnerabilities in .jar files?

Or is there an add-on where you can scan those files too?

**Comment by heww** [comment]
You can try anchore https://github.com/anchore/harbor-scanner-adapter which supports jar.

**Comment by Lyrwon** [comment]
thank you
i will try it

**Comment by Lyrwon** [comment]
Is there a configuration where you don't need kubernetes?

**Comment by Lyrwon** [comment]
> You can try anchore https://github.com/anchore/harbor-scanner-adapter which supports jar.

The problem on harbor-scanner-adapter is, that this is only a connector between a working anchore-engine and harbor. So you need a running anchore-engine -.-

But thank you for your help
