### ISSUE TITLE
harbor 2.0 some UI not translate

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11256]
build 3158

![image](https://user-images.githubusercontent.com/188115/77498678-3102d480-6e8b-11ea-8dce-13c3cb4c9f8c.png)

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/77502160-fd2cac80-6e94-11ea-94c4-3e3f8d1b5559.png)

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/77502178-103f7c80-6e95-11ea-8ff7-79af058379b9.png)

**Comment by jwangyangls** [comment]
I suspect the translation file in your environment container is not updated

**Comment by AllForNothing** [comment]
@bitsf  Duplicated with #10708
