### ISSUE TITLE
Write and publish a 2.0 release blog on release day

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#11250]
This issue is meant to track the writing and publishing of a 2.0 release blog on release day.
A draft should be ready for review 10 days before planned release, to make sure we receive feedback and catch any errors well before release.

The blog post will be created in the https://github.com/goharbor/website repo.

- [ ] Draft ready for review
- [ ] Draft reviewed
- [x] PR for blog post ready
- [ ] Blog post published

**Comment by xaleeks** [comment]
this is done
