### ISSUE TITLE
Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'

### ISSUE THREAD

**Issue by qiyuehan** [goharbor/harbor#11261]
What can we help you?
This problem occurs the first time  log in. The account password is the default and has not been changed.Anyone ．Has anyone encountered this problem？Version:1.10.1

**Comment by wglambert** [comment]
Which service/port are you connecting to?

It should be the `nginx-photon` container on port 80, not the `harbor-portal` on 8080.
With credentials: admin / Harbor123

**Comment by kratos81** [comment]
I experienced the same issue .  I changed the default password , it didn't work.  Even when I reverted to the default , it still didn't work
