### ISSUE TITLE
admin role can't modify his role when he was added as project developer

### ISSUE THREAD

**Issue by sigsbee** [goharbor/harbor#1126]
Harbor0.5.0 rc
add a normal user,for example user1  toggle to admin role
login another user create a project, add user1 as developer
logout habor, login as user1, manage project's users, developer user with admin role can add remove user, and can modify other user's role, but can't change his own role
![manage](https://cloud.githubusercontent.com/assets/23101283/20426553/92d8312c-adba-11e6-8faa-53f3638dfe4f.PNG)

**Comment by reasonerjt** [comment]
@sigsbee please double check if the issue exists on new ui

**Comment by reasonerjt** [comment]
A user cannot modify his own role, this is a limitation.
