### ISSUE TITLE
Unexpeted behavior when scanning a cnab

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#11265]
Deploy Harbor chart with Trivy scanner enabled, the scan doesn't work, this is tracked by the issue https://github.com/goharbor/harbor-helm/issues/547. This is the background of this issue.

Trying to scan the cnab, the scanning bar stuck in in progress status:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/5835782/77509518-d4fa7900-6ea7-11ea-94ad-25bc853eab76.png">

Entering the child artifact list view, the scan already fails:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/5835782/77509482-c0b67c00-6ea7-11ea-9e6c-326a244d8c2a.png">

Come back to the cnab view again, it shows not scanned:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/5835782/77509273-63bac600-6ea7-11ea-99c7-d6f6decb9ba6.png">

**Comment by reasonerjt** [comment]
I saw this the error is trivy failed to recognize the OS, so IMO it's not a bug.
