### ISSUE TITLE
login successfully, but push failed

### ISSUE THREAD

**Issue by Lebronbingcheng** [goharbor/harbor#11263]
If you are reporting a problem, please make sure the following information are provided:
I tried to push a new image to harbor which is deployed on K8S. I got a successful response when logging in. However it showed 'unauthorized: authentication required' when I tried to push an image.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.8.x
- docker engine version: 18.09.7
- docker-compose version: 1.23.1

**Comment by krisbai** [comment]
I tried to push a new image to harbor which is deployed on K8S. I got a successful response when logging in. However it showed 'unauthorized: authentication required' when I tried to push an image.

Versions:
harbor version: 1.2.2
docker engine version: 18.09.7
docker-compose version: 1.23.1

**Comment by krisbai** [comment]
![harbor](https://user-images.githubusercontent.com/10414888/77511082-425bd900-6eab-11ea-92aa-3ce5a8308c62.jpg)

**Comment by Lebronbingcheng** [comment]
![screenshot_7](https://user-images.githubusercontent.com/20316586/77511201-88b13800-6eab-11ea-9a8b-6de37bf6fdae.png)

**Comment by wglambert** [comment]
This might be relevant  https://github.com/goharbor/harbor/issues/10840#issuecomment-591708144
>I turned off "Automatically scan images on push" option yesterday, and then there's no error.

However he's getting a `Waiting` and `Retrying` before the unauthorized error.

**Comment by Lebronbingcheng** [comment]
@wglambert I did not turn on clair. So It should not be this problem.
