### ISSUE TITLE
Rancher pipeline use custom CA error: x509

### ISSUE THREAD

**Issue by easonjim** [goharbor/harbor#11278]
Dear,
Using Rancher's pipeline function is, if the HARBOR warehouse configured with a self-signed IP certificate is used, the prompt: x509 error, how can I solve this problem?
The official way is to configure parameters to ignore:https://docs.rancher.cn/rancher2x/user-manual/projects/tools/pipelines/faqs.html#%E6%9E%84%E5%BB%BA%E9%95%9C%E5%83%8F%E6%97%B6%EF%BC%8C%E6%8F%90%E7%A4%BA%E6%9C%AA%E9%AA%8C%E8%AF%81

Is there any other way to solve this problem?

**Comment by heww** [comment]
You can sign cert for habor by the root ca which trust by rancher pipeline.
