### ISSUE TITLE
[GC] Perform GC with untagged image, CNAB with no tag  were deleted

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11277]
Test Steps:

![image](https://user-images.githubusercontent.com/44018302/77520507-46442700-6ebc-11ea-81c5-c2d6f2bf7dae.png)

![image](https://user-images.githubusercontent.com/44018302/77520597-65db4f80-6ebc-11ea-9338-872a45e2b8df.png)

**GC Log:**

2020-03-25T09:00:46Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:101]: start to run gc in job.
2020-03-25T09:00:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:113]: GC results: status: true, message: aaa/cnab1
aaa/cnab_copied
aaa/mariadb
aaa/mariadb111
bbb/cnab1
bbb/cnab_copied
ccc/cnab1
library/alpine
library/alpine: marking manifest sha256:5c4217c00be9ecba7735157998a4ac0475b5381c8c885396baa6f798f7f839db 
library/alpine: marking blob sha256:e738dfbe7a10356ea998e8acc7493c0bfae5ed919ad7eb99550ab60d7f47e214
library/alpine: marking blob sha256:c954b025b8806fe2f19bdaba8f509da37cbe7ce42640aae1193446f8b71787bd
library/busybox
library/busybox: marking manifest sha256:679b1c1058c1f2dc59a3ee70eed986a88811c0205c8ceea57cec5f22d2c3fbb1 
library/busybox: marking blob sha256:020584afccce44678ec82676db80f68d50ea5c766b6e9d9601f7b5fc86dfb96d
library/busybox: marking blob sha256:0f8c40e1270f10d085dda8ce12b7c5b17cd808f055df5a7222f54837ca0feae0
library/hello-world
library/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
library/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
library/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
library/mariadb
library/mariadb: marking manifest sha256:b5e273ed46d2b5a1c96bf8f3ae37aa5e90c6c481e7f7ae66744610d7df79cbd1 
library/mariadb: marking blob sha256:c1c9e6fba07af64bb1bf9c2e67e46755ec0072683d65144537c5d48ca84333d2
library/mariadb: marking blob sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
library/mariadb: marking blob sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
library/mariadb: marking blob sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
library/mariadb: marking blob sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
library/mariadb: marking blob sha256:215d801d026333c9167f6adfe47166d4f0c4c0d2b42bba8e8e0a04a87474427f
library/mariadb: marking blob sha256:59feacde9e0873f2f58c384307f211f814237a4e0ad7a2e1b024a354cf6edac3
library/mariadb: marking blob sha256:741aa98d779c1bb98e2f8b7fff2d11ef6b25fe63f81d3558d78545f16e6fbbe3
library/mariadb: marking blob sha256:e3f771d07df1b6b9589bbb07de679a21b2283402a22cd26f549d7302be7e5f61
library/mariadb: marking blob sha256:38be307a8063d66ba338584a8c466192d55c3c30eadd9726990b47e35168a2be
library/mariadb: marking blob sha256:5ef9df553f6df85d27ed451a3131bfad6ec9fc17194d218541ea03b1f98001c1
library/mariadb: marking blob sha256:3917045a480257d1965bee909926cc87f6d6149c1857057447f61899f1288035
library/mariadb: marking blob sha256:2635016646c968783dd9f5839d7ce53de7d091aa1a6c4af2624e9315198d6406
library/mariadb: marking blob sha256:50f7a0ab1439f46a5f2b42eac72b0665773bdef18fe9ca77bdbe8f09886fa78e
library/mariadb: marking blob sha256:1beaf4bb59c1b542119be53b757b52b6d1ed9a1ca95488a1f4b63dbc466dae8e
library/memcached
library/memcached: marking manifest sha256:850e5421b841d813966f5e210ff8758fe4d085efef463fb847282af59ca32546 
library/memcached: marking blob sha256:b32d3ed7da92b981b892dff6b378374f7331a44f31e8d2f9533d5d92dba62171
library/memcached: marking blob sha256:8ec398bc03560e0fa56440e96da307cdf0b1ad153f459b52bca53ae7ddb8236d
library/memcached: marking blob sha256:60e10c2aa199f4392bf1ddbfa150c6839c390eb66d1774c68eddacd8c11b8642
library/memcached: marking blob sha256:288dc9f908106487c0bad762aaa118ac1198279015f1d5440c3139be04ed7f2f
library/memcached: marking blob sha256:a244ab9e1e9de308e7c856704ec0378f73f5f996f979eaad845ac3f1a49f86bc
library/memcached: marking blob sha256:9db86ad11ed8bbffd528085a0ddb67ac989b020992ffd4c0032b263ee7dad22a
library/memcached: marking blob sha256:356f3b62ef2b4bd1cf49aa61dbbe1f11643c2f85f62cbe081e4d7de8d8f39ff2
library/redis
library/redis: marking manifest sha256:e4b315ad03a1d1d9ff0c111e648a1a91066c09ead8352d3d6a48fa971a82922c 
library/redis: marking blob sha256:9b188f5fb1e6e1c7b10045585cb386892b2b4e1d31d62e3688c6fa8bf9fd32b5
library/redis: marking blob sha256:8ec398bc03560e0fa56440e96da307cdf0b1ad153f459b52bca53ae7ddb8236d
library/redis: marking blob sha256:da01136793fac089b2ff13c2bf3c9d5d5550420fbd9981e08198fd251a0ab7b4
library/redis: marking blob sha256:cf1486a2c0b86ddb45238e86c6bf9666c20113f7878e4cd4fa175fd74ac5d5b7
library/redis: marking blob sha256:a44f7da98d9e65b723ee913a9e6758db120a43fcce564b3dcf61cb9eb2823dad
library/redis: marking blob sha256:c677fde73875fc4c1e38ccdc791fe06380be0468fac220358f38c910e336266e
library/redis: marking blob sha256:727f8da63ac248054cb7dda635ee16da76e553ec99be565a54180c83d04025a8
library/tomcat
library/tomcat: marking manifest sha256:a20a17236a2393610637906ad3f0d05c260a8bd665b065ca3d09385971cd7eba 
library/tomcat: marking blob sha256:ed94f55483b8ee076a1ee5c395a1337e9743699e73f7d40d22048ef5dc3fc7ea
library/tomcat: marking blob sha256:146bd6a886182fde06fbf747470b1c89814bc8ab1c96fdf1aef6107171959fe6
library/tomcat: marking blob sha256:9935d0c62ace92b388be202275e222007d6cac10b9c1f2c1ea63af38c09ea7ab
library/tomcat: marking blob sha256:db0efb86e80601b5bbdbb7c406426982c4202d339687c14c3941b364527e2249
library/tomcat: marking blob sha256:e705a4c4fd310b96bfb3d7928428e65f0d3f5bad0cd0bda1434aee1d89418468
library/tomcat: marking blob sha256:3d3bf7f7e874cd48fbdc9e46465264782687a52022f502b1e5eaf5f73287a877
library/tomcat: marking blob sha256:49371c5b9ff6f6c17a499d1b67b8aeec23280d3e4afb38e85074923ebe6ed90e
library/tomcat: marking blob sha256:e7873a7ca0fd67b2ad5624aa9efabd6eac45a5da640eb1030a78156b046faa1e
library/tomcat: marking blob sha256:925a95344b57ac6bff29cfdbaf7d5a1cefd9d40100a47bfdce7a813d24404b47
library/tomcat: marking blob sha256:0448a86618dafd758dba2b62472cfa4ef3e92a74f11220f1b5a5e295809400ac
library/tomcat: marking blob sha256:71917b8caadab16b4aad504b0a4a95a645092fdff6900be433e03f5a9282f865
private031585124904/hello-world
private031585124904/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
private031585124904/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
private031585124904/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585121738/hello-world
project031585121876/hello-world
project031585121876/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585121876/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585121876/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585122252/vmware/photon
project031585122252/vmware/photon: marking manifest sha256:773efceb22b4f7844f8d1d6ed2e43a2a79130f66647144eb74f07f21cad43d22 
project031585122252/vmware/photon: marking blob sha256:9e2c9d5f44efbb6ee83aecd17a120c513047d289d142ec5738c9f02f9b24ad07
project031585122252/vmware/photon: marking blob sha256:67b38845fad17e2bc52920dabbc7324b676262cc7671ffa3ac2b8a44625bb734
project031585122441/tomcat
project031585122441/tomcat: marking manifest sha256:a20a17236a2393610637906ad3f0d05c260a8bd665b065ca3d09385971cd7eba 
project031585122441/tomcat: marking blob sha256:ed94f55483b8ee076a1ee5c395a1337e9743699e73f7d40d22048ef5dc3fc7ea
project031585122441/tomcat: marking blob sha256:146bd6a886182fde06fbf747470b1c89814bc8ab1c96fdf1aef6107171959fe6
project031585122441/tomcat: marking blob sha256:9935d0c62ace92b388be202275e222007d6cac10b9c1f2c1ea63af38c09ea7ab
project031585122441/tomcat: marking blob sha256:db0efb86e80601b5bbdbb7c406426982c4202d339687c14c3941b364527e2249
project031585122441/tomcat: marking blob sha256:e705a4c4fd310b96bfb3d7928428e65f0d3f5bad0cd0bda1434aee1d89418468
project031585122441/tomcat: marking blob sha256:3d3bf7f7e874cd48fbdc9e46465264782687a52022f502b1e5eaf5f73287a877
project031585122441/tomcat: marking blob sha256:49371c5b9ff6f6c17a499d1b67b8aeec23280d3e4afb38e85074923ebe6ed90e
project031585122441/tomcat: marking blob sha256:e7873a7ca0fd67b2ad5624aa9efabd6eac45a5da640eb1030a78156b046faa1e
project031585122441/tomcat: marking blob sha256:925a95344b57ac6bff29cfdbaf7d5a1cefd9d40100a47bfdce7a813d24404b47
project031585122441/tomcat: marking blob sha256:0448a86618dafd758dba2b62472cfa4ef3e92a74f11220f1b5a5e295809400ac
project031585122441/tomcat: marking blob sha256:71917b8caadab16b4aad504b0a4a95a645092fdff6900be433e03f5a9282f865
project031585122641/redis
project031585122641/redis: marking manifest sha256:0e67625224c1da47cb3270e7a861a83e332f708d3d89dde0cbed432c94824d9a 
project031585122641/redis: marking blob sha256:f7302e4ab3a81ad2d8033bc0088e5c335e7f046870f76728286bfb3fb17b3221
project031585122641/redis: marking blob sha256:1ab2bdfe97783562315f98f94c0769b1897a05f7b0395ca1520ebee08666703b
project031585122641/redis: marking blob sha256:966bc436cc8b415efa8b2bb2da5a7af612edbdcf2e08d1a5cf9455a2294e9eb6
project031585122641/redis: marking blob sha256:c1b01f4f76d9b86e740fe51d3477de3804d14e594b8c729d8b6a3bf9a378c567
project031585122641/redis: marking blob sha256:8a9a85c968a2d3858c6e49f4aa5695843039d1b5dcacf5181442e89f8f502925
project031585122641/redis: marking blob sha256:8e4f9890211f3dd5f7dd6c84b54cdfd65c79195d1cbf6ccd7b4ddb3d50a885c4
project031585122641/redis: marking blob sha256:93e8c2071125a94ed25a83290f9ea39655b6230b4e2c2760d37be58b58829f7f
project031585122750/mariadb
project031585122750/mariadb: marking manifest sha256:b5e273ed46d2b5a1c96bf8f3ae37aa5e90c6c481e7f7ae66744610d7df79cbd1 
project031585122750/mariadb: marking blob sha256:c1c9e6fba07af64bb1bf9c2e67e46755ec0072683d65144537c5d48ca84333d2
project031585122750/mariadb: marking blob sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
project031585122750/mariadb: marking blob sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
project031585122750/mariadb: marking blob sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
project031585122750/mariadb: marking blob sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
project031585122750/mariadb: marking blob sha256:215d801d026333c9167f6adfe47166d4f0c4c0d2b42bba8e8e0a04a87474427f
project031585122750/mariadb: marking blob sha256:59feacde9e0873f2f58c384307f211f814237a4e0ad7a2e1b024a354cf6edac3
project031585122750/mariadb: marking blob sha256:741aa98d779c1bb98e2f8b7fff2d11ef6b25fe63f81d3558d78545f16e6fbbe3
project031585122750/mariadb: marking blob sha256:e3f771d07df1b6b9589bbb07de679a21b2283402a22cd26f549d7302be7e5f61
project031585122750/mariadb: marking blob sha256:38be307a8063d66ba338584a8c466192d55c3c30eadd9726990b47e35168a2be
project031585122750/mariadb: marking blob sha256:5ef9df553f6df85d27ed451a3131bfad6ec9fc17194d218541ea03b1f98001c1
project031585122750/mariadb: marking blob sha256:3917045a480257d1965bee909926cc87f6d6149c1857057447f61899f1288035
project031585122750/mariadb: marking blob sha256:2635016646c968783dd9f5839d7ce53de7d091aa1a6c4af2624e9315198d6406
project031585122750/mariadb: marking blob sha256:50f7a0ab1439f46a5f2b42eac72b0665773bdef18fe9ca77bdbe8f09886fa78e
project031585122750/mariadb: marking blob sha256:1beaf4bb59c1b542119be53b757b52b6d1ed9a1ca95488a1f4b63dbc466dae8e
project031585123310/mariadb
project031585123310/mariadb: marking manifest sha256:b5e273ed46d2b5a1c96bf8f3ae37aa5e90c6c481e7f7ae66744610d7df79cbd1 
project031585123310/mariadb: marking blob sha256:c1c9e6fba07af64bb1bf9c2e67e46755ec0072683d65144537c5d48ca84333d2
project031585123310/mariadb: marking blob sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
project031585123310/mariadb: marking blob sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
project031585123310/mariadb: marking blob sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
project031585123310/mariadb: marking blob sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
project031585123310/mariadb: marking blob sha256:215d801d026333c9167f6adfe47166d4f0c4c0d2b42bba8e8e0a04a87474427f
project031585123310/mariadb: marking blob sha256:59feacde9e0873f2f58c384307f211f814237a4e0ad7a2e1b024a354cf6edac3
project031585123310/mariadb: marking blob sha256:741aa98d779c1bb98e2f8b7fff2d11ef6b25fe63f81d3558d78545f16e6fbbe3
project031585123310/mariadb: marking blob sha256:e3f771d07df1b6b9589bbb07de679a21b2283402a22cd26f549d7302be7e5f61
project031585123310/mariadb: marking blob sha256:38be307a8063d66ba338584a8c466192d55c3c30eadd9726990b47e35168a2be
project031585123310/mariadb: marking blob sha256:5ef9df553f6df85d27ed451a3131bfad6ec9fc17194d218541ea03b1f98001c1
project031585123310/mariadb: marking blob sha256:3917045a480257d1965bee909926cc87f6d6149c1857057447f61899f1288035
project031585123310/mariadb: marking blob sha256:2635016646c968783dd9f5839d7ce53de7d091aa1a6c4af2624e9315198d6406
project031585123310/mariadb: marking blob sha256:50f7a0ab1439f46a5f2b42eac72b0665773bdef18fe9ca77bdbe8f09886fa78e
project031585123310/mariadb: marking blob sha256:1beaf4bb59c1b542119be53b757b52b6d1ed9a1ca95488a1f4b63dbc466dae8e
project031585123443/mariadb
project031585123443/mariadb: marking manifest sha256:b5e273ed46d2b5a1c96bf8f3ae37aa5e90c6c481e7f7ae66744610d7df79cbd1 
project031585123443/mariadb: marking blob sha256:c1c9e6fba07af64bb1bf9c2e67e46755ec0072683d65144537c5d48ca84333d2
project031585123443/mariadb: marking blob sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c
project031585123443/mariadb: marking blob sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff
project031585123443/mariadb: marking blob sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1
project031585123443/mariadb: marking blob sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4
project031585123443/mariadb: marking blob sha256:215d801d026333c9167f6adfe47166d4f0c4c0d2b42bba8e8e0a04a87474427f
project031585123443/mariadb: marking blob sha256:59feacde9e0873f2f58c384307f211f814237a4e0ad7a2e1b024a354cf6edac3
project031585123443/mariadb: marking blob sha256:741aa98d779c1bb98e2f8b7fff2d11ef6b25fe63f81d3558d78545f16e6fbbe3
project031585123443/mariadb: marking blob sha256:e3f771d07df1b6b9589bbb07de679a21b2283402a22cd26f549d7302be7e5f61
project031585123443/mariadb: marking blob sha256:38be307a8063d66ba338584a8c466192d55c3c30eadd9726990b47e35168a2be
project031585123443/mariadb: marking blob sha256:5ef9df553f6df85d27ed451a3131bfad6ec9fc17194d218541ea03b1f98001c1
project031585123443/mariadb: marking blob sha256:3917045a480257d1965bee909926cc87f6d6149c1857057447f61899f1288035
project031585123443/mariadb: marking blob sha256:2635016646c968783dd9f5839d7ce53de7d091aa1a6c4af2624e9315198d6406
project031585123443/mariadb: marking blob sha256:50f7a0ab1439f46a5f2b42eac72b0665773bdef18fe9ca77bdbe8f09886fa78e
project031585123443/mariadb: marking blob sha256:1beaf4bb59c1b542119be53b757b52b6d1ed9a1ca95488a1f4b63dbc466dae8e
project031585123583/hello-world
project031585123583/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585123583/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585123583/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585124518/hello-world
project031585124518/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585124518/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585124518/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585125388/busybox
project031585125388/busybox: marking manifest sha256:679b1c1058c1f2dc59a3ee70eed986a88811c0205c8ceea57cec5f22d2c3fbb1 
project031585125388/busybox: marking blob sha256:020584afccce44678ec82676db80f68d50ea5c766b6e9d9601f7b5fc86dfb96d
project031585125388/busybox: marking blob sha256:0f8c40e1270f10d085dda8ce12b7c5b17cd808f055df5a7222f54837ca0feae0
project031585125782/hello-world
project031585125782/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585125782/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585125782/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585126181/hello-world
project031585126181/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585126181/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585126181/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
project031585126504/hello-world
project031585126504/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
project031585126504/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
project031585126504/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
public031585124904/hello-world
public031585124904/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
public031585124904/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
public031585124904/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced
test031585124968/hello-world
test031585124968/hello-world: marking manifest sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a 
test031585124968/hello-world: marking blob sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
test031585124968/hello-world: marking blob sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced

63 blobs marked, 77 blobs and 0 manifests eligible for deletion
blob eligible for deletion: sha256:597c87082c114f1e78cf07db96e69306d6771ce8fe5f72cecb82a5c724c1bd9f
blob eligible for deletion: sha256:8a0637ca1ac98db4cf29f7632449c92801adc80cf0da2cd9c9e39882ce466561
blob eligible for deletion: sha256:afb25d7b78d81dd0166c9f510bfa7a1f7071fdecd5fe846ebfb2a6d691828c05
blob eligible for deletion: sha256:e25900e2a7f96a6326b79ec6dfdce1ac5461c7a961fb3752ec1770cd82b8d03c
blob eligible for deletion: sha256:e9e3c043ec689651a0d36c0ec99c38a8b2fabd1126bf07ca3add42ec3d6d0ac7
blob eligible for deletion: sha256:f338bc35613f66cfaad272234de7b77a91d6c5422855bf6239f2b0ff9d73f0a4
blob eligible for deletion: sha256:08c2ebb11ba5d423d76bddaf822705aab352824489e9d6c4e1e09414a5635910
blob eligible for deletion: sha256:18d287a2191c4ae3309a5243f9d80aed4a286f00d0259485e24a3dd3658751aa
blob eligible for deletion: sha256:f7079338b6e3ad99995bfa7c319ea9d289c9d32efc389625079b53fddb7b274d
blob eligible for deletion: sha256:4fe1c0ecf89b84d70170b9ed1e4dcd2eaf0943711183fadfa055034ecc0ca1b4
blob eligible for deletion: sha256:61ed6712c0f138b33db030687fad65c362891b450eeb1a9d5775dfbc524dbf98
blob eligible for deletion: sha256:7a2b5d8e22d1e14003926fd10a36840dd922e09875dc573143398a69996c8f9b
blob eligible for deletion: sha256:bc1c99f4ba60de0d3ca52dc6855483e24c91884e33df71f502bbff6eb909d9b9
blob eligible for deletion: sha256:1ebf0e70c6bafcefa1d24df9217c3fa17182807e9a69e6502b9d08a74a5945b2
blob eligible for deletion: sha256:382fb8a7e67f496c473ce35bbb5fd96ac8289ba01da51b0cf79c9134702e4afb
blob eligible for deletion: sha256:cb8a924afdf0229ef7515d9e5b3024e23b3eb03ddbba287f4a19c6ac90b8d221
blob eligible for deletion: sha256:80f1ddb594ce7242775b62baf91e85dcc296b36244309dc2aa0023f2d452db79
blob eligible for deletion: sha256:ac36f12abe8fdc6dbcbe5af0432962a38a8d3cce0e926dd3ddec3b9f75300df2
blob eligible for deletion: sha256:8b3e52d9242854f547542ff52d1019285ebb93414a6ba86691c2a30b7ea4db75
blob eligible for deletion: sha256:954eb9d35fd6ab9717942de3097d5ed5f67f84578a998c935357276ce2fe0c9d
blob eligible for deletion: sha256:a187dde48cd289ac374ad8539930628314bc581a481cdb41409c9289419ddb72
blob eligible for deletion: sha256:aad63a9339440e7c3e1fff2b988991b9bfb81280042fa7f39a5e327023056819
blob eligible for deletion: sha256:bb1676b16791346523c3ade56c278169f01cbf075725f7b505c05529b694f64e
blob eligible for deletion: sha256:da4c70250b800037b3507bf2063f2fe8313a1a4333f21adf5a985c2c9ec6cf72
blob eligible for deletion: sha256:091d6d504ae74c9ac75f36d55e331d02196d34758e89746c7ffc52b230b9ee59
blob eligible for deletion: sha256:64719a336a24e8a6d930335b5c3036ba3d1a4d8aec929d9f7150d1cc7e41effd
blob eligible for deletion: sha256:f1aff18a7013dece1ddcb7d5de7432fb942ec04d316918116e8f4e85841fd2c1
blob eligible for deletion: sha256:a58fa8abd6e5fd6cd61f5f5d28ad868fc08c72f28115fe26e60a0b816396b9ac
blob eligible for deletion: sha256:1d820e29c4c3cad56c52f9d3bd88c1881e76c04bf346929a74ea7f676d3c9553
blob eligible for deletion: sha256:43f6a4398e1c9e860dfb5c93d7049ab9eedf814513bd6d07e06077c560303c7a
blob eligible for deletion: sha256:4a70e15859d4aecd037423529f5aa72bd7894e0ef54508bf794463ad3eb0fb60
blob eligible for deletion: sha256:975241fcd2057cc8f4cb8f066d68ed18877152b88da11e682911ccc3bc3da7c4
blob eligible for deletion: sha256:04d04970e33c492fa411b508455d02a85978492db0403b8a714f365432c04f1c
blob eligible for deletion: sha256:48983962b8f5ed83191ee21936de26c963474c59f4cde8bdee512497a7f1dc66
blob eligible for deletion: sha256:b276d875eeed9c7d3f1cfa7edb06b22ed22b14219a7d67c52c56612330348239
blob eligible for deletion: sha256:c5ea49127cd44d0f50eafda229a056bb83b6e691883c56fd863d42675fae3909
blob eligible for deletion: sha256:0776aeec3430c5a5ba3f43937f0ee6a7770a1fe81a318c9d94cc76512e5375e9
blob eligible for deletion: sha256:35c117514f9901b0a3e44fdefbbd1e0d7c67d41714443fa5da1e40ae86721aaa
blob eligible for deletion: sha256:dd6b8c4ba5b8bf50f87196be66ee8710d054d0e5c5607493c2e9b59a369db366
blob eligible for deletion: sha256:68ced04f60ab5c7a5f1d0b0b4e7572c5a4c8cce44866513d30d9df1a15277d6b
blob eligible for deletion: sha256:bc6ed541d5bbd977fd22fd589104159d10a22d7818368a8c79791ab0a3436cdb
blob eligible for deletion: sha256:452f204f05aae9837957231219a5d48e346220f0ac71874632109c1f8be49b9e
blob eligible for deletion: sha256:9cb6e30e72ca48836d0b42b3fb222949c352c292f296a18d9fff9b21dd678c4d
blob eligible for deletion: sha256:31eef31f6d1d942c7d608464c5109c6d45839220a3d390efe1e0bc9c2347678a
blob eligible for deletion: sha256:37f5f0a258bf77afe2010d7400fd87a07ddd1b619d5fb45858f4bad1dd480aef
blob eligible for deletion: sha256:50698da392fbf44a46c939f69bf0630c626982eeb776df8abdf6c57b09b7c6ca
blob eligible for deletion: sha256:60890c0035d847e17e4b46bcb18bc9082f25cd9524e0af0848a76e85f54fbb30
blob eligible for deletion: sha256:aa55e810a20d239d95a69d5da4bc7f894261882f9e7ce89284f80a54f0377cd7
blob eligible for deletion: sha256:d3c99e51e960b9a4e4276ca76499ccea6a477e6906358fe1bd42e891722d5c7b
blob eligible for deletion: sha256:d9bf605ce3d4449f4b90035c3e21d691806324781d43a5287b1da25a01779d6b
blob eligible for deletion: sha256:fc3a251cdf5c2dfbdf7e36ba610c475e4893eaf18dee50e5205fbc4b8a050945
blob eligible for deletion: sha256:141e45c6af4bfa80295fe6fe19f3a76fd69f260eafeca26bc9b625b89fdfc3ef
blob eligible for deletion: sha256:1de10f1ae2a5bfd5f34f19421ebd282580e443321e4947cdf5f943875782b018
blob eligible for deletion: sha256:842db5c820b72e078691118de1791c9baa15ba09c87235e70990186ac0f825de
blob eligible for deletion: sha256:ba380812d45c01e7e1a0b2381cee9d88568aa727732c9a3b23dd1d92141266d9
blob eligible for deletion: sha256:46b58b90a56e9a71a97e019f7c0934d96a9a1f757fbb0f2916636ee91587dc9f
blob eligible for deletion: sha256:5bed26d33875e6da1d9ff9a1054c5fef3bbeb22ee979e14b72acf72528de007b
blob eligible for deletion: sha256:c7bcd9961bee1d541ab21b169b9d8e826a8d7abccfca865c7ea9727bf6bbfd87
blob eligible for deletion: sha256:0647ec428f9f62cf956bd7c8f0fec090b25cc7260e67e7fd84673bf05d9f7b2b
blob eligible for deletion: sha256:40ccaf895c8a33b8c6e3bc1d8065e4ef31442809d70d3eaefa1fc2899f91540e
blob eligible for deletion: sha256:930bda195c84cf132344bf38edcad255317382f910503fef234a9ce3bff0f4dd
blob eligible for deletion: sha256:ca1c6795bfb97df28a926fd646127ba4944b69beb1cea7b00d62787b8b3c0108
blob eligible for deletion: sha256:78bf9a5ad49e4ae42a83f4995ade4efc096f78fd38299cf05bc041e8cdda2a36
blob eligible for deletion: sha256:8092eb0cb942d030c7f142501fdc2268f882794bfc4874ede3b9c0317597ef6d
blob eligible for deletion: sha256:d47df81a64bf203c9452e452aeba7aa6e6ec311361c796f82ec05dc350892a21
blob eligible for deletion: sha256:e4f687f868687d81d13df99e9eda0fbb48f1dfbda3817a023c5323a25347b2df
blob eligible for deletion: sha256:2f364b8f1744a448ff1cd22d9487b95a4d2ca9a8d6b2f5e0a185807aa798fa62
blob eligible for deletion: sha256:3c43274064ab51a31f9c534aad1cfb795aaea0d26ac36cf2d6f08d2cd022f6d8
blob eligible for deletion: sha256:a85b7dc939850681b5236be87f257ff22f45a2c439e646d11a9122fa2b57dbc2
blob eligible for deletion: sha256:fff3167bf8c79dc08baf67eb607823aadcbee2033f9620cc502e2c49423f605b
blob eligible for deletion: sha256:2d665f60c94a9bce6313853ec27d3e977394c13196fc732ee44aca2de166f26e
blob eligible for deletion: sha256:2ee122dcc32de080998a9e1ab8665445f621cd323d3ce6bdea2b8a58a921f312
blob eligible for deletion: sha256:8effa8e8816b285d717419a7923ebcb581e08e1eb6d481dac1c989703f6a72ad
blob eligible for deletion: sha256:a26245908a82e62155c2d10d7b7152341c5172f259020f17dd5ca186c5736c30
blob eligible for deletion: sha256:f11b29a9c7306674a9479158c1b4259938af11b97359d9ac02030cc1095e9ed1
blob eligible for deletion: sha256:0d8bd234c4c84739c3b7a6386e80bd2e65b6dc52d8870a31e75eaa7233217c9d
blob eligible for deletion: sha256:597bd5c319cc09d6bb295b4ef23cac50ec7c373fff5fe923cfd246ec09967b31
, start: 2020-03-25 09:00:48.897874611 +0000 UTC, end: 2020-03-25 09:00:50.1551698 +0000 UTC.
2020-03-25T09:00:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:114]: success to run gc in job.

**Comment by reasonerjt** [comment]
This is working as designed.
