### ISSUE TITLE
The GET /api/v2.0/scans/schedule/metrics request is sent continually after setting schedule scan

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#11289]
Set the scan all runs weekly, refresh the page:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/5835782/77602564-c87a2d00-6f48-11ea-8eaf-21d1d2081213.png">

**Comment by reasonerjt** [comment]
I guess this is the design.  the `metrics` api is also used to check the status of the scan all job.

**Comment by heww** [comment]
This API is used to get the progress of the scan all job. And it should be requested only when the scan al job is running.

**Comment by jwangyangls** [comment]
I cannot  understand

**Comment by reasonerjt** [comment]
The status of Metric api should be updated and UI should behave according to the status.
