### ISSUE TITLE
harbor 2.0 slack webhook should consider API rate limit

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11281]
And when using slack, we should consider the API rate limit, maybe add some cache to group the message help

This error maybe relative rate limit
![image](https://user-images.githubusercontent.com/188115/77526997-67aa1080-6ec6-11ea-9038-ed6efb564fcd.png)

But error code is not 409, according to the doc
https://api.slack.com/docs/rate-limits

**Comment by reasonerjt** [comment]
Is there a way to augment the quota in Slack?

Another to mitigate the issue, could we explicitly set the job not to retry if it's sending notification in Slack?

**Comment by mmpei** [comment]
i will check this scenario and try to make the webhook more graceful to slack.
and nowdays i think it is not an issue because harbor will retry after a backoff interval time when error occurs.

**Comment by wy65701436** [comment]
Doc for reference: https://api.slack.com/docs/rate-limits

**Comment by renmaosheng** [comment]
@mmpei @wy65701436 could we have some discussion in next community meeting?

**Comment by steven-zou** [comment]
@mmpei 

For controlling the speed of sending messages to the slack, you can try to use the `Scheduled` job which is executed after the given time.

With this idea, you can use a base timestamp as a lock, a lock of the timestamp that indicates the triggering time of last job should be acquired before firing the next job. Then the jobs will be sequenced.

e.g.: 
t0=1000
t1=1002
t2=1003
...

**Comment by wy65701436** [comment]
close it as https://github.com/goharbor/harbor/pull/11623 merged.
