### ISSUE TITLE
[RobotAccount] Allow additional scopes to be provided to Robot accounts.

### ISSUE THREAD

**Issue by DandyDeveloper** [goharbor/harbor#11286]
**Is your feature request related to a problem? Please describe.**
We have a resource in our CI that labels images/charts as they are deployed in environments. This works fine when using a user account. However, we want to move to OIDC and start using Robot accounts. 

The Robot account works perfectly for pushing/pulling an image but unfortunately gets a 403 as expected when trying to trigger label changes. 

**Describe the solution you'd like**
Right now, we only have a set amount of defined roles: 

```sql
 role_id | role_mask | role_code |     name     
---------+-----------+-----------+--------------
       1 |         0 | MDRWS     | projectAdmin
       2 |         0 | RWS       | developer
       3 |         0 | RS        | guest
       4 |         0 | DRWS      | master
       5 |         0 | LRS       | limitedGuest
       6 |         0 | LRS       | limitedGuest
```

I think Harbor may benefit from having a `scopes` table that defined the access rights that can be applied to Robot accounts, then potentially extended to user roles. It will allow more granularity on user access, but also solve my specific problem I'm experiencing.

**Describe the main design/architecture of your solution**
As above, adding a a scopes table, which I believe already exist in the code, would enable better access management overall for individual users, but more importantly for Robot accounts. 

`scopes` relation `id` would be referenced as a FK in `roles` and roles in `harbor_user`. Right now, Harbor just has "User" or "Admin", but extending this would be really good for enterprises. 

Those scopes can be references in the JWT of the robot, Harbor already has these checks for robot accounts: 

```json
  "access": [
    {
      "Resource": "/project/2/repository",
      "Action": "push",
      "Effect": ""
    },
    {...}
```

**Challenges**
The biggest challenge is agreeing on the scopes: It could be as simple as what exists as roles right now "user" and "admin" etc. and introducing more complicated scopes in future. 

**Describe the development plan you've considered**
None at the moment, I might have a go at the PR for this if I get a chance.

**Comment by xaleeks** [comment]
I think that's a great idea and we've talked in the past about user defined roles that allows very extreme granular control over their actions on Harbor.  will look into this.

**Comment by DandyDeveloper** [comment]
Just to add onto this, explicitly granting access to the API is fundamental to making this work. I know we produce a token for robot accounts, but perhaps having a login secret to generate tokens would be more apprioriate?

**Comment by xaleeks** [comment]
https://github.com/goharbor/community/pull/148

**Comment by wy65701436** [comment]
We can close it as the robot enhancement is introduced in v2.2, just try with https://github.com/goharbor/harbor/releases/tag/v2.2.0-rc1.
