### ISSUE TITLE
Webhooks select what action would like to be triggered 

### ISSUE THREAD

**Issue by jbiancot** [goharbor/harbor#11293]
When setup the Webhook, it would be great if the Web UI allows the end-user to select what actions you would like to trigger, instead of be “trigger all”, E.g: enable when imagePull but not imagePush, etc. like events “checkboxes”. That way the API endpoint doesn’t get call/trigger on every action.

**Comment by renmaosheng** [comment]
mingming/Alex,
       Could you please take a look at this issue? thanks.

**Comment by wy65701436** [comment]
@jbiancot this feature will be supported in Harbor v2.0, and all of events are selectable when setup a webhook endpoint.

**Comment by wadefelix** [comment]
> @jbiancot this feature will be supported in Harbor v2.0, and all of events are selectable when setup a webhook endpoint.

Could disable the imagePull events now?
then enable it in v2.0.

**Comment by xaleeks** [comment]
this is now possible in v2.0, check docs on goharbo.io on instructions, and feel free to reopen if you're having trouble configuring on harbor web console
