### ISSUE TITLE
The scan result is gone after upgrading from 1.9.4 to 2.0

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#11290]
After upgrading from 1.9.4 to 2.0, the UI shows "Not Scanned"

**Comment by heww** [comment]
I will close this issue, for it will be tracked in https://github.com/goharbor/harbor/issues/11310

**Comment by xaleeks** [comment]
is this the same issue as https://github.com/goharbor/harbor/issues/11376? @ywk253100
