### ISSUE TITLE
harbor 2.0 migrator not work for 1.10

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11298]
harbor 2.0, build 3166

![image](https://user-images.githubusercontent.com/188115/77620252-e78eb400-6f74-11ea-8f6c-6dd9d8be116a.png)

**Comment by bitsf** [comment]
Or delete this old harbor-migrator, that user would have to use the new prepare migrator

**Comment by ninjadq** [comment]
fixed in #11381
