### ISSUE TITLE
harbor 1.8.0 migration 1.9.4 , the page display confusion

### ISSUE THREAD

**Issue by Ethan-2017** [goharbor/harbor#11297]
![image](https://user-images.githubusercontent.com/31506919/77617468-39ccd680-6f6f-11ea-9422-86f8f6119101.png)
![image](https://user-images.githubusercontent.com/31506919/77617493-48b38900-6f6f-11ea-8805-75db64ad4d36.png)

**Comment by bitsf** [comment]
it maybe browser cache, try refresh or clean cache

**Comment by jwangyangls** [comment]
I agree with bistsf, try refresh or clean cache.
