### ISSUE TITLE
Documentation lacks WebHooks details

### ISSUE THREAD

**Issue by jbiancot** [goharbor/harbor#11292]
I think the Documentation should include what to expect when setup the WebHooks, it is not clean it would send information about the events triggered on JSON; response headers, payload fields, etc.

**Comment by xaleeks** [comment]
This is a valid point, please add above to the docs @wy65701436 @mmpei

**Comment by xaleeks** [comment]
documented here now : https://github.com/goharbor/harbor/pull/11910
