### ISSUE TITLE
replication not work after upgrade 2.0 from 1.10, because we only support replicate between both 2.0 harbor

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11302]
1. install harbor 1.10
2. add remote registry name harbor1
3. add replication rule, pull from harbor1, with repo "library/**"
4. add schedule run
5. upgrade to 2.0
6. find schedule not run anymore, and edit rule also fail with "internal error", http 500

![image](https://user-images.githubusercontent.com/188115/77622630-946b3000-6f79-11ea-9008-a861b69f6f54.png)

**Comment by bitsf** [comment]
This error should because the origin target harbor version is old(1.8) than 2.0, and current design is we can only replicate between 2.0 harbors

**Comment by bitsf** [comment]
I think this is not good, we should make sure backward compatibility.
Maybe a good design is add a new harbor replication adapter to support 2.0 and change old harbor adapter to harbor legacy adapter

**Comment by reasonerjt** [comment]
I don't think it's realistic to make replication support cross versions, but why that 500 happens?

When you editing the rules do you call the remote server?  Just make it not call the remote should fix this?

**Comment by bitsf** [comment]
The replication rule even can not be deleted.

**Comment by ywk253100** [comment]
> The replication rule even can not be deleted.

Got error when try to delete the rule:
```
Mar 26 21:56:28 192.168.16.1 core[1562]: 2020-03-26T13:56:28Z [ERROR] [/server/error/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to delete the policy 2: http error: code 500, message {\"code\":10006,\"message\":\"stop job failed with error\",\"details\":\"no valid periodic job policy found: cd23c9b925a88e4412ebafd3:1585190167\"}"}]}
```

**Comment by ywk253100** [comment]
> The replication rule even can not be deleted.

This is fixed by https://github.com/goharbor/harbor/pull/11309

**Comment by bitsf** [comment]
current fix not enough
![image](https://user-images.githubusercontent.com/188115/77715475-a7800d80-7016-11ea-9421-35514d576bf1.png)

**Comment by reasonerjt** [comment]
In this case UI should display a more friendly error to tell user the version mismatch,

**Comment by xaleeks** [comment]
I don't think we want to get in the habit of officially _supporting_ replication between different versions.  We want to push users to use the same version of Harbor and I'd rather we spend effort on a better upgrade experience.  In the future when we have multi node harbor clusters, we will perform rolling upgrades that ends with all harbor instances being of the same version.  It is the source of much headache in hypervisor replications, and even though different versions of esxi are supported, the vCenter servers fronting the esxi hosts need to be the same version. 

Ofc, we're open to hearing suggestions and why it's absolutely necessary to replicate btw different versions of Harbor

**Comment by bitsf** [comment]
When replicate from 2.0 to 1.x, if artifact is a manifest list, it will fail as 1.x not support such manifest.
![image](https://user-images.githubusercontent.com/188115/79822831-b1eab880-83c4-11ea-84dc-c13cea1012b3.png)
