### ISSUE TITLE
Fail to run GC

### ISSUE THREAD

**Issue by jilleJr** [goharbor/harbor#11307]
Using harbor deployed via helm to a k8s cluster.
- Harbor version v1.10.0-6b84b62f
- CHART harbor-1.3.0
  - APP VERSION 1.10.0
  - REPO https://helm.goharbor.io
  - Our helm values: https://pastebin.com/VBjTc0H7
- Kubernetes server: v1.15.3

We can't run GC, neither via the web UI nor by running `registry garbage-collect --delete-untagged=true /etc/registry/config.yml` on the registryctl container. We've also found that none of our scheduled GC jobs has succeeded.

Here's a log from a scheduled GC job, taken from the jobservice pod:

```bash
❯ kubectl exec harbor-harbor-jobservice-794869d89f-7t8p2 -it sh
sh-4.4$ cat /var/log/jobs/421cbd9d357d232587f02a9d@1584576000.log
2020-03-19T00:00:01Z [INFO] [/jobservice/job/impl/gc/job.go:87]: start to run gc in job.
2020-03-19T00:00:07Z [ERROR] [/jobservice/job/impl/gc/job.go:90]: failed to get gc result: Failed to start GC: 500
```

We also receive the same two-lined log as above when starting the GC via the web interface.

When running via the commandline on the registryctl we get a little more verbose result.
(Running command as suggested in #7945)

```bash
❯ kubectl exec -it harbor-harbor-registry-586494c695-wtvwp --container registryctl bash
harbor [ / ]$ registry garbage-collect --delete-untagged=true /etc/registry/config.yml
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-
-redacted image name-: marking manifest sha256:d8835997bf0ed67701f13e12348b43f71ba2d0f7b1fd9f85032b4c5253772405
-redacted image name-: marking blob sha256:0a767b7adcf89dd7bf534738574930446bba47ac3c04c8384799a582bedaa26e
-redacted image name-: marking blob sha256:804555ee037604c40de144f9f8da0d826d38db82f15d74cded32790fe279a8f6
-redacted image name-: marking blob sha256:970251047358aea56ba6db6975b14ff12470b75de0c2477f4445240ddd727fd4

/snip about +7000 lines/

-redacted image name-: marking blob sha256:3dc99f571daf389aed6ca12c817635c5ba32eaf47020b5c7a72b494bf3c9b213
-redacted image name-: marking blob sha256:884ea3f64c14a775dbf7fb3c204fb4c84d9545367dde0b7fce227e89e836448a
-redacted image name-: marking blob sha256:c54009433f6afbb992f9e0ba819cc7372eab036b331aabbb4b00c7b5139d765f

4497 blobs marked, 6784 blobs and 0 manifests eligible for deletion
blob eligible for deletion: sha256:560a996ff7b713f6b1400715e0ef002f3103362d7dcdf036527a38a101ffc1c2
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/56/560a996ff7b713f6b1400715e0ef002f3103362d7dcdf036527a38a101ffc1c2  go.version=go1.12.12 instance.id=4c2347d9-50c2-47d4-a363-f2f9d6105ab4 service=registry
failed to garbage collect: failed to delete blob sha256:560a996ff7b713f6b1400715e0ef002f3103362d7dcdf036527a38a101ffc1c2: filesystem: Path not found: /docker/registry/v2/blobs/sha256/56/560a996ff7b713f6b1400715e0ef002f3103362d7dcdf036527a38a101ffc1c2
harbor [ / ]$ echo $?
1
```

That hash it's referencing, `560a996ff7b713f6b1400715e0ef002f3103362d7dcdf036527a38a101ffc1c2`, never appears in the snipped logs.

I don't know where to look for more logs. Need help to figure out how to get past this.

Small extra detail: Our harbor is now full (filled up 40 GiB out of 40 GiB of the persistent volume) but and garbage collecting looks like a nice way of fixing this. But the garbage collection didn't work even before it got full. We just now noticed it 😂

Kind regards,
Kalle

**Comment by bitsf** [comment]
you may try use the native registry command for workaround first.
docker exec -it -u harbor registry registry garbage-collect --delete-untagged=true /etc/registry/config.yml

**Comment by jilleJr** [comment]
Status update:

Just looked in the filesystem inside the `registry` container (with the mounted PV) and it's not found inside the  
`/storage/docker/registry/v2/blobs/sha256/56/`  
folder as expected, but there is a folder at  
`/storage/docker/registry/v2/blobs/blobs/sha256/56/` that DOES contain it.

Weird how there's two storages for all the blobs. Maybe a relic from an update or if someone had changed the path from our end. No clue.
Searching the two storages `v2/blobs/sha256` and `v2/blobs/blobs/sha256` we found that the latest edited file in blobs were from today (2020-04-20) while latest edited file in blobsblobs were from late december (2019-12-17 something). 

We did a full diff of all the files and there were no collisions (according to `comm`)

```sh
cd /storage/docker/registry/v2/blobs/sha256
find . -type f > ~/blobs.txt

cd /storage/docker/registry/v2/blobs/blobs/sha256
find . -type f > ~/blobsblobs.txt

comm -12 ~/blobsblobs.txt ~/blobs.txt
# no output ==> no collisions
```

So given that there were no collisions we felt secure in the attempt to merge these two freely since we have the log of which files belongs to which folder.

We ran the following:

```sh
cd /storage/docker/registry/v2/blobs/blobs
find . -type f | while read -r x; do mkdir -pv ../$(dirname $x); mv -v $x ../$x ; done
```

With popcorn and stressballs in hand, we then attempted the GC anew by running it on the registryctl container.

👌 And it succeeded 🤘

---

Maybe there's a way for you "team harbor" to implement an extra check to not make it error here and figures out how to complete the GC anyway but this seems more like some edge case where we somehow messed up our storage, and not the fault of harbor itself.

Thanks for making such a great product!
Closing as we've no issue with this anymore.
