### ISSUE TITLE
harbor2.0 Robot account not work

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11317]
build 3166

![image](https://user-images.githubusercontent.com/188115/77647208-fa1ee280-6fa0-11ea-92cd-f0a6925e1621.png)

![image](https://user-images.githubusercontent.com/188115/77647330-26d2fa00-6fa1-11ea-9f24-d268afdea4d9.png)

private repo
![image](https://user-images.githubusercontent.com/188115/77647607-a9f45000-6fa1-11ea-94e0-18756a3ec86c.png)

**Comment by bitsf** [comment]
docker pull also failed
![image](https://user-images.githubusercontent.com/188115/77648338-f68c5b00-6fa2-11ea-8fa4-d4b216545792.png)

**Comment by bitsf** [comment]
The basic auth not work when docker pull
![image](https://user-images.githubusercontent.com/188115/77648486-2fc4cb00-6fa3-11ea-8eb6-6f1ea4442575.png)

**Comment by wy65701436** [comment]
duplicate with https://github.com/goharbor/harbor/issues/11225
