### ISSUE TITLE
all scan info lose after upgrade from 1.10 to 2.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11310]
build 3166
Because harbor 2.0 use Trivy as the default scanner, after upgrade to 2.0, it will force override the old clair scanner setting.
I can understand use Trivy as default when fresh installation.
But this is a bad user experience after upgrade case.
All old scan info is invalid, and even critical is that user can not pull images if enabled "Prevent vulnerable images from running"

**Comment by reasonerjt** [comment]
We should make sure whatever scanner user chooses we should never update the default scanner.

**Comment by xaleeks** [comment]
I think this is the experience we are looking for (apply to each individual project).  The already configured scanner always has highest priority, even if the upgrade specifies trivy with '--with-trivy'.  Trivy is higher priority than Clair.

The new install / upgrade experience should be like this
Brand New install
On brand new install, customer can pick 
     i. Nothing. In this case no scanner is installed
     ii. “with-trivy”. Trivy is installed and default
     iii. “with-clair”. Clair is installed and default
     iv. “with-clair” and “with-trivy”. Both are installed and Trivy is the default
 
Upgrades
Original Harbor had no scanner configured [this is the same case as for a brand new install]
     i. Nothing. In this case no scanner is installed
     ii. “with-trivy”. Trivy is installed and default
     iii. “with-clair”. Clair is installed  and default
     iv. “with-clair” and “with-trivy”. Both are installed. Trivy is the default

Original Harbor had a scanner X configured 
     i. Nothing. Error out since a scanner was configure pre-upgrade
     ii. “with-trivy”. Trivy is installed. X scanner is default
     iii. “with-clair”. Clair is installed . X scanner is default
     iv. “with-clair” and “with-trivy”.  both are installed. X scanner is default

**Comment by steven-zou** [comment]
@xaleeks 

` Error out since a scanner was configured pre-upgrade`?

What does `Error out` mean? Throw an error when such case happen?
