### ISSUE TITLE
GC schedule job failed after upgrade from 1.10 to 2.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11313]
build 3166

![image](https://user-images.githubusercontent.com/188115/77641221-aad3b480-6f96-11ea-9b33-ac5689350ce2.png)
![image](https://user-images.githubusercontent.com/188115/77641244-b45d1c80-6f96-11ea-9c96-55382be940cd.png)

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/77641612-482ee880-6f97-11ea-8f4d-90407bb3f539.png)

**Comment by wy65701436** [comment]
duplicate with https://github.com/goharbor/harbor/issues/11225

**Comment by steven-zou** [comment]
cause by the statement `gc.deleteUntagged = params["delete_untagged"].(bool)` in GC job.

It then causes a runtime error that is captured by job service runner.

**Comment by steven-zou** [comment]
This issue contains two problems.

For bug in js, use this new issue to track https://github.com/goharbor/harbor/issues/11361
