### ISSUE TITLE
harbor 2.0 retention job delete with a lot ERR

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11316]
build 3166
setup a retention rule which should del all artifacts except 1 immutable, but many failed.

![image](https://user-images.githubusercontent.com/188115/77644952-dfe30580-6f9c-11ea-9824-42145085de1a.png)
![image](https://user-images.githubusercontent.com/188115/77644987-ee312180-6f9c-11ea-9ec8-1534bf1ee360.png)

**Comment by bitsf** [comment]
The failed artifacts are actually displayed twice.
There maybe some problem in list artifacts API

**Comment by bitsf** [comment]
ListAllArtifacts() from core api return a lot of duplicate items.

**Comment by ywk253100** [comment]
@bitsf This should be fixed by https://github.com/goharbor/harbor/pull/11339
Please verify it, tks
