### ISSUE TITLE
[Internal Error] Without install any scanner, get 500 after click the Vulnerability

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11322]
Can we hide the button?

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/2841473/77669361-9bb52c80-6fbf-11ea-9fb7-0655ddc828a2.png">

**Comment by jwangyangls** [comment]
it should not return 500

**Comment by heww** [comment]
@jwangyangls Please ensure that `/api/v2.0/system/scanAll/schedule` and `/api/v2.0/scans/schedule/metrics` APIs only request when there exists scanners in the system.

**Comment by heww** [comment]
Duplicated with #11187
