### ISSUE TITLE
Unable to push to registry after a while (on AWS)

### ISSUE THREAD

**Issue by paulkilla** [goharbor/harbor#11324]
I have an issue occurring on my harbor build in AWS.
The issue is after doing a docker-composer stop/start I am able to use the docker-registry/harbor fully to the extent it is intended by pulling and pushing docker images etc.
This issue comes up after an uncertain amount of time, I am still able to pull images, but when I try to push images I get connection refused.

# Setup
This is on AWS, and I have an ELB (with SSL termination) listening on 443, which then forwards to my harbor instance on port 80.
I have configured Harbor to work in this way by removing the **proxy_set_header X-Forwarded-Proto line in the nginx.conf file** as directed.

# Version of docker engine and docker-compose
**docker:**
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**docker-compose**
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Latest version of harbor installed from releases tab. 

# Configuration files of Harbor
**harbor.yml**

hostname: https://docker.url.here

http:
  port: 80

external_url: https://docker.url.here

harbor_admin_password: ***
data_volume: /efs/harbor

clair:
  updaters_interval: 12

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 1.10.0

external_database:
  harbor:
    host: aws-rds-host-here
    port: 5432
    db_name: harbor
    username: harbor
    password: ***
    ssl_mode: disable
    max_idle_conns: 2
    max_open_conns: 0
  clair:
    host: aws-rds-host-here
    port: 5432
    db_name: clair
    username: harbor
    password: ***
    ssl_mode: disable
  notary_signer:
    host: aws-rds-host-here
    port: 5432
    db_name: notary_signer
    username: harbor
    password: ***
    ssl_mode: disable
  notary_server:
    host: aws-rds-host-here
    port: 5432
    db_name: notary_server
    username: harbor
    password: ***
    ssl_mode: disable

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair

# Log files
local docker logs:
This is where it gets interesting.. for some reason it seems to try to do the push then redirect to :80.
docker push docker.url.here/repo/postgres:latest
The push refers to repository [docker.url.here/repo/postgres]
165835815df0: Pushing [==================================================>]  1.536kB
8c05ef7a503a: Pushing [==================================================>]  10.93kB/10.93kB
0d94fb29e7df: Retrying in 1 second 
8c5ecaf89287: Retrying in 1 second 
7be9029cea6c: Retrying in 1 second 
4a4116c34a06: Waiting 
24eaea503437: Waiting 
957f13e9ee6d: Waiting 
0dbfb680e105: Waiting 
810fa437bf64: Waiting 
b068cedcb84a: Waiting 
94cac46bbf9c: Waiting 
965b24a8dd0f: Waiting 
f2cb0ecef392: Waiting 
dial tcp aws.lb.ip.address:80: connect: connection refused

# How to Reproduce
docker-compose stop
docker-compose start
Do an initial push of something and it works.
docker push docker.url.here/repo/postgres:latest
The push refers to repository [docker.url.here/repo/postgres]
165835815df0: Pushed 
8c05ef7a503a: Pushed 
0d94fb29e7df: Pushed 
8c5ecaf89287: Pushed 
7be9029cea6c: Pushed 
4a4116c34a06: Pushed 
24eaea503437: Pushed 
957f13e9ee6d: Pushed 
0dbfb680e105: Pushed 
810fa437bf64: Pushed 
b068cedcb84a: Pushed 
94cac46bbf9c: Pushed 
965b24a8dd0f: Pushed 
f2cb0ecef392: Layer already exists 
latest: digest: sha256:b65a4e9df3bd1f26606cb75fde0fcc56fa2c9ad2cedda399c77c5dea822b3aef size: 3245

Then wait a while, and try do the push again, and we get the result from the logs section. and in my local /var/log/messages I see:
Upload failed, retrying: dial tcp aws.lb.ip.address:80: connect: connection refused
Upload failed, retrying: dial tcp aws.lb.ip.address:80: connect: connection refused
Upload failed, retrying: dial tcp aws.lb.ip.address:80: connect: connection refused

The bit that is confusing me, is if I do a composer stop and start, then it starts working again, and it obviously is sending my docker command to the AWS LB over https, but after a while it then returns back saying to then do it over http/port 80 which is blocked as I don't allow port 80 traffic.

Thanks

**Comment by paulkilla** [comment]
I should add that everything else works fine when the push connection refuse occurs, I am able to pull images, and use the harbor Web UI with no issues.

**Comment by heww** [comment]
Can you provide the core.log when push image failed?

**Comment by paulkilla** [comment]
So I have re-deployed (3rd time) and haven't had this issue currently, I will monitor it throughout the day and if it occurs again I will reply, otherwise I'll close this as not an issue.
Thanks

**Comment by paulkilla** [comment]
Closing issue, this re-deploy seems to be working fine.
