### ISSUE TITLE
External Redis with TLS enabled is not possible to set 

### ISSUE THREAD

**Issue by lukasmrtvy** [goharbor/harbor#11331]
Its not possible to setup external redis with TLS enabled. Thats usually problem when is Harbor deployed in Azure, AWS with external redis server with TLS enabled ( PaaS ).

**Comment by natitomattis** [comment]
I'm trying to connect external elasticache redis service, but I'm having the same issue. Is it solved in any version?

**Comment by flyingbricks** [comment]
@natitomattis It doesn't seem so, also see issue here: https://github.com/goharbor/harbor/issues/13223

**Comment by slushysnowman** [comment]
Just to give some workaround hints for anyone struggling with this... you can add an stunnel sidecar to get around this

Is this issue a duplicate of https://github.com/goharbor/harbor/issues/13223?

**Comment by MinerYang** [comment]
close by duplicate
