### ISSUE TITLE
harbor 2.0 sort by push time in artifacts UI is not working

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11334]
![image](https://user-images.githubusercontent.com/188115/77750320-8216f200-705e-11ea-9ca7-774024314ccb.png)

![image](https://user-images.githubusercontent.com/188115/77750028-09b03100-705e-11ea-9139-9046eff72fd2.png)

![image](https://user-images.githubusercontent.com/188115/77750355-9529c200-705e-11ea-9421-5f14d168c098.png)

**Comment by jwangyangls** [comment]
Can't sort manually by now.

**Comment by bitsf** [comment]
If can't sort now, remove the sort button, don't mislead user

**Comment by bitsf** [comment]
We should add sort param in backend and make this sort with pages
