### ISSUE TITLE
How do I use java to authenticate and call harbor HTTPS

### ISSUE THREAD

**Issue by littlefoolkid** [goharbor/harbor#11342]
Harbor：1.10.0
java：1.8

**Comment by heww** [comment]
You can try to use https://editor.swagger.io/ to generate client sdk for java by [swagger file](https://github.com/goharbor/harbor/blob/release-1.10.0/api/harbor/swagger.yaml) of harbor 1.10

**Comment by littlefoolkid** [comment]
> You can try to use https://editor.swagger.io/ to generate client sdk for java by [swagger file](https://github.com/goharbor/harbor/blob/release-1.10.0/api/harbor/swagger.yaml) of harbor 1.10


Thank you. It's settled
