### ISSUE TITLE
Pull based replication from DTR using pattern repo/* and repo/** is not working

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#11341]
Harbor's pull-based replication from DTR using patterns  - repo/* and repo/** is not working.

Steps:
I configured DTR instance under Harbor >> Registries as a "docker-registry".
Then tried to replicates images from DTR to Harbor using pull-based replication. 

Works:
sandbox-bjethwan/testhostnetwork
sandbox-bjethwan/testplatform
Logs:
```
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/common/utils/registry/transport.go:51]: 200 | GET https://dfwdtrlabawsw.xxx.xxxx/v2/sandbox-bjethwan/testplatform/tags/list
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/replication/operation/flow/stage.go:104]: fetch image completed
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/replication/operation/flow/stage.go:107]: fetch resources from the source registry completed
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/replication/operation/flow/stage.go:190]: assemble the source resources completed
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/replication/operation/flow/stage.go:215]: assemble the destination resources completed
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/core/filter/security.go:169]: got secret from request
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/core/filter/security.go:171]: using global project manager
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [DEBUG] [/core/filter/security.go:174]: creating a secret security context...
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020-03-28T05:11:23Z [ERROR] [/common/api/base.go:73]: POST /api/projects failed with error: {"code":409,"message":"conflict project"}
Mar 28 05:11:23 172.18.0.1 core[1135]: 2020/03/28 05:11:23.107 #033[1;44m[D]#033[0m [server.go:2774]  |      127.0.0.1|#033[97;43m 409 #033[0m|   2.085558ms|   match|#033[97;46m POST    #033[0m /api/projects   r:/api/projects/

```

Doesn't work
sandbox-bjethwan/*
sandbox-bjethwan/**
Logs:
```
Mar 28 05:07:06 172.18.0.1 core[1135]: 2020-03-28T05:07:06Z [DEBUG] [/common/utils/registry/transport.go:51]: 200 | GET https://dfwdtrlabawsw.xxx.xxxx/v2/_catalog?n=1000
Mar 28 05:07:06 172.18.0.1 core[1135]: 2020-03-28T05:07:06Z [DEBUG] [/replication/operation/flow/stage.go:104]: fetch image completed
Mar 28 05:07:06 172.18.0.1 core[1135]: 2020-03-28T05:07:06Z [DEBUG] [/replication/operation/flow/stage.go:107]: fetch resources from the source registry completed
Mar 28 05:07:06 172.18.0.1 core[1135]: 2020-03-28T05:07:06Z [INFO] [/replication/operation/flow/copy.go:75]: no resources need to be replicated for the execution 10, s
```

DTR Screenshot:
![image](https://user-images.githubusercontent.com/5045325/77814862-fe4f1b00-70da-11ea-9e39-3204fe7d4e5c.png)

- harbor version: 1.10.1
- docker engine version: 19.03.7
- docker-compose version: 1.25.4
- dtr version: 2.7.1

**Comment by bjethwan** [comment]
Not working case:
sandbox-bjethwan/**
`[DEBUG] [/common/utils/registry/transport.go:51]: 200 | GET https://dfwdtrlabawsw.xxx.xxxx/v2/_catalog?n=1000`

Working one:
sandbox-bjethwan/testplatform
`[DEBUG] [/common/utils/registry/transport.go:51]: 200 | GET https://dfwdtrlabawsw.xxx.xxxx/v2/sandbox-bjethwan/testplatform/tags/list`

**Comment by steven-zou** [comment]
@bjethwan 

So far, no DTR replication adapter provided yet. See https://goharbor.io/docs/1.10/install-config/harbor-compatibility-list/

**Comment by bjethwan** [comment]
@steven-zou 
I thought I saw DTR/UCP support in project board: https://github.com/orgs/goharbor/projects/1
But I can't find it now, either in the backlog or under planned releases?

Is this DTR/UCP support going to come out any time soon? Any timelines which can help us plan our release?

**Comment by bjethwan** [comment]
@steven-zou 
I can take a reference from existing adapters (https://github.com/goharbor/harbor/tree/master/src/replication/adapter) and create one for DTR. Is anyone already working on this?

**Comment by steven-zou** [comment]
@bjethwan 

Yes, there was already a PR for supporting DTR. Check https://github.com/goharbor/harbor/pull/9512

The most challenge is not creating an adapter for the specified registry service, the most challenge is the continuously maintaining it. So, the current policy is if no maintenance guaranteed, we'll hold introducing more adapters into the list.

**Comment by gregsidelinger** [comment]
@steven-zou This has been mentioned in #9512.  Is there any desire to maybe enable some of these community ones with an --experimental flag or something along those lines?  That way users know the supportability of these are not 100%.  I will gladly support the DTR adaptor as long as I have access to DTR.

**Comment by bjethwan** [comment]
I can do some testing too. I have a 2-3 DTR/UCP at different versions.

**Comment by steven-zou** [comment]
@gregsidelinger @bjethwan 

Thanks for letting us know you guys are all willing to verify the DTR adapter. We're going to set up a compatibility verification testing framework recently. After that, we may need your help to put DTR into the list then. Keep in touch!

And for the issue of replicating DTR with a docker-registry adapter, if you guys have ideas to do change, you can submit PR for fixing it.

**Comment by bjethwan** [comment]
@steven-zou I will sure verify the DTR adapter in my non-prod environments

**Comment by bjethwan** [comment]
@steven-zou 
Can you point me to the right direction/docs to be able to build harbor with PR from @gregsidelinger ?

**Comment by steven-zou** [comment]
> @steven-zou
> Can you point me to the right direction/docs to be able to build harbor with PR from @gregsidelinger ?

@bjethwan 

Do you want to use a customized harbor? I think you can pull the code form this or and do a merge with the latest main branch. Then follow the guide shown [here](https://goharbor.io/docs/2.0.0/build-customize-contribute/use-make/) to start your customized harbor.

**Comment by MnrGreg** [comment]
@bjethwan the below is a simplified process for building just the DTR related images from master using @gregsidelinger PR:

```shell
git clone https://github.com/goharbor/harbor
cd harbor
git remote add upstream https://github.com/gregsidelinger/harbor.git
git fetch upstream
git rebase --onto upstream/dtr origin/master
make compile
sed -i.bak 's/_build_prepare _build_db _build_portal _build_core _build_jobservice _build_log _build_nginx _build_registry _build_registryctl _build_notary _build_clair _build_clair_adapter _build_trivy_adapter _build_redis _build_chart_server/_build_prepare _build_core _build_jobservice/g' ./make/photon/Makefile
make build

# Container cache should now have the following DTR enabled images:
# goharbor/harbor-core:dev
# goharbor/harbor-jobservice:dev
```

**Comment by MnrGreg** [comment]
By the way this adapter works with the latest DTR version 2.8.1

**Comment by steven-zou** [comment]
DTR adapter has been merged into the harbor. Close this issue.
