### ISSUE TITLE
two different timestamps printed in jobservice.log.

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11354]
In my docker-compose deployment environment, when I checked the /var/log/harbor/jobservice.log,  as we can see each line has two timestamps, those timestamps are different. why we need two timestamps? if we really need it, in the single host deployment, they should be the same. 
```
...
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:244]: the blob sha256:4297d2238a4c9368cf3ff8567f48cd216194664d93daefa3a0fd5cff8ef87576 already exists on the destination registry, skip
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:244]: copying the blob sha256:ae8395e171fbdedaaf59d4886db6c03f841e08cf594f9cbf270da728d1811df3...
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:180]: the manifest of artifact goharbor/nginx-photon:dev pulled
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:244]: copying the blob sha256:42cb67590e78dd661e454bd75de552673a08b4f6b784a3b48b22699a87be58dd...
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:244]: the blob sha256:42cb67590e78dd661e454bd75de552673a08b4f6b784a3b48b22699a87be58dd already exists on the destination registry, skip
Mar 29 09:54:56 172.18.0.1 jobservice[1660]: 2020-03-29T16:54:56Z [INFO] [/replication/transfer/image/transfer.go:244]: copying the blob sha256:ae8395e171fbdedaaf59d4886db6c03f841e08cf594f9cbf270da728d1811df3...
```

**Comment by renmaosheng** [comment]
Qian,
       I remembered in last meeting, you mentioned some background of this design? could you please share it? thanks.

**Comment by ninjadq** [comment]
there are are two timestamps because all logs generated by harbor components will be collected by syslogd. And syslogd will add a timestamp in which is the time syslogd receive the log. The difference between these two timestamps is caused by timezone setting

**Comment by renmaosheng** [comment]
could we make the containers within  docker-compose using the same timezone?

**Comment by reasonerjt** [comment]
@renmaosheng It's interesting b/c in my env they are always in the same timezone

**Comment by renmaosheng** [comment]
I just checked my docker host timezone is different from the timezone in docker containers. but the containers' timezone are the same

**Comment by renmaosheng** [comment]
talked with Qian, we will revisit this after he fixes the helm tls feature.

**Comment by prima101112** [comment]
@renmaosheng could you please explain whats the plan? make it using syslogd timestamp or using docker container time? 
or try to sync container time with the host?
