### ISSUE TITLE
The database and redis are deployed separately The container failed to start while starting harbor

### ISSUE THREAD

**Issue by bjzqhe** [goharbor/harbor#11367]
harbor version: 1.10.1
Apr 1 00:23:16 localhost core[12065]: goroutine 1 [running]:
Apr 1 00:23:16 localhost core[12065]: github.com/astaxie/beego.initBeforeHTTPRun()
Apr 1 00:23:16 localhost core[12065]: #11/harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20d
Apr 1 00:23:16 localhost core[12065]: github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Apr 1 00:23:16 localhost core[12065]: #11/harbor/src/vendor/github.com/astaxie/beego/beego.go:58 +0x26
Apr 1 00:23:16 localhost core[12065]: main.main()
Apr 1 00:23:16 localhost core[12065]: #11/harbor/src/core/main.go:292 +0xeb0
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port, err: strconv.Atoi: parsing "": invalid syntax
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/native/adapter.go:42]: the factory for adapter docker-registry registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/harbor/adapter.go:40]: the factory for adapter harbor registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/aliacr/adapter.go:26]: the factory for adapter ali-acr registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/quayio/adapter.go:34]: the factory of Quay.io adapter was registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/gitlab/adapter.go:19]: the factory for adapter gitlab registered
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/controllers/base.go:289]: Config path: /etc/core/app.conf
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:177]: initializing configurations...
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:100]: key path: /etc/core/key
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port, err: strconv.Atoi: parsing "": invalid syntax
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:73]: init secret store
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:76]: init project manager based on deploy mode
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:145]: initializing the project manager based on local database...
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:181]: configurations initialization completed
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-172.31.0.23 port-20010 databse-registry sslmode-"disable"
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/base.go:89]: Register database completed
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/pgsql.go:122]: No change in schema, skip.
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:83]: User id: 1 already has its encrypted password.
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:245]: initializing notification...
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/pkg/notification/notification.go:50]: notification initialization completed
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:269]: Because SYNC_REGISTRY set false , no need to sync registry
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:272]: Init proxy
Apr 1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:291]: Version: v1.10.1, Git commit: f3e1171
Apr 1 00:24:17 localhost core[12065]: panic: ERR Client sent AUTH, but no password is set
Apr 1 00:24:17 localhost core[12065]:
Apr 1 00:24:17 localhost core[12065]: goroutine 1 [running]:
Apr 1 00:24:17 localhost core[12065]: github.com/astaxie/beego.initBeforeHTTPRun()
Apr 1 00:24:17 localhost core[12065]: #11/harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20d
Apr 1 00:24:17 localhost core[12065]: github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Apr 1 00:24:17 localhost core[12065]: #11/harbor/src/vendor/github.com/astaxie/beego/beego.go:58 +0x26
Apr 1 00:24:17 localhost core[12065]: main.main()
Apr 1 00:24:17 localhost core[12065]: #11/harbor/src/core/main.go:292 +0xeb0

**Comment by bjzqhe** [comment]
Apr  1 00:23:16 localhost core[12065]: goroutine 1 [running]:
Apr  1 00:23:16 localhost core[12065]: github.com/astaxie/beego.initBeforeHTTPRun()
Apr  1 00:23:16 localhost core[12065]: #011/harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20d
Apr  1 00:23:16 localhost core[12065]: github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Apr  1 00:23:16 localhost core[12065]: #011/harbor/src/vendor/github.com/astaxie/beego/beego.go:58 +0x26
Apr  1 00:23:16 localhost core[12065]: main.main()
Apr  1 00:23:16 localhost core[12065]: #011/harbor/src/core/main.go:292 +0xeb0
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/native/adapter.go:42]: the factory for adapter docker-registry registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/harbor/adapter.go:40]: the factory for adapter harbor registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/aliacr/adapter.go:26]: the factory for adapter ali-acr registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/quayio/adapter.go:34]: the factory of Quay.io adapter was registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/replication/adapter/gitlab/adapter.go:19]: the factory for adapter gitlab registered
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/controllers/base.go:289]: Config path: /etc/core/app.conf
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:177]: initializing configurations...
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:100]: key path: /etc/core/key
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:73]: init secret store
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:76]: init project manager based on deploy mode
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/config/config.go:145]: initializing the project manager based on local database...
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:181]: configurations initialization completed
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-172.31.0.23 port-20010 databse-registry sslmode-"disable"
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/base.go:89]: Register database completed
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/common/dao/pgsql.go:122]: No change in schema, skip.
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:83]: User id: 1 already has its encrypted password.
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:245]: initializing notification...
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/pkg/notification/notification.go:50]: notification initialization completed
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:269]: Because SYNC_REGISTRY set false , no need to sync registry 
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:272]: Init proxy
Apr  1 00:24:17 localhost core[12065]: 2020-03-31T16:24:17Z [INFO] [/core/main.go:291]: Version: v1.10.1, Git commit: f3e11715
Apr  1 00:24:17 localhost core[12065]: panic: ERR Client sent AUTH, but no password is set
Apr  1 00:24:17 localhost core[12065]: 
Apr  1 00:24:17 localhost core[12065]: goroutine 1 [running]:
Apr  1 00:24:17 localhost core[12065]: github.com/astaxie/beego.initBeforeHTTPRun()
Apr  1 00:24:17 localhost core[12065]: #011/harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20d
Apr  1 00:24:17 localhost core[12065]: github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Apr  1 00:24:17 localhost core[12065]: #011/harbor/src/vendor/github.com/astaxie/beego/beego.go:58 +0x26
Apr  1 00:24:17 localhost core[12065]: main.main()
Apr  1 00:24:17 localhost core[12065]: #011/harbor/src/core/main.go:292 +0xeb0

**Comment by bjzqhe** [comment]
vim  harbor.yml
external_database:
   harbor:
     host: 172.31.0.23
     port: 20010
     db_name: registry
     username: postgres
     password: root123
     ssl_mode: disable
     max_idle_conns: 2
     max_open_conns: 0
   clair:
     host: 172.31.0.23
     port: 20011
     db_name: clair
     username: postgres
     password: root123
     ssl_mode: disable
   notary_signer:
     host: 172.31.0.23
     port: 20012
     db_name: notarysigner
     username: postgres
     password: root123
     ssl_mode: disable
   notary_server:
     host: 172.31.0.23
     port: 20013
     db_name: notaryserver
     username: postgres
     password: root123
     ssl_mode: disable

# Uncomment external_redis if using external Redis server
external_redis:
   host: 172.31.0.23
   port: 20000
   password:
#   # db_index 0 is for core, it's unchangeable
   registry_db_index: 1
   jobservice_db_index: 2
   chartmuseum_db_index: 3
   clair_db_index: 4

**Comment by bjzqhe** [comment]
docker ps
b4c9322b4830        goharbor/harbor-jobservice:v1.10.1                        "/harbor/harbor_jobs…"   44 minutes ago      Up 32 seconds (health: starting)                                                 harbor-jobservice
663ba560dbc1        goharbor/harbor-core:v1.10.1                              "/harbor/harbor_core"    44 minutes ago      Restarting (2) 1 second ago                                                      harbor-core

**Comment by heww** [comment]
Ensure that the database configurations for clair is ok when you installed clair with harbor.

**Comment by bjzqhe** [comment]
cat common/config/core/env
CONFIG_PATH=/etc/core/app.conf
UAA_CA_ROOT=/etc/core/certificates/uaa_ca.pem
_REDIS_URL=172.31.0.21:20000,100,None
SYNC_REGISTRY=false
SYNC_QUOTA=true
CHART_CACHE_DRIVER=redis
_REDIS_URL_REG=redis://172.31.0.21:20000/1

PORT=8080
LOG_LEVEL=info
EXT_ENDPOINT=https://registry.hongyaa.com
DATABASE_TYPE=postgresql
POSTGRESQL_HOST=172.31.0.21
POSTGRESQL_PORT=20010
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=root123
POSTGRESQL_DATABASE=registry
POSTGRESQL_SSLMODE=disable
POSTGRESQL_MAX_IDLE_CONNS=2
POSTGRESQL_MAX_OPEN_CONNS=0
REGISTRY_URL=http://registry:5000
TOKEN_SERVICE_URL=http://core:8080/service/token
HARBOR_ADMIN_PASSWORD=Harbor12345
MAX_JOB_WORKERS=10
CORE_SECRET=7A883Fmq4NSM1Y0w
JOBSERVICE_SECRET=skJXWHWvCIZA3g4U
ADMIRAL_URL=
WITH_NOTARY=False
WITH_CLAIR=False
CLAIR_DB_PASSWORD=
CLAIR_DB_HOST=
CLAIR_DB_PORT=
CLAIR_DB_USERNAME=
CLAIR_DB=
CLAIR_DB_SSLMODE=
CORE_URL=http://core:8080
CORE_LOCAL_URL=http://127.0.0.1:8080
JOBSERVICE_URL=http://jobservice:8080
CLAIR_URL=http://clair:6060
CLAIR_ADAPTER_URL=http://clair-adapter:8080
NOTARY_URL=http://notary-server:4443
REGISTRY_STORAGE_PROVIDER_NAME=filesystem
READ_ONLY=false
RELOAD_KEY=
CHART_REPOSITORY_URL=http://chartmuseum:9999
REGISTRY_CONTROLLER_URL=http://registryctl:8080
WITH_CHARTMUSEUM=False

HTTP_PROXY=
HTTPS_PROXY=
NO_PROXY=core,notary-server,log,127.0.0.1,registryctl,nginx,clair-adapter,jobservice,registry,.local,.internal,postgresql,chartmuseum,portal,clair,notary-signer,db,localhost,redis

**Comment by bjzqhe** [comment]
external_database:
   harbor:
     host: 172.31.0.21
     port: 20010
     db_name: registry
     username: postgres
     password: root123
     ssl_mode: disable
     max_idle_conns: 2
     max_open_conns: 0
   clair:
     host: 172.31.0.21
     port: 20011
     db_name: clair
     username: postgres
     password: root123
     ssl_mode: disable
   notary_signer:
     host: 172.31.0.21
     port: 20012
     db_name: notarysigner
     username: postgres
     password: root123
     ssl_mode: disable
   notary_server:
     host: 172.31.0.21
     port: 20013
     db_name: notaryserver
     username: postgres
     password: root123
     ssl_mode: disable

# Uncomment external_redis if using external Redis server
external_redis:
   host: 172.31.0.21
   port: 20000
   password:
#   # db_index 0 is for core, it's unchangeable
   registry_db_index: 1
   jobservice_db_index: 2
   chartmuseum_db_index: 3
   clair_db_index: 4

**Comment by bjzqhe** [comment]
external_database:
   harbor:
     host: 172.31.0.21
     port: 20010
     db_name: registry
     username: postgres
     password: root123
     ssl_mode: disable
     max_idle_conns: 2
     max_open_conns: 0
   clair:
     host: 172.31.0.21
     port: 20011
     db_name: clair
     username: postgres
     password: root123
     ssl_mode: disable
   notary_signer:
     host: 172.31.0.21
     port: 20012
     db_name: notarysigner
     username: postgres
     password: root123
     ssl_mode: disable
   notary_server:
     host: 172.31.0.21
     port: 20013
     db_name: notaryserver
     username: postgres
     password: root123
     ssl_mode: disable


external_redis:
   host: 172.31.0.21
   port: 20000
   password:
   registry_db_index: 1
   jobservice_db_index: 2
   chartmuseum_db_index: 3
   clair_db_index: 4

**Comment by bjzqhe** [comment]
The database can be connected normally
psql -U postgres  -h 172.31.0.21 -p 20011 -d clair  
clair=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 clair     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres

**Comment by bjzqhe** [comment]
The problem has not been solved

**Comment by bjzqhe** [comment]
Version 1.9.3, which I tested, didn't have this problem

**Comment by heww** [comment]
Please try to remove `password` item in the `external_redis` configuration.

**Comment by bjzqhe** [comment]
Configuring the redis password solved the problem, thank you

**Comment by bjzqhe** [comment]
I want to change the database to mysql5.7 seems to have an error
[/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: unknown response for startup: 'J'

**Comment by heww** [comment]
Currently harbor only support postgresql, not support mysql.

**Comment by bjzqhe** [comment]
I see. Thank you
