### ISSUE TITLE
I want know where can I get the source file dumb-init 

### ISSUE THREAD

**Issue by yuzp1996** [goharbor/harbor#11371]
Hello! I have a simple question about the file dumb-init  under harbor/make/photon/clair, can you tell me where can I get the source file, a link is enough.

I want get the arm64 version of this file

thank you very much

**Comment by heww** [comment]
dumb-init in harbor/make/photon/clair is from here https://github.com/Yelp/dumb-init/releases/tag/v1.2.0

**Comment by yuzp1996** [comment]
> dumb-init in harbor/make/photon/clair is from here https://github.com/Yelp/dumb-init/releases/tag/v1.2.0

Thank you very much
