### ISSUE TITLE
Scan overview missing in the detail page of the artifact

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11376]
Steps to reproduce the problem:
1. Scan the artifact which will get error result
2. Go to the detail page of the artifact

Expected behavior and actual behavior:
The scan overview should be displayed, but it is missing.

![image](https://user-images.githubusercontent.com/5634205/78103791-59a54400-7420-11ea-9bfd-835d1d0e353b.png)

![image](https://user-images.githubusercontent.com/5634205/78103842-780b3f80-7420-11ea-834e-7588e5902f64.png)

**Comment by AllForNothing** [comment]
It is designed behavior

**Comment by reasonerjt** [comment]
We should render the scan_overview result in the detail page.
