### ISSUE TITLE
Add Azure Storage as a backend in harbor tile configuration.  

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11372]
Add Azure Storage as a backend in harbor tile configuration just like we have for GCP / s3 right now.  This is important for users of tile to have centralized management through opsman instead of managing backend separately from the registry.

This feature is a blocker for 1.10.2 tile release.

**Comment by stonezdj** [comment]
Already add this feature in Harbor tile 1.10.2 and 2.0
