### ISSUE TITLE
creating user in harbor using curl

### ISSUE THREAD

**Issue by thatsk** [goharbor/harbor#11384]
curl -v -X PUT  -u "build:Harbor12345"-H "Content-Type: application/json" -ki  https://harbor/api/configurations -d'{"auth_mode":"db_auth"}'

**Comment by thatsk** [comment]
{"code":401,"message":"UnAuthorized"}
how to pass adimin credentials or some toek authenticity

**Comment by balonik** [comment]
BasicAuth works, but you cannot change `auth_mode` after it is switched to ldap/oidc

**Comment by thatsk** [comment]
my auth_mode is local so need example how to import the user.

**Comment by thatsk** [comment]
via curl

**Comment by thatsk** [comment]
curl -u "admin:Harbor12345" -k -X POST -H "Content-Type: application/json" "https://harbor.$(hostname -d)/api/users" -d "{ \"username\": \"build\", \"email\": \"sre@gmail.com\", \"password\": \"example@123\", \"realname\": \"Build User\", \"comment\": \"Build User\" }"

**Comment by thatsk** [comment]
i am talking about this.
