### ISSUE TITLE
Does the clair's CVE data provide API imports offline?

### ISSUE THREAD

**Issue by 1661788089** [goharbor/harbor#11388]
Does the clair's CVE data provide API imports offline?

I did not find the relevant API, the document only provides the way of manual import, offline state, data update can only manually import the update? Is there a better plan?

**Comment by 1661788089** [comment]
Does the clair's CVE data provide API imports offline?

I did not find the relevant API, the document only provides the way of manual import, offline state, data update can only manually import the update? Is there a better plan?

**Comment by heww** [comment]
Currently there is no API to import vulnerability data to Clair. And I think at the moment we do not have any plan to support this method.

You can follow the docs https://goharbor.io/docs/1.10/administration/vulnerability-scanning/import-vulnerability-data/#back-up-the-harbor-clair-database to import vulnerability data to Clair.
