### ISSUE TITLE
notification link in README is a 404 Not found

### ISSUE THREAD

**Issue by ericwb** [goharbor/harbor#11386]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
This is a dead link.  Goes to GitHub 404 page

**Steps to reproduce the problem:**
* Click on the link "notification" in the README.  The link is next to Community Meeting

This is the dead link:
https://github.com/goharbor/harbor/blob/master/docs/img/bell-outline-badged.svg

**Versions:**
Please specify the versions of following systems.
N/A

**Additional context:**

**Comment by inspuradmin** [comment]
![image](https://user-images.githubusercontent.com/20829578/78975516-d6ce6880-7b46-11ea-9c27-d82c0508199d.png)
