### ISSUE TITLE
GC jobs are never been completed...they are always in running state and doing nothing.

### ISSUE THREAD

**Issue by pgkulk** [goharbor/harbor#11402]
What can we help you?
Current Version : 1.10.1 (upgraded today from 1.9.3 -> 1.10.1 but issue exists from 1.9.3 itself)

I am having issue with GC. There are 4 previous jobs which are always in running state and never changed their state to "finished".  
Starting new job doesn't do anything. I see following in jobservice.log but nothing after this line:
Apr  2 06:59:48 emea-got-dmzgw.emea.tibco.com jobservice[34201]: 2020-04-02T10:59:48Z [INFO] [/jobservice/runner/redis.go:187]: start to run gc in job.

I also tried upgrading from 1.9.3 to 1.10.1 but no luck.
Attached are following log files. Can someone please help with this? Thank you!

<img width="1147" alt="GC_screenshot" src="https://user-images.githubusercontent.com/20462788/78244706-cc3b2000-7503-11ea-8ed6-8e3e54669887.png">

[registry.log](https://github.com/goharbor/harbor/files/4420696/registry.log)
[core.log](https://github.com/goharbor/harbor/files/4420699/core.log)
[jobservice.log](https://github.com/goharbor/harbor/files/4420700/jobservice.log)
[redis.log](https://github.com/goharbor/harbor/files/4420701/redis.log)

**Comment by pgkulk** [comment]
Latest Update:
The job was actually running it seems. It changed the state to "Error" after almost 25 hrs. Please note that  I have more than 4TB of data. It would be nice if more log is printed or displayed in the UI that GC is actually running. 
Although it failed with error "Failed to start GC: 500", It had surely cleaned up few blobs as I got back 200GB of free space when it finished. Please let me know if you need more information from my side.

https://github.com/goharbor/harbor/issues/7945#issuecomment-498123934
https://github.com/goharbor/harbor/issues/10203

<img width="416" alt="Screen Shot 2020-04-03 at 10 29 40 AM" src="https://user-images.githubusercontent.com/20462788/78523099-4a8e0f80-77ed-11ea-956d-078844dbaab5.png">

**Comment by wy65701436** [comment]
From the latest update, it seems GC works for you now? GC may execute several hours, especially in cloud-based storage with TB data. 

`Running` on the GC page is definitely standing for a job that is running in the backend. And so far Harbor cannot know how long it will take, just update the status to finish or error eventually. 

Do not trigger a new one if you're seeing there is a `running` one.

**Comment by steven-zou** [comment]
As it's not a problem, I'll close this issue now. If you have any further questions, feel free to reopen, or create new.
