### ISSUE TITLE
harbor 2.0 UI 翻译不准确

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11404]
![image](https://user-images.githubusercontent.com/188115/78264526-de35b680-7535-11ea-8370-8e31e1b2e2a5.png)

不应该是 `Tag数量`，可以翻译为 `Tag列表`，或者直接为 `Tags`

**Comment by xaleeks** [comment]
那这个数字代表什么, 还是这个‘1’ 就是tag的名字？ @bitsf 

we should start including the harbor build on these internal bug reports.  I'v

**Comment by xaleeks** [comment]
I figured it out, this should just say 'tags'

**Comment by bitsf** [comment]
verified in build 3378
