### ISSUE TITLE
Image scan scheduled job lacking date configuration

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11417]
harbor version: Version v2.0.0-759c759b
 
@zhoumeina  please see screenshot on requirement, and please work with @lweitzman  on design 

![Screen Shot 2020-04-03 at 12 10 10 AM](https://user-images.githubusercontent.com/51319901/78332773-ab4fea80-7556-11ea-89ee-86041e196353.png)

**Comment by reasonerjt** [comment]
putting it to backlog as user can use corn to customize t he schedule.
