### ISSUE TITLE
Editing project quota inconsistent with other tabs in UI

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11416]
harbor version: Version v2.0.0-759c759b

If this is the only place where we use '...', let's just remove it and use the edit button up top for consistency sake.

![Screen Shot 2020-04-02 at 10 41 17 PM](https://user-images.githubusercontent.com/51319901/78332597-54e2ac00-7556-11ea-8d8e-662e14a97418.png)

**Comment by AllForNothing** [comment]
dulplicated with #11079
