### ISSUE TITLE
New registry endpoint typo

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11415]
harbor version: Version v2.0.0-759c759b

'registry' should be 'Registry'

![Screen Shot 2020-04-02 at 10 39 22 PM](https://user-images.githubusercontent.com/51319901/78332502-28c72b00-7556-11ea-88d4-6e1a5dd4d6ce.png)

**Comment by lweitzman** [comment]
Also the message becomes redundant when specifying "unhealthy" twice

**Comment by AllForNothing** [comment]
The error message is returned by the back end  API

**Comment by bitsf** [comment]
backend golang error message should always be lowercase beginning
