### ISSUE TITLE
change naming in breadcrumbs

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11412]
harbor version: Version v2.0.0-759c759b

![Screen Shot 2020-04-02 at 10 17 27 PM](https://user-images.githubusercontent.com/51319901/78332168-78f1bd80-7555-11ea-88cf-03851b49d6e6.png)

**Comment by AllForNothing** [comment]
![image](https://user-images.githubusercontent.com/30999793/78854995-51b75680-7a55-11ea-9bae-555a6086d3fe.png)
projects   (can back to project list page)  <   repos(can back to repo list page）
repo name (you are here）
