### ISSUE TITLE
confirmation alert not using clarity

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11414]
harbor version: Version v2.0.0-759c759b

The confirmation dialog after successfully creating a user is not standard clarity. it should not be as tall, have an info icon on the left and text left justified

@louis, can you provide some guidance here?

![Screen Shot 2020-04-02 at 10 23 39 PM](https://user-images.githubusercontent.com/51319901/78332348-df76db80-7555-11ea-9613-f3a7ff79b60d.png)

**Comment by AllForNothing** [comment]
@lweitzman What's your opinion

**Comment by lweitzman** [comment]
@AllForNothing the proper clarity alert is this... (sorry for delay missed this)

![Screen Shot 2020-06-01 at 12 44 56 PM](https://user-images.githubusercontent.com/626032/83431749-d5624380-a405-11ea-83d1-0f3d0dbac350.png)

**Comment by xaleeks** [comment]
I tagged it 2.0.1 so we don't miss it on the engineering meeting
