### ISSUE TITLE
3rd party registry endpoint UI improvement

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11423]
harbor version: Version v2.0.0-759c759b

please see screenshot on requirement

![Screen Shot 2020-04-03 at 12 21 48 AM](https://user-images.githubusercontent.com/51319901/78333376-b8b9a480-7557-11ea-9a1b-4af9b9bb0894.png)

**Comment by AllForNothing** [comment]
They are returned by back-end API

**Comment by bitsf** [comment]
These name is also used as an ID in db, so we can't simply change them.
They need be localization or add another "DisplayName" field.

Not suggest fix in 2.0 FC now.

**Comment by AllForNothing** [comment]
@xaleeks Please check below text  
`"ali-acr": "Ali Acr",
  "aws-ecr": "Aws Ecr",
  "azure-acr": "Azure Acr",
  "docker-hub": "Docker Hub",
  "docker-registry": "Docker Registry",
  "gitlab": "Gitlab",
  "google-gcr": "Google Gcr",
  "harbor": "Harbor",
  "helm-hub": "Helm Hub",
  "huawei-SWR": "Huawei SWR",
  "jfrog-artifactory": "Jfrog Artifactory",
  "quay-io": "Quay Io",`

**Comment by xaleeks** [comment]
"ali-acr": "Alibaba ACR",
"aws-ecr": "Aws ECR",
"azure-acr": "Azure ACR",
"docker-hub": "Docker Hub",
"docker-registry": "Docker Registry",
"gitlab": "Gitlab",
"google-gcr": "Google GCR",
"harbor": "Harbor",
"helm-hub": "Helm Hub",
"huawei-SWR": "Huawei SWR",
"jfrog-artifactory": "jFrog Artifactory",
"quay-io": "Quay.io"
