### ISSUE TITLE
Scanner connectivity test possibly redundant

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11425]
@wy65701436  @steven-zou  When adding a scanner, it seems that we test the connection, because it timed out with a bad endpoint url. why do we need "test connection” button if we test on save?

harbor version: Version v2.0.0-759c759b

**Comment by steven-zou** [comment]
@heww 

Could you please confirm if we check the healthy of the scanner when creating and editing?

**Comment by steven-zou** [comment]
@xaleeks 

Leave the option for the users when they want to check the health if necessary.

**Comment by heww** [comment]
I confirmed that we check the health of the scanner when creating and editing.
