### ISSUE TITLE
Filter project logs on repository name doesn't work

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#11433]
Filter logs by typing the repository name into the search field doesn’t return the repository. filter only works on username

**Comment by AllForNothing** [comment]
![image](https://user-images.githubusercontent.com/30999793/78644684-d5076980-78e8-11ea-8648-b6c726f679d4.png)
@lweitzman  For now ,  not support fitering logs by repository name.
In simple mode,  filter only works on username by default
