### ISSUE TITLE
Replication between two harbor instances not working 

### ISSUE THREAD

**Issue by cleman95** [goharbor/harbor#11430]
Overview : 

I'm trying to replicate the registries of an harbor instance in an other one. 
The replication works from Harbor to DockerHub, but not from Harbor to Harbor. 

What's the problem ? 

The replication task is marked as failed with a **405 method not allowed error**. 

```
the execution 11 failed: failed to do the prepare work for pushing/uploading resources: http error: code 405, message <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

Environment :

- OS :  Centos 7
- Kubernetes version : 1.16.7
- Chart Helm version : harbor-1.3.1
- Harbor version: 1.10.1
- Helm version: 2

Steps to reproduce the problem :

So first, deploy two harbor instances on a kubernetes cluster using Helm, Harbor 1 and Harbor 2. 
Then, create :
- a registry on the Harbor 1 (with the ip adress of the Harbor 2) 
- a push based replication rule on Harbor 1 targeting the Harbor 2. 

The replication rule is configured like this :
- no source ressource name or library/** or **: 

What i already tried ? 

I tried source resource name with nothing , ** or library/**. I tried just library/ and the replication task is marked as succeed with no resources to replicate. I tried a pull-based replication rules with an internal server error while creating the replication rule. 
 

Stacktrace of the error :

2020/04/03 13:00:43.416 [D] [server.go:2774]  |      127.0.0.1| 200 |   4.271613ms|   match| GET      /api/replication/executions   r:/api/replication/executions
2020/04/03 13:00:46.307 [D] [server.go:2774]  |   10.233.67.87| 200 |   1.663779ms|   match| GET      /api/ping   r:/api/ping
2020/04/03 13:00:46.508 [D] [server.go:2774]  |      127.0.0.1| 201 |   6.675675ms|   match| POST     /api/replication/executions   r:/api/replication/executions
2020/04/03 13:00:46.517 [D] [server.go:2774]  |      127.0.0.1| 200 |    8.49132ms|   match| GET      /api/projects   r:/api/projects/
2020/04/03 13:00:46.552 [D] [server.go:2774]  |      127.0.0.1| 200 |   34.92956ms|   match| GET      /api/repositories   r:/api/repositories
2020/04/03 13:00:46.591 [D] [server.go:2774]  |  10.233.65.165| 200 |   1.004957ms|   match| POST     /service/notifications   r:/service/notifications
2020/04/03 13:00:46.595 [D] [server.go:2774]  |  10.233.65.165| 200 |    887.223µs|   match| POST     /service/notifications   r:/service/notifications
2020/04/03 13:00:46.619 [D] [server.go:2774]  |      127.0.0.1| 200 |   66.10655ms|   match| GET      /api/repositories/library/server/tags   r:/api/repositories/*/tags
2020/04/03 13:00:46.620 [D] [server.go:2774]  |  10.233.65.165| 200 |   1.403851ms|   match| POST     /service/notifications   r:/service/notifications
2020/04/03 13:00:46.632 [D] [server.go:2774]  |      127.0.0.1| 200 |   4.612451ms|   match| GET      /api/replication/executions   r:/api/replication/executions
2020/04/03 13:00:46.642 [D] [server.go:2774]  |      127.0.0.1| 200 |  88.913696ms|   match| GET      /api/repositories/library/node/tags   r:/api/repositories/*/tags
2020-04-03T13:00:46Z [ERROR] [/replication/operation/controller.go:108]: the execution 11 failed: failed to do the prepare work for pushing/uploading resources: http error: code 405, message <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
2020/04/03 13:00:52.100 [D] [server.go:2774]  |   10.233.67.87| 200 |    1.54456ms|   match| GET      /api/ping   r:/api/ping
2020/04/03 13:00:53.559 [D] [server.go:2774]  |      127.0.0.1| 200 |   4.494392ms|   match| GET      /api/replication/executions   r:/api/replication/executions

**Comment by renmaosheng** [comment]
Hi Ziming, could you please take a look? thanks.

**Comment by bitsf** [comment]
because harbor 2.x is support OCI manifest list, and some API is changed, so you can not replicate  between 1.x and 2.x

**Comment by bitsf** [comment]
replicate from 2.x to 1.x is partial support

**Comment by xaleeks** [comment]
please upgrade so that both versions are the same before you attempt to upgrade.
