### ISSUE TITLE
Add Webhook dialog needs cleanup

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#11432]
things needing updating... events in 2 columns and aligned, button placement (and order of buttons), user friendly names, names organized, description under title changed.

![Screen Shot 2020-04-02 at 1 32 25 PM](https://user-images.githubusercontent.com/626032/78375678-276c2180-759b-11ea-8817-0d7d0690e062.png)

**Comment by AllForNothing** [comment]
It has been fixed by PR #11393
