### ISSUE TITLE
docker登陆harbor 出现x509：certificate signed by unknown authority

### ISSUE THREAD

**Issue by diem12315** [goharbor/harbor#11439]
docker的版本18.09
kuberrnetes版本：16.0
harbor版本v1.10.1
helm部署
harbor暴露服务的方式是nodePort，使用自动创建的证书
访问的地址：www.harbor.com:30003
可以通过ca.crt上传helm-chart
不能登陆到harbor
报错为：x509: certificate signed by unknown authority

**Comment by heww** [comment]
Please following this doc https://docs.docker.com/datacenter/dtr/2.0/configure/config-security/#install-registry-certificates-on-client-docker-daemons to install custom cert for docker.

**Comment by diem12315** [comment]
尝试将docker Security configuration中的方法，将证书放入到/etc/pki/ca-trust/source/anchors/ 还是报错x509: certificate signed by unknown authority
