### ISSUE TITLE
In Webhooks datagrid the Event type column is not wide enough

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#11431]
the event type column is not wide enough and it overflows to next one making it hard to see tooltip of all the event types. Label, "DELETE_ARTIFACT", should be shown with more user friendly capitalization..."Delete Artifact"

<img width="748" alt="Screen Shot 2020-03-25 at 11 41 30 AM" src="https://user-images.githubusercontent.com/626032/78375072-4322f800-759a-11ea-916f-ed3116e702d1.png">

**Comment by AllForNothing** [comment]
It has been fixed by PR #11393
