### ISSUE TITLE
Text areas on detail pages is not Clarity 

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#11434]
the text areas when in dark mode, should use the clarity text area colors

<img width="1248" alt="Screen Shot 2020-04-02 at 1 02 34 PM" src="https://user-images.githubusercontent.com/626032/78376496-6cdd1e80-759c-11ea-9f53-262e822e1659.png">

**Comment by AllForNothing** [comment]
@lweitzman It is a rich text box(markdown) returned by back-end API.   So the CSS depends on the author  not  Harbor.
