### ISSUE TITLE
Multiple Docker endpoints for harbor

### ISSUE THREAD

**Issue by kratos81** [goharbor/harbor#11448]
Does harbor support having multiple docker repositories on multiple ports akin to the nexus implementation? 

I have searched for documentation to implement  this to no avail and suspect it may not be supported.   If not, is this a feature on the roadmap? 

Thanks

**Comment by kratos81** [comment]
Hi , any traction on this?

**Comment by xaleeks** [comment]
This is not supported and not on the roadmap atm @kratos81
