### ISSUE TITLE
Harbor Core service can't connect to postgres with custom password

### ISSUE THREAD

**Issue by OheyThere** [goharbor/harbor#11449]
Hey guys,

I am trying to deploy Harbor v1.10.1 on Ubuntu 18.04.
Now I ran into the following problem: as soon as i change the password for the database root-user, the core-service will not start properly (always restarting).
I get the following output in my core.log:

    Apr  6 11:27:06 172.28.0.1 core[1173]: [ORM]2020/04/06 11:27:06 register db Ping `default`, pq: 
    password authentication failed for user "postgres"
    Apr  6 11:27:06 172.28.0.1 core[1173]: 2020-04-06T11:27:06Z [FATAL] [/core/main.go:188]: failed 
    to initialize database: register db Ping `default`, pq: password authentication failed for user 
    "postgres"

As for the postgres.log:

    Apr  6 11:27:09 172.28.0.1 postgresql[1173]: #011Connection matched pg_hba.conf line 95: "host 
    all all all md5"
    Apr  6 11:27:36 172.28.0.1 postgresql[1173]: FATAL:  password authentication failed for user 
    "postgres"
    Apr  6 11:27:36 172.28.0.1 postgresql[1173]: DETAIL:  Password does not match for user 
    "postgres".

I tried a default installation with default database-password and that worked perfectly!
I couldn't find any solution to this online, so maybe there's some weird bug going on. Can you help me with that?

**Comment by heww** [comment]
Changing the password of the harbor-db in the harbor.yml after the harbor-db bootstraped will be not work.

If you want change the password of boostraped harbor-db, please login the postgresql, and change it my sql commonds.

**Comment by OheyThere** [comment]
Thanks for your answer but I think i have to clarify my problem.
I did not change the password after starting the services.

I simply followed the steps provided on this site: https://goharbor.io/docs/1.10/install-config/
So I first downloaded the Offline-installer (same problem occurs with online installer) and unpacked it onto my machine.

After that, I configured the harbor.yml (and changed the db-root-pw there) to be deployed with ssl, hostname etc.

And only after that process I used the install.sh script to bring all services up and running.
I also looked into the config folder and found that the env-file for the db-service is existent and the password provided there is correct - I have no idea why this problem would still occur...

**Comment by OheyThere** [comment]
Oh wow,

shame over me! I found my mistake - when reinstalling Harbor I forgot to delete the data-folder beforehand so it would connect to the old database.

Thank you anyways :)

**Comment by saitho** [comment]
I had the same issue, but it was because I had special characters (like %$§&") in the database password.
Removing them and setting up everything from scratch solved the connectivity issues.

**Comment by chance2021** [comment]
I have to add below env variables in the `values.yaml` in order to make core service work...
```
core:
  extraEnvVars:
  - name: POSTGRESQL_USERNAME
    value: <YourPostgresUsername>
  - name: POSTGRESQL_PASSWORD
    value: <YourPostgresPassword>

```
