### ISSUE TITLE
when use oss，can't use migration tools from 1.4.0 to 1.6+

### ISSUE THREAD

**Issue by KylinVnne** [goharbor/harbor#11440]
**Expected behavior and actual behavior:**
When upgrading my existing Habor(1.4.0) instance to a newer version(1.6.3), I encountered an error：
```bash
Exception: Error: no provider configurations are provided for provider oss
```
In my config file `harbor.cfg`,
```bash
registry_storage_provider_name = oss
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.4.0]
- docker engine version: [19.03.6]
- docker-compose version: [1.25.4]

**Comment by heww** [comment]
Please set `registry_storage_provider_config` (eg, oss key, secert, bucket, endpoint ...) for oss in harbor.cfg

**Comment by KylinVnne** [comment]
> Please set `registry_storage_provider_config` (eg, oss key, secert, bucket, endpoint ...) for oss in harbor.cfg

The current configuration is like this, but the prompt does not support. Only filesystem, I want to know whether it will affect the existing oss registry.

**Comment by KylinVnne** [comment]
I found this in src code , harbor/make/photon/prepare/utils/configs.py
![image](https://user-images.githubusercontent.com/24524834/78505881-f6f9d280-77a8-11ea-8052-f639664916b0.png)
Why?

**Comment by KylinVnne** [comment]
I miss registry_storage_provider_config
