### ISSUE TITLE
Is there any plan to support pull passthrough from 

### ISSUE THREAD

**Issue by OriBenHur-Any** [goharbor/harbor#11447]
We host our docker images on gcr.io, and we want to use an internal registry that will act as a pull passthrough to gcr.io to reduce the outbound network activity.

I saw that: https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md 
but it seems like it's only for docker hub, and it a bit out of date

**Comment by xaleeks** [comment]
@OriBenHur-Any  yep, we're tracking it on this ticket, please follow it https://github.com/goharbor/harbor/issues/8082
