### ISSUE TITLE
Replication to Azure Container Registry add project name in image name

### ISSUE THREAD

**Issue by fredgate** [goharbor/harbor#11442]
Harbor version 1.10.1

When I am replicating from Harbor to ACR (Azure Container Registry), the project name is added in ACR.

For example, if my project name is `production`, the images will be tagged like:
- `{harbor}/production/app:version`
- `{harbor}/production/sub/comp:version`

When replication occurs to ACR, I expect that images be named only
- `{acr}/app:version` not `{acr}/production/myapp:version`
- `{acr}/sub/comp:version` not `{acr}/production/sub/comp:version`

How to get rid of the project name from replicated images.

**Comment by fredgate** [comment]
Is it caused by a bad configuration or is it a bug?
#up

**Comment by joshisagar92** [comment]
hi @fredgate 

This out of the context but I would like to know as I am not able to replecate from Harbor to ACR

Following are the screen shot


![Harbor](https://user-images.githubusercontent.com/38806356/79854062-dfb90880-8396-11ea-98a5-27f581ffe266.png)

Test connection is suceess full

![harbor2](https://user-images.githubusercontent.com/38806356/79854204-18f17880-8397-11ea-9829-af0de565e24e.png)


When I try to replicate in logs it shows following error

**2020-04-21T09:57:52Z [ERROR] [/replication/transfer/image/transfer.go:340]: failed to push manifest of image ecw/db_multum:latest: http error: code 200, message**

**Comment by fredgate** [comment]
It has nothing to do with this issue. But @joshisagar92 you should change the provider of your registry : this is not a docker-registry but a Azure Container Registry.

**Comment by joshisagar92** [comment]
Hi @fredgate ,

I have created new issue https://github.com/goharbor/harbor/issues/11685.


I am using older harbor and it does not have option for acr. This is the reason I have used docker registry.

I have also tried with new version and facing same issue

**Comment by fredgate** [comment]
@ywk253100 @wy65701436 @reasonerjt Can someone take a look at this issue ?
