### ISSUE TITLE
Scanner `Clair` does not support image which manifest is schema 1

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11441]
There is a manifest which media type is `application/vnd.docker.distribution.manifest.v1+prettyjws`, these image is not support scan in v2.0.

Eg:  `redis@sha256:6c9f9cb9a250b12c15a92d8042a44f4557ca5bc590f36e63e529d52fb15b4ddc`

![image](https://user-images.githubusercontent.com/5634205/78977879-75f55f00-7b4b-11ea-8370-0bf6c52bb4bd.png)

How to reproduce the problem:
Add docker hub as replication regsitry, and replicate `library/redis:2.6` to harbor, the result is that `redis:2.6` is not supported to scan by clair.

**Comment by reasonerjt** [comment]
Let's fix it in "clair" and "trivy" scanner adapters.

**Comment by heww** [comment]
Scanner need to add "application/vnd.docker.distribution.manifest.v1+prettyjws" and "application/vnd.docker.distribution.manifest.v1+json" to its `consumes_mime_types` if it support to scan image which manifest is schema 1.

**Comment by steven-zou** [comment]
Talked to @danielpacak, Trivy does not support V1 schema at present. It seems not possible to enhance Trivy to support it in the 2.0 timeline. Let's remove the 2.0 label and plan it as a long-term item. The concrete supporting date depends on the Aqua team's prioritizing.

**Comment by steven-zou** [comment]
Specified this issue for Clair only.

For Trivy, open new issue: https://github.com/goharbor/harbor/issues/11611

**Comment by heww** [comment]
I tested the adapter with this PR https://github.com/goharbor/harbor-scanner-clair/pull/17 , but it will be failed to scan `redis:2.6` with error `worker: OS and/or package manager are not supported`. Let's add enhancement label to it and I will do  more investigation later.
