### ISSUE TITLE
Build from source for ARM platform fails with "exec format error"

### ISSUE THREAD

**Issue by zeraza** [goharbor/harbor#11453]
Hi,

I am trying to build harbor from source on a arm-based QNAP device. I have cloned the current git repository and try to build with the following command:

make build GOBUILDIMAGE=golang:1.13.8 COMPILETAG=compile_golangimage CLAIRFLAG=true NOTARYFLAG=true

The problem is that the build does not really build all harbor-related Docker images from source but pulls X86-based images from the Docker hub which lead to "exec format error" when trying to run these images.

My question: How do I rebuild these base images for the ARM platform? The official documentation does not seem to address this.

Thanks,

Peter

**Comment by hzliangbin** [comment]
@zeraza as the makefile say,  "make build " build Harbor docker images from photon baseimage, not output the images from source code but base on some other image.
the baseimage is needed but should be in arm-based form. check the docker info and make sure Experimental true. try to arm64-based images from dockerhub and the photon baseimages support arm64. https://hub.docker.com/_/photon?tab=tags

**Comment by smartczy** [comment]
I had the same problem when build image for `swagger`. No images for ARM after I searched swagger in dockerhub.com.

**Comment by smartczy** [comment]
I build success with version 1.7.4 according to this [blog](https://bbs.huaweicloud.com/forum/thread-49256-1-1.html).

**Comment by amoravek** [comment]
Is there any progress towards the arm64 arch? Currently it is impossible for me to build arm64 binaries even though I've used the photon 3.0 images, build docker-compose with the help of the ubiquiti/docker-compose-aarch64, but still I'm ending with exec format error every time.

Now, I'm stuck here:
make install GOBUILDIMAGE=golang:1.14.3 COMPILETAG=compile_golangimage
(guide from: https://goharbor.io/docs/2.0.0/build-customize-contribute/compile-guide/)

...produces:

generate all the files for API from api/v2.0/swagger.yaml
standard_init_linux.go:211: exec user process caused "exec format error"
Makefile:325: recipe for target 'gen_apis' failed
make: *** [gen_apis] Error 1

I use harbor every day on amd64 cluster, but now I need to run it also on purely amr64 one.

**Comment by smartczy** [comment]
> generate all the files for API from api/v2.0/swagger.yaml

I have searched swagger image on dockerhub.com. But didn't find the official image build for arm64. So I have to try the old version of harbor.

**Comment by zeraza** [comment]
To solve the exec format error for the swagger binary just must go to harbor/tools/swagger and change the name of the downloaded swagger binary in the Dockerfile to "swagger_linux_arm64".

**Comment by zeraza** [comment]
General comment: My target platform is actually ARM 32-bits, so I can't use the Photon3.0 images for ARM64. I had some success building the harbor 2.0 images for ARM 32 bit when using Debian Buster for ARM32 for the base images. This required tweaking of paths in the Dockerfiles since Debian has different default paths for things like PKI compared to Photon. The resulting images don't work for the time being, however. I had not the time yet to investigate further.

**Comment by hzliangbin** [comment]
@zeraza  may i know your using verision. I am trying to build the 2.0.0 for arm but the base image didn't have an arm image.https://hub.docker.com/r/goharbor/harbor-prepare-base/tags
