### ISSUE TITLE
Helm Hub adapter not respecting Insecure

### ISSUE THREAD

**Issue by pawalt** [goharbor/harbor#11454]
**Expected behavior and actual behavior:**

When Harbor attempts to reach out to Helm Hub from behind a proxy that messes with certificates, the healthchecks respond with `health check to registry https://hub.helm.sh failed: Get https://hub.helm.sh: x509: certificate signed by unknown authority` despite insecure being true.

**Steps to reproduce the problem:**

```
$ cat config/helm_hub.json
{
  "credential": {
    "access_key":"",
    "access_secret":"",
    "type":"basic"
  },
  "description":"test",
  "insecure":true,
  "name":"helm_hub",
  "type":"helm-hub",
  "url":"https://hub.helm.sh/"
}
$ curl --data-binary "@config/helm_hub.json" -H "Content-Type: application/json" -u "admin:admin" http://example.harbor.url.com/api/registries
{"code":400,"message":"health check to registry https://hub.helm.sh/ failed: Get https://hub.helm.sh: x509: certificate signed by unknown authority"}
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.1]
- docker engine version: [18.06.2]
- docker-compose version: N/A

**Additional context:**

This error appears to stem from the following code not factoring in the `insecure` option:
https://github.com/goharbor/harbor/blob/master/src/replication/adapter/helmhub/client.go#L94

**Comment by steven-zou** [comment]
@mmpei 

Please take a look to check if we need to do any enhancements.

**Comment by mmpei** [comment]
ok.
