### ISSUE TITLE
Support Redis AUTH

### ISSUE THREAD

**Issue by cten** [goharbor/harbor#11451]
The Helm chart supports passing a Redis password to the JobService and Chartmuseum but not Core. From my digging into the core code, I can't find that passing a Redis password is supported. For better security it would be good to support AUTH to Redis. 
Thanks

**Comment by heww** [comment]
In my mind, harbor core itself support password for the redis. For example, in this issue https://github.com/goharbor/harbor/issues/11367#issuecomment-607817014 ,  bjzqhe mentioned that when set password for redis , harbor works.

If you ensure that https://github.com/goharbor/harbor-helm not support password for redis, please create issue in harbor-helm.

**Comment by cten** [comment]
I understand that harbor-helm should also make changes to support Redis Auth, but I am unable to find how to configure the Redis password when using the the images https://github.com/goharbor/harbor/tree/master/make/photon/core built from the harbor repo.

**Comment by heww** [comment]
The following are redis env in core with password

```
_REDIS_URL=10.xx.xxx.xxx:6379,100,pass,0,30
_REDIS_URL_REG=redis://anonymous:pass@10.xx.xxx.xxx:6379/1
```

`10.xx.xxx.xxx` is the ip address of the redis, `pass` is the password of the redis.
