### ISSUE TITLE
Tag retention rules not working as expected - v1.10.1

### ISSUE THREAD

**Issue by rob8714** [goharbor/harbor#11450]
Facing an issue with tag retention rules when it comes to matching/excluding tags.  I have a very simple rule

For repositories matching: **
By image count or number of days: retain the most recently pushed # images (count = 1)
Tags: excluding master*

The results when running the retention rule are the following:

```
|                                 Digest                                   |       Tag       | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |

|--------------------------------------------------------------------------|-----------------|-------|--------|---------------------|---------------------|---------------------|-----------|

| sha256: 1111111111111111111111111111111111111111111111111111111111111111 | dev-123         | image |        | 2020/04/06 10:28:30 | 2020/04/06 10:28:43 | 2020/04/06 10:28:29 | DEL       |

| sha256: 2222222222222222222222222222222222222222222222222222222222222222 | master          | image |        | 2020/04/06 10:24:24 | 0001/01/01 00:00:00 | 2020/04/06 10:24:23 | DEL       |

| sha256: 3333333333333333333333333333333333333333333333333333333333333333 | rel-789         | image |        | 2020/04/06 10:27:26 | 2020/04/06 10:27:34 | 2020/04/06 10:27:25 | DEL       |

| sha256: 4444444444444444444444444444444444444444444444444444444444444444 | rel-123         | image |        | 2020/04/06 10:30:28 | 2020/04/06 10:30:31 | 2020/04/06 10:30:27 | RETAIN    |

| sha256: 5555555555555555555555555555555555555555555555555555555555555555 | rel-456         | image |        | 2020/04/06 10:25:27 | 2020/04/06 10:25:40 | 2020/04/06 10:25:26 | DEL       |
```

My expectation was that the rule would be applied on all the tags except master.

Tried to work around it by using instead:
Tags: matching rel*

Again, the retention is not as expected, it says it will delete all the tags that don't match rel* and then keep only one image matching tag rel*

```
|                                 Digest                                  |       Tag       | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |

|-------------------------------------------------------------------------|-----------------|-------|--------|---------------------|---------------------|---------------------|-----------|

| sha256: 1111111111111111111111111111111111111111111111111111111111111111 | dev-123         | image |        | 2020/04/06 10:28:30 | 2020/04/06 10:28:43 | 2020/04/06 10:28:29 | DEL       |

| sha256: 2222222222222222222222222222222222222222222222222222222222222222 | master          | image |        | 2020/04/06 10:24:24 | 0001/01/01 00:00:00 | 2020/04/06 10:24:23 | DEL       |

| sha256: 3333333333333333333333333333333333333333333333333333333333333333 | rel-789         | image |        | 2020/04/06 10:27:26 | 2020/04/06 10:27:34 | 2020/04/06 10:27:25 | DEL       |

| sha256: 4444444444444444444444444444444444444444444444444444444444444444 | rel-123         | image |        | 2020/04/06 10:30:28 | 2020/04/06 10:30:31 | 2020/04/06 10:30:27 | RETAIN    |

| sha256: 5555555555555555555555555555555555555555555555555555555555555555 | rel-456         | image |        | 2020/04/06 10:25:27 | 2020/04/06 10:25:40 | 2020/04/06 10:25:26 | DEL       |
```

**Comment by rob8714** [comment]
Looking at the documentation, it currently says the following for tags:

> If you selected matching, the rule is applied to the tags you identified. If you selected excluding, the rule is applied to all of the tags in the repository except for the ones that you identified.

From this I understand that tags that are not matched by the retention rule should not be deleted.

Can you clarify on this behavior please?

**Comment by xaleeks** [comment]
@rob8714  It's working as intended but you bring up a very good point.  The key to interpreting this is that you are configuring a retention policy, and not a deletion policy.  The 'exclude' modifier being applied to 'master*' means these are excluded from retention altogether, so they are deleted.  I guess to interpret excluding these as to be left alone and not deleted is also valid, if not more valid now that I think about it.  It's something we wrestled with when we were designing the UI.  

If you still think this is unintuitive and difficult to wrap your head around, we can discuss further and think about changing.  Btw, you are not the first one to bring this up.

**Comment by rob8714** [comment]
@xaleeks thanks for the feedback and the clarification. I do understand how it works now but I still think it is unintuitive to the end user.  I think it would be better and more flexible if the tags that are deleted are those that are matched by the retention policy, and those that are excluded are left alone.  Then one could add additional rules if needed to match these previously excluded tags.

Or maybe there could be an additional option defined in the rule on what to do about tags that are not matched by the rule? So one could either choose to delete tags that are not matched or keep them

**Comment by BradenBorg** [comment]
bump. Would be good to sort this feature out

**Comment by reasonerjt** [comment]
@xaleeks please clarify if this has to be addressed in 2.1.0 or not.

**Comment by vasily-v-ryabov** [comment]
We really need this feature! Please restore it.

**Comment by zhangguanzhang** [comment]
same issue

**Comment by vasily-v-ryabov** [comment]
`master**` instead of `master*` should help.
