### ISSUE TITLE
compiled artifacts in release

### ISSUE THREAD

**Issue by micheelengronne** [goharbor/harbor#11455]
**Is your feature request related to a problem? Please describe.**
Is it possible to have already compiled artifacts published in releases (with their sha256 and asc) ?

**Describe the solution you'd like**
I would like to use these artifacts in my own containers.

**Describe the development plan you've considered**
I plan to download releases source codes and build them in an internal CI to reuse them in my own containers.

**Comment by heww** [comment]
Do you mean release the binary of the harbor components?

**Comment by micheelengronne** [comment]
exactly.
