### ISSUE TITLE
harbor mirror not pull the image in itself

### ISSUE THREAD

**Issue by JadeQin** [goharbor/harbor#11464]
**Expected behavior and actual behavior:**
Harbor can pull the image from remote and store it.

**Steps to reproduce the problem:**
I config the harbor remoteurl 
```
proxy:
  remoteurl: https://dockerhub.azk8s.cn
```
I config the docker daemon.json
```
"registry-mirrors": ["https://***.***.com"]
```

`docker info` show it right,and I can pull image success.
But I can not find the image in Harbor UI.

**Versions:**
Please specify the versions of following systems.

- harbor version: [v1.10.1]
- docker engine version: [19.03.8]
- docker-compose version: [1.25.4]

**Comment by heww** [comment]
Closed because it is duplicated with https://github.com/goharbor/harbor/issues/8082
