### ISSUE TITLE
Vulnerabilities addition API will very slow when its response is too big

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11462]
When there are thousands of vulnerabilities for the image, the vulnerabilities addition API will be very slow. eg, 4039 vulnerabilities, response size is 3.7M, response time is 3.2s.

![image](https://user-images.githubusercontent.com/5634205/78624035-46c8be80-78bb-11ea-8208-abe29a646fd9.png)

**Comment by reasonerjt** [comment]
Let's not fix it in 2.0 and document as a known issue.
