### ISSUE TITLE
Document the potential impacts brought by the cron spec parsing change in the release notes

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11476]
PR #11473 make a change to the CRON spec parsing function to let the periodical job scheduling following the UTC timezone. This change may impact previous periodical job behaviors. So, we may need to explicitly document this change. 

Tracking issue: #11466

**Comment by renmaosheng** [comment]
I think this will be in our release note.

**Comment by steven-zou** [comment]
Already in the release notes. Close this issue now.
