### ISSUE TITLE
Trigger scanner on push

### ISSUE THREAD

**Issue by cblomart** [goharbor/harbor#11485]
**Is your feature request related to a problem? Please describe.**
To support our companies security policy we need information on vulnerability as soon as possible.

**Describe the solution you'd like**
We would like imaged scanned for vulnerabilities as soon as they are pushed to a repository.

**Describe the main design/architecture of your solution**
Call image scanners as soon as the image is fully pushed. A manual trigger is possible via the web interface so I do suppose a scan can be triggered after a push.

**Describe the development plan you've considered**
Scan the image as soon as it is pushed

**Comment by cblomart** [comment]
I get that this setting can be set on a project, we would like to have that globally.

**Comment by xaleeks** [comment]
Thanks for the feedback.  The solution you'd like is called 'Automatically scan images on push' and is already available in Harbor.  Regarding your request to make this available at a system level, please see my response to this issue https://github.com/goharbor/harbor/issues/11486#issuecomment-610778649
