### ISSUE TITLE
Limit actions on vulnerable images

### ISSUE THREAD

**Issue by cblomart** [goharbor/harbor#11486]
**Is your feature request related to a problem? Please describe.**
To respect our company policies it would help to be able to limit actions possible on images in function of the scanning results.

**Describe the solution you'd like**
A image whose scanning result is bad (with critical or major issues) shouldn't be downloadable from the registry.

**Describe the main design/architecture of your solution**
Pull requests should be forbidden if a critical or major issue if found. An exception could be placed by an admin to allow pulls of certain images to allow for operations to continue. This would force reflection and/or refactoring of images to get compliant.

**Describe the development plan you've considered**
If necessary a transition solution could be seen to warn users when they use vulnerable solutions (i.e. emails). This is really a cosmetic proposition as only the blocking of pulls and admin action that would trigger a reaction from an organization.

**Comment by steven-zou** [comment]
@cblomart 

Which version of Harbor are you using?

Harbor supports setting policies to prevent users from pulling vulnerable images as well as excludes some found CVEs via the whitelist. All these configurations can be found in the project settings of each project.

**Comment by cblomart** [comment]
Thanks, we are on version v1.10.1-f3e11715

The current policy is to let users create their projects so developers are owner of their projects. 

I get that a project can be configured to automatically scan images and prevent pull of vulnerable images or even unsigned images.

Is it possible to control this behavior globally and impose these settings on all projects?

**Comment by xaleeks** [comment]
It was a conscious decision to build this functionality at the project level and not at the system level. Perhaps there will come a time when we think about enabling this at the system level as a default system and allow project setting to override, but it is not on the roadmap yet  @cblomart

**Comment by cblomart** [comment]
We are having the discutions internaly to prevent developpers or team leaders to create their projects in habor.

We must ensure security measures are enforced in Harbor:
* Clair scan on a global schedule
* Clair scan on push request
* Prevent pull on images starting at a certain level of severity (i.e. 2 mediums or above)
* Prevent public projects

We will most probably need to handle project creation by a specific team (PKS team) and will need to automate that.
If the CSO requests it we may even need to audit these settings to be sure they don't change.

On clair level, I would reason it makes no harm to scan on pull and schedule for the whole system. Only clair would be annoyed by the extra work.

Preventing pulls or public repos is another story i think (more impacting).

**Comment by xaleeks** [comment]
Hi Cedric, 

like I said, everything you described already exists but at the project level.  We won't be doing this at the system level anytime soon because most users need the multi-tenancy that harbor projects provide.  If we move this control to the system level, it would break 90% of current workflows. 

'We are having the discutions internaly to prevent developpers or team leaders to create their projects in habor' 

I get what you mean, but these are things that need to be worked out internally and then the right actors can leverage existing features of Harbor.
