### ISSUE TITLE
It should return a 404 instead of 500 when to pull non-exist artifact

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11495]
I get a 500 when to pull a non-exist docker image, the error code should be 404. 

`Error response from daemon: received unexpected HTTP status: 500 Internal Server Error`

**Comment by wy65701436** [comment]
We should return the internal self-defined error instead of error. 

Otherwise, the pre-defined HTTP error code will be lost and gives a 500 eventually.

https://github.com/goharbor/harbor/blob/master/src/server/middleware/util.go#L51

**Comment by reasonerjt** [comment]
Fixed by https://github.com/goharbor/harbor/pull/11554
