### ISSUE TITLE
The UI load the >100 KB css file each time I switch between Dark/Light mode on UI.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11496]
When I click the Dark Mod icon on UI to switch the theme.

Each time I click it downloads the css file again，：

![Screen Shot 2020-04-08 at 11 34 55 AM](https://user-images.githubusercontent.com/2390463/78741872-17828200-798d-11ea-941b-eebb3b0b1f68.png)

 is it possible to cache it or package it in the portal package?  So it won't be downloaded again and again?

**Comment by AllForNothing** [comment]
It is the best practice for now

**Comment by zhoumeina** [comment]
Hi Yogi, 
Could you please take care of this issue? You can refer the document I send to you to set the cache control properties for nginx configuration to make sure all static files will be cached.
