### ISSUE TITLE
harbor 2.0 docker  pull return 500 when tag not exist

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11507]
build 3253

![image](https://user-images.githubusercontent.com/188115/78753540-83beaf00-79a8-11ea-8c65-a52834249b86.png)

step:
1. clone images from hub.docker.com/arm32v6/jetty
2. docker pull x.x.x.x/arm32v6/jetty from a macbook
3. there's actually no tag latest
4. harbor return 500
it should return something like 404

**Comment by bitsf** [comment]
error message comes from

![image](https://user-images.githubusercontent.com/188115/78756468-6e984f00-79ad-11ea-99f7-ffd7c1f0362a.png)

**Comment by wy65701436** [comment]
dup with https://github.com/goharbor/harbor/issues/11495
