### ISSUE TITLE
With content trust policy enabled, a signed image cannot be pulled

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11504]
I have an image signed and pushed to Harbor
<img width="987" alt="Screen Shot 2020-04-08 at 1 12 25 PM" src="https://user-images.githubusercontent.com/2390463/78747002-e1e49580-799a-11ea-9743-5974ef76287d.png">

It shows the tag `test-signed` is signed in API and UI but I still cannot pull it via CLI:
```
:/var/log/harbor# export DOCKER_CONTENT_TRUST=0
:/var/log/harbor# docker pull jt-dev.local.goharbor.io/library/redis:test-signed
Error response from daemon: unknown: The image is not signed in Notary.
```

I checked the log of core there's no any helpful information.

**Comment by wy65701436** [comment]
after investigation, the root cause should be EnsureArtifactDigest can't set digest into context.
https://github.com/goharbor/harbor/blob/master/src/server/middleware/util.go#L39.

**Comment by reasonerjt** [comment]
Fixed by 
https://github.com/goharbor/harbor/pull/11554
