### ISSUE TITLE
Robot Expiration

### ISSUE THREAD

**Issue by OrwillT** [goharbor/harbor#11502]
Is there a way to extend the validity of the robot account after it expires, or make it never expire?

**Comment by wy65701436** [comment]
So for, it doesn't. But, the `never expire` will be supported in Harbor v2.0.0.

You can extend the expiration date on the configuration page, set it to `9999` to have a workaround it.

**Comment by bitsf** [comment]
The token is JWT token, which also includes the expires time in the token, so have to create new token after expires.
You can decode it yourself.
![image](https://user-images.githubusercontent.com/188115/78766853-63005480-79bc-11ea-88ae-b1fa49c9d96f.png)

**Comment by bitsf** [comment]
The token is JWT token, which also includes the expires time in the token, so have to create new token after expires.
You can decode it yourself.
![image](https://user-images.githubusercontent.com/188115/78766853-63005480-79bc-11ea-88ae-b1fa49c9d96f.png)
