### ISSUE TITLE
"Overview" is confusing in the artifact details page

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11500]
![image](https://user-images.githubusercontent.com/2841473/78743136-56660700-7990-11ea-8378-2377bd15f6aa.png)

Use "General" instead?

**Comment by steven-zou** [comment]
Don't understand why 'Overview' is confused. Actually `General` is not an accurate term for such properties.

@wy65701436 

cc @xaleeks

**Comment by wy65701436** [comment]
confusing is beacuse that the information is actually not about the `overview` of this artifact.

**Comment by reasonerjt** [comment]
@xaleeks please help make a decision and add comment

**Comment by xaleeks** [comment]
I think 'overview' is appropriate
