### ISSUE TITLE
 Csrf was not successfully set in the cookie   when harbor is http environment

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#11514]
![image](https://user-images.githubusercontent.com/29826789/78761987-eb2f2b80-79b5-11ea-87e8-9020b6d7c061.png)

**Comment by reasonerjt** [comment]
After debugging, this issue happens when the same browser accessed the same host with https.
This looks like a security mechanism in browser that if it handles the secure cookie of the same site it will drop insecure cookies
