### ISSUE TITLE
The 127.0.0.1 should be added into the certificate of core when mTLS is enabled

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#11521]
In some Kubernetes deployment, the hairpin mode is disabled by default, and the pod cannot access itself by service.
Core needs to call itself in replication, so we replace the hostname of core with 127.0.0.1 to workaround the hairpin issue, but this will cause failure when the mTLS is enabled.
So we should add 127.0.0.1 into the IP san of the core certificate.

BTW, the hairpin issue fix https://github.com/goharbor/harbor/pull/11484 isn't merged yet. After it is merged, we should verify the solution

**Comment by reasonerjt** [comment]
@ywk253100 can we not access itself?
This will be tricky, because most of the cases I expect user generate the certs.

**Comment by reasonerjt** [comment]
for non-mTLS we can use insecure transport to access 127.0.0.1
For mTLS we have to add a release note.

**Comment by ninjadq** [comment]
disable mtls to work around
#11688  #11709
