### ISSUE TITLE
after enabling "content trust" policy in project I cannot pull helm chart via helm v3

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11523]
The reason behind it is that in Harbor's use-case the image is signed via docker-content-trust.

And when pulling a manifest artifact the middleware will check the signature against notary, and when notary doesn't have information about the signature of the artifact of the chart the middleware blocks the request.    

There are 2 options:
1)  Skip the artifacts that can't be supported and document it, i.e. those can't be handled by docker-contest-trust.  The UI may be a little inconsistent but it's acceptable.  

2） Provide guidelines to users to help them sign the artifact, we don't know what the commands should be, need some investigation, but it should work based on my understanding.
The commands will be tedious and tricky, in addition the key management will also be tricky because the root key may have been generated already.

3） Leave it as is, the impact will be, when user wants to put images and charts in one project, and use content trust policy to cover the images, charts cannot be pulled.

Personally I prefer option 1).

**Comment by reasonerjt** [comment]
`docker app` has the same problem when handling cnab

**Comment by renmaosheng** [comment]
the notary needs to support OCI format if we want to support the signing for all types of artifacts? could we raise this in the notary discussion?thanks.

**Comment by reasonerjt** [comment]
@renmaosheng 

notary can sign anything , the problem is the user experience in Harbor is tied to `DOCKER_CONTENT_TRUST`, when you set the env var, docker will sign the image and push to notary.   (see option 2)

I don't think docker content trust can handle other artifacts even in the future.  

We need to move away from docker content trust if we want to introduce a consistent workflow for signing artifacts.  Unlike public cloud service, there will never be a KMS in Harbor, so probably it has to be a separate flow that the user signs the artifact and do another push.

**Comment by reasonerjt** [comment]
We don't want to add ad-hoc code which we need to remove later.
So for 2.0.0 we'll choose 3), and explicitly mention in the doc that they need to figure out how to sign a chart using notary.

**Comment by xaleeks** [comment]
3 is acceptable, since notary isn't limited to signing container images, no need to treat helm charts and others separately.  Adding note for docs that if user wants to be able to pull unsigned helm charts (as is the case for most scenarios), he will have to store these on a different project from the one hosting images that he wishes to enforce 'pull only when signed'

**Comment by renmaosheng** [comment]
It seems  we need to raise issue in the OCI meeting eventually propose some idea to address it.

**Comment by reasonerjt** [comment]
let's make sure this is mentioned in the doc.

**Comment by reasonerjt** [comment]
For consistency, we won't suggest user store images and charts in one project with content trust enabled.

When notary-v2 is implemented the signature will be artifact neutral.

If there's requirement we may spend some time to provide a way to sign OCI artifact with notary v1.
