### ISSUE TITLE
Internal Server Error for Pull-based replication rule between two Harbor instances 

### ISSUE THREAD

**Issue by cleman95** [goharbor/harbor#11525]
**Overview:** 
I'm trying to replicate the registries from an harbor instance to an other harbor instance.
pull based replication rule can't be created when selecting the source registry as the other harbor instance. it has an error message "Internal Server Error".

**Expected behavior:**
when creating a pull based replication rule with: 

- source registry: the endpoint of the other harbor instance
- source ressource name: library/**
- destination namespace: library

I expect the replication task to pull all my repositories inside the project library of the other Harbor instance into the project library my Harbor instance.

 **actual behavior:**
when creating a pull based replication rule with: 

- source registry: the endpoint of the other Harbor instance

An error message is displayed: " Internal Server Error". Input field for the source resource filter are not displayed.

**Environment :**

OS : Centos 7
Kubernetes version : 1.16.7
Chart Helm version : harbor-1.3.1
Harbor version: 1.10.1
Helm version: 2

**Steps to reproduce the problem:**
So first, deploy two harbor instances on a kubernetes cluster using Helm, Harbor 1 and Harbor 2.
Then, create :

- a registry on the Harbor 1 (with the ip adress of the Harbor 2)
- a pull based replication rule on Harbor 1 targeting the Harbor 2.
The replication rule is configured like this :

source registry: Harbor 2

**Additional context:**

**- Log files:**
`2020/04/08 15:13:12.101 [D] [server.go:2774]  |   10.233.67.87| 200 |   1.231746ms|   match| GET      /api/ping   r:/api/ping
2020-04-08T15:13:14Z [ERROR] [/common/api/base.go:233]: failed to get registry info 5: invalid character '<' looking for beginning of value
2020-04-08T15:13:14Z [ERROR] [/common/api/base.go:73]: GET /api/registries/5/info failed with error: {"code":500,"message":"Internal Server Error"}
2020/04/08 15:13:14.927 [D] [server.go:2774]  |      127.0.0.1| 500 |   2.470369ms|   match| GET      /api/registries/5/info   r:/api/registries/:id/info
`

**Comment by ywk253100** [comment]
Is the source Harbor instance healthy?
Could you try to curl the API of source Harbor: 
`curl -i http(s)://the_ip_of_source/api/systeminfo`?

**Comment by cleman95** [comment]
yes the source Harbor is healthy. I'm getting this for the curl :

`HTTP/1.1 200 OK
Content-Length: 463
Content-Type: application/json; charset=utf-8
Server: beegoServer:1.12.1
Set-Cookie: sid=8052ae50f7d11c5706e3693cb8146f2d; Path=/; HttpOnly
Set-Cookie: _xsrf=akxUVHJEOTdrSDRuVE9ZR0lmMGxNVWdaTEdRS285blc=|1586966029182871736|f89c9e85b79c2f555ce41fa8002717044270cd4818dbc51db4ed20e683d85c24; Expires=Wed, 15 Apr 2020 16:53:49 UTC; Max-Age=3600; Path=/
Date: Wed, 15 Apr 2020 15:53:49 GMT

{
  "with_notary": false,
  "with_admiral": false,
  "admiral_endpoint": "NA",
  "auth_mode": "db_auth",
  "registry_url": "core.harbor.domain",
  "external_url": "https://core.harbor.domain",
  "project_creation_restriction": "everyone",
  "self_registration": false,
  "has_ca_root": true,
  "harbor_version": "v1.10.1-f3e11715",
  "registry_storage_provider_name": "filesystem",
  "read_only": false,
  "with_chartmuseum": true,
  "notification_enable": true
`

**Comment by Srikrishnabh** [comment]
@cleman95 is your target registry endpoint correct make sure you have not added '/' at end of your target registry endpoint.

**Comment by cleman95** [comment]
Yes there is no '/' at the end of my endpoint.

**Comment by chaulexiong** [comment]
I have the same problem. Does anyone know the reason?
