### ISSUE TITLE
Task: non-blocking GC user story - GC needs to be non-blocking, no impact to push / pull / delete etc

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11537]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a project admin / developer / guest, I can continue pushing / pulling / deleting images to Harbor while a GC job is under execution with no risk of data loss or data corruption.

**Comment by wy65701436** [comment]
clost it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
