### ISSUE TITLE
Replication policy wildcards issue

### ISSUE THREAD

**Issue by mdraijer** [goharbor/harbor#11531]
**Expected behavior:**

When I specify `my-project/{a,b,c}**` in the Source resource filter -> Name field of a replication policy, then this should match images 'my-project/a-something:1.0' and 'my-project/b-something:1.0', but _also_ 'my-project/a-something/my-image:1.0'.

**Actual behavior:**

The pattern does _not_match 'my-project/a-something/my-image:1.0'. In order to match mentioned image you need the pattern `my-project/{a,b,c}**/**`.

So, in order to match all mentioned images, you need to specify _two_ replication policies, each with one of the above patterns.

**Steps to reproduce the problem:**

Push images with mentioned names to Harbor A. Define replication policies with mentioned Name patterns in Harbor B.

**Versions:**

- harbor version: 1.9.3

**Additional context:**

Documentation mentions:
```
*: Matches any sequence of non-separator characters /.
**: Matches any sequence of characters, including path separators /.
```
on https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-rules/

**Comment by ywk253100** [comment]
This isn't supported by the pattern matching library(https://github.com/bmatcuk/doublestar#doublestar) that replication uses:
```
Note that the doublestar must appear as a path component by itself. A pattern such as /path** is invalid and will be treated the same as /path*, but /path*/** should achieve the desired result.
```

And we should update the doc to mention this notes.

**Comment by mdraijer** [comment]
I suggest you explicitly mention the link to the used library in the documentation. That makes it much easier for users to learn how to use the patterns.
For example the abiity to use character classes is also not mentioned in the docs, but would have helped us a lot.

**Comment by bitsf** [comment]
fixed doc with PR https://github.com/goharbor/harbor/pull/11888
