### ISSUE TITLE
Task: non-blocking GC user story - GC should have scheduled tasking capability

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11536]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, I can configure GC to run at scheduled times and on specific days of the week or month and can enable or disable the scheduled GC job at will.

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
