### ISSUE TITLE
Task: non-blocking GC user story - GC should have dry run capability

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11535]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, I can execute GC at will (as long as there’s no ongoing GC job running) and can first execute a “dry run” which will display an estimate of disk space freed along with the list of blobs that will be garbage collected. No data is actually garbage collected from performing a dry run. After hitting 'GC now' button, it should stay grayed out until GC is completed.

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
