### ISSUE TITLE
Task: non-blocking GC user story - GC should support OCI artifacts

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11538]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, my GC job can garbage collect any OCI artifacts stored in blob format following docker v2 spec including container images, manifest lists, helm charts (stored in OCI registry and not in chartmusem), OPA bundles, CNAB bundles etc

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
