### ISSUE TITLE
Suggestion on adding member.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#1153]
1, I am trying to add a member to my project, but somehow I forget the member's exactly name. How can I handle this as I only get the error message to index that the member doesn't exist? Is it possible to list users fuzzy match the name that I am typing? Also, it's better to support to add with email address.

2, Should let the admin to select the entitlement instead of giving an default value(Project Admin). If there needs to be set a default value, it should be the minimum(Guest).

**Comment by wy65701436** [comment]
Harbor Version: 0.5.0-rc1

**Comment by reasonerjt** [comment]
There is hint on the UI now.  Closing this issue.
