### ISSUE TITLE
Task: non-blocking GC user story - GC should resolve correctly against quotas

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11543]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, I can verify that immediately after running GC, the storage usage of Harbor should be the same as the disk consumption shown in project quotas. This should take into account any blobs shared across multiple projects, i.e. aggregated project quotas could be larger than storage usage.

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
