### ISSUE TITLE
Task: non-blocking GC user story - GC should be able to be disabled from harbor instance

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11542]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, I can disable GC so garbage collection is never run. I can achieve this by setting the schedule to 'none'

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
