### ISSUE TITLE
Can not pull images from nvidia NGC

### ISSUE THREAD

**Issue by qzwlinux** [goharbor/harbor#11548]
What can we help you?
I find images in `https://ngc.nvidia.com/`

I can't download images use harbor

When i login nvcr.io , it error ,so i only use `https://nvcr.io/proxy_auth`
![storage](https://user-images.githubusercontent.com/46511491/78874933-b8ea0080-7a7f-11ea-8bea-8c9f2da2c90a.png)

but i can not find some images in here
![深度截图_选择区域_20200409163615](https://user-images.githubusercontent.com/46511491/78875882-234f7080-7a81-11ea-8aaf-4bfe00f4485d.png)
![深度截图_选择区域_20200409163600](https://user-images.githubusercontent.com/46511491/78875888-24809d80-7a81-11ea-9a3f-b787248c6df3.png)

**Comment by wy65701436** [comment]
could you please provide harbor logs?

**Comment by qzwlinux** [comment]
Apr  9 15:47:22 172.19.0.1 core[1214]: 2020-04-09T07:47:22Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://nvcr.io: Head http://nvcr.io/v2/: Get http://nvcr.io/v2/: dial tcp 52.11.24.105:80: connect: connection timed out
Apr  9 15:47:22 172.19.0.1 core[1214]: 2020-04-09T07:47:22Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Apr  9 15:47:22 172.19.0.1 core[1214]: 2020/04/09 07:47:22 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m|4m14.790702074s|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 15:47:41 172.19.0.1 core[1214]: 2020/04/09 07:47:41 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    871.013µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:48:11 172.19.0.1 core[1214]: 2020/04/09 07:48:11 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    973.364µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:48:42 172.19.0.1 core[1214]: 2020/04/09 07:48:42 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.698641ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:49:13 172.19.0.1 core[1214]: 2020/04/09 07:49:13 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    771.339µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:49:29 172.19.0.1 core[1214]: 2020-04-09T07:49:29Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry https://nvcr.io: http error: code 401, message
Apr  9 15:49:29 172.19.0.1 core[1214]: 2020-04-09T07:49:29Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Apr  9 15:49:29 172.19.0.1 core[1214]: 2020/04/09 07:49:29 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m| 8.845143339s|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 15:49:43 172.19.0.1 core[1214]: 2020/04/09 07:49:43 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    757.652µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:50:00 172.19.0.1 core[1214]: 2020-04-09T07:50:00Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry https://nvcr.io: http error: code 401, message
Apr  9 15:50:00 172.19.0.1 core[1214]: 2020-04-09T07:50:00Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"registry https://nvcr.io is unhealthy: unhealthy"}
Apr  9 15:50:00 172.19.0.1 core[1214]: 2020/04/09 07:50:00 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m| 2.339667775s|   match|#033[46m POST    #033[0m /api/registries   r:/api/registries#033[0m
Apr  9 15:50:14 172.19.0.1 core[1214]: 2020/04/09 07:50:14 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    733.791µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:50:44 172.19.0.1 core[1214]: 2020/04/09 07:50:44 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.328802ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:51:15 172.19.0.1 core[1214]: 2020/04/09 07:51:15 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    882.522µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:51:17 172.19.0.1 core[1214]: 2020-04-09T07:51:17Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://nvcr.io: Head http://nvcr.io/v2/: Get http://nvcr.io/v2/: dial tcp 52.11.24.105:80: connect: connection timed out
Apr  9 15:51:17 172.19.0.1 core[1214]: 2020-04-09T07:51:17Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Apr  9 15:51:17 172.19.0.1 core[1214]: 2020/04/09 07:51:17 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m| 4m14.762615s|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 15:51:45 172.19.0.1 core[1214]: 2020/04/09 07:51:45 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    989.709µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:52:16 172.19.0.1 core[1214]: 2020/04/09 07:52:16 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    817.229µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:52:47 172.19.0.1 core[1214]: 2020/04/09 07:52:47 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    994.639µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:52:59 172.19.0.1 core[1214]: 2020-04-09T07:52:59Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry https://nvcr.io: http error: code 401, message
Apr  9 15:52:59 172.19.0.1 core[1214]: 2020-04-09T07:52:59Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"registry https://nvcr.io is unhealthy: unhealthy"}
Apr  9 15:52:59 172.19.0.1 core[1214]: 2020/04/09 07:52:59 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m|  3.03689968s|   match|#033[46m POST    #033[0m /api/registries   r:/api/registries#033[0m
Apr  9 15:53:07 172.19.0.1 core[1214]: 2020-04-09T07:53:07Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry https://nvcr.io: http error: code 401, message
Apr  9 15:53:07 172.19.0.1 core[1214]: 2020-04-09T07:53:07Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"registry https://nvcr.io is unhealthy: unhealthy"}
Apr  9 15:53:07 172.19.0.1 core[1214]: 2020/04/09 07:53:07 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m| 1.626241184s|   match|#033[46m POST    #033[0m /api/registries   r:/api/registries#033[0m
Apr  9 15:53:17 172.19.0.1 core[1214]: 2020/04/09 07:53:17 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    879.189µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:53:48 172.19.0.1 core[1214]: 2020/04/09 07:53:48 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   1.024439ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:54:18 172.19.0.1 core[1214]: 2020/04/09 07:54:18 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    965.571µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:54:23 172.19.0.1 core[1214]: 2020-04-09T07:54:23Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://nvcr.io: Head http://nvcr.io/v2/: Get http://nvcr.io/v2/: dial tcp 52.11.24.105:80: connect: connection timed out
Apr  9 15:54:23 172.19.0.1 core[1214]: 2020-04-09T07:54:23Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"registry http://nvcr.io is unhealthy: unhealthy"}
Apr  9 15:54:23 172.19.0.1 core[1214]: 2020/04/09 07:54:23 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m|4m14.468743902s|   match|#033[46m POST    #033[0m /api/registries   r:/api/registries#033[0m
Apr  9 15:54:49 172.19.0.1 core[1214]: 2020/04/09 07:54:49 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.405229ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:55:19 172.19.0.1 core[1214]: 2020/04/09 07:55:19 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    934.152µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:55:40 172.19.0.1 core[1214]: 2020-04-09T07:55:40Z [ERROR] [/replication/adapter/googlegcr/adapter.go:129]: failed to ping registry http://nvcr.io: Get http://nvcr.io/v2/: Get http://nvcr.io/v2/: dial tcp 52.11.24.105:80: connect: connection timed out
Apr  9 15:55:40 172.19.0.1 core[1214]: 2020-04-09T07:55:40Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Apr  9 15:55:40 172.19.0.1 core[1214]: 2020/04/09 07:55:40 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m|4m14.934065896s|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 15:55:50 172.19.0.1 core[1214]: 2020/04/09 07:55:50 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    889.355µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:56:20 172.19.0.1 core[1214]: 2020/04/09 07:56:20 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    823.374µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:56:51 172.19.0.1 core[1214]: 2020/04/09 07:56:51 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    693.713µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:57:22 172.19.0.1 core[1214]: 2020/04/09 07:57:22 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    892.707µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:57:52 172.19.0.1 core[1214]: 2020/04/09 07:57:52 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    756.987µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:58:23 172.19.0.1 core[1214]: 2020/04/09 07:58:23 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.535098ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:58:53 172.19.0.1 core[1214]: 2020/04/09 07:58:53 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    919.191µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:59:24 172.19.0.1 core[1214]: 2020/04/09 07:59:24 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   1.135465ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 15:59:54 172.19.0.1 core[1214]: 2020/04/09 07:59:54 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.418637ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 16:00:25 172.19.0.1 core[1214]: 2020/04/09 08:00:25 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    822.459µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 16:00:55 172.19.0.1 core[1214]: 2020/04/09 08:00:55 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|    818.281µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Apr  9 16:01:10 172.19.0.1 core[1214]: 2020-04-09T08:01:10Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:10 172.19.0.1 core[1214]:
Apr  9 16:01:10 172.19.0.1 core[1214]: 2020-04-09T08:01:10Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:10 172.19.0.1 core[1214]: 2020/04/09 08:01:10 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 1.227368421s|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:13 172.19.0.1 core[1214]: 2020-04-09T08:01:13Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:13 172.19.0.1 core[1214]:
Apr  9 16:01:13 172.19.0.1 core[1214]: 2020-04-09T08:01:13Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:13 172.19.0.1 core[1214]: 2020/04/09 08:01:13 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 203.094305ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:14 172.19.0.1 core[1214]: 2020-04-09T08:01:14Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:14 172.19.0.1 core[1214]:
Apr  9 16:01:14 172.19.0.1 core[1214]: 2020-04-09T08:01:14Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:14 172.19.0.1 core[1214]: 2020/04/09 08:01:14 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 203.290111ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:14 172.19.0.1 core[1214]: 2020/04/09 08:01:14 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 203.290111ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:15 172.19.0.1 core[1214]:
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020/04/09 08:01:15 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 226.397921ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:15 172.19.0.1 core[1214]:
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020/04/09 08:01:15 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 200.033259ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:15 172.19.0.1 core[1214]:
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020-04-09T08:01:15Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:15 172.19.0.1 core[1214]: 2020/04/09 08:01:15 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 274.257453ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:16 172.19.0.1 core[1214]: 2020-04-09T08:01:16Z [ERROR] [/common/api/base.go:233]: failed to check health of registry https://nvcr.io/proxy_auth: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {"detail":"Incorrect authentication credentials"}
Apr  9 16:01:16 172.19.0.1 core[1214]:
Apr  9 16:01:16 172.19.0.1 core[1214]: 2020-04-09T08:01:16Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":500,"message":"Internal Server Error"}
Apr  9 16:01:16 172.19.0.1 core[1214]: 2020/04/09 08:01:16 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[41m 500 #033[0m| 200.367943ms|   match|#033[46m POST    #033[0m /api/registries/ping   r:/api/registries/ping#033[0m
Apr  9 16:01:17 172.19.0.1 core[1214]: 2020-04-09T08:01:17Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"health check to registry https://nvcr.io/proxy_auth failed: generate 'docker-hub' type adapter form factory error: login to dockerhub error: login to dockerhub error: {\"detail\":\"Incorrect authentication credentials\"}\n\n"}
Apr  9 16:01:17 172.19.0.1 core[1214]: 2020/04/09 08:01:17 #033[1;44m[D] [server.go:2774] |  192.168.50.25|#033[43m 400 #033[0m| 204.383411ms|   match|#033[46m POST    #033[0m /api/registries   r:/api/registries#033[0m
Apr  9 16:01:26 172.19.0.1 core[1214]: 2020/04/09 08:01:26 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   1.093749ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m






thank you




| |
qzwlinux
|
|
qzwlinux@163.com
|
签名由网易邮箱大师定制
On 4/10/2020 00:41，Wang Yan<notifications@github.com> wrote：

could you please provide harbor logs?

**Comment by steven-zou** [comment]
You need to make sure the NGC is compatible with docker-registry (no namespace). If there are namespaces in NGC, then a specified adapter needs to cover the task of reading namespaces.

**Comment by qzwlinux** [comment]
I can login nvcr.io use docker 
 


and I can download images  from `nvcr.io/nvidia/deepstream-l4t:5.0-dp-20.04-base`


but when i login harbor use  docker-registry , i can not login success


so..... , i don't know how to do
Thankyou




| |
qzwlinux
|
|
qzwlinux@163.com
|
签名由网易邮箱大师定制
On 5/20/2020 15:39，Steven Zou<notifications@github.com> wrote：

You need to make sure the NGC is compatible with docker-registry (no namespace). If there are namespaces in NGC, then a specified adapter needs to cover the task of reading namespaces.

**Comment by qzwlinux** [comment]
I can login nvcr.io use docker

```bash
$docker login nvcr.io

Username: $oauthtoken
Password: <Your Key>
```

and I can download images  from `nvcr.io/nvidia/deepstream-l4t:5.0-dp-20.04-base`

```bash
em:~/ $ docker pull nvcr.io/nvidia/deepstream-l4t:5.0-dp-20.04-base                                                                                 [16:02:01]
5.0-dp-20.04-base: Pulling from nvidia/deepstream-l4t
3b5e2c02f523: Downloading [>                                                  ]    538kB/288.4MB
b9448035bb0a: Downloading [=>                                                 ]  2.157MB/66.62MB
ec9ea6732d09: Download complete 
515b0d7ffbf7: Download complete 
7663c88dd173: Waiting 
5dd4bd16e931: Waiting 
5231bd433c70: Waiting 
9e017cdad796: Waiting 
0c8ba4b0f40b: Waiting 
de2653fc4eda: Waiting 
21b3dc12ac76: Waiting 
18d3041d2711: Waiting 
8b4bed079038: Waiting 

```

but when i  add new target use  docker-registry , i can not login success
provider : docker-registry
target name :ngc
target url: https://nvcr.io
access id : $oauthtoken
access pass: ******

so..... , i don't know how to do
Thankyou
