### ISSUE TITLE
The status “Succeed” should say “Succeeded”

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#11546]
/api/v2.0/replication/executions

![image](https://user-images.githubusercontent.com/30999793/78870374-9bfdff00-7a78-11ea-90cb-ba2b6a4172f6.png)

**Comment by AllForNothing** [comment]
This is required by Alex

**Comment by reasonerjt** [comment]
In the UI it should transform the status.

The status cannot be changed in backend as it's used as a state.

**Comment by xaleeks** [comment]
@AllForNothing  What is the status here?  We need to fix this somehow, 'succeed' is just plain wrong
