### ISSUE TITLE
Maybe providing a `USE SYSTEM DEFAULT` in the project scanner setting page is more friendly 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11545]
Once the project admin selects the scanner for the specified project, it has no chance to keep consistent with the system scanner setting anymore unless manually set the scanner that is also system default (actually the capability of removing project-level scanner setting metadata should be supported).

<img width="963" alt="Screen Shot 2020-04-09 at 15 21 17" src="https://user-images.githubusercontent.com/5753287/78868775-14af8c00-7a76-11ea-86f9-1f0366d410b4.png">

**Comment by AllForNothing** [comment]
This now can be closed
