### ISSUE TITLE
Trivy should not be the default scanner when user already installed the clair 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11549]
Install Harbor 1.9.0 with clair
Upgrade to Harbor tile 2.0 
The default scanner becomes trivvy.
It is OK if it is a fresh install, but current is an upgrade, it could not be the customer expected. they would like to take the clair as the default scanner.

<img width="1261" alt="Screen Shot 2020-04-09 at 5 25 28 PM" src="https://user-images.githubusercontent.com/2696760/78880170-95c34f00-7a87-11ea-93b6-ccfb4e3d9748.png">

**Comment by steven-zou** [comment]
It was fixed by the PR https://github.com/goharbor/harbor/pull/11558. Close it now.
