### ISSUE TITLE
Task: non-blocking GC user story - GC jobs should product logs

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11541]
> This issue is a sub-task of the non-blocking Garbage Collection epic (#11534 )

As a system admin, I can view logs of GC jobs which lists Job ID, trigger type, status, start time, finish time, disk space deallocated, #of blobs deleted (see screenshot below).

**Comment by wy65701436** [comment]
close it per https://github.com/goharbor/harbor/issues/11534#issuecomment-657994172
