### ISSUE TITLE
Some UI improvements

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11556]
1. the icon message about clicking the OCI index is "click this icon to enter the Artifac list of refer", it needs to be changed to "click to view this OCI index's artifact list"? 
<img width="1672" alt="Screen Shot 2020-04-09 at 4 50 45 PM" src="https://user-images.githubusercontent.com/14900967/78908250-67a83400-7ab4-11ea-8d85-4dd72747ac2a.png">

2. the view documentation link of image scanners is porting to a deprecated page, we should change to the correct document link. 
<img width="1673" alt="Screen Shot 2020-04-09 at 4 41 23 PM" src="https://user-images.githubusercontent.com/14900967/78908270-6d057e80-7ab4-11ea-8e1a-8fe6f8c8cecc.png">

**Comment by renmaosheng** [comment]
@xaleeks to give suggestion on the first issue about the message content.

**Comment by reasonerjt** [comment]
for 2. it should link to goharbor.io

**Comment by jwangyangls** [comment]
issue 1 : fix by #11530

**Comment by xaleeks** [comment]
@jwangyangls  I would link to this page which has all the relevant info, https://goharbor.io/blog/harbor-1.10-release/#vulnerability-scanning-with-pluggable-scanners
