### ISSUE TITLE
"Upgrading Harbor" documentation not found.

### ISSUE THREAD

**Issue by ogra** [goharbor/harbor#11559]
Page Not Found
https://goharbor.io/docs/1.10/administration/upgrade/upgrade-migrate-data.md

**Comment by wy65701436** [comment]
it's in https://goharbor.io/docs/1.10/administration/upgrade/

**Comment by ogra** [comment]
@wy65701436 Thank you.

"Upgrading Harbor" link in the following page is not correct.

https://goharbor.io/docs/1.10/administration/
