### ISSUE TITLE
 HELM install - pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor#11550]
Hello folks!

My issue:

- Centos 7
- Kubernetes 1.15

steps:

1. helm repo add harbor https://helm.goharbor.io
2. helm install --name harbor harbor/harbor 

than i got erro on my pods: 

``pod has unbound immediate PersistentVolumeClaims (repeated 7 times)``

listing:

``  kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        STORAGECLASS       REASON   AGE
consul-2                                   10Gi       RWO            Retain           Bound       default/consul-3             manual                      71d
consul-3                                   10Gi       RWO            Retain           Bound       default/vol-postgres         manual                      71d
consul-data                                1Gi        RWO            Retain           Available                                local-storage               126d
consul-l                                   10Gi       RWO            Retain           Released    default/consul-2             manual                      71d
data-consul-0                              10Gi       RWO            Retain           Bound       default/data-consul-0        manual                      119d
data-consul-1                              10Gi       RWO            Retain           Bound       default/data-consul-1        manual                      119d
data-consul-2                              10Gi       RWO            Retain           Bound       default/data-consul-2        manual                      119d
data-consul-pv0                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      119d
data-consul-pv1                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      7d21h
minio-pv-volume                            15Gi       RWO            Retain           Bound       default/minio-pv-claim       manual                      154d
my-local-pv                                500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv2                               500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv3                               500Gi      RWO            Retain           Available                                my-local-storage            2d
postgres-volume                            10Gi       RWO            Retain           Bound       default/consul-1             manual                      105d
pv-volume10                                10Gi       RWX            Retain           Bound       sonar/sonar-temp-pv-claim                                105d
pv-volume7                                 10Gi       RWX            Retain           Bound       sonar/sonar-ext-pv-claim                                 105d
pv-volume8                                 10Gi       RWX            Retain           Bound       sonar/sonar-data-pv-claim                                105d
pv-volume9                                 10Gi       RWX            Retain           Bound       sonar/pg-pv-claim                                        105d
pv0                                        10Gi       RWO            Retain           Available                                default                     126d
pv1                                        10Gi       RWO            Retain           Available                                default                     126d
pv2                                        10Gi       RWO            Retain           Bound       default/vault-pv-claim       default                     126d
pvc-b2cd2c8a-e7bb-4ea4-ac05-521f29966ce8   1000Mi     RWO            Delete           Bound       default/test-data            my-storage                  143d
sonarqube-volume                           10Gi       RWO            Retain           Bound       sonarqube/sonar-postgresql   manual                      105d
test-pv-volume                             1Gi        RWO            Retain           Available                                slow                        8d
vol-mobsf                                  10Gi       RWO            Retain           Bound       default/vol-mobsf            manual                      65d
vol-mobsf2                                 10Gi       RWO            Retain           Bound       ingress-nginx/vol-mobsf2     manual                      51d
vol-nginx-log                              10Gi       RWO            Retain           Bound       default/vol-nginx-log        manual                      65d
vol-postgres                               10Gi       RWO            Retain           Available                                manual                      65d
![2](https://user-images.githubusercontent.com/38696837/78886095-55070e00-7a66-11ea-9148-b9c6fcbdd81e.png)
``

PVC:

`` kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        STORAGECLASS       REASON   AGE
consul-2                                   10Gi       RWO            Retain           Bound       default/consul-3             manual                      71d
consul-3                                   10Gi       RWO            Retain           Bound       default/vol-postgres         manual                      71d
consul-data                                1Gi        RWO            Retain           Available                                local-storage               126d
consul-l                                   10Gi       RWO            Retain           Released    default/consul-2             manual                      71d
data-consul-0                              10Gi       RWO            Retain           Bound       default/data-consul-0        manual                      119d
data-consul-1                              10Gi       RWO            Retain           Bound       default/data-consul-1        manual                      119d
data-consul-2                              10Gi       RWO            Retain           Bound       default/data-consul-2        manual                      119d
data-consul-pv0                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      119d
data-consul-pv1                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      7d21h
minio-pv-volume                            15Gi       RWO            Retain           Bound       default/minio-pv-claim       manual                      154d
my-local-pv                                500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv2                               500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv3                               500Gi      RWO            Retain           Available                                my-local-storage            2d
postgres-volume                            10Gi       RWO            Retain           Bound       default/consul-1             manual                      105d
pv-volume10                                10Gi       RWX            Retain           Bound       sonar/sonar-temp-pv-claim                                105d
pv-volume7                                 10Gi       RWX            Retain           Bound       sonar/sonar-ext-pv-claim                                 105d
pv-volume8                                 10Gi       RWX            Retain           Bound       sonar/sonar-data-pv-claim                                105d
pv-volume9                                 10Gi       RWX            Retain           Bound       sonar/pg-pv-claim                                        105d
pv0                                        10Gi       RWO            Retain           Available                                default                     126d
pv1                                        10Gi       RWO            Retain           Available                                default                     126d
pv2                                        10Gi       RWO            Retain           Bound       default/vault-pv-claim       default                     126d
pvc-b2cd2c8a-e7bb-4ea4-ac05-521f29966ce8   1000Mi     RWO            Delete           Bound       default/test-data            my-storage                  143d
sonarqube-volume                           10Gi       RWO            Retain           Bound       sonarqube/sonar-postgresql   manual                      105d
test-pv-volume                             1Gi        RWO            Retain           Available                                slow                        8d
vol-mobsf                                  10Gi       RWO            Retain           Bound       default/vol-mobsf            manual                      65d
vol-mobsf2                                 10Gi       RWO            Retain           Bound       ingress-nginx/vol-mobsf2     manual                      51d
vol-nginx-log                              10Gi       RWO            Retain           Bound       default/vol-nginx-log        manual                      65d
vol-postgres                               10Gi       RWO            Retain           Available                                manual                      65d
``

Plz tell me how to make correct PV for solution 🙏

![2](https://user-images.githubusercontent.com/38696837/78885892-035e8380-7a66-11ea-8805-dae48431c216.png)
![1](https://user-images.githubusercontent.com/38696837/78885896-03f71a00-7a66-11ea-906e-d8797d9a1e5f.png)

**Comment by itsecforu** [comment]
![2](https://user-images.githubusercontent.com/38696837/78886122-63552a00-7a66-11ea-8675-6931f81f6d39.png)

**Comment by reasonerjt** [comment]
Could you open issue on goharbor/harbor-helm?

**Comment by itsecforu** [comment]
> 
> 
> Could you open issue on goharbor/harbor-helm?

Ok :-(
