### ISSUE TITLE
When the replication strategy is triggered, the number of harbor_core threads will always increase

### ISSUE THREAD

**Issue by liy516** [goharbor/harbor#11557]
What can we help you?

-The replication strategy is triggered, the number of harbor_core threads will always increase, the replication strategy ends but the thread does not end。

- harbor version 1.9.4

- docker version  18.03.0-ce

`[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
45
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
45
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
45
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
56
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
57
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
63
[root@06l15b003 harbor-1.9.4]# ps -eLf | grep harbor_core | wc -l
63`

**Comment by ywk253100** [comment]
@liy516 How many CPU cores does the host that Harbor is running on has?

**Comment by liy516** [comment]
> @liy516 How many CPU cores does the host that Harbor is running on has?

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               1422.953
BogoMIPS:              4405.15
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
