### ISSUE TITLE
Event based replication is never triggered when source resource filter is based on Label

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11565]
Steps to reproduce:
1. Create a replication rule on HarborA, triggered by event. replicate library/** to HarborB/library/**, filtered with Label "yellow"
<img width="592" alt="Screen Shot 2020-04-10 at 12 23 37 PM" src="https://user-images.githubusercontent.com/2696760/78962101-2a7c8a00-7b26-11ea-9f11-a945d165cabd.png">
2. Push images to HarborA/library/busybox:1.0 
3. Label the HarborA/library/busybox:1.0 with "yellow".
4. Go to HarborB/library, the is no busybox:1.0 image replicated.

Expected Result:
Because event based replication, it might based on docker push a image, when pushing image, it is impossible to have a Label at this moment. so the replication will never trigger.

**Comment by ywk253100** [comment]
This works as expected for now. We don't support `Add Label` event yet, only support `Push` and `Delete`
