### ISSUE TITLE
UNIQUE job is not supported in jobservice

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11570]
GC job is using `UNIQUE` to ensure there is only one GC job runing simultaneously. 

But in Harbor v2.0.0, jobservice deprecates unique job, which may lead to multiple GC instances are running in a specific time slot if user sets up a short interval cron schedule.

It's dangerous as GC will delete the backend storage assets.

**Comment by steven-zou** [comment]
Work has been done a while, close this issue now.
