### ISSUE TITLE
All internal TLS communication should require TLS v1.2

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11583]
When we enable TLS for internal communication, please make sure they require TLS v1.2+ , including the 3rd party softwares.

It is known that in chartmuseum it's not configurable so for v2.0 this can be an exception.

**Comment by ninjadq** [comment]
harbor components can set TLS minversion to v1.2
The third-party components are varied. Clair and notary are already set min version to 1.2. docker registry not set by default. The chartmuseum can not set it yet. Trivy is unknown but it seems no place to set min Version.

**Comment by ninjadq** [comment]
PR of harbor:
