### ISSUE TITLE
Why my clair doesn't have alpine CVE?

### ISSUE THREAD

**Issue by cycwll** [goharbor/harbor#11581]
Harbor version: 1.10
--with-clair
clair doesn't have alpine CVE.

How can I add other CVE libraries besides the existing?

![image](https://user-images.githubusercontent.com/6410130/79034656-55301680-7bea-11ea-89ec-05d5a537faa7.png)

![image](https://user-images.githubusercontent.com/6410130/79034652-49445480-7bea-11ea-8209-73e0ab4ecb9e.png)

**Comment by wy65701436** [comment]
can you try to compare with the native clair? and any error in the clair.log?
