### ISSUE TITLE
portal container build failed by harbor-1.10.2 source code

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#11602]
when i build harbor by harbor-1.10.2 source code, portal container build failed, when it run 'npm run build_lib' reported killed

**Comment by wy65701436** [comment]
please tell how did you build the portal and what did you modifed.

**Comment by tongying123456** [comment]
> please tell how did you build the portal and what did you modify.

build the dockerfile of portal, when run step: node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod , it report errors :ERROR in app/shared/shared.module.ts(91,5): Error during template compile of 'SharedModule'
  Could not resolve @harbor/ui relative to [object Object]..

**Comment by AllForNothing** [comment]
@tongying123456 For harbor version 1.10.x,   here are the right steps to compile  UI  code:
![image](https://user-images.githubusercontent.com/30999793/79196806-4e600880-7e63-11ea-996e-a05509f1050d.png)
![image](https://user-images.githubusercontent.com/30999793/79197230-f70e6800-7e63-11ea-814e-614ba5ee2ef7.png)

**Comment by tongying123456** [comment]
> @tongying123456 For harbor version 1.10.x, here are the right steps to compile UI code:
> ![image](https://user-images.githubusercontent.com/30999793/79196806-4e600880-7e63-11ea-996e-a05509f1050d.png)
> ![image](https://user-images.githubusercontent.com/30999793/79197230-f70e6800-7e63-11ea-814e-614ba5ee2ef7.png)

I know, but when it run to 'node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod ', it report error, such as no find modul @harbor/ui

**Comment by AllForNothing** [comment]
@tongying123456  You need to run "build_lib" and "link_lib" first , these two steps will generate "@harbor/ui" module

**Comment by tongying123456** [comment]
that’s what I did


发自我的iPhone

------------------ Original ------------------
