### ISSUE TITLE
How to prevent user from executing GC in container of registry/registryctl 

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11606]
As from Harbor v2.0, `tag` is maintained in Harbor instead of back end registry, which leads to the valid images in Harbor with tags but without tags in the registry.

Therefore, Harbor disables its GC job to delete the untagged manifest when to call registry GC CLI.

But, how can we prevent a user from executing GC CLI with enabling delete untagged manifest option in the container of registry and regsitryctl. 

If the user executes GC with the option, it should be a catastrophic event as GC will remove most of the valid images from the backend storage and no way to restore.

**Comment by reasonerjt** [comment]
We can rename the binary file to mitigate the risk, 
and we MUST clearly add release note and document
