### ISSUE TITLE
GC UI improvement

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11613]
please get rid of the 'garbage collection' and left align everything with the title above, ie. move the schedule and 'save' to the left margin.  In current design, once user confirms the scheduled GC, the 'garbage collection' turns to 'current schedule', which is also not that useful. 

![Screen Shot 2020-04-14 at 6 31 50 AM](https://user-images.githubusercontent.com/51319901/79215958-61021f80-7e1a-11ea-884a-bacb2cd6da1e.png)

**Comment by AllForNothing** [comment]
@xaleeks Please choose one:
1.
![image](https://user-images.githubusercontent.com/30999793/79294443-c6ccd500-7f08-11ea-9542-a5007d164335.png)
2.
![image](https://user-images.githubusercontent.com/30999793/79294465-d77d4b00-7f08-11ea-95c9-9499eb8c9fb7.png)
3.
![image](https://user-images.githubusercontent.com/30999793/79294489-e19f4980-7f08-11ea-919f-7d334d3f1616.png)
