### ISSUE TITLE
Scanner `Trivy` does not support image which manifest is schema 1

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11611]
There is a manifest which media type is `application/vnd.docker.distribution.manifest.v1+prettyjws`, these image is not support scan in v2.0.

Eg:  `redis@sha256:6c9f9cb9a250b12c15a92d8042a44f4557ca5bc590f36e63e529d52fb15b4ddc`

![image](https://user-images.githubusercontent.com/5634205/78977879-75f55f00-7b4b-11ea-8370-0bf6c52bb4bd.png)

How to reproduce the problem:
Add docker hub as replication regsitry, and replicate `library/redis:2.6` to harbor, the result is that `redis:2.6` is not supported to scan by trivy.

**Comment by danielpacak** [comment]
After discussing internally with our team at Aqua I tend to close this issue as wont' fix. The reason for that is that we do not plan to support such old manifests with Trivy and Aqua CSP commercial scanners. 

What's more, most popular third-party libraries for pulling images from registries do not support such schema as well. See for example https://github.com/google/go-containerregistry - we use this one in Trivy

/cc @steven-zou @xaleeks @michmike
