### ISSUE TITLE
Report 404 when docker push

### ISSUE THREAD

**Issue by chunqizhi** [goharbor/harbor#11615]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
$ docker push 123.126.106.88/baseimg:latest 
The push refers to repository [123.126.106.88/baseimg]
b496eb81b7a4: Preparing 
27a216ffe825: Preparing 
9e9d3c3a7458: Preparing 
7604c8714555: Preparing 
adcb570ae9ac: Preparing 
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"
原来是可以的，但是同事改了 iptables 之后，就不行了，不知道是怎么回事。

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.1]
- docker engine version: [19.03.8]
- docker-compose version: [1.25.4]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
`docker push 123.126.106.88/baseimg:latest`

`123.126.106.88` is your Harbor? you have to specify the project name in the docker push.

**Comment by chunqizhi** [comment]
> `docker push 123.126.106.88/baseimg:latest`
> 
> `123.126.106.88` is your Harbor? you have to specify the project name in the docker push.

yes, using the same operation, but other machines are ok.

**Comment by wy65701436** [comment]
please check your host settings.

**Comment by chunqizhi** [comment]
yes, this is indeed a problem with my host. thanks!
