### ISSUE TITLE
Rest api token

### ISSUE THREAD

**Issue by jehutyy** [goharbor/harbor#11617]
Hi,
we would like to use Harbor rest api and we are trying to figure out how to get a user token to make request. Looking in the faq and the documentation didn't help that much.

Is there something  that we're missing ?

**Comment by wy65701436** [comment]
do you mean the registry bearer token? what's your harbor version?

**Comment by jehutyy** [comment]
I don't know about bearer token. I would like to be able to create project for example. What do I need to do to get to use the rest api ?

**Comment by wy65701436** [comment]
Please just refer to the swagger document. BTW, you just need the basic auth when to call harbor rest API.

**Comment by jehutyy** [comment]
Which swagger document. There is no such "swagger document" anywhere...

Anyway, I have more detail to give. I just set up a Harbor

**Comment by yamlCase** [comment]
I'm getting the same results trying to create a registry endpoint using the API on version 1.10.2. 
 This is a fresh install of harbor-offline-installer-v1.10.2.tgz. with no configuration, using the admin account.  

I tried with the authenticated API explorer first and was able to create a registry.

Here's my curl (the `Basic YWRtaW46UEBzc3cwcmQ=` base64s out to my username/password):

```
curl --request POST \
  --url https://sparebox.spike/api/registries \
  --header 'authorization: Basic YWRtaW46UEBzc3cwcmQ=' \
  --header 'content-type: application/json' \
  --cookie sid=328c04a0432549cf7b371ae2616dbf4a \
  --data '{
	"name": "docker-hub",
	"url": "https://hub.docker.com",
	"insecure": true,
	"type": "docker-hub",
	"description": "docker hub"
}'
```

And here's the error:

```
422 Unprocessed Entity

Response:
...
<br>The page you have requested is forbidden.<br>Perhaps you are here because:<br><br><ul><br>'_xsrf' argument missing from POST</ul>
...
```

Only thing missing from my curl is the `X-Xsrftoken` header, and I have no idea how to generate that. Harbor documentation has nothing about this that I can find.

**Comment by yamlCase** [comment]
@jehutyy 
I found the answer here: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#api

For the first step in the #2 answer, it seems a little ambiguous.  Just curl any GET endpoint and you'll get the needed header in your response.

**Comment by jehutyy** [comment]
Thank you very much for your answer. I managed to get it working with this method that seems a little bit sketchy in my opinion but well, if it works it works ; I would like nonetheless that a maintainer acknowledge the lack of informations about this topic. 

A little change would be to point into the wiki a paragraph:
## How to get Xsrf token 
* curl any endpoint and get xsrf from header

**Comment by yamlCase** [comment]
@jehutyy #11813 revealed something even easier:  Apparently, if I don't send a cookie with my POST, the response won't look for an "X-Xsrftoken" header and basic auth works as we expect it to.  

In your case, maybe sending the X-Xsrftoken triggers the check anyways and fails.  

I tried your command without the X-Xsrftoken and it succeeds:

```
$ curl --request POST \
>   --url https://example.com/api/projects \
>   --header 'authorization: Basic YWRtaW46SGFyYm9yMTIzNDU=' \
>   --header 'content-type: application/json' \
>   --data '{
>   "count_limit": 10,
>   "project_name": "foo2",
>   "cve_whitelist": {
>     "items": [
>       {
>         "cve_id": "string"
>       }
>     ],
>     "project_id": 0,
>     "id": 0,
>     "expires_at": 0
>   },
>   "storage_limit": 10,
>   "metadata": {
>     "enable_content_trust": "true",
>     "auto_scan": "false",
>     "severity": "none",
>     "reuse_sys_cve_whitelist": "false",
>     "public": "true",
>     "prevent_vul": "false"
>   }
> }' -k --verbose
```

Response:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to example.com (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=example.com
*  start date: Apr 29 18:59:39 2020 GMT
*  expire date: Sep 14 18:59:39 2047 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> POST /api/projects HTTP/1.1
> Host: example.com
> User-Agent: curl/7.58.0
> Accept: */*
> authorization: Basic YWRtaW46SGFyYm9yMTIzNDU=
> content-type: application/json
> Content-Length: 413
>
* upload completely sent off: 413 out of 413 bytes
< HTTP/1.1 201 Created
< Server: nginx
< Date: Thu, 30 Apr 2020 12:14:47 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: /api/projects/3
< Set-Cookie: sid=1d1a2edc2d4c4398fde780; Path=/; Secure; HttpOnly
< Set-Cookie: _xsrf=M2JKbFBxZ1dMMVRWQ0ZEJtQWFpd2M=|158824860788250|8e4da3819ec703e9ca23805b4e2e05525be00; Expires=Thu, 30 Apr 2020 13:14:47 UTC; Max-Age=3600; Path=/; Secure
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: DENY
< Content-Security-Policy: frame-ancestors 'none'
<
* Connection #0 to host example.com left intact
```
