### ISSUE TITLE
Error pushing to registry: Server error: 500 trying to push

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#11629]
DOCKER PUSH IS FAILING WITH OLDER DOCKER CLIENT 1.7.1
THIS CLIENT IS RUNNING ON A JENKINS SLAVE.
ANY QUICK WORKAROUND (TILL WE UPGRADE THE JENKINS SLAVE)??

Harbor is running perfectly:
harbor version: 1.10.1
docker engine version: 19.03.7
docker-compose version: 1.25.4

STEPS TO REPRODUCE

1. Ubuntu 16.04  and Docker 19.03.8 docker push against harbor worked perfectly fine
2. Ubuntu 14.04 and Docker 1.7.1 and docker push against harbor FAILED. 

$ git clone https://github.com/bjethwan/hello-app.git

$ sudo docker build -t bjethwan/hello-app .

$ sudo docker login harbor.XXX.XXXXX
Username: admin
Password: 
Email: bj151v@XXXX.XXX.XXX
WARNING: login credentials saved in /home/ubuntu/.dockercfg.
Login Succeeded

$ sudo docker tag bjethwan/hello-app harbor.XXX.XXXXX/bjethwan/hello-app:1

$ sudo docker push harbor.XXX.XXXXX/bjethwan/hello-app:1
The push refers to a repository [harbor.XXX.XXXXXbjethwan/hello-app] (len: 1)
17e035be3ea5: Image already exists 
639ed3c5aca5: Image successfully pushed 
59cc35b0a56c: Image push failed 
FATA[0004] Error pushing to registry: Server error: 500 trying to push bjethwan/hello-app blob - sha256:22ce633f6ab1462259ecac9f41897051838eaa331faa0ba3e61b4fbd94451e11

**Comment by wy65701436** [comment]
Docker 1.7.1 is out of support  in v1.10.1, please try to upgrade it.

**Comment by bjethwan** [comment]
@wy65701436 
Thanks. I was hoping that it would be the case, but I was unsure about it as this one id on the client-side of the harbor. 

For some internal reasons, the upgrade of docker client on those would take some time.
Anyways, I found below logs linked to this issue. It seems that the older docker client is messing up the packet/blob size on the final step, while Harbor is expecting it for storage quota.


ubuntu@ip-10-223-5-33:~/harbor$ grep -i 355626d75b0af01ba3da3c09a8d53cb7907c7eaab1fabcf8a6d43da69c60a157 /var/log/harbor/
grep: /var/log/harbor/: Is a directory
ubuntu@ip-10-223-5-33:~/harbor$ grep -i 355626d75b0af01ba3da3c09a8d53cb7907c7eaab1fabcf8a6d43da69c60a157 /var/log/harbor/*
/var/log/harbor/proxy.log:Apr 15 01:44:11 172.24.0.1 proxy[1159]: 10.223.3.194 - "PUT /v2/bjethwan/hello-app/blobs/uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936?_state=bzVgRGWKCzW9UFtL7Nqj9yqevQMe2nv0DxhLm2xHb817Ik5hbWUiOiJiamV0aHdhbi9oZWxsby1hcHAiLCJVVUlEIjoiMDg2OTk1NWYtMGVkZS00YzFiLWFkNmEtZWM4MTI0YmFlOTM2IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA0LTE1VDAxOjQ0OjExLjE2NjY4OTM0NFoifQ%3D%3D&digest=sha256%3A355626d75b0af01ba3da3c09a8d53cb7907c7eaab1fabcf8a6d43da69c60a157 HTTP/1.1" 500 403 "-" "docker/1.7.1 go/go1.4.2 kernel/2.6.32-754.3.5.el6.x86_64 os/linux arch/amd64" 0.010 0.012 .
ubuntu@ip-10-223-5-33:~/harbor$ grep -i 0869955f-0ede-4c1b-ad6a-ec8124bae936 /var/log/harbor/*
/var/log/harbor/core.log:Apr 15 01:44:11 172.24.0.1 core[1159]: 2020-04-15T01:44:11Z [DEBUG] [/core/middlewares/url/handler.go:40]: in url handler, path: /v2/bjethwan/hello-app/blobs/uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936
/var/log/harbor/core.log:Apr 15 01:44:11 172.24.0.1 core[1159]: 2020-04-15T01:44:11Z [WARNING] [/core/middlewares/sizequota/handler.go:48]: Error occurred when to handle request in size quota handler: failed to get content length of blob upload 0869955f-0ede-4c1b-ad6a-ec8124bae936, error: redigo: nil returned
/var/log/harbor/core.log:Apr 15 01:44:11 172.24.0.1 core[1159]: 2020/04/15 01:44:11.509 #033[1;44m[D]#033[0m [server.go:2774]  |     10.27.17.4|#033[97;41m 500 #033[0m|   8.167554ms|   match|#033[97;43m PUT     #033[0m /v2/bjethwan/hello-app/blobs/uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936   r:/v2/*
/var/log/harbor/proxy.log:Apr 15 01:44:11 172.24.0.1 proxy[1159]: 10.223.3.194 - "PUT /v2/bjethwan/hello-app/blobs/uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936?_state=bzVgRGWKCzW9UFtL7Nqj9yqevQMe2nv0DxhLm2xHb817Ik5hbWUiOiJiamV0aHdhbi9oZWxsby1hcHAiLCJVVUlEIjoiMDg2OTk1NWYtMGVkZS00YzFiLWFkNmEtZWM4MTI0YmFlOTM2IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA0LTE1VDAxOjQ0OjExLjE2NjY4OTM0NFoifQ%3D%3D&digest=sha256%3A355626d75b0af01ba3da3c09a8d53cb7907c7eaab1fabcf8a6d43da69c60a157 HTTP/1.1" 500 403 "-" "docker/1.7.1 go/go1.4.2 kernel/2.6.32-754.3.5.el6.x86_64 os/linux arch/amd64" 0.010 0.012 .
/var/log/harbor/registry.log:Apr 15 01:44:11 172.24.0.1 registry[1159]: time="2020-04-15T01:44:11.237827341Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/bjethwan/hello-app/_uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936/startedat")" auth.user.name=admin go.version=go1.12.12 http.request.host=harbor.aeg.cloud http.request.id=84c48bc0-52d1-4883-899a-023a0e6ee163 http.request.method=POST http.request.remoteaddr=10.27.17.4 http.request.uri="/v2/bjethwan/hello-app/blobs/uploads/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/2.6.32-754.3.5.el6.x86_64 os/linux arch/amd64" trace.duration=71.112013ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=ca183906-1024-4c11-8557-e1d3512df1d9 trace.line=110 vars.name="bjethwan/hello-app" 
/var/log/harbor/registry.log:Apr 15 01:44:11 172.24.0.1 registry[1159]: time="2020-04-15T01:44:11.257517171Z" level=debug msg="s3aws.Writer("/docker/registry/v2/repositories/bjethwan/hello-app/_uploads/0869955f-0ede-4c1b-ad6a-ec8124bae93/data", false)" auth.user.name=admin go.version=go1.12.12 http.request.host=harbor.aeg.cloud http.request.id=84c48bc0-52d1-4883-899a-023a0e6ee163 http.request.method=POST http.request.remoteaddr=10.27.17.4 http.request.uri="/v2/bjethwan/hello-app/blobs/uploads/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/2.6.32-754.3.5.el6.x86_64 os/linux arch/amd64" trace.duration=19.638749ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=4d7b4e04-7df9-4306-a630-982ea51d415b trace.line=142 vars.name="bjethwan/hello-app" 
/var/log/harbor/registry.log:Apr 15 01:44:11 172.24.0.1 registry[1159]: time="2020-04-15T01:44:11.340729963Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/bjethwan/hello-app/_uploads/0869955f-0ede-4c1b-ad6a-ec8124bae936/hashstates/sha256/0")" auth.user.name=admin go.version=go1.12.12 http.request.host=harbor.aeg.cloud http.request.id=84c48bc0-52d1-4883-899a-023a0e6ee163 http.request.method=POST http.request.remoteaddr=10.27.17.4 http.request.uri="/v2/bjethwan/hello-app/blobs/uploads/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/2.6.32-754.3.5.el6.x86_64 os/linux arch/amd64" trace.duration=83.162922ms trace.file="/go/src/github.com/docker/distribution/registry/storage

**Comment by kurbar** [comment]
FWIW this same error can also happen if there is an issue with `redis-photon` and the redis container has gone into an unhealthy state. Restarting the redis container is a quick fix for this issue.
