### ISSUE TITLE
push image to aliyun oss, happen "received unexpected HTTP status: 504 Gateway Time-out" error

### ISSUE THREAD

**Issue by xiaochonghao** [goharbor/harbor#11625]
![test1](https://user-images.githubusercontent.com/18009560/79314183-03fa8c80-7f34-11ea-812b-878358b39a5b.png)
I install the version v1.10.1，and reset nginx conf file (position: harbor/common/config/nginx/nginx.conf) does not work to me. After change this, and push image will stop still.
![quest2](https://user-images.githubusercontent.com/18009560/79313137-779b9a00-7f32-11ea-9204-dde5dc98a6a5.png)
![test2](https://user-images.githubusercontent.com/18009560/79314238-15439900-7f34-11ea-8da4-cceea21f1bcb.png)
And below is my filesystem config at "harbor.yml" file, parts of image is success saved in bucket.
![quest4](https://user-images.githubusercontent.com/18009560/79313283-aca7ec80-7f32-11ea-81e1-74e234b20c05.png)

**Comment by wy65701436** [comment]
can you provide the core and registry.log?

**Comment by xiaochonghao** [comment]
I give up the oss storage, there are so many unknown problems.
