### ISSUE TITLE
(external database) - failed to initialize database: register db Ping `default`, pq: database "registry" does not exist

### ISSUE THREAD

**Issue by cparadal** [goharbor/harbor#11626]
Hi,

I'm trying to install Harbor (Helm chart) with a setup of external components:  RDS (Postgres), Elasticache (Redis) and S3 storage.

Upon chart install, multiple pods, including the core one, fail with the below error:

```
port-5432 databse-registry sslmode-"disable"
[ORM]2020/04/15 08:45:56 register db Ping `default`, pq: database "registry" does not exist
2020-04-15T08:45:56Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: database "registry" does not exist
```

It doesn't seem to be an issue with the RDS instance itself (or connectivity to it) as the pods and come up with no issues if I manually create the registry, clair, notarysigner and notaryserver myself.

As I understand, those databases should be created on Harbor initialization.
Is there any way of making it work without having to manually create the databases, which is obviously not scalable?

Thanks.

Harbor Helm chart version: 1.3.1
Kubernetes version: 1.15.4

**Comment by wy65701436** [comment]
can you please file it in helm repo?

**Comment by cparadal** [comment]
Oops sorry, closing this issue. Thanks!
