### ISSUE TITLE
harbor 2.0 user can get a bearer token even credencial is wrong

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11632]
curl -u admin:asdfdsf "https://10.184.85.205/service/token?scope=repository%3Alibrary%2Fmariadb%3Apull&service=harbor-registry"

![image](https://user-images.githubusercontent.com/188115/79342328-919fa180-7f5f-11ea-8f81-4fc486a09f32.png)

docker hub will fail
![image](https://user-images.githubusercontent.com/188115/79342367-9f552700-7f5f-11ea-8aa2-7e63de082c31.png)

**Comment by reasonerjt** [comment]
This is by design, as the token can be used to access public resource.

**Comment by bitsf** [comment]
but when I use a scope not exists, it also return a token

**Comment by bitsf** [comment]
harbor 1.10.2 has the same behavior too, so this is not introduced by 2.0

**Comment by reasonerjt** [comment]
It's also expected if you decode the token, you'll see the token's scope is also empty.

**Comment by reasonerjt** [comment]
Closing as it's working as designed.
