### ISSUE TITLE
Replication job might be hang when doing copy to some big blobs (after enable tls)

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11642]
![image (7)](https://user-images.githubusercontent.com/5753287/79437989-8606b600-8005-11ea-9645-1234c03f52e1.png)

The [response body](https://github.com/goharbor/harbor/blob/9bc96dd97a2f2be7a41001f98fc2c5a724ea0ee9/src/pkg/registry/client.go#L364) is returned to the [push blob function](https://github.com/goharbor/harbor/blob/9bc96dd97a2f2be7a41001f98fc2c5a724ea0ee9/src/pkg/registry/client.go#L367) for reading from the [pull blob function](https://github.com/goharbor/harbor/blob/9bc96dd97a2f2be7a41001f98fc2c5a724ea0ee9/src/pkg/registry/client.go#L349) that is for writing.

The issue might be caused by the underlying golang library, there are some issues may be related to this issue:

- https://github.com/golang/go/issues/23559
- https://github.com/golang/go/issues/32388
- https://github.com/golang/go/issues/33425
- https://github.com/golang/go/issues/33006

**Comment by bitsf** [comment]
Manually create the http client like this can fix the replication hang. It seems the main different with http.DefaultTransport is param ForceAttemptHTTP2=false

![image](https://user-images.githubusercontent.com/188115/79526150-3a045180-8097-11ea-9065-7469161b3b44.png)

**Comment by steven-zou** [comment]
Fixed in issue https://github.com/goharbor/harbor/pull/11645.

Close this issue now.
