### ISSUE TITLE
Not able to push the image to the Registry - Docker push (retrying)

### ISSUE THREAD

**Issue by Pradyumnakashyap** [goharbor/harbor#11646]
Installed Harbor with Helm on Kubernetes (on EC2-AWS - Development env)
All pods are fine and able to login with UI and create projects, When i try to push images after a successful docker login, keeps on retrying and fails (Docker logs says - time="2020-04-15T16:19:05.287199445Z" level=error msg="Upload failed, retrying: received unexpected HTTP status: **500 Internal Server Error**"
cross verified other similar issues, No problem with storage as I am using file system (local) to store the images.
Please Advice.

**Comment by wy65701436** [comment]
can you please file issue on helm repository? BTW, provide log is helpful for debugging.

**Comment by Pradyumnakashyap** [comment]
opened the issue on Harbor-helm repository hence closing here
