### ISSUE TITLE
Epic: Proxy Cache user stories

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11658]
> This is an `epic` tracking all user stories for Harbor functioning as proxy cache for upstream registries

**Comment by mvisonneau** [comment]
I am so excited to see this feature being 🚀 , thanks @xaleeks! 🙇

**Comment by xaleeks** [comment]
@a-mccarthy fyi

**Comment by Morriz** [comment]
@reasonerjt why was this closed? I can't find any evidence that it is now possible to do automatic image scanning of proxied images? Or is that tracked somewhere else now?

**Comment by candoom** [comment]
Is this feature still planned or completely discarded? I would be very interested in it as well.
