### ISSUE TITLE
Can I set the chunk size when pulling the container image？

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#11678]
The backend storage of harbor is S3. 

Can I set the chunk size when pulling the container image？

Chunksize in the configuration file seems to work only when pushing images.

**Comment by wy65701436** [comment]
can you try [this](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#fetch-blob-part)? BTW, it should be supported by the client either.

**Comment by Iverson-lena** [comment]
When we use the pull command to pull the image, we find that there is no slicing pull on the back-end storage S3.

How do I set it to support chunk and pull？
