### ISSUE TITLE
Can't push image to Harbor with Minio S3 in distributed mode as storage backend

### ISSUE THREAD

**Issue by annkam** [goharbor/harbor#11677]
Originally, I created an issue in Minio project about two months ago: https://github.com/minio/minio/issues/9070
Have your ever tested Harbor with Minio in distributed mode? I wanted to deploy HA Harbor using your helm chart and Minio as a HA storage backend, but it does not work. It works when there is only one instance of Minio. It does not matter whether Harbor is deployed in k8s or with docker-compose.

The problem is still present with Harbor 1.10.2.

When I try to push an image, I see the following:

`# docker push registry31-test.s7.aero/library/minio:RELEASE.2020-04-15T19-42-18Z
The push refers to repository [registry31-test.s7.aero/library/minio]
af6cf3c35329: Pushing [==================================================>]  51.01MB
12969495508c: Pushing [==================================================>]  1.083MB
96db304789ec: Pushing [==================================================>]  5.632kB
531743b7098c: Pushing [==================================================>]  5.819MB
blob upload unknown
`

And in registry.log:

```
Apr 21 05:01:38 10.11.21.1 registry[939]: time="2020-04-21T05:01:38.131212838Z" level=error msg="upload resumed at wrong offest: 2788338 != 2786962" auth.user.name=a.s.kamenskaya go.version=go1.12.12 http.request.host=registry31-test.s7.aero http.request.id=7b2abb43-e8cb-4d81-8b34-d3899d2b0526 http.request.method=PUT http.request.remoteaddr=172.27.115.198 http.request.uri="/v2/library/minio/blobs/uploads/b9a87021-729e-475c-9a66-2e5ec7244a89?_state=VQc9GV4wq71B2xNjYxX0IUFxOUIsHvd7dxqu3jB-tLJ7Ik5hbWUiOiJsaWJyYXJ5L21pbmlvIiwiVVVJRCI6ImI5YTg3MDIxLTcyOWUtNDc1Yy05YTY2LTJlNWVjNzI0NGE4OSIsIk9mZnNldCI6Mjc4Njk2MiwiU3RhcnRlZEF0IjoiMjAyMC0wNC0yMVQwNTowMToxNVoifQ%3D%3D&digest=sha256%3A4167d3e149762ea326c26fc2fd4e36fdeb7d4e639408ad30f37b8f25ac285a98" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/4.9.0-8-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" vars.name="library/minio" vars.uuid=b9a87021-729e-475c-9a66-2e5ec7244a89
Apr 21 05:01:38 10.11.21.1 registry[939]: time="2020-04-21T05:01:38.356322279Z" level=error msg="response completed with error" auth.user.name=a.s.kamenskaya err.code="blob upload invalid" err.message="blob upload invalid" go.version=go1.12.12 http.request.host=registry31-test.s7.aero http.request.id=7b2abb43-e8cb-4d81-8b34-d3899d2b0526 http.request.method=PUT http.request.remoteaddr=172.27.115.198 http.request.uri="/v2/library/minio/blobs/uploads/b9a87021-729e-475c-9a66-2e5ec7244a89?_state=VQc9GV4wq71B2xNjYxX0IUFxOUIsHvd7dxqu3jB-tLJ7Ik5hbWUiOiJsaWJyYXJ5L21pbmlvIiwiVVVJRCI6ImI5YTg3MDIxLTcyOWUtNDc1Yy05YTY2LTJlNWVjNzI0NGE4OSIsIk9mZnNldCI6Mjc4Njk2MiwiU3RhcnRlZEF0IjoiMjAyMC0wNC0yMVQwNTowMToxNVoifQ%3D%3D&digest=sha256%3A4167d3e149762ea326c26fc2fd4e36fdeb7d4e639408ad30f37b8f25ac285a98" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/4.9.0-8-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=473.827045ms http.response.status=404 http.response.written=76 vars.name="library/minio" vars.uuid=b9a87021-729e-475c-9a66-2e5ec7244a89
```

Here is my config:

```
storage_service:
  s3:
    accesskey: MY_ACCESS_KEY
    secretkey: MY_SECRET_KEY
    region: us-east-1
    regionendpoint: MY_ENDPOINT
    encrypt: false
    bucket: epaas-harbor
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  redirect:
    disabled: true
```

I've tried connecting to Minio through load balancer and directly, enabling and disabling redirect - it does not work either way.

**Comment by ynnt** [comment]
+1 to this

This issue blocks me from getting Minio deployed at scale...

**Comment by renmaosheng** [comment]
the https://github.com/goharbor/harbor-cluster-operator project is looking into support the scaling of Minio, Steven Zou and Ziming, did we hit the same issue? thanks.

**Comment by harshavardhana** [comment]
> # docker push registry31-test.s7.aero/library/minio:RELEASE.2020-04-15T19-42-18Z The push refers to repository [registry31-test.s7.aero/library/minio] af6cf3c35329: Pushing [==================================================>] 51.01MB 12969495508c: Pushing [==================================================>] 1.083MB 96db304789ec: Pushing [==================================================>] 5.632kB 531743b7098c: Pushing [==================================================>] 5.819MB blob upload unknown

@annkam this is already fixed in latest releases of MinIO
