### ISSUE TITLE
push image with large layer get 502 badway error

### ISSUE THREAD

**Issue by xiaochenluo** [goharbor/harbor#11687]
My image has a big layer about 2.7GB. And got `received  unexpected HTTP status: 502 Bad Gateway` when I pushed it to my harbor. 
Then I found `registry[637]: fatal error: runtime: out of memory` in registry.log. Is the whole layer data should read into memory? So the upper limit of layer size is memory.  Are there any Settings to change this?

**Comment by bitsf** [comment]
This need to check docker distribution code, and I think they may load the data in memory in order to compute the digest.
You can try `docker run -it -p 5000:5000 registry`, and see if that has the same problem.

**Comment by xiaochenluo** [comment]
I tried this method and still got the same 502  error on the docker client. And the performance of the service has changed, but not fundamentally. 
I checked the service log, not found `runtime: out of memory` in the registry.log. But memory changes throughout the upload process are the same as before. 
A temporary solution is changing the client settings `"max-concurrent-uploads": 1`. Memory exhaustion is not because uploading a large layer but upload large layer data at the same time.

**Comment by bitsf** [comment]
good catch, I think this can be doc as an known issue somewhere first

**Comment by rochaporto** [comment]
Can this be reopened? The client side config change only works if it's possible to control it, and the issue would still happen if a single layer exceeds the available memory.

**Comment by s4ke** [comment]
If you are using an nginx proxy in front of the docker harbor provided one, you might want to try setting

```
    # this is necessary for us to be able to disable request buffering in all cases
    proxy_http_version 1.1;
```
