### ISSUE TITLE
Vulnerability found in harbor-db and harbor-core

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11681]
(build.3329) Push harbor-db and harbor-core into harbor and scan them with trivy.

Got these VUL, we need to upgrade base images to fix them. 

![image](https://user-images.githubusercontent.com/2841473/79852064-c183f480-83f8-11ea-814c-ae0e88fc3eb1.png)

**Comment by bitsf** [comment]
check with current build 
https://storage.googleapis.com/harbor-releases/release-2.0.0/harbor-offline-installer-v2.0.0-build.3356.tgz

harbor-db
![image](https://user-images.githubusercontent.com/188115/80445276-6b5a0880-8946-11ea-85d7-5fdfcbd3039c.png)

harbor-core
![image](https://user-images.githubusercontent.com/188115/80445337-993f4d00-8946-11ea-8fb4-61c9661b9588.png)

**Comment by bitsf** [comment]
Verified build 3378 with upgraded photon base images, all Vulnerabilities have gone
![image](https://user-images.githubusercontent.com/188115/80464315-32cd2580-896c-11ea-8dff-dace2b8b0208.png)

**Comment by kofj** [comment]
@bitsf  What version/tag/digest you upgraded?
