### ISSUE TITLE
harbor2.0 the title "Harbor Api" is ambiguous

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11689]
The title "Harbor Api" is ambiguous. It might be "Harbor Chartmuseum Api".

![image](https://user-images.githubusercontent.com/188115/80055581-92829580-8554-11ea-9297-998651813137.png)

**Comment by ywk253100** [comment]
The second `Harbor Api` is rendered by the swagger file https://github.com/goharbor/harbor/blob/master/api/swagger.yaml which contains all APIs with no version prefix. It consists of two kinds of API currently: chart museum API and get version API.

So `Harbor Chartmuseum Api` isn't a proper name, but I agree that the current name `Harbor Api` is ambiguous indeed.

**Comment by reasonerjt** [comment]
Let's hide the "Harbor Api" item.

**Comment by bitsf** [comment]
verified in build 3378
