### ISSUE TITLE
强烈建议增加定时删除清理镜像策略

### ISSUE THREAD

**Issue by zhaogj1987** [goharbor/harbor#1168]
强烈建议增加定时删除清理镜像策略

**Comment by hainingzhang** [comment]
Deleting images and recycling free space requires shutting down the registry, this cannot be scheduled and completed automatically.

**Comment by zhaogj1987** [comment]
想提个小的需求 应该也会有很多人有
随着我们仓库的越来越大 存储的镜像也越来越多 但是有很多镜像我们一段时间后就不用了
所以 是否可以新增一个镜像定期删除策略 由用户自定义保留多久以前的镜像
建议策略 粒度越小 优先级越高
比如项目定义保留30天以内的镜像
某个仓库保留60天 就保留60天

这是另一个人的提问，这个也是我们想要的

**Comment by hainingzhang** [comment]
Thanks for your suggestion, we will consider this in later release. 

However, since the recycling image space requires shutting down the registry, the user must know there will be down time during the scheduled recycling of images. Please refer to the user guide about the Gargage collection for more explanation.

**Comment by nuaays** [comment]
@hainingzhang why register should be shutted down when deleting images?

**Comment by hainingzhang** [comment]
yes, please refer to our user guide: https://github.com/vmware/harbor/blob/master/docs/user_guide.md

**Comment by swqmaven** [comment]
自动清理这个支持！！！

**Comment by moooofly** [comment]
This is so-called "**Retention Policy**".

**Comment by nlowe** [comment]
We're looking into something like this as well. If this isn't something harbor supports (or is going to support) we might have to consider another registry or weigh that against developing our own solution for retention.

**Comment by linydquantil** [comment]
up up

**Comment by Eddie-he** [comment]
up

**Comment by reasonerjt** [comment]
Let's track this requirement in #5882
