### ISSUE TITLE
Error raised when enabling webhook after upgrading from 1.9.0 to 2.0.0

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11696]
<img width="1170" alt="Screen Shot 2020-04-23 at 13 45 22" src="https://user-images.githubusercontent.com/5753287/80064068-cfa55280-8569-11ea-9b5e-edbffd4e1542.png">

Flow:

 - install 1.9.0
 - add a webhook endpoint (not reachable) and disable it
 - upgrade to 2.0.0
 - select the configured endpoint and click `enable`, error occurred

**Comment by steven-zou** [comment]
1.10 to 2.0.0 same issue

**Comment by renmaosheng** [comment]
@mmpei we need to get the code fix in before 4/28, thanks.

**Comment by steven-zou** [comment]
Verified with build: harbor-offline-installer-v2.0.0-build.3388.tgz
