### ISSUE TITLE
Retention rule treats the push time of untagged artifact as nil

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11690]
I have a repository which pushes time show as below

![image](https://user-images.githubusercontent.com/2841473/80056289-71bb3f80-8556-11ea-83fc-94fbb9521dba.png)

But, in the retention log, it shows as nil

2020-04-23T03:22:26Z [INFO] [/pkg/retention/job.go:83]: Run retention process.
 Repository: library/busybox 
 Rule Algorithm: or 
 Dry Run: true
2020-04-23T03:22:26Z [INFO] [/pkg/retention/job.go:98]: Load 2 candidates from repository library/busybox
2020-04-23T03:22:26Z [INFO] [/pkg/retention/job.go:201]: 
|                                 Digest                                  |  Tag   | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|--------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12 | latest | image |        | 2020/04/23 03:18:55 | 0001/01/01 00:00:00 | 2020/04/23 03:18:55 | RETAIN    |
| sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a |        | image |        | 0001/01/01 00:00:00 | 0001/01/01 00:00:00 | 2020/04/21 13:11:35 | DEL       |

**Comment by bitsf** [comment]
time value is int64(-62135596800) when shown as "0001/01/01 00:00:00"
time value is 0 when shown as "1970/01/01 08:00:00"

**Comment by bitsf** [comment]
Can't reproduce case PushedTime is nil.
This should be some corner case, that in database artifact.push_time and tag.push_time not synced, and tag.push_time seems be nil.

**Comment by wy65701436** [comment]
For the untagged artifact, retention sees its push time as `0001/01/01 00:00:00`, which will cause the reserved taged to be deleted.
