### ISSUE TITLE
harbor2.0 there's no pull command and bad artifact icon

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11705]
1.  The icon should not be "ROCKET"
2. The pull command should be oras pull 10.184.93.50/myoras/test@sha:xxxxxx

![image](https://user-images.githubusercontent.com/188115/80099051-6bea4c00-85a0-11ea-98f4-b06b4a83c540.png)

oras reference https://github.com/deislabs/oras

**Comment by reasonerjt** [comment]
For unrecognized artifact it's OK there's no pull command.

Let's see if we can reproduce the issue that the tooltip is showing `ROCKET`

**Comment by AllForNothing** [comment]
This type is returned by back-end API:
![image](https://user-images.githubusercontent.com/30999793/80195119-ffc62180-864d-11ea-97dc-a5b08e702056.png)

**Comment by reasonerjt** [comment]
the type was extracted from the header and the header was set when issuing oras push.

So this is working as designed, I'm resolving as won't fix.
