### ISSUE TITLE
Duration of tag retention is refreshed even it reaches the final status.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11702]
I have executed several times of tag retention, and all of them are reached to the final status.

Is it caused by retention job retry？

![image](https://user-images.githubusercontent.com/2841473/80085399-bd87dc00-858a-11ea-84db-8b955a87967f.png)

But, after I switch to other pages and back again, it's changed.

![image](https://user-images.githubusercontent.com/2841473/80085969-94b41680-858b-11ea-9434-f3b8e1f24518.png)

**Comment by reasonerjt** [comment]
the retention job should not auto retry.
