### ISSUE TITLE
Replication does not handle the extra "/" well

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11700]
**Steps to reproduce the problem:**
I have a Harbor instance A with an repository like `/test/ns/redis`
I created a replication policy on instance A to push to instance B target namespace `jt-test`
I also created a replication policy on instance B to pull from instance A target namespace `my-test`

After executing the replication policies, I expect on instance B there should be repositories `jt-test/ns/redis` and `my-test/ns/redis`,

but actually on instance B there are `jt-test/redis` and `my-test/redis`.  It seems the way it split the repo's name has a problem

**Versions:**

- harbor version: v2.0.0-rc

**Additional context:**

**Comment by wuzhihui1123** [comment]
i have the same problem, My harbor version is 1.9.1, the problem still exists when I upgrade to 1.10.2。

**=== Example ===**
**harbor host**: harbor.example.com
**project**:  docker.io
**image a**:  harbor.example.com/docker.io/apache/skywalking-ui:7.0.0
**image b**:  harbor.example.com/docker.io/skywalking-ui:7.0.0

the image a can be replicate,  but image b can't

**Comment by steven-zou** [comment]
@ywk253100 

I'm not sure whether the behavior mentioned here doe work as design or not?

**Comment by ywk253100** [comment]
It's working by design https://github.com/goharbor/harbor/blob/master/src/replication/operation/flow/stage.go#L308
