### ISSUE TITLE
Quota does take effect on immutable index

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11710]
[Steps]
1, push a hello-world:latest
2, set an immutable rule to match all of repos and tags
3, set a docker hub replication rule to replication hello-world:latest.

Step 3 will be eventually failed by the immutable setting, but the children manifest have been already replicated into the project and the quota is not updated.

**Comment by heww** [comment]
Quota summary showed that the project had used `47.16KB` storage, but in artifacts page there is a artifact which size is `96.44MB`. That becuase the artifact is a window image, which include a forgin layer which size is `96.4339990616MB` .

![image](https://user-images.githubusercontent.com/5634205/80185153-72c79c00-863e-11ea-97d0-ee7ca6b7e26e.png)

![image](https://user-images.githubusercontent.com/5634205/80185315-bc17eb80-863e-11ea-97eb-9044b621951b.png)

**Comment by reasonerjt** [comment]
It's expected that the foreign layer should not be taken into account when calculating the quota.

**Comment by xaleeks** [comment]
if a replication policy is active on the repo, the sync should happen as soon as the image is pushed onto it.  If you set an immutable policy before the entire index and children images are fully replicated, it should fail the job and generate a webhook.  @wy65701436
