### ISSUE TITLE
Group Claim Name not working in Harbor with OIDC provider ( GitLab) 

### ISSUE THREAD

**Issue by Manjul1987** [goharbor/harbor#11729]
What can we help you?
Harbor version: 1.10.2
OIDC provider: Gitlab

 I have successfully configured oidc_auth mode, used GitLab as OIDC provider and authentication working as expected. However its not working Group Claim Name. I configured Group Claim Name in the initial configuration. Group name (ex:  XYZ) is visible under the group tab and attached XYZ group to project (ex:  demo) in the harbor. As I’m a member of XYZ group in GitLab, so I should be able to `demo` project in the harbor,  but it's not visible. That means the members of XYZ group are not propagating in the harbor.

**Comment by reasonerjt** [comment]
Have you double-checked that the ID token by gitlab has the group claim as configured in Harbor?

Could you paste the ID token here in the issue?

**Comment by Manjul1987** [comment]
Hello @reasonerjt , 
Here I got the id token. 

`{
    "access_token": "8f8518f1580a83b741c3f2c346b88d54ee8b538f40d937449b923555f16faf23",
    "token_type": "Bearer",
    "refresh_token": "f96aae1321f71416ebaa28aaea4b2d046b0f980fe259e716ecc934d92c40fc82",
    "scope": "openid email profile read_user",
    "created_at": 1587999030,
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Imtld2lRcTlqaUM4NEN2U3NKWU9CLU42QThXRkxTVjIwTWIteTdJbFdEU1EifQ.eyJpc3MiOiJodHRwczovL2dpdGxhYi5jb20iLCJzdWIiOiI1ODYzNzY4IiwiYXVkIjoiNWFiMDQwMzBiZTFiZmY0N2M0YWZhOTBkYWRmYThlOGY3NTExNGQ5NTc4OTMwMTExNmY1YmJjYTVlYjgwYjI5NSIsImV4cCI6MTU4Nzk5OTE1MCwiaWF0IjoxNTg3OTk5MDMwLCJhdXRoX3RpbWUiOjE1ODc5Njk5ODEsInN1Yl9sZWdhY3kiOiIyN2Y5YWMwMmRjMTQ2MGQ2ZmRkMjE5ODJiNjczNmE3YzI1YzE3NjhmNTRjNWM5NmUxYTc3MDRlNGEzMjY4MzQxIn0.gebkbc8Iy3ANBjLISVS0FNa51E8gr4S3TQKDQQ8IJVHO6gh1ZJpsPAxnNx_APn-mZEL2vOTMmmpsprX6aVDdC-k93b7aglnXWAoOZULxQD6ZbbDwdAPIITjTw9TaPAo_ieoRrV0Zi_BpsNfOoAHN9_HjGuL_IeCWONv75U11CXj6CcQsk5gFE5HIXyS5jWIq4hB1EhmaRo20rHoBvscHL7Qy3qhJUiQJvPij0KdRDXvrhyYjAHylbo4XHFukHVWNhQ8woe_dLq82bL0FLxqyOwsdFNkF5Qcw1FQe6vZeqUdvOkj_BzrZQPoFpRwe6Rlqa5JrFgcFgeHe7g9rPl5RfMtB4bKbhj5R2hbAuo9AM_rTfkZbnHjp7Eeogvx8IlWsUtoCaBEq7elwY7Q1DUJj_J1FXjkrp_qcBm1ufHhJJuoSLTNwemeIqUXdwmpLtR1MXVin7A58KC_Hrjo4Wgldc2s-syPRjtxVs71YlQ9JFtBTQwb061CTlrlYkMy-JAZj-8xkbpKZ1gqH-zGc_A933FkvLgLGOosKhrJ52Hnrs6G1YN7Gp9cdZlHGaWwJAAAhFTlJ-kPMHzd1VclNyBZlNn-duKPEGFuK6kejUCfCjOMvFfiaIuPlSua1i8jEO201pOVsTuPekafw4Y1wgMRcCBqGK5wRF5YZsTtsQ-fDGlM"
}`

**Comment by Manjul1987** [comment]
Hello @reasonerjt, 

The issue has been resolved.
I furnished `Group Claim Name ` as a group name available in GitLab instead; we have to provide `groups`.
