### ISSUE TITLE
LDAP Search Password is not able to read from config file. [v1.6.3]

### ISSUE THREAD

**Issue by Vox1984** [goharbor/harbor#11723]
I can reproduce it every time - ldap_search_pwd is set in harbor.cfg, prepare populate properly ./common/config/adminserver/env But the GUI harbor/configs tab - LDAP Search Password
is not able to read this password and authenticate.

**Expected behavior:
LDAP Search Password gets read properly from ` ./common/config/adminserver/env `and I am able to authenticate with LDAP.

**Actual behaviour:
> ldap search fail: Can not bind search dn, error: LDAP Result Code 49 "Invalid Credentials": Simple Bind Failed: NT_STATUS_LOGON_FAILURE

**Steps to reproduce the problem:**
1. `ldap_search_pwd` is set in harbor.cfg
2. run `./prepare` script 
3. `./common/config/adminserver/env LDAP_SEARCH_PWD` is populated (equals the one in harbor.cfg)
4. `GUI harbor/configs tab - LDAP Search Password `is filled by ****** but authentication to LDAP does not work
5. By copy - pasting password to GUI from `./common/config/adminserver/env`  everything works fine.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.6.3
- docker  version: Docker version 18.06.3-ce, build d7080c1
- docker-compose version: docker-compose version 1.23.2, build 1110ad0

**Comment by reasonerjt** [comment]
@Vox1984 
I think this works as expected, api will not return decrypted password for security reasons

**Comment by reasonerjt** [comment]
at some version you can no longer that ldap password in configuration file.

**Comment by Vox1984** [comment]
thanks, i moved to 1.10.2 and it is no longer an issue
