### ISSUE TITLE
Unable to add k8s.gcr.io - Unable to parse json key.

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#11724]
I wanted to pull kubernetes control plane images from k8s.gcr.io, onto my local harbor instance.

![image](https://user-images.githubusercontent.com/5045325/80206582-3437de80-864a-11ea-9152-d4bb1d96885c.png)

I tried all the options in the drop-down, 
gcr.io
us.gcr.io
eu.gcr.io
asia.gcr.io

Logs in harbor-core
[DEBUG] [/common/utils/registry/auth/tokenauthorizer.go:214]: scopes parsed from request: 
[ERROR] [/replication/adapter/googlegcr/adapter.go:129]: failed to ping registry https://us.gcr.io: http error: code 400, message {"errors":[{"code":"UNKNOWN","message":"Unable to parse json key."}]}
[ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}

I referred to https://github.com/goharbor/harbor/issues/7784, however in my case I was able to ping/curl the gcr.io endpoints perfectly fine.
sample
```
harbor [ /harbor ]$ curl https://k8s.gcr.io
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://cloud.google.com/container-registry/">here</A>.
</BODY></HTML>
harbor [ /harbor ]$ 
harbor [ /harbor ]$ curl https://gcr.io
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://cloud.google.com/container-registry/">here</A>.
</BODY></HTML>
```

harbor version: 1.10.1
docker engine version: 19.03.7
docker-compose version: 1.25.4

**Comment by steven-zou** [comment]
@bitsf 

Let's take a look at what happened. I also tried before, it really does not work. I'm also wondering if the images of k8s.gcr.io are public ones, how can I directly replicate them without JSON key?

**Comment by bitsf** [comment]
You should input the entire json in the textarea.
![image](https://user-images.githubusercontent.com/188115/80300661-34161b00-87d1-11ea-99d5-dfdad748ed2b.png)

The key is something like
![image](https://user-images.githubusercontent.com/188115/80300682-66c01380-87d1-11ea-841f-a962aa94fde0.png)

And your account should have `Storage Admin` role in IAM setting
![image](https://user-images.githubusercontent.com/188115/80300801-4a70a680-87d2-11ea-8632-ee6167b70723.png)


And in replication rule, you should also input the namespace
![image](https://user-images.githubusercontent.com/188115/80300704-8fe0a400-87d1-11ea-96a4-3daab714c7b9.png)
![image](https://user-images.githubusercontent.com/188115/80300809-578d9580-87d2-11ea-8e97-976adfc50922.png)


And the replication can work as
![image](https://user-images.githubusercontent.com/188115/80300736-c61e2380-87d1-11ea-916a-33de8182c45e.png)

**Comment by bjethwan** [comment]
@bitsf 
Do I need this even for public k8s control plane images?
I am not using GCR for more than replicating k8s images.

**Comment by bitsf** [comment]
@bjethwan Yes, we need credential, this is because GCR _catalog API which we use to list repositories need authorization.

**Comment by soulawaker** [comment]
@bitsf Currently Habor does not allow users to add gcr endpoint without credentials. But Docker client can pull distroless images from gcr.io without any credential. Really no method to pull public images from gcr.io without credential?

**Comment by steven-zou** [comment]
@soulawaker 

Have you tried to replicate public GCR images with the `Docker Registry` adapter?

I tried to replicate k8s.gcr.io by the `Docker Registry` adapter without providing json_key, it does work.

cc @bitsf

**Comment by bitsf** [comment]
if you don't need use * to filter, you can use docker registry adapter.

**Comment by soulawaker** [comment]
@steven-zou 

OK, I confirmed to work. 
1. Go to the Administraion > Registries.
2. Create New Endpoint with `docker-registry` as a Provider and `https://gcr.io` as an Endpoint URL. 
3. Apply that registry to the Replication Rule.

Thanks for suggesting workaround.
