### ISSUE TITLE
Notary was with error "timestamp key trust data unavailable" with DOCKER_CONTENT_TRUST_SERVER variables defined.

### ISSUE THREAD

**Issue by jepsenwan** [goharbor/harbor#11736]
I have enabled harbor with Notary:

And I found the images were pushed, but they were with below error:

[root@swarm-manager01 harbor]# docker push  harbor.xxx.com/baseimages/nginx:latest
The push refers to repository [harbor.xxx.com/baseimages/nginx]
3ff93588120e: Layer already exists 
24ee0a3fd4b9: Layer already exists 
d626a8ad97a1: Layer already exists 
latest: digest: sha256:1f9c00b4c95ef931afa097823d902e7602aebc3ec5532e907e066978075ca3e0 size: 948
Signing and pushing trust metadata
Enter passphrase for root key with ID cb8826c: 
Enter passphrase for new repository key with ID 8cef995: 
Repeat passphrase for new repository key with ID 8cef995: 
Error: trust data missing for remote repository harbor.xxx.com/baseimages/nginx or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized?

There seems to be no root_keys directory.

[root@swarm-manager01 .docker]# tree
.
├── config.json
├── tls
│   └── harbor.xxx.com
│       └── ca.crt
└── trust
    ├── private
    │   ├── 21967787b5b627b48cadb869d7960f5f39038d755e5214d309fda11817f7bb2b.key
    │   ├── 27f596b0bce13216d870e3d5a22e80c87aaad03a089006db2f80a10e5932f53e.key
    │   ├── 53a30bcf455221746edd0e0e076daa744d9a1ce5460939c43f117a9d5ee28d58.key
    │   ├── 8cef995ef501dfc5adcfabc5ad03277e40f25f9718c3f223a31cc63fdb614e6a.key
    │   ├── cb8826c1d8cd796b6e312e2af8b54070ed06d7ce18ee007a3311bc7fd9c07d66.key
    │   └── ff3dedf3209663b10d5354fdedcc21d3c79bbff2bc006f834f5c5effcff8cc1c.key

[root@swarm-manager01 private]# pwd
/root/.docker/trust/private

[root@swarm-manager01 private]# ll
total 24
-rw------- 1 root root 466 Apr 26 13:41 21967787b5b627b48cadb869d7960f5f39038d755e5214d309fda11817f7bb2b.key
-rw------- 1 root root 466 Apr 26 13:44 27f596b0bce13216d870e3d5a22e80c87aaad03a089006db2f80a10e5932f53e.key
-rw------- 1 root root 466 Apr 26 13:39 53a30bcf455221746edd0e0e076daa744d9a1ce5460939c43f117a9d5ee28d58.key
-rw------- 1 root root 462 Apr 26 14:06 8cef995ef501dfc5adcfabc5ad03277e40f25f9718c3f223a31cc63fdb614e6a.key
-rw------- 1 root root 416 Apr 26 13:39 cb8826c1d8cd796b6e312e2af8b54070ed06d7ce18ee007a3311bc7fd9c07d66.key
-rw------- 1 root root 463 Apr 26 14:08 ff3dedf3209663b10d5354fdedcc21d3c79bbff2bc006f834f5c5effcff8cc1c.key

In docker doc, it says we need to define DOCKER_CONTENT_TRUST_SERVER variable, but it has been defined on my host:

[root@swarm-manager01 private]# echo $DOCKER_CONTENT_TRUST_SERVER
https://harbor.xxx.com

Please suggest if anything else I could check into.
Thanks.

Wan

**Comment by reasonerjt** [comment]
normally it's listening port 4443

**Comment by jepsenwan** [comment]
@reasonerjt 

Thanks. It indeed is. It is resolved now.

Wan
