### ISSUE TITLE
Harbor is not able to replication to remote harbor with OIDC connect

### ISSUE THREAD

**Issue by ruruiye** [goharbor/harbor#11731]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
recently I am trying to do a replication from one harbor to another. the remote is configured with OIDC, and I setup an account which has right permission, and I even can run docker login with the username and CLI token, but the replication failed with 401 unauthorized.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
It is known issue that you cannot create project using the CLI secret.
To workaround that could you create the project before running the replication, or use the system admin of the remote instance to do the replicaiton

**Comment by ruruiye** [comment]
it's still not work after all the project is created.

**Comment by reasonerjt** [comment]
When you say still not work, does the job fail?  could you attach the log of the job?

**Comment by ruruiye** [comment]
@reasonerjt yes, it's failed immediately, there is no task scheduled. and here is the log.
```
2020-04-28T02:37:40Z [ERROR] [/replication/operation/controller.go:108]: the execution 2072 failed: failed to do the prepare work for pushing/uploading resources: http error: code 401, message {"code":401,"message":"Unauthorized"}
```

this log is inside the core pod. not the job service.

**Comment by reasonerjt** [comment]
I checked the code, the replicator will issue POST regardless of the existence of the project, so it's not a valid workaround to create the project before replication. 

 Currently, you use OIDC secret to issue a POST to create a project it will fail with 401 immediately 

The only way to workaround is to use the system admin account.

**Comment by ruruiye** [comment]
Thanks @reasonerjt , if that's the only way I can set it up use the admin account. hope a future fix for this.

**Comment by reasonerjt** [comment]
@ruruiye 

It's on my radar and there will be a fix.

**Comment by reasonerjt** [comment]
Fixed in https://github.com/goharbor/harbor/pull/12596
