### ISSUE TITLE
upgrade harbor 2.0 from 1.10, db migration dirty fail

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11754]
when upgrade from 1.10 to 2.0, harbor core can't startup, because of db migrate fail
![image](https://user-images.githubusercontent.com/188115/80310349-b1ab4c80-880c-11ea-9532-52b1613fe51c.png)

**Comment by bitsf** [comment]
This error is because db migrate fail at first time, then the db is marked as dirty, and the container will continuously restart.

DB sql error, because some artifact.repository_id is null
![image](https://user-images.githubusercontent.com/188115/80310394-0058e680-880d-11ea-9def-a0c27cb7fed8.png)
![image](https://user-images.githubusercontent.com/188115/80310390-fcc55f80-880c-11ea-9721-e012533542ff.png)


There's a bad record "test/mmm" that has incomplete data.
![image](https://user-images.githubusercontent.com/188115/80310423-46ae4580-880d-11ea-8aa0-efadf36cd04c.png)


core.log
![image](https://user-images.githubusercontent.com/188115/80310446-62b1e700-880d-11ea-97b9-568f625d0cf5.png)

![image](https://user-images.githubusercontent.com/188115/80310457-765d4d80-880d-11ea-8e3e-3174fb6328b5.png)


registry.log
![image](https://user-images.githubusercontent.com/188115/80310450-6ba2b880-880d-11ea-8021-68bb8eebc832.png)

**Comment by reasonerjt** [comment]
This may happen to other users, we should try to make the migration script more resilient.

**Comment by wy65701436** [comment]
close it as PR https://github.com/goharbor/harbor/pull/11766 merged

**Comment by LunaticZorr** [comment]
@bitsf  I'm experiencing the same issue. We've been running Harbor for over 6 months without issues, but it seems some of the pods restarted a couple of days ago due to the instance failing, and harbor is not non-functional and the core container does not sart showing the same error you have on your first image. 
How can I fix this? I can't find any info on how to solve it.

**Comment by bitsf** [comment]
@LunaticZorr First we need to find why db migrate failed.
In my case, there's an unexpected record in table artifact.
So I just delete that record, then run the upgrade sql manually (harbor/make/migrations/postgresql/0030_2.0.0_schema.up.sql)
Then run sql `update schema_migrations set dirty=false;` to mark the migration done.

If you need further help, you should give more detail about your version and error messages.

**Comment by LunaticZorr** [comment]
> 
> 
> @LunaticZorr First we need to find why db migrate failed.
> In my case, there's an unexpected record in table artifact.
> So I just delete that record, then run the upgrade sql manually (harbor/make/migrations/postgresql/0030_2.0.0_schema.up.sql)
> Then run sql `update schema_migrations set dirty=false;` to mark the migration done.
> 
> If you need further help, you should give more detail about your version and error messages.
> And it's better open another issue, that we may not notice such closed issues.

Thank you @bitsf 

We ended up deleting the helm deployment and re-creating it fresh with the new version. We're now trying to re-read our docker images from S3. Any idea if these can be re-imported of harbor has been setup using the same S3/Bucket config?
