### ISSUE TITLE
Meaning of "Robot Token Expiration" in system setting of  is confused for user.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11764]
In harbor design, "Robot Token Expiration" in system setting means when creating a robot account without setting expiration, this robot account will use Robot Token Expiration" in system setting as default setting. This meaning should be more clear described in UI, like when creating a robot account , Expiration input should load this setting as default value for user.

**Comment by xaleeks** [comment]
![Screen Shot 2020-05-02 at 10 23 52 PM](https://user-images.githubusercontent.com/51319901/80897240-d5670a80-8cc4-11ea-809d-1630234099ee.png)

@AllForNothing

**Comment by AllForNothing** [comment]
@xaleeks @danfengliu There is a problem if do so. Only system admin can  read and set system value, but  roles like mater and  developer  can add new robot

**Comment by danfengliu** [comment]
I think since we have a hint for user, current design is OK for me.
