### ISSUE TITLE
No scan report from API

### ISSUE THREAD

**Issue by SDBrett** [goharbor/harbor#11775]
Version: 1.10.1

Issue: GET request to `/repositories/{repo_name}/tag/{tag_name}/scan` returns `{}`.
Expected result: Return information about vulnerability found.
Actual result: {} Status 200

A image has been uploaded to Harbor which has a vulnerability and CVE information about the vulnerability is displayed in the Harbor UI. This information cannot be obtained using the scan API request.

Tested with Curl and Harbor swagger.

Request URL (swagger): /repositories/library%2Fkuard-amd64/tag/blue/scan
Request URL (curl): /repositories/library/kuard-amd64/tag/blue/scan

Have tried with and without the mimetype header `application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0`.

Scan overview information is provided with /repositories/library/kuard-amd64/tags?detail=true but this does not provide any information on the CVE found.

**Comment by steven-zou** [comment]
@SDBrett 

>Have tried with and without the mimetype header application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0.

Tried with an accept header like 
```
curl -H 'Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0'
```

@heww please follow up on this issue to confirm if it's a real bug.

**Comment by SDBrett** [comment]
I ran curl with the header and it gave an error output. I'm awaiting approval to supply the stdout, but the gist is

Harbor: operator 'exact' need 1 args not 2
Request Method: GET
Request URL: /api/repositories/{repo_name}/tags/{tag}/scan (this was correct)
RemoteAddr: <Client IP Address>

**Comment by SDBrett** [comment]
I have checked the registry database and can view 4 scan reports in the scan_report table, with the information CVE info that I'm after.

I can use /api/repositories/{repo_name}/tags/{tag}/scan/{UUID}/log to get the log info

stdout from previous test
```

curl -X GET " /repositories/{repo_name}/tags/{tag}/scan" -H "accept: application/json" -H "authorization: Basic REMOVED" -H 'Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0'                               
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>beego application error</title>
    <style>
        html, body, body * {padding: 0; margin: 0;}
        #header {background:#ffd; border-bottom:solid 2px #A31515; padding: 20px 10px;}
        #header h2{ }
        #footer {border-top:solid 1px #aaa; padding: 5px 10px; font-size: 12px; color:green;}
        #content {padding: 5px;}
        #content .stack b{ font-size: 13px; color: red;}
        #content .stack pre{padding-left: 10px;}
        table {}
        td.t {text-align: right; padding-right: 5px; color: #888;}
    </style>
    <script type="text/javascript">
    </script>
</head>
<body>
    <div id="header">
        <h2>Harbor:operator `exact` need 1 args not 2</h2>
    </div>
    <div id="content">
        <table>
            <tr>
                <td class="t">Request Method: </td><td>GET</td>
            </tr>
            <tr>
                <td class="t">Request URL: </td><td>/api/repositories/{repo_name}/tags/{tag}/scan</td>
            </tr>
            <tr>
                <td class="t">RemoteAddr: </td><td>REMOVED</td>
            </tr>
        </table>
        <div class="stack">
            <b>Stack</b>
            <pre>/usr/local/go/src/runtime/panic.go:522
/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:1191
/harbor/src/vendor/github.com/astaxie/beego/orm/db_tables.go:380
/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:990
/harbor/src/vendor/github.com/astaxie/beego/orm/orm_queryset.go:213
/harbor/src/pkg/scan/dao/scan/report.go:81
/harbor/src/pkg/scan/report/base_manager.go:162
/harbor/src/pkg/scan/api/scan/base_controller.go:279
/harbor/src/core/api/scan.go:130
/usr/local/go/src/reflect/value.go:447
/usr/local/go/src/reflect/value.go:308
/harbor/src/vendor/github.com/astaxie/beego/router.go:853
/usr/local/go/src/net/http/server.go:2774
/usr/local/go/src/net/http/server.go:1878
/usr/local/go/src/runtime/asm_amd64.s:1337
</pre>
        </div>
    </div>
    <div id="footer">
        <p>beego 1.12.1 (beego framework)</p>
        <p>golang version: go1.12.12</p>
    </div>
</body>
</html>

```

**Comment by SDBrett** [comment]
Found the issue with the error I was receiving when adding the `application/vnd` header into the curl command. There were 2 accept commands in the curl string. When swagger displays the curl command it included both the `application/json` and `application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0` accept headers.

I have updated the curl command to remove `AcceptL=: application/json` and it appears to be working now

**Comment by heww** [comment]
The following curl will get the scan report of the `demo.goharbor.io/library/redis:5.0`.
```bash
curl -v -u admin:Harbor12345 -H "Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0" https://demo.goharbor.io/api/repositories/library/redis/tags/5.0/scan
```

The API request for `/api/repositories/*/redis/tags/{tag}/scan` to get the scan report need to set the `Accept` header to `application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0`.

**Comment by SDBrett** [comment]
My confusion stemmed from the curl command generated by the Swagger UI, as it contained both the the `application/json` and `application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0` accept headers.

**Comment by itsecforu** [comment]
@SDBrett did u solve it? Can u show whole command.
Form CLI it works fine:
` curl -i -k -X GET "URL/api/repositories/repo/tags/tag/scan" -u foo:bar -H "Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0"`

And i can get output with:

```
{
  "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0": {
    "generated_at": "2020-07-22T14:03:37.122940111Z",
    "scanner": {
      "name": "Clair",
      "vendor": "CoreOS",
      "version": "2.x"
    },
    "severity": "None",
    "vulnerabilities": null
  }
```

But via Gitlab CI is only **200 Ok Nginx** and **{}**

**Comment by blackdahlia** [comment]
Hy!

API: v2.0

My observation is `/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/scan` service works in an **asynchronous** way. I mean
1. send a POST request to `/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/scan`,
2. harbor API replies w/ status 202 (Accepted) but there is no response body so the result of the scan is unknown at this point because harbor runs scan in this moment.

If you would like to check the status of the scan you have to call `/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}` with query parameter `with_scan_overview=true` and you can check the scan_status in the response body. If the scan_status is "Success" then you can get the vulnerabilities (`artifact.addition_links.vulnerabilities.href`). Or you can call `artifact.addition_links.vulnerabilities.href` directly after scan because the scan runs fast.

Im trying to implement a script that starts scans for all images and after that get the vulnerabilities. When there is different images with the same digest value then the harbor api replies an error: `a previous scan process is Pending`. The problem is the asynchronous way of the scan.

I tried to use the `Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0` header but it did not work.
How to do scan in a **synchronous** way? If it is impossible then why? What is the logic behind this functionality?

**Comment by heww** [comment]
Hi, @blackdahlia There is no way to scan artifact in a synchronous way because this job may take a long time to run. The synchronous way will make the API timeout.
