### ISSUE TITLE
what kind of data will be stored in harbor-db

### ISSUE THREAD

**Issue by yuzp1996** [goharbor/harbor#11770]
Hello, I want know why harbor need database, what info will be stored in database. 

In other word, If I move harbor-db from harbor, what components will be affected. Is it  only clair?

**Comment by heww** [comment]
Most things you can access in the portal are saved in database. For example, users, projects, project members, project configurations, robot accounts, tag retention, webhooks, access logs, replications, quotas, interrogation services and so on.

**Comment by yuzp1996** [comment]
> Most things you can access in the portal are saved in database. For example, users, projects, project members, project configurations, robot accounts, tag retention, webhooks, access logs, replications, quotas, interrogation services and so on.

Thanks for your reply, I will close this issue now
