### ISSUE TITLE
Import existing Harbor registry from S3

### ISSUE THREAD

**Issue by LunaticZorr** [goharbor/harbor#11773]
What can we help you?

We've lost our Harbor setup which was using S3 for storage, and have created a new one. We're now trying to import all our images from S3 into the new setup.
We've created the new setup using the same S3 configuration, but the images do not show up. I can push new images to the registry and these show up withing S3.

Is there any way of importing the S3 images from S3? Even if not directly from Harbor. Is there any way of getting them back in?

Thank you!

**Comment by FrederikNS** [comment]
We just upgraded from harbor v1 to harbor v2, and the database migrations failed. We decided that we had all the data available in S3, so we could probably delete the harbor database and recreate it, and simply hook it up to the existing S3 bucket. But yeah, now we have a completely empty harbor, we can push images, and they show up in S3, but the images that are already present in S3 are not showing up and harbor, and pulling the image simply yields a `unknown: repository <repo-name> not found`.

**Comment by LunaticZorr** [comment]
> We just upgraded from harbor v1 to harbor v2, and the database migrations failed. We decided that we had all the data available in S3, so we could probably delete the harbor database and recreate it, and simply hook it up to the existing S3 bucket. But yeah, now we have a completely empty harbor, we can push images, and they show up in S3, but the images that are already present in S3 are not showing up and harbor, and pulling the image simply yields a `unknown: repository <repo-name> not found`.

Yep, same situation we faced. We ended up using a small bash script on everyone of our servers that pushed every image locally stored to the new registry. This way we at least recovered every working image we had. But many Dev and archived images were lost.

**Comment by FrederikNS** [comment]
It seems that there used to be a feature where you could set the `SYNC_REGISTRY` environment variable to `true`, and harbor would go and scan S3, however it was removed back in february without any explanation: https://github.com/goharbor/harbor/commit/bd204464f33d8d61f156f14c5a0da91296f8eb90

Would this feature be possible to ressurect?

**Comment by FrederikNS** [comment]
We desperately wiped our entire harbor registry and installed the latest v1 version (1.10.2) instead.

We manually recreated all the projects (not repositories) we had previously and set the environment variable `SYNC_REGISTRY=true` on the core container and then restarted it. This resulted in harbor starting up and scanning our entire registry, so we now have all our images present again. User accounts and similar settings are of course still lost though.

We will retry the upgrade to version 2 again.

**Comment by FrederikNS** [comment]
Hmmm, unfortunately it seems that none of the artifacts was detected, so we have a list of all the repositories, but no images within...

**Comment by reasonerjt** [comment]
@FrederikNS 
In v2 we use DB as the source of truth for tags.  So it seems in your migration v1.10 -> v2.0 the tags are failed to populate into the DB.

After you sync the registry in 1.10 as described in https://github.com/goharbor/harbor/issues/11773#issuecomment-641418113, did you try to upgrade again? Was is successful and could you provide the log of harbor-core so we can check?

**Comment by FrederikNS** [comment]
Yes, we did try the upgrade again, but that resulted in all the artifacts going missing... I do unfortunately not have the logs available.

**Comment by bitsf** [comment]
Is it possible that querying S3 is very slow, and db sync is not finished after upgrade.
Maybe you can try use a small set of images on S3, testing if upgrade still fail.

**Comment by reasonerjt** [comment]
IMO we may start by providing a external tool in future to help user check the consistency, and sync data.

**Comment by artbegolli** [comment]
So to confirm - if we have S3 backing our harbor registry and we need to failover we won't be able to restore our images from our S3 bucket? This seems like a quite a critical and common workflow so I'm quite surprised I can't sync data previously in S3?

**Comment by steveal** [comment]
same problem, but we use local storage
we use  v1.3.1, and want to upgrade to v2.2.0
upgrade path  v1.3.1 -> 1.18  -> 1.10 -> 2.2.0
after upgrade to v2.2.0 , we cant' see the atrifact info.

we find a solution to sync atrifact info in v1.10
1. delete all info in quota_usage , 
2. set common/config/core/env SYNC_QUOTA=true
3. restar harbor-core contianer
4. you will see message in /var/log/harbor/core like below
 ```
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/main.go:110]: Start to sync quota data .....
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:90]: [Quota-Sync]:: start to ping server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:95]: [Quota-Sync]:: success to ping server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:96]: [Quota-Sync]:: start to dump data from server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:102]: [Quota-Sync]:: success to dump data from server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:109]: [Quota-Sync]:: start to persist data for server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quo4ta/registry/registry.go:212]: [Quota-Sync]:: start to persist artifact&blob for project: library, progress... [0/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:224]: [Quota-Sync]:: success to persist artifact&blob for project: library, progress... [0/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:212]: [Quota-Sync]:: start to persist artifact&blob for project: demo, progress... [1/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:224]: [Quota-Sync]:: success to persist artifact&blob for project: demo, progress... [1/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:283]: [Quota-Sync]:: start to persist project&blob for project: library, progress... [0/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:316]: [Quota-Sync]:: success to persist project&blob for project: library, progress... [0/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:283]: [Quota-Sync]:: start to persist project&blob for project: demo, progress... [1/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/registry/registry.go:316]: [Quota-Sync]:: success to persist project&blob for project: demo, progress... [1/2]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/api/quota/migrator.go:114]: [Quota-Sync]:: success to persist data for server ... [registry]
Mar 11 10:44:14 192.168.80.1 core[6928]: 2022-03-11T02:44:14Z [INFO] [/core/main.go:115]: Success to sync quota data .....
````
5.  you will see atrifact, artifact_blob, quota_usage info in postgres, now you can upgrade to v2.2

you cant find the way by see code in 
release-1.10.0  
```
# src/core/main.go:89 
# delete quota_usage info to force sync
// Quota migration
func quotaSync() error {
	projects, err := dao.GetProjects(nil)
	if err != nil {
		log.Errorf("list project error, %v", err)
		return err
	}

	var pids []string
	for _, project := range projects {
		pids = append(pids, strconv.FormatInt(project.ProjectID, 10))
	}
	usages, err := dao.ListQuotaUsages(&models.QuotaUsageQuery{Reference: "project", ReferenceIDs: pids})
	if err != nil {
		log.Errorf("list quota usage error, %v", err)
		return err
	}

	// The condition handles these two cases:
	// 1, len(project) > 1 && len(usages) == 1. existing projects without usage, as we do always has 'library' usage in DB.
	// 2, migration fails at the phase of inserting usage into DB, and parts of them are inserted successfully.
	if len(projects) != len(usages) {
		log.Info("Start to sync quota data .....")
		if err := quota.Sync(config.GlobalProjectMgr, true); err != nil {
			log.Errorf("Fail to sync quota data, %v", err)
			return err
		}
		log.Info("Success to sync quota data .....")
		return nil
	}

	// Only has one project without usage
	zero := common_quota.ResourceList{
		common_quota.ResourceCount:   0,
		common_quota.ResourceStorage: 0,
	}
	if len(projects) == 1 && len(usages) == 1 {
		totalRepo, err := dao.GetTotalOfRepositories()
		if totalRepo == 0 {
			return nil
		}
		refID, err := strconv.ParseInt(usages[0].ReferenceID, 10, 64)
		if err != nil {
			log.Error(err)
			return err
		}
		usedRes, err := types.NewResourceList(usages[0].Used)
		if err != nil {
			log.Error(err)
			return err
		}
		if types.Equals(usedRes, zero) && refID == projects[0].ProjectID {
			log.Info("Start to sync quota data .....")
			if err := quota.Sync(config.GlobalProjectMgr, true); err != nil {
				log.Errorf("Fail to sync quota data, %v", err)
				return err
			}
			log.Info("Success to sync quota data .....")
		}
	}
	return nil
}
```

**Comment by steveal** [comment]
For the recorder, find a better solution,
after upgarde to v1.10 , call for harbor api 
```
1. POST
​/internal​/syncregistry
Sync repositories from registry to DB.
2. POST
​/internal​/syncquota
Sync quota from registry/chart to DB.
```

**Comment by rwd5213** [comment]
Anyone find a solution for this, lost our harbor postgres and recreating the harbor deploying pointing at the same bucket does not populate images

**Comment by EsDmitrii** [comment]
the same for me
tried to push `grafana:latest` to Harbor, got 'received unexpected HTTP status: 500 Internal Server Error'
<img width="573" alt="Screenshot 2023-07-04 at 19 38 54" src="https://github.com/goharbor/harbor/assets/124890665/3adbbf26-b795-402f-9036-50de55425636">

I can see data in my S3:
<img width="484" alt="Screenshot 2023-07-04 at 19 40 03" src="https://github.com/goharbor/harbor/assets/124890665/e86158d1-6fef-42ab-beb8-94ae58f6624f">

But nothing displays in Harbor (but as you can see we have something inside by used quota):
<img width="1662" alt="Screenshot 2023-07-04 at 19 40 45" src="https://github.com/goharbor/harbor/assets/124890665/10601d81-3305-46fc-9059-0b26279f0f6b">

When I try to pull the image, I get `Error response from daemon: unknown: repository library/grafana not found`

**Comment by EsDmitrii** [comment]
I put ours custom CA to `caBundleSecretName`, and now all works well
