### ISSUE TITLE
x509: certificate signed by unknown authority [with trusted ssl]

### ISSUE THREAD

**Issue by emrax** [goharbor/harbor#11772]
docker login harbor.xxx.com returns 

x509: certificate signed by unknown authority. 

I have trusted ssl cert. (not self-signed ) 

But it seems that registry does not accepting it? 

What should I do to fix this issue ?

**Comment by stonezdj** [comment]
You need to check verify the current certificate trusted by command:
```
curl -v  https://harbor.xxx.com 
```

**Comment by emrax** [comment]
the root cause was expired ssl certificate(root certificate), 
for more details;

https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020
