### ISSUE TITLE
harbor 2.0 it should show "Not Scanned" in detail panel if artifact is never scanned

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11782]
Here, the test image is not scanned, and it shows "Not Scanned" in list view
![image](https://user-images.githubusercontent.com/188115/80464821-ecc49180-896c-11ea-80e5-f2f30d1f6b88.png)

However in the Vulnerabilities detail panel, it shows "No recognizable vulnerability found" on UI, this is not accurate.
![image](https://user-images.githubusercontent.com/188115/80464856-f817bd00-896c-11ea-9e8f-c816bbc87b16.png)

**Comment by AllForNothing** [comment]
1.  I think "No recognizable vulnerability found" is normally the result  of "Not Scanned"
2.  To show "Not Scanned" is not good looking
@xaleeks What's your oppinion?

**Comment by reasonerjt** [comment]
Let's defer it

**Comment by xaleeks** [comment]
'no vulnerabilities detected' implies its been scanned at least once
lets do this:

If (image has not been scanned)
    show 'not scanned'
else
    if (no cves detected in scan)
         show 'no vulnerabilities detected'
etc..
