### ISSUE TITLE
Pulling image takes long time and retries some layers

### ISSUE THREAD

**Issue by zerone12** [goharbor/harbor#11796]
Below is My environment.

Harbor helm version : 1.3.2
k8s : rancher 2.4.2 rke cluster
nginx(tls termination) - ingress - harbor
**==plus==
backend storage : minio(with same nginx proxy, not in k8s cluster)**

It takes only few seconds when pushing images to harbor, but when pulling images from harbor, some layers are pended and retry while other layers are downloaded speedy.
After first retrying, pended layers are downloaded speedy like other layers.

On harbor-core pod, some errors like below are logged that time
2020/04/28 05:47:16.774 [C] [panic.go:522]  Handler crashed with error net/http: abort Handler
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/runtime/panic.go:522
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/net/http/httputil/reverseproxy.go:309
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/registryproxy/handler.go:60
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/countquota/handler.go:55
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/immutable/handler.go:55
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/sizequota/handler.go:55
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/vulnerable/handler.go:46
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/contenttrust/handler.go:45
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/listrepo/handler.go:90
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/multiplmanifest/handler.go:47
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/regtoken/handler.go:32
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/url/handler.go:73
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/readonly/hanlder.go:44
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/middlewares/inlet.go:56
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/core/controllers/proxy.go:22
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/reflect/value.go:447
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/reflect/value.go:308
2020/04/28 05:47:16.774 [C] [panic.go:522]  /harbor/src/vendor/github.com/astaxie/beego/router.go:853
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:2774
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/net/http/server.go:1878
2020/04/28 05:47:16.774 [C] [panic.go:522]  /usr/local/go/src/runtime/asm_amd64.s:1337

This situation occurs usually when pulling image that has layers which is not exist on my machine yet.

Could you please help me?

**Comment by xtreme-conor-nosal** [comment]
I'm encountering the same stack trace with harbor-helm 1.3.3/harbor 1.10.3, on GKE with s3 backend

**Comment by ywk253100** [comment]
Similar issues: https://github.com/goharbor/harbor/issues/10813 https://github.com/goharbor/harbor/issues/12011

**Comment by reasonerjt** [comment]
When Harbor is serving a request for pulling an image, `harbor-core` is acting as a proxy.
Per my investigation, oftentimes the root cause is that the backend is too slow so the proxy closed the connection, which then causes such error in `harbor-core`

Please check the the logs in your ingress controller or nginx proxy or even backend storage to find out why it took so low to serve the content.

In my case I set the CPU quota of the pod to extreme low by mistake, which makes the registry unable to handle parallel requests and caused the timeout.

**Comment by AnavMahajan** [comment]
Similar issue https://github.com/goharbor/harbor/issues/15751
