### ISSUE TITLE
How to access Harbor APIs when it is exposed as clusterIP 

### ISSUE THREAD

**Issue by Karthik11Hegde** [goharbor/harbor#11793]
What can we help you?
When i expose the Harbor as ingress, then i can access the administration UI to create user, project, endpoints. But when i choose to expose it as "clusterIP", how can i do all these operations similar to what UI provides?
Where can i get the API list through which i can create the user, project, endpoint etc... using the clusterIP?

**Comment by ninjadq** [comment]
clusterIP only accessible in your k8s cluster, If you wanna access it from outside of your harbor API, you must choose ingress or nodeport or loadbalance.

**Comment by Karthik11Hegde** [comment]
Yes, i want to access only within the k8s cluster. So, in this case how can i do the administration tasks using the clusterIP? Are there APIs for this?

**Comment by ninjadq** [comment]
If your application is in the same k8s cluster, it can access harbor api directly
