### ISSUE TITLE
[Request] Add user from LDAP

### ISSUE THREAD

**Issue by cavemandaveman** [goharbor/harbor#1180]
Currently as of 0.5.0-rc2, if you have ldap setup, you cannot add a member to a project without them first logging in to Harbor.

It would be nice if the "Add Member" function could do a query against ldap first, and if that username exists, add them.

Or to take it one step deeper, maybe have "Add User" functionality in the "Users" section of the "Admin Options" that does the ldap querying if you want to add someone without them logging in first. Then the "Add Member" functionality won't have to change.

**Comment by hainingzhang** [comment]
Thanks for this suggestion. We will consider it in future release.

**Comment by reasonerjt** [comment]
@cavemandaveman thanks for raising this.
Indeed, we are considering add an "on board" process, that admin can import users from ldap to Harbor , some enhancement around ldap support will be added in near future.

**Comment by jiangshouzhuang** [comment]
@reasonerjt 
when using admin user to import users from ldap, we should consider synchronize users from ldap server which adds new users.

**Comment by yhua123** [comment]
#1355

**Comment by reasonerjt** [comment]
Closing as a user in ldap can be automatically "onboard" to Harbor
