### ISSUE TITLE
It takes very long for smtp.exmail.qq.com to return if credentials are incorrect.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#1181]
With current code if the mail server is set to 
host: smtp.exmail.qq.com
port: 465
ssl: true

And when the credential is incorrect, the function ```sendMailWithTLS``` takes 1 minute to return.

Per investigation seems smtp package does not work very well with this mail server. 
An issue has been opened to golang to track:
https://github.com/golang/go/issues/18094

We don't plan to hack go's library to workaround this issue at least for 0.5.0.

**Comment by frankli0614** [comment]
@reasonerjt the port should be 465.

**Comment by reasonerjt** [comment]
thanks @frankli0614
