### ISSUE TITLE
redhat registry as replication endpoint

### ISSUE THREAD

**Issue by tspreeth** [goharbor/harbor#11817]
For registry replication, could we add redhat endpoint in the list? it would be verfy useful for enterprises to adapt harbor as registry, where they want to redhat ubi images.

**Comment by xaleeks** [comment]
Quay.io is supported.  Please see this : https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-endpoints/

**Comment by chlins** [comment]
Closed as supported.
