### ISSUE TITLE
Can I create User Groups with Database authentication?

### ISSUE THREAD

**Issue by jgreat** [goharbor/harbor#11819]
I can see there's a grayed out option to assign groups to projects as members, but I can't find a place to create the groups in the UI.

Assigning individual users to projects is pretty painful.

I'm using the local database as the authentication source.

Harbor Version v1.10.2-d0189bed

**Comment by xaleeks** [comment]
If there is way to do it, I'm certainly not aware and no documentation exists for it.  Groups seem to be limited to ldap and oidc authn.  For ldap, it's enabled by the memberof feature of the ldap server

**Comment by xaleeks** [comment]
I just checked and it's not supported.

**Comment by jgreat** [comment]
Thanks for checking. Can we turn this into a feature request?
