### ISSUE TITLE
Error verifying online installer due to incorrect signature and invalid commands

### ISSUE THREAD

**Issue by bradfordcp** [goharbor/harbor#11816]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Following the steps at https://goharbor.io/docs/1.10/install-config/download-installer/ a couple of errors are encountered.

1. The command to verify is using a large dash instead of double dash `gpg -v –keyserver hkps://keyserver.ubuntu.com –verify harbor-online-installer-v1.10.2.tgz.asc` vs `gpg -v --keyserver hkps://keyserver.ubuntu.com --verify harbor-online-installer-v1.10.2.tgz.asc`
2. Upon updating the command an error message is returned 
   ```
   gpg: no valid OpenPGP data found.
   gpg: the signature could not be verified.
   Please remember that the signature file (.sig or .asc)
   should be the first file given on the command line.
   ```
3. Looking at the signature file it appears the release wasn't actually signed
   ```
   [fedora@harbor ~]$ cat harbor-online-installer-v1.10.2.tgz.asc 
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: harbor-releases/release-1.10.0/harbor-online-installer-v1.10.2.tgz.asc</Details></Error>
   ```

**Steps to reproduce the problem:**
```bash
curl -L -O https://github.com/goharbor/harbor/releases/download/v1.10.2/harbor-online-installer-v1.10.2.tgz
curl -L -O https://github.com/goharbor/harbor/releases/download/v1.10.2/harbor-online-installer-v1.10.2.tgz.asc
gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 644FF454C0B4115C
gpg -v --keyserver hkps://keyserver.ubuntu.com --verify harbor-online-installer-v1.10.2.tgz.asc
```

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.10.2
- docker engine version: 19.03.8 - although it shouldn't matter given the nature of this issue
- docker-compose version: 1.25.4 - although it shouldn't matter given the nature of this issue

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by soulawaker** [comment]
It seems that the `.asc` file does not contain expected values. 

```shell
➜ cat harbor-online-installer-v1.10.2.tgz.asc
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: harbor-releases/release-1.10.0/harbor-online-installer-v1.10.2.tgz.asc</Details></Error>%
```

**Comment by bitsf** [comment]
thanks @soulawaker 
I've manually upload one.

@wy65701436 Please check it seems the build script has some problem to upload the online installer's signing file to google storage

**Comment by bitsf** [comment]
dup with https://github.com/goharbor/harbor/issues/11816
