### ISSUE TITLE
Tag rentention policy system wide.

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#11818]
Currently Tag retention policy is project wise. In our environment there are multiple projects and each project has project admin which has full access of project  so that he can edit/add/modify retention rules.

Is it possible to set retention policy system wide ( One policy for all project) which is only managed by Harbor Admin?

**Comment by xaleeks** [comment]
It will stay at the project level for the foreseeable future I'm afraid.  Here's why.

Most users are leveraging harbor projects as the tenancy boundary and require different sets of retention policies across different projects, rendering building this at the system level only to be overridden by project admins a bad investment right now.  We will come back to this when we have a better idea on unification btw project and system settings, this is a constant challenge for us.
