### ISSUE TITLE
Unable to perform API actions with curl when authorization is required.

### ISSUE THREAD

**Issue by yamlCase** [goharbor/harbor#11813]
I am unable to perform authenticated actions on the Harbor API, like create a registry endpoint using the API on version 1.10.2.  This is a fresh install of harbor-offline-installer-v1.10.2.tgz. with no configuration, using the admin account.  

I tried with the swagger API explorer first and was able to create a registry just fine.

but outside the Swagger API Explorer, on the command line the same action fails.  Here's my curl (the `Basic YWRtaW46UEBzc3cwcmQ=` base64s out to my username/password):

```
curl --request POST \
  --url https://harbor.example.com/api/registries \
  --header 'authorization: Basic YWRtaW46UEBzc3cwcmQ=' \
  --header 'content-type: application/json' \
  --cookie sid=328c04a0432549cf7b371ae2616dbf4a \
  --data '{
	"name": "docker-hub",
	"url": "https://hub.docker.com",
	"insecure": true,
	"type": "docker-hub",
	"description": "docker hub"
}'
```

And here's the error:

```
422 Unprocessed Entity

Response:
...
<br>The page you have requested is forbidden.<br>Perhaps you are here because:<br><br><ul><br>'_xsrf' argument missing from POST</ul>
...
```

Only thing missing from my curl is the `X-Xsrftoken` header, and I have no idea how to generate that. Harbor documentation has nothing about this that I can find.

Similar issue to #11617

**Comment by heww** [comment]
CSRF token required  for APIs when session is enabled.  Please remove `--cookie sid=328c04a0432549cf7b371ae2616dbf4a` in you curl command.

**Comment by yamlCase** [comment]
thank you @heww 
removing the cookie did the trick.  In my case I'm using Insomnia which keeps and uses cookies by default.

@reasonerjt For your FAQ under https://github.com/goharbor/harbor/wiki/Harbor-FAQs#api:

Q: How do I disable Xsrftoken checking during API testing?

A: Make sure your API explorer (Insomnia, postman, httpie, etc) does not send cookies with the POST request.
