### ISSUE TITLE
Auth_mode menu still disabled

### ISSUE THREAD

**Issue by hutger** [goharbor/harbor#11815]
Hi guys, 

I need to change auth_mode, but menu is inactive. I've tried to remove the users from WebUI and DB following #7992 but nothing seems to work. 

```
docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user
delete from harbor_user where user_id > 2
```
I've also restarted all components, but no luck so far. 

Any clue on how to get this fixed?

Harbor Version: 1.10.2

**Comment by hutger** [comment]
I've found the issue... actually it was my mistake when deleting the users from the DB.  Shame on me. :)

**Comment by sshankjha** [comment]
@hutger Can you tell me what your mistake was? I am still facing the issue so I probably need to do the same thing.
