### ISSUE TITLE
Replication jobs failing with repeating registry urls

### ISSUE THREAD

**Issue by rvennam-lbg** [goharbor/harbor#11825]
**Expected behavior and actual behavior:**
Replication job is configured to pull images from GCR and push them to a harbor project. This fails only when ``**`` is used on the image pattern and works when the full path is provided

**Steps to reproduce the problem:**
Adding a replication job with wildcards for a GCR replication job fails at DNS lookup due to repeating registry in the link ```https://eu.gcr.iohttps//eu.gcr.io/v2/```

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.1]
- GKE : [1.14.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

2020-05-04T13:25:04Z [ERROR] [/replication/operation/controller.go:108]: the execution 44585 failed: failed to fetch image: Get **https://eu.gcr.iohttps//eu.gcr.io/v2/_catalog?n=1000&last=mgmt-bak-tst-0d5f/platform_tools/jenkins** dial tcp: lookup eu.gcr.iohttps on 10.84.124.138:53: no such host

**Comment by bitsf** [comment]
if you are using googlegcr adapter, you should input the project name as prefix.

**Comment by bitsf** [comment]
if you are using other adapter, you should paste some snapshot to clarify how you setup the registry and the replication rule
