### ISSUE TITLE
Configure Clair's Max Connections

### ISSUE THREAD

**Issue by Salamandastron1** [goharbor/harbor#11826]
**Is your feature request related to a problem? Please describe.**
Hello all you all! Ran into needing to configure Clair's database to max connections being exceeded with a customer. Quick fix was to update the postgres.conf. Problem is now that anytime bosh kills the VM it will revert.

**Describe the solution you'd like**
Have the `postgres.conf` be configurable in the tile or from the yaml

**Describe the main design/architecture of your solution**
Add declarative syntax the the harbor helm/yaml/tile integration in order to access this feature. eg 

https://raw.githubusercontent.com/coreos/clair/master/config.yaml.sample

**Describe the development plan you've considered**
I have not considered this.

**Additional context**
https://www.gitmemory.com/issue/goharbor/harbor/10234/566938612

**Comment by xaleeks** [comment]
@stonezdj  please investigate how to safely expose these in tile.  I recall another similar issue of configuration being reverted when bosh director takes over and reboots VM.  Let's try to deliver this in the harbor tile 2.0 if possible, which is some time off and not immediately following the OSS 2.0

**Comment by wy65701436** [comment]
close it as the build-in scanner of harbor now is trivy.
