### ISSUE TITLE
registries creating via api does not take credentials.

### ISSUE THREAD

**Issue by thatsk** [goharbor/harbor#11827]
Creating harbor registry using API:-
curl -u "admin:Harbor12345" -k -X POST -H "Content-Type: application/json" "https://harbor/api/registries" -d "{ \"name\": \"harbor\", \"description\": \"Harbor\", \"type\": \"harbor\", \"url\": \"https://harbor.example\", \"credentials\": { \"type\": \"basic\", \"access_key\": \"admin\", \"access_secret\": \"Harbor12345\" }, \"insecure\": true }"

root@60d6640b67f3:~# curl -u admin:Harbor12345 -i -k -X GET "https://harbor/api/registries"
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 05 May 2020 08:52:18 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 422
Connection: keep-alive
Set-Cookie: sid=67092e8adbfd14b66fd93af76ff568e5; Path=/; HttpOnly

[
  {
    "id": 1,
    "name": "harbor",
    "description": " Harbor",
    "type": "harbor",
    "url": "https://harbor.example",
    "token_service_url": "",
    "credential": {
      "type": "",
      "access_key": "",
      "access_secret": ""
    },
    "insecure": true,
    "status": "",
    "creation_time": "2020-05-05T08:52:14.537191Z",
    "update_time": "2020-05-05T08:52:14.537194Z"
  }
]

**Comment by thatsk** [comment]
when i go via ui and edit the credentials it get worked. not sure why.

**Comment by thatsk** [comment]
after editing via ui.
curl -u admin:Harbor12345 -i -k -X GET "https://harbor/api/registries"
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 05 May 2020 08:52:49 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 437
Connection: keep-alive
Set-Cookie: sid=63c1ed501800c42977c160ddc91575f4; Path=/; HttpOnly

[
  {
    "id": 1,
    "name": "harbor",
    "description": "Harbor",
    "type": "harbor",
    "url": "https://harbor",
    "token_service_url": "",
    "credential": {
      "type": "basic",
      "access_key": "admin",
      "access_secret": "*****"
    },
    "insecure": true,
    "status": "",
    "creation_time": "2020-05-05T08:52:14.537191Z",
    "update_time": "2020-05-05T08:52:45.427028Z"
  }
]

**Comment by bitsf** [comment]
@thatsk credential not credentials
