### ISSUE TITLE
Don't roll your own CA for kubernetes

### ISSUE THREAD

**Issue by puckettgw** [goharbor/harbor#11820]
This relates specifically to the Helm chart --

It'd be great if the Helm chart didn't use 'notary' to create the SSL certificates used for the frontend and the registry (_do you have any idea how frustrating it is to have to manually trust these certs across n number of apps? doing it once is painful enough when you're at the level of abstraction present in a Kubernetes deployment_ ) or at least offered a cert-manager option that would disable the use of Notary.

It's extremely frustrating and not The Right Way (tm) to roll your own CA service and sign certificates when a reasonably well-built Kubernetes deployment will have its own CA via cert-manager.

The excuse that "you can define your own tls secret" is barely helpful.. especially considering that  Ingress resources (particularly nginx ingress resources) can be annotated to use cert-manager without the need for adding a bunch of extra crap in values.yaml or manually creating certificate resources.

I get that maybe at some point this was necessary, and indeed it may be helpful in non-Kubernetes deployments.  But rolling your own CA is almost never the most efficient way to do things, and from what I can see there's no special sauce in these certificates that would require them to be generated by a custom application.

**Comment by tmojlupo** [comment]
Is there any update on this?  We use our own ingress controller with a default wildcard certificate used for all ingress.  So, there is no ingress secret in the namespace.  Right now, I have to use `helm template` commands and then manually edit the resulting manifest to strip out all of the references to the created CA certs before applying.

**Comment by nyarly** [comment]
Pinging on this to remove stale. I'm very interested in proper TLS for Harbor especially.

**Comment by nyarly** [comment]
Any progress here?
