### ISSUE TITLE
We should not show replication log button when the status is Initialized

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11832]
When replication job is under Initialized status, the log is actually not create, user will get 404 error when click it

 
![image](https://user-images.githubusercontent.com/188115/81135760-0167e180-8f8c-11ea-897d-4a6505145bb6.png)

**Comment by AllForNothing** [comment]
UI need to write hard code to solve this, not good
@xaleeks What's your oppinion?

**Comment by reasonerjt** [comment]
Let's render the link based on the value of status.
