### ISSUE TITLE
Unique ID for Interrogation Services

### ISSUE THREAD

**Issue by gunboe** [goharbor/harbor#11839]
I have 2 Harbor Nodes (installed with local Clair) sharing only one PostgresDB and single Ceph S3 Storage to images. In front end, I have a Nginx Load Balancer This cenario give me high avalibility. My problem occur when the schedule scan start Harbors at same time, both Harbos try to complet the process. Thats beginning the problems. I dont know what server is scanning.

Maybe to adjust this issue is pick up only one "Interrogation Services" server, but both have the same Name. If Services would have a Unique ID, it is possible to solve this issue.

**Comment by steven-zou** [comment]
@gunboe
