### ISSUE TITLE
Scroll Bar on right side of page not working - 2.0.0-rc2

### ISSUE THREAD

**Issue by OliverTw1st** [goharbor/harbor#11843]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The scrollbar on the right side of the page does not work when clicking it to move up or down the page. The pages do scroll when using the mouse wheel. Tested on two different deployments of harbor and with chrome, IE, and firefox. I think that the event log overlay is inhibiting its use. 
![image](https://user-images.githubusercontent.com/6865247/81228745-3be57480-8fb4-11ea-9185-31e648658cd1.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
Deploy harbor server.
Go to a page that utilizes the scroll bar (i.e. system configuration or log files if there are some generated.)
Click and drag on the scroll bar to attempt to move it.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.0-rc2]
- docker engine version: [19.03.5]
- docker-compose version: [1.18.0]

Both harbor installs are served from behind haproxy.

**Comment by AllForNothing** [comment]
@OliverTw1st Please use mouse wheel to move the overall pane, and use the mouse click to move the datagrid.  Duplicated with ##8423

**Comment by ngharo** [comment]
@AllForNothing will you accept pull requests with the scroll bar issue fixed? If so, I may give it a shot.

It seems like a bug because the scroll bar is visible. The user experience is impacted; users expect scroll bars to always work.

**Comment by AllForNothing** [comment]
@ngharo Yes, please, and welcome!
