### ISSUE TITLE
Sign up in demo page not possible

### ISSUE THREAD

**Issue by haexhub** [goharbor/harbor#11842]
Hi,

I tried to create an account at your [demo page](https://demo.goharbor.io), but its always complaining about the name and the email field. I use normal characters as name and my regular/correct email address. But its not working.

**Comment by theJaxon** [comment]
There's no sign up option on that demo page, it only shows 'Log in' !

**Comment by haexhub** [comment]
On the demo page you can create a new account, where the error occurred. But you it seems already fixed.

**Comment by wy65701436** [comment]
hi @haexhub are you still experiencing the problem? Someone may login as admin to disable the self registrion selection.

But, the demo site will be refreshed every two days.

**Comment by haexhub** [comment]
I actually tried it write now and it seems the problem is back. If you go in your demo page to sign up a New account, the fieldvalidation for the username and email always fails and therfore you can't finish the registration.

**Comment by darrylsepeda** [comment]
I just encountered the same issue on local app:

<img width="1918" height="1107" alt="Image" src="https://github.com/user-attachments/assets/c5b3efb7-dad4-4eb1-b690-c6fbf31573ea" />

Update:
I found that when using a correct configuration, the sign-in page doesn't have register/sign-up link.
we should login with Harbor's default account, my configuration was incorrect in the port forwarding, type, and tlsEnabled.
