### ISSUE TITLE
Anonymous user in harbor - allow pulling of images in public repos

### ISSUE THREAD

**Issue by shashank-k** [goharbor/harbor#11841]
How to allow users to pull images from a public repo without creating the robot accounts. Its more of annoymous user access to public repos.

**Comment by heww** [comment]
In version 2.0, harbor support to pull images from a public repo by anonymous user.

**Comment by shashank-k** [comment]
Hi,

I have installed the latest version (v2.0) and Not able to create an anonymous account which can pull the images without username and password.

**Comment by shashank-k** [comment]
I think this feature would be necessary when we have to download public helm charts and its images to install on a airgapped system
