### ISSUE TITLE
Can't sign up for the Demo server

### ISSUE THREAD

**Issue by syrine10** [goharbor/harbor#11853]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
As a user I want to create an account to access the demo server

**Steps to reproduce the problem:**
Accessing this URL https://demo.goharbor.io/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects
Can't find the sign up action.

**Comment by shahedex** [comment]
The Sign Up options is right there under the login button. Click the **Sign up for an account** to register yourself.

![image](https://user-images.githubusercontent.com/17005411/81399176-5fdbbe00-914c-11ea-8207-9a0607f77132.png)

**Comment by bitsf** [comment]
Sometimes disk got full because too many people upload too many things. The env will auto recreate after several days.
