### ISSUE TITLE
Need a way of notify users when image replication failed. 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11859]
As the administrator, I have two harbor instances configured with replication to sync up the images, I need to know which image replication failed so that I can take actions to mitigate the issue to make sure the two harbor instances can always be synced. 

In my scenario, I just push images in the first Harbor instances, but pulling images can happen simultaneously in two harbor instances.

**Comment by steven-zou** [comment]
We have a webhook event related to replication action that can match your requirement.

![Screen Shot 2020-06-08 at 12 01 22](https://user-images.githubusercontent.com/5753287/83991642-faaffe00-a97f-11ea-8f85-cc8304acb741.png)
