### ISSUE TITLE
Unable to pull some Images

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#11852]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We have an harbor registry that has a project that mirrors gcr.
We are unable to pull some of the images from harbor, and this is the log-line:
```
May  7 16:37:18 172.18.0.1 core[1830]: 2020/05/07 14:37:18.072 #033[1;44m[D]#033[0m [server.go:2774]  |   10.88.104.15|#033[97;43m 401 #033[0m|   3.614232ms|   match|#033[97;45m HEAD    #033[0m /v2/gcr/k8s/kube-apiserver/manifests/v1.18.2   r:/v2/*
May  7 16:37:18 172.18.0.1 core[1830]: 2020-05-07T14:37:18Z [ERROR] [/core/service/token/token.go:55]: Unexpected error when creating the token, error: Unable to parse image from string: kube-apiserver
```
The Image in this Version exists and syncs fine.
Scanning also works as expected so its not an corrupted Image
![image](https://user-images.githubusercontent.com/4894735/81307984-8e409700-9081-11ea-9905-1a3a9c8d9776.png)

**Steps to reproduce the problem:**
Mirror kube-api-server or kubernetes-dashboard-amd64 and try to pull those images

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.2]
- containerd 1.3.4 for the pulling side

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MaxRink** [comment]
This seems only to happen to images with the structure Registryurl/project/image:version, if i add an identifier like registryurl/project/k8s/image:version the issue goes away

**Comment by Cellebyte** [comment]
```go
package main
import (
	"fmt"
	"strings"

)
type endpointParser struct {
	endpoint string
}
type imageParser interface {
	parse(s string) (*image, error)
}
type image struct {
	namespace string
	repo      string
	tag       string
}
func parse(s string) (*image, error) {
	repo := strings.SplitN(s, "/", 2)
	fmt.Println("Repo: ", repo)
	if len(repo) < 2 {
		return nil, fmt.Errorf("Unable to parse image from string: %s", s)
	}
	return parseImg(repo[1])
}
// build Image accepts a string like library/ubuntu:14.04 and build a image struct
func parseImg(s string) (*image, error) {
	repo := strings.SplitN(s, "/", 2)
	fmt.Println("Image: ", repo)
	if len(repo) < 2 {
		return nil, fmt.Errorf("Unable to parse image from string: %s", s)
	}
	i := strings.SplitN(repo[1], ":", 2)
	res := &image{
		namespace: repo[0],
		repo:      i[0],
	}
	if len(i) == 2 {
		res.tag = i[1]
	}
	return res, nil
}
func main() {
	fmt.Println("Hello, playground")
        // Doesn't work
	asdf, asdf2 := parse("gcr/kube-api-server:v1.14.1")
        // Works
	fmt.Println("Hello", asdf, asdf2)
        asdf, asdf2 := parse("gcr/k8s/kube-api-server:v1.14.1")
}
```

**Comment by bitsf** [comment]
Not quite sure what you mean.
  `docker pull registryip/gcr/kube-api-server:v1.14.1` fail ?
Can you show me the snapshot of replication rule that I can verify too.

**Comment by Cellebyte** [comment]
> `docker pull registryip/gcr/kube-api-server:v1.14.1` fail ?

Correct if you put in something like `docker pull registryip/library/gcr/kube-api-server:v1.14.1`
it works.

**Comment by bitsf** [comment]
how did you setup the replication rule for this kube-api-server image

**Comment by MaxRink** [comment]
![image](https://user-images.githubusercontent.com/4894735/81809151-2d054180-9521-11ea-8343-aed08bc62115.png)

**Comment by bitsf** [comment]
which registry adapter are you using?

**Comment by MaxRink** [comment]
docker-registry, but that works fine. the images are correctly registered in harbor.
Its not a replication issue, its a pull issue

**Comment by MaxRink** [comment]
The issue happens when a token should be generated:

Logs of server Pulling: 
crictl pull regsitry/gcr/kube-apiserver:v1.17.5
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "regsitry/gcr/kube-apiserver:v1.17.5": failed to resolve reference "regsitry/gcr/kube-apiserver:v1.17.5": failed to authorize: failed to fetch anonymous token: unexpected status: 500 Internal Server Error

Harbor: 

May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/middlewares/url/handler.go:40]: in url handler, path: /v2/gcr/kube-apiserver/manifests/v1.17.5
May 13 14:01:31 172.24.0.1 core[1830]: 2020/05/13 12:01:31.574 #033[1;44m[D]#033[0m [server.go:2774]  |   10.88.104.12|#033[97;43m 401 #033[0m|   3.868176ms|   match|#033[97;45m HEAD    #033[0m /v2/gcr/kube-apiserver/manifests/v1.17.5   r:/v2/*
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/token.go:42]: URL for token request: /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/creator.go:204]: scopes: [repository:gcr/kube-apiserver:pull repository:kube-apiserver:pull]
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/authutils.go:47]: scopes: [repository:gcr/kube-apiserver:pull repository:kube-apiserver:pull]
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/authutils.go:94]: user: , access: &{repository  gcr/kube-apiserver [pull]}
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/authutils.go:94]: user: , access: &{repository  kube-apiserver [pull]}
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [ERROR] [/core/service/token/token.go:55]: Unexpected error when creating the token, error: Unable to parse image from string: kube-apiserver

**Comment by bitsf** [comment]
I test with harbor 2.0 rc, and it can work
![image](https://user-images.githubusercontent.com/188115/81810529-af0f5d80-9555-11ea-87cc-28047538d7ac.png)
![image](https://user-images.githubusercontent.com/188115/81810557-bafb1f80-9555-11ea-9ae7-d1fd237b492e.png)

**Comment by MaxRink** [comment]
i guess the issue is that we use containerd, which behaves a bit different.

```
May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/token.go:42]: URL for token request: /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry
```
is the call harbor gets, i guess it missbehaves with the duplicate scope parameter und only uses the 2nd one, which it cant resolve.

Can you compare that line with your result 
 full logs, as i missed some in the last post:

```
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/middlewares/url/handler.go:40]: in url handler, path: /v2/gcr/kube-apiserver/manifests/v1.17.5
May 13 14:14:30 172.24.0.1 core[1830]: 2020/05/13 12:14:30.720 #033[1;44m[D]#033[0m [server.go:2774]  |   10.88.104.12|#033[97;43m 401 #033[0m|   2.507497ms|   match|#033[97;45m HEAD    #033[0m /v2/gcr/kube-apiserver/manifests/v1.17.5   r:/v2/*
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/service/token/token.go:42]: URL for token request: /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/service/token/creator.go:204]: scopes: [repository:gcr/kube-apiserver:pull repository:kube-apiserver:pull]
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/service/token/authutils.go:47]: scopes: [repository:gcr/kube-apiserver:pull repository:kube-apiserver:pull]
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/service/token/authutils.go:94]: user: , access: &{repository  gcr/kube-apiserver [pull]}
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [DEBUG] [/core/service/token/authutils.go:94]: user: , access: &{repository  kube-apiserver [pull]}
May 13 14:14:30 172.24.0.1 core[1830]: 2020-05-13T12:14:30Z [ERROR] [/core/service/token/token.go:55]: Unexpected error when creating the token, error: Unable to parse image from string: kube-apiserver
May 13 14:14:05 172.24.0.1 proxy[1830]: 10.88.104.12 - "HEAD /v2/gcr/kube-apiserver/manifests/v1.17.5 HTTP/1.1" 401 0 "-" "containerd/v1.3.4" 0.003 0.004 .
May 13 14:14:05 172.24.0.1 proxy[1830]: 10.88.104.12 - "GET /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry HTTP/1.1" 500 0 "-" "Go-http-client/1.1" 0.003 0.000 .
May 13 14:14:30 172.24.0.1 proxy[1830]: 10.88.104.12 - "HEAD /v2/gcr/kube-apiserver/manifests/v1.17.5 HTTP/1.1" 401 0 "-" "containerd/v1.3.4" 0.003 0.004 .
May 13 14:14:30 172.24.0.1 proxy[1830]: 10.88.104.12 - "GET /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry HTTP/1.1" 500 0 "-" "Go-http-client/1.1" 0.003 0.004 .
May 13 14:14:05 172.24.0.1 registry[1830]: time="2020-05-13T12:14:05.26889752Z" level=debug msg="authorizing request" go.version=go1.12.12 http.request.host=harbor.sce-dcn.net http.request.id=a966052b-12bf-492a-a91f-fcfb8172f75e http.request.method=HEAD http.request.remoteaddr=10.88.104.12 http.request.uri="/v2/gcr/kube-apiserver/manifests/v1.17.5" http.request.useragent="containerd/v1.3.4" vars.name="gcr/kube-apiserver" vars.reference=v1.17.5
May 13 14:14:05 172.24.0.1 registry[1830]: time="2020-05-13T12:14:05.269010107Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.12.12 http.request.host=harbor.sce-dcn.net http.request.id=a966052b-12bf-492a-a91f-fcfb8172f75e http.request.method=HEAD http.request.remoteaddr=10.88.104.12 http.request.uri="/v2/gcr/kube-apiserver/manifests/v1.17.5" http.request.useragent="containerd/v1.3.4" vars.name="gcr/kube-apiserver" vars.reference=v1.17.5
May 13 14:14:05 172.24.0.1 registry[1830]: 172.24.0.8 - - [13/May/2020:12:14:05 +0000] "HEAD /v2/gcr/kube-apiserver/manifests/v1.17.5 HTTP/1.1" 401 161 "" "containerd/v1.3.4"
May 13 14:14:30 172.24.0.1 registry[1830]: time="2020-05-13T12:14:30.719762222Z" level=debug msg="authorizing request" go.version=go1.12.12 http.request.host=harbor.sce-dcn.net http.request.id=98bf7d42-d65f-4782-9b2d-d3f47fda7781 http.request.method=HEAD http.request.remoteaddr=10.88.104.12 http.request.uri="/v2/gcr/kube-apiserver/manifests/v1.17.5" http.request.useragent="containerd/v1.3.4" vars.name="gcr/kube-apiserver" vars.reference=v1.17.5
May 13 14:14:30 172.24.0.1 registry[1830]: time="2020-05-13T12:14:30.719863981Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.12.12 http.request.host=harbor.sce-dcn.net http.request.id=98bf7d42-d65f-4782-9b2d-d3f47fda7781 http.request.method=HEAD http.request.remoteaddr=10.88.104.12 http.request.uri="/v2/gcr/kube-apiserver/manifests/v1.17.5" http.request.useragent="containerd/v1.3.4" vars.name="gcr/kube-apiserver" vars.reference=v1.17.5
May 13 14:14:30 172.24.0.1 registry[1830]: 172.24.0.8 - - [13/May/2020:12:14:30 +0000] "HEAD /v2/gcr/kube-apiserver/manifests/v1.17.5 HTTP/1.1" 401 161 "" "containerd/v1.3.4"

```

**Comment by bitsf** [comment]
I just test in harbor 1.10.2, it also works.

What you mean you use containerd?
Installed in k8s cluster ?

**Comment by bitsf** [comment]
I can't run crictl successfully, how did you install it

![image](https://user-images.githubusercontent.com/188115/81813482-15967a80-955a-11ea-98bf-e1191330cd5d.png)

**Comment by MaxRink** [comment]
We use the bundeled version with containerd: https://github.com/containerd/cri/blob/master/docs/installation.md
I guess you use the wrong endpoint, as docker configures another socket than plain containerd would (although its also containerd under the hood)
And we use one feature of containerd, which is registry mirrors
We redirect some registries to our private harbor, for use in airgapped envs

**Comment by bitsf** [comment]
Just from the log, I think you are right, the crictl client pass a duplicate scope param, which does not has a namespace
And harbor doesn't support repo without namespace, because it need to map it to project, and also not using default "library" namespace.
so I think you have to run cmd like `crictl pull registry/gcr/xxxx/kube-apiserver` to workaround.
But I'm not sure if this work if you set the project private, as the token for xxxx/kube-apiserver is not valid.
So you may need run  `crictl pull registry/gcr/gcr/kube-apiserver` to workaround.

**Comment by MaxRink** [comment]
the question is, can we change the behaviour of harbor in that regard? with a plain docker-registry this works, so i suppose that only checks the first scope param, thus never gets to issue an error.
And harbor should be able to create a token for the first scope param, so the error handeling for the 2nd param could be different, so that it doesnt just end the execution and proceeds with the first, valid, run.

**Comment by bitsf** [comment]
we can only deal with one scope, but not sure whether the first scope or the last scope would be better, as other clients may have different behavior

**Comment by reasonerjt** [comment]
@bitsf I don't think we have time for this in 1.10.3

**Comment by reasonerjt** [comment]
It seems it's the `crictl` sending wrong scope:
`May 13 14:01:31 172.24.0.1 core[1830]: 2020-05-13T12:01:31Z [DEBUG] [/core/service/token/token.go:42]: URL for token request: /service/token?scope=repository%3Agcr%2Fkube-apiserver%3Apull&scope=repository%3Akube-apiserver%3Apull&service=harbor-registry`

It shoud NOT send "reopsitory:kube-apiserver" in the url and it's not a repository...

**Comment by bitsf** [comment]
This issue is tracking by containerd, close first
