### ISSUE TITLE
Error 500 while retrieving existing vulnerability scan result after successful PVC expansion of Postgres DB

### ISSUE THREAD

**Issue by patelvi1** [goharbor/harbor#11866]
K8S PVC of PostgreSQL was 98% full. So, after expansion of PVC ([link- allowVolumeExpansion](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims)), I have been getting 500 error code while scanning(vulnerability) some of existing images stored in harbor. Most of the images have scanning results available and users are able to scan them again as well, but very few of images are unable to finish scanning nor able to pull previous scanning results.
Has anyone experienced similar issue?
Thanks

```
2020-05-06T16:17:40Z [ERROR] [/jobservice/job/impl/scan/clair_job.go:109]: Failed to get result from Clair, error: Unexpected status code: 500, text: {"Error":{"Message":"database: an error occured when querying the backend"}}
```
`Version details`

<img src="https://user-images.githubusercontent.com/64622312/81460671-d55b8480-9174-11ea-93e1-3bcc662385f5.png" width="400" height="500" />

**Comment by bitsf** [comment]
I think you can also check clair.log. Harbor just call clair Api to get info, and this error message should also come from clair.

**Comment by patelvi1** [comment]
Unable to find one of the layer returns 500 in clair log 

```
{"Description":"searchFeatureVersionVulnerability.Rows()","Event":"Handled Database Error","Level":"error","Location":"pgsql.go:284","Time":"2020-05-13 15:52:56.768482","error":"pq: index \"vulnerability_pkey\" contains unexpected zero page at block 20874"}

{"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2020-05-13 15:52:56.769866","elapsed time":10786272711,"method":"GET","remote addr":"10.42.XX.XX:36190","request uri":"/v1/layers/f2cc5b32375eabbXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1?features\u0026vulnerabilities","status":"500"}
```

**Comment by heww** [comment]
I thinks your postgres db may broken in some tables. Please get more info in harbor-db container.

And according to https://community.pivotal.io/s/article/Querying-a-Table-Fails-with-the-Error-index-xx-contains-unexpected-zero-page-at-block-xxx?language=en_US you can reindex the index.

Note: it will be best practice to backup your database or pv before reindex. 
```sql
reindex index vulnerability_pkey
```

**Comment by patelvi1** [comment]
Pgsql is also suggesting to reindex the db

Let me try this and update it here. 
It is live application 
```
ERROR:  index "vulnerability_pkey" contains unexpected zero page at block 20878

HINT:  Please REINDEX it.

CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."vulnerability" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

STATEMENT:

			INSERT INTO Vulnerability_Affects_FeatureVersion(vulnerability_id, featureversion_id, fixedin_id)

			VALUES($1, $2, $3)

ERROR:  index "vulnerability_pkey" contains unexpected zero page at block 20878

HINT:  Please REINDEX it.

CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."vulnerability" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

STATEMENT:

			INSERT INTO Vulnerability_Affects_FeatureVersion(vulnerability_id, featureversion_id, fixedin_id)

			VALUES($1, $2, $3)

ERROR:  index "vulnerability_pkey" contains unexpected zero page at block 20874

HINT:  Please REINDEX it.

STATEMENT:

				SELECT vafv.featureversion_id, v.id, v.name, v.description, v.link, v.severity, v.metadata,

					vn.name, vn.version_format, vfif.version

				FROM Vulnerability_Affects_FeatureVersion vafv, Vulnerability v,

						 Namespace vn, Vulnerability_FixedIn_Feature vfif

				WHERE vafv.featureversion_id = ANY($1::integer[])

							AND vfif.vulnerability_id = v.id

							AND vafv.fixedin_id = vfif.id

							AND v.namespace_id = vn.id

							AND v.deleted_at IS NULL
```

**Comment by patelvi1** [comment]
Is there any official guide to take backup?
I only found one command taking backup of Postgres database. I can see more database under postgres pod.

**Comment by patelvi1** [comment]
https://github.com/goharbor/harbor/issues/10729#issuecomment-587268867

If this is recommended way to take backup, I would use it. 
May need to tweak for Kubernetes pod.

**Comment by patelvi1** [comment]
I have tried to initiate the reindexing. 

- is there any way to see the progress?
- Is there any way to find size of index?
It seems taking forever. Can those indexes be deleted? what will be impact to the data?
