### ISSUE TITLE
Task: proxy cache user story - Image pull scenarios

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11868]
> This issue is a sub-task of the Proxy Cache epic (#11658)

【P0】As an admin, I can make sure that when pulling an image from a proxy project, proxy project will check its cached copy against the remote registry to make sure it has the latest. If not, it will update itself with the latest ver before serving the pull request. A couple of scenarios to consider

    Image requested is not in cache and is found in upstream registry, so cache will pull from upstream, store, before serve to client
    Image requested is in cache, checks upstream and finds a newer copy, grabs newer copy, caches it and serve to client
    Image requested is in cache, checks upstream and finds the same copy, serves the cached copy to client
    Image requested is in cache, checks upstream and image has been removed, disregard pull request and return image not found
    Image requested is in cache, checks upstream and finds the registry is down, serves the cached copy to client

**Comment by stonezdj** [comment]
Closed with PR #12274
