### ISSUE TITLE
Task: proxy cache user story - Cache creation in Harbor

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11864]
> This issue is a sub-task of the Proxy Cache epic (#11658)

【P0】As an admin, I can set up a proxy project (parallel to Harbor project) acting as a pull-through cache for a repository on a remote registry otherwise unavailable to me, by specifying the remote endpoint (HTTP or HTTPS) of the repository, credentials of the remote repository, and choosing a name / alias for the proxy project. I can create proxy projects for multiple target registries per single Harbor instance using this approach.  A proxy project and a regular project cannot share the same name so Harbor can correctly resolve any docker pull request

Steps
- Create proxy project for a remote repository
- Use ‘test’ to test connectivity and display contents of remote registry
- Edit or remove this proxy at any time

**Comment by stonezdj** [comment]
The task include the API and the permission check to proxy project.

**Comment by ywk253100** [comment]
Done
