### ISSUE TITLE
Task: proxy cache user story - Cache Retention policies

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11869]
> This issue is a sub-task of the Proxy Cache epic (#11658)

【P0】As an admin, I can specify how long an artifact lives in cache before it is removed. Can configure this during creation or edit at a later time. Couple of ways to do this
Steps
Configure ‘retention time’ during proxy project creation step, this is how long artifacts will live on cache before it is removed
Or, configure retain most recently pulled x artifacts
Or, select ‘-1’ for infinite retention
edit this value at any later time

**Comment by reasonerjt** [comment]
For 2.1.0 this will be handled via tag retention policy.
