### ISSUE TITLE
ui crashes often and log me out

### ISSUE THREAD

**Issue by tirelibirefe** [goharbor/harbor#11874]
I've explained my system here > #11848 

ui crashes often and log me out. I don't have any idea what causes it but I faced with the same problem before in different installations.

![image](https://user-images.githubusercontent.com/45227339/81491960-71cc7680-929c-11ea-9781-bdc8345b3317.png)

**Comment by AllForNothing** [comment]
@tirelibirefe Something wrong with the requests to the back-end. Please open the browser console to check.
![image](https://user-images.githubusercontent.com/30999793/81516277-ee795680-9369-11ea-813d-10c5dd9a3f18.png)

**Comment by tirelibirefe** [comment]
what screen is it you pasted? 
I check but check what?

**Comment by AllForNothing** [comment]
@tirelibirefe It's browser develop tool console( https://balsamiq.com/support/faqs/browserconsole/) which you can find out which requests don't work

**Comment by bitsf** [comment]
@tirelibirefe also try clean browser cache. backend error should not report such confuse error message on UI

**Comment by tirelibirefe** [comment]
> @tirelibirefe also try clean browser cache. backend error should not report such confuse error message on UI

No, not browser issue.

**Comment by bitsf** [comment]
maybe harbor-core crashed and restart

**Comment by tirelibirefe** [comment]
@bitsf I don't think my case is related with just restart, harbor crashes all the time and I have to re-login all the time. Currently I couldn't have determined what causes to crash yet.

**Comment by bitsf** [comment]
you can upload logs in /var/log/harbor

**Comment by tirelibirefe** [comment]
new releases of Harbor and helm chart doesn't has the same problem.
