### ISSUE TITLE
Add an expiration time of the uploaded blob size cache

### ISSUE THREAD

**Issue by qinshaoxuan** [goharbor/harbor#11873]
**Is your feature request related to a problem? Please describe.**
I found that Harbor cleaned the uploaded blob size cache in redis only when run GC. See #9151
But Harbor will be placed in readonly mode when run GC. In production environment it's unacceptable.
So there is no chance to clean the uploaded blob size cache. As time goes by, the cache will be too large.

**Describe the solution you'd like**
Add an expiration time of the uploaded blob size cache

**Describe the main design/architecture of your solution**
The uploaded blob size cache is only used for the image upload process. After image uploaded, it's useless.
So maybe we can add an expiration time.

**Describe the development plan you've considered**
If it's ok, I can create a PR recently.

**Comment by bitsf** [comment]
We will introduce non-blocking GC feature in harbor 2.1.

**Comment by bitsf** [comment]
And I'm quite surprised that why you think such blob size cache would be too large, it's just some metadata, it's quite small compared to the blob data

**Comment by qinshaoxuan** [comment]
@bitsf Thanks for your reply.

In our production environment, about 100,000 new blob size cache, which using about 20MB redis memory, will be created in a month, And this number is growing. Redis memory is more expensive than object storage space in the cloud.

Maybe we don’t need to wait for the GC to clear this cache. Adding the expiration time or clearing this cache at the end of the upload is more reasonable

**Comment by bitsf** [comment]
I remember @wy65701436 add this redis cache for docker blob is in order to workaround an issue in docker distribution, not only for upload process.

**Comment by bitsf** [comment]
issue seems be https://github.com/docker/distribution/issues/2094

**Comment by wy65701436** [comment]
hi @heww , I recall we do have a expiration for the blob size in the redis, right?

**Comment by heww** [comment]
Hi, @qinshaoxuan  we will add an expiration time (24 hours) of the uploaded blob size cache in v2.1 and you may need to set the harbor to readonly mode to clean the old blob size data in the cache manually.
