### ISSUE TITLE
Task: proxy cache user story - cache operations logs

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11871]
> This issue is a sub-task of the Proxy Cache epic (#11658)

【P1】As a system admin, I need to log all pulls through the proxy cache for all projects so each project admin can access this log. Since harbor is acting as middleman for clients pulling from a remote registry to which they supposedly have no access, I need to store detailed logs of all transactions on server side. Logs for each cache should include #of pulls from upstream registry as well as #of pulls to from clients

**Comment by stonezdj** [comment]
Because the pull and push is done by core, these operation log in the audit log, it seems no change required.
<img width="997" alt="Screen Shot 2020-06-17 at 12 30 51 PM" src="https://user-images.githubusercontent.com/2696760/84855376-93d4c800-b096-11ea-9fbc-b7b0769f5cc9.png">

**Comment by stonezdj** [comment]
Because the proxy cache project works like a normal project, there is no need to change anything.
