### ISSUE TITLE
Task: proxy cache user story - silent sync with upstream

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11870]
> This issue is a sub-task of the Proxy Cache epic (#11658)

【P1】As a stretch goal, I can also set a flag that allows the proxy cache to pulse the upstream and update itself with the latest version continuously so as to minimize likelihood of syncing during an actual pull from proxy. This is when bandwidth is a luxury

**Comment by stonezdj** [comment]
Comfirmed with @xaleeks , current the proxy cache always check the latest version of manifest and send it to the client on demand, so there is no need to sync the content periodically.
