### ISSUE TITLE
Unable to delete replication job

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#11894]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We have an replication job setup, that i want to delete.
its setup with a cron schedule
![image](https://user-images.githubusercontent.com/4894735/81672453-733ba180-944a-11ea-8944-bf5d757f4178.png)

If i try that in the UI i get an Error 500
![image](https://user-images.githubusercontent.com/4894735/81672306-425b6c80-944a-11ea-9919-30497fb3862c.png)
If i look at the jobservce log i find this:
```
May 12 12:13:59 172.18.0.1 jobservice[1830]: 2020-05-12T10:13:59Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/b21678c7545519d1bf27d493' error: 500 {"code":10006,"message":"stop job failed with error","details":"mismatch job status for stopping job: b21678c7545519d1bf27d493, job status Error is behind Running"}

```

I can neitehr disable, alter or delete that job.

**Steps to reproduce the problem:**
Delete a jobservice that was running on a cron schedule
**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.2

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory. Will provide as needed
- **Log files:** You can get them by package the `/var/log/harbor/` .
Will provide as needed

**Comment by steven-zou** [comment]
@MaxRink 

We'll take a look at it. It seems a bug of replication deletion. We'll check more details later and if it is, we'll try to introduce the fix into an upcoming fix patch.

For a workaround approach, if it's urgent to resolve, you can try to delete it via the database directly.

**Comment by dajose** [comment]
I can confirm this is still there for harbor 2.0
