### ISSUE TITLE
Many broken image links in docs

### ISSUE THREAD

**Issue by supereagle** [goharbor/harbor#11895]
We are reorganizing the docs for v2.0, but many image links are not updated at the same time.
Therefore, many images can not be shown in the docs. For example, [administration/configure-authentication/ldap-auth.md](https://github.com/goharbor/harbor/blob/master/docs/administration/configure-authentication/ldap-auth.md)

**Comment by xaleeks** [comment]
We took care of a lot of these, please let me know if you find anymore broken links

**Comment by bitsf** [comment]
Please also notice, the images in doc currently using "../../..", which suppose to be correct, because it will show correct on harbor document website https://goharbor.io/docs/2.0.0/

**Comment by supereagle** [comment]
It is ok on website, but has problems in the markdown docs of this repo.
I think it should be ok for both website and these docs of this repo.

![image](https://user-images.githubusercontent.com/3390333/81804982-a8301d00-954c-11ea-89ae-c39df905eec9.png)

**Comment by bitsf** [comment]
@xaleeks is discussing with doc maintainer whether this can be fixed
