### ISSUE TITLE
Helm unable to add repo due to index.yaml parsing issue

### ISSUE THREAD

**Issue by mattfarina** [goharbor/harbor#11903]
**Expected behavior and actual behavior:**
The issue has to do with chart `appVersion` set to a string that's a valid number. For example, 1234e2. A version like this needs to be wrapped in quotes in the `Chart.yaml` file so that it is properly treated as a string and not a number.

The issue was fixed in Chartmuseum 0.10.0 but Harbor is using 0.9.0.

The `appVersion` should be treated properly and quoted so that there are no issues with the versions in use.

**Steps to reproduce the problem:**
Create a chart that has an app version with a number using the e eponent. Push the chart to chartmuseum. Try to add the repo to Helm.

You'll get an error along the lines of:
```
Error: looks like "https://xx.xx.xx.xx/chartrepo/abc" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

**Comment by mattfarina** [comment]
Note, this should still be true on the latest harbor.

**Comment by ninjadq** [comment]
fixed in 
1.10.x: https://github.com/goharbor/harbor/pull/12069
2.0.x: https://github.com/goharbor/harbor/pull/12073
master: https://github.com/goharbor/harbor/pull/12071
