### ISSUE TITLE
Wrong download chart name

### ISSUE THREAD

**Issue by CorentinHache** [goharbor/harbor#11901]
For some projects, when I try to download a specific version of a HELM chart, the downloaded filename is not correct :
![image](https://user-images.githubusercontent.com/54442534/81715179-325a8180-9478-11ea-9dab-c9defcbd3b2b.png)

Expected behaviour : 
The chart filename is always composed of the project name and the chart version
![image](https://user-images.githubusercontent.com/54442534/81715281-528a4080-9478-11ea-8a2f-2e7c5d338fdd.png)
 

**Steps to reproduce the problem:**
This issue occurs only on some specific projects : 
- Click on a project
- Open the "HELM charts" sheet
- Select a chart name and click on download -> The downloaded chart file name is correct.
- Click on the chart name 
- Select a specific version and click on download -> The downloaded chart file name is not correct.

**Versions:**
- harbor version: Version v1.9.2-17aba8be

**Comment by bitsf** [comment]
Did you push the chart by yourself, or replication from somewhere, that we can verify this.

**Comment by CorentinHache** [comment]
The charts are pushed using a same CURL command for both projects (the ones with and without the issue)

curl --user $HUB_LOGIN:$HUB_PASSWORD -X POST -F "repo=$HUB_PROJECT" -F "chart=@$HELM_CHART_DIR/$HELM_CHART_NAME" https://$HUB_ADDR/api/chartrepo/$HUB_PROJECT/charts

**Comment by chache35** [comment]
Look like a real issue. Should not be at a "stale" state.

**Comment by gph35** [comment]
@ninjadq or @bitsf any news on this issue ?
For the same chart, we have 2 different behaviours : 
- if we download chart from "Helm Charts" main page : it's ok the name is correct
- if we download a specific version : the name is wrong.

Besides it's not "stale" issue. 

Poke @chache35.

**Comment by AllForNothing** [comment]
Closing as it has been fixed by #15679
