### ISSUE TITLE
Batch remove the images 

### ISSUE THREAD

**Issue by qqian1991** [goharbor/harbor#1192]
Through the UI:
* I can only delete the image one by one 
* everytime when I delete it, the page will do not refresh automatically
* no way to batch remove multiple images only if you delete the project

**Comment by reasonerjt** [comment]
We'll see the refresh issue.
Currently we don't plan to support deleting multiple images on UI.

**Comment by moooofly** [comment]
just need some checkboxes.

**Comment by qqian1991** [comment]
@moooofly thanks for the response

**Comment by moooofly** [comment]
@bibotai have a try with [harbor-go-client](https://github.com/moooofly/harbor-go-client)

**Comment by reasonerjt** [comment]
Batch remove from UI is supported, additionally as pointed out in previous comment, you can use the client developed by community user to to batch deletion.
