### ISSUE TITLE
1.9.1 Failed to start GC: 500

### ISSUE THREAD

**Issue by odeng888** [goharbor/harbor#11929]
Failed to start GC
1、Enter pod
#kubectl exec -it harbor-release-harbor-registry-695d76dd76-7qt6l --container registryctl -- /bin/bash

2、Run command:
#registry garbage-collect /etc/registry/config.yml
DEBU[0084] s3aws.Walk("/docker/registry/v2/repositories")  go.version=go1.11.13 instance.id=53970271-715b-49cc-b0a8-088e3e96ef4b service=registry trace.duration=1m24.799674376s trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk" trace.id=b2177bae-06d4-4834-9e51-deaf634e8964 trace.line=232

**get error:**
failed to garbage collect: failed to mark: s3aws: Path not found: /docker/registry/v2/repositories

Harbor v1.9.1
Harbor backend is Ceph s3 api

docker version
Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

**Comment by wy65701436** [comment]
dup with https://github.com/goharbor/harbor/issues/11067

**Comment by odeng888** [comment]
Different error prompts！！

**Comment by odeng888** [comment]
upgrade v1.9.1 to v1.10.2
Same problem!!
....
.....
ueh/wxapp-bidhelper-second-service: marking blob sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742
ueh/wxapp-bidhelper-second-service: marking blob sha256:dbdc36973392a980d56b8fab63383ae44582f6502001d8bbdd543aa3bf1d746e
ueh/wxapp-bidhelper-second-service: marking blob sha256:f59d6d019dd5b8398eb8d794e3fafe31f9411cc99a71dabfa587bf732b4a7385
ueh/wxapp-bidhelper-second-service: marking blob sha256:5fee445fce940c37221a2a1de8588cda557eb4cbc3f7583931e384b137762539
ueh/wxapp-bidhelper-second-service: marking blob sha256:d270185e6f4dcd4cf5d00aec5a2b5f3888c1757ca73728f988198afc8303e3cc
ueh/wxapp-bidhelper-second-service: marking blob sha256:0ca0b0a3fc43fc2508d780f16173002056aabffcbeed244b5128f0653ff5756a
ueh/wxapp-bidhelper-second-service: marking blob sha256:15d2a93057363514e9a69fae945edb65d42513c80346c2159e21fef91e30d953
ueh/wxapp-bidhelper-second-service: marking blob sha256:1ed59a2e55d26765e5369227e62e93cffd9cda339df4605a94423e663d4db327
ueh/wxapp-bidhelper-second-service: marking blob sha256:22a2a70efe6190e556fe127c2b9164f3c447b3ddf02648c59457503622687d6a
failed to garbage collect: failed to mark: s3aws: Path not found: /docker/registry/v2/repositoriesharbor [ / ]$

**Comment by wy65701436** [comment]
thanks @odeng888 , can we clost it and use th original issue to track the problem? https://github.com/goharbor/harbor/issues/11067

**Comment by odeng888** [comment]
Unfortunately, it seems that the problem error message is not the same！

What is the reason for this problem?

When will it be solved？

thanks!

**Comment by bitsf** [comment]
Do you have such folder "/docker/registry/v2/repositories" on aws?
How is it work from harbor UI?

**Comment by odeng888** [comment]
The backend server is ceph by s3 api access.
I have two folder:
/docker/registry/v2/blobs/
/docker/registry/v2/repositories/

@bitsf

**Comment by bitsf** [comment]
How about from harbor UI, is it work well?

**Comment by odeng888** [comment]
from harbor UI

**get error:**
2020-05-19T09:25:42Z [INFO] [/jobservice/job/impl/gc/job.go:87]: start to run gc in job.
2020-05-19T09:27:41Z [ERROR] [/jobservice/job/impl/gc/job.go:90]: failed to get gc result: Failed to start GC: 500

@bitsf

**Comment by odeng888** [comment]
harbor [ / ]$ cat /etc/registry/config.yml 
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  s3:
    region: default
    bucket: harbor
    regionendpoint: http://192.168.1.50:7480
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: false
redis:
  addr: "harbor-release-harbor-redis:6379"
  db: 2
http:
  relativeurls: false
  addr: :5000
  # set via environment variable
  # secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: "http://192.168.1.50:32614/service/token"
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
validation:
  disabled: true
notifications:
  endpoints:
    - name: harbor
      disabled: false
      url: http://harbor-release-harbor-core/service/notifications
      timeout: 3000ms
      threshold: 5
      backoff: 1s
      ignoredmediatypes:
        - application/vnd.docker.image.rootfs.diff.tar.gzip
        - application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
        - application/vnd.oci.image.layer.v1.tar
        - application/vnd.oci.image.layer.v1.tar+gzip
        - application/vnd.oci.image.layer.v1.tar+zstd
        - application/vnd.oci.image.layer.nondistributable.v1.tar
        - application/vnd.oci.image.layer.nondistributable.v1.tar+gzip
        - application/vnd.oci.image.layer.nondistributable.v1.tar+zstd
        - application/octet-stream

In the S3 configuration section,I found no accesskey\secretkey parameter.
@bitsf

**Comment by odeng888** [comment]
#cat /etc/registry/config.yml

In the S3 configuration section, I found that there is no accesskey \ secretkey parameter.

**Comment by wy65701436** [comment]
@odeng888,  you can refer to https://github.com/docker/distribution/issues/3200#issuecomment-674353444

**Comment by zyitingftnt** [comment]
i have exactly the same issue on Harbor 1.10.0 with Docker version 20.10.5, build 55c4c88, the log message from harbor does not much help either....

**Comment by odeng888** [comment]
ceph storage is not exist folder /docker/registry/v2/repositories,it's only prefix,so upload any file to /docker/registry/v2/repositories  can resolved it!
example: upload file to /docker/registry/v2/repositories/empty.txt
next to run gc ....Done!

**Comment by wy65701436** [comment]
link to the upstream: https://github.com/distribution/distribution/issues/3200
