### ISSUE TITLE
Cross-Posting: Requesting update of helm chart to 2.0

### ISSUE THREAD

**Issue by tvvignesh** [goharbor/harbor#11925]
Hi. Since this is the main repo for harbor, cross posting here:

Have filed an issue where the helm chart would need to be updated to 2.0:
https://github.com/goharbor/harbor-helm/issues/584

Thanks.

**Comment by horihel** [comment]
The documentation of harbor 2.0.0 mentions installing with helm, but following that documentation actually installs 1.10.2.
So it might be worth reopening this issue, as the docs in this repo are actually referring to the wrong (yet non-existing) chart?

**Comment by tvvignesh** [comment]
@horihel Yup. Have opened the issue here: https://github.com/goharbor/harbor-helm/issues/584
