### ISSUE TITLE
Limit Archs synced with replication in harbor 2.x

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#11937]
**Is your feature request related to a problem? Please describe.**
Harbor 2.0 now supports OCI-Images which brings some new issues to the table.
When im replicating images from docker hub for example, it also fetches windows-container which i dont need for my environment.
I havent found a way to limit the architectures that get replicated
**Describe the solution you'd like**
Add an option to replications to select what architectures you want to replicate

**Comment by reasonerjt** [comment]
Thanks for raising this issue.
Currently, there's no way to do that.  The design is to treat the top level artifact, in your the case the manifest list, as the unit of replication, I don't think we want to edit the manifest list during replication.

**Comment by bitsf** [comment]
@xaleeks maybe we can add some architecture filters to help save disk space. But there's a challenge that how to deal with the top level artifact manifest, rewrite manifest or just ignore the lack of some child artifacts.

**Comment by steven-zou** [comment]
I think it can be:

- only replicate the specified arch artifacts (as single images) and no manifest anymore
- replicate the images with the specified arch and re-create a new manifest list (user should aware of this, it's not the original list anymore)

@xaleeks

**Comment by xaleeks** [comment]
Replicating everything in the manifest list is the right behavior.  It's better to replicate than to not replicate for users that actually need them.  For pulling, should only pull the version matching the host but replication is different, replication represents transferring from one site to another, so the artifact should be preserved in full.  Especially since lots of users are leveraging replication as substitute for instance to instance synchronization.  I'm marking it won't fix for now

**Comment by YAMLcase** [comment]
I'd like to throw my 2 cents in here:
There needs to be some way to rebuild the manifest list in the case that *some* images fail vulnerability check (or can't be scanned in the case of windows on Trivvy).  We want to bring the good images in and leave the bad and unknown ones out.

I know there's the project setting "don't allow pull of vulnerable images", but in the case of a scan error or no scan at all (again, Windows images with Trivy) the image will be presented as "no vulnerability found" thus allowing a pull.
