### ISSUE TITLE
Can not pull image from k8s.gcr.io when registry is docker-registry and rule contains brace

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#11939]
Version: harbor 2.0
OS: Ubuntu 1804

When replicating images from `k8s.gcr.io` through endpoint `docker-registry` and replications rule contain brace parenthesis. 
like this `kube-{apiserver,controller-manager,proxy,scheduler}`
The replication job will hang forever

**Comment by bitsf** [comment]
When trigger replication, UI will get 500 error
![image](https://user-images.githubusercontent.com/188115/82007176-2e0eae00-969c-11ea-9c32-ad57850eff4e.png)

Backend harbor-core container is actually crashed
![image](https://user-images.githubusercontent.com/188115/82007309-7b8b1b00-969c-11ea-80f6-d3d92225062c.png)

**Comment by bitsf** [comment]
authorizer is nil
![image](https://user-images.githubusercontent.com/188115/82008469-619f0780-969f-11ea-9a5e-4133834fe2fa.png)

This issue maybe not only impact the docker-registry adapter when not setting credentials, but also some other scenario.
#11874 maybe also relative with this.
