### ISSUE TITLE
Why the registry auth changes between version 1 and 2?

### ISSUE THREAD

**Issue by angelbarrera92** [goharbor/harbor#11936]
Hi team!

I am trying to use (almost) the same configuration i already have in Harbor 1 but with the new version (2.0.0).

And I have some issues while trying to connect to the registry.
Seems to be related with: 

https://github.com/goharbor/harbor/blob/v1.10.2/make/photon/prepare/templates/registry/config.yml.jinja

and 

https://github.com/goharbor/harbor/blob/v2.0.0/make/photon/prepare/templates/registry/config.yml.jinja

In v1.10.2 the registry auth configuration was based in tokens issued by `core` while in v2 is hardcoded to be httpasswd....

What is the reason? I can not find any docs around this topic in the changelog/docs site

Thanks!

**Comment by jkjell** [comment]
This looks like it's intentional to me based on the comments in this commit: https://github.com/goharbor/harbor/commit/2064a1cd6d9b97fd2c7445885cdc4eb461455af9

**Comment by angelbarrera92** [comment]
> This looks like it's intentional to me based on the comments in this commit: [2064a1c](https://github.com/goharbor/harbor/commit/2064a1cd6d9b97fd2c7445885cdc4eb461455af9)

Hmm yeah... looks intentional, but what was the reason? just curiosity.

**Comment by reasonerjt** [comment]
It's part of the effort to let Harbor core control the auth scheme and treat distribution as storage
