### ISSUE TITLE
CSRF token errors with OIDC auth mode

### ISSUE THREAD

**Issue by rofafor** [goharbor/harbor#11938]
**Expected behavior and actual behavior:**
CSRF token errors after login until web browser has reloaded the Harbor UI. One need to reload the page right after the OIDC login in order to get any POST request working. Otherwise any request will provide 403 Forbidden response.

It seems that that `X-Harbor-CSRF-Token` header is missing from requests without reloading.

Tested with Firefox 76.0.1 with and without privacy mode. Chrome 81.0.4044.138 seems to be working.

**Steps to reproduce the problem:**

0. Use Firefox 76.0
1. Delete all cookies (optional)
2. Login via OIDC provider (using Dex)
3. Create a new project, add project name (anything goes), press OK and `CSRF token invalid` error occurs
4. Press Cancel
5. Reload the browser (e.g. CMD-R in Firefox@MacOS)
6. Create a new project, add project name (anything goes), press OK and `Created project successfully.` message is shown

**Versions:**
- harbor version: 2.0.0
- docker engine version: 18.09.6
- docker-compose version: 1.24.0-rc3, build 42894249

**Additional context:**
- **Log files:**

`proxy.log`:
```
proxy[26877]: x.x.x.x - "POST /api/v2.0/projects HTTP/1.1" 403 65 "https://x.x.x/harbor/projects" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0" 0.000 0.000 .
```
`core.log` contains these kind of errors:
```
[WARNING] [/server/middleware/security/idtoken.go:45][requestID="00000000-e3b1-4b8d-af22-2ed299139111"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts
````

**Comment by reasonerjt** [comment]
Have you been  using the FF browser with older version of Harbor?

**Comment by rofafor** [comment]
Yes. This is a regression introduced in 2.0.0 (tested rc2, rc3 and final). My earlier 1.10.2 installation didn't had this annoyance.

**Comment by rofafor** [comment]
Just to be sure, I installed 1.10.2 from scratch with empty data (as it wouldn't start with 2.0.0 schema) and Firefox 76 worked nicely. The 2.0.0-rc1 seems to be the first broken version. I even reinstalled 2.0.0 final from scratch with empty data as well and got CSRF error already in OIDC onboarding.

**Comment by reasonerjt** [comment]
@rofafor this is possible because the CSRF mechanism has changed completely in 2.x

@AllForNothing @jwangyangls could you check with FF?

**Comment by reasonerjt** [comment]
This is reproduced in FF browser, likely due to the *samesite* setting in the cookie, more debug is ongoing...

**Comment by reasonerjt** [comment]
Hi @rofafor 
After upgrading FF to 77.0.1 the problem is gone.

I guess FF made update to handle the cookies correctly.

Please double check.

**Comment by rofafor** [comment]
Yes! Firefox 77.0.1 seems to be working nicely. This issue can be closed on my behalf.
