### ISSUE TITLE
Add a default value for nginx

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#11940]
As mentioned in issue: https://github.com/goharbor/harbor/issues/7440
It is better to add two default values to solve the timeout issue.
proxy_send_timeout
proxy_read_timeout in nginx.conf

```
location /v2/ 
{
proxy_pass http://ui/registryproxy/v2/;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_set_header X-Forwarded-Proto $scheme;      
proxy_buffering off;     
proxy_request_buffering off;

proxy_send_timeout 900;
proxy_read_timeout 900;
}
```

**Comment by reasonerjt** [comment]
Please make sure this is also incorporated in the helm chart.

**Comment by ninjadq** [comment]
fixed in 
1.10: https://github.com/goharbor/harbor/pull/12068
master: https://github.com/goharbor/harbor/pull/12072
