### ISSUE TITLE
Conformance test issue -- DELETE request to manifest tag should return 202, unless tag deletion is disallowed (400) 

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11949]
```
~~~ REQUEST ~~~
DELETE  /v2/conformance/testrepo/manifests/tagtest0  HTTP/1.1
HOST   : 10.193.21.1
HEADERS:
	Authorization: Bearer *****
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
RECEIVED AT  : 2020-05-15T06:41:41.902342671Z
TIME DURATION: 4.03836ms
HEADERS      :
	Connection: keep-alive
	Content-Length: 82
	Content-Type: application/json; charset=utf-8
	Date: Fri, 15 May 2020 06:41:41 GMT
	Server: nginx
	Set-Cookie: sid=07ba2ce0521fa22a855db8c37275b6c0; Path=/; HttpOnly
	X-Request-Id: ede705e6-c8c8-42c3-9a0a-1fe38d4afeef
BODY         :
{
   "errors": [
      {
         "code": "DIGEST_INVALID",
         "message": "invalid checksum digest format"
      }
   ]
}


```

Expected
    <string>: DIGEST_INVALID
to equal
    <string>: UNSUPPORTED

**Comment by reasonerjt** [comment]
Hmm, this one is fixable on our side but debatable...

**Comment by wy65701436** [comment]
it's not easy to fix it on our side, the root cause is the validate func of digest struct. https://github.com/opencontainers/go-digest/blob/master/digest.go#L103

For the kind of a string without the algorithm, it always returns an ErrDigestInvalidFormat, we cannot force to rewrite it with ErrDigestUnsupported as in some cases we need the ErrDigestInvalidFormat.

If we want to fix it, we should overwrite the validate func of the digest. But it's not a reasonable way compared with to discuss with OCI team to update the case.

**Comment by reasonerjt** [comment]
We can return 202 because it does not exist and the manifest can't exist
