### ISSUE TITLE
There are problems with the latest version pushing the same tag image and copy pull command

### ISSUE THREAD

**Issue by zxiaozhou** [goharbor/harbor#11944]
**Expected behavior and actual behavior:**

1.  How can harbor copy the pull command and get results using sha256 instead of tag.It really affects the experience.
![image](https://user-images.githubusercontent.com/62740686/82034309-9aa3a000-96d0-11ea-89a3-388b6ae9b331.png)

2.  I tag the same tag, which means the same version, but now the old version is still there, so there is a lot of garbage data
![image](https://user-images.githubusercontent.com/62740686/82037544-dccee080-96d4-11ea-9bae-41b1828bf1e1.png)

**Steps to reproduce the problem:**
1. When you click on the mirror pull command, you get sha256 instead of tag
2. Push the same tag image, check the mirror warehouse after success, and produce a lot of garbage data without tag

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.0.0
- docker engine version: 19.03.8
- docker-compose version: 1.25.5

**Comment by bitsf** [comment]
Current design is because the artifact may have several tags for the same digest.

@xaleeks  I think maybe we can add the pull command button to each tag name too.

**Comment by zxiaozhou** [comment]
@xaleeks Can pull command with tag use tag? If not, use sha256

**Comment by adrianovieira** [comment]
Same behaviour here on Harbor-2.0.1-rc1

**Comment by xuchongchong** [comment]
give me tags on pull command of Harbor2.0 please
