### ISSUE TITLE
Conformance test issue

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11943]
As we have already enabled the conformance testing in CI against the master branch, we have to track all of the failures and provide the fix.

Report: https://storage.googleapis.com/harbor-conformance-test/report.html 

CI jobs: https://github.com/goharbor/harbor/actions?query=workflow%3ACONFORMANCE_TEST, it's trigger daily on the latest master code.

Conformance Testing code: https://github.com/opencontainers/distribution-spec.git

**Comment by caniszczyk** [comment]
when you fix the issues, can you send a PR with the conformance test results here like this? https://github.com/opencontainers/oci-conformance/pull/41

thank you!

**Comment by dioguerra** [comment]
Hello,

I just ran conformance tests on my test registry-staging running  (also happens for v2.1.0) harbor:v2.2.0-rc2 and i was presented with:

```bash
Summarizing 3 Failures:

[Fail] OCI Distribution Conformance Tests Push Blob Upload Monolithic [It] POST request with digest and blob should yield a 201 
/home/dtomasgu/ws/distribution-spec/conformance/02_push_test.go:74

[Fail] OCI Distribution Conformance Tests Push Blob Upload Monolithic [It] GET request to blob URL from prior request should yield 200 
/home/dtomasgu/ws/distribution-spec/conformance/02_push_test.go:82

[Fail] OCI Distribution Conformance Tests Push Blob Upload Chunked [It] Out-of-order blob upload should return 416 
/home/dtomasgu/ws/distribution-spec/conformance/02_push_test.go:159

Ran 59 of 62 Specs in 23.744 seconds
FAIL! -- 56 Passed | 3 Failed | 0 Pending | 3 Skipped
```

I am running my test cluster with the harbor-helm with a type: ingress behind an openstack loadbalancer. My cluster is also behind an SSO.

Client -> LB -> reverse proxy (nginx) -> pods

Can you check and validate my findings? Im currently having problems uploading singularity images and all points out to a miss-configuration on the manifest/configs. Im currently reading through the OCI specs to see if i can find the error.

Please check: https://github.com/hpcng/singularity/issues/5691

**Comment by dioguerra** [comment]
From the conformance tests, this is the one that is hindering the push from singularity:

```go
                        g.Specify("POST request with digest and blob should yield a 201", func() {
                                SkipIfDisabled(push)
                                req := client.NewRequest(reggie.POST, "/v2/<name>/blobs/uploads/").
                                        SetHeader("Content-Length", configBlobContentLength).
                                        SetHeader("Content-Type", "application/octet-stream").
                                        SetQueryParam("digest", configBlobDigest).
                                        SetBody(configBlobContent)
                                resp, err := client.Do(req)
                                Expect(err).To(BeNil())
                                location := resp.Header().Get("Location")
                                Expect(location).ToNot(BeEmpty())
                                Expect(resp.StatusCode()).To(Equal(http.StatusCreated))
                        })
```

So, for some reason Harbor is not supporting single file (blob) and digest image push??
Im still reading the specs

**Comment by wy65701436** [comment]
according to the latest status, there is one last failure. I have fixed in the distribution side, Harbor should wait for the next distribution major release, and bump up it.

Close it as fixed.
