### ISSUE TITLE
Harbor Core is not starting up

### ISSUE THREAD

**Issue by JohannesKnauft** [goharbor/harbor#11950]
**Expected behavior and actual behavior:**
Harbor Core is not starting up. After first installation of harbor with the install.sh script the core is not starting. When I check the logs, they just say:
`[FATAL] [/core/main.go:123]: failed to migrate: pq: relation "schema_migrations" does not exist`

**Steps to reproduce the problem:**
1. Download installer `https://github.com/goharbor/harbor/releases/download/v2.0.0/harbor-offline-installer-v2.0.0.tgz`
2. Extract Installer
3. Edit Harbor.yml (find mine attatched)
4. run `./prepare`
5. run `./install.sh`

It First says, thät everything was fine, but in `docker container ls` you can see, that the core Container is always restarting.

**Versions:**

- harbor version: [2.0.0]
- docker engine version: [19.03.8]
- docker-compose version: [1.25.5]

**Additional context:**

- **Harbor config files:**
- **Log files:**

[harbor.zip](https://github.com/goharbor/harbor/files/4634173/harbor.zip)

**Comment by reasonerjt** [comment]
@JohannesKnauft 
This is interesting, I checked the log the following messages indicated that there are data in `/data` volume.
```
May 15 13:46:54 172.18.0.1 core[1136]: 2020-05-15T11:46:54Z [INFO] [/common/dao/pgsql.go:118]: Upgrading schema for pgsql ...
May 15 13:46:54 172.18.0.1 core[1136]: 2020-05-15T11:46:54Z [INFO] [/common/dao/pgsql.go:121]: No change in schema, skip.
```

So could you double check if the `/data` is empty when you do the installation?  Have you tried any dev or rc build that might have installed Harbor and populated data in that directory?

**Comment by JohannesKnauft** [comment]
@reasonerjt reasonerjt So i tried to reinstall it on the machine and deleted the logs, data and common directory before, you can find my install commands in the install.log file.

There are also all other new log files attached.

[harbor-logs.zip](https://github.com/goharbor/harbor/files/4643198/harbor-logs.zip)

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/82276457-eb104b80-99b7-11ea-84e9-01b91a123b2b.png)
clair_db_port is invalidate in harbor.yml
Can you check and upload the harbor.yml

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/82278238-55c38600-99bc-11ea-8fdd-a0deff93c044.png)

in postgresql.log, we can find the database initialization was interruptted, and the db table schema_migrations was not created.

Can you try delete old docker container and fresh install again? And use docker ps to check the harbor-db container status, check if it restart too.

**Comment by JohannesKnauft** [comment]
I removed the docker containers, volumes, common folder, log folder and /data directory und got the same output:

`May 19 09:20:03 172.20.0.1 postgresql[1136]: The files belonging to this database system will be owned by user "postgres".
May 19 09:20:03 172.20.0.1 postgresql[1136]: This user must also own the server process.
May 19 09:20:03 172.20.0.1 postgresql[1136]: 
May 19 09:20:03 172.20.0.1 postgresql[1136]: The database cluster will be initialized with locales
May 19 09:20:03 172.20.0.1 postgresql[1136]:   COLLATE:  en_US.UTF-8
May 19 09:20:03 172.20.0.1 postgresql[1136]:   CTYPE:    en_US.UTF-8
May 19 09:20:03 172.20.0.1 postgresql[1136]:   MESSAGES: C
May 19 09:20:03 172.20.0.1 postgresql[1136]:   MONETARY: C
May 19 09:20:03 172.20.0.1 postgresql[1136]:   NUMERIC:  C
May 19 09:20:03 172.20.0.1 postgresql[1136]:   TIME:     C
May 19 09:20:03 172.20.0.1 postgresql[1136]: The default text search configuration will be set to "english".
May 19 09:20:03 172.20.0.1 postgresql[1136]: 
May 19 09:20:03 172.20.0.1 postgresql[1136]: Data page checksums are disabled.
May 19 09:20:03 172.20.0.1 postgresql[1136]: 
May 19 09:20:03 172.20.0.1 postgresql[1136]: fixing permissions on existing directory /var/lib/postgresql/data ... ok
May 19 09:20:03 172.20.0.1 postgresql[1136]: creating subdirectories ... ok
May 19 09:20:03 172.20.0.1 postgresql[1136]: selecting default max_connections ... 100
May 19 09:20:03 172.20.0.1 postgresql[1136]: selecting default shared_buffers ... 128MB
May 19 09:20:03 172.20.0.1 postgresql[1136]: selecting default timezone ... UTC
May 19 09:20:03 172.20.0.1 postgresql[1136]: selecting dynamic shared memory implementation ... posix
May 19 09:20:03 172.20.0.1 postgresql[1136]: creating configuration files ... ok
May 19 09:20:04 172.20.0.1 postgresql[1136]: running bootstrap script ... ok
May 19 09:20:04 172.20.0.1 postgresql[1136]: performing post-bootstrap initialization ... ok
May 19 09:20:04 172.20.0.1 postgresql[1136]: 
May 19 09:20:04 172.20.0.1 postgresql[1136]: WARNING: enabling "trust" authentication for local connections
May 19 09:20:04 172.20.0.1 postgresql[1136]: You can change this by editing pg_hba.conf or using the option -A, or
May 19 09:20:04 172.20.0.1 postgresql[1136]: --auth-local and --auth-host, the next time you run initdb.
May 19 09:20:04 172.20.0.1 postgresql[1136]: syncing data to disk ... ok
May 19 09:20:04 172.20.0.1 postgresql[1136]: 
May 19 09:20:04 172.20.0.1 postgresql[1136]: Success. You can now start the database server using:
May 19 09:20:04 172.20.0.1 postgresql[1136]: 
May 19 09:20:04 172.20.0.1 postgresql[1136]:     pg_ctl -D /var/lib/postgresql/data -l logfile start
May 19 09:20:04 172.20.0.1 postgresql[1136]: 
May 19 09:20:04 172.20.0.1 postgresql[1136]:                         ****************************************************
May 19 09:20:04 172.20.0.1 postgresql[1136]:                         WARNING: No password has been set for the database.
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         This will allow anyone with access to the
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         Postgres port to access your database. In
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         Docker's default configuration, this is
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         effectively any other container on the same
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         system.
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         Use "-e POSTGRES_PASSWORD=password" to set
May 19 09:20:04 172.20.0.1 postgresql[1136]:                                         it in "docker run".
May 19 09:20:04 172.20.0.1 postgresql[1136]:                         ****************************************************
May 19 09:20:04 172.20.0.1 postgresql[1136]: postgres
May 19 09:20:04 172.20.0.1 postgresql[1136]: waiting for server to start....LOG:  database system was shut down at 2020-05-19 07:20:04 UTC
May 19 09:20:04 172.20.0.1 postgresql[1136]: LOG:  MultiXact member wraparound protections are now enabled
May 19 09:20:04 172.20.0.1 postgresql[1136]: LOG:  autovacuum launcher started
May 19 09:20:04 172.20.0.1 postgresql[1136]: LOG:  database system is ready to accept connections
May 19 09:20:05 172.20.0.1 postgresql[1136]:  done
May 19 09:20:05 172.20.0.1 postgresql[1136]: server started
May 19 09:20:05 172.20.0.1 postgresql[1136]: ALTER ROLE
May 19 09:20:05 172.20.0.1 postgresql[1136]: 
May 19 09:20:05 172.20.0.1 postgresql[1136]: 
May 19 09:20:05 172.20.0.1 postgresql[1136]: /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/initial-notaryserver.sql
May 19 09:20:05 172.20.0.1 postgresql[1136]: CREATE DATABASE
May 19 09:20:05 172.20.0.1 postgresql[1136]: CREATE ROLE
May 19 09:20:05 172.20.0.1 postgresql[1136]: ALTER ROLE
May 19 09:20:05 172.20.0.1 postgresql[1136]: GRANT
May 19 09:20:05 172.20.0.1 postgresql[1136]: 
May 19 09:20:05 172.20.0.1 postgresql[1136]: 
May 19 09:20:05 172.20.0.1 postgresql[1136]: /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/initial-notarysigner.sql
May 19 09:20:06 172.20.0.1 postgresql[1136]: CREATE DATABASE
May 19 09:20:06 172.20.0.1 postgresql[1136]: CREATE ROLE
May 19 09:20:06 172.20.0.1 postgresql[1136]: ALTER ROLE
May 19 09:20:06 172.20.0.1 postgresql[1136]: GRANT
May 19 09:20:06 172.20.0.1 postgresql[1136]: 
May 19 09:20:06 172.20.0.1 postgresql[1136]: 
May 19 09:20:06 172.20.0.1 postgresql[1136]: /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/initial-registry.sql
May 19 09:20:06 172.20.0.1 postgresql[1136]: CREATE DATABASE
May 19 09:20:06 172.20.0.1 postgresql[1136]: You are now connected to database "registry" as user "postgres".
May 19 09:20:06 172.20.0.1 postgresql[1136]: CREATE TABLE
May 19 09:20:06 172.20.0.1 postgresql[1136]: 
May 19 09:20:06 172.20.0.1 postgresql[1136]: 
May 19 09:20:06 172.20.0.1 postgresql[1136]: waiting for server to shut down....LOG:  received fast shutdown request
May 19 09:20:06 172.20.0.1 postgresql[1136]: LOG:  aborting any active transactions
May 19 09:20:06 172.20.0.1 postgresql[1136]: LOG:  autovacuum launcher shutting down
May 19 09:20:06 172.20.0.1 postgresql[1136]: LOG:  shutting down
May 19 09:20:06 172.20.0.1 postgresql[1136]: LOG:  database system is shut down
May 19 09:20:07 172.20.0.1 postgresql[1136]:  done
May 19 09:20:07 172.20.0.1 postgresql[1136]: server stopped
May 19 09:20:07 172.20.0.1 postgresql[1136]: 
May 19 09:20:07 172.20.0.1 postgresql[1136]: PostgreSQL init process complete; ready for start up.
May 19 09:20:07 172.20.0.1 postgresql[1136]: 
May 19 09:20:07 172.20.0.1 postgresql[1136]: LOG:  database system was shut down at 2020-05-19 07:20:06 UTC
May 19 09:20:07 172.20.0.1 postgresql[1136]: LOG:  MultiXact member wraparound protections are now enabled
May 19 09:20:07 172.20.0.1 postgresql[1136]: LOG:  database system is ready to accept connections
May 19 09:20:07 172.20.0.1 postgresql[1136]: LOG:  autovacuum launcher started
May 19 09:20:08 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:10 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:10 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:11 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:11 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:11 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:13 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:13 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:13 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:14 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:14 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:14 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:16 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:16 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:16 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:19 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:19 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:19 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:23 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:23 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:23 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:30 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:30 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:30 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:20:44 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:20:44 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:20:44 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
May 19 09:21:11 172.20.0.1 postgresql[1136]: LOG:  incomplete startup packet
May 19 09:21:11 172.20.0.1 postgresql[1136]: ERROR:  relation "schema_migrations" does not exist at character 26
May 19 09:21:11 172.20.0.1 postgresql[1136]: STATEMENT:  select data_version from schema_migrations
`

**Comment by JohannesKnauft** [comment]
@bitsf @reasonerjt I found the Issue. My database Password in the harbor.yml started with a `#` char. Because of this, the prepare script did not copy the actual value into the env file of the postgres common config dir. I am not familiar with go, but it seems to be a string parsing issue. 
Thanks for your help!
