### ISSUE TITLE
Update docs readme for v2.0

### ISSUE THREAD

**Issue by KeithRichardLee** [goharbor/harbor#11955]
https://github.com/goharbor/harbor/blob/master/docs/README.md currently has the following line of "This is the main table of contents for the Harbor 1.10.x documentation." where it should say "Harbor 2.0.x"

**Comment by xaleeks** [comment]
Good catch Keith, it should be this one https://github.com/goharbor/harbor/blob/master/docs/README.md

I submitted a PR to fix already

**Comment by renmaosheng** [comment]
Hi Keith,
     we are moving the docs to https://goharbor.io/docs/2.0.0/ , you can choose which version of document you can review. Hope this helps. thanks. 
Best regards,
Steven
