### ISSUE TITLE
Migration issue from harbor v1.8.0 to v1.10.0

### ISSUE THREAD

**Issue by hemachandrark** [goharbor/harbor#11962]
I am in the current version of the harbor is v1.8.0 and I want to upgrade to v1.10.0

Followed steps from the `https://goharbor.io/docs/1.10/administration/upgrade/`
 At step 6 am getting the below error

sudo docker run -it --rm -v ${harbor_yml}:/harbor/harbor.yml goharbor/harbor-migrator:v1.10.0 --cfg up
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Skip cfg up as no harbor.cfg in the path.

**Comment by baifuwa** [comment]
${harbor_yml} is configuration file of  harbor v1.8.0

**Comment by hemachandrark** [comment]
@baifuwa Yes I have given the right path of the configuration file `/harbor/harbor.yml`

**Comment by hemachandrark** [comment]
Any update regarding my issue

**Comment by mihalycsokas** [comment]
You changed the path where the file or directory is mounted inside the container: `:/harbor/harbor.yml`   
The migrator tool will try to migrate the file in the path: `:/harbor-migration/harbor-cfg/harbor.yml`   
I used this command: `docker run -it --rm -v ${old_harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml -v ${new_harbor_yml}:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.10.1 --cfg up`
