### ISSUE TITLE
Once scan job is triggerd successfully, image's pull times statistic data will be increased along with it

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11960]
As screenshot shown as below, all "Pulls" statistic was caused by a scan cron job, and if a scan job failed, this job will retry for 5 times, and  "Pulls" statistic will increase many times. My question is, does this "Pulls" statistic mean user pull times, not  any other scenarios? then "Pulls" statistic should not include pulls trigger by a scan job?

![image](https://user-images.githubusercontent.com/44018302/82180639-869bb080-9913-11ea-90b4-db925fbe1047.png)

**Comment by steven-zou** [comment]
@danfengliu 

If the "Pulls" did really happen, they should be counted into the statistic no matter if they're triggered by the scan process.
