### ISSUE TITLE
Azure Replication not working after 2.0 Upgrade

### ISSUE THREAD

**Issue by phin1x** [goharbor/harbor#11974]
Hi,

after the Harbor upgrade to 2.0 the replication to our Azure Container Registry does not work anymore. The registry is marked as unhealthy.
When I try to add the registry again I get the error message "Failed to ping endpoint".
In the debug logs, I see that the acr responds to the ping request with unauthorized.
Does harbor use the given credentials for its registry ping request?

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/82328140-11fb6b80-9a12-11ea-909e-e36ba8194fd7.png)
![image](https://user-images.githubusercontent.com/188115/82328153-14f65c00-9a12-11ea-823e-f6c138eed64a.png)

It seems the auth token in req header is not handle well.

**Comment by Gui13** [comment]
Is the 2.0.1 close to be merged? This is blocking us from migrating to 2.0 for one month

**Comment by Gui13** [comment]
Hello,

We installed the 2.0.1 as soon as it was up, and sadly this problem is not solved.

We are able to push images from the command line, docker login on the same machine works flawlessly, but a simple ping in the UI will issue an error in the logs:

> Jun 22 09:16:13 172.27.0.1 core[31232]: 2020-06-22T09:16:13Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://xxx.azurecr.io: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information.","detail":null}]}

Note that with harbor version 1 there is no issue at all.
