### ISSUE TITLE
Projects are not visible on the UI

### ISSUE THREAD

**Issue by batchamalick** [goharbor/harbor#11970]
Customer is using PKS env and the harbor installation was not part of the tile as it's installed in individual VM

Harbor UI shows invalid username/password but we are able to ssh into the harbor with same username
registry=# select * from properties
registry-# ;
 id |               k                |                                          v
----+--------------------------------+-------------------------------------------------------------------------------------
 46 | email_host                     | smtp.mydomain.com
 55 | ldap_filter                    | (objectClass=person)
 54 | uaa_client_secret              | <enc-v1>BtrSQ6JIYaFVOo6XFffja0e/klYRWQ==
 48 | admin_initial_password         | <enc-v1>dE5p/3K/e0rAqyyD/gHSrC8j3L7MqDtrTaU0
 41 | uaa_client_id                  | id
 22 | jobservice_url                 | http://jobservice:8080
 40 | admiral_url                    | NA
 15 | ldap_scope                     | 2
 53 | max_job_workers                | 10
 62 | scan_all_policy                | {"parameter":{"daily_time":0},"type":"daily"}
 35 | reload_key                     |
  9 | email_port                     | 25
 50 | chart_repository_url           | http://chartmuseum:9999
 45 | uaa_verify_cert                | true
 14 | email_identity                 |
 25 | email_password                 | <enc-v1>uVXAA1/dQrMLcrV2dRkfd32yAw==
 28 | ldap_group_search_scope        | 2
 38 | clair_db_username              | postgres
  4 | ldap_group_attribute_name      | cn
  7 | with_clair                     | false
 59 | ldap_group_search_filter       | (objectclass=group)
 30 | ldap_timeout                   | 5
 32 | postgresql_username            | postgres
 56 | ldap_group_base_dn             | dc=corp,dc=interoptech,dc=local
 20 | notary_url                     | http://notary-server:4443
 26 | registry_url                   | http://registry:5000
 37 | ldap_search_dn                 | cn=adbind,cn=Users,dc=corp,dc=interoptech,dc=local
 39 | postgresql_host                | postgresql
 34 | auth_mode                      | ldap_auth
  5 | ldap_uid                       | sAMAccountName
  8 | email_insecure                 | false
 42 | project_creation_restriction   | everyone
 49 | database_type                  | postgresql
 31 | with_chartmuseum               | true
 18 | email_ssl                      | false
 33 | cfg_expiration                 | 5
 12 | token_expiration               | 30
 29 | clair_db                       | postgres
 13 | postgresql_sslmode             | disable
 27 | email_username                 | sample_admin@mydomain.com
 58 | ldap_group_admin_dn            | cn=* interop infrastructure team,ou=security groups,dc=corp,dc=interoptech,dc=local
 19 | postgresql_database            | registry
  1 | uaa_endpoint                   | uaa.mydomain.org
 10 | with_notary                    | false

On the UI we saw the version as 1.2 however on the docker ps command we see the version as 1.7.5 as below 
iot-dal root@harbor harbor]# docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                            PORTS                                                              NAMES
0b2b80791b89        goharbor/nginx-photon:v1.7.5                  "nginx -g 'daemon of…"   2 months ago        Up About an hour (healthy)        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
69f1c48164d4        goharbor/harbor-portal:v1.7.5                 "nginx -g 'daemon of…"   2 months ago        Up About an hour (healthy)        80/tcp                                                             harbor-portal
b79534a42772        goharbor/harbor-core:v1.7.5                   "/harbor/start.sh"       2 months ago        Up 4 seconds (health: starting)                                                                      harbor-core
8e60653b5d46        goharbor/chartmuseum-photon:v0.8.1-v1.7.5     "/docker-entrypoint.…"   2 months ago        Up About an hour (healthy)        9999/tcp                                                           chartmuseum
38d4e582ff57        goharbor/registry-photon:v2.6.2-v1.7.5        "/entrypoint.sh /etc…"   2 months ago        Up About an hour (healthy)        5000/tcp                                                           registry
8dd38de826f2        goharbor/redis-photon:v1.7.5                  "docker-entrypoint.s…"   2 months ago        Up About an hour                  6379/tcp                                                           redis
b61105e95f2e        goharbor/harbor-db:v1.7.5                     "/entrypoint.sh post…"   2 months ago        Up About an hour (healthy)        5432/tcp                                                           harbor-db
81483b217a80        goharbor/harbor-registryctl:v1.7.5            "/harbor/start.sh"       2 months ago        Up About an hour (healthy)                                                                           registryctl
5dacd1cefc5d        goharbor/harbor-log:v1.7.5                    "/bin/sh -c /usr/loc…"   2 months ago        Up About an hour (healthy)        127.0.0.1:1514->10514/tcp                                          harbor-log
22505105e6cc        goharbor/notary-signer-photon:v0.6.1-v1.7.5   "/bin/signer-start.sh"   12 months ago       Up 1 second     

As the core container is restarting we checked the logs and found below 
tail core.log
May 19 03:19:19 172.24.0.1 core[5416]: 2020-05-19T03:19:19Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:21 172.24.0.1 core[5416]: 2020-05-19T03:19:21Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:23 172.24.0.1 core[5416]: 2020-05-19T03:19:23Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:25 172.24.0.1 core[5416]: 2020-05-19T03:19:25Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:27 172.24.0.1 core[5416]: 2020-05-19T03:19:27Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:29 172.24.0.1 core[5416]: 2020-05-19T03:19:29Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:31 172.24.0.1 core[5416]: 2020-05-19T03:19:31Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:33 172.24.0.1 core[5416]: 2020-05-19T03:19:33Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:35 172.24.0.1 core[5416]: 2020-05-19T03:19:35Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host
May 19 03:19:37 172.24.0.1 core[5416]: 2020-05-19T03:19:37Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host

We ran the command to stop and remove  all the container
[iot-dal root@harbor harbor]# docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
0b2b80791b89
69f1c48164d4
fccf1a54da5a
b79534a42772
8e60653b5d46
dee85c080749
38d4e582ff57
8dd38de826f2
b61105e95f2e
81483b217a80
5dacd1cefc5d
5c1976965c95
22505105e6cc
0aa2b73ecf33
0b2b80791b89
69f1c48164d4
fccf1a54da5a
b79534a42772
8e60653b5d46
dee85c080749
38d4e582ff57
8dd38de826f2
b61105e95f2e
81483b217a80
5dacd1cefc5d
5c1976965c95
22505105e6cc
0aa2b73ecf33
[iot-dal root@harbor harbor]#

We rebooted the harbor VM and now no container was running.

We did a docker-compose by the command 

[iot-dal root@harbor harbor-1.7.5]# docker-compose -f docker-compose.yml  up -d
Creating harbor-db ... done
Creating harbor-core ... done
config.yaml/       postgresql-init.d/
Creating harbor-portal ... done
Creating nginx ... done
Creating registryctl ...
Creating harbor-adminserver ...
Creating harbor-db ...
Creating registry ...
Creating redis ...
Creating harbor-core ...
Creating harbor-jobservice ...
Creating harbor-portal ...
Creating nginx ...
[iot-dal root@harbor harbor-1.7.5]#
[iot-dal root@harbor harbor-1.7.5]# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                   PORTS                                                              NAMES
d13e6c7ad776        goharbor/nginx-photon:v1.7.5             "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
24c3b9f868da        goharbor/harbor-jobservice:v1.7.5        "/harbor/start.sh"       3 minutes ago       Up 3 minutes                                                                                harbor-jobservice
80e6299780b2        goharbor/harbor-portal:v1.7.5            "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes (healthy)   80/tcp                                                             harbor-portal
cf69938b474d        goharbor/harbor-core:v1.7.5              "/harbor/start.sh"       3 minutes ago       Up 3 minutes (healthy)                                                                      harbor-core
9235944e0abc        goharbor/harbor-db:v1.7.5                "/entrypoint.sh post…"   3 minutes ago       Up 3 minutes (healthy)   5432/tcp                                                           harbor-db
5c42b68a7025        goharbor/registry-photon:v2.6.2-v1.7.5   "/entrypoint.sh /etc…"   3 minutes ago       Up 3 minutes (healthy)   5000/tcp                                                           registry
b315fb809669        goharbor/redis-photon:v1.7.5             "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes             6379/tcp                                                           redis
7ec8ef842388        goharbor/harbor-adminserver:v1.7.5       "/harbor/start.sh"       3 minutes ago       Up 3 minutes (healthy)                                                                      harbor-adminserver
80fb993f88a1        goharbor/harbor-registryctl:v1.7.5       "/harbor/start.sh"       3 minutes ago       Up 3 minutes (healthy)                                                                      registryctl
cf777f8ce092        goharbor/harbor-log:v1.7.5               "/bin/sh -c /usr/loc…"   3 minutes ago       Up 3 minutes (healthy)   127.0.0.1:1514->10514/tcp                                          harbor-log
[iot-dal root@harbor harbor-1.7.5]#

Now we were able to login UI however we can not see the projects in the harbor.
We can see the project count and the DB has the info as well 
registry=# select * from project;
 project_id | owner_id |              name               |       creation_time        |        update_time         | deleted
------------+----------+---------------------------------+----------------------------+----------------------------+---------
          1 |        1 | library                         | 2019-04-16 14:17:03.106674 | 2019-04-16 14:17:03.106674 | f
          3 |        4 | rms                             | 2019-04-16 15:03:55        | 2019-04-16 15:03:55        | f
          4 |        3 | helm                            | 2019-04-17 22:14:47        | 2019-04-17 22:14:47        | f
          5 |       42 | k8s-helm-pks                    | 2019-06-10 18:17:02        | 2019-06-10 18:17:02        | f
          6 |       42 | jenkins                         | 2019-06-17 14:19:02        | 2019-06-17 14:19:02        | f
          7 |       42 | chatbot_platform-autobuild      | 2019-07-01 14:22:01        | 2019-07-01 14:22:01        | f
          9 |       42 | chatbot_platform-1.0            | 2019-07-01 14:22:15        | 2019-07-01 14:22:15        | f
         10 |       42 | rms-autobuild                   | 2019-07-24 18:14:59        | 2019-07-24 18:14:59        | f
          2 |        4 | chatbots#2                      | 2019-04-16 15:03:49        | 2019-10-17 15:32:17.593583 | t
          8 |       42 | chatbot_platform-1.1#8          | 2019-07-01 14:22:09        | 2019-10-17 15:33:41.662466 | t
         11 |       42 | chatbot_platform-1.2            | 2019-10-17 15:34:13        | 2019-10-17 15:34:13        | f
         12 |       49 | dluong-wip                      | 2019-12-11 18:32:03        | 2019-12-11 18:32:03        | f
         13 |        3 | pcw#13                          | 2020-01-27 19:48:25        | 2020-01-27 20:02:02.364256 | t
         14 |        3 | clearwater                      | 2020-01-27 20:02:12        | 2020-01-27 20:02:12        | f
         15 |        6 | pksresize                       | 2020-01-30 20:07:55        | 2020-01-30 20:07:55        | f
         16 |        3 | nagios                          | 2020-01-31 15:14:56        | 2020-01-31 15:14:56        | f
         17 |       42 | rms-7.0                         | 2020-02-04 16:51:14        | 2020-02-04 16:51:14        | f
         18 |       42 | chatbot_platform-pre_atomic-1.0 | 2020-02-12 14:44:14        | 2020-02-12 14:44:14        | f
         19 |        3 | edgefs                          | 2020-02-24 20:50:13        | 2020-02-24 20:50:13        | f
         20 |       52 | cluster-monitoring              | 2020-03-24 15:23:36        | 2020-03-24 15:23:36        | f
         21 |       42 | fluentd-elasticsearch-mongo     | 2020-04-15 20:43:04        | 2020-04-15 20:43:04        | f
         22 |       50 | akwon                           | 2020-04-21 17:06:41        | 2020-04-21 17:06:41        | f
(22 rows)

On the core.log we see 
May 19 04:45:54 172.24.0.1 core[5410]: 2020-05-19T04:45:54Z [ERROR] [project.go:426]: Failed to get total of charts under project cluster-monitoring: Get http://chartmuseum:9999/cluster-monitoring/index.yaml: dial tcp: lookup chartmuseum on 127.0.0.11:53: no such host
May 19 04:46:02 172.24.0.1 core[5410]: 2020/05/19 04:46:02 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   8.428132ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m

We need help in getting the project visible on the UI

**Comment by reasonerjt** [comment]
@batchamalick for customer issue please contact vmware GSS, this repo is for Harbor OSS project

**Comment by stonezdj** [comment]
It seems some configuration file missed in the env
```
ERROR: Couldn't find env file: /root/harbor-1.7.5/common/config/clair/clair_env
```
Try this command to regenerate it
```
./prepare --with-clair --with-notary --with-chartmuseum
```
Then run the following command to start Harbor
```
# you can list the file in the current directory, 
ls |grep docker-compose
docker-compose -f docker-compose.yml -f docker-compose.notary.yml -f docker-compose.clair.yml -f docker-compose.chartmuseum.yml 
```
Check the chartmuseum container is running
```
docker ps |grep chartmuseum
```

**Comment by xaleeks** [comment]
is this resolved?  If so, please close @stonezdj
