### ISSUE TITLE
new repository not  visible on the UI after version upgrade

### ISSUE THREAD

**Issue by xiaochenluo** [goharbor/harbor#11976]
The old version of my harbor is 1.6.0. I upgrade it to 1.10.2  a few days ago. After upgrade, all things look good. But yesterday I found that if I pushed an image to a new repository , I can not see it on my harbor website.
Example: 
one of my project named `planet`, and a repository named `venus` in it. If I push an image named `planet/venus:v2`, I can see this image information on my harbor. If I push an image with a new repository name like `planet/mars:v1`, I can not see it on the UI. The image has indeed been pushed, I can pull it in other computers. The only problem is I can't see it on the UI. In the `/var/log/harbor/registry.log`, the image push and pull info can found without error.

Versions:
- harbor version: v1.10.2-d0189bed
- docker engine version: 18.06.1-ce
- docker-compose version: 1.22.0, build f46880fe

**Comment by AllForNothing** [comment]
@xiaochenluo This should not be a UI problem.
@bitsf What do you think?

**Comment by xiaochenluo** [comment]
After checking, we found that the problem was caused by incompatible configuration items. 
Since we need to configure remote storage, we copied configuration items in the `registry/config.yml` directly. But the `notifications` item is not compatible. The problem disappeared after we update this yml file and restart our harbor.
