### ISSUE TITLE
slack channel.

### ISSUE THREAD

**Issue by crazy-canux** [goharbor/harbor#11977]
support to specify slack channel for web hook.

what if someone have multiple web hook for one slack app?
So, gitlab web hook can send message to "gitlab" channel.
harbor web hook can send message to "harbor" channel.

What do you think?

**Comment by xaleeks** [comment]
you can send any number of webhooks to any slack channel, there is no limit to #of slack channels you can configure as endpoints.  Check docs on how to do this.
