### ISSUE TITLE
Is it possible to run Harbor in multi-nodes with single external redis container

### ISSUE THREAD

**Issue by shanmukhavardhan** [goharbor/harbor#11980]
We are implementing Harbor 
i am facing some issues when i am running harbor in 3 nodes and using single Redis container,
and also facing issues when we configured OIDC to harbor.

please suggest better way to handle harbor in Production environment

**Comment by 7error** [comment]
my be you can read this this https://github.com/goharbor/harbor/blob/v2.0.0/docs/install-config/harbor-ha-helm.md
