### ISSUE TITLE
consider disabling 'test connection' for webhook endpoint.

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#11982]
considering disabling 'test connection' button when creating a webhook endpoint in harbor UI.  Even though this is only exposed to project admin, it has been raised by the community that it might not be enough and he should at the very least have select-ability in 'test connection' feature

**Comment by reasonerjt** [comment]
Please clarify we will only disable test connection for webhook.

**Comment by reasonerjt** [comment]
Both the `test connection` button and the API will be removed in 2.0.1

**Comment by AllForNothing** [comment]
Test button on UI has been removed.

**Comment by reasonerjt** [comment]
PR to remove the API:
2.0: https://github.com/goharbor/harbor/pull/12164
master: https://github.com/goharbor/harbor/pull/12163

**Comment by AllForNothing** [comment]
UI PR to remove test button :  #12043 for mater ; #12184 for release-2.0.0
