### ISSUE TITLE
ldaps:// doesn't work in v2.0.0

### ISSUE THREAD

**Issue by olifka** [goharbor/harbor#11984]
Hello!

Secure ldap protocol (ldaps://) doesn't work in v2.0.0. In v1.10.1 all works fine.

**Steps to reproduce the problem:**
Change standard ldap:// URI to ldaps://. Eg.: ldap://my.ldap:389/ to ldaps://my.ldap:636/
Push "Test LDAP Server" button
Get error message "Failed to verify LDAP server with error: internal server error."
If try to save settings with ldaps:// URI, user's authentication will broke

**Versions:**
- harbor version: 2.0.0
- docker engine version: 18.09.6
- docker-compose version: 1.24.0

**Additional context:**
In previous harbor versions all works fine

- **Logs:**
/var/log/docker/core.log
```
May 20 16:08:31 10.11.0.1 core[560]: 2020/05/20 13:08:31.323 #033[1;44m[D]#033[0m [transaction.go:62]  |  192.168.12.43|#033[97;42m 200 #033[0m|   6.996238ms|   match|#033[97;46m POST    #033[0m /api/v2.0/ldap/ping   r:/api/v2.0/ldap/ping
May 20 16:08:39 10.11.0.1 core[560]: 2020-05-20T13:08:39Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"LDAP connect fail, error: LDAP Result Code 200 \"\": remote error: tls: handshake failure"}]} 
May 20 16:08:39 10.11.0.1 core[560]: /harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
May 20 16:08:39 10.11.0.1 core[560]: /harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
May 20 16:08:39 10.11.0.1 core[560]: /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
May 20 16:08:39 10.11.0.1 core[560]: /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
May 20 16:08:39 10.11.0.1 core[560]: /harbor/src/core/api/ldap.go:103, github.com/goharbor/harbor/src/core/api.(*LdapAPI).Ping
```

**Comment by reasonerjt** [comment]
The error `tls: handshake failure` is a bit unclear.
Is it using a self-signed cert?  Is it possible it's expired?
Have you tried to turn off the cert verification?

**Comment by olifka** [comment]
I'm using valid cert (not self-signed), and it's not expired. "Verify cert" option have no effect

**Comment by olifka** [comment]
If this is important, I'm using wildcard cert, and both servers (harbor & ldap) are using the same cert files

**Comment by olifka** [comment]
Could you give me advise, how can I recieve more verbose log data? Is there a harbor debug mode?

**Comment by olifka** [comment]
Hello again!

Checked Harbor v1.10.3 - all works fine with my LDAPS. Problem **only** with version **2.0.0**

Some info about my enviorment:
As the LDAP-server, Red Hat **_389-ds version 1.3.8.4_** is used (_CentOS 7, EPEL_)

Certificate - it's _wildcard_ cert, signed by [COMODO/Sectigo](https://comodoca--c.na115.content.force.com/sfc/dist/version/download/?oid=00D1N000002Ljih&ids=0683l00000G9SlpAAF&d=%2Fa%2F1N0000000wpc%2FDpl1Z0WPKdXMFFcWVLP4OhlPQzse22s919GMgDbM_is&operationContext=DELIVERY&viewId=05H3l000001O5GkEAK&dpt=), expires at 05/21/2021. All other services works fine with this cert

**Comment by 7error** [comment]
@olifka did you try to close Checksum Offloading of your NIC eth0 use this cmd？
```bash
ethtool -K eth0 tx off
```

**Comment by olifka** [comment]
@7error, I tried - it didn't help

**Comment by 7error** [comment]
can you use openssl s_client test the certs in your core container?
```bash
openssl s_client -showcerts -connect my.ldap:636 -servername my.ldap:636 </dev/null 2>/dev/nul
```l

**Comment by olifka** [comment]
`CONNECTED(00000005)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 326 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---`

**Comment by 7error** [comment]
may be this issue https://stackoverflow.com/questions/24124814/secure-renegotiation-is-not-supported-openssl-issue,it can not find current Cipher for tls

**Comment by olifka** [comment]
Turned off SSLv3 and turnde on TLSv1.2 on my ldap-server, as it [described here](https://www.port389.org/docs/389ds/howto/howto-disable-sslv3.html). Now get this reply for the command "openssl s_client":
```
CONNECTED(00000005)
---
Certificate chain
 0 s:OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.my-site.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
-----BEGIN CERTIFICATE-----
000000000000000000000000000000000000
-----END CERTIFICATE-----
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
-----BEGIN CERTIFICATE-----
000000000000000000000000000000000000
-----END CERTIFICATE-----
 2 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
-----BEGIN CERTIFICATE-----
000000000000000000000000000000000000
-----END CERTIFICATE-----
---
Server certificate
subject=OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.my-site.com

issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

---
Acceptable client certificate CA names
C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
Client Certificate Types: RSA sign, ECDSA sign, DSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ECDSA+SHA1:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:RSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ECDSA+SHA1:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:RSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512:DSA+SHA1
---
SSL handshake has read 5137 bytes and written 679 bytes
Verification: OK
---
New, SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-SHA
    Session-ID: 60E2A60DAB1C46F8C4352527DCE80916263E2A99B7550EC11624CE010F1590D3
    Session-ID-ctx:
    Master-Key: 3DA3EF4DC646639894AFF551B0B86410DD92539BB9CFA8F1DDB04C8BB59A65990CE6004C9E6A8BB59AAB18518C5DF62A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1592828392
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

But still get the same error in core.log:
Jun 22 15:23:07 10.11.0.1 core[560]: 2020-06-22T12:23:07Z [ERROR] [/server/error/error.go:53]: `{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"LDAP connect fail, error: LDAP Result Code 200 \"\": remote error: tls: handshake failure"}]}`

**Comment by olifka** [comment]
@7error , thank you!
