### ISSUE TITLE
Some confusing issues of scheduled GC log display

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11994]
Precondition:
     Start scheduled GC job as * */5 * * * *

Issues:
1. Log page was refreshed once job was triggered, no history.
2. After custom schedule was set, custom job started and job ID is  7, with rounds jobs, job ID turns to 8.
3.  After set schedule as none, GC job log with ID 8 disappeared.

**Comment by reasonerjt** [comment]
this will be fixed after switch the job to task manager and will  fall out of v2.1.0.

**Comment by reasonerjt** [comment]
Let's fix it in v2.2 along with #12563

**Comment by wy65701436** [comment]
as GC has migirated to task manager, we can close it.
