### ISSUE TITLE
pull image Error response from daemon: error parsing HTTP 404 response body:

### ISSUE THREAD

**Issue by lijujntao120** [goharbor/harbor#11995]
公司内多部署了一套harbor.v1.6.2 ,通过另一台服务器的nginx反向代理出去，浏览器可以正常登录.在linux命令行里面也是可以正常登录，但push&pull 一直报错，注：没有使用https
和harbor同台机的Nginx代理又能正常使用，麻烦看一下，谢谢！

和harbor同一台机的nginx配置：

===========================
upstream  harbor_port {
     server   192.168.1.23:10080;
}

server {
listen 80;
        server_name docker-harbor.xx.com;

        location   /
        {
        proxy_pass http://192.168.1.23:10080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30000;
        proxy_read_timeout 30000;
        proxy_send_timeout 30000;
        proxy_http_version 1.1;
        client_max_body_size 0;
        }
}
===============================
另外一台机的nginx配置：
server {
listen 80;
        server_name  docker-harbor.xxx.com;
location / {

    proxy_pass              http://192.168.1.23:10080;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
       client_max_body_size 20m;

    }

![image](https://user-images.githubusercontent.com/35087233/82541530-2e6ae580-9b83-11ea-96d5-a66124378ddb.png)

**Comment by lijujntao120** [comment]
好像只能本机Nginx能作正常反向代理，其他服务器的nginx不能正常反向代理

**Comment by TimeBye** [comment]
尝试修改为这样呢？

另外一台机的nginx配置：
```
server {
listen 80;
server_name docker-harbor.xxx.com;
location / {

proxy_pass              http://192.168.1.23:10080;
# proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;
   client_max_body_size 20m;

}
```

**Comment by lijujntao120** [comment]
依然不行，公司的网络方式是NAT端口转发方式，将内网IP转发出去~！

**Comment by lijujntao120** [comment]
location / {

    proxy_pass              http://192.168.1.23:10080;
#    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
#    proxy_http_version 1.1;
    client_max_body_size 20m;

    }

**Comment by lijujntao120** [comment]
![image](https://user-images.githubusercontent.com/35087233/82746008-8c830d00-9dbd-11ea-9766-5a1a0e1656fd.png)

**Comment by bitsf** [comment]
I think you should also set the hostname in harbor.yml to your external name docker-harbor.xxx.com

**Comment by lijujntao120** [comment]
在docker-compose.yml 配置里面，我所使用的版本有点旧，是1.6.2
networks:
  harbor:
    external: false
#    external: http://docker-harbor.xxx.com
#    external_url: http://docker-harbor.xxx.com

**Comment by lijujntao120** [comment]
尝试修改了几次配置，依然无法解决。


Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.14.0</center>\r\n</body>\r\n</html>\r\n"

**Comment by bitsf** [comment]
你可以先在社区的微信群中问问，我记得好像以前有人搭建过nginx的反向代理

**Comment by lijujntao120** [comment]
从哪里可以进社区的微信群呢？？

**Comment by ninjadq** [comment]
Is there any error in your company's Nginx? And I find that the external URL you configured is HTTP, But docker pull/push need https

**Comment by lijujntao120** [comment]
我们push的时候没有使用https的，在使用过程中外面有一层nginx，docker pull/push不成功。
内网访问的是时候通此此nginx代理一下也是不能正常pull/push。
但可以通过harbor所在同一台机的nginx可以正常 pull/push。

**Comment by lijujntao120** [comment]
仓库同时开了http https解决了！

**Comment by kubehan** [comment]
解决了吗？我也遇到这个问题
