### ISSUE TITLE
Installation faliled : invalid mount config for type "bind":mount path must be absolute

### ISSUE THREAD

**Issue by hadri-oussama** [goharbor/harbor#11999]
Dears;

the installation  of harbor 2.0.0 is failing with the error below , the file docker-compose.yml is generated with relative path on on the volume configuration which is think is not supported.

[conf.zip](https://github.com/goharbor/harbor/files/4663281/conf.zip)

```
[Step 5]: starting Harbor ...
Creating harbor-log ...

ERROR: for harbor-log  Cannot create container for service log: invalid mount config for type "bind": invalid mount path: 'common/config/log/logrotate.conf' mount path must be absolute

ERROR: for log  Cannot create container for service log: invalid mount config for type "bind": invalid mount path: 'common/config/log/logrotate.conf' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

1. download and unzip harbor-offline-installer-v2.0.0.tgz
2. generate self signed certificate
3. update harbor.yml
4. execute ./install.sh

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.0]
- docker engine version: [19.03.9]
- docker-compose version: [1.18.0-rc1]

**Additional context:**
- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by bitsf** [comment]
you show give more info about how you config harbor.yml setting
