### ISSUE TITLE
switching auth to ldap requires restart (and there is no hint about that anywhere)

### ISSUE THREAD

**Issue by fireba11** [goharbor/harbor#12007]
**Actual behavior:**
* change auth to ldap
* enter config
* hit test button
-> internal server error

* save
* restart
-> test ok

**Expected behaviour**
either show a message "restart needed" if you change auth
or it should just work without restart

**Versions:**

- harbor version: [2.0.0]

**Comment by stonezdj** [comment]
When switch auth_mod from basic auth to ldap auth, should save the LDAP config settings before test connection.

**Comment by fireba11** [comment]
Saving & testing didn't work either.

**Comment by stonezdj** [comment]
Could you please upload the screenshot and logs?

**Comment by fireba11** [comment]
Not very easily, my testing environment got reused in the meantime.
If it helps i can run my ansible scripts on it again and reproduce it, might take a couple days to get around to do that though.
