### ISSUE TITLE
harbor  FetchArtifacts error when collect tags for repos

### ISSUE THREAD

**Issue by opcache** [goharbor/harbor#12003]
**Expected behavior and actual behavior:**
Many docker images need to be copied synchronously
harbor reported this error
FetchArtifacts error when collect tags for repos

**Steps to reproduce the problem:**
Please see the screenshot
![a20200522111617](https://user-images.githubusercontent.com/39149378/82628889-afc48580-9c20-11ea-9108-3cc7fb101f16.png)
![a20200522111705](https://user-images.githubusercontent.com/39149378/82628891-b3580c80-9c20-11ea-9e61-c50650048842.png)

**Versions:**
CentOS Linux release 7.7.1908 (Core)

- harbor version: [ v2.0.0-87602132]
- docker engine version: [18.09.8]
- docker-compose version: [1.25.4]

**Additional context:**

- **Harbor config files:**
harbor.yml The default configuration only modifies the domain name

- **Log files:**

**Comment by ppabc** [comment]
#9295

**Comment by bitsf** [comment]
what's your repo `aaa` like ? How many tags ?
What is. the job log on UI, and what is /var/log/harbor/core.log?

**Comment by opcache** [comment]
> 
> 
> what's your repo `aaa` like ? How many tags ?
> What is. the job log on UI, and what is /var/log/harbor/core.log?

In the aaa project, there are 150 DOCKER mirror warehouses and more than 3,000 TAGs
This problem is also the same in harbor v1.10.1-f3e11715

**Comment by bitsf** [comment]
In harbor 2.0.0, test with a repo with more than 3000 tags, do pull-based replication, not reproduce the issue.

@opcache Still need you provide logs, something like
![image](https://user-images.githubusercontent.com/188115/83507940-cfe72500-a4fb-11ea-9aaa-5be66a1e6ce1.png)
![image](https://user-images.githubusercontent.com/188115/83508037-f4db9800-a4fb-11ea-9ad5-7d7a7c9833f3.png)

**Comment by bitsf** [comment]
I think I reproduce this when I create 300+ repos.

**Comment by bitsf** [comment]
This issue is because the postgres database connection exceeded.
The default max connection is 100.
However ever it's still not working even set database.max_open_conns in harbor.yaml.
You have to also manually edit postgresql.conf like
`sudo sed  's/max_connections =.*/max_connections=999/g' /data/database/postgresql.conf`
and restart harbor-db

track db issue with 12124

**Comment by nijamashruwala** [comment]
I want to migrate from an old no-auth docker-registry to Harbor. To make the repository and Replication rule, I followed: https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-endpoints/ and https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-rules/

I've changed my PostGres maxConns setting and restarted the pods, as instructed above. I am still getting the same "FetchArtifacts error" when manually starting the replication.

# Change appears after restart
```root [ /var/lib/postgresql/data ]# grep 999 ./postgresql.conf 
max_connections = 999			# (change requires restart)```

# Error still appears
```<namespace>/<podName>[core]: 2020-06-08T20:45:44Z [ERROR] [/replication/operation/controller.go:108]: the execution 209 failed: failed to fetch artifacts: FetchArtifacts error when collect tags for repos```

@bitsf Any thoughts about what might be going on?

**Comment by bench87** [comment]
@nijamashruwala Did you set resource limit for deployment? In my case I set the resources cpu and memory then will not reproduce that error

**Comment by Lincoln-dac** [comment]
core.logs 


Jun 25 10:18:21 172.17.0.1 core[130554]: 2020/06/25 02:18:21.016 #033[1;44m[D]#033[0m [transaction.go:62]  |  10.204.240.15|#033[97;42m 201 #033[0m|   1.705379ms|   match|#033[97;46m POST    #033[0m /api/v2.0/replication/executions   r:/api/v2.0/replication/executions
Jun 25 10:18:21 172.17.0.1 core[130554]: 2020/06/25 02:18:21.025 #033[1;44m[D]#033[0m [middleware.go:52]  |      127.0.0.1|#033[97;42m 200 #033[0m|    177.995µs|   match|#033[97;44m GET     #033[0m /api/version   r:/api/version
Jun 25 10:18:21 172.17.0.1 core[130554]: 2020/06/25 02:18:21.069 #033[1;44m[D]#033[0m [transaction.go:62]  |  10.204.240.15|#033[97;42m 200 #033[0m|   1.357342ms|   match|#033[97;44m GET     #033[0m /api/v2.0/replication/executions   r:/api/v2.0/replication/executions
Jun 25 10:18:22 172.17.0.1 core[130554]: 2020-06-25T02:18:22Z [ERROR] [/common/utils/passports.go:109]: failed to list artifacts of repository '******* http error: code 500, message {"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
Jun 25 10:18:22 172.17.0.1 core[130554]: 2020-06-25T02:18:22Z [ERROR] [/common/utils/passports.go:109]: failed to list artifacts of repository '*******ttp error: code 500, message {"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
Jun 25 10:18:22 172.17.0.1 core[130554]: 2020-06-25T02:18:22Z [ERROR] [/common/utils/passports.go:109]: failed to list artifacts of repository '*******ce': http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}
Jun 25 10:18:22 172.17.0.1 core[130554]: 2020-06-25T02:18:22Z [ERROR] [/common/utils/passports.go:109]: failed to list artifacts of repository '*******': http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}

**Comment by Lincoln-dac** [comment]
i fix this issue

**Comment by cten** [comment]
I am having this same issue but I am using AWS Aurora RDS Serverless which is not showing more than 40 connections at any given where the limit is 180.

**Comment by bitsf** [comment]
@cten you can open another issue to clarify your case
