### ISSUE TITLE
Add Ldap user group by RestApi

### ISSUE THREAD

**Issue by Evendger** [goharbor/harbor#12008]
Hi! Is it possible to add an ldap group via the rest api, I have found an option to attach an ldap group member, but I need to attach a group, not individual group members. Is it possible?

**Comment by stonezdj** [comment]
Yes, you can add usergroup by REST api
Refer the swagger.yaml
https://github.com/goharbor/harbor/blob/master/api/v2.0/legacy_swagger.yaml#L1850
