### ISSUE TITLE
Inconsistency in API for tag retention.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12019]
1. The retention policy is a an attribute for a project, but the URI looks like `/api/retentions/:id`.  Currently the permission of the policy is determined by `scope` in the request body, such as 
```
"scope":{"level":"Project",\"ref":18}}"
```
Which is very error prone and confusing.

2. The `kind` and `pattern` in `tag_selectors` are inconsistent:

```
"tag_selectors": [
        {
          "kind": "doublestar",
          "decoration": "excludes",
          "pattern": "prod*"
        }
```

**Comment by steven-zou** [comment]
@bitsf 

Please check if it's doable. Thanks!
