### ISSUE TITLE
Non-blocking GC engineering story

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12023]
The engineering story of non-blocking GC, use this story to track the engineering tasks.

Proposal：https://github.com/goharbor/community/pull/133

**Comment by reasonerjt** [comment]
@wy65701436 Could you add the `target` label to the sub issues of this epic?

**Comment by zhaogaolong** [comment]
We have completed Non-blocking GC， blocking GC cannot accept， because we have 100T+ docker image ，so once blocking GC need a few days。

The difference is to use mark delete design idea to delete s3 (backend) data，The same is based on database analysis of blolb reference relationship。

gc stage：
1. mark soft delete blolb & artifact and set expired time(Silent time).
2. get expired time is ready , and delete harbor repo:tag, and delete data on s3

bad:
but can't clean  registry link file, because i can't this blob with artifact context .

**Comment by wy65701436** [comment]
hi @zhaogaolong do you mean that you have modified Harbor source code? BTW, the non-blocking GC dev work is almost done, and if you'd like to have a try, just build from latest source or use the latest dev build(let me know if you've interest).

**Comment by zhaogaolong** [comment]
> hi @zhaogaolong do you mean that you have modified Harbor source code? BTW, the non-blocking GC dev work is almost done, and if you'd like to have a try, just build from latest source or use the latest dev build(let me know if you've interest).

@wy65701436  I'm not modified  Harbor source code, only add proxy  in front of habor。The proxy analyzes manifest requests, blob requests, and rejections (if it is marked as deny), and obtains full artifact and blob data through request analysis.

The biggest reason for the development of proxy is that harbor does not support non-blocking gc. Harbor upgrade (currently 1.7) also faces the risk of downtime. We value stability and reliability more.

> the non-blocking GC dev work is almost done

if non-blocking GC done, I‘m happly to try.

**Comment by wy65701436** [comment]
> > hi @zhaogaolong do you mean that you have modified Harbor source code? BTW, the non-blocking GC dev work is almost done, and if you'd like to have a try, just build from latest source or use the latest dev build(let me know if you've interest).
> 
> @wy65701436 I'm not modified Harbor source code, only add proxy in front of habor。The proxy analyzes manifest requests, blob requests, and rejections (if it is marked as deny), and obtains full artifact and blob data through request analysis.
> 
> The biggest reason for the development of proxy is that harbor does not support non-blocking gc. Harbor upgrade (currently 1.7) also faces the risk of downtime. We value stability and reliability more.
> 
> > the non-blocking GC dev work is almost done
> 
> if non-blocking GC done, I‘m happly to try.

@zhaogaolong you can try with the v2.1.0-rc1, it contains non-blocking GC.

**Comment by wy65701436** [comment]
close it as all of engineering task has been done, and the PR of documen has been created.
