### ISSUE TITLE
Replicating upto 20TB of image files from docker-reigstry over to harbor

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#12037]
I got a couple of old docker registries with each holding docker images with a total size of 20tb.
Now due to some compliance reasons, I have to retain all of them while migrating over to harbor.
Those docker registries are storing image contents on S3 buckets.

What is the best way to replicate all the images from those docker registries over to harbor?

How about making a clone of the docker-registry S3 bucket and then make harbor use that cloned S3 bucket, so that when I trigger the replication, it's just about creating the meta-data and I will save on moving actual image blobs?

I couldn't find a document giving a deeper insight into harbor replication and its configuration.
How does replication work under the hood?

**Comment by bitsf** [comment]
Currently we don't have such migration tools to help directly import the registry data to database.
I think what you said that clone the S3 bucket and do replication is feasible.

**Comment by bjethwan** [comment]
@bitsf Thank you.
I am going to try cloning the S3 bucket and attach it to harbor.
I will let you know.

BTW. Any tool to run some functional tests against a harbor cluster? Or maybe some helpful document or tool to run some performance tests. We are expecting a huge number of concurrent image downloads.

**Comment by bjethwan** [comment]
@bitsf Do you know how replication works under the hood? Given that we are planning to re-use S3 bucket from docker-registry it should be fairly simple for the replication job to create the metadata....but I am not able to reason about the resources it would require...time it would require....to complete ......the docs are not helpful to reason about harbor replication performance....And that's one reason we are holding it back to kick start the replication...Kindly let me know.

**Comment by bitsf** [comment]
replication is pull blob from src, and push blob to dest at the same time.
If blob is already in dest, it should be much quicker.
