### ISSUE TITLE
Harbor returns 500 instead of 404 to GET request to non-existing resource

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#12038]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
expected 404 when Get request to non-existing resource.
actual behavior:
GET to /api/chartrepo/test-prj/charts/sample-appaa/ returns 500 with message about chart not found
[centos@centos-test ~]$ curl -vk -X GET -b cookie "https://1.2.3..net/api/chartrepo/test-prj/charts/sample-appaa"
...
* Connected to .... (...) port 443 (#0)
...
< HTTP/2 500
...
{"error":"chart not found"}

**Steps to reproduce the problem:**

send a Get request to a non-exists resource and observer the response, for example,
curl -vk -X GET -b cookie "https://1.2.3.4/api/chartrepo/test-prj/charts/sample-app/1.0.7"
..
...
< HTTP/2 500
...
{"error":"No chart version found for sample-app-1.0.7"}

 curl -vk -X GET -b cookie "https://1.2.3.4/api/chartrepo/test-prj/charts/sample-appaa

< HTTP/2 500
...
{"error":"chart not found"}

**Versions:**
1.10

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

this behavior cause trouble when use API to send question to harbor,  the client don't know whether it's a real "internal server error" or "resource not found", especial in a auto testing case,please help to enhance this behavior.
thanks.

**Comment by ninjadq** [comment]
fixed in https://github.com/goharbor/harbor/pull/12070
