### ISSUE TITLE
Go 1.13 is required during build

### ISSUE THREAD

**Issue by hvandenb** [goharbor/harbor#12035]
During the build I get the following error:

> For this generation to compile you need to have some packages in your GOPATH:
> 
> 	* github.com/go-openapi/runtime
> 	* github.com/jessevdk/go-flags
> 
> You can get these now with: go get -u -f src/server/v2.0/...
> compiling binary for core (golang image)...
> /harbor
> # github.com/goharbor/harbor/src/lib/errors
> ../lib/errors/errors.go:26:7: undefined: errors.As
> ../lib/errors/errors.go:28:7: undefined: errors.Is
> note: module requires Go 1.13

**Comment by hvandenb** [comment]
To solve the issue I did the following. I'll put in PR for the documentation fix.

`docker pull golang:1.13`

**Comment by bitsf** [comment]
harbor build in Makefile is using a  docker container as build, it should auto download the docker image golang:1.13.8
