### ISSUE TITLE
repositories gone when upgrade form 1.10 to 2.0.0 

### ISSUE THREAD

**Issue by kurosakisora** [goharbor/harbor#12046]
- version: 2.0.0
- event: upgrade form 1.10 to 2.0.0
- issue:
First I want to say a huge thanks to harbor teams.
We follow the 2.0.0 main page to upgrade our harbor. Upgrading  process is all ok ,and all project are exit. But when we check the repositories in it, there is nothing, all repositories information are gone. And when we push image to it, harbor restore that image to local filesystem, looks like the in ./common/config/registry/config.yml  is not take effect, but it works well in 1.10, and the logs show nothing error, we don't where is the error.

Thanks for help!

1.10 ./common/config/registry/config.yml:
```
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  oss:
    accesskeyid: ***
    accesskeysecret: ***
    region: oss-cn-beijing
    bucket: **
    chunksize: 1610612736
    endpoint: ***.aliyuncs.com
    internal: True
  delete:
    enabled: true
  redirect:
    disable: True
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://harbor.at***
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
validation:
  disabled: true
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: http://core:8080/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
    ignoredmediatypes:
        - application/vnd.docker.image.rootfs.diff.tar.gzip
        - application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
        - application/vnd.oci.image.layer.v1.tar
        - application/vnd.oci.image.layer.v1.tar+gzip
        - application/vnd.oci.image.layer.v1.tar+zstd
        - application/vnd.oci.image.layer.nondistributable.v1.tar
        - application/vnd.oci.image.layer.nondistributable.v1.tar+gzip
        - application/vnd.oci.image.layer.nondistributable.v1.tar+zstd
        - application/octet-stream
compatibility:
  schema1:
    enabled: true
```

2.0.0 ./common/config/registry/config.yml:
```
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  oss:
    accesskeyid: ***
    accesskeysecret: ***
    region: oss-cn-beijing
    bucket: ***
    chunksize: 1610612736
    endpoint: ***.aliyuncs.com
    internal: True
  delete:
    enabled: true
  redirect:
    disable: True
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
redis:
  addr: redis:6379
  password:
  db: 1
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://harbor.at***
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
compatibility:
  schema1:
    enabled: true
```

**Comment by bitsf** [comment]
Do you mean when you `docker push image` in 2.0.0, you can find the blob under `/data/registry/docker/registry/v2/blobs` ?
How did you install harbor 2.0? What is your harbor.yml like ?

**Comment by reasonerjt** [comment]
@kurosakisora 

I assume you are using `docker-compose` installer?
Please check the content of config.yml of the registry from within the container:
```
docker exec -it registry cat /etc/registry/config.yml
```

**Comment by kurosakisora** [comment]
@bitsf 
yes, I can find /data/registry/docker/registry/v2/blobs, my harbor.yml is like this:

hostname: harbor.atompai.com

http:
  port: 80

https:
  port: 443
  certificate: /etc/letsencrypt/live/harbor.atompai.com/fullchain.pem
  private_key: /etc/letsencrypt/live/harbor.atompai.com/privkey.pem



harbor_admin_password: Harbor12345

database:
  password: xtalpi20181011
  max_idle_conns: 50
  max_open_conns: 100

data_volume: /data

storage_service:
  ca_bundle:

clair:
  updaters_interval: 12

trivy:

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor


_version: 2.0.0


proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy

**Comment by kurosakisora** [comment]
@reasonerjt 
I use ./install.sh to install, then harbot is auto started with no error. Then I down harbor whith 
# docker-compose down
and replace it with abobe file I provided,because the new created file ./common/config/registry/config.yml is not we want,
then use
# docker-compose up -d 
to start harbor

 just follow this guide,
https://github.com/goharbor/harbor/blob/release-2.0.0/docs/administration/upgrade/_index.md
and I encounter a little problem on stop 6, but finall i solved that whith this command:

# docker run -it --rm -v /data/harbor:/data/harbor goharbor/prepare:v2.0.0 migrate -i /data/harbor/harbor.yml

the /data/harbor/harbor.yml is the correct file from v1.10 copy to here,
I'm a little confused about what step 6 actually means，but when i exec this command，the /data/harbor/harbor.yml has been a little change，as far as I saw，just
 - trivy

added in last line.

I didn't check the container's config.yml, i think it will be the same to /common/config/registry/config.yml, because of the registry volume configuration docker-compose.yml 
We have roll back to 1.10, But i will do it again to check. thanks.

**Comment by bitsf** [comment]
Actually you should add storage_service in harbor.yml but not change ./common/config/registry/config.yml directly.

You can now check @reasonerjt comment
docker exec -it registry cat /etc/registry/config.yml

For step 6, it's a mistake, you just run upgrade script
docker run -it --rm -v /:/hostfs goharbor/prepare:v2.0.0 migrate -t 2.0.0 -i path/to/old/harbor.yml -o harbor.yml

**Comment by kurosakisora** [comment]
@bitsf 
sorry, i struggle a while for looking reason, but still can't get through.
when i edit harbor.yml before run prepare, 

harbor.yml:
#data_volume: /data/harbor

storage_service:
  redirect:
    disable: true
  oss:
    accesskeyid: ***
    accesskeysecret: ***
    region: oss-cn-beijing
    bucket: ***
    chunksize: 1610612736
    endpoint: ***
    internal: true
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false

old dir is /data/tools/harbor/,it shows like these:

# docker run -it --rm -v /data/tools/harbor/:/data/tools/harbor/ goharbor/prepare:v2.0.0 migrate -t 2.0.0 -i  /data/tools/harbor/harbor.yml -o harbor.yml

migrating to version 2.0.0
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 40, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_0_0/__init__.py", line 20, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_0_0/harbor.yml.jinja", line 100, in top-level template code
    disabled: {{ value.disabled }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'disabled'

or i try to exec ./prepare, then it shows like this:

prepare base dir is set to /data/tools/harbor
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 38, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 189, in parse_yaml_config
    config_dict['data_volume'] = configs['data_volume']
KeyError: 'data_volume'

but when i first run prepare, the prepare is ok:
migrating to version 2.0.0
Written new values to harbor.yml

but i didn't see any new file harbor.yml and the old file has not been changed, same as ./prepare way too.

And i have check docker exec -it registry cat /etc/registry/config.yml content(with the way edit ./common/config/registry/config.yml directly), it is same content as ./common/config/registry/config.yml.

**Comment by bitsf** [comment]
@ninjadq Can you check this

**Comment by ninjadq** [comment]
the error shows that `value.disabled` not exist, but it seems already in your harbor.yml file. could you edit it with the correct indent?

> @bitsf
> sorry, i struggle a while for looking reason, but still can't get through.
> when i edit harbor.yml before run prepare,
> 
> harbor.yml:
> 
> #data_volume: /data/harbor
> storage_service:
> oss:
> accesskeyid: LTAIQbWaH9tKkPzi
> accesskeysecret: NjM9p3sQtKveVHH4Kwgtleo5hl7a4x
> region: oss-cn-beijing
> bucket: nitrogen
> chunksize: 1610612736
> endpoint: nitrogen.oss-cn-beijing-internal.aliyuncs.com
> internal: True
> delete:
> enabled: true
> redirect:
> disable: True
> maintenance:
> uploadpurging:
> enabled: true
> age: 168h
> interval: 24h
> dryrun: false
> readonly:
> enabled: false
> 
> old dir is /data/tools/harbor/,it shows like these:
> 
> # docker run -it --rm -v /data/tools/harbor/:/data/tools/harbor/ goharbor/prepare:v2.0.0 migrate -t 2.0.0 -i /data/tools/harbor/harbor.yml -o harbor.yml
> 
> migrating to version 2.0.0
> Traceback (most recent call last):
> File "main.py", line 15, in
> cli()
> File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in **call**
> return self.main(*args, **kwargs)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/usr/src/app/commands/migrate.py", line 40, in migrate
> m.migrate(current_input_path, current_output_path)
> File "/usr/src/app/migrations/version_2_0_0/**init**.py", line 20, in migrate
> f.write(tpl.render(**config_dict))
> File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
> self.environment.handle_exception()
> File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
> reraise(*rewrite_traceback_stack(source=source))
> File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
> raise value.with_traceback(tb)
> File "/usr/src/app/migrations/version_2_0_0/harbor.yml.jinja", line 100, in top-level template code
> disabled: {{ value.disabled }}
> jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'disabled'
> 
> or i try to exec ./prepare, then it shows like this:
> 
> prepare base dir is set to /data/tools/harbor
> Traceback (most recent call last):
> File "main.py", line 15, in
> cli()
> File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in **call**
> return self.main(*args, **kwargs)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/usr/src/app/commands/prepare.py", line 38, in prepare
> config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
> File "/usr/src/app/utils/configs.py", line 189, in parse_yaml_config
> config_dict['data_volume'] = configs['data_volume']
> KeyError: 'data_volume'
> 
> but when i first run prepare, the prepare is ok:
> migrating to version 2.0.0
> Written new values to harbor.yml
> 
> but i didn't see any new file harbor.yml and the old file has not been changed, same as ./prepare way too.
> 
> And i have check docker exec -it registry cat /etc/registry/config.yml content(with the way edit ./common/config/registry/config.yml directly), it is same content as ./common/config/registry/config.yml.

**Comment by kurosakisora** [comment]
@ninjadq 
ok，thanks a log，we will try again later，and for my mistake, I had write our oss accesskeysecret info on it, and your comments have it too, even we have delete the old key, but it still has some our oss information on it and it is not safe, could you delete that info on your comments?  Thanks!

**Comment by ninjadq** [comment]
@kurosakisora did you tried with fixed `harbor.yml`? Is this problem solved?

**Comment by kurosakisora** [comment]
not yet, we will response the result as soon as we do it again, thanks for your feedback.

**Comment by finalha** [comment]
Hi all:
I just got the same issue when upgrading harbor from 1.10.4 to 2.4.0. Following the wiki: https://goharbor.io/docs/2.4.0/administration/upgrade/
The services are all OK.
`CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                   PORTS                       NAMES
47cd600287b0   goharbor/harbor-jobservice:v2.4.0      "/harbor/entrypoint.…"   7 minutes ago   Up 7 minutes (healthy)                               harbor-jobservice
cbb8d22792f6   goharbor/nginx-photon:v2.4.0           "nginx -g 'daemon of…"   7 minutes ago   Up 7 minutes (healthy)   0.0.0.0:80->8080/tcp        nginx
405b82c1e6aa   goharbor/harbor-core:v2.4.0            "/harbor/entrypoint.…"   7 minutes ago   Up 7 minutes (healthy)                               harbor-core
59546569d335   goharbor/trivy-adapter-photon:v2.4.0   "/home/scanner/entry…"   7 minutes ago   Up 7 minutes (healthy)                               trivy-adapter
13641dd466cf   goharbor/harbor-db:v2.4.0              "/docker-entrypoint.…"   7 minutes ago   Up 7 minutes (healthy)                               harbor-db
b2641e63de36   goharbor/harbor-portal:v2.4.0          "nginx -g 'daemon of…"   7 minutes ago   Up 7 minutes (healthy)                               harbor-portal
283f612eff54   goharbor/harbor-registryctl:v2.4.0     "/home/harbor/start.…"   7 minutes ago   Up 7 minutes (healthy)                               registryctl
48756c9eff81   goharbor/chartmuseum-photon:v2.4.0     "./docker-entrypoint…"   7 minutes ago   Up 7 minutes (healthy)                               chartmuseum
3f0f1ef75672   goharbor/redis-photon:v2.4.0           "redis-server /etc/r…"   7 minutes ago   Up 7 minutes (healthy)                               redis
5a654e2b6b1d   goharbor/registry-photon:v2.4.0        "/home/harbor/entryp…"   7 minutes ago   Up 7 minutes (healthy)                               registry
826d1bcf41bb   goharbor/harbor-log:v2.4.0             "/bin/sh -c /usr/loc…"   7 minutes ago   Up 7 minutes (healthy)   127.0.0.1:1514->10514/tcp   harbor-log
`
And 
docker exec -it registry cat /etc/registry/config.yml
`version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: redis
  filesystem:
    rootdirectory: /storage
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
redis:
  addr: redis:6379
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  password: 
  db: 1
  pool:
    maxidle: 100
    maxactive: 500
    idletimeout: 60s
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true`
