### ISSUE TITLE
in repo view show the project name

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12050]
Within repository view, I'd like to be able tell which project I'm in.  

![Screen Shot 2020-05-23 at 5 27 17 AM](https://user-images.githubusercontent.com/51319901/82880462-733ca680-9f0c-11ea-9676-c359b0168ae0.png)

![Screen Shot 2020-05-23 at 5 29 58 AM](https://user-images.githubusercontent.com/51319901/82880681-c0207d00-9f0c-11ea-9e56-c61a3e66c513.png)

**Comment by xaleeks** [comment]
@lweitzman Hey Louis, can you help design this

**Comment by lweitzman** [comment]
the simple rule of thumb is the breadcrumb should display the title of the page it will bring you back to. so when drilling into a chart you now see "Projects < **Charts** < **Versions**" and it should read "Projects < **Library** < **[name of chart]**"
