### ISSUE TITLE
implement min interval for GC jobs - update the cron string input text field on UI.

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12057]
I would like to cut down the frequency allowed for Garbage collection by enforcing a minimum interval, perhaps we block the seconds and minutes selection, and set allowable values for the hour field to >=4

**Comment by reasonerjt** [comment]
There's enhancement in backend that GC job can't be scheduled if there is one running.

We can modify the widget on UI once and for all to enforce such minimal interval.
Let's eliminate the bit for second of cron string on UI.

**Comment by AllForNothing** [comment]
Reopen as Cron string on add replication rule page was not covered  before:
![Uploading image.png…]()
