### ISSUE TITLE
Postgres FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#12058]
Harbor Version v1.10.2-d0189bed deployed over k8s using helm chart version harbor-1.3.2.

seems like every couple of hours harbor Postgres receiving 
`FATAL:  sorry, too many clients already`
after some time it will crash and restart.

![image](https://user-images.githubusercontent.com/38837459/82885938-7ce6fe00-9f4e-11ea-9f1f-d282bee60dbe.png)
237 restarts in 11 Days.

I tried to change the value of max_connections in postgresql.conf from 100 to 150,200,250,300.
Also trying increasing harbor-core config map values
```
  POSTGRESQL_MAX_IDLE_CONNS
  POSTGRESQL_MAX_OPEN_CONNS
```

Every setting change may have delayed the issue, but eventually Postgres will crash and reload.

```
LOG:  database system was interrupted; last known up at 2020-05-26 09:28:40 UTC
FATAL:  the database system is starting up
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/60B84F60
LOG:  invalid record length at 0/60C033C0: wanted 24, got 0
LOG:  redo done at 0/60C03398
LOG:  last completed transaction was at log time 2020-05-26 09:29:02.691594+00
FATAL:  the database system is starting up
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
```

![image](https://user-images.githubusercontent.com/38837459/82886984-00551f00-9f50-11ea-8ec2-0f6950cfd01c.png)

any suggestions?

**Comment by reasonerjt** [comment]
Looks like there's a leakage, could you let us know your usage pattern?

**Comment by YakirShriker** [comment]
The new harbor was deployed in order to replace old 1.8,
so the current usage over Harbor1.10 is a single VM who pulling images from Harbor1.8 and pushing to 1.10.
Also, there is harbor-exporter that I wrote that running quite a lot of API calls to Harbor in order to collect metrics that running over 1 year on Harbor 1.8 without any problems.

No other clients currently working with Harbor.

While looking at Postgres pg_stat_activity I can see that all connections received from harbor-core.
```
16388 | registry |   47 |       10 | postgres |                  | 10.84.221.99<#**HARBOR-CORE-POD-IP**#>|                 |       34110 | 2020-05-26 09:35:25.758515+00 |
                        | 2020-05-26 10:36:07.758591+00 | 2020-05-26 10:36:07.75894+00  |                 |            | idle   |             |
    | SELECT COUNT(*) FROM project_blob JOIN blob ON project_blob.blob_id = blob.id AND project_id = $1 AND digest = $2
```

**Comment by bitsf** [comment]
harbor 1.10 introduced Quota function which will record the blob size in db, so it will consume more connections while replication.
I think you can try edit harbor.yml, adjust database.max_open_conns, or edit common/config/core/env  POSTGRESQL_MAX_OPEN_CONNS, to check if this can workaround

**Comment by YakirShriker** [comment]
@Bitsf already tried playing with these values.

**Comment by bitsf** [comment]
@YakirShriker Is it fixed now?

**Comment by YakirShriker** [comment]
@bitsf No, I was trying to change the values before I created the issue. 

> I tried to change the value of max_connections in postgresql.conf from 100 to 150,200,250,300.
> Also trying increasing harbor-core config map values

**Comment by heww** [comment]
The max open connections for the db which is provided in harbor is 100, changing `POSTGRESQL_MAX_OPEN_CONNS`  to 150 in habor core will make db reach it's max connections.

I found that you changed the postgresql.conf in db, can you confirm that the max open connections is changed using `SHOW max_connections;` ? 

The `POSTGRESQL_MAX_IDLE_CONNS` need to be smaller than `POSTGRESQL_MAX_OPEN_CONNS`.

And before 1.9, `POSTGRESQL_MAX_OPEN_CONNS` is 0 and `POSTGRESQL_MAX_IDLE_CONNS` is 2, you can try to change these values as the same with 1.8.

**Comment by YakirShriker** [comment]
SHOW max_connections; indeed showed that max connection number changed.
POSTGRESQL_MAX_IDLE_CONNS is smaller than POSTGRESQL_MAX_OPEN_CONNS

Tried to change the values of POSTGRESQL_MAX_OPEN_CONNS = 0 and POSTGRESQL_MAX_OPEN_CONNS =2 and the same error came after 2 hours.

**Comment by heww** [comment]
What do you do during the 2 hours? Pulling, pushing images, or access the protal ? How frequency do you do these operations?

**Comment by YakirShriker** [comment]
harbor-exporter that I wrote that running quite a lot of API calls to Harbor in order to collect metrics that running over 1 year on Harbor 1.8 without any problems.

Replications between harbors. event-based and scheduled every 3 hours for 7 different projects.

**Comment by heww** [comment]
Is it possible to share the `harbor-exporter` for us so that I can reappear the problem?

**Comment by bitsf** [comment]
@YakirShriker you can check `select count(1) from pg_stat_activity;` , that whether the connection is over 300 that you set.
And I think you can try directly change it to a larger num, like 1000, and see if it can  workaround.

**Comment by YakirShriker** [comment]
Hi,
I Changed Postgres max_connections to 3000,
Harbor core-cm:
  POSTGRESQL_MAX_IDLE_CONNS: "0"
  POSTGRESQL_MAX_OPEN_CONNS: "0"

So far so good.

What do 0 means in these properties?

**Comment by wangweihong** [comment]
meet the same error.  I has an 1.6 version harbor environment, which has 1000+ projects, some projects has 1000+ repositories.  When I upgrade to 1.8, it works fine, all my projects and repositories looks well. But When I upgrade to 1.10.2, core reports "too many clients".  I had check Postgres connection as @bitsf said,  it has only one connection. After I move my old database data away, harbor works fine.

**Comment by heww** [comment]
> Hi,
> I Changed Postgres max_connections to 3000,
> Harbor core-cm:
> POSTGRESQL_MAX_IDLE_CONNS: "0"
> POSTGRESQL_MAX_OPEN_CONNS: "0"
> 
> So far so good.
> 
> What do 0 means in these properties?

`POSTGRESQL_MAX_IDLE_CONNS` is zero means no idle connections are retained.

`POSTGRESQL_MAX_OPEN_CONNS` is zero means no limit on the number of open connections.

**Comment by heww** [comment]
From v2.0.2, the `max_connections` of Postgres (harbor-db) was changed to 1024 and the `POSTGRESQL_MAX_OPEN_CONNS` was changed to 1000.

For the harbor less than v2.0.2, please change the `max_connections` of Postgres yourself according to the wiki https://github.com/goharbor/harbor/wiki/Harbor-FAQs#modify-the-max-connections-of-the-database-for-versions-less-than-v202
