### ISSUE TITLE
whitelist OCI mediaTypes for pushes

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12061]
Consider adding a whitelisting mechanism to control what can and can’t be pushed to harbor.  Since harbor v2.0 is now OCI compliant, you can technically push anything onto harbor with tools like ORAS, ie. push .txt, .vmdk, .wmv, everything is essentially wrapped into a blob that can be onboarded although no metadata is displayed. We need a way to gate access based on the mediaType so there is a handshake with the registry handler.  

related to https://github.com/goharbor/harbor/issues/12013

**Comment by renmaosheng** [comment]
Why we want to whitelist the upload type? this belong to category 'others', I don't see any harm to allow it.
