### ISSUE TITLE
image push: client version 1.40 is too new

### ISSUE THREAD

**Issue by christofhaerens** [goharbor/harbor#12064]
pushing an image with docker client (docker_ce-19.03.9 (released 7 days ago)) results to the following error:
```
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
```
```
# docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:22:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```
Using harbor 2.0

**Comment by reasonerjt** [comment]
it is an error from docker daemon, the request has not yet reached Harbor....

**Comment by chlins** [comment]
@christofhaerens It's looks like docker issue due to the version from 19.03.8 -> 19.03.9, we also ran into the problem, maybe you can downgrade your version to avoid the problem.
