### ISSUE TITLE
host restart fails to bring containers back up

### ISSUE THREAD

**Issue by fireba11** [goharbor/harbor#12063]
**Steps to reproduce the problem:**
* use the installer
* reboot host

The containers depend on one another. On a normal start (docker-compose up -d) this works fine.
If you reboot the host a number of containers will fail to start (exact number varies, with 3 tries i never had everything come up) since the logging container is not yet ready.
A manual docker-compose up -d --build starts the rest just fine.

Is there any way around that? Having to manually kick it on every host reboot isn't really nice ...

Docker log says

May 26 15:31:22 spielplatz-local dockerd[1282]: time="2020-05-26T15:31:22.524000205+02:00" level=error msg="Failed to start container 1916e7b917ee81d7430caedc
fe0eac04d992c328b6d057d4f0dba14f5ce9369e: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused"
May 26 15:31:22 spielplatz-local dockerd[1282]: time="2020-05-26T15:31:22.604882279+02:00" level=error msg="8d0e9b751a040d7f5d81877b1ced716a20176606b08bfc78e9
b5e89b2ebb7786 cleanup: failed to delete container from containerd: no such container"

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.0
- docker engine version: 19.03.9
- docker-compose version: 1.25.4

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
This is dup to https://github.com/goharbor/harbor/issues/7008
