### ISSUE TITLE
Add Korean translation (ko-kr-lang.json)

### ISSUE THREAD

**Issue by minSW** [goharbor/harbor#12067]
Hi
I read the [i18n developer guide](https://github.com/goharbor/harbor/blob/master/docs/build-customize-contribute/developer-guide-i18n.md) and try to translate `lang.json` for UI in Korean.
Can I do this? If somebody already work in progress, plz tell me : )

**Comment by heww** [comment]
Yes, you can create PR to add Korean translation, thanks!

**Comment by bitsf** [comment]
you can also connect other UI colleagues for help if needed

**Comment by minSW** [comment]
@bitsf Thx! 😄

**Comment by minSW** [comment]
This is in Progress.

**Comment by jangjunho7** [comment]
Hi, @minSW .
is this in progress?
