### ISSUE TITLE
Internal server error reported when saving replications rules

### ISSUE THREAD

**Issue by opcache** [goharbor/harbor#12075]
Expected behavior and actual behavior:
Internal server error reported when saving replications rules

Steps to reproduce the problem:
I created 50 replications rules using the API interface. Re-edit the rule, when saving the rule, there will be an internal server error 
Please see the screenshot
![qq20200527173928](https://user-images.githubusercontent.com/39149378/83003697-42aa5900-a041-11ea-92f5-732b741d9998.png)

Versions:
CentOS Linux release 7.7.1908 (Core)

    harbor version: [ v1.10.1-f3e11715]
    docker engine version: [18.09.8]
    docker-compose version: [1.25.4]

Additional context:

    Harbor config files:
    harbor.yml The default configuration only modifies the domain name

    Log files:

**Comment by OBenned** [comment]
Im having the same issue

**Steps to reproduce the problem:**
I've had luck adding the replication rule, but i cannot delete it

**Versions:**
CentOS Linux release 7.8.2003 (Core)

- harbor version: v2.0.0-87602132
- docker engine version: 19.03.9, build 9d988398e7
- docker-compose version: 1.25.5, build 8a1c60f6

**Additional context:**

- **Log files:**

`May 29 10:20:41 172.31.0.1 core[20383]: 2020-05-29T08:20:41Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to delete the policy 1: status behind error"}]} 
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/core/api/replication_policy.go:237, github.com/goharbor/harbor/src/core/api.(*ReplicationPolicyAPI).Delete
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/reflect/value.go:460, reflect.Value.call
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/lib/orm/orm.go:63, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/readonly/readonly.go:77, github.com/goharbor/harbor/src/server/middleware/readonly.MiddlewareWithConfig.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/csrf/csrf.go:55, github.com/goharbor/harbor/src/server/middleware/csrf.attach.func1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/vendor/github.com/gorilla/csrf/csrf.go:297, github.com/gorilla/csrf.(*csrf).ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/csrf/csrf.go:75, github.com/goharbor/harbor/src/server/middleware/csrf.Middleware.func2
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
May 29 10:20:41 172.31.0.1 core[20383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:2802, net/http.serverHandler.ServeHTTP
May 29 10:20:41 172.31.0.1 core[20383]: /usr/local/go/src/net/http/server.go:1890, net/http.(*conn).serve
May 29 10:20:41 172.31.0.1 core[20383]: 2020/05/29 08:20:41.921 #033[1;44m[D]#033[0m [transaction.go:62]  |  192.168.240.9|#033[97;41m 500 #033[0m| 382.720354ms|   match|#033[97;41m DELETE  #033[0m /api/v2.0/replication/policies/1   r:/api/v2.0/replication/policies/:id([0-9]+)`

**Comment by soulawaker** [comment]
In my case, it was occurred when I tried to manually modify `scheduled` rules in Edit Replication Rule GUI. It seems that it is not occurred when Trigger mode is Manual.

**Comment by ywk253100** [comment]
This should be fixed by PR https://github.com/goharbor/harbor/pull/12121 and will be available in 2.0.1.
