### ISSUE TITLE
harbor chartmuseum giving unauthorized intermittently

### ISSUE THREAD

**Issue by piyush94** [goharbor/harbor#12082]
Hi,
We are intermittently facing 401 unauthorized issue during helm push and pull.
Some error in the logs in core.log,
**GET**
![harbor-1-core-log (2)_LI](https://user-images.githubusercontent.com/11614204/83008599-08d25600-a033-11ea-8155-c4face531155.jpg)

**POST**
![harbor-1-core-log-2_LI](https://user-images.githubusercontent.com/11614204/83008846-71213780-a033-11ea-9cb5-a6dbb63b6a58.jpg)

Harbor version v1.10.2-d0189bed
Regards.

**Comment by bitsf** [comment]
seems you didn't login
What detail commands are you using?

**Comment by piyush94** [comment]
@bitsf We are using a script that does helm repo add and update steps before doing helm upgrade.
The first two steps are always successful but when doing the upgrade, helm fails to fetch chart with error code 401 Unauthorized.
Tested with Helm v2.16.3
We install around 30-40 charts sequentially using the script, and we get this error intermittently.

**Comment by bitsf** [comment]
Could it be successful if you upload the same chart again ?
How is your script like ?

**Comment by 7error** [comment]
try pass --username and --password args of your chart repo
```bash
helm upgrade --username youruser --password yourpassword -- --install <release> <chart>
```
