### ISSUE TITLE
inconsistency in /api/v2.0/projects/xxxx

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12080]
As we bumped up to v2.0 and introduce new API for repositories there are some inconsistency in the reference of a project in the URI:

`GET .../api/v2.0/projects/test/repositories/postgres `  <----- project name
`GET .../api/v2.0/projects/1/summary ` <----- project ID

First we need to reach agreement which is the preferred reference of a project or generally all resource in Harbor.

Second, we need to make it consistent at least for projects, which trying to introduce minimal break change.

We probably can make it self-adaptable so the ` /api/v2.0/projects/:reference` can use both name and ID as indicator, for example, we can first try to map to project name, if it fails to find the project with given name and the reference matches the pattern of ID, we fall back to use reference as ID.

**Comment by heww** [comment]
There is a problem for the `reference` that project name can be number in harbor and some customers had used number as the name for their projects.

**Comment by reasonerjt** [comment]
@heww it's clearly true, in that case, we try to match the name first.
I don't think of better way.

**Comment by steven-zou** [comment]
support both ID and name with the same API pattern: /api/v2.0/projects/{id_or_name}

- If `{id_or_name}` is not number, treat it as name
- if `{id_or_name}` is number,
  - if both have id and name equal to `{id_or_name}`, then read a header to confirm if it is id or name
  - otherwise, treat as ID or name per the query situation

**Comment by heww** [comment]
Project and robotv1 APIs support both project name and project id in their path. See #13744 for more info.

And other APIs will track in this issue #13815, I will close this issue.
