### ISSUE TITLE
API for LDAP authentication configuration

### ISSUE THREAD

**Issue by daloulou** [goharbor/harbor#12088]
Hi,
I'm installing Harbor through Ansible and I would like to know if there is a way to configure LDAP authentication without UI, with API or anything else ?

Regards,

Azoulay Dan

**Comment by daloulou** [comment]
Thanks @rayisbadat it's worked 👍
My Ansible version:
`- name: Configure Harbor LDAP Authentication
  uri:
    url: https://{{ harbor_hostname}}:{{ harbor_https_port }}/api/configurations
    method: PUT
    user: admin
    password: {{ harbor_admin_password }}
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body:
      auth_mode: "ldap_auth"
      ldap_url: "{{ harbor_ldap_url }}"
      ldap_base_dn: "{{ harbor_ldap_base_dn}}"
      ldap_search_dn: "{{ harbor_ldap_search_dn }}"
      ldap_search_password: "{{ harbor_search_password }}"
      #ldap_filter: "{{ harbor_ldap_filter }}"
      #ldap_scope: "{{harbor_ldap_scope}}"
      #ldap_timeout: "{{ harbor_ldap_timeout }}"
      #ldap_uid: "{{ harbor_ldap_uid }}"
      #ldap_verify_cert: "{{ harbor_ldap_verify_cert }}"
      #ldap_group_admin_dn: "{{ harbor_ldap_group_admin_dn }}"
      #ldap_group_attribute_name: "{{ harbor_ldap_group_attribute_name }}"
      #ldap_group_base_dn: "{{ harbor_ldap_group_base_dn }}"
      #ldap_group_search_filter: "{{ harbor_ldap_group_search_filter }}"
      #ldap_group_search_scope: "{{ harbor_group_search_scope }}"
      #ldap_group_membership_attribute: "{{ harbor_group_membership_attribute }}"
    validate_certs: no`

**Comment by bigornoo** [comment]
Hello,
important change from Harbor v2.0 : API path = https://your.server/api/v2.0/configurations.
HTH.
