### ISSUE TITLE
Robot Account token expiry / invalidation / crypto errors

### ISSUE THREAD

**Issue by poidag** [goharbor/harbor#12085]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Expected: No manual intervention to reauthenticate Robot Accounts.
Actual: Configured Robot Accounts with valid tokens (expiry set far in the future) periodically return authentication failure/verification error.

**Steps to reproduce the problem:**
Problem happens periodically when Robot Accounts are configured.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10]
- docker version: [18.06-.09]
- kubernetes version: [1.16.9]

**Additional context:**

Around the same time, auth errors connecting to replicated registries begin to occur (without a corresponding password change, restarting both registries resolves the registry auth error)

- **Log files:** You can get them by package the `/var/log/harbor/` .

```
May 5, 2020 @ 14:15:48.383 2020-05-05T14:15:48Z [ERROR] [/core/filter/security.go:430]: failed to authenticate robot$mrs-build: Failed to authenticate user, due to error 'Not found an entry'
May 5, 2020 @ 14:15:46.862 2020-05-05T14:15:46Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
May 5, 2020 @ 14:15:46.862 2020-05-05T14:15:46Z [ERROR] [/core/filter/security.go:196]: failed to decrypt robot token, crypto/rsa: verification error
```

**Comment by wy65701436** [comment]
hi @pickledrick, could you please tell the exactly reproduce steps? Then,I'll have a debug,thanks.

**Comment by wy65701436** [comment]
can you provide the token as well? Or can you try to decode it with jwt-online?

**Comment by bryan-taylor** [comment]
I'm seeing something similar on v2.0.1 . I get intermittent failures (50%?) and I seem to get log entries like this: 
```
Jul 19 20:50:27 192.168.100.1 core[1106]: 2020-07-20T01:50:27Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
Jul 19 20:50:27 192.168.100.1 core[1106]: 2020-07-20T01:50:27Z [ERROR] [/server/middleware/security/robot.go:46][requestID="5dbed84f-90a1-43cf-8dd2-36e791eb174a"]: failed to decrypt robot token: crypto/rsa: verification error
Jul 19 20:50:27 192.168.100.1 core[1106]: 2020-07-20T01:50:27Z [WARNING] [/core/auth/ldap/ldap.go:69]: Not found an entry.
Jul 19 20:50:28 192.168.100.1 core[1106]: 2020-07-20T01:50:28Z [ERROR] [/server/middleware/security/basic_auth.go:41][requestID="5dbed84f-90a1-43cf-8dd2-36e791eb174a"]: failed to authenticate robot$pet_gitlab_ci: Failed to authenticate user, due to error 'Not found an entry'
```
Here is the decode of the robot's password/jwt token via jwt.io:
```
{
  "iat": 1594746950,
  "iss": "harbor-token-defaultIssuer",
  "id": 607,
  "pid": 10,
  "access": [
    {
      "Resource": "/project/10/repository",
      "Action": "push",
      "Effect": ""
    }
  ]
}
```
We have two front end servers and I saw 7 failures yesterday and today, but they were all on sever1 . So possibly the intermittency is because it's working on server2 and failing on server1?

btw... total aside... I think the 'iss' field should be the public hostname of harbor, since there is more than one harbor in the world.

**Comment by bryan-taylor** [comment]
Can we remove the pending-for-more-info tag? I've provide the requested information.

**Comment by wy65701436** [comment]
how did you install Harbor? Helm Chart or Offline?  If Offline, you have to make sure that the server1 and server2 shares the private key, which is responsible for decoding the jwt token, otherwise the token issued by server1 can never be decoded by server2.

**Comment by bryan-taylor** [comment]
Offline. Sounds like a very plausible explanation. Where does harbor store the signing key? I see admin docs on "Customize the Harbor Token Service". Is that the relevant instructions? This doc shows how to generate and put private_key.pem and root.crt in place, and I'm guessing it's the former that is used to sign robot JWT tokens, too.

I think my comment about the 'iss' field above is actually central to the issue. The issuer should say exactly what signed the token. If harbor allows signing tokens to vary per node, the issuer should be the hostname of the node, and the private signing keys should be aggregated across the nodes. A single issuer per cluster seems better, but harbor should enforce a single key.

**Comment by bryan-taylor** [comment]
Does harbor use the same private key for TLS as for signing tokens? The only key I see mentioned anywhere in our harbor.yml is the private_key attribute under https . I did confirm these values are different on out two nodes.

**Comment by wy65701436** [comment]
> Offline. Sounds like a very plausible explanation. Where does harbor store the signing key? I see admin docs on "Customize the Harbor Token Service". Is that the relevant instructions? This doc shows how to generate and put private_key.pem and root.crt in place, and I'm guessing it's the former that is used to sign robot JWT tokens, too.
> 
> I think my comment about the 'iss' field above is actually central to the issue. The issuer should say exactly what signed the token. If harbor allows signing tokens to vary per node, the issuer should be the hostname of the node, and the private signing keys should be aggregated across the nodes. A single issuer per cluster seems better, but harbor should enforce a single key.

yes, the `private_key.pem` is the key to issue token, and the key to sign registry and robot token.

**Comment by langlois-michael** [comment]
> > Offline. Sounds like a very plausible explanation. Where does harbor store the signing key? I see admin docs on "Customize the Harbor Token Service". Is that the relevant instructions? This doc shows how to generate and put private_key.pem and root.crt in place, and I'm guessing it's the former that is used to sign robot JWT tokens, too.
> > I think my comment about the 'iss' field above is actually central to the issue. The issuer should say exactly what signed the token. If harbor allows signing tokens to vary per node, the issuer should be the hostname of the node, and the private signing keys should be aggregated across the nodes. A single issuer per cluster seems better, but harbor should enforce a single key.
> 
> yes, the `private_key.pem` is the key to issue token, and the key to sign registry and robot token.

This easy fix worked for us... Was defiantly a pain after we moved from a single node to two nodes.
