### ISSUE TITLE
show vulnerability as suppressed if cve is whitelisted

### ISSUE THREAD

**Issue by atoom** [goharbor/harbor#12090]
**Is your feature request related to a problem? Please describe.**
We have Harbor configured to prevent pulling of images that contains any critical vulnerabilities. Sometimes there is no proper fix so we have to add a cve to the project/system whitelist. After a rescan of the image it is possible to pull it but there is no indicator in the web-ui that tells the user that the critical cve:s have been suppressed.

**Describe the solution you'd like**
It would be nice if there was some alternative styling or additional text/information in the vulnerability list that indicates that the cve has been suppressed via the whitelist.

**Comment by xaleeks** [comment]
can you think about what's a good indication here? @lweitzman
