### ISSUE TITLE
Replications:can push blob with 401  at pull-base

### ISSUE THREAD

**Issue by zhipengzuo** [goharbor/harbor#12095]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
when i want to do a replication , 401 error occurs.
![image](https://user-images.githubusercontent.com/54702578/83217464-6cc55d80-a19e-11ea-9652-467adbc4f547.png)

this destination registry's url is the coreurl .
as the pic show ,the job have finished pulling from source registry.
 

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.1
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ywk253100** [comment]
What user are you using as the credential of destination harbor instance when running the replication? Does it has the enough permission to do the push operation?
And please make sure the time of source and destination harbor instances are same, the time impacts the expiration of token.

If all these are good, please check the registry log of destination harbor, it should contain the detail information about the 401 error

**Comment by zhipengzuo** [comment]
@ywk253100 I use admin account to do replication.One thing is different is that the url of destination harbor in the pic is the coreurl not the externalurl, does that influence replication?

the log of destination harbor shows ：
![image](https://user-images.githubusercontent.com/54702578/83591452-914c7b80-a58a-11ea-9778-b705b4cc826d.png)

**Comment by zhipengzuo** [comment]
@ywk253100 If i change the coreurl to external it wil be ok .
I see some difference in the log : if replication success ,"http.request.useragent=harbor-registry-client"  when destination url is external is external url   ;  if replication got 404, "http.request.useragent=harbor-replication-service"  when destination url is external is core url,

**Comment by ywk253100** [comment]
I just noticed, why the destination URL in you pic is 10.xxx? It should be `http://core:8080`

**Comment by zhipengzuo** [comment]
@ywk253100 yes. A litter different .We  divide harbor into separate binary not with image.

**Comment by ywk253100** [comment]
It should work but we didn't test the deployment with separated binaries. You need to do some debug deeply.

**Comment by zhipengzuo** [comment]
OK.Thanks.
