### ISSUE TITLE
Helm repo can not pull after changing the Harbor URL

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#12091]
After change the Harbor FQDN in Harbor tile, for example:
a.example.com 
change to 
b.example.com

helm repo add myrepo https://b.example.com/library/chart
helm pull myrepo/xxxxx
The output error shows it still pull the helm chart from the old url: a.example.com 
Because the redis cache cached the url of the helm chart and user cannot clean up the cache.  should we provide a way to cleanup redis cache?

**Comment by reasonerjt** [comment]
Maybe we can always clear redis DB that stores cache for chartmuseum when redis instance restarts?

**Comment by pgkulk** [comment]
Hi @reasonerjt ,
I am facing similar issue. Is there any workaround that I can use until it is fixed?

**Comment by pgkulk** [comment]
Hi @reasonerjt @ninjadq 
Is there any workaround until it is fixed? I am facing the same issue and we are unable to use helm repository. 
Thank you!

**Comment by ninjadq** [comment]
@pgkulk I think you can try to clean Redis cache of chartmsueum
