### ISSUE TITLE
This format image cannot be synchronized with the harbor image warehouse

### ISSUE THREAD

**Issue by opcache** [goharbor/harbor#12109]
Expected behavior and actual behavior:
This format image cannot be synchronized with the harbor image warehouse
E.g:
xxx.xxx.com/xxx/xxx/xxx:1.0
xxx.xxx.com/xxx/xxx/xxx:2.0
But this format image can be pushed to the image warehouse

Steps to reproduce the problem:
Push this format image to the image warehouse
Set up warehouse synchronization rules
This format image cannot be synchronized to another warehouse

Versions:
CentOS Linux release 7.7.1908 (Core)

harbor version: [ v1.10.1-f3e11715]
docker engine version: [18.09.8]
docker-compose version: [1.25.4]

Additional context:

Harbor config files:
harbor.yml The default configuration only modifies the domain name

Log files:

**Comment by bitsf** [comment]
Are you doing replication between two harbor instances or to other registry ?

**Comment by opcache** [comment]
> 
> 
> Are you doing replication between two harbor instances or to other registry ?

Two harbor instances

**Comment by bitsf** [comment]
Can you paste more snapshot that how you create the replication rule and what error is it?

**Comment by opcache** [comment]
A harbor image warehouse
![AAA20200605141901](https://user-images.githubusercontent.com/39149378/83845737-0ad79b80-a73c-11ea-95df-04dda7686f1c.png)
![AAA20200605142937](https://user-images.githubusercontent.com/39149378/83845740-0e6b2280-a73c-11ea-99cf-0f07eb7ad05e.png)


B harbor image warehouse
![BBB20200605144436](https://user-images.githubusercontent.com/39149378/83845756-14f99a00-a73c-11ea-86b8-3b9d704e2860.png)
![bbb20200605144537](https://user-images.githubusercontent.com/39149378/83845757-162ac700-a73c-11ea-8389-29509c4d54e7.png)
![BBB20200605144702](https://user-images.githubusercontent.com/39149378/83845760-175bf400-a73c-11ea-9714-cfe52134d187.png)


B image warehouse cannot synchronize the following address image
hub.XXXXX.com/search/k8s/bert-dssm-ranking:1.22

**Comment by bitsf** [comment]
use `search/**` as resource filter

**Comment by opcache** [comment]
> 
> 
> use `search/**` as resource filter

Still can't sync this docker image

**Comment by bitsf** [comment]
@opcache Are you sure you still can't sync with `search/**`, I have tested, this is worked.
You can show me the new replication rule and job.

**Comment by bitsf** [comment]
close first as not reproduced and no more reply.
