### ISSUE TITLE
Harbor is set to read-only mode, Deleting repository, artifact, tag and pushing image will be disabled under read-only mode.

### ISSUE THREAD

**Issue by kiran009** [goharbor/harbor#12117]
What can we help you?
We recently started using Harbor 2.0.0.
With a fresh installation, no other changed done to GC and other triggers automatically being set.
The system is going to read-only mode, making it unusable.

Something with respect to jobservice need to be taken care, please point me to the same.

**Comment by reasonerjt** [comment]
Are you saying Harbor remains `read-only` after GC job finished?

**Comment by wy65701436** [comment]
this could be dup with https://github.com/goharbor/harbor/issues/12209

**Comment by steven-zou** [comment]
@kiran009 

Could you please provide more context for your issue?

What're your concrete steps for producing this issue.
