### ISSUE TITLE
allow customization with docker images

### ISSUE THREAD

**Issue by fireba11** [goharbor/harbor#12120]
It would be nice if customization (as descripbed in https://goharbor.io/docs/2.0.0/build-customize-contribute/customize-look-feel/) would be able while using the docker container.
aka without manually building everything ;)

I think some basics like colors, logo etc. should be quite sufficient for most users.

**Comment by reasonerjt** [comment]
I don't think it's part of the priority.  Please fork the code to make customization.

**Comment by xaleeks** [comment]
agree w/ @reasonerjt, feel free to submit a proposal and PR on this however
