### ISSUE TITLE
database config max_open_conns in harbor.yml is not work

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12124]
The config max_open_conns is not working, because the postgres config is not changed.
in harbor-db container /var/lib/postgresql/data/postgresql.conf 
  max_connections=100 can be set to max_connections=1000

**Comment by heww** [comment]
We can change the `max_connections` for harbor-db by providing `POSTGRES_MAX_CONNECTIONS`  env for it now.

**Comment by bitsf** [comment]
fixed by https://github.com/goharbor/harbor/pull/12477

**Comment by KeithTt** [comment]
How to modify this value? 

I got this https://github.com/goharbor/harbor/issues/12003 problem.

Harbor version: v1.10.10

I try to modify the value `max_open_conns` in the config file `harbor.yml`, and restart the db service `docker-compose restart postgresql`, but it seems did not work.
