### ISSUE TITLE
update from 1.8.2 to 1.10.2 ip login fail sometimes

### ISSUE THREAD

**Issue by ynntg** [goharbor/harbor#12130]
update from 1.8.2 to 1.10.2 
ui login use ip once fail once sucess 
------
用户名或者密码不正确。
==> /var/log/harbor/proxy.log <==
time ip proxy[9618]: client_ip - "POST /c/login HTTP/1.1" 422 1934 "http://harbor_ip/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" 0.003 0.003 .

harbor version: [1.10.2]
docker engine version: [19.03.10]
docker-compose version: [1.21.2]

**Comment by heww** [comment]
Which method do you install harbor, docker-compose, helm?

Does this problem happen in private mode of browser?

**Comment by ynntg** [comment]
> Which method do you install harbor, docker-compose, helm?
> 
> Does this problem happen in private mode of browser?

i change version,in version 1.10.2 always log docker restart
