### ISSUE TITLE
 Error information is returned (create user api returns status code error, no error message), when the login expires

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#12137]
Error information is returned (create user api returns status code error, no error message), when the login expires，
![image](https://user-images.githubusercontent.com/29826789/83736955-f1274d00-a684-11ea-85ee-e6c04d5a2254.png)
![image](https://user-images.githubusercontent.com/29826789/83736984-fd130f00-a684-11ea-90a5-1cb73200eaa3.png)

**Comment by reasonerjt** [comment]
if it expires it should return 401 not 403.  

Why this is a blocker for 2.0.1?

**Comment by reasonerjt** [comment]
Fixed by following PRs

master : #12195 
2.0 branch: #12212
