### ISSUE TITLE
Failed Replication Executions shows under Local Events - "All" and not "Failed"

### ISSUE THREAD

**Issue by ebcarty** [goharbor/harbor#12134]
After adding a Registry and setting up a manual replication rule,  I executed the replication which failed after a minute.  Tried again with the same failed result.

I noticed the Local Events showing 2 entries and when I clicked on it, it showed the 2 replication executions with a checkmark and nothing was listed under Failed.

![image](https://user-images.githubusercontent.com/13952816/83675562-17b68c80-a58e-11ea-9250-833a41195268.png)

**Comment by reasonerjt** [comment]
The design of "Local Event" is a little confusing.  It doesn't track the job status.
