### ISSUE TITLE
API returns an empty array when '/' is used

### ISSUE THREAD

**Issue by 4integration** [goharbor/harbor#12131]
**Expected behavior and actual behavior:**
Through an API call get a list of artifacts and especially their tags to be used in next step to get vulnerabilities

**Steps to reproduce the problem:**
Using Harbor v2.0 API and endpoint `https://harbor.domain.com/api/v2.0/projects/{project}/repositories/{repository_name}/artifacts?q=tags%3D*&page=1&page_size=10&with_tag=true` to get all tags on an artifact

When I have an repository_name with /  in it and encode that with %252F e.g. something/else to something%252Felse
I get an empty JSON array.

A complete example URL: `https://harbor.domain.com/api/v2.0/projects/builds/repositories/devexp%25252Fcurity-vfb/artifacts?q=tags%3D*&page=1&page_size=10&with_tag=true`

When trying another repository_name which not have / then it works.

**Versions:**
- harbor version: v2.0.0
- docker engine version: 19.03.7
- docker-compose version: 1.25.5

**Comment by ywk253100** [comment]
Is your repository "devexp/curity-vfb"? If it is, you should use `devexp%252Fcurity-vfb`

**Comment by 4integration** [comment]
Aha :) , it is the Swagger UI in Harbor API Explorer that mess it up.
I am using `devexp%252Fcurity-vfb` but SwaggerUI makes the request as `https://harbor.domain.com/api/v2.0/projects/builds/repositories/devexp%25252Fcurity-vfb/artifacts?page=1&page_size=10&with_tag=true` and I copied that.
Using correct encoded string and cURL it works.
