### ISSUE TITLE
adding label UI issue

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12149]
after adding a label to an artifact, the menu doesn't disappear (need to click in the background) and the "Actions" menu shifts up vertically. (#190 might be related)

<img width="356" alt="Screen Shot 2020-06-02 at 4 04 15 PM" src="https://user-images.githubusercontent.com/51319901/83783785-40a65280-a65e-11ea-9b50-7c14cd727c62.png">

**Comment by jwangyangls** [comment]
repeated #12118
