### ISSUE TITLE
UI color inconsistency

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12147]
In dark mode many of the colors are using light mode blue and some colors are missing.

In interrogation services the + sign should be blue and the down arrow for Action seems wrong.
![color of scanner icons wrong plus and down arrow](https://user-images.githubusercontent.com/51319901/83782481-d9889e00-a65d-11ea-9767-a24503c803ad.png)

In projects Policy the button bar should be the lighter blue of the add rule button.
<img width="388" alt="color of button bar" src="https://user-images.githubusercontent.com/51319901/83782578-e1484280-a65d-11ea-92cd-e258eeaa9b71.png">

In configuration, the CVE items are in the darker blue and should be lighter blue in dark mode.
<img width="516" alt="color admin config CVE items" src="https://user-images.githubusercontent.com/51319901/83782682-ea391400-a65d-11ea-9b6f-12d5fcba5068.png">

**Comment by xaleeks** [comment]
@lweitzman please shepherd this fix

**Comment by selina-cui** [comment]
I don't find the second level tab in Clarity UI doc, here is the vSphere Client  for your reference.

<img width="1042" alt="Screen Shot 2020-06-09 at 12 02 52 PM" src="https://user-images.githubusercontent.com/8787455/84105058-c43eb580-aa49-11ea-94c3-02c4a605ecd4.png">
<img width="1069" alt="Screen Shot 2020-06-09 at 12 03 09 PM" src="https://user-images.githubusercontent.com/8787455/84105064-c99c0000-aa49-11ea-8c2a-757ea0ccc298.png">
