### ISSUE TITLE
Registry endpoint issue 

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12153]
2 things. the drop down for Endpoint URL should go away when the user clicks outside of the dropdown. If you click the dropdown and then click cancel button for removing the dropdown, when you come back to the dialog, the drop down is still open. this is opening the dialog fresh: (#140 might be related)

![Screen Shot 2020-06-03 at 2 11 12 PM](https://user-images.githubusercontent.com/51319901/83785217-fd001880-a65e-11ea-9ead-7c2f0c477c3f.png)

**Comment by AllForNothing** [comment]
this has been fixed
