### ISSUE TITLE
cant access system logs sometimes

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12152]
I went to the logs area and see 2 spinners while its trying to get info. it never completed. Seems like we only need the one in the center of the page and could initially use the empty datagrid placeholder. that would then be replaced with the right number of rows.

<img width="475" alt="wrong colors in dark mode" src="https://user-images.githubusercontent.com/51319901/83785155-e8238500-a65e-11ea-89c7-34e39bbb5a46.png">

**Comment by AllForNothing** [comment]
It is because of #11522
