### ISSUE TITLE
Define a remote registry fails with "crypto/aes: invalid key size 12" when using user/password

### ISSUE THREAD

**Issue by titou10titou10** [goharbor/harbor#12158]
When we try to define a remote registry to another Harbor instance, with a valid user/password, the process fails with a "internal server message" and the following traces:

    2020-06-04T20:23:32Z [ERROR] [/replication/registry/manager.go:124]: Convert registry model to dao layer model error: crypto/aes: invalid key size 12
    2020-06-04T20:23:32Z [ERROR] [/core/api/registry.go:231]: Add registry 'https://<remote host>' error: crypto/aes: invalid key size 12
    2020-06-04T20:23:32Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"crypto/aes: invalid key size 12"}]} 

When we left the userid/password empty, it works (the remote registry allows anonymous pulls)
If we set a valid userid/password for the remote registry, we receive the message: "registry https://<remote host> is unhealthy", and this in the logs:

    2020-06-04T20:31:59Z [ERROR] [/server/middleware/security/basic_auth.go:41][requestID="33fb713c-781a-4def-b930-6602341e1f69"]: failed to authenticate admind: Failed to authenticate user, due to error 'Invalid credentials'
    2020-06-04T20:32:00Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://<remote host>: http status code: 401, body: 

So it seems that the problem comes *after* Harbor succeeded to connect to the remote registry and *before* it finalized the process

- harbor version: 1.10.2 and 2.0.0: problem arises with both versions
- docker engine version: 1.16.2 (OpenShift v4.3) and 1.17.1 (OpenShift v4.4)

**Comment by reasonerjt** [comment]
Are you using the helm chart to deploy harbor or using docker-compose?

**Comment by titou10titou10** [comment]
Helm chart. 
If it matters the instances of harbor have been "upgraded" from 1.9 then 1.10.2
From my 2cts analysis, it seems it trie to use some "Internal" "secretkey" to encrypt the given password and it fails bacuse the key is not valid...Or maybe I'm wrong

**Comment by Balador59** [comment]
I have installed it on GKE and add a docker-registry is working, but i have the same issue on AKS and can't add registry with user/pass

**Comment by titou10titou10** [comment]
@Balador59 What do you mean by "*Issue fix on AKS with harbor v2.0.0*" ? Do you mean that you had the problem with v1.10.x and no more with v2.0.0? If so, did you "upgraded" your v1.10 instance or performed a new fresh install of v2.0.0?

**Comment by Balador59** [comment]
@titou10titou10  sorry for the misunderstanding, i was in harbor v1.10.2 and made a fresh install of v2.0.0, but in fact i have now another issue on AKS.

I can add the repository with login and pass but only in http, https keep failing. 
I have open another issue on harbor-helm here -> [issue #612](https://github.com/goharbor/harbor-helm/issues/612)

**Comment by titou10titou10** [comment]
OK. I don't know if thers is a "clean" way to install a fresh v2.0.0 and "transfer" the content of the current v1.10.2 into it as it seems there is something bad in the config

**Comment by ywk253100** [comment]
> Helm chart.
> If it matters the instances of harbor have been "upgraded" (with helm upgtade...) from 1.9 then 1.10.2. And the instance of harbor v2.0.0 has been created from a backup of the first instance, and then an "helm upgrade"
> From my 2cts analysis, it seems it trie to use some "Internal" "secretkey" to encrypt the given password and it fails because the key is not valid...Or maybe I'm wrong

@titou10titou10 You are correct, a secret key is used to encrypt the password: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L330

The secret key is populated into the secret of the core: https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-secret.yaml#L9

Please make sure it's a valid key

**Comment by titou10titou10** [comment]
Yes the 16 bytes secret is here and semms valid... and it seems Harbor has difficuties to use it...

**Comment by titou10titou10** [comment]
Q: is there a way to regenerate a fresh secret key?

**Comment by titou10titou10** [comment]
Got it to work !

As explicitely said in the hem chart readme the`secretKey` that is used to populate the secret must be exactly 16 chars longs! 
Ours was 12, so the message 
    
    [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"crypto/aes: invalid key size 12"}]} 

Maybe the core pod should not start if the length of the secret is not exactly 16 bytes long, or at least make the error message more explicit. eg`the secretKey entry in secret "harbor-core" must be explicitely 16 bytes long` ...

**Comment by rivolity** [comment]
I recently ran into the same issue while trying to configure Harbor, where I was getting an error related to an invalid key size for AES encryption:

```
2024-10-22T12:35:20Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: crypto/aes: invalid key size 18"}]}
```

This error occurred because the encryption key located in `/etc/core/key` had an invalid size. Harbor requires AES encryption keys to be exactly 16, 24, or 32 bytes (128, 192, or 256 bits). My original key was 18 bytes, which caused the error.

## Solution:
Here’s how I fixed it:

1. **Check the Key Size**:
   I found that the key in `/etc/core/key` was 18 bytes long, which is not a valid size for AES encryption.

2. **Generate a Correct Key**:
   You need to generate a raw (binary) 16, 24, or 32-byte key. Initially, I used a base64-encoded key, which caused another error due to the incorrect size (45 bytes instead of 32). To fix this, I generated a raw 32-byte key:

   ```bash
   openssl rand 32 > /etc/core/key
   ```

3. **Verify the Key Size**:
   After generating the key, you can verify the size using:

   ```bash
   wc -c /etc/core/key  # This should return 32
   ```

4. **Restart Harbor**:
   Finally, I restarted Harbor Core Pod.


This resolved the error for me, and Harbor was able to use the key correctly without any issues.
