### ISSUE TITLE
why tcp connection not be released forever when connect to openldap ? 

### ISSUE THREAD

**Issue by Jamlee** [goharbor/harbor#12162]
**Versions:**
- harbor version: [v1.10.1]
- docker engine version: [19.03.6]

![image](https://user-images.githubusercontent.com/5196641/83838544-1622cb00-a72c-11ea-82f6-c04d572a64c3.png)

connection is mean the tcp connection to openldap's 389 port. 
60 connections in the morning.
540 connections in the noon.

**Comment by orangedeng** [comment]
I think it is the same reason I found in my issue https://github.com/goharbor/harbor/issues/12161.

**Comment by orangedeng** [comment]
So, do we have a plan to solve this issue? It is a bug for sure.

**Comment by stonezdj** [comment]
Fixed in PR: #12558, #12543
