### ISSUE TITLE
Connection Leaks when Performing Add-member to Project

### ISSUE THREAD

**Issue by orangedeng** [goharbor/harbor#12161]
**Expected behavior and actual behavior:**
If performing add member API to a project in a harbor with ldap auth enabled, the connection to the openLDAP won't be close in harbor-core container after the search method is finished.

**Steps to reproduce the problem:**
1. Setup a fresh harbor instance
2. Enable LDAP auth in harbor
3. Create project
4. Add a member to this project
5. Use `netstat -na|grep <ldap-server-ip-address>` and you will find multiple `ESTABLISHED` connection to ldap server.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.4]
- docker engine version: [18.09]
- docker-compose version: [1.24.1]

**Additional context:**
Found code [here https://github.com/goharbor/harbor/blob/master/src/core/auth/ldap/ldap.go#L151-L178](https://github.com/goharbor/harbor/blob/master/src/core/auth/ldap/ldap.go#L151-L178) and the connection is not closed after the session opened.

**Comment by reasonerjt** [comment]
let's discuss this in #12162
