### ISSUE TITLE
[OIDC] Handling of user onboarding.

### ISSUE THREAD

**Issue by Cellebyte** [goharbor/harbor#12169]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I expected, that it is possible to change the username of a User.
For that to be able a uuid and a sub field need to be introduced to the user table.
Because Everything regarding OIDC is hardwired against the username.

`["sub"]` uniquely identifies a user from an OIDC Auth provider.
```json
{
  "exp": 1589899135,
  "iat": 1589899075,
  "jti": "0d85f792-d15c-4a7b-9884-f052cea6dc73",
  "iss": "<issuer url>",
  "sub": "bc6cd5c0-3349-4c6b-9da0-9463482e9082",
  "typ": "Bearer",
  "azp": "<client-id>",
  "session_state": "5668c6e2-98b2-468a-b8a3-7c66dd2c4260",
  "acr": "1",
  "allowed-origins": [
    "<endpoint>"
  ],
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile email groups",
  "email_verified": false,
  "name": "GIVEN FAMILYr",
  "groups": [
    "offline_access",
    "uma_authorization",
    "user",
    "<group>"
  ],
  "preferred_username": "<usernamer>",
  "given_name": "GIVEN",
  "family_name": "FAMILY",
  "email": "user@example.com"
}
```

**Steps to reproduce the problem:**
Login first time with your credentials. Set username.

**Comment by reasonerjt** [comment]
Could you clarify your requirement?

As for now, the OIDC onboard process DOES allow user to change his username.

**Comment by Cellebyte** [comment]
In version 1.10.2 it is not possible to change the username once the person is onboarded.
It is also not possible that the username from the auth provider gets adapted.

**Comment by reasonerjt** [comment]
It's the design once the user is onboarded the username cannot changed because it's the attribute to identify a user in Harbor, regardless the auth mode.

As for your second question, looks like this PR may help?
https://github.com/goharbor/harbor/pull/9311

**Comment by xaleeks** [comment]
closing this since it has been addressed, watch for that PR as it will be merged and you will have this capability in the 2.1 release
