### ISSUE TITLE
There is no option to export the vulnerability data as CSV

### ISSUE THREAD

**Issue by prabha1331** [goharbor/harbor#12171]
**Is your feature request related to a problem? Please describe.**
There is no option to export the vulnerability data as CSV 

**Describe the solution you'd like**
There should be a button called Export CSV to export Vulnerability data as CSV 

**Describe the main design/architecture of your solution**
When we click on the artifact name sha256:f87b586d there should be an option to export results as CSV

<img width="1421" alt="Screenshot 2020-06-06 at 1 07 39 PM" src="https://user-images.githubusercontent.com/58968096/83938973-b6ddbd00-a7f6-11ea-98d4-10d928762a9f.png">

**Describe the development plan you've considered**
We need to develop export CSV feature in vulnerability data viewing page.

**Comment by reasonerjt** [comment]
@zidhumenon 
I think you can use the API to achieve similar goal.

**Comment by xaleeks** [comment]
Agreed with @reasonerjt 
we're also working on a feature to aggregate vulnerability data across all projects user is entitled to for display on harbor UI.  Closing this unless it's something not achievable by API, in which case feel free to chime in

**Comment by chlins** [comment]
Closed as delivered since harbor v2.6.
