### ISSUE TITLE
Support image build from github or gitlab

### ISSUE THREAD

**Issue by zhipengzuo** [goharbor/harbor#12177]
**Is your feature request related to a problem? Please describe.**

From some scene like CICD,we need to build image from gitlab or github,Can harbor support ability of image builder?
**Describe the solution you'd like**

**Describe the main design/architecture of your solution**

**Describe the development plan you've considered**

**Additional context**

**Comment by reasonerjt** [comment]
@zhipengzuo 
This is confusing.

Could you elaborate the workflow in your mind.

Harbor stores the image but does not involve in building it from source, it seems you want github to build the image and push to Harbor, if that's the case I don't think there's much Harbor can do as a registry.

**Comment by zhipengzuo** [comment]
> @zhipengzuo
> This is confusing.
> 
> Could you elaborate the workflow in your mind.
> 
> Harbor stores the image but does not involve in building it from source, it seems you want github to build the image and push to Harbor, if that's the case I don't think there's much Harbor can do as a registry.

OK.Thanks. I will try to do image building over harbor.
