### ISSUE TITLE
OIDC User cannot login to docker registry with generated CLI password

### ISSUE THREAD

**Issue by iWangJiaxiang** [goharbor/harbor#12172]
**Expected behavior and actual behavior:**

The command below should login to harbor docker registry successfully.

```shell
docker login -u <OIDC_user> -p <generated CLI command> https://harbor.example.com/
```

However, it returns:

```shell
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://harbor.example.com/v2/: unauthorized: authentication required
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

1. Configure OIDC for harbor instance.
1. Login harbor with OIDC and harbor will create a user automatically.
1. login to harbor using docker CLI with the OIDC user's generated CLI password.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.0
- docker engine version: 19.03.9
- docker-compose version: 1.23.2

**Additional context:**

- **Harbor config files:** 

```
http:
  port: 8800

https:
  port: 8843
  certificate: /path/to/harbor.cert
  private_key: /path/to/harbor.key

external_url: https://harbor.example.com

data_volume: /path/to/harbor-volume/

clair:
  updaters_interval: 12

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  local:
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.0.0

external_database:
.......
```

- **Log files:** You can get them by package the `/var/log/harbor/` .

```
Jun  7 00:40:07 172.28.0.1 core[24044]: 2020/06/06 16:40:07.427 #033[1;44m[D]#033[0m [middleware.go:52]  |  192.168.6.102|#033[97;43m 401 #033[0m|    479.502µs|   match|#033[97;44m GET     #033[0m /v2/   r:/v2/*
Jun  7 00:40:07 172.28.0.1 core[24044]: 2020-06-06T16:40:07Z [ERROR] [/server/middleware/security/oidc_cli.go:54][requestID="35f630bf-d8d2-4aac-8657-44f3aea475c8"]: failed to verify secret: failed to refresh token
Jun  7 00:40:07 172.28.0.1 core[24044]: 2020-06-06T16:40:07Z [ERROR] [/server/middleware/security/basic_auth.go:41][requestID="35f630bf-d8d2-4aac-8657-44f3aea475c8"]: failed to authenticate <OIDC user>: Not supported
```

**Comment by iWangJiaxiang** [comment]
Thank you @reasonerjt .

My problem's solved!

**Comment by dev-hana** [comment]
@iWangJiaxiang 

How did you solve the problem?

**Comment by iWangJiaxiang** [comment]
> A workaround is re-login Harbor via the SSO flow and so the new token will be associated with CLI secret.

**Comment by tumbl3w33d** [comment]
Something's still fishy about this. It is hard to describe when exactly this happens, but the CLI secret certainly has a limited lifetime and if this expiry date is reached, it is not (always) sufficient to open the harbor UI to refresh the lifetime, because your UI session lifetime is not connected to the CLI secret lifetime, i.e., you are still signed in to the UI via IDP, but the CLI secret expired and is not refresh. In that case you need to actively logout and sign in again to refresh it. I'd say there is at least some hook missing when someone is active in the UI to check for expired CLI secret and renew it (and possibly make the user do the OIDC dance).

**Comment by mpsOxygen** [comment]
I am also encountering this issue, usually a logout and re login solves it, but it is really problematic when working with the cli.
