### ISSUE TITLE
harbor-log service starts failed

### ISSUE THREAD

**Issue by shellwalker** [goharbor/harbor#12186]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
After execute the ./install.sh of harbor-online-installer-v1.10.2.tgz, the result as below:
```
ERROR: for harbor-db  Cannot start service postgresql: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused
Creating registryctl   ... error
ERROR: for registry  Cannot start service registry: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

Creating harbor-portal ... error

ERROR: for harbor-portal  Cannot start service portal: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for postgresql  Cannot start service postgresql: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for registry  Cannot start service registry: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for registryctl  Cannot start service registryctl: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for portal  Cannot start service portal: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused
ERROR: Encountered errors while bringing up the project.
```

harbor-log's  docker log result as below:
```
docker logs -f --tail=10 harbor-log
Changing password for root.
sudo: unable to change expired password: Authentication token manipulation error
sudo: Account or password is expired, reset your password and try again
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Changing password for root.
sudo: unable to change expired password: Authentication token manipulation error
sudo: Account or password is expired, reset your password and try again
Changing password for root.
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: unable to change expired password: Authentication token manipulation error
```

**Steps to reproduce the problem:**
1. download `harbor-online-installer-v1.10.2.tgz`
2. unzip it.
3. set the `harbor.yml`
4. execute `install.sh`

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.2]
- docker engine version: [19.03.11]
- docker-compose version: [1.26.0]

**Additional context:**
**WORKAROUND** 
The Current date of my host is 2020/06/09. 
If I execute `date -s 20190609` to set it back to 2019, the `install.sh` will work well, and all services started.

**Comment by qiuhongshuai** [comment]
same problem， any solution？

**Comment by sluetze** [comment]
#11633

**Comment by sluetze** [comment]
Other solution (without time):

1. Start an Container from the log-image in Interactive mode `docker run -it goharbor/harbor-log:v1.10.2 bash`
2. Reset password to an empty password `passwd <return> <return>`
3. Set timeout to infinite for the password, so the timebomb is disabled `chage -M 99999 root`
4. commit the container as new image `docker commit <containerid> goharbor/harbor-öpg:v1.10.2`

Or update to a newer release ;-)

**Comment by reasonerjt** [comment]
Closing as a dup, and v1.10.3 has been released.
