### ISSUE TITLE
Postgresql init should Change directory permissions in harbor-db data directory

### ISSUE THREAD

**Issue by jbrandli** [goharbor/harbor#12182]
Opening a new issue so i can submit a pr for this issue
https://github.com/goharbor/harbor/issues/8224

**Comment by jbrandli** [comment]
jbrandli:12182-Postgresql-init-should-change-directory-permissions-in-harbor-db-data-directory

**Comment by ywk253100** [comment]
@ninjadq  @reasonerjt  I see that the docker official postgres image includes a command to change the ownership of the data directory, is it possible we fix the issue in the same way for both OSS Harbor and Harbor chart https://github.com/docker-library/postgres/blob/master/13/docker-entrypoint.sh#L40?

Maybe [this](https://github.com/goharbor/harbor-helm/issues/444#issuecomment-568261109) is another solution? Not sure about that, need to do more investigation.

Related Harbor chart issues: 
https://github.com/goharbor/harbor-helm/issues/444  
https://github.com/goharbor/harbor-helm/issues/363 
https://github.com/goharbor/harbor-helm/pull/613
