### ISSUE TITLE
harbor 2.0 version, authentication issues

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#12190]
Hello, @steven-zou consult a question, harbor 2.0 version, registry the default use of htpasswd authentication, the previous token authentication method abandoned? How do you compare token,htpasswd?

**Comment by 7error** [comment]
it looks like change from token authentication to basic authentication for registry, read details from this link https://github.com/goharbor/harbor/commit/2064a1cd6d9b97fd2c7445885cdc4eb461455af9

**Comment by PauloFavero** [comment]
Hello,

I was using Harbor 1.10 without HTTPS behind an HTTPS Reverse Proxy. 
In this environment, I was having issues to login into docker.

`Error response from daemon: Get https://my.registry.company.com/v2/: unauthorized: authentication required`

Following the recommendations in this [issue](https://github.com/goharbor/harbor/issues/3114#issuecomment-432962664) I was able to fix it and successfully login and pull/push images into harbor. 

Today, I upgraded Harbor to 2.0.0 and I’m getting the same docker login error.

As the authentication method changed in the config.yml file I don't know to fix this unauthorized authentication error. 

How can I make it work in Harbor 2.0?

Thanks

**Comment by 7error** [comment]
is there any error logs in /var/log/harbor ? Here are the detailed upgrade steps https://github.com/goharbor/harbor/blob/v2.0.0/docs/administration/upgrade/_index.md

**Comment by PauloFavero** [comment]
I don't have access to the logs anymore because I did a complete downgrade to 1.10 again. Following these steps, the config.yml file  inside /common/config/registry will be replaced with the version 2.0.0. Am I right? Because if it happens, I won't be able to login into the registry with the following command:

`docker login my.registry.company.com` 

The version 1.10 uses the following authentication method:

```
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://my.registry.company.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
```

The authentication in version 2.0.0 is:

```
  htpasswd:
     realm: harbor-registry-basic-realm
     path: /etc/registry/passwd
```

Is there a way which I can use the token authentication method in version 2.0.0? 

I'll try to deploy harbor 2.0.0 again to get the logs.

**Comment by 7error** [comment]
i find this https://github.com/goharbor/harbor/issues/10190 ,there may be a big change from v1.10 -->v2.0，but there's no more detail here

**Comment by PauloFavero** [comment]
Yeah, I couldn't find anything helpful to fix it. 
Do you suggest opening a specific issue to better explain the login problem?

**Comment by julienvey** [comment]
Same problem here. And we could not find a clear explanation on what should be done for auth when upgrading from 1.1 to 2.0.

The upgrade guide doesn't mention anything :(

**Comment by PauloFavero** [comment]
> Same problem here. And we could not find a clear explanation on what should be done for auth when upgrading from 1.1 to 2.0.
> 
> The upgrade guide doesn't mention anything :(

I opened an issue for this problem -> https://github.com/goharbor/harbor/issues/12364
