### ISSUE TITLE
Notary Server configuration missing

### ISSUE THREAD

**Issue by fadao23** [goharbor/harbor#12196]
Hello,

Actually I tried many times to configure Notary servers like the official [documentation](https://docs.docker.com/notary/reference/server-config/). But I can't access this file and the harbor.yaml file configuration just allow to configure external DB.

**Expected behavior:**

```
#insert in the Notary configuration file : 
  "repositories": {
    "gun_prefixes": ["docker.io/", "my-own-registry.com/"]
  }

# to be able todo :
ubuntu@harbor:~$ export DOCKER_CONTENT_TRUST=1 
ubuntu@harbor:~$ export DOCKER_CONTENT_TRUST_SERVER=https://my-own-registry.com:4443 

ubuntu@harbor:~$ docker pull docker.io/library/rancher
...
```

**Actual behavior:**

```
ubuntu@harbor:~$ export DOCKER_CONTENT_TRUST=1 
ubuntu@harbor:~$ export DOCKER_CONTENT_TRUST_SERVER=https://my-own-registry.com:4443 

ubuntu@harbor:~$ docker pull docker.io/library/rancher
Error: error contacting notary server: received unexpected HTTP status: 500 Internal Server Error

```

If I look to the log file : `/var/log/harbor/core.log`, I get : 

`
...
Jun  9 15:40:44 172.18.0.1 core[10280]: 2020-06-09T13:40:44Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Mismatch endpoint from string: docker.io/library/rancher, expected endpoint: my-own-registry.com
...
`

How can I enable Notary to pull signed images avaible in DockerHub ?

Thanks

**Comment by reasonerjt** [comment]
@fadao23 
I think there's some misunderstanding.  The Notary in Harbor is for managing the signature of images that are stored in Harbor.

So you cannot pull signed images available in Dockerhub by pointing to the notary instance in Harbor.  Instead, please try to set the  DCT SERVER to `https://notary.docker.io`

**Comment by fadao23** [comment]
Thanks for te answer ! 

So think with me this use case : 

- I have my private registry, and my k8s cluster will pull images from it, but my cluster need some Rancher images.

So all Rancher images are pushed in the DockerHub. I'm trying actually to make a copy of all the rancher images and push into Harbor. But if I have another solution I will take it !

And I tkink the solution to open the `https://notary.docker.io` by the Notary server configurtion files can be good.

Thanks

**Comment by reasonerjt** [comment]
@fadao23 
I don't quite understand why you think updating notary server configuration file in Harbor can solve your problem.  Are you expecting the notary may act like a mirror to the instance at `https://notary.docker.io` ?
