### ISSUE TITLE
Invalid authentication type in www-authenticate header of /v2/_catalog response

### ISSUE THREAD

**Issue by danielpacak** [goharbor/harbor#12192]
**Expected behavior and actual behavior:**

I expect that the `www-authenticate` header in the GET /v2/_catalog response indicates basic authentication type:

```
curl -v https://demo.goharbor.io/v2/_catalog
< HTTP/2 401
< www-authenticate: Basic realm="harbor-registry"
```

**Steps to reproduce the problem:**

```
curl -v https://demo.goharbor.io/v2/_catalog
< HTTP/2 401
< www-authenticate: Bearer realm="https://demo.goharbor.io/service/token",service="harbor-registry"
```

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0-b803975b - Demo server

**Additional context:**

- N/A

**Comment by knqyf263** [comment]
I have a similar problem with a private project. When calling Harbor API, I don't see a `www-authenticate` header in the response.

```
$ curl --insecure -v -X GET "https://core.harbor.domain/api/v2.0/projects/library/repositories/alpine/artifacts/3.10.2/additions/vulnerabilities"

< HTTP/2 401
< server: nginx/1.17.10
< date: Wed, 08 Jul 2020 08:07:59 GMT
< content-type: application/json; charset=utf-8
< content-length: 62
< set-cookie: sid=8c2c47144832c291f3aa2b426c746404; Path=/; HttpOnly
< x-request-id: 912c4745c9a9f9346bfa51818a7d30ec
<
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
```

The version of Harbor in my environment is `v2.0.1-d714b3ea`.

**Comment by reasonerjt** [comment]
@knqyf263 
sorry for the late response.
The `www-authenticate` header is only available for request to `/v2/xxx` URIs.

**Comment by knqyf263** [comment]
Thank you for your answer. I get it. I'm curious why API doesn't support `www-authenticate` even though it requires authentication.
