### ISSUE TITLE
Upgrade to v2 wipes all artifacts

### ISSUE THREAD

**Issue by jetersen** [goharbor/harbor#12197]
We went through an upgrade/downgrade scenario where we ended up needing to destroy our installation due to failed migration.

Than discovered we could not rescan our s3 registry on harbor v2.
Than we decided to downgrade, rescan our registry, upgrade to v2 however once we upgraded the image tags (artifacts) were missing.

We downgraded everything to v1 once again, rescanned registry and we will properly keep it there till v2 upgrade path is safe. We definitely burned our fingers several times.

For anyone else reading this, to rescan see this comment: https://github.com/goharbor/harbor/issues/11773#issuecomment-641418113

Interestingly as long as we stay on version 1 we have all our repositories and image tags available when we follow the above mentioned procedure. However as soon as we upgrade to version 2, the repositories are kept, but all the image tags are lost.

_Originally posted by @FrederikNS in https://github.com/goharbor/harbor/issues/11773#issuecomment-641452261_

**Comment by reasonerjt** [comment]
@jetersen based on the description this looks like a dup to #11773 ?

Could you add comment in #11773 so we can focus the discussion in one issue?
