### ISSUE TITLE
How to support multiple registry?

### ISSUE THREAD

**Issue by duffqiu** [goharbor/harbor#122]
If I have to have one harbor to manage multiple registry,

How can I do it?

Thanks

**Comment by reasonerjt** [comment]
Currently harbor only works with one registry.
I wish to understand more about your scenario, if you have multiple registry instances, do they share storage?

**Comment by duffqiu** [comment]
if without share storage, how can I setup a HA solution with multiple private registries?

**Comment by reasonerjt** [comment]
I don't think we have plan to support it.  
Closing as won't fix.
