### ISSUE TITLE
Replication Rules not working 

### ISSUE THREAD

**Issue by cten** [goharbor/harbor#12207]
**Expected behavior and actual behavior:**
That the replication rule would only replicate images with the specified Label from the Rule.

**Steps to reproduce the problem:**
Create Replication Rule with Source resource filter that specifies a Label, then upload images and check replication logs. The images regardless of the fact they aren't Labeled at all are being replicated.

**Versions:**
- harbor version: 1.10.1

![Screen Shot 2020-05-28 at 10 59 16 AM](https://user-images.githubusercontent.com/13521094/84273420-a41bfe80-aafc-11ea-99b0-b5b5dcf756e7.png)

**Comment by ywk253100** [comment]
@cten Could you upgrade your deployment to Harbor v2.0, it is fixed in 2.0.

**Comment by bitsf** [comment]
How about cherry-pick the fix to 1.10.x, it seems a critical function lost. @reasonerjt
