### ISSUE TITLE
Error 404 on a README link

### ISSUE THREAD

**Issue by gronono** [goharbor/harbor#12217]
Hello,

In README.md in Demos sections, there is a link on "For additional information please refer to this page."

The reference page : https://github.com/goharbor/harbor/blob/master/docs/demo_server.md is not found by Github.

**Comment by reasonerjt** [comment]
Thanks, the docs are being migrated to another repo, we'll keep this open and verify things work after the migration is done.

**Comment by reasonerjt** [comment]
Closing this issue as all the md files have been moved to:
https://github.com/goharbor/website
