### ISSUE TITLE
 How to smoothly and safely upgrade harbor1.9 to 2.0

### ISSUE THREAD

**Issue by zhangzhenyu2** [goharbor/harbor#12227]
What can we help you?

**Comment by reasonerjt** [comment]
I see you opened another issue to ask about upgrading from 1.4 to 2.0, please clarify are you seeing any problem upgrading from 1.9 to 2.0?

**Comment by xaleeks** [comment]
please follow the upgrade guide here: https://goharbor.io/docs/2.0.0/administration/upgrade/
