### ISSUE TITLE
 How to smoothly and safely upgrade harbor1.4 to 2.0 is really a problem, please seek support

### ISSUE THREAD

**Issue by zhangzhenyu2** [goharbor/harbor#12228]
What can we help you?

**Comment by reasonerjt** [comment]
Each release we tested upgrade from 2 lower versions.

So 1.4 -> 1.6 1.6->1.8 1.8 -> 1.10 1.10 ->2.0 should work in your case.

But 1.4.0 is a version that is too old and there's no official support.

I'll keep this open and see if anyone has such experience.
