### ISSUE TITLE
Bump Clair to v2.1.4

### ISSUE THREAD

**Issue by burdzwastaken** [goharbor/harbor#12221]
Clair v2.1.4 is a version that adds support for Ubuntu 20.04. It seems the wording of v2.1.3 was ambiguous and only mentions some "ubuntu support".

ref: https://github.com/quay/clair/releases/tag/v2.1.4

**Comment by wy65701436** [comment]
thanks, we will plan it.

**Comment by wy65701436** [comment]
close it as https://github.com/goharbor/harbor/pull/12245
