### ISSUE TITLE
Cannot find repository if name contains slashes via rest api

### ISSUE THREAD

**Issue by rocenpe** [goharbor/harbor#12224]
If I push image to project whose name contains slashes, then when i do get info about repository via rest api it does not work. In some case the repository cannot be deleted.
Example if you call get info about all repositories in project
curl -X GET "https://vncub2056.os.kb.cz/api/v2.0/projects/it-tools/repositories?page=1&page_size=100" -H "accept: application/json" -H "X-Harbor-CSRF-Token: LXURUcMfo3bnRvzvXGZyFYdIWsewtIABWJsXhmYsXE+WQ5aa2eUXkzgfxS7QQ0O1sP5TY2oNi6UBfwh+p3C+Kw=="

then I see repositories.
{
    "artifact_count": 1,
    "creation_time": "2020-06-11T15:08:50.890Z",
    "id": 4,
    "name": "it-tools/mws/tools/mw_nginx_builder",
    "project_id": 35,
    "pull_count": 1,
    "update_time": "2020-06-11T15:08:52.311Z"
  },

If I call get only for one repository 
curl -X GET "https://vncub2056.os.kb.cz/api/v2.0/projects/it-tools/repositories/mws%2Ftools%2Fmw_nginx_builder" -H "accept: application/json" -H "X-Harbor-CSRF-Token: 62Sp3fpHRrzp5n+pEzw8SfsV8LColsW6qKTsxQe9EwRQUi4W4L3yWTa/RmifGQ3pzKP5FHIvzh7xQPM9xuHxYA=="

then it gives error
{
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "path /api/v2.0/projects/it-tools/repositories/mws/tools/mw_nginx_builder was not found"
    }
  ]
}
If repository name contains project name between slashes then it even cannot be deleted and it gives error method DELETE is not allowed, but [GET] are
see the picture at the attachment

![screen1](https://user-images.githubusercontent.com/13677083/84477075-597ebb80-ac8f-11ea-895e-c37c8f1a8d59.png)

- harbor version: v2.0.0-87602132
- docker engine version: 18.01.0-ce
- docker-compose version: 1.25.5, build 8a1c60f6

Than you for your help.
Blessings,
Petr Rocen

**Comment by reasonerjt** [comment]
@ywk253100 please provide more details regarding how to encode the URI

**Comment by rocenpe** [comment]
Hello Daniel,
This problem I can reproduce with  harbor rest api browser devcenter-api-2.0.
Do you need some logs? Can you clarify what information you need?
Thank you.
Blessings,
Petr

**Comment by ywk253100** [comment]
@rocenpe You need to encode the `/` twice: `a/b` -> `a%252Fb`: https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L673

**Comment by rocenpe** [comment]
Hello Wenkai,
thank you for your notes. Problem is only your rest api browser devcenter-api-2.0. I must change slash for %2F 
![image](https://user-images.githubusercontent.com/13677083/84755424-ef815180-afc1-11ea-97e5-82b1b27e5b00.png)
Maybe wants to fix it, it's a little confusing
Blessings,
Petr

**Comment by Akaronte** [comment]
reponame encode before send in url 
"replaceAll('/', '%252F')"
This works for me
