### ISSUE TITLE
unauthorized: unauthorized to access repository: library/tomcat, action: push: unauthorized to access repository: library/tomcat, action: push

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12229]
My harbor architecture

harbor2.0

User ->  load balancer  (ali slb, tcp:443)   -> harbor1 host(192.168.xxx.1, tcp 80) or harbor2  host(192.168.xxx.2, tcp 80)

haror1 and  harbor2  harbor.yml 
    hostname: harbor.domain.cn

I use admin account,  push tomcat:

[root@ceph3 ~]# docker push harbor.domain.cn/library/tomcat
The push refers to repository [harbor.domain.cn/library/tomcat]
123a7175f991: Preparing 
68b9387df273: Preparing 
a1c4399f9b22: Preparing 
4f866e977815: Preparing 
f73b2345c404: Preparing 
f5181c7ef902: Waiting 
2e5b4ca91984: Waiting 
527ade4639e0: Waiting 
c2c789d2d3c5: Waiting 
8803ef42039d: Waiting 
unauthorized: unauthorized to access repository: library/tomcat, action: push: unauthorized to access repository: library/tomcat, action: push

push other image is same error.

===================

my logs 

`==> /var/log/harbor/core.log <==
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [WARNING] [/server/middleware/security/v2_token.go:51][requestID="22687602-ff0c-423a-821e-4dbad206085c"]: failed to decode bearer token: crypto/rsa: verification error
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [WARNING] [/server/middleware/security/v2_token.go:51][requestID="43eef867-7d55-479b-91f0-4586f1436e5e"]: failed to decode bearer token: crypto/rsa: verification error
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
Jun 13 20:21:09 192.168.0.1 core[11956]: 2020-06-13T12:21:09Z [WARNING] [/server/middleware/security/v2_token.go:51][requestID="607417d9-a67b-4d07-b3f8-7c662956df90"]: failed to decode bearer token: crypto/rsa: verification error

==> /var/log/harbor/registry.log <==
Jun 13 20:21:09 192.168.0.1 registry[11956]: time="2020-06-13T12:21:09.763619445Z" level=info msg="authorized request" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=ec71f106-96bd-438c-91ba-3d01c5448e3a http.request.method=HEAD http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/library/tomcat/blobs/sha256:612a9f566fdc082f9d43f642791723e34bab94c243b34a965b4602d416ee7a72" http.request.useragent="docker/19.03.11 go/go1.13.10 git-commit/42e35e61f3 kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.11 \(linux\))" vars.digest="sha256:612a9f566fdc082f9d43f642791723e34bab94c243b34a965b4602d416ee7a72" vars.name="library/tomcat" 
Jun 13 20:21:09 192.168.0.1 registry[11956]: time="2020-06-13T12:21:09.764808362Z" level=info msg="redis: connect 192.168.200.8:6379" go.version=go1.13.8 instance.id=6d36cff5-eed6-4773-a984-f76cf3f92b1d redis.connect.duration=1.076414ms service=registry version=v2.7.1.m 
Jun 13 20:21:09 192.168.0.1 registry[11956]: 2020/06/13 12:21:09 GET http://harbor-1302123233.cos.ap-shanghai.myqcloud.com/docker/registry/v2/repositories/library/tomcat/_layers/sha256/612a9f566fdc082f9d43f642791723e34bab94c243b34a965b4602d416ee7a72/link ...
Jun 13 20:21:09 192.168.0.1 registry[11956]: time="2020-06-13T12:21:09.766334263Z" level=info msg="authorized request" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=edd6025e-85a0-4cfb-916c-a4e1e882e9aa http.request.method=HEAD http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/library/tomcat/blobs/sha256:fbb20561cd50035dc87ca3800f5ea60f1690595721486e3358281cda470af5f2" http.request.useragent="docker/19.03.11 go/go1.13.10 git-commit/42e35e61f3 kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.11 \(linux\))" vars.digest="sha256:fbb20561cd50035dc87ca3800f5ea60f1690595721486e3358281cda470af5f2" vars.name="library/tomcat`
`

What should i do? 

![harbor1](https://user-images.githubusercontent.com/50136484/84569994-f428e880-adbc-11ea-92e7-6ce46e9fa1e7.png)

======================

close harbor2  host,  push image is same error.

**Comment by fz8770** [comment]
i  using external storage, 

storage_service:
  ca_bundle:
  oss:
    .....

**Comment by fz8770** [comment]
if not use slb,  User -> harbor1 host, No problem.
 What should i do?

**Comment by reasonerjt** [comment]
@fz8770 
I think your deployment is problematic, the two instances are setup separately and they have different keys to verify token, hence if the request carries token of instance A is sent to instance B, instance B cannot verify it.

**Comment by fz8770** [comment]
> @fz8770
> I think your deployment is problematic, the two instances are setup separately and they have different keys to verify token, hence if the request carries token of instance A is sent to instance B, instance B cannot verify it.

How to solve this? please tell me, thanks. 
How can let them have same token ?

**Comment by tedgxt** [comment]
I use docker-compose to deploy 2 harbor instance at 2 nodes and same question occurred。
to sovle this，make sure the `private_key.pem` for core and `root.crt` for registry is same in different  nodes。
