### ISSUE TITLE
更改docker工作（graph）目录后 ,harbor启动异常，报错如下

### ISSUE THREAD

**Issue by wzg0120** [goharbor/harbor#12220]
`rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied`

why?

**Comment by reasonerjt** [comment]
Because the file permission changes when you copy the directory on your docker host.

You should use `cp -p`

**Comment by LuChenjing** [comment]
请问后来怎么解决的?我也是在数据迁移，cp的时候没有带上权限之类的。

**Comment by andanyoung** [comment]
解决方案：https://editor.csdn.net/md/?articleId=129621152
