### ISSUE TITLE
Unable to upload Helm chart in Harbor 2.0 

### ISSUE THREAD

**Issue by mramanathan** [goharbor/harbor#12233]
I installed Harbor using this [playbook](https://github.com/mramanathan/ansible-harbor). No issues with that. 

Recently, received set of changes via this [PR](https://github.com/mramanathan/ansible-harbor/pull/3) to upgrade to Harbor 2.0; amongst other things, this PR has code changes to exclude chartmuseum. Using the changes from this PR, am unable to upload Helm chart.

FWIW, my Harbor is setup to run in a local VM managed using Vagrant and VirtualBox, no TLS certs installed.

Pls let me know what more details are needed to consider this issue.

**Comment by renmaosheng** [comment]
could you push docker images? only the helm chart not working? please upload the logs.

**Comment by mramanathan** [comment]
can push Docker images but failing with Helm charts. Will share the logs in few days.
