### ISSUE TITLE
docker pull push invalid character 'p' after top-level value: "404 page not found\n"

### ISSUE THREAD

**Issue by kerven88** [goharbor/harbor#12248]
外部用nginx代理了harbor，login正常，push和pull提示：
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
![image](https://user-images.githubusercontent.com/51351006/84733312-7a694880-afd0-11ea-93a4-cf803088f367.png)

nginx配置：
![image](https://user-images.githubusercontent.com/51351006/84733338-8ce38200-afd0-11ea-8da2-eef9b0b5b0c1.png)

harbor.yml配置：
![image](https://user-images.githubusercontent.com/51351006/84733369-a1c01580-afd0-11ea-9dd6-a7744bf59347.png)

麻烦帮忙看看是什么问题？

**Comment by mzzgaopeng** [comment]
push 的时候 看registry、core日志

**Comment by kerven88** [comment]
> push 的时候 看registry、core日志

push时候同时 监控core和 registry的日志，没有任何输出，并且nginx access log也没有，所以应该请求都还没到nginx这一层。
接下来要怎么排查？

**Comment by kerven88** [comment]
docker login 是正常的，nginx access日志也有：
124.172.188.118 - liyongan [16/Jun/2020:14:53:03 +0800] "GET /service/token?account=liyongan&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 913 "-" "docker/19.03.11 go/go1.13.10 git-commit/42e35e61f3 kernel/3.10.0-957.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.11 \x5C(linux\x5C))"
124.172.188.118 - - [16/Jun/2020:14:53:05 +0800] "GET /v2/ HTTP/1.1" 200 2 "-" "docker/19.03.11 go/go1.13.10 git-commit/42e35e61f3 kernel/3.10.0-957.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.11 \x5C(linux\x5C))"

push和pull时候nginx日志都没有，请求还没到nginx这一层就出问题了

**Comment by mzzgaopeng** [comment]
tagpush号加上吧

**Comment by kerven88** [comment]
> tagpush号加上吧

[root@heketi ~]# docker push harbor.deepexi.cloud/ywops/busybox:latest
The push refers to repository [harbor.deepexi.cloud/ywops/busybox]
1be74353c3d0: Preparing 
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
加了tag还是一样的情况。

**Comment by 7error** [comment]
@kerven88 does your domain harbor.deepexi.cloud listen 443 port but not harbor web app?
read https://github.com/moby/moby/issues/33564#issuecomment-608215995 and https://docs.docker.com/registry/insecure/

**Comment by kerven88** [comment]
> @kerven88 does your domain harbor.deepexi.cloud listen 443 port but not harbor web app?
> read [moby/moby#33564 (comment)](https://github.com/moby/moby/issues/33564#issuecomment-608215995) and https://docs.docker.com/registry/insecure/

http模式，没用https

**Comment by 7error** [comment]
@kerven88 
1、does docker pull work ok?  

2、I mean the machine whitch the front nginx have other 443 listen?

run `ss -tunlp |grep 443` on the nginx machine

3、your nginx`s conf  /v2/ proxy_pass backend`s /v2/ is also not needed， juet / proxy backend`s /

**Comment by 7error** [comment]
@kerven88 

You can use this method to debug to find some information

1、 config docker daemon debug,and reload config

https://success.docker.com/article/how-do-i-enable-debug-logging-of-the-docker-daemon  

2、 docker pull image or push  from your registry

3、find`s dockerd log

journalctl -fexu docker

**Comment by kerven88** [comment]
pull也是一样错误，nginx只代理了harbor的http 80端口，harbor并没有启用https 17053331551 邮箱：17053331551@139.com 签名由 网易邮箱大师 定制 On 06/16/2020 19:25, 7error wrote: @kerven88 1、does docker pull work ok? 2、I mean the machine whitch the front nginx have other 443 listen? run ss -tunlp |grep 443 on the nginx machine 3、your nginxs conf /v2/ proxy_pass backends /v2/ is also not needed， juet / proxy backend`s / — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kerven88** [comment]
> @kerven88
> 1、does docker pull work ok?
> 
> 2、I mean the machine whitch the front nginx have other 443 listen?
> 
> run `ss -tunlp |grep 443` on the nginx machine
> 
> 3、your nginx conf /v2/ proxy_pass backend /v2/ is also not needed， just / proxy backend /

1、pull也是一样错误，nginx只代理了harbor的http 80端口，harbor并没有启用https。
2、/v2/ 代理删除了也是一样情况。

**Comment by kerven88** [comment]
> @kerven88
> 
> You can use this method to debug to find some information
> 
> 1、 config docker daemon debug,and reload config
> 
> https://success.docker.com/article/how-do-i-enable-debug-logging-of-the-docker-daemon
> 
> 2、 docker pull image or push from your registry
> 
> 3、look dockerd log
> 
> journalctl -fexu docker

docker debug日志如下：
![image](https://user-images.githubusercontent.com/51351006/84842854-d687a780-b078-11ea-81d8-48b88217bb0c.png)

**Comment by kerven88** [comment]
参考这个issue的方法也没用。
https://github.com/goharbor/harbor/issues/3114

**Comment by 7error** [comment]
important information
```bash
skipping non-tls endpoint for host/port that appears to use tls
```
because it·s docker pull logic for http ,it`ll always first sniffing https( your domain 443) 

![7FA4E636-3815-4C07-AE6A-95BFCCEC303A](https://user-images.githubusercontent.com/55312878/84843860-a097f280-b07b-11ea-9708-42ea277c8cc7.png)

read this https://docs.docker.com/registry/insecure/

**Comment by kerven88** [comment]
> important information
> 
> ```shell
> skipping non-tls endpoint for host/port that appears to use tls
> ```
> 
> because this is docker pull default logic for http ,it will always first sniffing https( your domain 443)
> 
> ![7FA4E636-3815-4C07-AE6A-95BFCCEC303A](https://user-images.githubusercontent.com/55312878/84843860-a097f280-b07b-11ea-9708-42ea277c8cc7.png)
> 
> read this https://docs.docker.com/registry/insecure/

但 docker daemon.json 已经配置了http模式。
![image](https://user-images.githubusercontent.com/51351006/84844720-90811280-b07d-11ea-8d17-c621802af7ed.png)

**Comment by 7error** [comment]
yes ,but docker still attempt https, this is docker story

**Comment by kerven88** [comment]
harbor修改成https方式解决了该问题。

**Comment by ninjadq** [comment]
close cause the problem is solved

**Comment by linxingwu** [comment]
> harbor修改成https方式解决了该问题。

过分了啊，不https不让用？
