### ISSUE TITLE
can I use the auth-htpasswd in registry or core/ui in version 1.6.0 and 1.10.1

### ISSUE THREAD

**Issue by mzzgaopeng** [goharbor/harbor#12249]
In my project, I whill change my auth from token to htpasswd
CHANGE:
common/config/registry/config.yml
![token](https://user-images.githubusercontent.com/22125180/84739674-a5f32f80-afde-11ea-9ea5-86dfa262bb85.png)

but when i restart the registry container, docker login this registry is ok
when i pull some image, the core log to 401 error 
![image](https://user-images.githubusercontent.com/22125180/84739862-f4a0c980-afde-11ea-84cd-c09beba64d3f.png)

emm, how can i to chanange the auth to htpasswd,thanks

**Comment by reasonerjt** [comment]
Core makes API call to registry, you need to update the code to make sure the authn works.

There are a lot of details you have to figure out by getting familiar with the code.

**Comment by mzzgaopeng** [comment]
> b

when I change the registry auth to htpasswd, then   core  server auth log 401 error

**Comment by mzzgaopeng** [comment]
> Core makes API call to registry, you need to update the code to make sure the authn works.
> 
> There are a lot of details you have to figure out by getting familiar with the code.

when I change the registry auth to htpasswd, then core server auth log 401 error

**Comment by mzzgaopeng** [comment]
> Core makes API call to registry, you need to update the code to make sure the authn works.
> 
> There are a lot of details you have to figure out by getting familiar with the code.

the registry auth default is token auth,it mast be use ip/server/token to authentication.
I want not used the token auth,so I change to htpasswd

**Comment by mzzgaopeng** [comment]
why close the issus
