### ISSUE TITLE
oidc-auth.md pictures all are not available

### ISSUE THREAD

**Issue by hobbytp** [goharbor/harbor#12244]
All the pictures in this [link](https://github.com/goharbor/harbor/blob/master/docs/administration/configure-authentication/oidc-auth.md) are not available, could you please help to fix it?
Thanks,

**Comment by ninjadq** [comment]
@hobbytp you can access it in this [link](https://goharbor.io/docs/2.0.0/administration/configure-authentication/oidc-auth/)

**Comment by ninjadq** [comment]
We will fix it in next version
