### ISSUE TITLE
If use ldap as the Auth Mode,  How do I delete a user? 

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12241]
If use ldap as the Auth Mode, How do I delete a user? 
harbor version:  1.10.

![harbor2](https://user-images.githubusercontent.com/50136484/84722837-e8087b00-afb6-11ea-8024-ae098bdf492f.png)

![harbor1](https://user-images.githubusercontent.com/50136484/84722868-f35ba680-afb6-11ea-8775-e7e8577e9012.png)

**Comment by jonhatallasf** [comment]
https://github.com/goharbor/harbor/issues/8424

**Comment by ninjadq** [comment]
dup to #8424
