### ISSUE TITLE
Missing chartrepo operations api in legacy_swagger.yaml

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#12252]
No definition for  chartrepo operations in legacy_swagger.yaml, like get chartrepo and delete chartrepo.
And also in  file legacy_swagger.yaml, there are useless API definitions as below:

    POST /chartrepo/{repo}/charts/{name}/{version}/labels
    GET  /chartrepo/{repo}/charts/{name}/{version}/labels
    DELETE /chartrepo/{repo}/charts/{name}/{version}/labels/{id}

![image](https://user-images.githubusercontent.com/44018302/84742951-d2f61100-afe3-11ea-8b9f-17a99becd217.png)

**Comment by hxquangnhat** [comment]
Hi, this is still missing in v2.0.1
