### ISSUE TITLE
Logs pages don't load in Firefox, raises JS error for date convertion

### ISSUE THREAD

**Issue by nielsslot** [goharbor/harbor#12262]
**Expected behavior and actual behavior:**
When using Harbor 2.0.0 with Firefox 77.0.1 on Ubuntu 18.04 I expect the logs (both global and per project) to show. However, when navigating to '/harbor/logs' or '/harbor/projects/ID/logs' it shows a spinner indefinitely.

I can see in the Network tab of the developer tools that HTTP requests are being made to fetch the logs in JSON format. These requests succeed, but an error is printed in the console afterwards:

`ERROR Error: "InvalidPipeArgument: 'Unable to convert "2020-06-16 12:53:15.801768 +0000 UTC" into a date' for pipe 'e'"`

Firefox includes a stack trace. It seems obfuscated, I'm only including the top few lines:

```
    vn https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    transform https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    qb https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    qb https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    qb https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    m_ https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    m https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    updateRenderer https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
    Gb https://harbor.example.com/main.bd2ce62700a1744a95c4.js:1
```

Firefox might pick up my locale, which is set to Dutch:

```
$ env | grep LC
LC_MEASUREMENT=nl_NL.UTF-8
LC_PAPER=nl_NL.UTF-8
LC_MONETARY=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_NUMERIC=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
```
The browser and OS language are set to English.

I can't reproduce this on Chrome 83 running on the same system. The JSON response returned to Chrome seems the same as in Firefox, which makes me think this is a date parsing issue in Firefox.

**Steps to reproduce the problem:**
* Install Harbor 2.0.0
* Perform some action, like a push or pull
* Open the Harbor UI in Firefox 77.0.1 on Ubuntu 18.04
* Navigate to the 'Logs' page
* Notice that the spinner keeps spinning and the logs don't load

**Versions:**

- harbor version: 2.0.0
- docker engine version: 19.03.11
- docker-compose version: 1.24.1

**Comment by adrianovieira** [comment]
Same behavior here on Harbor-2.0.1-rc1

**Comment by AllForNothing** [comment]
@nielsslot Thanks!
For now,  Firefox can't  convert time string  like "2020-06-16 12:53:15.801768 +0000 UTC", we are going to fix it  in next patch version. See #11522 
We strongly recommend Chrome to visit Harbor UI.
I'm closing this issue, and keep #11522 opened
