### ISSUE TITLE
running with docker-compose: docker login 401 Unauthorized

### ISSUE THREAD

**Issue by siredmar** [goharbor/harbor#12271]
Hi!
I'm trying to set up harbor with bitnami images based on `2.0.0-0` (https://github.com/bitnami/bitnami-docker-harbor-portal) with a predefined docker-compose file. I created my own private key and certificate, put and gave them harbor. 

Harbor is reachable in the network:
```
$ ping harbor.lan
PING harbor.lan (192.168.1.107) 56(84) bytes of data.
64 bytes from harbor.lan (192.168.1.107): icmp_seq=1 ttl=64 time=0.018 ms
```
But i cannot `docker login`.
```
docker login http://harbor.lan
Username: admin
Password: <here is the default admin password>
Error response from daemon: login attempt to http://harbor.lan/v2/ failed with status: 401 Unauthorized
```

However, i can manually get a auth token:

```
curl -i -k -u admin:bitnami http://harbor.lan/service/token\?service\=harbor-registry
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 18 Jun 2020 06:04:51 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1105
Connection: keep-alive
Set-Cookie: sid=aa8533c761d19f9850e69f05c2a7b9d5; Path=/; HttpOnly
X-Request-Id: f711be99-ec26-4a33-afd0-9c515cb5a8f4

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1XSlM6V1BMWDozNU83OlVKRkk6SUQ3RDpNT09VOklVTE06 .... 
dZxhzCQc7ozepij6OEPBAhmbHGiGbZZk","access_token":"","expires_in":1800,"issued_at":"2020-06-18T06:04:51Z"}%
```
I can login to the web view, create users, create repositories and so on.
What i can't do is use the registry because the login doesn't work.
I am overseeing something obvious here? 
The only thing changed in the [docker-compose.yml](https://github.com/bitnami/bitnami-docker-harbor-portal/blob/master/docker-compose.yml) is `EXT_ENDPOINT=http://harbor.lan` for core service.

**Comment by beltran-rubo** [comment]
This is a Bitnami specific request, we will try to help you at https://github.com/bitnami/bitnami-docker-harbor-portal/issues/4

**Comment by ninjadq** [comment]
Close it because Bitnami will handle this. You can reopen it if there is something that needs to be solved in harbor.
