### ISSUE TITLE
will return 403 even I am admin

### ISSUE THREAD

**Issue by zhangguanzhang** [goharbor/harbor#12273]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

```shell
$ curl -L -u admin:'xxxxx'  https://harbor-local.xxxxx.com/api/projects/1/members/1/
{"code":403,"message":"admin"}
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [v1.8.1-16b59c41]
```text
    image: goharbor/harbor-log:v1.10.3
    image: goharbor/registry-photon:v2.7.1-patch-2819-v1.10.3
    image: goharbor/harbor-registryctl:v1.10.3
    image: goharbor/harbor-db:v1.10.3
    image: goharbor/harbor-core:v1.10.3
    image: goharbor/harbor-portal:v1.10.3
    image: goharbor/harbor-jobservice:v1.10.3
    image: goharbor/redis-photon:v1.10.3
    image: goharbor/nginx-photon:v1.10.3

```

**Additional context:**

https://github.com/goharbor/harbor/blob/16b59c41cdbe56fdd6a61e6794621885198edebe/src/core/api/projectmember.go#L96

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
`/var/log/harbor/core.log`
```
Jun 18 17:43:28 172.19.0.1 core[1205]: 2020-06-18T09:43:28Z [ERROR] [/common/api/base.go:69]: GET /api/projects/1/members/1 failed with error: {"code":403,"message":"admin"}
Jun 18 17:43:28 172.19.0.1 core[1205]: 2020/06/18 09:43:28 #033[1;44m[D] [server.go:2619] |     10.0.6.181|#033[43m 403 #033[0m|  17.111492ms|   match|#033[44m GET     #033[0m /api/projects/1/members/1   r:/api/projects/:pid([0-9]+)/members/?:pmid([0-9]+)#033[0m
```

**Comment by 7error** [comment]
try curl -L -u "amin: xxxxx"

**Comment by zhangguanzhang** [comment]
> try curl -L -u "amin:xxxxx"

see my command  in  the  first comment

**Comment by zhangguanzhang** [comment]
> try curl -L -u "amin:xxxxx"

not this, it will work  in version `v1.5.1` and `v1.10.3`

**Comment by reasonerjt** [comment]
@7error is there really project 1 and member 1?

It is by design to return 403 if the ID does not exist to avoid enumeration attack.

**Comment by zhangguanzhang** [comment]
thanks @7error
