### ISSUE TITLE
GCR replication does not work with patterns

### ISSUE THREAD

**Issue by beltran-rubo** [goharbor/harbor#12275]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Trying to replicate a full catalog in GCR e.g. folder/** the replication job finishes with a success but 0% replicated. It is not able to get all the image names & tags there.

If I specify the name of the container, it is able to replicate all the tags.

<img width="1523" alt="Screenshot 2020-06-18 at 18 17 51" src="https://user-images.githubusercontent.com/3718440/85046178-57859280-b190-11ea-81ed-e6d3a7812931.png">
<img width="676" alt="Screenshot 2020-06-18 at 18 17 39" src="https://user-images.githubusercontent.com/3718440/85046183-594f5600-b190-11ea-8fb5-d1d363e31883.png">

**Steps to reproduce the problem:**
Configure a GCR registry with a _json_key and try to replicate a catalog with more than one image name.

**Versions:**
- Harbor version: 2.0.0
- Deployed in a GKE cluster

**Comment by ninjadq** [comment]
could you provide the logs of your replication and jobservice?

**Comment by beltran-rubo** [comment]
There is no log, just the "no resources needed to be replicated". In the jobservice log I can only see those entries:

```
2020-06-19T05:54:28Z [DEBUG] [/jobservice/api/handler.go:278]: Serve http request 'GET /api/v1/stats': 200 {"worker_pools":[{"worker_pool_id":"b99c02be32ffba58f11e3c84","started_at":1592496317,"heartbeat_at":1592546066,"job_names":["DEMO","IMAGE_GC","IMAGE_REPLICATE","IMAGE_SCAN","IMAGE_SCAN_ALL","REPLICATION","RETENTION","SCHEDULER","SLACK","WEBHOOK"],"concurrency":10,"status":"Healthy"}]}
```

**Comment by ninjadq** [comment]
oh, I find that your name is only `demo/**`. You may need to add the URL of gcr in front of your source Name. In this case, try to use `gcr.io/demo/**`

**Comment by beltran-rubo** [comment]
Same issue: `no resources needed to be replicated`

**Comment by ninjadq** [comment]
`project-id-xxx` need to replaced by your own project name in gcr.
for example
![image](https://user-images.githubusercontent.com/1069785/85131757-00ec8700-b26a-11ea-9286-2c99911c69f3.png)
in the case of the pic, your project id is`eminent-nation-87317`

**Comment by beltran-rubo** [comment]
The same, I am testing this GCR demo registry https://docs.bitnami.com/tanzu-application-catalog/how-to/consume-tac-harbor/#step-1-configure-a-registry You can also configure it the registry and test on your side. Using "sys-2b0109it/demo/bitnami/kafka" works properly and pull all the tags, but not using "sys-2b0109it/demo/bitnami/**".

**Comment by bitsf** [comment]
What permission have you assigned? You can try assign Storage Admin role.

**Comment by beltran-rubo** [comment]
Right, that works. Do you know why it is required to have "Storage Admin" role there to just list the containers in the registry? I am concerned about the security implications.

**Comment by steven-zou** [comment]
@bitsf 

If it is not a code issue, could you please add it as a [FAQ](https://github.com/vmware/harbor/wiki/Harbor-FAQs)?

**Comment by bitsf** [comment]
https://cloud.google.com/container-registry/docs/access-control
![image](https://user-images.githubusercontent.com/188115/85589233-fc630c80-b675-11ea-8ddf-286682111cb2.png)

**Comment by bitsf** [comment]
Let me explain more, when using * pattern, we need to call GCR Api to list the artifacts, but if not using * pattern, it will just call registry pull Api, which need less permission.
Anyway, just give enough permission as Google Doc suggest.

**Comment by beltran-rubo** [comment]
Probably "Storage Object Viewer" should be enough. It is more restricted and allow Harbor to list & get the objects in the registry.
