### ISSUE TITLE
/repositories/{repo_name}/tags shuold add the page_size in the url params

### ISSUE THREAD

**Issue by zhangguanzhang** [goharbor/harbor#12279]
**Is your feature request related to a problem? Please describe.**
`/repositories/{repo_name}/tags` always return the all tags, I am the version `v1.10.3`

shuold add the `page_size`  in the url query params

**Comment by ninjadq** [comment]
It's because in Harbor 1.10.x the tags info is requested from docker distribution which does not provide pagination feature. But In harbor 2.0 tags info is stored in Harbor DB. You can refer the API doc to get tags with pagination

**Comment by zhangguanzhang** [comment]
I think it's possible to determine whether the page_size parameter exists or not, and return all if it doesn't

**Comment by ninjadq** [comment]
In harbor 1.10.x, you can paginate the tags in frontend. If you use API to get tags

**Comment by zhangguanzhang** [comment]
I turned on the Network option in the browser's F12, and looked at all the returns from the API interface called below, not the real page-turning

**Comment by ninjadq** [comment]
You can try Harbor 2.0. In which There are tags pagination feature

**Comment by zhangguanzhang** [comment]
`v1.x` aren't you going to continue with the update? I reviewed the swagger documentation for `v2.0` and the API list is pretty sparse

**Comment by ninjadq** [comment]
@zhangguanzhang yes, new features that will cause API change are no longer supported in 1.x
