### ISSUE TITLE
Frequent harbor core failures 

### ISSUE THREAD

**Issue by ajayk** [goharbor/harbor#12278]
**Expected behavior and actual behavior:**
On a Harbor installation (Kubernetes using harbor-helm), I'm seeing the following timeouts for few requests intermittently on the core server:

**Steps to reproduce the problem:**
Harbor 1.10 was upgraded to harbor 2.0.0.

**Versions:**
Please specify the versions of following systems.
- harbor version: 2.0.0
- helm chart version - harbor-1.4.0                      	
- docker engine version: 18.9.9
- Kubernetes: 1.16.8

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
```
harbor      17m         Warning   Unhealthy                pod/harbor-harbor-core-f4fd6dddc-gwpbq   Readiness probe failed: Get http://10.161.52.119:8080/api/v2.0/ping: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
harbor      48m         Warning   Unhealthy                pod/harbor-harbor-core-f4fd6dddc-ddfqb   Readiness probe failed: Get http://10.161.34.105:8080/api/v2.0/ping: net/http: request canceled (Client.Timeout exceeded while awaiting header
```

**Comment by ninjadq** [comment]
Could you provide more details like provides the log files?

**Comment by ajayk** [comment]
@ninjadq is there a private way of sharing the logs
