### ISSUE TITLE
Docker Trust Signer Failure / Docker Push failure

### ISSUE THREAD

**Issue by nijamashruwala** [goharbor/harbor#12276]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Background: I am a Project Admin
Expected: Able to add signer and push images
Actual: 500 error, unsure what's wrong with the notary service

**Steps to reproduce the problem:**
### Pull a test image
[me] ~ $ docker pull alpine
### Tag image to upload
[me] ~ $ docker tag alpine <server where notary is running>:4443/docker/alpine:latest
### Generate a key
[me] ~ $ docker trust key generate harbor-alpha-alpine-test
### Login to the server
[me] ~ $ docker login <server where notary is running>
Authenticating with existing credentials...
Login Succeeded
### Add the key -- this fails
[me] ~ $ docker trust signer add harbor-alpha-alpine-test <server where notary is running>:4443/docker/alpine:latest --key ~/harbor-alpha-alpine-test.pub
Adding signer "harbor-alpha-alpine-test" to <server where notary is running>:4443/docker/alpine:latest...
Error: error contacting notary server: received unexpected HTTP status: 500 Internal Server Error
Failed to add signer to: <server where notary is running>:4443/docker/alpine:latest
### Notary pods exist and are running
[me] ~ $ k get pods |grep -i notary
harbor-alpha-harbor-notary-server-5b947d9cf6-q5bct   1/1     Running   0          47h
harbor-alpha-harbor-notary-signer-769cf4b6b9-2t428   1/1     Running   0          47h
### Ingress exists
[me] ~ $ k get ingresses |grep -i notary
harbor-alpha-harbor-ingress-notary   notary-alpha.build-usw2.k8s.platform.einstein.com   a5832f63e4ec1457c90d7d85070d983b-181089916.us-west-2.elb.amazonaws.com   80, 443   2d

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.0
- docker engine version: 19.03.8
- docker-compose version: 1.26.0-rc4, build d279b7a8

**Additional context:**

- **Harbor config files:
### Sanitized config file
---
notary:
  secretName: ""
  enabled: true
expose:
  type: ingress
  tls:
    enabled: true
    secretName: "harbor-core-tls"
    notarySecretName: "harbor-notary-tls"
  ingress:
    hosts:
      core: harbor-alpha.<my domain>.com
      notary: notary-alpha.<my domain>.com
    controller: default
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx-protected

    tls:
    - secretName: harbor-core-tls
      hosts:
        - harbor-alpha.<my domain>.com
    - secretName: harbor-notary-tls
      hosts:
        - notary-alpha.<my domain>.com

externalURL: https://harbor-alpha.<my domain>.com

persistence:
  enabled: true
  imageChartStorage:
    type: s3
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 10Gi
    chartmuseum:
      size: 10Gi
    jobservice:
      size: 10Gi
    database:
      size: 10Gi
    redis:
      size: 5Gi

imagePullPolicy: IfNotPresent

logLevel: debug

portal:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

core:
  replicas: 5
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

jobservice:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

redis:
  type: external
  external:
    host: "redis-master.harbor-alpha.svc.cluster.local"
    port: "6379"
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    chartmuseumDatabaseIndex: "3"
    clairAdapterIndex: "4"
    trivyAdapterIndex: "5"
    password: "BD2iMSY0N0"

registry:
  replicas: 3
  registry:
    resources:
     requests:
       memory: 256Mi
       cpu: 100m
  controller:
    resources:
     requests:
       memory: 256Mi
       cpu: 100m

database:
  maxOpenConns: 999
  internal:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
is there any error logs in notary pod？

**Comment by nijamashruwala** [comment]
@ninjadq Nothing but the 500 error going out

**Comment by reasonerjt** [comment]
@nijamashruwala please provide the complete logs of different pods if you reproduce this problem.
If the request reached notary pod there should be errors otherwise the 500 was returned by som proxy depending on your env.
