### ISSUE TITLE
harbor 2.0: Artifacts are not sortable by tag, size, or vulns.

### ISSUE THREAD

**Issue by rayisbadat** [goharbor/harbor#12277]
**Expected behavior and actual behavior:**
Actual behavior: columns Artifacts,tag, size, vuln, annotation, nor labels are sort-able.
Expected:  At least tag,size, and vuln should be sort-able.  Especially since tag is the most common identifier.

**Steps to reproduce the problem:**
1) Goto Projects>Repositories , select a repo with lots of images/artifacts.  I used a rabbitmq sync.  
2) Click the column headers and see that no sort functionality exists.
<img width="870" alt="Screen Shot 2020-06-18 at 3 59 26 PM" src="https://user-images.githubusercontent.com/1338507/85071990-f5239680-b17d-11ea-8713-2e4cbe49885e.png">

**Versions:**
- harbor version: v2.0.0-87602132

**Additional context:**
* Deployed harbor 2.0.0 from harbor-helm.
* This was a test upgrade of our dev instance from 1.9.

**Comment by AllForNothing** [comment]
@xaleeks @rayisbadat 
Not a bug. Currently, sorting is not supportted, we can add sorting functiong in the future
