### ISSUE TITLE
chartmuseum failed 

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#12272]
when i install harbor 2.0.0 with ./install.sh  --with-chartmuseum, i checked core.log found :
 [ERROR] [/core/api/project.go:435]: populate project properties failed get chart count of project 82 failed: get content failed: send request GET /docker/index.yaml failed: Get http://chartmuseum:9999/docker/index.yaml: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by ninjadq** [comment]
could you provide more context like what operation you did and the logs of other components like chartmuseum?

**Comment by jonhatallasf** [comment]
When listing projects, I have also gotten this message
