### ISSUE TITLE
POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12296]
**Steps to reproduce the problem:**

My habor structures
nginx:443 -> harbor1 host (192.168.200.4:80) / harbor2 host (192.168.210.13:80)
two harbor host have same external db , redis, data storage(oss)

i use  browser access  http://192.168.200.4/harbor/configs  auth
set LDAP Search Password  , save ,  test ldap server is ok
/var/log/harbor/core.log  no error 

but i use  browser access http://192.168.210.13/harbor/configs  auth
test ldap server ,  not ok,  I find  these error in  harbor2 (192.168.210.13)

tail -f /var/log/harbor/core.log 
[ERROR] [/common/api/base.go:233]: LDAP connect fail, error: LDAP Result Code 49 "Invalid Credentials": 
[ERROR] [/common/api/base.go:73]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

so i set LDAP Search Password in http://192.168.210.13/harbor/configs  auth
set LDAP Search Password  , save ,  test ldap server is ok
/var/log/harbor/core.log  no error 

but i use  browser access http://192.168.210.13/harbor/configs  auth
test ldap server ,  not ok,  same error in  harbor1 (192.168.200.4)

[ERROR] [/common/api/base.go:233]: LDAP connect fail, error: LDAP Result Code 49 "Invalid Credentials": 
[ERROR] [/common/api/base.go:73]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

over and over again, How to solve this?

**Versions:**

- harbor version: 1.10.3
- docker engine version:  19.03.11
- docker-compose version: 1.26

**Comment by 7error** [comment]
read this post http://bbs.chinaunix.net/thread-1674895-1-1.html

**Comment by fz8770** [comment]
> read this post http://bbs.chinaunix.net/thread-1674895-1-1.html

Yes, I think it's a password error, but no matter how I set the password,   test server is always wrong on the other host.

**Comment by fz8770** [comment]
> read this post http://bbs.chinaunix.net/thread-1674895-1-1.html

hello , I'm Chinese. Are you Chinese, too?  Can  add a weixin or qq?

**Comment by fz8770** [comment]
In my tests, this is a bug, on one host browser harbor/configs auth  enter  ldap search password, save, click test ldap server ok, but   other host browser harbor/configs , click test ldap server faild 

two host all Save ldap password, no click test ldap server
exit admin, Saved first ldap password host can use ldap user login, other host can not login. 

not login host logs error 

Use your browser's debugging tool,   one host browser harbor/configs  auth  enter  ldap search password,    click test ldap server ok,  reponse can look  ldap_search_password vaule  , save,   Click again test ldap server,  reponse have not  ldap_search_password vaule
