### ISSUE TITLE
Harbor v1.10.3 : authorization token required

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12290]
What can we help you?

I have installed Harbor v1.10.3 but I got these errors in the registry.log. I don't have any issue for pulling/pushing images.

error authorizing context: authorization token required

My habor structures
nginx:443 ->  harbor1 host (192.168.0.1:80)  / harbor2 host (192.168.0.2:80)

two harbor  host  user  hostname is  harbor.domain.cn in harbor.yaml 

How to solve this?

cat /var/log/harbor/registry.log | grep -i error
``
Jun 19 21:13:05 172.26.0.1 registry[1417]: time="2020-06-19T13:13:05.278965866Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=5a9fa043-f882-4cf9-8a85-00bc3bbd7b5b http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" 
Jun 19 21:13:09 172.26.0.1 registry[1417]: time="2020-06-19T13:13:09.119672417Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=056fa9c2-7b0e-4366-ac2e-260bcb2415dd http.request.method=HEAD http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/test/tomcat/blobs/sha256:612a9f566fdc082f9d43f642791723e34bab94c243b34a965b4602d416ee7a72" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" vars.digest="sha256:612a9f566fdc082f9d43f642791723e34bab94c243b34a965b4602d416ee7a72" vars.name="test/tomcat" 
Jun 19 21:13:09 172.26.0.1 registry[1417]: time="2020-06-19T13:13:09.120846432Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=9964384e-a596-48fe-93bf-bcf001fc11b1 http.request.method=HEAD http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/test/tomcat/blobs/sha256:e99c920870d7c775d4be5b39e979c47870f40f50b2ef3c42ad32b7a1d657953d" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" vars.digest="sha256:e99c920870d7c775d4be5b39e979c47870f40f50b2ef3c42ad32b7a1d657953d" vars.name="test/tomcat" 
``

**Comment by 7error** [comment]
your harbor nginx behind an external proxy（nginx443）, I suggest you config external_url in your  harbor.yaml

**Comment by fz8770** [comment]
> 您的Harbor Nginx位于外部代理（nginx443）之后，建议您在Harbor.yaml中配置external_url

How to use external_url  prot?  I'm... confused. please tell me, thanks.

external_url: https://reg.mydomain.com:8433 ? 
external_url: https://reg.mydomain.com:443 ?

**Comment by 7error** [comment]
external_url is the address where you expect to expose the Internet. in your case it will https://reg.mydomain.com, port ignore if 443

**Comment by fz8770** [comment]
> external_url是您希望公开Internet的地址。在您的情况下，它将是https://reg.mydomain.com，如果443，则端口将忽略

thanks,  I'll try.

**Comment by fz8770** [comment]
I'm already add it in harbor.yml 

\# Uncomment external_url if you want to enable external proxy
\# And when it enabled the hostname will no longer used
external_url: https://harbor.domain.cn


 I try pushing  imags ,  don't have any issue. but aslo error

cat /var/log/harbor/registry.log | grep -i error | tail -n 10
``
Jun 19 22:17:10 172.28.0.1 registry[1417]: time="2020-06-19T14:17:10.097213212Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=f401a2e4-068b-49d0-84df-a54e9a387bdc http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" 
Jun 19 22:18:27 172.28.0.1 registry[1417]: time="2020-06-19T14:18:27.367703144Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=4eae9beb-9600-40f7-b538-1011ccbf86e8 http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" 
Jun 19 22:44:15 172.30.0.1 registry[1417]: time="2020-06-19T14:44:15.69488832Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=792d5c87-efad-401a-bc6a-89e3e7c25369 http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))"
``

**Comment by 7error** [comment]
Did you redo the step prepare after change harbor.yml，and docker-compose down && docker-compose up ?

**Comment by fz8770** [comment]
> Did you redo the step prepare after change harbor.yml，and docker-compose down && docker-compose up ?

yes,  My operation

``
docker-compose down -v
vim harbor.yml   # add  external_url: https://harbor.domain.cn
./prepare --with-chartmuseum
sed -i 's/proxy_set_header X-Forwarded-Proto \$scheme;/#proxy_set_header X-Forwarded-Proto \$scheme;/g' common/config/nginx/nginx.conf
docker-compose up -d
``

**Comment by fz8770** [comment]
I try pull nginx image  ,  There seems to be some new errors.

level=error msg="response completed with error"
level=error msg="response completed with error" auth.user.name=denis.fang err.code="blob unknown" err.


cat  /var/log/harbor/registry.log | grep -i error | tail -n 3

``
Jun 19 23:21:26 192.168.0.1 registry[1417]: time="2020-06-19T15:21:26.303513488Z" level=error msg="response completed with error" auth.user.name=denis.fang err.code=unknown err.detail="Aliyun API Error: RequestId: NWVlY2Q3ZjZfOGMyMDQzNjRfMTI5NTJfMzdlMjg5YQ== Status Code: 400 Code: MalformedXML Message: The XML you provided was not well-formed or did not validate against our published schema." err.message="unknown error" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=b89f1d94-6ac7-4c9d-bdc5-8e47f175afc3 http.request.method=PUT http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/test/nginx/blobs/uploads/c95a2d5c-e9ce-4719-b0af-b0ee1408cb26?_state=LbeCZlAJLUQy5pLDmOQf7x10TlFf5KlMekYAsVNq_iF7Ik5hbWUiOiJ0ZXN0L25naW54IiwiVVVJRCI6ImM5NWEyZDVjLWU5Y2UtNDcxOS1iMGFmLWIwZWUxNDA4Y2IyNiIsIk9mZnNldCI6MjcwOTgyNjUsIlN0YXJ0ZWRBdCI6IjIwMjAtMDYtMTlUMTU6MjE6MDlaIn0%3D&digest=sha256%3A8559a31e96f442f2c7b6da49d6c84705f98a39d8be10b3f5f14821d0ee8417df" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=232.674532ms http.response.status=500 http.response.written=298 vars.name="test/nginx" vars.uuid=c95a2d5c-e9ce-4719-b0af-b0ee1408cb26 
Jun 19 23:21:45 192.168.0.1 registry[1417]: time="2020-06-19T15:21:45.971591745Z" level=error msg="response completed with error" auth.user.name=denis.fang err.code="blob unknown" err.detail=sha256:2622e6cca7ebbb6e310743abce3fc47335393e79171b9d76ba9d4f446ce7b163 err.message="blob unknown to registry" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=b90e71a7-415a-4d44-b683-df666a82c073 http.request.method=HEAD http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/test/nginx/blobs/sha256:2622e6cca7ebbb6e310743abce3fc47335393e79171b9d76ba9d4f446ce7b163" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=37.620002ms http.response.status=404 http.response.written=157 vars.digest="sha256:2622e6cca7ebbb6e310743abce3fc47335393e79171b9d76ba9d4f446ce7b163" vars.name="test/nginx" 
Jun 19 23:21:56 192.168.0.1 registry[1417]: time="2020-06-19T15:21:56.244060971Z" level=error msg="response completed with error" auth.user.name=harbor-core err.code="manifest unknown" err.detail="unknown tag=latest" err.message="manifest unknown" go.version=go1.13.8 http.request.host="registry:5000" http.request.id=0e3c2e0a-3b9b-48ce-98e6-b96c54201795 http.request.method=HEAD http.request.remoteaddr="192.168.0.6:36044" http.request.uri="/v2/test/nginx/manifests/latest" http.request.useragent=harbor-registry-client http.response.contenttype="application/json; charset=utf-8" http.response.duration=29.026489ms http.response.status=404 http.response.written=96 vars.name="test/nginx" vars.reference=lates
``

**Comment by 7error** [comment]
check
1、does your machine(harbor1 host) can access harbor.domain.cn to your nginx443 (DNS config)
2、cat common/config/registry/config.yml
3、does your two instance has the same token config in common config? because you have two instance deploy , It's getting more complicated，can you try first 443 proxy only one instance

**Comment by fz8770** [comment]
1、does your machine(harbor1 host) can access harbor.domain.cn to your nginx443 (DNS config)

How check? 

2、cat common/config/registry/config.yml

harbor1 host and harbor2 is same realm

auth:
  token:
    issuer: harbor-token-issuer
    realm: https://harbor.domain.cn/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

3、does your two instance has the same token config in common config? 

yes, 

two instance , in harobor.yaml 

my set  same host name: harbor.domain.com
same external_url: https://harbor.domain.cn

If this is wrong, how do I change it?

**Comment by 7error** [comment]
I suggest first try a single instance to go through the whole process.Duplicate of #12229

**Comment by 7error** [comment]
Duplicate of #12229，I suggest first try a single instance to go through the whole process

**Comment by 7error** [comment]
some tokens are generated random after prepare step,so you have two instance but the token are not same.

**Comment by fz8770** [comment]
> 一些令牌是在准备步骤后随机生成的，因此您有两个实例，但令牌并不相同。

thanks , What should I do? 
I'm confused

harbor1 host and harbor2  is  internal ip host  (192.168.200.4 / 192.168.210.13)
how set host name and external_url for them ?

if set it ,  right ?
harbor1 host  host name  192.168.200.4 ?  external_url  https://harbor.domain.cn
harbor2 host  host name  192.168.210.13 ?  external_url  https://harbor.domain.cn

My Access Address   https://harbor.domain.cn

**Comment by fz8770** [comment]
> some tokens are generated random after prepare step,so you have two instance but the token are not same.

> 
> thanks , What should I do?
> I'm confused
> 
> harbor1 host and harbor2 is internal ip host (192.168.200.4 / 192.168.210.13)
> how set host name and external_url for them ?
> 
> if set it like this , right ?
> harbor1 host host name 192.168.200.4 ? external_url https://harbor.domain.cn
> harbor2 host host name 192.168.210.13 ? external_url https://harbor.domain.cn
> 
> My Access Address https://harbor.domain.cn
> 
> or must be set extranet ip for harbor1 host and harbor2 ?
> host name set extranet ip ?

**Comment by fz8770** [comment]
> but the token are not same.

or  How can let them have same token ?

**Comment by fz8770** [comment]
> I suggest first try a single instance to go through the whole process

i try a single instance to go through the whole process. 
docker-compose down harbor1 host ,  Open only harbor1 host (192.168.210.13),  but alse error

I pushed  nginx image , don't have any issue.
There seems to be some new errors in registry.log

Jun 20 05:56:38 192.168.64.1 registry[1417]: time="2020-06-19T21:56:38.940972039Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=9437fdac-a7fd-4fc8-bb84-849cf31e61df http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" 

Jun 20 05:56:54 192.168.64.1 registry[1417]: time="2020-06-19T21:56:54.78171078Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=7a47f321-a6ca-45ec-b2cd-cdf6c23605cc http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))"

**Comment by fz8770** [comment]
My questionlike https://github.com/goharbor/harbor/issues/7197

**Comment by 7error** [comment]
did you try redo docker logout and docker login for a new session

**Comment by 7error** [comment]
You may need to read this https://tonybai.com/2017/06/15/fix-auth-fail-when-login-harbor-registry/

**Comment by fz8770** [comment]
> did you try redo docker logout and docker login for a new session

yes , my clicent docker logout  && docker login
I pushed nginx image , don't have any issue.
still error  in registry.log

i try a single instance to go through the whole process.
docker-compose down harbor1 host , Open only harbor1 host (192.168.210.13)

cat /var/log/harbor/registry.log  | grep -i error | tail -n 3 | grep -i error

Jun 20 09:32:24 172.23.0.1 registry[1417]: time="2020-06-20T01:32:24.719606844Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=d0c4189f-541c-469b-89e9-7bc77650eec7 http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))" 

Jun 20 09:33:02 172.23.0.1 registry[1417]: time="2020-06-20T01:33:02.135107838Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=b769a04f-e853-4d2c-985c-7a6dd488fa1c http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))"

**Comment by fz8770** [comment]
> You may need to read this https://tonybai.com/2017/06/15/fix-auth-fail-when-login-harbor-registry/

thanks , I try it.

**Comment by 7error** [comment]
if push pull use ok, this can be ignore, look https://github.com/goharbor/harbor/issues/7780

**Comment by fz8770** [comment]
> if push pull use ok, this can be ignore, look #7780
> 
> this is a warn level info,if you do not want see this warn log, config registry/config.yml log:--->level: error

My question like https://github.com/goharbor/harbor/issues/7197

**Comment by fz8770** [comment]
> You may need to read this https://tonybai.com/2017/06/15/fix-auth-fail-when-login-harbor-registry/

harbor1 host 
[root@harbor1 harbor1.10.3]# ls common/config/registry/root.crt
common/config/registry/root.crt
[root@harbor1 harbor1.10.3]# find . -name root.crt
./common/config/registry/root.crt
[root@harbor1 harbor1.10.3]# find . -name private_key.pem
[root@harbor1 harbor1.10.3]# find / -name private_key.pem
/data/harbor/data/secret/core/private_key.pem
/data/docker/overlay2/7ab9485d9c6dd02a4d5695d6da3988664362ebd89d0108de008c02beee07adbc/diff/etc/core/private_key.pem
/data/docker/overlay2/7ab9485d9c6dd02a4d5695d6da3988664362ebd89d0108de008c02beee07adbc/merged/etc/core/private_key.pem
/data/docker/volumes/disable/_data/secret/core/private_key.pem

Which private_key.pem  should I copy to harbor2 host? 

no find common/config/ui/private_key.pem

**Comment by fz8770** [comment]
> You may need to read this https://tonybai.com/2017/06/15/fix-auth-fail-when-login-harbor-registry/

i try  Copy these files to harbor2 host 
scp /data/harbor/data/secret/registry/root.crt root@192.168.210.13:/data/harbor/data/secret/registry/root.crt
scp /data/harbor/data/secret/core/private_key.pem  root@192.168.210.13:/data/harbor/data/secret/core/private_key.pem
scp /data/harbor/data/secret/keys/secretkey  root@192.168.210.13:/data/harbor/data/secret/keys/secretkey

$ docker-compose down -v
$ docker-compose up -d

still error in registry.log

Jun 20 12:53:02 172.27.0.1 registry[1417]: time="2020-06-20T04:53:02.847000012Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.13.8 http.request.host=harbor.domain.cn http.request.id=af28602b-330d-4e27-a0fa-70cf393fb3bb http.request.method=GET http.request.remoteaddr=180.162.12.67 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.4.216-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(linux\))"

**Comment by 7error** [comment]
Did you config external_database and external_redis in harbor.yml to share your session and db for your two instance ?

**Comment by fz8770** [comment]
> 您是否在Harbor.yml中配置了external_database和external_redis以共享您的两个实例的会话和数据库？

yes ,  2 harbor host  have same external share db , redis, data storage(oss)

Now, I find  another problem.  look https://github.com/goharbor/harbor/issues/12296
I'm not sure if it's a bug .
