### ISSUE TITLE
Make it a default that robot accounts are not allowed to push or allow to set this per instance

### ISSUE THREAD

**Issue by zimmski** [goharbor/harbor#12297]
When i create a robot account for a customer, i always have to uncheck the "push" option. A customer should not be able to push images and we do not want to make a project public so everyone can pull images. The problem is, that one can "forget" to uncheck the "push" option. That is very bad and practically a security problem.

The easiest solution is therefore to simply make it a default in the Harbor source code to not check "push" and someone who wants a robot account to push, needs to check it.

Another solution would be to introduce an instance configuration that makes this "unchecked push for robot accounts" a default, i.e. every administrator of a Harbor instance can decide on the default behavior instead of the predefined one.

Since the description ask for a screenshot: I think the "Create Robot Account" should look like this:
![Screenshot_20200620_122250](https://user-images.githubusercontent.com/1847950/85199548-c4b03980-b2f0-11ea-8bae-d0d5a712f747.png)

I am sure that there are many robot accounts created with Harbor in this world, that should not push. Please make the default therefore secure by default.

**Comment by xaleeks** [comment]
There are too many instance level configs in ymls as it is, I don't think this warrants another one.  However, I want to point out that far more users have wanted the ability to push images than to block pushes and we can't satisfy everyone.  Unfortunately, looks like you're stuck having to uncheck the box if you want to block pushes for the time being

**Comment by zimmski** [comment]
@xaleeks what about introducing an instance-configuration so one can change the default? This is basically a configuration option for a template-condition to maintain. Nothing that really changes the logic of some critical part of Harbor. If i do a PR for that is that something that would get merged? I want to avoid the scenario of having us forking Harbor.

**Comment by wy65701436** [comment]
you can try with the robot v2 and it's possible to specify permission when to issue an new robot with API.
