### ISSUE TITLE
Logs does not show log entries because of exception "InvalidPipeArgument"

### ISSUE THREAD

**Issue by zimmski** [goharbor/harbor#12299]
When I go to the "Logs" page the page shows a loading indicator forever because in reality there was an exception and the data cannot be shown anymore. So there are two problems:

1. If there is an exception, the UI should tell the user that something went wrong.
2. The following exception is in my browser console: "ERROR Error: "InvalidPipeArgument: 'Unable to convert "2020-06-20 13:07:40.209079 +0000 UTC" into a date' for pipe 'e'""

- harbor version: v2.0.1-aa8bd64b
- browser: 77.0.1 (64-bit) linux openSUSE Tumbleweed

**Comment by zimmski** [comment]
@ninjadq i would mark this as a bug, because the default content of the logs makes the whole log page unusable: no logs are shown. I currently look at the HTTP response contet to see the logs. I cannot use the UI.

**Comment by zimmski** [comment]
@ninjadq i would mark this as a bug, because the default content of the logs makes the whole log page unusable: no logs are shown. I currently look at the HTTP response contet to see the logs. I cannot use the UI.

**Comment by AllForNothing** [comment]
@zimmski Thanks.
For now,  some browser can't convert time string like "2020-06-16 12:53:15.801768 +0000 UTC", we are going to fix it in next patch version. See #11522
We strongly recommend Chrome to visit Harbor UI.
I'm closing this issue, and keep #11522 opened

**Comment by zimmski** [comment]
Wow that must be my worst bug report in my history. Sorry that i forgot to actually write down the browser's name and just posted the version. Will do better next time. Thanks for fixing the problem.
