### ISSUE TITLE
POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12295]
What can we help you?

My habor structures
nginx:443 -> harbor1 host (192.168.200.4:80) / harbor2 host (192.168.210.13:80)
external share db ,  redis, data storage(oss)

i use  browser access  http://192.168.200.4/harbor/configs  auth
set LDAP Search Password  , save ,  test ldap server is ok
/var/log/harbor/core.log  no error 

but i use  browser access http://192.168.210.13/harbor/configs  auth
test ldap server ,  not ok,  I find  these error in  harbor2 (192.168.210.13)

tail -f /var/log/harbor/core.log 
[ERROR] [/common/api/base.go:233]: LDAP connect fail, error: LDAP Result Code 49 "Invalid Credentials": 
[ERROR] [/common/api/base.go:73]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

so i set LDAP Search Password in http://192.168.210.13/harbor/configs  auth
set LDAP Search Password  , save ,  test ldap server is ok
/var/log/harbor/core.log  no error  

but i use  browser access http://192.168.210.13/harbor/configs  auth
test ldap server ,  not ok,  same error in  harbor1 (192.168.200.4)

[ERROR] [/common/api/base.go:233]: LDAP connect fail, error: LDAP Result Code 49 "Invalid Credentials": 
[ERROR] [/common/api/base.go:73]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

over and over again, How to solve this?

Versions:

harbor version: 1.10.3
docker engine version: 19.03.11
docker-compose version: 1.26

**Comment by opswfit** [comment]
您好，你的这个问题解决了么？
