### ISSUE TITLE
what registry_DO_NOT_USE_GC mean in registryctl Dockerfile and registry Dockerfile

### ISSUE THREAD

**Issue by 7error** [goharbor/harbor#12300]
I notice there is a name change 
```bash
COPY ./make/photon/registry/binary/registry /usr/bin/registry_DO_NOT_USE_GC
```
in these files
```bash
https://github.com/goharbor/harbor/blob/v2.0.0/make/photon/registry/Dockerfile#L7
https://github.com/goharbor/harbor/blob/v2.0.0/make/photon/registryctl/Dockerfile#L6
https://github.com/goharbor/harbor/blob/v2.0.0/src/registryctl/api/registry.go#L41
```
And before v2.0 registryctl Dockfer file is /usr/bin/registry，why change name of binary/registry to registry_DO_NOT_USE_GC? Does it have any deep meaning?
```bash
https://github.com/goharbor/harbor/commit/ff2a6c7a0167d3a4698879922644ac8b277d3ce9
```

**Comment by wy65701436** [comment]
Please refer to https://github.com/goharbor/harbor/issues/11606 to get the background, and the reason of renaming it is just want to tell user **DO NOT USE GC** command inside the registy/regsityctl container. Whenever users wants to use GC, just client GC Now or call Harbor GC API to do it.

**Comment by 7error** [comment]
Got it，tks

**Comment by mperez-glic** [comment]
I have a problem with the registry and deletion of blobs..
My Harbor web UI is showing nearly 480G used, but in the filesystem /data (which I have configured in the harbor.yml) I have almost 900G.. Clearly I need to delete some blobs from filesystem.. I looked into a post in medium where it says to run the GC manually, but when I tried to run it from inside the container I got into this.
This is the medium post I refer to
https://medium.com/@shahids89/harbor-container-images-cleanup-automation-1de7cc7c5655

**Comment by KeithTt** [comment]
> Please refer to #11606 to get the background, and the reason of renaming it is just want to tell user **DO NOT USE GC** command inside the registy/regsityctl container. Whenever user wants to use GC, just click GC Now or call Harbor GC API to do it.

Hi, I have clicked GC now on the web, but still didn't release disk space, anything else?
