### ISSUE TITLE
support pushing Windows Containers in full

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12313]
related to this issue https://github.com/goharbor/harbor/issues/11710 which focuses more on a side effect of the requirement in question, we should consider allow pushing foreign layers onto harbor so that Windows containers are pushed in full so to speak

Background:
Docker doesn't push foreign layers, so for ex. it doesn't push the base windows layers (licensing issue, they are not freely distributable).  Windows Server Core images are now hosted on MCR and so are "foreign layers" when pushed to private registries that are implementations of distribution.  It's essentially storing a reference to a Microsoft hosted location so all the pulling and pushing happens remote to harbor, harbor is only acting as a conduit to relay that information.  

But there is way to allow layers to be pushed by force
https://docs.docker.com/engine/reference/commandline/dockerd/#allow-push-of-nondistributable-artifacts

Goal:
We should verify that we can leverage this; meaning we can push windows images to harbor as long as it's switched on in dockerd.  One scenario where just storing references might not be enough and need to push the actual layers would be:  if your goal is to distribute images from your build server (windows) to a set of docker nodes through pushing to harbor first, each of which is pulling from that harbor but are otherwise in an airgapped env.  If you push your foreign layer as a ref only, the production nodes still can't pull it with the reference because they can’t hit the MCR central server 

next step:
if they are pushed, I would assume https://github.com/goharbor/harbor/issues/11710 is moot, that as long as layers are pushed to harbor, quota and image size displayed should resolve perfectly.  If not, we need to indicate to the user the reason for this discrepancy somehow.  Current UI experience is not good enough IMHO.

Impact:
TKGI 1.9 will support windows containers fully and this could be an anticipated experience

**Comment by heww** [comment]
I had tested to push windows images with `allow-nondistributable-artifacts` use the `docker for windows`, and it works with the harbor. The following is detailed information.

1.  Windows Edition and version:  Windows 10 Pro, 1903
2. Docker desktop: 2.3.0.3 (45519)
3. Docker Engine: 19.03.8

The `allow-nondistributable-artifacts` for the docker daemon in the picture.

![image](https://user-images.githubusercontent.com/5634205/87316110-e7ccb280-c557-11ea-8c04-1e9bbabd6da2.png)


Then push a windows image to the harbor, the docker daemon will push the foreign layers to the harbor as normal layers and transform the foreign layers to normal layers in the manifest. The following is the manifest pushed to the harbor with `allow-nondistributable-artifacts`

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1883,
      "digest": "sha256:365a278e3083dfdb08b9a2251d4cda5fe9261e9a0345507279a64244085c6060"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 83746595,
         "digest": "sha256:13b1e189162fa380a056b62d2e3c5159e91c25b4206b6149c736f24cfd0e4e00"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 57769385,
         "digest": "sha256:2e218f520c2b7d3020372147791245b5cfb6aaeb2fda3600005fe34ae095f4c4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1674,
         "digest": "sha256:820bcf206accb2b4a8f0dc15cc291863b0acc4fd959697bafca029c0cafd4e29"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 952,
         "digest": "sha256:13ba9b09a17a569c68431a3958ab6864d347ab8d0410011efe89b9023b747677"
      }
   ]
}
```

And the pushed manifest without `allow-nondistributable-artifacts` to the harbor is like this:

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1883,
      "digest": "sha256:365a278e3083dfdb08b9a2251d4cda5fe9261e9a0345507279a64244085c6060"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 81039739,
         "digest": "sha256:407ada6e90de9752a53cb9f52b7947a0e38a9b21a349970ace15c68890d72511",
         "urls": [
            "https://go.microsoft.com/fwlink/?linkid=860906"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 55958054,
         "digest": "sha256:59774a31bc8e61a8112b0be9d21f5210bded1bfc99ce63cea3dfc18f50e3c89d",
         "urls": [
            "https://go.microsoft.com/fwlink/?linkid=2050873"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1674,
         "digest": "sha256:820bcf206accb2b4a8f0dc15cc291863b0acc4fd959697bafca029c0cafd4e29"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 952,
         "digest": "sha256:13ba9b09a17a569c68431a3958ab6864d347ab8d0410011efe89b9023b747677"
      }
   ]
}
```

So there is nothing that needs to do in the harbor to handle the image pushed by docker for windows with `allow-nondistributable-artifacts`.

**Comment by xaleeks** [comment]
Thanks! @heww

**Comment by heww** [comment]
I had also tested the `allow-nondistributable-artifacts` feature of docker in Windows Server 2019 and it works well.

1. Windows Edition and version: Windows Server 2019,  10.0.18362.0
3. Docker Engine: 19.03.5

![image](https://user-images.githubusercontent.com/5634205/88082973-0d3f6900-cbb5-11ea-8694-4bd454fcae2b.png)

![image](https://user-images.githubusercontent.com/5634205/88083574-ce5de300-cbb5-11ea-965e-c37f1b03ef40.png)

**Comment by reasonerjt** [comment]
Let's make sure it's reflected in the doc.
