### ISSUE TITLE
Impossible to upload images to S3 backend -- Ceph S3 gateway

### ISSUE THREAD

**Issue by bigornoo** [goharbor/harbor#12317]
Hello,
I installed Harbor v2.0 on a Debian 10 and configured an S3 backend for docker images. But I can only send Alpine images. The rest won't pass: 
`« received unexpected HTTP status: 500 Internal Server Error »`

There's nothing anywhere but in the registry logs:
```
" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: NoSuchKey:

level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:e9afc4f90ab09248d75c8081b6dfba749a7f7efdac704ced7e0ceb506e02fa4a err.message="blob unknown to registry" go.version=go1.13.8 http.request.host=myURL http.request.id=a0109576-6f32-44cf-b1ce-5ab973b9d2b9 http.request.method=HEAD http.request.remoteaddr=IP http.request.uri="/v2/test/golang/blobs/sha256:e9afc4f90ab09248d75c8081b6dfba749a7f7efdac704ced7e0ceb506e02fa4a" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=28.217098ms http.response.status=404 http.response.written=157 vars.digest="sha256:e9afc4f90ab09248d75c8081b6dfba749a7f7efdac704ced7e0ceb506e02fa4a" vars.name="test/golang" 

 #011status code: 404, request id: tx000000000000000127a07-005ef0ebab-1e377a49-eu-sxb-1, host id: " err.message="unknown error" go.version=go1.13.8 http.request.host=myURL http.request.id=0b7ad604-e2a6-4d23-b571-d52fb0406981 http.request.method=PUT http.request.remoteaddr=IP http.request.uri="/v2/test/openjdk/blobs/uploads/fb2b8d9c-5240-4373-a5bb-d80bc21b9caa?_state=C-&digest=sha256%3Ab6abafe80f63b02535fc111df2ed6b3c728469679ab654e03e482b6f347c9639" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=452.445344ms http.response.status=500 http.response.written=123 vars.name="test/openjdk" vars.uuid=fb2b8d9c-5240-4373-a5bb-d80bc21b9caa 
```

The S3 we have is not on Amazon but it's a gateway to CEPH. 
Thank you very much for your help.

**Comment by reasonerjt** [comment]
We don't have bandwidth to test ceph S3 gateway.


But this looks like an issue about consistency in storage, the sha256 was written and read right after it but it failed to see it.

Please check it in your setup.

**Comment by axelgobletbdr** [comment]
I am experiencing the same issue. Large layers seem to be the problem, but I have not figured out yet how to solve it.

**Comment by axelgobletbdr** [comment]
I have tracked the issue down further. The problem that occurs is that the registry tries to move an object on S3 that does not yet exist. It therefore crashes. I am able to manually perform the move on s3 at a later moment, and then the container will appear in harbor.

If I am correct harbor is using the default docker registry as registry, so I am going to investigate there further why this is happening and why there are no retries built in.

**Comment by axelgobletbdr** [comment]
The error is occuring when executing the following function in the docker registry: https://github.com/docker/distribution/blob/16128bbac47f75050e82f7e91b04df33775e0c23/registry/storage/blobwriter.go#L295

In the logs I can see that the `Stat` function is called twice, as in this piece of code. It then decided that the file needs to be moved, but somehow it is unable to, because the file is not available yet.

**Comment by axelgobletbdr** [comment]
setting the `storage.s3.multipartcopythresholdsize` in the `config.yml` of the registry to a larger value (e.g. 5368709120) has solved the problem for me. I will incorporate this into https://github.com/axelgobletbdr/harbor-helm as well, as it is not possible to configure this there yet.

**Comment by bigornoo** [comment]
> setting the `storage.s3.multipartcopythresholdsize` in the `config.yml` of the registry to a larger value (e.g. 5368709120) has solved the problem for me. I will incorporate this into https://github.com/axelgobletbdr/harbor-helm as well, as it is not possible to configure this there yet.

Hello, I confirm that the configuration you propose works for me. Thank you very much !

**Comment by DinshKW44** [comment]
time="2020-07-16T17:52:10.669283469Z" level=error msg="response completed with error" auth.user.name=harbor-user err.code="blob unknown" err.detail=sha256:a1125296b23d78a3585a7910d649fbf0cc56284f9d2066e3243e8bc18f90b308 err.message="blob unknown to registry" 

http.response.status=404 http.response.written=157 vars.digest="sha256:a1125296b23d78a3585a7910d649fbf0cc56284f9d2066e3243e8bc18f90b308" vars.name="harbor-user/mongo

@bigornoo @axelgobletbdr  I too am facing the same issue when using s3 ceph as the registry storage. Please may I know what would be optimal values for chunksize, multipartcopychunksize, multipartcopymaxconcurrency, and multipartcopythresholdsize in the registry config.yml when using ceph s3 backend storage.

Also, when I am trying to push an image, it keeps retrying and in the end at times it succeeds or it throws a timeout.

**Comment by axelgobletbdr** [comment]
To me it seems like any multi-part upload fails, no matter what chunk size and concurrency is chosen. Therefore, I set the threshold to the very large number 5368709120. This disables multipart uploading for layers up to 5gb. Unfortunately, there is no option to fully disable it.

**Comment by bigornoo** [comment]
Hi, our account is without tenants. HTH.

**Comment by bitsf** [comment]
reference fix https://github.com/goharbor/harbor-helm/pull/657
