### ISSUE TITLE
Harbor V1.10.3 'New Registry Endpoint' unhealthy issue

### ISSUE THREAD

**Issue by chensp0668** [goharbor/harbor#12329]
While using harbor create 'New Registry Endpoint' unhealthy issue as below: I followed the https cert generation instruction as link:https://goharbor.io/docs/1.10/install-config/configure-https/

The harbor installed successfull,and login to create 'New Registry Endpoint',and show the issue 'registry https://hub.csp.cn is unhealthy: unhealthy',issue detail as below:
Jun 25 11:23:36 172.21.0.1 core[1034]: 2020-06-25T03:23:36Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://hub.csp.cn: Head http://hub.csp.cn/v2/: Get http://hub.csp.cn/v2/: proxyconnect tcp: dial tcp: lookup hub.csp.cn on 127.0.0.11:53: no such host
Jun 25 11:23:36 172.21.0.1 core[1034]: 2020-06-25T03:23:36Z [ERROR] [/common/api/base.go:73]: POST /api/registries failed with error: {"code":400,"message":"registry http://hub.csp.cn is unhealthy: unhealthy"}

I config /harbor/common/config/core/env http=http://hub.csp.cn and https=https://hub.csp.cn,and also do the same config in /harbor/common/config/jobservice/env,and do the operation as below: 
docker-compose down -v 
docker-compose up -d 

The issue can't be fixed. 

Anyone have idea for the issue?

**Comment by 7error** [comment]
you can add extra_hosts  docker-compose.xml
```yaml
  core:
    image: goharbor/harbor-core:v1.10.3
    container_name: harbor-core
    extra_hosts:
      hub.csp.cn: 192.168.1.110
```
make sure you have hosts in your harbor-core container
```bash
docker exec -it harbor-core sh -c "cat /etc/hosts"
```

**Comment by chensp0668** [comment]
> you can add extra_hosts in your docker-compose.xml
> 
> ```yaml
>   core:
>     image: goharbor/harbor-core:v1.10.3
>     container_name: harbor-core
>     extra_hosts:
>       hub.csp.cn: 192.168.1.110
> ```
> 
> make sure you have hosts in your harbor-core container
> 
> ```shell
> docker exec -it harbor-core sh -c "cat /etc/hosts"
> ```

Thanks for your help,I followed your gride,but the issue can't be fixed.
I did the two step and reboot the docker,and the docker-compose.

**Comment by 7error** [comment]
which kind Provider of this New Registry Endpoint did you chose? did you uncheck verify remote cert  ?

**Comment by chensp0668** [comment]
> which kind Provider of this New Registry Endpoint did you chose? did you uncheck verify remote cert ?

I put the Enpoint Url as https://hub.csp.cn,and uncheck or check the remote cert.

**Comment by chensp0668** [comment]
> which kind Provider of this New Registry Endpoint did you chose? did you uncheck verify remote cert ?

I found the harbor demo link 'https://demo.goharbor.io/',the egistry endpoint is ok,the harber version is ' v2.1.0-b803975b'

**Comment by 7error** [comment]
did you config proxy in your env

**Comment by chensp0668** [comment]
> proxyconnect

What your means the proxyconnect in nginx or others?can you show me the more details?thanks a lot.

**Comment by 7error** [comment]
compare your log and mine log
your log ---->
```bash
[ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://hub.csp.cn: Head http://hub.csp.cn/v2/: Get http://hub.csp.cn/v2/: proxyconnect tcp: dial tcp: lookup hub.csp.cn on 127.0.0.11:53: no such host
```
mine log ---->
```bash
[ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://hub.csp.cn: Head http://hub.csp.cn/v2/: Get http://hub.csp.cn/v2/: dial tcp: lookup hub.csp.cn on 8.8.8.8:53: no such host
```
I mean your logs has proxyconnect tcp:  why?

**Comment by chensp0668** [comment]
> I mean your logs has proxyconnect tcp: why?

I config the the network dns as below:
/etc/sysconfig/network-scripts/ifcfg-ens33
DNS1=8.8.8.8
DNS2=4.2.2.2

**Comment by du-do** [comment]
Same issue as you, but  add extra_hosts in docker-compose worked.  My harbor version is v2.0.  By the way, if you want use Replications , you also need add extra_hosts under jobservice just like core.

**Comment by ninjadq** [comment]
Try to config the proxy in `harbor.yml`, If you wanna proxy the traffic

**Comment by 4admin2root** [comment]
the same issue but with ip addr,  http://192.168.1.11
harbor version: Version v1.10.3-6990ccaa
