### ISSUE TITLE
Flood, how to turn off health log!Change configuration log_level of common/config/registryctl/config.yml has no effect

### ISSUE THREAD

**Issue by 7error** [goharbor/harbor#12324]
I change common/config/registryctl/config.yml  log_level: "INFO"  to  log_level: "ERROR",
but it no effect for https://github.com/goharbor/harbor/blob/v2.0.0/src/registryctl/handlers/handler.go#L37
there will always a health check log for interval 30s from https://github.com/goharbor/harbor/blob/v2.0.0/make/photon/registryctl/Dockerfile#L17

look these
```bash
Jun 24 17:39:35 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:39:35 +0000] "GET /api/health HTTP/1.1" 200 9
Jun 24 17:40:05 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:40:05 +0000] "GET /api/health HTTP/1.1" 200 9
Jun 24 17:40:35 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:40:35 +0000] "GET /api/health HTTP/1.1" 200 9
Jun 24 17:41:05 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:41:05 +0000] "GET /api/health HTTP/1.1" 200 9
Jun 24 17:41:35 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:41:35 +0000] "GET /api/health HTTP/1.1" 200 9
Jun 24 17:42:05 172.30.0.1 registryctl[1350]: 127.0.0.1 - - [24/Jun/2020:09:42:05 +0000] "GET /api/health HTTP/1.1" 200 9
```

**Comment by 7error** [comment]
In addition to the HEALTHCHECK of dockerfile, there are also check from core every 10 * time.Second ,https://github.com/goharbor/harbor/blob/v2.0.0/src/core/api/health.go#L66 .The checked module with http will have a lot of health log.

**Comment by wy65701436** [comment]
You should modify the log_level of core directly, as the regsitryclt and core are using unique logger. The log_level of regsitryctl should be removed, thanks for pointing. 

And for the HEALTHCHECK frequence, you can file an HEALTHCHECK separate issue for, so far it's hard coded.

**Comment by 7error** [comment]
Got it,tks!
