### ISSUE TITLE
can‘t  add the harbor-chart-repo

### ISSUE THREAD

**Issue by yizhishang** [goharbor/harbor#12326]
helm-chart： version 2.0

helm repo add harbor https://core.harbor.yizhishang.com/chartrepo/library --username "admin" --password "admin"
Error: looks like "https://core.harbor.yizhishang.com/chartrepo/library" is not a valid chart repository or cannot be reached: Get "https://core.harbor.yizhishang.com/chartrepo/library/index.yaml": x509: certificate signed by unknown authority

**Comment by 7error** [comment]
you may add --ca-file to your cmd like helm repo add --ca-file

**Comment by yizhishang** [comment]
how do deal in rancher?
rancher use git tool to pull the chart-data from the harbor
