### ISSUE TITLE
Docs contain incorrect information about how to access Swagger definitions

### ISSUE THREAD

**Issue by GJKrupa** [goharbor/harbor#12323]
The Swagger docs page (https://goharbor.io/docs/2.0.0/build-customize-contribute/configure-swagger/) contains some incorrect information:

> Open the file swagger.yaml under the docs directory in Harbor project

There is no such file in the repo

> `wget https://raw.githubusercontent.com/goharbor/harbor/master/docs/prepare-swagger.sh https://raw.githubusercontent.com/goharbor/harbor/master/docs/swagger.yaml`

See above. This URL results in a 404 error

> `http://<HARBOR_SERVER>/static/vendors/swagger/index.html`

This results in a 404 when I try to access it on our v1.10.2 server (the URL is present in the 1.10 docs as well). I believe the link should be http://<HARBOR_SERVER>/devcenter.

**Comment by ninjadq** [comment]
Sorry for the convenience. You can access Harbor API documents in Harbor home page directly. The entrance is located in the left bottom corner.
![image](https://user-images.githubusercontent.com/1069785/85966277-d3ce7000-b9f1-11ea-9990-5ae17eaad796.png)

**Comment by codwu** [comment]
> Sorry for the inconvenience. You can access Harbor API documents in the Harbor home page directly. The entrance is located in the left bottom corner.
> ![image](https://user-images.githubusercontent.com/1069785/85966277-d3ce7000-b9f1-11ea-9990-5ae17eaad796.png)

I still cannot find the entrance in the Harbor home page, could you show me in a bigger screenshot?
