### ISSUE TITLE
Harbor doesn't start after reboot

### ISSUE THREAD

**Issue by tmcmm** [goharbor/harbor#12334]
Harbor doesn't seem to start after a reboot or a restart on docker service. Displaying the error:
ERROR: for registry  Cannot start service registry: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

**Comment by 7error** [comment]
Duplicate of #9382 
This error is very common. It reflects the vulnerability and lack of robustness of the system. You can restart several times and use the following command
```bash
docker-compose down;docker-compose up -d;
```
Good luck

**Comment by ninjadq** [comment]
closed as dup
