### ISSUE TITLE
API v2.0: Show labels assigned to image artifact and search for images with a certain label

### ISSUE THREAD

**Issue by claflico** [goharbor/harbor#12332]
Harbor 2.0 fresh install. Have pushed a few images in for testing. Trying to use the API to add labels to images.

1. Using the API is it possible to show the labels already associated with an image
2. Is it possible to query the API to get all images that have a certain label?

**Comment by ninjadq** [comment]
Please refer the API documents, you can get an image with associated labels

**Comment by claflico** [comment]
Not to sound rude but can you be more specific? I've already looked through API Explorer and see how to create/delete labels from images but it doesn't show how to view labels that an image has. I've looked at docs on the goharbor.io website which sent me to github and when I click on the links for managing labels I get 404s.

**Comment by ywk253100** [comment]
Use getting artifact API with `with_label=true` in query:  https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L233 with

**Comment by claflico** [comment]
@ywk253100 That worked for getting the labels from the artifact but is it possible to go the other way as well? Find all artifacts with a certain label?

**Comment by ywk253100** [comment]
No, it isn't supported
