### ISSUE TITLE
Harbor registry disk size is far larger than actual images exist on Harbor.

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#12347]
**Expected behavior and actual behavior:**
While uploading a large docker image to Harbor, Docker retrying to copy large blobs in loops until it fails(we are using cache layer on the server that pushed the image but it's not the issue).
![image](https://user-images.githubusercontent.com/38837459/85990690-12b4f380-b9fb-11ea-8b71-f192a3390576.png)
![image](https://user-images.githubusercontent.com/38837459/85989735-9cfc5800-b9f9-11ea-8dba-9d68ffce18bf.png)
After some retries, I noticed the Harbor-Registry disk size is far larger than actual images that exist on Harbor.
At this point, I would expect GC to remove the data, But running GC didn't clear it.

Harbor Registry storage:
> harbor [ /storage/docker/registry/v2/repositories ]$ du -sh *
**> 1.3T	data-science**
> 411M	lpapps_release
> 432M	prod-infra

This is the repo which I showed in the example which failed to push - there is no single image under this repo in Harbor UI but it still has data on disk.
> harbor [ /storage/docker/registry/v2/repositories/**data-science** ]$ du -sh *
> **223G	lp-smartcapacity-app**

Harbor UI project usage:
**data-science - 66.54GB of unlimited**
lpapps_release - 356.73GB of unlimited
prod-infra - 10.46GB of unlimited

Registry log:
[registry.log](https://github.com/goharbor/harbor/files/4844613/registry.log)

**Versions:**
- harbor version: v2.0.0-87602132 installed using helm chart over k8s.

**Comment by reasonerjt** [comment]
@YakirShriker 
Please check are there blobs that are in Storage of registry but are not in DB?

@wy65701436 
Will the data of blobs that failed to be pushed be stored some where in registry?

**Comment by wy65701436** [comment]
Can you size the `_uploads` folder of each repository? The location is `/storage/docker/registry/v2/repositories/{repository_name}/_uploads`.

And you can try to clean the items in these folders, but please make sure set Harbor to read-only at the time you do it.

**Comment by YakirShriker** [comment]
@reasonerjt @wy65701436 
I Already removed the project from Harbor UI(removed all repositories), cleaned the disk under 
`/storage/docker/registry/v2/repositories/{repository_name}`
restarted Harbor.
Problem solved.

Now I'm pushing images not using Proxy, but It certainly requires a check.
I can reproduce the issue for more info if needed.

**Comment by xaleeks** [comment]
In the case where it fails to push the image, whether it's a quota issue or connectivity or something else, the already uploaded blobs are not removed and need to wait until GC in order to be deleted off the registry.  The exception is if these blobs are referenced by another subsequent image upload so they are needed for completeness.  Can you check to see if are any such blobs?

**Comment by YakirShriker** [comment]
@xaleeks 
GC not removing the blobs even after deleting the whole project.(I guess no image should have 
I can reproduce it and check, but can you share how can I check if a blob is referenced by another image?
