### ISSUE TITLE
Double REST API calls needed to get __csrf response header

### ISSUE THREAD

**Issue by pawelmy** [goharbor/harbor#12354]
After upgrading harbor from version **1.10** to **2.0.0-87602132**, the REST API needs two calls to get a response **__csrf** Set-Cookie header. Previously we would get **_xsrf** token after first call.

The first call only provides:

`Server: openresty/1.15.8.1
Date: Thu, 25 Jun 2020 12:50:14 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 418
Vary: Accept-Encoding
Set-Cookie: sid=e1da0ad782819d6c44f7609e6d401061; Path=/; HttpOnly
X-Request-Id: 683103a880af1cfdfaf69f15e54b59fb
Strict-Transport-Security: max-age=15724800; includeSubDomains`

The second one gives:

`Server: openresty/1.15.8.1
Date: Thu, 25 Jun 2020 12:50:14 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 418
Vary: Accept-Encoding
Set-Cookie: _gorilla_csrf=MTU5MzA4OTQxNHxJbm95TjBsU1VGTlFZbk5KWldrNE5VdFlLMjlUYjJ0TFRFc3pWRW81VW1ad2RXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_G6hNqYt81cc19Fd3; Path=/; Expires=Fri, 26 Jun 2020 00:50:14 GMT; Max-Age=43200; HttpOnly; Secure; SameSite=Strict
Set-Cookie: __csrf=oMEqxAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXqscGQmhVn20nv3nnPLm9SOw==; Path=/; Secure; SameSite=Strict
Vary: Cookie
X-Request-Id: d83d4054a4dc829f25b28ecfbea6aac8
Strict-Transport-Security: max-age=15724800; includeSubDomains`

Is this an expected behavior? Is there some way to receive the **__csrf** token on first call to set the **X-Harbor-CSRF-Token** header?

Regards,
P.M.

**Comment by reasonerjt** [comment]
You shouldn't see CSRF token header it only checks requests carrying the sid cookie.

**Comment by pawelmy** [comment]
Thanks for the answer. Indeed after ignoring cookies, the XSRF token was no longer needed :)
