### ISSUE TITLE
Failed to replicate image from Harbor to gitlab

### ISSUE THREAD

**Issue by WenwuPeng** [goharbor/harbor#12355]
It is failed to replicate image from harbor to gitlab, and get error "failed to push manifest of image test:latext http error: code 404, message"

**Steps to reproduce the problem:**
1. Upload image into harbor
2. Create gitlab register with  username and personal access token
3. Create replication rule to replicate the image with push mode
4. Trigger the replicate rule.

Expect:
can replicate image to gitlab.

Actually result:
Failed to replicate image to gitlab

- harbor version: v1.10.1-f3e11715
- docker engine version: 
root@harbor01:/home/vio# docker version
Client: Docker Engine - Community
 Version:           19.03.6

- docker-compose version: 
root@harbor01:/home/vio# docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

gitlab version:   GitLab Enterprise Edition 12.10.0-ee

**Comment by steven-zou** [comment]
@WenwuPeng 

Please attach the relevant logs

**Comment by steven-zou** [comment]
@ lxShaDoWxl

Any comments?

**Comment by WenwuPeng** [comment]
[replication.log](https://github.com/goharbor/harbor/files/4850297/replication.log)

**Comment by bitsf** [comment]
Can other images replicate successful ?
There seems something wrong with gitlab cache.

**Comment by bitsf** [comment]
most issues was fixed in harbor 2.1.0 and 2.0.3
