### ISSUE TITLE
test against multiple k8s versions

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12350]
CI needs to support testing multiple (N-2) k8s versions fairly easily for future releases.  N-2 means 3 minor releases, which would be 1.18, 1.17. 1.16 at this time.  Compatible means nothing in stable features should break the release, beta or alpha features can be ignored.

**Comment by reasonerjt** [comment]
For nightly we'll test against the latest.
If the infrastructure permits we should make sure the test suites pass on multiple k8s version.

**Comment by wy65701436** [comment]
17/18/19 already supported

**Comment by ywk253100** [comment]
done
