### ISSUE TITLE
Unify the way Harbor creates JWT token 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12351]
There was legacy code in src/core/service/token that signs a jwt, it should reuse the func in `src/pkg/token`

**Comment by flixpae** [comment]
does this effect functionality to use a other (external) JWT token-realm for pushing images to the docker registry ?

i look for a way to use gitlab aus auth endpoint for the harbor registry. 
so we can keep all authentication in gitlab and dont need to introduce some kind of explicit authentication in our ci pipelines

my question is somewhat related to #6666

**Comment by reasonerjt** [comment]
@flixpae No it does not.

**Comment by reasonerjt** [comment]
Fixed by #13257
