### ISSUE TITLE
500 error when pushing image due to error "pq: sorry, too many clients already"

### ISSUE THREAD

**Issue by djoyahoy** [goharbor/harbor#12352]
**Expected behavior and actual behavior:**
The image is pushed successfully and a 500 error is not reported.

**Steps to reproduce the problem:**
I am using [kpack](https://github.com/pivotal/kpack) to build the images but I can more easily replicate this behavior with [pack](https://github.com/buildpacks/pack).

Run the following command 3 or more times concurrently:
`pack create-builder <harbor-repo> -b ./builder-config.toml --publish`

Where `builder-config.toml` has the following contents:
```
[[buildpacks]]
image = "gcr.io/paketo-buildpacks/java"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/nodejs"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/go"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/dotnet-core"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/php"

[[buildpacks]]
image = "gcr.io/paketo-buildpacks/procfile"

[[order]]
group = [
  { id = "paketo-buildpacks/java" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/nodejs" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/go" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/dotnet-core" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/php" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/procfile", version = "1.3.8" },
]

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
run-image = "gcr.io/paketo-buildpacks/run:full-cnb-cf"
build-image = "gcr.io/paketo-buildpacks/build:full-cnb-cf"
```

At least one of the commands should fail with a 500 error code.

**Versions:**
- harbor version: v2.0.0-87602132
- docker engine version: N/A
- docker-compose version: N/A

I have not provided the docker versions because I am using kpack/pack which push directly to the registry without a docker daemon.

**Additional context:**
- The relevant core logs are as follows:
```
2020-06-29T19:56:44Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"UNKNOWN","message":"unknown: deal with /v2/tmp/builder/blobs/sha256:240bb3a3282629a1be5009f0ec2182ef886bdc7987e44d59445ac99b2eb84971 request in transaction failed: pq: sorry, too many clients already"}]}
2020-06-29T19:56:44Z [ERROR] [/lib/orm/orm.go:59]: begin transaction failed: pq: sorry, too many clients already
```
- pack will report the error as such:
```
ERROR: failed to write image to the following tags: [<harbor repo>: HEAD https://<harbor url>/blobs/sha256:d35ca452c1fb657a3e58b7caf95eafad50bf6355df8cfd82b885e0df8ede0032: unsupported status code 500]
```
- The core config map has the follow postgress conn settings:
```
  POSTGRESQL_MAX_IDLE_CONNS: "50"
  POSTGRESQL_MAX_OPEN_CONNS: "100"
```

**Comment by reasonerjt** [comment]
@djoyahoy are you using kpack to push image?

Do you know how many concurrent requests it is sending when pushing different images in parallel?

**Comment by djoyahoy** [comment]
Hi @reasonerjt, I am using kpack to push these images. My workflow is to create 4 [CustomClusterBuilder CRDs](https://github.com/pivotal/kpack/blob/master/docs/custombuilders.md) that generate images in the registry. Each image is roughly 4GB in size and each has 60 layers.  I don't know how many concurrent requests this produces, but I can attempt to find out.

**Comment by xaleeks** [comment]
@djoyahoy is this stereotypical of a kpack backed image push to harbor, any other discernible patterns in common usage that we should be aware of?  This is very helpful btw, thanks for helping test against harbor 2.0.  I'm guessing these 3 crds are managing 4 different images entirely?

**Comment by djoyahoy** [comment]
@xaleeks These pushes are unique from other types of image pushes in kpack. These images are generated in the controller, whereas most typical image pushes will happen in a kpack generated pod container. These CRDs will generally be created right after installation, and then updated as new dependencies are released (a weekly to monthly cadence). Finally, you are correct, the CRDs manage separate images.

**Comment by heww** [comment]
Closed as we update the `max_connections` of harbor-db to 1024 and limit the `max_open_conns` to 1000 in harbor-core.
