### ISSUE TITLE
asynchronous container image replication

### ISSUE THREAD

**Issue by wzcwts521** [goharbor/harbor#12366]
CHART version: harbor-1.3.1
APP version: 1.10.1

I've set up a replication rule between local(harbor) to a cloud. (ACR)
Replication mode: push-based

The behavior is: 
docker push completion timestamps are similar to the timestamps that the container image is available in the harbor. 
there are 1 to 5+ minutes delayed once the container image is ready in ACR.

Is there a way to reduce the delay?

**Comment by reasonerjt** [comment]
It's designed to be asynchronous, there's extra time for scheduling and launching the job.

Could you check the timestamp in the log of replication jobs and see when the data transfer happened?

**Comment by wzcwts521** [comment]
Thanks, guys for taking a look. 
The test was done a couple of weeks ago. I'll check with our team if we can create an ACR to test it again.

**Comment by wzcwts521** [comment]
Sorry for the delay. 

I got a chance to run a test with two images. 
Here is the test case. push a container image from an image build host to harbor registry, then by utilizing harbor replication rule (event base) pushes the image to Azure ACR. 

Container image A with a size of 1.63GB. 
It took 35 seconds from container image build completion to the container image is available in ACR.

Container image B with a size of 109MB.
It took 7 seconds from container image build completion to the container image is available in ACR.
