### ISSUE TITLE
Harbor core crashes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#12361]
Harbor V2 installed over k8s(new installation).
I see a lot of Harbor core crashes
NAME                                         READY   STATUS             **RESTARTS**   AGE
harbor-harbor-core-55c95f6fc8-cznll          1/1     Running            **16**         6d19h

**core.log**
> 2020/06/29 12:55:52.787 [D] [middleware.go:52]  |   10.84.221.72| 200 |  27.844322ms|   match| POST     /service/notifications/jobs/replication/task/14568   r:/service/notifications/jobs/replication/task/:id([0-9]+)
> 2020-06-29T12:55:52Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with topic 'REPLICATION': &event.ReplicationEvent{EventType:"REPLICATION", ReplicationTaskID:14525, OccurAt:time.Time{wall:0xbfb697162a05c646, ext:1053002638510, loc:(*time.Location)(0x3066180)}, Status:"Error"}
> 2020-06-29T12:55:52Z [ERROR] [/core/service/notifications/jobs/handler.go:159]: failed to update the status of the replication task 14528: dial tcp 172.16.60.47:5432: connect: cannot assign requested address
> 2020-06-29T12:55:52Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"dial tcp 172.16.60.47:5432: connect: cannot assign requested address"}]}
> /harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
> /harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
> /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
> /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
> /harbor/src/core/service/notifications/jobs/handler.go:160, github.com/goharbor/harbor/src/core/service/notifications/jobs.(*Handler).HandleReplicationTask
> /usr/local/go/src/reflect/value.go:460, reflect.Value.call
> /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
> /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2802, net/http.serverHandler.ServeHTTP
> /usr/local/go/src/net/http/server.go:1890, net/http.(*conn).serve
> 2020/06/29 12:55:52.804 [D] [middleware.go:52]  |   10.84.221.72| 500 |  16.931779ms|   match| POST     /service/notifications/jobs/replication/task/14528   r:/service/notifications/jobs/replication/task/:id([0-9]+)
> 2020-06-29T12:55:52Z [ERROR] [/core/service/notifications/jobs/handler.go:159]: failed to update the status of the replication task 14532: dial tcp 172.16.60.47:5432: connect: cannot assign requested address
> 2020-06-29T12:55:52Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"dial tcp 172.16.60.47:5432: connect: cannot assign requested address"}]}
> /harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
> /harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
> /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
> /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
> /harbor/src/core/service/notifications/jobs/handler.go:160, github.com/goharbor/harbor/src/core/service/notifications/jobs.(*Handler).HandleReplicationTask
> /usr/local/go/src/reflect/value.go:460, reflect.Value.call
> /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
> /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2802, net/http.serverHandler.ServeHTTP
> /usr/local/go/src/net/http/server.go:1890, net/http.(*conn).serve
> 2020/06/29 12:55:52.806 [D] [middleware.go:52]  |   10.84.221.72| 500 |  15.696719ms|   match| POST     /service/notifications/jobs/replication/task/14532   r:/service/notifications/jobs/replication/task/:id([0-9]+)
> 2020-06-29T12:55:52Z [ERROR] [/core/config/config.go:130]: failed to load config, error dial tcp 172.16.60.47:5432: connect: cannot assign requested address
> 2020-06-29T12:55:52Z [WARNING] [/server/middleware/security/security.go:54][requestID="f69cf749-8fbb-4ea9-8cd7-6f73231630e9"]: failed to get auth mode: dial tcp 172.16.60.47:5432: connect: cannot assign requested address
> 2020-06-29T12:55:52Z [ERROR] [/core/service/notifications/jobs/handler.go:159]: failed to update the status of the replication task 14535: dial tcp 172.16.60.47:5432: connect: cannot assign requested address
> 2020-06-29T12:55:52Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"dial tcp 172.16.60.47:5432: connect: cannot assign requested address"}]}
> /harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
> /harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
> /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
> /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
> /harbor/src/core/service/notifications/jobs/handler.go:160, github.com/goharbor/harbor/src/core/service/notifications/jobs.(*Handler).HandleReplicationTask
> /usr/local/go/src/reflect/value.go:460, reflect.Value.call
> /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
> /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2802, net/http.serverHandler.ServeHTTP
> /usr/local/go/src/net/http/server.go:1890, net/http.(*conn).serve
> 2020/06/29 12:55:52.810 [D] [middleware.go:52]  |   10.84.221.72| 500 |   18.39826ms|   match| POST     /service/notifications/jobs/replication/task/14535   r:/service/notifications/jobs/replication/task/:id([0-9]+)
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb25d73]
> 
> goroutine 419016 [running]:
> github.com/goharbor/harbor/src/pkg/scan/whitelist.(*defaultManager).Get(0x308daa0, 0x4, 0xc002dccc10, 0x6, 0xc0008db948)
> 	/harbor/src/pkg/scan/whitelist/manager.go:70 +0x43
> github.com/goharbor/harbor/src/core/promgr.(*defaultProjectManager).Get(0xc00080e1c0, 0x19ede20, 0xc00086b150, 0x0, 0x0, 0x0)
> 	/harbor/src/core/promgr/promgr.go:85 +0x213
> github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.constructReplicationPayload(0xc00093e9c0, 0x616122, 0x20c5600, 0xc0008c4280, 0x1d054d7)
> 	/harbor/src/controller/event/handler/webhook/artifact/replication.go:191 +0x87a
> github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.(*ReplicationHandler).Handle(0x308daa0, 0x19845a0, 0xc00093e9c0, 0xc0000ee000, 0x7f827d5d0648)
> 	/harbor/src/controller/event/handler/webhook/artifact/replication.go:40 +0x7b
> github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1.1(0x208fce0, 0x308daa0, 0x0, 0x1d11279, 0xb, 0x19845a0, 0xc00093e9c0)
> 	/harbor/src/pkg/notifier/notifier.go:200 +0xba
> created by github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1
> 	/harbor/src/pkg/notifier/notifier.go:194 +0xac
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb25d73]
> 
> goroutine 419652 [running]:
> github.com/goharbor/harbor/src/pkg/scan/whitelist.(*defaultManager).Get(0x308daa0, 0x4, 0xc000bd16f0, 0x6, 0xc002c042c8)
> 	/harbor/src/pkg/scan/whitelist/manager.go:70 +0x43
> github.com/goharbor/harbor/src/core/promgr.(*defaultProjectManager).Get(0xc00080e1c0, 0x19ede20, 0xc000be4160, 0x0, 0x0, 0x0)
> 	/harbor/src/core/promgr/promgr.go:85 +0x213
> github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.constructReplicationPayload(0xc002374580, 0x616122, 0x20c5600, 0xc002c40a00, 0x1d054d7)
> 	/harbor/src/controller/event/handler/webhook/artifact/replication.go:191 +0x87a
> github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.(*ReplicationHandler).Handle(0x308daa0, 0x19845a0, 0xc002374580, 0xc000af4e00, 0x7f827d5e5af0)
> 	/harbor/src/controller/event/handler/webhook/artifact/replication.go:40 +0x7b
> github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1.1(0x208fce0, 0x308daa0, 0x0, 0x1d11279, 0xb, 0x19845a0, 0xc002374580)
> 	/harbor/src/pkg/notifier/notifier.go:200 +0xba
> created by github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1
> 	/harbor/src/pkg/notifier/notifier.go:194 +0xac

**database.log**

> [root@raor-kmb01 ~]# kubectl logs -n harbor harbor-harbor-database-0
> LOG:  database system was interrupted; last known up at 2020-06-23 13:31:10 UTC
> FATAL:  the database system is starting up
> LOG:  database system was not properly shut down; automatic recovery in progress
> LOG:  redo starts at 0/E99CA20
> LOG:  invalid record length at 0/EA60C08: wanted 24, got 0
> LOG:  redo done at 0/EA60BE0
> LOG:  last completed transaction was at log time 2020-06-23 13:35:04.034183+00
> LOG:  MultiXact member wraparound protections are now enabled
> LOG:  database system is ready to accept connections
> LOG:  autovacuum launcher started
> LOG:  incomplete startup packet
> LOG:  incomplete startup packet
> LOG:  incomplete startup packet
> LOG:  incomplete startup packet
> LOG:  incomplete startup packet
> LOG:  could not send data to client: Connection reset by peer
> STATEMENT:  SELECT b.digest_blob FROM artifact a, artifact_blob b WHERE a.digest = b.digest_af AND a.project_id = $1 AND b.digest_blob IN ($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
> FATAL:  connection to client lost
> STATEMENT:  SELECT b.digest_blob FROM artifact a, artifact_blob b WHERE a.digest = b.digest_af AND a.project_id = $1 AND b.digest_blob IN ($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  incomplete startup packet
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  incomplete startup packet
> LOG:  incomplete startup packet
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  could not send data to client: Connection reset by peer
> STATEMENT:  SELECT b.digest_blob FROM artifact a, artifact_blob b WHERE a.digest = b.digest_af AND a.project_id = $1 AND b.digest_blob IN ($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
> FATAL:  connection to client lost
> STATEMENT:  SELECT b.digest_blob FROM artifact a, artifact_blob b WHERE a.digest = b.digest_af AND a.project_id = $1 AND b.digest_blob IN ($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  could not receive data from client: Connection reset by peer
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  unexpected EOF on client connection with an open transaction
> LOG:  incomplete startup packet
> ERROR:  duplicate key value violates unique constraint "unique_tag"
> DETAIL:  Key (repository_id, name)=(56, 1.0.0.7-52) already exists.
> STATEMENT:  INSERT INTO "tag" ("repository_id", "artifact_id", "name", "push_time", "pull_time") VALUES ($1, $2, $3, $4, $5) RETURNING "id"

**Comment by reasonerjt** [comment]
Do you see the problem if you turn off webhook?

**Comment by reasonerjt** [comment]
This looks similar to #12339

**Comment by YakirShriker** [comment]
Yes, I'm replication a lot of images.
How can I turn off webhook?

**Comment by reasonerjt** [comment]
There may be issues when there are a lot DB connections, but even though there should not be a nil pointer panic, let's make sure there won't be runtime error @mmpei

**Comment by reasonerjt** [comment]
@mmpei Please double check if this bug exists in v1.10.x

**Comment by ywk253100** [comment]
@reasonerjt The bug doesn't exist in v1.10.x

**Comment by reasonerjt** [comment]
@mmpei please make sure the fix is cherry picked to 2.0 branch

**Comment by reasonerjt** [comment]
Cherry pick to 2.0 branch: https://github.com/goharbor/harbor/pull/12597
