### ISSUE TITLE
A couple of enhancements

### ISSUE THREAD

**Issue by renjithkm86** [goharbor/harbor#12362]
This is about the Harbor v2.0

1) Right now, I didn't find any way to collect the error logs from the UI. For example, if replication fails, it shows the error message when we place mouse cursor over the status icon. But no way to download or get the detailed error message. So, please add a feature to collect error logs from the UI itself.
![image](https://user-images.githubusercontent.com/50958130/86130462-cef8e180-bb01-11ea-8d59-d5df068a6900.png)

2) The browser scroll bar(vertical one) is not working on Harbor UI. Only PageUp/Down or Keyboard arrow keys works. 
![image](https://user-images.githubusercontent.com/50958130/86130272-8e00cd00-bb01-11ea-9435-f79ad46e2242.png)

**Comment by reasonerjt** [comment]
For 1. 
In replication Harbor will first gather the information of the artifacts to be replicated and launch jobs
If the job is not launched when the error happens you have to check the log of `harbor-core` to get more details.

**Comment by steven-zou** [comment]
@renjithkm86 

Fort the first question, you're checking the overall status of the execution that contains multiple tasks. For checking the concreted logs you need to enter the task list by clicking the execution ID link and then find the log links of the failed tasks.

**Comment by reasonerjt** [comment]
Closing as it's a dup of #12363
