### ISSUE TITLE
How can I use a registry mirror pull from Harbor Registry？

### ISSUE THREAD

**Issue by Thinkwp** [goharbor/harbor#1236]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
3)Log files, you can get them by package the /var/log/harbor/

**Comment by ScorpioCPH** [comment]
Do you mean you want do deploy your own docker registry as a mirror?

**Comment by Thinkwp** [comment]
Server A(docker.mydomain.com): I used Harbor build a private registry, now I can login, pull and push from docker.mydomain.com.
Server B(mirror.mydomain.com): Server B as a mirror of Server A. if I set proxy remoteurl: https://registry-1.docker.io, It looks fine. But, if I set  proxy remoteurl:https://docker.mydomain.com, It doesn't work.
 Can I realize this deployment?
Thanks.

**Comment by Thinkwp** [comment]
Sure, I known Harbor's replication policies. I want Mirror pull from Registry instead of Registry push to Mirror.

**Comment by hainingzhang** [comment]
current design works in a push fashion. There is no plan for a pull type replication. 

We have not tested the proxy configuration. The docker client may only works for docker hub.
