### ISSUE TITLE
Harbor v2.0.1-rc01 with JFrog 

### ISSUE THREAD

**Issue by renjithkm86** [goharbor/harbor#12363]
I am trying to connect Harbor to JFrog Artifactory. Registry is configured without any issue.

![image](https://user-images.githubusercontent.com/50958130/86132062-08325100-bb04-11ea-9d62-299266531ba0.png)

Now, I am trying to do Pull Replication. 
![image](https://user-images.githubusercontent.com/50958130/86132782-03ba6800-bb05-11ea-93a0-fd8076d17d86.png)

But it fails with the following error:
![image](https://user-images.githubusercontent.com/50958130/86132981-5136d500-bb05-11ea-92fc-95c19be9a300.png)

From /var/log/harbor/core.log,
![image](https://user-images.githubusercontent.com/50958130/86133190-9ce97e80-bb05-11ea-870a-b300f80d02c6.png)

Please check what could be the issue. Also, please let me know if more info required.  

- harbor version: v2.0.1 rc01
- docker engine version: 18.06.0~ce~3-0~ubuntu
- docker-compose version: 1.8.0-2~16.04.1

**Comment by reasonerjt** [comment]
This is the same problem you mentioned in https://github.com/goharbor/harbor/issues/12362 right?

It seems Artifactory is returning an error page.

**Comment by renjithkm86** [comment]
> This is the same problem you mentioned in #12362 right?
> 
> It seems Artifactory is returning an error page.

Yeah, but that ticket is opened for Enhancement.

**Comment by chlins** [comment]
@renjithkm86 Your jfrog artifactory endpoint url looks strange, try to remove the suffix '/artifactory/webapp/#/home'.

**Comment by bitsf** [comment]
@renjithkm86 Is it fixed after you try chlins's suggestion?

**Comment by renjithkm86** [comment]
No, the error now I am seeing in the core.log is:

Jul  6 06:50:41 172.18.0.1 core[1001]: 2020-07-06T06:50:41Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://artifacts-xx.xxx.xxx.xxxx.com: http status code: 400, body: {
Jul  6 06:50:41 172.18.0.1 core[1001]:   "errors" : [ {
Jul  6 06:50:41 172.18.0.1 core[1001]:     "status" : 400,
Jul  6 06:50:41 172.18.0.1 core[1001]:     "message" : "Unsupported docker v2 repository request for 'artifacts-xx'"
Jul  6 06:50:41 172.18.0.1 core[1001]:   } ]
Jul  6 06:50:41 172.18.0.1 core[1001]: }

**Comment by bitsf** [comment]
curl -L -k `https://artifacts-xx.xxx.xxx.xxxx.com/v2/` should be success.
if not, maybe the endpoint path is not correct, try use `https://artifacts-xx.xxx.xxx.xxxx.com/artifactory/v2/`

And you can check if `docker pull` can work first.

**Comment by chlins** [comment]
@renjithkm86 Can you provide your jfrog HTTP setting - Docker Access Method? and the type of your repo, local、remote or virtual？

**Comment by reasonerjt** [comment]
@bitsf @chlins Could you clarify if there is a PR to fix this problem?  We wanna clarify if this can be fixed in v2.0.2

**Comment by steven-zou** [comment]
Pending for more info from the bug reporter.

**Comment by renjithkm86** [comment]
Thanks, I think I figured out the issue. /v2 URL works. It is different from what artifacts is pointing to. 

One last question, what is the difference between 'docker-registry' and JFrog' registry options? My /v2 URL works with both.

**Comment by bitsf** [comment]
@renjithkm86 so do you mean you finally set the registry url to https://artifacts-xx.xxx.xxx.xxxx.com/v2/ which function well ?

Main difference between adapters is the authentication and some special APIs that different vendor may provide, most registry v2 APIs are same as docker distribution defined.
You can check code directly to understand
https://github.com/goharbor/harbor/tree/master/src/replication/adapter

**Comment by mehulgogri** [comment]
@renjithkm86 while adding jfrog artifactory as a registry endpoint, what Access ID and Access Secret did you use?
Artifactory provides regular username password, Identity Token, API key, encrypted password. I tried each of this and it fails to ping the endpoint
