### ISSUE TITLE
Delete helm chart failed

### ISSUE THREAD

**Issue by kerven88** [goharbor/harbor#12370]
harbor版本：v2.0.0
helm版本：v3

使用helm3上传了一个chart包，然后在harbor界面删除时一直删除不了。
删除时候core日志：
Jul  1 15:29:39 192.168.96.1 core[16822]: 2020/07/01 07:29:39.856 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    269.892µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  1 15:29:41 192.168.96.1 core[16822]: 2020/07/01 07:29:41.087 #033[1;44m[D]#033[0m [middleware.go:52]  |    172.16.4.89|#033[97;43m 404 #033[0m|   5.829532ms|   match|#033[97;41m DELETE  #033[0m /api/chartrepo/helm-repo/charts/postgresql/latest-pg12   r:/api/chartrepo/:repo/charts/:name/:version
Jul  1 15:29:41 192.168.96.1 core[16822]: 2020/07/01 07:29:41.106 #033[1;44m[D]#033[0m [middleware.go:52]  |    172.16.4.89|#033[97;42m 200 #033[0m|   5.656285ms|   match|#033[97;44m GET     #033[0m /api/chartrepo/helm-repo/charts/postgresql   r:/api/chartrepo/:repo/charts/:name

删除chart日志：
![image](https://user-images.githubusercontent.com/51351006/86216244-543acf80-bbb0-11ea-808b-d95537b6aa6e.png)

![image](https://user-images.githubusercontent.com/51351006/86216292-63ba1880-bbb0-11ea-9f4d-62586db42234.png)

点击chart进去，提示：
![image](https://user-images.githubusercontent.com/51351006/86216578-d6c38f00-bbb0-11ea-9b30-7a5cf308bfb5.png)

helm chart包下载不了，有报错日志：
![image](https://user-images.githubusercontent.com/51351006/86216476-aed42b80-bbb0-11ea-9026-cdb0beca6419.png)

Jul  1 15:36:10 192.168.96.1 core[16822]: 2020/07/01 07:36:10.760 #033[1;44m[D]#033[0m [middleware.go:52]  |    172.16.4.89|#033[97;43m 404 #033[0m|   4.818481ms|   match|#033[97;44m GET     #033[0m /chartrepo/helm-repo/charts/postgresql-latest-pg12.tgz   r:/chartrepo/:repo/charts/:filename
Jul  1 15:36:19 192.168.96.1 core[16822]: 2020/07/01 07:36:19.685 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|   1.571874ms|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping

**Comment by reasonerjt** [comment]
I believe the charts are still stored in chartmuseum.

**Comment by kerven88** [comment]
> I believe the charts are still stored in chartmuseum.

So, How can I deleted it by force？

**Comment by ninjadq** [comment]
@kerven88  If the chart still stored in the chartmusum, you can find and remove that chart in chart dir which inside your data dir. Then clean up the cache on the chart's Redis db.

**Comment by kerven88** [comment]
> @kerven88 If the chart still stored in the chartmusum, you can find and remove that chart in chart dir which inside your data dir. Then clean up the cache on the chart's Redis db.

Can you give me instructions on how to do this? thank you very much!

**Comment by kerven88** [comment]
在本地已经没有了这个chart包，redis要怎么清除界面才不会显示出来？

**Comment by kerven88** [comment]
该问题已解决。

**Comment by LiuCarl** [comment]
> 该问题已解决。
can you share the fix steps for this issue? i faced same problem

**Comment by zgyyun** [comment]
@kerven88 
你好，能不能说下是怎么解决的？我也遇到同样问题。
