### ISSUE TITLE
error parsing HTTP 411 when pushing from external

### ISSUE THREAD

**Issue by DorianRoos** [goharbor/harbor#12373]
Hi,

Thanks for this great tools it's work well but i have one issue.

When i push an image i have this :

`error parsing HTTP 411 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>411 Length Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>411 Length Required</h1></center>\r\n<hr><center>nginx/1.2.1</center>\r\n</body>\r\n</html>\r\n"`

This is my serveur configuration
Proxy(nginx) -> Serveur ( with harbor )

This is my proxy nginx conf : 

      server {

        listen 443 ssl;
        ssl on;
        ssl_certificate /etc/nginx/ssl/client.cert;
        ssl_certificate_key /etc/nginx/ssl/client.key;
        ssl_client_certificate /etc/nginx/ssl/ca.crt;
        ssl_verify_client optional;

        server_name harbor.xxx.fr;

        location / {
        proxy_redirect off;
        # Adresse ip LAN serveur
        proxy_pass https://x.x.x.x;
        chunked_transfer_encoding on;
 
        proxy_redirect          off;
        proxy_set_header        Host            $host;
        proxy_set_header  X-Real-IP         $remote_addr; # pass on real client’s IP
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        client_max_body_size    0;
        client_body_buffer_size 128k;
        proxy_connect_timeout   90;
        proxy_send_timeout      90;
        proxy_read_timeout      90;
        proxy_buffer_size   16k;
        proxy_buffers       32   16k;
        proxy_busy_buffers_size 64k;

        }
      }

when i use local network Ip on my host config  (ex: 10.80.x.x ) for push, everything work fine.

The issue is when i use the external ip.

i've try this nginx config on harbor instead of default, but not working : 

      location /v2/ {
      proxy_pass http://core/v2/;
      proxy_set_header Host $http_host;
      #proxy_set_header X-Real-IP $remote_addr;
     #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      #proxy_set_header X-Forwarded-Proto $scheme;
      proxy_buffering off;
      proxy_request_buffering off;
    }

Thank's

**Comment by reasonerjt** [comment]
It seems the nginx dropped some required header of the request.
Could you check the log and see which component is sending the 411?

**Comment by DorianRoos** [comment]
Hello, i've update the nginx proxy version ( which was 1.2.1 ) and now it's seem ok.

I have an another issue but now it's probably with kubernetes.

I have two kubernetes ( PROD & PREPROD ).

On PREPROD i can pull image, on PROD i can't.

The log from harbor proxy send this :

`Jul  3 08:28:20 192.168.80.1 proxy[2195879]: 2020/07/03 08:28:20 [error] 6#0: *2344 upstream prematurely closed connection while reading upstream, client: X.X.X.X, server: , request: "GET /v2/xxx/preprod-php-fpm-alpine/blobs/sha256:20bc0086526a478aa1e9db6b3d78a7025e38a36f3750ef1260a6c1950eeb6ae7 HTTP/1.1", upstream: "http://192.168.80.8:8080/v2/xxx/preprod-php-fpm-alpine/blobs/sha256:20bc0086526a478aa1e9db6b3d78a7025e38a36f3750ef1260a6c1950eeb6ae7", host: "harbor.registry.fr"`
