### ISSUE TITLE
Docker nginx-photon And  harbor-jobservice Not Start

### ISSUE THREAD

**Issue by liyongxian** [goharbor/harbor#12384]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
install harbor by docker-compose, **Docker nginx-photon And  harbor-jobservice Not Start.**
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1、./prepare --with-notary  --with-chartmuseum
2、docker-compose -f docker-compose.yml

![harbor](https://user-images.githubusercontent.com/18571576/86349858-5fffc200-bc94-11ea-9c09-9bfb0df9374e.jpg)

**Versions:**
Please specify the versions of following systems.

- harbor version: Harbor 2.0
- docker engine version: 17.09.1-ce
- docker-compose version: 1.24.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.

- **Log files:** You can get them by package the `/var/log/harbor/` .
**Not loging proxy.log and jobservice.log**
**postgresql.log**
Jul  2 18:36:13 172.18.0.1 postgresql[1489]: LOG:  incomplete startup packet
Jul  2 18:36:13 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:14 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:15 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:16 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:17 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:18 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:19 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:20 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:21 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:22 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:23 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:24 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:25 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:26 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:26 172.18.0.1 postgresql[1489]: LOG:  database system was not properly shut down; automatic recovery in progress
Jul  2 18:36:26 172.18.0.1 postgresql[1489]: LOG:  invalid record length at 0/17612B8: wanted 24, got 0
Jul  2 18:36:26 172.18.0.1 postgresql[1489]: LOG:  redo is not required
Jul  2 18:36:27 172.18.0.1 postgresql[1489]: FATAL:  the database system is starting up
Jul  2 18:36:27 172.18.0.1 postgresql[1489]: LOG:  MultiXact member wraparound protections are now enabled
Jul  2 18:36:27 172.18.0.1 postgresql[1489]: LOG:  database system is ready to accept connections
Jul  2 18:36:27 172.18.0.1 postgresql[1489]: LOG:  autovacuum launcher started
Jul  2 18:36:28 172.18.0.1 postgresql[1489]: LOG:  incomplete startup packet
   **core.log**       
Jul  2 18:40:44 172.18.0.1 core[1489]: 2020-07-02T10:40:44Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s
Jul  2 18:41:01 172.18.0.1 core[1489]: 2020/07/02 10:41:01.825 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|     192.23µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:41:32 172.18.0.1 core[1489]: 2020/07/02 10:41:32.213 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    205.067µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:42:02 172.18.0.1 core[1489]: 2020/07/02 10:42:02.619 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|     230.69µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:42:32 172.18.0.1 core[1489]: 2020/07/02 10:42:32.990 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    224.205µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:43:03 172.18.0.1 core[1489]: 2020/07/02 10:43:03.371 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    212.266µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:43:33 172.18.0.1 core[1489]: 2020/07/02 10:43:33.765 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    268.242µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:44:04 172.18.0.1 core[1489]: 2020/07/02 10:44:04.150 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    212.993µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:44:34 172.18.0.1 core[1489]: 2020/07/02 10:44:34.546 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    192.532µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:45:04 172.18.0.1 core[1489]: 2020/07/02 10:45:04.959 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    224.851µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:45:35 172.18.0.1 core[1489]: 2020/07/02 10:45:35.458 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    202.677µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:46:05 172.18.0.1 core[1489]: 2020/07/02 10:46:05.886 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    197.121µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:46:36 172.18.0.1 core[1489]: 2020/07/02 10:46:36.266 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|     227.39µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:47:06 172.18.0.1 core[1489]: 2020/07/02 10:47:06.675 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    245.115µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:47:37 172.18.0.1 core[1489]: 2020/07/02 10:47:37.044 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|     216.82µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Jul  2 18:48:07 172.18.0.1 core[1489]: 2020/07/02 10:48:07.465 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|     205.26µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
**portal.log**             
Jul  2 18:46:09 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:09 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:46:12 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:46:12 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:46:19 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:19 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:46:29 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:29 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:46:39 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:39 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:46:42 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:46:42 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:46:49 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:49 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:46:59 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:46:59 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:09 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:09 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:13 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:47:13 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:47:19 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:19 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:29 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:29 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:39 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:39 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:43 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:47:43 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:47:49 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:49 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:47:59 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:47:59 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:48:09 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:48:09 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:48:14 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:48:14 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:48:19 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:48:19 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:48:29 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:48:29 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:48:39 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:48:39 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
Jul  2 18:48:45 172.18.0.1 portal[1489]: 127.0.0.1 - - [02/Jul/2020:10:48:45 +0000] "GET / HTTP/1.1" 200 856 "-" "curl/7.59.0"
Jul  2 18:48:49 172.18.0.1 portal[1489]: 172.18.0.8 - - [02/Jul/2020:10:48:49 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"

**Comment by reasonerjt** [comment]
The command `docker-compose -f docker-compose` does not look correct to me.

Please double check to make sure it's not a usage error, what's the output of 
`docker-compose up -d`?

**Comment by liyongxian** [comment]
sorry,I omit it.Start Harbor:
/usr/local/bin/docker-compose -f /opt/harbor/docker-compose.yml up -d
Thanks.

**Comment by liyongxian** [comment]
@reasonerjt  I met a strange problem.All Docker is UP and Healthy,but When I push image,  the problem was Bad Gateway 502 error.

**Comment by reasonerjt** [comment]
502 normally means the nginx failed to access backend.

**Comment by hantmac** [comment]
Maybe something wrong with nginx config @liyongxian

**Comment by liyongxian** [comment]
yes, It was reson of harbor.yml.Thanks.
