### ISSUE TITLE
LDAP config not picked up during installation on harbor 2.0.1

### ISSUE THREAD

**Issue by faseyiks** [goharbor/harbor#12387]
What can we help you?

Configuration parameters for ldap is not picked up for user settings during installation

What do I expect?
------------------
After installation, that I should have the LDAP fully configured and working. I do not have the option of making the configuration post-installation as the values have to be pulled at install time.  I expect to be able to find the mapped values for these configuration parameters in the common/config/core/env file as below

AUTH_MODE=ldap_auth
SELF_REGISTRATION=off
LDAP_URL=ldaps://ldap.myldapserver.com:636
LDAP_SEARCH_DN=uid=myuid,ou=Users,o=621a35f1a3,dc=jumpcloud,dc=com
LDAP_SEARCH_PWD={redacted}
LDAP_BASE_DN=o=5efde25abec044621a35f1a3,dc=myldapserver,dc=com
LDAP_UID=uid
LDAP_SCOPE=3
LDAP_TIMEOUT=5
VERIFY_REMOTE_CERT=on

Installation Command
-----------------------
./install.sh --with-clair --with-trivy --with-chartmuseum --with-notary

Environment 
------------
Centos 7.8

Harbour Version: 2.0.1

Contents of harbor.yml
-----------------------

`hostname: harbor.ourdomain.com
https:
  port: 443
  certificate: /opt/harbor/configure/harbor.ourdomain.com-bundle.crt
  private_key: /opt/harbor/configure/harbor.ourdomain.com.key

ui_url_protocol: https
ssl_cert: /opt/harbor/tls/notary_signer.crt
ssl_cert_key: /opt/harbor/tls/notary_signer.key

harbor_admin_password: {redacted}

auth_mode: ldap_auth
ldap_url: ldaps://ldap.myldapdomain.com:636
ldap_base_dn: "o=621f1a3,dc=myldapdomain,dc=com"
ldap_search_dn: uid=myuid,ou=Users,o=5efde23,dc=myldapdomain,dc=com
ldap_search_password: {redacted}
ldap_verify_cert: true

database:
  password: {redacted}
  max_idle_conns: 50
  max_open_conns: 100

data_volume: /data_v2.0.1

storage_service:
  s3:
    bucket: {redacted}
    region: eu-west-2
    accesskey: {redacted}
    secretkey: {redacted}
    regionendpoint: s3.eu-west-2.amazonaws.com
    chunksize: 10485760
    encrypt: 'true'
    rootdirectory: /registry
    secure: 'true'
    v4auth: 'true'

  redirect:
    disabled: false

clair:
  updaters_interval: 12

trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: debug
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.0.0

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy`

Additional Questions:
---------------------
There is no reference as the construct of these parameters inside the harbor.yml file. also examples are very rare to find on the net.  The harbour documentation contains the element but did not explain which one is first class parameters and which is sub.  Any idea on how to arrange this in the harbor.yml file will be appreciated.

**Comment by stonezdj** [comment]
The LDAP setting is user related settings,  and is no longer configurable in harbor.yml, you need to instal harbor first and change auth_mod to ldap_auth and configure the ldap setting through web console or REST api.
