### ISSUE TITLE
Granular Access Management for Images

### ISSUE THREAD

**Issue by OheyThere** [goharbor/harbor#12398]
Hey guys,

we are currently running Harbor and only starting to integrate it into our development processes. I really like the look and feel and my colleagues so aswell.
One thing that came to our mind because of some specific use-case was access management for specific images. Inside the project you can create certain members with certain roles and robot accounts but you can not select different rights for different images. E.g. I create user John and I'd like this user to only be able to push and pull the image myproject/website as he is an external partner and should only be allowed to access this certain image

**Describe the solution you'd like**
It would be pretty neat to have the option to create such acces-rules for specific images. Maybe in some kind of tabular form where images are listed and you can tick some boxes with different access rules.

Is this even possible or is the design of Docker preventing this? What is your opinion about this?

**Comment by reasonerjt** [comment]
It is possible but it's a very basic design decision that the permission is assigned at the project level not repository or artifact level.

**Comment by xaleeks** [comment]
You can track progress on this here which is articulated slightly differently - https://github.com/goharbor/harbor/issues/10159
