### ISSUE TITLE
Does harbor support multi domain?

### ISSUE THREAD

**Issue by hwdef** [goharbor/harbor#12396]
I want to use multi domains to access harbor. Does harbor support it?

I didn't find it in the documentation.

**Comment by reasonerjt** [comment]
Currently it does not, because the hostname is also used for getting the token for CLI tools like docker.

Could you give us a specific use case where you need multi-domain?

**Comment by hwdef** [comment]
@reasonerjt 
![image](https://user-images.githubusercontent.com/13084946/86580089-d102ea80-bfb0-11ea-8074-be4f81b0ac3a.png)

For example this picture, is there any good solution?

Now I have configured multiple domain names for ingress so that I can access a.harbor.com through harbor.com and a.harbor.com, but I don’t know how to handle the push of the images.

Can I push `harbor.com/library/hello-world:latest` to a.harbor.com ?

**Comment by 7error** [comment]
This can be a complex situation,you may share your redis 、postgres、postgresql、Registry_data_folder for A and B instance
you can ref these links
```bash
https://github.com/goharbor/harbor/blob/v2.0.1/docs/install-config/harbor-ha-helm.md
https://tonybai.com/2017/06/09/setup-a-high-availability-private-registry-based-on-harbor-and-cephfs/
https://tonybai.com/2020/03/16/build-high-performance-object-storage-with-minio-part1-prototype/
```

**Comment by hwdef** [comment]
@7error 

A and B is already HA.  I want to make B a backup of A, Visit A when A is normal, and visit B when A is down.

**Comment by 7error** [comment]
as you say , becomes simpler，you can  make server B backup in nginx.conf ,B is just a backup 
```bash
http://nginx.org/en/docs/http/ngx_http_upstream_module.html
https://serverfault.com/questions/480241/nginx-failover-without-load-balancing
```

**Comment by hwdef** [comment]
@7error 
Yes,you are right.Now I configure it like this.But I have some requirements that require harbor support multi domain.
For example, I want to push `harbor.com/library/ubuntu:latest`  to A( by nginx ), and I also want `a.harbor.com/library/ubnutu:latest` to A(direct).

Can harbor receive mirrors like this?

**Comment by reasonerjt** [comment]
@hwdef 
I haven't tested it, if your client can both access a.harbor.com and harbor.com, this MAY work.

The potential problem is the redirection when requesting token, the hostname will be set to external endpoint.

**Comment by hwdef** [comment]
@reasonerjt 

Thanks for your reply,I will have a try.

**Comment by Timoses** [comment]
This sounds related to: https://github.com/goharbor/harbor/issues/8243
