### ISSUE TITLE
Query string: how to specify nested object

### ISSUE THREAD

**Issue by carlbalmer** [goharbor/harbor#12399]
This is probably a super simple question...
How can i define a query string that matches a nested object field?

For example when listing artifacts (​/projects​/{project_name}​/repositories​/{repository_name}​/artifacts)
q=scan_overview.scan_status='Success' does not seem to work.
Also filtering for a specific tag e.g. q=tag.name='latest does not work.

**Comment by ywk253100** [comment]
The query for nested object isn't supported.

And filtering for a specific tag, you should use `q=tags=latest`
