### ISSUE TITLE
Got {"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]} when login harbor

### ISSUE THREAD

**Issue by shaobo322** [goharbor/harbor#12393]
version v2.0.0
Post https://192.168.205.11:80/c/login?principal=admin&password=******
got error response Got {"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]} when login harbor

**Comment by reasonerjt** [comment]
It is expected, you need CSRF token.  The login endpoint is for accessing from web browser only.

**Comment by shaobo322** [comment]
how to get a csrf token or is there any rest api to login
