### ISSUE TITLE
Failed to replicate image from Harbor with postgresql connection "too many clients already"

### ISSUE THREAD

**Issue by WenwuPeng** [goharbor/harbor#12406]
It is failed to replicate image from harbor to gitlab, and get postgresql connection  error "too many clients already"

Steps to reproduce the problem:

    1. Setup Harbor A with 20 projects and >1000 images
    2. Setup Harbor B
    3. Create replication rule in Harbor B to replicate the image with pull mode from Harbor A
    4. Trigger the replicate rule.

it is failed to replicate image with error "too many clients already"

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.4
- docker engine version: 19.03.5
- docker-compose version: 1.25.0

**Additional context:**

Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [ERROR] [/common/api/base.go:200]: failed to check the existence of project nokia: pq: sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 postgresql[1247]: FATAL:  sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 postgresql[1247]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [ERROR] [/core/config/config.go:185]: failed to load config, error pq: sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [WARNING] [/core/filter/security.go:153]: Failed to get auth mode, err: pq: sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [ERROR] [/common/api/base.go:200]: failed to check the existence of project nokia: pq: sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [ERROR] [/core/config/config.go:185]: failed to load config, error pq: sorry, too many clients already
Jul  7 01:07:41 172.18.0.1 core[1247]: 2020-07-07T06:07:41Z [WARNING] [/core/filter/security.go:153]: Failed to get auth mode, err: pq: sorry, too many clients already

**Comment by WenwuPeng** [comment]
harbor-core log snippet:

Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:200]: failed to check the existence of project nokia: pq: sorry, too many clients already
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:233]:
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:73]: GET /api/repositories/nokia/cmk/tags failed with error: {"code":500,"message":"Internal Server Error"}
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020/07/07 07:35:21 #033[1;44m[D] [server.go:2774] |  66.170.98.241|#033[41m 500 #033[0m| 124.530178ms|   match|#033[44m GET     #033[0m /api/repositories/nokia/cmk/tags   r:/api/repositories/*/tags#033[0m
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/core/config/config.go:185]: failed to load config, error pq: sorry, too many clients already
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [WARNING] [/core/filter/security.go:153]: Failed to get auth mode, err: pq: sorry, too many clients already
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:200]: failed to check the existence of project nokia: pq: sorry, too many clients already
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:233]:
Jul  7 02:35:21 172.18.0.1 core[1247]: 2020-07-07T07:35:21Z [ERROR] [/common/api/base.go:73]: GET /api/repositories/nokia/ipds/tags failed with error: {"code":500,"message":"Internal Server Error"}

**Comment by heww** [comment]
Closed as we increase the max conns of Postgres in harbor-db to 1024 now. See #12437 to get more info.

And for the versions before 2.x, see FAQ https://github.com/goharbor/harbor/wiki/Harbor-FAQs#modify-the-max-connections-of-the-database-for-versions-less-than-v202 modify the max conns yourself.
