### ISSUE TITLE
Maven support like in Nexus and Artifactory

### ISSUE THREAD

**Issue by 030** [goharbor/harbor#12409]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

* https://www.jfrog.com/confluence/display/JFROG/Maven+Repository
* https://blog.sonatype.com/using-nexus-3-as-your-repository-part-1-maven-artifacts

**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
A clear and concise description of the plan to make the solution ready. It can include a development timeline, resource estimation, and other related things.

**Additional context**

**Comment by reasonerjt** [comment]
Sorry but I'm afraid this is not in the roadmap of Harbor

**Comment by RakeshRaj97** [comment]
Can Maven be included to Harbor in future?
