### ISSUE TITLE
Get an internal server error when failing to add docker-hub type of registry

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#12422]
**Core Log:**
Jul  7 18:12:03 172.23.0.1 core[9549]: 2020-07-07T18:12:03Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 43697015-d874-43cc-ba31-14a1d0dff98c to the logger for the request GET /api/v2.0/registries/3/info
Jul  7 18:12:03 172.23.0.1 core[9549]: 2020-07-07T18:12:03Z [DEBUG] [/server/middleware/security/session.go:47][requestID="43697015-d874-43cc-ba31-14a1d0dff98c"]: a session security context generated for request GET /api/v2.0/registries/3/info
Jul  7 18:12:06 172.23.0.1 core[9549]: 2020-07-07T18:12:06Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to create the adapter for registry 3: login to dockerhub error: Post https://hub.docker.com/v2/users/login/: EOF"}]}

![image](https://user-images.githubusercontent.com/44018302/86868714-d45cba00-c107-11ea-9b5f-ae124d439153.png)

**Comment by reasonerjt** [comment]
is it found in automated test and can it be constantly reproduced?

**Comment by danfengliu** [comment]
Yes, it's found in automation test, and it happened on a rare occasion, not reproducible.

**Comment by bitsf** [comment]
Seems just the dockerhub website happened to out of service.
Close first as not reproduced.
