### ISSUE TITLE
Can't log in for using letters to account?

### ISSUE THREAD

**Issue by dunmorogh1993** [goharbor/harbor#12426]
Hi guys - I do not know why there was a tip that I could not log in with "admin"... It asked me enter a valid email address to log in. Can't "admin" log in?
![image](https://user-images.githubusercontent.com/41850822/86909761-27a42c00-c14b-11ea-95f8-72ee40b4871d.png)

Harbor version: v2.0.1,
Docker version 19.03.12,
OS: ubuntu 20.04 LTS.

Thanks for your help. :)

**Comment by reasonerjt** [comment]
It does not look like Harbor OSS's UI

**Comment by dunmorogh1993** [comment]
> 
> 
> It does not look like Harbor OSS's UI
> 
> Have you forked the code?

Hi @reasonerjt - seems it indeed does not look like what you said... No, I have not, I just followed the guidance to install it. But I found, it is weird, I inputted url with domain, it could be visited but seemed it directed me into another page, but after I inputted url with IP integers, another page looked to be right occurred...
![image](https://user-images.githubusercontent.com/41850822/87004353-dbf78e00-c1ef-11ea-829b-cd8768c8dab8.png)

**Comment by dunmorogh1993** [comment]
Hi @reasonerjt,

Before I used specified domain like "*.harbor.com", so I thought that is why it directed me the wrong page (seems it is official website?).

Now I changed the domain whose second domain does not include "harbor", I can use it correctly and access into login page successfully.

Above, thank you. :-)
