### ISSUE TITLE
Unable to login with default admin password

### ISSUE THREAD

**Issue by limecheng** [goharbor/harbor#12423]
After setting up harbor with admin password of Harbor12345, I tried login to the UI but got an error "Invalid user name or password."

Environment:
OS: Ubuntu 18.04
Harbor: v2.0.0

**Comment by reasonerjt** [comment]
Is it a clean install?

**Comment by 06kellyjac** [comment]
Using helm to install I can successfully log in if I port-forward the main "harbor" service, but if I port-forward "<NAME>-harbor-portal" service I see the same login page but the request never makes it to the "harbor-harbor-core" pods

`helm install harbor harbor/harbor --namespace some-namespace --set expose.type=clusterIP --set expose.tls.enabled=false`

`kubectl -n some-namespace port-forward svc/harbor 8080:80`

**Comment by ankush06** [comment]
you need to add the externalURL
ex:
externalURL: http://10.207.5.1:30032

**Comment by PepsicolaShell** [comment]
In my case I was integrating Harbor installed with Helm with traefik gatewayapi and i was pointing my httproute to the "harbor-portal" svc. Changing it to the correct just "harbor" svc fixed it for me
