### ISSUE TITLE
Client authentication login uses NAT converted address, authentication failed.

### ISSUE THREAD

**Issue by zkf1987** [goharbor/harbor#12431]
Harpor2.0 version
We have a big problem with harpor. We have two environments: the headquarters and the branches. When the branch host logs into the warehouse of the headquarters, NAT conversion is required. In the branch company, we configure the converted address, but the authentication fails all the time?
`docker login 10.10.123.2:30443 -u admin -p 123456
Error response from daemon: Get https://10.10.123.2:30443/v2/: Get https://172.22.23.234:30443/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)(Client.Timeout exceeded while awaiting headers).
`

10.10.123.3 address after nat
172.22.23.234 source address

**Comment by reasonerjt** [comment]
This seems a limitation for now, see comments in 
https://github.com/goharbor/harbor/issues/12396

**Comment by reasonerjt** [comment]
This may be mitigated after the issue 
https://github.com/goharbor/harbor/issues/9794
is resolved.
