### ISSUE TITLE
goharbor/harbor-migrator:v1.10.3 not found

### ISSUE THREAD

**Issue by kmmanto** [goharbor/harbor#12441]
**Expected behavior and actual behavior:**
goharbor/harbor-migrator:v1.10.3 can be pulled and run

**Steps to reproduce the problem:**
docker pull goharbor/harbor-migrator:v1.10.3

**Versions:**

- harbor version: [1.10.3]
- docker engine version: [19.03.8]
- docker-compose version: [1.24.1]

**Comment by ninjadq** [comment]
there is no `goharbor/harbor-migrator:v1.10.3` image, you can use `harbor-migrator:v1.10.0` instead
