### ISSUE TITLE
habor 2.0 support redis cluster  3master 3slavemode

### ISSUE THREAD

**Issue by mzzgaopeng** [goharbor/harbor#12449]
habor 2.0 support redis cluster  3master 3slave mode？

**Comment by reasonerjt** [comment]
Please elaborate your question.

Have you done any experiment on your side and seen any issues?

**Comment by mzzgaopeng** [comment]
harbor 是否支持三主三从的 redis模式

**Comment by reasonerjt** [comment]
Harbor can only talk to one endpoint, you have to setup haproxy.
