### ISSUE TITLE
Cannot create project member using basic auth

### ISSUE THREAD

**Issue by zclyne** [goharbor/harbor#12455]
Hi, I'm developing a REST API client of Harbor with Spring RestTemplate. Since I don't find a specific API for user login, I directly set basic auth to the client. For APIs like creating projects, creating users, and etc., I can successfully call the API with basic auth. However, I cannot use basic auth to perform adding a user as a project's member, namely, calling the `POST /projects/{project_id}/members` API. I got `403 Forbidden: [{"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}. ` It's weird that only this API returns this error while others work well.
Where can I get this CSRF token or does Harbor provide a REST API for user login? Thank you for your help!

**Comment by heww** [comment]
Please disable cookies in the Spring RestTemplate otherwise you should process the CSRF token yourself.

**Comment by zclyne** [comment]
> Please disable cookies in the Spring RestTemplate otherwise you should process the CSRF token yourself.

Thank you for your reply! I'll try it as soon as possible.
