### ISSUE TITLE
Sysdig Scanner for Harbor Image scanning

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#12450]
**Is your feature request related to a problem? Please describe.**
Allow Sysdig Scanner to be used for image scanning in Harbor and add steps on deploying and using to harbor documentation.

The integration work has already been done by the Sysdig team !  Please check out
https://github.com/sysdiglabs/harbor-scanner-sysdig-secure

**Comment by reasonerjt** [comment]
Closing as this is done by sysdig.
