### ISSUE TITLE
Logs unavailable: InvalidPipeArgument: 'Unable to convert "..." to a date' (Firefox)

### ISSUE THREAD

**Issue by tomlankhorst** [goharbor/harbor#12453]
**Expected behavior and actual behavior:**
- Expected: click 'Logs' in sidebar, logs appear
- Actual: click 'Logs' in sidebar, page opens but no logs appear. Spinner keeps spinning. Multiple console errors appear:

```
ERROR Error: InvalidPipeArgument: 'Unable to convert "2020-07-10 06:25:44.51214 +0000 UTC" into a date' for pipe 'e'
```

*Problem appears in Firefox, not in Chrome*

**Steps to reproduce the problem:**
1. Click 'Logs'

**Versions:**
- harbor version: 2.0.1
- docker engine version: 19.03.12
- docker-compose version: 1.25.5
- Firefox version: 78.0.1

**Comment by AllForNothing** [comment]
@tomlankhorst 
Thanks.
It's a duplicated issue, see #1522
We strongly recommend Chrome to visit Harbor UI.
I'm closing this issue, and keep #11522 opened

**Comment by tomlankhorst** [comment]
@AllForNothing 
Thanks for your reply! 

Firefox is a standard adhering browser so valid JavaScript should work without issues. 
There are multiple reasons why I do not have access to a Chrome browser on my device. 

I'm looking forward to a solution. Will #12333 do this?

**Comment by AllForNothing** [comment]
@tomlankhorst 
Yes, it will fix this issue. Harbor 2.1.0 is coming, if needed you can update your Harbor to version 2.1.0
