### ISSUE TITLE
How to restart failed copy task.

### ISSUE THREAD

**Issue by hwdef** [goharbor/harbor#12467]
I created two harbor cluster . set replication policy.
![image](https://user-images.githubusercontent.com/13084946/87287490-bee2f800-c52c-11ea-9082-3d14aa18e797.png)

![image](https://user-images.githubusercontent.com/13084946/87288538-103fb700-c52e-11ea-81d0-2bd3352ecfb7.png)

![image](https://user-images.githubusercontent.com/13084946/87288578-1f266980-c52e-11ea-8a48-4deaa311ecb8.png)

I did an experiment. I shutdown harborA , and push a image to harborB . So harborB have a failed  copy job, but when I started harborA , the failed task is not restarted.

![image](https://user-images.githubusercontent.com/13084946/87288081-72e48300-c52d-11ea-8844-64957f604ad1.png)

**Comment by reasonerjt** [comment]
@hwdef This is by design,  the Harbor A may be down forever and it doesn't make sense to retry forever
If a job failed you need to trigger it again by creating a manually triggered policy.

To make it a little more robust, you can set it to trigger  for example weekly or daily.

**Comment by hwdef** [comment]
@reasonerjt 
thank you for your reply
