### ISSUE TITLE
Can I replicate images from Huawei SWR to harbor through pull mode

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#12466]
What can we help you?
Can I replicate images from Huawei SWR to harbor through pull mode.

**Comment by reasonerjt** [comment]
I think the answer is yes @bitsf could you confirm?

**Comment by bitsf** [comment]
We have a Huawei SWR adapter which contributed by community, so this should work.
However I didn't test this as we don't have setup such environment.
You can test this, and expect for your result.
BTW, you can find contributors from https://github.com/goharbor/community/blob/master/workgroups/wg-replication/README.md

**Comment by Iverson-lena** [comment]
The configuration of push mode can work normally, but when the pull mode is selected, the trigger mode cannot be selected and save the policy on the portal.

**Comment by bitsf** [comment]
SWR adapter does not set the SupportedTriggers correctly, need to check the reason.

https://github.com/goharbor/harbor/blob/bad8f026fcfa2dbf192ae3f0bcc051c47761eb2c/src/replication/adapter/huawei/huawei_adapter.go#L66

**Comment by bitsf** [comment]
@Iverson-lena How did you test this ? Is there a public service or install a private service ?

**Comment by Iverson-lena** [comment]
I've verified the functionality, but there's still a problem. In pull mode, if the source resource filter is configured, it cannot be filtered normally.

**Comment by Iverson-lena** [comment]
I've verified the functionality, but there's still a problem. In pull mode, if the source resource filter is configured, it cannot be filtered normally.
