### ISSUE TITLE
filter for os/architecture when pulling images

### ISSUE THREAD

**Issue by fireba11** [goharbor/harbor#12468]
We want to replicate some images from docker hub to check what the security scanner reports etc.
Replication pulls all architectures, can we somehow filter that? We got no use for the ARM versions :-D
If that is a label that filter option is only available for pushing apparently ...

**Comment by reasonerjt** [comment]
The answer is no,  the unit for replication is artifact and in Harbor it considers the manifest list as an artifact so all referenced images are replicated.

I think it may make sense to support filter to filter manifests in a manifest list.

**Comment by xaleeks** [comment]
I don't foresee changing this behavior, it's not the same thing as a pull which is like a deploy, replication is more for keeping things in sync
