### ISSUE TITLE
[harbor-portal] Repository not fount when the repo contains the project name field

### ISSUE THREAD

**Issue by zeed-w-beez** [goharbor/harbor#12460]
I found the bug in `goharbor/harbor-portal:v2.0.1`, and the PR <https://github.com/goharbor/harbor/pull/12391> has been merged into `master branch`.

This is a serious UI bug, can you Release a small version for this bug fix?

**Steps to reproduce the problem:**

docker push harbor.example.com/test/abc/test/alpine:3

![image](https://user-images.githubusercontent.com/20834022/87222077-59173480-c3a3-11ea-887e-3ffa01ebd79c.png)

![image](https://user-images.githubusercontent.com/20834022/87222079-5c122500-c3a3-11ea-93be-c7d1e4deeb78.png)

**Comment by reasonerjt** [comment]
We will cherrypick the fix into 2.0.x patch

**Comment by AllForNothing** [comment]
duplicated with #12500
