### ISSUE TITLE
Docker goharbor/registry-photon: wrong permissions on named volume

### ISSUE THREAD

**Issue by carlbalmer** [goharbor/harbor#12463]
If using named volumes instead of mounting the host folders generated by `goharbor/prepare` the permissions for `/storage` are wrong (root:root instead of harbor:harbor). This leads to an error `filesystem: mkdir /storage/docker: permission denied` when trying to upload an image.
**Expected behavior and actual behavior:**
Expected:
adding named volume the permission on `/storage` should be harbor:harbor

Actual:
adding named volume the permission on `/storage` is root:root

**Steps to reproduce the problem:**
```
docker run -it --rm --entrypoint=/bin/bash goharbor/registry-photon:v2.0.0
mkdir storage/docker
```

**Versions:**

- harbor version: v2.0.0
- docker engine version: 19.03.12
- docker-compose version: 1.25.5

**Additional context:**
error form registry.log:
```
registry[1800]: time="2020-07-12T07:52:30.228936096Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="filesystem: mkdir /storage/docker: permission denied" err.message="unknown error" go.version=go1.13.8 http.request.host="proxy:8080" http.request.id=f71abc7b-a246-41bc-b36b-736cb409470
e http.request.method=POST http.request.remoteaddr=172.18.0.4 http.request.uri="/v2/test/nginx/blobs/uploads/" http.request.useragent="docker/19.03.9 go/go1.13.10 git-commit/9d988398e7 kernel/5.3.0-62-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.9 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=23.216667ms http.response.status=500 http.response.written=155 vars.name="test/nginx"
```

**Comment by reasonerjt** [comment]
There should be a way to set the perm of named volume before it's mounted?

**Comment by Weasy666** [comment]
I have the same problem. In the compose file i changed the `registry` volume to
``` yaml
    volumes:
          - docker_registry:/storage:rw
```
and am getting the `err.detail="filesystem: mkdir /storage/docker: permission denied"` error. Looking into the running container gives me the following permissions for the `storage` folder/volume
```
drwxr-xr-x   2 root root 4096 2020-08-19 07:25 storage
```

after changing the owner manually, everything works as expected.

**Comment by Weasy666** [comment]
Any thoughts on this? (This comment is mostly to keep the issue open)
