### ISSUE TITLE
Unable to use groups with LDAP auth

### ISSUE THREAD

**Issue by mattdowdell** [goharbor/harbor#12470]
I think this is a quirk of the LDAP server I'm using, but posting on the off chance it's been seen before (looks pretty similar to #6608).

As far as I can tell, my LDAP server does not return groups for a user when looking up the user. Example ldapsearch output (redacting personal info):

```
ldapsearch -H 'ldaps://ldap.example.com' -b 'O=example.com' -x 'uid=me@example.com' \* +
# extended LDIF
#
# LDAPv3
# base <O=example.com> with scope subtree
# filter: uid=me@example.com
# requesting: * +
#

# me@example.com, People, example.com
dn: uid=me@example.com,ou=People,o=example.com
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: ntUser
objectClass: posixAccount
givenName: Matthew
sn: Dowdell
cn: Matthew Dowdell
uid: me@example.com
mail: me@example.com
structuralObjectClass: inetOrgPerson
entryUUID: 1a69ca0e-97df-1036-90db-11dc3dd49176
creatorsName: cn=foo.example.com,ou=servers,o=example.com
createTimestamp: 20170308000829Z
l: Example
postalCode: XXXX XXX
c: GB
co: United Kingdom
homeDirectory: /home/me
gidNumber: 6347
st: Example
ou: Example
o: Example
entryCSN: 20200501121314.621847Z#000000#002#000000
modifiersName: cn=foo.example.net,ou=servers,o=example.com
modifyTimestamp: 20200501121314Z
entryDN: uid=me@example.com,ou=People,o=hp.com
subschemaSubentry: cn=Subschema
hasSubordinates: FALSE

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

I can look up groups and they work fine. But there's nothing on the user lookup to indicate if I'm a member of the group. Not sure if this is a standard setup. You can get the groups you're a member of with something like the following instead:

```
ldapsearch -h ldap.example.com -LLL -x -b "o=example.com" '(&(objectClass=groupOfNames)(member=uid=me@example.com,ou=People,o=example.com))' dn
```

Is there anything that can be done here without appealing to whoever manages my LDAP server to change something in there?

**Comment by stonezdj** [comment]
To enable the LDAP group feature in Harbor, the LDAP server should enable the `memberof overlay`,  when adding a user mike to a group harbor_user, the harbor_user's attribute member should contain an item mike's DN, and the user mike's attribute memberof should contain the group harbor_user's DN.

**Comment by mattdowdell** [comment]
@stonezdj is that documented anywhere? It's not implausible that the LDAP server and harbor are owned by different people/teams.
