### ISSUE TITLE
Swagger in API explorer is incomplete

### ISSUE THREAD

**Issue by mattdowdell** [goharbor/harbor#12474]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The swagger used for the API explorer appears to be incomplete. I created an ansible playbook to configure as much as possible automatically, including the user authentication. Some of the attributes in the configurations endpoint are missing, notably those used for LDAP configuration. To get them, I had to inspect the network response in the GUI using browser devtools and figure out which fields were missing. It would be more helpful if the names fields in the GUI matched those in API too so you can tell how they match up or use the documentation.

Not sure how widespread the issue is, but the API explorer makes things much harder than necessary, e.g. no obvious order to endpoints meaning it's hard to find the endpoint you want. The lack of attributes suggests that the swagger is generated from code rather than code is generated from swagger or that an old version is being served.

**Steps to reproduce the problem:**
Attempt to configure LDAP authentication in the GUI. Take each field that exists for that and map it to those in the corresponding API. Observe a few attributes are left over.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.1
- docker engine version: 19.06
- docker-compose version: 1.26

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
@mattdowdell 
It is true that the legacy swagger was not used to generate code.

Could you clarify which particular API has the problem so we can check and fix?

**Comment by mattdowdell** [comment]
The models used for /configurations GET/PUT were the ones I noticed. Not sure if there's more.

**Comment by j-zimnowoda** [comment]
Indeed.

For example the `oidc_groups_claim` property is missing in `Configurations` schema.

**Comment by mattdowdell** [comment]
Also noticed the limited guest group (role_id: 5) is missing from the model docs used for listing/creating members in a project `/projects/{project_id}/members`. I guess this should ideally be an enum?

**Comment by mattdowdell** [comment]
`POST /projects/{project_id}/immutabletagrules` lists the example model (and by extension the used model) to have a field named `tag_filter`. This looks to be an earlier version of the API as what actually gets sent when using the GUI is:

```json
{
    "disabled": false,
    "action": "immutable",
    "scope_selectors": {
        "repository": [
            {
                "kind": "doublestar",
                "decoration": "repoMatches",
                "pattern":"**"
            }
        ]
    },
    "tag_selectors": [
        {
            "kind":"doublestar",
            "decoration":"matches",
            "pattern":"**"
        }
    ],
    "project_id":4,
    "priority":0,
    "template":"immutable_template"
}
```

**Comment by nolte** [comment]
Hi, 

I am Using the Swagger Spac for generate a go api client, used for [nolte/terraform-provider-harbor](https://github.com/nolte/terraform-provider-harbor) and i have the same problem.

Some Generated API methods, din`t work again the Harbor RestAPI (Tested with Version v2.1.0, v2.0.1).
I use [JSON Patch](https://en.wikipedia.org/wiki/JSON_Patch) for change the Swagger Spec before generate the go client. 
 
Here is a Link to the: [JSon Patch](https://github.com/nolte/terraform-provider-harbor/blob/40017c79704eb7e6ee009105395135924e8ff0db/scripts/swagger-specs/patch.1.json).

I hope it helps for locate other miss matches.

**Comment by mattdowdell** [comment]
Found another issue, this time in the non-legacy swagger. This is the returned response for the listArtifacts operation (/projects/{project_name}/repositories/{repository_name}/artifacts):

```json
[
  {
    "addition_links": {
      "build_history": {
        "absolute": false,
        "href": "/api/v2.0/projects/my-project/repositories/my-repo/artifacts/sha256:ad028994bc47a14c1c7348bb052128c69baa45cf67312a59477e3997ea748398/additions/build_history"
      },
      "vulnerabilities": {
        "absolute": false,
        "href": "/api/v2.0/projects/my-project/repositories/my-reo/artifacts/sha256:ad028994bc47a14c1c7348bb052128c69baa45cf67312a59477e3997ea748398/additions/vulnerabilities"
      }
    },
    "digest": "sha256:ad028994bc47a14c1c7348bb052128c69baa45cf67312a59477e3997ea748398",
    "extra_attrs": {
      "architecture": "amd64",
      "author": null,
      "created": "2020-07-14T10:40:12.096417537+01:00",
      "os": "linux"
    },
    "id": 6,
    "labels": null,
    "manifest_media_type": "application/vnd.docker.distribution.manifest.v2+json",
    "media_type": "application/vnd.docker.container.image.v1+json",
    "project_id": 3,
    "pull_time": "2020-07-14T10:59:08.256Z",
    "push_time": "2020-07-14T10:57:17.343Z",
    "references": null,
    "repository_id": 5,
    "size": 22675460,
    "tags": [
      {
        "artifact_id": 6,
        "id": 6,
        "immutable": false,
        "name": "1.0.84-0-g7791815",
        "pull_time": "0001-01-01T00:00:00.000Z",
        "push_time": "2020-07-14T10:57:17.387Z",
        "repository_id": 5,
        "signed": false
      }
    ],
    "type": "IMAGE"
  }
]
```

Here we see extra_attrs is a series of string values:
```
    "extra_attrs": {
      "architecture": "amd64",
      "author": null,
      "created": "2020-07-14T10:40:12.096417537+01:00",
      "os": "linux"
    },
```

But the model in the swagger claims the values to be objects:

```
  ExtraAttrs:
    type: object
    additionalProperties:
      type: object
```

I can't tell if this was correct for the other 3 places that use it, but it's not correct here.

**Comment by mattdowdell** [comment]
Also found 3 instance of `format: int` in https://github.com/goharbor/harbor/blob/v2.0.1/api/v2.0/swagger.yaml#L1062-L1075. This is incorrect - it should be int32 or int64 per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by mattdowdell** [comment]
Found another issue in the `AdminJobSchedule` model used in `GET /system/scanAll/schedule`. The model claims the following example:

```json
{
  "parameters": {
    "additionalProp1": true,
    "additionalProp2": true,
    "additionalProp3": true
  },
  "schedule": {
    "cron": "string",
    "type": "string"
  }
}
```

But when running the request in the API explorer, we see the following:

```json
{
  "schedule": {
    "type": "Weekly",
    "cron": "0 0 0 * * 0"
  },
  "id": 0,
  "job_name": "",
  "job_kind": "",
  "job_parameters": "null",
  "job_status": "",
  "deleted": false,
  "creation_time": "0001-01-01T00:00:00Z",
  "update_time": "0001-01-01T00:00:00Z"
}
```

----

Found another niggle in that the [legacy swagger](https://github.com/goharbor/harbor/blob/master/api/v2.0/legacy_swagger.yaml#L6) sets host=localhost which means any generated client will default to localhost instead of using the one you provide it when creating the client instance. Depending on how you generate the client, this may not even be possible and you have to patch the swagger before it generates the client. Can this just be removed as it seems particularly suited to testing but not much else.

----

@reasonerjt I'm happy to keep posting these as I automate the configuration of my harbor instance, but this feels somewhat neverending. Either way, I'd suggest the current pending-for-more-info tag has outlived it's use here, so could it be tagged to reflect the documented issues here?

I'd love to be able to generate a client using something like [bravado](https://github.com/Yelp/bravado), but there's so many issues here it ends up being more effort to keep patching to documented swagger than it is to hack some calls together.

**Comment by mattdowdell** [comment]
Following on from the previous post, I found that there's a model within `AdminJobSchedule` named `AdminJobScheduleObj` that contains the schedule params, e.g. the object within `schedule`:

```json
"schedule": {
    "type": "Weekly",
    "cron": "0 0 0 * * 0"
  },
```

However, what isn't obvious is that the object within `schedule` is set to `None` when no schedule is configured. This is in contrast to `GET /system/gc/schedule` which does populate the corresponding model with empty values, e.g.:

```
"schedule": {
    "type": "None",
    "cron": ""
}
```

This one isn't a swagger bug per se, but it would be good to have consistency in the API implementations.

**Comment by mattdowdell** [comment]
Bump

**Comment by stonezdj** [comment]
After refactoring APIs to the new programming model, this issue should be fixed.
