### ISSUE TITLE
Internal Server Error: While create (GCR) registry endpoint. || invalid key size 35

### ISSUE THREAD

**Issue by amitdah4** [goharbor/harbor#12475]
Issue: Getting Internal server error while adding Google container registry.

Habor Helm chart used to deploy in kubernetes: harbor/harbor

I have found below error in core service logs:
```
[ERROR] [/replication/registry/manager.go:124]: Convert registry model to dao layer model error: crypto/aes: invalid key size 35
2020-07-14T06:51:59Z [ERROR] [/core/api/registry.go:231]: Add registry 'https://gcr.io' error: crypto/aes: invalid key size 35
2020-07-14T06:51:59Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"crypto/aes: invalid key size 35"}]}
/harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
/harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
/harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
/harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
/harbor/src/core/api/registry.go:232, github.com/goharbor/harbor/src/core/api.(*RegistryAPI).Post
```

Please refer below snapshot.
![ha](https://user-images.githubusercontent.com/41111515/87398115-1176ef80-c5d3-11ea-89a1-327002b18cc1.PNG)

**Comment by reasonerjt** [comment]
@amitdah4 is it GCR specific?

**Comment by amitdah4** [comment]
**helm hub** as registry endpoint is working fine.

For _Google container registry_, It is throwing error.

**Comment by amitdah4** [comment]
@reasonerjt Any update on this issue?

**Comment by bitsf** [comment]
from the error message, your Google token file is not complete, please check if you are pasting all the original json file download from google.

**Comment by bitsf** [comment]
from the error message, your Google token file is not complete, please check if you are pasting all the original json file download from google.

**Comment by amitdah4** [comment]
@bitsf I have cross checked. I am passing correct json file.

Apart from that.. I have tried to add **docker-hub**  as registry endpoint and I am getting same error.

Please check.

**Comment by amitdah4** [comment]
@reasonerjt Please update. I have cross checked. I am facing same issue with docker hub as well.

**Comment by bitsf** [comment]
oh, I just realize the problem, your encrypt key which used to encrypt the password saving in db, is not correct.

**Comment by bitsf** [comment]
you can check the file /data/secret/keys/secretkey, which should contain only 16 characters.

**Comment by amitdah4** [comment]
Thank you @bitsf . I was using encrypt-key having length of 35 character.

I have changed it to exact 16 characters and it is working fine. You can close this ticket now.
