### ISSUE TITLE
Internal server error reported when saving replications rules

### ISSUE THREAD

**Issue by fz8770** [goharbor/harbor#12488]
**Versions:**
Please specify the versions of following systems.

- harbor version: v1.10.4-417e12ec
- docker engine version: 19.03.11
- docker-compose version: 1.26.0

 Re-edit the rule, when saving the rule, there will be an internal server error
Please see the screenshot

delete the rule also will be an internal server error

tail -f core.log 

Jul 15 18:02:19 172.22.0.1 core[1391]: 2020-07-15T10:02:19Z [ERROR] [/common/api/base.go:233]: failed to update the policy 1: failed to unschedule the policy 1: status behind error
Jul 15 18:02:19 172.22.0.1 core[1391]: 2020-07-15T10:02:19Z [ERROR] [/common/api/base.go:73]: PUT /api/replication/policies/1 failed with error: {"code":500,"message":"Internal Server Error"}

![222](https://user-images.githubusercontent.com/50136484/87534163-38fbb400-c6c8-11ea-8e26-c4db2496f858.png)
![333](https://user-images.githubusercontent.com/50136484/87534174-3c8f3b00-c6c8-11ea-9f22-862a5d5423da.png)

**Comment by bitsf** [comment]
@ywk253100 This seems fixed in 2.x ?

**Comment by ywk253100** [comment]
@bitsf Yes, this is fixed in v2.0.0

**Comment by fz8770** [comment]
@ywk253100  I hope fix this problem in the v1.10.5 version.
