### ISSUE TITLE
harbor API swagger file does not match with API interface on Quota resource

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#12482]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

1. in swagger file, quota is kind of int type

"quota": {
    "type": "object", 
    "properties": {
        "hard": {
            "description": "The hard limits of the quota", 
            "$ref": "#/definitions/ResourceList"
         }, 
        "used": {
            "description": "The used status of the quota", 
            "$ref": "#/definitions/ResourceList"
        }
    }
}

"ResourceList": {
            "additionalProperties": {
                **"type": "integer"**
            },
            "type": "object"
        },

2. but API interface, it's not a integer, for example 50GB, 53687091200 is not a integer.

{
  "repo_count": 0,
  "chart_count": 0,
  "project_admin_count": 1,
  "master_count": 0,
  "developer_count": 0,
  "guest_count": 0,
  "limited_guest_count": 0,
  "quota": {
    "hard": {
      "count": 50,
      **"storage": 53687091200 <- 50GB is not integer**
    },
    "used": {
      "count": 0,
      "storage": 0
    }
  }
}

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by danielzhanghl** [comment]
hi, any plan to get it fixed? thanks.

**Comment by heww** [comment]
We will fix this in 2.1 and backport to 2.0.x and 1.10.x

**Comment by danielzhanghl** [comment]
thanks for the p

**Comment by heww** [comment]
According to the spec of swagger, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types, the `integer` type support int64, so we will only format the value of `ResourceList` as int64 to fix this issue.
