### ISSUE TITLE
GPG verification generates warning

### ISSUE THREAD

**Issue by tdensmore** [goharbor/harbor#12486]
The [current online install documentation](https://goharbor.io/docs/2.0.0/install-config/download-installer/) describes the steps to verify the tarball and check the signature:

<img width="655" alt="signature" src="https://user-images.githubusercontent.com/469399/87503122-65b0bc80-c631-11ea-9f90-25d3d36a50a5.png">

However when I run the command, I get a warning:

**gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.**

As seen in this screenshot:

<img width="1171" alt="warning" src="https://user-images.githubusercontent.com/469399/87503135-6e08f780-c631-11ea-9300-33a48beadd84.png">

**Comment by bitsf** [comment]
Hi, jiangd is the maintainer, this is good signature, as we didn't spend money to apply verified cert for open source harbor yet.

**Comment by tdensmore** [comment]
First, I don't understand that thought process at all. Spend money to verify that your product (free or paid) has a valid signature.

Second, if you don't want to provide assurance that your product is what you say it is (and you are who you say you are), you might want to update the online documentation to show users that they will receive a WARNING when they follow the instructions that you provided. If you do not update the documentation, users will think that the tarball has been compromised, right?

**Comment by bitsf** [comment]
Hi, we are just reference some other popular open source project that also use the maintainer's own GPG key to do sign.

@xaleeks Can you check this if the document can be improved or maybe apply a good GPG key from CNCF.

**Comment by bitsf** [comment]
add warning info in doc to make it more accurate now before we may have a trusted key
