### ISSUE TITLE
Replication can not sync all the repositories from source registry

### ISSUE THREAD

**Issue by fred214** [goharbor/harbor#12495]
I made a scheduled replication from azure ecr to harbor, It works well.
Recently I found harbor missing a docker image with a specific tag, but it exists in the source azure ecr.
I have to copy image from azure ecr to harbor by using skopeo

The harbor version is v1.10.3-6990ccaa, is there any issue about replication in this version?

**Comment by bitsf** [comment]
what specific tag, make it clear.

**Comment by bitsf** [comment]
close as no more info
