### ISSUE TITLE
Errors getting repositories

### ISSUE THREAD

**Issue by linux-user001** [goharbor/harbor#12500]
Hi
I recently mirrored images to harbor with the "oc" tool provided by RedHat for Openshift clusters.
I use this tool because it needs to mirror the images from one registry to the other without changing the digests of the images in the target repository , and Openshift's components use specific digests to pull images.

For some reason , I mirrored 227 images to my harbor instance, but when trying to go to any of those images in the harbor portal I get internal errors.

I have a project named operators , and then inside I have around 227 repositories that I cannot use harbor to do anything with them.

For example, inside "operators" project, trying to get into "redhat-operators/datagrid/datagrid8-rhel8"
 causes the following error:
repository operators/redhat- not found
![IMG_20200716_133039](https://user-images.githubusercontent.com/47380344/87661156-d6a6c000-c768-11ea-81ff-5e649d0ebe56.jpg)
![IMG_20200716_133117](https://user-images.githubusercontent.com/47380344/87661192-e4f4dc00-c768-11ea-8794-bb0d8cc66444.jpg)

Also, trying to delete the following repository using the API doesn't work.

Command :
curl -u username:password 'https://harbor-prod.domain.dom/api/v2.0/projects/operators/repositories/redhat-operators/datagrid/datagrid8-rhel8' -X DELETE --cert /etc/harbor/harbor.crt --key /etc/harbor/harbor.key --cacert /etc/harbor/ca.crt

Output:
{"errors":[{"code":"NOT_FOUND","message":"path /api/v2.0/api/v2.0/projects/operators/repositories/redhat-operators/datagrid/datagrid8-rhel8 was not found

Although I CAN see this repository in the list of repositories when getting inside the "operators" project.

**Versions:**
Please specify the versions of following systems.

harbor version: v2.0.1-d714b3ea
docker engine version: 19.03.5
docker-compose version: 1.23.2

**Environment**
This is a highly-secured  private network instance , so I cannot get any logs out unfortunately.

**Comment by linux-user001** [comment]
@AllForNothing This issue also effects getting the artifacts from the API ?
Because in my case I wasn't even able to get the repository with an API request.

**Comment by AllForNothing** [comment]
@linux-user001 you need to encode the repository name twice for your API request
