### ISSUE TITLE
When delete a registry with a proxy project failed, it should prompt some error message

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#12514]
When create a proxy cache project and associate a registry to proxy
Then go back to delete the registry, it just failed without any error message.
<img width="998" alt="Screen Shot 2020-07-17 at 5 18 57 PM" src="https://user-images.githubusercontent.com/2696760/87770632-d7ffe780-c851-11ea-9b2f-e952bd203291.png">

**Comment by AllForNothing** [comment]
fixed by #12508
