### ISSUE TITLE
Updating service joomla_xx xxxx  image xxx could not be accessed on a registry to record  its digest. Each node will access XXregistryxx independently,  possibly leading to different nodes running different  versions of the image.

### ISSUE THREAD

**Issue by chiru6003** [goharbor/harbor#12523]
Updated the cerificates and tried to deploy joomla site from gitlab job. Getting the following error and website is down.
Updating service joomla_xx xxxx  image xxx could not be accessed on a registry to record  its digest. Each node will access XXregistryxx independently,  possibly leading to different nodes running different  versions of the image.

When checked in the harbor GUI log it is not showing pull log. 

**Steps to reproduce the problem:**
Updated the certificates and ran ./prepare and docker-compose down -v and 

docker-compose up -d

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.1
- docker engine version: 18.09.9,
- docker-compose version: 1.24.1,

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by heww** [comment]
Please use the digest to pull the image rather than use the tag.

**Comment by reasonerjt** [comment]
@chiru6003 
I don't quite understand the problem based on your description...

**Comment by chiru6003** [comment]
> Please use the digest to pull the image rather than use the tag.

Can you please elaborate on where to add this. 
[
![Pipeline issue](https://user-images.githubusercontent.com/32079721/87940673-fa6b4e00-ca67-11ea-9c69-62d1f6f3f70a.PNG)
](url)

**Comment by chiru6003** [comment]
> @chiru6003
> I don't quite understand the problem based on your description...

Hi @reasonerjt Thanks for your reply. I have harbor setup on the server. And I am trying to deploy services by creating a new image and pushing it and pulling it from and to the harbor. My SSL certs of the harbor are going to expire so got new certs and added on the server followed by harbor service down and up docker-compose commands. Certs are upgraded as expected but when I tried to deploy a site from my gitlab. Getting this issue at docker stack deploy level. 

Let me know if you need any further info.
![Pipeline issue](https://user-images.githubusercontent.com/32079721/87941320-f8ee5580-ca68-11ea-8f99-b49b9a794df9.PNG)

**Comment by heww** [comment]
Some issues related to this problem.

https://github.com/moby/moby/issues/34153
https://github.com/containerd/containerd/issues/3291
