### ISSUE TITLE
An error occours when manully execute p2p-preheat policy

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#12527]
1. Request:
![image](https://user-images.githubusercontent.com/30999793/87896785-d9145d00-ca7b-11ea-9438-d434aeedfaea.png)
2.Response:
 ![image](https://user-images.githubusercontent.com/30999793/87896844-0bbe5580-ca7c-11ea-905c-08cca946d98f.png)
3.Log
![image](https://user-images.githubusercontent.com/30999793/87897826-129a9780-ca7f-11ea-86b7-48fa1e77de75.png)

**Comment by steven-zou** [comment]
Verified in the community demo.
