### ISSUE TITLE
MacOS - chown: '/var/log/docker' to '10000:10000': Operation not permitted

### ISSUE THREAD

**Issue by zi-l** [goharbor/harbor#12524]
**issue**

`failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused`

 Some containers fail to startup when I try to install with command ```sudo ./install.sh``` or ```sudo docker-compose down -v && sudo docker-compose up -d```:

```
[Step 5]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
Creating harbor-log ... done
Creating redis         ... error
Creating harbor-db  ... 
Creating harbor-portal ... 
Creating harbor-db     ... error
Creating registry      ... 

Creating harbor-portal ... done
Creating registryctl   ... done
Creating registry      ... done

ERROR: for redis  Cannot start service redis: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused
ERROR: for postgresql  Cannot start service postgresql: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused
ERROR: Encountered errors while bringing up the project.
```
**Steps to reproduce the problem:**

- Config Harbor with `HTTP` following [Connecting to Harbor via HTTP](https://github.com/goharbor/harbor/blob/master/docs/install-config/run-installer-script.md#connecting-to-harbor-via-http-connect-http)，
    - http port is set to `80`,`81` or `5000` on `harbor.yml`, and comment out the `HTTPS` config.
    - log location is set to `/private/var/log/harbor` and give `g+w` for `/privatre/var/log` (the actual location of `/var/log/harbor`, to avoid not shared error)
    - data_volume is set to `/Users/data` (to avoid not shared error)
- `daemon.json` config: `"insecure-registries" : ["<ip>:5000", "0.0.0.0"]` or`"insecure-registries" : ["<ip>:<port>", "0.0.0.0"]`
- Run `sudo ./install.sh` or `sudo docker-compose down -v && sudo docker-compose up -d`

**Versions:**

- OS: MacOS 10.15.1
- harbor version: Tested with `v1.10.4`/` v2.0.1`
- docker engine version: `19.03.8, build afacb8b`
- docker-compose version: `1.25.5, build 8a1c60f6`

**Additional context:**

- **Log files:** got nothing in `/var/log/harbor/` .
- `sudo docker-compose logs log`:
```
Attaching to harbor-log
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
harbor-log     | chown: '/var/log/docker' to '10000:10000': Operation not permitted
```
- Related issue/PR:
    - [PR](https://github.com/goharbor/harbor/pull/6913) for #6895
    - #8300 

***Notice***: It's fine if set log location to a path owned by current user, but can harbor used by all users?

**Comment by ninjadq** [comment]
Did you set log file path in file sharing of your Mac's docker resource

**Comment by zi-l** [comment]
@ninjadq Yes, both `/var/log` and `/var/log/docker`

**Comment by zi-l** [comment]
@ninjadq `sudo ./install.sh` does not create directory `/private/var/log/docker` , it's manually created by myself

**Comment by ninjadq** [comment]
did you change the permission in `/private/var/log/docker` dir?

**Comment by zi-l** [comment]
@ninjadq I give `g+w` for `/privatre/var/log/docker`

**Comment by ninjadq** [comment]
I think create file or dir on that dir need `x` permission

**Comment by zi-l** [comment]
@ninjadq 
here it is.
![a](https://user-images.githubusercontent.com/25576713/88536504-7d7b3e00-d03e-11ea-8a81-24f45f2b664a.jpg)

**Comment by ninjadq** [comment]
I suggest try to set `/var/log` directly instead of `/private/var/log`

**Comment by zi-l** [comment]
> I suggest try to set `/var/log` directly instead of `/private/var/log`

@ninjadq 
It's a link to `/private/var`. 
![var](https://user-images.githubusercontent.com/25576713/89201385-01579c00-d5e4-11ea-928c-34fe7fd054d5.jpg)
And seems I cannot set `/var/log` directly on Docker

**Comment by ninjadq** [comment]
What error messages?
Because sometimes there are some problems when mount a link

**Comment by zi-l** [comment]
@ninjadq 
sorry for not replying soon.
how could I mount a link? I am not clear about this.
I am using `Docker.app`, sharing settings directs me to the actual location `/private/var/log` of `/var/log`, I am not able to set `/var/log`

**Comment by zi-l** [comment]
@ninjadq 
I think I've understand.
as [Steps to reproduce the problem](https://github.com/goharbor/harbor/issues/12524#issue-660682162) described, I switch to `/private/var/log` for this error when using `/var/log`:
![mount_denied](https://user-images.githubusercontent.com/25576713/90794274-2e73b080-e33f-11ea-9f46-678f62fa4a35.jpg)
