### ISSUE TITLE
宿主机主机名被篡改为harbor的hostname  The host machine hostname is tampered with as harbor's hostname

### ISSUE THREAD

**Issue by mytting** [goharbor/harbor#12526]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.10.1
- docker engine version: 18.09.6  19.03.12
- docker-compose version: 1.23.2
- centos7 2003     kernel4.4.220-1   4.4.230-1      

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

After I installed Harbor, the host name of harobR's host was changed to Harbor's hostname

**Comment by mytting** [comment]
CentOS Linux release 7.6.181  kernel 4.4.184-1   not have this problem

**Comment by reasonerjt** [comment]
@mytting I don't think Harbor's installation script will update the `/etc/hostname`
