### ISSUE TITLE
Clarify the support of different PostgreSQL  versions

### ISSUE THREAD

**Issue by jsuchome** [goharbor/harbor#12522]
AFAICS, Harbor only mentions the requirement for **High available PostgreSQL database** when installing via Helm chart and requiring external database.

When internal database is deployed, photon-based `harbor-db` image actually uses version 9.6.14.

So the question/AI is this: documentation should explain what version is required, if there's hard requirement.

Or, even better, official image could be bumped to use more recent version, or such goal could be present at some Roadmap.

FWIW, I've tested it myself with (SUSE based) postgresql12 image and everything seems to work fine.

**Comment by PavloZabudskyi** [comment]
It would be nice to have newer postgresql version.
Currently we have issue with initial harbor deployment with glusterfs.
We used image based on postgresql 12 version and it works.
