### ISSUE TITLE
Tag filter is ignored in execution of pull replication rule

### ISSUE THREAD

**Issue by auberta2** [goharbor/harbor#12533]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A replication rule has been created with a specific image and tag to be pulled. When executing, all tags are being pulled and the tag filter is ignored.
<img width="696" alt="Screenshot 2020-07-20 at 12 20 24" src="https://user-images.githubusercontent.com/33618644/87927430-7921b480-ca83-11ea-861d-5af6662203f1.png">
<img width="1398" alt="Screenshot 2020-07-20 at 12 20 40" src="https://user-images.githubusercontent.com/33618644/87927420-7757f100-ca83-11ea-93b0-0d31496660af.png">

**Steps to reproduce the problem:**
Create a pull replication rule with a specific tag filter. Execute it. See that all tags get pulled no matter the filter.

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.0.1]
- kubernetes :
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Additional context:**

Harbor is setup with helm chart using these settings : 
`helm upgrade --wait --install harbor harbor/harbor --namespace harbor \
  --set expose.ingress.hosts.core=harbor.$CLUSTER_NAME \
  --set expose.ingress.hosts.notary=notary.$CLUSTER_NAME \
  --set harborAdminPassword=$KUBLR_PASSWORD \
  --set-string expose.ingress.annotations."kubernetes\.io/tls-acme"=true \
  --set expose.tls.secretName=harbor-secret \
  --set expose.tls.notarySecretName=notary-secret \
  --set externalURL=https://harbor.$CLUSTER_NAME
`

**Comment by bitsf** [comment]
Not reproduced with dockerhub adapter. Not sure what you are using
![image](https://user-images.githubusercontent.com/188115/91422956-75572e00-e88a-11ea-9930-3f05901604c6.png)
![image](https://user-images.githubusercontent.com/188115/91423008-843de080-e88a-11ea-9034-b29c25870d95.png)

**Comment by bitsf** [comment]
close first as not reproduced and no more info

**Comment by schmel** [comment]
same issue. Gitlab registry. 
My filter is: 
![image](https://user-images.githubusercontent.com/1849390/111186258-e6aac400-85c3-11eb-8132-36b4766eb88e.png)

But, this sync all tags. 

![image](https://user-images.githubusercontent.com/1849390/111186613-39847b80-85c4-11eb-88d4-420767924591.png)
