### ISSUE TITLE
404 Error when using Azure as OIDC Provider

### ISSUE THREAD

**Issue by fl-max** [goharbor/harbor#12535]
### Issue
When configuring Authentication to use OIDC as the "Auth Mode" and using Azure as the Provider, the UI is giving the error "failed to verify connection" and the logs give:

```bash
2020-07-20T14:55:14Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 109256439487f6cc1afcd0337b4e7189 to the logger for the request POST /api/v2.0/system/oidc/ping
2020-07-20T14:55:14Z [DEBUG] [/server/middleware/security/session.go:47][requestID="109256439487f6cc1afcd0337b4e7189"]: a session security context generated for request POST /api/v2.0/system/oidc/ping
2020-07-20T14:55:14Z [ERROR] [/core/api/oidc.go:53]: Failed to verify connection: {URL:https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize VerifyCert:true}, err: 404 Not Found: 
2020-07-20T14:55:14Z [DEBUG] [/server/error/error.go:58]: {"errors":[{"code":"BAD_REQUEST","message":"failed to verify connection"}]}
2020/07/20 14:55:14.726 [D] [transaction.go:62]  | 10.225.172.130| 400 |   17.08772ms|   match| POST     /api/v2.0/system/oidc/ping   r:/api/v2.0/system/oidc/ping
2020-07-20T14:55:21Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 2a756a5f-5068-4413-a9a4-c0ab1fe55b0e to the logger for the request GET /api/v2.0/ping
2020-07-20T14:55:21Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="2a756a5f-5068-4413-a9a4-c0ab1fe55b0e"]: an unauthorized security context generated for request GET /api/v2.0/ping
2020/07/20 14:55:21.135 [D] [transaction.go:62]  | 10.225.172.193| 200 |    211.005µs|   match| GET      /api/v2.0/ping   r:/api/v2.0/ping
2020-07-20T14:55:22Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 92b4227b-aff9-4b67-9008-f7cfc3360a09 to the logger for the request GET /api/v2.0/ping
2020-07-20T14:55:22Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="92b4227b-aff9-4b67-9008-f7cfc3360a09"]: an unauthorized security context generated for request GET /api/v2.0/ping
```

### OIDC Configuration:
**Auth Mode:** OIDC
**OIDC Provider Name:** Azure
**OIDC Endpoint:** https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize
**OIDC Client ID:** <azure_appreg_client_id>
**OIDC Client Secret:** <azure_appreg_client_secret>
**Group Claim Name:** blank
**OIDC Scope:** openid,offline_access,email
**Verify Certificate:** checked

### Azure App Registration Configuration:
**Redirect URI:** https://harbor.my.fqdn.com/c/oidc/callback
**Implicit grant:** `ID tokens` checked
**Supported account types:** Accounts in this organizational directory only
**API Permissions:**
- Microsoft.Graph.User.Read (Delegated)
- Microsoft.Graph.User.Read.All (Delegated)
- Microsoft.Graph.User.Read.All (Application)

Followed Docs:
Azure AD OIDC Protocol [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc)
Consent Scopes [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes)
Configure App Registration [here](https://docs.microsoft.com/en-us/learn/modules/secure-app-with-oidc-and-azure-ad/4-exercise-create-aad-register-app) & [here](https://docs.microsoft.com/en-us/learn/modules/secure-app-with-oidc-and-azure-ad/5-exercise-deploy-app-with-oidc-auth)

### Environment
Kubernetes: `v1.17.7`
Harbor: `v2.0.1`
OIDC Provider: `Azure`
Deployment: Helm Chart `v1.4.1`

**Comment by fl-max** [comment]
UPDATE: just stumbled upon this [issue](https://github.com/goharbor/harbor/issues/9193).

I tried all the "Endpoints" in Azure Portal -> Azure AD -> App Registrations -> Endpoints, including `https://login.microsoftonline.com/{tenant_id}/v2.0/.well-known/openid-configuration`. The working endpoint however is `https://login.microsoftonline.com/{tentant_id}/v2.0` (w/o the trailing slash).

IMO, `https://login.microsoftonline.com/{tenant_id}/v2.0/.well-known/openid-configuration` should be the proper endpoint and would allow Harbor to grab important configuration details about the OIDC Provider.

**Comment by reasonerjt** [comment]
Hi, this is opinionated, but this has been documented and we don't want to introduce such break change.
Maybe we add more information on the UI to better clarify

**Comment by fl-max** [comment]
The `/.well-known/openid-configuration` context-path (Discovery Endpoint) appears to be the standard and is part of the RFC (see [here](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest) and [here](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_oidc_endpoint_urls.html#rwlp_oidc_endpoint_urls__discovery_endpoint)).

When looking at other OIDC providers' docs, they give this URI as well (ie. [Auth0](https://auth0.com/docs/protocols/oidc/openid-connect-discovery), [Swagger](https://swagger.io/docs/specification/authentication/openid-connect-discovery/)).

This Discovery Endpoint returns important information regarding the interaction of OIDC Provider and could help automate some of the fields needed to configure it (ie. `scopes_supported`, `claims_supported`) or at the least help validate user provided configuration and subsequently provide rich error messages.

**Comment by reasonerjt** [comment]
Actually Harbor DOES rely on the discovery URI to get information.

The expected value of the `OIDC ENDPOINT` is the URI does not contain the suffix `/.well-known/openid-configuration`

**Comment by fl-max** [comment]
I see. So the code is doing something like `"https://login.microsoftonline.com/{tenant_id}/v2.0/.well-known/openid-configuration" + "/.well-known/openid-configuration"`?

Wouldn't it make sense to just allow the full URI as a valid input? Maybe check if the suffix `/.well-known/openid-configuration` exists in the given endpoint and if not, add it?

**Comment by reasonerjt** [comment]
This may help, but I don't think most users will consider the `well-known` uri as OIDC endpoint and I think it's documented.

**Comment by reasonerjt** [comment]
I'll keep this open if there are more users hitting the same issue we may consider make this improvement.

**Comment by lindhe** [comment]
> This may help, but I don't think most users will consider the `well-known` uri as OIDC endpoint and I think it's documented.

I cannot find it [here](https://goharbor.io/docs/2.2.0/administration/configure-authentication/oidc-auth/). Is there anywhere else that it's expected to be documented?

**Comment by acobaugh** [comment]
Just hit this as well, and the logging is confusing because the value I provided for the endpoint definitely doesn't 404 for me. IMO this needs to be documented better. Since the UI doesn't have separate fields for each of the individual oidc endpoints, then I think most users are going to assume that the "OIDC endpoint" _is_ the well-known uri.

```
021-07-21T14:38:39Z [ERROR] [/server/v2.0/handler/oidc.go:32]: Failed to verify connection: {URL:https://login.microsoftonline.com/xxxxx/v2.0/.well-known/openid-configuration VerifyCert:true}, err: 404 Not Found```

**Comment by lindhe** [comment]
I think this issue should not be closed until there's at least better documentation.

**Comment by sziyan** [comment]
Chipping in to feedback that I encountered the same issue as well when using Azure AD as IDP.
