### ISSUE TITLE
Test proxy cache performance

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#12540]
The proxy cache performance might need to verify in two scenarios
1.  Pull not cached images from proxy
2. Pull images that already cached.

**Comment by reasonerjt** [comment]
@heww any update?

**Comment by heww** [comment]
The result for pulling the 10MiB image with 500 concurrencies is


Action | Min (sec) | Median (sec) | 90%ile (sec) | 95%ile (sec) | Max (sec) | Avg (sec) | Success | Count | Concurrency
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
harbor.pull_image | 119.623 | 151.086 | 160.42 | 162.083 | 168.622 | 151.184 | 100.00% | 1000 | 500






The result for pulling the 10MiB image with 500 concurrencies from proxy cache proxy is

Action | Min (sec) | Median (sec) | 90%ile (sec) | 95%ile (sec) | Max (sec) | Avg (sec) | Success | Count | Concurrency
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
| harbor.pull_image        | 111.622   | 153.33       | 168.977      | 171.026      | 179.952   | 153.981   | 100.0%  | 1000  | 500 |
