### ISSUE TITLE
Add New Registry Endpoint && Failed to ping endpoint.

### ISSUE THREAD

**Issue by haitang5445** [goharbor/harbor#12542]
The newly installed system is very clean. When I start the harbor, I cannot successfully add New Registry, and I cannot change several versions.

The target Registry  is available

I don't know why this happened

![image](https://user-images.githubusercontent.com/59681546/88035122-3ee41000-cb74-11ea-998d-cc2e71ffd4c5.png)

**Comment by heww** [comment]
What is the version of the src harbor, and what is the version of the target harbor?

**Comment by haitang5445** [comment]
2.0.1 & 1.10.3 & 1.9.3

I have tried these versions

> What is the version of the src harbor, and what is the version of the target harbor?

**Comment by amitdah4** [comment]
@haitang5445 Is this endpoint required some authentication ?. 

Also is it accessible from Harbor pod (network).

**Comment by haitang5445** [comment]
@amitdah4   I try to enter the container to test the network, but the network is connected.  
                      curl http://10.134.130.247  is  ok. 
                      I found that harbor failed to add itself . Oh my god ,I doubt life

**Comment by reasonerjt** [comment]
`curl http://10.134.130.247` doesn't mean it's a valid registry endpoint, at all...

I would check the log to find out why the ping failed.

**Comment by haitang5445** [comment]
I found that there are many logs in job_logs, but I don't know which one to look at

**Comment by haitang5445** [comment]
Jul 22 11:11:05 172.22.0.1 core[23497]: 2020-07-22T03:11:05Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry http://10.134.130.247: Get http://localhost/service/token?service=harbor-registry: dial tcp 127.0.0.1:80: connect: connection refused
Jul 22 11:45:15 172.22.0.1 core[23497]: 2020-07-22T03:45:15Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry http://10.134.130.247: Get http://localhost/service/token?service=harbor-registry: dial tcp 127.0.0.1:80: connect: connection refused

**Comment by haitang5445** [comment]
I found the cause of the problem。 The harbor.yml host name cannot be resolved. Can be used after reconfiguration. 
TKS everyone!!!
![image](https://user-images.githubusercontent.com/59681546/88155532-c5632500-cc3a-11ea-8358-5fc68a176170.png)

**Comment by xjuric29** [comment]
> I found the cause of the problem。 The harbor.yml host name cannot be resolved. Can be used after reconfiguration.
> TKS everyone!!!
> ![image](https://user-images.githubusercontent.com/59681546/88155532-c5632500-cc3a-11ea-8358-5fc68a176170.png)

Thank you for your help! I copied VM with installed Harbor exactly for testing of repplication and I could not examine the problem when the second harbor was accessible from core container. Maybe it will be good to modify the error message a little.
