### ISSUE TITLE
Allow to assume an IAM role for ECR replication

### ISSUE THREAD

**Issue by yogeek** [goharbor/harbor#12553]
For ECR replication, it is currently only possible to use AWS `access_id` and `access_secret` fields in the ECR endpoint configuration.
[The code](https://github.com/goharbor/harbor/blob/2041fd337b5f6fa7f59f4eab3ebb469346b7027a/src/replication/adapter/awsecr/auth.go#L96) is apparently using aws sdk [static_provider.go](https://github.com/goharbor/harbor/blob/2041fd337b5f6fa7f59f4eab3ebb469346b7027a/src/vendor/github.com/aws/aws-sdk-go/aws/credentials/static_provider.go)

It would be very useful to be able to assume a role to do this to avoid having to use static credentials to access ECR. 
It seems that the aws sdk already provides the [assume_role_provider.go](https://github.com/goharbor/harbor/blob/2041fd337b/src/vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go) to achieve this.

**Comment by heww** [comment]
Do you mean that to limit the permission of AWS credential (eg the access_id and access_secret only allowed to access the ecr) in the replication?

**Comment by yogeek** [comment]
I may not sure to understand your question but my use case is that we only create IAM user on 1 AWS account and then create specific roles target accounts and use 'assume role' to perform actions on these other accounts.
That allow us to centralize the user management and to limit the permissions associate to a role and then to be able to use some tool like kube2iam to perform actions on AWS from inside a pod.

Anyway, in general, tools often allowed to use both id/secret or a role to do AWS IAM authentication and as it is present in the AWS SDK, I think it would be a useful feature in harbor replication on AWS.

**Comment by xaleeks** [comment]
Can you elaborate on how this is setup? So you're saying you have one IAM user and you're giving access to its resources through the roles target accounts to other accounts through assume role API? are these external accounts or some other aws account? What is the benefit to this approach, is it short lived access credentials over over hardcoded secret? Sorry I'm not terribly well versed in AWS.  Back to Harbor, what persona in your scenario is doing the replication configuration.  Is the goal here that different roles have coded in access permissions to different repos and images?

Btw, seems you already identified all the steps needed, so can you submit a PR for this change?

**Comment by yogeek** [comment]
@xaleeks Yes the main benefit of this approach is that only security team can create users in a main AWS account and users are requesting roles (that can be assumed by these users) to target other AWS accounts. With this, no static creds are needed by the users, only roles (that they assume either in their terraform provider, or their k8s pods with kube2iam for example)

So on our case, Harbor is deployed and configured automatically by a code which does the following steps :

- Terraform is launched by a user in the main account, and is assuming a role in the harbor AWS account to deploy an EKS (terraform provider is configured to assume this role). 
- Harbor is deployed with Helm to the EKS
- Harbor is configured by code calling its API. 

So in Harbor AWS account, we have no AWS user, only AWS role. 
In order for the harbor pod to be able to do the replication to another account's ECR, the EKS nodes instance profile must have the permission to assume a role that is allowed to put images into the targeted ECR.
With the current Harbor configuration, it is only possible to use a user credentials to replicate to the ECR...

**Comment by bitsf** [comment]
@yogeek Is it suppose to input a role name in the credential field, or just leave it as empty?
I tried to assign a role to a EC2, and I can directly call ECR Api without input any credential or role in this EC2.
But the code `assume_role_provider.go` seems need input a myRoleArn in method `NewCredentials()`

**Comment by yogeek** [comment]
I think it may propose 2 choices :
- AWS 'static' credentials (if chosen, the 2 fields access_key and secret_key that are today proposed are enabled and must be filled, and harbor will use these credentials via the SDK to authenticate to AWS API as it is already done today)
- AWS 'role' (if chosen, a field role-arn must be filled, and harbor will use that role via the SDK to authenticate to AWS API. Of course the harbor pod must have been granted the permission to connect to ECR, with kube2iam for example)

I think you were able to connect directly because your ECR has no policy that restrain the access.

**Comment by bitsf** [comment]
I find we could use [ec2_role_provider.go](https://github.com/goharbor/harbor/blob/master/src/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go), which can query ec2 API without any access_key input.

I didn't test with assume_role_provider.go successfully, it seems to be some other use, which also need an access_key first.

**Comment by Mierpo** [comment]
In what version of harbor will this feature be available in?
