### ISSUE TITLE
OnScanningCompleted logging object IDs instead of text values

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [goharbor/harbor#12554]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: readable artifact name in scan logs
Actual: `[INFO] [/core/notifier/notifier.go:204]: Handle notification with topic 'OnScanningCompleted': &model.ScanImageEvent{EventType:"scanningCompleted", Artifact:(*v1.Artifact)(0xc000e157c0), OccurAt:time.Time{wall:0xbfbe1c606715efff, ext:125442802496268, loc:(*time.Location)(0x2c90c00)}, Operator:"auto"}`

**Steps to reproduce the problem:**
Trigger a scan with clair, view harbor core logs

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.3]

**Comment by xtreme-conor-nosal** [comment]
Just upgraded to harbor 2.0.1 and noticed the same on pulls `Handle notification with topic 'PULL_ARTIFACT': &event.PullArtifactEvent{ArtifactEvent:(*event.ArtifactEvent)(0xc000348e00)}`

**Comment by heww** [comment]
@mmpei we may need to implement the `String` method for the event type of the notification.
