### ISSUE TITLE
OIDC log in breaks when redis has an NFS stale handle

### ISSUE THREAD

**Issue by brandonkal** [goharbor/harbor#12550]
I was asked to open this as an issue here: https://cloud-native.slack.com/archives/CC1E09J6S/p1595266394424000

**Expected behavior and actual behavior:**

Perhaps redis should be marked as unhealthy if it logs an nfs stale handle.

**Steps to reproduce the problem:**

I am running k3s on a single ubuntu vm with rancher's local path pvc provisioner. Harbor is installed via helm chart template.

The pvc provisioner is configured to create folders within `/mnt/kube` which is an NFS mount from another system.

I can't really provide any more details than that. This all appears very dependent on my particular setup but I believe the harbor issue is that it doesn't recognize this as an error state.

In a multi-host cluster, harbor could try scheduling the redis pod to use a pvc on another host.

Restarting the VM resolves the issue for some time.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.0.1
- kubernetes version: v1.18.4+k3s1
- host: ubuntu 18.04 LTS

**Comment by brandonkal** [comment]
Well it happened again. My harbor installation goes sour every 1-2 days.
I've attached some log snippets if it helps. Note that some lines are wrapped below.

logs for registry/harbor-harbor-redis-0:redis
```
1:M 24 Jul 05:45:14.113 # Background saving error                                                                                                                 │
│ 1:M 24 Jul 05:45:20.030 * 1 changes in 900 seconds. Saving...                                                                                                     │
│ 1:M 24 Jul 05:45:20.031 * Background saving started by pid 1944                                                                                                   │
│ 1944:C 24 Jul 05:45:20.034 # Failed opening the RDB file dump.rdb (in server root dir /var/lib/redis) for saving: Stale file handle                               │
│ 1:M 24 Jul 05:45:20.132 # Background saving error                                                                                                                 │
│ 1:M 24 Jul 05:45:26.049 * 1 changes in 900 seconds. Saving...                                                                                                     │
│ 1:M 24 Jul 05:45:26.049 * Background saving started by pid 1945                                                                                                   │
```
logs for registry/harbor-harbor-core-68c459b6d9-mdrz7:core
```
2020/07/24 05:46:18.749 [D] [transaction.go:62]  |      10.42.0.1| 200 |    949.382µs|   match| GET      /api/v2.0/ping   r:/api/v2.0/ping                        │
│ 2020-07-24T05:46:23Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="3b48ef77-680c-4038-999a-ee70b67bc278"]: failed to verify token: oidc: malfo │
│ rmed jwt: square/go-jose: compact JWS format must have three parts                                                                                                │
│ 2020/07/24 05:46:23.056 [D] [transaction.go:62]  |      10.42.0.1| 200 |     870.44µs|   match| GET      /api/v2.0/ping   r:/api/v2.0/ping                        │
│ 2020-07-24T05:46:28Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="f382a3a9-e3c3-49dd-a281-1405caf45aa8"]: failed to verify token: oidc: malfo │
│ rmed jwt: square/go-jose: compact JWS format must have three parts                                                                                                │
│ 2020/07/24 05:46:28.749 [D] [transaction.go:62]  |      10.42.0.1| 200 |   1.012538ms|   match| GET      /api/v2.0/ping   r:/api/v2.0/ping                        │
│ 2020-07-24T05:46:33Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="c13dedd4-e63e-4d56-a3ce-c6b14a90cc62"]: failed to verify token: oidc: malfo │
│ rmed jwt: square/go-jose: compact JWS format must have three parts                                                                                                │
│
```
logs for registry/harbor-harbor-jobservice-59c778db68-vsmhf:jobservice
```
2020-07-24T05:47:55Z [ERROR] [/jobservice/hook/hook_agent.go:204]: Resend hook event error: MISCONF Redis is configured to save RDB snapshots, but it is currentl │
│ y not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snap │
│ shotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.                                                 │
│ 2020-07-24T05:48:00Z [ERROR] [/jobservice/hook/hook_agent.go:204]: Resend hook event error: MISCONF Redis is configured to save RDB snapshots, but it is currentl │
│
```

**Comment by reasonerjt** [comment]
@brandonkal 

Hi Brandon, 

Currently as long as the redis process is responsive, Harbor will think it's healthy.  I don't think stopping the process once the write failure happens is a good idea.

so do you have any clue why this `Stale file handle` happened?  I think maybe we can tweak the configuration in Redis to mitigate the problem.

**Comment by brandonkal** [comment]
Well once redis fails to write harbor essentially locks all users out and things can't be pushed.
My dev setup was:
1. Unraid host with kube NFS share and Ubuntu VM.
2. Ubuntu VM running k3s. Share is automounted to `/mnt/kube`
3. The k3s pvc local provisioner is set to create pvc volume folders in `/mnt/kube/pv`

I suspect there could be an NFS sharing issue and the k3s local provisioner doesn't recover. Naturally when it doesn't recover, harbor freezes up and that is not reflected in its reported status. I can still write to the mounted NFS volume.

**Comment by reasonerjt** [comment]
Closing this issue as this looks like a env issue.
