### ISSUE TITLE
Collapsed left nav exposes light/dark mode icon

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#12566]
On version v2.0.0-549ca22b, on safari...

i see the light/dark mode icon partially shown when the left navigation is closed. see images in both light and dark mode.
It seems to be pushed to the right too much. 

<img width="135" alt="Screen Shot 2020-07-23 at 9 33 48 AM" src="https://user-images.githubusercontent.com/626032/88292922-461c3280-ccc8-11ea-89f7-46d2e2326673.png">

<img width="174" alt="Screen Shot 2020-07-23 at 9 34 41 AM" src="https://user-images.githubusercontent.com/626032/88292943-4fa59a80-ccc8-11ea-8cbc-dda6f25f2cfc.png">

there is no need to have an expandable API explorer category. could we just have one row below the light/dark icon row?

**Comment by AllForNothing** [comment]
@lweitzman Thanks!
This UI bug has been fixed in 2.0.x and master branch
