### ISSUE TITLE
希望推出全库复制功能

### ISSUE THREAD

**Issue by KeithTt** [goharbor/harbor#1256]
我有多个节点，多个项目，目前复制策略只支持从项目添加，如果一个一个项目添加复制策略会有很多无意义的重复操作，如果能支持全库复制就好了！谢谢！

**Comment by hainingzhang** [comment]
Thanks for your suggestion, we will consider a system-wide replication policy for the above requirement.

**Comment by xaleeks** [comment]
doing some long overdue cleanup
