### ISSUE TITLE
Images not showing up in the UI (version 2.0.1) when using Istio

### ISSUE THREAD

**Issue by jabbors** [goharbor/harbor#12560]
I'm currently using harbor 1.10.2 in production behind a Istio VirtualService and with external storage (s3). My Istio configuration is posted in https://github.com/goharbor/harbor-helm/issues/77.

In an attempt to upgrade to version 2.0.1, I've been experimenting in a playground environment with a fresh setup but struggles to figure out why pushed images doesn't show up in the UI. I'm using the same workaround as for version 1.10.2, which is routing `/v2/` requests directly to  the registry service. I can login to registry just fine (`docker login myharbor.domain`) and even push and pull images. But the images does not show up in the UI at all.

Anyone who knows what could be up? Does `/v2/` requests actually have to go through the core service?

**Comment by jabbors** [comment]
I eliminated Istio and replace the VirtualService with nginx. Similarly to the VritualService, I configured nginx to proxy `/v2/` request directly to the registry service.

Again I was able to push and pull an image but the image does not show up in the UI.

**Comment by jabbors** [comment]
I've verified that the I can see images in the UI when I deploy harbor 2.0.1 with helm and external storage configured. The only difference with helm and my setup is that I'm using token authentication in favour of the default basic authentication with helm.

**Comment by heww** [comment]
@jabbors can you paste this issue to https://github.com/goharbor/harbor-helm/issues/77 , all the issues about istio are discussed in that issue.

**Comment by jabbors** [comment]
sure, will do.

**Comment by ywk253100** [comment]
Closing as a new issue is opened in the harbor chart repositoy
