### ISSUE TITLE
Non-Blocking GC does not perform deletion for orphan blobs caused by quotas policy

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#12565]
**Reproduce Steps:**
1. Deploy harbor;
2. Create project and set project quotas as 100M;
3. Push a image with size of 200M, get failure due to quotas;
4. Trigger GC.

**Expectation Result:**
    project quotas usage should be Zero;
**Actural Result:**
    project quotas usage has a non-zero value;

**Comment by wy65701436** [comment]
currently, it's as designed. The GC job will not execute the sweep step as there is no actually removed artifact, but just some of orphan blobs.

If you try to push/delete a image, then to run GC, these orphan blobs will be removed.

It's could be discussed.

**Comment by wy65701436** [comment]
close it as PR merged. https://github.com/goharbor/harbor/pull/12595
