### ISSUE TITLE
Curl Vulnerabilities scan

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor#12562]
Hello!

Version v1.10.2-d0189bed

Im trying to get vulnerabilies report via curl command.

I can use curl via CLI on my Centos machine and view the output with vulnerabilities:

`curl -i -k -X GET "URL/api/repositories/repo/tags/tag/scan" -u foo:bar -H "Accept: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0"`

ouput:

```
{
  "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0": {
    "generated_at": "2020-07-23T07:32:40.515935885Z",
    "scanner": {
      "name": "Clair",
      "vendor": "CoreOS",

      "version": "2.x"
    },
    "severity": "None",
    **"vulnerabilities": null"**
  }

```
but when i make the same request via CI i get empty report:
![1](https://user-images.githubusercontent.com/38696837/88263351-93050680-ccd2-11ea-991f-9093b93ac657.png)

The same with Swagger

![1](https://user-images.githubusercontent.com/38696837/88263529-d790a200-ccd2-11ea-9ad7-e7c952ea11d4.png)

**Comment by heww** [comment]
Related issue https://github.com/goharbor/harbor/issues/11775
