### ISSUE TITLE
docker distribution 本身有 prometheus metrics ，在harbor中如何enable呢

### ISSUE THREAD

**Issue by ckyx** [goharbor/harbor#12577]
现象：我们生产环境的 harbor 镜像仓库registry 的cpu占用一直很高，内存使用也不释放，导致经常重启。并且push镜像后需要很久才能出现在ui页面，event_base同步规则触发会失效。

希望得到解答：可以从哪些方面来排查，应该如何优化，registry的这个prometheus指标应该如何enable和抓取

谢谢

**Comment by wy65701436** [comment]
hi @ckyx what's your harbor version？What kind of storage? and can you upload the log?

**Comment by ckyx** [comment]
> 
> 
> hi @ckyx what's your harbor version？What kind of storage? and can you upload the log?

we are now using harbor 1.9.0.

and this is the log of docker registry 
[registry-error.log](https://github.com/goharbor/harbor/files/4999141/registry-error.log)

**Comment by heww** [comment]
Hi @ckyx, 

you can modify the `config.yml` of the registry component to enable the Prometheus metrics according to the doc https://github.com/docker/distribution/blob/master/docs/configuration.md#prometheus

For the harbor installed by the `installer`, the location of `config.yml` is `common/config/registry/config.yml` relatives to `install.sh`.

For the harbor installed by the `helm`, the `config.yml` is in the `ConfigMap` resource of the registry.

**Comment by ckyx** [comment]
> 
> 
> Hi @ckyx,
> 
> you can modify the `config.yml` of the registry component to enable the Prometheus metrics according to the doc https://github.com/docker/distribution/blob/master/docs/configuration.md#prometheus
> 
> For the harbor installed by the `installer`, the location of `config.yml` is `common/config/registry/config.yml` relatives to `install.sh`.
> 
> For the harbor installed by the `helm`, the `config.yml` is in the `ConfigMap` resource of the registry.

ok ,i will try it ,thank u very much heww

**Comment by xaleeks** [comment]
Seems this has been answered, we will have a solution for when deployed as a kubernetes cluster soon
