### ISSUE TITLE
Replication Tasks Not Executing Tasks

### ISSUE THREAD

**Issue by hmmxp** [goharbor/harbor#12576]
Dear All,

I am running Harbor 1.9.0 and Docker 19.03.11

In our production environment, we are encountering issues with harbor replication tasks not replicating to our other harbor. Our current harbor replication policy is event based, we tested pushing new image to trigger the replication task but it will not replicate. 

We attempted to restart harbor and replication will work for a short period of time before it will stop replication.

Looking at logs but we cannot find anything helpful

Any assistance will be of a great help

**Comment by bitsf** [comment]
Do you mean the task not start or no images was replicated ?

**Comment by hmmxp** [comment]
Replication Task Not Starting and no images was replicated

**Comment by Jaycean** [comment]
I have encountered a similar problem before. What I encountered was that there was no problem with the two harbor connection tests. The copy task started, but there was no image to be copied

**Comment by bitsf** [comment]
hi @steven-zou , can you help on this, seems some known issue of jobservice, how to recover.

**Comment by steven-zou** [comment]
> I have encountered a similar problem before. What I encountered was that there was no problem with the two harbor connection tests. The copy task started, but there was no image to be copied

Need to confirm: were the replication tasks completed but no images are replicated? or the replication tasks are hung?

**Comment by steven-zou** [comment]
> Replication Task Not Starting and no images was replicated

Are the replication tasks in `pending` status? No `Running` tasks?

Is there any other jobs like scan are running?

**Comment by hmmxp** [comment]
> > Replication Task Not Starting and no images was replicated
> 
> Are the replication tasks in `pending` status? No `Running` tasks?
> 
> Is there any other jobs like scan are running?

No Jobs Are Running

**Comment by bitsf** [comment]
suggest to upgrade to some newer version of Harbor, some replication scheduler has been refactor

**Comment by bitsf** [comment]
Close as 1.9.x is not active maintained
