### ISSUE TITLE
Links are not clickable on repository search result page (for anonymous access)

### ISSUE THREAD

**Issue by sizowie** [goharbor/harbor#12594]
**Expected behavior and actual behavior:**
It is not possible for an **anonymous user** to view/gather informations (e.g. "pull command" or "artifact details") about images in public projects, change the language or just view the "About"-Site. It seems that the "mask-layer" class on the result page prevents the user from clicking any visible links. Not sure if it's supposed to be.

This worked in previous releases (tested with v1.10.0).

![2020-07-27_10h42_47](https://user-images.githubusercontent.com/169141/88523342-15a20480-cff8-11ea-8f11-8e6e447f9ad9.png)

**Steps to reproduce the problem:**
- Create a public accessable project
- Place an image in this project
- Logout
- Search in Harbor-UI for the image
- Click on the Image

**Versions:**
- harbor version: [v2.0.1]
- docker engine version: [19.03.6]
- docker-compose version: [1.24.1]

**Additional context:**
No issues on the standard login page, when you're not logged in.

**Workaround:**
To workaround the issue, remove the "mask-layer" class from the result page. All links are clickable as expected again:

![2020-07-27_10h49_11](https://user-images.githubusercontent.com/169141/88523395-2d798880-cff8-11ea-911f-e5ef938d5e8d.png)

**Comment by AllForNothing** [comment]
@sizowie Thanks.
This is by design. For Harbor version 2.x.x,  if user session is timeout ,you are  not allowed to operate UI unless you login again. It,s more safe and reasonable

**Comment by sizowie** [comment]
@AllForNothing Thank you. But why do you allow non-logged users to search in harbor anyway? We miss this feature as in our usecase users are able to search for public images that can be pulled without having harbor access.

**Comment by AllForNothing** [comment]
@sizowie 
Understood.
On below page, It's a public project, non-logged users should be able to do something like copy pull comand, but now, they can do nothing.  I'll reopen this issue and discuss if there is any improvement for this.

**Comment by sizowie** [comment]
> @sizowie
> Understood.
> On below page, It's a public project, non-logged users should be able to do something like copy pull comand, but now, they can do nothing. I'll reopen this issue and discuss if there is any improvement for this.

That's correct. Thank you!

**Comment by sethbergman** [comment]
This is an important feature for public repositories, since the UI redirects to the login page when you click on a link to a image repository. Then even after logging in, the expected behavior is to get access to the original link to the image repository, but this is not the case. Public images should be accessible from a URL without having to login.
