### ISSUE TITLE
Do not display the annotations attribute after push the manifest

### ISSUE THREAD

**Issue by smallteeths** [goharbor/harbor#12593]
**Versions:**

- harbor version: [v2.0.1]
- docker engine version: [19.03.8]
- docker-compose version: [1.25.4]

**Steps to reproduce the problem:**

- Use buildah to create manifest (buildah version 1.14.9) and add annotation. `buildah create --format=docker mylist:v1.18 ${image}  && buildah manifest annotate --annotation left=right mylist:v1.18 ${image}`
- push manifest lists to registry `buildah manifest push --tls-verify=false --format=docker --all mylist:v1.18 ${docker://xxx.xx.xx/library/xxx/image:tag}`

**Expected behavior and actual behavior:**

The current result is that the push is successful but the annotations in the artifacts list are empty. as shown:

![Jietu20200727-163430](https://user-images.githubusercontent.com/27733391/88521112-14d49700-d027-11ea-802e-e7cfd981583c.jpg)

I'm confused. I think the expected behavior should show the annotations attribute of the manifest.

![Jietu20200727-164447](https://user-images.githubusercontent.com/27733391/88522125-82cd8e00-d028-11ea-830b-413f25b1b413.jpg)

Not sure if this is a bug or not.

**Comment by unreal-altran** [comment]
@smallteeths i have the same problem. 
would it be possible to have an example in order to see something appear on the GUI annotations section?

**Comment by AllForNothing** [comment]
@unreal-altran 
Currently, the "annotations" column on UI does not work, we are planning to fix it

**Comment by unreal-altran** [comment]
@AllForNothing 
Thank you for your quick answer!
Once the bug is fixed, due to the little documentation on annotations (OCI) and the difference with the classic LABEL of the dockerfile, I think it is necessary to describe in the official Harbor doc. how to use the annotations with a practical example.

**Comment by urangurang** [comment]
@AllForNothing 
Hello, 
is there any update about this issue?

**Comment by AllForNothing** [comment]
@wy65701436 will have a look at this remaining issue
