### ISSUE TITLE
Wrong time format in audit logs

### ISSUE THREAD

**Issue by phiphi282** [goharbor/harbor#12598]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

When trying to open the audit-logs, angular fails to parse the timestamps and the site loads for a very long time before printing out the information without the timestamp.
![Screenshot_2020-07-27 Harbor](https://user-images.githubusercontent.com/32705812/88552827-d342ec80-d024-11ea-8cd4-52069a86e7b7.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

Click on logs inside of the harbor ui.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.0]
- docker engine version: [19.03.8]
- docker-compose version: [1.25.5]

Happens on https://demo.goharbor.io/harbor/logs as well

**Additional context:**

I already patched my own installation by changing the timestamp format to rfc3339.
Before creating a pull request I wanted to ask if this is acceptable to do, since it could potentially break integrations for older harbor versions.
Otherwise I can specify the go timestamp format in the fronted as well, however I think that rfc3339 has a wider support than the go timestamp format. 

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by AllForNothing** [comment]
@phiphi282 Thanks.
It's a duplicated issue, see #11522
We strongly recommend Chrome to visit Harbor UI.
I'm closing this issue, and keep #11522 opened
