### ISSUE TITLE
"response completed with error"  err.code="blob unknown"

### ISSUE THREAD

**Issue by DinshKW44** [goharbor/harbor#12619]
Harbor Version: 1.10.1
Chart Version: 1.3.1
Kubernetes Version: 1.16.3
S3 Storage: Ceph S3
Ingress: nginx
Deployed Harbor into Kubernetes and connected it Ceph s3. When pushing an image to ceph s3 registry, I am getting below error.
level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" 

The error keeps occurring in the registry logs of harbor but in the end, the image gets pushed. The push at times is taking more an 10min. 
Could you please help me with this?

**Comment by wy65701436** [comment]
can you provide the regsitry and core log for debugging? Have you tried the storage configuration with native distribution?

**Comment by DinshKW44** [comment]
I have tried it minio as backend too. The push is faster but the logs still show the response completed with error. Please find the logs below.

[core_s3.log](https://github.com/goharbor/harbor/files/5063076/core_s3.log)
[registry_minio.log](https://github.com/goharbor/harbor/files/5063077/registry_minio.log)
[registry_s3.log](https://github.com/goharbor/harbor/files/5063078/registry_s3.log)
[core_minio.log](https://github.com/goharbor/harbor/files/5063079/core_minio.log)

**Comment by brondum** [comment]
+1
The registry-photon service keeps logging `err.message="blob unknown to registry"``
, even though the layers get pushed.

Harbor 2.0.1 and 2.0.2 with GCS Backend.

**Comment by DinshKW44** [comment]
@wy65701436 Please may I know whether you could find anything regarding the issue? 
 core logs:
2020/08/18 13:38:03.546 [D] [server.go:2774]  |    10.235.74.0| 404 |   11.33774ms|   match| HEAD     /v2/blobs/sha256:592ef4d4587137f4896b34c2181a5347b3bd55c6cda09677a2248ed8f3eec422   r:/v2/*

registry logs:
time="2020-08-18T13:37:56.206402374Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.12.12 http.request.host=registry3.it.k8.cin.platinum.platinumtest.com http.request.id=ce9299d2-6ef8-4a15-8fda-5fba79b47bfa http.request.method=GET http.request.remoteaddr=10.235.74.1 http.request.uri="/v2/" http.request.useragent="docker/19.03.6 go/go1.12.17 git-commit/369ce74a3c kernel/4.15.0-112-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \(linux\))" 
time="2020-08-18T13:37:56.588656057Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:1dca47e3e3908e2f00ea12153a006f9e5d9599eeb559efe2a5d80a800f9f7447 err.message="blob unknown to registry" go.version=go1.12.12 http.request.host=registry3.it.k8.cin.platinum.platinumtest.com http.request.id=c8240af1-bbcf-46e4-9ae7-c63fb9aa605d http.request.method=HEAD http.request.remoteaddr=10.235.74.0 http.request.uri="/v2/testuser/samburney/gns3/blobs/sha256:1dca47e3e3908e2f00ea12153a006f9e5d9599eeb559efe2a5d80a800f9f7447" http.request.useragent="docker/19.03.6 go/go1.12.17 git-commit/369ce74a3c kernel/4.15.0-112-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.6 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=7.794214ms http.response.status=404 http.response.written=157 vars.digest="sha256:1dca47e3e3908e2f00ea12153a006f9e5d9599eeb559efe2a5d80a800f9f7447" vars.name="testuser/samburney/gns3"

this is happening when using local pvc too which is backed by ceph

**Comment by brondum** [comment]
not stale

**Comment by 7rouz** [comment]
I am encountring the same logs too.
Harbor 1.10.1 
here are some logs of registry.log and core.log:

**registry.log**
`Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX registry[106936]: 172.18.0.8 - - [16/Feb/2021:12:02:50 +0000] "PUT /v2/XXXXXXXXXXXXXXXXXXX/blobs/uploads/3b23a1d2-b694-4047-8092-79179e830d49?_state=90KXnKZDScSbK5_kogzmMaqvTT-c9Q0DO4IcRXAmfPd7Ik5hbWUiOiJhMTkxMS9zcGFya3ktY29uc3VtZXItc2ciLCJVVUlEIjoiM2IyM2ExZDItYjY5NC00MDQ3LTgwOTItNzkxNzllODMwZDQ5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTAyLTE2VDEyOjAyOjUwLjE0NTIxMjY0M1oifQ%3D%3D&digest=sha256:a71877835fd8c8c84f43c5afa393e9796f4a21baa254a1992fa3da6b0865f442 HTTP/1.1" 201 0 "" "harbor-replication-service"

Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX registry[106936]: time="2021-02-16T12:02:54.022304801Z" 
level=info msg="authorized request" 
go.version=go1.12.12 
http.request.host="core:8080"
http.request.id=28b47637-e9df-4277-8c87-b6b3f36d93d5 
http.request.method=HEAD 
http.request.remoteaddr=172.18.0.10 
http.request.uri="/v2/XXXXXXXXXXXXXXXXXXX/blobs/sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d" 
http.request.useragent=harbor-replication-service 
vars.digest="sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d"
vars.name="XXXXXXXXXXXXXXXXXXX"

Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX registry[106936]: time="2021-02-16T12:02:54.023481926Z" level=info msg="redis: connect redis:6379" go.version=go1.12.12 instance.id=63fc77f7-8bbf-427b-9e03-c85838969987 redis.connect.duration=993.933µs service=registry version=v2.7.1.m

Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX registry[106936]: 172.18.0.8 - - [16/Feb/2021:12:02:54 +0000] "HEAD /v2/XXXXXXXXXXXXXXXXXXX/blobs/sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d HTTP/1.1" 404 157 "" "harbor-replication-service"
Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX registry[106936]: time="2021-02-16T12:02:54.039163106Z" 
level=error 
msg="response completed with error"
auth.user.name=harbor-jobservice 
err.code="blob unknown"
err.detail=sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d 
err.message="blob unknown to registry"
go.version=go1.12.12 
http.request.host="core:8080" 
http.request.id=28b47637-e9df-4277-8c87-b6b3f36d93d5 
http.request.method=HEAD 
http.request.remoteaddr=172.18.0.10 
http.request.uri="/v2/XXXXXXXXXXXXXXXXXXX/blobs/sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d"
http.request.useragent=harbor-replication-service 
http.response.contenttype="application/json; charset=utf-8" 
http.response.duration=19.702134ms 
http.response.status=404 
http.response.written=157 
vars.digest="sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d"
vars.name="XXXXXXXXXXXXXXXXXXX"
`
**core.log**
`Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX core[106936]: 2021/02/16 12:02:54.016 #033[1;44m[D]#033[0m [server.go:2774]  |    172.18.0.10|#033[97;42m 201 #033[0m| 3.809563461s|   match|#033[97;43m PUT     #033[0m /v2/XXXXXXXXXXXXXXXXXXX/blobs/uploads/3b23a1d2-b694-4047-8092-79179e830d49   r:/v2/*
Feb 16 13:02:54 XXXXXXXXXXXXXXXXXXX core[106936]: 2021/02/16 12:02:54.039 #033[1;44m[D]#033[0m [server.go:2774]  |    172.18.0.10|#033[97;43m 404 #033[0m|  21.625655ms|   match|#033[97;45m HEAD    #033[0m /v2/XXXXXXXXXXXXXXXXXXX/blobs/sha256:bd017faf886b636fe0a19f41297b42c68aa2ad709fb2edfff418cb0fe73e361d   r:/v2/*`

So the same behavior as described before registry keep logging "blob unknown to registry" when replicating from docker registry to harbor (private S3 storage) even though the images are finely pushed.

**Comment by paulliss** [comment]
"+1" have the same issue

**Comment by mbugua-samuel** [comment]
Experiencing same issue +1

**Comment by paulliss** [comment]
Hello.
I have struggled a lot with "blob unknown" and want to share my experience:

There seems to be no bugs in the Harbor and / or Docker client.
The "blob unknown" problem has to do with timing
out on your load balancers (this could be the S3 side or your harbor side) with a relatively slow data link or when loading huge (over 35GB) docker images
OR
This may be due to errors on the side of the S3 service itself (in my case, the S3 service is based on DELL EMC ECS) -
I needed to update the DELL EMC ECS firmware to the latest version and only that solved the problem.

**Comment by adminy** [comment]
sounds similar to the issue I'm having.

I have a self hosted repo.

In the terminal I get 
```
error: failed to solve: failed to push localhost:5000/adminy/name:tag: failed to do request: Head "http://localhost:5000/v2/adminy/name/blobs/sha256:a775605f036862e7b646bf344f0d3795c196cd85dbd07c938eaebc3588bb5c79": dial tcp 127.0.0.1:5000: connect: connection refused
```
When I went into the url myself I got:
```json
{"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:a775605f036862e7b646bf344f0d3795c196cd85dbd07c938eaebc3588bb5c79"}]}
```
