### ISSUE TITLE
Harbor redirects to OIDC login page, when the username or password invalid

### ISSUE THREAD

**Issue by luckymagic7** [goharbor/harbor#12616]
**Expected behavior and actual behavior:**
- Expected behavior: When `Username` or `Password` is invalid, Harbor should return login failure.
- actual behavior: When `Username` or `Password` is invalid, Harbor redirects to the OIDC login page(In my case OneLogin)

**Steps to reproduce the problem:**
- Go to harbor login page via web brower(Chrome, Safari etc..)
- Type invalid Username and Password
- Click LOG IN

**Versions:**
- Harbor
```
goharbor/harbor-core:v2.0.0
goharbor/harbor-jobservice:v2.0.0
goharbor/harbor-portal:v2.0.0
goharbor/harbor-registryctl:v2.0.0
goharbor/harbor-db:v2.0.0
goharbor/harbor-log:v2.0.0
```

- Docker
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Jul  1 18:51:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Jul  1 18:53:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Docker compose
```
docker-compose version 1.26.2, build unknown
docker-py version: 4.2.2
CPython version: 2.7.18
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Additional context:**
When I click the login button on web brower with invalid username or password, below logs come out.
- **Log files:** 
```
==> proxy.log <==
Jul 29 07:23:35 $HARBOR_IP proxy[3756]: $CLIENT_IP - "POST /c/login HTTP/1.1" 403 68 "$HARBOR_ADDRESS_HTTPS/sign-in?signout=true&redirect_url=%2Fharbor%2Fusers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77" 0.002 0.000 .

==> core.log <==
Jul 29 07:23:35 $HARBOR_IP core[3756]: 2020/07/29 07:23:35.408 #033[1;44m[D]#033[0m [middleware.go:52]  |   61.32.106.42|#033[97;43m 403 #033[0m|    534.184µs|   match|#033[97;46m POST    #033[0m /c/login   r:/c/login
Jul 29 07:23:35 $HARBOR_IP core[3756]: 2020/07/29 07:23:35.957 #033[1;44m[D]#033[0m [middleware.go:52]  |   61.32.106.42|#033[90;47m 302 #033[0m| 518.144289ms|   match|#033[97;44m GET     #033[0m /c/oidc/login   r:/c/oidc/login

==> proxy.log <==
Jul 29 07:23:35 $HARBOR_IP proxy[3756]: $CLIENT_IP - "GET /c/oidc/login HTTP/1.1" 302 275 "$HARBOR_ADDRESS_HTTPS/sign-in?signout=true&redirect_url=%2Fharbor%2Fusers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77" 0.519 0.516 .
```

**Comment by reasonerjt** [comment]
@luckymagic7 

Could you provide more context for this scenario?

```
When Username or Password is invalid, Harbor redirects to the OIDC login page(In my case OneLogin)
```

Where did you input the username and password?  If you click "Login via OIDC ...." you should input the credentials in the OIDC provider's login page?

**Comment by luckymagic7** [comment]
<img width="467" alt="Screen Shot 2020-07-30 at 11 27 27 AM" src="https://user-images.githubusercontent.com/33619494/88873467-a88caa00-d257-11ea-8a9f-335edb3cc19e.png">

`If you click "Login via OIDC ...." you should input the credentials in the OIDC provider's login page?`
-> yes, it works fine.

**Comment by reasonerjt** [comment]
@luckymagic7 Thanks a lot of the nice screenshot!

This is the current design because once Harbor is set to oidc auth mode, the local login does not work for regular users, the input fields are for internal admin user only.

**Comment by reasonerjt** [comment]
We may consider redesigning the login dialog when Harbor is configured to use OIDC.

For example the input text boxes for username and password can be folded and they will apear only when user click the link "Login as internal admin user"

**Comment by reasonerjt** [comment]
cc @xaleeks
