### ISSUE TITLE
Google OAuth endpoint update

### ISSUE THREAD

**Issue by rvennam-lbg** [goharbor/harbor#12627]
What can we help you?

This is needed when we are deploying to GCP with VPC service controls enabled where all the internal GCP API's will be able to be accessible from within the google backbone. This change would not break any other functionality as the DNS resolution will differ based on where these requests are being sent from.

Refer to the link explaining how the private connectivity works.

https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity

Below is the email chain from Google

=============================

At the time we introduced VPC SC, we changed the OAuth endpoints for Google APIs to be hosted under the googleapis.com DNS domain, so that only that zone needed to be available on private Cloud DNS to run the workloads inside the perimeter. For example, the token info endpoint was changed like this:

accounts.google.com/o/oauth2/tokeninfo -> oauth2.googleapis.com/tokeninfo
accounts.google.com/o/oauth2/token -> oauth2.googleapis.com/token

The client libraries were updated to refer to the new endpoints, and for applications that did not use the standard libraries we tried to cover support (here's the change I submitted for Terraform to use the new endpoints).

Since your application is using the old endpoints, DNS is not responding to the private.googleapis.com VIP, and the request is matching the default route/firewall rule, which is not allowed in the VM/GKE node.

Thanks,
Raghu Vennam

**Comment by reasonerjt** [comment]
I think it SHOULD work, have you had a chance to verify?
@rvennam-lbg

**Comment by MohamedTalhaoui** [comment]
Hi,

I think I am hitting the a related issue.
I have deployed Harbor in a VPC with service controls enabled.
Harbor uses GCS as Image and Charts storage.
I can push charts to Harbor and can see it is correctly stored to GCS.
But I cannot push any image.

Digging inot the logs I have:
```
time="2020-10-14T08:52:20.598498295Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown 
err.detail="gcs: Get https://storage.googleapis.com/<xxx>/docker/registry/v2/repositories/<xxx>/_layers/sha256/<xxx>/link: **oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 172.217.168.13:443: i/o timeout"** 
err.message="unknown error" go.version=go1.13.8 http.request.host="harbor-app-harbor-core:443" http.request.id=9e65e0f4-53bf-4c52-b7a2-e864e7ec41e9 http.request.method=HEAD http.request.remoteaddr=172.22.1.25 
http.request.uri="/v2/<xxx>/blobs/sha256:<xxx>" http.request.useragent=harbor-registry-client 
http.response.contenttype="application/json; charset=utf-8" http.response.duration=30.238396262s http.response.status=500 http.response.written=344 vars.digest="sha256:<xxx>" vars.name="<xxx>" 
```

Which shows a timeout trying to reach accounts.google.com.
The endpoint should be oauth2.googleapis.com/token here, right ?

Is there any reason this is working for Helm charts and not for Docker images ?

**Comment by MohamedTalhaoui** [comment]
So the go client still reference accounts.google.com here
https://godoc.org/golang.org/x/oauth2/google#pkg-variables

Using the harbor helm chart I am limited to the exposed configuration for the GCS storage backed
https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-cm.yaml#L37
vs what is supported:
https://docs.docker.com/registry/configuration/#storage

I guess if you don't use helm, you can add **auth_uri** and **token_uri** to the storage backend configuration.
In my case, I will try to patch the config map in some way as a workaround
