### ISSUE TITLE
Replication Rule setup in Harbor does not display the exact cause of the error

### ISSUE THREAD

**Issue by prahaladdarkin** [goharbor/harbor#12625]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I am attempting to setup a replication rule under **Administration** --> **Replication**. To enable Replication I need to create a source **Endpoint**
When creating a **Endpoint**, after the required details and credentials are entered click on **Test Connection**. I had incorrect credentials due to a typo and the error message that was displayed was **Failed to ping endpoint**. It would be helpful to also specify the exact cause of the error.

**Expected behavior** - A clear error message stating the underlying reason on why the registry connection failed
**Actual Behavior** - Please refer below screenshot

<img width="573" alt="Screenshot 2020-07-30 at 7 54 29 AM" src="https://user-images.githubusercontent.com/30070908/88873370-23df6300-d23a-11ea-81c6-d7f23b156d47.png">

**Steps to reproduce the problem:**
* Login to Harbor
* Create an endpoint using **Administration -> Registries**
* When specifying details for the endpoint, specify an incorrect credential
* Click on **Test Connection**

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by bitsf** [comment]
You can check /var/log/harbor/core.log

**Comment by wy65701436** [comment]
and it's by design not to return the details information as there may be security issue.
