### ISSUE TITLE
Chartmuseum still uses old domain URLs after switching to new

### ISSUE THREAD

**Issue by camelx1** [goharbor/harbor#12620]
**Expected behavior and actual behavior:**
I had to change my server name from myhub.old.domain to myhub.new.domain
I changed hostname in the harbor.yml, run ./prepare, and run new deployment.
Harbor's part works well with new domain name, except Chartmuseum part

I expected that helm chart will have new download url, but it still uses old url:

`curl -k -u admin:password https://myhub.new.domain/chartrepo/myproject/index.yaml
apiVersion: v1
entries:
  myproject:
  - apiVersion: v1
    created: "2020-07-27T12:29:46.034601982Z"
    digest: d1456101b7156948889670dbfe7dd99a80d9be64fd09c802996816ac0cd614a9
    name: mychart
    urls:
    - https://myhub.old.domain/chartrepo/myproject/mychart-18.2.0.0.tgz
    version: 18.2.0.0
generated: "2020-07-27T12:29:46Z"
serverInfo: {}
`

**Versions:**
- harbor version: [2.0.1]
- docker engine version: [17.12.0-ce]
- docker-compose version: 1.24.1]

H

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
Did you tried clear the chartmuseum's cache in disk and redis?

**Comment by camelx1** [comment]
> Did you tried clear the chartmuseum's cache in disk and redis?

No, How i can do it?

 and just for FYI: I have never used chartmuseum with old domain.

**Comment by ninjadq** [comment]
remove the `index-cache.yaml` in your chart_storage dir under `data_volume` 
at the same time clear the redis database of your chart

**Comment by camelx1** [comment]
> remove the `index-cache.yaml` in your chart_storage dir under `data_volume`
> at the same time clear the redis database of your chart

It  helped me,
Thanks a lot.

**Comment by pgkulk** [comment]
@camelx1 @ninjadq how do I clear the redis database of helm chart only? 
Using "redis-cli FLUSHALL" inside redis-photon container? 
Thank you!
