### ISSUE TITLE
harbor1.4中img_scan_job表数据太多，可以清空数据吗

### ISSUE THREAD

**Issue by zhangzhenyu2** [goharbor/harbor#12623]
harbor1.4中img_scan_job表数据太多，可以清空数据吗，是否影响正常功能。

**Comment by wy65701436** [comment]
is it possible to upgrade your harbor to the latest version?

**Comment by steven-zou** [comment]
@zhangzhenyu2 

For all the complete data (status not equal `running`) or data before a specified date can be cleaned.

**Comment by steven-zou** [comment]
Your version is too old, we suggest you upgrade to the newer version(1.10+).

For clean data, considering safety, backup your data before cleaning.
