### ISSUE TITLE
How to reset lost admin password

### ISSUE THREAD

**Issue by lalithvaka** [goharbor/harbor#12639]
What can we help you?
With out looking at the comments in harbor.yml,  I have re ran the ./prepare with updated password to change the Admin password from the default Harbor12345. Now am not able to retrieve. the password even though I tried following https://github.com/goharbor/harbor/issues/8778.

![image](https://user-images.githubusercontent.com/8292387/88999414-5eccaf80-d2a9-11ea-85e2-6d664d98695f.png)

Tried updating the password field directly in the data base per #8778 screenshot but still no use.

**Comment by lalithvaka** [comment]
Just to provide sequence of steps 
1. Installed Harbor on a VM with RHEL 7.X with out Http with default Harbor admin password and default DB password
2. Applied https config using self signed certificates
3. reran the ./prepare process 
4. Harbor is up and running with the default admin password. 
5. Created an additional user and did some settings changes and created a new project / repo.
6. Was able to login using new user and push an image
7. Enabled Clair by running the ./prepare --with-clair option process. everything good so far.
-- at this time, we have taken the VM snapshot and also increased the VM resources (CPU and Memory)
8. Updated both Admin and DB password using Harbor.yml(with out knowing I need to do this through UI) and re ran the ./prepare script.
9. I was not able to login to the browser UI with admin or user 
10. Tried following the steps laid out here https://kb.vmware.com/s/article/76289 to change the admin password and shaw depicted in [here](https://github.com/goharbor/harbor/issues/8778#issuecomment-523729511)
11. Still could not login with either admin or other user.

Hope this helps understand the steps I took.

**Comment by stonezdj** [comment]
Something maybe wrong in step 8.  The DB password cannot be changed in Harbor.yml, Because it is a exsiting database, you should also update the password in database and both in harbor.yml, if you just change the DB password in harbor.yml, it will cause the other component cannot connect to the database, the admin password cannot be reset either.  Change one thing in a time.

**Comment by lalithvaka** [comment]
@stonezdj Can you please suggest how we can restore both the passwords with out impacting the entire setup / projects / images etc?? At this point, admin user and other user on the instance lost access.

**Comment by stonezdj** [comment]
You should rollback the previous username password in harbor.yml and run with prepare, and restart harbor and check the  core.log to make sure the core container can connect to database with the username password.

Then change the admin password in Harbor web admin console. not in the harbor.yml

**Comment by lalithvaka** [comment]
Thank you for all your help
