### ISSUE TITLE
harbor install error

### ISSUE THREAD

**Issue by wuchao1111** [goharbor/harbor#12648]
The ERROR shows as below:
docker: Error response from daemon: Mounts denied: 
The paths /data and /data/secret
are not shared from OS X and are not known to Docker.

I know how to share the file in Docker,but actually where is the directory /data and /data/secret?
I can't find them.

**Comment by wy65701436** [comment]
are you trying to install Harbor on Mac OS? For the `data` location, you have to refer to the `data_volume` in the harbor.yml.

**Comment by wuchao1111** [comment]
> are you trying to install Harbor on Mac OS? For the `data` location, you have to refer to the `data_volume` in the harbor.yml.

yes,I have handling this problem on my Mac for a few days.
the harbor.yml shows:
# The default data volume
data_volume: /data

However, when I type 'cd /data' in my terminal.it says 'cd: no such file or directory: /data';
I want to know when and how the /data is created.
Does that mean I need to create one by myself?

**Comment by wuchao1111** [comment]
> are you trying to install Harbor on Mac OS? For the `data` location, you have to refer to the `data_volume` in the harbor.yml.

thanks!
I have solved my problem.
It seems that I need to change the location in the harbor.yml~
