### ISSUE TITLE
Harbor-to-harbor replications failing after upgrade to Harborv2

### ISSUE THREAD

**Issue by ajchiarello** [goharbor/harbor#12644]
**Expected behavior and actual behavior:**
When setting up a manual replication of all projects and repositories between two instances of harbor, attempting replication fails immediately with the error "failed to fetch artifacts: FetchArtifacts error when collect tags for repos" four times out of five.

Expected behavior would be that the replication would proceed normally.

**Steps to reproduce the problem:**
Create and endpoint to another harbor, and then attempt a replication of all projects and repositories.

**Versions:**

- harbor version: 2.0.1
- docker engine version: 19.3.12
- docker-compose version: N/A - I am installing on Kubernetes 1.18.6 using the bitnami/harbor helm chart v6.0.10

**Comment by wy65701436** [comment]
are those two harbor instance using the same version? and can you share the core and jobservice log both on source and  target node?

**Comment by ajchiarello** [comment]
Yes, they are both running the same version (v2.0.1). I've attached the logs.

[destination-core.log](https://github.com/goharbor/harbor/files/5016670/destination-core.log)
[source-jobservice.log](https://github.com/goharbor/harbor/files/5016671/source-jobservice.log)
[source-core.log](https://github.com/goharbor/harbor/files/5016672/source-core.log)
[destination-jobservice.log](https://github.com/goharbor/harbor/files/5016673/destination-jobservice.log)

**Comment by ajchiarello** [comment]
For more information: I worked my way through all my projects and found that they all work as individual syncs, except for the largest one, which has 63 repositories and 258 artifacts - is that more than I should expect to work?

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/89637208-6957fc00-d8dc-11ea-849f-47a18949b37a.png)
this is the known issue that db connection exceed.
Please upgrade to v2.0.2

**Comment by ajchiarello** [comment]
I've upgraded to v2.0.2, and I am still getting the same error when attempting a large replication ("failed to fetch artifacts: FetchArtifacts error when collect tags for repos").

**Comment by ajchiarello** [comment]
Do you need more logs when for when this occurs in 2.0.2, or should I attempt with 2.1.0 first?

**Comment by bitsf** [comment]
hi, please check if the db max connections is big than 100 now.

`docker exec -it harbor-db psql registry -c "show max_connections;" `
if should be 1024 now.

**Comment by ajchiarello** [comment]
OK - my database is still showing the lower max connections. Possibly because I use the bitnami helm chart (for HA). I'll pursue that angle.
