### ISSUE TITLE
can not perform pull/push from local？

### ISSUE THREAD

**Issue by chenzhikang** [goharbor/harbor#12640]
when i installed harbor of hostA，config the domain and port is xxx.domain.top:9999；
harbor version :v2.0.1;
i have configed Insecure registries;
i have logined to harbor;

i can open harbor dashboard from browser，i also can pull/push in hostB.
This mean the harbor server is correct,also mean the firewall was no problem;
 
but，i can not pull/push in local hostA with below command : 
sudo docker pull xxx.domain.top:9999/library/first_gitlab_project:latest 

docker logs say that:
Jul 30 19:24:59 homeserver dockerd[2599117]: time="2020-07-30T19:24:59.326316118+08:00" level=info msg="Attempting next endpoint for pull after error: Get http://xxx.domain.top:9999/v2/library/first_gitlab_project/manifests/latest: read tcp 192.168.3.167:58528->113.120.111.xxx:9999: read: connection reset by peer"
Jul 30 19:24:59 homeserver dockerd[2599117]: time="2020-07-30T19:24:59.326481572+08:00" level=error msg="Handler for POST /v1.40/images/create returned error: Get http://xxx.domain.top:9999/v2/library/first_gitlab_project/manifests/latest: read tcp 192.168.3.167:58528->113.120.111.xxx:9999: read: connection reset by peer"

It's strange that i can pull ok with localhost address:
sudo docker pull localhost:9999/library/first_gitlab_project:latest
sudo docker pull 127.0.0.1:9999/library/first_gitlab_project:latest
sudo docker pull 192.168.3.167:9999/library/first_gitlab_project:latest

**Comment by chenzhikang** [comment]
sudo docker-compose ps

      Name                     Command                  State                 Ports          
---------------------------------------------------------------------------------------------
harbor-core         /harbor/entrypoint.sh            Up (healthy)                            
harbor-db           /docker-entrypoint.sh            Up (healthy)   5432/tcp                 
harbor-jobservice   /harbor/entrypoint.sh            Up (healthy)                            
harbor-log          /bin/sh -c /usr/local/bin/ ...   Up (healthy)   127.0.0.1:1514->10514/tcp
harbor-portal       nginx -g daemon off;             Up (healthy)   8080/tcp                 
nginx               nginx -g daemon off;             Up (healthy)   0.0.0.0:9999->8080/tcp   
redis               redis-server /etc/redis.conf     Up (healthy)   6379/tcp                 
registry            /home/harbor/entrypoint.sh       Up (healthy)   5000/tcp                 
registryctl         /home/harbor/start.sh            Up (healthy)

**Comment by wy65701436** [comment]
I don't quite understand the problem, can you give more details, what is Host A and  Host B? 

- How did your configurate the Harbor instances A and B? 
- Are you trying to configurate HA with offline installer?

**Comment by chenzhikang** [comment]
> I don't quite understand the problem, can you give more details, what is Host A and Host B?
> 
> * How did your configurate the Harbor instances A and B?
> * Are you trying to configurate HA with offline installer?

hostA hostB just mean two  linux OS

**Comment by chenzhikang** [comment]
update:
the issue seems not because harbor，i reproduce this issue with docker-registry;
finally,i set a record in hosts file,and solve this problem;
127.0.0.1 xxx.domain.top
