### ISSUE TITLE
harbor-core容器启动异常

### ISSUE THREAD

**Issue by zhangfan-5391621** [goharbor/harbor#12643]
harbor.v2.0.1

Jul 31 16:47:42 172.20.0.1 core[8730]: [ORM]2020/07/31 08:47:42 register db Ping `default`, pq: password authentication failed for user "postgres"
Jul 31 16:47:42 172.20.0.1 core[8730]: 2020-07-31T08:47:42Z [FATAL] [/core/main.go:120]: failed to initialize database: register db Ping `default`, pq: password authentication failed for user "postgres"

Restarting (1) 23 seconds ago
~

**Comment by wy65701436** [comment]
how did you installl Harbor? internal or external DB? Did you update the db password? 

Any details will help us to triage, thanks.
