### ISSUE TITLE
Provide a service to handle the icon of artifacts.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12658]
As is required by 
https://github.com/goharbor/harbor/issues/12657

Harbor should provide an internal service to handle the icon, do basic verification, cache the data, and UI should call and specific URI (represented as an addition?) to render it.

It is TBD as for the default icons, should it from the backend or render at the front end as before

**Comment by ywk253100** [comment]
We'll introduce a new API `GET /api/v2.0/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/icon` to serve the icon resource.

For the icon of well-known(image, helm chart, CNAB, ...) and unknown artifacts, two options:
1. The backend core service serves all kinds of icon, a new method `GetIcon` needs to be added in the `Processor` interface
2. The front end determines the type of artifact and is responsible for the static icon file(icons for image, helm chart, CNAB and the default one)

**Comment by ywk253100** [comment]
Done by https://github.com/goharbor/harbor/pull/12683
