### ISSUE TITLE
Upload of Index.yaml

### ISSUE THREAD

**Issue by snyderdb** [goharbor/harbor#12653]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by snyderdb** [comment]
I am using VMWare Harbor 2.1.0. I have a set of child charts that I will push to ChartMuseum. I also have an index.yaml file that was created as a result of running helm repo index.

I have read that I should upload the index.yaml file to Chart Museum. But, Chart Museum will only support uploading of .tgz files.

Can someone advise how I can upload the index.yaml to the Chart Museum repo?

Thank you

**Comment by wy65701436** [comment]
@steven-zou can you help？

**Comment by snyderdb** [comment]
Hello Yan. Do u need help?

**Comment by steven-zou** [comment]
@snyderdb 

You don't need to upload the index.yaml file the ChartMuseum as it will generate that file at the server-side.

@ninjadq 

Can you confirm the answer?

**Comment by ninjadq** [comment]
> @snyderdb
> 
> You don't need to upload the index.yaml file the ChartMuseum as it will generate that file at the server-side.
> 
> @ninjadq
> 
> Can you confirm the answer?

yes, that file is auto-generated by chartmuseum

**Comment by snyderdb** [comment]
Thank you so much steven-zou and ninjadq!  Tremendously appreciated!
