### ISSUE TITLE
harbor 1.9.1 image 0B data1/1/1

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#12667]
hello!
     Why does this happen? How is it triggered?  in the webUI , it show size 0B and createtime 1/1/1

**Comment by wy65701436** [comment]
the 0 size issue has been fixed in Harbor v2.0.0, you can try to upgrade.

**Comment by minxiaogang** [comment]
can you tell me why does this happen? and Can you give me a tutorial or link on upgrading with harbor:1.9.1 to harbor2.0.0+,Better be more specific,we use helm install harbor. thanks!

**Comment by wy65701436** [comment]
for upgrding from v1.9.1 to v2.0.0, you can refer to the upgrade document.
