### ISSUE TITLE
WEB project could not show image,but can download

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#12666]
web界面项目里面镜像仓库点开看不到镜像，但是上传成功了，也可以起下载。显示标签0 下载数2.

In the web interface project, you can't see the image when you click open the image warehouse. However, if the upload is successful, you can download it. Display tab 0 downloads 2.

**Comment by minxiaogang** [comment]
harbor 1.9.1 , thanks

**Comment by wy65701436** [comment]
Can you check the repository and artifact table in the DB for you image? And you can try to re-push it.

BTW, you'd better to upgrade Harbor to latest.

**Comment by minxiaogang** [comment]
1. ###Can you check the repository and artifact table in the DB for you image?
    can you tell me which table store the image info in the postgresql?  I checked all the tables, but I couldn't find them. Can you 
    tell me the name of the table?
2. ###And you can try to re-push it.?   yes,I do it. and it is ok ,I can see it in the WEB UI---project.

**Comment by wy65701436** [comment]
`artifact` and `repository` are the table names you can check in PGsql.

**Comment by minxiaogang** [comment]
yes,I checked the artifact this table。 I found the image and tag in the artifact table, but In the web interface project, I can't see the image . how to solve this?

**Comment by wy65701436** [comment]
did you see the data in the repository table? and any error in core.log?

**Comment by minxiaogang** [comment]
yes,i see it.  no erroe in core.log. we use storage S3

**Comment by minxiaogang** [comment]
How to solve this problem? It appears again, can push successfully, but the web interface does not display, can also download！！！help!!!

**Comment by wy65701436** [comment]
hi @minxiaogang , can you try to update Harbor to the latest? Since v1.9 is too old for team to provide help.
