### ISSUE TITLE
error when I go build the project

### ISSUE THREAD

**Issue by mzzgaopeng** [goharbor/harbor#12680]
when I make the harbor
[root@localhost core]# go build -v -o .
../common/models/label.go:20:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/models": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/models
../server/v2.0/handler/handler.go:25:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi
../server/v2.0/handler/artifact.go:40:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/artifact": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/artifact
../server/v2.0/handler/auditlog.go:15:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/auditlog": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/auditlog
../server/v2.0/handler/project.go:10:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/project": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/project
../server/v2.0/handler/repository.go:32:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/repository": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/repository
../server/v2.0/handler/scan.go:26:2: unknown import path "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/scan": cannot find module providing package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/scan
[root@localhost core]# pwd
/root/go/src/github.com/goharbor/harbor/src/core

**Comment by wy65701436** [comment]
please run the `make gen_apis` before building source code.

**Comment by wy65701436** [comment]
can you add document(https://github.com/goharbor/harbor/blob/master/CONTRIBUTING.md) for this?

**Comment by zetaab** [comment]
Could you please include these artifacts to source code. Now it is impossible to use harbor as library

```
	github.com/goharbor/harbor/src/pkg/notifier/model imports
	github.com/goharbor/harbor/src/common/models imports
	github.com/goharbor/harbor/src/server/v2.0/models: module github.com/goharbor/harbor/src@latest found (v0.0.0-20200818082251-f7e1d186e0fe), but does not contain package github.com/goharbor/harbor/src/server/v2.0/models
```

**Comment by heww** [comment]
> Could you please include these artifacts to source code. Now it is impossible to use harbor as library in another application
> 
> ```
> 	github.com/goharbor/harbor/src/pkg/notifier/model imports
> 	github.com/goharbor/harbor/src/common/models imports
> 	github.com/goharbor/harbor/src/server/v2.0/models: module github.com/goharbor/harbor/src@latest found (v0.0.0-20200818082251-f7e1d186e0fe), but does not contain package github.com/goharbor/harbor/src/server/v2.0/models
> ```

Hi @zetaab , I think this issue was fixed by https://github.com/goharbor/harbor/pull/12936 , can you help to verify it?

**Comment by hyy0322** [comment]
Would you merge #12936 to release-2.1 ?

**Comment by heww** [comment]
> Would you merge #12936 to release-2.1 ?

No, we don't cherry-pick this PR to release-2.1.0.
