### ISSUE TITLE
Allow users to login with refresh token

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [goharbor/harbor#12684]
**Is your feature request related to a problem? Please describe.**
End users (including Limited Guests) would like the ability to authenticate with harbor without using their password, particularly when setting up automation (CI jobs that pull images), or shared environments (kubernetes clusters that need registry secrets).

**Describe the solution you'd like**
Allow the user to provide an oauth refresh token (that they fetch out-of-band from the identity provider) in place of their password. This approach is similar to how GCR allows login with a [json key](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key) or dockerhub allows login with an [access token](https://docs.docker.com/docker-hub/access-tokens/#use-an-access-token)

**Describe the main design/architecture of your solution**
The different [AuthenticateHelper](https://github.com/goharbor/harbor/blob/master/src/core/auth/authenticator.go#L62) implementations would need to be able to authenticate with `grant_type=refresh_token` in addition to `grant_type=password`. 

Deciding which grant type to use can be based on:
1) a special username (like GCP)
2) identify if the secret is a token or password (e.g. UAA supports JWT tokens, or opaque tokens ending in "-r")
3) naively try both if 2) can't be reliably achieved

Using a special username would be simplest and most reliable. It would also prevent the edge case where a user provides a username that doesn't match the token.

e.g. if the [UAA Client](https://github.com/goharbor/harbor/blob/master/src/common/utils/uaa/client.go) implemented token refresh as:
```
func (dc *defaultClient) RefreshTokenAuth(refreshToken string) (*oauth2.Token, error) {
	tokenURL := dc.endpoint + TokenURLSuffix
	req, err := http.NewRequest(http.MethodPost, tokenURL, nil)
	if err != nil {
		return nil, err
	}
	v := url.Values{}
	v.Set("client_id", dc.oauth2Cfg.ClientID)
	v.Set("client_secret", dc.oauth2Cfg.ClientSecret)
	v.Set("grant_type", "refresh_token")
	v.Set("token_format", "jwt") // or "opaque" - may need format to be configurable when deploying harbor
	v.Set("refresh_token", refreshToken)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")
	resp, err := dc.httpClient.PostForm(tokenURL, v)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	token := &oauth2.Token{}
	if err := json.Unmarshal(data, token); err != nil {
		return nil, fmt.Errorf("error unmarshaling token: %v\n", err)
	}
	if !token.Valid() {
		return nil, fmt.Errorf(string(data))
	}
	return token, nil
}
```
then the [UAA AuthenticateHelper](https://github.com/goharbor/harbor/blob/master/src/core/auth/uaa/uaa.go#L40) would become:
```
func (u *Auth) Authenticate(m models.AuthModel) (*models.User, error) {
	if err := u.ensureClient(); err != nil {
		return nil, err
	}
	var t *oauth2.Token
	if m.Principal == "_refresh_token" {
		t, err := u.client.RefreshTokenAuth(m.Password)
	} else {
		t, err := u.client.PasswordAuth(m.Principal, m.Password)
	}
	if err != nil {
		return nil, auth.NewErrAuth(err.Error())
	}
	info, err2 := u.client.GetUserInfo(t.AccessToken)
	if err2 == nil {
		return &models.User{
			Username: info.UserName,
			Email: info.Email,
			Realname: info.Name,
		}, nil
	}
	log.Warningf("Failed to extract user info from UAA, error: %v", err2)
	return nil, err2
}
```

**Describe the development plan you've considered**
Exposing refresh auth as part of the AuthenticateHelper interface might reduce duplication of having every implementation do the `if m.Principal == "_refresh_token"` check. Ideally all helpers would support token auth for feature parity, but they need not be updated all at once.

**Additional context**
A theoretical alternative would be to have the harbor admin/site admin create and manage a robot account for each limited guest, but:
- this scales poorly (thousands of users needing access to 10s or hundreds of projects)
- adds complexity (requiring external automation to provision a set of robots for each new user) 
- is inconsistent with what other registries (GCR, DockerHub, etc) offer
- per-project robots would require frequent reauthentication with different credentials

**Comment by xaleeks** [comment]
@xtreme-conor-nosal @reasonerjt per our discussion, this is no longer required and Conor will investigate oidc cli token as an alternative.  Please let us know if your support stance on UAA changes and we can shift priorities.  Can reopen if we decide to pursue again
