### ISSUE TITLE
Unable to get robot access levels or reset robot token

### ISSUE THREAD

**Issue by mattdowdell** [goharbor/harbor#12692]
**Is your feature request related to a problem? Please describe.**

I would like to be able to tell when a robot has the expected access (push or pull+push) and modify those that don't have the expected permissions. I would also like to be able to reset the token if necessary.

**Describe the solution you'd like**

Add/Extend API endpoints to support the proposed feature and the associated GUI changes.

**Describe the main design/architecture of your solution**

- Extend `GET /projects/{project_id}/robots` and `GET /projects/{project_id}/robots/{robot_id}` to return a model with the `access` field present, following the same underlying schema as used for `POST /projects/{project_id}/robots`. The new model in JSON would be as follows:

    ```json
    {
        "update_time": "string",
        "description": "string",
        "creation_time": "string",
        "expires_at": "int",
        "disabled": "bool",
        "project_id": "int",
        "id": "int",
        "name": "string",
        "access": [
            {
                "action": "string",
                "resource": "string"
            }
        ]
    }
    ```

- Add `POST /projects/{project_id}/robots/{robot_id}/token` to reset the token for the robot account. This would take no request body and re-use the model used for the response to `POST /projects/{project_id}/robots`.
- Extend `PUT /projects/{project_id}/robots/{robot_id}` to allow the `access`, `name`, `description` fields to be updated in addition to the `disabled` field.

**Describe the development plan you've considered**

Perhaps overstepping the mark, but personally I'd break it down into the following:

- Each API endpoint should be independent of each other, but I would do them in the following order:
    - `GET /projects/{project_id}/robots` + `GET /projects/{project_id}/robots/{robot_id}`. This means that robots found not to conform can be deleted and recreated.
    - `POST /projects/{project_id}/robots/{robot_id}/token`. In the mean time, robots can be deleted and recreated.
    - `PUT /projects/{project_id}/robots/{robot_id}`
- The GUI work naturally follows the API changes, but I would guess it is decoupled enough to allow the API changes without the GUI needing to be updated.

**Additional context**

None

**Comment by mattdowdell** [comment]
Bump

**Comment by d4vydm** [comment]
(my apologies upfront if I am not following some kind of agreement on comments on this project)


@mattdowdell agree, would be good feature.

I encounter following:

When creating a robot account through API I get stuck on the access policy.

My input file is:
`{
  "access": [
    {
      "resource": "ResourceRepository",
      "action": "ActionPush"
    }
  ],
  "name": "test",
  "expires_at": 0,
  "description": "test robot"
}`

Now it is unclear what the value of "resource" and "action" should be, and it is not documented.
But whatever maybe feasible value I type in de access policy section, i get:
`message: ... action of ... resource not exist in project sensors`

Which is a validation code from the API:
src/server/v2.0/handler/robotV1.go

So the above feature request would be great because it would allow you to see the options the GUI configures when creating the robot account.

**Comment by mattdowdell** [comment]
> From documentation it is unclear what the value of "resource" and "action" should be.

I more or less gave up on the documentation. The newer APIs are better, but unfortunately the legacy swagger is often missing fields or just plain wrong. I resorted to inspecting the network requests in browser devtools to figure out what was actually happening.

**Comment by wy65701436** [comment]
hi, @mattdowdell @d4vydm does the robot v2 meet your requirement? If not, reopen this issue.

**Comment by mattdowdell** [comment]
@wy65701436 I haven't had a chance to upgrade my Harbor instance to verify properly, but judging by the [swagger spec](https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L3030) and [docs](https://goharbor.io/docs/2.3.0/administration/robot-accounts/), I think it's all there. Thanks for adding this :)
