### ISSUE TITLE
The maintainer(s) info of the p2p provider is confused

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#12705]
The maintainer(s) info of the provider is confused, for the following info I will think that the kraken is maintained by `mmpei/peimingming@corp.netease.com` but the source is `https://github.com/uber/kraken`. In general, Kraken is the product of uber.

![image](https://user-images.githubusercontent.com/5634205/89851690-afa0aa00-dbbf-11ea-87f0-fd383c287155.png)

**Comment by steven-zou** [comment]
Preheat function is maintained by @mmpei and the code is in the Kraken codebase that is an OSS project.

I don't think we need to do changes to such info.
