### ISSUE TITLE
The "Cache-Control" header doesn't work because the cookie changes in every response

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#12704]
![image](https://user-images.githubusercontent.com/5835782/89851746-d19a2c80-dbbf-11ea-83a4-3b2310f855db.png)

The cookie is set by CSRF middleware.

**Comment by reasonerjt** [comment]
If we return `Set-Cookie` the `Vary` must be set so the token will not be cached.  
The problem is if a request already has a valid CSRF token the `Set-Cookie` is not needed.

**Comment by reasonerjt** [comment]
Marking this as `defer-candidate` as the API currently is not setting the `Cache-Control` header.

**Comment by reasonerjt** [comment]
Closing this issue as after https://github.com/goharbor/harbor/pull/12826 is merged the `__csrf` won't be set as cookie.
