### ISSUE TITLE
No method to unset p2p provider to not default

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#12715]
After creating the first p2p instance which is not the default one, then I can set the instance to the default, but I can't unset the instance to not default one to back to the original status after creating the first p2p instance.

There are two options to resolve this problem:
1. Provide the method to unset p2p provider to not default.
2. The first created instance is the default one and there must exist one instance which is the default like the behavior of the scanner.

**Comment by steven-zou** [comment]
@AllForNothing 

Any usage of `default` property of a provider instance at the front end? If not, let's hide it from the front end now.

**Comment by steven-zou** [comment]
Possible related to https://github.com/goharbor/harbor/issues/12706
