### ISSUE TITLE
The freed size by GC doesn't equal with quota

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#12717]
Replicate library/golang:1.14.5 from docker hub, the quota shows 2.46 GB, but after running GC, the log says freed size is 10195 MB.
Maybe it's related with the windows images

**Comment by wy65701436** [comment]
dup with： https://github.com/goharbor/harbor/issues/12710

**Comment by wy65701436** [comment]
GC job should exclude the foreign layer.
