### ISSUE TITLE
Pull cached images might be failed with 500 error suddenly

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#12714]
**cmd:**

```shell
steven@steven-zou:~/testing-day/harbor$ docker pull <harbor-host>/szou_proxy/library/redis:5.0
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
steven@steven-zou:~/testing-day/harbor$ docker pull <harbor-host>szou_proxy/library/redis:5.0
5.0: Pulling from szou_proxy/library/redis
Digest: sha256:ab3998e18bfaa570fad08c884ffbcc7861f59caf736a5a0c1ad5383c4d863958
Status: Image is up to date for <harbor-host>/szou_proxy/library/redis:5.0
<harbor-host>/szou_proxy/library/redis:5.0
```

**core logs:**

>Aug 11 06:35:34 172.26.0.1 core[9962]: 2020-08-11T06:35:34Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with topic 'CREATE_PROJECT': &event.CreateProjectEvent{EventType:"CREATE_PROJECT", ProjectID:4, Project:"myproj", Operator:"szou2", OccurAt:time.Time{wall:0xbfc4aced8604ac79, ext:3253359829467, loc:(*time.Location)(0x3610ec0)}}
Aug 11 06:39:36 172.26.0.1 core[9962]: 2020-08-11T06:39:36Z [ERROR] [/lib/orm/orm.go:78]: commit transaction failed: unexpected command tag SELECT
Aug 11 06:39:36 172.26.0.1 core[9962]: 2020-08-11T06:39:36Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: deal with /v2/szou_proxy/library/redis/manifests/5.0 request in transaction failed: unexpected command tag SELECT"}]}
Aug 11 06:39:36 172.26.0.1 core[9962]: 2020-08-11T06:39:36Z [ERROR] [/controller/proxy/controller.go:127]: failed to get manifest, error sql: transaction has already been committed or rolled back
Aug 11 06:39:44 172.26.0.1 core[9962]: 2020-08-11T06:39:44Z [ERROR] [/controller/proxy/controller.go:127]: failed to get manifest, error sql: transaction has already been committed or rolled back
Aug 11 06:39:45 172.26.0.1 core[9962]: 2020-08-11T06:39:45Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with topic 'PULL_ARTIFACT': &event.PullArtifactEvent{ArtifactEvent:(*event.ArtifactEvent)(0xc0002a1c00)}
Aug 11 06:39:45 172.26.0.1 core[9962]: 2020-08-11T06:39:45Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with topic 'PULL_ARTIFACT': &event.PullArtifactEvent{ArtifactEvent:(*event.ArtifactEvent)(0xc0002a1c00)}
Aug 11 06:39:45 172.26.0.1 core[9962]: 2020-08-11T06:39:45Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with topic 'PULL_ARTIFACT': &event.PullArtifactEvent{ArtifactEvent:(*event.ArtifactEvent)(0xc0002a1c00)}
Aug 11 06:39:56 172.26.0.1 core[9962]: 2020-08-11T06:39:56Z [ERROR] [/controller/proxy/controller.go:189]: error when push manifest list to local :sql: transaction has already been committed or rolled back
Aug 11 06:39:56 172.26.0.1 core[9962]: 2020-08-11T06:39:56Z [ERROR] [/controller/proxy/controller.go:139]: failed to get manifest, error sql: transaction has already been committed or rolled back

**Comment by steven-zou** [comment]
Repeat the same cmd, failures will frequently occur

**Comment by wy65701436** [comment]
get the same error, with log


```
Aug 11 01:15:53 172.22.0.1 core[1454]: 2020-08-11T08:15:53Z [ERROR] [/lib/orm/orm.go:78]: commit transaction failed: unexpected command tag SELECT
Aug 11 01:15:53 172.22.0.1 core[1454]: 2020-08-11T08:15:53Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: deal with /v2/mycache/library/redis/manifests/latest request in transaction failed: unexpected command tag SELECT"}]} 
Aug 11 01:15:53 172.22.0.1 core[1454]: 2020-08-11T08:15:53Z [ERROR] [/controller/proxy/controller.go:127]: failed to get manifest, error sql: transaction has already been committed or rolled back
Aug 11 01:16:13 172.22.0.1 core[1454]: 2020-08-11T08:16:13Z [ERROR] [/controller/proxy/controller.go:189]: error when push manifest list to local :sql: transaction has already been committed or rolled back
Aug 11 01:16:13 172.22.0.1 core[1454]: 2020-08-11T08:16:13Z [ERROR] [/controller/proxy/controller.go:139]: failed to get manifest, error sql: transaction has already been committed or rolled back
Aug 11 01:16:13 172.22.0.1 core[1454]: 2020-08-11T08:16:13Z [ERROR] [/controller/proxy/controller.go:127]: failed to get manifest, error sql: transaction has already been committed or rolled back
```

**Comment by stonezdj** [comment]
duplicate with 12741
