### ISSUE TITLE
Blank author displayed when maintainers are specified via Dockerfile labels

### ISSUE THREAD

**Issue by occupytheweb** [goharbor/harbor#12734]
**Expected behavior and actual behavior:**
The `author` field of the image summary UI is blank when [specifying maintainers via labels](https://docs.docker.com/engine/reference/builder/#:~:text=The%20LABEL%20instruction%20is%20a%20much%20more%20flexible%20version%20of%20this%20and%20you%20should%20use%20it%20,instead).
It is expected that the author information is sourced from `maintainer` label of an image, as was the case in harbor v1. 

**Steps to reproduce the problem:**
Publish an image using `LABEL maintainer="xxx"`.
Note that the `author` field is blank:

![with_label](https://user-images.githubusercontent.com/7443943/89883681-8725a980-dbd9-11ea-8f34-9888ab1b55bb.png)

The [deprecated](https://docs.docker.com/engine/reference/builder/#:~:text=MAINTAINER%20(deprecated)) `MAINTAINER` directive remains supported.

![with_directive](https://user-images.githubusercontent.com/7443943/89883935-e4b9f600-dbd9-11ea-9fef-861483ea84f0.png)

v1 supported `maintainer` labels:

![v1](https://user-images.githubusercontent.com/7443943/89884200-424e4280-dbda-11ea-8532-5056029307d8.png)

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.x.x]

**Additional context:**

Support for populating the author field from Dockerfile labels was added by #3790.

**Comment by ywk253100** [comment]
Fixed
