### ISSUE TITLE
Improperly handle auth session after all the redis sentinel are down

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#12732]
![Screen Shot 2020-08-11 at 17 26 16](https://user-images.githubusercontent.com/5753287/89881315-f14d4700-dbf7-11ea-8c62-69a3ebf9f88d.png)

All the sentinel nodes are down. At this time, when doing regular operations on the web UI. Sometimes, it does work and sometimes not. The authentication alert is popped up.

Click the `login` directly back to the normal view.
After a while, no responses when clicking the `login` link button.

**Comment by bitsf** [comment]
beego framework is using redis to cache session cookie
I think the weird behavior is acceptable, if it can be recovery when redis come back.
