### ISSUE TITLE
Getting Projects without authentication

### ISSUE THREAD

**Issue by vipingupta5352** [goharbor/harbor#12730]
I have setup Harbor registry on ec2 instance.

If I hit the api `/api/v2.0/projects?page=1&page_size=15&name={name}` to get list of all projects without Authentication

**Expected Behavior**
I should get HTTP status code 401 and body 
```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "UnAuthorize"
        }
    ]
}
```
**Actual Behavior**
I get the list of all projects in the registry.

**Versions:**
- Harbor version: v2.0.2

**Comment by ywk253100** [comment]
The public projects can be fetched without authentication
