### ISSUE TITLE
Error while runing docker login registry.xxxxxxx.com

### ISSUE THREAD

**Issue by click2cloud-vivekg** [goharbor/harbor#12739]
Error response from daemon: Get https://registry.xxxxxxxxx.com/v2/: Get http://registry.xxxxxxxxxxxxxxx.com:8091/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by ywk253100** [comment]
Is `http://registry.xxxxxxxxxxxxxxx.com:8091` running well? Seems it's the network issue between the docker client and the server

**Comment by click2cloud-vivekg** [comment]
Got it's working thanks for your update
