### ISSUE TITLE
[proxy cache] it needs to immediately fail the docker push to a proxy cache project

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12731]
when I try to push a project to a proxy cache project, the return code(415) makes docker client retry pushing.

User `412` can fix it.

**Comment by heww** [comment]
I think to process this problem in the `/service/token` will better, exclude the push action for the proxy cache project.

**Comment by ywk253100** [comment]
@heww The pushing requests can be authenticated via different ways: bearer token, basic auth, secret and others.
