### ISSUE TITLE
Forgot password vanished for db_auth on sign-in page

### ISSUE THREAD

**Issue by monofone** [goharbor/harbor#12745]
Hi,

we currently have db_auth running and need the ability to let users set their own password. I found the dialog still exists in the sign-in component, but the logic for the link to open the dialog is removed, is this on purpose ?

Regards monofone

**Comment by ywk253100** [comment]
The ability of resetting password has been removed both in back-end and front-end, please refer to https://github.com/goharbor/harbor/issues/10712.

And the dialog in your environment should be the cache of browser

**Comment by monofone** [comment]
Hey,

thanks for the answer, this was the issue I searched for but didn't found it. 
The location I mentioned is here https://github.com/goharbor/harbor/blob/master/src/portal/src/app/sign-in/sign-in.component.html#L47.

Regards monofone
