### ISSUE TITLE
[proxy cache] sql error in the log

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12741]
I see such error in the log:
```
Aug 11 12:54:47 172.18.0.1 core[4975]: 2020-08-11T12:54:47Z [ERROR] [/controller/proxy/controller.go:127]: failed to get manifest, error sql: transaction has already been committed or rolled back
```
Is it because the sequence of middlewares caused all DB calls in the proxy controller failed with such error?

**Comment by wy65701436** [comment]
dup with https://github.com/goharbor/harbor/issues/12714 ?

**Comment by reasonerjt** [comment]
Looks like it is but I'll let @stonezdj make the call.
