### ISSUE TITLE
[proxy cache] Is it necessary to create a default retention policy in the proxy cache project?

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12743]
![image](https://user-images.githubusercontent.com/2841473/89921645-8ec46d00-dc30-11ea-8779-933052c7bacb.png)

**Comment by xaleeks** [comment]
@a-mccarthy please make sure to add a note that there's a default 7-day retention policy created for each project, I don't think this was in prd anywhere

**Comment by stonezdj** [comment]
Documented in https://github.com/goharbor/website/pull/95
