### ISSUE TITLE
[p2p] inconsistency in workflow

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12758]
1. The healthy icon is not consistent with that from registry endpoints:
<img width="1385" alt="Screen Shot 2020-08-13 at 12 19 04 AM" src="https://user-images.githubusercontent.com/2390463/90040534-a36d3780-dcfa-11ea-97a6-149f91685d85.png">
2. The replication has the enablement on policy level but the p2p preheat has the enablement at both target and policy level.

3.In replication the enablement is done via "Edit" the policy, but in p2p preheat the enablement is provided as a separate button, any particular benefit for introducing this change?

**Comment by steven-zou** [comment]
@AllForNothing let's update the health status column of registry management view to a similar style to scanner management and p2p preheat provider management view.

**Comment by steven-zou** [comment]
>3.In replication the enablement is done via "Edit" the policy, but in p2p preheat the enablement is provided as a separate button, any particular benefit for introducing this change?

Using a separate button to trigger the action of `enable`/`disable` policy is more convenient as it's just a single action. That action does not need to open the edit dialog and can be directly applied to the selected policy and also this action does not need any inputs.

New issue to improve the UE of replication part later: https://github.com/goharbor/harbor/issues/12780

**Comment by steven-zou** [comment]
>2. The replication has the enablement on policy level but the p2p preheat has the enablement at both target and policy level.

I think the root cause is because the P2P providers are managed under the system admin view and the policies are managed under the project level. They have different requirements.

But the replication and its relying-on registries are all managed under system level, the scenarios are a little different.

For this item, we'll do nothing and just keep as it is now.

cc @AllForNothing @reasonerjt
