### ISSUE TITLE
[p2p]The instance information pane can be misleading

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12759]
1) When I chookse "kraken" it says the maintainer is mmpei and the repo is uber/kraken.  But mmpei is not really a maintainer of kraken?

<img width="528" alt="Screen Shot 2020-08-13 at 12 29 39 AM" src="https://user-images.githubusercontent.com/2390463/90042033-b84aca80-dcfc-11ea-8214-209c7d458304.png">

2) The version is misleading the UI says the version of kraken is "0.1.3".  Is it determined by the instance or hard coded?  I set it to an invalid endpoint for dragonfly but the version is still there .

<img width="516" alt="Screen Shot 2020-08-13 at 12 29 59 AM" src="https://user-images.githubusercontent.com/2390463/90042003-a9fcae80-dcfc-11ea-9334-63a1c863a12d.png">

**Comment by steven-zou** [comment]
Let's change the name from project names to drivers: `Kraken Driver` and `Dragonfly Driver`.

**Comment by steven-zou** [comment]
All the versions here are Preheat driver versions.
And we also need to add P2P provider versions here.

**Comment by reasonerjt** [comment]
in v2.1 let's remove this tooltip to avoid confusion.
