### ISSUE TITLE
[p2p]:Issue in dialogs and tables when using the P2P preheat feature.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#12757]
1. The tooltip is incorrect
Looks like it's copied from the dialog to create replication endpoint?
2. the provider type is not editable once the instance is saved.
<img width="1183" alt="Screen Shot 2020-08-13 at 12 07 08 AM" src="https://user-images.githubusercontent.com/2390463/90039245-f645ef80-dcf8-11ea-8bd6-eca24059f251.png">
3. The token string should be marked as `***` instead of showing the plain text:

<img width="837" alt="Screen Shot 2020-08-13 at 12 13 28 AM" src="https://user-images.githubusercontent.com/2390463/90039901-dcf17300-dcf9-11ea-8089-5d6e50a2df63.png">

**Comment by reasonerjt** [comment]
Not a issue in the dialg but I see the overlap in the list:

<img width="1033" alt="Screen Shot 2020-08-13 at 12 36 17 AM" src="https://user-images.githubusercontent.com/2390463/90042295-15df1700-dcfd-11ea-9bd0-760e3fb2fecc.png">

**Comment by reasonerjt** [comment]
Also the `description` should be `Description` in the header of the table, 
and the enablement is text, instead of icon in other tables  <--  another inconsistency.

**Comment by reasonerjt** [comment]
Another thing I wanna mention is in the policy dialg ,the text layout of `Criteria` is not quite aligned I feel.
Additionally the checkbox of `Only signed image` remain unchecked even it's set to true in the project configuration tab.

<img width="690" alt="Screen Shot 2020-08-13 at 2 29 41 PM" src="https://user-images.githubusercontent.com/2390463/90101692-c5ee6780-dd71-11ea-872e-4d785407ca27.png">

**Comment by reasonerjt** [comment]
Why the tooltip icons of `Criteria` and `Trigger` placed differently?

**Comment by AllForNothing** [comment]
> Why the tooltip icons of `Criteria` and `Trigger` placed differently?

tooltip  is for "Event based", not for "Trigger"
