### ISSUE TITLE
Docker image can not be pushed

### ISSUE THREAD

**Issue by softshipper** [goharbor/harbor#12754]
Hi all 

I have a problem with pushing images to the harbor docker registry. The pod hub-harbor-core shows:

![Screenshot from 2020-08-12 14-31-06](https://user-images.githubusercontent.com/56756949/90015550-0cc45a80-dca9-11ea-864d-c9d0c97589b4.png)

As you can see on the picture, I have got internal service error.   

What is wrong with my harbor?  

Thanks

**Comment by ywk253100** [comment]
Cannot get the error detail from your screenshot
