### ISSUE TITLE
Why is copy pull followed by hash, instead of tag??

### ISSUE THREAD

**Issue by zxiaozhou** [goharbor/harbor#12763]
**Steps to reproduce the problem:**
Why is copy pull followed by hash, instead of tag??
I think 90% of people want to use tag for copy pull (just like DockerHub).
Isn't this design anti-human??Show the one you don't need and hide the one you really need. You want to torture the user！！！！

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.2
- docker engine version: 19.03.12
- docker-compose version: 1.26.2

**Comment by ywk253100** [comment]
The pull command with tag is already merged into master branch and will be available in 2.1. You can enter the tag list page and get it.

**Comment by zxiaozhou** [comment]
@ywk253100 Why is copy pull followed by hash, instead of tag?? in v21.0

**Comment by itdoginfo** [comment]
> The pull command with tag is already merged into master branch and will be available in 2.1. You can enter the tag list page and get it.

@ywk253100 please tell me where can I find it? Pull button gives SHA256. I am using version 2.2.3. 
![Screenshot from 2021-07-07 15-50-11](https://user-images.githubusercontent.com/11143109/124762130-3b8b9500-df3b-11eb-8286-f92b3fe51370.png)

**Comment by k4nzdroid** [comment]
> > The pull command with tag is already merged into master branch and will be available in 2.1. You can enter the tag list page and get it.
> 
> @ywk253100 please tell me where can I find it? Pull button gives SHA256. I am using version 2.2.3.
> ![Screenshot from 2021-07-07 15-50-11](https://user-images.githubusercontent.com/11143109/124762130-3b8b9500-df3b-11eb-8286-f92b3fe51370.png)

@itdoginfo My version is 2.3.0. After click the `sha256:3445d4ac`, a new page is shown up...

![image](https://user-images.githubusercontent.com/40691275/126492957-9d79acfb-cdce-49be-9d5e-b9df0fa1690d.png)
