### ISSUE TITLE
upgrade deployment document about some questions

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#12784]
hello!
I see the deployment doc about helm upgrade  in the https://goharbor.io/docs/2.0.0/administration/upgrade/helm-upgrade/ ,but at the end of the page found this:
-------------------
The job logs will be lost if you upgrade from version 0.3.0 as the logs are store in a emptyDir in 0.3.0.
-------------------
Can you tell me about this version 0.3.0 what does it mean? what's version?

**Comment by ywk253100** [comment]
It's the version of harbor helm chart

**Comment by minxiaogang** [comment]
but 'helm search harbor': i see harbor chart version is 1.4.2 and app verison is 2.0.2. i can't found 0.3.0 this version?
