### ISSUE TITLE
upgrade doc: upgrade to 2.0.1 must go through 1.9

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor#12781]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The upgrade document would not miss important steps.
If upgrades must go through certain versions, the upgrade document for goharbor as well as harbor helm-chart should both reference this information.

**Steps to reproduce the problem:**
helm upgrade harbor/harbor --version harbor-1.4.1 ...

**Versions:**
chart harbor v1.1.3 app (harbor) v1.8.3

- harbor version: [1.8.3]
- docker engine version: [n/a]
- docker-compose version: [n/a]

**Additional context:**
We ended up have to 
- helm delete the harbor installation
- restore the data, helm install the old version, chart harbor-1.1.3/app 1.8.3
- helm upgrade to chart harbor-1.2.3/app 1.9.3 before finally
- helm upgrade to chart harbor-1.4.1/app 2.0.1

- **Harbor config files:** n/a
- **Log files:** The last log line of core after upgrading from 1.8.3 directly to 2.0.1:
```2020-08-15T19:52:49Z [FATAL] [/core/main.go:123]: failed to migrate: please upgrade to version 1.9 first```

**Comment by reasonerjt** [comment]
Fixed in https://github.com/goharbor/website/pull/104
