### ISSUE TITLE
can't do regular login to harbor when oidc client active

### ISSUE THREAD

**Issue by Morriz** [goharbor/harbor#12782]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I would expect to be able to login from the presented login screen with the form's input, but instead I get logged in with the previously used oidc login.

**Steps to reproduce the problem:**
login once using the oidcc client, then try to login with the form

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.0.0-87602132
- k8s: 1.16

**Additional context:**

installed using helm chart:
- version: 1.4.0
- appVersion: 2.0.0

**Comment by reasonerjt** [comment]
Please elaborate 
```
I would expect to be able to login from the presented login screen with the form's input, but instead I get logged in with the previously used oidc login.
```

When you set Harbor to use OIDC auth, you have to be redirected to the OIDC provider for login.

**Comment by Morriz** [comment]
> When you set Harbor to use OIDC auth, you have to be redirected to the OIDC provider for login.

That assumption is imo not correct (nor UX friendly). I still expect the initial login method to stay in function, in case oidc does not work.

Why show the login box (username+password) with submit button and then not handling the input correctly?

**Comment by Morriz** [comment]
bumping this

**Comment by reasonerjt** [comment]
Morriz, currently Harbor does not support multiple auth backend at the same time.

The login dialog still appears for the internal admin user (the only one) to login.  

I agree UX wise this is not friendly but function-wise this is the design right now.

**Comment by Morriz** [comment]
Alright. Tnx. If we do a full sign out with the IDP the admin login becomes active again until an OIDC session takes over. Will do with some explanation towards our users for now.

**Comment by Morriz** [comment]
bumping as this still needs rework in the UI
