### ISSUE TITLE
Support chart replication to AWS ECR

### ISSUE THREAD

**Issue by matt-demers** [goharbor/harbor#12794]
Amazon released support for alternate media types in ECR manifests. They can support storing helm charts as OCI images.
See: https://github.com/aws/containers-roadmap/issues/308#issuecomment-675027095

I would like to be create replication rules for syncing charts between Harbor and ECR

Currently if I try to create a replication rule to push charts from Harbor to ECR, it gives the error 
```
failed to create client for destination registry: the adapter doesn't implement the "ChartRegistry" interface
```

**Comment by ywk253100** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/5835782/90585411-6081f700-e207-11ea-8c9f-f549211d49b8.png">

When you creating the replication rule, set the `Resource` filter as `artifact` and try again.
The `chart(chartmuseum)` only filters the charts stored in chart museum which aren't in OCI format

**Comment by matt-demers** [comment]
Thanks, that did work

**Comment by vikramvicky61** [comment]
I tried with the artifact in the resource block but still got the same error. It only tries to replicate the Images, not the helm charts. Below are logs of the replication when resource as charts.

2022-04-27T05:22:45Z [INFO] [/controller/replication/transfer/chart/transfer.go:92]: client for source registry [type: harbor, URL: http://harbor-core:80, insecure: true] created
2022-04-27T05:22:45Z [ERROR] [/controller/replication/transfer/chart/transfer.go:98]: failed to create client for destination registry: the adapter doesn't implement the "ChartRegistry" interface

Can someone help with this, please?
