### ISSUE TITLE
replicate the image folder is missed when specify “destination namespace”

### ISSUE THREAD

**Issue by WenwuPeng** [goharbor/harbor#12791]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We found the image tree/folder will be broken when  Harbor replicate image with difference “destination namespace”. E.g
Harbor A  test-paas ->  replicate  to Harbor B  test,  the image In Harbor A  test-paas/jetstack/cert-manager-controller. ->  test/cert-manager-controller , and the folder “jetstack” is missed.
 
In Harbor A have same image with difference folder. It is count as 2 in Harbor A:
test-paas/jetstack/cert-manager-controller
test-paas/ cert-manager-controller
 
After replicate to Harbor B. It will be one image test/cert-manager-controller, it is count as 1.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
The sector `jetstack` was removed b/c for some target registry the namespace has to be one-level?
For different target registries, we may consider retaining the sector?

**Comment by xaleeks** [comment]
but he's going from harbor to harbor, same versions I'm assuming?

**Comment by reasonerjt** [comment]
@bitsf This can be fixed along with the enhancement for harbor <-> harbor replication?

**Comment by bitsf** [comment]
We consider to add an option `keep structure` in replication rule, that indicate this rule will auto keep the namespace part when replication.
This option should be shown based on different adapter, such as dockerhub doesn't support multi-level namespace

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/13549
