### ISSUE TITLE
Add audit logs persistent stored on disk drive

### ISSUE THREAD

**Issue by jaminlai** [goharbor/harbor#128]
Expected the harbor audit logs persistent stored not only on the db but also on the disk drive, which can be transported to the audit system and analysed in company.

In addition, if the audit log files with rollingpolicy and be mounted to the identify machine path would be better and better.

Thanks

**Comment by reasonerjt** [comment]
We would add a configurable "audit handler", such that it's extensible and audit logs can be persisted to DB or FS or any other endpoint.

**Comment by reasonerjt** [comment]
We do have plan to refactor this part, marked as a backlog item.
