### ISSUE TITLE
cant login using robot account in high-availability mode

### ISSUE THREAD

**Issue by kuznetsovkk** [goharbor/harbor#12806]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

If I create robot-account at node1, I can see in at both nodes (using web ui), but I can't login with its token at node2: 

Expected behavior:
docker login node1
Login Succeeded

docker login node2
Login Succeeded

Actual behavior:
docker login node1
Login Succeeded

docker login node2
Error response from daemon: Get https://harbor.local/v2/: unauthorized: authentication required

and vice versa: cant login to node1 using robot-account created at node2

**Steps to reproduce the problem:**

Im trying to install harbor in a high availability mode with shared storage (minio), shared database (postgresql) and shared redis.
Just 2 rhel7-vms (not kubernetes, not ocp) with a harbor running on each of it.
Harbor-versions (and other packages) are the same on each VM.

**Versions:**

- harbor versions: 2.0.1, 2.0.2, 2.1-tech-preview
- docker engine version: 1.13.1, build 64e9980/1.13.1
- docker-compose version: 1.18.0, build 8dd22a9

I have to disable check_docker function in install.sh script to install harbor with docker-1.13.1:
...
\# check_docker
...

**Comment by ywk253100** [comment]
There is a cert/key pair used to generated the robot account token, you need to make sure it is shared between the two nodes.
@wy65701436 Could you point out where the key pair is located?

**Comment by kuznetsovkk** [comment]
thank you for help!
data_volume:/secret/core/private_key.pem should be the same on all nodes
this needs to be added to the documentation, I think
