### ISSUE TITLE
 How to add Annotations to a Repositories in Harbor 2.0.2 ?

### ISSUE THREAD

**Issue by wangyu8460958** [goharbor/harbor#12824]
Now I have a project  name  "google_containers"  in  Harbor 2.0.2 ,  the  "google_containers"  project  contain a  repositories  name  "spartakus-amd64"  .  Now  I want to  add  Annotations to  "spartakus-amd64" .  

How to add Annotations to "spartakus-amd64" ？

Can Annotations be added to the command "docker push" when using the "docker push" command to push a repository to Harbor?

**Comment by ywk253100** [comment]
AFAIK, the annotations cannot be added to the repository
