### ISSUE TITLE
Repository never loads data

### ISSUE THREAD

**Issue by xxwassyxx** [goharbor/harbor#12820]
**Expected behavior and actual behavior:**
https://harborurl/harbor/projects/2/repositories
clicking the link to load a repository loads the images in that repository.
Actual behaviour is that the loading spinner just spins forever and never loads the data

**Steps to reproduce the problem:**
I

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.4]
- crio engine version: [1.13.0]

**Additional context:**
What I noticed is that looking in developer tools the data does indeed appear to load up. I can see the request out
https://harborurl/api/repositories?page=1&page_size=15&project_id=2
and after say 9s there is a response json with all the data I would expect on the page.
Whats interesting is looking at the registry container I see the requests asking for all the tags, no errors
If I hit the refresh button on the top right of the harbor page I can see the data in the background like a ghost image of it, but the spinner still spinning.
This only appears to happen with one repository.
I have another repository with fewer images and it loads just fine.
There are 17 images in this particular repository and only 3 in the other.
Every other link works on the projects page.
I have tested this on firefox, chrome and safari with all the same results
Looking in the portal container I don't see any errors, neither do I see any errors in core. Any help would be great. Again this is purely an ui issue. Pushing and pulling images works just fine.

**Comment by ywk253100** [comment]
@AllForNothing Please take a look

**Comment by AllForNothing** [comment]
@xxwassyxx any errors in developer tool console tab ?

**Comment by xxwassyxx** [comment]
No, tomorrow ill post a few screenshots to give you a picture of what im seeing if that will help

**Comment by AllForNothing** [comment]
> No, tomorrow ill post a few screenshots to give you a picture of what im seeing if that will help

Thanks! That will be helpful.
