### ISSUE TITLE
Cannot replicate to harbor in Azure

### ISSUE THREAD

**Issue by ajchiarello** [goharbor/harbor#12838]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: replication between harbor installations to work
Actual: I get an error "failed to check the existence of blob sha256:d6ff36c9ec4822c9ff8953560f7ba41653b348a9c1136755e653575f58fbded7 on the destination registry: http status code: 500, body:" on all replicated images.

**Steps to reproduce the problem:**
Install a kubernetes cluster in Azure (not AKS), using Azure file storage for the persistent data, and install harbor via helm with an nginx ingress controller. Attempt to replicate or push to the new installation (both fail).

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.2
- docker engine version: 19.3.12
- kubernetes version: 1.18.6

**Comment by ywk253100** [comment]
Could you provide logs when you pushing to the instance?

**Comment by ajchiarello** [comment]
Logs attached.
[core.log](https://github.com/goharbor/harbor/files/5120288/core.log)
[jobservice.log](https://github.com/goharbor/harbor/files/5120289/jobservice.log)
[portal.log](https://github.com/goharbor/harbor/files/5120290/portal.log)
[registry.log](https://github.com/goharbor/harbor/files/5120291/registry.log)
