### ISSUE TITLE
Image not reflecting in harbour console UI

### ISSUE THREAD

**Issue by leeadh** [goharbor/harbor#12833]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I am working with vSphere 7 with Kubernetes and there is an integrated harbour. 

An issue I encountered was that when  I  tried to push an image  (i.e  tag=;latest) it isnt appearing in the UI. When  i retagged the image  (tag = v1) and pushed then both images  appeared  in the UI.  Hence, a question is why  is the image with tag latest didnt appear for the first  time but when he pushed a subsequent image with a new tag it was pushed in. 

**Steps to reproduce the problem:**
hen  i retagged the image  (tag = v1) and pushed then both images  appeared  in the UI.  Hence, a question is why  is the image with tag latest didnt appear for the first  time but when he pushed a subsequent image with a new tag it was pushed in. 

![image](https://user-images.githubusercontent.com/15122358/91141696-92e99380-e6e2-11ea-9b5a-d9eaeb069ec9.png)

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.x]
- docker engine version: []
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ywk253100** [comment]
Could you provide some logs?

**Comment by reasonerjt** [comment]
@leeadh 
This may happen if you are using v1.x due to the reliability of reigstry's notification mechanism.
