### ISSUE TITLE
[p2p] the error message of disabling a referenced instance is not readable

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12842]
![image](https://user-images.githubusercontent.com/2841473/90851087-416d9b80-e3a6-11ea-89c8-412457a0b5e2.png)

**Comment by steven-zou** [comment]
@AllForNothing Is the message returned from the backend?

If it is, maybe @kofj can help to fix.

**Comment by steven-zou** [comment]
`Provider [name] cannot be disabled as some preheat policies are using it.`

**Comment by steven-zou** [comment]
@AllForNothing 

It's your turn to update the UI part as backend service has been fixed

**Comment by AllForNothing** [comment]
Not need to change UI
