### ISSUE TITLE
[p2p] the provider should not be able to updated

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12844]
I can update the provider of a p2p instance, but it may cause some unknown issue as it may already referenced by some projects.  

![image](https://user-images.githubusercontent.com/2841473/90851574-bdb4ae80-e3a7-11ea-9450-aba7aacf92f9.png)

**Comment by steven-zou** [comment]
Updare is ok. 

The policy uses the id to refer to the provider. When evaluating p2p preheat policy, the provider instance is retrieved by the id. The instance info will be always the latest.
