### ISSUE TITLE
[p2p] Get internal error when to trigger a provider updated preheat policy

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12843]
1, add a kraken instance
2, add a kranken policy in project library
3, update the instance provider to dragonfly.
4, execute the policy in project library.

Got
![image](https://user-images.githubusercontent.com/2841473/90851329-ee481880-e3a6-11ea-9e9b-54d10127aa98.png)

But, I see 404 in the log,

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/2841473/90851259-b9d45c80-e3a6-11ea-85bb-82563d8004cc.png">

**Comment by steven-zou** [comment]
I think the root cause is the provider driver is not updated.
