### ISSUE TITLE
We can save a proxy cache project without setting a registry

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12852]
build: 3833
We can save a proxy cache project without setting a registry. UI and api should block this with error.
![image](https://user-images.githubusercontent.com/188115/90957731-3c9e0a00-e4c2-11ea-83f8-f36ae31ef9c9.png)
![image](https://user-images.githubusercontent.com/188115/90957742-56d7e800-e4c2-11ea-90dd-7b52410a1df7.png)
![image](https://user-images.githubusercontent.com/188115/90957749-60f9e680-e4c2-11ea-8db4-f0d5b4194e78.png)

**Comment by AllForNothing** [comment]
duplicated with #12846
