### ISSUE TITLE
harbor v1.9.4 replication issues 

### ISSUE THREAD

**Issue by tdk-github** [goharbor/harbor#12854]
Have several replication rules created, when I try to manually replicate any of them I have been recently getting
the following : 
 chartmuseum.log : 
L:ERROR,T,M:Request served, clientIP:XXXXX,method:GET,statusCode: 401

core.log : 
...
GET /api/labels r:/api/labels#033
ERROR [/core/api/project.go:452] pupulate project properties failed get chart count of project 14 failed: http error: code 401, message unathorized
GET /api/projects r:/api/projects/#033
...
ERROR : populate project properties failed get chart count of project 14 failed: http error: code 401, message unauthorized
ERROR: fail to list charts: http error: code 401, message unauthorized
ERROR: GET /api/chartrepo/ibm/charts failed with error: {"code":401,"message":"unauthorized"}

This had been working for all the replication rules. Recently someone did a "./prepare" w/out clair and chartmuseum so
those images/containers had not been running until today. Today, those containers are now running but the replications
are still failing.

Thanks -

**Comment by ywk253100** [comment]
Seems that some configuration doesn't match between the components, suggest to re-install all of them or replicating only images by editting the replication rules
