### ISSUE TITLE
Harbor (1.9.4) replication issues w/ chartmuseum

### ISSUE THREAD

**Issue by tdk-github** [goharbor/harbor#12869]
Have several replication rules created, When I try to manually replicate any of them I have been recently getting
the following :

chartmuseum.log :
L:ERROR,T,M:Request served, clientIP:XXXXX,method:GET,statusCode: 401

core.log :
...
GET /api/labels r:/api/labels#033
ERROR [/core/api/project.go:452] pupulate project properties failed get chart count of project 14 failed: http error: code 401, message unathorized
GET /api/projects r:/api/projects/#33
...
ERROR : populate project properties failed get chart count of project 14 failed: http error: code 401, message unauthorized
ERROR: fail to list charts: http error: code 401, message unauthorized
ERROR: GET /api/chartrepo/ibm/charts failed with error: {"code":401,"message":"unauthorized"}

This had been working for all the replication rules. Recently someone did a "./prepare" w/out clair and chartmuseum so
those images/containers had not been running until today. Today, those containers are now running but the replications
are still failing.

Is there a way to update what projects chartmuseum thinks are avail? That seems to be the issue. New projects were
created whilst chartmuseum was 'offline'. Now chartmuseum is back online and probably doesnt have a current view of
all the projects.

Thanks -

**Versions:**

- harbor version: 1.9.4
- docker engine version: 18.09.5-3
- docker-compose version: 1.18.0-4

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/12854?

**Comment by bitsf** [comment]
@tdk-github you can check BASIC_AUTH_PASS in `harbor/common/config/chartserver/env` and CORE_SECRET in `harbor/common/config/core/env`, they should be same, and restart harbor
