### ISSUE TITLE
harbor V2.0.2 quota limit

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#12876]
I (admin) created an project and limited the quota and assigned users,  But when ordinary users log in to this project, they can build projects themselves. How can the quota be limited?

**Comment by Ahmadabed83** [comment]
From the UI:
Administration --> Configuration --> System Settings tab --> change "Project Creation" to "Admins Only" instead of default "Everyone"

This will prevent non-admins from creating projects

**Comment by minxiaogang** [comment]
thanks, 
---------------------------------
https://harbor.com/api/v2.0/quotas/14
404: Quota ID does not exist.
-------------------------------
14 is the project ID.  this Quota ID is not project ID? what is ?

**Comment by minxiaogang** [comment]
{
  "hard": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  }
}
but i see the web post --{"hard":{"storage":53687091200}}---- this 
what is use in API? and additionalProp1 this how to use?

**Comment by heww** [comment]
Quota ID is not the project id.

```
{
"hard": {
"additionalProp1": 0,
"additionalProp2": 0,
"additionalProp3": 0
}
}
```
This is the definition of a map in swagger which means "additionalProp1", "additionalProp2" is not the real key of the map, it depends on the API server.

**Comment by minxiaogang** [comment]
I get the following results by using API"/quotas"（ #list quotas）
API: https://harbor.com/api/v2.0/quotas  
result:
--------------------
[
  {
    "id": 14,
    "ref": {
      "id": 14,
      "name": "test",
      "owner_name": "testuser"
    },
    "creation_time": "2020-08-26T18:44:38.805202+08:00",
    "update_time": "2020-08-26T18:44:38.805202+08:00",
    "hard": {
      "storage": 53687091200
    },
    "used": {
      "storage": 0
    }
  },
........]
-----------------------------
whict id is the quota id? and  this project id is 14.  I don't quite understand this.

**Comment by heww** [comment]
A quota is a resource in the harbor. It is not just designed for the project. 

We can also have system-level storage limitations. 

So the `id` is the identity for quota itself, and `ref` is the object quota limited on.
