### ISSUE TITLE
Need refactor replication registry client and http client

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12882]
Currently http client is wrapped in the registry client, that makes the fix like PR https://github.com/goharbor/harbor/pull/12819 hard to call the http client, so I export the method Do() in the PR, and change the interface.
This fix is simple but not grace, the interface seems confusing.
It might be better to separate the http client, and inject to the replication adapters, that can make the override method in adapters easily use it.

**Comment by reasonerjt** [comment]
Per discussion with @ywk253100 this should be handled in the gcr adapter.
