### ISSUE TITLE
maintain nested structure when replicating artifacts

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [goharbor/harbor#12890]
**Expected behavior and actual behavior:**
If I have a project with a nested folder structure (e.g. `my-project/foo/bar`) and I replicate the contents of that project, I would like the structure to be preserved (e.g. `new-project/foo/bar`). 

Actual behaviour:
The directories are discarded, and the result is `new-project/bar`)

**Steps to reproduce the problem:**
Create a project (eg `my-project`)
Push an artifact with multiple path separators (`my-project/foo/bar/bizz`)
Create a destination project (`new-project`)
Create a replication rule
- source `my-project/**`
- destination `new-project`
- source registry = dest registry

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.1]

**Comment by stonezdj** [comment]
We might have discuss it in #12791

**Comment by bitsf** [comment]
@xtreme-conor-nosal  You can try keep the destination field as empty, which will use the src namespace

**Comment by xtreme-conor-nosal** [comment]
@bitsf we needed to replicate within one registry (in this case trying to effectively rename a project), so we couldn't use a blank destination namespace.

**Comment by bitsf** [comment]
Unfortunately, we don't support replicate sub namespace when specify the destination now, it was designed as this before.
We're trying to support this, but there're still some problems we not sure how to resolve, like how to upgrade from old version, how to deal with registry which does not support multi namespaces, which sub namespaces should be copy from.

**Comment by junaid18183** [comment]
This creates serious issues when replicating from other repositories like Jfrog.

**Comment by xtreme-conor-nosal** [comment]
Replication endpoints already require a `Provider` to be selected - this could be limited to harbor<->harbor replications.

An alternative (for our specific use case) would be the ability to rename projects but it seems that's blocked by docker distribution https://github.com/goharbor/harbor/issues/858

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/13549
