### ISSUE TITLE
Distribution can't be deleted if the related project was deleted instead of deleting p2p prehead policy first

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#12891]
**Test Step:**
  1. Add a new distribution;
  2. Add a new project and add a new p2p preheat policy ror this project, policy referenced the new distribution;
  3. Delete this new project;

**Expectation Behavior and Actual Behavior:**
  distribution should be deleted successfully, but it's not actrually.

![image](https://user-images.githubusercontent.com/44018302/91376327-6901af80-e84f-11ea-956c-efbc37cb3b2e.png)

**Comment by steven-zou** [comment]
@danfengliu 

It's by design. If some preheat policies have used the provider. It cannot be deleted. To delete it, you need to clean all the related preheat policies first.

**Comment by danfengliu** [comment]
Project deletion should be including P2P preheat policy deletion, so distribution can be deleted.
