### ISSUE TITLE
Failed to cache image occasionally

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#12900]
Image cache failed occasionally, although image was pulled successfully, but image was not cached in proxy cache project.

![image](https://user-images.githubusercontent.com/44018302/91529663-41d4dc00-e93c-11ea-8afe-56a51c09f2cb.png)

![image](https://user-images.githubusercontent.com/44018302/91529690-50bb8e80-e93c-11ea-809e-8802a8bfcec0.png)

### Harbor Log:

Aug 27 19:30:54 172.23.0.1 core[5615]: 2020-08-27T19:30:54Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:66c8388f5e806aa88c2fe900e6ce19fbc736065f7d12388ec57f03a79d57ea8d
Aug 27 19:30:54 172.23.0.1 core[5615]: 2020-08-27T19:30:54Z [DEBUG] [/server/middleware/security/proxy_cache_secret.go:40][requestID="6289a58b-c3e4-4409-a63f-e1c10c50c4ad"]: a proxy cache secret security context generated for request HEAD /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:66c8388f5e806aa88c2fe900e6ce19fbc736065f7d12388ec57f03a79d57ea8d
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/local.go:200]: checking the blob dependency: sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id ed22f073-f2a1-4283-81fd-aa1a24d730b1 to the logger for the request HEAD /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/security/proxy_cache_secret.go:40][requestID="ed22f073-f2a1-4283-81fd-aa1a24d730b1"]: a proxy cache secret security context generated for request HEAD /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/local.go:204]: Check dependency failed!
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/local.go:200]: checking the blob dependency: sha256:dad1aefe4fab1ca95f2fc58acb55fa218d26fbd17eebf2387b9e5d88b51c9682
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id ff67505e-cba7-4cab-ae5a-25833be149c0 to the logger for the request HEAD /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:dad1aefe4fab1ca95f2fc58acb55fa218d26fbd17eebf2387b9e5d88b51c9682
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:dad1aefe4fab1ca95f2fc58acb55fa218d26fbd17eebf2387b9e5d88b51c9682
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/server/middleware/security/proxy_cache_secret.go:40][requestID="ff67505e-cba7-4cab-ae5a-25833be149c0"]: a proxy cache secret security context generated for request HEAD /v2/project081598556397/danfengliu/for_proxy/blobs/sha256:dad1aefe4fab1ca95f2fc58acb55fa218d26fbd17eebf2387b9e5d88b51c9682
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/local.go:208]: Check dependency result [{application/vnd.docker.image.rootfs.diff.tar.gzip 763789 sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb [] map[] <nil>}]
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/controller.go:203]: Current n=9 artifact: project081598556397/danfengliu/for_proxy:1.0
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/controller.go:210]: Waiting blobs not empty, push it to local repo directly
Aug 27 19:30:55 172.23.0.1 core[5615]: 2020-08-27T19:30:55Z [DEBUG] [/controller/proxy/controller.go:177]: Put blob to local registry!, sourceRepo:danfengliu/for_proxy, localRepo:project081598556397/danfengliu/for_proxy, digest: sha256:61c5ed1cbdf8e801f3b73d906c61261ad916b2532d6756e7c4fbcacb975299fb
**Aug 27 19:30:57 172.23.0.1 core[5615]: 2020-08-27T19:30:57Z [ERROR] [/controller/proxy/controller.go:180]: failed to create blob reader, error http status code: 429, body: Too Many Requests (HAP429).
Aug 27 19:30:57 172.23.0.1 core[5615]: 2020-08-27T19:30:57Z [ERROR] [/controller/proxy/controller.go:214]: Failed to push blob to local repo, error: http status code: 429, body: Too Many Requests (HAP429).**
Aug 27 19:31:25 172.23.0.1 core[5615]: 2020-08-27T19:31:25Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 302e1021-7be7-46c5-9824-42481b2e6666 to the logger for the request GET /api/v2.0/ping

**Comment by reasonerjt** [comment]
This is due to docker hub throttling, how about register an account for our nightly? so this particular account will not reach the limit that easiliy.

**Comment by danfengliu** [comment]
Right, it's better to find a way to a void the influence by docker hub throttling.

**Comment by danfengliu** [comment]
@reasonerjt  Currently proxy cache test is already using  a particular account in docker hub.
