### ISSUE TITLE
Broken authentication (OIDC ): it was possible to re-initiate the last session that was used on the browser even after logout. 

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#12905]
**Expected behavior and actual behavior:**
it was possible to re-initiate the last session that was used on the browser even after logout.  

expected : after user logout, need clean all session information on the browser. 

**Steps to reproduce the problem:**
1) user uses a public computer to log into Harbor application as a Project Admin. (OIDC enabled only)
2) user logs out of the application and closes the browser.
3) anthoer user uses the same public computer and visits the application with the same browser.
4) anthoer user inputs any not exist username and password and logs in. The application will redirect the user to https://harbor.xxxxxxx/c/oidc/login.
5) anthoer user is successfully logged into the first user's previous session and has full control over his account.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.1 (Helm install 1.4.1)

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by promasu** [comment]
I guess its more feature than bug as it looks like the session with the oidc provider is still valid. You need to logout there and not only at Harbor for not being able to log right back in.
I think Harbor redirects you to the authentication endpoint of the oidc if the normal user credential login fails

**Comment by cafeliker** [comment]
It means the logout doesn't work, it's a critical cyber security issue than a feature request.

**Comment by steven-zou** [comment]
Is it the same as this one? https://github.com/goharbor/harbor/issues/12634

**Comment by cafeliker** [comment]
Yes, I think so, @reasonerjt  Daniel, could you pls help look at this issue with priority? The issue was detected by our security security and blocked the production deployment for us.

**Comment by reasonerjt** [comment]
@cafeliker what makes you think it's security issue?

so far, by design it is the user's responsibility to logout from the 3rd party endpoint, it is not rare in enterprise env.  

It may be problematic to logout the SSO endpoint if you logout Harbor because other application also depends on the session in SSO service.

**Comment by cafeliker** [comment]
We are going to make Harbor as an internet facing service, and think about the use-case below. It a big security leak for a public application.

1. User uses a public computer to log into Harbor application as a Project Admin. (OIDC enabled only)
2. User logs out of the application and closes the browser.
3. Another unexpected user uses the same public computer and visits the application with the same browser.
4. Another unexpected user inputs any not exist username and password and logs in. The application will redirect the user to https://harbor.xxxxxxx/c/oidc/login.
5. Another unexpected user successfully logged into the first user's previous session and had full control over his account.

**Comment by cafeliker** [comment]
If users want to take the advantage of SSO, they should not click logout; otherwise, logout does mean nothing.

**Comment by reasonerjt** [comment]
@cafeliker 
I don't think this is how things work currently.  Logout should only log him out from the current application he's using, not other applications.

One way to mitigate it I can think of is not to redirect the user to `oidc/login` after he clicks the login button.  But I don't think it's right to logout from the external service.

**Comment by cafeliker** [comment]
@reasonerjt I can understand what you are saying, but it will not have any OIDC logout opportunity until timeout, it's not exactly logout means. Again, I am talking about when Harbor is an internet facing application, not running after the company firewall; for us, it's a critical cyber security issue raised by our cyber security team.

Maybe you can offer a configuration item to enable/disable SSO logout, but we definitely need a SSO logout when user clicks the logout button otherwise cyber security will not allow us to move Harbor to production. 

Do you mind to share me how to make it? Where are the codes control the Harbor logout activity?

**Comment by reasonerjt** [comment]
@cafeliker 
Providing a universal logging out mechanism for OIDC can be complicated.  There are several options that are in `draft` status, and I'm not very sure which vendor support any of them:
https://openid.net/specs/openid-connect-session-1_0.html
https://openid.net/specs/openid-connect-frontchannel-1_0.html
https://openid.net/specs/openid-connect-backchannel-1_0.html

So I wish to suggest we refrain from providing a `global logout` feature on Harbor side.

As for your case, if it's a show stopper, you can fork Harbor's code and add a snippet of code to access your OIDC provider's logout URI when user sends logout request to Harbor:
https://github.com/goharbor/harbor/blob/master/src/core/controllers/base.go#L120

But that can be considered a CSRF attack by some security reviewer, and please keep it on your fork currently.

I'm not convinced that an internet facing app should support global logout, not supporting it doesn't add to attack surface.  I randomly checked a internet app: https://soundcloud.com
When you choose login via google and logout, it does not log you out from google

**Comment by cafeliker** [comment]
@reasonerjt I am not sure if VMWare uses Office 365 or Worday, and you could see both of them would trigger SSO logout when the user clicks the sign-out button.

I looked at https://github.com/goharbor/harbor/blob/master/src/core/controllers/base.go#L120 and it called the Beego DestroySession() method, and this method would only clean the sessions in Harbor server side; and could you pls help guide me how to insert some codes to delete all cookies under the habor domain? Let's see if we can make it after cleanup all cookies at client side.

**Comment by bitsf** [comment]
This issue should also be similar with my old stale issue https://github.com/goharbor/harbor/issues/9941

**Comment by cafeliker** [comment]
@bitsf how you handle this issue today?

**Comment by reasonerjt** [comment]
@cafeliker I tried workday in my intranet, and it DID NOT require re-login.

I clicked "sign out" button in workday, input the URL of workday's home page, and I could continue using it without having to input my credentials again...

**Comment by cafeliker** [comment]
@reasonerjt I discussed with our internal identify management team, and added some codes in the logout function to delete the cookie, it worked.

Thank you for all your comments.

**Comment by danielzhanghl** [comment]
@cafeliker 
seems you did not issue GET request to logout URI? and just delete the cookie, could you share more detail on how did that? we may need do that either.
thanks.

**Comment by danielzhanghl** [comment]
@cafeliker @reasonerjt 
does that like below? try that but seems does not work.

// LogOut Habor UI
func (cc *CommonController) LogOut() {


        cc.DestroySession()
       http.SetCookie(cc.Ctx.ResponseWriter, &http.Cookie{
           Name:     "sid",
           MaxAge:   -1,
       })

}
