### ISSUE TITLE
2.0以上版本的swagger api 的脚本没有了吗

### ISSUE THREAD

**Issue by xuan200922702** [goharbor/harbor#12909]
在1.0版本有这个
wget https://raw.githubusercontent.com/goharbor/harbor/master/docs/prepare-swagger.sh https://raw.githubusercontent.com/goharbor/harbor/master/docs/swagger.yaml

2.0以上都没有了呢？我该怎么配置swagger api

**Comment by stonezdj** [comment]
You don't have to configure swagger api. there is a dev center feature in Harbor
<img width="241" alt="Screen Shot 2020-08-31 at 12 22 36 PM" src="https://user-images.githubusercontent.com/2696760/91682618-b9954780-eb84-11ea-9196-d930cce94267.png">
