### ISSUE TITLE
State mismatch  - Error after Harbor Upgrade to 2.1.0

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#12910]
Hello,
we have Harbor 2.0.2 running and just upgraded to  2.1.0. now the admin can't login and the oidc user gets the error **"State mismatch".**
I have seen this error in 2.0.0 -> 2.0.2 and there I rested everything and assumed that it was a glitch in the matrix.

What I did:

- Reset Redis
- Restart Pod, core, portal
 

Here is the list of the secrets that get generated:

jobservice:

- JOBSERVICE_SECRET: '++++++++ # (16 bytes)'

notary-server:

- ca.crt: '++++++++ # (1103 bytes)'
- tls.crt: '++++++++ # (1115 bytes)'
- tls.key: '++++++++ # (1675 bytes)'

registry:

- REGISTRY_HTTP_SECRET: '++++++++ # (16 bytes)'

core:

- CSRF_KEY: '++++++++ # (32 bytes)'
- secret: '++++++++ # (16 bytes)'

I think it has something to do with the redeployment and the regeneration of the keys.
Now I am wondering if that has something to do with regenerated "core.secret"?

Also what secrets can be regenerated across deployment and which should stay the same?

**Comment by bitsf** [comment]
The error message is at src/core/controllers/oidc.go:74
![image](https://user-images.githubusercontent.com/188115/91743395-51794c80-ebea-11ea-8d38-99a89738a043.png)

Maybe you can check core.log, to search `State mismatch, in session` to get some more info.
I think this is something change in browser session or cookie, maybe also relative with CSRF token.

**Comment by bitsf** [comment]
#12905 this seems also relative

**Comment by Vad1mo** [comment]
I rolled back to previous version and redeployed again with 

same CSRF_KEY and secret. Still the same error:

I am not sure if that is the only case, after the upgrade I am also not able to long as admin. Http 403 `Invalid user name or password.`

```sh
2020-09-01T10:45:47.443003445Z 2020/09/01 10:45:47.442 [D] [middleware.go:52]  |185.193.226.243| 302 |  20.401922ms|   match| GET      /c/oidc/login   r:/c/oidc/login
2020-09-01T10:45:47.711915207Z 2020-09-01T10:45:47Z [ERROR] [/core/controllers/oidc.go:76]: State mismatch, in session: %!s(<nil>), in url: xsI2CyIgAyNmOttBKYgo0QFwKFKzlL9M
2020-09-01T10:45:47.712281355Z 2020/09/01 10:45:47.712 [D] [middleware.go:52]  |185.193.226.243| 400 |   2.471366ms|   match| GET      /c/oidc/callback   r:/c/oidc/callback
```

`/c/oidc/callback?code=70fkapqkrIaWeCiD&state=xsI2CyIgAyNmOttBKYgo0QFwKFKzlL9M`

**Comment by reasonerjt** [comment]
@Vad1mo 

I tried the upgrade but did not reproduce this problem.

Are you seeing the issue in `incognito mode`?
The state is stored in session, so it's possible in `incognito mode` it failed to load data from session properly.

Are you seeing this issue occasionally or it always blocks from logging in via OIDC after you upgrade?

**Comment by yue-wen** [comment]
Same here.

Helm installation with harbor **v2.1.0**

```
2020/09/21 09:21:39.367 [D] [middleware.go:52]  |  47.57.116.217| 302 |    450.118µs|   match| GET      /c/oidc/login   r:/c/oidc/login

2020-09-21T09:21:40Z [ERROR] [/core/controllers/oidc.go:76]: State mismatch, in session: %!s(<nil>), in url: ugqvJDIfhG4vzc418wZdi2Gmgjwa87Yp
```
```json
{
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "State mismatch"
    }
  ]
}
```
It was upgraded from:
* helm chart: v1.4.2
* Harbor image: v2.0.2

 OIDC was works fine before upgrade.

**Comment by reasonerjt** [comment]
@yue-wen the state is stored in session it's possible that the data mapped to `sid` is broken after the upgrade.

Is it constantly reproducible?

More discussion regarding the `state mismatch` please see #12982

**Comment by yue-wen** [comment]
@reasonerjt 
Today after i use harbor helm chart [v1.5.0](https://github.com/goharbor/harbor-helm/releases/tag/v1.5.0) upgrade exist harbor, the oidc issue is gone.
