### ISSUE TITLE
prepare update script lost some settings in 2.1.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12920]
run script to update harbor.yml from 2.0.2 to 2.1.0
`docker run -it --rm -v /:/hostfs goharbor/prepare:v2.1.0-build.3878 migrate -i /home/harbor2.1/harbor/harbor.yml`

1. trivy section
![image](https://user-images.githubusercontent.com/188115/91736362-1c67fc80-ebe0-11ea-98dd-605d6afec5fa.png)

2. external_database section
![image](https://user-images.githubusercontent.com/188115/91736029-afecfd80-ebdf-11ea-96c9-96aa4ab1597d.png)

**Comment by heww** [comment]
Upgrade from v1.10.4 to v2.1,  `max_idle_conns` and `max_open_conns` are missing in `external_database`.

![image](https://user-images.githubusercontent.com/5634205/91875111-a0d48100-ecad-11ea-8b7c-9cd89b7abf34.png)
