### ISSUE TITLE
some gc log on ui is hard to understanding in 2.1.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12925]
It's hard to understand what do below log mean? This log is read directly by user, which should be more readable and meaningful.
![image](https://user-images.githubusercontent.com/188115/91740937-969b7f80-ebe6-11ea-896a-008e2f35f21c.png)

**Comment by wy65701436** [comment]
fixed per PR: https://github.com/goharbor/harbor/pull/12943
