### ISSUE TITLE
Not verified images can still be pulled in 2.1.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12921]
1. enable content trust
![image](https://user-images.githubusercontent.com/188115/91738131-9f8a5200-ebe2-11ea-9d0c-1b5fab31cd49.png)

2. push an image `busybox:test` without sign
![image](https://user-images.githubusercontent.com/188115/91738311-da8c8580-ebe2-11ea-9370-03d80967b0eb.png)

3. docker pull can still be success
![image](https://user-images.githubusercontent.com/188115/91738442-0d367e00-ebe3-11ea-9a10-a39039c991b1.png)

BTW, I can push a signed image
![image](https://user-images.githubusercontent.com/188115/91738592-45d65780-ebe3-11ea-8244-3574d75ec7b0.png)

**Comment by reasonerjt** [comment]
@bitsf this is the design the signature is done against artifact.
i.e. if two tags have the same digest, and one of the tag is signed Harbor consider the artifact signed and can be pulled.

**Comment by reasonerjt** [comment]
The reason is that when checking if an image is signed or not, it locates to the artifact, not tag, I'll make the update to make things consistent between CLI and UI.

**Comment by reasonerjt** [comment]
Fixed by
#12973 #12972
