### ISSUE TITLE
Error message is confusing -  admin role is lost in session after upgrade

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#12934]
- install 1.0
- login harbor portal and open repository
- upgrade to v2.0
- navigate to project view (error message popped up
![Screen Shot 2020-09-01 at 16 50 28](https://user-images.githubusercontent.com/5753287/91829022-782f9580-ec73-11ea-930e-9da5b5c86c75.png)
)

**Comment by steven-zou** [comment]
It seems you must logout and then can login again

**Comment by wy65701436** [comment]
root cause is here https://github.com/goharbor/harbor/issues/11301#issuecomment-615101068

**Comment by reasonerjt** [comment]
This impact 1.10 -> 2.0 migration.

We may render a 401 so that user is asked to login again.

**Comment by reasonerjt** [comment]
Reopening as the fix to this issue breaks the LDAP admin group feature, this admin role by admingroup was populated to session during user login, when fetching userinfo via user ID this information is lost.
