### ISSUE TITLE
[proxy cache] what's the expect behavior with content trust enabled

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12940]
1, create a proxy cache project mycache
2, docker pull *****/mycache/library/redis:latest
3, delete the latest tag
4, enable content trust in proxy mycache
5, docker pull *****/mycache/library/redis:latest

Get the following,

```
docker pull *****/mycache/library/redis:latest
latest: Pulling from mycache/library/redis
unknown: The image is not signed in Notary.

```

Is it the expected behavior? 

[Expeciton]
Pull the latest tag from dockhub or gives me a 404?

**Comment by reasonerjt** [comment]
UI should disable the checkbox of content trust if a project is proxy cache.

API should ignore the request to update content trunst switch status.
