### ISSUE TITLE
it's better not save p2p preheat instance when testing connection failed

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12941]
1. create a p2p instance with a wrong url, it can be saved with unhealthy status
![image](https://user-images.githubusercontent.com/188115/91927187-731e2500-ed0b-11ea-8392-d20246a60506.png)
![image](https://user-images.githubusercontent.com/188115/91927306-b6789380-ed0b-11ea-911a-298894070c4b.png)

It's better to check this as creating registry

**Comment by reasonerjt** [comment]
@AllForNothing please make sure the registry endpoint saving function has the same behavior, i.e. not to check the health when saving the endpoint.
