### ISSUE TITLE
only 1 repo is p2p preheated, while others not

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#12942]
1. setup p2p preheat, there're 4 repos, but only 1 repo test/debian is preheated.
![image](https://user-images.githubusercontent.com/188115/91928723-5a177300-ed0f-11ea-89fc-6ef8e73b4911.png)

![image](https://user-images.githubusercontent.com/188115/91928748-6b607f80-ed0f-11ea-9b03-9a6fb640519b.png)

![image](https://user-images.githubusercontent.com/188115/91928696-48ce6680-ed0f-11ea-8980-61ea998a9de3.png)

2. and there's a panic in core.log
![image](https://user-images.githubusercontent.com/188115/91929277-a1eaca00-ed10-11ea-82c6-a16b8b767877.png)

3. the second time I run preheat, it will directly fail with `preheat task already exists`
![image](https://user-images.githubusercontent.com/188115/91931456-107e5680-ed16-11ea-94e0-197ae9c8aa64.png)
![image](https://user-images.githubusercontent.com/188115/91931479-25f38080-ed16-11ea-8a6c-46210a99e1cc.png)

**Comment by reasonerjt** [comment]
This may be caused by the client-side resetting the connection?

**Comment by steven-zou** [comment]
From the log we can see all the related criteria are used by the preheat policy. Signature and vulnerability `High:4` are inherited from the project configurations. The strict criteria may cause the result that only 1 repo can be matched.

For the `preheat task already exists` issue, that's a known issue of the dragonfly P2P engine. They'll fix it later.

**Comment by steven-zou** [comment]
@bitsf 

If you can reproduce it, we can reopen it and fix.
