### ISSUE TITLE
GC deletes used blobs

### ISSUE THREAD

**Issue by aofekiko** [goharbor/harbor#12975]
The GC does not mark blobs inside an active project which causes it to delete all of the project's blobs while harbor still thinks the artifacts inside the project exist. 

When viewing the GC logs we see that no manifest is deleted from said project, when we reach the flush artifact phase, the project's repos don't even show up, as if they don't exist in the storage, which causes the contents of the whole project to be flushed. 

The project, images, artifacts etc still remain in harbor but any attempt at pulling or opening any artifact from the UI will result in an UNKNOWN_MANIFEST error. 

Looking at the storage we could see that the directory of the project did exist along with its repositories inside, but were missing the layers and manifests due to the GC. 

We are using S3 on Ceph as the storage backend 

**Versions:**

- harbor version: 2.0.1
- docker engine version: 19.03.5
- docker-compose version: 1.25.1

**Additional context:**

We will provide full logs of the job service as well as the harbor.yml as soon as possible but it may take time due to the nature of our environment.

**Comment by wy65701436** [comment]
hi, did you check the GC logs and the digest in the logs, can you confirm that the blob&manifest that delete by GC are valid ones? I mean, they are references by any of artifact in Harbor.

And, can you reproduce the issue?

**Comment by aofekiko** [comment]
The blobs & manifests that were deleted were valid and were used by the artifacts that now cause UNKNOWN_MANIFEST when I try to open them.
What do you mean by checking the digest?
If you mean the API calls that run before the flushing, then I did delete some repos that had the same digest as the artifacts I lost, I assumed this was the problem but when I tried to reproduce it, it worked fine. 
So far I have not managed to find a way to reproduce the problem. But I think a key point here is that the GC didn't see the existence of the repositories I lost.

**Comment by wy65701436** [comment]
For the digtest checking:
can you try to check the existence with the digest of deleted manifest in the table of artifact & artifact_blob?
```
select * from artifact where digest = '****'
select * from artifact_blob where digest_af = '****'
```

Did you get any error when to delete repo or artifact in Harbor? And please share the core.log and the GC log as well.

**Some background** In Harbor v2.0.1, Harbor leverages the distribution GC to do the mark & swepp job, it doesn't use the Harbor DB data to compute the reference count. So, if GC deletes any of blob or manifest, it definitely gets 0 reference count from the backend storage.

**Comment by ananditabhatt** [comment]
> For the digtest checking:
> can you try to check the existence with the digest of deleted manifest in the table of artifact & artifact_blob?
> 
> ```
> select * from artifact where digest = '****'
> select * from artifact_blob where digest_af = '****'
> ```
> 
> Did you get any error when to delete repo or artifact in Harbor? And please share the core.log and the GC log as well.
> 
> **Some background** In Harbor v2.0.1, Harbor leverages the distribution GC to do the mark & sweep job, it doesn't use the Harbor DB data to compute the reference count. So, if GC deletes any of blob or manifest, it definitely gets 0 reference count from the backend storage.

Hi @wy65701436, we are facing a similar issue in our project. We have a job running where GC runs every night. However, yesterday it ran and deleted close to 80 GB data. On further analyses we found that it deleted blobs of layers from various images, even the valid (referenced) ones. 
We followed the suggestion you gave and looked up the digest in artifact and artifact_blob table. We are able to find those blobs reference there however the data is deleted from S3.
It appears that the GC deleted blobs despite being referred. Also, we verified the policies and there were repos with and without retention policies which were impacted by that.
Still not sure what's the root cause and how to avoid this in future.

**Comment by aofekiko** [comment]
Back then I closed the issue because we moved from S3 as our harbor storage so we couldn't help further with the issue.
I'd still love to see this issue resolved so we could maybe move back to S3 some day.

@ananditabhatt I didn't see any mention of the version you are running or the s3 provider you are using, is the issue still on newer versions?

**Comment by reasonerjt** [comment]
@aofekiko let's continue the discussion under the new issue, instead of adding comments in the closed one.

**Comment by AnavMahajan** [comment]
@aofekiko  @reasonerjt  Created new issue with more details GC deletes used blobs #15445
