### ISSUE TITLE
每个版本的API差别也太大了吧，能不能稳定点？

### ISSUE THREAD

**Issue by hugo2017** [goharbor/harbor#12983]
What can we help you?

**Comment by reasonerjt** [comment]
which one do you mean?

For 1.x -> 2.x upgrade, per semver definition the MAJOR release change does introduce break change.

**Comment by ruirui9** [comment]
兄弟 api的问题研究明白了么 ，能分享一下么 我也头疼着api

**Comment by xaleeks** [comment]
These kinds of tickets are of little use to us.  It roughly translates to "can APIs be more stable?" 

Please look at the documentation on how to create meaningful posts.  There are even templates provided.
