### ISSUE TITLE
generate `docker pull command` with tag instead of sha

### ISSUE THREAD

**Issue by tangx** [goharbor/harbor#12980]
**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.2]
- docker engine version: [19.03]

# Generate pull command

Could use  **TAG**  to Generate pull command .
Sha is hard to use

```
docker pull harbor.example.com/gitlab/gitlab-runner@sha256:06e2b46ada1b70f6e625bad58651138210a3d93dd877088b977567871379b8a8
```
![image](https://user-images.githubusercontent.com/7335398/92207613-17df6480-eebc-11ea-9a9f-dcb4a17664ff.png)

**Comment by AllForNothing** [comment]
@tangx 
For Harbor version 2.1.x and above, you can generate `docker pull command` with tag on artifact detail page
![image](https://user-images.githubusercontent.com/30999793/92338450-180d7900-f0e3-11ea-8d7a-290bb6fdfab7.png)
