### ISSUE TITLE
Can not login when using https protocol！！unable to decode private key PEM: unable to find PEM encoded data！

### ISSUE THREAD

**Issue by LinQing2017** [goharbor/harbor#13019]
My environment information：

harbor version：2.0.2
helm version：1.4.2
k8s version：v1.13.10

When I login using https protocol, I get the following error：

```
[root@kube certs]# docker login core.harbor.domain
Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain/v2/: received unexpected HTTP status: 500 Internal Server Error
```
At the same time, there is the following output in the harbor-core pod：

```
2020-09-09T11:51:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: unable to decode private key PEM: unable to find PEM encoded data
```
The certificate is automatically generated by helm, and the same configuration can work normally in version 1.9.
PS：I have manually imported the ca certificate into the docker daemon！！

**Comment by steven-zou** [comment]
Intuitively feel that this certificate is not correctly generated.

@ywk253100 

Could you please take a look?

**Comment by ywk253100** [comment]
What is the version of your helm client? Is this a fresh installation or upgrading from 1.9?

**Comment by ywk253100** [comment]
Closing as inactivity
