### ISSUE TITLE
unknown blob

### ISSUE THREAD

**Issue by a121984376** [goharbor/harbor#13010]
What can we help you?
my network is 
HTTPS->Haproxy  ->  HTTP-> Harbor

docker login is succeed
docker push   is error:
error message:
fecad0a81d5: Preparing
218fd7d0335c: Preparing
8954cc800da0: Preparing
6cd0e4a3b261: Preparing
3ac8989cc414: Preparing
d0f104dc0a1f: Preparing
d0f104dc0a1f: Waiting
docker : unknown blob

**Comment by steven-zou** [comment]
@a121984376 

If possible, please provide the related logs (proxy.log, core.log, registry.log etc.) for doing troubleshooting.

**Comment by ywk253100** [comment]
Please refer to `Using nginx or Load Balancing` section in https://goharbor.io/docs/2.0.0/install-config/troubleshoot-installation/
