### ISSUE TITLE
Replicating public images from gcr.io requires authentication

### ISSUE THREAD

**Issue by MohamedTalhaoui** [goharbor/harbor#13022]
I am trying to set up a replication from gcr.io/tekton-releases/github.com/tektoncd/** to harbor.
Following instructions from https://github.com/goharbor/harbor/issues/11724, I have set up the following:
Registry:
```json
  {
    "name": "public-gcr",
    "description": "",
    "type": "docker-registry",
    "url": "https://gcr.io",
    "token_service_url": "",
    "credential": {
      "type": "",
      "access_key": "",
      "access_secret": ""
    },
    "insecure": false,
    "status": "healthy",
    "creation_time": "2020-09-04T15:31:53.886696Z",
    "update_time": "2020-09-09T16:06:36.532824Z"
  }
```
Replication:
```json
{
  "name": "docker-tekton",
  "description": "tekton",
  "src_registry": {
    "name": "public-gcr"
  },
  "dest_namespace": "library/tektoncd",
  "trigger": {
    "type": "manual"
  },
  "enabled": true,
  "deletion": false,
  "override": true,
  "filters": [
    {
      "type": "name",
      "value": "tekton-releases/github.com/tektoncd/**"
    }
  ,
    {
      "type": "tag",
      "value": "v0.15.1"
    }
  ]
}
```

When running the replication it fails with **"No valid credentials was supplied"**:
![image](https://user-images.githubusercontent.com/26436887/92625304-c4f51b00-f2c8-11ea-9058-978b801bccc0.png)

I expect no credentials are needed here since tekton images are public.

**Comment by steven-zou** [comment]
@MohamedTalhaoui 

The root cause of requiring access credentials when replicating public images from GCR may be because you configured a general pattern in the repo/tag filters, and we need the GCR API access to do check and matching operations. If you directly specify concrete repo name, the credential can then be ignored.

@bitsf 
Can you double confirm it?

**Comment by steven-zou** [comment]
@steven-zou 

Could you please try the native （`docker-registry`）adapter to replicate public repositories？

**Comment by bitsf** [comment]
yes, gcr adapter need auth to call api

**Comment by MohamedTalhaoui** [comment]
Just to clarify, my replication does use the docker-registry adapter not the gcr one.
I agree that pointing to individual repos works, but I have to setup dozens of replication rules for tektoncd images.

**Comment by sidewinder12s** [comment]
Setting up a general GCR.io Registry with:

Endpoint: `https://gcr.io` 
Provider: Docker Registry appears to work for public GCR endpoints
