### ISSUE TITLE
Manual Scan All job stuck

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#13027]
I am using Harbor 2.0.2 with Trivy as scanner.
After manually running Scan All the job is stuck for several hours in following state:

```
curl https://harbor/api/v2.0/scans/all/metrics
{
  "total": 3950,
  "completed": 3945,
  "metrics": {
    "Running": 5,
    "Success": 3945
  },
  "requester": "22",
  "ongoing": true
}
```

I couldn't find a way how to stop it. I am pretty sure Trivy is not doing anything.

Any ideas? Thanks

**Comment by balonik** [comment]
The job was actually finished and it was just reporting wrong info. After I figured out how to trigger manual Scan All job via API (below) it started a new job and UI and API started giving proper info again.

```
curl -X POST "https://harbor/api/v2.0/system/scanAll/schedule" -H "accept: application/json" -H "Content-Type: application/json" -H "X-Harbor-CSRF-Token: reducted" -d '{"schedule":{"type":"Manual"}}'
```

**Comment by steven-zou** [comment]
@balonik 

When you said the status is stunk, have you checked the logs of job service? No any logs indicating some jobs are still running? If not, have you checked if there are some errors that occurred at the core side, especially something like `update job status`?

**Comment by balonik** [comment]
Sorry, I forgot about it and I can't reproduce it in 2.1.1.
