### ISSUE TITLE
Even after making parameter redirect: disabled: false all the docker pull/push requests are directly contacting s3-endpoint not the Application Load Balancer

### ISSUE THREAD

**Issue by niroopj** [goharbor/harbor#13037]
Hi Team,
   This is an issue with respect to pull/push requests where it is directly trying to communicate with s3 end point.
Even after we have made redirect: disabled: false in harbor configuration still the request instead of going to the Application Load Balancer it is contacting directly the s3 end point...
How can this issue be resolved??

Thanks & Regards,
   Niroop

**Comment by steven-zou** [comment]
@niroopj 

It seems you need to set the `redirect: disabled` to be `true`. The setting has been verified in many places including the harbor operator. It does work.

@heww 

Could you please double confirm?
