### ISSUE TITLE
Logs are not displayed in Safari and Firefox

### ISSUE THREAD

**Issue by savealive** [goharbor/harbor#13031]
Seems harbor UI doesn't work properly in Safari and Firefox. We have a pretty long log of 300k events in it. If you click on "Logs" in harbor UI it will display indefinite spinner.
Safari:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/12967071/92773913-9fb4eb00-f362-11ea-8768-8f6fb2b1e73c.png">

In Chrome everything works fine:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/12967071/92774044-b8bd9c00-f362-11ea-8d5e-bbf139c90da7.png">

It doesn't look like any problem with API but rather with UI. API returns logs json correctly:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/12967071/92774436-16ea7f00-f363-11ea-9896-da40363e2c59.png">

Harbor version:  v2.0.2

**Comment by wy65701436** [comment]
it fixed by https://github.com/goharbor/harbor/pull/12629, and will be in the v2.1.0, you can just try with the latest rc2 build, thanks.
