### ISSUE TITLE
why!!!!!!!build by source code v1.9.3 always failed by the step create container portal????????? it's so bad

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#13044]
why can help me???????
no one face this problem?????????????????
when exec the step:  build container portal by /harbor/make/photon/partal/Dockerfile  ,it always failed

**Comment by steven-zou** [comment]
@tongying123456 

Any logs provided? It may be blocked by the process of pulling packages from npm repo? We need more context info to do troubleshooting.

**Comment by tongying123456** [comment]
> @tongying123456
> 
> Any logs provided? It may be blocked by the process of pulling packages from npm repo? We need more context info to do troubleshooting.

logs:
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! harbor@1.9.0 release: `ng build --prod`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the harbor@1.9.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-15T17_54_57_710Z-debug.log
The command '/bin/sh -c ls -la     && npm run build_lib     && npm run link_lib     && npm run release' returned a non-zero code: 137
/home/ty2/Downloads/harbor-1.9.3/make/photon/Makefile:111: recipe for target '_build_portal' failed
make[1]: *** [_build_portal] Error 137
make[1]: Leaving directory '/home/ty2/Downloads/harbor-1.9.3'
Makefile:306: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by xaleeks** [comment]
I'm closing this because it's spam.  Please read the guidelines on how to create an issue

**Comment by xaleeks** [comment]
this definitely does not qualify as a good first issue
