### ISSUE TITLE
does harbor support Helm 3 charts, or would like to know component versions

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor#13042]
Which version of Harbor supports Helm 3 charts, i.e., charts of apiVersion v2?

In general, we can get hints by looking at the version of the Chartmuseum used by Harbor.  At least at Harbor v1.9.3, the component version is reflected on the image tag, e.g., goharbor/chartmuseum-photon:v0.9.0-v1.9.3, but Harbor v2.0.1 image tags only have the Harbor version.  Chartmeseum does not seem to announce its version in the logs.

**Comment by steven-zou** [comment]
@wu105 

From V2.0.0, Harbor is upgraded to be an OCI registry that does support storing all OCI compatible the artifacts, of course, including the Helm 3 Charts.

From version 1.10.2, the component version will only mark the harbor version, remove the 3rd party component versions for keeping simple and consistent.
