### ISSUE TITLE
New schedule cannot support cron type attribute

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#13047]
When doing GC/Scan migration to task mgr & schedule mgr, the method which handles to create schedule does not support the type attribute, like daily, weekly or custom. The attribute is used for UI to render only.

```
Schedule(ctx context.Context, vendorType string, vendorID int64, cron string,
		callbackFuncName string, params interface{}) (int64, error)
```

**Comment by ywk253100** [comment]
Fixed
