### ISSUE TITLE
failed to grabage collect: failed to mark: filesystem:filesystem: invalid checksum digest  format

### ISSUE THREAD

**Issue by wangdwcsd** [goharbor/harbor#13046]
harbor  version:  1.9.4
storage:  glusterfs

exec registry garbage-collect --delete-untagged=true /etc/registry/config.yml

report errors:
failed to grabage collect: failed to mark: filesystem:filesystem: invalid checksum digest  format

**Comment by wy65701436** [comment]
you can refer to https://github.com/docker/distribution/issues/1960#issuecomment-449620559 to get more details.

**Comment by YahuiAn** [comment]
> you can refer to [distribution/distribution#1960 (comment)](https://github.com/distribution/distribution/issues/1960#issuecomment-449620559) to get more details.

I didn't understand why, but it did solve my problem 😂
