### ISSUE TITLE
invalid character 'U' looking for beginning of value

### ISSUE THREAD

**Issue by JadeQin** [goharbor/harbor#13045]
I deploy harbor 1.10.1, when I use `docker login `， it show the error message like this :
```
Error response from daemon: Get https://***/v2/: error parsing HTTP 400 response body: invalid character 'U' looking for beginning of value: "Unable to handle service: harbor-registry?account=test"
```
What is the problem? How can I resolve it? Thanks

**Comment by steven-zou** [comment]
@JadeQin 

All the Harbor containers are `healthy` at that time?

cc @ywk253100 @wy65701436 any suggestions?

**Comment by iiwoai** [comment]
I got the same problem. I deploy harbor v2.0.2 

docker login , it show the error  message like this 

Error response from daemon: Get https://xx/v2/: unable to decode token response: invalid character 'h' looking for beginning of value

ALL the  Harbor containers are healthy

**Comment by JadeQin** [comment]
@steven-zou yes, ALL the Harbor containers are healthy.
I deploy harbor again and resolve it.

**Comment by alphakevin** [comment]
@JadeQin I have had the same problem, if your serve harbor behind a nginx reverse proxy, there is a solution #3114

**Comment by jakublabno** [comment]
Same issue on my harbor registry

**Comment by maese83** [comment]
On my side I had the same issue. Problem was the configured **external_url** was not matching with the hostname I used to connect to harbor. I was using the hostname configured in harbor.yml

# And when it enabled the hostname will no longer used
external_url: https://registry.xyz.com

After I used the external_url to make the docker pull it worked
