### ISSUE TITLE
Limit of 15 retention rules

### ISSUE THREAD

**Issue by jaswQ** [goharbor/harbor#13041]
There is a hardcoded limit of max 15 retention rules that got added here: https://github.com/goharbor/harbor/pull/8936

I have been unable to find a reason of this limitation. Is there a technical reason to limit to 15 retention rules? Are we supposed to upgrade to a "pro" version to get more?

**Comment by steven-zou** [comment]
@jaswQ 

Harbor does not have a `pro` version.

We'll discuss your question about the limitation applied to the number of created retention rules.


cc @bitsf

**Comment by bitsf** [comment]
No pro version, harbor is quit open.
We just think 15 rules are enough, and it would not be too complex for GUI design and impact rate.

**Comment by xaleeks** [comment]
what component or pod needs to scale with this.  These are training wheels we installed with first release of tag retention, i think we talked about removing them as the end goal if I remember correctly @steven-zou

**Comment by meganlyntalley** [comment]
This is also a concern for my organization; sometimes 15 rules aren't enough. Is this still being considered?

**Comment by pschultz** [comment]
We want to make sure that any image that has been used recently anywhere in our infrastructure remains in the registry. The nDaysSinceLastPull template isn't enough because images can be used without being pulled if they already exist on the docker host. Some projects have more than 15 repositories and/or tags in use.

Please remove this limit or at least make it configurable.

**Comment by pschultz** [comment]
Yes, this issue is still relevant.

**Comment by haagtobias** [comment]
We have also an issue with this limit in our organization. My department has one projekt in Harbor with many different images. So many retention policies are necessary. I don't understand the reason for this limit. Please consider to remove it.
