### ISSUE TITLE
Harbor replication failures

### ISSUE THREAD

**Issue by Bak3y** [goharbor/harbor#13052]
I'm trying to set up replication between dockerhub and harbor, pulling some public images for caching reasons, and I'm seeing errors like this:

`2020-09-14T14:45:59Z [ERROR] [/replication/transfer/image/transfer.go:326]: failed to push manifest of artifact library/golang:sha256:ffa8f83bdc012f535063e016a30f4f6bcb0e40d5eeb7517111f5daf55bbce75f: http status code: 500, body: {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{}}]}`

Why does it seem like harbor is trying to push anything at all?  This is replicating golang images with this setup:

![image](https://user-images.githubusercontent.com/4029474/93101330-bcf1fe00-f66f-11ea-9cfa-0386011d8a7c.png)

Note I'm able to sync 1.9 and 1.10 images fine, but 1.11 fails with the message above.

**Comment by steven-zou** [comment]
@Bak3y 

Any mode replication will trigger two actions: pull content from the src and push the pulled content to the dest.

**Comment by steven-zou** [comment]
@Bak3y 

>Note I'm able to sync 1.9 and 1.10 images fine, but 1.11 fails with the message above.

`1.11`? Do you mean `2.0` or `1.10.x`? Harbor never release the 1.11 version.

**Comment by Bak3y** [comment]
> @Bak3y
> 
> > Note I'm able to sync 1.9 and 1.10 images fine, but 1.11 fails with the message above.
> 
> `1.11`? Do you mean `2.0` or `1.10.x`? Harbor never release the 1.11 version.

Here I'm talking about golang versions, sorry if that was unclear.

I've had the same behavior attempting to sync python3 images, it works fine for a few matches and then suddenly throws the error above and fails to sync.

**Comment by Bak3y** [comment]
@steven-zou any ideas here?

**Comment by Bak3y** [comment]
@bitsf @ywk253100 I'd like some more feedback here on what I may be doing wrong, please.

**Comment by zacheryph** [comment]
I get the same/similar. I get for all images though. I was attempting with alpine, and then tried golang after seeing this ticket.

```
2020-10-20T06:11:24Z [ERROR] [/replication/transfer/image/transfer.go:308]: failed to pushing the blob sha256:a24bb4013296f61e89ba57005a7b3e52274d8edd3ae2077d04395f806b63d83e, size 1509: http status code: 500, body: {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"s3aws","Enclosed":{}}}]}
```

This is a helm chart deployment using a minio backend and I did make sure to `disableredirect`.

**Comment by Bak3y** [comment]
Today I upgraded to using harbor v2.1.0-a3eca103 (via the harbor-helm chart v1.5.0) and initial testing indicates this problem may be gone now.

Heads up @zacheryph
