### ISSUE TITLE
Integrate Harbor with LitmusChaos to enable chaos testing Harbor

### ISSUE THREAD

**Issue by prithvi1307** [goharbor/harbor#13066]
Chaos Engineering will help enable extra resiliency before any outage impacts Harbor itself. With cloud-native resiliency being of uttermost priority in the upcoming transformation, chaos might help prevent downtime drastically!

**Comment by steven-zou** [comment]
@prithvi1307 

Do you have any plan to support chaos testing in Harbor? If yes, you can share some info in our bi-weekly community meeting. Find the meeting schedule in the Harbor readme.

**Comment by bitsf** [comment]
what is Chaos? Is there any official document?

**Comment by prithvi1307** [comment]
@steven-zou Not ready with an exact plan but I believe chaos tests can be used in the CI/CD pipeline to help test vulnerabilities that might possibly occur in Harbor. Any thoughts on your end? I might be able to follow up then

**Comment by prithvi1307** [comment]
> what is Chaos? Is there any official document?

@bitsf Chaos Engineering is the practice of inducing a fault deliberately in a system or application to find out or test the resiliency of the system. LitmusChaos is a Chaos Engineering toolset that helps carry out chaos testing in cloud-native applications.
Here are the useful links: https://litmuschaos.io/
Docs: https://docs.litmuschaos.io/docs/getstarted/
Blogs: https://dev.to/t/litmuschaos/latest

Please take a look and let me know what else would you need!

**Comment by xaleeks** [comment]
sorry to say, but this is not going to be done by the Harbor team.  But feel free to contribute a Pull Request and we'll do a code review.
