### ISSUE TITLE
[OIDC] Conflict in username, when change OIDC domain

### ISSUE THREAD

**Issue by yue-wen** [goharbor/harbor#13068]
### Get this error, when change OIDC domain.
Error message:
"Conflict in username, the user with same username has been onboarded."

**Step to reproduce**:
* set up OIDC config with endpoint example: https://auth.oidc-old-domain.com/auth/realms/registry
* login some user via OIDC
* change oidc domain, example: https://auth.oidc-new-domain.com/auth/realms/registry
* update OIDC config with new endpoint
* re-login same user of step 2  

**Workaround to fix this case**
* Connect to harbor database `registry`
* find table `oidc_user` 
* change old OIDC endpoint of row `subiss` to new endpoint

_Originally posted by @yue-wen in https://github.com/goharbor/harbor/issues/9600#issuecomment-693119481_

**Comment by reasonerjt** [comment]
@yue-wen unfortunately this is the current design, Harbor uses the `issuer` and `subject` to identify users from OIDC provider.  And your OIDC provider uses the domain as the `issuer`.  I wish to suggest you stick to the same issuer when you change the domain, because logically it is the same one.

I agree current approach does not have enough flexibility to cover the corner cases.  I'm thinking maybe we should introduce other settings so admin can customize the claim for identifying user.

There is another issue related to this limitation:
https://github.com/goharbor/harbor/issues/10797

**Comment by yue-wen** [comment]
@reasonerjt 
Thanks for your reply.

Unfortunately we have to change the OIDC provider domain.

I have read the #10797 .
I have some thoughts instead changing design of "subiss".

If OIDC provider URL changed, which means it should be a "new" provider to harbor. 

Then old onboard oidc user data should removed.
Because base on current design, we can only use  one oidc provider to login at same time.

And the projects access can be reclaimed by oidc group mapping.

With the oidc "Automatic onboarding" feature, user can smoothly migrate to new oidc provider. 

I think the only disadvantage is, that oidc user need update they CLI secret after change OIDC provider url.

**Comment by reasonerjt** [comment]
@yue-wen 
Even if you have to change the domain of OIDC provider I think it may be possible to update the configuration to make sure the `issuer` stays the same.

As for your suggestion, if we decide to support multiple OIDC provider, the groups with same name from different OIDC provider must be treated as different groups, same reason we can't assume `jack` from google and `jack` from facebook is the same person.  So I don't think there can be a smooth migration with such approach.

**Comment by yue-wen** [comment]
@reasonerjt 
Yes, you are right about multi oidc providers situation.
Change oidc domain is unusual case.
Looking forwad an enhancement in feature release can cover this case.

**Comment by Jamesits** [comment]
We encountered this problem too. After changing OIDC provider, we are unable to either login with existing account (they are mapped to the same email and NameID), or remove any accounts (https://github.com/goharbor/harbor/issues/8424). This is very annoying.

**Comment by lindhe** [comment]
We also have an issue related to this. There exists two users in our directory with unique IDs (`Andreas_L` and `Simon_A`), both without any e-mail (there is no registered e-mail in the directory). Only `Andreas_L` can login to Harbor, but when `Simon_A` tries to login via OIDC it says that "Conflict, the user with same username or email has been onboarded" (in this case: `email=''`).

Would it be appreciated by the Harbor maintainers if we created a PR to try and remedy this?

**Comment by Jamesits** [comment]
nope
