### ISSUE TITLE
The tag delete confirm tips is not correct under chinese mode

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#13086]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

Harbor 2.x deletes one tag will not delete other tags with the same digest, but the confirm tip is:
<img width="958" alt="WechatIMG23" src="https://user-images.githubusercontent.com/31262637/93335124-90e5a100-f858-11ea-9cd1-1a3992605c06.png">

<img width="841" alt="WechatIMG25" src="https://user-images.githubusercontent.com/31262637/93335175-a22ead80-f858-11ea-965f-6547d0829c47.png">

**Comment by AllForNothing** [comment]
This issue has been fixed by: #13104 for master and #13105 for release-2.1.0
