### ISSUE TITLE
Get artifact api should limit the count of tags returned

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#13099]
API: /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}

When trying to reproduce the issue #13098 with Harbor 2.1, found this API doesn't limit the tags returned, when there are 5000 tags in same repo, it will return all tags and took long time to return (26-27 seconds)

It is better to limit the max count of tags returned.

https://github.com/goharbor/harbor/blob/91e2779822ae0c096ae97ea9de7c4cac20ab0a61/src/controller/artifact/controller.go#L599

**Comment by ywk253100** [comment]
You can call the getting artifact API without fetching the tags: https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L456

For the tag part, there is a separated API to list them with pagination support: https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L614

**Comment by steven-zou** [comment]
artifact view : withTag=false

get tags by pagination
