### ISSUE TITLE
Healthcheck API is not documented

### ISSUE THREAD

**Issue by Shadrocks** [goharbor/harbor#13090]
Unable to locate any documentation on how to implement health check API calls. Documentation should include example API calls, curl command formatting, authentication requirements, individual endpoints and detailed explanation of response information.

**Comment by Shadrocks** [comment]
Are there any documents that I can refer to today to get help setting up a healthcheck call? We are trying to monitor our instance for problems.

**Comment by ywk253100** [comment]
Please refer to https://github.com/goharbor/harbor/blob/master/api/v2.0/legacy_swagger.yaml#L22
