### ISSUE TITLE
Allow API access with an API-Key when OIDC is used

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#13093]
**Is your feature request related to a problem? Please describe.**
When OIDC is enabled, only the admin user/credential can use the API. 

**Describe the solution you'd like**
Harbor should extend the "Robot Accounts" with READ/WRITE API

**Comment by Wykiki** [comment]
Just encoutered that problem while trying to setup replication with Harbor as Provider.

**Comment by steven-zou** [comment]
We're planning to enhance the robot account in the next 2.2 version. Supporting API permission is one of the items. Please stay tuned.

**Comment by pingcrosby** [comment]
See also.. where i have it working with Azure AD
https://github.com/goharbor/harbor/issues/13683#issuecomment-739036574

**Comment by christian-korneck** [comment]
>  planning to enhance the robot account in the next 2.2 version. Supporting API permission is one of the items. Please stay tuned.

I can see the first harbor 2.2 rc has been released today. Just to clarify: Is it possible in 2.2 to assign arbitrary api permissions to a robot account or only the select 10 permissions that are shown in the GUI? (I’m interested in editing the repo description, which doesn’t work with a regular user when oidc auth is enabled).

**Comment by Morriz** [comment]
@steven-zou is this delivered in 2.2.1 already?

**Comment by Vad1mo** [comment]
@Morriz take a look at https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533 and let us know if that did work for you

**Comment by Morriz** [comment]
got that to work! check out https://github.com/redkubes/otomi-tasks/blob/master/src/tasks/harbor/harbor.ts/

**Comment by wy65701436** [comment]
@Vad1mo does the robot v2 meet your requirement?

**Comment by YangJiao0817** [comment]
In the new version(v2.8.x, v2.7.x, v2.6.x) of Harbor, you can use robot v2 to call the API of OIDC auth.
