### ISSUE TITLE
Support custom oauth request parameters for OIDC Authentication

### ISSUE THREAD

**Issue by mhuangpivotal** [goharbor/harbor#13092]
After configuring Harbor with our OIDC client, this is the authorization URL we get when signing in with OIDC

```
https://gaz-preview.csp-vidm-prod.com/oauth/authorize?client_id=<client_id>&redirect_uri=<redirect_uri>&response_type=code&scope=openid&state=<state>
```

However, this fails because our OIDC provider requires `idp_id` parameter to be set. If we manually add `idp_id=<id>&` to the URL, then everything works.

This seems to be common in other OIDC providers also, for example, Facebook's oauth supports a `display` parameter.

Would it be possible for Harbor to support such custom parameters in OIDC auth configuration?

**Comment by reasonerjt** [comment]
It is.  Are such "custom parameters" mentioned in any of the specs?

**Comment by mhuangpivotal** [comment]
Sorry I missed your comment. I found the following specs:

https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#parameters
https://tools.ietf.org/html/rfc6749#section-8.2

Specifically this paragraph
> Unregistered vendor-specific parameter extensions that are not
   commonly applicable and that are specific to the implementation
   details of the authorization server where they are used SHOULD
   utilize a vendor-specific prefix that is not likely to conflict with
   other registered values (e.g., begin with 'companyname_').

Hope this helps!

**Comment by reasonerjt** [comment]
After the PR #13791 is merged, you will be able to set such parameters via the configuration attribute `oidc_extra_redirect_parms` by calling API:
```
curl -H "Content-Type:application/json" -X PUT -u "admin:Harbor12345" -kv https://jt-dev.local.goharbor.io/api/v2.0/configurations -d'{"oidc_name":"***", "oidc_endpoint":"***", 
.....
"oidc_extra_redirect_parms":"{\"key\":\"value\"}"}'
```

Note that due to time constraints this will only be exposed via API in v2.2.0.  If we see more usage in your case we'll expose it on the UI.
