### ISSUE TITLE
the image has no tag in ui

### ISSUE THREAD

**Issue by mzzgaopeng** [goharbor/harbor#13100]
when I push the image with the same tag，but these image sha256 are not same，when I find the ui in my Browser，i find the image without tag

**Comment by steven-zou** [comment]
What's the harbor version?

**Comment by mzzgaopeng** [comment]
> What's the harbor version?

V2.0

**Comment by mzzgaopeng** [comment]
![harbor-problem](https://user-images.githubusercontent.com/22125180/93740125-732f8780-fc1c-11ea-8b1c-fff0dcbee0f6.png)

**Comment by steven-zou** [comment]
It's by design.
