### ISSUE TITLE
Version 2.1.0 not available on helm repo

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [goharbor/harbor#13119]
Hi,
When the helm chart for the version 2.1.0  will be available on the official repo? 
Currently the latest version available is the 2.0.2

`
harbor/harbor   1.4.2           2.0.2           An open source trusted cloud native registry th...
`

Thanks,
Pietro

**Comment by whereismyjetpack** [comment]
The helm chart is managed in a different repo, there is a PR for 2.1.0, but when I applied it I ran into issues. https://github.com/goharbor/harbor-helm/pull/735

**Comment by p3t3rp3pp3r** [comment]
Thanks  @whereismyjetpack for the quick reply.

**Comment by yue-wen** [comment]
It is now available.
https://github.com/goharbor/harbor-helm/releases/tag/v1.5.0

**Comment by ywk253100** [comment]
The Harbor chart 1.5.0 with OSS Harbor 2.1.0 has released.
