### ISSUE TITLE
robot account enhancement

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#13110]
- API permissions customizability(multiple projects & more api access)
- CSP Scanner Support
- Remove $ sign from robot account name

**Comment by xaleeks** [comment]
where is the solution for removing $sign recorded? I couldn't find it @wy65701436

**Comment by swade1987** [comment]
I would propose to replace the `$` with a `+`

**Comment by MrD2** [comment]
> I would propose to replace the `$` with a `+`

OR `-` ex: robot-proj1.

Why keep a special symbol if the account name is already prep-ended?

**Comment by wy65701436** [comment]
In 2.2, the prefix can be set to anything.

**Comment by wy65701436** [comment]
Close it as fixed.
