### ISSUE TITLE
Avoid too many GET request to the dockerhub when checking the latest manifest

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#13112]
When pulling an image by proxy cache, if the image is already cached in local, it should check the latest manifest from remote by HEAD request instead of GET. 
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

**Comment by xaleeks** [comment]
this will be very important in mitigating against dockerhubs strict rate limiting that goes into effect on 11.1

**Comment by xaleeks** [comment]
@a-mccarthy this is the thing we discussed in the blog that will help mitigate against DH rate limiting policies going into effect 11.1.  I'm not sure if it's worth emphasizing this in the doc somewhere.  The salient point here is that if none of the blobs for the image are updated, it will not register +1 against dockerhub's quota.

**Comment by immanuelfodor** [comment]
Thank you for implementing this on time! :)
