### ISSUE TITLE
Trouble with viewing the log of policy tag retenion

### ISSUE THREAD

**Issue by eugenesotnikov** [goharbor/harbor#13118]
Ather upgrade from 1.10.3 to 2.1.0 i have trouble with viewing the log of policy tag retention. 
When i entering to project-policy-tag retention and opening any log, i viewing infinity loading gif and cannot open log.

**Versions:**
- harbor version: [2.1.0]
- docker engine version: [19.03.12]
- docker-compose version: [1.26.1]

![image](https://user-images.githubusercontent.com/60689184/93790398-a7667080-fc3b-11ea-983e-9cade47f041c.png)

**Comment by bitsf** [comment]
refresh your browser, or clean the cache
check developer tool of Chrome
check /var/log/harbor/core.log

**Comment by eugenesotnikov** [comment]
I cleared cashe. It didn't help. 
But when i open log for 10 or 20 time, it is opened successful one time. And after close it isn't opened again.
In /var/log/harbor/core.log error is absent

Sep 28 07:11:38 172.18.0.1 core[1217]: 2020-09-28T07:11:38Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'InternalArtifact' on topic 'PULL_ARTIFACT': ID-2680, Repository-vuejs/frontend Tags-[dev-4a19ea45] Digest-sha256:b2b118ebf4534295090b725c93eaa050526b4408194213139c7bd01e87bbfbcf Operator-admin OccurAt-2020-09-28 07:11:38
Sep 28 07:11:38 172.18.0.1 core[1217]: 2020-09-28T07:11:38Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-2680, Repository-vuejs/frontend Tags-[dev-4a19ea45] Digest-sha256:b2b118ebf4534295090b725c93eaa050526b4408194213139c7bd01e87bbfbcf Operator-admin OccurAt-2020-09-28 07:11:38
Sep 28 07:11:38 172.18.0.1 core[1217]: 2020-09-28T07:11:38Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'AuditLog' on topic 'PULL_ARTIFACT': ID-2680, Repository-vuejs/frontend Tags-[dev-4a19ea45] Digest-sha256:b2b118ebf4534295090b725c93eaa050526b4408194213139c7bd01e87bbfbcf Operator-admin OccurAt-2020-09-28 07:11:38

**Comment by bitsf** [comment]
fixed by pr #13905 targeting release 2.2.0
