### ISSUE TITLE
Allow robot account to invoke API to create another robot account

### ISSUE THREAD

**Issue by cafeliker** [goharbor/harbor#13125]
**Is your feature request related to a problem? Please describe.**
Per cyber security requirements, the robot account needs to be rotated every 6 months; it's not possible to rotate the robot account used in pipelines with automation approach.

**Describe the solution you'd like**
Allow robot account to invoke robot API to create another robot account; the idea is regularly call robot API to create a new robot account which replaces the existing one.

**Comment by xaleeks** [comment]
you will be able to regen the token for the robot instead of having to recreate the robot on the v2.2

**Comment by xaleeks** [comment]
this isn't part of core CI.  We don't want robots to be delegating access to other robots, it can cause some really bad side effects and we are not at a stage where we can respond accordingly
