### ISSUE TITLE
registry fails to load storage driver in v2.1.0

### ISSUE THREAD

**Issue by fl-max** [goharbor/harbor#13120]
**Expected behavior and actual behavior:**
Using [example config](https://github.com/docker/distribution/blob/master/cmd/registry/config-example.yml) from the [Docs](https://docs.docker.com/registry/configuration/#storage), v2.1.0 is failing to run with the following error:

```bash
[ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:open : no such file or directory
[FATAL] [/registryctl/main.go:78]: Failed to load configurations with error: open : no such file or directory
```

This is working with `v2.0.*`.

**Steps to reproduce the problem:**

**config-example.yaml**
```bash
$ cat ./config-example.yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/registry
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**v2.1.0 not working:**
```bash
$ docker run -v `pwd`/config-example.yaml:/etc/registryctl/config.yml -it goharbor/harbor-registryctl:v2.1.0 /bin/bash
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
2020-09-21T20:20:02Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:open : no such file or directory
2020-09-21T20:20:02Z [FATAL] [/registryctl/main.go:78]: Failed to load configurations with error: open : no such file or directory
```

**v2.0.2 working:**
```bash
$ docker run -v `pwd`/config-example.yaml:/etc/registryctl/config.yml -it goharbor/harbor-registryctl:v2.0.2 /bin/bash
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
```

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0
- docker engine version: 19.03.12
- docker-compose version: N/A

**Comment by whereismyjetpack** [comment]
I had to add the following to my registryctl config 

# /etc/registryctl/config.yml
```
registry_config: "/etc/registry/config.yml"
```

Your config example looks like a standard `/etc/registry/config.yml` and not the `/etc/registryctl/config.yml` which should look something like this 

```
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
```

Good Luck!

**Comment by wy65701436** [comment]
thanks @whereismyjetpack for the comment, registryctl does not support the standard distribution configuration file.

@fl-max please just refer to the https://github.com/goharbor/harbor/blob/release-2.1.0/src/registryctl/config_test.yml.

**Comment by fl-max** [comment]
Hmm, didn't see any mention of an additional "registryctl" config that points to a "standard" config in the [Docs](https://goharbor.io/docs/1.10/install-config/configure-yml-file/) which subsequently links to [Registry Configuration Reference](https://docs.docker.com/registry/configuration/#storage) with examples (which I gave in my original post).

Also, the Helm Chart is mounting the same configuration in both places [here](https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-dpl.yaml#L183-L188) which has worked before v2.1.0. So I assumed that since everything worked fine in <v2.1.0 that it was some bug in this latest version.

Will try with this new registrctl config.

**Comment by fl-max** [comment]
I figured out the issue. Is `registry_config` a new property or was it default in previous versions in `/etc/registryctl/config.yml`?

In `v1.4.2` of the Helm Chart, this property is non-existent which was causing the Pod to fail: https://github.com/goharbor/harbor-helm/blob/v1.4.2/templates/registry/registry-cm.yaml#L195

This is fixed in the [master branch](https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-cm.yaml#L224) from a [commit](https://github.com/goharbor/harbor-helm/commit/ee8e41d7d8da9fb9db783975b8a86e739316f82a) in July. Will open an issue there. Thx

**Comment by whereismyjetpack** [comment]
@fl-max  I had the same issue, i think that parameter is required for 1.2.1, but not 1.2.0, the fix is in the master branch, and when https://github.com/goharbor/harbor-helm/pull/735 is merged the issue will sort itself out.
