### ISSUE TITLE
Can not push image with error retrying.

### ISSUE THREAD

**Issue by aurorazl** [goharbor/harbor#13135]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

I check /var/log/harbor/ and there is error in core.log and postgresql.log:

tail -f /var/log/harbor/postgresql.log
Sep 22 12:28:36 172.22.0.1 postgresql[29352]: LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": Permission denied
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  database system was interrupted; last known up at 2020-09-22 12:27:14 UTC
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  database system was not properly shut down; automatic recovery in progress
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  invalid record length at 0/1D7EBB0: wanted 24, got 0
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  redo is not required
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  MultiXact member wraparound protections are now enabled
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  database system is ready to accept connections
Sep 22 12:29:24 172.23.0.1 postgresql[29352]: LOG:  autovacuum launcher started
Sep 22 12:29:27 172.23.0.1 postgresql[29352]: LOG:  incomplete startup packet
Sep 22 12:29:28 172.23.0.1 postgresql[29352]: LOG:  incomplete startup packet
Sep 22 12:31:05 172.23.0.1 postgresql[29352]: ERROR:  MultiXactId 2127 has not been created yet -- apparent wraparound
Sep 22 12:31:05 172.23.0.1 postgresql[29352]: STATEMENT:  SELECT "id", "reference", "reference_id", "used", "creation_time", "update_time" FROM "quota_usage" WHERE "reference" = $1 AND "reference_id" = $2 FOR UPDATE

tail -f /var/log/harbor/core.log
Sep 22 12:31:13 172.23.0.1 core[29352]: 2020/09/22 12:31:13.065 #033[1;44m[D]#033[0m [transaction.go:62]  |    10.31.3.188|#033[97;42m 202 #033[0m| 2.264493514s|   match|#033[97;42m PATCH   #033[0m /v2/sz_gongdianju/apulistech/kfserving-manager/blobs/uploads/77eb7157-0ba3-4fae-989f-993eef28e81b   r:/v2/*/blobs/uploads/:session_id
Sep 22 12:31:13 172.23.0.1 core[29352]: 2020-09-22T12:31:13Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"UNKNOWN","message":"unknown: pq: MultiXactId 2127 has not been created yet -- apparent wraparound"}]}

**Comment by bitsf** [comment]
it seems your disk is full or maybe in readonly status from the error log, and pg db is crashed, you should try recovery db first.
