### ISSUE TITLE
Tracking issue: Blog post for 2.3 release

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#13136]
This is a tracking issue to ensure we have a blog going out together with the 2.2 release, explaining new features and functionality.

- [ ] Assigned blog author
- [ ] Blog drafted
- [ ] Blog reviewed
- [ ] Blog published

**Comment by xaleeks** [comment]
This implies delaying the release potentially for the blog.  Is that really preferred to getting the release out as soon as it's ready?

**Comment by a-mccarthy** [comment]
@xaleeks are you able to work on this for 2.3?
