### ISSUE TITLE
harbor 2.0 API authorize admin user with invalid password

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#13138]
Harbor API allow admin user to login using invalid password.

**Comment by bitsf** [comment]
@dbenduga which API

**Comment by dbenduga** [comment]
harbor swagger 2.0
<img width="528" alt="harbor api" src="https://user-images.githubusercontent.com/52532360/94793072-8e0db300-03f7-11eb-9e23-505f5d6273b7.PNG">

**Comment by heww** [comment]
hi @AllForNothing can we disable the session for the developer center when customers provide their custom basic authorization?

![image](https://user-images.githubusercontent.com/5634205/95722219-3c421400-0ca6-11eb-84d4-f3dc05c7c6c6.png)

**Comment by AllForNothing** [comment]
@dbenduga 
Authorization  in Harbor API center UI  is invalid. 
In fact, you can visit it without login,  as Harbor API center is doc for all Harbor user

**Comment by heww** [comment]
We will do the following to resolve this issue:

1. Disable the cookie for the swagger ui
2. Make the authorization works

**Comment by AllForNothing** [comment]
> We will do the following to resolve this issue:
> 
> 1. Disable the cookie in the swagger ui
> 2. Make the authorization works

1.  As the related cookie is "httponly", we can not disable them. 
2.  The authorization works after logging out Harbor
