### ISSUE TITLE
Sometimes unhealthy state when creating preheat provider instance

### ISSUE THREAD

**Issue by DevHan2020** [goharbor/harbor#13148]
The same Dragonfly supernode, when Harbor configuring HTTP is healthy.
But after configuring HTTPS, Status is Unhealthy.

**Version**

- Harbor v2.1.0
- dragonflyoss/supernode:1.0.6

**Comment by bitsf** [comment]
maybe the endpoint doesn't support https yet, check the core.log

**Comment by DevHan2020** [comment]
> 端点可能不支持https，或者使用无法验证的自签名证书，请检查core.log

Thank you,question is resolve but i did nothing.
The core.log have error 'context deadline exceeded (Client.Timeout exceeded while awaiting headers)'.
If the problem occurs again, I will check the log again.
