### ISSUE TITLE
Immutable Helm Charts

### ISSUE THREAD

**Issue by kfirfer** [goharbor/harbor#13146]
Hello

Per this conversation about Immutable repository: #3413
Would be nice to see immutable helm charts

**Comment by mot256** [comment]
This feature will be much appreciated. It will help protect against multiple (or incorrect) runs of a CI/CD pipeline, that will potentially override a version.

**Comment by wy65701436** [comment]
Harbor supports user to set immutable rule for OCI compatible chart, please try this. And the chartmuseum is planned to deprecated.
