### ISSUE TITLE
LDAP error when adding group member

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [goharbor/harbor#13145]
Hi,

When I try to add an LDAP  group as member of a project we got the following error on harbor-core container

`
[ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Failed to add project member, error: LDAP Result Code 4 \"Size Limit Exceeded\": "}]}
`

**Version:** Harbor 2.1.0

**Comment by bitsf** [comment]
this error message is actually from ldap not harbor, you can also check if your LDAP has any limitation to prevent query users.

**Comment by p3t3rp3pp3r** [comment]
Thanks @bitsf for the reply,
We are using harbor v.1.10 with the same configuration since last year and we never got this issues, we experienced for the first time this issue during the migration from v.1.10 to v.2.1.0 (currently a mirror of the v.1.10) but also on v.2.0.3

Pietro

**Comment by langlois-michael** [comment]
Having the same issue after upgrading from 2.0.1 to v2.1.0... Any updates on a possible fix?

**Comment by p3t3rp3pp3r** [comment]
Hi @langlois-michael,
Some people is trying to find a workaround in the #13156 issue, but none of these works for me, I hope it can help you.

**Comment by gar0t0** [comment]
Having the same issue after upgrade from 1.10 to 2.0.3 to 2.1.0

**Comment by langlois-michael** [comment]
> Having the same issue after upgrade from 1.10 to 2.0.3 to 2.1.0

I had to rollback my production environment.... Restoring the postgres database as well...I'm hoping that a new build fixes this issue soon and we aren't stuck with this issue for good.

**Comment by stonezdj** [comment]
It is fixed in Harbor 2.1.1 by PR #13267
