### ISSUE TITLE
Newly pulled artifacts in a ProxyCache project have no Pull Time

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#13152]
**Expected behavior and actual behavior:**
When pulling an image from a ProxyCache project that doesn't exist in the cache, the image gets pulled from the upstream registry and served to the client, however the Pull Time for this image is not updated (Pull Time remains empty), if the image is not pulled again by another client it will be marked for deletion by the default retention rule since it meets the criteria "wasn't pulled during last 7 days".

I would expect to the Pull Time (and Pull Count ?) to be updated during the initial load of the artifact when the `proxy-cache-service` creates the artifact in the ProxyCache project.

**Steps to reproduce the problem:**

1. Create a ProxyCache project (we used a Docker Hub registry endpoint)
2. pull only once an image that doesn't currently exist in the Project repos
3. make sure the image is pulled by the client and can be seen in the Project's repositories
4. notice that Pull Time has an empty value
5. run a DRY RUN for the project's default retention rule and check the log, this image should have a `DEL` retention result.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0
- docker engine version: 19.03.12
- docker-compose version: 1.27.2

**Additional context:**

N/A, happy to provide additional info as requested.

/cc @jonasrosland following our slack chat.

**Comment by dkulchinsky** [comment]
some additional info here, upon additional testing we noticed the following sequence of events:
1. immediately after pulling the image, it appears in the UI with a `Pull Time` == `Push Time`
2. at this point, there's no `folder` link for the OCI manifest and Tags are missing
3. after some time, the Tag information if added as well as the OCI manifest, at this time we see the following log entries:
```
[harbor-core-5c85497bc8-ppmq7 core] 2020-09-24T18:16:33Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'InternalArtifact' on topic 'PUSH_ARTIFACT': ID-11, Repository-dockerhub/library/postgres Tags-[13] Digest-sha256:ac7aace981ed96301669471d317d0397a797d7798477a954b6c5f78fccd2ca33 Operator-harbor#proxy-cache-service OccurAt-2020-09-24 18:16:33
[harbor-core-5c85497bc8-ppmq7 core] 2020-09-24T18:16:33Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'AuditLog' on topic 'PUSH_ARTIFACT': ID-11, Repository-dockerhub/library/postgres Tags-[13] Digest-sha256:ac7aace981ed96301669471d317d0397a797d7798477a954b6c5f78fccd2ca33 Operator-harbor#proxy-cache-service OccurAt-2020-09-24 18:16:33
[harbor-core-5c85497bc8-ppmq7 core] 2020-09-24T18:16:33Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'ArtifactWebhook' on topic 'PUSH_ARTIFACT': ID-11, Repository-dockerhub/library/postgres Tags-[13] Digest-sha256:ac7aace981ed96301669471d317d0397a797d7798477a954b6c5f78fccd2ca33 Operator-harbor#proxy-cache-service OccurAt-2020-09-24 18:16:33
[harbor-core-5c85497bc8-ppmq7 core] 2020-09-24T18:16:33Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'Replication' on topic 'PUSH_ARTIFACT': ID-11, Repository-dockerhub/library/postgres Tags-[13] Digest-sha256:ac7aace981ed96301669471d317d0397a797d7798477a954b6c5f78fccd2ca33 Operator-harbor#proxy-cache-service OccurAt-2020-09-24 18:16:33
[harbor-core-5c85497bc8-ppmq7 core] 2020-09-24T18:16:33Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'P2PPreheat' on topic 'PUSH_ARTIFACT': ID-11, Repository-dockerhub/library/postgres Tags-[13] Digest-sha256:ac7aace981ed96301669471d317d0397a797d7798477a954b6c5f78fccd2ca33 Operator-harbor#proxy-cache-service OccurAt-2020-09-24 18:16:33
```
4. once that happens, the `Pull Time` becomes empty

hope this helps, as I understand things the cached artifacts are processed asynchronously to create their OCI manifest and Tag information, when this happens the `Pull Time` gets nullified it seems.

**Comment by steven-zou** [comment]
@dkulchinsky We'll take a look. Thanks for reporting the issue.

cc @stonezdj

**Comment by xaleeks** [comment]
@a-mccarthy Hey Abbie, please add this to the docs if you find it useful

**Comment by a-mccarthy** [comment]
@xaleeks i dont think we need to add docs for this, since this seems like a fix to the expected behavior.
