### ISSUE TITLE
镜像推送问题

### ISSUE THREAD

**Issue by ruirui9** [goharbor/harbor#13150]
What can we help you?
我今天安装完harbor2.0后，无法推送镜像至仓库
Error response from daemon: Get https://39.97.18.16/v2/: dial tcp 39.97.18.16:443: connect: connection refused
我问别人他们搭建好就可以用命令行登录的，我用的是源码安装无法登陆和推送镜像

**Comment by bitsf** [comment]
docker ps 看看容器是不是都起来了，另外尝试重启一下 docker restart nginx
