### ISSUE TITLE
Pull-though Image Pulls dont get triggered if container is asking for a new, non-cached Image

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#13153]
**Expected behavior and actual behavior:**

Expected: pull-trough works, if new images are asked for they get fetchhed from docker-hub and served

Actual behaviour:
We are running our k8s-nodes with containerd.
We switched from replication jobs that push to a project to a pull-trough project named docker-hub.
If an containerd-Host tries to pull an Image that isnt jet precached the image will not be replicated and not be pulled from docker-hub, thus the pull from harbor fails.
If the Image has been pulled by another host, that is not running containerd the image pull works just fine.

**Steps to reproduce the problem:**
Setup an (k8s)host with containerd
Create an project configured as pull-trough
Try to pull an non-cached image

**Versions:**
- harbor version: 2.1.0
- Containerd 1.3.4 and 1.4.0 (most likely more)

**Additional context:**

- **Log files:** Sadly i cant attach the full file, but this are the related (bascally everything 0 to 5s after such an request) lines for such an request:
proxy:
```
Sep 24 20:16:52 172.28.0.1 proxy[10687]: 10.27.50.43 - "HEAD /v2/docker-hub/beats/filebeat/manifests/7.5.1 HTTP/1.1" 401 0 "-" "containerd/v1.3.4" 0.002 0.004 .
Sep 24 20:16:52 172.28.0.1 proxy[10687]: 10.27.50.43 - "GET /service/token?scope=repository%3Abeats%2Ffilebeat%3Apull&scope=repository%3Adocker-hub%2Fbeats%2Ffilebeat%3Apull&service=harbor-registry HTTP/1.1" 200 1012 "-" "Go-http-client/1.1" 0.023 0.020 .
Sep 24 20:16:52 172.28.0.1 proxy[10687]: 10.27.50.43 - "HEAD /v2/docker-hub/beats/filebeat/manifests/7.5.1 HTTP/1.1" 404 0 "-" "containerd/v1.3.4" 0.004 0.004 .
```

core:
```
Sep 24 20:16:52 172.28.0.1 core[10687]: 2020-09-24T18:16:52Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="2f267340-92f3-490c-b5e0-b703d3e7f7da"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts
```
The other logs dont have lines for that timestamp.

**Comment by reasonerjt** [comment]
OK...
This seems a valid issue, b/c containerd will send HEAD to registry, if there's 404 it will fail directly.  
If the client does not send GET to Harbor, Harbor will not start to proxy the content.

I currently don't think of a good solution for this scenario... we may discuss this limitation under this thread.

cc @xaleeks

**Comment by stonezdj** [comment]
The current proxy rely on the registry.Client to check the existence of Manifest or Blob, they are sending HEAD request to Harbor
https://github.com/goharbor/harbor/blob/c3fde4e483a1fdcc7a4cd4c0407007406d622790/src/pkg/registry/client.go#L245
https://github.com/goharbor/harbor/blob/c3fde4e483a1fdcc7a4cd4c0407007406d622790/src/pkg/registry/client.go#L336
If need to proxy the HEAD request, these API is incorrect, because they are proxied HEAD request, then it should use local API to check existence instead of HEAD request.

**Comment by reasonerjt** [comment]
@stonezdj 
The  API can behave differently if the HEAD is sent to a regular project or `proxy-cache` project?

**Comment by djpbessems** [comment]
This affects any default K3s installation, since it relies by default on containerd: https://rancher.com/docs/k3s/latest/en/advanced/#using-docker-as-the-container-runtime.

So in case this still needs reproducing, you can probably do this relatively fast with K3s.

**Comment by stonezdj** [comment]
> @stonezdj
> The API can behave differently if the HEAD is sent to a regular project or `proxy-cache` project?

yes

**Comment by MaxRink** [comment]
I actually have foudn some images where my precaching via docker so containerd can find them doesnt work:
all calico images "misbehave" in that regard ( e.g.  calico/cni:v3.16.1 )
