### ISSUE TITLE
ldap group filter 

### ISSUE THREAD

**Issue by takyon77** [goharbor/harbor#13156]
Hi,

until Harbor 2.0, in Harbor configuration, I never set the fields 'LDAP Group Base DN' and 'LDAP Group Filter' but I was still able to add and use LDAP groups in Harbor.
Using the same config in Harbor 2.1, I can't add a LDAP group and I have the following error in the logs:

Sep 24 13:48:08 172.18.0.1 core[1723]: 2020-09-24T18:48:08Z [ERROR] [/common/utils/ldap/ldap.go:302]: Wrong filter format, filter:()
Sep 24 13:48:08 172.18.0.1 core[1723]: 2020-09-24T18:48:08Z [WARNING] [/core/auth/ldap/ldap.go:208]: ldap search group fail: invalid filter syntax

I am able to login with a LDAP user so the user LDAP config seems OK

So is the LDAP group filter is now required or is that a bug?

Thanks,

Chris.

**Comment by bitsf** [comment]
seems relative to https://github.com/goharbor/harbor/pull/13009

**Comment by stonezdj** [comment]
Workaround: set a ldap group search filter like that 
`(cn=*)`
or
`(uid=*)`

**Comment by kuznetsovkk** [comment]
I have the same problem.

==> core.log <==
Sep 25 13:08:15 172.20.0.1 core[35069]: 2020-09-25T10:08:15Z [WARNING] [/core/api/usergroup.go:54]: failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax

Tried to set LDAP Group Filter to:
- empty
- (cn=*)
- cn=*
- (uid=*)
- uid=*

nothing helps

**Comment by takyon77** [comment]
Setting only 'LDAP Group Filter' to (cn=*) was not working for me, I got the following error:

ldap search group fail: LDAP Result Code 4 "Size Limit Exceeded":

So I was able to go around the problem by setting 'LDAP Group Filter' to '(cn=*)' **and** 'LDAP Group Base DN' to the value of my groups' DN without the CN. From the tests I did, it seems that both values are necessary. Also the tests **seems** to show that the group DN is case sensitive when creating the group but once the group is created, the whole group DN is displayed in small letters which is confusing...
I'm definitely not a LDAP guy so not sure if this whole behavior is a bug or a feature...

**Comment by bitsf** [comment]
it seems https://github.com/goharbor/harbor/issues/13145 also report "Size Limit Exceeded" error

**Comment by steven-zou** [comment]
duplicated with #13140

**Comment by kuznetsovkk** [comment]
Found a workaround:
```
LDAP Group Filter: cn=*
LDAP Group GID: cn
```
This solution works for me.

**Comment by p3t3rp3pp3r** [comment]
> Found a workaround:
> 
> ```
> LDAP Group Filter: cn=*
> LDAP Group GID: cn
> ```
> 
> This solution works for me.

Not for me, I got always the error:
ldap search group fail: LDAP Result Code 4 "Size Limit Exceeded":

**Comment by stonezdj** [comment]
Sorry, the ldap filter should be more specific to limit the row size < 1000, for example `(&(cn=groupname1)(cn=groupname2))`

**Comment by p-alexisv** [comment]
The workaround LDAP group filter must be using the OR operator though. `'(|(cn=groupname1)(cn=groupname2))'`

**Comment by p3t3rp3pp3r** [comment]
None of the workarounds proposed by @stonezdj and @p-alexisv work in my environment.
the error in both cases is the following:

`2020-10-18T20:17:53Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Failed to add project member, error: Failed to searh ldap group with groupDN:cn=devgroup,ou=groups,dc=companynet,dc=com"}]}
`

**Comment by gar0t0** [comment]
Hello there.
I've two LDAP Group errors like that:

==> /var/log/harbor/core.log <==
Oct 21 16:01:21 172.27.0.1 core[16931]: 2020-10-21T16:01:21Z [WARNING] [/core/api/usergroup.go:54]: failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Oct 21 16:01:21 172.27.0.1 core[16931]: 2020-10-21T16:01:21Z [WARNING] [/core/auth/ldap/ldap.go:208]: ldap search group fail: LDAP Result Code 4 "Size Limit Exceeded": 


I think is the same problem or correlated

Same problem using harbor 2.0.1 and 2.1, I saw that problem are solved in 2.0.3, but I dont know why that problem in 2.1.0

**Comment by xaleeks** [comment]
@a-mccarthy not sure if this should go in ldap section of the docs, or maybe we can add this to the FAQ

**Comment by a-mccarthy** [comment]
@xaleeks please make an issue in the website repo with more info on the improvements to the ldap docs you'd like :)
