### ISSUE TITLE
Changing user scope settings with curl

### ISSUE THREAD

**Issue by robojones** [goharbor/harbor#13167]
How can I change user scope settings for LDAP using the CLI?

I found [this docs page](https://github.com/goharbor/website/blob/master/docs/install-config/configure-user-settings-cli.md) which seems to be outdated as the example `curl` command results in a `404`. When looking around in the Harbor code I found that the route should be `/api/v2.0/configurations` instead of `/api/configurations`.

Now I am facing the next problem: authentication errors. The basic auth mentioned in the docs does no longer work. I get CSRF errors because of the new CSRF security with [gorilla-csrf](https://github.com/gorilla/csrf) and there is no option to disable it (#12348).

This might also be related to #13124.

Help would be greatly appreciated!

**Comment by bitsf** [comment]
thanks for pointing the doc issue, I opened https://github.com/goharbor/website/issues/116 to track.

you don't need to pass csrf token in curl

**Comment by robojones** [comment]
Thanks @bitsf :smiley:
