### ISSUE TITLE
The gc time is too long. Is there a way to cancel the GC task?

### ISSUE THREAD

**Issue by ysicing** [goharbor/harbor#13161]
The gc time is too long. Is there a way to cancel the GC task?
So far, the GC task is not over, almost 12 hours old?
Is there any way to solve this problem, which results in the online mirror library being unable to use push mirroring?

**Comment by ysicing** [comment]
Or where can I see the relevant logs?

**Comment by ysicing** [comment]
Oh, my god. it's finally done.

**Comment by wy65701436** [comment]
what version are you using？If the version is v2.0.0 or previous, yes, it may take long time to execute a gc, especially on the cloud based storage. And it's no way to stop gc as it may disrupt data.

did you try the non-blocking GC(Harbor v2.1), it can reduce the gc execution time, and allows use to push/pull/deleting during GC.

**Comment by ysicing** [comment]
version: v1.10.1.
