### ISSUE TITLE
GetProjectByID sql statement

### ISSUE THREAD

**Issue by hfutwangfei** [goharbor/harbor#13188]
https://github.com/goharbor/harbor/blob/master/src/common/dao/project.go#L83

```
...
sql := `select p.project_id, p.name, p.registry_id, u.username as owner_name, p.owner_id, p.creation_time, p.update_time
	from project p left join harbor_user u on p.owner_id = u.user_id where p.deleted = false and p.project_id = ?`
queryParam := make([]interface{}, 1)
queryParam = append(queryParam, id)

p := []models.Project{}
count, err := o.Raw(sql, queryParam).QueryRows(&p)
...
```

In this sql statement, there is only one param, but queryParam will includes two elements, nil and id.
I don't know much about the use of queryParam. I think we can just use queryParam like this:

```
...
sql := `select p.project_id, p.name, p.registry_id, u.username as owner_name, p.owner_id, p.creation_time, p.update_time
	from project p left join harbor_user u on p.owner_id = u.user_id where p.deleted = false and p.project_id = ?`
p := []models.Project{}
count, err := o.Raw(sql, id).QueryRows(&p)
...
```

**Comment by hfutwangfei** [comment]
https://github.com/goharbor/harbor/blob/master/src/vendor/github.com/astaxie/beego/orm/db_utils.go#L63

Here, I find the unnecessary param is ignored. But it is still wrong use.

**Comment by heww** [comment]
Hi, @hfutwangfei thanks for your suggestion. Yes, you are right about the description of the `GetProjectByID` function. 

We will remove the `core/promgr` pkg which is the only place to use the `GetProjectByID` function in the master branch now in v2.2.x. See #13408 to get more information to remove `core/promgr`. After this PR merged, `GetProjectByID` will be removed from the code.

Thanks again for this issue.
