### ISSUE TITLE
Add a Switch to Control if Enable the Metrics in Docker Registry

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#13181]
- [x] rendering metrics related config based on Harbor metric config

**Comment by xaleeks** [comment]
where is this switch exactly? @ninjadq

**Comment by ninjadq** [comment]
Actually the switch is an bool value item in `harbor.yml`

**Comment by a-mccarthy** [comment]
@xaleeks @ninjadq, just wanted to confirm, was it decided not to do this? i don't see a PR linked, and I want to make sure there are no docs updates to make. thanks!
