### ISSUE TITLE
Add speed limit for replication job

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#13194]
currently replication job does not have any network speed limitation, and it is using several workers to do jobs concurrently, usually it will occupy too much bandwidth.
So we can consider add a speed limiter for each replication job.
The speed limiter can be a global setting in harbor.yml for now.
In future it may be extend to project level or job level.

There're several methods to do this, we can simply use package `golang.org/x/time/rate`.
```
func NewReader(r io.Reader, s float64) io.Reader {
	l := rate.NewLimiter(rate.Limit(s), 100*1024)
	return &reader{
		r:       r,
		limiter: l,
	}
}

func (r *reader) Read(buf []byte) (int, error) {
	n, err := r.r.Read(buf)
	if n <= 0 {
		return n, err
	}
	now := time.Now()
	rv := r.limiter.ReserveN(now, n)
	if !rv.OK() {
		return 0, fmt.Errorf("exceeds limiter's burst")
	}
	delay := rv.DelayFrom(now)
	time.Sleep(delay)
	return n, err
}
```

**Comment by bitsf** [comment]
waiting PM's PRD to determine design scope

**Comment by xaleeks** [comment]
we need to think about UX.  We need to limit both ingress and egress.  I don't think this is in scope for v2.2
