### ISSUE TITLE
Customize the text of the OIDC login button

### ISSUE THREAD

**Issue by thoro** [goharbor/harbor#13198]
**Is your feature request related to a problem? Please describe.**
Users might be confused if they are presented with an OIDC login button and are used to "Company SSO", most software supports to customize the text of the login links.

For example:

"Login with Dex"
"Login with Okta"
"Login with SSO"

etc.

**Describe the solution you'd like**
The OIDC provider should have a field to define the text presented on the UI.

**Comment by reasonerjt** [comment]
Since we have the name of OIDC provider we may render the button dynamically? 
cc @xaleeks @AllForNothing

**Comment by Thoro** [comment]
Even though my samples all give the prefix "Login with", I would let the whole text to be decided, without a static portion!

**Comment by xaleeks** [comment]
I'm ok with this.

**Comment by AllForNothing** [comment]
@reasonerjt As discussed, the provider name will be provided in the response of "systeminfo" API

**Comment by rgarcia89** [comment]
Any update here?

**Comment by VladoPortos** [comment]
Would be nice to have.
