### ISSUE TITLE
LDAP authentication not working

### ISSUE THREAD

**Issue by ruben-herold** [goharbor/harbor#13206]
Versions:
Please specify the versions of following systems.

    harbor version: v2.1.0-a3eca103
    docker engine version: 19.03.13, build 4484c46d9d
    docker-compose version: 1.27.4, build 40524192

I try to authenticate via our active directory services. So I try the minimal configuration at first:

 Auth Mode:  LDAP
 LDAP URL :  ldap://dc01.ourdomain.de
 LDAP Search DN : CN=harbor ,OU=Service Accounts,DC=subdomain,DC=domain,DC=de
 LDAP Search Password: $ourbadaspassword
 LDAP Base DN: DC=subdomain,DC=domain,DC=de
 LDAP UID: sAMAccountName

LDAP Verify Certificate off

all other settings default.

On Test I got only internal error. The logfile said:

Oct  1 16:37:23 172.18.0.1 core[13118]: 2020-10-01T14:37:23Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"LDAP connect fail, error: LDAP Result Code 200 \"\": dial tcp: i/o timeout"}]} 
Oct  1 16:37:23 172.18.0.1 core[13118]: /harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
Oct  1 16:37:23 172.18.0.1 core[13118]: /harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
Oct  1 16:37:23 172.18.0.1 core[13118]: /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
Oct  1 16:37:23 172.18.0.1 core[13118]: /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
Oct  1 16:37:23 172.18.0.1 core[13118]: /harbor/src/core/api/ldap.go:103, github.com/goharbor/harbor/src/core/api.(*LdapAPI).Ping

If I do an docker exec -it ba41e2edb48a /bin/bash into the core container I can reach the ldap server via:
curl telnet://dc01.ourdomain.de:389 without any problems

**Comment by eric-gunn** [comment]
@ruben-herold We're having the same issue. Have you found anything else out since?

**Comment by ruben-herold** [comment]
@eric-gunn no and no feedback from others

**Comment by stonezdj** [comment]
The LDAP result code 200 means ErrorNetwork

**Comment by stonezdj** [comment]
dup https://github.com/goharbor/harbor/issues/12296
