### ISSUE TITLE
Upgrade golang-migrate to latest stable version

### ISSUE THREAD

**Issue by jsuchome** [goharbor/harbor#13208]
Notary images are using quite late version of golang-migrate, 3.5.4. This one is not using any of latest go packaging techniques (go.mod is missing).
So I suggest to bump the version to latest stable one.

What I did for testing the change:

1. deployed Harbor 2.0 with upstream (photon based) images for notary
2. pulled, pushed and signed one image into my registry
3. upgraded my Harbor installation, only thing I changed was switching notary images to the ones based on SUSE and using 4.12.2 version of golang-migrate in there.
4. nothing seems to be broken, no migration errors in notary pods for example.

This might not be relevant to cover what is needed to test, let me know how can I test more specificaly

**Comment by reasonerjt** [comment]
Closing as it's been bumped up to v4.
