### ISSUE TITLE
Deploy Harbor image repository on NFS share - problem

### ISSUE THREAD

**Issue by giladk1221** [goharbor/harbor#13209]
Hi,
I need to define the harbor server on nfs server.
/database - include all data(database and etc)
/data - include all repositories

I tried to add in harbor.yml file:
storage_service:
  filesystem:
    rootdirectory: /data

This is doesn’t work.

Please give me any good solution to define the repositories directory on NFS share(/data) and all other files and PostgreSQL database in different directory(/database)

Docker version: 19.03.13
Docker compose: 1.27.4
Harbor version: v1.10.3

Waiting for response,

Gilad

**Comment by steven-zou** [comment]
@ninjadq 

Please take a look. Thanks!

**Comment by system51** [comment]
@giladk1221  I think you don’t need `/database` because we use external databases redis and postgresql and don’t need to be enabled it because your NFS is already mounted locally
```
storage_service:
  filesystem:
    rootdirectory: /data
```

**Comment by geewhizsmith** [comment]
Hello, I had the same or a very similar problem, and have an explanation and steps to make it work.

The "install.sh" and "prepare" or the templates they use do not account for the
setting of a "rootdirectory", and so no "volume" is set in "docker-compose.yml"
to enable the setting to work.

To make it work with my setup I did this...

    1) configure "rootdirectory" to point to my mounted NFS storage:
        harbor.yml
            storage_service:
              filesystem:
                rootdirectory: /mnt/storage/harbor-registry
                maxthreads: 100

    2) run the installation script and shut the installation down (it was running but could not store files)
        sudo ./install.sh
        sudo docker compose down --volumes

    3) add configuration for the volume (and make a backup of the file in case somebody ran the base "install.sh")
        sudo vi docker-compose.yml
            services:
              registry:
                volumes:
                  - /mnt/storage/harbor-registry:/mnt/storage/harbor-registry
        sudo cp docker-compose.yml docker-compose.yml-EDITED_BACKUP

    4) and start it again
        sudo docker compose up --detach

And in my README for the service, I put a warning on the restart notes:

    diff docker-compose.yml docker-compose.yml-EDITED_BACKUP || echo "WARNING:  docker-compose.yml does is different from docker-compose.yml-EDITED_BACKUP"
    sudo docker compose down --volumes
    sudo docker compose up --detach

I am going to open a new issue, but I wanted to drop this comment on a number of
threads where other people might find it while tring to do a fix of their own.
