### ISSUE TITLE
E-mail configuration did not work without authentication data

### ISSUE THREAD

**Issue by ruben-herold** [goharbor/harbor#13205]
**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0-a3eca103
- docker engine version: 19.03.13, build 4484c46d9d
- docker-compose version: 1.27.4, build 40524192

If I try to configure the email settings, I enter:

Email Server: $my.$domain.tld
Email Server Port: 25
Email Username
Email Password
Email From $my@$domain.tld
Email SSL 
Verify Certificate

As you can see I disabled Verify Certificate and Email SSL. Also Email Username and Email Password is left blank.
After saving I try to test it and the log on the mailserver said:

Oct  1 16:12:54 mail postfix/smtpd[21689]: connect from harbor01.test.de[XXXX:XXXX:1:9::1:9]
Oct  1 16:12:54 mail postfix/smtpd[21689]: Anonymous TLS connection established from harbor01.test.de[XXXX:XXXX0:1:9::1:9]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Oct  1 16:12:56 mail postfix/smtpd[21689]: warning: harbor01.test.de[XXXX:XXXX:1:9::1:9]: SASL PLAIN authentication failed: 
Oct  1 16:12:56 mail postfix/smtpd[21689]: disconnect from harbor01.test.de[XXXX:XXXX:1:9::1:9] ehlo=2 starttls=1 auth=0/1 quit=1 unknown=0/1 commands=4/6

Seems that it ever try to use smtp auth even if username and pass is empty

**Comment by steven-zou** [comment]
cc @stonezdj
