### ISSUE TITLE
Quay.io pull fuzzy name not working

### ISSUE THREAD

**Issue by funzie19** [goharbor/harbor#13200]
**Expected behavior and actual behavior:**
`company/**` sync up all repositories from Quay.io into Harbor

**Steps to reproduce the problem:**
- Setup a registry to Quay.io
- Setup a replication rule.
-- Use registry create before
-- Set as pull
-- Set name: `company/**`
-- Set destination
- Run replication
-- Replication will fail with:
```failed to fetch artifacts: http status code: 400, body: {"errors":[{"code":"INVALID_REQUEST","detail":{},"message":"Unable to decode repository and actions: registry:catalog:*"}]}```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.0

**Additional context:**
- Harbor is running in a GKE cluster
- Pulling `company/name` works as expected.

**Comment by mfld** [comment]
good suggestion
+1

**Comment by steven-zou** [comment]
@chlins 
Please take a look at this issue. Thanks!

**Comment by chlins** [comment]
@funzie19 Can you try to configure the pattern of company/{repo1, repo2} and check if it can work well ?

**Comment by mfld** [comment]
hello, just wanted to voice my concern.

Even though "company/{repo1,repo2}"  might work, it will be hard to maintain for companies with lots of repositories listed on quay. Please add support for fuzzy names.

**Comment by chlins** [comment]
@mfld The pattern of "company/{repo1,repo2}" just help to find out the problem. Not mean we do not fix the fuzzy name like  company/**.  Our ultimate goal must be fuzzy pattern can work well(prerequisites:  with auth mode).

**Comment by xaleeks** [comment]
@a-mccarthy please note this change in the docs

**Comment by a-mccarthy** [comment]
@xaleeks i dont think this needs more docs than what is already on the site. let me know if i'm misunderstanding things
