### ISSUE TITLE
unable to delete tag using restapi

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#13203]
https://aus-harbor-sjctest.bmc.com/api/v2.0/projects/core-remedy/repositories/remedy%252Faronly/artifacts/sha256%3Acb3880cf41004260d8fd0cb795e3d1a6da89ffdad393d34facba37657f116bff/tags/1808-HF1

----- Error------
{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "CSRF token invalid"
    }
  ]

**Comment by dbenduga** [comment]
Using Harbor 2.1.0 version

**Comment by steven-zou** [comment]
@dbenduga 

Please paste your curl command here.

Moreover, you can refer the FAQ doc shown [here](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#api) to fire an API  request.

**Comment by dbenduga** [comment]
I have tried both tag and artifact deletion API however getting same error message.

Please see below curl command 

###TAG##
curl -X DELETE "https://pun-harbor-02.bmc.com/api/v2.0/projects/dipesh/repositories/alpine/artifacts/latest/tags/latest" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46Ym1jQWRtMW4="

##artifact##
curl -X DELETE "https://pun-harbor-02.bmc.com/api/v2.0/projects/dipesh/repositories/alpine/artifacts/latest" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46Ym1jQWRtMW4="

**Comment by ywk253100** [comment]
```
yinw-a01:dev yinw$ curl -X DELETE -i -u username:password "https://demo.goharbor.io/api/v2.0/projects/library/repositories/hello-world/artifacts/latest/tags/latest"
HTTP/2 200
date: Fri, 13 Nov 2020 06:23:30 GMT
content-length: 0
server: nginx
set-cookie: sid=763c91d0a26a80e803aaf263467e6711; Path=/; Secure; HttpOnly
x-request-id: 8d3bd61c-97da-480b-845b-43abdc360c93
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: DENY
content-security-policy: frame-ancestors 'none'
```
