### ISSUE TITLE
mkdir permission denied when docker push image to harbor

### ISSUE THREAD

**Issue by giladk1221** [goharbor/harbor#13214]
Hi,
I added this lines to harbor.yml to store the repositories on nfs server(/data):

storage_service:
  ca_bundle:
  filesystem:
    rootdirectory: /data/registry
  redirect:
    disabled: false

the deployment finished successfully.
after that i connected to the harbor with the command: docker login

trying to push image to the harbor and got this:

e41010411a8f: Retrying in 1 second
f88b6ac4df7e: Retrying in 1 second
6cee2ca3272c: Retrying in 1 second
840eaa67357d: Retrying in 1 second
872a1466e826: Retrying in 1 second

after take a look in the registry log(registry contanier) i got this error:
 level=error msg="response completed with error" auth.user.name=admin err.code=unknown err.detail="filesystem: mkdir /data: permission denied" 

if i removed the lines for storage service in the harbor.yml everything working fine and pushing images finished without any problem.

im tried to connect to the registry contanier and create directory and i have the same problem - permission denied.
i tried to add permission to some folders but the problem still exist.

what i need to do for reslove this issue?

waiting for your advice,
Thanks

docker version: 19.03.13
docker-compose version: 1.27.4
harbor version: v1.10.3

**Comment by catchups** [comment]
When you push an image into the registry, the registry creates a directory named after the image's Hash. Check the system permissions for docker

**Comment by system51** [comment]
How to contact you

**Comment by SamyakGangwal** [comment]
I am having the exact same issue. Has anyone solved this problem?
