### ISSUE TITLE
Setting to allow Trivy to work in an air-gapped environment needs to be exposed in tile

### ISSUE THREAD

**Issue by techgnosis** [goharbor/harbor#13218]
**Is your feature request related to a problem? Please describe.**
The Harbor tile includes the Trivy container vulnerability scanner. Out of the box, the Trivy scanner expects to be able to reach the internet to pull down its vulnerability database. There is no setting to change this in the tile, but you can change this setting in a config file on the Harbor VM. The settings works, however it does not persist across Apply Changes. 

**Describe the solution you'd like**
I would like a section in the Harbor tile that allows you to set Trivy to not reach out to the internet. This would require that you put trivy.db and metadata.json at the right location on disk (see Additional Context below).

_The most important part here is that there is already a workaround that fixes the problem. It just doesn't persist across Apply Changes. It needs to be an official setting so it doesn't continue to be a hack._

**Describe the main design/architecture of your solution**
A single setting in the tile. A checkbox that says "Do not reach out to the internet for Trivy DB". Or anything like that. The checkbox sets the "skip_update" property to "true".

**Additional context**
The setting "skip_update" is in /var/vcap/jobs/harbor/config/harbor.yml

trivy.db and metadata.json need to be inside /var/vcap/store/harbor/trivy-adapter/trivy/db/

**Comment by xaleeks** [comment]
Can we get this in for v2.2 tile? @stonezdj

**Comment by stonezdj** [comment]
Close it, we have tracked it in jira, we'd discuss tile product issue in jira.

**Comment by xaleeks** [comment]
what PKS ticket is this,please link it here.  I didn't find any ticket that addresses the issue of not persisting across apply changes.

**Comment by stonezdj** [comment]
Already provide a workaround in Harbor Tile 2.2.1
