### ISSUE TITLE
High postrgres connection and CPU after upgrading to 1.10.5

### ISSUE THREAD

**Issue by stephenwolfe1** [goharbor/harbor#13226]
**Expected behavior and actual behavior:**
After upgrading to 1.10.5 from 1.10.0 we have seen major database issues when viewing repositories with a large tag count, trying to dry run retention rules, or running retention rules. We were running an r4.large aurora instance for over a year with minimal CPU usage. After upgrading clicked on one of our larger repositories that had about 10k tags and the RDS instance connection count shot up to over 4k and CPU pegged at 100%. This never recovered and AWS eventually stopped/rebooted the instance. Added an additional replica and increased both to r4.2xlarge instances but have continued to see high connection and CPU issues doing anything around these larger repositories. Added retention rules at night and executed them; which have been running for 1-2 days depending on the repo at a very slow pace. Stopped the 3 running rules due to intermittent docker cli connection errors and database connections spiked to over 15k. The external database config has been deployed with the default setting of 100 max open connections.

Expected:
Max open connections setting is respected
Reliable way to manage view large repo's without crashing the DB
Reliable way to prune large repo's without crashing the DB or running for days or weeks

**Steps to reproduce the problem:**
Create a project with a large amount of tags, 1k+
View the tags in the UI and watch DB performance
Start a dry run or execute a retention rule and watch DB performance

**Versions:**
- harbor version: [1.10.5]
- kubernetes version: [1.17.11]

**Additional context:**
Dry run example:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/38081080/95499388-0de8cf80-095a-11eb-8765-d2cd1ef19af2.png">

Execution example:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/38081080/95499452-248f2680-095a-11eb-8c23-d46ee2cb6c54.png">

**Comment by yanji09** [comment]
In 2.x, there is a setting to limit the db connections.
Recommend you to upgrade Harbor to latest version.

**Comment by heww** [comment]
Hi, @stephenwolfe1 We release the 1.10.6 today. In this version, the max open db connections can be limited in the harbor core component, and we also limited to goroutines when process the list tags API. Could you try to upgrade your harbor instance to v1.10.6?
