### ISSUE TITLE
Obtain CLI Secret through API?

### ISSUE THREAD

**Issue by brianmajor** [goharbor/harbor#13221]
I have seen the PUT endpoint in the API for setting a user's CLI Secret but I am looking for an endpoint to download (GET) a user's CLI Secret.

We are running Harbor in OIDC auth mode.  

The use case is to dynamically set imagePullSecrets in kubernetes for user who have provided their idToken.  We'd like to the use idToken to access the Harbor CLI secret to obtain private images from the Harbor registry.

Harbor version: 2.0.2-debian-10-r0
Docker image: docker.io/bitnami/harbor-core:2.0.2-debian-10-r0

**Comment by reasonerjt** [comment]
You can get it in the response of API to query user's profile, for example:
```
~# curl -u "admin:Harbor12345" https://jt-dev.local.goharbor.io/api/v2.0/users/3 -k|jq .oidc_user_meta.secret
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   635  100   635    0     0   3128      0 --:--:-- --:--:-- --:--:--  3128
"1MKzzTfYH5z9ZdUtVfNhEm125ZqVoIdj"
```

**Comment by brianmajor** [comment]
Perfect, thanks.
