### ISSUE TITLE
curl harbor /v2/_catalog api hang out and no return

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#13229]
What can we help you?

harbor version: v2.0.1

When execute the command `curl -k -X GET -u admin:Harbor12345 https://xxx.harbor.cn/v2/_catalog`, the request hangs and never responds. And the cpu usage of database will increase a lot.

The size of the data:

table of artifact: `select count(*) from artifact`, ~10000+
table of repository: `select count(*) from repository`, ~1000+

**Comment by yuluxs007** [comment]
I have the same problem. Have you found the reason ？

**Comment by chlins** [comment]
Not yet.

**Comment by harryleesan** [comment]
I am also experiencing the same problem.

I get a "504 Gateway Timeout" when trying to run _catalog.

table of artifact: `select count(*) from artifact` 30328
table of repository: `select count(*) from repository` 1455

**Comment by wy65701436** [comment]
clost it as fixed by PR https://github.com/goharbor/harbor/pull/14120
