### ISSUE TITLE
image cannot can be replicated from harbor version 1. X to harbor version 2.1

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#13237]
image cannot can be replicated from harbor version 1. X to harbor version 2.1.
when replicate images from  version 1. X to harbor version 2.1, report 404 error.
The API in error is still in the old format. Is this format not compatible in harbor 2.1?
    POST /api/projects HTTP/1.1
    Host: 10.41.5.187:80
    User-Agent: harbor-replication-service
    Content-Length: 57
    Authorization: Basic ****************
    Content-Type: application/json
    Accept-Encoding: gzip

**Comment by yanji09** [comment]
Harbor doesn't support replication from low version to high version.
