### ISSUE TITLE
Mixed authentication (LDAP + "arbitrary" users)

### ISSUE THREAD

**Issue by It4lik** [goharbor/harbor#1323]
Hi, 

I got a specific use-case that make me think about that : what about mixed authentication ? 
I mean, in my organization, we got a LDAP server used as an authentication backend for various services. So cool, Harbor supports it. But if LDAP is enabled, I can't arbitrary add other users. What if I want to open my service to both my LDAP users, and some others ? 

Regards, It4.

**Comment by yhua123** [comment]
Hi It4,
Sorry, no recent plan to support mixed authentication.
How to resolve duplicate username is a major problem, do you have some suggestion? Thanks~

**Comment by reasonerjt** [comment]
To support that, we can introduce some concept like "domain", and each domain maps to a ldap setup, so when login as "user1@localDB" it validates password against DB but "user1@ldap1" it fetch the configuration of "ldap1" and validate against that particular ldap.

But no, this is not on the near term plan.

**Comment by It4lik** [comment]
I like the "domain" idea. I would have suggest something like a prefix for each authentication backend. This prefix would be configurable by admins, and invisible for users. When adding a user to a project, the user should also specify the prefix. 
For us, the problem is that we got two different authentication backends for two distinct types of users (internal and external user to our enterprise)

Okay, thank you for answers anyway :)

**Comment by yhua123** [comment]
Thanks.
Will list this as a new feature request.

**Comment by bstevenson** [comment]
I think this is a similar request: https://github.com/vmware/harbor/issues/698
with a proposed solution
https://github.com/vmware/harbor/commit/182d65f79e51b139459f3c20ea433b8827d92710

I could really use the local service account feature for CICD in conjunction with ldap for users RBAC.

**Comment by nlowe** [comment]
@bstevenson Interesting but I don't see a way to create service account users. Was this abandoned / not merged?

**Comment by xaleeks** [comment]
going to mark this as won't do.  Please use a single source for external auth
