### ISSUE TITLE
configurable maxReplicators value

### ISSUE THREAD

**Issue by enajeeb** [goharbor/harbor#13245]
Trying to run replication on docker registry and getting following error. 
```
failed to fetch artifacts: failed to fetch artifacts: failed to list artifacts of repository test/actions/0abb0ca651a1b752695e16442c75e8f5e5fc916d: http status code: 429, body: {\"errors\":[{\"code\":\"TOOMANYREQUESTS\",\"message\":\"Rate-limit reached, please try again in 10 seconds\",\"detail\":null}]}
```

Can we set `maxReplicators` using `common/config/core/app.conf` https://github.com/goharbor/harbor/blob/master/src/replication/operation/controller.go#L46

**Comment by steven-zou** [comment]
Please check: https://github.com/goharbor/harbor/blob/8535ecbbe511a6b0033e68774d692c97e14ec900/make/harbor.yml.tmpl#L102

**Comment by steven-zou** [comment]
But I need to clarify that even you decrease the worker number, you still may meet the rate limitation issue from the docker hub.

**Comment by enajeeb** [comment]
Still getting TOOMANYREQUESTS error after tring with `max_job_workers: 1`. I wonder why no one else have faced this issue. Any other suggestions?

**Comment by twellspring** [comment]
I'm also running into this issue with an ECR registry. Setting maxJobWorkers to 1 also did not help. 

Without a good tagging system to use for limiting I ended creating several jobs and limiting each job to part of the alphabet (i.e. first letter of the repo name)

Name: {a**,b**,c**,d**,e**}
etc...

**Comment by twellspring** [comment]
@steven-zou Any thoughts on how to avoid getting TOOMANYREQESTS from ECR?
