### ISSUE TITLE
A switch button (or check box ) to show password when changing the password

### ISSUE THREAD

**Issue by colachg** [goharbor/harbor#13240]
**Is your feature request related to a problem? Please describe.**

Today, I change admin password with auto generated password. After that, when I login again with new password it shows that invalid username or password. I check the generated history, there is only one password.
So I think it's necessary to view what you inputed to check it.

**Describe the solution you'd like**
There is a button to click to show your password.

**Comment by AllForNothing** [comment]
@colachg
Thanks for your information.
For some security reasons,  we will not change this.
For your case, you can use browser debug mode to view the password you input:
![Uploading image.png…]()

**Comment by colachg** [comment]
I know this hack way, but don't you think is it inconvenient？ And can you tell me for what security reasons?

**Comment by AllForNothing** [comment]
Agree it is inconvenient.
