### ISSUE TITLE
[Proposal] Replication should include other Harbor settings to be replicated if recipient is Harbor instance.

### ISSUE THREAD

**Issue by DandyDeveloper** [goharbor/harbor#13246]
**Is your feature request related to a problem? Please describe.**
I did a quick search for this, I'm sure it's been requested before but I couldn't find anything. Please close if that's the case (sorry). 

It would be good if the replication supported additional objects from the Harbor database to replicate over other settings like:
* Users
* Robot Accounts
* Policies
* Labels 

Etc. Etc.

Right now, I have a number of Harbor instances that I replicate against and having to recreate and reconfigure everytime can be painful. This would also be a great option for DR scenarios. 

**Describe the solution you'd like**
I think the summary describes the request well enough. 

**Describe the main design/architecture of your solution**
I haven't looked into the code, but I guess if we add an adapter of some kind that says "If selected repository is Harbor, add options for Harbor settings" then through the backend processing of the request, add a sync cron of some kind that replicates over these settings via the Harbor API / RPC (Do we have RPC???) over the selected protocol. 

**Describe the development plan you've considered**
I will update this when I get a closer look at the areas this would affect. Right now, I don't have a good solution. 

**Additional context**
This should ultimately piggyback on the existing replication logic, this specific use case is for Harbor -> Harbor replication

**Comment by xaleeks** [comment]
Thanks @DandyDeveloper for the detailed requirement, it's already in our backlog https://github.com/goharbor/harbor/issues/7993.  I pasted it to that ticket.  We're trying to prevent from having to track multiple tickets for the same requirement.
