### ISSUE TITLE
Unable to ping the container

### ISSUE THREAD

**Issue by AlterGu** [goharbor/harbor#13243]
When finished install harbor-v2.1.0, I cannot ping the docker containers. 
harborv210_harbor's subnet is 172.19.0.0/16 and gateway is 172.19.0.1.
After ping 172.19.0.10(nginx) ，system request "From 172.19.0.1 icmp_seq=1 Destination Host Unreachable"
WHY?

**Comment by itsecforu** [comment]
check ur cluster network logs

**Comment by AlterGu** [comment]
> check ur cluster network logs

how can I check my cluster network logs
