### ISSUE TITLE
[OIDC] login with preferred_username fails

### ISSUE THREAD

**Issue by bsctl** [goharbor/harbor#13269]
Logging with OIDC. We use `preferred_username` as claim for Username Claim without specify the email. Harbor logs first user but further login attempts with other usernames are denied with the following message: `"{"errors":[{"code":"CONFLICT","message":"Conflict, the user with same username or email has been onboarded."}]}"`.

**Expected behavior and actual behavior:**
It looks Harbor wants the `email` as unique user identifier for OIDC users. We expect to use the `preferred_username` only

**Steps to reproduce the problem:**
1. Provision OIDC login in Harbor

`curl -k -X PUT "https://harbor.example.com/api/v2.0/configurations" -H "accept: application/json" -H "Content-Type: application/json" -u "admin:Harbor12345" -d "{ \"auth_mode\": \"oidc_auth\", \"oidc_client_id\": \"harbor\", \"oidc_endpoint\": \"https://oidc.example.com\", \"oidc_groups_claim\": \"groups\", \"oidc_user_claim\": \"preferred_username\", \"oidc_name\": \"keycloak\", \"oidc_scope\": \"openid\", \"oidc_verify_cert\": \"false\", \"oidc_client_secret\": \"********\"}"`

2. Login with OIDC as user "alice": success
3. Logout
4. Login with OIDC as different user, e.g "joe": fail with the error above

An example of id_token released by the IdP is:

```
{
  "exp": 1602674724,
  "iat": 1602673824,
  "auth_time": 0,
  "jti": "*********",
  "iss": "oidc.example.com",
  "aud": "harbor",
  "sub": "***************",
  "typ": "ID",
  "azp": "harbor",
  "session_state": "***************",
  "at_hash": "**************",
  "preferred_username": "alice",
  "email_verified": false,
  "acr": "1",
  "groups": [
    "spectre"
  ],
  "client_id": "harbor",
  "username": "alice",
  "active": true
}
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.0

**Additional context:**
Harbor deployed with Helm Chart 1.5.0

**Comment by Morriz** [comment]
We have the same problem. Why is harbor feeling responsible to say something about the JWT payload? It is signed and verified, and should just accept the claims given. It might idempotently store them for internal reference if it needs to, but not bork.

So please guys, trust signed JWT and handle payload without failures.

**Comment by Morriz** [comment]
We encounter this after a fresh install of keycloak, which might send something different. Let me inspect:

- we have consistent subs, so these stay the same
- the verification secret is also the same

I don't really see anything different about the JWT actually, but something obviously is because why would harbor bork?

Again, I would assume harbor to accept the new JWT and overwrite the internal identity.

**Comment by Morriz** [comment]
Sample decode bearer token:
```json
{
  "exp": 1603987159,
  "iat": 1603987099,
  "auth_time": 1603986054,
  "jti": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "iss": "https://keycloak.our.domain/realms/master",
  "aud": "otomi",
  "sub": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "typ": "ID",
  "azp": "otomi",
  "session_state": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "acr": "0",
  "email_verified": true,
  "name": "xxx",
  "groups": [
    "create-realm",
    "offline_access",
    "admin",
    "team-otomi",
    "uma_authorization",
    "team-dev"
  ],
  "preferred_username": "",
  "given_name": "xxx,
  "family_name": "xxx",
  "email": "xxx"
}
```

**Comment by gabrilabs75** [comment]
Any news about this issue?

Thanx and regards,
Gabriele

**Comment by Morriz** [comment]
It is very likely the `SubIss` field that is storing and checking the sub coming from keycloak. This keycloak sub might change since keycloak generates them when acting as a broker for external IDPs, and as such can be deemed "stateless" and be destroyed and recreated. Please support this 12-factor way of working with ephemeral processes.

**Comment by bsctl** [comment]
Any progress?

**Comment by bsctl** [comment]
Any progress?
