### ISSUE TITLE
Registering a scanner with Authorization APIKey doesn't work

### ISSUE THREAD

**Issue by m-kostrzewa** [goharbor/harbor#13277]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Registering a scanner with Authorization APIKey doesn't work - returns `Ping: registration ts:http://XXX:8889/harbor is unreachable`, but no error in Harbor Core logs, and no request comes in Scanner adapter logs. Browser returns 400 Bad Request error.

(BTW: any error is returned as Unreachable in frontend, no matter what is the actual cause)

Expected: it works

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

```
$ helm list
my-harbor      	1       	Tue Oct  6 16:54:23 2020	DEPLOYED	harbor-1.5.0   	2.1.0
```

**Additional context:**

In Edit Scanner window
![untitled (1)](https://user-images.githubusercontent.com/9220158/96112390-d393ab00-0ee2-11eb-9374-8a87db0ebd03.png)

In Harbor Core logs: nothing

Browser reports 400 Bad Request
![Screenshot from 2020-10-15 12-31-31](https://user-images.githubusercontent.com/9220158/96112408-dabab900-0ee2-11eb-8af7-d7d536c6c4f7.png)

Request payload:
```
{"name":"ts","description":"","url":"http://IP:8889/harbor","auth":"APIKey","access_credential":"asdf","skip_certVerify":false,"use_internal_addr":false}
```

**Why**

https://github.com/goharbor/harbor/blob/8a0e8627ff5cbafd09c6436ca0911db97f6748de/src/pkg/scan/rest/auth/auth.go#L24-L54

Code expects field 	`X-ScannerAdapter-API-Key`, but frontend sends `APIKey`

**Comment by steven-zou** [comment]
@chlins will try to fix it
