### ISSUE TITLE
Clair scan the image hourly even though it is set to none

### ISSUE THREAD

**Issue by benjamincao** [goharbor/harbor#13281]
What can we help you?
I continued to suffer from the issue as bellow:
![image](https://user-images.githubusercontent.com/1814862/96206887-79572080-0f9c-11eb-9364-3c1a0b08d392.png)
I didnot set the garbage collection and set scanner to None.

Have no idea for the reason.
After checking the logs, I find Clair scanner to run hourly, and the mode is set to read only.
And I could not delete the Clair, it just reponsed that "registration %s is not allowed to delete as it is immutable: scanner API: delete"
How can I disable the scanner? or just make the limit of the happening of read only mode a little less?

**Comment by steven-zou** [comment]
@benjamincao 

What's your harbor version?

For a workaround, you can disable read-only mode on the system configuration page.

The read-only mode can only be set by the GC job. Would you please check if you have created a scheduled GC task and try to reset it if it exists?

**Comment by steven-zou** [comment]
@benjamincao 

Please check if this FAQ can help you. https://github.com/goharbor/harbor/wiki/Harbor-FAQs#stuck-in-read-only-mode

**Comment by steven-zou** [comment]
Close and reopen when necessary.
