### ISSUE TITLE
could not get NVD data feed 

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#13284]
Harbor version : 1.9.4

getting below error message in clair.log.

Oct 16 13:24:55 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:55.169532","data feed name":"2015","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2015.meta failed status code: 404"}
Oct 16 13:24:55 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:55.431630","data feed name":"2016","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2016.meta failed status code: 404"}
Oct 16 13:24:55 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:55.688011","data feed name":"2017","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2017.meta failed status code: 404"}
Oct 16 13:24:55 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:55.945410","data feed name":"2018","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta failed status code: 404"}
Oct 16 13:24:56 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:56.234419","data feed name":"2019","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.meta failed status code: 404"}
Oct 16 13:24:56 10.104.1.1 clair[16934]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-16 07:54:56.507757","data feed name":"2020","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2020.meta failed status

**Comment by wy65701436** [comment]
dup with https://github.com/goharbor/harbor/issues/13212
