### ISSUE TITLE
push images   received unexpected http status 504 gateway time-out

### ISSUE THREAD

**Issue by wangdwcsd** [goharbor/harbor#13307]
When I push a image  to a project  A ，received unexpected http status 504 gateway time-out

![image](https://user-images.githubusercontent.com/28424375/96531678-c7319880-12bc-11eb-8741-240ea09fb2bd.png)

but When I push a image  to a project  B,    this is ok

![image](https://user-images.githubusercontent.com/28424375/96531880-38714b80-12bd-11eb-9bf1-e15544bef441.png)

Using glusterfs as the storage of harbor

**Comment by ninjadq** [comment]
Could you provide more information and log files?
