### ISSUE TITLE
GarbageCollection on Proxy Cache projects

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#13314]
How doe Garbage collection work for proxy cache projects with Quota limit?

Is there any documentation, could not find it...

**Comment by wy65701436** [comment]
GC and Quote don't do any extra scenario on the proxy cache projects, same as normal project.

**Comment by MrD2** [comment]
What happens if  the proxy quota reaches its limit?

Does the project delete the least pulled / least recent pulled / the oldest image.

What is the procedure?

**Comment by xaleeks** [comment]
It does not delete the image automatically, only the '7 days until last pulled' retention policy is enforced at all times.  If cache is still topped up when there's a pull request from the upstream, it will be rejected as it's just treated as a push

**Comment by xaleeks** [comment]
Hi Abbie, please highlight this behavior in the docs @a-mccarthy
