### ISSUE TITLE
使用helm3向harbor1.7.5上传charts时报错：x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by hanzhc** [goharbor/harbor#13321]
使用helm3向harbor1.7.5上传charts时报错：x509: certificate signed by unknown authority
helm3的版本为3.3.4
harbor访问方式采用https，自签TLS证书，已经在/etc/cert.d中将相关证书填入。通过docker login登录镜像库及docker push均能正常操作，且无证书的报错。

当执行 `helm chart push registry.mirrors.com/test/wordpress:v1.9.2 --debug`，报错信息如下：

> helm chart push registry.mirrors.com/test/wordpress:v1.9.2 --debug
The push refers to repository [registry.mirrors.com/test/wordpress]
ref:     registry.mirrors.com/test/wordpress:v1.9.2
digest:  15ac502e6b3db2291e02700227b61770b03c418abdc732c03a75a3f5af237a0f
size:    37.6 KiB
name:    wordpress
version: 9.0.3
WARN[0000] encountered unknown type application/tar+gzip; children may not be fetched 
DEBU[0000] push                                          digest="sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e" mediatype=application/tar+gzip size=38508
WARN[0000] reference for unknown type: application/tar+gzip  digest="sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e" mediatype=application/tar+gzip size=38508
DEBU[0000] checking and pushing to                       digest="sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e" mediatype=application/tar+gzip size=38508 url="https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e"
DEBU[0000] do request                                    digest="sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e" mediatype=application/tar+gzip request.header.accept="application/tar+gzip, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=38508 url="https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:3e3477f82ac148a32317da7178dc582b9274a410899dc0cdf857af107b2a2f4e"
WARN[0000] encountered unknown type application/vnd.cncf.helm.config.v1+json; children may not be fetched 
DEBU[0000] push                                          digest="sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0" mediatype=application/vnd.cncf.helm.config.v1+json size=615
WARN[0000] reference for unknown type: application/vnd.cncf.helm.config.v1+json  digest="sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0" mediatype=application/vnd.cncf.helm.config.v1+json size=615
DEBU[0000] checking and pushing to                       digest="sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0" mediatype=application/vnd.cncf.helm.config.v1+json size=615 url="https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0"
DEBU[0000] do request                                    digest="sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0" mediatype=application/vnd.cncf.helm.config.v1+json request.header.accept="application/vnd.cncf.helm.config.v1+json, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=615 url="https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0"
Error: failed to do request: Head "https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0": x509: certificate signed by unknown authority
helm.go:94: [debug] Head "https://registry.mirrors.com/v2/test/wordpress/blobs/sha256:15a25b6a1b05c45ba7f05b40122535fb9a070b8e7f8decf3da14942e4b0b72a0": x509: certificate signed by unknown authority
failed to do request
github.com/containerd/containerd/remotes/docker.(*request).do
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/docker/resolver.go:513
github.com/containerd/containerd/remotes/docker.(*request).doWithRetries
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/docker/resolver.go:520
github.com/containerd/containerd/remotes/docker.dockerPusher.Push
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/docker/pusher.go:87
github.com/containerd/containerd/remotes.push
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:154
github.com/containerd/containerd/remotes.PushHandler.func1
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:146
github.com/containerd/containerd/images.HandlerFunc.Handle
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/images/handlers.go:54
github.com/containerd/containerd/images.Handlers.func1
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/images/handlers.go:64
github.com/containerd/containerd/images.HandlerFunc.Handle
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/images/handlers.go:54
github.com/containerd/containerd/images.Dispatch.func1
	/go/pkg/mod/github.com/containerd/containerd@v1.3.4/images/handlers.go:133
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by ninjadq** [comment]
OCI registry is not supported in Harbor 1.7.5. 
If you wanna upload chart to harbor as OCI artifact, please upgrade to v2.0 or upper version
Or you need to use chart's push plugin to upload charts
