### ISSUE TITLE
Harbor replication improvement for disaster recovery

### ISSUE THREAD

**Issue by skyrain** [goharbor/harbor#13323]
**Is your feature request related to a problem? Please describe.**
I am trying to create a disaster recovery mechanism for Harbor. I have several Harbor instances in different clusters. It is very convenient that Harbor support replication for image/charts. However, it is not enough for Harbor disaster recovery. Take my case as an example:

I enabled OIDC configuration in Harbor. And I created different member groups for different projects. But Harbor cannot replicate this kind of information to another backup Harbor.

**Describe the solution you'd like**
Currently, I find some way to get around Harbor disaster recovery issue. But it is hacky from my point of view.

Production Harbor `HarborProd` using external DB `DBProd`, OIDC enabled using keycloak.

Backup Setup:
1. Start a backup Harbor instance `Harbor1` using external Database `DB1` enabled. `DB1` is doing streaming replication of `DBProd`. Thus `DB1` does NOT allow write operation directly.

2. Start a backup Harbor instance `Harbor2` .

3. Enable replication of `image` from `HarborProd` to `Harbor1`, replication of `chart` from `HarborProd` to `Harbor2`.

Disaster recovery steps:
1. promote `DB1`.
2. replicate `chart` from `Harbor2` to `Harbor1`.
3. Now `Harbor1` contains all information of production Harbor.

**Describe the main design/architecture of your solution**
The above disaster recovery step is too hacky from my point of view. And I think that it is not sustainable, as I just utilized a specific Harbor behavior in specific Harbor version. If in the future the internal design of Harbor changed, this way might mess up Harbor data some how.

Later, I find out a better way to deal with disaster recovery of Harbor with OIDC config enabled, and the rough idea is: 
1. Host each project member group info inside our own database.
2. Create a new service, calling Harbor native exposed API to create project member group for each project using the info saved in our database.

Above disaster recovery mechanism will be able to solve major info replication problem missed by current Harbor replication design, however apparently we are losing all original production Harbor's logs, and each OIDC user has to login Harbor again to register in Harbor, not to say OIDC users are losing their original CLI secrets (Although we can reset the new CLI secret as old CLI secret using Harbor native API).

**Describe the development plan you've considered**
Above is my two cents, and I DO think Harbor should be able to replicate more than image/chart as it already have such powerful functionality and versatile data itself. 

Please let me know which mechanism you guys prefer, or is there any better way to solve the issue?

**Comment by skyrain** [comment]
I read this official doc [](https://goharbor.io/docs/1.10/install-config/harbor-ha-helm/), it seems like my first `hacky` solution is official way to deal with metadata?

**Comment by ninjadq** [comment]
dup of #8709

**Comment by skyrain** [comment]
I would love to illustrate my final design of disaster recovery for Harbor cross cluster HA.

1. Start Harbor instances:
hb1: deploy with external database db1 in cluster1.
hb2: deploy with external database db2 in cluster2.
2. Replicate database:
In cluster 2, do streaming replication of db1 as db3.
3. Start event based replication from hb1 to hb2.

When disaster happens, cluster1 is down. Conduct following steps:
1. Promote db3.
2. Update hb2 pointing to db3 as external database.

Can anyone confirm the above recovery step follows Harbor original design and not violate Harbor design concept? @ninjadq

**Comment by ninjadq** [comment]
Actually replication is design for distribute images to different registry at first. But it can used for people who wanna backup data in some perspective.

If your intention is to backup the whole Harbor instance, Images and database is not enough. Cause there are other data used by Harbor. You need to backup all the files in data volume.

**Comment by skyrain** [comment]
> Actually replication is design for distribute images to different registry at first. But it can used for people who wanna backup data in some perspective.
> 
> If your intention is to backup the whole Harbor instance, Images and database is not enough. Cause there are other data used by Harbor. You need to backup all the files in data volume.

Can you provide more details what (the `other` data you mentioned) data on my above backup process miss to backup for the `whole` Harbor instance? 

In my final design, `hb2` contains all `image/charts` from `production` harbor, same for `postgres` data. And as in official doc [https://goharbor.io/docs/1.10/install-config/harbor-ha-helm/] to achieve Harbor HA all we need to do is to have HA `postgres database`, `storage - image/charts` and `redis`. As my understanding, `redis` is for session only, in terms of disaster recovery, we do not need to backup `redis`. Anything wrong in my understanding?

Thanks,
