### ISSUE TITLE
I want to move the information from server 1 to server 2. Is there a way??

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13332]
I want to back up user information/project member information in harbor.
I want to move the information from server 1 to server 2.
Is there a way??

Thank you.

**Comment by xaleeks** [comment]
not right now, unless you do raw DB updates.  Configuration replication is something on the roadmap however

**Comment by peterjc85** [comment]
@xaleeks Speaking of configuration replication, is it a function to replicate the configuration (user / member) of server 1 to server 2?
Where can I find the roadmap?

**Comment by ninjadq** [comment]
No
