### ISSUE TITLE
Harbor `pull_count` does not indicate the user from which the pull originated.

### ISSUE THREAD

**Issue by anoncam** [goharbor/harbor#13333]
What can we help you?
We have a highly regulated deployment of Harbor.  At the moment the v2 API only has `pull_count` for a repository, and `pull_count` does not get associated with the user who pulled the image.

Is this by design? Meaningful metrics and observing abuse within our registry are becoming a patched series of efforts just to make a meaningful sense of user behavior.

Thoughts?

**Comment by ninjadq** [comment]
pls check access log
