### ISSUE TITLE
The compatibility list doc is out of date

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#13344]
The compatibility list doc should be updated and the old link referred to in the readme should also be pointed to the new doc version.

**Comment by xaleeks** [comment]
@steven-zou  can you point out the specifics to @a-mccarthy ?

**Comment by steven-zou** [comment]
Double confirm: documents on the website is ok, the issue only in the readme doc

**Comment by steven-zou** [comment]
Create a PR: https://github.com/goharbor/harbor/pull/13582

**Comment by xaleeks** [comment]
please help review the new links @a-mccarthy

**Comment by a-mccarthy** [comment]
I left a comment on the PR
