### ISSUE TITLE
GitLab replication fails if "Container registry" feature disabled.

### ISSUE THREAD

**Issue by blackprowler** [goharbor/harbor#13353]
Hello Harbor team.

This issue is related to the replication process from GitLab Container Registry (GLCR) to the Harbor.
The whole replication process fails if from the set of GitLab projects that should be replicated, at least one has a "Container Registry" feature diasabled.

### Expected behavior and actual behavior:
GitLab group `"MyGitlabGroup"` contains several projects. One of the projects `"NonDockerProject"` has "Container Registry" feature **disabled**.

Harbor is configured to replicate all the docker images from `"MyGitlabGroup"` group to a respective Harbor "`GitlabReplica"` Project with rule `"MyGitlabGroup/**"`

#### Expected behavior
Harbor does the replication of all the docker images for all Projects in the GLCR `"MyGitlabGroup"` Group to Harbor `"GitlabReplica"` Project excluding (skipping) replication for the GitLab's `"MyGitlabGroup/NonDockerProject"` as API endpoint for this Project will return an Error 403 "Forbidden".

In the replication status Harbor will show some "Partially completed"

#### Actual behavior
Harbor completely fails the replication after it gets an Error 403 "Forbidden" from the GitLab for `"MyGitlabGroup/NonDockerProject"`project and not trying to replicate other ones.

### Steps to reproduce the problem:
1. Create a group in Gitlab with several projects (at least more that two).

2. All projects except one should have "Container Registry" feature **enabled**. The last one should have it **disabled**

3. Push at least one docker image for all the GitLab's projects with GLCR feature enabled

4. Configure Harbor to replicate all the projects from the GitLab's group to some Harbor's project.

5. Run the replication. It will fail

### Versions:**

- harbor version: all versions starting from 1.10
- gitlab vestion: any actual supported version (Currently v13.3+)

**Comment by bitsf** [comment]
hi, you can use `MyGitlabGroup/DockerProject/**` to point out the project.
I'm not sure how to check whether project has enabled "Container registry" by Gitlab API yet, cache 403 is not a good idea.

**Comment by blackprowler** [comment]
@bitsf, I would prefer not to have the whole replication failed, but to just skip the failed project from the replication and proceed with the next one.

Because when you have thousands of projects, not each of them need to have this feature enabled. And even when you enable it for all, it might be the case that someone will create / reconfigure a project that will not have this feature. So it will "accidentally" fail the whole working replication process.
