### ISSUE TITLE
[Inquiry] robot token sharing crossing multiple Harbor services.

### ISSUE THREAD

**Issue by drehpehs** [goharbor/harbor#13351]
Hi Sir,

I am hosting multiple Harbor services in different areas, and they have isolated DB and redis servers.

Currently I try to integrate them into one general domain service with Load balancer. But the robot token can't be shared to each other because the root.crt are different and the DB servers are separated.

I would like to know do you have any suggestion or idea for my current design?
Like using one centralized DB or sync up all secret crossing all Harbor services.
Or will you provide some features such as robot replication?

Thank you in advance.

**Comment by xaleeks** [comment]
part of your requirement is tracked here - https://github.com/goharbor/harbor/issues/9209

as to robot for syncing multiple harbor instances, it is something we've discussed, the robot token service would need to be externalized but in a safe way to do this.  There are security concerns here

**Comment by drehpehs** [comment]
@xaleeks
 
Thanks for your reply.
I checked the issue, so is it possible to have a global read/write robot account in the future?
(maybe just image push for write operation)

**Comment by wy65701436** [comment]
@drehpehs just refer to the proposal https://github.com/goharbor/community/pull/148

**Comment by wy65701436** [comment]
As 2.2 is RCed, the system level robot can cover this, close it as fixed.
