### ISSUE TITLE
Unable to add LDAP group with different letter case in DN

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#13362]
**Expected behavior and actual behavior:**
When adding LDAP Group via UI or API I get error
`LDAP Group DN is not found: DN: cn=somegroup,dc=example,dc=com` if the DN has one or more letters in different case.
I am using MS AD as LDAP.

Actual DN of the group in Microsoft AD returned by using `ldapsearch` on Linux shell: `CN=somegroup,dc=example,dc=com`

I was able to add groups with case insensitive DN in previous versions.

**Steps to reproduce the problem:**
Have a group in LDAP with DN: `CN=somegroup,dc=example,dc=com`
Try to add new Group in Harbor using DN: `cn=somegroup,dc=example,dc=com`

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.3
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

Adding group with lowercase 'cn':
```
Oct 26 13:13:39 172.19.0.1 core[1957]: 2020-10-26T12:13:39Z [DEBUG] [/common/utils/ldap/ldap.go:262]: Start to dial ldaps
Oct 26 13:13:39 172.19.0.1 core[1957]: 2020-10-26T12:13:39Z [DEBUG] [/common/utils/ldap/ldap.go:393]: Groupname: , groupDN: cn=somegroup,dc=example,dc=com
Oct 26 13:13:39 172.19.0.1 core[1957]: 2020-10-26T12:13:39Z [DEBUG] [/common/utils/ldap/ldap.go:305]: Search ldap with filter:(objectclass=group)
Oct 26 13:13:40 172.19.0.1 core[1957]: 2020-10-26T12:13:40Z [DEBUG] [/common/utils/ldap/ldap.go:320]: Found entries:24
Oct 26 13:13:40 172.19.0.1 core[1957]: 2020-10-26T12:13:40Z [DEBUG] [/server/error/error.go:58]: {"errors":[{"code":"BAD_REQUEST","message":"LDAP Group DN is not found: DN:cn=somegroup,dc=example,dc=com"}]}
```

Adding group with uppercase 'CN':
```
Oct 26 13:17:43 172.19.0.1 core[1957]: 2020-10-26T12:17:43Z [DEBUG] [/common/utils/ldap/ldap.go:262]: Start to dial ldaps
Oct 26 13:17:43 172.19.0.1 core[1957]: 2020-10-26T12:17:43Z [DEBUG] [/common/utils/ldap/ldap.go:393]: Groupname: , groupDN: CN=somegroup,dc=example,dc=com
Oct 26 13:17:43 172.19.0.1 core[1957]: 2020-10-26T12:17:43Z [DEBUG] [/common/utils/ldap/ldap.go:305]: Search ldap with filter:(objectclass=group)
Oct 26 13:17:45 172.19.0.1 core[1957]: 2020-10-26T12:17:45Z [DEBUG] [/common/utils/ldap/ldap.go:320]: Found entries:24
Oct 26 13:17:45 172.19.0.1 core[1957]: 2020-10-26T12:17:45Z [DEBUG] [/common/utils/ldap/ldap.go:413]: Current ldap entry attr name: cn
```

**Comment by stonezdj** [comment]
It seems to be an issue related to the goldap library.
https://github.com/goharbor/harbor/blob/160e22f0fed8fdf72f01ede94cdc0eec0c61916f/src/vendor/gopkg.in/ldap.v2/dn.go#L198
```
func (d *DN) AncestorOf(other *DN) bool
```
It is case senesitive. need to change to lowercase beforehand.
