### ISSUE TITLE
GitLab Replication uses incorrect project search logic

### ISSUE THREAD

**Issue by blackprowler** [goharbor/harbor#13363]
Hello Harbor team.

This issue is related to the replication process from GitLab Container Registry (GLCR) to the Harbor.
Harbor is [using](https://github.com/goharbor/harbor/blob/eed8aa91a514c47db307afa46f3e7280c21c2b30/src/replication/adapter/gitlab/client.go#L101-L108) a GitLab's [Search API](https://docs.gitlab.com/ee/api/search.html), while the [Projects API](https://docs.gitlab.com/ee/api/projects.html) and [Groups API](https://docs.gitlab.com/ee/api/groups.html) should be used.

### Expected behavior and actual behavior:
GitLab has two projects with similar names, each one of them is created under it's own specific group:
- Project name: `hugo`; Group name: `docker`; URL-encoded path: `docker%2Fhugo`
- Project name: `hugo-docs`; Group name: `public`; URL-encoded path: `public%2Fhugo-docs`

Harbor administrator creates a pull-based replication from GitLab to Harbor with the following settings:
- GitLab SRC project: `docker/hugo`
- Harbor DST project: `GitlabReplica`

#### Expected behavior
Harbor does the replication of all the docker images for GitLab's project `docker/hugo`.

#### Actual behavior
Harbor uses the Search API of GitLab and seeks for the `hugo` project.
GitLab returns two projects (`docker/hugo`, `public/hugo-docs`) as the result of the search instead of one (`docker/hugo`) if Project API would be used.
Harbor is evaluating the result and checks each project for the available tags.

In case the issue #13353 apply to this case, the whole replication might fail.

### Steps to reproduce the problem:
1. Create GitLab groups: `docker`, `public`
2. Create GitLab project `docker / hugo`
3. Push some images into a `docker / hugo` GLCR.
4. Create GitLab project: `public / hugo-docs`. Disable the"Container Registry" feature for this project.
5. Create "pull" replication in Harbor with the following settings:
5.1. GitLab SRC project: `docker/hugo`
5.2. Harbor DST project: `GitlabReplica`
6. Run the replication. It should fail because of the combination of this issue and #13353.

### Versions:
- harbor version: all versions starting from 1.10
- gitlab version: any actual supported version (Currently v13.3+)

**Comment by bitsf** [comment]
hi, I'm not quite understand, for step 5.1, even search api is used now, it still can filter out the project `docker/hugo`, why would `publi/hugo-docs` be hit ?

**Comment by blackprowler** [comment]
Hi @bitsf ,
GitLab will return a list of all the repositories that match the query.
Harbor will start to process the replication for all of those projects returned by the GitLab search query.

This is what I caught in my test environment.

**Comment by bitsf** [comment]
seems also relative to #13797

**Comment by hlubek** [comment]
> seems also relative to #13797

The widened search would still return too many projects (which then could fail replication if container registry is not enabled). This can only be solved if an iteration approach over groups / subgroups / projects is implemented correctly.
