### ISSUE TITLE
Missing field of insecure when updating instance

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#13369]
There is no `insecure` field in preheat instances API.

**API:**
PUT  /api/v2.0/p2p/preheat/instances/_instance_sname_

payload:
 `{"auth_mode":"BASIC","description":"qqq","enabled":true,"endpoint":"http://1.1.1.3","id":1,"name":"instance_sname","setup_timestamp":1603784885,"status":"Unknown","vendor":"dragonfly"}`

**API:**
GET  https://10.158.214.19/api/v2.0/p2p/preheat/instances

payload:
`{"auth_mode":"BASIC","description":"qqq","enabled":true,"endpoint":"http://1.1.1.2","id":1,"name":"instance_sname","setup_timestamp":1603784885,"status":"Unknown","vendor":"dragonfly"}`

**Harbor version:**
1. 2.1.0;
2. master

![image](https://user-images.githubusercontent.com/44018302/97386964-ffb22180-190f-11eb-82d5-34bab3d83884.png)

`

**Comment by reasonerjt** [comment]
What if you check the check box?

**Comment by AllForNothing** [comment]
UI fixing for this issue #13376 on master(2.2)

**Comment by chlins** [comment]
Backend fixing for this issue https://github.com/goharbor/harbor/pull/13380 to master(2.2) and cherry-pick https://github.com/goharbor/harbor/pull/13381 to 2.1
