### ISSUE TITLE
我想咨询下，harbor仓库能否从一些其它类型的docker仓库中同步出镜像

### ISSUE THREAD

**Issue by lowenitt** [goharbor/harbor#1337]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by hainingzhang** [comment]
Currently, importing images from other registry is not supported. Do you have any registry in mind to export images to Harbor?

**Comment by reasonerjt** [comment]
pull-based replication let's track it by #580 in the backlog
