### ISSUE TITLE
harbor http_auth mode can not push images although it was able to land successfully

### ISSUE THREAD

**Issue by hyypan** [goharbor/harbor#13371]
Error response from daemon: unauthorized: unauthorized to access repository: test/nginx, action: push: unauthorized to access repository: test/nginx, action: push

The image cannot be pushed unless the user has a group，You can't push an image without a user group even if you add a user to the project

src/core/service/token/authutils.go:105 ->  filter function always make actions An empty array . 
I've changed this code. Make it always return a non-empty array to push the image

**Comment by reasonerjt** [comment]
http_auth mode was introduced for internal integration, so there's no good documentation.
line 105 is in an  `if err!=nil` condition.

**Comment by hyypan** [comment]
Why will http_auth mode not be supported in the future ？

**Comment by hyypan** [comment]
> http_auth mode was introduced for internal integration, so there's no good documentation. Make sure you understand how the code works.
> This auth mode may be removed in future releases.
> 
> line 105 is in an `if err!=nil` condition.

Why will http_auth mode not be supported in the future

**Comment by hyypan** [comment]
> > http_auth mode was introduced for internal integration, so there's no good documentation. Make sure you understand how the code works.
> > This auth mode may be removed in future releases.
> > line 105 is in an `if err!=nil` condition.
> 
> Why will http_auth mode not be supported in the future

I want to do a private third party authentication service based on Harbor, which plan is more reasonable

**Comment by reasonerjt** [comment]
OIDC/LDAP
