### ISSUE TITLE
No location returned in POST instance response header message

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#13378]
No location returned in POST instance response header message, so can't get instance id from it.

![image](https://user-images.githubusercontent.com/44018302/97403040-a73e4c80-192e-11eb-8bef-7e22ea79abf2.png)

**Comment by AllForNothing** [comment]
@chlins Here is an example of adding a new project, the response contains a header "location"
![image](https://user-images.githubusercontent.com/30999793/97514950-e7eba380-19ca-11eb-8672-d15c94448469.png)
