### ISSUE TITLE
Robot users should be able to sync private projects (Harbor -> Harbor)

### ISSUE THREAD

**Issue by ChristianCiach** [goharbor/harbor#13384]
I am trying to replicate a private repository from Harbor to Harbor (both using version 2.1.1) by using pull-based replication.

As you can see, my source-project contains images on multiple levels:

![grafik](https://user-images.githubusercontent.com/19341644/97495074-86deb400-1967-11eb-8179-7fa99b06c2d1.png)

On  the target side, I configure this registry by using "Provider: Harbor" and using the credentials of the robot user:

![grafik](https://user-images.githubusercontent.com/19341644/97495474-f785d080-1967-11eb-8ea8-d1fdada9a77b.png)

Then, still on the target side, I configure the pull-based replication:

![grafik](https://user-images.githubusercontent.com/19341644/97495973-99a5b880-1968-11eb-8940-f8d28e1fc1b2.png)

But no matter what I put into the "Source resource filter", Harbor won't even replicate a single image. There is no error when running the replication, just a false success message that appears almost immediately:

![grafik](https://user-images.githubusercontent.com/19341644/97496274-0620b780-1969-11eb-8242-8bf43ec37bf7.png)

When using a regular user instead of a robot user, everything works as expected. Is this a known limitation of robot users?

**Versions:**

- harbor version: 2.1.1

**Comment by ChristianCiach** [comment]
Observation: When I add a completely "public" project and leave the replication-filter empty, the replication will successfully find and replicate this images stored inside the public project. This is strange. Why can the robot-user see the images of the public project, but is unable to see the images of the private project that the robot-user explicitly belongs to?

**Comment by xaleeks** [comment]
you configured a pull based replication (from harbor A to harbor B) on harbor B using the credentials of the robot account that belongs to the project on harbor A.  Is this right? just making sure @ChristianCiach

**Comment by ChristianCiach** [comment]
That's exactly right.

**Comment by xaleeks** [comment]
I thought neither are supported, are you sure you're replicating images successfully with a public project? @ChristianCiach 

replication policies cannot leverage robot tokens right? @wy65701436

**Comment by ChristianCiach** [comment]
> I thought neither are supported

Can  you please elaborate on that?

> are you sure you're replicating images successfully with a public project?

Absolutely! In fact, we have two pull-based replication jobs configured at "harbor B". One one replicated the public project called "public" from harbor A, the other one replicates the private job called "shnetz" (see screenshots above) from harbor A. Unfortunately, the second job (for "shnetz") only works when configuring it using a non-robot user. This feels wrong, because this user is only ever used by a robot (Harbor B).

> replication policies cannot leverage robot tokens right?

I know this question isn't targeted at me, but why shouldn't robot tokens be used for that? In fact, I would expect this to be one of the primary use-cases of robot users.

**Comment by oliverbutanowitz** [comment]
@xaleeks 
I can confirm the same issue here using 2 Harbor Instances 2.1.1.
>  are you sure you're replicating images successfully with a public project?

All public projects are replicated within harbor B, but the "Private Projekt, having the assignment of robot$user" is not replicated.

**Comment by ChristianCiach** [comment]
I didn't test it, but according to the release notes, this should now work with Harbor 2.4.0.
