### ISSUE TITLE
Tag Immutability Permissions of Master Role in Harbor is inconsistent with the Document

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#13389]
Maintainer role can create/edit/delete the rules on immutability tab
![image](https://user-images.githubusercontent.com/1069785/97540872-35820380-19ff-11eb-80e4-3ee48754c6dd.png)

But in Harbor Document the maintainer doesn't have it.

![image](https://user-images.githubusercontent.com/1069785/97540636-df14c500-19fe-11eb-9321-33e891de4ac0.png)

We need to update the doc

**Comment by xaleeks** [comment]
@a-mccarthy please make correction to docs

**Comment by a-mccarthy** [comment]
@xaleeks can you please provide more context here? Is this a new ability for this role, should we only fix this in the latest version, or all versions? The docs list the role as Master, but the UI screen shot shows Maintainer, should we also update the docs to say Maintainer here? Thanks!

**Comment by ninjadq** [comment]
hi, @a-mccarthy it's not a new abilities, the role have these abilities all the way.

**Comment by xaleeks** [comment]
@a-mccarthy basically the permissions displayed here https://goharbor.io/docs/1.10/administration/managing-users/user-permissions-by-role/ are inaccurate.  The ss is showing that the maintainer role can infact create / edit / delete.  We should only update for the versions since tag immutability was released, which would be >= v1.10

**Comment by xaleeks** [comment]
yes, if you are seeing 'master' elsewhere in docs, please update it to say 'maintainer'.  and not just in reference to roles, if you see the word 'master' anywhere, please flag it so we can address it. Thx

**Comment by a-mccarthy** [comment]
thanks @xaleeks and @ninjadq for the information, i opened a PR on the website repo to update this, https://github.com/goharbor/website/pull/145
