### ISSUE TITLE
Get the ID token from Azure OIDC provider and then call the API example 

### ISSUE THREAD

**Issue by pingcrosby** [goharbor/harbor#13383]
What can we help you?

I have Harbor and Azure OIDC working ...

However to invoke an api via curl for example are there any example on how to get the ID token from OIDC provider and then  call the API 

Am struggling to find any documentation on the process / steps

Can anyone point me in the correct direction.. 

If harbor is using OIDC do i need a token via `authorize`, or can I just invoke the api with a user : password copied from the user profile. 

Is the "basic workflow"...
```
    GET https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}/oauth2/v2.0/authorize?
client_id=XXXX
&response_type=code%20id_token&response_mode=form_post&scope=openid%20offline_access
&state=arbitrary_data_you_can_receive_in_the_response&nonce=12345

Then using the token retrieved use that to access the API
```
```
This doesnt work - but maybe im calling it wrong

password=passwordXXX # the cli secret from my userprofile 
username=ausernameXXX # userprofile name
HOST=http://harbor-host

# base64 it
auth=$(echo "$username:$password" | base64)
curl -X POST \
     -H "Content-type: application/json" \
     -H "authorization: Basic $auth" \
     -v \
     -k -i -d '{"data": "example"}'  "https://$HOST/api/v2.0/system/scanAll/schedule" \

```

**Comment by pingcrosby** [comment]
tried with a token.. (token looks ok) and again no luck

401 unauthorised
```
rawtoken=$(curl -v \
--location \
--request POST 'https://login.microsoftonline.com/{ tenant }/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode "client_id={ client-id }" \
--data-urlencode "client_secret={ secret }" \
--data-urlencode "resource=api://{ resource}" )

token=$(echo $rawtoken  | jq -r ".access_token")

curl -X POST \
     -H "Content-type: application/json" \
     -H "Authorization: Bearer $token" \
     -v \
     -k -i -d '{"data": "example"}'  "https://$HOST/api/v2.0/system/scanAll/schedule"

```

**Comment by reasonerjt** [comment]
@pingcrosby you should get the id token instead of access_token.

Have you tried
```
token=$(echo $rawtoken  | jq -r ".id_token")
```

**Comment by pingcrosby** [comment]
Sadly there is no id_token in the response..

Can someone confirm the exact flow / provide a concrete example of calling an API v2 when using OIDC.

According to the MS docs the code below should return an id_token and it does in a browser if i am already logged into Harbor (eg in the browser ive clicked [ Login With OIDC ]

So put simply - how do i achieve the same as a non-interactive login.. eg
  ```
   Is this the correct flow....?
   login somehow with my creds .. HOW??? and grab some session info for the next call to "https://login.microsoftonline.com/< tenant >/oauth2/authorize" and ask for an id_token
```

```
The url generated by this curl does return an id_token .. but only if i paste the url into a browser after i have logged into harbor interactively.

 curl  -G \
 --data-urlencode "client_id=< my id >" \
 --data-urlencode "response_type=id_token" \
 --data-urlencode "response_mode=form_post" \
 --data-urlencode "scope=openid" \
 --data-urlencode "state={ what should this be }" \
"https://login.microsoftonline.com/< tenant >/oauth2/authorize"
```

**Comment by pingcrosby** [comment]
https://github.com/goharbor/harbor/issues/10597#issuecomment-603159112

This reference from the doc uses a [ password ] flow and the docs also say "login in via the UI" which is clearly not what i want to do if i need to call APIs non-interactively.. It would seem there is some confusion around this so - can it be more clearly documented..

So what would be the equiv flow in Azure AD to this

``` url = "https://[$KEYCLOAK_URL]/auth/realms/[$REALM]/protocol/openid-connect/token"
    data = {'grant_type': 'password', 'client_id': '[$HARBOR_CLIENT_NAME]', 'client_secret': '[REDACTED]',
            'scope': 'openid', 'username': '[$USER_NAME]', 'password': '[$USER_PASSWORD]'}
    response = requests.post(url, data=data)```

Ive tried the above changing the url to mosfts equivalent and again no success - in curl im redirected always to login first

**Comment by pingcrosby** [comment]
More information on this; working curl here..

https://github.com/goharbor/harbor/issues/13683#issuecomment-739036574

**Comment by reasonerjt** [comment]
Thanks @pingcrosby, now since you have figured out I assume this issue can be closed?

Sorry I didn't have the bandwidth (nor account) to try on azure myself

**Comment by pingcrosby** [comment]
Yes it can be closed 
Hope it helps others
