### ISSUE TITLE
http_auth not work correctly

### ISSUE THREAD

**Issue by xvdy** [goharbor/harbor#13388]
**Expected behavior and actual behavior:**
User generated by http_auth can't push image, even add user to project member with manager role.

**Steps to reproduce the problem:**
1. set auth mode to http_auth
2. docker login with some user // we name it user1 for convenience.
3. create a project named test
4. add user1 to project as member with manager role
5. docker push harbor.com/test/python:3.8 and it wrongs here:

```
Error response from daemon: unauthorized: unauthorized to access repository: test/python, action: push: unauthorized to access repository: test/python, action: push
```

**Versions:**
harbor-offline-installer-v2.1.0.tgz

- harbor version: [v2.1.0]
- docker engine version: [18.09.4]
- docker-compose version: [1.27.4]

**Additional context:**

If need more info ask me.

**Comment by reasonerjt** [comment]
1. There's no manager role
2. I strongly suggest not use http_auth, which was introduced historically for integration.  
Please continue the discussion in #13371
