### ISSUE TITLE
I want to install harbor in  K8s‘s cluster

### ISSUE THREAD

**Issue by Goend** [goharbor/harbor#13400]
harbor version: v1.5.0
k8s version : v1.14.3
i dont need too hign version to break my own project about this,but if i installed it by my own,i can't find some useful instructions,i dont want to install it by helm . please give me some useful tips ,thanks a lot

**Comment by lyyao09** [comment]
refer to [kubernetes_deployment](https://github.com/goharbor/harbor/blob/release-1.5.0/docs/kubernetes_deployment.md).

**Comment by Goend** [comment]
thanks a lot,![image](https://user-images.githubusercontent.com/40394339/97822646-90fb0c80-1cf1-11eb-90e3-2c8af822599a.png),if i want to usr Clair ,what should i do?

**Comment by ninjadq** [comment]
you can try harbor chart or operator to install in K8S
