### ISSUE TITLE
1 click vulnerability data export

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#13405]
As a project admin, I would like to 1 click export all vulnerability data for my project in csv format.  We have APIs for retrieving data, but there is additional value from export functionality.  This is an opportunistic requirement however

As a user (any role), I would like to 1 click export all vulnerability data for the projects that I'm entitled to

**Comment by dioguerra** [comment]
@stonezdj can close this, it's released in v2.6.x

**Comment by chlins** [comment]
Closed as delivered in v2.6.
