### ISSUE TITLE
"failed to migrate: Dirty database version 40. Fix and force version" during a fresh installation

### ISSUE THREAD

**Issue by biello** [goharbor/harbor#13403]
when I'm installing harbor by helm follow this doc https://goharbor.io/docs/2.1.0/administration/, the harbor core keeps report this log and restarting...

![image](https://user-images.githubusercontent.com/11658142/97674604-c4a71e00-1ac8-11eb-9f51-73936d5b3f5c.png)

it's really confusing in a totally fresh installation with empty databases and fresh new disk.

**Comment by ninjadq** [comment]
could you provide more information like how you install Harbor

**Comment by biello** [comment]
> could you provide more information like how you install Harbor and the logs of core's

Thank you for replying. I installed using helm:
`helm repo add harbor https://helm.goharbor.io
helm fetch harbor/harbor --untar
helm install harbor ./harbor`

Problem solved by using newer version of postgreSQL.
Versions under  [Postgres 9.6](https://www.postgresql.org/docs/9.6/sql-altertable.html) do not support 
ALTER TABLE table_name ADD COLUMN IF NOT EXISTS column_name INTEGER;

using postgreSQL under version 9.6 causes harbor core fails when staring up. I suppose this should be added to the documents, for clairty.

**Comment by kasim457** [comment]
@ninjadq @biello 

I am also getting same errror message when I did fresh installation of harbor application in our k8s cluster.  What is the fix for this issue.

```
2021-01-27T14:09:04Z [INFO] [/common/dao/base.go:70]: Register database completed
2021-01-27T14:09:04Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
2021-01-27T14:09:04Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 40. Fix and force version."
2021-01-27T14:09:04Z [FATAL] [/core/main.go:174]: failed to migrate: Dirty database version 40. Fix and force version.
```

**Comment by biello** [comment]
@kasim457 since it's a fresh installation, you can try purging postgreSQL and install again , watch the logs of core's at the first time when core is starting up. if core failed to start up, the datebase could be dirty which causes the error `failed to migrate: Dirty database version 40. Fix and force version.`.
In my case, it's an unsupported psql grammar caused the core failed to start up, update postgreSQL to 10.4 solved the problem.

**Comment by kasim457** [comment]
> 
> 
> @kasim457 since it's a fresh installation, you can try purging postgreSQL and install again , watch the logs of core's at the first time when core is starting up. if core failed to start up, the datebase could be dirty which causes the error `failed to migrate: Dirty database version 40. Fix and force version.`.
> In my case, it's an unsupported psql grammar caused the core failed to start up, update postgreSQL to 10.4 solved the problem.

Could you write down the steps which you had executed in your environment.  How to purge PostgreSQL and install it again?

**Comment by biello** [comment]
to purge PostgreSQL, first connect to your  PostgreSQL server
```
psql -U dbuser -d exampledb -h 127.0.0.1 -p 5432
```

then drop database "registry":
```
DROP DATABASE registry;
```
type `\l` to list the databases
you can alse drop clair, notary_server, notary_signer too.

reinstall harbor, just use helm
```
helm uninstall harbor
helm install harbor ./harbor
```

**Comment by DonAndrey** [comment]
Is this going to be fixed in the upcoming releases?

**Comment by jvleminc** [comment]
We had the same issue: `failed to migrate: Dirty database version *80*. Fix and force version`

What we did and apparently worked, is:

- Switch liveness probe of `core` off  in values + redeploy chart
- Scale core pods to 0: `kubectl -n registry scale deployment whiteregistry-harbor-core --replicas=0`
- Enter in main DB pod:
```
kubectl -n registry exec -ti  whiteregistry-postgresql-ha-postgresql-1 bash
psql -U whiteregistry_core <- password from chart
use whiteregistry_core;
update schema_migrations set dirty=false; commit;
```
- Scale core pods to 3: `kubectl -n registry scale deployment whiteregistry-harbor-core --replicas=3`
- Pods should go up
- Switch liveness probe of `core` off  in values + redeploy chart

We tried a quick push to the registry and it seems to work, but my doubt is if itr's normal that the counter in that DB table remains in 80:
``` 
> use whiteregistry_core; select version,dirty from schema_migrations;

version | dirty 
---------+-------
      80 | f
```
