### ISSUE TITLE
Lower the DB connection in cfgManager

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#13418]
Currently Harbor stores some of the configurations in DB.  

While the code calls `config.XXX`.   It almost always creates a new connection to DB.  This has an impact on performance, in addition, it greatly increases the chance to deadlock: (#13155)

Something we may consider:
1) Pass the context to cfgManager and get the `ormer` from context.  This approach may require us to change a LOT of code to pass the ctx, and querying pgSQL concurrently within a TX has some known issue:
https://github.com/goharbor/harbor/blob/master/src/server/v2.0/handler/project.go#L424
2) Introduce a cache layer in cfgManager, so then we need to consider the case when there are multiple `harbor-core` instances and be careful with the criteria for cache invalidation.

**Comment by stonezdj** [comment]
Fixed after using cache and refactor config to new programming model
