### ISSUE TITLE
Onboarding new OIDC users without have an access to the Harbor UI

### ISSUE THREAD

**Issue by farbgit** [goharbor/harbor#13427]
Dear Team, 
Is it possible to onboard a new user through an API call? 
Or is it possible to onboard a new user without have an access to the harbor UI?

We have developed our custom UI for our services and in the backend, we are calling some of the harbor APIs with the user's access token, but it gets an unauthorized error for the user that exists in OIDC provider and are not onboarded into the harbor yet.

Is there any way to automate the onboarding process? (without accessing the harbor UI)

**Comment by reasonerjt** [comment]
If you think about the onboarding SSO flow it involves the user inputing his password on the OIDC provider, I think the gap is how you can automate it.

I think you can do it by implementing you own flow, by accessing Harbor's DB, but there's no API to do that.

**Comment by farbgit** [comment]
No, I mean after the SSO process, we got an access token for the current user. 

We are using this access token for calling harbor APIs on behalf of the user in our backend methods. (It helps us to not struggle with access and role management on the projects, harbor will manage that)

All in all, thanks for your comments, quick reply and for such a great open source software.

Good luck.

Should I close this thread?

**Comment by reasonerjt** [comment]
If there's no further action we need to take.  I'm closing this one.

Thanks @farbgit
