### ISSUE TITLE
add group user failed in harbor2.1

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#13434]
What can we help you?
hi 
after upgrade to harbor 2.1  i can not add group. i create a new harbor 2.0 and test add group function works well
my configuration is :
LDAP Group GID: cn
LDAP Group Membership: memberof 
our ldap server is windows AD 
when i add group it shows:
LDAP Group DN is not found: DN:CN=AXXX,OU=AAA,OU=BBBList,OU=CCC,DC=DD,DC=EEE,DC=FFF

please help me to check if harbor changed group search code,so i got this error
thank you

**Comment by reasonerjt** [comment]
@stonezdj please follow up to confirm if this has been fixed in 2.1.1

**Comment by sinycn** [comment]
verified，already fixed this issue 
thank you for quick response
