### ISSUE TITLE
How to reset default admin password

### ISSUE THREAD

**Issue by suh209** [goharbor/harbor#13441]
Hi 

I have lost my admin password. The default password which was set in the harbor.yaml was changed from the Harbor GUI. I have tried this solution, but didn't work - 
https://kb.vmware.com/s/article/76289

Any suggestion will be highly appreciated

**Comment by reasonerjt** [comment]
@suh209 Are you a user of Harbor Tile?

**Comment by reasonerjt** [comment]
@stonezdj please follow up as this OP is probably a user of tile or bosh-release.

**Comment by suh209** [comment]
@reasonerjt I have solved the problem. The VM that hosted the Harbor needed a restart.
