### ISSUE TITLE
Can someone please share curl command to delete image

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#13445]
Can someone please share curl command to delete image for harbor version 2.1.1

In harbor api v2.0, w e can delete image using digest/tagname or artifacts.. when I try to do it using API getting below error msg.

  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "CSRF token invalid"
    }
  ]
}

**Comment by reasonerjt** [comment]
Something like this works:
```
curl -kv -X DELETE -u "admin:Harbor12345" https://demo.goharbor.io/api/v2.0/projects/library/repositories/redis/artifacts/sha256:ae4b7c01640a2688e9ef5dd630e2135df7a9e711e712e3d9eab05608d34e2b84
```

Please refer to 
https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml

Instead of copying the curl from UI plugin.  There are additional verifcation if your request carries UI session.

**Comment by reasonerjt** [comment]
Seems continued discussion in #13459 closing this one.
