### ISSUE TITLE
Update Docs for Robot Account to Authenticate using password-stdin

### ISSUE THREAD

**Issue by doddatpivotal** [goharbor/harbor#13447]
The robot account tokens are so large they are not allowed as input to the docker cli prompt for password.  This can be worked around by providing the robot account token in the `docker login` command using the --password flag or by using the --password-stdin flag (which would be preferred due to security).

The request is to update the docs at bottom of the following URL that say to use `docker login harbor_address` and then follow prompts for username and password.  This will not work due to the size of the token.

https://goharbor.io/docs/2.0.0/working-with-projects/project-configuration/create-robot-accounts/

One suggestion is to shorten the length of the token.

Or update the docs to something like: `echo $PASSWORD | docker login $REGISTRY --username $USER --password-stdin`

**Comment by reasonerjt** [comment]
In v2.2 we will rework the robot account  and the users will be able to set the password for any robots.

The proposed command is not a must-have IMO to the doc, it's more like a shortcut to lower the effort and it will not be needed soon.

**Comment by doddatpivotal** [comment]
Do we acknowledge though that the docs are incorrect for the current version?  You can not put the password in the prompt as the docs suggest.
