### ISSUE TITLE
CSRF token invalid -- using curl

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#13459]
Hello,

I am trying to use the Harbor API but getting the below error.
Harbor VM 2
Scalable VM 2
Database(Postgres) VM 1
Redis VM 1
Harbor Version 2.0.0
Docker version 19.0.0
docker-compose version 1.26

{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "CSRF token invalid"
    }
  ]
}

The curl command is working fine and also able to login successfully.
Only getting the error from Harbor API since Harbor 2.x.x

Thank You

**Comment by reasonerjt** [comment]
Please DO NOT copy the curl from UI developer tools and use it on cmd line. more details see:
https://github.com/goharbor/harbor/issues/13445#issuecomment-723823252

**Comment by dbenduga** [comment]
I tried to delete image using artifacts but getting 400 error. Please see below output.

# curl -kv -X delete -u "admin:xxxxx" https://pun-harbor-02.xxx.com/api/v2.0/projects/dipesh/repositories/alpine/artifacts/sha256:a15790640a6690aa1730c38cf0a440e2aa44aaca9b0e8931a9f2b0d7cc90fd65
* About to connect() to pun-harbor-02.bmc.com port 443 (#0)
*   Trying 10.128.177.181...
* Connected to pun-harbor-02.bmc.com (10.128.177.181) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=pun-harbor-02.bmc.com,OU=test_harbor,O=xxx Inc,L=Houston,ST=Texas,C=US
*       start date: Oct 10 15:03:44 2019 GMT
*       expire date: Oct 09 15:03:44 2020 GMT
*       common name: pun-harbor-02.bmc.com
*       issuer: CN=pun-harbor-02.bmc.com,OU=test_harbor,O=xxx Inc,L=Houston,ST=Texas,C=US
* Server auth using Basic with user 'admin'
> delete /api/v2.0/projects/dipesh/repositories/alpine/artifacts/sha256:a15790640a6690aa1730c38cf0a440e2aa44aaca9b0e8931a9f2b0d7cc90fd65 HTTP/1.1
> Authorization: Basic YWRtaW46Ym1jQWRtMW4=
> User-Agent: curl/7.29.0
> Host: pun-harbor-02.xxxcom
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Tue, 10 Nov 2020 11:55:32 GMT
< Content-Type: text/html
< Content-Length: 150
< Connection: close
<
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Closing connection 0

**Comment by reasonerjt** [comment]
Have you bothered to try `-X DELETE` ????
