### ISSUE TITLE
Events logs are available for each user

### ISSUE THREAD

**Issue by Tchoupinax** [goharbor/harbor#13454]
**Expected behavior and actual behavior:**

Hello,

I created an user and I assigned it as admin of a project. When i am logging with this user, I only see public project and the one which this user administrates.

However, events logs (tabs on the right) are available and could give private informations.

![image](https://user-images.githubusercontent.com/9136206/98227529-b6894f80-1f57-11eb-8bc0-dd1e668acc2b.png)

I am expecting that event logs are only visible for their owner :)

**Steps to reproduce the problem:**

- With admin account, create an user, an project and assign this user "admin" of this project
- log in with this admin and show the event log tab

**Versions:**
Please specify the versions of following systems.

I'm using the chart

```
NAME            	CHART VERSION	APP VERSION	DESCRIPTION                                       
harbor/harbor   	1.5.1        	2.1.1 
```

**Comment by reasonerjt** [comment]
The root is that the event logs are stored on UI side.

If you use different user on the same browser on the browser it will show the same results as it's stored on the browser.

**Comment by Tchoupinax** [comment]
Hum, your explanation rings well, but my test does not agree with.. :(

As admin, I deleted a project.
![image](https://user-images.githubusercontent.com/9136206/99040047-b9ec8e80-2588-11eb-8cba-8ecbc14fb337.png)

Then, I log in with a standard user.

![image](https://user-images.githubusercontent.com/9136206/99040119-d983b700-2588-11eb-8742-9f62dc783b65.png)

As you can see on the previous screen, rights are very limited for this user, it is not an admin and it has access only to his project. The only tab it has are projects and logs

However, logs menu shows all actions made by `admin`. Morever the side panel, I just notice that the log menu is present.

![image](https://user-images.githubusercontent.com/9136206/99040383-54e56880-2589-11eb-8ac9-0f267a309f5a.png)

In my local storage, I have this entry but when I delete it, it come back ^^

Maybe it is a wish to give access to logs to all user but I think is a bad practice. And if it is a bug, we should find it :)

**Comment by AllForNothing** [comment]
@Tchoupinax Thanks for providing the  information.
Harbor UI loads  the logs data from local storage into memory, so it will come back when you delete it.
I'm closing this issue, if you have any good suggestions please open another issue
