### ISSUE TITLE
Registries configuretion have some problem. 

### ISSUE THREAD

**Issue by sober-wang** [goharbor/harbor#13458]
my harbor version is v1.7.4 

![图片](https://user-images.githubusercontent.com/35804630/98241180-89638e00-1fa5-11eb-93f8-f725f774f051.png)

this is core.log 
Nov  5 20:28:24 172.18.0.1 core[32525]: 2020-11-05T12:28:24Z [ERROR] [target.go:65]: failed to ping target: Head https://mirror.xxxx.com.cn/v2/: Get https://mirror.xxxx.com.cn/v2/: dial tcp: lookup mirror.dbappsecurity.com.cn on 127.0.0.11:53: no such host

Who can help me?

**Comment by reasonerjt** [comment]
Sorry but v1.7.4 is no longer supported.

Based on the discussion on wechat I assume this problem is solved, closing.
