### ISSUE TITLE
I want to save the harbor log separately every day. Help..!

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13463]
What can we help you?
I want to save daily log of harbor.

Logs are accumulated in /var/log/harbor.
I want to cut and save the log every day.
in common/config/log
I added daily to logrotate, but it doesn't seem to work.
Modifying rsyslog_docker to add DDMM
It is stamped with the date of execution.
That is, no new log is created as of 00:00 every day.
Is there any way?

**Comment by reasonerjt** [comment]
If you are not familiar with logrotate, you can write a cron job on the docker host to handle the packaged log files?

**Comment by peterjc85** [comment]
> logrotate에 익숙하지 않은 경우 Docker 호스트에서 cron 작업을 작성하여 패키지 된 로그 파일을 처리 할 수 ​​있습니까?

It is the same even if you set daily in loglotate.
No new log is created even after 00:00 based on server.
