### ISSUE TITLE
Scanning Finished Webhook notification , image TAG is empty

### ISSUE THREAD

**Issue by mricartx** [goharbor/harbor#13464]
I have set up a webhook for scanning finished event in a project . 
The endpoint receives all information but image tag is empty. 

Received JSON:  
{
  "_index": "harbor",
  "_type": "data",
  "_id": "h63QnHUBnNErpmnnarlA",
  "_version": 1,
  "_score": null,
  "_source": {
    "type": "SCANNING_COMPLETED",
    "occur_at": 1604653704,
    "operator": "auto",
    "event_data": {
      "resources": [
        {
          "digest": "sha256:a98d9dcf3a34b2b78e78c61d003eb4d7a90d30fd54451686e2f0bd2ef5f602ac",
          **"tag": "",**
          "resource_url": "192.168.78.128/ti-evo/ubuntu:",
          "scan_overview": {
            "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0": {
              "report_id": "56ecaaee-15f6-493b-837e-abcfcaf6adfa",
              "scan_status": "Success",
              "severity": "Medium",
              "duration": 32,
              "summary": {
                "total": 171,
                "fixable": 35,
                "summary": {
                  "Low": 145,
                  "Medium": 26
                }
              },
              "start_time": "2020-11-06T09:07:52.12667Z",
              "end_time": "2020-11-06T09:08:24.243906Z",
              "scanner": {
                "name": "Trivy",
                "vendor": "Aqua Security",
                "version": "v0.9.2"
              },
              "complete_percent": 100
            }
          }
        }
      ],
      "repository": {
        "name": "ubuntu",
        "namespace": "ti-evo",
        "repo_full_name": "ti-evo/ubuntu",
        "repo_type": "public"
      }
    }
  },
  "fields": {
    "event_data.resources.scan_overview.application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0.start_time": [
      "2020-11-06T09:07:52.126Z"
    ],
    "event_data.resources.scan_overview.application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0.end_time": [
      "2020-11-06T09:08:24.243Z"
    ]
  },
  "sort": [
    1604653672126
  ]
}

- harbor version: 2.0.1 and 2.1.1
- docker engine version: 18.09.0
- docker-compose version: 1.19.0

There is no information or errors in the logs files .

Regards,
Marc

**Comment by jonny-wg2** [comment]
I can confirm that tags are missing in my setup also.

**Comment by reasonerjt** [comment]
@mmpei could you double check?

**Comment by jonny-wg2** [comment]
I have also tested this with a second scanner and still the same

**Comment by reasonerjt** [comment]
The root cause is that after v2.0 when trigger the scanning it will only pass the digest to the scanner, maybe we should adjust the structure of JSON in the webhook request.

**Comment by mricartx** [comment]
Is there any news on this issue ? is there any workaround that could be applied ?
Thanks

**Comment by heww** [comment]
Hi, @mricartx there isn't a workaround to fill the tag in the webhook resource. I will remove the tag filed in the response when it's empty.
