### ISSUE TITLE
Kubernetes can't pull new image from proxy-cache

### ISSUE THREAD

**Issue by pavanfhw** [goharbor/harbor#13475]
I have set up a proxy-cache for my private registry.

I am able to do `docker pull <harbor-proxy-cache>/<proxy-cache-project>/<target-registry-image>:<tag>`
The image is pulled successfully.

In my Kubernetes cluster I am unable to create a deployment using an image from the private registry:
`failed to resolve reference "<harbor-proxy-cache>/<proxy-cache-project>/<target-registry-image>:<tag>": <harbor-proxy-cache>/<proxy-cache-project>/<target-registry-image>:<tag>: not found`.

This happens if the image is not already present in the proxy-cache harbor. If I previously pulled the image, it works. Examples:

**This works**: 
1. `docker pull <harbor-proxy-cache>/<proxy-cache-project>/<target-registry-image>:1.0` (not from the node running the deployment, from any other machine)
2. create Kubernetes deployment that uses image version 1.0

**This fails**:
1. `docker pull <harbor-proxy-cache>/<proxy-cache-project>/<target-registry-image>:1.0`
2. create Kubenetes deployment that uses image version 1.1 (image not present in the proxy-cache harbor)

Kubernetes fails to get image with the early mentioned error.

Is this the expected behavior?
Why this scenario does not cause Harbor to pull the new image from the target registry?

**Comment by msiebuhr** [comment]
Looks to be an issue with `containerd` and Harbor somehow not playing well together per this containerd bug: https://github.com/containerd/containerd/issues/4706
