### ISSUE TITLE
vague log message during upgrade

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#13477]
@ywk253100 coming across this during an upgrade from v1.9.2 to v2.0.3, not sure 'abstracting artifact metadata' means, is this referring to going from a docker tag to creating a harbor tag in 2.x?  

once this is cleared up, please work with Abbie on the best wording for this

11/3/2020 5:02:51 PM 2020-11-03T23:02:51Z [DEBUG] [/migration/artifact.go:44]: abstracting artifact metadata under repository abc/test_taks ....
11/3/2020 5:02:52 PM 2020-11-03T23:02:52Z [DEBUG] [/migration/artifact.go:64]: artifact metadata under repository abc/test_taks abstracted
11/3/2020 5:02:52 PM 2020-11-03T23:02:52Z [DEBUG] [/migration/artifact.go:44]: abstracting artifact metadata under repository abc/addon-resizer ....
11/3/2020 5:02:52 PM 2020-11-03T23:02:52Z [DEBUG] [/migration/artifact.go:64]: artifact metadata under repository abc/addon-resizer abstracted
11/3/2020 5:02:52 PM 2020-11-03T23:02:52Z [DEBUG] [/migration/artifact.go:44]: abstracting artifact metadata under repository abc/tools-rmt ....
11/3/2020 5:02:52 PM 2020-11-03T23:02:52Z [DEBUG] [/migration/artifact.go:64]: artifact metadata under repository abc/tools-rmt abstracted

**Comment by ywk253100** [comment]
There are several artifact metadata managed by Harbor, such as size, annotations, author, os, arch etc. 
The process of `abstracting artifact metadata` reads these metadata from docker registry and stores them into the database
