### ISSUE TITLE
Q/ Endpoint communication or "pull command" example config related

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13478]
I installed the harbor package.
We installed L4 in front and 2 harbors.
I installed the harbor hostname as an L4 VIP domain.
However, communication No. 1 and No. 2 from the endpoint to the IP are not available.
This is possible by changing the hostname to each server IP.
However, if you change it to IP, it will appear as IP in "pull command".
Here in the "pull command" example I want to show it as a domain.
Is there any way?

1. How to communicate by IP in communication between endpoints?
2. How to static config to domain in "pull command" example.?

**Comment by reasonerjt** [comment]
> 
> However, communication No. 1 and No. 2 from the endpoint to the IP are not available.
> This is possible by changing the hostname to each server IP.
> 

I do not understand why it's not available, whatever hostname you setup for Harbor, that's the endpoint Harbor expect user to use.

**Comment by peterjc85** [comment]
I set the hostname of harbor.yml as the VIP of L4.
(2 units of harbor01, harbor02)
If you set the endpoint after accessing the next Portal, even if you enter the domain and IP of Harbor01, Harbor02, "Failed to ping endpoint" appears. Fails.
You can connect by changing the hostname of harbor.yml from VIP to harbor01, harbor02's IP or DNS.
I am using a certificate.
Do you ever support multi hostname in harbor.yml hostname?
Or is there no other way??

**Comment by peterjc85** [comment]
> > However, communication No. 1 and No. 2 from the endpoint to the IP are not available.
> > This is possible by changing the hostname to each server IP.
> 
> I do not understand why it's not available, whatever hostname you setup for Harbor, that's the endpoint Harbor expect user to use.

I set the hostname of harbor.yml as the VIP of L4.
(2 units of harbor01, harbor02)
If you set the endpoint after accessing the next Portal, even if you enter the domain and IP of Harbor01, Harbor02, "Failed to ping endpoint" appears. Fails.
You can connect by changing the hostname of harbor.yml from VIP to harbor01, harbor02's IP or DNS.
I am using a certificate.
Do you ever support multi hostname in harbor.yml hostname?
Or is there no other way??

**Comment by reasonerjt** [comment]
@peterjc85 
Is it the same scenario as in #13504?  If the answer is yes, I'll close this one and continue the discussion in the latter.
