### ISSUE TITLE
group users can not see project in harbor 2.1.1

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#13479]
**Expected behavior and actual behavior:**
Expected behavior: when a group add to project members with project admin privileges in a private project .users in group log in harbor can see this project.
actual behavior:  add group in private project  but users in group can not see private project.

Steps to reproduce the problem:
in harbor v2.1.1   group can add successfully but users in group can not see private project.
in harbor v2.0.2   group can add successfully but users in group can not see private project.
in harbor v2.0.0   group can add successfully users in group can see private project.

**Comment by sinycn** [comment]
add more info : we use ldap to auth users& group

**Comment by stonezdj** [comment]
Could you please paste your LDAP configuration? and login with the LDAP user and send us the core.log ?

**Comment by sinycn** [comment]
this is LDAP setting 
![image](https://user-images.githubusercontent.com/1812254/99365110-d0c91300-28f1-11eb-843b-308b58c0e34b.png)

and core log of harbor 2.1.1  is  large than 10M  so i upload it to baidu pan
链接: https://pan.baidu.com/s/1BnAIO6xNCWRt1vIl5SkLyg 提取码: 8qns

**Comment by xeivieni** [comment]
Hi, we are facing the same issue. Some of our users cannot see some projects after updating to 2.1.1

**Comment by stonezdj** [comment]
> this is LDAP setting
> ![image](https://user-images.githubusercontent.com/1812254/99365110-d0c91300-28f1-11eb-843b-308b58c0e34b.png)
> 
> and core log of harbor 2.1.1 is large than 10M so i upload it to baidu pan
> 链接: https://pan.baidu.com/s/1BnAIO6xNCWRt1vIl5SkLyg 提取码: 8qns

it is expired

**Comment by stonezdj** [comment]
LDAP group base DN and the LDAP group filter  and the ldap group membership is empty.
Harbor 2.1.1 add more restrict on the group search for security reason.
If there is no LDAP group membership is not defined, it can not search its user group. then it can not access the projects of its groups.

![Screen Shot 2020-11-26 at 3 20 22 PM](https://user-images.githubusercontent.com/2696760/100319791-2e98e180-2ffb-11eb-9a41-cbe5e40c3c90.png)

**Comment by xaleeks** [comment]
Stone, can you link the change that we implemented in 2.1.1? I don't recall this.  @stonezdj

**Comment by stonezdj** [comment]
see PR: https://github.com/goharbor/harbor/pull/13298
