### ISSUE TITLE
Extraction of CVE List 

### ISSUE THREAD

**Issue by GazRagzz** [goharbor/harbor#13482]
Hi ! 

It's possible to extract the latest CVE List and sending it by email after an automatic Scan of a specific image ? 

Using Harbor API ? 
In clair / aqua / ... container ? 

Thanks !

**Comment by reasonerjt** [comment]
By CVE list do you mean scan result?

You have to use Harbor API to get the scan result.

**Comment by GazRagzz** [comment]
Hi !
Thanks for reply ! 
Yes I mean Scan Result for latest specific image.
There is a way to extract it by the Harbor API ?

**Comment by heww** [comment]
Hi @GazRagzz you can try `/api/v2.0/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/vulnerabilities` to get the vulnerability report of the artifact. `reference` can be a `digest` (sha256:xxxxxxxx) or `tag`.

**Comment by xaleeks** [comment]
@a-mccarthy Abbie, can you call this out in the docs, export via API is not listed in docs anywhere I don't think.  Maybe include a short description that it's possible to do this via API and link to swagger under this https://goharbor.io/docs/2.1.0/administration/vulnerability-scanning/

**Comment by GazRagzz** [comment]
> 
> 
> Hi @GazRagzz you can try `/api/v2.0/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/vulnerabilities` to get the vulnerability report of the artifact. `reference` can be a `digest` (sha256:xxxxxxxx) or `tag`.

Hi ! Thanks a lot for that !
