### ISSUE TITLE
replication policy push image to alibaba ACR failed, error code 404

### ISSUE THREAD

**Issue by qiangshui** [goharbor/harbor#13484]
Harbor version: v2.0.1-d714b3ea

I created a replication policy to push images to Alibaba ACR. When the dest repository type is Harbor, the connection test is successful, but when the type is Alibaba ACR, the connection test is failed.

I was able to push image to ACR successfully by execute command "docker push" , but failed when using the harbor replication policy.

when execute replication manually, get this error
![image](https://user-images.githubusercontent.com/24819310/98662398-ac65b780-2382-11eb-896a-0ed516a9913e.png)
failed to do the prepare work for pushing/uploading resources: http error: code 404, message 404 page not found

**Comment by bitsf** [comment]
I wonder how did you create the ACR registry, if the connection failed ?

**Comment by qiangshui** [comment]
> I wonder how did you create the ACR registry, if the connection failed ?

Mymistake,  the ACR service type is ‘Docker Registry’, I selected 'Harbor'. After changing the type, push successfully.
