### ISSUE TITLE
GC not working

### ISSUE THREAD

**Issue by davidhoelzel** [goharbor/harbor#13487]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Starting GC seems to work (http status 201). Taking a look in the logs, all GC runs are marked with status error. I cannot view the logs, I only get 404 NOT_FOUND (/api/v2.0/system/gc/9/log).
Daily cron shows the same behaviour.
Tried the workaround in https://github.com/goharbor/harbor/issues/7945#issuecomment-498123934, but I cannot execute the command in the container, I get: "sudo: Account or password is expired, reset your password and try again"

**Steps to reproduce the problem:**
Install Helm Chart, try to run GC.

**Versions:**

- harbor version: 2.0.2
- docker engine version: 19.03.12

**Additional context:**
Installed with helm chart. Addtional params:
--namespace harbor \
  --set database.internal.nodeSelector.type=system \
  --set registry.nodeSelector.type=system \
  --set jobservice.nodeSelector.type=system \
  --set redis.internal.nodeSelector.type=system \
  --set persistence.persistentVolumeClaim.registry.existingClaim=harbor \
  --set persistence.persistentVolumeClaim.registry.subPath=registry \
  --set persistence.persistentVolumeClaim.registry.size=47Gi \
  --set persistence.persistentVolumeClaim.jobservice.existingClaim=harbor \
  --set persistence.persistentVolumeClaim.jobservice.subPath=jobservice \
  --set persistence.persistentVolumeClaim.jobservice.size=1Gi \
  --set persistence.persistentVolumeClaim.database.existingClaim=harbor \
  --set persistence.persistentVolumeClaim.database.subPath=database \
  --set persistence.persistentVolumeClaim.database.size=1Gi \
  --set persistence.persistentVolumeClaim.redis.existingClaim=harbor \
  --set persistence.persistentVolumeClaim.redis.subPath=redis \
  --set persistence.persistentVolumeClaim.redis.size=1Gi \
  --set expose.ingress.hosts.core="$HOSTNAME" \
  --set externalURL=https://"$HOSTNAME" \
  --set expose.tls.enabled=false \
  --set notary.enabled=false \
  --set trivy.enabled=false \
  --set clair.enabled=false \
  --set chartmuseum.enabled=false
Running with Longhorn Volume in simple Kubernetes cluster.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
It doesn't seem right if you can't see the log of gc job.
If possible please consider bump up to 2.1.x where the GC has been reworked.

**Comment by reasonerjt** [comment]
It's very likely the job is not started in job-service.

**Comment by davidhoelzel** [comment]
After upgrading to 2.1.0, I now get an overlay in the UI saying "Internal Error" when I try to manually run GC. Same when clicking on "Dry Run".
![image](https://user-images.githubusercontent.com/56548897/100102568-180c5200-2e64-11eb-8714-e6b7a02d74c2.png)

**Comment by davidhoelzel** [comment]
Seems GC is working now, although it does not think that something should be deleted. I manually deleted dozens of artificats because my volume is getting full and hoped to get back some space.

**Comment by anigkus** [comment]
We hit the same issue with the same version of Harbor

**Comment by anigkus** [comment]
> Seems GC is working after upgrading to 2.1.0, although it does not think that something should be deleted. I manually deleted dozens of artificats because my volume is getting full and hoped to get back some space.

Hi @davidhoelzel , sorry to bother you. I hit the same issue, I'd like to know how to remove the artifacts by manually? I mean we can remove it on host path of operation system?

**Comment by davidhoelzel** [comment]
Hi @anigkus,
I gave up on deleting stuff. As I´m running this for our staging environment only, I finally created a base backup of the volume for the harbor registry. When space is getting low, I simply revert to the backup as we do not need persistent images.
We are using Longhorn and the problem with block storage is that it is simply getting full over the time by definition. Deleting files does not prevent the volume from getting full.

You could delete it manually from the UI, but that is really annoying when you have more than 2 projects. I don´t know how the files are organized on the disk, so perhaps any of the devs could say something about that.

**Comment by wy65701436** [comment]
hi @davidhoelzel did you update Harbor to the latest? I've moved GC to the new task/schedule framework.

From the original log, its very likely a jobservice issue, we need the core/jobservice log to debug.

**Comment by davidhoelzel** [comment]
GC seems to work again after upgrading to 2.3.1. 
Does not solve the problem with the volume getting full, obviously.
