### ISSUE TITLE
Robot accounts can't authenticate after upgrade

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [goharbor/harbor#13481]
Hi,
After the upgrade from v2.0.3 to v2.1.1 all robot accounts can't able to push/pull images.
I had to regenerate them.

the error is:
`
2020-11-06T05:00:49Z [ERROR] [/server/middleware/security/basic_auth.go:41][requestID="6e263b58-7c7c-42ce-9e6f-5f3d1e22261a"]: failed to authenticate robot$user: Failed to authenticate user, due to error 'Not found an entry'
`
Regards.

**Comment by wy65701436** [comment]
how did you upgrade the harbor, and are you using harbor on k8s? If the private key is changed during upgrade, the token of robot cannot be decoded after that.

**Comment by adonyina** [comment]
Hey I had the same issue and I was wondering what private key you were referring to? thanks

**Comment by hasonhai** [comment]
@wy65701436 could you point out which private key?
I saw lost of private keys in Harbor deployment: private key for ingress tls, private key for each component for internal tls, "secretKey" mentioned in the helm chart. Did you mean the secretKey which is a random generated string?
We don't have the issue right now but we are planning to upgrade Harbor from 2.0.1 to 2.1.1. Thank you.

**Comment by p3t3rp3pp3r** [comment]
Hi,
Many thanks for your reply.
I'm sorry to not having specified installation specs, then I confirm that we upgraded harbor on a k8s cluster.

@wy65701436 : We set the secretName field only in core and tls section. I must admit that I ignored this aspect, but we didn't find any documentation or entries in values.yaml that describe how to preserve robot account during upgrade.

Regards

**Comment by wy65701436** [comment]
@hasonhai you can refer to the above comments, just keep the secretName field during upgrade.

**Comment by wy65701436** [comment]
Keep the value of secretName be same can avoid this issue for old version robot account. And also you can upgrade Harbor to use the robot v2, it doesn't leverage private key to decode the password.
