### ISSUE TITLE
Proxy cache should support GCR endpoint.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#13480]
What can we help you?

**Comment by Moumoutaru** [comment]
I concur we should allow a broader range of endpoints k8s.gcr.io, gcr.io, etc.

**Comment by stonezdj** [comment]
It seems that both UI and backend should change to enable new type of endpoint.
https://harborserver/api/v2.0/registries?q=type=%7Bdocker-hub%20harbor%7D
https://github.com/goharbor/harbor/blob/30215582729eba5b73f14b761fbb2fab1dd6749c/src/server/v2.0/handler/project.go#L511

**Comment by AllForNothing** [comment]
Close as both  UI and backend PRs merged
