### ISSUE TITLE
Web interface display wrong info in the bubble

### ISSUE THREAD

**Issue by hasonhai** [goharbor/harbor#13488]
Normally when we hover the mouse on the tag of the image, Harbor WebUI will display a bubble telling some info.
I saw that, for signed image, the bubble display wrong info. It should be a screen stick instead of a red X for signed image.  

![image](https://user-images.githubusercontent.com/1762517/98791692-b67cca00-2405-11eb-808e-2d3e0337e949.png)

**Comment by reasonerjt** [comment]
@hasonhai
Please clarify which version you are using.

**Comment by AllForNothing** [comment]
@hasonhai 
Is it consistent with the detail page:
![image](https://user-images.githubusercontent.com/30999793/98928182-78220080-2514-11eb-8471-2981f2dc4d60.png)

**Comment by hasonhai** [comment]
@AllForNothing hi, it's inconsistent. My image is signed but the bubble display the wrong info.
I saw this happenned in 2.0.1.

**Comment by AllForNothing** [comment]
![image](https://user-images.githubusercontent.com/30999793/100189597-8cf49000-2f27-11eb-8c84-4ca2c1f4941a.png)
@ywk253100 Just comfirmed,  the backend api returns wrong value for Tag.signesd property:
![image](https://user-images.githubusercontent.com/30999793/100189734-d47b1c00-2f27-11eb-9d04-efc33ca545e7.png)
