### ISSUE TITLE
redis+sentinel cannot be used as core chart cache

### ISSUE THREAD

**Issue by hobti01** [goharbor/harbor#13485]
**Expected behavior and actual behavior:**
**Expected:** redis+sentinel can be used for chart cache.
**Actual:** redis+sentinel cannot be used for chart cache

**Steps to reproduce the problem:**
* Run harbor core with `CHART_CACHE_DRIVER=redis_sentinel`
* Observe harbor core log.
```
2020-11-10T15:03:25Z [ERROR] [/chartserver/controller.go:62]: failed to get cache configuration with error: cache driver 'redis_sentinel' is not supported, only support 'memory' and 'redis'
2020-11-10T15:03:25Z [INFO] [/chartserver/controller.go:66]: No cache is enabled for chart caching
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.1]

**Additional context:**

`redis_sentinel` driver cannot be used because only `redis` or `memory` are allowed:
https://github.com/goharbor/harbor/blob/d32527dfd77a87f8a9913904c0652146e9c32c38/src/chartserver/cache.go#L20-L22
https://github.com/goharbor/harbor/blob/d32527dfd77a87f8a9913904c0652146e9c32c38/src/chartserver/cache.go#L62-L64

**Comment by bitsf** [comment]
I'll fix this
But you should also notice that chartmuseum 2.0 is to be deprecated, you should use helm3 to push to OCI-based chart repo in harbor

**Comment by hobti01** [comment]
Yes certainly it will be deprecated in the future, but we are not there yet and it is still supported.  We like using the bitnami charts but this was also a surprise with Harbor 1.x when bitnami stopped providing updates to the 1.x version when 2.x was released 😃 

Please let me know if there is something I can do to assist here - we certainly like the bitnami non-root images that are updated regularly.
