### ISSUE TITLE
Harbor helm chart breaks in combination with ingress-nginx 0.41.0 (chart version 3.8.x and 3.9.0) (404 on login call)

### ISSUE THREAD

**Issue by mohag** [goharbor/harbor#13493]
What can we help you?
With the combination above, the login call (`/c/login`) returns a 404. On the UI (without the developer tools open), this shows as "Invalid user name or password." even with a correct username / password.

It seems related to [this change in ingress-nginx](https://github.com/kubernetes/ingress-nginx/issues/6437). They did improve the behaviour, but currently, that is not in a released version yet. (It is also possible that Harbor's ingress resources might need updating, it is hard to test without their change released)

Mainly logging this here if someone else runs into the same issue. Using `ingress-nginx` from the 3.7.1 Helm chart resolves the issue. (It is likely only present if ingress mode is enabled and when Harbor is run on Kubernetes) (It took me a few days to figure out)

Another note: I'm using the Bitnami chart. The ingress resources seems similar though.

**Comment by reasonerjt** [comment]
Please open issue in the bitnami chart repo.

We don't maintain the bitnami chart of Harbor.

**Comment by mohag** [comment]
The issue is present with the official chart as well. (I just configured a test instance) (With ingress-nginx chart version 3.9.0)

(It is likely the ingress-nginx that is broken though, instead of Harbor...)

Reverting to ingress-nginx chart version 3.7.1 fixes the 404 on that as well...

This works: (401 on login URL on incorrect login - I did not bother to actually get into it on the test deploy)
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
harbor          default         2               2020-11-12 13:34:03.0080306 +0200 SAST  deployed        harbor-1.5.1            2.1.1
ingress-nginx   ingress-nginx   3               2020-11-12 13:38:19.3100688 +0200 SAST  deployed        ingress-nginx-3.7.1     0.40.2
```

This does not: (404 on login URL)
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS  CHART                   APP VERSION
harbor          default         2               2020-11-12 13:34:03.0080306 +0200 SAST  deployedharbor-1.5.1            2.1.1
ingress-nginx   ingress-nginx   4               2020-11-12 13:41:17.3676595 +0200 SAST  deployedingress-nginx-3.9.0     0.41.0
```

**Comment by johann8384** [comment]
This seems to still be an issue with the latest ingress-nginx chart (3.23.0 ingress-nginx 0.44) and the 1.5.4 helm chart (https://github.com/goharbor/harbor-helm/releases/tag/v1.5.4).

Can this be re-opened and looked into instead of dismissed?

![image](https://user-images.githubusercontent.com/154673/112508430-e948ae80-8d65-11eb-98ac-7de78ac0b728.png)

**Comment by ywk253100** [comment]
@johann8384 opened a new issue https://github.com/goharbor/harbor-helm/issues/918 to track this
