### ISSUE TITLE
Update nodejs base image to a more recent version

### ISSUE THREAD

**Issue by dirkmueller** [goharbor/harbor#13492]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Currently harbor portal images are built against nodejs 10.15.0, as can be seen here I think: 

https://github.com/goharbor/harbor/blob/ca8cb87790c4231ff504adfbbe459a1e13291e53/make/photon/portal/Dockerfile#L3

according to https://nodejs.org/en/about/releases/ nodejs 10.x is in LTS mode, and 10.15 not the latest release (which I think is 10.27.x right now). This is missing a number of bug and security fixes. 

I am wondering what the plan of upgrading is (either newer version that is not in LTS or at least the most recent 10.x release) for harbor 2.1.x. 

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.1]

**Comment by xaleeks** [comment]
@reasonerjt please consider this
