### ISSUE TITLE
failed to parse the issued at time of token 

### ISSUE THREAD

**Issue by mfld** [goharbor/harbor#13491]
harbor version: 2.1.1

I see a lot of these error messages from core and jobservice containers.

`core-68d6cdc844-qvmk4 core-68d6cdc844-9btnlcore  core2020-11-11T12:54:46Z [ERROR] [/pkg/registry/auth/bearer/cache.go:98]: failed to parse the issued at time of token : parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006`

`jobservice-675f767cd4-tl92f jobservice 2020-11-11T12:32:58Z [ERROR] [/pkg/registry/auth/bearer/cache.go:98]: failed to parse the issued at time of token : parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"`

The errors seem harmless as operations are carried out and succeed regardless, but I am curious if there is any configuration missing to satisfy this requirement?

**Comment by mfld** [comment]
forgot to mention. These messages appear when replication from quay.io is trigged.

**Comment by chlins** [comment]
@mfld Hi, don't worry, it's quay.io side's token expired time is empty, so when harbor side parse the expire time can not successfully, log the error info, harbor will refresh token to fetch artifacts, so this error log will not affect the bussiness logic.

**Comment by mfld** [comment]
thank you @chlins. The info-logging seems a bit much though. Would it be possible to have an option to omit the check for token expiration? Perhaps a feature?

**Comment by chlins** [comment]
@mfld，thanks your ideas, but setting logging rules at too small a granularity for a feature is too heavy, maybe we can do some improvement such as adjust this error info to warning? maybe a generic rule for log framework is more helpful to all features.

**Comment by Vad1mo** [comment]
maybe set the warn level to [warn] instead of [error] as errors usually affect the correct execution, and in this case the replication still succeeds.

**Comment by chlins** [comment]
Maybe we can adjust the logic, check time whether empty before parse time. So we can avoid the error when time is empty.
