### ISSUE TITLE
docker registry migrate to harbor

### ISSUE THREAD

**Issue by wangycc** [goharbor/harbor#13506]
I have a docker Registry. I want to migrate to the harbor for management. What is a good migration plan?

The simplest solution I can think of is as follows:

1. /v2/_catalog  get all images
2. /v2/$image/tags/list Get all tags of image
3. docker pull  docker_registry.com/$image:$tag 
4. docker tag docker_registry.com/$image:$tag harbor.com/$image:$tag 
5. docker push harbor.com/$image:$tag

**Comment by ChristianCiach** [comment]
Two solutions I can think of:

* Use the pull-based replication that is built into harbor: https://goharbor.io/docs/2.1.0/administration/configuring-replication/
* Use skopeo, especially `skopeo sync`: https://github.com/containers/skopeo/blob/master/docs/skopeo-sync.1.md

Anyway, this question is not a good fit for an issue tracker. It's better to ask questions on stackoverflow.com or on Gitter chat: https://gitter.im/vmware/harbor

**Comment by wangycc** [comment]
@ChristianCiach thanks
