### ISSUE TITLE
L4 -> harbor01, harbor02 construction, replication error (multi domain??), Help..!!

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13504]
How to do multi hostname in harbor?
harbor01, harbor02 were built, and harbor.yml
It is set as the VIP (domain) of L4.
The endpoint does not communicate with harbor01, harbor02 domain, ip.
If the hostname is changed to the IP of VIP -> harbor01, harbor02, cloning is performed.
To solve this, I tried dns-search and extra_host inside docker, but it failed.
When extra_host was done, cloning was successful from harbor01 -> harbor02. (Forcing the VIP's IP to the opposite server in hosename) Then, if you restart the harbor01 service (in case of a failover), replication will not occur from the next time.

It seems possible if you use 2 IPs for hostname in harbor.yml.
Is there another way?

(The reason for using VIP domain in harbor.yml seems to be set as the value of hostname when you see "pull command" in the project.
I would like to set both servers as VIP domains.

**Comment by reasonerjt** [comment]
I dont quite understand the problem you mentioned.

What is cloning?  Do you mean replication.

the endpoint you set in harbor.yml is the endpoint to be used in replication.

I'm afraid the replication will not work with your setup.
