### ISSUE TITLE
docker push images to harbor occured unauthorized to access 

### ISSUE THREAD

**Issue by KevinWang2015** [goharbor/harbor#13503]
version: harbor 2.0

docker push images to harbor occured unauthorized to access repository:library/redis  action:push with admin user 
but  If the docker client is in another  datacenter, it is ok to push the image

is there someone give me some advices? thanks a lot

**Comment by KevinWang2015** [comment]
docker login successfully。 Pls refer to the docker push  logs from /var/log/harbor/core.log

Nov 13 11:35:11 172.22.0.1 core[30822]: 2020/11/13 03:35:11.688 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    355.486¦Ìs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
Nov 13 11:35:12 172.22.0.1 core[30822]: 2020/11/13 03:35:12.799 #033[1;44m[D]#033[0m [middleware.go:52]  |   10.59.99.181|#033[97;42m 200 #033[0m|  25.858451ms|   match|#033[97;44m GET     #033[0m /service/token   r:/service/token
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.443 #033[1;44m[D]#033[0m [middleware.go:52]  |   10.59.99.181|#033[97;43m 401 #033[0m|    895.406¦Ìs|   match|#033[97;44m GET     #033[0m /v2/   r:/v2/*
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.585 #033[1;44m[D]#033[0m [middleware.go:52]  |   10.59.99.181|#033[97;42m 200 #033[0m|  28.765171ms|   match|#033[97;44m GET     #033[0m /service/token   r:/service/token
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.915 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m| 133.615419ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.921 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m| 138.680945ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.921 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m| 141.106469ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.921 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m| 140.516994ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads
Nov 13 11:35:19 172.22.0.1 core[30822]: 2020/11/13 03:35:19.922 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m|  120.43912ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.025 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;43m 401 #033[0m|   4.321904ms|   match|#033[97;42m PATCH   #033[0m /v2/library/redis/blobs/uploads/726bcef5-9c9b-4a53-9de5-d8e331856162   r:/v2/*/blobs/uploads/:session_id
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.025 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;43m 401 #033[0m|   4.233904ms|   match|#033[97;42m PATCH   #033[0m /v2/library/redis/blobs/uploads/5c8ff720-9462-4107-b1f6-25799df7b55a   r:/v2/*/blobs/uploads/:session_id
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.027 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;43m 401 #033[0m|   5.953989ms|   match|#033[97;42m PATCH   #033[0m /v2/library/redis/blobs/uploads/5046293d-8656-4e1e-8c2b-deef27e47df6   r:/v2/*/blobs/uploads/:session_id
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.097 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;43m 401 #033[0m|   4.114612ms|   match|#033[97;42m PATCH   #033[0m /v2/library/redis/blobs/uploads/e82db9ed-f0da-46fa-8ca5-03db17d5e3a8   r:/v2/*/blobs/uploads/:session_id
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.098 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;43m 401 #033[0m|   4.984567ms|   match|#033[97;42m PATCH   #033[0m /v2/library/redis/blobs/uploads/e2c70dbc-28f9-4698-b933-a94fdb84b802   r:/v2/*/blobs/uploads/:session_id
Nov 13 11:35:20 172.22.0.1 core[30822]: 2020/11/13 03:35:20.245 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.59.99.181|#033[97;42m 202 #033[0m|  24.228976ms|   match|#033[97;46m POST    #033[0m /v2/library/redis/blobs/uploads/   r:/v2/*/blobs/uploads

**Comment by reasonerjt** [comment]
@KevinWang2015 
The log messages you pasted do not have relevant errors.



Under the hood docker will get a token via `service token` and use that token to push image.
Does the `docker push` fail immediately with `unauthorized` or failed in the middle of data transfer?

**Comment by KevinWang2015** [comment]
> @KevinWang2015
> The log messages you pasted do not have relevant errors.
> 
> Under the hood docker will get a token via `service token` and use that token to push image.
> Does the `docker push` fail immediately with `unauthorized` or failed in the middle of data transfer?

 in the middle of data transfer: unauthorized: unauthorized to access repository: evolve/redis, action: push: unauthorized to access repository: evolve/redis, action: push

**Comment by heww** [comment]
Hi, @KevinWang2015  it's really hard to debug the problem in this issue. Can you install an HTTP proxy tool and configure the Docker daemon to use the HTTP proxy and capture the HTTP request/response during the failed pushing? 

whistle (https://github.com/avwo/whistle) a good tool to capture the HTTP request/response. Note that after installation, enable the HTTPS feature.

![image](https://user-images.githubusercontent.com/5634205/99475728-205b1d80-298a-11eb-8e4e-1f225af8863f.png)


Then trust the rootca of the whistle in the system and enable HTTP proxy in docker daemon. See here https://docs.docker.com/config/daemon/systemd/#httphttps-proxy to configure the HTTPS proxy for the docker daemon.

In the network panel of the whistle, find the failed request during pushing, and show it to me, thanks!

![image](https://user-images.githubusercontent.com/5634205/99475935-8e074980-298a-11eb-9090-6d1b96dd718e.png)

**Comment by KevinWang2015** [comment]
@heww  hi, i can't install whistle by software installation restrictions。
1.  has any other way？

2.  Under what circumstances will the backend application return 401 while docker push image ？

**Comment by heww** [comment]
This issue may be caused by `docker-credential-helpers`, see https://github.com/goharbor/harbor/issues/13553 and https://github.com/docker/docker-credential-helpers/issues/154 for more information.

**Comment by zhaogaolong** [comment]
do you have https gateway server proxy harbor(http)? 

```
| https nginx gateway |
            |
           \|/
      -------------
      | http harbor |
      -------------
```
if this Architecture ， can change proxy mode nginx.conf
```
location /v2/{
  proxy_set_header X-Forwarded-Proto https;  // default $schema
}
```

**Comment by DaNussi** [comment]
I solved the issue by changeing my reverse proxy settings from http to https. (TLS is disabled in harbor) I alsow enabled http2 support in.

I hope this helps someone. (:
