### ISSUE TITLE
Can support database and ldap for Authentication Auth Mode?

### ISSUE THREAD

**Issue by zhengqisong** [goharbor/harbor#13505]
**Is your feature request related to a problem? Please describe.**
Can support database and ldap for Authentication Auth Mode?
ldap auth for user, database auth for programe 

**Describe the solution you'd like**
Now harbor login Auth Mode can only support one database or LDAP, but in our actual work, there will be two roles to user and program. Can the database authentication be used by the program when the authentication mode is LDAP.

**Comment by sluetze** [comment]
Hi zheng,

I think robotaccounts is what you are looking for:
https://goharbor.io/docs/2.1.0/working-with-projects/project-configuration/create-robot-accounts/

This allows you to use "internal" users at least for pull/push.
If you want  to talk to the API for other cases i guess you must create a user in LDAP for the programs.

**Comment by reasonerjt** [comment]
@zhengqisong 

Currently Harbor only supports ONE auth mode.

**Comment by reasonerjt** [comment]
Let me dup this to #13610
