### ISSUE TITLE
Can I edit projectd's push command config?

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13515]
What can we help you?
![image](https://user-images.githubusercontent.com/54056150/99210917-6db08100-280a-11eb-8425-df138f2c842e.png)

저기 192.168.137.111  의 부분이
harbor.yml의  hostname부분입니다.
저기를 static으로 고정하는 config가 있나요?

**Comment by reasonerjt** [comment]
It's determined by the env var `EXT_ENDPOINT` which is populated by `hostname` in harbor.yml.

If you change the env var without resetting `hostname` there may be unexpected problems.
