### ISSUE TITLE
Please provide a way to clean the audit log.

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#13513]
The following is the thread from the harbor channel of CNCF.

```
Is there a clean way to purge Harbor logs (audit_logs) ? I saw in a test environment that you could simply remove them in postgresql, but I guess it's not really advised to do on production.
Reason being I have 75 millions items in Logs, and the page often time-out while loading all of that.
```

I think we can provide a way to clean the audit log like the logs, eg only keeps the audit logs in the latest 30 days, the customer can configure the days of audit logs to be kept. The default configuration is to keep the audit logs forever.

**Comment by wy65701436** [comment]
we can consider to add a option for system admin to reserve logs in days.

**Comment by LiuShuaiyi** [comment]
Should we close this issue now since audit log purge is supported in 2.6?

**Comment by stonezdj** [comment]
We have provided the audit log rotation in 2.6.0
https://goharbor.io/docs/2.7.0/administration/log-rotation/
