### ISSUE TITLE
How to reduce container HTTP access logs

### ISSUE THREAD

**Issue by VoiDeD** [goharbor/harbor#13510]
Harbor version: 2.1.0
HA install via helm chart
K8s version: v.18.8
K8s distro: Rancher v2.4.8

The `registryctl`, `portal`, and `registry` components seem to be logging out HTTP access logs to the container's stdout quite significantly due to the liveness probes associated with them.

registryctl:
```
10.23.4.158 - - [14/Nov/2020:21:32:15 +0000] "GET /api/health HTTP/1.1" 200 9
10.18.64.1 - - [14/Nov/2020:21:32:16 +0000] "GET /api/health HTTP/1.1" 200 9
10.18.64.1 - - [14/Nov/2020:21:32:24 +0000] "GET /api/health HTTP/1.1" 200 9
10.23.4.158 - - [14/Nov/2020:21:32:25 +0000] "GET /api/health HTTP/1.1" 200 9
10.18.64.1 - - [14/Nov/2020:21:32:26 +0000] "GET /api/health HTTP/1.1" 200 9
```

portal:
```
10.18.64.1 - - [14/Nov/2020:21:30:58 +0000] "GET / HTTP/1.1" 200 856 "-" "kube-probe/1.18"
10.18.64.1 - - [14/Nov/2020:21:30:58 +0000] "GET / HTTP/1.1" 200 856 "-" "kube-probe/1.18"
10.23.4.158 - - [14/Nov/2020:21:31:05 +0000] "GET / HTTP/1.1" 200 856 "-" "Go-http-client/1.1"
10.18.64.1 - - [14/Nov/2020:21:31:08 +0000] "GET / HTTP/1.1" 200 856 "-" "kube-probe/1.18"
10.18.64.1 - - [14/Nov/2020:21:31:08 +0000] "GET / HTTP/1.1" 200 856 "-" "kube-probe/1.18"
```

registry:
```
10.23.4.158 - - [14/Nov/2020:21:31:55 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
10.18.64.1 - - [14/Nov/2020:21:31:57 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.18"
10.18.64.1 - - [14/Nov/2020:21:32:01 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.18"
10.23.4.158 - - [14/Nov/2020:21:32:05 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
10.18.64.1 - - [14/Nov/2020:21:32:07 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.18"
10.18.64.1 - - [14/Nov/2020:21:32:11 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.18"
```

Is there a way to reduce this logging without disabling the healthchecks?

I've tried `logLevel: warning` in my chart `values.yaml` but that doesn't seem to change the logging behavior for these 3 apps.

**Comment by reasonerjt** [comment]
You can change the beego's setting of the 3 containers and rebuild the image.

But please make sure you read the related documents as it's not the setting in official build.

**Comment by VoiDeD** [comment]
Thanks for the info. This seems doable, but ideally I'd like to to see this functionality in the upstream so I don't have to diverge with forked container images.

Would you guys be willing to take a contribution that adds support for configuring this?

I'm more of a node & .NET guy so I'm not too familiar with beego (and harbor, for that matter), but I can try hacking away on something.

If that sounds good, I would love some quick pointers for where in the code-base the most ideal place to configure beego's logs module would be - and also how to control that configuration (env var? is there a config file that registryctl/portal/etc are already loading?).

The starting point for my needs is helm's values.yaml, so I may also need a little guidance on how install.sh's harbor.yaml works.

**Comment by mdekoster** [comment]
We have a lot of logging in the harbor-core about a malformed oidc token:

```
2020-12-16T19:24:36Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="a7c76598-2bb7-4cd0-922a-ece39e91c116"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts
2020-12-16T19:24:37Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="3c8055aa7f8d14574a4155385b99c252"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts
2020-12-16T19:24:37Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="8c7499f200ac8ba676ef97d8f0db86eb"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts
```

This is from the kube-probe, that send `ping` requests without oidc token to harbor.  With that many log lines the real information is hard to find in the logfiles. It would be nice if the kube-probe messages are not generate these log lines.
