### ISSUE TITLE
Malformed semversion - helm chart repository cannot be deleted

### ISSUE THREAD

**Issue by mkretzer** [goharbor/harbor#13524]
When uploading a helm chart version and using a space character in the version number the chart can no longer be deleted from the GUI.
The files are beeing deleted from disk, but not from the project.

Deleting the whole chart repository does not help and leads to http/500, caused by multiple http/404 because the files cannot be found. If i touch all the help chart file names in /data/chart_storage/ the repository delete does not lead to server errors, files are deleted from disk again but the delete is also again not reflected in GUI.

- harbor version: [2.1.1]
- docker engine version: [19.03.8]
- docker-compose version: [1.24.0]

core.log:
Nov 16 14:08:47 172.18.0.1 core[686]: 2020-11-16T13:08:47Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"[http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7177.67a273a5.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7252.64cc656b.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7197.80716449.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7202.c18c8129.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7190.62343a37.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7193.59db1a26.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7194.5b1a061e.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7172.47f1e794.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7204.c18c8129.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7239.2a78c5de.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7104.a22bb5eb.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7251.64cc656b.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7105.f3f9ac0e.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-1 2.24.0-7235.6ca0a6fb.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-1 2.24.0-7236.6ca0a6fb.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7080.d83740ca.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7051.9119d033.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7097.eca5bc7f.tgz: no such file or directory http error: code 404, message remove /chart_storage/xxxxx/xxxmanager-2.24.0-7053.fb1a60ac.tgz: no such file or directory]"}]}
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/core/api/chart_repository.go:388, github.com/goharbor/harbor/src/core/api.(*ChartRepositoryAPI).DeleteChart
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/reflect/value.go:460, reflect.Value.call
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/readonly/readonly.go:77, github.com/goharbor/harbor/src/server/middleware/readonly.MiddlewareWithConfig.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/security/security.go:63, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/artifactinfo/artifact_info.go:55, github.com/goharbor/harbor/src/server/middleware/artifactinfo.Middleware.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/lib/orm/orm.go:73, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/csrf/csrf.go:48, github.com/goharbor/harbor/src/server/middleware/csrf.attach.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/vendor/github.com/gorilla/csrf/csrf.go:297, github.com/gorilla/csrf.(*csrf).ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/csrf/csrf.go:68, github.com/goharbor/harbor/src/server/middleware/csrf.Middleware.func2
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
Nov 16 14:08:47 172.18.0.1 core[686]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:2836, net/http.serverHandler.ServeHTTP
Nov 16 14:08:47 172.18.0.1 core[686]: /usr/local/go/src/net/http/server.go:1924, net/http.(*conn).serve
Nov 16 14:08:47 172.18.0.1 core[686]: 2020-11-16T13:08:47Z [WARNING] [/chartserver/chart_operator.go:198]: Malformed semversion 1 2.24.0-7235.6ca0a6fb for the chart xxxmanager
Nov 16 14:08:47 172.18.0.1 core[686]: 2020-11-16T13:08:47Z [WARNING] [/chartserver/chart_operator.go:198]: Malformed semversion 1 2.24.0-7236.6ca0a6fb for the chart xxxmanager

**Comment by ninjadq** [comment]
It's seems your chart version name not handled properly in chartmuseum's cache strategy, you should open an issue on chartmuseum.

As a workaround, you can remove the index file and chart redis cache at the same time to remove the chart shown in harbor UI
