### ISSUE TITLE
[Proposal] Time based Deletion of Logs to comply with GDPR

### ISSUE THREAD

**Issue by sluetze** [goharbor/harbor#13523]
**Is your feature request related to a problem? Please describe.**
Currently Audit Logs are saved for an infinitive (or non configurable) time. Since we are based in Europe we have to comply with GDPR which includes the necessity to save userinformation just for the time it is needed.
Since Audit-Logs inlcude the username, userinformation is saved in auditlog.

**Describe the solution you'd like**
I would like to have a configurable parameter which sets a retention/rotation time for audit logs. This should be configurable via API, Helm-Chart or GUI. Optionally a configuration via Harbor-Tile. A granularity in days should be precise enough. There should be a sane default for the parameter (365 days?).

**Describe the main design/architecture of your solution**
With the granularity of a day, a job is started which checks the age of the entrys in the auditlogs and deletes all entries which are older than the defined value. 

**Describe the development plan you've considered**
N/A

**Additional context**
related to: 
* https://github.com/goharbor/harbor/issues/13513
* https://github.com/goharbor/harbor/issues/13514

For other usecases the size of the logs may be a valid parameter to delete old entries. (i.e. 1GB of logs shall be retained, rest deleted)
I will also push this Issue with my VMware TAM.

**Comment by xaleeks** [comment]
can you point me to the specific GDPR requirement in question here?  Thanks for raising this issue

**Comment by sluetze** [comment]
[GDPR Art 5 (1) (e)](https://gdpr.eu/article-5-how-to-process-personal-data/)
>[  Personal data shall be: ] kept in a form which permits identification of data subjects for **no longer than is necessary** for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’);

[GDPR Art 6 (1)](https://gdpr.eu/article-6-how-to-process-personal-data-legally/) states the necessity of processing the data i.e. for "performance or compliance". The most assessments of the GDPR say, that theses reasons (compliance & performance) begin to shrink over time. So you may have a reason to process the data for a few days/weeks but there ist no reason to be able to tell who was on your system 2 Years ago.

[Here](https://www.termsfeed.com/blog/gdpr-log-data/) is a blog which gives an overview. (searched it for this purpose, I opened the issue, because our internal DataProtectionOfficers are in my neck :) )

**Comment by xaleeks** [comment]
adding this to the backlog

**Comment by Hokwang** [comment]
any updates?

**Comment by lindhe** [comment]
I think this is still an interesting feature!

**Comment by stonezdj** [comment]
Harbor 2.6.0 support rotating the audit log.
see https://github.com/goharbor/harbor/issues/17074.

close it
