### ISSUE TITLE
Common users can not PULL/PUSH when the project name is a pure number

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#13521]
If you are reporting a problem, please make sure the following information are provided:
Common users can not PULL/PUSH when the project name is a pure number，For example, the project name is :123456
![image](https://user-images.githubusercontent.com/18571340/99238232-7158fd80-2834-11eb-9cce-86cc30441f5c.png)
![image](https://user-images.githubusercontent.com/18571340/99238601-e75d6480-2834-11eb-95bd-b79360498269.png)
I tracked the source code, found that the number 123456, matched into a project id, resulting in no project found
![image](https://user-images.githubusercontent.com/18571340/99239031-779ba980-2835-11eb-921c-4d63518a9545.png)
![image](https://user-images.githubusercontent.com/18571340/99239198-add92900-2835-11eb-9ebe-cef52672fe73.png)

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [v1.8.1]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by heww** [comment]
Hi, @koulq the version 1.8.x reached the end of life when 2.0 released. Could you upgrade your harbor instance to the latest?
