### ISSUE TITLE
Harbor not able to pull docker images from Jfrog Registry

### ISSUE THREAD

**Issue by Amrutayan** [goharbor/harbor#13530]
We are getting below error while executing replication of  "docker images" from Jfrog to Harbor.

`status code: 400, body: { "errors" : [ { "status" : 400, "message" : "Ancesstor of level 2 does not exist for manifest.json." } ] } `

Installed Harbor Version: Version v2.1.1-5f52168e
Docker Client Version: 19.03.12
Install Type: Helm3
Jfrog Version: 6.13.1

Harbor Core log Details:

`2020-11-17T06:31:14Z [ERROR] [/replication/operation/controller.go:103]: the execution 12 failed: failed to fetch artifacts: http status code: 400, body: {
  "errors" : [ {
    "status" : 400,
    "message" : "Ancesstor of level 2 does not exist for manifest.json."
  } ]
}`

Please let me know for any additional information.

Thanks
Amrutayan

**Comment by bitsf** [comment]
it seems the image in jfrog is not complete.
you can try docker pull image or replicate some other images

**Comment by Amrutayan** [comment]
> it seems the image in jfrog is not complete.
> you can try docker pull image or replicate some other images


Yeah it works when i give absolute path to the "docker images", but it throws this error "Ancesstor of level 2 does not exist for manifest.json." when i provide the root path of the Jfrog Docker registry.

**Comment by Amrutayan** [comment]
For my understanding what this error exactly means "Ancesstor of level 2 does not exist for manifest.json." . What exactly it is trying to search in the path.

**Comment by chlins** [comment]
@Amrutayan Which your kind of repository of jfrog docker registry, is it local registry? and what your docker regsitry access method, subdomain or additional port or other?

**Comment by Amrutayan** [comment]
- Docker Registry Access method is subdomain. 
- Kind of repository of jfrog docker registry(This is not a local registry, Jfrog is hosted on-premise. Package type docker and API version V2)
