### ISSUE TITLE
Question about ha helm architecture

### ISSUE THREAD

**Issue by eoli3n** [goharbor/harbor#13535]
[https://goharbor.io/docs/2.1.0/install-config/harbor-ha-helm/](https://goharbor.io/docs/2.1.0/install-config/harbor-ha-helm/)
>Architecture
>
>Most of Harbor’s components are stateless now. So we can simply increase the replica of the pods to make sure the components are distributed to multiple worker nodes, and leverage the “Service” mechanism of K8S to ensure the connectivity across pods.
>
>As for storage layer, it is expected that the user provide high available PostgreSQL, Redis cluster for application data and PVCs or object storage for storing images and charts.

I don't understand why Harbor needs external PostgreSQL and Redis cluster to be highly available, what are "application data" ? Data of Harbor application ?
If yes, why not store everything harbor needs on cluster distributed persistent storage ?
If no, is cluster persistent storage like rook-cephfs or longhorn sufficient to store images and charts ?

**Comment by heww** [comment]
The Postgres and Redis build-in don't support HA. You can deploy a Postgres with HA (eg https://github.com/zalando/postgres-operator), and a Redis with sentinel (eg  https://github.com/spotahome/redis-operator). And configure the harbor to store the data in them, then the datastore is HA, this makes the core, jobservice, components are HA.

The "application data" are projects, users, replication registries, replication rules, and everything you can create, modify, delete in the portal of the harbor. These are stored in Postgres and Redis.

Except for the data stored in Postgres and Redis, harbor also needs to store the manifests and blobs of the artifacts. Manifests and blobs often are stored in the filesystem, object storage (s3, minio, OpenStack swift ....). To make the registry component to be HA, you need a PV (filesystem) which supports ReadWriteMany access mode,  or object storage. rook-cephfs used as file storage (not block storage) is ok here, but longhorn may not.

Both Postgres, Redis and the storage used to store manifests and blobs are HA, the harbor is HA (Don't forget to increase the replicas of the components bigger than 1)

The description above will be implemented in version 1.0 of harbor-operator (https://github.com/goharbor/harbor-operator)

**Comment by eoli3n** [comment]
Thanks for your answer :+1:
