### ISSUE TITLE
replication job failed to pushing the blob

### ISSUE THREAD

**Issue by kobetim** [goharbor/harbor#13547]
I deploy harbor HA，there are 3 harbor-jobservice instances，when I execute replicaiton job concurrently the frequency of job failures is very high，the /var/log/harbor/jobservice.log show failed reason：

Nov 18 20:05:52 172.20.0.1 jobservice133557: 2020-11-18T12:05:52Z [ERROR] [/replication/transfer/image/transfer.go:247]: failed to pushing the blob sha256:54ce2410aa8e3bc0f933a2c68f9ea1cdcff5d76a6cf84b5e206e5c0ed8b3df50: **http status code: 400, body: {"errors":[{"code":"DIGEST_INVALID","message":"provided digest did not match uploaded content"**,"detail":{"Digest":"sha256:54ce2410aa8e3bc0f933a2c68f9ea1cdcff5d76a6cf84b5e206e5c0ed8b3df50","Reason":{}}}]}

but when I stop other harbor-jobservice instance，only keep one jobservice instance，that kind of error won't happen.

I doubt，can harbor-jobservice be multiple instances ?

the version of harbor is 2.0.1

docker version
Client: Docker Engine - Community
Version: 19.03.5
API version: 1.40
Go version: go1.12.12
Git commit: 633a0ea
Built: Wed Nov 13 07:25:41 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 19.03.5
API version: 1.40 (minimum version 1.12)
Go version: go1.12.12
Git commit: 633a0ea
Built: Wed Nov 13 07:24:18 2019
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.2.10
GitCommit: b34a5c8af56e510852c35414db4c1f4fa6172339
runc:
Version: 1.0.0-rc8+dev
GitCommit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
docker-init:
Version: 0.18.0
GitCommit: fec3683

docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l 10 Sep 2019

**Comment by heww** [comment]
Could you share your HA arch with us?

**Comment by bitsf** [comment]
if you start with docker-compose, only 1 jobservice could be running and register to harbor-core, not sure what you did you change?
