### ISSUE TITLE
In the case of concurrency replication job Failed high frequency caused by unexpected EOF

### ISSUE THREAD

**Issue by kobetim** [goharbor/harbor#13546]
when I create replication job concurrently (cunrrency is 5)，the frequency of job failures is very high，the /var/log/harbor/jobservice.log show failed reason：

Nov 19 15:26:02 172.20.0.1 jobservice[142745]: 2020-11-19T07:26:02Z [ERROR] [/replication/transfer/image/transfer.go:80]: **Put http://core:8080/v2/**********/blobs/uploads/2c23df4b-8256-422c-9ac8-7fc0f05a3ec9**
?_state=id*********************d-O7cTRLGFnciGH1kUuF***************VuZ2luZS1jbHVzdGVyL3J1bGUtbm9kZS12MS0wMzItMDAwMDAwNyIsIlVVSUQiOiIyYzIzZGY0Yi04MjU2LTQyMmMtOWFjOC03ZmMwZjA1YTNlYzkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjAtMTEtMTlUMDc6MjU6M
DEuMDQwMjQ3MjNaIn0%!D(MISSING)&digest=sha256%!A(MISSING)29b3fe9bc04d7ce1a8979de8ea679fd81de73bd9875a60435d595081a801ad96: **readfrom tcp 172.20.0.7:42916->172.20.0.6:8080: unexpected EOF**
Nov 19 15:26:02 172.20.0.1 jobservice[142745]: 2020-11-19T07:26:02Z [ERROR] [/replication/transfer/image/transfer.go:80]: got error during the whole transfer period, mark the job failure
Nov 19 15:26:02 172.20.0.1 jobservice[142745]: 2020-11-19T07:26:02Z [ERROR] [/jobservice/runner/redis.go:109]: Job 'REPLICATION:5235d54e0a6b837b8cb72a1c' exit with error: run error: got error during the whole transfer period, mark the job fa
ilure

if the cunrrency is 1，it's not going to happen this error.

the version of harbor is 2.0.1

**docker version**
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**docker-compose version** 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by bitsf** [comment]
Where did you replication from ?
It seems the network broken which caused EOF reading.
Or maybe memory is not enough, something crashed.
