### ISSUE TITLE
proxy-cache support for privare registries on quay.io

### ISSUE THREAD

**Issue by mfld** [goharbor/harbor#13540]
As of now "Harbor only supports proxy caching for Docker Hub and Harbor registries." (harbor documentation version 2.x)
I would like for support of proxy caching from private quay.io registries to be added.

Hope that is possible within a foreseeable future.

/best regards

**Comment by alanmbarr** [comment]
Would be nice to see support for the Microsoft registries mcr.microsoft.com

**Comment by nfrush** [comment]
I'd like to see general agnosticism about the proxy_cache (i.e the registry shouldn't matter. I'm sure plenty will want to mirror quay.io, gcr.io, etc.)

**Comment by jgallucci32** [comment]
@mfld Have you tried configuring quay to pretend it is an upstream Harbor registry? I was able to successfully configure Elastics Docker Registry (which I highly doubt is running Harbor) as a Harbor registry and it is an active proxy cache in our environment.

I suspect this can be done with Quay and many others. Never hurts to lie to software, it doesn't have feelings :)

**Comment by xaleeks** [comment]
Can we look into supporting this for v2.2 release?  I'm referring to quay.io which is being used as a public registry by lots of OSS projects.  @steven-zou @stonezdj

**Comment by jgallucci32** [comment]
@xaleeks It should be easy enough to support, I just tested Quay.io as a proxy cache in v.2.1.1 and so far it works as expected. Here is a screenshot of the **Registries** configuration for Quay
![image](https://user-images.githubusercontent.com/9018897/100520828-dd9d0080-3154-11eb-8402-a64665d51a5c.png)
Here is the **Project** configuration
![image](https://user-images.githubusercontent.com/9018897/100520861-0f15cc00-3155-11eb-8097-4369571d27b8.png)
I was able to successfull pull an image using the pull-through cache method
```
# docker pull harbor.domain.local/quay-cache/projectquay/quay:latest
latest: Pulling from quay-cache/projectquay/quay
3c72a8ed6814: Pull complete
1f951c9622b2: Pull complete
9474431ed19b: Pull complete
6aa67e7feeb0: Pull complete
72a79400d249: Pull complete
8fd7d6347115: Pull complete
aa2672eeef17: Pull complete
ccefd4a2888c: Pull complete
3e76bb81bc4c: Pull complete
6a51add8f612: Pull complete
eb0698c7af6d: Pull complete
640b9ec846cf: Pull complete
9d2cd2b8ae9d: Pull complete
db18a7e74cea: Pull complete
bda2445b0403: Pull complete
2cdddc396fd9: Pull complete
3305320c4898: Pull complete
Digest: sha256:4a3c4c0fc2d05187c28d4fa289801ea0c80a271223ae39bd435e55e6f4ab8588
Status: Downloaded newer image for harbor.domain.local/quay-cache/projectquay/quay:latest
harbor.domain.local/quay-cache/projectquay/quay:latest
```

**Comment by xaleeks** [comment]
@jgallucci32 Thanks for the validation, good to know it works!  it's just that the quay.io replication adapter is quite fragile and breaks often due to api break changes on Quay's side.

**Comment by m-yosefpor** [comment]
Thanks, great news. when will be the estimate release for 2.2?

**Comment by stonezdj** [comment]
yes, #13897 merged

**Comment by dbaltor** [comment]
I've tested proxying to mcr.microsoft.com with harbor 2.1 and it works fine. Here is the configuration I used:
```
Provider: Docker registry
URL: https://mcr.microsoft.com
```

**Comment by ShalbafZadeh** [comment]
@dbaltor  and how you do use it  ? assume that we create a project named mcrproxy 
then for example pulling dotnet core 5 image mcr.microsoft.com/dotnet/sdk:5.0
running 
HARBOR_URL/mcrproxy/dotnet/sdk:5.0
fails with 
```
Error response from daemon: unknown: repository mcrproxy/dotnet/sdk not found

**Comment by dbaltor** [comment]
HI @ShalbafZadeh, my previous comment was wrong. We used in fact Harbor 2.2 and **Azure Container Registry** as provider. I tested with  `docker pull <harbor-hostname>/windows/servercore/iis:windowsservercore-ltsc2019`
