### ISSUE TITLE
“Default disk space per project” don't work

### ISSUE THREAD

**Issue by zhangwenlong8911** [goharbor/harbor#13551]
i used harbor 2.1.0, in set "project quotas->Default disk space per project",but is always show "0Byte of unlimited",is it a bug?

The machine information is:
[root@node2 harbor]# docker-compose -v
docker-compose version 1.27.4, build unknown
[root@node2 harbor]# docker -v
Docker version 18.06.3-ce, build d7080c1
[root@node2 harbor]# uname -a
Linux node2 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by heww** [comment]
Could you share the log of the core component when setting the default quota?
