### ISSUE TITLE
There is no prepare-swagger.sh 

### ISSUE THREAD

**Issue by zhangwenlong8911** [goharbor/harbor#13552]
i want to test zhe API of harbor,
The official [documentation](https://goharbor.io/docs/2.1.0/build-customize-contribute/configure-swagger/) says that the test script can be downloaded by[prepare-swagger.sh](https://raw.githubusercontent.com/goharbor/harbor/master/docs/prepare-swagger.sh) but the download link does not exist. How can I get the script

**Comment by heww** [comment]
I'm so sorry that the doc is out of date about `View and Test the Harbor REST API via Swagger`.

Harbor includes the feature described in that section of the doc from v1.8.  Please see https://goharbor.io/docs/2.1.0/working-with-projects/using-api-explorer/ for more information.

**Comment by zhangwenlong8911** [comment]
ok ,thanks

**Comment by alexivkin** [comment]
Ran into the same outdated doc on 2.2. Could you please remove it?

**Comment by alexivkin** [comment]
Ah, yeah, even the [updated page](https://goharbor.io/docs/2.1.0/working-with-projects/using-api-explorer) is no longer correct. The Harbor API link is at the bottom, under the theme color switch, and no longer looks like a button. Correct?

**Comment by a-mccarthy** [comment]
This should be fixed by the the PR linked above. if you are still noticing this issue, please reopen. thanks
