### ISSUE TITLE
Add Registries in harbor v2.1.0 failed

### ISSUE THREAD

**Issue by yehaifeng** [goharbor/harbor#13563]
I want to add a registriy for replication, but it is failed.

Harbor version: v2.1.0

NETWORK: office harbor --> haproxy --> pro harbor

LOGS from office harbor:
```
Nov 20 12:53:43 172.25.0.1 core[17676]: 2020-11-20T04:53:43Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 880642d3-be20-498c-a1df-542bd19675d7 to the logger for the request POST /api/v2.0/registries/ping
Nov 20 12:53:43 172.25.0.1 core[17676]: 2020-11-20T04:53:43Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /api/v2.0/registries/ping
Nov 20 12:53:43 172.25.0.1 core[17676]: 2020-11-20T04:53:43Z [DEBUG] [/server/middleware/security/session.go:47][requestID="880642d3-be20-498c-a1df-542bd19675d7"]: a session security context generated for request POST /api/v2.0/registries/ping
Nov 20 12:53:44 172.25.0.1 core[17676]: 2020-11-20T04:53:44Z [DEBUG] [/replication/adapter/harbor/adaper.go:48]: API version is v2.0, create the v2 adapter
Nov 20 12:53:46 172.25.0.1 core[17676]: 2020-11-20T04:53:46Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://vipharbor.99bill.com: http status code: 401, body:
Nov 20 12:53:46 172.25.0.1 core[17676]: 2020-11-20T04:53:46Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}
```

LOGS from pro harbor:
```
Nov 20 13:15:10 172.22.0.1 proxy[2185381]: 172.21.197.111 - "POST /api/v2.0/registries/ping HTTP/1.1" 401 62 "-" "curl/7.29.0" 0.0020.001 .
```

Use cmd `docker login` in office harbor is succeed, i can push image else. 

I confirm that user and password are correct!

**Comment by heww** [comment]
Do you mean to add `pro harbor` as a registry in `office harbor`? If so, please input the username and password of the `pro harbor` not the username and password of `office harbor`.

**Comment by yehaifeng** [comment]
> Do you mean to add `pro harbor` as a registry in `office harbor`? If so, please input the username and password of the `pro harbor` not the username and password of `office harbor`.

Yes, I see something for this problem.
I add a dns resolve to /etc/hosts in host, but this don't take effect in docker containers of harbor. And i add it to containers to solve.
This is my change to file docker-compose.yml:
```
    extra_hosts:
      - "vipharbor.99bill.com:190.21.197.109"
```

But what are the methods for debug, this is no any tool in containers?

**Comment by heww** [comment]
Using command `docker run -it --pid=container:harbor-core --net=container:harbor-core --cap-add sys_admin ubuntu bash` to debug the network problem of harbor-core in ubuntu system.

See https://medium.com/@rothgar/how-to-debug-a-running-docker-container-from-a-separate-container-983f11740dc6 for more information on how to debug a container which lacks tools in it.

**Comment by yehaifeng** [comment]
@heww 
I have a test in my test env
```
[root@b92c5902b64a /]# ping vipharbor.99bill.com  # container
PING vipharbor.99bill.com (192.168.112.200) 56(84) bytes of data.
64 bytes from 192.168.112.200 (192.168.112.200): icmp_seq=1 ttl=62 time=0.284 ms
64 bytes from 192.168.112.200 (192.168.112.200): icmp_seq=2 ttl=62 time=0.256 ms
^C
--- vipharbor.99bill.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.256/0.270/0.284/0.014 ms
[root@b92c5902b64a /]# exit
[root@harbor ~]$ ping vipharbor.99bill.com  # host
PING vipharbor.99bill.com (192.168.9.48) 56(84) bytes of data.
64 bytes from vipharbor.99bill.com (192.168.9.48): icmp_seq=1 ttl=64 time=0.269 ms
64 bytes from vipharbor.99bill.com (192.168.9.48): icmp_seq=2 ttl=64 time=0.211 ms

```

I have a hosts in host:
```
192.168.9.48 vipharbor.99bill.com
```
But not in container:
```
[root@b92c5902b64a /]# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.27.0.8	b92c5902b64a
```

**Comment by yehaifeng** [comment]
@heww 
Is it possible to add an add HOSTS function in harbor.yml?

**Comment by heww** [comment]
We don't have a plan to add HOSTS in harbor.yml.
