### ISSUE TITLE
Small typos in variable

### ISSUE THREAD

**Issue by sluetze** [goharbor/harbor#13568]
Hi,
while doing #13511 the reviewers found some small typos in the Key Naming, which exist in the code and in the language-files.

Shall I fix this in source and all translations?
If yes in #13511 or in a new PR?

Keys are:
```bash
OIDC_ENDPOIT_FORMAT #missing N
ADMIN_CIL_SECRET_BUTTON #confused CIL and CLI i guess
ADMIN_CIL_SECRET_RESET_BUTTON #confused CIL and CLI i guess
RESET_Ok #lowercase k
```

Furthermore there is `ISADMNISTRATOR` in `src/portal/src/app/user/user.component.ts`

Best Regards
--sluetze

**Comment by heww** [comment]
Better fix it in source and all translations, another PR to fix this is welcome, thanks!

**Comment by sluetze** [comment]
Sure, will do so. Can you confirm, that CIL is a typo for CLI and i'm not misunderstanding the naming?
