### ISSUE TITLE
Harbor v2.0.0 list artifact api report mismatch "signed" info comparing to portal

### ISSUE THREAD

**Issue by overmike** [goharbor/harbor#13567]
**Expected behavior and actual behavior:**
I am using docker content trust to push and sign my images. I was able to see the the tick mark on signed column at repository artifact page. but when I use api, it always report signed=false for all images. no idea if configuration issue or api bug
`{'artifact_id': 2863, 'id': 2739, 'immutable': False, 'name': '1.0.0', 'pull_time': '0001-01-01T00:00:00.000Z', 'push_time': '2020-11-12T07:46:23.804Z', 'repository_id': 483, 'signed': False}`

**Steps to reproduce the problem:**
1. docker push an image with content trust setup
2. log in to harbor portal, repository artifact that you just push
3. make sure there is a tick mark on signed column
4. use api on path `projects/{}/repositories/{}/artifacts`
5. expect to see the signed field is true

**Versions:**

- harbor version: [2.0.0]
- docker engine version: [19.03.13]
- docker-compose version: [1.24.1]

**Additional context:**

**Comment by ywk253100** [comment]
Request the API with the query sting `with_signature=true`: https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L986

**Comment by ChristianCiach** [comment]
That changes nothing. The issue is still valid. When `GET`ting the `/artifacts` endpoint with `with_tags=true&with_signature=true`, the result will always state `'signed': False` for all artifacts, even though they are all signed. Also, the cosign signature artifact (tag-name ending with `.sig`) is *never* included in the returned tags.

**Comment by ChristianCiach** [comment]
The "signed" attribute is only use for Notary, not for cosign. See https://github.com/goharbor/harbor/issues/17595#issuecomment-1257747657
