### ISSUE TITLE
The length of job_parameters column in admin_job table is tool short, in case of redis+sentinel

### ISSUE THREAD

**Issue by GyeonSeon** [goharbor/harbor#13577]
The length of job_parameters in admin_job is tool short, in case of redis+sentinel

Can NOT run GC NOW or schedule to GC in Garbage Collection menu.

**Error:**
It is not possible to run/set GC.
Redis+Sentinel is used.

< core log >
```
2020-11-23T08:21:22Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"pq: value too long for type character varying(255)"}]} 
2020-11-23T08:21:36Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"pq: value too long for type character varying(255)"}]} 
```

< postgresql log >
```
2020-11-23 08:21:22.439 GMT [348458] ERROR:  value too long for type character varying(255)
2020-11-23 08:21:22.439 GMT [348458] STATEMENT:  insert into admin_job (job_name, job_parameters, job_kind, status, job_uuid, cron_str, creation_time, update_time) values ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
2020-11-23 08:21:36.971 GMT [348773] ERROR:  value too long for type character varying(255)
2020-11-23 08:21:36.971 GMT [348773] STATEMENT:  insert into admin_job (job_name, job_parameters, job_kind, status, job_uuid, cron_str, creation_time, update_time) values ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
```

**Versions:**
- harbor version: 2.1.1
- docker engine version: 19.03.13
- kubernetes version: 1.19.4

**Additional context:**
I found that the length of job_parameters in admin_job is tool short to hold data.
The length is 255. In case of using Redis+Sentinel and mulitiple pods of redis,
job_parameters is too short.

postgres=# \c registry
You are now connected to database "registry" as user "postgres".

registry=# \d admin_job
                                          Table "public.admin_job"
     Column     |            Type             | Collation | Nullable |                Default                
----------------+-----------------------------+-----------+----------+---------------------------------------
...
 job_parameters | character varying(255)     |           |          | ''::character varying

After I changed the length to 1024, the problems hase been solved.
I found that the lengh is over 255.
registry=# \d admin_job
                                          Table "public.admin_job"
     Column     |            Type             | Collation | Nullable |                Default                
----------------+-----------------------------+-----------+----------+---------------------------------------
...
 job_parameters | character varying(1024)     |           |          | ''::character varying
 
registry=# select  * from admin_job;
 id | job_name | job_kind |                cron_str                |  status  |         job_uuid         |    creation_time    |        update_time         | deleted |  revision  | statu
s_code |                                                                                                                                         job_parameters                           
                                                                                                              
----+----------+----------+----------------------------------------+----------+--------------------------+---------------------+----------------------------+---------+------------+------
-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
  8 | IMAGE_GC | Generic  | {"type":"Manual","cron":""}            | finished | dd2a266ff9092971edf5e067 | 2020-11-23 09:30:09 | 2020-11-23 09:30:09.278924 | f       | 1606123809 |      
     3 | {"delete_untagged":false,"dry_run":false,"redis_url_reg":"redis+sentinel://redis:1qaz2wsx@harbor-redis-node-0.harbor-redis-headless:26379,harbor-redis-node-1.harbor-redis-headle
ss:26379,harbor-redis-node-2.harbor-redis-headless:26379/mymaster/2?idle_timeout_seconds=30","time_window":2}

**Comment by wy65701436** [comment]
you can just refer this response to get details. https://github.com/goharbor/harbor/issues/13262#issuecomment-709288478

**Comment by GyeonSeon** [comment]
The answer(#13262 (comment)) is
```
@Paul-Michaud considering we are deprecating the admin job mechanism, hopefully you can reduce the length?
```

When is deprecating the admin job mechanism supposed to be applied?
If there are no changes in the near future, I would like respected contributors to resize the size of the column.
Please.

**Comment by wy65701436** [comment]
the deprecating will happen in v2.2, so you can temporary modify the DB scheme in your environment, and wait for the coming release.

**Comment by Hokwang** [comment]
@wy65701436 
Hi, something will be deprecated in v2.2 but your team will support v2.1 still, right? why don't you fix this little thing?

**Comment by wy65701436** [comment]
As 2.2 is RCed, close it as fixed.
