### ISSUE TITLE
Harbor cannot replicate from jfrog artifactory if access method on sub domain

### ISSUE THREAD

**Issue by alexcasutt** [goharbor/harbor#13576]
If artifactory has set the docker access method on "sub domain", harbor 2.1.1 is not able to replicate images. With harbor 2.0.1 it was possible.
Error:
`2020-11-23T09:32:52Z [ERROR] [/replication/transfer/image/transfer.go:322]: failed to pull the manifest of artifact docker/nginx:latest: http status code: 404, body: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"The named manifest is not known to the registry.","detail":{"manifest":"docker/nginx"}}]}`

`2020-11-23T09:32:52Z [ERROR] [/replication/transfer/image/transfer.go:175]: http status code: 404, body: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"The named manifest is not known to the registry.","detail":{"manifest":"docker/nginx"}}]}`

`2020-11-23T09:32:52Z [ERROR] [/replication/transfer/image/transfer.go:181]: got error during the whole transfer period, mark the job failure`

docker/nginx -> docker is the virtual repository on artifactory.

Artifactory Version: 7.11.2
Harbor Version: 2.1.1

There have been similar issues with jfrog, but with other error messages. #12429

**Comment by chlins** [comment]
@alexcasutt Can you try to use docker-registry adapter as your registry to verify your scene?

**Comment by alexcasutt** [comment]
Hi @chlins 
With docker-registry it worked.. I understand, in SubDomain-Mode Artifactory acts as a "normal" registry and the jfrog-adapter works at the moment only with the repository-path-mode.

**Comment by chlins** [comment]
> Hi @chlins
> With docker-registry it worked.. I understand, in SubDomain-Mode Artifactory acts as a "normal" registry and the jfrog-adapter works at the moment only with the repository-path-mode.

Yep, if use subdomain, the behavior of jfrog docker registry is same with normal 'docker registry', but we provide jfrog adapter to handle more complex scene, like replicate images from jfrog multi docker registry(not specify one registry), so when use jfrog adapter, you need configure the registry endpoint to your jfrog server url instead of just specify docker registry endpoint.

**Comment by alexcasutt** [comment]
Ok, thanks alot for the info! 
Regards
