### ISSUE TITLE
CSRF token invalid

### ISSUE THREAD

**Issue by xgy560501** [goharbor/harbor#13570]
I tried to use python to excute harbor api.I tried to excute the url "https://xxxxxx/c/login" but i got the error "{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "CSRF token invalid"
        }
    ]
}"

**Comment by reasonerjt** [comment]
`/c/login` is to be called from UI

**Comment by xgy560501** [comment]
How to login the platform to use the api?

**Comment by xgy560501** [comment]
How to get the X-Harbor-CSRF-Token:

**Comment by heww** [comment]
The harbor supports basic authorization for the APIs. Disable the cookie for the python client when you don't want to deal with the CSRF token during the API request.

**Comment by xgy560501** [comment]
I use basic authorization to login,it still returns error. Here is the authorization data. {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic YWdddddsdfewfsdfdewrewrI='}

**Comment by xgy560501** [comment]
> 港口支持API的基本授权。当您不想在API请求期间处理CSRF令牌时，请禁用python客户端的cookie。

I use basic authorization to login,it still returns error. Here is the authorization data. {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0', 'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'Basic YWdddddsdfewfsdfdewrewrI='}

**Comment by xgy560501** [comment]
Here is my demo.
import json
import requests
from pprint import pprint
from requests.auth import HTTPBasicAuth
data_json = {
  "count_limit": -1,
  "project_name": "sdfsdf",
  "cve_whitelist": {
    "items": [
      {
        "cve_id": "0"
      }
    ],
    "project_id": 0,
    "id": 0,
    "expires_at": 0
  },
  "storage_limit": -1,
  "metadata": {
    "public": "false"
  }
}
req_url = 'https://******/api/v2.0/projects'
header_dict = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0', 'Content-Type': 'application/json'}
req_handler = requests.post(req_url, data=data_json, auth=('admin', '*****'))
print(req_handler.json())

**Comment by bitsf** [comment]
fix his demo
```
import requests
from pprint import pprint
from requests.auth import HTTPBasicAuth
data_json = {
"count_limit": -1,
"project_name": "aaaa",
"cve_whitelist": {
"items": [
{
"cve_id": "0"
}
],
"project_id": 0,
"id": 0,
"expires_at": 0
},
"storage_limit": -1,
"metadata": {
"public": "false"
}
}
req_url = 'http://10.193.3.250/api/v2.0/projects'
header_dict = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36', 'Content-Type': 'application/json'}
req_handler = requests.post(req_url, json=data_json, auth=('admin', 'Harbor12345'))
print(req_handler.status_code)
```
