### ISSUE TITLE
How do I get notifications? mail?

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13580]
How do I get notifications?

When the image of the project is pushed, pulled, or deleted
I want to notify the registered user of the project by mail.

There is a webhook, but if you have a related manual or setting method, please share it.

**Comment by heww** [comment]
The doc about the webhook is here https://goharbor.io/docs/2.1.0/working-with-projects/project-configuration/configure-webhooks/

**Comment by heww** [comment]
Closed as we can do this with webhook.
