### ISSUE TITLE
To check version compatibility to integrate the external Database in harbor with postgresql v 9.4

### ISSUE THREAD

**Issue by shankartcs2004** [goharbor/harbor#13588]
Currently harbor v2.1.1 is installed on CentOS 7,  I need to intergrate the external Database in harbor with postgresql 9.4 version. Would it be compatible? Please share your thoughts.

**Comment by heww** [comment]
We didn't test the integration with Postgres 9.4.

The special feature we used in Postgres is that some data is stored in json/jsonb type.
