### ISSUE TITLE
Can I log in when the redis server is down?

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13583]
Built external DB, redis.

When I stopped redis, I couldn't log in.
If redis goes down during the service, is the service a problem?
Is there a setting to log in from the DB when redis is down?

**Comment by heww** [comment]
Currently, we can't log in to the portal when the Redis is down. 

You can use a Redis sentinel as the Redis service for the HA. Harbor supports Redis sentinel from v2.1.
