### ISSUE TITLE
function goSliceInitializer not defined

### ISSUE THREAD

**Issue by GitSoftwareNow** [goharbor/harbor#13608]
root@kube4s#make all

**Comment by heww** [comment]
Could you share the output of the `make all` and give more information?

**Comment by GitSoftwareNow** [comment]
build swagger image successfully
generate all the files for API from api/v2.0/swagger.yaml
could not complete template processing in directory "/root/harbor/tools/swagger/templates": could not add template: failed to load template serverResponses: template: serverResponses:114: function "goSliceInitializer" not defined
make: *** [Makefile:313：gen_apis] error 1

**Comment by AlawnWong** [comment]
i meet the same problem.
and, how to compile the v2.2.1 ?
