### ISSUE TITLE
unable to define JFrog Artifactory 7 as registry endpoint

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#13604]
**Expected behavior and actual behavior:**
When I try to define new Registry endpoint for JFrog Artifactory 7 I get an error `Failed to ping endpoint.`
It seems to be using the `native` adapter instead of `jfrog`.

My current version of JFrog Artifactory is 7.9.1.

**Steps to reproduce the problem:**
1. Try to create new endpoint of type/provider JFrog Artifactory with Endpoint URL `https://artifactory.example.com`

relevant entry from `core.log`
```
Nov 25 11:43:24 172.22.0.1 core[1957]: 2020-11-25T10:43:24Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://artifactory.example.com: http status code: 404, body: {
Nov 25 11:43:24 172.22.0.1 core[1957]:   "errors" : [ {
Nov 25 11:43:24 172.22.0.1 core[1957]:     "status" : 404,
Nov 25 11:43:24 172.22.0.1 core[1957]:     "message" : "Not Found"
Nov 25 11:43:24 172.22.0.1 core[1957]:   } ]
Nov 25 11:43:24 172.22.0.1 core[1957]: }
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.1
- docker engine version: 19.03.12
- docker-compose version: 1.18.0

**Comment by chlins** [comment]
@balonik You can try to `curl https://artifactory.example.com/v2/` and check the response.

**Comment by balonik** [comment]
@chlins same result

```
Nov 26 08:33:41 172.24.0.1 core[1957]: 2020-11-26T07:33:41Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://artifactory.example.com/v2: http status code: 404, body: {
Nov 26 08:33:41 172.24.0.1 core[1957]:   "errors" : [ {
Nov 26 08:33:41 172.24.0.1 core[1957]:     "status" : 404,
Nov 26 08:33:41 172.24.0.1 core[1957]:     "message" : "Not Found"
Nov 26 08:33:41 172.24.0.1 core[1957]:   } ]
Nov 26 08:33:41 172.24.0.1 core[1957]: }
```

related entries in JFrog Artifactory log, first line is when trying to ping without the `/v2/` path, second line is with the `/v2/` path.

```
2020-11-26T07:35:32.378Z [jfrt ] [WARN ] [2cf67df22017a668] [o.a.w.s.RequestUtils:157      ] [http-nio-8081-exec-8] - Request /v2/ should be a repo request and does not match any repo key
2020-11-26T07:35:37.403Z [jfrt ] [WARN ] [1336f1a22515a895] [o.a.w.s.RequestUtils:157      ] [http-nio-8081-exec-2] - Request /v2/v2/ should be a repo request and does not match any repo key
```

**Comment by balonik** [comment]
After playing with the setup I found the root cause. Our Nginx proxy was configured for Sub-Domain access method as described in `https://www.jfrog.com/confluence/display/JFROG/HTTP+Settings#HTTPSettings-DockerReverseProxySettings`
However, Harbor currently needs Direct Access method to ping the registry endpoint. Updating our Nginx proxy config to support both options resolved the issue. I thing this could be mentioned in documentation somewhere as JFrog supports 3 access methods for Docker.

Optionally, I have also tried configuring Registry endpoint in Harbor to sub-domain URL `https://docker-repo.artifactory.example.com` which worked fine and Registry endpoint was added ok. But any configured push replication rules failed with following error:

```
Nov 25 11:44:30 172.22.0.1 core[1957]: 2020-11-25T10:44:30Z [ERROR] [/replication/adapter/jfrog/adapter.go:150]: Create Namespace testnamespace error: http error: code 403, message {
Nov 25 11:44:30 172.22.0.1 core[1957]:   "errors" : [ {
Nov 25 11:44:30 172.22.0.1 core[1957]:     "status" : 403,
Nov 25 11:44:30 172.22.0.1 core[1957]:     "message" : "Forbidden"
Nov 25 11:44:30 172.22.0.1 core[1957]:   } ]
Nov 25 11:44:30 172.22.0.1 core[1957]: }
Nov 25 11:44:30 172.22.0.1 core[1957]: 2020-11-25T10:44:30Z [ERROR] [/replication/operation/controller.go:103]: the execution 52 failed: failed to do the prepare work for pushing/uploading resources
: http error: code 403, message {
Nov 25 11:44:30 172.22.0.1 core[1957]:   "errors" : [ {
Nov 25 11:44:30 172.22.0.1 core[1957]:     "status" : 403,
Nov 25 11:44:30 172.22.0.1 core[1957]:     "message" : "Forbidden"
Nov 25 11:44:30 172.22.0.1 core[1957]:   } ]
Nov 25 11:44:30 172.22.0.1 core[1957]: }
```

I resolved my issue. In case you would like to support the sub-domain method as well just let me know if I can help.

**Comment by chlins** [comment]
@balonik I found a similar issue (https://github.com/goharbor/harbor/issues/13576), i hope this can provide some additional infos for you.

**Comment by balonik** [comment]
> @balonik I found a similar issue (#13576), i hope this can provide some additional infos for you.

Thanks, I found that issue as well, but since that was about pulling from Artifactory and I push to Artifactory I have raised a new issue. I didn't want to hijack closed issue.

Anyway, this is resolved for me. I understand that sub-domain method is not supported at the moment and I have switched to direct access (repository path access).

**Comment by chlins** [comment]
We will add some configuration notes(docs)  explain this issue.
