### ISSUE TITLE
OIDC with google groups problem

### ISSUE THREAD

**Issue by shvepsy** [goharbor/harbor#13609]
Unfortunately I can't find any ways to use google groups in Harbor v2.1 with OIDC auth.

One of reasons could be impossibility use scope url in 'OIDC Scope' field. 

Can you explain current or planing ways to solve this. Thanks

**Comment by reasonerjt** [comment]
@shvepsy 

I'm not sure how google is populating the group info into the ID token.

Could you please elaborate
```
One of reasons could be impossibility use scope url in 'OIDC Scope' field.
```

**Comment by shvepsy** [comment]
In other system we can write url  at scope list, like - https://www.googleapis.com/auth/admin.directory.group.readonly
where we can find with dots name of scope. Unfortunately 'OIDC Scope' field don't support any from those types.

**Comment by fooka03** [comment]
Wanted to mention this is still an issue.  We can probably work around this by using Dex, but it would be nice for oidc to support url based claims, specifically for Google but there may be other providers that don't expose claims directly in the jwt.

**Comment by nfoucha** [comment]
@reasonerjt what additional information do you need to address this issue?

**Comment by jobcespedes** [comment]
Hi,

I was able to add `https://www.googleapis.com/auth/admin.directory.group.readonly` scope using [api directly](https://goharbor.io/docs/2.8.0/install-config/configure-system-settings-cli/). It enables Google consent page asking for that scope.  However, I can't fetch groups yet. I got the error `Unable to get groups from claims`  and `groups claims key: groups`. It seems there are no group info in the response

**Comment by much-pedrorodrigues** [comment]
+1 Is there any progress on this, or intentions of making this work with Google IAM groups??

**Comment by fatsolko** [comment]
still need Google IAM groups

**Comment by discostur** [comment]
Still an issue in 2025 ...
