### ISSUE TITLE
What does v1.10.6 update

### ISSUE THREAD

**Issue by 7error** [goharbor/harbor#13613]
I notice that v1.10.6 is released, but here is nothing in the `full list of issues fixed in v1.10.6` with this link https://github.com/goharbor/harbor/issues?q=is%3Aissue+label%3Atarget%2F1.10.6+is%3Aclosed

**Comment by heww** [comment]
The v1.10.6 update is here https://github.com/goharbor/harbor/issues?q=label%3Atarget%2F1.10.6+is%3Aclosed+
