### ISSUE TITLE
harbor gcp push synchronization to GCP with nested source directory structure

### ISSUE THREAD

**Issue by mmilbrath** [goharbor/harbor#13628]
**Expected behavior and actual behavior:**
I use harbor for on-premise registry and then push images to GCP registry.    Several of the images I want to push out are in a nested directory structure repository/foo/image:tag.    I can push to the GCP registry successfully only if I put the GCP project ID as the destination namespace.    Unfortunately when I do this though, I lose the source hierarchy of <foo>.

This may be the expected behavior but if so then seems like there is no easy way to push and mirror images from harbor to GCP GCR that have nested directory structure?

**Steps to reproduce the problem:**

1. Create image with repository/nested_dir/image:tag within harbor
2. Replicate to GCP registry by only using project id as target namespace

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.1-5f52168e

**Workaround**

I can of course create a replication rule for each image that has a nested directory structure but seems like should be a better option.

**Comment by heww** [comment]
The harbor will support this feature in v2.2 or v2.3.

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/13549
