### ISSUE TITLE
transparent proxy cache 

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#13627]
merge the work done here https://github.com/indeedeng-alpha/harbor-container-webhook into goharbor

**Comment by stonezdj** [comment]
We'd like to move to 2.3.0 release

**Comment by xaleeks** [comment]
sounds good

**Comment by steven-zou** [comment]
Planed into the harbor-operator [plan](https://github.com/goharbor/harbor-operator/projects/7), the close issue here.
