### ISSUE TITLE
fresh install, change log level to 'warning', registry and registryctl will be in restart/loop state

### ISSUE THREAD

**Issue by piengeng** [goharbor/harbor#13624]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
following new setup instruction, I change the harbor.yml's log level to 'warning' then proceed to execute the install.sh script. The `docker-compose ps` setup should say all Up (healthy) except notary*, however regitry+registryctl is in restart/looping state

**Steps to reproduce the problem:**
as above

**Versions:**
- harbor version: [2.1.1]
- docker engine version: [19.03.13]
- docker-compose version: [1.25.4]

**Additional context:**
none

**Comment by wy65701436** [comment]
@ninjadq seem that we have to map the level warning to warn for registry & registryctl.
