### ISSUE TITLE
docs on lost Notary keys

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#13646]
add a section to docker content trust docs on how to resolve orphaned images if user accidentally deleted notary root key and did not backup properly.

**Comment by reasonerjt** [comment]
I've verified following steps as workaround to remove the signature of images on v2.1.1, docker-compose installation:

1. Remove data from notarysigner and notaryserver DB:
```
# docker exec -it harbor-db /bin/bash
postgres [ / ]$ psql
....
postgres=# \c notaryserver
notaryserver=# delete from tuf_files where gun='xxxxx/library/alpine';
....
notaryserver=# \c notarysigner
notarysigner=# delete from private_keys where gun='xxxxxx/library/alpine';
notarysigner=# \q
```
2.Restart `harbor-core` to clear some temporary cache.
```
# docker restart harbor-core
```

You need to replace the `xxxxx/library/alpine` as the fully qualified URI of your repo in the SQL commands.
