### ISSUE TITLE
failed to login harbor

### ISSUE THREAD

**Issue by carrieyang1212** [goharbor/harbor#13648]
No response at harbor

**Comment by YahuiAn** [comment]
see #12753 , maybe redis is wrong

**Comment by yangli1212** [comment]
![image](https://user-images.githubusercontent.com/57127288/100700787-485e6e00-33d9-11eb-805a-e8a1b593b642.png)
![Uploading image.png…]()

**Comment by yangli1212** [comment]
![image](https://user-images.githubusercontent.com/57127288/100700828-6035f200-33d9-11eb-9b7a-c79c9aca81a1.png)

**Comment by yangli1212** [comment]
![image](https://user-images.githubusercontent.com/57127288/100700870-78a60c80-33d9-11eb-8d3a-e8c32c2311b9.png)

**Comment by YahuiAn** [comment]
@yangli1212 I have the same problem. see #8537
