### ISSUE TITLE
使用Clair扫描问题

### ISSUE THREAD

**Issue by xyzzen** [goharbor/harbor#13649]
使用Harbor版本 v2.0.0-87602132
扫描器信息:
`Name:Clair
Vendor:CoreOS
Version:2.x
Capabilities
Consumes Mime Types:[application/vnd.oci.image.manifest.v1+json , application/vnd.docker.distribution.manifest.v2+json]
Produces Mime Types:[application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0]
Properties
harbor.scanner-adapter/registry-authorization-type:Bearer
harbor.scanner-adapter/scanner-type:os-package-vulnerability`

使用审查服务里批量扫描时都显示无漏洞,重新在某个项目单独扫描时又显示有漏洞

两张图前后对比
![1](https://user-images.githubusercontent.com/29516370/100694876-f1519c80-33ca-11eb-84de-24a9b5650611.png)
![2](https://user-images.githubusercontent.com/29516370/100694878-f282c980-33ca-11eb-8ade-25fe4ae22e68.png)

**Comment by wy65701436** [comment]
The CVE data may updating at this time, can you check the clair DB or log to confirm?

**Comment by snuglove** [comment]
The underlying image of the warehouse project is ubuntu18.04 vulnerabilities that are known to have been made public.
The scan on November 27th showed no vulnerabilities.
Then today, a single scan in the project image warehouse scanned for vulnerabilities.
