### ISSUE TITLE
Include a 'show fixable issues' in the UI for CVE reports

### ISSUE THREAD

**Issue by beltran-rubo** [goharbor/harbor#13645]
**Is your feature request related to a problem? Please describe.**
Users are scared of lot of vulnerabilities into the container images. Most of them are related to unfixed system packages the distro maintainers decided not to fix for many reasons.

**Describe the solution you'd like**
Quay.io has a 'show only fixable' CVEs that excludes all the CVEs that do not have a package with the fix. That way the user would know if he has to rebuild its container e.g. https://quay.io/repository/bitnami/kafka/manifest/sha256:6b557573e356f35361e357c48383656cdfafb273df51003272ebb2692c5ed1dc?tab=vulnerabilities. You can check with and without 'show only fixable'.

It would be great to have that similar option in the UI so users can filter the CVE reports from any scanner to only show the ones that have packages available with the fix.

**Comment by wy65701436** [comment]
hi @beltran-rubo do you mean this setting https://github.com/goharbor/harbor/blob/master/make/harbor.yml.tmpl#L73?

**Comment by danielpacak** [comment]
In some cases it's desirable to show unfixed vulnerabilities in other cases it is not. Therefore, this is configurable and by default Trivy shows all vulnerabilities including unfixed. You can set the value mentioned by @wy65701436 to true and ignore unfixed vulnerabilities. We have similar config value for Helm chart `trivy.ignoreUnfixed`.

**Comment by beltran-rubo** [comment]
Right, my suggestion is to include that option into the UI itself for filter them in an easy way.

**Comment by danielpacak** [comment]
> Right, my suggestion is to include that option into the UI itself for filter them in an easy way.

Yes I got your point @beltran-rubo and I think it can be useful. Especially for scanners that do not provide such config to ignore unfixed vulnerabilities. Anyway we should create another issue for such enhancement or update the description of this one to point out that we're talking about UI and / or Harbor API. It's not related to Trivy or any other integrated scanner. /cc @xaleeks

**Comment by beltran-rubo** [comment]
Thanks! updated

**Comment by danielpacak** [comment]
I think this is related #13731
