### ISSUE TITLE
signed status not reflected on mouseover of sha256 artifact

### ISSUE THREAD

**Issue by piengeng** [goharbor/harbor#13642]
**Expected behavior and actual behavior:**
the mouse hover shows all not signed
![image](https://user-images.githubusercontent.com/8223560/100616635-55854980-3354-11eb-8568-a4c22a77d680.png)
but within the artifact shows 2 tags are signed. side note: if you obverse attentively, the red and green are not aligned...
![image](https://user-images.githubusercontent.com/8223560/100616705-7057be00-3354-11eb-8d30-a6730dcaf36d.png)
expects signed status to be consistent.

**Steps to reproduce the problem:**
Signing multiple/some tags on the same sha256 artifact.

**Versions:**
- harbor version: [v2.1.1-5f52168e]
- docker engine version: [19.03.13]
- docker-compose version: [1.25.4]

**Comment by AllForNothing** [comment]
@piengeng Thanks for providing the info.
This is duplicated with #13488
