### ISSUE TITLE
long image path will be delete part when registry replication HarborA to HarborB

### ISSUE THREAD

**Issue by tangkelu** [goharbor/harbor#13659]
- HarborA version: [v2.0.0-57272e3b]
- HarborB version: [v2.1.1-5f52168e]
- Image full path: HarborA/lib/service/image:tag

registry replication from HarborA to HarborB，the origin path HarborA/lib/service/image:tag will become HarborB/lib/image:tag .
[**service**] was deleted

**Comment by bitsf** [comment]
duplicate with issue https://github.com/goharbor/harbor/issues/12791
