### ISSUE TITLE
API endpoints /projects/{project_id} and /projects/{project_id}/summary don't return repo_count if project is empty

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#13664]
**Expected behavior and actual behavior:**
API endpoints `/projects/{project_id}` and `/projects/{project_id}/summary` don't return `repo_count` if project is empty.
API only returns this property if there are any repositories in the project.

When repository is empty it should return `repo_count: 0` for consistency.
Otherwise it should be described as optional property in output.

This applies to other properties like `developer_count` as well.

**Steps to reproduce the problem:**
Create empty project.
Make a call to API.

**Versions:**

- harbor version: [2.1.1]

Example output for empty repository

```json
{
    "developer_count": 1,
    "guest_count": 1,
    "maintainer_count": 1,
    "project_admin_count": 2,
    "quota": {
        "hard": {
            "storage": -1
        },
        "used": {
            "storage": 0
        }
    }
}
```

Example output with non-empty repository

```json
{
    "project_admin_count": 1,
    "quota": {
        "hard": {
            "storage": -1
        },
        "used": {
            "storage": 614579585
        }
    },
    "repo_count": 3
}
```

**Comment by wy65701436** [comment]
@heww it seems an API issue, please help to debug.
