### ISSUE TITLE
Support for GitHub Container Registry (ghcr.io)

### ISSUE THREAD

**Issue by chipzoller** [goharbor/harbor#13672]
**Is your feature request related to a problem? Please describe.**
Support for replications from ghcr.io

**Describe the solution you'd like**
Support for replications from ghcr.io

**Comment by chipzoller** [comment]
To be clear: This works when specifying the registry type as "Docker Registry", but it would be nice to have a specific menu item just for GHCR.

**Comment by kofj** [comment]
Ahaaa, I'm interested in that, will PR later.

**Comment by kofj** [comment]
@chipzoller Hi, I've only tried a small part of GHCR's features, such as pull/push docker images, and is there anything special about it that needs support?

**Comment by chipzoller** [comment]
Not that I know of myself. But now with the Docker Hub rate limiting, more projects are pushing to GHCR instead, so probably the most needed features right now are push/pull.

**Comment by bitsf** [comment]
please notice using this feature need
1. enable Enabling improved container support
https://docs.github.com/en/free-pro-team@latest/packages/guides/enabling-improved-container-support
2. use a github token with right permission
https://docs.github.com/en/free-pro-team@latest/packages/learn-github-packages/about-github-packages#about-scopes-and-permissions-for-package-registries
