### ISSUE TITLE
Deploy: Use containerd insead of docker/docker-compose when deploy outside kubernetes

### ISSUE THREAD

**Issue by hyy0322** [goharbor/harbor#13682]
**Is your feature request related to a problem? Please describe.**
As we all know many projects like kubernetes is going to [deprecate docker](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation).
Is there any plans for Harbor to deploy without docker?

**Describe the solution you'd like**
Deploy Harbor without docker.

**Describe the main design/architecture of your solution**
Currently, I am working on this deploy method and have made some progress.
Just use ctr cmd to call containerd and run containers.
I think maybe we could discuss for it if Harbor is interested in it and is going to do something like this. I can help with it.

**Describe the development plan you've considered**
Not for now.

**Additional context**
/cc @steven-zou @xaleeks @ninjadq

**Comment by reasonerjt** [comment]
I don't think k8s deprecating docker means docker is deprecating itself.  That said if docker-compose can do the work I don't see a reason we move away from it.

If docker is deprecating itself, it may be k8s is the only way you can deploy Harbor in a way which is offcially supported.

I agree we may help users without k8s if there're tools with the same level of simplicity.  
If there are community contributors willing to contribute things like playbook, I wish I can ask him for dedication to maintain...

**Comment by reasonerjt** [comment]
My 2 cents.

K8S is deprecating docker doesn't mean docker is disappearing.
We have been using a pretty old version of docker-compose and it does the work.

So I don't see a reason we start to move away now.

Hopefully there can be a tool like docker-compose for ctr with same level of stability and simplicity when we have to do the switch.

**Comment by rob8714** [comment]
I think it would be good to have alternate solutions to docker available, for example Redhat 8 doesn't seem to officially support docker although it looks like you can still install it using some workarounds
