### ISSUE TITLE
Unable to add an AWS ECR registry via a instance/pod assigned AWS IAM role

### ISSUE THREAD

**Issue by sbkg0002** [goharbor/harbor#13687]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When the `Access ID` and `Access Secret` are left empty, the instance / pod IAM AWS role is used when adding an AWS ECR registry.

**Steps to reproduce the problem:**

1. Add an instance EC2 role with `ecr:*` privileges to the `core` pod.
2. Add a registry type `Amazon ECR` and leave `Access ID` and `Access Secret` empty
3. Select the correct region (`eu-west-1` in my case)

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.1
- docker engine version: 2.1.1
- docker-compose version: Helm chart version 1.5.1

**Additional context:**

core log:
```
2020-12-03T15:43:42Z [ERROR] [/replication/adapter/awsecr/adapter.go:210]: no credential to ping registry https://api.ecr.eu-west-1.amazonaws.com
```
Other notes:
* It _does_ work if I specify the ID and the key
* execing into the `core` pod and requesting the IAM information works:
```
sh-4.4$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/harbor -I
HTTP/1.1 200 OK
Date: Thu, 03 Dec 2020 15:53:09 GMT
Content-Length: 559
Content-Type: text/plain; charset=utf-8
```

**Comment by bitsf** [comment]
Do you mean you are testing within k8s? If so, you should also bind the role to the jobservice pod

**Comment by sbkg0002** [comment]
Thanks @bitsf. I'm running within k8s, but the jobservice pod also has the IAM role attached (via KIAM).

**Comment by bitsf** [comment]
hi, the pr https://github.com/goharbor/harbor/pull/13040 is targeting 2.2.0
