### ISSUE TITLE
Error response from daemon: unknown: middleware: vulnerable handler: error: 10412(Precondition failed) : no scanner registration configured for project: 34

### ISSUE THREAD

**Issue by LioCisco** [goharbor/harbor#13696]
What can we help you?
I pull image and then get this massage!
[Error response from daemon: unknown: middleware: vulnerable handler: error: 10412(Precondition failed) : no scanner registration configured for project: 34]

**Comment by wy65701436** [comment]
please share the configuration of your project? just try to disable the `Prevent vulnerable images from running`.

**Comment by wy65701436** [comment]
did you configurate the scanner?
