### ISSUE TITLE
docker-registry not send the httpbasic authentication header

### ISSUE THREAD

**Issue by Lionelpang** [goharbor/harbor#13700]
What can we help you?
hello, 
When replication sync the image to the docker registry which uses HTTP basic authentication, then the authentication information is not sent by the harbor side. Does harbor support the scenario of using docker registry to support HTTP basic authentication?
After reading the code, it is found that the account password authentication is not sent

**Comment by bitsf** [comment]
You should input the credential when you add the registry.
![image](https://user-images.githubusercontent.com/188115/101455479-9fca8400-396d-11eb-970f-c5e4c4bec667.png)

**Comment by Lionelpang** [comment]
> You should input the credential when you add the registry.
> ![image](https://user-images.githubusercontent.com/188115/101455479-9fca8400-396d-11eb-970f-c5e4c4bec667.png)

i had input the credential
