### ISSUE TITLE
Harbor behind reverse proxy - TLS Handshake Failure

### ISSUE THREAD

**Issue by bcousins** [goharbor/harbor#13702]
So I have Harbor 2.1.1 configured behind an NGiNX reverse proxy. Removing the reverse proxy is not an option. 

I have tried commenting out `proxy_set_header X-Forwarded-Proto $scheme; ` in multiple endpoints, including `/`, `/service` and `/v2`, per the documentation. I attempt to push the image to the repo that I've created, and...:

```
docker push <URL>/<repo>/<reponame>:development
The push refers to repository [<URL>/<repo>/<reponame>]
2a31467d7a55: Preparing 
a87bde03a72b: Pushing [==================================================>]  339.5kB
ba91725ac46a: Pushing [=>                                                 ]  34.82kB/1.481MB
20f80569560e: Preparing 
d9dd7057c00e: Preparing 
f6253634dc78: Waiting 
9069f84dbbe9: Waiting 
bacd3af13903: Waiting 
```
And that's it. It just hangs. And does nothing. At all. 

Edit: I have now ended up in a place where I am not doing this on data: 

I note I now have a workable error: 

`remote error: tls: handshake failure` - but like I said, I configured it all for that, and the web UI works with no issues with the cert that is on the reverse proxy.

**Comment by ninjadq** [comment]
did you configured external_url on `harbor.yml`?

**Comment by bcousins** [comment]
> did you configured external_url on `harbor.yml`?

Yes, I did.

**Comment by ninjadq** [comment]
is TLS correctly configured between the reverse proxy and Harbor?

**Comment by bcousins** [comment]
Yes, everything works with the same config except Harbor.

**Comment by bcousins** [comment]
I have established the issue as I have now had more time to review. I need to add certificates right the way through. [This Comment](https://github.com/goharbor/harbor/issues/3114#issuecomment-475930116) is exactly the procedure I needed to use.
