### ISSUE TITLE
How to use curl to add an user and group to Harbor

### ISSUE THREAD

**Issue by ws-way** [goharbor/harbor#13704]
Hello,

We do have a working LDAP with our AD, but I am unable to figure out how to add an AD user and an AD group to harbor via the curl command.

Can anybody help me? Thanks!

**Comment by sluetze** [comment]
as of 2.1.1 (untestet)
`curl -u $user:$password-H "Content-Type: application/json" --data @body.json  $harboruri/api/v2.0/projects/$projectid/members`

```bash
 # role_id
      # 1: Project Admin
      # 2: Developer
      # 3: Guest
      # 4: Maintainer
```

body.json
```json
{
  "role_id": 4,
  "member_group": {
    "ldap_group_dn": "CN=MYGROUP,OU=MYOU1,DC=MYDOMAIN,DC=HOME",
    "group_name": "NameOfTheCreatedGroupInHarbor",
    "group_type": 1
  }
}
```

Take a look at the API-Explorer in the Harbor GUI. It builds the curls for you, if you provide the correct values for the parameters.

**Comment by ws-way** [comment]
Thanks @sluetze, that's helpfull. I am using the API explorer, but it is not always clear to me. When I look at the ldap import user and all there is stated is ldap_uid_list and I do not know what to enter there. Do you have an example of this?

**Comment by sluetze** [comment]
I guess that call is to provide/provision users, without them needing to sign in.
That said, it's depends on your workflow if you need to use that API-Call. If your users authenticate on harbor anyway, you don't need to add them.

```json
{
  "ldap_uid_list": [
    "user1",
    "user2",
    "..."
  ]
}
```

where user1 / user2 are the values from the field that you configured as uid in your ldap configuration

**Comment by ws-way** [comment]
Excellent, thanks for the reply and help

**Comment by wy65701436** [comment]
Thanks @sluetze for your help.
