### ISSUE TITLE
Support Postgres 12

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#13708]
Currently some components dont work with PG12 , like notary and clair. 
Harbor also seems to have some issues with PG12, mainly around deleting projects.
Harbor is currently shipping with PG9.6, which has rougly a year of support left.

**Comment by wy65701436** [comment]
could you tell the issues / problems you encounter? cc @xaleeks

**Comment by morlay** [comment]
@MaxRink notary & clair is third parts. 

notary https://github.com/theupdateframework/notary
clair seems removed in v2

**Comment by immanuelfodor** [comment]
I use Harbor with an external PG13 DB without any visible problem on the UI. Though I don't have Notary and Clair enabled, all other parts are turned on.

**Comment by chaospuppy** [comment]
Can someone from Harbor officially confirm what the latest supported release of postgresql is?  We're running into #14191 while upgrading from Harbor 2.0.0 and I'm wondering if it's related to the fact that we're using Postgres 11.9.  If so, the Harbor teams should certainly look into supporting later versions of Postgres.

**Comment by sidewinder12s** [comment]
We're also wondering what the supported versions of Postgres are. We're running into performance issues with Harbor and an external RDS database and would like to upgrade to 10+ so that we can enable Performance Insights in AWS RDS, as it can't be installed in 9.6. And the general list of performance improvements in newer versions of Postgres.

**Comment by blhagadorn** [comment]
Is there any update o nthis?

**Comment by gunboe** [comment]
finally:
Which External Database versions does the Harbor support?
This information could be stated in requirements section (or Harbor Installation Prerequisites).

**Comment by wy65701436** [comment]
Harbor v2.3 is now supporting PG v13, just have a try. Close it as fixed.
