### ISSUE TITLE
When an image is synchronized, the Dockers Registry interface has no validation information

### ISSUE THREAD

**Issue by 1661788089** [goharbor/harbor#13706]
I used Harbor's mirror synchronization feature, I simulated and tested the interface between Huawei-SWR and Harbor,When the V2 interface is called, the validation information is missing.
Syncing to Harbor is an example(PUSH). 

I implemented a Registry to harbor specifications,Push a mirror and synchronize it to my Registry, But step3 and Step5 lack token and are intercepted:

step1:
method:/api/projects
cookies:null
headers:
authorization=Basic MTIzNDoxMjM0
content-length=49
host=*****
content-type=application/json
accept-encoding=gzip
user-agent=harbor-replication-service

step2:
method:/v2/
cookies:null
headers:
host=*****
accept-encoding=gzip
user-agent=Go-http-client/1.1

step3:
method: /v2/target/busybox/manifests/latest
headers:
host=*****
user-agent=harbor-replication-service
accept=application/vnd.docker.distribution.manifest.v1+json

step4:
method:/v2/
cookies:null
headers:
host=*****
accept-encoding=gzip
user-agent=Go-http-client/1.1

step5:
method:/v2/target/busybox/blobs/sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f
cookies:null
headers:
host=*****
user-agent=harbor-replication-service

.........

**Comment by stonezdj** [comment]
Could you please give more detail information about your issue? Are you using proxy cache or image replication?

**Comment by bitsf** [comment]
I think you need use change for bear token with push permission.

below is an example of pull permission
![image](https://user-images.githubusercontent.com/188115/102056939-2082f780-3e28-11eb-883d-0c85d1da6a26.png)
