### ISSUE TITLE
Harbor API to push Images and helm-charts

### ISSUE THREAD

**Issue by ankush06** [goharbor/harbor#13712]
Is there any API to PUSH the images and helm-charts ?
The docker repository API are accessible to get the image (https://<address>/v2/_catalog) but not sure how to access the chartmuseum API ? 
please provide pointer for this. I am looking for APIs to upload docker images and helm charts.

**Comment by wy65701436** [comment]
Harbor is OCI compatible registry, so you can just refer to the OCI distribution spec to upload config/blobs and manifest of a docker image.
