### ISSUE TITLE
CVE allowlist doesn't work

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#13726]
Hi, 

I'm trying to use/understand CVE allowlist,
I tried to add one CVE from an image to the allowlist (project and system),
I re-launched a scan with Harbor and it's still in the CVE list of my scanned image
maybe I misunderstood how it works?

https://goharbor.io/docs/2.1.0/working-with-projects/project-configuration/configure-project-allowlist/
"You can create allowlists of CVEs to ignore during vulnerability scanning"

![project allowlist](https://user-images.githubusercontent.com/11298399/101752765-28623500-3ad2-11eb-8a88-c0e3ca92746d.png)
![system allowlist](https://user-images.githubusercontent.com/11298399/101752884-4def3e80-3ad2-11eb-9528-99374b655477.png)

![scan](https://user-images.githubusercontent.com/11298399/101752801-32843380-3ad2-11eb-9284-59778d73b099.png)

**Comment by wy65701436** [comment]
The allowlist is for the docker pull to by pass `deployment security` in the project configuration, not for ignoring them in the scan result.

**Comment by flbla** [comment]
@wy65701436 as a user without access to the configuration, it could be great to have like a flag, something showing in the scan that the CVE is in a allowlist
