### ISSUE TITLE
clair_vulnerability_status where did it go ?

### ISSUE THREAD

**Issue by pernygaard** [goharbor/harbor#13722]
What happened to the clair_vulnerability_status from api/systeminfo ?

In Harbor version 1.9.4 it was there, but after we upgraded to v1.10.1 it was gone

"clair_vulnerability_status": {
    "overall_last_update": 1575578301,
    "details": [
......
.....
....
  },

I'm now on version 2.1.1
And this is what I got now from api/v2.0/systeminfo
{
  "with_notary": false,
  "auth_mode": "ldap_auth",
  "registry_url": "XXXXXXXXXXXX",
  "external_url": "XXXXXXXXXXXXXX",
  "project_creation_restriction": "adminonly",
  "self_registration": false,
  "has_ca_root": false,
  "harbor_version": "v2.1.1-5f52168e",
  "registry_storage_provider_name": "filesystem",
  "read_only": false,
  "with_chartmuseum": true,
  "notification_enable": true
}

I'm was using clair_vulnerability_status to monitor if clair scans had been performed.
if not for 2 days I used to get an alarm, but now I do not know what to check in the api to see if clair has run a scan.

Do anyone have an Idea, or could I please get clair_vulnerability_status back in api/v2.0/systeminfo

**Comment by heww** [comment]
It's was removed from the response of the systeminfo when the harbor support multiple scanners.

There is a key named `harbor.scanner-adapter/vulnerability-database-updated-at` in the `properties` of the scanner's metadata,  its value is the last time the vulnerability database updated.

The endpoint to get the metadata of the scanner is `/api/scanners/{registration_id}/metadata` in harbor v1.10.

**Comment by pernygaard** [comment]
@heww Thank you very much, I will use that instead.
