### ISSUE TITLE
Image vulnerability scan results are lost after upgrade from v1.9.3 to v1.10.6

### ISSUE THREAD

**Issue by annkam** [goharbor/harbor#13738]
Hello. Yesterday I performed an upgrade from v1.9.3 to v.1.10.6 on my prod instance which is deployed with official docker-compose.yaml 
Some projects were configured to prevent vulnerable images from pulling and as all vulnerability scan results were missing, images were not pullable. We did not discover that immediately. I was able to reproduce the problem in test environment.

**Steps to reproduce the problem:**
1. Deploy a simplest Harbor v.1.9.3 installation  with docker-compose
2. Push an image and run vulnerability scan on it
3. Upgrade to v.1.10.6
4. Check that image's vulnerability scan status has become 'not scanned'

**Versions:**

- harbor version: [1.9.3, 1.10.6]
- docker engine version: [19.03.13]
- docker-compose version: [1.24.1]

**Comment by wy65701436** [comment]
it's by desgin, after migration success, you can just execute one time scan all to get them back.

**Comment by annkam** [comment]
You should mention this in the upgrade guide. Am I going to face the same issue while upgrading from 1.10 to 2.1?

**Comment by wy65701436** [comment]
we will add this in the migration document. For upgrade from 1.10 to 2.1, yes the result will be lost.
