### ISSUE TITLE
github adapter always inprogress when not setting filter

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#13737]
Version v2.2.0-a4f21b1d
![image](https://user-images.githubusercontent.com/188115/101859191-2b2e5a00-3ba6-11eb-8773-212156566345.png)
![image](https://user-images.githubusercontent.com/188115/101859288-60d34300-3ba6-11eb-8414-6181c2a7c39d.png)
jobservice.log
![image](https://user-images.githubusercontent.com/188115/101859314-73e61300-3ba6-11eb-8964-560203cf3627.png)

**Comment by kofj** [comment]
![image](https://user-images.githubusercontent.com/3346673/102292323-e7f63180-3f7f-11eb-988a-06d5b63f5aac.png)

![image](https://user-images.githubusercontent.com/3346673/102292348-f17f9980-3f7f-11eb-8af3-002d187e8606.png)

@bitsf Hi,Ziming. I  cannot reproduce this problem, did you compile the latest code to try again?

**Comment by bitsf** [comment]
yes, this can't be reproduced now
