### ISSUE TITLE
found the error message in the core service log: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CoderX-Aaron** [goharbor/harbor#13742]
When I log in using the web interface, a login error is displayed. And found the error message in the core service log: 
> Handler crashed with error runtime error: invalid memory address or nil pointer dereference

> [ERROR] [/common/api/base.go:73]: GET /api/configurations failed with error: {"code":401,"message":"UnAuthorized"}

But when I click the login button multiple times, I can log in. I can be sure that the username and password are correct。
The version of Harbor is v1.10.6.

Does anyone know what is causing this

**Comment by ywk253100** [comment]
Could you provide more logs about the error `invalid memory address or nil pointer dereference`? The log should indicate in which line the error comes from

**Comment by CoderX-Aaron** [comment]
> Could you provide more logs about the error `invalid memory address or nil pointer dereference`? The log should indicate in which code the error comes from

This is the complete log. could you give me some suggestions：
> 2020-12-14T03:41:46Z [ERROR] [/common/api/base.go:73]: GET /api/users/current failed with error: {"code":401,"message":"UnAuthorize"}

**Comment by CoderX-Aaron** [comment]
> Could you provide more logs about the error `invalid memory address or nil pointer dereference`? The log should indicate in which code the error comes from

@ywk253100 This is the full log. could you give me some suggestion:
> 2020/12/14 07:57:05.936 #033[1;35m[C]#033[0m [panic.go:522]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference

**Comment by dox1042** [comment]
Has there been any progress on this issue? I ran accross this exact same thing.

**Comment by alexdepalex** [comment]
Same issue here. Happens when I try to pull an image from a proxy cache. Running the most recent bitnami containers.
```
2021-06-01T15:04:31Z [WARNING] [/server/middleware/repoproxy/proxy.go:139]: Artifact: docker-cache/library/python:3.8-buster, digest: is not found in proxy cache, fetch it from remote repo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1c0e6d0]

goroutine 249 [running]:
github.com/goharbor/harbor/src/controller/proxy.(*ManifestListCache).CacheContent(0xc0015f94c0, 0x26e6e80, 0xc000985ad0, 0xc000481eb5, 0xe, 0x26ae520, 0xc0019fc000, 0xc000481ea8, 0x1b, 0xc000481ece, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/manifestcache.go:72 +0x230
github.com/goharbor/harbor/src/controller/proxy.(*controller).waitAndPushManifest(0xc0000bd040, 0x26e6e80, 0xc000985ad0, 0xc000481eb5, 0xe, 0x26ae520, 0xc0019fc000, 0xc000481ea8, 0x1b, 0xc000481ece, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:278 +0x11e
github.com/goharbor/harbor/src/controller/proxy.(*controller).ProxyManifest.func2(0xc0000bd040, 0xc000481ea8, 0x1b, 0xc000481ece, 0xa, 0xc000481ea8, 0xc, 0x0, 0x0, 0xc000481ece, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:213 +0x245
created by github.com/goharbor/harbor/src/controller/proxy.(*controller).ProxyManifest
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:201 +0x4e8
```

**Comment by alexdepalex** [comment]
Anybody an idea what this could be? Did anybody find a workaround?

**Comment by FrodoBeuthling** [comment]
I was able to work around the issue with the bitnami containers by setting the environment variable `_REDIS_URL_CORE`(missing from the `docker-compose.yml`) on the harbor-core container to a valid redis address. It looked like without it the default cache does not get initialized which results in `src/controller/proxy/manifestcache.go:72: m.cache` being nil.

**Comment by alexdepalex** [comment]
Thanks. That fixed it for me. The current version of the compose file still seems to use the wrong variable for this.

**Comment by YangJiao0817** [comment]
Harbor v1.10.X is no longer maintained.
