### ISSUE TITLE
Invalidated OIDC session handling

### ISSUE THREAD

**Issue by kautkata** [goharbor/harbor#13747]
**Expected behavior:**
Docker image push to harbor using CLI secret should fail, and Harbor web UI should handle exiting session as invalid after OIDC 
session get's invalidated on OIDC providers side.

1. Harbor UI periodically should invoke OIDC providers `check_session_iframe` or some other API endpoint to validate if OIDC session hasn't been invalidated on providers side -  similarly how server side core is doing it
2. Harbor server(core) should thread all OIDC userinfo endpoint error responses as fatal and shouldn't fallback to "user data from ID token".

**Actual behavior:**
Docker images can be pushed to harbor, Harbor web UI still allows access project/repositories/etc after OIDC session get's invalidated on OIDC providers side.

**Steps to reproduce the problem:**
1. Set up harbor with OIDC authentication backed - keycloak
2. Enroll/auto onboard harbor user via web front-end (login with oidc provider)
3. Generate OIDC user/token specific CLI secret
4. Log in into harbor via `docker login -u <oidc username> -p <CLI secret> <harbor url>`
5. Push random image into harbor - as expected OIDC session is still valid
6. Open OIDC provider and invalidate all OIDC user sessions associated with harbor client
7. **Bug number 1** - harbor UI is still accessible in session created in 2nd step
8. **Bug number 2** - images can be pushed to harbor relying on 4th steps authentication data.

**Workaround/mitigation for 8th steps bug**
Harbor aggressively tracks access tokens validity and if it's expired then it get's refreshed via refresh token.
I can't pinpoint exact location in harbors code but if access tokens refresh fails then image push to harbor get's rejected (as expected) with unauthorized exception. So by relying on this behavior invalidated OIDC session handling bug can be partially mitigated by reducing access tokens validity time to minimum (1 minute) just to force refreshes more often. Yes this puts much more stress OIDC provider but it works.

**Versions:**
- harbor version: v2.1.1-5f52168e
- docker engine version: 19.03.12
- docker-compose version: 1.26.2
- keycloak version: v10.0.1

**Additional context:**
In [log-mix.txt](https://github.com/goharbor/harbor/files/5683129/log-mix.txt) part of core.log mixed in with keycloaks event representation during 8th steps invoke.
Location which causes server side [issues](https://github.com/goharbor/harbor/blob/v2.1.1/src/common/utils/oidc/helper.go#L243)

PS. If needed I can try to trim down my dockerfiles/keycloak/etc so that this would be easily reproducible, but it will take some time as my keycloak is set up with user federation to active directory and stuff

**Comment by reasonerjt** [comment]
@kautkata 
This is by design that Harbor use the ID token as the single source of truth the determine if the request is valid.  Such that Harbor does not have to communicate with the ID provider before the ID token expires.

**Comment by kautkata** [comment]
You can correct me if I'm wrong - but token expiry isn't the only case when OIDC session can be thought of as invalid/expired. Sessions can be invalidated by OIDC provider it self as well - lost hardware, compromised credentials, etc. In this case only way how harbor can identify this by by invoking some kind of api on OIDC providers side.

**Comment by reasonerjt** [comment]
I don't think I'm convinced.
If the ID provider is compromised, the API for such verification may return fake response right?
If the private key is lost, the OIDC provider can rotate the key and this change will be reflected in the `.well-known/openid-configuration`, and the validation will fail.

AFAIK normally ID token cannot be revoked by server, and to lower the risk the lifespan can be set relatively short.

**Comment by kautkata** [comment]
I'm not talking about OIDC providers compromises but about user credential compromises. 
As far as I get then to mitigate these compromises session invalidation functionality exists. Problem is that when harbor stumbles on this case then it still continues to work using fallback to original token instead of refusing pull/push actions.

**Comment by reasonerjt** [comment]
If the user creds are compromised and the hacker gets a valid id token.  Unfortunately, the token will be valid until it expires.

I don't think we should rely on the response of`/userinfo` to check the validity of the token.

**Comment by kautkata** [comment]
> the token will be valid until it expires.

I don't believe that this is entirely true - OIDC providers are/must be state-full (in the same scene as harbors token service) they track authenticated session state - at the end of they day they must know which refresh token maps to witch access token. This in turn gives them option to invalidate existing sessions - just like google and facebook does.

What actually is broken in harbors implementation is compliance with OIDC providers decision during "userInfo" endpoints invoke (it already does get called during each docker pull/push command) 

Actual problems resides here [https://github.com/goharbor/harbor/blob/v2.1.1/src/common/utils/oidc/helper.go#L250](https://github.com/goharbor/harbor/blob/v2.1.1/src/common/utils/oidc/helper.go#L250) instead of logging warning and falling back to locally stored [token](https://github.com/goharbor/harbor/blob/v2.1.1/src/common/utils/oidc/helper.go#L262), harbor should reject incoming pull/push operation. 

Technically I get that this will introduce runtime dependency on OIDC providers availability - but this can be mitigated by more checks like - if token was issued by OIDC provider less than 5 minutes ago then we trust it's content (most likely it hasn't been invalidated) and don't invoke userinfo at all - this even might be configurable threw UI.

**Comment by lindhe** [comment]
No bot, please unstale this. :)

**Comment by kautkata** [comment]
Roughly half a year has passed (I switched employer and had to set up infra from scratch). This This time I gave up on OIDC authentication for good.

In cases when there are a lot of relatively shady users who can't be completely trusted this issue becomes really important. But luckily robot tokens where re-implemented so I use them as mitigation for this issue

**Comment by lindhe** [comment]
I think it could be worthwhile to bring up this issue in a community meeting on Zoom. The meeting schedule is woefully out of date, so I don't know when the next one is, but hopefully someone knows...

**Comment by BrixSat** [comment]
I would love to see this solved.

**Comment by mtusseau** [comment]
Please Bot, unstale this.
