### ISSUE TITLE
Docs shouldn't encourage the use of deprecated CN field in X.509 certificates

### ISSUE THREAD

**Issue by lizrice** [goharbor/harbor#13745]
The instructions for [configuring internal TLS](https://goharbor.io/docs/2.1.0/install-config/configure-internal-tls/) in Harbor talk about using the Common Name (CN) field in certificates. CN has been [deprecated](https://tools.ietf.org/html/rfc2818#section-3.1) in favour of [Subject Alternative Name](https://tools.ietf.org/html/rfc5280#section-4.2.1.6) fields for a long time (and generally browsers no longer support it, for example [Chrome dropped support for CN in 2013](https://bugs.chromium.org/p/chromium/issues/detail?id=308330)). 

Golang [retired support for CN in 1.15](https://golang.org/doc/go1.15#commonname) so it would be a good idea for internal Harbor certificates not to rely on it, and the documents should indicate configuring the SAN rather than the CN for these certificates.

**Comment by wy65701436** [comment]
hi @ninjadq we should consider this, and it could impact the internal TLS after we're upgraded to go v1.15

**Comment by lizrice** [comment]
@wy65701436 #13810 will help with the actual certificates being used, but I think [this page of Harbor docs](https://goharbor.io/docs/2.1.0/install-config/configure-internal-tls/) also need to be updated to encourage people to use SAN instead of CN?

**Comment by ninjadq** [comment]
reopen as per doc impact

**Comment by ninjadq** [comment]
Doc updates are included in https://github.com/goharbor/website/pull/172
