### ISSUE TITLE
Default Username/Password for Harbor Registry Login

### ISSUE THREAD

**Issue by V-Bhadauriya** [goharbor/harbor#13743]
I am not able authenticate harbor registry running on 5000.
I tried with default UI password admin/Harbor12345 but no luck.

**Comment by unki** [comment]
please see <https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication>

**Comment by V-Bhadauriya** [comment]
@unki I got the username and password for private registry from config.yaml file.
