### ISSUE TITLE
helm cli support anonymous access charts from public project

### ISSUE THREAD

**Issue by geneliu** [goharbor/harbor#13746]
Tried both the default AUTH_ANONYMOUS_GET: "false" and AUTH_ANONYMOUS_GET: "true" via update chartmuseum-cm. Neither works for public project ever.

Each time access the chartrepo requires authentication. 
Is there a way to access chart without authenticate for public project?

**Comment by geneliu** [comment]
The ConfigMap I updated for AUTH_ANONYMOUS_GET: "true" is at: https://github.com/goharbor/harbor-helm/blob/master/templates/chartmuseum/chartmuseum-cm.yaml

**Comment by geneliu** [comment]
BTW, the container image registry access (docker pull) works well for the same public project.

**Comment by geneliu** [comment]
Thanks for your assistance on this! 

My team/org is evaluating harbor (my preference) and chartmuseum which we can embed a chart repo server in our product. I feel harbor should allow helm chart anonymous get access same/similar as registry for image(push charts to the repo requires authentication is fine). If the repo service is the same chartmuseum, there is no reason harbor does not support that. However, I need confirmation and help to setup it.

**Comment by ninjadq** [comment]
hi @geneliu I recommend you use `helm3` and harbor artifact registry to store charts, because the separated chart repo will deprecated in future. You can refer https://github.com/goharbor/harbor/tree/master/tools/migrate_chart to migrate

**Comment by geneliu** [comment]
Hi @ninjadq We do use helm3. Is there a reference/documentation about how to use artifact registry for charts? I use helm chart from https://chartcenter.io/harbor/harbor?version=1.5.2

Or just unset the 'chartmuseum.enabled'?

Thanks!

**Comment by geneliu** [comment]
I got it. Thanks. (unset the chartmuseum).
