### ISSUE TITLE
ldap auth fails with empty password

### ISSUE THREAD

**Issue by robkooper** [goharbor/harbor#13763]
I upgraded my harbor from 2.1.1 to 2.1.2 and this stopped LDAP from working. I could still login with my local admin account but the ldap did no longer work.

I use ldaps, no need for login to access the server.

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
1. use ldap with harbor, no authentication needed to check username/password
2. upgrade harbor from 2.1.1 to 2.1.2
3. try and login

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.2]
- docker engine version: [19.03.1]
- docker-compose version: [1.25.4]

**Additional context:**

Following is listed in the log files:

```
Dec 14 14:28:56 172.18.0.1 core[1130]: 2020-12-14T20:28:56Z [WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: Can not bind search dn, error: LDAP Result Code 206 "Empty password not allowed by the client": ldap: empty password not allowed by the client
Dec 14 14:28:56 172.18.0.1 core[1130]: 2020-12-14T20:28:56Z [ERROR] [/core/controllers/base.go:109]: Error occurred in UserLogin: Can not bind search dn, error: LDAP Result Code 206 "Empty password not allowed by the client": ldap: empty password not allowed by the client
```

**Comment by stonezdj** [comment]
for security reason, empty password is not allowed in go-ldap v3

**Comment by robkooper** [comment]
so how do you work with a system that allows for non authenticated queries?

**Comment by tbaptista** [comment]
Have the same issue. Will it no longer be a configuration option to have anonymous queries to LDAP?

**Comment by pbolle** [comment]
Have the same issue. Harbor is not working after update.

**Comment by enajeeb** [comment]
I have same issue after upgrading from 2.0.2 to 2.1.2. If `LDAP Search Password` is required, then UI should make it a required field.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/3844941/103706791-4c465880-4f62-11eb-846d-c095f588bb4f.png">

**Comment by jacekn** [comment]
> for security reason, empty password is not allowed in go-ldap v3

@stonezdj I think above is slightly more complex. They allow empty passwords but not by default:
https://github.com/go-ldap/ldap/blob/d53d0d99860eaa6a14a5bedc9879911c5621ff3e/bind.go#L27

Anonymous LDAP binds are not uncommon so this limitation will impact some deployments.

I think that for better usability the harbor project should allow empty passwords. However if you prefer to be opinionated in this matter and enforce best practices among your userbase maybe this should be explicitly called out in the docs?

**Comment by robkooper** [comment]
maybe have a checkbox that allows for anonymous ldap bind? So a person needs to explicitly check the box.

**Comment by gwkunze** [comment]
this is a breaking change in a harbor patch release, so technically breaks semver

**Comment by crazy-canux** [comment]
How to solve this?

**Comment by luandrea** [comment]
I just installed Harbor 2.5.0 and now the LDAP Search DN is market as mandatory.
The problem is that my LDAP and be accessed as an anonymous user. I cannot configure my user in that field because the password have to be changed regularly and I can't update it every time in Harbor.
