### ISSUE TITLE
 Harbor 2.1.2 version obtains artifacts through api, more than 100 errors on one page

### ISSUE THREAD

**Issue by ilanni2460** [goharbor/harbor#13765]
Harbor 2.1.2 version obtains artifacts through api, more than 100 errors on one page

the api url :
https://docker2.XXX.cn/api/v2.0/projects/xx/repositories/cc/artifacts?page=1&page_size=200&with_tag=true

the message is: 
{"errors":[{"code":"UNPROCESSABLE_ENTITY","message":"validation failure list:\npage_size in query should be less than or equal to 100"}]}

**Comment by ywk253100** [comment]
This is by design, you cannot set the page size > 100

**Comment by zbh2021** [comment]
how to set page size > 100
