### ISSUE TITLE
Docker Image Overview Cannot display author

### ISSUE THREAD

**Issue by duhongle** [goharbor/harbor#13779]
**Versions:**
- harbor version: 2.1.1
- docker engine version: 20.10.1
- docker-compose version: 1.27.4

![Snipaste_2020-12-16_19-21-33](https://user-images.githubusercontent.com/4733964/102343491-98daeb80-3fd5-11eb-8ea9-852d4051057b.png)

Dockerfile Use LABEL maintainer...... build docker image
LABEL maintainer="xxx@abc.com"

[maintainer-deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/12734 and the fix will be available in v2.2
