### ISSUE TITLE
Docker  login expires with OIDC  unauthorized: authentication required 

### ISSUE THREAD

**Issue by zdhamasha** [goharbor/harbor#13778]
Running with v2.1.1 and OIDC Enabled.

the following what's happened:
* User OIDC Logs in. User gets his token
*  docker login -u username with the token
* docker push and pull working fine  24 Hours later, the User OIDC session expires User tries to docker push using and it fails

`unauthorized: authentication required `

Why does the user's token expire? Why does re-logging into Harbor UI seem to reset the token?

I need to use OIDC everyday with script,I don't want to login into the Harbor UI to reset token

is there an api I can call it to reset token, please advise us !!

**Comment by sphr2k** [comment]
This seems to be by design: https://github.com/goharbor/harbor/issues/10737

However, it would be great if it were possible to change this behavior, i.e. to disable token expiry.

**Comment by kautkata** [comment]
I recently was testing similar setup.

When token (one stored in harbor db) between harbor and and OIDC provider expires harbor tries to re-acquire it via refresh token. If OIDC provider is set up correctly - scope includes in tokens, refresh token expiry (should be longer than access token - in keycloak default to 30 days),etc  then harbor should be able to survive your case.

In core services logs (debug required) you can see what is actually going on and debug it further from there.

**Comment by reasonerjt** [comment]
@kautkata thanks for the explanation!

**Comment by zdhamasha** [comment]
we have added an option on the OIDC scope **offline_access**  to obtain refresh token
it worked 
thanks all
