### ISSUE TITLE
Use chartMuseum to view the chart specified version to report an error （internal server error）

### ISSUE THREAD

**Issue by programmingroad** [goharbor/harbor#13775]
harbor version: v2.0.0
installation: sudo ./install.sh --with-chartmuseum

The following error is reported when I check the specified version of chart：

![image](https://user-images.githubusercontent.com/51621027/102297416-390b2300-3f8a-11eb-9484-e4b3b52a90a5.png)

How do I find out

**Comment by ywk253100** [comment]
@programmingroad Could you upload the logs?

**Comment by programmingroad** [comment]
I saw this error in core.log 

![image](https://user-images.githubusercontent.com/51621027/102336246-e6eaf180-3fcb-11eb-8eeb-dee815c50626.png)

**Comment by ywk253100** [comment]
ping @ninjadq, I recall this is a known issue and is fix in a patch version?

**Comment by programmingroad** [comment]
@ywk253100 @ninjadq 

I also reported the above error when I pushed chart from one harbor to another.

**Comment by ninjadq** [comment]
@programmingroad, could you update harbor to latest harbor version like 2.1.2 or 2.0.5. I remember it fixed in #11735

**Comment by programmingroad** [comment]
@ninjadq Harbor version 2.0.5 works normally. thanks ！
