### ISSUE TITLE
harbor-core cannot connect to aliyun acr.

### ISSUE THREAD

**Issue by ikechan8370** [goharbor/harbor#13771]
I installed harbor 2.1.2 using `install.sh`, everything seemed to be ok but when I tried to create a target registry it couldn't pass the connection test, and the log of `harbor-core` told me "Specified access key is not found or invalid", log is below:
`2020-12-15T20:42:00+08:00 [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://registry.cn-beijing.aliyuncs.com: SDK.ServerError`
`ErrorCode: InvalidAccessKeyId`
`Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidAccessKeyId&source=PopGw`
`RequestId: 9C12194C-9DB5-406E-A176-5F1E57E06FE0`
`Message: Specified access key is not found or invalid.`
Should the accessKey be configured manully or what? Thanks.

**Comment by bitsf** [comment]
I think you should use a RAM user's AK with AliyunContainerRegistryFullAccess permission

**Comment by bitsf** [comment]
yes, you should input your account's AK or RAM user's AK with AliyunContainerRegistryFullAccess permission
![image](https://user-images.githubusercontent.com/188115/104036406-50969e00-520e-11eb-8822-539cbbad51f6.png)

**Comment by QiuToo** [comment]
我也遇到这个问题，但看issue后依然无法解决。
我的harbor Version2.3.5，我确认我的ACR地址正确，且namespace也是正确的。
![image](https://user-images.githubusercontent.com/88759374/167677218-64831d49-d548-4bfb-b565-d4a64f58b00d.png)

**Comment by lajifeiwomoshu** [comment]
当你选择使用providers为alibaba ACR的时候，你只能使用accesskey，不能用用户名和密码，所以你报错了，并且使用accesskey的时候需要注意版本，企业版ACR的话，主账号accesskey和RAM账号accesskey都可以连接成功，只要你有访问容器镜像服务的权限，但是当你是连接个人版ACR的时候，你要使用RAM accesskey的话，需要RAM账号先注册下个人版ACR。具体可以参考：
https://blog.51cto.com/blogger/success/5645721

**Comment by realzhangqingwei** [comment]
> 
个人版本实验过是这样, 看起来是一个bug, 需要先登录
