### ISSUE TITLE
Replication from GitLab with project in subgroup with namespace filter not working

### ISSUE THREAD

**Issue by hlubek** [goharbor/harbor#13796]
**Expected behavior and actual behavior:**

### Expected

* A replication rule from a GitLab registry with name filter `mygroup/mysubgroup/**` will from registry for GitLab project `mygroup/mysubgroup/myproject` with image name `mygroup/mysubgroup/myproject/myimage`

### Actual

* Only images of some (seemingly random) projects in `mygroup` were replicated (less than expected)
  * It seems only projects in `mygroup/mysubgroup` that had a description with the word `mysubgroup` actually were considered for replication

**Steps to reproduce the problem:**

* Create GitLab group `mygroup`
* Create subgroup `mysubgroup` in group
* Create projects inside `mysubgroup`
  * `project1` no description
  * `project2` with description "This is mysubgroup project"
* Create images in `project1` and `project2`
* Add GitLab registry in Harbor
* Add pull replication rule in Harbor with
  * name filter: `mygroup/mysubgroup/**`
  * tag filter: `*.*.*`
  * namespace: (blank)

Only images in `project2` with a matching description are replicated.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.2

**Additional context:**

I inspected the GitLab API calls and identified that the GitLab projects were fetched by using a project search (https://docs.gitlab.com/ee/api/projects.html#list-all-projects with `?search=...`) for `mysubgroup` which does not return all expected projects (can be easily reproduced by just calling the GitLab API with e.g. Curl)

There seem to be some related issues like #13364 which are not exactly the same case. Replication from GitLab in Harbor seems overall a bit unreliably and hard to reason about.

I'd suggest another approach for https://github.com/goharbor/harbor/blob/05f327cfbd170bb89f94c158e11559b3f50d4441/src/replication/adapter/gitlab/adapter.go#L80

- Collect all suitable projects from GitLab by iterating all projects (using group API with subgroups and projects depending on name filter components is more troublesome to get correct and just an optimization to fetch less projects in this first step)
- Match projects against name filter (is project path a prefix of the filter), so less repositories need to be fetched
- Collect repositories of all remaining projects
- Match against name filter (like is already done)

In the meantime there seems to be an easy fix by just adding `&search_namespaces=1` when searching for projects .

**Comment by bitsf** [comment]
gitlab can have multi level groups and multi level namespace, such as repo `g1/g2/g3/project1/ns1/ns2/repo1:latest`, so it would be quite hard to find the project by name base on current architect.

**Comment by bitsf** [comment]
propose to add some trick method, like use square brackets to distinguish the group name if there're multi level groups, `[g1/g2/g3]/project1/ns1/ns2/repo1:latest`
