### ISSUE TITLE
Not able to push helm charts to OCI-Compatible Registry of Harbor

### ISSUE THREAD

**Issue by krohit90** [goharbor/harbor#13809]
What can we help you?

helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}

Step 1:
helm registry login harbor.test.com
Username: admin
Password: 
Login succeeded

step 2:
helm chart save helm harbor.test.com/library/mychart:myversion
ref:     harbor.test.com/library/mychart:myversion
digest:  206e97d57f456b94a090db15214ec2ebdc95c29cfb3819745ced235f938b355c
size:    3.5 KiB
name:    test-config
version: 0.1.0
myversion: saved

Step 3: [Error]
helm chart push harbor.test.com/library/mychart:myversion
The push refers to repository [harbor.test.com/library/mychart]
ref:     harbor.test.com/library/mychart:myversion
digest:  3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3
size:    3.5 KiB
name:    test-config
version: 0.1.0
Error: failed commit on ref "manifest-sha256:206e97d57f456b94a090db15214ec2ebdc95c29cfb3819745ced235f938b355c": unexpected status: 400 Bad Request

Can you please help me with this?

**Comment by ywk253100** [comment]
Please provide the logs, we can do nothing with just the `400 Bad Request` error message

**Comment by krohit90** [comment]
The push refers to repository [harbor.test.com/mychart/helm/configserver]
ref:     harbor.test.com/mychart/helm/configserver:develop
digest:  5301aaab3f287e5375dfcb336977edaf98709f1e4240c1911ecbde229347d564
size:    3.5 KiB
name:    mychart-config
version: 0.1.0
WARN[0000] encountered unknown type application/vnd.cncf.helm.config.v1+json; children may not be fetched 
DEBU[0000] push                                          digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json size=152
WARN[0000] reference for unknown type: application/vnd.cncf.helm.config.v1+json  digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json size=152
WARN[0000] encountered unknown type application/tar+gzip; children may not be fetched 
DEBU[0000] push                                          digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip size=3572
WARN[0000] reference for unknown type: application/tar+gzip  digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip size=3572
DEBU[0000] checking and pushing to                       digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip size=3572 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26"
DEBU[0000] checking and pushing to                       digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json size=152 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f"
DEBU[0000] do request                                    digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json request.header.accept="application/vnd.cncf.helm.config.v1+json, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=152 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f"
DEBU[0000] do request                                    digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip request.header.accept="application/tar+gzip, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=3572 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26"
DEBU[0000] fetch response received                       digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json response.header.connection=keep-alive response.header.content-length=172 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=99c4badd85fd0cf5e04a69c56272256b; Path=/; HttpOnly" response.header.www-authenticate="Bearer realm=\"https://harbor.test.com/service/token\",service=\"harbor-registry\",scope=\"repository:mychart/helm/configserver:pull\"" response.status="401 Unauthorized" size=152 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f"
DEBU[0000] Unauthorized                                  digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" header="Bearer realm=\"https://harbor.test.com/service/token\",service=\"harbor-registry\",scope=\"repository:mychart/helm/configserver:pull\"" mediatype=application/vnd.cncf.helm.config.v1+json size=152
DEBU[0000] fetch response received                       digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip response.header.connection=keep-alive response.header.content-length=172 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=86f176feb856f322ba13f3741a4f78c3; Path=/; HttpOnly" response.header.www-authenticate="Bearer realm=\"https://harbor.test.com/service/token\",service=\"harbor-registry\",scope=\"repository:mychart/helm/configserver:pull\"" response.status="401 Unauthorized" size=3572 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26"
DEBU[0000] Unauthorized                                  digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" header="Bearer realm=\"https://harbor.test.com/service/token\",service=\"harbor-registry\",scope=\"repository:mychart/helm/configserver:pull\"" mediatype=application/tar+gzip size=3572
DEBU[0000] do request                                    digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json request.header.accept="application/vnd.cncf.helm.config.v1+json, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=152 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f"
DEBU[0000] do request                                    digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip request.header.accept="application/tar+gzip, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=3572 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26"
DEBU[0000] fetch response received                       digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" mediatype=application/vnd.cncf.helm.config.v1+json response.header.accept-ranges=bytes response.header.cache-control="max-age=31536000" response.header.connection=keep-alive response.header.content-length=152 response.header.content-type=application/octet-stream response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-content-digest="sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f\"" response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=cd3ffb8fc230c0f53e9ad442224613ee; Path=/; HttpOnly" response.status="200 OK" size=152 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:a65a40ad1d463e4d23be9f7ec7ef15d814debe1e8c3cdd00e3bde1459f912a0f"
DEBU[0000] fetch response received                       digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" mediatype=application/tar+gzip response.header.accept-ranges=bytes response.header.cache-control="max-age=31536000" response.header.connection=keep-alive response.header.content-length=3572 response.header.content-type=application/octet-stream response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-content-digest="sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26\"" response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=2997e4518bebf5dd62c8cd82c85af95c; Path=/; HttpOnly" response.status="200 OK" size=3572 url="https://harbor.test.com/v2/mychart/helm/configserver/blobs/sha256:ada61c281a9a8ffdda85a4553d5561053d5d7af755a663a0abb361786b8a8f26"
DEBU[0000] push                                          digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json size=322
DEBU[0000] checking and pushing to                       digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json size=322 url="https://harbor.test.com/v2/mychart/helm/configserver/manifests/develop"
DEBU[0000] do request                                    digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json request.header.accept="application/vnd.oci.image.manifest.v1+json, */*" request.header.user-agent=containerd/1.3.4+unknown request.method=HEAD size=322 url="https://harbor.test.com/v2/mychart/helm/configserver/manifests/develop"
DEBU[0000] fetch response received                       digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json response.header.connection=keep-alive response.header.content-length=97 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=98ed942d03f7d36b00f07128458773c1; Path=/; HttpOnly" response.status="404 Not Found" size=322 url="https://harbor.test.com/v2/mychart/helm/configserver/manifests/develop"
DEBU[0000] do request                                    digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json request.header.content-type=application/vnd.oci.image.manifest.v1+json request.header.user-agent=containerd/1.3.4+unknown request.method=PUT size=322 url="https://harbor.test.com/v2/mychart/helm/configserver/manifests/develop"
DEBU[0000] fetch response received                       digest="sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3" mediatype=application/vnd.oci.image.manifest.v1+json response.header.connection=keep-alive response.header.content-length=82 response.header.content-type="application/json; charset=utf-8" response.header.date="Tue, 05 Jan 2021 07:32:57 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server=nginx/1.11.13 response.header.set-cookie="beegosessionID=c3ec10978eb7ab39bf9d4956a5f760e8; Path=/; HttpOnly" response.status="400 Bad Request" size=322 url="https://harbor.test.com/v2/mychart/helm/configserver/manifests/develop"
Error: failed commit on ref "manifest-sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3": unexpected status: 400 Bad Request
helm.go:81: [debug] unexpected status: 400 Bad Request
github.com/containerd/containerd/remotes/docker.(*pushWriter).Commit
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/docker/pusher.go:347
github.com/containerd/containerd/content.Copy
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/content/helpers.go:151
github.com/containerd/containerd/remotes.push
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:171
github.com/containerd/containerd/remotes.PushHandler.func1
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:146
github.com/containerd/containerd/remotes.PushContent
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:216
github.com/deislabs/oras/pkg/oras.Push
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/deislabs/oras@v0.8.1/pkg/oras/push.go:55
helm.sh/helm/v3/internal/experimental/registry.(*Client).PushChart
	/private/tmp/helm-20201209-72230-gqtdqr/internal/experimental/registry/client.go:131
helm.sh/helm/v3/pkg/action.(*ChartPush).Run
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/action/chart_push.go:43
main.newChartPushCmd.func1
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/chart_push.go:45
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/asm_amd64.s:1374
failed commit on ref "manifest-sha256:3efc315166c3ee16750a4d160b82643cb70fafeea0725972d2d65193eb6dabe3"
github.com/containerd/containerd/content.Copy
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/content/helpers.go:153
github.com/containerd/containerd/remotes.push
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:171
github.com/containerd/containerd/remotes.PushHandler.func1
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:146
github.com/containerd/containerd/remotes.PushContent
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containerd/containerd@v1.3.4/remotes/handlers.go:216
github.com/deislabs/oras/pkg/oras.Push
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/deislabs/oras@v0.8.1/pkg/oras/push.go:55
helm.sh/helm/v3/internal/experimental/registry.(*Client).PushChart
	/private/tmp/helm-20201209-72230-gqtdqr/internal/experimental/registry/client.go:131
helm.sh/helm/v3/pkg/action.(*ChartPush).Run
	/private/tmp/helm-20201209-72230-gqtdqr/pkg/action/chart_push.go:43
main.newChartPushCmd.func1
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/chart_push.go:45
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20201209-72230-gqtdqr/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/asm_amd64.s:1374
