### ISSUE TITLE
Not able to push charts with helm OCI registry method for robot accounts

### ISSUE THREAD

**Issue by binnie268** [goharbor/harbor#13802]
What can we help you?
We are facing an issue where we are not able to use helm registry login with robot accounts. We are only able to do helm registry login with admin account via the OCI registry method. Could we add support OCI registry method for robot accounts?

**Harbor version**: v2.1.0-a3eca103

When executing
```
export HELM_EXPERIMENTAL_OCI=1
helm registry login harbor.xxxx.com -u robot$account -p $(HARBOR_PASSWORD)
```

We get this error:
```
WARNING: Using --password via the CLI is insecure. Use --password-stdin.
Error: Get "***v2/": unauthorized: authentication required
```

Thanks!

**Comment by sluetze** [comment]
do you properly escape the $ in robot$account ?

**Comment by binnie268** [comment]
@sluetze yes that worked...thanks :) !

**Comment by Gigigotrek** [comment]
If somebody need some more tips, we also had to single quotes.

`helm registry login harbor.xxxx.com -u 'robot\$account' -p $(HARBOR_PASSWORD)`

In our case we were using it from Jenkins and the command needed was

```
        stage("Push Helm charts to registry") {
            when { changeRequest target: 'main' }
            environment {
                CHART_REPO='harbor.xxxx.com/REPO'
                HELM_EXPERIMENTAL_OCI=1
                REPO_USERNAME="robot\$\$account"
            }
            steps {
                    script {
                        try {
                            sh('''echo $(REPO_PASSWORD) | helm registry login --username '$(REPO_USERNAME)' --password-stdin $(CHART_REPO)''')
                        } catch (ex) {
                            unstable('The chart could not be pushed')
                        }
                    }
            }

```
