### ISSUE TITLE
OICD Redirect-Url wrong with reverse proxy

### ISSUE THREAD

**Issue by KirschbaumP** [goharbor/harbor#13814]
Hi guys,

I deployed a system like this:

(reverse proxy - ssl termination) <--> (harbor - nginx) ...

If I try to add an OICD-Provider the redirect-url has the internal url with http://...:40080/..
and not https://...:443/...

Does someone have the same problem or got it running somehow?

**Comment by ywk253100** [comment]
What's the `hostname` or `external_url` configured?

**Comment by KirschbaumP** [comment]
Tanks! I forgot to set the external_url...
