### ISSUE TITLE
Upgrade from 1.10.6 to 2.1.1 breaks ldaps

### ISSUE THREAD

**Issue by dtkelse** [goharbor/harbor#13811]
Subject pretty much says it all. Using ldaps:// with v1.9.4 and with v1.10.6 works , users can log in.
Then I upgraded to v2.1.1 and users logging via ldaps no longer works. If I change the configuration
from ldaps to simply ldap, users can login.

What changed in 2.x ?

In core.log I see (but im not sure if its related) : 
Appending internal xls trust CA to ca-bundle ...
find : /etc/harbor/ssl: No such file or dir
Internal xls trust CA appending is Done

I cannot find anything in harbor docs talking about /etc/harbor/ssl. I cannot get ldaps working.

Pls advice

**Comment by alexandrovas** [comment]
@dtkelse 
I use ldaps in my Harbor 2.1.1 and it works nice. You need add your custom root CA certificate to your `harbor.yml`:
```yaml
...
storage_service:
  ca_bundle: /etc/ssl/certs/ca-certificates.crt
...
```

In `ca_bundle` option you can specify path to you system certificate bundle (as in my case) or path to you CA certificate.

After change `harbor.yml` file you need rerun the installation script `install.sh`. Your data will not be affected.

**Comment by stonezdj** [comment]
If there are multiple trusted certificates need to install in all harbor containers, you should copy it to the directory 
`<harbor install directory>/common/config/shared/trust-certificates`  after Harbor installed. it will be installed to the trusted certificate by default.

**Comment by dtkelse** [comment]
> 
> 
> @dtkelse
> I use ldaps in my Harbor 2.1.1 and it works nice. You need add your custom root CA certificate to your `harbor.yml`:
> 
> ```yaml
> ...
> storage_service:
>   ca_bundle: /etc/ssl/certs/ca-certificates.crt
> ...
> ```
> 
> In `ca_bundle` option you can specify path to you system certificate bundle (as in my case) or path to you CA certificate.
> 
> After change `harbor.yml` file you need rerun the installation script `install.sh`. Your data will not be affected.

Thanks ..but that just gives me an error during the install.sh run :
Error:root:errno 2 No such file or directory: '/hostfs/etc/pki/tls/certs/ca-bundle.trust.crt'

**Comment by dtkelse** [comment]
> 
> 
> If there are multiple trusted certificates need to install in all harbor containers, you should copy it to the directory
> `<harbor install directory>/common/config/shared/trust-certificates` after Harbor installed. it will be installed to the trusted certificate by default.

Hello, Ive tried what you mention but ldaps still fails w/ tls handshake error. This did not happen during 1.10.6. 
Can you point me to the docs where it discusses pushing files to that common/config/shared/trusted-certificates dir?

**Comment by dtkelse** [comment]
> 
> 
> If there are multiple trusted certificates need to install in all harbor containers, you should copy it to the directory
> `<harbor install directory>/common/config/shared/trust-certificates` after Harbor installed. it will be installed to the trusted certificate by default.

Can I use a bundled file or does each cert need to be pulled out into its own file ?

**Comment by dtkelse** [comment]
> 
> 
> > @dtkelse
> > I use ldaps in my Harbor 2.1.1 and it works nice. You need add your custom root CA certificate to your `harbor.yml`:
> > ```yaml
> > ...
> > storage_service:
> >   ca_bundle: /etc/ssl/certs/ca-certificates.crt
> > ...
> > ```
> > 
> > 
> > In `ca_bundle` option you can specify path to you system certificate bundle (as in my case) or path to you CA certificate.
> > After change `harbor.yml` file you need rerun the installation script `install.sh`. Your data will not be affected.
> 
> Thanks ..but that just gives me an error during the install.sh run :
> Error:root:errno 2 No such file or directory: '/hostfs/etc/pki/tls/certs/ca-bundle.trust.crt'

alexandrovas, the entry i put in for the 'ca_bundle' option was a link... harbor didnt like that. I put the correct filename
in and get past the install.sh/prepare but ldaps still doesnt work. I do see debug msgs in core.log : 
DEBUG : failed to get key ldap_filter, error: the configure value is not set
DEBUG: failed to get key ldap_group_search_filter, error: the configure value is not set

Im assuming those are only debug stmts and not an error... as this config worked before the upgrade to 2.1.1

**Comment by alexandrovas** [comment]
@dtkelse
Looks like you have an error in these fields in your Harbor ldap configuration.
Have you checked the connection to the LDAP server via button "TEST LDAP SERVER"?

**Comment by dtkelse** [comment]
alexandrovas,

The 'test ldap server' does the same..  failure.
I do not believe those fields are required...as it works in earlier versions, and that is what is 
shown in the harbor docs for ldap configuration.

The question I have remains however : my config works in 1.9 and 1.10, and not in 2.1.1. All
I did was the upgrade. Ive checked the docs and my ldap config is still valid as documented
in the harbor ldap config docs. 

Ive tried adding certs in common/.../trust-certificates, Ive uncommented out the storage_service
param in harbor.yml and provided a valid ca bundle for the ca_bundle option.

Thanks

**Comment by stonezdj** [comment]
You should copy the cert file to the directory after the prepare or install.sh.
The harbor.yml's ca_bundle option doesn't make sense.
