### ISSUE TITLE
Upgrading from v1.10.6 to v2.1.1 breaks existing replication agreements

### ISSUE THREAD

**Issue by dtkelse** [goharbor/harbor#13812]
Title pretty much says it all.

Another issue w/ the upgrade from v1.10.6 to v2.1.1 is that it has broken existing replication
functionality. Replication was configured and working in v1.9.4. Upgraded system to v1.10.6
and replication worked fine. Upgraded system to v2.1.1 on both systems and replication now
fails. 

In the jobservice.log file I see the following : 
errors : code : UNAUTHORIZED , message : authentication required

What changed in v2.1.1 that has broken replication agreements? What has changed w/
authentication in v2.1.1 ?

- Thanks

**Comment by ywk253100** [comment]
There shouldn't break anything. Could you package all logs for source and destination Harbor instance and upload them?

**Comment by dtkelse** [comment]
I agree w/ you ... this configuration worked w/ 1.9.4, it worked w/ 1.10.6 ... however upgrading to 2.1.1 broke it. Nothing
else has changed. Unfor I cannot easily upload logs.

**Comment by dtkelse** [comment]
On the client replication side, in the registry.log file I see the following error : 

level = warning msg="error authorizing context: basic authentication challenge for realm "harbor-registry-basic-realm" : authentication failure

On the server side, I see its trying to use http to connect to remote

Again, this is working in 1.9 and 1.10, not in 2.1.1 however

Thanks
