### ISSUE TITLE
CHANGELOG.md hasn't been updated since 1.8.0

### ISSUE THREAD

**Issue by stefanlasiewski** [goharbor/harbor#13829]
The `CHANGELOG.md` file hasn't been updated in quite some time. The most recent update covers v1.8.0. Can the changelog that be updated to reflect the changes after v1.8.0 ? Tracking down the changes via https://github.com/goharbor/harbor/releases is fairly burdensome if we're looking at more then one release.

![image](https://user-images.githubusercontent.com/142752/102954795-32e4dd00-4489-11eb-9116-b8a10535f534.png)

**Comment by msudgh** [comment]
I found Harbor's blog for such cases. Unfortunately, the changelog is still outdated.
https://goharbor.io/blog/
