### ISSUE TITLE
Unable to add Dockerhub registry endpoint

### ISSUE THREAD

**Issue by strange-developer** [goharbor/harbor#13837]
Harbor: V2.1.2
OS: Ubuntu 20.04.1 LTS
Docker version: 20.10.1
Docker Compose version: 1.25.5

When trying to add Dockerhub as an endpoint, I receive the following error:

![image](https://user-images.githubusercontent.com/17576163/102978944-032be880-450e-11eb-90f8-9609635399af.png)

I've tried with the credentials and without the credentials. This is a fresh installation of Harbor as well. I am trying to create a proxy cache for Dockerhub. I've added updated the port number on the `proxy` docker service to `5000:8080`. The rest of the installation is at default. I'm also testing this on my machine so the `harbor.yml` hostname is set to `localhost`.

Is there a problem in the setup of Harbor to be able to cache images from Dockerhub?

**Comment by z-yfgit** [comment]
can't see the picture.


hostname is set to localhost is not allow

**Comment by z-yfgit** [comment]
harbor.yml hostname is set to localhost is not allow

**Comment by WiXZlo** [comment]
I had same problems because docker for non-default network incorrect works with systemd-resolved.
For fix I configured DNS servers in docker config. 
* need create file  `/etc/docker/daemon.json`
* add to file
```
{
    "dns": ["8.8.8.8", "8.8.4.4"]
}
```
* restart docker.service
