### ISSUE TITLE
Developer role can delete image via docker registry api

### ISSUE THREAD

**Issue by stingshen** [goharbor/harbor#13833]
**Expected behavior and actual behavior:**

Expected: Developer role cannot delete image with any API. Ref: https://goharbor.io/docs/1.10/administration/managing-users/user-permissions-by-role/

Actual: Developer role can delete image with docker registry API.

**Steps to reproduce the problem:**

1. Make user A as developer role
2. User A can still delete image from harbor using docker registry API. For example, use skopeo: skopeo delete --debug --tls-verify=false docker://docker-registry/repository:tag

**Versions:**

- harbor version: v1.10.4-417e12ec
- docker engine version: 19.03.9

**Comment by xaleeks** [comment]
@stingshen  Thanks a lot for finding this, this is indeed a security issue and I don't know how we missed it.  This will be patched across 1.10.x, 2.0.x, and 2.1.x.  2.1.3 will be the first of these patches.

**Comment by reasonerjt** [comment]
fix for 1.10.x: https://github.com/goharbor/harbor/pull/13871
fix for 2.0.x: https://github.com/goharbor/harbor/pull/13874  (merged)
fix for 2.1.x: https://github.com/goharbor/harbor/pull/13873 (merged)
fix for 2.2.0: https://github.com/goharbor/harbor/pull/13872 (merged)

**Comment by reasonerjt** [comment]
closing as #13871 is merged.

**Comment by bburky** [comment]
Release [v2.0.6](https://github.com/goharbor/harbor/releases/tag/v2.0.6) and this ticket clearly describe this as a security fix. Will a CVE be issued and added to the [security advisories](https://github.com/goharbor/harbor/security/advisories) list?
