### ISSUE TITLE
Add endpoint failed in Registries.

### ISSUE THREAD

**Issue by z-yfgit** [goharbor/harbor#13841]
**Expected behavior and actual behavior:**
Add endpoint failed in Registries.

**Steps to reproduce the problem:**
My architecture is : The Master is deployed in the K8S cluster under helm. Slave is started with Docker-Compose.
Because the target host port is already occupied. So I map it this way:
`439e53258db6        goharbor/nginx-photon:v2.1.1                          "nginx -g 'daemon of…"   8 minutes ago       Up 8 minutes (healthy)   33.33.33.33:80->8080/tcp, 33.33.33.33:443->8443/tcp   nginx`

When add endpoint, Test connection failed. I don't think the address in the log should have a IP（33.33.33.33）

Other than that, all my services are normal。 
The target host may also be accessed through curl or the browser

**Versions:**

- harbor version: [2.1.1]
- docker engine version: [19.03.9]
- docker-compose version: [1.18.0]
- helm version: [3.4.0]

**Additional context:**

helm charts:
`
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "****-com"
  ingress:
    hosts:
      core: harbor.****.com

externalURL: https://harbor****.com

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    jobservice:
      storageClass: "rbd"
      accessMode: ReadWriteOnce
      size: 2Gi
    trivy:
      storageClass: "rbd"
      accessMode: ReadWriteOnce
      size: 10Gi
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: us-w**
      bucket: harbor***
      accesskey: JTXGURV***
      secretkey: BHRu02vnIrxIYj***
      regionendpoint: http://c***
      secure: false
      v4auth: false
      chunksize: "104857600"
imagePullPolicy: IfNotPresent
logLevel: info
harborAdminPassword: "****"

portal:
  replicas: 2
core:
  replicas: 2
jobservice:
  replicas: 1
registry:
  replicas: 2
chartmuseum:
  replicas: 2
clair:
  enabled: false
trivy:
  enabled: true
notary:
  enabled: false

database:
  type: external
  external:
    host: "***"
    port: "****"
    username: "****"
    password: "****"
    coreDatabase: "harbor_core"

redis:
  type: external
  external:
    addr: "****"
    coreDatabaseIndex: "3"
    jobserviceDatabaseIndex: "4"
    registryDatabaseIndex: "5"
    chartmuseumDatabaseIndex: "6"
    clairAdapterIndex: "7"
    trivyAdapterIndex: "8"
    password: ""
`

docker-compose.yaml:
`

hostname: registry2.****.com
http:
  port: 33.33.33.33:80
https:
  port: 33.33.33.33::443
  certificate: /home/apps/harbor/certs/tls.crt
  private_key: /home/apps/harbor/certs/tls.key
harbor_admin_password: qoW3FasUNwEG
database:
  password: WY****
  max_idle_conns: 50
  max_open_conns: 1000
data_volume: /home/apps/harbor/data
clair:
  updaters_interval: 12
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /home/apps/harbor/log
_version: 2.0.0
proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy
`

harbor-core logs:
`2020-12-24T07:07:03Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://registry2.example.com: Get "https://registry2.xfreeapp.com:33.33.33.33/service/token?service=harbor-registry": dial tcp: lookup registry2.example.com:33.33.33.33: no such host`

**Comment by z-yfgit** [comment]
If I don't bind IP， I change the port ，I can add endpoint

**Comment by z-yfgit** [comment]
The problem is on the target host. Using Docker Pull directly will report the same error. Harbor which was started by Docker-Composedoes not support port binding to iP?

**Comment by z-yfgit** [comment]
@jessehu

**Comment by jessehu** [comment]
` The Master is deployed in the K8S cluster under helm. Slave is started with Docker-Compose.`
What does master and slave mean and why this kind deployment is needed?
/cc @reasonerjt to triage.

**Comment by z-yfgit** [comment]
> ` The Master is deployed in the K8S cluster under helm. Slave is started with Docker-Compose.`
> 主从是什么意思，为什么需要这种部署？
> / cc @reasonerjt进行分类。

To prevent the master down。

$ cat core/env 
`CONFIG_PATH=/etc/core/app.conf
UAA_CA_ROOT=/etc/core/certificates/uaa_ca.pem
_REDIS_URL_CORE=redis://redis:6379?idle_timeout_seconds=30
SYNC_QUOTA=true
CHART_CACHE_DRIVER=redis
_REDIS_URL_REG=redis://redis:6379/1?idle_timeout_seconds=30

LOG_LEVEL=info
EXT_ENDPOINT=https://registry2.example.com:33.33.33.33:443`

The problem arises in the last line.
IP is added when the EXT ENDPOINT is generated

**Comment by z-yfgit** [comment]
我手动将 common/config/core/env文件中的EXT_ENDPOINT=https://registry2.example.com:33.33.33.33:443  修改为EXT_ENDPOINT=https://registry2.example.com:443，common/config/nginx/nginx.conf文件中的`return 308 https://$host:33.33.33.33:443$request_uri;`修改为`return 308 https://$host:443$request_uri;`后可以正常使用

**Comment by jessehu** [comment]
Good to know it's resolved. Could you please close this ticket?
