### ISSUE TITLE
harbor replication failed code 405

### ISSUE THREAD

**Issue by bruceforlearn** [goharbor/harbor#13855]
Hello Guys.
I used same harbor version v1.10.6 very well,but harbor replication failed code 405 just like that:
![微信图片_20201228092043](https://user-images.githubusercontent.com/29446582/103183524-fe8c7900-48ed-11eb-8581-eda1ce2f60a1.jpg)
![微信图片_20201228092047](https://user-images.githubusercontent.com/29446582/103183525-ffbda600-48ed-11eb-9d49-e54f66bc9201.png)
between two harbor servers,I have added daemon.json "insecure-registries": ["harbor.szlanyou.com","harbor.test.com", and Login Succeeded.
does anyone  help ?

**Comment by bruceforlearn** [comment]
Dec 28 14:26:41 172.18.0.1 core[18279]: 2020-12-28T06:26:41Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://10.30.102.27: Head http://10.30.102.27/v2/: Get https://harbor.test.com/service/token?service=harbor-registry: read tcp 172.18.0.2:39072->69.172.200.109:443: read: connection reset by peer
Dec 28 14:26:41 172.18.0.1 core[18279]: 2020-12-28T06:26:41Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}
Dec 28 14:26:41 172.18.0.1 core[18279]: 2020/12/28 06:26:41.922 #033[1;44m[D]#033[0m [server.go:2774]  |    10.30.9.101|#033[97;43m 400 #033[0m| 513.803885ms|   match|#033[97;46m POST    #033[0m /api/registries/ping   r:/api/registries/ping
Dec 28 14:26:50 172.18.0.1 core[18279]: 2020/12/28 06:26:50.652 #033[1;44m[D]#033[0m [server.go:2774]  |      127.0.0.1|#033[97;42m 200 #033[0m|    573.788µs|   match|#033[97;44m GET     #033[0m /api/ping   r:/api/ping
Dec 28 14:26:51 172.18.0.1 core[18279]: 2020-12-28T06:26:51Z [ERROR] [/replication/adapter/native/adapter.go:154]: failed to ping registry http://10.30.102.27: Head http://10.30.102.27/v2/: Get https://harbor.test.com/service/token?service=harbor-registry: read tcp 172.18.0.2:39104->69.172.200.109:443: read: connection reset by peer
Dec 28 14:26:51 172.18.0.1 core[18279]: 2020-12-28T06:26:51Z [ERROR] [/common/api/base.go:73]: POST /api/registries/ping failed with error: {"code":400,"message":""}

**Comment by bitsf** [comment]
Is `docker login 10.30.102.27` successful ? Is login 10.30.102.27 UI successful? Is user `test` added in the project members

**Comment by bruceforlearn** [comment]
thank for reply 
off course docker login 10.30.102.27 successful 
I have solved this question 
it is not harbor question. it is dns question

thank you

**Comment by aminellouz** [comment]
> thank for reply off course docker login 10.30.102.27 successful I have solved this question it is not harbor question. it is dns question
> 
> thank you

how did you solved it plz ?
