### ISSUE TITLE
[Question] How does harbor makes blob exist in distribution registry when deleting blob in non-blocking GC process?

### ISSUE THREAD

**Issue by xiechengsheng** [goharbor/harbor#13854]
What can we help you?
Hi there, in the non-blocking gc process, the codes: https://github.com/goharbor/harbor/blob/bd46af691c1c977f50dc3f0b12f9f381cb9e07ae/src/server/middleware/blob/head_blob.go#L49-L58

Here, harbor server seems to tell docker clinet the blob you want to `head` is not existing, then the docker client would put blob to distribution registry. So my question is:
1. what if the blob is always in `"deleting"` status? 
2. Or, for a specific storage drvier, "deleting a blob" progress costs very long time in harbor, would the process of docker client puts the blob and the process of harbor deletes a blob(Note that the blob digest is the same) be conflicted? After these two processes finished, would the blob still exist in the distribution registry?

Any help would be appreciated!

**Comment by wy65701436** [comment]
1, what if the blob is always in "deleting" status?
`If the blob status is stuck on the delelting status, it will be back to normal if someone push the same blob again after two hours. But, within the two hours, any pushing will be rejected as the status is stuck on deleting`.

2, Or, for a specific storage drvier, "deleting a blob" progress costs very long time in harbor, would the process of docker client puts the blob and the process of harbor deletes a blob(Note that the blob digest is the same) be conflicted? After these two processes finished, would the blob still exist in the distribution registry?

The scenario that you mentioned here is a read-write confilict, the non-blocking GC was just designed for remove the read-write confilict when doing GC. Basiclly, we use optimistic lock and status to resolve it. But, for details, you can refer to the design proposal. https://github.com/goharbor/community/blob/master/proposals/new/Non-Blocking-GC.md
