### ISSUE TITLE
Groups not sync when connect harbor to LDAP

### ISSUE THREAD

**Issue by agentchif** [goharbor/harbor#13852]
hi
after install harbor on air-gap VM i tried to connect it to LDAP
when I connect it to LDAP I succeed to get the users but not the groups.
no matter what I type on the LDAP group section I got the error:
[/core/api/usergroup.go:54] failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax

i expect that the harbor will sync the groups the same as it sync the users but its not the situation right now.
from my searching over the web this issue was happened in earlier version but it according to the cases it supposed to be solve in version 2.0 - and i am running version 2.1.2

**Versions:**
- harbor version: 2.1.2
- docker engine version: 20.10.1
- docker-compose version: 1.27.4

**Comment by agentchif** [comment]
also when i log in with ldap user i am able to log in and the user appears in harbor users section but I got warnings in the log file:
[/core/auth/ldap/ldap.go:121] Can not get the ldap group name with DB CN=<group_name>,OU=<our_ou>,DC=<out_dc>
[/core/api/usergroup.go:54] failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax

so its seems like there is an issue with: /core/api/usergroup.go:54

10x alot

**Comment by sluetze** [comment]
have you defined a groupfilter in the ldap config? and if no, can you try to configure a filter, which matches all your groups?

**Comment by agentchif** [comment]
yes i tried to define a filter that much my criteria.
this filter is working fine on other systems in my lab.
the filter is (&(objectClass=Group)(cn=*))

and its not working

**Comment by kautkata** [comment]
I have seen issue like your's when I was trying to use harbor with pre-historic openldap instance. In my case reason why groups where not available in harbor was because of ldap data model.
 
 ldap protocol/implementation technically allows at least 2 ways how to define user/group membership:
1.  user object memberof attributes - e.g. each user has multiple memberfo attributes (with the same key) where each attribute points to one unique ldap group DN - harbor supports this ldap data model
2.  group object member attribute - e.g. each group has multiple member attributes (wit the same key) where each attribute points to one unique ldap user dn or something - harbor doesn't support this data model format 

In my case problem was that our pre-historic ldap used 2nd approach for group membership definition. I didn't open and issue related to this as as far as I know 2nd approach of membership definition is considered legacy or something. 

Keep in mind that 2nd approach puts extra load on harbor->ldap communication as for correct user group discovery harbor should scan all known groups in ldap and look into each of them individually for user membership resolving. 

So at least I would advise you to check you ldap data model first.

**Comment by agentchif** [comment]
our LDAP is support memberof method.
on other applications (like nexus, mattermost etc.. ) the connection to LDAP working well
so i think the problem is not with the ldap.

**Comment by vlgermanov** [comment]
Hi,
I would like to report the same issue.
- using Harbor v2.0.2 LDAP groups are automatically synced
- using Harbor v2.0.3 or v2.0.5 LDAP groups are not synced.

On all versions there is the same warning in the logs:
- v2.0.3 and v2.0.5
Jan  8 13:20:24 10.246.128.1 core[1463]: 2021-01-08T12:20:24Z [WARNING] [/core/api/usergroup.go:54]: failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Jan  8 13:20:24 10.246.128.1 core[1463]: 2021/01/08 12:20:24.070 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.130.39.63|#033[97;42m 200 #033[0m|   1.982923ms|   match|#033[97;44m GET     #033[0m /api/v2.0/usergroups   r:/api/v2.0/usergroups/?:ugid([0-9]+)

- v2.0.2
Jan  8 13:21:37 10.246.128.1 core[1466]: 2021-01-08T12:21:37Z [WARNING] [/core/api/usergroup.go:54]: failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Jan  8 13:21:37 10.246.128.1 core[1466]: 2021/01/08 12:21:37.741 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.130.39.63|#033[97;42m 200 #033[0m|   4.465974ms|   match|#033[97;44m GET     #033[0m /api/v2.0/usergroups   r:/api/v2.0/usergroups/?:ugid([0-9]+)

**Configuration:**
Connecting to MS AD
![image](https://user-images.githubusercontent.com/16061454/104015732-58762400-51b5-11eb-9f49-988b7f1a3d08.png)

**Result:**
- v2.0.2
![image](https://user-images.githubusercontent.com/16061454/104015763-662ba980-51b5-11eb-887d-bc08468b2952.png)

- v.2.0.3 and v2.0.5
![image](https://user-images.githubusercontent.com/16061454/104015835-80fe1e00-51b5-11eb-9438-dc00174d391e.png)

Let me know if you need more details/logs.

Thanks!

**Comment by stonezdj** [comment]
Harbor doesn't sync all LDAP groups when user login. when a ldap user login. it only sync the groups that the user is member of.

**Comment by vlgermanov** [comment]
Hi @stonezdj at the screenshots above, I was logged in via LDAP user and in v2.0.2, I can see that LDAP groups which the user is member of were synced, but in v2.0.3/5 -> LDAP groups were not synced.

**Comment by entasisj** [comment]
Hi, we observed the described misbehavior when upgrading from 1.10.6 to 2.1.3. Rolling back to 1.10.6 and upgrading to 2.0.2 resolved the issue.
Users could only access projects that are public or the users were explicitely added as members. Getting access via membership in an LDAP group did not work anymore.
``

**Comment by stonezdj** [comment]
@entasisj could you please check your ldap group filter and ldap_group_base_dn settings? it is doesn't take effective before 2.1.3, after 2.1.3, it is take effective when query ldap group and on board ldap group, if the group is out of the scope of the ldap_group_filter and ldap_group_base_dn. it doesn't work.

**Comment by santascsi** [comment]
I am seeing the same issue on a harbor that was upgraded from 1.10.1 to 2.1.3. The strange thing is that users in group 1 can login, but users in group 2 cannot. Both groups are covered by the ldap search config.

```
Feb  8 16:54:29 172.18.0.1 core[1898]: 2021-02-08T15:54:29Z [WARNING] [/core/api/usergroup.go:54]: failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Feb  8 16:59:21 172.18.0.1 core[1898]: 2021-02-08T15:59:21Z [WARNING] [/core/auth/ldap/ldap.go:121]: Can not get the ldap group name with DN CN=GROUP_2_REDACTED,OU=Harbor,OU=App,OU=Security Groups,DC=ACME,DC=COM
```
Group1 with DN `CN=GROUP_1_REDACTED,OU=Harbor,OU=App,OU=Security Groups,DC=ACME,DC=COM` works fine.

**Comment by alexanderdalloz** [comment]
Hi,
to my understanding there is no clear solution to the issue described in this ticket.
I am facing this issue where Active Directory based LDAP groups are not automatically listed on system level, though AD provides the memberOf attribute. A group has first to be added to Harbor explicitly and then can be picked up on project level to grant permissions.
Why are the AD based LDAP groups not enlisted automatically? The bind user can definitely see the groups. Using ldapsearch there is no issue to use all the config options like base DN and group filter to list the groups the bind user has permissions for.
The issue manifests at least with all of these Harbor releases:
v2.5.0-98e1b82f |   v2.5.1-b0506782 | v2.6.2-498e7e21 | v2.7.0-864aca34
