### ISSUE TITLE
How to regenerate Harbor's certificate after deployed 1 year?

### ISSUE THREAD

**Issue by spark1231** [goharbor/harbor#13850]
Hi all experts,

Sorry for first post question here, we have deployed harbor in our environment by using helm around 1 year ago. Since we did not modify specific configuration during installing harbor. Then, we are facing its certificate is expired now.

Is there any way to replace current certificate without remove and re-install harbor?

Here is our harbor's environment information

1. All certificates are self-signed during harbor installation
2. Using helm tool for harbor installation without special setting as mention above.
```
# kubectl get po
NAME                                           READY   STATUS    RESTARTS   AGE
harbor-harbor-adminserver-6f59774959-gsvfr     1/1     Running   16         133d
harbor-harbor-chartmuseum-5c7c7cbfc6-zdb9m     1/1     Running   13         385d
harbor-harbor-clair-7596895d88-nkfp9           1/1     Running   54085      385d
harbor-harbor-core-6cb5c66c97-vtjhh            1/1     Running   0          57m
harbor-harbor-database-0                       1/1     Running   13         385d
harbor-harbor-jobservice-7c644685f-972pt       1/1     Running   32         385d
harbor-harbor-nginx-557f986864-qsb98           1/1     Running   0          24m
harbor-harbor-notary-server-d9fb8fc7b-625p4    1/1     Running   0          56m
harbor-harbor-notary-signer-7d48cb95db-fbhwb   1/1     Running   0          56m
harbor-harbor-portal-c97c55c76-cdmsf           1/1     Running   6          133d
harbor-harbor-redis-0                          1/1     Running   14         385d
harbor-harbor-registry-5dcdfc75db-vlm7h        2/2     Running   0          56m

# kubectl get secrets 
NAME                        TYPE                                  DATA   AGE
default-token-nqqkl         kubernetes.io/service-account-token   3      385d
harbor-harbor-adminserver   Opaque                                4      385d
harbor-harbor-chartmuseum   Opaque                                1      385d
harbor-harbor-core          Opaque                                4      385d
harbor-harbor-database      Opaque                                1      385d
harbor-harbor-jobservice    Opaque                                1      385d
harbor-harbor-nginx         Opaque                                3      385d
harbor-harbor-registry      Opaque                                1      385d

# kubectl get configmaps 
NAME                          DATA   AGE
harbor-harbor-adminserver     39     385d
harbor-harbor-chartmuseum     24     385d
harbor-harbor-clair           1      385d
harbor-harbor-core            1      385d
harbor-harbor-jobservice      1      385d
harbor-harbor-nginx           1      385d
harbor-harbor-notary-server   5      385d
harbor-harbor-registry        2      385d
```

I found all certificates are encode and store in k8s secrets object. And I have also generated a new ca certificate, then base64 encode this ca.crt file and modify `harbor-harbor-nginx` secret replace the ca.crt section directly. 
However, after above steps, I still cannot docker login successfully and the error message is `x509: certificate has expired or is not yet valid`

My question is:

1. How many certificates should I generate for entire harbor usage?
2. If there are several certificates that I have to generate, what k8s secret object should I modify it? I mean the certificate and secret object mapping table

Thank you!!

**Comment by ninjadq** [comment]
remove all the cert files and reinstall harbor or use cert-manager to keep the cert up to date

**Comment by wu105** [comment]
The following worked for me on harbor 2.0.2:
Using the same helm 2 install command with --dry-run --debug options on a cluster that does not have the same release name, extract the harbor-notary-server secret, apply it to the harbor installation, delete the notary server and signer pods, if their logs still show the certificate issue, delete the pods a second time, and the logs are clear.

**Comment by lszxyz** [comment]
The default is 365 days. Would it be better to add a configurable expiration time to the value.yaml ?
