### ISSUE TITLE
After harbor installation, the default account and password are invalid

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#13867]
helm repo add harbor https://helm.goharbor.io

helm install  harbor  harbor/harbor  -n  harbor

The default account password is  ？？
account:    admin
password:  Harbor12345

But I can't log in

**Comment by yanji09** [comment]
What is the error shown in the UI? Any changes made in file values.yaml? And what is the expose type?

**Comment by forbearing** [comment]
same error
