### ISSUE TITLE
Harbor Proxy-Cache not pulling

### ISSUE THREAD

**Issue by gikvin** [goharbor/harbor#13865]
What can we help you?

I am using harbor proxy-cache to dockerhub. Pulling images like nginx with harbor proxy-cache is not a problem (HarborDomainName/proxy-cache/library/nginx), but when pulling images like vmware/harbor-log (HarborDomainName/proxy-cache/library/vmware/harbor-log), harbor can't read manifest and verify image existence.

**Comment by phin1x** [comment]
I think the image path for vmware/harbor-log should be HarborDomainName/proxy-cache/vmware/harbor-log

**Comment by gikvin** [comment]
> I think the image path for vmware/harbor-log should be HarborDomainName/proxy-cache/vmware/harbor-log

you are right, but this opens then the big problem. Most applications are written in the fashion they use registry in this format:
registryname/imagename, it means if imagename is nginx, it would throw error (HarborDomainName/proxy-cache/nginx), so there would be no fix to overwrite the default image URL settings with HarborDomainName/proxy-cache/ private registry string.

**Comment by gikvin** [comment]
reference to https://github.com/goharbor/harbor/issues/8082#issuecomment-698012277
