### ISSUE TITLE
Prompt error after system robot account deletion

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#13868]
After delete a system robot account, there is an error prompt, but the system robot account was deleted successfully.

Reproduce steps:
1. Create a  system robot account;
2. Go to view projects list;
3. Delete the system robot account;

![image](https://user-images.githubusercontent.com/44018302/103403939-ed14cc80-4b8c-11eb-823a-39aeced9bb79.png)

**Comment by wy65701436** [comment]
@AllForNothing it seems that the second DELETE call is redundant.
