### ISSUE TITLE
Docker login Harbor how to use ca.crt

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#13870]
[root@kubesphere core.harbor.domain]# kubectl describe secret harbor-harbor-ingress -n harbor   
Name:         harbor-harbor-ingress
Namespace:    harbor
Labels:       app=harbor
              app.kubernetes.io/managed-by=Helm
              chart=harbor
              heritage=Helm
              release=harbor
Annotations:  meta.helm.sh/release-name: harbor
              meta.helm.sh/release-namespace: harbor

Type:  kubernetes.io/tls

 \  Data
 \====
tls.key:  1675 bytes
ca.crt:   1086 bytes
tls.crt:  1164 bytes

[root@kubesphere core.harbor.domain]# kubectl get secret harbor-harbor-ingress -n harbor -o jsonpath="{.data.ca\.crt}"|base64 --decode  > ca.crt

[root@kubesphere core.harbor.domain]# docker login  https://core.harbor.domain:32522                                                             
Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain:32522/v2/: x509: certificate signed by unknown authority

[root@kubesphere core.harbor.domain]# ls
ca.crt  tls.crt  tls.key
[root@kubesphere core.harbor.domain]# pwd
/etc/docker/certs.d/core.harbor.domain

What's the solution?

**Comment by stonezdj** [comment]
You should copy the ca.crt to the directory: `/etc/docker/certs.d/core.harbor.domain:32522`

**Comment by misteruly** [comment]
Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain:31247/v2/: Get https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 172.20.0.2:443: connect: connection refused

Report this mistake again???
