### ISSUE TITLE
同步harbor容器时间后导致无法登陆

### ISSUE THREAD

**Issue by mlrsyz** [goharbor/harbor#13884]
这个问题我通过复制宿主机的/etc/localtime 命令如下
docker cp -L /usr/share/zoneinfo/Asia/Shanghai "容器名":/etc/localtime
完成了9大容器的时间不准确 然后产生了很突兀的bug 只要重启了harbor容器就无法使用争取的账号登录了
Linux 4.18.0-193.28.1.el8_2.x86_64 x86_64

Client: Docker Engine - Community
Version: 19.03.13
API version: 1.40
Go version: go1.13.15
Git commit: 4484c46d9d
Built: Wed Sep 16 17:02:36 2020
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 19.03.13
API version: 1.40 (minimum version 1.12)
Go version: go1.13.15
Git commit: 4484c46d9d
Built: Wed Sep 16 17:01:11 2020
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.3.7
GitCommit: 8fba4e9a7d01810a393d5d25a3621dc101981175
runc:
Version: 1.0.0-rc10
GitCommit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
docker-init:
Version: 0.18.0
GitCommit: fec3683

**Comment by stonezdj** [comment]
Can you please provide the error msg in harbor logs: /var/log/harbor/core.log?

**Comment by mlrsyz** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goharbor/harbor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 上午10:59
收件人:&nbsp;"goharbor/harbor"<harbor@noreply.github.com&gt;;
抄送:&nbsp;"叶梓"<mlrsyz@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goharbor/harbor] 同步harbor容器时间后导致无法登陆 (#13884)





 
Can you please provide the error msg in harbor logs: /var/log/harbor/core.log?
