### ISSUE TITLE
How to reset my passward?

### ISSUE THREAD

**Issue by www516717402** [goharbor/harbor#13880]
How to reset my passward? I only find sign up account

**Comment by sluetze** [comment]
If logged in as an admin user, you can reset the password of any user in the GUI
If logged in as user you can change your password on the top right corner

**Comment by www516717402** [comment]
thank you for reply. However as user i cant find button on the top right corner.
![image](https://user-images.githubusercontent.com/30460509/103536641-de505180-4ecd-11eb-953b-db9a97a56585.png)

**Comment by sluetze** [comment]
you need to be logged in.

if you completely forgot your password you should contact an administrator. if you are the administrator the further options depend on your authentication model (ldap, database etc.)

**Comment by www516717402** [comment]
thank you. Administrator help reset already.
