### ISSUE TITLE
docker login harbor  error

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#13907]
###  This is my operation record

[root@kubesphere certs.d]#helm install  harbor  harbor/harbor  --set  expose.type=nodePort --set  expose.tls.auto.commonName=core.harbor.domain  -n workshop
[root@kubesphere core.harbor.domain:30003]#kubectl get secret harbor-harbor-nginx -n workshop -o jsonpath="{.data.ca\.crt}"|base64 --decode  >  ca.crt
[root@kubesphere certs.d]# ls
core.harbor.domain:30003
[root@kubesphere certs.d]# 
[root@kubesphere certs.d]# docker login https://core.harbor.domain:30003  -u admin  -p  Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://core.harbor.domain:30003/v2/: Get https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 172.20.0.2:443: connect: connection refused
[root@kubesphere certs.d]# 
[root@kubesphere certs.d]# 
[root@kubesphere certs.d]# docker login http://core.harbor.domain:30002  -u admin  -p  Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://core.harbor.domain/v2/: dial tcp 172.20.0.2:443: connect: connection refused

Port 30002 is forced to switch to port 443 ??Can not skip the login??

Port 30003 is also unavailable ????

**Comment by stonezdj** [comment]
dup to #13878
