### ISSUE TITLE
Replication rule resource filter does not work with fragments

### ISSUE THREAD

**Issue by enajeeb** [goharbor/harbor#13900]
When I use `enajeeb/**`, I get 403 Forbidden error

<img width="541" alt="image" src="https://user-images.githubusercontent.com/3844941/103717175-abfc2e00-4f79-11eb-868c-c0d7f1ec4d0a.png">

```
==> log/harbor/core.log <==
Jan  5 17:09:51 192.168.176.1 core[19345]: 2021-01-06T01:09:51Z [ERROR] [/replication/operation/controller.go:103]: the execution 10 failed: failed to fetch artifacts: http status code: 403, body: <html>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: <head><title>403 Forbidden</title></head>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: <body>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: <center><h1>403 Forbidden</h1></center>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: <hr><center>nginx/1.17.10</center>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: </body>#015
Jan  5 17:09:51 192.168.176.1 core[19345]: </html>#015

```
But, If I be more specific `enajeeb/postgres`, it works as expected.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/3844941/103717244-d6e68200-4f79-11eb-920c-0513d67ec348.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.2]
- docker engine version: [19.03.14]
- docker-compose version: [1.18.0]

**Comment by stonezdj** [comment]
@enajeeb  could you please tell us which adapter are you using?

**Comment by enajeeb** [comment]
@stonezdj where can I check which adapter being used?

**Comment by bitsf** [comment]
did you input credential, it seems you don't have rights to access the images

**Comment by enajeeb** [comment]
`enajeeb/**` should include all images under my namespace so i don't understand why it would work for a specific repository under my namespace.
