### ISSUE TITLE
Scheduled Garbage Collection does not work

### ISSUE THREAD

**Issue by chaithramohan86** [goharbor/harbor#13917]
we are using harbor Version v2.1.0 and GC was scheduled to run daily and it worked fine for the first time. However after it ran once , I do not see it scheduled. I had to save the schedule to run daily once gain to get a scheduled job to run for the next day and when doing that the old job ID and logs got lost from the history. Please let me know why it does not work as expected and run daily and how the old logs went missing. 

I could not see any possible error in the job service or core logs as to why it went missing.

**Comment by steven-zou** [comment]
@wy65701436 

Any comments here?

**Comment by wy65701436** [comment]
the periodic gc job shares one histry item, it just refershes the status/end time and logs with the same history ID(As for v2.2, Harbor will use task manager to handle GC job, any periodic job will have a history item). 

You can try to monitor the end time of the periodic job. If you still find it's not refreshed, @steven-zou could you provide a way to search cron setting of gc in the redis? BTW, Harbor stores the GC schedule in the redis, so please do not clean the redis DB of jobservcie, otherwise the schedule will be lost.

**Comment by chaithramohan86** [comment]
![image](https://user-images.githubusercontent.com/47654067/103889245-1cd34f80-510c-11eb-914d-fd453f24d88d.png)

As seen in the image attached, there was a job with id 33 that was scheduled to run on the midnight of Jan 6 which ran for about 12 hours and completed successfully as expected
    

_2021-01-06T13:05:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:271]: delete manifest from storage: sha256:70933d7a33c9eb80945c9d8725d6cf81911835917cd50d33846d35e54169c4e3
2021-01-06T13:05:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:283]: delete artifact trash record from database: 7183, fsdactivate/fsd-activation-service, sha256:70933d7a33c9eb80945c9d8725d6cf81911835917cd50d33846d35e54169c4e3
2021-01-06T13:05:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:295]: delete blob from storage: sha256:70933d7a33c9eb80945c9d8725d6cf81911835917cd50d33846d35e54169c4e3
2021-01-06T13:05:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:309]: delete blob record from database: 555610, sha256:70933d7a33c9eb80945c9d8725d6cf81911835917cd50d33846d35e54169c4e3
2021-01-06T13:05:50Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:321]: The GC job actual frees up 1014423 MB space.
2021-01-06T13:07:36Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:173]: success to run gc in job._

As per the schedule set to daily, another job should have been scheduled for midnight of Jan 7th but I did not see it and assumed it will be triggered only at midnight, nothing happened. 

I tried saving the schedule again and now I see a job scheduled with ID 35 as seen on screen shot.

Maybe the explanation for job history is valid and thus it does not show the details of ID 33, but there are 2 queris
1) Why did the schedule not run today if it was set to daily , does it mean everyday it has to be saved to create a schedule
2) What should we do to check old histories of GCs?
![image](https://user-images.githubusercontent.com/47654067/103889663-c9153600-510c-11eb-9c67-a43e09e89b08.png)
Attaching also  a screen shot of schedule.


Any help is highly appreciated. Thanks a lot for reading and support

**Comment by chaithramohan86** [comment]
The job service pod is running for quite somedays as well as the redis-db pods so am not sure what kind of clean up would have been done here. Is there something else to be checked?

Controlled By:  StatefulSet/harbor-jobservice
Containers:
  jobservice:
    Container ID:   containerd://72a7c7e8695ed36f1a95524fa06e31867aafbc93e18d861fd438a769317c39da
    Image:          eu.gcr.io/metro-op-runtime-mcdr-live0/mcdr-mirror/goharbor/harbor-jobservice:v2.1.0
    Image ID:       eu.gcr.io/metro-op-runtime-mcdr-live0/mcdr-mirror/goharbor/harbor-jobservice@sha256:c3cb98642c9ac2c2b65af5e1af5dd10f7e1471f333393b7987c5487e8f21314e
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 31 Dec 2020 06:02:53 +0000
    Last State:     Terminated
      Reason:       Unknown
      Exit Code:    255
      Started:      Thu, 24 Dec 2020 06:19:54 +0000
      Finished:     Thu, 31 Dec 2020 06:02:07 +0000
    Ready:          True
    Restart Count:  3

**Comment by chaithramohan86** [comment]
Schedule that ran today ( because i explicitly saved it again yesterday)
![image](https://user-images.githubusercontent.com/47654067/103977167-a6336200-519e-11eb-8ba5-4fdccac32672.png)

As you can see 35 is the latest one that ran and there is no job scheduled to run tonight inspite of enabling daily schedule

**Comment by steven-zou** [comment]
@chaithramohan86 

You can use the following commands to check if there are scheduled created at the jobservice dataset (in redis)

1. Enter your Redis container `docker exec -ti redis /bin/bash`
2. Connect to the Redis `redis-cli -n 2` `2` is the db index for jobservice (you can find the settings in the installation configuration yaml file `harbror.yaml`)
3. Find all the schedule policies related to IMAGE_GC wth command: `zrange {harbor_job_service_namespace}:period:policies 0 -1`

**Comment by chaithramohan86** [comment]
@steven-zou 

I did the below steps after logging into the redis pod

k -n registry exec -it redis-ha-server-0 sh


/data $ redis-cli -n 2

127.0.0.1:6379[2]> auth XXX
OK
127.0.0.1:6379[2]> zrange {harbor_job_service_namespace}:period:policies 0 -1
(empty array)
127.0.0.1:6379[2]> zrange {registry}:period:policies 0 -1 // just tried replacing the namespace of jobservice
(empty array)
127.0.0.1:6379[2]> exit
/data $

**Comment by stonezdj** [comment]
@chaithramohan86  could you please check if the data exist in the other redis node?

**Comment by chaithramohan86** [comment]
@stonezdj  I had already checked the other 2 pods for the values and found them empty.

We have a stateful set deployed for redis servers





`    ---
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: redis-ha-server
        namespace: registry
        labels:
          redis-ha: replica
          app: redis-ha
      spec:
        selector:
          matchLabels:
            app: redis-ha
        serviceName: redis-ha
        replicas: 3
        podManagementPolicy: OrderedReady
        updateStrategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: redis-ha
              redis-ha: replica
          spec:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app: redis-ha
                        redis-ha: replica
                    topologyKey: kubernetes.io/hostname
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app:  redis-ha
                          redis-ha: replica
                      topologyKey: failure-domain.beta.kubernetes.io/zone
            securityContext:
              fsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
            serviceAccountName: redis-ha
            initContainers:
            - name: config-init
              image: <%= scope['rp']['harbor']['redis']['image'] %>
              imagePullPolicy: IfNotPresent
              resources:
                {}
              command:
              - sh
              args:
              - /readonly-config/init.sh
              env:
              - name: SENTINEL_ID_0
                value: 4bd43a1eaa8574a74d87e7f2d1dcd8805e6987c0
      
              - name: SENTINEL_ID_1
                value: 0356c5ee334a804b217adf86bf25e03bc25e0057
      
              - name: SENTINEL_ID_2
                value: f595a6b3b94aeeafbba39fba31fba035eef40027
        
              - name: AUTH
                valueFrom:
                  secretKeyRef:
                    name: redis-ha
                    key: auth
              volumeMounts:
              - name: config
                mountPath: /readonly-config
                readOnly: true
              - name: data
                mountPath: /data
            containers:
            - name: redis
              image: <%= scope['rp']['harbor']['redis']['image'] %>
              imagePullPolicy: IfNotPresent
              command:
              - redis-server
              args:
              - /data/conf/redis.conf
              env:
              - name: AUTH
                valueFrom:
                  secretKeyRef:
                    name: redis-ha
                    key: auth
              resources:
                requests:
                  memory: <%= scope['rp']['harbor']['redis']['request_memory'] %>
                  cpu: <%= scope['rp']['harbor']['redis']['request_cpu'] %>
                limits:
                  memory: <%= scope['rp']['harbor']['redis']['limit_memory'] %>
                  cpu: <%= scope['rp']['harbor']['redis']['limit_cpu'] %>
              livenessProbe:
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 15
                successThreshold: 1
                failureThreshold: 5
                exec:
                  command:
                    - sh
                    - -c
                    - /health/redis_liveness.sh
              resources:
                {}
              ports:
              - name: redis
                containerPort: 6379
              volumeMounts:
              - mountPath: /data
                name: data
              - mountPath: /health
                name: health
            - name: sentinel
              image: <%= scope['rp']['harbor']['redis']['image'] %>
              imagePullPolicy: IfNotPresent
              command:
                - redis-sentinel
              args:
                - /data/conf/sentinel.conf
              env:
              - name: AUTH
                valueFrom:
                  secretKeyRef:
                    name: redis-ha
                    key: auth
              livenessProbe:
                initialDelaySeconds: 30
                periodSeconds: 15
                timeoutSeconds: 15
                successThreshold: 1
                failureThreshold: 5
                exec:
                  command:
                    - sh
                    - -c
                    - /health/sentinel_liveness.sh
              resources:
                {}
              ports:
                - name: sentinel
                  containerPort: 26379
              volumeMounts:
              - mountPath: /data
                name: data
              - mountPath: /health
                name: health
            volumes:
            - name: config
              configMap:
                name: redis-ha-configmap
            - name: health
              configMap:
                name: redis-ha-health-configmap
                defaultMode: 0755
            <%- if '%{lookup('registry::pvc::enabled')}' == "false" -%>
            - emptyDir: {}
              name: data
            <%- end -%>
        <%- if '%{lookup('registry::pvc::enabled')}' == "true" -%>
        volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: "50Gi"
            storageClassName: "fast"
        <%- end -%>

`

We also have configs loaded via config map

**Comment by chaithramohan86** [comment]
@stonezdj @steven-zou is there something else that we could check?

**Comment by chaithramohan86** [comment]
hi do we have any updates here @stonezdj  @steven-zou  something further that we could do to check from our side?

**Comment by chaithramohan86** [comment]
Will it help if we upgrade harbor to next version

**Comment by steven-zou** [comment]
@chaithramohan86 

It seems your Redis is running with sentinel mode, is that correct?

As you have checked policy data with cmd ` zrange {harbor_job_service_namespace}:period:policies 0 -1` on redis database with index 2 and got empty data, that might be the root cause of the issue. If the policy is not written into the Redis, there will not be a second run as expected. It's a little weird because the 1st time run is ok but the policy list is empty, which means data can be written into some keys of Redis, not every key.

Would you double-check the policy is really not in the Redis and no errors in the jobservice logs?

@bitsf do you have any other comments for troubleshooting this issue?

**Comment by chaithramohan86** [comment]
hi @steven-zou ,

We tried to debug the issues that caused the GC not to work. We found out that there was an inconsistency between the redis and the database data. For example if a replication job's status changes to delete / failed it would change in the redis cache but not in the database. Any operations done with regards to scheduling of GC or replication jobs or even simply editing them were causing internal server Error with job not found in logs. We had to manually delete the values in the database and then they started working as expected. Now the GC seems to run as per schedule though there is only one history item which keeps updating every time a new job runs (which is already known)

Suggestions for improvements :

1) As @wy65701436  had already mentioned in earlier comments " _Harbor stores the GC schedule in the redis, so please do not clean the redis DB of jobservice, otherwise the schedule will be lost_" , is there any specific reason that the redis cache which ideally is not the temporary cache is treated as the source of truth than the database? We use PVCs for redis pods but there seems to be an inconsistency between the data in redis and database at times which leads to these errors. We had upgraded to the minor version (2.1.3) and tested the issue still seems to persist. Is there a better way to deal with this issue or any improvements happening for the same?

2) We understand that the periodic GC job shares only one history item and it keeps getting refreshed but each time we can see only the latest logs. Please let us know if there is a way to get the old logs of the previous runs from somewhere ?
