### ISSUE TITLE
Enable automating an OIDC setup

### ISSUE THREAD

**Issue by slinstaedt** [goharbor/harbor#13911]
As an administrator I want to automate the setup of our harbor environment using OIDC (openid connect) as authentication method for single sign-on with our corporate identity provider.

As far as the documentation tells and after investigating the [source code](https://github.com/goharbor/harbor/blob/master/src/common/config/metadata/metadatalist.go), this is currently only possible using the UI and not via some applied configuration, so automation is not possible right now.

Like with the other supported authentication methods (db, ldap, uaa) I would like to configure AUTH_MODE=oidc_auth and also supply the additional OIDC specific configuration via environment variables, that are needed to preconfigure harbor to be able to use OIDC for authentication without the need to do this manually via UI.

As far as I see the straight forward solution would be extending the OIDC specific config items in https://github.com/goharbor/harbor/blob/master/src/common/config/metadata/metadatalist.go, so each of them  additionally contain an EnvKey analogous to the other config items, whose values are then picked up during application start and preconfigure it accordingly.

**Comment by Vad1mo** [comment]
We do it by updating the data in the DB directly, it's just a few columns. Works great so far. 
An API would be a great thought. However, I am not a big fan on putting everything in ENV or config files. I find this to be more app consumer specific.

**Comment by slinstaedt** [comment]
Thanks for the hint. I was not aware these configuration entries will be also stored in the DB, because once set up, they will probably never change.

**Comment by Vad1mo** [comment]
Here is the script we are using 

```sh
#!/usr/bin/env sh

_apply_db_script() { # $1 -> env. $2 -> file
  command -v psql >/dev/null 2>&1 || { echo >&2 "psql is required. but it's not installed."; exit 1; }
  command -v yq >/dev/null 2>&1 || { echo >&2 "yq is required. but it's not installed."; exit 1; }
  command -v sops >/dev/null 2>&1 || { echo >&2 "sops is required. but it's not installed."; exit 1; }
  PGHOSTADDR=$(yq -r .database.host "$1".values.yaml) \
  PGPORT=$(yq .database.port "$1".values.yaml) \
  PGDATABASE="$1"_harbor \
  PGUSER="$1"_harbor \
  PGPASSWORD=$(sops -d --extract '["database"]["password"]' "$1".secrets.yaml) \
  psql -f $2
}

db_customization_stage() {
  _apply_db_script stage ./customization/create_project_for_new_user.sql
}

```

```sql
--
-- Setting for the registry
--
INSERT INTO public.properties (id, k, v)
VALUES
    (1, 'oidc_client_id', ''),
    (2, 'oidc_endpoint', 'https://container-registry.eu.auth0.com/'),
    (3, 'oidc_name', 'Container Registry'),
    (4, 'oidc_scope', 'openid,offline_access,profile,email'),
    (5, 'oidc_client_secret', '<enc-'),
    (6, 'auth_mode', 'oidc_auth'),
    (7, 'project_creation_restriction', 'adminonly'),
    (8, 'email_ssl', 'true'),
    (9, 'email_username', 'AKIAVM5VRBMN'),
    (10, 'email_password', '<enc-'),
    (11, 'email_from', 'Container Registry <hello@container-registry.com>'),
    (12, 'email_host', 'email-smtp.eu-central-1.amazonaws.com'),
    (13, 'email_port', '465')
ON CONFLICT DO NOTHING;
```

**Comment by reasonerjt** [comment]
Thanks, @Vad1mo 
We store the OIDC settings in DB, b/c we want the admin to be able to update the setting, verify it without having to restart Harbor.

For the settings that are stored in DB, the admin needs to call Harbor's API to change them.

**Comment by Xartos** [comment]
@Vad1mo I have not looked if this is possible or how much implementation it would require to get this feature.
But is this something you think you would approve if it was implemented or is it not something you would want?

**Comment by reasonerjt** [comment]
@Xartos AFAIK, there will be a proposal that allows the admin to configure Harbor during start up, but this comes with a limitation that the configurations can't be updated via API, I'll link the proposal once is submitted.

**Comment by slinstaedt** [comment]
Does this proposal also supports GitOps?

**Comment by dioguerra** [comment]
> Does this proposal also supports GitOps?

im using a helm job to do this

**Comment by reasonerjt** [comment]
@slinstaedt could you elaborate your question?

The settings will be set via an environment variable:
https://github.com/goharbor/community/pull/158

**Comment by slinstaedt** [comment]
goharbor/community#158 will close this one.

**Comment by reasonerjt** [comment]
OK, I'm closing it as the proposed configuration approach has been checked into master branch

**Comment by fabasoad** [comment]
@reasonerjt So, can we use env vars to define OIDC settings now? Could you please point me to the list of env vars for this purpose?
