### ISSUE TITLE
How to run Harbor in host network?

### ISSUE THREAD

**Issue by shashank-k** [goharbor/harbor#13920]
I have issues running harbor in bridge network in docker compose. Is there a way or document which will show how to run harbor in host network rather than bridge network?

**Comment by phin1x** [comment]
Can you give us more information on what problems you are running into? We are using harbor with the provided docker-compose  file without any issues.

**Comment by whitfin** [comment]
@phin1x hi!

Found this while looking for a similar issue, but I have this question too - use case is internal AWS DNS hostnames not resolving from within containers because they're not on the host network. 

Maybe there's now some way to set all containers to host in the Harbor config?
