### ISSUE TITLE
如何停止auto image scan的排程?

### ISSUE THREAD

**Issue by ypl75** [goharbor/harbor#13926]
大家好，
harbor 1.5.2 從jobservice.log發現，每日八點都會進行IMAGE_SCAN，
並且會有 [ERROR]: Unexpected error: Post http://clair:6060/v1/layers: dial tcp: lookup clair
不知如何停止auto image scan的排程?
謝謝

---------------------------------------------------------------------------------------------------------------------------------------
Jan  6 08:00:56 172.18.0.1 jobservice[1698]: 2021-01-06T00:00:56Z [INFO] Job incoming: IMAGE_SCAN:37892d8242d577fe2007d22f

Jan  6 08:01:17 172.18.0.1 jobservice[1698]: 2021-01-06T00:01:17Z [ERROR] [service_logger.go:63]: Job 'IMAGE_SCAN:cb1b7add6887a7bb96ba11de' exit with error: 404 {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"ibmb/check-domestic-deposit-business","Revision":"sha256:f892f06fbb69e1484f7dfb5ec8e44c4240ad00e3a9592f0e8b20a6b76ceb33e4"}}]}

Jan  6 08:01:37 172.18.0.1 jobservice[1698]: 2021-01-06T00:01:37Z [ERROR] [client.go:83]: Unexpected error: Post http://clair:6060/v1/layers: dial tcp: lookup clair: Temporary failure in name resolution

**Comment by bitsf** [comment]
看起来clair容器没有起来，或者dns解析有问题，可以依次尝试重启harbor-clair容器，harbor-jobservice容器，docker service

**Comment by ypl75** [comment]
HI bitsf,
我昨天有重啟harbor及docker，但看起來今日八點一樣的錯誤又出現。
可以請問harbor-clair容器怎重啟呢?  我們安裝時，好像沒有clair。

# docker-compose ps
       Name                     Command                  State                                    Ports
-------------------------------------------------------------------------------------------------------------------------------------
harbor-adminserver   /harbor/start.sh                 Up (healthy)
harbor-db            /usr/local/bin/docker-entr ...   Up (healthy)   3306/tcp
harbor-jobservice    /harbor/start.sh                 Up
harbor-log           /bin/sh -c /usr/local/bin/ ...   Up (healthy)   127.0.0.1:1514->10514/tcp
harbor-ui            /harbor/start.sh                 Up (healthy)
nginx                nginx -g daemon off;             Up (healthy)   0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp, 0.0.0.0:80->80/tcp
redis                docker-entrypoint.sh redis ...   Up             6379/tcp
registry             /entrypoint.sh serve /etc/ ...   Up (healthy)   5000/tcp

**Comment by bitsf** [comment]
安装时如果执行 `install.sh --with-clair` 会安装 clair 容器，如果没有安装的话那么 image scan 功能是不应使用的
你可以看一下是不是某个项目的`配置管理`中把`自动扫描镜像`打开了
![image](https://user-images.githubusercontent.com/188115/104031204-66ed2b80-5207-11eb-9a79-c9b78beb0a51.png)
或者`审查服务`中配置了定时扫描
![image](https://user-images.githubusercontent.com/188115/104031623-ea0e8180-5207-11eb-822c-4887ba5735d3.png)

不过你用的1.5.2版本比较老，界面和功能可能不太一样

**Comment by stonezdj** [comment]
Could you please upgrade your Harbor version to v2.2.0?
