### ISSUE TITLE
registryctl 2.1.2 can't access Azure storage

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#13927]
Hello,

Harbor 2.1.2
Deployed with Helm
Azure Storage v2 as Harbor storage.
Azure Kubernetes (AKS)

I'm facing a weird issue with 2.1.X version. The registryctl can't access Azure storage sometimes:
```
kubectl logs harbor-harbor-registry-848ccb5f74-b9hz2 registryctl
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
time="2021-01-07T11:24:47Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_HTPASSWD"
2021-01-07T11:24:59Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:Put "https://xxxxxx.blob.core.windows.net/xxxx?restype=container": net/http: TLS handshake timeout
2021-01-07T11:24:59Z [FATAL] [/registryctl/main.go:78]: Failed to load configurations with error: Put "https://xxxxxx.blob.core.windows.net/xxxx?restype=container": net/http: TLS handshake timeout
```

I deployed 10 replicas, I don't have this error on all my pod, only some... :/
Sometimes after X restart it works...

No issue with 2.0.5..

Any idea how to fix/debug this ?

**Comment by bitsf** [comment]
maybe this web site also have some rate limitation, like docker hub, that block your api request

**Comment by flbla** [comment]
I don't think there is some limitation, it's an Azure blob storage (it's somehow, like a AWS S3).
I want to use it as backend to store my registry images and Helm charts
as described in the doc : https://github.com/goharbor/harbor-helm/blob/master/README.md
> The type of storage for images and charts: filesystem, azure, gcs, s3, swift or oss. 

I tried to deployed a version 2.0.5 of the registryctl instead of 2.1.X and it's perfectly working. But when I deploy a 2.1.1 or 2.1.2 of the registryctl, I have this weird error.

I tried to switch logs to debug, but it's the same logs lines.

Yes, I tried to do some curl on the K8S node and I don't have any issue, I can contact the Blob storage.

Is there any breaking changes on the registryctl component between 2.0.5 en 2.1.X ?

**Comment by wy65701436** [comment]
the error was raised at here: https://github.com/docker/distribution/blob/master/vendor/github.com/Azure/azure-sdk-for-go/storage/container.go#L289

From the v2.1.*, the registrycl has to create the storage driver instance on launching, maybe we can update it to lazy initialization. But, it's not the root cause of TLS hand shake time, @flbla can you confirm whether the storage are ready to connect when the registry is launching and when the ten instances  are connecting to the same storage at the same time, some of them are timeout?

**Comment by flbla** [comment]
yes, the storage account was ready when I deployed the registry pods
all pods are connected to the same storage account.
and I confirm, some pods are able to connect and some other not :/
is there any way to add more logs? to try to understand why sometimes it's failing?
thank you

**Comment by wy65701436** [comment]
As mentioned, you're using AKS. I'm not sure whether it's the same issue, but you can have a reference. https://github.com/Azure/AKS/issues/14

I think you can find the root cause from the backend storage, maybe do some tuning on your gateway to enlarge the http time out.

**Comment by flbla** [comment]
I saw it too, but unfortunately it's not the same.
do you think it can be a regression in the docker sdk you use?
thanks

**Comment by wy65701436** [comment]
Not sure whether it's a regression, but you can try to build harbor with an newer version to validate it.
https://github.com/goharbor/harbor/blob/master/src/go.mod#L6

**Comment by wy65701436** [comment]
We should consider to upgrade the Azure SDK
