### ISSUE TITLE
regenerate certificate of notary-signer 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#13921]
The certificate of notary-signer in previous versions of Harbor may not have SAN.

We need to make sure this doesn't break upgrade.

**Comment by reasonerjt** [comment]
It seems currently `prepare` generates the certificate without SAN, we should fix this before FC...

**Comment by wy65701436** [comment]
we have to CP the fix to release-1.10 as the version was bumped up to go 15 in 1.10.
