### ISSUE TITLE
OIDC account unauthorized to add labels on images via the API using the CLI secret, but labels on helm charts allowed

### ISSUE THREAD

**Issue by dominykas** [goharbor/harbor#13925]
**Expected behavior and actual behavior:**

When using a CLI secret for an OIDC account, I should either be allowed to add labels on both - docker images and helm charts, or not allowed to add labels on either of them.

At the moment, adding labels on helm charts works, but does not work for docker images.

The same user can add the labels on docker images via the UI.

The admin user can add labels on docker images via the API.

**Versions:**

Please specify the versions of following systems.

- harbor version: 2.0.5

**Comment by reasonerjt** [comment]
Could you provide a concrete example?  like a few `curl` commands?

The CLI secret is used for CLI tools like docker or helm to push/pull artifacts, do you use the CLI secret in basic auth header to call the API

**Comment by dominykas** [comment]
✅ OIDC user, label helm chart:

```
12:36 $ curl --user dominykas:${HARBOR_PASSWORD} -i -H 'Content-Type: application/json' --data-binary '{"id":4}' https://${HARBOR_HOST}/api/v2.0/chartrepo/library/charts/helm-wave/4.5.1/labels
HTTP/1.1 200 OK
Date: Fri, 08 Jan 2021 10:36:33 GMT
Location: /api/v2.0/chartrepo/library/charts/helm-wave/4.5.1/labels/4
Server: nginx/1.19.1
Set-Cookie: sid=3021affe19029deb13b49458673290dc; Path=/; HttpOnly
X-Request-Id: ede49b337eb0fb298afd5b8333dc3e14
Content-Length: 0
Connection: keep-alive
```

❌ OIDC user, label docker image:

```
12:36 $ curl --user dominykas:${HARBOR_PASSWORD} -i -H 'Content-Type: application/json' --data-binary '{"id":4}' https://${HARBOR_HOST}/api/v2.0/projects/library/repositories/wave-services/artifacts/v58.37.4/labels
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Fri, 08 Jan 2021 10:39:02 GMT
Server: nginx/1.19.1
Set-Cookie: sid=d249c1bb8b43ab0c745cf9a89bbb8511; Path=/; HttpOnly
X-Request-Id: dbbee2205aa22fbdbbb754c7a40bdfa7
Content-Length: 62
Connection: keep-alive

{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
```

✅ admin user, label docker image

```
12:39 $ curl --user admin:${HARBOR_PASSWORD} -i -H 'Content-Type: application/json' --data-binary '{"id":4}' https://${HARBOR_HOST}/api/v2.0/projects/library/repositories/wave-services/artifacts/v58.37.4/labels
HTTP/1.1 200 OK
Date: Fri, 08 Jan 2021 10:40:08 GMT
Server: nginx/1.19.1
Set-Cookie: sid=6f4a136a3b23530ec0c1d5a8a9084722; Path=/; HttpOnly
X-Request-Id: 3f9e2cac6e83caf18dbb61f36594764e
Content-Length: 0
Connection: keep-alive
```

**Comment by dominykas** [comment]
> The CLI secret is used for CLI tools like docker or helm to push/pull artifacts, do you use the CLI secret in basic auth header to call the API

Yes, it's in the basic auth header.

Are you implying we shouldn't use the CLI secrets for the API? This leaves us without a way to access the API at all? Robot accounts can't use API, OIDC users can't use API, admin password usage should be avoided as it is too risky?

**Comment by dominykas** [comment]
OK, here's another one for a puzzler:

```
curl -f -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" -X GET https://harbor.cluster01.ops.dev.k8s.mckinseywave-npn.com/api/v2.0/statistics
```

✅ with a robot account (why does it work with a robot account?)
❌ with an OIDC user CLI token

**Comment by dominykas** [comment]
OK, here's another one for a puzzler:

```
curl -f -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" -X GET https://${HARBOR_HOST}/api/v2.0/statistics
```

✅ with a robot account (why does it work with a robot account?)
❌ with an OIDC user CLI token

**Comment by reasonerjt** [comment]
As for the CLI secret it's not for calling the API, It may work for some APIs with the same access level as granted in Harbor,  but not all APIs.

If you have an OIDC user and want to use it to call API, please use the ID token.

```
curl -H "Authorization:Bearer $ID token" $API_URL
```

**Comment by dominykas** [comment]
I don't think that I can acquire the ID token easily in our setup, plus it would expire after 24 hours, so we'd have to set up some sort renewal mechanism or manual intervention, so this kind of defeats using this for automation purposes, but if this is not considered to be a bug, then it is not a bug.

I'm still curious though, how come labelling helm charts works with the CLI token - should it not be prohibited, same as everything else? Is that not a security concern?

**Comment by reasonerjt** [comment]
@dominykas 

Sorry for the late reply.  I think it should be prohibited for consistency, but we are deprecating the support for chart museum and wanna suggest users use the OCI registry to store helm chart, so it's not high priority.

As for security, I don't consider it a problem, b/c by design the CLI token to provide a way for the user to "docker login", so its permission is bound to the user, as long as the token's permission is lower than the user it should be OK.
