### ISSUE TITLE
Unreasonable robot account conventions

### ISSUE THREAD

**Issue by anoncam** [goharbor/harbor#13932]
What can we help you?
What is the justification for including a `$` to separate `robot` from `name of robot`?  It often can require escaping and unnecessary interpreter problems.  Especially when decoding and encoding to base64.  It almost seems intentionally malformed.

**Comment by wy65701436** [comment]
The prefix can be configurated in the coming release, v2.2.

**Comment by stonezdj** [comment]
Fixed in Harbor 2.2
