### ISSUE TITLE
通过oss作为镜像存储，下载镜像没有通过代理，而是直接请求oss

### ISSUE THREAD

**Issue by renhao-0518** [goharbor/harbor#13936]
我使用oss作为了镜像的存储后端，oss是内网地址，当我在本地拉去镜像的时候，他直接请求oss的后端存储，因为本地到oss内网是不通的，导致拉取失败，我的疑问是他应该是通过代理来访问oss，而不是直接去请求oss。
但是当我本地上传镜像时，他成功了，得出的结果是上传走了代理，下载而没有走。
部署方式：kubernetes install 
helm chart version：v1.5.1
harbor version：2.1.1 
![image](https://user-images.githubusercontent.com/52058058/103971675-31fcbc80-51a6-11eb-8eef-cedbf0033579.png)

**Comment by heww** [comment]
Please disable the redirect for the OSS storage in the registry component.

```yaml
# Harbor Storage settings by default is using /data dir on local filesystem
# Uncomment storage_service setting If you want to using external storage
# storage_service:
#   # ca_bundle is the path to the custom root ca certificate, which will be injected into the truststore
#   # of registry's and chart repository's containers.  This is usually needed when the user hosts a internal storage with self signed certificate.
#   ca_bundle:

#   # storage backend, default is filesystem, options include filesystem, azure, gcs, s3, swift and oss
#   # for more info about this configuration please refer https://docs.docker.com/registry/configuration/
#   filesystem:
#     maxthreads: 100
#   # set disable to true when you want to disable registry redirect
#   redirect:
#     disabled: false
```

**Comment by bitsf** [comment]
docker pull时，redirect的url是返回给你的docker client端的，所以我觉得你需要在你本地设置代理。或者按照楼上的方法禁用redirect，这样会通过harbor-core和registry容器进行转发，会走容器中配置的代理

**Comment by renhao-0518** [comment]
关闭redirect后确实可以了，谢谢。
