### ISSUE TITLE
Support other ordering in list project api

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#13940]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I'd like to have other ordering options in list projects. Currently, the ordering is fixed, and frontend has ordering options in table header, but it only sort in the current page, the api sent to backend doesn't have ordering param

![image](https://user-images.githubusercontent.com/16573984/103987079-d55dc980-51c6-11eb-8e48-aae1261fb414.png)

![image](https://user-images.githubusercontent.com/16573984/103987092-dbec4100-51c6-11eb-89bd-8057cb8102e9.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version:  2.1.2
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by AllForNothing** [comment]
@cd1989 We are planning to support specifying sorting filed and sorting method for all list APIs in 2.3
Related Issues #13578 #12277
