### ISSUE TITLE
openldap s_client w/in harbor-core container

### ISSUE THREAD

**Issue by dtkelse** [goharbor/harbor#13949]
harbor-core> echo | openssl s_client -connect <ldap>:636
verify error 19 : using self signed certs (Im not)

harbor-core> echo | openssl s_client -connect <ldap>:636 -CAfile /etc/pki/tls/certs/ca-bundle.crt
verify return code: 0 (ok)

So in the container it works if I specify the ca bundle file. If I dont, how do I determine which file or location
the harbor-core container is trying to use (cause, by default, it doesnt work correctly and my ldaps authentications
are failing)

Thanks

**Comment by stonezdj** [comment]
The default cert store is in the file /etc/pki/tls/certs/ca-bundle.crt,  seems the openssl doesn't pickup the default cert store.
