### ISSUE TITLE
Cryptic/Unclear error message returned when writing an image & harbor is out of space

### ISSUE THREAD

**Issue by sukhil-suresh** [goharbor/harbor#13959]
**Problem:** When using `github.com/google/go-containerregistry v0.1.1` to [write an image](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/remote#Write) to harbor and harbor does not have space, it results in an unclear error message.

Sample error:
> Error: PUT https://harbor-01a.livefire.solutions/v2/library/tanzu-buildpacks_go/manifests/latest: UNKNOWN: unknown error; map[DriverName:filesystem Enclosed:map[Err:28 Op:write Path:/storage/docker/registry/v2/repositories/library/tanzu-buildpacks_go/_manifests/revisions/sha256/ed99e73df43380c86c983e09d97151caf1952e8f423053a6e0a15de526515f4c/link]]

~~(I have reached out to the user for the harbor version information and will update this issue, when available)~~
harbor version: v2.0.2+vmware.1-e91b4ff1

**Expectation:** A more obvious error message indicating that harbor is out of space, would be very helpful

**Comment by AllForNothing** [comment]
@ninjadq Can have a look at this issue as it is not a UI issue

**Comment by sukhil-suresh** [comment]
updated issue text to add harbor version - `v2.0.2+vmware.1-e91b4ff1`
