### ISSUE TITLE
Fail to sign image by notary after upgrading

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#13954]
In upgrade test (from 2.0 or 2.1 to 2.2), sign image test failed with x509 certificate  error.

Jan 10 18:10:26 172.28.0.1 notary-server[6064]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0\"","time":"2021-01-10T18:10:26Z"}

**Comment by reasonerjt** [comment]
same issue with #13921

**Comment by ninjadq** [comment]
dup to #13921

**Comment by MohammadrezaMasoumi** [comment]
same issue here
