### ISSUE TITLE
GC execution taking more time

### ISSUE THREAD

**Issue by kiran009** [goharbor/harbor#13958]
**Harbor Version:** 2.1.0

We have initiated GC to remove untagged artifacts and end up that being running from last 15 hours.
We observe that in jobservice.log it is removing lot of untagged docker artifacts.

Even after trying to restart harbor services also the GC continues to run.

Is it expected in version 2.1.0, we have not seen the same with 1.X versions.

What are the right next steps ?

Jan 11 15:54:34 172.23.0.1 jobservice[34603]: 2021-01-11T10:24:34Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:179]: delete the untagged artifact: ProjectID:(8)-RepositoryName(test/<imgname>)-MediaType:(application/vnd.docker.distribution.manifest.v2+json)-Digest:(sha256:b3455cada3f44e413973a7a3ed9cfc3158b20e3c6e16ad4fd117b8302e153981)

**Comment by wy65701436** [comment]
The execution time of GC depends on how many blob candidates and the storage kind, but the GC is non-blocking mode, it won't block any push/pull, and it must not be cancelled during the execution, as it may cause some uncertain issues.

The jobservice is designed to continue executing the interrupted job if it's in the job queue from first version introduced. So for your scenario, the gc will continue executing.

If you're sure that the GC job is running, please just wait and DO NOT restart jobservice or core service, which may break your data.

**Comment by kiran009** [comment]
Thanks, @wy65701436 for the prompt response.
Also, the blocking GC is failing with an internal server error, how can we resolve the same?

**Comment by wy65701436** [comment]
Which version do you mean on the blocking GC? and what kind of failure in the jobservice log?

**Comment by kiran009** [comment]
@wy65701436 With version 2.1.0, change any gc scheduler settings to weekly gives
"internal server error"

**Comment by wy65701436** [comment]
you can get the details from the jobsevice.log, cc @steven-zou

**Comment by steven-zou** [comment]
@kiran009

When reporting `"internal server error"`, would you check the core.log and jobservice.log to get more context for debugging?

----

After restarting the Harbor services, if the GC job is rescheduled to continue to run, that means the GC job is not completed yet (the GC logic did not exit).

---

For 2.1, maybe you can upgrade to the latest 2.1.x as we also fixed some bugs in resetting schedules.

**Comment by steven-zou** [comment]
@kiran009

When reporting `"internal server error"`, would you check the core.log and jobservice.log to get more context for debugging?

----

After restarting the Harbor services, if the GC job is rescheduled to continue to run, that means the GC job is not completed yet (the GC logic did not exit).

---

For 2.1, maybe you can upgrade to the latest 2.1.x as we also fixed some bugs(https://github.com/goharbor/harbor/issues/13599) in resetting schedules.

**Comment by kiran009** [comment]
@steven-zou No update is seen with core.log, the jobservice.log returned:
Jan 12 15:43:08 172.23.0.1 jobservice[34603]: 2021-01-12T10:13:08Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/149380146ff3d07f186a26b7' error: 404 {"code":10010,"message":"object is not found","details":"149380146ff3d07f186a26b7"}

**Comment by steven-zou** [comment]
@kiran009 

>For 2.1, maybe you can upgrade to the latest 2.1.x as we also fixed some bugs(#13599) in resetting schedules.

Could you upgrade the version to 2.1.2+ as we have introduced fix into the post releases?

**Comment by steven-zou** [comment]
@kiran009 

This issue has been fixed in the 2.2 release and we'll also introduce a fix into the 2.1.5 patch release.

**Comment by steven-zou** [comment]
Can be fixed by pr 

- 1. https://github.com/goharbor/harbor/pull/14601
- 2. https://github.com/goharbor/harbor/pull/14597
