### ISSUE TITLE
Postgresql Permission Denied 

### ISSUE THREAD

**Issue by fshadid96** [goharbor/harbor#13961]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
harbor-db does not start properly due to permission issues after running install.sh  
Jan 11 18:05:07 ip-172-23-0-1.us-gov-west-1.compute.internal postgresql[1667]: initdb: could not access directory "/var/lib/postgresql/data": Permission denied

**Steps to reproduce the problem:**
run install.sh

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.2
- docker engine version: 
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- docker-compose version:  1.19.0, build 9e633ef

**Comment by caoyunshi** [comment]
chown -R polkitd.input ./database ./redis
