### ISSUE TITLE
v2.1.2，仓库管理->新建目标-->测试连接，报错：dial tcp: lookup registry.cn-shanghai.aliyuncs.com on 127.0.0.11:53: read udp 127.0.0.1:42566->127.0.0.11:53: i/o timeout

### ISSUE THREAD

**Issue by caoyunshi** [goharbor/harbor#13964]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
错误信息：
==> core.log <==
Jan 12 10:00:51 30.10.1.1 core[29085]: 2021-01-12T02:00:51Z [ERROR] [/core/api/registry.go:239]: failed to check the health status of registry https://registry.cn-shanghai.aliyuncs.com: generate 'ali-acr' type adapter form factory error: Get "https://registry.cn-shanghai.aliyuncs.com/v2/": dial tcp: lookup registry.cn-shanghai.aliyuncs.com on 127.0.0.11:53: read udp 127.0.0.1:42566->127.0.0.11:53: i/o timeout

==> proxy.log <==
Jan 12 10:00:51 30.10.1.1 proxy[29085]: 30.10.1.1 - "POST /api/v2.0/registries/ping HTTP/1.0" 400 74 "https://harbor.up360.com/harbor/registries" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 12.005 12.005 .

**Steps to reproduce the problem:**
仓库管理，新建目标，Alibaba ACR,
目标URL：https://registry.cn-shanghai.aliyuncs.com

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.2]
- docker engine version: [ 20.10.2]
- docker-compose version: [1.18.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by caoyunshi** [comment]
在宿主机：
能够ping通registry.cn-shanghai.aliyuncs.com;
docker login registry.cn-shanghai.aliyuncs.com也是成功的。

**Comment by stonezdj** [comment]
You need to specify your dns in /etc/docker/daemon.json
```
{
"dns":["<IP address of dns"]
}
```

**Comment by caoyunshi** [comment]
> You need to specify your dns in /etc/docker/daemon.json
> 
> ```
> {
> "dns":["<IP address of dns"]
> }
> ```

The /etc/docker/daemon.json looks like this:
{
    "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn","https://registry.aliyuncs.com","https://hub-mirror.c.163.com"],
    "insecure-registries": ["xxx"],
    "max-concurrent-downloads": 20,
    "live-restore": true,
    "max-concurrent-uploads": 10,
    "debug": false,
    "data-root": "/www/Docker/data",
    "exec-root": "/www/Docker/exec",
    "log-opts": {
      "max-size": "100m",
      "max-file": "5"
    },
    "default-address-pools" : [
         {
             "base" : "xxx.xxx.xxx.xxx/16",
             "size" : 24
         }
    ],
    "dns":["10.0.0.100"],
    "tlsverify": true,
    "tlscacert": "/etc/docker/certs.d/ca.crt",
    "tlscert": "/etc/docker/certs.d/up360.dev.crt",
    "tlskey": "/etc/docker/certs.d/up360.dev.key"
}

However, problems still exist:
==> /var/log/harbor/core.log <==
Jan 13 09:08:05 30.10.1.1 core[28480]: 2021-01-13T01:08:05Z [ERROR] [/core/api/registry.go:239]: failed to check the health status of registry https://registry.cn-shanghai.aliyuncs.com: generate 'ali-acr' type adapter form factory error: Get "https://registry.cn-shanghai.aliyuncs.com/v2/": dial tcp: lookup registry.cn-shanghai.aliyuncs.com on 127.0.0.11:53: read udp 127.0.0.1:45802->127.0.0.11:53: i/o timeout

==> /var/log/harbor/proxy.log <==
Jan 13 09:08:05 30.10.1.1 proxy[28480]: 30.10.1.1 - "POST /api/v2.0/registries/ping HTTP/1.0" 400 74 "https://harbor.up360.com/harbor/registries" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 12.005 12.005 .

**Comment by caoyunshi** [comment]
> You need to specify your dns in /etc/docker/daemon.json
> 
> ```
> {
> "dns":["<IP address of dns"]
> }
> ```

Sstep:
1. add the dns config to daemon.json
2. harbor: docker-compose down
3. systemctl restart docker
4. harbor: docker-compose up -d

**Comment by caoyunshi** [comment]
> You need to specify your dns in /etc/docker/daemon.json
> 
> ```
> {
> "dns":["<IP address of dns"]
> }
> ```

The problem has been solved. Thank you for your guidance. 
The reason for the problem is that my firewall blocks UDP port 5, only opens TCP port 53.
