### ISSUE TITLE
upgrade script is not correct for 2.2

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#13971]
build: v2.2.0-build.284
steps:
1. install a harbor 2.1.3 first
2. prepare upgrade to v2.2.0-build.284, with script
`docker run -it --rm -v /harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/prepare:v2.2.0-build.284 migrate -i /harbor-migration/harbor-cfg/harbor.yml`

many fields are quite different from the harbor.yml.tmpl

**Comment by tobiashochguertel** [comment]
Is there an documentation which describes how to upgrade harbor?
I followed this document: https://goharbor.io/docs/2.0.0/install-config/reconfigure-manage-lifecycle/

and saw in the prepare (shell script) that there is a a container image referenced with a version number (2.1.2) and I just thought me, maybe I have a change the version number to 2.1.3 and rerun the script. It looks like that this changing the version numbers of the used images in the `docker-compose.yml` and maybe that's all but is there a official document which helps me with this upgrade? I mean I just thought that this is maybe the way it could be done, but I'm unsure.
