### ISSUE TITLE
Document minimum and recommended system specs

### ISSUE THREAD

**Issue by akshayl** [goharbor/harbor#1397]
I ran across an issue running Harbor on a VM with 512MB of RAM. We should document minimum and recommended specs around CPU, memory and storage.

**Comment by reasonerjt** [comment]
@hainingzhang @ywk253100 I recall we discussed it, was it documented somewhere?

**Comment by ywk253100** [comment]
The system specs of Harbor appliance is documented [here](https://github.com/vmware/harbor/blob/master/docs/installation_guide_ova.md#prerequisites).

**Comment by akshayl** [comment]
That's for OVA installation, but not here: https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#prerequisites-for-the-target-host

**Comment by asoltesz** [comment]
Both of the links are broken now.

**Comment by Zierhut-IT** [comment]
https://goharbor.io/docs/1.10/install-config/installation-prereqs/
