### ISSUE TITLE
OIDC users with admin role are not shown as "Admin"  

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#13977]
![image](https://user-images.githubusercontent.com/30999793/104412623-9bfed280-55a7-11eb-9cf7-644a1d1d8805.png)

User  "001_user" is OIDC user in admin groups, so it should be regarded as   Administrator

**Comment by reasonerjt** [comment]
It is a limitation introduced when we mark user based on information in external IDP.

The column "Administrator" only reflects the flag in Harbor's DB.

I think all we can do is to add some description in the page or rename the header of the grid.

cc @xaleeks

**Comment by AllForNothing** [comment]
@reasonerjt @xaleeks 
What about hiding the column "Administrator" for both oidc and ladp users,
UI can call systeminfo API to know "auth type"

**Comment by reasonerjt** [comment]
I don't think that's correct b/c currently we allow admin in Harbor to mark a regular user in OIDC/LDAP as admin in Harbor by marking him in Harbor's local DB.

**Comment by xaleeks** [comment]
why not fix it and make it show up as 'yes'?

**Comment by xaleeks** [comment]
we decided on using 'unknown' and I think it should say 'please verify whether the user has admin status through the Identity Provider System'
