### ISSUE TITLE
dry_run for gc does not count all blobs to be deleted

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#13976]
1. prepare an artifacts with two layers, 10MB and 50MB
2. limit the project with quota 50MB
3. push the artifacts, and it is blocked as desired, left one garbage 10MB layer
4. wait 2 hours or adjust the env GC_TIME_WINDOW_HOURS=0 in harbor-core
5. run GC job with `dry_run` option, found no blobs to be deleted
![image](https://user-images.githubusercontent.com/188115/104404891-aebcdb80-5596-11eb-85f0-d8294246b5d0.png)
6. run GC job, found 1 blob to be deleted
![image](https://user-images.githubusercontent.com/188115/104404927-c1cfab80-5596-11eb-8ed9-c783b5ebcb54.png)

`dry_run` GV job is expected to reflect the real operation

**Comment by wy65701436** [comment]
It's a design limiation.

The reference count is calculated by joining table project_blob and blob, which needs the orphans blobs to be removed firstly. But Iin the dry run mode, the orphans blobs will be not actually removed from table project_blob.
