### ISSUE TITLE
The permisson "Create Artifact Label" of robot account is confuse

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#13974]
How about rename it to `Add Label To Artifact`?

**Comment by wy65701436** [comment]
hi @xaleeks , can you help to review the words in the permission list?

**Comment by xaleeks** [comment]
you mean the ability to add harbor labels to artifact?  how about just 'add labels'

**Comment by AllForNothing** [comment]
@ywk253100 @xaleeks  According to the current design,   each permission consists of two parts:   action and resource,

"Create Artifact Label " :    {action:  create,   resource:   artifact-label}

So I suggest not modifying this.
