### ISSUE TITLE
Editing the expiration time of a robot account is confusing.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#13983]
The expiration time is represented as "# of days".

If I edit a robot account, update the expiration to change that number, seems the expiration time is calculated against the creation time.

So if I create a robot account, set the expiration as 3 days, then after 2 days I update the expiration to 4 days.  Does it mean the robot will expire in 2 days instead of 4 days?

This is confusing to users, can we use the date/time widget to edit the expiration time?

**Comment by AllForNothing** [comment]
As discussed, the prompt for "expires_at" will be shown on UI when Editing
