### ISSUE TITLE
unauthorized: unauthorized to access repository

### ISSUE THREAD

**Issue by kiran009** [goharbor/harbor#13988]
What can we help you?
unauthorized: unauthorized to access repository: <harborproject>/<imagename>, action: push: unauthorized to access repository: <harborproject>/<imagename>, action: push

Harbor Version: 2.1.0

**Comment by kiran009** [comment]
Error: 401: could not properly parse response JSON: {"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorized"}]}

**Comment by stonezdj** [comment]
It seems that you push image without project name.
```
docker tag <imageID> <harbor_server>/<project_name>/<repo>:<tag>
docker push <harbor_server>/<project_name>/<repo>:<tag>
```

**Comment by kiran009** [comment]
No, the tag name and projectname are correct

**Comment by vangogh-ken** [comment]
Anyone resolved this issue ?

**Comment by spinus** [comment]
same issue here, so far only for user with space in username (not sure if relevant)

**Comment by spinus** [comment]
@kiran009 @vangogh-ken for me it was the port in docker image name. 
Harbor gives you (in my case) copy-paste command with port and it throws an error. When I tagged without port I was able to push.
Can you guys confirm if that's your case as well?

**Comment by nemethk** [comment]
the same issue...
```
17:35:31  error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "myhost.com/project_name/repo_name:1.0.0-dev-3": UNAUTHORIZED: unauthorized to access repository: project_name/repo_name, action: push: unauthorized to access repository: project_name/repo_name, action: push
```

**Comment by hzliangbin** [comment]
`Error response from daemon: unauthorized: unauthorized to access repository: cloud-native/kube-apiserver, action: pull: unauthorized to access repository: cloud-native/kube-apiserver, action: pull`
same issue ,harbor version 2.0

**Comment by kiran009** [comment]
The issue is intermittent, doesn't come always.

**Comment by Umair841** [comment]
Error response from daemon: unauthorized: unauthorized to access repository: ironbank/f5-networks/nginx-plus-software-adc, action: pull: unauthorized to access repository: ironbank/f5-networks/nginx-plus-software-adc, action: pull

does anyone have a solution for this error?

**Comment by AdinhLux** [comment]
I have the same issue.


Despite having a successful connection test on LDAP, I was encountering issues for adding a group to a private repository.

So I decided to switch to local DB users. 


After having created on + success with docker login, it refuses to pull the image from the repository where this user has access 
👎

**Comment by kabnfever** [comment]
Had the same inexplicable issue, just started happening one day after several months with no issues. Required me to explicitly logout of Harbor registry and then login.

1) docker logout registry.example.com
2) docker login registry.example.com

After this sequence, the "unauthorized to access" went away and pushes began working again.

**Comment by Rtoax** [comment]
check in https://github.com/goharbor/harbor/issues/13115, you must login.

**Comment by anton-petrov** [comment]
Same problem, `docker logout` and then `docker login` doesn't help :(
OS: Linux Ubuntu 22.04, Windows 11 gives the same results

**Comment by jack-09-wong** [comment]
ENV       ：os ：centos7  kernel：4.4.244-1.el7 docker：19.03.13  compose：1.29   harbor： 2.3.5 offline
Question：admin is login OK，but push after report this issue：
unauthorized: unauthorized to access repository: library/busybox, action: push: unauthorized to access repository: library/busybox, action: push

search web   result  ：/etc/docker/daemon.json   add  "insecure-registries":["xxx.xxx.xxx"]
but is not work.

**Comment by janithcooray** [comment]
Please Re-Open

**Comment by xjezzuuuu** [comment]
same issue, any solution?. My context is kubernetes with ingress-nginx, but only pass with large size images.

**Comment by Adamou02** [comment]
Same problem with my CI/CD. In local (with the same Harbor robot account), I don't have any problem (except when I am logout obviously).

**Comment by xjezzuuuu** [comment]
> Same problem with my CI/CD. In local (with the same Harbor robot account), I don't have any problem (except when I am logout obviously).

This problem fix change configuration in portal harbor, change first value (token expiration) for a larger value.

**Comment by Adamou02** [comment]
> This problem fix change configuration in portal harbor, change first value (token expiration) for a larger value.

Not a problem. Actually in -1 (never expire) I change to 365 days : same issue.
My CI/CD log in to my docker harbor registry, then when I `docker push` the `401 Unauthorized`  error occurs.

My harbor bot has permissions to push. When I log in to my docker harbor registry from my laptop (with robot credentials), `docker push` works well...

**Comment by xjezzuuuu** [comment]
> > This problem fix change configuration in portal harbor, change first value (token expiration) for a larger value.
> 
> Not a problem. Actually in -1 (never expire) I change to 365 days : same issue. My CI/CD log in to my docker harbor registry, then when I `docker push` the `401 Unauthorized` error occurs.
> 
> My harbor bot has the rights to push. When I log in to my docker harbor registry from my laptop, `docker push` works well...

did you add your user in project?

**Comment by Adamou02** [comment]
> did you add your user in project?

Actually I'm using Robot accounts, this is not a member of the project

![Image](https://github.com/user-attachments/assets/73e98e1b-dd4a-4ef0-84ff-188b03462539)

**Comment by xjezzuuuu** [comment]
> > did you add your user in project?
> 
> Actually I'm using Robot accounts, this is not a member of the project
> 
> ![Image](https://github.com/user-attachments/assets/73e98e1b-dd4a-4ef0-84ff-188b03462539)

Oh ok, but when edit or create select permissions for a different projects. Verify if your robot account has permissions for the project

**Comment by Adamou02** [comment]
@xjezzuuuu Problem solved, thanks.

We have a `DOCKER_AUTH_CONFIG` variable set at the organization level to log in to the proxy registry.
For some reason, my `docker login` command still uses the username from the `DOCKER_AUTH_CONFIG `variable, even when I specify a different username and password in the `docker-config.json` file or through the `docker login` command for my specific project.

So the issue wasn't related to Harbor — the problem was actually how Docker-in-Docker handles the `DOCKER_AUTH_CONFIG `variable.

**Comment by dameng324** [comment]
I run to this issue too in Windows DockerDesktop envrionment, and solved by:

Uncheck : Setting->General-> Use containerd for pulling and storing images.
