### ISSUE TITLE
Create robot account return internal server error 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#13981]
<img width="864" alt="Screen Shot 2021-01-13 at 10 00 58 AM" src="https://user-images.githubusercontent.com/2696760/104415486-10884000-55ad-11eb-977f-18c99c697615.png">

**Comment by wy65701436** [comment]
`Jan 13 06:58:18 192.168.48.1 core[16729]: 2021-01-13T06:58:18Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: pq: value \"1000000000000000000\" is out of range for type integer"}]} `
