### ISSUE TITLE
it should add a credential to harbor metrics

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#13992]
build: v2.2.0-build.284
Install harbor with metrics enabled
1. uncomment metrics items in harbor.yml
2. set enabled to true

curl http://127.0.0.1:9090/metrics

it should add a basic auth credential with password as harbor_admin_password, or generate a random password, and add to nginx config

**Comment by reasonerjt** [comment]
This is a good point, we don't want anonymous user get the data
