### ISSUE TITLE
Failed scan all job keeps the ongoing flag to "true"

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#14001]
I set up a clair-adapter.

Set the remote adapter as default scanner and triggered scan-all.

B/C the clair container does not trust the certificate of my Harbor instance all scan jobs failed.

The scan button became unclickable, checked the response of `/api/v2.0/scans/all/metrics` is 
```
{
	"completed": 0,
	"metrics": {
		"Error": 6,
		"Pending": 0,
		"Running": 0,
		"Stopped": 0,
		"Success": 0
	},
	"ongoing": true,
	"total": 6,
	"trigger": "Schedule"
}
```
It's the value of "ongoing" makes the button unclickable.

**Comment by stonezdj** [comment]
Same error even install the ca.crt to the trusted certificates of clair-adapter container.

**Comment by heww** [comment]
> Same error even install the ca.crt to the trusted certificates of clair-adapter container.

ca.crt need to be trusted in clair container, I will update the test case.
