### ISSUE TITLE
Garbage Collection does nothing

### ISSUE THREAD

**Issue by asifbacchus** [goharbor/harbor#14020]
First off -- great project!
My only problem: Garbage Collection is not working for me.
Whether I try dry-run or actual GC, the log is *completely* empty (i.e. blank white screen). My job-logs are also empty. It actually seems that literally, nothing is happening.

This is *not* a 2-hour issue, I know there is stuff that has been deleted 2 weeks ago, 1 week ago and more stuff deleted a few days ago.

Where I'm stuck: I have **no idea** where to start looking for logs or what commands I could execute manually to test since I cannot find anything in the documentation. Some issues reported by others here mentioned running various "registry" commands in the registry container or registryctl containers, however, neither of those contains seem to have any command named registry. (They both have 'registry_do_not_use_GC'). Should I be checking different containers?

I'm happy to provide any/all data needed to sort this out I just have very little idea where to start because the documentation is very sparse.

Thanks in advance to anyone that can help.

**Comment by wy65701436** [comment]
it seems that the GC job can not be started in job service, can you provide the jobservice.log as well?

**Comment by asifbacchus** [comment]
I would be super happy to provide logs but, as I stated, there literally are *none*. The logs are either blank or non-existent. This is still happening with the latest update too. Is there a way I can manually trigger a GC via docker exec or something so maybe I can see some stdout/stderr output?

**Comment by wy65701436** [comment]
it's very likely a job service issue cc @steven-zou

**Comment by steven-zou** [comment]
> I would be super happy to provide logs but, as I stated, there literally are _none_. The logs are either blank or non-existent. This is still happening with the latest update too. Is there a way I can manually trigger a GC via docker exec or something so maybe I can see some stdout/stderr output?

Which way did you use to install Harbor? And what's your harbor version?

For docker-compose way, you can find it in /var/logs/harbor/[core, jobservice].log
For helm, maybe directly check the kubectl logs against core and jobservice pod?

**Comment by asifbacchus** [comment]
Sorry about not getting back to this issue for so long. No, it looks like the actual files that take care of garbage collection are somehow missing in the containers themselves... I have no idea. I'm going to eventually do a clean re-install anyways and will open a new issue if this is still a problem at that time.

Thanks.
