### ISSUE TITLE
Harbor API Access-Control-Allow-Origin (CORS)

### ISSUE THREAD

**Issue by joaosamouco** [goharbor/harbor#14029]
Hello everyone.

Currently, I'm trying to send some requests to the Harbor API from a different endpoint (a small webpage that requests some information directly from the browser) but I'm not able to do so thanks to the CORS policy implemented that only allows requests from the harbor endpoint itself.

> Access to fetch at 'https://ENDPOINT_A/api/repositories/repository/tags' from origin 'https://HARBOR_HOSTNAME' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

What I'm looking for is a way to configure or disable cors. Something similar to the configuration available on the [docker/registry](https://github.com/docker-archive/docker-registry/blob/master/ADVANCED.md#cors) service for example.

Is there an easy way to do it with harbor right now?

**Comment by steven-zou** [comment]
@joaosamouco 

So far, we don't support `CORS` from Harbor side, you can try some other ways to introducing a wrapper layer.

**Comment by Goend** [comment]
you need to get the header(X-Harbor-Csrf-Token) from the some no userful api request ,
![image](https://user-images.githubusercontent.com/40394339/105690030-7c1bc700-5f36-11eb-922e-0b4fc550b3c2.png)
