### ISSUE TITLE
请问harbor容器ip地址怎么更改

### ISSUE THREAD

**Issue by sakufo** [goharbor/harbor#1403]
由于barbor的内网ip地址与我的生产环境内网地址冲突，导致无法正常使用。
请问harbor的ip地址在哪里设置

**Comment by yhua123** [comment]
Please post your detail network environment. Thanks~
By default, you can change your host IP address manually and modify harbor.cfg `hostname = new address`. Then run `~/harbor/make# ./prepare` and restart Harbor instance.
If you want to set each container's ip inside Harbor, please follow this reference: https://docs.docker.com/engine/userguide/networking/.

**Comment by sakufo** [comment]
我的生产环境网段是172.18.0.0/16,安装harbor后在安装的非生产环境主机上生成了以下网络：
705: br-1f8277fd8a4f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:a4:1e:13:86 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-1f8277fd8a4f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:a4ff:fe1e:1386/64 scope link 
       valid_lft forever preferred_lft forever

并且harbor的网络地址也是172.18.0.0/16段，导致我的harbor无法与生产环境通信。
请问如何才能修改harbor所使用的网段，避免与生产环境冲突

**Comment by reasonerjt** [comment]
Hi, I think updating bip of docker daemon may fix your issue:
https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by zhuima** [comment]
碰到同样的问题，不知道 @sakufo 解决了没有？

**Comment by sakufo** [comment]
删除docker使用的集团网络，再手动创建一个就可以了。无法指定具体IP地址，但可以更改网段

**Comment by jessehu** [comment]
Hi @sakufo @zhuima, 

We have created two mailing list for better communication with the Harbor community. The harbor-dev one will be used for connection with developers and harbor-users are for end users. We will discuss their use in our next community meeting. You can visit by this link: https://groups.google.com/forum/

harbor-dev@googlegroups.com
harbor-users@googlegroups.com

Harbor’s twitter account @project_harbor is also set up. We will use it as another channel to broadcast news to global users.

**Comment by jessehu** [comment]
If https://groups.google.com/ is not convenient for you, please also join Harbor Slack channel #harbor on [VMware {code}](https://code.vmware.com/join/) to ask questions. Thanks for using Harbor.

**Comment by reasonerjt** [comment]
Closing the issue as it seemed to have various solutions mentioned in this thread already.
