### ISSUE TITLE
Harbor Jobservice Fails on Garbage Collection and Interrogation Services

### ISSUE THREAD

**Issue by luhahn** [goharbor/harbor#14047]
I noticed that the Jobservice is behaving strangely in our cluster.

Initially I am able to setup the Garbage Collector/ Interrogation Service job via API and everything works.
After a few days the Jobservice directory /var/logs/jobs is filled with thousands of logs, up to the point that the Jobservice logs reports, that no space is left on device (which is not true, but it seems that the inode limit is reached).

It is possible to delete the logs by hand, so at least the no space left message is gone. However after the Jobservice failed once, I am not able to recover functionality.
If I try to set the scheduling of the garbage collector job manually I'll receive an internal server error on the ui, followed by this logs on the jobservice pod:

```
2021-01-21T12:09:01Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/78612fc8ac29344b9b743f54' error: 404 {"code":10010,"message":"object is not found","details":"78612fc8ac29344b9b743f54"}
```

It is not possible to set the garbage collector or interrogation service values via API either.

Harbor is running on 
Version: 2.1.3
With Helm Chart Version: 1.5.3

Maybe someone has an idea how to fix this.

**Comment by luhahn** [comment]
I think I know what happened. Somehow the Vulnerability Scan got triggered every second. (Even though it was scheduled dayli)
Since the logging was set to file logging we got a new log file every second, which escalated pretty quickly and eventually reached the inode max limit. 

This broke the file system and the job service.

Workaround seems to be:

1. Set to stdout logging to be safe
2. Set the cron job manually and check the logs if the job gets triggered correctly

The Vulnerability Scan was setup via api call after installing harbor. I still have no clue why the job is triggered every second.

**Comment by steven-zou** [comment]
@luhahn 

It is probably there are some wrong cron settings that are set previously and not successfully deleted (this can be checked via the Redis data under a root key `{harbor_job_service_namespace}`.

For normal case, the file logger has a sweeper that can help clean the log files with a specified duration (by default is 1 day)

**Comment by luhahn** [comment]
Since I can't replicate this Issue anymore I'm going to close it :) Thanks for your response !
