### ISSUE TITLE
Can you use or install Harbor without Docker or Kubernetes

### ISSUE THREAD

**Issue by RobertS6144** [goharbor/harbor#14045]
Can you use or install Harbor without Docker or Kubernetes? So that if they fail Harbor is still available.

**Comment by sluetze** [comment]
no.
If you are looking for High Availability you should use Kubernetes. Distribute the Cluster-Nodes over different Failure-Domains and you should be fine even if one failure-domain has problems.

**Comment by RobertS6144** [comment]
Thanks

**Comment by vaminakov** [comment]
Okay, but if you're no need for High Availability and use it for very small installations?

**Comment by sluetze** [comment]
Then you still need docker or another container-runtime, as harbor is shipped containerized (if this wasnt changed last two years, havent been active here for a while)
