### ISSUE TITLE
failed to upgrade from 2.1 to 2.2 with internal tls enabled

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14062]
build v2.2.0-build.315

steps:
1. install v2.1.3 with internal tls enabled
docker run --rm -v /:/hostfs:z goharbor/prepare:v2.1.3 gencert -p /data/inttls

2. upgrade v2.2.0 
docker run -it --rm -v /:/hostfs goharbor/prepare:v2.2.0-build.315 migrate -i /home/zzm/harbor/harbor.yml

results:
1. jobservice is always restarting
![image](https://user-images.githubusercontent.com/188115/105666889-339fe180-5f15-11eb-90d3-dd2539dd76dd.png)
jobservice failed because failed to connect core as x509 error

2. docker inspect jobservice
![image](https://user-images.githubusercontent.com/188115/105666929-5631fa80-5f15-11eb-9326-88ec31f43e83.png)

3. core.crt is empty
![image](https://user-images.githubusercontent.com/188115/105666966-68ac3400-5f15-11eb-86b3-c0e2ed63eedb.png)

**Comment by bitsf** [comment]
regenerate certs and reinstall can fix
docker run --rm -v /:/hostfs:z goharbor/prepare:v2.2.0-build.315 gencert -p /data/inttls
sudo ./install.sh --with-trivy --with-chartmuseum

**Comment by ninjadq** [comment]
Won't fix because, Certs generated by old version of prepare didn't include SAN. So it has issues when use harbor compiled with go 1.5 +

**Comment by steven-zou** [comment]
Do check and fail earlier
