### ISSUE TITLE
Destroy sessions after changing password, resetting password and disabling user

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#1406]

**Comment by reasonerjt** [comment]
Per a brief search, I didn't see beego's session manager has a func to return a map of sessions, so I don't think we can easily map a session ID to user ID.  

Instead, maybe we can have a thread-safe list for the user IDs, whenever it tries to validate user via session it checks the list, when it sees the user ID it invalidates the current session?

**Comment by ywk253100** [comment]
How about we keep a map by ourselves? When a user login, we put his user ID and session ID into the map. And we destroy all sessions of the user if needed.
There is a function in beego SessionDestroy(w http.ResponseWriter, r *http.Request), maybe we can populate the session ID into the cookie of the request, and call this method to destroy sessions?
