### ISSUE TITLE
Replication to AWS ECR does not create target repository

### ISSUE THREAD

**Issue by harryleesan** [goharbor/harbor#14069]
## Description
I have a project named `tester`, and a repository named `foo`. I have setup replication from Harbor to destination ECR with Source resource filter: `tester/**`. Replication is set up with a blank destination namespace.

Pushing and pulling `tester/foo` from Harbor works. Replication to ECR fails when the repository does not exist in ECR. Replication succeeds when the repository is manually created in ECR.

Harbor version: v2.2.0-42559479.
Kubernetes version: AWS EKS 1.15

## Expected behavior
The repository `foo` does not exist in ECR. Expecting the ECR repository `<account>.dkr.ecr.<region>.amazonaws.com/tester/foo` to be created by Harbor before replication. Replication to succeed after repository is created.

## Actual behavior
The repository is not created in ECR. Replication fails with `failed to do the prepare work for pushing/uploading resources: RepositoryNotFoundException: The repository with name 'tester/foo' does not exist..`. Replication does not even start as the repository does not exist and was not created.

<img width="1489" alt="Screenshot 2021-01-25 at 15 26 36" src="https://user-images.githubusercontent.com/7056279/105675497-e2cac180-5ef1-11eb-8c02-8de5b510c59b.png">

<img width="581" alt="Screenshot 2021-01-25 at 15 27 12" src="https://user-images.githubusercontent.com/7056279/105675521-ea8a6600-5ef1-11eb-9a5b-5f379bc2fa6a.png">

## Steps to reproduce the problem
1. Create a new project. Push an image into it.
2. Create a replication rule to ECR.
3. Do not create the target repository in ECR.
4. Manually trigger replication.
5. Replication fails.

## Additional context

The functionality to create the ECR repository is in `/src/replication/adapter/awsecr/adapter.go`. However, I suspect that the issue is with the `checkRepository` function at `https://github.com/goharbor/harbor/blob/master/src/replication/adapter/awsecr/adapter.go#L246`. An error is thrown which prevents `createRepository` from running.

**Comment by lebenitza** [comment]
Same problem. Harbor is configured with an user having

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ecr:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
So there should not be any permission issues.

**Comment by Lemmons** [comment]
This issue seems to be a regression.  This was working for us with 2.1.3, but now is not working in 2.2.0.

**Comment by lebenitza** [comment]
Seems this issue doesn't get much attention. @Lemmons do you have any idea if a downgrade from 2.2.0 to 2.1.3 is possible?

**Comment by Lemmons** [comment]
It is not.  2.2.0 had significant database changes which make it almost impossible to go back to 2.1.3.

**Comment by bitsf** [comment]
this seems because pr https://github.com/goharbor/harbor/pull/13361, aws API DescribeRepositories() is return err now, not out.Repositories=0

**Comment by P01DHANRAJSG** [comment]
Did any find the solution for this issue?
I am also facing the same issue and finding a way to create the Repository automatically on ECR by using the Harbor, but somehow Hoarbor is unable to create the Repo on ECR.
