### ISSUE TITLE
UI looks weird after upgrade from 2.0.x

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#14070]
After I performed upgrade from v2.0.4 using chart 1.4.4 to latest version.

The elements UI became unaligned:

![image](https://user-images.githubusercontent.com/2390463/105679228-1d038580-5f29-11eb-9cfd-a957da114279.png)

Can we invalidate the cache in the browser automaticly after upgrade?

**Comment by AllForNothing** [comment]
Clear CSS cache can fix this

**Comment by reasonerjt** [comment]
I'm reopening it as although it is challenging, we still see it as a problem.

We may want to figure out a way to invalidate cache only when the version changes.

**Comment by AllForNothing** [comment]
Sure,  will figure out the best practice to fix this

**Comment by AllForNothing** [comment]
Adding buildStamp  query parameter to  "CSS  get request" can surely fix this
