### ISSUE TITLE
Timestamp error in Harbor Logs

### ISSUE THREAD

**Issue by hemantdindi** [goharbor/harbor#14096]
The logs section in the Harbor UI shows wrong date or one day more than actual.  
Harbor version is 2.0.1

![err](https://user-images.githubusercontent.com/9191710/105942338-0c682200-6085-11eb-9159-1d21f3da78eb.jpg)

**Comment by steven-zou** [comment]
What's the timezone of the server. I think the timestamp is the local format of the server time.

cc @AllForNothing

**Comment by AllForNothing** [comment]
@hemantdindi For 2.0.1,  Harbor UI renders the timestamp based on the "en-US" format and your browser time zone.
So if your harbor backend serve and your browser are using different time zone, it may cause this situation
