### ISSUE TITLE
Missing Set-Cookie: sid

### ISSUE THREAD

**Issue by brianmajor** [goharbor/harbor#14091]
Hello,

I have two harbor installations setup with the same OIDC provider.  On installation `harbor-1` OIDC logins work and `harbor-2` they don't.

For the call to /c/oidc/login, installation`harbor-1` is setting the cookie header `Set-Cookie: sid=<value>`, but on installation `harbor-2` this header is not present.  This causes a 'state mismatch' when the OIDC provider returns to harbor, as harbor cannot determine the state from the cookie.

The two installations are identical, except for:
- The hostnames are different
- `harbor-1` is on kubernetes 1.16.  `harbor-2` is on kubernetes 1.18

On harbor-1:
```
curl -v https://harbor-1/c/oidc/login

< Set-Cookie: _gorilla_csrf=MTYxMTY4MzY2NHxJbmcyYVRKNkwyeG1iRXBtUVN0RVNIRXlUUzlpYW5sNU5qUkllakJvTDFCcVpuVjRjSGwwTm5OalZVazlJZ289fCfWp6mFj_izyAA8ytcd9wPC_ZPDJvHaqZBWHa7FZs41; Path=/; Expires=Wed, 27 Jan 2021 05:54:24 GMT; Max-Age=43200; HttpOnly; Secure; SameSite=Strict
< Set-Cookie: __csrf=6WMdb82kcuvZQQeAkEJBTA50Ca5a3s+KdSLeNENA/Rguy6ugNPvmfBm5NmpIjZrDIs7p0q5ZPGkLzrf+neyMWg==; Path=/; Secure; SameSite=Strict
< Set-Cookie: sid=c8f2f7ef75f7091e84793f64d4733d43; Path=/; HttpOnly
< Vary: Cookie
```

On harbor-2:
```
curl -v https://harbor-2/c/oidc/login

< Set-Cookie: _gorilla_csrf=MTYxMTY4MzY3MnxJbU54T1RWcWRGQXJRVEUxUlc1MWRGTlZTVEJvYUV4dFZuZE5VR1pwTnpsSVMyUk9aRWhxVlc5RFVFRTlJZ289fO7DhkFIiccTBzYI_rQS5_A7kivVytizn9hLL74wUQX6; Path=/; Expires=Wed, 27 Jan 2021 05:54:32 GMT; Max-Age=43200; HttpOnly; Secure; SameSite=Strict
< Set-Cookie: __csrf=CYaYlC5ktpz0fgDpjQYZKQjvtT6vUjhKeaHSr4yfYbB7KeEa/Zq1wrDg67vdizitsXp1/XDZhw1Qco+xubdpQA==; Path=/; Secure; SameSite=Strict
< Vary: Cookie
```

What would lead `harbor-2` to not issuing the `sid` cookie?

**Comment by brianmajor** [comment]
I forgot to mention that this is harbor version 2.0.2 installed with the bitnami charts:

```
coreImage:
  registry: docker.io
  repository: bitnami/harbor-core
  tag: 2.0.2-debian-10-r0
  ```

**Comment by reasonerjt** [comment]
1. How do you expose Harbor on these 2 instances?
2. Check the log of harbor-core on the problematic env, there may be issues when creating a session record.

**Comment by brianmajor** [comment]
Many thanks for the response, I'm eager to get this working.

1.  Both instances are exposed directly through the nginx ingress from the bitnami charts.

2.  I have tried clearing the cache and still only see the two cookies in harbor-2.

3.  Here are the relevant lines from the harbor-core logs:

```
2021-02-10T17:07:57Z [DEBUG] [/core/controllers/oidc.go:66]: State dumped to session: mhmhsddqdwehepw3pf78t4yweby5eqyl
```

```
2021-02-10T17:08:09Z [ERROR] [/core/controllers/oidc.go:75]: State mismatch, in session: %!s(<nil>), in url: mhmhsddqdwehepw3pf78t4yweby5eqyl
2021-02-10T17:08:09Z [DEBUG] [/server/error/error.go:58]: {"errors":[{"code":"BAD_REQUEST","message":"State mismatch"}]}
```

**Comment by brianmajor** [comment]
Hi @reasonerjt I have ruled out it being a problem with how harbor is exposed.  From within each core pod on both instances of harbor, I issued a local call to the oidc login endpoint:

```
curl -v http://localhost:8080/c/oidc/login
```

harbor-2 still only sets the two csrf cookies and not the `sid` cookie.  harbor-1 sets all three.  So, something in core on harbor-2 is preventing that Set-Cookie header from being issued for `sid`.

I am at a loss as to how to diagnose this further, other than digging into the harbor OIDC code myself to see what conditions could lead to the sid cookie not being set.

Cheers.

**Comment by brianmajor** [comment]
I see in this issue: https://github.com/goharbor/harbor/issues/12982

that the last user had success by fixing something in the redis container.  Does harbor-core save Session IDs in redis for another process to use?  The redis pod seems to be healthy and working.  If it's used for sessions, is there a way for me to test that it's working properly?

**Comment by brianmajor** [comment]
I also notice that in harbor-1, the header `Server: beegoServer:1.12.1` is present on a GET to /c/oidc/login, but that header is missing in harbor-2.

**Comment by brianmajor** [comment]
Resolved:  there was an unknown mismatch between the chart version and values.yaml, which had the effect of making redis unavailable to the core pod.  It could not parse the redis URL in the environment as the format of that URL changed between chart versions.
