### ISSUE TITLE
Enforcing username on OIDC signup

### ISSUE THREAD

**Issue by outime** [goharbor/harbor#14102]
I was wondering if there'd be a way to enforce certain username when signing up to Harbor through OIDC. It seems to suggest a valid username based on the claim but it'd be great if we could choose to enforce the same name and not letting the end user choose one.

**Comment by Vad1mo** [comment]
There is "**Automatic onboarding**" feature if that is ticked the username will be used from Username Claim 


![image](https://user-images.githubusercontent.com/1492007/106000189-d8095b80-60ae-11eb-87cb-7d27474ce18d.png)

**Comment by outime** [comment]
@Vad1mo I totally missed this - that's great thank you!
