### ISSUE TITLE
Interrogation Services are constantly polled for metadata during scan

### ISSUE THREAD

**Issue by skrech** [goharbor/harbor#14104]
Hello,

I'm implementing a custom interrogation service and noticed a problematic behavior. Once Harbor initiates a scan through POST-ing to `/scan/` endpoint of the scanning service, in addition to the expected polling of the `/scan/{scan_request_id}/report` endpoint, there is a flood of other request coming from Harbor, but targeting the `/metadata/` endpoint. This metadata polling happens every second or so.

**Expected behavior and actual behavior:**
Expected: During scan Harbor should poll only the `/scan/{scan_request_id}/report` endpoint.
Actual: During scan Harbor polls for `/scan/{scan_request_id}/report` there are additional requests happening every second to the `/metadata` endpoint.

**Versions:**
Harbor Version v2.1.1-5f52168e

**Comment by skrech** [comment]
Hello, is there any development on this front?

**Comment by heww** [comment]
Closed by https://github.com/goharbor/harbor/pull/14879

This PR also was cherry-picked to release 2.2.2.

Due to the lack of the cache library, this PR was not cherry-picked to release 2.1.x.
