### ISSUE TITLE
Avoid to use orm transaction in GET request

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#14109]
After Harbor 2.x, almost every request there is an orm transaction, it consumes too many db connection resources, for all GET request, because it is idempotent, there is no need to start a transaction. it could improve the Harbor performance.

**Comment by reasonerjt** [comment]
GET is idempotent for the request but not for the data in DB,  for example a `pull` will write a record audit log and increase the pull number.

I agree too many tx may be problematic, but the issue you saw was a deadlock because some code is NOT reusing connection within the tx, right?

**Comment by stonezdj** [comment]
Correct, there are many database connections hanging with "idle in transaction" for each parallel transaction.
Current transaction middleware have skipped some request, but we should add more.
https://github.com/goharbor/harbor/blob/a773ef358fbe770dcb04b58b6402f932ab26a66a/src/core/middlewares/middlewares.go#L45
