### ISSUE TITLE
Project api returns too slow.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#14111]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

`time curl https://harbor.domain/api/v2.0/projects?page=1&page_size=15 -u username:password`

```
real	0m10.197s
user	0m0.061s
sys	0m0.095s
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.0.1]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by heww** [comment]
How many projects are there in the harbor? 

Is the chartmuseum enabled? How many charts are there in the chartmuseum? Which storage used by the chartmuseum?

**Comment by ggerrit** [comment]
Could this be a duplicate of https://github.com/goharbor/harbor/issues/13327? Moving from Chartmuseum 0.12.0 to 0.13.1 might fix this.

**Comment by heww** [comment]
List projects API is not very slow using the https://github.com/goharbor/perf. In the goharbor/perf we don't prepare any helm charts in the projects, the perf limitation may in the chartmuseum. 

Because the Chartmuseum may be removed in harbor 2.4, so this issue will not be fixed.
