### ISSUE TITLE
executions run history tab not loading automatically

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#14114]
**Expected behavior and actual behavior:**
Execution history should load automatically first time without clicking on refresh buttone

**Steps to reproduce the problem:**
to load executions history in tag retention, need to click refresh tab

**Versions:**
1.10.4

- harbor version: 1.10.4

**Additional context:**

![image](https://user-images.githubusercontent.com/8274052/106115005-46fdb780-6176-11eb-80e6-3f5e13632029.png)

**Comment by arsulesandy** [comment]
any updates on this @AllForNothing ?

**Comment by AllForNothing** [comment]
@arsulesandy Thanks for the info.
This has been fixed in version 2.x.x,  so upgrading your Harbor can  fix this
