### ISSUE TITLE
Scan image sometimes spend too long time.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#14110]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

Under normal circumstances, scan image only need a few seconds, but sometimes it spends too long.

![image](https://user-images.githubusercontent.com/31262637/106088525-17908000-6161-11eb-9d8d-4307402a7360.png)

![image](https://user-images.githubusercontent.com/31262637/106088482-0182bf80-6161-11eb-91a3-fc70221c4079.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.0.1]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

Scan Engine: Trivy

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

After open the debug level log of trivy, there's no related error log print.

**Comment by heww** [comment]
The image scanning is executed in the jobservice, please check whether the jobservice is full (for example, there are lots of replication jobs running in the jobservice) when the scanned image spend a too long time.

**Comment by heww** [comment]
Scan report in the harbor 2.0.x uses the creation time as the scan job start time, so the scan duration may take long time when the job is pending in job service.

From 2.2.x, the scan report uses the start time in the task record which is set when the scan job is executing in jobservice. So this issue was fixed in 2.2.0.
