### ISSUE TITLE
Missing DELETE route for tag retention policy API

### ISSUE THREAD

**Issue by elenz97** [goharbor/harbor#14118]
Hey everyone!

While it is possible to create project-individual **tag retention policies** _once_ via API, I'm missing a way to **delete** them programmatically.

Consider the following:
- A tag retention policy is added to an existing project (`POST api/v2.0/retentions`).
- All rules of the tag retention policy are deleted (`PUT api/v2.0/retentions/{id}`).
    - An empty array of rules like in the below example can be observed for the tag retention policy:
    ```
    {
    "id": 1,
    "algorithm": "or",
    "rules": [],
    "trigger": {
        "kind": "Schedule",
        "settings": {
        "cron": ""
        }
    },
    "scope": {
        "level": "project",
        "ref": 1
    }
    }
    ```

The tag retention policy is now left unused, but still exists - it can still be fetched by its individual ID (`GET api/v2.0/retentions/{id}`).
However, the ID is at this point _only_ contained in the parent project's metadata.

If - eventually - you want to create another tag retention policy for this project, it seems inconvenient to
first fetch the project's metadata to get the tag retention policy's ID (this can be achieved via `GET api/v2.0/projects/{id}/metadatas"`).

---

As a counterpart to the `POST api/v2.0/retentions"`-route, add an API route like `DELETE api/v2.0/retentions/{id}`.

When issuing a request against this new route, all internal references to the tag retention policy should be deleted.
When creating a new tag retention policy for a project, a new object (with a new, individual ID) should be created.

Similar routes already exist for immutabletagrules:
`POST /projects/{project_id}/immutabletagrules`
`GET /projects/{project_id}/immutabletagrules`
`PUT /projects/{project_id}/immutabletagrules/{id}`
`DELETE /projects/{project_id}/immutabletagrules/{id}`

As a side note, moving the retention API in its entirety to `api/v2.0/projects/{project_id}/retentions` also seems to be a more sensible long-term solution (as already suggested here: https://github.com/goharbor/harbor/issues/12019).

Looking forward to any feedback on this!

--- 
Environment used:
Kubernetes `v1.20.2`
via kind `v0.10.0`
running Harbor `v2.1.3-b6de84c5` (Harbor Helm Chart [v1.5.3](https://github.com/goharbor/harbor-helm/releases/tag/v1.5.3))

**Comment by bitsf** [comment]
execution histories are also related to this id, so it is not suggested to delete, so not implement this from UI to backend.
however from the API point of view, this can be added
