### ISSUE TITLE
Evaluating private offline container registry 

### ISSUE THREAD

**Issue by dvyas** [goharbor/harbor#14121]
Hi, 
I am looking for available options for offline container registry. 

I am looking for some +plus points for harbor to evaluate compared to other container registry mainly docker trusted registry and jfrog. My use case is to have a secure container registry with image authentication, RBAC, LDAP/AD support, policy based image replication. 

Any points here will be helpful. Thanks in advance

**Comment by phin1x** [comment]
Hi dvyas,

harbor should meet your requirements. authenticated pulls, rbac, ldap integration, replication is supported and works well (we use those feature in our offline setup).
For more information, visit the official website at https://goharbor.io/.
