### ISSUE TITLE
proxy cache document missing "library"

### ISSUE THREAD

**Issue by jwomack** [goharbor/harbor#14130]
The usages of the proxy with the docker cli is missing library at the end of the command.

On page https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/:

Current:
To start using the proxy cache, configure your docker pull commands or pod manifests to reference the proxy cache project by adding <harbor_servername>/<proxy_project_name>/ as a prefix to the image tag.

Proposed:
To start using the proxy cache, configure your docker pull commands or pod manifests to reference the proxy cache project by adding <harbor_servername>/<proxy_project_name>/library as a prefix to the image tag.

**Comment by stonezdj** [comment]
There is a following paragraph already:

To pull official images or from single level repositories, make sure to include the ‘library’ namespace.
```
 docker pull <harbor_server_name>/library/hello-world:latest
```
