### ISSUE TITLE
Can the Endpoint URL be added to the context-path in The Registries module of The Harbor console?Anyone have idea for the issue?

### ISSUE THREAD

**Issue by 1661788089** [goharbor/harbor#14139]
I have a local harbor and I want to use the synchronization function of the harbor to trigger the image information when I push the image to the harbor.

So here's what I did:

I emulated the Docker-Registry repository locally, creating a Registry project to parse the information that Harbor was synchronized with
In the Harbor Console, the Registrys module configures the IP: port of my Registry service to retrieve the mirrored service.
By tracing service invocations:
1、Harbor first calls my /v2 and returns 401. The header contains the service-token address
2、Then call the server-token address to get the token
3、The header to add Token calls /v2 again, test connection succeeds, push succeeds.

Due to limitations of my local network, specification, etc., I want to add context to the service address configured in Registrys,But when testing the connection, he did not call the server address I returned to him to get token after calling the /v2 interface, and nothing happened, and the connection test failed. Why did this phenomenon occur?

So I would like to ask, can I add the context to the service address in the REGISTRYS module?

我有一个本地harbor，我想通过harbor的同步功能，当push镜像到harbor时，触发获取镜像信息。
所以我这样做：
我本地模拟docker-registry仓库 ，创建了一个registry项目，用来解析harbor同步过来的信息
在harbor控制台，registrys模块，配置我的registry服务的ip：port，是可以获取到镜像服务的，
通过跟踪服务调用 ：1、harbor首先调用我的/v2并返回401，header中含有service-token地址2、接着调用server-token地址获取token，3、header中加入
token再次调用/v2，测试连接成功，push成功
因为我本地网络、规范等限制原因，我想在registrys 中配置的服务地址，加入上下文，但是测试连接的时候，他调用/v2接口之后，不再调用我返给他的server地址获取token，没有任何反应，并测试连接失败，为什么出现这种现象呢？
所以想咨询一下，我可以在registrys模块中的服务地址加入上下文么 ？

**Comment by bitsf** [comment]
I think `external_url` in `harbor.yml` may help, you can specify a context path
