### ISSUE TITLE
Missing default page size for the list replication policy API

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#14141]
When I request the list replication policy API without the page size parameter, the server will return all the policies in the system. 

Please apply a default page size to the API likes other APIs.

![image](https://user-images.githubusercontent.com/5634205/106550929-1a1f1b00-654f-11eb-9b41-b5388cc5e46c.png)

**Comment by ywk253100** [comment]
already fixed as we introduced the default value for page size in the swagger definition
