### ISSUE TITLE
Unable to preheat images with dragonfly - status error

### ISSUE THREAD

**Issue by suojy** [goharbor/harbor#14149]
Installed harbor2.1 and dragonfly1.0.6 on Kubernetes. All pods are fine and able to docker pull images from harbor registry with p2p pattern. The status of P2P preheat provider instances is healthy but the execution failed. 
Any help would be appreciated.

![image](https://user-images.githubusercontent.com/24563192/106709387-66da2300-662f-11eb-8606-9a2f8440be94.png)
![image](https://user-images.githubusercontent.com/24563192/106709750-ec5dd300-662f-11eb-8b03-b303ad835102.png)

logs of core
[ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"{\"code\":10009,\"message\":\"failed to get the job log\",\"details\":\"error for getting log of job 9706845375953b54b871ea38: {\\\"code\\\":10010,\\\"message\\\":\\\"object is not found\\\",\\\"details\\\":\\\"9706845375953b54b871ea38\\\"}\"}"}]} 

logs of jobservice
 [ERROR] [/jobservice/runner/redis.go:111]: Job 'P2P_PREHEAT:65c1739755a5865753effbd4' exit with error: open /var/log/jobs/65c1739755a5865753effbd4.log: permission denied
 [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/9706845375953b54b871ea38/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"error for getting log of job 9706845375953b54b871ea38: {\"code\":10010,\"message\":\"object is not found\",\"details\":\"9706845375953b54b871ea38\"}"}

**Comment by bitsf** [comment]
`docker exec -it harbor-jobservice bash` and check `ls -l /var/log/jobs`, and `touch test` check if can write any file

**Comment by suojy** [comment]
Write change is not allowed. Thanks for your help.
