### ISSUE TITLE
Create Robot Account  Drop Down is to big for smaller screens

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#14143]
I have a full HD 1920x1080 pixel display and on that screen the drop-down isn't fully visible in the new Create Robot Account screen (Harbor 2.2); On top its not possible to scroll down. 

- harbor version: 2.2.0 RC1

![image](https://user-images.githubusercontent.com/1492007/106587979-8ea38b00-654a-11eb-9f3a-ae415da6a6a7.png)

Is there a reason why the permission matrix that existed prior 2.2  was replaced with a drop-down. Usually in permission and access control context, matrix views are the most common method.

I see also addition problems with the drop-down, so if more permissions are added then even bigger screens won't fit in there.

**Comment by AllForNothing** [comment]
@Vad1mo  Thanks for your info.
I have raised a PR to make the drop-down scrollable, this will fix the problem.
Matrix views may be suitable when permissions are very less.
There will be too many cols and rows if  there are many permissions, the matrix views will become too big and complex
