### ISSUE TITLE
Action button still exist after edit window open

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#14161]
When editing the Robert account content the action button should disappear￼

![image](https://user-images.githubusercontent.com/1069785/106841689-8a5ba700-66dd-11eb-8423-8c2e7834503d.png)
![image](https://user-images.githubusercontent.com/1069785/106841671-8596f300-66dd-11eb-986d-91d6bd8f8409.png)

Text alignt on FF
![image](https://user-images.githubusercontent.com/30999793/119609651-84273d00-be2a-11eb-98f6-ed15a997ec78.png)

**Comment by AllForNothing** [comment]
Only appears on FF browser
