### ISSUE TITLE
there're too many 404 in metrics harbor_core_http_request_total

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14160]
build: v2.2.0-rc1
1. install harbor with metrics enable
2. curl http://127.0.0.1:9090/metrics\?comp=core |grep harbor_core_http_request_total
3. we can find there're more then one million records in the metrics just in less one hour, and it increase continuously
![image](https://user-images.githubusercontent.com/188115/106761349-afb1cc00-666f-11eb-85b6-0b0f87eec049.png)
![image](https://user-images.githubusercontent.com/188115/106761926-467e8880-6670-11eb-8086-f12886d49eed.png)

**Comment by bitsf** [comment]
jobservice.log has huge log
![image](https://user-images.githubusercontent.com/188115/106762432-cad10b80-6670-11eb-9260-de79668ba685.png)

this env is upgrade from 2.1.0 to 2.2.0-rc1

**Comment by steven-zou** [comment]
It's a follow-up issue after a broken upgrading process.

**Comment by steven-zou** [comment]
Depends on the env to collect more info about the issue.

**Comment by bitsf** [comment]
can't reproduced after fixed https://github.com/goharbor/harbor/issues/14157
