### ISSUE TITLE
registry metrics return 502 when install with http

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#14175]
1. Install Harbor with http only and enable metrics.
2. Visit:
```
http://<servername>:9090/metrics?comp=registry
```
Return 502 error.

It seems to be a issue related to the following section, these ports should not be hard-code.
https://github.com/goharbor/harbor/blob/f0db1938951950cc922b721557571c5b5a1a3dee/make/photon/prepare/templates/nginx/nginx.http.conf.jinja#L212-L222

**Comment by ninjadq** [comment]
fixed in #14190 #14203
