### ISSUE TITLE
Harbor webhook for uploaded chart considered as artifact push

### ISSUE THREAD

**Issue by ppawiggers** [goharbor/harbor#14177]
**Expected behavior and actual behavior:**
When I create a webhook for "Chart uploaded" I except a webhook when I upload a Helm chart when I push a chart to Harbor:

`helm chart push mychart harbor.mydomain.com/chart:1.0.0`

However, nothing happens. When I enable "Artifact pushed" in the webhook configuration, I does work and I receive a payload like:

```
{
  "type": "PUSH_ARTIFACT",
  ...
}
```

I expected it to work with just "Chart uploaded" enabled and to identify itself as "UPLOAD_CHART".

**Versions:**
- harbor version: 2.1.3

**Comment by wy65701436** [comment]
UPLOAD_CHART is only for helm v2, which pushes charts into the chartmuseum. As regards `PUSH_ARTIFACT` , it's for the OCI artifact format that covers image, cnab bundle, charts and etc.

**Comment by ppawiggers** [comment]
That makes sense, thank you.
