### ISSUE TITLE
Authorization' should start with 'Harbor-Secret'

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#14183]
Hello,

I am trying to upgrade the Harbor from v2.1.2 to v2.1.3.
The upgrade is successful but when I tried to login with docker or UI then i am getting the below error:
"code":10011,"message":"unauthorized","details":"'Authorization' should start with 'Harbor-Secret'" in the jobservice.log.

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 1
Redis VM 3(Master-Slave-Slave)
Harbor Version 2.1.3
Docker version 19.0.0
docker-compose version 1.26

Can you please help me

**Comment by bitsf** [comment]
please try restart nginx container

**Comment by AyushCloud** [comment]
I restarted the Harbor containers and after that the service is fine.
Is there any specific reason of this issue.
I am seeing the issue for the first time during upgrade.
Will this manual operation is mandatory post upgrade ?
