### ISSUE TITLE
confused by two v2.0 APIs 

### ISSUE THREAD

**Issue by MartinEmrich** [goharbor/harbor#14189]
What can we help you?
Hello! 
We just upgraded to Harbor 2.1.3, and I have to adapt a script of mine which uses the API. The old API (e.g. `/api/projects?name=someProject`) apparently no longer works. I found two documents describing the new API, the main README only lists them as "New or Changed" and "Legacy" API.

* https://editor.swagger.io/?url=https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml
* https://editor.swagger.io/?url=https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/legacy_swagger.yaml

Apparently, the non-"legacy" API does not work: I try e.g. `/api/v2.0/projects/someProject`, and I get an HTTP message "project_id in path must be of type int64"

What am I doing wrong? Do I have to "switch over" to the non-legacy API somehow?

Thanks

Martin

**Comment by reasonerjt** [comment]
That change will be released in v2.2, you can try it on v2.2 rc

**Comment by MartinEmrich** [comment]
Thanks... I guess I'll have to stick with 2.1 until 2.2 gets stable....
