### ISSUE TITLE
Helm Charts Visibility Misbehaving when Chart has Pre-Release version 

### ISSUE THREAD

**Issue by anshul-sehgal22** [goharbor/harbor#14188]
Issue:
When pushing charts with [Pre-Release](https://semver.org/#spec-item-9) version, not able to see charts with "helm search repo myrepo"

Pushing chart using  (helm push --username=myuser --password=mypassword redis-**0.1.0-1**.tgz myrepo)

Also, when deleting those charts from UI, charts name remain in list but in fact it got deleted. If we try to download it, we get 404 OK error.
![image](https://user-images.githubusercontent.com/54599278/107041689-d34b5280-67e6-11eb-9487-9a65ae578778.png)

While charts with format MAJOR.MINOR.PATCH version (example 0.1.0) works fine.
Pushing chart using (helm push --username=myuser --password=mypassword redis-**0.1.0**.tgz myrepo)

This is tested over demo harbor server(https://demo.goharbor.io/).
Version v2.1.0-a3eca103

**Comment by ioannissavvaidis** [comment]
We are facing the same issue, using Harbor `2.1.3`.

For charts with naming scheme `<chart-name>:X.X.X` or `<chart-name>:vX.X.X` , everything works as expected.
But, in pipelines, we need to push and install charts with naming scheme as `<chart-name>:X.X.X-dev` and with these kind of charts, we have exactly the described behaviour.

Any update on this ?

**Comment by siavashs** [comment]
Helm follows SemVer 2 standard so Harbor should do the same: https://helm.sh/docs/topics/charts/#charts-and-versioning
