### ISSUE TITLE
Feature Request Search Feature in Project Quota

### ISSUE THREAD

**Issue by mohit94614** [goharbor/harbor#14194]
Please Introduce Search Feature in Project Quota under the Administration section 
this would be helpful when we have a huge no of projects.

Something similar to what we have on the projects page 
https://harborhost.com/harbor/project-quotas
![image](https://user-images.githubusercontent.com/17672906/107111069-f0c5fe00-6872-11eb-9e29-abacb8c84c0c.png)

**Comment by xaleeks** [comment]
that sounds reasonable  

@AllForNothing  can you take care of this in 2.3?

**Comment by AllForNothing** [comment]
@xaleeks  Now, we can search quota by project name (exact match)in v2.3, for fuzzy matching,  may be supported in the future
