### ISSUE TITLE
All the issues reported by the CodeQL should be resolved

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#14205]
Issue query: https://github.com/goharbor/harbor/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+severity%3Aerror

**Comment by reasonerjt** [comment]
https://github.com/goharbor/harbor/security/code-scanning/12?query=ref%3Arefs%2Fheads%2Fmaster
This one is confusing, some of the links under this item redirect me to UI code.

We may consider skip this one for v2.2
