### ISSUE TITLE
Harbor doesn't replicate images that start with '-' in tag name

### ISSUE THREAD

**Issue by uniit** [goharbor/harbor#14207]
**Actual behavior:**
Harbor doesn't replicate images that start with '-' in tag name from ECR to local storage.

**Expected behavior:**
Harbor replicates images that start with '-' in tag name from ECR to local storage.

**Steps to reproduce the problem:**
1. Push artifact '-0.2.0' to an ECR.
2. Create and trigger a replication job.
3. Check the logs.

**Versions:**
- harbor version: 2.2.0-rc1
- EKS 1.18

**Additional context:**

I used the latest helm chart, EKS and s3 storage (not sure that this is important).
Errors from the logs:
``2021-02-08T06:05:28Z [ERROR] [/replication/transfer/image/transfer.go:357]: failed to push manifest of artifact repo/service:-0.2.0: http status code: 400, body: {"errors":[{"code":"BAD_REQUEST","message":"project name required"}]}``
``2021-02-08T06:05:28Z [ERROR] [/replication/transfer/image/transfer.go:176]: http status code: 400, body: {"errors":[{"code":"BAD_REQUEST","message":"project name required"}]}``

**Comment by bitsf** [comment]
This seems some limitation of AWS

**Comment by bitsf** [comment]
tag with prefix `-` is even not supported by docker tag
