### ISSUE TITLE
[Feature Request] Harbor infographics for Admins

### ISSUE THREAD

**Issue by govindkailas** [goharbor/harbor#14223]
It would be really nice to have an infographic on **whats the total pulls/push for a week/month/year.** 

This feature can be added to the admin a/c alone so that they can get an idea about the usage in terms of push and pull. With the possible option to export the infographics as PDF/JPG

It would be better if you can add some figures like,
1. what're the most popular images that are pulled.
2. Mostly used project in terms of the number of images and quota. 
3. Projects that are about to exceed the quota

**Comment by phin1x** [comment]
Maybe the new metrics coming in 2.2 fits your needs. There is a "artifact_pulled" Metric, which look promising, but i didn't see a "artifact_pushed" metric or something like that. You could configure a grafana dashboard with your prefered kpi's.

**Comment by yanji09** [comment]
Please use v2.2 new feature metrics. It may satisfy your requirements.
