### ISSUE TITLE
Unable to sign images with Harbor Notary

### ISSUE THREAD

**Issue by ashishmiyapuram** [goharbor/harbor#14232]
Hi,
I am running harbor on kubeadm. All pods are up and able to push images in to repository but facing issue while trying to sign images using notary.
$ docker login core.harbor.domain
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
$ export DOCKER_CONTENT_TRUST=1
$ export DOCKER_CONTENT_TRUST_SERVER=https://10.111.125.189:4443
$ cp ca.crt /etc/docker/certs.d/10.111.125.189
$ cp ca.crt $HOME/.docker/tls/10.111.125.189:4443/ca.crt
$ sudo docker tag busybox core.harbor.domain/ashish/busybox:0
$ sudo docker push core.harbor.domain/ashish/busybox:0
The push refers to repository [core.harbor.domain/ashish/busybox]
6b245f040973: Layer already exists 
0: digest: sha256:56853b711255f4a0bc7c44d2158167f03f64ef75a22a0249a9fae4703ec10f61 size: 527

expected the my image to be signed but still unsigned. So tried again differently by generating key as below

$ docker login core.harbor.domain
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
$ cp ca.crt /etc/docker/certs.d/10.111.125.189
$ cp ca.crt $HOME/.docker/tls/10.111.125.189:4443/ca.crt
$ sudo docker trust key generate key
Generating key for key...
Enter passphrase for new key key with ID 9bb929f: 
Repeat passphrase for new key key with ID 9bb929f: 
Successfully generated and loaded private key. Corresponding public key available: /home/user/key.pub
$ export DOCKER_CONTENT_TRUST=0
$ sudo docker tag busybox core.harbor.domain/ashish/busybox:unsigned
$ export DOCKER_CONTENT_TRUST=1
$ export DOCKER_CONTENT_TRUST_SERVER=https://10.111.125.189:4443
$ sudo docker trust signer add key core.harbor.domain/ashish --key key.pub
Adding signer "key" to core.harbor.domain/ashish...
Error: error contacting notary server: x509: certificate signed by unknown authority

Failed to add signer to: core.harbor.domain/ashish
 why I am getting this certificate issue though I have provided respective certs? Help me with this.

**Comment by bitsf** [comment]
I think the cert in folder `$HOME/.docker/tls/10.111.125.189:4443` is still not matching https://10.111.125.189:4443, you can check with openssl cmd
openssl s_client -connect 10.111.125.189:4443 -showcerts -servername 10.111.125.189
openssl x509 -text -noout -in ca.crt

**Comment by ashishmiyapuram** [comment]
> I think the cert in folder `$HOME/.docker/tls/10.111.125.189:4443` is still not matching https://10.111.125.189:4443, you can check with openssl cmd
> openssl s_client -connect 10.111.125.189:4443 -showcerts -servername 10.111.125.189
> openssl x509 -text -noout -in ca.crt

Hello, Thanks for the response. This is what I have observed after executing following commands respectively.
~~~
(a)
CONNECTED(00000003)
140443325138240:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 305 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
~~~
~~~
(b)
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            29:80:87:ed:7d:41:a5:16:69:b5:87:75:e1:2e:e1:2d
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = harbor-notary-ca
        Validity
            Not Before: Feb 27 02:28:30 2021 GMT
            Not After : Feb 27 02:28:30 2022 GMT
        Subject: CN = harbor-notary-ca
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:df:67:de:05:a0:f4:6a:2d:1f:f3:bf:17:e8:7b:
                    19:48:ae:ca:8f:4c:c2:51:ad:03:fc:11:8c:35:26:
                    b4:61:d5:f7:20:4e:f6:ee:05:9a:af:d7:00:d9:62:
                    62:f8:02:15:c3:8c:f9:2b:fb:41:85:42:8b:b0:54:
                    09:bf:18:17:be:9c:5b:ed:09:59:3e:45:7d:61:a8:
                    21:4a:df:ec:0c:13:24:aa:8e:29:3b:87:e0:1c:c9:
                    bf:33:4d:18:ad:c3:ec:e7:dd:d4:70:29:7e:30:ee:
                    4c:60:83:ea:e6:e5:64:de:c7:9b:d3:b1:89:1f:a3:
                    79:e3:1e:74:00:da:7c:51:c6:60:4b:18:a5:a0:2d:
                    b0:46:99:90:3a:f3:d3:17:e0:a0:2f:21:03:c5:6c:
                    9d:ea:b1:74:44:0b:79:8d:27:07:7d:90:fa:52:45:
                    3a:5a:b3:09:ad:96:1e:23:63:f3:90:f2:90:1f:10:
                    cb:e4:3d:51:36:5d:1d:a7:3c:ba:0d:15:1d:a4:d7:
                    7f:06:7d:8b:54:ce:fd:05:b6:2f:2a:13:cc:45:af:
                    d2:fd:2d:a5:c3:20:ec:75:fb:c0:42:d8:53:08:4e:
                    40:e3:47:a6:bd:1b:1c:c6:cf:a2:99:96:dc:01:a1:
                    ce:2e:5d:43:9d:26:53:8f:e5:31:63:46:f5:d3:ab:
                    a2:03
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                58:A4:8B:DB:CB:6B:0B:44:32:37:A4:F3:7D:5B:99:58:B6:70:30:58
    Signature Algorithm: sha256WithRSAEncryption
         51:7a:49:74:b1:72:b2:0d:9d:b1:d1:2d:84:e7:17:8e:0e:e4:
         8e:84:9e:55:6d:ea:e1:e0:3f:2f:f6:48:32:f1:a7:54:20:d1:
         35:bb:72:c3:1d:db:a3:aa:68:c5:0f:a2:44:ce:e0:b1:15:5b:
         39:e8:c7:ad:58:8d:f1:36:79:5e:b7:49:57:80:52:b6:08:cb:
         6e:b9:23:0b:5a:1f:37:62:b4:01:c6:17:1a:30:09:84:68:ae:
         95:7c:39:d8:6b:21:19:5e:f5:f0:3f:22:d0:7f:5e:70:cc:58:
         6f:23:95:a5:c4:68:43:fe:3d:80:09:c3:b8:17:b7:4b:52:3f:
         99:8e:ae:14:99:cb:46:4a:a8:47:7d:cd:ca:3a:15:e0:57:24:
         39:cf:96:fc:b3:38:90:8f:07:dd:8f:cb:28:93:1f:45:08:2f:
         a6:2b:a3:c8:cd:90:3f:79:71:36:7f:08:92:9a:bb:90:ef:04:
         54:16:b9:e3:7f:59:7f:c6:55:51:b7:62:90:98:5e:54:54:38:
         f5:0d:bf:98:0d:84:02:fa:f6:fa:09:21:fa:c1:91:b0:0a:b1:
         ee:32:c1:70:72:3d:07:3e:90:f4:c4:f2:23:8c:6e:1c:bb:68:
         fb:2e:11:2b:ca:d4:c2:63:fc:9e:0b:d0:79:cc:7d:ce:76:38:
         f2:c9:f4:42
~~~

**Comment by reasonerjt** [comment]
@ashishmiyapuram 
b/c you use `sudo` in ` sudo docker trust signer add key core.harbor.domain/ashish --key key.pub`
The $HOME changes in the context.

**Comment by ashishmiyapuram** [comment]
Thanks @reasonerjt , the issue is resolved now.
