### ISSUE TITLE
Harbor 2.1 supports installation on Redhat Linux 7.1 VM

### ISSUE THREAD

**Issue by shahidv3** [goharbor/harbor#14239]
Hi there 👋

Does harbor 2.1 supports installation on RHEL VM

please clarify

I don’t see any documentation about installation on RHEL 7.

Thanks,sahid

**Comment by phin1x** [comment]
Harbor is deployed with containers (docker-compose), so the host operating system is not important. it just needs to support Docker or something similar.

**Comment by shahidv3** [comment]
Thanks @phin1x 
Is Docker officially supported on RHEL?
I read somewhere that docker-ce not supported on RHEL

**Comment by phin1x** [comment]
As far as i know rhel 7 and newer comes with podman, a replacement for docker. Here is some examples how to use docker-compose with podman:
https://www.redhat.com/sysadmin/compose-podman-pods
https://www.redhat.com/sysadmin/podman-docker-compose

Or you can install the centos packages, they should work as well.

**Comment by shahidv3** [comment]
thanks @phin1x . I can install docker-compose & harbor on RHEL successfully.
closing this ticket
