### ISSUE TITLE
Project name removal when publishing to ECR

### ISSUE THREAD

**Issue by uniit** [goharbor/harbor#14237]
**Is your feature request related to a problem? Please describe.**
One of the important use cases for me is pulling images from external dev ECR to the current prod one based on some schedule.
However, there is no way to replicate the same repository structure between ECRs. The replication controller always adds a project name prefix.

Example:
Account A ECR:
- repository_A
- repository_B
- repository_C

Account B ECR after replication:
- project_name/repository_A
- project_name/repository_B
- project_name/repository_C

**Describe the solution you'd like**

I expect to have a check box to disable adding the harbor project name during the replication in case the destination is ECR or enhanced 'Destination namespace' filed with regexp that allows doing the same.

**Comment by bitsf** [comment]
it has to have a project namespace in harbor, not allow no project, as there's no default namespace `library` as dockerhub
