### ISSUE TITLE
harbor-migrator error when upgrading from 1.5 to 1.6.3

### ISSUE THREAD

**Issue by danmar-s24** [goharbor/harbor#14235]
I have a 1.5.0 installation on a ubuntu 18.04 host with docker 18.09 and would like to update to 1.6.3. For the upgrade I have found the guide https://github.com/goharbor/harbor/blob/release-1.6.0/docs/migration_guide.md

When I perform the step

`docker run -it --rm -e DB_USR=*** -e DB_PWD=**** -v /var/S24_Harbor/data/database:/var/lib/mysql -v /var/S24_Harbor/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg  goharbor/harbor-migrator:v1.6.3 up`

i get the error:

/harbor-migration/db/util/mysql_pgsql_1_5_0.sh: line 24:   110 Killed                  python /harbor-migration/db/util/mysql_pgsql_data_converter.py /harbor-migration/db/schema/registry.mysql /harbor-migration/db/schema/registry_insert_data.pgsql

anyone had the problem and how to solve it?

**Comment by yanji09** [comment]
v1.6.x is currently not maintained by maintainers.

**Comment by danmar-s24** [comment]
I was able to solve the problem. The error with the harbor migration was displayed because the VM had too less RAM. After I increased the RAM from 4 to 16GB, I was able to upgrade with harbor-migrator.
