### ISSUE TITLE
 {"errors":[{"code":"UNKNOWN","message":"unknown: READONLY You can't write against a read only replica."}]}

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#14238]
Hello,

I have configured the Harbor in HA mode with the below configurations

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 1
Redis VM 3(Master-Slave-Slave)
Harbor Version 2.1.3
Docker version 19.0.0
docker-compose version 1.26

But when I restart the harbor-containers, I am getting the issue of write access denied on the Redis VM and unable to push any images to Harbor.
When I do a Redis failover(stop and start redis) on MasterVM then everything is fine.

haproxy.cfg
global
    daemon
    log stdout format raw daemon debug
    maxconn 4096
	
defaults
    log     global
    mode    tcp
    option  tcplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

resolvers redisdns
    parse-resolv-conf
    hold valid           10s
	
frontend haproxy_rserve
    bind *:6379
    mode tcp
    option tcplog
    default_backend bk_redis

backend bk_redis
    mode tcp
    option tcplog
    option tcp-check
    tcp-check connect
    tcp-check send AUTH\ password\r\n
    tcp-check expect string +OK
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send info\ replication\r\n
    tcp-check expect string role:master
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    #server Redis_0_6379 %REDIS_0%:6379 maxconn 1024 check resolvers redisdns inter 1s
    #server Redis_1_6379 %REDIS_1%:6379 maxconn 1024 check resolvers redisdns inter 1s
    #server Redis_2_6379 %REDIS_2%:6379 maxconn 1024 check resolvers redisdns inter 1s
	
Please let me know if you need any more information.

**Comment by bitsf** [comment]
you can use redis sentinel mode which will auto determine the master redis node

**Comment by AyushCloud** [comment]
Yes, now i am using the redis-sentinel. It resolves the issue
