### ISSUE TITLE
Proxy project not available for gitlab-registry

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#14234]
Testing Harbor v2.2.0-dev i was expecting to be able to do a proxy project for a remote self hosted gitlab instance, which is not possible. Is this expected?

![image](https://user-images.githubusercontent.com/5084445/107545238-5c89cd00-6bcb-11eb-96a4-5802ca660a94.png)

I saw an issue somewhere to fix this a while ago for the v2.2.0 release but i cant find it, and it is not in https://github.com/goharbor/harbor/issues?q=is%3Aissue+is%3Aopen+label%3Atarget%2F2.2.0

**Comment by ChristianCiach** [comment]
Did you create an endpoint at `Adminsitration -> Registries` before?

**Comment by phin1x** [comment]
It seems that Gitlab ist not supported for proxy projects. I tried it with registry type "gitlab" and "registry" and non of them showed up in the dropdown.
When i look into the docs only harbor, docker hub, quay, ecr, acr and gcr are supported: https://github.com/goharbor/website/blob/master/docs/administration/configure-proxy-cache/_index.md

**Comment by dioguerra** [comment]
> Did you create an endpoint at `Administration -> Registries` before?

Yes i did. Exactly as @phin1x

**Comment by xaleeks** [comment]
@stonezdj  can you look into supportability here?  Gitlab registry is seeing more usage as a public repo now because of the dockerhub rate limiting.

**Comment by crileroro** [comment]
@dioguerra As a workaround, you may try to create an _endpoint (Registry)_ with Provider type _Harbor_. I tried this way using a self managed Gitlab instance and it worked (Harbor v2.2.0). I am able to cache image from Gitlab.

**Comment by stonezdj** [comment]
@dioguerra You could consider it as a Docker Registry type when creating registry.
