### ISSUE TITLE
Uploading Helm chart using API

### ISSUE THREAD

**Issue by filwie** [goharbor/harbor#14249]
I am looking for a way to upload Helm chart to Harbor using API request directly.
I cannot seem to find a documented way or matching endpoint in api explorer. 
When I use web api to upload a request is made to `/api/chartrepo/library/charts` but I cannot work out how to replicate this request - I either get 401 or 502 when I try request with basic auth.

I've tried below approach:

```sh
 curl -k -X POST "https://192.168.121.22/api/chartrepo/library/charts" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46Wk1QYXhRY3VURQ==" -H  "Content-Type: multipart/form-data" -d ~/fek/harbor-1.4.1.tgz
 ```
 
but I am getting below 502 error:

```txt
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```

Is there a way to upload chart using API?

**Comment by filwie** [comment]
It works when using `multipart/form-data`:

```sh
curl -k -X POST "https://192.168.121.22/api/chartrepo/library/charts" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46Wk1QYXhRY3VURQ==" -H  "Content-Type: multipart/form-data" -d ~/fek/harbor-1.4.1.tgz
```

as suggested on Slack. I cannot seem to find related docs though.

**Comment by quanbisen** [comment]
hello, I also meet this problem. How do you resolve it? I follow your command return `{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}`. Here is my command `curl -u admin:Harbor12345 -k -X POST "https://172.16.11.198/api/chartrepo/library/charts" -H "accept: app
lication/json" -H  "Content-Type: multipart/form-data" -d '@./chart-test-0.1.3.tgz'`

**Comment by bo-er** [comment]
> It works when using `multipart/form-data`:
> 
> ```shell
> curl -k -X POST "https://192.168.121.22/api/chartrepo/library/charts" -H  "accept: application/json" -H  "authorization: Basic YWRtaW46Wk1QYXhRY3VURQ==" -H  "Content-Type: multipart/form-data" -d ~/fek/harbor-1.4.1.tgz
> ```
> 
> as suggested on Slack. I cannot seem to find related docs though.

Your solution is not working and I wish this issue permanently removed for being misleading.

**Comment by bo-er** [comment]
To those who has problem with this:
`
curl -k -u "{username}:{password}" -X POST "https://{domain here}/api/chartrepo/{repoName}/charts"  -H "Content-Type: multipart/form-data"  -F "chart=@{filename}.tgz;type=application/x-compressed-tar"   -H "accept: application/json" 
`

**Comment by parveshmourya** [comment]
> To those who has problem with the above broken command, try this: `curl -k -u "{username}:{password}" -X POST "https://{domain here}/api/chartrepo/{repoName}/charts" -H "Content-Type: multipart/form-data" -F "chart=@{filename}.tgz;type=application/x-compressed-tar" -H "accept: application/json" `

works for me
