### ISSUE TITLE
Add AWS public and Chinese ECR endpoints

### ISSUE THREAD

**Issue by folimy** [goharbor/harbor#14248]
What can we help you?
https://docs.aws.amazon.com/general/latest/gr/ecr-public.html
harbor/registries add AWS Public ECR endpoint.

**Comment by bitsf** [comment]
I'm not sure if this change is required, it seems no impact now.

but some China endpoints can not be used, https://docs.amazonaws.cn/en_us/general/latest/gr/cnnorth_region.html
