### ISSUE TITLE
Replication not syncing tags with pull-through proxy

### ISSUE THREAD

**Issue by gwkunze** [goharbor/harbor#14245]
**Expected behavior and actual behavior:**
I expect my replication to ECR to replicate all images pulled through my dockerhub pull-through proxy. But occassionally it didn't work. Looking at the replication logs I saw the docker image WAS replicated but without the appropriate tag, i.e. the image showed up in AWS ECR without any tags but with the correct digest.

**Steps to reproduce the problem:**
Seems to happen randomly, which is why I suspect some kind of race-condition, i.e. the replication starts off before the tag is applied to the image.

**Versions:**
- harbor version: 2.1.3

**Additional context:**

[harbor-replication.log](https://github.com/goharbor/harbor/files/5990528/harbor-replication.log)

**Comment by bitsf** [comment]
it seems the tags are not ready when you replication, the list tags Api did not get tags. Not sure if this is relative with your process, that you seems add a proxy cache in the middle ?
But for this problem, it should replicate all tags successfully if you run job again

**Comment by gwkunze** [comment]
@bitsf this is an "event based" trigger, so I guess it is harbor that's triggering the replication process too soon?

**Comment by ravens** [comment]
Observing the same "intermittent" failure on an harbor installation with the docker pull cache toward some docker registry with S3 storage. Sometime only the layers are available, but the tags are missing.
