### ISSUE TITLE
[Question]: Does Harbor delete data from s3 storage?

### ISSUE THREAD

**Issue by Atharex** [goharbor/harbor#14241]
I have Harbor configured with the s3 backend as a local Minio storage backend on kubernetes.

When I run Harbor GC or simply delete existing images, they are deleted successfully from Harbor, but the underlying data is still persisted in MinIO.

Is this behaviour correct & intended or is Harbor supposed to also delete data inside MinIO, when it deletes it in Harbor?

**Comment by phin1x** [comment]
Harbor will delete blobs if they are not referenced by a image. At the latest with a gc run they should be deleted. If they still persist, the blob is referenced by a another image and can't be deleted.

**Comment by heww** [comment]
The data in the storage will be deleted in the GC job.
