### ISSUE TITLE
run retention rule failed with special pattern

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14259]
When add 2 repositories with
`distribution-portal/administration-distribution-portal,distribution-portal/client-distribution-portal`,
it fails the Dry Run with an Internal server error.
`Feb 12 11:21:19 172.22.9.1 core[1153]: 2021-02-12T10:21:19Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"launcher: syntax error in pattern"}]}`
![image](https://user-images.githubusercontent.com/188115/108390472-addd3080-724b-11eb-92c0-1fb17ace06f6.png)

If create a rule with just a single repository either using portal/administration-distribution-portal or distribution-portal/client-distribution-portal then the Dry run is successful.

**Comment by bitsf** [comment]
The problem is because the dependency golang library `github.com/bmatcuk/doublestar` is splitting string by '/' first, then splitting ','
That means it can support pattern `AA/{a,b}`, but not `{AA/a,AA/b}`
And the braces is auto added from UI code when find a comma, so even use pattern `AA/{a,b}`, it will be converted to `{AA/{a,b}}` which is also bad syntax

**Comment by bitsf** [comment]
@AllForNothing we may remove the logic that auto add braces from UI code, and check if user doesn't add braces when having comma

**Comment by xaleeks** [comment]
can we make sure to have this fixed in a 2.2 patch release? @bitsf  @AllForNothing

**Comment by AllForNothing** [comment]
Sure, this UI Fix can be cherry-picked to the 2.2 branch
