### ISSUE TITLE
Manual migrate images from harbor 1.53 to harbor 2.0

### ISSUE THREAD

**Issue by cjenlet** [goharbor/harbor#14253]
#!/bin/bash

source_registry=harbor1.53.test.com
target_registry=harbor2.0.test.com
source_auth='YWRta*********************EkMA=='
target_auth='YWRta***********************hbzA='

source_projects_file=harbor.json
target_projects_file=harbor2.json
temp_file=temp.json
curl -X GET -H "Content-Type: application/json" -H  "authorization: Basic $source_auth" "https://$source_registry/api/projects?" 2>/dev/null > $source_projects_file
curl -X GET -H "Content-Type: application/json" -H  "authorization: Basic $target_auth" "https://$target_registry/api/v2.0/projects?" 2>/dev/null > $target_projects_file
source_projects=($(cat $source_projects_file|jq -r .[].name))
target_projects=($(cat $target_projects_file|jq -r .[].name))

temp_projects=($(echo ${source_projects[@]} ${target_projects[@]}|sed 's/ /\n/g'|sort | uniq -u))
will_create_projects=($(echo ${source_projects[@]} ${temp_projects[@]}|sed 's/ /\n/g'|sort | uniq -d))
#echo ${will_create_projects[@]}

### 调用用法 : Create_project
Create_project()
{
	for p in ${will_create_projects[@]}
	do
		echo "create project $p"
        	curl -X POST -H "Content-Type: application/json" "https://$target_registry/api/v2.0/projects" -H  "authorization: Basic $target_auth" -d @split/${p}.json
	done
}

### 调用用法 : init_projects_file
init_projects_file()
{
	rm -f $temp_file
        cp $source_projects_file $temp_file
        sed -i '/creation_time/d' $temp_file
        sed -i '/update_time/d' $temp_file
        sed -i '/project_id/d' $temp_file
        sed -i '/owner_id/d' $temp_file
        sed -i '/deleted/d' $temp_file
        sed -i '/owner_name/d' $temp_file
        sed -i '/current_user_role_id/d' $temp_file
        sed -i '/repo_count/d' $temp_file
        sed -i 's/\"name\"/\"project_name\"/g' $temp_file
}

## 分片项目文件的json文件，每个项目一个json文件，在新harbor2创建项目时使用
split_projects()
{
        rm -fr split/*
        for f in `cat $temp_file | jq -r 'keys[]'`
        do
                cat $temp_file | jq ".[$f]" > split/${source_projects[$f]}.json
        done
	#rm -f $temp_file
}

## 检查本地镜像缓存目录/var/lib/docker空间是否充足，空间不足则清理本地镜像
Check_disk_usag()
{
	asize_percentage=$(df -h | grep '/dev/mapper/overlay2-lvol0' | awk '{print $5}' | cut -d "%" -f 1)
	if [ $asize_percentage -gt 80 ]
	then
		local images=($(docker images|grep -v REPOSITORY|grep 'test.com'|awk -F' ' '{print $1":"$2}'))
		for ri in ${images[@]}
		do
			docker rmi $ri
		done
	fi
}

### 调用用法 : Check_image_exist <project_name>/<repo_name> "${source_tag_list[*]}"
Check_image_exist()
{

        local project=${1%/*}
        local repo=${1##*/}
        local source_tag_list=($2)
        target_tag_list=($(curl -X GET "https://$target_registry/api/v2.0/projects/$project/repositories/$repo/artifacts?page=1&page_size=10000&with_tag=true" -H  "accept: application/json" -H  "authorization: Basic $target_auth" 2>/dev/null |jq .[].tags|jq -r .[].name))
        ## 求异 ##
        local temp1_tags=($(echo ${source_tag_list[@]} ${target_tag_list[@]} | sed 's/ /\n/g'|sort | uniq -u))
        ## 求同 ##
        local temp2_tags=($(echo ${temp1_tags[@]} ${source_tag_list[@]} | sed 's/ /\n/g'|sort | uniq -d))
	echo ${temp2_tags[@]}
}

## 迁移一个项目的一个镜像仓库
Migrate_one_repos()
{

	local p_i=$1
	local project=${p_i%/*}
	local source_tag_list=($(curl -X GET -H "Content-Type: application/json" -H  "authorization: Basic $source_auth" "https://$source_registry/api/repositories/${p_i}/tags" 2>/dev/null |jq -r .[].name))
	val_return=$(echo $project ${target_projects[@]} | sed 's/ /\n/g'|sort | uniq -d)
	if [ -z "$val_return" ]
	then
		tag_list=(${source_tag_list[@]})
	else
		tag_list=($(Check_image_exist ${p_i} "${source_tag_list[*]}"))
	fi
	for tag in ${tag_list[@]}
	do
		Check_disk_usag
		docker pull $source_registry/${p_i}:$tag
		docker tag $source_registry/${p_i}:$tag $target_registry/${p_i}:$tag
		docker push $target_registry/${p_i}:$tag
	done
}

## 迁移项目
Migrate_all_projects()
{
	for p in ${source_projects[@]}
	do
		p_repos=($(curl -X GET -H "Content-Type: application/json" -H  "authorization: Basic $source_auth" "https://$source_registry/api/search?q=$p" 2>/dev/null |jq -r .repository[].repository_name))
		for p_repo in ${p_repos[@]}
		do
			Migrate_one_repos $p_repo
		done
	done
}

Create_project
init_projects_file
split_projects
Migrate_all_projects

**Comment by yanji09** [comment]
Currently harbor doesn't test this scenario.
Suggest to post it as a blog if you can.
