### ISSUE TITLE
[ERROR] "message":"system auth_mode isn't ldap_auth, please check configuration"

### ISSUE THREAD

**Issue by MrVBian** [goharbor/harbor#14258]
core.log:
[ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"system auth_mode isn't ldap_auth, please check configuration"}]}

details：
There is no configuration error when configuring LDAP. An error is reported after the test button is pressed.
Solution:
First save the configuration, and then test, it can be successfully configured.

**Comment by gy95** [comment]
> core.log:
> [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"system auth_mode isn't ldap_auth, please check configuration"}]}
> 
> details：
> There is no configuration error when configuring LDAP. An error is reported after the test button is pressed.
> Solution:
> First save the configuration, and then test, it can be successfully configured.

老哥你咋配置的LDAP，能详细说一下嘛

**Comment by MrVBian** [comment]
> > core.log:
> > [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"system auth_mode isn't ldap_auth, please check configuration"}]}
> > details：
> > There is no configuration error when configuring LDAP. An error is reported after the test button is pressed.
> > Solution:
> > First save the configuration, and then test, it can be successfully configured.
> 
> 老哥你咋配置的LDAP，能详细说一下嘛

![image](https://user-images.githubusercontent.com/37790267/109901555-4061e300-7cd4-11eb-9fbf-6a1f2c91d14f.png)

**Comment by MrVBian** [comment]
> 老哥你咋配置的LDAP，能详细说一下嘛

我是Ldap没有问题。遇到了神学问题。先保存后测试LDAP服务器成功。先测试LDAP服务器后保存报错。
希望对你有所帮助。

**Comment by stonezdj** [comment]
The previous implementation requires the current auth_mode should be ldap_auth, after the PR https://github.com/goharbor/harbor/pull/14351 merged, this issue is fixed.
