### ISSUE TITLE
What are the sources of the clair database update?

### ISSUE THREAD

**Issue by rgadeev** [goharbor/harbor#14267]
Сan I find out the sources of the clair database update (CVE)? I need to pass traffic through the firewall.

**Comment by phin1x** [comment]
clair doesn't have one db like trivy. clair gets its cve data from multiple datasources like nist.gov, the oval definitions (for example suse or redhat) / custom database (for example alpine) from the linux distributions.
the easy way of getting all domains is setting up squid or something similar and record all http request clair does. the harder way is going to https://github.com/quay/claircore and search for the database locations manually.

**Comment by rgadeev** [comment]
Thanks
All I could find was there

rhel   https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL%d.xml
ubuntu https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.%s.cve.oval.xml.bz2
alpine https://secdb.alpinelinux.org/%s/%s.json
aws    http://repo.us-west-2.amazonaws.com/2018.03/updates/x86_64/mirror.list
           https://cdn.amazonlinux.com/2/core/latest/x86_64/mirror.list
	   (need read and parsing)
debian https://www.debian.org/security/oval/oval-definitions-%s.xml
oracle https://linux.oracle.com/security/oval/com.oracle.elsa-all.xml.bz2
           https://linux.oracle.com/security/oval/com.oracle.elsa-%d.xml.bz2
	   http://oval.mitre.org
	   
photon https://packages.vmware.com/photon/photon_oval_definitions/	   
pyupio https://github.com/pyupio/safety-db/archive/master.tar.gz
suse https://support.novell.com/security/oval/
