### ISSUE TITLE
Keep's retrying on push, and not able to pull

### ISSUE THREAD

**Issue by rhjensen79** [goharbor/harbor#14269]
What can we help you?
On my newly deployed Harbor, on ubuntu 18.04, behind a Traefik proxy, i can login just fine,
but when i push an image, it keeps saying retrying in xx seconds, and then it ends, and looks like it ok.
But there is no image pushed, and i can't pull it again.

The push refers to repository [registry.cmplab.dk/cmplab/ubuntu]
e156c976a2ba: Pushing [==================================================>]  3.072kB
45d8dc025525: Retrying in 1 second
f2fa9f4cf8fd: Retrying in 3 seconds

I can't find anything usefull in the logs.

Harbor is running on http on port 8080, and the Traefik reverse proxy, is getting a valid let's encrypt certificate, and is responding on port 443. 
I have a feeling that it could be what's causing the problem. 

So all help is appreciated.

Thanks

**Comment by rhjensen79** [comment]
Closing. Found the error. 
Read this trubleshooting blog, and i think what fixed it, was that i had to # proxy_set_header X-Forwarded-Proto $scheme; 
multiple times. I missed that. 

https://www.claudiokuenzler.com/blog/958/running-harbor-registry-behind-reverse-proxy-solve-docker-push-errors

**Comment by rhjensen79** [comment]
Closing. Found the error. see privies note

**Comment by kerry-Cho** [comment]
@rhjensen79
Hi, I have a same problem but I have a slightly different setup.
It's revers proxy is a K8s ingress service and service type ExternalName , The ExternalName use to IPaddress
What should I check on the situation now?

in my case https -> K8s Ingress-> exterName -> http -> [ Docker Host FW -> Harbor Nginx -> Harbor Core ]
