### ISSUE TITLE
Does Harbor support the CAS？

### ISSUE THREAD

**Issue by aluomaidi** [goharbor/harbor#14275]
The SSO used by our company is based on CAS, and I want Harbor to integrate CAS. What should I do in case of secondary development?

**Comment by reasonerjt** [comment]
I have no experience using CAS but seems you can configure CAS as an OIDC provider:
https://apereo.github.io/cas/5.0.x/installation/OIDC-Authentication.html

**Comment by reasonerjt** [comment]
Closing as the question is answered.

**Comment by foreverm10** [comment]
Can I use this
