### ISSUE TITLE
Label with long name can not be deleted

### ISSUE THREAD

**Issue by Pactionly** [goharbor/harbor#14276]
**Expected behavior and actual behavior:**
Actual Behavior: When a label with a very long name is created, the creation process goes smoothly. When a user tries to delete that label, Harbor returns a 500 Internal Server Error and the label is not successfully deleted.

Expected Behavior: When a request to delete a label is sent, the label is deleted and Harbor returns 200 Ok.

**Steps to reproduce the problem:**
Navigate to Harbor Administration - > Labels tab. Create a new label with a name length between 126-128 characters. Select, and delete that label. 

**Versions:**

- harbor version: [Version v2.1.3-b6de84c5]
- docker engine version: [20.10.2]
- docker-compose version: [1.27.4]

**Additional context:**

Harbor Core Logs:
```
2021-02-22T01:07:40Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to delete label 14: pq: value too long for type character varying(128)"}]}
```

**Comment by Pactionly** [comment]
After a bit more testing, a similar problem occurs for projects as well as labels. When a project is created with a name near its character limit, deleting it becomes impossible, as trying to delete returns 500 errors.

I assume the problem might be caused by these lines:
https://github.com/goharbor/harbor/blob/master/src/common/dao/project.go#L295
https://github.com/goharbor/harbor/blob/master/src/common/dao/label.go#L105
which seem to be changing the name of the resource when marking them for deletion.

**Comment by ywk253100** [comment]
The label will be hard deletion in 2.3.
And for the project, fixed by https://github.com/goharbor/harbor/pull/14912
