### ISSUE TITLE
Redirect to user dashboard after user registered successfully.

### ISSUE THREAD

**Issue by liboshi** [goharbor/harbor#1428]
harbor version: 0.5.0

Install harbor-0.5.0 on my own Ubuntu 16.04.2 LTS. Then I register a new user, such as "TestUser".
After registered successfully, page will be redirected to home rather than user dashboard. It means that I have to login again.

I think it is not a good user experience. Maybe you can improve it.

Thanks.

**Comment by reasonerjt** [comment]
we are redesigning UI and the UX flow.
