### ISSUE TITLE
Upgraded Harbor/Notary from v1.10.4 to v2.1.3 - Error response from daemon: unknown: The image is not signed in Notary.

### ISSUE THREAD

**Issue by GJKrupa** [goharbor/harbor#14281]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior**

Able to docker pull pre-existing images before the upgrade

**Actual behavior:**

`Error response from daemon: unknown: The image is not signed in Notary.`

**Steps to reproduce the problem:**
Install Harbor v1.10.4 with Notary v0.6.1-v1.10.1
Push a signed image
Upgrade to Harbor and Notary v2.1.3
Attempt to pull the previously pushed image

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.3
- docker engine version: 19.03.14
- docker-compose version: 1.28.4

**Additional context:**

- Contains sensitive data

**Comment by GJKrupa** [comment]
There were no obvious errors in the Harbor, Notary or Docker Daemon logs but when inspecting the Harbor API using the Chrome dev tools I could see that the images were *not* being reported as signed. Is there some intermediate upgrade required instead of going directly from 1.10.4 to 2.1.3?

**Comment by reasonerjt** [comment]
You should be able to upgrade from 1.10.x to 2.1.x 

If the data is not lost during the upgrade the signatures should be retained.

1.10.x is a bit old to support I'll see if anyone from community can help.

**Comment by GJKrupa** [comment]
The project that was affected by this has been shut down so this is no longer something that I need to address (or that I will be able to test further).

**Comment by reasonerjt** [comment]
@GJKrupa 
This is unfortunate, but thanks for the update.
