### ISSUE TITLE
Harbor replication issues since upgrade to OSS version:v2.1.3

### ISSUE THREAD

**Issue by cparadal** [goharbor/harbor#14292]
What can we help you?

We're running Harbor on Kubernetes v1.18.15. We recently upgraded Harbor from Helm chart v1.4.6 (Harbor OSS version:v2.0.6) to Helm chart v1.5.3 (Harbor OSS version:v2.1.3)

Since the upgrade, we've noticed a number of errors re replication:

- One of the replication rules can't be disabled, we get an `Internal Server Error` in the UI, which on the `jobservice` logs translates to:
```
[ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/d353946f090203dbc8ca5035' error: 404 {"code":10010,"message":"object is not found","details":"d353946f090203dbc8ca5035"}
```

- Another replication rule, which is currently trying to replicate artifacts to a destination Harbor instance, and uses a robot account for authentication, errors out complaining about said robot account not existing:

```
failed to do the prepare work for pushing/uploading resources: http error: code 404, message {"errors": [{"code":"NOT_FOUND","message":"user robot$XXXXX not found"
```

... but the robot account does exist, and this was working fine before.

In terms of configuration, we're currently using external components for Harbor database (RDS Postgres), chart/image persistence (S3 bucket) and caching layer (Redis Elasticache).
I've tried stuff such as Harbor restarts, Redis flushing, GC runs... to no avail.

**Comment by phin1x** [comment]
@cparadal did you try to delete the redis database? this fixed some of our issues with the jobservice.

**Comment by cparadal** [comment]
> @cparadal did you try to delete the redis database? this fixed some of our issues with the jobservice.

Hi, I've tried flushing and also rebooting the Elasticache cluster. Also, i've tried switching to Redis internal but no luck.

**Comment by wsams** [comment]
We're seeing this same issue at least as far back as Harbor 2.1.1. We are a TKGI customer.

**Comment by steven-zou** [comment]
@ywk253100 

Would you please check the issue why the robot account is not found in the preparation stage?

>Another replication rule, which is currently trying to replicate artifacts to a destination Harbor instance, and uses a robot account for authentication, errors out complaining about said robot account not existing:

`failed to do the prepare work for pushing/uploading resources: http error: code 404, message {"errors": [{"code":"NOT_FOUND","message":"user robot$XXXXX not found"`

**Comment by ywk253100** [comment]
The robot account cannot be used for replication

**Comment by steven-zou** [comment]
@cparadal 

When meeting the error you mentioned, is it possible to check the reids data if the job stats is still there?

>Since the upgrade, we've noticed a number of errors re replication:
One of the replication rules can't be disabled, we get an Internal Server Error in the UI, which on the jobservice logs translates to:

`[ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/d353946f090203dbc8ca5035' error: 404 {"code":10010,"message":"object is not found","details":"d353946f090203dbc8ca5035"}`


The key of the  job stats is {js-namespace}:job_stats:<job_id>.

The job stats might be gone as there is a default expiration time for reducing the data kept in the Redis DB.

We're also looking at the code at core side to see if it handles the 404 case correctly.

**Comment by steven-zou** [comment]
Probably it's similar to the issue： https://github.com/goharbor/harbor/issues/13958

**Comment by steven-zou** [comment]
And this one: https://github.com/goharbor/harbor/issues/13732

The `object not found` error.

**Comment by steven-zou** [comment]
@cparadal / @wsams / @phin1x :

This issue has been fixed in the 2.2 release and we'll also introduce a fix into the 2.1.4 patch release.

**Comment by steven-zou** [comment]
Can be fixed by pr 

- 1. https://github.com/goharbor/harbor/pull/14601
- 2. https://github.com/goharbor/harbor/pull/14597

**Comment by krth1k** [comment]
> @cparadal did you try to delete the redis database? this fixed some of our issues with the jobservice.

Thanks, its worked for me.  I deleted the harbor-redis pod. It works for me.
