### ISSUE TITLE
Notary key rotate & delete fails in Harbor v2.1.3

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#14303]
/cc @reasonerjt 

**Expected behavior and actual behavior:**
We're running Harbor v2.1.3 with Notary, we are able to push images to the repo and then using `notary` client to init a collection and sign the images, they appear as signed in Harbor UI.

However, when attempting to use `notary` client to rotate the snapshot or timestamp keys, or to delete a collection from notary, we get a `401 not authorized` error.

we use the `admin` user to authenticate, by setting:
```
NOTARY_AUTH=$(echo admin:<password> | base64)
```

this is the client command:
```
❯ notary -s https://notary.<our registry> key rotate <our registry>/<project>/test/test-image snapshot -r --debug -v
DEBU[0000] Using the following trust directory: /Users/<user>/.docker/trust
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] Making dir path: /Users/<user>/.docker/trust/tuf/<our registry>/<project>/test/test-image/changelist
* fatal: unable to rotate remote key: you are not authorized to perform this operation: server returned 401.
```

Setting the log level to `debug` for all Harbor components, the only relevant log is in `harbor-server`:
```
{"go.version":"go1.14.13","http.request.host":"notary.<our registry>","http.request.id":"434ebabc-d572-4d94-9a23-55d68694dd3e","http.request.method":"POST","http.request.remoteaddr":"10.253.1.19","http.request.uri":"/v2/<our registry>/<project>/test/test-image/_trust/tuf/snapshot.key","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"292.464µs","http.response.status":401,"http.response.written":195,"level":"info","msg":"response completed","time":"2021-02-24T04:50:49Z"}
```

similar log is shown when trying to rotate a timestamp key or when deleting a collection.

We were able to fix the issue by rolling back all the images of Harbor component to v2.1.2 (nothing else changed), and the above commands work as expected.

here's a similar log snippet from `notary-server` when rotating timestamp & snapshot keys with Harbor 2.1.2:

```
{"go.version":"go1.14.7","http.request.host":"notary.<our registry>","http.request.id":"5fa10e5e-4d8f-4fc3-86d8-a801b3d2ada1","http.request.method":"POST","http.request.remoteaddr":"10.253.1.18","http.request.uri":"/v2/<our registry>/<project>/test/test-image/_trust/tuf/snapshot.key","http.request.useragent":"Go-http-client/1.1","http.response.duration":"19.309709ms","http.response.status":200,"http.response.written":181,"level":"info","msg":"response completed","time":"2021-02-25T02:41:13Z"}

{"go.version":"go1.14.7","http.request.host":"notary.<our registry>","http.request.id":"eaafd505-cb4b-41a1-b98b-f86e5b1dbafe","http.request.method":"GET","http.request.remoteaddr":"10.253.1.16","http.request.uri":"/v2/<our registry>/<project>/test/test-image/_trust/tuf/timestamp.json","http.request.useragent":"Go-http-client/1.1","http.response.duration":"2.712442ms","http.response.status":200,"http.response.written":495,"level":"info","msg":"response completed","time":"2021-02-25T02:41:15Z"}
```

both commands were successful and returned 200.

**Steps to reproduce the problem:**
1. Deploy Harbor 2.1.3 with notary
2. Push and sign an image
3. using the `notary` client cli, try to rotate the timestamp or snapshot key:
   ```sh
   $ notary -s notary.<registry> key rotate <registry>/<project>/<repo> snapshot -r
   $ notary -s notary.<registry> key rotate <registry>/<project>/<repo> timestamp -r
   ```
   both commands will fail with `fatal: unable to rotate remote key: you are not authorized to perform this operation: server returned 401.`

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.3]
- notary client version: [0.6.1]

**Additional context:**

- Harbor is deployed in K8s using a Helm chart

**Comment by reasonerjt** [comment]
I can reproduce the issue, it was introduced by this commit:
https://github.com/goharbor/harbor/commit/5e8506831a306db0e27cc364239aabfdc8fea8a3

Where the "*" was removed from the claim of a token and grant the permission of action according to distribution code:
https://github.com/distribution/distribution/blob/main/registry/handlers/app.go#L907

However, I didn't realize the "*" is being used in Notary for specific permission, such as
https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L200

I'll add the `*` as specific permission to project admin and system admin to fix the issue.

**Comment by DerrickMartinez** [comment]
Is this related to an error w/ the notary client:  (in core logs)

2021-03-04T02:55:24Z [ERROR] [/core/service/token/authutils.go:103]: Failed to handle the resource repository:project/company-ui, due to error Mismatch endpoint from string: project/company-ui, expected endpoint: harbor.ourdomain.com, returning empty access for it.

**Comment by reasonerjt** [comment]
- [x] `master`: #14336 
- [ ] `2.2.x`: #14343
- [x] `2.1.x`: #14342
