### ISSUE TITLE
TEST OIDC SERVER failed

### ISSUE THREAD

**Issue by gy95** [goharbor/harbor#14306]
when i click the  'TEST OIDC SERVER' button, UI error is "failed to verify connection".
log error is as follows:
[/core/api/oidc.go:53]: Failed to verify connection: {URL:https://127.0.0.1:5554/dex VerifyCert:false}, err: Get "https://127.0.0.1:5554/dex/.well-known/openid-configuration": http: server gave HTTP response to HTTPS client

I choose dex(https://github.com/dexidp/dex) as the OIDC server, how to fix this problem

**Comment by reasonerjt** [comment]
Do you have experience using dex?
Seems it's hosting HTTP not HTTPS

**Comment by gy95** [comment]
> Do you have experience using dex?
> Seems it's hosting HTTP not HTTPS

no, i am just trying OIDC function, and harbor docs(https://goharbor.io/docs/2.0.0/administration/configure-authentication/oidc-auth/) uses the dex, i think dex works well.
![image](https://user-images.githubusercontent.com/36992787/109123280-9be81a00-7784-11eb-8784-fe210fb25a3d.png)

**Comment by gy95** [comment]
> Do you have experience using dex?
> Seems it's hosting HTTP not HTTPS

有什么解决办法吗

**Comment by gy95** [comment]
> Do you have experience using dex?
> Seems it's hosting HTTP not HTTPS

ok, it's dex problem, HTTPS server is broken in the master.
I solved this problem using the tag release.
