### ISSUE TITLE
TEST OIDC SERVER failed

### ISSUE THREAD

**Issue by gy95** [goharbor/harbor#14304]
core.log is as follows: 
Failed to verify connection: {URL:https://127.0.0.1:5554/dex VerifyCert:false}, err: Get "https://127.0.0.1:5554/dex/.well-known/openid-configuration": dial tcp 127.0.0.1:5554: connect: connection refused

but I use curl command(curl http://127.0.0.1:5554/dex/.well-known/openid-configuration) it works well.

harbor server and dex server are installed on the same server.

**Comment by reasonerjt** [comment]
dup to #14306

**Comment by gy95** [comment]
> dup to #14306

not exactly the same, connection refused maybe due to the harbor works in the docker and cannot access ip 127.0.0.1 of the physical server. i tried using physical server ip
