### ISSUE TITLE
the global robot account can't search/read private project information but has covered this project,it could change  it's resource but can't read it?

### ISSUE THREAD

**Issue by Goend** [goharbor/harbor#14314]
harbor version:v2.2.0
![image](https://user-images.githubusercontent.com/40394339/109247639-3b59eb00-781f-11eb-9ec0-4621d9189599.png)
![image](https://user-images.githubusercontent.com/40394339/109247749-68a69900-781f-11eb-8f67-9012fc4e8ae2.png)

**Comment by wy65701436** [comment]
hi, can you clarify the descriptions? Please provide the exactly steps to reproduce you problem.

**Comment by Goend** [comment]
I can't use global robot account to use "/api/v2.0/search?q=",I hope i could get  the repository and projects information about which covered by robotaccount.

**Comment by wy65701436** [comment]
1, the global search is a not kind of resource, for the current design, robot can have access for it.
2, Do you mean that you want a API to list projects/repositories that the robot covered? If so, let's keep this issue open, and get more feedback from community.

**Comment by Goend** [comment]
yes,you know me

**Comment by marcomezzaro** [comment]
Hi,
we've installed harbor 2.3.x and configured it with oidc login. afaik we cannot use local users (except admin) to make api call.
I've done the following:

- a new robot account robot$my-api-user
- all permissions to this robot account
- a new private project named private-demo
- push demo-image

opened insomnia-postman and submit the following api call: 

https://harbor.domain.com/api/v2.0/projects/private-demo/repositories/demo-image/artifacts

if logged in with admin local account: 
200 with correct answer

if logged with basic auth robot account:
403 with {"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}

there is a way to make api call in oidc environment without using admin local account?
our scripts and ci need to communicate to harbor and retrieve informations about repo and tags


thank you for your hard work!

**Comment by wy65701436** [comment]
hi @marcomezzaro can you file another issue for it? 

As for this original problem of this issue, it's fixed by https://github.com/goharbor/harbor/pull/15431, and will be in v2.4, close it.
