### ISSUE TITLE
In OIDC authentication mode, can't we use self-registration way to register users?

### ISSUE THREAD

**Issue by gy95** [goharbor/harbor#14327]
If I configure an OIDC provider in Harbor, I cannot using database authentication mode, and harbor don't allow self-registration.
Is this right?

**Comment by phin1x** [comment]
yes, thats correct. you can only use one authentication provider. combining two or more is not possible.

**Comment by Vad1mo** [comment]
Take a look at auth0.com it works great with harbor and has a generous free tier. This should be enough for internal and external users.
