### ISSUE TITLE
Error with GCR configuration: invalid key size

### ISSUE THREAD

**Issue by cyrilcros** [goharbor/harbor#14326]
I created a Google cloud service account and got a json token GCR. When I configure the GCR endpoint I get: `2021-02-27T00:32:55Z [ERROR] [/replication/registry/manager.go:112]: Convert registry model to dao layer model error: crypto/aes: invalid key size 23 ` 
The registry endpoint gets `connection tested successfully` when I test the connection and `internal server error` when I try to create it.

- harbor version: [2.2.0]
- using the v1.6.0 Helm Chart

__________________________FIRST ISSUE SUBMISSION NOW COVERED BY #14477________________________________

If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I can set up proxy caches with empty access id/secret  for DockerHub,  Quay, Gitlab, but not the Google cloud registry. It doesn't seem possible to access and cache publicly available images.

Expected behavior: get an endpoint set up for gcr.io without needing to create a service account / a json key.

**Steps to reproduce the problem:**
Try to set up a GCR endpoint: there is no anonymous option you need a  `_json_key` which cannot be blank.
**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.0]
- using the v1.6.0 Helm Chart

NOTE: this issue is different from #14090 because my harbor version is 2.2.0 and this is now supported in theory since #13537 has been merged. #14234 is the same for gitlab.

PS: using a Google cloud service account I created I now see: `2021-02-27T00:32:55Z [ERROR] [/replication/registry/manager.go:112]: Convert registry model to dao layer model error: crypto/aes: invalid key size 23 ` when I use the generated json key so something else may be wrong? The registry endpoint gets `connection tested successfully` when I test the connection and `internal server error` when I try to create it.

**Comment by Hokwang** [comment]
@stonezdj Can you check this issue, please?

**Comment by Hokwang** [comment]
@bitsf please check this issue.

**Comment by bitsf** [comment]
for anonymous case, you just need to use the ''Docker Registry" type
@stonezdj consider to add ''Docker Registry" type in proxy cache later

**Comment by cyrilcros** [comment]
@bitsf Thanks, I will edit the issue to reflect the problem is now GCR token, and open another one for for the cache type.

**Comment by stonezdj** [comment]
Docker registry is added to proxy cache in Harbor 2.2.x and 2.3.x
