### ISSUE TITLE
How to install a LDAP server?

### ISSUE THREAD

**Issue by gy95** [goharbor/harbor#14332]
I want to select LDAP/AD authentication mode.
But i did not find documents for installing a LDAP server, does someone use this mode and install a LDAP server?
please give me some opinions about building LDAP server.

**Comment by Vad1mo** [comment]
How to install an operate an LDAP Service is out of scope of this project. Please look at Microsfoft AD, Azure AD or Apache Directory and teir respective detailed installation guides.
