### ISSUE TITLE
global search does not work as expected after 2.2.0 migration

### ISSUE THREAD

**Issue by phin1x** [goharbor/harbor#14338]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
After migrating from version 2.1.3 to 2.2.0, harbor does not show any results when we search for images or helm charts (e.g. ubuntu, golang, python) in the global search. When we search for projects, everything works as expected. I don't see any errors in the logs and increasing the log level to debug didn't help either. I can reproduce this behavior on our production and test environment.
I can provide some screenshot if they help.

**Steps to reproduce the problem:**
1. setup Harbor 2.1.3
2. push some images into harbor (for example ubuntu)
3. test global search for the image
2. migrate Harbor to 2.2.0
3. search for the image again, image should not show up

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.0

**Additional context:**

**Comment by heww** [comment]
Hi, @phin1x do you execute the global search by the system admin or a normal user?

The global search will only show the repositories whose projects can be accessed by the user.

**Comment by phin1x** [comment]
We have tested it as a normal user and as an admin, both times did not work. Images / Helm Charts from public projects are also not displayed.

**Comment by heww** [comment]
Hi, @phin1x thanks for your reply. I got the reason for this bug and will fix it in v2.2.1.
