### ISSUE TITLE
arm64 supported

### ISSUE THREAD

**Issue by HankHannah** [goharbor/harbor#14330]
Hi Harbor team,
 Since the Linux os based on arm architecture is more and more popular.So  could you please support arm64 version installation package for each release started at 2.x version?

**Comment by ninjadq** [comment]
We have plan to support arm architecture in next release. You can attend our biweekly community meeting for more info

**Comment by zbh2021** [comment]
> We have plan to support arm architecture in next release. You can attend our biweekly community meeting for more info

when  the  next release  be released?

**Comment by iTonyYo** [comment]
when the next release be released?
