### ISSUE TITLE
I cannot push images to harbor

### ISSUE THREAD

**Issue by thangnv201** [goharbor/harbor#14367]
When I try to push image to harbor. It have a error.
`vht@harbor:~$ docker push 172.21.5.247/software/hello-world

Using default tag: latest

The push refers to repository [172.21.5.247/software/hello-world]

9c27e219663c: Pushed

unknown: http status code: 404, body: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"software/hello-world","Revision":"sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042"}}]}
`

**Comment by ninjadq** [comment]
could you provide more information? like environment and logs?
