### ISSUE TITLE
Troubles with schedule task

### ISSUE THREAD

**Issue by eugenesotnikov** [goharbor/harbor#14380]
Hello
I have harbor that i upgraded from old versions. And i always had trouble with schedule. For example now i disable schedule in policy, but tasks still run ever 10 minutes how it was. I got error "internal server error" when edit schedule to none and save it. 
I edited schedule to daily. And it didn't work. Still worked old schedule every 10 minutes. And it's trouble in all tasks. In policy, in GC.

How can i delete all invisible/visible schedule tasks, history,cashe etc and start all from beginer?

- harbor version: 2.1.3
- docker engine version: 19.03.12
- docker-compose version: 1.26.1

![image](https://user-images.githubusercontent.com/60689184/110085490-3c03fb80-7da2-11eb-8837-d2c11d7e4d0f.png)
![image](https://user-images.githubusercontent.com/60689184/110086064-f7c52b00-7da2-11eb-9ef9-03110a43c8a2.png)

**Comment by phin1x** [comment]
We faced the same issue and ended up with a new, fresh installation of harbor.

**Comment by eugenesotnikov** [comment]
ohh. it's terrible. i don't want to manual create project, charmuseum, proxy, users. May bee exists solution to flush schedule part. I think it's truncate 2-3 table in pg and some flush in redis...

**Comment by phin1x** [comment]
migrating to a fresh instance is not very complicated. here is our migration plan:

```
db tables (via pg_dump / psql):
 
cve_allowlist
harbor_label
harbor_resource_label
harbor_user
immutable_tag_rule
notification_policy
project
project_member
project_metadata
properties
registry
replication_policy
retention_policy
robot
schedule
user_group
quota
quota_usage
 
pg_dump -a -O -b -t cve_allowlist -t harbor_label -t harbor_resource_label -t harbor_user -t immutable_tag_rule -t notification_policy -t project -t project_member -t project_metadata -t properties -t registry -t replication_policy -t retention_policy -t robot -t schedule -t user_group -t quota -t quota_usage registry | egrep -v 'robot.*for scan'

-> set quota usage for all projects to 0
-> remove admin user from: harbor_user project_member
-> remove library project from: quota quota_usage project project_metadata

fs directories (via rsync):
/data/secret/
 
image / chart replication:
internal push based harbor replication (event)
-> source name: **
   source tag: **
   destination registry: <new harbor>
   destination namespace: <empty>`
```

**Comment by eugenesotnikov** [comment]
hmm. thnks. i will think. but may bee fresh installation of harbor will be more simple.  ((

**Comment by eugenesotnikov** [comment]
At the end i made fresh installation of harbor. I think it is best solution. Repair is very hard. Harbor had not simple system of scheduling imho.
