### ISSUE TITLE
Error response from daemon: : x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dylanyht** [goharbor/harbor#14385]
I created an https certificate based on the https://goharbor.io/docs/2.0.0/install-config/configure-https/ address but I get an error in docker login with the following error.

```
docker login  harbor.xxx.com
Username: admin
Password:
Error response from daemon: Get https://harbor.xxx.com/v2/: x509: certificate signed by unknown authority
```
I still can't do it according to the issue https://github.com/goharbor/harbor/issues/6774, is there any other way to deal with this problem?

**Comment by dylanyht** [comment]
Already solved, thanks to the community

**Comment by enajeeb** [comment]
@dylanyht can you please share the fix. I started facing the same issue after `v2.2.0` upgrade.

**Comment by AlexanderZhou01** [comment]
Can you please share the fix

**Comment by thiagooqueiroz86** [comment]
Can you please share fix

**Comment by AnAnonymousFriend** [comment]
Can you please share fix

**Comment by thiagooqueiroz86** [comment]
Hello, my problem was that I was only passing the .crt and .key certificates when including the entire certificate chain, the problem disappeared
