### ISSUE TITLE
Scheduled tasks not running after upgrade from 2.1.3 to 2.2.0

### ISSUE THREAD

**Issue by Lemmons** [goharbor/harbor#14393]
**Expected behavior and actual behavior:**
We upgraded from 2.1.3 to 2.2.0.  Since the migration, scheduled tasks no longer run, this includes replications with a cron schedule and image retention jobs.

**Steps to reproduce the problem:**
It is unclear why exactly this happened in our environment.  I assume most users are not experiencing this bug.

**Versions:**
- harbor version: [2.2.0]
- harbor helm: [1.6.0]

**Additional context:**
I cannot currently provide logs, as I haven't found any which look relevant yet, but if I do find some I will add them.
Looking at both the release notes and database migration, it's clear the v2.2.0 has changed the way scheduled tasks are ran, but I have been unsuccessful in finding information on where these processes run and where to look for errors.

**Comment by Lemmons** [comment]
It appears that updating the cron schedule for the non-running tasks (via the Harbor Web UI) got them going again.  This seems to indicate some sort of race condition when doing the migration.  Either something didn't get properly updated in the postgres database, or something didn't get updated in redis, though I'm not familiar enough with these systems to say which is was.

**Comment by Lemmons** [comment]
We continued to have issues after upgrading to 2.2.0.  Since purging the redis data, scheduled jobs (replications, scans, retention) have all stopped working again.

It seems that https://github.com/goharbor/harbor/issues/13440 might be related, but the context for it only is around GC jobs, but this is affecting all jobs in our deployment, and the suggested workaround mention a database table which no longer exists.  What is the proper way to get scheduled jobs running again?

**Comment by bitsf** [comment]
you should not purging redis data, especially redis db 2 which is used for jobservice schedule settings.
you can try edit the cron job on UI which should regenerate the setting after version 2.2.x
and upgrade to 2.2.1 which include a fix of a performance issue about jobservice

**Comment by Lemmons** [comment]
We had no choice.  As I stated in the attached ticket, the retention job created 100's of duplicate replication runs, and the only way we could get it to stop hammering the database was to purge the redis cache, as deleting the replication runs did not stop the jobservice from continuing to hammer the database at an unreasonable rate.  Additionally, the case is that redis should not be purged, then you need much better documentation on how to actually operate Harbor, and fix it's inevitable problems.  We have been forced to dig through source code and try to parse out how each component works in detail because the operational documentation is poor and the devs are extremely slow to answer any question on github, often leaving them entirely unanswered.  For instance, https://github.com/goharbor/harbor/issues/13544 asks what the purpose of the redis instance is and no real answer is ever given, and the documentation doesn't go over what redis is used for basically at all.

**Comment by viceice** [comment]
So every time my redis cluster is reset, all schedules need to be edited to get working again?

I had some required full stops of my kubernetes cluster, so my redis lost data, because they only use temp volume.

If you say, redis database for job service must persisted, i need to enbale persistend volumes for my redis cluster?

**Comment by sidewinder12s** [comment]
> So every time my redis cluster is reset, all schedules need to be edited to get working again?
> 
> I had some required full stops of my kubernetes cluster, so my redis lost data, because they only use temp volume.
> 
> If you say, redis database for job service must persisted, i need to enbale persistend volumes for my redis cluster?

I haven't found a very good answer around what data is stored in Redis, other than its not nearly as cache/trashable as the architecture docs imply. We've generally had a ton of issues with the Job service due to bugs, then clearing redis to remediate the bug which then exposed us to more issues cause the redis data was gone.
