### ISSUE TITLE
can not update retention schedule after upgrade from 2.0.x to 2.1.x

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14405]
1. upgrade from 2.0.1 to 2.1.3
2. edit retention job schedule from daily to weekly or none
3. report `internal server error`
![image](https://user-images.githubusercontent.com/188115/110587533-c7b8c600-81ae-11eb-93df-74ca87221555.png)
4. error log in core.log
![image](https://user-images.githubusercontent.com/188115/110587822-17978d00-81af-11eb-9d6c-53e4df76cb70.png)

**Comment by bitsf** [comment]
![Uploading image.png…]()

**Comment by ywk253100** [comment]
This is also effect v2.2.0, the workaround is to run the sql command inside the database container:
```
update execution set status='Success', revision=0 where status is NULL;
```

**Comment by ywk253100** [comment]
This doesn't effect v2.2 as we have updated the revision during the upgrade of 2.2 https://github.com/goharbor/harbor/blob/v2.2.0/make/migrations/postgresql/0050_2.2.0_schema.up.sql#L543

**Comment by ywk253100** [comment]
Fixed
