### ISSUE TITLE
Core service can not connect Cluster redis 

### ISSUE THREAD

**Issue by StevenLeiZhang** [goharbor/harbor#14409]
Install harbor with an external Cluster redis.
core serveice can not boot up normally.
log shows 

`[WARNING] [/lib/cache/helper.go:65]: failed to save value to cache, error: MOVED 11633 xxxxxxxxx:6379

2021/03/10 12:07:36.897 [E] [middleware.go:52]  MOVED 4662 xxxxx:6379
2021/03/10 12:07:38.431 [E] [middleware.go:52]  MOVED 11191 xxxxx:6379
2021/03/10 12:07:46.896 [E] [middleware.go:52]  MOVED 4617 xxxxx:6379
2021/03/10 12:07:48.431 [E] [middleware.go:52]  MOVED 13544 xxxxx:6379
2021/03/10 12:08:16.896 [E] [middleware.go:52]  MOVED 14067 xxxxx:6379`

It seems that redigo does not support "cluster redis"
Do you plan upgrade redigo to other client, which supports cluster redis ?

**Comment by ninjadq** [comment]
We didn't have plan to upgrade it recently, you can try redis sentinel
