### ISSUE TITLE
The ChartMuseum is scheduled to be deprecated in a future v2.4.0 release.

### ISSUE THREAD

**Issue by eugenesotnikov** [goharbor/harbor#14407]
I read features of relese 2.2.0. And i was very surprised by this
"The ChartMuseum is scheduled to be deprecated in a future v2.4.0 release."
What does it mean? I didn't find anything about it on site.
We have deploy based on helm+harbor. And i want to be ready for this.

**Comment by Vad1mo** [comment]
Helm 3 uses OCI for package distribution. It ships with two new subcommands to help with this: registry and chart. The registry sub-command handles authentication with OCI registries while chart takes care of save, push and pull charts to the registry.
The fetch and pull sub-commands used for interacting with the chart repositories, chartmuseum, (in earlier versions) are still retained for backward compatibility.

**If you use helm 3 then OCI is the future, there will be no need for ChartMuseum, so it's safe to deprecate it.**

**Comment by MaxRink** [comment]
>If you use helm 3 then OCI is the future, there is no need for ChartMuseum, so it's safe to deprecate it.

This is not true, yet. The default helm behaviour still doesnt support OCI and OCI suppoort is still experimental

**Comment by sagikazarmark** [comment]
Quoting the [official website](https://helm.sh/docs/topics/registries/):

> Currently OCI support is considered experimental.

This seems to be quite a major change...major enough not to hide it in a changelog.

I also think that most of the ecosystem still uses the "old" helm repository format, so talking about ChartMuseum deprecation seems to be a bit premature to me.

**Comment by hojerst** [comment]
Considering that Helm Registry support was a major reason why we acutally chose Harbor, I'd also like to see the Chartmuseum supported a bit longer. As mentioned before, the OCI support in helm is still experimental and even needs to be turned on with a env feature flag. I'd really like to see chartmuseum support in Harbor at least until Helm officially supports OCI for production use. Just my two cents.

**Comment by Vad1mo** [comment]
hey all, 

We should close this issue and continue our discussion on https://github.com/goharbor/harbor/discussions/15057

**Comment by steven-zou** [comment]
Agree with @Vad1mo. If you have any comments on the `chartmuseum` deprecation work, move to the discussions on #15057.

cc @hojerst / @sagikazarmark  / @MaxRink / @eugenesotnikov / @alxbse
