### ISSUE TITLE
How to remove the Clair ? 

### ISSUE THREAD

**Issue by ypl75** [goharbor/harbor#14402]
Harbor version used v1.5.2, install  the following command.
./install.sh --with-clair

Now, how to remove the Clair ? 

thank you!

**Comment by balonik** [comment]
Try to run just
`./install.sh`

**Comment by ypl75** [comment]
HI balonik
if run ./install.sh , original information be lost?

**Comment by balonik** [comment]
Hi @ypl75 
If you haven't changed the `harbor.cfg` and if you have not customized the installer all data and database should be located on your server's disks. Re-running the installer should map to your existing data.
Of course if you need, you should create backup before any change.

**Comment by ypl75** [comment]
HI balonik
Thank you for your explanation

**Comment by KeithTt** [comment]
Encountered a bug about clair, disk space did not release. https://github.com/goharbor/harbor/issues/14402

And intend to remove clair, harbor version: v1.10.2.

I followed the official guide: https://goharbor.io/docs/1.10/install-config/reconfigure-manage-lifecycle/ and https://goharbor.io/docs/1.10/install-config/run-installer-script/

I wonder that do I need to exec `prepare` script again before `install.sh` or just exec `install.sh` without `prepare`?
Or refer to the `Reconfigure Harbor` part just exec `prepare` without `install.sh`?

```shell
docker-compose down -v
prepare
docker-compose up -d
```
