### ISSUE TITLE
Harbor Proxy with credentials

### ISSUE THREAD

**Issue by yctn** [goharbor/harbor#14410]
**Is your feature request related to a problem? Please describe.**
So the problem is that i need to add the Harbor credentials in Every projects i wanne deploy into k8s

**Describe the solution you'd like**
https://github.com/Lotto24/aws-ecr-http-proxy

what i would like i a small proxy i can install onto k8s that has the credentials of my harbor registry so i dont have to add the ImagePullSecret to Everything i deploy into k8s

**Describe the main design/architecture of your solution**
see above link

**Describe the development plan you've considered**
i think you can use the reposeitory i linked above. fork it. and make all the changes needed to be compatible with harbor

**Additional context**

**Comment by reasonerjt** [comment]
We are considering adding a mutating webhook via Harbor operator to inject the image pull secret, but that's not decided yet.

You may also push image to public project, so you don't need credentials to pull image.

Other than that, I don't think it justifies a feature in Harbor
