### ISSUE TITLE
Interrogation Services API doesn't supply `tag` value on POST /scan

### ISSUE THREAD

**Issue by skrech** [goharbor/harbor#14416]
**Expected behavior and actual behavior:**
When Harbor sends its POST request to our interrogation service on endpoint `/scan` it always contains empty string for `tag` field. As written in the API spec, it should contain the actual tag of the image. 

Please note, that the tag is displayed correctly in the Harbor UI, it's just not send to the interrogation service.

**Steps to reproduce the problem:**
Just inspect the POST request coming from Harbor with image that is not based on `:latest` tag. By the way, `latest` is never contained in  the `tag` field as well, but I think this is by convention.

**Versions:**
Harbor 2.2

**Comment by heww** [comment]
The scanArtifact endpoint is `/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/scan` and the `reference` can be a digest or a tag.

**Comment by skrech** [comment]
Hello heww,

I think we have some kind of miscommunication. I'm talking about the content of the POST request that is sent from Harbor to its Interrogation Service. In the docs:
```
{
  "registry": {
    "url": "https://core.harbor.domain",
    "authorization": "Basic BASE64_ENCODED_CREDENTIALS"
  },
  "artifact": {
    "repository": "library/mongo",
    "digest": "sha256:6c3c624b58dbbcd3c0dd82b4c53f04194d1247c6eebdaab7c610cf7d66709b3b",
    "**tag**": "3.14-xenial",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
```
The tag field is always empty. Never populated.

**Comment by skrech** [comment]
Hello, any activity on this matter?
