### ISSUE TITLE
Make robot name prefix configurable in harbor.yml 

### ISSUE THREAD

**Issue by jesper510** [goharbor/harbor#14415]
Make robot name prefix configurable in harbor.yml 

This will allow for automatic configuration in cases where the user wants a different robot name prefix. 

I would greatly appreciate this feature.

**Comment by jr200** [comment]
It looks like a subset of configuration needs to be done via the REST APIs after harbor is up and running. In my case, I use the PUT /configurations endpoint (and POST /robots endpoint) to setup system-wide robot accounts via ansible after the install has completed and harbor is up and running. (harbor v2.2.0)

**Comment by jesper510** [comment]
> It looks like a subset of configuration needs to be done via the REST APIs after harbor is up and running. In my case, I use the PUT /configurations endpoint (and POST /robots endpoint) to setup system-wide robot accounts via ansible after the install has completed and harbor is up and running. (harbor v2.2.0)

That's a good idea. Unfortunately I don't see any way to specify the robot name prefix using the /configurations endpoint.

These are the supported variables:
```
{
  "oidc_verify_cert": true,
  "email_identity": "string",
  "ldap_group_search_filter": "string",
  "auth_mode": "string",
  "self_registration": true,
  "oidc_scope": "string",
  "ldap_search_dn": "string",
  "storage_per_project": "string",
  "scan_all_policy": {
    "type": "string",
    "parameter": {
      "daily_time": 0
    }
  },
  "verify_remote_cert": true,
  "ldap_timeout": 0,
  "ldap_base_dn": "string",
  "ldap_filter": "string",
  "read_only": true,
  "quota_per_project_enable": true,
  "ldap_url": "string",
  "oidc_name": "string",
  "project_creation_restriction": "string",
  "ldap_uid": "string",
  "oidc_client_id": "string",
  "ldap_group_base_dn": "string",
  "ldap_group_attribute_name": "string",
  "email_insecure": true,
  "ldap_group_admin_dn": "string",
  "email_username": "string",
  "oidc_endpoint": "string",
  "oidc_client_secret": "string",
  "ldap_scope": 0,
  "count_per_project": "string",
  "token_expiration": 0,
  "ldap_group_search_scope": 0,
  "email_ssl": true,
  "email_port": 0,
  "email_host": "string",
  "email_from": "string"
}
```

There is also no way to specify a different robot name prefix using the /robots endpoint.

**Comment by jr200** [comment]
What version of harbor are you using? I see it on v2.2.0 under a setting called "robot_name_prefix".

**Comment by jesper510** [comment]
> What version of harbor are you using? I see it on v2.2.0 under a /configurations setting called "robot_name_prefix".

I'm on the same version, and you're absolutely right. I thought it wasn't there because it's missing in the Swagger API documentation in the web UI. I tested it with curl and it works. I will make another issue for this. Thanks so much!
