### ISSUE TITLE
'Developer' role should be able to scan

### ISSUE THREAD

**Issue by aw-zededa** [goharbor/harbor#14420]
Why is 'scan' limited to Maintainer and up when a Developer can cause a scan just by uploading an image?  Shouldn't that permission be a level down as a result?  Is there any way to 'move' that permission down on an install?

Thanks!

**Comment by ninjadq** [comment]
This by design

**Comment by aw-zededa** [comment]
OK, why?  What's the overriding reason to limit scan to maintainer?
