### ISSUE TITLE
In OIDC Auth mode, every Harbor user can create new groups 

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#14421]
**Actual behavior:**
In OIDC Auth mode, every Harbor user can create groups. 

**Expected behavior:**
We think this should not be possible, as in Database mode normal users can't do that. 
There is also no possibility for the user to see or change groups, so only creating groups makes no sense.
What should be possible is 
1. Normal user should not be able to create groups
2. A Normal user who is project admin should only be able to add an existing group to the project but not be able to create new groups.

**Steps to reproduce the problem:**

1. Configure Harbor with any OIDC provider 
2. Login as non admin user.
3. Create a new project or assign a user to a project where the user has Project Admin rights
4. Create a new group

**Versions:**
- harbor version: 2.0, 2.1, 2.2

**Comment by reasonerjt** [comment]
@Vad1mo

The flow is that a project admin can add a group that is not onboarded yet to a project as a member.

Otherwise, we need to wait till the first member of the group login Harbor via OIDC before it can be added as a member

**Comment by Vad1mo** [comment]
>  a project admin can add a group that is not onboarded yet

Makes total sense to me, This is how we are using it. 

The bug here is that **every** user can do that not only the admin, and I think this should not be the case.

**Comment by reasonerjt** [comment]
@Vad1mo 

I mean a **project admin**  If a user creates a project, he becomes the project admin and can add members to the project.

**Comment by dioguerra** [comment]
Can we do something like.
1. User logs in for the first time and the groups (that do not exist) are created by the OIDC engine.
2. User creates the project and wants to add a GROUP.
3. User can only create groups that exist (it would be nice that we could have a fuzzy finder dropdown results of what is typed)
4. User adds group to the project (as the admin of said project)

I don't think there is a strong case where the user wants to add a group that is not onBoarded yet. Usually the user would belong to this group, and so when he logs in the group is automatically onboarded, in the case that he does not belong to this group, it would make impossible that project admins add groups (that might be misstyped) leaving the group name persisted on the DB for eternity. In this last case it would only require one user of that group to Login once and the problem would be solved.
