### ISSUE TITLE
[UI] Hovering over Tags of an artifact in a repository shows "(X)" under SIGNED (image is signed)

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#14439]
**Expected behavior and actual behavior:**

When hovering over an artifact's Tags in a repository it should be show a `(V)` for signed images and `(X)` for not signed tags, however all tags appear with `(X)` even though they are all signed:
![image](https://user-images.githubusercontent.com/61992380/111088520-f7910200-84fd-11eb-968b-1753f5f07a0f.png)

When accessing the specific artifact (clicking on `sha256:9a9ec836`), the signed status is rendered correctly:
![image](https://user-images.githubusercontent.com/61992380/111088547-142d3a00-84fe-11eb-9e52-2e271179235a.png)

**Steps to reproduce the problem:**
1. Push and sign an image
2. Find the artifact in the repository view in the UI and hover over "Tags", the tag will show as "not signed" `(X)`
3. click on the artifact - in this view the tag will show as signed `(V)`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.2

**Additional context:**

N/A

**Comment by AllForNothing** [comment]
@dkulchinsky Thanks for your info.
And this is a duplicated issue with #13488, which has been fixed in version 2.2.0

**Comment by dkulchinsky** [comment]
ohh, thanks @AllForNothing! I guess I missed that issue when I was looking if this is a known one.
