### ISSUE TITLE
Add missing variables for /configurations to Swagger documentation

### ISSUE THREAD

**Issue by jesper510** [goharbor/harbor#14437]
**Expected behavior and actual behavior:**

Swagger API documentation for /configurations is missing several variables exposed on the /configurations endpoint:

- http_authproxy_admin_groups
- http_authproxy_endpoint
- http_authproxy_server_certificate
- http_authproxy_skip_search
- http_authproxy_tokenreview_endpoint
- http_authproxy_verify_cert
- ldap_group_membership_attribute
- ldap_verify_cert
- notification_enable
- oidc_admin_group
- oidc_auto_onboard
- oidc_extra_redirect_parms
- oidc_groups_claim
- oidc_user_claim
- robot_name_prefix
- robot_token_duration
- uaa_client_secret
- uaa_endpoint
- uaa_verify_cert

**Steps to reproduce the problem:**

Compare HTTP GET /configurations and Swagger API documentation at #/Products/get_configurations

**Versions:**

- harbor version: 2.2.0
- docker engine version: 1.5-2
- docker-compose version: 1.25.0-1

**Comment by stonezdj** [comment]
Fixed in https://github.com/goharbor/harbor/pull/14413, you could reference the latest swagger : https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L186
