### ISSUE TITLE
Missing Helm tab in Harbor UI

### ISSUE THREAD

**Issue by dev-hana** [goharbor/harbor#14446]
What can we help you?
I installed 'Harbor' with version 2.2.0.
![image](https://user-images.githubusercontent.com/46733911/111122923-0fc25900-85b2-11eb-923a-91b59811421d.png)
There is no helm chart tab.
What can I do?
And, I cant add repo in command
with error 
`.../index.yaml: 404 Not Found`

**Comment by ninjadq** [comment]
Did you installed chartmuseum?

**Comment by dev-hana** [comment]
> Did you installed chartmuseum?

I Installed chartmuseum after installed harbor.
And restart harbor

**Comment by AllForNothing** [comment]
@dev-hana Try these steps and see if it works:
1. Clear your browser cache and  reload Harbor UI
2. Use your browser debug tool to check "with_chartmuseum"  property returned by "systeminfo" API  after logging in:
![Uploading image.png…]()

**Comment by dev-hana** [comment]
> @dev-hana Try these steps and see if it works:
> 
> 1. Clear your browser cache and  reload Harbor UI
> 2. Use your browser debug tool to check "with_chartmuseum"  property returned by "systeminfo" API  after logging in:
>    ![image](https://user-images.githubusercontent.com/30999793/111243333-de8e6b00-863b-11eb-9422-68429e3197b5.png)

![image](https://user-images.githubusercontent.com/46733911/111259025-76eb1680-8661-11eb-9418-e2c422aa6e6b.png)
"with_chartmuseum" is false
How can I change it to true?

**Comment by dev-hana** [comment]
![image](https://user-images.githubusercontent.com/46733911/111259554-8028b300-8662-11eb-8fe8-b053e2c831d7.png)

I changed 'install.sh' as follows and reinstalled. but It`s still false.

**Comment by AllForNothing** [comment]
@dev-hana if "with_chartmusem" is false, it means the helm chart was not installed rightly.
Do not modify "install.sh"  directly,  you can  add  "--with-chartmuseum" to the building cli, like this:
`sudo ./install.sh --with-notary  --with-chartmuseum`

**Comment by dev-hana** [comment]
> @ dev-hana "with_chartmusem"이 거짓이면 helm 차트가 올바르게 설치되지 않았 음을 의미합니다.
> "install.sh"를 직접 수정하지 마십시오. 다음과 같이 건물 cli에 "--with-chartmuseum"을 추가 할 수 있습니다.
> `sudo ./install.sh --with-notary --with-chartmuseum`

I solve it to use `sudo ./install.sh --with-notary --with-chartmuseum`.
Thanks for the help:)
