### ISSUE TITLE
Grafana Dashboard for Harbor Exportor 

### ISSUE THREAD

**Issue by mohit94614** [goharbor/harbor#14441]
Hey team ,

Looking for a Grafana dashboard from the Harbor team for the newly introduced feature i.e Harbor Exporter.

it would be great if you can share a sample dashboard / json with all the available matrices

**Comment by gunboe** [comment]
That would be great, a good start to make personal monitor graphics!
+1

**Comment by gunboe** [comment]
That would be great, a good start to make personal monitor graphics!

**Comment by a-mccarthy** [comment]
@ninjadq, is this issue closed by your recent PR, https://github.com/goharbor/harbor/pull/14504?

**Comment by ninjadq** [comment]
Yes, thank you @a-mccarthy
