### ISSUE TITLE
jobservice.log gets flooded with failed PUSH messages to core on wrong port

### ISSUE THREAD

**Issue by codescale** [goharbor/harbor#14444]
The jobservice.log get's flooded with warning messages:

`jobservice[3584]: [WARNING] [/jobservice/hook/hook_agent.go:121]: Send hook event 'status change: job=240996962fec456ad355a57b@1615680000, status=Success' to 'http://core:8080/service/notifications/tasks/1' failed with error: Post "http://core:8080/service/notifications/tasks/1": dial tcp 192.168.16.8:8080: connect: connection refused; push hook event to the queue for retrying later`

The hook tries to contact core on `8080` although the `env` file defines `CORE_URL=https://core:8443`.

It's hard for us to tell what triggered the issue. As we updated to 2.2 and switched to internal tls communication.

**Comment by codescale** [comment]
While monitoring redis I saw this:

```
1615800446.245073 [2 192.168.48.9:35176] "ZADD" "{harbor_job_service_namespace}:hook_events" "NX" "1615800446245035647" "{\"url\":\"http://core:8080/service/notifications/tasks/1\",\"message\":\"status change: job=240996962fec456ad355a57b@1615680000, status=Success\",\"data\":{\"job_id\":\"240996962fec456ad355a57b@1615680000\",\"status\":\"Success\",\"metadata\":{\"id\":\"240996962fec456ad355a57b@1615680000\",\"status\":\"Success\",\"name\":\"SCHEDULER\",\"kind\":\"Scheduled\",\"unique\":false,\"ref_link\":\"/api/v1/jobs/240996962fec456ad355a57b@1615680000\",\"cron_spec\":\"0 0 0 * * *\",\"enqueue_time\":1615679992,\"update_time\":1615680004,\"run_at\":1615680000,\"check_in_at\":1615680004,\"web_hook_url\":\"http://core:8080/service/notifications/tasks/1\",\"upstream_job_id\":\"240996962fec456ad355a57b\",\"revision\":1615679992}},\"timestamp\":1615716064}"
1615800446.245246 [2 192.168.48.9:51682] "PING"
1615800446.245324 [2 192.168.48.9:51682] "MULTI"
1615800446.245329 [2 192.168.48.9:51682] "ZRANGE" "{harbor_job_service_namespace}:hook_events" "0" "0"
1615800446.245337 [2 192.168.48.9:51682] "ZREMRANGEBYRANK" "{harbor_job_service_namespace}:hook_events" "0" "0"
1615800446.245344 [2 192.168.48.9:51682] "EXEC"
1615800446.245451 [2 192.168.48.9:51682] "EVALSHA" "217a9d0f7fc17c55a38bd0b5627abaecb7f7346c" "1" "{harbor_job_service_namespace}:job_stats:240996962fec456ad355a57b@1615680000" "Success" "1615679992" "1615680004"
1615800446.245496 [2 lua] "hmget" "{harbor_job_service_namespace}:job_stats:240996962fec456ad355a57b@1615680000" "status" "revision" "check_in_at" "ack"
```

It seems as if there is a web-hook stuck with the old port before switching to internal-tls. Is there a way how I can remove it?

**Comment by steven-zou** [comment]
@codescale 

You're correct. The webhook url is kept in the job data that is stored in the redis. As the core URL changes, but the already existing jobs can not update the webhook. 

At present, you can clean the items under `hook_events` in redis.

I'll do some investigations to see if we can introduce some enhancements to avoid such cases happening.

**Comment by codescale** [comment]
Hi @steven-zou and thank you for the answer. Sadly I don't know anything about redis :/ Can you tell me how I can clean the items? Much appreciated! Thx

**Comment by hasonhai** [comment]
Is there any problem if we clear everything in Redis? I'm also having the same problem.

**Comment by codescale** [comment]
Hi hasonhai, I ended up doing exactly that. It was fine in our case - because the cache inside redis was not important.

**Comment by steven-zou** [comment]
@codescale / @hasonhai 

For the most time, cleaning Redis data is ok. If you have set some schedules, then you need to reset after your cleaning via the webconsole.

If the latest 2.4 is used, no further actions are needed after cleaning Redis.


I'll close this issue now. You can reopen it when you have further comments.
