### ISSUE TITLE
Registries unhealthy after upgrade to v2.2.0

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#14459]
Hello,

I have configured the Harbor in HA mode with the below configurations

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 1
Redis VM 3(Master-Slave-Slave)
Harbor Version 2.1.2
Docker version 19.0.0
docker-compose version 1.26

I have upgraded the harbor to v2.2.0. Everything is working fine but all the registries status turns to unhealthy.

Could you please help.

**Comment by AyushCloud** [comment]
I think the issue is that, i have updated the /data/secret certificates

**Comment by reasonerjt** [comment]
@AyushCloud have you figured out?

Since deploying HA via docker-compose is not tested in our pipeline, you need to make sure the configuration is correct on your side.

**Comment by AyushCloud** [comment]
It is related to expiration of the certificates. Need to configure registries again
