### ISSUE TITLE
harbor-db keeps restarting

### ISSUE THREAD

**Issue by HaoLiuHust** [goharbor/harbor#14460]
I have tried v1.5.0 and v2.1.4. they all stucked at harbor-db. According to the /va/log/harbor, 
```
The default text search configuration will be set to "english".
Mar 16 20:41:36 172.21.0.1 postgresql[83052]: Data page checksums are disabled.
Mar 16 20:41:36 172.21.0.1 postgresql[83052]: initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
Mar 16 20:41:36 172.21.0.1 postgresql[83052]: fixing permissions on existing directory /var/lib/postgresql/data ... 
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: The files belonging to this database system will be owned by user "postgres".
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: This user must also own the server process.
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: The database cluster will be initialized with locales
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   COLLATE:  en_US.UTF-8
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   CTYPE:    en_US.UTF-8
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   MESSAGES: C
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   MONETARY: C
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   NUMERIC:  C
Mar 16 20:42:38 172.21.0.1 postgresql[83052]:   TIME:     C
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: The default text search configuration will be set to "english".
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: Data page checksums are disabled.
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
Mar 16 20:42:38 172.21.0.1 postgresql[83052]: fixing permissions on existing directory /var/lib/postgresql/data ... 

```
there is a permission error

**Comment by phin1x** [comment]
The log tells you whats wrong:
```
could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
```

so the init script of postgres cannot change the persmissions to 700. this is an error caused by your underlying storage which doesn't allow the chmod.
this could be caused if the directory is not writable which is bind mounted into the container.
you can temporary change the permissions of the parent to 777 and then, if the database is up and running, change it back to its previous value.

**Comment by reasonerjt** [comment]
Thanks @phin1x

**Comment by HaoLiuHust** [comment]
> The log tells you whats wrong:
> 
> ```
> could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
> ```
> 
> so the init script of postgres cannot change the persmissions to 700. this is an error caused by your underlying storage which doesn't allow the chmod.
> this could be caused if the directory is not writable which is bind mounted into the container.
> you can temporary change the permissions of the parent to 777 and then, if the database is up and running, change it back to its previous value.

actually, there is no folder "/var/lib/postgresql/data" at all... I have set it successfully on another machine，I will survey this problem when I have some time

**Comment by phin1x** [comment]
/var/lib/postgresql/data is the directory, which will be created in the db container. you have to look at the directory which is mountet into your container.
