### ISSUE TITLE
exporter does not support TLS even provide key/cert/tls_enabled flag

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#14475]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

provided TLS related information to harbor exporter pod, it is shown as below:

=======
2021-03-18T16:13:01+08:00 [INFO] [/cmd/exporter/main.go:62]: Starting harbor_exporter with port=8001 path=/metrics metrics=true max_request=0 **tls=true cert=/harbor/tls/tls.crt key=/harbor/tls/tls.key cache_time=0 clean_internal=0**

===
but the exporter server did not listen on https, only on http, from the code, please enhance that code to support https.

src/pkg/exporter/exporter.go:

func newServer(opt *Opt, r *prometheus.Registry) *http.Server {
        exporterMux := http.NewServeMux()
        exporterMux.Handle(opt.MetricsPath, promhttp.Handler())
        exporterMux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                w.Write([]byte(`<html>
                <head><title>Harbor Exporter</title></head>
                <body>
                <h1>Harbor Exporter</h1>
                <p><a href="` + opt.MetricsPath + `">Metrics</a></p>
                </body>
                </html>`))
        })

        return &http.Server{
                Addr:    fmt.Sprintf(":%d", opt.Port),
                Handler: exporterMux,
        }
}

thanks.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by matgn** [comment]
Same here ! 
"Get SSL_ERROR_RX_RECORD_TOO_LONG"
"ssl3_get_record:wrong version number"

Harbor Version  2.1.0
docker engine version 18.09.6
docker-compose version 1.22.0

Is there a way to workaround ? 

`
https:
  port: 443
  certificate: /root/cert/hb.crt
  private_key: /root/cert/hb.key

metric:
  enabled: true
  port: 9101
  path: /metrics
`

**Comment by danielzhanghl** [comment]
hi, harbor team, 
any plan to support tls for harbor exporter?

**Comment by danielzhanghl** [comment]
just close it as no response, choose to use nginx like proxy...
