### ISSUE TITLE
Getting error while trying to sign image with docker push

### ISSUE THREAD

**Issue by lyoumar** [goharbor/harbor#14473]
When i try to push the image with DOCKER_CONTENT_TRUST=1, i am getting this same issue:
Signing and pushing trust metadata
Error: error contacting notary server: x509: certificate signed by unknown authority.

The test connection between nginx et notary-server loook like this:
openssl s_client -connect notary-server:4443 -CAfile /etc/nginx/cert/ca.crt -no_ssl3 -no_ssl2
CONNECTED(00000003)

**Comment by reasonerjt** [comment]
See the section "Configure Notary Content Trust"
https://goharbor.io/docs/2.2.0/working-with-projects/working-with-images/pulling-pushing-images/

**Comment by lyoumar** [comment]
Thanks for your feedback. This is what I have observed after executing following commands.
Login Succeeded
$ cp ca.crt  /etc/docker/certs.d/
$ cp ca.crt   $HOME/.docker/tls/notary.staging.nonprod.cloud.res.bngf.local
export DOCKER_CONTENT_TRUST=0
docker pull docker/trusttest

export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=https://notary.staging.nonprod.cloud.res.bngf.local
export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="mypassphrase123"
export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE="rootpassphrase123"
docker tag docker/trusttest portail.staging.nonprod.cloud.res.bngf.local/library/trust:latest-secure 
docker push  portail.staging.nonprod.cloud.res.bngf.local/library/trust:latest-secure 

$ docker push portail.staging.nonprod.cloud.res.bngf.local/library/trust:latest-secure
The push refers to repository [portail.staging.nonprod.cloud.res.bngf.local/library/trust]
5f70bf18a086: Layer already exists 
c22f7bc058a9: Layer already exists 
latest-secure: digest: sha256:7034d197b82fcb07299fda8b05c91d1601ce64f31bc102b1345d03a2953d210a size: 734
Signing and pushing trust metadata
Error: trust data missing for remote repository portail.staging.6019.nonprod.cloud.res.bngf.local/library/trust or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized?

**Comment by lyoumar** [comment]
The cert in folder ~/.docker/tls/notary.staging.6019.nonprod.cloud.res.bngf.local/ca.crt is the same as located into the https://notary.staging.nonprod.cloud.res.bngf.local 

$ openssl x509 -text -noout -in  ~/.docker/tls/notary.staging.6019.nonprod.cloud.res.bngf.local/ca.crt
 ----
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 13443237070596470767 (0xba8ff8e3f043f7ef)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Harbor Notary CA
        Validity
            Not Before: Mar 15 14:53:56 2021 GMT
            Not After : Mar 13 14:53:56 2031 GMT
        Subject: CN=Harbor Notary CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:be:c6:28:64:92:cc:70:0b:bf:83:72:86:15:f5:
                    38:ab:09:4b:db:23:89:64:a0:0d:8f:3c:9f:ea:2d:
                    0b:17:ea:aa:58:31:67:71:48:e6:58:b3:53:c0:9c:
                    54:b1:a1:75:a6:98:a5:9f:dc:24:bd:5b:21:e7:b3:
                    7f:54:56:c9:d7:7d:ee:ff:16:f9:46:9c:e7:9b:e0:
                    f2:0c:01:a3:69:61:7f:9a:c4:20:37:34:f5:5b:6d:
                    e4:09:24:6f:3e:47:5e:93:31:0d:e1:26:3f:56:c1:
                    6f:e9:d5:b2:e0:f9:a4:94:1d:d8:69:5d:99:ae:f8:
                    9f:9f:2a:0a:e8:db:51:5c:dc:47:7a:7c:87:70:87:
                    dd:57:45:97:82:e2:1b:09:a8:5d:a8:95:67:a5:bc:
                    53:10:21:11:64:a9:7b:d2:c1:7b:db:82:74:6b:16:
                    9d:89:d0:77:55:e2:d9:0e:95:88:12:a4:1e:c0:77:
                    d4:c9:b4:bb:53:1c:50:d5:28:8c:2d:80:e4:2b:fd:
                    ad:a6:71:0d:1e:36:79:4c:4a:e1:25:dd:b1:c0:30:
                    b1:42:d8:d0:c3:e3:5e:c6:d2:4f:2e:5f:b1:2d:91:
                    8c:02:b1:61:22:3f:ff:26:c6:8d:f6:de:67:31:a6:
                    47:a3:12:f8:53:91:62:27:a4:81:ab:7a:d1:03:cc:
                    e6:86:1e:2e:af:45:93:95:e2:25:c0:00:47:0a:3c:
                    fc:1f:ab:e5:cc:63:13:30:ee:73:24:14:7e:06:69:
                    4f:37:5c:50:9e:6c:4a:79:78:a9:c4:92:61:74:7a:
                    0b:c6:b1:31:e2:31:ff:d2:f3:1d:02:2c:ba:c2:9b:
                    62:cc:88:42:b9:28:1c:d1:57:bd:96:38:f6:11:b2:
                    fd:ce:75:25:71:27:c7:98:a7:3d:14:2a:ab:b9:21:
                    71:6c:e9:8d:c5:22:9a:ac:69:f6:23:51:06:6f:bd:
                    d9:8e:85:6d:a7:08:d0:22:50:52:4f:7d:1a:0c:95:
                    dd:d6:9a:25:69:59:5b:3f:be:03:36:e3:be:36:04:
                    c5:c3:e5:90:64:3e:c8:5e:7d:31:07:a8:ff:08:34:
                    79:29:0c:07:01:86:4d:6f:e9:a1:ef:b0:de:c1:90:
                    3a:fd:bc:b7:03:bc:81:5c:a4:ff:62:ae:51:51:52:
                    9f:cd:a6:a1:06:f2:3c:c5:c9:7b:16:51:fb:9c:a9:
                    35:b5:6a:3f:c1:13:4c:5f:b2:e3:44:13:82:fb:39:
                    11:e8:57:46:e1:77:9c:ab:22:32:57:a6:bf:d9:bd:
                    50:19:77:2b:b1:17:73:b0:a6:21:4d:9c:1e:97:4b:
                    7a:4b:8e:fa:0f:83:8d:45:9a:e7:5a:1a:12:7b:ba:
                    5b:41:3d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
            X509v3 Key Usage: critical
                Non Repudiation, Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                30:26:A0:8D:F6:2B:4E:DB:DF:C0:BA:9D:49:29:17:95:D7:EF:C3:9F
    Signature Algorithm: sha256WithRSAEncryption
         ae:fb:a0:33:cf:a2:17:ce:71:2e:d2:e9:2b:af:64:e4:15:09:
         33:9a:06:4b:c7:20:ea:85:a3:5d:ea:17:1c:ec:50:80:b9:02:
         03:84:60:f5:6e:f1:2d:d2:77:91:e1:b3:86:c5:da:9b:56:ed:
         95:f8:cf:14:8a:91:ab:1d:51:aa:66:49:9f:cc:90:68:38:d6:
         31:74:9b:33:e1:05:6e:b9:70:8a:14:aa:20:44:24:0a:7c:ea:
         1d:e1:c8:62:76:ad:66:5c:3b:ca:48:d1:d2:99:99:87:7f:fc:
         e0:27:60:12:4f:38:3f:98:09:a6:bd:12:b3:4b:d7:b8:76:29:
         ec:31:09:6c:7e:99:5d:28:01:63:cd:8c:14:c1:dd:49:0f:b0:
         00:08:f3:4e:5d:0a:f1:39:98:3a:f8:1e:d4:a9:9f:86:34:54:
         0e:ce:ba:30:82:c9:bd:95:ce:ee:95:72:08:c3:ed:e1:5e:4f:
         0e:7c:5c:15:11:6b:b0:bf:ad:88:ff:4a:a3:44:e5:ba:d3:ca:
         db:5e:ab:a9:ec:41:8c:57:f7:20:62:4f:24:1a:77:e8:bf:50:
         8f:70:9a:d4:a6:fa:11:9e:48:b6:ed:63:b2:fb:56:ad:7c:dc:
         11:09:7e:90:67:82:f5:8b:23:a4:56:77:0f:b0:00:06:89:54:
         a6:30:93:ce:29:c9:f2:ba:96:d7:9e:d3:52:6d:ce:99:f2:08:
         78:b3:de:a0:87:3b:e1:c7:52:27:b2:e6:ce:02:c6:35:b7:4b:
         8c:ca:90:42:84:93:33:8b:8d:ec:c8:dc:fc:69:70:d9:98:81:
         9e:5b:30:57:96:5b:bd:2b:08:d9:8f:a9:db:02:67:98:51:50:
         9e:26:da:9e:fd:7b:ee:b2:2f:b1:73:20:df:6b:bb:37:e4:c2:
         e6:3f:1b:22:98:55:46:5d:63:8f:17:bd:81:a5:68:9c:9d:b5:
         ae:58:dd:05:28:73:a1:c0:4e:9b:85:c1:b8:db:4d:59:64:91:
         6c:be:55:6c:9c:d1:ab:9d:69:1d:05:dc:fd:bb:5b:5e:11:45:
         da:b3:a5:a4:f4:04:b6:ac:53:96:0e:a6:f7:0e:21:6d:b1:60:
         bc:6c:f9:d3:9f:da:e1:c1:39:da:01:9f:57:51:8e:1d:9b:cc:
         46:e8:f7:c6:ca:9f:4c:ab:f0:27:3f:12:14:9f:e0:54:36:9e:
         01:11:bb:33:a6:b8:5e:6f:53:2a:46:9a:9f:b6:28:e2:42:9b:
         6a:db:91:d1:ce:05:2d:db:cc:27:f6:b7:0d:4c:7b:3d:ea:c2:
         67:ca:81:2d:b0:55:43:29:f5:32:45:34:43:8d:6d:bd:2f:ab:
         2c:96:32:2d:88:99:f0:ee
----
Verify insight the pods 
$ k exec -it notary-server-65fb888898-lht9r sh
sh-4.4$ openssl x509 -text -noout -in /etc/ssl/notary/ca.crt
----
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ba:8f:f8:e3:f0:43:f7:ef
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = Harbor Notary CA
        Validity
            Not Before: Mar 15 14:53:56 2021 GMT
            Not After : Mar 13 14:53:56 2031 GMT
        Subject: CN = Harbor Notary CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:be:c6:28:64:92:cc:70:0b:bf:83:72:86:15:f5:
                    38:ab:09:4b:db:23:89:64:a0:0d:8f:3c:9f:ea:2d:
                    0b:17:ea:aa:58:31:67:71:48:e6:58:b3:53:c0:9c:
                    54:b1:a1:75:a6:98:a5:9f:dc:24:bd:5b:21:e7:b3:
                    7f:54:56:c9:d7:7d:ee:ff:16:f9:46:9c:e7:9b:e0:
                    f2:0c:01:a3:69:61:7f:9a:c4:20:37:34:f5:5b:6d:
                    e4:09:24:6f:3e:47:5e:93:31:0d:e1:26:3f:56:c1:
                    6f:e9:d5:b2:e0:f9:a4:94:1d:d8:69:5d:99:ae:f8:
                    9f:9f:2a:0a:e8:db:51:5c:dc:47:7a:7c:87:70:87:
                    dd:57:45:97:82:e2:1b:09:a8:5d:a8:95:67:a5:bc:
                    53:10:21:11:64:a9:7b:d2:c1:7b:db:82:74:6b:16:
                    9d:89:d0:77:55:e2:d9:0e:95:88:12:a4:1e:c0:77:
                    d4:c9:b4:bb:53:1c:50:d5:28:8c:2d:80:e4:2b:fd:
                    ad:a6:71:0d:1e:36:79:4c:4a:e1:25:dd:b1:c0:30:
                    b1:42:d8:d0:c3:e3:5e:c6:d2:4f:2e:5f:b1:2d:91:
                    8c:02:b1:61:22:3f:ff:26:c6:8d:f6:de:67:31:a6:
                    47:a3:12:f8:53:91:62:27:a4:81:ab:7a:d1:03:cc:
                    e6:86:1e:2e:af:45:93:95:e2:25:c0:00:47:0a:3c:
                    fc:1f:ab:e5:cc:63:13:30:ee:73:24:14:7e:06:69:
                    4f:37:5c:50:9e:6c:4a:79:78:a9:c4:92:61:74:7a:
                    0b:c6:b1:31:e2:31:ff:d2:f3:1d:02:2c:ba:c2:9b:
                    62:cc:88:42:b9:28:1c:d1:57:bd:96:38:f6:11:b2:
                    fd:ce:75:25:71:27:c7:98:a7:3d:14:2a:ab:b9:21:
                    71:6c:e9:8d:c5:22:9a:ac:69:f6:23:51:06:6f:bd:
                    d9:8e:85:6d:a7:08:d0:22:50:52:4f:7d:1a:0c:95:
                    dd:d6:9a:25:69:59:5b:3f:be:03:36:e3:be:36:04:
                    c5:c3:e5:90:64:3e:c8:5e:7d:31:07:a8:ff:08:34:
                    79:29:0c:07:01:86:4d:6f:e9:a1:ef:b0:de:c1:90:
                    3a:fd:bc:b7:03:bc:81:5c:a4:ff:62:ae:51:51:52:
                    9f:cd:a6:a1:06:f2:3c:c5:c9:7b:16:51:fb:9c:a9:
                    35:b5:6a:3f:c1:13:4c:5f:b2:e3:44:13:82:fb:39:
                    11:e8:57:46:e1:77:9c:ab:22:32:57:a6:bf:d9:bd:
                    50:19:77:2b:b1:17:73:b0:a6:21:4d:9c:1e:97:4b:
                    7a:4b:8e:fa:0f:83:8d:45:9a:e7:5a:1a:12:7b:ba:
                    5b:41:3d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
            X509v3 Key Usage: critical
                Non Repudiation, Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                30:26:A0:8D:F6:2B:4E:DB:DF:C0:BA:9D:49:29:17:95:D7:EF:C3:9F
    Signature Algorithm: sha256WithRSAEncryption
         ae:fb:a0:33:cf:a2:17:ce:71:2e:d2:e9:2b:af:64:e4:15:09:
         33:9a:06:4b:c7:20:ea:85:a3:5d:ea:17:1c:ec:50:80:b9:02:
         03:84:60:f5:6e:f1:2d:d2:77:91:e1:b3:86:c5:da:9b:56:ed:
         95:f8:cf:14:8a:91:ab:1d:51:aa:66:49:9f:cc:90:68:38:d6:
         31:74:9b:33:e1:05:6e:b9:70:8a:14:aa:20:44:24:0a:7c:ea:
         1d:e1:c8:62:76:ad:66:5c:3b:ca:48:d1:d2:99:99:87:7f:fc:
         e0:27:60:12:4f:38:3f:98:09:a6:bd:12:b3:4b:d7:b8:76:29:
         ec:31:09:6c:7e:99:5d:28:01:63:cd:8c:14:c1:dd:49:0f:b0:
         00:08:f3:4e:5d:0a:f1:39:98:3a:f8:1e:d4:a9:9f:86:34:54:
         0e:ce:ba:30:82:c9:bd:95:ce:ee:95:72:08:c3:ed:e1:5e:4f:
         0e:7c:5c:15:11:6b:b0:bf:ad:88:ff:4a:a3:44:e5:ba:d3:ca:
         db:5e:ab:a9:ec:41:8c:57:f7:20:62:4f:24:1a:77:e8:bf:50:
         8f:70:9a:d4:a6:fa:11:9e:48:b6:ed:63:b2:fb:56:ad:7c:dc:
         11:09:7e:90:67:82:f5:8b:23:a4:56:77:0f:b0:00:06:89:54:
         a6:30:93:ce:29:c9:f2:ba:96:d7:9e:d3:52:6d:ce:99:f2:08:
         78:b3:de:a0:87:3b:e1:c7:52:27:b2:e6:ce:02:c6:35:b7:4b:
         8c:ca:90:42:84:93:33:8b:8d:ec:c8:dc:fc:69:70:d9:98:81:
         9e:5b:30:57:96:5b:bd:2b:08:d9:8f:a9:db:02:67:98:51:50:
         9e:26:da:9e:fd:7b:ee:b2:2f:b1:73:20:df:6b:bb:37:e4:c2:
         e6:3f:1b:22:98:55:46:5d:63:8f:17:bd:81:a5:68:9c:9d:b5:
         ae:58:dd:05:28:73:a1:c0:4e:9b:85:c1:b8:db:4d:59:64:91:
         6c:be:55:6c:9c:d1:ab:9d:69:1d:05:dc:fd:bb:5b:5e:11:45:
         da:b3:a5:a4:f4:04:b6:ac:53:96:0e:a6:f7:0e:21:6d:b1:60:
         bc:6c:f9:d3:9f:da:e1:c1:39:da:01:9f:57:51:8e:1d:9b:cc:
         46:e8:f7:c6:ca:9f:4c:ab:f0:27:3f:12:14:9f:e0:54:36:9e:
         01:11:bb:33:a6:b8:5e:6f:53:2a:46:9a:9f:b6:28:e2:42:9b:
         6a:db:91:d1:ce:05:2d:db:cc:27:f6:b7:0d:4c:7b:3d:ea:c2:
         67:ca:81:2d:b0:55:43:29:f5:32:45:34:43:8d:6d:bd:2f:ab:
         2c:96:32:2d:88:99:f0:ee
---

**Comment by lyoumar** [comment]
I also checked the connection between the pods  nginx and notary-server and i find this.
sh-4.4$ openssl s_client -CAfile /etc/nginx/cert/ca.crt -connect notary-server:4443
CONNECTED(00000003)
139964286344832:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 307 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1616782575
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Comment by lyoumar** [comment]
I wondering if the issue is related in my self signed certificates, i have follow all the documentation from harbor and i tried many time without any succes to signed the image. I have deployed harbor in kubernetes cluster, i am using istio for ingress gateway to send all the  traffic to my nginx. I have the self signed cert for nginx and the self signed cert for notary. I not am sure  which one i should setup throught the folders:
~/.docker/tls/notary.staging.6019.nonprod.cloud.res.bngf.local/
/etc/docker/certs.d/notary.staging.6019.nonprod.cloud.res.bngf.local/

**Comment by reasonerjt** [comment]
@lyoumar sorry for the late resposne.

The error in this comment:
https://github.com/goharbor/harbor/issues/14473#issuecomment-804990108

```
Signing and pushing trust metadata
Enter passphrase for root key with ID a29c031:
Enter passphrase for new repository key with ID 0e5f932:
Repeat passphrase for new repository key with ID 0e5f932:
Error: trust data missing for remote repository portail.staging.nonprod.cloud.res.bngf.local/library/trust or remote repository not found: timestamp key trust data unavailable. Has a notary repository been initialized?
```
It indicates the cert checking is passed, because client can access to the notary server.

I also noticed
```
$docker push portail.staging.nonprod.cloud.res.bngf.local/library/trust:latest-secure
The push refers to repository [portail.staging.6019.nonprod.cloud.res.bngf.local/library/trust]
```

I'm not sure what's the magic but the URLs are different, this may cause the error above.

**Comment by reasonerjt** [comment]
@lyoumar let me know if we need to keep this open.
