### ISSUE TITLE
 add ''Docker Registry" type in proxy cache

### ISSUE THREAD

**Issue by cyrilcros** [goharbor/harbor#14477]
You can't directly use some registries like GCR as an anonymous proxy cache because they require a JSON token.
@bitsf suggested to use a "Docker registry" endpoint type, which does allow to use GCR without a token. However, it isn't currently possible to use those as a proxy cache, but that support could be added.

Here are the pull requests that were used for adding Quay, for reference: #13897 and for the UI #13902
Goes with #14234 I guess

-----------------------
**I leave the previous issue open, as something was wrong with GCR endpoint configuration.**

for anonymous case, you just need to use the ''Docker Registry" type
@stonezdj consider to add ''Docker Registry" type in proxy cache later

_Originally posted by @bitsf in https://github.com/goharbor/harbor/issues/14326#issuecomment-801828443_

**Comment by Hokwang** [comment]
@bitsf 
Inconsistency  with guide for quay (https://github.com/goharbor/harbor/issues/13540#issuecomment-735254165)
and comment for gcr 
as @cyrilcros said.

**Comment by Hokwang** [comment]
very weired,
I created registry like below,
select Quay, and endpoint is asia.gcr.io, and no access id, no access secret
![image](https://user-images.githubusercontent.com/1247030/111735305-283ab800-88bf-11eb-999f-ab3da0a78f70.png)


OMG, it works.

@stonezdj @bitsf 
I think your team need to decide that create `docker registry` type or
provide remove access id and access secret in `gcr` type.
