### ISSUE TITLE
cannot validate certificate for 192.168.8.121 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by LeeZBug** [goharbor/harbor#14483]
![problem](https://user-images.githubusercontent.com/37901768/111873779-0b8ca600-89cd-11eb-83f5-7b9c95c30449.jpg)
    I follow this page（https://goharbor.io/docs/2.0.0/install-config/configure-https/）to configure my harbor an docker. But when I docker login, type my username and password, it show me: Error response from daemon: Get https://lizhejie.docker.com/v2/: Get https://192.168.8.121/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: x509: cannot validate certificate for 192.168.8.121 because it doesn't contain any IP SANs.
   I have copied three ca files( mydomain.cert, mydomainkey.key ca.crt) into 192.168.8.121's machine(my docker client)
,and I can curl my harbor host by https (like jpg).

**Comment by reasonerjt** [comment]
@LeeZBug  How did you install Harbor? via docker-compose?

**Comment by bitsf** [comment]
This error means your server cert is not signed for IP 192.168.8.121
you can run `openssl x509 -text -in mydomain.cert -noout` to check if `X509v3 Subject Alternative Name` part contains `IP Address: 192.168.8.121`
and you should also notice whether you set correct values in harbor.yml, `hostname` `https` `external_url`

**Comment by hj00494yong** [comment]
i resolve this problem  by  set  DNS.2=ip in v3.ext , then recreate  certificates

![Uploading image.png…]()

**Comment by hj00494yong** [comment]
you can try it ,i think its very very useful and can resolve you problem ,beacause i success
