### ISSUE TITLE
Unable to send emails using Office 356 smtp server

### ISSUE THREAD

**Issue by glego** [goharbor/harbor#14480]
**Expected behavior and actual behavior:**
Unable to send emails using Office 356 smtp server with STARTTLS encryption.

**Steps to reproduce the problem:**

* Email Server: `smtp.office365.com`
* Email Server Port: `587`
* Email Username: `username`
* Email Password: `password`
* Email From: `admin <noreply@domain.com>`
* Email SSL: `True`
* Verify Certificate: `True`

Reference: https://support.microsoft.com/en-us/office/pop-imap-and-stmp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

**Versions:**

- harbor version: v2.2.0-ec0ba116
- docker engine version: -
- docker-compose version: -

**Additional context:**

- **Log Files**

```
2021-03-19T21:19:19Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
2021-03-19T21:19:21Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
2021-03-19T21:22:34Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
```

#5757

**Comment by snoopotic** [comment]
Hi. You can repoduce it as well, setting Port 25 and check/uncheck Email SSL. If you disable it will Try TLS but cor.log throws:
`core[684]: 2021-04-20T11:47:44Z [ERROR] [/core/api/email.go:113]: failed to ping email server: 535 5.7.8 Error: authentication failed: no mechanism available`

if you enable ssl on Port 25 it throws known reported error...

**Comment by Antiarchitect** [comment]
We also suffering from this.

**Comment by antoineozenne** [comment]
Same here.

**Comment by pinaki124** [comment]
We have the same issue using Office365 smtp.office365.com on Port 587

```
2021-12-10T23:55:41Z [ERROR] [/core/api/email.go:115]: failed to ping email server: 504 5.7.4 Unrecognized authentication type [CO1PR15CA0097.namprd15.prod.outlook.com]
2021-12-10T23:51:01Z [ERROR] [/core/api/email.go:115]: failed to ping email server: tls: first record does not look like a TLS handshake
2021-12-10T23:49:59Z [ERROR] [/core/api/email.go:115]: failed to ping email server: 504 5.7.4 Unrecognized authentication type [MW4PR03CA0043.namprd03.prod.outlook.com]
```

**Comment by antoineozenne** [comment]
I think this issue is really important because many companies use Exchange.

**Comment by RobertBoyd** [comment]
I'm seeing the same issue with SMTP setup with Office 365 on port 587 with a failed ping error. Like @pinaki124 I am also getting the failed ping. The same credentials work in other applications to send mail via SMTP via Office 365/ Exchange.

**Comment by samox73** [comment]
would also love an update if there is anybody currently working on this.

**Comment by snoopotic** [comment]
This issue is not stale. We just don't have more to say. What do you need to fix that? 😅

**Comment by Antiarchitect** [comment]
Issue is not stale.

**Comment by timbrown5** [comment]
We are seeing this also 😞

**Comment by timbrown5** [comment]
I believe this is still an issue.

**Comment by Roia5** [comment]
Still an issue

**Comment by AllForNothing** [comment]
Closing is as of #17683

**Comment by cwilso03** [comment]
@AllForNothing - Not having had time to go spelunking into the specific changes in #17683, but rather just reading the title of that issue, is the 'fix" that Harbor no longer has any ability to send email?

**Comment by AllForNothing** [comment]
@cwilso03 Yes. since v2.3 the e-mail configuration became useless. And since v2.7, we removed it from both the UI and the back-end.
