### ISSUE TITLE
Unable to delete repo from s3 bucket

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor#14488]
Chart version: harbor-1.6.0                    
Harbor version: 2.2.0

Hi all,
I'm trying to delete haproxy repository permanently from my project but when I perform the delete action from Harbor UI on "Repositories" section and I click on "GC Now" the section is still present on s3 bucket (cloudian in my case) as you can see

`$  s3cmd -c .s3cfg ls `s3://<my_bucket>/docker/registry/v2/repositories/sun/haproxy/`

                          `DIR`  `s3://<my_bucket>/docker/registry/v2/repositories/sun/haproxy/_layers/`
                          `DIR`  `s3://<my_bucket>/docker/registry/v2/repositories/sun/haproxy/_manifests/`

Any idea or suggestion?

Thanks,
Gabriele

**Comment by wy65701436** [comment]
did you find the digest of expecte layer & manifest in the GC.log? In 2.2, we have a 2-hour time window  to reserve the recent uploaded layers. Garbage collection does not sweep the manifest & blob files that have a timestamp in the time window.

**Comment by gabrilabs75** [comment]
Hi,
I tried right now to delete haproxy from repositories section.
Here you can find the output of GC.

...
...
...
2021-03-25T08:29:04Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:222]: blob eligible for deletion: sha256:d7da7ee4e55eb8271b301f80c245eaef7b87ad6f73df7f8e15e41b9b11c76cbb
2021-03-25T08:29:04Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:234]: 6 blobs and 1 manifests eligible for deletion
2021-03-25T08:29:04Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:235]: The GC could free up 3 MB space, the size is a rough estimation.
2021-03-25T08:29:04Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:173]: success to run gc in job.

Anyway I'm still found the image on s3 bucket:

$ s3cmd -c .s3cfg ls -l s3://<my_bucket>/docker/registry/v2/repositories/<my_repo>/

                          DIR                                                    s3://<my_bucket>/docker/registry/v2/repositories/<my_repo>/haproxy/

                          DIR                                                    s3://<my_bucket>/docker/registry/v2/repositories/<my_repo>/grafana/            
                          DIR                                                    s3://<my_bucket>/docker/registry/v2/repositories/<my_repo>/memcached/
                          DIR                                                    s3://<my_bucket>/docker/registry/v2/repositories/<my_repo>/nginx/

As you can see i found other image repo deleted from harbor registry days ago. (grafana,memcached for example)

**Comment by gabrilabs75** [comment]
Hi all,
do you have any update about this issue?

**Comment by wy65701436** [comment]
I tried on my S3 env, all of data can be removed by GC. What's your S3 version? And is there any file in the directory(`s3://<my_bucket>/docker/registry/v2/repositories/sun/haproxy/_layers/`)? or just a empty folder?
