### ISSUE TITLE
nginx 1.16.1 is EOL. Please upgrade.

### ISSUE THREAD

**Issue by aquaherd** [goharbor/harbor#14489]
Using EOL versions of internet facing SW.

**Steps to reproduce the problem:**
Install latest stable harbor.
Current version 1.16.1 has 'Request Smuggling vulnearibility'.

**Versions:**

- harbor version: 2.1.4
- docker engine version: 20.10.05
- docker-compose version: 1.21.0

**Additional context:**
Please upgrade nginx to at least 1.18 or provide instructions on how to do so, since composition of used nginx is not documented.

**Comment by phin1x** [comment]
harbor is using photon as a base image. the nginx comes from the photon packages repo and is maintained by the photon team until photon1 goes eol.
there is a issue to upgrade to photon4 with the 2.3.0 release #14395.

duplicted to #13341

**Comment by aquaherd** [comment]
Thank you.
