### ISSUE TITLE
Remove OIDC user

### ISSUE THREAD

**Issue by j-zimnowoda** [goharbor/harbor#14496]
What can we help you?
Removing OIDC user is disabled in Harbor portal. Why?

**Comment by reasonerjt** [comment]
If it's deleted on Harbor side, when the same user gets onboarded via external ID manager again, should we consider it the same user or a different one?  You can't assign the same old ID to the new user.

**Comment by j-zimnowoda** [comment]
@reasonerjt If a user is removed from harbor then there shouldn't be any information about that user. Therefore I would consider an incoming user as a new one?.

**Comment by reasonerjt** [comment]
I think this has been implemented in v2.4 
@stonezdj please confirm.

**Comment by stonezdj** [comment]
fixed in https://github.com/goharbor/harbor/pull/15247
