### ISSUE TITLE
How to edit a database user?

### ISSUE THREAD

**Issue by blaluc** [goharbor/harbor#14506]
Hello,
I've just installed Harbor Version v2.1.3-b6de84c5.
I've created some users (database users) filling the required fields (email, first name and last name).
Once inserted their appear in the list but it seems there's no way to edit the inserted data, the only options available after selecting one entry in the list are "reset password" and "delete".
How can I open a detail form to view/edit the previously inserted fields?
Many thanks in advance

**Comment by reasonerjt** [comment]
Currently via UI the user has to login and edit his own profile.

**Comment by reasonerjt** [comment]
Closing the issue given no further questions.
