### ISSUE TITLE
Access to 'GET /projects/<name>' denied for robot account although permissions are set

### ISSUE THREAD

**Issue by defreng** [goharbor/harbor#14512]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
With a system-level robot account and the following permissions, I receive a 403 FORBIDDEN response when trying to access the `GET /projects/existing_name` API.

```
{
    'kind': 'system',
    'namespace': '/',
    'access': [
        {'resource': 'project', 'action': 'list'},
        {'resource': 'project', 'action': 'read'},
    ]
},
{
    'kind': 'project',
    'namespace': '*',
    'access': [
        {'resource': 'repository', 'action': 'list'},
        {'resource': 'artifact', 'action': 'list'},
        {'resource': 'artifact', 'action': 'read'},
        {'resource': 'artifact', 'action': 'create'},
    ]
}
```

On the other hand, listing projects using `GET /projects` works fine.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.0

**Comment by defreng** [comment]
I just realized a better workaround, but even hackier by setting the following permission:

```
{
    'kind': 'project',
    'namespace': '*',
    'access': [
        # FIXME: Super hack.
        # The question mark will be interpreted as part of the regex in Harbor RBAC for resource matching and
        # negate the unnecessary '/'. Regex will become '/project/.*/?', which matches the requested resource
        # for reading a project, e.g. '/project/37'
        {'resource': '?', 'action': 'read'},
    ]
},
```

Notice that the permission must be set as one of kind `project`, not system as mentioned in the initial post.

**Comment by wy65701436** [comment]
if you want the robot to have the list permission of all the projects, just try with:

```
{
    'kind': 'project',
    'namespace': '*',
    'access': [
        {'resource': '', 'action': 'list'}, --- let the resource be empty.
    ]
}

```
with a particular project, with:

```
{
    'kind': 'project',
    'namespace': 'project_name',
    'access': [
        {'resource': '', 'action': 'list'},
    ]
}
```

**Comment by defreng** [comment]
I'm actually not trying to list all projects - but to read a specific one (to get the project ID from its name).

**Comment by wy65701436** [comment]
@defreng the above comment helps?

**Comment by poblahblahblah** [comment]
The only way I've found that I can use a robot user to list projects via the API is with the following permission set:

```
{
   "name":"service.test1",
   "duration":30,
   "description":"service.test2",
   "disable":false,
   "level":"system",
   "permissions":[
      {
         "kind":"system",
         "namespace": "/",
         "access":[
            {
               "resource":"project",
               "action":"list"
            },
            {
              "resource":"project",
              "action":"read"
            }
         ]
      }
   ]
}
```

This user can hit /api/v2.0/projects and get a list of the projects just fine.

My problem now, and I think it's within the spirit of this ticket, is that I can't read information about the project itself, e.g. I get a FORBIDDEN if I go to /api/v2.0/projects/5/members.

**Comment by defreng** [comment]
@poblahblahblah yes, you're right... Listing projects works with the permissions you mentioned (the "list" permission is the key here).

However, getting a specific project (e.g. "GET /project/myproject") does not work.

@wy65701436 unfortunately the permission set you mentioned does not help with that.

**Comment by codergs** [comment]
I can attest that listing repository on a given project is broken on 2.2.1 with any combination of permission access on project and system level namespace on a system account is also not working.

**Comment by defreng** [comment]
@codergs as a workaround you can try the permission set from this comment:
https://github.com/goharbor/harbor/issues/14512#issuecomment-807650475

**Comment by phin1x** [comment]
we hit the same problem and digged a little bit into the rbac system of harbor

there are two kind of priviliges, system level privs and project level privs. you can assign both to a robot account, but when the polivicies gets evalutated the policies are splitted into a list of system level and a list of project level list. then harbor checks if the amout of system level privileges is greater then zero. if thats the case harbor discards all project level privileges. so you need robot accounts, one with only system level privileges and one with only project level robot accounts.

we also hit some other bugs where a robot account cannot create projects or cannot work with projects.

**Comment by codergs** [comment]
yes @phin1x, this worked for us. 
```
{
  "id": REDACTED,
  "level": "system",
  "name": "REDACTED",
  "permissions": [
    {
        kind: "project", 
        namespace: "REDACTED",
        access: [
            {
                "resource":"repository",
                "action":"list"
            },
            {
                "action": "read",
                "resource": "artifact"
            },
            {
                "action": "list",
                "resource": "artifact"
            },
            {
                "action": "read",
                "resource": "tag"
            },
            {
                "action": "list",
                "resource": "tag"
            },
            {
                "action": "read",
                "resource": "artifact-addition"
            },
            {
                "action": "list",
                "resource": "artifact-addition"
            }
        ]
    }
  ]
}
```

**Comment by phin1x** [comment]
@codergs we came up with somethings similar. we created two robot account because we need to manage projects and robot account through one api.

**Comment by SimonAlling** [comment]
Same problem here.

### System permissions

<details>
<summary>📃 <code>robot.json</code></summary>

```json
{
  "disable": false,
  "duration": -1,
  "editable": true,
  "expires_at": -1,
  "id": 133742,
  "level": "system",
  "name": "robot-glados",
  "permissions": [
    {
      "access": [
        {
          "action": "list",
          "resource": "project"
        }
      ],
      "kind": "system",
      "namespace": "/"
    }
  ]
}
```
</details>

```console
$ curl -u "robot-glados:${GLADOS_PASSWORD}" -X GET "${HARBOR_URL}/api/v2.0/projects" -H "Accept: application/json" --silent
[{"chart_count":1,"creation_time":…
```

### Project permissions

<details>
<summary>📃 <code>robot.json</code></summary>

```json
{
  "disable": false,
  "duration": -1,
  "editable": true,
  "expires_at": -1,
  "id": 133742,
  "level": "system",
  "name": "robot-glados",
  "permissions": [
    {
      "access": [
        {
          "action": "list",
          "resource": "repository"
        }
      ],
      "kind": "project",
      "namespace": "*"
    }
  ]
}
```
</details>

```console
$ curl -u "robot-glados:${GLADOS_PASSWORD}" -X GET "${HARBOR_URL}/api/v2.0/projects/foobar/repositories" -H "Accept: application/json" --silent
[{"artifact_count":9,"creation_time":…
```

### Both system and project permissions

<details>
<summary>📃 <code>robot.json</code></summary>

```json
{
  "disable": false,
  "duration": -1,
  "editable": true,
  "expires_at": -1,
  "id": 133742,
  "level": "system",
  "name": "robot-glados",
  "permissions": [
    {
      "access": [
        {
          "action": "list",
          "resource": "project"
        }
      ],
      "kind": "system",
      "namespace": "/"
    },
    {
      "access": [
        {
          "action": "list",
          "resource": "repository"
        }
      ],
      "kind": "project",
      "namespace": "*"
    }
  ]
}
```
</details>

```console
$ curl -u "robot-glados:${GLADOS_PASSWORD}" -X GET "${HARBOR_URL}/api/v2.0/projects" -H "Accept: application/json" --silent
[{"chart_count":1,"creation_time":…
$ curl -u "robot-glados:${GLADOS_PASSWORD}" -X GET "${HARBOR_URL}/api/v2.0/projects/foobar/repositories" -H "Accept: application/json" --silent
{"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}
```

Please fix.

**Comment by wy65701436** [comment]
PR to resolve the robot to call list project API, https://github.com/goharbor/harbor/pull/15431, it will be in v2.4, and you can try with main branch now.
