### ISSUE TITLE
Tag Retention Rules: repo name with slash will cause 500 internal error

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#14510]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

tried to add "Tag Retention Rules" in https://goharbor.io/docs/2.0.0/working-with-projects/working-with-images/create-tag-retention-rules/
the repo name like: "**csi/cinder-csi-plugin,gcr.io/etcd-development/etcd**", the rule could be added. but when try a "Dry Run", there will be error report. from Harbor core log as below:

=====
2021-03-25T15:05:31+08:00 [DEBUG] [/pkg/permission/evaluator/admin/admin.go:32]: system administrator admin require update action for resource /project/1/tag-retention
2021-03-25T15:05:31+08:00 [ERROR] [/lib/http/error.go:54]: {"errors":**[{"code":"INTERNAL_SERVER_ERROR","message":"launcher: syntax error in pattern"}]}**
=========

also tried to add backslash to the repo name when add rules, like:

"**csi\/cinder-csi-plugin,gcr.io\/etcd-development\/etcd**"

the dry run could pass.

could somewhere translate the repo name automatically, instead of causing "internal error" in harbor?

thanks.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

as below.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by danielzhanghl** [comment]
add more note:
actually, the retention rule does not work if the repo is a list with forward slash, 
for example", add a rule with "excluding" and repo name with "csi/cinder-csi-plugin,gcr.io/etcd-development/etcd", 
after the dry run, repo "gcr.io/etcd-development/etcd" or "csi/cinder-csi-plugin" **are not excluded**.

**it only work when there is only one repo**, like "csi/cinder-csi-plugin",
 **if that is a list, it does not work.**

**Comment by danielzhanghl** [comment]
hello Harbor team, any suggestion on this failure? thanks.

**Comment by bitsf** [comment]
try add bracket, like {csi/cinder-csi-plugin,gcr.io/etcd-development/etcd}

**Comment by danielzhanghl** [comment]
just tried with "namespaceA/{repoA,repoB}", also return 500 internal error.

**Comment by danielzhanghl** [comment]
hello, any update on this issue? thanks.

**Comment by danielzhanghl** [comment]
ping...

**Comment by bitsf** [comment]
oh, I forget to see, upgrade to 2.2.1
refer https://github.com/goharbor/harbor/issues/14259

**Comment by danielzhanghl** [comment]
thanks.
