### ISSUE TITLE
Support customize the Look and Feel of Harbor

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#14515]
From  v2.x.x, below function brakes
https://goharbor.io/docs/1.10/build-customize-contribute/customize-look-feel/
Consider fixing it in v2.3.0

**Comment by AllForNothing** [comment]
Reopen it, we may add some nightly case for this

**Comment by a-mccarthy** [comment]
@AllForNothing can you clarify what you mean by this? Are the instructions on this page completely broken for 2.0, 2.1, and 2.2? 

Looks like the configuration names have change in your PR that will impact docs, can you confirm if the instructions for 2.3 will be different. Thanks!

**Comment by AllForNothing** [comment]
@a-mccarthy 
Are the instructions on this page completely broken for 2.0, 2.1, and 2.2?
A: Not completely broken,  but partly broken. For 2.0,2.1 and 2.2,  as Harbor has two theme modes,  the setting item "headerBgColor"  becomes unavailable.  Other setting items still work.

 i'm wondering if we should add a note on the versions where this functionality is broken to warn users.
A:  It would be nice if we can add a note to the setting item "headerBgColor" for version 2.0, 2.1, and 2.2

**Comment by a-mccarthy** [comment]
@AllForNothing If someone was using this and then upgraded to 2.0, 2.1 or 2.2, would this value be ignored in favor for the default light/dark mode default settings?

**Comment by AllForNothing** [comment]
@a-mccarthy You are right.  The value of "headerBgColor" would be overridden by the default light/dark value.
