### ISSUE TITLE
API /systeminfo/volumes returns incomplete response with S3 storage

### ISSUE THREAD

**Issue by mmslkr** [goharbor/harbor#14511]
**Expected behavior and actual behavior:**
After updating from v2.1.3-b6de84c5 to v2.2.0-ec0ba116 we noticed a change in how the API responds to `/systeminfo/volumes` when the storage is S3.

Before:
```
$ curl -X GET "https://HARBOR/api/v2.0/systeminfo/volumes" -H "accept: application/json" -u admin:password
{"storage":{"total":0,"free":0}}
```
This response is totally fine for S3.

Now:
```
$ curl -X GET "https://HARBOR/api/v2.0/systeminfo/volumes" -H "accept: application/json" -u admin:password
{"storage":[{}]}
```
We expect the behaviour from before the update.

**Steps to reproduce the problem:**
1. Run goharbor/harbor-core:v2.2.0 and setup an admin user. 
2. Call the API as shown above

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.2.0-ec0ba116
- docker engine version: 19.3.13
- kubernetes version: 1.17
- Image: goharbor/harbor-core:v2.2.0

**Additional context:**

- **Harbor config files:** nothing special, except that we use S3 as storage
- **Log files:**
```
2021-03-25T06:34:10Z [DEBUG] [/server/middleware/security/basic_auth.go:47][requestID="9ca1c5f1a6a5510c623be3d56fdab372"]: a basic auth security context generated for request GET /api/v2.0/systeminfo/volumes
2021-03-25T06:34:10Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require read action for resource /system/system-volumes
2021-03-25T06:34:10Z [WARNING] [/pkg/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity
```

Since the code for this doesn't seem to have changed, I can only guess that something prevents the json response being correctly created.

Thanks in advance.

**Comment by reasonerjt** [comment]
This is a known limitation, the /volume api is only usable for local storage.

**Comment by mmslkr** [comment]
Yes, we expect it to be "useless" for non-local disk. So the response should still be
```
{"storage":{"total":0,"free":0}}
```
Instead, it returns a "broken" json
```
{"storage":[{}]}
```
This breaks API consumers that relied on the storage.total, storage.free fields being present.
