### ISSUE TITLE
Scheduled Retention Job Creating 100's of Duplicate Runs

### ISSUE THREAD

**Issue by Lemmons** [goharbor/harbor#14527]
**Expected behavior and actual behavior:**
Expected behavior is that when a scheduled retention jobs runs it creates one and only one retention run.

Instead, what happens is a retention run is created at the initially scheduled time, and then duplicates are created every so often after the initial one is created. 
In our case the first duplicate appeared 6.5 minutes after the initial run was created.  From that point forward additional duplicates were created anywhere from every 10 seconds to about 6 minutes.  321 duplicates were created in total over the period of about 2.5 hours.  This brought our database to its knees and we had to manually stop every retention run, which took a long time because the database as pegged at 100% because of so many retention runs running at the same time.

**Steps to reproduce the problem:**
Exact steps to reproduce are unknown. Seems to be happening every few times the retention cron runs in our production Harbor instance.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.0]
- kubernetes version: [1.18]

**Additional context:**
- **Log files:** I'm not sure what log files will be relevant here, but can provide them as requested.

**Comment by bitsf** [comment]
hi, I'm not quite understand the issue clearly, can you paste some pictures ?

**Comment by reasonerjt** [comment]
@Lemmons 
What cron string did you use to trigger the retention job?

**Comment by Lemmons** [comment]
@reasonerjt This was using the built in weekly cron (I didn't specify a cron string, just used the dropdown box)

**Comment by Lemmons** [comment]
@bitsf This was in a Harbor instance which has been running for over a year.  Our deployment has about 630 images/repositories in a single project.  We upgraded from 2.1.3 to 2.2.0 around a month ago, and have been having issues since, particularly when the retention job runs.

After the above issue I was forced to disable the retention job entirely, as it keeps taking down the deployment.

It's also worth noting that the final resolution to the outage associated with this issue required us to purge all the data in our redis instance.  After doing this (along with killing all running retention jobs) the database finally recovered.

Here are a few screenshots of the some relevant pages from the retention ui.  Hopefully this clarifies things a little bit.
![Screenshot 2021-03-30 at 12 03 19](https://user-images.githubusercontent.com/2343674/113019759-c8ea6c80-9136-11eb-8b43-48b932e510bd.png)
![Screenshot 2021-03-30 at 12 03 33](https://user-images.githubusercontent.com/2343674/113019797-d1db3e00-9136-11eb-98db-1770eb160061.png)
![image](https://user-images.githubusercontent.com/2343674/113019910-f0413980-9136-11eb-8277-31bd281fa125.png)

**Comment by Lemmons** [comment]
Is it possible this is related to this other issue we ran into? https://github.com/goharbor/harbor/issues/14393

**Comment by bitsf** [comment]
hi, please upgrade to 2.2.1, which includes a fix of task manager, that maybe relative with this issue

**Comment by Lemmons** [comment]
@bitsf Can you please explain how that issue is related?  That issue doesn't talk at all about duplicated tasks being created, which is the core issue here.  What logic in 2.2.1 will fix this?

**Comment by bitsf** [comment]
I think this is not fixed in 2.2.1, as I reproduced it in replication
https://github.com/goharbor/harbor/issues/14683
