### ISSUE TITLE
missing timestamp information on pull time

### ISSUE THREAD

**Issue by zyitingftnt** [goharbor/harbor#14535]
In harbor 1.10.0, the timestamps are shown only for push but not pull, any idea?

![image](https://user-images.githubusercontent.com/81583999/112876924-f376ef80-907a-11eb-968c-caf668cc0a15.png)

it's a vanilla install, with very basic harbor.yml as blow

`---
hostname: <>
http:
  port: 80
https:
   port: 443
   certificate: /data/certs/<>.crt
   private_key: /data/certs/<>.key
harbor_admin_password: <>
data_volume: /data

clair:
  updaters_interval: 12
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 1.10.0

database:
  password: <>
  max_idle_conns: 50
  max_open_conns: 100

proxy:
  http_proxy:
  https_proxy:
  no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair,chartmuseum,notary-server
  components:
    - core
    - jobservice
    - clair
...`

**Comment by zyitingftnt** [comment]
in fact, all pull actions are not logged.

**Comment by reasonerjt** [comment]
v1.10.0 is no longer being maintained, could you check if the issue exists in v2.1.x and v2.2.x?

**Comment by zyitingftnt** [comment]
this can be closed since it was a problem of redis.
