### ISSUE TITLE
An error is reported when upgrading from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by ilanni2460** [goharbor/harbor#14534]
The upgrade command is：
docker run -it --rm -v /:/hostfs goharbor/prepare:v2.2.0 migrate -i /data/harbor_2.1.4_backup/harbor.yml

The following is the error log：

 dtr adapter was registered
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/replication/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/replication/adapter/tencentcr/adapter.go:35]: the factory for adapter tencent-tcr registered
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/replication/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/controllers/base.go:299]: Config path: /etc/core/app.conf
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/main.go:164]: initializing cache ...
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/main.go:171]: initializing configurations...
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/config/config.go:77]: key path: /etc/core/key
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/config/config.go:57]: init secret store
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/core/main.go:173]: configurations initialization completed
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/common/dao/base.go:70]: Register database completed
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:809]: error: no migration found for version 41
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "file does not exist"
Mar 29 23:38:16 172.21.0.1 core[1452]: 2021-03-29T15:38:16Z [FATAL] [/core/main.go:188]: failed to migrate: file does not exist

**Comment by reasonerjt** [comment]
In 2.1.4 there's SQL script to fix a performance issue which also exists in 2.2.0, hence, it's intentional that 2.1.4 cannot be upgraded to v2.2.0.  v2.1.4 can be upgraded to v2.2.1

We should have added to v2.1.4 release note, sorry for the confusion.

**Comment by ilanni2460** [comment]
tks @reasonerjt  i have success upgrading from 2.1.4 to 2.2.1
