### ISSUE TITLE
mirror sync with success rate   0%

### ISSUE THREAD

**Issue by 811105717** [goharbor/harbor#14543]
**Expected behavior and actual behavior:**

when an event_based sync job started, the ui present that sync percent 0%, but log show that not like 0%(maybe 30% ...etc)

**Steps to reproduce the problem:**

in ui:
         
![image](https://user-images.githubusercontent.com/35412811/112945342-bf78f880-9166-11eb-9939-2c6de27c4a39.png)

but the log:

  
![image](https://user-images.githubusercontent.com/35412811/112945414-d3bcf580-9166-11eb-85ec-c5098ac78537.png)

**versions**

- harbor version: 2.2.0
- docker engine version: 19.03.5, build 633a0ea838
- docker-compose version: 1.23.2, build 1110ad01

**Comment by heww** [comment]
This rate is the replicated artifact count / the total artifact count will be replicated.

**Comment by bitsf** [comment]
it would be 100% when job is done

**Comment by reasonerjt** [comment]
This seems by design because 0 artifact has been replicated yet when you check the log.

**Comment by 811105717** [comment]
I understand, thank you for your answers
