### ISSUE TITLE
Issue when using Harbor as Proxy Cache for ECR public registry

### ISSUE THREAD

**Issue by crileroro** [goharbor/harbor#14547]
I get an error once I try to use Harbor to proxy cache images from ECR public registry (https://gallery.ecr.aws/)

**Expected behavior:**

Image should be cached successfully in Harbor.

**Actual behavior:**

When I attempt to pull through my proxy cache project named **public.ecr.aws** the public image in ECR Gallery [nginx/nginx:latest](https://gallery.ecr.aws/nginx/nginx), I get the following error from my Docker client:
```sh
$ docker pull core.harbor.mydomain.com/public.ecr.aws/nginx/nginx:latest
Error response from daemon: unknown: resource not found: repo public.ecr.aws/nginx/nginx, tag latest not found
```

From the logs in my pod **harbor-core** the only line I see is the following:
```
2021-03-30T17:54:22Z [WARNING] [/controller/proxy/local.go:132]: failed to remove artifact, error http status code: 401, body:
```

My configuration is as follows:

*Registry*

![image](https://user-images.githubusercontent.com/26554832/113035465-8d31c000-9193-11eb-8ef4-ce61046643b4.png)

As from the [AWS docs](https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html), public.ecr.aws requires the region **us-east-1**:
```
The Amazon ECR Public registry requires authentication in the us-east-1 Region
```
*Project*

![image](https://user-images.githubusercontent.com/26554832/113035723-c23e1280-9193-11eb-8e7a-9367f3a308e9.png)

I tried using a replication rule with the same Registry and it works perfectly.

**Versions:**
  * Harbor Helm Chart: 1.6.0
  * Harbor version: 2.2.0
  * Kuberentes version: 1.18 (EKS)

**Comment by heww** [comment]
We can use the public ECR registry as a normal docker registry without username and password. And we will support to docker registry as the source of proxy cache in v2.3.0. @stonezdj will give a workaround for harbor v2.2.x.

**Comment by stonezdj** [comment]
1.Add a normal docker registry without a username and password in the UI
2.Create a normal project that needs to use as a proxy cache in the UI
3.Go the postgres db console
```
docker exec -it harbor-db bash
psql -U postgres -d registry
select * from registry ;
<get the id of the registry>
select * from project;
<get the project id of the project>

Update project set registry_id= <registryID> where project_id = <projectID>;
```
Then the proxy cache project is visible in the UI and you could pull images through it.

**Comment by stonezdj** [comment]
close it, supported in Harbor 2.2.x and 2.3.x

**Comment by redhat-demo** [comment]
does harbor support proxy for public.ecr.aws?

**Comment by killermoehre** [comment]
> does harbor support proxy for public.ecr.aws?

For everybody stumbling about this in 2024. You can add `public.ecr.aws` as a generic Docker Registry.

**Comment by ramfjord** [comment]
> For everybody stumbling over this in 2024. You can add public.ecr.aws as a generic Docker Registry.

But you need to auth with ECR in harbor as described in [the ECR public registries docs](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html), and the token you generate for a user might be too long for harbor to save.  Otherwise your proxy cache project will give you an auth error when you set it up.

**Comment by killermoehre** [comment]
@ramfjord I updated my statement. We use this configuration only as internal proxy to pull images, not for pushing. And for pulling you don't need credentials.
