### ISSUE TITLE
"Unauthorized to access repository" when trying to push image that is above > 1 GB 

### ISSUE THREAD

**Issue by jkagarise** [goharbor/harbor#14557]
When I try to push an image that is approximately 1GB or more I receive a "Unauthorized to access repository" message after all the data has been reported 'Pushed'.  I am able to push smaller images with no issue.  I have Project Admin rights to the repository.

Default configuration used in setup.

**Comment by heww** [comment]
How do you install your harbor instance, docker-compose, or helm?

**Comment by jkagarise** [comment]
Helm, with these settings.

expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    auto:
      commonName: "harbor-<domain name>"
    secret:
      secretName: "harbor-tls"
      notarySecretName: "notary-tls"
  ingress:
    hosts:
      core: "harbor-<domain name>"
      notary: notary-<domain name>

  # nodePort:
  #   name: harbor
  #   ports:
  #     http:
  #       port: 80
  #       nodePort: 30002
  #     https:
  #       port: 443
  #       nodePort: 30003
  #     notary:
  #       port: 4443
  #       nodePort: 30004
externalURL: https://harbor-<domain name>

**Comment by heww** [comment]
Could you share the annotations of the ingress for the harbor?

**Comment by heww** [comment]
Could you share the log of the registry when got `Unauthorized to access repository` error?
