### ISSUE TITLE
Install doc's do not cover directories that need to be created

### ISSUE THREAD

**Issue by csmykay** [goharbor/harbor#14558]
What can we help you?
Under: https://goharbor.io/docs/2.2.0/install-config/download-installer/
But then in the next step you make an assumption that the '/data' directory is already there when the installer has not been run yet under: https://goharbor.io/docs/2.2.0/install-config/configure-https/

Recommend you either put a step at the end of the downlod-installer page to create directory or create a "pre-reqs.sh" script that prompts for the directories to create.

**Comment by ninjadq** [comment]
hi @csmykay , have you use root user to install Harbor
