### ISSUE TITLE
Multiple Arch Support Story

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#14552]
With more ARM systems coming into market, multiple arch support is becoming more significant. However, so far Harbor only ship x86_64 binaries, let's start the engineering work and use this epic to check the progess. 

[Requirements]
https://github.com/goharbor/harbor/issues/3505
https://github.com/goharbor/harbor/issues/14330
https://github.com/goharbor/harbor/issues/10578

[Sub-Repos]
https://github.com/goharbor/harbor-arm
https://github.com/goharbor/harbor-loongson

[PRs]
https://github.com/goharbor/harbor/pull/13788

**Comment by xiaoweihong** [comment]
any update? when arm64 version release?

**Comment by replacewithname** [comment]
still relevant

**Comment by MikeK184** [comment]
any updates on this?

**Comment by smartinov** [comment]
Still relevant!

**Comment by jbpadgett** [comment]
Status check starting fresh for 2023.
Are there any updates on development efforts for an ARM capable image?

**Comment by zruijie** [comment]
We want ARM supported.

**Comment by disconn3ct** [comment]
FYI https://github.com/octohelm/harbor works (and has worked for a long time) so it is just an integration problem at this point.
