### ISSUE TITLE
"GC NOW" button should reconfirm！

### ISSUE THREAD

**Issue by gejunqiang** [goharbor/harbor#14555]
**Is your feature request related to a problem? Please describe.**
As we all know, In the process of garbage collection, we can not push image to harbor. If I click the button "GC NOW", I can not stop the gc task actually. In the production environment, the gc task often takes a long time. And on the web UI, when I click the "GC NOW" button, it begins to GC directly with no reconfirm! So if I click the button by mistake or other things happen, it will cause serious consequences.

![image](https://user-images.githubusercontent.com/26571382/113127815-c463a800-924b-11eb-82ea-ceefe9a9b4dc.png)

**Describe the solution you'd like**

 I think when user click the "GC NOW" button,  it should **pops up a prompt box**  with the warning message, the user will have to click "OK" to reconfirm this dangerous operation or "Cancel" to cancel this operation.

**Comment by gejunqiang** [comment]
By the way, the harbor version we use is v1.10.6

**Comment by dkulchinsky** [comment]
@gejunqiang might want to consider upgrading to v2 which introduced non-blocking GC.

**Comment by AllForNothing** [comment]
@xaleeks sounds reasonable,  should we add it to target 2.3?

**Comment by reasonerjt** [comment]
We can do it but GC will not put Harbor into readonly status after v2.1

**Comment by gejunqiang** [comment]
> We can do it but GC will not put Harbor into readonly status after v2.1

> @gejunqiang might want to consider upgrading to v2 which introduced non-blocking GC.

Thanks @dkulchinsky  and @reasonerjt , I got it. We will consider upgrading to v2.1 later.

**Comment by xaleeks** [comment]
I think we can close this, let me know if you still have questions
