### ISSUE TITLE
FORBIDDEN when using v2 API with robot account

### ISSUE THREAD

**Issue by abelsromero** [goharbor/harbor#14554]
Harbor version: 2.1.3

We want to automate some things, and for one we need to obtains the sha for published Helm charts.
The only thing that seems to work was using `/artifacts` (using `/chartrepo` always returned 404).

Now the real issue is that to authenticate, it requires a nominal (with user & pass) user and according to the swagger.yaml it only supports basic auth. This breaks some of our current conventions and other scenarios for which we use robot accounts without problems.

- Is this intended?
- Is there som other way to authenticate? Docs don't talk about autentication methods and this screenshot shows an api-key option https://goharbor.io/docs/1.10/build-customize-contribute/configure-swagger/#testing-harbor-rest-api, however, there's no way to generate that from the admin UI.

**Comment by heww** [comment]
Harbor v2.2.x supports system-level robot accounts and you can create a system-level robot account using API with custom access (policy). 

The access resources and actions are will [here](https://github.com/goharbor/harbor/blob/0d4992a41e994ac75121581505e26ac1b116a988/src/common/rbac/const.go).

**Comment by abelsromero** [comment]
I guess then we are stuck as long as we have 2.1.3.

> Harbor v2.2.x supports system-level robot accounts

That will be awesome when we upgrade. Right now we have to handle different robot accounts for related projects.

**Comment by wy65701436** [comment]
you can refer to the v2.2.0 document for the system robot account at goharbor.io

**Comment by abelsromero** [comment]
Thanks a lot, for reference I found this:

* Create System Robot Accounts (v2.2.0): https://goharbor.io/docs/2.2.0/administration/robot-accounts/
