### ISSUE TITLE
Get registries API only return 10 items even though there're more than 10 items 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#14561]
Although more than 10 registries have been created, but registry list only display 10 items. We can get the target registry by filtering search.

![image](https://user-images.githubusercontent.com/44018302/113278297-59ca6f00-9314-11eb-8837-5e2c43f2f4c9.png)

![image](https://user-images.githubusercontent.com/44018302/113376686-dd33a100-93a4-11eb-80c7-b77a45369f9f.png)

**Comment by ywk253100** [comment]
If no page size is setting when requesting the resources, the default value `10` is used. You can see that the response `Link` header indicates there is still more data

**Comment by ywk253100** [comment]
@AllForNothing please add the pagination information for the request

**Comment by danfengliu** [comment]
Replication rule edition have this issue too.
