### ISSUE TITLE
error closing blobwriter: sync 

### ISSUE THREAD

**Issue by robrosillo** [goharbor/harbor#14573]
Hello.
A Harbor v1.8.6-5d2c4c2d is running, and since a some weeks ago when a docker image is pushed to Harbor, sometime the process shows a 503 error. It is possible that 30 minutes or and one hour after  the some push process for that image docker work well. It appear like a aleatory issue.

We have checked the registry.log and we seen the next messages:

pr  5 09:47:45 192.168.240.1 registry[2433]: time="2021-04-05T07:47:45.863199646Z" 
level=info msg="response completed" go.version=go1.12.12 
http.request.contenttype="application/json" http.request.host=registry.global.ccc.srvb.bo.paas.cloudcenter.corp 
http.request.id=48a55317-7b2f-421c-bd17-a8ed8965ac99 http.request.method=POST 
http.request.remoteaddr=180.156.105.148 http.request.uri="/v2/project/s-node-50057040-backend-v4/blobs/uploads/" 
http.request.useragent=go-containerregistry http.response.duration=11.993805ms http.response.status=202 http.response.written=0 

Apr  5 09:47:45 192.168.240.1 registry[2433]: time="2021-04-05T07:47:45.877290684Z" level=info msg="authorized request" 
go.version=go1.12.12 http.request.host=registry.global.ccc.srvb.bo.paas.cloudcenter.corp http.request.id=17b673ce-fb99-43e5-8eaa-f1987af6985c 
http.request.method=DELETE http.request.remoteaddr=180.156.105.148 
http.request.uri="/v2/project/s-node-50057040-backend-v4/blobs/uploads/eb9119df-0e76-448a-89eb-ff7dec369a02?_state=zuFP6bFReziK9VY-uRneuftglXrEfaL-1FHtrC4Nyv97Ik5hbWUiOiJzYW4tZnhwYXktc2FuL3Mtbm9kZS01MDA1NzA0MC1iYWNrZW5kLXY0IiwiVVVJRCI6ImViOTExOWRmLTBlNzYtNDQ4YS04OWViLWZmN2RlYzM2OWEwMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMS0wNC0wNVQwNzo0Nzo0NS44NTI1MTU1OTRaIn0%3D" 
http.request.useragent=go-containerregistry vars.name="project/s-node-50057040-backend-v4" 
vars.uuid=eb9119df-0e76-448a-89eb-ff7dec369a02 

Apr  5 09:47:45 192.168.240.1 registry[2433]: time="2021-04-05T07:47:45.884228522Z" level=error 
msg="error closing blobwriter: sync /storage/docker/registry/v2/repositories/project/s-node-50057040-backend-v4/_uploads/eb9119df-0e76-448a-89eb-ff7dec369a02/data: file already closed" auth.user.name=aplappdevops go.version=go1.12.12 
http.request.host=registry.global.ccc.srvb.bo.paas.cloudcenter.corp 
http.request.id=17b673ce-fb99-43e5-8eaa-f1987af6985c http.request.method=DELETE 
http.request.remoteaddr=180.156.105.148 http.request.uri="/v2/project/s-node-50057040-backend-v4/blobs/uploads/eb9119df-0e76-448a-89eb-ff7dec369a02?_state=zuFP6bFReziK9VY-uRneuftglXrEfaL-1FHtrC4Nyv97Ik5hbWUiOiJzYW4tZnhwYXktc2FuL3Mtbm9kZS01MDA1NzA0MC1iYWNrZW5kLXY0IiwiVVVJRCI6ImViOTExOWRmLTBlNzYtNDQ4YS04OWViLWZmN2RlYzM2OWEwMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMS0wNC0wNVQwNzo0Nzo0NS44NTI1MTU1OTRaIn0%3D" 
http.request.useragent=go-containerregistry vars.name="project/s-node-50057040-backend-v4" vars.uuid=eb9119df-0e76-448a-89eb-ff7dec369a02 

Apr  5 09:47:45 192.168.240.1 registry[2433]: time="2021-04-05T07:47:45.890861123Z" level=info msg="response completed" go.version=go1.12.12 
http.request.host=registry.global.ccc.srvb.bo.paas.cloudcenter.corp http.request.id=17b673ce-fb99-43e5-8eaa-f1987af6985c http.request.method=DELETE 
http.request.remoteaddr=180.156.105.148 http.request.uri="/v2/project/20210405.9.23-20210405093024-snapshot/blobs/uploads/eb9119df-0e76-448a-89eb-ff7dec369a02?_state=zuFP6bFReziK9VY-uRneuftglXrEfaL-1FHtrC4Nyv97Ik5hbWUiOiJzYW4tZnhwYXktc2FuL3Mtbm9kZS01MDA1NzA0MC1iYWNrZW5kLXY0IiwiVVVJRCI6ImViOTExOWRmLTBlNzYtNDQ4YS04OWViLWZmN2RlYzM2OWEwMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMS0wNC0wNVQwNzo0Nzo0NS44NTI1MTU1OTRaIn0%3D" http.request.useragent=go-containerregistry 
http.response.duration=15.846499ms http.response.status=204 http.response.written=0 

In my opinion, it is possible that the disk doesn't not work properly in that moment, but I am not sure.

Any idea about what is happening?

Thank you in advance.

**Comment by heww** [comment]
Which installer do you use, docker-compose or helm?

**Comment by robrosillo** [comment]
Hello,
Thank you for you answer. We will.
