### ISSUE TITLE
scanning finished webhook

### ISSUE THREAD

**Issue by wangzd1** [goharbor/harbor#14585]
hi,
   I configed scanning finished webhook,but when i receive the response,it's scan_status is "Running".Any idea?
harbor version:v2.1.1
scanner:Clair 2.x

**Comment by heww** [comment]
Do you have a scheduled scan all in the system?

Is the artifact in the webhook also referenced in another artifact?

**Comment by wangzd1** [comment]
是的，我启用了harbor的clair扫描器，并导入了漏洞元数据，在页面上能看到某一个镜像有一些漏洞信息。但是当我在页面上勾选后扫描，触发了scanning finished 的webhook后，收到的body中的scan_overview下的summary是null。

**Comment by wangzd1** [comment]
[](url)

**Comment by wangzd1** [comment]
扫描的是该镜像：
![IMG_20210407_212443](https://user-images.githubusercontent.com/23433396/113874195-1d9d7f80-97e8-11eb-9a1c-5bf37f324ed5.jpg)
从webhook中收到的response如下：
![IMG_20210407_212434](https://user-images.githubusercontent.com/23433396/113874186-1bd3bc00-97e8-11eb-879f-cdd15aed9749.jpg)

**Comment by heww** [comment]
Can you verify that this payload of the webhook is the scan finished event?

**Comment by cdchris12** [comment]
Just wanted to drop a comment to say that we're having this issue as well on Harbor `v2.1.5-919c9fd2`. We're using the Trivy scanner and our config isn't far off from the helm chart. We're seeing webhooks sent out with the `scan_status` of `Running`, even though the job has been reported as successful by the jobservice container. Here's an example:

```
{
  "type": "SCANNING_COMPLETED",
  "occur_at": 1621658778,
  "operator": "auto",
  "event_data": {
    "resources": [
      {
        "digest": "sha256:4f7c592b7c3d9d2a9b6d633ef62a7577af5bc679f02e1eb87fe1add91e94b66c",
        "tag": "",
        "resource_url": "REDACTED",
        "scan_overview": {
          "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0": {
            "report_id": "22ac2776-4f13-46ae-964e-9a10266e13bf",
            "scan_status": "Running",
            "severity": "",
            "duration": 0,
            "summary": null,
            "start_time": "2021-05-22T04:45:50.407902Z",
            "end_time": "0001-01-01T00:00:00Z",
            "complete_percent": 0
          }
        }
      }
    ],
    "repository": {
      "name": "REDACTED",
      "namespace": "REDACTED",
      "repo_full_name": "REDACTED",
      "repo_type": "private"
    }
  }
}
```
