### ISSUE TITLE
harbor can not be build for users of Go 1.14 or 1.15

### ISSUE THREAD

**Issue by zhangwenlong8911** [goharbor/harbor#14586]
I built GO-swagger using Golang 1.15,Then execute the command "swagger generate server --template-dir=/root/test/harbor/tools/swagger/templates --exclude-main --additional-initialism=CVE --additional-initialism=GC -f api/v2.0/swagger.yaml -A harbor --target src/server/v2.0"

it show error information is as follows:

failed rendering template data for definition: template execution failed for template definition: template: schematype:2:18: executing "schemaType" at <(len .AllOf) gt 0>: can't give argument to non-function len .AllOf

This is because the GO is more stringent in grammar check after the 1.14 version, and the [Go-swagger fixes this issue in V0.23.0 version](https://github.com/go-swagger/go-swagger/issues/2215).,But harbor still use swagger v0.21.0 .So suggest to upgrade the Go-swagger version in Harbor to support Golang 1.14 or 1.15

**Comment by zhangwenlong8911** [comment]
@heww 
Hello, can you reproduce this problem? I have verified several times, it is inevitable error

**Comment by heww** [comment]
Sorry that we can't upgrade the go-swagger at the moment because the open api packages used by the go-swagger was conflicted with the open api packages used by the chartmuseum.

We need to upgrade the pkgs of the chartmuseum first to upgrade go-swagger.

**Comment by heww** [comment]
Hi @zhangwenlong8911 Can you ensure that go-swagger 0.23 resolved this issue? If so, I can try to upgrade go-swagger to 0.23 first.

**Comment by zhangwenlong8911** [comment]
the changelog of go-swagger show this [bug fixed in v0.23.0](https://github.com/go-swagger/go-swagger/releases), the number of issue is [2215](https://github.com/go-swagger/go-swagger/issues/2215)

**Comment by zhangwenlong8911** [comment]
Of course, I think there are other ways to circumvent this problem, such as modifying the harbor code to ensure that after compiling swagger-v0.21.0 with golang-1.15, the files in the harbor can be parsed normally

**Comment by zhangwenlong8911** [comment]
thanks, The problem has been resolved
