### ISSUE TITLE
Updates to docs contributing processes

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#14590]
**Is your feature request related to a problem? Please describe.**

Docs for the Harbor project are kept in the https://github.com/goharbor/website repo. 

This issue covers some process improvements to make it easier to submit and manage docs issues. PRs for docs or website improvement should still be filed against the website repo, but it would be easier to manage docs issues and prioritize them with other dev work if the issues are all in the same repo. 

**Describe the solution you'd like**
1. [ ] Disable the website repo to accepting new issues, have all docs related issues filed agains the core harbor repo (this repo)
1. [ ] Migrate all open issues from the website repo to this repo (or close the ones that it doesn't make sense to move)
1. [ ] Create an issue template for docs that captures information needed to update docs or make site improvements and adds the area/docs label by default
1. [x] Update website repo to require PRs to have at least 1 approving review before merging 

There is also a PR open to add a PR template to the repo to help collect information on things like the changes being submitted issue(s) being fixed, https://github.com/goharbor/harbor/pull/14271

**Comment by Vad1mo** [comment]
I thought it would also make sense to add harbor-helm to harbor as well. 

@jonasrosland pointed out that there is https://github.com/orgs/goharbor/projects that we can use for issue triage. It already contains harbor and harbor-helm. 

Alternative suggestion is to add website to https://github.com/orgs/goharbor/projects.

**Comment by jonasrosland** [comment]
Looking closer at this, the maintainers are using milestones within the `harbor` repo for sprint planning, which only works with issues within that repo: https://github.com/goharbor/harbor/milestones
So, there might be a disconnect between the org board and the repo milestones? @renmaosheng Can you chime in here?
