### ISSUE TITLE
harbor 2.0.2 mirror layer missing

### ISSUE THREAD

**Issue by hyserver** [goharbor/harbor#14599]
Before the new image, after a month to pull again when found that a layer does not exist.

`registry.log:Apr  2 14:22:22 172.25.0.1 registry[16242]: time="2021-04-02T06:22:22.900925434Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3 err.message="blob unknown to registry" go.version=go1.14.5 http.request.host=a.b.com http.request.id=af0ff5fa-8b3c-4c48-a307-643e3fa5cb6a http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/mtech/openjdk/blobs/sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=56.369112ms http.response.status=404 http.response.written=157 vars.digest="sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3" vars.name="mtech/openjdk"
registry.log:Apr  2 14:22:22 172.25.0.1 registry[16242]: time="2021-04-02T06:22:22.97404503Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:1ec0dcc7831dbb0f2b20654d18c2a6c528c9f3dfd28df45c608a243c7f4f15e1 err.message="blob unknown to registry" go.version=go1.14.5 http.request.host=a.b.com http.request.id=6d3813d3-2312-4c68-9890-c0fbe1dfcfdb http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/mtech/openjdk/blobs/sha256:1ec0dcc7831dbb0f2b20654d18c2a6c528c9f3dfd28df45c608a243c7f4f15e1" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9.853542ms http.response.status=404 http.response.written=157 vars.digest="sha256:1ec0dcc7831dbb0f2b20654d18c2a6c528c9f3dfd28df45c608a243c7f4f15e1" vars.name="mtech/openjdk"
registry.log:Apr  2 14:22:22 172.25.0.1 registry[16242]: time="2021-04-02T06:22:22.979631112Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76 err.message="blob unknown to registry" go.version=go1.14.5 http.request.host=a.b.com http.request.id=a94856f4-6d16-4aec-873b-d9476f38c61b http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/paas/supervisord/openjdk/blobs/sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=118.262473ms http.response.status=404 http.response.written=157 vars.digest="sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76" vars.name="paas/supervisord/openjdk"
registry.log:Apr  2 14:22:23 172.25.0.1 registry[16242]: time="2021-04-02T06:22:23.118283761Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3 err.message="blob unknown to registry" go.version=go1.14.5 http.request.host=a.b.com http.request.id=00cd95bd-6a0b-40a7-9f28-8db14e8f6b7c http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/mtech/openjdk/blobs/sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=95.045831ms http.response.status=404 http.response.written=157 vars.digest="sha256:65a5ae1d66f17d8b433f420fdc45c2fc1b8c60b55da03e01c27af8afbe62a3e3" vars.name="mtech/openjdk"
registry.log:Apr  2 14:22:23 172.25.0.1 registry[16242]: time="2021-04-02T06:22:23.123484062Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76 err.message="blob unknown to registry" go.version=go1.14.5 http.request.host=a.b.com http.request.id=5e83df6e-bcc2-477e-80af-b7c2a2579786 http.request.method=HEAD http.request.remoteaddr=x.x.x.x http.request.uri="/v2/paas/supervisord/blobs/sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=112.078233ms http.response.status=404 http.response.written=157 vars.digest="sha256:6196d579f10b7d1eb6c07031fea45740c879ccf22abb75eec500a00ed21cbf76" vars.name="paas/supervisord"`

**Comment by heww** [comment]
Which storage do you use in the registry? filesystem, s3?

**Comment by hyserver** [comment]
Storage uses Ceph, three GCs were performed in March.

**Comment by hyserver** [comment]
Are you Chinese?

**Comment by hyserver** [comment]
Can you sent your email or wechat for me? thanks.

**Comment by heww** [comment]
> Can you sent your email or wechat to me? thanks. @heww

You can get my email from the git commit.

**Comment by heww** [comment]
Closed as the bucket created by the customer in the ceph has a 30 days expiration.
