### ISSUE TITLE
Error deleting chart with version in quotes

### ISSUE THREAD

**Issue by twellspring** [goharbor/harbor#14607]
A helm chart got uploaded with the version in quotes 

![image](https://user-images.githubusercontent.com/9868888/114242863-6f591d80-9940-11eb-9d0d-ce06c48a3bbf.png)

If I try to delete it from the gui I get the error 
`fail to delete chart version: remove /chart_storage/ironnet/dns-tunneling-ss-"3.4-356".tgz: no such file or directory`

The file does not exist.  I have added that file 
`touch '/chart_storage/ironnet/dns-tunneling-ss-"3.4-356".tgz'` and then the delete completes successfully, but the entry still exists in my repo and a `helm repo update` command on my workstation throws this error

```index.go:339: skipping loading invalid entry for chart "dns-tunneling-ss" "\"3.4-356\"" from https://harbor.aws-dev.irondev.io/chartrepo/ironnet: validation: chart.metadata.version "\"3.4-356\"" is invalid ```

How can I get rid of this entry?

**Comment by twellspring** [comment]
Harbor Version v2.2.0-6db1a349 
Installed in EKS using the helm chart https://github.com/goharbor/harbor-helm

**Comment by ninjadq** [comment]
This is caused by upstream chartmuseum.
the file is already deleted, but the cache still left on cache. 
you can try following steps as workaround
1. stop harbor
2. delete cache both in Redis and chart data storage
3. start harbor

**Comment by piyush94** [comment]
Chartmuseum has newer releases >= 0.13.0 in which chart semantic versioning issues have been resolved. Kindly upgrade the chartmuseum version in Harbor release as well. PR: https://github.com/helm/chartmuseum/pull/362
