### ISSUE TITLE
Link Dockerfile to a TAG

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#1460]
Hi, It would be very interesting if Harbor could link a Dockerfile to TAG using the WEB console.

Thanks.

**Comment by pineking** [comment]
That's a nice feature if we can upload/paste Dockerfile to Harbor.

**Comment by reasonerjt** [comment]
But then we need to think about how to ensure the consistency between Dockerfile and the image.

Any good ideas?

**Comment by roldancer** [comment]
The consistency should be project/repository owner's responsability. cop&paste should be enough ...

Thanks.

**Comment by pineking** [comment]
@roldancer I agree

**Comment by reasonerjt** [comment]
@roldancer so what do you think if we enable the owner to add/edit description of a repo such that he can put whatever information to describe the repository.

Or do you think it has to be Dockerfile?

**Comment by roldancer** [comment]
Hi, That sounds good, but URL in a description field should be recognized as a html link.

Thanks.

**Comment by akshayl** [comment]
@roldancer We're thinking we could accommodate this by allowing the user to specify metadata for each tag such as:
- Description
- Link to Dockerfile source (rather than the file itself) e.g. github.com/org/projects/master/foo/Dockerfile

Would that work?

**Comment by reasonerjt** [comment]
This is partially fixed as we have introduced description to repository.
