### ISSUE TITLE
Prompt "loading..." when accessing

### ISSUE THREAD

**Issue by snow-with-tea** [goharbor/harbor#14609]
After installation：
![image](https://user-images.githubusercontent.com/33077280/114337848-78d2c780-9b84-11eb-81b8-667af8573c77.png)
docker ps：
![image](https://user-images.githubusercontent.com/33077280/114337795-5b9df900-9b84-11eb-84ef-50fdd146d6f5.png)
Revised part：（harbor.yml）
![image](https://user-images.githubusercontent.com/33077280/114338024-cc451580-9b84-11eb-9c15-387e4c4ac25a.png)
firewalld：
![image](https://user-images.githubusercontent.com/33077280/114338187-1fb76380-9b85-11eb-89d6-3523382ca512.png)
logs：
![image](https://user-images.githubusercontent.com/33077280/114338261-4e353e80-9b85-11eb-9b27-901cc72e8b7e.png)
I don't know what's wrong

**Comment by snow-with-tea** [comment]
Some system environment information：
centos8
ifconfig：
![image](https://user-images.githubusercontent.com/33077280/114338685-272b3c80-9b86-11eb-95cd-f5dab3cf5d56.png)

**Comment by heww** [comment]
Which browser do you use? How about trying to use the latest version of chrome?

**Comment by snow-with-tea** [comment]
> 您使用哪个浏览器？尝试使用最新版的chrome怎么样？

Sorry because I am an intranet environment, I didn't try to access the graphic interface. Only 'curl', the agent has been built. Now I can access it after using chrome. Thank you

**Comment by heww** [comment]
Yup, the portal is a SPA and a browser may be needed to access it.
