### ISSUE TITLE
API for enable/disable read-only mode

### ISSUE THREAD

**Issue by mdraijer** [goharbor/harbor#14603]
The only possibility to enable and disable the read-only mode is via the UI. This should also be possible via the API.

The use case for this is that Harbor must be frozen during backup. When images are pushed during backup, you will have problems once you restore that backup. Tests proved that after a restore of a backup taken while pushing an image, it is not possible anymore to push images (at all, to any project).

**Comment by heww** [comment]
Try `curl -u admin:password https://harbor-host/api/v2.0/configurations -X 'PUT' --data-raw '{"read_only":true}'` to enable the read-only mode.

The portal calls the APIs to complete the operations.

**Comment by mdraijer** [comment]
Thanks, that does the trick!
I just needed to add -H "content-type: application/json"
