### ISSUE TITLE
NGINX Proxy not staring when "harbor_internal_ca.crt" is missing

### ISSUE THREAD

**Issue by dan-m8t** [goharbor/harbor#14618]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Proxy starting up properly.
Actual behavior: not starting because of missing CA certificate

**Steps to reproduce the problem:**
Follow official guide, build own CA, start harbor with docker-compose --> nginx and  harbor-jobservice refusing to run

Copy harbor_internal_ca.crt to ..  common/config/shared/trust-certificates , restart nginx and harbor-jobservice container --> profit

Logs:

nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/harbor_cust_cert/harbor_internal_ca.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)

To be more clear:

I am setting this whole thing up with ansible and was debugging why the nginx container is missing the certificate.
I added a copy job to copy the CA file to the right folder, but when I run ./install.sh the certificate is deleted and I need to copy it again to get it to work

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.1
- docker engine version: 20.10.5
- docker-compose version: 1.18.0

**Comment by bitsf** [comment]
hi, server cert should be configured in harbor.yml https.certificate and https.private_key
certs for components communication is configured in harbor.yml internal_tls.dir
if you add other certs, currently can be configured in harbor.yml  storage_service.ca_bundle as workaround
