### ISSUE TITLE
spec is missing many operationId fields

### ISSUE THREAD

**Issue by Morriz** [goharbor/harbor#14617]
What can we help you?

"What can we help you with?" perhaps?

Well, you publish an openapi spec with many missing `operationId` props. All the endpoints under `paths:` should have one. I kindly ask you to enrich your schema so that we can generate clients that work. 

tnx

**Comment by Morriz** [comment]
I noticed the operations under `"/configurations"` don't have them, but we need to be able to talk to those apis as well of course...

**Comment by Vad1mo** [comment]
Yes the rest api isn't perfect at the moment 2.3 is addressing the problem. In the meantime, look at  this swagger file here.  We used that to create an rest api client, it contains operationId and is cleanedup by hand 

https://github.com/container-registry/harbor-python-client-api/blob/f0cc6c453b488d5f456eff94000156182eb3a468/swagger.yaml

**Comment by Morriz** [comment]
As I mentioned somewhere else, we got a fully operational setup as example here: https://github.com/redkubes/otomi-tasks/blob/master/src/tasks/harbor/harbor.ts

**Comment by heww** [comment]
Please try the swagger file https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml in the master branch which includes the operationId for each path.

As you know, we will move most of the APIs from legacy swagger to this swagger file in harbor v2.3.

**Comment by wy65701436** [comment]
We're refactor the APIs, will have a check about the operionID, thanks for catching.
