### ISSUE TITLE
panic: Get "https://registry.test.com/v2/": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by love-miao** [goharbor/harbor#14612]
harbor source version:1.2.2
Harbor mirror version:v1.10.6
1. question:
The habor source is a self issued certificate, and then I configure a mirror mode harbor to synchronize the source, but the error is as follows:
panic: Get "https://registry.test.com/v2/": x509: certificate signed by unknown authority

2. thc mirror mode must a CA issue a legal certificate?

**Comment by love-miao** [comment]
I may have found a way to close this parameter, but I don't know where to change it（Harbor mirror version:v1.10.6）
harbor.cfg:
verify_remote_cert = off

**Comment by wy65701436** [comment]
hi,  I'm not clear understand the query, are you talking about the replication between Harbor v1.2.2 and v1.10.6? If so, harbor doesn't support cross version replication, you have to upgrade the v1.2.2 to v1.10.X, then do the replication, if the problem still exist, just reply with logs.

**Comment by love-miao** [comment]
Thank you. I'll try again after upgrading
