### ISSUE TITLE
Link Git repository

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#1461]
Hi, It would be very interesting if Harbor could link a Git repository to a Harbor repo, using the WEB console, The Git repository URL should be a Harbor's repo properties.

Thanks.

**Comment by hainingzhang** [comment]
Thanks for the suggestion. Could you describe how this link is used ? Is it just a reference to jump to the Git repo?

**Comment by roldancer** [comment]
Right, it should be used only to jump to the Git repo.

Thanks.
