### ISSUE TITLE
Upgrading from v1.10.1 -> v1.10.6: No `harbor-migrator` for version 1.10.3 and above

### ISSUE THREAD

**Issue by stefanlasiewski** [goharbor/harbor#14622]
We’re still using Harbor v1.10 (upgrading to 2.x soon). I want to upgrade the latest 1.10.6 version. The upgrade instructions at https://goharbor.io/docs/1.10/administration/upgrade/#upgrading-harbor-and-migrating-data at step 5 say I should do `docker pull goharbor/harbor-migrator:[tag]` where [tag] is the new Harbor version. 

Problem is, that there is no version `1.10.6` in the registry. Versions `1.10.3` through `1.10.6` all end in `*-dev` which makes them not-production worthy. The latest non-dev version is v1.10.2. See the screenshot below showing the `-dev` versions.

Why was there never a production version for `1.10.6`? Should I use the `1.10.6-dev` version?

![image](https://user-images.githubusercontent.com/142752/114473710-98301b80-9ba9-11eb-929b-52787137738d.png)

**Comment by stefanlasiewski** [comment]
Was the image changed from `goharbor/harbor-migrator` to `goharbor/prepare` for v1.10.x?

https://goharbor.io/docs/1.10/administration/upgrade/#upgrading-harbor-and-migrating-data still says `goharbor/harbor-migrator`.

**Comment by ninjadq** [comment]
You can use 1.10.0 tag. Because there is no change between 1.10.x and 1.10.0
