### ISSUE TITLE
add examples to documentation to show how to use the openapi client(s) for common use cases

### ISSUE THREAD

**Issue by Morriz** [goharbor/harbor#14620]
**Is your feature request related to a problem? Please describe.**

Problem is to find out how to add role to group via rest api. But the problem is bigger: no examples exists that show how to use the rest/swager api.

**Describe the solution you'd like**
A section in the docs that show how to do these operations in code. It is time to acknowledge that we do everything as code nowadays and would like to be able to repeat routines.

**Comment by Vad1mo** [comment]
@Morriz we are currently building an rest api SDK and CLI based on the swagger spec. 

take a look at this example here https://github.com/container-registry/harbor-python-client-api/blob/f0cc6c453b488d5f456eff94000156182eb3a468/docs/ProductsApi.md#set_project_member

**Comment by Morriz** [comment]
Awesome! Any oidc examples? I can't seem to find anything that works.

**Comment by Morriz** [comment]
I hope you are aware that there is a `ProductsApi` that should be `ProjectsApi`?

**Comment by Vad1mo** [comment]
The docs folder has description and examples https://github.com/container-registry/harbor-python-client-api/blob/master/docs/OidcApi.md. Its OpenApi Spec there is nothing Harbor related on how to use it.

**Comment by Vad1mo** [comment]
>I hope you are aware that there is a ProductsApi that should be ProjectsApi?

Thats how it is in defined in swagger. We didn't want rewrite the whole swagger file.

**Comment by Morriz** [comment]
I hope this is going to be addressed still? I am not sure about the coverage of your operator and if we can do all we want with it, but I presume the api will have to be useable for a long time...

**Comment by Morriz** [comment]
Bump
