### ISSUE TITLE
Wrong image pull times and tag retention removing not correct images

### ISSUE THREAD

**Issue by KingKunn** [goharbor/harbor#14638]
**Expected behavior and actual behavior:**
- Problem: Older pushed images were actually not pulled by user nor system, but the last "pull time" field shows strange time and it won't match with "last pull" time in second place. Our tag retention removes wrong images as older images are getting newer pull time
- Waiting solution: Image pull time will be fixed? and tag retention is not removing wrong images 

**Steps to reproduce the problem:**
- Checking pull times manually
-- Projects -> choose project -> choose repository:
-- Check "Pull Time" from the last column: "4/13/21, 2:34 AM"
-- Check "PULL TIME" when holding cursor on "tags" column tag name: "1/7/21, 2:19 PM"
-- Pull times don't match
![Screenshot 2021-04-13 at 15 36 53](https://user-images.githubusercontent.com/82453016/114559768-be6ebd80-9c74-11eb-80f5-521d5bb94405.png)

- Tag retention Dry run matches with "Pull Time" in last column: "2021/04/12 23:34:27"
`
|                                 Digest                                  |       Tag       | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|-----------------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:XXX | master-39       | image |        | 2021/04/12 14:31:00 | 2021/04/12 22:45:38 | 2021/04/12 14:31:00 | RETAIN    |
| sha256:XXX | master-38       | image |        | 2021/04/07 06:02:22 | 2021/04/12 22:59:29 | 2021/04/07 06:02:22 | RETAIN    |
| sha256:XXX | development-200 | image |        | 2021/04/07 05:58:36 | 2021/04/12 22:59:33 | 2021/04/07 05:58:36 | RETAIN    |
| sha256:XXX | master-36       | image |        | 2021/01/22 09:28:44 | 2021/04/12 23:33:28 | 2021/01/22 09:28:44 | DEL       |
| sha256:XXX | master-35       | image |        | 2021/01/15 13:31:57 | 2021/04/12 23:33:54 | 2021/01/15 13:31:57 | DEL       |
| sha256:XXX | master-34       | image |        | 2021/01/07 11:53:00 | 2021/04/12 23:34:27 | 2021/01/07 11:53:00 | RETAIN    |
`

- Checking Harbor logs for the specific image
-- Logs -> resource -> Type selected image -> last pull time matches with holding cursor on "tags" column tag name": "1/7/21, 2:19 PM"
![Screenshot 2021-04-13 at 15 39 27](https://user-images.githubusercontent.com/82453016/114560290-3806ab80-9c75-11eb-8739-02772bd8f961.png)

**Versions:**
- harbor version: 2.2.0
- docker engine version: 20.10.5, build 55c4c88
- docker-compose version: 1.23.2, build 1110ad01

**Additional context:**

- **Harbor config files:** 
- **Log files:**

**Comment by bitsf** [comment]
there're two tables in the database called artifact and tag, both tables have pull_time field
if you run `docker pull xxx:tag1`, both tables will be updated.
if you run `docker pull xxx@sha256:sss`, only artifact table will be updated.
if you scan the image, it will also update the artifact table.

tag retention will check both tables, and use the latest time as pull time, for detail check https://github.com/goharbor/harbor/blob/c701ce09fa2a34b7ea26addb431154f9812de8af/src/pkg/retention/dep/client.go#L115 .

**Comment by bitsf** [comment]
I think you are using scan images, which is updating pull time.
@wy65701436 @heww is it possible not to update pull time when just doing scanning

**Comment by tob123** [comment]
can there be considered a feature that allows to scan daily AND to configure retention based on pull time ?
perhaps consider to filter retention in case the pull is done by a different user and configure that user for pulling in case of vulnerabilities ?

**Comment by KingKunn** [comment]
Hi! 
Yes, seems that vulnerability scanner is changing image pull times. Previously used clair scanner and there was no such problem, now we are using trivy.
Will remove or change "Keep last three pulled images" tag retention policy settings.

**Comment by bitsf** [comment]
we're consider not update pull time when doing scanning, or add some extra fields to distinguish the user pull from scan pull

**Comment by bitsf** [comment]
@heww @wy65701436 take a look if this can be implement

**Comment by stonezdj** [comment]
@qnetter  should we consider to fix it?

**Comment by stonezdj** [comment]
In audit log
```
29,1,pull,artifact,library/busybox:sha256:0dc78806f5885db569f7389b0e0df2e190346b0df59937268c5862d5bfc5f933,robot$library+Trivy-8c20ae69-f5c1-11ec-8fba-0242ac1e0009,2022-06-27 02:33:43.721128

```
The robot account name has this pattern start with `robot$` and contains a `+Trivy`.

**Comment by shapirus** [comment]
this may well be used in a future configuration to support skipping the image pull time update for certain users, such as the trivy robot.

**Comment by mdraijer** [comment]
Experiencing the same problem here. With many teams building images on a daily basis is complicated enough as is. But with Trivy schedule enabled - a very sensible thing of course - it becomes a nightmare. Registry is growing quickly since Trivy is active.

@stonezdj Any idea how _feasible_ it is to fix this in release 2.7.0? (Since it was targeted for 2.*3*.0 more than a year ago.)

**Comment by naitmare01** [comment]
I'm interested in a "Last scan time"!

**Comment by shapirus** [comment]
A workaround: there is now (I'm not sure I saw it before) an option in the project configuration called `Automatically scan images on push` which should not interfere with retention policies, since it should, as I expect, only run once, when the image is pushed. 

Obviously it will not help to find vulnerabilities which will only become known in the future, but it's still better than not have the images scanned at all.

**Comment by mdraijer** [comment]
@shapirus the whole point in this discussion is that we want scheduled scanning without interfering with the retention policy. So, no, your suggestion is not a work around.

@yanji09 can you tell if the target for 2.7.0 is still feasible, and _when_ 2.7.0 is expected to be released?

**Comment by wy65701436** [comment]
@qnetter we're drafting a PR to resolve this issue as linked above(**not via a scanner update pull time**).

Before moving forward, I would like to point out that this is not actually a bug fix, but a change in behavior that we should be aware of and decide if it is good to go.

If we agree to make this change, it means that the harbor has changed the default behavior of tag retention from no-delete to delete. If the user has understood and adopted this, it is a bad experience that after they upgrade to the latest harbor, the retention rules may not keep the tags he is willing to keep.

cc @stonezdj

**Comment by stonezdj** [comment]
> Yes. (Sorry I missed this.) Scanning should not update pull time. We should consider adding "Last scan time" field if enough people think it is useful.

Should we display the Last scan time in the UI? and what if the media type is not supported to scan or fails to scan image?

**Comment by qnetter** [comment]
> > Yes. (Sorry I missed this.) Scanning should not update pull time. We should consider adding "Last scan time" field if enough people think it is useful.
> 
> Should we display the Last scan time in the UI? and what if the media type is not supported to scan or fails to scan image?

It need not be last SUCCESSFUL scan. Though it would be helpful to indicate also whether successful, unsuccessful, or scanning not supported.

**Comment by qnetter** [comment]
I agree that pulls from clients is what matters. That is why I suggest distinguishing between last PULLED time and last SCANNED time (which should not update last pulled time). If there were an indicator with last scanned time of S(uccessful)/U(successful)/-(could not scan) that would be good too.

**Comment by stonezdj** [comment]
From the server side(harbor-core), it is not easy to check if the current scan is success or fail.

**Comment by qnetter** [comment]
If we can’t, we can’t - it was aspirational.

**Comment by stonezdj** [comment]
After discussion, we decided to implement it in this way


1. Add a configuration “Skip Scanner Pull Update”, if Harbor admin checks it, the scanner will not update the pull time for scanner, neither the pull count.
2. The “Last Scan Time”, because it only indicates the last time pulled by the scanner, but it can not indicate the scan success or failure, it seems this time is of no use in the UI. usually, the Harbor user will check the scan report and get the scan time in it, it is the accurate scan time user wants to know. So we will not add the “Last Scan Time” column in the artifact table.
3. In order to discriminate the scanner robot account from user created robot account, we add a UUID in the scanner robot account, it is a UUID generated by installation and the scanner robot account is named like that: `robot$<projectName>+<Scanner UUID (8byte)>-<Scanner Name>-<UUID>` and the Harbor detect the scanner robot account by prefix `robot$<projectName>+<Scanner UUID (8byte)>`
