### ISSUE TITLE
can not copy  helm charts from a harbor to another harbor

### ISSUE THREAD

**Issue by kevin-hao** [goharbor/harbor#14637]
I have two harbors Harbor_A and Harbor_B.  I have set a replication rule to copy image from Harbor_A to Harbor_B. And the stutus is Succeeded. I set another replication rule to copy helm charts from Harbor_A to Harbor_B. The status is Failed. The error is : http error: code 404, message {"code":404,"message":"not found"}. How can I set the replication rule to copy helm charts?

**Comment by wy65701436** [comment]
what's the harbor version?

**Comment by kevin-hao** [comment]
The version is 2.2.1.

**Comment by ntalekt** [comment]
We are seeing something similar in 2.2.1. We have event_based triggers setup to replicate all objects in a project. We added several new images which figured the event_based trigger, however the new helm chart didn't replicate. A manual execution of that same replication rule replicated the helm chart.

Thoughts?

**Comment by ntalekt** [comment]
Confirmed fix in 2.2.2: https://cloud-native.slack.com/archives/CC1E09J6S/p1621980197049300?thread_ts=1621980197.049300&cid=CC1E09J6S
