### ISSUE TITLE
Can not show the size of some replicated image from dockerhub

### ISSUE THREAD

**Issue by AimAlex** [goharbor/harbor#14636]
Hi,

**What happened**
I replicated an image(busybox:1.24.1) from dockerhub, and it succeeded. However, harbor does not show the size and scanner is unsupported. 

**my replication policy**
![replicationpolicy](https://user-images.githubusercontent.com/26958630/114538708-3ee9ea00-9c86-11eb-82c8-59f232ce28ed.png)

**replicated image status in harbor**
![截屏2021-04-13 下午6 19 12](https://user-images.githubusercontent.com/26958630/114538889-73f63c80-9c86-11eb-836c-fd13e7798879.png)

The image is an official image from dockerhub, and it appears normal when I push this image to harbor directly using `docker push`.

**docker push image status in harbor**
![截屏2021-04-13 下午6 55 33](https://user-images.githubusercontent.com/26958630/114542059-0c41f080-9c8a-11eb-83a3-2e458126eb73.png)

Harbor version: 2.1.4

**Comment by heww** [comment]
The image of schema 1 is not supported by both Clair and trivy scanners, so please verify that the original image from the dockerhub is not schema 1.

**Comment by AimAlex** [comment]
thanks,

yes, it is the schema 1. btw, image size is calculated by scanner? or the size calculator does not support schema 1, either?
