### ISSUE TITLE
Harbor 1.10 branch: Is there a fix that updates Clair version to fix NVD deprecated links?

### ISSUE THREAD

**Issue by pealtrufo** [goharbor/harbor#14641]
Hi! 

I have a Harbor instance running v1.10.6 and I was wondering if it was released a fix for 1.10 branch that updates Clair so that it works with the new NVD 1.1 links. Moving to Harbor 2.X is a bit challenging for me atm so I am trying to understand short term alternatives. 

I see the latest tag of 1.10.X was released in Nov'20
![image](https://user-images.githubusercontent.com/32867433/114592631-0d235400-9c83-11eb-9778-9bfd4e7ba59e.png)

And I see that there was a commit in Oct'20 that seems to update the version of Clair to 2.1.6 (which I understand fixes the issue with the NVD)
![image](https://user-images.githubusercontent.com/32867433/114592742-2a582280-9c83-11eb-85b2-bd1eb505f455.png)

Was that fix included anywhere in the 1.10 branch? 

Thanks

**Comment by wy65701436** [comment]
We highly recommend you to upgrade the latest as v1.10 is out of support now.
