### ISSUE TITLE
Checkbox display style

### ISSUE THREAD

**Issue by cobolbaby** [goharbor/harbor#14649]
**Expected behavior and actual behavior:**

![2021-04-14 15-01-38屏幕截图](https://user-images.githubusercontent.com/11460848/114667786-7f06a680-9d32-11eb-8595-19a8484d1102.png)

The checkbox is displayed on a line separately.

**Versions:**

- harbor version: v2.2.1

**Comment by ChristianCiach** [comment]
I had the same issue immediately after updating from 2.1 to 2.2. Just clear your browser cache and the issue will disappear.

**Comment by wy65701436** [comment]
can you try it with Chrome?

**Comment by cobolbaby** [comment]
Confirmed.
