### ISSUE TITLE
Fail to run GC on 1.10.3

### ISSUE THREAD

**Issue by alter** [goharbor/harbor#14655]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I've try to run GC from web panel, but got error 500 as a lot of other issues here.
```
2021-04-14T20:55:01Z [INFO] [/jobservice/job/impl/gc/job.go:87]: start to run gc in job.
2021-04-14T20:57:02Z [ERROR] [/jobservice/job/impl/gc/job.go:90]: failed to get gc result: Failed to start GC: 500

```
I've found a command for running GC manually directly from docker container
`registry garbage-collect --delete-untagged=true /etc/registry/config.yml`
but got a bug:
```
xxx/dcp-api-stub: marking blob sha256:12648d1af4a55a9242ec8d98fe99f2263bfdff7cc347411406b35145e1d2e4e7
xxx/dcp-api-stub: marking manifest sha256:750d0d8f4c6d3a36487c468eec3d03617ba78e705abcb9dff6309bac6725a1e0
failed to garbage collect: failed to mark: azure: azure: failed to retrieve manifest for digest sha256:750d0d8f4c6d3a36487c468eec3d03617ba78e705abcb9dff6309bac6725a1e0: invalid character '{' after top-level value
```

**Steps to reproduce the problem:**
connect into registryctl container and run `registry garbage-collect --delete-untagged=true /etc/registry/config.yml`

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.3]
- docker engine version: [19.03.8]
- docker-compose version: [1.22.0]

**Additional context:**
I use Azure Blob Storage as a storage for harbor

**Comment by wy65701436** [comment]
can you check the data of 750d0d8f4c6d3a36487c468eec3d03617ba78e705abcb9dff6309bac6725a1e0?  It seems that the data format is not correct.
