### ISSUE TITLE
Add unexistent user returns Server error instead of Not Found

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#14668]
**Expected behavior and actual behavior:**
Adding unexistent user (in this case with a space before the currect username) returned Server Error, instead of User Not found error (or 4xx)

**Steps to reproduce the problem:**
WITH OIDC, go to a project and add a user as member (ex: user 'myself' exists but ' myself' does not)

- harbor version: V2.2.1
**Additional context:**

**Comment by reasonerjt** [comment]
The error can be refined so that API returns 404.

**Comment by reasonerjt** [comment]
fixed in 
https://github.com/goharbor/harbor/pull/14696
https://github.com/goharbor/harbor/pull/14695
