### ISSUE TITLE
High cpu load after upgrade Harbor 2.2.1

### ISSUE THREAD

**Issue by smp1204** [goharbor/harbor#14667]
We succesfully upgraded our Harbor instance yesterday. However, at around 2 o'clock cpu usage increased massively (maybe related to garbage collector)
![Screenshot 2021-04-15 at 10 13 26](https://user-images.githubusercontent.com/82573175/114838037-9ac28900-9dd4-11eb-987b-c8ca92ec3ea6.png)

Garbage collector failed its automated run at 2 o'clock, but ran fine when started manually this morning.

So far I have followed the steps from #14358, doing:
```
select vendor_type,status,count(*) from execution group by vendor_type,status;
```
Which gives me 
```
registry=# select vendor_type,status,count(*) from execution group by vendor_type,status;
    vendor_type     | status  | count
--------------------+---------+-------
 SCHEDULER          | Running |     1
 GARBAGE_COLLECTION | Error   |     1
 IMAGE_SCAN         | Success |   240
 SCHEDULER          | Success |     2
 SCAN_ALL           | Success |     1
 RETENTION          | Success |    53
 GARBAGE_COLLECTION | Success |     3
(7 rows)
```
Followed by:
```
\c registry
update execution set status='Success' where status='Succeed';
```
and restarting harbor-core.
No luck unfortunately.

The error I am seeing in jobservice.log is
```
Apr 15 10:27:45 172.25.0.1 jobservice[1600]: ; push hook event to the queue for retrying later
Apr 15 10:27:45 172.25.0.1 jobservice[1600]: 2021-04-15T08:27:45Z [WARNING] [/jobservice/hook/hook_agent.go:121]: Send hook event 'status change: job=c19a73868859c999790a5648@1618444800, status=Success' to 'http://core:8080/service/notifications/jobs/adminjob/4' failed with error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID c19a73868859c999790a5648@1618444800 not found"}]}
Apr 15 10:27:45 172.25.0.1 jobservice[1600]: ; push hook event to the queue for retrying later
```
Could the issue be that the job doesn't exist anymore? And can I manually clear it?

**Steps to reproduce the problem:**
The problem is ever present

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.1
- docker engine version: 19.03.5
- docker-compose version: 1.25.0

**Comment by wy65701436** [comment]
can you help to provide the full job service log? It's helpfule for us to debug.

**Comment by steven-zou** [comment]
It seems the task is missed in the database as then the webhook is failed to handle, we need to check why the task is missing? cc @wy65701436 @ywk253100 

```
task with job ID c19a73868859c999790a5648@1618444800 not found
```

However, from the log data, I don't think it's related to the high CPU.

@smp1204 

Would you check if there are some other actions that happened at that time?

**Comment by ThomasRasmussen** [comment]
@steven-zou  I'm helping my colleague here... We did investigate if anything else happened, but it does not... Notice that the log statement is coming *very* often - about 7000 per minute.  There is not much other happening in the jobservice.log file. 

We have tried to restart the jobservice container (as well as entire harbor instance) without any help. 

We did infact see a error with the redis container today, which did run out of memory and needed a restart before we were able to login to the web-ui or push images.

**Comment by steven-zou** [comment]
@ThomasRasmussen

If you have seen too many resending logs, that may cause the Redis out of memory or high CPU of the core as the webhook will always not be correctly responded to. That may cause the resending to enter an infinite loop bug. 

May be similar to the issue https://github.com/goharbor/harbor/issues/14545 which has been fixed in the upcoming patch releases.

**Comment by steven-zou** [comment]
@ywk253100 

Why does the task is gone in the database as then cause the webhook will not be correctly responded to?

**Comment by steven-zou** [comment]
Might be similar to the issue mentioned [here #14683](https://github.com/goharbor/harbor/issues/14683)

**Comment by ThomasRasmussen** [comment]
> Might be similar to the issue mentioned [here #14683](https://github.com/goharbor/harbor/issues/14683)

Would the process described here https://github.com/goharbor/harbor/issues/14683#issuecomment-822958595 possibly workaround this issue? 

`redis [ ~ ]$ redis-cli -n 2 keys "{harbor_job_service_namespace}:executions*"
 1) "{harbor_job_service_namespace}:executions:a0a86ef722e84cb1b12b9b34"
 2) "{harbor_job_service_namespace}:executions:5d760ae3052690633c7f374b"
 3) "{harbor_job_service_namespace}:executions:7771b31f405ccfc4e59eff29"
 4) "{harbor_job_service_namespace}:executions:ab0ac85060597207d3993118"
 5) "{harbor_job_service_namespace}:executions:8fe0a76721358cd2a0a9f29e"
 6) "{harbor_job_service_namespace}:executions:b842cdb6c09a7840dfd14f37"
 7) "{harbor_job_service_namespace}:executions:c7207b6e516b393a6703ace8"
 8) "{harbor_job_service_namespace}:executions:e6b831d00389ee01f7c15a63"
 9) "{harbor_job_service_namespace}:executions:c19a73868859c999790a5648"
10) "{harbor_job_service_namespace}:executions:22bdd347710702b453bb60b1"
11) "{harbor_job_service_namespace}:executions:3034942aee87155762e484a0"`

`redis [ ~ ]$ redis-cli -n 2 keys "{harbor_job_service_namespace}:job_stats*" | wc -l
2767 `

**Comment by steven-zou** [comment]
2.2.2 patch release will contain fixes for this issue.

cc @smp1204 @ThomasRasmussen

**Comment by cakhanif** [comment]
i still get this problem when cronjob is running on version 2.2.2
