### ISSUE TITLE
Cannot delete project - PostgreSQL only supports 65535 parameters

### ISSUE THREAD

**Issue by warmfusion** [goharbor/harbor#14678]
When attempting to delete a seemingly empty project in harbor's UI an 'Internal Server Error' message is displayed and the harbor core pod logs show;

> 2021-04-16T15:11:31Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: pq: got 98119 parameters but PostgreSQL only supports 65535 parameters"}]}

We are using harbor 2.2.0 deployed on a Kubernetes cluster, with an external Postgres 9.6.3.

The s3 backend and database has many projects which have been deleted from the UI but remain in the DB/Storage and may be causing some issues, but without knowing what the query is that fails I can't debug any further.

**Comment by warmfusion** [comment]
I have deleted from S3 the repository data on the assumption that the 98000 entries are a list of containers etc from the repository (It was a replicated set from another OCI registry we operate as a test case).

But this has made no difference to the delete command.

**Comment by heww** [comment]
Hi, @warmfusion could you share more logs around the "got 98119 parameters but PostgreSQL only supports 65535 parameters" with us? Thanks.

**Comment by wy65701436** [comment]
can you try with the project deletion API? And provide the request & response.

**Comment by warmfusion** [comment]
The API call is not that useful;

```
curl -X DELETE "https://harbor.REDACTED.TLD/api/v2.0/projects/vanilla" -H  "accept: application/json" -H  "X-Is-Resource-Name: false" -H  "authorization: Basic REDACTED=" -v
...
< HTTP/2 500
< server: nginx/1.19.0
< date: Mon, 19 Apr 2021 18:35:29 GMT
< content-type: application/json; charset=utf-8
< content-length: 66
< set-cookie: sid=4f9f861b320bbf8a18634c29bf35c7df; Path=/; HttpOnly
< x-request-id: 38b16e3a4f2a92c74337c32fca589e4c
< strict-transport-security: max-age=15724800; includeSubDomains
<
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```

The logs from the core service are literally all i've shown you already, but here are some lines around just for clarity;

```
2021-04-19T18:34:50Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-15597, Repository-docker.io/jaegertracing/jaeger-agent Tags-[latest] Digest-sha256:83219dff5bdebc835714e9f0bdc7710058056e69e2ff1987e182baaa557083cc Operator- OccurAt-2021-04-19 18:34:50
2021-04-19T18:35:29Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: pq: got 98119 parameters but PostgreSQL only supports 65535 parameters"}]}
2021-04-19T18:36:20Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'InternalArtifact' on topic 'PULL_ARTIFACT': ID-2091, Repository-docker.io/gitlab/gitlab-runner-helper Tags-[x86_64-a8a019e0] Digest-sha256:5e1c83270146c0cb0b26708f1c4f006de3c298e71b036acdcd502eeb87fb0b24 Operator- OccurAt-2021-04-19 18:36:20
```

**Comment by warmfusion** [comment]
On a probably related note; The reason i'm trying delete the project is because some of my team are having issues pushing containers to the repo...

> INFO[0078] Pushing image to harbor.REDACTED.TLD/vanilla/fte/phpfpm:harbor-272611 
error pushing image: failed to push to destination harbor.REDACTED.TLD/vanilla/fte/phpfpm:harbor-272611: POST https://harbor.REDACTED.TLD/v2/vanilla/fte/phpfpm/blobs/uploads/: UNKNOWN: internal server error

Which is weird.

**Comment by warmfusion** [comment]
is there away i can rename the existing project so i can work around this issue ?

**Comment by heww** [comment]
> is there away i can rename the existing project so i can work around this issue ?

This only can be done by updating the record in the database. 
```sql
update project set deleted = 't', name = CONCAT(name, '#', project_id::text)  where name = 'project_name';
```

Replace the project_name with your real project name to be deleted.

**Comment by warmfusion** [comment]
Cool...

So while rummaging around the database, I think i worked out which table is causing the problem;
The vanilla project i'm tryting to delete is project_id 7

Look at the robots count;

```
harbor_core=# select project_id, count(1) from robot group by project_id;
 project_id | count
------------+-------
        862 |     1
        861 |     1
          0 |     1
        865 |     1
          9 |   333
        863 |     1
          7 | 98120
(7 rows)
```

All the robots are named; ` robot$Clair-` with description `for scan`

So this looks to be where the trouble is caused.

**Comment by heww** [comment]
Thanks, @warmfusion, this info is so helpful to me to resolve this issue.
