### ISSUE TITLE
Project name already exists.

### ISSUE THREAD

**Issue by softmarch** [goharbor/harbor#14684]
What can we help you?
![image](https://user-images.githubusercontent.com/22042539/115218865-9205e600-a139-11eb-945e-0c4b611accc0.png)

**Comment by softmarch** [comment]
![image](https://user-images.githubusercontent.com/22042539/115345651-adc4c700-a1e1-11eb-8753-e48befdcf70c.png)

**Comment by softmarch** [comment]
![image](https://user-images.githubusercontent.com/22042539/115348070-c08ccb00-a1e4-11eb-90b3-36172ee08866.png)
postman 创建成功

**Comment by wy65701436** [comment]
hi, what's your query? Could you please give more details?version, steps?

**Comment by softmarch** [comment]
> hi, what's your query? Could you please give more details?version, steps?

v2.2.1

in v2.0.6:
sudo docker-compose down -v
remove v2.0.6 docker images
sudo rm -rf /data

harbor.yml The following parameters are modified:

hostname: reg.xxx.cn
# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 8500
# https related config
# https:
  # https port for harbor, default is 443
  # port: 443
  # The path of cert and key files for nginx
  # certificate: /your/certificate/path
  # private_key: /your/private/key/path
external_url: https://reg.xxx.cn

in v2.2.1:
sudo ./install.sh

There is no problem installing v2.2.1 on a server that has not installed v2.0.6.

**Comment by AllForNothing** [comment]
Can you provide more info from your browser debug mode? Like this :
![image](https://user-images.githubusercontent.com/30999793/116338934-21348d00-a80f-11eb-9bae-b6658c2b6b0d.png)
And the log in /var/log/harbor/core.log  for   this API call

**Comment by softmarch** [comment]
![image](https://user-images.githubusercontent.com/22042539/116339781-a0769080-a810-11eb-840c-e36d0ae5688b.png)

**Comment by heww** [comment]
Hi, @softmarch could you try to call this API by curl?

**Comment by softmarch** [comment]
```shell
curl -X HEAD -vk "https://reg.softmarch.cn/api/v2.0/projects/?project_name=fffffs"
```

```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
*   Trying 81.68.196.x:443...
* TCP_NODELAY set
* Connected to reg.softmarch.cn (81.68.196.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=reg.xxx.cn
*  start date: Apr 20 05:52:09 2021 GMT
*  expire date: Jul 19 05:52:09 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x562678359820)
> HEAD /api/v2.0/projects/?project_name=fffffs HTTP/2
> Host: reg.xxx.cn
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< server: nginx
< date: Wed, 28 Apr 2021 03:34:26 GMT
< content-type: application/json
< content-length: 468
< set-cookie: sid=2880e334944389a5aa9ccff75dc7189d; Path=/; HttpOnly
< x-request-id: 429906a3-382e-41fa-a420-c9301ea6e278
< x-total-count: 1
< x-frame-options: DENY
< content-security-policy: frame-ancestors 'none'
< expires: Wed, 28 Apr 2021 15:34:26 GMT
< cache-control: max-age=43200
< x-cache: MISS
< cache-control: no-cache
<
* transfer closed with 468 bytes remaining to read
* stopped the pause stream!
* Connection #0 to host reg.softmarch.cn left intact
curl: (18) transfer closed with 468 bytes remaining to read
```
