### ISSUE TITLE
Provide higher-resolution images for users and partners

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#14685]
issue ported over from https://github.com/goharbor/website/issues/36

The current user and partner logos are very grainy. Better improved would provide a quick aesthetic win.

From @jonasrosland, ```I'll keep this issue open, but we have implemented higher-res images for most of the users and partners on the new website. I think it warrants a second pass though, before closing. ```

**Comment by a-mccarthy** [comment]
@jonasrosland do you have any follow up to do on this?

**Comment by a-mccarthy** [comment]
@OrlinVasilev do you have any thoughts on this? Do you think there is a need for better logo images for the harbor site? https://goharbor.io/ (scroll down to Harbor users)

**Comment by OrlinVasilev** [comment]
IMHO it will be better! For example Aqua's, OVH Cloud and Tensor are great clear and sharp, the others a bit blurry and are not pleasant to read. But in general is not a big issue!

**Comment by a-mccarthy** [comment]
@OrlinVasilev I remember we talked about this a while ago, but I dont remember if you had been working on it. Is there an update you can provide? thanks

**Comment by OrlinVasilev** [comment]
@a-mccarthy we have to rework the whole thing about partners and adopters, as of right now we don't have clear definition and process for partners! Will open general issue to rework it so we can discuss!

**Comment by a-mccarthy** [comment]
@OrlinVasilev for now i'm going to close this issue, since there isn't any action to take at the moment. Did you have a chance to open the other issue about partner processes? If so we should make a note to include updating the images

**Comment by OrlinVasilev** [comment]
We can close is indeed because it's not worked on, we have to rework the whole section there as we don't actually have partners we have adopters :) If you share the same I can open issue and we can work on that :)

**Comment by a-mccarthy** [comment]
@OrlinVasilev i think that makes sense. I'll close this one and you can open a new issue for figuring out partners/adopters stuff? :)
