### ISSUE TITLE
add helm repo with robot account

### ISSUE THREAD

**Issue by rrgadeev** [goharbor/harbor#14693]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
adding a HELM repo using global robot account
helm repo add --username=robot\$rancher --password='*****' harbor https://harbor.local/chartrepo
I get an error:
Error: looks like "https://harbor.local/chartrepo" is not a valid chart repository or cannot be reached: failed to fetch https://harbor.local/chartrepo/index.yaml : 403 Forbidden
If you use a domain account, everything works

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
Create robot account
add charts in project
helm repo add --username=robot\$rancher --password='*****' harbor https://harbor.local/chartrepo

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.1
- docker engine version: 20.10.1
- docker-compose version: 1.25.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

core.log
Apr 20 10:08:29 30.30.11.1 core[758]: 2021-04-20T07:08:29Z [ERROR] [/server/middleware/security/robot.go:45][requestID="ac63e3b9-da2b-4ffc-8534-ad0b84afa7d9"]: failed to decrypt robot token: token contains an invalid number of segments
Apr 20 10:08:29 30.30.11.1 core[758]: 2021-04-20T07:08:29Z [INFO] [/server/middleware/security/robot2.go:74][requestID="ac63e3b9-da2b-4ffc-8534-ad0b84afa7d9"]: a robot2 security context generated for request GET /chartrepo/index.yaml

**Comment by rgadeev** [comment]
chart:
  # Change the value of absolute_url to enabled can enable absolute url in chart
  absolute_url: disabled
maybe that's the problem

**Comment by failytaler** [comment]
@rgadeev No, this is not the issue :(

**Comment by ChrisJBurns** [comment]
I am also getting 403 forbidden error when trying to hit my `/chartrepo/create/index.yaml` file via basic REST.

Hitting the endpoint with my robot account credentials:
`curl --location --request GET 'blabh.blah.harbor.com/chartrepo/create/index.yaml' \
--header 'Authorization: Basic robot-username:roboy-password'`

However if I hit it with the admin credentials I can see the `yaml` come back successfully - so there seems to be some robot account permission issues here which isn't ideal.

**Comment by discostur** [comment]
Problem still exists ... just tried to add the helm repo with harbor v2.4.1 and a robot token but its not possible:

```bash
$helm repo add dockerhub.tld.com https://hub.tld.com/chartrepo --username 'robot$gitlab-ci' --password XXX
Error: looks like "https://hub.tld.com/chartrepo" is not a valid chart repository or cannot be reached: failed to fetch https://hub.tld.com/chartrepo/index.yaml : 403 Forbidde
```

Tried the same request with another admin account (no robot account) works:

```bash
$helm repo add hub.tld.com https://hub.tld.com/chartrepo --username 'kilian.ries' --password XXX
"hub.tld.com" has been added to your repositories
```

**Comment by discostur** [comment]
Tried today with new oci version of helm chart storage and it works:

```
helm registry login https://hub.tld.com --username 'robot$gitlab-ci' --password 'XXX'
helm package ingress-nginx
helm push ingress-nginx-4.1.0-beta.1.tgz oci://hub.tld.com/library
``` 

Maybe thats only related to the old chartmuseum. Will be switching to new oci now ...

**Comment by rrgadeev** [comment]
https://github.com/goharbor/harbor/issues/14693#issuecomment-1102786869
