### ISSUE TITLE
Quick install script needs updating

### ISSUE THREAD

**Issue by mduijm** [goharbor/harbor#14694]
From your website this script:
https://goharbor.io/docs/2.0.0/install-config/quick-install-script/

needs some updating:

1. it needs the harbor.yml file in the harbor folder, however the download get a .yml.tmpl file which needs rename
2. the install script starts the installation with --with-clair, which is depracated
3. According to the site:
This script installs Harbor with an HTTP connection, Clair, and the Chart Repository Service. It does not install Notary, which requires HTTPS.

However it doesn't install it, it throws an error. I disabled https in the config file, which is also throwing errors. Can you fix this? 

thank you

**Comment by wy65701436** [comment]
Sure, some details that needs to be updated. Thanks for pointing.

**Comment by a-mccarthy** [comment]
Thanks for raising this issue. The script behind this page is no longer being maintained. This page was removed from the 2.2 docs, https://github.com/goharbor/website/pull/176#issuecomment-785409372, but it should also have been removed from the previous versions.
