### ISSUE TITLE
Support IPv6 for Harbor

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#14690]
This is the Epic of engineering work for tracking the requirement https://github.com/goharbor/harbor/issues/11399.

**Comment by a-mccarthy** [comment]
@ninjadq do you expect any documentation updates needed for this? thank! :)

**Comment by ninjadq** [comment]
Hi @a-mccarthy, from now on there are no changes that will impact user experiences. I will notify you if we need doc updates. Thanks
