### ISSUE TITLE
How to log in via token like docker hub or github packages ?

### ISSUE THREAD

**Issue by xiaozhi747** [goharbor/harbor#14697]
I know that the harbor has robots to support tokens, but its account and token have a one-to-one relationship. I want the account and token to have a one-to-many relationship. How can I do it? Thank you.

**Comment by wy65701436** [comment]
do you mean the system robot account? If so, just try it with v2.2, see the release notes and goharobr.io to get more details.

**Comment by xiaozhi747** [comment]
> do you mean the system robot account? If so, just try it with v2.2, see the release notes and goharobr.io to get more details.
Not a robot system account, but I have solved it, thank you

**Comment by xiaozhi747** [comment]
> do you mean the system robot account? If so, just try it with v2.2, see the release notes and goharobr.io to get more details.

Not a robot system account, but I have solved it, thank you
