### ISSUE TITLE
how to uninstall harbor with docker on linux?

### ISSUE THREAD

**Issue by Pedrocho** [goharbor/harbor#14715]
Hi Everyones,

how to uninstall harbor with docker on linux? .  what are the steps? .  I can't find how to do it

Thanks  for your help.

**Comment by wy65701436** [comment]
how did you install Harbor? If with docker-compose, just call `docker-compose down -v`

**Comment by yioda** [comment]
You could take a look in here: [Reconfigure Harbor and Manage the Harbor Lifecycle](https://goharbor.io/docs/1.10/install-config/reconfigure-manage-lifecycle/)

To remove containers

``` bash
sudo docker-compose down -v
```

To remove all data

``` bash
rm -r /data/database
rm -r /data/registry
```

Change the path `/data/...` you set in config file.
