### ISSUE TITLE
goharbor/prepare Where is this repository?

### ISSUE THREAD

**Issue by namalk** [goharbor/harbor#14710]
Hi,
Im now to harbor  and trying to get harbor up and running in my servers which are not connected to internet. 
Offline installer helps in this case a lot. 

Just wondering where is the repo for "prepare" and what it does?

Can anyone please point me to the corresponding repository?

Cheers

**Comment by reasonerjt** [comment]
The code for prepare is in this repo:
https://github.com/goharbor/harbor/tree/master/make/photon/prepare

It's a bunch of python scripts that generates the required files and docker-compose yaml .
