### ISSUE TITLE
Info graph and api for Storage is responding NAN

### ISSUE THREAD

**Issue by mohit94614** [goharbor/harbor#14719]
`private-registry.com/api/v2.0/systeminfo/volumes 
`
Is Returning empty response when used with NFS as Backing storage 
```
{"storage":[{}]}
```

![image](https://user-images.githubusercontent.com/17672906/115542895-62341b00-a2be-11eb-9452-7aafd862b710.png)

At the same time we have other harbor instance with S3 as storage Same response of API for storage but not able to see the infographic.
![image](https://user-images.githubusercontent.com/17672906/115543980-a83dae80-a2bf-11eb-94d7-c5bd446dc627.png)

Working as expected on Linux VM Docker-based deployment. 

All the instance are running on the same Version :> Harbor version Version v2.2.0-ec0ba116

Let me know, if further details are required

**Comment by kingc1** [comment]
Seeing the same issue on our k8s deployment.  We are using the k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.10.0 to manage storage.

**Comment by AllForNothing** [comment]
Related back-end PR  #14772

**Comment by AllForNothing** [comment]
Close it  as both back-end  and front-end PRs merged
