### ISSUE TITLE
The scanner is still get touched even with "with_scan_overview=false" query string when listing artifacts

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#14716]
We found that calling the listing artifacts API is getting slow(more that 30s) when the Trivy scanner unreachable even with the `with_scan_overview=false` query string

**Comment by ywk253100** [comment]
And we need to double check the code why when scanner is unhealthy listing artifacts becomes slow

**Comment by reasonerjt** [comment]
BTW this is saw in a debug session whose deployment is on v2.1.3

**Comment by heww** [comment]
In this API, the scanner metadata was used to get the vulnerability addition link even this `with_scan_overview=false`, it's by design.

I will cache the metadata of the scanner to improve the pref.

**Comment by heww** [comment]
The cache of metadata was cherry-picked to release-2.2.0 and also be merged in master.

Due to the missing of `lib/cache` pkg in release-2.1.0 so this improvement will not be backported to release-2.1.0.

Closed by #14879 #14883
