### ISSUE TITLE
Cannot add a replication rule between two Harbor instances

### ISSUE THREAD

**Issue by Sumukha15** [goharbor/harbor#14721]
I am trying to create a replication between two Harbor instances: Harbor on an AWS EC2 and a Harbor hosted On-Prem.

Any type of replication (Pull/Push) from Harbor On-Prem to Harbor AWS is not working. The Harbor AWS registry endpoint in Harbor On-Perm is added successfully when the verify remote cert option is unchecked.

![Screen Shot 2021-04-21 at 4 43 44 PM](https://user-images.githubusercontent.com/77364204/115630295-04550280-a2c1-11eb-8a55-31ca014289f8.png)

The registry connection is unsuccessful when I check the verify remote cert option.

![Screen Shot 2021-04-21 at 4 44 51 PM](https://user-images.githubusercontent.com/77364204/115630368-25b5ee80-a2c1-11eb-9c94-14388d0fa9fe.png)

Harbor EC2 instance on AWS is running behind an ALB which has cert from ACM and I have a self-signed cert on the Harbor application.

When I add the registry in replication, there is an "Internal Server Error". When I force save the replication rule and initiate the rule, I get the "Failed to get the adapter" 404 error.

![Screen Shot 2021-04-21 at 4 48 54 PM](https://user-images.githubusercontent.com/77364204/115630731-c3112280-a2c1-11eb-9f6c-6fd7f5935476.png)

Even thought the destination Harbor is secured, cURL from the On-Prem Harbor is throwing an error "curl: (60) SSL certificate problem: self signed certificate. More details here: https://curl.haxx.se/docs/sslcerts.html. curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it."

Any thoughts on what I am missing or additional information would greatly help.

Thank you.

**Comment by Vad1mo** [comment]
can you pull and push images from you desktop to Harbor on EC2 and on Prem?

**Comment by bitsf** [comment]
it looks like the cert you apply from the ACM for the AWS Harbor is not trusted. 
Where and how did you apply this cert ?
