### ISSUE TITLE
"HEAD responses have no body" by concurrent pushes

### ISSUE THREAD

**Issue by llech** [goharbor/harbor#14738]
I've installed goharbor using Helm Charts, with PostgreSQL as backend, and external storage to NFS.
I haven't configured any parameters beyond that what was necessary (DB, claims). 

I've configured a project with active docker images vulnaribility scan.

Single pushes make no problem. But when I've started a pipeline, that was building many images concurrently, I started getting errors "HEAD responses have no body".

In logs it looks like that:
INFO[0015] Pushing image to goharbor.local.url/repo:tag
error pushing image: failed to push to destination goharbor.local.url/repo:tag: HEAD https://goharbor.local.url/v2/build/repo/blobs/sha256:<sha>: unexpected status code 500 Internal Server Error (HEAD responses have no body, use GET for details)

The build is made by kaniko (latest). 

Are the default settings not production ready? What do I need to configure to be able to use that productively?
The error occurs by the very few concurrent pushes, less than 10.

**Comment by heww** [comment]
Hi, @llech  could you share the logs of harbor with us?

**Comment by llech** [comment]
> Hi, @llech could you share the logs of harbor with us?

Hello,
The problem is that I haven't found anything specific to the error in the logs of harbor-registry and harbor-portal. Only the infos about the success and about the healthcheck probes.

But I have suspition, it has to do with depleted number of connections to the postgresql server, because other product had such problem in the same time, and it had logged it to his logs.
