### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by anselmhou** [goharbor/harbor#14737]
What can we help you?

I'm not sure is it expected but just let you know that the https://demo.goharbor.io/ is not accessible and giving HTTP 502 bad gateway as on HKT 16:37 today.

Thanks,
Anselm

**Comment by wy65701436** [comment]
@ywk253100 please help to recover it

**Comment by ywk253100** [comment]
@anselmhou Thank you for reporting this. The website is recovered now
