### ISSUE TITLE
Token Error when attempting Docker Login

### ISSUE THREAD

**Issue by npampaloni** [goharbor/harbor#14732]
Good Morning! I am facing an issue after a fresh install where docker login fails with a 500 internal server error.

**Expected behavior and actual behavior:**
A user trying to login with docker login mydomain.com receives the following error:

`Error response from daemon: Get https://mydomain.com/v2/: received unexpected HTTP status: 500 Internal Server Error`

/var/log/harbor/core.log contains the following:

`Apr 22 09:41:46 172.18.0.1 core[5646]: 2021-04-22T13:41:46Z [ERROR] [/core/service/token/token.go:49]: Unexepected error when creating the token, error: unable to get PrivateKey from PEM type: PRIVATE KEY`

This error occurs with the default root.crt and private_key.pem files located in /data/secret/registry/ and /data/secret/core/ respectively and when I replace those two files with my own internal private key and certificate file per [these](https://goharbor.io/docs/2.2.0/install-config/customize-token-service/) instructions. 

**Steps to reproduce the problem:**
Fresh install of Harbor using offline installation bundle. Once installation is complete run `docker login mydomain.com`.

**Versions**

- Host OS: [Centos 7.8]
- Docker Engine Version:  [20.10.2]
- Docker-Compose Version: [1.28.2]

**Additional Context**
Offline installation in an air-gapped environment.

**Comment by wy65701436** [comment]
What's the reuslt with the default root.crt and private_key.pem files?

**Comment by npampaloni** [comment]
The result is the same with the defaults.

**Comment by npampaloni** [comment]
Any update on this?
