### ISSUE TITLE
The home page shows NaNGB capacity

### ISSUE THREAD

**Issue by mcck** [goharbor/harbor#14730]
主页显示NaNGB的容量

![image](https://user-images.githubusercontent.com/20223048/115694000-09828200-a393-11eb-8dc8-60329fa874b4.png)

harbor version: v2.2.1
docker version: 19.03.12
helm version: 1.6.1
![image](https://user-images.githubusercontent.com/20223048/115694557-8f9ec880-a393-11eb-96a8-aeeb157abdec.png)

Harbor config files
[harbor-deploy.zip](https://github.com/goharbor/harbor/files/6357306/harbor-deploy.zip)

**Comment by wy65701436** [comment]
it because that Harbor core cannot access the host storage to get the real data, this feature is supposed to be provided by the platform instead of application. We're planning to remove it and replace with total storage consumption of All artifacts.

**Comment by AllForNothing** [comment]
Duplicated issue of  #14719,  and close this one
