### ISSUE TITLE
How does the project name carry special characters except"._-", such as "/"

### ISSUE THREAD

**Issue by xiaozhi747** [goharbor/harbor#14743]
How does the project name carry special characters except"._-", such as "/"

![image](https://user-images.githubusercontent.com/19251872/115983928-db8d7f80-a5d6-11eb-955b-841931fa9543.png)

harbor version: v2.2.1

**Comment by AllForNothing** [comment]
@xiaozhi747 
No special character is allowed , except for ".","_", and "-".

**Comment by xiaozhi747** [comment]
> @xiaozhi747
> No special character is allowed , except for ".","_", and "-".

How can I customize this part of the rules to support other special characters? Such as "/"

**Comment by AllForNothing** [comment]
@xiaozhi747 
You need to remove the validators from both UI and back-end  source code and rebuild Harbor,
 or you can directly modify the project name in the DB

**Comment by xiaozhi747** [comment]
@AllForNothing 
Thank you, I've now understood

**Comment by a-mccarthy** [comment]
@wy65701436 please let me know if there is anything specific you'd like added, otherwise i'll leave this as closed. thanks!
