### ISSUE TITLE
change project name?

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#14750]
when i create proiect in WEB UI, example:  the project name is 'goharbor'， then i want change the project name 'k8sharbor'?
how can i change it? in the WEB Ui  ,I can't find this change buttow.........

**Comment by phin1x** [comment]
You can't change the name of a project. you have to create a new project, retag all images or copy the images with a tool like skopeo from the old to the new project.

**Comment by wy65701436** [comment]
You cannot change the project name, either via UI or API. Just use the delete and create as the workaround.
