### ISSUE TITLE
Make adding Labels as an event for replication

### ISSUE THREAD

**Issue by shashankkmurthy** [goharbor/harbor#14765]
**Is your feature request related to a problem? Please describe.**
We should consider adding labels also as events. This helps in reducing the number of projects in Harbor.

**Describe the solution you'd like**
Adding a label to an image should trigger an event based replication job.

This way it will be more helpful for using labels not just for filtering but also for replication.

**Comment by phin1x** [comment]
@shashankkmurthy out of interest how could this feature help you reducing the number of projects?

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/13015

**Comment by shashank-k** [comment]
> @shashankkmurthy out of interest how could this feature help you reducing the number of projects?

@phin1x 
Lets say I have a project which has to replicate images to multiple registries, in different regions. We can use filters as the names of the regions and have get this replication done. We tried with tagging but its of very less help.
Currently we are having multiple projects for the same application and if we start using labels, all of these can be consolidated into one.
