### ISSUE TITLE
core nginx jobservice unhealthy

### ISSUE THREAD

**Issue by somnuscq** [goharbor/harbor#14769]
docker-compose up -d
About half an hour, docker ps,will get unhealthy service, as follow:
![image](https://user-images.githubusercontent.com/25476788/116345727-4deea180-a81b-11eb-90a6-11d946b981d0.png)

cat /var/log/harbor/core.log
![image](https://user-images.githubusercontent.com/25476788/116345921-afaf0b80-a81b-11eb-943a-b7692a637aca.png)
but get into the redis docker container, redis-cli ping, can get  pong
but from outside, cannot connect

**Comment by ywk253100** [comment]
Seems it's related with your env
