### ISSUE TITLE
proxy cache: Error response from daemon: unauthorized: http status code: 401, body:

### ISSUE THREAD

**Issue by 7rouz** [goharbor/harbor#14767]
When pulling a docker image from proxy-cache that I have configured I get this error 
`Error response from daemon: unauthorized: http status code: 401, body:`

Pulling and pushing images from other repositories (private or public) work fine.

**logs:**
```
 docker image pull HARBOR.URL/proxy/alpine
Using default tag: latest
Error response from daemon: unauthorized: http status code: 401, body:

```
Didn't find any significant logs in log files but this one in **proxy.log**

```
Apr 27 15:04:27 xxxxxxxxxxxxxxxxxxxxxxxxx.compute.internal proxy[1414]: XXX.XXX.XXX.XXX - "GET /v2/proxy/alpine/manifests/latest HTTP/1.1" 401 79 "-" "docker/18.09.9 go/go1.11.13 git-commit/039a7df kernel/3.10.0-1160.11.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.9 \x5C(linux\x5C))" 0.857 0.857 .
```

**Harbor version :** 2.2.1
I am also using **http_proxy**, **https_proxy** and **no_proxy** to access docker hub 

**additional info:**
I configured a replication job to see if harbor can pull images from docker hub to a local repository and it works fine.

Can you help  to understand why I have this behavior ? where should I look to get more logs ?

**Comment by phin1x** [comment]
@7rouz can you try "HARBOR.URL/proxy/**library**/alpine" for the image.

**Comment by 7rouz** [comment]
hello @phin1x 

Yes it works !!
Thank you for your help 

PS:
Sorry I just saw that it was montioned in the [configure proxy cache documentation](https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/) . For some raison I did not pay attention to that !
