### ISSUE TITLE
when I run ./install.sh, get the error: raise Exception('cert file {} should include SAN'.format(filename))

### ISSUE THREAD

**Issue by jimmy0** [goharbor/harbor#14763]
I have generate the internal certs by the command:
`docker run --rm -v /:/hostfs goharbor/prepare:v2.1.4 gencert -p /etc/harbor/tls/internal`

[root@one ~]# ll /etc/harbor/tls/internal
total 156
-rw-r--r-- 1 root root 1826 Apr 27 14:08 chartmuseum.crt
-rw-r--r-- 1 root root 1675 Apr 27 14:08 chartmuseum.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 chartmuseum.key
-rw-r--r-- 1 root root 1826 Apr 27 14:08 clair_adapter.crt
-rw-r--r-- 1 root root 1679 Apr 27 14:08 clair_adapter.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 clair_adapter.key
-rw-r--r-- 1 root root 1818 Apr 27 14:08 clair.crt
-rw-r--r-- 1 root root 1667 Apr 27 14:08 clair.csr
-rw-r--r-- 1 root root 3268 Apr 27 14:08 clair.key
-rw-r--r-- 1 root root 1814 Apr 27 14:07 core.crt
-rw-r--r-- 1 root root 1667 Apr 27 14:07 core.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:07 core.key
-rw-r--r-- 1 root root 1822 Apr 27 14:08 harbor_db.crt
-rw-r--r-- 1 root root 1675 Apr 27 14:08 harbor_db.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 harbor_db.key
-rw-r--r-- 1 root root 1911 Apr 27 14:01 harbor_internal_ca.crt
-rw-r--r-- 1 root root 3272 Apr 27 14:01 harbor_internal_ca.key
-rw-r--r-- 1 root root   17 Apr 27 14:08 harbor_internal_ca.srl
-rw-r--r-- 1 root root 1822 Apr 27 14:07 job_service.crt
-rw-r--r-- 1 root root 1675 Apr 27 14:07 job_service.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:07 job_service.key
-rw-r--r-- 1 root root 1826 Apr 27 14:08 notary_server.crt
-rw-r--r-- 1 root root 1679 Apr 27 14:08 notary_server.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 notary_server.key
-rw-r--r-- 1 root root 1826 Apr 27 14:08 notary_signer.crt
-rw-r--r-- 1 root root 1679 Apr 27 14:08 notary_signer.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 notary_signer.key
-rw-r--r-- 1 root root 1818 Apr 27 14:07 proxy.crt
-rw-r--r-- 1 root root 1667 Apr 27 14:07 proxy.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:07 proxy.key
-rw-r--r-- 1 root root 1822 Apr 27 14:07 registry.crt
-rw-r--r-- 1 root root 1671 Apr 27 14:07 registry.csr
-rw-r--r-- 1 root root 1826 Apr 27 14:07 registryctl.crt
-rw-r--r-- 1 root root 1675 Apr 27 14:07 registryctl.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:07 registryctl.key
-rw-r--r-- 1 root root 3272 Apr 27 14:07 registry.key
-rw-r--r-- 1 root root 1826 Apr 27 14:08 trivy_adapter.crt
-rw-r--r-- 1 root root 1679 Apr 27 14:08 trivy_adapter.csr
-rw-r--r-- 1 root root 3272 Apr 27 14:08 trivy_adapter.key

And I have edit the internal_tls in harbor.yml
internal_tls:
  enabled: true
  dir: /etc/harbor/tls/internal

then I run the install.sh, get the error
`[root@one harbor]# ./install.sh 

[Step 0]: checking if docker is installed ...

Note: docker version: 20.10.2

[Step 1]: checking docker-compose is installed ...

Note: docker-compose version: 1.26.2

[Step 2]: preparing environment ...

[Step 3]: preparing harbor configs ...
prepare base dir is set to /usr/local/src/harbor
Clearing the configuration file: /config/portal/nginx.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/core/env
Clearing the configuration file: /config/core/app.conf
Clearing the configuration file: /config/registry/passwd
Clearing the configuration file: /config/registry/config.yml
Clearing the configuration file: /config/registryctl/env
Clearing the configuration file: /config/registryctl/config.yml
Clearing the configuration file: /config/db/env
Clearing the configuration file: /config/jobservice/env
Clearing the configuration file: /config/jobservice/config.yml
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Generated configuration file: /config/registryctl/config.yml
Generated configuration file: /config/db/env
Generated configuration file: /config/jobservice/env
Generated configuration file: /config/jobservice/config.yml
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 54, in prepare
    prepare_tls(config_dict)
  File "/usr/src/app/utils/internal_tls.py", line 4, in prepare_tls
    config_dict['internal_tls'].validate()
  File "/usr/src/app/models.py", line 116, in validate
    self._check(filename)
  File "/usr/src/app/models.py", line 104, in _check
    raise Exception('cert file {} should include SAN'.format(filename))
Exception: cert file harbor_db.crt should include SAN
[root@one harbor]# `

How to fix this? Thanks.

**Comment by ninjadq** [comment]
the prepare script generated certs not include the SAN section. 
this https://github.com/goharbor/harbor/pull/13810 PR should cherry-pick to 2.1 branch

**Comment by ninjadq** [comment]
hi @jimmy0  We will fix it in the 2.1.6, as a workaround you can use  higher version of `goharbor/prepare` like `2.2.x` to generate certs

**Comment by jimmy0** [comment]
Thanks. I fix it as your advice.
`docker run --rm -v /:/hostfs goharbor/prepare:v2.2.1-dev gencert -p /etc/harbor/tls/internal`
