### ISSUE TITLE
Unable to upload image : always retrying

### ISSUE THREAD

**Issue by bledieu** [goharbor/harbor#14766]
I first installed Harbor on a debian machine hosted by OVH with success.
My company choose to migrate on Oracle after the OVH site has burn and we lost our backup, so I install Harbor on a CentOS oracle machine.

I success to log on the UI, create a new project but I am not able to send any image from anywher (local computer / azure pipeline / ...).

The layout are always retring 5 times, then I get a "EOF" and nothing more
![image](https://user-images.githubusercontent.com/17746828/116213088-c5ea9800-a745-11eb-8002-f24d5aa52933.png)

Here is the core.log
![image](https://user-images.githubusercontent.com/17746828/116213482-1e219a00-a746-11eb-99f9-a0d3e628c861.png)

And the proxy.log
![image](https://user-images.githubusercontent.com/17746828/116213728-545f1980-a746-11eb-958c-a841f2b8acf4.png)
![image](https://user-images.githubusercontent.com/17746828/116213815-6476f900-a746-11eb-964e-ba168169aeba.png)

The registry.log
![image](https://user-images.githubusercontent.com/17746828/116214011-94260100-a746-11eb-8e79-9d0260ab3641.png)

Additional information :
My harbor stands behind a traefik.

harbor.yml
![image](https://user-images.githubusercontent.com/17746828/116214345-e7984f00-a746-11eb-8c11-223e3e72bffd.png)

version 2.0.0

Any help to understand will be very appreciate (and sorry for my poor english !)

**Comment by heww** [comment]
Do you enable the HTTPS port for the harbor?

**Comment by bledieu** [comment]
Thanks a lot to spend time to answer.

 

No, I haven’t, because traefik ensure I only access to Harbor through a https connection.

I don’t want to manage https and certificate through Harbor config because it is already done previously.

 

In my previous config (on OVH server), this was exactly the same configuration … I believe ! Perhaps am I doing something wrong.

 

Do you want my harbor.yml and the matching docker-compose.yml ?

 

Baptiste

 

De : He Weiwei ***@***.***> 
Envoyé : mardi 27 avril 2021 13:43
À : goharbor/harbor ***@***.***>
Cc : bledieu ***@***.***>; Author ***@***.***>
Objet : Re: [goharbor/harbor] Unable to upload image : always retrying (#14766)

 

Do you enable the HTTPS port for the harbor?

**Comment by ywk253100** [comment]
Set debug option for the docker client and check its log, it should report more detail information

**Comment by bledieu** [comment]
Hello,

 

Once again, thanks a lot for helping me.

Here is the log.

 

Does it help ?

 

Baptiste Ledieu

 

De : Wenkai Yin(尹文开) ***@***.***> 
Envoyé : mercredi 28 avril 2021 04:52
À : goharbor/harbor ***@***.***>
Cc : bledieu ***@***.***>; Author ***@***.***>
Objet : Re: [goharbor/harbor] Unable to upload image : always retrying (#14766)

 

Set debug option for the docker client and check its log, it should report more detail information

**Comment by ywk253100** [comment]
Cannot see any logs in the github issue page

**Comment by bledieu** [comment]
[log.zip](https://github.com/goharbor/harbor/files/6401190/log.zip)
Sorry for the delay,

Here are the logs

**Comment by ywk253100** [comment]
Seems you are using the docker client on windows, could you try to push on a linux OS?

BTW, could you check that whether the traefik receives any docker push traffic?
