### ISSUE TITLE
transport: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zyitingftnt** [goharbor/harbor#14780]
I have 2 Harbor nodes and 2 external NFS servers connected as below:

NFS1-------mounted_to----------Node1
   ^
    |
 lsyncd syncing the whole /data folder from NFS2 to NFS1
    |
    |
NFS2-------mounted_to----------Node2
both NFS servers contain the same /data directory. Everything works find with push and pull when I connect through Node2.

Now, if I stop the lsyncd and reverse it from NFS1 to NFS2 and try the same operations through Node1 as below

NFS1-------mounted_to----------Node1
    |
    |
 lsyncd syncing the whole /data folder from NFS2 to NFS1
    |
    v
NFS2-------mounted_to----------Node2

I got this error message:
Apr 28 21:20:57 10.111.48.1 notary-server[9365]: {"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"Self-signed by GoHarbor\\\")\"","time":"2021-04-29T04:20:57Z"}

I don't understand since all happened with the same client, same Nodes and all filed synced and the same on both NFS server.

**Comment by zyitingftnt** [comment]
I wonder what information in which place does Harbor use to validate the certificates presented by the client.

**Comment by ywk253100** [comment]
I guess the error is reported when the notary server trying to connect to the notary signer.
The certificate of notary signer isn't trusted by the notary server.

**Comment by zyitingftnt** [comment]
I close this since it is resolved now. It was due to a missing step when bring up the harbor, needed to rerun the prepare script to load the necessary certificates to right folder.
