### ISSUE TITLE
OIDC doesn't support token signing algorithms other than RS256

### ISSUE THREAD

**Issue by shawngmc** [goharbor/harbor#14787]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: Harbor should be able to negotiate the token signing algorithm and onboard/login users via OIDC.
Actual: Harbor appears to be able to use the OIDC Provider; however, any OIDC login attempt fails.

**Steps to reproduce the problem:**
1) Install Harbor
2) Log In to Web UI as Admin
3) Configure OIDC Authentication against an OIDC provider that does not support RS256 (for example, allows RS512 only)

**Versions:**
- harbor version: 2.0.3
- docker engine version: 20.10.5
- docker-compose version: 1.18.0

**Additional context:**
I'm using an air-gapped system, so I can't provide the Harbor config or full logs; I don't have an RS512-only OIDC provider in my homelab to reproduce the issue, either. From a general perspective, this is Harbor config file agnostic (I've reproduced it with the example config with minimal changes (like cert path, etc.)

The OIDC callback response is:
`{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}`

The log message is:
`[WARNING] [/server/middleware/security/idtoken.go:45][requestID="************"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts`

I've been able to get my enterprise OIDC provider to temporarily allow RS256 tokens on their test endpoint, but will not be able to go to production with this.

This negotiation appears to be implemented by the coreos/go-oidc library. In https://github.com/coreos/go-oidc/issues/225, a user reported a similar issue; they fixed it in https://github.com/coreos/go-oidc/issues/227. Sure enough, in https://github.com/coreos/go-oidc/blob/78c840bd18d9ddb99ff8719bd5c1b1c141b664b2/oidc/oidc.go#L99, they add a supporting data structure for this negotiation.

However, the version of go-oidc bundled with Harbor - even in v2.2.1 - doesn't have the same structure here https://github.com/goharbor/harbor/blob/b0d6308293bf80e241c33920e262a8be1edfcd40/src/vendor/github.com/coreos/go-oidc/oidc.go#L84

Can the go-oidc library updated to enable support for other OIDC token signing algorithms?

**Comment by reasonerjt** [comment]
It's bumped up by https://github.com/goharbor/harbor/pull/14809

And will be fixed in v2.3.0
