### ISSUE TITLE
Harbor should allow to use the same tag for an image and a chart in the same repository

### ISSUE THREAD

**Issue by tompatib** [goharbor/harbor#14794]
**Expected behavior and actual behavior:**
Using the OCI functionality of harbor 2.2.1 I'm uploading docker images and helm charts into the same repo. Seems the tags needs to be unique in a repo, although I think the same tag could exists if those are different types (docker image, helm chart).

**Steps to reproduce the problem:**
I have uploaded a docker image with the same tag and uploading its helm chart which had the same tag so the docker image lost its tag.

In this case I tried with Kibana:

![kibana1](https://user-images.githubusercontent.com/16067575/116896759-d8c50700-ac34-11eb-8f05-905bf4fe65fb.png)

When I try to tag that manually, I get an error message:

![kibana2](https://user-images.githubusercontent.com/16067575/116896799-df537e80-ac34-11eb-9e41-24468a473926.png)

Also would be nice to mention the repository name instead of the Id ;). (Let me know if I should raise a Suggestion for that)

**Versions:**
- harbor version: 2.2.1
- docker engine version: 1.13.1
- docker-compose version: 1.25.0

**Comment by ywk253100** [comment]
That doesn't work for OCI registry. If there are two tags named `1.0` in the same repository, when the clients trying to pull the `1.0`, the registry cannot distinguish which one the clients are requesting

**Comment by tompatib** [comment]
Thanks @ywk253100, I see this is beyond Harbor. I close the issue.
