### ISSUE TITLE
How to helm repo add when pushing oci compliant charts

### ISSUE THREAD

**Issue by mjschmidt** [goharbor/harbor#14796]
Hi I was able to successfully push an oci compliant helm chart to my repo using `helm chart push`

How can I helm repo add this new storage location? Our end users need the ability to search though our repos to find the charts that work for them.

**Comment by ywk253100** [comment]
I don't think the helm client support `repo add` operation for OCI charts

The OCI charts uses different mechanism with regular charts. So if you need to `repo add` and `search`, use the regular chart instead
