### ISSUE TITLE
Add search capability to Project Quotas tab

### ISSUE THREAD

**Issue by sbajaj-vmw** [goharbor/harbor#14799]
As a Harbor administrator we often get requests to increase project quotas.  This can be done only in the Project Quotas menu.  However there is no search capability within Project Menus so I have to scroll page-by-page until I find the correct project.  Moreover, the projects seem to be listed in random order and cannot be sorted alphabetically or via storage usage or quota.  

Please add a search capability and the ability to order how the projects are displayed.

We are running version 2.1.3.

**Comment by AllForNothing** [comment]
Duplicated issue of #14194
