### ISSUE TITLE
Clair4x external scanner to Harbor 

### ISSUE THREAD

**Issue by ila-001** [goharbor/harbor#14804]
I have Clair 4x running on my cluster. On the Harbor side i need to attach the scanner. 
To give a try i did add sccaner, 
However i am getting "unreachable error".

![image](https://user-images.githubusercontent.com/57230278/117164518-99292700-adbc-11eb-89e8-06cb20b9716a.png)

sh-4.4$ curl http://registry-xxx.xxx.xxx.xx.corp
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
sh-4.4$

Could you please help me on this?

**Comment by heww** [comment]
For security reasons, we don't show more info that can't add the scanner to the harbor in the portal, please get more info from the log of the core component.

**Comment by ywk253100** [comment]
@ila-001 The clair 4.x may not work with Harbor at all
