### ISSUE TITLE
Delete specific immutable repository

### ISSUE THREAD

**Issue by stingshen** [goharbor/harbor#14806]
The following is my use case:

1. The repository is immutable if it starts with `readonly/`. So the master or admin sets an immutable rule for these repositories, the rule pattern is `readonly/**`. 
2. The master or admin has no way to delete a repo starting with `readonly/`，e.g. `readonly/a`.
  a. The immutable rule shouldn't be disabled or deleted because it may accidentally allow other users to mutate other repositories starting with `readonly/`.
  b. No way to create an exclusion immutable rule specifically for `readonly/a` because Immutability rules use `OR` logic.

Is there any proper usage to support the above use case?

**Comment by stingshen** [comment]
@wy65701436 Do you have any thoughts on this issue?

**Comment by wy65701436** [comment]
To make the scenario sample, we do not introduce exclusion rule for the immutable.

For your case, I think you can use a separate project to cover read-only repos. Or do not use ** to match all things, just use exactly match. 

Let's just keep this issue open, if we get more requirement about `exclusion`, will let PM to weigh and consider.

**Comment by wy65701436** [comment]
@stingshen please try the above suggestion. And so far, we do not have plan to introduce the exclusion rule for immutable. 
Please file an feature request if you would like to have it in Harbor.
