### ISSUE TITLE
Docker Hub pull-through proxy stopped working

### ISSUE THREAD

**Issue by gwkunze** [goharbor/harbor#14802]
**Expected behavior and actual behavior:**
Our docker pull-through proxy starting exhibiting more and more failures starting today. Now it only rarely succeeds in allowing a pull.

**Steps to reproduce the problem:**
```
$ docker pull my-harbor/dockerhub/library/alpine:3.2
Error response from daemon: unknown: artifact dockerhub/library/alpine:3.2 not found
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.3
- docker engine version: 18.09.1
- docker-compose version: N/A

**Additional context:**

[harbor.log](https://github.com/goharbor/harbor/files/6426736/harbor.log)

**Comment by gwkunze** [comment]
From the logs it looks like we're getting a 404 from Harbor trying to `docker login` to `hub.docker.com`, however according to https://stackoverflow.com/questions/59133704/docker-hub-login-failed-with-status-404-not-found `hub.docker.com` is deprecated and you should use `index.docker.io` but it is hardcoded in the pull-through configuration.
I tried setting it to `index.docker.io` in the database, that got rid of the 404 errors, but the registry remained "unstable".

**Comment by alexfrancavilla** [comment]
We are observing the same issue with the latest Harbor version (2.2.3) with the same error message as @gwkunze - doesn't matter if we leave `hub.docker.com` or patch the database to use `index.docker.io`.

**Comment by rjeka** [comment]
We have the same problem as @gwkunze. Harbor version 2.2.1. 
I tried to change the docker hub endpoint URL  in the database, but it did not help

**Comment by elnebuloso** [comment]
We have the same Problem with Habor Version v2.2.1-b0d63082, via Helm https://helm.goharbor.io, version 1.6.1

**Comment by mgomse-divante** [comment]
The same here - Harbor Version v2.2.1-b0d63082

**Comment by CptDaniel** [comment]
We're seeing this the last few hours as well (Version v2.2.1). In some cases, it works and in other cases, the login request just returns the default error page from docker hub. But I don't think it's related to the pull rate, since we're using a docker account with unlimited pulls.

**Comment by cbcos** [comment]
Same here with v2.2.1 and with docker account with unlimited pulls.
Problem started around 2021-05-04 16:00:00 UTC for us and is getting worse.. most pulls are failing, some are going through..

**Comment by alexdepalex** [comment]
Severely impacted by this as well. Is there a quick workaround for using index.docker.io?

**Comment by behrtam** [comment]
Why does a pull through cache fail anyway on images/tags that are present but when upstream is temporary down or not reachable.

**Comment by gwkunze** [comment]
@alexdepalex that was me just trying to resolve it by randomly whacking at harbor, but it didn't work. It is possible the issue is completely unrelated to this

**Comment by rudeblunt** [comment]
Also severely impacted by this, (v2.1.3) started around May  4th, 14:15 UTC

**Comment by cbcos** [comment]
Note: Docker at least confirms that they have a problem with logins: [Active Incident on Docker Status Page](https://status.docker.com/pages/533c6539221ae15e3f000031)

**Comment by cbcos** [comment]
Update: Docker engineers are working on a solution (see incident URL above):

> A highly probable root cause for the authentication and pull issues on the registry has been identified in part of the infrastructure involved in session creation. Engineers are working on a solution now.
> The incident may also affect Hub UI intermittently on authentication and logout.

**Comment by CptDaniel** [comment]
It seems like they fixed something. For us the pull-through-cache is working again.

**Comment by rudeblunt** [comment]
Yep, the cache started working again here too, last ""Failed to generate login session." error was recorded at 16:38 UTC

**Comment by gregdobedobedo** [comment]
Too bad that this issue has been closed because this comment from @behrtam is pertinent:

> Why does a pull through cache fail anyway on images/tags that are present but when upstream is temporary down or not reachable.

Shouldn't we improve the proxy cache feature in order to be fully functional even if upstream is failing ?

**Comment by cbcos** [comment]
Hey guys, we have opened a new issue so the team can mitigate this kind of problem in the future: #14822 
Feel free to upvote if you also think this should be fixed and our proposal looks good to you.
If not, please comment there to improve the issue

**Comment by gregopenit** [comment]
Thank you @cbcos ! This is perfect.
