### ISSUE TITLE
Repository deletion is not replicated

### ISSUE THREAD

**Issue by szimonek** [goharbor/harbor#14812]
**Expected behavior and actual behavior:**
I have two Harbor instances (namely Harbor01 nad Harbor02) which replicates to each other with push-based event replication rules. Repository deletion is not replicated with event-based replication rules, what leads to inconsistent copies of. Only artifacts deletion is replicated. 
I expect that all delete commands should be replicated.

**Steps to reproduce the problem:**
1. Harbor01 populated with image docker.io/nginx:1.19.10 which gets replicated to Harbor02
Harbor01:
![harbor03](https://user-images.githubusercontent.com/29062643/117267825-f7a2e380-ae56-11eb-86ec-585df7c7f0fc.JPG)
Harbor02:
![harbor04](https://user-images.githubusercontent.com/29062643/117267842-fb366a80-ae56-11eb-9adf-38bdea9dbfb6.JPG)

2. Deletion of artifact on Harbor01 is replicated to Harbor02
Harbor01:
![harbor05](https://user-images.githubusercontent.com/29062643/117268020-26b95500-ae57-11eb-80ee-6d715bed8b01.JPG)
Harbor02:
![harbor06](https://user-images.githubusercontent.com/29062643/117268058-2e78f980-ae57-11eb-8352-5a1bc7b797f0.JPG)

3. Deletion of repository is not replicated do Harbor02 (doesn't matter if I delete empty repository or that which contains artifacts):
Harbor01:
![harbor07](https://user-images.githubusercontent.com/29062643/117268316-713ad180-ae57-11eb-85f4-7287db0b6a46.JPG)
![harbor08](https://user-images.githubusercontent.com/29062643/117268333-7566ef00-ae57-11eb-933c-b0061e6f9bbd.JPG)
Harbor02:
![harbor09](https://user-images.githubusercontent.com/29062643/117268363-7e57c080-ae57-11eb-939f-20dd1a42fd29.JPG)

**Versions:**

- harbor version: [2.2.1]
- docker engine version: [20.10.5]
- docker-compose version: [1.29.1]

**Comment by ywk253100** [comment]
It's by design. Only artifacts are replicated between registries, other resources(e.g. repository, project, user, ...) are all not in the scope of replication
