### ISSUE TITLE
Make the P95 of list-audit-logs to be 20s in v2.3

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#14815]
In the small size of user data, the P95 of list-audit-logs API is about 32s in 300 concurrencies, we need to make it to be 20s.

| API               | Avg    | Min    | Med    | Max    | P(90)  | P(95)  | Success Rate | Iterations Rate |
| ----------------- | ------ | ------ | ------ | ------ | ------ | ------ | ------------ | ---------------- |
|list-audit-logs     |15.78s  |73.24ms |12.52s  |32.72s  |32.47s  |32.55s  |100%        |18.28/s        |

**Comment by codergs** [comment]
I was looking at the harbor code around audit logs list API, and puzzled why the code is trying to get count of all entries every time an audit logs API is called?
https://github.com/goharbor/harbor/blob/master/src/server/v2.0/handler/auditlog.go#L73
```
	total, err := a.auditMgr.Count(ctx, query)
	if err != nil {
		return a.SendError(ctx, err)
	}
	logs, err := a.auditMgr.List(ctx, query)
	if err != nil {
		return a.SendError(ctx, err)
	}
```
If q="resource=~project/repo:tag,operation=create,resource_type=artifact"&pageStart=1&pageSize=1, we are unnecessary calling `Count`. Should count be derived from the audit log entries matched by the query and received in the response from the DB? I think it will save unnecessary extra call to the DB thereby improving some performance.

**Comment by heww** [comment]
The total was used by the portal to render pagination in the audit log page.

We will improve the performance of this API in harbor v2.3.

**Comment by codergs** [comment]
@heww thanks for the update. I think it makes to sense call `qs.One` vs `qs.All` in cases where exact match is used. For `operation=create`, and a `exact match query` there can be only one value. I wish uploader information was actually on the artifact meta itself - https://github.com/goharbor/harbor/issues/14878 as it's been bit hard to use this API concurrently with the excessive PostgreSQL CPU load (currently present under v2.2.x). Looking forward to similar fix as https://github.com/goharbor/harbor/pull/14899 for audit-logs as well :) Thanks!

**Comment by heww** [comment]
Closed by https://github.com/goharbor/harbor/pull/14930
