### ISSUE TITLE
wehook and endpoint test problems

### ISSUE THREAD

**Issue by workman-Lu** [goharbor/harbor#14824]
**Expected behavior and actual behavior:**
Harbor webhook fails for some IPs and the endpoint test is abnormal
![image](https://user-images.githubusercontent.com/23043492/117524917-6799a100-aff2-11eb-9509-d1a0f5964e17.png)

**Steps to reproduce the problem:**

**Versions:**

- harbor version: [1.9.4]
- docker engine version: [19.03.5]
- docker-compose version: [1.25.0]

**Comment by YjLeo** [comment]
Its return 200 anyway，
![image](https://user-images.githubusercontent.com/23043492/117527571-9bc78e80-afff-11eb-9ae4-9770f3a4bef5.png)
this is another server，normal work
![image](https://user-images.githubusercontent.com/23043492/117527618-f82aae00-afff-11eb-84b6-e9d111d04580.png)

**Comment by ywk253100** [comment]
@YjLeo Could you try that on the latest version of Harbor? 1.9.x is already out of our support scope

**Comment by workman-Lu** [comment]
![image](https://user-images.githubusercontent.com/23043492/127867730-01b1df22-d1f6-41c0-bb76-ccba304bb815.png)
from v2.0.0 .

**Comment by workman-Lu** [comment]
The problem has been solved. 
A request is intercepted from my Global proxy(nginx) when i test the Endpoint
add  the URL to NO_PROXY in order to avoid being intercepted
