### ISSUE TITLE
Customize harbor password compliexity for organization

### ISSUE THREAD

**Issue by smallc2009** [goharbor/harbor#14821]
We have launched the Harbor in the office, which is quite good. but when changing the CLI password, it asked password with at least 1 capital character. we don't want this strict password policy.  all lowercase + number password is okay.  I didn't find any related settings to customize the password policy. any solution? thanks. 

**Expected behavior and actual behavior:**
I want to customize the password complexity policy

harbor version: [Version v2.2.1-b0d63082]

**Comment by ywk253100** [comment]
The customization isn't supported
