### ISSUE TITLE
Improve the performance of authModeCanBeModified method in config controller

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#14833]
There are two ways to improve this method.

1. Use the count method user manager to implement the authModeCanBeModified method.
2. Limit the query and only get one user from the user table.

https://github.com/goharbor/harbor/blob/3322716bc692e0a00a95864c940ae3a3a7906127/src/controller/config/controller.go#L182

I prefer to limit to query only one user from the table because count may be expensive.

**Comment by stonezdj** [comment]
Fixed it in pr #14777
