### ISSUE TITLE
Still get certificate error even though specifying the "http_get_ca=true" when running robot cases

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#14830]
The test cases `Helm CLI Push` and `Helm3 CLI Push`  failed with following errors:
```
11:18:27.456 | INFO | Running command 'helm repo add --ca-file /ca/ca.crt --username=user004 --password=Test1@34 myrepo https://harbor.chart.local/chartrepo/project051620530279 2>&1'. |  
11:18:27.506 | INFO | ${rc} = 1
11:18:27.506 | INFO | ${output} = Error: Could not construct protocol handler for: https error: can't create TLS config: can't read CA file: /ca/ca.crt
```

There are several different kinds of clients need to handle the certificate(docker/helm/cnab/oras/notary/...), is it possible to trust the harbor certificate in the OS level so that we don't need to care the certificate issue for different clients?

**Comment by danfengliu** [comment]
It's fixed in all 3 branches.
