### ISSUE TITLE
there is  no button to stopping scanning images in web page

### ISSUE THREAD

**Issue by svenlu** [goharbor/harbor#14831]
Hi everyone,
how to stop harbor  scanning images in  web page ? scanning images cause redis memory raise suddenly。
kind regardrs

**Comment by steven-zou** [comment]
@svenlu 

Please provide more background context such as how many repos are being scanned etc.?

**Comment by svenlu** [comment]
> @svenlu
> 
> Please provide more background context such as how many repos are being scanned etc.?

![bc4fbf80-fa9f-40b2-ab92-59e0e44406a0](https://user-images.githubusercontent.com/5123378/117603130-ecb4bf80-b184-11eb-8f52-3624b9b858d8.png)

![企业微信截图_1620469471628](https://user-images.githubusercontent.com/5123378/117603147-f8a08180-b184-11eb-92e2-2a27392f4634.png)

**Comment by steven-zou** [comment]
@heww 

Can we consider adding a stop function in the next release?
