### ISSUE TITLE
shared project/system robot crossing different harbor services

### ISSUE THREAD

**Issue by drehpehs** [goharbor/harbor#14845]
Hi Harbor team,

Currently we hosted multiple Harbor services, and we would like to have shared project/system robot for all harbor services?

We did some tests in the latest version (v2.2.1) of Harbor and found the project/system robot is authenticated by the `secret` and `salt` in **robot** table as new design. And we can manually sync up the value of them in the separated DBs of each harbor service. Then the robot with its original token can be used in other harbor services.

But we think it is not a good idea to update the the value of `secret` and `salt` in DB manually.
1. Do you have any suggestion or idea for this?
2. Is it possible or will you provide the feature or API to allow admin to update/customize the robot token (such as CLI secret for OIDC user) in the future?

Thank you in advance.

**Comment by stonezdj** [comment]
You could create the same robot account name and credential in different instances

**Comment by drehpehs** [comment]
Hi @stonezdj ,

Thanks for your reply. 
I think the same robot name is fine, but I wonder how can we have the same credential/token for it without updating the DB manually?

**Comment by AllForNothing** [comment]
@drehpehs You can update the credential/token on UI:
![image](https://user-images.githubusercontent.com/30999793/118914900-9f8fd500-b95e-11eb-881e-ced43298c9e1.png)

**Comment by drehpehs** [comment]
@AllForNothing 

Sorry, I didn't notice and check that.
Thanks for your sharing, it is really helpful.
