### ISSUE TITLE
Should return  401 status  instead of 200 status  when calling  permission API without  authorization

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#14862]
![image](https://user-images.githubusercontent.com/30999793/117950038-5aa7e500-b345-11eb-9276-7861478401f6.png)

**Comment by codergs90** [comment]
Same is the case with other APIs(eg: ListProjects, ListArtifacts, etc)

**Comment by reasonerjt** [comment]
@codergs90  
```
Same is the case with other APIs(eg: ListProjects, ListArtifacts, etc)
```
This is NOT same, it's the design that the artifacts under public project can be accessed without authentication.

**Comment by codergs** [comment]
> @codergs90
> 
> ```
> Same is the case with other APIs(eg: ListProjects, ListArtifacts, etc)
> ```
> 
> This is NOT same, it's the design that the artifacts under public project can be accessed without authentication.
I think then it is not that great as this means for private repos with no auth you are still getting 200! For a moment, I can agree with 200 on public repos, but if the API is same to access private repos, then harbor should have the added intelligence to toggle from 200 to 4XX if precondition is missing. At least it would make API usage consistent for a developer use case.

**Comment by reasonerjt** [comment]
```
I think then it is not that great as this means for private repos with no auth you are still getting 200! 
```
If it is the case, could you reproduce it, and open a new issue.  Let's try to make one issue focus on one problem.
