### ISSUE TITLE
Schedule scanner (Trivy  ) is  pending

### ISSUE THREAD

**Issue by carrieyang1212** [goharbor/harbor#14873]
Schedule scanner (Trivy  ) is  pending，and change configuration report error
![image](https://user-images.githubusercontent.com/57127288/118113468-ed658400-b418-11eb-9bec-e783ed4bc09b.png)

**Comment by heww** [comment]
Harbor version,  logs of the core component pls.

**Comment by carrieyang1212** [comment]
harbor2.0 
[core.log](https://github.com/goharbor/harbor/files/6498950/core.log)

**Comment by heww** [comment]
Hi, @carrieyang1212 could you delete the log above and only share the log around the request error of the schedule scanner? Thanks.

**Comment by carrieyang1212** [comment]
May 20 13:30:38 12.48.255.1 core[6582]: 2021-05-20T05:30:38Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"job not found"}]}
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/core/api/admin_job.go:71, github.com/goharbor/harbor/src/core/api.(*AJAPI).updateSchedule
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/core/api/scan_all.go:92, github.com/goharbor/harbor/src/core/api.(*ScanAllAPI).Put
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/reflect/value.go:460, reflect.Value.call
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/reflect/value.go:321, reflect.Value.Call
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/readonly/readonly.go:77, github.com/goharbor/harbor/src/server/middleware/readonly.MiddlewareWithConfig.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/security/security.go:63, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/artifactinfo/artifact_info.go:55, github.com/goharbor/harbor/src/server/middleware/artifactinfo.Middleware.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/lib/orm/orm.go:73, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/csrf/csrf.go:48, github.com/goharbor/harbor/src/server/middleware/csrf.attach.func1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/vendor/github.com/gorilla/csrf/csrf.go:297, github.com/gorilla/csrf.(*csrf).ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/csrf/csrf.go:68, github.com/goharbor/harbor/src/server/middleware/csrf.Middleware.func2
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
May 20 13:30:38 12.48.255.1 core[6582]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:2836, net/http.serverHandler.ServeHTTP
May 20 13:30:38 12.48.255.1 core[6582]: /usr/local/go/src/net/http/server.go:1924, net/http.(*conn).serve
