### ISSUE TITLE
Need docker label display on interface && api

### ISSUE THREAD

**Issue by urpyLLIKa** [goharbor/harbor#14876]
I really miss my own docker labels or annotation in the interface and api, as well as search by labels of docker containers 

For example label
OsType = Linux
OsName = Debian
OsVerson = 10.7
Type = builder
TypeBuilder = Go
TypeBuilderVerision = 12

**Comment by stonezdj** [comment]
You could get in the build history of the image

**Comment by deuch** [comment]
Need this too to retrieve the labels put during build of image. And with the harbor API, not the UI (for automation)

**Comment by urpyLLIKa** [comment]
fixed  in version 2.3.0-047b122c in method /projects/{project_name}/repositories/{repository_name}/artifacts/{reference} return JSON with extra_attrs.config.Labels
