### ISSUE TITLE
Handle image deletion when Harbor is installed with notary.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#1487]
Should try to delete the signature before removing the image

**Comment by reasonerjt** [comment]
It's probably not possible to make update to notary's data from Harbor instance.

**Comment by smekkley** [comment]
This will be indirectly fixed if #/7424 is implemented.

**Comment by DerrickMartinez** [comment]
Any chances this might get worked on? We'd like to move to Harbor but not being able to manage auto deletion of signed tags is a bummer.

**Comment by youvegotmoxie** [comment]
Is there any update on this?
