### ISSUE TITLE
The switch of Allow garbage collection on untagged artifacts is invalid

### ISSUE THREAD

**Issue by charnet1019** [goharbor/harbor#14891]
![image](https://user-images.githubusercontent.com/18616254/118351102-7d780a80-b58c-11eb-8c7c-51e918219e50.png)

**Comment by wy65701436** [comment]
hi please give more info, harbor version?log?Reproduce step? Otherwise, we cannot provide help.

**Comment by parsifallo** [comment]
Same here. Fresh installation via harbor-online-installer-v2.3.4.tgz
If I turn the switch it on and leave the site and go back, switch is turned off again. It seams that this switch has no function.
Container harbor-log doesn't have any entries, but I do have a lot of these in harbor-core:
`2021-11-22T04:00:18Z [ERROR] [/pkg/token/token.go:66]: parse token error, token contains an invalid number of segments`
br,parsi
