### ISSUE TITLE
Should improve style for the UI

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#14897]
too much space above title
no units on storage
need more space between event log button and content area
color of breadcrumb is too dark and should be the color of the line of the selected tab 
size of 2 actions is different (Registry certificate and push command)
color of tag is too dark like the breadcrumb
color of unselected tab bar is colored (looks purple)

**Comment by lweitzman** [comment]
i think we may consider dropping the breadcrumb altogether.
