### ISSUE TITLE
Snyk Container Scanner Support

### ISSUE THREAD

**Issue by josephlim75** [goharbor/harbor#14892]
**Is your feature request related to a problem? Please describe.**
Nope is not a problem, just wanted to know if goHarbor has any plan to support Snyk as part of the container scanner.  Currently Anchore, Clair, and Trivy is supported.  Just wondering if Snyk will be supported in the future.  

Thanks

**Comment by steven-zou** [comment]
@josephlim75 

There is a [scanner spec](https://github.com/goharbor/pluggable-scanner-spec). For a new scanner, you can directly follow this guide to implement one. The scanner adapter is always supported by its vendor, not by Harbor.

**Comment by lindhe** [comment]
Looks to me like they have support for it, at least with Enerprise plan: <https://support.snyk.io/hc/en-us/articles/360018401678-Container-security-with-Harbor-integration>

**Comment by steven-zou** [comment]
> Looks to me like they have support for it, at least with Enterprise plan: https://support.snyk.io/hc/en-us/articles/360018401678-Container-security-with-Harbor-integration

They did not reach the Harbor team. And then we can not say Harbor support it because there is no maintenance guarantee from Snyk vendor.

Close this issue now and reopen when necessary.
