### ISSUE TITLE
Roadmap out of date

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#14890]
It looks like the current Harbor roadmap is out of date and needs to be updated.

https://github.com/goharbor/harbor/blob/master/ROADMAP.md

**Comment by a-mccarthy** [comment]
@xaleeks do you have an ETA on when you will be able to update this?

cc: @jonasrosland @Orlix

**Comment by jonasrosland** [comment]
We need to update the roadmap here, it is very out of date.

**Comment by qnetter** [comment]
Should be updated within two weeks.

**Comment by a-mccarthy** [comment]
@qnetter can you provide another update on the status of the roadmap, thanks!!

**Comment by qnetter** [comment]
We have the 2.6 items targeted. We need one more pass to roughly timeline the remaining items, which are already prioritized. I estimate one more week. I can post what we have now - as 2H2022 and "future" - this week, then revise.

**Comment by a-mccarthy** [comment]
@qnetter can you provide and update here? thanks
