### ISSUE TITLE
Project repositories are paginated, then sorted instead of sorted, then paginated

### ISSUE THREAD

**Issue by pmorch** [goharbor/harbor#14903]
**Expected behavior and actual behavior:**

When listing more than 15 repositories in a project, they get paginated. One can sort the repositories.

I then expect that page 1 will contain all the images starting with A..... B.... etc. and the last page contains all those images with Z....

Instead, the actual behavior is that sorting will take the random images that happen to be on page 1 and sort *them*. So there it is possible to have A.... and Z... images on both the first and last page.

To simplify assume that there were 2 repositories instead of 15 per page.

Then if it looks like this before sorting:

* page1
    * foo
    * bar
* page2
    * foz
    * baz

Then after sorting I expect:

* page1
    * bar
    * baz
* page2
    * foo
    * foz

But instead I actually see:

* page1
    * bar
    * foo
* page2
    * baz
    * foz

This basically makes sorting nearly useless.

**Steps to reproduce the problem:**

Create e.g. 60 repositories in a project with varying names.

See that sorting and pagination don't do "the right thing".

**Versions:**
Please specify the versions of following systems.

- harbor version: Version v2.1.3-b6de84c5
- docker engine version: I don't have access to this information (our operations team have set it up)
- docker-compose version: I don't have access to this information (our operations team have set it up)

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

I don't have access to this information (our operations team have set it up)

**Comment by AllForNothing** [comment]
@pmorch Thanks for the info.
It is a similar issue to  #13578
