### ISSUE TITLE
MySQL service not started

### ISSUE THREAD

**Issue by lailailee** [goharbor/harbor#14908]
When first installed, the database port was 3306 and Harbor was running fine.

A month later, my colleague restarted the server and started another database service using 3306. Because the user name and password were not correct, I couldn't connect to the database.

Instead, I changed the configuration from 3306 to 3309, reinstalled Harbor, and when I started the container, I still couldn't connect to the database in 3309.

Lsof then looked at the port of 3309 and found no database server, so would the harbor-online-installer-v1.5.0. TGZ install package not start MySQL?

![image](https://user-images.githubusercontent.com/28286591/118586066-ab4b9200-b7cc-11eb-9460-f51832a1ed3a.png)
[docker-compose-log.txt](https://github.com/goharbor/harbor/files/6498187/docker-compose-log.txt)

**Comment by stonezdj** [comment]
Harbor 1.5.0 is a too old version, the current version is 2.2.0

**Comment by lailailee** [comment]
> Harbor 1.5.0 is a too old version, the current version is 2.2.0

ok,thank you
