### ISSUE TITLE
system/gc/schedule API inconsistency

### ISSUE THREAD

**Issue by elenz97** [goharbor/harbor#14917]
**Expected behavior and actual behavior:**
Garbage collection configuration via API should behave the same as through GUI.

When `curl`'ing the Harbor API, the behavior is not the same as when interacting with it through the GUI.

Since Harbor `v2.2.0`, the `parameters` key has been added to the `Schedule` object that is required when `POST`'ing / `PUT`'ing.
As it seems to be mandatory - not providing it resulting in a crash of the GC handler, that means - it should be marked as required in the API specification, too. I've provided a potential fix for the handler crashing in https://github.com/goharbor/harbor/pull/14918.

You can try provoking this error yourself at `demo.goharbor.io` (just for convenience), or else refer to my environment below.

```shell-session
$ curl  --user "<redacted>" -X POST "https://demo.goharbor.io/api/v2.0/system/gc/schedule" \
  -H "accept: application/json" -H "Content-Type: application/json" \
  -d '{  "schedule": { "cron": "0 * * * * *", "type": "Hourly" } }' -v
```

When setting a GC schedule via GUI, the json object will look like below, _always_ containing the `"parameters"` section while it is not specified by the user:
```
{
  "schedule": {
    "type": "Daily",
    "cron": "0 0 0 * * *"
  },
  "parameters": {
    "delete_untagged": false
  }
}
```

As of now, only the `schedule` parameter is marked as required on [POST](https://github.com/goharbor/harbor/blob/b0d6308293bf80e241c33920e262a8be1edfcd40/api/v2.0/swagger.yaml#L2212-2218) / [PUT](https://github.com/goharbor/harbor/blob/b0d6308293bf80e241c33920e262a8be1edfcd40/api/v2.0/swagger.yaml#L2239-2245) `system/gc/schedule`. Users should be informed about the `parameters` being required, and what value it takes when it is defaulted.

**Versions:**

- harbor version: v2.2.1-b0d63082 (deployed via the latest `harbor-helm` chart [`v1.6.1`](https://github.com/goharbor/harbor-helm/releases/tag/v1.6.1)).
- docker engine version: 19.03.13
- docker-compose version: -

**Comment by wy65701436** [comment]
close as https://github.com/goharbor/harbor/pull/14918 merged.
