### ISSUE TITLE
unable to migrate to new harbor registry with old harbor url

### ISSUE THREAD

**Issue by hisrarul** [goharbor/harbor#14947]
What can we help you?
I have deployed two harbor registries.  One is working as primary and another is working as secondary.
To sync the images and project, I have enabled replication between them. Each has a endpoints e.g.` primary.harbor.test.org` and `secondary.harbor.test.org`
When I want to pull the images from primary harbor I ran docker pull `primary.harbor.test.org/<project_name>/<image_name>:<tag>` and to pull from secondary docker pull secondary.harbor.test.org/<project_name>/<image_name>:<tag>
Now, my primary harbor got some issues, it's unable to show new project so decides to do failover meaning point primary url to secondary harbor and vice versa. Here, is the problem, when I try to pull using `docker pull primary.harbor.test.org/<project_name>/<image_name>:<tag>` which is pointing to secondary harbor currently. It is still showing the old tags on each project meaning `secondary.harbor.test.org/<project_name>/<image_name>:<tag>` . Hence, I am unable to download images from new primary endpoint url.

**Comment by stonezdj** [comment]
Just change the hostname is not enough, you might need to run ./prepare after you change the Harbor server name in the harbor.yml
