### ISSUE TITLE
unauthorized: unauthorized to access repository

### ISSUE THREAD

**Issue by ccc469** [goharbor/harbor#14952]
Docker login successful, but push error, even the admin account，Even configuration "insecure-registries" are also invalid， someone has a solution, please help me 。。。。

Docker push error: 

The push refers to repository [xxxxxxxx/common/hello-world]
510e49905755: Pushing [==================================================>]  27.41MB
0eba77cb641f: Pushing [==================================================>]  3.072kB
cf6c4aad3fcc: Pushing [==============>                                    ]  32.64MB/109MB
883b3861724b: Pushing [==================================================>]  3.584kB
b865cfc9b0c3: Pushing [==================================================>]  9.141MB
02c055ef67f5: Pushing [=======================>                           ]  32.55MB/69.26MB
unauthorized: unauthorized to access repository: common/hello-world, action: push: unauthorized to access repository: common/hello-world, action: push

**Comment by 2013kaa** [comment]
Did you manage to solve this problem?
