### ISSUE TITLE
push apsopen/h5-nginx:xxxx received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by hbzhu** [goharbor/harbor#14950]
- harbor version: v2.1.5
- docker engine version: 19.03.12
- docker-compose version: 1.26.0

使用2.1.5版本推送镜像，某些项目的名字推送会出现500错误，比如

_docker push registry.xxx.cn/apsopen/h5-nginx:dev-0858945_

The push refers to repository [registry.xxx.cn/apsopen/h5-nginx]
e99f06cd9b42: Retrying in 1 second 
0c05fc7793f0: Retrying in 1 second 
c54f86c2d835: Retrying in 1 second 
29a0c09583c9: Retrying in 1 second 
2a5702ba664f: Layer already exists 
3fc64803ca2d: Layer already exists 
received unexpected HTTP status: 500 Internal Server Error

同样的镜像修改下项目名，比如h5修改为hh5，就可以了

_**docker tag registry.xxx.cn/apsopen/h5-nginx:dev-0858945 registry.xxx.cn/apsopen/hh5-nginx:dev-0858945**
_docker push registry.xxx.cn/apsopen/hh5-nginx:dev-0858945__

The push refers to repository [registry.xxx.cn/apsopen/hh5-nginx]
[registry.log](https://github.com/goharbor/harbor/files/6527480/registry.log)

e99f06cd9b42: Pushed 
0c05fc7793f0: Pushed 
c54f86c2d835: Pushed 
29a0c09583c9: Pushed 
2a5702ba664f: Mounted from apsopen/h5-nginx 
3fc64803ca2d: Mounted from apsopen/h5-nginx 
dev-0858945: digest: sha256:fbec21c2d607458a4f317f4845f9918ae02189ecc45ad650ace9ff4c0de5a244 size: 1576

测试就apsopen/h5-nginx:xxxx不可以,其他apsopn/h5-nginx:xxxx或者sre/h5-nginx:xxxx都可以

**Comment by stonezdj** [comment]
auth.user.name="harbor_registry_user" err.code=unknown err.detail="filesystem: open /storage/docker/registry/v2/repositories/apsopen/h5-nginx/_manifests/revisions/sha256/fb0caedb4edc59978b876e5d184b05a85aadf49779d4d60f563afc78fbc40846/link: permission denied"

It file permission denied.

**Comment by hbzhu** [comment]
使用的是admin用户，应该不是权限的问题

**Comment by hbzhu** [comment]
之前的版本2.1.3是可以的，升级到2.1.5就不可以了

**Comment by hbzhu** [comment]
查看了registry容器，的确有部分的数据变成了50000的用户所主，估计升级期间异常导致的
