### ISSUE TITLE
Help wanted: 2.2 retag via api

### ISSUE THREAD

**Issue by zigmund** [goharbor/harbor#14954]
/help wanted

Need to retag image with overwrite - `latest`, for example.

Of course I can do `docker pull registry/proj/repo:source && docker tag registry/proj/repo:source registry/proj/repo:latest && docker push registry/proj/repo:latest`, but want to avoid needless traffic.

According to docs (https://goharbor.io/docs/2.2.0/working-with-projects/working-with-images/retagging-images/), I should use _copy_. Docs says: _In the Retag window, enter the project name, repository name, the **new tag name**, and click Confirm._ But web ui forbids to set `:tag` to destination repo field. Also, according to api swagger, seems it's not possible.

I tried to use _create tag_ api call, but got `CONFLICT` and cannot see in swagger any param to overwrite tag.
Also tried to delete destination tag at first and then create tag with api. It works, but since we have event-based replication, there is race condition sometimes (create replicated first and delete goes after) and we have inconsistent remote registry.

So what is best atomic way to retag image with overwrite without pull / tag / push?

**Comment by zigmund** [comment]
Same issue was resolved two years ago in v1 api but it is unavailable in Harbor v2.
https://github.com/goharbor/harbor/issues/5778

**Comment by stonezdj** [comment]
You should make sure you have permission to the target project.

**Comment by zigmund** [comment]
@stonezdj I have permissions, doing it under admin account.
Problem in v2 api. There are two routes in api for such operations:
1. `artifact/CopyArtifact` - doesn't allow to specify destinations tag.
2. `artifact/createTag` - doesn't allow to overwrite existing tag.

**Comment by Yingrjimsch** [comment]
Hi is there progress or is it possible to implement this feature?
My workaround for now is deleting the tag via API and then resetting it on another digest.
Would be great if that could be done in one step 😄
