### ISSUE TITLE
[portal] enhance harbor login form when OIDC auth is configured

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#14968]
**Is your feature request related to a problem? Please describe.**
This feature request tries to solve the Harbor landing page when the user is not authenticated when Harbor is configured to use other Auth Services (in our case OIDC) 

**Describe the solution you'd like**
As discussed with @reasonerjt he proposed to add:
![image](https://user-images.githubusercontent.com/5084445/119535022-dd8a6000-bd87-11eb-96d9-4a5d7cc09cf8.png)
Which i also agree, at least makes the user think. This is important as so the user does not expose user:passwd from the organization into the Harbor service.

We where also thinking on adding configurable Text button for the OIDC as some users are not technical. So, having something like "CompanyX SSO". This goes against @reasonerjt wishes of not introducing configuration complexity but i also would like you to consider it :) 

**Describe the main design/architecture of your solution**
I have no opinion on this

**Describe the development plan you've considered**
The solution proposed by Daniel its mainly front-end form editing. For the rest is more complex and if accepted we can split into another ticket

**Additional context**
![Harbor Login](https://user-images.githubusercontent.com/5084445/119537150-0ca1d100-bd8a-11eb-942a-a7fc4da018b2.png)

**Comment by Vad1mo** [comment]
Another option would be to redirect the user directly to the OIDC provider, skipping the login screen entirely.  

If the admin enters the exact url `../harbor/sign-in` the user can login with username/password

You can take a look at our public container registry [c8n.io](https://c8n.io) to see it in action. We could create a PR to enable this.

**Comment by Vad1mo** [comment]
It's done on the frontend (Harbor Portal) it checks on `c8n.io/` (root) if OIDC is enabled in `/systeminfo` and if so it redirects the user to the login page `c/login/`.  If you go straight to `/harbor/sign-in` nothing will happen. 

I need to polish this a bit but generally we can open up a merge request.

**Comment by reasonerjt** [comment]
Edited the title for clarification @dioguerra

**Comment by dioguerra** [comment]
I also though about it, but i don't know how will this work with cli docker login as it uses the user token.
I guess this is ok as it uses the /auth path. https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/vendor/github.com/docker/docker/client/login.go#L15

Never the less, then i need to change the reverse proxy ingress configs. Currently i use the helm chart to set up my client. So i would need to change the chart to achieve your suggested workaround.
` 
 spec:
    rules:
    - host: registry-staging.foo.bar
      http:
        paths:
        - backend:
            serviceName: harbor-staging-harbor-portal
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
        - backend:
            serviceName: harbor-staging-harbor-core
            servicePort: 80
          path: /api
          pathType: ImplementationSpecific
        - backend:
            serviceName: harbor-staging-harbor-core
            servicePort: 80
          path: /service
          pathType: ImplementationSpecific
        - backend:
            serviceName: harbor-staging-harbor-core
            servicePort: 80
          path: /v2
          pathType: ImplementationSpecific
        - backend:
            serviceName: harbor-staging-harbor-core
            servicePort: 80
          path: /chartrepo
          pathType: ImplementationSpecific
        - backend:
            serviceName: harbor-staging-harbor-core
            servicePort: 80
          path: /c
          pathType: ImplementationSpecific
`

This is not good for maintenance, and if you consider other users that require the same is adding extra work to everyone. Am i missing something?

**Comment by Vad1mo** [comment]
>I also though about it, but i don't know how will this work with cli docker login as it uses the user token.
I guess this is ok as it uses the /auth path. https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/vendor/github.com/docker/docker/client/login.go#L15

the current solution is working fine with the CLI as the the CLI is not going to `/` (root) but `/api/` (something like that)

>Never the less, then i need to change the reverse proxy ingress configs. Currently i use the helm chart to set up my client. So i would need to change the chart to achieve your suggested workaround.

no changes to reverse proxy are needed as the logic happens on the portal side. On top as an Harbor admin you can enable or disable the feature as needed.

**Comment by AllForNothing** [comment]
What about just changing the "LOG IN" button to "LOG IN WITH LOCAL DB"?
This is enough to distinguish between  "log in with OIDC provider" and "log in with local database"
![image](https://user-images.githubusercontent.com/30999793/123360982-d0d47400-d5a0-11eb-9e18-656ec3e4507d.png)
