### ISSUE TITLE
GC: Error status and object is not found but job is running ?

### ISSUE THREAD

**Issue by guyguy333** [goharbor/harbor#14966]
**Expected behavior and actual behavior:**

As long as GC job is running, I shouldn't have error status. However, I'm pretty sure GC job is running as registry is spammed with DELETE. Moreover, I'm unable to fetch the job log so I believe job is not done.

![Screenshot 2021-05-25 at 11 31 52](https://user-images.githubusercontent.com/4040959/119474762-cf6b1e00-bd4c-11eb-9047-e207fc19caac.png)

Here is the output clicking on Log:

```json
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"log entity: 3ae399a817334a6a372bccd0\"}"}]}
```

**Steps to reproduce the problem:**

Run a long GC job (We've 1.5Tb and ~175k objects on S3)

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.22
- docker engine version: Using containerd
- docker-compose version: Using K8S

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
can you share the job service log as well? It's helpful for narrow down the problem. 

And, can you confirm whether the other jobs(Replication/Scan or Retention) are running at the time of GC execution? We found that the job log may fail to create at the some particular job high load scenario.

**Comment by guyguy333** [comment]
Sure. However, after a fail, if I don't restart Harbor (job service pod), I'm having this response requesting a log of any garbage collection (even on which failed multiple days ago and a restart already happened):

```
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```

Storage is on S3. I have many job service logs with `context deadline exceeded` I can share if you want.

Here is an example of a job service. 

[jobserver.log](https://github.com/goharbor/harbor/files/6576567/jobserver.log)

**Comment by guyguy333** [comment]
I got an other error retrieving log after job failed: `{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"log entity: 2c456ecc4b695fa3505e6fd0\"}"}]}`

Maybe finally related to #12948 ?

**Comment by steven-zou** [comment]
```
2021-05-31T07:25:18Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:262]: failed to delete manifest with v2 API, xxxxx/xxxxx/xxxxx, sha256:1a793c56994d3fd017dbf95ec73f8c3615477da8e3d44dc8c0957580eb6e3e05, Delete "http://harbor-harbor-registry:5000/v2/xxxxx/xxxxx/xxxxx/manifests/sha256:1a793c56994d3fd017dbf95ec73f8c3615477da8e3d44dc8c0957580eb6e3e05": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021-05-31T07:25:18Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:165]: failed to execute GC job at sweep phase, error: failed to delete manifest with v2 API: xxxxx/xxxxx/xxxxx, sha256:1a793c56994d3fd017dbf95ec73f8c3615477da8e3d44dc8c0957580eb6e3e05: Delete "http://harbor-harbor-registry:5000/v2/xxxxx/xxxxx/xxxxx/manifests/sha256:1a793c56994d3fd017dbf95ec73f8c3615477da8e3d44dc8c0957580eb6e3e05": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by wy65701436** [comment]
You can upgrade to latest Harbor, it introduces retry on GC failure within one minute.

**Comment by guyguy333** [comment]
Thanks @wy65701436 I will try that :)

**Comment by wy65701436** [comment]
@guyguy333 please reopen it if you still encounter the problem.

**Comment by miminar** [comment]
We are having the same issue in 2.6.2.
Using S3 storage, we are also hitting #12948. The jobs keeps running for a very long time, it is reported as Running, but opening the Log results in:

```
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"228f7a1eb1175ebabcaafd76\"}"}]}
```

![image](https://user-images.githubusercontent.com/1478803/210553447-9bc2826a-cb46-4747-9db6-df927b2254ae.png)

@wy65701436 or @steven-zou, can you please re-open? Or shall I open a new one? What other information do you want me to provide?

**Comment by Antiarchitect** [comment]
Same symptoms. I use Ceph Radosgw as an S3-like storage. I have 2.66 TB overall registry space used (and growing). No one job (weekly because of https://github.com/goharbor/harbor/issues/14774) didn't succeeded since September 2022.

P.S. jobservice pod CPU consumption is close to zero and pod stdout does not contain anything worthy of mentioning. Could it be it's doing nothing?

**Comment by Antiarchitect** [comment]
Removing all Redis instances (KeyDB in my case) with all the PVCs seems did the trick and now one worker is doing GC after a manual restart.

**Comment by salmon5** [comment]
My harbor version is 2.2.0,have same issue.
I update harbor to 2.4.0,the issue is fixed.
https://goharbor.io/docs/2.4.0/administration/upgrade/

**Comment by mdavid01** [comment]
Hi Team - What is the log entity?  How can it help me locate the root cause?

**Comment by kdambekalns** [comment]
Seeing this with v2.11.0 – should this be reopened or shall I create a new issue?

**Comment by mdavid01** [comment]
Thx for following up.  We are just now installing 2.11.  I would say leave closed and we'll open new issues as we encounter them with 2.11.

**Comment by imcom** [comment]
I am running with the version `Version v2.11.1-6b7ecba1` and currently encountered a failed GC. Then I run a new GC again then immediate the log gives me this
```
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"fa1fa3b7095092f69a588140\"}"}]}
```

Job status is Running and from logs of `harbor-jobservice` I could see that the job is indeed running and deleting things

```
2024-11-10T02:51:36Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:424]: [2837ff8f-735c-4beb-8bb1-b148b7445a75][89868/779771] delete blob from storage: sha256:8fa693c326245c4397a5e8409ea08f354c0c2177d29d6970278675200f02455a
2024-11-10T02:51:36Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:453]: [2837ff8f-735c-4beb-8bb1-b148b7445a75][89868/779771] delete blob record from database: 335257, sha256:8fa693c326245c4397a5e8409ea08f354c0c2177d29d6970278675200f02455a
```
