### ISSUE TITLE
How to replicate NEXUS repository images in HARBOR repository?

### ISSUE THREAD

**Issue by vinusorout** [goharbor/harbor#14967]
As per the documentation(https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-endpoints/), we can replicate the images from a non Harbor repository.

Currently there are following options for provider:
 - Alibaba ACR
 - Artifact Hub
 - Aws ECR
 - Azure ACR
 - Docker Hub
 - Docker Registry
 - DTR
 - Github GHCR
 - Gitlab
 - Google GCR
 - Harbor
 - Helm Hub
 - Huawei SWR
 - JFrog Artifactory
 - Quay
 - Tencent TCR
 
But I cant find NEXUS in the drop down. Is there any way to replicate NEXUS repository images in HARBOR repository?

**Comment by phin1x** [comment]
You can try to add your nexus with the "docker registry" provider.

**Comment by steven-zou** [comment]
@phin1x 

are you willing to do more contributions to Harbor community?

**Comment by vinusorout** [comment]
Yes the "docker registry" provider works with NEXUS

**Comment by abdennour** [comment]
Ah! that's coool! 
تسلم الأيادي

**Comment by torsten-online** [comment]
Hi, I'am getting the following error with replication from nexus over Docker Registry to harbor Version v2.7.1-6015b3ef - deployed over Harbor Helm v1.11.1: 

`````
failed to fetch artifacts: http status code: 404, body: {"errors":[{"code":"UNKNOWN","message":"Unauthorized","detail":null}]}
`````

The auth credentials for nexus are working fine.

IT seems to be that the catalog can not be retrieved.

Nexus Log:
````
org.sonatype.nexus.repository.docker.internal.orient.DockerProxyFacetImpl - Exception org.sonatype.nexus.repository.proxy.BypassHttpErrorException checking remote for update, proxy repo docker-hub failed to fetch v2/_catalog, content not in cache.
````

Any idea how to fix this?

**Comment by sichiba** [comment]
Hello Guys, any ideas on how to acheive replication between an Onprem Quai registry and Hrabor?
