### ISSUE TITLE
harbor 1.10基于push的方法往2.2进行复制，项目下面是有镜像的。复制结果的状态为succeed的，但成功百分比为0，总数也为0

### ISSUE THREAD

**Issue by kevin-hao** [goharbor/harbor#14964]
What can we help you?
![图片](https://user-images.githubusercontent.com/14213577/119466286-0ce4a100-bd77-11eb-8a96-6ce6929768ec.png)

**Comment by steven-zou** [comment]
@kevin-hao 

Harbor does not support replication between different harbor versions.

**Comment by steven-zou** [comment]
you can try to pull images from 1.10 to 2.2.
