### ISSUE TITLE
Replication tips formatting isn't as good

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#14978]
Please gives more details about all of options, and in good format.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/2841473/119599679-0fe39e00-be18-11eb-9130-805e405dfce0.png">

**Comment by danfengliu** [comment]
There is no tip info for condition that destination namespace is empty, in this situation, flattening is meaningless. User can't get it with current web UI design, so web UI should restrict flattening selection when destination namespace is empty, and add more tip info.
