### ISSUE TITLE
Vulnerabilities Export Feature 

### ISSUE THREAD

**Issue by fshadid96** [goharbor/harbor#14987]
**Is your feature request related to a problem? Please describe.**
It would be ideal to export a report to see the list of vulnerabilities for clients reports and such 

**Describe the solution you'd like**
It would be a good idea to add an export button for vulnerabilities on a repository/tag level

**Describe the main design/architecture of your solution**
![image](https://user-images.githubusercontent.com/20993211/119693802-a022e280-be1a-11eb-8cd6-658680853546.png)
add a button next to the scan button to export the list of vulnerabilities for that image 

**Describe the development plan you've considered**
No plan yet but if someone can help then I can work on it 

**Additional context**
N/A

**Comment by a-mccarthy** [comment]
@AllForNothing can you provide an update on this? will this issue need docs for 2.6? thanks!

**Comment by AllForNothing** [comment]
@a-mccarthy Sure, it needs docs.  And you can move to #17081 for more detail
