### ISSUE TITLE
the latest update time on UI is not correct

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14989]
build: v2.3.0-build.653
the latest update time of repo is not correct, not sync with the artifact update time
![image](https://user-images.githubusercontent.com/188115/119758776-ab891300-bed9-11eb-8577-470c93aff5ec.png)
![image](https://user-images.githubusercontent.com/188115/119758793-b348b780-bed9-11eb-8d0b-3cf966d5409a.png)

**Comment by wy65701436** [comment]
discussed with @ywk253100 , will do nothing on 2.3. And for the update time, we do not have a clearly scope for repository and project, which action should impact the update time.
