### ISSUE TITLE
Harbor-database pod crashloopbackoff

### ISSUE THREAD

**Issue by gppillai12** [goharbor/harbor#14993]
What can we help you?
We have observed harbor-database pod crashloopbackoff as **kubelet Back-off restarting failed container** but it's not showing any logs when we ran kubectl logs for database pod it's empty no logs.

How can we resolve this issue? can you please help with this...

**Comment by steven-zou** [comment]
Any events/status.conditions from kubectl describe?

**Comment by gppillai12** [comment]
I got this from the kubectl describe
Warning BackOff 21s (x50 over 10m) kubelet, 10.x.x.x Back-off restarting failed container
