### ISSUE TITLE
Cleanup unneeded AD/LDAP Users 

### ISSUE THREAD

**Issue by vidhyasagar7** [goharbor/harbor#15002]
**Is your feature request related to a problem? Please describe.**
Currently to cleanup a LDAP/AD User we would have to delete them from the Harbor DB using the steps mentioned here

https://github.com/goharbor/harbor/wiki/Harbor-FAQs#ldap

**Describe the solution you'd like**
It would be better to have an option in the Harbor UI under Users section that would allow us to delete the AD/LDAP User  rather than having to delete them from "harbor_user" table from the DB  

**Describe the main design/architecture of your solution**
Attaching a snippet from Users section in Harbor UI where the user I have selected is from AD and the Delete option is disabled for these users, if the user leaves the org or for any reason if I have to remove that user I had to delete by docker exec in to Harbor DB container and remove them which is tedious and also can be risky.

![image](https://user-images.githubusercontent.com/34569412/119873338-12daad80-bf42-11eb-96c6-a468b620449e.png)

**Describe the development plan you've considered**
We can implement a solution just like how we have the option to remove the Members from Project in UI

**Additional context**

**Comment by stonezdj** [comment]
Fix it in pr: #15247
