### ISSUE TITLE
found project with same name in table repository

### ISSUE THREAD

**Issue by walleliu1016** [goharbor/harbor#15004]
There are multiple projects with the same name in the project table. 
As shown in the figure below, an error will be reported when you use “docker pull tag” to pull the image, but the method of "docker pull digest" is no problem.
![image](https://user-images.githubusercontent.com/8541378/119918527-3847d580-bf9b-11eb-9967-2029514404d8.png)

The name clomun is the unique primary key in the repository table, why there are multiple records with the same name?

**Comment by steven-zou** [comment]
@walleliu1016 

How can we reproduce this case？

**Comment by walleliu1016** [comment]
it looks like the combine index problem
when i pull a image by tag, you will got the error about no artifact found for xxxx,
but you can find the record in the tag table by name or artifact_id, 
after read the source about harbor api, the combine index will used in find the tag select sql, 
you can refers the details as the image below.
![image](https://user-images.githubusercontent.com/8541378/123358436-13488180-d59e-11eb-895f-d09a853d6f96.png)

i got the same err in tag table last day, we want to migrate the postgresql to anthor machine, the step is as follews:
1. stop the harbor
2. copy the postgresql to anther machine
3. start the harbor with the database configuration to the new machine

you will find the err about some records in the tag table

i fix the problem by reconstruct the index.

i think the other table may contains the same problem.

@steven-zou 
@ywk253100

**Comment by walleliu1016** [comment]
the combile index about tag:
`registry=# select * from pg_indexes where tablename='tag';
 schemaname | tablename | indexname  | tablespace |                                    indexdef                                    
------------+-----------+------------+------------+--------------------------------------------------------------------------------
 public     | tag       | tag_pkey   |            | CREATE UNIQUE INDEX tag_pkey ON public.tag USING btree (id)
 public     | tag       | unique_tag |            | CREATE UNIQUE INDEX unique_tag ON public.tag USING btree (repository_id, name)
(2 rows)

registry=# `
