### ISSUE TITLE
Unable to create replication for ECR on harbor running under kubernetes

### ISSUE THREAD

**Issue by ramukima** [goharbor/harbor#15007]
What can we help you?

I have harbor v2.2.2 running on a kubernetes cluster. I see the following error when I try to add an ECR endpoint without specifying access key/secret -

```
2021-05-28T06:08:54Z [ERROR] [/replication/adapter/awsecr/adapter.go:208]: failed to ping registry https://<id>.dkr.<region>.amazonaws.com: EC2RoleRequestError: EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I have added following environment variables to 'core' and 'jobservice' deployments -

- AWS_ROLE_ARN - Policies/Roles set in AWS to allow read access to my ECR instance
- AWS_WEB_IDENTITY_TOKEN_FILE - I am using kubernetes OIDC discovery and projected service account token
- AWS_REGION - Though it should not be required and is extracted from the registry URL.

I do not have any AWS metadata service running (e.g. KIAM) in the cluster. All IAM policies are in place in AWS for the role I am trying to use. 

I tried an 'awscli' pod with similar environment variables and the aws CLI is able to talk to my ECR using the same role ARN.

I checked https://github.com/goharbor/harbor/issues/13687 but no mention of what changes were done to the core/jobservice pods. Also, the setup explained in the issue uses KIAM to associate roles to pods, which is not my case.

Not sure why is the awecr adaptor trying to fetch roles from metadata despite having those environment variables set ?

**Comment by ramukima** [comment]
Reference: https://gist.github.com/stormcat24/e8172b4130776e486f2758508eb4f3aa

**Comment by bitsf** [comment]
if you don't enter access key, it will try to use IAM role, based on feature request https://github.com/goharbor/harbor/issues/12553

**Comment by ramukima** [comment]
Following changes (not the best) work for me (without having KIAM in my k8s cluster), note that I am trying this in non-EC2 environment.

{code}
diff --git a/src/pkg/reg/adapter/awsecr/auth.go b/src/pkg/reg/adapter/awsecr/auth.go
index 8729e8f6f..0d0dc1056 100644
--- a/src/pkg/reg/adapter/awsecr/auth.go
+++ b/src/pkg/reg/adapter/awsecr/auth.go
@@ -18,19 +18,24 @@ import (
 	"encoding/base64"
 	"errors"
 	"fmt"
+	"net/http"
+	"net/url"
+	"os"
+	"strings"
+	"time"
+
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/aws/awserr"
 	"github.com/aws/aws-sdk-go/aws/credentials"
 	"github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds"
+	"github.com/aws/aws-sdk-go/aws/credentials/stscreds"
+	"github.com/aws/aws-sdk-go/aws/ec2metadata"
 	"github.com/aws/aws-sdk-go/aws/session"
 	awsecrapi "github.com/aws/aws-sdk-go/service/ecr"
+	"github.com/aws/aws-sdk-go/service/sts"
 	commonhttp "github.com/goharbor/harbor/src/common/http"
 	"github.com/goharbor/harbor/src/common/http/modifier"
 	"github.com/goharbor/harbor/src/lib/log"
-	"net/http"
-	"net/url"
-	"strings"
-	"time"
 )

 // Credential ...
@@ -89,10 +94,29 @@ func (a *awsAuthCredential) Modify(req *http.Request) error {
 }

 func getAwsSvc(region, accessKey, accessSecret string, insecure bool, forceEndpoint *string) (*awsecrapi.ECR, error) {
+
+	log.Debugf("getAwsSvc Environment Variables")
+	for _, env := range os.Environ() {
+		// env is
+		envPair := strings.SplitN(env, "=", 2)
+		key := envPair[0]
+		value := envPair[1]
+
+		log.Debugf("%s : %s\n", key, value)
+	}
+
 	sess, err := session.NewSession()
 	if err != nil {
 		return nil, err
 	}
+
+	var tr *http.Transport
+	if insecure {
+		tr = commonhttp.GetHTTPTransport(commonhttp.InsecureTransport)
+	} else {
+		tr = commonhttp.GetHTTPTransport(commonhttp.SecureTransport)
+	}
+
 	var cred *credentials.Credentials
 	log.Debugf("Aws Ecr getAuthorization %s", accessKey)
 	if accessKey != "" {
@@ -100,15 +124,36 @@ func getAwsSvc(region, accessKey, accessSecret string, insecure bool, forceEndpo
 			accessKey,
 			accessSecret,
 			"")
+	} else if os.Getenv("AWS_WEB_IDENTITY_TOKEN_FILE") != "" {
+		log.Debugf("AWS_ROLE_ARN: %s, AWS_WEB_IDENTITY_TOKEN_FILE: %s",
+			os.Getenv("AWS_ROLE_ARN"), os.Getenv("AWS_WEB_IDENTITY_TOKEN_FILE"))
+
+		aws.NewConfig().
+			WithCredentialsChainVerboseErrors(true).
+			WithCredentials(credentials.NewChainCredentials([]credentials.Provider{
+				&credentials.EnvProvider{},
+				&credentials.SharedCredentialsProvider{},
+				// Required for IRSA
+				stscreds.NewWebIdentityRoleProvider(
+					sts.New(sess),
+					os.Getenv("AWS_ROLE_ARN"),
+					"harbor",
+					os.Getenv("AWS_WEB_IDENTITY_TOKEN_FILE"),
+				),
+				&ec2rolecreds.EC2RoleProvider{
+					Client: ec2metadata.New(sess),
+				},
+			})).
+			WithHTTPClient(&http.Client{
+				Transport: tr,
+			}).
+			WithRegion(region)
+		cred = aws.NewConfig().Credentials
+
 	} else {
 		cred = ec2rolecreds.NewCredentials(sess)
 	}
-	var tr *http.Transport
-	if insecure {
-		tr = commonhttp.GetHTTPTransport(commonhttp.InsecureTransport)
-	} else {
-		tr = commonhttp.GetHTTPTransport(commonhttp.SecureTransport)
-	}
+
 	config := &aws.Config{
 		Credentials: cred,
 		Region:      &region,
{code}

**Comment by ramukima** [comment]
Is it worth getting a PR for this ?

**Comment by Geethree** [comment]
> Is it worth getting a PR for this ?

I vote yes. Leveraging IAM Role Service accounts to let the aws sdk grab temporary credentials from a cluster's OIDC provider is handy.

**Comment by SeanKnight** [comment]
Related to #12888 which shouldn't have been closed.

**Comment by DerrickMartinez** [comment]
Anyone going to get a PR in?

**Comment by DerrickMartinez** [comment]
@ramukima are you going to get a PR going?
