### ISSUE TITLE
Log admin user with OIDC

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#15022]
Hello,
My Harbor (Harbor 2.2.2) is connected to a OIDC (Keycloak).

core logs are full of this log message : "failed to verify secret: user is not onboarded as OIDC user, username: admin"

**Comment by reasonerjt** [comment]
Are you using basic auth to access API?  In that case, you can ignore this message.  This is the middleware of OIDC secret that tries to verify any basic auth header as OIDC CLI secrets.

**Comment by flbla** [comment]
yes, sometimes, but not that much. 
the log line is present 7000 times every hour

**Comment by reasonerjt** [comment]
@flbla 
Do they all have `username: admin` in the message?
If the answer is yes, I'm afraid the only explanation is that the `harbor-core` process receives that many requests.

**Comment by flbla** [comment]
yes, okay thanks
I'll investigate on my side :)
