### ISSUE TITLE
getting random robot username in project logs

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#15021]
**Expected behavior and actual behavior:**
We should have events in logs related robot account created by the user only. But we are getting random robot username in project logs. 

**Steps to reproduce the problem:**
Check project logs after push pull events

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.10.4-417e12ec
- docker engine version: 20.10.5
- docker-compose version:

**Additional context:**
Below yellow marked robots are not created by us. Can you please provide information on when they are created
![image](https://user-images.githubusercontent.com/8274052/120178548-3db95000-c227-11eb-9d20-be37825ee45b.png)

**Comment by phin1x** [comment]
these are robot accounts for harbor internal usage. for example if you use trivy for cve scanning, every time a container gets scanned, a robot account is generated for that action.

**Comment by wy65701436** [comment]
It's by designed.

**Comment by steven-zou** [comment]
we had an answer.
