### ISSUE TITLE
Support distribution-spec in Harbor

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#15038]
**Is your feature request related to a problem? Please describe.**
We are using harbor as an mirror in an airtgapped env and use containerd-features to make it invisible to the user.
We found a few issues with that mirror support ( https://github.com/containerd/containerd/issues/5518 ) and one of the suggestions on how to best proceed was distribution-spec, which containerd already supports ( https://github.com/opencontainers/distribution-spec/blob/v1.0.0/spec.md )
There is a proposed change for direct mirror support, that is also already suppoorted in containerd
https://github.com/opencontainers/distribution-spec/pull/66/files

**Comment by wy65701436** [comment]
thanks, we'll monitor the PR.
