### ISSUE TITLE
Cannot prevent vulnerable images from running with docker 20.10.5

### ISSUE THREAD

**Issue by t-matsuo** [goharbor/harbor#15035]
**Expected behavior and actual behavior:**

Expected: 
"docker pull"  fails if "Prevent vulnerable images from running." is checked.

Actual:
"docker pull" gets success.

**Steps to reproduce the problem:**

1. uncheck "Prevent vulnerable images from running." 
2. docker pull -> success
3. check "Prevent vulnerable images from running." 
4. docker pull -> success    (expected: fail)

**Versions:**

- harbor version: [2.2.1]
- docker engine version: [20.10.5]

**Additional context:**

Docker-ce 19.03.15 can prevent vulnerable images from pulling after unchecking and checking "Prevent vulnerable images from running." 
This behavior probably is related to #13825.

proxy.log (docker-ce 20.10.5)

```
"GET /v2/ HTTP/1.1" 401 76 "-" "docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.5 \x5C(linux\x5C))" 0.004 0.005 .
"GET /service/token?scope=repository%3Alibrary%2Fubi8%3Apull&service=harbor-registry HTTP/1.1" 200 935 "-" "docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.5 \x5C(linux\x5C))" 0.041 0.041 .
"HEAD /v2/library/ubi8/manifests/latest HTTP/1.1" 200 0 "-" "docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.5 \x5C(linux\x5C))" 0.018 0.019 .
```

=> docker pull gets success.

proxy.log (docker-ce 19.03.15)

```
"GET /v2/ HTTP/1.1" 401 76 "-" "docker/19.03.15 go/go1.13.15 git-commit/99e3ed8919 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.15 \x5C(linux\x5C))" 0.033 0.032 .
"GET /service/token?scope=repository%3Alibrary%2Fubi8%3Apull&service=harbor-registry HTTP/1.1" 200 937 "-" "docker/19.03.15 go/go1.13.15 git-commit/99e3ed8919 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.15 \x5C(linux\x5C))" 0.065 0.064 .
"GET /v2/library/ubi8/manifests/latest HTTP/1.1" 412 362 "-" "docker/19.03.15 go/go1.13.15 git-commit/99e3ed8919 kernel/3.10.0-1160.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.15 \x5C(linux\x5C))" 0.105 0.105 .
```

=> docker pull  fails with this message
"Error response from daemon: unknown: current image with 103 vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "High" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist."

**Comment by wy65701436** [comment]
yes, we found that in docker 20, the containerd may leverage the local cache when to pull a image. If the docker client doesn't send the Get manifest request, Harbor cannot give any handling. 

You can try to clean the local image and restart containerd, then it will work.

**Comment by t-matsuo** [comment]
Can't harbor error out on HEAD method ?

**Comment by t-matsuo** [comment]
> You can try to clean the local image and restart containerd, then it will work.

I tried

```
# docker rmi  my-image-name     <= there is  no same image ID
# sytemctl stop docker
# systemctl stop containerd
# systemct start docker
```

but  docker pull gets success.
I confirmed that curl command gets this messages. 

```
# curl --insecure -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' https://my-harbor.example.com/v2/library/my-image-name/manifests/latest
{"errors":[{"code":"PROJECTPOLICYVIOLATION","message":"current image with 102 vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of \"High\" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist."}]}
```

**Comment by wy65701436** [comment]
can you confirm whether the docker client set the get manifest request? The vul middleware only works for this reqeust.

**Comment by t-matsuo** [comment]
I confirmed that dcoker clinet send "HEAD" method. 
"docker rmi" and restaring contaienrd are procedural error ?

How about this ieda noted above ?

```
Can't harbor error out on HEAD method ?
```

**Comment by wy65701436** [comment]
The middleware works for pulling images, but the HEAD reqeust cannot stand for it.

**Comment by wy65701436** [comment]
PR to fix it: https://github.com/goharbor/harbor/pull/15056

**Comment by wy65701436** [comment]
close it as PR merged, @t-matsuo just try with the incoming release.
