### ISSUE TITLE
Can not found Helm charts in dashboard with Harbor 2.2.2

### ISSUE THREAD

**Issue by charles1503** [goharbor/harbor#15031]
I create repository helm,but can not found helm charts in dashboard.
execute command "helm repo add harbor https://domain/helm--username ****--password ****--ca-file /**/**.crt --cert-file /**/**.cert" 

error msg:  Error: looks like "https://domain/helm" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile

What should I do?

**Comment by ninjadq** [comment]
please check the document https://goharbor.io/docs/2.0.0/working-with-projects/working-with-images/managing-helm-charts/
