### ISSUE TITLE
Update document about configuring destination namespace part of replication

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#15044]
Update document about how to configure destination namespace part of replication:
https://goharbor.io/docs/2.2.0/administration/configuring-replication/create-replication-rules/

More background: https://github.com/goharbor/harbor/pull/14818

**Comment by a-mccarthy** [comment]
Thanks for opening @ywk253100! I was testing this feature out, and noticed that the tool tips for Destination registry and Destination Namespace are the same. Is this expected or should i file a new  bug?
<img width="410" alt="Screen Shot 2021-06-08 at 3 59 24 PM" src="https://user-images.githubusercontent.com/20771501/121249825-05db8980-c873-11eb-9252-4d006c9e16c5.png">
<img width="310" alt="Screen Shot 2021-06-08 at 3 59 17 PM" src="https://user-images.githubusercontent.com/20771501/121249826-05db8980-c873-11eb-8022-b7f164af1d52.png">

**Comment by ywk253100** [comment]
It should be a bug 
@AllForNothing please take a look

**Comment by AllForNothing** [comment]
@a-mccarthy  Thanks for the info.  
The tooltip for "Destination registry" is redundant, I will remove it later

**Comment by a-mccarthy** [comment]
Thanks @AllForNothing, i filed a bug for it, #15108.

**Comment by a-mccarthy** [comment]
closed by goharbor/website#225
