### ISSUE TITLE
upgrade failed from 2.1.1 to 2.2.2 version

### ISSUE THREAD

**Issue by arjunprasad2143** [goharbor/harbor#15045]
I'm currently running harbor 2.1.1 version with an external database, external redis and external storage (minio).
We wanted to upgrade to version 2.2.2 . So we followed the steps mentioned in the document : https://goharbor.io/docs/2.2.0/administration/upgrade/

At the step : docker run -it --rm -v /:/hostfs goharbor/prepare:2.2.2 migrate -i /root/harbor/harbor.yml
It fails with below message.

migrating to version 2.2.0
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_2_0/__init__.py", line 20, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_2_0/harbor.yml.jinja", line 353, in top-level template code
    host: {{ external_redis.host }}:{{ external_redis.port }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'port'

Attaching my current harbor.yml file below

hostname: harbor.xxxxx.com
http:
  port: 80
https:
  port: 443
  certificate: /etc/pki/tls/certs/****.cert
  private_key: /etc/pki/tls/private/*****.pem

external_url: https://harbor.xxxxxxxxx.com
harbor_admin_password: xxxxxxxxx

database:
  password: xxxxxxx
  max_idle_conns: 50
  max_open_conns: 1000

data_volume: /data
storage_service:
  ca_bundle: /etc/pki/ca-trust/extracted/pem/********.pem
  s3:
    accesskey: xxxxxxxxx
    secretkey: xxxxxxxxx
    region: xxxxxxxxxx
    regionendpoint: https://xxxxxxxxxxx.com 
    encrypt: false
    bucket: xxxxxxxxx
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  redirect:
    disabled: true
clair:
  updaters_interval: 12

trivy:
  ignore_unfixed: False
  skip_update: False
  insecure: False

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    location: /var/log/harbor

#This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
_version: 2.1.0
external_database:
  harbor:
    host: xxxxxx
    port: 5432
    db_name: harbor
    username: harbor
    password: xxxxxxxx
    ssl_mode: require
    max_idle_conns: 2
    max_open_conns: 0
  clair:
    host: xxxxxxx
    port: 5432
    db_name: clair
    username: harbor
    password: xxxxxxx
    ssl_mode: require
  notary_signer:
    host: xxxxxxx
    port: 5432
    db_name: notarysigner
    username: harbor
    password: xxxxxxx
    ssl_mode: require
  notary_server:
    host: xxxxxxxx
    port: 5432
    db_name: notaryserver
    username: harbor
    password: xxxxxxxx
    ssl_mode: require
external_redis:
    host: xxxxxxxxxxx:6379
    password: xxxxxxxx
proxy:
  http_proxy: http://xxxxxx
  https_proxy: http://xxxxxx
  no_proxy: xxxxxx
  components:
    - core
    - jobservice
    - clair
    - trivy

Any suggestions?

**Comment by arjunprasad2143** [comment]
Fixed this migration issue by updating the yaml file. 
Updated the external redis to include port also in configuration.

external_redis:
  host: xxxxxxxxxxx
  port: 6379
  password: xxxxxxxx
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  clair_db_index: 4
  trivy_db_index: 5


Without the above config the migrator is still throwing error.

Once I changed my harbor.yml with updated redis config as below. The migration completes successfully.

But then when I start harbor, the core service is not starting up due to a database error. 

Jun  2 07:55:26 172.24.0.1 core[1413]: 2021-06-02T05:55:26Z [FATAL] [/core/main.go:188]: failed to migrate: migration failed: could not create unique index "unique_schedule", Key (vendor_type, vendor_id)=(RETENTION, 1) is duplicated. in line 0: /*



_Jun  2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
Jun  2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version._

What can I do to fix the above issue?

**Comment by arjunprasad2143** [comment]
I have checked my current postgres version. Its is 10.15

**Comment by paulliss** [comment]
is it helm or docker-compose.yaml ?

**Comment by arjunprasad2143** [comment]
> is it helm or docker-compose.yaml ?

This is a single vm setup of harbor. ie docker-compose

**Comment by arjunprasad2143** [comment]
Similar issue reported again : [15066](https://github.com/goharbor/harbor/issues/15066)

**Comment by ninjadq** [comment]
dup of #15066

**Comment by arjunprasad2143** [comment]
> dup of #15066

Not really.. There were 2 issues with the upgrade and I had done a work around with the issue found on 15066.

The database issue also exists. 

Jun 2 07:55:26 172.24.0.1 core[1413]: 2021-06-02T05:55:26Z [FATAL] [/core/main.go:188]: failed to migrate: migration failed: could not create unique index "unique_schedule", Key (vendor_type, vendor_id)=(RETENTION, 1) is duplicated. in line 0: /*

Jun 2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
Jun 2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.
