### ISSUE TITLE
Occasional "unauthorized to access repository" when pulling images

### ISSUE THREAD

**Issue by BrandonWeng** [goharbor/harbor#15052]
**Expected behavior and actual behavior:**

Expected: Once the client logins in, it's able to pull images consistently. 

Actual: Able to pull images successfully but occasionally receive 
`Error response from daemon: unauthorized: unauthorized to access repository: library/node–exp, action: pull: unauthorized to access repository: library/node-exp, action: pull`

In the harbor-core pod I see 
```
2021-06-02T20:16:39Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/
2021-06-02T20:16:39Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="754f6e59-9610-40fd-8f0e-f24bac448ff2"]: an unauthorized security context generated for request GET /v2/
2021-06-02T20:16:39Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
```

**Steps to reproduce the problem:**
1. docker login to a Harbor registry with robot acccount that has permission to pull artifacts, create and destroy tag.
2. consistently run `docker pull ....`
3. Observe that sometimes it may fail with unauthorized access

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.2]
- docker engine version: [19.03.14]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by steven-zou** [comment]
@BrandonWeng 

Could you please provide the full core.log and related context for us to do easy troubleshooting?

**Comment by BrandonWeng** [comment]
Actually, this seems to be fine now. Sorry for the noise, it was an issue on our side with a flakey setup.
