### ISSUE TITLE
How can we enable the expired robot account from Harbor Database without changing the credentials?

### ISSUE THREAD

**Issue by jyotinpo** [goharbor/harbor#15051]
We are using Harbor as Docker Repository in the organization. To push/pull the docker images through Jenkins CI/CD or K8S deployment, we have created a Robot account.

This robot account expired and we wish to extend the expiry without changing the credentials for it. We made an attempt to modify the ```robot``` table in the ```registry``` schema of Harbor by changing the expiry date to ```-1```. However, this change was reflected only in the Harbor UI but the credentials are still not valid. While trying to login through the Harbor Robot credentials, we are encountering the below error message:

```unauthorized: unauthorized to access repository: abc-def/pqr```

**Updated change on the Harbor UI**

![image](https://user-images.githubusercontent.com/14236343/120540202-081e8d80-c406-11eb-883c-75657772fec1.png)

Which tables shall be referred to for this change in Harbor DB?

Links already referred:
https://github.com/goharbor/harbor/issues/9966
https://github.com/goharbor/harbor/issues/8405

Stackoverflow:
https://stackoverflow.com/questions/67811207/how-can-we-enable-the-expired-robot-account-from-harbor-database-without-changin

Harbor Version - 2.0

**Comment by wy65701436** [comment]
This is supported by robot v2 which is introduced from v2.2, you can upgrade to this version and create some new robot accounts(v2) for instead. 

For the robotv1, it's no way to update the expiration date as it's encapsulated into the jwt token. 

BTW, it's **not recommened** to update the DB directly for any reason,  as it may cause some unexpected behaviors.
