### ISSUE TITLE
How can key/value metadata be added to an artifact?

### ISSUE THREAD

**Issue by YAMLcase** [goharbor/harbor#15058]
How can key/value metadata be added to an image?  For instance, we want our automation tool to have a daily task that checks the number of days an image has failed vulnerability scan.  Labels get _close_ to what we're trying to accomplish, but if we're concerned about only 9 days, then that's 9 labels created for the project.  when we need to start storing strings this won't be a workable solution.

**Comment by ywk253100** [comment]
I‘'m afraid that label may be the feature most closest to your requirement.

OCI artifact manifest annotation is another feature to support customized metadata, but this needs operations during the image building
