### ISSUE TITLE
Internal server error when modifying replication rules after update to 2.2.2

### ISSUE THREAD

**Issue by dan-m8t** [goharbor/harbor#15061]
Hey!

Yesterday I updated my harbor instance to version 2.2.2.
The first attempt failed because the database couldn't be migrated, after I changed "_version" to 2.2.2 in harbor.yml it seemed to fix the issue.
Nevermind I wanted to edit an old replication rule, but every attempt on editing the rules leads to a "internal server error" . It seems the replications are running but I see no logs anymore and I am not sure if the replication jobs are really running.

Where should I take a look to fix the issue?

In the jobservice.log I can see something like this:

`Jun  4 08:37:44 172.18.0.1 jobservice[2048]: 2021-06-04T06:37:44Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 30ff7d5cc9846c2985506cb1 not found"}]}
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: , evt=status change: job=30ff7d5cc9846c2985506cb1, status=Error, revision=1622788144->https://core:8443/service/notifications/tasks/3822815, duration=2.160588611s
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: 2021-06-04T06:37:44Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 171550116ffd8a4fb23a62f5 not found"}]}
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: , evt=status change: job=171550116ffd8a4fb23a62f5, status=Error, revision=1622788144->https://core:8443/service/notifications/tasks/3822586, duration=23.822999886s
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: 2021-06-04T06:37:44Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 8bd8fc407af759f4d1a5644c not found"}]}
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: , evt=status change: job=8bd8fc407af759f4d1a5644c, status=Running, revision=1622788144->https://core:8443/service/notifications/tasks/3823292, duration=21.301165541s
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: 2021-06-04T06:37:44Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 1afbe6eea8eaec2a8bc119af not found"}]}
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: , evt=status change: job=1afbe6eea8eaec2a8bc119af, status=Error, revision=1622788144->https://core:8443/service/notifications/tasks/3823169, duration=4.635336411s
Jun  4 08:37:44 172.18.0.1 jobservice[2048]: 2021-06-04T06:37:44Z [ERROR] [/jobservice/hook/hook_agent.go:159]: Retry: still failed after all retries: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 42e961b2580ee546a37cf50b not found"}]}`

Any clues on how to repair this?

thanks

**Comment by steven-zou** [comment]
@dan-m8t 

The logs shown in the jobservice log may not be related to the issue you mentioned. For the details of the internal server, you need to check the core log and see what happened?

**Comment by steven-zou** [comment]
@ywk253100 

For the error messages returned by the hook, are there any potential problems?

**Comment by kiorky** [comment]
seems to look like #15169
