### ISSUE TITLE
content trust will break after the "hostname" of Harbor changes.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#1506]
As the GUN in notary has the hostname of Harbor, if the hostname changes, the GUN in notary will stay the same, and docker client will fail to look up the targets from notary when user use the new hostname to pull image.

**Comment by stuclem** [comment]
Proposed release note entry:

-----

- <b>Docker Content Trust does not function if the hostname of vSphere Integrated Containers Registry changes. [#1506](https://github.com/vmware/harbor/issues/1506)</b>

------

@reasonerjt is this OK? Thanks!

**Comment by stuclem** [comment]
This documented in the release notes, so removing the kind/note label.
