### ISSUE TITLE
nginx has a vulnerability CVE.

### ISSUE THREAD

**Issue by wangyanghack** [goharbor/harbor#15065]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
nginx has a vulnerability CVE. 
CNNVD recommend upgrade nginx to the latest versions(1.20.1, 1.21.0) which has been patched for this vulnerability. Should portal and nginx in harbor upgrade to the latest version?
http://www.cnnvd.org.cn/web/xxk/ldxqById.tag?CNNVD=CNNVD-202105-1581

**Comment by phin1x** [comment]
duplicated to #14489 and #13341

**Comment by wangyanghack** [comment]
thanks a lot
