### ISSUE TITLE
Can't change to readonly mode when the declarative config is enabled.

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#15069]
Can't change to readonly mode when the declarative config is enabled although I can enable the checkbox in the portal.

The same issue to enable the webhook.

And I can save the configurations when adding some items in the CVE allowlist, but the readonly checkbox is still unenabled when refreshing the page, the webhook checkbox is enabled.

![image](https://user-images.githubusercontent.com/5634205/120953143-fda22200-c77e-11eb-9172-3c2ff679ffa3.png)

**Comment by AllForNothing** [comment]
Just a UI issue, will fix it later
