### ISSUE TITLE
How to replace the certificate and the pull command?

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#15070]
docker pull harbor.kubesphere.lan/calico/pod2daemon-flexvol@sha256:0a8bbc9c2ab2850cc8d53c2db261ea683bd05797dc09f5078ddde7be7e9c07a7

change for

docker pull harbor.misteruly.cn/calico/pod2daemon-flexvol@sha256:0a8bbc9c2ab2850cc8d53c2db261ea683bd05797dc09f5078ddde7be7e9c07a7

**Comment by steven-zou** [comment]
So far, we have no plan to support accessing Harbor via multiple domains dynamically.
