### ISSUE TITLE
LDAP Group permission/role lost on Project during upgrade from 2.0.0 to 2.2.2

### ISSUE THREAD

**Issue by JanusTekk** [goharbor/harbor#15073]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Users belonging to LDAP groups with permissions to view projects in harbor should still be able to view projects after an upgrade from 2.0.0 to 2.2.2

**Steps to reproduce the problem:**
1. Grant a LDAP group the Guest permission on a project in harbor 2.0.0
2. User can log in and view the project
3. Upgrade harbor to 2.2.2
4. User can log in, but not view the project in harbor

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.0 & 2.2.2

**Additional context:**

Note that we had to remove the group from harbor and re-add it to the projects for them to start working again.

**Comment by crossRT** [comment]
I think I have the same problem as urs.
harbor version: 2.3.0

Pretty sure the LDAP group search query is correct,
but not sure why is that all users in the group are not able to view the project.

just found there is another issue that might relate to this as well.
https://github.com/goharbor/harbor/issues/15171

**Comment by stonezdj** [comment]
Could you please check you have configured these items?
```
ldap_group_base_dn
ldap_group_search_scope
ldap_group_membership_attribute
ldap_group_search_filter
```

**Comment by Moep90** [comment]
@stonezdj It has fixed the issue for setting your suggested fields.
BUT, we have multiple LDAP Group Trees.
```
cn=users,cn=example,cn=com
cn=groups1,cn=example,cn=com
cn=groups2,cn=example,cn=com
```
Now we had to fix set one path.
