### ISSUE TITLE
create new tag to different repo

### ISSUE THREAD

**Issue by childe** [goharbor/harbor#15078]
**Is your feature request related to a problem? Please describe.**

No related problems found in issues.

`POST ​/projects​/{project_name}​/repositories​/{repository_name}​/artifacts​/{reference}​/tags Create tag` API could create a new tag in the same repository for now . 

**Describe the solution you'd like**

We want to create a new tag to a  different repository

**Describe the main design/architecture of your solution**

artifactAPI.CreateTag  uses RepositoryID and ArtifactID from src tag to create the new tag. Maybe it can use it from params?

**Describe the development plan you've considered**

**Additional context**

harbor v2.2.0

**Comment by steven-zou** [comment]
Have u tried the `reTag` API?

**Comment by childe** [comment]
> Have u tried the `reTag` API?

I did not find `reTag` API in v2.2.0 .

`POST ​/repositories​/{repo_name}​/tags Retag an image` exists in v1.10.0

**Comment by AllForNothing** [comment]
@childe You can use this API:
https://localhost:4200/api/v2.0/projects/test061623167428/repositories/abc/artifacts?from=library%2Fhello-world%40sha256%3A92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a


And you can also do it on UI
![image](https://user-images.githubusercontent.com/30999793/121280540-10e0f900-c909-11eb-8a37-7212c481dab0.png)
![image](https://user-images.githubusercontent.com/30999793/121280636-353cd580-c909-11eb-9174-825c3ff8eb26.png)

**Comment by childe** [comment]
@AllForNothing Thank you.  But this API is too heavy because it copy all data deeply to dst.

What I want it to add a **lightweight** tag (like a pointer) to existing artifact.  Does this idea make sense?
