### ISSUE TITLE
upgrade failed from 2.1.1 to 2.2.2 "Dirty database issue"

### ISSUE THREAD

**Issue by arjunprasad2143** [goharbor/harbor#15088]
I'm currently running harbor 2.1.1 version with an external database, external redis and external storage (minio).
We wanted to upgrade to version 2.2.2 . So we followed the steps mentioned in the document : https://goharbor.io/docs/2.2.0/administration/upgrade/

But then when I start harbor, after the migration is complete the core service is not starting up due to a database error.

Jun 2 07:55:26 172.24.0.1 core[1413]: 2021-06-02T05:55:26Z [FATAL] [/core/main.go:188]: failed to migrate: migration failed: could not create unique index "unique_schedule", Key (vendor_type, vendor_id)=(RETENTION, 1) is duplicated. in line 0: /*

Jun 2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
Jun 2 07:55:27 172.24.0.1 core[1413]: 2021-06-02T05:55:27Z [FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.

What can I do to fix the above issue?

Attaching my current harbor.yml file below

hostname: harbor.xxxxx.com
http:
port: 80
https:
port: 443
certificate: /etc/pki/tls/certs/****.cert
private_key: /etc/pki/tls/private/*****.pem

external_url: https://harbor.xxxxxxxxx.com
harbor_admin_password: xxxxxxxxx

database:
password: xxxxxxx
max_idle_conns: 50
max_open_conns: 1000

data_volume: /data
storage_service:
ca_bundle: /etc/pki/ca-trust/extracted/pem/********.pem
s3:
accesskey: xxxxxxxxx
secretkey: xxxxxxxxx
region: xxxxxxxxxx
regionendpoint: https://xxxxxxxxxxx.com
encrypt: false
bucket: xxxxxxxxx
secure: true
v4auth: true
chunksize: 5242880
rootdirectory: /
redirect:
disabled: true
clair:
updaters_interval: 12

trivy:
ignore_unfixed: False
skip_update: False
insecure: False

jobservice:
max_job_workers: 10

notification:
webhook_job_max_retry: 10

chart:
absolute_url: disabled
log:
level: info
local:
rotate_count: 50
location: /var/log/harbor

#This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
_version: 2.1.0
external_database:
harbor:
host: xxxxxx
port: 5432
db_name: harbor
username: harbor
password: xxxxxxxx
ssl_mode: require
max_idle_conns: 2
max_open_conns: 0
clair:
host: xxxxxxx
port: 5432
db_name: clair
username: harbor
password: xxxxxxx
ssl_mode: require
notary_signer:
host: xxxxxxx
port: 5432
db_name: notarysigner
username: harbor
password: xxxxxxx
ssl_mode: require
notary_server:
host: xxxxxxxx
port: 5432
db_name: notaryserver
username: harbor
password: xxxxxxxx
ssl_mode: require
external_redis:
host: xxxxxxxxxxx:6379
password: xxxxxxxx
proxy:
http_proxy: http://xxxxxx
https_proxy: http://xxxxxx
no_proxy: xxxxxx
components:
- core
- jobservice
- clair
- trivy

Any suggestions?

**Comment by bitsf** [comment]
looks like you have some unexpect data in database before upgrade
1. `docker exec -it harbor-db psql registry`
2. `select * from schedule;`
check the rows

**Comment by arjunprasad2143** [comment]
select * from schedule;
 id |       creation_time        |        update_time         | vendor_type | vendor_id |    cron     | callback_func_name |         cal
lback_func_param          
----+----------------------------+----------------------------+-------------+-----------+-------------+--------------------+------------
--------------------------
  1 | 2020-11-19 08:29:43.585203 | 2020-11-24 00:00:01.563517 | RETENTION   |         1 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:1,"Trigger":"Schedule"}
 37 | 2021-01-29 12:02:58.094582 | 2021-01-29 12:02:58.094582 | RETENTION   |         3 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:3,"Trigger":"Schedule"}
 38 | 2021-01-29 12:04:35.418125 | 2021-01-29 12:04:35.418125 | RETENTION   |        37 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:37,"Trigger":"Schedule"}
 39 | 2021-01-29 12:08:17.949661 | 2021-01-29 12:08:17.949661 | RETENTION   |         2 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:2,"Trigger":"Schedule"}
 40 | 2021-01-29 12:10:07.268213 | 2021-01-29 12:10:07.268213 | RETENTION   |         1 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:1,"Trigger":"Schedule"}
 41 | 2021-01-29 12:11:15.84392  | 2021-01-29 12:11:15.84392  | RETENTION   |         4 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:4,"Trigger":"Schedule"}
 42 | 2021-02-09 10:00:21.601438 | 2021-02-09 10:00:21.601438 | RETENTION   |        39 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:39,"Trigger":"Schedule"}
 75 | 2021-05-26 09:58:37.396093 | 2021-05-26 09:58:37.396093 | RETENTION   |        72 | 0 0 0 * * * | RETENTION          | {"PolicyID"
:72,"Trigger":"Schedule"}
(8 rows)


I dont see any issue here.

We rolled back our last upgrade and restored our database. Maybe status changed?

**Comment by bitsf** [comment]
you can run sqls in https://github.com/goharbor/harbor/tree/master/make/migrations/postgresql, from 0041_2.1.4_schema.up.sql to 0052_2.2.2_schema.up.sql, one line by one line, and check which sql may have problems.
and update version flag in table schema_migrations at last
then `docker-compose up -d` to start the harbor 2.2.2

**Comment by arjunprasad2143** [comment]
Hello,

As suggested I manually tried to run the sqls one by one. I got the below error.

psql:0050_2.2.0_schema.up.sql:296: ERROR:  could not create unique index "unique_schedule"
DETAIL:  Key (vendor_type, vendor_id)=(RETENTION, 1) is duplicated.

I checked my schedule table and found the below. 

harbor=> select * from schedule;
id  |       creation_time        |        update_time         | vendor_type | vendor_id |        cron         |  callback_func_name  | 
        callback_func_param          | cron_type | extra_attrs 
-----+----------------------------+----------------------------+-------------+-----------+---------------------+----------------------+-
-------------------------------------+-----------+-------------
   1 | 2020-11-19 08:29:43.585203 | 2020-11-24 00:00:01.563517 | RETENTION   |         1 | 0 0 0 * * *         | RETENTION            | {"PolicyID":1,"Trigger":"Schedule"}  |           | 
  37 | 2021-01-29 12:02:58.094582 | 2021-01-29 12:02:58.094582 | RETENTION   |         3 | 0 0 0 * * *         | RETENTION            | {"PolicyID":3,"Trigger":"Schedule"}  |           | 
  38 | 2021-01-29 12:04:35.418125 | 2021-01-29 12:04:35.418125 | RETENTION   |        37 | 0 0 0 * * *         | RETENTION            | {"PolicyID":37,"Trigger":"Schedule"} |           | 
  39 | 2021-01-29 12:08:17.949661 | 2021-01-29 12:08:17.949661 | RETENTION   |         2 | 0 0 0 * * *         | RETENTION            | {"PolicyID":2,"Trigger":"Schedule"}  |           | 
  40 | 2021-01-29 12:10:07.268213 | 2021-01-29 12:10:07.268213 | RETENTION   |         1 | 0 0 0 * * *         | RETENTION            | {"PolicyID":1,"Trigger":"Schedule"}  |           | 
  41 | 2021-01-29 12:11:15.84392  | 2021-01-29 12:11:15.84392  | RETENTION   |         4 | 0 0 0 * * *         | RETENTION            | {"PolicyID":4,"Trigger":"Schedule"}  |           | 
  42 | 2021-02-09 10:00:21.601438 | 2021-02-09 10:00:21.601438 | RETENTION   |        39 | 0 0 0 * * *         | RETENTION            | {"PolicyID":39,"Trigger":"Schedule"} |           | 
  75 | 2021-05-26 09:58:37.396093 | 2021-05-26 09:58:37.396093 | RETENTION   |        72 | 0 0 0 * * *         | RETENTION            | {"PolicyID":72,"Trigger":"Schedule"} |           | 
 108 | 2021-01-28 16:21:29.547472 | 2021-06-02 02:00:03.156253 | REPLICATION |        41 | 0 0 */8 * * MON-FRI | REPLICATION_CALLBACK | 41                                   |           | 
 109 | 2021-05-26 11:31:21.366231 | 2021-06-02 02:00:03.211081 | REPLICATION |        74 | 0 0 */8 * * MON-FRI | REPLICATION_CALLBACK | 74                                   |           | 
 110 | 2021-01-28 16:22:42.846807 | 2021-06-02 02:00:03.466444 | REPLICATION |        42 | 0 0 */8 * * MON-FRI | REPLICATION_CALLBACK | 42                                   |           | 
 111 | 2021-01-28 16:23:53.771298 | 2021-06-02 02:00:03.538536 | REPLICATION |        43 | 0 0 */8 * * MON-FRI | REPLICATION_CALLBACK | 43                                   |           | 
 112 | 2021-01-28 16:19:33.770985 | 2021-06-02 02:00:03.546685 | REPLICATION |        40 | 0 0 */8 * * MON-FRI | REPLICATION_CALLBACK | 40                                   |           |             |        0
 113 | 2020-12-17 11:46:00        | 2021-01-28 01:00:02.535457 | SCAN_ALL    |         0 | 0 0 0 * * *         | scanAll              |                                      | Daily     |             |        0
(14 rows)

Any help what might be the issue? 
Also
harbor=> select * from schema_migrations ;
 version | dirty 
---------+-------
      40 | f
(1 row)

To what version should I upgrade to?

Looking forward to your response.

**Comment by arjunprasad2143** [comment]
Manually running the queries and upgrading the version to 52 in schema migrations fixed the issue for me.

**Comment by senthil13** [comment]
@arjunprasad2143  -  could you please provide the queries and steps you took to resolve them?

**Comment by arjunprasad2143** [comment]
@senthil13 

queries can be found here : https://github.com/goharbor/harbor/tree/master/make/migrations/postgresql
You can run the queries depending on the version that you are in and upgrading to.

For example if you are upgrading from 2.1.1 to 2.2.2, run the queries 0041_2.1.4_schema.up.sql, 0050_2.2.0_schema.up.sql, 0051_2.2.1_schema.up.sql and 0052_2.2.2_schema.up.sql. Then update the version to 52 in schema migrations table.

**Comment by senthil13** [comment]
Sorry for the late response, we followed the same by applying each update.sql, but still we say the dirty version entry. What we missing is the last step which is updating the version to 52. Which we did now and all are good.
