### ISSUE TITLE
Remove duplicate tool tip for Destination registry from replication rule UI

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#15108]
**Expected behavior and actual behavior:**
Opening issue [based on this comment](https://github.com/goharbor/harbor/issues/15044#issuecomment-857301806).

The tool tips for Destination registry and Destination Namespace are the same when creating a new replication rule.

<img width="410" alt="Screen Shot 2021-06-08 at 3 59 24 PM" src="https://user-images.githubusercontent.com/20771501/121249825-05db8980-c873-11eb-9252-4d006c9e16c5.png">
<img width="310" alt="Screen Shot 2021-06-08 at 3 59 17 PM" src="https://user-images.githubusercontent.com/20771501/121249826-05db8980-c873-11eb-8022-b7f164af1d52.png">

We should remove the duplicated tool tip from Destination Registry. 

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.0

**Comment by AllForNothing** [comment]
Fixed via #15093
