### ISSUE TITLE
Add maintenance mode that pauses all scheduled jobs while enabled

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#15107]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Harbor provides a read-only mode that blocks any writes to the system, this is useful however we identified cases where we would also like to have a Maintenance Mode that will automatically pause all scheduled jobs from executing while it is enabled (retention rules, garbage collection, replication, etc...)

Using maintenance mode is particularly useful during Harbor upgrades or infrastructure work related to where Harbor is deployed, in our case the most common case is K8s cluster upgrades, we would like to actively disable any jobs from executing while we're making these upgrades as currently it causes things to fail due to transient errors when services connect to each other and could be avoided.

**Describe the main design/architecture of your solution**
Maintenance mode toggle (enable/disable) and optionally a duration (i.e. that turns off maintenance mode after a defined period) that can be set from the UI and API, while enabled the system will not execute any scheduled/recurring jobs.

**Describe the development plan you've considered**
Don't have any specific plan here, but I suspect this is mostly going to affect the Jobservice scheduling engine that will need to check the state of the maintenance mode toggle and act not execute jobs if it's enabled.

**Additional context**
N/A

**Comment by dkulchinsky** [comment]
still relevant

**Comment by ywk253100** [comment]
We have enhanced the read-only mode in 2.6 which also blocks the write operation from the internal jobs.
So to a certain extent, I think this should meet your requirement with this change

**Comment by stonezdj** [comment]
With this feature https://github.com/goharbor/harbor/issues/17512 integrated, 
The admin user could pause all pending tasks and stop all the running jobs in the worker pool.  it meets the requirement of maintenance mode, right?

**Comment by dkulchinsky** [comment]
Hey @stonezdj, apologies for not replying sooner.

Closing this as this is now possible with the new Jobs UI

Thanks!
