### ISSUE TITLE
Expired robot account token can be used to login to the docker registry

### ISSUE THREAD

**Issue by j-zimnowoda** [goharbor/harbor#15110]
Expired robot account token can be used to login to the docker registry

**Expected behavior and actual behavior:**

actual behavior:
I can successfully login but I am not authorised to pull image.

Expected behavior
On docker login with expired credentials a user shall not authenticate
On docker pull with expired credentials  a user shall see unauthenticated not unauthorised.

**Steps to reproduce the problem:**
1. Open Dashbord
2. Go to project
3. Create robot account with short lived token
4. Wait until token expiries
5. docker login -u <roboruser> -p <robor password>
6. Observe that you are authenticated
7. Try to pull and observe that you are not authorised

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.0
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Comment by wy65701436** [comment]
hi, which version robot are you using? v1 or v2?

**Comment by j-zimnowoda** [comment]
It was v1
