### ISSUE TITLE
not support tencent cloud COS  as docker image backend storage?

### ISSUE THREAD

**Issue by t1faith** [goharbor/harbor#15117]
I deployed harbor-v2.2.2 on tencent cloud, use tencent cloud COS as the docker image storage , when i pushed image to registry, it didn't work properly.there is need to push twice, ,first push,it keeps "retrying" status untill return "500 internal error",next push, it's ok.
In addition,I use Aliyun OSS and AWS S3 as the docker image storage, it's all ok.
I guess harbor don't support tencent cloud COS.
thanks .

**Comment by t1faith** [comment]
docker@txshdaily-daily-penglai-build-011 ~]$ docker push tmp-shdocker.mozzi.com/mozzi/node:10.15.0-alpine
The push refers to repository [tmp-shdocker.mozzi.com/mozzi/node]
cdb1bc319303: Layer already exists
abbd24a8638d: Layer already exists
945feb772e99: Layer already exists
7bff100f35cb: Layer already exists
received unexpected HTTP status: 500 Internal Server Error
[docker@txshdaily-daily-penglai-build-011 ~]$ docker push tmp-shdocker.mozzi.com/mozzi/node:10.15.0-alpine
The push refers to repository [tmp-shdocker.mozzi.com/mozzi/node]
cdb1bc319303: Layer already exists
abbd24a8638d: Layer already exists
945feb772e99: Layer already exists
7bff100f35cb: Layer already exists
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the tmp-shdocker.mozzi.com registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
10.15.0-alpine: digest: sha256:f9c6f5dc48333ad13a1d09bf97d6df1eda7c50f2f63d4c661a735ec5a31e6f7e size: 9750

**Comment by t1faith** [comment]
Jun 10 17:47:09 172.19.0.1 registry[2566]: time="2021-06-10T09:47:09.847503725Z" level=error msg="unknown error completing upload: s3aws: Path not found: /docker/registry/v2/repositories/mozzi/golang/_uploads/76af6da3-7c4e-4f4a-82af-7c122aff4c57/data" auth.user.name="harbor_registry_user" go.version=go1.14.7 http.request.host=tmp-shdocker.mozzi.com http.request.id=46252665-efa9-4ed1-a7e6-0dd5057702a5 http.request.method=PUT http.request.remoteaddr=172.30.66.145 http.request.uri="/v2/mozzi/golang/blobs/uploads/76af6da3-7c4e-4f4a-82af-7c122aff4c57?_state=epILXclGNM0I5pJuZOWhw2HYE2_7g7hcF2_Al9w4yx57Ik5hbWUiOiJtb3p6aS9nb2xhbmciLCJVVUlEIjoiNzZhZjZkYTMtN2M0ZS00ZjRhLTgyYWYtN2MxMjJhZmY0YzU3IiwiT2Zmc2V0IjoxMjgyLCJTdGFydGVkQXQiOiIyMDIxLTA2LTEwVDA5OjQ3OjA3WiJ9&digest=sha256%3A2948ef12fdbdf3e361375f19d5b0359d3cbb6775bf661c45c88edb5e8c819c0d" http.request.useragent="docker/19.03.12 go/go1.13.10 git-commit/48a66213fe kernel/4.14.105-19-0006 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))" vars.name="mozzi/golang" vars.uuid=76af6da3-7c4e-4f4a-82af-7c122aff4c57
Jun 10 17:47:09 172.19.0.1 registry[2566]: time="2021-06-10T09:47:09.847806481Z" level=error msg="error canceling upload after error: already closed" auth.user.name="harbor_registry_user" go.version=go1.14.7 http.request.host=tmp-shdocker.mozzi.com http.request.id=46252665-efa9-4ed1-a7e6-0dd5057702a5 http.request.method=PUT http.request.remoteaddr=172.30.66.145 http.request.uri="/v2/mozzi/golang/blobs/uploads/76af6da3-7c4e-4f4a-82af-7c122aff4c57?_state=epILXclGNM0I5pJuZOWhw2HYE2_7g7hcF2_Al9w4yx57Ik5hbWUiOiJtb3p6aS9nb2xhbmciLCJVVUlEIjoiNzZhZjZkYTMtN2M0ZS00ZjRhLTgyYWYtN2MxMjJhZmY0YzU3IiwiT2Zmc2V0IjoxMjgyLCJTdGFydGVkQXQiOiIyMDIxLTA2LTEwVDA5OjQ3OjA3WiJ9&digest=sha256%3A2948ef12fdbdf3e361375f19d5b0359d3cbb6775bf661c45c88edb5e8c819c0d" http.request.useragent="docker/19.03.12 go/go1.13.10 git-commit/48a66213fe kernel/4.14.105-19-0006 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))" vars.name="mozzi/golang" vars.uuid=76af6da3-7c4e-4f4a-82af-7c122aff4c57
Jun 10 17:47:09 172.19.0.1 registry[2566]: time="2021-06-10T09:47:09.896712422Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: Path not found: /docker/registry/v2/repositories/mozzi/golang/_uploads/76af6da3-7c4e-4f4a-82af-7c122aff4c57/data" err.message="unknown error" go.version=go1.14.7 http.request.host=tmp-shdocker.mozzi.com http.request.id=46252665-efa9-4ed1-a7e6-0dd5057702a5 http.request.method=PUT http.request.remoteaddr=172.30.66.145 http.request.uri="/v2/mozzi/golang/blobs/uploads/76af6da3-7c4e-4f4a-82af-7c122aff4c57?_state=epILXclGNM0I5pJuZOWhw2HYE2_7g7hcF2_Al9w4yx57Ik5hbWUiOiJtb3p6aS9nb2xhbmciLCJVVUlEIjoiNzZhZjZkYTMtN2M0ZS00ZjRhLTgyYWYtN2MxMjJhZmY0YzU3IiwiT2Zmc2V0IjoxMjgyLCJTdGFydGVkQXQiOiIyMDIxLTA2LTEwVDA5OjQ3OjA3WiJ9&digest=sha256%3A2948ef12fdbdf3e361375f19d5b0359d3cbb6775bf661c45c88edb5e8c819c0d" http.request.useragent="docker/19.03.12 go/go1.13.10 git-commit/48a66213fe kernel/4.14.105-19-0006 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.346679051s http.response.status=500 http.response.written=196 vars.name="mozzi/golang" vars.uuid=76af6da3-7c4e-4f4a-82af-7c122aff4c57

**Comment by kofj** [comment]
@t1faith 
When you use Tencent Cloud COS as backend storage, need a special Distribution driver. But this storage driver still is a business source.

**Comment by bitsf** [comment]
@kofj would this be fixed in future?

**Comment by t1faith** [comment]
Okay, I will always support harbor and look forward to supporting COS. That will help me a lot.
