### ISSUE TITLE
No restapi package found

### ISSUE THREAD

**Issue by barrettzjh** [goharbor/harbor#15115]
Hello!
When I read the source code of the master branch, I couldn't load the restapi package,
Full name of package: github.com/goharbor/harbor/src/server/v2.0/restapi
Problem location: github/harbor/src/server/v2.0/handler/handler.go line 28
Thank you very much.

**Comment by bitsf** [comment]
check swagger.yaml, and `make gen_apis`

**Comment by barrettzjh** [comment]
got it! thanks
