### ISSUE TITLE
Harbor GC trigger issue, not able to edit the Schedule to GC option, though it has the value Daily, GC not happening daily.

### ISSUE THREAD

**Issue by prudhvigodithi** [goharbor/harbor#15123]
**Expected behavior and actual behavior:**
We have Harbor Schedule to GC value as daily, this was configured when we installed harbor at v1 and was never changed, now we are using v2, when we try to edit the value of Schedule to GC or just click save, it throws internal server error banner in UI. Also though it has Saved as daily, the GC does not happen, as when we click manually then GC clears all the not required blobs, if GC was running daily, the GB of blobs cleared when we run manually should we less. Also under history I only see trigger type as Manual only.

**Steps to reproduce the problem:**
Under Harbor GC settings, edit Schedule to GC and try to save throws internal server error.vi 

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.3 (installed with helm)
- docker engine version: Docker version 20.10.6, build 370c289(but we have multiple docker versions on different servers)

**Additional context:**
We Expect the schedule GC value to be able to be modified, and once modified able to run the GC in accordingly.
Additionally, we have a test harbor with the Same version, and able to edit and save the schedule GC value, also under history I see both manually and value as Daily.
I expect something was corrupted or disturbed with our main harbor, Garbor collection settings
please let us know what steps we need to take to fix this

- **Harbor config files:** 
Job service logs:
```
2021-06-10T13:40:46Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/252c269c55aafd41f56af949' error: 404 {"code":10010,"message":"object is not found","details":"252c269c55aafd41f56af949"}
2021-06-10T13:42:24Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/252c269c55aafd41f56af949' error: 404 {"code":10010,"message":"object is not found","details":"252c269c55aafd41f56af949"}
```
Core logs:
`2021-06-10T13:51:06Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="58dc71ec-3fbe-458c-b2bf-6774831ff47e"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts`
![Screen Shot 2021-06-10 at 9 40 52 AM](https://user-images.githubusercontent.com/28733332/121538591-e6f40900-c9d2-11eb-9cb5-f582c720fc69.png)
![Screen Shot 2021-06-10 at 10 02 40 AM](https://user-images.githubusercontent.com/28733332/121538761-08ed8b80-c9d3-11eb-8f84-d2a4d67e1838.png)

**Comment by prudhvigodithi** [comment]
Hello, just wanted to follow up, if this issue is only with my configured harbor, or could it be a general issue, please advise, how we can proceed further.
thank you

**Comment by strainovic** [comment]
We are facing the same issue with our Harbor instance v2.1.3.

**Comment by ywk253100** [comment]
Please try to upgrade to v2.1.5 or v2.2.2, this should already be fixed in these minor releases

**Comment by strainovic** [comment]
Thanks, @ywk253100! I will post back my findings after the upgrade.

**Comment by strainovic** [comment]
We've upgraded to v2.1.5 and it works now. Thanks! :)

**Comment by prudhvigodithi** [comment]
Thanks a lot for the update, we will upgrade our harbor to v2.1.5 and test the GC process.

**Comment by prudhvigodithi** [comment]
Hey, I just upgraded to v2.1.5 and after the upgrade, I'm able to edit and save the GC settings, also in the history I'm able to see the status as SCHEDULED with trigger type as Daily.
