### ISSUE TITLE
Portal Frontend About Version not provided (version string is empty)

### ISSUE THREAD

**Issue by MatthiasHertel** [goharbor/harbor#15128]
What can we help you?
 I installed harbor with helm
 
 And the version string is empty
LOC: 
 https://github.com/goharbor/harbor/blob/master/src/portal/src/app/shared/components/about-dialog/about-dialog.component.html#L9
 
 
 
![image](https://user-images.githubusercontent.com/8426566/121565479-c486dd80-ca1c-11eb-8bd5-4a4c8a295b6d.png)

**Comment by AllForNothing** [comment]
@MatthiasHertel What's the response returned from  "systeminfo" API?

**Comment by MatthiasHertel** [comment]
@AllForNothing 

sorry for my late answer

here the harbor_version string is a dash

![image](https://user-images.githubusercontent.com/8426566/127102842-3d1cd4b6-8f67-4de8-b7bd-5e793b37e471.png)

**Comment by MatthiasHertel** [comment]
relates to:
https://github.com/bitnami/bitnami-docker-harbor-portal/issues/19

**Comment by AllForNothing** [comment]
@reasonerjt it seems a back-end issue of  "systeminfo"  API
