### ISSUE TITLE
can't login via docker-cli.

### ISSUE THREAD

**Issue by yshihao** [goharbor/harbor#15127]
i have deployed harbor v2.1.5-rc2 in lab's server. The internal ip address is 192.168.1.61 ,the external ip address is 202.130.39.13. i've done port mapping. i can login by web ui but i can't login via docker-cli.
Does anyone know why?

ysh@yshMacBookPro ~ % docker login 202.120.39.13:61555 -u admin -p Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get http://202.120.39.13:61555/v2/: Get http://192.168.1.61:30002/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

my harbor.yml

> ` Configuration file of Harbor

 The IP address or hostname to access admin UI and registry service.
 DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: 192.168.1.61:30002

 http related config
http:
   port for http, default is 80. If https enabled, this port will redirect to https port
  port: 80

 https related config
 https:
   https port for harbor, default is 443
   port: 443
   The path of cert and key files for nginx
   certificate: /your/certificate/path
   private_key: /your/private/key/path

  Uncomment following will enable tls communication between all harbor components
 internal_tls:
   # set enabled to true means internal tls is enabled
   enabled: true
   # put your cert and key files on dir
   dir: /etc/harbor/tls/internal

 Uncomment external_url if you want to enable external proxy
 And when it enabled the hostname will no longer used
 external_url: https://reg.mydomain.com:8433

 The initial password of Harbor admin
 It only works in first time to install harbor
 Remember Change the admin password from UI after launching Harbor.
harbor_admin_password: Harbor12345

 Harbor DB configuration
database:
   The password for the root user of Harbor DB. Change this before any production use.
 password: root123
   The maximum number of connections in the idle connection pool. If it <=0, no idle connections are retained.
  max_idle_conns: 50
   The maximum number of open connections to the database. If it <= 0, then there is no limit on the number of open connections.
   Note: the default number of connections is 1024 for postgres of harbor.
  max_open_conns: 1000

 The default data volume
data_volume: /data

**Comment by bitsf** [comment]
`hostname: 192.168.1.61:30002` should be ` 202.120.39.13:61555`

**Comment by yshihao** [comment]
> `hostname: 192.168.1.61:30002` should be ` 202.120.39.13:61555`

!!!!!  login succeeded! Thks very much
