### ISSUE TITLE
docker login with official certificate not working: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dariosanna** [goharbor/harbor#15137]
I am using an official certificate to setup Harbor following the Harbor installation documentation.
Nginx works perfect with the certificate (https acces to Harbor gui), but docker login results in x509: certificate signed by unknown authority.

Can you please provide a simple step by step list, how to get rid of the x509: certificate signed by unknown authority error?
The current Harbor 2.2.0 certificate documentaion is somewhat confusing and also not up to date:
- https://goharbor.io/docs/2.2.0/install-config/customize-token-service/ referes to an directory config/ui that does not exists

What i did (but without success)
- update /data/secret/registry/root.crt
- update /data/secret/core/private_key.pem
- restarting all containers

More questions (confusing):
- what must contain /data/secret/keys/secretkey ??
- how to create /data/ca_download/ca.crt (manually?)
- how is the docker configuration on the Harbor hostsystem related to the  x509: certificate signed by unknown authority problem?

Many thanks and best regards.

**Comment by bitsf** [comment]
add cert to path like `/etc/docker/certs.d/core.harbor.domain/ca.crt`
for more detail please search docker document

**Comment by abjoseph** [comment]
> add cert to path like `/etc/docker/certs.d/core.harbor.domain/ca.crt`
> for more detail please search docker document

Your reply was not helpful at all. I am also experiencing this issue with a Let's Encrypt publicly signed cert.
