### ISSUE TITLE
Helm charts not being logged in Harbor GUI

### ISSUE THREAD

**Issue by Casperfrost12** [goharbor/harbor#15140]
Hi

I have noticed that the Harbor GUI does not log pushing, pulling and deleting helm charts in a project. I tried creating a project and pushing a docker image to a project, which logs fine to the 'logs' section in the sidebar. But pushing a helm chart and deleting it shows nothing.
I am sorry if this is a feature you can enable, but i haven't found it anywhere.

**Comment by bitsf** [comment]
chartmuseum is going be deprecated in harbor, this is low priority now

**Comment by Casperfrost12** [comment]
Can you shed some light on what the new solution will be instead?
