### ISSUE TITLE
Inaccurate API documentation

### ISSUE THREAD

**Issue by piximos** [goharbor/harbor#15141]
Hello, 
In the [Harbor REST API documentation](https://github.com/goharbor/website/blob/master/docs/build-customize-contribute/configure-swagger.md), the [link for `prepare-swagger.sh`](https://raw.githubusercontent.com/goharbor/harbor/master/docs/prepare-swagger.sh) points to an obsolete link. Also, the [link for the `swagger.yaml`](https://raw.githubusercontent.com/goharbor/harbor/master/docs/swagger.yaml) should point to [the following link instead](https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml)

**Comment by heww** [comment]
Duplicated with  https://github.com/goharbor/website/issues/118

**Comment by heww** [comment]
Also duplicated with #13552
