### ISSUE TITLE
core metrics export does not support TLS even INTERNAL_TLS_ENABLED is enabled

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#15145]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

when INTERNAL_TLS_ENABLED is enable, the core metrics port should listen in TLS mode, but it still listen to http only,
refer to 

lib/metric/server.go:func **ServeProm**(path string, port int) {

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

enable INTERNAL_TLS_ENABLED flag and core metrics as below:

metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.1]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

#   curl -l **https**://harbor-harbor-core:8001/metrics
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by ninjadq** [comment]
the current harbor internal TLS not includes the metrics endpoint. If you have some security concerns, you can config a firewall rule to let the metrics only accessed by the specific host.

**Comment by danielzhanghl** [comment]
since it's the design, just close it.
