### ISSUE TITLE
How to scan an artifact using API

### ISSUE THREAD

**Issue by mdconner** [goharbor/harbor#15144]
Are additional header parameters or payload needed to issue /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/scan?  Per doc, only {project}, {repo}, and {reference} are needed.

I've verified my URL is correct by checking the call the GUI makes using Developer Tools.  I noticed a payload "{"headers":{"normalizedNames":[],"lazyUpdate":null},"responseType":"json"}" is sent along with many additional parameters.

When I make a similar request via PostMan, I get "CSRF token invalid".  From my JavaScript/Node app, I get a 401 error - verified user has permission (Project Administrator) to scan

We are using OAuth for Single-Sign-On and have had good success with other GET calls (projects, repos, artifacts).

**Comment by heww** [comment]
What does `using OAuth for Single-Sign-On` mean? 

How about try to disable the cookie in the postman?

**Comment by mdconner** [comment]
Was stating using OAuth to get bearer token

Cookies were the problem in Postman and found issue with my app too.  Thank you
