### ISSUE TITLE
Configure Proxy Cache without library for official image

### ISSUE THREAD

**Issue by patsevanton** [goharbor/harbor#15154]
Hello! Thanks for Harbor!

I read.

> To start using the proxy cache, configure your docker pull commands or pod manifests to reference the proxy cache project by adding <harbor_servername>/<proxy_project_name>/ as a prefix to the image tag. For example:
> 
> > docker pull <harbor_server_name>/<proxy_project_name>/goharbor/harbor-core:dev
> To pull official images or from single level repositories, make sure to include the ‘library’ namespace.
> 
> > docker pull <harbor_server_name>/library/hello-world:latest

But Please will make Configure Proxy Cache without library for official image

**Comment by Vad1mo** [comment]
Official images all have `library` its the docker client that silently appends `library`, There is nothing that can be done about that on Harbor side.

**Comment by bitsf** [comment]
this is currently by design
