### ISSUE TITLE
"create" operation log is outputed in project log when pushing container image

### ISSUE THREAD

**Issue by t-matsuo** [goharbor/harbor#15152]
**Expected behavior and actual behavior:**

--- Exptected ---
When I push container image, "push" operation log is outputed in projects log.

| Username  | Resource                 | Resource Type | Operation | Timestamp           |
| admin        | library/alpine:latest | artifact             | push          | 6/16/21, 2:06 PM |

--- Actual behaivor ---
When I pushed container image, "create" operation log was outputed in projects log.

| Username  | Resource                 | Resource Type | Operation | Timestamp           |
| admin        | library/alpine:latest | artifact             | create       | 6/16/21, 2:06 PM |

I re-pushed same image again, but same log was outputed.
When is "push" operation log outputed ? 

**Steps to reproduce the problem:**

docker push  my-harbor-server/library/alpine:latest

**Versions:**

- harbor version: 2.2.1
- docker engine version: [20.10.5]

**Comment by t-matsuo** [comment]
Is this a specification ?
Waht's "Push" Operation ? 
In this doc, there are "pull" "push" "create" "delete" "others" operations.
https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/access-project-logs/

**Comment by wy65701436** [comment]
actually, the create artifact event is for push.

**Comment by AllForNothing** [comment]
@a-mccarthy Need to update the screenshot of Harbor doc. "push" has been removed now
 
![image](https://user-images.githubusercontent.com/30999793/134281669-cad1ad30-96c6-4fbe-9176-e43335b3b573.png)
