### ISSUE TITLE
Portal injects password in the field "Email password" automatically in SMTP configuration

### ISSUE THREAD

**Issue by abdennour** [goharbor/harbor#15163]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I expect to be able to configure insecure SMTP which means port 25 and no credentials.
Actually, i didn't put Email password but it was filled in automatically :( 
![image](https://user-images.githubusercontent.com/1788384/122672826-32c65f80-d1d6-11eb-813b-c172396a050e.png)

**Steps to reproduce the problem:**
- install harbor thru helm chart ( we have http proxy) 
- navigate to http://host:port/harbor/configs
- go to tab Email
- configure insecure SMTP outgoing
- Click on Save 

You will see that the field "Email Password" has been filled in automatically.
![image](https://user-images.githubusercontent.com/1788384/122672925-b6804c00-d1d6-11eb-8e42-35fd20816163.png)

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by AllForNothing** [comment]
@abdennour That's a faked password，it acts as a placeholder.
So it's not an issue
