### ISSUE TITLE
Using same storage backend for multiple Harbor instances

### ISSUE THREAD

**Issue by omkarparkhe** [goharbor/harbor#15162]
Hi, 
1. I have multiple Harbor instances running and I would like to use the same backend storage for all the instances. 
2. Essentially one image pull from an external repository to any one of Harbor instances should reflect the changes in all the instances. 

I am using the latest Harbor version and is it possible to achieve both of the above?

**Comment by omkarparkhe** [comment]
I am aware that one way of achieving it is to use replication rules to replicate repositories/images from one instances to others. But this will essentially store the images/repositories to individual backend storage for each instance which is not desirable.

**Comment by phin1x** [comment]
I don't think its possible, all harbor instances would need to use the same redis, postgres and storage backend. Only sharing the storage backend is not enougth.

**Comment by omkarparkhe** [comment]
Ok, is it possible if I have a dedicated separately hosted redis and postgres services?

**Comment by omkarparkhe** [comment]
So essentially configuring an external redis and an external database?

**Comment by phin1x** [comment]
Yes, but then you have one big decentrelized harbor instance.

**Comment by omkarparkhe** [comment]
ok, but the question is it possible in this case or no?
And if yes then which is a better option - doing it this way or instead having a kubernetes cluster?

**Comment by phin1x** [comment]
No, you can't have multiple harbor instance with the same storage and different redis and postgres instances. Harbor saves some information about the images layers in its database. So even if you would use the same storage backend, the change in one harbor instance would not reflect to another instance. Also you could run into some integrity issues if a gc job in one instance deletes a layer from the storage which is still in use in a other instance.
one thing you could do is having one big harbor instance with a central storage (s3 for example), redis and postgres instance with multipe endpoints in different regions.

the docker-compose setup and the kubernetes helm chart setup supports both external redis and postgres instances. for example one of our harbor instance is running on aws eks with aws elasticache, s3 and rds for the external components. so it depends on you, what you prefer. if you prefer to scale you instances, go with the kubernetes setup.

**Comment by omkarparkhe** [comment]
okay, thanks
And just one correction - I meant is it possible in case multiple instances have the same storage, redis and postgres. These could be internal using a shared network file system or an external one.

**Comment by omkarparkhe** [comment]
But I think Kubernetes would the answer for horizontal scaling.
