### ISSUE TITLE
failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

### ISSUE THREAD

**Issue by xyzzen** [goharbor/harbor#15175]
#9382 #12334 都看过.试过了就是不行..
Harbor版本2.0.0

**Comment by xyzzen** [comment]
目前解决方案是从2.0升级为2.3但是harbor-db无法启动,这个版本换成了2.0的
2.0版本的这个报错,显示日志有问题,但是无从下手,不知道如何解决,不能保证2.3版本的某一天不会出现这个问题.
有解决的大佬麻烦给一下排查思路,非常感谢.

**Comment by yanji09** [comment]
Would you check the docker logs to find more information?

**Comment by pxvp2008** [comment]
`docker rmi <harbor>`，删掉所有镜像，然后 `docker-compose up -d`即可
