### ISSUE TITLE
Image scan status stays in "queued" 

### ISSUE THREAD

**Issue by cycwll** [goharbor/harbor#15170]
I installed a harbor v2.0.0 via helm in k8s.
Now, all scan job can't run, and the status stays in "queued", I referred to this issue： https://github.com/goharbor/harbor/issues/11720. 
And now has been upgraded to v2.2.1. But there are still the problems.
![image](https://user-images.githubusercontent.com/6410130/122718067-0e828580-d29f-11eb-9093-3ab0ec983c51.png)

I tried to restart all pods, But no effect. The Data is persistent.

```
# kubectl -n harbor get statefulset  
NAME                     READY   AGE
harbor-harbor-database   1/1     381d
harbor-harbor-redis      1/1     381d
harbor-harbor-trivy      1/1     381d
```

How can I clear this queue? Or what should I do?
Thanks a lot.

**Comment by bitsf** [comment]
is there other jobs, like replication also queued?

**Comment by cycwll** [comment]
#select status,vendor_type from task where status !='Success' and status !='Stopped';     

 status  | vendor_type 
---------+-------------
 Error   | IMAGE_SCAN
 Pending | IMAGE_SCAN
 Pending | IMAGE_SCAN
 Pending | IMAGE_SCAN
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | REPLICATION
 Error   | IMAGE_SCAN
 Error   | IMAGE_SCAN
(48 rows)

**Comment by bitsf** [comment]
@heww please also help how to clean the db to stop

**Comment by cycwll** [comment]
I deleted the directory /home/scanner/.cache/, and then work is ok.

**Comment by piyush94** [comment]
@bitsf Hi, I am also currently facing this issue. I deleted the directory /home/scanner/.cache/ and also cleared job_service redis db but still it's stuck at queued. Can you help me with how to clear this queue ?

**Comment by stonezdj** [comment]
@piyush94 if the job service queue is occupied by other tasks, then the scan job could stay in `queued` status
