### ISSUE TITLE
X509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by khbrady** [goharbor/harbor#15189]
I am building a Tanzu Kubernetes install, Tanzu 1.3 on vsphere 6.7U3 with  harbor installed and it seems to be working fine I can push/pull images to/from Harbor without any issues.
 
Part of the lab is showing a simple application and a ingress controller, we use  the standard  kuard application which is in harbor. I can push/pull the kuard image from the Ubuntu VM. However, when I deploy a yaml file which attempts to pull the image from harbor I see that the pod create fails, err image pull. When I look at the deployment I see a X509 error that the certificate is signed by a unknown authority.
 
Since I can pull the image fine using docker pull so I assume it’s a issue with a certificate I am missing someplace ?

**Comment by rgadeev** [comment]
mkdir -p /etc/docker/certs.d/{domain name harbor}
wget https://{domain name harbor}/api/v2.0/systeminfo/getcert --no-check-certificate -o /etc/docker/certs.d/{domain name harbor}/ca.crt

**Comment by geneliu** [comment]
Same error when I upgraded to 2.3.0. I suspect the ingress-route settings from my kubernetes.
