### ISSUE TITLE
from v1.10.3 after v2.3.0 upgrade no user and data

### ISSUE THREAD

**Issue by wyaopeng** [goharbor/harbor#15190]
upgrade  succed!but visit site!
![image](https://user-images.githubusercontent.com/12064306/123196410-72de5880-d4dc-11eb-9013-77de82ab6ced.png)

my site old  Auth Mode is ldap

I feel  the postgres is failed
 but it no error

then  i restart docker-compose
the DB always restarting!!
![image](https://user-images.githubusercontent.com/12064306/123196736-0d3e9c00-d4dd-11eb-9a3f-a6f8b732b626.png)

**Comment by yanji09** [comment]
It is not supported to upgrade from v1.10 to v2.3 which > 2 minor version.
Suggest upgrade path 1.10 -> 2.0 -> 2.2 -> 2.3.
Please always backup the DB before upgrading. in case of failure, you can easily restore the original DB.

**Comment by wy65701436** [comment]
please refer to the above notes for the upgrading path, and please also share the postgres.log of your env.

**Comment by wyaopeng** [comment]
In the same environment,  I use  v2.2  is succed
