### ISSUE TITLE
Goharbor - non docker image replication

### ISSUE THREAD

**Issue by ZeroGraviti** [goharbor/harbor#15208]
Can goharbor (2.x) be used to replicate builds/packages/artifacts from/to jfrog artifactory ? The replication setup for a jfrog artifactory endpoint assumes the existence of -
- Name
- Tag
- Label
- Resource : **Image**
AFAIK, for non-docker images, there is no convention for docker-style tagging as required above.

When I run the replication, it shows success but no artifacts are replicated. I have setup the replication endpoint as type "JFrog Artifactory" and not "Docker Registry". When I test the endpoint the logs _always_ shows `native` adapter being used. Shouldn't the `jfrog` adapter be used instead ? 

In JFrog Artifactory, I have non-docker images e.g., tarballs (gpg tar.gz), OVA, QCow2 images etc which I want to be replicated into goharbor. 

Is this possible ? 

Please guide me.

**Comment by steven-zou** [comment]
@ZeroGraviti 

Unfortunately, Harbor does not support replicating non-docker images from jfrog. Harbor is focusing on building an OCI compatible registry and then only supports storing and managing OCI artifacts. The other regular package formats like tgz, npm, python wheel can not be convered.

**Comment by steven-zou** [comment]
If you're ok, I'll close this issue later.
