### ISSUE TITLE
Switch from Postgres driver from lib/pq to pgx

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#15209]
There are quite a few problems and limitations with the current Postgres driver lib/pq.

Furthermore, lib/pq maintainer recommend switching to pgx  
>lib/pq is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using [pgx](https://github.com/jackc/pgx) which is actively maintained.

fixes  #13782
fixes #14856 
fixes #14943

**Comment by heww** [comment]
We will try to test the pgx when https://github.com/golang-migrate/migrate releases the version which supports the pgx.

**Comment by Vad1mo** [comment]
Migrate does already support PGX (https://github.com/golang-migrate/migrate/tree/master/database/pgx) or is there something missing?

**Comment by heww** [comment]
Yes, it supports pgx in the master branch, we will wait for it to publish a release.

**Comment by Vad1mo** [comment]
thank you, didn't notice that detail :)

**Comment by phin1x** [comment]
@heww golang-migrate now supports pgx with the latest 4.15.x release. is there something missing now to switch to pgx?
