### ISSUE TITLE
Support user name and project name Exact match in Harbor users and projects apis.

### ISSUE THREAD

**Issue by yunkunrao** [goharbor/harbor#15207]
**Is your feature request related to a problem? Please describe.**
Currently Harbor project list api(/api/v2.0/projects) and user list api(/api/v2.0/users) only support fuzzy match search. But in some scenario, we want to do the exact match search. But current apis didn't support it. Image we have hundreds of accounts. There is an account named Alex, other named Alexis. We want to filter out Alexis and get only Alex user info instead of both of them.

**Describe the solution you'd like**
Project list api(/api/v2.0/projects) and user list api(/api/v2.0/users) support exact match.

**Describe the main design/architecture of your solution**
The solution is straightforward, for example, add an exact match flag in query parameter, and default value is false to be compatible with current UI search behavior.

**Comment by heww** [comment]
From harbor v2.3, the list projects and list users APIs support `q` to filter the resources.

```
The `q` is a query string to query resources. 
Supported query patterns are "exact match(k=v)", "fuzzy match(k=~v)", "range(k=[min~max])", "list with union releationship(k={v1 v2 v3})" and "list with intersetion relationship(k=(v1 v2 v3))". 
The value of range and list can be string(enclosed by " or '), integer or time(in format "2020-04-09 02:36:00"). 
All of these query patterns should be put in the query string "q=xxx" and splitted by ",". e.g. q=k1=v1,k2=~v2,k3=[min~max]
```

So query the projects or users by exact match using the like the following

```
curl -u admin:Harbor12345 https://demo.goharbor.io/api/v2.0/projects?q=name%3Dfoo
curl -u admin:Harbor12345 https://demo.goharbor.io/api/v2.0/users?q=username%3Dfoo
```
