### ISSUE TITLE
Storage used displayed in Bytes, and not in GiB/TiB

### ISSUE THREAD

**Issue by fayak** [goharbor/harbor#15200]
Hi !

I'm running the latest version of harbor, and I have a repository with more than a TiB of data.

This size displayed on the top right corner is displayed in Bytes, even if the value is `1372900780740Byte`. I feel like it'd be better to have it in GiB/TiB. Because of the length, it's not fully displayed, and causes horizontal scrolling.

![bytes](https://user-images.githubusercontent.com/11300056/123394597-974f3900-d59f-11eb-94ae-21aaf9c48e14.jpg)

Let me know if you need more information about this

**Comment by sixeIa** [comment]
It's caused by https://github.com/goharbor/harbor/blob/1896df2cfb285de6d376d1d9c549d1d69f2bd2d7/src/portal/src/app/shared/units/utils.ts#L586 (and so on for getSizeUnit and formatSize) not handling terrabytes.

**Comment by fayak** [comment]
I'm not familiar with typescript, but I can try making a PR if you'd like

**Comment by sixeIa** [comment]
I'll do it.

**Comment by AllForNothing** [comment]
PR to 2.3 branch:  #15222
