### ISSUE TITLE
Allow to configure LDAPS certificates

### ISSUE THREAD

**Issue by rayburgemeestre** [goharbor/harbor#15216]
**Expected behavior and actual behavior:**

This issue is basically a two-in-one issue.

**Expected 1: Configure own self-signed CA for LDAPS for Harbor, so we can enable the checkbox `LDAP Verify Certificate`.**

**Expected 2: LDAPS can be used with custom client certificates**

**Steps to reproduce problem 1**

* Go through the painful process of configuring LDAPS.
* Make sure that when hitting the "TEST LDAP SERVER" button yields: `Connection to LDAP server is verified.`
* Then enable the "LDAP Verify Certificate" checkbox.
* Hit "TEST LDAP SERVER" button again. It should fail now.
* Now copy the CA to harbors config directory `cp -prv /path/to/my/ca.pem /path/to/harbor/common/config/shared/trust-certificates/` Make sure the permissions are set appropriately (chown 10000:10000, chmod +x)
* Restart Harbor.
* Hit "TEST LDAP SERVER" button again.

Actual behavior: `Failed to verify LDAP server with error: internal server error.`

Expected behavior: `Connection to LDAP server is verified.`.

**Debugging problem 1**

Before Harbor is restarted, the following containerized call is executed to "prepare" harbor:

https://github.com/goharbor/harbor/blob/master/make/prepare#L60

Which deletes all files in the config directory recursively (including the CA we copied to `config/shared/trust-certificates`).

https://github.com/goharbor/harbor/blob/e714a8eacc5edce218ca96e6a458413f71badf0c/make/photon/prepare/commands/prepare.py#L36

This produces the following output in the log file:

`Jun 28 12:26:01 node001 bash[23709]: Clearing the configuration file: /config/shared/trust-certificates/ca.pem`

The file gets deleted before the `install_cert.sh` script gets the chance to add it to the system.

**Workaround for problem 1**

Modifying the prepare script is an option (copying the CA after the prepare step purges the CA).

A possibly better solution that requires no code-change is to modify `docker-compose.override.yml` and add the following extra bind mount:

```
[root@node001 ~]# cat /path/to/harbor/docker-compose.override.yml 
---
version: '2.3'  # this should match the main docker-compose file generated by the prepare script
networks:
  harbor:
    external: True
  core:
    volumes:
      - type: bind
        source: /path/to/ca.pem
        target: /etc/harbor/ssl/ldap/ca.crt
```

The `install_cert.sh` script also looks for files named `ca.crt` in `/etc/harbor/ssl/*/`. For this reason this solution also works.

With the beforementioned mount, and restart of Harbor, the TEST LDAP SERVER button will result in:

`Connection to LDAP server is verified.`.

**Proposed solution for problem 1**

In my opinion it would be nicer if we can simply copy the additional CA in the `trust-certificates` directory instead. This will require fewer changes to the yaml.

**Steps to reproduce problem 2**

Please note that this problem exists even when problem 1 is solved (with the proposed workaround mentioned above for example).

Whether this occurs might depend on the strictness of the LDAPS server configuration in question. For example with openldap/slapd, we set the following option in `slapd.conf`:

`TLSVerifyClient demand`

Some background on this flag:

```This directive specifies what checks to perform on client certificates in an incoming TLS session, if any. This option is set to never by default, in which case the server never asks the client for a certificate. With a setting of allow the server will ask for a client certificate; if none is provided the session proceeds normally. If a certificate is provided but the server is unable to verify it, the certificate is ignored and the session proceeds normally, as if no certificate had been provided. With a setting of try the certificate is requested, and if none is provided, the session proceeds normally. If a certificate is provided and it cannot be verified, the session is immediately terminated. With a setting of demand the certificate is requested and a valid certificate must be provided, otherwise the session is immediately terminated.```

This means that additionally the server will demand a valid client certificate. These have to be signed by the (self-signed) CA that we just mentioned to install properly.
Unfortunately, I think this will require an extra configuration option, and some changes to the go code.

**Workaround / proposed solution for problem 2**

I managed to make those code changes in v2.1.1, this is an older version, but I see the code in master is still basically the same, just in a different file path (`src/pkg/ldap/ldap.go` instead of `src/common/utils/ldap/ldap.go` in 2.1.1).
This is the diff I made:

```
trigen@xps:~/projects/harbor[(HEAD detached at v2.1.1)]> git diff
diff --git a/src/common/utils/ldap/ldap.go b/src/common/utils/ldap/ldap.go
index ca0ade095..c5a460afc 100644
--- a/src/common/utils/ldap/ldap.go
+++ b/src/common/utils/ldap/ldap.go
@@ -260,7 +260,12 @@ func (session *Session) Open() error {
                session.ldapConn = ldap
        case "ldaps":
                log.Debug("Start to dial ldaps")
-               ldap, err := goldap.DialTLS("tcp", hostport, &tls.Config{ServerName: host, InsecureSkipVerify: !session.ldapConfig.LdapVerifyCert})
+               cert, err := tls.LoadX509KeyPair("/data/secret/ldap/ldap.pem", "/data/secret/ldap/ldap.key")
+               if err != nil {
+                       log.Fatal(err)
+               }
+
+               ldap, err := goldap.DialTLS("tcp", hostport, &tls.Config{ServerName: host, InsecureSkipVerify: !session.ldapConfig.LdapVerifyCert, Certificates: []tls.Certificate{cert}})
                if err != nil {
                        return err
                }
```

I had to patch `harbor_core` inside the `goharbor/harbor-core:v2.1.1` image with the above mentioned patch, and in my case I placed the client certificates here on the host:

```
[root@node001 harbor]# ls -al /var/lib/harbor/secret/ldap/
total 8
drwxr-xr-x 2 root  root    38 Jun 29 12:36 .
drwxr-xr-x 7 root  root    70 Jun 29 12:44 ..
-r--r----- 1 10000 10000 1704 Jun 28 11:29 ldap.key
-r--r----- 1 10000 10000 1115 Jun 28 11:29 ldap.pem
```

After restarting Harbor those certificates were used was I able to login with users from our LDAPS server.

**Versions:**

- harbor version: 2.1.1
- docker engine version: 19.03.15
- docker-compose version: 1.27.4

**Comment by rayburgemeestre** [comment]
Problem 1: has a decent solution, so less important I guess.

Problem 2: I'm happy to attempt drafting a Pull Request against master with the changes needed for supporting client certificates if nobody else has the time.

My diff was just a simple fix, we can change it by doing an "if file exists" check, or by extending `session.ldapConfig` maybe, with additional optional fields? (If you agree that this needs to be fixed)

**Comment by kbakk23** [comment]
Any updates for enabling ldaps for custom ca ?

**Comment by CallieNCI** [comment]
Issue for us too, I replicated the behaviour described, and was able to _fix_ it with some code based upon the above example.

```
version: '2.3'
services:
  core:
    volumes:
      - type: bind
        source: /home/ubuntu/harbor/certs/ca.crt
        target: /etc/harbor/ssl/ldap/ca.crt
```

**Comment by gstefanoff** [comment]
Any updates on this? Issue still exists, this should be reopened.
