### ISSUE TITLE
Supports proxy caching for more registries like Jfrog

### ISSUE THREAD

**Issue by rahulinux** [goharbor/harbor#15239]
As per the [document proxy cache only available](https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/) for Harbor and Docker hub registry, however when I configured Jfrog docker registry into Proxy cache and it works without any issue. 

To get it working, the only config difference is I used the Harbor provider and then provide [Jfrog](https://jfrog.com/artifactory/) docker-registry endpoints, creds. 

Is Harbor registry and Jfrog docker registry use the same implementation at the backend? 
Is this officially supported this way or it can stop working anytime? 
is it safe to use this kind of setting?

**Comment by rahulinux** [comment]
Update:

I did one more attempt with Jfrog as a docker registry provider(Harbor v2.3.0) and it's also working with proxy cache setup. 

Also, Jfrog has mentioned that "*Artifactory supports the relevant calls of the Docker Registry HTTP API*" 

> From Jfrog https://jfrog.com/integration/docker-registry/docker-repository/
> Full compatibility with Docker
> A binary repository in Artifactory can be designated as a Docker repository to contain Docker images. Artifactory supports all Docker functions for tagging the images its Docker repositories contain. You can create as many Docker repositories as you need in Artifactory, without limit.

> Artifactory supports the relevant calls of the Docker Registry HTTP API, so you can manage all your Docker images in Artifactory transparently with the Docker client. Just invoke Docker from the command line as you would any other Docker registry service to add images to a repository or pull images for distribution to a Docker engine.

So this seems a safe option to use however it would be helpful to have this information on the official Harbor doc that you can use any registry which supports Docker etc.

**Comment by Bledai** [comment]
Are there any undates here?

**Comment by OrlinVasilev** [comment]
@Bledai @rahulinux in 2.7 we have added jfrog https://github.com/goharbor/harbor/pull/17738 thanks to @erismaster  :))
