### ISSUE TITLE
scale registry replicas to 3 ，push image    have  error： blob unknown to registry

### ISSUE THREAD

**Issue by wangdwcsd** [goharbor/harbor#15234]
**When the number of registry copies is 3, 25 images will be pushed on a docker client at the same time, and about 5 images will be pushed to report an error each time.** 
The error content is: **bolt upload unknown**. 
In harbor web page, check that the image that has reported an error has not been transmitted

Registry found the following error log:
`time="2021-07-01T03:03:04.135074079Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:a726ec0c2712fa87ab085942057bb570f6dd4def88063d0a55d06930200f849c err.message="blob unknown to registry" go.version=go1.12.12 http.request.host="10.223.216.124:30612" http.request.id=b3a20af3-79f3-43de-8fd9-91abbbb5b8fa http.request.method=HEAD http.request.remoteaddr=5.243.166.0 http.request.uri="/v2/ctd/8-test-file/blobs/sha256:a726ec0c2712fa87ab085942057bb570f6dd4def88063d0a55d06930200f849c" http.request.useragent="docker/19.03.0 go/go1.12.5 git-commit/aeac9490dc kernel/3.10.0-1062.12.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.0 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=27.819612ms http.response.status=404 http.response.written=157 vars.digest="sha256:a726ec0c2712fa87ab085942057bb570f6dd4def88063d0a55d06930200f849c" vars.name="ctd/8-test-file"`

**When the number of registry copies is 1, 25 images are pushed on a docker client at the same time. All 25 images are successfully pushed and no error will be reported**

The back-end storage used by registry is: glusterfs

**Comment by zap23** [comment]
We're facing the exact same issue, one out of five `docker push` attempts are going through. What kind of informations, logs, etc. do you need for evaluation?

**Comment by wy65701436** [comment]
@zap23 it's helpful if you can provide harbor version & settings, core/registry log, and the steps for reproduce?

**Comment by yuluxs007** [comment]
```I have the same problem， harbor v2.2.0
./jobservice.log:36435:Jan 19 03:11:15 172.17.0.1 jobservice[1337]: 2022-01-19T03:11:15Z [ERROR] [/replication/transfer/image/transfer.go:357]: failed to push manifest of artifact buildpack-build/832c04a069c7cda9bcd499d2855f6d05-59b248f928c1490026717c00f9e9519175e8aad0:latest: http status code: 404, body: {"errors":[{"code":"NOT_FOUND","message":"http status code: 404, body: {\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"manifest unknown\",\"detail\":{\"Name\":\"buildpack-build/832c04a069c7cda9bcd499d2855f6d05-59b248f928c1490026717c00f9e9519175e8aad0\",\"Revision\":\"sha256:90ec0e2ca6bff4601f859e42a85d5c5a98cf17db0d3df85755f73b7008fd5e47\"}}]}\n"}]}
./jobservice.log:36436:Jan 19 03:11:15 172.17.0.1 jobservice[1337]: 2022-01-19T03:11:15Z [ERROR] [/replication/transfer/image/transfer.go:176]: http status code: 404, body: {"errors":[{"code":"NOT_FOUND","message":"http status code: 404, body: {\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"manifest unknown\",\"detail\":{\"Name\":\"buildpack-build/832c04a069c7cda9bcd499d2855f6d05-59b248f928c1490026717c00f9e9519175e8aad0\",\"Revision\":\"sha256:90ec0e2ca6bff4601f859e42a85d5c5a98cf17db0d3df85755f73b7008fd5e47\"}}]}\n"}]}
