### ISSUE TITLE
refreshing oidc access token breaks users subiss in database

### ISSUE THREAD

**Issue by kschu91** [goharbor/harbor#15241]
Refreshing an access token, will lead to an empty `subiss` field in the database. Which then forces harbor to recreate a user that already exists.

**Expected behavior and actual behavior:**
Actual:
Refreshing an access token, will lead to an empty `subiss` field in the database. Which then forces harbor to recreate a user that already exists.

Expected:
Refreshing an access token should not empty  `subiss` field in database.

**Steps to reproduce the problem:**
- login to harbor via OIDC
- wait until access token expires
- visit harbor again, so that harbor is forced to refresh the token

**Versions:**
- harbor version: v2.3.0-047b122c

**Additional context:**
The following line updates the oidc_user table in the database:
https://github.com/goharbor/harbor/blob/29ccdff766541aadc0d4eeae6e18676a955ccc23/src/pkg/oidc/secret.go#L115

But when we have a look at how the `oidcUser` object is fetched from the database:
https://github.com/goharbor/harbor/blob/29ccdff766541aadc0d4eeae6e18676a955ccc23/src/pkg/oidc/dao/meta.go#L46

We can see that the `subiss` field is not part of the selected fields and therefore is empty.

I am providng a pull request soon.

**Comment by reasonerjt** [comment]
@kschu91 
This indeed looks like a bug introduced by the refactory.  Unfortunately not caught by the pipelines.
Thanks a lot for the issue and PR.

I'll do verification and merge/cherrypick your fix.  
We'll also open another issue to make sure a test case is added.

**Comment by reasonerjt** [comment]
Thanks @kschu91 , for consistency I also write up a PR to try to restore the empty subiss and make sure only `token` column is updated when token refresh happens
