### ISSUE TITLE
Preheat histroy page back

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#15256]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/31262637/124374117-2f999c00-dccb-11eb-9356-d5bee49c6368.png">
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/31262637/124374139-51931e80-dccb-11eb-9f93-dd9ab1a47558.png">
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/31262637/124374157-7b4c4580-dccb-11eb-880b-70de21b26888.png">

Select into running preheat executions,  and back previous page,  got empty page.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
https://user-images.githubusercontent.com/31262637/124374170-915a0600-dccb-11eb-8267-98214de97bc1.mov

**Comment by AllForNothing** [comment]
@chlins The root cause is the same with #14991,  the p2p tasks API should return standard  date time

**Comment by AllForNothing** [comment]
@chlins And highly recommend using Chrome to visit Harbor UI
