### ISSUE TITLE
UI changes related to cleanup the unused LDAP/AD/OIDC user

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#15250]
PR: https://github.com/goharbor/harbor/pull/15247 is going to enable deleting user when auth_mode is not db_auth, please enable the Delete menu

**Comment by obeyler** [comment]
please reopen it, it doesn't work on harbor 2.3.1
![image](https://user-images.githubusercontent.com/23224162/130650389-13a12b05-0124-4dba-abd1-e67720f786b0.png)

**Comment by AllForNothing** [comment]
@obeyler We fixed it on the master branch(version 2.4.0), so the issue still exists in the previous versions
