### ISSUE TITLE
405 when trying to POST request a new project

### ISSUE THREAD

**Issue by maja5627** [goharbor/harbor#15254]
I am getting a 405 error on our harbor web page when trying to test a POST request to our harbor web page and create a new project. I am using harbor V2.0 and any GET requests send back correct info only POST requests get 405. I have added the CSRF token to the header and double checked that the JSON project is valid, any help or recommendations would be great, thank you. 
<img width="1064" alt="Screen Shot 2021-07-02 at 9 24 30 AM" src="https://user-images.githubusercontent.com/43732109/124296891-b279f580-db17-11eb-9e2e-bbaa41e92622.png">

**Comment by maja5627** [comment]
and I get a       "code": "FORBIDDEN",
      "message": "CSRF token invalid"
when trying to test it with the Swagger api

**Comment by stonezdj** [comment]
The request url is wrong.
```
{{BASE_URL}}/projects
```
It should be
```
{{BASE_URL}}/api/v2.0/projects

The sid and _gorilla_csrf should be removed from the cookie if you are using postman

**Comment by maja5627** [comment]
When I delete all cookies and try with that url I get 
<img width="1060" alt="Screen Shot 2021-07-05 at 9 51 01 AM" src="https://user-images.githubusercontent.com/43732109/124496372-932cd380-dd76-11eb-8620-d23e6d656418.png">

I found a curl command that does execute a post to create a new project 
      curl -u "admin:ADMIN_PASSWORD" -X POST -H "Content-Type: application/json" "https://harbor.harpooncorp.com/api/v2.0/projects" -d \
          "{
          \"project_name\": \"mat-testing\",         
          \"public\": true
          }"
but when trying to convert it to an angular post command I get this CORS error 
<img width="1440" alt="Screen Shot 2021-07-03 at 5 12 11 PM" src="https://user-images.githubusercontent.com/43732109/124496667-f6b70100-dd76-11eb-8563-0cf88cfc4403.png">
