### ISSUE TITLE
Signed tags can't be removed even as the admin user

### ISSUE THREAD

**Issue by jk** [goharbor/harbor#15266]
I'm new to signing container images, docker notary and the whole docker trust system. I've somehow managed to sign an off-the-shelve alpine docker image and pushed it to my private evaulation harbor instance. But now I wanted to remove the signed image and realized that I'm not able to do this, because I can't remove that last tag of a signed image. When I try to remove it, I'll see an error message: »the tag latest with signature cannot be deleted« even as the admin user.

So I tried and failed:

```
# export DOCKER_CONTENT_TRUST=1
# docker login registry-test.mydomain.tld
Authenticating with existing credentials...
Login Succeeded

# docker trust registry-test.mydomain.tld/library/signed:latest
could not remove signature for registry-test.mydomain.tld/library/signed:latest: you are not authorized to perform this operation: server returned 401.
```

*I'm not entirely clear, why I'm seeing a 401 here, since the login went succesful*

Is there documentation covering it, that I'm missing here?

**Comment by robbrucks** [comment]
I am having the same problem.

**Comment by wy65701436** [comment]
you need to use the notary client to remove the signaure firstly, and then to remove the tag from Harbor.
