### ISSUE TITLE
Harbor API login thru OIDC always return 401

### ISSUE THREAD

**Issue by honghan94** [goharbor/harbor#15269]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The account should login successfully.

**Steps to reproduce the problem:**
Login using API thru OIDC will fail, no matter what account type.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.0]
- docker engine version: [19.3.13]
- Run in kubernetes 1.19.6 (EKS)

**Additional context:**
We configure our Harbor thru kubernetes, connected to external Postgres and Keycloak.
When I tried to login thru API, it will throw this error.
`2021-07-06T03:00:21Z [WARNING] [/server/middleware/security/idtoken.go:53][requestID="889c1f31-f4a3-45e4-a6b1-825cdaa4821a"]: failed to get user based on token claims: can't find security context`
The error seems like coming from here.
https://github.com/goharbor/harbor/blob/master/src/controller/user/controller.go#L142
But I have no idea why the user is unable to get the permission context.

The account is able to login fine thru Web GUI and Docker CLI, but not thru API with OIDC.
The API code is as below
```python
  rq_headers = {
      "accept": "application/json",
      'Authorization': f"Bearer {token}"
  }
  rq_repo = requests.get(harbor_url + '/api/v2.0/projects/' + harbor_project +
                         '/repositories?page_size=100',
                         headers=rq_headers)
```
The login will always throw 401 unauthorized even with authorization header attached.

**Comment by reasonerjt** [comment]
@honghan94 Please provide more context in the log and your code, is the `token` the `id_token`?
