### ISSUE TITLE
Change robot account secret through API

### ISSUE THREAD

**Issue by niltongouveajr** [goharbor/harbor#15268]
Hello!

Is it possible to set a robot account's secret through the API? I couldn't do this either at the time of account creation or change it after creation.

`curl -s -k -X POST "${HARBOR_API_URL}/robots" -H "accept: application/json" -H "authorization: Basic ${HARBOR_API_TOKEN}" -H "Content-Type: application/json" -d "{ \"name\": \"${HARBOR_ROBOT_USER}\", \"secret\": \"${HARBOR_ROBOT_SECRET}\", \"disable\": false, \"level\": \"system\", \"duration\": -1, \"permissions\": [ { \"access\": [ { \"action\": \"create\", \"resource\": \"scan\" }, { \"action\": \"push\", \"resource\": \"repository\" }, { \"action\": \"pull\", \"resource\": \"repository\" }, { \"action\": \"delete\", \"resource\": \"artifact\" }, { \"action\": \"read\", \"resource\": \"helm-chart\" }, { \"action\": \"create\", \"resource\": \"helm-chart-version\" }, { \"action\": \"delete\", \"resource\": \"helm-chart-version\" }, { \"action\": \"create\", \"resource\": \"tag\" }, { \"action\": \"delete\", \"resource\": \"tag\" }, { \"action\": \"create\",  \"resource\": \"artifact-label\" } ], \"kind\": \"project\", \"namespace\": \"${HARBOR_ROBOT_PROJECT}\" } ]}"`

`curl -s -k -X PUT "${HARBOR_API_URL}/robots/${HARBOR_ROBOT_ID}" -H "accept: application/json" -H "authorization: Basic ${HARBOR_API_TOKEN}" -H "Content-Type: application/json" -d "{ \"secret\": \"${HARBOR_ROBOT_SECRET}\" }"`

I thought about trying to change the secret directly in the database but I believe this is not the best way. 

Best regards,
Nilton

**Comment by wy65701436** [comment]
The API doesn't support create robot with specific secret, but you can refersh it after created, just try:

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/2841473/124587302-0ecb7500-de8a-11eb-9ef2-eff6cef1f414.png">

Anything about Harbor API, you can find it at devcenter, click the button(Harbor API v2.0) on the lower left

**Comment by niltongouveajr** [comment]
Thank you very much @wy65701436.

**Comment by ussu** [comment]
Hi @wy65701436, according to the swagger.yaml (https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml),
the `POST /robots` route uses the `RobotCreate` schema, which includes the `secret` parameter (https://github.com/goharbor/harbor/blob/8fb76689abdaf2d61772e27063593c70dca53400/api/v2.0/swagger.yaml#L6831)
i'm quite new to Harbor and i'm trying to get to know it better, do you know whether creating robot with specific secret is not "currently" supported or is it not planned at all?
Thank you very much,
Sulidi

**Comment by wy65701436** [comment]
The api doesn't support create robot with specific secret and is not in the plan as well. You can refresh the secret with `PATCH` endpoint.

**Comment by ussu** [comment]
thanks for the reply :)
