### ISSUE TITLE
harbor-core cannot  connect postgresql

### ISSUE THREAD

**Issue by molu-guwang** [goharbor/harbor#15272]
the harbor version is v1.10.8

I'm install a harbor1.10.8 in a vitual mechine,and it works well.
but I had restart the harbor mechine. container harbor-core and harbor-jobservice was always restart.the core log as :[ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.22.0.3:5432: i/o timeout

but harbor-db is running and i even can sign in the pgsql in harbor-db use command line : psql -U postgres -h 172.22.0.3 -p 5432 postgres

I swear the configuration has not changed。

where is the problem ?what should I do ?
![image](https://user-images.githubusercontent.com/69225004/124557417-111ed680-de6c-11eb-98d5-d292959cb349.png)

![image](https://user-images.githubusercontent.com/69225004/124557609-475c5600-de6c-11eb-8533-b74cf18a7fc2.png)

**Comment by ninjadq** [comment]
`v1.10.8` is not supported by community, please upgrade to newer version

**Comment by molu-guwang** [comment]
> `v1.10.8` is not supported by community, please upgrade to newer version

Actually,the original version is v2.1.0 .because it had that problem,so I upgrade the harbor to v1.10.8.Unfortunately ,it could't  connect postgresql too

**Comment by molu-guwang** [comment]
> `v1.10.8` is not supported by community, please upgrade to newer version

and I copy the dir databases ,harbor.yaml   to a new mechine,the postgresql could't run too.the log as picture
![image](https://user-images.githubusercontent.com/69225004/125256300-e8488680-e32e-11eb-8a78-8f123e3a0376.png)
I had chmod the dir and mod the harbor.yaml.
