### ISSUE TITLE
Handle Carvel packages

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#15277]
Per discussion with @heww the pkg made by Carvel toolkit (https://github.com/vmware-tanzu/carvel-imgpkg) is just plain docker image and don't contain extra metadata.

IMO it's a matter of time that Carvel packages will contain more informations.  We should monitor the change in Carvel packaging workflow to make sure the information can be handled by Harbor.

**Comment by stonezdj** [comment]
Refer to [the air gap workflow](https://carvel.dev/imgpkg/docs/v0.24.0/air-gapped-workflow/), with this workflow, uses have to run command line to imgpkg bundle from projects.registry.vmware.com to their private Harbor instance. Is it possible to do it by replication?
