### ISSUE TITLE
Don`t have Deploy/templates/registry/config.yml before 

### ISSUE THREAD

**Issue by patsevanton** [goharbor/harbor#15279]
Hello! Thanks for harbor!

I try use registry mirror in harbor.
After unpack archive harbor, i see only this files.
```
common.sh  harbor.v2.2.3.tar.gz  harbor.yml  install.sh  LICENSE  prepare 
```
After ./prepare i see file registry/config.yml
```
ls harbor/common/config/registry/config.yml
```

**Comment by phin1x** [comment]
the common directory contains the configs which are generated from your harbor.yml file.

if you install harbor, you should do this via the install.sh script. this script executes prepare for generating the configs, loads the image and starts harbor via docker-compose.

**Comment by ninjadq** [comment]
thanks @phin1x
