### ISSUE TITLE
LDAP login timeout after upgrading to v2.2.1

### ISSUE THREAD

**Issue by massimo-coletti** [goharbor/harbor#15278]
**Expected behavior**
docker login with LDAP user works successfully

**Actual behavior:**
Getting following error:
root@dockerclient ~]# docker login myharbor.example.com
Username: example_user
Password:
Error response from daemon: Get https://myharbor.example.com/v2/: Get https://myharbor.example.com/service/token?account=example_user&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded

**Notes**
This problem started immediately after upgrading from version 1.10 to 2.2.1. The upgrade was done in-place and we are running on the same server. This is the *only* change we did in the environment. All other environment details remain the same as the working version (same server, same docker version, OS version, LDAP configuration, user definitions, etc...)

**Versions:**
- harbor version: v2.2.1
- docker engine version: 20.10.7
- docker-compose version: 1.29.2

Please help us troubleshoot this issue. What log files should we review? What settings should we modify? Is it a bug in Harbor v2.2?

Thank you

**Comment by stonezdj** [comment]
Maybe duplicate to https://github.com/goharbor/harbor/issues/13718

**Comment by massimo-coletti** [comment]
Hi stonezdj,

Thanks for looking into this. We checked the workarounds described in #13718, but they did not mitigate the problem.
Meanwhile we managed to narrow down the scope of the issue:

When using a domain controller in the same data center, login is successful. For example, when both Harbor server and domain controller are in Austin.
 
However when specifying a remote domain controller (e.g. Harbor server in Austin, domain controller in Amsterdam), docker login fails. 

Please note: both scenarios above work perfectly in Harbor version 1.10. As soon as we switch to Harbor version 2.2 (without changing anything else!) the second scenario fails.

Could you guide us how to debug the issue? Which logs to check? Any other suggestion? This is delaying our upgrade.

Thanks

**Comment by stonezdj** [comment]
what is your ldap related config settings? try to remove all your LDAP group related settings and login again. it maybe timeout the login process if there are too many groups for the current user in the LDAP.

**Comment by massimo-coletti** [comment]
Thanks, that worked! We removed the LDAP group settings and now login is working fine.
Is it possible to increase the timeout period for this lookup?

**Comment by stonezdj** [comment]
The timeout should be set in the client, but it seems there is no such option in docker client.
