### ISSUE TITLE
[harbor-exporter] Error on secure DB connection

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#15275]
I am seeing an error on the harbor-exporting after upgrading from V2.2.0 to V2.3.0.

```
$~/ws/helm/releases/cci-container-infra$ kn staging logs -f harbor-staging-harbor-exporter-7bf898854b-nwqn8
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2021-07-06T08:26:26Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL harbordb.foo.bar port-6601 database-registry sslmode-"require"
2021-07-06T08:26:26Z [INFO] [/common/dao/base.go:70]: Register database completed
panic: bad redis url: not support scheme 

goroutine 1 [running]:
github.com/goharbor/harbor/src/pkg/exporter.InitBackendWorker(0xc0001efec0)
	/harbor/src/pkg/exporter/js_worker.go:42 +0x265
main.main()
	/harbor/src/cmd/exporter/main.go:50 +0x7c5

```

It seems that the ssl mode is replaced in the connection configuration with the **"**

**Steps to reproduce the problem:**
            database:
                type: external
                external:
                    [...]
                    sslmode: require

**Versions:**
- harbor-helm version: 1.7.0
- harbor version: 2.3.0

**Comment by chlins** [comment]
@dioguerra The panic cause is redis url invalid, not database, the db looks connected well from the log.

**Comment by dioguerra** [comment]
Not sure how this happened as the redis is provided by the helm-chart.
I will close this as a non-fix. Maybe if someone else finds the same problem they can comment below, and if needed we will follow up on this
