### ISSUE TITLE
Trivy failed do download DB error

### ISSUE THREAD

**Issue by khbrady** [goharbor/harbor#15284]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
I am working on the Hands On Lab for VMworld 2021 for Tanzu, installed Harbor as part of the lab. I'd like to show scanning a image with Trivy but can't get it to work
I installed Trivy as per the instructions in Harbor, run install-sh --with-trivy
Harbor in fact shows trivy and status is Green. I ASSUMED this means it's OK
I run a scan and in the log I see a error showing it failed to download the trivy database
I don't see anything in the Harbor docs that suggests that there is anything I need to change in the harbor.yml file
I did try to configure Harbor with trivy w/o downloading the database. I downloaded and unzipped the trivy database
Tried to install it (the instructions here could be clearer do I copy the files to the home/scanner/.cache/trivy/db
And BTW there was no metadata.json file extracted ...
If the flag is enabled you have to download the `trivy-offline.tar.gz` archive manually, extract `trivy.db` a
nd
  # `metadata.json` files and mount them in the `/home/scanner/.cache/trivy/db` path.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

<img width="1645" alt="Screen Shot 2021-07-07 at 4 58 28 PM" src="https://user-images.githubusercontent.com/13338366/124828690-975b1b80-df45-11eb-96a9-4695cb160638.png">

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
please refer this faq: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment

**Comment by khbrady** [comment]
Thanks but I am not sure this applies. I installed Docker according to the Tanzu 1.3 documentation so Trivy is installed as a Docker container. I downloaded the trivy database and added the location of the database to docre-commpose.yaml. However Trivy still gives me a error 
<img width="800" alt="Screen Shot 2021-07-12 at 8 25 14 AM" src="https://user-images.githubusercontent.com/13338366/125287336-c7f6d880-e2ea-11eb-8b79-85c2c04ee800.png">

**Comment by danielpacak** [comment]
@khbrady Is it air gapped environment? Or can you configure outbound connection to download Trivy DB file from internet? If your cluster has access to internet it looks to me like a DNS config issue when Docker Engine fails to resolve the api.github.com hostname.

**Comment by khbrady** [comment]
Hey Daniel – It’s kind of air gapped. This is being deployed for the VMware Hands On Labs 2021 , the labs won’t have internet access.

I followed the guides to download and install the Trivy DB but it’s not being recognized either because I have the docker-compose entry wrong or maybe something with Trivy

Yes it’s possible I need to add a DNS entry to docker-compose.yml or start harbor via docker-compose with a DNS flag

Thank you

[Graphical user interface, text, application  Description automatically generated]

From: Daniel Pacak ***@***.***>
Reply-To: goharbor/harbor ***@***.***>
Date: Monday, July 12, 2021 at 8:49 AM
To: goharbor/harbor ***@***.***>
Cc: Kevin Brady ***@***.***>, Mention ***@***.***>
Subject: Re: [goharbor/harbor] Trivy failed do download DB error (#15284)


@khbrady<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkhbrady&data=04%7C01%7Cbradyk%40vmware.com%7Ca9abb24c9f454502b18708d94533847d%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637616909837544225%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p4%2BfofzXWfRaNxXIFSvLe0Qd%2FhhX92D6FsUSvndRqAM%3D&reserved=0> Is it air gapped environment? Or can you configure outbound connection to download Trivy DB file from internet? If your cluster has access to internet it looks to me like a DNS config issue when Docker Engine fails to resolve the api.github.com hostname.

**Comment by danielpacak** [comment]
In air gapped environment its is essential to mount trivy.db and metadata.json at the right paths according to documentation and make sure that that 10000:10000 can read it. Also disable Trivy updates in harbor.yaml https://github.com/goharbor/harbor/blob/master/make/harbor.yml.tmpl#L74

**Comment by khbrady** [comment]
Thanks I did that
Question though
I logged into the docker container, trivy-adapter

There is a /home/scanner/.cache/trivy/db directory path and there is a trivy.db and metadata.json entry but… I expected they would be files but they are directories ?

The link below seems to suggest that there is a /home/scanner/.cache/trivy/db. Where you would place the database and yaml files
What I see is 2 subdirectories under the db directory ?

Thanks !!

From: Daniel Pacak ***@***.***>
Reply-To: goharbor/harbor ***@***.***>
Date: Monday, July 12, 2021 at 9:02 AM
To: goharbor/harbor ***@***.***>
Cc: Kevin Brady ***@***.***>, Mention ***@***.***>
Subject: Re: [goharbor/harbor] Trivy failed do download DB error (#15284)


In air gapped environment its is essential to mount trivy.db and metadata.json at the right paths according to documentation and make sure that that 10000:10000 can read it. Also disable Trivy updates in harbor.yaml https://github.com/goharbor/harbor/blob/master/make/harbor.yml.tmpl#L74<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoharbor%2Fharbor%2Fblob%2Fmaster%2Fmake%2Fharbor.yml.tmpl%23L74&data=04%7C01%7Cbradyk%40vmware.com%7C45896596a5ff46e2bc5f08d945355aee%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637616917733030833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lD%2FAmlKdAmXxaz6yVgzF%2F1vImAIKqr4RQQwOKZ1fUCo%3D&reserved=0>

**Comment by danielpacak** [comment]
In the container the expected paths are:

/home/scanner/.cache/trivy/db/metadata.json
/home/scanner/.cache/trivy/db/trivy.db

If it's not the case then I believe you must fix volume binds in your docker-compose.yml

**Comment by khbrady** [comment]
Thanks Daniel – Perhaps I have done something fundamentally wrong
I have Harbor installed as a docker container on a Ubuntu VM
I downloaded the trivy.db and installed trivy.db and metadata.json under a /home/scanner/.cache/trivy/db directory

I added the lines from the image below to docker-compose.yml, stop/start Harbor do I need a -type: bind before the lines below ?
I assumed I didn’t need s source and target but maybe I do ?

Thank you

***@***.***D776FF.A34B0620]


From: Daniel Pacak ***@***.***>
Reply-To: goharbor/harbor ***@***.***>
Date: Monday, July 12, 2021 at 9:19 AM
To: goharbor/harbor ***@***.***>
Cc: Kevin Brady ***@***.***>, Mention ***@***.***>
Subject: Re: [goharbor/harbor] Trivy failed do download DB error (#15284)


In the container the expected paths are:

/home/scanner/.cache/trivy/db/metadata.json
/home/scanner/.cache/trivy/db/trivy.db

If it's not the case then I believe you must fix volume binds in your docker-compose.yml
