### ISSUE TITLE
Harbor 2.3: LDAP config PUT operations are sending the wrong data type to core

### ISSUE THREAD

**Issue by mmiller1** [goharbor/harbor#15282]
After updating Harbor from v2.1 to 2.3.0, it has been observed that we can no longer modify the LDAP Scope values as inconsistent data types are being PUT back to the core service' API. resulting in this error:
```validation failure list: parsing configurations body from "" failed, because json: cannot unmarshal string into Go struct field Configurations.ldap_scope of type int64```

when setting both the group and user scopes to "Base" we see this payload being sent to /api/v2.0/configurations
```{"ldap_group_search_scope":0,"ldap_scope":"0"}```

if we duplicate the request, modifying the values to all be integers, the request is accepted and the configuration values are updated. It initially appears that the value for "ldap_group_search_scope" is only sent back as an integer when "Base" (0) is selected, but the "ldap_scope" value is always sent as a string(!?)

- harbor version: 2.3.0

**Comment by stonezdj** [comment]
Yes, the current configuration API adapted the new programming model, it verifies the datatype before sending to the API handler,  and failed with data type mismatch.
You should follow the swagger doc to refine your code.
https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L8075-L8084

**Comment by mmiller1** [comment]
I think this has been misunderstood, it is the portal UI that is sending the wrong data types, not code that I wrote.

**Comment by mmiller1** [comment]
Is there a mechanism to re-open this, or should I create a new issue?
