### ISSUE TITLE
[OIDC] get GC logs permissions error

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#15298]
As an admin (set on the local db) with OIDC configured, retrieving the GC logs fails with the message:
`{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}`

**Expected behavior and actual behavior:**
I expect to get the GC logs presented

**Steps to reproduce the problem:**
Go to: Administration -> Garbage Collection -> History and open one of the log files. The message is displayed

**Versions:**
- harbor version: 2.2.0 installed with harbor-helm

**Additional context:**
The GC job seems to run without problem:

logs from jobserver:

> 2021-07-09T09:27:40Z [INFO] [/jobservice/worker/cworker/c_worker.go:76]: Job incoming: {"name":"GARBAGE_COLLECTION","id":"1d131d52774687b5ba6cecf5","t":1625822859,"args":null}
> 2021-07-09T09:27:40Z [INFO] [/common/config/store/driver/rest.go:31]: get configuration from url: http://harbor-harbor-core:80/api/internal/configurations
> 2021-07-09T09:27:40Z [INFO] [/common/config/store/driver/rest.go:31]: get configuration from url: http://harbor-harbor-core:80/api/internal/configurations
> 2021-07-09T09:27:40Z [INFO] [/common/registryctl/client.go:41]: initializing client for registry http://harbor-harbor-registry:8080 ...
> 2021-07-09T09:27:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:144]: Garbage Collection parameters: [delete_untagged: false, dry_run: false, time_window: 2]
> 2021-07-09T09:27:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:154]: start to run gc in job.
> 2021-07-09T09:27:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:401]: artifact trash candidates.
> 2021-07-09T09:27:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:403]: ID-1 MediaType-application/vnd.docker.container.image.v1+json ManifestMediaType-application/vnd.docker.distribution.manifest.v2+json RepositoryName-docker.io/library/centos Digest-sha256:fc4a234b91cc4b542bac8a6ad23b2ddcee60ae68fc4dbd4a52efb5f1b0baad71 CreationTime-2020-10-20 02:00:01
> 2021-07-09T09:27:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:403]: ID-2 MediaType-application

Getting the logs shows in harbor-core:

> 2021-07-09T09:59:10Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator dtomasgu require read action for resource /system/garbage-collection
> 2021-07-09T09:59:10Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"{\"code\":10009,\"message\":\"failed to get the job log\",\"details\":\"error for getting log of job 1d131d52774687b5ba6cecf5: no log data getter is configured\"}"}]} 
> /harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
> /harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
> /harbor/src/server/v2.0/handler/base.go:214, github.com/goharbor/harbor/src/server/v2.0/handler.(*ErrResponder).WriteResponse
> /harbor/src/server/v2.0/restapi/operations/gc/get_gc_log.go:71, github.com/goharbor/harbor/src/server/v2.0/restapi/operations/gc.(*GetGCLog).ServeHTTP
> /harbor/src/server/v2.0/restapi/operations/harbor_api.go:1096, github.com/goharbor/harbor/src/server/v2.0/restapi/operations.(*HarborAPI).handler.func1
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/apiversion/api_version.go:28, github.com/goharbor/harbor/src/server/middleware/apiversion.Middleware.func1.1
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/router/router.go:90, github.com/goharbor/harbor/src/server/router.(*Route).Handler.func1
> /harbor/src/vendor/github.com/astaxie/beego/router.go:769, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
> /harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP
> /harbor/src/server/middleware/security/security.go:76, github.com/goharbor/harbor/src/server/middleware/security.UnauthorizedMiddleware.func1
> /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
> /usr/local/go/src/net/http/server.go:2042, net/http.HandlerFunc.ServeHTTP

**Comment by dioguerra** [comment]
This is duplicated here: https://github.com/goharbor/harbor/issues/14250
Not sure if using OIDC so i will leave it open.

**Comment by maxisam** [comment]
I have the same configuration with 2.3.0. Same error

**Comment by steven-zou** [comment]
Have changed configurations of jobservice?

There are three kinds of jobservice logger implementations. STD, FILE and DB. Only FILE and DB kind support log getter. For STD kind, no log getter implemented.

@dioguerra / @maxisam

**Comment by dioguerra** [comment]
Job logger is default:

>      jobservice:
>        jobLoggers:
>         - stdout

In my opinion, job runs that offer the possibility to get logs, if outputting to std should also log that specific section into DB, no?
This includes not only GC but also replications.

**Comment by steven-zou** [comment]
> Job logger is default:
> 
> > ```
> >  jobservice:
> >    jobLoggers:
> >     - stdout
> > ```
> 
> In my opinion, job runs that offer the possibility to get logs, if outputting to std should also log that specific section into DB, no?
> This includes not only GC but also replications.

Multiple loggers supported to be configured. You can config bothh STD and FILE logger.

**Comment by dioguerra** [comment]
This solves the issue indeed. Thank you

**Comment by dioguerra** [comment]
Should we create a ticket for better error report?
