### ISSUE TITLE
Log in to Harbor via OIDC, prompting that the user name and email address already exist

### ISSUE THREAD

**Issue by Shinji-IkariG** [goharbor/harbor#15294]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

Log in to Harbor via OIDC

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
Click to log in through OIDC, an error occurred during the verification process
Return to the error page
![image](https://user-images.githubusercontent.com/58841610/125015146-7f98aa00-e0a1-11eb-85d9-9be3c255e444.png)

 Only my account in the company has this problem, and everyone else can log in to Harbor through OIDC normally.
 
**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.0]
- docker engine version: [ 20.10.7]
- docker-compose version: [1.29.2]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by Shinji-IkariG** [comment]
The accounts that cannot be logged in are also created through oidc login. I have not created any local accounts on the harbor.

**Comment by reasonerjt** [comment]
@Shinji-IkariG could you check the data in table `oidc_user`?
It maybe a dup of https://github.com/goharbor/harbor/issues/15241

**Comment by Shinji-IkariG** [comment]
My user id is 3
![image](https://user-images.githubusercontent.com/58841610/125394230-f1436180-e3db-11eb-8cd9-353ab285ed65.png)

I used this command to query subiss from oidc_user
`select * from oidc_user;`
![image](https://user-images.githubusercontent.com/58841610/125394161-d4a72980-e3db-11eb-9ff5-5d7ce0ce7902.png)
It seems that the cause of the problem is different from #15241

**Comment by Shinji-IkariG** [comment]
Sorry, I made a mistake, the subiss field is empty. It seems that I have encountered the same problem.

**Comment by reasonerjt** [comment]
@Shinji-IkariG there is a patch that will restore the data in that column: 
https://github.com/goharbor/harbor/pull/15303
It will be released in v2.3.1 if you need urgent fix please refer to this PR.

I'm closing this issue as a dup to #15241
