### ISSUE TITLE
Inconsistent username claim behavior

### ISSUE THREAD

**Issue by kschu91** [goharbor/harbor#15290]
**Expected behavior and actual behavior:**
Harbor tries to fetch username and groups from the ID Token and from the USERINFO endpoint:
```go
func mergeUserInfo(remote, local *UserInfo) *UserInfo {
	res := &UserInfo{
		// data only contained in ID token
		Subject: local.Subject,
		Issuer:  local.Issuer,
		// Used data from userinfo
		Username: remote.Username,
		Email:    remote.Email,
	}
	if remote.hasGroupClaim {
		res.Groups = remote.Groups
		res.AdminGroupMember = remote.AdminGroupMember
		res.hasGroupClaim = true
	} else if local.hasGroupClaim {
		res.Groups = local.Groups
		res.AdminGroupMember = local.AdminGroupMember
		res.hasGroupClaim = true
	} else {
		res.Groups = []string{}
	}
	return res
}
```
It assumes that the Username is always fetchted from the remote.

Now consider the following use case:
An IDP that has claims for username and groups in the token. Eg. `cognito:username` and `cognito:groups`.
But in the userinfo endpoint of the IDP the username field is just named `username` and groups does not exist at all in the remote.

In the OIDC settings of harbor I am now forced to specify the `user_claim` as `username`, even though the actual claim is `cognito:username`.
This leads to misunderstanding of the setting, as it is not clear that the settings value is not the actual claim in the token instead it is the field in the userinfo endpoint. When adding the actual claim value `cognito:username`, onboarding of a user fails with:
```
Failed to recover Username from claim. Claim 'cognito:username' is invalid or not a string
```

Expected:
Fetch username **and** groups from the remote first. If not available in the remote, fall back to information in the token.

**Steps to reproduce the problem:**
- setup harbor oidc with aws cognito idp
- `cognito:username` as user claim
- `cognito:groups` as groups claim

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.3.0-047b122c

**Comment by reasonerjt** [comment]
@kschu91 Thanks for point out this issue.
It seems the root cause is that the code assumes the claims in ID token and userinfo are the same.
I don't have a cognito env available, could you show me the response when you call the `/userinfo` endpoint?

**Comment by acobaugh** [comment]
I think this is happening with Azure OIDC, too. The claims returned by the `userinfo` endpoint are very limited (sub,name,family_name,given_name,picture,email), and so not only are we unable to use something like `preferred_username` for username, groups don't seem to be coming through either for the user (yet are still being populated in the UI under the Groups tab).

**Comment by kschu91** [comment]
> @kschu91 Thanks for point out this issue.
> It seems the root cause is that the code assumes the claims in ID token and userinfo are the same.
> I don't have a cognito env available, could you show me the response when you call the `/userinfo` endpoint?

Sure, here is the response from the userinfo endpoint:
```json
{
  "sub": "auniquesub",
  "identities": "...",
  "email_verified": "true",
  "email": "kevin.schu@aoe.com",
  "username": "kevin.schu"
}
```

vs. ID Token:
```json
{
  "at_hash": "wcIq...",
  "sub": "auniquesub",
  "cognito:groups": [
    "Group1",
    "Group2",
    "Group3"
  ],
  "email_verified": true,
  "iss": "https://cognito-idp.eu-central-1.amazonaws.com/xxx",
  "cognito:username": "kevin.schu",
  "nonce": "je9Dm...",
  "origin_jti": "b47e53cc...",
  "aud": "4joo6...",
  "token_use": "id",
  "auth_time": 1626077324,
  "exp": 1626080924,
  "iat": 1626077324,
  "jti": "94a20915...",
  "email": "kevin.schu@aoe.com"
}
```
