### ISSUE TITLE
Trivy not recognizing trivy.db and metadata.json files when using skip update=true

### ISSUE THREAD

**Issue by khbrady** [goharbor/harbor#15307]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I expected Trivy to use the downloaded database, instead it gives me a error saying I can't use skip update = true
I have installed Harbor as a docker container as per the guidelines in the Tanzu Kubernetes Grid 1.3 documentation.
I downloaded the database and he metadata file, placed them in /home/scanner/.cache/trivy/db validated that the files and driectory are readable and then added the path to the file in the docker compose yaml file. I expected that this would work but it's not.

<img width="800" alt="Screen Shot 2021-07-12 at 8 25 14 AM" src="https://user-images.githubusercontent.com/13338366/125287977-9a5e5f00-e2eb-11eb-9973-e8389ded1735.png">

A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
hi please ref the [faq](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment)
