### ISSUE TITLE
An error occurred in Get schedule 

### ISSUE THREAD

**Issue by yyt6200** [goharbor/harbor#15304]
harbor version: [2.1.5]
docker engine version: [20.10.6]
docker-compose version: [1.22.0]

![image](https://user-images.githubusercontent.com/44914868/125226523-d7cee680-e303-11eb-8678-aee0efa0ea0b.png)

**Comment by ninjadq** [comment]
could you provide the logs here?

**Comment by yyt6200** [comment]
@ninjadq 
Thank you for your reply。
I can't find any useful logs from the containers below. Can you tell me where to look at the logs?
![image](https://user-images.githubusercontent.com/44914868/125380262-833f7000-e3c4-11eb-9a1e-011f343c1ed9.png)
