### ISSUE TITLE
Harbor core - login issues when running multiple replicas

### ISSUE THREAD

**Issue by jess-belliveau** [goharbor/harbor#15313]
Hello,

I'm running Harbor on Kubernetes:
`[INFO] [/core/main.go:221]: Version: v2.1.5, Git commit: 919c9fd2`

If I run the "core" pod with 1 replica, I can use the UI fine and browse as normal. Due to our high usage of Harbor, we have run the old version "Version v1.10.6-490042d8" with 5 replicas of the core pod. If I scale up my test deployment to 5 replicas I can no longer auth passed the initial portal login page.

I've watched the logs of both the core and portal pods, but no errors are thrown - the login page just doesn't redirect me and the login button remains greyed out until I refresh the page.

I've confirmed I've set CSRF_KEY correctly and the "Invalid CSRF key from environment" error is not being thrown by the core container.

What other areas/logs should I be looking at to help chase down why Harbor doesn't function with multiple core replicas?

**Comment by ninjadq** [comment]
are you run harbor with a mixed version? I saw you log is `v2.1.5` but also run `Version v1.10.6-490042d8` version

**Comment by jess-belliveau** [comment]
Hi @ninjadq , not running mixed version. I was just explaining with `Version v1.10.6-490042d8` we currently run 5 core pod replicas - but in our testing with `v2.1.5` its not working. My current theory is the problem is with the session state storage. Do you know if this is offloaded to redis and if I can enable any debug logs on the core pod to show additional logging?

**Comment by jess-belliveau** [comment]
I've captured some logs here;
https://gist.github.com/jess-belliveau/593d11ad983735b5fb5ab18853fa745a
though nothing stands out to me as an obvious problem :(

I've also tried to capture some activity in the browser - from the screenshots attached, you can see the initial auth request works and returns a 200 OK, then when I am redirected to the next page "current" it returns a 401 error and I remain on the main login page with a grey button. To re-activate the button, I need to reload the page.

![login](https://user-images.githubusercontent.com/434752/126252854-438f5917-7369-4ef2-9351-2042b36037d4.png)
![current](https://user-images.githubusercontent.com/434752/126252868-7f84a323-8c73-483c-8cac-41c79e691172.png)

**Comment by jess-belliveau** [comment]
I figured this out - well, a colleague helped me work through the problem.

Along the line of my upgrade work, I had dropped setting some REDIS settings for the core pods - hence session state was not being shared.
