### ISSUE TITLE
Digest of image pushed to Harbor is different from replicated image

### ISSUE THREAD

**Issue by pavellajczyk** [goharbor/harbor#15310]
Hi,
When I push a docker image from my local machine to Harbor, I see that the digest of the image has changed.
I'm not sure if this is some problem with Harbor or if my procedure and understanding of digests is wrong.

Let's say I have this image on my local machine which I have pulled from quay.io:
```
rnd-vm-5-146 ~# docker image ls --digests
REPOSITORY                                        TAG          DIGEST                                                                   IMAGE ID      CREATED        SIZE
quay.io/kiali/kiali                               v1.29        sha256:26f832246fdedc0912b0dcb2c587d16082920019a97b049c486d6d583b36c997  6d194f4249aa  4 months ago   174 MB
```

After that I tag it:
```
docker tag quay.io/kiali/kiali:v1.29 harbor.our-registry.com/paas/paveltest/kiali:v1.29
REPOSITORY                                        TAG          DIGEST                                                                   IMAGE ID      CREATED        SIZE
harbor.our-registry.com/paas/paveltest/kiali    v1.29        sha256:26f832246fdedc0912b0dcb2c587d16082920019a97b049c486d6d583b36c997  6d194f4249aa  4 months ago   174 MB
```

And then I push the image to Harbor:
`docker push harbor.our-registry.com/paas/paveltest/kiali:v1.29`

Now when I look into the Harbor UI and check the image digest I see it's:
**_sha256:7a5cad073556770f4965237893e038f594dd8ec7628d07e3bbccf0b98a2aa5ba_**

Which is different than the original value:
_sha256:26f832246fdedc0912b0dcb2c587d16082920019a97b049c486d6d583b36c997_

In case when I create Harbor replication rule to automatically pull the image directly from quay.io, then in the Harbor UI I see that the pulled image has the 'correct' digest which I expect:
_sha256:26f832246fdedc0912b0dcb2c587d16082920019a97b049c486d6d583b36c997_

Can someone please explain to me why the digest shown in Harbor UI differs in the  two scenarios (manual push vs replication)?

The version of Harbor is:
_Version v2.0.2-e91b4ff1_

The docker/podman version on my local machine is:
_podman version 2.0.5_

**Comment by ninjadq** [comment]
this is a manifest list
