### ISSUE TITLE
deprecate project-level legacy robot accounts

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#15316]
Remove legacy project-level robot accounts in Harbor today.  Robot accounts shall only be created under the system config which can be assigned to multiple projects at once.

user stories to follow shortly

**Comment by wy65701436** [comment]
After deprecate the legacy robot accounts, 

1. the project admin still can create project level robot accounts, but its version 2 robots.
2. the system & project admin still can get & delete the legacy robots, but cannot login and do any pull/push.

**Comment by wy65701436** [comment]
PR to deprecate robot v1: https://github.com/goharbor/harbor/pull/15296

**Comment by wy65701436** [comment]
Pr is merged, and doc should be updated.

**Comment by wy65701436** [comment]
close it as fixed.
