### ISSUE TITLE
Integrate Sigstore Cosign into Harbor

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#15315]
We will investigate integrating Cosign for container image signing into Harbor. 

This will not impact existing Notary signing but instead offer an alternative signing solution.

**Comment by tianon** [comment]
For any folks looking to follow along, this has an official proposal over in https://github.com/goharbor/community/pull/172.

**Comment by xaleeks** [comment]
This will be delivered in v2.5

**Comment by wy65701436** [comment]
let close it as engineering work has almost done, and use https://github.com/goharbor/harbor/issues/16025 to track doc.
