### ISSUE TITLE
OIDC - Keycloack - Groups claim

### ISSUE THREAD

**Issue by h4wkmoon** [goharbor/harbor#15327]
Hi, 

We have trouble getting Harbor v2.3.0-047b122c to read groups from the oidc tokens.
As you can see, groups are set in the claim "listRoles", but Harbor says it can get them even though we set the paramater "groups claim" to listRoles.

What are we missing or doing wrong ?

```
021-07-16T06:19:51Z [WARNING] [/pkg/oidc/helper.go:375]: Unable to get groups from claims, claims: map[acr:0 aud:nova auth_time:1.626416346e+09 azp:nova email:*********** exp:1.626452346e+09 family_name:*********** *********** iat:1.62641639e+09 iss:*********** jti:32d90cdc-13af-4b6b-9fd1-898a9d12b498 listRoles:[NOVA_CICD.NEXUS_ADMIN] name:*********** nbf:0 preferred_username:*********** session_state:76fbc3c9-c754-4330-9205-fbbb850b3e17 sub:f:1e2c4ce2-30e9-46d8-be61-13ccc86b4c5c:****** typ:ID], groups claims key: listRoles
2021-07-16T06:19:51Z [WARNING] [/pkg/oidc/helper.go:375]: Unable to get groups from claims, claims: map[email:*********** family_name:*********** given_name:*********** listRoles:[NOVA_CICD.NEXUS_ADMIN] name:***********preferred_username:*********** sub:f:1e2c4ce2-30e9-46d8-be61-13ccc86b4c5c:***********], groups claims key: listRoles
```

**Comment by Vad1mo** [comment]
Does you claim name follow the URL format? 
e.g. https://auth0.com/docs/tokens/create-namespaced-custom-claims
We had difficulties as well until we did that.

**Comment by h4wkmoon** [comment]
Thanks. 
It appeared that the custom mapper created for us on keycloak was sending the groups as a string, not an array. After they corrected that, everything worked as planned.
