### ISSUE TITLE
Bot user can not be entitled to retrieve list of images

### ISSUE THREAD

**Issue by Martin-Weiss** [goharbor/harbor#15321]
For image staging and replication we need a way to retrieve the list of images from harbor. This works for users configured as "harbor admin" but as we need to do this in some scripts from external we would like to use a bot user and would like to give the bot user the right to retrieve the list of images from the harbor registry.

Unfortunately this right an not be assigned to a bot user.

Could we get the access control for bot users enhanced to allow image list retrieval (https://registry.domain.local/v2/_catalog)?

**Comment by wy65701436** [comment]
you can refer to this: https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533

**Comment by scottso** [comment]
Is there any ongoing work toward a solution to this?  It is currently blocking our ability to integrate Snyk with Harbor.

**Comment by YangJiao0817** [comment]
I can call /v2/_catalog in the following way.
1. Create system level robot account
```
curl -k -u '<admin_name>:<admin_password>' -X 'POST' \
 'https://<domain>/api/v2.0/robots' \
 -H 'accept: application/json' \
 -H 'Content-Type: application/json' \
 -d '{
    "name": "<robot_name>",
    "duration": 30,
    "description": "test",
    "disable": false,
    "level": "system",
    "permissions": [
        {
            "kind": "system",
            "namespace": "/",
            "access": [
                {
                    "resource": "catalog",
                    "action": "read"
                }
            ]
        }
    ]
}'
```
2. Call catalog API
```
curl -k -u '<robot_name>:<robot_password>' -X 'GET' 'https://<domain>/v2/_catalog'
```

**Comment by wy65701436** [comment]
please try with the above method, thanks @YangJiao0817

**Comment by DarkWolf7** [comment]
I am running into the same issue - when I attempt the same curl, I get the following error:

`{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to list catalog: unauthorized to list catalog"}]}`
