### ISSUE TITLE
Why are SMTP credentials still an option?

### ISSUE THREAD

**Issue by harrishcris** [goharbor/harbor#15331]
SMTP server credentials are still an option in the settings however the password reset feature has been removed - https://github.com/goharbor/harbor/issues/10712

Or are these settings still used somewhere if you can still enable the user password reset feature when using the local inbuilt database?

**Comment by reasonerjt** [comment]
Hi, currently the SMTP is not used.

We don't plan to re-enable the `reset` feature so far.
