### ISSUE TITLE
Jobservice not honoring sweeper duration

### ISSUE THREAD

**Issue by tmojlupo** [goharbor/harbor#15339]
In the harbor jobservice configmap, the sweeper duration is set to 14 days, but in our 2 instances we are seeing files as old as 27 days (I had removed these files to address replication failures due to maxed out inodes). 

Today's date is 7/19 and these are the oldest files in /var/log//lobs filesystem.  The oldest should be from 7/5.
-rw------- 1 harbor harbor   1708 2021-06-25 09:07 6415ae66d2cc67edfc2ff3d2.log
-rw------- 1 harbor harbor   1973 2021-06-25 09:07 230dff04feb51a545e03c192.log
-rw------- 1 harbor harbor   1891 2021-06-25 09:07 6f8a550e692a0401a3142081.log
-rw------- 1 harbor harbor   1973 2021-06-25 09:07 1c5e4c2f29efbfbb69974e08.log
-rw------- 1 harbor harbor   1973 2021-06-25 09:07 336ab72c4fd7a689ca34fbfc.log

Found issue #6250 referenced this in the past and was pointed at the jobservice sweeper as the fix.

**Expected behavior and actual behavior:**
We would expect that the jobservice sweeper would remove files more than 14 days old, but the files just kept getting created until the filesystem ran out of inodes.

**Steps to reproduce the problem:**
Seems you can run replication frequently with a lot of images.  

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.3]
- docker engine version: [19.03.14]
- docker-compose version: [z.z.z]
- k8s version: [1.17.17]

**Additional context:**

We have a few hundred images and run push replication jobs on event as well as pull every hour to keep our 2 Harbor instances in sync.  We upgraded one side to 2.1.3 in June and it took 27 days to fill up.

- jobservice configmap.

```apiVersion: v1
data:
  config.yml: |
    #Server listening port
    protocol: "http"
    port: 8080
    worker_pool:
      workers: 10
      backend: "redis"
      redis_pool:
        redis_url: "redis://tke-harbor-harbor-redis:6379/1"
        namespace: "harbor_job_service_namespace"
        idle_timeout_second: 3600
    job_loggers:
      - name: "FILE"
        level: INFO
        settings: # Customized settings of logger
          base_dir: "/var/log/jobs"
        sweeper:
          duration: 14 #days
          settings: # Customized settings of sweeper
            work_dir: "/var/log/jobs"
    #Loggers for the job service
    loggers:
      - name: "STD_OUTPUT"
        level: INFO
kind: ConfigMap
metadata:
  labels:
    app: harbor
    chart: harbor
    heritage: Helm
    release: tke-harbor
  name: tke-harbor-harbor-jobservice
  namespace: tke-harbor
```

**Comment by steven-zou** [comment]
@tmojlupo 

Can any jobservice log relate to this issue provided for troubleshooting?

I double-checked the related code, it seems there is no explicit problem there.
