### ISSUE TITLE
New Registry Endpoint - Internal server error

### ISSUE THREAD

**Issue by nikola-vortexwe** [goharbor/harbor#15345]
Hi guys, I am trying to deploy the latest version of Harbor via docker-compose without SSL communication between Harbore components. All of the config files are left with the default configurations they come with. 

The deployment step worked fine, but I am unable to create a new registry endpoint. 
I get the following error while trying to do so:
`Convert registry model to dao layer model error: crypto/aes: invalid key size 17
Add registry 'https://hub.docker.com' error: crypto/aes: invalid key size 17
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"crypto/aes: invalid key size 17"}]}`. 

Validations against the desired registry - Docker Hub are performed successfully, meaning that the credentials are properly getting checked against it.  The value of both the CORE_SECRET and JOBSERVICE_SECRET environment variables are exactly 16 characters long. 

Any ideas what I'm doing wrong? Please, let me know if you need further information.

**Comment by heww** [comment]
@ninjadq should we validate the configurations during the preparing stage? Especially the length of the secret key and xsrf key.

**Comment by ninjadq** [comment]
Add verification of key length in prepare script
