### ISSUE TITLE
v2.3.0 About popup is showing [object Object]

### ISSUE THREAD

**Issue by enajeeb** [goharbor/harbor#15342]
Instead of Harbor description and link to license as in previous version, its showing `[object Object]`

<img width="576" alt="image" src="https://user-images.githubusercontent.com/3844941/126387827-80a3d358-0376-46e5-b79f-7af933bb04d6.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.0]

**Comment by AllForNothing** [comment]
@enajeeb How do you configure the "setting.json" under src/portal/src?

**Comment by AllForNothing** [comment]
@enajeeb Youcan refer to https://goharbor.io/docs/2.3.0/build-customize-contribute/customize-look-feel

**Comment by enajeeb** [comment]
It works now without me doing anything.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3844941/127174068-5855de8e-148f-42de-a3d2-40c2bd3eb6ac.png">

**Comment by AllForNothing** [comment]
@enajeeb Looks like a browser cache issue if you  updated your Harbor from the old version
