### ISSUE TITLE
Unable to use Azure OIDC claims that aren't present in userinfo

### ISSUE THREAD

**Issue by acobaugh** [goharbor/harbor#15348]
It would appear that Harbor can only use claims from Azure ID tokens that are also present in the `userinfo` endpoint. This is evidenced by the fact that I can't use other claims like `upn` and `preferred_username` and similar for `Username Claim`. 

Additionally, groups are not being extracted for the user. The log message for that is below. However, there are `Groups` showing up under `Administration -> Groups`, so they're present somehow. If I turn up the log level to debug and decode the ID token that's logged, all the claims I'm trying to use are present.

My suspicion is that Harbor is only looking at the claims present in the userinfo endpoint.

**Expected behavior and actual behavior:**

Claims such as `groups`, `upn`, `preferred_username`, etc, should be usable.

**Steps to reproduce the problem:**

Configure harbor to use Azure OIDC. Expose groups, or any other claims via ID Token (https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims).

**Versions:**

- harbor version: v2.3.0-047b122c

**Additional context:**

- **Log files:** 

```
harbor-core-f5bfbc5c4-xstxf core 2021-07-22T20:54:42Z [WARNING] [/pkg/oidc/helper.go:375]: Unable to get groups from claims, claims: map[email:atc135@psu.edu family_name:Cobaugh given_name:Andy name:Cobaugh, Andy picture:https://graph.microsoft.com/v1.0/me/photo/$value sub:6PvEO0UQDbdLGFZr16tPCDBu7AlIe1IUgSvYVexoGhw], groups claims key: groups
```

**Comment by reasonerjt** [comment]
@acobaugh 
1) As for the groups since the groups are populated, I believe you can ignore the warning in the log message, Harbor DOES fallback to the groups information in ID token.
2) As for the username, it seems a dup of #15290 I'm waiting for the clarification from the submitter, if no response I will merge the PR and consider to have it in the patch.

**Comment by acobaugh** [comment]
For (1), it doesn't seem to be making me an admin based on oidc group membership, which is what lead me to believe that groups weren't working.

For (2), I thought maybe #15290 was related, but didn't read the code close enough to see if that's what was causing me issues or not. If there were docker images with that patch include, I'd be happy to test to see if that resolves the issue for me.

**Comment by Athosone** [comment]
Do you poke userinfo endpoint to get groups claim ?

**Comment by acobaugh** [comment]
Just updated to v2.3.3 and I'm still having this issue, which I think proves that the fix for #15504 doesn't fix my problem.

```
harbor-test-core-5885dd4778-5lgpl core 2021-09-28T15:34:11Z [WARNING] [/pkg/oidc/helper.go:361]: OIDC. Failed to recover Username from claim. Claim 'preferred_username' is invalid or not a string
harbor-test-core-5885dd4778-5lgpl core 2021-09-28T15:34:11Z [WARNING] [/pkg/oidc/helper.go:361]: OIDC. Failed to recover Username from claim. Claim 'preferred_username' is invalid or not a string
harbor-test-core-5885dd4778-5lgpl core 2021-09-28T15:34:11Z [WARNING] [/pkg/oidc/helper.go:387]: Unable to get groups from claims, claims: map[email:atc135@psu.edu family_name:Cobaugh given_name:Andy name:Cobaugh, Andy picture:https://graph.microsoft.com/v1.0/me/photo/$value sub:6PvEO0UQDbdLGFZr16tPCDBu7AlIe1IUgSvYVexoGhw], groups claims key: groups
```

**Comment by R-Studio** [comment]
I have the same issue. Any news on this?

**Comment by R-Studio** [comment]
Any news?

**Comment by yexia553** [comment]
any new? still has this issue in 2.7.0 version.

**Comment by philippw** [comment]
We are also affected by this.
