### ISSUE TITLE
many images size were 0B and creation time marked 1/1/01, 8:05 AM and docker login error

### ISSUE THREAD

**Issue by jhondom** [goharbor/harbor#15343]
i found that many images were 0B and creation time marked 1/1/01, 8:05 AM:
![image](https://user-images.githubusercontent.com/37328297/126418165-cabf75ea-08ac-46f1-8551-488969d79691.png)

as the same time, when this is occurred, docker login is error:
![image](https://user-images.githubusercontent.com/37328297/126418239-eb7b9c6f-87bd-4b27-a574-0abf4661af11.png)

or docker push is error:
![image](https://user-images.githubusercontent.com/37328297/126418259-328de8ab-bcf4-47a1-867d-25a5a67d7fc2.png)

and the web ui is error:
![image](https://user-images.githubusercontent.com/37328297/126418349-13bbe288-5207-47bc-bd3d-7f20cc3525d3.png)

Versions:

harbor version: [1.7.1]

**Comment by heww** [comment]
This is a known issue in harbor 1.x, please upgrade to harbor 2.x which resolves the 0 size problem.
