### ISSUE TITLE
why no ldap auth self like other software?

### ISSUE THREAD

**Issue by ruben-herold** [goharbor/harbor#15352]
hi.

I saw that harbor still needs an binddn and password to connect to ldap why? This is from my perspective also security related.
With all modern libs it should be possible to do an selfbind to get all informations which are needed. 

Which means that the user connects with its username password to the ldap server to: 
                 a) validate the password
                 b) to get groupmemberships

**Comment by stonezdj** [comment]
1. When a user (mike) login to Harbor with LDAP auth, how to do selfbind when the user DN is unknown?
2. When an admin adds an LDAP group to the project member, the admin is not an LDAP user, he should use the admin dn to search/check if the group exists.
