### ISSUE TITLE
Harbor postgresql too many clients already

### ISSUE THREAD

**Issue by jhondom** [goharbor/harbor#15357]
when i acess the postgresql.log. there are many FATAL messages,but i can login the webui correctly and push or pull the image normally, how can i do to forbid the error and resolve the problem?
-----------
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 31 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 8 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 5 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 3 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 8 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 10 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 50 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 16 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 28 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 2 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 9 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 6 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: message repeated 5 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:35:24 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:20 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:20 172.18.0.1 postgresql[9499]: message repeated 32 times: [ FATAL:  sorry, too many clients already]
Jul 26 10:36:20 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:21 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:21 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:21 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:21 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
Jul 26 10:36:21 172.18.0.1 postgresql[9499]: FATAL:  sorry, too many clients already
![Uploading image.png…]()

version:1.7.5

**Comment by heww** [comment]
Please upgrade to harbor v2.x which supports limiting the DB connection used by the core component.

**Comment by jhondom** [comment]
how can i do before upgrade harbor v2.x。the harbor services is right?

**Comment by jhondom** [comment]
> Please upgrade to harbor v2.x which supports limiting the DB connection used by the core component.

how can i do before upgrade harbor v2.x。the harbor services is right?
