### ISSUE TITLE
Better Webhook Management in Web UI

### ISSUE THREAD

**Issue by atzawada** [goharbor/harbor#15363]
**Is your feature request related to a problem? Please describe.**
I am frustrated that debugging webhooks can be difficult to the end user. If a hook fails it it often difficult to acertain the root cause of the failure.

**Describe the solution you'd like**
I would like an addition to the Webhook management UI that shows previously delivered webhooks and their request body, response status, and other pertinent information. The way I imagine it would look would be similar to the GitHub repository webhook UI. 

**Describe the development plan you've considered**
I don't have a development plan for this but if someone can point me in the right direction I can start to work it out.

**Comment by Vad1mo** [comment]
I think we should build up on this proposal and add a "General purpose event emitting functionality" to Harbor.

There are already some libraries around that topic that we could use:
- https://github.com/nikoksr/notify
- https://github.com/caronc/apprise.

This way, each project or organization can decide what events from Harbor should be forwarded and what channel.

**Comment by mmpei** [comment]
hi @Vad1mo, harbor webhook already has the function you described above now.
we will consider the libraries you mentioned.
thank you for your advise.
