### ISSUE TITLE
Missing goharbor/clair-photon:v2.1.6 image when using online installer

### ISSUE THREAD

**Issue by son-la** [goharbor/harbor#15369]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
*** Expected ***
Install Harbor 2.1.6 with clair successfully when executing Execute ./install --with-clair

*** Actual ***
[Step 4]: starting Harbor ...
Pulling clair (goharbor/clair-photon:v2.1.6)...
ERROR: manifest for goharbor/clair-photon:v2.1.6 not found

**Steps to reproduce the problem:**
Install Harbor 2.1.6
Execute ./install --with-clair

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.6]

**Comment by wy65701436** [comment]
fixed, just try it again, thanks.
