### ISSUE TITLE
How can I upload helm plugins to harbor repository

### ISSUE THREAD

**Issue by sarvesh-ranjan** [goharbor/harbor#15377]
I have seen documentation about how to upload new "helm charts" to a harbor repository https://goharbor.io/docs/1.10/working-with-projects/working-with-images/managing-helm-charts/#upload-a-new-chart

But I want to upload a helm plugin to harbor, so that I'm able to run commands from master node to install the plugin like 
`helm plugins install PATH`

Plugin I want to upload: 
`https://github.com/hickeyma/helm-mapkubeapis`
Expected command to install above plugin
`helm plugin install https://github.com/hickeyma/helm-mapkubeapis <Repo info>`

Helm version 
```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```
harbor version: 2.3.1
docker engine version: 20.10.7
docker-compose version: 1.29.2

**Comment by ninjadq** [comment]
hi @sarvesh-ranjan, do you mean you wanna storage the chart plugin repo into Harbor? Actually, it's a GitHub repo, Harbor doesn't support this content. 
Or do you just want to install this plugin? please refer [this](https://helm.sh/docs/helm/helm_plugin_install/)

**Comment by wy65701436** [comment]
it's not supported. You can wrap the plugin to be an OCI artifact, then operate it with Harbor via OCI client, like oras.
