### ISSUE TITLE
Replication wildcard not working

### ISSUE THREAD

**Issue by jsmartel68** [goharbor/harbor#15371]
### Issue Description

When trying to mirror an external registry, a wildcard in the resource filter Name field of the Replication does not work.

Harbor Version v2.1.5-919c9fd2

### Steps to Reproduce

1. Create Endpoint for quay.io with endpoint https://quay.io
2. Create Replication using the quay endpoint with resource filters Name: osism/* and Tag: wallaby
3. Run the Replication

### Expected Results

The Replication will copy resources from all repositories from the quay.io/osism/ organization with tag wallaby.

### Actual Results

The Replication will say "Succeeded" and the pop up will display "no resources need to be replicated". No actual images are copied.

### Other Information

The Replication will correctly pull the tagged resources if a list of repositories is specified in the resource filter:
- Name: osism/{keystone,neutron-server}
- Tag: wallaby

Wildcard patterns that fail with the "no resources need to be replicated" message that I have attempted:

```
- osism/*
- osism/**
- osism/*/*
- osism/**/**
```

Note, there are 186 repositories in the quay.io/osism organization. Listing them all in { } is not practical, hence the desire for the wildcard to work.

**Comment by bitsf** [comment]
`osism/*` should already work.
Does `osism/{keys*} ` work for replicating the `keystone` ?

**Comment by bitsf** [comment]
I test with v2.3.0, with repo filter 'xxxx/*' and tag filter 'latest', it works.
I'm not sure if it related with large repositories paging problem.
Can you check some other tags or not use tag filter?

**Comment by bitsf** [comment]
oh, I know, you are not the owner of osism, or you didn't enter credential when you create Endpoint, that  harbor can't use catalog API to list repositories when you use wildcard
