### ISSUE TITLE
Unable to add credentials to existing Docker Hub endpoint

### ISSUE THREAD

**Issue by kartikdc** [goharbor/harbor#15382]
Hello.

Not sure if this is by design but wanted to report anyway.

After creating a Docker Hub registry endpoint with NO application ID and secret, I wasn't able to edit the endpoint and add the credentials to it so that I would be able to access private images. The web UI would just say "Internal Server Error". This is the relevant error message from core.log (I triple checked that the credentials were correct):

```
Aug  2 14:48:25 172.26.0.1 core[2910616]: 2021-08-02T12:48:25Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: login to dockerhub error: {\"detail\":\"Incorrect authentication credentials\"}\n\n"}]}
```

I had to delete the endpoint and create a new one with credentials, which worked.

If this is by design a clearer error message would help here.

**Versions:**

- harbor version: 2.3.0
- docker engine version: 20.10.6
- docker-compose version: 1.29.2

**Comment by stonezdj** [comment]
It seems to be a UI issue, the update request only contains the access_secret field.

**Comment by kartikdc** [comment]
@stonezdj If if you need more information feel free to let me know. I can try replicating the issue and give you whatever logs you want.

**Comment by AllForNothing** [comment]
@kartikdc Thanks for your info.
It is surely a UI bug and PRs raised to fix it
