### ISSUE TITLE
failed to ping registry with http status code: 401, body: error occurred in harbor cluster

### ISSUE THREAD

**Issue by unixomg** [goharbor/harbor#15386]
hello:
       I manually deployed two harbor v2.3.0, using shared storage and shared redis. When I configured the destination registry, I observed that one of the core logs of the two machines must execute HealthCheck every 5 minutes. It reports a failed to ping registry error, but if I stop a server and just use one, this error will not be reported. 
       I don’t know why, by the way, I want to replication  image from v1.2.2 to v2.3.0, there will be part of success. The failed log, the specific log is as follows:
       Can someone help me look at these two issues？ tks.

   **Versions:**
      Please specify the versions of following systems.

      harbor version: v2.3.0
      docker engine version: 19.03.9
      docker-compose version: 1.29.2

   Additional context:

    core.log: 

    `Aug  2 18:16:22 172.26.0.1 core[14131]: 2021-08-02T10:16:22Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://10.72.xx.xx: http status code: 401, body: 
     Aug  2 18:21:22 172.26.0.1 core[14131]: 2021-08-02T10:21:22Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://10.72.xx.xx: http status code: 401, body: 
     Aug  2 18:26:22 172.26.0.1 core[14131]: 2021-08-02T10:26:22Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://10.72.xx.xx: http status code: 401, body: 
     Aug  2 18:31:22 172.26.0.1 core[14131]: 2021-08-02T10:31:22Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://10.72.xx.xx: http status code: 401, body: 
     Aug  2 18:36:22 172.26.0.1 core[14131]: 2021-08-02T10:36:22Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://10.72.xx.xx: http status code: 401, body:  `

This error will only appear on one machine, and will cause the destination registry in the ui interface to be healthy and unhealthy for a while.

    jobservice.log:   `Aug  4 09:57:17 172.28.0.1 jobservice[14131]: 2021-08-04T01:57:17Z [INFO] [/controller/replication/transfer/image/transfer.go:339]: the manifest of artifact chi/webapp:20200518.289729 pulled
    Aug  4 09:57:17 172.28.0.1 jobservice[14131]: 2021-08-04T01:57:17Z [ERROR] [/controller/replication/transfer/image/transfer.go:347]: failed to check the existence of the manifest of artifact chi/webapp:20200518.289729 on the destination registry: http status code: 401, body: 
    Aug  4 09:57:17 172.28.0.1 jobservice[14131]: 2021-08-04T01:57:17Z [ERROR] [/controller/replication/transfer/image/transfer.go:175]: http status code: 401, body: 
    Aug  4 09:57:17 172.28.0.1 jobservice[14131]: 2021-08-04T01:57:17Z [INFO] [/controller/replication/transfer/image/transfer.go:191]: copying chi/webapp:20200518.289773(source registry) to chi/webapp:20200518.289773(destination registry)...`

The above error occurs when I try to pull the destination mirror image, there is always a part of the log that cannot be pulled, indicating 401

Some of the log prompts of replication failure seen in the dashboard are as follows：

`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"2adbd40746a8892c7e69d07e\"}"}]}`

**Comment by heww** [comment]
You must provide the same secret key for both harbor instances. The default path of the secret key file is `/data/secret/keys/secretkey`.

Besides the secret key file, the private key file `/data/secret/core/private_key.pem` also must be the same one.

Also `CSRF_KEY` in the env of the core compoent.

**Comment by unixomg** [comment]
After my test, it is indeed like this, thank you very much！！  In addition, I have another question. What happens if the redis database data that the harbor relies on is lost? Will it affect the functionality of the harbor?

**Comment by unixomg** [comment]
> You must provide the same secret key for both harbor instances. The default path of the secret key file is `/data/secret/keys/secretkey`.
> 
> Besides the secret key file, the private key file `/data/secret/core/private_key.pem` also must be the same one.
> 
> Also `CSRF_KEY` in the env of the core compoent.

After my test, it is indeed like this, thank you very much

**Comment by heww** [comment]
> After my test, it is indeed like this, thank you very much！！ In addition, I have another question. What happens if the redis database data that the harbor relies on is lost? Will it affect the functionality of the harbor?

It may make the scheduled jobs (schedule gc, scan all) failed. BTW, this problem will be resolved in harbor 2.4

**Comment by unixomg** [comment]
> schedule

Will the push image and pull image be affected if redis fails? Or it will only affect gc and scan all tasks，tks

**Comment by heww** [comment]
Pushing will be failed when the Redis fails.

**Comment by unixomg** [comment]
> Pushing will be failed when the Redis fails.

At present, our redis uses a single point server. If the service where redis is located fails, start a new redis on a new machine. At this time, there may not be the original old data. If the harbor is directly connected to the new redis database, can it continue to provide services? ? Or it must have the original redis data.thks

**Comment by heww** [comment]
If the harbor is directly connected to the new redis database, it can continue to provide services. But the scheduled job needs to reconfigure.

**Comment by unixomg** [comment]
> If the harbor is directly connected to the new redis database, it can continue to provide services. But the scheduled job needs to reconfigure.
How can I quickly restore the service if I encounter this kind of failure? is there any related document for reference? after connecting to a new redis database, services can be provided quickly.

**Comment by heww** [comment]
Please wait for harbor 2.4, all things will still work when the Redis data is lost at that version.

**Comment by unixomg** [comment]
> Please wait for harbor 2.4, all things will still work when the Redis data is lost at that version.

Sorry, please ask you another question. if i configure a redis master-slave synchronization, when the master fails, I switch to the slave redis, so that the pull and push functions of the harbor should be able to provide services normally? if possible, i am going to adopt this method to avoid a single point of failure。

**Comment by heww** [comment]
Harbor supports Redis sentinel for the HA of redis.
