### ISSUE TITLE
Get raw scanning report from the API

### ISSUE THREAD

**Issue by chengyuhui** [goharbor/harbor#15389]
The [proposal](https://github.com/goharbor/community/blob/master/proposals/pluggable-image-vulnerability-scanning_proposal.md) hightlights that a scanner should support `application/vnd.scanner.adapter.vuln.report.raw`, and in fact Harbor does pull a report of that type from the scanner if it has that type defined in its metadata.

However, there does not seem to be an API (or argument) that we can use to pull such a report from Harbor as our scanner is not accessible outside of the Harbor instance environment for security reasons. A header does exist in more recent versions, but the type it can fetch is whitelisted for no reason ("only these types are supported").

Any idea what I am missing?

**Comment by heww** [comment]
`application/vnd.scanner.adapter.vuln.report.raw` is not used in the harbor at the moment.
