### ISSUE TITLE
Replication - tag filter not work

### ISSUE THREAD

**Issue by andreevgrisha** [goharbor/harbor#15385]
**Expected behavior**

replicate images only with filter tag

![1](https://user-images.githubusercontent.com/37334538/128021254-1b869cf8-1894-45c5-b632-4f1ecd922ddf.jpg)

**actual behavior**

replicate all images with every tags

![2](https://user-images.githubusercontent.com/37334538/128021299-6215d3eb-b6a4-45c0-b38f-a1e5b750a3fe.jpg)

**Versions:**
 harbor version: [2.3.1]
- docker engine version: [19.03.13]
- docker-compose version: [1.26.2]

**Comment by heww** [comment]
Which version of GitLab do you use?

**Comment by andreevgrisha** [comment]
https://registry.gitlab.com - may be latest version :) ?
Or you ask about something else?

**Comment by bitsf** [comment]
this seems an issue, I will check it.

**Comment by TheWiresharkGuy** [comment]
Hi, same problem here with the latest self-hosted GitLab version (14.2.3-ee)
