### ISSUE TITLE
ProjectAdmins cannot see their project's replications

### ISSUE THREAD

**Issue by jonwtech** [goharbor/harbor#15391]
What can he help you?

Harbor version: 2.2.3.

As a system admin I’ve set up several event-based push replications which are working fine. My understanding from the docs (https://goharbor.io/docs/2.2.0/administration/managing-users/user-permissions-by-role/) is that (non-system admin) ProjectAdmins should be able to view the replications and replication jobs for their projects, but we cannot find out how to do this.

In the screenshot here https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/ I can see a Replication tab within a project, but we’re not seeing that tab on any of our projects. The screenshot looks to be an earlier version of Harbor so I was wondering if this functionality is still available.

Many thanks!

**Comment by phin1x** [comment]
the screenshot you mentioned is very old and not longer correct. the replication is only available under the administration settings and so only available to an adminstrator (its a system permission and not a project permission).

the screenshots should be updated.

**Comment by jonwtech** [comment]
Many thanks for the clarification. The docs also mention that ProjectAdmins should be able to view project replications: https://goharbor.io/docs/2.2.0/administration/managing-users/user-permissions-by-role/ - perhaps this could be updated to reflect that this can be achieved via a webhook now.
