### ISSUE TITLE
Timestamp error in gc-page

### ISSUE THREAD

**Issue by JinXingYoung** [goharbor/harbor#15408]
Asking for help about a timestamp problem,thanks.
Harbor version is 2.1.2

The timestamp of  update_time in the gc-page is 8h more than creation_time.And finding that this problem is because of the trigger of table.I will show the problem with table admin_job,other tables with this trigger is same.And my timezone is CST-8.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/11850715/128960076-ddd78d0b-5f99-40fc-9c37-738d8a587701.png">

select id,job_name,creation_time,update_time from admin_job;
<img width="709" alt="image" src="https://user-images.githubusercontent.com/11850715/128963850-0647d894-3536-4913-b2e8-8635c58f1791.png">

Then finding there's a db trigger for admin_job update.Is there any situation that need this trigger?It also updates update_time in the code.
trigger in the admin_job table:
https://github.com/goharbor/harbor/blob/fcc6751d5439da1b58f2553cb49b7db9bc3ad17a/make/migrations/postgresql/0001_initial_schema.up.sql#L357
https://github.com/goharbor/harbor/blob/fcc6751d5439da1b58f2553cb49b7db9bc3ad17a/make/migrations/postgresql/0001_initial_schema.up.sql#L48-L55
update update_time in the code:
https://github.com/goharbor/harbor/blob/fcc6751d5439da1b58f2553cb49b7db9bc3ad17a/src/common/dao/admin_job.go#L79-L85

postgresql using our own stage service and pg version is 11.10
It mounts the /etc/localtime file of the hosts(CST-8)
It seems NOW() is a timestamp with timezone, and using this time to update update_time which is a timestamp without timezone.
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/11850715/128962055-0d57f1c0-6126-4140-9b11-b91caa47cb02.png">

**Comment by cd1989** [comment]
@ywk253100 @wy65701436 Could you help check problem ?

**Comment by wy65701436** [comment]
hi, this table was dropped after v2.2,  would you mind to update to latest build?

**Comment by JinXingYoung** [comment]
> hi, this table was dropped after v2.2, would you mind to update to latest build?

ok, but other tables with this trigger have the same question, such as harbor_user.I add a user and then change pwd,update_time is 8h more than creation_time
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/11850715/128985907-23373200-8c27-4983-a267-c3cb1f6744d7.png">

**Comment by zyyw** [comment]
in harbor 2.1.2 env, even i manually set PostgreSQL timezone as below:
```
registry=# set timezone to 'Asia/Shanghai';
SET
registry=# show timezone;
   TimeZone
---------------
 Asia/Shanghai
(1 row)
```
And then I create a user3 and wait for 1 min to set user3 as admin. And the update_time is not 8h more than creation_time either.
<img width="851" alt="Screen Shot 2022-05-26 at 16 30 27" src="https://user-images.githubusercontent.com/6709992/170450429-7396bcaf-5f3c-4a5a-a976-1c78d502b5d9.png">

@JinXingYoung I noticed that you mentioned:
```
postgresql using our own stage service and pg version is 11.10
```
The issue you report may due to the config of your pg.

**Comment by zyyw** [comment]
@JinXingYoung I noticed that you mentioned:
```
postgresql using our own stage service and pg version is 11.10
```
the issue you reported may due to the config of the pg database you are using. Could you please try another pg database or use the pg database shipped with harbor and see if this issue still persists?
