### ISSUE TITLE
The version of the source code is inconsistent during installation.

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#15409]
When executing. / install:
![image](https://user-images.githubusercontent.com/88759374/128970505-95f2d5a7-4cdf-403b-a148-1f507626e970.png)
How to solve this problem? No solution to this problem was found on the network.

**Comment by wy65701436** [comment]
you have to check the connect to the docker hub, and just try to pull goharbor/harbor-log:v2.3.1 to see if any problem.
