### ISSUE TITLE
Obtain CLI Secret through API using OIDC username and password?

### ISSUE THREAD

**Issue by prudhvigodithi** [goharbor/harbor#15402]
**Expected behavior and actual behavior:**
Expected to Query /users/{user_id} with external OIDC user, but when it try to Query it gives message":"UnAuthorize
`{"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorize"}]}`

**Steps to reproduce the problem:**
Works
`curl -u '<default_harboradmin_user>:<default_harboradmin_pass>' -X GET  https://testharbor.internal.com/api/v2.0/users/40 -k`
fails
`curl -u '<svc_account_user>:<svc_account_pass>' -X GET  https://testharbor.internal.com/api/v2.0/users/40 -k`

**Versions:**
- harbor version:  v2.2.3-74ecf354

**Additional context:**
Referring to https://github.com/goharbor/harbor/issues/13221

Hey, currently we are using the harbor version v2.2.3-74ecf354
we are trying to use harbor API to rotate system robot accounts password, we are able to successfully do it with admin username and password, but we want to leverage service account coming from OIDC (integrated with keycloak) for this automation.
As part of this we are trying to GET the cli_secret value of the service account
`curl -u '<svc_account_user>:<svc_account_pass>' -X GET  https://testharbor.internal.com/api/v2.0/users/40 -k`
But we get output as
`{"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorize"}]}`
Howver when we try with admin username and password it works
`curl -u '<default_harboradmin_user>:<default_harboradmin_pass>' -X GET  https://testharbor.internal.com/api/v2.0/users/40 -k`
One more observation is from console after I login with <svc_account_user> and <svc_account_pass> then this works https://testharbor.internal.com/api/v2.0/users/40  from browser, but from curl or other code it fails.
Is this expected that only internal admin user can query the users from API? Please let me know how to proceed further.
Thank you

**Comment by reasonerjt** [comment]
Hi @prudhvigodithi 

By  `<svc_account_user>:<svc_account_pass` do you mean the username and `OIDC CLI secret`?  
This will not work because the CLI secret is used for issue docker commands to push/pull the images, not calling the API, for calling the API using a user that is onboarded to Harbor via OIDC SSO flow, you need the ID token of the user

**Comment by prudhvigodithi** [comment]
Hey @reasonerjt, hanks for reaching back
```<svc_account_user>:<svc_account_pass```
I'm passing the password of the user
So now I will test actual  id_token, we use backend keycloak, so I will query the keycloak for id_token and pass the generated id_token  for harbor API as ```<svc_account_user>:<svc_account_id_token>```

**Comment by prudhvigodithi** [comment]
Hey @reasonerjt yes works with 
```curl -H "Authorization: Bearer {token}"  -X GET https://testharbor.internal.com/api/v2.0/users/40 -k```
Thanks for the information, any documentation adding these details would be helpful.
