### ISSUE TITLE
How to change Authentication from OIDC to AD/LDAP

### ISSUE THREAD

**Issue by binhnguyenduc** [goharbor/harbor#15419]
We are currently using Harbor with Goole OIDC on production. 

Recently, we set up a AD/LDAP server of our own and would like to move Harbor users to use the new LDAP server. There is no option to change Authentication mode from OIDC to AD/LDAP on Harbor UI (v2.2.2)

Is it not possible at all? If it is, please point me to a possible solution. 

Thanks so much.

**Comment by wy65701436** [comment]
Harbor does not support change auth mode from OIDC to AD/LDAP once you have onboarded user. If you'd like to do it, you'd better to deploy an new one Harbor, and manual data to the new instance.
