### ISSUE TITLE
Replication to second harbor is extremely slow

### ISSUE THREAD

**Issue by massimo-coletti** [goharbor/harbor#15415]
- harbor version: [2.2.1]
- docker engine version: [20.10.7]
- docker-compose version: [1.29.2]

After upgrading to version 2.2.1, image replication is extremely slow, both manual replication and event based.

The log 'jobservice.log' is full of errors similar to:

Aug 11 10:00:47 10.104.1.1 jobservice[1771]: 2021-08-11T15:00:47Z [WARNING] [/jobservice/hook/hook_agent.go:121]: Send hook event 'status change: job=93279c759b7713af91a0469a, status=Error' to 'http://core:8080/service/notifications/tasks/1266302' failed with error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 93279c759b7713af91a0469a not found"}]}

and it seems they are repeating in an endless loop.

Can you please advise how to troubleshoot the problem? Which jobs are not found?

Thanks

**Comment by bitsf** [comment]
hi, is this still exists ?
Can you try stop all jobs including replication / scan / retention / gc, and wait some time, then check core.log and jobservice.log, check if job are still running.
If still running, you may clean jobservice cache in redis. And check execution status in database.
`select vendor_type,status,count(*) from execution group by vendor_type,status;`

**Comment by sshota0809** [comment]
I ran into this issue while replicating about 1000 images from other registry.
And I guess this is the same as #15430

**Comment by vainkop** [comment]
Any updates on that?
I get the following error when trying to replicate from gcr: 
`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"038a8435bb522a9c295069c2\"}"}]}`

This might be related to https://github.com/goharbor/harbor/issues/15415
