### ISSUE TITLE
Pull image return "ImagePullBackOff" using harbor robot account in k8s secrets

### ISSUE THREAD

**Issue by u0324020** [goharbor/harbor#15410]
What can we help you?

Harbor version: v2.1.4
Kubernetes version: Client v1.21.3/ Server v1.18.20-eks-8c579e
Installation method: AWS eks
Host OS: Linux

I'm trying using the harbor robot account and token as k8s secret to pull image.
I follow this guide to add secrets https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
command:
$ kubectl create secret docker-registry harbor-registry-secret --docker-server=xxx.com --docker-username=robot$xxx password=xxx

However, after add k8s secret success, when I pull image using that secret will return "ImagePullBackOff" and show unauthorized

How do I figure out this problem?

**Comment by phin1x** [comment]
did you escape the dollar sign in your shell? otherwise the shell will treat the $xxx as a variable.

**Comment by u0324020** [comment]
> did you escape the dollar sign in your shell? otherwise the shell will treat the $xxx as a variable.

this is the right way to figure out the unauthorized problem!!!! 
I create the secret using --docker-username="robot\$xxx" instead of --docker-username='robot$xxx'
The harbor robot account in k8s secret worked!
thank you!
