### ISSUE TITLE
Robots produce a lot of "failed to verify secret: failed to verify the secret: user does not exist" error logs

### ISSUE THREAD

**Issue by BrandonWeng** [goharbor/harbor#15420]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

We're seeing a lot of error logs like this whenever a robot account tries to interact with Harbor:
`2021-08-12T20:07:39.744Z 2021-08-12T20:07:39Z [ERROR] [/server/middleware/security/oidc_cli.go:59][requestID="43f6faf1-3327-4eae-b018-46317f4b72b4"]: failed to verify secret: failed to verify the secret: user does not exist, name: <robot_name>`

This started occurring after we enabled OIDC login. What I think is happening is that Harbor tries to auth via OIDC first, and when it fails it will raise this error but it will also try the next auth method, probably in this order: https://sourcegraph.com/github.com/goharbor/harbor@538266c/-/blob/src/server/middleware/security/security.go?L28-41

Our Robot accounts can still interact with Harbor but this is pretty noisy when we're trying to search for error logs. Is it possible to skip OIDC auth if the username has the robot prefix?

**Steps to reproduce the problem:**
- Enable OIDC
- Try to interact with Harbor through a robot account

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.1
- docker engine version: 19.03.1
- docker-compose version: unknown

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by AnavMahajan** [comment]
+1

**Comment by xammep4** [comment]
+1
