### ISSUE TITLE
After the installation is complete, the login prompts the password or the user name is incorrect

### ISSUE THREAD

**Issue by lemoba** [goharbor/harbor#15427]
What can we help you?
After the installation is complete, the login prompts the password or the user name is incorrect

**Comment by B3DTech** [comment]
I've been having this same issue.  Nobody has replied in the last 9 days yet.

**Comment by wy65701436** [comment]
hi, can you provide more info? 

Harbor version? 
how did you config Harbor? What's the auth mode?
How did you install Harbor? 
And the harbor log?

**Comment by B3DTech** [comment]
So I installed it via helm chart using defaults. I finally was able to fix it by manually setting the password in the database for the admin user. The instructions on VMware almost fully work. They say to use an empty password but you need to use the password you want.
