### ISSUE TITLE
download chart will response 404 not found resource

### ISSUE THREAD

**Issue by yosensen** [goharbor/harbor#15428]
**Expected behavior and actual behavior:**
expected:
download the chart
actual:
404 the resource not found 

**Steps to reproduce the problem:**
click PROJECT-> <project> -> HelmCharts -> select chart -> download 
when you download a chart,the request will be send following data
![image](https://user-images.githubusercontent.com/48777973/129373381-99584270-d945-4a1b-b066-f45ece0b45dd.png)
the data in v2.2.2 is 
![image](https://user-images.githubusercontent.com/48777973/129373559-f0e057f6-2679-4646-b2de-075c20d2b2f6.png)

**Versions:**

- harbor version: [ v2.3.1-299c29bd]
- docker engine version: [19.03.15]
- docker-compose version: [1.25.5]

**Comment by ninjadq** [comment]
dup for #15228
