### ISSUE TITLE
v2.3.1 standalone - db won't restart - seems to run initdb instead

### ISSUE THREAD

**Issue by MattBianco** [goharbor/harbor#15426]
Downloaded the standalone installer, ran it, logged in, configured LDAP authentication. logged out+in = success.
Stopping with **docker-compose stop** and then starting with **docker-compose start** fails to start the db container

Using docker-ce-19.03.4-3.el7.x86_64 + docker-compose-1.18.0-4.el7.noarch
SELinux is Disabled on the host

DB container logs this:
```
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: ls: cannot access '/var/lib/postgresql/data': Operation not permitted
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: The files belonging to this database system will be owned by user "postgres".
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: This user must also own the server process.
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: 
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: initdb: error: directory "/var/lib/postgresql/data/pg13" exists but is not empty
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: If you want to create a new database system, either remove or empty
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: the directory "/var/lib/postgresql/data/pg13" or run initdb
Aug 13 12:33:22 172.22.0.1 postgresql[31369]: with an argument other than "/var/lib/postgresql/data/pg13".
```

Which seems to be because this test failing:

https://github.com/goharbor/harbor/blob/86185989cfdcc94e5c73292d1d7ca4a809a53a6b/make/photon/db/docker-entrypoint.sh#L23

**Comment by MattBianco** [comment]
It seems to work on a different host. I'll close this and investigate on my own.

**Comment by MattBianco** [comment]
Works after upgrading Docker to **Docker version 20.10.8, build 3967b7d**

**Comment by DengLZ** [comment]
it's work! @MattBianco
