### ISSUE TITLE
Chart not showing when using SemVer 2 (x.y.z-rc.1)

### ISSUE THREAD

**Issue by aloisiobilck** [goharbor/harbor#15433]
The chart is shown in the Harbor UI, but I can't list it with the `helm search repo -l myrepo/myadd` command

Example:
Chart.yaml 
```
apiVersion: v2
name: myapp
description: A helm chart for myapp
type: application
version: 2.1.0-rc.1
version: 2.1.0-rc.1
``` 
SemVer 2 (https://helm.sh/docs/chart_best_practices/conventions/#version-numbers). 

Am I doing something wrong?

**Comment by ninjadq** [comment]
is there any error log in chartmuseum or harbor core component?
