### ISSUE TITLE
Only Project Members Can Start Scan In Public Project

### ISSUE THREAD

**Issue by headkm** [goharbor/harbor#15439]
Harbor Version: 2.2

In a public project we've found that users outside of those specifically granted permissions in the project **cannot** initiate a scan of images in the public project. Is this by design? Some users believe they should have the ability to scan any public project in the registry at any time due to the constant threat of 0 day vulnerabilities. Others feel scan on push and scheduled scanning are sufficient controls.

**Comment by wy65701436** [comment]
yes, it's by design. The member out of the public project can only have read permission.
