### ISSUE TITLE
User experience with respect to searching, navigating and sharing URLs

### ISSUE THREAD

**Issue by karuppiah7890** [goharbor/harbor#15436]
**Is your feature request related to a problem? Please describe.**

I have been using Harbor recently. I noticed some small subtle issues which didn't give a great user experience

For example, below are the experiences I had
- When I search something on the Harbor UI Search Bar, the URL of the browser does Not change. This leads to me not being able to share the search's (search action) URL to someone else
- When I see search results, I can't `Right Click` and choose  `Open in new tab` or do `Command / Ctrl` + `Left Click` to `Open in new tab`, as the search results are not actual `a` HTML tag (anchor tag) URLs, instead the navigation is based on JavaScript and I can see `javascript:void(0)` open up in a new tab when I Command + Click
- Searching within a project also does Not change the browser URL. This again leads to me not being able to share the search's (search action) URL to someone else

I know these are probably not very critical features, it's just that I felt it was a very basic thing and was wondering why it's not present in Harbor. I'm assuming it's because it's a Single Page Application and all the links are all managed by JavaScript and don't use anchor tag `a` at all, and probably the whole UI is more suited to be used in a single page, rather than opening up multiple new tabs with right clicks / command + click

**Describe the solution you'd like**

I would like to be able to share the search action I do on Harbor, where URL holds the search input and any other search action state

**Describe the main design/architecture of your solution**

I don't have any design / architecture for this as of now

**Describe the development plan you've considered**

I don't have any development plan for this as of now

**Additional context**

Version of Harbor that I'm using - `Version v2.1.3-b6de84c5`

I wrote about shareable URLs recently based on this experience - https://karuppiah7890.github.io/blog/posts/shareable-urls/

**Comment by AllForNothing** [comment]
@karuppiah7890 
Thanks for your great suggestion/idea.
After discussion, we decided to add it  to "target/2.4.0"

**Comment by karuppiah7890** [comment]
Thanks @AllForNothing !
