### ISSUE TITLE
Image pull issue - For images having tag names containing hyphens and capital letters

### ISSUE THREAD

**Issue by anupdhamale** [goharbor/harbor#15452]
Hello,

We are facing an issue with image pull . 

Harbor version - V 2.3.0
# docker pull harborprod.prod.com
Trying to pull repository parborprod.prod.com/myproject/https/apache/imagename:1100-RTM
unknown: artifact myproject/https/apache/imagename:1100-RTM not found
# 

This issue is identified images with tag names which includes Hyphen and Capital letters.
E.g. 1100-RTM

If we re-tag the same image with different name then able to pull the image.

Any pointers what could be the issue.

Thanks,
Anup

**Comment by stonezdj** [comment]
I could not reproduce your issue

**Comment by anupdhamale** [comment]
Thanks Stonezdj for your response.

If anyone came across similar issue please help.
