### ISSUE TITLE
Harbor-db keep restarting after restart VM or restart harbor services.

### ISSUE THREAD

**Issue by Ethan9909** [goharbor/harbor#15456]
What can we help you?
Hello experts:
      I'm new to harbor , today I install a Harbor follow the official guide but I found if I reboot the Harbor vm or restart Harbor services by docker-compose down -v && docker-compose up -d , the Harbor can't work, I checked the docker-compose I found harbor-db keep in restarting status, I check harbor logs found error like this:
==> /var/log/harbor/core.log <==
Aug 19 12:32:41 172.19.0.1 core[14352]: 2021-08-19T04:32:41Z [ERROR] [/common/utils/utils.go:106]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp: lookup postgresql on [240e:3b3:e90:69b0:3223:3ff:fec2:bb22]:53: dial udp [240e:3b3:e90:69b0:3223:3ff:fec2:bb22]:53: connect: network is unreachable
==> /var/log/harbor/postgresql.log <==
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: ls: cannot access '/var/lib/postgresql/data': Operation not permitted
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: initdb: error: directory "/var/lib/postgresql/data/pg13" exists but is not empty
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: If you want to create a new database system, either remove or empty
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: the directory "/var/lib/postgresql/data/pg13" or run initdb
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: with an argument other than "/var/lib/postgresql/data/pg13".
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: The files belonging to this database system will be owned by user "postgres".
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: This user must also own the server process.
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: 
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: The database cluster will be initialized with locales
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   COLLATE:  en_US.UTF-8
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   CTYPE:    en_US.UTF-8
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   MESSAGES: C
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   MONETARY: C
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   NUMERIC:  C
Aug 19 12:33:15 172.19.0.1 postgresql[14352]:   TIME:     C
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: The default text search configuration will be set to "english".
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: 
Aug 19 12:33:15 172.19.0.1 postgresql[14352]: Data page checksums are disabled.

How can I fix this issue? Many thanks for you help.

Harbor version is v2.3.1

**Comment by wy65701436** [comment]
hi, you can refer to this https://github.com/goharbor/harbor/issues/15464#issuecomment-909909558 to resolve the problem.

**Comment by Ethan9909** [comment]
Thanks.

**Comment by wy65701436** [comment]
@Ethan9909 did you resolve the problem?

**Comment by Ethan9909** [comment]
Hello wy65701436, I fixed it by downgraded docker version to 1.18.09,Thanks.

**Comment by wy65701436** [comment]
close it as fixed.

**Comment by clp01** [comment]
For me, this was resolved by updating all packages on the system before proceeding with the upgrade.

**Comment by MySunbing** [comment]
> 将 Docker 升级到 Docker 版本 20.10.8 后工作，内部版本 3967b7d

感谢，升级后已解决。
