### ISSUE TITLE
Harbor database postgresql 9.5 to 11.5 or 12 upgrade guideline requires.

### ISSUE THREAD

**Issue by thiyagu247** [goharbor/harbor#15458]
Hi Team,

We are using harbor V1.8 in Kubernetes (AWS EKS) with the external database running on AWS RDS (postgresql 9.6.15). AWS will deprecate the PostgreSQL 9.6 from January 2022 as per their official page. 

https://forums.aws.amazon.com/ann.jspa?annID=8499

Failure to migrate the database will automatically be upgraded to postgresql version 12.

We are planning to migrate the database before auto-upgrade happens. 

Will harbor support Postgresql version 11.5 or 12? can you please suggest whether harbor v1.8 supports a database other than 9.6 as the official document shows? 

If harbor supports database version 11.5 or 12 could please tell me from which harbor version?

**Comment by wy65701436** [comment]
From Harbor v2.3, it supports PG v13.3.

**Comment by thiyagu247** [comment]
> 
> 
> From Harbor v2.3, it supports PG v13.3.

Hey, thanks for the information. Any idea about V1.18 higher version of DB support?

**Comment by wy65701436** [comment]
We didn't test it on v1.8. What I can tell is that there was no big challenge at Harbor core side when I tried to upgrade 9.6 to 13.3, but the PG major version migration.

BTW, recommend you to upgrade to latest as v1.8 is too old to have a support.

**Comment by Entropy70** [comment]
Hi @wy65701436 , we are running harbor 2.2 and planning to migrate our external rds postgres to v14.4. Is it recommended to do so?
