### ISSUE TITLE
Ability to manage project group membership without being Harbor admin

### ISSUE THREAD

**Issue by pashcan** [goharbor/harbor#15451]
Harbor should have functionality to allow non-admin users or at least users with Project Admin role within a project they created to add Project Admin Group membership. Not having this ability creates a huge bottleneck for admin users who should be focusing on managing overall Harbor configurations instead of micromanaging hundreds of individual project.

**Comment by pashcan** [comment]
I created this functionality proposal because of maintainer's response in #15432.

**Comment by stonezdj** [comment]
Fixed by #15483

**Comment by pashcan** [comment]
Thank you @stonezdj!

**Comment by jcambronero** [comment]
Hi, we just ran into this same issue on v2.3.5.
Has this fix already been released and if so, in which release?

Thanks.
