### ISSUE TITLE
log rotation is not working in recent release

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#15468]
1. test with harbor 2.2.0 and harbor 2.3.0
2. change rotate size in `/home/harbor/harbor/common/config/log/logrotate.conf`
3. `docker exec -ti harbor-log bash` and check logs in /var/log/docker
4. script in /etc/cron.hourly/logrotate seems not run hourly
5. if run logrotate manually, logs can rotate

**Comment by dirk-olmes** [comment]
Just a me-too. I got informed by our ops team yesterday that the disk that stores the logs is full. I reviewe the generated logrotate.conf and it looks fine to me. So I'm suspecting something with cron in the harbor-logs container. I see crond running but didn't find any logs - neither on stdout nor inside the container.
