### ISSUE TITLE
tag retention policy running success and delete some tags in UI, but didn’t delete those tag directory in data directory

### ISSUE THREAD

**Issue by linyinli** [goharbor/harbor#15463]
**Expected behavior and actual behavior:**
Tag retention policy running success and delete some tags in UI, but didn’t delete those tag directory in data directory.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1. Push an image with three tags to harbor, in here, I use alpine 3.12 3.13 and 3.14;
2. Add a tag retention rule to retain latest pulled 2 images, like this: For the repositories matching **, retain the most recently pulled 2 artifacts with tags matching ** with untagged;
3. Run tag retention policy now;
4. 1 tag will delete in UI, but not delete in data directory, such this directory: /data/registry/docker/registry/v2/repositories/library/alpine/_manifests/tags/

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.1
- docker engine version: 20.10.7
- docker-compose version: 1.29.2

**Comment by linyinli** [comment]
The tag rentention running log:
2021-08-20T08:01:56Z [INFO] [/pkg/retention/job.go:83]: Run retention process.
 Repository: library/alpine 
 Rule Algorithm: or 
 Dry Run: false
2021-08-20T08:01:56Z [INFO] [/pkg/retention/job.go:98]: Load 3 candidates from repository library/alpine
2021-08-20T08:01:56Z [INFO] [/pkg/retention/job.go:201]: 
|                                 Digest                                  |     Tag     | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|-------------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:a9c28c813336ece5bb98b36af5b66209ed777a394f4f856c6e62267790883820 |        3.12 | image |        | 2021/08/20 08:00:21 |                     | 2021/08/20 08:00:21 | RETAIN    |
| sha256:be9bdc0ef8e96dbc428dc189b31e2e3b05523d96d12ed627c37aa2936653258c |        3.14 | image |        | 2021/08/20 07:04:05 |                     | 2021/08/20 07:04:05 | DEL       |
| sha256:def822f9851ca422481ec6fee59a9966f12b351c62ccb9aca841526ffaa9f748 | 3.13,latest | image |        | 2021/08/20 07:03:48 | 2021/08/20 07:00:53 | 2021/06/03 02:35:01 | RETAIN    |

**Comment by linyinli** [comment]
Check delete result:
# cd /data/registry/docker/registry/v2/repositories/library/alpine/_manifests/tags
# ls
3.12  3.13  3.14  latest

**Comment by stonezdj** [comment]
It is by docker/distribution design, these folders will keep even after GC.
