### ISSUE TITLE
After Harbor is reconfigured replication, only increments image can be replication but not replicated in full

### ISSUE THREAD

**Issue by unixomg** [goharbor/harbor#15467]
I have a Harbor of version 1.2.2. after I reconfigured the replicaiton task, I found that a repository with a large amount of data can only copy the image generated by the most recent increment, and cannot copy all the old data before. How should I solve this problem?  how make the old data can also be synchronized to my newly configured 1.2.2 backup machine.

**Comment by stonezdj** [comment]
Could you please upgrade to latest version of Harbor?

**Comment by unixomg** [comment]
Can't upgrade now due to historical reasons，other programs use the old version of the api。
