### ISSUE TITLE
Helm charts download 404 error

### ISSUE THREAD

**Issue by Areturn** [goharbor/harbor#15465]
![image](https://user-images.githubusercontent.com/25275823/130214520-e1d385fa-2e70-4ffa-8bf6-c9d6c0c50d4d.png)

The correct path should be:
![image](https://user-images.githubusercontent.com/25275823/130214652-9792d61d-b7ab-4861-a7b6-6138d83f701e.png)

/api/chartrepo/library/charts/apisix-custom-0.3.5.tgz   ×
/chartrepo/library/charts/apisix-custom-0.3.5.tgz    √

- helm harbor version: 1.7.1
- harbor version: v2.3.1-1058f330

**Comment by adityati** [comment]
@Areturn see #15228

**Comment by wy65701436** [comment]
dup with https://github.com/goharbor/harbor/issues/15228.
