### ISSUE TITLE
How to log out when connecting OIDC

### ISSUE THREAD

**Issue by dev-hana** [goharbor/harbor#15470]
Is there way to log out user when connecting OIDC? 
or Is there  have a session-out API?

**Comment by reasonerjt** [comment]
Currently, you need to go to the portal of the OIDC provider and logout.

**Comment by reasonerjt** [comment]
Closing as the question has been answered.

**Comment by dev-hana** [comment]
> Currently, you need to go to the portal of the OIDC provider and logout.

Thank you for anwered.
