### ISSUE TITLE
Concurrency block while creating/deleting objects

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#15474]
currently i'm trying to run harbor/perf in a cluster i have setup using harbor/helm.
The core pods are configured to be 3 and the connections are limited to 20/5 (max open/max idle)

I notice if running VU >> (pods * max connect) the core server stalls, blocking everything. If i check the DB i have many pending transaction connections in a blocked state. 
The DB server is not under stress, so this seems to be a problem with the DB factories.

To be honest, i still could not make the perf test work 1 single time. The script blocks always in **prepare** step  3 **scripts/data/03-project-member.js**.

Any pointers?

**Comment by stonezdj** [comment]
Could you please upgrade to version 2.3.x ?
