### ISSUE TITLE
API update proxy project

### ISSUE THREAD

**Issue by fragfutter** [goharbor/harbor#15477]
it is not possible to update proxy projects source registry

- create registry registry1.docker.hub (wich gets a registry_id, let's say 1)
- create registry registry2.docker.hub (wich gets a registry_id, let's say 2)
- create a project project1 as proxy cache of registry1

get project details via api

```curl -u admin -X get https://registry.example.com/api/v2.0/projects/project1```

it will hold a registry_id = 1

changing the proxy cache to  different url via webinterface is not possible

through the api i can do put the update, get a http 200 but nothing changes.

```curl -v -u admin  -X PUT "https://registry.example.com/api/v2.0/projects/project1" -d '{"registry_id": 2}'```

if i read the go code right, only cve and metadata can be updated 

https://github.com/goharbor/harbor/blob/b9228096dc4b5058cb7e2e80d7440e3421bf686c/src/server/v2.0/handler/project.go#L516

**Comment by stonezdj** [comment]
The PUT method doesn't support update the registry_id, but it only used by POST request
https://github.com/goharbor/harbor/blob/698c3364213365d6640ae35906fae1a1fd8d4771/api/v2.0/swagger.yaml#L6196
