### ISSUE TITLE
Clicking on Filter icon in a repo/project should focus on the text input

### ISSUE THREAD

**Issue by tompatib** [goharbor/harbor#15493]
**Is your feature request related to a problem? Please describe.**
In a repository when I click on the filter icon I'd expect that I can type the filter term immediately. Instead of this I need to click on the text box or press a tab. Same happens with the project filter.

![harbor](https://user-images.githubusercontent.com/16067575/130915699-353c82aa-7e02-4192-924a-e9e5e778c8b4.png)

**Describe the solution you'd like**
This should work the same way as the "Search Harbor..." option, there if I click on the magnifier icon I can type immediately. Although here the input box is visible.

My proposal is when I click on the magnifier icon, the focus changes to the Filter repositories/projects input after appearing.

**Additional context**
The "Search Harbor..." option already works like this.

**Comment by AllForNothing** [comment]
@tompatib Nice suggestion, let's add it to v2.4.0 plan
