### ISSUE TITLE
The home page shows incorrect storage usage 

### ISSUE THREAD

**Issue by the-papi** [goharbor/harbor#15503]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I don't think the calculation is correct. I have a 100 GB drive and Harbor tells me that I have already used 210 GiB. The actual size of my /data/registry is about 32 GiB.

I think this bug was introduced in #14772.

**Steps to reproduce the problem:**
Just push some images to harbor.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.2
- docker engine version: 19.03.13
- docker-compose version: 1.23.2

**Comment by wy65701436** [comment]
can you show the results of "du -sh /data/registry/docker/registry/v2/blobs/"?

**Comment by anantsaraswat** [comment]
@wy65701436  We have updated harbor to the latest version(2.3.0) and facing the same issue.

Please check the attached screenshot.

![df-h](https://user-images.githubusercontent.com/14076907/131536961-b86b7d30-6497-4a2f-93ff-49c579eab9b2.png)

So we have 393 GB disk attached for harbor data, where on the home page it's showing 992GB.

![home_page](https://user-images.githubusercontent.com/14076907/131537373-d6f9c32a-c26f-4715-a310-756489d27578.png)

if I check `Storage used` under any specific project, that seems correct, Only the home page is not showing correct details.

Also, earlier it used to show meter of disk usage, which seems missing in latest version.

**Comment by wy65701436** [comment]
@anantsaraswat can you help to show the results of "du -sh /opt/harbor/data/registry/docker/registry/v2/blobs/" in your env?
And can you help to show the result of this sql: `select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip');`?

**Comment by anantsaraswat** [comment]
@wy65701436 Please check the following output.

root@registry:~# du -sh /opt/harbor/data/registry/docker/registry/v2/blobs/
161G	/opt/harbor/data/registry/docker/registry/v2/blobs/

I am not sure how to run this sql, and I tried to connect the `harbor-db` container and following is the output.

`postgres [ / ]$ psql 
psql (13.3)
Type "help" for help.

postgres=# select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip');
ERROR:  relation "blob" does not exist
LINE 1: select sum(size) from blob Where content_type NOT IN ('appli...
`
Please let me know, how can I run the given sql.

**Comment by anantsaraswat** [comment]
Also, I have noticed that we have downloaded the 2.3.2 offline installer from the GitHub release page, whereas in harbor.cfg it says `_version: 2.3.0`

**Comment by wy65701436** [comment]
if you in the db container, execute the followings:

- psql -U postgres
- \c registry

then run the sql that I mentioned above.

**Comment by anantsaraswat** [comment]
Thanks @wy65701436  for guiding me.

```

postgres=# \c registry
You are now connected to database "registry" as user "postgres".
registry=# select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip');
      sum      
---------------
 1065915594982
(1 row)
```

**Comment by wy65701436** [comment]
@anantsaraswat could you please also provide the results of `select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip') and status in ('none');`? thanks.

**Comment by anantsaraswat** [comment]
Sure @wy65701436 

```
registry=# select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip') and status in ('none');
      sum      
---------------
 1070597746365
(1 row)
```

**Comment by wy65701436** [comment]
@anantsaraswat what kind of storage do you use? I cannot reproduce it in the local filesystem and S3.

**Comment by anantsaraswat** [comment]
@wy65701436 We are running a droplet on Digital Ocean and the data disk is a volume (Block storage) provided by Digital Ocean.

One thing I want to mention, we have increased the Digital Ocean volume size along with the Harbor upgrade.

I have taken the snapshot and I am able to replicate the same behaviour on droplets created from the snapshot.

**Comment by wy65701436** [comment]
@the-papi can you provide the info of the above sqls? If you still encounter this problem, since I cannot reproduce it at my side, I need more infor about the backend storage kind.

**Comment by the-papi** [comment]
@wy65701436 
```
$ du -sh /data/registry/docker/registry/v2/blobs/
41G	/data/registry/docker/registry/v2/blobs/
```

```
registry=# select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip');
     sum      
--------------
 235187199951
(1 row)
```

```
registry=# select sum(size) from blob Where content_type NOT IN ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip') and status in ('none');
     sum      
--------------
 235187199951
(1 row)
```

**Comment by anantsaraswat** [comment]
@wy65701436  @the-papi very strange we checked this morning and it's showing the correct size on our live instance.

Also, I want to share my findings here, we tried to add a new disk on a test instance and sync the data to the new disk, and it shows the correct size with the new disk.

So my doubt is the disk resize we did on digital ocean volume. 

Please let me know for any inputs that can help.

Thanks @wy65701436  :+1:

**Comment by wy65701436** [comment]
@the-papi what kind of storage are you using?

**Comment by the-papi** [comment]
@wy65701436 local filesystem

**Comment by DorianRoos** [comment]
Hi, i have the same issue.
i've update v2.0.2 to 2.3.2.

Since the update, the storage used on dashboard display my full size disk and not the used storage.

```
du -sh data/registry/docker/registry/v2/blobs/
29G	data/registry/docker/registry/v2/blobs/
```

Dashboard display 345.21GiB witch is my full size disk.
