### ISSUE TITLE
Can harbor support arm architecture？

### ISSUE THREAD

**Issue by googlebabaio** [goharbor/harbor#15502]
**Is your feature request related to the problem? Please describe.** 

When I want to deploy a harbor in the arm architecture, I am prompted that this architecture is not supported

**Describe the solution you want**
Supporting arm architecture is a trend, and hope that harbor can support it.

**Additional context**
When I execute the `prepare` command, the execution result is as follows:

```
Status: Downloaded newer image for goharbor/prepare:v2.3.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by chlins** [comment]
@googlebabaio You can watch the repo https://github.com/goharbor/harbor-arm.
