### ISSUE TITLE
API decodes URL-encoding wrongly

### ISSUE THREAD

**Issue by emranbm** [goharbor/harbor#15508]
**Expected behavior and actual behavior:**
When calling an API that includes special characters in its URL, they obviously need to be [URL-encoded](https://secure.n-able.com/webhelp/nc_9-1-0_so_en/content/sa_docs/api_level_integration/api_integration_urlencoding.html).  For example, if we want to get info of a docker image like `library/hello-world:latest` through the API, we should call something like `curl http://someharbor.com/api/v2.0/projects/{project_name}/repositories/library%2Fhello-world`, to avoid parsing `/` as a standard URL component.  
But, it seems the Harbor API decodes the URL and tries to parse the decoded URL again!  
i.e. calling the above `curl` command leads to an error like:
```
{
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "path /api/v2.0/projects/{project_name}/repositories/library/hello-world was not found"
    }
  ]
}
```
It's dealing with the `library/hello-world` as a *path*, not a unit of argument as `image_name`!

**Steps to reproduce the problem:**
Run `curl http://{harbor_host}/api/v2.0/projects/{project_name}/repositories/library%2Fhello-world`.  
**Note:** the `library%2Fhello-world` is the URL-encoded version of `library/hello-world`

**Workaround**
Just **double-encode** the URL to pass the first-level decoding!  
i.e.:  
- Encode `library/hello-world` to get `library%2dFhello-world`
- Encode `library%2Fhello-world` again to get `library%252Fhello-world`
- Now just curl with the double-encoded parameter: `curl http://{harbor_host}/api/v2.0/projects/{project_name}/repositories/library%252Fhello-world`  

**Versions:**
- harbor version: 2.3.1
- docker engine version: 2.10.8
- docker-compose version: 1.25.0

**Comment by ywk253100** [comment]
Double encode is needed just like the doc said https://github.com/goharbor/harbor/blob/master/api/v2.0/swagger.yaml#L5322
