### ISSUE TITLE
Scan harbor code find some code issues

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#15514]
What can we help you?

harbor branch: release-2.2.0

Scan harbor source code with sonarqube,  we find some code bugs from scan report, maybe need frontend developer confirm.

![image](https://user-images.githubusercontent.com/31262637/131322903-17fe5cd4-08b9-420a-9b0a-ce3590cd3e97.png)

**Comment by AllForNothing** [comment]
Not sure if the checking rules of this tool are suitable for Harbor UI code.
Currently, Harbor UI code is using this [tslint.json](https://github.com/goharbor/harbor/blob/master/src/portal/tslint.json) for ts code checking
