### ISSUE TITLE
Registry proxy list upstream tags

### ISSUE THREAD

**Issue by ErmakovDmitriy** [goharbor/harbor#15513]
Hi team,

I would like to ask you if it is expected behavior of Harbor (version v2.2.1).

I have a project `dockerhub` which is configured as Docker Proxy.
When I try to list tags of some repository through the proxy project, I see only tags which are in the cache:

```sh
$ skopeo list-tags docker://proxy.example.com/dockerhub/library/busybox
{
    "Repository": "proxy.example.com/dockerhub/library/busybox",
    "Tags": [
        "1.30-musl",
        "1.31",
        "1.31-musl",
        "1.32-musl",
        "1.33",
        "1.33-musl",
        "latest"
    ]
}
```

although, there are more published tags in Docker Hub:

```sh
$ skopeo list-tags docker://docker.io/library/busybox
{
    "Repository": "docker.io/library/busybox",
    "Tags": [
        "1",
#
# About a hundred lines were omitted here
#
        "ubuntu-14.04",
        "uclibc",
        "unstable",
        "unstable-glibc",
        "unstable-musl",
        "unstable-uclibc"
    ]
}
```

I understand, that the current logic is to show only cached images but, unfortunately, it breaks some tools which help to keep track on updates and patches (for example, [Keel](https://keel.sh), [Diun](https://crazymax.dev/diun/)).

I wonder if it is possible to add some flag to the Proxy Project settings which configures whether Harbor should list all tags or only tags of cached images.

I suppose that it is possible to cache tags metadata in Harbor database so as not to have too many requests to upstream container registry (and have the cache lifetime configurable for the whole project for simplicity).

**Comment by ExNG** [comment]
This was fixed in v2.5.
