### ISSUE TITLE
How to migrate from native Docker Registry V2 to Harbor V2?

### ISSUE THREAD

**Issue by zyayun** [goharbor/harbor#15525]
If inscribe.

- My Docker Registry already has about 2.5TB of data
- Migration through the retag method has been attempted,The mirror is lost during migration. Procedure
- How to migrate to Harbor in one piece?

**Comment by ChristianCiach** [comment]
Have a look at skopeo: https://github.com/containers/skopeo/

Especially `skopeo sync`: https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md

**Comment by Vad1mo** [comment]
you can use harbor for that, setup replication on harbor side to copy images from your old registry. 

This is what we normally do and it works great!
