### ISSUE TITLE
helm chart replication existing files

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#15522]
test version: harbor 2.3.1
1. I have a chart `certmanager` with 23 versions
![image](https://user-images.githubusercontent.com/188115/131606322-5c836220-a3b5-4e4b-9841-25229d68f442.png)
2. I create a replication job to push to another harbor
![image](https://user-images.githubusercontent.com/188115/131608658-7a9158e7-18ab-4cfa-b59d-85da01e394f0.png)
3. run job several times
![image](https://user-images.githubusercontent.com/188115/131608724-f77fe029-b640-4653-97b0-8b329d511b3f.png)
4. on remote harbor, there will be  much more than 23 versions appear
![image](https://user-images.githubusercontent.com/188115/131608782-9f2a552e-6826-4f29-95fa-59a07ccba011.png)
![image](https://user-images.githubusercontent.com/188115/131608815-8a8bfd04-fefd-41c7-b78c-339a5cef876a.png)

**Comment by stonezdj** [comment]
this issue is fixed https://github.com/helm/chartmuseum/pull/454

**Comment by bitsf** [comment]
one workaround to clean them is to delete the index file in /data/chart_storage, and cache in redis db num 3

**Comment by ninjadq** [comment]
the fix PR was merged in chartmuseum. we can patch it to chartmuseum in the harbor in 2.5
