### ISSUE TITLE
Cron expression cannot be changed in retention policies

### ISSUE THREAD

**Issue by p3t3rp3pp3r** [goharbor/harbor#15532]
Hi Team,

Harbor Version: v2.1.1
Enviroment: Kubernetes
Installation Type: Helm Chart

We are experiencing issues when we try to change the cron expression of a tag retention policy on specific projects, the error  detected in the core pod logs is the following:

`2021-09-01T16:03:53Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to unschedule the schedule 1: the execution 1 isn't in final status"}]}
/harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
/harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
/harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
/harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
/harbor/src/core/api/retention.go:225, github.com/goharbor/harbor/src/core/api.(*RetentionAPI).UpdateRetention
/usr/local/go/src/reflect/value.go:460, reflect.Value.call
/usr/local/go/src/reflect/value.go:321, reflect.Value.Call
/harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
/harbor/src/server/middleware/readonly/readonly.go:77, github.com/goharbor/harbor/src/server/middleware/readonly.MiddlewareWithConfig.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/security/security.go:63, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
/usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/artifactinfo/artifact_info.go:55, github.com/goharbor/harbor/src/server/middleware/artifactinfo.Middleware.func1.1
/usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
/harbor/src/lib/orm/orm.go:73, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
/harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2041, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1`

Is there a workaround for this issue?
At the moment we can't upgrade to a newer version.

Thanks,

**Comment by steven-zou** [comment]
Suggest upgrading to newer version 2.1.6+

**Comment by bitsf** [comment]
refer https://github.com/goharbor/harbor/issues/14405
