### ISSUE TITLE
A large number of connections and locks in postgresql

### ISSUE THREAD

**Issue by xammep4** [goharbor/harbor#15547]
harbor v2.2.3 deployed via helm;
- s3 external
- redis external
- postgresql external

Problem: a large number of postgresql db connections and locks(see the screenshot). The number increases linearly with increasing artifacts in the storage.

2 replications are configured: event based and scheduled (once every 30 seconds). When scheduled, the tasks do not have time to run and the next one starts, probably this creates a bunch of idle connections.

Please tell me how to get out of this situation? For us, harbor is a highload service, with a huge number of artifacts and a load in the future
![db_conn](https://user-images.githubusercontent.com/10144377/132222619-b00cb082-47e5-44ce-ad72-4a6456013559.jpg)

**Comment by heww** [comment]
Hi @xammep4, what tool do you use to monitor the Postgres? 

There is a [PR](https://github.com/goharbor/harbor/pull/15399) to reduce the locks for the DB, and I would like to verify that whether that PR resolves the problem.

**Comment by xammep4** [comment]
> Hi @xammep4, what tool do you use to monitor the Postgres?

This zabbix.
Postgres usage is external. We do not use postgres from the harbor delivery. And we use our deployment on hosts(for fault tolerance and reliability)

upd: The screenshots show a situation when there was a limit of 200 connections on postgres.

Now the settings have been changed to 1000. And it seems that this solved our problem. However, the question still remains, why are so many connections hanging in Idle mode.
And what does the maxIdleConn, maxOpenConn parameters affect in the harbor settings?
![image](https://user-images.githubusercontent.com/10144377/132334127-42091d5d-d52a-4356-bd18-13121bea76a0.png)

**Comment by chengyinwu-hash** [comment]
test。。。

**Comment by wy65701436** [comment]
@xammep4 there are some connections shouldn't be created, the [PR](https://github.com/goharbor/harbor/pull/15399 ) will reduce them.

**Comment by Vad1mo** [comment]
this [PR](https://github.com/goharbor/harbor/pull/15211) that landed in 2.3.1 should also help get the connections down.

**Comment by Vad1mo** [comment]
fixed by #15211
