### ISSUE TITLE
failed to connect to tcp://postgresql:5432 

### ISSUE THREAD

**Issue by littleant1111** [goharbor/harbor#15546]
按照文档操作：https://goharbor.io/docs/2.0.0/install-config/reconfigure-manage-lifecycle/
harbor登录界面提示：核心服务不可用。
日志文件：/var/log/harbor/core.log
[ERROR] [/common/utils/utils.go:106]: faild to connect to tcp://postgresql:5432, retry after 2 seconds : dial tcp: lookup postgresql on 127.0.11:53: server misbehaving
我使用的版本: v2.3.0

**Comment by littleant1111** [comment]
version: v2.3.0

**Comment by reasonerjt** [comment]
Env issue, name resolution failure due to DNS problem:
```
dial tcp: lookup postgresql on 127.0.11:53: server misbehaving
```

**Comment by littleant1111** [comment]
已经回滚到 v2.2.3 发现没出现问题了。 
重启、数据迁移均已正常。

**Comment by hanhyalex** [comment]
这种情况你看一下docker ps ，会发现pg数据库一直重启，这个问题就是数据库的存储文件不正确导致的，我上次也遇到了，如果把data文件夹换个位置，依然可以启动起来，但是就找不到之前的所有数据了。能保证不少数据并且保证还能启动的方法我还没找到

**Comment by lwx57280** [comment]
How to solve???
