### ISSUE TITLE
Reopening auto-closed issue about replication failure

### ISSUE THREAD

**Issue by gwkunze** [goharbor/harbor#15553]
Reopening #14245

Still happens in Harbor v2.3.2-6b6c21da

Original issue text:

**Expected behavior and actual behavior:**
I expect my replication to ECR to replicate all images pulled through my dockerhub pull-through proxy. But occassionally it didn't work. Looking at the replication logs I saw the docker image WAS replicated but without the appropriate tag, i.e. the image showed up in AWS ECR without any tags but with the correct digest.

**Steps to reproduce the problem:**
Seems to happen randomly, which is why I suspect some kind of race-condition, i.e. the replication starts off before the tag is applied to the image.

**Versions:**
- harbor version: 2.1.3

**Additional context:**

[harbor-replication.log](https://github.com/goharbor/harbor/files/5990528/harbor-replication.log)

**Comment by yogeek** [comment]
Not sure if it is linked but I have a similar issue :

- configured a proxy cache project in harbor called "docker-proxy"
- configured replication to ECR for this project
- `docker pull $HARBOR_URL/docker-proxy/library/hello-world:latest` => the image is then in harbor but not the `latest` tag, only the SHA1
- in ECR, the image is replicated but "untagged"... so I cannot pull from ECR

How can I do to have the tag for a proxy cached dockerhub image in both harbor and ECR please ?

**Comment by moisei** [comment]
Reproduced in 2.3.2 with the Dockerhub cache.
Just in case it can help somehow when I manually run image scan with Trivy, the tag is refreshing and appears properly.

**Comment by stonezdj** [comment]
Duplicate to #15591
