### ISSUE TITLE
Replication to alibaba cloud acr errror

### ISSUE THREAD

**Issue by spiritman1990** [goharbor/harbor#15569]
first in harbor, create one repo
![image](https://user-images.githubusercontent.com/14070910/132793685-b7c34281-1bc7-46fb-bb64-6bab5b577c28.png)

test is ok
column id is the alibaba cloud ram accout id
column secret is the alibaba cloud ram  accout  secret

when above is done, create one replication rule
![image](https://user-images.githubusercontent.com/14070910/132793898-3409a353-8b56-4ec6-b5ee-294d1437bc7d.png)

![image](https://user-images.githubusercontent.com/14070910/132794007-7318fc7a-f0d1-4925-ab5c-f71404821bd9.png)

**Versions:**

- harbor version: [2.3.2]
- docker engine version: [20.10.8]
- docker-compose version: [1.18.0]

**Comment by bitsf** [comment]
can you `docker login registry.cn-shanghai.aliyuncs.com` with that AK successfully, and push image ?

**Comment by spiritman1990** [comment]
> can you `docker login registry.cn-shanghai.aliyuncs.com` with that AK successfully, and push image ?

yes, it works correctly

**Comment by spiritman1990** [comment]
> you can create AK with your ram account, not using password. The Aliyun SDK doesn't allow using password to auth
> 
> https://github.com/goharbor/harbor/blob/7b39bab0f3b87035397a23d193ce8ab4c9e80b25/src/pkg/reg/adapter/aliacr/auth.go#L47
thus, replication to aliacr is kind of a broken feature, even auth succeed,not working on replication

**Comment by QiuToo** [comment]
> 

你好！我在添加阿里云ACR规则的时候，“测试连接”操作失败，方便告诉我你的阿里云ACR是怎么配置的吗？
访问ID我填的是ACR的“命名空间名称”，访问密码是“访问凭证”设置的密码，还需要做其它的操作吗？
![image](https://user-images.githubusercontent.com/88759374/167757063-7f44d903-2ad6-4320-b927-eba8d7916fd0.png)

**Comment by chlins** [comment]
@QiuToo The aliyun adapter needs to use the AccessKey as authorization, you can generate that refer to https://ram.console.aliyun.com/manage/ak.
