### ISSUE TITLE
Harbor doesn't support changing auth mode from ldap_auth to db_auth in portal

### ISSUE THREAD

**Issue by yunkunrao** [goharbor/harbor#15561]
What can we help you?

Currently, harbor doesn't support changing auth mode from ldap_auth to db_auth in portal. According to FAQ and issue #13831 , admin need to delete synced users from ldap manually. I guess it's designed deliberately for user accounts security. But from product perspective, maybe it doesn't make sense. It's on the one hand. On the other hand, admin need to login the servers and update the db. It's not convenient and not safe either. 

So is it possible to enable admin to be able to delete synced accounts in portal and switched auth mode?

**Comment by reckless-huang** [comment]
It's really a bad setting， could harbor change it
