### ISSUE TITLE
Postgres Version 9.6 EOL 

### ISSUE THREAD

**Issue by SysAdmLS** [goharbor/harbor#15579]
What can we help you?
Hi, i was wondering if there are any plans to upgrade the used Postgres Server version used by harbor.

Current used version seems to be 9.6 which has its EOL in november this year:
https://www.postgresql.org/support/versioning/

**Comment by wy65701436** [comment]
Hi, you could get the answer from https://github.com/goharbor/harbor/releases/tag/v2.3.0.

**Comment by SysAdmLS** [comment]
@wy65701436 Oh didn't see that. I've looked in the docs and it said 9.6 in the core components section.

https://goharbor.io/docs/2.3.0/install-config/
