### ISSUE TITLE
Login to Web works, but not into registry

### ISSUE THREAD

**Issue by MrMEEE** [goharbor/harbor#15570]
After setting up a new Harbor installation (version 10.2.11).. I can login to the web-interface, but not through the registry:

DEBU[0001] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.aperta.dk:5000 
DEBU[0001] GET https://registry.aperta.dk:5000/v2/      
DEBU[0001] Ping https://registry.aperta.dk:5000/v2/ status 401 
DEBU[0001] GET https://registry.aperta.dk:5000/v2/      
DEBU[0001] error logging into "registry.aperta.dk:5000": unable to retrieve auth token: invalid username/password: unauthorized: authentication required 
Error: error logging into "registry.aperta.dk:5000": invalid username/password

Log on registryctl is saying:

2021-09-10T13:01:24Z [ERROR] [/registryctl/handlers/handler.go:73]: failed to authenticate request: invalid authorization credential 
10.130.0.1 - - [10/Sep/2021:13:01:24 +0000] "GET /v2/ HTTP/1.1" 401 13 2021-09-10T13:01:24Z [ERROR] [/registryctl/handlers/handler.go:73]: failed to authenticate request: invalid authorization credential 
10.130.0.1 - - [10/Sep/2021:13:01:24 +0000] "GET /v2/ HTTP/1.1" 401 13 
10.128.2.86 - - [10/Sep/2021:13:01:25 +0000] "GET /api/health HTTP/1.1" 200 9 2021-09-10T13:01:27Z [ERROR] [/registryctl/handlers/handler.go:73]: failed to authenticate request: invalid authorization credential

Installed using helm charts and type: loadbalancer

**Comment by steven-zou** [comment]
Please double confirm your harbor version `10.2.11`, the latest Harbor is 2.3.x.

And also, please double-check your related configurations. It seems the issue mentioned here may be caused by misconfiguration.
