### ISSUE TITLE
No tags in dockerhub proxy cache for 'library' images  

### ISSUE THREAD

**Issue by yogeek** [goharbor/harbor#15571]
**Expected behavior and actual behavior:**
I created a dockerhub proxy cache project, and pulled an image from a single level repository (a `library` prefixed one) : `docker pull library/hello-world:latest`
Expected : the image is present in harbor proxy cache project with the tag `latest`
Actual behavior : the image is present in harbor proxy cache project but without any tag 

**Versions:**

- harbor version: [v2.2.2]
- docker engine version: [20.10.7]

**Additionnal context**
We found this because we set up a replication to an ECR and we had `ImagePullBackOff`errors in our cluster because all the `library` images were not been able to be pulled with the tag we wanted.

**Comment by steven-zou** [comment]
duplicated with #15560

**Comment by yogeek** [comment]
@steven-zou I am not sure it is the same problem actually...
Even without the replication, the tag are not present on any image pulled from 'library' into the cache.
The other ticket is about replication only no?

**Comment by stonezdj** [comment]
duplicate to #15591
