### ISSUE TITLE
Migrate issue from really old harbor v1.10.1 to v2.3.2  

### ISSUE THREAD

**Issue by kuja53** [goharbor/harbor#15585]
What can we help you?
Hi, I recently migrate really old harbor v1.10.1 to latest v2.3.2. Harbor runs on kubernetes.

Everything was really smooth. I dump postgresql db, restore it to new clean db. Core service made a migration of scheme to current version. But after few weeks of running new version I see this in core service log:

`2021-09-13T15:41:44Z [ERROR] [/core/auth/authenticator.go:264]: Failed to get user from DB, username: <user1>, error: user <user1> not found`

But funny is that this user is in `harbor_user` table. I try to delete this user directly from `harbor_user`. Core service recreate that user immediately and still throws the error in log.

I wonder if someone experienced this in tha past or what is the right mitigation of this. Everything works, all users (admin account and LDAP users) are able to login.

Thank you for answer.

**Comment by bitsf** [comment]
I think you are using LDAP, and the user is auto created in db.
cc @reasonerjt , it seems the error log is confusing here.

**Comment by stonezdj** [comment]
It is a noise in the log, you could ignore it.

**Comment by kuja53** [comment]
@stonezdj I know that this message is some kind of noise. I experience this in previous versions since 1.6. But currently this specific case cause unreadability of the core log for future debug. And it consumes a lot of RAM currently. But never mind I will wait for future improvement because I try nearly everything what is technically possible :) Even to play with log levels.

**Comment by kuja53** [comment]
@bitsf Yes, we are using LDAP. So users are generated upon request. I also consider to upgrade authentication to OIDC but currently I have no room to perform it in reasonable time on our production harbors.
