### ISSUE TITLE
misleading documentation about authentication

### ISSUE THREAD

**Issue by LU-386** [goharbor/harbor#15592]
Hey,

the project looks awesome and, even with the pretty limited installscipt, i got it up and running.
The containers are running and healthy, the web ui behind traefik as reverse proxy works fine aswell.

I've even forwarded 4443 from the firewall to the docker-host and added the port in docker-compose.yml

But running `docker login harbor.domain.tld` or `docker login https://harbor.domain.tld` with password or token (Issue #6159) fails with (same behavior with podman on Fedora 34).

`Error response from daemon: Get "https://harbor.domain.tld/v2/": unauthorized: authentication required`

I've red what i could find on google and in the documentation (correct version) but nothing helped yet.

What am i doing wrong here?
Are there any plans for a clean "docker-compose"- style deployment instead of a bunch of external scripts?

hosts tested: VMware PhotonOS, Fedora 34 WS
clients tested: docker 20.10.8 and podman 3.3.1
harbor version v2.3.2-6b6c21da

**Comment by LU-386** [comment]
harbor version v2.3.2-6b6c21da

**Comment by bitsf** [comment]
can you login from UI ?
Can you try `docker restart nginx` ?

**Comment by LU-386** [comment]
login from ui works, restarting takes some about 30s nginx but did't help

**Comment by bitsf** [comment]
@stonezdj please help on this

**Comment by LU-386** [comment]
i found out that the only thing that works is "docker login localhost" ...

this software looks great, isn't it possible to provide a container without some of those badly behaving installer scripts with common available containers?
