### ISSUE TITLE
Memory leaks with image scans since Harbor 2.3

### ISSUE THREAD

**Issue by okin** [goharbor/harbor#15595]
Since Harbor 2.3 active daily image scanning leaks memory.

I have two Harbor instances with Harbor 2.3 (one on 2.3.2 and the other 2.3.0). Both are running daily image scans with Trivy. Whenever an daily image scan runs it leaks memory. The problems appeared with Harbor 2.3.0.
Monitoring makes it pretty obvious. The ditches appear whenever Harbor has been restarted.
![grafik](https://user-images.githubusercontent.com/445491/133393500-3581d6cf-999b-4a68-bd90-df978a4c03c2.png)

To verify the behaviour I disabled image scanning on one instance over the weekend (blue box). If image scans aren't running there isn't a problem.
![grafik](https://user-images.githubusercontent.com/445491/133393776-fab991bd-699f-4ebe-ba27-0f383a7e4a66.png)

**Comment by heww** [comment]
Can you help to check which component takes the memory, harbor-core, harbor-db, jobservice or trivy?

**Comment by okin** [comment]
@heww we extended memory monitoring to the mentioned containers and I will report back once I've got some more data.

We have 3k to 4k images depending on the instance. Both instances are configured to run the vulnerability scans daily.

**Comment by okin** [comment]
> Can you help to check which component takes the memory, harbor-core, harbor-db, jobservice, or trivy?

@heww Hopefully you find this useful:

<details>

# host with Harbor 2.3.0

Overall memory usage on the host:
![grafik](https://user-images.githubusercontent.com/445491/135226678-f870b3d5-b14d-4343-8c86-32752601503f.png)

Usage for harbor-core:
![grafik](https://user-images.githubusercontent.com/445491/135226965-b24e32e6-31c5-428f-a348-237f651abe20.png)

Usage for harbor-db:
![grafik](https://user-images.githubusercontent.com/445491/135227139-fc32e0dd-138a-46d7-ba9b-c068d24cb3f1.png)

Usage for harbor-jobservice:
![grafik](https://user-images.githubusercontent.com/445491/135227277-6eca12d2-b26c-4089-ada8-54360014ea4b.png)

Usage for trivy-adapter:
![grafik](https://user-images.githubusercontent.com/445491/135227419-8226b1bd-0d88-44e9-b6c7-864c7ffc5652.png)


# Host with Harbor 2.3.2
![grafik](https://user-images.githubusercontent.com/445491/135227649-4fc33470-44f5-489c-a602-84e3ddc3efd0.png)

While the RAM usage did not increase as much as before reporting there is a trend visible but it is stretched out a lot further:
![grafik](https://user-images.githubusercontent.com/445491/135227870-0c9093f2-7839-4dc8-987b-0f7e1e75a51d.png)

While I don't have graphs I have some `docker stats` to compare and the usage increased the most at harbor-db followed by habor-core.
</details>

Is there anything else I can help with?

**Comment by heww** [comment]
According to your graph of the metrics, there isn't a memory leak in the trivy adapter.

The Postgres' memory doesn't reduce anymore, we need more investigation for this problem. cc @chlins
