### ISSUE TITLE
2.2.4 build-package error

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#15590]
2.2.4 File conflicts occurred when building trivy-adapter base images, resulting in failure to build

error message:
file /usr/bin/file from install of file-5.30-2.ph2.x86_64 conflicts with file from package toybox-0.7.3-6.ph2.x86_64

conflict command:
tdnf install -y rpm

**Comment by bitsf** [comment]
maybe we don't  need to install that `rpm` package

**Comment by YangJiao0817** [comment]
@bitsf Already resolved in this pr https://github.com/goharbor/harbor/pull/15593
