### ISSUE TITLE
Configuring a Filesystem Storage Backend inconsistency 

### ISSUE THREAD

**Issue by SysAdmLS** [goharbor/harbor#15597]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Configure an filesystem Storage Backend as described here:
https://goharbor.io/docs/2.3.0/install-config/configure-yml-file/

sample from harbor.yml:
storage_service:
  filesystem:
    rootdirectory: /root/daten
    maxthreads: 100

In my understanding from the docs, this should have changed the registry storage destination to the "/root/daten" of the host machine running the registry container.

Instead it changes the storage destination INSIDE THE CONTAINER, with the /etc/registry/config.yml file.

Expected behaviour would be that the registry volume declaration in the docker-compose.yml gets changed to the desired new storage destination:
  
    volumes:
      - /data/registry:/storage:z 
->
   ```
 volumes:
      - /root/daten:/storage:z
```

**Steps to reproduce the problem:**
define a local fileystem storage backend in harbor.yml

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1]

**Comment by bitsf** [comment]
you should change line `data_volume: /data`

**Comment by bitsf** [comment]
you should move all data to new location

**Comment by geewhizsmith** [comment]
Hello, I had the same or a very similar problem, and have an explanation and steps to make it work.

The "install.sh" and "prepare" or the templates they use do not account for the
setting of a "rootdirectory", and so no "volume" is set in "docker-compose.yml"
to enable the setting to work.

To make it work with my setup I did this...

    1) configure "rootdirectory" to point to my mounted NFS storage:
        harbor.yml
            storage_service:
              filesystem:
                rootdirectory: /mnt/storage/harbor-registry
                maxthreads: 100

    2) run the installation script and shut the installation down (it was running but could not store files)
        sudo ./install.sh
        sudo docker compose down --volumes

    3) add configuration for the volume (and make a backup of the file in case somebody ran the base "install.sh")
        sudo vi docker-compose.yml
            services:
              registry:
                volumes:
                  - /mnt/storage/harbor-registry:/mnt/storage/harbor-registry
        sudo cp docker-compose.yml docker-compose.yml-EDITED_BACKUP

    4) and start it again
        sudo docker compose up --detach

And in my README for the service, I put a warning on the restart notes:

    diff docker-compose.yml docker-compose.yml-EDITED_BACKUP || echo "WARNING:  docker-compose.yml does is different from docker-compose.yml-EDITED_BACKUP"
    sudo docker compose down --volumes
    sudo docker compose up --detach

I am going to open a new issue, but I wanted to drop this comment on a number of
threads where other people might find it while tring to do a fix of their own.

**Comment by SysAdmLS** [comment]
> rootdirectory: /root/daten

Thnaks for sharing, my solution was to just maunally configure the host directory in the docker-compose file for the registry volumes. So its my nfs shared Volume gets mounted it.

My point was, that the harbor.yml options

storage_service:
filesystem:
rootdirectory: /root/daten

are basically useless because they only change the mount points INSIDE the container but having no effect on the host destination in the volume declaration in docker-compose.yml. Forcing me to always manually edit these before upgrading per hand.

**Comment by ptv1p3r** [comment]
can you please give the example of your harbor.yml and docker compose so i can see how you did it? i also want harbor to remain on the /data and the registry to go to my unraid nfs share

**Comment by ptv1p3r** [comment]
bor

> Hello, I had the same or a very similar problem, and have an explanation and steps to make it work.
> 
> The "install.sh" and "prepare" or the templates they use do not account for the setting of a "rootdirectory", and so no "volume" is set in "docker-compose.yml" to enable the setting to work.
> 
> To make it work with my setup I did this...
> 
> ```
> 1) configure "rootdirectory" to point to my mounted NFS storage:
>     harbor.yml
>         storage_service:
>           filesystem:
>             rootdirectory: /mnt/storage/harbor-registry
>             maxthreads: 100
> 
> 2) run the installation script and shut the installation down (it was running but could not store files)
>     sudo ./install.sh
>     sudo docker compose down --volumes
> 
> 3) add configuration for the volume (and make a backup of the file in case somebody ran the base "install.sh")
>     sudo vi docker-compose.yml
>         services:
>           registry:
>             volumes:
>               - /mnt/storage/harbor-registry:/mnt/storage/harbor-registry
>     sudo cp docker-compose.yml docker-compose.yml-EDITED_BACKUP
> 
> 4) and start it again
>     sudo docker compose up --detach
> ```
> 
> And in my README for the service, I put a warning on the restart notes:
> 
> ```
> diff docker-compose.yml docker-compose.yml-EDITED_BACKUP || echo "WARNING:  docker-compose.yml does is different from docker-compose.yml-EDITED_BACKUP"
> sudo docker compose down --volumes
> sudo docker compose up --detach
> ```
> 
> I am going to open a new issue, but I wanted to drop this comment on a number of threads where other people might find it while tring to do a fix of their own.

this wroks as described, now i have harbor on host in /data and registry on nfs nas share ...

**Comment by SysAdmLS** [comment]
> bor
> 
> > Hello, I had the same or a very similar problem, and have an explanation and steps to make it work.
> > The "install.sh" and "prepare" or the templates they use do not account for the setting of a "rootdirectory", and so no "volume" is set in "docker-compose.yml" to enable the setting to work.
> > To make it work with my setup I did this...
> > ```
> > 1) configure "rootdirectory" to point to my mounted NFS storage:
> >     harbor.yml
> >         storage_service:
> >           filesystem:
> >             rootdirectory: /mnt/storage/harbor-registry
> >             maxthreads: 100
> > 
> > 2) run the installation script and shut the installation down (it was running but could not store files)
> >     sudo ./install.sh
> >     sudo docker compose down --volumes
> > 
> > 3) add configuration for the volume (and make a backup of the file in case somebody ran the base "install.sh")
> >     sudo vi docker-compose.yml
> >         services:
> >           registry:
> >             volumes:
> >               - /mnt/storage/harbor-registry:/mnt/storage/harbor-registry
> >     sudo cp docker-compose.yml docker-compose.yml-EDITED_BACKUP
> > 
> > 4) and start it again
> >     sudo docker compose up --detach
> > ```
> > 
> > 
> >     
> >   
> > And in my README for the service, I put a warning on the restart notes:
> > ```
> > diff docker-compose.yml docker-compose.yml-EDITED_BACKUP || echo "WARNING:  docker-compose.yml does is different from docker-compose.yml-EDITED_BACKUP"
> > sudo docker compose down --volumes
> > sudo docker compose up --detach
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am going to open a new issue, but I wanted to drop this comment on a number of threads where other people might find it while tring to do a fix of their own.
> 
> this wroks as described, now i have harbor on host in /data and registry on nfs nas share ...

you dont need to run the installer. Simply calling ./prepare (--with-trivy in case you use it) will create the docker compose file.
In that just edit the /mnt/storage/harbor-registry volume mountpoint to your desired path.
Atm there should be 2 containers using this mountpount, registry and registryctl.
