### ISSUE TITLE
Failed to create replication rule which syncing imaes from acr

### ISSUE THREAD

**Issue by yunkunrao** [goharbor/harbor#15607]
If you are reporting a problem, please make sure the following information are provided:
**Expected behavior and actual behavior:**
Currently when I created replicate rule which syncing images from acr to local harbor cluster, 404 error occured.

**Steps to reproduce the problem:**
1. create acr registry endpoint
2. create replication rule with pull-based mode

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.3.2
- docker engine version: 19.03.13
- docker-compose version: 1.29.2

**Additional context:*
![截屏2021-09-17 下午4 31 32](https://user-images.githubusercontent.com/20353538/133751480-5fbad0a5-e377-48d4-b48c-9196741d5cbb.png)

![截屏2021-09-17 下午4 30 33](https://user-images.githubusercontent.com/20353538/133751276-8586b318-2c04-47df-9240-3660cf9bcd5a.png)

**Comment by bitsf** [comment]
it looks like the `Provider` you selected is not correct

**Comment by yunkunrao** [comment]
Got it, thanks.
