### ISSUE TITLE
Authentication error in Docker login for ldap 

### ISSUE THREAD

**Issue by mohitsharma-in** [goharbor/harbor#15605]
Hello Team,

some users are reporting login failure when doing docker login. But subsequent attempt with same creds works without any change is username or password.

`Error: unauthorized: unauthorized to access repository: project/myfunc-python, action: push: unauthorized to access repository: project/myfunc-python, action: push`

Error log from harbor core 

``2021-09-16T10:17:03Z [ERROR] [/server/middleware/security/basic_auth.go:40][requestID="813c1987-9d87-4d39-996a-99b95156c081"]: failed to authenticate username: Failed to authenticate user, due to error 'LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839'
[16/Sep/2021:10:17:03 +0000]:192.168.53.0 - "GET /service/token?account=username&scope=repository%project%2Fmyfunc-python%3Apush%2Cpull&service=harbor-registry HTTP/1.1" 200 945 "-" "docker/20.10.7 go/go1.13.15 git-commit/b0f5bc3 kernel/5.10.25-linuxkit os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" 1.585 1.585 .
``

Let us know if further details are required.

**Comment by bitsf** [comment]
it looks like just LDAP returning authentication error, are you sure the credentials are correct ?

**Comment by mohit94614** [comment]
Our users are reporting for 2 out of 10 login attempts are getting failed

**Comment by bitsf** [comment]
Do you mean 2 of 10 users using same LDAP reporting issue, or 1 user login 10 times but fails 2 times ?

**Comment by mohit94614** [comment]
1 user login 10 times but fails 2 times and this is happening for multiple users

**Comment by stonezdj** [comment]
It should be some setting in the LDAP server that results in the issue. the error message LDAP Result Code 49 "Invalid Credentials" is from the LDAP server. this issue can't be fixed in Harbor.

**Comment by stonezdj** [comment]
For security reasons, Harbor locks the account for 1.5s if a client tries to log in with an invalid credential. The client which has the valid credential fails to log in during the lock interval.
If there are many clients try to log in with the same account with an invalid credential, the failed changes are increased.
