### ISSUE TITLE
OIDC Client Secret must be Base64 Encoded?

### ISSUE THREAD

**Issue by damonearp** [goharbor/harbor#15603]
##### Affected Versions
* 2.2.3
* 2.3.2 
 
##### Issue
Core stores the OIDC Client Secret as it is entered on the web form, but Base 64 decodes it before using in the `Authorization: BASIC ...` header of the /token endpoint.

I'm unsure if this is intended, but https://goharbor.io/docs/2.3.0/administration/configure-authentication/oidc-auth/ doesn't mention this requirement. But my poor search skills cannot find any issues on this, which means I'm doing something wrong, I'm failing to locate other issues, or I'm the only one trying this. I have a hard time believing the latter. Could this be a misconfiguration? 

I used a simple request logging web server emulating the OIDC endpoints. And saw the Authorization header contained binary data `Authorization: Basic base64(<ID>:<BINARY>)`. After issuing an `update properties set v='base64(v)' where k='oidc_client_secret'` I was finally able to login to harbor using OIDC.

**Comment by damonearp** [comment]
This is a side effect when the `KEY_PATH=<FILE>` doesn't point to a file with *exactly* 16 bytes. I guess harbor-core fails to initialize the AES key?? and then stores the secret in the db in cleartext. And if it's in the db in cleartext harbor-core assumes it's base64 encoded.

After I made this report, I continued working with harbor and noticed the secret key leading to errors in the logs. Now that I corrected this, the webui and OIDC is working as expected. 

Why is the secret key, configured with `KEY_PATH`, limited to 16 characters/bytes? If this is being used as a Symmetric Key why isn't it treated as a seed for pbkdf2? Using this algorithm users could feed in any amount of data and a key of the correct size will be generated.

**Comment by reasonerjt** [comment]
@damonearp 

As for the CLI secret question.  This is to make sure the flow work for CLI like docker, you input your cli secret in `password` field in `docker login`.  
It's not documented b/c we don't expect a regular user to use the OIDC CLI secret in http request directly.

As for the symmetric key issue, you may open another issue to elaborate on the alternative way to handle it, but we should be very careful in order not to introduce break changes.

**Comment by damonearp** [comment]
It would be beneficial to users is if when `KEY_PATH`  is misconfigured (ex file is 17 bytes long due to `\n`), core will error when it wants to store a field encrypted instead of returning success after storing the cleartext in the db.

As for the pbkdf2 question I'll open another issue. Thanks
