### ISSUE TITLE
ERROR: manifest for goharbor/harbor-log:v2.4.0-build.889 not found

### ISSUE THREAD

**Issue by liamhao** [goharbor/harbor#15609]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
```bash
wget https://codeload.github.com/goharbor/harbor/tar.gz/refs/tags/v2.3.2 harbor.tar.gz
tar -zxvf harbor.tar.gz
cd /root/harbor-2.3.2/make
./install.sh
```

**Versions:**
- harbor version: [2.3.2]
- docker engine version: [18.06.3-ce]
- docker-compose version: [1.18.0]

**Additional context:**
```bash
[Step 4]: starting Harbor ...
Pulling log (goharbor/harbor-log:v2.4.0-build.889)...
ERROR: manifest for goharbor/harbor-log:v2.4.0-build.889 not found
```
![image](https://user-images.githubusercontent.com/31812811/133773545-8cd51fe7-2252-4ce4-8ac6-7b49b84f2494.png)
![image](https://user-images.githubusercontent.com/31812811/133773589-16c2514b-9b18-4710-a157-f4296a49a668.png)

**Comment by paulohleal** [comment]
Hi,

In my machine it worked fine. The only thing different I spoted is that my harbor distribution did not have the "make" folder.
Also the link I downloaded was:  https://github.com/goharbor/harbor/releases/download/v2.3.2/harbor-online-installer-v2.3.2.tgz

**Comment by liamhao** [comment]
> Hi,
> 
> In my machine it worked fine. The only thing different I spoted is that my harbor distribution did not have the "make" folder.
> Also the link I downloaded was: https://github.com/goharbor/harbor/releases/download/v2.3.2/harbor-online-installer-v2.3.2.tgz

# OHHHHH! Thanks!
### It works after follw your description. but, where is the page of download link you found? I did not found it.

![image](https://user-images.githubusercontent.com/31812811/133892805-e5a2ae53-19d6-438c-b524-c8fb2bffc808.png)

**Comment by bitsf** [comment]
I just wonder where you find the url of `codeload.github.com` ?

**Comment by liamhao** [comment]
> I just wonder where you find the url of `codeload.github.com` ?

emmm...

![image](https://user-images.githubusercontent.com/31812811/134285923-5c9349f5-8c4d-4f22-b80d-6bdee148aac4.png)

![image](https://user-images.githubusercontent.com/31812811/134286058-62f56d65-c766-4af3-aa39-ccc5e9f0c877.png)
