### ISSUE TITLE
 synchronize the harbor image of version 1.5 to 2.0.5 error

### ISSUE THREAD

**Issue by zhangfu266** [goharbor/harbor#15604]
When I want to synchronize the harbor image of version 1.5 to 2.0.5 through rule synchronization, I will be prompted with an error.
What else can I do besides upgrading 1.5?

The information is as follows:

Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: 2021-09-17T02:04:14Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"7ba4898fca1723d15dbab807", "hook_url":"http://ui:8080/service/notifications/jobs/replication/89167"}
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: 2021-09-17T02:04:14Z [INFO] Job incoming: IMAGE_TRANSFER:7ba4898fca1723d15dbab807
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: 2021-09-17T02:04:14Z [ERROR] [service_logger.go:63]: Job 'IMAGE_TRANSFER:7ba4898fca1723d15dbab807' exit with error: http error: code 404, message <!DOCTYPE HTML>
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: <html>
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: <head>
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: <meta charset="utf-8">
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: <title>404 - Page Not Found</title>
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]: <style>
Sep 17 10:04:14 172.20.0.1 jobservice[2993116]:

**Comment by wy65701436** [comment]
Harbor doesn't support cross version replication, you have to ensure the source and target share the same version.
