### ISSUE TITLE
[UI] No way to scroll through retention runs result pages

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#15602]
**Expected behaviour and actual behaviour:**
The retention run results view shows 5 repos (per each run), if there are more then 5 repos the UI has no navigation buttons to scroll through the pages, so we can only see the results of the first 5 repos.

I'd expect to see  navigation buttons to scroll through the pages and also a way to set the page size.

![image](https://user-images.githubusercontent.com/61992380/133616625-3cfbbf93-0731-472d-a385-ad32eb3d1b34.png)

**Steps to reproduce the problem:**
1. have more then 5 repos in a project
2. create a retention rule and run it
3. see the result of the run and notice that only the first 5 repos can be observed and there's no navigation buttons to go to next page or define the page size

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.2
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**
N/A

**Comment by AllForNothing** [comment]
This is a duplicated issue with #15488
