### ISSUE TITLE
Arbitrary login problem

### ISSUE THREAD

**Issue by song-liang** [goharbor/harbor#15612]
Open burp, click proxy option match and replace to add and automatically replace the response header 401 status code with 200 status code
![image](https://user-images.githubusercontent.com/22864620/133868547-fa95687c-00ff-4af9-a8e1-c20c760f83a3.png)

You can directly access the website URL
![截图_选择区域_20210918095958](https://user-images.githubusercontent.com/22864620/133868620-3c345029-deb5-4a4a-85b3-fc9e3fd1f176.png)

**Comment by bitsf** [comment]
these are public repositories, you can also search them on the top search bar too.

**Comment by reasonerjt** [comment]
@song-liang 

@bitsf is correct, even you update the response code you don't see data that you don't have access to.

**Comment by song-liang** [comment]
@reasonerjt  Public should be visible only after logging in, but I can browse without logging in

**Comment by reasonerjt** [comment]
```
Public should be visible only after logging in
```
Not true.  you can get it by calling API without credential, and this is by design.
