### ISSUE TITLE
Artifact list viewable without authentication

### ISSUE THREAD

**Issue by ajchiarello** [goharbor/harbor#15619]
**Expected behavior and actual behavior:**
When going to the list of artifacts for a particular repository in Harbor, you do not need to authenticate in order to view the list of artifacts and tags. For example, you can go directly to https://demo.goharbor.io/harbor/projects/3/repositories/app without logging in and view the contents.

I would expect unauthenticated users to be directed to the login page, which is what happens with other pages in Harbor (like https://demo.goharbor.io/harbor/projects/3/repositories).

**Steps to reproduce the problem:**

Without authenticating, go directly to the address for a repository in harbor.

**Versions:**

I'm running Harbor 2.3.0, installed on Kubernetes via the Bitnami Helm Chart, but since the problem shows up on the Demo server, I suspect it is broader than that.

**Comment by Vad1mo** [comment]
This is only true for public project, which makes sense as this is the whole point of public projects.
try for example, this: https://8gears.container-registry.com/harbor/projects/2/repositories/aws-infra
and this: https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions

FYI: the first is private, and the second URL is a public repo, hence you can see it.
