### ISSUE TITLE
Use admin and Harbor12345 to Login, respone 401 Unauthorized

### ISSUE THREAD

**Issue by shannonflying** [goharbor/harbor#15614]
**Harbor Version** : V2.3.2

### **Opreate 1 : Login on web page**

![image](https://user-images.githubusercontent.com/34269214/133880797-8ff59e64-1cf9-4599-9808-15d8a3ab386b.png)

### **Opreate 2: Login on docker**

[root@localhost harbor]# docker login 192.168.145.188
Username: admin
Password:
Error response from daemon: Get http://192.168.145.188/v2/: unauthorized: authentication required
[root@localhost harbor]#

### **Opreate 3 : exec curl command**

[root@localhost harbor]# curl -v -u admin:Harbor12345 "http://192.168.145.188/api/v2.0/configurations"
* About to connect() to 192.168.145.188 port 80 (#0)
*   Trying 192.168.145.188...
* Connected to 192.168.145.188 (192.168.145.188) port 80 (#0)
* Server auth using Basic with user 'admin'
> GET /api/v2.0/configurations HTTP/1.1
> Authorization: Basic YWRtaW46SGFyYm9yMTIzNDU=
> User-Agent: curl/7.29.0
> Host: 192.168.145.188
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: nginx
< Date: Sat, 18 Sep 2021 07:35:04 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 62
< Connection: keep-alive
< Set-Cookie: sid=f1a90642f39eaab0e7b4abdde930b5cf; Path=/; HttpOnly
< X-Request-Id: 549c47b7-2e7a-47b7-a7eb-b28ab46838ef
<
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
* Connection #0 to host 192.168.145.188 left intact

### **Opreate 4 : View Log in core**

![image](https://user-images.githubusercontent.com/34269214/133880866-81f24e9e-8e28-4e9f-8799-67b1a9d6d0a4.png)

**My Harbor.yml file**:

![image](https://user-images.githubusercontent.com/34269214/133881059-e5082a5c-3f07-4e55-8c53-11514fcabda6.png)

**Every one are up in docker ps**

![image](https://user-images.githubusercontent.com/34269214/133881795-8ffe49ae-7ec7-4d1c-9840-d5017b58d0d7.png)

Pls Help!!!

**Comment by bitsf** [comment]
This should not happen, maybe you can try `docker restart nginx`, or fresh install harbor again.
And you should change `hostname` in harbor.yml to 192.168.145.188, and need not use external_url if you don't have proxy in front.

**Comment by bitsf** [comment]
if login response is `CSRF token invalid`, try use `clear site data`
![image](https://user-images.githubusercontent.com/188115/134336665-21e6de80-d333-4e68-bd39-5d0ae4054df3.png)

**Comment by shannonflying** [comment]
@bitsf thanks for you first!

I udpate **daemon.json** in docker config and **hostname :192.168.145.188** in harbor.yml file ，As you said
then  execute：
`
./prepare
systemctl restart docker
docker-compose down -v
docker-compose up -d
`

Also the site data is cleared at chorme Application Storage,

Still login failed in docker and web page,  Look at the picture below:

**daemon.json**
![image](https://user-images.githubusercontent.com/34269214/134440585-a72fb265-8898-498d-86a6-5392be807cd5.png)

**harbor.yml file**
![image](https://user-images.githubusercontent.com/34269214/134440837-2c7f3377-7f70-4a1e-ba40-5a7679ed5a8f.png)

**harbor in docker**
![image](https://user-images.githubusercontent.com/34269214/134440876-7b31a777-bc4e-43ce-88bf-947138465aff.png)

**login in  docker** 
![image](https://user-images.githubusercontent.com/34269214/134440987-ea5c3dc0-b74e-41f5-8c5e-77eb38d24b85.png)

**Comment by shannonflying** [comment]
I began to suspect that there was a problem with my account and password，
But i confirm that I use admin and harbor12345  to login Harbor

**Comment by shannonflying** [comment]
@bitsf  thank you

I solved the problem，
I found the data is  old db,
Maybe I updated my password a long time ago and mounted it to the same folder when I reinstalled it, so now I switch the data directory and it works

### Change **/data**
// The default data volume
> data_volume: /data
### To **/home/my/harbor/harbor/data**
// The default data volume
> data_volume: /home/my/harbor/harbor/data

#### Its working now, I will close issue

**Comment by shannonflying** [comment]
thanks  every one
