### ISSUE TITLE
Add rules for not matching tags in replications

### ISSUE THREAD

**Issue by beltran-rubo** [goharbor/harbor#15610]
**Is your feature request related to a problem? Please describe.**
At Bitnami we support [several rolling tags](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/):

```
3.4.6-debian-9-r24, 3, 3.4.6, latest


The latest tag always points to the latest revision of the Redmine image.
The 3 tag is a rolling tag that always points to the latest revision of Redmine 3.x.
The 3.4.6 tag is a rolling tag that points to the latest revision of Redmine 3.4.6. It will be updated with different revisions or daily releases but only for Redmine 3.4.6.
```

Replicating the whole catalog to update those tags will require to overwrite all images (lot of TB).

**Describe the solution you'd like**
Ideally we can set 2 kind of replication:
- All container images (without overwriting them)
- All tags that do not include "-r" that is the pattern we use for immutable tags (overwriting them)

**Describe the main design/architecture of your solution**
A rule that allows to not include certain patterns for the replication

**Describe the development plan you've considered**
n/a

**Additional context**
n/a

**Comment by bitsf** [comment]
if the sha256 blobs are already existed, it would not replicate the data actually, so it should takes TB data to copy only at first time.

**Comment by bitsf** [comment]
in the coming release v2.4.0, we support exclude tags/lables
