### ISSUE TITLE
Failed to get OIDC user info for user, id: 1, error: unknown: oidc info for user 1 not found

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#15617]
This error message is constantly displayed when the local admin account logs in when OIDC is enabled.

**Expected behavior and actual behavior:**
This message should not be displayed as the user with id == 1 is the local admin and should ne be  present within the OIDC provider pool.

```sh
2021-09-19T20:30:39Z [WARNING] [/core/controllers/base.go:72]: Failed to get OIDC user info for user, id: 1, error: unknown: oidc info for user 1 not found
```

**Steps to reproduce the problem:**
- Enable OIDC 
- Login as Admin

**Versions:**
- harbor version: 2.3.1

**Comment by stonezdj** [comment]
Noise in the log, you could ignore it.

**Comment by Vad1mo** [comment]
> Noise and hunting don’t go together.

You know it; After a few hours of investigation, I know it now too. Do we want others to teach the same thing?
