### ISSUE TITLE
sample image in document of robot account is not updated after version 2.3

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#15628]
https://goharbor.io/docs/2.3.0/administration/robot-accounts/
![image](https://user-images.githubusercontent.com/188115/134280519-24bb86ab-12ca-4999-a075-87c614800414.png)

the sample image lost `Robot Name Prefix` part

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/website/pull/266
