### ISSUE TITLE
Forbidden / Unknown error / not found since Harbor 2.3.2

### ISSUE THREAD

**Issue by matgn** [goharbor/harbor#15620]
**Expected behavior and actual behavior:**
I have a project called ui-core (it's an old project), and this project contains 2 repositories with images. 
Since 2.3.2, I can see this project with web interface, but listing repositories is "forbidden". 
Same problem with API (forbidden).
It's impossible to delete it (because it contains some repo), and you can create a project with the same name /!\ 

**Steps to reproduce the problem:**
It's difficult to reproduce. I have many projects and it's the only one with this problem. 

**Versions:**

- harbor version: 2.3.2
- docker engine version: 20.10.8
- docker-compose version: 1.22.0

**Additional context:**

- Logs :
`[ERROR] [/server/v2.0/handler/base.go:88]: failed to get project ui-core : project ui-core not found`
- API (get repo of project): 
`{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "forbidden"
    }
  ]
}
`

- Screenshot WEB UI
![Harbor](https://user-images.githubusercontent.com/22295201/134131410-e8ec4528-3188-479e-a6d0-9a88d07e9c33.png)

**Comment by bitsf** [comment]
did you login into to the UI ?

**Comment by matgn** [comment]
> did you login into to the UI ?

Yes ! On the interface, I can see my project in the list but I get a forbidden on "repositories", "Helm charts"," p2p-provider" and "Logs"

**Comment by bitsf** [comment]
maybe we need to check the database.
`docker exec -it harbor-db psql registry`
`select * from project;`
`select * from repository;`

**Comment by matgn** [comment]
> maybe we need to check the database.
> `docker exec -it harbor-db psql registry`
> `select * from project;`
> `select * from repository;`

I found nothing strange... Repositories exist and so do the project... 

> select * from project;
 project_id | owner_id |              name               |       creation_time        |        update_time         | deleted | registry_id 
------------+----------+---------------------------------+----------------------------+----------------------------+---------+-------------      
         58 |       12 | ui-core                         | 2020-02-13 09:09:11        | 2020-02-13 09:09:11        | f       | 

> select * from repository WHERE repository.project_id = 58;  
 repository_id |               name               | project_id | description | pull_count | star_count |       creation_time        |        update_time         
---------------+----------------------------------+------------+-------------+------------+------------+----------------------------+----------------------------
           223 | ui-core/alpha                    |         58 |             |        351 |          0 | 2020-02-13 10:18:21.288773 | 2021-09-14 12:37:16.129784
           224 | ui-core/beta                     |         58 |             |       1797 |          0 | 2020-02-13 10:19:43.186733 | 2021-09-12 00:14:37.786734

**Comment by bitsf** [comment]
from the error log, it comes from https://github.com/goharbor/harbor/blob/6b6c21da213a77efa80951cfa8170f3276a18ab7/src/pkg/project/dao/dao.go#L150

but quite strange, the data seems correct.
can you double check if `select * from project where name='ui-core' and deleted=false;` works ?

**Comment by matgn** [comment]
> from the error log, it comes from
> 
> https://github.com/goharbor/harbor/blob/6b6c21da213a77efa80951cfa8170f3276a18ab7/src/pkg/project/dao/dao.go#L150
> 
> but quite strange, the data seems correct.
> can you double check if `select * from project where name='ui-core' and deleted=false;` works ?

I performed some queries and it's frightening ... 

> registry=# select * from project where project_id='58';     
>  project_id | owner_id |  name   |    creation_time    |     update_time     | deleted | registry_id 
> ------------+----------+---------+---------------------+---------------------+---------+-------------
>          58 |       12 | ui-core | 2020-02-13 09:09:11 | 2020-02-13 09:09:11 | f       |            
> (1 row)
> 
> registry=# select * from project where name='ui-core'; 
>  project_id | owner_id | name | creation_time | update_time | deleted | registry_id 
> ------------+----------+------+---------------+-------------+---------+-------------
> (0 rows)
> 
> registry=# select * from project where name='ui-core' and deleted=false; 
>  project_id | owner_id | name | creation_time | update_time | deleted | registry_id 
> ------------+----------+------+---------------+-------------+---------+-------------
> (0 rows)

> registry=# select * from project where project_id='58' and deleted=false;
>  project_id | owner_id |  name   |    creation_time    |     update_time     | deleted | registry_id 
> ------------+----------+---------+---------------------+---------------------+---------+-------------
>          58 |       12 | ui-core | 2020-02-13 09:09:11 | 2020-02-13 09:09:11 | f       |            
> (1 row)

**Comment by vgeorgik** [comment]
I am experiencing the same issue after upgrade from v2.2.2 to v2.3.3 or v2.3.3.
I have 5 projects but one is reporting as forbidden after the upgrade.
Also in the logs i am getting the same error:
[ERROR] [/server/v2.0/handler/base.go:88]: failed to get project dockerhub_proxy: project dockerhub_proxy not found

i have rolled back the update using a vmware snapshot

**Comment by vgeorgik** [comment]
I have upgraded from v2.2.2 to v2.2.3 and didn't have any issues. Will try to update to v2.3.1 and report back

**Comment by matgn** [comment]
> I have upgraded from v2.2.2 to v2.2.3 and didn't have any issues. Will try to update to v2.3.1 and report back
> 
> I forget to mentioned that i am doing offline installer with the following components: notary, trivy and chartmuseum

I tried to upgrade 2.3.2 -> 2.3.3 : still have the problem (no surprise) ...

**Comment by vgeorgik** [comment]
Upgrading to v2.3.1 from v2.2.3 still the same problem. The project is reported as forbidden although it exists in the postgredb.

**Comment by matgn** [comment]
The error occurred on another old project. I noticed it when I pushed images.
Strangely, this project was working properly after upgrading... I do not have a clue.

**Comment by bitsf** [comment]
I think there's something non-printable around the project name `ui-core`.
Maybe you can check `select length(name),encode(name::bytea,'hex'),* from project;`
And you can run `update project set name='ui-core' where id=58;` to fix

**Comment by bitsf** [comment]
if anyone else met this again, please use `encode(name::bytea, 'hex')` to show what ever the extra char it is

**Comment by bitsf** [comment]
well, I think this maybe some database trick, I really have no idea why you can fix with two command
```
registry=# update project set name='tmp_name' where project_id=73;
registry=# update project set name='my_project' where project_id=73;
```
but failed with one command
```
registry=# update project set name='my_project' where project_id=73;
```

maybe postgres db upgrade to v13.3 in harbor 2.3.x

**Comment by stonezdj** [comment]
It is the unique index on the repository table corrupt and caused this issue.  
Solving this issue by following workaround
1. Find the duplicated repository name
```
select * from (select name, count(*) cnt from repository group by name) a where a.cnt > 1
```
2. Find the ID of duplicated repository and get the new_id and old_id
```
select repository_id, name, creation_time from repository where name like ‘%prometheus/test-job%’ 
```
3. Update  the tag and artifact point to the new repository id

```
update artifact set repository_id = <new_id> where repository_id = <old_id>
update tag set repository_id = <new_id> where repository_id = <old_id>
delete from repository where repository_id = <old_id>
```

4. After all duplicated repositories are removed, no row return in following query

```
select * from (select name, count(*) cnt from repository group by name) a where a.cnt > 1
```

5. Then reindex the table

```
REINDEX TABLE repository;
```

7. Verify the 404 error is eliminated.

**Comment by shoeffner** [comment]
> I tried to encode manually and I get the same. But, I have the same issue with this project..

I also have the same issue and to verify the bytes are the same, I also used:
```sql
select encode('the-hub'::bytea, 'hex');
```
which gives the same output as 
```sql
select encode(name::bytea, 'hex') from project where project_id='37';
```
(of course, I used our project name)still, I have to select using `LIKE` and not `=` – and it does not matter where I put the %, so for example:
```sql
select * from project where name LIKE 'the%hub';
select * from project where name LIKE '%the-hub';
select * from project where name LIKE 'the-hub%';
```
would all return the same results, while 
```sql
select * from project where name LIKE 'the-hub';
select * from project where name='the-hub';
```
would not return any results.

Re-indexing the table as @stonezdj recommended worked for us:
```
REINDEX TABLE project;
```

**Comment by matgn** [comment]
Still have the problem with a project, but this time : can't workaround... 
Harbor : `v2.3.5`
Tried : reindex / changing name / no duplicated repository name

**Comment by stonezdj** [comment]
@matgn the error message 
```
Http failure response for https://<URL>/api/v2.0/projects/matomo/repositories/matomo/artifacts?with_tag=false&with_scan_overview=true&with_label=true&page_size=15&page=1: 0 Unknown Error
```
It is not a Harbor logs, could you please upload the related Harbor core log?
