### ISSUE TITLE
Interrogation Service - Vuln response v1.0 overrides v1.1

### ISSUE THREAD

**Issue by skrech** [goharbor/harbor#15623]
Hello,

I've noticed that if one Interrogation Service reports support for both of these mime types from its `/metadata` endpoint:
`application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0`
`application/vnd.security.vulnerability.report; version=1.1`

Then Harbor makes two requests - one for v1.0 and another one for 1.1. First, it seems redundant to request for v1.0 data when v1.1 data is a superset of the v1.0 data. Second, it seems that v1.0 takes precedence over v1.1 data, which means that even though CVSS scores are returned from the Interrogation Service, they don't appear in the UI.

**Versions:**
- Harbor version: 2.3
- Running in Kubernetes, default config

**Comment by bitsf** [comment]
@danielpacak what do you suggest about this ?

**Comment by danielpacak** [comment]
We allowed scanners to return multiple mime types for backward compatibility, especially to install newer scanners with older Harbor deployments. However, this is problematic as pointed out by @skrech. At the same time we wanted to introduce canonical names for the vulnerability report mime type, which is somehow independent of Harbor data model.

To fix this problem we could:
1. Require scanner adapters to return only one mime type that corresponds to vulnerability report displayed in the UI. Release notes should indicate that it breaks compatibility with previous versions of Harbor.
2. Patch Harbor service to skip fetching report with legacy mime type `application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0` if scanner declared also `application/vnd.security.vulnerability.report; version=1.1`.

To quick fix this problem for the default Trivy scanner I'd release new version of the scanner adapter that only declares `application/vnd.security.vulnerability.report; version=1.1` mime type and bump it up in Harbor Makefile. WDYT? @heww @prahaladdarkin @steven-zou

**Comment by prahaladdarkin** [comment]
@danielpacak  IMHO, we should patch the Harbor implementation to pull only the latest  vulnerability MIME type if the scanner returns both the vulnerability MIME types (Option 2).
This is the only way to address any backward compatibility issues. @steven-zou  @heww  your pointers or alternate approaches are welcome.

**Comment by heww** [comment]
Hi @skrech, if you want the report of version 1.1, please request the API with `application/vnd.security.vulnerability.report; version=1.1` for `X-Accept-Vulnerabilities` header.

**Comment by heww** [comment]
```
To quick fix this problem for the default Trivy scanner I'd release a new version of the scanner adapter that only declares application/vnd.security.vulnerability.report; version=1.1 mime type and bump it up in Harbor Makefile. WDYT?
```
I think it's ok to release a new version for trivy to resolve this problem.

BTW, it's by design that harbor will generate and save all scan reports which are supported by the scanner. In this issue, it's just a coincidence that the scan report version 1.1 is compatible with scan report version 1.0.
