### ISSUE TITLE
the version 1.8.0 not supported, make sure the version in input file above 1.8.0

### ISSUE THREAD

**Issue by Chenless** [goharbor/harbor#15630]
The upgrade failed from 1.8.2 to 2.3.2. Procedure

![image](https://user-images.githubusercontent.com/5126487/134280558-701d911e-ec35-441c-a75f-a39c386a8187.png)

the version 1.8.0 not supported, make sure the version in input file above 1.8.0

**Comment by bitsf** [comment]
upgrade to 1.9,1.10 one by one

**Comment by 1314cc** [comment]
It was great, but I upgraded to 2.3.2 and found that the data, users, repository, etc. were not present on the page. But 2.2.3 is good

**Comment by bitsf** [comment]
can you clarify what you mean not present on the page ? and error logs ?
