### ISSUE TITLE
harbor api, trivy, questions

### ISSUE THREAD

**Issue by C1ph3R-s** [goharbor/harbor#15635]
Hi,

I have tow questions about the api.

@projects
I have to query all project via api, but unfortunately it got back for me just some of them, do you have any suggestions for that? (all project are in public state)

Query:
`curl -u user:pass -s -H 'Content-type: application/json' -H "limit: 100000" -X GET "https://harbor.mycompany.local/api/projects" | jq -r '.[] | .name' `

@vulnerabilites, trivy
Trivy has been installed on harbor host, so I would like to create a query for the findings of scans.
Would you be so kind and suggest for me a query for that purpose, because It did not work:

`​/projects​/{project_name}​/repositories​/{repository_name}​/artifacts​/{reference}​/scan​/{report_id}​/log`

Thanks,

**Comment by bitsf** [comment]
I think you may also query from the `harbor-db`
`docker exec -it harbor-db bash`
`psql registr`
`select * from vulnerability_record;`

**Comment by C1ph3R-s** [comment]
Thanks, @bitsf but I have to use api, I haven't got access for the db.

**Comment by heww** [comment]
For the first question, the list projects API doesn't support fetching all projects by one call, only 100 projects will be returned at one call. Please using pagination to fetching all the projects.

**Comment by C1ph3R-s** [comment]
100 would be more than enough for me, but unfortunately, it gave back for me only 10 pieces of project.

**Comment by heww** [comment]
> 100 would be more than enough for me, but unfortunately, it gave back for me only 10 pieces of project.

Please have a look at the `Harbor API V2.0` in the portal of harbor, the parameter is named `page_size` in query string.

![image](https://user-images.githubusercontent.com/5634205/134912366-d3cbe6b6-beae-4add-8573-5d1b99f16a26.png)

**Comment by C1ph3R-s** [comment]
@heww thanks :)
