### ISSUE TITLE
harbor auth mode can not modify

### ISSUE THREAD

**Issue by svenlu** [goharbor/harbor#15640]
认证模式无法修改
![wecom-temp-b21f0630d33c2e59298aa5a5e7995c92](https://user-images.githubusercontent.com/5123378/134449033-958e31d0-9f76-46e4-b9d1-dad7d69a6600.png)

账户里只有一个admin账号
![image](https://user-images.githubusercontent.com/5123378/134449090-0887b8a3-2391-4de1-acec-ff7bd73e4f54.png)

**Comment by stonezdj** [comment]
What is your Harbor version? it could be that you have removed the anonymous user and caused this issue.

https://github.com/goharbor/harbor/blob/a11a70d941019ad779f04f9e4d904100c03abdca/src/common/dao/config.go#L27-L33

Harbor 2.3.1 already fixed this issue.

**Comment by svenlu** [comment]
> What is your Harbor version? it could be that you have removed the anonymous user and caused this issue. Manually create an anonymous user could workaround this issue.
> 
> <img alt="Screen Shot 2021-09-27 at 6 33 30 PM" width="1358" src="https://user-images.githubusercontent.com/2696760/134892748-9232c490-21fa-4b28-bd88-a56137337e3f.png">
> 
> https://github.com/goharbor/harbor/blob/a11a70d941019ad779f04f9e4d904100c03abdca/src/common/dao/config.go#L27-L33
> 
> Harbor 2.3.1 already fixed this issue.
hi, My harbor version is 2.1.5

**Comment by svenlu** [comment]
create  an anonymous user fix it , thank you
