### ISSUE TITLE
core hang when a lot request coming at the same time

### ISSUE THREAD

**Issue by Jarvis-Zhou** [goharbor/harbor#15649]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
call delete or other api 500+ at once
expected: success
actual: core hang

- harbor version: 2.1.0

**Additional context:**

we find core create a transcaction in middleware (transaction.Middleware(dbTxSkippers...)). but in dao, we always use globalOrm to create / delete from database. this can case transaction in transaction. when db connect is not enough and a lot request comming at the same time, the core will hang as all the request go pass transaction.Middleware(dbTxSkippers...) and then not enough db connect to deal with the next dao request.

**Comment by wy65701436** [comment]
We have fix several DB connection & transtion issues, you can try with the latest build with the scenario.

**Comment by Jarvis-Zhou** [comment]
but in the code, i also can find some where that use WithTransaction after  transaction.Middleware(dbTxSkippers...) , will this still case transtion issue ?

**Comment by Jarvis-Zhou** [comment]
why we need transaction.Middleware(dbTxSkippers...)  every requst ?

**Comment by bitsf** [comment]
please wait and try release 2.3.3 or 2.4.0

**Comment by heww** [comment]
Closed as this is fixed in harbor 2.3.3+
