### ISSUE TITLE
Improve the database migration process

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#15642]
Currently, the `harbor-core` container will trigger `go-migrator` to do the database migration every time it starts, if the migration fails the process will exit with a non-zero status code.
The way `go-migrator` works, is to set the schema to `dirty` status, run the SQL, and remove the `dirty` flag.  
When Harbor was deployed on top of K8S it becomes a problem if the migration process fails, the schema will remain in `dirty` status and we see `harbor-core` keep restarting.  This situation is confusing and makes it difficult to find the root cause of why the migration failed.

To make improvements with relatively low cost, I suggest we can add `migration` mode to `harbor-core` so that the process kicks off the migration process, and when the process is successful it exits.  We can use it as a `initContainer` so the failure is more explicit and easy to debug.  And we don't need to ship a new image as the code will still be in `harbor-core`

**Comment by stonezdj** [comment]
Fixed by #16272
