### ISSUE TITLE
Redis TLS Support

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#15645]
What can we help you?

Redis support TLS communication now, could harbor support the TLS related setting when connect to redis?

**Comment by bitsf** [comment]
this need be supported by upstream dependency library first, like beego / trivy / chartmuseum / distribution .

**Comment by danielzhanghl** [comment]
hi, @bitsf  
another solution for upstream projects:
if that is not redis+tls ready, harbor could use stunnel side car container as the bridge, like / trivy / chartmuseum / distribution, that belong harbor helm chart new enhancement, refer to https://redis.com/blog/stunnel-secure-redis-ssl/ on how stunnel could be used, if need, I could open ticket to harbor helm chart for that part.


and harbor itself could enhance to support redis+tls, and core/jobservice/exporter could connect to redis directly.

**Comment by danielzhanghl** [comment]
and right now, container repo support redis over TLS already,
========
https://github.com/distribution/distribution/blob/main/docs/configuration.md
redis
Additionally, you can control TLS connection settings with the tls subsection (in-transit encryption).

**Comment by danielzhanghl** [comment]
looks there are same request on https://github.com/goharbor/harbor/issues/13223

**Comment by danielzhanghl** [comment]
close this duplicated one.
