### ISSUE TITLE
Proxy cache failed when the manifest exist in harbor db but its blob missing in storage

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#15654]
Sometimes, users might see the manifest already exist in the proxy cache project, but the pull command fails with manifest unknown,  there is no blob for this manifest in the storage, users have to delete the manifest to workaround it.
Proxy cache should provide a way to self-recover for these issues.

**Comment by reasonerjt** [comment]
Harbor is designed in a way that if a manifest is not written to storage the record should NEVER be inserted into the DB.

I think we need to investigate if such inconsistency really exists.  For example, did the user write any script to do clean up and removed the blobs by mistake?  Or if there's any problem in his setting in storage?
