### ISSUE TITLE
Add `KEY_SEED_PATH=` to replace `KEY_PATH`

### ISSUE THREAD

**Issue by damonearp** [goharbor/harbor#15651]
**Is your feature request related to a problem? Please describe.**
When diagnosing  #15603 I found that I had misconfigured `KEY_PATH=` because I had missed the 16 byte requirement.  But I also wonder how many people set this value to only ascii chars? I screwed up a second time when I set it to a string with a `\n` at the end.

**Describe the solution you'd like**
The 16 byte requirement makes me suspect this is used for a Symmetric Key. Under this assumption I believe it would be better if this field is treated as an input into the [PBKDF2 Key Generation Algorithm](https://en.wikipedia.org/wiki/PBKDF2). 

Two benefits over the existing `KEY_PATH`
1. Users can put however many bytes they want into the file, the algorithm will generate the 16 bytes needed internally
2. If users only provide only printable chars (0x20-0x80), the generated key can still use bytes outside of this range, therefore user input can still provide good random keys.

**Describe the main design/architecture of your solution**

To maintain backward compatibility
1. If `KEY_PATH` is defined use it
2. else look for `KEY_SEED_PATH` and generate the key to use

**Describe the development plan you've considered**
None at this time.

**Additional context**
None at this time.

**Edit** - s/KEY_FILE/KEY_PATH/

**Comment by Vad1mo** [comment]
harbor is full of people failing to start harbor because of secret key size issues. It would be great if we could fix that. Thank you for your research @damonearp

**Comment by bitsf** [comment]
I just wonder why are you editing this file manually, it should be auto generated when install harbor ?

**Comment by damonearp** [comment]
> I just wonder why are you editing this file manually, it should be auto generated when install harbor ? Is it reasonable ?

I am integrating Harbor into our infrastructure. Not only do we want it working with our existing services, we also want to understand its topology and how it communicates. We don't want a black box. Therefore I have manually setup harbor on our cluster without the installer. I think the installer is a great solution for lots of groups, it's just not going to be a universal one.
