### ISSUE TITLE
Harbor Portal is showing scanner database updated time in old date although the clair db is updated till today.

### ISSUE THREAD

**Issue by SoaadMahmoud** [goharbor/harbor#15664]
Harbor portal is showing scanner database updated time in old date "attached screenshot"although the clair db is updated till today. so how is this date is updated in harbor portal?
note that we are on latest version of harbor 2.3.2 and we are using clair as external scanner 

<img width="304" alt="db harbor" src="https://user-images.githubusercontent.com/37635397/134672192-008c059c-c470-4614-8f12-8d1188de63ac.PNG">

clair db:
=======
clair=> select * from  vulnerability_notification order by created_at desc;

  id   |                 name                 |          created_at           | notified_at | deleted_at | old_vulnerabi

lity_id | new_vulnerability_id

-------+--------------------------------------+-------------------------------+-------------+------------+--------------

--------+----------------------

 28480 | 8da075b9-df41-423d-b62c-3b804fe7e3d7 | 2021-09-21 08:31:17.25221+02  |             |            |

        |               248871

**Comment by danielpacak** [comment]
Harbor scanner adapter for Clair reads the DB update timestamp from the`keyvalue` database https://github.com/goharbor/harbor-scanner-clair/blob/v1.1.1/pkg/clair/client.go#L110
