### ISSUE TITLE
failed to install harbor(v2.3.1)

### ISSUE THREAD

**Issue by pashenmebaojinwo** [goharbor/harbor#15667]
Expected behavior: successful harbor installation;
Actual behavior: failed to install harbor;

Note: stopping existing Harbor instance ...
Stopping redis         ... done
Stopping harbor-portal ... done
Stopping harbor-db     ... done
Stopping harbor-log    ... done
Removing redis         ... done
Removing registry      ... done
Removing registryctl   ... done
Removing harbor-portal ... done
Removing harbor-db     ... done
Removing harbor-log    ... done
Removing network harbor_harbor

[Step 4]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
Creating harbor-log ... done
Creating harbor-db  ... 
Creating registry      ... error
Creating registryctl ... 
Creating redis       ... 
Creating harbor-portal ... 
Creating registryctl   ... error
Creating harbor-db     ... doneallowed

Creating redis         ... done
Creating harbor-portal ... done

ERROR: for registry  Cannot start service registry: error setting label on mount source '/usr/local/docker/harbor/common/config/registry': relabeling content in /usr is not allowed

ERROR: for registryctl  Cannot start service registryctl: error setting label on mount source '/usr/local/docker/harbor/common/config/registry': relabeling content in /usr is not allowed
ERROR: Encountered errors while bringing up the project.

[root@localhost harbor]# docker -v
Docker version 19.03.13, build 4484c46
[root@localhost harbor]# docker-compose -v
docker-compose version 1.29.1, build c34c88b2

**Comment by bitsf** [comment]
it seems the folder permission is not changable for `/usr/local/docker/harbor/common/config/registry`
try install harbor in some other folder, like /root/harbor
you just need to define the `data` folder in harbor.yml to some other bigger storage

**Comment by bitsf** [comment]
what os are you using?
maybe selinux issue ?
