### ISSUE TITLE
Harbor sometimes duplicates Helm Charts instead of overriding them

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#15666]
**Expected behavior and actual behavior:**
I performed some tests with Helm charts and because of this I pushed multiple charts with the same version to the Helm repository. I expected that Harbor will override existing files with new ones. But sometimes, for reasons not known to me, a duplicate entries are created instead. Later this span multiple issues.
![duplicates](https://user-images.githubusercontent.com/20277750/134685573-54be1efb-d702-4d18-bdd5-bbc4cc811ca3.PNG)

When I remove one of this Helm Chart, also a chart file is removed and because of this I cannot delete the rest of the entries because of 404 error. 
`fail to delete chart version: remove /chart_storage/projectname/chartname-3.1.31-SNAPSHOT.tgz: no such file or directory`
Also, there is problem with project removal. I cannot remove projects which contains data and I cannot remove this data because of the issue above.

I observed also another problem on our environment related to download of Helm charts through UI. When I click on download button (also on valid chart), such url is generated:
` https://hostname/api/chartrepo/ppl/charts/chartname-3.1.32-SNAPSHOT.tgz` - this returns 404
But when I go to url below, chart is downloaded:
`https://hostname/chartrepo/ppl/charts/chartname-3.1.32-SNAPSHOT.tgz`
I don't know if this is in any way related to the issue with duplicated entries.

**Steps to reproduce the problem:**
Not fully known, but I pushed a few charts with the same version to one of our repository and such issue occurred. I tried to replicate issue in new repository but I failed.

**Versions:**

- harbor version: v2.3.2
- Helm chart version: 1.7.2
- Kubernetes version:
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+IKS", GitCommit:"980cba7ca2fa7f8fb49262d7ad3fdce5f809528a", GitTreeState:"clean", BuildDate:"2021-08-12T20:29:16Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**Additional context:**
The Harbor environment was updated some time ago from older version (Helm: 1.6.2, but there was another earlier version too). Also, long time ago data was migrated from one kubernetes cluster to other (by reusing the same cloud disc volumes).

**Comment by bitsf** [comment]
dup with https://github.com/goharbor/harbor/issues/15522
this issue is pending on upstream chartmuseum to fix.

**Comment by jowko** [comment]
Closing as duplicate with #15522
