### ISSUE TITLE
Configure UI session timeout

### ISSUE THREAD

**Issue by rasta-rocket** [goharbor/harbor#15669]
First of all, thanks for your awesome work on this project 💪 

Harbor make us saved a lot of time 😉 

We are using harbor v2.3.2

Currently the UI session timeout is by default too small

Is there a way to configure it (especially through the harbor.yml config file). If no can we have one ?

(maybe it will be interesting if I can get some hints on the code, if a PR is required to handle this issue)

Cheers 👋

**Comment by bitsf** [comment]
it is in backend code, currently not configurable

**Comment by rasta-rocket** [comment]
@bitsf thanks for your quick answer 👍 

Would it be possible you show me in the code the location of that configuration ?

Thanks

**Comment by holzman** [comment]
AFAIK, a session lifetime of 3600s comes from the beego default.  To modify it, add a line to `app.conf` on the harbor server with

sessiongclifetime = 86400 

I'm using bitnami's helm chart for harbor deployment, so I'll send a PR upstream making this configurable in the chart, FWIW.

**Comment by qnetter** [comment]
Should we implement both the session timeout (upstream) and a (shorter) inactivity timeout (in the UI) if possible?
