### ISSUE TITLE
Broken REST API to Manage Project Members (delete,add,update)

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#15670]
**Expected behavior:**

If you have a User and a project, you should be able to remove that user from that project! This is not possible in the API right now. 

### DELETE
The REST API CALL to `DELETE ​/projects​/{project_name_or_id}​/members​/{mid}`
is not working as expected because the member_id is declared but in the SQL query  the `id` is used.
https://github.com/goharbor/harbor/blob/2fa530eefa9468693f14c1f40c7423b43fa43e94/src/pkg/member/dao/dao.go#L171

### ADD
entity_id should be returned instead of the ID.
https://github.com/goharbor/harbor/blob/2fa530eefa9468693f14c1f40c7423b43fa43e94/src/pkg/member/dao/dao.go#L158

### UPDATE
https://github.com/goharbor/harbor/blob/0dfc801a50c78f4ff441f9f4e5416a9b6a4c3764/src/pkg/member/dao/dao.go#L169

**Actual  behavior:**
In the SQL queries, the ID is used or returned instead of the Entity_ID. 

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

```sh
curl -I -X POST "https://demo.goharbor.io/api/v2.0/projects" -H "accept: application/json" -H "X-Resource-Name-In-Location: false" -H "authorization: Basic $(echo admin:secret | base64 -)" -H "Content-Type: application/json" -d "{ \"project_name\": \"test-asdf\"}"

# getproject id from response location
EXPORT PROJECT_ID= 39

curl -X DELETE "https://demo.goharbor.io/api/v2.0/projects/$PROJECT_ID/members/1" -H "accept: application/json" -H "authorization: Basic $(echo admin:secret | base64 -)"

```
The user id 1 is the admin.

**Versions:**
Please specify the versions of the following systems.

- harbor version: [2.3.2]

The error was introduced 6 months ago. 

**Additional context:**

**Comment by stonezdj** [comment]
maybe not clear about your question.
The ID is the pmid, it is the primary key of the project_member table, and the entityid is the user id or group id. 
The update/delete operation always uses the pmid as the input parameter. and the create operation return this ID.

**Comment by Vad1mo** [comment]
The **pmID** equals to **entity_id** not to **ID**. The id is just pk entry counter.

I don't know why it is called entity_id in this contex here pm_id would be the better name. This might be a resaon for the  mix up.

**Comment by bitsf** [comment]
I'm afraid it's hard to fix this now, as that will break current API.

**Comment by Vad1mo** [comment]
I disagree, the current code **is broken**. Changing the Code won't break the API because the api is broken. Nobody was using this API because it can not work.  

The performed operations happen on the wrong projects!

Look at this here:

`DELETE "https://demo.goharbor.io/api/v2.0/projects/$PROJECT_ID/members/1`

This will not delete the user with the ID = 1 from the project PROJECT_ID but it will delete the row with id 1.

**There is no way to get the ROW ID** from Harbor, Only if you add a user with `AddProjectMember` it will return the ROW ID once  instead of the entity_id. If you did not save that row id in your system there is no chance to get again. 

So if you have a User and a Project you are not able to remove the user from the project!

**Comment by Vad1mo** [comment]
I investigated some more regarding members and projects,

it is possible to remove a user from a project, in order to do so you need to first get the list of the project members. There the member has the id.    

- PUT ​/projects​/{project_name_or_id}​/members​/{mid}
- GET ​/projects​/{project_name_or_id}​/members​/{mid}
- DELETE ​/projects​/{project_name_or_id}​/members​/{mid}
- POST ​/projects​/{project_name_or_id}​/members
- GET ​/projects​/{project_name_or_id}​/members


The API is still quite confusing and not straightforward, but now I can work around it at least.
