### ISSUE TITLE
Harbor 2.3.2 : can not read LDAP Search Password

### ISSUE THREAD

**Issue by AdinhLux** [goharbor/harbor#15673]
Hi,

Currently I'm facing a weird issue. 

After having set a LDAP Search password, when testing the connection, the error message indicates there is an empty password.

Is it possible to configure the LDAP settings without filling the form in the Web ?

Thanks.

![image](https://user-images.githubusercontent.com/43099257/134864541-fbca86a2-6b1f-492a-886b-e6e18c186cf9.png)

**Comment by stonezdj** [comment]
Have you saved the current settings?  you could refer configure it by  https://goharbor.io/docs/edge/install-config/configure-user-settings-cli/

**Comment by AdinhLux** [comment]
Hello stonezdj,


Do you mean this ?

![image](https://user-images.githubusercontent.com/43099257/134898459-5b4381f8-294b-4755-b115-a026529006be.png)

**Comment by AdinhLux** [comment]
According to logs (**/var/log/harbor/core.log**) the app will look after a local DB user

> Sep 27 11:15:27 172.18.0.1 core[824]: 2021-09-27T11:15:27Z [ERROR] [/core/auth/authenticator.go:264]: Failed to get user from DB, username: ldapsearch, error: user ldapsearch not found
> Sep 27 11:15:28 172.18.0.1 core[824]: 2021-09-27T11:15:28Z [ERROR] [/server/middleware/security/basic_auth.go:40][requestID="cb5d7277-3577-4ac0-8bb4-093199940062"]: failed to authenticate ldapsearch: Failed to authenticate user, due to error 'Invalid credentials'
> Sep 27 11:16:02 172.18.0.1 core[824]: 2021-09-27T11:16:02Z [ERROR] [/core/auth/authenticator.go:264]: Failed to get user from DB, username: ldapsearch, error: user ldapsearch not found
> Sep 27 11:16:03 172.18.0.1 core[824]: 2021-09-27T11:16:03Z [ERROR] [/server/middleware/security/basic_auth.go:40][requestID="81a89a43-a3ac-4ced-82cf-e6ba380a0e12"]: failed to authenticate ldapsearch: Failed to authenticate user, due to error 'Invalid credentials'

**Comment by AdinhLux** [comment]
Ok,


I retried whit removing 389 for ldap URL. And now it works.

So don't bother to look after my issue.


Thanks for paying attention to my issue 👍 .
