### ISSUE TITLE
test and save ldap auth_mode INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by svenlu** [goharbor/harbor#15688]
hi, my harbor version is v2.1.5
i change my auth_mode to ldap, but core's log is 
```sh
Sep 28 14:44:37 192.168.48.1 core[2012]: 2021-09-28T06:44:37Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"system auth_mode isn't ldap_auth, please check configuration"}]}
```

my ldap config is
![image](https://user-images.githubusercontent.com/5123378/135038561-07eeef6b-0004-45b8-ba13-ecf7b220751e.png)

**Comment by zyyw** [comment]
please update harbor to 2.3.2 and try again.
