### ISSUE TITLE
there should be a tracing point when request backend distribution

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#15689]
when check tracing of `PUT /v2/library/busybox/manifests/latest`
![image](https://user-images.githubusercontent.com/188115/135043407-c65e025d-780a-48ac-8000-6750de0283dc.png)

I find it there's quite a large time area I can't determine what is going on.
from the code, I find it should be calling `proxy.ServeHTTP(buffer, req)`
![image](https://user-images.githubusercontent.com/188115/135043835-6853171c-45a2-4f78-a9ed-ce3fcac8b38d.png)

So I suggest we should also add tracing here

maybe add code in `https://github.com/goharbor/harbor/blob/38e0910fc775a9c81e8846355bc722457d48357c/src/server/registry/proxy.go#L47`

**Comment by chlins** [comment]
relevant
