### ISSUE TITLE
The robot account doing replication did not meet the expected HTTP code

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#15684]
**Expected behavior and actual behavior:**
![图片](https://user-images.githubusercontent.com/72076317/135036640-cbd0a2b7-c298-40d2-9165-a2277ef20d82.png)

The http error code is 401 when the robot account is used for replication without corresponding permission, which is not the expected 403

**Versions:**

- harbor version: v2.4.0-90747caf

**Comment by zyyw** [comment]
Please refer to the following issue for a more comprehensive testing scenarios and results: #15695
