### ISSUE TITLE
Test replication with robot account

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#15695]
What can we help you?
Test case 1: replication with robot on "Specific" project
Test Action:
Harbor B: create system-level robot account with all permission only covering project A
Harbor A: 
1. create replication registry of Harbor B with the robot account of Harbor B
2. create push-based and pull-based  replication policy/rule respectively
3. perform the "REPLICATE" operation from Harbor A

Test Result:
| push-based replication                                       | pull-based replication                                       |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| push artifacts from Harbor A, project A to Harbor B, project A: success (as expected) | pull artifacts from Harbor B, project A into Harbor A, project A:  403 (should this be success?) |
| push artifacts from Harbor A, project A to Harbor B, project B: 401 in the replication log (not 403) | pull artifacts from Harbor B, project B into Harbor A, project B: 403 (as expected) |

Test case 2: replication with robot covering all projects with all permissions but no push-artifact permission
Test Action:
Harbor B: create system-level robot account covering all projects with all permissions but **no push-artifact** permission.
Harbor A: 
1. create replication registry of Harbor B with the robot account of Harbor B
2. create push-based and pull-based  replication policy/rule respectively
3. perform the "REPLICATE" operation from Harbor A

Test Result:
| push-based replication                                       | pull-based replication                                       |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| push artifacts from Harbor A, project A to Harbor B, project A: success (should this failed since no push permission?) | pull artifacts from Harbor B, project A into Harbor A, project A:  403 (should this be success since having pull permission?) |
| push artifacts from Harbor A, project A to Harbor B, project B: 401 in the replication log (not 403) | pull artifacts from Harbor B, project B into Harbor A, project B: 403 (should this be success since have pull permission covering all projects) |

**Comment by wy65701436** [comment]
close it.
