### ISSUE TITLE
Unable to create Alibaba ACR type Registry Endpoint

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#15693]
I can’t create Alibaba ACR type Registry Endpoint with my account password, but I can successfully docker login
![图片](https://user-images.githubusercontent.com/72076317/135059247-f7516107-8e25-4478-9a17-dc278b0c2e0e.png)

**Comment by QiuToo** [comment]
我也遇到同样的问题，但我无法找到原因，如果你已经解决了，可以告诉我解决办法吗？非常感谢！
