### ISSUE TITLE
Tag immutability rules do not work

### ISSUE THREAD

**Issue by milica-nikolic** [goharbor/harbor#15700]
Hi!

I am trying to push new images to Harbor from GitLab CI pipeline.
I have set up tag immutability rule to avoid pushing images with tags that already exist on Harbor registry. This is the rule that I use and it doesn't work:

for repositories I set up this combination: matching + cbmp/firstRepo,cbmp/secondRepo
for tags: matching + **

Previously I had image with tag v1.0.0 and after pushing image with same tag I now have new image with tag v1.0.0 and previous image became tagless, I want to prevent this behaviour.

Thank you in advance!

**Comment by Vad1mo** [comment]
what Harbor version are you using?

**Comment by milica-nikolic** [comment]
This is the version: Version v2.1.1-5f52168e

**Comment by wy65701436** [comment]
to match multiple repositories, you need to give cbmp/{firstRepo,secondRepo}

**Comment by milica-nikolic** [comment]
When I try to add curly braces they just disappear or even when they stay and I save those changes when I open rule again for editing I can't see previous changes, it is acting weird.
