### ISSUE TITLE
after stop replication job, the task is actually still running for a while

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#15708]
Currently when user click stop job, it just set a stop marker in database, and jobservice will break job at some check point.
But if user is copying a big blob, or use replication bandwidth limit (in v2.4), that may need quite a long time before the jobs really exit. Because there isn't any checkpoint inside `PushBlob()` https://github.com/goharbor/harbor/blob/93e644119d39239ebdec9170414b4de5b2474f6e/src/controller/replication/transfer/image/transfer.go#L331

The side effect is other executions/tasks may not be scheduled because usually only 10 concurrent workers, and you will see job pending status and log NOT_FOUND problem.
```{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"1537612e372ab09cb9bba00f\"}"}]}```

user has to restart jobservice container if he want to force stop the network transfer.

**Comment by zyyw** [comment]
wait for feedback from users

**Comment by dioguerra** [comment]
This is happening to us and our service is down as a result
