### ISSUE TITLE
Replicating Registries crypto error

### ISSUE THREAD

**Issue by tman5** [goharbor/harbor#15712]
Running Harbor 2.2.2 on both sides. 

When adding registry2 from registry1 using the builtin `admin` account for the username/password just as a registry (not replication yet) I see these errors:

registry2
```
2021-09-29T17:49:16Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
2021-09-29T17:49:16Z [WARNING] [/server/middleware/security/v2_token.go:48][requestID="201789ad-0d1d-47f5-92b4-a6696daa3fbb"]: failed to decode bearer token: crypto/rsa: verification error
```

registry1
```
2021-09-29T13:12:06Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://registry2.local: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
```

Note I can confirm I can login to both with their respective admin accounts without issue.

**Comment by sixeIa** [comment]
Are the hostname/external_url of harbor.yml correct ?
Are the two registries behind a loadbalancer ?
Is this a multiple node registry ?

**Comment by tman5** [comment]
External_url is not used in our case. It's still commented out.

We do use a load balancer but I tried going directly to the host and same result.

Each registry has a single node. So 2 separate registries I'm trying to replicate between them.

**Comment by sixeIa** [comment]
Can you check debug process describe by @reasonerjt here: https://github.com/goharbor/harbor/issues/12199#issuecomment-641866516

**Comment by tman5** [comment]
I did take a look at that. The 2 instances do in fact have different private keys. I tested by copying the private key from one to the other and it now works. But, is that required? Do they both need the same registry private key to replicate between them?

**Comment by wy65701436** [comment]
There is no need to copy private key in the replicaion scenario. Did you try the test connection in the Harbor UI?

**Comment by bitsf** [comment]
is docker login registry2.local -u admin -p Harbor12345 work ?
