### ISSUE TITLE
The trace of jobservice not showing the backend jobs

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#15725]
I install Harbor dev build with tracing enabled.

On the UI I triggered the scan of an image and after the scan completed I accessed Jaeger to see the traces under service `harbor-jobservice` .  I couldn't see any traces for backend jobs, instead, I only see a few traces like `tx-insert-for-report` and `start-transaction`
![Screen Shot 2021-10-03 at 6 31 44 PM](https://user-images.githubusercontent.com/2390463/135749801-a26d4945-3dbc-462b-8bef-cc1e8b9cf470.png)
![Screen Shot 2021-10-03 at 6 31 38 PM](https://user-images.githubusercontent.com/2390463/135749803-77ce99ad-8f63-494b-a501-3ff7db0f5e3b.png)
![Screen Shot 2021-10-03 at 6 31 25 PM](https://user-images.githubusercontent.com/2390463/135749805-67d8f7aa-7380-4aec-a170-4f5cad1d34d5.png)

**Comment by reasonerjt** [comment]
I re-ran the case and found there is a trace called `run-job`
<img width="1634" alt="Screen Shot 2021-10-13 at 11 30 15 AM" src="https://user-images.githubusercontent.com/2390463/137062439-b6aa7b37-47ed-4b53-a699-3f3ede921714.png">

I think I can close the issue for now.

**Comment by stonezdj** [comment]
<img width="439" alt="Screen Shot 2021-10-13 at 12 04 43 PM" src="https://user-images.githubusercontent.com/2696760/137065345-50b3be13-47e8-4b47-9575-b1dd88c1070b.png">
