### ISSUE TITLE
harbor-core crash loop (helm installation)

### ISSUE THREAD

**Issue by aendi123** [goharbor/harbor#15720]
I have installed Harbor using the helm chart on a new RKE2 Cluster. Im using external Postgres, Redis and Minio. These three services are working correctly as far as I know, becasuse they are used without problems by Nextcloud and Gitlab.

These are my [values.yaml.txt](https://github.com/goharbor/harbor/files/7258619/values.yaml.txt)

All components work well, except harbor-core. Also I cannot push images, but I think that's because of the core not working. The core restarts every few minutes, sometimes the readiness check succeeds, sometime it doesn't. On the webinterface, I sometimes can't login with the error "Core service not available" and the banner "Unauthorized" is showed when I'm logged in sometimes. Shortly, the core service works for some seconds and then does not work for some seconds. The same thing happens with 1 or 2 harbor-core replicas.

Logs harbor-core pod between the start of the pod and the first restart: [logs.txt](https://github.com/goharbor/harbor/files/7259646/logs.txt)

Important lines are probably (count of `[middleware.go:52]  EOF` is always different):
```
2021/09/30 12:45:34.454 [E] [middleware.go:52]  EOF
2021-09-30T12:45:41Z [ERROR] [/server/middleware/security/session.go:34][requestID="50b64fa6cbf864f72fd69f019bfdf25c"]: failed to get the session store for request: EOF
```

Pushing error:
```
The push refers to repository [harbor.mydomain.com/project/repo]
3e7aa53fce93: Pushed
870e46a0594c: Pushed
f2d445d884e0: Pushed
8f9bed20e0f2: Pushed
215b233c3556: Pushed
2e9435626e2d: Pushed
f3ffceb6c734: Pushed
b681d38d38b0: Pushed
e2eb06d8af82: Pushing [==================================================>]  5.865MB
blob upload unknown
```

**Steps to reproduce the problem:**
1. Install fresh RKE2 Cluster
2. Install Postgres Cluster with CrunchyData Operator
3. Install Redis Sentinel Cluster and HAProxy using bitnami/redis helm chart (I'm using HAProxy in front of the cluster because Harbor currently doesn't support Sentinel with password according to #14810)
4. Set up Minio server
5. Install Portworx in Cluster
6. Install Harbor using Helm

**Versions:**
- harbor version: v2.3.3
- RKE2 v1.21.4+rke2r3
- Containerd 1.4.8-k3s1
- AlmaLinux 8

**Comment by bitsf** [comment]
is password for redis correct ?

**Comment by bitsf** [comment]
Nextcloud and Gitlab and harbor are all using redis index 0, they maybe have some conflicts, such as harbor beego session is deleted by Nextcloud or Gitlab.
for `keys *` in redis, it should be something like
![image](https://user-images.githubusercontent.com/188115/149264297-2431d1b1-7e54-4515-9511-16269c1da3b4.png)

you can try use a clean redis
