### ISSUE TITLE
Large image push fails

### ISSUE THREAD

**Issue by harpo** [goharbor/harbor#15729]
**Expected behavior and actual behavior:**
Images should upload without issues regardless of size.
Large image (>2GB) docker push retries and fails. 

` docker image push registry.domain/project/ccc:1.0
The push refers to repository [registry.domain/project/ccc]
85bc43fa95f1: Pushing [==================================================>]   5.12GB
df64d3292fd6: Layer already exists
received unexpected HTTP status: 504 Gateway Time-out`

**Steps to reproduce the problem:**
docker push image larger than 2GB. Docker then retries and fails with 504.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.3]
- docker engine version: [20.10.8]

**Additional context:**
smaller images are pushed without issues. 
During upload I can see the directory /storage/docker/registry/v2/repositories/project/xxxxxx/_uploads/ filling up with data.

- **Harbor config files:** 
registry config.yml
`version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /storage
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: false
redis:
  addr: harbor-1-1628783898-redis:6379
  db: 2
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  pool:
    maxidle: 100
    maxactive: 500
    idletimeout: 60s
http:
  addr: :5000
  relativeurls: false
  debug:
    addr: localhost:5001
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true
`

- **Log files:** 
Registry Container Log:
`ime="2021-10-04T12:57:22.714944786Z" level=error msg="client disconnected during blob PATCH" auth.user.name="harbor_registry_user" contentLength=5121562699 copied=2640967724 error="unexpected EOF" go.version=go1.15.12 http.request.host=registry.domain http.request.id=04a54825-013b-4cfb-a31d-6b4317a0c7d0 http.request.method=PATCH http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/project/repo/blobs/uploads/e7fb6db0-ce6e-4c72-8169-2f85de8cc54d?_state=PjTkBa-Jvj-TJJ_VHBCvLxW5XtlBjLT_GZEeUQK18gt7Ik5hbWUiOiJlbXBhaWEtdGVzdC9jY2MiLCJVVUlEIjoiZTdmYjZkYjAtY2U2ZS00YzcyLTgxNjktMmY4NWRlOGNjNTRkIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTEwLTA0VDEyOjUzOjU0LjMzNjc0Mzg0N1oifQ%3D%3D" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(linux\))" vars.name="project/repo" vars.uuid=e7fb6db0-ce6e-4c72-8169-2f85de8cc54d
time="2021-10-04T12:57:27.647354105Z" level=info msg="authorized request" go.version=go1.15.12 http.request.host=registry.domain http.request.id=50f0c3c7-2d22-4043-b67b-88b41be823d0 http.request.method=POST http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/project/repo/blobs/uploads/" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(linux\))" vars.name="project/repo"
time="2021-10-04T12:57:28.471220972Z" level=info msg="response completed" go.version=go1.15.12 http.request.host=registry.domain http.request.id=50f0c3c7-2d22-4043-b67b-88b41be823d0 http.request.method=POST http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/project/repo/blobs/uploads/" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(linux\))" http.response.duration=891.564016ms http.response.status=202 http.response.written=0
xxx.xxx.xxx.xxx - - [04/Oct/2021:12:57:27 +0000] "POST /v2/project/repo/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \\(linux\\))"
2021/10/04 12:57:30 http: superfluous response.WriteHeader call from github.com/docker/distribution/vendor/github.com/gorilla/handlers.(*responseLogger).WriteHeader (handlers.go:125)
xxx.xxx.xxx.xxx - - [04/Oct/2021:12:56:52 +0000] "PATCH /v2/project/repo/blobs/uploads/e7fb6db0-ce6e-4c72-8169-2f85de8cc54d?_state=PjTkBa-Jvj-TJJ_VHBCvLxW5XtlBjLT_GZEeUQK18gt7Ik5hbWUiOiJlbXBhaWEtdGVzdC9jY2MiLCJVVUlEIjoiZTdmYjZkYjAtY2U2ZS00YzcyLTgxNjktMmY4NWRlOGNjNTRkIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTEwLTA0VDEyOjUzOjU0LjMzNjc0Mzg0N1oifQ%3D%3D HTTP/1.1" 500 89 "" "docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \\(linux\\))"
time="2021-10-04T12:57:30.1817844Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="client disconnected" err.message="unknown error" go.version=go1.15.12 http.request.host=registry.domain http.request.id=04a54825-013b-4cfb-a31d-6b4317a0c7d0 http.request.method=PATCH http.request.remoteaddr=xxx.xxx.xxx.xxx http.request.uri="/v2/project/repo/blobs/uploads/e7fb6db0-ce6e-4c72-8169-2f85de8cc54d?_state=PjTkBa-Jvj-TJJ_VHBCvLxW5XtlBjLT_GZEeUQK18gt7Ik5hbWUiOiJlbXBhaWEtdGVzdC9jY2MiLCJVVUlEIjoiZTdmYjZkYjAtY2U2ZS00YzcyLTgxNjktMmY4NWRlOGNjNTRkIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTEwLTA0VDEyOjUzOjU0LjMzNjc0Mzg0N1oifQ%3D%3D" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/4.15.0-159-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=37.622842614s http.response.status=500 http.response.written=89 vars.name="project/repo" vars.uuid=e7fb6db0-ce6e-4c72-8169-2f85de8cc54d`

**Comment by harpo** [comment]
Problem was fixed by setting the following nginx ingress annotations:
`nginx.ingress.kubernetes.io/proxy-body-size=0
nginx.ingress.kubernetes.io/proxy-buffering=off
nginx.ingress.kubernetes.io/proxy-connect-timeout=7200
nginx.ingress.kubernetes.io/proxy-next-upstream-timeout=7200
nginx.ingress.kubernetes.io/proxy-read-timeout=7200
nginx.ingress.kubernetes.io/proxy-request-buffering=off
nginx.ingress.kubernetes.io/proxy-send-timeout=7200
nginx.ingress.kubernetes.io/proxy_ignore_headers=X-Accel-Buffering
`

**Comment by j4ckstraw** [comment]
I meet the same problem, can you explain why these annotations fix that?

> Problem was fixed by setting the following nginx ingress annotations: `nginx.ingress.kubernetes.io/proxy-body-size=0 nginx.ingress.kubernetes.io/proxy-buffering=off nginx.ingress.kubernetes.io/proxy-connect-timeout=7200 nginx.ingress.kubernetes.io/proxy-next-upstream-timeout=7200 nginx.ingress.kubernetes.io/proxy-read-timeout=7200 nginx.ingress.kubernetes.io/proxy-request-buffering=off nginx.ingress.kubernetes.io/proxy-send-timeout=7200 nginx.ingress.kubernetes.io/proxy_ignore_headers=X-Accel-Buffering `

**Comment by harpo** [comment]
> I meet the same problem, can you explain why these annotations fix that?

I totally forgot to update this issue. The actual fix was to remove memory related ressource limits from the the harbor namespace.

**Comment by j4ckstraw** [comment]
> > I meet the same problem, can you explain why these annotations fix that?
> 
> I totally forgot to update this issue. The actual fix was to remove memory related ressource limits from the the harbor namespace.

thanks a lot, that's may not be the root cause for me. I deploy harbor by docker-compose.
