### ISSUE TITLE
failed to create a new keydbstore: pq: unknown authentication response: 10

### ISSUE THREAD

**Issue by kevinlmadison** [goharbor/harbor#15731]
I'm using the Harbor Operator to deploy a harbor cluster and in my notary server and signer pods I'm getting the following output
```
2021/10/05 16:55:06 Updating database.
2021/10/05 16:55:06 schema_migrations table does not require update, skip.
no change
notarysigner database migrated to latest version
{"level":"info","msg":"Version: 0.6.1, Git commit: d6e1431f","time":"2021-10-05T16:55:06Z"}
{"level":"fatal","msg":"failed to create a new keydbstore: pq: unknown authentication response: 10","time":"2021-10-05T16:55:06Z"}
```

I believe this has to do with the `scram-sha-256` client library needing to be updated as per [this](https://stackoverflow.com/questions/64316524/how-to-fix-the-unknown-authentication-response-10-in-postgis-database-through) post on stackoverflow.

Is this something I can work around or does this need to be fixed in the codebase? 
Thank you!

**Comment by zer0def** [comment]
This issue isn't operator-specific, but rather specifically applicable to both notary services. This still applies in 2.4.0.

**Comment by InderpreetSaini** [comment]
Hi,
Did you find any resolution to this issue? I am facing the same issue for both notary server and signer pods?
I am using the below postgres cluster.

https://access.crunchydata.com/documentation/postgres-operator/5.0.4/quickstart/

**Comment by kevinlmadison** [comment]
Hey @InderpreetSaini 
I am using the same operator setup for postgres, and essentially what you have to do is update the `verifier` in the secret created by crunchy with you postgres database credentials. The update you need to make is to hash with MD5 instead of scramsha256. There is some info [here](https://access.crunchydata.com/documentation/postgres-operator/5.0.4/architecture/user-management/)
There was another page where they showed you how to hash and I'm looking for that for you now.

**Comment by kevinlmadison** [comment]
@InderpreetSaini 
[Here you go!](https://github.com/CrunchyData/postgres-operator/issues/2724)
He links to the code you can use in his response to me.

**Comment by InderpreetSaini** [comment]
Thanks a lot @kevinlmadison ! It worked and now my notary pods are running without any issues.

**Comment by djtaylor** [comment]
I was having the same issue, but the link mentioned above worked for me in resolving it. Are there any plans on adding support for `SCRAM-SHA-256`?

**Comment by Ramki33** [comment]
@InderpreetSaini 
@kevinlmadison 

HI ,  
i am facing same issue , with harbor using postgres operator 
i tried  patching secret with SCRAM-SHA-256  as mentioned [https://github.com/CrunchyData/postgres-operator/commit/fddc90e0f55fb1d0455c5d56d2b086150410142b](url) 

 its not solving :-(  could you pls guide me 

oc logs harbor-notary-signer-5d5bf66dbb-p9kzb
2022/04/13 20:25:12 Updating database.
2022/04/13 20:25:12 schema_migrations table does not require update, skip.
no change
notarysigner database migrated to latest version
{"level":"info","msg":"Version: 0.6.1, Git commit: d6e1431f","time":"2022-04-13T20:25:12Z"}
{"level":"fatal","msg":"failed to create a new keydbstore: **pq: unknown authentication response: 10**","time":"2022-04-13T20:25:12Z"}

harbor values.yaml : 
  external:
    host: "hippo-primary.postgres-operator.svc"
    port: "5432"
    username: hippo
    password: datalake
    coreDatabase: "registry"
    notaryServerDatabase: "notaryserver"
    notarySignerDatabase: "notarysigner"
    sslmode: "require"

**Comment by Ramki33** [comment]
> I was having the same issue, but the link mentioned above worked for me in resolving it. Are there any plans on adding support for `SCRAM-SHA-256`?

hi @djtaylor ,
 
As said , I tried same mentioned step . its not working for me  ( see above comment from me ) 
i might be doing some thing wrong .  could you guide me.

**Comment by InderpreetSaini** [comment]
> @InderpreetSaini @kevinlmadison
> 
> HI , i am facing same issue , with harbor using postgres operator I am using the postgres cluster https://access.crunchydata.com/documentation/postgres-operator/5.0.4/quickstart/
> 
> i tried patching secret with SCRAM-SHA-256 as mentioned [above](https://github.com/CrunchyData/postgres-operator/commit/fddc90e0f55fb1d0455c5d56d2b086150410142b) its not solving :-( could you pls guide me
> 
> oc logs harbor-notary-signer-5d5bf66dbb-p9kzb 2022/04/13 20:25:12 Updating database. 2022/04/13 20:25:12 schema_migrations table does not require update, skip. no change notarysigner database migrated to latest version {"level":"info","msg":"Version: 0.6.1, Git commit: d6e1431f","time":"2022-04-13T20:25:12Z"} {"level":"fatal","msg":"failed to create a new keydbstore: **pq: unknown authentication response: 10**","time":"2022-04-13T20:25:12Z"}
> 
> harbor values.yaml : external: host: "hippo-primary.postgres-operator.svc" port: "5432" username: hippo password: datalake coreDatabase: "registry" notaryServerDatabase: "notaryserver" notarySignerDatabase: "notarysigner" sslmode: "require"

Hi @Ramki33 , as per my understanding, notary in Harbor does not support SCRAM-SHA-256 encrypted password authentication. Have you tried generating the verifier using algorithm value as md5 instead of scram-sha-256?

Besides the latest version of Harbor 2.5.0 supports Cosign integration as an image signing solution along with Notary. So you have the option to go along with Cosign, instead of Notary.

**Comment by Ramki33** [comment]
Hi  @InderpreetSaini , 

Thanks a lot it worked with md5  as you suggested .

**Comment by bbroniewski** [comment]
Just use some tool to hash your password with md5 (postgres uses also username to hash) and when you do it, then alter the user like:
```
ALTER USER test WITH PASSWORD 'md5c4c2d8de69efb9041d37711fe303a3dd'
```

Then password will be stored as MD5 encrypted and all pods will work.

**Comment by Smartich0ke** [comment]
Just adding to @mubei1005 's comment, don't forget to make sure your `pg_hba.conf` is updated accordingly otherwise you might not be able to login.

For example, to make sure the user 'harbor' has their password hashed with md5, add the following line (above any `host all all all ...` lines):
```
host    all     harbor    all     md5
```
