### ISSUE TITLE
Project export / import 

### ISSUE THREAD

**Issue by florentortiz** [goharbor/harbor#15732]
Hello everyone,

In my company, we have set up multiple harbor registries for different networks/needs and put some replications rules so that every registry have the same (or nearly) images in each project.

But for one specific network, we can't use the replication functionality as it is a specific network with very limited access. 

So, we need to export every "production" project in one registry and then copy and import this data in the registry that is in the "specific" network.

It seems that it can't be done natively for the moment, so it may be good to add this ?

Or maybe you can provide me some steps to do it ? Maybe in command line ?

Many thanks,

**Comment by zyyw** [comment]
it's currently not supported
