### ISSUE TITLE
WUI error setting up LDAP Scope

### ISSUE THREAD

**Issue by gerrytb** [goharbor/harbor#15740]
I got the following error message setting up LDAP Scope (whatever value):  _**validation failure list: parsing configurations body from "" failed, because json: cannot unmarshal string into Go struct field Configurations.ldap_group_search_scope of type int64**_

**Steps to reproduce the problem:**
On Configuration -> Authentication -> Auth Mode -> LDAP 
Setting up LDAP Scope 
Save

**Expected behavior and actual behavior:**
Expected behavior:
The expected behavior would be to select  the option for **LDAP Scope** between:
> Base
> OneLEvel
> Subtree
Without any kind of problem.

Actual behavior:
Whatever value has been selected on **LDAP Scope**, when I save the configuration I get this error message:
_**validation failure list: parsing configurations body from "" failed, because json: cannot unmarshal string into Go struct field Configurations.ldap_group_search_scope of type int64**_
Forcing me to left **LDAP Scope** empty

As a consequence
![harbor_problem](https://user-images.githubusercontent.com/82316970/136525263-87744a9e-5b11-4b51-95c0-8dc925dc2593.png)
, LDAP cannot find users and login to Harbor with LDAP is not possible.

**Versions:**
- harbor version: [2.3.2] (Updated to v2.3.3 and the problem persist)
- docker engine version: [20.10.15]
- docker-compose version: [1.29.2]

**Additional context:**

The error is only on the Web User Interface, no other message is written in logfiles /var/log/harbor

Please check attached image to see the error from WUI.

**Comment by stonezdj** [comment]
could you please paste the payload of the HTTP request?

**Comment by zyyw** [comment]
could you please provide which Harbor version you are using?

**Comment by REHICode** [comment]
same problem here
