### ISSUE TITLE
about job_loggers type

### ISSUE THREAD

**Issue by sundaykeke** [goharbor/harbor#15741]
in the values.yaml, the .Values.jobservice.jobLogger is file.And I see it supports database,too.
Which type is recommended?
Or what are the disadvantages of database types？
Thank you~

**Comment by sidewinder12s** [comment]
Ya, I was hoping to see more docs on this as I was looking at options to retain job logs, primarily for retention and GC runs.

**Comment by steven-zou** [comment]
Here are some differences:

File and DB loggers support log getting API.  That means the log content can be retrieved from the UI.
File and DB loggers also support retention policy. That means you can specify a duration for cleaning old logs to avoid increasing log storage size.
DB logger can well support HA mod (multiple jobservice pods/nodes).

@sundaykeke and @sidewinder12s


Hope the above answer can clarify your questions. I'll close the issue and you can reopen it at any time when necessary.

**Comment by sidewinder12s** [comment]
> Here are some differences:
> 
> File and DB loggers support log getting API. That means the log content can be retrieved from the UI. File and DB loggers also support retention policy. That means you can specify a duration for cleaning old logs to avoid increasing log storage size. DB logger can well support HA mod (multiple jobservice pods/nodes).
> 
> @sundaykeke and @sidewinder12s
> 
> Hope the above answer can clarify your questions. I'll close the issue and you can reopen it at any time when necessary.

@steven-zou Are there docs/issues about how to run the job service in HA mode? Is it just run more replicas while using DB mode? I don't recall seeing anything about that before.
