### ISSUE TITLE
Cannot docker login with robot user

### ISSUE THREAD

**Issue by btwnsvll** [goharbor/harbor#15757]
**Summary:**
After a fresh installation of Harbor v2.3.3, I could not log in with a robot user although logging in with a regular user works.

**Steps to reproduce the problem:**
Create a regular user called `user` and grant access to one project. Log in with the docker cli:

```
$ docker login https://harbor.mydomain.com --username user
Password: (enter password...)

Login Succeeded
```

Create a robot user called `test` and grant access to one project with "Pull Artifact" permission. Click add. I see a modal with header "Created 'robot$test' successfully" along with the name `robot$test` and a token. I copy the token.

I try to log in with docker client several different ways.

```
$ docker login https://harbor.mydomain.com --username robot$test
Password: 
Error response from daemon: Get "https://harbor.mydomain.com/v2/": unauthorized: authentication required
```

```
$ echo "<the token from harbor ui>" |docker login https://harbor.mydomain.com --username robot$test --password-stdin
Error response from daemon: Get "https://harbor.mydomain.com/v2/": unauthorized: authentication required
```

```
$ docker login https://harbor.mydomain.com --username robot$test --password <the token from harbor ui>
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://harbor.mydomain.com/v2/": unauthorized: authentication required
```
Each time, I see `unauthorized: authentication required`.

I expected to be able to log in with the robot user using the docker cli client.

**Versions:**
- harbor version: v2.3.3
- docker engine version: 20.10.8
- docker-compose version: 1.25.5

**Comment by Vad1mo** [comment]
try `robot$$test`  or 'robot$test' in quote
