### ISSUE TITLE
Right way to get swagger.yaml for certain harbor release 

### ISSUE THREAD

**Issue by iyurev** [goharbor/harbor#15768]
Hi, 
I gonna dev a client api library for harbor registry , but I couldn't find guide in the documentation about what's right way to get swagger.yaml for certain harbor registry release.

For example: 
I have harbor instance  version - v2.3.2-6b6c21da ( I've grabbed  it in UI),  documentation says that I can get swagger.yaml in directory api/v2.0/ , but it miss about how to get swagger.yaml for  my of  instance harbor with  version v2.3.2-6b6c21da  

I'll be grateful if someone get me advice about  my question, and this information  appear in the official documentation .

**Comment by iyurev** [comment]
> Browse the harbor source code by the tag, and find the swagger.yaml in the `api/v2.0/swagger.yaml`.
> 
> Here is the raw url for the swagger.yaml of harbor 2.3.2 https://raw.githubusercontent.com/goharbor/harbor/v2.3.2/api/v2.0/swagger.yaml

Thanks  for information, so what about add this information to documentation ?

**Comment by heww** [comment]
Hi @AllForNothing, is it possible to add a link in the `Harbor API` page to download the raw swagger file for the customers?
