### ISSUE TITLE
Replication task is always in pending status

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#15760]
There is a failed replication job, it stayed in the queue for a month, but its status always in `Pending`
error logs
```
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"ba483d5f7e8750a43832f006\"}"}]}
```
Harbor version: 2.3.1

Screenshot
<img width="1374" alt="Screen Shot 2021-10-12 at 10 57 48 AM" src="https://user-images.githubusercontent.com/2696760/136883755-1c483abb-62ce-4010-9840-84ec1cb5eb8b.png">

**Comment by sizowie** [comment]
Same here with Harbor 2.4.

Replications times vary between some seconds and >100minutes. But only on fresh installations, I've upgraded about 6 instances from 2.2.1 without an issue yet.

**Comment by sizowie** [comment]
The transfer itself was quick, but the replication job was pending for minutes/hours. In my case I identified that trivy couldnt access search.maven.org for library scanning. This resulted in hanging scan jobs and might filled up worker with scanreport waiting processes. After fixing the trivy part, it works like a charm again. Also we've increased the worker from 10 to 20.

**Comment by bitsf** [comment]
yes, if no workers, the job would be pending status
