### ISSUE TITLE
Password limitations for harbor users

### ISSUE THREAD

**Issue by sunielm7** [goharbor/harbor#15771]
Are special characters allowed in password for users in harbor? I couldnt find any documentation regarding characters that are not allowed while creating a password. I am using authentication mode as database for this harbor instance.

**Comment by AllForNothing** [comment]
@sunielm7 Here is the password regex for your reference `^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,128}$`

**Comment by sunielm7** [comment]
Thanks much. Does harbor UI/API validate this regex when admin creates a user account and sets the password?

**Comment by AllForNothing** [comment]
@sunielm7, Yes, both UI and back-end API validate it
