### ISSUE TITLE
Harbor 2.3.1 cannot create chartmuesum replication rule with Pull-based replication mode

### ISSUE THREAD

**Issue by sarathsprakash** [goharbor/harbor#15778]
With harbor 2.3.1 version. It doesn't allow replication rule to be added for chart-museum. Once the **source registry**(which is another harbor 2.3.1 registry) is added. The **Resource** option `chart(chartmuseum)` gets vanished. However in Harbor 2.2.2 this option was available, even with source registry as harbor 2.3.1 , it works.

**Steps to reproduce the problem:**
* Install Harbor 2.3.1 with `--with-chartmuseum` option
* Got to the web ui.
* Add a new endpoint of type harbor(any version) installed with `--with-chartmuseum`
* Add a new Replication rule with source-registry as above harbor instance, replication mode as `Pull-based` 
* Now the Resource will have only options `all`, `images`, `artifacts`

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.1
- docker engine version: 19.03.1
- docker-compose version: 1.29.2

**Comment by bitsf** [comment]
you should check the harbor v2.3 instance with `curl api/v2.0/systeminfo -u admin`, currently your log is about `harbor_version=v2.2.2-56d7937f`

**Comment by sarathsprakash** [comment]
@bitsf , I was checking the v2.2 to conclude if the issue is to v2.3 and to my surprise that the same issue was there for the v2.2 as well and hence I posted info of v2.2
