### ISSUE TITLE
[/core/controllers/base.go:103]: Error occurred in UserLogin: user XXXXXXXXX or email  already exists

### ISSUE THREAD

**Issue by arpitvipulsharma** [goharbor/harbor#15793]
What can we help you?
Hello Team,
We are facing one issue with harbor version 2.3.3 . We are using AD for authentication. With one user we are getting error as 
/core/auth/authenticator.go:262]: Failed to get user from DB, username: XXXXXXXX, error: user XXXXXXXXX not found
[/core/controllers/base.go:103]: Error occurred in UserLogin: user XXXXXXXXX or email  already exists
User is not able to login in UI while user is trying with right AD password. 
When we checked in database( harbor_user), user doesn't exist there. Can you help us with this case?
Our setup is based on docker-compose & for other users its working fine. we are facing issue with only 1 user currently. 
Many thanks

**Comment by stonezdj** [comment]
Is this user email address is empty or the email is not empty but duplicate with an existing user?
```
docker exec -it harbor-db bash
psql -U postgres -d registry
select email from harbor_user
```

**Comment by stonezdj** [comment]
The email should be unique in database.

**Comment by jeshwanth-harish** [comment]
I faced same issue and the fix was - converting Username field to lowercase in PG db and the users were able to login. It looks like the fields are case sensitive.
