### ISSUE TITLE
 level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: Path not found:xx"

### ISSUE THREAD

**Issue by unixomg** [goharbor/harbor#15801]
When I used S3 as the back-end storage, after storing 20T of data, suddenly something went wrong，and docker push has a lot of retries and returns unknown blob,I don't know how to solve this problem。

`Oct 15 16:52:50 192.168.176.1 registry[38061]: time="2021-10-15T08:52:50.736849512Z" level=error msg="unknown error completing upload: s3aws: Path not found: /docker/registry/v2/repositories/dibuild/performance-osim140.dev-osim140-v.performance.centos72/_uploads/65121ba0-c42a-4690-b2e1-9d30ec6411a1/data" auth.user.name="harbor_registry_user" go.version=go1.15.12 http.request.host=registry.test.com http.request.id=66b4366d-e4e3-419b-9b2d-a78766ce90fd http.request.method=PUT http.request.remoteaddr=10.85.68.246 http.request.uri="/v2/dibuild/performance-osim140.dev-osim140-v.performance.centos72/blobs/uploads/65121ba0-c42a-4690-b2e1-9d30ec6411a1?_state=ab_kYi7Nf0p6Ow1luYQYLoJELHmqTC3HL2MQcEYMjnt7Ik5hbWUiOiJkaWRpYnVpbGQvcGVyZm9ybWFuY2UtaG5hLW9zaW0xNDAuemp5LWRldi1vc2ltMTQwLXYucGVyZm9ybWFuY2UuZ3MuYml6Lm9zaW0uZGlkaS5jb20uY2VudG9zNzIiLCJVVUlEIjoiNjUxMjFiYTAtYzQyYS00NjkwLWIyZTEtOWQzMGVjNjQxMWExIiwiT2Zmc2V0IjozNTcwNjk2MywiU3RhcnRlZEF0IjoiMjAyMS0xMC0xNVQwODo1MjozN1oifQ%3D%3D&digest=sha256%3A3f160654073f75cb7dd07b0c3f74680851cf0c9a48ba1a81dafd81b4cc978444" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-514.16.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \(linux\))" vars.name="didibuild/performance-osim140.dev-osim140-v.performance.centos72" vars.uuid=65121ba0-c42a-4690-b2e1-9d30ec6411a1
Oct 15 16:52:50 192.168.176.1 registry[38061]: time="2021-10-15T08:52:50.747501144Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: Path not found: /docker/registry/v2/repositories/dibuild/performance-osim140.dev-osim140-v.performance.centos72/_uploads/65121ba0-c42a-4690-b2e1-9d30ec6411a1/data" err.message="unknown error" go.version=go1.15.12 http.request.host=registry.test.com http.request.id=66b4366d-e4e3-419b-9b2d-a78766ce90fd http.request.method=PUT http.request.remoteaddr=10.85.68.246 http.request.uri="/v2/didibuild/performance-osim140.dev-osim140-v.performance.centos72/blobs/uploads/65121ba0-c42a-4690-b2e1-9d30ec6411a1?_state=ab_kYi7Nf0p6Ow1luYQYLoJELHmqTC3HL2MQcEYMjnt7Ik5hbWUiOiJkaWRpYnVpbGQvcGVyZm9ybWFuY2UtaG5hLW9zaW0xNDAuemp5LWRldi1vc2ltMTQwLXYucGVyZm9ybWFuY2UuZ3MuYml6Lm9zaW0uZGlkaS5jb20uY2VudG9zNzIiLCJVVUlEIjoiNjUxMjFiYTAtYzQyYS00NjkwLWIyZTEtOWQzMGVjNjQxMWExIiwiT2Zmc2V0IjozNTcwNjk2MywiU3RhcnRlZEF0IjoiMjAyMS0xMC0xNVQwODo1MjozN1oifQ%3D%3D&digest=sha256%3A3f160654073f75cb7dd07b0c3f74680851cf0c9a48ba1a81dafd81b4cc978444" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/3.10.0-514.16.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=161.610502ms http.response.status=500 http.response.written=277 vars.name="dibuild/performance-osim140.dev-osim140-v.performance.centos72" vars.uuid=65121ba0-c42a-4690-b2e1-9d30ec6411a1
`

**Comment by heww** [comment]
Do you use the s3 of the AWS of the compatible s3 like minio, ceph?

**Comment by unixomg** [comment]
> Do you use the s3 of the AWS of the compatible s3 like minio, ceph?
yes ,i used minio, but i found in harbor aws sdk does not found any retry mechanism，if there is a synchronization delay in the metadata reading of the s3 storage backend, it will cause the upload to fail, and then cause the docker push to fail。

**Comment by ZPerling** [comment]
@unixomg how to fix this problem?  I have the same problem

**Comment by tvanderwal-lmco** [comment]
We're also seeing this issue, did anyone figure out a root cause and/or fix?

**Comment by ZPerling** [comment]
> We're also seeing this issue, did anyone figure out a root cause and/or fix?

@tvanderwal-lmco I fix this issue by rebuild registry module. 
https://github.com/distribution/distribution/pull/3278/files
