### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by xiongyunhua-star** [goharbor/harbor#15823]
What can we help you?
docker push error,info: 413 Request Entity Too Large

harbor version:
harbor  harbor-offline-installer-v2.2.2.tgz 

nginx.config:
[root@xyh-harbor-single-host nginx]# pwd
/root/harbor/common/config/nginx
[root@xyh-harbor-single-host nginx]# ls
conf.d  nginx.conf
[root@xyh-harbor-single-host nginx]# grep client nginx.conf 
  client_body_temp_path /tmp/client_body_temp;
    client_max_body_size 0;

error info:
[root@xyh-gitlab ~]# docker push 10.0.0.87/s2i/tomcat:8
The push refers to a repository [10.0.0.87/s2i/tomcat]
aa3d17275dd0: Pushed 
c190c471d474: Pushed 
82ec57a337a5: Pushing [==================================================>] 18.98 MB
ecf2a68d58aa: Pushed 
211736d7fc9d: Pushing [==================================================>] 342.7 MB/342.7 MB
62a5b8741e83: Pushing [==================================================>]    512 B
36e0782f1159: Waiting 
ba6e5ff31f23: Waiting 
9f9f651e9303: Waiting 
0b3c02b5d746: Waiting 
62a747bf1719: Waiting 
error parsing HTTP 413 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n"

**Comment by xiongyunhua-star** [comment]
Have a nginx proxy. set a client_max_body_size.  
It has been solved

**Comment by LinuxSuRen** [comment]
> Have a nginx proxy. set a client_max_body_size. It has been solved

But how to set the via helm chart?

**Comment by the-paulus** [comment]
@LinuxSuRen Either patch your harbor ingress by adding the following in .metadata.annotations:

```
nginx.ingress.kubernetes.io/proxy-body-size: 8m
```

You can also add this to the values file.
