### ISSUE TITLE
The label option is not align with the input field in replication rule edit dialog

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#15824]
Create some labels in the current Harbor instance.
Create a registry 
Create a replication rule with label filter. 
<img width="617" alt="Screen Shot 2021-10-20 at 2 35 55 PM" src="https://user-images.githubusercontent.com/2696760/138040597-3df76604-a344-4e91-9978-54a55211e843.png">

**Comment by AllForNothing** [comment]
another  css issue 
![image](https://user-images.githubusercontent.com/30999793/138073798-34c9ca3d-6093-4fc8-886d-c88ddea0570f.png)
