### ISSUE TITLE
The label should be editable when the replication rule is pull based

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#15825]
The current label filter field is a drop-down selection,  but for a pull-based replication, the label is defined in the source Harbor,  it might be some label string that is not defined in the current Harbor instance. suggest changing this field to be editable.

<img width="617" alt="Screen Shot 2021-10-20 at 2 35 55 PM" src="https://user-images.githubusercontent.com/2696760/138041796-fbf3ed04-566d-4ba6-a8c1-d74f2c468325.png">
BTW, this feature might make the user consider labels are replicated, but they aren't actually.

**Comment by bitsf** [comment]
dup https://github.com/goharbor/harbor/issues/8207

**Comment by bitsf** [comment]
@AllForNothing I think it would be better to make it editable just when user select pull-base replication, you can add a different widget
