### ISSUE TITLE
Cannot download images with oci media types via pull-through

### ISSUE THREAD

**Issue by mbarecki** [goharbor/harbor#15837]
Hello,

We are experiencing problems with pulling images via harbor pull-through proxy with `docker`.  
From the observations it does look like issues are occuring for images with these media types present in manifest list:
- `application/vnd.oci.image.manifest.v1+json`
- `application/vnd.oci.image.index.v1+json`  

Only as an example for describing situation image `eks-distro/kubernetes-csi/node-driver-registrar:v2.0.1-eks-1-18-1` stored in `public.ecr.aws` is used (similar behavior we observed with `ghcr.io`).  

We created project `publicecraws` in our local Harbor for ECR pull-through proxy.  
It is possible to pull image only once via Harbor ECR pull-through proxy - when it was not yet cached in Harbor.

Next pull and subsequent pulls are failing with such message:
```console
docker pull MY-LOCAL-HARBOR/publicecraws/eks-distro/kubernetes-csi/node-driver-registrar:v2.0.1-eks-1-18-1
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
```

No problems were observed when pulling mentioned image directly from upstream.

With image `public.ecr.aws/cloudwatch-agent/cloudwatch-agent:1.247349.0b251399` there are no issues downloading it via Harbor ECR pull-through proxy.  
This image has these media types present in manifest list:
- `application/vnd.docker.distribution.manifest.list.v2+json`
- `application/vnd.docker.distribution.manifest.v2+json`  

We are using Harbor version: `v2.3.2`

Do you have any suggestions why problems are observed when pulling mentioned image via Harbor ECR pull-through proxy ?

**Comment by stonezdj** [comment]
It is a bug, there are two types manifest list, manifest list v2 and image index v1, their media type is different. but the cache doesn't save the content type and consider they are manifest list

https://github.com/goharbor/harbor/blob/d00024ab36bfb7f2717cffdf973871026d2be743/src/controller/proxy/controller.go#L168
