### ISSUE TITLE
[ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID b9d4bdadccc731c09f0798bf not found"}]}

### ISSUE THREAD

**Issue by unixomg** [goharbor/harbor#15833]
I have encountered a new problem now. There is an error in jobservice.log. I don't know how to fix it. We are using the cluster mode of harbor and deploying postgres and redis separately. Some nodes report this error.

> Oct 21 13:29:02 172.18.0.1 jobservice[179519]: , evt=status change: job=fa9f1e87f0c8b7a8e676cbb0, status=Success, revision=1634715800->http://core:8080/service/notifications/tasks/113763, duration=1m27.172440508s
Oct 21 13:29:03 172.18.0.1 jobservice[179519]: 2021-10-21T05:29:03Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID ff8ec998290570c7e906e031 not found"}]}
Oct 21 13:29:03 172.18.0.1 jobservice[179519]: , evt=status change: job=ff8ec998290570c7e906e031, status=Error, revision=1634729492->http://core:8080/service/notifications/tasks/114930, duration=33.542492732s
Oct 21 13:29:03 172.18.0.1 jobservice[179519]: 2021-10-21T05:29:03Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID b9d4bdadccc731c09f0798bf not found"}]}
Oct 21 13:29:03 172.18.0.1 jobservice[179519]: , evt=status change: job=b9d4bdadccc731c09f0798bf, status=Error, revision=1634723006->http://core:8080/service/notifications/tasks/114390, duration=1m15.337988486s
Oct 21 13:29:04 172.18.0.1 jobservice[179519]: 2021-10-21T05:29:04Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 5f5faf2fa3504c629ce33077 not found"}]}
Oct 21 13:29:04 172.18.0.1 jobservice[179519]: , evt=status change: job=5f5faf2fa3504c629ce33077, status=Success, revision=1634722175->http://core:8080/service/notifications/tasks/114330, duration=1m2.946314003s
Oct 21 13:29:05 172.18.0.1 jobservice[179519]: 2021-10-21T05:29:05Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dba41a5a09b378e5f24f02e4 not found"}]}
Oct 21 13:29:05 172.18.0.1 jobservice[179519]: , evt=status change: job=dba41a5a09b378e5f24f02e4, status=Success, revision=1634723304->http://core:8080/service/notifications/tasks/114422, duration=41.335425389s
Oct 21 13:29:07 172.18.0.1 jobservice[179519]: 2021-10-21T05:29:07Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 503318c0372bac383cdfda64 not found"}]}

**Comment by alxbse** [comment]
I'm currently having this issue in a v2.4.0 install with messages like these filling up the logs of the jobservice pod making it hard to troubleshoot scheduling issues.

@unixomg Did you manage to solve the issue?

**Comment by creeea** [comment]
I have the same issue as @alxbse after I upgraded to v2.4.1
```
Jan 25 10:03:56 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1643073707, status=Scheduled, revision=1643073528->http://core:8080/service/notifications/jobs/replication/7, duration=5.668483949s
Jan 25 10:03:56 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:56Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dfc38c1099b142d2c35ed7f0@1643072566 not found"}]}
Jan 25 10:03:56 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1643072566, status=Scheduled, revision=1643072528->http://core:8080/service/notifications/jobs/replication/7, duration=22.081125964s
Jan 25 10:03:56 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:56Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID f2e6bf35684345ffc09b79af@1643062470 not found"}]}
Jan 25 10:03:56 192.168.96.1 jobservice[1333]: , evt=status change: job=f2e6bf35684345ffc09b79af@1643062470, status=Success, revision=1643062410->http://core:8080/service/notifications/jobs/replication/2, duration=1m20.119488084s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:159]: Retry: still failed after all retries: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dfc38c1099b142d2c35ed7f0@1642986882 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1642986882, status=Success, revision=1642986862->http://core:8080/service/notifications/jobs/replication/7
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dfc38c1099b142d2c35ed7f0@1643072844 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1643072844, status=Scheduled, revision=1643072774->http://core:8080/service/notifications/jobs/replication/7, duration=2.596552089s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 7dd130769b0f15862a97fb90@1642988755 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=7dd130769b0f15862a97fb90@1642988755, status=Success, revision=1642988739->http://core:8080/service/notifications/jobs/replication/8, duration=1m6.519318561s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dfc38c1099b142d2c35ed7f0@1642989533 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1642989533, status=Success, revision=1642989482->http://core:8080/service/notifications/jobs/replication/7, duration=17.419101426s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID 63d1d9db694cf7502d8b7864@1643070630 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=63d1d9db694cf7502d8b7864@1643070630, status=Success, revision=1643070533->http://core:8080/service/notifications/jobs/replication/1, duration=43.885640436s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [ERROR] [/jobservice/hook/hook_agent.go:155]: Retry: sending hook event error: {"errors":[{"code":"NOT_FOUND","message":"task with job ID dfc38c1099b142d2c35ed7f0@1642986799 not found"}]}
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: , evt=status change: job=dfc38c1099b142d2c35ed7f0@1642986799, status=Success, revision=1642986739->http://core:8080/service/notifications/jobs/replication/7, duration=59.720311707s
Jan 25 10:03:57 192.168.96.1 jobservice[1333]: 2022-01-25T09:03:57Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
```

**Comment by sidewinder12s** [comment]
I've had these errors getting thrown for a year plus. I suspected it was stale jobs in redis from before the Harbor Helm Chart renamed basically everything, since the jobs stored the hook address in the redis task itself rather than just looking it up as it processes them.

So now there are a bunch of jobs with invalid service addresses. Haven't gone into redis to try and validate however.

**Comment by adriannieto-attechnest** [comment]
How did you fix this issue? After we updated to 2.5.1 we are getting a HUGE spam of this being retried forever:

```
harbor-jobservice-5fcf4b5cf9-nk6g2 jobservice 2023-03-09T10:23:58.547675471+01:00 , evt=status change: job=5dc8f622cf95418fbb28517d, status=Error, revision=1678285523->https://harbor-core:443/service/notifications/tasks/915437, duration=1m26.046428994s
```

**Comment by WeiXie96** [comment]
Any update? I have the same problem in version 2.6.1

**Comment by kingnarmer** [comment]
I am having same issue with 2.8.2. Appreciate any help resolving.

**Comment by 0xj0el** [comment]
Any update facing same issue

**Comment by xiaobai2il** [comment]
any update? I'm also facing the same issue

**Comment by sidewinder12s** [comment]
We ended up just dumping redis when we moved it to ElastiCache and the problem went away. Otherwise I'd assume you need to manually clean out the redis instance of the bad keys.

**Comment by miminar** [comment]
Dumping it here in case it helps someone.

After renaming helm release from `proxy-cache` to `harbor`, we had the same issue:

```
[harbor-jobservice-8bc45f5cb-fg98s] 2024-03-18T10:04:39Z [ERROR] [/jobservice/hook/hook_agent.go:159]: Retry: still failed after all retries: Post "http://prox
y-cache-harbor-core:80/service/notifications/tasks/9368": dial tcp: lookup proxy-cache-harbor-core on 10.206.126.10:53: no such host, evt=status change: job=18
```

We solved it by renaming the web_hook_url in the redis database like this:

1. Created harbor-redis-fix-url.sh script:

    ```sh
    #!/usr/bin/env bash
    
    set -euo pipefail
    
    db=1  # harbor_job_service_namespace
    old_hostname=proxy-cache-harbor-core
    new_hostname=harbor-core
    
    function get_keys() {
        local db="$1"
        redis-cli -n "$db" --json keys '*' | jq -r '.[]'
    }
    
    function process_key() {
        local db="$1"
        local key="$2"
        local _type
        _type="$(redis-cli -n "$db" --json type "$key" | jq -r)"
        if [[ "$_type" != "hash" ]]; then
            return 0
        fi
        local value
        value="$(redis-cli -n "$db" --json hget "$key" web_hook_url | jq -r)"
        if ! grep -q -F "$old_hostname" <<<"$value"; then
            return 0
        fi
        local new_value
        new_value="${value/$old_hostname/$new_hostname}"
        printf 'updating web_hook_url of %s from %s to %s\n' "$key" "$value" "$new_value"
        # printf 'before: '; redis-cli -n "$db" --json hgetall "$key"
        redis-cli -n "$db" hset "$key" web_hook_url "$new_value"
        # printf 'after:  '; redis-cli -n "$db" --json hgetall "$key"
    }
    
    #for db in {0..7}; do
    for key in $(get_keys "$db"); do
        process_key "$db" "$key"
    done
    ```
    
1. copied scripts and bins to the redis pod:

    ```sh
    kubectl exec -n harbor -t harbor-redis-0 -- mkdir /var/lib/redis/bin
    kubectl cp -n harbor ./harbor-redis-fix-url.sh harbor-redis-0:/var/lib/redis/bin/
    curl -L -O https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64
    kubectl cp -n harbor ./jq-linux-amd64 harbor-redis-0:/var/lib/redis/jq
    kubectl exec -n harbor -t harbor-redis-0 -- chmod +x /var/lib/redis/bin/jq
    ```
    
1. executed into the redis pod and ran the script:

    ```sh
    $ kubectl exec -n harbor -it harbor-redis-0
    redis [ ~ ]$ export PATH="$PATH:/var/lib/redis/bin"
    redis [ ~ ]$ bash bin/harbor-redis-fix-url.sh
    ```

Apart from that we also identified `proxy-cache` vestige in a schedule in the database after dumping it with `pg_dump`, it has been updated like this:

1. exec'd into the database pod and connected to the registry database:
    
    ```sh
    $ kubectl exec -n harbor -it -c database harbor-database-0
    postgres [ / ]$ psql registry
    psql (14.10)
    Type "help" for help.
    registry=# 
    ````
    
1. updated `callback_func_param` of the entry:

    ```sql
    -- BEGIN;      -- dry-run
    UPDATE public.schedule
        SET callback_func_param = '{"trigger":null,"deleteuntagged":false,"dryrun":false,"extra_attrs":{"delete_untagged":false,"dry_run":false,"redis_url_reg":"redis://harbor-redis:6379/2?idle_timeout_seconds=30","time_window":2}}'
        WHERE id = 13;
    SELECT * FROM public.schedule WHERE id = 13;  -- check
    -- ROLLBACK;   -- revert
    ```
