### ISSUE TITLE
Two GC jobs were allowed to run in parallel

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#15830]
**Expected behavior and actual behavior:**
The system should not execute two GC jobs in parallel, however while testing things as part of the issue reported in #15822 we manually launched a GC job, while it was running the daily GC schedule also kicked in and a 2nd (Scheduled) GC job was started and now we have two of them running in parallel:

![image](https://user-images.githubusercontent.com/61992380/138126915-52c3e627-b3fe-47d4-a28a-99ff74be92b0.png)

I'm assuming this shouldn't happen and not sure how these two are actually working in parallel and what they are doing, we also have no way of stopping them.

**Steps to reproduce the problem:**
1. Start a GC job manually
2. Configure a scheduled GC to start shortly after
3. notice the scheduled GC jobs is triggered too and now two GC jobs are running in parallel

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.3
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

N/A

**Comment by wy65701436** [comment]
Move it to 2.6 per discussion with @steven-zou

**Comment by wy65701436** [comment]
move out 2.6 per discuss.
