### ISSUE TITLE
Creating project using API, Limit not concidered

### ISSUE THREAD

**Issue by ehsansh84** [goharbor/harbor#15855]
**Expected behavior and actual behavior:**
When I define a project using storage_limit, I expect when it will be considered

**Steps to reproduce the problem:**
Request to /projects
sending these parameters:
```
    params = {
        "project_name": 'my_project',
        "public": 'private',
        "storage_limit": 1000
    }
```

And these headers:
```
USER_HEADERS = {
        'accept': 'application/json',
        'Content-Type': 'application/json',
        'authorization': 'Basic ZWhzYW46QWFAMTIzNDU2',
    }
```
After the request is made, project is created but in the panel it says that storage used: 0 byte of unlimited.

- harbor version: [2.3.3]
- docker engine version: [20.10.8]
- docker-compose version: [1.29.2]

**Comment by heww** [comment]
The storage limitation setting is only accepted when the user creating the project is a system administrator.

Please check that the user `ehsan` is a system administrator.
