### ISSUE TITLE
Scheduled Garbage Collector Error Not Found

### ISSUE THREAD

**Issue by Grounz** [goharbor/harbor#15850]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Hi,

I have upgrade Harbor to 2.3.3 from 2.2.3 and i have this error when i run GC with scheduler:

`json
{
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "{\"code\":10010,\"message\":\"object is not found\",\"details\":\"f7d54004a275590aeccd94ee\"}"
    }
  ]
}`

Jobserver.log in time range:

`
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: 2021-10-17T00:00:01Z [ERROR] [/jobservice/runner/redis.go:152]: Run job GARBAGE_COLLECTION:f7d54004a275590aeccd94ee error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 61 [running]:
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2(0xc0013217d0, 0xc00078ba40)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/runner/redis.go:150 +0xa5
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: panic(0x28b80c0, 0xc000cfbdd0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/usr/local/go/src/runtime/panic.go:975 +0x47a
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc000d0ef30, 0xc000c592c0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x365
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).init(0xc000d0ef30, 0x2eb5860, 0xc000e29e50, 0xc000c592c0, 0x7, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:109 +0x313
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc000d0ef30, 0x2eb5860, 0xc000e29e50, 0xc000c592c0, 0xc000e29e50, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:151 +0x4d
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc000413a70, 0xc00078ba40, 0x0, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/runner/redis.go:212 +0xc55
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: 2021-10-17T00:00:01Z [ERROR] [/jobservice/runner/redis.go:113]: Job 'GARBAGE_COLLECTION:f7d54004a275590aeccd94ee' exit with error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 61 [running]:
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2(0xc0013217d0, 0xc00078ba40)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/runner/redis.go:150 +0xa5
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: panic(0x28b80c0, 0xc000cfbdd0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/usr/local/go/src/runtime/panic.go:975 +0x47a
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc000d0ef30, 0xc000c592c0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x365
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).init(0xc000d0ef30, 0x2eb5860, 0xc000e29e50, 0xc000c592c0, 0x7, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:109 +0x313
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc000d0ef30, 0x2eb5860, 0xc000e29e50, 0xc000c592c0, 0xc000e29e50, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:151 +0x4d
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc000413a70, 0xc00078ba40, 0x0, 0x0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/runner/redis.go:212 +0xc55
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: github.
`

**Steps to reproduce the problem:**
Upgrade to 2.3.3 from 2.2.3.
Configurer gc in scheduler (cron)

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.3
- docker engine version: 18.09.3,
- docker-compose version: 1.18.0

**Logs**
[jobserver.log](https://github.com/goharbor/harbor/files/7395095/jobserver.log)

**Comment by steven-zou** [comment]
@wy65701436 

Please double check if there are type mismatch when parsing parameters of GC job.


>github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc000d0ef30, 0xc000c592c0)
Oct 17 02:00:01 172.18.0.1 jobservice[2857]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x365

```
// parseParams set the parameters according to the GC API call.
func (gc *GarbageCollector) parseParams(params job.Parameters) {
	// redis url
	gc.redisURL = params["redis_url_reg"].(string)
```

**Comment by wy65701436** [comment]
are you using the build-in redis or external?

**Comment by Grounz** [comment]
Hi,

We use build in redis.

**Comment by lindhe** [comment]
I once got a similar error in the vulnerability scanning, when the `jobservice` pod ran out of disk space. Could that be the issue here also?

**Comment by Grounz** [comment]
@lindhe In my case i have a free disk space :/

**Comment by Vad1mo** [comment]
related to #16010

**Comment by shoeffner** [comment]
We have the same issue. We are running the docker-compose stack and the core container _REDIS_URL_REG matches Grounz's.
The failing line is https://github.com/goharbor/harbor/blob/44bfb992f48d54905c48b38997b3e39b103af277/src/jobservice/job/impl/gc/garbage_collection.go#L113, although we are still on harbor 2.4.1 where this is line 116.
It seems that for scheduled GC, params["redis_url_reg"] is nil:
 ```
Jun 21 02:00:01 registry jobservice[25294]: 2022-06-21T00:00:01Z [ERROR] [/jobservice/runner/redis.go:166]: Run job GARBAGE_COLLECTION:5d0a81871abfef6c65cfdec5 error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 86 [running]:
Jun 21 02:00:01 registry jobservice[25294]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2()
Jun 21 02:00:01 registry jobservice[25294]: #011/harbor/src/jobservice/runner/redis.go:164 +0x7b
Jun 21 02:00:01 registry jobservice[25294]: panic({0x276d1a0, 0xc001fcdcb0})
Jun 21 02:00:01 registry jobservice[25294]: #011/usr/local/go/src/runtime/panic.go:1047 +0x266
Jun 21 02:00:01 registry jobservice[25294]: panic({0x276d1a0, 0xc001fcdcb0})
Jun 21 02:00:01 registry jobservice[25294]: #011/usr/local/go/src/runtime/panic.go:1047 +0x266
Jun 21 02:00:01 registry jobservice[25294]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc001104360, 0x6)
Jun 21 02:00:01 registry jobservice[25294]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x288
Jun 21 02:00:01 registry jobservice[25294]: panic({0x276d1a0, 0xc001fcdcb0})
Jun 21 02:00:01 registry jobservice[25294]: #011/usr/local/go/src/runtime/panic.go:1047 +0x266
Jun 21 02:00:01 registry jobservice[25294]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc001104360, 0x6)
Jun 21 02:00:01 registry jobservice[25294]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x288
Jun 21 02:00:01 registry jobservice[25294]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).init(0xc001104360, {0x2dd9aa0, 0xc00014cdc0}, 0x14d84e9)
Jun 21 02:00:01 registry jobservice[25294]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:109 +0x30e
```

Manually triggering the garbage collection works fine.
A simple solution might be something along these lines:
```patch
From 0da4b2868074989994d3e9e739d62bcedff22033 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Sebastian=20H=C3=B6ffner?=
 <sebastian.hoeffner@mevis.fraunhofer.de>
Date: Tue, 21 Jun 2022 12:00:58 +0200
Subject: [PATCH] Default redis_url_reg

---
 src/jobservice/job/impl/gc/garbage_collection.go | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/src/jobservice/job/impl/gc/garbage_collection.go b/src/jobservice/job/impl/gc/garbage_collection.go
index 5260032e4..fc5f2e296 100644
--- a/src/jobservice/job/impl/gc/garbage_collection.go
+++ b/src/jobservice/job/impl/gc/garbage_collection.go
@@ -110,7 +110,13 @@ func (gc *GarbageCollector) init(ctx job.Context, params job.Parameters) error {
 // parseParams set the parameters according to the GC API call.
 func (gc *GarbageCollector) parseParams(params job.Parameters) {
 	// redis url
-	gc.redisURL = params["redis_url_reg"].(string)
+	gc.redisURL = "redis://redis:6379/1?idle_timeout_seconds=30"
+	redisURL, exist := params["redis_url_reg"]
+	if exist {
+		if url, ok := redisURL.(string); ok {
+			gc.redisURL = url
+		}
+	}
 
 	// delete untagged: default is to delete the untagged artifact
 	gc.deleteUntagged = true
-- 
2.36.1
```
But this would probably only work for docker setups with default arguments and does not solve the root cause of e.g. faulty env variables in the job schedule.
Better would be to pass the correct parameters right away, but I didn't have the time to dig deeper into the code base yet.

**Comment by shoeffner** [comment]
This is still unresolved.
