### ISSUE TITLE
Where is the performance limit of harbor?

### ISSUE THREAD

**Issue by unixomg** [goharbor/harbor#15857]
Now there is such a problem. When we performed a single-machine stress test, we found that multiple clients concurrently push mirrors. The current total number of concurrent pushes is more than 80. Our back-end storage uses S3. When the pressure goes up, we use the harbor. The exporter monitoring found that the indicator of harbor_core_http_inflight_requests has not been able to go up, this value can only be up to 20,and the time to push a mirror increased from 30 seconds to 200 seconds. I want to know what restrictions does the harbor itself have?
![harbor](https://user-images.githubusercontent.com/25821142/138553815-c8be5b1f-67c1-4d9f-a87e-8c8dc4771029.png)

![harbor3](https://user-images.githubusercontent.com/25821142/138554732-01622a03-d033-4318-91fe-f46f684e7ec6.png)

**Comment by Jeremy-boo** [comment]
Can you provide harbor version information and harbor database connection setting information, such as the maximum number of connections to the database.
You can also observe the harbor-core log in the concurrent test to see if there are some obvious error logs
