### ISSUE TITLE
unexpected EOF in Proxy (http proxy error) while push image to harbor (skopeo copy)

### ISSUE THREAD

**Issue by andijurt** [goharbor/harbor#15876]
We are monitoring our Harbor-Registry (v2.1.5) with a recurring cronjob (every 10min) by pushing a Docker-Image. We are copying this docker-image (1 Layer - approx. 80MB) with skopeo from an OpenShift-Pod to the Harbor-Registry. In irregular intervalls, the skopeo copy process aborts with the following exception:

*******************************
Trying to copy test image /test-image/ubi.tar to <harbor-url>/columbo-intern/harbor-checker/ubi8/ubi:latest
skopeo copy --authfile /home/toolset/auth.json tarball:/test-image/ubi.tar docker://<harbor-url>/columbo-intern/harbor-checker/ubi8/ubi:latest
b'time="2021-10-25T13:21:23+02:00" level=fatal msg="Error writing blob: Patch \\"https://<harbor-url>/v2/columbo-intern/harbor-checker/ubi8/ubi/blobs/uploads/511198c3-9e43-4735-8beb-f7141a0d9609?_state=L1Gn8MD2n8fkwaTrUfo2rudqc638ef-QNFeP3fFLF5h7Ik5hbWUiOiJjb2x1bWJvLWludGVybi9oYXJib3ItY2hlY2tlci91Ymk4L3ViaSIsIlVVSUQiOiI1MTExOThjMy05ZTQzLTQ3MzUtOGJlYi1mNzE0MWEwZDk2MDkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMTAtMjVUMTE6MjE6MjAuODE3NjY0NDY0WiJ9\\": write tcp 10.255.12.227:60448->10.99.36.227:443: **write: connection reset by peer"\n'**
*******************************

Harbor aborts the http-connection by  sending the http-error 400 (incl. tcp rst-pkg).

Logfiles in Harbor:
Proxy.log:
*******************************
Oct 25 13:21:23 172.23.0.1 proxy[1330]: 10.180.138.203 - "PATCH /v2/columbo-intern/harbor-checker/ubi8/ubi/blobs/uploads/511198c3-9e43-4735-8beb-f7141a0d9609?_state=L1Gn8MD2n8fkwaTrUfo2rudqc638ef-QNFeP3fFLF5h7Ik5hbWUiOiJjb2x1bWJvLWludGVybi9oYXJib3ItY2hlY2tlci91Ymk4L3ViaSIsIlVVSUQiOiI1MTExOThjMy05ZTQzLTQ3MzUtOGJlYi1mNzE0MWEwZDk2MDkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMTAtMjVUMTE6MjE6MjAuODE3NjY0NDY0WiJ9 **HTTP/1.1" 400 0** "-" "skopeo/1.3.2-dev" 2.065 2.065 .
*******************************

Registry.log:
*******************************
Oct 25 13:21:23 172.23.0.1 registry[1330]: time="2021-10-25T11:21:23.058802989Z" level=error msg="**client disconnected during blob PATCH**" auth.user.name="harbor_registry_user" contentLength=-1 copied=12419550 error=**"unexpected EOF"** go.version=go1.14.13 http.request.contenttype="application/octet-stream" http.request.host=<harbor-url> http.request.id=4c6b64c3-0cd7-4538-8964-85caed1373c6 http.request.method=PATCH http.request.remoteaddr=10.180.138.203 http.request.uri="/v2/columbo-intern/harbor-checker/ubi8/ubi/blobs/uploads/511198c3-9e43-4735-8beb-f7141a0d9609?_state=L1Gn8MD2n8fkwaTrUfo2rudqc638ef-QNFeP3fFLF5h7Ik5hbWUiOiJjb2x1bWJvLWludGVybi9oYXJib3ItY2hlY2tlci91Ymk4L3ViaSIsIlVVSUQiOiI1MTExOThjMy05ZTQzLTQ3MzUtOGJlYi1mNzE0MWEwZDk2MDkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMTAtMjVUMTE6MjE6MjAuODE3NjY0NDY0WiJ9" http.request.useragent="skopeo/1.3.2-dev" vars.name="columbo-intern/harbor-checker/ubi8/ubi" vars.uuid=511198c3-9e43-4735-8beb-f7141a0d9609
*******************************

When we execute the same skopeo copy commands locally (same node where harbor-core/-proxy is running), the error does not occur.

We are currently at a loss as to why this is happening and are looking for Input on how to troubleshoot this issue further.

Best regards,
Andi

**Comment by j4ckstraw** [comment]
I have the same problem

**Comment by j4ckstraw** [comment]
we deploy harbor v2.3.1 with docker-compose,  and meet the same problem.

user push image with kaniko, got `reset by peer` like this:
```
Pushing image to [example.com/transformers/transformers-dev:staging-d0f63f4c](http://example.com/transformers/transformers-dev:staging-d0f63f4c) 
error pushing image: failed to push to destination [example.com/transformers/transformers-dev:staging-d0f63f4c](http://example.com/transformers/transformers-dev:staging-d0f63f4c): Patch "https://example.com/v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9": write tcp [10.119.97.216:53746](http://10.119.97.216:53746/)->[10.108.196.199:443](http://10.108.196.199:443/): write: connection reset by peer
```

proxy(which is nginx) response with 400 bad request, like this:
```
Apr 13 14:45:46 172.18.0.1 proxy[4584]: 10.119.97.216 - "PATCH /v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9 HTTP/1.1" 400 0 "-" "kaniko/v1.5.1" 10.990 10.992 .
```

registry return with 500 because `client disconnected during blob PATCH`: 
```
Apr 13 14:45:35 172.18.0.1 registry[4584]: time="2022-04-13T06:45:35.039320417Z" level=info msg="authorized request" go.version=go1.16 http.request.host=example.com http.request.id=a2287253-0306-4ac5-8a03-1664980c027a http.request.method=PATCH http.request.remoteaddr=10.119.97.216 http.request.uri="/v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9" http.request.useragent="kaniko/v1.5.1" vars.name="transformers/transformers-dev" vars.uuid=71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab 
Apr 13 14:45:46 172.18.0.1 registry[4584]: time="2022-04-13T06:45:46.090138686Z" level=error msg="client disconnected during blob PATCH" auth.user.name="harbor_registry_user" contentLength=-1 copied=510227635 error="unexpected EOF" go.version=go1.16 http.request.host=example.com http.request.id=a2287253-0306-4ac5-8a03-1664980c027a http.request.method=PATCH http.request.remoteaddr=10.119.97.216 http.request.uri="/v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9" http.request.useragent="kaniko/v1.5.1" vars.name="transformers/transformers-dev" vars.uuid=71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab
Apr 13 14:45:47 172.18.0.1 registry[4584]: time="2022-04-13T06:45:47.426664433Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="client disconnected" err.message="unknown error" go.version=go1.16 http.request.host=example.com http.request.id=a2287253-0306-4ac5-8a03-1664980c027a http.request.method=PATCH http.request.remoteaddr=10.119.97.216 http.request.uri="/v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9" http.request.useragent="kaniko/v1.5.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=12.395099606s http.response.status=500 http.response.written=89 vars.name="transformers/transformers-dev" vars.uuid=71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab 
Apr 13 14:45:47 172.18.0.1 registry[4584]: 172.18.0.6 - - [13/Apr/2022:06:45:35 +0000] "PATCH /v2/transformers/transformers-dev/blobs/uploads/71f86ddf-7fc5-4de8-9c1d-29f73c7ce5ab?_state=VCiM14f-3wY3XAEYnqVzR0wIIquAUDjFGPIte6wB-1x7Ik5hbWUiOiJ0cmFuc2Zvcm1lcnMvdHJhbnNmb3JtZXJzLWRldiIsIlVVSUQiOiI3MWY4NmRkZi03ZmM1LTRkZTgtOWMxZC0yOWY3M2M3Y2U1YWIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDQtMTNUMDY6NDU6MzUuMDA4NzY5NDczWiJ9 HTTP/1.1" 500 89 "" "kaniko/v1.5.1"
```

by read the `distribution` [source code](https://github.com/distribution/distribution/blob/main/registry/handlers/helpers.go#L57), I figure out that clientClosed cause the `client disconnected during blob PATCH`, while user got `reset by peer`, which means server close the connection. I'm confused.  help!

**Comment by drehpehs** [comment]
Hi Sir,

Any update on this? We also got the same issue. 

The error pattern
- PATCH request with 400 code in proxy.log
`Sep 27 02:03:37 240.0.1.1 proxy[20264]: 100.99.80.66 - "PATCH /v2/scp-dev/scp-calculation/blobs/uploads/a29aec1d-6d09-4adc-8a73-98187f336455?_state=bk1FiX702AzE_qssqh-PgJe75KWrbXKWG8TeqRBQ1Mx7Ik5hbWUiOiJzY3AtZGV2L3NjcC1jYWxjdWxhdGlvbiIsIlVVSUQiOiJhMjlhZWMxZC02ZDA5LTRhZGMtOGE3My05ODE4N2YzMzY0NTUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDktMjdUMDE6NTM6NDEuODk3MjIyNjYyWiJ9 HTTP/1.1" 400 0 "-" "docker/18.06.3-ce go/go1.10.8 git-commit/d7080c1 kernel/4.19.56-coreos-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \x5C(linux\x5C))" 595.504 595.504 .`

- client disconnected during blob PATCH (PATCH request with 500 code) in registry.log
`Sep 27 02:03:37 240.0.1.1 registry[20264]: time="2022-09-27T02:03:37.50492042Z" level=error msg="client disconnected during blob PATCH" auth.user.name="harbor_registry_user" contentLength=-1 copied=30021322 error="unexpected EOF" go.version=go1.15.6 http.request.host=registry-jpe2.r-local.net http.request.id=d3b6fa5c-56de-4393-a626-abee6192ca61 http.request.method=PATCH http.request.remoteaddr=100.99.89.1 http.request.uri="/v2/scp-dev/scp-calculation/blobs/uploads/a29aec1d-6d09-4adc-8a73-98187f336455?_state=bk1FiX702AzE_qssqh-PgJe75KWrbXKWG8TeqRBQ1Mx7Ik5hbWUiOiJzY3AtZGV2L3NjcC1jYWxjdWxhdGlvbiIsIlVVSUQiOiJhMjlhZWMxZC02ZDA5LTRhZGMtOGE3My05ODE4N2YzMzY0NTUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDktMjdUMDE6NTM6NDEuODk3MjIyNjYyWiJ9" http.request.useragent="docker/18.06.3-ce go/go1.10.8 git-commit/d7080c1 kernel/4.19.56-coreos-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \(linux\))" vars.name="scp-dev/scp-calculation" vars.uuid=a29aec1d-6d09-4adc-8a73-98187f336455`
`Sep 27 02:18:07 240.0.1.1 registry[20264]: 240.0.1.7 - - [27/Sep/2022:01:53:41 +0000] "PATCH /v2/scp-dev/scp-calculation/blobs/uploads/a29aec1d-6d09-4adc-8a73-98187f336455?_state=bk1FiX702AzE_qssqh-PgJe75KWrbXKWG8TeqRBQ1Mx7Ik5hbWUiOiJzY3AtZGV2L3NjcC1jYWxjdWxhdGlvbiIsIlVVSUQiOiJhMjlhZWMxZC02ZDA5LTRhZGMtOGE3My05ODE4N2YzMzY0NTUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDktMjdUMDE6NTM6NDEuODk3MjIyNjYyWiJ9 HTTP/1.1" 500 89 "" "docker/18.06.3-ce go/go1.10.8 git-commit/d7080c1 kernel/4.19.56-coreos-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \\(linux\\))"`

We are using docker-compose with Harbor v2.2.2 and s3 storage.
When there are lots of images pushing at the same time, the layers could encounter retrying and eventually got 504 Gateway Timeout.

It doesn't happen every time. But when it occurs, it could block the following images push even the size of them are small.
Also the Sockstat TCP memory size and the number of concurrent connections also got peak in our monitoring.
Temporary solution: restart the harbor containers can relieve the situation.

Do you have any idea for this?

**Comment by XuShaohui** [comment]
same above. is there any clue or update on this issue?

**Comment by Tireur2cables** [comment]
Having the same problem here, I would love some updates on this

**Comment by Tireur2cables** [comment]
> this might be related to your case too:
> 
> https://cloud-native.slack.com/archives/CC1E09J6S/p1736332560877279?thread_ts=1734709438.226199&cid=CC1E09J6S

Hi thanks for sharing but an authentication is needed to access the content.
Maybe you can paste the related content or solution here.
