### ISSUE TITLE
Sticky project search filter in web ui

### ISSUE THREAD

**Issue by jared-schmidt-civ** [goharbor/harbor#15889]
One of the most annoying and common scenarios in the web ui is the following:

A user navigates to an enormous project with hundreds or thousands of repositories.  The user types a string in the "Filter Repositories" field to narrow down the search.  Multiple results are presented.  The user wants to view multiple repositories quickly for a number of different reasons.  The user clicks on a repository to get more information about available tags or even further clicks on a hash to get more details.  When the user navigates back to the project in the browser using either the back button or the breadcrumb navigation, the filter is gone and the user has to retype it.

Please make the search filter in the project view "sticky" so that the user does not need to repeatedly type in the filter.  The filter could be cleared by clicking an "x" by the search field or something like that.  This one feature would make navigating a target subset of repositories in a project so much smoother and faster.

**Comment by AllForNothing** [comment]
@jared-schmidt-civ Thanks for your info.
Currently, Harbor UI will reload the related component for every routing action, and this ensures that the latest data is displayed on the page, but surely annoying for the use cases you mentioned.

And we are enabling the right-click to open a link in a new tab, see #15436. It can meet this demand to a certain extent

As for the solution you mentioned, it looks really good, but a little bit complex. We will discuss it, and try to find  the best solution at the code level
