### ISSUE TITLE
Vulnerable middleware always used for HEAD requests

### ISSUE THREAD

**Issue by rofafor** [goharbor/harbor#15885]
**Expected behavior and actual behavior:**

`docker/build-push-action@v2` action can't re-publish a fixed image if `Prevent vulnerable images from running` has been enabled due to the fact that it makes a `HEAD` request to manifest before `PUT` and the `HEAD` request fails due to the  pre-condition failure. This issue has been introduced in https://github.com/goharbor/harbor/pull/15056

In order to circumvent this issue, one must temporarily allow pulling vulnerable images in the project settings while pushing the fixed image.

**Steps to reproduce the problem:**

1. Enable `Prevent vulnerable images from running.` in project settings.
2. Build and push image containing vulnerabilities via GHA's `docker/build-push-action@v2` action
3. Retry step 2 by re-running the workflow and push fails due to `412 Precondition failed`

**Versions:**

- harbor version: v2.3.3-a0a9ed8a
- GHA runner docker version: 20.10.8
- GHA runner containerd version: e25210fe30a0a703442421b0f60afac609f950a3
- GHA runner buildx plugin version: Build with BuildKit (Docker Inc., v0.6.3)
- GHA action: docker/build-push-action@v2

**Additional context:**

GHA step log:
```
#20 exporting to image
#20 pushing layers 5.1s done
#20 pushing manifest for harbor.my.company/foo/bar/tfrontend:master@sha256:b73e0b1d9d1e27490fd8a5e9248919759038523e9d6dca4528775b78cfb27229
#20 pushing manifest for harbor.my.company/foo/bar/frontend:master@sha256:b73e0b1d9d1e27490fd8a5e9248919759038523e9d6dca4528775b78cfb27229 0.2s done
#20 ERROR: unexpected status: 412 Precondition Failed
------
 > exporting to image:
------
error: failed to solve: unexpected status: 412 Precondition Failed
Error: buildx failed with: error: failed to solve: unexpected status: 412 Precondition Failed
```

proxy.log:
```
Oct 27 09:39:04 172.19.0.1 proxy[952]: x.x.x.x - "PUT /v2/foo/bar/rontend/blobs/uploads/a9da9df8-1a3d-479f-a4fb-0a38178c9f15?_state=xxx&digest=sha256%3Aec357d73405b70154d928dad5f04931e7a8a2f16ca6f9baa238a070828496148 HTTP/1.1" 201 0 "-" "containerd/1.5.3+unknown" 4.153 4.153 .
Oct 27 09:39:04 172.19.0.1 proxy[952]: x.x.x.x - "PUT /v2/foo/bar/frontend/blobs/uploads/a8940d83-af95-4432-abce-902869ba3b9c?_state=xxx&digest=sha256%3A1267712ebad26f085f8542e1fe1a313a47ebec10d028835811a405f03a51998f HTTP/1.1" 201 0 "-" "containerd/1.5.3+unknown" 3.611 3.611 .
Oct 27 09:39:04 172.19.0.1 proxy[952]: x.x.x.x - "HEAD /v2/foo/bar/frontend/manifests/latest HTTP/1.1" 412 0 "-" "containerd/1.5.3+unknown" 0.172 0.171 .
```

**Comment by sizowie** [comment]
Duplicates issue https://github.com/goharbor/harbor/issues/15283
