### ISSUE TITLE
Updating database. Failed to connect DB after 30 seconds, time out on Notary server and Signer.

### ISSUE THREAD

**Issue by netanbu** [goharbor/harbor#15898]
Hi,

I did setup harbor HA with external posgres, redis. All pods are sucessfully running.  But notary pods were stuck CrashLoopBackOff state. Could you please advise what could be the error ?   The logs of the both notary pods shows.

_Updating database. 
Failed to connect DB after 30 seconds, time out_ 

PFB pod status.
kubectl get pods -n harbor

NAME                                             READY   STATUS             RESTARTS   AGE
harbor-release1-chartmuseum-7bbbf46d44-trlvb     1/1     Running            0          6h15m
harbor-release1-core-6577b7fdbd-xrfvz            1/1     Running            0          104m
harbor-release1-jobservice-54d66dd554-zkr5p      1/1     Running            0          101m
harbor-release1-notary-server-7df94cdd4b-5mlgb   0/1     **CrashLoopBackOff**   47         4h3m
harbor-release1-notary-signer-ff6dcfd68-mg6n9    0/1     **CrashLoopBackOff**   47         4h3m
harbor-release1-portal-b9d7947c4-s29gz           1/1     Running            0          110m
harbor-release1-registry-584fcdcc94-g4nhr        2/2     Running            0          109m
harbor-release1-trivy-0                          1/1     Running            0          6h14m
 
kubectl get pods -n pgo  ==>  posgres 
NAME                                               READY   STATUS      RESTARTS   AGE
backrest-backup-pgo4harbor-lw9vg                   0/1     Completed   0          6h13m
pgo-deploy-rdq5r                                   0/1     Completed   0          5d18h
pgo4harbor-575c8fdc79-9mk8d                        1/1     Running     0          6h18m
pgo4harbor-backrest-shared-repo-7d6ddb4446-fzszn   1/1     Running     0          6h19m
pgo4harbor-pgadmin-6b85cf6b4c-5g24j                1/1     Running     0          6h17m
postgres-operator-6b48fbc879-2k6m4                 4/4     Running     144        5d18h

kubectl get pods -n redis

NAME                                 READY   STATUS    RESTARTS   AGE
haproxy-deployment-8bf7665cc-6kz94   1/1     Running   2          27h
haproxy-deployment-8bf7665cc-9wvcc   1/1     Running   2          27h
redis-0                              1/1     Running   0          6h19m
redis-1                              1/1     Running   0          6h17m
redis-2                              1/1     Running   0          6h16m
sentinel-0                           1/1     Running   0          6h19m
sentinel-1                           1/1     Running   0          6h16m
sentinel-2                           1/1     Running   0          6h16m

**Comment by wy65701436** [comment]
what's the Harbor & helm version? Please provide the log as well. BTW, you can file helm issue on the helm repo.

**Comment by tribock** [comment]
same issue here:
harbor version: v2.4.1
postgres version: 13
operator: crunchy
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
        - host all all 10.0.0.0/8 md5
        - host all all 10.0.0.0/8 password

**Comment by k9ne257** [comment]
Was this issue ever resolved? Am having a similar problem. I'd really appreciate it if you have any ideas on how to solve it.

**Comment by francesco-furnari** [comment]
I have the same issue.
