### ISSUE TITLE
Username for External Redis is hardcoded

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#15895]
There is no way to configure External Redis username since it is hardcoded as `redis`.
See: `{{- define "harbor.redis.url" -}}`
Historically Redis didn't supported different users, so username didn't mattered.
But from version 6.0.0 it can also verify passed username:
https://redis.io/commands/auth
It would be nice to have an option to configure username too.

**Comment by MinerYang** [comment]
We considered not to add/support external redis username for Harbor 2.5.0 currently, because redis v6.0+ has not been supported in other dependency like `github.com/astaxie/beego`. 
beego upgrade issue: https://github.com/beego/beego/issues/4861

**Comment by verenion** [comment]
Any chance of this being looked at again?

**Comment by MinerYang** [comment]
We will

**Comment by jowko** [comment]
Issue is still not resolved.

**Comment by viceice** [comment]
not stale, still an issue

**Comment by MinerYang** [comment]
https://github.com/goharbor/harbor/issues/18892
DO NOT USE external redis username which would affect distribution performance on push and pulling
