### ISSUE TITLE
WebUI Group pagination missing in v2.4.0

### ISSUE THREAD

**Issue by drshawnkwang** [goharbor/harbor#15906]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Actual behavior: Groups listed on website has no pagination.

Expected behavior: Groups listed on website has a pagination in lower-right to page through all groups. I know in v2.3.3 there were 43 groups total, with pagination to scroll through multiple groups.

**Steps to reproduce the problem:**
Installed Harbor v2.4.0 from v2.3.3

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.4.0]
- docker engine version: [20.10.10]
- docker-compose version: [1.29.2]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
![harbor-bug-groups](https://user-images.githubusercontent.com/18352107/139476894-b2df0330-1cbb-4b55-b8f6-b84a3f3bd4ed.png)

**Comment by wy65701436** [comment]
can you provide the API response？

**Comment by drshawnkwang** [comment]
I went to the webUI API explorer page and selected the **GET /usergroups Get all user groups information** API call.

The default `page_size` is 10, and when I run this query I get 10 groups.

```
curl -X 'GET' \
  'https://harbor.example.net/api/v2.0/usergroups?page=1&page_size=10' \
  -H 'accept: application/json'
```

If I change `page_size` to 100, this query returns 45 groups. (Two more than I had originally thought; but that is because my user was added to two LDAP groups recently.)
```
curl -X 'GET' 
  'https://harbor.example.net/api/v2.0/usergroups?page=1&page_size=100' \
  -H 'accept: application/json'
```

Lastly if I change the API settings to `page` to 2 and `page_size` to 10. I get 10 groups and they are the "next ten" 
```
curl -X 'GET' \
  'https://harbor.example.net/api/v2.0/usergroups?page=2&page_size=10' \
  -H 'accept: application/json'
```

I can post the JSON output of the groups but it's rather long and I would have to sanitize the output for privacy reasons. Do you still want me to post it?

**Comment by AllForNothing** [comment]
@drshawnkwang Thanks for your info. It is enough to confirm this UI issue.
Once the fixing PR is merged, you can fetch the code and then rebuild your Harbor to apply the bug fixing
