### ISSUE TITLE
Page occlusion

### ISSUE THREAD

**Issue by jpgkudo** [goharbor/harbor#15909]
url: https://goharbor.io/docs/2.3.0/install-config/configure-yml-file/

![image](https://user-images.githubusercontent.com/51149477/139586569-88841964-0c37-4a4a-9cad-db12af23620f.png)

**Comment by AllForNothing** [comment]
@jpgkudo Thanks for the info.
Please move this issue to [goharbor/website](https://github.com/goharbor/website)

**Comment by jpgkudo** [comment]
....那你移一下，不是什么大问题，昨天看文档发现的。

**Comment by AllForNothing** [comment]
Move to https://github.com/goharbor/website/issues/262
