### ISSUE TITLE
Error EOF / 503 on image push when using redis as session store

### ISSUE THREAD

**Issue by pablo-ruth** [goharbor/harbor#15901]
Hello,

We have a bug using Harbor (v2.3.2), with redis for session storage, where we randomly see 503 error on image push. After some digging we found that the problem is in Beego on the redis pool configuration. There is no "TestOnBorrow" func defined (https://github.com/astaxie/beego/blob/v1.12.1/session/redis/sess_redis.go#L160), so in case redis timeout a connection it can still be returned from the pool and then when a call is made to start a session it can fail with a EOF / 503 (https://github.com/astaxie/beego/blob/v1.12.1/router.go#L718). It's easy to fix, we just have to add the TestOnBorrow like this one in Harbor (https://github.com/goharbor/harbor/blob/master/src/lib/redis/redisclient.go#L72).

So the problem is not in Harbor, but I have questions on how I can contribute to this fix.

I see in Harbor dependencies that "github.com/astaxie/beego" is used and not "github.com/beego/beego" and I wonder why and on which one I have to do the PR ?

I also see that in v2 of "github.com/beego/beego" the problem doesn't exist anymore because there is a new redis library used, before it was "github.com/gomodule/redigo/redis" and now it's "github.com/go-redis/redis/v7" (https://github.com/beego/beego/blob/v2.0.1/server/web/session/redis/sess_redis.go#L157). So does Harbor have plans to upgrade to beego v2 ?

Thanks,

**Comment by wy65701436** [comment]
We can evaluate to upgrade beego v2.
