### ISSUE TITLE
Unable to delete artifacts with robot account

### ISSUE THREAD

**Issue by manuschillerdev** [goharbor/harbor#15904]
**Expected behavior and actual behavior:**
A robot account with the permissions "Delete Artifact" and "Delete Tag" set via the GUI  should be able to delete images from the registry.

**Steps to reproduce the problem:**
* create a robot account in a project and give it the following permission: "Delete Artifact" and "Delete Tag"
* push an Image to the project
* try to delete the image with any docker v2 client (in this example [reg](https://github.com/genuinetools/reg))
```bash
reg digest my.registry.acme/project/image -u "robot\$project-robot" -p "***redacted***"
> b8ac37c2299ed4214dfb355f12033e2eb4559bcf36b6fddb647ca3ec14c05396

reg rm my.registry.acme/project/image@sha256:b8ac37c2299ed4214dfb355f12033e2eb4559bcf36b6fddb647ca3ec14c05396 -u "robot\$project-robot" -p "***redacted***"
```

Please note: the same steps work with my **personal account credentials** but not with the robot account

**Versions:**
Please specify the versions of the following systems.

- harbor version: Version v2.3.0-047b122c
- docker engine version: unknown

**Additional context:**

I can see the same behavior with [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md). Deleting the image via crane with my personal credentials works, deleting an image with the robot account does not work.

**Comment by wy65701436** [comment]
The delete artifact and tag are means by Harbor API, instead of docker v2 client. Please reopen it if you still encounter any problem.
