### ISSUE TITLE
服务器时间差异导致的：failed to decode bearer token: token is not valid yet

### ISSUE THREAD

**Issue by lyp256** [goharbor/harbor#15911]
我们在 kubernetes 中部署 harbor。启用了 3 个 core 实例（他们在3个不同的 node 上）。偶然间发在在 CI 中调用 `docker login` 会导致 401 错误，通过查询日志发现 `failed to decode bearer token: token is not valid yet` 信息。初步排查会怀疑是签发 jwt （`GET host/service/token`）的 pod 和验证（`GET host/v2/`）的 pod 所在的主机时间差异导致出现该问题。目前通过 clockdiff 工具排查集群中 node 时间误差均在 50 ms  以内属于正常范围。可否考虑在签发 jwt token 时加入控制时间误差容忍的配置项？

**Comment by wy65701436** [comment]
I'm not clear that 50ms is acceptable in the real world scenario, but you can update your CI to bypass it.

**Comment by reasonerjt** [comment]
I don't  think we want to hack the way a JWT token is verified.

**Comment by lyp256** [comment]
对于 [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5) 中的定义，`nbf`  可以提供一定的误差容忍，并且 `nbf` 作为一个可选项可以在创建 Token 时省略

**Comment by koulq** [comment]
I have had the same problem，After using ntp to sync the nodes the problem is gone
![image](https://user-images.githubusercontent.com/18571340/141430221-dac971af-4d53-4280-906a-d12e1e53edfd.png)

**Comment by bravosierrasierra** [comment]
@koulq Thank you from 2023: my mysterious "401 Unauthorized" fixed with NTP setup on kubernetes nodes!

**Comment by lengrongfu** [comment]
@koulq Thank you from 2024
