### ISSUE TITLE
Generate golang client code using go-swagger

### ISSUE THREAD

**Issue by ymping** [goharbor/harbor#15912]
I'm use go-swagger generate golang client code, but [the generated client code call a NOT exits method](https://github.com/go-swagger/go-swagger/issues/2648)

How can we fix this?

**Comment by wy65701436** [comment]
how did you generate it? and in which Harbor?

**Comment by ymping** [comment]
@wy65701436 
how genarated and which harbor as follows info

### Go swagger install doc
https://goswagger.io/install.html

### Steps to reproduce
```bash
~$  swagger version
version: v0.27.0
commit: 43c2774170504d87b104e3e4d68626aac2cd447d
~$  
~$  mkdir debug && cd debug
~$  go mod init harbor
~$  wget https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml
~$  swagger generate client -f ./swagger.yaml
```
code in file ./models/project_summary_quota.go at [line 97](https://github.com/ymping/goharbor/blob/a76647cf0a71472969e3cf457434d97eb50bf963/models/project_summary_quota.go#L97) call a NOT exits method `ContextValidate` of golang struct named `types.ResourceList` in package `"github.com/goharbor/harbor/src/pkg/quota/types"`

**Comment by ymping** [comment]
go-swagger's developer suggest about this issue: https://github.com/go-swagger/go-swagger/issues/2648#issuecomment-944022243

**Comment by ymping** [comment]
@heww  Hi, this problem happens again at current main branch `swagger.yaml`, it has `x-go-type` define again.
```yaml
  ResourceList:
    type: object
    additionalProperties:
      type: integer
      format: int64
    x-go-type:
      type: ResourceList
      import:
        package: "github.com/goharbor/harbor/src/pkg/quota/types"
```

when use current `swagger.yaml` generate code by [go-swagger](https://goswagger.io/install.html) to build, errors as follow
```text
# github.com/ymping/goharbor/models
models/project_summary_quota.go:101:18: m.Hard.ContextValidate undefined (type types.ResourceList has no field or method ContextValidate)
models/project_summary_quota.go:115:18: m.Used.ContextValidate undefined (type types.ResourceList has no field or method ContextValidate)
models/quota.go:148:18: m.Hard.ContextValidate undefined (type types.ResourceList has no field or method ContextValidate)
models/quota.go:162:18: m.Used.ContextValidate undefined (type types.ResourceList has no field or method ContextValidate)
models/quota_update_req.go:73:18: m.Hard.ContextValidate undefined (type types.ResourceList has no field or method ContextValidate)
```
problem code
```go
func (m *ProjectSummaryQuota) contextValidateHard(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Hard.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("hard")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("hard")
		}
		return err
	}

	return nil
}
```
`ContextValidate` of golang struct named `types.ResourceList` in package `github.com/goharbor/harbor/src/pkg/quota/types`

steps to reproduce: https://github.com/goharbor/harbor/issues/15912#issuecomment-956071267

**Comment by iyurev** [comment]
Hi,
I've not completely got it ,  is there  solution for this issue currently?

**Comment by iyurev** [comment]
I'm sorry, I've noticed that in main branch the bug is fixed, but what's about  fix in release version ?  Currently the problem reproducing on tag v2.4.1.
