### ISSUE TITLE
Replications start to fail & fixed by helm upgrade but the root cause is unclear

### ISSUE THREAD

**Issue by vainkop** [goharbor/harbor#15910]
I was using harbor v2.3.0 installed on Google Kubernetes Engine using Helm chart v1.7.0 https://github.com/goharbor/harbor-helm/blob/v1.7.0/values.yaml

Harbor is used to replicate images from other container registries like gcr, dockerhub & etc.
After ~ 3 months the UI showed that there're ~ 60Gb of data.

GCS bucket was configured to persist docker images + Google Cloud SQL as Postgres DB for metadata + cloud redis for cache
The following config was used to set GCS:

https://github.com/goharbor/harbor-helm/blob/v1.7.0/values.yaml#L264
`    type: filesystem` > `    type: gcs`
+
`
    gcs:
      bucket: bucketname
      encodedkey: xxx
`
Those were left commented:
`
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: "5242880"
`

Other options for deployments storage were left at default values for example https://github.com/goharbor/harbor-helm/blob/v1.7.0/values.yaml#L208
`
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
`

Then at some point the replication stated to fail with the following errors in logs:
`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"038a8435bb522a9c295069c2\"}"}]}`

After inspecting the logs & K8s manifests & configuration I've discovered that deployments actually have `emptyDir` volumes even though the actual data was present in the GCS bucket. 

The error in the logs was unclear so after reading through some other similar github issues I've decided to try to upgrade Harbor to a newer v2.3.3, chart v1.7.3 https://github.com/goharbor/harbor-helm/blob/v1.7.3/values.yaml which is the latest one in the helm chart repo at the moment.

Also I've changed the `storageClass` to `standard` which changed `emptyDir` volumes to dynamic PVCs from GCP
Also I've increased the size to a value which is at least larger than what I see in the Harbor UI (~ 60Gb)
`
      storageClass: "standard"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 100Gi
`
  
That upgrade fixed the issue & replication started to work again but the reason for the fix is still unclear & that is not acceptable for a production service.
  
  
**What is the actual reason for those replication failures & what should be the fix?**

**What are those emptyDir/PVCs used for if docker images blobs are stored in a GCS bucket ?**

**Comment by steven-zou** [comment]
@vainkop 

Could you please share more job service logs when the following error you mentioned above happened? We need the related context for troubleshooting.

`
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"038a8435bb522a9c295069c2\"}"}]}
`
