### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by yuyadiel** [goharbor/harbor#15929]
Hope to develop a guide to build arm64 architecture,
At the same time, I hope that the architecture installation will consider lightweight, remove unnecessary components or provide a detachment plan, thank you

**Comment by wy65701436** [comment]
For any problem on ARM, please file issue on https://github.com/goharbor/harbor-arm.

**Comment by yuyadiel** [comment]
> 对于 ARM 上的任何问题，请在https://github.com/goharbor/harbor-arm上提交问题。

ok

**Comment by yuyadiel** [comment]
ok
