### ISSUE TITLE
jobservice start failed deployed on K8S

### ISSUE THREAD

**Issue by Lebronbingcheng** [goharbor/harbor#15926]
The jobservice pod start unsuccessfully. I got the error msg
``` "Failed on load rest config err:http error: code 401, message {"code":401,"message":"UnAuthorized"}"```
The logs of jobservice show as following: 

![jobserviceError](https://user-images.githubusercontent.com/20316586/139816705-f69a8038-e371-458f-82af-b21a383e3997.png)

The logs of core:
![coreError](https://user-images.githubusercontent.com/20316586/139816776-ff9cb9ff-537a-4051-b9de-af13c93428a1.png)

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.10.4

**Comment by wy65701436** [comment]
Hi, please file helm issue on harbor [helm repo](https://github.com/goharbor/harbor-helm) and 1.10 is out of support scope, suggest use the latest package.
