### ISSUE TITLE
mac m1 arm64 architecture support

### ISSUE THREAD

**Issue by yuyadiel** [goharbor/harbor#15928]
I hope the development will give an arm64 architecture building guide, thank you

**Comment by wy65701436** [comment]
we're working on Harbor ARM, but didn't try on mac m1, you can monitor the repo https://github.com/goharbor/harbor-arm

**Comment by yuyadiel** [comment]
ok

**Comment by princeba84** [comment]
Hi, Any news of Harbor deployment on M1 chips. For me It did not work. 
Many Thanks for you help!

**Comment by csthink** [comment]
Guys, is there any update on this issue？
