### ISSUE TITLE
Add unique constraint for the schedule job 

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#15936]
The scheduler should be unique by the (vendorType, vendorID, cronString) so that we can ensure that only one task job is created for when the (vendorType, vendorID, cronString) is the same.

**Comment by chlins** [comment]
As the constraint `unique_schedule` has been existed(https://github.com/goharbor/harbor/blob/ea16f1fb5edc3c081870b51b2be3cdf50d62e984/make/migrations/postgresql/0050_2.2.0_schema.up.sql#L296), close the issue.
