### ISSUE TITLE
2.2.3: robot account authentication attempted against LDAP (2)

### ISSUE THREAD

**Issue by hostalp** [goharbor/harbor#15941]
_Alright, opening a 2nd issue about the same thing as the 1st one (#15842) was closed without justification (the problem is definitely there but I can't reopen that issue)._

We've got a Harbor 2.2.3 instance configured for LDAP authentication.
In some cases we're getting LDAP IO timeouts that we're trying to troubleshoot now, but this isn't the most important thing here.

The main problem we encounter is that even robot accounts are affected by the LDAP issue, even though these are local accounts. Example:
```
Oct 20 02:37:52 172.18.0.1 core[1250]: 2021-10-20T00:37:52Z [ERROR] [/pkg/token/token.go:66]: parse token error, token contains an invalid number of segments
Oct 20 02:37:52 172.18.0.1 core[1250]: 2021-10-20T00:37:52Z [ERROR] [/server/middleware/security/robot.go:45][requestID="bbdc8273-7f51-44ea-865e-0955709cb53e"]: failed to decrypt robot token: token contains an invalid number of segments
Oct 20 02:37:52 172.18.0.1 core[1250]: 2021-10-20T00:37:52Z [ERROR] [/server/middleware/security/robot2.go:47][requestID="bbdc8273-7f51-44ea-865e-0955709cb53e"]: failed to authenticate robot account: robot$global
Oct 20 02:37:57 172.18.0.1 core[1250]: 2021-10-20T00:37:57Z [WARNING] [/core/auth/ldap/ldap.go:58]: ldap connection fail: LDAP Result Code 200 "Network Error": dial tcp: i/o timeout
Oct 20 02:37:57 172.18.0.1 core[1250]: 2021-10-20T00:37:57Z [ERROR] [/server/middleware/security/basic_auth.go:40][requestID="bbdc8273-7f51-44ea-865e-0955709cb53e"]: failed to authenticate robot$global: LDAP Result Code 200 "Network Error": dial tcp: i/o timeout
```
_Note that all of the above is the same authentication request using the robot account. The reply in the 1st issue that only part of the above belongs to this authentication process is incorrect. If the timeout captured above occurs the robot account simply fails to authenticate. In the case of no such timeout the robot account authenticates successfully._

I believe this shouldn't happen, so there's some bug in the authentication processing that leads to LDAP (or probably any external provider) being always tried first.

I'd expect that the local user registry should be tried first and LDAP or anything such second (only if the user isn't found in the first user registry).

**Comment by YangJiao0817** [comment]
@hostalp I replaced the correct LDAP URL with an Unreachable address on the Configuration->Authentication page, and then used the robot account to perform docker login and docker push operations. Your problem cannot be reproduced. Can you tell me more detailed steps?

**Comment by hostalp** [comment]
@YangJiao0817 I'm not sure what situation you exactly achieved, but based on your description it was probably the case which would fail immediately (non-existent host, unable to open connection etc).

In order to reproduce this issue you will need to simulate the LDAP timeout case. That is slow LDAP response (or perhaps slow DNS resolution of the LDAP server IP address because that's when it appears to exhibit such timeouts as well, see #13718).

But I'd say even when looking at the code (or debugging the robot account login) it should be possible to see that it uses the external auth. provider (in this case LDAP) first.

**Comment by hostalp** [comment]
comment to prevent closing the issue
