### ISSUE TITLE
Execution sweep lists execution records from DB in dead loop without sleep

### ISSUE THREAD

**Issue by childe** [goharbor/harbor#15945]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Actual behavior: 
https://github.com/goharbor/harbor/blob/release-2.4.0/src/pkg/task/execution.go#L127-L205

Every new execution would create a new goroutine in which sweep lists execution records from DB in dead loop without any sleep. This makes DB high load if there are dirty records for some reason (Maybe job worker is killed?)

Expected:
Sleep in the  loop ? or has a Timeout?

**Steps to reproduce the problem:**

We do not know how to reproduce it for now.

**Versions:**

- harbor version: [2.2.0]
- docker engine version: [Docker version 19.03.12, build 48a66213fe]
- docker-compose version: [docker-compose version 1.25.1, build a82fef07]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by childe** [comment]
It is better to offer a fixed number of go routines to do the sweep job ?

DB load is very high when there are executions running for long time, and new go routines and more and more connections to db are created and not released.

**Comment by chlins** [comment]
I think we only need one global periodic cleaner job to do the sweep task. cc @wy65701436 @ywk253100
