### ISSUE TITLE
How can docker client pull a harbor without logging in, as docker registry does?

### ISSUE THREAD

**Issue by asskss** [goharbor/harbor#15942]
hello，
How can dockerClient pull a Harbor without logging in, as docker registr does?
We want to be able to pull and push without having to log in.

**Comment by Vad1mo** [comment]
you need to create a public project thats it, However there is no option for an unauthorized user to push to harbor. 
All pushs need to be done by authorized users who have access to the project.
see: https://goharbor.io/docs/2.4.0/working-with-projects/project-configuration/
