### ISSUE TITLE
"latest" tag incorrectly points to version 1, not version 2

### ISSUE THREAD

**Issue by emhelmich** [goharbor/harbor#15955]
https://github.com/goharbor/harbor/releases/latest

**Comment by Vad1mo** [comment]
because technically, `latest` means the latest release of whatever, not just the most up-to-date version. 
Its mainly how github is displaying that 

see: https://github.com/goharbor/harbor/discussions/15908

**Comment by wy65701436** [comment]
cc @xaleeks
