### ISSUE TITLE
chart provenance file replication between harbor servers doesn't work

### ISSUE THREAD

**Issue by coolio8818** [goharbor/harbor#15959]
I have setup two 2.4 harbor servers and testing the replication between them. I was able to replicate the helm charts but the provenance files were not replicated. Wondering if the chart provenance file replication was supported? Can someone please advise how to replicate provenance file if it's supported? Thanks a lot!

**Comment by wy65701436** [comment]
chart provenance file replication is not supprted in Harbor.
