### ISSUE TITLE
Adding projects through the official API is too cumbersome. Is there any other way to add harbor projects on the command line? For example, in docker registry, secondary directories can be automatically generated without API

### ISSUE THREAD

**Issue by asskss** [goharbor/harbor#15951]
What can we help you?
Adding projects through the official API is too cumbersome. Is there any other way to add harbor projects on the command line? For example, in docker registry, secondary directories can be automatically generated without API

**Comment by Vad1mo** [comment]
you can use one of the different CLIs
eg. 
- https://github.com/disaster37/harbor-cli
- https://github.com/hinyinlam/cli-for-harbor
