### ISSUE TITLE
How to add the warehouse address of harbor without restarting docker and modifying the daemon.json file in the online environment？

### ISSUE THREAD

**Issue by asskss** [goharbor/harbor#15950]
What can we help you?
There are too many online docker tasks and restarting is too troublesome. Is there any way to add a private warehouse address without restarting

**Comment by phin1x** [comment]
since this is a question related to the docker daemon you have open this issue with your question in the docker repository. but as far as i know you need to restart the docker engine to make the changes in the daemon.json take effect.

**Comment by wy65701436** [comment]
please file issue on docker side, thanks.
