### ISSUE TITLE
Cosign integration engineering work

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#15964]
In Harbor v2.5.0, we'd like to introduce cosign as a OCI artifact signature solution. After that, Harbor will support to manage cosign signature that associated with the artifact.

Proposal: https://github.com/goharbor/community/pull/172

**Comment by wy65701436** [comment]
close it as all the taskes were done.

**Comment by lfrancke** [comment]
I'm sorry to ask this in this issue: Has any documentation been added for this feature?

**Comment by AshleyDumaine** [comment]
Found the docs for cosign here: https://goharbor.io/docs/edge/working-with-projects/working-with-images/sign-images/
