### ISSUE TITLE
When pulling the image, some layers report Retrying，But it can be pulled from other servers...

### ISSUE THREAD

**Issue by lynn447742** [goharbor/harbor#15968]
I tried adding the configuration "relativeurls: true" to the file "common/config/registry/config.yml", restarted the docker daemon, and redeployed the harbor using docker-compose, but it still didn't work.
The error is as follows:  
[root@k8s ~]# docker pull harbor-local.unicloudsrv.com/moove/uco-cce-core:v2.2.5
v2.2.5: Pulling from moove/uco-cce-core
33847f680f63: Pull complete 
a825c467b688: Retrying in 9 seconds 
4c60b5145021: Retrying in 9 seconds 
d099dc72363e: Download complete

**Comment by stonezdj** [comment]
please upload the registry.log and core.log?
