### ISSUE TITLE
Cannot delete repository with signed images that exist in multiple projects

### ISSUE THREAD

**Issue by ssmall** [goharbor/harbor#15960]
**Expected behavior and actual behavior:**

I am trying to move some images from one project to a new one in my Harbor registry. When I re-tag the images and push them to the new project, I expect to be able to delete the repository from the old project.

However, I am unable to delete the repository from the old project. This only happens with repositories that have been pushed to both projects -- I cannot delete from either project. Instead, I see the message

```
the tag 6.2.6-amd64 with signature cannot be deleted
```

**Steps to reproduce the problem:**

```
$ docker pull harbor.my.domain/oldproject/redis:6.2.6-amd64
6.2.6-amd64: Pulling from oldproject/redis
Digest: sha256:5d30f5c16e473549ad7c950b0ac3083039719b1c9749519c50e18017dd4bfc54
Status: Image is up to date for harbor.my.domain/oldproject/redis:6.2.6-amd64
harbor.my.domain/oldproject/redis:6.2.6-amd64

$ docker tag harbor.my.domain/oldproject/redis:6.2.6-amd64 harbor.my.domain/newproject/redis:6.2.6-amd64

$ docker push harbor.my.domain/newproject/redis:6.2.6-amd64
The push refers to repository [harbor.my.domain/newproject/redis]
146262eb3841: Mounted from oldproject/redis
0bd13b42de4d: Mounted from oldproject/redis
6b01cc47a390: Mounted from oldproject/redis
8b9770153666: Mounted from oldproject/redis
b43651130521: Mounted from oldproject/redis
e8b689711f21: Mounted from oldproject/redis
6.2.6-amd64: digest: sha256:5d30f5c16e473549ad7c950b0ac3083039719b1c9749519c50e18017dd4bfc54 size: 1573
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.2]
- docker engine version : [20.10.8]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ssmall** [comment]
I was able to get a more detailed error message by drilling down to the specific tag and trying to delete just that tag:

```
The tag must be removed from the Notary before it can be deleted. Delete from Notary via this command: notary -s https://harbor.my.domain:4443 -d ~/.docker/trust remove -p harbor.my.domain/oldproject/redis 6.2.6-amd64
```

It is unclear to me if this is related to the repository existing in multiple projects or only has to do with Notary signing. Either way, perhaps this error detail could be included when trying to delete the repository so that it's more obvious what went wrong.

**Comment by ssmall** [comment]
Update: when I try to run the command suggested in https://github.com/goharbor/harbor/issues/15960#issuecomment-962564274 it prompts for a username and password. My Harbor username and password do not seem to work:

```
$ notary -s https://harbor.my.domain:4443 -d ~/.docker/trust remove -p harbor.my.domain/redis 6.2.6-amd64
Removal of 6.2.6-amd64 from harbor.my.domain/redis staged for next publish.
Auto-publishing changes to harbor.my.domain/redis
Enter username: XXXXXX
Enter password:
ERRO[0008] Could not publish Repository since we could not update: you are not authorized to perform this operation: server returned 401.

* fatal: you are not authorized to perform this operation: server returned 401.
```

**Comment by ssmall** [comment]
I believe this is still an issue

**Comment by pratik705** [comment]
- I am able to remove the image from the UI after removing the target from a trusted collection:

`# notary  -D -d .docker/trust/ -s https://notary.xxx.com remove -p  harbor.xxx.com/internal/nginx 1.14.2`
