### ISSUE TITLE
task for the scan report xxx not found after update from 2.3.3 to 2.4.0

### ISSUE THREAD

**Issue by EHEX-schildt** [goharbor/harbor#15974]
**Expected behavior**
If i scan a Image i see all vulnerabilities in web gui.

**actual behavior:**
GUI show's all Green / No recognizable vulnerability detected
If i click "View Log" i get:
{"errors":[{"code":"NOT_FOUND","message":"report with uuid 6f69f3c7-48fd-4b37-b64e-d70521c8f83b does not exist"}]}

core.log:
Nov  8 15:38:55 172.21.0.1 core[8161]: 2021-11-08T14:38:55Z [WARNING] [/controller/scan/base_controller.go:966]: task for the scan report 6f69f3c7-48fd-4b37-b64e-d70521c8f83b not found

if i try to pull this image i get:
Error response from daemon: unknown: current image with "Error" status of vulnerability scanning cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "High" or higher from running.' To continue with pull, please contact your project administrator for help

**Steps to reproduce the problem:**
* Scan images with v2.3.3
* update from 2.3.3 to 2.4.0

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.0
- docker engine version: 20.10.10
- docker-compose version: 1.29.2

**Comment by heww** [comment]
Please try upgrading to 2.4.1 and checking whether this problem still exists.

**Comment by cfrantsen** [comment]
I have the same issue, on 2.4.1. The only way to pull images is to disable the Deployment Security policy :(
