### ISSUE TITLE
GC fails with "invalid checksum digest format" from registry when deleting manifests

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#15970]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

GC should delete all manifests & blobs marked for removal and if an error is encountered should skip the offending manifest/blob and continue with the rest, logging the issue, instead GC fails to delete some manifest because registry returns 500 and the following error message:
```
err.message="invalid checksum digest format"
```

and the whole GC job fails and stops.

**Steps to reproduce the problem:**
Don't know what causes it, so not sure how to reproduce.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.3
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

Registry logs
```
time="2021-11-08T00:41:24.515110036Z" level=info msg="authorized request" go.version=go1.15.12 http.request.host="harbor-registry:5000" http.request.id=c5e9fa5c-804e-46b8-a610-1c523bda67ad http.request.method=DELETE http.request.remoteaddr="127.0.0.1:50242" http.request.uri="/v2/<project>/<repo>/manifests/sha256:875c0867bae86b06e7c4e098eff8877663c13859eb760f36b451354c755e591d" http.request.useragent=harbor-registry-client vars.name="<project>/<repo>" vars.reference="sha256:875c0867bae86b06e7c4e098eff8877663c13859eb760f36b451354c755e591d" 

time="2021-11-08T00:43:20.098404428Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.message="invalid checksum digest format" go.version=go1.15.12 http.request.host="harbor-registry:5000" http.request.id=c5e9fa5c-804e-46b8-a610-1c523bda67ad http.request.method=DELETE http.request.remoteaddr="127.0.0.1:50242" http.request.uri="/v2/<project>/<repo>/manifests/sha256:875c0867bae86b06e7c4e098eff8877663c13859eb760f36b451354c755e591d" http.request.useragent=harbor-registry-client http.response.contenttype="application/json; charset=utf-8" http.response.duration=1m55.650187865s http.response.status=500 http.response.written=70 vars.name="<project>/<repo>" vars.reference="sha256:875c0867bae86b06e7c4e098eff8877663c13859eb760f36b451354c755e591d" 
```

jobservice log:
```
2021-11-08T00:43:20Z [ERROR] [/jobservice/runner/redis.go:113]: Job 'GARBAGE_COLLECTION:4d498cc8dea08115a5d2a92d' exit with error: run error: failed to delete manifest with v2 API: <project>/<repo>, sha256:875c0867bae86b06e7c4e098eff8877663c13859eb760f36b451354c755e591d: retry timeout: http status code: 500, body: {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{}}]}
```

**Comment by dkulchinsky** [comment]
@wy65701436 came across this issue (https://github.com/distribution/distribution/issues/3018) and PR (https://github.com/distribution/distribution/pull/3019) in the upstream Docker Distribution that seem to have identified the same issue that is causing these errors we're seeing.

AFAICT the PR was abandoned and the issue is still open with now resolution, GitLab seem to have forked distribution and started using their own version due to inability to push changes.

With distribution still (?) using Google SDK from 2015, it's really worrying and looks like it's contributing to a lot of the issues we're seeing, including this one?

**Comment by wy65701436** [comment]
thanks @dkulchinsky , I'll update the Google SDK for upstream distribution. Given this, Harbor still cannot leverage it till we get an new distribution release.

**Comment by dkulchinsky** [comment]
Thanks @wy65701436!

can we consider using gitlab's fork of the distribution? seems like it's in a much better shape in terms of reliability, perfromance and overall maintenance, Docker's distribution last release was in January 2019 😱 

Is there anything you can suggest for my situation? we already have over 10,000 artifacts waiting for GC (and the number grows daily) and the GC job keeps failing either due to this issue or the other GC issues I've reported (mostly https://github.com/goharbor/harbor/issues/15822)

What can we do? getting really desperate with this 😞

**Comment by wy65701436** [comment]
We have no plan to leverage other forked distribution. We're(distribution maintainers) working on issue new release for upstream distribution, but I cannot give an date.

- For this issue, I'll raise the PR to fix in the upstream. Harbor needs to wait for distribution 3.0 release.
- For other issues on GC, I'll go through them and maybe we can do some enhancement on Harbor side. But, so far, most of the problems are raised by the backend storage.

**Comment by dkulchinsky** [comment]
Thanks again for replying @wy65701436! I appreciate it 👍🏼 

> We have no plan to leverage other forked distribution. We're(distribution maintainers) working on issue new release for upstream distribution, but I cannot give an date.
> 
> * For this issue, I'll raise the PR to fix in the upstream. Harbor needs to wait for distribution 3.0 release.

Looking forward to it 👍🏼 

> * For other issues on GC, I'll go through them and maybe we can do some enhancement on Harbor side. But, so far, most of the problems are raised by the backend storage.

I think allowing GC to skip blobs/manifests that fail to be removed due to persistent errors such as 404 & 500 can help mitigate this issue considerably, at least allow us to GC the majority of artifacts.

perhaps this behaviour can be an optional configuration, so that it won't be considered as a breaking change and will be opt-in.

**Comment by wy65701436** [comment]
yes, to allow skip failure could be an option. BTW, for the performance issue, we maybe will do some enhancement on distribution side.

**Comment by dkulchinsky** [comment]
> yes, to allow skip failure could be an option. 

That would be great @wy65701436 🤝  this will be greatly appreciated as it would really help our current situation, I hope this can implement sooner than later 🙏🏼 

> BTW, for the performance issue, we maybe will do some enhancement on distribution side.

👏🏼

**Comment by dkulchinsky** [comment]
this is still being tracked I believe?

**Comment by dkulchinsky** [comment]
still relevant

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
not stale

**Comment by dkulchinsky** [comment]
Looks like I missed the `stale` notifications and didn't post here.

his is definitely still an issue and should be tracked.

@wy65701436 can you please re-open?

**Comment by moepoop** [comment]
My harbor version is v2.2.2, and I also encountered the error 'invalid checksum digest format'.

Here are my discoveries and temporary solutions:

1. Find the corresponding revisions directory based on the error message, the approximate path is as follows:
/data/registry/docker/registry/v2/repositories/*/*/*/_manifests/revisions/sha256/

2.Entering the incorrect sha256 folder, it was found that the content in the `link` file was empty. Perhaps this is the reason for the error 'invalid checksum digest format'.  ''link' file is not empty in other normal folder.

3.Solution: Delete the folder where the `link` file is empty.  Running GC again found that the previous cleaning failure issue has been fixed, and this time it will be cleaned up normally.
There may be more than one problematic folder. It is necessary to identify all folders with empty `link` files and clean them up.

**Comment by microyahoo** [comment]
> My harbor version is v2.2.2, and I also encountered the error 'invalid checksum digest format'.
> 
> Here are my discoveries and temporary solutions:
> 
> 1. Find the corresponding revisions directory based on the error message, the approximate path is as follows:
>    /data/registry/docker/registry/v2/repositories/_/_/*/_manifests/revisions/sha256/
> 
> 2.Entering the incorrect sha256 folder, it was found that the content in the `link` file was empty. Perhaps this is the reason for the error 'invalid checksum digest format'. ''link' file is not empty in other normal folder.
> 
> 3.Solution: Delete the folder where the `link` file is empty. Running GC again found that the previous cleaning failure issue has been fixed, and this time it will be cleaned up normally. There may be more than one problematic folder. It is necessary to identify all folders with empty `link` files and clean them up.

hi @lonelyagegeek, seems pr https://github.com/distribution/distribution/pull/4343/files will fix it.
