### ISSUE TITLE
Define live backup/restore workflow for Harbor.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#15975]
We need a solution to backup/restore Harbor without having to shut down Harbor instance.

1)  We need a reliable approach to quiesc Harbor, or check if it's in a state that is ready to backup.  Currently there is a readonly API but after the API is called there may be jobs running in the backend making updates to the storage such as tag retention, replication, GC.  And new records of accesslog may be inserted to DB when user pulls artifacts.  If that's not possible, we may need to define a "rerequisite" state only in which Harbor can be backed up.
2)  We need to clarify the scope of data that will be backed up and restored.  For example, the data in redis may be ignored, it may be OK to lose some records in accesslog that are not backed up during this process.
3)  We need to define a test process to check the consistency of the data to verify the solution.

**Comment by Jeremy-boo** [comment]
Will the backup and restore of harbor data be put on the agenda in version 2.5? Now more and more users have requirements in this regard

**Comment by reasonerjt** [comment]
@Jeremy-boo Currently the flow has to be shut down Harbor, copy all data, and start.

We are still investigating to provide a more reliable way to quiesc Harbor. considering there can be backend jobs running to clean up/replicating data, we still need more understanding regarding what impact such inconsistency may cause.
