### ISSUE TITLE
Default robot permissions should be all false

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#15988]
Security wise, it is best to have the robot permissions
all set to false and if the users wish to enable a
certain permission to expressely do it. The other way
around loses the permission policy enforcement from
lazy/unknowing users.

**Comment by AllForNothing** [comment]
@xaleeks It makes sense, but it doesn’t seem to be very important， what do you think?

**Comment by ChristianCiach** [comment]
I second that request, but for ergonomical reasons.

Almost all of our robot-accounts should only be allowed to `PULL` - and nothing else. Currently I have to remove *a lot* of permissions when creating new robot accounts, which is very prone to error.

**Comment by AllForNothing** [comment]
@ChristianCiach For your use case，It's surely more comfortable for you if all the permissions are unselected default.
But we are not sure if this is a very common case.
In version 2.5, we have added "select all" and "unselect all" operations for robot permissions， see #15774.
It can meet the requirement to a certain extent

**Comment by dioguerra** [comment]
What is the decision here? This does not make sense?
