### ISSUE TITLE
harbor api CSRF token invalid

### ISSUE THREAD

**Issue by kay07** [goharbor/harbor#15994]
when I use the codes to create project,I can do it in my local computer,but when I deploy my codes to server,I always get the error :
`{\"errors\":[{\"code\":\"FORBIDDEN\",\"message\":\"CSRF token invalid\"}]}`
I don't know how to solve it,^_^ 
My codes are:
`    

private final static String version="/api/v2.0/projects/";

    @Override

    public boolean createItem(String name) {

        if(name==""){

            throw new SysCodeException(SysCodeEnum.NULL_ERROR);

        }

        String url=this.url+version;

        String authToken=loginToken(this.username,this.password);

        Map<String,String> map=new HashMap<>();

        map.put("Authorization","Basic "+authToken);

        map.put("Content-Type","application/json");

        String s = "{\"project_name\": "+'"'+name+'"'+",\"metadata\": {\"public\": \"true\"},\"storage_limit\": -1}";

        String body=HttpRequest.post(url).addHeaders(map).body(s).execute().body();

        if(!body.equals("")){

            throw new RuntimeException(body);

        }

        return true;

    }`

HELP
HELP

**Comment by AllForNothing** [comment]
@kay07 For every non-query request, you have to add the "X-Harbor-CSRF-Token" header. And you can get this token from the response header of your last request.
![image](https://user-images.githubusercontent.com/30999793/141399474-3d648ffb-0b1b-4bb5-914b-4afab37a2ab8.png)

**Comment by kay07** [comment]
@AllForNothing When I use get methord ,there I can get the X-Harbor-CSRF-Token ,should I use this token?But I also find the token will change every times ,so I should use the latest one?Thanks a lot

**Comment by AllForNothing** [comment]
@kay07 Every token is valid for one hour,  you can use any valid token. But better use the latest one

**Comment by kay07** [comment]
Got it.Thank you.

**Comment by kay07** [comment]
I added the X-Harbor-CSRF-Token to header,but the error is still arise,about one in ten will success.
The error will occur only when I deloyed my codes to server.

**Comment by birkhoff2017** [comment]
I write the same code as yours,and encountered the same problem,may I ask how to solve this problem.

**Comment by birkhoff2017** [comment]
I solved this problem by disable cookies
https://github.com/goharbor/harbor/issues/13124#issuecomment-1064415554
