### ISSUE TITLE
ERROR: for harbor-core  Cannot start service core: OCI runtime create failed: container_linux.go:318: starting container process caused "chdir to cwd (\"/harbor\") set in config.json failed: permission denied": unknown

### ISSUE THREAD

**Issue by yanghuinnn** [goharbor/harbor#15993]
I compiled the offline installation package using source code on the ARM architecture, decompressed the offline installation package, and executed./install, reporting this error
![屏幕截图 2021-11-11 205647](https://user-images.githubusercontent.com/92514704/141301866-0fec1bba-d09a-41aa-a746-8269aafcafa7.png)

**Comment by wy65701436** [comment]
please file arm issue at https://github.com/goharbor/harbor-arm.
