### ISSUE TITLE
audit log rotate

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#15995]
What can we help you?

harbor will write every operations to audit_log table for ever, and in one of the cluster, there are lot of user activities under test, and one day the database disk space is used up, cause harbor is down.
=========

registry=# select count(*) from audit_log;
  count
---------
 5379393
(1 row)

==========

please provide a option to rotate the audit log per project level, and maybe one option to delete the audit log.

thanks.

**Comment by wy65701436** [comment]
let's use https://github.com/goharbor/harbor/issues/15653 to track this problem, thanks.
