### ISSUE TITLE
HA with Dual-node Configuration LDAP exception

### ISSUE THREAD

**Issue by domcai** [goharbor/harbor#16007]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I used Docker-compose to deploy a dual-node Harbor with the same external PG and the same external Redis.
When I configure LDAP, only one of the two nodes can log in properly.

**Steps to reproduce the problem:**
When I configured LDAP on one node, an error was reported on the other node.
I went to the node where the error occurred and tested the LDAP link.
![image](https://user-images.githubusercontent.com/7867371/141934707-f738a002-9100-4869-9acb-46f2f8314fdb.png)
I can log in only after I change the `LDAP Search Password` again. However, the nodes that have logged in successfully before cannot be logged in.
Only one node can be logged in to using LDAP.

This is the core.log
```
Nov 16 14:14:20 172.24.0.1 core[27942]: 2021-11-16T06:14:20Z [WARNING] [/core/auth/ldap/ldap.go:68]: ldap search fail: can not bind search dn, error: LDAP Result Code 49 "Invalid Credentials":
Nov 16 14:14:20 172.24.0.1 core[27942]: 2021-11-16T06:14:20Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: can not bind search dn, error: LDAP Result Code 49 "Invalid Credentials":
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.4]
- docker engine version: [ 20.10.10]
- docker-compose version: [1.29.2]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by stonezdj** [comment]
The LDAP password is encrypted and stored in the database,  key files in /data/secret/keys/secretkey should be identical in both instances.

**Comment by domcai** [comment]
/ data/secret/keys/secretkey refers to the LDAP password? I found that the secretkey file contents of the two nodes are different.

**Comment by domcai** [comment]
After holding the key in file /data/secret/keys/secretkey, the problem is resolved.thx

**Comment by roysbike** [comment]
is it possible to store a secret key in S3?
