### ISSUE TITLE
Trivy Scanner is failing

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#16011]
Hello,

Nov 15 00:00:20jobservice[13934]: 2021-11-15T00:00:20Z [WARNING] [/pkg/scan/dao/scan/vulnerability.go:148][error="**pq: integer out of range**" report="b3a8ce0d-14b1-43de-a7db-80c9f26a46bb"]: Could not associate vulnerability record to the report
Nov 15 00:00:20  jobservice[13934]: 2021-11-15T00:00:20Z [ERROR] [/pkg/scan/postprocessors/report_converters.go:182][error="pq: integer out of range" report="b3a8ce0d-14b1-43de-a7db-80c9f26a46bb"]: Could not associate vulnerability records to the report
Nov 15 00:00:20 jobservice[13934]: 2021-11-15T00:00:20Z [ERROR] [/pkg/scan/job.go:292]: Failed to convert vulnerability data to new schema for report b3a8ce0d-14b1-43de-a7db-80c9f26a46bb, error Error when converting vulnerability report: pq: integer out of range
Nov 15 00:00:20  jobservice[13934]: 2021-11-15T00:00:20Z [ERROR] [/jobservice/runner/redis.go:113]: Job 'IMAGE_SCAN:8ea075fb4e9db026a9597fcf' exit with error: run error: Error when converting vulnerability report: pq: integer out of range

On checking i found that the table report_vulnerability_record, theid is set as int

Table: report_vulnerability_record;  

Description

Table "public.report_vulnerability_record" 
 Column | Type | Modifiers 
----------------+---------+-------------------------------------------------------------------------- 
 **id** | integer | not null default nextval('report_vulnerability_record_id_seq'::regclass) 
 report_uuid | text | not null default ''::text 
 vuln_record_id | bigint | not null default 0 
Indexes: 
 "report_vulnerability_record_pkey" PRIMARY KEY, btree (id) 
 "report_vulnerability_record_report_uuid_vuln_record_id_key" UNIQUE CONSTRAINT, btree (report_uuid, vuln_record_id) 
Foreign-key constraints: 
 "fk_report_uuid" FOREIGN KEY (report_uuid) REFERENCES scan_report(uuid) ON DELETE CASCADE 
 "fk_vuln_record_id" FOREIGN KEY (vuln_record_id) REFERENCES vulnerability_record(id) ON DELETE CASCADE

Is this a known issue?
Do I have to change it to bigint?

Harbor Version v2.3.2
Docker version 19.0.0
docker-compose version 1.26
Postgresql: 9.6

**Comment by heww** [comment]
How many records are there in your report_vulnerability_record table? What's the max value of id in your table?

**Comment by AyushCloud** [comment]
The maximum value of id is 2,147,483,647. The report_vulnerability_record_id_seq has reached the max value of int which is 2,147,483,647.

**Comment by TakiTake** [comment]
I also encountered same issue.
I guess the setting comes from ORM library. It convert auto tag to SERIAL type of PostgreSQL.
SERIAL range is 1 to 2147483647.

How can I solve the issue if ID has reached the limit?

Related code
https://github.com/goharbor/harbor/blob/v2.3.2/src/pkg/scan/dao/scan/model.go#L106
https://github.com/goharbor/harbor/blob/v2.3.2/src/vendor/github.com/astaxie/beego/orm/db_postgres.go#L42

**Comment by heww** [comment]
HI @AyushCloud and @TakiTake can you help to count the records in the vulnerability_record and report_vulnerability_record tables?

**Comment by TakiTake** [comment]
Hi @heww,
I counted records and check last value of sequences.

```
registry=# select count(*) from vulnerability_record;
 count
--------
 240619
(1 row)

registry=# select last_value from vulnerability_record_id_seq;
 last_value
------------
     246018
(1 row)

registry=# select count(*) from report_vulnerability_record;
 count
--------
 158376
(1 row)

registry=# select last_value from report_vulnerability_record_id_seq;
 last_value
------------
 2147483647
(1 row)
```

**Comment by AyushCloud** [comment]
Hello @heww 
In order to by pass, I have change the type to bigint for "id" in "report_vulnerability_record"

=> select count(*) from vulnerability_record; 
 count 
------- 
 56900 
(1 row) 
 
=> select count(*) from report_vulnerability_record; 
 count 
---------- 
 12319202 
(1 row) 
 
=> select last_value from report_vulnerability_record_id_seq; 
 last_value 
------------ 
 2260110383 
(1 row)

**Comment by drehpehs** [comment]
Hi @heww ,

I noticed we have the same issue now. Since we also reached the maximum sequence id of the table `report_vulnerability_record`, the vulnerability scan can't work properly.
Any update or solution to resolve this problem? Can we ALTER the data type of the id to BIGINT? (Will there be any side effect?)

BTW, I found the column `vuln_record_id` in table `report_vulnerability_record` is bigint, but the `id` of `vulnerability_record` is interger as well.

**Comment by heww** [comment]
@AyushCloud @TakiTake @drehpehs Here is a workaround to resolve the problem. Depending on the data size of the two tables, this may take a long time and block the harbor system to serve users' requests.

```sql
ALTER TABLE vulnerability_record ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE vulnerability_record_id_seq AS BIGINT;

ALTER TABLE report_vulnerability_record ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE report_vulnerability_record_id_seq AS BIGINT;
```

**Comment by a-mccarthy** [comment]
@wy65701436, did we want to document anything here for 2.5? I see that you added the docs-impact label, but i'm nots sure what specifically should be documented to best help folks. thanks!

**Comment by itsecforu** [comment]
Did anyboady solve it?
