### ISSUE TITLE
When endpoint provider is quay, am unable to replicate images

### ISSUE THREAD

**Issue by pradeep288** [goharbor/harbor#16035]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
**Expected**:
When the Registry Provider is quay, image replication should happen

**Actual**
When the Registry Provider is quay , image replication is not happening. With same info but Provider as docker registry Replication is happening.

   
**Steps to reproduce the problem:**
Followed the below steps:

- Login to Harbor
- Click on Registries
- Click on New EndPoint
- Provide
     1. Provider as quay
     2. Name: Quay-EndPoint
     3. Give the EndPoint as https://quay.io
     4. AccessID: Empty
     5.  AccessSecret: 
          ```
          {
          "account_name": "username",
          "docker_cli_password": "XXXX" 
          }
          ```
       Get the Docker CLI password by logging to quay via New RedHat SSO Login
     6. Verify Remote Cert: True
     7. Click on Test Connection, Connection succeeds

- Click on Replication Tab
   1. Click on New Replication
   2. Provide the Replication name
   3. Select Pull-based Button
   4. Provide Source Resouce filters
   5. Select the destination registry, which was added on the earlier step
   6. Keep Trigger mode as manual
   7. Keep Override checkbox enabled
   8. Save the setting

- Select the last added  replication
- click on Replicate

**Versions:**
Please specify the versions of the following systems.

- harbor version: 2.1.3
- docker engine version: 20.10.10

**Comment by chlins** [comment]
This issue maybe caused by the change of quay.io authorization. The post from Red Hat: https://access.redhat.com/articles/5925591

**Comment by chlins** [comment]
Can't reproduce the issue at harbor v2.4.0.

**Comment by chlins** [comment]
> Can't reproduce the issue at harbor v2.4.0.
> 
> replication rule ![image](https://user-images.githubusercontent.com/31262637/142819377-45c863bb-44dc-4c9a-a490-9a1848c74abf.png)
> 
> execution ![image](https://user-images.githubusercontent.com/31262637/142819439-71290d3c-13fe-4fc0-9062-e81caef1aacd.png)

Also not reproduce at harbor v2.1.3.
