### ISSUE TITLE
Increase default page size in Projects view

### ISSUE THREAD

**Issue by r10r** [goharbor/harbor#16030]
Hi there,

is it possible to customize/increase the default page size in the **Projects** view ?

<img width="520" alt="Screenshot 2021-11-18 at 10 19 59" src="https://user-images.githubusercontent.com/309304/142387049-0c1c68c3-2538-4b64-836c-352595ed4483.png">

**Comment by AllForNothing** [comment]
@r10r You need to modify the UI source code, change <“pageSize”>[https://github.com/goharbor/harbor/blob/main/src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts#L64] to the value you want, then rebuild Harbor.

**Comment by r10r** [comment]
Hi @AllForNothing, thanks a lot for the pointer. Is it possible in the long-term to make this a configuration setting without having to rebuild Harbor ?

**Comment by AllForNothing** [comment]
@r10r Technically,  we can surely implement it.  Let keep this issue open for a period of time to see if it's a common requirement

**Comment by kilimar** [comment]
+1
