### ISSUE TITLE
DB connection spike when too many request comes from kapp-controller

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16039]
The kapp controller reconcile the application every 5 minutes, during the reconcile process, it pulls the manifest from the Harbor,  the pull manifest operation result in too many database updates on the table 
```
 UPDATE repository  SET  pull_count  =  pull_count + $1, update_time  = $2 WHERE  repository_id  IN ( SELECT T0.repository_id FROM repository T0 WHERE T0.repository_id = $3  )

 UPDATE artifact  SET pull_time  = $1 WHERE id = $2
```

**Comment by dkulchinsky** [comment]
@wy65701436 looks like `PULL_TIME_UPDATE_DISABLE` will also mitigate:
- https://github.com/goharbor/harbor/issues/14638
- https://github.com/goharbor/harbor/issues/15810

at least until a more specific fix is available to not update pull time when image pulled by a scanner.
