### ISSUE TITLE
LDAP user can pull images but not Login on the UI after update to v. 2.4.0

### ISSUE THREAD

**Issue by Krumbelfix** [goharbor/harbor#16041]
**Expected behavior and actual behavior:**
After the Upate from to 2.4.0 LDAP-Users are able to pull images but cant login in the webui ( `Invalid user name or password ` on the ui)

After the rollback everything worked proberly.

**Steps to reproduce the problem:**
add an LDAP-Group as user (NOT as Admin's - they are working fine)
Update Harbor from v2.2.2 to version 2.4.0
try to Login to the web-ui

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.40
- docker engine version: Docker version 20.10.9-ce, build 79ea9d308018
- docker-compose version: docker-compose version 1.24.1, build 4667896b

**Additional context:**

- **Harbor config files:**
[harbor.yml.txt](https://github.com/goharbor/harbor/files/7581185/harbor.yml.txt)

- **Log files:** unfortunately we had to restore the whole harbor vm from an offline-snapshot, so we are unable to provide more logs-files. The key error message was:

 `Nov 19 13:03:08 172.22.0.1 core[2767]: 2021-11-19T12:03:08Z [WARNING] [/core/auth/ldap/ldap.go:135]: Failed to fetch ldap group configuration:pq: duplicate key value violates unique constraint "unique_group_name" `

 `Nov 19 13:03:08 172.22.0.1 core[2767]: 2021-11-19T12:03:08Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: pq: current transaction is aborted, commands ignored until end of transaction block `

 `Nov 19 13:03:50 172.22.0.1 core[2767]: 2021-11-19T12:03:50Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'  `

 `Nov 19 13:04:09 172.22.0.1 core[2767]: 2021-11-19T12:04:09Z [WARNING] [/core/auth/ldap/ldap.go:135]: Failed to fetch ldap group configuration:pq: duplicate key value violates unique constraint "unique_group_name" `

 `Nov 19 13:04:09 172.22.0.1 core[2767]: 2021-11-19T12:04:09Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: pq: current transaction is aborted, commands ignored until end of transaction block `

 `Nov 19 13:04:15 172.22.0.1 core[2767]: 2021-11-19T12:04:15Z [WARNING] [/core/auth/ldap/ldap.go:82]: Failed to bind user, username: <snipped>, dn: CN=<snipped>,OU=<snipped>,OU=<snipped>,DC=<snipped>,DC=<snipped>,DC=de, error: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839 `

 `Nov 19 13:04:16 172.22.0.1 core[2767]: 2021-11-19T12:04:16Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: Failed to authenticate user, due to error 'LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839#000`

**Comment by stonezdj** [comment]
Because the error is from LDAP server, please check if the login into the LDAP server with the user and password.

**Comment by Krumbelfix** [comment]
The ldap-server did not change. 
The user was able to login right bevor the update and after the restore. Nothing changed on the LDAP site, the credentials are saved in keypass so the wrong kombination is not the issue.

**Comment by Krumbelfix** [comment]
We uesed the same AD credentials:
Test-harbor v2.4.0 - non admin: UI login isn't possible
prod-harbor v2.2.2 - non admin: UI login is OK

**Comment by kuznetsovkk** [comment]
Same error.
We have 1 AD and 2 harbors: test (updated from v2.3.2 to v2.3.4) and prod (v2.3.2).
Before update both harbors were v2.3.2, and ldap-configuration was the same.
After upgrading test-harbor to 2.3.4 cant login in web UI using ldap user - invalid credentials. Logs:

```
Dec 13 16:11:02 172.22.0.1 core[13753]: 2021-12-13T13:11:02Z [WARNING] [/core/auth/ldap/ldap.go:135]: Failed to fetch ldap group configuration:pq: duplicate key value violates unique constraint "unique_group_name"
Dec 13 16:11:02 172.22.0.1 core[13753]: 2021-12-13T13:11:02Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: pq: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by stonezdj** [comment]
Could you please paste the postgres.log, it should have detail information about the unique_group_name
```
pq: duplicate key value violates unique constraint "unique_group_name"
```
The error message should be 
```
Dec  9 10:06:19  postgresql[6131]: ERROR:  duplicate key value violates unique constraint "unique_group_name"
Dec  9 10:06:19  postgresql[6131]: DETAIL:  Key (group_name)=(My group) already exists.
Dec  9 10:06:19  postgresql[6131]: STATEMENT:  INSERT INTO "user_group" ("group_name", "group_type", "ldap_group_dn") VALUES ($1, $2, $3) RETURNING "id"
```
It indicates that the user group `My group` is already exist in database, but with different LDAP group DN.
It is possible that LDAP group name is duplicated with existing the user_group.

When a user login, it calls populateGroup function to search or onboard the group in Harbor, usually, it search the group by LDAP group DN, if the ldap group dn is not found in Harbor, it consider it should create a new user group in Harbor, when creating the new user group, it named this user group with the `cn` by default, sometimes, the cn might be conflict, and it breaks the unique_group_name constraint.

You could check all user group of current user with this command:
```
docker run -it firstfloor/ldaputils:2.0 bash
>ldaputils
The ldap.json file doesn't exist, create a new one

# update the json with your ldap configurations
>vi ldap.json

# Search the ldap user with this command
>ldaputils -username mike02
================================================
Verify basic LDAP information
Start to search users
==> No LDAP user found in current search conditions.
Trying to find user mike02
==> User mike02 found!
==> User email is empty!
==> User in the group with dn: [cn=harbor_users,ou=groups,dc=example,dc=com] OnboardGroup: true
================================================
``` 

If you find which user group is duplicated, updated it to another name.
```
docker exec -it harbor-db bash
psql -U postgres -d registry
select * from user_group;
update user_group set group_name = 'My group duplicate'  where ldap_group_dn ='<previous dn>';
```
It is just a workaround, the final solution is to config the ldap_group_attribute_name with a unique attribute to avoid naming conflict.

**Comment by kuznetsovkk** [comment]
> It is just a workaround, the final solution is to config the ldap_group_attribute_name with a unique attribute to avoid naming conflict.

@stonezdj how to config the ldap_group_attribute_name with a unique attribute? Where should it be configured? In harbor.yml / in MSAD ?

**Comment by stonezdj** [comment]
sorry,  it should be 'LDAP Group GID' in the UI. 
 https://goharbor.io/docs/2.4.0/administration/configure-authentication/ldap-auth
<img width="543" alt="Screen Shot 2022-01-21 at 9 53 47 AM" src="https://user-images.githubusercontent.com/2696760/150451694-f4e68553-8f83-43b3-bca5-8f01998fad03.png">
<img width="502" alt="Screen Shot 2022-01-21 at 9 56 58 AM" src="https://user-images.githubusercontent.com/2696760/150451842-c449cfc5-64cf-4f0c-9adc-7871209df51c.png">

**Comment by kuznetsovkk** [comment]
We already use 'cn' in this field. In both harbors: test and prod. But the error still occurred

**Comment by stonezdj** [comment]
> We already use 'cn' in this field. In both harbors: test and prod. But the error still occures

Because the CN can be duplicated in Active Directory, you could set it to `sAMAccountName` instead.
