### ISSUE TITLE
Registry public.ecr.aws returns 404 during replication

### ISSUE THREAD

**Issue by hobti01** [goharbor/harbor#16055]
**Expected behavior and actual behavior:**
Expected that public.ecr.aws could be configured as a Harbor Registry, but returns a 404 when replicating images

**Steps to reproduce the problem:**
* Configure `public.ecr.aws` as a Registry of type `Docker Registry` (Attempting type `Aws ECR` fails the connectivity test) with anonymous authentication, confirm connectivity
<img src="https://user-images.githubusercontent.com/4631304/143395183-2972439e-bee8-4e6a-975f-44981be90f34.png" height="300">

* Attempt to replicate any image fails listing tags 
<img src="https://user-images.githubusercontent.com/4631304/143396297-6b5d6680-b1e2-479b-9cbd-190cdc68e663.png" height="100">

**Versions:**
- harbor version: [2.4.0]

**Additional context:**
Most likely this is due to an upstream issue as it is affecting all clients that list tags https://github.com/aws/containers-roadmap/issues/1262

**Comment by chlins** [comment]
Depends on https://github.com/aws/containers-roadmap/issues/1262.
