### ISSUE TITLE
同步到Tencent TCR问题

### ISSUE THREAD

**Issue by trotyoung** [goharbor/harbor#16050]
**Expected behavior and actual behavior:**

预期：

Harbor能够将仓库的新增、删除、清理等动作同步Tencent TCR

实际情况：

使用docker registry类型的同步目标，harbor中镜像清理后，镜像还在TCR中，实际已并不可用。

使用Tencent TCR类型的同步目标，部分仓库同步时报错，此处projectA同步失败，projectB同步成功。

<img src="https://user-images.githubusercontent.com/19234895/143199805-73275c89-055d-4c22-8b15-7bc692733b4f.png" alt="image-20211124160359415" style="zoom:33%;" />

```
Nov 24 10:50:19 192.168.208.1 core[2815]: 2021-11-24T02:50:19Z [WARNING] [/replication/adapter/tencentcr/sdk.go:133]: [tencent-tcr.PrepareForPush.isNamespaceExist] namespace=projectA, total=3
Nov 24 10:56:33 192.168.208.1 core[2815]: 2021-11-24T02:56:33Z [WARNING] [/replication/adapter/tencentcr/sdk.go:133]: [tencent-tcr.PrepareForPush.isNamespaceExist] namespace=projectB, total=1
Nov 24 10:56:33 192.168.208.1 core[2815]: 2021-11-24T02:56:33Z [WARNING] [/replication/adapter/tencentcr/sdk.go:26]: [tencent-tcr.PrepareForPush.createPrivateNamespace.skip_exist] namespace=projectB
Nov 24 10:56:33 192.168.208.1 core[2815]: 2021-11-24T02:56:33Z [WARNING] [/replication/adapter/tencentcr/sdk.go:63]: [tencent-tcr.PrepareForPush.createRepository.skip_exist] namespace=projectB, repository=busybox
```

配置docker registry类型的同步目标

<img src="https://user-images.githubusercontent.com/19234895/143199801-9b4d19b4-eaa7-4a06-96d6-289c9b1275a0.png" alt="image-20211124155643821" style="zoom:33%;" />

配置Tencent TCR类型的同步目标

<img src="https://user-images.githubusercontent.com/19234895/143199794-32bd73c8-851a-413b-aa20-882fea587f15.png" alt="image-20211124155519131" style="zoom:33%;" />

配置同步任务

<img src="https://user-images.githubusercontent.com/19234895/143199803-7c4e591a-184d-4feb-931e-377ae24e5257.png" alt="image-20211124155817156" style="zoom:33%;" />

**Steps to reproduce the problem:**

可以通过手动或事件触发同步任务来复现。

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.2.1-b0d63082]
- docker engine version: [19.03.12]
- docker-compose version: [1.25.4]

**Comment by kofj** [comment]
@trotyoung thx, I will fix this issue.

**Comment by chlins** [comment]
Close issue as fix pr:https://github.com/goharbor/harbor/pull/16279 has been merged.
