### ISSUE TITLE
helm: harbor as generic registry mirror

### ISSUE THREAD

**Issue by maitredede** [goharbor/harbor#16053]
Hello,

I am trying to replace the docker registry mirror with harbor, without reconfiguring everything that use it on my network.

I have deployed harbor v2.4.0 using helm (using ingress), and tried to configure it as a registry-mirror in my docker/daemon.json. When I docker pull, image seams to be pulled from docker registry, not harbor.

It seams there is a way to have harbor as registry mirror : https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md
Looks like #8082 already addressed this case, but I did not managed to make it work.

Is there a full complete working doc I can follow and test ? Or where should I search for diagnostics ?

Edit : found in ingress logs that harbor returns 401 for registry-proxy requests

**Comment by heww** [comment]
Harbor 2.0+ doesn't support registry mirror. If you want this feature, suggest deploying standalone distribution support the registry mirror.

**Comment by maxclac** [comment]
Will this feature be supported in the future?

**Comment by codepitbull** [comment]
Leaving this here for whoever is also mislead by this issue.
Harbor is able to mirror other registries fully and partially using the replication functionality.

https://goharbor.io/docs/1.10/administration/configuring-replication/
