### ISSUE TITLE
Harbor exporter not sending metrics after upgrade to 2.4.0

### ISSUE THREAD

**Issue by flaviomoringa** [goharbor/harbor#16057]
**Expected behavior and actual behavior:**
We are using the endpoint of the harbor-exporter metrics: http://harbor-exporter.harbor.svc.cluster.local:8001/metrics to gather metrics to prometheus.

Before the endpoint would just show the metrics.

We were using Harbor 2.3.2 installed through the helm chart, and just upgraded to the new 1.8.0 helm chart to have Harbor 2.4.0.

Other metrics endpoint work fine:
http://harbor-core.harbor.svc.cluster.local:8001/metrics
http://harbor-registry.harbor.svc.cluster.local:8001/metrics

But the exporter has the metrics we need the most to assess the health of the system.

Now it shows:
```
An error has occurred while serving metrics:

collected metric "harbor_project_total" { label:<name:"public" value:"false" > gauge:<value:134 > } was collected before with the same name and label values
```

**Steps to reproduce the problem:**
Just enable the Harbor exporter pod on the helm chart, and when running try to access the endpoint http://harbor-exporter.harbor.svc.cluster.local:8001/metrics

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.0

**Comment by flaviomoringa** [comment]
Hello @ninjadq , do you have any eta for this fix? It would really help us on our monitoring.

Thanks

**Comment by flaviomoringa** [comment]
@wy65701436  and @ninjadq  could this checked for 2.4.1 release?

Thanks

**Comment by chlins** [comment]
@flaviomoringa Hi, does your issue still exist? I've tried to upgrade harbor from 2.3.2 to 2.4.1 and not reproduce this problem.

**Comment by flaviomoringa** [comment]
@chlins Because the issue was not closed for 2.4.1 I did not update yet to 2.4.1 (was waiting for it to be fixed).
I will try to update to 2.4.1 and see if it still happens and I'll let you know.

Thanks for picking this up.

**Comment by flaviomoringa** [comment]
@chlins It seems it's still the same for me. Just updated from 2.4.0 to 2.4.1 and I stikll get this:

```
$ kubectl exec -it harbor-exporter-6d56d56b65-t462p -n harbor -- /bin/bash
harbor [ /harbor ]$ curl http://localhost:8001/metrics
An error has occurred while serving metrics:

collected metric "harbor_project_total" { label:<name:"public" value:"false" > gauge:<value:133 > } was collected before with the same name and label values
```

:-(

**Comment by flaviomoringa** [comment]
It seems there are at least 2 more issues open related with this: 
https://github.com/goharbor/harbor/issues/16312
https://github.com/goharbor/harbor/issues/16448

So maybe it should really be looked into :-(

**Comment by chlins** [comment]
@flaviomoringa I have tried to reproduce this issue in my environment, but It's not be reproduced, and actually it's hard to find out the root cause of the issue without reproducibility.

**Comment by flaviomoringa** [comment]
@chlins I know... and I understand that :-( Anything  might be able to help let me know. Maybe there is some race condition somehwere...

**Comment by QiuToo** [comment]
@flaviomoringa Can you provide me with the yaml file of your harbor export deployment? I would appreciate your generosity!

**Comment by flaviomoringa** [comment]
@QiuToo It seems this issue has been solved in https://github.com/goharbor/harbor/issues/16448 But I can still send the export deployment if you still need it.
