### ISSUE TITLE
Different scan results with trivy on identical Harbor instances

### ISSUE THREAD

**Issue by dan-m8t** [goharbor/harbor#16052]
Hi there,

I use two different but identical (in configuration) Harbor instances because of security related issues.
Replication works fine between both instances (Pull, Harbor A <- Harbor B).
I use trivy as scanning engine on both instances, both are running the same Harbor version and also trivy versions.
For some images I get different results when scanning the image for vulnerabilities.

Here's some data:

Harbor A:

Harbor Version: v2.3.3-a0a9ed8a
Trivy Version: v0.17.2
harbor.scanner-adapter/vulnerability-database-updated-at:11/24/21, 7:40 AM

Harbor B:

Harbor Version: v2.3.3-a0a9ed8a
Trivy Version: v0.17.2
harbor.scanner-adapter/vulnerability-database-updated-at:11/24/21, 7:40 AM

Scan results on Harbor A:

![grafik](https://user-images.githubusercontent.com/48068660/143237956-8160f1dd-8aab-4e1e-bd2f-0e7d1833174d.png)

Scan results on Harbor B:

![grafik](https://user-images.githubusercontent.com/48068660/143237998-1bf40132-f5ea-4e8a-b55d-200c527c6883.png)

Note the digest, this is the same image, scanned with identical scanning engine.

I tried to find any database related stuff for that image but wasn't able to find anything suitable.

I checked the size of the trivy database, both got the same size, so I guess those are identical:

Harbor A:

`scanner [ / ]$ stat /home/scanner/.cache/trivy/db/trivy.db
  File: /home/scanner/.cache/trivy/db/trivy.db
  Size: 211308544        Blocks: 412712  IO Blocks: 512  regular file`

Harbor B:

`scanner [ / ]$ stat /home/scanner/.cache/trivy/db/trivy.db
  File: /home/scanner/.cache/trivy/db/trivy.db
  Size: 211308544        Blocks: 412712  IO Blocks: 512  regular file`

Any idea what is causing this behaviour? I already deleted the image and replicated it again, same results.

Where should I take a look?

Thanks 

Dan

**Comment by wy65701436** [comment]
hi @danielpacak , can you help on that?

**Comment by heww** [comment]
This issue may be caused by the same reason of this issue https://github.com/goharbor/harbor/issues/15623. 

Please try upgrading to harbor v2.4.0+.

**Comment by dan-m8t** [comment]
Is this even fixed in 2.3.4? I wanted to wait a little bit until upgrade to 2.4.0

**Comment by heww** [comment]
No, it's not fixed in 2.3.4. If you can't upgrade the harbor, you can just replace the trivy adapter container with the trivy adapter image in harbor 2.4.0.

> Is this even fixed in 2.3.4? I wanted to wait a little bit until upgrade to 2.4.0

**Comment by dan-m8t** [comment]
Thanks for your input, I'll give it a try

**Comment by dan-m8t** [comment]
That didn't fix the issue :( I replaced both 2.3.3 trivy adapter containers with the 2.4.0, no luck. I also downloaded the trivy.db manually and put it into the cache folder of the container, same results. Any other clue?

**Comment by dan-m8t** [comment]
Hi @danielpacak I investigated a little bit further, it seems that this affects lots of images which has been scanned prior with a different scanning engine (anchore), I switched to trivy because it is way faster and more stable than the anchore scanner adapter for harbor. 
Could this issue comes from some kind of caching or something? I am not sure where the reports for any image is stored.
I got some images that has never been scanned on one of the harbor instances, I triggerd a scan for one of that images and here I'll get the same results as expected.

**Comment by danielpacak** [comment]
1. We should take out of picture other scanners (like anchor) and make sure that it's a problem with trivy scanner (in isolation)
2. Only then we can check that it only happens after switching from one scanner engine to the other
3. In both cases deterministic steps to reproduce (with particular image digest) would be very helpful

We store vulnerability data in PostgreSQL. You can cleanup vulnerability data with the following SQL.

**NB** Make sure to have a DB backup and restore procedure in place. I also assume that you understand what you're doing ;)

``` sql
delete from vulnerability_record;
delete from report_vulnerability_record;
delete from scan_report;
```

**Comment by dan-m8t** [comment]
This seems to work as expected, I deleted all records on both instances and started a new full scan. Right now it looks good. I'll keep you updated if this fixed it.

Thanks

**Comment by dan-m8t** [comment]
I can finally confirm this fixed the issue, thanks @danielpacak and @heww
