### ISSUE TITLE
harbor UI界面时间格式怎么调整为24小时制？

### ISSUE THREAD

**Issue by arsenalpoll** [goharbor/harbor#16060]
What can we help you?

默认显示的时间是：**AM** 或者**PM** 
`3/24/21, 9:16 AM`

改哪里的配置可能设置成 **24小时制**

**Comment by AllForNothing** [comment]
@arsenalpoll 目前Harbor  UI  并未有对外暴露配置项， 你可以手动修改源码， 然后重新构建Harbor.
可将改行代码[https://github.com/goharbor/harbor/blob/main/src/portal/src/app/shared/pipes/harbor-datetime.pipe.ts#L22]
修改为`return new DatePipe(lang).transform(value, `yyyy/MM/dd HH mm ss`);`

参考 https://angular.cn/api/common/DatePipe
