### ISSUE TITLE
repositories gone when upgrade form 1.10.4 to 2.4.0

### ISSUE THREAD

**Issue by finalha** [goharbor/harbor#16079]
Hi all:
I just got the issue when upgrading harbor from 1.10.4 to 2.4.0. Following the wiki: https://goharbor.io/docs/2.4.0/administration/upgrade/
The services are all OK.
![图片](https://user-images.githubusercontent.com/13330963/144569145-c6913c66-6207-4230-b794-b7d6f16aa84b.png)
But the repositories are gone which are OK in harbor 1.10.4.
![图片](https://user-images.githubusercontent.com/13330963/144569696-819f100b-8f9d-4f55-a652-5f082a17463b.png)

And 
docker exec -it registry cat /etc/registry/config.yml
`

> version: 0.1
> log:
>   level: info
>   fields:
>     service: registry
> storage:
>   cache:
>     layerinfo: redis
>   filesystem:
>     rootdirectory: /storage
>   maintenance:
>     uploadpurging:
>       enabled: false
>   delete:
>     enabled: true
> redis:
>   addr: redis:6379
>   readtimeout: 10s
>   writetimeout: 10s
>   dialtimeout: 10s
>   password: 
>   db: 1
>   pool:
>     maxidle: 100
>     maxactive: 500
>     idletimeout: 60s
> http:
>   addr: :5000
>   secret: placeholder
>   debug:
>     addr: localhost:5001
> auth:
>   htpasswd:
>     realm: harbor-registry-basic-realm
>     path: /etc/registry/passwd
> validation:
>   disabled: true
> compatibility:
>   schema1:
>     enabled: true

`
The docker version is Docker version 20.10.3, build 48d30b5
How to fix this issue?

**Comment by wy65701436** [comment]
how did you upgrade your Harbor? Can you clarify the upgrade path?

**Comment by finalha** [comment]
> how did you upgrade your Harbor? Can you clarify the upgrade path?
I have followed the wiki: https://goharbor.io/docs/2.4.0/administration/upgrade/ 
My old harbor(v1.10.4) path is /opt/harbor and data folder is /opt/docker-hub/data
Commands are in below with user root:

1.
`cd /opt/harbor; docker-compose down`
2.
`mv /opt/harbor /root/my_backup_dir/harbor`
3.
`cp -rf /opt/docker-hub/data /root/my_backup_dir/`
4.
`tar zxf <harbor 2.4.0 offline package>;docker image load -i harbor/harbor.v2.4.0.tar.gz`
5.
`mkdir -p /opt/harbor; docker run -it --rm -v /:/hostfs goharbor/prepare:v2.4.0 migrate -i /root/my_backup_dir/harbor/harbor.yml -o /opt/harbor/harbor.yml -t 2.4.0`
6.
`cd /opt/harbor;  bash install.sh --with-trivy --with-chartmuseum`

The status of services are all OK. But my old docker images are gone

**Comment by finalha** [comment]
> how did you upgrade your Harbor? Can you clarify the upgrade path?

Otherwise, I found that in https://github.com/goharbor/harbor/releases
As release v1.10.9 drops the migrator support, if you're experiencing upgrade Harbor from previous v1.10 to v2.0 forward, you should skip this build and use v1.10.7 as a springboard.
So maybe v1.10.4->v1.10.7->v2.4.0 should be OK? I will try this way.

**Comment by zyyw** [comment]
@finalha ,  in your /opt/harbor/harbor.yml, what is the value set for `data_volume` field?

**Comment by steven-zou** [comment]
`v1.10.4->v1.10.7->v2.4.0 ` this upgrading path does not work. You have to upgrade to 2.0 at least and then move on to 2.x.

**Comment by finalha** [comment]
> @finalha , in your /opt/harbor/harbor.yml, what is the value set for `data_volume` field?
`data_volume: /opt/docker-hub/data`

**Comment by finalha** [comment]
> `v1.10.4->v1.10.7->v2.4.0 ` this upgrading path does not work. You have to upgrade to 2.0 at least and then move on to 2.x.

So v1.10.4->v1.10.7->v2.0.0->v2.4.0 should be OK?

**Comment by kebyn** [comment]
I also started to upgrade from `v1.10.2`, and found that the data disappeared after upgrading to `v2.3.4`. After several attempts, I confirmed that I can only upgrade to `v2.2.4`. My upgrade path is `v1.10.2`->`v2.0.6`- >`v2.1.6`->`v2.2.4`, once the upgrade version to `v2.3`, all data will disappear

**Comment by finalha** [comment]
> I also started to upgrade from `v1.10.2`, and found that the data disappeared after upgrading to `v2.3.4`. After several attempts, I confirmed that I can only upgrade to `v2.2.4`. My upgrade path is `v1.10.2`->`v2.0.6`- >`v2.1.6`->`v2.2.4`, once the upgrade version to `v2.3`, all data will disappear

Thank you for applying the information. How about the version v2.2.4?  Any important functions with v2.0.6?
