### ISSUE TITLE
harbor-core private key issue

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#16073]
**Expected behavior and actual behavior:**
Expected: The harbor built and installed from the source code can perform docker login normally
Actual: Use the docker log command to report an error 500 from the harbor built and installed from the source
**Steps to reproduce the problem:**
1.Execute in the harbor source code directory`./tests/showtime.sh ./tests/ci/api_common_install.sh $IP DB` named installation harbor
2.Run the command docker login

**Additional context:**
`docker login xx.xxx.xxx.xxx -u admin -p Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://xx.xxx.xxx.xxx/v2/: received unexpected HTTP status: 500 Internal Server Error`
core.log
`Dec  1 06:16:09 172.26.0.1 core[29474]: 2021-12-01T06:16:09Z [ERROR] [/core/service/token/token.go:49]: Unexpected error when creating the token, error: unable to get PrivateKey from PEM type: PRIVATE KEY`

**Comment by wy65701436** [comment]
close it as fixed.
