### ISSUE TITLE
Typo in the docs: gpg receive keys command

### ISSUE THREAD

**Issue by T0T4R4** [goharbor/harbor#16072]
There is a typo in the doc at
https://goharbor.io/docs/2.0.0/install-config/download-installer/

The command to receive GPG keys should be 
gpg --keyserver hkps://keyserver.ubuntu.com **--recv-keys** 644FF454C0B4115C

**Comment by wy65701436** [comment]
PR to fix it is welcome, thanks. Raise Pr to https://github.com/goharbor/website
