### ISSUE TITLE
Modify Headers When Connecting To Docker based registries (needed for registry.redhat.io)

### ISSUE THREAD

**Issue by headkm** [goharbor/harbor#16075]
**Is your feature request related to a problem? Please describe.**
Our team has been working to create a proxy cache connection to the Quay based [registry.redhat.io](https://registry.redhat.io/) registry. Our current issue is after we successfully create a replication endpoint to the registry we get "unsupported manifest file" errors when trying to perform pulls. 

**Describe the solution you'd like**
After consulting with Red Hat we determined that while the registry.redhat.io registry supports schema v2 manifests it will default to pulling schema v1 manifests if a particular header media type (`"Accept: application/vnd.docker.distribution.manifest.v2+json"`) is not explicitly referenced in the header of the pull request. 

Another solution could be to allow Quay registries to include additional pathing such as `registry.redhat.io/v2/` to ensure a schema v2 manifest is pulled. 

**Describe the main design/architecture of your solution**
In any calls to a Quay based registry I would suggest modifying either the replication endpoint logic or payload request logic to include one of the above solutions. 

**Describe the development plan you've considered**
This is not a breaking change so any timeline the project sees fit to incorporate this change into the design 

**Additional context**
full text of the Red Hat engineer's test below
UBI8 image being tested, parsing the manifest raw:

```
$ skopeo inspect --raw docker://registry.redhat.io/ubi8 | jq ''
{
  "manifests": [
    {
      "digest": "sha256:8ee9d7bbcfc19d383f9044316a5c5fbcbe2df6be3c97f6c7a5422527b29bdede",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
	"architecture": "amd64",
	"os": "linux"
      },
      "size": 737
    },
    {
      "digest": "sha256:de0185f0fed3bc78c2055a3753a9aa2c8c77de3a8bf5a7d621b11c396cf417fa",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
	"architecture": "arm64",
	"os": "linux"
      },
      "size": 737
    },
    {
      "digest": "sha256:03ef40d7edca9e5ac4900493ace629be45be8258ccdbbdd1c14bf147025faa71",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
	"architecture": "ppc64le",
	"os": "linux"
      },
      "size": 737
    },
    {
      "digest": "sha256:737eafb6d1bd51655b661ac25f1e048c02f722cf00d2942150c1ca77a44f0b64",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
	"architecture": "s390x",
	"os": "linux"
      },
      "size": 737
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
}

```
The advertised mediatype on this manifest list is `application/vnd.docker.distribution.manifest.list.v2+json` which is a Media Type advertised as a fat manifest, and the manifests present in the fat manifest indicate `application/vnd.docker.distribution.manifest.v2+json` which is manifest type V2Schema2 as per the definitions:

	https://docs.docker.com/registry/spec/manifest-v2-2/

Since skopeo inspects the fat manifest only, let's check it with curl:

	
```
$ curl -s -u "$myuser:$mypass" "https://sso.redhat.com/auth/realms/rhcc/protocol/redhat-docker-v2/auth?service=docker-registry&client_id=curl&scope=repository:rhel:pull" | jq ''
	{
	  "token": "xxx",
	  "access_token": "xxx",
	  "expires_in": 300,
	  "issued_at": "2021-12-01T17:34:49Z"
	}
```

With the token, we have to set our Accept type explicitly as per:

	https://docs.docker.com/registry/spec/api/#pulling-an-image

Let's specify we want v2:

```
$ curl -L -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://registry.redhat.io/v2/ubi8/manifests/8.4 | jq ''
	{
	  "schemaVersion": 2,
	  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	  "config": {
	    "mediaType": "application/vnd.docker.container.image.v1+json",
	    "size": 4366,
	    "digest": "sha256:b1e63aaae5cffb78e4af9f3a110dbad67e8013ca3de6d09f1ef496d00641e751"
	  },
	  "layers": [
	    {
	      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
	      "size": 83303635,
	      "digest": "sha256:eac1b95df832dc9f172fd1f07e7cb50c1929b118a4249ddd02c6318a677b506a"
	    },
	    {
	      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
	      "size": 1789,
	      "digest": "sha256:47aa3ed2034c4f27622b989b26c06087de17067268a19a1b3642a7e2686cd1a3"
	    }
	  ]
	}
```

If we do not *explicitly* state SchemaV2 in the Accept header, it will default to SchemaV1:

```
$ curl -L -s -H "Authorization: Bearer $TOKEN" https://registry.redhat.io/v2/ubi8/manifests/8.4 | jq ''
	{
	  "schemaVersion": 1,
	  "name": "ubi8",
	  "tag": "8.4",
	  "architecture": "amd64",
	  "fsLayers": [
	    {
	      "blobSum": "sha256:47aa3ed2034c4f27622b989b26c06087de17067268a19a1b3642a7e2686cd1a3"
	    },
	    {
	      "blobSum": "sha256:eac1b95df832dc9f172fd1f07e7cb50c1929b118a4249ddd02c6318a677b506a"
	    }
	  ],
	  "history": [
	    {
	      "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"4f9012b22b61\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"container=oci\"],\"Cmd\":[\"/bin/bash\"],\"ArgsEscaped\":true,\"Image\":\"bdcbd8c599a3eacb9b766797ebcdf86521642812af98ad459990c68a0d83651a\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":[],\"Labels\":{\"architecture\":\"x86_64\",\"build-date\":\"2021-10-26T13:03:15.222780\",\"com.redhat.build-host\":\"cpt-1003.osbs.prod.upshift.rdu2.redhat.com\",\"com.redhat.component\":\"ubi8-container\",\"com.redhat.license_terms\":\"https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI\",\"description\":\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\",\"distribution-scope\":\"public\",\"io.k8s.description\":\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\",\"io.k8s.display-name\":\"Red Hat Universal Base Image 8\",\"io.openshift.expose-services\":\"\",\"io.openshift.tags\":\"base rhel8\",\"maintainer\":\"Red Hat, Inc.\",\"name\":\"ubi8\",\"release\":\"213\",\"summary\":\"Provides the latest release of Red Hat Universal Base Image 8.\",\"url\":\"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.4-213\",\"vcs-ref\":\"ed5adf70c28eb951940c72f4173fa32c4bca2165\",\"vcs-type\":\"git\",\"vendor\":\"Red Hat, Inc.\",\"version\":\"8.4\"}},\"container_config\":{\"Hostname\":\"4f9012b22b61\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"container=oci\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"mv -fZ /tmp/ubi.repo /etc/yum.repos.d/ubi.repo || :\"],\"ArgsEscaped\":true,\"Image\":\"sha256:b77375d1c9cade801467fe061a324581b894c9c4c27270cc242e114e4f2e0c10\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":[],\"Labels\":{\"architecture\":\"x86_64\",\"build-date\":\"2021-10-26T13:03:15.222780\",\"com.redhat.build-host\":\"cpt-1003.osbs.prod.upshift.rdu2.redhat.com\",\"com.redhat.component\":\"ubi8-container\",\"com.redhat.license_terms\":\"https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI\",\"description\":\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\",\"distribution-scope\":\"public\",\"io.k8s.description\":\"The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\",\"io.k8s.display-name\":\"Red Hat Universal Base Image 8\",\"io.openshift.expose-services\":\"\",\"io.openshift.tags\":\"base rhel8\",\"maintainer\":\"Red Hat, Inc.\",\"name\":\"ubi8\",\"release\":\"213\",\"summary\":\"Provides the latest release of Red Hat Universal Base Image 8.\",\"url\":\"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.4-213\",\"vcs-ref\":\"ed5adf70c28eb951940c72f4173fa32c4bca2165\",\"vcs-type\":\"git\",\"vendor\":\"Red Hat, Inc.\",\"version\":\"8.4\"}},\"created\":\"2021-10-26T13:03:40.047826Z\",\"docker_version\":\"1.13.1\",\"id\":\"bfcd338c0e4a121c6b2256bb5296cfa11829b9d63812e1d93aa978b4f6107462\",\"os\":\"linux\",\"parent\":\"383e2d353d9c7c0911bec3c884ac50609352333b4ddc152a7668692b3bdeaed8\"}"
	    },
	    {
	      "v1Compatibility": "{\"id\":\"383e2d353d9c7c0911bec3c884ac50609352333b4ddc152a7668692b3bdeaed8\",\"comment\":\"Imported from -\",\"created\":\"2021-10-26T13:03:29.480973679Z\",\"container_config\":{\"Cmd\":[\"\"]}}"
	    }
	  ],
	  "signatures": [
	    {
	      "header": {
		"jwk": {
		  "crv": "P-256",
		  "kid": "EZQE:QY3W:LZ7M:DHUW:FLDW:TRLU:UF4G:6AL5:D5L2:X2PH:OJVN:FNLJ",
		  "kty": "EC",
		  "x": "-hPxNwGHwnllz6Um-U3RnukN4h3PH0sD3tscViZYf6U",
		  "y": "qDNafrhP1eJNwUKOIqs7c2m7cNK_DTYIEgjR2c_EIXU"
		},
		"alg": "ES256"
	      },
	      "signature": "Y9FgmWHU_JlaQIbaFrjgag7PdE7WiVDeTEf-oZK0LajiCzIWm-wTl9cipxMyhMHeuxtZj0g7O626v_lutRCNIg",
	      "protected": "eyJmb3JtYXRMZW5ndGgiOjUxMjMsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAyMS0xMS0wMlQwOTowNDowNloifQ"
	    }
	  ]
	}
```

Perhaps the outgoing request is not explicitly setting the Media-Type on the Accept type to "application/vnd.docker.distribution.manifest.v2+json"?  If you do not explicitly set the "Accept" on the GET request received on the server, it assumes SchemaV1."

**Comment by chlins** [comment]
@headkm hi, which adapter did you use for replication, docker-registry or quay?

**Comment by evanstoner** [comment]
Hi there, the Red Hat registries are not actually powered by Quay. However, I have replicated this issue on Harbor 2.4.0 with the Docker Registry adapter:

```
$ podman pull --tls-verify=false 192.168.56.112/rh-docker/ubi8/ubi:latest
Trying to pull 192.168.56.112/rh-docker/ubi8/ubi:latest...
Error: determining manifest MIME type for docker://192.168.56.112/rh-docker/ubi8/ubi:latest: Manifest does not match provided manifest digest sha256:8ee9d7bbcfc19d383f9044316a5c5fbcbe2df6be3c97f6c7a5422527b29bdede
```

Where `rh-docker` is a proxy cache project backed by a Docker Registry provider pointing to `https://registry.access.redhat.com`.

Related: https://github.com/goharbor/harbor/issues/14401

**Comment by headkm** [comment]
Interesting. When we spoke with Red Hat they told us they were using Quay for that registry. Either way glad you were able to replicate it.

**Comment by chlins** [comment]
@headkm Sorry, I did not get your point clearly,  do you want to use proxy cache or replication with quay?

**Comment by headkm** [comment]
@chlins Our goal is to use a proxy cache, but the issue is with how the replication endpoint is connecting to the registry. Because of this we wouldn't even be able to use it for replication because we are not able to explicitly set the media type to accept manifest schema v2.

**Comment by chlins** [comment]
@stonezdj Could you take a look about this issue, does the proxy cache support quay registry?

**Comment by evanstoner** [comment]
@chlins to clarify, the goal is to create a proxy cache of the Red Hat registries (registry.redhat.io and registry.access.redhat.com), not Quay registries. (There was some earlier confusion about whether the Red Hat registries are powered by Quay; they are not.)

@headkm can you update the issue title to reflect that and remove Quay? E.g. "Docker Registry type should include Accept headers".

FWIW in the Docker Registry docs (https://docs.docker.com/registry/spec/api/#pulling-an-image) this is stated:

> The client should include an Accept header indicating which manifest content types it supports.

**Comment by headkm** [comment]
@evanstoner I'm hesitant to do that because we were **explicitly** told by Red Hat that registry.redhat.io uses Quay as a backend. We still have our ticket open with them so I can confirm that again.

**Comment by headkm** [comment]
@evanstoner I apologize for the confusion. It looks like Red Hat has never told us what backs registry.redhat.io, instead they randomly mentioned quay.io works with harbor so we assumed registry.redhat.io was using the same backend registry. I updated the ticket to mention docker; which is probably what is really backing it, but Red Hat gave us another non answer when asked.

**Comment by evanstoner** [comment]
Not stale - this enhancement is still needed based on recent comment on related issue: https://github.com/goharbor/harbor/issues/14401#issuecomment-1071196541

**Comment by childofthewired** [comment]
I'm also seeing the same thing:
Trying to pull [harbortest.testlab.org:80/harbortest/ubi8:latest.](http://harbortest.testlab.org/harbortest/ubi8:latest.)..
DEBU[0000] Copying source image //[harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest) to destination image [overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on][harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest)
DEBU[0000] Trying to access "[harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest)"
DEBU[0000] Found credentials for [harbortest.testlab.org:80/harbortest/ubi8](http://harbortest.testlab.org/harbortest/ubi8) in credential helper containers-auth.json in file /run/user/0/containers/auth.json
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for [harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest), using built-in default file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/[harbortest.testlab.org:80](http://harbortest.testlab.org/)
DEBU[0000] GET https://harbortest.testlab.org:80/v2/    
DEBU[0000] Ping https://harbortest.testlab.org:80/v2/ err Get "https://harbortest.testlab.org:80/v2/": http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://harbortest.testlab.org:80/v2/", Err:(*errors.errorString)(0xc000eabbf0)})
DEBU[0000] GET [http://harbortest.testlab.org:80/v2/](http://harbortest.testlab.org/v2/)    
DEBU[0000] Ping [http://harbortest.testlab.org:80/v2/](http://harbortest.testlab.org/v2/) status 401
DEBU[0000] GET http://harbortest.testlab.org/service/token?account=admin&scope=repository%3Aharbortest%2Fubi8%3Apull&service=harbor-registry
DEBU[0000] GET [http://harbortest.testlab.org:80/v2/harbortest/ubi8/manifests/latest](http://harbortest.testlab.org/v2/harbortest/ubi8/manifests/latest)
DEBU[0002] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json"
DEBU[0002] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb
DEBU[0002] Source is a manifest list; copying (only) instance sha256:88b67c5c3d7bc900e0dc77c058601c618758e3c79d468ebfe446e91c45657b46 for current system
DEBU[0002] GET [http://harbortest.testlab.org:80/v2/harbortest/ubi8/manifests/sha256:88b67c5c3d7bc900e0dc77c058601c618758e3c79d468ebfe446e91c45657b46](http://harbortest.testlab.org/v2/harbortest/ubi8/manifests/sha256:88b67c5c3d7bc900e0dc77c058601c618758e3c79d468ebfe446e91c45657b46)
DEBU[0002] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json"
DEBU[0002] Error pulling candidate [harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest): determining manifest MIME type for docker://[harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest): Manifest does not match provided manifest digest sha256:88b67c5c3d7bc900e0dc77c058601c618758e3c79d468ebfe446e91c45657b46
Error: determining manifest MIME type for docker://[harbortest.testlab.org:80/harbortest/ubi8:latest](http://harbortest.testlab.org/harbortest/ubi8:latest): Manifest does not match provided manifest digest sha256:88b67c5c3d7bc900e0dc77c058601c618758e3c79d468ebfe446e91c45657b46

**Comment by evanstoner** [comment]
Red Hat will begin ditching v2schema1 support on June 22, and ultimately use quay.io to service registry requests, which may make this issue obsolete. More info: https://access.redhat.com/articles/6138332

**Comment by stonezdj** [comment]
Verify with Harbor proxy cache, the registry.redhat.io returns schema version is 2
```
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "schemaVersion": 2
```
but still get the error in the docker client
```
unsupported manifest format
```
