### ISSUE TITLE
it is psobile to use rleative urls for all harbor projects?

### ISSUE THREAD

**Issue by huckley** [goharbor/harbor#16070]
I wish that I can harbor map to a relative url.
Background: I use harbor as docker registry, but the clients which are have access to it have access only to one hostname. (restricted firewalls with https mitm)
On this hostname also other projects are available.
I wish that I can map like all access 
=>  nginx/frontendproxy ( https://example.com/harbor) => harbor.
Is this Posible or not?

**Comment by steven-zou** [comment]
@huckley 

Can you describe more clearly what do you want and share with us more use cases?

**Comment by huckley** [comment]
I work i a company which have multiple installations of their software running on the customers servers.
The software is a wild mix of different software stacks.
The updater use one host like update.example.com.
Some Customers have restricted Firewalls and proxys. So the whitelist only the url https://update.example.com/*.
Now we want to use Harbor as registry.
During decisions in the past this world only possible to run habor in a path like https://update.example.com/harbor.
The Idea is that a nginx proxys (outside of harbor) the requests https://update.example.com/harbor to the nginx of harbor.
At the moment this seems not possible, because harbor like only the answer on https://update.example.com/*.
