### ISSUE TITLE
Link to Harbor Logos Broken on Site

### ISSUE THREAD

**Issue by pnbrown** [goharbor/harbor#16076]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The link in the website's footer goes to a 404 on GitHub.

**Steps to reproduce the problem:**
Click the Logos link in the footer of the website.

**Versions:**
N/A

**Additional context:**
N/A

**Comment by wy65701436** [comment]
hi, can you give a screenshot for which link you point to?

**Comment by pnbrown** [comment]
Hi. It's the link that says logos, not artwork. Sorry.

![Screenshot_20211205-111507.png](https://user-images.githubusercontent.com/10396286/144756476-eceb1364-ace4-47a2-b932-0d4893681b42.png)

**Comment by steven-zou** [comment]
@jonasrosland / @a-mccarthy 

Could you take a look at this issue and see if this issue should be moved to the website repo?
