### ISSUE TITLE
Registry Garbage Collection still fails on NFS backend

### ISSUE THREAD

**Issue by zkb-cisupport** [goharbor/harbor#16084]
This Issue was first reported [here](https://github.com/goharbor/harbor/issues/13589) as "fourth issue: internal server error on unlinkat command on registry NFS filesystem". This was supposed to be solved by this [commit](https://github.com/goharbor/harbor/pull/14287/commits/7e83cc5284aaf2e3f5f9d65b61f0209cd7b2d25a) as described in this [pull request](https://github.com/goharbor/harbor/pull/14287). The Pull request is closed, with [comment](https://github.com/goharbor/harbor/pull/14287#issuecomment-784988731) "Let's hold this change for a while and push distribution to merge this change contain it in the next patch release."

However, current main branch is still missing the commit from this pull request, and we are still experiencing the same garbage collection failure on NFS filesystem.

From the [distribution patch 3309](https://patch-diff.githubusercontent.com/raw/distribution/distribution/pull/3309.patch) it seems there should be line 
```
defer r.Close()
```
in the function _getContent()_ on [this line](https://github.com/goharbor/harbor/blob/7e67c1f495a47c48dcebf598df9e0dfbf9ecc3e4/src/vendor/github.com/docker/distribution/registry/storage/io.go#L21). This patch has already been [applied upstream](https://github.com/distribution/distribution/blob/cc4627fc6e5f20cfe8534492b44331fa16ccf872/registry/storage/io.go#L21).

Could you merge the patch 3309 as described by the closed [pull request 14278](https://github.com/goharbor/harbor/pull/14287) ?

**Comment by wy65701436** [comment]
the fix was already merged, see https://github.com/goharbor/harbor/pull/14356.
