### ISSUE TITLE
I would like to ability to remove the namespace when replicating to Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by garrmark** [goharbor/harbor#16089]
What can we help you?
Is there a way to set up replication to strip the namespace and use a root namespace?  

ACR allows me to put things in the "root" namespace.

For example, I'd like to go from `my.repo/library/image:latest` to `acr.registry.com/image:latest` the namespace field allows me to either leave it empty and reuse the library namespace or replace library, but using . or / isn't allowed.

For more context, see the slack discussion at https://cloud-native.slack.com/archives/CC1E09J6S/p1638894589268100

**Comment by joseaio** [comment]
Also valid for Nexus replicas without namespace or library (in my case)

**Comment by bmerry** [comment]
@garrmark you closed this - did you find a solution or just give up?

**Comment by garrmark** [comment]
@bmerry, I no longer use harbor, but I'll re-open it and see what happens

**Comment by dmitry-g** [comment]
This feature would be useful for us too

**Comment by vyas-n** [comment]
I also need this feature since my work uses separate instances of registries for image promotion for each environment, and they don't all use harbor.

@garrmark, out of curiosity, do you use a registry that has this feature? If so, mind if I know what it is?

**Comment by vyas-n** [comment]
Hey @garrmark,

Mind closing the issue as "Not Planned" instead of "Complete".

<img width="484" alt="Screenshot 2024-10-15 at 12 36 23" src="https://github.com/user-attachments/assets/f7d6d54f-6960-4c9b-a4fe-c31b2d323730">

That way, folks referring back to this issue in the future know that the Harbor team doesn't intend to implement it, instead of thinking that the feature is there.

**Comment by garrmark** [comment]
> I also need this feature since my work uses separate instances of registries for image promotion for each environment, and they don't all use harbor.
> 
> @garrmark, out of curiosity, do you use a registry that has this feature? If so, mind if I know what it is?

No, sorry
