### ISSUE TITLE
High memory usage during Trivy scan since upgrade to 2.3

### ISSUE THREAD

**Issue by polatsinan** [goharbor/harbor#16095]
**Expected behavior and actual behavior:**
Since we have upgraded Harbor (to v2.3.4-7a068b12) we notice very high memory usage when we scan images using trivy. The system has 6GB of memory. Whenever we scan an image (in this case an image with ~2000 vulnerabilities), the memory usage goes sky high. From ~15% memory utilization to 100% memory utilization.

![Schermafbeelding 2021-12-08 om 10 35 30](https://user-images.githubusercontent.com/1501084/145184763-6fbe13b3-9580-48df-86ed-d2195ef36a90.png)

This is the output of `ps aux --sort -rss`, as you can see trivy is using +80% memory during a scan:
```bash
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
10000     3649 19.5 82.5 7971032 4907328 ?     Sl   10:24   0:48 /usr/local/bin/trivy --no-progress --cache-dir /home/scanner/.cache/trivy --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --vuln-type os,library --format json --output /home/scanner/.cache/reports/scan_report_005371186.json core:8080/project_dev/img-service@sha256:35b1d145fce5bee021e6d74116746bf2ec03ae2ee56a4ad74c60fe3b6e4cfb0f
10000     3509  0.1  1.8 1130072 107940 ?      Sl   Nov25  28:21 /harbor/harbor_core
10000     2623  0.2  0.9 1172304 54596 ?       Sl   Nov25  47:03 /harbor/harbor_jobservice -c /etc/jobservice/config.yml
root      1715  0.5  0.6 2405424 38676 ?       Ssl  Nov25  95:11 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
10000     3288  0.1  0.5 714284 32648 ?        Sl   Nov25  20:17 /home/scanner/bin/scanner-trivy
polkitd   3270  0.1  0.3 219312 19620 ?        Ss   10:24   0:00 postgres: postgres registry 172.18.0.9(59032) idle
polkitd   3280  0.0  0.2 219592 17524 ?        Ss   10:24   0:00 postgres: postgres registry 172.18.0.9(59240) idle
polkitd   3271  0.0  0.2 218444 17420 ?        Ss   10:24   0:00 postgres: postgres registry 172.18.0.9(59034) idle
polkitd   3272  0.0  0.2 219596 16664 ?        Ss   10:24   0:00 postgres: postgres registry 172.18.0.9(59038) idle
```
**Steps to reproduce the problem:**
Vulnerability scanning using Trivy.

**Versions:**

- harbor version: v2.3.4-7a068b12
- docker engine version: 20.10.10, build b485636
- docker-compose version: 1.18.0, build 8dd22a9

**Comment by danielpacak** [comment]
👋 @polatsinan We've see a similar behaviour where Trivy may require more memory than usually for certain container images.

Could you share somehow the image core:8080/project_dev/img-service@sha256:35b1d145fce5bee021e6d74116746bf2ec03ae2ee56a4ad74c60fe3b6e4cfb0f so we can reproduce and see what is going on? /cc @knqyf263

**Comment by danielpacak** [comment]
We keep upgrading Trivy with improvements to memory management. If the problem persists with the latest version integrated with Harbor, please provide a minimal reproducible container image so we can pull it down in our dev environments and debug why Trivy requires so much memory.
