### ISSUE TITLE
integrate with my own SSO(base oauth2.0)

### ISSUE THREAD

**Issue by yuanlin-yoyo-worker** [goharbor/harbor#16115]
As you see,we have a independent SSO system,base on oauth2.0. How can we integrate  the harbor with it, any advise?

**Comment by Vad1mo** [comment]
you should use OIDC, many oauth provider support also OIDC.

If this isn't possible, you can use some services like auth0, https://github.com/dexidp/dex, https://www.authelia.com/ or https://www.keycloak.org/.

There are so many solutions out there that it makes little sense for Harbor to support different OAuth methods, as they aren't standardized.
