### ISSUE TITLE
Github sponsoring support for harbor

### ISSUE THREAD

**Issue by vbasem** [goharbor/harbor#16130]
**Is your feature request related to a problem? Please describe.**
No, but given how interesting the project is, we would like to financially contribute to its stability and activity.

**Describe the solution you'd like**
We would like to support this great project by sponsoring it if possible

**Describe the main design/architecture of your solution**
1. Define few financial goals that would benefit the project and define-add them to the github sponsors program.
2. Document and enable the option with github
3. Provide transparency regarding the cash flow within the project

**Describe the development plan you've considered**
--

**Additional context**
--

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by OrlinVasilev** [comment]
Hi @vbasem, I'm the Community manager for Harbor! Thanks for reaching out!
I would love to discuss your proposal and how we can drive it forward with CNCF, not sure if we can do much right now around Christmas break but January we will, keep in touch!

**Comment by OrlinVasilev** [comment]
Hi @vbasem we will need support from CNCF it self, @amye @idvoretskyi can you advice here please?

**Comment by idvoretskyi** [comment]
My suggestion would be to use the LFX Crowdfunding platform instead - https://crowdfunding.lfx.linuxfoundation.org

**Comment by OrlinVasilev** [comment]
@idvoretskyi does that mean we have to create like a crowdfunding for Harbor and the folks from Daimler can donate there? And then we can use that as funding for the community like, travels, swag etc...?

**Comment by idvoretskyi** [comment]
@OrlinVasilev yes, correct (I can create it for you if you prefer).

**Comment by vbasem** [comment]
One of the reasons we asked about github sponsoring, was due to the work and clearance we have put into the process (mainly legal/tax). For any other platform we have to do the same. Once you are certain which platform works best, do let me know and I have to run after the legal work required for it.

**Comment by idvoretskyi** [comment]
@vbasem I can make a connection for you, Orlin and LFX team so you could figure out more details, specifically from the legal standpoint (feel free to shoot an email to me at ihor(at)cncf.io).

**Comment by OrlinVasilev** [comment]
@vbasem any update on your side?

**Comment by vbasem** [comment]
I apologize, for the lack of update. I did trigger the process internally for the legal checks and all the paper work required for LFX funding service. This will take a while on our side. Hence I would propose closing this issues until we are ready to fund over LFX.

I appreciate all the work gone into this project and hope it keeps thriving.

Thank you.

**Comment by wgehring** [comment]
Let me jump in :-) - currently, we can only sponsor through GitHub sponsors, as @vbasem mentioned. I have asked GitHub to support you, in case you would like to set up GH Sponsors on your side. That would be easiest for us, but of course I don't know about on your side. 
 
We are planning to add more platforms through which we can do sponsoring, like LFX Crowdfunding. The whole process of adding another platform is, unfortunately, a bit complicated on our side, but I hope that we can do it by, say, mid 2022. So if you prefer to use LFX Crowdfunding, I would leave you on our list, but it would be delayed by a bit. :-) Let me know what you think.
