### ISSUE TITLE
Encrypt admin password

### ISSUE THREAD

**Issue by Sandy7894** [goharbor/harbor#16134]
Hi,

We have deployed Harbor on top of EC2 instance with EBS backed, behind a load balancer. Usually as per the installation doc, we need to provide the harbor admin password & other config in harbor.yml file, is there any way we can encrypt the passwords and other sensitive data in config file?

Also as per our setup, Harbor is running on port 80 (basically nginx container on host port) and load balancer is accepting the connections on 443, and sending the traffic to port 80 on Harbor VM. I am able to access UI and APIs using load balancer but when i try to access harbor for docker login, it is expecting me to open SG to Harbor VM over port 80 also from source server instead of just from load balancer SG.. Is there anyway we can turn off this behaviour. 

Thanks and Regards,
Sandeep.

**Comment by bitsf** [comment]
you can change admin password from GUI.
you should set `external_url` in harbor.yaml
No effective method to encrypt config file yet, as it always need a decrypt method, you or others can also give suggestion.
