### ISSUE TITLE
Robots cannot delete images or tags even with the necessary privileges

### ISSUE THREAD

**Issue by kopytov** [goharbor/harbor#16133]
Hello!

We need to delete images after tests in our CI. I have encountered that I get `UNAUTHORIZED` error on this action when I use robots.

It is possible to reproduce the problem at [demo.goharbor.io](https://demo.goharbor.io/) as follows:

1. Create a project and a robot with all possible permissions.
2. Authorize in the registry with the robot account using `docker login`.
3. Push some image to the registry.
```
docker pull ubuntu:focal
docker tag docker.io/library/ubuntu:focal demo.goharbor.io/kopytov/ubuntu:focal
docker push demo.goharbor.io/kopytov/ubuntu:focal
```
4. Get a digest of the pushed image.
```
curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    -siL \
    -u 'robot$kopytov+ebobot:secret' \
    https://demo.goharbor.io/v2/kopytov/ubuntu/manifests/focal \
    | grep docker-content-digest:
```
```
docker-content-digest: sha256:26c3bd3ae441c873a210200bcbb975ffd2bbf0c0841a4584f4476c8a5b8f3d99
```
5. Try to remove the image by the digest, we get an error.
```
curl -X DELETE -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    -siL \
    -u 'robot$kopytov+ebobot:secret' \
    https://demo.goharbor.io/v2/kopytov/ubuntu/manifests/sha256:26c3bd3ae441c873a210200bcbb975ffd2bbf0c0841a4584f4476c8a5b8f3d99
```
```
HTTP/2 401
date: Thu, 16 Dec 2021 14:38:10 GMT
content-type: application/json; charset=utf-8
content-length: 182
server: nginx
docker-distribution-api-version: registry/2.0
www-authenticate: Basic realm="harbor"
x-request-id: 551134c0-53b0-4bbd-8e1c-951ef4376494

{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to access repository: kopytov/ubuntu, action: delete: unauthorized to access repository: kopytov/ubuntu, action: delete"}]}
```
6. If I send the same request with my own credentials, the image will be deleted successfuly.
```
curl -X DELETE -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
    -siL \
    -u 'kopytov:secret' \
     https://demo.goharbor.io/v2/kopytov/ubuntu/manifests/sha256:26c3bd3ae441c873a210200bcbb975ffd2bbf0c0841a4584f4476c8a5b8f3d99
```
```
HTTP/2 202
date: Thu, 16 Dec 2021 15:06:13 GMT
content-length: 0
server: nginx
x-request-id: dad162c3-52d0-428b-8206-ba75bf6e9489
```

**Comment by YangJiao0817** [comment]
@kopytov 
You are using the wrong API. Use the robot account to delete the artifact API as follows: 
`curl -X 'DELETE'   'https://demo.goharbor.io/api/v2.0/projects/kopytov/repositories/ubuntu/artifacts/sha256:26c3bd3ae441c873a210200bcbb975ffd2bbf0c0841a4584f4476c8a5b8f3d99'   -H 'accept: application/json'   -u 'robot$kopytov+ebobot:secret'`
For more harbor API information, you can refer to `https://{your domain}/devcenter-api-2.0 `

**Comment by kopytov** [comment]
@YangJiao0817 thank you!

But it's strange that I can do it by standard registry API with my own credentials but cannot with a robot. It could be useful to work with registry in CI with tools like [regctl](https://github.com/regclient/regclient) which works with standard registy API.

**Comment by annkam** [comment]
I have the same issue with system level Robot Accounts. If I configure replication with a Robot Account which has all possible permissions granted, it gets permission denied on deleting artifacts on the destination registry. Harbor v2.4.1

2022-01-24T11:16:57Z [INFO] [/controller/replication/transfer/image/transfer.go:125]: client for source registry [type: harbor, URL: http://harbor-core:80, insecure: true] created
2022-01-24T11:16:57Z [INFO] [/controller/replication/transfer/image/transfer.go:135]: client for destination registry [type: harbor, URL: https://***, insecure: false] created
2022-01-24T11:16:57Z [ERROR] [/controller/replication/transfer/image/transfer.go:408]: failed to delete the manifest of artifact test/hello:latest on the destination registry: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to access repository: test/hello, action: delete: unauthorized to access repository: test/hello, action: delete"}]}

**Comment by wy65701436** [comment]
@annkam for your problem, it's fixed in main branch, and will be in v2.5. What you have to do is give the repositry-delete scope for you robot.

**Comment by wy65701436** [comment]
@kopytov did you try the @YangJiao0817 mentioned API path? It works for Harbor. You should try with  -H 'accept: application/json' in your request.

**Comment by kopytov** [comment]
@wy65701436 no, I didn't. My main goal was to use regctl to delete images, but it works only with standard registry API paths.

**Comment by haiwu** [comment]
I just hit the same issue, trying to use regctl/regbot to delete image, failing in the same way. It seems harbor 2.5 will be released soon?

**Comment by haiwu** [comment]
@wy65701436 : also tested the above mentioned API path, yes it is working. But ideally would still want to get regctl/regbot to work as is.

**Comment by wy65701436** [comment]
@haiwu I havn't any experienced on regctl, can you share how do you use it? cc @YangJiao0817

**Comment by ChristianCiach** [comment]
Issue is still valid. I have a system-level robot account that has all permissions that can be granted via the UI, but deleting an artifact still always returns `401` with the body `{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}`.

Harbor version is `v2.6.2` and I am using the `/api/v2.0/projects/{project}/repositories/{repo_urlenc}/artifacts/{digest}` endpoint with the http method `DELETE` and an `Accept` header of `application/json`.

`GET` requests work fine, so the credentials are valid. I've double checked that.

**Comment by coder-hugo** [comment]
It's still not possible to delete image tags via the [docker registry api](https://docs.docker.com/registry/spec/api/#deleting-an-image) using a robot account. The request still ends in the following response, although the robot has got all permissions:
```
{                                                                                                                                                             
    "errors": [                                                                                                                                               
        {                                                                                                                                                     
            "code": "UNAUTHORIZED",                                                                                                                           
            "message": "unauthorized to access repository: test/alpine, action: delete: unauthorized to access repository: test/alpine, action: delete"                                                                                                                                                                       
        }                                                                                                                                                     
    ]                                                                                                                                                         
}  
```
