### ISSUE TITLE
Harbor stuck Readonly - docs unclear on how to stop

### ISSUE THREAD

**Issue by robertgates55** [goharbor/harbor#16132]
I'm running Harbor 2.0 (we're yet to quite update), and GC has now been running for 9 hours - my registry is read only.

I'd like to abort the GC job and retrigger it for the weekend when fewer people rely on the registry.

I found the docs here https://github.com/goharbor/harbor/wiki/Harbor-FAQs#stuck-in-read-only-mode but what values to use for the `[INDEX]` is not clear (they reference the wrong steps, and even correcting for that it's not clear which value to use for [INDEX])

```
127.0.0.1:6379[1]> zrange {harbor_job_service_namespace}:period:policies 0 -1
1) "{\"id\":\"366fb0240a59edae924f540c\",\"job_name\":\"IMAGE_GC\",\"cron_spec\":\"0 0 0 * * *\",\"job_params\":{\"admin_job_id\":\"5\",\"delete_untagged\":false,\"redis_url_reg\":\"redis://harbor-harbor-redis:6379/2\"},\"web_hook_url\":\"http://harbor-harbor-core:80/service/notifications/jobs/adminjob/5\"}"
2) "{\"id\":\"ecc99b249316205ad3dd4f14\",\"job_name\":\"SCHEDULER\",\"cron_spec\":\"0 0 0 * * *\",\"job_params\":{\"callback_func\":\"SchedulerCallback\",\"params\":\"{\\\"PolicyID\\\":1,\\\"Trigger\\\":\\\"Schedule\\\"}\"},\"web_hook_url\":\"http://harbor-harbor-core:80/service/notifications/schedules/1\"}"
```

But then what to use as the inputs for the `ZREMRANGEBYLEX` command?
```
127.0.0.1:6379[1]> ZREMRANGEBYLEX {harbor_job_service_namespace}:period:policies 0 1
(error) ERR min or max not valid string range item
```

**Comment by wy65701436** [comment]
In v2.0, the duration of GC depends on the image count and storage. We've move GC to non-blocking and have a obvious improvement on performance, recommend to upgrade to latest.

You can uncheck the read-only button for temporary solution, and wait for the GC complete.
