### ISSUE TITLE
Trivy is not fully disconnected usable with skip_update

### ISSUE THREAD

**Issue by sizowie** [goharbor/harbor#16145]
When using the Trivy scanner with Harbor and the configuration setting `skip_update: true`, my expectations is that scans can be done fully disconnected from the internet. OS scanning works as expected with offline db patterns. But at least with Harbor 2.4 Trivy runs with ENV `SCANNER_TRIVY_VULN_TYPE=os,library` meaning that libraries/files types with JAR/WAR/EAR will be scanned dynamically through search.maven.org with the checksum of the corespoding files.

That results in really slow scans when having no internet connectivity, as the scanner will retry to reach search.maven.org.

Either the vuln_type should be configurable in harbor.yml or a dependency between `skip_update:true` and the SCANNER_TRIVY_VULN_TYPE (meaning = OS only) should be set, as long as trivy doesn't have a fix for that.

See also https://github.com/aquasecurity/trivy/issues/1185

Harbor: 2.4.0

**Comment by heww** [comment]
Hi, @danielpacak seems that this issue was resolved in trivy. Do we need to bump up a new release of trivy in harbor 2.4.x to resolve this problem on the harbor side?

**Comment by danielpacak** [comment]
> Hi, @danielpacak seems that this issue was resolved in trivy. Do we need to bump up a new release of trivy in harbor 2.4.x to resolve this problem on the harbor side?

This would require bumping up Trivy to 0.22.0 in harbor-scanner-trivy and add support for the --offline-scan flag that was added to resolve exactly this problem.
