### ISSUE TITLE
There is a SSRF security vulnerability in the v2

### ISSUE THREAD

**Issue by garenwen** [goharbor/harbor#16141]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.3]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ninjadq** [comment]
hi, for security reporting, please follow this step https://github.com/goharbor/harbor/blob/main/SECURITY.md#reporting-a-vulnerability---private-disclosure-process
