### ISSUE TITLE
源码无法编译

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16154]
[root@harbor251 harbor-2.3.1]# pwd
/root/harbor/harbor-2.3.1
[root@harbor251 harbor-2.3.1]# ls
ADOPTERS.md  CHANGELOG.md  contrib          docs   LICENSE  Makefile   README.md    ROADMAP.md   src    tools
api          codecov.yml   CONTRIBUTING.md  icons  make     OWNERS.md  RELEASES.md  SECURITY.md  tests  VERSION
[root@harbor251 harbor-2.3.1]# make
fatal: Needed a single revision
Sending build context to Docker daemon  62.09MB
Step 1/6 : ARG GOLANG
Step 2/6 : FROM ${GOLANG}
 ---> e5b4455acc93
Step 3/6 : ARG SPECTRAL_VERSION
 ---> Using cache
 ---> ec36d34612a9
Step 4/6 : RUN curl -fsSL -o /usr/bin/spectral https://github.com/stoplightio/spectral/releases/download/$SPECTRAL_VERSION/spectral-linux && chmod +x /usr/bin/spectral
 ---> Running in ca25c26d4d89

说明：
https://github.com/stoplightio/spectral/releases/download/不存在，无法完成源码编译安装部署。

**Comment by wy65701436** [comment]
please specify the  NPM_REGISTRY in the make command, like `make install NPM_REGISTRY={the registry address}`

**Comment by bitsf** [comment]
it looks like the var `SPECTRAL_VERSION` is losing, please check your environment

**Comment by QiuToo** [comment]
> 

我已手动安装spectral
[root@harbor-code harbor-2.3.5]# ls  -l  /usr/bin/spectral
-rwxr-xr-x. 1 root root 57043724 12月  7 07:45 /usr/bin/spectral
