### ISSUE TITLE
docker image auto cleanup policy not work properly

### ISSUE THREAD

**Issue by AbhijitPatil1992** [goharbor/harbor#16156]
Hi Team,

I am new in harbor so I want to add auto cleanup policy for docker images in harbor. I was tried to add retention policy it's running successfully but not removing docker images from harbor registry. can some one please look into it.

![image](https://user-images.githubusercontent.com/91177718/147054009-b3d61cb1-74d6-4f75-95ed-6ef2a56fe28f.png)

![image](https://user-images.githubusercontent.com/91177718/147054121-89d2f6f4-044f-44b8-a626-110ada12a5d6.png)

Harbor version : 2.3.5-239680cd

logs:
registry       | 172.19.0.8 - - [22/Dec/2021:08:05:08 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
harbor-portal  | 172.19.0.8 - - [22/Dec/2021:08:05:08 +0000] "GET / HTTP/1.1" 200 531 "-" "Go-http-client/1.1"
registryctl    | 172.19.0.8 - - [22/Dec/2021:08:05:08 +0000] "GET /api/health HTTP/1.1" 200 9
nginx          | 10.4.149.49 - "POST /api/v2.0/retentions/1/executions HTTP/1.1" 201 0 "http://harborhosts.com/harbor/projects/2/tag-strategy/tag-retention" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" 0.032 0.031 .
nginx          | 10.4.149.49 - "GET /api/v2.0/retentions/1/executions?page=1&page_size=15 HTTP/1.1" 200 1599 "http://harborhosts.com/harbor/projects/2/tag-strategy/tag-retention" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" 0.013 0.012 .
harbor-portal  | 127.0.0.1 - - [22/Dec/2021:08:05:18 +0000] "GET / HTTP/1.1" 200 1167 "-" "curl/7.78.0"
registry       | 172.19.0.8 - - [22/Dec/2021:08:05:18 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
registryctl    | 172.19.0.8 - - [22/Dec/2021:08:05:18 +0000] "GET /api/health HTTP/1.1" 200 9
harbor-portal  | 172.19.0.8 - - [22/Dec/2021:08:05:18 +0000] "GET / HTTP/1.1" 200 531 "-" "Go-http-client/1.1"
registryctl    | 127.0.0.1 - - [22/Dec/2021:08:05:19 +0000] "GET /api/health HTTP/1.1" 200 9

**Comment by wy65701436** [comment]
Did you check the dry run results to see whether it meets your expection? If not, what is it?

**Comment by bitsf** [comment]
don't add project name as prefix
