### ISSUE TITLE
Handling vulnerabilities "Scan all" behavior for a large number of images

### ISSUE THREAD

**Issue by ShabiDabi** [goharbor/harbor#16158]
I would like to share an issue that we are dealing with regarding the "scan all" behavior.

Currently, when performing "Scan All", whether manually triggered or automatically(scheduled), Harbor sends scan requests in batches (looks like batches of 50 requests) for all the images in the registry. In registries that contain a **large number of images**, this may result in a big amount of requests to handle, as harbor sends requests on all images in the registry and expects us to send an OK for each request. 

This behavior requires us to aggregate requests in memory which might result in an unusual memory footprint. As we can't aggregate all requests, after a certain limit we have to fail requests. Scan request congestion also leads to longer handling of the requests, this also eventually results in Harbor timeouts requesting reports on images.

Is it possible to add a functionality that will make Harbor send another batch of requests only after responses to the previous batch were returned (either success or failures)? 
It will slow down the scan but at least it will make it predictive in terms of load and timeouts. Another possible solution can be adding handling of 429 responses, which will slow down the request rate and resend failed images later.

**Comment by wy65701436** [comment]
@heww please help to evaluate it.

**Comment by heww** [comment]
How many artifacts are there in your registry?

**Comment by ShabiDabi** [comment]
It can get to 100k artifacts. But in our case, it fails also with 3k artifacts. Basically, we have a limited number of scanning resources, so we just can’t handle harbor request load, and we have no way to lower the request rate.
