### ISSUE TITLE
The container goharbor/harbor-db:v2.3.5 restart error Every time

### ISSUE THREAD

**Issue by huangenlong** [goharbor/harbor#16164]
The container goharbor/harbor-db:v2.3.5 restart error Every time。
error：
initdb: error: directory “/var/lib/postgresql/data/pg13“ exists but is not empty

**Comment by stonezdj** [comment]
maybe file privilege in this directory is incorrect.

**Comment by wy65701436** [comment]
if it's installed by docker compose, you can try to add `privilege=true` in the harbor-db.

**Comment by huangenlong** [comment]
That's the right approach.The problem was solved. thank you !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goharbor/harbor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goharbor/harbor] The container goharbor/harbor-db:v2.3.5 restart error Every time (Issue #16164)





 
if it's installed by docker compose, you can try to add privilege=true in the harbor-db.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by halfhoney** [comment]
add  privileged: true
