### ISSUE TITLE
Projects page: when filtering between all projects and my projects the label doesnt change

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#1617]
it looks like it always shows the first thing in the drop down filter. even after switching the filter says "My projects"
![screen shot 2017-03-15 at 4 40 55 pm](https://cloud.githubusercontent.com/assets/626032/23969829/2f2f08e0-099e-11e7-888d-c142a015918b.png)

**Comment by wknet123** [comment]
Fixed
