### ISSUE TITLE
不同架构的镜像推到仓库后 tag 没了

### ISSUE THREAD

**Issue by saodis** [goharbor/harbor#16176]
不同架构的镜像推到仓库后 tag 没了，这样拉镜像就只能拉有 tag 的了，有办法解决么？

**Comment by wy65701436** [comment]
did you push them one by one into Harbor? If so, you can try to use image index to handle it.

**Comment by saodis** [comment]
@wy65701436 image index ? 意思是拉的时候加镜像哈希值？这样
`docker pull busybox@sha256:db67d231d7de3d552b371543cf04d8f702482bc04d841997fcee2b1400d2cb83`
