### ISSUE TITLE
How to get image size via API harbor

### ISSUE THREAD

**Issue by jcdelarosa7** [goharbor/harbor#16175]
is it possible to get the image size via API in harbor? i tried suggestion on this issue https://github.com/goharbor/harbor/issues/7603, but this seems to be not working anymore as tags is not clickable in UI

**Comment by miaoshixuan** [comment]
/projects/{project_name}/repositories/{repository_name}/artifacts

**Comment by AllForNothing** [comment]
@jcdelarosa7 

you can get it from both the artifact list and detail APIs:
![image](https://user-images.githubusercontent.com/30999793/148001167-fa6fe259-2237-436b-a5a7-15773aa4e101.png)

![image](https://user-images.githubusercontent.com/30999793/148001021-ee24e797-ea98-4dc3-8312-e2b8e68e260b.png)

**Comment by jcdelarosa7** [comment]
Thanks guys
