### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by mail2sandeepd** [goharbor/harbor#16179]
Hi 

I have deployed Harbor 2.4 for my environment, it's working perfectly, We have a requirement to add additional opensource image Vulnerability scanner.

Trivy is working fine, we just want to add additional security scanner, can anyone please help me complete setup guide or documentation for opensource scanner. (I was trying to work with clair but unable to configure it correctly, able to run clair but not able to integrate it from harbor).

Any related help will be much appreciated.

Thanks.

**Comment by wy65701436** [comment]
please follow this spec. https://github.com/goharbor/pluggable-scanner-spec
