### ISSUE TITLE
Push and pull images to the root path

### ISSUE THREAD

**Issue by zkryakgul** [goharbor/harbor#16183]
Hi,
I have an existing docker registry in my infrastructure and i want to move it to the harbor. But on my existing docker registry(v2 docker image) there are so many images in the root.(like. reg.my.domain/image1:tag)

I was setup the harbor with compose and I added my existing registry into registries section. After that i created replication job. But when process comes to replicate the images which i described above it fails. It says:

```
failed to get project , error: project name required
```

I already know I can set the destination Namespace and apply flattining to it but in this scenero I need to edit almost half of my production kubernetes resources to set new image names to them.

So is there way to use the images like  `reg.my.domain/image1:tag`?

**Comment by Vad1mo** [comment]
Harbor needs a project/namespace. There is no automatic mapping to the `library` like in docker.io

**Comment by wy65701436** [comment]
the namespace(project) is the foundational definition in Harbor, no way to drop it.
