### ISSUE TITLE
disk space is not free.

### ISSUE THREAD

**Issue by GeGavin** [goharbor/harbor#16182]
I have deleted the image from Harbor 2.4.1 UI but the disk space is not free.

**Comment by colinwilson** [comment]
Did you run the Garbage Collection (GC)?

Also GC doesn't remove recently deletes images from disk space until 2 hours after their deletion timestamp (see related issue I opened a few days ago, #16167).

Try waiting a couple of hours and running GC again, see if that frees up your disk space.

**Comment by wy65701436** [comment]
You should exe GC to release the disk space, artifact deletion only releases project quota.

And please be aware the time window to reserve deleted artifacts, the default is two hours.
