### ISSUE TITLE
OIDC - Unable to recover username for auto onboard

### ISSUE THREAD

**Issue by JoooostB** [goharbor/harbor#16180]
With auto-onboard enabled, user login through OIDC fails with error in harbor-core: 
```
{"code":"INTERNAL_SERVER_ERROR","message":"unable to recover username for auto onboard, username claim: email"}
```
However, the username claim `email` **is** included in the user info string:
```
[DEBUG] [/core/controllers/oidc.go:225]: User info string: {"iss":"https://login.hooli.com/adfs","sub":"YzI5dFpWUm9hVzVuVW1GdVJHOXRSazlTWjJsVVNWTlRkV1U9=","name":"","email":"gilfoyle.bertram@hooli.com","groups":["Pied_Piper_Admin"],"admin_group_member":true}
```

We have multiple Harbor instances, one for prod (v2.2.1-b0d63082) and one for test (v2.4.1-c4b06d79). Test has a newer version and is not working. Prod works fine with equal settings. We're hesitating to update prod as this issue would have a very high impact.

We're using an OIDC logging provider with the following settings:*

| Auth Mode            | OIDC                                       |
|----------------------|--------------------------------------------|
| OIDC Provider Name   | HOOLI-CORP                                 |
| OIDC Endpoint        | https://login.hooli.com/adfs               |
| OIDC Client ID       | REDACTED                                   |
| OIDC Client Secret   | REDACTED                                   |
| Group Claim Name     | group                                      |
| OIDC Admin Group     | Pied_Piper_Admin                           |
| OIDC Scope           | email,offline_access,openid,profile,groups |
| Verify Certificate   | TRUE                                       |
| Automatic onboarding | TRUE                                       |
| Username Claim       | email                                      |  

\* _Sensitive info has been redacted_

## Expected behaviour
OIDC login should succeed with auto-onboard enabled, as the user info string contains the email of the logged in user. Instead the user instantly gets the following error after successfully logging in at our OIDC provider and thus is unable to access Harbor:
```
{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
```
This seems to correspond with error log below in harbor-core:
```
[DEBUG] [/pkg/oidc/helper.go:209]: Raw ID token for verification: REDACTED
[WARNING] [/pkg/oidc/helper.go:271]: Failed to get userInfo by calling remote userinfo endpoint, error: 401 Unauthorized:  
[DEBUG] [/pkg/oidc/helper.go:281]: Fall back to user data from ID token.
[DEBUG] [/core/controllers/oidc.go:132]: Doing automatic onboarding
[ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"unable to recover username for auto onboard, username claim: email"}]} 
```
I checked the Raw JWT token by decoding it back to JSON, which results in:
```json
{
  "aud": "REDACTED",
  "iss": "https://login.hooli.com/adfs",
  "iat": 1640792352,
  "exp": 1640795952,
  "auth_time": 1640792238,
  "mfa_auth_time": 1640792250,
  "sub": "REDACTED",
  "upn": "gilfoyle.bertram@hooli.com",
  "unique_name": "HOOLI\\gilfoyle001",
  "pwd_exp": "4902352",
  "sid": "REDACTED",
  "email": "gilfoyle.bertram@hooli.com",
  "group": [
    "Pied_Piper_Admin"
  ],
  "apptype": "Confidential",
  "appid": "REDACTED",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "ver": "1.0",
  "scp": "profile openid offline_access email"
}
```
To me this looks to be complete, as it contains both the neccessary username claim (email) and list of group(s). 

## Steps to reproduce
1. Enable login through OIDC and ADFS provider
1. Enable auto-onboard
1. Try to login as OIDC-user  

## Workaround
When disabling auto-onboard, OIDC login does work and the User info string seem to contain the necessary info. 
```
[DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="c29tZVRoaW5nUmFuRG9tRk9SZ2lUSVNTdWU="]: an unauthorized security context generated for request POST /c/oidc/onboard
[DEBUG] [/core/controllers/oidc.go:225]: User info string: {"iss":"https://login.hooli.com/adfs","sub":"YzI5dFpWUm9hVzVuVW1GdVJHOXRSazlTWjJsVVNWTlRkV1U9=","name":"","email":"gilfoyle.bertram@hooli.com","groups":["Pied_Piper_Admin"],"admin_group_member":true}
[DEBUG] [/core/controllers/oidc.go:193]: User created: gilfoyle.bertram@hooli.com
```

## Versions
Our instance is installed using the latest Helm Chart (2.4.1) onto our Kubernetes cluster:
* Harbor: 2.4.1
* Docker engine: 19.3.12
* Helm Version: 3.7.2

## Additional context:
I think information above shoul be sufficient to diagnose the issue, but if not; please let me know and I'll provide everything that's neccessary.

**Comment by JoooostB** [comment]
I think I narrowed down the root cause of this issue to some changes made in #15625.

When a user does not exist and userInfoFromRemote fails: https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L269 
[mergeUserInfo](https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L287) is never called, which leads to `local.Username` to remain empty (as this is handled by `mergeUserInfo`).
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L273-L277

What I'd like to suggest is setting the Username if it's still empty, after setting the autoOnboardUsername:
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L358

I will submit a PR to address my suggestion, which I tested prior on our test environment and seems to resolve the issue entirely.

**Comment by reasonerjt** [comment]
Thanks for pointing this out, please see my comment in the PR
