### ISSUE TITLE
delete user and change LDAP to OIDC 

### ISSUE THREAD

**Issue by wyaopeng** [goharbor/harbor#16201]
docker  version:
![image](https://user-images.githubusercontent.com/12064306/148753179-20f1c219-2578-4be9-9701-589b14e78434.png)
server version
![image](https://user-images.githubusercontent.com/12064306/148753260-0b0c1b19-8375-48fd-9349-01119373ba04.png)

delete user change LDAP to OIDC 

The login and WEB-UI  is OK;but  docker login is err;
someting wrong with:
![image](https://user-images.githubusercontent.com/12064306/148752690-fb9c1f12-a271-4ac9-b5e7-c6a962bfc115.png)

docker login err:
![image](https://user-images.githubusercontent.com/12064306/148752852-f0d21d9d-1125-4189-b8e7-3ca7d9d49904.png)
![image](https://user-images.githubusercontent.com/12064306/148756862-e51b294b-003c-4d51-95cb-1b2dc27f5c64.png)

Then ,I use the robot-user is ok!
![image](https://user-images.githubusercontent.com/12064306/148753035-1d1e8ac6-5117-4787-a0f6-d66bc84f4f6b.png)

so，how to fix it?

**Comment by Moep90** [comment]
@wyaopeng would you share your fix, if there is any?
