### ISSUE TITLE
how export image

### ISSUE THREAD

**Issue by GeGavin** [goharbor/harbor#16216]
Sometimes, you can't link to the network,so can't  visit docker hub.How to publish offline

**Comment by rgadeev** [comment]
https://docs.docker.com/engine/reference/commandline/save/
https://docs.docker.com/engine/reference/commandline/load/

**Comment by GeGavin** [comment]
> https://docs.docker.com/engine/reference/commandline/save/ https://docs.docker.com/engine/reference/commandline/load/

I want a link to export in the harbor Web UI

**Comment by wy65701436** [comment]
can you clarify the problem here?

**Comment by GeGavin** [comment]
> 
I want to have a page function.Turn the image into a tar package and download this tar package.
export image function  same as  other docker hub(portainer.io)

**Comment by rgadeev** [comment]
as far as I know, it is impossible to upload an image through the UI.
use command on host with network :
```
docker pull image:tag
docker tag image:tag harbor.domen.local:tag
docker push harbor.domen.local:tag
```

or
save and transfer the archive to a host where there is access to harbor
```
docker tag image:tag harbor.domen.local:tag
docker push harbor.domen.local:tag
```

**Comment by rgadeev** [comment]
> I want to have a page function.Turn the image into a tar package and download this tar package.
> export image function same as other docker hub(portainer.io)

the fact is that it may be redundant. Docker consists of layers, some of them are already present in the form of basic images. Whereas the archive contains all the layers. This will create an unnecessary load on the network and disks. If you can connect to docker hub and harbor, then you can use standard docker commands.

**Comment by GeGavin** [comment]
> > I want to have a page function.Turn the image into a tar package and download this tar package.
> > export image function same as other docker hub(portainer.io)
> 
> the fact is that it may be redundant. Docker consists of layers, some of them are already present in the form of basic images. Whereas the archive contains all the layers. This will create an unnecessary load on the network and disks. If you can connect to docker hub and harbor, then you can use standard docker commands.

thx,I think so, too

**Comment by wy65701436** [comment]
> > 
> 
> I want to have a page function.Turn the image into a tar package and download this tar package. export image function same as other docker hub(portainer.io)

No, Harbor doesn't support that and it's not in the roadmap as well. Docker pull & save could handle that.
