### ISSUE TITLE
Group members lose access to push or see projects on Harbor - LDAP authentication 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16220]
Under ldap_auth mode, some LDAP user can login, but they cannot access the project which they are group members.
During the user login, the core log output the error.
```
pq: duplicate key value violates unique constraint "unique_group_name"
```
Root cause:
When the LDAP user login, Harbor will retrieve the LDAP group which the current user is a member of.
and search the user_group to find out if existing user with the same ldap_group_dn exist, if not present, then create a user group , the group name is the CN of the group. but the CN might be duplicated in LDAP, it result in the duplicate user group name error.

**Comment by stonezdj** [comment]
Yes, it is the same issue

**Comment by stonezdj** [comment]
It seems for AD server, it is better to set the LDAP Group GID to  `sAMAcountName` rather than `CN`. because the 'sAMAccountName` can't be duplicated.

**Comment by kuznetsovkk** [comment]
> BTW, please double check the `LDAP group filter` is set, for AD server it should be `objectClass=groups`, for openLDAP it should be `objectClass=groupOfNames`

objectclass=group, not groups

**Comment by robbrucks** [comment]
We had the same problem with users not seeing projects via group membership.  
We discovered that there was a group (that wasn't even used for project membership) in Harbor that had a DN different from the one presented by LDAP/AD.  Either the group had been created manually with the wrong DN, or an AD admin had moved the group to a different tree structure which changed the DN.
