### ISSUE TITLE
Image names with slash failed to pull when using proxy-cache

### ISSUE THREAD

**Issue by jansobczak** [goharbor/harbor#16222]
So I follow https://goharbor.io/docs/2.3.0/administration/configure-proxy-cache/
but unfortunately this doesn't work for images that have slash in name.

**Expected behavior and actual behavior:**
I'm able to pull docker images with / in iname like ubuntu/nginx

**Steps to reproduce the problem:**
```
docker pull registry-public/docker-hub/library/ubuntu/nginx:latest
Error response from daemon: unknown: repository docker-hub/library/ubuntu/nginx not found

docker pull registry-public/docker-hub/library/ubuntu:latest
latest: Pulling from docker-hub/library/ubuntu
ea362f368469: Pull complete 
Digest: sha256:b5a61709a9a44284d88fb12e5c48db0409cfad5b69d4ff8224077c57302df9cf
Status: Downloaded newer image for registry-public/docker-hub/library/ubuntu:latest
registry-public/docker-hub/library/ubuntu:latest
```

**Versions:**

- harbor v2.3.1-1058f330
- docker engine version: 20.10.10
- docker-compose version: 1.29.2

**Comment by rgadeev** [comment]
there is such a problem. Need to use:
`docker pull registry-public/docker-hub/ubuntu/nginx:latest`

**Comment by rgadeev** [comment]
so
`docker pull registry-public/docker-hub/ubuntu/nginx:latest`
correct use of the command

adding "library" is a workaround for images with a short name in docker hub
`docker pull registry-public/docker-hub/library/ubuntu:latest`

**Comment by zyyw** [comment]
Hi @jansobczak , for example, when you create a `NEW PROJECT` as the type of proxy cache named as `proxy-cache-0117`, the proper command to pull images from the the proxy cache is: 
```
docker pull harbor-domain/proxy-cache-0117/image_name:image_tag
```

So in your case, the proxy cached is named as `docker-hub`, the image name is `ubuntu/nginx`, as @rgadeev suggested, the correct command should probably be: 
```
docker pull registry-public/docker-hub/ubuntu/nginx:latest
```

**Comment by jansobczak** [comment]
Ok, that's works, Thanks for clearing that up.
