### ISSUE TITLE
running harbor in a subfolder (static files path)

### ISSUE THREAD

**Issue by fabricfc** [goharbor/harbor#16231]
I have an Apache2 acting as reverse proxy for some applications over some hosts. 
These application are accessed through a domain, but referenced by a "subfolder" (using rewrite):
https://www.lab.some_institute.com/application1 - for application1
https://www.lab.some_institute.com/application2 - for application2

So I installed harbor in a k8s cluster and I'm trying to nest harbor in the same way:
https://www.lab.some_institute.com/registry - for harbor

However, I get "Loading..." but the scripts doesn't load because, I think, they are hard coded to the "/" of the domain. 
So, do you know if there is a way to change the path to find the "static" files (js, css, etc.) (ex: variable that I should set in values.yaml, on some part in the code)?

**Comment by fabricfc** [comment]
Do you think that changing this:
`<base href="/">` to `<base href="./">`  
inside of https://github.com/goharbor/harbor/blob/main/src/portal/src/index.html would tackle the issue?

**Comment by Vad1mo** [comment]
One note is that your frontend will be on `registry.example.org/harbor/` but not the api. So you have to use `registry.example.org` to pull push images.

**Comment by fabricfc** [comment]
> One note is that your frontend will be on `registry.example.org/harbor/` but not the api. So you have to use `registry.example.org` to pull push images.

Well observed. However, since it is running inside a k8s cluster (name/address resolution is internal) and API external access is consumed through the proxy, I don't thinks that could be a problem (conjecturing).

**Comment by fabricfc** [comment]
Got stuck changing the index.html (base ref tag). The files in the portal pod belong to root:root, not nginx (default "exec -it"  user). Tried to enter as root using containerd (microk8s.ctr) but no success to impersonate root.

**Comment by Vad1mo** [comment]
@fabricfc take a look at #16031
