### ISSUE TITLE
failed to check health of registry 1: login to dockerhub error

### ISSUE THREAD

**Issue by ehsansh84** [goharbor/harbor#16242]
Hi there, I've configured a docker hub proxy cache. When trying to pull images like:
```
docker pull habor.domain.com/docker/library/python
```
in logs of harbor-core an error says:
```
2022-01-18T08:19:47Z [ERROR] [/controller/registry/controller.go:233]: failed to check health of registry 1: login to dockerhub error: Post "https://hub.docker.com/v2/users/login/": dial tcp: lookup hub.docker.com: Temporary failure in name resolution
```
My registry status is `healthy` and when I edit the registry and hit `test connection`  this is the log for `nginx`:
```
196.240.57.221 - "POST /api/v2.0/registries/ping HTTP/1.1" 500 66 "https://harbor.domain.com:4443/harbor/registries" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" 10.011 10.012 .
127.0.0.1 - "GET / HTTP/1.1" 308 171 "-" "curl/7.78.0" 0.000 - .
```
While harbor can not connect to docker hub `docker pull python` works successfully on the server.
What could be wrong?

**Comment by stonezdj** [comment]
refer https://github.com/goharbor/harbor/issues/13718#issuecomment-744179993
