### ISSUE TITLE
Retry on Harbor registry push image failures

### ISSUE THREAD

**Issue by yanbinren** [goharbor/harbor#16249]
What can we help you?
Hi Harbor community, we recently experienced a similar issue to this: https://github.com/goharbor/harbor/issues/15982. 

Symptom:
Pushing a specific image to harbor failed deterministically for ~3 hrs.  Error message:
```
status code: 500, request id: VXTS9BNHFG527G8Q, host id: REDACTED=" err.message="unknown error" go.version=go1.15.6 http.request.host=REDACTED http.request.id=requestId http.request.method=PUT http.request.remoteaddr=x.x.x.x http.request.uri="/v2/path/blobs/uploads/blob/digest" http.request.useragent="//containerregistry/client:fast_pusher_.py" http.response.contenttype="application/json; charset=utf-8" http.response.duration=19.266519358s http.response.status=500 http.response.written=123 vars.name="repo" 

time="2022-01-17T23:25:31.061101365Z" level=error msg="unknown error completing upload: s3aws: InternalError: We encountered an internal error. Please try again.
```

After restarting the registry pods, the error went away (not sure if it helped to mitigate the issue though).

After some digging around, it looks like this is error caused by underlying s3 service: https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/

One of the suggested solutions is `Enable a retry mechanism in the application making requests`. I took a quick look at the source code and seems we don't currently retry on registry HTTP failures. Is there a design rationale behind this? (e.g. expecting client to retry)

Do you have any recommended approach to mitigate such issues? Thanks in advance!

**Comment by MinerYang** [comment]
Docker cli includes retry  mechanism already. You may check your cli itself.

**Comment by stonezdj** [comment]
When pushing images with the docker client, the most efficient way to do it by redirecting, which means that the harbor registry will redirect the docker client's POST request to the s3 storage. it means that the 500 error is unknown to the Harbor registry. so that there is no way for Harbor to retry.
It is better to improve the stability of the backend s3 storage service or reduce the size of the image layer(blob size).

**Comment by yanbinren** [comment]
Thanks for the feedback! @stonezdj @MinerYang Appreciate it!
