### ISSUE TITLE
Update harbor with more inclusive language

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#16248]
**Is your feature request related to a problem? Please describe.**
We should make sure that all harbor features are using inclusive language.

**Describe the solution you'd like**
We should replace "disable" within Harbor with something like "deactivate". So, for example, the enable/disable option on the robot accounts page should become enable/deactivate. https://goharbor.io/docs/2.4.0/administration/robot-accounts/#edit-disable-or-delete-a-system-robot-account

This should be updated in all Habor features and tool tips. 

**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Comment by a-mccarthy** [comment]
@xaleeks Is it possible to prioritize this for the next release? thanks!


cc: @OrlinVasilev

**Comment by AllForNothing** [comment]
@a-mccarthy Can you help to list all the words that need to be modified, then I can raise a PR to commit the changes

**Comment by OrlinVasilev** [comment]
@AllForNothing - https://inclusivenaming.org/ that's the original initiative website!

**Comment by AllForNothing** [comment]
Just scanned Harbor with "Inclusive Terminology Service", the only thing that needs to be done is to replace "disable" with "deactivate".
<img width="650" alt="image" src="https://user-images.githubusercontent.com/30999793/158939660-4b565ebf-1bac-41c0-b98c-9ca90c5077bb.png">

**Comment by AllForNothing** [comment]
And this PR #16548 is for the Harbor UI, @wy65701436 the back-end error messages also needs to be modified accordingly
<img width="549" alt="image" src="https://user-images.githubusercontent.com/30999793/158940067-e18f910c-c65b-45ac-be1a-fa3fd96962c2.png">

**Comment by OrlinVasilev** [comment]
+1

**Comment by AllForNothing** [comment]
Back-end PR #16569

**Comment by AllForNothing** [comment]
Closing it, as it is fixed
