### ISSUE TITLE
How to clean up blobs folders

### ISSUE THREAD

**Issue by AlbertYangXY** [goharbor/harbor#16256]
After my service was upgraded from 1.9 to 2.4, there was a problem with the replication strategy, which caused many replication tasks to be in Inprogress state.I do psql `Update task set status='Stopped' where status='Running' or status='Pending'; update execution set status='Stopped' where status='Running'; ` and restart harbor ,solved, But blobs file is very big, I want to clean it, but I tried online, such as GC cleaning in the Harbor UI, can not clean it, I would like to ask what is a good way?

**Comment by wy65701436** [comment]
the blobs are orphan or adhere with subject manifest? 
For the orphan ones, you can just run GC, and for the blobs that belongs to one artifact, you have to remove all the artifacts that references the blob, then wait for tow hours(the default time window) and run GC.

**Comment by kingnarmer** [comment]
I am having same issue . How to clean up space ? GUI report 150GB , registry mount /storage is using 450GB. I don't have the luxury to delete all images to clean up ? . I lowered retention policy from 7 days to 5 days and gain was 10GB.
