### ISSUE TITLE
speed up image scanning

### ISSUE THREAD

**Issue by phin1x** [goharbor/harbor#16264]
Hi,

We have about 22,000 images in our production port instance that we check daily for new cves. The full scan takes up to six or more hours.
Is there any way to speed up the scanning process? Our server would be able to scan multiple images in parallel. Would it help to increase the number of workers in the job service?

**Comment by MinerYang** [comment]
We've already supported parallel scanning. You can increase workers number in job-service configuration and restart Harbor. 

For example, if you are using offline-installer, modify the `max_job_workers` in your yml file. More detailes in [Configure the Harbor YML File](https://goharbor.io/docs/2.4.0/install-config/configure-yml-file/).

>  jobservice:  
  \#Maximum number of job workers in job service  
  max_job_workers: 10
