### ISSUE TITLE
Some empty keys in the redis-0 library

### ISSUE THREAD

**Issue by DHmc133** [goharbor/harbor#16266]
We found that the harbor-core service will continue to generate some empty keys in the redis-0 library. And if other code calls the harbor interface, it will also generate some empty keys. What is the purpose of these empty keys? 
![image](https://user-images.githubusercontent.com/98294423/150712087-b9722453-66ca-4240-b3b1-f0e7d18f522a.png)

**Comment by chlins** [comment]
These keys look like `beego` sessions.

**Comment by DHmc133** [comment]
> These keys look like `beego` sessions.

The value of some keys is user information, but there are a large number of keys whose value is empty. The keys with these empty values don't seem to have any effect

**Comment by chlins** [comment]
The empty value of some keys maybe from `beego` mechanism, i'm not very sure, but these keys will be deleted automatically once TTL reached.

**Comment by DHmc133** [comment]
> The empty value of some keys maybe from `beego` mechanism, i'm not very sure, but these keys will be deleted automatically once TTL reached.

The empty value of some keys indeed  from  `beego`  mechanism。
Is it not necessary to store these empty keys in redis? 
Maybe  can add judgment to only store non-empty keys in Redis
![image](https://user-images.githubusercontent.com/98294423/150757678-fecf824b-f102-4a84-9ca0-542f17f4f28c.png)

We pushed a lot of images for a short time, causing over 1.8 million null keys to be stored in the redis-0 repository, which is causing redis errors。

**Comment by chlins** [comment]
Yes, i think no necessary to store empty keys,  and you could open issue in `beego` repository.

**Comment by chlins** [comment]
Depend on upstream issue: https://github.com/beego/beego/issues/4851
