### ISSUE TITLE
Docker Login Issues

### ISSUE THREAD

**Issue by donzee529** [goharbor/harbor#16274]
After running the installation script, it says run `docker login -u admin -p Harbor12345 registry.pyrohost.cloud`
(I replaced URL with my URL)
It returns with
Error response from daemon: Get "http://registry.pyrohost.cloud/v2/": dial tcp 127.0.1.1:80: connect: connection refused

**Comment by zyyw** [comment]
Hi @donzee529 which version of Harbor you are using?

BTW, do you have a chance to install and configure Harbor with HTTPS, reference: https://goharbor.io/docs/2.2.0/install-config/configure-https/
Not sure whether harbor support http access or not (Didn't get a chance to try HTTP yet).

**Comment by Gainutdinov** [comment]
I face the similar issue,
periodically, started to face 401 and only after restarting docker-compose harbor lets me log in.

Is there something to check from my side?
