### ISSUE TITLE
Add CreateRepository API

### ISSUE THREAD

**Issue by Abhidipto** [goharbor/harbor#16276]
**Is your feature request related to a problem? Please describe.**
Add an API to create a repository

**Describe the solution you'd like**
Are you open to this API being added? I'm more than happy to perform the work if so.

**Comment by wy65701436** [comment]
the repo will be created when user first time to push artifact into that repository, can you explain why this API is needed?

**Comment by Abhidipto** [comment]
Actually, for my requirements, it'd be nice to have the flexibility to have the option of creating a repository without having to push an artifact immediately, and also, adding this api would not only complete the CRUD api set for harbor repositories, but also would make it more compatible with aws ecr and thus can be used more interchangeably with aws ecr
