### ISSUE TITLE
with metric: enabled: true harbor reboot continuously

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor#16275]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
with metric enable harbor reboot continuosly

**Steps to reproduce the problem:**
check logs 
harbor up and running but harbor down only.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.1 and 2.4.0
- docker engine version: 17.12.1-ce
- docker-compose version: 17.12.1-ce

**Additional context:**

metric: enabled: true

**Comment by chlins** [comment]
Could you please provide more info,  which pod reboot and any logs of it?

**Comment by jorgemansillacriado** [comment]
Hi 
we're using docker containers

all containers are restarted at the same time

I don't see any relevant logs

**Comment by jorgemansillacriado** [comment]
solved

problem was one monitoring script our
