### ISSUE TITLE
Project Quota not being applied when project is created via API

### ISSUE THREAD

**Issue by R-Lam** [goharbor/harbor#16278]
**Expected behavior and actual behavior:**
Created project with quota applied when parameter `storage_limit` value is different from 0 or -1. Instead, the project is created and default quota is applied (unlimited in new instances).

**Steps to reproduce the problem:**
Create a project via API like the following:
```
curl -X POST https://${registry}/api/v2.0/projects -H "accept: application/json" -H "X-Resource-Name-In-Location: false" -H "authorization: Basic ${token}" -H "Content-Type: application/json" -d "{ \"project_name\": \"test\", \"public\": true, \"storage_limit\": 1073741824}"
```

**Versions:**

- harbor version: [v2.3.4-7a068b12]

**Comment by wy65701436** [comment]
Verified at Harbor v2.4.1, cannot reproduce it. cc @YangJiao0817 can you try with that on v2.3.4?

**Comment by YangJiao0817** [comment]
@wy65701436 I can't reproduce this issue with v2.3.4-7a068b12.
`test` is the project created with API
<img width="1137" alt="WechatIMG80" src="https://user-images.githubusercontent.com/72076317/151095652-bf613551-b335-446b-85e0-8332a7f415a4.png">
```
# docker push 10.202.250.222/test/goharbor/harbor-e2e-engine:latest-api
The push refers to repository [10.202.250.222/test/goharbor/harbor-e2e-engine]
3862eb8c62b0: Pushed 
dc7d686f8ac2: Pushed 
b8bc5bfc25d1: Layer already exists 
2ff2e52d7400: Pushed 
0de832629f45: Pushing [==================================================>]  229.6MB
4117c719d7b3: Pushing [==============>                                    ]  257.2MB/875.4MB
86df02cfa80a: Pushed 
98572c4cd588: Pushed 
denied: adding 66.2 MiB of storage resource, which when updated to current usage of 968.3 MiB will exceed the configured upper limit of 1.0 GiB.
```

**Comment by R-Lam** [comment]
Interesting.

Tested on newer version 
- Version v2.4.1-c4b06d79

The same result: no quota being applied.

Am I missing something on my call?
```
curl -k https://${REGISTRY}/api/v2.0/projects -H "content-type: application/json" -H "authorization: Basic ${TOKEN}" -H "accept: application/json" -d '{"project_name": "test", "storage_limit": 1073741824}'
```

**Comment by YangJiao0817** [comment]
@R-Lam You can try using the example below.
```
curl -k -X 'POST' https://${REGISTRY}/api/v2.0/projects -H "content-type: application/json" -H "authorization: Basic ${TOKEN}" -H "accept: application/json" -d '{"project_name": "test", "storage_limit": 1073741824}'
```

**Comment by R-Lam** [comment]
Thanks!

Working, for our CI system we use jq to process that json with variables first before making the request.

**Comment by agaillar** [comment]
Hi, 

i reproduced this error in 2.5.1. 
From portal, it's OK ( project created with quota (record in public.quota and public.quota_usage)
From API, it's KO ( project created without quota (no record in public.quota and public.quota_usage)
