### ISSUE TITLE
Deadlock: Can't delete or create Retention Policies

### ISSUE THREAD

**Issue by leppez** [goharbor/harbor#16288]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: I would expect the API to allow me to create and/or delete the existing retention policies. 
Actual Behavior: Harbor retention policy in only one project is in a state where I can't retrieve or delete the retention policy since its ID doesn't not exist or create a new retention policy since there's already one created.

**Steps to reproduce the problem:**
With the v2.0 API, and using the UI the endpoint GET /retentions/4/executions/ returns an `Internal Server Error` with message `no such Retention policy with id 4`. The same error is returned when using the DELETE /retentions/id endpoint. 

The POST /retentions endpoint I get an error with message `bad request: project 10 already has retention policy 4`. It seems as though I can't retrieve or delete the current retention policy or create a new one altogether. 

Is there a way to get out of this deadlock with the retention policy?

I'm unsure as to how exactly this one project got to this state, so I'm not sure if you're able to replicate.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.2]

**Additional context:**
Running on Kubernetes using the Helm chart

**Comment by leppez** [comment]
Any ideas of how I can get out this issue?

**Comment by leppez** [comment]
To further clarify, We are able to successfully do a PUT to `/retentions/4/` but GET, DELETE and POST are failing.

**Comment by MinerYang** [comment]
Can you conduct it on  the UI instead?

**Comment by Shashankft9** [comment]
Stuck in the similar issue with harbor v2.5 - I created the policy using API, then deleted it, and now stuck in the deadlock as mentioned in the issue. 
@leppez were you able to figure out some solution to this?

**Comment by zyyw** [comment]
@leppez , @Shashankft9 it seem that I can't reproduce the scenario you guys encountered. Could you please share some details how to reproduce this?

**Comment by zyyw** [comment]
reproduced by call delete api, for example:
```
DELETE harbor-ip/api/v2.0/retentions/retention_id
```
And see the `Internal Server Error` on the UI and `bad request: project 7 already has retention policy 6` when call POST api.
I resolved this issues by executing the following sql
```
delete from project_metadata where project_id=7 and name='retention_id' and value='6';
```
please make sure to back-up your data and replace `project_id (7)` and the value of retention_id (6) with your the value in your env.
