### ISSUE TITLE
chartmusuem replace by charthall

### ISSUE THREAD

**Issue by rafal-prasal** [goharbor/harbor#16287]
What can we help you?

Recently I started a project called charthall [charthall](https://github.com/rafal-prasal/charthall), which uses the same API as chartmuseum, but with limitation that only filename is a source of truth. 

it does not support any fancy stuff(only storage=local and depth=1), but thanks to that it can be easily incorporated into harbor deployment in ex. docker-compose.

it is still not battle tested, but it should be good enough.

**Comment by Vad1mo** [comment]
interesting, can it work as a drop in replacement for chartmuseum?

Situation is that Chartmuseum is deprecated in Harbor. So only critical fixes are added but no new features. The way to go is OCI. see the ongoing discussion ->  https://github.com/goharbor/harbor/discussions/15057

**Comment by rafal-prasal** [comment]
to some extent yes. if you are using STORAGE=Local and only one replica then yes.

**Comment by zyyw** [comment]
As Vad1mo mentioned, harbor is going to deprecate Chartmuseum and embrace OCI helm, instead of replacing chartmuseum with a customized charthall. 

Closing it for now.
