### ISSUE TITLE
API additions/vulnerabilities not working

### ISSUE THREAD

**Issue by lucasbaccan** [goharbor/harbor#16295]
Hi everybody, i need some help with the Harbor API.

Something it's not working very well, because the Harbor web interface show one information and the API does not.

But for some projets, everything it is OK.

This request does not work, but the status code it is 200 and the body is empty.
`https://harbor-dev.XXXXXX.com/api/v2.0/projects/core-team/repositories/ndf/artifacts/sha256:c24152b600f2e2d59d4b313c1e6e6935d8a9d18705f91259be0a396e485e1c01/additions/vulnerabilities (11.0.3)
`

This request work, the status code it is 200 and the body show a JSON with the vulnerabilitys
`https://harbor-dev.XXXXXX.com/api/v2.0/projects/core-team/repositories/ndf/artifacts/sha256:b2f8d27c70cd723495a6730a8f1662430f19831f4f3a5922bd650d50fe9e4ab1/additions/vulnerabilities (11.0.2)
`
All the images have vulnerability by Trivy

I'm using harbor on version v2.4.0-d4affc2e

The log don't show anything, no errors, i don't know what to do.

Thanks

![image](https://user-images.githubusercontent.com/2676484/151200774-588fc14b-be12-477a-bea4-ede796480155.png)

**Comment by heww** [comment]
There is a [header](https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L1400) for the vulnerabilities addition API,  the API will find the scan report

**Comment by lucasbaccan** [comment]
> Please upgrade the harbor to v2.4.1, we fixed this issue #16085
> 
> If you don't want to upgrade the harbor instance, please set this [header](https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L1400) with scan report v1.1 and v1.0 in your vulnerabilities addition API request.

Thanks for your reply, i will open a internal ticket to update the version. But the new header worked :smile:
