### ISSUE TITLE
Trivy Performance Issue 

### ISSUE THREAD

**Issue by creeea** [goharbor/harbor#16293]
I upgraded Harbor from 2.1.5 to 2.4.1. We have a lot of images (around 15k) to scan and it takes almost 20h. Especially these SQL queries take very long:
`select id from task where extra_attrs->>$1 = $2;`
We use an external Postgres database (v12)

Does it makes sense to create an index like this?
`CREATE INDEX ON idx_extra_attrs((extra_attrs->>'name'));`

**Comment by MinerYang** [comment]
You might have a try and share the follow-up result with the community, thx .
