### ISSUE TITLE
Question on Throughput for Pulling

### ISSUE THREAD

**Issue by herter4171** [goharbor/harbor#16291]
Before I started at my current employer in late 2018, a contractor set up a Harbor registry for us with a single `t2.medium` instance and images saved to S3.  This has worked with virtually no fuss since then, so with those images no longer maintained, we haven't bothered to update and are currently at VMware Harbor v1.5.1.  Obviously, we are very far behind and need to catch up, so I have been testing out GoHarbor v2.3.2 with a single `c5n.xlarge` instance in the hopes of better network performance and images saved to S3 like our current deployment.  Also, for now, SSL is not in place on our new GoHarbor deployment, so in case that has any bearing, it's an insecure registry.

My question pertains to throughput for pulling.  As shown in the plot below, I have benchmarked pulling a few representative images from the two Harbor deployments and also Docker Hub, and we get noticeably less throughput from GoHarbor than Docker Hub and especially compared to our old VMware Harbor deployment.  I believe this is largely due to GoHarbor hanging for 5-10 seconds before pulling actually commences, which is a lot more noticeable for smaller images, and this behavior appears to be unique to the GoHarbor implementation.

**Main question:** Is there a known cause for GoHarbor having less throughput than old-school VMware Harbor, and if so, is there anything I can do to boost throughput for the GoHarbor deployment?  I'm a bit hesitant to venture down the Kubernetes rabbit hole, but if multi-instance is known to significantly improve throughput, I suppose I'm open to it.

![image](https://user-images.githubusercontent.com/21989132/151096519-b91d0874-1c50-4af6-807f-e1551739a2b3.png)

**Comment by chlins** [comment]
@herter4171 Which tool did you use, we have tested goharbor/harbor performance by `k6` and you can find more details and test report  for recently version. ref: https://github.com/goharbor/perf/wiki

**Comment by chlins** [comment]
Additionally, does the `GoHarbor` and `VMware Harbor` with the same deploy and hardware resources?

**Comment by herter4171** [comment]
I just did `time docker pull` on a separate EC2 instance in a different VPC from the Harbor deployments.  I like that there are metrics for performance and will look into that.  For us, though, the big-ticket item is pull throughput on a production instance, and it's odd that only `GoHarbor` exhibits that 5-10 second hang with `docker pull` before visibly pulling down layers.  Since it's the same filesystem for each pull, I see no reason to doubt the time for extracting layers is consistent, making the data points representative.

Regarding hardware, both are single instance.  Additionally,
* `VMware Harbor` is on a `t2.medium`, so 2 cores and 4 GB RAM
* Per the hardware recommendations, `GoHarbor` is on a `c5n.xlarge`, so 4 cores and 10.5 GB RAM

I had hoped the `c5n.xlarge` choice for `GoHarbor` would provide a boost, since it advertises "up to 25 Gbps."  Unfortunately, it did not.  The only other thing I can think of is that perhaps with our `GoHarbor` currently being an insecure registry, maybe the initial lag before pulling layers is an SSL handshake timing out?  That said, Docker knows it's an insecure registry, so I'm not sure why Docker would try SSL first.

**Comment by herter4171** [comment]
@chlins, I added SSL to my `GoHarbor` test deployment.  The 5-10 second hang before pulling layers went away, and the throughput matches `VMware Harbor` exactly.  I am closing the issue, because I'm happy with how Harbor is performing.  If someone wants to reopen the issue to explore performance for insecure registries, I won't be offended, though.  Thanks for the engagement.
