### ISSUE TITLE
version of v1.10.10 Latest don't work script Installation with Trivy

### ISSUE THREAD

**Issue by losadacris71** [goharbor/harbor#16308]
when I use Installation with Trivy
<img width="776" alt="trivy problem" src="https://user-images.githubusercontent.com/98327412/151391929-10ba3df4-1fcb-49c3-8292-573e4c117005.png">
don't work 
version of  v1.10.10 Latest
harbor-offline-installer-v1.10.10.tgz 
I run with docker version 20.10.12
and docker-compose version  1.29.2 , build 5becea4c

**Comment by wy65701436** [comment]
v1.10.10 doesn't support trivy, please try with v2.4.1.
