### ISSUE TITLE
Tag Retention Policy with all projects

### ISSUE THREAD

**Issue by Hexcah** [goharbor/harbor#16318]
Hi,

I would like to create a tag retention rule for all projects, actually I have 2 rules for some projects but I did it manually.

- For the repositories matching **, retain the most recently pushed 5 artifacts with tags excluding v* with untagged
- For the repositories matching **, retain the most recently pushed 10 artifacts with tags matching v* with untagged

But I want this for all project or an automatic deployment of the rules for new projects.

I read the doc and saw the API swagger but I'm still stuck on this parameters, has anyone managed to do this?

The version of Harbor is not a problem but currently I am in 2.0.2

Thank you ^^

**Comment by MinerYang** [comment]
We only support project-level retention currently, not system-level.
