### ISSUE TITLE
Errors in core.log after upgrade to 2.4.1

### ISSUE THREAD

**Issue by kuznetsovkk** [goharbor/harbor#16319]
After upgrade harbor 2.3.2 to 2.4.1 I have this error messages in core.log:

```
Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/config.go:70]: Register called twice for manager db_cfg_manager
Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:143]: GetStringToStringMap failed, current value's metadata is not defined, &{Name: Value:}
Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:126]: GetBool failed, the current value's metadata is not defined, &{Name: Value:}
Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:126]: GetBool failed, the current value's metadata is not defined, &{Name: Value:}
Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:78]: GetInt failed, the current value's metadata is not defined, &{Name: Value:}
```

Is it normal?

**Comment by stonezdj** [comment]
It is noise in logs, we are going to remove it.

**Comment by QiuToo** [comment]
> 将 Harbor 2.3.2 升级到 2.4.1 后，我在 core.log 中有以下错误消息：
> 
> ```
> Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/config.go:70]: Register called twice for manager db_cfg_manager
> Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:143]: GetStringToStringMap failed, current value's metadata is not defined, &{Name: Value:}
> Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:126]: GetBool failed, the current value's metadata is not defined, &{Name: Value:}
> Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:126]: GetBool failed, the current value's metadata is not defined, &{Name: Value:}
> Jan 31 13:21:59 172.25.0.1 core[2002]: 2022-01-31T10:21:59Z [ERROR] [/lib/config/metadata/value.go:78]: GetInt failed, the current value's metadata is not defined, &{Name: Value:}
> ```
> 
> 正常吗？

I have the same problem, but I don't know how to fix it
