### ISSUE TITLE
pypi goharbor package official?

### ISSUE THREAD

**Issue by shoeffner** [goharbor/harbor#16327]
Is this package: https://pypi.org/project/goharbor officially related to goharbor? 
It only offers two wheel files and I didn't find how this project actually creates and publishes them, though it is linked as the pypi project's homepage.
The last release was in 2019.

**Comment by wy65701436** [comment]
No, it's not. @heww can you give more details? We can remove it if it's not maintained by goharbor?

**Comment by heww** [comment]
> Is this package: https://pypi.org/project/goharbor officially related to goharbor?

No, this is not an officially related package. 

I have deleted this project in PyPI.
