### ISSUE TITLE
Verify Harbor translations

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#16321]
**Describe the solution you'd like**

We have a lot of community contributor translations for the Habror portal, https://github.com/goharbor/harbor/tree/main/src/portal/src/i18n/lang. We should go through each translations and make sure that they are correct and updated for the most recent version of Harbor. 

**Describe the main design/architecture of your solution**

We should reach out to the Harbor community to see of folks are able to validate the current translation files. 

Checklist of languages to validate:

- [x] EN (default language. this is validated by the Harbor maintainers for every release) -https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/en-us-lang.json 
- [x] ZH-CN (this is validated by the Harbor maintainers for every release) -https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/zh-cn-lang.json
- [x]  FR - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/fr-fr-lang.json
- [ ] ES - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/es-es-lang.json
- [ ] TR - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/tr-tr-lang.json
- [x] DE - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/de-de-lang.json 
- [ ] PT-BR - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/pt-br-lang.json
- [ ] ZH-TW - https://github.com/goharbor/harbor/blob/main/src/portal/src/i18n/lang/zh-tw-lang.json

Ask to community:
If you are fluent in any of the above languages, please review the file for your language and verify that the content is correct or open a PR with any changes. 

Related links
* https://goharbor.io/docs/2.4.0/build-customize-contribute/developer-guide-i18n/

**Comment by a-mccarthy** [comment]
It looks like the files for the translations have been update with the current UI fields as they were added to the Harbor portal UI. They were added in English, mixed in with the previously translated fields. 

More info on how translations within the harbor portal ui work can be found here: https://goharbor.io/docs/2.4.0/build-customize-contribute/developer-guide-i18n/

**Comment by a-mccarthy** [comment]
@Vad1mo Here's the issue for validating the Harbor interface localizations. Thanks for offering to help with German. Please tag anyone else you thinking might be willing to help :)

**Comment by sluetze** [comment]
Sure, will reach out on slack tomorrow.

**Comment by a-mccarthy** [comment]
thank you @sluetze and @Vad1mo for working on this! 

Do you have any ideas or suggestions on how we can track wording changes that will need to be translated going forward?

**Comment by Vad1mo** [comment]
>track wording changes

This is not clear to me, can you elaborate about the goal?

 Normally we look at all the text snippets that are not translated and translate them.

**Comment by a-mccarthy** [comment]
@Vad1mo I'm just wondering if its possible to keep track of updates to the interface that would need to be translated. For example, if there is a PR that updates the interface text, then we should make an issue to track that translation work is needed? Or, should we just do a check around release time to see if anything has been updated and translate it then?

I'm trying to think about translation needs going forward to see if we can make this process easier for folks to know when we need help, and I was interested to see if y'all had any ideas  :)

**Comment by Vad1mo** [comment]
- So we rarely change existing text, it is mostly only added.
- When Devs add a text, they copy & paste it to all language files in English.
- When we look at the language file, we look at the changes between the releases.  

So I would say that for the moment it is enough to ping all the translation responsible people before the release and ask them to take a look and update the lang file.

**Comment by sluetze** [comment]
alternative would be to ping the people when changes are made to the file and make language-specific changes directly. But this would slow down the developers (since they would be dependent on translators) and would result in duplicate work as translator, since sometimes there is more than one language-change in a release. So this is a bad idea. a ping a few days/weeks before code-freeze should be sufficient.

**Comment by a-mccarthy** [comment]
ok, thanks for the feedback @Vad1mo and @sluetze! we'll stick with checking for updates around release time  🚀

**Comment by Vad1mo** [comment]
@a-mccarthy, there is https://github.com/goharbor/harbor/pull/16524 open for FR translation. According to google translate and my minimal French the translation seems reasonable and definitely better than the status quo

**Comment by a-mccarthy** [comment]
The french translation was updated in this PR: https://github.com/goharbor/harbor/pull/16570 🚀

**Comment by AllForNothing** [comment]
Keep it open so that the community can continue to contribute
