### ISSUE TITLE
Project's summary is incorrect 

### ISSUE THREAD

**Issue by Katatafjsh** [goharbor/harbor#16323]
**Expected behavior and actual behavior:**
- Expected: The summary tab on a project is not updated when a user is deleted via Administration>Users
- Actual: Members summary is unchanged

**Steps to reproduce the problem:**
- Add a user to a project with desired role
- Delete user via Administration>Users
- Check project's summary

**Versions:**
- harbor version: 1.10.10-322972dc
- docker engine version: 20.10.12
- docker-compose version:  2.1.1

**Comment by wy65701436** [comment]
hi, please upgrade to latest version(v2.4.*), and 1.10 is out of support.

**Comment by Katatafjsh** [comment]
Thank you. I got fooled because the latest tag is pointing to 1.10.10.
![image](https://user-images.githubusercontent.com/79232936/152755841-d94b4003-b7ca-40e3-aade-98d1b8bb4e69.png)
