### ISSUE TITLE
Can list a repository but cannot get or delete it

### ISSUE THREAD

**Issue by gregopenit** [goharbor/harbor#16320]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I have 2 problematic repositories "rhinelevel" and "rhine_level" from a project "digital" which cannot be accessed nor deleted. From the UI, the repositories are listed but when accessing them, the message "repository digital/rhine_level not found" is displayed.

I can push an artifact in them and delete it. But I am not able to delete these repositories themselves, not get information from them such as vulnerabilities.

**Steps to reproduce the problem:**
I can list the two buggy repositories:

```
$ curl -u gmahe -X GET "https://harbor.dts.corp.local/api/v2.0/projects/digital/repositories?sort=name&page=15&page_size=10" -H "accept: application/json" -H "x-harbor-csrf-token: XXX"  --basic
Enter host password for user 'gmahe':
[
{"artifact_count":0,"creation_time":"2019-09-27T10:08:18.361Z","id":117,"name":"digital/rhine_level","project_id":8,"pull_count":1217,"update_time":"2022-01-16T20:22:48.255Z"},
{"artifact_count":0,"creation_time":"2019-05-01T08:43:24.059Z","id":71,"name":"digital/rhinelevel","project_id":8,"pull_count":3195,"update_time":"2022-01-30T20:20:17.803Z"},
(...)
```

But I can't get them:

$ curl -u gmahe -X GET "https://harbor.dts.corp.local/api/v2.0/projects/digital/repositories/rhine_level" -H "accept: application/json" -H "x-harbor-csrf-token: XXX"  --basic
Enter host password for user 'gmahe':
{"errors":[{"code":"NOT_FOUND","message":"repository digital/rhine_level not found"}]}

I didn't find anything similar in the current and past issues. Does anyone know a way to clean what looks like a corruption ?
I found nothing which could explain how these 2 repositories could have been corrupted but they had artifacts with >200 vulnerabilities scanned by trivy every week. And except Trivy, there were no change (artifact push) on these repositories for months.

Thanks for your help.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.3.1-1058f330
- docker engine version: 20.10.7
- docker-compose version: 1.29.2

**Comment by rgadeev** [comment]
I had a similar one, I did pull, deleted it in harbor and push. Two repositories with the same name appeared, the first working, the second duplicates the first. I think it's an interface error.

**Comment by gregopenit** [comment]
Thanks a lot @stonezdj . It was indeed a non-printable character. You really helped me.

```
registry=# select * from repository where name='digital/rhine_level';
 repository_id | name | project_id | description | pull_count | star_count | creation_time | update_time
---------------+------+------------+-------------+------------+------------+---------------+-------------
(0 rows)

registry=# select * from repository where name LIKE 'digital/rhine_level%';
 repository_id |        name         | project_id | description | pull_count | star_count |      creation_time       |        update_time
---------------+---------------------+------------+-------------+------------+------------+--------------------------+----------------------------
           117 | digital/rhine_level |          8 |             |       1217 |          0 | 2019-09-27 10:08:18.3616 | 2022-01-16 20:22:48.255551
(1 row)
```

Your 2 updates have corrected the name now.

**Comment by gregopenit** [comment]
Just a complement, the two UPDATE statements didn't fix the non-printable character. I had to rename first to a random value:

```
registry=# update repository set name='digital/rhine_level' where repository_id=117;
UPDATE 1

registry=# select * from repository where name='digital/rhine_level';
 repository_id | name | project_id | description | pull_count | star_count | creation_time | update_time
---------------+------+------------+-------------+------------+------------+---------------+-------------
(0 rows)

registry=# update repository set name='digital/rhine_levelTEMP' where repository_id=117;
UPDATE 1
registry=# update repository set name='digital/rhine_level' where repository_id=117;
UPDATE 1

registry=# select * from repository where name='digital/rhine_level';
 repository_id |        name         | project_id | description | pull_count | star_count |      creation_time       |        update_time
---------------+---------------------+------------+-------------+------------+------------+--------------------------+---------------------------
           117 | digital/rhine_level |          8 |             |       1217 |          0 | 2019-09-27 10:08:18.3616 | 2022-02-08 14:17:29.01582
(1 row)
```
