### ISSUE TITLE
Failed to upgade Harbor v2.1.0 instance to v2.4.1 or v2.2.2

### ISSUE THREAD

**Issue by polskomleko** [goharbor/harbor#16329]
Hello.
We've got two standalone (docker-compose) instances of Harbor with local DB deployment running:

### Main instance
**Harbor version:** v2.1.0
**OS:** CentOS 7.8.2003
**Docker version:** 19.03.12

Used as primary host for images, registries, users, robot accounts etc.

### Secondary instance
**Harbor version:** v2.2.2
**OS:** CentOS 7.8.2003
**Docker version:** 19.03.12

Used as a kind of backup registry for images by pulling images from main instance. We don't really have any users here other than harbor admins and no replications, tag retention rules etc.

We're currently trying to move it to a better architecture with an external PGSQL cluster and at least two instances behind a load balancer (even though we're not using k8s or ocp deployment architecture for this as we want Harbor as a standalone VMs).

As a first step, we've tried to update our instances to a current version (v2.4.1 as of now).

Following upgrade guide from docs (https://goharbor.io/docs/2.4.0/administration/upgrade/), first we've tested the upgrade on a fresh v2.1.0 installation which we populated a bit for purpose of testing and succefully upgraded v2.1.0 -> v2.4.1 without any issues.

Then we've moved on to our secondary instance and again, no problems upgrading v2.2.2 -> v2.4.1. 

But during primary instance upgrade from v2.1.0 -> v2.4.1 we've encountered following problems: everything came up healthy, except harbor-core, which after a long start up became unhealthy, and harbor-jobservice, which was "starting" infinitely. 

Excerpt from core.log and postgresql.log 
[core.log](https://github.com/goharbor/harbor/files/8004296/core.log)
[postgresql.log](https://github.com/goharbor/harbor/files/8004331/postgresql.log)

Harbor-core didn't produce any logs after it got stuck on running the 2.2.0 schema migration SQL script before we've tried to docker-compose restart all of the containers after about 15 to 20 minutes of waiting. Obviously, it didn't help, as harbor-core kept restarting because schema migration didn't complete properly and the schema was stuck in dirty state, harbor-core was looping trying to upgrade a dirty schema.

We've rolled back from the update succefully and figured that it might be helpful to do a granual update like v2.1.0 -> v2.2.2 -> v2.4.1, even though documentation doesn't suggest that you should upgrade gradually if you have 2.x.x. And - same issue, it got stuck on "Read and execute 50/u 2.2.0_schema" and harbor-core container went to unhealthy status So, we've decided to roll back and to collect logs to ask your opinion on the issue and maybe get some help.

So, anyone can help us with the problem? Might it be that we haven't waited for long enough for the database upgrade? The local database is 11G, could it have been way too large for migrator script?
Maybe someone could suggest a working upgrade roadmap (upgrading to every minor version or something)? I would appreciate any help or suggestions here, thanks.

**Comment by wy65701436** [comment]
how many records of table task & execution in your 2.1 harbor? cc @ywk253100

**Comment by polskomleko** [comment]
There are 3 records per table.

**Comment by polskomleko** [comment]
If it would provide any addition information, I've uploaded those records here.
[table records.txt](https://github.com/goharbor/harbor/files/8022264/table.records.txt)

**Comment by polskomleko** [comment]
By the way, I've noticed that our pull-based scheduled replications has stopped working since we've rolled back from the failed update. It doesn't schedule new jobs, they work only if triggered manually. Shoud I open another issue or bug report?

**Comment by polskomleko** [comment]
An update on the issue.
I took a pg_dumpall on 2.1.0 DB and restored it in our test enviroment and tried an update once again.
It seems like the update was a success, it just took 1 hour 36 minutes for 2.2.0 schema migration script to execute:
Feb 10 18:27:14 [192.168.224.1](https://192.168.224.1/) core[108942]: 2022-02-10T15:27:14Z [INFO] [/vendor/[github.com/golang-migrate/migrate/v4/migrate.go:763](https://github.com/golang-migrate/migrate/v4/migrate.go:763)]: Finished 50/u 2.2.0_schema (read 10.808613ms, ran 1h36m56.235166095s
I'll test the update once more to check if everything works fine after the update.
