### ISSUE TITLE
Allow garbage collection of untagged artifacts

### ISSUE THREAD

**Issue by robbrucks** [goharbor/harbor#16326]
Garbage collection of untagged artifacts is actually DELETION of untagged artifacts.

**Expected behavior and actual behavior:**
Expected behavior would be that untagged artifacts **that have already been marked for deletion** by an external entity or process would be garbage-collected by the job. 

Actual behavior is that untagged artifacts **that have NOT been deleted** are both deleted and garbage-collected by the job.

**Steps to reproduce the problem:**
Upload an artifact that is not tagged.
Run the garbage collection with the "Allow garbage collection on untagged artifacts" option enabled.
Artifact is both deleted and garbage-collected.

**Versions:**
Harbor 2.2.1

- harbor version: 2.2.1
- docker engine version: 19.03.8
- docker-compose version: 1.25.3

**Additional context:**
Pictures of the UI in the docs do not match the verbiage for the option.
https://goharbor.io/docs/2.2.0/administration/garbage-collection/

The picture of the web UI in the docs shows "Allow garbage collection on untagged artifacts"
The doc wording says "To delete untagged artifacts, select the check box Delete Untagged Artifacts."

The docs are still not correct as of 2.4.

Solution:
The wording in the UI needs to be changed to "Delete untagged artifacts" if that is the intended action.

**Comment by zyyw** [comment]
The `Allow garbage collection on untagged artifacts` ACTUALLY both deletes the untagged artifacts and also does garbage collection on the untagged artifacts after deletion. I guess the `Allow garbage collection on untagged artifacts` implicitly expression the `delete untagged artifacts` behavior, but explicitly express the behavior of *allow garbage collection on the untagged artifacts*.

**Comment by flaviomoringa** [comment]
Also agree that the message needs to be A LOT more clearer. I was having some issues with cached images, selected this option, and it broke existing images from the proxy project I had :-( Not nice at all.

**Comment by AllForNothing** [comment]
@a-mccarthy I think the current wording `Allow garbage collection of untagged artifacts` is more suitable than `Delete untagged artifacts`, as @zyyw mentioned, `Allow garbage collection of untagged artifacts` contains both `deleted` and `garbage-collected`. So your updates in the doc are enough to avoid the confusion, and now we can close this issue

**Comment by ktzsolt** [comment]
> @a-mccarthy I think the current wording `Allow garbage collection of untagged artifacts` is more suitable than `Delete untagged artifacts`, as @zyyw mentioned, `Allow garbage collection of untagged artifacts` contains both `deleted` and `garbage-collected`. So your updates in the doc are enough to avoid the confusion, and now we can close this issue

If I understand garbage collection removes blobs from the storage that are deleted from the registry. So "garbage collection on untagged artifacts" should indeed not delete all untagged artifacts only those that are deleted prior.

Thus the correct wording on the UI would be: "Delete and garbage collect all untagged artifacts"
With this wording looking up documentation - that I also had to do - could be avoided. 

The docs correctly says:  https://goharbor.io/docs/2.12.0/administration/garbage-collection/
To Allow garbage collection on untagged artifacts, select the option. If you have this option turned on, the next time Garbage collect runs on your Harbor instance, Harbor **will delete untagged artifacts and then perform garbage collection** on them.
