### ISSUE TITLE
Support retry on failed replication jobs

### ISSUE THREAD

**Issue by yanbinren** [goharbor/harbor#16331]
What can we help you?
Similar to https://github.com/goharbor/harbor/issues/15150, Harbor replication job fails eventually after a few times of retries.

```
2021-08-16T05:49:01Z [ERROR] [/replication/transfer/image/transfer.go:181]: got error during the whole transfer period, mark the job failure
```

Does Harbor plan to support automatic job-level retries in the future releases? Or is there a way to expose all images that are failed to replicate in the job?

**Comment by chlins** [comment]
@yanbinren For image replication, there are two level retry mechanism, one is retry when copy blob fails which will retry 5 times and another is job level which will retry 3 times when job failed, and these options are all hard-coded, not expose to configure for user.

**Comment by rgadeev** [comment]
We have event-based replication configured. Will old changes be replicated when new ones occur if previous replications failed?

**Comment by chlins** [comment]
When a new event arrived, harbor will only create a new replication job and not handle the previous jobs.

**Comment by vinusorout** [comment]
What will happen, if we push an image to source repo, and during the event based replication the destination repo was down. Will the source harbor repo going to retry the replication to destination repo when the destination repo is up again?

**Comment by chlins** [comment]
> What will happen, if we push an image to source repo, and during the event based replication the destination repo was down. Will the source harbor repo going to retry the replication to destination repo when the destination repo is up again?

@vinusorout No, harbor will not monitor the dest registry health, in your case if the dest repo is done, the job will fail and retry 3 times in meanwhile and if your dest repo is up, you need to re-push image to source or replicate manually.

**Comment by yanbinren** [comment]
Hi @chlins, thanks for the explanation! I was wondering if there is any suggested way to reach eventual consistency for harbor replication? e.g. is there a way for users to discover failed jobs and retry?

**Comment by chlins** [comment]
@yanbinren There is a way to get notifications from harbor, that is `Webhook` what you could configure  webhook policy in the project and then check the subscribe event of `Replication finished`, and the payload which send to your webhook endpoint contains the replication task status.

**Comment by chlins** [comment]
> Why is there no ability to re-run a job? This seems relatively trivial to implement and would make eventual consistency between failover instances simple.
> 
> I am not sure why this issue was closed as there was no reason given why harbor _should not_ support this. [@chlins](https://github.com/chlins) what do you think?

@ianseyer Hi, as explained in the above comment, harbor has the mechanism for retry internally when errors occurred. FYI: https://github.com/goharbor/harbor/issues/16331#issuecomment-1030993216
