### ISSUE TITLE
Repository forbidden after upgrade from 2.2.2 to 2.3.0 or more

### ISSUE THREAD

**Issue by AntoineCourtil** [goharbor/harbor#16340]
Hello,

I'm facing an issue after Harbor update. I have standalone instance executed by docker-compose cmds.
I have same issue after an upgrade from v2.2.2 to v2.3.0, v2.3.5 or v2.4.1

___

### Details:
- Harbor version: v2.2.2
- OS: CentOS 7.9.2009
- Docker version: 20.10.11
- Docker-compose version: 1.24.0

___

The process of Harbor upgrade is working fine. All containers are updated and running. All of them have their status healthy.

The web interface is working well and we can pull/push without any problem via CLI.

But we have a persistent issue, no matter the new versions, regarding a repository (name: internaltools, id: 8). After the upgrade, we have **forbidden** red banner on _Repositories_ tab and it's empty. But, in _Summary_ tab, we can see number of repositories (48) and size (25Gb), so it's not really empty.
We also have this error on _P2P Preheat_ tab (we are not using it but we have this error only on these two tabs).
By the way, we are not able to pull/push on this repo. I tried different version but the problem still persists.

In core.log, I can see :
`Feb  9 13:39:05 172.21.0.1 core[1319]: 2022-02-09T12:39:05Z [ERROR] [/server/v2.0/handler/base.go:88]: failed to get project internaltools: project internaltools not found
Feb  9 13:39:05 172.21.0.1 core[1319]: 2022-02-09T12:39:05Z [ERROR] [/server/v2.0/handler/base.go:88]: failed to get project internaltools: project internaltools not found`

In proxy.log, I received 403 HTTP response for this repo:
`Feb  9 13:43:14 172.21.0.1 proxy[1319]: 192.168.2.5 - "GET /api/v2.0/users/current/permissions?scope=/project/8&relative=true HTTP/1.1" 200 3351 "https://10.14.1.14/harbor/projects/8/p2p-provider/policies" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 0.004 0.004 .
Feb  9 13:43:14 172.21.0.1 proxy[1319]: 192.168.2.5 - "GET /api/v2.0/systeminfo HTTP/1.1" 200 396 "https://10.14.1.14/harbor/projects/8/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 0.004 0.004 .
Feb  9 13:43:14 172.21.0.1 proxy[1319]: 192.168.2.5 - "GET /api/v2.0/projects/internaltools/repositories?page_size=15&page=1 HTTP/1.1" 403 56 "https://10.14.1.14/harbor/projects/8/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 0.004 0.005 .
Feb  9 13:43:14 172.21.0.1 proxy[1319]: 192.168.2.5 - "GET /api/v2.0/projects/internaltools/repositories?page_size=15&page=1 HTTP/1.1" 403 56 "https://10.14.1.14/harbor/projects/8/repositories" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 0.004 0.005 .
`

Due to these errors, I rolled back our Production Harbor service, but I cloned it in order to do some tests on it.

Don't hesitate to contact me if you need more logs, or if my explanations are not clear.
Thanks a lot for your help,

Antoine

**Comment by chlins** [comment]
From the core log it shows the project `internaltools` not found, so could you verify whether the project exist in fact from query from database directly?

**Comment by chlins** [comment]
https://github.com/goharbor/harbor/issues/15620

**Comment by AntoineCourtil** [comment]
Hello chlins,

I already checked the database, and *internaltools* project exists

There are two repositories wit the same name. The first one with ID 4 is an old one and deleted since more than one year. The second one is the great one (ID 8). Currently it's working fine like that since version 1.8

On the test instance, I tried to delete manually the ID 4, and restart the instance, but the problem persists 

>registry=# SELECT * FROM project;
 project_id | owner_id |         name         |       creation_time        |        update_time         | deleted | registry_id
------------+----------+----------------------+----------------------------+----------------------------+---------+-------------
>          1 |        1 | library              | 2020-10-23 05:36:15.22537  | 2020-10-23 05:36:15.22537  | f       |
>          4 |        6 | internaltools#4      | 2020-11-06 09:13:06        | 2020-11-06 09:13:27.964756 | t       |
>          8 |        6 | internaltools        | 2020-11-12 08:18:39        | 2020-11-12 08:18:39        | f       |

**Comment by AntoineCourtil** [comment]
Hello,

As my issue is related to https://github.com/goharbor/harbor/issues/15620, I found a fix.

I fixed the issue by changing in DB name of repository with tmp name, and rename it.
Problem is a non printable char in repo name, I don't know how this char has appeared..

`UPDATE project SET name='TMP' WHERE project_id=8;
UPDATE project SET name='internaltools' WHERE project_id=8;`

Upgrade was done without any issue, this case can be closed

Thanks a lot,
Antoine

**Comment by GuilhermeFernandesFaria** [comment]
> Hello,
> 
> As my issue is related to #15620, I found a fix.
> 
> I fixed the issue by changing in DB name of repository with tmp name, and rename it. Problem is a non printable char in repo name, I don't know how this char has appeared..
> 
> `UPDATE project SET name='TMP' WHERE project_id=8; UPDATE project SET name='internaltools' WHERE project_id=8;`
> 
> Upgrade was done without any issue, this case can be closed
> 
> Thanks a lot, Antoine

You saved my life! Thanks a lot!
