### ISSUE TITLE
Unable to create label via API call using curl command when behind OIDC.

### ISSUE THREAD

**Issue by prashi2202** [goharbor/harbor#16342]
Attempt to create a label for a registry owned by us works expected from the Harbor inbuilt swagger tool. We are connected to swagger with Schema as HTTPS and OIDC credentials role as a Admin.

POST HTTP requests are failing with Unauthorized/Forbidden error when we are accessing the API from outside (Ex: cURL command, Postman or from python requests package).

```
curl  -X 'POST' \
  'https://sashostedrepo.example.com/api/v2.0/labels' \
  -H 'accept: application/json' \
  -H 'X-Request-Id: 75' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: a68hsWTBhZqNITq1tEdNv1lxypZy0o/A4UZJ7Xi2vXOct3hGN9m/tTLgReF6a5NESjlUp6qMw==' \
  -d '{
  "update_time": "2022-02-09T15:22:27.700Z",
  "description": "Testing12345",
  "color": "string",
  "creation_time": "2022-02-09T15:22:27.700Z",
  "deleted": true,
  "scope": "p",
  "project_id": 75,
  "id": 0,
  "name": "Prashanth_Testing12345"
}'
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
```

We also tried using the credentials however no luck..

```
curl -u "harbor-admin-prashanth:oSCYvPae7xq9isS2DvT4LIIa" -X 'POST' \
  'https://sashostedrepo.example.com/api/v2.0/labels' \
  -H 'accept: application/json' \
  -H 'X-Request-Id: 75' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: a68hsWTBhZqNITq1tEdNv1lxypZy0o/A4UZJ7Xi2vXOct3hGN9m/tTLgReF6a5NESjlUp6qMw==' \
  -d '{
  "update_time": "2022-02-09T15:22:27.700Z",
  "description": "Testing12345",
  "color": "string",
  "creation_time": "2022-02-09T15:22:27.700Z",
  "deleted": true,
  "scope": "p",
  "project_id": 75,
  "id": 0,
  "name": "Prashanth_Testing12345"
}'
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
```
Same action on a harbor instance that is not controlled by ODIC succeeds.

```
$ curl -X 'POST' \
  'https://sashostedrepo.example.com/api/v2.0/labels' \
  -H 'accept: application/json' \
  -H 'X-Request-Id: 75' \
  -H 'authorization: Basic YWRtaQDEyMw==' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: rl00MYQlI6wOf9DBHaQmKlwC8jQEAKhkySb5VhMsdRwMjq26w==' \
  -d '{
  "update_time": "2022-02-09T15:22:27.700Z",
  "description": "Testing123456",
  "color": "string",
  "creation_time": "2022-02-09T15:22:27.700Z",
  "deleted": true,
  "scope": "p",
  "project_id": 75,
  "id": 0,
  "name": "Prashanth_Testing123456"
}'
```
![image](https://user-images.githubusercontent.com/83032278/153235148-5cb679c3-eab0-4d73-9044-e61069b2c001.png)

What is needed :

We do not wish to give the admin access to the user, a normal OIDC user with project ownership should be able to perform this action.
I see that there are many articles discussing about similar incident, is there a solution for this issue. If so can someone  please share the same.

**Comment by prashi2202** [comment]
We need urgent assistance on this, one of our client is in need of a solution soon.

**Comment by prashi2202** [comment]
Is there any progress with the concern I have raised?

**Comment by chlins** [comment]
@prashi2202 Harbor does not support basic auth when use OIDC, but could use id token to call harbor API, refer to this issue: https://github.com/goharbor/harbor/issues/10597#issuecomment-603159112
