### ISSUE TITLE
Garbage collection does not delete images from file system

### ISSUE THREAD

**Issue by grafra** [goharbor/harbor#16349]
- harbor version: 2.4.1
- docker engine version:   20.10.12 Community
- docker-compose version: 1.23.2,

I have freshly installed harbor 2.4.1 on CentOS 7 using the installer

It seems to me that running the garbage collector does not remove the deleted images from the file system.

I created a new project and using a replication rule i imported some images from my old registry. 
After the import the project page stated, that the images in this project were in total about 28 GB. 
The project overview page stated that the storage used was in total 32 GB.

Now I went into the project and deleted all the repositories in the project and after that I run the garbage collector.

The project now  reported 0 GB of images.
I would have expected, that also the total storage space would be reduced by the 28 GB. However this did not happen. It stayed at 32 GB.

I deleted the empty project and had a look at all the other projects and the sum of the space reported as used by these projects added up to 6 GB. Which was what I expected.
However the total space was still reported as 32 GB.

Which is in accordance with the amount of disk space reported when invoking df -h -Text4

If on then runs the same replication rule again, the import of the images is quite fast and in the log file on finds a lot of lines telling the blob already exists

2022-02-10T16:42:28Z [INFO] [/controller/replication/transfer/image/transfer.go:296]: the blob sha256:60381189250b34207b2ce1c2878e0f0fa05fba6934a34355b0926f03ea1e8e18 already exists on the destination registry, skip
2022-02-10T16:42:28Z [INFO] [/controller/replication/transfer/image/transfer.go:272]: copy the blob sha256:60381189250b34207b2ce1c2878e0f0fa05fba6934a34355b0926f03ea1e8e18 completed

For  me it seems as if harbor skips deleting the blob data.

How can I free up the disk space occupied by the deleted images.

**Comment by grafra** [comment]
I found the garbage collector logs and I do not understand what they want to say.
They list a lots of candidates but then say nothing to delete ?
Is this correct
```
garbage_collection.go:145]: Garbage Collection parameters: [delete_untagged: false, dry_run: false, time_window: 2]
garbage_collection.go:155]: start to run gc in job.
garbage_collection.go:430]: artifact trash candidates.
garbage_collection.go:432]: ID-663 MediaType-application/vnd.docker.container.image.v1+json ManifestMediaType-application/..
garbage_collection.go:432]: ID-665 MediaType-application/vnd.docker.container.image.v1+json ManifestMediaType-application/..
                             .
							 .
							 .
garbage_collection.go:203]: no need to execute GC as there is no non referenced artifacts.
garbage_collection.go:331]: The GC job actual frees up 0 MB space.
garbage_collection.go:174]: success to run gc in job.
```

**Comment by wy65701436** [comment]
Are these artifact were removed within two hours, if so, it will reserve 2 hours for read/write conflict. Execute GC after the time window.

**Comment by grafra** [comment]
In deed I tried the garbage collection with in 2 hours after importing them. 

I will try waiting 2 hours.

**Comment by grafra** [comment]
OK after 2 hours the gc removed the files.

All tough, this time window is mentioned in the documentation, it slipped my attention.
But this is entirely my fault.

But in the log file it would be helpful  to  have some hint on this time window.
You are showing the creation time. Maybe on could add a hint.
