### ISSUE TITLE
GC log too long to check

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16345]
Because there are many GC logs, it might exceed 100MB files, users might fail to get the logs of the job service in the browser. especially in some failed cases, the most important information is the last failed error. it is better to check the file size before retrieve, if it exceeds the max size, should send the tail of this file.

https://github.com/goharbor/harbor/blob/f2beed577f5014f84ad53c92a9192b54947bdd58/src/jobservice/logger/getter/file_getter.go#L27-L38

**Comment by bitsf** [comment]
I think this API should support http range query, and return stream instead of bytes, or it will take too much memory
