### ISSUE TITLE
Missing images for v2.4.1 in ghcr.io

### ISSUE THREAD

**Issue by keskad** [goharbor/harbor#16347]
Hi,

Verson v2.4.1 was already released - https://github.com/goharbor/harbor/releases/tag/v2.4.1
but it is not present on https://github.com/orgs/goharbor/packages/container/package/harbor-core

My Harbor upgrade on test cluster hanged up, because it is not able to pull from docker hub.

Thanks :)

**Comment by wy65701436** [comment]
we do not use ghcr to ship images, but dockerhub. For your case, you can download the offline installer, unzip and docker load images.
