### ISSUE TITLE
Registry Landscape need to updated

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16357]
see 
https://goharbor.io/docs/2.4.0/build-customize-contribute/registry-landscape/

We need to add the proxy cache and trace metrics to Harbor

**Comment by a-mccarthy** [comment]
@stonezdj thanks for opening.  I can update the Harbor components, but i'm wondering if we've kept up the other registries in the doc? i can't remember how we have been maintaining this page in the past, do are we rely on the community to help us keep this page up-to-date? thanks!
