### ISSUE TITLE
docker push 403

### ISSUE THREAD

**Issue by variesdiffmayfuse2** [goharbor/harbor#16360]
harbor version：v2.4.1
docker version：20.10.2
docker-compose version 1.18.0;

when i run 
docker login xxx.cn
Login Succeeded
then i push
docker push xxx.cn/xx/xx:v1
it returns:
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access this resource.</p>\n</body></html>\n"

I have tagged rightly according to harbor manul.

who can help me? Does anyone know this problem?

![图片](https://user-images.githubusercontent.com/95687271/153808298-a7eb6c5e-08fa-4cae-bad9-6333023b1974.png)

**Comment by chlins** [comment]
Did you create project in harbor manually before push image?

**Comment by variesdiffmayfuse2** [comment]
> image

yes,i did!
BUT
i login use command "docker login ip:port" !
then tag use command "ip:port/xx/xx:v1"
then it does not response 403 and push Sucessfully!

**Comment by chlins** [comment]
So push failed and return 403 when you use domain, but success when use ip:port?  Which way did you use to install harbor ?
