### ISSUE TITLE
Trivy fails for large (>1GB) images

### ISSUE THREAD

**Issue by jcambronero** [goharbor/harbor#16365]
We're facing the same issue described at: https://github.com/aquasecurity/trivy/issues/1312, where images larger than 1GB are failing to complete the trivy scan.
We have tried using trivy-adapter-photon:v2.2.4, trivy-adapter-photon:v2.3.5 and even trivy-adapter-photon:v2.4.1, but we're seeing the same issue in all versions.
According to the trivy issue mentioned [above](https://github.com/aquasecurity/trivy/issues/1312), this seems to be resolved in trivy [v0.22.0](https://github.com/aquasecurity/trivy/releases/tag/v0.22.0), which is not available in any of the current Harbor releases.

Is it possible to bump up trivy to v0.22.0+ for all Harbor releases?

**Comment by zyyw** [comment]
Hi @jcambronero TRIVYVERSION is dumped to v0.22.0 and TRIVYADAPTERVERSION is dumped to v0.25.0 in Harbor 2.4.2 and Harbor 2.5.0 , both of which will be FC-ed within a few weeks. Stay tuned and please try it out once they are released.

**Comment by jcambronero** [comment]
Thank you @zyyw , yes we'll test it as soon as it's available.

**Comment by AyushCloud** [comment]
Hello,

We are also facing the same issue with image greater than 23Gb
2022-06-22T12:50:43Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 2: 2022-06-22T12:45:46.433Z#011#033[34mINFO#033[0m#011Need to update DB
Jun 22 12:50:43 jobservice[13349]: 2022-06-22T12:45:46.433Z#011#033[34mINFO#033[0m#011Downloading DB...
Jun 22 12:50:43 jobservice[13349]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 22 12:50:43 jobservice[13349]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15d6598]
Jun 22 12:50:43 jobservice[13349]: goroutine 30045 [running]:
Jun 22 12:50:43 jobservice[13349]: github.com/aquasecurity/fanal/analyzer/language/python/packaging.packagingAnalyzer.Analyze({}, {0x3eb00000200, 0xc003b17510}, {{0x0, 0x0}, {0xc003675340, 0x63}, {0x21699a8, 0xc0023095e0}, {0x7f2e08e65e88, ...}, ...})
Jun 22 12:50:43 jobservice[13349]: https://github.com/goharbor/harbor/issues/11/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220303080309-254063f95ea0/analyzer/language/python/packaging/packaging.go:53 +0x178
Jun 22 12:50:43 jobservice[13349]: github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile.func1({0x215ac10, 0x31f4028}, {0x215c6f8, 0xc003b17510})
Jun 22 12:50:43 jobservice[13349]: https://github.com/goharbor/harbor/issues/11/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220303080309-254063f95ea0/analyzer/analyzer.go:253 +0x275
Jun 22 12:50:43 jobservice[13349]: created by github.com/aquasecurity/fanal/analyzer.AnalyzerGroup.AnalyzeFile
Jun 22 12:50:43 jobservice[13349]: https://github.com/goharbor/harbor/issues/11/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220303080309-254063f95ea0/analyzer/analyzer.go:248 +0x3d2
Jun 22 12:50:43 jobservice[13349]: : general response handler: unexpected status code: 500, expected: 200
Jun 22 12:50:43 jobservice[13349]: 2022-06-22T12:50:43Z [ERROR] [/jobservice/runner/redis.go:122]: Job 'IMAGE_SCAN:96bc19994b9862a5d051cf42' exit with error: run error: check scan report with mime type

Is is related to the size of an image

Harbor Version v2.4.2
Docker version 19.0.0
docker-compose version 1.26
Postgresql: 9.6
