### ISSUE TITLE
Option to disable weak ciphers

### ISSUE THREAD

**Issue by Tembhum** [goharbor/harbor#16367]
**Is your feature request related to a problem? Please describe.**
Weak ciphers are considered a security vulnerability.

**Describe the solution you'd like**
Providing users an option to specify TLS settings in order to disable weak ciphers from Harbor.

> List of Weak Cipher Examples on Harbor:
> 1. TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA 
> 2. TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA 
> 3. TLS_RSA_WITH_AES_256_CBC_SHA
> 4. TLS_RSA_WITH_AES_128_CBC_SHA 
>

**Comment by stonezdj** [comment]
You could disable the weak cipher by updating the 
common/config/nginx.config
change ssl_ciphers
```
ssl_ciphers '!SHA:!aNULL:kECDH+AESGCM:ECDH+AESGCM:RSA+AESGCM:kECDH+AES:ECDH+AES:RSA+AES:';
```
And restart Harbor.
