### ISSUE TITLE
High version harbor does not support low version harbor to join

### ISSUE THREAD

**Issue by lilongfeng0902** [goharbor/harbor#16361]
What can we help you?
**Harbor Info:**
High version harbor：v2.3.4-7a068b12
Low version harbor: v1.10.10-322972dc
**Purpose:** 
Put low version harbor join to the high version harbor that I can copy the images in the high version to the low version.
**The error message:**
When registering a lower version of harbor with a higher version of harbor， the messager "the registry is unhealthy" will pop up.
**Through source code analysis:**
Higher versions of harbor only support v2 api.

Now, I want to know, whether the community supports the registration of a higher version of harbor with a lower version, one of the scenarios is to copy a higher version image to a lower version image.

**Comment by chlins** [comment]
Harbor not support replication between different versions.

**Comment by lilongfeng0902** [comment]
> Harbor not support replication between different versions.

Thanks for your attention. Is there any plan to support, low version harbor can be registered to high version harbor. In other words, a higher version of harbor can manage a lower version of harhor.

**Comment by chlins** [comment]
Unfortunately, we have no plan to support replication between 1.x and 2.x because there are big changes. The replication between 1.x to 1.x or 2.x to 2.x is possible, so you could upgrade your harbor to 2.x or use other image copy tools outside of harbor for replication if you just want to replicate from 2.x to 1.x.

**Comment by lilongfeng0902** [comment]
> Unfortunately, we have no plan to support replication between 1.x and 2.x because there are big changes. The replication between 1.x to 1.x or 2.x to 2.x is possible, so you could upgrade your harbor to 2.x or use other image copy tools outside of harbor for replication if you just want to replicate from 2.x to 1.x.

Yeah, I know. Thanks again for your attention. Thank you.
