### ISSUE TITLE
How to edit response structure of PUT robot api

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#16371]
Hi, 
We recently upgraded Harbor from 2.1.0 to 2.2.0 and noticed that the response of create robot via api has changed.
Earlier it was:
```
{
   "name":"name",
   "token":"token"
}
```

But now it is:
```
{
    "creation_time": "2022-02-13T04:59:34.568Z",
    "id": <id>,
    "name": "<name>",
    "secret": "<token>"
}
```

Due to the change of "token" to "secret", we are facing some issues in our pipelines.
Is there a way we can revert back or make some changes to the response structure? 
Thanks

**Comment by wy65701436** [comment]
the change was introduced by robot v2 to support system level and permission editing. And the robot v1 support has been deprecated from v2.4, won't revert back. Just please update your pipeline to accommodate the change.
