### ISSUE TITLE
Unable to delete Helm charts or Helm chart repository

### ISSUE THREAD

**Issue by squashedlime** [goharbor/harbor#16384]
Unable to delete Helm charts or Helm repository

Harbor version: 2.40
Helm version: 1.8.0
Redis-ha version: 4.10.2

We have noticed in Harbor we have Helm a chart repository where we can’t delete any more helm charts. 
The helm repository had 430 helm charts which we tried to delete. Most of the helm charts were deleted but we were left with 107 helm charts that we are unable to delete. 
In the gui we get these errors:
When trying to delete the repository - Internal server error
When trying to delete a helm chart - fail to delete chart version: remove /chart_storage/testcharts/test-a55285619e2-eks.tgz: no such file or directory

In the logs for harbor-core pod  when trying to remove the repository:

`2022-02-16T12:10:57Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"[http error: code 404, message remove /chart_storage/app-storage/app-storage-3.65-SNAPSHOT-a55285619e2.tgz: no such file or directory http error: code 404, message remove /chart_storage/app-storage/app-storage-3.65-SNAPSHOT-28414b160e7-eks.tgz: no such file or directory http error: code 404, message remove /chart_storage/app-storage/app-storage-3.65.3.tgz: no such file or directory http error: code 404`

What should be done to allow the deletion of these Helm charts or the chart repository folder.

**Comment by zyyw** [comment]
@squashedlime , could you please clean the cached used by chartmuseum, and try to delete the remaining charts again?

**Comment by squashedlime** [comment]
@zyyw Thanks for the reply but could you be a bit more specific by what you mean by clean the cache used by chartmuseum? Could you give a more detailed how to if possible?

**Comment by kagehisa** [comment]
Same issue here. Harbor version: 2.4.0

The complete core log after trying to delete a helm chart:
`Jul  4 08:10:45 172.26.0.1 core[1383]: 2022-07-04T12:10:45Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"[http error: code 404, message remove /chart_storage/ados-agent/Postleitdaten-Api-0.4.25.tgz: no such file or directory]"}]}
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/lib/http/error.go:82, github.com/goharbor/harbor/src/lib/http.apiError
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/lib/http/error.go:51, github.com/goharbor/harbor/src/lib/http.SendError
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/common/api/base.go:73, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/common/api/base.go:234, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/core/api/chart_repository.go:391, github.com/goharbor/harbor/src/core/api.(*ChartRepositoryAPI).DeleteChart
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/reflect/value.go:543, reflect.Value.call
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/reflect/value.go:339, reflect.Value.Call
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/readonly/readonly.go:77, github.com/goharbor/harbor/src/server/middleware/readonly.MiddlewareWithConfig.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/security/security.go:75, github.com/goharbor/harbor/src/server/middleware/security.UnauthorizedMiddleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/artifactinfo/artifact_info.go:60, github.com/goharbor/harbor/src/server/middleware/artifactinfo.Middleware.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/lib/orm/orm.go:131, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/csrf/csrf.go:48, github.com/goharbor/harbor/src/server/middleware/csrf.attach.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/vendor/github.com/gorilla/csrf/csrf.go:297, github.com/gorilla/csrf.(*csrf).ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/csrf/csrf.go:68, github.com/goharbor/harbor/src/server/middleware/csrf.Middleware.func2
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/requestid/requestid.go:43, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/metric/metric.go:67, github.com/goharbor/harbor/src/server/middleware/metric.transparentHandler.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/trace/trace.go:28, github.com/goharbor/harbor/src/server/middleware/trace.traceHandler.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /usr/local/go/src/net/http/server.go:2046, net/http.HandlerFunc.ServeHTTP
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/mergeslash/mergeslash.go:17, github.com/goharbor/harbor/src/server/middleware/mergeslash.Middleware.func1
Jul  4 08:10:45 172.26.0.1 core[1383]: /harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1`

The tgz file was not on the filesystem, in that the message itself is correct. There was an entry in the chart storage cache.
I tried clearing the chart storage cache and the redis cache but the chart still appears in the UI.

Any idea what I could try next to fix this or any idea where to look next?

**Comment by okin** [comment]
I am seeing a similar behaviour with Harbor v2.5.3.

The UI shows a message like this:
```
fail to delete chart version: remove /chart_storage/<redacted>/orderservice-1.3.0.tgz: no such file or directory
```

The log of chartmuseum shows messages like this:
```json
{"L":"WARN","T":"2022-07-28T07:38:12.576Z","M":"[218567] Request served","path":"/api/<redacted>/charts/orderservice/1.3.0","comment":"","clientIP":"192.168.0.4","method":"DELETE","statusCode":404,"latency":"533.014µs","reqID":"4b77ccbc-6cc9-4d21-94ae-4a2bdeff2e95"}
```

I can work around this if I switch into the container and touch the missing file and then try to delete it again.
```bash
touch /chart_storage/<redacted>/orderservice-1.3.0.tgz
```

I would expect the service to nontheless delete the entry.
If the file is gone already half the job is done!
