### ISSUE TITLE
better handling of ldap users and groups

### ISSUE THREAD

**Issue by Krumbelfix** [goharbor/harbor#16388]
**Is your feature request related to a problem? Please describe.**
we had some troubles after moving an AD-Group into another folder. We got the error `Failed to fetch ldap group configuration:pq: duplicate key value violates unique constraint "unique_group_name" `. Users in the group which was moved can't see their Projects anymore. 

**Describe the solution you'd like**
Delete an user / Group completely from Harbor(database) including referencing db-entrys so we don't have orphan entries.
Aditionally it would be helpfull to see in which Projects the user / group is privileged and which privilegies are given. Maybe as an overview which is shown after clicking on 'groups' (or 'user').

**Additional context**
Thank you :)

**Comment by stonezdj** [comment]
it is fixed https://github.com/goharbor/harbor/pull/16260
