### ISSUE TITLE
system robot account can't pull from private project

### ISSUE THREAD

**Issue by r10r** [goharbor/harbor#16385]
Hi there,

I've configured a system robot account with the permission **Pull Artifact** under **Cover all projects** a s shown below
but the robot account can't pull artifacts from a private project.

<img width="555" alt="Screenshot 2022-02-17 at 14 57 10" src="https://user-images.githubusercontent.com/309304/154496610-fb186792-0e75-46d4-90df-92cfc4c7e7a5.png">

Trying to add the robot account as "Guest" member to the private projects fails too

<img width="555" alt="Screenshot 2022-02-17 at 15 06 35" src="https://user-images.githubusercontent.com/309304/154498222-968936e6-a301-418a-a872-504e620b98e0.png">

How can I configure the robot account to be able to pull from the private project?

The harbor version is **v2.3.2**  and I'm using OIDC authentication.

Thanks for your help.

**Comment by r10r** [comment]
I've upgraded to **v2.4.1** now but the issue persists.
Using `podman pull` returns the error **unauthorized: unauthorized to access repository**

**Comment by wy65701436** [comment]
hi, did you try with the docker client?

**Comment by r10r** [comment]
I tried it with podman and buildah. Do you need log output from either of these?

**Comment by wy65701436** [comment]
I want to confirm whether it's a podman specific problem.

**Comment by r10r** [comment]
Well, after testing with docker (in podman) I figured out that the secret of the robot account was invalid. :roll_eyes:
Podman and buildah always used the credentials from */etc/containers/auth.json* and I was to stupid to not relogin.

I'tested with docker client in podman
```
podman run -d --privileged --userns=host -v /etc/modules:/etc/modules:ro docker.io/library/docker:dind --name dind
podman exec -it dind /bin/sh
```

Sorry for taking your time!
