### ISSUE TITLE
Harbor UI does not show helm value file and throws an error

### ISSUE THREAD

**Issue by muhittink** [goharbor/harbor#16387]
Hi Folks!

If we want to have a look at the helm values file over the UI, we are getting a red banner which says: "unknown error, please try again later".

Harbor-Core says:

```
 harbor-core-69d7dd64f6-5zjhn core 2022-02-18T06:21:43Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: gzip: invalid header"}]} 
 ```

This seems to happen randomly with some charts, but you can still pull the charts and install them.

We are using the latest version of Harbor (v2.4.1). We push our Helm-Charts with helm v3.8 to the OCI-Registry (chartmuseum works not well).

This error happens with the bitnami and the official chart.

We tried also to upload 1000 Charts, after some time the command seems to hang and we sporadically get an 502-Error and the Chart is not uploaded. If we restart the container, it seems to work better but after a while there is the 502 again. I don't know wether this problem is related to the one above and has the same root cause, just want to mention.

**Comment by wy65701436** [comment]
hi, since the chartmuseum is under the deprecation phase, we just provide limit support on it. We engage user to use helm v 3.8 later to manage their OCI compatible charts.

**Comment by muhittink** [comment]
The problem ist not related to the chartmuseum, we disabled it already, since it slows everything down. We are using helm v3.8 and pushing to the oci-registry.

**Comment by sleepy-manul** [comment]
We are experiencing the following problem:
- Uploading a Helm chart with the Web GUI works fine
- Uploading the exact same Helm chart with Helm v3.8.1 is accepted (no errors in the Helm command), but the chart is not shown under "Helm Charts".

I currently cannot share logfiles of the server since I am not the administrator but can try to contact the admin and get them if it helps.

**Comment by hryan-ib** [comment]
Was there a resolution to this issue? I just upgraded Harbor to 2.6.1 (from 2.4.2) to see if the error banner mentioned above went away but it is still there. Along with that, it does not show details about the chart. We are setting up an OCI registry and are not using chart museum. We are not signing Helm charts with CoSign yet, but it seems these errors only pop up when I push a gpg signed Helm chart up. Charts that are not signed have not shown this issue so far.

**Comment by 0Styless** [comment]
We are also still seeing this issue. Is there anything we can do about this? @wy65701436

**Comment by fritz0011** [comment]
End of Apr 2025 and same error .....
