### ISSUE TITLE
Replication timeout between two harbors

### ISSUE THREAD

**Issue by liuchaowhu** [goharbor/harbor#16393]
Harbor version is v2.2.3

When copying between two harbors, **timeout occurs every 30 minutes**  why ? Which configuration parameter is working ？
 the log print  "**context deadline exceeded (Client.Timeout or context cancellation while reading body)**"

The following is the complete log :

Feb 17 17:49:00 172.20.0.1 jobservice[3950]: 2022-02-17T09:49:00Z [ERROR] [/replication/transfer/image/transfer.go:309]: failed to pushing the blob sha256:4b6b38e3e7dfa4cddf2f5e476484837c8c6c093ad4fb46831372b0bfeb5b4b80, size 1195411737: Put "http://core:8080/v2/bdp/cppocr/blobs/uploads/0fe9173c-4fa5-4c42-a15e-dbad05c372d9?_state=XtpK0kylGot9NiH1YfT3uq-trdGgLNRYUYtGoVr_lqt7Ik5hbWUiOiJ5b3VjYXNoLWJkcC9jcHBvY3IiLCJVVUlEIjoiMGZlOTE3M2MtNGZhNS00YzQyLWExNWUtZGJhZDA1YzM3MmQ5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIyLTAyLTE3VDA5OjE5OjAwLjMxOTExNjExWiJ9&digest=sha256%3A4b6b38e3e7dfa4cddf2f5e476484837c8c6c093ad4fb46831372b0bfeb5b4b80": readfrom tcp 172.20.0.10:50152->172.20.0.9:8080: **context deadline exceeded (Client.Timeout or context cancellation while reading body)**
Feb 17 17:49:00 172.20.0.1 jobservice[3950]: 2022-02-17T09:49:00Z [INFO] [/replication/transfer/image/transfer.go:274]: will retry 2s later
Feb 17 17:49:02 172.20.0.1 jobservice[3950]: 2022-02-17T09:49:02Z [INFO] [/replication/transfer/image/transfer.go:266]: copying the blob sha256:4b6b38e3e7dfa4cddf2f5e476484837c8c6c093ad4fb46831372b0bfeb5b4b80(the 2th running)...

**Comment by liuchaowhu** [comment]
![图片](https://user-images.githubusercontent.com/89571485/154832335-d29c8832-6194-495a-820b-bf1c3b9b6c95.png)

**Comment by liuchaowhu** [comment]
timeout occurs every 30 minutes
![图片](https://user-images.githubusercontent.com/89571485/154832770-0566d60d-b950-459a-b37c-d440278df236.png)

**Comment by chlins** [comment]
@liuchaowhu The default timeout for registry client in harbor is 30 minutes, so if the blob has not been copied in 30 mins, it will be timeout, did you set any bandwidth limit?

**Comment by liuchaowhu** [comment]
> 

no ,  how can i modify this  parameter  ?

**Comment by liuchaowhu** [comment]
no , how can i modify this  parameter&nbsp; ?&nbsp; or How to remove this restriction




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chenyu ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [goharbor/harbor] Replication timeout between two harbors (Issue #16393)





 
@liuchaowhu The default timeout for registry client in harbor is 30 minutes, so if the blob has not been copied in 30 mins, it will be timeout, did you set any bandwidth limit?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chlins** [comment]
@liuchaowhu  Currently no way to change it from outside, but you could change it from code and build the image by self. https://github.com/goharbor/harbor/blob/8d05007eb5671c324c69370f9a0e51a375c96414/src/pkg/registry/client.go#L110

**Comment by liuchaowhu** [comment]
> @liuchaowhu Currently no way to change it from outside, but you could change it from code and build the image by self.
> 
> https://github.com/goharbor/harbor/blob/8d05007eb5671c324c69370f9a0e51a375c96414/src/pkg/registry/client.go#L110

@chlins Can you provide a version to fix this problem ？help ~

**Comment by liuchaowhu** [comment]
> 
@chlins Can you provide a version which has no timeout limit ..help

**Comment by liuchaowhu** [comment]
How do I repackage if I delete timeout  parameter?  Can you provide packaging methods ? thank you  @chlins

**Comment by liuchaowhu** [comment]
> You could git clone harbor repo and then change the above `harbor/src/pkg/registry/client.go` line 110, replace the timeout 30 to what value you need or remove this line if don't want to timeout config, could follow below steps:
> 
>     1. `git clone` and checkout to v2.2.3, then change code.
> 
>     2. `make compile_core` this will compile core binary.
> 
>     3. `mv make/photon/jobservice/harbor_jobservice /${yourfolder}`
> 
>     4. write Dockerfile in ${yourfolder}
> 
> 
> ```
> FROM goharbor/harbor-core:v2.2.3
> COPY harbor_core /harbor/
> ```
> 
>     5. `docker build -t goharbor/harbor-core:v2.2.3-patch-timeout`
> 
>     6. replace image to  `goharbor/harbor-core:v2.2.3-patch-timeout` in goharbor/harbor-core:v2.2.3-patch-timeout docker-compose.yml or deployment if you use k8s.

@chlins When I perform the second step  ，There are no binaries in the directory  “make/photon/jobservice/harbor_jobservice”    .  but I found the dierectory  "/make/photon/core/" has the binary file harbor_core, Is there any problem ?
![图片](https://user-images.githubusercontent.com/89571485/155061392-d83bbe1e-3aed-4805-b5a1-718d382a6f1c.png)

**Comment by chlins** [comment]
@liuchaowhu Oh... sorry, it's my typo, you are right, it is `make/photon/core/harbor_core`.

**Comment by liuchaowhu** [comment]
> @liuchaowhu Oh... sorry, it's my typo, you are right, it is `make/photon/core/harbor_core`.

@chlins when i replace the timeout 30 to 30000   or  remove timeout , the harbor-jobservice has error
![图片](https://user-images.githubusercontent.com/89571485/155087799-ba35ab97-b260-4454-8677-549d2ee356aa.png)

The following is the complete log :
![图片](https://user-images.githubusercontent.com/89571485/155088446-1754bf27-47d5-47c6-8f4b-da9c379c3451.png)
![图片](https://user-images.githubusercontent.com/89571485/155088682-41f21264-7be5-4b70-b34f-301fdd70e4e4.png)

**Comment by chlins** [comment]
Could you try to use the same way to recompile and rebuild harbor jobservice component?

**Comment by liuchaowhu** [comment]
still has the same error , my steps :
1、 make compile_jobservice
![图片](https://user-images.githubusercontent.com/89571485/155116071-c3b73248-249f-4edd-96e2-018f713d4f90.png)

2、write Dockerfile in ${myfolder}
![图片](https://user-images.githubusercontent.com/89571485/155116284-7a2dbd82-ae7d-4515-a1c6-0b8e4d69946d.png)

3、replace image in docker-compose.yml
![图片](https://user-images.githubusercontent.com/89571485/155116493-abf50153-1bea-4025-8c5c-d87088375681.png)

4、docker-compose up -d
![图片](https://user-images.githubusercontent.com/89571485/155116591-3bbaeaa2-c201-4e9a-a4fe-69955c979aaf.png)

the  same error:
![图片](https://user-images.githubusercontent.com/89571485/155116900-7a15d309-6dfd-4e79-b319-6b5efd2fd49d.png)

**Comment by liuchaowhu** [comment]
> still has the same error , my steps : 1、 make compile_jobservice ![图片](https://user-images.githubusercontent.com/89571485/155116071-c3b73248-249f-4edd-96e2-018f713d4f90.png)
> 
> 2、write Dockerfile in ${myfolder} ![图片](https://user-images.githubusercontent.com/89571485/155116284-7a2dbd82-ae7d-4515-a1c6-0b8e4d69946d.png)
> 
> 3、replace image in docker-compose.yml ![图片](https://user-images.githubusercontent.com/89571485/155116493-abf50153-1bea-4025-8c5c-d87088375681.png)
> 
> 4、docker-compose up -d ![图片](https://user-images.githubusercontent.com/89571485/155116591-3bbaeaa2-c201-4e9a-a4fe-69955c979aaf.png)
> 
> the same error: ![图片](https://user-images.githubusercontent.com/89571485/155116900-7a15d309-6dfd-4e79-b319-6b5efd2fd49d.png)

@chlins

**Comment by chlins** [comment]
Does harbor service work well like ui login or pull/push images ?

**Comment by chlins** [comment]
If still not work, you could try to replace the core image to original version: goharbor/harbor-core:v2.2.3 but keep the replacement of jobservice image.

**Comment by liuchaowhu** [comment]
> If still not work, you could try to replace the core image to original version: goharbor/harbor-core:v2.2.3 but keep the replacement of jobservice image and then `docker-compose down` and `docker-compose up -d`.

@chlins Thanks， it  works !!
but why  the image sizes compiled in CentOS and ubutu   is  different ?   Is it related to the compilation environment ？
![图片](https://user-images.githubusercontent.com/89571485/155315134-819b5a83-ca2c-4ae6-ac29-dc48a7dffd04.png)

**Comment by liuchaowhu** [comment]
> If still not work, you could try to replace the core image to original version: goharbor/harbor-core:v2.2.3 but keep the replacement of jobservice image and then `docker-compose down` and `docker-compose up -d`.
@chlins 
but why the image sizes compiled in CentOS and ubutu is different ? Is it related to the compilation environment ？
![图片](https://user-images.githubusercontent.com/89571485/155315424-122c3238-08d7-45dd-807b-c260ff05b85a.png)

**Comment by liuchaowhu** [comment]
> If still not work, you could try to replace the core image to original version: goharbor/harbor-core:v2.2.3 but keep the replacement of jobservice image and then `docker-compose down` and `docker-compose up -d`.

@chlins  It Works  !
but why the image sizes compiled in CentOS and ubutu is different ? Is it related to the compilation environment ？
![图片](https://user-images.githubusercontent.com/89571485/155315641-986572f6-64a1-455b-adde-81a59f9252f3.png)

**Comment by liuchaowhu** [comment]
> If still not work, you could try to replace the core image to original version: goharbor/harbor-core:v2.2.3 but keep the replacement of jobservice image and then `docker-compose down` and `docker-compose up -d`.

@chlins  Thanks , It works
![图片](https://user-images.githubusercontent.com/89571485/155340986-0476b4b0-5cfb-44ca-8a53-0a611b16bd5e.png)

**Comment by liuchaowhu** [comment]
I have another question about  **make compile_jobservice** ：
When the **golang version** is **1.17.6,**     the harbor-jobservice  will be  **unhealthy**  , the error ：
![图片](https://user-images.githubusercontent.com/89571485/155678593-ffe2615b-9ac5-49bd-937b-7cedc0cf2eb2.png)
 but the version **1.15.6 is normal** 
![图片](https://user-images.githubusercontent.com/89571485/155678320-61a19ae4-1354-406c-9ae5-953818f09f03.png)

**Comment by chlins** [comment]
> 

I'm not sure that, but theoretically, base image should have no effect on the results. And also the error report was caused by harbor-core(jobservice will call core api) so you could check the core service.

**Comment by ziye-dm** [comment]
> You could git clone harbor repo and then change the above `harbor/src/pkg/registry/client.go` line 110, replace the timeout 30 to what value you need or remove this line if don't want to timeout config, could follow below steps:
> 
> 1. `git clone` and checkout to v2.2.3, then change code.
> 2. `make compile_core` this will compile core binary.
> 3. `mv make/photon/jobservice/harbor_jobservice /${yourfolder}`
> 4. write Dockerfile in ${yourfolder}
> 
> ```
> FROM goharbor/harbor-core:v2.2.3
> COPY harbor_core /harbor/
> ```
> 
> 5. `docker build -t goharbor/harbor-core:v2.2.3-patch-timeout`
> 6. replace image to  `goharbor/harbor-core:v2.2.3-patch-timeout` in goharbor/harbor-core:v2.2.3-patch-timeout docker-compose.yml or deployment if you use k8s.

Thank you for the detailed steps! I followed them with version v2.4.2 and it's working as expected now!
The patch image is at https://hub.docker.com/repository/docker/ziyedm/harbor-core and used in harbor-helm version 1.8.2 with values.yaml:
```
core:
  image:
    repository: ziyedm/harbor-core
    tag: v2.4.2-patch-timeout
```

But still, better to have an argument to control the timeout or I need to compile it every time I want to upgrade harbor! Which is error-prone!

**Comment by dajose** [comment]
I am facing this same issue, is there a plan to support configuring this timeout without rebuilding from code?

**Comment by leociociano** [comment]
I have the same problem.  Is there any other way to change this parameter?... maybe with an environmental variable?.  It's not an option for me to rebuild the images.

**Comment by dajose** [comment]
For my environment, what I've found useful is to set the replication to be done by chunks. Works every time with my slow network

![image](https://user-images.githubusercontent.com/4218582/214603369-fc60071a-5148-41c7-9daa-a942b10de236.png)

**Comment by chlins** [comment]
@leociociano Hi, there is an env `REGISTRY_HTTP_CLIENT_TIMEOUT` be available since v2.6.2, you can set it by minutes for harbor jobservice container. (e.g.  REGISTRY_HTTP_CLIENT_TIMEOUT=60 means timeout is 60 minutes)

**Comment by chlins** [comment]
> For my environment, what I've found useful is to set the replication to be done by chunks. Works every time with my slow network
> 
> ![image](https://user-images.githubusercontent.com/4218582/214603369-fc60071a-5148-41c7-9daa-a942b10de236.png)

@dajose Cool, it seems that replication copy by chunk is helpful for your scenario.

**Comment by yeongjae-motif** [comment]
> 안녕하세요, v2.6.2부터 사용할 수 있는 env가 있습니다 REGISTRY_HTTP_CLIENT_TIMEOUT. harbor jobservice 컨테이너에 대해 분 단위로 설정할 수 있습니다. (예: REGISTRY_HTTP_CLIENT_TIMEOUT=60은 시간 제한이 60분임을 의미합니다.)
라고 말씀해주셨는데, 아래와 같이 2분으로 적용 후 image pulling 하게되면 2분 내 fail 되어야하는데 동일하게 30분 후 fail됩니다.
이는 유효하지 않는 것 같습니다.

```
test@test:~$ kubectl exec -it harbor-core-xxx -n harbor -- printenv | grep REGISTRY_HTTP_CLIENT_TIMEOUT
REGISTRY_HTTP_CLIENT_TIMEOUT=2
test@test:~$ kubectl exec -it harbor-jobservice-xxx -n harbor -n harbor-test -- printenv | grep REGISTRY_HTTP_CLIENT_TIMEOUT
REGISTRY_HTTP_CLIENT_TIMEOUT=2
test@test:~$ kubectl exec -it harbor-registry-xxx -n harbor -n harbor-test -- printenv | grep REGISTRY_HTTP_CLIENT_TIMEOUT
Defaulted container "registry" out of: registry, registryctl
REGISTRY_HTTP_CLIENT_TIMEOUT=2
```
