### ISSUE TITLE
Global search returns empty result and "Internal server error"

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#16399]
Dear Harbor-Community,

We are using the Harbor registry in three different regions and in Region 1 we see, that the global search bar is not returning any result and we seeing ```internal server error``` message in the UI.
Unfortunately, we are not seeing any error messages in our logs, therefore I can't provide any more details at the moment.
The "Filter project" search is working fine in this particular reason.

In our other regions the global search bar is working fine, fast and without any issues.
The differences between these regions are mainly the amount of images which are stored:

Region 1: >450.000 images
Region 2: >70.000 images
Region 3: ~10.000 images

The version we are using is v2.4 in all three regions.

Does anyone of you have the same issues or had this issues in the past so we can find a solution for this? 

Thanks a lot!

Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Daimler TSS, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by wy65701436** [comment]
hi, can you please provide the incremental logs on the` internal server error`, and do you enable the chartmuseum in the failure harbor instance?

**Comment by AlexBarth13** [comment]
Hi @wy65701436, Thanks for your reply!
Yesterday we did some tests again to give you the correct feedback.
Results:

- Yes, we have chartmuseum enabled all the time
- Below are all logs, which we saw. We searched for an project called ```amazoncache```. Log level is set to ```DEBUG```.
```
2022-02-28 17:21:51	
proxy.log
Feb 28 17:21:51 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/search?q=amazoncache HTTP/1.1" 500 66 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 31.568 31.565 .

2022-02-28 17:21:20	
proxy.log
Feb 28 17:21:20 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/statistics HTTP/1.1" 200 203 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.919 0.920 .

2022-02-28 17:21:19	
proxy.log
Feb 28 17:21:19 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/projects?page=1&page_size=15 HTTP/1.1" 200 6646 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.091 0.092 .

2022-02-28 17:21:19	
proxy.log
Feb 28 17:21:19 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/configurations HTTP/1.1" 200 2863 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.012 0.012 .

2022-02-28 17:21:19	
proxy.log
Feb 28 17:21:19 172.18.0.1 proxy[2012]: <IP> - "GET /api/v2.0/registries?q=type%3D%7Bdocker-hub%20harbor%20azure-acr%20aws-ecr%20google-gcr%20quay%20docker-registry%7D&page_size=100&page=1 HTTP/1.1" 200 2501 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.010 0.012 .

2022-02-28 17:21:18	
proxy.log
Feb 28 17:21:18 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/users/current HTTP/1.1" 200 497 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.013 0.012 .

2022-02-28 17:21:18	
proxy.log
Feb 28 17:21:18 172.28.0.1 proxy[2019]: <IP> - "GET /api/v2.0/systeminfo HTTP/1.1" 200 371 "https://<host>/harbor/projects?globalSearch=amazoncache" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.008 0.004 .

2022-02-28 17:21:18	
proxy.log
Feb 28 17:21:18 172.28.0.1 proxy[2019]: <IP> - "GET /harbor/projects?globalSearch=amazoncache HTTP/1.1" 200 901 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.000 0.000 .

2022-02-28 17:17:11	
core.log
Feb 28 17:17:11 192.168.192.1 core[2028]: 2022-02-28T16:17:11Z [DEBUG] [/chartserver/handler_repo.go:166]: Getting index.yaml from 'http://chartmuseum:9999/amazoncache/index.yaml'

2022-02-28 17:17:09	
core.log
Feb 28 17:17:09 192.168.192.1 core[2028]: 2022-02-28T16:17:09Z [DEBUG] [/chartserver/handler_repo.go:166]: Getting index.yaml from 'http://chartmuseum:9999/amazoncache/index.yaml'

2022-02-28 17:17:06	
core.log
Feb 28 17:17:06 172.18.0.1 core[2024]: 2022-02-28T16:17:06Z [DEBUG] [/chartserver/handler_repo.go:166]: Getting index.yaml from 'http://chartmuseum:9999/amazoncache/index.yaml'

2022-02-28 17:17:02	
core.log
Feb 28 17:17:01 192.168.192.1 core[2028]: 2022-02-28T16:17:01Z [DEBUG] [/chartserver/handler_repo.go:166]: Getting index.yaml from 'http://chartmuseum:9999/amazoncache/index.yaml'
```

The result of the search is this:
![image](https://user-images.githubusercontent.com/99802718/156117083-6240d0f6-d2dc-4d26-90ca-002047dde606.png)

And as soon as I go back to the main page I will get the ```Internal server error```:
![2022-02-28 17_20_41-](https://user-images.githubusercontent.com/99802718/156117152-b7a40a55-9d1c-4b5a-9596-66f30c23ed1c.png)

I hope this helps!
Let me know, if you need more information from my side.
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Daimler TSS, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by wy65701436** [comment]
all of the `core.log` incremental entries are all provided? As for 500, it should be some errors.

**Comment by AlexBarth13** [comment]
Hi! Yes, all of the logs are provided. There are no more logs visible.

**Comment by wy65701436** [comment]
is it possible to enable debug log level for core?

**Comment by AlexBarth13** [comment]
Hi, The debug log level was already enabled for the logs. Therefore, the above log entries are all logs which we can provide.

**Comment by AlexBarth13** [comment]
Hi @wy65701436 Just a friendly reminder :) Any hint what may cause the problem or how we could fix it? Thanks!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Daimler TSS, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by wy65701436** [comment]
@AlexBarth13 if you still have the problem, we need the incremental log when you issue the search request, you can provide the core.log with enable the debug.

**Comment by AlexBarth13** [comment]
Hi @wy65701436 This issue still exists in our environment. Unfortuantely, we already enabled the DEBUG log level but there is not clear error messages in it.
I will grap the logs and provide it to you.

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by AlexBarth13** [comment]
Still an open topics and not yet identified and solved...

**Comment by AlexBarth13** [comment]
There was nobody else with this issue and no error in the logs. Therefore I will close this issue.
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
