### ISSUE TITLE
No external connection

### ISSUE THREAD

**Issue by jbleijenberg-esites** [goharbor/harbor#16396]
Hello,

I'm trying to use Harbor v1.10.10, via the docker-compose installer.
Everything works as expected, i can see the registry i can login, create projects/users etc.
But the entire setup has no outside connection, so i can't send new user emails or connect to external registries.

All other Docker containers i have running can connect to external resources easily. When i run a standalone container of the Harbor core, it can connect too.
It's not an DNS issue, since i can't connect directly by IP either

**Comment by wy65701436** [comment]
is it possible to upgrade Harbor to latest version, like v2.4? Since the v1.10.10 is EOF.

**Comment by jbleijenberg-esites** [comment]
Yeah, it is. To be honest, the tagging in Github is very confusing.

v1.10.10 is a newer tag than 2.4, so i assumed they just don't know how to tag properly and downloaded the latest tag instead of an older tag with newer code.

**Comment by wy65701436** [comment]
you can try with v2.5.0-rc1, and reopen it if the issue still exists.
