### ISSUE TITLE
TTL for images

### ISSUE THREAD

**Issue by yurinnick** [goharbor/harbor#164]
It would be nice to have an ability to specify TTL for images for different projects/repositories. Main use case: Nexus-like snapshot repository.

**Comment by reasonerjt** [comment]
Could you specify?  Such that when the image expires it will be cleared?

**Comment by yurinnick** [comment]
Yea. When image will expire, it should be removed. Might be a good idea automatically create tag with snapshot number on each push to this repository type.

Scenario:
- Create new repository `Demo` with `Snapshots` type and TTL 30 days
- Push new images to this repository. Image automatically gets two tags: lastest, previouse_tag + 1. Example: lastest and 1 (first image in the repository).
- After 30 days this image will be automatically removed.

Propose: storing images with very fast update cycle and short usage time. Example: images under heavy development which should be deployed on multiple machines.

**Comment by colachg** [comment]
With the rapid development of Docker and Microservice, I think this is a meaning feature.I hope it will be in your milestones.

**Comment by NeQuissimus** [comment]
**Resurrecting this**

What about a simple REST API with an endpoint /ttl/<IMAGE_NAME>/<DAYS_TO_KEEP>/ that flags an image as "to-be-expired after <DAYS_TO_KEEP> days"?
That way a CI could just make that REST call and essentially flag the image as "temporary"?!
Cronjob in the background, done :)

**Comment by reasonerjt** [comment]
We are working on a proposal about retention policy of images in Harbor:
https://github.com/goharbor/community/pull/4

It covers the requirement, closing this one.
