### ISSUE TITLE
Gitlab returns 401 on replication with Gitlab registry type, but works fine with Docker registry type

### ISSUE THREAD

**Issue by wvh** [goharbor/harbor#16405]
Hello!

I've got a problem replication/pulling from Gitlab causing an instant 401 even though the token seems to work.

- I've create a deploy token with `read_registry` permission in Gitlab. This token works when running `docker pull` locally.
- I added a Gitlab registry to Harbor (https://registry.gitlab.com/) with the token and key.
- Harbor seems to be able to connect to the URL and authenticate. Ping passes.
- I add a replication for `group/project` and start replication.
- The Harbor UI immediately returns the status: `failed to fetch artifacts: http error: code 401, message {"message": "401 Unauthorized"}`
- Nothing shows in the pod logs

But:
- I add a new registry with registry type basic Docker registry, everything else set exactly the same.
- Harbor replicates successfully

My guess is that the Gitlab code runs some fancier search code which does not work for a simple deploy token. I haven't found a way to get more debugging output about the actual URL triggering 401 in Gitlab.

I have tried many variations of `group/project`, `group/project/image`, `group/**` and `group/project/**` and all return 401 while regular Docker has no problem, so I think it must be some Gitlab-specific group or search API call as opposed to just a simple registry pull.

**Versions:**
- Harbor version 2.4.1
- Chart version 1.8.1
- Docker version 20.10.12, build e91ed5707e
- Docker-compose version (Kubernetes 1.21)

**Additional context:**
- **Harbor config files:** Available on request; nothing special.
- **Log files:** Nothing explaining more about the actual cause of the 401 during replication.

**Comment by chlins** [comment]
@lxShaDoWxl Could you help to take a look?

**Comment by lxShaDoWxl** [comment]
test your token this command
```
curl --header "PRIVATE-TOKEN: your-token" "https://gitlab.com/api/v4/projects?membership=1&per_page=50"
```

**Comment by MrLuje** [comment]
Using a token with only the `read_registry` permission give me the following message, is it expected ? 
What are the minimum permissions needed for a pull-based replication ?

![image](https://user-images.githubusercontent.com/632075/157627592-8306cc9a-6607-4ce7-ae7e-3014223c9048.png)

Thanks

**Comment by lxShaDoWxl** [comment]
minimum read all groups and projects, this **read_api**
