### ISSUE TITLE
why harbor-db   Keep restarting？

### ISSUE THREAD

**Issue by xwb1993** [goharbor/harbor#16410]
[root@bogon make]# docker logs 5f76e1636aa5
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
The default text search configuration will be set to "english".

Data page checksums are disabled.

**Comment by xwb1993** [comment]
there is a permission error,but not the same as https://github.com/goharbor/harbor/issues/14460,
who can help me ? Thanks!

**Comment by xwb1993** [comment]
#14460 said  can temporary change the permissions of the parent to 777,but /var/lib/postgresql/data is the directory, which will be created in the db container,how can i into  the container are not running? The harbor-db is keep restarting.

**Comment by stonezdj** [comment]
The /var/lib/postgresql/data directory is mounted by docker-compose,  could be found in the docker host, usually in `/data/database`
```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/data/database",
                "Destination": "/var/lib/postgresql/data",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Comment by lqywow** [comment]
I met the same problem, So how can I fix this problem？ @stonezdj

**Comment by lqywow** [comment]
> #14460 said can temporary change the permissions of the parent to 777,but /var/lib/postgresql/data is the directory, which will be created in the db container,how can i into the container are not running? The harbor-db is keep restarting.

@xwb1993 Has your problem solved？？？

**Comment by xwb1993** [comment]
> > #14460 said can temporary change the permissions of the parent to 777,but /var/lib/postgresql/data is the directory, which will be created in the db container,how can i into the container are not running? The harbor-db is keep restarting.
> 
> @xwb1993 Has your problem solved？？？

Sorry.Not resolved.

**Comment by lqywow** [comment]
Yes, I saw these 2 issues,&nbsp; not resolved...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 下午2:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [goharbor/harbor] why harbor-db   Keep restarting？ (Issue #16410)





   
#14460说可以临时将父级的权限改为777，但是/var/lib/postgresql/data是目录，会在db容器中创建，怎么进入容器没有运行？Harbor-db 不断重启。
  
@xwb1993你的问题解决了吗？？？
  
对不起。没有解决。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您发表了评论。消息 ID：<goharbor/harbor/issues/16410/1192228546 @ github 。com&gt;
