### ISSUE TITLE
Review content in Harbor wiki

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#16414]
**Is your feature request related to a problem? Please describe.**
I was looking through the [wiki](https://github.com/goharbor/harbor/wiki) in this repo and it seems to be very outdated. Im opening this issue to figure out how the wiki is being used and if content should be moved from the wiki to the website.

**Describe the solution you'd like**
We should review the content and either migrate it over to the Harbor website, remove it, or add a note saying the content is no longer being maintained and point folks to the website

I dont know a lot about how the wiki in this repo was used, so i'm interested in the following:
* Do any maintainers still add content to the Wiki? 
* Is there any advantage to having the wiki and the website?

Open to hearing everyone's thoughts!

| Page|  Keep | To Do/Questions|
|-----|------|---|
|[Home](https://github.com/goharbor/harbor/wiki) | Yes | **Abbie:** Update to reflect wiki pages after we remove outdated pages. Include a message about how to use the wiki and point to the website as well for additional information on using harbor |
|[Harbor Use case Chinese version](https://github.com/goharbor/harbor/wiki/%5BHarbor-User-Case%5D-(Chinese-Version)--%E4%BD%BF%E7%94%A8Harbor-Azure-IOT-Edge%E6%9E%84%E5%BB%BA%E6%99%BA%E8%83%BD%E8%BE%B9%E7%95%8C) | Yes | **Maintainers:** Is content still up-to-date? |
|[Architecture Overview](https://github.com/goharbor/harbor/wiki/Architecture-Overview-of-Harbor) | Yes | **Maintainers:** is content still up to date? **Abbie:** Create issue to add a link to this content in the harbor website|
|[Community events](https://github.com/goharbor/harbor/wiki/Community-Events) | TBD | **Orlin:** What should we do with this page, do we want to track these kinds of things again? |
|[Followup steps for feature 'image build history' developed by 360 team](https://github.com/goharbor/harbor/wiki/Followup-steps-for-feature-'image-build-history'-developed-by-360-team) | TBD | **Maintainers:** Issue referenced by this page has been closed, is this page needed any more? |
|[Followup steps for feature 'Keep the latest X tags, clear the old ones'](https://github.com/goharbor/harbor/wiki/Followup-steps-for-feature-'Keep-the-latest-X-tags,-clear-the-old-ones') | TBD | **Maintainers:** Are these notes still needed? Should they be kept in an issue? |
|[Harbor Book](https://github.com/goharbor/harbor/wiki/Harbor-Book) | Keep | **Orlin:** Is the wiki the best place for this information? |
|[Harbor FAQ](https://github.com/goharbor/harbor/wiki/Harbor-FAQs) | Keep | **Maintainers:** Are all FAQs are still relevant? **Abbie:** Create issue to add a link from the docs site to this page |
|[Harbor Roadmap](https://github.com/goharbor/harbor/wiki/Harbor-Roadmap) | TBD | **Roger:** Is there any benefit to keeping this for historical reasons? If we keep this page, we should add a note to the top pointing to the current roadmap file |
|[How to do replication with Robot Account](https://github.com/goharbor/harbor/wiki/How-to-do-replication-with-Robot-Account) | Move to website | This seems like a good candidate to move to the docs site. **Maintainers: Any reasons why this should stay in the wiki? |
|[Project page for incubating project 'Nuwa'](https://github.com/goharbor/harbor/wiki/Project-page-for-incubating-project-'Nuwa') | TBD | **Maintainers:** Is this page still needed? Project seems inactive, hasn't had a commit in 4 years |
|[Projects coming from community](https://github.com/goharbor/harbor/wiki/Projects-coming-from-community) | TBD | **Maintainers/Orlin: Whats the status of these community contributed projects? This page should be updated if we want to keep track of this information (hasn't been updated in 2 years)|
|[Release 1.5.1](https://github.com/goharbor/harbor/wiki/Release-1.5.1), [Release 1.6.0](https://github.com/goharbor/harbor/wiki/Release-1.6.0), and [Release 1.7.0](https://github.com/goharbor/harbor/wiki/Release-1.7.0)  | Remove | **Maintaienrs:** were these release notes? they seem to be different from the release notes on release page, for example: https://github.com/goharbor/harbor/releases/tag/v1.6.0. Please confirm before we remove|
|[Video Demos for Harbor](https://github.com/goharbor/harbor/wiki/Video-Demos-for-Harbor) | TBD | **Orlin:** Do we want to start tracking these again?|

**Comment by a-mccarthy** [comment]
@OrlinVasilev do you have any thoughts on this? There is some older community content in the wiki were we tracked talks and such. Do you have plans to restart tracking those things on the site again? https://github.com/goharbor/harbor/wiki/Community-Events and https://github.com/goharbor/harbor/wiki/Video-demos-for-Harbor

**Comment by yanji09** [comment]
Hi @a-mccarthy, team had an initial discussion on this. This wiki is a central place that allow users to navigate to other contents. Since the wiki page is easily to be updated and maintained, hence still want to keep the wiki instead of moving it to website. But yes, there are some content are out of date which should be removed. For example, the release section need to be removed as no need to track every release here. a few links are not available anymore.

**Comment by a-mccarthy** [comment]
@yanji09 thanks for the update! If it's still in use, then of course we should keep it :) For right now, maybe we can take the opportunity to clean out content that is outdated, and make sure that we have links from the wiki to the website and vice versa where it makes sense.

For example, this wiki page https://github.com/goharbor/harbor/wiki/Architecture-Overview-of-Harbor has a bunch of great information, but we dont link to it or cover this information on the website (to my knowledge). So i think this is an area where we can make improvements.

I can try to take a first pass through the pages to identify where we can remove or update wiki pages.

**Comment by a-mccarthy** [comment]
I started a table with some questions and ideas for what to do with this content. I added the table to the issue comment. Hopefully folks are able to edit this and update the chart.

 @yanji09 can you help get some eyes from the maintainers on the questions in the table?

@OrlinVasilev and @qnetter can you also take a look

thanks!

**Comment by yanji09** [comment]
thanks @a-mccarthy. do you want us to update the table directly or comment in this issue?

@wy65701436 would you help to take a look at the table and give some guidance?

**Comment by a-mccarthy** [comment]
@yanji09, if possible, I think we should update the table directly. That way we have one place to look for all the information.

**Comment by a-mccarthy** [comment]
@yanji09 and @qnetter adding the 2.6 label here because i'd like to get at least an idea of what needs to be updated in the wiki within the 2.6 release timeline. Based on the [community meeting notes](https://github.com/goharbor/community/wiki/Harbor-Community-Meetings#04202022), there is still a lot of time before we are planning to release 2.6, but i'm not sure of the other commitments in the release. Do you think it's possible to work on this issue within that timeframe? thanks!

cc: @OrlinVasilev
