### ISSUE TITLE
Unable to login with default login credentials 

### ISSUE THREAD

**Issue by thyagarajab** [goharbor/harbor#16419]
What can we help you?
While harbor upgradation form 2.2.0 to 2.3.4 we faced lot of issues so we have reverted  to 2.2.0 then we are unable to login with default credentials and also my oidc secret has expired. 

even if tried with actual default  user : Admin we are getting {"errors":[{"code":"BAD_REQUEST","message":"oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_client\",\"error_description\":\"xxxxxxxxx: Invalid client secret provided. 

please guide us how can resolve this issue.

**Comment by stonezdj** [comment]
It is `admin` not `Admin`

**Comment by thyagarajab** [comment]
@stonezdj We are trying with "Admin" username only it's redirecting to oidc auth please guide me how to update oidc secret  directly on db or how to remove oidc connect.

**Comment by thyagarajab** [comment]
@stonezdj  thanks now I am able to login to my older version of harbor, Could you please guide me how can I upgrade to harbor latest stable version my current version is 2.2.0
