### ISSUE TITLE
[Harbor 2.4.0]- Notary signature not getting replicated after Harbor image replication

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16411]
Hello,

Need some help with the harbor setup we are trying to do for a production environment.

We have setup 2 Harbor standalone registries - one primary and the other acting as Standby and enabled Harbor Replication feature to copy the images , helm charts and other artifacts between the 2 repositories.

Although the images are getting replicated but the notary signature is not getting replicated to the standby, due to which we are not able to enable Deployment security on Standby to pull only signed images.

Requesting you to suggest a workaround to work around this issue as notary signature is very important for us to ensure only trusted images are pulled from standby Harbor repository as well.

Thanks,
Inderpreet.

**Comment by wy65701436** [comment]
yes, it's by designed since the limiation of notary. And, in the coming new release, we will introduce cosign as the signature solution, and it supports signature replicaiton, try it.

**Comment by InderpreetSaini** [comment]
Thanks. 
In which release version, should we expect this to be integrated?

Any timelines by which this version would be available? Just for our planning purposes.
