### ISSUE TITLE
Multiple domain support in Harbor

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16422]
Hi,

I have a question around multi-domain support in Harbor, both HA and standalone (using docker-compose).

We are trying to deploy Harbor in active-standby setup , where HA Harbor using helm will be the active and standalone harbor will be standby.

Requests will only be sent to standby in case the active Harbor is down.

Is it possible to use 2 domains for each of the 2 Harbor repository like below, for both docker pull/push and using the Harbor portal?
Is there any recommendation from Harbor on not using multiple domains since there is no provision in the Helm/YAML configuration to specify more domains for both Harbor HA and standalone? Please advise.

Harbor HA:  www.abc.com, www.def.com
Standalone Harbor:  www.abc.com, www.xyz.com

def.com and xyz.com would be used to enable replication between the 2 instances and end-users will use harbor with www.abc.com for push/pull operations.

Also www.abc.com will be served from a load balancer which will work in active-passive mode.

**Comment by Vad1mo** [comment]
@InderpreetSaini, I actually would question your HA setup, Harbor does not support this active/passive setup. What is stopping you from setting up a true multi-cluster HA Harbor?

this way you don't have to deal with things like that?

**Comment by InderpreetSaini** [comment]
> I have seen some users configure different DNS for the active-standby and replication, but it requires lots of configuring change.

Thanks @stonezdj . Apart from the ingress rule addition for the second domain in the HA Helm setup, what are the configuration steps we are talking about on a high level?

Sorry to ask that, since there is not much documentation to refer to, for such a setup.

**Comment by InderpreetSaini** [comment]
> @InderpreetSaini, I actually would question your HA setup, Harbor does not support this active/passive setup. What is stopping you from setting up a true multi-cluster HA Harbor?
> 
> this way you don't have to deal with things like that?

@Vad1mo, when you say multi-cluster setup, you are saying 2 HA Harbor Helm setup done on 2 Kubernetes clusters, which are sharing the external Postgres DB and Redis DB, along with the images/artifacts stored in shared object/NAS storage?

We want to deploy our Postgres and Redis components in the Kubernetes cluster itself as pods to avoid provisioning/maintaining/administrating external Postgres and Redis components.

**Comment by Vad1mo** [comment]
> We want to deploy our Postgres and Redis components in the Kubernetes cluster itself as pods to avoid provisioning/maintaining/administrating external Postgres and Redis components.

You can do that. It is a proven and common concept to have a HA PG, Redis and S3. On such a foundation it is a no brainer to run a HA HArbor.

**Comment by InderpreetSaini** [comment]
> > We want to deploy our Postgres and Redis components in the Kubernetes cluster itself as pods to avoid provisioning/maintaining/administrating external Postgres and Redis components.
> 
> You can do that. It is a proven and common concept to have a HA PG, Redis and S3. On such a foundation it is a no brainer to run a HA HArbor.

Thanks @Vad1mo.
Although HA Harbor setup will fulfill our requirement of High availability, but we still need another setup to failover to, in case the whole cluster or the Datacenter goes down, to meet our Disaster recovery RTO/RPO guidelines.

**Comment by Vad1mo** [comment]
As I said a multi region HA Harbor Cluster is possible on top of other HA components. 

Gavin a harbor HA makes only sense if you have other system in HA config like IDP or the DBs etc.

Sometimes a short TTR (time to recover) is already  enough
