### ISSUE TITLE
Cannot add retention policy

### ISSUE THREAD

**Issue by jbertozzi** [goharbor/harbor#16436]
Hi,

It seems there is a bug when creating a policy retention using the UI.

**Expected behavior and actual behavior:**
Adding a new policy in the UI should work. Instead, I got the following message in a red top banner:

`validation failure list: id in path must be of type int64: string`

**Steps to reproduce the problem:**

Go to a project, "Policy", "add rule", put whatever in the fields, click add.

**Versions:**

- harbor version: 2.4.1
- docker engine version: 20.10.6
- docker-compose version: 1.28.6

**Additional context:**

Replaying the same request in with curl:

```
curl -XGET -H  "Content-Type: application/json" -u admin:XXX https://registryurl/api/v2

cat policy.json
{
    "algorithm": "or",
    "rules": [
        {
            "disabled": false,
            "action": "retain",
            "scope_selectors": {
                "repository": [
                    {
                        "kind": "doublestar",
                        "decoration": "repoMatches",
                        "pattern": "**"
                    }
                ]
            },
            "tag_selectors": [
                {
                    "kind": "doublestar",
                    "decoration": "excludes",
                    "pattern": "prod",
                    "extras": "{\"untagged\":true}"
                }
            ],
            "params": {
                "latestPushedK": 30
            },
            "template": "latestPushedK"
        }
    ],
    "trigger": {
        "kind": "Schedule",
        "references": {},
        "settings": {
            "cron": ""
        }
    },
    "scope": {
        "level": "project",
        "ref": 90
    }
}
```

```
Feb 28 16:31:58 192.168.80.1 core[1330]: 2022-02-28T15:31:58Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id a888e11b-2d47-4167-9329-955a1db5668d to the logger for the request PUT /api/v2.0/retentions/string
Feb 28 16:31:58 192.168.80.1 core[1330]: 2022-02-28T15:31:58Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/v2.0/retentions/string
Feb 28 16:31:58 192.168.80.1 core[1330]: 2022-02-28T15:31:58Z [DEBUG] [/server/middleware/security/session.go:46][requestID="a888e11b-2d47-4167-9329-955a1db5668d"]: a session security context generated for request PUT /api/v2.0/retentions/string
Feb 28 16:31:58 192.168.80.1 core[1330]: 2022-02-28T15:31:58Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"UNPROCESSABLE_ENTITY","message":"validation failure list:\nid in path must be of type int64: \"string\""}]}
```

**Comment by jbertozzi** [comment]
Please also note that we just migrate from 2.4.0 to 2.4.1.

It seems possible to add retention policy on newly created projects.

**Comment by jbertozzi** [comment]
Error stills occurs after an upgrade in 2.5.0.

**Comment by YangJiao0817** [comment]
I have not been able to reproduce the problem, can you provide more details?

**Comment by yogeek** [comment]
We also experience the same issue on one of our harbor project :
![Capture](https://user-images.githubusercontent.com/9500406/189320424-e54b817a-bc76-4b24-be83-aa5ade8f67f2.PNG)

What is strange is that all our harbor instance is configured as code with [terraform harbor provider](https://github.com/goharbor/terraform-provider-harbor) and on multiple projects, there is no issue with the retention policy, but on his specific project the policy is missing (cf. screenshot) and the error message is displayed each time we click on the policy menu.

We mounted a test instance of harbor with the same infra-as-code as the production one, but without any data and the issue doe not appear in this case. So we suspect a problem in the database...?

/reopen please ?

@YangJiao0817 Is it possible to reopen this issue please ?

**Comment by yogeek** [comment]
Additional information : when looking at the browser devtools, the following message is seen :
```
{"errors":[{"code":"UNPROCESSABLE_ENTITY","message":"validation failure list:\nid in path must be of type int64: \"string\""}]}

```

**Comment by YangJiao0817** [comment]
@yogeek Your issue is a little different, can you create a new issue and describe it?

**Comment by yogeek** [comment]
@YangJiao0817 Ok here is the new issue : https://github.com/goharbor/harbor/issues/17532
