### ISSUE TITLE
Metrics suddenly doesn't work

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor#16448]
If you are reporting a problem, please make sure the following information are provided:

Expected behavior and actual behavior:
curl localhost:9200/metrics suddenly doesn't work

Steps to reproduce the problem:

Versions:
Please specify the versions of following systems.

harbor version: 2.x
docker engine version: 17.12.1-ce
docker-compose version: 1.18.0
Additional context:

I don't see logs with error

my configuration is:

**Comment by chlins** [comment]
@jorgemansillacriado Could you fill your detail information?

**Comment by jorgemansillacriado** [comment]
Hi

exporter container is running even I can check metrics for components but work well
`curl localhost:9090/metrics?comp=core // work successfully`

``curl localhost:9090/metrics`   // no work
An error has occurred while serving metrics:

collected metric "harbor_project_total" { label:<name:"public" value:"true" > gauge:<value:4 > } was collected before with the same name and label values

**Comment by chlins** [comment]
It's not work when you don't carry comp parameter? I didn't reproduce your problem in my environment, and could you share more configurations?

**Comment by jorgemansillacriado** [comment]
> It's not work when you don't carry comp parameter? I didn't reproduce your problem in my environment, and could you share more configurations?

Hi what configuration do you need??
metric:
  enabled: true
  port: 9090
  path: /metrics

**Comment by jorgemansillacriado** [comment]
> curl localhost:9090/metrics?comp=core

it's straing because when I install registry metrics works well but after some hours it levave of work

**Comment by flaviomoringa** [comment]
I had already opened a similar issue here:
https://github.com/goharbor/harbor/issues/16057

And there is another similar one here:
https://github.com/goharbor/harbor/issues/16312

So maybe it should really be looked into

**Comment by chlins** [comment]
Do you have any error log got from the exporter?

**Comment by Lzhang-hub** [comment]
@flaviomoringa @chlins 
I have the same issue, is there any update?

------------------
exporter version: v2.5.0

this is exporter log:
```
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2022-03-25T07:56:59Z [INFO] [/common/dao/base.go:66]: Registering database: type-PostgreSQL host-aicloud-harbor-database port-5432 database-registry sslmode-"disable"
2022-03-25T07:56:59Z [INFO] [/common/dao/base.go:71]: Register database completed
2022-03-25T07:56:59Z [INFO] [/pkg/exporter/exporter.go:63]: collector HealthCollector registered ...
2022-03-25T07:56:59Z [INFO] [/pkg/exporter/exporter.go:63]: collector SystemInfoCollector registered ...
2022-03-25T07:56:59Z [INFO] [/pkg/exporter/exporter.go:63]: collector ProjectCollector registered ...
2022-03-25T07:56:59Z [INFO] [/pkg/exporter/exporter.go:63]: collector JobServiceCollector registered ...
2022-03-25T07:56:59Z [INFO] [/cmd/exporter/main.go:67]: Starting harbor_exporter with port=8001 path=/metrics metrics=true max_request=0 tls=false cert= key= cache_time=23 clean_interval=14400
```

curl CLUSTER-IP:8001/metrics

```
An error has occurred while serving metrics:

collected metric "harbor_project_total" { label:<name:"public" value:"false" > gauge:<value:1 > } was collected before with the same name and label values

```

**Comment by chlins** [comment]
@flaviomoringa @Lzhang-hub Could you try to run the sql in the database ? 

```
SELECT project_metadata.value AS public, COUNT(project_metadata.value)
	FROM project INNER JOIN project_metadata ON project.project_id=project_metadata.project_id
	WHERE project.deleted=FALSE AND project_metadata.name='public'
	GROUP BY project_metadata.value;
```

**Comment by Lzhang-hub** [comment]
> 

Thank you for your reply!
We deploying Harbor via Helm, and I run the sql in the database in follow step:

1.` kubeexec -it aicloud-harbor-database-0 /bin/bash`
2. `SELECT project_metadata.value AS public, COUNT(project_metadata.value) FROM project INNER JOIN project_metadata ON project.project_id=project_metadata.project_id WHERE project.deleted=FALSE AND project_metadata.name='public' GROUP BY project_metadata.value;`

The result is :
![image](https://user-images.githubusercontent.com/57925599/160271754-7a1383a1-2832-4d3b-b76a-4e4c164f09f2.png)

**Comment by chlins** [comment]
@Lzhang-hub Thanks your feedback, your result are helpful in identifying the root cause of the problem, and a more question, have you ever created a harbor project by harbor API manually(not in harbor UI)?

**Comment by flaviomoringa** [comment]
@chlins Only tomorrow I can also share the db results, but regarding creating projects through the API I can say that I have created many through the API because we have some automations in place to automatically create projects in harbor when a new tenant is added to our platform. So yes.

**Comment by Lzhang-hub** [comment]
> @Lzhang-hub Thanks your feedback, your result are helpful in identifying the root cause of the problem, and a more question, have you ever created a harbor project by harbor API manually(not in harbor UI)?

Yes , we have created some harbor project by harbor API manually. In our env , we provide API for user to create project.

**Comment by chlins** [comment]
@flaviomoringa @Lzhang-hub We found the root cause and will fix it asap, if you are in a hurry to use here is a workaround,  run the sql in the database: `update project_metadata set value='false' where name='public' and value not in('true', 'false');`

**Comment by jorgemansillacriado** [comment]
> @flaviomoringa @Lzhang-hub We found the root cause and will fix it asap, if you are in a hurry to use here is a workaround, run the sql in the database: `update project_metadata set value='false' where name='public' and value not in('true', 'false');`

ok thanks I'm going to check

**Comment by flaviomoringa** [comment]
> @flaviomoringa @Lzhang-hub We found the root cause and will fix it asap, if you are in a hurry to use here is a workaround, run the sql in the database: `update project_metadata set value='false' where name='public' and value not in('true', 'false');`

Amazing, will also try asap.

Thank you very much.

**Comment by jorgemansillacriado** [comment]
> SELECT project_metadata.value AS public, COUNT(project_metadata.value) FROM project INNER JOIN project_metadata ON project.project_id=project_metadata.project_id WHERE project.deleted=FALSE AND project_metadata.name='public' GROUP BY project_metadata.value;
 public | count
--------+-------
 false  |     7
 true   |     2
(2 rows)

I don't have public project , it fix i my case doesn't work

**Comment by jorgemansillacriado** [comment]
> update project_metadata set value='false' where name='public' and value not in('true', 'false');

Amazing , it works!!!

thanks

**Comment by flaviomoringa** [comment]
The result of the SQL command in my case is:

```
public | count
--------+-------
 true   |     2
 false  |     7
 False  |   126
(3 rows)
```

**Comment by flaviomoringa** [comment]
Does this means that all projects created through the API that are not public are using "False" instead of "false" and the capital F breaks the metrics?

This also means that until it's fixed when a new project is created through the API the metrics will break again, correct?

**Comment by chlins** [comment]
> Does this means that all projects created through the API that are not public are using "False" instead of "false" and the capital F breaks the metrics?
> 
> This also means that until it's fixed when a new project is created through the API the metrics will break again, correct?

@flaviomoringa Yes, the metadata.public should only be true or false, but API not validate the coming payload,  we'll also add the validation in API server side and migrate invalid data and if you still use old version, you could standardize your input of project creation API.

**Comment by qnetter** [comment]
Or, of course, we could make the test case-insensitive.

**Comment by Lzhang-hub** [comment]
OK, Thanks!


| |
张雷
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/28/2022 14:17，Chenyu ***@***.***> wrote：

@***@***.*** We found the root cause and will fix it asap, if you are in a hurry to use here is a workaround, run the sql in the database: update project_metadata set value='false' where name='public' and value not in('true', 'false');
