### ISSUE TITLE
LDAP Group DN is not found: DN:

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor#16441]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
LDAP Group DN is not found: DN:

**Steps to reproduce the problem:**
add group ldap configuration is ok because I can logon with my ldap user

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.x
- docker engine version: 17.12.1-ce
- docker-compose version: 1.18.0

**Additional context:**

I don't see logs with error

my configuration is:

LDAP Group Base DN 
ou=group,dc=mydomain,dc=com
LDAP Group Filter 
objectclass=group
LDAP Group GID 
cn
LDAP Group Admin DN 
LDAP Group Membership 
memberof
LDAP Ámbito 

Subárbol

**Comment by stonezdj** [comment]
You should input a valid DN for this configuration item or input field:
```
ccc_paas1-developer
```
Is not a DN name, the DN should like that 
```
cn=myname,ou=group,dc=mydomain,dc=com
```

**Comment by jorgemansillacriado** [comment]
> fail in llll
> 
> llll lll Y para tí he asignado, nuestra propo. de quitar un carril para obtener más plazas de aparcamiento, las dos preguntas, dos propo. del Gmixto, la de los árboles y el registro de comercios y la prop. del psoe de mejora la luz de las canchas de la pista de Gasómetro. Seis en total.
> 
> punto 3.
> 
> punto 7. punto 8. punto 10.
> 
> puno 16 punto 17

Y para tí he asignado, nuestra propo. de quitar un carril para obtener más plazas de aparcamiento, las dos preguntas, dos propo. del Gmixto, la de los árboles y el registro de comercios y la prop. del psoe de mejora la luz de las canchas de la pista de Gasómetro. Seis en total.

punto 3.

punto 7.
punto 8.
punto 10.

puno 16
punto 17

**Comment by jorgemansillacriado** [comment]
I'm going to use
Thanks for the reply. I going to use LDAP Group DN such as : cn=testgroup1,ou=HARBOR_ACL's,dc=mycompany,dc=local
