### ISSUE TITLE
Helm Chart  download   Fail

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16467]
![image](https://user-images.githubusercontent.com/88759374/156684820-5667de93-f2f0-4638-b5d7-dc2af9f23196.png)

Http failure response for https://192.168.2.250/api/chartrepo/helm-chart/charts/zookeeper-8.1.1.tgz: 404 Not Found

**Comment by wy65701436** [comment]
hi, since we're planning to deprecate chartmuseum and engage user to use helm v3.8 later to manager their OCI compatible chart file.

**Comment by AllForNothing** [comment]
Duplicated with #15228
