### ISSUE TITLE
Deploy harbor with helm in k8s,there is 404 not Found error in nginx,when i visit harbor interface.

### ISSUE THREAD

**Issue by neblen** [goharbor/harbor#16465]
What can we help you?
404 Not Found appears in harbor website.I deploy harbor with helm in k8s.What can I do for solving this problem？

**Comment by chlins** [comment]
@neblen Did you install ingress-controller, and could you check the log of it when you access harbor and got 404 response?

**Comment by wy65701436** [comment]
please file issue on helm-chart repo, thanks. https://github.com/goharbor/harbor-helm
