### ISSUE TITLE
Sync via tags

### ISSUE THREAD

**Issue by renhao-0518** [goharbor/harbor#16470]
如果通过标签来同步镜像。
那么配置的事件驱动，是打标签的事件，还是push事件。配置成通过标签同步，事件就不会生效。如果手动，那么他会遍历配置的project下的镜像有没有标签，几万个镜像，postgres cpu会被瞬间打满。
<img width="580" alt="image" src="https://user-images.githubusercontent.com/52058058/156712157-f0d731ee-1f59-43f5-bffe-8162da1251d7.png">
或者有没有同步单个镜像的api接口？看了下，好像是没有。

**Comment by chlins** [comment]
@renhao-0518 The event-based events type does not include `label` event, the label is only defined for filter, so it will not trigger replication when you add a label manually. As your replication policy, it will spend many resources if your harbor has numerous images when you trigger it manually, but if this action could be triggered by event like `push`, that will only filter this image of event and no need to iterate all images.
