### ISSUE TITLE
upgrade v2.2.0 to latest stable release 

### ISSUE THREAD

**Issue by thyagarajab** [goharbor/harbor#16475]
What can we help you?
Could you please guide me how can I upgrade to harbor latest stable version my current version is 2.2.0

Is need to upgrade stepwise upgrades ? or directly we can upgrade to latest

**Comment by wy65701436** [comment]
Just follow the migration guide, v2.2 can be upgraded to latest directly. 

https://goharbor.io/docs/2.4.0/administration/upgrade/
