### ISSUE TITLE
Will you support Nexus with Proxy cache?

### ISSUE THREAD

**Issue by chaojiniubi** [goharbor/harbor#16474]
Will you support Nexus with Proxy cache?

**Comment by wy65701436** [comment]
We need to implement the Nexus adapter, then the proxy cache can support it. Add the `help wanted` lable to see whether someone from community can help.

**Comment by stonezdj** [comment]
could you please try to create a registry with "Docker Registry" for Nexus and create a proxy cache project to proxy it?

**Comment by stonezdj** [comment]
could you please try to create a registry with "Docker Registry" for Nexus and create a proxy cache project to proxy it?

**Comment by chaojiniubi** [comment]
> could you please try to create a registry with "Docker Registry" for Nexus and create a proxy cache project to proxy it?

Oh,Thanks,it works.
