### ISSUE TITLE
wrong directory permissions for PVs

### ISSUE THREAD

**Issue by jmozd** [goharbor/harbor#16488]
**Expected behavior and actual behavior:**

After installing Harbor via Helm chart v1.8.1 on RKE and specifying Cinder-backed PVs, the created volumes are mounted successfully and Harbor apparently is up and running.

We noticed that after creating our first project (proxy for Docker Hub), no "Repositories" were showing up in that Harbor project, despite successfully fetching images. By chance we noticed error messages in the "registry" container about denied permissions while creating directories in "/storage".
After changing "/storage" ownership to "harbor:harbor" (from root:root) within the container, "repositories" were created and artefacts stored.

Once that was running, we tried "scanning" these repositories via Harbor's built-in scanner, which failed with "artifact not found" messages. The actual error cause was found in the jobservice container, where permission problems regarding /var/log/jobs were reported. Again changing ownership to "harbor:harbor" solved the issue, scanning was successful after that simple change.

**Steps to reproduce the problem:**
Install Harbor via Helm chart (v1.8.1 in this case). PVs were specified in values.yaml pointing to our Cinder-based back-end, but any block storage based back-end might result in the same problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.1
- docker engine version: 20.10.9-ce, build 79ea9d308018
- docker-compose version: n/a, installed via Helm chart v1.8.1

**Comment by stonezdj** [comment]
Could please open an issue in https://github.com/goharbor/harbor-helm ?

**Comment by jmozd** [comment]
https://github.com/goharbor/harbor-helm/issues/1157
