### ISSUE TITLE
GC with Allow garbage collection on untagged artifacts seems buggy.

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#16482]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I run a dryrun of the GC with 'Allow garbage collection on untagged artifacts' ON and the report says it would free
```
2022-03-07T10:25:53Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:236]: 24517 blobs and 2552 manifests eligible for deletion
2022-03-07T10:25:53Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:237]: The GC could free up 841210 MB space, the size is a rough estimation.
2022-03-07T10:25:53Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:174]: success to run gc in job.
```
This is not possible as there are multiple policies in place on various projects (with lots of images) and the total size of my registry is the same as the space being freed

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.4.2]
Installed with helm chart

Is this report currect? I mean, does it present the 'estimated value' based on just the existent images and does not take into account the policies and the immutability rules on each project?

**Comment by wy65701436** [comment]
The GC marks candidate by using table blob & project_blob, get the results that in blobs but not in project_blobs.
You can try to run sql(%d is the time_window, by default is 2):

`SELECT b.id, b.digest, b.content_type, b.status, b.version, b.size FROM blob AS b LEFT JOIN project_blob pb ON b.id = pb.blob_id WHERE pb.id IS NULL AND b.update_time <= now() - interval '%d hours';`

You can check the above results, and randomly pick up some to validate, to see whether it is being used. By table project_blob or table artfact and artifact_blob and blob.

**Comment by dioguerra** [comment]
Ok, I run this query and it gives no result.

So this means the blobs are being used by the project. But how does the retain policy work here?

**Comment by wy65701436** [comment]
For how does retain policy work, please refer to goharbor.io.

**Comment by stonezdj** [comment]
Could you please confirm the Harbor version is 2.4.2?

**Comment by dioguerra** [comment]
I rechecked and I'm running harbor-helm 1.8.1 which maps to 2.4.1
