### ISSUE TITLE
Unable to use unauthenticated email server

### ISSUE THREAD

**Issue by kfiresmith** [goharbor/harbor#16489]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: configure MTA w/o `email username` and `email password`
Actual: 
```
core[3001524]: 2022-03-08T21:39:27Z [ERROR] [/core/api/email.go:115]: failed to ping email server: 535 5.7.8 Error: authentication failed: generic failure
```

**Steps to reproduce the problem:**
Configure Harbor to use unauthenticated MTA and send test email.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.1
- docker engine version: 20.10.7-0ubuntu5~20.04.2
- docker-compose version: 1.25.0

**Comment by lindhe** [comment]
I'll let you in on a secret: it's never used, so it doesn't matter.

There is indeed a page in the global configuration settings to configure an email server, and there's even a button to test the connection to verify that it works! I configured this, believing that it would be used for sending warnings when vulnerabilities are detected, or something like that. But as far as I can tell, it is never referred to even once in the Harbor code (except for the configuration menu I mentioned).

At least this is my impression, please correct me if I'm wrong. :)

**Comment by lindhe** [comment]
https://github.com/goharbor/harbor/issues/15351#issuecomment-885721625
> The reset password feature had been removed, the configuration of the email server will be removed too.

Relates to #15351, #8045 and #13355.

**Comment by stonezdj** [comment]
The email server feature might be deprecated.  cc @qnetter
