### ISSUE TITLE
Harbor doesn't log locally when external logging is configured

### ISSUE THREAD

**Issue by kfiresmith** [goharbor/harbor#16483]
**Expected behavior and actual behavior:**
Configuring `external_endpoint:` in harbor.yml seems to disable `local:` logs.
Logs should be able to go to both places, allowing for quick on-host observation *and* long-term central log storage.

**Steps to reproduce the problem:**
Configure both local and external_endpoint, and observe that only external logs go out.

**Versions:**
- harbor version: 2.40

**Additional context:**

**Comment by stonezdj** [comment]
It is an expected behavior.

**Comment by kfiresmith** [comment]
Thanks for the clarification, but AFAICT, that's not detailed in the documentation, and to me seems like a less than ideal situation for the two options to be mutually exclusive rather than allowing for optionally logging to both, which provides more flexibility.
