### ISSUE TITLE
Proxy cache intermittently fails when using redhat registry

### ISSUE THREAD

**Issue by warroyo** [goharbor/harbor#16495]
When attempting to use registry.redhat.io as an endpoint for a proxy cache it intermittently fails. We are using "harbor" as the type for the proxy cache which seems to work fine for the auth to redhat registry however when pulling an image it errors out with the message below. It eventually will succeeded, and once the image is cached there are no longer issues.

i realize that redhat is not a defined type available for proxy cache however being able to use a proxy cache to redhat is extremely helpful in many environments. It is also odd that this is intermittent. 

```
Trying to pull [<redacted-domain>/rhel/rhel8/dotnet-60-runtime@sha256:3d55d22ddc68a2a23c01035c6b2bff0affba15c276761c7c5b9510c82fcc724e](http://<redacted-domain>/rhel/rhel8/dotnet-60-runtime@sha256:3d55d22ddc68a2a23c01035c6b2bff0affba15c276761c7c5b9510c82fcc724e)... 

determining manifest MIME type for docker://<redacted-domain>/rhel/rhel8/dotnet-60-runtime@sha256:3d55d22ddc68a2a23c01035c6b2bff0affba15c276761c7c5b9510c82fcc724e: Manifest does not match provided manifest digest sha256:e1b81533a9435de12537a5d93a0054d220d56ef8e2cf8a9c3f63e1c73429545e ERRO[0001] exit status 125
```

harbor version: 2.2.3

**Comment by qnetter** [comment]
@stonezdj @yanji09 can we discuss?

**Comment by warroyo** [comment]
@stonezdj any progress on this? can we remove the stale tag
