### ISSUE TITLE
Unable to limit login to AD group

### ISSUE THREAD

**Issue by kfiresmith** [goharbor/harbor#16491]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected:  Limit logins to specific AD group (eg `Harbor-Users`), similar to Harbor Admins group when using LDAP.  This is probably an RFE rather than purely a bug.
Actual:  Only able to play with LDAP base scopes, which won't help if you have a split in OU structure between parties that need access to access Harbor as regular users.

**Suggestion**
Apply same LDAP logic for Admins to a new feature for optionally limiting non-admin logins to a single AD/LDAP group.

**Versions:**
Please specify the versions of following systems.

   - harbor version: 2.4.1
   - docker engine version: 20.10.7-0ubuntu5~20.04.2
  -  docker-compose version: 1.25.0

**Comment by stonezdj** [comment]
You could specify the `LDAP Filter` to limit the logins to a specific LDAP group, for example:
```
memberof=cn=harbor_users,ou=groups,dc=example,dc=com
```
