### ISSUE TITLE
UNAUTHORIZED while using Harbor API

### ISSUE THREAD

**Issue by AndreyByhalenko** [goharbor/harbor#16504]
I need to use Harbor API and i send the following command:
**curl -X GET "https://registry.harbor.com/api/v2.0/replication/policies/38" -H "accept: application/json"**
Unfortunately i got the following error:
**{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}**

I tried to authorize with cli (**curl - u admin:*******)
I authorized on Harbor API itself.
I tried to login with robot account and token.

Still unable to use Harbor API.
Where should i add the authorization credentials in order to make it work?
Thanks.

**Comment by stonezdj** [comment]
```
curl -u "admin:Harbor12345" -k -X GET -H "Content-Type:application/json" "https://registry.harbor.com/api/v2.0/projects"
```

**Comment by AndreyByhalenko** [comment]
When i run curl commands i got the following error:
"Failed to authenticate user, due to error 'Invalid credentials' "

I'm using default admin:Harbor12345

**Comment by dioguerra** [comment]
I tried also user:pass basic auth but didn't work.

Using -H 'authorization: Basic {{ printf "admin:%s" .Values.harbor.harborAdminPassword | b64enc }}' \ Works for me
