### ISSUE TITLE
I have problem with network range created durning prepare - 172.17.0.0/16 clashes with my existing network range

### ISSUE THREAD

**Issue by ssbaksa** [goharbor/harbor#16505]
Hi,

I would like to ask is there a possibility to change or add network configuration to prepare process. As we are using 172.17.0.0/16 network heavily in our Lab (more than 400 systems) it is impossible to change that part.
Initial setting with prepare brake NFS mount of /data directory so I must do some manipulation each time when I test things. Example:
Create /data directory locally

Do configuration and execute ./install or ./prepare and then ./install

Move all data from /data directory to /temp/something mount NFS to /data directory than move back all data from /temp/something
Reconfigure docker-compose.yml to use different network by changing from:
networks:
  harbor:
    external: false
to:
networks:
  harbor:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
        - 
And then starting install.

It would be nice to have an option in harbor.yml which will be used to change default value for network in docker-compose.yml.jinja during prepare process.

Is something like that possible?

Br,

Saša

**Comment by stonezdj** [comment]
You could specify the docker network address by specifying the default-address-pools in the /etc/docker/daemon.json 
```
"default-address-pools":[{"base":"172.80.0.0/16","size":24},{"base":"172.90.0.0/16","size":24}]

```

**Comment by rgadeev** [comment]
don't forget to use yml syntax
`{
  "default-address-pools":
  [
    {"base":"172.80.0.0/16","size":24}
  ]
}
`

**Comment by ssbaksa** [comment]
Hi,

Thank you for your help. That was quick and easy solution. That way I can use different network in building process and then chose exact network range if I wish so.

Br,

Saša
