### ISSUE TITLE
[harbor 2.0.3] when dns fails on the ldap server, core should report the same instead of 'ldap connection fail: LDAP Result Code 200 "": dial tcp: i/o timeout"

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor#16518]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When using ldap authentication and dns fails to resolve the ldap server, the core log should reporting the same.  No connection to the ldap server is attempted.

Currently we would see logs similar to the following:
```
2022-03-12T11:34:07Z [WARNING] [/core/auth/ldap/ldap.go:58]: ldap connection fail: LDAP Result Code 200 "": dial tcp: i/o timeout
2022-03-12T11:34:07Z [ERROR] [/server/middleware/security/basic_auth.go:41][requestID="b7ca6c87-a281-4a78-afb8-9403e373fefe"]: failed to authenticate someone@sample.com: LDAP Result Code 200 "": dial tcp: i/o timeout
```

**Steps to reproduce the problem:**
Configure the ldap url with a non-existant server name that dns would respond with "No such name", or removing the ldap server name from dns, then try to login harbor and examine the log.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.3]
- docker engine version: [19.03.11]
- docker-compose version: [n/a] kubernetes v1.12

**Additional context:**

When the dns server lost the ldap server name occasionally, the harbor core log is misleading and making the diagnose so much harder.  

We have to setup tcpdump to capture the occasional dns failure - because when there is a dns failure, core did not send any packets to the ldap server, and we had to resort to capture for analysis.  On top of that the dns traffic is from the dns pods on a different k8s node.  During an outage, we do not the luxury of time, and being mislead, we could not device an effective work around - changing the ldap server to its ip would have worked if we know it is dns failure.

#15759 essentially is the same issue on harbor 2.2.3 and the same logs, except it had a known dns issue.

Please make the error log more informative, please fix the goldap library if necessary, at least you can test the error from goldap library, and add suggestion of the "real" root cause.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by stonezdj** [comment]
There is a security consideration, it is recommended that don't display error messages from LDAP to the end user.

**Comment by wu105** [comment]
If what we saw in the log is the response to the end user, we should add a separate, internal and meaningful log for administrators.
