### ISSUE TITLE
Refreshed token missing from robot account JSON doc

### ISSUE THREAD

**Issue by davidrfreeman** [goharbor/harbor#16519]
When refreshing a token for a robot account, there is an option to copy the new token, or download a JSON file. The downloaded JSON is missing the new token though, and it was assumed this would be present, to match the JSON downloaded when a robot account is initially created. The version I am current'y using is `2.2.2`.

**Comment by wy65701436** [comment]
@AllForNothing we should provide the same behavior for refresh.

**Comment by AllForNothing** [comment]
Confirmed, it is a UI bug, will fix it in 2.6
