### ISSUE TITLE
Projects can not be sorted by consumed quota in "Project Quotas"

### ISSUE THREAD

**Issue by fivezerosix** [goharbor/harbor#16517]
**Expected behavior and actual behavior:**
The project quotas view uses the column names as a sorting mechanism. By clicking the name you would be able to sort the most consuming project or the least. 

The column name not longer has that behavior, making it difficult to extract quick insights.

We even tried the old API call: `api/v2.0/quotas?reference=project&page=1&page_size=15&sort=-used.storage`
and the JSON returned objects unsorted. 

**Steps to reproduce the problem:**
From the left hand side menu clic "Project Quotas" -> The storage column can no longer be sorted by clicking it:
![image](https://user-images.githubusercontent.com/33496047/157914555-1bbf2b51-f523-4e9e-a56c-39839dd3780e.png)

**Versions:**
Please specify the versions of following systems.

- Harbor version: v2.3.5-239680cd
- Working Version: v2.2.4-1bc848b3

Please let me know if i can provide anything else useful.

**Comment by lindhe** [comment]
Sorry if I'm hijacking the discussion, but is the bytes used ever updated? I can only see "0Byte of ..." in my projects, regardless of what limit they have. And that's what I see in your screenshot too. I guess that needs to be fixed first before there's anything to sort by...

Or does that work for anyone else?

**Comment by AllForNothing** [comment]
@lindhe
Never seen the issue you mentioned.
Do you have any artifacts in each project?  And What's the used storage returned from quota API?
<img width="1899" alt="BA939467-7977-4ADC-9A51-834A41D27D7B" src="https://user-images.githubusercontent.com/30999793/164447820-c4460b7c-05d6-4e29-b032-4169a22c1582.png">

**Comment by lindhe** [comment]
Yeah, we have ~1TiB on disk.

Thanks for the suggestion. I've checked the quotas request now, and they too say that it's 0.

```json
{
  "8": {
    "creation_time": "2022-03-09T13:03:04.393Z",
    "hard": {
      "storage": 1099511627776
    },
    "id": 8,
    "ref": {
      "id": 7,
      "name": "project-1",
      "owner_name": ""
    },
    "update_time": "2022-03-09T13:03:04.393Z",
    "used": {
      "storage": 0
    }
  }
}

```

**Comment by lindhe** [comment]
Should I open a new issue for this? I don't want to clutter this discussion if my issue is not really related to OP's request.
