### ISSUE TITLE
error code not compliant with docker specs

### ISSUE THREAD

**Issue by alexmanno** [goharbor/harbor#16515]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When an image is not available on the registry, it should return `MANIFEST_UNKNOWN` error code instead of `NOT_FOUND` as described in https://docs.docker.com/registry/spec/api/#errors-2 .
This unexpected error code seems as been introduced in version 2.1.0. (https://github.com/goharbor/harbor/pull/12006)
This unexpected error brokes `docker-compose pull --ignore-pull-failures`. In fact it should exit without errors but it exit with an error instead.

**Steps to reproduce the problem:**

Both tests are executed with a **non existent image**

Against Harbor v1.10.3:

```
$ docker-compose pull --ignore-pull-failures
Pulling nginx ... 
Pulling nginx ... done
Some service image(s) must be built from source by running:
    docker-compose build nginx
```

Against Harbor v2.3.0:

```
$ docker-compose pull --ignore-pull-failures
Pulling nginx ... 
Pulling nginx ... error
ERROR: for nginx  unknown: repository example/nginx-not-found not found
unknown: repository example/nginx-not-found not found
```

Same error as above but from curl:

Against Harbor v1.10.3:

```
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"example"}}]}
```

Against Harbor v2.3.0:

```
{"errors":[{"code":"NOT_FOUND","message":"repository example/foobar not found"}]}
```

**Versions:**
Please specify the versions of following systems.

- harbor version: >= 2.1.0
- docker engine version: 20.10.7 
- docker-compose version: 1.29.2

**Comment by alexmanno** [comment]
Any news on this?

**Comment by alexmanno** [comment]
Any news on this?

**Comment by reasonerjt** [comment]
Harbor will NOT implement Docker's spec, instead, the target is to be compliant with
https://github.com/opencontainers/distribution-spec/blob/main/spec.md

Therefore, seems we should return the error code `NAME_UNKNOWN `

@wy65701436

**Comment by Vad1mo** [comment]
Hello @alexmanno 

We checked your PR and we fear that this change would break the OCI spec.

See:

- https://github.com/opencontainers/distribution-spec/blob/main/conformance/01_pull_test.go#L167
- https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests

**Comment by Vad1mo** [comment]
I am closing the PR, feel free to reopen if you think we need to discuss that again.

**Comment by hunshcn** [comment]
it should be reopened
