### ISSUE TITLE
Project Quota should be editable on the project

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#16523]
**Is your feature request related to a problem? Please describe.**
Right now, to edit a project quota, the administrator needs to navigate to the Project Quotas Admin page, search for the project, select the project and edit the quota. In my biew, this is a bit cumbersome

**Describe the solution you'd like**
Instead of needing to navigate the Administrative Panel to edit quotas, the admin should be able to edit the quota directly on the project. Maybe under summary or configuration

**Comment by stonezdj** [comment]
It should be edited in the administrator's page, or anyone could change the quota in project tab.

**Comment by stonezdj** [comment]
It should be edited in the administrator's page, or anyone could change the quota in project tab.
