### ISSUE TITLE
Replication by label very slow

### ISSUE THREAD

**Issue by xammep4** [goharbor/harbor#16535]
harbor v2.4.1 deployed via helm;

- storage external(s3)
- redis external
- postgresql(vers 10.15) external

Total images ~150k
The volume of images is ~1.5TB

We use replication in the same harbor configuration, we replicate only images with a globally defined label. replication task is configured scheduled (every 7 minutes).

After the replication starts (for example at 12:28), there is a delay of 5 minutes (12:33) before the actual replication starts.
At this time, we fix an increased load on the database and CPU component: core.
![Снимок экрана 2022-03-16 в 13 13 00](https://user-images.githubusercontent.com/10144377/158567286-8f4a1b52-00e8-4aae-9134-9d92514419d3.png)
.
![Снимок экрана 2022-03-16 в 13 14 10](https://user-images.githubusercontent.com/10144377/158567489-9f561c1c-3cad-4039-b3e2-c6ce2fed8af4.png)

I assume that this delay goes to the formation of a list of objects with the specified label.
![Снимок экрана 2022-03-16 в 00 41 00](https://user-images.githubusercontent.com/10144377/158567915-d0c92e3d-8692-4387-9931-ea77dabd3aec.png)
![Снимок экрана 2022-03-16 в 00 43 32](https://user-images.githubusercontent.com/10144377/158567942-5697c3fc-3539-4650-8f4d-4d5004b06b95.png)

We managed to reduce the time by limiting the list of projects by regular expression (by 3 minutes).
![Снимок экрана 2022-03-16 в 13 04 41](https://user-images.githubusercontent.com/10144377/158566319-c0526d5b-7d56-4e65-8295-bd5566806b8d.png)
I would like to hear tips that could lead to a reduction in this delay.

Had version 2.2.3, updated to 2.4.1. Which did not give results.

**Comment by chlins** [comment]
The execution start time is the trigger time which generated by schedule, but once the job be triggered, harbor needs to list all your candidate artifacts and analyze replication rules as filter then create different tasks for actual execution, and also the jobservice's default worker number is 10 which means the max parallel task number, so if your harbor has so many images it will spend relative time for filter and enqueue job for running that leads the start time latency.

**Comment by xammep4** [comment]
@chlins 
Thank you so much for the explanations. Tell me, can an increase in job service workers help in solving performance problems?

Maybe there are some other ways to solve this problem?

**Comment by chlins** [comment]
@xammep4  I think you could try to increase workers in jobservice and this can only help to reduce the task execution time, but the duration for list artifacts and filter can not reduce, they are happened in core. We will try to mock the large data volume like your environment to reproduce this issue, but for now there are no better workaround, i would recommend change the cron expression and reduce the frequency, from your monitor image it shows that hit all CPU of postgres, and also a tip is change the replication resource filter name to specific name like `library/nginx` that will benefit for less query from postgres.

**Comment by xammep4** [comment]
@chlins 
Thanks for the reply. However, we decided to use images to define prod. And tags can be hung by a large number of people. It is part of the ci\cd company. Accordingly, we only replicate prod images. Specifying the name directly, unfortunately, is not suitable. The frequency is set in such a way that the tasks do not overlap, otherwise, parallel tasks load the database even more, up to failure.

Maybe tuning the database (adding an index) can help and do you have a solution to this?

**Comment by chlins** [comment]
I'm not sure whether ways like adding an index can be helpful but i think the root cause is currently harbor does not support `create label` event to trigger replication.

**Comment by xammep4** [comment]
@chlins I see, thanks for the explanations. We will experiment with the database. Tag creation events to trigger replication are a wonderful, very necessary feature. Should we expect it in the next versions?

**Comment by chlins** [comment]
I'm sure `Tag creation events to trigger replication` has been supported in harbor, which not yet supported is `add label to someone artifact`.

**Comment by xammep4** [comment]
Competent colleagues helped with the index, which increased the speed by 2 times:

CREATE INDEX concurrently idx_artifact_repository_name_tmp ON public.artifact USING hash (repository_name)

![Снимок экрана 2022-03-22 в 23 19 35](https://user-images.githubusercontent.com/10144377/162452425-6b86d038-7ca9-4997-8f72-d627e8458086.png)
