### ISSUE TITLE
How can I push images of different architectures to the same repository?

### ISSUE THREAD

**Issue by thissuper** [goharbor/harbor#16532]
Hi, I have two architecture images, how can I push them to the same repository?

I tried to push it directly to the repository, but the first pushed tag will disappear.
![image](https://user-images.githubusercontent.com/57950591/158545135-b15159f4-9585-49ec-a24a-a9aeacfdf54e.png)

arm
```
docker push 129.168.100.3/library/nginx:latest
````
x86
```
docker push 129.168.100.3/library/nginx:latest
```

**Comment by ChristianCiach** [comment]
This has nothing to do with harbor. This is a docker-question. You cannot just push multiple images with the same tag and expect things to work.

See https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ for an example for how to do it correctly.

**Comment by thissuper** [comment]
@ChristianCiach thanks a lot
