### ISSUE TITLE
work on secrets: prevent they are exposed

### ISSUE THREAD

**Issue by tob123** [goharbor/harbor#16557]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
expected: sensitive data such as passwords are supported to be protected using docker secrets or other vault mechanisms.
instead I see many secrets are in env files and as such they are exposed each time for example when docker-compose, docker inspect <harbor container> is run.
secrets I have seen:
```
POSTGRESQL_PASSWORD
CORE_SECRET
REGISTRY_CREDENTIAL_PASSWORD
CSRF_KEY
JOBSERVICE_SECRET
POSTGRES_PASSWORD
HARBOR_ADMIN_PASSWORD

```

**Steps to reproduce the problem:**
install harbor using online installer 2.4.2. it puts env files here: 
```
./common/config/jobservice/env
./common/config/core/env
./common/config/registryctl/env
./common/config/db/env
```

**suggestions / thoughts**
* document purpose of the secrets
* document if the secret can be removed from the env file after installation (HARBOR_ADMIN_PASSWORD)
* support docker swarm secret engine

?

tob123

**Comment by stonezdj** [comment]
Do you have any suggestions on how to solve this issue in kubernetes?

**Comment by tob123** [comment]
docker-compose / docker / support docker secret engine:
solvable by supporting "SECRET_FILE" instead of only "SECRET" as an environment variable in the harbor container images.
the "SECRET_FILE" is a file on the container that can be read by the container.
reference example is here for mariadb container for example:
`docker run --name some-mysql -e MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql-root -d mariadb:latest`
source: https://hub.docker.com/_/mariadb/ 
one function that could be used during container startup (entrypoint) to support this:

````
file_env() {
    set +x
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
    local varValue=$(env | grep -E "^${var}=" | sed -E -e "s/^${var}=//")
    local fileVarValue=$(env | grep -E "^${fileVar}=" | sed -E -e "s/^${fileVar}                                                                                                                                                             =//")
    if [ -n "${varValue}" ] && [ -n "${fileVarValue}" ]; then
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi
    if [ -n "${varValue}" ]; then
        export "$var"="${varValue}"
    elif [ -n "${fileVarValue}" ]; then
        export "$var"="$(cat "${fileVarValue}")"
    elif [ -n "${def}" ]; then
        export "$var"="$def"
    fi
    unset "$fileVar"
    set -x
}
in case the secret is needed just execute file_env CORE_SECRET : 
it would return the contents of CORE_SECRET_FILE (which is an environment variable that refers to a file)

````
this function is in use a lot on official docker library container images.
value add:
prevent the secret is exposed if one runs 

a) docker-compose config
b) docker inspect {harbor container}
c) "some info" from the app perspective that parses system environment variables and shows them. more concrete example is phpinfo that exposes $_ENV.

kubernetes: it seems to me it can be solved already in helm charts / k8s secrets engine already and does not depend on the container image : https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
