### ISSUE TITLE
Add query condition to avoid full table scan

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16575]
https://github.com/goharbor/harbor/blob/354a2bd80d9efc1bcefe48ccac06394af62de556/src/controller/scan/base_controller.go#L989-L988

The underlying sql is 
```
SELECT id 
FROM task 
WHERE extra_attrs ->> ? = ?
```
it results in a full table scan.
We are going to create a index with vendor_type

CREATE INDEX IF NOT EXISTS idx_task_vendor_type ON task (vendor_type);

Because the current background is image scan, we should pass the vendor_type query condition to reduce rows to be scanned.

**Comment by kdenis4** [comment]
The issue is still active causing significant performance issues
