### ISSUE TITLE
Sensitive information printing

### ISSUE THREAD

**Issue by sundaykeke** [goharbor/harbor#16578]
version : 2.1.0

src/common/dao/testutils.go src/common/utils/test/database.go
log.Infof("POSTGRES_HOST: %s, POSTGRES_USR: %s, POSTGRES_PORT: %d, POSTGRES_PWD: %s\n", dbHost, dbUser, dbPort, dbPassword)

src/controller/blob/controller.go
log.Errorf("failed to set accepted blob size for session %s in redis, error: %v", sessionID, err)

src/pkg/token/token.go
log.Errorf(fmt.Sprintf("invalid jwt token, %v", token))

src/common/config/store/store.go
log.Errorf("error when loading data item, key %v, value %v, error %v", key, value, err)

src/common/security/secret/context.go
log.Debugf("invalid secret: %s", s.secret)

src/server/middleware/csrf/csrf.go
log.Warningf("Invalid CSRF key from environment: %s, generating random key...", key)

**Comment by zyyw** [comment]
as for the info in `src/common/config/store/store.go`, it not plaintext of sensitive info.
BTW, do you mean all of the above info are sensitive info that may need to be updated?
