### ISSUE TITLE
Trivy scan image failed

### ISSUE THREAD

**Issue by kuznetsovkk** [goharbor/harbor#16582]
Hello, I'm using harbor v2.4.1 with internal trivy (--with-trivy)
When I try to scan an image, i get an error log:

`2022-03-24T08:45:48Z [INFO] [/pkg/scan/job.go:385]: {
  "uuid": "3ae6f74e-01a3-11eb-b3f2-0242ac190008",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.20.1",
  "create_time": "2020-09-28T18:56:54.444474Z",
  "update_time": "2020-09-28T18:56:54.444477Z"
}
2022-03-24T08:45:48Z [INFO] [/pkg/scan/job.go:385]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 14,
    "repository": "dockertests/openjdk",
    "tag": "",
    "digest": "sha256:763ecc9f11937fd3af8a9721e65d2481e4e3b230202474d4d387cf373cef86ee",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2022-03-24T08:45:48Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2022-03-24T08:45:48Z [INFO] [/pkg/scan/job.go:222]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1

2022-03-24T08:50:40Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-03-24T08:50:45Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-03-24T08:50:50Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-03-24T08:45:49.844Z	[34mINFO[0m	Using your github token
2022-03-24T08:50:49.843Z	[31mFATAL[0m	scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded
: general response handler: unexpected status code: 500, expected: 200
`

In trivy-adapter.log i see this:

`Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: Appending internal tls trust CA to ca-bundle ...
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: find: '/etc/harbor/ssl': No such file or directory
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: Internal tls trust CA appending is Done.
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: Appending trust CA to ca-bundle ...
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]:  /harbor_cust_cert/storage_ca_bundle.crt Appended ...
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: CA appending is Done.
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: {"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2022-03-23T13:45:02Z","version":"dev"}
Mar 23 16:45:02 192.168.128.1 trivy-adapter[129775]: {"addr":":8080","level":"warning","msg":"Starting API server without TLS","time":"2022-03-23T13:45:02Z"}
Mar 24 11:50:49 192.168.128.1 trivy-adapter[129775]: {"exit_code":1,"image_ref":"core:8080/dockertests/openjdk@sha256:763ecc9f11937fd3af8a9721e65d2481e4e3b230202474d4d387cf373cef86ee","level":"error","msg":"Running trivy failed","std_out":"2022-03-24T08:45:49.844Z\t\u001b[34mINFO\u001b[0m\tUsing your github token\n2022-03-24T08:50:49.843Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","time":"2022-03-24T08:50:49Z"}
Mar 24 11:50:49 192.168.128.1 trivy-adapter[129775]: {"error":"running trivy wrapper: running trivy: exit status 1: 2022-03-24T08:45:49.844Z\t\u001b[34mINFO\u001b[0m\tUsing your github token\n2022-03-24T08:50:49.843Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","level":"error","msg":"Scan failed","time":"2022-03-24T08:50:49Z"}
Mar 24 11:50:50 192.168.128.1 trivy-adapter[129775]: {"error":"running trivy wrapper: running trivy: exit status 1: 2022-03-24T08:45:49.844Z\t\u001b[34mINFO\u001b[0m\tUsing your github token\n2022-03-24T08:50:49.843Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","level":"error","msg":"Scan job failed","scan_job_id":"f4c3a2313ae3467421349c85","time":"2022-03-24T08:50:50Z"}`

**Comment by stonezdj** [comment]
There is an option in Harbor v2.4.2 which you could disable trivy to resolve package online
harbor.yaml
```
offline_scan: true
```

**Comment by zyyw** [comment]
@kuznetsovkk could you try the config mentioned above?

**Comment by kuznetsovkk** [comment]
> @kuznetsovkk could you try the config mentioned above?

I have openned full internet access from harbor node. It fixes this issue. thx
