### ISSUE TITLE
a previous scan all job aleady exits, its status is Running

### ISSUE THREAD

**Issue by kuznetsovkk** [goharbor/harbor#16581]
Hello, I'm using harbor v2.4.1 with internal trivy (--with-trivy)
When I try to scan all images, i get an error: "a previous scan all job aleady exits, its status is Running"
In debug-log-mode I see this error:

`Mar 24 11:39:13 172.27.0.1 core[2002]: 2022-03-24T08:39:13Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"CONFLICT","message":"a previous scan all job aleady exits, its status is Running"}]}`

In database I see this:
```
harbor=# select * from task where vendor_type != 'RETENTION' and status != 'Error' and status != 'Success' and status != 'Stopped';

(0 rows)
```

```
harbor=# select * from schedule where vendor_type != 'RETENTION' and vendor_type != 'GARBAGE_COLLECTION';

(0 rows)
```

Already read this
https://github.com/goharbor/harbor/issues/15338
But it didnt help me.

**Comment by zyyw** [comment]
Hi @kuznetsovkk , will you be able to click the `STOP SCAN` button under `Interrogation Services >> Vulnerability`?

Alternatively, did you try this suggestion: https://github.com/goharbor/harbor/issues/15338#issuecomment-884623020

**Comment by kuznetsovkk** [comment]
> Hi @kuznetsovkk , will you be able to click the `STOP SCAN` button under `Interrogation Services >> Vulnerability`?
> 
> Alternatively, did you try this suggestion: [#15338 (comment)](https://github.com/goharbor/harbor/issues/15338#issuecomment-884623020)

There is no STOP button
![изображение](https://user-images.githubusercontent.com/69850715/160351876-5f0676d8-0963-4224-9ece-37cb3135fbd2.png)

**Comment by kuznetsovkk** [comment]
Fixed with
`UPDATE execution SET status = 'Error' WHERE vendor_type = 'SCAN_ALL' AND status = 'Running';`
hope this wont brake smth else

**Comment by krrishkishore** [comment]
Anyone else faced this issue? I have also tried @kuznetsovkk method, but the execution is changing it's status back to Running not sure from where it is reverting back. Any help would be much appreciated.
