### ISSUE TITLE
Update Helmcharts

### ISSUE THREAD

**Issue by andalam-commscope** [goharbor/harbor#16601]
Hi,
There is no relevant api to upload Helmcharts using Chart File option under Projects.I request you to provide api such that it meets up the said requirement.

Regards,
Seshuphani

**Comment by Vad1mo** [comment]
There is actually. 

see: https://chartmuseum.com/docs/ and see the docs https://goharbor.io/docs/edge/working-with-projects/working-with-images/managing-helm-charts/

**Comment by islinwb** [comment]
> There is actually.
> 
> see: https://chartmuseum.com/docs/ and see the docs https://goharbor.io/docs/edge/working-with-projects/working-with-images/managing-helm-charts/

can't find _relevant api_ to upload Helmcharts in Harbor API 2.0.
