### ISSUE TITLE
Harbor replication policy to be updated

### ISSUE THREAD

**Issue by andalam-commscope** [goharbor/harbor#16600]
Hi,
I am working on harbor v2.0 while creating a replication policy , there is step of creating replication mode pull/push based for which there is no mention in api.Please update the api by including the replication mode under replication policy creation.

Best Regards,
Seshuphani

**Comment by MinerYang** [comment]
This is by design if `src_registry` is null indicate is push based, otherwise is `dest_registry` is null indicated is push-based
