### ISSUE TITLE
Create a Deprecation Policy for Harbor

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/harbor#16607]
**Is your feature request related to a problem? Please describe.**
Our deprecation policy not clear.

**Describe the solution you'd like**
As a user of Harbor, I'd like a clear way to understand how features of Harbor are deprecated. This includes 

* having an opportunity to discuss and give feedback about my use of a feature, and how deprecations will impact me as a user
* easily receive and find information about a feature's deprecation once its been decided to be deprecated
* Be able to read the deprecation policy that will be used for each feature deprecation.

In order to set this up for our community, we should develop a deprecation policy and publish it in the repo. This policy should require things like the following before a feature can be deprecated:

* A proposal is created and accepted by the community in the Community Repo.
* An issue or Github discussion is created where users can provide feedback (if there isn't a proposal)
* Make the community aware of a deprecation proposal via social media, mailing list, community meetings, add to road map, blogs
* Once the deprecation proposal is accepted, it should be scheduled for a release. 
* Update the Harbor docs with information about the deprecation, and any migration steps that are available
* A firm timeframe for how long we will support a feature, once we decide to deprecate something. For example - 1 year, 3 releases, etc.

**Comment by OrlinVasilev** [comment]
@tianon @goharbor/all-maintainers @goharbor/maintainers

**Comment by qnetter** [comment]
This should be discussed at the next community meeting (and un-staled).

**Comment by a-mccarthy** [comment]
looks like @qnetter created a proposal for this, https://github.com/goharbor/community/pull/193.

**Comment by qnetter** [comment]
Completed via https://github.com/goharbor/community/pull/193
