### ISSUE TITLE
gitlab registry cannot be added 

### ISSUE THREAD

**Issue by sysnasri** [goharbor/harbor#16614]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I have a gitlab hosted on-prem I have also enabled gitlab container registry which resides in the same url but on different port something like this registry.example.com:5050, unfortunately when I want to add this registry into harbor it wants to ping the url, as url consist port number, ping does not work thus harbor does not allow to add it. 

**Steps to reproduce the problem:**
add a new gitlab registry on different port rather than 80,443 

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.5.0-rc2
- docker engine version: 20.10.14
- docker-compose version: 1.25.0

**Additional context:**

172.18.0.1 - "POST /api/v2.0/registries/ping HTTP/1.1" 400 74 "https://registry.xxxxxx.com/harbor/registries" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" 0.952 0.952 .

**Comment by Vad1mo** [comment]
how did you enter it in the UI?

**Comment by sysnasri** [comment]
I am entering like this : git.example.com:5050

**Comment by wy65701436** [comment]
did you add the https or http as the prefix?

**Comment by sysnasri** [comment]
I did not added https at first but I have tried that though I know that is not correct protocol. git.example.com:5050 is the correct form.

**Comment by MinerYang** [comment]
Have you succeeded by adding `https` or `http`? If yes, then it is by design.

**Comment by sysnasri** [comment]
It does not work with or without http, https

**Comment by sysnasri** [comment]
It's the same. Actually I have checked every possible options.

**Comment by chlins** [comment]
Could you try to remove access ID and secret and then test again?

**Comment by sysnasri** [comment]
without access ID and secret it works, but is there any point to it? because it cannot authenticate to gitlab!

**Comment by chlins** [comment]
Does your gitlab container registry server deployed by http or https? we should use the actual server protocol as the url prefix and also you could check your access id and secret whether has permission to access gitlab api.

**Comment by sysnasri** [comment]
@chlins, everythingis fine but the main problem is port number, it does not work when I add port in the url! 

Did you read my comments really?

**Comment by chlins** [comment]
@lxShaDoWxl Could you help to verify this issue? Thanks.

**Comment by lxShaDoWxl** [comment]
@sysnasri 
Hi! Show the result of the command from the harbor server
`curl -I -L https://registry.example.com:5050/v2/`

**Comment by sysnasri** [comment]
@lxShaDoWxl 

HTTP/1.1 401 Unauthorized
Server: nginx
Date: Mon, 18 Apr 2022 12:19:18 GMT
Content-Type: application/json
Content-Length: 87
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://git.example.com/jwt/auth",service="container_registry"
X-Content-Type-Options: nosniff

**Comment by lxShaDoWxl** [comment]
@sysnasri give me please harbor log

**Comment by sysnasri** [comment]
@lxShaDoWxl in the first post I have mentioned it.

172.18.0.1 - "POST /api/v2.0/registries/ping HTTP/1.1" 400 74 "https://registry.xxxxxx.com/harbor/registries" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" 0.952 0.952 .

**Comment by lxShaDoWxl** [comment]
this is nginx, need logs core

**Comment by lxShaDoWxl** [comment]
if you runner docker-compose,  the need files in logs/core.log

**Comment by sysnasri** [comment]
@lxShaDoWxl logs are going to rsyslog, are you sure about the path? I could not find it.

**Comment by lxShaDoWxl** [comment]
@sysnasri yes, $GOPATH/src/github.com/goharbor/harbor/logs/ or see make/docker-compose.yml volumes in log services

**Comment by ithesadson** [comment]
I had the same problem, I could not ping the port where the container registry was running. In my case it was because the firewall did not allow that port.

external_url: gitlab.example.com
registry_external_url: gitlab.example.com:5050

The problem was solved when I added the url of Gitlab registry to the firewall.
$ sudo ufw allow 5050
