### ISSUE TITLE
does harbor change project owner when change project member

### ISSUE THREAD

**Issue by lijianfeng1993** [goharbor/harbor#16613]
I have deployed harbor v2.2.1.
(1)create project with user user1， and i can list the project by /api/v2.0/projects&owner=user1， because the project owner is user1.
(2)into the project, and add member user2 and set it as project admin role, then delete member user1. And now, i cannot list the project by /api/v2.0/projects&owner=user2, because the project owner is still user1.

so, if harbor will change project owner when change project member. Even if the user1 is deleted from harbor .does the harbor is still owned by user1. if the project will be a dirty data.

**Comment by wy65701436** [comment]
Yes, it's by designed. The project owner cannot be modified from the initial creation. Reopen it if you have any concern on it.
