### ISSUE TITLE
Replication and two-way TLS

### ISSUE THREAD

**Issue by aceeric** [goharbor/harbor#16617]
I'm attempting to configure replication between Harbor and an external Docker registry that requires two-way TLS. The external registry obtains the CN from the client cert and uses the CN to determine the push/pull entitlements for that CN. So - is it possible to configure replication between Harbor and a registry such that Harbor provides a client cert to the endpoint - i.e. two-way TLS? I can see the "Access Secret" field and some associated documentation for Amazon ECR and Google GCR but no documentation on how to configure this specific use case. Thank you.

**Comment by Vad1mo** [comment]
Harbor does not support client TLS however you can try setup something on the ingress, Nginx or the LB that sits in front of Harbor. It depends on your setup usually. There is plenty of documentation on the net regarding mTLS and how to set it up, so this is not in scope of Harbor.

**Comment by aceeric** [comment]
Thanks - in this scenario, Harbor is the **client**, and the external registry is the entity supporting client TLS.

**Comment by Vad1mo** [comment]
I see. I am afraid Harbor does not support that, the closest thing you could use is https://github.com/ghostunnel/ghostunnel

**Comment by aceeric** [comment]
Thanks.
