### ISSUE TITLE
Tag Population is taking time

### ISSUE THREAD

**Issue by gkarthiks** [goharbor/harbor#16618]
What can we help you?

I have a harbor registry and when I logged into and go to any projects, and click on the image to the list of tags; I get the list of images with the SHA immediately. But I don't see the sematic tag versions immediately. It takes almost about a minute to load those. Was curious to know what's happening there.

Another issue that I am facing is explained here https://github.com/goharbor/harbor/issues/16611

**Comment by wy65701436** [comment]
how many artifacts do you have in your Harbor? And for this particular case, how many tags does this image have?

**Comment by gkarthiks** [comment]
774 container images spread across 38 projects unevenly. The image tag I am trying to list has ~15 tags.

https://user-images.githubusercontent.com/30545166/161632974-7ed17276-9a5c-45d9-9f95-8370c178deb9.mov

**Comment by chlins** [comment]
Which version did you use?

**Comment by gkarthiks** [comment]
v2.4.0

**Comment by chlins** [comment]
Could you check the harbor database load like cpu and memory usage when you open this page?

**Comment by gkarthiks** [comment]
This has been addressed in the versions > 2.4.0 I don't see this anymore in 2.5.0
