### ISSUE TITLE
Sorting on Tags not working

### ISSUE THREAD

**Issue by gwiersma** [goharbor/harbor#16611]
When viewing artifacts in a repo, we can sort the artifacts based on there SHA , size push and pull time. I saw that sorting on tags worked in previous versions. We are currently using version 2.4.2 but sorting on tags doesn't work. Please restore the abillity for sorting on tags.

![image](https://user-images.githubusercontent.com/10595726/160779028-6c5ddacb-1b64-4d3b-a8f0-0dfba16f78a1.png)

**Comment by wy65701436** [comment]
@AllForNothing please have to verify it.

**Comment by AllForNothing** [comment]
@gwiersma Thanks for your info.
Since the tags column is actually an array, it means an artifact may have a lot of tags,  
if artifact A has tags `v0.1.5, v3.4.2`, and artifact B has tags `latest, v0.1.5, v3.4.2`,
We can't think of a reasonable ordering rule for this.
so we decided to remove this functionality.

**Comment by gwiersma** [comment]
Without the functionality it is really hard to find images. We get a lot of complaints regarding this functionality. Wouldn't it be better to filter on the latest version number or latest tag in a Array? For example 

Artifact A with tag stable, v0.1.5, v3.4.2
Artifact B with latest, v0.1.5, v3.4.2

Would result in: 
Artifact B on top because of the latest tag Followed by Artifact A. 

When a Artifact doesnt contain any latest/stable tags just filter on the highest or lowest version number. For example:
Artifact A with tag v0.1.5, v3.4.2
Artifact B with tag v0.1.2, v3.4.3

Would result in:
Artifact B on top because of 3.4.3 followed by Artifact A

Without a tag filter it is almost impossible to find the latest or stable images in large repositories. I rather have a so-so tag filter than none.

**Comment by AllForNothing** [comment]
@gwiersma Understand your concern， but it's complicated to realize an ordering rule for this.
For your use case, you can use the label filter as the workaround

**Comment by srhb** [comment]
Could we not just have a view that has one line per tag (including "none" in case there are artifacts without tags)

This would mirror the docker ux and as such is probably more intuitive to many developers that are used to it:

```
> docker images
REPOSITORY                    TAG    IMAGE ID       CREATED       SIZE
harbor.foo.bar/project/repo   aaaa   eeeeeeeeeeee   2 weeks ago   1.23MB
harbor.foo.bar/project/repo   bbbb   eeeeeeeeeeee   2 weeks ago   1.23MB
harbor.foo.bar/project/repo   cccc   eeeeeeeeeeee   2 weeks ago   1.23MB
```

**Comment by AllForNothing** [comment]
@srhb This can be considered as a feature requirement. If possible,  can you open a new issue and then share your user stories?

**Comment by pycgo** [comment]
Regardless of the complex part, direct and simple Sort by ASCII code is enough, allowing users to have at least one way to sort, rather than removing the sorting directly

**Comment by AllForNothing** [comment]
@pycgo I'm not sure if sorting by ASCII code is possible when querying from DB,  @chlins Any thoughts about this?
