### ISSUE TITLE
960 blobs marked, 0 blobs eligible for deletion

### ISSUE THREAD

**Issue by zzf1208** [goharbor/harbor#16621]
960 blobs marked, 0 blobs eligible for deletion
![image](https://user-images.githubusercontent.com/40556830/160984419-5a12b523-b091-4cd8-8a77-735cbeccd5bc.png)
通过官方方式去手动删除gc，命令如下（To manually delete gc in the official mode, run the following command:）：
docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect /etc/registry/config.yml
但是执行完，依然没有删除，提示（But after the execution, there is still no deletion, prompting） 960 blobs marked, 0 blobs eligible for deletion

**Comment by zzf1208** [comment]
habor is v2.4.2
![image](https://user-images.githubusercontent.com/40556830/160984711-83c4457e-fc1e-41f6-936b-c2111e59a3d6.png)

**Comment by wy65701436** [comment]
If your're using harbor, just trigger GC in Harbor side. And DO NOT execute GC as you mentioned above, refer to https://github.com/goharbor/harbor/issues/12300#issuecomment-647273805

**Comment by KeithTt** [comment]
Any update? disk space still not release even trigger GC in harbor portal.
