### ISSUE TITLE
push 502 Bad Gateway

### ISSUE THREAD

**Issue by tb51cx** [goharbor/harbor#16638]
install command:
helm install harbor harbor/harbor -n ingress-apisix \
--set expose.tls.certSource=secret \
--set expose.tls.secret.secretName=xxxx.xx \
--set expose.type=nodePort \
--set externalURL=https://harbor.xxxx.xx \
--set persistence.resourcePolicy='' \
--set registry.relativeurls=true \
--set redis.type=external \
--set redis.external.addr=xxx.com:6379 \
--set notary.enabled=false

push:
docker login https://harbor.xxxx.xx          
Login Succeeded
docker push harbor.xxxx.xx/library/hello-word
Using default tag: latest
The push refers to repository [harbor.xxxx.xx/library/hello-word]
6b73d082fc93: Retrying in 1 second 
received unexpected HTTP status: 502 Bad Gateway

pod status:
harbor-chartmuseum-775b76d9db-k65rc          1/1     Running   0             15m
harbor-core-6c9dcbd5c5-7krv6                 1/1     Running   0             15m
harbor-database-0                            1/1     Running   0             15m
harbor-jobservice-68d565499d-59s4m           1/1     Running   0             15m
harbor-nginx-7cc84c558c-9qcv7                1/1     Running   0             15m
harbor-portal-d49cc656c-7pxh7                1/1     Running   0             15m
harbor-registry-6644cb67cb-rcsf4             2/2     Running   0             15m
harbor-trivy-0                               1/1     Running   0             15m

harbor-registry logs:

kubectl logs -f  harbor-registry-6644cb67cb-rcsf4 -c registry -n ingress-apisix
172.18.188.205 - - [02/Apr/2022:05:34:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:34:21 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:34:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:34:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:34:31 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:34:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:34:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:34:41 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:34:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:34:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
time="2022-04-02T05:34:44.610719821Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=b498c686-f640-4bec-b334-4f33c78561f3 http.request.method=POST http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/library/hello-word/blobs/uploads/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" vars.name="library/hello-word" 
time="2022-04-02T05:34:44.650127006Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=b498c686-f640-4bec-b334-4f33c78561f3 http.request.method=POST http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/library/hello-word/blobs/uploads/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" http.response.duration=107.6579ms http.response.status=202 http.response.written=0 
172.20.153.104 - - [02/Apr/2022:05:34:44 +0000] "POST /v2/library/hello-word/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \\(linux\\))"
172.20.153.104 - - [02/Apr/2022:05:34:51 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:34:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:34:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:01 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:35:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:11 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
time="2022-04-02T05:35:13.370419695Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=73bb00d6-a851-4358-93ed-7cd1b185d8f5 http.request.method=POST http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/library/hello-word/blobs/uploads/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" vars.name="library/hello-word" 
time="2022-04-02T05:35:13.413641691Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=73bb00d6-a851-4358-93ed-7cd1b185d8f5 http.request.method=POST http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/library/hello-word/blobs/uploads/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" http.response.duration=121.227247ms http.response.status=202 http.response.written=0 
172.20.153.104 - - [02/Apr/2022:05:35:13 +0000] "POST /v2/library/hello-word/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \\(linux\\))"
172.18.188.205 - - [02/Apr/2022:05:35:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:21 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:35:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:31 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:35:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:41 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:35:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:35:51 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:35:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:35:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:01 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:11 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:21 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:23 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:31 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:33 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:41 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:43 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:36:51 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:36:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:36:53 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
time="2022-04-02T05:37:00.671186013Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=070573cf-5f3a-4431-9e02-de781b0dc924 http.request.method=GET http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" 
time="2022-04-02T05:37:00.671264427Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=harbor.xxxx.xx http.request.id=070573cf-5f3a-4431-9e02-de781b0dc924 http.request.method=GET http.request.remoteaddr=123.151.116.110 http.request.uri="/v2/" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=68.052671ms http.response.status=200 http.response.written=2 
172.20.153.104 - - [02/Apr/2022:05:37:00 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \\(linux\\))"
172.20.153.104 - - [02/Apr/2022:05:37:01 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:37:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.18.188.205 - - [02/Apr/2022:05:37:03 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
172.20.153.104 - - [02/Apr/2022:05:37:11 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.188.205 - - [02/Apr/2022:05:37:13 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"

**Comment by tb51cx** [comment]
没有人吗。。。

**Comment by wy65701436** [comment]
hi, please file issue on https://github.com/goharbor/harbor-helm for helm issue, thanks.

**Comment by tb51cx** [comment]
这不是helm的问题啊，502怎么能是helm的问题呢？
