### ISSUE TITLE
Copy images from one project to another in same Harbor Instance

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#16635]
Hi,

Is it possible to copy images from one project to another in Harbor? Currently we are pulling images from one project, then pushing it to another. So we were wondering if there's a replication like feature which will copy images from one project to another in same Harbor Instance automatically.

Thanks

We are currently using Harbor v2.2

**Comment by wy65701436** [comment]
yes, it is. 
![image](https://user-images.githubusercontent.com/2841473/161496688-1963ffee-4e7c-4d75-835e-b2cf54990665.png)

@a-mccarthy we probably can add a section about the artifact copy.
