### ISSUE TITLE
Entire-system scan takes too long

### ISSUE THREAD

**Issue by hasonhai** [goharbor/harbor#16636]
What can we help you?

We have around 1000 images in Harbor and we set the schedule to daily scan the Image for CVE. But it took 10 hours to finish around 150 images, I have to cancel the scan every time to let other people can trigger the single image scan since the scheduled scan was stuck everytimes and let other scan request wait forever in queue. 

The weird thing is that we have another Harbor system with same configuration but with around 6000 images, but it took only 2-3 hours for the full-system scan to complete.

Our installation using harbor-helm version 1.8.1 and harbor version is 2.4.1. Most of the configuration is using default settings.

In the problematic system, I see Trivy complaints about TLS handshake error, but with debug-level verbosity and different level of logs printout, we don't have more error logs about TLS. I checked the TLS setup and saw that all the internal TLS certificates that Harbor component uses are all good and are still valid. 

For "context deadline exceed" error, I already set the time-out for both Trivy executable and Trivy adapter to 1 hour, but still got that error. The images in the problematics Harbor are built from the same pileline with the healthy one.

```
2022/04/01 08:52:37 http: TLS handshake error from 10.42.86.106:57780: EOF
2022/04/01 08:52:57 http: TLS handshake error from 10.42.86.106:57936: EOF
2022/04/01 08:53:02 http: TLS handshake error from 10.42.86.106:57970: EOF
2022/04/01 08:53:12 http: TLS handshake error from 10.42.86.106:58040: EOF
2022/04/01 08:53:12 http: TLS handshake error from 10.42.86.106:58042: EOF
{"exit_code":1,"image_ref":"version-2-2-1-harbor-core:443/admin-private/keycloak@sha256:6ac0126676c6b5eed82bae26fcb38493c2c23e8263e08beef0a77de1bc3aa8c6","level":"error","msg":"Running trivy failed","std_out":"2022-04-01T08:53:12.968Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","time":"2022-04-01T08:53:12Z"}
{"error":"running trivy wrapper: running trivy: exit status 1: 2022-04-01T08:53:12.968Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","level":"error","msg":"Scan failed","time":"2022-04-01T08:53:12Z"}
ERROR: runJob.panic - runtime error: invalid memory address or nil pointer dereference
{"level":"error","msg":"Cannot find scan job","scan_job_id":"02c3ff70911c9fa0137b9dcd","time":"2022-04-01T08:53:15Z"}
2022/04/01 08:53:27 http: TLS handshake error from 10.42.86.106:58174: EOF
{"level":"error","msg":"Cannot find scan job","scan_job_id":"05c3117d7dbcfa3375a62d19","time":"2022-04-01T08:53:30Z"}
{"exit_code":1,"image_ref":"version-2-2-1-harbor-core:443/admin-private/keycloak@sha256:60ecc50402162a2207be08f0c3ac8e90652889ba262cd9e9124dd59016fb65ae","level":"error","msg":"Running trivy failed","std_out":"2022-04-01T09:53:51.740Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","time":"2022-04-01T09:53:51Z"}
{"error":"running trivy wrapper: running trivy: exit status 1: 2022-04-01T09:53:51.740Z\t\u001b[31mFATAL\u001b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","level":"error","msg":"Scan failed","time":"2022-04-01T09:53:51Z"}
ERROR: runJob.panic - runtime error: invalid memory address or nil pointer dereference
```
This Harbor was upgraded many times. From version 2.2.1 and a few other versions, until version 2.4.1. Before 2.4.1, it worked quite well.

**Comment by danielpacak** [comment]
The "timeout: context deadline exceeded" error coming from Trivy indicates that it was not able to scan a container image in 5 minutes, which is the default timeout duration.

There might be different reasons for that. For example, Harbor registry being overloaded and not able to server image layers which are pulled by Trivy before each scan. Or it might be some performance issue in Trivy scanner itself. We cannot tell based on your input.

First off, I'd try increasing the timeout duration and see if the problem persists.

**Comment by hasonhai** [comment]
Thank you. We found the issue.
The TLS handshake was because the jobservice was overloaded so it did not successfully establish TLS connection.
Problem of timeout is because Trivy was trying to access CVE of *.jar and some other sources over internet and stuck there. In later version, we have the offlineScan option, when we enabled it, the scan was functioning fine.
