### ISSUE TITLE
Error 500 when using Proxy cache feature for Azure

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#16637]
What can we help you?

Hi all,

We have set up a Proxy cache connection to a private ACR (xxxx.azurecr.io). When we are trying to pull an image with `docker pull` we are seeing the following issue in the CLI after around 2-3 seconds:
```
docker pull <URL>/<Project>/<Image>:<Tag>
<Tag>: Pulling from <Project>/<Image>
xxxx: Pulling fs layer 
xxxx: Pulling fs layer 
xxxx: Pulling fs layer 
xxxx: Waiting 
error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error
``` 

In our DEBUG logs we can see the following entry:
```
Apr  1 18:10:02 <IP> core[3768]: 2022-04-01T16:10:02Z [DEBUG] [/server/middleware/repoproxy/proxy.go:256]: Failed 
to ensure tag {Repository:<NAME> Reference:<SHA> ProjectName:<NAME> Digest: Tag:<SHA> 
BlobMountRepository: BlobMountProjectName: BlobMountDigest:} , error the artifact is not ready yet, failed to tag it to xxxx
```

We tested the following already:
- Endpoint provider **Azure ACR**
- Endpoint provider **Docker Registry**
- Project Access Level **private**
- Project Access Level **public**

When we are login to the ACR endpoint with our local client and try to pull the image directly, everything is working fine.

Our version of Harbor is **v2.4.0**.

Are you aware of any issues with ACR or using private registries with the Proxy Cache Feature?

Thank you in advance!
<br ><br >

Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Daimler TSS, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by stonezdj** [comment]
The log seems trivial to the http 500 error because it is a background goroutine.
https://github.com/goharbor/harbor/blob/d00024ab36bfb7f2717cffdf973871026d2be743/src/server/middleware/repoproxy/proxy.go#L244
Could please check the full content of the core.log, maybe the HTTP 500 error is returned by the azure registry?

**Comment by stonezdj** [comment]
Is it a fresh install or a upgrade, or in other words, did you see it works in previous version?
the core.log doesn't contain information about the 500 error. could you please upload the proxy.log?

**Comment by AlexBarth13** [comment]
Hi @stonezdj,
We checked with the owner of the ACR to see if we are missing something.
As it is intended from Harbor, the docker pull command have to be like this: `docker pull registry-end-point/proxy-project/repo-name/image:tag`

The concept of Azure CR is a little bit different because they don't have a repository:
https://docs.microsoft.com/en-us/azure/container-registry/media/container-registry-concepts/registry-elements.png

(from: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-concepts)

With this concept in mind and to use the naming of Azure, our docker pull command is `docker pull registry-end-point/proxy-project/repository:artifact`.

Comparison:
`docker pull registry-end-point/proxy-project/repo-name/image:tag`
`docker pull registry-end-point/proxy-project/repository:artifact`

For me this means, the concept of a repository is defined differently in Azure compared to other registries.

Together with the owner of the Azure CR, we tested to change the tag of the image from `repository:artifact` to `name/repository:artifact`. For example: `name/repository:123`.
Than our docker pull command is `docker pull registry-end-point/proxy-project/name/repository:123`. But the issue stayed the same like mentioned in the previous comments.

Furthermore, we tried to add `library` into the docker pull command (`docker pull registry-end-point/proxy-project/library/repository:artifact`), but this wasn't working eiter.

Do you have any idea how we can fix this "problem" and to able to pull the image?

Thanks!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by AlexBarth13** [comment]
Hi @stonezdj and @wy65701436! Thank you for your help yesterday. Today we done the part on our side and now the issue is fixed and we can pull the images from ACR.
Since this is solved, I will close the issue.

Again: Thanks for the great support!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
