### ISSUE TITLE
Database Host Config Change Caused Inability To Pull Via Tags For About Half Of Repositories

### ISSUE THREAD

**Issue by asummers** [goharbor/harbor#16648]
**Expected behavior and actual behavior:**
Okay so this one's a bit of a doozy. If I can provide further details, please let me know, but this is kind of a cry for help brain dump.

Yesterday I attempted to change the database Harbor pointed from one external URL another. This was achieved by changing the lines in https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L773-L774 to point to a host that was running as a WAL follower which was cut over after placing Harbor in read mode and waiting for remaining WALs to propagate and updating config.  This is an older 1.x harbor that has been brought through necessary migrations to get to its current 2.x version, so not a fresh install.

After the migration we noticed that about 50% (anecdotally) of the images lost some sort of tag repository artifact combination, but the data was available in both old and new databases and had been for quite a while. This resulted in:
1) Inability to pull to specific repositories via tag, with errors about "repository XYZ/ABC not found"
2) Repository UI populated with red error banner messages about "repository XYZ/ABC not found", similar to 1) but SHAs and unable-to-be-pulled tags were visible on page next to SHAs. 
3) Upon pushing new images to the supposedly not found repositories, banner went away, but the UI resulted in duplicate URLs for repository and other tagged images remained unable to be pulled
4) Remaining ability to push/pull to all repositories via sha256 id for all images
5) Repositories not affected did not have UI banner or any errors

During course of debugging, all harbor pods were restarted so no remaining connection strings or similar should have been remaining; this was haphazardly verified in original database which showed no active connections and it was later shut down to ensure that, resulting in no errors or changed behavior.

After changing config back to old DB, all UI errors went away and pull worked as normal. Looking into DBs, everything appeared as expected according to my understanding of the data model as expressed in Postgres in their artifact tag repository relationships.

My question for you all is... what happened? How is this data model set up here, because it's something outside of the database given the associations all existed as expected. This feels like some sort of caching issue given only some of the repositories experienced this, but I'm not sure what happened to be able to do anything beyond speculate.

And what else do I need to do to change databases besides change DB URL? I could not find documentation around this to treat it special and do some sort of cache flush or similar, if I am correct with my speculation. 

**Steps to reproduce the problem:**
Not done on clean environment
1) Place harbor in read mode
2) Change external DB url to different external DB url
3) Take harbor out of read mode

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x] 2.3.0

**Additional context:**

- **Harbor config files:** Happy to provide relevant parts if necessary.
- **Log files:** You can get them by package the `/var/log/harbor/` . We have some of these at debug level, happy to share anything that is helpful.

We did not see a ton of helpful logs at info level and after turning on debug logs, only found a few possible ones:
```
2022-04-03T19:19:36Z [DEBUG] [/server/v2.0/handler/util.go:81]: field RepositoryName not found in ListRepositoriesParams
2022-04-03T19:19:36Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require list action for resource /project/217/repository
```

**Comment by asummers** [comment]
Swapping a different Harbor instance to point to same DB resulted in same behavior of missing repositories, so this is consistent on our end, and I have something I can poke. Clearing Redis with FLUSHALL did not seem to help anything here, beyond expectedly making me log in again. With Redis out of the picture, I can't explain this behavior using my understanding of harbor's architecture and moving parts.

**Comment by MinerYang** [comment]
Please kindly check if the original db is consistent with current one.

**Comment by asummers** [comment]
The DB is consistent with the original one. It was restored via base backup and is a WAL follower that was caught up. The DB has the tag/repo/artifact data that something (Harbor core?) is claiming is missing.

**Comment by asummers** [comment]
Given that the DB is consistent with the one it's pulling from, and that wiping Redis did not fix this, what might explain my behavior?
