### ISSUE TITLE
Upgrading harbor 2.1 to latest results in broken "legacy" robot accounts

### ISSUE THREAD

**Issue by tszyszko** [goharbor/harbor#16649]
**Expected behavior and actual behavior:**
Latest harbor should authenticate "legacy" robot accounts.

**Steps to reproduce the problem:**
Create new VM
Install latest harbor (we are using puppet to do this)
Copy over /data to ensure same database, secret dir.
Start harbor
Normal users can authenticate, robot users are present in db (displayed as legacy robot accounts)
However when logging in with a robot account, core attempts to authenticated with LDAP, and then basic auth (no logs from security/robot.go). New robot accounts work fine.

**Versions:**
- harbor version: v2.4.2-ef2e2e56
- docker engine version: 20.10.14
- docker-compose version: [z.z.z]

**Additional context:**
Apr  4 17:17:51 172.31.0.1 core[4724]: 2022-04-04T17:17:51Z [WARNING] [/core/auth/ldap/ldap.go:72]: Not found an entry.
Apr  4 17:17:53 172.31.0.1 core[4724]: 2022-04-04T17:17:53Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="" requestID="" user agent="docker/20.10.12 go/go1.16.12 git-commit/459d0df kernel/4.18.0-348.7
.1.el8_5.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \(linux\))"]: failed to authenticate user:robot$****, error:Failed to authenticate user, due to error 'Not found an entry'
Apr  4 17:18:06 172.31.0.1 core[4724]: 2022-04-04T17:18:06Z [WARNING] [/core/auth/ldap/ldap.go:72]: Not found an entry.
Apr  4 17:18:08 172.31.0.1 core[4724]: 2022-04-04T17:18:08Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="" requestID="" user agent="docker/20.10.12 go/go1.16.12 git-commit/459d0df kernel/4.18.0-348.7
.1.el8_5.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \(linux\))"]: failed to authenticate user:robot$****, error:Failed to authenticate user, due to error 'Not found an entry'

**Comment by Vad1mo** [comment]
legacy robot account were deprecated in 2.4, see https://github.com/goharbor/harbor/releases/tag/v2.4.0

**Comment by piyush94** [comment]
@Vad1mo, just a thought, deprecated in software doesn't mean that functionality is removed rather that it is discouraged from being used further. The language should've been more clear in the release notes to say that it has been removed instead of deprecated.
_"Deprecated technologies are technologies which have been replaced by newer technologies. Features typically get marked as "deprecated", rather than simply removed, in order to provide backward compatibility for software users."_

**Comment by qnetter** [comment]
As new PM for Harbor, I will be proposing (via @OrlinVasilev as proxy, since meetings are in the middle of the night for me) a formal deprecation and removal process that means what you expect it to mean, under which a feature is removed at least a specified number of releases after its deprecation is announced. It will be up to the community to accept, reject, or amend it.

**Comment by piyush94** [comment]
@qnetter Thanks!

**Comment by horihel** [comment]
Hi guys - sorry for being late: Could you _please_ add this to the release notes.

Our upgrade procedure actually relies on reading release notes to see which features we use might be removed. The fact that legacy robots are 
- not marked as removed
- still mentioned in the documentation

let us believe they were still working.

Please put up a warning if you _know_ something is broken and you don't intent to fix it.

**Comment by OrlinVasilev** [comment]
@horihel @piyush94 - note taken, release notes fixed with the right wording, but I think you are still facing that same issue?
If it's that the case do you need further support on that matter ?

**Comment by horihel** [comment]
we're already scrambling to replace all robot accounts all morning.
with the other option being a downgrade & DB rollback we figured we might as well go forward now and fix it the good & painful way.

and we'll be much much more careful with future harbor updates.

**Comment by naveenb29** [comment]
ran into same issue that @horihel  mentioned  , had to replace all these accounts.

**Comment by horihel** [comment]
@OrlinVasilev I couldn't help but notice that the current documentation still mentions robot accounts as "deprecated but working" when they in fact are not working at all: https://goharbor.io/docs/2.5.0/working-with-projects/project-configuration/create-robot-accounts/#legacy-robot-accounts
Additionally I couldn't find any mention in the release notes (at least 2.5.0+) - maybe I looked at the wrong place.

I'm praying to the dieties of e2e testing that you hopefully don't pull of the same strategy with chartmuseum support :/

**Comment by wy65701436** [comment]
The legacy robots have been deprecated from v2.4, please refer to https://github.com/goharbor/harbor/releases/tag/v2.4.0.

We should update the doc accordingly.

**Comment by horihel** [comment]
hi @wy65701436 
thank you for pointing it out. Please allow me to correct you: they have been removed at least as of 2.5.0
