### ISSUE TITLE
Trivy scan timing out in an air-gapped environment

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16654]
Hi,
We have deployed Harbor setup using the installer Harbor version: 2.4.0. Since ours is an air-gapped environment, we had set the skipUpdate to true in our harbor.yml file and downloaded the Trivy DB to the container using [https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment]

Our vulnerability type is both SCANNER_TRIVY_VULN_TYPE=os,library.

For some of our images, we are observing the Trivy scan is failing. We tried increasing the timeout from 5 minutes to 60 minutes (max value we could specify), but the scan still times out.

On enabling debug mode for the logs, we found that the scan is trying to download some files from the Internet and it is failing due to the environment inaccessible to the Internet. Please find below sample logs:

`https://search.maven.org/solrsearch/select?q=1%3A%2268babcdaf59c9225459d4284bb45cd61c1da1f28%22\u0026rows=1\u0026wt=json\", \"timeout\": \"5m0s\", \"remaining\": 1}\n2022-04-02T15:18:14.234Z\t\u001b[35mDEBUG\u001b[0m\trequest failed\t{\"error\": \"Get \\\"https://search.maven.org/solrsearch/select?q=1%3A%22a8b5db3ba7a573104d851cf0cdf51b824514ac85%22\u0026rows=1\u0026wt=json\\\": Forbidden\", \"method\": \"GET\", \"url\": \"https://search.maven.org/solrsearch/select?q=1%3A%22a8b5db3ba7a573104d851cf0cdf51b824514ac85%22\u0026rows=1\u0026wt=json\"}\n2022-04-02T15:18:14.234Z\t\u001b[35mDEBUG\u001b[0m\tretrying request\t{\"request\": \"GET https://search.maven.org/solrsearch/select?q=1%3A%22a8b5db3ba7a573104d851cf0cdf51b824514ac85%22\u0026rows=1\u0026wt=json\", \"timeout\": \"5m0s\", \"remaining\": 1}\n2022-04-02T15:18:14.282Z\t\u001b[35mDEBUG\u001b[0m\trequest failed\t{\"error\": \"Get \\\"https://search.maven.org/solrsearch/select?q=1%3A%22f915fd7341a436c398227e743f0639af6fd35685%22\u0026rows=1\u0026wt=json\\\": Forbidden\", \"method\": \"GET\", \"url\": \"https://search.maven.org/solrsearch/select?q=1%3A%22f915fd7341a436c398227e743f0639af6fd35685%22\u0026rows=1\u0026wt=json\"}\n2022-04-02T15:18:14.282Z\t\u001b[35mDEBUG\u001b[0m\tretrying request\t{\"request\": \"GET https://search.maven.org/solrsearch/select?q=1%3A%22f915fd7341a436c398227e743f0639af6fd35685%22\u0026rows=1\u0026wt=json\", \"timeout\": \"5m0s\", \"remaining\": 1}\n2022-04-02T15:23:12.571Z\t\u001b[31mFATAL\u001b[0m\tscan error:\n    github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout\n        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:71\n  - image scan failed:\n    github.com/aquasecurity/trivy/pkg/commands/artifact.scan\n        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:216\n  - failed analysis:\n    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact\n        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:98\n  - analyze error:\n    github.com/aquasecurity/fanal/artifact/image.Artifact.Inspect\n        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/artifact/image/image.go:105\n  - timeout:\n    github.com/aquasecurity/fanal/artifact/image.Artifact.inspect\n        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20211014152324-29fbacfbfca4/artifact/image/image.go:175\n  - context deadline exceeded\n","level":"error","msg":"Scan failed","time":"2022-04-02T15:23:12Z"}

If we try to run the scan by specifying vulnerability type just as os, the scan completes successfully in 3-4 minutes

Could you please help on how to resolve this issue? Is there any other file we need to download in offline mode other than trivy.db and metadata.json?

Thanks and Regards,
Inderpreet.

`

**Comment by InderpreetSaini** [comment]
Adding to my earlier issue, I searched through the harbor github issues and found that this is a known issue and has been fixed in Harbor 2.4.2.

So I am trying now to upgrade my existing Harbor setup from 2.4.1 to 2.4.2. 

As part of upgrade, I brought down the containers running 2.4.1 using docker-compose down -v and then ran the install.sh command to bring the harbor up with the same data folder /data , but running harbor v2.4.2

After the upgrade completed, I am trying to scan an image by setting the skipupdate to true and offline_scan to true as well.

But getting the below error now. Could you please if  there are some additional steps that need to be done?

`2022-04-06T12:39:37Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; `version=1.1]
`2022-04-06T12:39:37Z [INFO] [/pkg/scan/job.go:222]: Get report for mime type: application/vnd.security.vulnerability.report; `version=1.1
`2022-04-06T12:39:39Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; `version=1.1 is not ready yet, retry after 5 seconds
`2022-04-06T12:39:44Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type `application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-04-`06T12:39:41.169Z	[31mERROR[0m	The local DB has an old schema version which is not supported by the current version `of Trivy CLI. It needs to be updated.
`2022-04-06T12:39:41.169Z	[31mFATAL[0m	DB error: database error: validate error: --skip-update cannot be specified `with the old DB schema
`: general response handler: unexpected status code: 500, expected: 200

**Comment by zyyw** [comment]
Hi @InderpreetSaini , I scp-ed /data/trivy-adapter/trivy/db generated from on harbor instance1 2.4.2 (skip_update=false && offline_scan=false, then do a scan, the `/data/trivy-adapter/trivy/db` will be automatically generated) to the air-gapped harbor instance2 2.4.2 (skip_update=true && offline_scan=true). 
Then, do a scan on the air-gapped harbor instance2, it errors out with the following error message: 
```
2022-04-11T09:39:26Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2022-04-11T09:39:26Z [INFO] [/pkg/scan/job.go:222]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2022-04-11T09:39:28Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-04-11T09:39:33Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-04-11T09:39:29.352Z	[31mFATAL[0m	DB error: error in vulnerability DB initialize: failed to open db: open /home/scanner/.cache/trivy/db/trivy.db: permission denied
: general response handler: unexpected status code: 500, expected: 200
```
And the I followed this:
* https://github.com/aquasecurity/harbor-scanner-trivy/issues/98#issuecomment-613467729
did:
```
chown -R 10000:10000 /data/trivy-adapter
```
And finally, a scan can be executed successfully on the air-gapped harbor instance2 without error.

**Comment by InderpreetSaini** [comment]
Thanks @zyyw for the feedback.

The issue I am facing is while upgrade from Harbor 2.4.1 to Harbor 2.4.2. The Trivy Adapter version has been upgraded to 0.26.0 and Trivy has also been upgraded to 0.24.2. 

Earlier we were using the [](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment) to download the Trivy DB in an airgapped environment. But now after upgrade, the DB downloaded from this link is not compatible with the newer version of the Trivy.

So my query is - Is there another link/documentation/steps recommended by Harbor to download the Trivy db that is compatible with the newer versions of Trivy and Trivy Adapter in an airgapped environment, so that we can include the steps as part of our SOP?

**Comment by zyyw** [comment]
> Is there another link/documentation/steps recommended by Harbor to download the Trivy db that is compatible with the newer versions of Trivy and Trivy Adapter in an airgapped environment
Not to my knowledge. A workaround would be install a harbor 2.4.2 instance1 from scratch and the do a scan in the newly installed harbor instance1, the trivy.db will be downloaded after the scan is completed. Then, you can copy the trivy.db from harbor instance1 over to the air-gapped environment (the env which upgrading 2.4.1 to 2.4.2).

**Comment by zyyw** [comment]
@InderpreetSaini found this: https://aquasecurity.github.io/trivy/v0.17.0/air-gap/
hope it's helpful to you.

**Comment by InderpreetSaini** [comment]
> @InderpreetSaini found this: https://aquasecurity.github.io/trivy/v0.17.0/air-gap/ hope it's helpful to you.

Thanks @zyyw. I will try that
