### ISSUE TITLE
ldap_search_pwd with special char

### ISSUE THREAD

**Issue by rajivece** [goharbor/harbor#1665]
I'm trying to setup  harbor ldap authentication with ldap_search_pwd having special character '#' at the end. User login fails with "Invalid credentials".

Please find the configurations and log details below

1)Version of docker engine and docker-compose.

> docker version: 1.12.2
> docker-compose version: 1.11.2
> 

2)Config files of harbor

> auth_mode = ldap_auth
> ldap_url = ldap://ldapserverip:3268
> ldap_searchdn = admin@example.com
> ldap_search_pwd = "xxxxxxx#"
> ldap_basedn = OU=doamin,DC=example,DC=com
> ldap_filter = (objectClass=person)
> ldap_uid = sAMAccountName
> ldap_scope = 3

3)Log files,  /var/log/harbor/ui.log

> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [DEBUG] [authenticator.go:57]: Current AUTH_MODE is ldap_auth
> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [DEBUG] [ldap.go:53]: ldapURL:ldap://ldapserverip:3268
> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [DEBUG] [ldap.go:64]: baseDn:OU=domain,DC=example,DC=com
> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [DEBUG] [ldap.go:68]: Search DN: admin@example.com
> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [DEBUG] [ldap.go:72]: Bind search dn errorLDAP::Bind() error (49) : Invalid credentials
> Mar 20 12:36:33 172.18.0.1 ui[20896]: 2017-03-20T07:06:33Z [ERROR] [base.go:186]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials

**Comment by reasonerjt** [comment]
This should be no longer valid as the ldap password will be set via UI dashboard.
