### ISSUE TITLE
The robot account cannot replicate charts in pull replication

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#16667]
**Expected behavior and actual behavior:**
I configured pull based replication from one harbor registry to second. I would expect that it will work correctly and will fetch all resources (images, charts, custom artifacts). 
It does not work at all if robot account is used and `All` or `charts` resources are selected in resource filter. Replication fails and there is a message:
```failed to fetch charts: http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"robot$my-robot-account"}]}```.
In such case no objects are copied because this error is thrown on the beginning of replication process and no logs are available.
It will fail even if registry does not contain any Helm Charts. If I use user account, then it works.

**Steps to reproduce the problem:**
1. Have two Harbor registries.
2. In first registry, create a robot account with all available permissions (either project robot account or system robot account).
3. In second registry, configure endpoint and pull based replication for whole project (name: project-name/**).
4. Execute replication.

**Versions:**
- harbor version: 2.4.1
- Bitnami harbor helm chart version: 12.0.0

**Additional context**
This is how it is displayed in UI (id 97 is with robot account, 98 is a user with no permissions to a replicated project):
<img width="1714" alt="replication" src="https://user-images.githubusercontent.com/20277750/162146264-3aa4f4e9-d4fa-4697-aab6-a5033d40ea22.PNG">

**Comment by nikcollins** [comment]
+1 Same scenario, trying to replicate helm charts with a robot account

**Comment by hasanhakkaev** [comment]
+1 same issue with pull.
We have also similar issue with push replication. Artifacts are being pushed successfully, but not the charts.
The robot users on both Harbors have full permissions. 
Harbor version 2.5.0 
Official helm chart v.1.9.0

![image](https://user-images.githubusercontent.com/14126525/163343081-3966c42a-f9dd-46b6-b512-e62b6bbef3b0.png)

**Comment by YangJiao0817** [comment]
This is by design.

**Comment by nikcollins** [comment]
@YangJiao0817 Can you please help us understand why robot accounts are not appropriate for replication? It seems robot accounts can be configured with all of the permissions required to replicate. Why require replication to be within the context of a user account?

**Comment by hasanhakkaev** [comment]
Little update from my side:
As stated above, replication for artifacts works as expected. Speaking of helm chart replication, they are relatively small in size and we didn't find a reason why we would need the charts replicated to each Harbor instance we have/use.
So we set only the artifact replication for both pull and push rules. As @YangJiao0817 said, maybe this is the reason for the design being so.

**Comment by YangJiao0817** [comment]
You can use this payload system robot account for chat replication.
All permissions for the system robot account are not displayed on the UI, you need to call the API to create or edit it
```
{
   "name":"test6",
   "duration":30,
   "description":null,
   "disable":false,
   "level":"system",
   "permissions":[
      {
         "kind":"project",
         "namespace":"chart",
         "access":[
            {
               "resource":"repository",
               "action":"list"
            },
            {
               "resource":"repository",
               "action":"pull"
            },
            {
               "resource":"repository",
               "action":"push"
            },
            {
               "resource":"repository",
               "action":"delete"
            },
            {
               "resource":"artifact",
               "action":"read"
            },
            {
               "resource":"artifact",
               "action":"list"
            },
            {
               "resource":"artifact",
               "action":"delete"
            },
            {
               "resource":"artifact-label",
               "action":"create"
            },
            {
               "resource":"artifact-label",
               "action":"delete"
            },
            {
               "resource":"tag",
               "action":"create"
            },
            {
               "resource":"tag",
               "action":"delete"
            },
            {
               "resource":"tag",
               "action":"list"
            },
            {
               "resource":"scan",
               "action":"create"
            },
            {
               "resource":"scan",
               "action":"stop"
            },
            {
               "resource":"helm-chart",
               "action":"read"
            },
            {
               "resource":"helm-chart",
               "action":"list"
            },
            {
               "resource":"helm-chart-version",
               "action":"create"
            },
            {
               "resource":"helm-chart-version",
               "action":"read"
            },
            {
               "resource":"helm-chart-version",
               "action":"list"
            },
            {
               "resource":"helm-chart-version",
               "action":"delete"
            },
            {
               "resource":"helm-chart-version-label",
               "action":"create"
            },
            {
               "resource":"helm-chart-version-label",
               "action":"delete"
            }
         ]
      }
   ]
}
```
