### ISSUE TITLE
Add a way to rename or prefix a Chart replicated

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#16673]
**Is your feature request related to a problem? Please describe.**
I replicate https://artifacthub.io/packages/helm/istio-official/base in a Harbor project (not dedicated to istio...).
so, when the chart is replicated to the harbor projet, the name of the chart is "base"...

**Describe the solution you'd like**
I would like a way to prefix it or rename it

**Describe the main design/architecture of your solution**
have a field "prefix" or "rename" in the "Destination" part :
![image](https://user-images.githubusercontent.com/11298399/162439083-492bde7a-2c45-44f1-9cb1-7398667cb23f.png)

**Describe the development plan you've considered**
/

**Additional context**
/

**Comment by MinerYang** [comment]
This is not only contains in the project name but also in the yaml file, so it is not reasonable.
