### ISSUE TITLE
chartrepo/index.yaml : 400 Bad Request

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16676]
[root@sc-master1 work]# helm repo add consoce http://192.168.2.250:443/chartrepo/chartrepo  --username=admin --password=Harbor12345
Error: looks like "http://192.168.2.250:443/chartrepo/chartrepo" is not a valid chart repository or cannot be reached: failed to fetch http://192.168.2.250:443/chartrepo/chartrepo/index.yaml : 400 Bad Request

**Comment by zyyw** [comment]
Hi, what the Harbor version and helm version you were using?
