### ISSUE TITLE
用户名或者密码不正确。

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16681]
helm部署的harbor2.3.5，登录出现用户名或者密码不正确。
[root@sc-master1 ~]# 
[root@sc-master1 ~]# kubectl -n harbor  get pods
NAME                                    READY   STATUS    RESTARTS   AGE
harbor-chartmuseum-84c55c747f-w4srq     1/1     Running   0          11h
harbor-core-6646c69db6-twmrs            1/1     Running   1          11h
harbor-database-0                       1/1     Running   0          11h
harbor-exporter-766f8677db-97v26        1/1     Running   0          11h
harbor-jobservice-549f8dccbd-7l42f      1/1     Running   1          11h
harbor-nginx-956fff988-2wwhm            1/1     Running   0          11h
harbor-notary-server-f978f6665-4kkmt    1/1     Running   0          11h
harbor-notary-signer-6ccc865df9-zx5vw   1/1     Running   0          11h
harbor-portal-5766b784c7-68cnh          1/1     Running   0          11h
harbor-redis-0                          1/1     Running   0          11h
harbor-registry-56dc95bd8c-bdwk5        2/2     Running   0          11h
harbor-trivy-0                          1/1     Running   0          11h
nfs-proversitioner-7b4c6cc9bf-s48ld     1/1     Running   1          20h
[root@sc-master1 ~]# 
[root@sc-master1 ~]# kubectl -n harbor  get svc
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
harbor                 NodePort    10.100.70.255    <none>        80:30002/TCP,4443:30004/TCP   11h
harbor-chartmuseum     ClusterIP   10.108.148.242   <none>        80/TCP                        11h
harbor-core            ClusterIP   10.99.159.102    <none>        80/TCP,8001/TCP               11h
harbor-database        ClusterIP   10.105.113.174   <none>        5432/TCP                      11h
harbor-exporter        ClusterIP   10.98.83.86      <none>        8001/TCP                      11h
harbor-jobservice      ClusterIP   10.106.17.141    <none>        80/TCP,8001/TCP               11h
harbor-notary-server   ClusterIP   10.100.240.242   <none>        4443/TCP                      11h
harbor-notary-signer   ClusterIP   10.100.182.39    <none>        7899/TCP                      11h
harbor-portal          ClusterIP   10.103.150.159   <none>        80/TCP                        11h
harbor-redis           ClusterIP   10.99.46.170     <none>        6379/TCP                      11h
harbor-registry        ClusterIP   10.103.252.133   <none>        5000/TCP,8080/TCP,8001/TCP    11h
harbor-trivy           ClusterIP   10.108.22.88     <none>        8080/TCP                      11h
日志正常

**Comment by Jeremy-boo** [comment]
Can you provide some more specific descriptive information? For example, the values.yml used when deploying Harbor, and the logs related to harbor-core when the password is incorrect when logging in?

**Comment by joesdu** [comment]
i use install.sh deploy harbor the default password is Harbor12345,but is always wrong

**Comment by ggjjlldd** [comment]
I have same problem, why?

**Comment by joesdu** [comment]
> I have same problem, why?

Do not change the default password in the configuration file during the deployment phase, wait for a successful boot, then log in to the system and change the password.
