### ISSUE TITLE
docker push new image: Layer already exists 

### ISSUE THREAD

**Issue by zhuchance** [goharbor/harbor#16689]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The mirror repository failed to update the mirror,When I docker push after the prompt.
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/3828352/162857728-20075f36-5d1c-4c22-9f1d-aea7d0e4a6ca.png">

**Steps to reproduce the problem:**
```bash
#docker build -t harbor.xx.cn/dev/auth:v8
#docker push  harbor.xx.cn/dev/auth:v8

77877a4f60b4: Pushed 
29b8aa47e3b4: Pushed 
ceaf9e1ebef5: Layer already exists 
9b9b7f3d56a0: Layer already exists 
f1b5933fe4b5: Layer already exists 
```
**Versions:**
centos7,  kernelVersion: 5.17.0-1.el7.elrepo.x86_64
- harbor version: [v2.4.2-ef2e2e56]
- docker engine version: [20.10.9]
- docker-compose version: [1.24.0,]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
Harbor No error log!

**Comment by Vad1mo** [comment]
this is correct behavior. 

Those layer seem to be common between `v8` and previous versions eg. `v7 or v6. or...`

````
ceaf9e1ebef5: Layer already exists 
9b9b7f3d56a0: Layer already exists 
f1b5933fe4b5: Layer already exists 
````

see https://blogs.cisco.com/developer/container-image-layers-1 to understand how docker image layers work.
