### ISSUE TITLE
Weird behaviour after deleting user that owns projects

### ISSUE THREAD

**Issue by creker** [goharbor/harbor#16693]
**Expected behavior and actual behavior:**
Administrator is able to delete any user even if it owns projects. Completely preventing deleting such users is probably too much but I would expected Harbor to better handle that case. Instead every time I go into projects previously owned by deleted user harbor-core logs `the owner of project test is not found, owner id is #`. Everything appears to be working fine but there's no option to set another user as owner.

**Steps to reproduce the problem:**
1. Login as any user
2. Create a project
3. Login as other administrator user
4. Delete the user from step 1
5. Go to a list of projects or open the project that was created at step 2
6. Observe `the owner of project test is not found, owner id is #` in harbor core logs. 

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.5.0]
- docker engine version: [20.10.14]
- docker-compose version: [1.29.2]

**Comment by MinerYang** [comment]
This is a default behavior. `owner` itself means the one who create it.

**Comment by creker** [comment]
I undertand the logic but I don't think it's correct to keep spamming logs with that message. I don't really care that project has no owner. I just don't want to see these messages. Especially when all our logs are collected in centralized store.

**Comment by wy65701436** [comment]
we can set the log level to debug to avoid noise, @MinerYang
