### ISSUE TITLE
Proxy projects not showing images when pulled through multiple projects

### ISSUE THREAD

**Issue by mdraijer** [goharbor/harbor#16695]
**Expected behavior and actual behavior:**

Execute `docker pull myharbor/docker-hub-project-one/library/ubuntu` and `docker pull myharbor/docker-hub-project-two/library/ubuntu` (make sure you remove and prune the local image between the two pulls, to make sure that the image is really pulled the second time, through the second proxy project).

Expected behaviour: in both situations the image gets pulled without error; in the UI both projects show the image.

Actual behaviour: in both situations the image gets pulled without error; in the UI only project `docker-hub-project-one` shows the image, project `docker-hub-project-two` does not show the image.

Consequence: in project `docker-hub-project-two` it is not possible to inspect e.g. the CVE's of the image.

**Steps to reproduce the problem:**

Execute `docker pull myharbor/docker-hub-project-one/library/ubuntu` and `docker pull myharbor/docker-hub-project-two/library/ubuntu` (make sure you remove and prune the local image between the two pulls, to make sure that the image is really pulled the second time, through the second proxy project).

**Versions:**

- harbor version: v2.4.2-ef2e2e56

**Additional context:**

We have setup Harbor in a multi tenant fashion, so each customer gets their own Docker Hub proxy project. Customers reported that they do not see images although they _are_ pulling it through their proxy project. Especially they reported that they are not able to see the list of CVE's.

**Comment by creker** [comment]
I'm on 2.5.0 and can't reproduce this. Both images show up. Maybe this is related to #15591 ? ubuntu is multiarch image which triggers a bug in Harbor where it doesn't register image tag being pulled through. This is fine until GC is triggered which will remove these images as their layers are not connected to any tag. Try checking other images that are not multiarch.

**Comment by stonezdj** [comment]
I cannot reproduce it in my env

**Comment by mdraijer** [comment]
We tested this by pulling on two different laptops, by two different persons. Best way to test it without the help of other people seems to me to do a `docker image prune` in between.

The Ubuntu image is just an example. We see the behaviour with many images, although they might be extensions of ubuntu of course.
