### ISSUE TITLE
I can't delete users while OIDC enabled

### ISSUE THREAD

**Issue by ehsansh84** [goharbor/harbor#16696]
I connected keycloak to harbor. I want to change auth mode to local database.
As I read [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj06ZH2p5D3AhXEOuwKHSgdAbIQFnoECAkQAQ&url=https%3A%2F%2Fgithub.com%2Fgoharbor%2Fharbor%2Fissues%2F2169&usg=AOvVaw0BMYX1UpPWT3-eSEwnnBQ_) I have to delete users from keycloak. I don't have access to my keycloak now. What should I do to change auth mode to database?

I'm using Harbor Version v2.3.3-a0a9ed8a

**Comment by Vad1mo** [comment]
You should delete **users in Harbor** (db table harbor_users) not in the IDP.  Delete all entries except **admin** and **anonymous**. then you can switch to OIDC.
