### ISSUE TITLE
GDPR compliant user deletion

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#16697]
**Is your feature request related to a problem? Please describe.**
It is possible to delete regular DB auth users and, since 2.4 also OIDC users. 

However, the performed deletion process is not GDPR compliant, as users are only **marked** as deleted and the DB still contains user identifiable data.

> The General Data Protection Regulation (GDPR) gives individuals the right to ask for their data to be deleted and organizations have an obligation to do so, except in the following cases:  

> the personal data your company/organisation  holds is needed to exercise the right of freedom of expression;
> there is a legal obligation to keep that data;
> for reasons of public interest (for example public health, scientific, statistical or historical research purposes).

**Describe the solution you'd like**
When anonymizing the user, we should replace the user identifiable data with its CRC. Although the user is not identifiable anymore, it is still possible to reconstruct user's action if the original user details still exist in an external system. E.g. HR system, for example.   

Currently, if the user is “deleted”, this happens internally in the system. 

- The user entry in DB is flagged as deleted
- The unique fields (username, email) are renamed, where the user `id` e.g.  `#num` is appended.

### Expected Result

- [ ]  Username replaced with its CRC + appended id e.g. `0xB76F0E6B#12`
- [ ]  Email replaced with its CRC + appended id
- [ ]  Replace real name replaces with CRC

**Describe the development plan you've considered**
We can provide such an implementation

**Additional context**
none

**Comment by sluetze** [comment]
You may want to make this feature optional, since some companies might need the username in their central SIEM to detect anormalies in user(account) behavior.

furthermore it might be harder for a administrator to analyse login-issues of a specific user (i.e. by grabbing logfiles/DB-Entries), if he is unaware of the hashing method.
