### ISSUE TITLE
push Images to hardor  is very slow 

### ISSUE THREAD

**Issue by xla145** [goharbor/harbor#16706]
The push refers to repository [192.168.110.241:5013/library/py-visual-model]
4383dfb2c377: Layer already exists 
3e04a574ce40: Pushed 
3de045e5b5c5: Layer already exists 
5d0cd94a4058: Layer already exists 
194b4899f27f: Retrying in 1 second 
c550c119fa51: Layer already exists 
f2cf7a7fa3c1: Layer already exists 
13d953676298: Layer already exists 
529389f36be8: Layer already exists 
b2cb1b47face: Layer already exists 
23b148f59e7a: Layer already exists 
8502864ee4ed: Pushed 
c1b0c1ead143: Layer already exists 
c023cf8fe796: Layer already exists 
b5694bda03f5: Layer already exists 
4b4c002ee6ca: Layer already exists 
cdc9dae211b4: Layer already exists 
7095af798ace: Layer already exists 
fe6a4fdbedc0: Layer already exists 
e4d0e810d54a: Layer already exists 
4e006334a6fd: Layer already exists 
EOF

push is fail

**Comment by Vad1mo** [comment]
can you provide more information and context?
