### ISSUE TITLE
双向复制失败

### ISSUE THREAD

**Issue by lixiaopengy** [goharbor/harbor#16707]
Docker Compose version v2.4.1
Docker version 19.03.4
Harbor version v2.4.2
PostgreSql 13.3.0

I share one redis and one postgres13 for two harbor image warehouses。
I copied the key of image warehouse A to image warehouse B。
The current situation is that the replication rules I configured have also passed the verification, but there is a problem with the mirrored data during replication. The replication rules show 100% success, and the log also shows that there is a copy. But my mirror data does not generate replication data。

The test cases are as follows:
I uploaded an nginx image on harbor1, and the configuration rules pushed the data on harbor1 to harbor2. Similarly, I pull the data on harbor1 in harbor2。
![image](https://user-images.githubusercontent.com/65278402/163675791-df2e1744-055b-422c-ad90-7143aacd2482.png)

![image](https://user-images.githubusercontent.com/65278402/163675979-5d98a939-d7da-4b2a-b204-5b8d732edd7e.png)

![image](https://user-images.githubusercontent.com/65278402/163676000-546a4ce6-4824-4bfb-8231-e3a2242f1971.png)

![image](https://user-images.githubusercontent.com/65278402/163676177-63dac63b-d94d-42a8-9a9c-a8fde1b54e14.png)

![image](https://user-images.githubusercontent.com/65278402/163676031-62862ef7-1321-438e-a076-3c273d6a5ee9.png)

![image](https://user-images.githubusercontent.com/65278402/163676036-e9f55790-cb82-4b3a-95e8-0aef4c0318ef.png)

Thank you for your help. If you need screenshots of other logs, please contact me

**Comment by chlins** [comment]
You share the one postgresql for two harbors, so when replication between the harbor1 and harbor2, you can see from job logs which print `... already exists on the destination registry, skip`, because harbor will check blob whether exist before replicate and harbor2 shares the same database volume so it has the blob record as same as harbor1, so these blob not be replicated in fact.

**Comment by lixiaopengy** [comment]
> 

Yes, I read the source code of harbor and found that the condition of data replication is that there is no BLOB data in the other party's database. Thank you for your help
