### ISSUE TITLE
安装启动成功后，重启主机，再重启harbor，harbor-db无法正常启动

### ISSUE THREAD

**Issue by misterluck** [goharbor/harbor#16713]
harbor2.5.0在安装成功后，重启主机，再使用docker-compose启动harbor
harbor-db无法正常启动

docker-compose ps

      Name                     Command                       State                              Ports                   
------------------------------------------------------------------------------------------------------------------------
harbor-core         /harbor/entrypoint.sh            Up (health: starting)                                              
harbor-db           /docker-entrypoint.sh 96 13      Restarting                                                         
harbor-jobservice   /harbor/entrypoint.sh            Up (health: starting)                                              
harbor-log          /bin/sh -c /usr/local/bin/ ...   Up (healthy)            127.0.0.1:1514->10514/tcp                  
harbor-portal       nginx -g daemon off;             Up (healthy)                                                       
nginx               nginx -g daemon off;             Up (healthy)            0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp
redis               redis-server /etc/redis.conf     Up (healthy)                                                       
registry            /home/harbor/entrypoint.sh       Up (healthy)                                                       
registryctl         /home/harbor/start.sh            Up (healthy)

docker logs 1b49d8aaa3b5
Error response from daemon: configured logging driver does not support reading

**Comment by chlins** [comment]
Could you try to run following scripts to restart harbor?
```
setenforce 0
systemctl start systemd-journald
systemctl status systemd-journald

docker-compose down
docker-compose up -d
```

**Comment by happywzy** [comment]
> 
```
Error response from daemon: configured logging driver does not support reading
```
重启就会报错，我也遇到了，谁也不能保证服务安装之后不会重启吧.

**Comment by misterluck** [comment]
[postgresql.log](https://github.com/goharbor/harbor/files/8629009/postgresql.log)

harbor-db的日志，是容器内的权限问题。
ls: cannot access '/var/lib/postgresql/data': Operation not permitted
![image](https://user-images.githubusercontent.com/30618801/166870690-07439d41-95ae-450d-9897-0aba003e5566.png)

**Comment by misterluck** [comment]
![image](https://user-images.githubusercontent.com/30618801/166872896-66c20da6-e913-4dc0-9c06-50ad26a7d983.png)
由于没有权限造成了shell脚本报错
ls: cannot access '/var/lib/postgresql/data': Operation not permitted

**Comment by canliuxiade2** [comment]
> 

一样的问题，你解决了吗

**Comment by 631068264** [comment]
> [postgresql.log](https://github.com/goharbor/harbor/files/8629009/postgresql.log)
> 
> harbor-db的日志，是容器内的权限问题。 ls: cannot access '/var/lib/postgresql/data': Operation not permitted ![image](https://user-images.githubusercontent.com/30618801/166870690-07439d41-95ae-450d-9897-0aba003e5566.png)

你是怎么看到日志的。。。。docker logs 直接报错

**Comment by zsinba** [comment]
有解决了吗？

**Comment by feiyue2008** [comment]
简单方式是，将原/data/database （默认路径）备份并清空，然后重新安装即可。

**Comment by zsinba** [comment]
> 简单方式是，将原/data/database （默认路径）备份并清空，然后重新安装即可。

重新安装后， 直接不用了。 继续使用内部的registry 2.8.1了。

重新安装倒是方便，但是以前的都丢了。

**Comment by atzq1234** [comment]
privileged: true
