### ISSUE TITLE
harbor unauthorized: unauthorized to access repository

### ISSUE THREAD

**Issue by zlwzlwzlw** [goharbor/harbor#16724]
harbor:2.3.5
deploy: docker-compose
harbor.yml
hostname: 192.168.33.92
http:
  port: 7002

external_url: https://mirror123.acmg.com

and **use nginx for proxy (harbor -> nginx)**
problem: login Succeeded but when push met "unauthorized: unauthorized to access repository: library/redis, action: push: unauthorized to access repository: library/redis, action: push"

**Comment by chlins** [comment]
Could you provide token in request?

**Comment by fanmaoyang** [comment]
Encountered the same problem

**Comment by phantooom** [comment]
the same problem 

v2.4.2 in k8s

nginx(https) -> ingress(http)-> harbor

**Comment by phantooom** [comment]
nginx add this config  solved.
proxy_set_header X-Forwarded-Proto https;

**Comment by wyaopeng** [comment]
unauthorized: unauthorized to access repository:

**Comment by wyaopeng** [comment]
like this
`location / {
      proxy_pass http://10.6.1.1:80;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http:// $scheme://;
  }`

**Comment by wyaopeng** [comment]
location / {
      proxy_pass http://10.6.1.1:80;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http:// $scheme://;
  }

**Comment by wyaopeng** [comment]
you can like this !

**Comment by wyaopeng** [comment]
you  can like this !
location / {
      proxy_pass http://192.168.33.92:7002;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect http:// $scheme://;
  }
