### ISSUE TITLE
helm harbor is not a valid chart repository or cannot be reached: object required

### ISSUE THREAD

**Issue by w7089** [goharbor/harbor#16727]
### Discussed in https://github.com/goharbor/harbor/discussions/16725

<div type='discussions-op-text'>

<sup>Originally posted by **w7089** April 20, 2022</sup>
I've successfully pushed some locally built helm chart to harbor private helm registry using below commands:

```
helm registry login private.harbor.com
helm push chart-version.tgz oci://private.harbor.com/some-project
```

Now I fail to add helm repo (for the goal of installation of the pushed helm chart) using below commands:

```
$ helm repo add helm-test2 oci://private.harbor.com/some-project/
Error: looks like "oci://private.harbor.com/some-project/" is not a valid chart repository or cannot be reached: object required
$ helm repo add helm-test2 oci://private.harbor.com/some-project/helm-test-repo
Error: looks like "oci://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: object required
$ helm repo add helm-test2 https://private.harbor.com/some-project/helm-test-repo
Error: looks like "https://private.harbor.com/some-project/helm-test-repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
$ helm repo add helm-test2 https://private.harbor.com/some-project
Error: looks like "https://private.harbor.com/some-project" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
```

How to `helm repo add` Harbor OCI helm repository?

It's important to note that docker images are stored alongside pushed helm charts at  `private.harbor.com/some-project/`.

Alternative way that worked is uploading helm chart under `Helm charts` tab in `some-project` in Harbor UI. 

Afterwards, below commands for adding and installing the chart worked:

```
helm repo add helm-test https://private.harbor.com/chartrepo/some-project
helm repo update helm-test
helm install chart helm-test/chart --version 1.5.0
```

I would use this method, but have no idea how to push to `https://private.harbor.com/chartrepo/some-project`, pushing to `oci://...` worked only after following [this][1] github link.

  [1]: https://github.com/goharbor/harbor/issues/13170</div>

**Comment by chlins** [comment]
You can refer to helm docs.

**Comment by w7089** [comment]
@chlins. Yes, that's what succeeded.

What failed is `helm repo add` after successful push

**Comment by openstep** [comment]
https://github.com/goharbor/harbor/issues/18720
