### ISSUE TITLE
"Prevent vulnerable images from running" is broken

### ISSUE THREAD

**Issue by jsolbrig** [goharbor/harbor#16732]
As the title says, "Prevent vulnerable images from running" is broken. It works fine for images that have been scanned, but there are times that images can make it into the registry without being scanned. For example, if you set up a project to act as a "proxy cache" for Docker Hub, the first time you pull an image it will be successfully delivered to you regardless of its vulnerabilities.

Note: I am aware of #16218 but it contains multiple issues, is not clear, and was causing confusion.

**Expected Behavior**
Say I set up a project to be a proxy cache for Docker Hub:
![image](https://user-images.githubusercontent.com/1684491/164564756-418e9b0a-bae5-4bcb-84ac-aac5027a4f36.png)

Then I set that project to "Prevent vulnerable images from running", "Automatically scan images on push", and an empty allowlist:
![image](https://user-images.githubusercontent.com/1684491/164566045-fc553043-c025-4fbc-93e7-5d01b4a2a770.png)

I would expect that Harbor would then protect me from pulling images that contain vulnerabilities above "Low".

**Observed Behavior**
However, once I have set things up as shown above, if I then pull an image from Docker Hub through my proxy cache, the image will pull successfully:
```
> docker pull my-registry/test/rancher/mirrored-coreos-etcd:v3.5.3
v3.5.3: Pulling from rancher/mirrored-coreos-etcd
dbba69284b27: Pull complete
7aafad10ecdb: Pull complete
f495bd50cdec: Pull complete
13d34bcbe78f: Pull complete
bb931e01bb50: Pull complete
a3f9b9b98618: Pull complete
93a8b8e7955a: Pull complete
Digest: sha256:a1011f42ce95738fea37d0693a7cb34826c1f7d0301ea14de4c300735377d8e4
Status: Downloaded newer image for my-registry/test/rancher/mirrored-coreos-etcd:v3.5.3
my-registry/test/rancher/mirrored-coreos-etcd:v3.5.3
```

It pulls despite containing vulnerabilities. This can be seen by navigating to the specific image in Harbor which shows that the image has critical vulnerabilities:
![image](https://user-images.githubusercontent.com/1684491/164565280-e3d2d519-9ec9-40e2-80ee-cf467adcbd34.png)

As would be expected, a second pull attempt results in the image being blocked:
```
> docker pull my-registry/test/rancher/mirrored-coreos-etcd:v3.5.3
v3.5.3: Pulling from rancher/mirrored-coreos-etcd
unknown: current image with 77 vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "Low" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist.
```

**Steps to reproduce the problem:**
- In Harbor, set up a project as a proxy cache for Docker Hub as shown above.
- Set the new project to "Prevent vulnerable images from running", "Automatically scan images on push", and an empty allowlist.
- Attempt to pull `rancher/mirrored-coreos-etcd:v3.5.3` as shown above.
  - This will succeed incorrectly.
- Attempt to pull a second time.
  - This will fail as expected.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.1]
- docker engine version: [20.10.11]

**Comment by stonezdj** [comment]
It is by design, the current proxy cache just proxy the request to the remote server, there is no cache of the image in the Harbor, then it is possible to scan the image.  that is why it allows the user to pull images the first time, but might failed to pull it the second time. the cache process is after the initial pull request.

**Comment by sacrificeme** [comment]
It means that actually, it does not prevent anything :(

**Comment by jsolbrig** [comment]
@stonezdj Sorry for being slow about getting back to this. After thinking about this more, I can see why this would be done by design.  

It would be very helpful if something were added to the documentation discussing this limitation and the reasons for it. Basically, no, Harbor can't protect you from images that are pulled via a pull-through cache. It can only protect you against images that have been in Harbor long enough to be scanned.

Do you have any suggestions on how to mitigate having unscanned images get pulled into a cluster? I suppose it's simply an issue of pre-pulling needed images, but this limitation largely makes the pull-through cache unusable for me. Maybe there is a good admission controller that would be helpful for people to look at? Maybe there is a workflow that can help mitigate this issue?

**Comment by AYDEV-FR** [comment]
Up 👍

**Comment by LeeWong** [comment]
Up pls

**Comment by sacrificeme** [comment]
This bug waking up our on-call security engineers quite often, so they need to quickly whitelist CVE just to not fold down production which will be unable to spin new pod.

**Comment by nipil** [comment]
> It is by design, the current proxy cache just proxy the request to the remote server, there is no cache of the image in the Harbor, then it is impossible to scan the image. that is why it allows the user to pull images the first time, but might failed to pull it the second time. the cache process is after the initial pull request.

So i understand the current flow is

1. receive pull
2. fetch & serve image (maybe streaming layers, i do not know)
3. store image in cache
4. scan image in cache

Might i ask why this processing flow could not be inverted ?

1. receive pull
2. fetch image
3. store image in cache
4. scan image in cache
5. serve image

As it "seems" that only the sequence of operation is modified, from a 1000 feet view, it seems doable.

Of course, this would lead to pull failures until the image is scanned, but for us, this **would indeed be** the desired behaviour

So, this is the reason (no scan before serving) that we do not use proxy-cache anywhere in our setup (currently using 2.12.1)
