### ISSUE TITLE
Make time format configurable

### ISSUE THREAD

**Issue by lindhe** [goharbor/harbor#16730]
**Is your feature request related to a problem? Please describe.**

When I inspect the repositories in a project, they are listed with a "Last modified time" column. The timestamps are using the American format to display time and date, which is very confusing to the rest of the world.

**Describe the solution you'd like**

I think the time and date formats should be locale sensitive. Either by automatically getting that information from the user's browser, or making it configurable by the user. And if any format is the default, it should clearly be the unambiguous, international date standard ISO 8601.

**Describe the main design/architecture of your solution**

This is how I think the date format should be determined:

1. Each user should be able to select their desired date format through a profile setting.
2. If the user has not set their desired date format in their profile, the format should be inferred from the web browser's locale settings.
3. If neither option above can be determined, Harbor should use a format configured to be the default by system administrators.
4. If all else fails, use ISO 8601.

**Describe the development plan you've considered**

Do I look like a guy with a plan?

**Additional context**

!["Last modified time" column with unintelligible dates](https://user-images.githubusercontent.com/7773090/164436681-572acd44-b249-4c8b-9c32-4f2b0e5be68c.png)

**Comment by AllForNothing** [comment]
@lindhe Thanks for your good suggestion.
Currently, the time format is consistent with the selected language.
If you select `English`, it uses the `en-us` format, if you select s`中文简体`， it uses the `zh-cn` format...
It is odd to show a B format in an A language, so, for this requirement, I think the best solution is to contribute your language to Harbor https://goharbor.io/docs/2.5.0/build-customize-contribute/developer-guide-i18n
What do you think？

**Comment by SimonAlling** [comment]
> Currently, the time format is consistent with the selected language.
> If you select `English`, it uses the `en-us` format, if you select `中文简体`， it uses the `zh-cn` format...
> It is odd to show a B format in an A language

In my opinion, that argument implies a stronger relation between language and date format than is arguably the case in reality. For example, [English (United Kingdom) and English (United States) use different date format conventions](https://docs.oracle.com/cd/E19455-01/806-0169/overview-7/index.html). At the very least, one could argue that Harbor's display name for `en-us` should therefore be **English (United States)** or **English (US)**, not just **English**.

In any case, a given language – especially without a country specifier, but even with one – does not necessarily use only one single date format. For example, in Swedish, both **2022-04-27** and **27 april 2022** are commonly used, depending on context and/or personal preference.

> so, for this requirement, I think the best solution is to contribute your language to Harbor https://goharbor.io/docs/2.5.0/build-customize-contribute/developer-guide-i18n
> What do you think？

I don't think that is a good solution. Translating Harbor to Swedish would require an immense amount of time and effort on our side, and we don't want Harbor to be displayed in Swedish anyway. We are perfectly happy with the _English language_; we just want to avoid the very confusing, ambiguous, non-standard _US date format_.

Windows, macOS and most Linux distributions allow the user to specify date and time format independently of language, so it's not an extraordinary feature we're suggesting.

**Comment by AllForNothing** [comment]
@SimonAlling 
Not quite sure if it's worth doing as I'm not sure if this is a common case. If you don't mind, you can directly modify the source code, then rebuild your Harbor intance:

**Comment by AllForNothing** [comment]
@qnetter Can you have a look at this? Then decide whether we should merge the PR #16796 or not

**Comment by dioguerra** [comment]
I are also interested in having the ability to change time format. Can you please give one more chance to this issue? @AllForNothing @lindhe
