### ISSUE TITLE
db  error

### ISSUE THREAD

**Issue by freemankevin** [goharbor/harbor#16734]
![b47c2396cb960caf21b21c2bc43ff98](https://user-images.githubusercontent.com/71524776/164756956-8b44d985-9926-40c1-8e88-6d68b62c9903.png)

After manually stopping it, and then re-up -d the pg database still executes the initialization script, which leads to abnormal startup. Isn't this an obvious bug? How could it be designed like this.

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/164951916-8539867e-af1c-4551-a758-2a183a24ec03.png)
This was started in the early morning yesterday, and I don't know when it hung up by myself.

**Comment by wy65701436** [comment]
can you go into the running DB container to execute `ls -A $PGDATA`? And please show the output.

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/165210596-d898663e-c1a0-4ef0-b4de-5cec31028718.png)

Now it is normal that harbor-db is abnormal first, and other services follow the exception. If I use docker-compose and cannot restore its state in time, this should be a problem.

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/165215240-c592af45-f0ff-493d-833d-811c315fdf69.png)
![image](https://user-images.githubusercontent.com/71524776/165215296-e64fc5f2-138e-4a46-9008-61fb20a7875b.png)

mirror image size。

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/165909057-f7df7f73-b3aa-495b-b754-6dfae58c13b3.png)
There is also a problem of self-starting after booting. If the machine is powered off and then powered on and then restarted, the harbor state is abnormal. It should be the problem of the deployment script, which is very passive.
