### ISSUE TITLE
1.10.7升级导致奇怪的本地化“SCANNER.SCANNER” 

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16735]
从haror version 1.18.6升级到harbor version 1.10.7后，登录Harbor UI出现以下异常：
![image](https://user-images.githubusercontent.com/88759374/164958279-cd4c4ebf-bc50-496a-b646-ac4cf80d2b08.png)

**Comment by AllForNothing** [comment]
Clean your browser cache and reload
