### ISSUE TITLE
Unable to use CSRF token on API

### ISSUE THREAD

**Issue by OlivierFrancais** [goharbor/harbor#16744]
I'm trying to add a label on an artifact using the API, but I unable to figure it out how to use CSRF token, and the documentation doesn't say anything.

Harbor version : v2.4.2-ef2e2e56
I'm using python 3.9.7 and requests 2.26.0 
Project admin user credentials.

```
client = requests.session()
registry_auth = ('admin', 'key')

payload = {'scope': "p", 'project_id':3, 'name':'Mylabel'}
r = client.get(f'https://{registry}/api/v2.0/labels', params=payload, auth=registry_auth )
r = client.post(f'https://{registry}/api/v2.0/projects/skypodsystem-integ/repositories/manifest/artifacts/{digest}/labels', json={'id':r.json()[0]['id']}, auth=registry_auth, headers={'X-Harbor-Csrf-Token': r.headers['X-Harbor-Csrf-Token']} )

```

I do a first GET call for a label, but I'm not able to do the POST, I've always a 401 error UNAUTHORIZED

If I do the same calls with the same credentials with swagger UI, it works, but it constantly fail on POST

**Comment by chlins** [comment]
The CSRF token is only used for UI and there is no need to add CSRF token header when you call API(example: `curl -u admin:key https://harbor.com/api`).

**Comment by OlivierFrancais** [comment]
If I don't send the CSRF Token but I use the same session including the cookie, I have a 403  FORBIDDEN 403 CSRF token invalid
If I don't use any session, no cookie and no CSRF token but the basic auth I have 401 UNAUTHORIZED

**Comment by OlivierFrancais** [comment]
No, I have juste few call to do.

**Comment by chlins** [comment]
CLI secret can not be used for API calling, you need to use admin account as basic auth or idtoken from OIDC provider as bearer token, you can refer to https://github.com/goharbor/harbor/wiki/Harbor-FAQs#api for more information.

**Comment by OlivierFrancais** [comment]
Ok, with a bearer token. It work's than you
