### ISSUE TITLE
The tag retention policy, whether it can be implemented according to the push version, to retain the number of recently pushed images.

### ISSUE THREAD

**Issue by boy461205160** [goharbor/harbor#16746]
The purpose of tag retention strategy is to achieve the retention of the feature and develop versions of the mirrors in the polarbear-pop-server-deploy warehouse, respectively. From the effect of the simulation operation, the effect to be achieved is not achieved. The result is arranged in the order of time push, and the total number of images is retained. 5.
It is not as expected. To achieve the expected purpose, adjust the total number of reserved tags, but another problem arises. Imagess are generated through gitlab c submission every day. The number of the above versions is inconsistent, there may be more features than develop, or develop: More than featue.
I don't know if there is a good way to do it.

![2](https://user-images.githubusercontent.com/25784013/165203137-7bbdd5d4-5755-46df-825e-4f4087f91d38.png)
![1](https://user-images.githubusercontent.com/25784013/165203145-808ef86c-0d75-4a71-9d1c-aa16138c7b3b.png)

**Comment by boy461205160** [comment]
Some people raised similar doubts, but unfortunately did not solve the problem

https://github.com/goharbor/harbor/issues/11822

**Comment by AllForNothing** [comment]
@boy461205160 For your user case, you can use 3 rules to meet your requirement.
Rule1:  Repos  match  `polarbear**`,   retain the latest 5 pushed images, tags match `feature-*`
Rule2:  Repos  match  `polarbear**`,   retain the latest 5 pushed images, tags match `release-*`
Rule3:  Repos  match  `polarbear**`,   retain the latest 5 pushed images, tags match `develop-*`

**Comment by boy461205160** [comment]
First of all thank you very much for your answer
I tested it and the validation rule works for my needs. The test results are shown in the attached screenshot, but there are also new questions, which are listed on the picture, please answer your doubts, thank you very much
![1](https://user-images.githubusercontent.com/25784013/165214938-b06dd6ad-0f28-4e1c-b9a8-e4eceba1a0eb.png)
![2](https://user-images.githubusercontent.com/25784013/165214955-a9026f51-ee81-4b5c-b790-1f2d9e508b5d.png)
![3](https://user-images.githubusercontent.com/25784013/165214971-e2962eef-7371-4f28-b940-9e7544f77257.png)
.

**Comment by AllForNothing** [comment]
@boy461205160 This is a known bug, see #15488 for details.

**Comment by boy461205160** [comment]
I saw it in another sync instance. The version of the habro instance is 2.3.5. After a few days of follow-up observation, if there is no abnormality, the issue will be closed and marked as resolved. Thank you so much for answering this question so quickly.
![4](https://user-images.githubusercontent.com/25784013/165221885-621f9607-6779-4e13-9639-bcce03bee8cd.png)

**Comment by boy461205160** [comment]
re

**Comment by boy461205160** [comment]
Reslove
