### ISSUE TITLE
tag保留策略，能否实现按push版本，保留最近推送个数。

### ISSUE THREAD

**Issue by boy461205160** [goharbor/harbor#16745]
tag保留策略，能否实现按push版本，保留最近推送个数。

![2](https://user-images.githubusercontent.com/25784013/165200608-a21765c0-8dad-40aa-a2e6-2024c79e078d.png)
![1](https://user-images.githubusercontent.com/25784013/165200625-f25d950d-2aa1-4edf-be6f-da0f3bbe82b6.png)

**Comment by AllForNothing** [comment]
duplicated with #16746
