### ISSUE TITLE
Can't return project labels with API

### ISSUE THREAD

**Issue by jclgithub01** [goharbor/harbor#16755]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When I query a project with the v2.0 API, I expect to see any project labels added to the project. What I actually see is:

```
bash-4.2# curl -s -u ${harbor_user}:${harbor_password} -X GET "https://${harbor_host}/api/v2.0/projects/approved" | jq -r
{
  "chart_count": 177,
  "creation_time": "2019-10-30T13:29:59.000Z",
  "current_user_role_ids": null,
  "cve_allowlist": {
    "creation_time": "0001-0-01T00:00:00.000Z",
    "items" [],
    "project_id": 15,
    "update_time": "0001-0-01T00:00:00.000Z"
  },
  "metadata": {
    "auto_scan": "true",
    "enable_content_trust": "false",
    "prevent_vul": "false",
    "public": "true",
    "retention_id": "4",
    "severity": "low"
  },
  "name": "approved",
  "owner_id": 11,
  "owner_name": "somedude",
  "project_id": 15,
  "repo_count": 203,
  "update_time": "2019-10-30T13:29:59.000Z"
}
```

  

**Steps to reproduce the problem:**
Run the above API query against a project.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.3.2-6b6c21da
- docker engine version: 20.10.8
- docker-compose version: 1.18.0

**Additional context:**

I need to designate target projects as part  of a utility I am creating

**Comment by AllForNothing** [comment]
@jclgithub01  
You need to call `https://${harbor_host}/api/v2.0/labels?scope=p&project_id=${project_id}` to get the project labels
