### ISSUE TITLE
Legacy robot account and TLS certificate renewal.

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#16756]
Hi,

We recently upgraded Harbor from 2.1 to 2.2 and we are seeing legacy robot accounts now. I wanted to know if Harbor uses TLS certificate secret to authenticate legacy robots or not? If they do, is it safe to renew the tls certificate, since it's nearing its expiration. We still use legacy robot accounts in production.

Current version: Harbor 2.2
Deployed on k8s

Edit:
https://github.com/goharbor/harbor/issues/12085

This seems to be related. Will a certificate renewal cause this problem?

**Comment by Vad1mo** [comment]
TLS isn't used for robot accounts. You can rotate your TLS Cert.
