### ISSUE TITLE
Proxy cache project using AWS ECR Public Gallery

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16754]
Hi,

I am trying to set up a new registry endpoint in Harbor 2.5.0, which would serve the proxy cache project that will pull images from the public AWS registry https://gallery.ecr.aws.

But when I test the connection by specifying the provider as AWS ECR in the UI, it fails the Test connection check. Please find below the screenshot. Is there a way to use AWS ECR provider to pull images from public gallery?

![image](https://user-images.githubusercontent.com/17871520/165305758-f941bb32-6280-4765-9ed5-3f5815237f35.png)

I am not providing any credentials as docker pull from the public gallery does not ask for credentials.  Tried with other AWS region endpoint URLs as well, but no luck.

**Comment by stonezdj** [comment]
Try to select it as docker registry and use the same endpoint url
