### ISSUE TITLE
Can't compile Harbor locally

### ISSUE THREAD

**Issue by wilmardo** [goharbor/harbor#16757]
**Expected behavior and actual behavior:**
When running make install it starts a Harbor instance like describes here:
[https://goharbor.io/docs/2.5.0/build-customize-contribute/compile-guide/#compiling-and-running](https://goharbor.io/docs/2.5.0/build-customize-contribute/compile-guide/#compiling-and-running)

But instead it errors since it tries to get `https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry` which returns a 404.
I want to contribute a patch but without a proper local build to test it feels not right to submit.

It seems that @mac-chaffee has issues as well: https://github.com/goharbor/harbor/pull/16642

**Steps to reproduce the problem:**
```
# make install

 => => naming to docker.io/goharbor/harbor-registry-base:dev                                                                                                                                             0.0s
download  https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
make[1]: *** [_build_registry] Error 1
make: *** [build] Error 2
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [main]
- docker engine version: [20.10.13]
- docker-compose version: [2.3.3]

**Comment by AllForNothing** [comment]
@wilmardo You need to add the `BUILDBIN=true` param, like:
`sudo make install BUILDBIN=true COMPILETAG=compile_golangimage CHARTFLAG=true TRIVYFLAG=true NOTARYFLAG=true`

**Comment by wy65701436** [comment]
and I've set the BUILDBIN=true as the default, refer to https://github.com/goharbor/harbor/pull/16763.
