### ISSUE TITLE
Bump up beego to 2.x

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#16762]
Investigate bump up beego to 2.x.
given to current situation, we plan to upgrade beego v1 to github.com/beego/beego/v2@v2.0.5 or above
Although use the official tools like `bee`to upgrade
<img width="1285" alt="Screen Shot 2022-08-26 at 1 37 32 PM" src="https://user-images.githubusercontent.com/44956229/186829879-305e4949-2884-4798-b06d-03dd0fdd5fc7.png">
There are still some dependency and functions we need to fix them manually allover the code base as below
<img width="926" alt="Screen Shot 2022-08-26 at 1 28 40 PM" src="https://user-images.githubusercontent.com/44956229/186830098-2ddf29a3-3313-42b6-9f04-e38e20eed624.png">

Mainly related to bellowing sub-module
```
github.com/beego/beego/cache => github.com/beego/beego/v2/client/cache

github.com/beego/beego/orm => github.com/beego/beego/v2/client/orm

github.com/beego/beego/validation => github.com/beego/beego/v2/core/validation

github.com/beego/beego/session => github.com/beego/beego/v2/server/web/session

github.com/beego/beego/context =>  github.com/beego/beego/v2/server/web/context

```
**Tasks:**
- https://github.com/goharbor/harbor/pull/17478
- https://github.com/goharbor/harbor/issues/17568
- https://github.com/goharbor/harbor/issues/17569
- https://github.com/goharbor/harbor/issues/17570
- https://github.com/goharbor/harbor/issues/17571
- https://github.com/goharbor/harbor/issues/17572

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/17801.
