### ISSUE TITLE
Loading slow when open the page of Replication Executions

### ISSUE THREAD

**Issue by tedgxt** [goharbor/harbor#16764]
Harbor Version : 2.1.5

We've got 360,000 records in replications executions，leads to time cost when opening the page of replications executions. 
Should I delete some records in database? or sth I can do to optimize it.

**Comment by chlins** [comment]
You could upgrade harbor to 2.2+, there will be a background worker to clean the execution records when create replication task. Also, you could delete those executions manually with Success/Error status if your harbor can't be upgraded.
