### ISSUE TITLE
can harbor use ipv6 connect redis, pgsql?

### ISSUE THREAD

**Issue by wayilau** [goharbor/harbor#16778]
What can we help you?
As the title said, i want to use ipv6 on my env. but connected failed  when harbor connect to redis and pgsql.

**Comment by MinerYang** [comment]
Yes, actually I have done with this test these days and  install harbor using harbor-helm on a dualstack-ipv6-primary k8s cluster with a external redis / pgsql , it works as expected.
Dose your harbor work properly on your environment with internal redis/pgsql?
Could you pls provide the logs of pods?

**Comment by wayilau** [comment]
OK, I will test again. Thanks a lot. @MinerYang

**Comment by MinerYang** [comment]
Hi @wayilau,

Np and I tested on harbor v2.4.2  which would be harbor-helm v1.8.2.
I would close the issue this time and welcome you to update more.

Best,
Miner
