### ISSUE TITLE
在使用ubuntu系统安装成功harbor后，网页版进行仓库连接的时候显示连接失败是为什么 

### ISSUE THREAD

**Issue by guoqianru** [goharbor/harbor#16781]
What can we help you?
![image](https://user-images.githubusercontent.com/70872381/165890480-80556081-850b-4020-b9d1-7734a1418cff.png)

**Comment by chlins** [comment]
Please provide more information such as API response details and harbor logs.

**Comment by guoqianru** [comment]
> 请提供更多信息，例如 API 响应详细信息和港口日志。

请问你说的是怎么看呢

**Comment by guoqianru** [comment]
在centos的系统是可以正常连接，但是ubuntu的系统不行

**Comment by chlins** [comment]
You could use `docker logs {harbor-core-containerid}` for docker-compose installation and `kubectl logs {harbor-core-pod-name}` for helm installation.

**Comment by guoqianru** [comment]
![image](https://user-images.githubusercontent.com/70872381/167329053-a08b3d41-addd-4eef-bb13-4ced11826548.png)

**Comment by guoqianru** [comment]
所有的服务是正常的，
