### ISSUE TITLE
Update Documentation/harbor.yml.tmpl

### ISSUE THREAD

**Issue by REHICode** [goharbor/harbor#16788]
Hi,

I was trying to install harbor with trivy in an air gapped environment.
I also have a mounted partition so I changed the default data_volume to: /srv/harbor_storage
./install.sh --with-trivy
This went great until I tried to scan an image in my registry.

**Expected behavior and actual behavior:**
In the harbor.yml.tmpl:78:
/home/scanner/.cache/trivy/db
Expected this to work ...

*Actual path needed*:
/srv/harbor_storage/trivy-adapter/trivy/db
*actual permissions needed*:
chown -R 10000:10000 /srv/harbor_storage/trivy-adapter/trivy/db

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
- download https://github.com/goharbor/harbor/releases/download/v2.5.0/harbor-offline-installer-v2.5.0.tgz
- extract into /opt directory
- cp /opt/harbor/harbor.yml.tmpl /opt/harbor/harbor.yml
- edit /opt/harbor/harbor.yml
1. 47  data_volume: /srv/harbor_storage
2. 79    skip_update: true
3. 87    offline_scan: true
- mkdir -p /srv/harbor_storage
- cd /opt/harbor
- ./install.sh --with-trivy
- log into harbor webui and try scanning an image

**Versions:**
Please specify the versions of following systems.

- Ubuntu 20.04 LTS
- harbor version: [2.5.0]
- docker engine version: [docker-ce                             5:20.10.14~3-0~ubuntu-focal]

So basically the first error you get without internet connection:
2022-04-29T08:22:41.197Z	[31mFATAL[0m	DB error: database error: --skip-update cannot be specified on the first run
When I put the offline Trivy DB into /srv/harbor_storage/trivy-adapter/trivy/db the error:
2022-04-29T09:02:26Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-04-29T09:02:22.819Z	[31mFATAL[0m	DB error: error in vulnerability DB initialize: failed to open db: open /home/scanner/.cache/trivy/db/trivy.db: permission denied
After updating permissions:
Scanning works as intended ...

Thank you for your efforts.
Kind Regards
Rene

**Comment by chlins** [comment]
You could refer to https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment if you want to skip update trivy db.

**Comment by REHICode** [comment]
> You could refer to https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment if you want to skip update trivy db.

Thank you for your answer, but this is actually not the problem.

The path given for the trivy.db and metadata.json in the documents and files and in the FAQs are wrong (in my scenario: if I use different data_volume (maybe this is not a dependency))

**Comment by ChenJhua** [comment]
I also want to execute chown, I don't know if you can solve this problem am
