### ISSUE TITLE
build harbor registry failed when download binary from https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#16785]
What can we help you?

hi, harbor team,
when I try to build the container image on version 2.5.0, it try to download binary from this URL, but there is no such asset there, please help to check.
https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry

thanks.

**Comment by YangJiao0817** [comment]
@danielzhanghl You can try specify `BUILDBIN=true` when build.
