### ISSUE TITLE
Error to download one layer of an image

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#16802]
Hello,
I've a weird issue on one layer (arround 70KB) of an image on Harbor, docker keep trying to downloading the layer
This is the log of harbor-registry with a status_code "416" :
![image](https://user-images.githubusercontent.com/11298399/166641586-b93903ca-7580-499d-b76e-6d07f1567d34.png)

And this is the harbor-core logs `2022/05/02 09:43:15 httputil: ReverseProxy read error during body copy: unexpected EOF`

We rebuilt the exact same image, with a different tag and it's working without any issue.

Harbor : 2.5.0
Thanks

**Comment by wy65701436** [comment]
if you see the failure around 2022/05/02 09:43:15 in the registry.log, provide it.

**Comment by flbla** [comment]
This is the registry log for the layer :

```
time="2022-05-02T09:43:15.543462189Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=XXXXXXXXXXXXXXXXX http.request.id=9e563ce3-0311-4d98-a3d2-afab4b4ec912 http.request.method=GET http.request.remoteaddr=X.X.X.X http.request.uri="/v2/<PROJECT>/<IMAGE_NAME>/blobs/sha256:142f25823c389e1959644cda74b0cbdc0244e53e5d9da4dbad296de4c7321586" http.request.useragent="docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/5.10.16.3-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \(linux\))" vars.digest="sha256:142f25823c389e1959644cda74b0cbdc0244e53e5d9da4dbad296de4c7321586" vars.name="<PROJECT>/<IMAGE_NAME>"

X.X.X.X - - [02/May/2022:09:43:15 +0000] "GET /v2/<PROJECT>/<IMAGE_NAME>/blobs/sha256:142f25823c389e1959644cda74b0cbdc0244e53e5d9da4dbad296de4c7321586 HTTP/1.1" 416 33 "" "docker/20.10.14 go/go1.16.15 git-commit/87a90dc kernel/5.10.16.3-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.14 \\(linux\\))"
```

Thanks
