### ISSUE TITLE
Is the webhook request blocking?

### ISSUE THREAD

**Issue by zhuxindong** [goharbor/harbor#16805]
Is the webhook blocking? for example , i set webhook to http://xxx，if the "http://xxx" crash dwon and cannot reply to any message，Will it affect harbor's normal work?

**Comment by ChristianCiach** [comment]
I am not a member of Harbor, but I was curious about this as well.

Looking at the code, it seems the webhooks are processes *asynchronously*. The requests (called "notification" in the code) are submitted to the jobservice. The jobservice processes a queue of jobs using the configured amount of workers.

The code in question starts here: https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/pkg/notification/hook/hook.go#L64

This also means that we probably don't notice when a webhook request failes. I guess these failures will only be visible in the logs.

**Comment by zhuxindong** [comment]
> I am not a member of Harbor, but I was curious about this as well.
> 
> Looking at the code, it seems the webhooks are processes _asynchronously_. The requests (called "notification" in the code) are submitted to the jobservice. The jobservice processes a queue of jobs using the configured amount of workers.
> 
> The code in question starts here:
> 
> https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/pkg/notification/hook/hook.go#L64
> 
> This also means that we probably don't notice when a webhook request fails. I guess these failures will only be visible in the logs.

yeah ，it seems li

**Comment by zhuxindong** [comment]
> I am not a member of Harbor, but I was curious about this as well.
> 
> Looking at the code, it seems the webhooks are processes _asynchronously_. The requests (called "notification" in the code) are submitted to the jobservice. The jobservice processes a queue of jobs using the configured amount of workers.
> 
> The code in question starts here:
> 
> https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/pkg/notification/hook/hook.go#L64
> 
> This also means that we probably don't notice when a webhook request fails. I guess these failures will only be visible in the logs.

Yeah ,It looks like the harbor don't care about the webhook response

**Comment by chlins** [comment]
Harbor has a component `jobservice` to execute these long-time jobs like `webhook/replication/scan/...` asynchronously, so it will not affect.
