### ISSUE TITLE
unable to push when behind reverse proxy: unauthorized: authorize header needed to send HEAD to repository

### ISSUE THREAD

**Issue by billyburly** [goharbor/harbor#16800]
New deployment of 2.5. Trying to run behind haproxy (my ssl terminator) and/or nginx. `podman login` works, but when I go to do a `podman push` the image doesn't transfer, and i get the following error.

    #podman push wr/app-base:0.0.1 harbor.mydomain.com/library/wr/app-base:0.0.1
    Getting image source signatures
    Copying blob c550c8e0f355 [--------------------------------------] 1.0MiB / 151.3MiB
    Copying blob fa498c409329 [--------------------------------------] 5.0MiB / 758.0MiB
    Error: writing blob: uploading layer chunked: unauthorized: authorize header needed to send HEAD to repository: authorize header needed to send HEAD to repository

If I configure podman to directly talk to harbor it works

    #podman push wr/app-base:0.0.1 harbor:8040/library/wr/app-base:0.0.1
    Getting image source signatures
    Copying blob c550c8e0f355 done
    Copying blob fa498c409329 done
    Copying config 424c60fc75 done
    Writing manifest to image destination
    Storing signatures

**Comment by chlins** [comment]
Could you provide your nginx configuration? It seems your haproxy trim auth header when proxy requests.

**Comment by billyburly** [comment]
```
upstream harbor {
  server 127.0.0.1:8040;
}

server {
    listen 80 proxy_protocol;
    server_name harbor.%%%.com;

    client_max_body_size 0;
    chunked_transfer_encoding on;

    location / {
        proxy_pass http://harbor/;
        proxy_set_header  Host              $http_host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;
   }
}
```

**Comment by chlins** [comment]
You could refer to https://github.com/goharbor/harbor/issues/3114.

**Comment by wy65701436** [comment]
@billyburly did you resolve the problem?
