### ISSUE TITLE
Expiration time ignored when creating a robot account with the robotv1 API

### ISSUE THREAD

**Issue by jpertejo** [goharbor/harbor#16803]
- harbor version: [v2.4.1-c4b06d79]

I'm trying to create a project robot account without expiration time using the robotv1 API: 

> https://{{harbor_url}}/api/v2.0/projects/testproject/robots

with the following body:
```
{
  "access": [
    {
      "action": "push",
      "resource": "/project/2/repository"
    }
  ],
  "name": "ra-test1",
  "expires_at": -1,
  "description": "Test"
}
```

The robot account is created, but with an expiration time of 30 days.
I've tried to configure other values in "expires_at" parameter (e.g. "expires_at": 365) and the robot account is always configured with an expiration time of 30 days.
I've also tried to add a "duration" parameter to the body, with the same result.
It seems that the "expires_at" parameter is ignored and the robot account is always configured with a default expiration time of 30 days.
Is there any way to configure the robot account's expiration time using the API?

**Comment by wy65701436** [comment]
the robot v1 is deprecated, please v2 for instead.
