### ISSUE TITLE
Allow Pull Deny Push in Public Repository

### ISSUE THREAD

**Issue by pthoelken** [goharbor/harbor#16815]
Hello Community, 

may a simple question; how can I configure Harbor that anonymous people can pull images from repo but nobody should can push images to the public registry / repo except the specified user? 

I didn't find any configuration for this. 

Thanks.

**Comment by pthoelken** [comment]
It seems to be that repositories which are marked  as "public" are configuired as **public-push=deny and public-pull=allow** by default.

**Comment by chlins** [comment]
This behavior is by design, for mostly public service like `dockerhub` are also the same policy.

**Comment by doug62** [comment]
When will this be fixed?
