### ISSUE TITLE
Trivy error after upgrade to v2.5.0

### ISSUE THREAD

**Issue by kuja53** [goharbor/harbor#16813]
What can we help you?
Hello, 

after upgrade all harbor images from v2.4.1 to 2.5.0 I experience following error messages in Trivy. But weird is that scanning works. I have air-gapped environment with skipUpdate and offlineScan enabled. And also I cannot see the current build version of Trivy DB in Harbor UI.

`{"exit_code":1,"level":"error","msg":"Running trivy failed","std_out":"Incorrect Usage. flag provided but not defined: -format\n\nNAME:\n   trivy - A simple and comprehensive vulnerability scanner for containers\n\nUSAGE:\n   trivy [global options] command [command options] target\n\nVERSION:\n   0.24.2\n\nCOMMANDS:\n   image, i          scan an image\n   filesystem, fs    scan local filesystem for language-specific dependencies and config files\n   rootfs            scan rootfs\n   repository, repo  scan remote repository\n   client, c         client mode\n   server, s         server mode\n   config, conf      scan config files\n   plugin, p         manage plugins\n   help, h           Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --quiet, -q        suppress progress bar and log output (default: false) [$TRIVY_QUIET]\n   --debug, -d        debug mode (default: false) [$TRIVY_DEBUG]\n   --cache-dir value  cache directory (default: \"/home/scanner/.cache/trivy\") [$TRIVY_CACHE_DIR]\n   --help, -h         show help (default: false)\n   --version, -v      print the version (default: false)\n2022-05-06T06:36:45.336Z\t\u001b[31mFATAL\u001b[0m\tflag provided but not defined: -format\n","time":"2022-05-06T06:36:45Z"}
{"error":"running trivy: exit status 1: Incorrect Usage. flag provided but not defined: -format\n\nNAME:\n   trivy - A simple and comprehensive vulnerability scanner for containers\n\nUSAGE:\n   trivy [global options] command [command options] target\n\nVERSION:\n   0.24.2\n\nCOMMANDS:\n   image, i          scan an image\n   filesystem, fs    scan local filesystem for language-specific dependencies and config files\n   rootfs            scan rootfs\n   repository, repo  scan remote repository\n   client, c         client mode\n   server, s         server mode\n   config, conf      scan config files\n   plugin, p         manage plugins\n   help, h           Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --quiet, -q        suppress progress bar and log output (default: false) [$TRIVY_QUIET]\n   --debug, -d        debug mode (default: false) [$TRIVY_DEBUG]\n   --cache-dir value  cache directory (default: \"/home/scanner/.cache/trivy\") [$TRIVY_CACHE_DIR]\n   --help, -h         show help (default: false)\n   --version, -v      print the version (default: false)\n2022-05-06T06:36:45.336Z\t\u001b[31mFATAL\u001b[0m\tflag provided but not defined: -format\n","level":"error","msg":"Error while retrieving vulnerability DB version","time":"2022-05-06T06:36:45Z"}`

**Comment by zyyw** [comment]
dup of this issue: https://github.com/goharbor/harbor/issues/16554
It's been fixed in this PR: https://github.com/goharbor/harbor/pull/16729
