### ISSUE TITLE
Artifact count / paging broken – cosign-related?

### ISSUE THREAD

**Issue by jkreileder** [goharbor/harbor#16816]
I'm pushing the same images as on https://hub.docker.com/r/jkreileder/exporter-merger/tags to a private harbor registry:

Harbor reports that there are **49** artifacts (7 would be correct) – but when you actually go the the repo, only 1 artifact is shown on page 1:

<img width="1099" alt="Screen Shot 2022-05-06 at 18 41 54" src="https://user-images.githubusercontent.com/4390544/167176034-29127041-2728-4b7d-bd0c-cae46b2f34b1.png">

Then 3 on page 2:

<img width="1107" alt="Screen Shot 2022-05-06 at 18 43 52" src="https://user-images.githubusercontent.com/4390544/167176317-313025c8-b5d1-4981-ac40-e72386ecb177.png">

Then 2 on page 3, and 1 on page 4.  Only if I switch to 50 items per page, I get all **7** rows at once.

The images are multi-platform (arm64+amd64) and signed with cosign (with `--recursive`).  This is the only repo on the instance with cosigned images and it's also the only repo showing this behavior – so I suspect this might be cosign-related.

**Versions:**

- harbor version: 2.5.0
- aws eks 1.22

**Comment by AllForNothing** [comment]
@jkreileder What's the `X-Total-Count` header of the artifact list API?
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/30999793/167235921-b2112e18-294e-4b19-a239-8d5dd43f73f8.png">

**Comment by jkreileder** [comment]
> @jkreileder What's the `X-Total-Count` header of the artifact list API? 

49

**Comment by jkreileder** [comment]
GC for untagged artifacts is enabled. It might very well be, that there would be 49 artifacts in the repository without GC.

**Comment by jkreileder** [comment]
I just noticed that the artifact count problem breaks other things as well: `/system/scanAll/schedule` stopped processing all artifacts!  I've delete above repo for now and `scanAll` seems to really scan all images again.
