### ISSUE TITLE
Could use clarity on going from 1.10.10 to 2.x in the upgrade instructions

### ISSUE THREAD

**Issue by herter4171** [goharbor/harbor#16826]
When I last did a long overdue update to Harbor, I hadn't realized there were 2.x versions or observed that `release v1.10.10 drops the migrator support,` and the latest was 1.x.  I thought I was SOL without the migrator, but thankfully porting over my `harbor.yml` fields worked.  Basically, I think there should be some attention drawn to that and how to work around it in the upgrade instructions on the site, because all I currently see is use of the migration image.

**Comment by AllForNothing** [comment]
@herter4171 Is this [doc](https://goharbor.io/docs/2.5.0/administration/upgrade/) helpful for you?

**Comment by herter4171** [comment]
That's the page I was referring to.  The release notes say you can't use the migration image for that version, but there's no indication of which versions can't use the image in the instructions.  The migration image also shows no indication of failure even though the modified `harbor.yml` doesn't work.

**Comment by herter4171** [comment]
Feel free to close.  I just wanted to point it out, because I didn't see anything for this contingency.
