### ISSUE TITLE
I use the cephfs as the external persistent volume, but trivy can't running correctly.

### ISSUE THREAD

**Issue by andyzheung** [goharbor/harbor#16838]
1、trivy helm:
![image](https://user-images.githubusercontent.com/22912347/167758986-38be5497-8eaa-44c3-83c3-b7537100849f.png)
2、sc:
![image](https://user-images.githubusercontent.com/22912347/167759043-82db1374-939a-451b-aa1a-3473d4acf53c.png)
3、trivy container logs:
![image](https://user-images.githubusercontent.com/22912347/167759074-f5676f49-7678-42ed-a946-3f83a394b5af.png)
4、I try it like this, but not ok:
(https://github.com/goharbor/harbor/issues/12933#issuecomment-754777914) • 
One could use a initContainer that sets the right permissions on the volume:

# trivy-sts.yaml
[...]
      initContainers:
      - name: set-permissions
        image: busybox:1.28
        command: ['chown', '-R', '10000:10000', '/home/scanner/.cache']
        volumeMounts:
          - name: data
            mountPath: /home/scanner/.cache
            subPath: {{ .Values.persistence.persistentVolumeClaim.trivy.subPath }}
            readOnly: false
[...]

**Comment by zyyw** [comment]
@andyzheung did you only specify cephfs for trivy? How about the configuration for persistence.persistentVolumeClaim.registry, persistence.persistentVolumeClaim.database, & persistence.persistentVolumeClaim.redis ?

**Comment by andyzheung** [comment]
> One could use a initContainer that sets the right permissions on the volume:

other component I also use cephfs, but the pod is ok..

**Comment by bolaji-atmost** [comment]
still facing the same issue, how did you go about solving it @andyzheung @zyyw @wy65701436 @danielpacak @ctrlaltdel
