### ISSUE TITLE
ListArtifacts is slow,it takes about 1s to call  ListArtifacts  function. And i found that the database doesn't create indexes for  repository_name  and content_type

### ISSUE THREAD

**Issue by pingwujinchu** [goharbor/harbor#16839]
harbor version: v2.3.1

actual sql：

[ORM]2022/05/10 08:42:32  -[Queries/default] - [  OK / db.QueryRow /   967.3ms] - [SELECT COUNT(*) FROM "artifact" T0 WHERE T0."repository_name" = $1 AND T0."id" =id AND (
		EXISTS (SELECT 1 FROM tag WHERE tag.artifact_id = [T0.id](http://t0.id/))
		OR 
		NOT EXISTS (SELECT 1 FROM artifact_reference ref WHERE ref.child_id = [T0.id](http://t0.id/))
	) ]

[ORM]2022/05/10 08:41:52  -[Queries/default] - [  OK /    db.Query /  1253.7ms] - [SELECT SUM(size) FROM blob Where content_type NOT IN ($1)]

sourcec code：
 harbor/src/server/v2.0/handler/artifact.go

func (a *artifactAPI) ListArtifacts(ctx context.Context, params operation.ListArtifactsParams) middleware.Responder {

total, err := a.artCtl.Count(ctx, query)

}

**Comment by chlins** [comment]
Could you check your database load and connections?

**Comment by pingwujinchu** [comment]
The number of connections is about 179. The database load is shown below
![image](https://user-images.githubusercontent.com/18208104/168241835-5ae58422-dda3-4920-bbe0-52530e596e4d.png)

**Comment by chlins** [comment]
How many artifact and blob do you have, could you try to execute `select count(*) from` to get the result?

**Comment by j4ckstraw** [comment]
> How many artifact and blob do you have, could you try to execute `select count(*) from` to get the result?

There are 704,781 artifacts and  4,659,833 blobs.

```
registry=> select count(*) from artifact;
 count
--------
 704781
(1 row)


registry=> select count(*) from blob;
  count
---------
 4659833
(1 row)
```

**Comment by chlins** [comment]
You could try to add index by `CREATE INDEX concurrently idx_artifact_repository_name_tmp ON public.artifact USING hash (repository_name)`.

**Comment by j4ckstraw** [comment]
> You could try to add index by `CREATE INDEX concurrently idx_artifact_repository_name_tmp ON public.artifact USING hash (repository_name)`.

OK, Thank you for your reply.

BTW, why not harbor add the index by default?

**Comment by chlins** [comment]
Recently we found this index maybe can help to improve the performance of some artifact APIs, but we still do more testing for that and maybe will add it by default in the future version but for some old versions like 2.3 we'll not keep maintaining.

**Comment by chlins** [comment]
@j4ckstraw Hi, does this index help to boost the SQL execution time?

**Comment by j4ckstraw** [comment]
> @j4ckstraw Hi, does this index help to boost the SQL execution time?

Sorry to reply so late, I'll try it today.

**Comment by j4ckstraw** [comment]
> > @j4ckstraw Hi, does this index help to boost the SQL execution time?
> 
> Sorry to reply so late, I'll try it today.
@chlins 
It's very impressive.

ListArtifact 2s -> 2ms, even for repository which has 1000 artifacts can be return at about 200ms.

Thank you very much

**Comment by chlins** [comment]
Some indexes which help to improve performance: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#create-index-for-harbor-tables-to-improve-performance

**Comment by dkulchinsky** [comment]
@chlins wanted to circle back to this as we're hitting a very similar issue.

any reason this index is not added by default to the schema? referring specifically to the artifacts one, or perhaps it was and I didn't see the related PR.
