### ISSUE TITLE
System Artifact Manager: Ensure Vendor and Artifact Type are set in selector query for system artifact cleanup

### ISSUE THREAD

**Issue by prahaladdarkin** [goharbor/harbor#16831]
Currently, when listing the candidate system artifacts for cleanup using the selectors, the vendor id and artifact type are not injected automatically within the query. This could cause an incorrect query to impact all vendors and artifact types. 
Hence injecting the artifact type and vendor id automatically within the query would help to prevent such incorrect behavior and restrict it to the vendor and artifact types that have been registered with a custom selector

**Comment by AllForNothing** [comment]
@prahaladdarkin I'm closing this issue. Reopen it if needed
