### ISSUE TITLE
rest api access vulnerability report via  is empty

### ISSUE THREAD

**Issue by fragfutter** [goharbor/harbor#16845]
Running goharbor v2.5.0 with trivy i try to get the vulnerability report for a local artifact. 

Trivy is up and running and the webinterface reports vulnerabilities. So far everything works.

fetch the artifact information via rest and extract the url to the vulnerability report
```
curl  https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/v0.12.0 \
jq .addition_links.vulnerabilities.href
```

reports 
```
/api/v2.0/projects/metallb/repositories/speaker/artifacts/sha256:6c91d1badafd76371fd394cc5e93cebe220a0391924796ea075bfe195531219a/additions/vulnerabilities
```

fetching this url results in an empty dictionary.

i also tried using the swagger api endpoint 

```
/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/vulnerabilities
```

with project_name=metallb, repository_name=speaker, reference=v0.12.0 also reports nothing.

Am i missing something?

**Comment by AllForNothing** [comment]
@fragfutter `empty dictionary` means the artifact is `not scanned` or `has no vulnerability`

**Comment by fragfutter** [comment]
the artifact should have a report. At least i can see one in the webinterface.

![Screenshot from 2022-05-12 08-08-34](https://user-images.githubusercontent.com/531718/168003701-cce3283c-2f62-485d-8280-fbff027ec707.png)

**Comment by AllForNothing** [comment]
curl  https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/v0.12.0 \
jq .addition_links.vulnerabilities.href

@fragfutter  you should use the digest instead of the tag to query, so you need to replace `v0.12.0` with `sha256:xxxxxx`, and query with necessary query parameters `with_tag=false&with_scan_overview=true&with_label=true&with_immutable_status=true`

example:   `https://10.202.250.196/api/v2.0/projects/library/repositories/hello-world/artifacts/sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4?with_tag=false&with_scan_overview=true&with_label=true&with_immutable_status=true`

**Comment by fragfutter** [comment]
using the hash makes no difference.

translate tag to digest
```curl https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/v0.12.0 | jq .digest```

results in ```sha256:6c91d1badafd76371fd394cc5e93cebe220a0391924796ea075bfe195531219a```

fetch this artifact and get the link to the report

`curl 'https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/sha256:6c91d1badafd76371fd394cc5e93cebe220a0391924796ea075bfe195531219a?with_tag=false&with_scan_overview=true&with_label=true&with_immutable_status=true' 
| jq .addition_links.vulnerabilities.href
`

fetch the report
```curl 'https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/sha256:6c91d1badafd76371fd394cc5e93cebe220a0391924796ea075bfe195531219a/additions/vulnerabilities'```

empty dictionary. 

screenshot of webinterface  has the right hash (6c91db1a)
![Screenshot from 2022-05-12 12-02-40](https://user-images.githubusercontent.com/531718/168046067-8579715f-e33f-4e79-b6c7-c18ceac8be70.png)

**Comment by AllForNothing** [comment]
@fragfutter I found the answer:
you have to add the `X-Accept-Vulnerabilities: application/vnd.security.vulnerability.report; version=1.1, application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0`

so  try   `curl -H "X-Accept-Vulnerabilities: application/vnd.security.vulnerability.report; version=1.1, application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0" https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/sha256:6c91d1badafd76371fd394cc5e93cebe220a0391924796ea075bfe195531219a/additions/vulnerabilities`, should get what you want

**Comment by fragfutter** [comment]
thank you, this works.

for completeness, this also works with a tag. 
`
curl -H "X-Accept-Vulnerabilities: application/vnd.security.vulnerability.report; version=1.1" https://HOST/api/v2.0/projects/metallb/repositories/speaker/artifacts/v0.12.0/additions/vulnerabilities
`
