### ISSUE TITLE
CVE Allowlist not visible in the Vulnerability Table 

### ISSUE THREAD

**Issue by diegoNutmeg** [goharbor/harbor#16842]
The current implementation of the UI is not following the `Project members permissions` of the official [documentation](https://goharbor.io/docs/1.10/administration/managing-users/user-permissions-by-role/).

<img width="699" alt="Screenshot 2022-05-11 at 13 08 28" src="https://user-images.githubusercontent.com/28001818/167846211-5ea632d4-caa5-46b7-b642-a8764c204170.png">

Current UI with any role apart if System Admin

![Screenshot 2022-05-11 at 13 15 55](https://user-images.githubusercontent.com/28001818/167847694-e61581c0-3445-413c-8005-593d5d819a15.png)

**Steps to reproduce the problem:**
If you are any role apart from System Admin, you won't see the column with `Listed In CVE Allowlist`

- Go to `Projects`
- Click in any `Repositories`
- Click in any `Artefact`
- In the Additions > Vulnerabilities Tab > Table does not have the  `Listed In CVE Allowlist` column

**Suggestion**

Modify the UI to allow any roles to visualize the `CVE Allowlist`

Expected UI

![image (7)](https://user-images.githubusercontent.com/28001818/167847934-04de67dc-eb3a-44a1-b58b-fda75b4c1905.png)

PR in progress

**Versions:**

- harbor version: 2.4.0-d4affc2e

**Comment by AllForNothing** [comment]
@diegoNutmeg Currently, Harbor has a system-level allowlist(system admin only) and project-level allowlist,  by default,  a project uses the system-level allowlist as its allowlist.  In this case, there is no way for non-admin users to know if a CVeEis in the CVE allowlist.
In other words, the `Listed In CVE Allowlist` column is a system-admin-only functionality

**Comment by diegoNutmeg** [comment]
> Allow all roles to see CVE AllowList - Fixes #16842 #16843

Thanks @AllForNothing I raised a quick [PR](https://github.com/goharbor/harbor/pull/16843), but feel free to create a new one
