### ISSUE TITLE
Harbor behind Apache

### ISSUE THREAD

**Issue by luandrea** [goharbor/harbor#16852]
I installed Harbor in a server inside the company farm and I can use it without problem through https://my-internal-server.com/harbor.
I tried to add a reverse proxy rule to Apache to access it through the public server, like https://my-public-server.com/harbor, but this doesn't work.
Ho can I do it?
I also tried to set it in harbor.yaml as external_url and relaunch install.sh:
external_url:  https://my-public-server.com

The problem is that some resources get loaded from https://my-public-server.com/runtime.44d3ea765049eac6.js and not from https://my-public-server.com/harbor/runtime.44d3ea765049eac6.js

**Comment by pthoelken** [comment]
Maybe the same from here? https://github.com/goharbor/harbor/issues/16844

Otherwise docker needs this to run behind the reverse proxy: 

```
proxy_set_header  Host              $http_host;
proxy_set_header  X-Real-IP         $remote_addr;
proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header  X-Forwarded-Proto $scheme;
proxy_buffering off;
proxy_request_buffering off;

```

**Comment by luandrea** [comment]
The issue #16844 is about a problem in the login page. 
In my case I can log in correctly through https://my-internal-server.com/harbor.
I cannot see any log in page if go to https://my-public-server.com/harbor.
In any case, where should I check those parameters that you are speaking of? In the harbor ngingx or in the external apache proxy?

**Comment by pthoelken** [comment]
This have to be configured in the native apache / nginx proxy.

**Comment by luandrea** [comment]
The only way that I made it running is creating a new Virtual Host in Apache with a dedicated port, so now I can access Harbor through https://my-public-server.com:8433 that redirects me to https://my-internal-server.com .
In port 443 in the main Virtual Host I have other contexts and I didn't find a way to make it work with Harbor.

**Comment by rrgadeev** [comment]
> The only way that I made it running is creating a new Virtual Host in Apache with a dedicated port, so now I can access Harbor through https://my-public-server.com:8433 that redirects me to https://my-internal-server.com . In port 443 in the main Virtual Host I have other contexts and I didn't find a way to make it work with Harbor.

we need another domain name that will lead to the ip my-public-server.com
harbor.my-public-server.com
