### ISSUE TITLE
Upgrade process is not correct

### ISSUE THREAD

**Issue by bbruun** [goharbor/harbor#16864]
I just went through a process of upgrading a Harbor 2.2 installation to 2.4.2 (latest as of this writing). (_yes old system don't ask_)

I found the upgrade process described in the  (https://goharbor.io/docs/1.10/administration/upgrade/)[https://goharbor.io/docs/1.10/administration/upgrade/] and (https://goharbor.io/docs/2.2.0/administration/upgrade/)[https://goharbor.io/docs/2.2.0/administration/upgrade/] and (https://goharbor.io/docs/2.4.0/administration/upgrade/)[https://goharbor.io/docs/2.4.0/administration/upgrade/] and found that they don't work - they are incorrect, for offline upgrades at least, but most likely also for online upgrades as the ` goharbor/prepare:<version>` docker image does not exist and returns `Error response from daemon: manifest for goharbor/harbor-migrator:2.4.2 not found: manifest unknown: manifest unknown`. The image is contained in the offline installer...

The upgrade process from Harbor 2.2 to 2.4.2 should be something like this
* Stop current version
* Download next minor release (2.3.4 in this case)
* Upgrade to 2.3.4
* Download latest 2.4.x release (2.4.2 in this case)
* Upgrade to 2.4.2

The process described in the above linked documentation should be like the following - where `VERSION` is setup correctly to the next latest minior release eg for a 2.2 upgrade it sould be the laetst 2.3.x version and for 2.3.x it should be the latest 2.4.x version etc.

Repeate the following and change/set the `export VERSION=vX.Y.Z` correctly for each minor version you want to upgrade to. 

**If you upgrade more than oneminor version eg jump from 2.2 to 2.4 then the system won't function afterwards!!!**

How to get current running version:
```bash
CURRENT_VERSION=$(sudo docker ps | tr ' ' '\n'  |grep goharbor | cut -d: -f2 | sort -u)
echo "Current Harbor version running: ${CURRENT_VERSION}"
```

```bash
# Stop Harbor using system service manager eg systemd (or manually using docker-compose)
sudo systemctl stop harbor
# or "docker-compose -f /opt/harbor/docker-compose.yml stop"

# Make local copies of config and database
sudo cp -r /opt/harbor /opt/backup-harbor
sudo cp -r /data/database /data/backup-database

# Define what version you want to upgrade to - check [github.com](https://github.com/goharbor/harbor/releases) for lastet minor version and set that eg "v2.3.4"
export VERSION=v2.3.4


# Download offline installer and prep images
cd /opt
sudo wget wget https://github.com/goharbor/harbor/releases/download/${VERSION}/harbor-offline-installer-${VERSION}.tgz
sudo tar zxf harbor-offline-installer-${VERSION}.tgz
sudo docker image load -f harbor/harbor.${VERSION}.tar.gz

# Run migrations
sudo docker run -it --rm -v /:/hostfs goharbor/prepare:${VERSION} migrate -f /opt/harbor/harbor.yml

# Upgrade Harbor
cd /opt/harbor
sudo ./install.sh

# Wait for container `harbor-db` to settledown (use Ctrl-C to exit `docker stats`)
sudo docker stats

# Stop Harbor and start it using your system service manager
sudo docker-compose -f /opt/harbor/docker-compose.yml stop
sudo systemctl start harbor
```

If you have a push/push replication then run the commands in parallel on both servers - at the same time.

A systemd service file ala `/etc/systemd/system/harbor.service` could be something like this 
```
[Unit]
Description=Harbor Docker Registry
After=network.target docker.service
Requires=docker.service

[Service]
Environment="HOME=/root"
Restart=always
RestartSec=10
TimeoutSec=300
WorkingDirectory=/opt/harbor
ExecStart=/usr/bin/env docker-compose -f "docker-compose.yml" up
ExecStop=/usr/bin/env docker-compose -f "docker-compose.yml" stop -t 60
ExecStopPost=/usr/bin/env docker-compose -f "docker-compose.yml" down
StandardOutput=null
StandardError=null

[Install]
WantedBy=docker.service
```

**Comment by MinerYang** [comment]
Hi @bbruun,

Do you have any chance to solve it or provide more update? Otherwise I would like to close this issue for now?
