### ISSUE TITLE
Failed opening the RDB file dump.rdb (in server root dir /var/lib/redis) for saving: No s       pace left on device

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16873]
[root@docker-man-01 harbor]# docker-compose ps
      Name                     Command                  State                 Ports          
---------------------------------------------------------------------------------------------
chartmuseum         /docker-entrypoint.sh            Up (healthy)   9999/tcp                 
harbor-core         /harbor/start.sh                 Up (healthy)                            
harbor-db           /entrypoint.sh postgres          Up (healthy)   5432/tcp                 
harbor-jobservice   /harbor/start.sh                 Exit 1                                  
harbor-log          /bin/sh -c /usr/local/bin/ ...   Up (healthy)   127.0.0.1:1514->10514/tcp
harbor-portal       nginx -g daemon off;             Up (healthy)   80/tcp                   
nginx               nginx -g daemon off;             Up (healthy)   0.0.0.0:8021->80/tcp     
redis               docker-entrypoint.sh redis ...   Up             6379/tcp                 
registry            /entrypoint.sh /etc/regist ...   Up (healthy)   5000/tcp                 
registryctl         /harbor/start.sh                 Up (healthy)  
============================================================
查看jobservice的日志
May 18 00:50:04 172.20.0.1 jobservice[25189]: ERROR: observer.write - MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
May 18 00:50:04 172.20.0.1 jobservice[25189]: message repeated 6 times: [ ERROR: observer.write - MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.]
May 18 00:50:04 172.20.0.1 jobservice[25189]: 2022-05-17T16:50:04Z [INFO] [/jobservice/logger/sweeper_controller.go:83]: sweeper *sweeper.FileSweeper exit
May 18 00:50:04 172.20.0.1 jobservice[25189]: ERROR: observer.write - MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
May 18 00:50:04 172.20.0.1 jobservice[25189]: message repeated 2 times: [ ERROR: observer.write - MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.]
May 18 00:50:04 172.20.0.1 jobservice[25189]: 2022-05-17T16:50:04Z [FATAL] [/jobservice/main.go:81]: redis sub/pub chan error: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
====
![image](https://user-images.githubusercontent.com/88759374/168947274-a8f3da46-4860-4e72-807c-d906c5f52430.png)
reids的日志：
![image](https://user-images.githubusercontent.com/88759374/168947357-8bf71d3f-6b4f-402b-9a01-dd8a6253a1e9.png)
 Failed opening the RDB file dump.rdb (in server root dir /var/lib/redis) for saving: No space left on device

**Comment by chlins** [comment]
Please ensure your device has enough free space.
