### ISSUE TITLE
harbor 2.2.4 prometheus alert rules

### ISSUE THREAD

**Issue by finalha** [goharbor/harbor#16877]
I'm using the harbor 2.2.4 and config the harbor exporter, now prometheus can get the metrics of harbor.
Some metrics can be found here: https://goharbor.io/docs/2.2.0/administration/metrics/
But I can't find the offical wiki of prometheus alert rules of harbor. Where could I get it?

**Comment by chlins** [comment]
We have no official wiki for prometheus alert rules, please refer to https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/.

**Comment by finalha** [comment]
> We have no official wiki for prometheus alert rules, please refer to https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/.

OK, thanks.
