### ISSUE TITLE
OIDC: failed to refresh token

### ISSUE THREAD

**Issue by enp** [goharbor/harbor#16875]
I have Harbor v2.2.2-56d7937f started via docker-compose and intergated with Keycloak via OIDC. Sometimes ```docker login``` fails and I see in harbor core log:

```
May 18 09:16:42 172.24.0.1 core[598]: 2022-05-18T09:16:42Z [ERROR] [/server/middleware/security/oidc_cli.go:59][requestID="cd77eaee-4fd0-48e3-8be0-ac17ce7a08ad"]: failed to verify secret: failed to refresh token, username: Bender_Rodriguez, error: oauth2: cannot fetch token: 400 Bad Request
May 18 09:16:42 172.24.0.1 core[598]: Response: {"error":"invalid_grant","error_description":"Token is not active"}
May 18 09:16:42 172.24.0.1 core[598]: 2022-05-18T09:16:42Z [ERROR] [/server/middleware/security/basic_auth.go:40][requestID="cd77eaee-4fd0-48e3-8be0-ac17ce7a08ad"]: failed to authenticate Bender_Rodriguez: not supported
```

On other side (keycloak) I see:

```
2022-05-18 09:16:42,805 WARN  [org.keycloak.events] (executor-thread-893) type=REFRESH_TOKEN_ERROR, realmId=harbor, clientId=harbor, userId=null, ipAddress=84.201.150.233, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```

Why this happens and how to resolve this issue?

**Comment by strgalt-t** [comment]
This is not a problem with Harbor but your Keycloak instance. Please make sure your time zones are synchronized.

**Comment by LarsBingBong** [comment]
@enp to me your timezones looks alright. You might actually "just" need to lower the value for the `Access Token Lifespan` setting under `Tokens` in your `Keycloak` `realm`. Make it lower than the value to the `SSO Session Idle` setting found on the same page.

Good luck.
