### ISSUE TITLE
support latest version of docker compose

### ISSUE THREAD

**Issue by willzhang** [goharbor/harbor#16885]
What can we help you?

when harbor will support latest version of docker compose?

old version for installtion
```
docker-compose ps
```

latest version for installtion
```
dockcer compose ps
```

**Comment by ChristianCiach** [comment]
As a workaround you can install https://github.com/docker/compose-switch until Harbor supports Compose V2 natively.

**Comment by MinerYang** [comment]
We add support for docker compose v2 in this pr. https://github.com/goharbor/harbor/pull/16919
Feel free to left comments.
