### ISSUE TITLE
Harbor can't proxy public Elastic Container Registry (ECR)

### ISSUE THREAD

**Issue by jamesglennan** [goharbor/harbor#16880]
What can we help you?
Running harbor v2.5.0-98e1b82f and when i attempt to setup pull-through cache for ecr, i get repository not found when pulling public images.

Setting up as registry with name `test` Type `Docker-Registry` and the address `public.ecr.aws/XXXX` where XXXX is the registry alias

`docker pull harbor.my-domain/test/example-image:latest` results in

```
Error response from daemon: unknown: repository example-image:latest
```

If i try without XXXXX, it doesnt work either. Am I doing something wrong or is this a bug when attempting to use pull-through on public images in ecr?

I should note that i managed to get it to work no issue on a private ecr

**Comment by AlexBarth13** [comment]
Hi @jamesglennan 
We have also implemented a connection the the public AWS ECR in our Harbor instance.
We used the URL `https://public.ecr.aws` as endpoint and used also `Docker-Registry` as `Provider`.

Did you tested it without `XXXX` if this is working?

From our side, we can pull images with the following command:
```
docker pull registry/amazoncache/<reponame>/<image>:<tag>
```

Example:
```
docker pull registry/amazoncache/ubuntu/redis:latest
```
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by jamesglennan** [comment]
So yes I did try that, although our repo name is an the default alias (the XXXX)

do you think if we added a custom alias and then pointed to the generic public ecr as you’ve suggested
It might work?

**Comment by stonezdj** [comment]
The harbor proxy cache is not a mirror cache, it proxy by project, in harbor.my-domain, you should create a proxy cache project such as ecr-proxy, then pull by this command
```
docker pull harbor.my-domain/ecr-proxy/test/example-image:latest
```

**Comment by jamesglennan** [comment]
Yeah so it worked with a custom alias. I’m not sure why it didn’t work with the default alias. 

Regardless, I think we can call this one solved thanks for your help
