### ISSUE TITLE
Which table in the database corresponds to the replication rules of harbor ？

### ISSUE THREAD

**Issue by liuchaowhu** [goharbor/harbor#16890]
**harbor version 2.2.3** 
**Which table in the database corresponds to the replication rules of harbor ？**
![图片](https://user-images.githubusercontent.com/89571485/169685567-e85593b6-feaf-45e2-9b52-b620ce75fcea.png)

![图片](https://user-images.githubusercontent.com/89571485/169685772-eb3a82f8-022b-4991-9c5d-2e2a5c9c31fc.png)

**Comment by liuchaowhu** [comment]
![图片](https://user-images.githubusercontent.com/89571485/169686040-eaccaea1-45d6-4b0d-8e82-389655dd8dc6.png)

**Comment by chlins** [comment]
It's the `replication_policy`.
