### ISSUE TITLE
Trivy secret scanning

### ISSUE THREAD

**Issue by stroeovidiu** [goharbor/harbor#16898]
Trivy has support for secret scanning and i was wondering if it is possible to enable that in harbor integration.
Can it be done?

Thank you!

**Comment by stonezdj** [comment]
What is it secret scanning? do you mean image contains secret or scanning by a secret?
@danielpacak  do you have any idea?

**Comment by danielpacak** [comment]
Trivy secret scanning is a new functionality to discover sensitive data in container images, e.g. password files, API keys, access tokens, etc.

Even though this functionality is available in Trivy, the Harbor Pluggable Scanners API and Harbor UI are not ready to consume such data. @stroeovidiu is it something you'd like to contribute to by proposing necessary extensions to Pluggable Scanners API?
