### ISSUE TITLE
Harbor Docs Edit Review

### ISSUE THREAD

**Issue by kcoriordan** [goharbor/harbor#16899]
Adding Harbor docs edit review attached
[Harbor docs review.docx](https://github.com/goharbor/harbor/files/8756847/Harbor.docs.review.docx)

**Comment by kcoriordan** [comment]
@a-mccarthy @jonasrosland

**Comment by OrlinVasilev** [comment]
@kcoriordan is that still valid?

**Comment by OrlinVasilev** [comment]
Hi @a-mccarthy any idea if that's till valid?
