### ISSUE TITLE
Document the steps/limitations of backup/restore Harbor with Velero

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#16903]
Limitations:

- [ ] The data in memory cannot be backed up and will be lost after restoring: pull time, pull count
- [ ] The registry upload purging may effect the backup with Restic

**Comment by a-mccarthy** [comment]
hi @ywk253100! Just want to make sure I understand, are you planning to create a draft of this content? Please let me know how I can help :)

**Comment by YangJiao0817** [comment]
https://github.com/goharbor/website/pull/346

**Comment by yanji09** [comment]
@a-mccarthy please help to review the doc.

**Comment by a-mccarthy** [comment]
I've created a new PR with a few small edits to @ywk253100's doc. If you have a minute, please review

**Comment by ywk253100** [comment]
> I've created a new PR with a few small edits to @ywk253100's doc. If you have a minute, please review

Thanks!
