### ISSUE TITLE
Garbage Collect error handling not working properly

### ISSUE THREAD

**Issue by SysAdmLS** [goharbor/harbor#16908]
Today i discover that gc run over the web ui did not delete any blobs although the logs in the webui did not report any errors and the database entries for the blobs got deleted.
**It seems as if the registryctl container isn't passing errors correctly to the other services.**

**Expected behavior and actual behavior:**
Expected:
If the gc (started over the ui) in registryctl fails it should pass the error to all other containers/services involved in the garbage collect process, so that these can stop the process/log the errors and dont falsely delete database entries.

Actual behavior:
There are no errors logged in the WEB UI and the database entries for the blobs are deleted while the blobs/files remain on disk. 
Only the registryctl.log file has error logs:
``` /var/log/harbor/registryctl.log:Mar 15 20:19:24 172.22.0.1 registryctl[2643539]: 2022-03-15T19:19:24Z [INFO] [/registryctl/api/registry/blob/blob.go:44]: failed to remove blob: sha256:6da60e0c103807b1bae5258fc6fa0de6e80e2ae65369327909e44f8b8974e8e1, with error:filesystem: Path not found: /docker/registry/v2/blobs/sha256/6d/6da60e0c103807b1bae5258fc6fa0de6e80e2ae65369327909e44f8b8974e8e1 ```

**Steps to reproduce the problem:**
Setup harbor, edit docker-compose.yml and change the volume mount for the registry path to an empty folder for the registryctl container

 registryctl:
    volumes:
      - /emptyfolder:/storage:z

Then push and delete some images and run a gc over the webui.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.4
filesystem storage driver

**Comment by zyyw** [comment]
@SysAdmLS why do you make the following change:
```
Setup harbor, edit docker-compose.yml and change the volume mount for the registry path to an empty folder for the registryctl container

registryctl:
volumes:
- /emptyfolder:/storage:z
```

Tried GC in harbor 2.3.4 (offline installer) without making the above change, the GC job just works fine.

**Comment by SysAdmLS** [comment]
@zyyw Im running a 2 node master/slave setup with haproxy in front. They both share the the same database and an nfs storage mounted on both servers for the registry data.

The problem is, the docker-compose gets auto generated by the ./prepare command and there is no way to **only change the registry data path**.

I already explained my issue with that here: https://github.com/goharbor/harbor/issues/15597

So I have to manually edit the docker-compose everytime I do an upgrade and i missed that the registryctl container also mounts the registry data. So the container mounted an empty folder which led to this problem.

I fully admit this is a error on my side but it could have been prevented if there either is a check in place, to see that everything gets mounted into the container correctly and/or throw the exceptions from the container in the web ui log for the gc.

**Comment by SysAdmLS** [comment]
Please consider this ticket as this is still a valid problem that could occur even in the default setup (for example some network drive failing while the gc is running or data that has been corrupted/deleted from some other software). **The admin/user would not notice any problem with the gc in the webui logs **since the errors thrown in the registryctl container are only logged to the local log file and not into the webui log**.**
