### ISSUE TITLE
Reindex/Repopulate blobs in database from filesystem

### ISSUE THREAD

**Issue by SysAdmLS** [goharbor/harbor#16909]
As a result from https://github.com/goharbor/harbor/issues/16908 my blob database table is out of sync with the blobs on my filesystem.

**Is there a way to either sync the database blob table with my filesystem or clean up the filesystem ?**

Im not sure if manually running ``` registry garbage-collect ``` in the registryctl container would solve my problem since its not advised from your side https://github.com/goharbor/harbor/issues/11606

**Comment by zyyw** [comment]
In my honest opinion, database is held as the source of truth, therefore repopulating blobs in database from filesystem doesn't sound like a decent way to recovering this issue.

**Comment by zyyw** [comment]
please do NOT use `registry garbage-collect`.

**Comment by SysAdmLS** [comment]
> In my honest opinion, database is held as the source of truth, therefore repopulating blobs in database from filesystem doesn't sound like a decent way to recovering this issue.

well then i would need a way to clean the blobs left on the filesystem


> btw, please do NOT use `registry garbage-collect`.

is that really no option ? I compared a dry run of "registry garbage-collect" with untagged removal disabled to the sha256 in my error logs (that got failed to clean) and the have been almost identical. 

Im understanding  https://github.com/goharbor/harbor/issues/11606 so that u should not run it with the untagged flag but otherwise should be fine.

**Comment by SysAdmLS** [comment]
@zyyw sorry for pinging but we are slowly running out of disk space. Do u have a suggestion what to do?

**Comment by SysAdmLS** [comment]
Since no help has been provided, im here to post my results for fixing this mess, that could have been prevented if the error messages that were thrown would have appeared in the webui log, see https://github.com/goharbor/harbor/issues/16908.

Running registry garbage-collect (in the container) in dry run mode and without untagged removal enabled, i created a list of blobs (sha256:XXXXXXXXXXXXX) that were going to be deleted. 

I then compared that list to the database table containing the blobs that should be on the filesystem. To get the list from the database, one has to use the following sql statement: `select digest from blob`

Both list should then sorted and cleaned from repeated lines/values. Example: `sort container_gc.txt | uniq > cotainer_gc_uniq.txt `

They can then be compared to each other to see if the gc would delete any blobs that the db references:

`grep -Fxf container_gc_uniq.txt db_digest.txt`

For me this showed 4 blobs which under later investigation proved to be old records which  were not used anymore and could be safely deleted.

Finally registry garbage-collect could be run without the dry run flag and untagged removal disabled. This cleaned up over 600gb and produced no errors. Make sure to set the registry to read only or turn it off completely before running this, otherwise you might delete blobs that are being pushed while running the gc.
