### ISSUE TITLE
Is it possible to clone a harbor instance/vm?

### ISSUE THREAD

**Issue by axi92** [goharbor/harbor#16926]
We use harbor and docker trust, is it possible to clone a harbor with trust enabled and use both?
The goal is that if one harbor fails the second will get live via the proxy. The problem is when docker trust is enabled the trust data will be different. Is there a way to have them be the same?

**Comment by stonezdj** [comment]
No, it is the limitation of notary.

**Comment by kuznetsovkk** [comment]
> The goal is that if one harbor fails the second will get live via the proxy.

It is a good way to HA harbor with 2 app-nodes behind the proxy-balancer, database cluster, and s3aws storage backend.

**Comment by axi92** [comment]
> > The goal is that if one harbor fails the second will get live via the proxy.
> 
> It is a good way to HA harbor with 2 app-nodes behind the proxy-balancer, database cluster, and s3aws storage backend.

But how did you solve the trust? You would need to sign on both instances?

**Comment by axi92** [comment]
I solved it by cloneing the instance so the keys are the same. And edit the local /etc/hosts file to bend the dns entry to the second server.
Push first then change dns settings and push again to the second.
