### ISSUE TITLE
Jobservice dashboard

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16921]
There are many jobs implemented by job service, and there are created/scheduled in different API/UI,  user might consider these jobs have no relationship. actually, the long-run job might block the execution of the other jobs, and cause some jobs never to be scheduled.  Users should have a jobservice dashboard to check if the current worker pool is blocked and also have a way to kill the long-run jobs, and check the queue depth ( it is exposed by metrics previously). without this tool, user could not recover the Harbor instance from these sorts of issues.

**Comment by okin** [comment]
I second this from an admin perspective.

As an admin finding running jobs might require me to visit different places and instead I'd like one place that gives me an overview with the possibility to filter jobs and also see their logs all in one place.
I want to be able to not only to find jobs but also have the possibility to stop or even kill them.

**Comment by stonezdj** [comment]
duplicated with #17512
