### ISSUE TITLE
Harbor doesn't execute replication tasks in parallel 

### ISSUE THREAD

**Issue by reddy9694** [goharbor/harbor#16928]
Hello
We have a harbor instance, were we created multiple replication tasks. These tasks are replicating resources to different destinations ( nexus and harbor ).  During this process we have noticed that, these replication tasks are **not executing in parallel** . This is creating huge impact on the application teams who are waiting for the resources to available in other instances.

Can we please know if this was intentional ? and if there is any configuration we need to update to execute replication tasks in parallel ?

**Comment by chlins** [comment]
The replication task is executed by harbor jobservice, the default max concurrency worker in jobservice is 10, so if only have replication tasks, they will be executed with 10 concurrency by default.

**Comment by reddy9694** [comment]
Can we increase this settings ? and if we increase this setting will that be impacting anything ?

**Comment by stonezdj** [comment]
It impact the database connection to the postgres.
