### ISSUE TITLE
Garbage Collector doesn't clean registry blob data

### ISSUE THREAD

**Issue by F0xedb** [goharbor/harbor#16936]
Hi,

At our company we have an internal registry running which seems to not garbage collect old image blobs.
In the dashboard (An on the underlying OS) it says 665.12 GiB storage used (And growing over time).

However, when going to Administration ⇾ Project Quotas it shown ~ 70 GiB of images.

Running the garbage collector yields no result (Only cleans up a few MiB)
We run the Garbage Collector every day.

**Expected behavior and actual behavior:**
The garbage collector removes all blobs in the `/data/registry/docker/registry/v2/blobs/sha256/` directory which are not in use or not known.
So that the total storage used and the sum of all project storage are equal. 

**Steps to reproduce the problem:**
1. Install harbor
2. Create a project
3. Set up a policy for the project: `For the repositories matching **, retain the most recently pushed 5 artifacts with tags matching ** with untagged`
4. Create a lot of images and tags so this policy gets triggered
5. UI shows that everything is removed successfully, but the disk space isn't reduced

**Versions:**
- harbor version: v2.3.3-a0a9ed8a
- docker engine version: 20.10.14
- docker-compose version: 1.24.1

**Additional context:**

- Using trivy for image scanning
- Default harbor installation with a reverse proxy in front of it

**Comment by zyyw** [comment]
@F0xedb , you mentioned the statement:
```
The garbage collector removes all blobs in the /data/registry/docker/registry/v2/blobs/sha256/ directory
```
which means delete every single artifact in your harbor environment. But the retention policy you set doesn't do that mean the exact same thing:
```
For the repositories matching **, retain the most recently pushed 5 artifacts with tags matching ** with untagged
```

Please alter your tag retention policy to delete all artifact, and confirm it on Harbor port, then, 2 hours later, you can run gc. The storage should be claimed. Notice that you may need to wait for at least 2 hours to run GC after deleting all artifacts from harbor portal.

**Comment by KeithTt** [comment]
@zyyw Hi, I have altered the policy, and exec GC on harbor portal after 2 hours, but disk space still not release.

**Comment by kingnarmer** [comment]
I am having same issue . How to clean up space  ? GUI report 150GB , registry mount /storage is using 450GB. I don't have the luxury to delete all images to clean up ?
