### ISSUE TITLE
admin login fail after upgrade to 2.5.1

### ISSUE THREAD

**Issue by iaderoubaix** [goharbor/harbor#16946]
I have upgraded 2 of my Harbor instances to 2.5.1 and both have the same symptoms
My authentication method has been set to LDAP and access to the upgraded instances is successful via LDAP
Unfortunately DB-based admin is failing to authenticate

I have reset the admin password in the database as 
update harbor_user set password='a71a7d0df981a61cbb53a97ed8d78f3e', salt='ah3fdh5b7yxepalg9z45bu8zb36sszmr' where username='admin';

Current DB entry is 
registry=# select user_id,username,password,salt,deleted,sysadmin_flag from harbor_user where username='admin';
 user_id | username |             password             |               salt               | deleted | sysadmin_flag 
---------+----------+----------------------------------+----------------------------------+---------+---------------
       1 | admin    | a71a7d0df981a61cbb53a97ed8d78f3e | ah3fdh5b7yxepalg9z45bu8zb36sszmr | f       | t
(1 row)

harbor.yml has also been reset to reflect password Harbor12345 

Startup is successful and all functionality tested is working.

core.log stated incorrect password
Jun  3 15:08:34 192.168.9.1 core[21014]: 2022-06-03T13:08:34Z [DEBUG] [/core/auth/authenticator.go:145]: Current AUTH_MODE is db_auth
Jun  3 15:08:34 192.168.9.1 core[21014]: 2022-06-03T13:08:34Z [DEBUG] [/core/auth/authenticator.go:158]: Login failed, locking admin, and sleep for 1.5s
Jun  3 15:08:35 192.168.9.1 core[21014]: 2022-06-03T13:08:35Z [ERROR] [/core/controllers/base.go:103]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'

**Comment by stonezdj** [comment]
You could reset the admin password with this FAQ: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
