### ISSUE TITLE
Status mismatch error post OIDC integration

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16942]
Hi,
I have enabled OIDC Integration for Harbor HA Setup deployed using helm chart v2.5.0. For the setup, I have used a core URL say [www.abc.com](http://www.abc.com/) using which helm chart was deployed. Additionally I have added an additional domain say [www.xyz.com](http://www.xyz.com/) as an ingress rule, post harbor setup.

For the OIDC integration, at the OIDC provider side, I gave both the redirect URI i.e. https://www.xyz.com/c/oidc/callback and https://www.abc.com/c/oidc/callback

After the setup and OIDC integration, I was able to login to the primary URL [www.abc.com](http://www.abc.com/), but getting a status mismatch error for the second domain [www.xyz.com](http://www.xyz.com/) and the URL in the browser after OIDC authentication redirects to https://www.abc.com/c/oidc/callback

{"errors":[{"code":"BAD_REQUEST","message":"State mismatch"}]}

In the core pod logs, I see the below error:

2022-06-01T12:41:17Z [ERROR] [/core/controllers/oidc.go:75]: State mismatch, in session: %!s(), in url: w3hn0KgXLLO7WHqRgW3gTsrAZM7dlRoL
2022-06-01T13:32:13Z [ERROR] [/core/controllers/oidc.go:75]: State mismatch, in session: %!s(), in url: lbJm9jc0cqxFbvIsBIThXpQ3NvKmHoAC

Could you please advise, if there is a way to make this setup work for OIDC based login for both URLs?

**Comment by stonezdj** [comment]
Current OIDC configure of www.xyz.com is invalid, because the registered app should be www.xyz.com and the callback URL should be https://www.xyz.com/c/oidc/callback, it is not allowed to configure the callback with a different server url, it will check if the state in current request matches the state in session.
see https://github.com/goharbor/harbor/blob/d3d4ad6a348e0cdc22c9844905c721af9d8b64a7/src/core/controllers/oidc.go#L74

**Comment by InderpreetSaini** [comment]
> Current OIDC configure of [www.xyz.com](http://www.xyz.com) is invalid, because the registered app should be [www.xyz.com](http://www.xyz.com) and the callback URL should be https://www.xyz.com/c/oidc/callback, it is not allowed to configure the callback with a different server url, it will check if the state in current request matches the state in session. see
> 
> https://github.com/goharbor/harbor/blob/d3d4ad6a348e0cdc22c9844905c721af9d8b64a7/src/core/controllers/oidc.go#L74

So does that mean, I can only login to Harbor using OIDC only with the core URL I configured in harbor.yml during the initial setup, and not with any other URL that points to the Harbor server/VM?

**Comment by stonezdj** [comment]
Yes
