### ISSUE TITLE
Deletion of Retention Policy is not Working

### ISSUE THREAD

**Issue by sunidhi271** [goharbor/harbor#16945]
I have a usecase where I need to maintain Retention policies using API.
After deleting the Retention policy , when I try to create a new retention policy via API, it gives an error that the previous retention policy already exists.

![image](https://user-images.githubusercontent.com/86234399/171797439-006da8cc-cfc3-429e-9bd3-2f0322bcb2f8.png)

![image](https://user-images.githubusercontent.com/86234399/171797482-4f72610f-cf7b-462a-834a-bdf3f10c7c18.png)

Below is my script: 
`#! /bin/bash

MODE=$1
if [[ -z "$MODE" ]];
  then
      source ../../conf/config.conf
  else
      source ../../conf/connect_harbor.sh
fi
echo ""

rm -f projects.json
rm -f input.json

echo -n "PROJECT_NAME (e.g: daas):"
read PROJECT_NAME
echo ""

echo -n "INPUT JSON FILE NAME WITH FULL PATH (e.g, /root/retention/bin/retention-policy.json): "
read INFILE_PATH
echo ""

echo ""

rm -rf logs/${PROJECT_NAME}-allProject.log
rm -rf logs/${PROJECT_NAME}-create-retention-policy.log
curl_cmd="${CURL_HARBOR_GET_API}/projects?page=1\&page_size=100\&with_detail=true -o projects.json"
sleep 1s
eval $curl_cmd >>logs/${PROJECT_NAME}-allProject.log 2>&1
echo "Find projects.json at projects.json"

cat_pid_cmd="cat projects.json | jq -r '.[] | select(.name| startswith("\"$PROJECT_NAME\"")) | .project_id'"
echo $cat_pid_cmd
PROJECTID=$(eval $cat_pid_cmd)
echo "Project ID of $PROJECT_NAME is $PROJECTID"

sed -e 's/PID/'"$PROJECTID"'/g' $INFILE_PATH > input.json

cat_input="cat input.json"
cat_input_test="cat input.json | jq"
eval $cat_input_test
#INPUT_DATA=$(eval $cat_input)
#echo $INPUT_DATA

CURL_HARBOR_POST_API="$CURL_HARBOR_API -X POST ${REGISTRY_API}"
create_curl_cmd="$CURL_HARBOR_POST_API/retentions -H \"Content-Type: application/json\" -d @input.json"
eval $create_curl_cmd >>logs/${PROJECT_NAME}-create-retention-policy.log 2>&1
echo ""

catcmdlogs="cat logs/${PROJECT_NAME}-create-retention-policy.log"
eval $cat_cmd_logs
`

**Comment by zyyw** [comment]
please use `PUT` HTTP method to update (delete) retention rules of a retention policy.

If you use `DELETE`, you will run into a similar issue to this:
* https://github.com/goharbor/harbor/issues/16288
and the workaround is this:
* https://github.com/goharbor/harbor/issues/16288#issuecomment-1135584216
