### ISSUE TITLE
Require image for ARM64 architecture 

### ISSUE THREAD

**Issue by odidev** [goharbor/harbor#16959]
Hi Team, 

I am trying to use **goharbor/harbor** on ARM64 architecture but it seems it is not available for arm64.   

There seem to be multiple dockerfiles and [docker images](https://hub.docker.com/u/goharbor) present, from which [harbor-core](https://hub.docker.com/r/goharbor/harbor-core/tags) is the main docker image using [make/photon/core/Dockerfile](https://github.com/goharbor/harbor/blob/main/make/photon/core/Dockerfile).

So, I tried to build **goharbor/harbor-core** image on my arm64 local machine using command `docker build -t image_name .` but it is failing for [FROM ${harbor_base_namespace}/harbor-core-base:${harbor_base_image_version}](https://github.com/goharbor/harbor/blob/main/make/photon/core/Dockerfile#L3) command and giving` invalid reference format` error. 

After investigating I found that it is using [dockerfile.base](https://github.com/goharbor/harbor/blob/main/make/photon/db/Dockerfile.base) as the base image in above error, so I have successfully build this base image from  [dockerfile.base](https://github.com/goharbor/harbor/blob/main/make/photon/db/Dockerfile.base) on my local arm64 machine without making any changes in [dockerfile](https://github.com/goharbor/harbor/blob/main/make/photon/core/Dockerfile) and also successfully pushed to the docker hub.

I have used the above base image to build the arm64 docker image for **goharbor/harbor-core** but it is failing with below error on both amd64 and arm64 architecture.
```
Step 7/15 : COPY ./make/photon/core/harbor_core /harbor/ 

COPY failed: file not found in build context or excluded by .dockerignore: stat make/photon/core/harbor_core: file does not exist 

```

I checked this file but it is unavailable. 

It will be very helpful if the image is released for the ARM64 platform.  

Do you have any plans to release an ARM64 image? 

If required, I am happy to contribute. But as a start, can you please provide me with some pointers on the above issues?

**Comment by MkAnHui** [comment]
for harbor-arm 
    harbor_core not foud  , you should check. command  return success `make compile COMPILETAG=compile_golangimage`

**Comment by laurivosandi** [comment]
Please provide multi-arch Docker images that work on both AMD64 and ARM64
