### ISSUE TITLE
Errors about compile_core

### ISSUE THREAD

**Issue by lqywow** [goharbor/harbor#16950]
When I use the source code to build(make install), I met some errors:

#github.com/goharbor/harbor/src/server/v2.0/models
../server/v2.0/models/addition_links.go:35:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:148:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:169:15: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:188:15: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:207:15: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:231:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:281:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:302:15: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:326:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:388:16: ce.ValidateName undefined (type *"github.com/go-openapi/errors".CompositeError has no field or method ValidateName)
../server/v2.0/models/artifact.go:388:16: too many errors
make: *** [Makefile:384：compile_core] 错误 2

How can I fix these errors??

**Comment by wy65701436** [comment]
please execute the make gen_apis firstly, then try again.
