### ISSUE TITLE
Administration -> Configuration -> System Page style error

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#16961]
![1661654655758_ pic](https://user-images.githubusercontent.com/72076317/172519397-5f219a39-e208-4c34-9cb9-0228c0e187fd.jpg)
![1651654655746_ pic](https://user-images.githubusercontent.com/72076317/172519581-e40cc33f-fc07-4b85-a624-0d2b320c934a.jpg)

- harbor version: v2.6.0-5dcd2ccf

**Comment by AllForNothing** [comment]
Close it as #16914 merged
