### ISSUE TITLE
LDAPS with custom client certificates

### ISSUE THREAD

**Issue by nknkgithub** [goharbor/harbor#16960]
Need to use custom client certificates i.e.

-  ldapclient.crt(signed by custom CA chain) 

- ldapclient.key

in harbor helm charts and connect to ldap server by enabling checkbox "LDAP Verify Certificate" for two way authentication between harbor and ldap server.

How can this be achieved??

**Comment by zyyw** [comment]
maybe use caBundleSecretName?
* https://github.com/goharbor/harbor-helm/blob/1.9.0/values.yaml#L390

**Comment by stonezdj** [comment]
Does it work in your env? @nknkgithub

**Comment by JqckB** [comment]
Hello,

I have in the Google LDAPs environment the necessity to send client certificate to authenticate the TLS session.
Can you look into implementing this ?
