### ISSUE TITLE
Creating project via API (POST) sets correct storage_limit, but updating (PUT) does not change it

### ISSUE THREAD

**Issue by brtduvally** [goharbor/harbor#16972]
I have been automating our management of harbor projects. Creation of the project works as expected, but updating the quota via the API doesn't seem to work. Response code was 200 as expected, but quota does not change. Using python request and PUT Also using same file as with the creation, so format appears correct (at least enough for creation). 

**Expected behavior and actual behavior:**
When doing a PUT to change the storage_limit of a project the quota of that project should be changed.

**Steps to reproduce the problem:**
Create a project, update that project with a different storage_limit via the API. 

**Versions:**

- harbor version: 2.3.0
- docker engine version: 20.10.12
- docker-compose version: N/A

**Additional context:**

Logs show a DEBUG message saying systems admin is required updating the project (id 212 here), but I am using the admin account, so I don't know if this is informational or part of a bug. 
```
2022-06-09T15:52:19Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require update action for resource /project/212
```

**Comment by brtduvally** [comment]
I'm invoking the /projects API. (https://harbor.domain.edu/api/v2.0/projects/project-name), and according to the API documentation using PUT will update the properties of the project, and that documentation includes the storage_limit value among the properties to be updated. 

Should I be calling the quota API to change the storage_limit of a project? I'm trying to make this as idempotent as possible and that should work, but it's 2 more API calls to make for each project (GET the quota ID, PUT the storage value to that ID)

**Comment by agaillar** [comment]
hi, 

I encounter the same error.
When I create a project from the `api/v2.0/projects` API (Harbor swagger) the "storage_limit" property is not taken into account.
No records are inserted in the `public.quota` and `public.quota_usage` tables.

When I create the project from the portal, the records are well added in the 2 tables.
version : 2.5.1

**Comment by brtduvally** [comment]
Still relevant and unaddressed.

**Comment by batusekerci** [comment]
Since it is so frustrating to fill all the fields in /projects/ PUT method for just a one field change (storage_limit), I think there should be a more direct method for updating the quota. I am suffering from this too.

**Comment by alexandre-k** [comment]
Hello,

I got it working with that:
```
curl -k -u '<username>:<password>' -X 'GET' 'https://harbor.local/api/v2.0/quotas?reference_id=<project_id>'

curl -k -u '<username>:<password>' -X 'PUT' \
 'https://harbor.local/api/v2.0/quotas/<quota_id>' \
 -H 'accept: application/json' \
 -H 'Content-Type: application/json' \
 -d '{"hard":{"storage":<your_quota>}}'
```
Taken from [here](https://codesti.com/issue/goharbor/harbor/17737).


Since `reference_id`  being here the `project_id`, we just need a  GET request to the project by name to get the `project_id`.
