### ISSUE TITLE
When a URL has no pagesize parameter, the default is to search for 10 tags, and I want to find all of them

### ISSUE THREAD

**Issue by 0918wang** [goharbor/harbor#16976]
When a URL has no pagesize parameter, the default is to search for 10 tags, and I want to find all of them

**Comment by AllForNothing** [comment]
@0918wang Call it  twice:
First,  get the total count from the `X-Total-Count`header of the response, then call it again and set `page_size=${total}`

**Comment by 0918wang** [comment]
> @0918wang Call it twice: First, get the total count from the `X-Total-Count`header of the response, then call it again and set `page_size=${total}`

validation failure list:\npage_size in query should be less than or equal to 100

**Comment by AllForNothing** [comment]
`List tags` API  has poor performance, So there are these limitations.

You can still use multiple Calls:

Calculate total pages   `Math.floor(total / 100) + 1`;    then get them page by page  `page=${i}&page_size=100`

**Comment by 0918wang** [comment]
> You can still use multiple Calls:
> 
> Calculate total pages `Math.floor(total / 100) + 1`; then get them page by page `page=${i}&page_size=100`

Thank you, but it will make my already messy code even messier
