### ISSUE TITLE
Export Directory for HTML Trivy Reports

### ISSUE THREAD

**Issue by pthoelken** [goharbor/harbor#16989]
It's possible to create the option in the harbor.yml file to setup the following Trivy settings? 

- automatic HTML reports from every Trivy scans
- choose Trivy HTML report output directory
- choose Trivy HTML report name pattern

**Comment by zyyw** [comment]
https://github.com/goharbor/community/pull/174

**Comment by pthoelken** [comment]
@zyyw how can I use it? Any documentations?

**Comment by danielpacak** [comment]
The whole concept of integrating Trivy with Harbor is based on Pluggable Scanners API and scanner updaters that return JSON data that is then rendered in Harbor UI as dynamic HTML. You can also consume JSON reports through Harbor RESTful APIs. However, there's no way to configure output directory and save static HTML vulnerability reports.

**Comment by pthoelken** [comment]
As we can see here there is a DIRECTORY option for Reports? https://github.com/aquasecurity/harbor-scanner-trivy#configuration

Is this not a possible solution to export the Reports?

**Comment by pthoelken** [comment]
It's maybe also possible to insert a button "Download PDF Report" in the section where I can see the Trivy HTML generated report in Harbor UI?

**Comment by danielpacak** [comment]
Please review the community proposal mentioned by us and shared your feedback there so we can keep it in one place.
