### ISSUE TITLE
concourse failing to fetch data from harbor

### ISSUE THREAD

**Issue by SOMAPANGU** [goharbor/harbor#16983]
![Screen Shot 2022-06-10 at 11 56 13 AM](https://user-images.githubusercontent.com/33832297/173105016-4f251cb2-13d8-470a-9daa-5b00e86450a4.png)
After recent upgrade, I see concourse fails to fetch the chart data it uploaded on the first run. If I rerun the pipeline with same inputs now its able to fetch the data it uploaded. Issue with all the pipeline...any fix for this?

No issue when downloading the charts from UI....

**Comment by zyyw** [comment]
could you please try to clean redis cache about chartmuseum. 
BTW, we are going to deprecate chartmuseum in the future and limited support will be provided.

**Comment by SOMAPANGU** [comment]
> could you please try to clean redis cache about chartmuseum. BTW, we are going to deprecate chartmuseum in the future and limited support will be provided.

We tried clearing the redis cache and also used the helm chat resource but its failing for the first time and when we rerun with same parameters its working.
