### ISSUE TITLE
Trivy automatic generated PDF reports to download

### ISSUE THREAD

**Issue by pthoelken** [goharbor/harbor#16993]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- In the section where I can see all vulnerabilities add a button to download the report as PDF file to send this to your manager or other person without success to harbor. 
- The other option should be an automatically PDF report to a in harbor.yml defined storage path which auto-generate the folder like image name and save up the reports in the correct image-folder locations.

**Describe the main design/architecture of your solution**
![image](https://user-images.githubusercontent.com/12643853/173352025-8c7c9d85-e68b-4daa-8956-26bcb6b7e2b7.png)

**Describe the development plan you've considered**
I'm not able and have not the time to make a development plan.

**Comment by wy65701436** [comment]
we will introduce the export scan resport feature in v2.6, refer to https://github.com/goharbor/community/pull/174, cc @prahaladdarkin
