### ISSUE TITLE
Webhook support application/json for content-type

### ISSUE THREAD

**Issue by maxhuebler** [goharbor/harbor#17002]
**Is your feature request related to a problem? Please describe.**
As well as having http/slack for notify type, I would really like to have the ability to have json as content-type as well

**Describe the solution you'd like**
Support json content-type for webhooks

**Comment by zyyw** [comment]
It has set `Content-Type: application/json`, at lease in harbor v2.5.1
* https://github.com/goharbor/harbor/blob/v2.5.1/src/jobservice/job/impl/notification/webhook_job.go#L97
* https://github.com/goharbor/harbor/blob/v2.5.1/src/jobservice/job/impl/notification/slack_job.go#L116
