### ISSUE TITLE
ui: all "pull command" buttons turn green after click

### ISSUE THREAD

**Issue by Dentrax** [goharbor/harbor#17001]
**Expected behavior and actual behavior:**
Isn't that supposed to be only last clicked "copy to clickboard" button should remain green and all others should be blue. 

**Steps to reproduce the problem:**
* 1. Jump to image artifacts
* 2. All click pull commands
* 3. All turns to green

![ezgif com-gif-maker(16)](https://user-images.githubusercontent.com/16493751/173560389-5da92ea5-74e7-4273-ba9d-4c2ac347ef00.gif)

**Versions:**

Tested on live version: https://demo.goharbor.io

**Additional context:**
`-`

**Comment by AllForNothing** [comment]
@Dentrax Thanks for the into.
Are you willing to submit a PR to improve this?

**Comment by Dentrax** [comment]
I'm not good at frontend stuff and don't know much about Harbor's domain, so probably not. :( Thanks for asking.

**Comment by AllForNothing** [comment]
@Dentrax 
It's OK, I will raise a PR to improve this later.  Put it to `target 2.6`
