### ISSUE TITLE
docker pull image timeout

### ISSUE THREAD

**Issue by finalha** [goharbor/harbor#17003]
I am using harbor v2.2.4-1bc848b3. When k8s is running "docker pull ****". The issue happened:
02:02:04  [Warning][pytorch/compile-p5kcm-hlz0v][Failed] Failed to pull image "hub.test.com/ci/clone:latest": rpc error: code = Unknown desc = Error response from daemon: Head "http://hub.test.com/v2/ci/clone/manifests/latest": Get "http://hub.test.com/service/token?account=CI-Robot&scope=repository%3Aci%2Fclone%3Apull&service=harbor-registry": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
02:02:04  [Warning][pytorch/compile-p5kcm-hlz0v][Failed] Error: ErrImagePull
02:02:04  [Normal][pytorch/compile-p5kcm-hlz0v][BackOff] Back-off pulling image "hub.test.com/ci/clone:latest"
02:02:04  [Warning][pytorch/compile-p5kcm-hlz0v][Failed] Error: ImagePullBackOff
02:02:18  [Normal][pytorch/compile-p5kcm-hlz0v][Pulling] Pulling image "hub.test.com/ci/clone:latest"
02:02:18  ERROR: Unable to pull Docker image "hub.test.com/ci/clone:latest". Check if image tag name is spelled correctly.

But I can't find the useful information in the core.log of harbor.
Because the image(hub.test.com/ci/clone:latest) may be download for many jobs in a short time period. So should I change the default values in harbor.yml
`max_job_workers: 10`
`webhook_job_max_retry: 10`
to
`max_job_workers: 100`
`webhook_job_max_retry: 100`

**Comment by Vad1mo** [comment]
jobs are for background processes, The timeout you see is because of wrong ingress or LB config.

**Comment by finalha** [comment]
> jobs are for background processes, The timeout you see is because of wrong ingress or LB config.

The issue happened timelessly and the configration of ingress is OK. How to check the load balance configration of harbor?

**Comment by Vad1mo** [comment]
This doesn't look like a problem/issue with harbor but your configuration or even k8s setup. Wit so little information it is even hard to make any wild guesses about what it could be.

**Comment by zyyw** [comment]
How do you install the harbor instance?

**Comment by finalha** [comment]
> How do you install the harbor instance?

In a virtual machine with docker instead of k8s, data is in NAS.

**Comment by finalha** [comment]
I have set the corntab of jenkins job like H(10-20) 5 * * * to reduce the high concurrency calling the harbor service and the issue did not happen for some days.
