### ISSUE TITLE
Installation requires docker-compose while docker instructions only guide to use docker compose

### ISSUE THREAD

**Issue by varjoti** [goharbor/harbor#17013]
Problem shown below. I have followed the instructions to the letter, but I only have docker compose instead of docker-compose. I went around this problem by installing docker-compose 2.6 as standalone, but now I have it in both under docker and as standalone which is of course not ideal. I am running RHEL8 (following Centos 8 guide).

`[root@testdomain-harbor harbor]# sudo ./install.sh

[Step 0]: checking if docker is installed ...

Note: docker version: 20.10.17

[Step 1]: checking docker-compose is installed ...
✖ Need to install docker-compose(1.18.0+) by yourself first and run this script again.
[root@testdomain-harbor harbor]# docker compose version
Docker Compose version v2.6.0`

**Comment by MinerYang** [comment]
Hi @varjoti ,
Sorry for your inconvenience. FYI, we've already added support for docker compose v2 and you would possible to use it in the next release.
For now, you need to install docker-compose (v1.18.0+ )individually, for example v1.29.2, pls reference to this doc. https://github.com/docker/compose/

**Comment by zyyw** [comment]
please try it in harbor 2.6.0 (to be released in the future)
