### ISSUE TITLE
Push Based replication rule with a label source filter not working when image retagged

### ISSUE THREAD

**Issue by KealanM** [goharbor/harbor#17014]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Having configured a push based replication rule from Harbor to Google Container Registry with a source filter that is based on a label I would expect that when a tag is applied to the image with said label via the API or UI the replication rule should fire. It how ever does not. 

**Steps to reproduce the problem:**
Create a simple push based replication rule with a source filter of label. 
Apply the label to a image (not expecting replication at this point as add label does not fire replication sadly).
Add a new tag to the image through the API or UI. 
At this point replication should occur as the image has been retagged and has the required label but no replication occurs. 
As a test I removed the label filter and retagged the image again and replication did occur.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.3.5

**Additional context:**

**Comment by zyyw** [comment]
Reproduced: It looks like the the push mode (event-based) replication doesn't honor the `Label` filter of `Source resource filter`.

BTW, tried push mode (Manual trigger) doesn't have this issue, which means images with `Label` filter can be replicated over if manually triggered.
