### ISSUE TITLE
Harbor as a pull through cache. -- need to create project.

### ISSUE THREAD

**Issue by PhoenixMage** [goharbor/harbor#1702]
I have configured an instance of Harbor 0.50 (ova) to act as a pull through cache per the instructions at chttps://github.com/vmware/harbor/blob/master/contrib/Configure_mirror.md

Everything works fine except for each project on the hub website I need to manually create a corresponding project in Harbor.

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by reasonerjt** [comment]
This is a limitation and we don't plan to fix it.
