### ISSUE TITLE
The resource filter does not take effect when replication management is used to pull remote warehouse images in version 2.1.0

### ISSUE THREAD

**Issue by yinmin2020** [goharbor/harbor#17030]
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
The resource filter does not work when harbor2.1.0 uses replication management to pull remote repository images. For example, if the name library/** is set to pull, all images in the remote repository will be pulled down. The remote warehouse is the SWR of huawei cloud
**Versions:**
2.1.0
![image](https://user-images.githubusercontent.com/65068467/174466030-401d1a59-f236-474a-8007-f9d06c3e541e.png)

**Comment by zyyw** [comment]
by `if the name library/** is set to pull, all images in the remote repository will be pulled down`, do you mean all images under other projects are also being pulled down?

**Comment by yinmin2020** [comment]
Yes, I have adjusted the permissions of huawei cloud SWR users. A new IAM account is set up and only the minimum read-only permissions are granted to designated organizations instead of the SWR-admin account. The purpose is to force the IAM account to only read the warehouse I want. In fact, it should be harbor API and SWR API match, harbor2.0 and above have tried
