### ISSUE TITLE
Usage of CVE Scanner makes Pull-Based Retention policies unusable

### ISSUE THREAD

**Issue by keydon** [goharbor/harbor#17049]
**Expected behavior and actual behavior:**
Actual: Build-In CVE Scanner **changes** "last pull timestamp" when scanning a image
Expected: Build-In CVE Scanner **LEAVES** "last pull timestamp" **unchanged** when scanning a image

**Steps to reproduce the problem:**
Scan an image with i.e trivy

**Versions:**
- harbor version:v2.5.0-98e1b82f
- trivy: v0.24.2

**Additional context:**
Makes Pull-Based retention policies useless.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/2421541/174833462-f746f6a7-7f2a-4c96-8d37-17b773a08468.png">

Because all images are scanned every night.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/2421541/174833696-f3805b1f-c2ee-46ed-b959-c50d367b742e.png">

**Comment by MinerYang** [comment]
duplicate with this https://github.com/goharbor/harbor/issues/14638
