### ISSUE TITLE
Update pull time failed - log messages after upgrading to 2.5.1

### ISSUE THREAD

**Issue by sizowie** [goharbor/harbor#17044]
After updating from 2.4.0 to 2.5.1 every 10 seconds multiple this kind of log messages appear:

Jun 21 09:10:30 192.168.13.1 core[1517]: 2022-06-21T07:10:30Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 31295, tag 0 not found
Jun 21 09:10:30 192.168.13.1 core[1517]: 2022-06-21T07:10:30Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 31294, tag 0 not found
Jun 21 09:10:30 192.168.13.1 core[1517]: 2022-06-21T07:10:30Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 41868, tag 0 not found
Jun 21 09:10:30 192.168.13.1 core[1517]: 2022-06-21T07:10:30Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 41867, tag 0 not found
...

Any hints?

**Versions:**
- harbor version: 2.5.1
- docker engine version: 20.10.12-3.el7.x86_64
- docker-compose version: 1.28.2

**Comment by chlins** [comment]
Don't worry, it just a warning log and will be optimized in the version 2.6.

**Comment by sizowie** [comment]
Alright thank you !
