### ISSUE TITLE
Add documentation for Nydus Acceleration service

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#17077]
What can we help you?
Add documentation for Nydus Acceleration service

**Comment by a-mccarthy** [comment]
@MinerYang thanks for filing this issue. Can you provide more context about Nydus Acceleration service and the docs needed for this? Is there another issue or PR that has some details i can review? :)

**Comment by MinerYang** [comment]
Hi @a-mccarthy ,

This is a reference for the context you might need https://github.com/goharbor/acceleration-service
I will raise a PR once the testing's done (in process now ) and provide you more details about Harbor with Nydus Acceleration service ASAP.

Thanks!

**Comment by MinerYang** [comment]
Hi @a-mccarthy ,
This PR refer to this new feature https://github.com/goharbor/harbor/pull/17126.
Basically, `nydus` artifact is as an accessory of a subject artifact, which is pretty much like the cosign accessory.
user can trigger a webhook configured on Harbor to let the image acceleration service convert the image then push back to Harbor.
We can discuss more details when you are convenient.

Best,
Miner

**Comment by MinerYang** [comment]
Support of manifest list in Nydus service side is still remained to be discussed.
Harbor would hold this feature this v2.6 release and enable it until there's a clear plan for nydus/image-acceleration service to support manifest index / manifest list considered to better user experience
https://github.com/goharbor/harbor/pull/17233
