### ISSUE TITLE
How to hide Repositories in images after docker pull

### ISSUE THREAD

**Issue by ChenJhua** [goharbor/harbor#17076]
I have a harbor repository, address `my.harbor.com`. There is a project name `dev`, I want to put all the packages in the dev project, but if I want to pull the image, I need to specify `docker pull dev/a/b:v1`.
 I want to Pull the image into the dev project through `docker pull a/b:v1`. 
At the same time, docker images are displayed as `a/b:v1` instead of `dev/a/b:v1`.
Can you tell me any way to achieve what I want?

My original purpose was that I had two projects, `dev` and `release`. 
One for development storage and one for publishing. 
But I need `docker pull dev/a/b:v1` or `docker pull release/a/b:v1` to pull the image.
 I want to use a tag to distinguish between pulling the image from dev or release. 
At the same time, the image name is viewed using `docker images` as `a/b:v1`

**Comment by MinerYang** [comment]
I don't think you can do this, since the project/repository/artifact is the way you navigate to the specific artifact.
