### ISSUE TITLE
Add document for audit log purge and forward

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#17074]
Refer [proposal](https://github.com/stonezdj/community/blob/65e779d6cd035499451c064ef949e086a98fb444/proposals/new/audit_log.md)

Add a section on purge/forward audit log.

**Comment by stonezdj** [comment]
Add two options in system settins tab.

User could forward the audit log to a sys log endpoint, (if the user install harbor with docker-compose, the sys log endpoint in local should be "harbor-log:10514") 
User could disable to log audit log in database table `audit_log`, before enabling this option, the audit log forward endpoint should be configured.
<img width="921" alt="Screen Shot 2022-06-27 at 4 01 25 PM" src="https://user-images.githubusercontent.com/2696760/175896184-1429bd40-d891-4e53-8330-31e41e3e3b0f.png">

**Comment by a-mccarthy** [comment]
docs for this were merged into the website
