### ISSUE TITLE
Project Admin add Member Forbidden

### ISSUE THREAD

**Issue by luandrea** [goharbor/harbor#17084]
I added a user in a project with the Project Admin role, but he cannot add other members to it because no users appears in the select user New Member form.

If I take a look at the request that is send when he insert the username, I see a call to api/v2.0/users?q=username%253D~ma&page_size=10&page=1 that returns a 403 Forbidden error.

The same user can use the search users API without any issues, for example:
api/v2.0/users/search?page=1&page_size=10&username=mam

This user is an LDAP user and doesn't have Harbor administration permissions.

I'm using Harbor Version v2.5.0-98e1b82f.

**Comment by stonezdj** [comment]
If the LDAP user never login to Harbor it will not appear in the add user member form. it work as designed.

**Comment by luandrea** [comment]
It doesn't work also if the user have already logged in.

**Comment by stonezdj** [comment]
Yes, it work as design, User is a system level resource, project admin have no permission to list it. see
https://github.com/goharbor/harbor/blob/e2e3bcca1c38e5041ea6f1d22409309818f100b7/src/common/rbac/system/policies.go#L20
https://github.com/goharbor/harbor/blob/2111703d8dc020c36c66d809db37d6e0aa612456/src/common/rbac/project/rbac_role.go#L25
