### ISSUE TITLE
OIDC Security Issue

### ISSUE THREAD

**Issue by geoger** [goharbor/harbor#17096]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
1)  use oidc user to do login
2)  log out
3)  use another oidc user to login in the same browser
4)  the second user will be as the first OIDC user 
5)  clear browser cache will make it normal.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.5.1]
- docker engine version: [y.y.y]  use aws eks  v 1.22
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by geoger** [comment]
the second oidc uer use "LOGIN VIA LOCAL DB" to do login

**Comment by geoger** [comment]
@MinerYang  
There is an easy way to fix this issue. it is disable OIDC user could choose "LOGIN VIA LOCAL DB" to do login, only allow local db user could do login when click "LOGIN VIA LOCAL DB"

**Comment by geoger** [comment]
if not clear browser cache /history.  The second oidc user choose to  click "LOGIN VIA LOCAL DB" to do login, after  input  name and password of the second OIDC user, he/she could login, but the second oidc user will find that the user information and all UI displays was wizardly the previous OIDC user, that is to say, he/she could act as the previous OIDC user after login

**Comment by MinerYang** [comment]
Thanks for describing the details. We will try to reproduce the problem and have a test on this situation.

**Comment by AllForNothing** [comment]
@geoger What did you do for the `log out` step?  OIDC users can not log out on the Harbor side,  you need to go to the portal of the OIDC provider and logout.  See #15470

**Comment by geoger** [comment]
@AllForNothing. Got it,  I did not know about it before. I think it has no relationship with this issue.  As any user of Harbor,  could click 'logout' button to do logout for Harbor, he/she did not know he/she actually not logout .    Even he/she did not do logout , open another window in the same browser then do login by click "LOGIN VIA LOCAL DB", input oidc user name and password,  he/she still could wizardly find that the profile is the previous OIDC user.

**Comment by AllForNothing** [comment]
Closing it as it's not a security issue. If you have any idea to improve the user experience, welcome to open another issue  as `kind/requirement`
