### ISSUE TITLE
The LDAP option cannot be selected except for the database

### ISSUE THREAD

**Issue by yangqi766** [goharbor/harbor#17104]
![image](https://user-images.githubusercontent.com/13087771/176618702-37f1138d-ab79-4814-945c-468117fa2b1f.png)

The LDAP option cannot be selected except for the database.

why ??

**Comment by MinerYang** [comment]
Hi @yangqi766 
which version of Harbor you were using.
Or could you provide more context, for example harbo.yml
Thanks.

**Comment by stonezdj** [comment]
Because there is an existing a non-admin user created in Harbor user, you should delete these non-admin users then you can change to LDAP auth.
