### ISSUE TITLE
Users with Developer role cannot see "Policy" tab for any project

### ISSUE THREAD

**Issue by neothematrix** [goharbor/harbor#17100]
I've searched the issues but couldn't find anything related.
The [documentation ](https://goharbor.io/docs/2.5.0/administration/managing-users/user-permissions-by-role/) states that "Developer" role should have Create/delete/Enable/Deactivate tag retention rules permission, however, if I login to harbor and open a project for which I'm a "Developer" the policy tab does not appear so I cannot see or modify any policy for that project.
Am I missing something?
If I upgrade my role to "Maintainer" the Policy tab correctly appears.

Currently using Harbor 2.5.1

thanks!

**Comment by AllForNothing** [comment]
@neothematrix  Thanks for your info.
This is sure a bug/inconsistency,  and add this to target2.6

**Comment by zyyw** [comment]
this PR should resolve this issue: 
* https://github.com/goharbor/harbor/pull/16514
