### ISSUE TITLE
Invalid user name or password on fresh install

### ISSUE THREAD

**Issue by premsgr6** [goharbor/harbor#17122]
![image](https://user-images.githubusercontent.com/46933846/177282943-f147efaa-68d1-4e45-86db-e8582917faf1.png)

After helm install XXX, and wait for all pods running.
I enter the portal using default username/password ( admin/Harbor12345), I got "Invalid user name or password".

I have no idea why I cannot login.

![image](https://user-images.githubusercontent.com/46933846/177283730-7c2793e5-c710-40dd-89f7-49663392e627.png)

i have checked the logs of harbor-core

![image](https://user-images.githubusercontent.com/46933846/177284368-a6390f7a-7227-4d93-b6b5-2570305d5480.png)

i have checked the nginx logs  & all pods are in running state

![image](https://user-images.githubusercontent.com/46933846/177284774-a95c4212-33ef-4ec2-a8f2-248cbe95df56.png)

**Comment by wangxg422** [comment]
I also have the same problem. The password is clearly correct, and there is no error log for each pod. What is the reason?

**Comment by wangxg422** [comment]
Maybe it has something to do with the browser. I reinstalled harbor with helm, and then opened the privacy window of the browser to log in. It was successful

**Comment by premsgr6** [comment]
@wangxg422 Which helm chart version you have used? I have reinstalled it couple of time setting different passwords and harbor-core secrets is able to pull the new password too, still the same issue on browser. Tried it on privacy window too, didn't work.

**Comment by wangxg422** [comment]
@premsgr6  The chart package I downloaded with the official tutorial is "helm fetch harbor/harbor --untar". I am a self signed certificate. I log in with edge browser and prompt the wrong user name and password (as shown in the figure). However, I can log in normally using the privacy window of edge.

![image](https://user-images.githubusercontent.com/35413234/177446222-03c2869c-2daf-4e41-a63c-db220ea54130.png)

**Comment by prem9966** [comment]
@wangxg422  I tried to reinstall with latest version with default username admin / password Harbor12345 , I am facing the same issue with diff version 1.8.0 , 1.9.0 & 1.9.2 (latest)  & tried to loging with diff private browser

**Comment by premsgr6** [comment]
When I expose the harbor with LoadBalancer on http same credentails work. With ingress and cert-manager certificate for https it gives Invalid username and password error.

**Comment by wangxg422** [comment]
@premsgr6 @prem9966  This is so strange. Have you deleted the PV and PVC created by harbor when uninstalling? Several of them will not be deleted automatically. Try other ways to expose services, such as nodeport or ingress. After reinstallation, if the browser still prompts that the user name and password are wrong, you can try logging in with docker login

**Comment by wangxg422** [comment]
@premsgr6 @prem9966  This is so strange. Have you deleted the PV and PVC created by harbor when uninstalling? Several of them will not be deleted automatically. Try other ways to expose services, such as nodeport or ingress. After reinstallation, if the browser still prompts that the user name and password are wrong, you can try logging in with docker login

**Comment by chlins** [comment]
@premsgr6 Could you provide the API response when login to harbor?

**Comment by wouter2397** [comment]
Same problem here, but I do not get any situation working.
I tried:

1) HTTPS ingress
2) HTTP ingress
3) private browser window

None of this worked...

**Comment by premsgr6** [comment]
@wouter2397 Thanks for u reply i have deleted all the pv & pvc reinstalled its working with http, issue is same when i attach ingress annotations its triggered same error  with invalid username & password

**Comment by wouter2397** [comment]
@premsgr6 I installed Harbor with Helm and had to configure the following values according to the ingress domain that is used by the ingress controller.

```
expose:
  ingress:
    hosts:
      core: core.harbor.domain
      notary: notary.harbor.domain

externalURL: https://core.harbor.domain
```

Once I configured these values with the correct domains, I was able to login successfully.

**Comment by premsgr6** [comment]
Is there any possibility  can we have call  Plz do let me know


Thanks,
With Regards,

PREM SAGAR . PODISHETTY  
 
  On Thu, 14 Jul 2022 at 10:59 am, ***@***.***> wrote:   


@premsgr6 I installed Harbor with Helm and had to configure the following values according to the ingress domain that is used by the ingress controller.
expose:
  ingress:
    hosts:
      core: core.harbor.domain
      notary: notary.harbor.domain

externalURL: https://core.harbor.domain

Once I configured these values with the correct domains, I was able to login successfully.
