### ISSUE TITLE
Tags for images from docker hub libraries and quay.io in proxy cache project are not set

### ISSUE THREAD

**Issue by jok26r** [goharbor/harbor#17135]
**Expected behaviour:**
After an image is pulled from docker hub or quay.io the image has to have tags

**Actual behavior:**
Image tags are absent

**Steps to reproduce the problem:**
1. Add [docker hub](https://hub.docker.com) or [quay.io](https://quay.io) registry
2. Create cache proxy project using the registry created above3. 
3. Try to pull image, for example:
- docker pull registry_name/project_name/quay/cilium/cilium:v1.11.3
- docker pull registry_name/project_name/library/ubuntu:22.04

**Versions:**
- harbor version: [2.5.1]
- docker engine version: [20.10.7]
- docker-compose version: [1.25.0]

**Additional info**:
The only interesting thing I found in the core logs is:
`2022-07-06T18:49:56Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 486, tag 0 not found`

How it looks in the UI:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/25959854/177622367-dd8f7603-e1ff-4b13-aeed-6f9fff44258d.png">

**Comment by chlins** [comment]
The warning log is just a noise which will be removed in 2.6, and actually the proxy cache has delay to cache the images, so does the tags never show up for long time?

**Comment by jok26r** [comment]
> The warning log is just a noise which will be removed in 2.6, and actually the proxy cache has about 10-15 minutes delay for caching the images, so does the tags never show up for long time?

Almost never, there are several images that have tags. For example:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/25959854/177940869-59b0caf1-951a-490d-a145-edc908fd79b2.png">

But others don't:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/25959854/177941278-d2546c24-542a-4235-8f86-b189989e9338.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/25959854/177941041-78e42ed7-3a6e-458d-b2c8-44e75069ebe6.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25959854/177941100-4986156f-ed93-4961-a3b2-92675d03d9f5.png">

Images that are from docker hub, but not from library, usually have tags:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/25959854/177941481-550bceee-ed1c-4264-a5bf-252e7fd27264.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/25959854/177941527-30562f75-6023-4e7e-8e53-1ec55350a698.png">

**Comment by chlins** [comment]
@stonezdj Could you take a look?

**Comment by chlins** [comment]
@jok26r The behavior depends on the client, for example, if docker client pull image by digest from harbor there will be no tags in proxy cache, otherwise if pull by tag that exact should have tags in proxy cache. Could you check the audit logs to see whether the client pull image by digest or tag?

**Comment by jok26r** [comment]
> @jok26r The behavior depends on the client, for example, if docker client pull image by digest from harbor there will be no tags in proxy cache, otherwise if pull by tag that exact should have tags in proxy cache. Could you check the audit logs to see whether the client pull image by digest or tag?

No, I pull all images by tags. Here are logs for cilium:v.1.11.6:
_Jul  6 16:20:20 172.27.0.1 core[15924]: 2022-07-06T13:20:20Z [WARNING] [/server/middleware/repoproxy/proxy.go:143]: Artifact: quay/cilium/cilium:v1.11.6, digest: is not found in proxy cache, fetch it from remote repo
Jul  6 16:20:21 172.27.0.1 core[15924]: 2022-07-06T13:20:21Z [WARNING] [/server/middleware/repoproxy/proxy.go:143]: Artifact: quay/cilium/cilium:, digest:sha256:f7f93c26739b6641a3fa3d76b1e1605b15989f25d06625260099e01c8243f54c is not found in proxy cache, fetch it from remote repo
Jul  6 16:20:21 172.27.0.1 core[15924]: 2022-07-06T13:20:21Z [WARNING] [/server/middleware/repoproxy/proxy.go:143]: Artifact: quay/cilium/cilium:, digest:sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 is not found in proxy cache, fetch it from remote repo
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'P2PPreheat' on topic 'PUSH_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-harbor#proxy-cache-service OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'InternalArtifact' on topic 'PUSH_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-harbor#proxy-cache-service OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'AuditLog' on topic 'PUSH_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-harbor#proxy-cache-service OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'Replication' on topic 'PUSH_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-harbor#proxy-cache-service OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/controller/event/handler/webhook/artifact/artifact.go:75]: []
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'ArtifactWebhook' on topic 'PUSH_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-harbor#proxy-cache-service OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'InternalArtifact' on topic 'PULL_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-username OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'AuditLog' on topic 'PULL_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-username OccurAt-2022-07-06 13:21:02
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/controller/event/handler/webhook/artifact/artifact.go:75]: []
Jul  6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-sha256:c52dbdf7a07cc7ad5e73eecf1ac79e5191d6ec57350c10ef536267c620f9c7f6 Operator-username OccurAt-2022-07-06 13:21:02
Jul  6 16:21:05 172.27.0.1 core[15924]: 2022-07-06T13:21:05Z [WARNING] [/controller/event/handler/internal/artifact.go:184]: failed to update pull time for artifact 442, tag 0 not found_

By the way, my harbor installation uses squid proxy, but there are no any denied request. Probably it can be important.

**Comment by jok26r** [comment]
> Although you pull image by tag like `docker pull cilium:v.1.11.6` but the docker daemon wouldn't necessarily use tag to pull, sometimes the daemon will head this tag firstly and then get the digest, finally pull the image by digest, from your logs it shows `Jul 6 16:21:02 172.27.0.1 core[15924]: 2022-07-06T13:21:02Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-442, Repository-quay/cilium/cilium Tags-[] Digest-`, here Tags is empty which means this image pulled by digest instead of tag.

Hence it means there is no way to fix this issue, right?

**Comment by chlins** [comment]
Yes, current behavior is by design.

**Comment by jok26r** [comment]
Thanks a lot for the help. We can close the issue, I guess.

**Comment by avestuk** [comment]
@chlins Do you know what causes docker to behave in this way? We rely on image tags to give us information about vulnerabilities so it'd be useful if we could get tags for all images.

**Comment by strom18** [comment]
same issue here, did you find a solution to force the daemon to pull the image tag instead of digest ?

**Comment by jok26r** [comment]
> same issue here, did you find a solution to force the daemon to pull the image tag instead of digest ?

Unfortunately not.
