### ISSUE TITLE
[OIDC] Filtering groups is not supported when reads user groups

### ISSUE THREAD

**Issue by colinlabs** [goharbor/harbor#17130]
When the authentication mode is switched to ODIC, after the user logs in through OIDC, by default, all the groups of the current user in the OIDC will be fetched and all the user groups will be written to the local database. I don't think this is an expected behavior, which will disclose the user group information of OIDC. It is hoped that OIDC will support group filtering familiarity to match specified groups instead of all groups. eg: group prefix or group regular expression.

**Comment by stonezdj** [comment]
Current LDAP auth support filter by LDAP group filter, it seems that the OIDC has no similar setting.

**Comment by colinlabs** [comment]
yeah,so may you should provide a way to filter OIDC group, otherwise all group in OIDC will be writed to harbor DB
