### ISSUE TITLE
Validation Helm chart upload via UI 

### ISSUE THREAD

**Issue by sizowie** [goharbor/harbor#17139]
Is there any input/upload validation (based on size, format, etc.?) implemented for the helm chart upload in the Harbor UI?

I've created a simple helm chart with a big file (2GB) in it. Compressed size was about 200MB. While uploading the chart via GUI the harbor-core process got stuck and the process memory consumption increased until it crashed. Far more than the 2 GB - looks like a memory leak.

harbor version: 2.5.1
docker engine version: 20.10.12-3.el7.x86_64
docker-compose version: 1.28.2

**Comment by stonezdj** [comment]
Chartmuseum is going to deprecated, we have no intention to add new feature for it, please use OCI registry to manage helm chart.
