### ISSUE TITLE
docker for macos  docker  login harbor  error

### ISSUE THREAD

**Issue by GeorGeWzw** [goharbor/harbor#17141]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/46982191/177788997-c7ad919d-bf1f-4224-ad04-3c446cd43471.png">

**Comment by chlins** [comment]
Could you login other registry like `dockerhub` successfully? It looks like your docker client error.

**Comment by GeorGeWzw** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/46982191/177908399-2fee2f7e-7d04-40bb-94bb-bd590c796546.png">
Logging in to dockerHub is OK @chlins

**Comment by GeorGeWzw** [comment]
I just logged in to Harbor again. Now it is OK @chlins

**Comment by chlins** [comment]
Close as resolved, feel free to reopen it if you encounter the issue again.
