### ISSUE TITLE
Problem with logging into the docker via HTTP.

### ISSUE THREAD

**Issue by PKulesza-iswireless** [goharbor/harbor#17148]
Hi,

This issue is partly relates to https://github.com/goharbor/harbor/issues/17110. I created Harbor again but now for HTTP connection. I did this because I thought it would help with the errors. The certificates I generated caused problems so I thought that if I omitted them, the errors would disappear, but it did not help. Error `Error response from daemon: Get "https://xxx.xxx.xxx.xxx/v2/": x509: cannot validate certificate for mydomain.test.com because it doesn't contain any IP SANs` has disappeared but a new one has appeared.

`docker login http://xxx.xxx.xxx.xxx`
`Username: admin`
`Password: Harbor12345 - password form harbor.yaml`
`Error response from daemon: Get "https://xxx.xxx.xxx.xxx/v2/": dial tcp xxx.xxx.xxx.xxx:443: connect: connection refused`

Best regards,
Piotr

**Comment by chlins** [comment]
You could try to add your harbor endpoint to docker daemon config `insecure-registries`, refer to https://docs.docker.com/registry/insecure/.

**Comment by chlins** [comment]
Also you could try to `docker login http://xxx.xxx.xxx.xxx:80`.
