### ISSUE TITLE
Wrong number of images shown when signed with cosign

### ISSUE THREAD

**Issue by steffann** [goharbor/harbor#17145]
**Expected behavior and actual behavior:**
I have a repository with 9 artifacts: 6 images and 3 manifests:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/509689/177984028-68deedf4-b347-4c95-8a30-44d836092564.png">

But after I sign them with cosign I only see 4 images and 2 manifests:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/509689/177984200-10f9feef-ae99-4540-873e-c7f68a0e06e2.png">

But… it still says "1 - 9 of 9 items" so the images are still there. It turns out that when I increase the page size (from 15 to 25 for example) the artifacts get shown:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/509689/177984413-18fc9184-3e8a-43c5-ab35-abaa2ba118f4.png">

Images disappearing after signing them gave me quite a shock, but I guess it's just a small bug in the query based on the page size :)

**Steps to reproduce the problem:**
- Start with a repository with unsigned images
- Sign the images with cosign
- If the total number of artifacts (images + cosign) if larger than the page size the wrong number of artifacts is shown

**Versions:**
- harbor version: v2.5.3-797c3536
- docker engine version: 20.10.12
- docker-compose version: 1.25.0

**Comment by AllForNothing** [comment]
@steffann Can you post the `X-Total-Count` of the artifacts API  for each screenshot  like below:
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/30999793/178187566-a18eb1fe-4500-48bd-be50-2846db979637.png">
