### ISSUE TITLE
Subpage Helm Charts in projects

### ISSUE THREAD

**Issue by PKulesza-iswireless** [goharbor/harbor#17147]
Hi,

I'm a new Harbor user, and just starting to get to know how it works.  I am mainly trying to familiarize myself with Harbor 2.5.x but I am also exploring 1.10.x. I am particularly interested in the functionality of supporting Helm Chart. This is where my main problem appeared, the documentation shows the Helm Charts subpage, but it is not on the website.
![image](https://user-images.githubusercontent.com/70103623/178147423-8b486dd3-1862-456c-b709-38b6b6addb30.png)
At first, I thought its lack was due to the fact that it was merged with Repositories version 2.x.x. However, version 1.10.x does not have it either, someone could tell you what the reason of it? I was very interested in the possibility of sending Helm archives to the website from the GUI level.

Best regards,
Piotr

**Comment by chlins** [comment]
The Helm charts subpage backend supported by chartmuseum, so when you install harbor if by docker-compose, you should run as `./install.sh --with-chartmuesum`. And actually chartmuseum will be deprecated in harbor, so suggest to you switch to OCI chart, harbor 2.x can native support that, the chart can be pushed like image, and no additional subpage for chart.
