### ISSUE TITLE
How to ignore certificate verification to log in to docker successfully

### ISSUE THREAD

**Issue by ChenJhua** [goharbor/harbor#17140]
I have 2 harbor， I want to use https； build a dual-master model and use a private certificate。
But I want to ignore the certificate in the internal network
so, i set `--insecure-registry https://10.222.3.156:8443` to docker.
but i use docker login:
```
[root@master-001 harbor]# docker login https://10.222.3.156:8443 -uadmin -pHarbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://10.222.3.156:8443/v2/": Get "https://None:8443/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry": dial tcp: lookup None on 10.96.0.10:53: server misbehaving
```
version: harbor2.5.2 offline install.
use docker-compose

I can configure it according to the official website, but I don't want to use such a complicated certificate operation
```
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ./harbor.key -out ./harbor.crt -subj "/CN=sina/O=ddr"
```
i only use key and crt 
@wy65701436

**Comment by chlins** [comment]
The error doesn't look like a certificate error, but a domain resolution error.

**Comment by ChenJhua** [comment]
> The error doesn't look like a certificate error, but a domain resolution error.

yet, i find not set hostname, have this error.

**Comment by chlins** [comment]
The hostname will not be set by default, you should set this value in the `harbor.yml`.

**Comment by ChenJhua** [comment]
> The hostname will not be set by default, you should set this value in the `harbor.yml`.

I found a problem with harbor2.5.2. When I execute ./prepare as root, the configuration of the root user will appear in common/config, causing the harbor to start abnormally

**Comment by ChenJhua** [comment]
Hello, after `systemctl restart docker`
my harbor no longer listens to 443
but `docker-compose ps` seems to be healthy, and `docker ps` is also normal. 
But harbor is not accessible, and docker exec cannot enter the container
can you tell me how to monitor this exception and recover?
@chlins

**Comment by chlins** [comment]
You could try to restart harbor service, `docker-compose down` and `docker-compose up -d`

**Comment by ChenJhua** [comment]
Hi, I have one more question.
That is, I have two primary and secondary docker-compose harbor warehouses.
I want to access both at the same time in lb. But there seems to be a problem with the token, how should I do it.
@chlins 
```
harbor parse token error, crypto/rsa: verification error
```
