### ISSUE TITLE
Harbor doesn't replicate LDAP permissions for projects.

### ISSUE THREAD

**Issue by perrfect** [goharbor/harbor#17154]
Hello.
I have two Harbor servers which run via docker-compose, version 2.5.0.
On the first server I've created replication to the second server.
I replicate all type of resources and replication works fine.

On each server setup-ed  LDAP authentication and it works fine too.
But when I'm creating a new project and give some permissions for users or groups, these permissions don't replicate.
Can Harbor replicate users, groups and permissions?

**Comment by stonezdj** [comment]
No, only images/helm chart are replicated.

**Comment by perrfect** [comment]
> No, only images/helm chart are replicated.

Hello. Thank you for your reply.
But in my case, when I have more than 10 developers and they need to create projects themselves, is not good change permissions for all projects on a main server and replica.
Maybe, in this case is there a way how can replicate LDAP permissions or is possible add this function in the next release?

**Comment by Vad1mo** [comment]
@perrfect you should use groups and put all the groups in LDAP and just map it on harbor 1:1, this way you don't need to replicate groups. 

Replication of Settings is currently not in the scope of Harbor.

**Comment by perrfect** [comment]
> @perrfect you should use groups and put all the groups in LDAP and just map it on harbor 1:1, this way you don't need to replicate groups.
> 
> Replication of Settings is currently not in the scope of Harbor.

Hello. Thank you for your reply.
But when I've created a project on one server, added members to this project with some permissions and then replicated this project to another server and try to push image, got an error:
`unauthorized: unauthorized to access repository: replication-test/ubuntu, action: push: unauthorized to access repository: replication-test/ubuntu, action: push  `

When I've added members to this project on replicate server and try to push, everything is ok.
But this case is not good, because I need to add members and set permissions on main server and replica for more then 100 projects manually.

**Comment by Vad1mo** [comment]
The logic should come from LDAP which use has permissions on which project.  This is the only solution there is at the moment. 

If you think this feature is valuable for you and other, we are happy to accept contributions.

**Comment by perrfect** [comment]
> The logic should come from LDAP which use has permissions on which project. This is the only solution there is at the moment.
> 
> If you think this feature is valuable for you and other, we are happy to accept contributions.

Ok, do I understand correctly that replication in Harbor doesn't work for projects LDAP members role and I have to set it separately for all my projects on all my servers in replica?
