### ISSUE TITLE
Docker proxy registry scan using Prismacloud triggers the pull of all the tags of a repository

### ISSUE THREAD

**Issue by ricardojdsilva87** [goharbor/harbor#17155]
Hello,

We encountered an issue/strange behaviour with the Harbor Docker proxy when we are using the external CVE scanner Prismacloud integration.

What is happening is that when a registry scan is triggered, Harbor fetches all the available tags under a certain repository.
We've contacted the Prismacloud support and after investigation they said that Prismacloud is doing what is supposed to regarding a Docker registry scanning.
Here is the [documentation](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/vulnerability_management/registry_scanning). In sum and checking the 3rd step "Registries on a large scale", Prismacloud does the following:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12953702/178255589-22c44c13-6d38-48fc-a7c7-ec8a26d1845a.png">

We've analysed the requests coming to Harbor and it seems that Prismacloud is using the [v2 API](https://docs.docker.com/registry/spec/api/) to list the Registry images:
The requests made agains Harbor:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/12953702/178255804-e1f45cf3-b1c7-4c7f-95f9-3c0695e986d9.png">
A tag not found in Harbor Docker proxy registry:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/12953702/178255913-7a77a523-a86a-4a08-9aa6-62c5debfc228.png">

Meaning that what happens is that Prismacloud requests a list of all the tags on the repository and the way that the Docker proxy registry works, it will requests those tags to Dockerio and not return the tags of the images that are already cached on Harbor and need to be scanned. 

What this causes is a wave of pulls from dockerio from Harbor for the tags that are not present, instantly reaching the dockerio API limit and blocking further requests for 6 hours.

You can see here a list of repositories with dozens of artifacts downloaded:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/12953702/178256270-d7e5470f-9c17-4812-8fa0-1a9893104fb3.png">

Checking in detail we have ARM images downloaded that we do not use, also some alpha, beta and random tagged images are downloaded into the docker proxy.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/12953702/178256395-4af0cde8-74f4-4069-a350-5513d6378147.png">

What I'm asking is if there is a "special configuration" that could be applied into the docker proxy registry in order to return only the already existent images tags to be scanned and not ask to dockerio what tags are available for that repository and not locally on Harbor that will be downloaded.

For the moment we've blacklisted this repository on the prismacloud settings to not be scanned.

Thank you for your support

**Comment by ricardojdsilva87** [comment]
Hello @stonezdj , that's true, in this case a list tags call against the dockerio proxy repo retrieves all the tags existent in dockerio, and the way the proxy repo is configured if those tags are not present locally they will be downloaded.
Not sure if this was a feature requested, but if we request all the tags to the proxy repo shouldn't it reply with the existent tags? Because the way that the proxy repo works is that if a pull request is done to a tag that does not exist locally it would be retrieved from dockerio, at the moment with the list all tags Harbor does not answer with the tags and images existent locally but retrieves all tags and images from dokckerhub itself
Thanks

**Comment by stonezdj** [comment]
It works as designed, the proxy cache needs to proxy the remote tags.  the scanner could scan it on push.

**Comment by ricardojdsilva87** [comment]
Hello @stonezdj , thanks for the feedback, the ticket can be closed then.
