### ISSUE TITLE
Condition 'len(link) != 0' is always 'false'

### ISSUE THREAD

**Issue by PengWuLin** [goharbor/harbor#17159]
**Expected behavior and actual behavior:**
Condition 'len(link) != 0' is always 'false'
![image](https://user-images.githubusercontent.com/39291860/178462804-dd351222-2723-46af-9136-cc5178d63aa6.png)

**Steps to reproduce the problem:**

**Versions:**

- harbor version: [2.5.3]

**Comment by OrlinVasilev** [comment]
@PengWuLin - thank you so much!!!
