### ISSUE TITLE
Harbor repository replicates across the cloud test failed！have screenshot and logs

### ISSUE THREAD

**Issue by jwh5566** [goharbor/harbor#17160]
src: hw cloud harbor
dst: aliyun cloud harbor

the two instance's network is internal ip, but the they use nat to access outside, config like screenshot:
![image](https://user-images.githubusercontent.com/7205703/178460279-07981345-7e09-4384-baea-fd631f77ca05.png)

the log like this:
![image](https://user-images.githubusercontent.com/7205703/178463778-31426e8f-5d2b-41d1-ad38-4133dd89ad76.png)

**Comment by chlins** [comment]
How did you install harbor? Could you provide the `harbor.yml`(docker-compose) or `values.yaml`(helm)?

**Comment by jwh5566** [comment]
![image](https://user-images.githubusercontent.com/7205703/178496702-f86df28a-26fe-400e-ae5f-1c3dd8e95770.png)

**Comment by chlins** [comment]
There is an environment variable `EXT_ENDPOINT` in the harbor-core, from your log, the value maybe is `http://172.19.101.120:8003` now, you could try to set this value same with `external_url` and restart harbor core.
