### ISSUE TITLE
Vulnerability scan report to show the file path

### ISSUE THREAD

**Issue by geowalrus4gh** [goharbor/harbor#17163]
**Is your feature request related to a problem? Please describe.**
Scan report can contain files which are not there in the container image. The vulnerability report might be due an indirect dependency from a file. If that is the case it would be helpful to track the file if result shows the exact path to the file in the container. 

**Describe the solution you'd like**
Show file path in the scan report screen,

**Comment by geowalrus4gh** [comment]
Oh no...its not stale

**Comment by geowalrus4gh** [comment]
@chlins

**Comment by bianjp** [comment]
Duplicate of #16017
