### ISSUE TITLE
Provided Nginx version 1.19 in Harbor Portal is end of life

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#17170]
The current version of nginx `v.1.19.3` is end of life. https://endoflife.date/nginx.

It is not supported nor receives any updates.

In the photon DEV repo, I found there is nginx 1.21.0. It is, however, not released yet. This version is also [endoflife](https://endoflife.date/nginx.) and does not contain any security patches.

**Comment by YangJiao0817** [comment]
Already feedback to photon team, waiting for photon team feedback.

**Comment by YangJiao0817** [comment]
Nginx version will be upgraded to 1.22 in Harbor 2.6.0 and Harbor 2.5.4.
