### ISSUE TITLE
Charts replicated with "replication" are pushed to the deprecated Chartmuseum

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#17177]
Harbor 2.5.3

Charts replicated with "replication" are pushed to the deprecated Chartmuseum.
I didn't find any issue about this.
Shouldn't it be pushed to the OCI registry? Do I miss something?
Is it planned to migrate chartmuseum charts to the OCI registry ?

Thanks.

**Comment by Vad1mo** [comment]
Do you replicate from OCI to OCI or do you expect to replicate from Chartmuseum to OCI?

**Comment by flbla** [comment]
I replicate from ArtifactHub to Harbor

**Comment by Vad1mo** [comment]
ArtifactHub may have OCI and Chartmuseum charts.
As said:
>There is no logic in Harbor that can convert from one to another. So, OCI -> OCI and Chartmuseum -> Chartmuseum

There is however a script here in some repo that converts Chartmuseum to OCI, I am not able to find it at the moment.  Maybe someone on slack can help you to find it.

**Comment by zyyw** [comment]
> ArtifactHub may have OCI and Chartmuseum charts. As said:
> 
> > There is no logic in Harbor that can convert from one to another. So, OCI -> OCI and Chartmuseum -> Chartmuseum
> 
> There is however a script here in some repo that converts Chartmuseum to OCI, I am not able to find it at the moment. Maybe someone on slack can help you to find it.

This is the doc about how to convert chartmuseum to OCI:
* https://github.com/goharbor/harbor/tree/main/tools/migrate_chart

**Comment by flbla** [comment]
Thanks @Vad1mo and @zyyw ,

Can you explain to me how to configure an OCI replication with ArtifactHub ?
I didn't see anything related to OCI when I created an Endpoint and a ReplicationRule :
![image](https://user-images.githubusercontent.com/11298399/179455781-c84222c6-a378-4b58-8ba3-93306b10f988.png)
![image](https://user-images.githubusercontent.com/11298399/179455796-52f32345-07c1-44cb-875c-1f86a188c6aa.png)

Thank you!

**Comment by zyyw** [comment]
> > ArtifactHub may have OCI and Chartmuseum charts. As said:
> > > There is no logic in Harbor that can convert from one to another. So, OCI -> OCI and Chartmuseum -> Chartmuseum
> > 
> > 
> > There is however a script here in some repo that converts Chartmuseum to OCI, I am not able to find it at the moment. Maybe someone on slack can help you to find it.
> 
> This is the doc about how to convert chartmuseum to OCI:
> 
> * https://github.com/goharbor/harbor/tree/main/tools/migrate_chart

As @Vad1mo mentioned, ArtifactHub may have OCI and Chartmuseum charts, and the replication can only replication OCI->OCI, or Chartmuseum -> Chartmuseum. However, harbor provide a doc how to convert an existed (pushed or replicated) Chartmuseum to OCI artifact, doc link: https://github.com/goharbor/harbor/tree/main/tools/migrate_chart

**Comment by flbla** [comment]
oh, okay, it means all the chart I tried to replicate are only Chartmuseum charts. And until ArtifactHub provide them as OCI charts, it will not be possible to replicate them to Harbor as OCI. (Unless using the migrate_chart tool)
Did I understand well?
Thank you!

**Comment by Vad1mo** [comment]
Your understanding is correct @flbla. 
In the meantime I recommnd you to create a CI cron job to sync/convert charts from Chartmuseum to OCI. This way you get the expected result.
