### ISSUE TITLE
Adoption of https://github.com/BESTSELLER/terraform-provider-harbor

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/harbor#17171]
Hi All, 

this project looks like is good addition to Harbor: https://github.com/BESTSELLER/terraform-provider-harbor

We have the chance to adopt it but we also need folks to maintain it!

Please share your thoughts and if you are using it and if you think it will make sense for us! Thank you!
Let's vote here!
Orlix

**Comment by slushysnowman** [comment]
We are using it and heavily rely on it for configuration of Harbor internals - it's a good provider and I think it would definitely make sense.

**Comment by HammerNL89** [comment]
I just noticed the warning on BESTSELLER/terraform-provider-harbor. We use this provider a lot in our Harbor setup, and it would be a shame if support would drop.

**Comment by OrlinVasilev** [comment]
@HammerNL89 and @slushysnowman thanks for the input, we are currently in the process of adopting it, so will not be dropped, but support will  be needed from folks like you to support it as we are not able to get resources as of now! So  if  you can volunteer will be great! :) As well as other folks if can join will be great ! :) Thank you!

**Comment by OrlinVasilev** [comment]
https://github.com/goharbor/terraform-provider-harbor
Looking for maintainers! :)

**Comment by OrlinVasilev** [comment]
Adopted! :)
