### ISSUE TITLE
Upgrade / migration from v1.10.1-f3e11715 to 2.x doesn't contain all the data?

### ISSUE THREAD

**Issue by jbiancot** [goharbor/harbor#17172]
Hi there,

I am running a Harbor v1.10.1-f3e11715 on a VM, I tried to upgrade a few times, from 1.10.x to 2.2.0 then 2.3.0 then 2.5.x but I noticed that some Docker images "artifacts" were missing?

Then I rolled back the VM to the original state "v1.10.1-f3e11715", and I did it again to just version 2.0.0, I am seeing the same thing, some data is missing, is any log file of the upgrade? is this a known issue?

I found a pattern, we have some images with the words "node" or "slim", those don't have the data?

I have attached 2 screenshots, one for Harbor v1.x and the other Harbor 2.x

<img width="1741" alt="Harbor_v1_10_x" src="https://user-images.githubusercontent.com/14841885/179063901-4ac21c13-0e3e-44f7-beb9-0a62fb4ca63b.png">

<img width="1735" alt="Harbor_v2_0_0" src="https://user-images.githubusercontent.com/14841885/179063928-15a6a85e-2967-44d0-89b8-4ea8a7396df4.png">

**Comment by chlins** [comment]
Could you check the error message of harbor-core when upgrade?

**Comment by jbiancot** [comment]
@chlins  How I can do that? I need to go inside the container? or there is a log file, mounted as a volume?

**Comment by chlins** [comment]
When you upgrade from 1.10 to 2.0, you can use `docker logs harbor-core` to catch any ERROR message about the missing image.
