### ISSUE TITLE
Can't get my Kubernetes nodes pulling from my Harbor. (401 Unauthorized)

### ISSUE THREAD

**Issue by niklaspm** [goharbor/harbor#17180]
Hello,

I can't get my Kubernetes cluster pulling images from my Harbor. 

I did the following: 
1. `docker login <my_harbor_host>`
2. `kubectl create secret generic regcred --from-file=.dockerconfigjson=/home/niklas/.docker/config.json --type=kubernetes.io/dockerconfigjson`
3. `kubectl create deployment hello-world --image myharbor.com/project/hello-world:latest`

I can pull the image on my local machine by running:
`docker pull myharbor.com/project/hello-world:latest`

But I can't deploy it to my Kubernetes cluster. `ImagePullBackOff` error all the time.

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m19s                   default-scheduler  Successfully assigned default/hello-world-89d58999d-9fr2w to cluster-node-23.host.to
  Normal   Pulling    7m54s (x4 over 9m18s)   kubelet            Pulling image "myharbor.com/project/hello-world:latest"
  Warning  Failed     7m54s (x4 over 9m18s)   kubelet            Failed to pull image "myharbor.com/project/hello-world:latest": rpc error: code = Unknown desc = failed to pull and unpack image "myharbor.com/project/hello-world:latest": failed to resolve reference "myharbor.com/project/hello-world:latest": pulling from host registry.niklas.pm failed with status code [manifests latest]: 401 Unauthorized
  Warning  Failed     7m54s (x4 over 9m18s)   kubelet            Error: ErrImagePull
  Warning  Failed     7m40s (x6 over 9m17s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m10s (x21 over 9m17s)  kubelet            Back-off pulling image "myharbor.com/project/hello-world:latest"
```

Running `kubectl get secrets` (checked the content of the secret twice by running `kubectl get secret regcred -o yaml` and decoding the base64 string results in the same config content as the one which is working without any problems on my local machine)  
```
NAME                           TYPE                             DATA   AGE
regcred                        kubernetes.io/dockerconfigjson   1      11m
``` 

Any ideas?

**Comment by chlins** [comment]
Did you reference this secret in the deployment?

**Comment by yoongeon1206** [comment]
@niklaspm Hi, I got the same issue on my kubernetes environment. 
it works fine on worker node 15 of my k8s, however ErrImagePull occurred on same worker node 15 when secret "regcred" is created in myservice namespace and then i deploy my service on the namespace. i added imagePullSecret "regcred" to helm chart (values.yaml).
"could you be more details? Did you setup your cluster on your local machine or another worker node? 

docker login <my_harbor_host> 
kubectl create secret generic regcred --from-file=.dockerconfigjson=/home/yoon/.docker/config.json --type=kubernetes.io/dockerconfigjson -n myservice
helm install myservice ./myservice_helm -n  myservice
