### ISSUE TITLE
OIDC scopes field must support URL-based scopes

### ISSUE THREAD

**Issue by andrey-yakubovskiy** [goharbor/harbor#17181]
**Expected behavior and actual behavior:**

"OIDC scopes" field at https://domain/harbor/configs/auth must support URL-based scopes, e.g. "https://my.company/auth/roles", URL-based scopes are extensively used by many identity providers, e.g. https://developers.google.com/identity/protocols/oauth2/scopes. 

Instead "OIDC scopes" field returns validation error.

**Steps to reproduce the problem:**

* Open portal https://domain/harbor/configs/auth
*  "Auth Mode": select "OIDC"
* "OIDC scopes": input URL-formatted scope, e.g. https://my.company/auth/roles
* see validation error
<img width="590" alt="image" src="https://user-images.githubusercontent.com/67272182/179390559-ecb75925-f680-4987-a363-66861ef11741.png">

**Versions:**
- harbor version: 2.6.0

**Comment by bpereto** [comment]
Can we /reopen this?
