### ISSUE TITLE
CVE export does not generate log information under /var/log/jobs/ in jobservice container

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#17199]
**Expected behavior and actual behavior:**
1. docker push x.x.x.x/library/nginx:1.13.12
2. get into the jobservice container shell: `docker exec -it <jobservice_container_id> /bin/bash`
3. within jobservice container shell: `ls /var/log/jobs/` there is no file
4. scan the nginx image, we can see there is a file generated with content under `/var/log/jobs/` in jobservice container: `ls /var/log/jobs/`
5. perform export cve against the `library` project, and cve data are exported and downloaded with cve information in it.
6. However, `ls /var/log/jobs/`, the new log file generated under `/var/log/jobs/` in jobservice container is empty (**actual behavior**). 
    This new file under `/var/log/jobs/` in jobservice container should contain some log information about the export cve log activity (**expected behavior**).
<img width="647" alt="Screen Shot 2022-07-19 at 14 56 20" src="https://user-images.githubusercontent.com/6709992/179687139-f6c3d25e-43d1-4241-9a4b-edfde1352d5e.png">

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
please check the above description

**Versions:**
Please specify the versions of following systems.
* Harbor Version: Version v2.6.0-f3edb03b

**Comment by stonezdj** [comment]
see https://github.com/goharbor/harbor/blob/130452111b628a85a66a59985fb561f0bf268511/src/jobservice/job/impl/scandataexport/scan_data_export.go#L78
You should change the logger to the logger get from context, like that
https://github.com/goharbor/harbor/blob/4d062c33d1c1b53c18866323ab8f112b34a8b9e3/src/jobservice/job/impl/systemartifact/cleanup.go#L29

**Comment by AllForNothing** [comment]
@prahaladdarkin Please have a look at this

**Comment by prahaladdarkin** [comment]
Fixed within CL https://github.com/goharbor/harbor/pull/17232. Refer below screenshot

<img width="1786" alt="Screen Shot 2022-07-25 at 6 04 28 PM" src="https://user-images.githubusercontent.com/30070908/180778448-454bd711-d049-4361-bb17-eb7e656a2401.png">
