### ISSUE TITLE
GET /export/cve/execution/<execution_id>  Returns data is missing job_name

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17196]
**Expected behavior and actual behavior:**
Expected:Returns data is
```
{
    "end_time": "2022-07-12T10:17:46.000Z",
    "file_present": true,
    "id": 14,
    "job_name": "Ubuntu_Vuln_Export_Job",
    "start_time": "2022-07-12T10:17:46.134Z",
    "status": "Success",
    "status_text": "",
    "trigger": "MANUAL",
    "user_id": 3,
    "user_name": "user"
}
```
Actual:Returns data is
```
{
    "end_time": "2022-07-19T04:29:04.000Z",
    "file_present": true,
    "id": 14,
    "job_name": "",
    "start_time": "2022-07-19T04:29:03.260Z",
    "status": "Success",
    "status_text": "",
    "trigger": "MANUAL",
    "user_id": 3,
    "user_name": "user"
}
```

**Steps to reproduce the problem:**
1. Create a project
2. Push image to project
3. Scan and Export CVE data
4. Call GET /export/cve/execution/<execution_id>
<img width="590" alt="图片" src="https://user-images.githubusercontent.com/72076317/179677554-177f4ec0-73a3-46d3-8032-4ab3bef6cfb0.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0-f3edb03b

**Comment by AllForNothing** [comment]
@YangJiao0817 After a discussion, we decided to remove `job_name` property, so this is not a bug.
@prahaladdarkin Now `job_name` is redundant, so we can remove it
