### ISSUE TITLE
Image author not valued in Harbor UI 

### ISSUE THREAD

**Issue by alexandreroman** [goharbor/harbor#17190]
**Expected behavior and actual behavior:**
The Harbor UI does not show the value for image author, despite using the OCI label org.opencontainers.image.authors.

**Steps to reproduce the problem:**
Create a Docker image using `LABEL org.opencontainers.image.authors=johndoe`.
Run `docker inspect -f '{{index .Config.Labels "org.opencontainers.image.authors"}}' MY-IMAGE`.
Check that image author is set in the image.
Use Harbor UI to show image details.
Check that image author is empty using the Harbor UI.

**Versions:**
- harbor version: 2.5.3

<img width="1148" alt="Missing image author in Harbor UI" src="https://user-images.githubusercontent.com/665131/179471616-cb392b64-4b18-4dbb-b87f-dd560f7d401c.png">

**Comment by chlins** [comment]
https://github.com/goharbor/harbor/blob/f3edb03b49a0c0c41bc4ac15506654d84915fc6c/src/controller/artifact/processor/image/manifest_v2.go#L69
