### ISSUE TITLE
Can not GC artifacts that has accessories

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17202]
1.Currently, an artifact can never be GCed once it has an accessory, maybe, we need to discuss whether this is reasonable

**Comment by MinerYang** [comment]
If it contains a cosign signature accessory then this artifact can not be GC, either the subject artifact or its accessory. It seems reasonable for a signed image.

But is it still suitable to apply the same rule to other accessory types , for example, when it only contains a nydus accessory we still can not GC the subject artifact without any tags unless we delete the accessory manually?

We may need to discuss more in the future.
