### ISSUE TITLE
Accessories quota consumption issues

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17207]
1.  Accessories only consume the quota of their original project. 
       Steps to reproduce:
      (1)  push `redis:latest` to `library`
      (2)  accelerate it by `nydus`
      (3)  Copy it to another project, like 'test'
      (4)  Check the quota of `test` project, you will find that accessory of `redis:latest` does not comsume any quota of `test`

2 .  The quota consumed by the accessories is greater than their size
       Steps to reproduce:
      (1)  push `nginx:latest` to `library`
      (2)  accelerate it by `nydus`
      (3)  Check the quota of `libray` project, you will find that the quota consumed by the accessory is greater than its size

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/17293
