### ISSUE TITLE
Harbor's Garbage Collection

### ISSUE THREAD

**Issue by lbcjf666** [goharbor/harbor#17209]
Why can't Harbor's Garbage Collection clean up my deleted artifacts immediately, do I need to wait a few days?
![image](https://user-images.githubusercontent.com/109259320/179884744-2f772a19-7e7b-4dee-8d72-989bf3216cfe.png)
My harbor version is v2.4.2

**Comment by QiuToo** [comment]
Please check whether your machine resources are sufficient and whether the cluster service is normal!

**Comment by wy65701436** [comment]
Refer to the **time window** in https://goharbor.io/docs/2.5.0/administration/garbage-collection/
