### ISSUE TITLE
Wrong behaviour trying get data with /search api v2 with robot account

### ISSUE THREAD

**Issue by nikolaevn** [goharbor/harbor#17218]
**Prerequisites**

* private project (test)
* robot acctount with all permissions to project

**Reproducing**

Trying to call /search api with swagger providing robot account name and secret
Got response with http status 200 and payload:
`
{"chart":[],"project":[],"repository":[]}
`

(!) But when trying to call api with robot account name + empty space char at end (aka "robot$temp ") then result is http status 200 and payload:
`
{"chart":[{"Chart":{"apiVersion":"v2","appVersion":"1.26.0","description":"A Helm chart for Kubernetes","engine":null,"icon":null,"keywords":null,"name":"test...", ...
`

**Versions:**

- harbor version: v2.5.3-797c3536

**Comment by wy65701436** [comment]
what do you mean by "swagger providing robot account name and secret"? Is it a robot account?

**Comment by nikolaevn** [comment]
> what do you mean by "swagger providing robot account name and secret"? Is it a robot account?

Yes. I use robot account to authenticate request with swagger
