### ISSUE TITLE
bypass redis related settings when core is started with "migrate" mode

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#17213]
Hi, 
currently when core is running in migrate mode, it still needs to connect with redis at the  beginning of process init, actually, redis is not needed for this mode, could add some check during the init. to bypass the redis related code? then the configuration for the pre-upgrade job will be simpler.
thanks.

======
https://github.com/goharbor/harbor/blob/main/src/core/main.go

	redisURL := os.Getenv("_REDIS_URL_CORE")
	if len(redisURL) > 0 {
		u, err := url.Parse(redisURL)
		if err != nil {
			panic("bad _REDIS_URL")
		}

		beego.BConfig.WebConfig.Session.SessionProvider = session.HarborProviderName
		beego.BConfig.WebConfig.Session.SessionProviderConfig = redisURL

		log.Info("initializing cache ...")
		if err := cache.Initialize(u.Scheme, redisURL); err != nil {
			log.Fatalf("failed to initialize cache: %v", err)
		}
		// when config/db init function is called, the cache is not ready,
		// enable config cache explicitly when the cache is ready
		dbCfg.EnableConfigCache()
	}

....
	if strings.EqualFold(*runMode, "migrate") {
		// Used by Harbor helm preinstall, preupgrade hook container
		**if err = migration.Migrate(database); err != nil {**
			log.Fatalf("failed to migrate the database, error: %v", err)
		}
		log.Info("the database migrate success")
		os.Exit(0)
	}

**Comment by danielzhanghl** [comment]
hi, any plan for this enhancement? thanks.

**Comment by stonezdj** [comment]
Yes,  Init the redis after the if else block of run mode

**Comment by danielzhanghl** [comment]
hi, which release will the enhancement be available ?  thanks.
