### ISSUE TITLE
Garbage collection failing with the error "object is not found"

### ISSUE THREAD

**Issue by VashishtRajan** [goharbor/harbor#17246]
Harbor version "harbor-0.7.0-master-c4bd385"
API v2.0

Garbage collection is giving this error in the UI when triggered and is not even triggering this scheduled job.

Error:
`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"63b28910acf34060c42690b1\"}"}]}`

**Comment by wy65701436** [comment]
hi, could you tell the harbor version?
