### ISSUE TITLE
is there a size limit for a layer?

### ISSUE THREAD

**Issue by qiankunli** [goharbor/harbor#17242]
![image](https://user-images.githubusercontent.com/8024725/180912467-4d12ea6c-0058-4a92-8b5f-fab2118c0347.png)
there is a layer whose size is 12GB, I can not `docker push` the layer successfully. 
I used `docker commit` to create the layer.

**Comment by wy65701436** [comment]
you can try to enlarge the http timeout in the nginx, and please provide the nginx, core and registry log for debugging.
