### ISSUE TITLE
Proxy Cache - Failed to fetch... invalid character '<'

### ISSUE THREAD

**Issue by bradwinfield** [goharbor/harbor#17245]
I'm trying to setup my Harbor as a Proxy Cache. The source repo is gcr.io.  I am using endpoint provider type of "Docker Registry", the 'Test Connection' succeeds. But when I use this one in a Provider and then try to do a Replication, I get this:
"failed to fetch artifacts: failed to list artifacts of repository ...: invalid character '<' looking for beginning of value

**Comment by stonezdj** [comment]
The proxy cache support GCR as a registry, you don't have to configure it as a docker registry. what is the core.log of the harbor?
