### ISSUE TITLE
Incorrect www-authenticate header when curling /v2/_catalog

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#17256]
Hi,

We are trying to integrate with an external application and we see an incorrect www-authenticate field error when curling to _catalog endpoint.

If we curl the _catalog endpoint we get:

Is there any way to fix or get the correct www-authenticate header when doing a HEAD call against the _catalog endpoint? Thanks

Harbor version: 2.2.0

**Comment by wy65701436** [comment]
can you share the curl cmd and error?
