### ISSUE TITLE
Empty Vulnerability Report

### ISSUE THREAD

**Issue by olivov** [goharbor/harbor#17263]
Howdy Folks,

We are currently running Harbor 2.5.3 as an installed Helm chart inside our Kubernetes cluster with Trivy enabled as our default vulnerability scanner. Everything works great; however, the issue we're coming across is that we cannot query the Harbor API to get vulnerability data out. Here's an example query to our API which results in an empty dictionary:
```
❯ curl --user admin https://harbor-dev.its.utexas.edu/api/v2.0/projects/library/repositories/ubuntu/artifacts/latest/additions/vulnerabilities
Enter host password for user 'admin':
{}%
```
Oddly enough, the Harbor UI shows all the vulnerabilities just fine:
<img width="1229" alt="Screen Shot 2022-07-28 at 12 18 24 PM" src="https://user-images.githubusercontent.com/23345433/181598609-641a7f2b-831b-4988-ad72-05627a01f2bb.png">

I have not seen this issue reported elsehwere and I don't see any information in any of the pod logs that would suggest an error somewhere, so I'm a bit lost on why the UI and API differ here. Any help is greatly appreciated. Thanks!

**Comment by chlins** [comment]
You should add the `X-Accept-Vulnerabilities` header, which can refer to https://github.com/goharbor/harbor/blob/bd1d441b013aba60e5db0a60658127abac83ee8a/api/v2.0/swagger.yaml#L5764

**Comment by olivov** [comment]
thanks @chlins 

with that header provided, i still do not see results unfortunately : /

```
❯ curl -H 'X-Accept-Vulnerabilities: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0' --user admin https://harbor.its.utexas.edu/api/v2.0/projects/base-images/repositories/ut-python/artifacts/sha256:33f3a227f7d3280630dca55dd8a2b8c4652ad01ac0d9df7b5856ea19ccbe9640/additions/vulnerabilities
Enter host password for user 'admin':
{}%
```

i dug in to this some more and once thing i noticed is that the registry database table 'scan_report' shows vulnerabilities being empty:
```
registry=# select report from scan_report where digest like 'sha256:33f3a227%';
                                                                               report
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"generated_at":"2022-07-29T00:04:43.103282178Z","scanner":{"name":"Trivy","vendor":"Aqua Security","version":"v0.29.2"},"severity":"Medium","vulnerabilities":[]}
(1 row)
```

does this seem correct?

**Comment by chlins** [comment]
Could you try to this header value? `'application/vnd.security.vulnerability.report; version=1.1, application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0'`

**Comment by chlins** [comment]
The code change for the swagger docs is https://github.com/goharbor/harbor/pull/16965.

**Comment by olivov** [comment]
ah! that appears to have done it. i'll avoid pasting in the json blob i get back. thanks for the help @chlins, much appreciated.
