### ISSUE TITLE
I found that harbor v2.4.0 adds the function of link tracking

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#17262]
I found that harbor v2.4.0 adds the function of link tracking, but I don't know the configuration parameters and can't use this function. In addition, which version of Jaeger should I use?

**Comment by chlins** [comment]
You mean the distributed tracing feature? You can refer to https://goharbor.io/docs/2.4.0/administration/distributed-tracing/ for this function.

**Comment by QiuToo** [comment]
no!It is a new trace added by harbor 2.4.0
trace:
#  enabled: true
#  sample_rate: 1

**Comment by chlins** [comment]
The trace configuration as you pasted is the feature of distributed tracing.
