### ISSUE TITLE
Add contributing documentation

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17299]
What can we help you?

When a newcomer or needs to carry out secondary development, there is no newcomer development document, there are some hidden things in the code, you need to execute the command to know, all proposals write an entry-level contribution document, and write down the required steps clearly.

**Comment by lengrongfu** [comment]
example：[https://github.com/goharbor/harbor/issues/17297](https://github.com/goharbor/harbor/issues/17297)

**Comment by wy65701436** [comment]
cc @OrlinVasilev
