### ISSUE TITLE
code import name is not exist

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17297]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/15009201/182512179-68f5bb19-5c3a-4582-a290-0992a3fe185d.png">

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [main]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
These directories are generated by swagger,  you can run the `make gen_apis` to generate these folders.
