### ISSUE TITLE
Replication pull mode does not send webhook

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17305]
**Expected behavior and actual behavior:**
Expected:Project on Harbor B receives the webhook message pulled by artifact
Actual:Project on Harbor B did not receive the webhook message pulled by the artifact

**Steps to reproduce the problem:**
1. Prepare two Harbor, Harbor A and Harbor B
2. Create a new Project A on Harbor A
3. Create a new Project B on Harbor B and set up the webhook
4. Push image to Project B in Harbor B
5. Create a replication rule
<img width="644" alt="WechatIMG183" src="https://user-images.githubusercontent.com/72076317/182509861-00ff3bb6-f828-4686-a666-ff81a156a8d9.png">

6. Trigger replication
7. Project B above Harbor B is not receiving webhook messages for artifact pulled

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0-66d34c8e

**Comment by HSoulat** [comment]
Same isssue with external webhook listener

**Comment by chlins** [comment]
relevant

**Comment by HSoulat** [comment]
relevant

**Comment by HSoulat** [comment]
relevant

**Comment by HSoulat** [comment]
relevant
