### ISSUE TITLE
Cosign signature check not visible

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#17324]
Hi all,

Yesterday we found the following issues with Cosign in our environment (**Harbor v2.5.0**):

**Expected behavior and actual behavior:**
Signing of images with Cosign is working fine and without any issues.
Yesterday we detected an issue with signed images (with Cosign) in an **public project**.
Within the public project, an image was signed successfully, but the green check mark is only visible to a) global Harbor admin users or b) to users, who are member with at least `Limited Guest` permissions.
If a user is no admin and not a member of the public project, he just see a red cross instead of the green check mark.

**Steps to reproduce the problem:**
- Create a public project
- Sign an image with Cosign and upload it

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.0

Are you aware of this issue or does anyone saw the same?

Please let me know, in case more information are needed.

Thanks a lot!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by wy65701436** [comment]
It's fixed in the v2.5.3 and the v2.6.0, please try these builds.

**Comment by AllForNothing** [comment]
This is the same issue as #[16940](https://github.com/goharbor/harbor/issues/16940)
