### ISSUE TITLE
When replicating charts not all versions are added to the index-cache

### ISSUE THREAD

**Issue by 1-cameron** [goharbor/harbor#17320]
**Expected behavior and actual behavior:**
During chart replication the index-cache file is not updated correctly. All charts will be copied over to the expected chart_storage sub directory but will not be visible in the Harbor UI or the index-cache file (Possibly linked to the deletion issue mentioned [here?](https://github.com/goharbor/harbor/issues/16384)). Logs show that charts are replicated correctly. I have also tried disabling state files as a workaround but the issue persists.

**Steps to reproduce the problem:**
- Set up replication between 2 instances of Harbor
- Push multiple versions of a chart to 1 of the instances
- Trigger the replication

**Versions:**
- harbor version: 2.5.3
- docker engine version: [20.10.4]
- docker-compose version: [z.z.z]

**Additional context:**

Versions in the chart_storage:
![Screenshot 2022-08-04 at 10 40 11](https://user-images.githubusercontent.com/68611194/182817103-b886c227-e84f-41be-9afa-2b4d42fce31b.png)

Versions shown in the GUI:
<img width="394" alt="Screenshot 2022-08-04 at 10 35 43" src="https://user-images.githubusercontent.com/68611194/182817123-9c152313-3f15-4852-b23f-55dfb4cefeb1.png">

Log for replication of chart not shown in GUI (v0.1.20):
`[INFO] [/controller/replication/transfer/chart/transfer.go:174]: copy <project>/<chart>:0.1.20+rc(source registry) to <project>/<chart>:0.1.20+rc(destination registry) completed`

**Comment by wy65701436** [comment]
hi since the chartmuseum is planned to be depreacted, we won't provide support on it. Please use the helm v3.7 to manage your OCI compatible charts for insteand.

See https://github.com/goharbor/harbor/discussions/15057
