### ISSUE TITLE
Harbor List Aritfacts API Call doesn't list report_id

### ISSUE THREAD

**Issue by adonismi** [goharbor/harbor#17338]
Hello, I am trying to get a scan report through API calls. For this, I need the report_id of a scan. I used to be able to get this information through the "List Artifacts" GET API call listed in the swagger ( GET /projects/{project_name}/repositories/{repository_name}/artifacts ), but now it seems like it doesn't return a report_id anymore. In the example under the API call the report_id is still noted, but not in my code 200 response. The artifacts have been scanned multiple times both manually and automatically. I

I am currently running Harbor Version v2.5.1-b0506782 and API 2.0. We recently upgraded from 2.2 to 2.5.1.

Has something changed regarding these API calls between version 2.5.1 and 2.2? Or is there any other way to get the report_id so I can get the scan report? Thanks in Advance,

Kind regards,

Adonis

**Comment by lengrongfu** [comment]
I checked the ` ( GET /projects/{project_name}/repositories/{repository_name}/artifacts )` interface in harbor2.5.1, and I saw from the api documentation that the `report_id` field is returned. 

<img width="569" alt="image" src="https://user-images.githubusercontent.com/15009201/183245732-56dc2b49-0dd5-44d8-875c-b565bd9484c9.png">
<img width="985" alt="image" src="https://user-images.githubusercontent.com/15009201/183245757-da2042bc-b1b7-49eb-a404-b53d119a6551.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/15009201/183245791-d1ac19ad-0835-40f2-ae95-3966c81855ac.png">

**Comment by zyyw** [comment]
@adonismi To get the `report_id` of `scan_overview`, we may need to add `with_scan_overview=true` as the query parameter AND also add a header of `X-Accept-Vulnerabilities: application/vnd.security.vulnerability.report; version=1.1`. 
For more details, please navigate to this issue:
* https://github.com/goharbor/harbor/issues/16085
