### ISSUE TITLE
The issue when the tag of cosign being occupied

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17332]
For the current design of Cosign,  if the tag of Cosign is occupied and set as `immutable`, you will get an error when you trying to cosign an image:
`Error: signing [10.202.250.196/library/redis@sha256:9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4]: getting signer: reading key: decrypt: encrypted: decryption failed
main.go:46: error during command execution: signing [10.202.250.196/library/redis@sha256:9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4]: getting signer: reading key: decrypt: encrypted: decryption failed
root@ubuntuguest:~/testing_day# cosign sign --key cosign.key 10.202.250.196/library/redis@sha256:9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4 --allow-insecure-registry
Enter password for private key: 
Pushing signature to: 10.202.250.196/library/redis
Error: signing [10.202.250.196/library/redis@sha256:9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4]: signing digest: PUT https://10.202.250.196/v2/library/redis/manifests/sha256-9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4.sig: PRECONDITION: Failed to process request due to 'redis:sha256-9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4.sig' configured as immutable.`

So, in the future, maybe, we can improve this

Steps to reproduce:
1. push two images, like `redis` and `node` to library
2. cosign `redis`, and remember the tag(let's say `sha256-9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4.sig`) of the pushed cosign signature
3. remove the cosign signature of `redis`
4. Add a tag named `sha256-9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4.sig`  to `node`
5. add a tag-immutable rule to make `sha256-9bc34afe08ca30ef179404318cdebe6430ceda35a4ebe4b67d10789b17bdf7c4.sig` immutable
6.  re-cosign `redis`,  then you will get an error as above

version: 2.5.x and 2.6.x

**Comment by wy65701436** [comment]
It's by designed behavior and user can rename the tag of image to avoid the confliction since the naming pattern of cosign signature is fixed.
