### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [goharbor/harbor#17340]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade Harbor to the newer version with no downtime
- How to downgrade harbor to the older version (hopefully with no downtime)

The only mention about downgrade possbility is found in Helm upgrade guides but nothing similar in general Harbor upgrade guide.

Thanks in advance!

**Comment by wy65701436** [comment]
Harbor doesn's support downgrade, only way to "downgrade" is just to restore your backuped data of old version.
Meanwhile, harbor doesn't support upgrade with no downtime.

**Comment by zamazan4ik** [comment]
Could you please add this information directly to the documentation? It would be helpful for future users.
