### ISSUE TITLE
Scan all long time can not be completed

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17349]
**Steps to reproduce the problem:**
1. Create some projects and push some images
2. Scan all
Can not be completed for a long time, the status is not updated

**Versions:**
- harbor version: v2.6.0-08c1cc40

**Additional context:**
[job_service.log](https://github.com/goharbor/harbor/files/9286534/jobservice_trivy.log)

**Comment by zyyw** [comment]
It's been discussed here: 
* https://github.com/aquasecurity/trivy/issues/2684

Closing it.
