### ISSUE TITLE
Used storage space display problem

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17348]
What can we help you?

The display of the used storage space that I see on the project homepage and after entering the project homepage is different.

- in the homepage
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/15009201/183346516-230065c1-9edd-4e58-ad5d-8b1a8275624e.png">

- in the project homepage 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/15009201/183346644-74aaeaf4-a156-4e1c-b528-96f525cd1140.png">

The home page counts the storage space that has not been released by GC, and the project home page counts the storage space that can be used for images. Is this designed? Still there is a problem here.

**Comment by zyyw** [comment]
The number in `the homepage` is calculated by blobs, since the blobs are not GC-ed therefore the number is still `17.80`.
The number in  `the project homepage` is the quota value. Because the the artifact is deleted, the quota being used should be 0.

**Comment by AllForNothing** [comment]
Now, the wording on the project page has been changed from `Storage used` to `Quota used` to avoid confusion
![image](https://user-images.githubusercontent.com/30999793/183556337-e14f8c1c-12b6-4fbc-a056-2be981e54d7f.png)
