### ISSUE TITLE
Development is not a valid chart repository or cannot be reached: Get index.yaml": EOF

### ISSUE THREAD

**Issue by miloslavkrisko** [goharbor/harbor#17351]
I am facing an issue where the harbor is either not responding or throwing following error message:
Development is not a valid chart repository or cannot be reached: Get index.yaml": EOF

What i am trying to perform:
"helm repo add <url>/chartrepo/development --username <username> -- password <password>"

Situation when it happens:
- We do have a jenkins agents which authenticates to the harbor by running above mentioned command. Sometimes it connects and works as expected, but there are some random occurences where it returns the above mentioned error.

Infrastructure:
- Harbor is running inside of AWS EKS cluster where the connection is handeld by traefic with NLB.
- HTTPS is opened to specific set of IP's 

From local machine i am able to connect there but as i run the lm repo add command only once i didn't notice any sort of this failures.

We are using Jenkins Agent without added helm repo for security reasons as we are splitting the chart repo's into multiple ones depending on the project while the agent is shared ( it contains the necessary tools like aws-cli, helm, helm-cm push plugin) for accessing the EKS cluster and performing the deploymnets + publishing the charts into harbor.

As the connectivity seems to be working as ping and telnet are going through i am wondering if there is some "default limit" which sets a number of "helm repo add" commands to be allowed to the specific chartrepo within timeframe of couple of minutes.

**Comment by zyyw** [comment]
@miloslavkrisko Chart-museum is going to be deprecated, please try to use OC compatible helm chart.

**Comment by miloslavkrisko** [comment]
@zyyw  so within the harbor helm chart installation what type of chart storage you are going to be implementing?

**Comment by miloslavkrisko** [comment]
@zyyw well the other spare solution which i see as potentially usable is nexus as we are storing docker images and arfitacts there. Just the nexus UI for chart storage is really terrible. Otherwise i will have to research other usable solution's as within the supported one's i saw Jfrog but i didn't saw a Nexus.
Is there any plan to add sonatype nexus within supported OCI?
