### ISSUE TITLE
Request to add harbor logo to nydus website

### ISSUE THREAD

**Issue by imeoer** [goharbor/harbor#17352]
What can we help you?

Nydus already has some collaboration with harbor, such as the [acceld](https://github.com/goharbor/acceleration-service) project, so we are requesting to add the harbor logo to the "Open Source Communities" section.

Talked about it with @wy65701436 offline and have obtained @OrlinVasilev 's permission, PR is here https://github.com/dragonflyoss/image-service-website/pull/6, and we can preview the website [here](https://deploy-preview-6--d7ynydus.netlify.app/).

Checked by:

- [x] @OrlinVasilev 
- [x] @wy65701436

**Comment by imeoer** [comment]
cc @OrlinVasilev @wy65701436 Once you confirm, I will merge that PR, thanks!

**Comment by OrlinVasilev** [comment]
Approved! @wy65701436  can you check as well please!

**Comment by wy65701436** [comment]
Approved!

**Comment by imeoer** [comment]
Thanks all! The [PR](https://github.com/dragonflyoss/image-service-website/pull/6) merged.
