### ISSUE TITLE
Harbor V2.5.3 is not working on chrome

### ISSUE THREAD

**Issue by rsha123** [goharbor/harbor#17365]
What can we help you?
Harbor Version v2.5.3-797c3536 is not working on chrome. It logs out automatically after few seconds and sometime dosesn't load the login page. It will working fine on MS Edge. 
Is it a configuration issue or there is any chrome compatibility issue? 

Please advise..

**Comment by AllForNothing** [comment]
@rsha123 What's your chrome version? Can you find any errors in the console tab under chrome's debug mode?
![image](https://user-images.githubusercontent.com/30999793/184568699-72c818da-a115-4e63-ad0f-8c587c4ec624.png)

**Comment by BK-STAR77** [comment]
Hello,

I solve my issue. I used Helm chart version with 2 replicas for each pod. I scale down to 1 and the issue gone.

**Comment by rsha123** [comment]
> @rsha123 What's your chrome version? Can you find any errors in the console tab under chrome's debug mode? ![image](https://user-images.githubusercontent.com/30999793/184568699-72c818da-a115-4e63-ad0f-8c587c4ec624.png)

Version 103.0.5060.114 (Official Build) (32-bit)

**Comment by AllForNothing** [comment]
@rsha123 Can you upgrade your chrome to version 104.xx.xx, and then have a try?

And  did you find any errors in the console tab under chrome's debug mode?

**Comment by rsha123** [comment]
> 

Yes, I can see the same msg's in console and then login. after few seconds/minutes it throws an error

**Comment by AllForNothing** [comment]
> > 
> 
> Yes, I can see the same msg's in console and then login. after few seconds/minutes it throws an error

Can you post a screenshot of the error?

**Comment by rsha123** [comment]
> > > 
> > 
> > 
> > Yes, I can see the same msg's in console and then login. after few seconds/minutes it throws an error
> 
> @rsha123 Can you post a screenshot of the error?

It is a 404 error

**Comment by AllForNothing** [comment]
@rsha123 Seems like a  browser cache issue. Try clear the cache then reload Harbor UI, and see if it works for you
