### ISSUE TITLE
Push image error

### ISSUE THREAD

**Issue by ilhan-sadikoglu** [goharbor/harbor#17361]
Hi. I create private registry with harbor. Then I opened it to external access using nginx and cloudflare. 
And successfully logged in.
![image](https://user-images.githubusercontent.com/56480436/183620416-8602bdd7-c519-4c8c-ad06-d862604b6db4.png)

Then then i tried to do an image push.
![image](https://user-images.githubusercontent.com/56480436/183621072-3332fe36-1e32-4a5c-a694-474d444552f4.png)
But it gave an error like this
![image](https://user-images.githubusercontent.com/56480436/183621349-bccdcf36-3671-480b-850d-70f3783678ac.png)

What could be the error?

**Comment by zyyw** [comment]
or alternatively, could you please try to push another image to Harbor as well, which doesn't exist on Harbor.

**Comment by ilhan-sadikoglu** [comment]
Hello. I solved the problem. When using the HTTP protocol, add this line in /etc/docker/daemon.json :
{
"insecure-registries" : ["HOSTNAME"]
}
and
systemctl reload docker
systemctl restart docker
