### ISSUE TITLE
Some translations are out of sync

### ISSUE THREAD

**Issue by DinghaoJoe** [goharbor/harbor#17370]
E.g
en-us-lang.json: P2P_PROVIDER.NAME_TOOLTIP
zh-cn-lang.json: P2P_PROVIDER.NAME_TOOLTIP not found, but has DESTINATION_NAME_TOOLTIP
So it's better to sync

**Comment by AllForNothing** [comment]
@DinghaoJoe What's your harbor version?  You can clear your browser cache and reload. This should fix the issue
