### ISSUE TITLE
Pull-based replication from private docker registry gives "400 Bad Request" when a destination namespace is not given

### ISSUE THREAD

**Issue by imageschool** [goharbor/harbor#17379]
(Harbor <-> insecure local private registry)

According to the [documents](https://goharbor.io/docs/2.5.0/administration/configuring-replication/create-replication-rules/), "If you do not enter a namespace, resources are placed in the same namespace as in the source registry"

With a destination namespace given, the feature seems to work without any issue, however, without a destination namespace the replication fails with 400 Bad Request.

**Comment by zyyw** [comment]
Hi @imageschool , which Harbor version you were using when you encountered with this issue? 
Tried Harbor (Version v2.5.3-797c3536), there is no issue when doing pull-based replication without specifying a destination namespace. Artifact is able to be replicated over even when the destination namespace is not specified.

**Comment by zyyw** [comment]
Could you please also provide us with more details for example: the replication rule, full error message

**Comment by imageschool** [comment]
@zyyw Version v2.5.3-797c3536 for me as well, I have installed them through helm-chart.

When I put namespace, it works perfectly. Without one, please look below for the details

![image](https://user-images.githubusercontent.com/29969006/184820979-abfea183-2e1d-448c-b1d4-dae6eb350733.png)
![image](https://user-images.githubusercontent.com/29969006/184821349-23c4908a-c3a1-473d-9831-f2d113fda882.png)

And one of the task logs
![image](https://user-images.githubusercontent.com/29969006/184821279-cafd3832-301a-401e-b4b5-71a12cbfadc9.png)

**Comment by imageschool** [comment]
@zyyw Have you checked the above!?

**Comment by chlins** [comment]
@imageschool It seems your image in the docker registry without namespace(default is library), but for harbor the project/namespace is required, so you could specify your dest namespace as library or any other.

**Comment by imageschool** [comment]
> @imageschool It seems your image in the docker registry without namespace(default is library), but for harbor the project/namespace is required, so you could specify your dest namespace as library or any other.

@chlins Yes, it works no problem when I specify destination namespace. 
But according to the documentation, it should also work when the namespace is not given (i.e all images underlying at the project root path) is this correct?

**Comment by chlins** [comment]
As described in the docs: https://goharbor.io/docs/2.5.0/administration/configuring-replication/create-replication-rules/

> For Destination Namespace, enter the name of the namespace in which to replicate resources in the text box. If you do not enter a namespace, resources are placed in the same namespace as in the source registry.

If the dest namespace was not given, it will use the same namespace with the source, but in your source registry, there are no namespaces, `work well when the namespace is not given` depends on that you have namespace in the source registry.

**Comment by imageschool** [comment]
Right, so this is intended behaviour, I'm closing the issue.
