### ISSUE TITLE
Harbor-portal:v2.5.3 is using end of life nginx version 1.19.3

### ISSUE THREAD

**Issue by sajithvasu** [goharbor/harbor#17378]
Harbor-portal:v2.5.3 is using end of life nginx version 1.19.3. Please check - https://endoflife.date/nginx

**Comment by sajithvasu** [comment]
@zyyw : Is there any way to fix this by updating the tdnf nginx package?

**Comment by zyyw** [comment]
Dup of this issue:
* https://github.com/goharbor/harbor/issues/17170
