### ISSUE TITLE
README.md page `Nightly Status` image does not display properly

### ISSUE THREAD

**Issue by mengjiao-liu** [goharbor/harbor#17371]
**Expected behavior and actual behavior:**
README.md page `Nightly Status` image does not display properly.

![image](https://user-images.githubusercontent.com/44460091/183836318-ac3843bc-54e5-4363-97ff-66c464856446.png)

markdown content:
```
[![Nightly Status](https://us-central1-eminent-nation-87317.cloudfunctions.net/harbor-nightly-result)](https://www.googleapis.com/storage/v1/b/harbor-nightly/o)
```
image link: https://us-central1-eminent-nation-87317.cloudfunctions.net/harbor-nightly-result

![image](https://user-images.githubusercontent.com/44460091/183837531-8da54ff4-6a5a-4a3e-9f0c-57e057daae54.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

https://github.com/goharbor/harbor

**Comment by MinerYang** [comment]
Hi @mengjiao-liu 
Thanks for your notice. The service is working now and I would like to close this issue by fixed.
