### ISSUE TITLE
Robot Account not created with secret we specify

### ISSUE THREAD

**Issue by ChrisJBurns** [goharbor/harbor#17386]
**Expected behaviour and actual behaviour:**
When I create a Robot account with `POST /robots` with the `secret` in the body, I expect the `secret` returned to be the `secret` I provided. But it is not, it is a completely separate secret. I have to submit an additional `PATCH /robots/{id}` with the desired `secret` value to make sure the robot account actually has the secret I want.

**Steps to reproduce the problem:**
- Create a Robot Account via the API with a secret value specified in request body

**Versions:**
Please specify the versions of following systems.
 Harbor version [`2.5.3`](https://github.com/goharbor/harbor-helm/blob/1.9.0/Chart.yaml#L4)

**Comment by lengrongfu** [comment]
I think this field is not assignable.

**Comment by ChrisJBurns** [comment]
When you say not assignable what do you mean? It's in the OpenAPI spec for the Harbor API for the `/robots/{id}` endpoint response.

**Comment by zyyw** [comment]
it's by design.

**Comment by ChrisJBurns** [comment]
What is "by design" mean? Sorry, still struggling to understand which parts are intended. As a user of the Harbor service, if I see a field in the API spec that is part of a response, I'd expect it to come back unless it describes elsewhere in the spec that it won't be returned under certain circumstance.

**Comment by nexus-core174** [comment]
This issue is almost four years old now, but I just ran into the same issue, if the endpoint allows the user to specify a secret, I expect it to be used in the creation. The example request in the Swagger UI is as follows:

```json
{
  "name": "string",
  "description": "string",
  "secret": "string",
  "level": "string",
  "disable": true,
  "duration": 0,
  "permissions": [
    {
      "kind": "string",
      "namespace": "string",
      "access": [
        {
          "resource": "string",
          "action": "string",
          "effect": "string"
        }
      ]
    }
  ]
}
```

So either this should not be exposed, or when the user specifies a secret it should be used.

Would love to hear why this is as designed, currently.
