### ISSUE TITLE
Harbor not communicating to LDAP sever while pulling images

### ISSUE THREAD

**Issue by vishal662** [goharbor/harbor#17389]
Hi,

In Harbor we have done configuration of LDAP server as mentioned below in the snapshot.
![image](https://user-images.githubusercontent.com/71074868/184295217-ef0dc595-aab1-4886-9803-0a3a9e2136d5.png)

Even though imagePullSecrets is present and mentioned in deployment yaml file, harbor is not communicating to LDAP server to authenticate the credentials.
We tried this scenario by making the repositories both public and private, but in both the cases its not communicating to LDAP server.
Can you please help us resolve this issue?

Thanks,
Vishal.

**Comment by zyyw** [comment]
What error message do you have in hand?
