### ISSUE TITLE
Use registry or distribution as storage backend for helm charts

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17395]
### Discussed in https://github.com/goharbor/harbor/discussions/17394

<div type='discussions-op-text'>

<sup>Originally posted by **lengrongfu** August 12, 2022</sup>
Hi,
Currently using `Chartmuseum` as the storage service for `helm charts` , The current [distribution](https://github.com/distribution/distribution) also supports the storage of helm charts, and I hope to use the same distribution as the `OCI  artifact` storage backend in Harbor.
Thanks.</div>

**Comment by zyyw** [comment]
@lengrongfu As discussed in the community meeting, Harbor is going to deprecate chart-museum, and there will be no further and additional development for it. It is extremely recommended to use OCI compatible helm charts

**Comment by lengrongfu** [comment]
Yes, I saw the discussion in the community today; after the chart-museum is deprecated, is the helm-charts table page still visible on harbor, and how to distinguish between helm chart and image?

**Comment by zyyw** [comment]
after deprecation completed, the helm-charts table will be disabled.

**Comment by panpan0000** [comment]
@zyyw ,  then how can we list the charts in harbor ?  How can we tell between image and charts both in OCI?
