### ISSUE TITLE
can't pull image from harbor,replication policy don't work either,error 403

### ISSUE THREAD

**Issue by mumong** [goharbor/harbor#17406]
What can we help you?

> https://stackoverflow.com/questions/73244273/error-happend-when-i-pull-image-from-my-harbor

i edit it on stackoverflow.
anayone know how can i fix it ?

when i pull image from my harbor it shows that 

> error parsing HTTP 403 response body: unexpected end of json input: ""
my harbor version is v1.1.2

**Comment by chlins** [comment]
The version v1.1.2 is obsolete and out of support, but the error 403 seems your credential is not correct, or you could check whether the account has the permission to the project.

**Comment by mumong** [comment]
> 

i use the root user,i can't pull image from harbor but push function is ok.the thing we might know this mistake .our company use the registry by our onw .like our people secondary develope the registry image and use it.then it 403,and when i change back the original registry image ,it dosn't shou on the web image hub
