### ISSUE TITLE
Cannot push helm charts

### ISSUE THREAD

**Issue by drew-viles** [goharbor/harbor#17402]
Habor Chart Version: 1.9.3
Harbor App Version: 2.5.3 
Helm Version: v3.9.3

I've installed the Harbor chart and have disabled ChartMuseum as, to my understanding, this is being deprecated in favour of the OCI compatible method for storing Helm Charts.

Docker pushing works absolutely fine but pushing a Helm Chart does not.

So, I've created a new project in Harbor and added a user.
I then use `helm registry login -u drew` to login to the repo.
That works fine.

Next I package up the chart with `helm package /chart/path/`

Finally, I try to push with `helm push chart-version.tgz oci://harbor.example.com/project_name` (and without the project name on the end)
This fails with: `Error: invalid_reference: invalid repository`

I've tried using the guide in the [docs on the website](https://goharbor.io/docs/2.5.0/working-with-projects/working-with-images/managing-helm-charts/#manage-helm-charts-with-the-oci-compatible-registry-of-harbor) but they refer to an older version of Helm and uses commands that were [deprecated in 3.7 of Helm](https://github.com/helm/helm/releases/tag/v3.7.0).

I've also tried going down the route of doing `helm repo add repo_name https://harbor.example.com/project_name --username=drew`  (again, with and without the project name on the end) and it errors with `Error: looks like "https://harbor.example.com/project_name" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile`.

No matter what approach I take I cannot get this working so I was wondering if there is a known bug or if I'm missing something that isn't described in the docs.

I suspect the `cannot unmarshal string into Go value of type repo.IndexFile` to be a red flag because once I've pushed the chart I'd need that to work and with an unmarshal coming into the equation here, it makes me wonder if there is something going on with the push command too whereby maybe it's not compatible with the latest version of helm.

I've tried with Helm 3.8 and helm 3.6 too as a test for historical Helm binaries but they produce the same errors.

Any thoughts/suggestions would be appreciated.

**Comment by DanielCastronovo** [comment]
Hello @drew-viles, i have exactly the same issue 👍🏻

**Comment by drew-viles** [comment]
I have indeed, unfortunately that's not working for me.
I've put all steps above in the OP.

**Comment by alex-broad** [comment]
So the docs may help here: https://goharbor.io/docs/2.5.0/working-with-projects/working-with-images/managing-helm-charts/#manage-helm-charts-with-the-oci-compatible-registry-of-harbor

Note that there appears to be a static path you have to talk to: `chartrepo/project_name`

**Comment by alex-broad** [comment]
Ah sorry I see you've tried following the docs too :(
