### ISSUE TITLE
自定义角色权限（Custom role permissions）

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#17411]
## chinese
我在实际的业务环境中遇到一个问题：应用需要镜像同步的权限，但项目管理员没有该权限，最终只能给admin权限，处于安全考虑，这不是个明智的决定，如果项目管理员有镜像同步的权限，或者可以自定义角色权限。
### English：
I have encountered a problem in the actual business environment: the application needs the permission of image synchronization, but the project administrator does not have this permission, and can only give admin permission in the end. For security reasons, this is not a wise decision. If the project administrator has the permission of image synchronization, or can customize the role permissions.

**Comment by stonezdj** [comment]
The replication should be created by admin or system level robot account, it works as designed.
