### ISSUE TITLE
Only the latest Garbage Collection history log (scheduled) is available

### ISSUE THREAD

**Issue by tompatib** [goharbor/harbor#17410]
**Expected behavior and actual behavior:**
We had issues with GC job as interferred with the Trivy scheduled image scan, so we moved the GC job to a daily schedule. Since then the GC job works fine but we noticed that only the latest log content can be retrieved.

**Steps to reproduce the problem:**
We have a daily GC job to perform cleanups. I can always check the latest log only.

![image](https://user-images.githubusercontent.com/16067575/184825607-7d5f6316-635c-49b6-9d58-fa1ebf57cdcf.png)

On the next day the same log shows not found.

![image](https://user-images.githubusercontent.com/16067575/184824746-573e0e48-3c33-475c-a263-9f29fe11ca7f.png)

![image](https://user-images.githubusercontent.com/16067575/184825748-647f90e6-f9d8-4c6f-b5de-b98cc8859c31.png)

**Versions:**

- harbor version: v2.5.0-98e1b82f

**Additional context:**

We are using built-in Redis.

**Comment by chlins** [comment]
The job logs were generated and stored by jobservice, these files will be cleaned periodically by sweeper, you can check the configuration in the `config.yaml` of jobservice.

**Comment by tompatib** [comment]
@chlins, thanks for the hint, looks like this is it. Based on this I consider this works as expected. Maybe in such case, based on the sweeper setting the log button could be removed for those records which supposed to be cleaned already.

`    sweeper:
      duration: 1 #days`
