### ISSUE TITLE
Non-admin users cannot query the Audit log of deleted project

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17412]
**Expected behavior and actual behavior:**
Expected: Non-admin users can query the Audit log of deleted project
Actual: Non-admin users cannot query the Audit log of deleted project

**Steps to reproduce the problem:**
1. Create a user as demo_user
2. Log in to harbor with demo_user and create a project as demo_project
3. Push image to demo_project
4. Verify Audit log with Push image
5. Delete demo_project
6. demo_user cannot query the Audit log of demo_project

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0

**Comment by stonezdj** [comment]
The root cause of this issue is the project is already removed and when querying audit_log, it filters the audit log by project id which the user is a member of, then it filter out the removed project.
