### ISSUE TITLE
Harbor v2.5.3 api PUT request failing

### ISSUE THREAD

**Issue by sajithvasu** [goharbor/harbor#17414]
After upgrading harbor to 2.5.3 version, we have noticed that the PUT method for system robot account fails with error : 

{"errors":[{"code":"NOT_FOUND","message":"project * not found"}]}

Steps to reproduce:
1) Create system robot account with POST method /robots and give permission to all the projects. 

Example payload for post method to create system robot account:

{
    "description": "Sample system account",
    "level": "system",
    "name": "sample",
    "expires_at": 0,
    "permissions": [
        {
            "access": [
                {
                    "action": "pull",
                    "effect": "allow",
                    "resource": "repository"
                },
                {
                    "action": "read",
                    "effect": "allow",
                    "resource": "helm-chart"
                }
            ],
            "kind": "project",
            "namespace": "*"
        }
    ]
}

2) Try to update the system account using using PUT method /robots/{robot_id}

**Comment by slenky** [comment]
Same issue on v2.5.3 during modifying robot account's permissions.

**Comment by stonezdj** [comment]
The Harbor 2.5.4 and 2.6.0 fixed this issue.
