### ISSUE TITLE
Improvement for audit log forward

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17413]
For the below case:

After the forward endpoint is configured and skip DB is enabled, the log will be recorded in core.log after the forward endpoint hangs midway. In this case, I think the bad experience is that unless the user takes the initiative to read the core.log or takes the initiative to ping the forward endpoint, he will not know that the forward endpoint is down.

so, maybe we can ping the forward endpoint every time when the user enters the config page. if the forward endpoint is down, then show a warning.

**Comment by stonezdj** [comment]
If add a function to ping a syslog endpoint, it could bring a security issue.

**Comment by AllForNothing** [comment]
Removed 2.7 label
