### ISSUE TITLE
Okta OIDC

### ISSUE THREAD

**Issue by DanielCastronovo** [goharbor/harbor#17425]
Hello, 

I've setup an OIDC authentication with Okta.
But it doesn't work.

```
Failed to verify connection: {URL:https://xxxxx.okta.com/oauth2/v1/authorize VerifyCert:true}, err: 404 Not Found:
[DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"BAD_REQUEST","message":"failed to verify connection"}]}
```

OIDC Endpoint : https://xxxxx.okta.com/oauth2/v1/authorize
OIDC Client ID : XXXX
OIDC Client Secret: XXXX
OIDC Scope : openid,profile,email,groups
Verify Certificate : ✔️ 

If a people that have already setup Harbor with Okta, could you please share with me your configuration.

**Comment by fmalykh** [comment]
Hey @DanielCastronovo,
Try setting `OIDC Endpoint: https://xxxxx.okta.com`

**Comment by DanielCastronovo** [comment]
Many thanks @fmalykh, it's works !

It's could be nice to adding this tips on the documentation
