### ISSUE TITLE
Unable to use auth.token option in registry config.yml

### ISSUE THREAD

**Issue by aggo15** [goharbor/harbor#17427]
I'm currently evaluating harbor v2.4.3 for the registry service. Everything works fine except that the config.yml for registry is using `auth.htpasswd` option instead of `auth.token`. When a docker client login to harbor registry, it will store the credential on client machine in config.json file and it can be decrypt easily to get the credential in plain text. 

Here is the output when I attempt to login from one of the docker client.
```
root@machine:~# docker login <harbor_registry_address>
Username: testuser
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

I prefer not to store the credential unencrypted on machine. Is there anyway to enable `auth.token` option in registry config.yml using harbor.yml?

**Comment by Vad1mo** [comment]
Your reported issue is not related to Harbor. Your local Conainer runtime, like Docker, Podman etc. is telling you how it stors the creds locally. 

see the message on how to resolve it.

> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
>

**Comment by aggo15** [comment]
@Vad1mo I think it is not completely unrelated.

Of course i can setup a credential store for my machine, but what if other machine not under my control are using the same registry and their owner/users maybe don't have the know how to setup the credential store?

Wouldn't it will be a lot easier for other people if i can just turn on the `auth.token` via harbor and everyone using the registry don't have to worry about this?

I believe this is something that harbor should allow the user to turn on, or at least make it configurable via harbor.yml. Judging from your respond i guess harbor is not supporting this option yet. Please consider to add this option in the future.
