### ISSUE TITLE
Harbor v2.6.0-rc2: CVE export via API results in empty file

### ISSUE THREAD

**Issue by tuxpeople** [goharbor/harbor#17429]
First and foremost, I know it's a RC release. It's not production, it's in test as I'm very interested in the new CVE export feature. Most likely, I'm doing it wrong, but I just want to make sure it's not a bug before you release 2.6.0

**Expected behavior and actual behavior:**
Expected: Having a csv file with all CVE

Actual: Having an empty file

**Steps to reproduce the problem:**
I did this:
- Installed a VM with Ubuntu 20.04.4 LTS
- Installed Docker CE from Docker itself
- Installed Harbor v2.6.0-rc2 with the bundle from the release page with Trivy enabled
- Made a public project
- Pushed a container image with vulnerabilities
- Scanned that image

What is working: CVE export via WebUI results in a proper CSV, as expected.
Whats not working: Getting the CVE export via API (results in empty file)

I made a small script to test the API way:

```shell
#!/bin/bash

AUTH="<base64 encoded auth>"
IP="<Harbor IP address>"

# Trigger export CVE and get it's id
ID=$(curl -q -X 'POST' \
  "http://${IP}/api/v2.0/export/cve" \
  -H 'accept: application/json' \
  -H 'X-Scan-Data-Type: application/vnd.security.vulnerability.report; version=1.1' \
  -H "authorization: Basic ${AUTH}" \
  -H 'Content-Type: application/json' \
  -d '{
  "projects": [
    4
  ]
}' | jq -r .id)

# Wait until the report is ready
STATUS="notready"
while [[ "${STATUS}" != "Success" ]]; do
    STATUS=$(curl -q -X 'GET' \
    "http://${IP}/api/v2.0/export/cve/execution/${ID}" \
    -H 'accept: application/json' \
    -H "authorization: Basic ${AUTH}" | jq -r .status)
    sleep 10
done

# Download the report's CSV file
curl -vvv -X 'GET' \
  "http://${IP}/api/v2.0/export/cve/download/${ID}?format=CSV" \
  -H 'accept: text/csv' \
  -H "authorization: Basic ${AUTH}" \
  --remote-name \
  --remote-header-name \
  --write-out "Downloaded %{filename_effective} file"
```

The first two steps look successful. But despite the fact the report is "ready", I'm getting an empty file. Heres the output of the last `curl`:

```
* Connected to ${IP} (${IP}) port 80 (#0)
> GET /api/v2.0/export/cve/download/16?format=CSV HTTP/1.1
> Host: ${IP}
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> accept: text/csv
> authorization: Basic <base64 encoded auth>
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 19 Aug 2022 09:03:07 GMT
< Content-Type: text/csv
< Content-Length: 0
< Connection: keep-alive
< Content-Disposition: attachment; filename="scandata_export_16.csv"
< Set-Cookie: sid=d98c7069c63a0c2af27ecd9b4fc8d1ad; Path=/; HttpOnly
< X-Request-Id: 3b9b6b7e-5dec-4608-b121-ff129f616a81
< X-Frame-Options: DENY
< Content-Security-Policy: frame-ancestors 'none'
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host ${IP} left intact
Downloaded scandata_export_16.csv file
```

File:
```
$ ls -la scandata_export_16.csv
-rw-r-----  1 tdeutsch  staff  0 19 Aug 11:03 scandata_export_16.csv
```

Should that work that way? Or do I use it wrong?

**Versions:**
- harbor version: `v2.6.0-rc2`
- docker engine version: `Docker version 20.10.17, build 100c701` 
- docker-compose version: `Docker Compose version v2.6.0`

**Comment by tuxpeople** [comment]
Ok, facepalming me now. I was wrong: I used the wrong project ID 🤦  Sorry.

But I have a question for clarification. The API Doc says, the list of projects can be empty and defaults to all: 

![image](https://user-images.githubusercontent.com/1506076/185588248-34aa9f88-2dd9-4fad-940e-9a41811443d1.png)

But when I try it:

```
{
  "projects": [
  ]
}
```

It complains:

`{"errors":[{"code":"BAD_REQUEST","message":"bad request: only support export single project, invalid value: []"}]}`

**Comment by chlins** [comment]
I think it's the mistake in the API Docs, export CVE only supports one project right now, and define this parameter as array for extension in the future.
