### ISSUE TITLE
CVE Export ScanDataExportRequest expects a list of project in spec but fails if a list is provided on Harbor 2.6.0-RC2

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#17431]
So the Model `ScanDataExportRequest` is expecting an array but fails if an array with multiple projects is provided.

https://github.com/goharbor/harbor/blob/49d73fa57dd74766ae7cd1083b53d50ed6624489/api/v2.0/swagger.yaml#L9167-L9195

**Expected behavior and actual behavior:**
Don't fail if an array is provided, if not possible, adapt spec.

**Steps to reproduce the problem:**

```sh
curl -X 'POST' \
  'https://focused-wing.container-registry.com/api/v2.0/export/cve' \
  -H 'accept: application/json' \
  -H 'X-Scan-Data-Type: application/vnd.security.vulnerability.report; version=1.1' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: 2eNLBjYDrAA75F/x5iLdcruuvjw47fV/5O6+JPncMgXaP6Y2zB+5QI9eSCEbMCPEOoMjSwJa2iLAt82z5KQOqg==' \
  -d '{
  "projects": [
    1,2
  ]
}'

```
**Versions:**

- harbor version: 2.6.0-rc2

**Comment by chlins** [comment]
Hi, please refer to this https://github.com/goharbor/harbor/issues/17429#issuecomment-1221682360
