### ISSUE TITLE
Harbor/Notary can't connect to to Postgres 14 because of SCRAM Authentication

### ISSUE THREAD

**Issue by rizzaricreative** [goharbor/harbor#17449]
What can we help you?
Hi,

I'm using RDS Postgres as an external db and ran into a few issues. Firstly noted that we need to create registry and notary db's manually which is not the end of the world.

However, how do we overcome the SCRAM authentication ?

see this from notary log

`➜  terraform git:(master) ✗ kubectl -n harbor logs -f harbor-notary-server-54c988b887-kz7z7 
2022/08/22 23:22:05 Updating database.
2022/08/22 23:22:05 schema_migrations table does not require update, skip.
no change
notaryserver database migrated to latest version
{"level":"info","msg":"Version: 0.6.1, Git commit: d6e1431f","time":"2022-08-22T23:22:05Z"}
{"level":"info","msg":"Using remote signing service","time":"2022-08-22T23:22:05Z"}
{"level":"info","msg":"Using postgres backend","time":"2022-08-22T23:22:05Z"}
{"level":"fatal","msg":"Error starting postgres driver: pq: unknown authentication response: 10","time":"2022-08-22T23:22:05Z"}`

Any help would be greatly appreciated !

This is the helmchart version

`        repository  = "https://helm.goharbor.io"
        chart       = "harbor"
        version     = "1.9.1"`

**Comment by stonezdj** [comment]
could you please check if the harbor-core could connect to the postgres?

**Comment by rizzaricreative** [comment]
Hi @stonezdj ,

atm harbor core is running fine, connected to RDS. However notary does still have the authentication issue as mentioned above

**Comment by YangJiao0817** [comment]
This is because Notary does not support PostgreSQL 14, Notary is deprecated, you can use [Sigstore/Cosign](https://github.com/sigstore/cosign), [Sigstore/Cosign](https://github.com/sigstore/cosign) is integrated in Harbor 2.5.x.
