### ISSUE TITLE
Log is too flatten to understand.  All the operations seems are for repository, but some of them are for project.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#1745]
![image](https://cloud.githubusercontent.com/assets/2841473/24241112/beae87b0-0fee-11e7-94f2-f572b5470e03.png)

**Comment by reasonerjt** [comment]
I agree this implementation is adhoc, Ideally the log should be "activity log" and be broken down into  different tables for better tracking and display.

**Comment by lweitzman** [comment]
Can we add a target column which would identify what object the activity is for? can the filter show just activity for projects or repos or all? would this help for this release?
