### ISSUE TITLE
Harbor repository inaccessible after service docker restart

### ISSUE THREAD

**Issue by testwill** [goharbor/harbor#17450]
r# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED       STATUS                             PORTS                       NAMES
d7767277e24f   goharbor/nginx-photon:v2.5.1    "nginx -g 'daemon of…"   4 weeks ago   Restarting (1) 4 seconds ago                                   nginx
f3752885f6f6   goharbor/harbor-portal:v2.5.1   "nginx -g 'daemon of…"   4 weeks ago   Up 20 seconds (health: starting)                               harbor-portal
e1f851501cef   goharbor/harbor-log:v2.5.1      "/bin/sh -c /usr/loc…"   4 weeks ago   Up 20 seconds (health: starting)   127.0.0.1:1514->10514/tcp   harbor-log

docker logs -f 
.....
nginx: [emerg] host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23

**Comment by rrgadeev** [comment]
https://github.com/goharbor/harbor/issues/12913#issuecomment-684497888

**Comment by testwill** [comment]
thanks.
