### ISSUE TITLE
Quay.io cannot sync public namespace, only exact image/repo inside namespace

### ISSUE THREAD

**Issue by qw3r3wq** [goharbor/harbor#17452]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected:
after execution of replication expect in destination project to see around 170 images with tag current-tripleo
Actual:
After replication execution (finishes successfully with (i) that no images found.

**Steps to reproduce the problem:**
1) create endpoint selecting quay and in address enter: https://quay.io
2) create replication as pull > select quay.io > source registry: tripleoussuri/** > tag: current-tripleo > destination ussuri, everything else default
3) run replication
4) open project list and it is empty

**Versions:**
Using offline installation
- harbor version: [2.4.3] and [2.5.3]
- docker engine version: [20.10.17]
- docker-compose version: [2.7.0]

**Additional context:**
Tried to define in destination exact image in https://quay.io/tripeoussuri , and exect project and that is completed successfully.

installed with `sudo ./install.sh --with-notary --with-trivy --with-chartmuseum`

- **Harbor config files:
  - harbor.yml http://paste.debian.net/hidden/9460b7cc/
- **Log files:**
- log file tar.xz and configsonly.tar.xz is in this google drive shared folder: https://drive.google.com/drive/folders/1KaQ_b6QHtHbB_xm5VUoNsRDxu9UyScVx?usp=sharing

**Comment by qw3r3wq** [comment]
by the way if I create project with same endpoint as proxy and request exact image, I get it and it gets synced to harbor proxy project

**Comment by chlins** [comment]
@qw3r3wq It can work by proxy cache, but can not work with replication if without credential, the `quay.io` return empty repos when request catalog API if no authorization.

**Comment by qw3r3wq** [comment]
I believe would be nice to have this info in replication documentation, but it is just my observation, as this bit is missing, I am new to whole conteinerization system.

**Comment by qw3r3wq** [comment]
By the way, even with credentials, it is not working.

I use to login - robot account.

**Comment by chlins** [comment]
I think you can refer to https://goharbor.io/docs/2.5.0/administration/configuring-replication/create-replication-endpoints/ for quay authorization, robot account maybe not be supported.
