### ISSUE TITLE
Why ca.key for client side is used for server side?

### ISSUE THREAD

**Issue by LiyuCode** [goharbor/harbor#17460]
Was following a Harbor doc page [Configure HTTPS Access to Harbor](https://goharbor.io/docs/2.5.0/install-config/configure-https/), but get confused by what are the files/certificates are to be used in Docker client side and Goharbor server side respectively.

For instance, according to [a page in Docker](https://docs.docker.com/engine/security/certificates/), the `ca.crt` is to store in client side as a part of docker configuration, `/etc/docker/certs.d/{goharbor_server_domain}`.

However, in the doc page, the `ca.crt` is also used for generate `ourdomain.om.crt` which is used in server side too.

To my current understanding, the processes of generating certificates to be used in client side and server side are independent. 

Why doing so in the doc page?

**Comment by rrgadeev** [comment]
https://en.wikipedia.org/wiki/Certificate_authority#:~:text=In%20cryptography%2C%20a%20certificate%20authority,to%20the%20certified%20public%20key
In short, the CA signs the client certificate. But to trust the client certificate, you need to trust the CA. To do this, ca.crt must be added to the root trusted certificates. Or in /etc/docker/harbor.domain.local/ca.crt, for docker.

**Comment by LiyuCode** [comment]
Hi rrgadeev, thank you for the reply.

_-- harbor clients, where the command 'docker login yourdomain.com' is to execute.
-- harbor servers, where the harbor service is running._

How about the understandings below ? (Considering the self-signing cases, no trusted third-party CA involved.)


Assuming there is a user (client), User1, and a server, YD1.com, has been setuped via the process in the doc page.
Then the current status is illustrated as in the following attachment `Cert Flow.svg`.
![Cert Flow](https://user-images.githubusercontent.com/10735579/187026364-b866d614-5773-436b-8c45-f0c9b89b738a.svg)

Now, what should we do if we want to add a new user (using its own certs) to access the server?

How about the following below ?

**On the new client, User2:**
 - Generating its own `ca.key`, `ca.crt`, named `ca-user2.key`, `ca-user2.crt`.

**On the 1st server, YD1:**
 - use the `ca-user2.key`, `ca-user2.crt` to generate a new `YD1.com.crt` named `User2-YD1.com.crt`, then store the file on `/data/cert/` and add a new entry 'certificate: /data/harbor/certs/User2-YD1.com.crt' in `harbor.yml`. (Then restart the server?)
 - use the `User2-YD1.com.crt` to generate a new `YD1.com.cert` named `User2-YD1.com.cert`, and pass it to User2 for `docker login YD1.com`

Or alternatively, User2 can use the old `ca.key` to generate its own `ca-user2.crt`. then put it and the old `YD1.com.key` and the old `YD1.com.cert` in `/etc/docker/cert.d/YD1.com` for the `docker login` command ?
