### ISSUE TITLE
CSRF tolken invalid while deleting images

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#17463]
Hi all,

We observed that when we are trying to delete multiple images in a repository (e.g. seven images) at once, we will see a red banner which says `CSRF tolken invalid`. Although this issue, a random amount of images will be deleted and a random number of images will remain in the repository.
For our Harbor environment we are using an OIDC provider and each user is logged in with this.
We already tried this possible solution, but it is still not working (Chrome, Brave, Edge, Firefox): https://todoist.com/help/articles/csrf-token-error-messages

Does anyone have an idea, how this could be fixed?

Thank you in advance!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by AllForNothing** [comment]
@AlexBarth13 I'll have a look at this

**Comment by AllForNothing** [comment]
@AlexBarth13 When you are trying to delete multiple images, the corresponding number of requests will be sent. There is no transaction between these requests. So `some fail and some succeed` is possible.

**Comment by AlexBarth13** [comment]
removing stale label

**Comment by AlexBarth13** [comment]
removing stale label
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by AlexBarth13** [comment]
removing stale label...

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
