### ISSUE TITLE
Issue with event based replication of cosign signatures

### ISSUE THREAD

**Issue by sizowie** [goharbor/harbor#17479]
**Expected behavior and actual behavior:**
Event based replications with a tag filter (e.g. 'latest') should be triggered when an cosign signature is uploaded afterwards.

**Steps to reproduce the problem:**
- Create local push replication rule of an image *with* tag filter (e.g. 'latest') from project A to B (trigger mode event_based)
- Push (unsigned) image to A
- Image appears in project B (which is fine)
- Sign (cosign) Image in project A
- Signature is not being replicated to B (which is an unexpected behavior)

**Versions:**
- harbor version: v2.5.1-e5dbc6de
- docker engine version: 20.10.17
- docker-compose version: 1.28.2

**Comment by sizowie** [comment]
Note: leaving out the tag filter or use a wildcards ** will work as expected.

**Comment by MinerYang** [comment]
It have already fixed , pls refer to this https://github.com/goharbor/harbor/issues/16883
You could upgrade to version above v2.5.4

**Comment by sizowie** [comment]
Thank you!
