### ISSUE TITLE
Upgrade from2.4.x to 2.6: [FATAL] : failed to register scanners

### ISSUE THREAD

**Issue by bpedersen2** [goharbor/harbor#17475]
During upgrade from a 2.4.3 install to v2.6.0 harbor-core failed to start:
```
Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [INFO] [/core/main.go:270]: Registering Trivy scanner
Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [FATAL] [/core/main.go:288]: failed to register scanners: creating registration Trivy at http://trivy-adapter:8080 failed: dao: create registration: registration name or url already exists
```

Upgrade steps:
``` 
(backup)
docker pull goharbor/prepare:v2.6.0
 docker run -it --rm -v /:/hostfs goharbor/prepare:v2.6.0 migrate -i /home/harbor2.6/harbor.yml
(fetch new install.sh)
  ./install.sh --with-notary --with-trivy --with-chartmuseum
```

**Comment by bpedersen2** [comment]
I was able to startup harbor core after manually updating the database with new name and url for the  existing trivy entry.

**Comment by bpedersen2** [comment]
Deleting the old scanner record was very slow, I needed to first add indexes on

- `registration_uuid` for table `vulnerability_record`
- `report_uuid` for table `report_vulnerability_record`

**Comment by bpedersen2** [comment]
Hint: It is recommend to have an index on all colums used in foreign keys.

**Comment by YangJiao0817** [comment]
Hi @bpedersen2 , I followed your steps to upgrade from 2.4.3 to 2.6.0, but cannot reproduce failed to register scanners, can you provide more steps? cc @wy65701436

**Comment by bpedersen2** [comment]
One thing which may play a role: The trivy scanner had been added manually while trivy was still optional and the default was to use chair. The scanner name did not match the  new default name, but the url did match.

**Comment by zyyw** [comment]
@bpedersen2 thank you for the additional details. That might be to reason, as the error message did say `registration name or url already exists`. This error was returned when insert records into scanner table:
* https://github.com/goharbor/harbor/blob/v2.6.0/src/pkg/scan/dao/scanner/registration.go#L47

Closing it now.

**Comment by bpedersen2** [comment]
Well, I think it should only emit a warning, not halting the startup completly?

**Comment by zyyw** [comment]
Hi @bpedersen2, could you please provide us with the records in this table:
```
select * from scanner_registration;
```

**Comment by zyyw** [comment]
The scanner_registration has unique key constraint for both `scanner_registration_url_key` and `scanner_registration_name_key`:
```
postgres=# \c registry
You are now connected to database "registry" as user "postgres".
registry=# \d scanner_registration;
                                            Table "public.scanner_registration"
      Column       |            Type             | Collation | Nullable |                     Default
-------------------+-----------------------------+-----------+----------+--------------------------------------------------
 id                | integer                     |           | not null | nextval('scanner_registration_id_seq'::regclass)
 uuid              | character varying(64)       |           | not null |
 url               | character varying(256)      |           | not null |
 name              | character varying(128)      |           | not null |
 description       | character varying(1024)     |           |          |
 auth              | character varying(16)       |           | not null |
 access_cred       | character varying(512)      |           |          |
 disabled          | boolean                     |           | not null | false
 is_default        | boolean                     |           | not null | false
 use_internal_addr | boolean                     |           | not null | false
 immutable         | boolean                     |           | not null | false
 skip_cert_verify  | boolean                     |           | not null | false
 create_time       | timestamp without time zone |           |          | CURRENT_TIMESTAMP
 update_time       | timestamp without time zone |           |          | CURRENT_TIMESTAMP
Indexes:
    "scanner_registration_pkey" PRIMARY KEY, btree (id)
    "scanner_registration_name_key" UNIQUE CONSTRAINT, btree (name)
    "scanner_registration_url_key" UNIQUE CONSTRAINT, btree (url)
    "scanner_registration_uuid_key" UNIQUE CONSTRAINT, btree (uuid)
Referenced by:
    TABLE "vulnerability_record" CONSTRAINT "fk_registration_uuid" FOREIGN KEY (registration_uuid) REFERENCES scanner_registration(uuid) ON DELETE CASCADE

```

**Comment by zyyw** [comment]
@bpedersen2 Please help me understand your scenario. So in harbor 2.4.3, you manually add both Trivy and Clair as potential scanners and set Clair as the default scanner, and then you do the following steps trying to upgrade harbor from 2.4.3 to 2.6.0:
```
(backup)
docker pull goharbor/prepare:v2.6.0
 docker run -it --rm -v /:/hostfs goharbor/prepare:v2.6.0 migrate -i /home/harbor2.6/harbor.yml
(fetch new install.sh)
  ./install.sh --with-notary --with-trivy --with-chartmuseum
```
and see the following error message:
```
Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [INFO] [/core/main.go:270]: Registering Trivy scanner
Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [FATAL] [/core/main.go:288]: failed to register scanners: creating registration Trivy at http://trivy-adapter:8080 failed: dao: create registration: registration name or url already exists
```
Is this process correct?

Could you please provide us with the parameters when you manually add Trivy and Clair as potential scanners? 
<img width="569" alt="Screen Shot 2022-09-07 at 12 26 16" src="https://user-images.githubusercontent.com/6709992/188788598-ae4e2b16-f830-4900-9bc3-66fccf7f59ad.png">

**Comment by bpedersen2** [comment]
> @bpedersen2 Please help me understand your scenario. So in harbor 2.4.3, you manually add both Trivy and Clair as potential scanners and set Clair as the default scanner, and then you do the following steps trying to upgrade harbor from 2.4.3 to 2.6.0:
> 
> ```
> (backup)
> docker pull goharbor/prepare:v2.6.0
>  docker run -it --rm -v /:/hostfs goharbor/prepare:v2.6.0 migrate -i /home/harbor2.6/harbor.yml
> (fetch new install.sh)
>   ./install.sh --with-notary --with-trivy --with-chartmuseum
> ```
> 
> and see the following error message:
> 
> ```
> Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [INFO] [/core/main.go:270]: Registering Trivy scanner
> Aug 30 08:35:52 172.29.0.1 core[1064638]: 2022-08-30T06:35:52Z [FATAL] [/core/main.go:288]: failed to register scanners: creating registration Trivy at http://trivy-adapter:8080 failed: dao: create registration: registration name or url already exists
> ```
> 
> Is this process correct?


Yes, seems accurate.
 
> Could you please provide us with the parameters when you manually add Trivy and Clair as potential scanners (the `Name` and `Endpoint` for example)

 2 | 6d6f9bf0-088d-11eb-87e7-0242ac1c0006 | http://trivy-adapter:8080 | trivy |             |      |             | f        | t          | t                 | f         | f                | 2020-10-07 11:08:28.437451 | 2020-10-07 11:08:28.437454

Main difference is  the spelling of the name (all lowercase)

**Comment by zyyw** [comment]
It looks that the trivy url `http://trivy-adapter:8080` you manually added before upgrading harbor from 2.4.3 to 2.6.0 conflict with the one used by `./install.sh --with-trivy`. Because there is a unique key constraint for both `scanner_registration_url_key` and `scanner_registration_name_key`.

I'm curious how you managed to manually add trivy with this particular url `http://trivy-adapter:8080` though.

**Comment by bpedersen2** [comment]
Probably really manually while clair was still the default ( I guess we started with 2.0 and added trivy at that time).
