### ISSUE TITLE
Increase UI session timeout

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#17474]
Hi all,

We noticed in our Harbor v2.5.0 environment, that we have a very low UI session timeout setting because we have to login multiple times a day.
Is there any setting or parameter in the configuration where we can adjust this timeout value?

Thank you in advance!

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by AlexBarth13** [comment]
Hi @AllForNothing, hi @chlins,

This is still an open topic for us. But am I right that this will get fixed in v2.7.x?

Thanks!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by chlins** [comment]
@AlexBarth13 Yes, the pr is under reviewing, the feature will be delivered in the v2.7.
