### ISSUE TITLE
DB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found

### ISSUE THREAD

**Issue by zeyad-mhmd** [goharbor/harbor#17473]
What can we help you?

Currently i installed Harbor on  VMware Photon OS (64-bit) & its disconnected server so i had to whitelist *.github.com i was able to scan images but for some reason suddenly i cannot scan for images

Thanks to all for your dedication & hard work 

---------- Logs of report fc1a9e90-2ac0-490a-9392-2cce4537780a ----------
2022-08-29T00:00:03Z [INFO] [/pkg/scan/job.go:385]: {
  "uuid": "fab89ca3-6179-11ec-abcc-0242ac120009",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.20.1",
  "create_time": "2021-12-20T09:48:26.698368Z",
  "update_time": "2021-12-20T09:48:26.698369Z"
}
2022-08-29T00:00:03Z [INFO] [/pkg/scan/job.go:385]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 1,
    "repository": "library/nginx",
    "tag": "",
    "digest": "sha256:186c79dc14ab93e43d315143ee4b0774506dc4fd952388c20e35d3d37058ab8d",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2022-08-29T00:00:03Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2022-08-29T00:00:03Z [INFO] [/pkg/scan/job.go:222]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2022-08-29T00:00:05Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-08-29T00:00:10Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-08-29T00:00:15Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-08-29T00:00:20Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-08-29T00:00:14.001Z	[34mINFO[0m	Need to update DB
2022-08-29T00:00:14.001Z	[34mINFO[0m	Downloading DB...
2022-08-29T00:00:15.424Z	[31mFATAL[0m	DB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found
: general response handler: unexpected status code: 500, expected: 200

**Comment by stonezdj** [comment]
Could you please check the trivy and trivy-adapter log?

**Comment by zeyad-mhmd** [comment]
The Trivy Container is up & i have whitelisted the below 
•	api.github.com
•	github.com
•	github-releases.githubusercontent.com

do i need to white list that too ?

ghcr.io


below are the logs from trivy container

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T00:18:52.977Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T00:18:52.977Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T00:18:53.589Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 193.188.52.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 41m11s]\n","level":"error","msg":"Scan failed","time":"2022-09-05T00:18:53Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T00:18:52.322Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T00:18:52.322Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T00:18:52.932Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 193.188.52.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 41m13s]\n","level":"error","msg":"Scan job failed","scan_job_id":"a57e7255f99d4519783320a0","time":"2022-09-05T00:18:57Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T00:18:52.977Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T00:18:52.977Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T00:18:53.589Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 193.188.52.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 41m11s]\n","level":"error","msg":"Scan job failed","scan_job_id":"da8f664590b7fe88f200c23a","time":"2022-09-05T00:18:58Z"}

{"exit_code":1,"image_ref":"core:8080/library/nginx@sha256:ead4adf366b0333e5f7e10f32b2b7814b3ea39807db3c3ac029d4404140da5b0","level":"error","msg":"Running trivy failed","std_out":"2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:06.162Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","time":"2022-09-05T07:09:06Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:06.162Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","level":"error","msg":"Scan failed","time":"2022-09-05T07:09:06Z"}
{"exit_code":1,"image_ref":"core:8080/library/nginx@sha256:42e0b052215b6e5890fe21fc250adf66a2a9d8cf4cd86713dd056b2fca6062d6","level":"error","msg":"Running trivy failed","std_out":"2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:07.929Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","time":"2022-09-05T07:09:07Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:07.929Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","level":"error","msg":"Scan failed","time":"2022-09-05T07:09:07Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:03.583Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:06.162Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","level":"error","msg":"Scan job failed","scan_job_id":"c14c2c4b7f469e90f9ff075c","time":"2022-09-05T07:09:09Z"}

{"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-05T07:09:06.210Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-05T07:09:07.929Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: DB file not found\n","level":"error","msg":"Scan job failed","scan_job_id":"a5d2541646ea7c4226c9afc2","time":"2022-09-05T07:09:09Z"}

**Comment by zeyad-mhmd** [comment]
*****Update******

I whitelisted ghcr.io without any luck, furthermore referring to log above specifically this one

`" 403 API rate limit exceeded for 193.188.52.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 41m11s]\n","level":"error","msg":"Scan failed","time":"2022-09-05T00:18:53Z"} "`

I read that's the way GitHub works to prevent API spam & **i should deploy some sort of token to bypass that issue** , but am not aware exactly how to implement that.

Wondering if that's the only issue in my log file & please correct me if am wrong
