### ISSUE TITLE
Random Error when running "docker login"

### ISSUE THREAD

**Issue by ayushkr04** [goharbor/harbor#17480]
Recently, we have started getting an error, when logging into docker. 
The error is random, when we try to login for the first time, it throws an error:

Error response from daemon: unauthorized: authentication required

And when we try to login again, with the same credentials, we are able to login successfully.

Versions:

harbor-portal: 1.8.0
harbor-core: 1.8.0
clair-photon: 2.0.8-v1.8.0

We have been running it successfully for close to 3 years, without any issues.
Recently, we have started running into this kind of error.

Please let me know if you need any additional information.

**Comment by stonezdj** [comment]
Harbor 1.8.0 is out of support now, please upgrade to latest Harbor version.

Current issue might be related to some clients try to log in with the expired password, harbor-core will lock the account login for each failure (15s), and during this interval, the login with the correct username/password will fail.

**Comment by ayushkr04** [comment]
Hey @stonezdj : Our harbor login is integrated with LDAP and this issue has been happening for every user.
Do you think this could be because of an old version of Harbor?

**Comment by stonezdj** [comment]
How about the login with admin user? is it something wrong with the LDAP connection?  we didn't found similar issue with old version of Harbor.

**Comment by ayushkr04** [comment]
@stonezdj : Only the admin login is successful the first time. For individual users, it fails the first time and successfully logs in the second time. 
Testing the connection with LDAP server, I get "500, Internal Sever Error" in the first try, and "successful" in the second try.

**Comment by stonezdj** [comment]
It seems to be an issue related to the LDAP connection.

**Comment by ayushkr04** [comment]
@stonezdj : Thank you for your helping out @stonezdj . It indeed turned out to be an issue with the connection with LDAP server.
