### ISSUE TITLE
reg/adapter/aliacr: support endpoint of aliacr for vpc and internal network.

### ISSUE THREAD

**Issue by szyhf** [goharbor/harbor#17488]
Support registry of aliacr for vpc network and internal network.

Endpoints like: 

+ `https://registry-vpc.%s.aliyuncs.com`
+ `https://registry-internal.%s.aliyuncs.com`

The vpc endpoint is  for vpc network node in ali cloud.

The internal endpoint is for classtic network node in ali cloud.

**Comment by chlins** [comment]
Not stale, pr reviewing.
