### ISSUE TITLE
Push image 503 when Harbor HTTP service behind HTTPS LB

### ISSUE THREAD

**Issue by aitchjoe** [goharbor/harbor#17481]
We run Harbor HTTP service behind HTTPS LB, but got error when we pushed image:

> Error: writing blob: uploading layer chunked: received unexpected HTTP status: 503 Service Unavailable

From [Using nginx or Load Balancing](https://goharbor.io/docs/2.6.0/install-config/troubleshoot-installation/#using-nginx-or-load-balancing):

> If Harbor is running behind an nginx proxy or elastic load balancing, open the file common/config/nginx/nginx.conf and search for the following line.
>
> `proxy_set_header X-Forwarded-Proto $scheme;`
>
> If the proxy already has similar settings, remove it from the sections location /, location /v2/ and location /service/ and redeploy Harbor.

Our default v2.6.0 config is `proxy_set_header X-Forwarded-Proto $x_forwarded_proto;`, we have removed (and `docker restart nginx`) but it is still not working. But after we changed to `proxy_set_header X-Forwarded-Proto https;`, the error gone. We think what to change also depend on LB config, so this is not for each case.

But now our problem is after we change `common/config/nginx/nginx.conf` manually, if we [Reconfigure Harbor](https://goharbor.io/docs/2.6.0/install-config/reconfigure-manage-lifecycle/) later, the `nginx.conf` will be overwritten to default, we have to change manually again, maybe we need a better solution?

**Comment by MinerYang** [comment]
As for this situation, you only need to restart. `sudo docker compose stop` and `sudo docker compose start`. 
You only need to do the prepare step when you  modified the harbor.yml configuration.

**Comment by aitchjoe** [comment]
> As for this situation, you only need to restart. `sudo docker compose stop` and `sudo docker compose start`. You only need to do the prepare step when you modified the harbor.yml configuration.

No, it is not ok:

1. change some config files manually, for example `common/config/nginx/nginx.conf`.
2. if we change other config in `harbor.yml` so we need to run `./prepare`.
3. check `common/config/nginx/nginx.conf` again, the changes by step 1 lost.
