### ISSUE TITLE
how to configure harbor ldap client to use tls1.2

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor#17484]
Our ldap server now supports tls1.2 only and that breaks our harbor's ldap authentication.  

How can we configure harbor to support tls1.2 when connectiing with ldap server?

We are running harbor 2.0.2.

**Comment by stonezdj** [comment]
You need to check if the current LDAP server's certificate is a trusted certificate or self signed certificate, if it is a self signed certificate, you need to add the root ca to the harbor-core's container trusted cert store.

If you install Harbor with docker-compose.
Copy the ca certificate to common/config/shared/trust-certificates directory and restart Harbor

If install Harbor with k8s, then create a secret for this ca certificate and set the secret name to the value caBundleSecretName in values.yaml
