### ISSUE TITLE
Can not login after first install when using 2.6.0

### ISSUE THREAD

**Issue by gsmlg** [goharbor/harbor#17495]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Login after fitst install.

**Steps to reproduce the problem:**
Download https://github.com/goharbor/harbor/releases/download/v2.6.0/harbor-online-installer-v2.6.0.tgz
untar and run
./prepare
./install.sh

Go to web page and login, Always get this error:

{"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.6.0]
- docker engine version: [20.10.17]
- docker-compose version: [1.25.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MinerYang** [comment]
It is a problem related to your browser

**Comment by QiuToo** [comment]
没看到您修改配置文件参数的步骤，同时也需要在主机上添加内核参数net.ipv4.ip_forward = 1，具体可以参考我的公众号文章：https://mp.weixin.qq.com/s/Wj_yutMibElf9Eqo5EzFQA，希望对你有所帮助。
