### ISSUE TITLE
Get Api ContextPath dynamically

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17493]
What can we help you?

Can we provide a logic that can uniformly modify the `harbor-portal` request address path, similar to the `ContextPath` of the backend.

We have a user scenario, we have multiple HARBOR instances, I hope to access it through a Harbor-Port front end. At present, we cannot dynamically modify the front-end request back-end address.

The logic I want to achieve is：
(1) `Harbor-Portal` first interface to get Contexntpath first, call an interface configured on` nginx`, such as `/contextPath`, it determines what the returned` contextPath` is determined according to the request parameter.
(2) `Harbor-Portal` after the request's back-end interface is to use` contexntpath` as `API PATH` prefix

We can use the logic of `/` as `contextPath` by default.

![new_arch](https://user-images.githubusercontent.com/15009201/188114688-c53c3a57-45a8-47ae-8a71-6b10b68cc69f.png)

`nginx.conf` configuration is similar：
```conf
server {
  port 80
  location /contexntpath {
       var param string
        if param == 1 {
            return 200 "/harborA";
       }
       if param == 2 {
            return 200 "/harborB";
       }

      return 404
}

  location /harborA {
      proxy_pass http://127.0.0.1:8080/
  }

  location /harborB {
      proxy_pass http://127.0.0.1:8081/
  }
}
```

**Comment by MinerYang** [comment]
You may build up your customized Harbor but we do not plan to support this officially.
