### ISSUE TITLE
Trivy scanner discrepancy in CVE number between two different Harbor instances

### ISSUE THREAD

**Issue by daliaezt** [goharbor/harbor#17497]
Hi team,
We are facing discrepancy issue regarding scanning result of exact same image on different two Harbor instances.
Replication rule has been applied, image replicated and scanned by Trivy, but on replica trivy detected more CVEs for same image.

we have checked trivy db file on both Harbor instances and it is the latest

Harbor version: 2.3.0
Trivy version : 0.17.2

**Comment by zyyw** [comment]
Please make sure the two trivy versions being used in the two harbor instances are the same. And the trivy configurations in the two harbor instance are the same:
* https://github.com/goharbor/harbor/blob/v2.3.0/make/harbor.yml.tmpl#L71

If this issue still persists, try to open a issue in trivy to report this:
* https://github.com/aquasecurity/trivy/issues

**Comment by daliaezt** [comment]
@zyyw yes Trivy configs are the same, we are using Trivy bundled with Harbor so it is same config, same version on both Harbor instances.

are you aware of any bugs that could be causing this issue and can be fixed by upgrade ?

**Comment by zyyw** [comment]
please also make sure the trivy db are updated at the same time:
* /data/trivy-adapter/trivy/db/metadata.json

**Comment by daliaezt** [comment]
It is the same, however trivy still detects different vulnerabilities. 
can you provide us the URLs being used by Trivy to download CVEs data ?

**On Harbor Hub** 
cat metadata.json
{"Version":1,"Type":1,"NextUpdate":"2022-09-06T12:53:31.220307537Z","UpdatedAt":"2022-09-06T06:53:31.220307737Z","DownloadedAt":"2022-09-06T07:16:13.739281576Z"}

![image](https://user-images.githubusercontent.com/8627955/188604690-60411168-d822-4aa9-b12f-451b6d372b1b.png)


**on replica**
cat metadata.json
{"Version":1,"Type":1,"NextUpdate":"2022-09-06T12:53:31.220307537Z","UpdatedAt":"2022-09-06T06:53:31.220307737Z","DownloadedAt":"2022-09-06T07:39:14.276367655Z"}

![image](https://user-images.githubusercontent.com/8627955/188605500-a06e5271-7970-4248-a6bb-1796c37f047c.png)

**Comment by sizowie** [comment]
@daliaezt what kind of vulnerabilities are detected more than on the hub? For example, trivy looks up dynamically on search.maven.org for Java artefacts (EAR/JAR/WAR,...). Does both systems have internet access?

**Comment by daliaezt** [comment]
@sizowie 
Thanks for your feedback.

no, one of Harbor instance doesn't have internet access.

I have whitelisted URL maven.org, is there any other websites used by Trivy to update it's data ?

**Comment by zyyw** [comment]
@daliaezt as mentioned in Harbor 2.5.4:
* https://github.com/goharbor/harbor/blob/v2.5.4/make/harbor.yml.tmpl#L81-L84
