### ISSUE TITLE
high cpu load when trivy is scanning

### ISSUE THREAD

**Issue by badsmoke** [goharbor/harbor#17505]
Hello,

I have enabled the trivy scanner, but as soon as I scan images, harbor becomes unusable CPU usage at 100%.

processes: 
postgres: porstgres registry 172.19.0.4 SELECT
postgres: porstgres registry 172.19.0.4 idle
postgres: parallel worker for PID ....

even minutes after the actual scan is already done.
it is currently installed harbor 2.6.0, but it also happens in the older versions.
loading the repository will also be extremely slow (Web UI) if there are scanned images in there

to the specs

VM
8 cores
4 gb RAM
SSD

trivy version (external) internal directly from harbor but is the same problem
```
Scanner:
Name:Trivy
Producer:Aqua Security
Version:0.29.2
Capabilities
Requires Mime Types:[application/vnd.oci.image.manifest.v1+json , application/vnd.docker.distribution.manifest.v2+json]
Creates Mime Types:[application/vnd.security.vulnerability.report; version=1.1]
Properties
env.SCANNER_TRIVY_DEBUG_MODE:true
env.SCANNER_TRIVY_IGNORE_UNFIXED:false
env.SCANNER_TRIVY_INSECURE:false
env.SCANNER_TRIVY_OFFLINE_SCAN:false
env.SCANNER_TRIVY_SEVERITY:UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
env.SCANNER_TRIVY_SKIP_UPDATE:false
env.SCANNER_TRIVY_TIMEOUT:5m0s
env.SCANNER_TRIVY_VULN_TYPE:os,library
harbor.scanner-adapter/scanner-type:os-package-vulnerability
harbor.scanner-adapter/vulnerability-database-next-update-at:9/6/22, 2:30 PM
harbor.scanner-adapter/vulnerability-database-updated-at:9/6/22, 8:30 AM
org.label-schema.build-date:2022-06-24T08:22:06Z
org.label-schema.vcs:https://github.com/aquasecurity/harbor-scanner-trivy
org.label-schema.vcs-ref:ff073cd57730f9258ec9fb6a72852f61a598f6e4
org.label-schema.version:0.30.0
```

I hope you can help me

**Comment by chlins** [comment]
Could you see the high CPU usage for which component(core/database/trivy)?

**Comment by badsmoke** [comment]
as I have written above. Postgres

very specifically these three types of processes:

postgres: porstgres registry 172.19.0.4 SELECT
postgres: porstgres registry 172.19.0.4 idle
postgres: parallel worker for PID ....

**Comment by chlins** [comment]
> as I have written above. Postgres
> 
> very specifically these three types of processes:
> 
> postgres: porstgres registry 172.19.0.4 SELECT postgres: porstgres registry 172.19.0.4 idle postgres: parallel worker for PID ....

Cannot figure out any clues from this, maybe you could use some 3-rd postgres monitor tool to crap out the slow SQL.
