### ISSUE TITLE
Design and implement the UI of jobservice dashboard

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#17518]

**Comment by AllForNothing** [comment]
@aarushisoni You can read the proposal first https://github.com/stonezdj/community/blob/add_jobservice_monitoring/proposals/new/jobservice_monitoring.md

The normal process:
Proposal   =>  UI design => back-end(APIs) implementing =>UI code development => integrate UI with back-end APIs => testing


Usually, implementing such a requirement requires a lot of team discussions and internal team resources. If you want to contribute, you can start with those requirements that can be done individually
