### ISSUE TITLE
ListRepositories API slowed down considerably after upgrade to v2.5.3 from v2.3.3

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#17511]
**Expected behavior and actual behavior:**

We expected that API methods performance would remain at same or comparable level, however we found that `ListRepositories` has become considerably slower.

p50 increased from ~60ms to **~850ms**
p90 increased from ~160ms to **~5 seconds**
p99 increased from ~300ms to **5-6 seconds**

we have 947 repositories and 65454 tags

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/61992380/188989857-51f4a5d5-222b-49aa-91c3-31db7df074d8.png">

**Steps to reproduce the problem:**

The only thing we changed was the Harbor software version from v2.3.3 to v2.5.3, nothing else has changed.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.5.3
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

I can provide additional information/context as required.

**Comment by chlins** [comment]
Could you provide the `ListRepositories` API details includes query parameters?

**Comment by dkulchinsky** [comment]
> Could you provide the `ListRepositories` API details includes query parameters?

Hey @chlins 👋🏼 

the query param is `/projects/<project name>/repositories`

**Comment by dkulchinsky** [comment]
Hey @chlins any thoughts on this? is this an expected degradation between 2.3.3 & 2.5.3 for this API?

**Comment by chlins** [comment]
Hi, @dkulchinsky, from harbor previous performance report(https://github.com/goharbor/perf/wiki) the result shows there is no degradation for this API between 2.3.x & 2.5.x, so could you check more in your environment? such as CPU usage and query the slow SQL from the database.

**Comment by dkulchinsky** [comment]
> Hi, @dkulchinsky, from harbor previous performance report(https://github.com/goharbor/perf/wiki) the result shows there is no degradation for this API between 2.3.x & 2.5.x

Looking at this, it's not representative of our environment,   we have less unique repositories and more artifacts per repository.

in our test environment with identical infra setup to prod, but much less artifacts we don't notice this degradation there.

> so could you check more in your environment? such as CPU usage and query the slow SQL from the database.

Our environment has not changed, we just upgraded from 2.3.3 to 2.5.3

when we run the API query continuously, we see a slight increase in core and DB cpu usage, but IO latency is low, however the DB is doing a lot more IO operations compared to 2.3.3, so perhaps something changed in the DB schema or Query?

I can test things further but can you tell me which queries to test? what do you want me to look for?

**Comment by chlins** [comment]
I think you could open the postgres monitor if you have or enable the pg statements(FYI: https://www.postgresql.org/docs/current/pgstatstatements.html), run the list repositories continuously, and fetch the slowest query.

**Comment by chlins** [comment]
BTW, do you have any plan to upgrade the harbor to 2.6.x?

**Comment by dkulchinsky** [comment]
> I think you could open the postgres monitor if you have or enable the pg statements(FYI: [postgresql.org/docs/current/pgstatstatements.html](https://www.postgresql.org/docs/current/pgstatstatements.html)), then run the list repositories continuously, and fetch the slowest query.

Thanks for you reply @chlins, but looks like we're on our own here.

I understand there's no clear answer for this issue we're seeing, but this degradation was clearly a result of the version change, I will try to analyze the query perfromance on our end, but as I'm not intimate with the implementation internals it would be very difficult for us to reverse engineer things to figure out why this is happening.

> BTW, do you have any plan to upgrade the harbor to 2.6.x?

We've started looking into 2.6.0, but currently there's a known bug so we at least need to wait until 2.6.1

we also have a fairly comprehensive process to validate new versions for functionality & breaking changes (especially when it's a minor bump), so this may take us some time to get to >=2.6.0

Do you think this issue could be mitigated/resolved with the new Cache layer that was introduced in 2.6?

**Comment by chlins** [comment]
@dkulchinsky Hi, I think the issue may occur when the project with big number of repositories and artifacts, this API performance downgrade may be brought by some code changes for artifact Count and List method in v2.5, but we have changed this part logic in 2.6, so this issue should be resolved when you upgrade to 2.6.x.

**Comment by dkulchinsky** [comment]
> @dkulchinsky Hi, I think the issue may occur when the project with big number of repositories and artifacts, this API performance downgrade may be brought by some code changes for artifact Count and List method in v2.5, but we have changed this part logic in 2.6, so this issue should be resolved when you upgrade to 2.6.x.

@chlins thanks for the information 👍🏼 

I'll start working internally on getting ready for upgrading to 2.6, is there any indication on when 2.6.1 might be released?

**Comment by dkulchinsky** [comment]
@chlins can confirm issues is resolved once we upgraded our instance to v2.6.1, closing as fixed
