### ISSUE TITLE
Harbor Helm CLI push docs use the wrong command

### ISSUE THREAD

**Issue by Osso-Robin** [goharbor/harbor#17528]
**Expected behavior and actual behavior:**
The documentation should describe the command to push using the `helm cm-push` command as it tells you to install it in the first step.
It instead uses `helm push --username xxx ---password xxx`. The username and password parameters do not exist for the `helm push` command  (at least as of version 3.9.4 I am using).

Example:
```
helm push --ca-file=ca.crt --username=admin --password=passw0rd chart_repo/hello-helm-0.1.0.tgz myrepo
Error: unknown flag: --username
```
The correct  commands involve first adding the repo with a username and password as described in "Add Harbor to the Repository List", then pushing using helm Chart Museum push plugin:
 ```
helm repo add --username="robot\$test+test" --password="somepassword" testcharthelm <harbor URL>
cm-push testchart-0.1.0.tgz testchart
```
It also doesn't need the ca.crt file anymore from what I tested.
I think this could also the solution for #17402 

**Steps to reproduce the problem:**
Follow "Push Charts to the Repository Server with the CLI" in the docs
Run the "helm push" command as described

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0
- Helm version: v3.9.4

**Comment by zyyw** [comment]
We may need to update the doc: 
* https://goharbor.io/docs/2.0.0/working-with-projects/working-with-images/managing-helm-charts/

change 
```
helm push --ca-file=ca.crt --username=admin --password=passw0rd chart_repo/hello-helm-0.1.0.tgz myrepo
```
to 
```
helm cm-push --ca-file=ca.crt --username=admin --password=passw0rd chart_repo/hello-helm-0.1.0.tgz myrepo
```
This has been updated in 2.6.0 doc:
* https://goharbor.io/docs/2.6.0/working-with-projects/working-with-images/managing-helm-charts/

please refer to the latest doc.
