### ISSUE TITLE
Skip Audit Log Database can be enabled without enabling Audit Log Forward

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17524]
**Expected behavior and actual behavior:**
Expected: Skip Audit Log Database cannot be enabled without Audit Log Forward
Actual: Skip Audit Log Database can be enabled without enabling Audit Log Forward

**Steps to reproduce the problem:**
1. Enable Audit Log Forward and Skip Audit Log Database
2. Call the API to modify the Audit Log Forward to empty

**Versions:**
- harbor version: v2.6.0

**Comment by aarushisoni** [comment]
I would like to work on this issue . Is this issue still open ? Kindly let me know the process.

**Comment by stonezdj** [comment]
It seems that we have the check on the disable log audit log update, and forget the check on the forward endpoint update  :-(
