### ISSUE TITLE
LDAP groups cannot be added as project members if 10 or more other groups extend their name

### ISSUE THREAD

**Issue by oliverlockwood** [goharbor/harbor#17535]
There are lots of LDAP groups in our organisation (which is, I think, not an uncommon situation).

As you can see from the following screenshot, there is a group named "Flex":
<img width="933" alt="Screenshot 2022-09-09 at 09 33 31" src="https://user-images.githubusercontent.com/6017680/189487765-652abe90-da71-46e0-b606-7ec66fab4fa6.png">

I would like to give permissions to this user, for the "Flex" project in Harbor.
However, when I type in "Flex", 10 other groups (containing the word "Flex" in their name) are shown.
<img width="1624" alt="Screenshot 2022-09-09 at 09 33 03" src="https://user-images.githubusercontent.com/6017680/189487788-3c41cbcc-115c-49d2-8569-47cd38a8185b.png">
 
As a result, I cannot add the group I want to as a member.

### Expected behavior and actual behavior:

Expected behaviour: If there are a large number of matches for a given group name, then:
- ideally the list should be scrollable;
- at very least, it should be possible to choose the group in some way - either by pressing "Enter" after typing its full name correctly; and/or by changing the drop-down generation logic such that an identical match is given first!

### Actual behaviour:

It is impossible to add some groups as members, in the circumstances described.
At a guess, probably this applies to users too, but I suspect it's less likely to occur.

### Steps to reproduce the problem:

1. Set up 11 or more LDAP groups, with the full name of one of the groups being the prefix or otherwise part of all the other group names.2. 
2. Try to add that group as a member to a Harbor project.

### Versions:

Please specify the versions of following systems.

- harbor version: [v2.7.0-006f495c]

**Comment by stonezdj** [comment]
The REST API should be sorted by the most matched result
