### ISSUE TITLE
Error response from daemon: unknown: artifact stencilapi:4.3.0.1 not found

### ISSUE THREAD

**Issue by wei-hsin-story** [goharbor/harbor#17544]
upgraded from v2.2.1 to v2.6.0 .

I found some conditions when pull partial image occurred "Error response from daemon: unknown: artifact stencilapi:4.3.0.1 not found"
But from UI , it exactly existed the image.

Then I deleted the image stencilapi  and re-push ,
I feel confused from UI.
![image](https://user-images.githubusercontent.com/111567876/190084677-77380838-0671-425d-aa53-ab34aeed859a.png)
![image](https://user-images.githubusercontent.com/111567876/190117542-7f587b99-f607-4142-9ea6-aa6b76b174cc.png)

It have two the same image repository  
Now it is work for me.
But how to remove redundant repositories ? 
I have no idea to do , because delete it from UI seems to  not work.

Is there more methods for correct operation ?

**Comment by tm-chang** [comment]
Hello, We upgrade harbor from 2.2. We also encountered the similar issue. We found different from Harbor UI to API request.
For example: 
Use API:
https://xxx.xxx.com/api/v2.0/projects/<project>/repositories/<repo name>/artifacts/4.3.0.12/tags?page=1&page_size=10&with_signature=false&with_immutable_status=false
The result:
{
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "<project>/<repo_name>:4.3.0.12 not found"
    }
  ]
}

UI:
<img width="1131" alt="截圖 2022-09-19 下午4 28 02" src="https://user-images.githubusercontent.com/14288854/190978739-39f2544d-b768-4762-9b27-64a72aa0a38f.png">

Pls help find root cause.
Thanks,
TM

**Comment by willy2653** [comment]
Today we also had the same issues.
When upgrade to latest version , we found partial images CAN NOT pull.
Total image repository 2047 , about  60 counts occurred "Not Found" 

any solutions or else advices for me?
Thanks!

**Comment by chlins** [comment]
> Hello, We upgrade harbor from 2.2. We also encountered the similar issue. We found different from Harbor UI to API request. For example: Use API: https://xxx.xxx.com/api/v2.0/projects//repositories//artifacts/4.3.0.12/tags?page=1&page_size=10&with_signature=false&with_immutable_status=false The result: { "errors": [ { "code": "NOT_FOUND", "message": "/<repo_name>:4.3.0.12 not found" } ] }
> 
> UI: <img alt="截圖 2022-09-19 下午4 28 02" width="1131" src="https://user-images.githubusercontent.com/14288854/190978739-39f2544d-b768-4762-9b27-64a72aa0a38f.png">
> 
> Pls help find root cause. Thanks, TM

@tm-chang It seems your API path is not correct, please refer to harbor swagger docs.

**Comment by chlins** [comment]
@wei-hsin-story @willy2653 Please check the artifact table to look for the missing artifact.

**Comment by stonezdj** [comment]
You could try this workaround:
1. Expose the database port
2. Check the duplicate repository name
```
// change the localhost to the hostname of your database host, and also change the username/password if required
docker run --rm firstfloor/before_reindex:latest --dburl=postgres://postgres:root123@localhost:5432/registry --command=list

```
3. Fix the duplicated repository name
```
// change the localhost to the hostname of your database host,and also change the username/password if required
docker run --rm firstfloor/before_reindex:latest --dburl=postgres://postgres:root123@localhost:5432/registry --command=fix
```

**Comment by wei-hsin-story** [comment]
> @wei-hsin-story @willy2653 Please check the artifact table to look for the missing artifacts.
Hi @chlins 
some imags were impacted  can't pull by Tag Name.
It's very tricky.
![ArtifactQuery](https://user-images.githubusercontent.com/111567876/192251518-6e886f2b-6db5-4a2a-852f-a1d04511f47e.jpg)

If using the sha256 to pull, it's actually work !

**Comment by wei-hsin-story** [comment]
@stonezdj  
I will try the method  to remove duplicate repository name.
thanks for your advice and response !

**Comment by wy65701436** [comment]
dup with: https://github.com/goharbor/harbor/issues/15620

**Comment by stonezdj** [comment]
@wei-hsin-story  Does it work?

**Comment by wei-hsin-story** [comment]
@stonezdj  
sorry for later.
I prepare the new environment to validate.

**Comment by wy65701436** [comment]
@stonezdj we still need to investigate why the index on repository name is corrupted.

**Comment by thechristschn** [comment]
I currently have the same problem after updating from 2.1.1 to 2.6.2 with 10 of 1272 repositories.

@stonezdj I would really like to try your proposed fix. But is the source of `firstfloor/before_reindex:latest` public? I would like to know what the image does, before I execute it in our environment.

**Comment by stonezdj** [comment]
The source of firstfloor/before_reindex:latest: https://github.com/stonezdj/before_reindex

**Comment by stonezdj** [comment]
Because this issue is not easy to reproduce in our env, and we have no clear conclusion for it, handle it case by case.

**Comment by wy65701436** [comment]
Hey @stonezdj, what do you think about closing this issue and using the workaround mentioned in https://github.com/goharbor/harbor/issues/17544#issuecomment-1257385150? Also, I didn't see any reports of this issue in v2.8.

**Comment by stonezdj** [comment]
The issue might related to the glibc2.28 change. the glibc 2.28 changed some character sort order esp -_$ with a-z A-Z
see 
https://wiki.postgresql.org/wiki/Locale_data_changes
https://postgresql.verite.pro/blog/2018/08/27/glibc-upgrade.html

It caused the database index corruption.

Harbor-db v2.2.x --> glibc 2.26
Harbor-db v2.3.0 --> glibc 2.30

The only way to fix is remove the duplicate item and reindex the table.
