### ISSUE TITLE
support of docker compose v2+

### ISSUE THREAD

**Issue by EHEX-schildt** [goharbor/harbor#17540]
Hi
i am a bit confused about the software requirements for Harbor.

https://goharbor.io/docs/2.6.0/install-config/installation-prereqs/
Docker Compose | Version 1.18.0 or higher
with a link to https://docs.docker.com/compose/install/
a gude to install Compose v2+

`root@harbor # docker compose version`
`Docker Compose version v2.10.2`

The installer stops:
Need to install docker-compose(1.18.0+) by yourself first and run this script again.

It looks like harbor/installer/harbor/common.sh only checks for Docker Compose < 2.0.0

Is installer support for Docker Compose v2+ planed?

**Comment by chlins** [comment]
I think harbor has supported docker compose v2. cc @MinerYang

**Comment by MinerYang** [comment]
Which version you are using? We have already support docker compose v2 in harbor v2.6.0. And sorry for the confusion we will update the official documentation soon

**Comment by EHEX-schildt** [comment]
Ok i got it. `docker-compose` vs `docker compose`

When i use Docker Compose Standalone it works.

I just installed the docker-compose-plugin before.

**Comment by MinerYang** [comment]
We have updated the official documentation for support of docker compose v2+, please check out.
https://goharbor.io/docs/2.6.0/install-config/installation-prereqs/

**Comment by EHEX-schildt** [comment]
Ok but now would assume that installing just the docker-compose-plugin like i dit before is ok.

The installer is not compatible with docker-compose-plugin and says i need to install `docker-compose v1.18.0+`.

The doc's should say docker compose v2 (Standalone only)

**Comment by MinerYang** [comment]
`docker-compose (v1.18.0+) or docker compose v2 (docker-compose-plugin)` has been update in the doc
https://github.com/goharbor/website/blob/main/docs/install-config/installation-prereqs.md#software
