### ISSUE TITLE
Cannot swap s3 bucket imageChartStorage

### ISSUE THREAD

**Issue by jcarapet** [goharbor/harbor#17541]
Harbor Version: 2.6.0
harbor-helm: 1.10.0
kubernetes version: 1.22.7

I am attempting to migrate from one s3 bucket to another. I have replicated the data from source s3 bucket using s3 cp, 
Running upgrade on the configuration should be to me as simple as swapping config values for the endpoint. 
    s3:
      bucket: harbor_old
      region: Standard
      accesskey: <my_access_key>
      regionendpoint: <my_region_endpoint>
      secretkey: <my_secret_key>

    s3:
      bucket: harbor_new
      region: Standard
      accesskey: <my_access_key>
      regionendpoint: <https://my_region_endpoint>
      secretkey: <my_secret_key>

After the migration I am able to login running `docker login <harbor_endpoint>`, but push/pull of images and charts is not functional. No obvious indicators in the logs from chartmuseum or registry. 

Is migrating buckets even possible to do, or is there an error in my approach

**Comment by chlins** [comment]
Could you provide the error message when pull/push the images?

**Comment by jcarapet** [comment]
Unfortunately I was not getting error messages visible that I could see in registry container. 

We have determined it is a firewall issue on the expected port being blocked
