### ISSUE TITLE
Harbor UI自定义样式

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#17543]
我从https://goharbor.io/docs/2.6.0/build-customize-contribute/customize-look-feel/了解到可以自定义Harbor前端样式，这是一个很有趣的功能，遗憾的是我无法通过源码编译的方式来使用他，如果可以在UI界面设置前端页面，那将会非常有趣。

**Comment by AllForNothing** [comment]
You can try to clone the code locally, and then configure the custom style according to the documentation, go to the `src/portal `folder, and build the static files of the UI according to READ.ME. Finally, `scp` these static files to the `/usr/share/nginx/html` folder under the portal container

**Comment by AllForNothing** [comment]
If no more questions, I'm closing it.
