### ISSUE TITLE
trivy - init error: DB error: failed to download vulnerability DB

### ISSUE THREAD

**Issue by rrgadeev** [goharbor/harbor#17555]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
scan completed successfully
scanning fails with an error

**Steps to reproduce the problem:**
starting a docker images scan

**Versions:**

- harbor version: [x.x.x] Version v2.5.4
- docker engine version: [y.y.y] 20.10.1
- docker-compose version: [z.z.z] 1.25.1

**Additional context:**
proxy access is used
logs UI:
`2022-09-16T07:47:08Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2022-09-16T07:44:23.117Z	[34mINFO[0m	Need to update DB
2022-09-16T07:44:23.117Z	[34mINFO[0m	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-09-16T07:44:23.117Z	[34mINFO[0m	Downloading DB...
2022-09-16T07:47:04.855Z	[31mFATAL[0m	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get "https://ghcr.io/v2/": dial tcp 140.82.121.33:443: connect: connection timed out
: general response handler: unexpected status code: 500, expected: 200`
/var/log/harbor/trivy-adapter.log
`Sep 16 10:47:08 30.30.27.1 trivy-adapter[766]: {"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-16T07:44:23.117Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-16T07:44:23.117Z\t\u001b[34mINFO\u001b[0m\tDB Repository: ghcr.io/aquasecurity/trivy-db\n2022-09-16T07:44:23.117Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-16T07:47:04.855Z\t\u001b[31mFATAL\u001b[0m\tinit error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get \"https://ghcr.io/v2/\": dial tcp 140.82.121.33:443: connect: connection timed out\n","level":"error","msg":"Scan job failed","scan_job_id":"4ebf06624db129e41bc7dcff","time":"2022-09-16T07:47:08Z"}`

if docker exec -it {trivy-adapter} bash
`scanner [ / ]$ curl https://ghcr.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
scanner [ / ]$ curl https://140.82.121.33 -k
<!DOCTYPE html><title>Not Found</title>
<body>The requested URL is was not found.</body>
</html>

...

    </div>
  </body>
</html>

`
thus, access seems to be there, but nevertheless does not work

upd
there was an update recently
2.5.1 to 2.5.4

**Comment by zyyw** [comment]
@rrgadeev , please refer to this issue to see whether it helps or not:
* https://github.com/goharbor/harbor/issues/17061

**Comment by stonezdj** [comment]
The test result varies with different proxy settings, if the proxy server is https proxy, you should add `ghcr.io` to the whitelist of the proxy for passthrough.

**Comment by rrgadeev** [comment]
https://github.com/aquasecurity/trivy-db/issues/252

```
docker run -it --rm -e HTTPS_PROXY=10.0.24.75:3128 -v $(pwd):/tmp -w /tmp -u 1001  harbor.local/dockerhub/bitnami/oras:latest pull ghcr.io/aquasecurity/trivy-db:2
Downloading 2833a05b2aff db.tar.gz
Downloaded  2833a05b2aff db.tar.gz
Pulled ghcr.io/aquasecurity/trivy-db:2
Digest: sha256:dee54808b596066fa114cbffa1cd07fccfd5c9a9c87d436ba86d7a341cd9ff92
```
harbor.yml
proxy:
  http_proxy: http://10.0.24.75:3128
  https_proxy: http://10.0.24.75:3128
  components:
    - core
    - jobservice
    - trivy


squid log
1664193313.685  75835 10.0.24.36 TCP_TUNNEL/200 6366 CONNECT docker.bintray.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664193327.590  90237 10.0.24.36 TCP_TUNNEL/200 4008 CONNECT ghcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664193329.247  90288 10.0.24.36 TCP_TUNNEL/200 5284 CONNECT k8s.gcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664193329.442  90095 10.0.24.36 TCP_TUNNEL/200 5327 CONNECT gcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664193402.134  13250 10.0.24.36 TCP_TUNNEL/200 5625 CONNECT ghcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664193402.134  12269 10.0.24.36 TCP_TUNNEL/200 35984445 CONNECT pkg-containers.githubusercontent.com:443 - FIRSTUP_PARENT/10.0.4.245 -


jobservice:
Sep 26 16:05:25 30.30.27.1 trivy-adapter[766]: {"error":"running trivy wrapper: running trivy: exit status 1: 2022-09-26T13:02:42.402Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-09-26T13:02:42.403Z\t\u001b[34mINFO\u001b[0m\tDB Repository: ghcr.io/aquasecurity/trivy-db\n2022-09-26T13:02:42.403Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-09-26T13:05:24.247Z\t\u001b[31mFATAL\u001b[0m\tinit error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get \"https://ghcr.io/v2/\": dial tcp 140.82.121.33:443: connect: connection timed out\n","level":"error","msg":"Scan job failed","scan_job_id":"85c8eab80c2834270a4c7679","time":"2022-09-26T13:05:25Z"}

squid log 
1664197438.593    413 10.0.24.36 TCP_TUNNEL/200 5030 CONNECT k8s.gcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197438.991     99 10.0.24.36 TCP_TUNNEL/200 5055 CONNECT gcr.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197439.472    378 10.0.24.36 TCP_TUNNEL/200 4279 CONNECT registry.deckhouse.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197439.859    386 10.0.24.36 TCP_TUNNEL/200 4930 CONNECT registry.deckhouse.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197440.011    152 10.0.24.36 TCP_TUNNEL/200 6858 CONNECT mcr.microsoft.com:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197440.173    158 10.0.24.36 TCP_TUNNEL/200 6858 CONNECT mcr.microsoft.com:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197440.679    505 10.0.24.36 TCP_TUNNEL/200 5796 CONNECT quay.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197441.368    689 10.0.24.36 TCP_TUNNEL/200 7059 CONNECT quay.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197442.672    618 10.0.24.36 TCP_TUNNEL/200 5992 CONNECT registry-1.docker.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197443.893    565 10.0.24.36 TCP_TUNNEL/200 5804 CONNECT registry-1.docker.io:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197447.054   5685 10.0.24.36 TCP_TUNNEL/200 10480 CONNECT hub.docker.com:443 - FIRSTUP_PARENT/10.0.4.245 -
1664197448.324   5651 10.0.24.36 TCP_TUNNEL/200 10020 CONNECT auth.docker.io:443 - FIRSTUP_PARENT/10.0.4.245 -

**Comment by rrgadeev** [comment]
it helped me:
```
trivy:
  insecure: false
```
