### ISSUE TITLE
IDOR (Insecure Director Object Reference) vulnerabilities

### ISSUE THREAD

**Issue by sajithvasu** [goharbor/harbor#17573]
Recently this article came out for IDOR vulnerability in harbor - https://www.helpnetsecurity.com/2022/09/19/vulnerabilities-harbor-open-source-artifact-registry/
Kindly let us know which version is impacted with this.

**Comment by chlins** [comment]
You can refer to https://github.com/goharbor/harbor/security/advisories for more details.

**Comment by sajithvasu** [comment]
> You can refer to https://github.com/goharbor/harbor/security/advisories for more details.

I don't see anything similar in the advisories.
