### ISSUE TITLE
Disable Anonymous access setting in system settings not working at all (Urgent)

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#17574]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Disabling Anonymous User doesn't disable anonymous access and people who are not registered still can access images from public projects. 

**Steps to reproduce the problem:**
![image](https://user-images.githubusercontent.com/63449625/191072518-38f81344-389a-4d30-b11d-bf74fdcb4c98.png)
Click on disable anonymous access and try to pull an image from a public project. It will throw no auth error and will pull the image.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.2.0

**Comment by Entropy70** [comment]
Hi, is there any way we can make this option work by doing some changes in database?

**Comment by Entropy70** [comment]
@wy65701436 can you please have a look at this. Thanks a lot

**Comment by wy65701436** [comment]
hi @Entropy70 where did you get the harbor installer from? We never had that feature.

**Comment by Entropy70** [comment]
Hi @wy65701436 , yeah sorry my bad. This was a customization which I wasn't aware of. Thanks anyway
