### ISSUE TITLE
http 500 on writing to s3

### ISSUE THREAD

**Issue by thomasober** [goharbor/harbor#17582]
In rare cases we have the problem that an error occurs when writing a Dockerimage.
Harbor uses an s3 objectstore as storage location (NetApp Storage Grid).
We notice that Harbor uses HEAD requests for objects that are not present in our S3 objectstore. What is the motivation behind this behavior and how will normal operations be affected if these HEAD requests fails?  

-- Background --
In some special situations, our Objectstore sends error 500 when HEAD or GET requests have been sent to objects that do not exist. WRITE (on all other objects) and GET/HEAD (on existing objects) operations works normally - but Harbor seems no longer working as expected 

Here some log output:
`172.18.0.8 - - [22/Jul/2022:09:59:42 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
time="2022-07-22T09:59:46.049372074Z" level=info msg="authorized request" go.version=go1.17.7 http.request.contenttype="application/json" http.request.host=hub.<DOMAIN> http.request.id=47da3cb3-c28d-426f-a843-633039f63de0 http.request.method=POST http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/" http.request.useragent="go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a" vars.name="downtime/nginx" 
time="2022-07-22T09:59:46.172831759Z" level=info msg="response completed" go.version=go1.17.7 http.request.contenttype="application/json" http.request.host=hub.<DOMAIN> http.request.id=47da3cb3-c28d-426f-a843-633039f63de0 http.request.method=POST http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/" http.request.useragent="go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a" http.response.duration=128.150281ms http.response.status=202 http.response.written=0 
172.18.0.8 - - [22/Jul/2022:09:59:46 +0000] "POST /v2/downtime/nginx/blobs/uploads/ HTTP/1.1" 202 0 "" "go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a"
time="2022-07-22T09:59:46.188692765Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=925fb4de-0a92-4081-96eb-e41507988269 http.request.method=DELETE http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/6abfce3c-b3ad-4d80-841f-05bcd764c369?_state=anSjh4hqZJVRkqImNQVpjAAxZYxQzeUj0IHVXHZ-DXl7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI2YWJmY2UzYy1iM2FkLTRkODAtODQxZi0wNWJjZDc2NGMzNjkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDYuMDQ5NDg1MzhaIn0%3D" http.request.useragent="go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a" vars.name="downtime/nginx" vars.uuid=6abfce3c-b3ad-4d80-841f-05bcd764c369 
time="2022-07-22T09:59:46.575639187Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=925fb4de-0a92-4081-96eb-e41507988269 http.request.method=DELETE http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/6abfce3c-b3ad-4d80-841f-05bcd764c369?_state=anSjh4hqZJVRkqImNQVpjAAxZYxQzeUj0IHVXHZ-DXl7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI2YWJmY2UzYy1iM2FkLTRkODAtODQxZi0wNWJjZDc2NGMzNjkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDYuMDQ5NDg1MzhaIn0%3D" http.request.useragent="go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a" http.response.duration=393.2212ms http.response.status=204 http.response.written=0 
172.18.0.8 - - [22/Jul/2022:09:59:46 +0000] "DELETE /v2/downtime/nginx/blobs/uploads/6abfce3c-b3ad-4d80-841f-05bcd764c369?_state=anSjh4hqZJVRkqImNQVpjAAxZYxQzeUj0IHVXHZ-DXl7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI2YWJmY2UzYy1iM2FkLTRkODAtODQxZi0wNWJjZDc2NGMzNjkiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDYuMDQ5NDg1MzhaIn0%3D HTTP/1.1" 204 0 "" "go-containerregistry/v0.8.1-0.20220214202839-625fe7b4276a"
time="2022-07-22T09:59:49.250223035Z" level=info msg="authorized request" go.version=go1.17.7 http.request.contenttype="application/json" http.request.host=hub.<DOMAIN> http.request.id=97b7c852-9864-4ffb-a348-c9d4bef1aa00 http.request.method=POST http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/" http.request.useragent="kaniko/v1.8.1" vars.name="downtime/nginx" 
time="2022-07-22T09:59:49.256916336Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=14fb94bd-c523-45ff-a100-8e4d0b93e0c1 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:a71634c55d292856f6a48a5984ff4aa7e244f2e82083e1279aa5af8a7da5819f" http.request.useragent="kaniko/v1.8.1" vars.digest="sha256:a71634c55d292856f6a48a5984ff4aa7e244f2e82083e1279aa5af8a7da5819f" vars.name="downtime/nginx" 
time="2022-07-22T09:59:49.262933465Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=7953d2ba-6d79-4182-aa62-a027bc9f2b0c http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:5595887beb811004cfb48cd5bb3eb9a9602fb1fd47d93117b92ef97e22859c00" http.request.useragent="kaniko/v1.8.1" vars.digest="sha256:5595887beb811004cfb48cd5bb3eb9a9602fb1fd47d93117b92ef97e22859c00" vars.name="downtime/nginx" 
time="2022-07-22T09:59:49.270793275Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=40d3b0dd-b77f-4047-b23e-ba4c3cd203c8 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:264026bbe25598d28ce74f288ce0b4ef93dc4123bb793bf655780e0455453f4c" http.request.useragent="kaniko/v1.8.1" vars.digest="sha256:264026bbe25598d28ce74f288ce0b4ef93dc4123bb793bf655780e0455453f4c" vars.name="downtime/nginx" 
time="2022-07-22T09:59:49.288660467Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=383701a4-cf7f-4b73-8832-5d7f5eccecbd http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10" http.request.useragent="kaniko/v1.8.1" vars.digest="sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10" vars.name="downtime/nginx" 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "POST /v2/downtime/nginx/blobs/uploads/ HTTP/1.1" 202 0 "" "kaniko/v1.8.1"
time="2022-07-22T09:59:49.407281889Z" level=info msg="response completed" go.version=go1.17.7 http.request.contenttype="application/json" http.request.host=hub.<DOMAIN> http.request.id=97b7c852-9864-4ffb-a348-c9d4bef1aa00 http.request.method=POST http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/" http.request.useragent="kaniko/v1.8.1" http.response.duration=163.545756ms http.response.status=202 http.response.written=0 
time="2022-07-22T09:59:49.440905684Z" level=info msg="authorized request" go.version=go1.17.7 http.request.contenttype="application/octet-stream" http.request.host=hub.<DOMAIN> http.request.id=797c8da4-2cb8-4891-9124-9035226d893d http.request.method=PATCH http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=-jQ4_d9y9vc4fXkWgjORf5cXfaQDNQgzd6pJrOrTPYZ7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDkuMjUwMzQ2MDI4WiJ9" http.request.useragent="kaniko/v1.8.1" vars.name="downtime/nginx" vars.uuid=766c58da-ec72-4671-accf-396d31bf2c47 
time="2022-07-22T09:59:49.68634191Z" level=info msg="response completed" go.version=go1.17.7 http.request.contenttype="application/octet-stream" http.request.host=hub.<DOMAIN> http.request.id=797c8da4-2cb8-4891-9124-9035226d893d http.request.method=PATCH http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=-jQ4_d9y9vc4fXkWgjORf5cXfaQDNQgzd6pJrOrTPYZ7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDkuMjUwMzQ2MDI4WiJ9" http.request.useragent="kaniko/v1.8.1" http.response.duration=250.813566ms http.response.status=202 http.response.written=0 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "PATCH /v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=-jQ4_d9y9vc4fXkWgjORf5cXfaQDNQgzd6pJrOrTPYZ7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDkuMjUwMzQ2MDI4WiJ9 HTTP/1.1" 202 0 "" "kaniko/v1.8.1"
time="2022-07-22T09:59:49.719439593Z" level=info msg="authorized request" go.version=go1.17.7 http.request.contenttype="application/octet-stream" http.request.host=hub.<DOMAIN> http.request.id=f9e8bbdc-163a-480a-953e-be34a70294fb http.request.method=PUT http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=4hVLrr5ZWbHLOeUNMPCVvQ7Hj7MeII9QdL-qw2Y1hwh7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjc3MjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDlaIn0%3D&digest=sha256%3Ac4658ace30131c5f327246360330db6968aa3c12a2235547947fc67096f9d807" http.request.useragent="kaniko/v1.8.1" vars.name="downtime/nginx" vars.uuid=766c58da-ec72-4671-accf-396d31bf2c47 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "HEAD /v2/downtime/nginx/blobs/sha256:264026bbe25598d28ce74f288ce0b4ef93dc4123bb793bf655780e0455453f4c HTTP/1.1" 500 123 "" "kaniko/v1.8.1"
time="2022-07-22T09:59:49.765800506Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InternalError: We encountered an internal error. Please try again.
        status code: 500, request id: 1658483006528796, host id: 12046476" err.message="unknown error" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=40d3b0dd-b77f-4047-b23e-ba4c3cd203c8 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:264026bbe25598d28ce74f288ce0b4ef93dc4123bb793bf655780e0455453f4c" http.request.useragent="kaniko/v1.8.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=501.0181ms http.response.status=500 http.response.written=123 vars.digest="sha256:264026bbe25598d28ce74f288ce0b4ef93dc4123bb793bf655780e0455453f4c" vars.name="downtime/nginx" 
time="2022-07-22T09:59:49.784438363Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InternalError: We encountered an internal error. Please try again.
        status code: 500, request id: 1658483435751571, host id: 12239504" err.message="unknown error" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=14fb94bd-c523-45ff-a100-8e4d0b93e0c1 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:a71634c55d292856f6a48a5984ff4aa7e244f2e82083e1279aa5af8a7da5819f" http.request.useragent="kaniko/v1.8.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=532.471784ms http.response.status=500 http.response.written=123 vars.digest="sha256:a71634c55d292856f6a48a5984ff4aa7e244f2e82083e1279aa5af8a7da5819f" vars.name="downtime/nginx" 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "HEAD /v2/downtime/nginx/blobs/sha256:a71634c55d292856f6a48a5984ff4aa7e244f2e82083e1279aa5af8a7da5819f HTTP/1.1" 500 123 "" "kaniko/v1.8.1"
time="2022-07-22T09:59:49.815802431Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InternalError: We encountered an internal error. Please try again.
        status code: 500, request id: 1658477831540841, host id: 12624152" err.message="unknown error" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=7953d2ba-6d79-4182-aa62-a027bc9f2b0c http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:5595887beb811004cfb48cd5bb3eb9a9602fb1fd47d93117b92ef97e22859c00" http.request.useragent="kaniko/v1.8.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=557.75014ms http.response.status=500 http.response.written=123 vars.digest="sha256:5595887beb811004cfb48cd5bb3eb9a9602fb1fd47d93117b92ef97e22859c00" vars.name="downtime/nginx" 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "HEAD /v2/downtime/nginx/blobs/sha256:5595887beb811004cfb48cd5bb3eb9a9602fb1fd47d93117b92ef97e22859c00 HTTP/1.1" 500 123 "" "kaniko/v1.8.1"
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "HEAD /v2/downtime/nginx/blobs/sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10 HTTP/1.1" 500 123 "" "kaniko/v1.8.1"
time="2022-07-22T09:59:49.841694694Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InternalError: We encountered an internal error. Please try again.
        status code: 500, request id: 1658480471140401, host id: 12939633" err.message="unknown error" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=383701a4-cf7f-4b73-8832-5d7f5eccecbd http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10" http.request.useragent="kaniko/v1.8.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=557.426929ms http.response.status=500 http.response.written=123 vars.digest="sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10" vars.name="downtime/nginx" 
time="2022-07-22T09:59:50.621433075Z" level=info msg="response completed" go.version=go1.17.7 http.request.contenttype="application/octet-stream" http.request.host=hub.<DOMAIN> http.request.id=f9e8bbdc-163a-480a-953e-be34a70294fb http.request.method=PUT http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=4hVLrr5ZWbHLOeUNMPCVvQ7Hj7MeII9QdL-qw2Y1hwh7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjc3MjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDlaIn0%3D&digest=sha256%3Ac4658ace30131c5f327246360330db6968aa3c12a2235547947fc67096f9d807" http.request.useragent="kaniko/v1.8.1" http.response.duration=906.426667ms http.response.status=201 http.response.written=0 
172.18.0.8 - - [22/Jul/2022:09:59:49 +0000] "PUT /v2/downtime/nginx/blobs/uploads/766c58da-ec72-4671-accf-396d31bf2c47?_state=4hVLrr5ZWbHLOeUNMPCVvQ7Hj7MeII9QdL-qw2Y1hwh7Ik5hbWUiOiJkb3dudGltZS9uZ2lueCIsIlVVSUQiOiI3NjZjNThkYS1lYzcyLTQ2NzEtYWNjZi0zOTZkMzFiZjJjNDciLCJPZmZzZXQiOjc3MjAsIlN0YXJ0ZWRBdCI6IjIwMjItMDctMjJUMDk6NTk6NDlaIn0%3D&digest=sha256%3Ac4658ace30131c5f327246360330db6968aa3c12a2235547947fc67096f9d807 HTTP/1.1" 201 0 "" "kaniko/v1.8.1"
172.18.0.8 - - [22/Jul/2022:09:59:52 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
time="2022-07-22T09:59:54.808887199Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=fd20c9aa-2f4a-400b-8271-a075f896d7b1 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/miri/sap-checker/manifests/sha256:822548d0cea658abd3dcec0c8ea80f3fc6f074f426c89b54133b20f1c6a79968" http.request.useragent="docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.24.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" vars.name="miri/sap-checker" vars.reference="sha256:822548d0cea658abd3dcec0c8ea80f3fc6f074f426c89b54133b20f1c6a79968" 
172.18.0.8 - - [22/Jul/2022:09:59:54 +0000] "HEAD /v2/miri/sap-checker/manifests/sha256:822548d0cea658abd3dcec0c8ea80f3fc6f074f426c89b54133b20f1c6a79968 HTTP/1.1" 200 3474 "" "docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.24.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
time="2022-07-22T09:59:54.882404018Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=hub.<DOMAIN> http.request.id=fd20c9aa-2f4a-400b-8271-a075f896d7b1 http.request.method=HEAD http.request.remoteaddr=10.97.22.2 http.request.uri="/v2/miri/sap-checker/manifests/sha256:822548d0cea658abd3dcec0c8ea80f3fc6f074f426c89b54133b20f1c6a79968" http.request.useragent="docker/20.10.5 go/go1.13.15 git-commit/363e9a8 kernel/3.10.0-1160.24.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=81.769064ms http.response.status=200 http.response.written=3474 
127.0.0.1 - - [22/Jul/2022:09:59:58 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.82.0"`

**Comment by stonezdj** [comment]
The storage should always return 404 for HEAD request to a non exist blob, but it might varies for different type of storage impl.

You could try to disable the redirect option in harbor.yml 
```
storage_service:
  redirect:
    disabled: true
```
