### ISSUE TITLE
redirect_url is not working when OIDC is enabled

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#17594]
Harbor does has support for `redirect_url` to redirect the user to the page he planned to go before hitting the login page. 

However `redirect_url` is not working and the value is ignored.

- Redirect is not set
- If redirect is set it is ignored

**Comment by chlins** [comment]
Could you provide more details such as screenshot?

**Comment by Vad1mo** [comment]
The following video coverts the case (1).

[Kapture 2022-09-26 at 11.50.58.webm](https://user-images.githubusercontent.com/1492007/192248055-a470cb8c-092c-436e-afab-8113be1a9359.webm)

The use case (2) if you change `redirect_url=%2F` to something meaningful eg.`redirect_url=harbor/projects/2/repositories/` it is also not working.

**Comment by AllForNothing** [comment]
@Vad1mo Try encoding the uri like this: `redirect_url=%2Fharbor%2Fprojects%2F4%2Frepositories`, it should work

**Comment by Vad1mo** [comment]
@AllForNothing , I tried it with encoded URL, for readability reasons I pasted it in clear here.

**Comment by AllForNothing** [comment]
@Vad1mo I tested on a Harbor with OIDC enabled, and it works for DB users(Not supported for ODIC users, as the redirect URL is fixed as Harbor home page).  

The redirect_url  must start with an encoded slash, which is `%2F`

**Comment by AllForNothing** [comment]
As for the use case (1),  the redirect_url should not be `%2F`,  I will check on this. But if you manually set a right redirect_url, it should work as expected
