### ISSUE TITLE
Duplicate all project repositories into /library

### ISSUE THREAD

**Issue by MayhemBill** [goharbor/harbor#17597]
What can we help you?
I would like to be able to replicate all of the individual projects into the default library, mostly as an index of all the repositories in one place, but I can't seem to figure out how, is this kind of thing even possible?

**Comment by chlins** [comment]
I think you could create replication policy and replicate from self projects to library(which can set the dest namespace as `library`).

**Comment by MayhemBill** [comment]
the issue with this is that I need to set up an endpoint for a destination repository, which is a dropdown of repositories setup

**Comment by chlins** [comment]
You can create the registry with your harbor instance self before and setup the `pull-based` rule which choose the source as yourself.

**Comment by MayhemBill** [comment]
`[ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: crypto/aes: invalid key size 10"}]} `

getting this issue trying that

**Comment by chlins** [comment]
This solution can work well in my environment, never see the error as you mentioned, could you provide the screenshots of replication rule and execution result?

**Comment by MayhemBill** [comment]
I can't even make the rules, I get that error just trying to add the registry to itself

**Comment by chlins** [comment]
Could you share the screenshot of the registry add page?
