### ISSUE TITLE
Harbor V2.3.1, GC Failed !!  [/jobservice/job/impl/gc/garbage_collection.go:166]: failed to execute GC job at sweep phase, error: failed to delete manifest with v2 API: {project}/{repo}, sha256:xxx: retry timeout

### ISSUE THREAD

**Issue by yongbowei2021** [goharbor/harbor#17596]
What can we help you?

**Comment by yongbowei2021** [comment]
question:
1. how to skip this error? 
2. this manifest must to delete ?

**Comment by yongbowei2021** [comment]
https://github.com/goharbor/harbor/issues/15807,I think this issue can solve my problem.Since in v2.5, can skip delete failure.

**Comment by chlins** [comment]
Yes, you can upgrade to v2.5.
