### ISSUE TITLE
External syslog server

### ISSUE THREAD

**Issue by senk** [goharbor/harbor#176]
Harbor should support configuration of an external syslog server

**Comment by xiaods** [comment]
@senk what purpose on syslog?

**Comment by senk** [comment]
to use the central graylog or elk stack to collect the logs instead of the log collector container (access logs etc)

**Comment by bobbyjunzhang** [comment]
Thanks for the suggestion, @senk, we will look into it.

**Comment by reasonerjt** [comment]
@senk I understand your point, currently you can update the docker-compose.yml to send log messages to other syslog servers.

Are you asking a better approach to configure this?

**Comment by senk** [comment]
yeah some kind of configuration option

**Comment by reasonerjt** [comment]
In the deployment based on docker-compose, we won't provide such flexibility user can achieve that by manually update the docker-compose template file.
