### ISSUE TITLE
Webhooks blocking normal registry operation

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#17607]
Checking some old issues:
* https://github.com/goharbor/harbor/issues/16805
It says that webhooks are non blocking. But we have a different experience.

On 23/09 we updated our harbor production environment to v2.5.4 from v2.5.1 due to the disclosed vulnerabilities
![image](https://user-images.githubusercontent.com/5084445/192534054-12e79892-66d1-4656-b3e8-820d3026c3e7.png)
![image](https://user-images.githubusercontent.com/5084445/192528629-43c19b37-2e1a-42fd-bac8-3eadd05b80a9.png)

Notice the big ramp up of pending tasks that started at the time where we do whole registry security scans and stable helm charts sync, happening around 1 and 3 AM

Today the service crashed, when finaly the number of pending task was decreasing (around 12h30)
![image](https://user-images.githubusercontent.com/5084445/192529642-fe979224-a014-4012-8c04-8533ecf20e75.png)

At the same time the image scans queue ended the webhook seems to start to pick up. Also there is a spike on GetInternalConfig requests probably related the the start of the webhook jobs? Notice the 'task concurrency' WEBHOOK count
At this time, the core service seemed to stop accepting normal push/pull requests from users making the service unavailable.
Finaly, recreating the core pods reseted the webhooks running making the service usable again

Clearly something happens with the webhooks handling that starves all other processes (even if they are asyncronous)...
Maybe blocking all the workers?
Shouldn't this processes be completly separated so that the webhook/image scans do not block normal registry operation (different container even?).

Cheking the logs for the core pods at the time of this incident [12h,13h] dosent produce much information. I can see some replication handler on projects that do not exist? Most part of the logs are filled with:
![image](https://user-images.githubusercontent.com/5084445/192545195-2e183429-69ba-474e-95b5-84040c71ee7d.png)

We also noticed this, some time ago where we had a similar issue and some taks (and executions) where in the pending state since (weeks) ago. This task don't seem to resolve into error/success state and might be one of the causes of this problem?
PM me for more debug info, if i can provide. Not sure where the webhooks come from: https://pastebin.com/SnevNP83

**Comment by dioguerra** [comment]
@stonezdj @wy65701436 Can we consider moving the secondary services (image sync, image scan, replications) into a separate container (or service), or have some sort of queueing where we can guarantee that the normal registry operation (push, pull oci artifacts) is not affected?

**Comment by stonezdj** [comment]
It seems that there are lots of running tasks in the jobservice, most are replication and image scan, and the task latency up to 1 day, it is unusual for replication task, (GC task could take 1 day sometimes), we should investigate why these jobs take took too long to complete. do you have any database monitoring tool to monitor the connection and the performance of each SQL, if yes, please check which SQL has the performance issue?

**Comment by dioguerra** [comment]
The only thing visible on the database side is an increase in  the connections to the database that seem to have triggered this. 

![image](https://user-images.githubusercontent.com/5084445/197823519-277745df-6d44-4403-80bb-b169de94409b.png)

![image](https://user-images.githubusercontent.com/5084445/197823808-a316e7af-8282-46da-b825-611e9b313645.png)

![image](https://user-images.githubusercontent.com/5084445/197824411-d7cc51a9-9032-4986-afe5-90f84f1dcd12.png)

But this increase in connections seem to have started way before registry was unresponsive (from the image timewindow is between 26 15h to 27 15h

![image](https://user-images.githubusercontent.com/5084445/197826806-6adf9ed9-67f6-439e-a889-2f263dbff172.png)

**Comment by stonezdj** [comment]
It is very likely that the execution/task webhook issue caused this problem.

could you please run the following SQL in your database?
```
select execution_id, count(*) task_cnt from task group by execution_id
```
If the task count exceed 10000, it might cause the performance issue.
see: https://github.com/goharbor/harbor/issues/17584
