### ISSUE TITLE
gc job failed, there are many blobs that is not erased

### ISSUE THREAD

**Issue by zhongguanqun** [goharbor/harbor#17634]
![harbor1](https://user-images.githubusercontent.com/4767546/194696363-a2a1375e-2091-4469-897f-3026c46918bb.png)
total used amount is about over 18TB.

![harbor02](https://user-images.githubusercontent.com/4767546/194696369-7d417972-75f1-4710-b1c2-46e52d4eca9b.png)
by means of invoking api, calculatation is over 10TB.

the two results diff too much.

![harbor03](https://user-images.githubusercontent.com/4767546/194696372-6a1e050b-3851-4ab7-9a67-3995ea23bb9f.png)
gc job failed, retrun info: {"errors":[{"code":"UNKNOWN","message":"internal server error"}]}

however, I check job_logs, found that 
![harbor04](https://user-images.githubusercontent.com/4767546/194696614-1c75dc32-f969-4762-8cfa-67bf6ce9a6d0.png)

**Versions:**
- harbor: v2.1.6-e38b6131
- docker-compose version 1.27.4, build 40524192
- docker-ce 19.03.13

Thanks for the help & support!

**Comment by wy65701436** [comment]
can you update to the latest harbor and enable the upload [purge](https://github.com/goharbor/harbor/blob/main/make/harbor.yml.tmpl#L241)? Then, let's see the results.

For the gc failure, in v2.6, harbor can skip it and continue executing, you can get the details failure from gc log.

**Comment by stonezdj** [comment]
It is the operation to list and purge _upload directory workaround: https://github.com/goharbor/harbor/issues/15641#issuecomment-942097240
If upgrade to 2.5.0, there is a default job to cleanup the _upload directory.
