### ISSUE TITLE
Upgrade/migration completion log message

### ISSUE THREAD

**Issue by robbrucks** [goharbor/harbor#17647]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate Harbor upgrades but there doesn't seem to be a clear message in the core log for when an upgrade has completed successfully.  We had tried to create an automated upgrade using Ansible, but the upgrade failed during the schema migration due to a PostgreSQL memory exhaustion error.  However, my automation thought the upgrade had completed successfully because the HTTP server had been started.

**Describe the solution you'd like**
I'd like for a log message to be written to the core log during startup indicating whether or not the upgrade or migration step of the Harbor startup process had succeeded or failed.  Also, if the upgrade/migration failed then Harbor should NOT start the HTTP server.  Instead it should stop processing and await human intervention.

**Describe the main design/architecture of your solution**

(INFO log level):
[/core/main.go:NN]: Harbor migration completed successfully.

--OR--  

(ERROR log level)
[/core/main.go:NN]: Harbor migration FAILED.

**Describe the development plan you've considered**
I don't have project visibility to make that determination, other than to say "as soon as possible".

**Additional context**
None

**Comment by stonezdj** [comment]
You could run the harbor-core container with 
```
docker run harbor-core:<tag> -mode=migrate
```
If this command fails, the output message should be
```
failed to migrate the database ....
```

see: https://github.com/goharbor/harbor/blob/f7ebf20d2e2897cea9102b6a55bda71176b8c843/src/core/main.go#L165
