### ISSUE TITLE
Failed multipart uploads taking space on S3 quota

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#17651]
It seems that when images fail to upload (mostly due to big files), the multipart failed blobs will stay in the S3 bucket and will take space
that is not contabilized for the total S3 quota usage. If this files take all the available free space, image or chart upload to the registry
will fail due to lack of quota.

Is there any way harbor takes this blobs into consideration and aborts multipart uploads after they are dangling for X amount of days?

If i list all this multipart uploads, i can see some pending since long time ago. Is this something that the Garbage Collector takes care of? Quite franckly im afraid of activating the GB as on dry run it says it deletes pretty much all the capacity of my registry.

Cheers,

**Comment by dioguerra** [comment]
Some reference if you are hitting the same issue and want to abort this uploads:

```
aws --profile "'${OS_PROJECT_NAME}'" --endpoint-url=https://foo.bar s3api list-multipart-uploads --bucket BUCKET > multipart.json

cat multipart.json | jq '.Uploads[] | "\(.Key) \(.UploadId)"' --raw-output | xargs -n2 -P16 bash -c 's3cmd abortmp s3://BUCKET/$0 $1'

```

**Comment by stonezdj** [comment]
Harbor doesn't count in these failed blobs and could not manage the multipart uploads because it is an underlying storage driver issue.

**Comment by dioguerra** [comment]
Hello @stonezdj 

Currently we are using version 2.5.4 with S3 backend and we did not notice this clean up procedure.
Not sure how you do this, but the best option i found so far is to 'put-bucket-lifecycle-configuration' and 'AbortIncompleteMultipartUpload' after some time

**Comment by dioguerra** [comment]
We are seing many failed uploads from big images, probably what is happening is that the 1week is to much time.
Closing
