### ISSUE TITLE
Update the Harbor instance at demo.goharbor.io to 2.6.x

### ISSUE THREAD

**Issue by thomas-grininger** [goharbor/harbor#17654]
I am currently testing out some features on the demo instance at demo.goharbor.io which is currently running on version `v2.5.0-98e1b82f` and would like to ask if there is a timeline for when this instance will be updated to version 2.6.X?

Best regards

**Comment by YangJiao0817** [comment]
[demo.goharbor.io](https://demo.goharbor.io/) has been upgraded to `v2.6.1-2903d593` .
