### ISSUE TITLE
Upgrading from 2.5.0 to 2.6.1/2.6.0 fails migration

### ISSUE THREAD

**Issue by weebl2000** [goharbor/harbor#17667]
**Expected behavior and actual behavior:**
Trying to migrate the config file from 2.5.0 to 2.6.0/2.6.1 fails with a python error. 

**Steps to reproduce the problem:**
Follow step 1 -> 6 of: https://goharbor.io/docs/2.6.0/administration/upgrade/

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.0 -> 2.6.0/1
- docker engine version: 20.10.20
- docker-compose version: 1.29.2

**Additional context:**

- **Harbor config files:** https://pastebin.com/aYLVPe16

Error thrown:
```
migrating to version 2.6.0
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_6_0/__init__.py", line 20, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_6_0/harbor.yml.jinja", line 6, in top-level template code
    
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'dir'

```

**Comment by weebl2000** [comment]
> This is because there is a problem with your harbor.ml configuration!

The config works fine for 2.5.0 and the error message is too cryptic for me to understand what part my configuration is wrong lol.

**Comment by MinerYang** [comment]
Could you provide the harbor.yml you are using? And describe the steps you are doing when migrate the config file?

**Comment by weebl2000** [comment]
> Could you provide the harbor.yml you are using? And describe the steps you are doing when migrate the config file?

Yes, it's linked in the original issue as a pastebin link, under additional context. The stepst that I'm taking is basically running the migrate, steps 1 through 6 from the documentation mentioend. So it fails on:


`docker run -it --rm -v /:/hostfs goharbor/prepare:v2.6.1 migrate -i /path/to/harbor/harbor.yml
`

**Comment by MinerYang** [comment]
there's 2 errors that inconsistent with 2.5.x harbor.yml file
Before doing migrate script, do not adding/remove any fields manually that version 2.5 don't have. And use attributes correctly.
1. no `trivy.timeout` filed harbor.yml, please remove it.
https://github.com/goharbor/harbor/blob/2b36a6ba64de37fb6908d94d88854872a3bcb027/make/harbor.yml.tmpl#L71
```
trivy:
  # ignoreUnfixed The flag to display only fixed vulnerabilities
  ignore_unfixed: false
  # timeout The duration to wait for scan completion
  timeout: 5m0s
```
2. pls uncommen the `dir` field together with `internal_tls.enabled`
```
# # Uncomment following will enable tls communication between all harbor components
internal_tls:
  # set enabled to true means internal tls is enabled
  enabled: false
  # put your cert and key files on dir
  dir: /etc/harbor/tls/internal
```

**Comment by weebl2000** [comment]
> there's 2 errors that inconsistent with 2.5.x harbor.yml file Before doing migrate script, do not adding/remove any fields manually that version 2.5 don't have. And use attributes correctly.
> 
> 1. no `trivy.timeout` filed harbor.yml, please remove it.
> *** snip to reduce duplicate text ***
>   dir: /etc/harbor/tls/internal
> ```

Thank you very much, this did the trick!

Shall I close this issue or is this something that the project wants to incorporate in the migrate script? I don't think our configuration was very exotic.

**Comment by MinerYang** [comment]
Np, the script just working as expected and I just wanna make sure that the problems solved and I will close this one.
THX.
