### ISSUE TITLE
Unable to add pluggable scanner

### ISSUE THREAD

**Issue by bainss** [goharbor/harbor#17680]
Trying to add an external pluggable-scanner as per https://goharbor.io/docs/2.6.0/administration/vulnerability-scanning/pluggable-scanners/

However I get an error :

Ping: registration Anchore:https://<redacted> is unreachable

logs give me 

[/controller/scanner/base_controller.go:298][error="v1 client: get metadata: : general response handler: unexpected status code: 404, expected: 200" requestID="522f692f5df3e89f1f401075ca670e1f"]: failed to ping scanner
2022-10-20T08:49:26Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"scanner controller: ping: v1 client: get metadata: : general response handler: unexpected status code: 404, expected: 200"}]}   

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

try to add an external scan provider (Anchore) 

**Versions:**
- harbor version: 2.6
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

installed with Helm

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

From the UI in developer mode I can also see 

POST https://<redacted>/api/v2.0/scanners/ping 500

**Comment by zyyw** [comment]
Hi @bainss , could you please elaborate the process how you add `Anchore`, it seems that Harbor cannot get the external scanner meta data.

**Comment by zyyw** [comment]
it looks that scanner spec is using /api/v1
* https://github.com/goharbor/harbor/blob/v2.6.0/src/pkg/scan/rest/v1/spec.go#L45

could you please check your anchore api version? it seems that the lates anchore is using swagger 2.0
* https://docs.anchore.com/current/docs/using/api_usage/specs/engine_api.yaml

**Comment by bainss** [comment]
When trying to add the external service I see the following in the browser when in developer mode...

`/api/v2.0/scanners/ping:1          Failed to load resource: the server responded with a status of 500 ()
/api/v2.0/scanners/ping:1          Failed to load resource: the server responded with a status of 500 ()
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
polyfills.af4f4bbe373e95ea.js:1          POST https://REDACTED/api/v2.0/scanners/ping 500`
