### ISSUE TITLE
Replication - how to get all tags of an image

### ISSUE THREAD

**Issue by pandel** [goharbor/harbor#17699]
Hello!

I am experimenting with replication and trying to setup a rule to fetch a single image from another hub (not Harbor-based), but with all its tags. 

Let's say, I have an image `a/b:latest`, that is also tagged `a/b:v1`,`a/b:v1-bla`, `a/b:v1-bla-blup`. How can get Harbor to replicate all those tags if I only setup `:latest` as filter?

Regards,
Holger

**Comment by chlins** [comment]
Currently there is no way to replicate other associated tags if you only setup `:latest` as filter.

**Comment by pandel** [comment]
That is a real pain, but thank you for the information!
