### ISSUE TITLE
Harbor2.6.1版本在web上修改密码报错：Http failure response for /api/v2.0/users/1/password: 0 Unknown Error

### ISSUE THREAD

**Issue by zhuanvgui** [goharbor/harbor#17705]
新部署的Harbor2.6.1，采用docker部署，登录web ui以后修改admin密码报错：Http failure response for /api/v2.0/users/1/password: 0 Unknown Error，大家有遇到过吗，有什么解决方案吗

**Comment by zyyw** [comment]
Could you please paste the core.log in this issue? Thanks

**Comment by QiuToo** [comment]
I have encountered the problem of insufficient space resources, which caused the exception of the db component and the password cannot be modified! https://mp.weixin.qq.com/s/zjZzVZcJZnlWhAvE608WeA
