### ISSUE TITLE
harbor ping cache service while ICMP is not allowed

### ISSUE THREAD

**Issue by zhilyaev** [goharbor/harbor#17717]
I tried to install harbor on EKS via helm. ICMP is prohibited in the cluster.

I can connect to the harbor redis manually.

```
$ redis-cli -h harbor-redis-master PING
PONG
```

While harbor has logs
```
[ERROR] [/lib/cache/cache.go:114]: failed to ping redis://harbor-redis-master:6379/0, retry after 500ms : dial tcp: lookup harbor-redis-master: i/o timeout
```

The problem method is here: https://github.com/goharbor/harbor/blob/main/src/lib/cache/redis/redis.go#L70

**Comment by wy65701436** [comment]
thanks @zhilyaev,  @chlins let's investigate if there is another way to ping redis while ICMP is not allowed

**Comment by zhilyaev** [comment]
Just use TCP ping message

```golang
package main

import (
    "log"
	"net"
	"strconv"
	"strings"
)

const (
	message       = "PING"
	StopCharacter = "\r\n\r\n"
)

func SocketClient(ip string, port int) {
	addr := strings.Join([]string{ip, strconv.Itoa(port)}, ":")
	conn, err := net.Dial("tcp", addr)

	defer conn.Close()

	if err != nil {
		log.Fatalln(err)
	}

	conn.Write([]byte(message))
	conn.Write([]byte(StopCharacter))
	log.Printf("Send: %s", message)

	buff := make([]byte, 1024)
	n, _ := conn.Read(buff)
	log.Printf("Receive: %s", buff[:n])

}

func main() {

	var (
		ip   = "127.0.0.1"
		port = 6379
	)

	SocketClient(ip, port)

}

```

```bash
go run ./app.go
2022/11/02 11:27:51 Send: PING
2022/11/02 11:27:52 Receive: +PONG
```

What do you @wy65701436 think?

**Comment by AlexBarth13** [comment]
Hi @zhilyaev,

Are you using the ElastiCache Redis service from AWS?
If yes, did you enabled `encryption at rest` and/or `encryption in transit`?

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by zhilyaev** [comment]
@AlexBarth13 No, I use builtin redis in the helm chart.
