### ISSUE TITLE
Error response from daemon: unauthorized: unauthorized to access repository

### ISSUE THREAD

**Issue by palakpandita98** [goharbor/harbor#17713]
I am getting the below error when I am trying to pull an image from the harbor

rpc error: code = Unknown desc = Error response from daemon: unauthorized: unauthorized to access repository:
 action: pull: unauthorized to access repository: xxxx/YYYY, action: pull

Harbor API V2.0

**Comment by zyyw** [comment]
Hi @palakpandita98 , which version of Harbor were you using? And could you please also paste the log messages when you encounter this error? thanks

**Comment by oetiker** [comment]
we get this error for about 30% of the requests being lobbed at our harbor 2.6.1 instance ... 

```
OL7zY| time="2022-11-02T14:14:56Z" level=fatal msg="Error initializing source docker://registry.xxx.com/ci/xxx-services-predict-labels/main/predict-labels:1.0.0: Error reading manifest 1.0.0 in registry.xxx.com/ci/xxx-services-predict-labels/main/predict-labels: unauthorized: unauthorized to access repository: ci/xxx-services-predict-labels/main/predict-labels, action: pull: unauthorized to access repository: ci/xxx-services-predict-labels/main/predict-labels, action: pull"
```
