### ISSUE TITLE
[v1.10.14] can't create a pull policy . msg "Internal Server Error"

### ISSUE THREAD

**Issue by cynen** [goharbor/harbor#17714]
- harbor version: [1.10.14]
- docker engine version:  19.03.15
- docker-compose version:  v2.12.0

install cmd: 
`./install.sh --with-clair --with-chartmuseum`

 [yes ,i already  have a perfect harbor]
purpose: i want to replicat the images from the remote Server (the perfect harbor). 

when i create a replications -->  create a new policy --> 
select the pull policy  `pull-Based` , 
after choice the  resources , then the page alert the Err Msg on the top:   **_Internal Server Error_**

Have any encountered this situation?

How to deal with this kind of problem?

**Comment by zyyw** [comment]
@cynen what is the version of the "perfect harbor". If its version is different from `v1.10.14`, then it's recommended to upgrade harbor to the same version and then replicate images between one another.

Alternatively, would you please paste the log message when you encounter the `Internal Server Error`?

**Comment by cynen** [comment]
(这是来自QQ邮箱自动回复邮件。)
 
您好，你的邮件我已经收到。我会在近期尽快给您回复。

**Comment by zyyw** [comment]
please upgrade Harbor to latest version.

**Comment by cynen** [comment]
> @cynen what is the version of the "perfect harbor". If its version is different from `v1.10.14`, then it's recommended to upgrade harbor to the same version and then replicate images between one another.
> 
> Alternatively, would you please paste the log message when you encounter the `Internal Server Error`?

"perfect harbor" means: i already deployed a harbor v2.6.1 and its work fine.

**Comment by cynen** [comment]
![img](https://cynen.oss-cn-shenzhen.aliyuncs.com/github/pics/err.png)

OK, As you see. I  fllow the steps . 

yes, i have already update my harbor to v2.6.x and its work fine.

BTW, it this is a bug in  v1.10.14?
