### ISSUE TITLE
New release required for OpenSSL 3.0.7

### ISSUE THREAD

**Issue by captn3m0** [goharbor/harbor#17724]
**Expected behavior and actual behavior:**

Expected: Harbor builds should not include vulnerable dependencies.

Actual Behaviour: Harbor docker images bundle a vulnerable version of OpenSSL as was recently announced: https://mta.openssl.org/pipermail/openssl-announce/2022-October/000238.html.

**Steps to reproduce the problem:**

- Run a scan on various Harbor images and check the openssl version.
- OpenSSL version is `3.0x` for all harbor images.
- This is because of Harbor Docker Images using `VMware Photon OS 4.0` as the base image, which ships with a vulnerable version of OpenSSL.

## Scan Results

```
syft --quiet goharbor/chartmuseum-photon:v2.6.1  | grep openssl
openssl                                           3.0.3-3.ph4
syft --quiet goharbor/harbor-core:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/harbor-exporter:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/harbor-jobservice:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/harbor-portal:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/registry-photon:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/harbor-registryctl:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4
syft --quiet goharbor/trivy-adapter-photon:v2.6.1  | grep openssl
openssl                                                          3.0.3-3.ph4

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.6.1
- docker engine version: NA
- docker-compose version: NA

**Additional context:** 

Slack Ref: https://cloud-native.slack.com/archives/CC1E09J6S/p1667133517450439

**Comment by wy65701436** [comment]
We are confirming with the upstream team, and will upgrade openssl in the patch release once we get it fixed in Photon.

**Comment by captn3m0** [comment]
PHSA-2022-0272 is out.

**Comment by wy65701436** [comment]
still pending on the upstream, @captn3m0 please keep monitoring our patch release.

**Comment by sidewinder12s** [comment]
Is it known what versions of Harbor are impacted?

**Comment by Fredouye** [comment]
> Is it known what versions of Harbor are impacted?

According to the syft scanner :

goharbor/harbor-core:v1.10.13 : OpenSSL 1.0.2

goharbor/harbor-core:v2.4.0 : OpenSSL 1.1.1l
goharbor/harbor-core:v2.4.1 : OpenSSL 3.0.0

goharbor/harbor-core:v2.5.0 : OpenSSL 3.0.0

goharbor/harbor-core:v2.6.0 : OpenSSL 3.0.3

So it seems Harbor >= 2.4.1 is impacted.

**Comment by captn3m0** [comment]
Upstream has published 3.0.6-2.ph4 with the fix: https://github.com/vmware/photon/issues/1369#issuecomment-1301748458

**Comment by dan-m8t** [comment]
Any news here?

**Comment by captn3m0** [comment]
https://github.com/goharbor/harbor/releases/tag/v2.6.2-rc1 is out which updates the base image via #17720.

It looks good:

```
syft --quiet goharbor/harbor-core:v2.6.2-rc1 | grep openssl
openssl                                                          3.0.7-1.ph4                                        rpm
```

**Comment by YangJiao0817** [comment]
In the upcoming release of Harbor v2.6.2, openssl will be upgraded to 3.0.7.

**Comment by YangJiao0817** [comment]
Upgrade openssl to 3.0.7 in [Harbor v2.6.2](https://github.com/goharbor/harbor/releases/tag/v2.6.2).

**Comment by ktsowes** [comment]
Are there any plans to fix harbor 2.4.x and 2.5.x as well?

**Comment by ktsowes** [comment]
> Are there any plans to fix harbor 2.4.x and 2.5.x as well?

Any updates for this?

**Comment by YangJiao0817** [comment]
@ktsowes In Harbor v2.5.5 will upgrade openssl to 3.0.7
Harbor v2.4.x will not fix this issue, as Harbor v2.4.x is not on the maintenance list.

**Comment by ktsowes** [comment]
@YangJiao0817 Thanks for your response. 

I read at https://github.com/goharbor/harbor/blob/main/SECURITY.md:

> The Harbor project maintains release branches for the three most recent minor releases. Applicable fixes, including security fixes, may be backported to those three release branches, depending on severity and feasibility.

According to this statement, 2.4.x should be fixed as the vulnerability is pretty severe and 2.4.x is part of the three most recent minor releases.

I presume it's not only me who would appreciate a fix...

**Comment by wy65701436** [comment]
> 

@ktsowes Correct, stay tuned for our release as we are planning the patches.

**Comment by ktsowes** [comment]
> @ktsowes Correct, stay tuned for our release as we are planning the patches.

wy65701436 are there any updates on this?

**Comment by YangJiao0817** [comment]
[Harbor v2.5.5](https://github.com/goharbor/harbor/releases/tag/v2.5.5) has been released.
