### ISSUE TITLE
Updating the quota of a project directly with API

### ISSUE THREAD

**Issue by batusekerci** [goharbor/harbor#17737]
Hi, I am trying to code a feature that first checking a project quota is available before upload, and then allows the uploading process. And also there is another feature that increasing/decreasing the project quotas on a condition. So, I take a look on API and concluded that there is no API for updating or getting a "project" quota directly. Am I right? 

Seems to me the only way is pulling all quotas, searching for specific project name and pulling the quota id of that project and finally using the quotas/{id} API

**Comment by rrgadeev** [comment]
get https://harbor.local/api/v2.0/projects/example/summary

**Comment by YangJiao0817** [comment]
You can try the following APIs
1. Get project quota
```
curl -k -u '<username>:<password>' -X 'GET' 'https://harbor.local/api/v2.0/quotas?reference_id=<project_id>'
```
2. Update project quota
```
curl -k -u '<username>:<password>' -X 'PUT' \
 'https://harbor.local/api/v2.0/quotas/<quota_id>' \
 -H 'accept: application/json' \
 -H 'Content-Type: application/json' \
 -d '{"hard":{"storage":<your_quota>}}'
```
