### ISSUE TITLE
Update document for config item OIDC Group Filter

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#17741]
Update document for config item OIDC Group Filter

**Comment by sjoukedv** [comment]
@stonezdj I am actually looking for this configuration option. How can I set a filter to only allow certain OpenID connect groups?

I am also missing this configuration option from the UI (using v2.6.2):

![image](https://user-images.githubusercontent.com/24683344/202671226-f115c316-5452-42e0-8c03-2e3c0246e084.png)

I found the options in the source code, https://github.com/goharbor/harbor/tree/main/src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html#L738, and it is supposed to be in between `oidcClientSecret` and `oidcGroupClaim`.

**Comment by sjoukedv** [comment]
Also no luck with the API

```
curl --location --request POST '<url>/api/v2.0/configurations' \
--header 'Authorization: Basic <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "oidc_group_filter": "<group>"
}'
```
