### ISSUE TITLE
Replication list tags rate limit

### ISSUE THREAD

**Issue by oscni** [goharbor/harbor#17746]
**Is your feature request related to a problem? Please describe.**
Yes, replicating a large library from dockerhub results in rate limit error 429 just by listing all the tags so the replication will fail and not even start.

**Describe the solution you'd like**
Rate limit list tags so that the job takes longer but do not exceed what the source registry allows.

**Describe the main design/architecture of your solution**
Preferably a configuration per registry endpoint.

**Describe the development plan you've considered**

**Additional context**

**Comment by zyyw** [comment]
@oscni please follow up DockerHub policy to resolve the "rate limit error" issue. Closing it now.

**Comment by oscni** [comment]
Did you understand that I'm not writing about rate limit for image pull but a rate limit for listing tags.
