### ISSUE TITLE
The deployment of harbor v2.6.1, but the container status to unhealthy

### ISSUE THREAD

**Issue by ptthon** [goharbor/harbor#17747]
dokcer ps, the container status to unhealthy,but curl -X GET "http://{ip}:8080/api/v2.0/health" -H "accept: application/json",  Each state is healthy

`root@ecs--wafv1:~# curl -X GET "http://172.31.1.201:8080/api/v2.0/health" -H "accept: application/json"
{"components":[{"name":"core","status":"healthy"},{"name":"database","status":"healthy"},{"name":"jobservice","status":"healthy"},{"name":"portal","status":"healthy"},{"name":"redis","status":"healthy"},{"name":"registry","status":"healthy"},{"name":"registryctl","status":"healthy"}],"status":"healthy"}
`

`root@ecs--wafv1:~# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                      PORTS                                       NAMES
7efb8b187c02   goharbor/harbor-jobservice:v2.6.1    "/harbor/entrypoint.…"   16 minutes ago   Up 16 minutes (unhealthy)                                               harbor-jobservice
d92598904c71   goharbor/nginx-photon:v2.6.1         "nginx -g 'daemon of…"   16 minutes ago   Up 16 minutes (unhealthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   nginx
a4f04a8fabe6   goharbor/harbor-core:v2.6.1          "/harbor/entrypoint.…"   16 minutes ago   Up 16 minutes (unhealthy)                                               harbor-core
07af7da42b19   goharbor/harbor-db:v2.6.1            "/docker-entrypoint.…"   16 minutes ago   Up 16 minutes (healthy)                                                 harbor-db
7ad3889695ad   goharbor/harbor-registryctl:v2.6.1   "/home/harbor/start.…"   16 minutes ago   Up 16 minutes (unhealthy)                                               registryctl
f2e16d780da7   goharbor/registry-photon:v2.6.1      "/home/harbor/entryp…"   16 minutes ago   Up 16 minutes (unhealthy)                                               registry
19601a81db6b   goharbor/harbor-portal:v2.6.1        "nginx -g 'daemon of…"   16 minutes ago   Up 16 minutes (unhealthy)                                               harbor-portal
dc3fcee93aab   goharbor/redis-photon:v2.6.1         "redis-server /etc/r…"   16 minutes ago   Up 16 minutes (healthy)                                                 redis
7abea904347b   goharbor/harbor-log:v2.6.1           "/bin/sh -c /usr/loc…"   16 minutes ago   Up 16 minutes (healthy)     127.0.0.1:1514->10514/tcp                   harbor-log
`

**Comment by QiuToo** [comment]
Please check the log of the component with the exception to troubleshoot the problem. This may help you: https://mp.weixin.qq.com/s/zjZzVZcJZnlWhAvE608WeA

**Comment by zyyw** [comment]
@ptthon could you please paste the log of corresponding components in unhealthy status? Thanks

**Comment by zyyw** [comment]
`docker ps` and curl "http://{ip}:8080/api/v2.0/health" are different.
