### ISSUE TITLE
Bi-directional push replication causes a replication loop

### ISSUE THREAD

**Issue by rci-kmccolm** [goharbor/harbor#17754]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We have two Harbor instances in different sites and we want to keep them in sync with each other and use Anycast or GSLB type load balancing/failover. When creating a push based replication rule between the two harbor sites, any change in one site gets replicated to the remote site, however the remote site then re-replicates the change back to the original site, and on and on. This creates a continual loop of replication traffic that drives unneccesary CPU, disk and network utilization on the Harbor servers.

We expect that when a replication event is received from a remote Harbor instance that it would not then immediately be pushed to the Harbor that sent the update even if a replication rule exists to do so.

Perhaps this is not the intended architecture for Harbor replication, please guide us if so.

**Steps to reproduce the problem:**
1. Create two harbor instances
2. Create a registry endpoint on each Harbor instance, pointing to the other
3. Create a push based replication rule on each Harbor to push updates to the other Harbor

**Versions:**
Please specify the versions of following systems.

- harbor version: `v2.7.1-6015b3ef`
- docker engine version: `20.10.21`
- docker-compose version: `2.12.2`

**Additional context:**

- **Harbor config files:** decline to provide
- **Log files:** decline to provide

**Comment by zyyw** [comment]
Please double check this on Harbor 2.6.1 @YangJiao0817 . Closing it if not reproduce-able.

**Comment by YangJiao0817** [comment]
Chartmuseum has been deprecated in v2.8.0, you can migrate helm charts to oci artifacts to solve this problem, refer to https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-harbor
