### ISSUE TITLE
Harbor Replication Azure Container Registry task failure

### ISSUE THREAD

**Issue by yuangeqingian** [goharbor/harbor#17755]
My ACR name: testdev
ACR URL: https://testdev.azurecr.io
ACR level: Premium 

I used acr admin username and password and tested connection in registry successful, so no privilege lacking.
Then I created replication rule without any filtering condition and always failed.
![image](https://user-images.githubusercontent.com/9658083/200218029-13e0de4e-eae2-4a20-8be8-1ee809ab028b.png)

The error message points to 401 error and unauthorized 
However, if I add some filter condition to mirror certain docker image/helm chart , the replication task can perform succeed.
![image](https://user-images.githubusercontent.com/9658083/200476524-0ba8e1a4-b1ce-40cc-8d0c-3febe3b31295.png)

**Comment by chlins** [comment]
Could you confirm whether your username and password have the permission to call `catalog` and `list tags` API?

**Comment by chlins** [comment]
Similar issue: https://github.com/goharbor/harbor/issues/16341

**Comment by rrgadeev** [comment]
use
name: **
tags: **

**Comment by yuangeqingian** [comment]
List tag API and call catalog api for Azure container registry seems all ok
![image](https://user-images.githubusercontent.com/9658083/200353237-8e8bcb72-5e03-482d-8e8d-6bd34963c90c.png)
![image](https://user-images.githubusercontent.com/9658083/200356002-5867fcfd-a8f3-4917-9ba7-ef82cfbdb66b.png)

**Comment by yuangeqingian** [comment]
https://github.com/goharbor/harbor/issues/17755

**Comment by yuangeqingian** [comment]
Thanks a lot for your fast feedback, any more information I should provide?

**Comment by yuangeqingian** [comment]
Success Harbor replication tasks to mirror ACR content:

![image](https://user-images.githubusercontent.com/9658083/200362598-4c33f232-abed-4fac-bcfa-c27d9dfe1158.png)
![image](https://user-images.githubusercontent.com/9658083/200366133-06453107-112e-4f15-ba2f-b07a78f78765.png)

**Comment by yuangeqingian** [comment]
@chlins , any update on this issue? Or anything more you need me to provide as supporting material?

**Comment by chlins** [comment]
> List tag API and call catalog api for Azure container registry seems all ok ![image](https://user-images.githubusercontent.com/9658083/200353237-8e8bcb72-5e03-482d-8e8d-6bd34963c90c.png) ![image](https://user-images.githubusercontent.com/9658083/200356002-5867fcfd-a8f3-4917-9ba7-ef82cfbdb66b.png)

@yuangeqingian The API for `list tags` you used seems different with harbor, replication call the OCI v2 list tags(`/v2/<name>/tags/list`) API for that. ref: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints

**Comment by yuangeqingian** [comment]
@chlins  thanks a lot for your quick feedback.
List tag API works for me also:
![image](https://user-images.githubusercontent.com/9658083/200984256-22b37294-dc6c-43f9-ac87-11998b2bbc2e.png)

**Comment by yuangeqingian** [comment]
@chlins  anything more you want me provide?

**Comment by yuangeqingian** [comment]
@chlins  I have another issue here, there are some broken docker images in ACR, it blocks the whole replication task
Anything we can do to improve that status?

**Comment by yuangeqingian** [comment]
Any logs you need provide such as harbor job service log?

**Comment by chlins** [comment]
Which version do you use?

**Comment by yuangeqingian** [comment]
> Which version do you use?

2.6.0

**Comment by chlins** [comment]
> 1: The account in Harbor that used to mirror ACR has ACR pull privilege granted and test connection succeed. 2: The issue happens for a specific ACR with 570 repository and over 20000+ docker image/helm chart counted with tags. 3: The account in Harbor for replication task succeed with multiple other ACRS with smaller storage size or smaller tags size.

@yuangeqingian Hi, I don't know the difference for the specific ACR, maybe some additional settings, I'm also curious about the issue, theoretically one would work, the others should work as well because they call the same APIs.

**Comment by yuangeqingian** [comment]
Yeap, I also raised ticket to Azure, they also don't know the root cause.
Right now, the workaround is to create multiple replication rules to sync ACR content.
If I had more time, I will try to find root cause.
