### ISSUE TITLE
Statistics will not be displayed in Harbor

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#17759]
Hi all,

We are having an issue in our environment, that the statistics are not visible anymore:

![image](https://user-images.githubusercontent.com/99802718/200365431-556bc07a-0489-4491-82b3-b80a455a3b45.png)

This is the entry from the `core.log`:
```
Nov  7 07:27:55 192.168.160.1 core[23485]: 2022-11-07T12:27:55Z [ERROR] [/lib/http/error.go:56]:
{"errors":[{"code":"UNKNOWN","message":"unknown: ERROR: relation \"system_artifact\" does not exist (SQLSTATE 42P01)"}]}
```

Harbor version: `v2.6.1`

Do you know why this issue occur and how to solve it?

Thank you in advance!

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by MinerYang** [comment]
Could you provide you database logs as well? Or for example query the project_metadata table manually for testing.

**Comment by AlexBarth13** [comment]
The issue was resolved on our end.
Reason of issue:
Due to manual database changes the issues occured. We didn't observed the issue in any other region.

<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Robbie558** [comment]
We are seeing the exact same issue after upgrading several versions for v2.5.X o v2.11.X.  

We appear to be completely missing the `system_artifact` table from the `registry` database, and are unclear as to why the migration scripts failed to run.
