### ISSUE TITLE
Is this a bug in v1.10.14?

### ISSUE THREAD

**Issue by cynen** [goharbor/harbor#17761]
How can we help you?

**Comment by cynen** [comment]
https://github.com/goharbor/harbor/issues/17714#issuecomment-1299457815

![img](https://cynen.oss-cn-shenzhen.aliyuncs.com/github/pics/err.png)

**Comment by cynen** [comment]
I have tried many times and this problem occurs every time

**Comment by cynen** [comment]
> I have tried many times and this problem occurs every time

`tried many times` means :  redeployed the harbor v1.10.14 in a different environment and machine.

**Comment by wy65701436** [comment]
Hi, since v1.10 is not supported, please try with a supported version of harbor v2.4 or above, thank you.

**Comment by cynen** [comment]
> Hi, since v1.10 is not supported, please try with a supported version of harbor v2.4 or above, thank you.

Thank you
