### ISSUE TITLE
Can I add a custom domain name feature for the agent ?

### ISSUE THREAD

**Issue by xzxiaoshan** [goharbor/harbor#17777]
Take `docker.io/ranger/mirrored-pause: 3.6` as an example. 
Create a project agent named `dockerhub` in Harbor to `hub.docker.com`. 
The actual pull address is now `www.myharbor.com/dockerhub/ranger/mirrored-pause: 3.6`. 
If you can customize the sub domain name to `dockerio.myharbor.com/ranger/mirrored-pause: 3.6`, it is a good feature function to maintain the consistency of URIs.

![image](https://user-images.githubusercontent.com/16459864/201015783-697b1ddb-832d-4548-924f-eb5053d947a8.png)

There were several HTTPS certificates with different domains in the `harbor.yml` file.

**Comment by QiuToo** [comment]
这个当然可以，可以在harbor.yml配置文件中的hostname参数后填写域名即可！

**Comment by xzxiaoshan** [comment]
> 这个当然可以，可以在harbor.yml配置文件中的主机名参数后域名重新刷新！

添加 hostname 似乎不可以吧？

这个是代理项目，正常的访问路径应该是  harbor.test.com/dockerhub/xxx/xxx:v1.1.0，期望的访问地址是 harbor.test.com/xxx/xxx:v1.1.0，不希望做了代理就必须增加一个 path 前缀，希望和代理原始域名的 path 保持一致仅仅是域名区别。

**Comment by xzxiaoshan** [comment]
官方有计划处理这个问题吗？
