### ISSUE TITLE
Call harbor API to list all repositories under a project only get 10 results everytime

### ISSUE THREAD

**Issue by yuangeqingian** [goharbor/harbor#17787]
I have another question here, I want to list all repositories under a project in harbor 2.6.
I read harbor api doc and get only 10 repositories every time:

![image](https://user-images.githubusercontent.com/9658083/201344288-9a7e4d27-ed3f-498e-823c-077471dd81c3.png)

Did I use wrong method or I need configure harbor to make it work?

**Comment by chlins** [comment]
The almost API of harbor have the query parameters `page` and `page_size`, the default page_size is 10.

**Comment by yuangeqingian** [comment]
> The almost API of harbor have the query parameters `page` and `page_size`, the default page_size is 10.

How can I change the page size ? I mean any document I can refer?

**Comment by chlins** [comment]
Add query parameters in the URL, for example: `https://demo.goharbor.io/api/v2.0/projects/library/repositories?page=1&page_size=10`

**Comment by MinerYang** [comment]
you can do query like this 
https://harbor.domain.com/api/v2.0/projects/test/repositories?page=1&page_si

Also, you can view Harbor API v2.0 to have a try.
<img width="240" alt="Screen Shot 2022-11-14 at 09 24 05" src="https://user-images.githubusercontent.com/44956229/201556646-07dbc0f9-fae2-4b14-ba96-d6fe2a25725f.png">
ze=20
