### ISSUE TITLE
Proposal- run tag retention policies with immutability rules in place

### ISSUE THREAD

**Issue by rodrigo14miguel** [goharbor/harbor#17781]
**Is your feature request related to a problem? Please describe.**

Not being able to run tag retention policies with immutability rules in place.
It would be nice to keep our tags immutable, to prevent the usage of existing tag on new digests, and to do scheduled tag retention policies for automatic cleanup of older not used images.

**Describe the solution you'd like**

The ability to run tag retention policies with immutability rules in place.

**Comment by MinerYang** [comment]
Could you provide more specific info on this request ? For example steps? And what's exactly meaning of  `existing tag on new digests`?

**Comment by rodrigo14miguel** [comment]
Hi,

Currently we have tag immutability enabled for our repos. This so that the developers don't overwide existing images.  

We enabled tag retention policies to do auto cleanup of really old images. 
We do a dry run of the tag retention policy but the policy cannot remove images with immutable tags, giving the following message:
```text
                                 Digest                                  |            Tag            | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|---------------------------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:xxxxxxx  | 6.0              | image |        | 2022/05/04 10:29:42 | 2022/06/22 09:28:57 | 2022/05/04 10:29:42 | IMMUTABLE |
2022-11-14T09:49:36Z [INFO] [/pkg/retention/job.go:206]: Retention error for artifact image:PROJECT/REPO/IMAGE:sha256:xxxxxxx : Immutable tag
```

I checked the docs and this is by design.
Right now, to run tag retention policy to cleanup, we have to:

- manually disable tag immutability
- run tag retention policy
- manually enable tag immutability


It would be nice to cleanup older images through tag retention policies, even with tag immutability enabled.

**Comment by YangJiao0817** [comment]
Yes, it is by design that tag immutability takes precedence over tag retention.
