### ISSUE TITLE
Harbor Replication rule pattern matching

### ISSUE THREAD

**Issue by yuangeqingian** [goharbor/harbor#17788]
I wrote harbor replication rules to mirror certain docker images in Azure Container Registry
ACR repository name: dev/app/slb-drillplan-reporting-pubsub

My replication rules here:
![image](https://user-images.githubusercontent.com/9658083/201357050-a3b37435-4ecf-4004-8657-96d6c22151f0.png)

The ACR repository name exists, but harbor just can't find that 
![image](https://user-images.githubusercontent.com/9658083/201357217-c7daacdb-a6c6-459e-a61a-806bf990da2b.png)

**Comment by MinerYang** [comment]
Could share your task logs of trigger replication task logs and the logs for harbor-core?
Which version of harbor is in use?

**Comment by yuangeqingian** [comment]
Root cause found, the repository got no real content,and no tags.
I think you can close this issue
