### ISSUE TITLE
代理仓库能否添加支持 push 功能？

### ISSUE THREAD

**Issue by xzxiaoshan** [goharbor/harbor#17796]
1、开发环境有 Harbor 仓库一个，配置了一个代理项目，代理项目中缓存了很多镜像。
2、生成环境和开发环境是网络隔离的，且生产环境禁止联网。
3、一开始将开发环境的整个 Harbor 拷贝到了生产环境。
4、后来因为开发环境新增了一些缓存镜像，无法迁移到生成环境的 Harbor 仓库中。
因为目前版本：
》harbor 不支持 push 镜像到代理项目（建议能支持 push 功能）。
》harbor 的代理项目，UI界面上没有上传功能（比如可以上传一个 docker save 后的 tar 文件）。

或者针对代理项目的问题，有没有什么解决方案？

**Comment by MinerYang** [comment]
Current we don't support tar file uploading and no plan to support the push functions.

**Comment by xzxiaoshan** [comment]
get, 3Q~
