### ISSUE TITLE
代理项目为什么有的image会没有 tag

### ISSUE THREAD

**Issue by xzxiaoshan** [goharbor/harbor#17798]
代理项目，为什么有的image会没有tag，如下图所示：

![image](https://user-images.githubusercontent.com/16459864/201698493-07abad41-9cf4-4edd-81c9-5a20afe1a9e6.png)

![image](https://user-images.githubusercontent.com/16459864/201698542-4854251e-86cf-4599-8613-3de3a849e7a7.png)

**Comment by wy65701436** [comment]
what's the harbor version? and can you provide the core.log for reference?

**Comment by stonezdj** [comment]
Because the docker client might cache the tag and digest information in local,and it will convert the pull by tag command to pull by digest, then the Harbor server just received the pull by digest command, and can't create the tag for this artifact.

**Comment by xzxiaoshan** [comment]
这些是 代理的项目，内容来自第三方仓库，不是本地手工推送上去的。本地手工推送上去的都有。

**Comment by xzxiaoshan** [comment]
> what's the harbor version? and can you provide the core.log for reference?

version：v2.5.3-797c3536

**Comment by stonezdj** [comment]
https://github.com/goharbor/harbor/issues/15591#issuecomment-927742241

**Comment by lissan** [comment]
the problem is relevant
