### ISSUE TITLE
Add default project when pulling from dockerhub without project name doesn't work as intended

### ISSUE THREAD

**Issue by AnishMadan** [goharbor/harbor#17804]
PR https://github.com/goharbor/harbor/pull/17537 was supposed to fix issue #12719 but when testing if it works, I ran into some trouble.

Building harbor from source and testing this PR results in an error:
`Error response from daemon: unknown: bad request: invalid repository name: redis`

`core.log` logs an `ERROR` message containing:
`authutils.go:104]: Failed to handle the resource repository:redis, due to error unable to parse image from string: redis, returning empty access for it.`

This error looks like it can be traced back to `parseImg` in `creator.go`, which can't account for this new acceptable pull format that this PR should enable.

**Comment by stonezdj** [comment]
Please pull with `docker pull 10.192.203.193/<dockerhub_proxy_project>/redis:4.0`
