### ISSUE TITLE
401 Unauthorized with api/v2.0 when create project

### ISSUE THREAD

**Issue by fzwu** [goharbor/harbor#17803]
I used api/v2.0 to create a project.I'm already add authentication in headers ,but response 401 Unauthorized
eg:
var authentication = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{_HarborConfig.UserName}:{_HarborConfig.Password}"));
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", authentication);
httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
httpClient.BaseAddress = new Uri(_HarborConfig.BaseUri);
HttpResponseMessage response = null;
if (httpMethod == HttpMethod.Post || httpMethod == HttpMethod.Put)
{
var buffer = Encoding.UTF8.GetBytes(keyValues);
var byteContent = new ByteArrayContent(buffer);
byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
byteContent.Headers.Add("authentication", authentication);
//var formUrlEncodedContent = new FormUrlEncodedContent(keyValues);
if (httpMethod == HttpMethod.Post)
{
response = await httpClient.PostAsync(requestUri, byteContent);
}
else
{
response = await httpClient.PutAsync(requestUri, byteContent);
}
}

Core log：
Nov 15 10:27:09 172.19.0.1 core[20013]: 2022-11-15T02:27:09Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="192.168.60.118" requestID="fe34a826-8424-4ce9-8840-ad379e53176a" user agent=""]: failed to authenticate user:admin, error:Failed to authenticate user, due to error 'Invalid credentials'

**Comment by wy65701436** [comment]
are you able to create project with the curl command(basic auth)?

**Comment by MinerYang** [comment]
Also pls make sure your authentication base64-encoded string is correct.

**Comment by MinerYang** [comment]
Closed by solved https://github.com/goharbor/harbor/discussions/17802
