### ISSUE TITLE
replication rule no take effect

### ISSUE THREAD

**Issue by lklkxcxc** [goharbor/harbor#17810]
**Expected behavior and actual behavior:**
I created new replication rule content "platform/velero/*" and other option default used to match source harbor image 'platform/velero/velero:v1.7.1' . The next manual 
action reolication success but log show 'no resources need to be replicated'

core.log: 
```
Nov 16 16:29:30 172.19.0.1 core[4280]: 2022-11-16T08:29:30Z [INFO] [/replication/operation/flow/copy.go:75]: no resources need t
o be replicated for the execution 40575, skip
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0 
- docker engine version: 19.03.8
- docker-compose version: 1.18.0

**Additional context:**

**Comment by wy65701436** [comment]
please attach the screen shot of your replication rule, thanks.

**Comment by lklkxcxc** [comment]
@wy65701436  Please look screen picture.

**Comment by chlins** [comment]
Which version of your source harbor, is it also v2.1.0?

**Comment by MinerYang** [comment]
https://goharbor.io/docs/2.1.0/administration/configuring-replication/create-replication-rules/
Please refer to the filter patterns part in the docs

**Comment by lklkxcxc** [comment]
@chlins My source harbor is  v1.9.4-49eb397c.

**Comment by lklkxcxc** [comment]
@chlins My source harbor is  v1.9.4-49eb397c.

**Comment by lklkxcxc** [comment]
@chlins My source harbor is  v1.9.4-49eb397c.

**Comment by lklkxcxc** [comment]
@MinerYang It still does not work when filter patterns part 'platform/velero' and 'platform/velero'

**Comment by lklkxcxc** [comment]
@chlins Only this rule dose not work,the others are in effect .

**Comment by chlins** [comment]
Harbor does not fully test and support for the replication which cross the major version, there are big gaps between v1.x and v2.x.
