### ISSUE TITLE
hi. I found an harbor unauthorized access vulnerability

### ISSUE THREAD

**Issue by lanqingaa** [goharbor/harbor#17827]
hi. I found an harbor unauthorized access vulnerability

**Comment by OrlinVasilev** [comment]
Hi there!

Thank you so much for that!
Can you send mail to: cncf-harbor-security@lists.cncf.io
Also here is the process: https://github.com/goharbor/harbor/blob/main/SECURITY.md

**Comment by lanqingaa** [comment]
> 你好啊！
> 
> 非常感谢！ 您是否可以将邮件发送至：[cncf-harbor-security@lists.cncf.io](mailto:cncf-harbor-security@lists.cncf.io) 流程如下：https://github.com/goharbor/harbor/blob/main/SECURITY.md



Mail not sent successfully
host lb01.groups.io[45.79.81.153] said: 500 Invalid request (in reply to RCPT TO command)

**Comment by lanqingaa** [comment]
I tried to send email 3 times but failed,Can I write the details of vulnerability recurrence here?

**Comment by Vad1mo** [comment]
@lanqingaa this is a terrible idea, that might put many systems in danger.  You can send me an email and I'll bring it up and discuss with the team. vb(AT)container-registry.com or @OrlinVasilev orlin(AT)orlix.org

**Comment by lanqingaa** [comment]
> @lanqingaa this is a terrible idea, that might put many systems in danger,before we can provide a patch. You can send me an email and I'll bring it up and discuss with the team. vb(AT)container-registry.com or @OrlinVasilev orlin(AT)orlix.org

What is your email address?

**Comment by lanqingaa** [comment]
@Vad1mo@OrlinVasilev What is your email address?

**Comment by lanqingaa** [comment]
@Vad1mo @OrlinVasilev What is your email address?

**Comment by Vad1mo** [comment]
email is vb(AT)container-registry.com or orlin(AT)orlix.org
you have to replace the (AT) with the actual @

**Comment by lanqingaa** [comment]
So far, have you confirmed the vulnerability?When will the security version be released?Please reply me by email! thank you!

**Comment by Vad1mo** [comment]
Not yet, we will reply/contact you via your email address.
