### ISSUE TITLE
Not scanned is displayed in tag details if image was scanned and does not have any vulnerabilities

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#17830]
**Expected behavior and actual behavior:**
I pushed new docker image to harbor project and scanned it using Trivy. It does not contains any vulnerabilities. Artifacts list shows that there are no vulnerabilities, but when I go to artifact details, I see that image was not scanned. I think that there should be something like 'No vulnerabilities found' message instead. Now it is confusing because I do not know if image does not have vulnerabilities or if scan failed and there is no report..

<img width="950" alt="artifacts-list" src="https://user-images.githubusercontent.com/20277750/203027166-559fb891-9c1c-410b-b29e-eaf0049b9c19.PNG">
<img width="1697" alt="artifact-details" src="https://user-images.githubusercontent.com/20277750/203027367-c8e8d906-b12c-4941-ae21-0966b50c5e1a.PNG">

**Steps to reproduce the problem:**
1. Take the newest alpine image and push it to repository.
2. Scan it using Trivy or other tool.
3. Go to repository, check Vulnerabilities column first, then click on artifact sha256 to display it's details.

**Versions:**
- harbor version: v2.5.1
- helm chart: harbor/harbor 1.9.1
- k8s version: Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+IKS", GitCommit:"acd6e017f238295f63fbb1aa691e7219a23257b6", GitTreeState:"clean", BuildDate:"2022-11-10T21:01:38Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by AllForNothing** [comment]
@jowko sure, you can close it now and reopen it if needed
