### ISSUE TITLE
Maintaining the GCR adapter

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/harbor#17835]
Hi All,
as we discussed we need folks and effort to properly support GCR
reached out to the community by:https://twitter.com/project_harbor/status/1594732216265109504
and @AvineshTripathi proposed he can help and he already did that for [@kubescope](https://github.com/kubescape/kubescape) via
https://github.com/kubescape/kubescape/pull/825

Can we use/reuse that?
Orlix

**Comment by OrlinVasilev** [comment]
@AvineshTripathi are you able to work on this ?

**Comment by AvineshTripathi** [comment]
@OrlinVasilev thanks for the reminder I forgot about this issue, sorry to keep you waiting! I'll start working on this

**Comment by OrlinVasilev** [comment]
Heyyyyy :) @AvineshTripathi thank you so much!!!! No hurry at all I was just wondering if you are still happy to spend some time on that :)) if you need anything just drop me a line ok ? Thanks again!!!

**Comment by AvineshTripathi** [comment]
Hey @OrlinVasilev I tried looking into links provided however I am a bit unsure about the expectatione of this issue can you give link or some more context to the expectations or maybe what feat we are looking for over here

**Comment by brad-taylor-yvr** [comment]
Not sure where to comment on the GCR/GAR integration, so I hope you don't mind the intrusion here...

Our corporate policy prohibits the use of (secret) service account keys for authentication. Is there any thought/interest/activity to use Access tokens for authentication?

https://cloud.google.com/artifact-registry/docs/docker/authentication#methods 

I'm generating an access token as:
`gcloud auth print-access-token --impersonate-service-account my-service-account@<project-id>.iam.gserviceaccount.com`

In the Harbor **New Registry Endpoint** dialog...

When I paste the access token in the **Access Secret** field
with _Google GCR_ as the selected **Provider** 
and _https://us.gcr.io_ as the **Endpoint URL** 

I get **_Failed to ping endpoint._**

Appreciate any advice on how best to proceed. Thanks!

**Comment by OrlinVasilev** [comment]
@brad-taylor-yvr no worries at all just not sure about your issue @wy65701436 can you comment on that?ideas?

**Comment by AvineshTripathi** [comment]
> Hey @OrlinVasilev I tried looking into links provided however I am a bit unsure about the expectatione of this issue can you give link or some more context to the expectations or maybe what feat we are looking for over here  

Hey @OrlinVasilev can you also address this comment. Thank you!

**Comment by OrlinVasilev** [comment]
@yanji09 I think you had something in mind here or I'm mistaken ?

**Comment by yanji09** [comment]
This originally came from #16973 to ask Harbor replication to support GCR. We would like to get helps from community to update/test the replication adapter to support GCR. Based on the progress of #16973, the GCR did slight changes at their side and now the harbor replication works for GCR without changes from harbor side.
While for long-term expectation, it would be great if someone from community can maintain the replication GCR adapter. For example, if there are break changes at GCR side, he can maintain/test the adapter and do the corresponding changes from harbor side.
