### ISSUE TITLE
Scaling Garbage Collector

### ISSUE THREAD

**Issue by honzasara** [goharbor/harbor#17836]
My Harbor use Swift Storage, we have not any problem with this.

but, we have about 10TB in this storage. Garbage Collector is too lazy. One run spent about 7 days.

It is possible to run the Garbage Collector in multiple instances ?

H.

**Comment by honzasara** [comment]
Hello,

i have details on this the problem. The problem is not big storage. But the problem is number of images.  More image is new created/uploaded and more images is removed.

H.

**Comment by wy65701436** [comment]
As harbor has introduced the parallel deletion since v2.9.0, you can set the workers to 5 and see if it's satisfy your request. Reopen it if it is still a blocker in your side.
