### ISSUE TITLE
Harbor Installation fails due to parser error in no_proxy

### ISSUE THREAD

**Issue by santoshkumarindia** [goharbor/harbor#17831]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Upgrade from 2.2.1 to 2.3.3 keeps failing due to a parser error in harbor.yml at line no proxy during ./install.sh script. For the upgrade, we have used the 2.2.1 harbor.yml file.
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/118736396/203055286-7eb89417-a595-44c9-8ce9-a31c7bb1476e.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/118736396/203054968-b4f499cc-df4c-41ab-8844-15908d9a8cd7.png">

While troubleshooting, we identified that after running the migrate command using command : docker run -it --rm -v /:/hostfs goharbor/prepare:v2.3.3 migrate -i /root/harbor/harbor.yml
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/118736396/203056256-4f040368-7a9e-4e91-b9c7-3bc6944a96e4.png">
harbor.yml file is getting update at line no_proxy. At this line, double quotes are getting removed for the values.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/118736396/203055067-5a26d7da-b65d-4fd3-a83b-c63f48af5180.png">

After inserting the double quotes manually into the no_proxy line, I re-tried install.sh command and it was installed successfully.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/118736396/203054968-b4f499cc-df4c-41ab-8844-15908d9a8cd7.png">

**Steps to reproduce the problem:**
In line no_proxy , remove the double quotes for the set values.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.1 to 2.3.3]
- docker engine version: [20.10.6]
- docker-compose version: [1.29.2]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MinerYang** [comment]
Hi @santoshkumarindia ,

Thanks for reporting this issue. After we 've done a several investigations, the problems related to the string filled the no_proxy attributes start with a special character `*`  which made the yml file can not be parsed and loaded properly.
Same problems will occurred when you are using a string starting with special characters like `*`, `@`, `#` etc.  for other property settings. 

We recommend to using a string not start with those special characters , then you don't need to added the double quotes manually, thereby running yml migration more smoothly everytime.
```
example:
no_proxy: 127.0.0.1, localhost, *.testlab.in
```

We will consider to add a yml validater in future release to make the pop-out error more readable.

Thx,
Miner
