### ISSUE TITLE
How to modify a project's “Proxy Cache Endpoint”

### ISSUE THREAD

**Issue by haitang5445** [goharbor/harbor#17840]
I want to change the project's Proxy Cache Endpoint

**Comment by chlins** [comment]
Could you describe your issue clearly?

**Comment by zyyw** [comment]
It seems that the "Proxy Cache Endpoint" cannot be updated/edited. I'm wondering why not create a new project as Proxy Cache with the new endpoint you like.

**Comment by eliasp** [comment]
Having to re-create a project to use a different endpoint means:
- to lose all the already cached images
- having to re-configure all the aspects of the corresponding project etc.
- causing a downtime for users of the existing project until the replacement project is up & running again under the same name

Sure, there might be technical reasons under the hood (e.g. the cache validation is potentially tied to the configured endpoint) for it being the way it is - from a user's PoV it's quite cumbersome.
