### ISSUE TITLE
artifact_blob never deleted

### ISSUE THREAD

**Issue by sundaykeke** [goharbor/harbor#17857]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

table artifact_blob never deleted.
now there are 70,000,000 rows in this table .
Delete artifacts takes 1 min

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
Have you ever run garbage collection on your harbor?

**Comment by jiaweizhou** [comment]
@chlins garbage collection does not clean this table too. And we do not find any code that will deleting data in table `artifact_blob`.  A

**Comment by alexanderdalloz** [comment]
I share the same issue. Garbage collection does not remove the leftover records.

```
harbor_1=# select count(*) from artifact;
 count
-------
    30
(1 row)

harbor_1=# select count(*) from artifact_blob;
  count
---------
 4173031
(1 row)
```
