### ISSUE TITLE
Error response from daemon: unknown: artifact, after upgraded harbor to v2.6.2

### ISSUE THREAD

**Issue by Jelly-Fisher-fish** [goharbor/harbor#17852]
**harbor upgraded from v2.0 to v2.6.2**

It failed to pull some artifacts with error response unknown: artifact

But i actually found it from db and web ui

What went wrong with `docker pull`

> Error response from daemon: unknown: artifact projectname/imagename:v3-centosrepo_cve_fix not found

![image](https://user-images.githubusercontent.com/105407327/203716995-22732bd2-2aa0-4be0-a49f-d980a44fa8e5.png)

What went wrong with `ctr image pull`

> ctr: failed to resolve reference "xxx/projectname/imagename:v3-centosrepo_cve_fix": xxx/projectname/imagename:v3-centosrepo_cve_fix: not found

![image](https://user-images.githubusercontent.com/105407327/203717224-e2733b4b-1277-4aea-91c3-431c8c7d47a3.png)

Data in db

![image](https://user-images.githubusercontent.com/105407327/203717456-72d37b6a-f0c1-4ce6-8e36-a7e1f3111e70.png)

Data in web ui

<img width="583" alt="image" src="https://user-images.githubusercontent.com/105407327/203717877-57c74413-0636-4a98-a6e5-53b634b5cde6.png">

And it can pull with digest

![image](https://user-images.githubusercontent.com/105407327/203717602-617bf53d-efdf-48bd-a68b-0fdd71624ba4.png)

**Comment by chlins** [comment]
Could you try to execute the sql `select * from repository where name like 'projectName/imageName'`?

**Comment by chlins** [comment]
Maybe related with https://github.com/goharbor/harbor/issues/17544

**Comment by Jelly-Fisher-fish** [comment]
> Maybe related with #17544

I tried once before created this issue, and only one repository as the result.

> select * from repository where name like 'projectName/imageName';

![image](https://user-images.githubusercontent.com/105407327/204195544-d219a4ea-d74c-401f-bf64-e342e00dccb1.png)

**Comment by chlins** [comment]
Could you try to do this workaround https://github.com/goharbor/harbor/issues/17544#issuecomment-1257385150?

**Comment by Jelly-Fisher-fish** [comment]
> Could you try to do this workaround [#17544 (comment)](https://github.com/goharbor/harbor/issues/17544#issuecomment-1257385150)?

Step 1. Backup data
Step 2. > docker run --rm firstfloor/before_reindex:latest --dburl=postgres://postgres:root123@localhost:5432/registry --command=list
Response with > No duplicate repository name found!
Do I need to try step 3?

**Comment by Jelly-Fisher-fish** [comment]
Maybe I can just run step 3 and 4 to fix it.
Now my problem is solved
Thanks for a lot
