### ISSUE TITLE
Endpoint Creation: Provider HelmHub missing

### ISSUE THREAD

**Issue by joeltraber** [goharbor/harbor#17858]
The provider option "helm hub" in the UI for creating an endpoint is missing. 

**Expected behavior and actual behavior:**
Missing option in UI (see attachment)

**Steps to reproduce the problem:**
Unclear how we got the instance to that point. not sure if the option in that instance was ever available.
Click through the UI to create a new endpoint to replicate a helm repo.

**Versions:**

- harbor version: v2.6.0-b035ca7c
- docker engine version: [20.10.12]
- docker-compose version: [1.29.2]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
![harbor](https://user-images.githubusercontent.com/5963149/203838596-1ef89a59-d6f2-4018-98b3-1732da9d56f1.png)
[harbor.yml.txt](https://github.com/goharbor/harbor/files/10086515/harbor.yml.txt)

**Comment by AllForNothing** [comment]
Duplicated with #13244
@chlins Please consider remove  it  from adapters  API

**Comment by chlins** [comment]
As the deprecation of chart museum, all related code and components about chart museum will be removed in the harbor v2.8, track by https://github.com/goharbor/harbor/issues/17958.
