### ISSUE TITLE
"Pending Jobs In Queues" says total of 0, while there is on-going replication job in progress

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#17869]
Step to reproduce:
1. create a replication rule like below
<img width="637" alt="Screen Shot 2022-11-25 at 18 06 53" src="https://user-images.githubusercontent.com/6709992/203959216-a761942d-ec5d-4d5e-8ce0-43b020c3b8f4.png">

2. "Replicate" this rule triggered manually and it says in-progress
<img width="1789" alt="Screen Shot 2022-11-25 at 18 06 08" src="https://user-images.githubusercontent.com/6709992/203958197-0d9c1b80-df6a-45fc-9156-7fd293f5f4b8.png">

3. while in "Pending Jobs In Queues", it says total of 0.
<img width="1766" alt="Screen Shot 2022-11-25 at 18 05 46" src="https://user-images.githubusercontent.com/6709992/203958397-c6504823-28ab-48d0-92f8-de40d71c6b18.png">

**Comment by stonezdj** [comment]
From the worker panel dashboard, we could see there is a task in the running state.
