### ISSUE TITLE
Job Service Dashboard RETENTION and P2P_PREHEAT and REPLICATION Schedule is displayed incorrectly

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17868]
<img width="1302" alt="图片" src="https://user-images.githubusercontent.com/72076317/203929599-f9141b07-51ad-480c-af1e-e244e98d97fc.png">

<img width="578" alt="图片" src="https://user-images.githubusercontent.com/72076317/203944586-3607b622-268c-483e-8290-19e6f79617dc.png">

<img width="624" alt="图片" src="https://user-images.githubusercontent.com/72076317/203944699-51351ce2-bace-49d5-a075-bb7cf16393c7.png">

<img width="1399" alt="图片" src="https://user-images.githubusercontent.com/72076317/203944471-2552de9c-8074-4e4a-904c-2e1ddf0f4434.png">

**Versions:**
Please specify the versions of following systems.

- harbor version:v2.7.0-619747fc

**Comment by stonezdj** [comment]
For different job type, their implementation is different, not all parameter are stored in extra attribute

**Comment by AllForNothing** [comment]
As discussed, we should remove `Cron Type` and `Extra Atrribute` columns
