### ISSUE TITLE
Job Service Dashboard job queues page does not automatically refresh data

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17863]
**Steps to reproduce the problem:**
latency does not increase with time

<img width="1662" alt="图片" src="https://user-images.githubusercontent.com/72076317/203915612-68163fc3-3e98-4481-aec7-4341444c94df.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.7.0-619747fc

**Comment by zyyw** [comment]
It seems that we need to refresh the page to see the `latency` increasing over time.
