### ISSUE TITLE
Replication is not supported for registry.redhat.io  

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17865]
Can not create a replication rule for registry.redhat.io  because it reports a 404 error when getting the registry info of  "https://registry.redhat.io".

Steps to reproduce:

1. Create a RedHat registry with endpoint `https://registry.redhat.io` in `Harbor` type
2. Go to the Replication page then try to new a replication rule,  check pull-mode, and select the RedHat registry
3. The registry info API will report a 404 error
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/30999793/203918019-7649a666-bd2a-40cc-a86d-292f0432fa80.png">

**Comment by stonezdj** [comment]
Because there is no registry type for registry.redhat.io,  create a registry with Harbor registry, when testing replication, it will try to access some Harbor-specific API, and the registry.redhat.io doesn't have this APIs. which is why it fails. it works as designed.
