### ISSUE TITLE
The pending count is inconsistent in the jobservice dashboard page.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#17864]
How can we help you?

The pending count in the jobservice dashboard is inconsistent, the data in the summary table is different with the detail table.

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/31262637/203917587-d841ebf4-5fe2-41c3-b6f1-852d04420c10.png">

**Comment by AllForNothing** [comment]
same issue with #17863
