### ISSUE TITLE
The jobservice dashboard data inconsistent with tasks.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#17861]
How can we help you?

The data shown in the jobservice dashboard is no pending jobs or tasks, but from the retention pages, many tasks are in the state of pending.

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/31262637/203911424-7fe4ed2a-509f-453a-916b-988b6ca26036.png">

<img width="1587" alt="image" src="https://user-images.githubusercontent.com/31262637/203911498-9e298686-c607-4a07-bc7a-dc4db416a4fe.png">

**Comment by stonezdj** [comment]
It seems that the job service already complete the work but it is updating the task status in the database. because there are 10000 tasks, to update their status might take a long time in the background. confirm with chlins, their final status is consistent.
