### ISSUE TITLE
Set the job to PAUSE to trigger the job, and the job status is not correctly displayed as pending

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17871]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: Set the job to PAUSE to trigger the job, and the job status is pending
Actual: Set the job to PAUSE to trigger the job, and the job status is not pending

**Steps to reproduce the problem:**
1. Set all jobs to PAUSE
2. Trigger GC job, GC job status is Running not Pending
<img width="1387" alt="图片" src="https://user-images.githubusercontent.com/72076317/203946282-5ed1fe60-ffdd-4a17-8a53-18e7fdeaf864.png">
3. Trigger PURGE_AUDIT job, PURGE_AUDIT job status is Running not Pending
<img width="1418" alt="图片" src="https://user-images.githubusercontent.com/72076317/203946863-a007a2f4-f01f-40cb-96b7-f4b8f91aeb56.png">
4. Trigger P2P_PREHEAT job, P2P_PREHEAT job status is Running not Pending
<img width="1376" alt="图片" src="https://user-images.githubusercontent.com/72076317/203949457-0cb5de83-6c28-4fa3-bc53-3462c1086dd4.png">
5. Trigger REPLICATION job, REPLICATION job status is InProgress not Pending
<img width="1409" alt="图片" src="https://user-images.githubusercontent.com/72076317/203950042-963bd2b6-a325-4278-9921-1719a37a8670.png">
6. Trigger RETENTION job, RETENTION job status is Running not Pending
<img width="1376" alt="图片" src="https://user-images.githubusercontent.com/72076317/203950770-eae0ede1-45a3-4c7c-b2ab-b478d83b3e2f.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.7.0-619747fc

**Comment by stonezdj** [comment]
The pause/resume operation just stop the worker from executing the job of specific job type, doesn't change the current job status.

**Comment by stonezdj** [comment]
work as design
