### ISSUE TITLE
After pausing scan_data_export, the export cve event keeps loading.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#17879]
Pause the scan_data_export in the jobservice dashboard.
Select one project to export cve.

![image](https://user-images.githubusercontent.com/2841473/204180910-0f3ea507-2d9a-4bad-b033-b22487ec55c5.png)

**Comment by AllForNothing** [comment]
@wy65701436 @chlins @stonezdj Need further discussion on this. Remove it from  2.7

**Comment by AllForNothing** [comment]
As discussed, we need to add a timeout to this.
