### ISSUE TITLE
Harbor Exporter Metrics on Replication tasks 

### ISSUE THREAD

**Issue by yuangeqingian** [goharbor/harbor#17876]
I would like to collect harbor metrics using harbor exporters.
I checked from harbor official document that it only has metrics about 3 harbor components:
https://goharbor.io/docs/2.2.0/administration/metrics
![image](https://user-images.githubusercontent.com/9658083/204098966-e0efc4e5-dc29-4476-93e2-9f65f7bea393.png)

If I want to get metrics about Replication tasks details in Harbor, 

does the harbor exporter metrics support this?

**Comment by chlins** [comment]
I think you could upgrade your harbor, since v2.3, it exposes some task related metrics such as `harbor_jobservice_task_total`, `harbor_jobservice_task_process_time_seconds `, please refer to https://goharbor.io/docs/2.3.0/administration/metrics/ for details.

**Comment by yuangeqingian** [comment]
Thanks a lot for your quick response!

 I am running harbor 2.6 now, I can see the support monitor components:
![image](https://user-images.githubusercontent.com/9658083/204217474-416782ca-b150-40ca-9de5-20a751a5add2.png)

However, only three metrics supported below:
harbor_jobservice_task_process_time_seconds
harbor_jobservice_task_total
harbor_jobservice_info

For instance, I wish to get replication task status like repo name, trigger type, execution succeed or failure.
Will that be provided in future harbor releases like harbor 2.7.0?

**Comment by chlins** [comment]
@yuangeqingian Hi, let's discuss the metrics you needed  [here](https://github.com/goharbor/harbor/discussions/17806).
