### ISSUE TITLE
Job Service Dashboard Job Queues Stop job Cannot sync job status

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17873]
Stop job in Job Queues can not sync the job status, the job status is still Running or InProgress, not Stopped
Contains the type of job: [GC, P2P_PREHEAT, PURGE_AUDIT, REPLICATION, RETENTION]

**Steps to reproduce the problem:**
1. Set all jobs to PAUSE
2. Trigger job and stop the job in Job Queues
3. Job status is still Running not Stopped

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.7.0-619747fc

**Comment by stonezdj** [comment]
duplicated with #17861
