### ISSUE TITLE
The "FREE" button of "Workers" under Job Service Dashboard works only occasionally

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#17872]
Problem description:
it seems that the `FREE` button doesn't work sometimes. User has to wait for a few seconds/minutes and then  click `FREE` and then it frees up the worker instances.
<img width="1780" alt="Screen Shot 2022-11-25 at 18 38 26" src="https://user-images.githubusercontent.com/6709992/203965992-f1fc6631-a157-48e6-a574-eff23154a79a.png">

**Comment by stonezdj** [comment]
The Free operation actually calls the function of stop running task, it might take some minutes varying to job type.

**Comment by stonezdj** [comment]
Work as design
