### ISSUE TITLE
Random blob upload unknown on docker push

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#17898]
**Expected behavior and actual behavior:**
We have jenkins job which builds and push a lot of images to our Harbor registry. We are on version 2.5.1 and we discovered, that in our job, there are random failures when pushing docker images to our harbor project. 
In jenkins, we have something like this:
```
[2022-11-30T17:34:06.289Z] 25a7d722ac72: Pushed
[2022-11-30T17:34:07.847Z] blob upload unknown
```
And our jobs fails. I checked harbor logs and discovered that there are such errors in registry pod (blob unknown to registry):
```
time="2022-11-30T17:33:51.859767297Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3 err.message="blob unknown to registry" go.version=go1.15 http.request.host=our-hostname.com http.request.id=965a8ab5-b6f8-420a-901d-ab1e06ef4c10 http.request.method=HEAD http.request.remoteaddr=172.17.110.192 http.request.uri="/v2/some-project/some-repository/blobs/sha256:5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3" http.request.useragent="docker/20.10.8 go/go1.16.6 git-commit/75249d8 kernel/5.10.102.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.8 \(windows\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=98.628283ms http.response.status=404 http.response.written=157 vars.digest="sha256:5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3" vars.name="some-project/some-repository" 
```

In harbor core, there are such logs:
```
2022-11-30T17:33:52Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 7891395db83070a74f8f2ec3e6f5eb00 to the logger for the request POST /v2/some-project/some-repository/blobs/uploads/
2022-11-30T17:33:52Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/some-project/some-repository/blobs/uploads/?from=some-project-with-other-repository&mount=sha256%3A5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3
2022-11-30T17:33:52Z [DEBUG] [/server/middleware/quota/quota.go:102][action="request" middleware="quota" requestID="7891395db83070a74f8f2ec3e6f5eb00" url="/v2/some-project/some-repository/blobs/uploads/"]: no resources request for this http request, so direct to next handler
```

**Steps to reproduce the problem:**
Issue occurs randomly. We run a job a couple of times to just push images and they occurred on different repositories. As a workaround we can run such job multiple times until all layers are pushed but this should not work in such way.

These images share a lot of layers with other images, also from other repositories. I'm not sure if I read this log correctly, but it looks like app tried to use layer from other repository and failed. We have two replicas for each pod, so maybe this may be causing this issue.

**Versions:**
- harbor version: 2.5.1
- helm chart: bitnami/harbor 14.0.2
- kubernetes: Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+IKS", GitCommit:"acd6e017f238295f63fbb1aa691e7219a23257b6", GitTreeState:"clean", BuildDate:"2022-11-10T21:01:38Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

**Additional context:**
- more logs from registry pod: [registry-error.txt](https://github.com/goharbor/harbor/files/10131135/registry-error.txt)
- more logs from jenkins job, which is running on windows machine: [jenkins-job.txt](https://github.com/goharbor/harbor/files/10131153/jenkins-job.txt)

There was similar issue reported to helm chart github by I think that this issue is related to the harbor itself (we also use bitnami Helm Chart instead of official one and we had that error): https://github.com/goharbor/harbor-helm/issues/839

**Comment by wy65701436** [comment]
what's your storage? for the failure blob, is it possible to view it in your storage?

**Comment by jowko** [comment]
Hello @wy65701436. We use IBM Cloud Object Storage. We have a PVC attached to Harbor which integrates with this IBM COS.
We can view what objects are in our storage and I searched for mentioned sha256 there (from logs above) and found such things (we can only search by prefix):
- docker/registry/v2/blobs/sha256/5f/5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3 - this has 0KB, probably directory
- docker/registry/v2/blobs/sha256/5f/5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3/data - this has 5.5kB

These objects were created about 17:12, an jenkins failure for this sha256 is from 17:34. This jenkins job pulls images from one repository, retags them and push to another. These issues looks random, since after a few jobs rerun we managed to push all layers (on each failure, issue occurred on other layer).

**Comment by wy65701436** [comment]
did you see the link file `/docker/registry/v2/repositories/some-project/some-repository/_layers/sha256/5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3/link` in your storage?

**Comment by jowko** [comment]
@wy65701436 I see such entries:
```
docker/registry/v2/repositories/some-project/some-repository/_layers/sha256/5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3/link
docker/registry/v2/repositories/some-project/some-other-project/_layers/sha256/b35265750914cc934d2d6baf1e43b39fb3c8c48609df2db4bcf93254789a9aa8/link
```
Both these files have 71 bytes. But this is current state. It is possible that these files were missing when job failed.

The first link was created at 2022-11-30 6:25 PM and the second was created at 2022-11-30 6:33 PM. 
This file:
```
docker/registry/v2/blobs/sha256/5f/5f1b3fcc79d53ab709b4b5a6ce5e1158dcdf62ee79fe57aaff33872c68d1e3b3
```
Was created at 2022-11-30 6:12 PM.

I see that such error occurred again but our users just rerun pipeline job and it succeeded next time.

Do you need any additional information? If we want to check it again when job will fail, I can ask user to not rerun job immediately but we need to know what we should check in advance because we should do rerun as quickly as we can to not block users.

**Comment by jowko** [comment]
Issue was not resolved.

**Comment by jowko** [comment]
Issue was not resolved.

**Comment by ZackCai** [comment]
facing the same question. 
After this, push of some layers failed. Keep retrying until client returns 500.  
registry.log shows: unable to delete layer upload resources "_uploads/some_upload_dir" filesystem: unlinkat some_upload_dir/hashstates/sha256/ directory not empty.
harbor version: 1.10.3
storage: local nfs

**Comment by jowko** [comment]
I think that issue may be still relevant.

**Comment by ZackCai** [comment]
Solved here.
In my case, it's not harbor itself causing this issue. Turns out that there's a security related process occupying the .nfs file and stops the harbor from deleting uploads tmp files. This stops a success image push. 
Please check for process occupation or nfs related reasons.
