### ISSUE TITLE
increase the limit on the number of wrong passwords

### ISSUE THREAD

**Issue by yingjunxu** [goharbor/harbor#17896]
you need to increase the limit on the number of wrong passwords,if there are too many wrong login passwords.
Secure symmetric encryption algorithm, such as AES (128, 192, 256 bits), and must ensure that the client key is safe and cannot be cracked or read; asymmetric encryption algorithm, such as RSA (not less than 1024 bits), SM2, etc.

**Comment by chlins** [comment]
Could you clarify your issue?
