### ISSUE TITLE
Replication locked during 15 minutes 

### ISSUE THREAD

**Issue by mbrizbee** [goharbor/harbor#17900]
**Actual behavior**

Replication task is randomly locked during more than 15 minutes. For example : [lock-1.txt](https://github.com/goharbor/harbor/files/10134737/lock-1.txt)
`2022-11-29T15:25:22Z  pulling the manifest of image xxxxx`
`2022-11-29T15:25:22Z the manifest of image xxxxxx pulled`
`2022-11-29T15:40:22Z copying the blob sha256:1b865068681de5b4ed7cfcc9830...`

-> locked between 15:25:22 and 15:40:22 (15 minutes)

Or this replication task : [lock-2.txt](https://github.com/goharbor/harbor/files/10134744/lock-2.txt)
`2022-11-29T14:54:57Z  pulling the manifest of image xxxxx`
`2022-11-29T14:54:57Z  the manifest of image xxxx pulled`
`2022-11-29T16:09:57Z  the image xxxx already exists on the destination registry, skip`

-> locked between 14:54:57 and 16:09:57 (1h15min)

**Version**
Version v1.10.1-f3e11715

**Comment by chlins** [comment]
The version v1.10 is too old which is out of support, could you try to upgrade to the latest version?

**Comment by mbrizbee** [comment]
The latest version works fine, no more issue on replication action at this moment. 
Thank for your help @chlins
