### ISSUE TITLE
Harbor replication pattern matching

### ISSUE THREAD

**Issue by yuangeqingian** [goharbor/harbor#17901]
Harbor replication task to mirror ACR to Harbor
I have two docker image in ACR:   aea-axx,aea-bxx,aea-cxx,aea-dxx .....
I wish to not mirror image: aea-bxx
Can we do that using harbor replication pattern matching?

I checked harbor Official document, it only supports below feature:

![image](https://user-images.githubusercontent.com/9658083/205159619-ec8727a3-f7a5-4a4e-bd3a-f26ab3d9bcde.png)

Does it support some other pattern matching like to exclude certain character?

**Comment by chlins** [comment]
For the filter decoration, you can choose `matching` or `excluding`, but the underlying library `doublestar` maybe not support write the match and exclude in the one pattern, so currently harbor can not support that.

**Comment by chlins** [comment]
The name filter does not support matching or excluding option, you could explore the https://github.com/bmatcuk/doublestar docs to fetch more pattern details.

**Comment by chlins** [comment]
Harbor depends on the https://github.com/bmatcuk/doublestar to implement filter, so only the package support your scenario, that harbor can support.

**Comment by yuangeqingian** [comment]
> Harbor depends on the https://github.com/bmatcuk/doublestar to implement filter, so only the package support your scenario, that harbor can support.

Suppose I have three docker images: 
har
harbor
harbor/test
I want to pattern matching them all.

Any suggestion on how to write the pattern matching?
har*/**/ didn't work as expected, it can only mirror: harbor/test


![image](https://user-images.githubusercontent.com/9658083/205595804-765a3016-96ce-4637-9380-a71d10444cce.png)




In document, /**/ can match 0 or more directories, but in real, it didn't work as expected.
