### ISSUE TITLE
Docker Push large image(12G)，One of the mirroring layers is 8G, report an error: Upload failed, retrying: blob upload unknown

### ISSUE THREAD

**Issue by AlexFly666** [goharbor/harbor#17908]
**Env Info**
Harbor deploy : docker-compose
Harbor version: 2.2.2
Dokcer version: 19.03.12
docker-compose version: 1.28.6

**And Use the public network certificate and the public network domain name，before harbor is not have a nginx**

**Error Info**

12月 01 10:38:50 gv226 dockerd[77278]: time="2022-12-01T10:38:50.866413795+08:00" level=error msg="Upload failed, retrying: blob upload unknown"

12月 01 10:39:22 gv226 dockerd[77278]: time="2022-12-01T10:39:22.088947282+08:00" level=error msg="Upload failed, retrying: blob upload unknown"

**Other**

Push large image, One of the mirroring layers is less than  4G,  push successfully

**Comment by Fly0905** [comment]
**Harbor log** 
# nginx日志
Dec  1 10:38:50 192.168.160.1 proxy[114482]: 123.235.52.27 - "PATCH /v2/dcu/admin/base/vscode-pytorch/blobs/uploads/72b13ade-f72d-40fa-9e07-8b1ef442c43b?_state=WpSIqFD7DGMgSIfJ2B2PQY5Caz96_NKUwx_3qyQUmsN7Ik5hbWUiOiJkY3UvYWRtaW4vYmFzZS92c2NvZGUtcHl0b3JjaCIsIlVVSUQiOiI3MmIxM2FkZS1mNzJkLTQwZmEtOWUwNy04YjFlZjQ0MmM0M2IiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjItMTItMDFUMDI6MjU6MDcuOTU5Njc1MzA5WiJ9 HTTP/1.1" 202 0 "-" "docker/19.03.9 go/go1.13.10 git-commit/9d988398e7 kernel/3.10.0-1160.42.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.9 \x5C(linux\x5C))" 822.115 822.003 .
Dec  1 10:38:50 192.168.160.1 proxy[114482]: 123.235.52.27 - "PUT /v2/dcu/admin/base/vscode-pytorch/blobs/uploads/72b13ade-f72d-40fa-9e07-8b1ef442c43b?_state=WWaoUfdQZtfbn9GuecVmTdAJsW5oCg8EkNryMRK86oV7Ik5hbWUiOiJkY3UvYWRtaW4vYmFzZS92c2NvZGUtcHl0b3JjaCIsIlVVSUQiOiI3MmIxM2FkZS1mNzJkLTQwZmEtOWUwNy04YjFlZjQ0MmM0M2IiLCJPZmZzZXQiOjQwMjM3MTE2LCJTdGFydGVkQXQiOiIyMDIyLTEyLTAxVDAyOjI1OjA3WiJ9&digest=sha256%3A7eea96517d46a6609b277dadade6e50a6bf3370590d49408db4b23206534b69b HTTP/1.1" 404 76 "-" "docker/19.03.9 go/go1.13.10 git-commit/9d988398e7 kernel/3.10.0-1160.42.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.9 \x5C(linux\x5C))" 0.017 0.017 .


# registry日志
Dec  1 10:38:50 192.168.160.1 registry[114482]: time="2022-12-01T02:38:50.858597289Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob upload invalid" err.message="blob upload invalid" go.version=go1.15.6 http.request.host="image.sourcefind.cn:5000" http.request.id=0bf94f97-2386-45ba-a363-aa3932b15a1c http.request.method=PUT http.request.remoteaddr=123.235.52.27 http.request.uri="/v2/dcu/admin/base/vscode-pytorch/blobs/uploads/72b13ade-f72d-40fa-9e07-8b1ef442c43b?_state=WWaoUfdQZtfbn9GuecVmTdAJsW5oCg8EkNryMRK86oV7Ik5hbWUiOiJkY3UvYWRtaW4vYmFzZS92c2NvZGUtcHl0b3JjaCIsIlVVSUQiOiI3MmIxM2FkZS1mNzJkLTQwZmEtOWUwNy04YjFlZjQ0MmM0M2IiLCJPZmZzZXQiOjQwMjM3MTE2LCJTdGFydGVkQXQiOiIyMDIyLTEyLTAxVDAyOjI1OjA3WiJ9&digest=sha256%3A7eea96517d46a6609b277dadade6e50a6bf3370590d49408db4b23206534b69b" http.request.useragent="docker/19.03.9 go/go1.13.10 git-commit/9d988398e7 kernel/3.10.0-1160.42.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.9 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=5.873535ms http.response.status=404 http.response.written=76 vars.name="dcu/admin/base/vscode-pytorch" vars.uuid=72b13ade-f72d-40fa-9e07-8b1ef442c43b 

Dec  1 10:38:50 192.168.160.1 registry[114482]: 192.168.160.7 - - [01/Dec/2022:02:38:50 +0000] "PUT /v2/dcu/admin/base/vscode-pytorch/blobs/uploads/72b13ade-f72d-40fa-9e07-8b1ef442c43b?_state=WWaoUfdQZtfbn9GuecVmTdAJsW5oCg8EkNryMRK86oV7Ik5hbWUiOiJkY3UvYWRtaW4vYmFzZS92c2NvZGUtcHl0b3JjaCIsIlVVSUQiOiI3MmIxM2FkZS1mNzJkLTQwZmEtOWUwNy04YjFlZjQ0MmM0M2IiLCJPZmZzZXQiOjQwMjM3MTE2LCJTdGFydGVkQXQiOiIyMDIyLTEyLTAxVDAyOjI1OjA3WiJ9&digest=sha256%3A7eea96517d46a6609b277dadade6e50a6bf3370590d49408db4b23206534b69b HTTP/1.1" 404 76 "" "docker/19.03.9 go/go1.13.10 git-commit/9d988398e7 kernel/3.10.0-1160.42.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.9 \\(linux\\))"

**Comment by stonezdj** [comment]
There is no limitation for the blob size.  it is possible that the network timeout when pushing the blob to the registry. because the common/config/nginx/nginx.conf defines the timeout as 900s by default.
```
    location /v2/ {
      proxy_pass http://core/v2/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
      proxy_buffering off;
      proxy_request_buffering off;
      proxy_send_timeout 900;
      proxy_read_timeout 900;
    }
```

You could adjust this value and verify it.

**Comment by Fly0905** [comment]
tanks,  network is important
