### ISSUE TITLE
 Add a maximum length limit to the robot account secrets

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17923]
Currently,  we have no maximum length limit defined in the backend code.

`if len(secret) >= 8 && hasLower.MatchString(secret) && hasUpper.MatchString(secret) && hasNumber.MatchString(secret) {
   return true
}`

if the secret length is bigger than the Database specified, `secret        | character varying(2048)`, it will report an error.

So we should consider adding a maximum length limit to the robot account secrets to align with the UI  `attern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,128}$"`

**Comment by zyyw** [comment]
this should be resolved by this PR:
* https://github.com/goharbor/harbor/pull/18916

Closing it now.
