### ISSUE TITLE
Job Service Dashboard Worker Pools page field filter issue

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17920]
**Steps to reproduce the problem:**
1. Go into Job Service Dashboard page
<img width="1677" alt="图片" src="https://user-images.githubusercontent.com/72076317/205849027-3e38f59e-0ceb-4857-8c34-bbe36c0184c5.png">
<img width="1675" alt="图片" src="https://user-images.githubusercontent.com/72076317/205848967-131800c9-8573-445b-b765-9ad4adddea97.png">
The following Workers are not displayed

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.7.0-ded7f0d0

**Comment by YangJiao0817** [comment]
@AllForNothing  Maybe we should remove the filter for these fields.
![图片](https://user-images.githubusercontent.com/72076317/205850722-18ea3734-0af9-4e42-b7b0-c4b536cbeba3.png)

**Comment by AllForNothing** [comment]
Seems an issue for Clarity. Remove the 2.7 label.

**Comment by AllForNothing** [comment]
It's the same issue with #17935
