### ISSUE TITLE
http: TLS handshake error

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17924]
**Steps to reproduce the problem:**
1. enable internal_tls
2. Select multiple images to scan
<img width="1420" alt="图片" src="https://user-images.githubusercontent.com/72076317/205868467-38a1dad3-ce51-4143-8fa2-4641acd560b7.png">
Report error in core.log

`[1;37m[M]#033[0m [log.go:208]  [HTTP] http: TLS handshake error from 172.26.0.10:41506: EOF`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.7.0-rc1, v2.6.2

**Additional context:**
[core.log](https://github.com/goharbor/harbor/files/10164579/core.log)

**Comment by wy65701436** [comment]
The EOF errors seems be caused by a Go bug https://github.com/golang/go/issues/50984 and appear on Harbor v2.3.0+.

And no functional issues releated to these error messages. At the moment, we won't do anything but wait for the upstream to fix this.
