### ISSUE TITLE
Unexpected behavior for proxy cache

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17933]
A wrong message is reported in core.log when pulling a cached image from a proxy cache project:
`2022-12-06T10:05:58Z [WARNING] [/server/middleware/repoproxy/proxy.go:197]: Artifact: proxy_dockerhub/library/redis:latest, digest: is not found in proxy cache, fetch it from remote repo`

Steps to reproduce:

     - Create a registry  for Dockerhub with username and password
     - Create a private proxy cache for this registry named dockerhub_proxy
     - Pull an image with username and password without project name
     - Verify the image could pull and the image is cached in proxy cache project after 15 minutes
     - Pull the image again then the wrong message is reported in core.log

version: 2.7

**Comment by stonezdj** [comment]
It is inaccurate log information, actually it just head the manifest in the remote server to check if the digest change, it doesn't pull the content from remote server.
