### ISSUE TITLE
OIDC session logout after specific time?

### ISSUE THREAD

**Issue by rgarcia89** [goharbor/harbor#17961]
**Expected behavior and actual behavior:**
We use OIDC as authentication provider to authenticate users against Harbor. So far everything works great. Users can log in and get permissions on different projects using the transferred group. What doesn't work well is obviously the OIDC session refresh. Thus, the session expires after X minutes of inactivity on the web interface. I can't find anything about this in the logs. Only the following message I could get via the developer tools on the web browser. Strange thing here - the users use the same IAM for other software, like Grafana or Kibana. On none of these applications we can observe the behavior we see with Harbor. Any idea why this could be happening?

![image](https://user-images.githubusercontent.com/4134730/206453188-1d8a6128-13f2-439c-aa08-68c15db5daba.png)

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.6.2
- helm chart version: 1.10.2

**Comment by Vad1mo** [comment]
@goharbor/maintainers, I think we need to investigate that, I have experienced the same situation
.

**Comment by rgarcia89** [comment]
Any update here?

**Comment by rgarcia89** [comment]
Can be changed in Configuration - System Settings - Session Timeout (Minutes).
Fine for me
