### ISSUE TITLE
Replication question for many projects and repl sites

### ISSUE THREAD

**Issue by tdk-github** [goharbor/harbor#17992]
Hello. Best practice question :
- have 5 replication sites
- have 30 projects, all using event-based replication rule

Is it best practice to create 5 single replication rules for each site or better to create a replication rule for each project, for each site? On paper, 5 rules seems better than 150 but do not understand how replication jobs work. If you have 150 rules, is it possible that 150 jobs try to run (possibly) at the same time?

**Comment by chlins** [comment]
Replied in https://cloud-native.slack.com/archives/CC1E09J6S/p1670975278907169
