### ISSUE TITLE
OIDC Groups are parsed as single string instead of array

### ISSUE THREAD

**Issue by mway-niels** [goharbor/harbor#17998]
We set up Harbor to authenticate users using our OIDC provider (Azure). The authentication itself is working as expected, we're only facing an issue when trying to synchronise groups.

The following ID token is returned by Azure:
```
{
  "aud": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "iss": "https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/v2.0",
  "iat": 1671080134,
  "nbf": 1671080134,
  "exp": 1671084034,
  "email": "john.doe@acme.com",
  "groups": [
    "1XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "2XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  ],
  "rh": "XXXXX",
  "sub": "XXXXX",
  "tid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "uti": "XXXXX",
  "ver": "2.0"
}
```

When this user logs into Harbor using the OIDC provider he is authenticated successfully and can see the landing page.
When logging in as the local administrator we found that Harbor is indeed creating a group based on the "groups" claim. However we expected it would create three groups, one for each entry in the array.

What we're seeing:
<img width="2991" alt="Screenshot 2022-12-15 at 13 14 00" src="https://user-images.githubusercontent.com/53857383/207786354-cebf4964-6e81-4822-b0cb-b6aea9d88e33.png">

What we expected:
<img width="2998" alt="Screenshot 2022-12-15 at 13 15 17" src="https://user-images.githubusercontent.com/53857383/207786540-d21223e6-e6da-4337-a473-23bce0c789a8.png">

Are we missing some configuration to make the automatic group assignments work?

**Comment by mway-niels** [comment]
Some log output when the user is trying to log in. We have since changed the Azure configuration to include all security groups the user is a member of in the ID token.

```
2022-12-15T06:56:19Z [WARNING] [/pkg/usergroup/manager.go:89]: failed to onboard user group {ID:0 GroupName:["1XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","2XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","4XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","5XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","6XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","7XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","8XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","9XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"] GroupType:3 LdapGroupDN:}, error ERROR: value too long for type character varying(255) (SQLSTATE 22001), continue with other user groups
```

**Comment by wouter2397** [comment]
I'm currently testing OIDC in Harbor aswell. We use KeyCloak instead of Azure but if I add a user to multiple groups and authenticate the seperate groups are created. So looks like this is something specific to Azure.

Unfortunatly in my current setup I'm unable to catch the incomming request containing the id token...

**Comment by mway-niels** [comment]
I was able to capture a valid ID token using the following procedure (unfortunately, AFAIK, Azure doesn't provide an easy way to debug tokens and claims returned by your OIDC/OAuth2 applications):
1. Configure OIDC in Harbor (& test that users can be authenticated)
2. Install Proxyman (or a comparable solution)
3. Install Postman (or use cURL/a comparable solution)
4. Set up Proxyman to enable intercepting requests on your local machine
5. Set up a breakpoint rule for https://\<HOSTNAME\>/c/oidc/callback, ANY method, breakpoint on request
6. Log in to Harbor using OIDC on your machine
7. Proxyman should intercept the request and allow you to inspect the query parameters
8. Copy the code parameter
9. Use Postman to send a request to the OAuth2 token endpoint (ex. https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret)

There may be easier ways to achieve this, for example by running a mock backend, allowing localhost in the app registration and calling the /authorize endpoint but I haven't tested those yet. Although the procedure described above is quite intricate and has a lot of steps, once set up it works reliably well to debug OIDC/OAuth2 tokens for any application.

**Comment by mway-niels** [comment]
After debugging some more it seems like the issue originates in the [userInfoFromRemote](https://github.com/goharbor/harbor/blob/d87d906c84b5f47029ed5137dc2bc1bc009050f4/src/pkg/oidc/helper.go#L321) function. I was able to verify that the groups in the [UserInfoFromIDToken](https://github.com/goharbor/harbor/blob/d87d906c84b5f47029ed5137dc2bc1bc009050f4/src/pkg/oidc/helper.go#L335) function **are parsed correctly**.

The group claim in the token returned by the remote endpoint is parsed like this:
```
map[amr:["pwd","mfa"] family_name:Doe given_name:John groups:[["1XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", "2XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX", "3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"]] ipaddr:X.X.X.X name:John Doe oid:XXXXX rh:XXXXX. sub:XXXXX tid:XXXXX unique_name:john@doe.com upn:john@doe.com uti:XXX ver:1.0]
```

Notice that the "groups" claim is effectively a 2 dimensional array. This at least explains why it's only trying to save a single group with a group name containing all group IDs as a string array to the database.

I am however not entirely sure where the 2D array is coming from (and why there isn't a type error thrown anywhere). When logging the ID token received by the userInfoFromRemote function and b64 decoding it, the groups are contained as expected: as a single array of strings.

**Comment by mway-niels** [comment]
Yes, it's the remote endpoint. This is the response returned by the Azure AD OIDC user info endpoint (`GET https://login.windows.net/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/openid/userinfo`):

```
{
    "amr": "[\"pwd\",\"mfa\"]",
    "family_name": "Doe",
    "given_name": "John",
    "ipaddr": "X.X.X.X",
    "name": "John Doe",
    "oid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "rh": "XXXXX",
    "sub": "XXXXX",
    "tid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "unique_name": "john@doe.com",
    "upn": "john@doe.com",
    "uti": "XXXXX",
    "ver": "1.0",
    "groups": [
        "[\"1XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\",\"2XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\",\"3XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\"]"
    ]
}
```

I'll forward this issue to Microsoft. Even though this is obviously a bug on their end, would you consider adding a checkbox to the OIDC configuration page allowing users to explicitly disable user info fetching from the remote endpoint?

**Comment by mway-niels** [comment]
Switching the OIDC endpoint from "https://sts.windows.net/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" to "https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/v2.0" fixed the issue. Using the v1.0 endpoint will not work as Microsoft returns sts.windows.net as the issuer which causes Harbor to reject the token (mismatched iss).

**Comment by Vad1mo** [comment]
@mway-niels can you post your harbor and azure config here to keep a history and a reference for others?

**Comment by mway-niels** [comment]
**Azure app registration**
Token configuration:
Add groups claim -> "Security groups" -> ID, Access, SAML "Group ID"

**Harbor configuration**
OIDC Endpoint: https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/v2.0
OIDC Client ID: See Azure
OIDC Client Secret: See Azure
Group Claim Name: groups
OIDC Admin Group: Object ID of the desired group
OIDC Scope: openid,offline_access,profile,email,Directory.Read.All
Verify Certificate: Yes
Automatic onboarding: Yes
Username claim: unique_name
