### ISSUE TITLE
Simple http interface for authentication

### ISSUE THREAD

**Issue by duffqiu** [goharbor/harbor#180]
Now, we only can use LDAP to integrate authentication system

But in most situation, each enterprise has its own way to do the authentication for example CAS.

So, maybe the simple http interface is the best way for integration

**Comment by reasonerjt** [comment]
Sorry, but I don't think simple http interface is standard, how about oauth?

**Comment by duffqiu** [comment]
oauth or oauth2? which oauth flow is best?

**Comment by reasonerjt** [comment]
#448 has very similar requirement, I think we'll consider to implement it, it's all about a contract.

**Comment by xieepp** [comment]
We need CAS .

**Comment by Thinkwp** [comment]
we need cas, too.

**Comment by AlphaSRE** [comment]
we need cas, three.

**Comment by clouderati** [comment]
@AlphaSRE, @Thinkwp and @xieepp – can you please elaborate on the desired / ideal behavior re: CAS + Harbor?

**Comment by reasonerjt** [comment]
We'll consider to support delegating the whole authn/authz to external but not simple http endpoint, closing.

**Comment by foreverm10** [comment]
we need cas
