### ISSUE TITLE
Add project member should call /api/v2.0/users/search instead of /api/v2.0/users 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#18001]
1. Add a user joe with admin
2. Create a project joe_proj with admin, add joe to joe_proj as project admin
3. Login with joe, and try to add user to the joe_project.
4. The request is to /api/v2.0/users, and failed with 403 error
<img width="993" alt="Screen Shot 2022-12-15 at 16 40 45" src="https://user-images.githubusercontent.com/2696760/207817774-24ea85a1-4ba9-46a9-8b8b-2b590e58c435.png">

**Comment by AllForNothing** [comment]
Duplicated with #18000
