### ISSUE TITLE
Documentation: 404 page not found

### ISSUE THREAD

**Issue by NicolasGoeddel** [goharbor/harbor#18015]
Hi,

I am trying to find out more about Harbor but when I go to https://goharbor.io/ and click on [Getting started](https://goharbor.io/docs/latest/install-config) or try to click me to the [Docs](https://goharbor.io/docs/2.7.0) I always get a 
![image](https://user-images.githubusercontent.com/1520064/208761826-cc319b8e-8929-43bf-ac1e-baab89b6bdf0.png)

It would be nice to have that fixed or showing me an other way to read through the docs.

**Comment by AllForNothing** [comment]
@NicolasGoeddel We are working on the doc, it should be done in 1 or 2 days.

**Comment by NicolasGoeddel** [comment]
It would be nice if the obvious links on the website always work as expected so new people get not confused or scared.

**Comment by AllForNothing** [comment]
@NicolasGoeddel 
The 2.7 doc is ready now. Closing this as completed.
