### ISSUE TITLE
harbor.v2.7.0 installed,use default redis connect failed

### ISSUE THREAD

**Issue by wcpsoft** [goharbor/harbor#18016]
harbor.v2.7.0 installed,use default redis connect failed

Dec 21 12:31:04 172.25.0.1 core[31748]: 2022-12-21T04:31:04Z [INFO] [/core/main.go:138]: initializing cache ...
Dec 21 12:31:04 172.25.0.1 core[31748]: 2022-12-21T04:31:04Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 500ms : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:07 172.25.0.1 core[31748]: 2022-12-21T04:31:07Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 589.630428ms : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:11 172.25.0.1 core[31748]: 2022-12-21T04:31:11Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 821.6259ms : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:15 172.25.0.1 core[31748]: 2022-12-21T04:31:15Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 1.037869321s : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:19 172.25.0.1 core[31748]: 2022-12-21T04:31:19Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 4.217149038s : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:23 172.25.0.1 core[31748]: 2022-12-21T04:31:23Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 10s : dial tcp 172.25.0.6:6379: connect: no route to host
Dec 21 12:31:34 172.25.0.1 core[31748]: 2022-12-21T04:31:34Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 1.586012586s : dial tcp 172.25.0.6:6379: connect: no route to host

harbor docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                             PORTS                                         NAMES
d9277d8438d2        goharbor/harbor-jobservice:v2.7.0    "/harbor/entrypoint.…"   26 seconds ago      Restarting (2) 8 seconds ago                                                     harbor-jobservice
712f1f4032fd        goharbor/nginx-photon:v2.7.0         "nginx -g 'daemon of…"   26 seconds ago      Up 25 seconds (health: starting)   0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   nginx
923872ac3665        goharbor/harbor-core:v2.7.0          "/harbor/entrypoint.…"   26 seconds ago      Up 26 seconds (health: starting)                                                 harbor-core
c83128cc721a        goharbor/registry-photon:v2.7.0      "/home/harbor/entryp…"   27 seconds ago      Up 26 seconds (health: starting)                                                 registry
6bb6df36db37        goharbor/redis-photon:v2.7.0         "redis-server /etc/r…"   27 seconds ago      Up 26 seconds (health: starting)                                                 redis
9fde4cbd52e0        goharbor/harbor-registryctl:v2.7.0   "/home/harbor/start.…"   27 seconds ago      Up 26 seconds (health: starting)                                                 registryctl
1e8bbd5f7ff5        goharbor/harbor-db:v2.7.0            "/docker-entrypoint.…"   27 seconds ago      Up 26 seconds (health: starting)                                                 harbor-db
abb0915a9f15        goharbor/harbor-portal:v2.7.0        "nginx -g 'daemon of…"   27 seconds ago      Up 27 seconds (health: starting)                                                 harbor-portal
f9d430391bb9        goharbor/harbor-log:v2.7.0           "/bin/sh -c /usr/loc…"   28 seconds ago      Up 27 seconds (health: starting)   127.0.0.1:1514->10514/tcp                     harbor-log

**Versions:**
- harbor version: v2.7.0
- docker engine version: Docker version 18.09.0, build d1134d1
- docker-compose version:docker-compose version 1.22.0, build f46880f

[harbor_conf_logs.tar.gz](https://github.com/goharbor/harbor/files/10274528/harbor_conf_logs.tar.gz)

**Comment by wcpsoft** [comment]
Docker iptables affect access to Redis and Harbor containers

**Comment by JeanRessouche** [comment]
Same issue here :( 
Fresh ubuntu 22.04 install, docker 23 installed, online 2.7 package used to install (without issues).
Same as above, redis is started and do not disclose errors, harbor core timeout on redis.

Any idea how to resolve it ? This is absolutely blocking.

**Comment by Duncan-Howe** [comment]
@wcpsoft I appreciate you fixed this a long time ago, but can you recall how you managed to make this blasted thing work?
