### ISSUE TITLE
new version2.7.0 use https error

### ISSUE THREAD

**Issue by LazySongQ** [goharbor/harbor#18010]
use new version 2.7.0 ，The error is reported as follows，http is ok
![image](https://user-images.githubusercontent.com/83281049/208387390-5ff83d0e-f68e-4827-9df4-9166f75ad852.png)

**Comment by LazySongQ** [comment]
![image](https://user-images.githubusercontent.com/83281049/208557798-16b0766f-bb9d-4628-a941-e2852a753d2d.png)

**Comment by MinerYang** [comment]
Hi @LazySongQ ,
You don't need the semicolon `;` when you configure your certificate & private_key, the you will be good to install.
