### ISSUE TITLE
repositories gone when upgrade from 2.2.4 to 2.3.5

### ISSUE THREAD

**Issue by finalha** [goharbor/harbor#18019]
Harbor version: v2.2.4
OS: CentOS Linux release 7.6.1810 (Core) 
Docker version: 
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           

> linux/amd64

 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

follow the document in https://goharbor.io/docs/2.3.0/administration/upgrade/
There are no issues during the the process of upgrading and logging.
The harbor.yaml is below:
![图片](https://user-images.githubusercontent.com/13330963/208896812-c296d18f-e279-4355-9f49-657e6d2350f7.png)

When I login the harbor, the old repositories are gone, but I can find the files in /opt/docker-hub/data/registry/docker/registry/v2/repositories, it seems that the database has someting wrong: there is no data in table task and execution
![图片](https://user-images.githubusercontent.com/13330963/208895607-34ff9aa1-d40f-4e9d-a4c2-7f6cb8ec4027.png)

The log of harbor-core and harbor-db containers are here:
[harbor-core.log](https://github.com/goharbor/harbor/files/10277249/harbor-core.log)
[harbor-db.log](https://github.com/goharbor/harbor/files/10277250/harbor-db.log)

By the way, when I try to upgrade from 2.2.4 to 2.4.3, the issue is the same. How could I fix it?

**Comment by chlins** [comment]
Maybe related with https://github.com/goharbor/harbor/issues/17544.

**Comment by finalha** [comment]
> Maybe related with #17544.

#17544 is the issue that the repositories are more than one with the same name in UI.
My issue is that I could not find all the repos from UI after upgrading.
It seems to be different.

**Comment by stonezdj** [comment]
You should add a semicolon at the end of the sql.

**Comment by finalha** [comment]
> You should add a semicolon at the end of the sql.

registry=# select * from task;
 id | execution_id | job_id | status | status_code | status_revision | status_message | run_count | extra_attrs | creation_time | start_time | update_time | end_time | vendor_type 
----+--------------+--------+--------+-------------+-----------------+----------------+-----------+-------------+---------------+------------+-------------+----------+-------------
(0 rows)

registry=# select * from execution;
 id | vendor_type | vendor_id | status | status_message | trigger | extra_attrs | start_time | end_time | revision | update_time 
----+-------------+-----------+--------+----------------+---------+-------------+------------+----------+----------+-------------
(0 rows)

The result is nothing.

**Comment by chlins** [comment]
Could you try to execute `select * from repository;`?

**Comment by finalha** [comment]
> Could you try to execute `select * from artifact;` and `select * from repository;`?

[root@harbor_test ~]# docker exec -it harbor-db bash
postgres [ / ]$ psql registry
psql (13.5)
Type "help" for help.

registry=# select * from artifact;
 id | project_id | repository_name | digest | type | pull_time | push_time | repository_id | media_type | manifest_media_type | size | extra_attrs | annotations | icon 
----+------------+-----------------+--------+------+-----------+-----------+---------------+------------+---------------------+------+-------------+-------------+------
(0 rows)

registry=# select * from repository;
 repository_id | name | project_id | description | pull_count | star_count | creation_time | update_time 
---------------+------+------------+-------------+------------+------------+---------------+-------------
(0 rows)

**Comment by stonezdj** [comment]
It seems the database directory/file is incorrect.
If it is upgrade correctly, these two table should not be empty.
