### ISSUE TITLE
replication image registry to another harbor failed

### ISSUE THREAD

**Issue by liyin37** [goharbor/harbor#18028]
harbor version is :
![image](https://user-images.githubusercontent.com/42507175/209531605-74e5d953-50ca-40b4-b961-b54abca86822.png)
I anync the  local harbor to registry，the job-logs have errors
![image](https://user-images.githubusercontent.com/42507175/209531753-56003731-0aa9-4c81-9c36-b2df5cac21ed.png)
![image](https://user-images.githubusercontent.com/42507175/209531806-f92282fa-0460-4987-805a-994229fc970d.png)
the errors is below：
![image](https://user-images.githubusercontent.com/42507175/209531917-546c3c69-5dd9-44f5-b1a5-cf3a0f83d99c.png)

**Comment by liyin37** [comment]
when I login the harbor server,
docker login registry.chengdu.tcs.cim.cd.cegn.cn and  docker pull one image is successfully

**Comment by stonezdj** [comment]
What is the output of testing connection?
<img width="463" alt="Screen Shot 2023-01-03 at 15 59 42" src="https://user-images.githubusercontent.com/2696760/210318726-f6ee5bc7-6c6c-47b2-9828-468a8058a6ce.png">
