### ISSUE TITLE
Support async image registry to ECR (AWS)

### ISSUE THREAD

**Issue by typro33333** [goharbor/harbor#18027]
- I have problem about network so slow when pull and push image to `ECR (AWS)`. It will take me long time to run CI to pull image. So i think we can store image and registry on `Harbor` then we will use all image and registry on harbor local. Then every at night, harbor will automatic up to all images latest to my `ECR (AWS)` or maybe `Harbor` can async all image and registry on `ECR (AWS)` into ECR either.

Workflow: 
> Dev -> push image -> Harbor -> Harbor will async image on ECR AWS every day.

- If another people not harbor but they push image to ECR then harbor can check new images and async it into local.
Workflow: 
> On Harbor -> Harbor check new images on ECR AWS -> if new -> harbor pull image to local.

If i wrong please comment tag me.

**Comment by Vad1mo** [comment]
yes you can crate this workflow.

**Comment by typro33333** [comment]
> 
yep, but i didn't see tutorial setup harbor connect to aws ecr.
