### ISSUE TITLE
Cosign doesn't work with Robot Accounts

### ISSUE THREAD

**Issue by lclc** [goharbor/harbor#18026]
**Expected behaviour and actual behaviour:**

1) I log into my Harbor using a Cosign with a Robot account, e.g. cosign login --username "robot$myAccount" --password "abcd" "myregistry.container-registry.com"

The Robot account has all rights set for all projects (I'd expect it to work with less - but anyway, I tested it with all rights).

2) I sign one of my images that are on my registry. That image I already pulled to my local computer.
Something like:

> cosign sign --key 21cosign.key myregistry.container-registry.com/project/name@sha256:a28d5f85fb8a4e75c9a65df04d2e5f8e0f1288ca41d98aabc1797a2841896701

Expected: It should work (sign the image and push the signature to the registry).

Actual behaviour: Fails with an access denied error. Something like:

> Error: signing [myregistry.container-registry.com/project/name@sha256:a28d5f85fb8a4e75c9a65df04d2e5f8e0f1288ca41d98aabc1797a2841896701]: accessing image: GET https://myregistry.container-registry.com/v2/project/name/manifests/sha256:a28d5f85fb8a4e75c9a65df04d2e5f8e0f1288ca41d98aabc1797a2841896701: UNAUTHORIZED: unauthorized to access repository: project/name, action: pull: unauthorized to access repository: project/name, action: pull
> 
> main.go:62: error during command execution: signing [myregistry.container-registry.com/project/name@sha256:ea95eb1fe3ff8aeeaa3c0f53e3b36d340201cf4c19d332ec0efdf48fc6c21b9c]: accessing image: GET https://myregistry.container-registry.com/v2/project/name/manifests/sha256:a28d5f85fb8a4e75c9a65df04d2e5f8e0f1288ca41d98aabc1797a2841896701: UNAUTHORIZED: unauthorized to access repository: project/name, action: pull: unauthorized to access repository: project/name, action: pull

**Important Note: It works with a Harbor User Account (with Admin privileges).**

**Versions:**

- harbor version: v2.6.2-6054dbd8
- docker engine version: 
> docker version 4.3.1
> podman version 4.3.1
- docker-compose version: n/a

**Additional context:**

We're using a dedicated service from https://container-registry.com/ by @Vad1mo (I didn't contact him yet because I assume it's a general Harbor problem).

**Comment by lclc** [comment]
cosign version: 1.13.1

**Comment by YangJiao0817** [comment]
Hi @lclc , You should use `docker login myregistry.container-registry.com -u 'robot$myAccount' -p abcd` and then do the cosign sign operation , cosign does not have the command cosign login.

**Comment by lclc** [comment]
It does: https://github.com/sigstore/cosign/blob/main/doc/cosign_login.md

Have you tried signing with a Robot Account?

**Comment by YangJiao0817** [comment]
@lclc Yes I tried that, maybe your problem is in the `"`, you can try the following command, replace `"` with `'`
`cosign login --username 'robot$myAccount' --password 'abcd' 'myregistry.container-registry.com'`

**Comment by lclc** [comment]
Thanks, that's it.
