### ISSUE TITLE
Add Replications task restart or retry

### ISSUE THREAD

**Issue by kong62** [goharbor/harbor#18021]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I hope that when the replication task fails, I can manually restart the replication task or have automatic retry

**Steps to reproduce the problem:**
when Replications  failed

**Versions:**
Please specify the versions of following systems.

- harbor version:  2.7.0
- docker engine version:  20.10.22
- docker-compose version: v2.11.0

**Additional context:**

![snap_screen_20221222195701](https://user-images.githubusercontent.com/10241723/209129620-afc76d1a-601a-4d03-9956-1d4f54a8bea6.png)

**Comment by chlins** [comment]
The replication task will retry max 3 times in backend when failed.
