### ISSUE TITLE
Can I configure multiple addresses in auth-token-realm in config.yml under registry

### ISSUE THREAD

**Issue by liuao5201314** [goharbor/harbor#18036]
I want to be able to access the harbor warehouse login service on the Internet and LAN. How do I configure /service/token?
![image](https://user-images.githubusercontent.com/64817960/210039606-6af36da7-8f8c-4f48-a4d8-524e1fac9a0e.png)

**Comment by stonezdj** [comment]
It is not support to configure multiple address.
