### ISSUE TITLE
go import missing at src/server/v2.0/handler/user.go

### ISSUE THREAD

**Issue by windghoul** [goharbor/harbor#18030]
Check the source code and find that the import position in the file is wrong, and the directory levels of the source code and import do not correspond.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/16053291/209781395-4d4c13d5-6054-4d1c-bd5d-0540ad0f17ea.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/16053291/209781415-19086d4f-608c-4447-bb50-d1f827cd514d.png">

**Comment by windghoul** [comment]
On the mac m1 system, make gen_apis behaves abnormally and needs to be fixed as follows. 
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/16053291/209792470-ed62f55d-82ee-4fa5-9936-e3aeb42421b4.png">

**Comment by stonezdj** [comment]
Currently we only support amd64, not support m1 system.
