### ISSUE TITLE
Stop ScanAll not work in case of lots of artifacts.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#18044]
How can we help you?

1. Prepare a harbor instance with 10w artifacts.
2. Trigger Scan ALL.
3. Trigger Stop Scan.

The jobs still be enqueued to the jobservice, and the success job numbers keep increasing which not reasonable.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/31262637/210322772-9495ffbf-d489-4572-8d6a-514118c23007.png">
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/31262637/210322828-98455814-0956-4e40-81d8-1134fd080c54.png">

**Comment by zyyw** [comment]
The execution status is currently not refreshed into database properly. We may need further investigate on that first.
