### ISSUE TITLE
crio not able to pull from harbor for configured internal registries via /etc/containers/registries.conf

### ISSUE THREAD

**Issue by danielcb** [goharbor/harbor#18047]
**Expected behavior and actual behavior:**
We're running harbor as internal registry and have configured proxy caches e.g. for dockerhub:

`https://exampleregistry.com/upstream-docker`

We also have configured our cluster to remap all images from docker.io to be pulled through our proxy cache:

```
cat /etc/containers/registries.conf
unqualified-search-registries = ["docker.io"]

# Docker Upstream Proxy
[[registry]]
prefix = "docker.io"
location = "exampleregistry.com/upstream-docker"
```

Up until now we we're using separate OIDC accounts as service accounts and used there tokens to download images. So we had a user `service_account`, logged in once as this user and copied it's token. These credentials were used inside k8s as imagePullSecrets and inside CI/CD pipelines, etc. This still works without problems. The same does not work with the globally scoped robot accounts.

We now switched to using the globally scoped robot accounts and added one robot account with access to all projects: `robot_account`.

When we pull an image directly, everything works:

`crictl pull --creds robot_account:SECRET_TOKEN exampleregistry.com/upstream-docker/some/image:latest`

When we try to use the remapping it does not work using the robot accounts:

`crictl pull --creds robot_account:SECRET_TOKEN some/image:latest`

The remapping itself seems to work, but we get the error `unauthorized to access repository`. It logs that it actually tries to access `exampleregistry.com/upstream-docker/some/image:latest` and we see the request in harbor.
 
 Logs from crictl:
```
DEBU[0000] get image connection
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:some/image,Annotations:map[string]string{},},Auth:&AuthConfig{Username:robot_account,Password:SECRET_TOKEN,Auth:,ServerAddress:,IdentityToken:,RegistryToken:,},SandboxConfig:nil,}
E0103 16:46:49.809188 2460131 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unknown desc = reading manifest latest in exampleregistry.com/upstream-docker/some/image: unauthorized: unauthorized to access repository: upstream-docker/some/image, action: pull: unauthorized to access repository: upstream-docker/some/image, action: pull" image="some/image"
FATA[0000] pulling image: rpc error: code = Unknown desc = reading manifest latest in exampleregistry.com/upstream-docker/some/image: unauthorized: unauthorized to access repository: upstream-docker/some/image, action: pull: unauthorized to access repository: upstream-docker/some/image, action: pull
```

Harbor logs the following for the request:
```
harbor-core        | 2023-01-03T16:51:51Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="XXXX, YYYY, ZZZZ" requestID="c5a149b9-fc32-4672-9453-bd8829392b4c" user agent="cri-o/1.25.1 go/go1.19 os/linux arch/amd64"]: failed to authenticate user:robot_account, error:not supported
```

**Steps to reproduce the problem:**
* Add a globally scoped robot account
* Add a proxy cache repo for dockerhub
* Configure /etc/containers/registries.conf to remap docker.io to an internal proxy cache in harbor
* Try to access the proxy cache directly: Works
* Try to access the proxy cache with its "docker.io" name: **Won't work for the robot account, but will work for a normal user account.**

**Versions:**

- k8s: v1.24
- harbor version: 2.6.1
- crio / crictl version: 1.25.1

**Comment by stonezdj** [comment]
Could you please try to add single quote to enclose the robot account name and secret and try again because the robot account contains special character `$`
