### ISSUE TITLE
部署时fuse-overlayfs错误

### ISSUE THREAD

**Issue by jhsswl** [goharbor/harbor#18051]
./prepare
prepare base dir is set to /usr/local/harbor
docker: Error response from daemon: using mount program fuse-overlayfs: cannot resolve path /data/fuse-overlayfs/l/IA4DTJDNFU6WCYT3UULSRP52KA
cannot load store (null) at /data/fuse-overlayfs/l/IA4DTJDNFU6WCYT3UULSRP52KA
fuse-overlayfs: cannot read lower dirs: No such file or directory
: exit status 1.
See 'docker run --help'.

docker容器存储nfs挂载/data，harbor存储/data/harbor
--------------------------------

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7
- docker engine version: 20.10.22
- docker-compose version: 2.14.2

rocky 9.1

**Comment by stonezdj** [comment]
It is the issue of the mount directory,  doesn't related to the Harbor
