### ISSUE TITLE
Not support multi arch for same tag

### ISSUE THREAD

**Issue by 631068264** [goharbor/harbor#18065]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

I hope can get pull image for the unique tag for multi arch just like dockerhub
<img width="1287" alt="企业微信截图_5c0d5a58-4f20-4b05-8ea2-d54c79844594" src="https://user-images.githubusercontent.com/8144089/210565277-28a52ac2-1cda-4a77-aa1e-c87c05406d42.png">

https://hub.docker.com/r/rancher/rancher-agent/tags?page=1&name=2.6.5

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

 Harbor 2.4 not work  , please tell me which version support?

 I push multi arch for same tag

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/8144089/210562363-f6351175-e564-4340-b61e-157acd58a35e.png">

even I use `docker pull --platform=arm64`  , I only get the amd64 one

I also find this https://github.com/goharbor/harbor/issues/6207#issuecomment-623913230   , this is an old issue or feature? **Why not support**?

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.2
- docker engine version: 20.10.21
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by huapox** [comment]
+1
