### ISSUE TITLE
first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by ppp0183** [goharbor/harbor#18068]
I have installed Harbor 2.7.0 in ubuntu 22.04
and tried to make registry which is in other network, but the connection always failed with below log.

the step that I did
1. login to harbor portal(70.130.30.x)
2. click registry menu
3. put the registry like this https://10.251.227.x
4. uncheck verify cert
5. click test connection button.
6. check /var/log/harbor/core.log

please help me how to fix this isuse
======================================================================================
Jan  5 14:29:21 user1-Precision-7560 core[1094]: 2023-01-05T05:29:21Z [ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: Get \"https://10.251.227.157/api/version\": tls: first record does not look like a TLS handshake"}]}

**Comment by stonezdj** [comment]
Is the registry with https://10.251.227.x a harbor registry? and the TLS is enabled in this server?
