### ISSUE TITLE
Specific project detail information endpoint returns 404 even if the project exist

### ISSUE THREAD

**Issue by batusekerci** [goharbor/harbor#18060]
Hi, I encountered a bug when I was trying to use "GET [​/projects​/{project_name_or_id}] Return specific project detail information" endpoint. We are keeping project names as integers. There was no problem when I was creating project with integer name from API or GUI. Whenever I used the "detail info" endpoint, it returns me 404 Not Found error, even if the project exists and I can push and pull images. 

If I create another project with just one char and integers there is no problem.

Example:
Project Name: 555  -> 404 Not found
Project Name: 555s  -> 200 Successful

BTW I know that our version is old, I do not know that this bug is fixed in future releases. I could not find any issues about this bug so I decided to create one.

Note: I noticed that other project endpoints are also not working which have "project_name_or_id" parameter.
 
Harbor version: v2.2.0-ec0ba116

**Comment by stonezdj** [comment]
what is the result this query?
```
select * from project where name = '555';
select * from project where name like '%555%';
```

**Comment by j4ckstraw** [comment]
I have a similar problem. 
I got `project not found`, mostly, when new image pushed.

**Comment by batusekerci** [comment]
> Do you mean all the project named with digits will return 404 or just one of them? What is the result this query?
> 
> ```
> select * from project where name = '555';
> select * from project where name like '%555%';
> ```

I mean **all** projects named with digits

**Comment by batusekerci** [comment]
The issue is still active.

**Comment by chlins** [comment]
@batusekerci Hi, please try to add the header `X-Is-Resource-Name: true` in request if your project name is numeric.
