### ISSUE TITLE
Ask about the expiration time of the CVE whitelists

### ISSUE THREAD

**Issue by hyeyoung-leee** [goharbor/harbor#18078]
**How can we help you?**

Hi,

I am inquiring about the expiration time of the CVE whitelists.
Harbor version is Version v2.5.3-797c3536.

I set the system wide CVE whitelists and expiration time to pull image with vulnerability. And I do not set per-project CVE whitelists and expiration time.
It seems that the whitelist is applied even after the expiration time has passed. Please check if this is the correct operation or a bug.

If this is the correct operation, shouldn't the whitelist be allowed after the expiration time?

Thanks.

**Comment by hyeyoung-leee** [comment]
@zyyw @YangJiao0817 @AllForNothing 
Can I try it?

**Comment by AllForNothing** [comment]
> @zyyw @YangJiao0817 @AllForNothing Can I try it?

@hyeyoung-leee 
Do you mean you want to fix it?
If so, welcome to raise a PR to fix it

**Comment by hyeyoung-leee** [comment]
> > @zyyw @YangJiao0817 @AllForNothing Can I try it?
> 
> @hyeyoung-leee Do you mean you want to fix it? If so, welcome to raise a PR to fix it

@AllForNothing 
Yes, I want to fix it. I will raise a PR.
Thanks.
