### ISSUE TITLE
if Harbor allows to ask for authentication for image pulls at system level rather than project level

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor#18088]
How can we help you?

Hi I don't see information about if Harbor allows to ask for authentication for image pulls at system level rather than project level

is it possible if Harbor allows to force all pulls to be authenticated at system level??

In doc only see two posibilities
esides the above roles, there are two system-level roles:

Harbor system administrator: “Harbor system administrator” has the most privileges. In addition to the privileges mentioned above, “Harbor system administrator” can also list all projects, set an ordinary user as administrator, delete users and set vulnerability scan policy for all images. The public project “library” is also owned by the administrator.
Anonymous: When a user is not logged in, the user is considered as an “Anonymous” user. An anonymous user has no access to private projects and has read-only access to public projects.

are there more options?

**Comment by stonezdj** [comment]
Could you please describe your requirement in detail? 
do you mean require pull privileges to pull image from public project?

**Comment by jorgemansillacriado** [comment]
> Could you please describe your requirement in detail? do you mean require a login user with pull privileges to pull image from public projects?

Hi , I want to know if Harbor has similar role options at system level to project level

In project level only has two system-level roles.  admin or anonymous

my question is? we have more options?

are there any possibility configurate every projects at system level?

**Comment by Vad1mo** [comment]
sorry I still have difficulties understanding your question and intention. 

if you enable OIDC you can put users in groups and groups to project so this way a user hase access to mulpile proejcts once he logs in.
