### ISSUE TITLE
Retention job: no processor registered with algorithm

### ISSUE THREAD

**Issue by vmwiz** [goharbor/harbor#18085]
**Expected behavior and actual behavior:**
Since upgrade to 2.7.0 (helm deployment on Openshift 4.9), the retention policy jobs are failing with the following error:
```
2023-01-10T07:11:58Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'RETENTION:b44bf1a595b942e0ddda455e' exit with error: run error: retention job: get processor for algorithm: : no processor registered with algorithm:
```
We see the same error on various proxy cache projects (quay.io, docker.io, ghcr.io, gcr.io) ; normal projects do not seems to be affected, the same kind of retention rule runs successfully. 
While `gcr.io` gives an error, `k8s.gcr.io` run successfully.

**Steps to reproduce the problem:**
1. Create a proxy cache project for quay.io
2. Pull some images to fill the cache
3. Configure a tag rentention rule
    - For the repositories matching **
    - By artifact count or number of days retain the artifacts pulled within the last # days 30
    - Tags matching ** (untagged artifacts true)
4. Execute the retention policy job manually

Job logs in the UI shows the same error as in the `jobservice` pod: `no processor registered with algorithm`

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7.0
- kubernetes version: 1.22
- openshift version: 4.9

**Additional context:**
jobservice logs
```
2023-01-10T07:26:52Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: http://harbor-core:80/api/v2.0/internalconfig
2023-01-10T07:26:52Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: http://harbor-core:80/api/v2.0/internalconfig
2023-01-10T07:26:52Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'RETENTION:725404ee6122bdc21b76f416' exit with error: run error: retention job: get processor for algorithm: : no processor registered with algorithm:
2023-01-10T07:26:52Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'RETENTION:4ad023cb8db26928d5a90e16' exit with error: run error: retention job: get processor for algorithm: : no processor registered with algorithm:
```
No other relevant errors are shown in the other pods

**Comment by stonezdj** [comment]
Could you please share the screenshot of the error?
And the query result of the SQL:
```
select * from retention_policy where scope_level = 'project' and scope_reference = <project_id>
```

**Comment by vmwiz** [comment]
Here are the requested informations:

Configuration of the tag retention policy from the UI:
![image](https://user-images.githubusercontent.com/17565465/212656835-e2357ced-3dff-4422-9963-13aedba6b7cc.png)
![image](https://user-images.githubusercontent.com/17565465/212657001-62286557-9323-447b-8cdf-c0faa30d90b8.png)

Job logs from the UI
![image](https://user-images.githubusercontent.com/17565465/212657138-cd18e282-c009-4296-b8cf-e082ec71de01.png)

Here's the `data` column from the query result (other fields didn't look relevant), the `algorithm` key is empty:
```json
{
   "id":0,
   "algorithm":"",
   "rules":[
      {
         "id":0,
         "priority":0,
         "disabled":false,
         "action":"retain",
         "template":"nDaysSinceLastPush",
         "params":{
            "nDaysSinceLastPull":30,
            "nDaysSinceLastPush":30
         },
         "tag_selectors":[
            {
               "kind":"doublestar",
               "decoration":"matches",
               "pattern":"**",
               "extras":"{\"untagged\":true}"
            }
         ],
         "scope_selectors":{
            "repository":[
               {
                  "kind":"doublestar",
                  "decoration":"repoMatches",
                  "pattern":"**",
                  "extras":""
               }
            ]
         }
      },
      {
         "id":0,
         "priority":0,
         "disabled":false,
         "action":"retain",
         "template":"latestPushedK",
         "params":{
            "latestPushedK":3
         },
         "tag_selectors":[
            {
               "kind":"doublestar",
               "decoration":"matches",
               "pattern":"**",
               "extras":"{\"untagged\":true}"
            }
         ],
         "scope_selectors":{
            "repository":[
               {
                  "kind":"doublestar",
                  "decoration":"repoMatches",
                  "pattern":"ansible/awx-ee",
                  "extras":""
               }
            ]
         }
      }
   ],
   "trigger":{
      "kind":"Schedule",
      "settings":{
         "cron":"0 0 0 * * 0"
      }
   },
   "scope":{
      "level":"project",
      "ref":71
   }
}
```

**Comment by vmwiz** [comment]
Issue still exists on 2.7.0
