### ISSUE TITLE
Buildkit cache cannot be saved to harbor

### ISSUE THREAD

**Issue by ushiii111798** [goharbor/harbor#18084]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Cache layer should be saved but it is not.

**Steps to reproduce the problem:**
Using docker buildx
Setup cache-to to harbor registry

**Versions:**

- harbor version: [2.6.1]
- docker engine version: [20.10.20]
- docker-compose version: [2.12.0]

**Additional context:**
![Screenshot 2023-01-10 at 11 25 38 AM](https://user-images.githubusercontent.com/11730880/211447819-ceb6951c-d8d7-464e-8160-3505e71f2d3c.png)

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by stonezdj** [comment]
could you please provide the proxy.log and the registry.log when the cache operation happens?

**Comment by kiorky** [comment]
i confirm this bug.

**Comment by kiorky** [comment]
dup #14774

**Comment by kiorky** [comment]
not stall
