### ISSUE TITLE
Cannot filter artifacts in the web UI

### ISSUE THREAD

**Issue by mikakatua** [goharbor/harbor#18082]
**Expected behavior and actual behavior:**
When browsing artifacts in a repository it is not possible to select a specific tag by typing in the search box.

In Harbor v2.6.3 this was working:
![filter-artifacts-v2 6 3](https://user-images.githubusercontent.com/44744529/211321918-023d2238-502f-4ddd-9118-2a788a189ece.png)

After upgrading to v2.7.0 it is not possible to perform a search by tag:
![filter-artifacts-v2 7 0](https://user-images.githubusercontent.com/44744529/211321920-a7840f75-c363-48da-8974-563327f9a9b1.png)

I have tested it with latest versions of Chrome and Firefox browsers for Linux.

**Steps to reproduce the problem:**
1. Go to the demo environment https://demo.goharbor.io/ 
1. Select any project which contain at least one repository
1. In the repository, click on the magnifier glass icon to perform a search
1. Select the type "Tags" and try to type in the search box to filter artifacts

**Versions:**
- harbor version: 2.7.0

**Additional context:**

**Comment by stranljip** [comment]
Hi @AllForNothing - can you already give an ETA for a new version with this bug fixed? It is quite hampering for my use cases  😬

**Comment by AllForNothing** [comment]
@stranljip If nothing else, 2.7.1 will be released within this month.
If you can not wait, you try this workaround:
After the linked PR is merged, you can clone the source code, then compile the UI code, then copy to the portal container:

1. `cd src/portal`
2. `npm install`
3. `npm run release`
4. `scp  -r dist username@servername:remote_dir`
5.  ssh to your Harbor server, then `docker exec -ti -u root harbor-portal rm -rf /usr/share/nginx/html/`
6. `cd your remote_dir` then `docker cp dist harbor-portal:/usr/share/nginx/html`
