### ISSUE TITLE
Installer fails on Fedora due to SELinux problem with generated config files

### ISSUE THREAD

**Issue by willgorman** [goharbor/harbor#18083]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

When following the default installation instructions from https://goharbor.io/docs/2.7.0/install-config/run-installer-script/ on Fedora 34 with SELinux enabled, I expect to have all of the components of Harbor start successfully.

The actual behavior is that only `harbor-log` starts and the other containers fail 
```
[Step 4]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
Creating harbor-log ... done
Creating harbor-portal ... error
Creating registryctl   ... 
Creating harbor-db     ... 
Creating redis         ... 
Creating harbor-db     ... error

ERROR: for harbor-portal  Cannot start service portal: failed to initialize logging driver: dial tcp [::1]:1514: connect: connection refused
```

The logs for `harbor-log` show that it is unable to read the config files:
```
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 63: error accessing config file or directory '/etc/rsyslog.d/rsyslog_docker.conf' [cwd: /]: Permission denied [v8.2202.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.2202.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

Follow the installation instructions on https://goharbor.io/docs/2.7.0/install-config/ on Fedora (or perhaps any distro with SELinux enabled) and run `sudo ./install.sh`

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.6.3]
- docker engine version: [20.10.16]
- docker-compose version: [1.28.6]

**Additional context:**

I believe this is the same issue reported in https://github.com/goharbor/harbor/issues/16369 which was closed as stale.  That issue contains a proposed fix for the problem.  Additionally, I was able to work around the problem by modifying the `prepare` script in the installer to add `:z` to the config files generated by the prepare script:

```
# Run prepare script
docker run --rm -v $input_dir:/input \
                    -v $data_path:/data \
                    -v $harbor_prepare_path:/compose_location \
                    -v $config_dir:/config:z \
                    -v /:/hostfs \
                    --privileged \
                    goharbor/prepare:dev prepare $@
````

**Comment by stonezdj** [comment]
Maybe related to this PR: https://github.com/goharbor/harbor/pull/16241

**Comment by senekor** [comment]
not stale
