### ISSUE TITLE
Cannot login in webconsole and docker login area/deployment

### ISSUE THREAD

**Issue by MadbnM** [goharbor/harbor#18090]
Hi, I recently installed harbor v2.7.0 with (http) however, I cannot login using the admin credentials I put in the harbor.yml file. 

the error is invalid username/password.

**Comment by stonezdj** [comment]
First, make sure the harbor-core and harbor-db container is running and healthy.
Then reset the password with this faq:
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
