### ISSUE TITLE
Harbor Replication rule filter with multiple regex rules

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#18093]
**Describe the solution you'd like**

I got a question about Harbor replication rule here:

When configuring resource filter and tag filtering, currently only one regular expression is supported. Can we support multiple regular expressions and divide them by one symbol?

Does Harbor support that function?

**Comment by stonezdj** [comment]
Duplicate to issue: https://github.com/goharbor/harbor/issues/12877
