### ISSUE TITLE
add mew harbor endpoint failed

### ISSUE THREAD

**Issue by zsh4614** [goharbor/harbor#18101]
I have 2 harbor instance，I want to add harbor endpoint each other，instance 1 can add instance 2，but instacne 2 can't add instance 1. When I TESET CONECTION，it shows: Fail to ping endpoint.

harbor1 add harbor2:
![image](https://user-images.githubusercontent.com/69032965/212310007-00317205-05bc-4179-bbb6-90be3e0f7ddc.png)

harbor2 add harbor1:
![image](https://user-images.githubusercontent.com/69032965/212310222-3deddc85-ad50-43cc-8742-853ddd9fd9d2.png)

Can someone help me?  thanks a lot!

**Comment by stonezdj** [comment]
could you uncheck the Verify Remote Cert and try again?
