### ISSUE TITLE
support short format image url

### ISSUE THREAD

**Issue by willzhang** [goharbor/harbor#18114]
is it possible for harbor to support short format image url?

docker reigstry support both the follow format.

```
format1: <registry_url>/<image_name>:<image_tag>

format2: <registry_url>/<project_name>/<image_name>:<image_tag>
```

related:  https://github.com/kubernetes/registry.k8s.io/issues/139

**Comment by chlins** [comment]
The project is a required option in harbor, so currently no way to hide the project name in the image URL.
