### ISSUE TITLE
Immutability - Be able to force deletion on immutable tags

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#18123]
**Is your feature request related to a problem? Please describe.**
As a user I would like to use immutable tags to avoid the same tag to be push on a existing one.
But I would also like to be able to force deletion of an existing immutable tag.

**Describe the solution you'd like**
A popup box "are you sure you wan't to delete this tag/image ?" when immutable rule exist.
Or in the immutable rule a check box "allow tag deletion"

**Comment by zyyw** [comment]
By design, immutable tags means tags cannot be deleted or updated/overwritten. You can open a discussion for this topic.
