### ISSUE TITLE
Job Service Dashboard Job Queues Stop PURGE_AUDIT Job Log Rotation execution is always Running

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#18121]
**Expected behavior and actual behavior:**
Expected: Log Rotation execution status should be Stopped
Actual: Log Rotation execution status is always Running

**Steps to reproduce the problem:**

1. Pause PURGE_AUDIT job
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/72076317/213669593-f47ebde4-d697-41c3-9442-9c4443a7100d.png">
2. Run Log Rotation
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/72076317/213669790-2f611e24-53c1-4c88-bbab-a3a752c230ab.png">

3. Stop PURGE_AUDIT job

4. Log Rotation execution status is Running

5. Reseme PURGE_AUDIT job
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/72076317/213670543-070025ee-e03f-4a6c-b693-6cc9e7799ea0.png">
6. Log Rotation execution status is Running
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/72076317/213672355-4a41a1c4-57e4-4656-bfa7-2fea5d164844.png">

**Versions:**
Please specify the versions of the following systems.

- harbor version: v2.7.0

**Additional context:**
purgeaudit.log
`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"470134105d33fa2423a57fce\"}"}]}`

**Comment by stonezdj** [comment]
The job service queue's pause/resume  status only stands for its queue status, not stands for the current single job status. the same for other job types such as GC, replication, tag retention...

**Comment by stonezdj** [comment]
User could click the Stop button in the Purge audit log to stop it again, and its status will be `Stopped`
