### ISSUE TITLE
Problem upgrade from 2.4.0 to 2.6.0

### ISSUE THREAD

**Issue by roberto-gomez** [goharbor/harbor#18122]
Hello.

We are triying to upgrade a Harbor 2.4.0 to 2.6.0 . We have followed the official guide to do it https://goharbor.io/docs/2.6.0/administration/upgrade and after execute the install script the core container is restarting.

We have installed Harbor in a docker host using the standar way.
 
**Expected behavior and actual behavior:**
After upgrade, the core container is restarting.

**Steps to reproduce the problem:**
In a clean installation the problem does not appear. The problem is new in a production installation with dozens of projects and images.

**Versions:**
Harbor version: 2.4.0 to 2.6.0
Docker version: 20.10.22
Docker-compose version: 1.24.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

core.log show this error:

```
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:30]: the factory for adapter ali-acr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:29]: Factory for adapter azure-acr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:18]: the factory for adapter gitlab registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:37]: the factory for adapter google-gcr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:40]: the factory of Huawei adapter was registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:43]: the factory of jfrog artifactory adapter was registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/core/controllers/base.go:153]: Config path: /etc/core/app.conf
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/core/main.go:136]: initializing cache ...
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/core/main.go:146]: initializing configurations...
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/lib/config/systemconfig.go:198]: key path: /etc/core/key
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/lib/config/config.go:92]: init secret store
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/core/main.go:148]: configurations initialization completed
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/lib/metric/server.go:23]: Prometheus metric server running on port 9090
Jan 20 13:40:31 10.112.0.33 core[71912]: 2023-01-20T12:40:31Z [INFO] [/common/dao/base.go:72]: Register database completed
Jan 20 13:40:32 10.112.0.33 core[71912]: 2023-01-20T12:40:32Z [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
Jan 20 13:40:32 10.112.0.33 core[71912]: 2023-01-20T12:40:32Z [ERROR] [/common/dao/pgsql.go:136]: Failed to upgrade schema, error: "Dirty database version 80. Fix and force version."
Jan 20 13:40:32 10.112.0.33 core[71912]: 2023-01-20T12:40:32Z [FATAL] [/core/main.go:177]: failed to migrate the database, error: Dirty database version 80. Fix and force version.

```

**Comment by ZrytyADHD** [comment]
Hi,
first of all are you run migration tool for config file ?
Each  major version of harbor need to do this before install.
I always put my yaml configuration file in folder with new harbor version and run for example:
docker run -it --rm -v /:/hostfs goharbor/prepare:v2.6.2 migrate -i /opt/harbor_262/harbor.yml
/opt/harbor_262/harbor.yml is location of my yaml config file
after that i run scripts:
/prepare
/install with specific options for me.
and this is everything what i need to upgrade to new version.

**Comment by roberto-gomez** [comment]
Hi @ZrytyADHD 

Yes, we do it. The config file is migrated to the new version and the migration process ends well. After migration command, we execute the install.sh scritp. We follow the documentation step by step. We suffered the problem in 2 production instances. In labs never happened.

Regards.

**Comment by ZrytyADHD** [comment]
Maybe this will help you.
https://github.com/golang-migrate/migrate/issues/282
or if you can check my idea:
to use migration tool to migrate config file from v.2.4.0 to v2.5.0 after that install and start harbor if everything is ok, do migration from 2.5.0 to 2.6.0.

**Comment by roberto-gomez** [comment]
Hi.

After testing and testing we have found the problem. We have an automated process to install and update. After run install.sh we apply several customizations and restart Harbor containers. If the Harbor services is not healthy befero the restart, some containers don't finish the initialization and migration (core container for example). To solve it, we add a pre-check to ensure that Harbor is healthy before apply the customizations and the upgrade finishs correctly.

Thanks @ZrytyADHD for your help.

Regards.
