### ISSUE TITLE
Clean up in projects with quota - cannot delete not fully pushed images

### ISSUE THREAD

**Issue by umberto10** [goharbor/harbor#18131]
Hello, I'm facing an issue with projects that have a quota. When I push the image that exceeds the quota, some of the data will be stored on disk (up to quota) and then the push end (that's ok). The problem is, that I cannot remove the not fully pushed artifact. So my quota is full and there is nothing I can do to get back my free space.

How to reproduce?
1. Set quota to 1G
2. Push an image that has over 1G in total (exceeding the quota)
The quota will be full but there will be no repository in the project.

How can I deal with it, besides extending the quota and pushing again?

Thanx for your help!

**Comment by kuznetsovkk** [comment]
GC doesnt help?

**Comment by umberto10** [comment]
oh, now it's working, but it took him quite a lot of time to be aware of those unused blobs.
Thanks for the support!
