### ISSUE TITLE
Way to provide authentication when using private registry for pull through cache.

### ISSUE THREAD

**Issue by Kaitou786** [goharbor/harbor#18133]
Hi I am trying to use harbour as a pull through cache for a private registry which requires to provide authentication for it work

I am not sure if this is supported; if it is how can I configure it.

Thanks for the help in advance!

**Comment by kuznetsovkk** [comment]
https://goharbor.io/docs/2.7.0/administration/configure-proxy-cache/
Before creating a proxy cache project, [create a registry endpoint](https://goharbor.io/docs/2.7.0/administration/configuring-replication/create-replication-endpoints/) for the proxy cache project to use. See how to create a registry endpoint.
Proxy cache projects can pull every image from the target registry that the access account you configure in the registry endpoint has access to. This means that Harbor users with access to the proxy cache project are able to pull any image available to the access account in the target repository.
https://goharbor.io/docs/2.7.0/administration/configuring-replication/create-replication-endpoints/
Enter the Access ID and Access Secret for the endpoint registry instance.

Use an account that has the appropriate privileges on that registry, or an account that has write permission on the corresponding project in a Harbor registry

**Comment by Kaitou786** [comment]
Thanks for the response,
I went through this right now and while creating the registry endpoint for google gcr.

Where do we need to put the secret json
In the access key or the secret key?

Also 'The namespace should start with the project ID.' Not sure if I follow what this mean on the roc

Couldn't understand it clearly from the docs.

Thanks!

**Comment by stonezdj** [comment]
see https://goharbor.io/docs/2.7.0/administration/configuring-replication/create-replication-endpoints/#access-id-and-secret-configuration
<img width="511" alt="Screen Shot 2023-01-27 at 14 01 07" src="https://user-images.githubusercontent.com/2696760/215019978-811fbde1-f77b-44e8-bcdc-c7369cd5e156.png">

**Comment by Kaitou786** [comment]
Thanks was able to make it work
