### ISSUE TITLE
Upgrade AWS Go SDK dependency

### ISSUE THREAD

**Issue by caleblloyd** [goharbor/harbor#18134]
#17932 introduces a change that depends on the AWS Go SDK to set credentials properly when none are supplied

The current  `aws-sdk-go` version in `go.mod` is [v1.34.28](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.28) from Sep 21, 2020

The most recent `aws-sdk-go` version is [v1.44.187](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.187)

I have not read all of the release notes (they auto-release almost daily), but I imagine in the past 2 years there have been improvements to detection for default credentials. Therefore I think it would be good to update this dependency.

I saw in `CONTRIBUTING.md` that maintainers handle dependency updates/vendoring.  Would it be possible to do the equivalent of:

```
go get -u github.com/aws/aws-sdk-go
```

Thanks!

**Comment by Vad1mo** [comment]
makes sense to update it
