### ISSUE TITLE
Upgrade Harbor from v2.0.2 to 2.7.0

### ISSUE THREAD

**Issue by devang704** [goharbor/harbor#18130]
Hi, 

We are using harbor as private registry to store docker images. We using harbor v2.0.2 deployed with helm chart on kubernetes cluster and now we want to upgrade it to v2.7.0

Can we directly upgrade from 2.0.2 > 2.7.0 or we have to move like 2.0.2 > 2.1.0 > 2.2.0 > 2.3.0 ... > 2.7.0.

Can you please suggest the way.

**Comment by chlins** [comment]
The recommended upgrade path is 2.0.x -> 2.2.x -> 2.4.x -> 2.6.x -> 2.7.x.
