### ISSUE TITLE
期望同一版本镜像保持不同架构，目前测试好像被覆盖

### ISSUE THREAD

**Issue by xiaoxiaojushi-ivan** [goharbor/harbor#18150]
期望同一版本镜像保持不同架构，目前测试好像被覆盖。
是否可以像dockerhub 一样支持同版本不同架构呢？

**Comment by MinerYang** [comment]
Do you mean multi-arch or multi-platform images? We do support this kind of artifact.
Would you provide more info/details of your requirement?
THX
