### ISSUE TITLE
replication with Accessories before the artfact will return error

### ISSUE THREAD

**Issue by sundaykeke** [goharbor/harbor#18153]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version:  2.6.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MinerYang** [comment]
Hi @sundaykeke,

Could you provide the steps of reproduce your issue. Thanks!
