### ISSUE TITLE
Support deploying to ECS

### ISSUE THREAD

**Issue by jamesfmaccoll** [goharbor/harbor#18162]
Can Harbor be deployed to ECS? I'd like to keep Harbor out of Kubernetes/EKS for redundancy, just wondered anyones thoughts?

**Comment by MinerYang** [comment]
We have limited experience on ECS. Need help from community. 
If it is Kubernetes compatible, you could have a try on harbor-helm installation. If not, please confirm with ECS team.
Thanks
