### ISSUE TITLE
Linking 2 harbor that are located in different places

### ISSUE THREAD

**Issue by aminellouz** [goharbor/harbor#18168]
Hello ,
I have a problem in linking 2 harbor registry. When i use the public ip address as a hostname the ping works fine but i can't do docker login and pull / push images. In the other hand, when i use a private ip address i can login and pull / push to harbor but the 2 harbor can't ping to each other

**Comment by ZrytyADHD** [comment]
Hmm,
I have the similiar problem and resolve it setting replication rule between them to have the same images on both servers.

**Comment by MinerYang** [comment]
This is something related to Network. We don't think this a harbor issue.

**Comment by aminellouz** [comment]
> This is something related to Network. We don't think this a harbor issue.

i don't think is network problem , because when i use docker registry as Provider it works. i m facing this problem only when i use harbor as a Provider.

**Comment by aminellouz** [comment]
> Hmm, I have the similiar problem and resolve it setting replication rule between them to have the same images on both servers.

how did you resolve it ?

**Comment by ZrytyADHD** [comment]
https://goharbor.io/docs/1.10/administration/configuring-replication/
I use this

**Comment by aminellouz** [comment]
![image](https://user-images.githubusercontent.com/83273119/217847498-70df291b-2523-4b45-aa31-705d0b8191e1.png)

**Comment by aminellouz** [comment]
![image](https://user-images.githubusercontent.com/83273119/217847985-5af61c82-6db5-44e3-9131-221f321d64ac.png)

**Comment by aminellouz** [comment]
![image](https://user-images.githubusercontent.com/83273119/217848111-7277c3ca-3a33-4b2c-95c8-511c3d846b14.png)
![image](https://user-images.githubusercontent.com/83273119/217848379-b79de94d-178c-4a12-8048-f640bb953f0c.png)
