### ISSUE TITLE
Requirement to update the endpoint url to push helm charts

### ISSUE THREAD

**Issue by suprita23** [goharbor/harbor#18163]
Hello team,
We are planning to migrate our existing chart-museum & registry to goharbor.  
Registry migration is smooth as all the existing apps will work smoothly with a rerouting.
However, with the chart-museum migration, there is a slight issue. 
The goHarbor exposes its endpoint to push/pull charts as https://goharbor/chartrepo/sample .. There is an extra subpath "**chartrepo**" which is causing a glitch for the smooth transition. We do not want to disrupt our already running processes, by introducing an extra step to update their scripts to add an extra "chartrepo" in the path.

When we do a url rewrite on the dns to automatically add /**chartrepo** to the path whenever goharbor is the hostname through Ingress rules, we get a failure on chart push (**helm push chartname.tgz https://goharbor/sample**)

Error: 404: could not properly parse response JSON: <!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>

Can we get some help on resolving this issue..

**Comment by zyyw** [comment]
@suprita23 The chart-museum component is going to be deprecated in Harbor v2.8.0. Please store helm charts in Harbor registry as oci-compatible artifacts.

**Comment by suprita23** [comment]
Thank you @zyyw for the reply. We can surely explore the option to move away from Chartmuseum. 
However, in the meantime, is there a way to rewrite the chartmuseum access url to not have "chartrepo" in the access url? 
This will help us keep the transition smooth.
