### ISSUE TITLE
unauthorized to access repository

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#18161]
Hello,

I am getting action: pull: unauthorized to access repository: ds-centos, action: pull post every upgrade for some hours and then it goes away.
Is it a known issue?
I do have any failure logs in harbor for the same.

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 2
Redis VM 3(Master-Slave-Slave)
Harbor Version v2.6.2
Docker version 19.0.0
docker-compose version 1.26

**Comment by MinerYang** [comment]
Did you pull from a private repository without proper role login?

**Comment by AyushCloud** [comment]
Hello,

I pulled from private registry with proper login credentials.
In the first try it failed but then it succeeds and i was able to see the issue with multiple users.

Is there any change or reload in redis database after we upgrade it.
Because after some hours it was fine.

Thank You,
Ayush

**Comment by stonezdj** [comment]
You should share these files between two Harbor vms

```
/data/secret/core/private_key.pem
/data/secret/registry/root.crt


```
and keep the same CSRF_KEY in <harbor install path>/common/config/core/env file

**Comment by AyushCloud** [comment]
Thank You @stonezdj. private key and root.crt are same. i will keep the CSRF_KEY also identical on Harbor VMs

**Comment by AyushCloud** [comment]
Hello,

I am facing this issue only during docker pull/push and not through Harbor UI.

Thanks,
Ayush

**Comment by stonezdj** [comment]
maybe another file should be synced
```
/data/secret/keys/secretkey
```

**Comment by AyushCloud** [comment]
Yes with secretkey, I am syncing servert.crt and server.key also

**Comment by stonezdj** [comment]
Is there any problem with the docker login right now?

**Comment by AyushCloud** [comment]
Hello,

Actually we are not using docker login, we use docker config to pull and push the images.
And now it is working fine but we have this issue after every upgrade.

Thank You,
Ayush

**Comment by stonezdj** [comment]
You should do the same steps after the upgrade.

**Comment by AyushCloud** [comment]
Hello,

I restart one Harbor VMs and see in the core.logs below error

Feb 14 09:15:28 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:28Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:28 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:28Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="f36dd19b-56da-4bc8-acfc-7eca7ca69f7c"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:33 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:33Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:33 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:33Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="c185a455-3cdb-4c28-9554-6da2010ab2c9"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:33 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:33Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:33 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:33Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="5c3735d1-4bd2-49ff-a205-fec3d6ef32a7"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:35 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:35Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:35 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:35Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="7bbea9d5-b7a1-481c-a4a1-17ed1c43e70a"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:46 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:46Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:46 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:46Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="894222f7-0d8c-45f5-a717-c1ee8f81c21c"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:50 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:50Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:50 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:50Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="f20f2c27-f0a0-460f-b4ae-2a9d0a69f0ba"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:51 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:51Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:51 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:51Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="c0599622-a58a-49e4-a3a4-b5e9a9f30023"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:52 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:52Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:52 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:52Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="1cad1610-e0af-479a-8bc4-a6e8351ad481"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:54 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:54Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:54 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:54Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="9e4257e1-d672-44c9-b644-ddf22d9afab5"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:54 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:54Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:54 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:54Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="9adad2d7-3b88-49ea-8595-b085855fa70e"]: failed to decode bearer token: token is not valid yet
Feb 14 09:15:55 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:55Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet
Feb 14 09:15:55 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:15:55Z [WARNING] [/server/middleware/security/v2_token.go:52][requestID="8f4878a6-5339-46ff-9f62-4d9346349168"]: failed to decode bearer token: token is not valid yet
Feb 14 09:16:00 ip-172-22-0-1.eu-west-2.compute.internal core[9786]: 2023-02-14T09:16:00Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet


Could you please help.


Thank You,
Ayush
