### ISSUE TITLE
Charts can be only replicated (pushed) if project is set to public

### ISSUE THREAD

**Issue by DarioCalovic** [goharbor/harbor#18171]
**Expected behavior and actual behavior:**
We are trying to sync images and charts between 2 harbor instances. We have a push-based Replication-Rule from Harbor A (with Version v2.5.3-797c3536) to Harbor B (with Version v2.6.0-b035ca7c). The user used for the synchronization from the Harbor B has all permissions assigned. Images are being pushed successfully but charts not. Only when you we set the project on the Harbor B to public the charts are being pushed successfully as well.

**Steps to reproduce the problem:**
When I manually trigger the replication rule while the project-on-b is set to public, I receive following error:
`failed to check the existence of chart project-on-b/some-chart:0.0.1 on the destination registry: http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"user-on-b"}]}`

**Comment by MinerYang** [comment]
Chart museum is going to be deprecated in v2.8.0. We don't provide any further support on this. You could transfer to OCI compatible artifact.
