### ISSUE TITLE
Tag retention tab is missing 

### ISSUE THREAD

**Issue by wh1test** [goharbor/harbor#18185]
Could somebody say why I'm not able to see Tag retention tab in my harbor?
Harbor version v2.7.0-864aca34
It was deployed as docker compose.
![image](https://user-images.githubusercontent.com/5803602/217228454-95b05b23-646f-40ce-977f-96c0d55c63fc.png)

**Comment by MinerYang** [comment]
Hi @wh1test ,

It's belongs to the `Policy` tab inside every project
https://goharbor.io/docs/2.7.0/working-with-projects/working-with-images/create-tag-retention-rules/

**Comment by wh1test** [comment]
Hi @MinerYang ,
Yeah, I got it. Thank you very much!
