### ISSUE TITLE
why page_size in query should be less than or equal to 100 #v2.6.2

### ISSUE THREAD

**Issue by xwb1993** [goharbor/harbor#18194]
My harbor version is v2.6.2，when i list projects and set page_size more than 100 like this，http://xxx/api/v2.0/projects?page=1&page_size=101，can't get projects and received an error："validation failure list:\npage_size in query should be less than or equal to 100".
    How can i list projects more than 100 or someone can tell me where is the limit in harbor source code?Thanks bro!!

**Comment by xwb1993** [comment]
And i didn't have this problem when use harbor v2.0.0 and another low version.

**Comment by AllForNothing** [comment]
@xwb1993 
Listing a large number of projects will have performance problems. So we limit the maximum page size to 100.

If you want to list projects of more than 100,  you can call the API for (total/100 + 1) times. It's an inconvenience, but it's a workable solution

**Comment by xwb1993** [comment]
> @xwb1993 Listing a large number of projects will have performance problems. So we limit the maximum page size to 100.
> 
> If you want to list projects of more than 100, you can call the API for (total/100 + 1) times. It's an inconvenience, but it's a workable solution

感谢大佬回复！可以留个联系方式吗？在这上面提问时效性太慢，有harbor的问题想要请教，这是我的qq：248229339。

**Comment by AllForNothing** [comment]
@xwb1993 
可以直接使用Slack APP  在  CNCF  下 的Harbor  频道提问（https://cloud-native.slack.com/archives/CC1E09J6S）
