### ISSUE TITLE
Invalid docs for trivy install

### ISSUE THREAD

**Issue by flaxeneel2** [goharbor/harbor#18203]
Hi there!
I recently startetd trying out harbor, but when i followed docs for an install with trivy, it did not accept the exact command i posted that i took from the documentation 
```sh
sudo ./install.sh --with-notary --with-trivy --with-chartmuseum
```

Looks like it did not like the `--with-trivy` argument, so i took a look at the install.sh script, and i found that it does not even accept the `--with-trivy` argument.

```sh
while [ $# -gt 0 ]; do
        case $1 in
            --help)
            note "$usage"
            exit 0;;
            --with-notary)
            with_notary=true;;
            --with-clair)
            with_clair=true;;
            --with-chartmuseum)
            with_chartmuseum=true;;
            *)
            note "$usage"
            exit 1;;
        esac
        shift || true
done
```

I also tried passing it to thhe prepare image directly, but that did not work either.

Do the docs need to be updated or something? I also tried running trivy seperately and making harbor use it, but that did not work either for some reason

This was taken from the v1.10.16 offline installer.

**Comment by wy65701436** [comment]
yes, it's because that the trivy was not integrated into harbor v1.10, please try with the latest support versions(**v2.5+**).
