### ISSUE TITLE
Why does the source code refer to the restapi and models, but there is no such package

### ISSUE THREAD

**Issue by xwb1993** [goharbor/harbor#18218]
Ay harbor version is v2.6.2

![image](https://user-images.githubusercontent.com/18282502/218674779-a660d5ed-6f1b-45d0-982b-2be21707836a.png)

**Comment by xwb1993** [comment]
@AllForNothing

**Comment by AllForNothing** [comment]
You need to run `make gen_apis`( https://github.com/goharbor/harbor/blob/main/Makefile#L341)   to generate the APIs and models
