### ISSUE TITLE
Allow .trivyignore

### ISSUE THREAD

**Issue by Jeansen** [goharbor/harbor#18225]
**Is your feature request related to a problem? Please describe.**
When scanning images with trivy, there will be a report with all found CVEs. That's great. One can also decide to allow image distribution with an allow list. Unfortunately, the trivy report always shows the full report. There is now way to filter allowed CVEs from the report, too.

**Describe the solution you'd like**
We have the following use-case. Whenever an image was pushed in harbor, it will be scanned with trivy. After that a webhook is called pushing the result of the scan to a team to a simple service which will then forward it to a team channel, if there a high or critical issues. Now, the team is already aware of irrelevant or currently not fixable CVEs. They would like to have them (temporarily) ignored and only get informed if there are new CVEs.

In practice I could imagine a similar configuration setting as is already available with the allow-list but for the trivy report itself.

For instance, manual trivy scans (not in harbor), can be configured (by means of e.g. a .trivyignore file) to only show relevant CVEs to a user.  I'd be happy to see something similar in harbor where a .trivyignore could be configured on a system-wide or project-wide scope.

**Comment by chlins** [comment]
There is a feature CVE export introduced since v2.6, this can help to filter CVEs by some defined rules, you can try to use this function. FYI: https://goharbor.io/blog/harbor-2.6/

**Comment by Jeansen** [comment]
Interesting feature, but does not really help with the use-case above. But thank you, anyway for pointing it out.

**Comment by zyyw** [comment]
Trivy in Harbor currently only support parameterized filter such as `--vuln-type`, and .trivyingore is not supported:
* https://aquasecurity.github.io/trivy/v0.22.0/vulnerability/examples/filter/

If you would like the support of this .trivyignore feature, please try to open an issue in the following repo:
* https://github.com/aquasecurity/harbor-scanner-trivy

**Comment by Jeansen** [comment]
@zyyw Thank you. Closing this one in favor of https://github.com/aquasecurity/harbor-scanner-trivy/issues/310
