### ISSUE TITLE
Can not upgrade from any of the 2.6.0 ~ 2.6.2 to 2.7.0

### ISSUE THREAD

**Issue by Dany-krstv** [goharbor/harbor#18252]
I'm trying to upgrade from either 2.6.0 or 2.6.2 to 2.7.0 but I get this error in the postgresql log:

`"Upgrading from PostgreSQL 9.6 to PostgreSQL 13 is not supported in the current Harbor release. You should upgrade to previous Harbor firstly, then upgrade to current release." `

By the documentation I should be able to upgrade from both versions (2.6.0 or 2.6.2) but I get the same error.
I've tried upgrading it to v2.6.3 and it was successful which is strange because I see that this version is using the newer postgresql version.

Maybe I'm missing something?

**Comment by chlins** [comment]
Did you have old data volume for database?

**Comment by LeoMoshko** [comment]
I get this error on a clean install.

Error: Upgrading from PostgreSQL 9.6 to PostgreSQL 13 is not supported in the current Harbor release.
You should upgrade to previous Harbor firstly, then upgrade to current release.

DB image = goharbor/harbor-db:v2.7.

**Comment by YangJiao0817** [comment]
Does this file(`${data_volume}/database/PG_VERSION`) exist under your data_volume? This file should not exist if this is your first installation, this file only exists in Harbor using pg9.6.

**Comment by AtaraxiaRun** [comment]
I had this problem today too:
Upgrading from PostgreSQL 9.6 to PostgreSQL 13 is not supported in the current Harbor release.
You should upgrade to previous Harbor firstly, then upgrade to current release.

As a result, I repeatedly restarted goharbor/harbor-db:v2.8.2 and goharbor/harbor-jobservice:v2.8.2

[root@rabbitmq-node2 harbor]# docker images
REPOSITORY                    TAG       IMAGE ID       CREATED       SIZE
goharbor/redis-photon         v2.8.2    6f4498a430ca   2 weeks ago   121MB
goharbor/harbor-registryctl   v2.8.2    fa61a236a6d6   2 weeks ago   142MB
goharbor/registry-photon      v2.8.2    f80e71363231   2 weeks ago   79.3MB
goharbor/nginx-photon         v2.8.2    3d009028f260   2 weeks ago   120MB
goharbor/harbor-log           v2.8.2    2914d282d9bf   2 weeks ago   127MB
goharbor/harbor-jobservice    v2.8.2    40118f1568a8   2 weeks ago   141MB
goharbor/harbor-core          v2.8.2    0bbbd1f379fc   2 weeks ago   165MB
goharbor/harbor-portal        v2.8.2    3e74e0758aa4   2 weeks ago   127MB
goharbor/harbor-db            v2.8.2    5126635ae9f0   2 weeks ago   174MB
goharbor/prepare              v2.8.2    eb3cf3cdd17a   2 weeks ago   163MB
[root@rabbitmq-node2 harbor]# docker ps
CONTAINER ID   IMAGE                                COMMAND                   CREATED         STATUS                             PORTS                                   NAMES
86bd43d71778   goharbor/nginx-photon:v2.8.2         "nginx -g 'daemon of…"   5 minutes ago   Up 5 minutes (healthy)             0.0.0.0:80->8080/tcp, :::80->8080/tcp   nginx
be05c0f23e76   goharbor/harbor-jobservice:v2.8.2    "/harbor/entrypoint.…"   5 minutes ago   Restarting (2) 54 seconds ago                                              harbor-jobservice
77f3506ed591   goharbor/harbor-core:v2.8.2          "/harbor/entrypoint.…"   5 minutes ago   Up 45 seconds (health: starting)                                           harbor-core
8830d56cd4af   goharbor/redis-photon:v2.8.2         "redis-server /etc/r…"   6 minutes ago   Up 5 minutes (healthy)                                                     redis
45ce70eeed50   goharbor/harbor-portal:v2.8.2        "nginx -g 'daemon of…"   6 minutes ago   Up 5 minutes (healthy)                                                     harbor-portal
8be4ba84d050   goharbor/registry-photon:v2.8.2      "/home/harbor/entryp…"   6 minutes ago   Up 5 minutes (healthy)                                                     registry
602733c7460c   goharbor/harbor-registryctl:v2.8.2   "/home/harbor/start.…"   6 minutes ago   Up 5 minutes (healthy)                                                     registryctl
13c53362ba64   goharbor/harbor-db:v2.8.2            "/docker-entrypoint.…"   6 minutes ago   Restarting (1) 56 seconds ago                                              harbor-db
e4e9282d449d   goharbor/harbor-log:v2.8.2           "/bin/sh -c /usr/loc…"   6 minutes ago   Up 5 minutes (healthy)             127.0.0.1:1514->10514/tcp               harbor-log

**Comment by rverchere** [comment]
Hi,

I have the same issue here. Could you reopen the issue, as I did not see revelant solution?

Harbor installed with helm, currently running version v2.6.4-77903faf.

Postgres running version 13.10 :

```shell
❯ kubectl exec -it harbor-harbor-database-0 -- bash
Defaulted container "database" out of: database, data-migrator (init), data-permissions-ensurer (init)
postgres [ / ]$ psql
psql (13.10)
Type "help" for help.

postgres=# select version();
                                    version                                    
-------------------------------------------------------------------------------
 PostgreSQL 13.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.0, 64-bit
(1 row)

postgres=# \l
                                   List of databases
     Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
--------------+----------+----------+-------------+-------------+-----------------------
 notaryserver | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 notarysigner | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 registry     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
(6 rows)

postgres=# 
```

When I upgrade to chart 1.11.2, which is harbor version 2.7.2, I have the same issue on database complaining migrating from 9 to 13.
