### ISSUE TITLE
Failed to synchronize Alibaba Cloud image

### ISSUE THREAD

**Issue by yunweidage** [goharbor/harbor#18256]
Harbor Version：v1.10.16
Warehouse management has been configured，Configured Aliyun AccessKey
When starting the replication task, the following error occurs

Can you see the lack of users through the log?
![image](https://user-images.githubusercontent.com/25795668/220257864-65482cd7-6523-43cf-8eb4-7d51df47d8e8.png)

![image](https://user-images.githubusercontent.com/25795668/220257545-f0366237-3d97-4443-bd99-a9a789549ae5.png)

**Comment by yunweidage** [comment]
Using RAM account and AK failed，

**Comment by chlins** [comment]
@kofj Could you please take a look?

**Comment by kofj** [comment]
@yunweidage Are you init the ACR account?  Read below:
https://developer.aliyun.com/article/1170591
