### ISSUE TITLE
The tag retention and tag immutable policies are not deleted after deleting the project

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#18250]
**Steps to reproduce the problem:**
1. Create a project
2. Create tag retention and tag immutable policies to project
3. Set tag retention policies policy schedule
4. Delete this project
5. tag retention and tag immutable policies still exist
<img width="1399" alt="图片" src="https://user-images.githubusercontent.com/72076317/220045582-566024df-e26f-4b21-af07-ae7106111ee4.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.5.x ~ v2.7.x

**Comment by chlins** [comment]
We should consider introducing new modules or ways to handle this recycling scenario, and perform asynchronous processing through events to improve usability and scalability. Of course, it is not limited to this scenario, and other parts can also be refactored into new ways. We can investigate GRPC, message queue and some other technologies.
