### ISSUE TITLE
Harbor Proxy Cache

### ISSUE THREAD

**Issue by saudade76** [goharbor/harbor#18270]
According to Harbor docs, I see the following sentence. https://goharbor.io/docs/2.5.0/administration/configure-proxy-cache/ 
-	“If the target registry is not reachable, the proxy cache project serves the cached image”
If that is true, my harbor system SHOULD serve the cached image in case of internet disconnection & cached images in harbor. However, as testing result, with the blocking https://registry-1.docker.io system (via IPTABLES rule), it doesn’t serve the cached artifact.
I see the following i/o timeout message, and docker pull failed to receive the cached artifact (i.e. nginx container image).

[harbor core log]
**2023-02-20T00:24:32Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://registry-1.docker.io: Get https://registry-1.docker.io/v2/: dial tcp 34.205.13.154:443: i/o timeout
2023-02-20T00:28:39Z [ERROR] [/server/middleware/repoproxy/proxy.go:240]: current registry is unhealthy, regID:2, Name:Docker Hub, Status: unhealthy**

[docker pull error message]
root@labtest:~# docker pull harbor.openmsa.monster:4443/docker_proxy/library/nginx
Using default tag: latest
Error response from daemon: unknown: artifact docker_proxy/library/nginx:latest not found
 
![image](https://user-images.githubusercontent.com/74942851/220766071-d6fdb501-6cf2-4f6f-8c06-2ac696453fe1.png)

Best Regards,
Thomas

**Comment by stonezdj** [comment]
We cannot comfirm the image is cached with your screenshot, could you please click the repository and show us the artifact in it?

**Comment by stonezdj** [comment]
Because the tag is not created locally, it returns 404 for the pull request when the dockerhub is unreachable.
