### ISSUE TITLE
Proxy Cache Image Tags and Vulnerability Scanner

### ISSUE THREAD

**Issue by gilAqua** [goharbor/harbor#18276]
When integrating the Aqua Vulnerability Scanner with Harbor, it doesn't appear Harbor is passing along the Named image tag that is being pulled to the Vulnerability Scanner. The Tag field is not populated. This isn't an issue for non-Proxy Cache. 

Expected Behavior
1) Configure the Aqua Harbor Plugin with the SCANNER_AQUA_USE_IMAGE_TAG=true 
2) Configure a Proxy Cache Project to scan on push. 
3) Pull an Image from a Proxy Cache Project using a named tag 
4) Harbor sends API to scanner with image named tag 
5) Aqua scans the image using named tag 

Actual Behavior
1) Configure the Aqua Harbor Plugin with the SCANNER_AQUA_USE_IMAGE_TAG=true
2) Configure a Proxy Cache Project to scan on push. 
3) Pull an Image from a Proxy Cache Project using a named tag 
4) Harbor sends API to scanner with a blank 'tag' field 
5) Aqua attempts to scan the image but doesn't have a tag to use other than the default "latest" which may not even exist 
6) Scan fails because the original name tag isn't passed to the scanner 

Example: 

Notice the Tag is empty even if the image being pulled has a named tag. 

2023-02-23T19:54:24Z [INFO] [/pkg/scan/job.go:385]: {
  "uuid": "9cee4b4e-2ee3-11ed-95c7-72578b7d321d",
  "name": "Aqua",
  "description": "Gil Test",
  "url": http://gfharbor-harbor-scanner-aqua:8080/,
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": true,
  "use_internal_addr": false,
  "adapter": "Aqua Enterprise",
  "vendor": "Aqua Security",
  "version": "scannercli version 6.5.23016, compiled Jan 23 2023 14:36:36\n",
  "create_time": "2022-09-07T19:31:04.36704Z",
  "update_time": "2022-09-07T19:31:04.367042Z"
}
2023-02-23T19:54:24Z [INFO] [/pkg/scan/job.go:385]: {
  "registry": {
    "url" <Removed>,
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 4,
    "repository": "gilproxy/brahim7/test-php",
    **"tag": "",**
    "digest": "sha256:dbf36e1fa5af36fe5c72f8d42933414988427f7f584d462f4c7112c0dfdcd963",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }

Shouldn't Harbor populate the tag field with the named tag?

The named tag works for non-Proxy Cache Projects.

- harbor version: 2.5.3
- running on k3s 
- containerd

**Comment by stonezdj** [comment]
It maybe related to the client behavior(docker/containerd)
Sometimes even you issue a command with pull by tag, such as 
```
gilproxy/brahim7/test-php:v1.1.0
```
If this tag already cached in local with a digest, then it will send request to Harbor with digest directly.
```
gilproxy/brahim7/test-php@sha256:dbf36e1fa5af36fe5c72f8d42933414988427f7f584d462f4c7112c0dfdcd963
```
Then the harbor proxy server doesn't receive the pull by tag command and it can't create a tag for this digest.
and the tag field send to scanner will be blank.

Is it possible to scan the image by digest when it is missed?

**Comment by gilAqua** [comment]
Thanks! 

The link you sent may very well be related. I say this because I noticed that Harbor appeared to associate a tag in the UI but only after a long while. It could be a timing/order issue.

Right now, the workaround is to fall back to sha digest if the tag is empty, but this isn't the desired behavior. 

 I will do some testing to confirm and report back.
