### ISSUE TITLE
COre container is restarting 

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#18277]
Hello,

core container is restarting with below error.

Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: panic: unexpected EOF
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: goroutine 424924 [running]:
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/beego/beego/orm.(*DB).QueryRow(0x386a233?, {0xc000150c40?, 0xc0028a4be8?}, {0xc003b8f0f0, 0x1, 0x1})
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/vendor/github.com/beego/beego/orm/db_alias.go:206 +0xe7
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/beego/beego/orm.(*dbBase).Read(0xc00011fa30, {0x3dd0308, 0xc000b1faa0}, 0xc0001f3b80, {0x3731360?, 0xc001db81a0?, 0x1ae082b?}, 0xc000aff530?, {0x0, 0x0, ...}, ...)
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/vendor/github.com/beego/beego/orm/db.go:361 +0x786
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/beego/beego/orm.(*orm).Read(0xc001779d60, {0x344f820?, 0xc001db81a0?}, {0x0, 0x0, 0x0})
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/vendor/github.com/beego/beego/orm/orm.go:129 +0xdc
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/pkg/artifact/dao.(*dao).Get(0x10?, {0x3dc7018, 0xc000aff530}, 0x100)
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/pkg/artifact/dao/dao.go:118 +0x88
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/pkg/artifact.(*manager).Get(0xc0004eef80, {0x3dc7018, 0xc000aff530}, 0x18?)
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/pkg/artifact/manager.go:87 +0x33
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/controller/artifact.(*controller).Get(0xc000156000, {0x3dc7018, 0xc000aff530}, 0x37f9e24?, 0xc002e1c648?)
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/controller/artifact/controller.go:260 +0x39
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/controller/event/handler/p2p.(*Handler).handlePushArtifact(0x5455670?, {0x3dc7018, 0xc000aff530}, 0xc000aa8428)
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/controller/event/handler/p2p/preheat.go:69 +0x1b3
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/controller/event/handler/p2p.(*Handler).Handle(0x0?, {0x3dc7018?, 0xc000aff530?}, {0x344e6a0?, 0xc000aa8428?})
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/controller/event/handler/p2p/preheat.go:42 +0x50
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1.1()
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: #011/harbor/src/pkg/notifier/notifier.go:201 +0xff
Feb 21 09:11:06 ip-172-26-0-1.cn-north-1.compute.internal core[10460]: created by github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1

nginx logs

7a31a32b13e46d3f9768b352debf HTTP/1.1", upstream: "http://172.26.0.8:8080/v2/blobs/uploads/039-84b9-97da9c7d9869?_state=KHWsGVOH-DlUKfr8kqtHqrNcY7PgRVGWhmY8eojNkul7Ik5hbWUiOiJwcm9kdWN0aW9uL2NvbXBvbmVudHMvbW9uaXRvcmluZy1hZ2VudC1rOHMiLCJVVUlEIjoiMWUyYTA2OWQtNjAxYy00MDM5LTg0YjktOTdkYTljN2Q5ODY5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIzLTAyLTIxVDExOjU0OjQxLjIzMzMzMjI5OFoifQ%3D%3D&digest=sha256%3A17fec3f5ab00f3fb8278165971f11b27ef087", host: "127.0.0.1:6443"
Feb 21 11:56:39 ip-172-26-0-1.cn-north-1.compute.internal proxy[10460]: 2023/02/21 11:56:39 [error] 8#0: *199786 upstream prematurely closed connection while reading response header from upstream, client: 172.31.39.29, server: , request: "PUT /v2/ds-mariadb/blobs/uploads/4537cef4-aad5?_state=FcVCMcVC2GB74ihIHVZYZfmw8eA8-P0VNcHmPOcr_x57Ik5hbWUiOiJwcm9kdWN0aW9uL2RldmVudmkxMDgvZHMtbWFyaWFkYiIsIlVVSUQiOiI0NTM3Y2VmNC1hYWQ1LTQ4MTktODc5My1iZjBiNmI2NTY1ODIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMDItMjFUMTE6NDk6MDkuMzQ4NDg3MjNaIn0%3D&digest=sha256%80da848bff24116377b5321e HTTP/1.1", upstream: 

We got these restart when replication is running around 450Gb of data

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 2
Redis VM 3(Master-Slave-Slave)
Harbor Version v2.7.0
Docker version 19.0.0
docker-compose version 1.26

**Comment by chlins** [comment]
Did you use the external database and could you provide the db logs?

**Comment by AyushCloud** [comment]
Hello,

Yes, i am using the external database and also haproxy container to handle the Master/replica on database VMs

haproxy:
    image: 
[postgresql-Thu.log](https://github.com/goharbor/harbor/files/10860555/postgresql-Thu.log)
[postgresql-Sat.log](https://github.com/goharbor/harbor/files/10860556/postgresql-Sat.log)
[postgresql-Mon.log](https://github.com/goharbor/harbor/files/10860557/postgresql-Mon.log)
[postgresql-Fri.log](https://github.com/goharbor/harbor/files/10860558/postgresql-Fri.log)
goharbor/haproxy:2.2
    container_name: haproxy-postgresql
    restart: on-failure:8
    security_opt:
      - no-new-privileges:true
    pids_limit: 50
    cpu_quota: 50000
    healthcheck:
      test: "exit 0"
    depends_on:
      - log
    volumes:
      - /usr/local/harbor/HAProxy:/usr/local/etc/haproxy:ro
      - type: bind
        source: /usr/local/harbor/HAProxy/pgsql-agent-check
        target: /usr/local/sbin/pgsql-agent-check
    ports:
      - 5432
    networks:
      - harbor
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "haproxy"

**Comment by chlins** [comment]
@AyushCloud Hi, the logs for haproxy would also be helpful to debug this issue, thanks.

**Comment by AyushCloud** [comment]
Hello,

PFB the haproxy container logs

Mar 22 23:59:59  haproxy[10047]: 172.22.0.8:39984 [22/Mar/2023:23:54:59.479] fr_pg bk_pg/pg_011 1/0/300037 13784 -- 3/3/2/1/0 0/0
Mar 23 00:00:00  haproxy[10047]: 172.22.0.8:52466 [23/Mar/2023:00:00:00.965] fr_pg bk_pg/pg_011 1/0/17 1976 -- 6/6/5/4/0 0/0
Mar 23 00:00:00  haproxy[10047]: 172.22.0.8:52252 [23/Mar/2023:00:00:00.771] fr_pg bk_pg/pg_011 1/2/211 8213 -- 5/5/4/3/0 0/0
Mar 23 00:00:02  haproxy[10047]: [WARNING] 081/000002 (9) : Server bk_pg/pg_011 is DOWN, reason: Layer4 timeout, info: " at initial connection step of tcp-check", check duration: 4ms. 0 active and 0 backup servers left. 4 sessions active, 0 requeued, 0 remaining in queue.
Mar 23 00:00:02  haproxy[10047]: Server bk_pg/pg_011 is DOWN, reason: Layer4 timeout, info: " at initial connection step of tcp-check", check duration: 4ms. 0 active and 0 backup servers left. 4 sessions active, 0 requeued, 0 remaining in queue.
Mar 23 00:00:02  haproxy[10047]: backend bk_pg has no server available!
Mar 23 00:00:02  haproxy[10047]: [ALERT] 081/000002 (9) : backend 'bk_pg' has no server available!
Mar 23 00:00:02  haproxy[10047]: [WARNING] 081/000002 (9) : Server bk_pg/pg_011 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
Mar 23 00:00:02  haproxy[10047]: Server bk_pg/pg_011 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
Mar 23 00:00:25  haproxy[10047]: 172.23.0.2:56862 [22/Mar/2023:23:59:35.082] fr_pg bk_pg/pg_011 1/0/50015 438 cD 5/5/4/3/0 0/0
Mar 23 00:00:50  haproxy[10047]: 172.22.0.8:52450 [23/Mar/2023:00:00:00.958] fr_pg bk_pg/pg_011 1/0/50041 1481 cD 5/5/4/3/0 0/0
Mar 23 00:00:51  haproxy[10047]: 172.22.0.10:56590 [23/Mar/2023:00:00:01.017] fr_pg bk_pg/pg_011 1/0/50008 807 cD 4/4/3/2/0 0/0
Mar 23 00:01:26  haproxy[10047]: 172.23.0.2:58734 [23/Mar/2023:00:00:35.082] fr_pg bk_pg/pg_011 1/1001/51012 438 cD 3/3/2/1/0 0/0
Mar 23 00:02:25  haproxy[10047]: 172.23.0.2:60050 [23/Mar/2023:00:01:35.083] fr_pg bk_pg/pg_011 1/0/50011 438 cD 3/3/2/1/0 0/0
Mar 23 00:03:25  haproxy[10047]: 172.23.0.2:33490 [23/Mar/2023:00:02:35.082] fr_pg bk_pg/pg_011 1/0/50012 438 cD 3/3/2/1/0 0/0
Mar 23 00:03:49  haproxy[10047]: [WARNING] 081/000349 (9) : Server bk_pg/pg_011 is DOWN, reason: Layer4 timeout, info: " at initial connection step of tcp-check", check duration: 4ms. 0 active and 0 backup servers left. 2 sessions active, 0 requeued, 0 remaining in queue.
Mar 23 00:03:49  haproxy[10047]: [ALERT] 081/000349 (9) : backend 'bk_pg' has no server available!
Mar 23 00:03:49  haproxy[10047]: Server bk_pg/pg_011 is DOWN, reason: Layer4 timeout, info: " at initial connection step of tcp-check", check duration: 4ms. 0 active and 0 backup servers left. 2 sessions active, 0 requeued, 0 remaining in queue.
Mar 23 00:03:49  haproxy[10047]: backend bk_pg has no server available!
Mar 23 00:03:49  haproxy[10047]: [WARNING] 081/000349 (9) : Server bk_pg/pg_011 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
Mar 23 00:03:49  haproxy[10047]: Server bk_pg/pg_011 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
Mar 23 00:04:25  haproxy[10047]: 172.23.0.2:35596 [23/Mar/2023:00:03:35.082] fr_pg bk_pg/pg_011 1/0/50010 438 cD 3/3/2/1/0 0/0
Mar 23 00:04:59  haproxy[10047]: 172.22.0.8:51040 [22/Mar/2023:23:59:59.519] fr_pg bk_pg/pg_011 1/0/300019 29894 -- 3/3/2/1/0 0/0
Mar 23 00:05:00  haproxy[10047]: 172.22.0.8:33082 [23/Mar/2023:00:05:00.977] fr_pg bk_pg/pg_011 1/0/4 0 -- 3/3/2/1/0 0/0
Mar 23 00:05:01  haproxy[10047]: 172.22.0.10:37188 [23/Mar/2023:00:05:01.024] fr_pg bk_pg/pg_011 1/0/3 0 -- 3/3/2/1/0 0/0
Mar 23 00:05:25  haproxy[10047]: 172.23.0.2:37524 [23/Mar/2023:00:04:35.082] fr_pg bk_pg/pg_011 1/0/50012 438 cD

**Comment by chlins** [comment]
@AyushCloud Hi, Is there any timeout-related configuration option in HAProxy that can be configured? Based on the logs you provided, it seems that the interruption of the connection between Harbor and the DB was caused by HAProxy, resulting in an EOF.
