### ISSUE TITLE
Unable to add hub.docker.com as a registry

### ISSUE THREAD

**Issue by richardtearle-nps** [goharbor/harbor#18279]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I'm unable to add https://hub.docker.com as a registry, as I receive the error "Failed to ping endpoint." I should be able to add docker hub as a registry.

**Steps to reproduce the problem:**

1. Log into harbor
2. Click on Registries
3. Click New Endpoint
4. Enter:
5. Name: docker-hub
6. Description: _left blank_
7. Endpoint URL: https://hub.docker.com
8. Access ID: _left blank_
9. Access Secret: _left blank_
10. Click Test Connection

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7.0
- podman engine version: 4.2.0
- docker-compose version: 2.15.1

**Additional context:**

harbor-core log:
```
2023-02-24T09:45:46Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://hub.docker.com: http status code: 404, body: <!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>404 : Docker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    * {
        line-height: 1.2;
        margin: 0;
    }

    html {
        color: #71859d;
        display: table;
        height: 100%!;(MISSING)
        text-align: center;
        width: 100%!;(MISSING)
    }

    body {
        background: #fff;
        display: table-cell;
        font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        font-weight: 300;
        margin: 2em auto;
        vertical-align: middle;
    }

    a {
        color: #22b8eb;
        text-decoration: none;
    }


    @media only screen and (max-width: 280px) {
        body,
        p {
            width: 95%!;(MISSING)
        }
    }
[SNIPPED]
```
I believe this is because the https://hub.docker.com/api/version has been removed. 

We have another installation of Harbor that already has docker hub as a registry, and that continues to function.

**Comment by Vad1mo** [comment]
Can not reproduce,  It might be your harbor pod can't reach docker hub.

**Comment by richardtearle-nps** [comment]
Thanks for trying, but as shown on the log output it can reach docker hub, it's just receiving a 404 for the api/version page - which I can confirm from a browser as well.

**Comment by chlins** [comment]
Did you choose the provider to `DockerHub` directly?
<img width="576" alt="image" src="https://user-images.githubusercontent.com/31262637/221529018-a596ff68-8682-4bcb-9b31-56d1fbeb08f1.png">

**Comment by richardtearle-nps** [comment]
D'oh no I wasn't. Sorry about that.
