### ISSUE TITLE
Replication Issue with GitLab

### ISSUE THREAD

**Issue by DisasteR** [goharbor/harbor#18284]
**Expected behavior and actual behavior:**
When I try to replicate projects from one of my gitlab instance some replication works as expected but others fail doing nothing (no task is created, nothing in logs)

**Steps to reproduce the problem:**
Create two replication rules for different gitlab project hosted in same gitlab instance (same group path, same credentials, gitlab user have same permissions on the two projects)
First one replicate as expected (Execution and Task)
Second one do nothing (Execution is created but no Task)

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.7.1]
- docker engine version: [23.0.1]
- docker-compose version: [1.26.0]

**Additional context:**
We tried upgrading from 2.5.3 to 2.7.1 but problem still exist.
We tried to remove project, replication rule and re-create them without any change.

There is nothing in the logs regarding the replications.

**Comment by AllForNothing** [comment]
@DisasteR Can you share your replication rule?

**Comment by DisasteR** [comment]
here is some of the non working one :

![image](https://user-images.githubusercontent.com/443279/223069391-b20f028a-9711-4e3b-955e-5e3863ea4b75.png)
![image](https://user-images.githubusercontent.com/443279/223070822-0f4901e9-830c-4464-aed5-753c3cbb7254.png)

![image](https://user-images.githubusercontent.com/443279/223069687-304d4dcf-835f-44fe-bc65-47c80dbd6a60.png)
![image](https://user-images.githubusercontent.com/443279/223070955-efe94a9c-04db-4ffe-95c1-204451df5c79.png)

![image](https://user-images.githubusercontent.com/443279/223072712-d44553cf-224a-4902-87d3-a249e1822436.png)
![image](https://user-images.githubusercontent.com/443279/223072846-bab98bbc-3ca9-4ada-a28c-b7f6debf226b.png)

The first project contain only one image on default project path.
The second one contain only one image on sub project path.
The third one contain multiple images on subs project path.

For these projects the replications where working before but now an execution is created without creating any tasks.

here is one working project :

![image](https://user-images.githubusercontent.com/443279/223071823-ebbe1786-fc4e-476d-a936-9056b2337feb.png)

This project contain only one image on default project path.

All the replication use the same user with same permission on each project.

**Comment by chlins** [comment]
Could you also provide the execution status screenshot?

**Comment by chlins** [comment]
@lxShaDoWxl Hi, could you please help to take a look for this issue?

**Comment by chlins** [comment]
@DisasteR I cannot reproduce the issue on my environment, so could you help to verify the pr at your environment?  I can build offline package to you, and then you can install a new harbor for testing.

**Comment by DisasteR** [comment]
@chlins i Can try that. Send me the offline package :)

**Comment by chlins** [comment]
@DisasteR Thanks, here is the offline package: https://drive.google.com/file/d/1lhqvWyHY8MVxN922I9TtWFDwMbcIVZHp/view?usp=share_link, but notice that this is only the version for testing which compiled from main branch, so install it as fresh one and do not override any old harbor data location.

**Comment by DisasteR** [comment]
@chlins i'll try that a soon as possible.

It's not possible to do an upgrade from a previous install ?
i can made it on a replica of my actual setup it will be really simpler to check the non working replications.

If that's not possible i'll try with a fresh one. but the update path look better for me.

I'll wait for your return before trying anything.

**Comment by chlins** [comment]
@DisasteR Because the package is built in my environment which based on the main branch(v2.9), so it's not a good idea and practice to upgrade a non release and unstable version. A standard process is to first verify, and if there are no issues, I will consider cherry-pick the fix to the released branch, and then you can wait to upgrade to the patch version(maybe v2.7.2).

**Comment by DisasteR** [comment]
Ok tryed it on a fresh install and i can replicate one of the non working previous project.
so it looks like it's working.

![image](https://user-images.githubusercontent.com/443279/233363184-a0ccd10f-39ef-4bf4-b77e-b0db837006d8.png)


Can't you add some logs in the gitlab project search part ? 
That part of the replication process have no log.
So if we have no created job like i got there is no log to analyze.

That way we can analyze if the problem still exist.

**Comment by chlins** [comment]
> Ok tryed it on a fresh install and i can replicate one of the non working previous project. so it looks like it's working.
> 
> ![image](https://user-images.githubusercontent.com/443279/233363184-a0ccd10f-39ef-4bf4-b77e-b0db837006d8.png)
> 
> Can't you add some logs in the gitlab project search part ? That part of the replication process have no log. So if we have no created job like i got there is no log to analyze.
> 
> That way we can analyze if the problem still exist.

Thanks for your verification and suggestion, @lxShaDoWxl how about add some debug level logs for the GitLab adapter?

**Comment by lxShaDoWxl** [comment]
@chlins I'm added debug information

**Comment by DisasteR** [comment]
Hi, are you planning to release this soon ?

**Comment by DisasteR** [comment]
@chlins ? when this will be released ?

**Comment by chlins** [comment]
> @chlins ? when this will be released ?

@lxShaDoWxl Hi, can you please help to cherry-pick the commit to release-2.7.0 and release-2.8.0?

**Comment by chlins** [comment]
> @chlins ? when this will be released ?

@DisasteR Hi, the issue has been fixed in main and will also be resolved in the v2.7.3 and v2.8.3, please wait for these 2 releases published for upgrade. @lxShaDoWxl Thanks for the work!

**Comment by DisasteR** [comment]
@chlins, Hi, have you some news ? are this release already planned ?

**Comment by chlins** [comment]
> @chlins, Hi, have you some news ? are this release already planned ?

Hi, currently team is focusing on the release 2.9, no specific time yet now.
