### ISSUE TITLE
Harbor Replication failed for exceeding the configured upper limit

### ISSUE THREAD

**Issue by sunidhi271** [goharbor/harbor#18298]
The replication is configured as event based. Some of those replications have failed with the below error:

![image](https://user-images.githubusercontent.com/86234399/222361912-420f9939-c401-4c0d-ad0e-b0f9f31e96bb.png)

Harbor version: v2.5.3
Replication rule: 
Type: Push based 
Trigger mode: Event Based.

![image](https://user-images.githubusercontent.com/86234399/222361623-c9a131f2-0bcb-4d97-ac10-ab47c3d742c0.png)
![image](https://user-images.githubusercontent.com/86234399/222361653-e560a82b-4d5b-4c02-b99e-18700cb51712.png)

**Comment by wy65701436** [comment]
The error message clearly explains the reason for the failure. The target project rejected the image push because the quota has been exceeded.
