### ISSUE TITLE
proxy cache fail,unknown: repository ... not found

### ISSUE THREAD

**Issue by biu-hqh** [goharbor/harbor#18292]
`[root@master1 ~]# podman pull registry.apps.okd4.myhci.com/hub/library/busybox:latest --tls-verify=false
Trying to pull registry.apps.okd4.myhci.com/hub/library/busybox:latest...
WARN[0000] failed, retrying in 1s ... (1/3). Error: initializing source docker://registry.apps.okd4.myhci.com/hub/library/busybox:latest: reading manifest latest in registry.apps.okd4.myhci.com/hub/library/busybox: unknown: repository hub/library/busybox not found
WARN[0001] failed, retrying in 1s ... (2/3). Error: initializing source docker://registry.apps.okd4.myhci.com/hub/library/busybox:latest: reading manifest latest in registry.apps.okd4.myhci.com/hub/library/busybox: unknown: repository hub/library/busybox not found
WARN[0002] failed, retrying in 1s ... (3/3). Error: initializing source docker://registry.apps.okd4.myhci.com/hub/library/busybox:latest: reading manifest latest in registry.apps.okd4.myhci.com/hub/library/busybox: unknown: repository hub/library/busybox not found
Error: initializing source docker://registry.apps.okd4.myhci.com/hub/library/busybox:latest: reading manifest latest in registry.apps.okd4.myhci.com/hub/library/busybox: unknown: repository hub/library/busybox not found`

core.log
`Proxy to remote failed, fallback to local repo, error: error unmarshalling content: invalid character '<' looking for beginning of value`

But when I pulled the quay image, it succeeded

`[root@master1 ~]# podman pull registry.apps.okd4.myhci.com/quay/prometheus/node-exporter:latest --tls-verify=false
Trying to pull registry.apps.okd4.myhci.com/quay/prometheus/node-exporter:latest...
Getting image source signatures
Copying blob 22b70bddd3ac skipped: already exists
Copying blob 5c12815fee55 skipped: already exists
Copying blob c0e87333d380 skipped: already exists
Copying config 0da6a335fe done
Writing manifest to image destination
Storing signatures
0da6a335fe1356545476b749c68f022c897de3a2139e8f0054f6937349ee2b83`

harbor version : 2.5.0
openshift version:4.9

![image](https://user-images.githubusercontent.com/34858388/222088655-22dfa1bb-9b8f-4562-8277-600be5d3b2fa.png)

![image](https://user-images.githubusercontent.com/34858388/222088879-d8ac492d-c22d-456b-8984-8c4519d8da55.png)

**Comment by l333308** [comment]
Face this matter too.Waiting for solution.

**Comment by wy65701436** [comment]
Just to confirm, are you pulling an image from a proxy project using podman? Have you tried the same scenario with docker? I wanted to mention that we haven't tested harbor with podman yet.

**Comment by biu-hqh** [comment]
> Just to confirm, are you pulling an image from a proxy project using podman? Have you tried the same scenario with docker? I wanted to mention that we haven't tested harbor with podman yet.

I meet the same situation with docker，it could be the company network
`[root@support registry]# docker pull registry.apps.okd4.myhci.com/hub/library/busybox:latest
Trying to pull repository registry.apps.okd4.myhci.com/hub/library/busybox ...
unknown: repository hub/library/busybox not found
[root@support registry]# docker pull registry.apps.okd4.myhci.com/quay/prometheus/node-exporter:latest
Trying to pull repository registry.apps.okd4.myhci.com/quay/prometheus/node-exporter ...
latest: Pulling from registry.apps.okd4.myhci.com/quay/prometheus/node-exporter
Digest: sha256:39c642b2b337e38c18e80266fb14383754178202f40103646337722a594d984c
Status: Image is up to date for registry.apps.okd4.myhci.com/quay/prometheus/node-exporter:latest`

**Comment by jade-tseng** [comment]
Facing same issue here. Anybody found solution?

**Comment by mreiche** [comment]
Same here. quay.io and ghcr.io images work, docker hub not - not even authenticated.
