### ISSUE TITLE
harbor proxy dockerhub tag absent

### ISSUE THREAD

**Issue by lissan** [goharbor/harbor#18300]
when docker pull myrepo.com/docker-hub/library/centos in harbor is not saved tag latest.

![image](https://user-images.githubusercontent.com/5618684/222448817-3684071b-16ad-418c-b457-2b97d566e35a.png)

**Comment by lissan** [comment]
version v2.5.3 harbor

**Comment by stonezdj** [comment]
The centos:latest is a manifest list, it will not create tag for each item in the list. for example
sha256:a1801b84 is the sub item. it will create tag for the image list
see 
<img width="744" alt="Screen Shot 2023-03-06 at 15 07 56" src="https://user-images.githubusercontent.com/2696760/223041814-1af77deb-e605-45dd-87c8-24aee5fb54fd.png">

**Comment by AllForNothing** [comment]
This is by design

**Comment by lissan** [comment]
after reloading the image, the latest disappears
