### ISSUE TITLE
Replicate different version  (1.7.4 to 2.7.0)

### ISSUE THREAD

**Issue by SiamPiApinant** [goharbor/harbor#18327]
Hi ,  
Now I have use harbor 1.7.4 for old project and I have init new harbor (2.7.0) for new project.  I try set replication rule to sync image but have an errors .    Question is  I should upgrade old harbor before sync or manual pull image and push to new harbor ?

Or some one have any idea to solve this . 

Thank you in advance

**Comment by wy65701436** [comment]
Harbor doesn't support allow major & minor version replication. To migrate data from an older version of Harbor to a newer one, you can create a script that pulls the data from the old Harbor instance and pushes it into the new one.

**Comment by SiamPiApinant** [comment]
@wy65701436  thanks for answer.
