### ISSUE TITLE
Certificate Issuer did not match

### ISSUE THREAD

**Issue by Eweol** [goharbor/harbor#18336]
Hi,

I use harbor in relation with Authentik.
I created an OIDC-Provider in Authentik and tried to connect harbor to that.
As far as I finished configuration and test the configuration it will fail.
After investigating the logs of the Core component I could figure out the following error.

`2023-03-11T13:53:01+01:00 [ERROR] [/server/v2.0/handler/oidc.go:33]: Failed to verify connection: {URL:https://xxx.yyy.de/application/o/harbor VerifyCert:false}, err: oidc: issuer did not match the issuer returned by provider, expected "https://xxx.yyy.de/application/o/harbor" got "https://xxx.yyy.de/"`

Since Authentik uses different endpoint for different applications the "Endpoint-Value" for harbor's configuration is 'https://xxx.yyy.de/application/o/harbor' which for sure is not matching the SSL issuer which is 'https://xxx.yyy.de/'.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.7.1]
- authentic version: [2023.2.3]
- microk8s version: [1.23.16]

**Comment by stonezdj** [comment]
What is your OIDC configuration setting?

**Comment by Eweol** [comment]
Hi,

I figured out, that Authentik give possibility to change the Configuration issuer in provider configuration.

@stonezdj Thanks
