### ISSUE TITLE
What should be the upgrade path to newer versions of Harbor from v2.2.0

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#18345]
We have Harbor v2.2.0 running via helm in our environment. We wish to upgrade to the new versions of Harbor. I wanted to ask what is the preferred upgrade path from v2.2.0.

Do we need to do a step wise upgrade (2.2 -> 2.3 -> 2.4) or can we directly upgrade to 2.4.

**Comment by wy65701436** [comment]
You can update the software version by skipping two versions, like v2.2.0 - v2.4.0 - v2.6.0.
