### ISSUE TITLE
Remove src/vendor 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#18346]
We are vendoring the dependencies of Harbor in `./src/vendor`.
Currently, on `main` branch `./src/vendor` is taking up 59M and `./src` is taking 75M, i.e. the vendor folder is using ~90% of the size of all source code.  In addition, there's a potential risk of inconsistency that someone may forget vendoring the dependency after updating `go.mod`.

Therefore, I wanna suggest we stop vendoring the dependencies and use `go.mod` as single source of truth.

The only negative impact is that it may take longer if we compile the code in container, in that case, we should use a local goproxy to accelerate downloading the moduls.

**Comment by wy65701436** [comment]
move it to v2.10
