### ISSUE TITLE
Replication fails because cosign is incorrectly associated with artifact

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#18343]
**Steps to reproduce the problem:**
1. push busybox:latest
2. push hello-world:latest
3. docker manifest create {domain_and_project}/index:index_tag {domain_and_project}/hello-world:latest {domain_and_project}/busybox:latest
4. docker manifest push {domain_and_project}/index:index_tag
5. Cosign Sign {domain_and_project}/busybox:latest
6. Cosign Sign {domain_and_project}/hello-world:latest
7. Cosign Sign {domain_and_project}/index:index_tag
8. Cosign Sign {domain_and_project}/index@${busybox@sha256}

project:
<img width="1394" alt="图片" src="https://user-images.githubusercontent.com/72076317/224891508-e480a9ea-6718-464a-947d-ce303193b0ce.png">
<img width="1450" alt="图片" src="https://user-images.githubusercontent.com/72076317/224890041-0d461d5d-3540-48fd-8865-fc3b10980583.png">
<img width="1385" alt="图片" src="https://user-images.githubusercontent.com/72076317/224891664-6043de8f-fe2e-4d54-9d89-433003d908ea.png">
<img width="1401" alt="图片" src="https://user-images.githubusercontent.com/72076317/224891708-ef96b53f-ed7a-4706-a787-9a484bd5c8f4.png">
<img width="1404" alt="图片" src="https://user-images.githubusercontent.com/72076317/224891759-2f88ceec-5e97-4ed1-aeec-b9a582553df9.png">

replication rule:
<img width="630" alt="图片" src="https://user-images.githubusercontent.com/72076317/224888450-fa88bae1-52a7-40c9-bd13-a897c8d02fb8.png">

executions:
<img width="1406" alt="图片" src="https://user-images.githubusercontent.com/72076317/224888803-7abf11a4-6cc3-4de5-bcf5-c9dde79d116f.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: main

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/18377
