### ISSUE TITLE
How to handle API requests when / is included in repositories

### ISSUE THREAD

**Issue by AbelHugh** [goharbor/harbor#18355]
When repositories has only one word and does not contain /, api access is normal
for example
curl -u "admin":"$pass" "https://${harbor_url}/api/v2.0/projects/library/repositories/mysql/artifacts" -k
![image](https://user-images.githubusercontent.com/71317399/225307617-dd35efe0-885a-48a1-8928-c9f45c60ae62.png)
However, as shown in the figure below, when repositories contains /, for example, 'nacos/nacos-server' in the figure below I will not be able to obtain the desired result
commad:
curl -u "admin":"$pass" "https://${harbor_url}/api/v2.0/projects/docker.io/repositories/nacos%2Fnacos-server/artifacts" -k  
![image](https://user-images.githubusercontent.com/71317399/225257195-7df94b8d-e4f8-4d51-83a0-d76cf37ed845.png)
![image](https://user-images.githubusercontent.com/71317399/225256915-4b6b3ecd-0c6d-4c27-915c-8e36416ea954.png)

Please tell me where the api format is incorrect

**Comment by chlins** [comment]
You should replace the `%2F` => `%252F`.
