### ISSUE TITLE
System robot account can't read project created by itself

### ISSUE THREAD

**Issue by coding4food** [goharbor/harbor#18363]
**Expected behavior and actual behavior:**
I am trying to use system robot account to manage Harbor resources with terraform. Terraform provider for Harbor tries to read project data at the end of resource creation and get "403 Forbidden" error. When I use regular user account everything work fine. I expect system robot account should be able to read projects it creates too.

**Steps to reproduce the problem:**
1. Create system robot account with following properties:
    ```
    {
        "level": "system",
        "name": "robot$test-robot-fff",
        "permissions": [
            {
                "access": [
                    {
                        "action": "*",
                        "effect": "allow",
                        "resource": "*"
                    }
                ],
                "kind": "project",
                "namespace": "*"
            },
            {
                "access": [
                    {
                        "action": "*",
                        "effect": "allow",
                        "resource": "*"
                    }
                ],
                "kind": "system",
                "namespace": "/"
            }
        ]
    }
    ```
1. Create project via API call with that system robot credentials
    ```
    POST <harbor_url>/api/v2.0/projects
    ...
    ```
1. Try to read project via API call
    ```
    GET <harbor_url>/api/v2.0/projects/<created_project_id>
    ...
    ```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.6.0, 2.7.1
- docker engine version: not relevant
- docker-compose version: not relevant

**Additional context:**

- **Log files:** [harbor.log](https://github.com/goharbor/harbor/files/10988839/harbor.log)

**Comment by YangJiao0817** [comment]
Same [issue](https://github.com/goharbor/harbor/issues/17636), will be fixed in v2.8.0.

**Comment by coding4food** [comment]
@YangJiao0817 still does not work in 2.8.0 for robot account with system-level and project-level permissions.

**Comment by YangJiao0817** [comment]
@coding4food Try using the following permissions payload.
```
[
  {
    "access": [
      {
        "action": "delete",
        "resource": "project"
      },
      {
        "action": "list",
        "resource": "project"
      },
      {
        "action": "read",
        "resource": "project"
      }
    ],
    "kind": "project",
    "namespace": "*"
  }
]
```

**Comment by coding4food** [comment]
@YangJiao0817 it kinda works, but not as expected:
- my harbor instance config requires system administrator permissions to create projects
- so robot account needs system-level permissions
- when robot account has system-level and project-level permissions, authorization checks fail on project read as reported above
- with project-only permissions robot account works, but that means "Everyone" can create projects

**Comment by YangJiao0817** [comment]
You can try the following payload to create a system-level robot account, which can read the items created by itself.
```
{
    "name": "proj_sys",
    "duration": 30,
    "description": null,
    "disable": false,
    "level": "system",
    "permissions": [
        {
            "kind": "project",
            "namespace": "*",
            "access": [
                {
                    "action": "delete",
                    "resource": "project"
                },
                {
                    "action": "list",
                    "resource": "project"
                },
                {
                    "action": "read",
                    "resource": "project"
                },
                {
                    "action": "create",
                    "resource": "project"
                }
            ]
        }
    ]
}
```

**Comment by coding4food** [comment]
@YangJiao0817 your suggestion won't work when only sysadmins are allowed to create projects

**Comment by drduker** [comment]
can this be reopened?

**Comment by dleske** [comment]
Running 2.8.2 and this does not work.
