### ISSUE TITLE
LDAP group problems

### ISSUE THREAD

**Issue by tropnikovvl** [goharbor/harbor#18375]
Hello! I am using a secure ldap service from Google. And my problem is that Harbor can't connect to it.
To connect, you need a key and a certificate that Google gives me (SSL over LDAP). They are part of the [authorization](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F9048516%3Fhl%3Den&assistant_id=generic-unu&product_context=9048516&product_name=UnuFlow&trigger_context=a).
At the moment I'm using the Stunnel as a middle proxy, but authorization through it takes almost 20 seconds. And it doesn't let me log in through the docker console.

That is, what authorization looks like in general:
Harbor uses the LDAP login and password by sending it to Stunnel, he, in turn, on top of this, additionally authorizes himself in Google LDAP using a certificate and key.

Is it possible to integrate the key and certificate into the Harbor directly? I saw the caBundleSecretName parameter, but it is only for the certificate and could not help me in the end.
Version 2.7.1

**Comment by tropnikovvl** [comment]
I made a proxy based on nginx.
`
    stream {
      upstream stream_backend {
          server ldap.google.com:636;
      }
      server {
          listen 1636;
          # proxy_bind $remote_addr transparent;
          proxy_connect_timeout 5s;
          proxy_pass stream_backend;
          proxy_buffer_size 2048k;
          proxy_ssl  on;
          proxy_ssl_certificate     /etc/nginx/test.crt;
          proxy_ssl_certificate_key /etc/nginx/test.key;
      }
      log_format basic '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time';

      access_log  /var/log/nginx/access.log basic;
      error_log  /var/log/nginx/error.log debug;
    }
`
I'm getting the same problem, as we can see from the log below the session lasted almost 20 seconds for some reason. Docker login fails early unfortunately.
`
2023/03/17 22:35:31 [info] 29#29: *1 client 10.180.13.101:43558 connected to 0.0.0.0:1636                                                                                                                          
2023/03/17 22:35:31 [info] 29#29: *1 proxy 10.180.13.103:46236 connected to 216.239.32.58:636                                                                                                                      
2023/03/17 22:35:50 [info] 29#29: *1 client disconnected, bytes from/to client:3666/3096, bytes from/to upstream:3096/3666                                                                                         
10.180.13.101 [17/Mar/2023:22:35:50 +0000] TCP 200 3096 3666 **19.534**                                                                                                                                                
2023/03/17 22:38:02 [info] 30#30: *3 client 10.180.13.101:57458 connected to 0.0.0.0:1636                                                                                                                          
2023/03/17 22:38:02 [info] 30#30: *3 proxy 10.180.13.103:51080 connected to 216.239.32.58:636                                                                                                                      
2023/03/17 22:38:22 [info] 30#30: *3 client disconnected, bytes from/to client:3666/3096, bytes from/to upstream:3096/3666                                                                                         
10.180.13.101 [17/Mar/2023:22:38:22 +0000] TCP 200 3096 3666 **19.429**
`

**Comment by tropnikovvl** [comment]
I disabled the search for groups in ldap and the login worked very quickly! Almost 3 seconds.
```
2023/03/18 08:53:13 [info] 30#30: *9 client 10.180.13.101:55372 connected to 0.0.0.0:1636                                                                                                                          
2023/03/18 08:53:13 [error] 30#30: *9 connect() to [2001:4860:4802:32::3a]:636 failed (101: Network is unreachable) while connecting to upstream, client: 10.180.13.101, server: 0.0.0.0:1636, upstream: "[2001:48 
2023/03/18 08:53:13 [warn] 30#30: *9 upstream server temporarily disabled while connecting to upstream, client: 10.180.13.101, server: 0.0.0.0:1636, upstream: "[2001:4860:4802:32::3a]:636", bytes from/to client 
2023/03/18 08:53:13 [info] 30#30: *9 proxy 10.180.27.147:41578 connected to 216.239.32.58:636                                                                                                                      
2023/03/18 08:53:17 [info] 30#30: *9 client disconnected, bytes from/to client:342/1055, bytes from/to upstream:1055/342                                                                                           
10.180.13.101 [18/Mar/2023:08:53:17 +0000] TCP 200 1055 342 3.784
```

**Comment by tropnikovvl** [comment]
Final verdict: every time you login, Harbor tries to create (?) groups and does it very slowly. Even though groups may have been created earlier.
Thus, a person who has fewer LDAP groups logs in faster than a person who has more groups.
And the main question: is it possible to disable this behavior? LDAP filters obviously do not help here.

It looks like my problem is exactly the same as in this post https://github.com/goharbor/harbor/issues/13780

**Comment by stonezdj** [comment]
You could setup the group filter parameter to filter all groups if you don't want this feature.
<img width="480" alt="Screenshot 2023-03-19 at 08 50 32" src="https://user-images.githubusercontent.com/2696760/226147863-913670cf-80dd-4d83-a507-2bd15e227ccc.png">

**Comment by tropnikovvl** [comment]
@stonezdj, Hello! I set up! And I am getting errors while the filter is running. And because of this, the login takes a very long time, because. the filter function iterates over each group individually

The whole second half of this post is about it. I showed what filters I tried to use and what I get in the logs
https://github.com/goharbor/harbor/issues/18375#issuecomment-1474809738

**Comment by stonezdj** [comment]
Could you keep the LDAP group filter empty?  it seems that if the filter is empty, then it will not fetch group information.
https://github.com/stonezdj/harbor/blob/09371b48e85aa588e7ddf7bbfc351f93693bec23/src/core/auth/ldap/ldap.go#L116

**Comment by tropnikovvl** [comment]
> Could you keep the LDAP group filter empty? it seems that if the filter is empty, then it will not fetch group information. https://github.com/stonezdj/harbor/blob/09371b48e85aa588e7ddf7bbfc351f93693bec23/src/core/auth/ldap/ldap.go#L116

Then group matching will stop working.
When people log in, they don’t see anything and all the access rights that I previously did for groups on projects are not used

**Comment by stonezdj** [comment]
How many groups for each user in your env? it seems you want the group privilege feature.  Base current mechanism, the querying and matching effort could not avoid.

**Comment by tropnikovvl** [comment]
> How many groups for each user in your env? it seems you want the group privilege feature. Base current mechanism, the querying and matching effort could not avoid.

20-40 groups per person.
How to use this feature?
