### ISSUE TITLE
Harbor cross-region replicaiton

### ISSUE THREAD

**Issue by idonca** [goharbor/harbor#18383]
Hello team,

I have a question regarding cross-region replication. In our case, we have deployed Harbor via helm chert in two regions. Now, we have only one replication rule which is push-based from region A to region B because for now, all of our workloads are in region A. We want to know what replication rule we should create from region B to region A when region A will be down, to say so. We are going to push in the Harbor only from region A, always, and the applications will going to pull from both regions.

Please do let me know what replication rule we should create from region B to region A when region A is down and the applications are going to push into region B. We would like to replicate all the push actions from region B to region A when region A is recovered.

Thank you!

**Comment by wy65701436** [comment]
@idonca I'm sorry, I'm having trouble fully understanding your problem. Could you please provide further clarification? Additionally, based on my understanding, it seems like it would be best addressed at the load balancing site.

**Comment by chlins** [comment]
To set up push-based and event-based replication policies in Harbor-A, any images pushed to A will be automatically copied to Harbor-B. However, occasional replication failures may occur, so an additional periodic policy can ensure all images are replicated again for consistency. The same process applies when setting up these policies in Harbor-B.

**Comment by idonca** [comment]
@chlins , thank you for your answer
