### ISSUE TITLE
Harbor application dependencies Repository

### ISSUE THREAD

**Issue by leandromoreirati** [goharbor/harbor#18384]
I'm studying harbor to replace actual repository solution on my work, but I need it support application dependencies as python (pypi), npm, java and other languages.

I researched in documentation and not find anythink about this possibility.

My question is, is possible use harbor as  application dependencies repository?

Case possible, could me indicate  documentation about this configuration?

**Comment by wy65701436** [comment]
You have to confirm the format of dependencies since Harbor can only servers OCI compatible files, like OCI helm charts, docker images.
