### ISSUE TITLE
download  failed for https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry

### ISSUE THREAD

**Issue by consoleKEC** [goharbor/harbor#18385]
when I compile in local env using command from harbor document: ' make  package_offline  GOBUILDIMAGE=golang:1.13.8 COMPILETAG=compile_golangimage NOTARYFLAG=true', I found registry in storage.googleapis.com is missing, and when I check the latest code of this line in branch main https://github.com/goharbor/harbor/blob/main/Makefile#L118, it is just right here with REGISTRYVERSION=v2.8.0-patch-redis in the former lines, but i could not found its path in this xml of https://storage.googleapis.com/harbor-builds/

I am not sure if is it removed of https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registry

![image](https://user-images.githubusercontent.com/24772998/226608314-ee366923-c0e6-4139-b921-d2aa5ea5c313.png)

**Comment by wy65701436** [comment]
This registry binary has been deprecated. Please try using the latest code and include the parameter 'BUINDBIN=true' when calling the 'make' command.

**Comment by consoleKEC** [comment]
> appreciate for your reply, while I do git pull the latest code without any modify and add "BUINDBIN=true" in make commands, I faced a new problem of go package missing in GOPATH, while i found it exist in harbor project src/vendor path by 'ls' in harbor source code directory, do you have any more suggestion? thanks

![image](https://user-images.githubusercontent.com/24772998/226850491-8951ed15-80c6-4e74-83b9-ab3a62c55cce.png)

**Comment by consoleKEC** [comment]
> This registry binary has been deprecated. Please try using the latest code and include the parameter 'BUINDBIN=true' when calling the 'make' command.

moreover, since it is deprecated, why do not update Makefile by removing registry URL, I suggest put it back since I was using harbor based on 2.0.2 stable for a long time, if removed registry in storage.googleapis.com, it means harbor community force to push all self-dev version to latest, that is not friendly and smooth way for some not very lower version, and that could be a more compatible way.

**Comment by thesayyn** [comment]
+1 for bringing the registry binary back for those who want to run harbor on bare metal servers where docker/k8s isn't available.
