### ISSUE TITLE
CVE export error "404 page not found"

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#18380]
Hi all,

In our environment (Harbor `v2.7.0`) we detected the issue with exporting the CVE report.

![image](https://user-images.githubusercontent.com/99802718/226391699-aac278bc-8a54-4d52-82b7-1a3aa224cf10.png)

`jobservice.log:`
```
Mar 20, 2023 @ 19:46:19.396    Mar 20 15:16:19 172.20.0.1 jobservice[25867]: 2023-03-20T14:16:19Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678138e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678138e+06.csv to persistent storage: http status code: 404, body: 404 page not found    
Mar 20, 2023 @ 19:45:48.329    Mar 20 15:15:48 172.20.0.1 jobservice[25867]: 2023-03-20T14:15:48Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678137e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678137e+06.csv to persistent storage: http status code: 404, body: 404 page not found    
Mar 20, 2023 @ 19:45:25.889    Mar 20 15:15:25 172.20.0.1 jobservice[25867]: 2023-03-20T14:15:25Z [ERROR] [/jobservice/job/impl/scandataexport/scan_data_export.go:130]: Export Job Id = 7.678135e+06. Error when persisting report file /var/scandata_exports/scandata_export_7.678135e+06.csv to persistent storage: http status code: 404, body: 404 page not found
```

We already checked the permissions in the filesystem and the Docker configuration and we didn't saw any "strange" configuration.

Does anyone have an idea, why this is not working?

P.S.: Maybe related to https://github.com/goharbor/harbor-helm/issues/1444

Thank you in advance!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Vad1mo** [comment]
Duplicate of https://github.com/goharbor/harbor-helm/issues/1444

**Comment by Vad1mo** [comment]
related to https://github.com/goharbor/harbor-helm/issues/1320

**Comment by chlins** [comment]
> related to [goharbor/harbor-helm#1320](https://github.com/goharbor/harbor-helm/issues/1320)

@Vad1mo We reproduced this issue seems not related with https://github.com/goharbor/harbor-helm/issues/1320, it's another issue.

**Comment by chlins** [comment]
The issue will happen when the execution primary key auto-increment ID grows to a big value, currently no temporary workaround for this, please upgrade to v2.6.5/v2.7.2/v2.8.0 to fix it.
