### ISSUE TITLE
Pushing an OCI helm chart with the same version as an existing BIG image fails with 412. Smaller images not affected.

### ISSUE THREAD

**Issue by funkypenguin** [goharbor/harbor#18395]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I'm using Harbor to store a copy of 3rd-party images and helm charts. I push the image into Harbor with `docker push`, and then I push the chart with `helm push <path to chart.tar.gz> oci://myharbor/myproject`.
 
This seems to work well with most images, but I stumbled across an issue with a 450MB image..

When I attempted to oci-push a chart with the same name as an existing large (450MB) image (_the example here is rook/ceph:v1.9.7_), the helm push fails with `Error: unexpected status: 412 Precondition Failed`. I replaced the large image with a busybox image (_re-tagged with the same name_), and the helm push then worked correctly.

**Steps to reproduce the problem:**

1. Grab a helm chart:
```
helm repo add rook-release https://charts.rook.io/release
helm repo update
helm pull rook-release/rook-ceph --version 1.9.7
```

2. Grab an image, tag it:
```
docker pull rook/ceph:v1.9.7
docker tag rook/ceph:v1.9.7 my-harbor/library/rook-ceph:v1.9.7
```

3. Push the image into Harbor:
```
docker push my-harbor/library/rook-ceph:v1.9.7
```

4. Push the chart into Harbor:
```
helm push rook-ceph-v1.9.7.tgz oci://my-harbor/library
```

5. Observe the 412:

```
~/tmp ❯ helm push rook-ceph-v1.9.7.tgz oci://myharbor/library                                                                                                                                                  17:04:45
Error: unexpected status: 412 Precondition Failed
~/tmp ❯
``` 

6. Delete the image from Harbor
7. Grab a small image, tag it with the same name:tag, push into Harbor

```
docker pull busybox
docker tag busybox:latest registry-internal.elpenguino.net/library/rook-ceph:v1.9.7
docker push my-harbor/library/rook-ceph:v1.9.7
```

8: Push the chart again, observe it working:

```
helm push rook-ceph-v1.9.7.tgz oci://myharbor/library  
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.7.0] using the helm chart in Kubernetes

**Additional context:**

1. I observed no errors in the db, core, or registry pods to indicate why the 412 was returned. 
2. This behavior is not observed with Docker Hub's OCI repo (which is what I was trying to replace)
3. If the chart is pushed **before** the big image, there's no problem. The problem only occurs when the big image is pushed before the chart.

**Comment by YangJiao0817** [comment]
I did not reproduce the problem by following your steps.
```
helm push rook-ceph-v1.9.7.tgz oci://my-harbor/library
Pushed: my-harbor/library/rook-ceph:v1.9.7
Digest: sha256:6390893d1cb0890b75a6a44b815489aabd16d138ce5095bf656239123ea371cb
```
