### ISSUE TITLE
I'm struggling with replication from Harbor to Azure ACR

### ISSUE THREAD

**Issue by PJSFL** [goharbor/harbor#18393]
Hello,

Guys, I need help with Harbor to Azure replication.
I've been struggling with the problem of replication not executing for two days now, and I think it's time to give up and seek advice here.

I set up a repository on our new Harbor server, I configured replication and when I run the replication the task ends Failed or Successful but still the repository in Azure does not receive any files.
I'd like to have Azure as a backup for Harbor and a potential place to download application images if the customer prefers Azure to Harbor.

![image](https://user-images.githubusercontent.com/127487190/226841000-e4b12ba0-0ec8-4ae0-b300-00720cbdeac1.png)

here everything looks fine, but sometimes i recieve a message 'Failed to connect to endpoint' or the status 'unhealthy' - i don't know why.

![image](https://user-images.githubusercontent.com/127487190/226841045-2c2fc807-3df9-43e6-9194-0a67be76a008.png)

and when i run the replication, all of the files are failed

![image](https://user-images.githubusercontent.com/127487190/226841073-555d6258-92c9-414f-8f1c-8f29e79c51d3.png)

I can see some errors in logs but have no idea how to fix them

a) failed to push manifest of artifact

b)
2023-03-10T09:09:05Z [ERROR] [/controller/replication/transfer/image/transfer.go:481]: failed to check the existence of the manifest of artifact XXX/mariadb:latest on the destination registry: http status code: 403, body:
2023-03-10T09:09:05Z [ERROR] [/controller/replication/transfer/image/transfer.go:194]: http status code: 403, body:
2023-03-10T09:09:05Z [ERROR] [/controller/replication/transfer/image/transfer.go:200]: got error during the whole transfer period, mark the job failure
: the blob sha256:XXX already exists on the destination registry, skip

but there is not a single file there on Azure ACR...

If you had any ideas - I would appreciate your support.
Azure ACR has a premium version. In Access ID and Password, I entered the login and password from the Access Keys tab in the Azure container. I didn't configure anything beyond that.

Thanks!

**Comment by rrgadeev** [comment]
name **
tag **

**Comment by PJSFL** [comment]
> name ** tag **

@rrgadeev I did it now, tried to replicate it once again, it finished Succesfull and still the Repository is empty

![image](https://user-images.githubusercontent.com/127487190/227174357-634aed81-1fc4-49c6-ace1-9dc4e3db91f1.png)
![image](https://user-images.githubusercontent.com/127487190/227174408-77c479ff-46e9-4df4-b2cf-dd4b1875b39d.png)
![image](https://user-images.githubusercontent.com/127487190/227174518-c35359e0-6b61-4a83-8c76-8a41551e3664.png)
![image](https://user-images.githubusercontent.com/127487190/227174277-86b702ea-9bdb-483d-8375-48ed32b2b050.png)

I am losing hope in getting that to work well...

**Comment by PJSFL** [comment]
It's connected correctly to the ACR
![image](https://user-images.githubusercontent.com/127487190/227174890-1a92a6c3-00e4-44e2-a6bd-66c4db7e5288.png)

And I added "**" in both cells
![image](https://user-images.githubusercontent.com/127487190/227175074-45b3e7cd-3768-4a28-ba43-1f3fb0287391.png)

**Comment by chlins** [comment]
@PJSFL Which harbor version did you use? The error logs shows that your account seems no permission to call the v2 registry standard API.

**Comment by chlins** [comment]
FYI: https://github.com/goharbor/harbor/issues/16341

**Comment by PJSFL** [comment]
> @PJSFL Which harbor version did you use? The error logs shows that your account seems no permission to call the v2 registry standard API.

Hey @chlins 
Our Harbor version is V2.7.1-6015b3ef
I couldn't find any suspicous or specific permissions call there. Could you please help me recognize the problem and understand it better?

Thanks!

**Comment by PJSFL** [comment]
Hey @chlins 
May I ask you for the support so we could try to fix it?

**Comment by chlins** [comment]
@PJSFL Hi, did you enable the `Admin user` for the Access key?
<img width="746" alt="image" src="https://user-images.githubusercontent.com/31262637/230523881-066d5e67-7140-47ba-a6ed-cce2dfb80d28.png">

**Comment by PJSFL** [comment]
> @PJSFL Hi, did you enable the `Admin user` for the Access key? <img alt="image" width="746" src="https://user-images.githubusercontent.com/31262637/230523881-066d5e67-7140-47ba-a6ed-cce2dfb80d28.png">

Yes, I did it :(

**Comment by chlins** [comment]
@PJSFL Could you also provide the job logs for above succeed tasks? I couldn't reproduce the issue with the same way.

**Comment by PJSFL** [comment]
> @PJSFL Could you also provide the job logs for above succeed tasks? I couldn't reproduce the issue with the same way.

I can't download the Succeeded logs now - i guess they disappear after a while.
I copied the failed logs that popped up right now, when i tried to replicate the files from Harbor to ACR
https://codeshare.io/eVnWrb

I can see that it will be visable for 24h. Let me know if it helps you

**Comment by PJSFL** [comment]
@chlins I can see that the error says:
'If this message persists and you would like to contact Azure Support'
Might it be an ACR problem? We have 24/7 Premium MS support - should i ask them for help?
I will try but i guess they are going to tell me that 'Harbor is not supported application so we will not help you'

**Comment by chlins** [comment]
@PJSFL Hi, from the log you provided we can only found that the azure returns 403 status code which often represents no permission, harbor does not know why the server respond to 403 because no detailed error message. BTW, I tried the same scenario with yours and authorize by access key enabled admin user, but it's work well in my registry.
