### ISSUE TITLE
rancher下载镜像问题

### ISSUE THREAD

**Issue by Goldlong1** [goharbor/harbor#18391]
部署一个服务的时候，选择一个镜像地址作为镜像源，实际拉取项目的时候，提示下载地址无法下载，并且镜像地址后面多了一个类中版本号的字符，比如   原本指定的镜像地址+“/v2”

**Comment by wy65701436** [comment]
It seems like there might be an issue on the client side. Have you tried pulling the image served by Harbor with the Docker client? If you have, please investigate further on your client's end.

**Comment by Goldlong1** [comment]
![image](https://user-images.githubusercontent.com/33437744/226828872-7bb41a7a-db37-476d-ba7c-2b1bd818bcf3.png)
![image](https://user-images.githubusercontent.com/33437744/226829199-1a5af87e-9b84-4dcb-9b3d-5f6b6ab568dc.png)
看看图片上的具体报错

**Comment by Goldlong1** [comment]
![image](https://user-images.githubusercontent.com/33437744/226829629-4fc534ca-f503-4e06-ab95-8c57366fb15c.png)
![image](https://user-images.githubusercontent.com/33437744/226829794-ae073980-fe05-43c9-9e41-2b9b669a22d2.png)
图片为具体报错内容

**Comment by Goldlong1** [comment]
会不会是网络原因呢
