### ISSUE TITLE
Schema version should be 2  when no accessory found.

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#18407]
referrers API: /v2/name/referrers/<digest>

<img width="348" alt="Screenshot 2023-03-23 at 19 51 26" src="https://user-images.githubusercontent.com/2696760/227195529-6067cbff-e233-40dd-a955-0591a08218b4.png">

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/18430
