### ISSUE TITLE
non-container setup

### ISSUE THREAD

**Issue by sckaftan** [goharbor/harbor#18403]
Hello everyone,

we would like to set up Harbor, but we would like to avoid container (or if necessary lxc-container is okay). 
I have not found any documentation regarding the non-container setup. Is there even a documentation for the non-container setup? If so, where can I find it and if there is not, how else can we setup Harbor?

Otherwise, what is the support with Podman meanwhile? I found the issue here #15105 (perhaps also this one #17113), but it is somewhat outdated.

**Comment by wy65701436** [comment]
It doesn't support non-container setup an harbor. And for Podman support, please monitor to the [proposal](https://github.com/goharbor/community/pull/208) and add your comments, thanks.
