### ISSUE TITLE
Non-manager user can get list of viewable repositories

### ISSUE THREAD

**Issue by Aaron-PanJi** [goharbor/harbor#18414]
**Suggested content:**
Non-manager user can list repositories if user has permission to access those repositories, such as user is project member or the project is public
Currently, Harbor will return 401 error when non-manager user call catalog API. For example,

curl -u test:test@123 192.168.0.159:8080/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to list catalog: unauthorized to list catalog"}]}

Only admin user can list repositories, as below
curl -u admin:Harbor12345 192.168.0.159:8080/v2/_catalog
{"repositories":["library/nginx"]}

**Suggested reasons:**
Downstream system can manage repositories based on view of user. For example, normal user can list, search repositories in public project.

**Comment by chlins** [comment]
The non-manager user can list/search the repositories by other harbor APIs instead, the catalog API is not designed for normal user.
