### ISSUE TITLE
Installation documentation leads to older version of releases

### ISSUE THREAD

**Issue by MaoMaoCake** [goharbor/harbor#18443]
Clicking on the link on [teh installation](https://goharbor.io/docs/2.7.0/install-config/download-installer/) page redirects to [this](https://github.com/goharbor/harbor/releases) page. This page latest release on this page is version 1.7 as opposed to the 2.7.1 as of this issue.

This looks to be an issue with github and not the project  itself. Thanks

**Comment by zyyw** [comment]
@MaoMaoCake not quiet understand your question fully. Could you please elaborate it in more details?
the hyperlink in this page https://goharbor.io/docs/2.7.0/install-config/download-installer/ is to this page, which is ordered by the time releases are made.

**Comment by MaoMaoCake** [comment]
Hi, when clicking on the link [https://github.com/goharbor/harbor/releases](https://github.com/goharbor/harbor/releases) on desktop it redirects to the release page for version 1.7 instead of the correct version(2.7.1), this works fine if I click on the link on github mobile

**Comment by zyyw** [comment]
@MaoMaoCake what do you mean by 
```
clicking on the link https://github.com/goharbor/harbor/releases on desktop it redirects to the release page for version 1.7
```
why could it be `version 1.7`? I don't see this when browsing through Chrome.
When I click this link:  https://github.com/goharbor/harbor/releases, it redirects me to a page like this:
<img width="1776" alt="Screen Shot 2023-04-04 at 15 35 57" src="https://user-images.githubusercontent.com/6709992/229721189-f6ac1a22-be94-48e8-962d-69531164ef51.png">
