### ISSUE TITLE
accessory digest 404 NOT_FOUND error

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#18446]
![图片](https://user-images.githubusercontent.com/72076317/228451658-bff0cbd7-a2db-460f-99af-431d877416b9.png)

- harbor version: v2.8.0, v2.7.1

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/18460

**Comment by bvp** [comment]
This is not a bug in the API. It should be MANIFEST_UNKNOWN

https://github.com/distribution/distribution/blob/main/registry/api/errcode/register.go#L145-L151
