### ISSUE TITLE
when i use macbook  m1 (centos9)  to install harbor2.7.1 or 1.10.17,  all failed! 

### ISSUE THREAD

**Issue by baiying319** [goharbor/harbor#18478]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/38554352/229774197-79aa4e5a-b9a8-48ba-af67-fada19e8ea31.png">
Status: Downloaded newer image for goharbor/prepare:v2.7.1 exec /usr/bin/python3: exec format error

prepare base dir is set to /usr/local/soft/harbor
exec /usr/bin/python3: exec format error

 hao i can install success?

**Comment by wy65701436** [comment]
We're aware that Harbor currently doesn't support Mac (M1), and we would like the community could help in identifying the root cause and finding solutions to address this issue.

**Comment by baiying319** [comment]
yes, it is an VM in my macbook(m1,version-12.5).
it work on parallels desktop, CentOS-Stream-9-latest-aarch64-dvd1.iso.
when i use command 'sudo ./prepare', It outputs as follows:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/38554352/230254236-beba1b50-8c52-4158-9304-165c11abe80c.png">
Then I add the parameter '--platform linux/amd64'  after the Docker command,It outputs as follows:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/38554352/230254521-2c11f7ad-5028-4395-84e6-1bd49050685c.png">
I thought there was a problem with my Python environment, and then I installed Python 3, but it didn't work.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/38554352/230254759-f1966a41-4f6d-4b36-b647-54bb5fab21ae.png">
when i use command 'sudo ./prepare',  It seems to have stopped in the prepare stage. I opened the install.sh script and saw that prepare. sh was executed inside.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/38554352/230255523-a1b709b2-5cfb-4b21-ad45-39438713eb6a.png">

**Comment by lj19950508** [comment]
my mac air m2 , env: vmware fusion - centos7.9-aarm64  :    exec format error

**Comment by devops-xu** [comment]
i want to use harbor on aarch64 too,when can harbor support

**Comment by rayoluo** [comment]
I met the same problem. Has someone succeeded installing harbor in aarch64 vm on mac m1?

**Comment by taitaking** [comment]
I met the same problem. Has someone succeeded installing harbor in aarch64 vm on mac m1?

**Comment by taitaking** [comment]
I met the same problem. Has someone succeeded installing harbor in aarch64 vm on mac m1?

**Comment by weifan01** [comment]
Your CPU architecture is ARM, but the prepare image provided by harbor is only [amd64](https://hub.docker.com/r/goharbor/prepare/tags), so we only need to build an image of ARM and replace the docker image in prepare script, it's a shell script

prepare source code: https://hub.docker.com/r/goharbor/prepare/tags
