### ISSUE TITLE
For OIDC configuration Harbor is maintaining default domain core.harbor.domain 

### ISSUE THREAD

**Issue by k-p-ani** [goharbor/harbor#18483]
Hello,
    I deployed harbor using values.yaml which override domain values for **external URL** and **hosts for ingress** as below, using values.yaml
```
expose:
  externalURL: https:// core.anik3stest.cmsee.net
  ingress:
    hosts:
      core: core.anik3stest.cmsee.net
      notary: notary.anik3stest.cmsee.net
```
Then I logged into harbor portal using https://**core.anik3stest.cmsee.net** and did configurations for OIDC, 
**Administration /configuration /Authentication**, in the same UI at the bottom I see a message "_Please make sure the Redirect URI on the OIDC provider is set to https://**core.harbor.domain**/c/oidc/callback"_. Even after changing domain details I don't understand why the system still suggesting to use domain **core.harbor.domain**.
I clicked option "**TEST OIDC SEVER**" which give successful message. I logged out and now I seen two option for login, one through "LOGIN VIA LOCAL DB" and other through "LOGIN VIA OIDC SEVER".

When I click option "**LOGIN VIA OIDC SEVER**", I get below error message 
```
{
"error":"invalid_request",
"error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."
}
```

and  I see harbor redirecting to below url (**encoded url)**

https://authelia.anik3stest.cmsee.net/api/oidc/authorization?client_id=harbor&redirect_uri=https%3A%2F%2Fcore.harbor.domain%2Fc%2Foidc%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=w6dzSsAmAEO1vH7NOwhngPRQfrF1tAhb

The **decode** value of above url as below (in this redirect uri has wrong domain **core.harbor.domain** instead of **_core.anik3stest.cmsee.net_**)

https://authelia.anik3stest.cmsee.net/api/oidc/authorization?client_id=harbor&redirect_uri=https://core.harbor.domain/c/oidc/callback&response_type=code&scope=openid profile email groups&state=w6dzSsAmAEO1vH7NOwhngPRQfrF1tAhb

Thanks in Advance

**Comment by zyyw** [comment]
Hi @k-p-ani , which harbor version you were using?

**Comment by shakalandy** [comment]
@k-p-ani any update from your side?

Having a similar setup, over here - deployed Harbor via Helm Chart (Version is v2.8.0-89ef156d).
"Test via OIDC provider" works - the Config screen shows the "registry URL" and not the harbor portal / core one.

We are using GitLab OIDC in our case - redirect after "Login with OIDC" brings up the same error as described from @k-p-ani. 

using the following settings in Harbor (removed secrets from screenshot)
![image](https://github.com/goharbor/harbor/assets/182060/7113b86f-58f3-4d1a-9bd5-781e5c6e519e)

This should work even without filters for groups, or?

in addition, GitLab is not sending a value for "offline_access", therefore we removed it despite the comments says this is only necessary for Google.

Any hints on what we could additionaly try out?
Thanks!

**Comment by IceBear2k** [comment]
FYI for anyone having the same issue, I've fallen into the same trap: `externalURL` is scoped on the top level and not a sub-element of `expose`. So, this works correctly:
```
expose:
  ingress:
    hosts:
      core: core.anik3stest.cmsee.net
      notary: notary.anik3stest.cmsee.net
externalURL: https://core.anik3stest.cmsee.net
```
