### ISSUE TITLE
Auto delete empty repositories

### ISSUE THREAD

**Issue by flbla** [goharbor/harbor#18489]
**Is your feature request related to a problem? Please describe.**
When a repository is empty (no artifacts), it doesn't automatically delete it, it keep until we delete it "manually" (with API or GUI)

**Describe the solution you'd like**
It could be great that the GC delete empty repositories or when there is no more artifacts in it
with a system option like "automatically delete empty repositories"

**Comment by chlins** [comment]
Duplicate with https://github.com/goharbor/harbor/issues/18313.
