### ISSUE TITLE
Trigger tag retention API should be non-blocking

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#18504]
How can we help you?

Currently the trigger tag retention API is blocked which will occur timeout if the project has huge repositories(tasks), should refactor this API to be asynchronously like replication and scanAll.

**Comment by tecule** [comment]
any progress on this issue? cause we find the "POST /api/v2.0/retentions/{id}/executions" api takes over 10s to handle thousands of repo.

**Comment by chlins** [comment]
> any progress on this issue? cause we find the "POST /api/v2.0/retentions/{id}/executions" api takes over 10s to handle thousands of repo.

Target this issue to be resolved in the v2.10.0.
