### ISSUE TITLE
Consider returning a 404 error when getting an empty log

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#18505]
Currently, When I view a log that doesn't exist, I will get a blank page, which can lead to confusion, making the user mistakenly think that there is a log and keep refreshing:
![image](https://user-images.githubusercontent.com/30999793/230844808-fa1ba207-def9-4fe8-870e-6019e74f7c33.png)
So, we can consider returning a 404 error when trying to get an un-existing log

**Comment by ricardojdsilva87** [comment]
Hello, we are experiencing the same situation. 
We are running Harbor v2.11.0 but on v2.10.x we experienced the same situation that the logs are empty even on dryruns on the projects. 
When trying to do it to check which images would be deleted, the log is always empty, even after a run, the page is still blank.
We already tried to change the logs to DEBUG, but nothing changes.
Is there any setting that needs to be updated?
Thanks
