### ISSUE TITLE
Docker push - 504 errro

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor#18508]
Hi, sometimes I see this kind of behaviour:
```
The push refers to repository [ip/pipeline/image]
79cbc3c25a75: Preparing
87214584935a: Preparing
5c17c2efc254: Preparing
51bf9e81fc00: Preparing
eaadf720213d: Preparing
8e4fb40b889e: Preparing
b53738361cc7: Preparing
7981c869eeeb: Preparing
b5ebffba54d3: Preparing
8e4fb40b889e: Waiting
b53738361cc7: Waiting
b5ebffba54d3: Waiting
7981c869eeeb: Waiting
87214584935a: Layer already exists
8e4fb40b889e: Layer already exists
79cbc3c25a75: Layer already exists
b53738361cc7: Layer already exists
7981c869eeeb: Layer already exists
b5ebffba54d3: Layer already exists
5c17c2efc254: Layer already exists
received unexpected HTTP status: 504 Gateway Time-out
```
Harbor version: Harbor
Version v2.2.0-ec0ba116

ConfigMap Nignx: 
`{
	"nginx.conf": "worker_processes auto;
		pid /tmp/nginx.pid;
		
		events {
		  worker_connections 1024;
		  use epoll;
		  multi_accept on;
		}
		
		http {
		  client_body_temp_path /tmp/client_body_temp;
		  proxy_temp_path /tmp/proxy_temp;
		  fastcgi_temp_path /tmp/fastcgi_temp;
		  uwsgi_temp_path /tmp/uwsgi_temp;
		  scgi_temp_path /tmp/scgi_temp;
		  tcp_nodelay on;
		
		  # this is necessary for us to be able to disable request buffering in all cases
		  proxy_http_version 1.1;
		
		  upstream core {
		    server \"harbor-harbor-core:80\";
		  }
		
		  upstream portal {
		    server harbor-harbor-portal:80;
		  }
		
		  log_format timed_combined '[$time_local]:$remote_addr - '
		    '\"$request\" $status $body_bytes_sent '
		    '\"$http_referer\" \"$http_user_agent\" '
		    '$request_time $upstream_response_time $pipe';
		
		  access_log /dev/stdout timed_combined;
		
		  server {
		    listen 8080;
		    server_tokens off;
		    # disable any limits to avoid HTTP 413 for large image uploads
		    client_max_body_size 0;
		
		    # Add extra headers
		    add_header X-Frame-Options DENY;
		    add_header Content-Security-Policy \"frame-ancestors 'none'\";
		
		    location / {
		      proxy_pass http://portal/;
		      proxy_set_header Host $host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		    location /api/ {
		      proxy_pass http://core/api/;
		      proxy_set_header Host $host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		    location /chartrepo/ {
		      proxy_pass http://core/chartrepo/;
		      proxy_set_header Host $host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		    location /c/ {
		      proxy_pass http://core/c/;
		      proxy_set_header Host $host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		    location /v1/ {
		      return 404;
		    }
		
		    location /v2/ {
		      proxy_pass http://core/v2/;
		      proxy_set_header Host $http_host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		    location /service/ {
		      proxy_pass http://core/service/;
		      proxy_set_header Host $host;
		      proxy_set_header X-Real-IP $remote_addr;
		      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
		      proxy_set_header X-Forwarded-Proto $scheme;
		
		      proxy_buffering off;
		      proxy_request_buffering off;
		    }
		
		  location /service/notifications {
		      return 404;
		    }
		  }
		}
		"
}`

has anyone experienced this problem?

**Comment by itsecforu** [comment]
Hey @liangxiong3403 ! Thx for feddback

Added as you indicated (before that it was 300) 
```
		  server {
		    listen 8080;
		    server_tokens off;
		    # disable any limits to avoid HTTP 413 for large image uploads
		    client_max_body_size 0;
		    proxy_read_timeout 600;
		    proxy_connect_timeout 600;
		    proxy_send_timeout 600;
```
Then ran the command:

`nginx -s reload`

I don't see any change for the better at the moment

**Comment by stonezdj** [comment]
You should update the comm/config/nginx/nginx.conf file, and change timeout to 900
<img width="671" alt="Screenshot 2023-04-14 at 16 22 19" src="https://user-images.githubusercontent.com/2696760/231987656-9d66f71e-1021-4784-bb52-470cafa66aae.png">

**Comment by itsecforu** [comment]
@stonezdj is v2 required specifically?

**Comment by liangxiong3403** [comment]
@itsecforu maybe you should add configuration under every `location` to ensure timeout correctly

**Comment by itsecforu** [comment]
seems like it works via /v2/, thanks You

**Comment by itsecforu** [comment]
although no, I was hasty, the mistakes are repeated
