### ISSUE TITLE
Artifacts count cleared during GC should be displayed on Harbor UI

### ISSUE THREAD

**Issue by Prince0205** [goharbor/harbor#18524]
**Is your feature request related to a problem? Please describe.**
We are using Harbor v2.5.1 and the amount of data stored is approx 20TB. The GC is scheduled to run everyday.
During GC, the logs are so huge that it is sometimes difficult to scroll to bottom of the GC logs page to check the number of artifacts cleared and also the size of data released. So we wanted to check if it is possible to have those details on the UI where we can see the number of aritfacts cleared and size of data released after each successful GC execution.

**Describe the solution you'd like**
We want to have the details on the UI under Garbage Collection page where we can see the number of aritfacts cleared and size of data released after each successful GC execution.

**Describe the main design/architecture of your solution**
An extra column in the Garbage Collection History page listing the artifacts/size released during GC execution.

**Describe the development plan you've considered**
NA

**Additional context**
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/44364707/231655168-6976ad9e-a519-41e2-80eb-39cf42002516.png">

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/18779
