### ISSUE TITLE
Trivy scans/reports not reporting most up to date fixable vulnerabilities

### ISSUE THREAD

**Issue by lixdavid94** [goharbor/harbor#18523]
When running a trivy scan through the Harbor UI on an image, the fixable vulnerabilities that trivy reports does not match what appears when running trivy locally. Checking the vulnerability DB md5sum for trivy.db on my local machine and in the kubernetes pod, both are matching and the UI and metadata.json show that the DB is up to date. We expect the fixable vulnerability count should match in the UI and when running locally. We've been seeing this issue for a while and thought it was because of an updated schema in the DB whenever we update the harbor version and have to purge the vulnerability data records from the the postgres DB and re-run the scans to fix the issue. But we've noticed this happens after a while as if the reports aren't reflecting the most up to date records. We purge these tables to temporarily fix the issue before it occurs again:

- vulnerability_record;
- report_vulnerability_record;
- scan_report;

Harbor version: v2.7.0
Harbor Scanner Adapter for Trivy version: v0.35.0
Harbor installation process: Helm chart

Does anyone have any ideas why trivy scans are stale?

**Comment by lixdavid94** [comment]
Here is an example, there are no fixable vulnerabilities showing up in the harbor UI, but it shows up locally when i run trivy
![Screenshot 2023-04-13 at 2 11 57 PM](https://user-images.githubusercontent.com/5509450/231883959-4bc72771-9a63-4fb5-9ebe-81549d735a7f.png)

![Screenshot 2023-04-13 at 2 12 03 PM](https://user-images.githubusercontent.com/5509450/231883986-5836bd56-2b92-45bd-9eca-929f8c5d0c03.png)

**Comment by zyyw** [comment]
The harbor default scanner trivy scans an artifact against Harbor trivy.db and saves the returned vulnerability results in Harbor database. The vulnerabilities shows up in the Harbor UI is retrieved from Harbor database while `trivy` cli doesn't interact with harbor database. If your images stored in Harbor were scanned a long time ago and the local images scanned by `trivy` cli happens in the present, the vulnerabilities between the two might be different.

**Comment by stonezdj** [comment]
If two DB's MD5 is identical, and the two scan result (at the same time) are different, then we consider it a scanner issue.

**Comment by lixdavid94** [comment]
@zyyw I understand that the vulnerability results that appear in the UI might be different against the locally scanned image through trivy CLI if the image hasn't been scanned in a while. But we rescanned the image to compare results using the most up to date trivy db. From my understanding, the trivy CLI and harbor trivy scanner adapter both use the same vulnerability database (since harbor updates it daily while the db gets updated when we run locally), so I don't understand why re-triggering a scan doesn't update the vulnerability report.

@stonezdj Why was this issue closed if this is considered a scanner issue? Is this a duplicate or should i reopen it as something else?

**Comment by lixdavid94** [comment]
This are screenshots I took from a scan that i triggered right now through the harbor UI and when i ran trivy locally. It's missing the vulnerabilities for `1.17-6ubuntu4.3`

![Screenshot 2023-04-24 at 7 01 36 PM](https://user-images.githubusercontent.com/5509450/234157255-251009b7-227f-4b4b-a2c1-8cdcc96b4508.png)


![Screenshot 2023-04-24 at 7 01 24 PM](https://user-images.githubusercontent.com/5509450/234157273-d31c64f9-9e4b-4957-a0e2-00f8f9ceeecd.png)


Local:
```
~/Desktop/trivy/cache/db
❯ md5 trivy.db
MD5 (trivy.db) = 30db88841bb6cdf2c52e9267ef05f7e4
```

Pod:
```
scanner [ ~/.cache/trivy/db ]$ md5sum trivy.db
30db88841bb6cdf2c52e9267ef05f7e4  trivy.db
```

Trivy versions:

Local:
```
~/Desktop/trivy
❯ ./trivy --version
Version: 0.35.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-04-25 00:11:51.474674845 +0000 UTC
  NextUpdate: 2023-04-25 06:11:51.474674545 +0000 UT
  DownloadedAt: 2023-04-25 02:05:48.965055 +0000 UTC
```

UI:

![Screenshot 2023-04-24 at 7 07 59 PM](https://user-images.githubusercontent.com/5509450/234157313-16e60fe5-b398-470f-9b2c-57ea399e0c86.png)

The DB is not the most up to date according to the UI, but the md5's still match for the trivy db.

**Comment by JipSogeti** [comment]
Has this issue been fixed (since it's closed)? I think I'm running into this caching of vulnerability results by harbor as well in https://github.com/goharbor/harbor/issues/18867.

**Comment by lixdavid94** [comment]
@JipSogeti Im not sure why this was closed, im still running into the same issues with stale results. I've been continuously clearing up these tables once a month to get newer results

- vulnerability_record;
- report_vulnerability_record;
- scan_report;

**Comment by lixdavid94** [comment]
@stonezdj @zyyw Any updates with this? 

I would think that when you click "scan" it would update old reports with the latest vulnerability information available from the trivy database. So for example, if an image was scanned one month ago shows no fix for a vulnerability is scanned today with a vulnerability that now has a fix, then harbor would update the report as showing that the vulnerability now has a fix, but i am not seeing that until i delete the records in the table

![Screenshot 2023-11-01 at 2 08 53 PM](https://github.com/goharbor/harbor/assets/5509450/2b462d89-991c-4404-ae0c-6a5338770755)

**Comment by Gui13** [comment]
We have the same issue here. The bug is closed but we exhibit the same problems and are missing reports of fixable issues.

**Comment by lixdavid94** [comment]
@Gui13 How are you currently dealing with the reports not being updated?

**Comment by lixdavid94** [comment]
Btw, i also opened this too https://github.com/aquasecurity/harbor-scanner-trivy/issues/411

**Comment by ssegato81** [comment]
I've been looking into this issue and it seems that once the vulnerability_record table was populated, Harbor doesn't update it anymore so it keeps old information. Could that be possible? For instance, I have two Harbor instances using the same configuration but the database of one of them was purged recently. I saw differences in the number of fixable vulnerabilities detected by the scan process. If I run the scan process again that number never changes. I went over that list of the vulnerabilities detected and I saw some difference in one of the values presented by one of the Harbor instances compared to the CVE report. One of the Harbor shows that the CVSS score is 4.8, the other one shows 3.5 and CVE 4.8. I have no way to update the  vulnerability_record table in the Harbor that is showing the wrong information. I could purge the content of that table but all the reports have an id that points to that table so I'd need to delete everything and our CI/CD system uses that information in order to allow/deny a deployment.

**Comment by ianseyer** [comment]
We are seeing the same issue

**Comment by Vad1mo** [comment]
will that fix it? https://github.com/goharbor/harbor/pull/22637

**Comment by thcdrt** [comment]
Hello we have the same issue, we had to delete vulnerability_record from DB, then relaunch scan to see it updated.
