### ISSUE TITLE
UI Pod can't connect to mysql Service when running on Kubernetes

### ISSUE THREAD

**Issue by itl91290** [goharbor/harbor#1853]
I'm trying to run Harbor on Kubernetes, as described in https://github.com/vmware/harbor/blob/master/docs/kubernetes_deployment.md
The setup worked fine and all the K8S entities have been successfully created.
I've also exposed the nginx services via NodePort to have the Harbor GUI available using the browser, but when I try to connect, I get a **502 Bad Gateway** error

Looking at the UI Pod's status, I see a lot of restarts, and eventually the status is CrashLoopBackOff   
```
NAME                    READY     STATUS             RESTARTS   AGE
jobservice-rc-h0qgw     1/1       Running            0          16h
mysql-rc-jvs40          1/1       Running            0          16h
nginx-rc-nm68z          1/1       Running            0          16h
registry-rc-c24p9       1/1       Running            0          16h
ui-rc-rh6n2             0/1       CrashLoopBackOff   163        16h
```
Looking at the Pods' log, there's a fatal connection issue to the mysql service:

```
2017-03-29T09:25:00Z [INFO] token expiration: 30 minutes
2017-03-29T09:25:00Z [INFO] Config path: /etc/ui/app.conf
2017-03-29T09:25:00Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
2017-03-29T09:25:20Z [ERROR] [mysql.go:79]: failed to connect to db, retry after 2 seconds :dial tcp 10.103.164.35:3306: i/o timeout
2017-03-29T09:25:42Z [ERROR] [mysql.go:79]: failed to connect to db, retry after 2 seconds :dial tcp 10.103.164.35:3306: i/o timeout
panic: failed to connect to database after 60 seconds
goroutine 1 [running]:
panic(0xbdb780, 0xc82032c560)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/vmware/harbor/src/common/dao.InitDatabase()
        /go/src/github.com/vmware/harbor/src/common/dao/base.go:50 +0x1d7
main.main()
        /go/src/github.com/vmware/harbor/src/ui/main.go:78 +0xd8
```

The mysql service IP has been resolved correctly.
Also, I've tried from a different Pod I've started just for this purpose, and I can connect to the Harbor's mysql instance using the mysql CLI with the same root password the UI Pod is using. So it's definitely not an issue on the mysql side.
It's worth to add that I'm running Harbor on Docker (on a different host) with the same configuration and it works fine.

I'm running Kubernetes v.1.5.4 and Docker 1.12.6 on Centos 7.3
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by reasonerjt** [comment]
looks like issue in your k8s networking, we don't have a k8s env currently, will try to reproduce later, please expect delay.

**Comment by itl91290** [comment]
In the meantime, we upgraded Kubernetes to version 1.6.1 and now Harbor is working as expected.

About this issue, I think it's worth to spend some more time to evaluate if it's something related to Kubernetes 1.5 or to our network: but we can't reproduce the error anymore, so proceed as you prefer, I don't mind if you decide to close it.

Thanks for your time.
