### ISSUE TITLE
How can I build and install harbor in mock environment?

### ISSUE THREAD

**Issue by xiacunshun** [goharbor/harbor#18531]
I download the newest harbor tarball and want to make it into a rpm package. We are making effort to support harbor on our dist.
But I found it's hard to run docker with newest img in mock.
Is there any solution or maybe some approach which can build harbor without docker?

**Comment by Vad1mo** [comment]
Apart from why you want to do that.

Yes, you can build all the components without docker, you can also extract the binaries from the container if that's easier
There is no guide on that, you need to dive into the details of the Makefile
