### ISSUE TITLE
Presence of "/" forward slash in redis password causing harbor not up issue.

### ISSUE THREAD

**Issue by 0xj0el** [goharbor/harbor#18538]
The presence of "/" forward slash character in the redis password is causing some issue in harbor installation. Replacing the "/" with "%2F" of password in harbor.yml is solving the issue . But  when i try to encode the whole password(eg : + to %2B and = to %3D) seems to cause failure in registry and registryctl.

**Comment by 0xj0el** [comment]
when encoding whole password
<img width="712" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/105660914/232331658-84ba4536-4ce4-4796-a10c-c17f8acdaf79.png">

**Comment by 0xj0el** [comment]
when not encoding and the password contains forward slash
<img width="832" alt="image" src="https://user-images.githubusercontent.com/105660914/232331716-eac5827c-a900-4573-8312-c082bc0e89f0.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/105660914/232331731-208f164c-c9fc-4a4e-a16d-72c8e4b5d79c.png">

**Comment by 0xj0el** [comment]
registry log when encoding the whole password:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/105660914/232398517-e9a05c15-8e74-4dac-8855-b789f2a3cf2a.png">
health check fail for registry and registryctl

only when encoding forward slash:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/105660914/232401195-fabaabd3-8d09-416d-b266-bd2856df8469.png">
success scenario

**Comment by YangJiao0817** [comment]
@wy65701436 @MinerYang  Database password does not have this problem.

**Comment by MinerYang** [comment]
closed by merge
release-2.7.0: https://github.com/goharbor/harbor/pull/18586
release-2.8.0: https://github.com/goharbor/harbor/pull/18587
main:               https://github.com/goharbor/harbor/pull/18566
