### ISSUE TITLE
  Jobservice out of memory when GC called

### ISSUE THREAD

**Issue by tjuzhy** [goharbor/harbor#18549]
Hi! we deploy a harbor on k8s by harbor-operator. We perform a docker cleanup task every day, clean up about 4TB of docker each time, and perform a GC after the cleanup is completed. We found that at an interval of 24 hours, that is, after each GC is triggered, the memory of jobservice will gradually increase, and oom will appear many times, so we have to adjust the upper limit of memory. After we reduced the number of dockers cleaned up each time, the memory of this harbor jobservice remained at a very high value. 
![image](https://user-images.githubusercontent.com/39646203/232744010-be0727a3-7129-4212-9f03-0cba62eede03.png)
![image](https://user-images.githubusercontent.com/39646203/232744283-e03d0a8b-8692-4e8c-8231-7db675603565.png)

What could be the cause of this?

**Comment by tjuzhy** [comment]
it's v2.5.3 harbor

**Comment by tjuzhy** [comment]
Due to oom, the failure of the gc task was not handled in a timely manner, resulting in a large amount of art to be cleaned up. Under the deletedArt function in the mark stage, a joint table query will be executed to obtain the blobs under the deleted art. A single SQL execution takes more than 3 seconds. When we have a large number of art, it will be stuck in this stage for more than a week. Is there any good optimization method to solve this problem?

**Comment by wy65701436** [comment]
@tjuzhy can you share the count of artifact table and artifact_trash? And if you mean GC stucks at this [SQL](https://github.com/goharbor/harbor/blob/main/src/pkg/artifactrash/dao/dao.go#L89), can you run the explain analyze {SQL} in PG?

**Comment by tjuzhy** [comment]
![image](https://github.com/goharbor/harbor/assets/39646203/da2b54cc-820e-4a1d-81da-f91ae7898a67)

we have almost 220k untag artifact, and after joint table query, there are 3.3m rows in the table
