### ISSUE TITLE
Ability to provide upgrade test automation scripts

### ISSUE THREAD

**Issue by kycheng** [goharbor/harbor#18551]
**Is your feature request related to a problem? Please describe.**

I'm testing an upgrade of harbor and in the docs I found a page about upgrade verification.

https://goharbor.io/docs/2.7.0/administration/upgrade/upgrade-test/

But in the process of repeatedly testing and verifying whether the upgrade was successful, I found that this process is cumbersome.

**Describe the solution you'd like**

Two scripts can be written, which are respectively responsible for the preparation of test data and the function verification after the upgrade. Replace this tedious process.

**Additional context**

Test harbor upgrade from 2.2.3 to 2.7.1.

According to the documentation, I understand my upgrade path should be: 2.2.3 → 2.4.3 → 2.6.4 → 2.7.1

**Comment by YangJiao0817** [comment]
You can refer to some of the test cases below.
https://github.com/goharbor/harbor/tree/main/tests/robot-cases/Group1-Nightly
