### ISSUE TITLE
push image, when build image: no active sessions 

### ISSUE THREAD

**Issue by foreverrice** [goharbor/harbor#18554]
push old image alpine to harbor v1, size: 9.2M, no problem
But old image alpine to harbor v2, size:5.7M, when I build image:
![image](https://user-images.githubusercontent.com/33533816/233019292-4261cf07-b532-4a15-9c67-a3f930caf4c2.png)

**Comment by stonezdj** [comment]
From the error message, it seems to be an issue related to the docker daemon, not the registry.
