### ISSUE TITLE
Harbor `2.8.0` deleted Helm Charts, broken release pipelines, removed Chart repository functionality

### ISSUE THREAD

**Issue by sspreitzer** [goharbor/harbor#18573]
Hi there

I wanted to leave the feedback here, that the company I work for and my personal Open Source projects have been affected by the release of minor version `2.8.0` of Harbor. The following effects have been seen:

- Helm Chart release pipeline broke
- All existing Helm Charts deleted
- All ArgoCD based Helm Chart deployments are affected
  - ArgoCD SemVer Helm Chart deployments (eg. version: `1.*`) are impossible with Helm OCI 
  - index.yaml repository index files no longer supported

The folks at the company I work for and myself did not expect that the Harbor project would not follow the [semantic versioning](https://semver.org) principles and release a minor version that would break existing functionality in our environments. This would be expected for major version changes.

Rather attending KubeCon sessions, we are now recovering the aftermath of this change.

Please be mindful about future minor/major version bumps.

Thank you

**Comment by wy65701436** [comment]
Yes, we are fully **MINDFUL** of the deprecation. 


**HERE IS THE BACKGROUND INFORMATION FOR THE CHARTMUEUM DEPRECATION >>>>**

**_FIRST_**: Harbor has defined an official [deprecation process](https://github.com/goharbor/community/blob/main/proposals/feature-lifecycle-and-deprecation.md), which we will follow for any existing features.

**_SECOND:_** Harbor shares information with the public through various channels, such as discussions, emails, community meetings, and release notes.
- Discussion: https://github.com/goharbor/harbor/discussions/15057 
- Voting : https://github.com/goharbor/harbor/discussions/15057#discussioncomment-3361184
- The announcement on the v2.6.0(Start the deprecation of Chartmuseum from v2.6.0 and begin to remove in v2.8.0. More details, please refer to the https://github.com/goharbor/harbor/discussions/15057.): https://github.com/goharbor/harbor/releases/tag/v2.6.0
- Community meeting: [in this community meeting](https://youtu.be/ck51xJdxY5I?t=2149), we were discussed about chartmuseum deprecation, why, pros and cons and path forward.
  
  And more:
  1. 10 August 2022 - Official introductory community meeting
  2. 24 August 2022 - Discussion and questions welcome at community meeting
  3. 07 September 2022 - Discussion concludes during community meeting
  4. 10 September 2022 - Vote concludes - 50%+1 of maintainers must vote yes (+1) or silently assent

- The voting email: 

<img width="878" alt="image" src="https://user-images.githubusercontent.com/2841473/233967264-c4c90756-6660-483e-b1ae-aa93cbe0fc8d.png">


**LAST**: We welcome and appreciate any feedback from the community. We will continue to follow the defined deprecation process and share all relevant information with the community.

**Comment by sspreitzer** [comment]
@wy65701436 Thank you for the insight and summary.

## On Harbor Versioning

I think one of the most important information here is, that harbor is effectively [not following](https://github.com/goharbor/harbor/blob/7ace561e5565e839d08deaa4249cf3aef81ec2b8/RELEASES.md) the Semantic the versioning convention as outlined at [semver.org](https://semver.org), but uses version triplets as they are used in semantic versioning.

From semver.org:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards compatible manner
> PATCH version when you make backwards compatible bug fixes

From Harbot GitHub /RELEASES.md:
> Harbor releases will be versioned using dotted triples, similar to [Semantic Version](http://semver.org/).

**->** Harbor uses semantic versioning triplets, but does not follow the semantic versioning guidelines on the MINOR version part of the triplet, which could and can result in an impediment of community open-interoperability.

**->** Following the semantic versioning guidelines would harmonise community interoperability.

## On Helm Chart Repository indexes

I where not able to find information (including the one provided here) how Harbor would support Helm Chart repository indexes (index.yaml) in future. Nor did I find any information that the Harbor project members where aware at the time of decision of deprecating Chartmuseum that this would effectively drop important functionality.

Watching the community meeting on the Youtube video I could see that Chartmuseum was dropped from Harbor, because Chartmuseum was actively looking for maintainers and was about to retire Chartmuseum as a whole.

**->** It would be appreciated if Harbor would support Helm Chart Repository indexes (index.yaml) as it did before.

Thank you for your great work!

**Comment by yanji09** [comment]
@sspreitzer if you can provide the feedback during the deprecation discussion phase would be more helpful. But seems you were not actively follow the Harbor community and carefully read the release notes for each harbor version. The deprecation of Chartmuseum was discussed for very long time based on above comments from @wy65701436. 

And there is a Wiki published by Harbor to help users to migrate helm chart to OCI. https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

**Comment by OrlinVasilev** [comment]
@sspreitzer @MaxRink You are absolutely right that we have a lot of opportunity to improve in the future. As these were the first two deprecations following any process of voting and the actual implementation.
As I'm one of the authors of the process will add your recommended step to block, but not delete or remove functionality(if possible).

We are open governed project and as such any sudestions and ideas how to make it better are more than welcome!
Please join us on our regular community meetings so we can have more community input, by community I refer to non-maintainers and non-contributors but rather end users! We need your feedback to take the right decisions and on time!

Thank you!
Orlix

**Comment by sspreitzer** [comment]
@OrlinVasilev What day is that? I saw from the [last meeting notes](https://github.com/goharbor/community/wiki/Harbor-Community-Meetings) the time and login URL, but could not find and information about the schedule. 

*What would I contribute to the community meeting?*

* I would try to motivate the Harbor project to adopt the semantic versioning convention as a whole, to better manage expectations for end users. 
  * I don’t think that the Harbor project did make a wrong technology decision.
  * The semantic versioning convention allows users to have deterministic expectations on the behaviour of software without following each and every software projects announcements, newsletters, etc.. And not to be trapped in the «dependency hell».
  * Benevolent meritocracy for contributors to lead change in a harmonic way. Rigid processes and hierarchical structures tend to impede innovation instead of fuelling it.
  * Narratives such as «time’s up» or «you had your chance» might be valid by a projects policy and important to organise work and to achieve results, but not welcome in an interoperating community of sentient humans.

* I would explain the Helm Chart repository mechanism, which relies on index.yaml files and how projects like ArgoCD use that to choose Helm Chart versions based on semantic version ranges.
  * Eg. `version: ">=1.0.0"` or `version: "1.*"`.
  * Which enables automatic updates, continuous deployment.

* I would explain that semantic versioning would have introduced these disruptive technology changes in version `3.0.0` and most users would have picked them up in version `3.2.0` (quality improvements), following a `2.*` to `3.*` documented migration path or script.

**Comment by cnmcavoy** [comment]
We are similarly affected (although I caught that 2.8.0 has this change, and only upgraded our pre-production harbor) and I am wondering about the migration steps: https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

10 manual steps for a migration is rather burdensome for admins, especially with many (hundreds) of projects that have charts, and some of the "steps" are actually fairly involved (step 1, for example, is not trivial if you haven't set up harbor locally before). Was the community involved in deciding how the migration could be handled?

**Comment by OrlinVasilev** [comment]
Hi @cnmcavoy, thanks for your feedback adding few more folks here for visibility!
BTW I'm super surprised that this depreciation is getting attention now :)
Either way obviously we did terrible job to get the community engaged and informed, or the community is not following the discussions and voting! :) in both cases in on our side to be more vocal!(noted)

The first occurrence of that information is in https://lists.cncf.io/g/harbor-users/message/227?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2Cchartmuseum%2C20%2C2%2C0%2C83761958, then it was postponed due to implementing the new policy for deprecation.

So as always I urge anyone in the community to participate in meetings and to be checking discussions and meeting minutes!

@sspreitzer  will send again new notifications for the meeting, but you can find it in the calendar!

**Comment by cnmcavoy** [comment]
@Vad1mo I'm confused, I am under the impression the behavior I described is how Harbor documents OCI storage to work. If there is a bug, in my opinion it is with the migration process, which I think this issue already represents. Do you think there are additional bugs based on my notes? If so, it's unclear what they are to me.

**Comment by ChristianCiach** [comment]
We were luckily not affected, since we didn't use chartmuseum before, but I do think that such a breaking change (including data loss) should have been made *way* more explicit on the release notes.

(I don't really care if Harbor uses semantic versioning or not. As long as Harbor doesn't clearly states to use semantic versioning, it is wrong for any using to assume otherwise.)

The release notes of 2.8.0 on Github *does* state the removal of chartmuseum, but I don't this this is nearly enough to convey the consequences to the end user. For me, as the end user, this reads as some implementation detail that I don't really need to concern myself with.

I think that the release notes should have mentioned in clear words that this update removes the functionality to store helm charts in the previous format and that it will *delete* existing charts from the registry without converting them to OCI artifacts.

I read the release notes of release and I *still* could have easily been surprised by this change (if we'd happened to store helm charts in harbor), because the release notes only mentioned the removal of some technical component (which happens with almost every release without breakage), but not the consequences.

**Comment by abh** [comment]
> I think that the release notes should have mentioned in clear words that this update removes the functionality to store helm charts in the previous format and that it will delete existing charts from the registry without converting them to OCI artifacts.

Yeah, I read the release notes carefully (I thought) but didn't understand that this removed functionality rather than just changing the backend implementation until I got bug reports about the repository not working anymore.

https://github.com/ntppool/charts/issues/2

**Comment by kurld** [comment]
Where can I find any documentation how to use OCI type chart repository in Harbor 2.8?
The last mention of this feature can be found in 2.5 docs, but this is missing in 2.8.

[https://goharbor.io/docs/2.5.0](https://goharbor.io/docs/2.5.0/working-with-projects/working-with-images/managing-helm-charts/#manage-helm-charts-with-the-oci-compatible-registry-of-harbor)
