### ISSUE TITLE
[EPIC] Metrics Enhancement

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#18589]
Collected the following metrics requirements from the community, consider to do the enhancements in the v2.9.

- https://github.com/goharbor/harbor/issues/18137
- https://github.com/goharbor/harbor/issues/17531
- https://github.com/goharbor/harbor/issues/14375
- https://github.com/goharbor/harbor/issues/14352
- https://github.com/goharbor/harbor/issues/13356

**Comment by dkulchinsky** [comment]
Hey @chlins, I'm hoping https://github.com/goharbor/harbor/issues/15721 can be considered as part of this EPIC.

The new UI dashboard already provides this information (Job worker pool utilization & pending jobs queue length), but it's not exposed with metrics which are critical to monitoring & alerting.

**Comment by dkulchinsky** [comment]
not stale

**Comment by OrlinVasilev** [comment]
what abnout this one https://github.com/goharbor/harbor/pull/18679 looks pretty cool
