### ISSUE TITLE
how can I remove swagger UI

### ISSUE THREAD

**Issue by coolqz** [goharbor/harbor#18591]
harbor version: 2.7.0

**Comment by AllForNothing** [comment]
You can try to clone the code locally, and then go to the src/portal folder, remove it from the source code, and build the static files of the UI according to README.md. Finally, scp these static files to the /usr/share/nginx/html folder under the portal container

**Comment by coolqz** [comment]
I mainly want to disable the swagger function because I can obtain interface information through GET/swagger. json, and I don't want to expose it. How should I handle this

**Comment by coolqz** [comment]
> 
I mainly want to disable the swagger function because I can obtain interface information through GET/swagger. json, and I don't want to expose it. How should I handle this

**Comment by coolqz** [comment]
I mainly want to disable the swagger function because I can obtain interface information through GET/swagger. json, and I don't want to expose it. How should I handle this




1025947949
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goharbor/harbor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goharbor/harbor] how can I remove swagger UI (Issue #18591)





 
You can try to clone the code locally, and then go to the src/portal folder, remove it from the source code, and build the static files of the UI according to README.md. Finally, scp these static files to the /usr/share/nginx/html folder under the portal container

**Comment by AllForNothing** [comment]
Then you can delete it from the portal container directly:
`docker exec -ti -u root harbor-portal rm  /usr/share/nginx/html/swagger.json`
This will make the Swagger API Center unavailable

**Comment by coolqz** [comment]
> Then you can delete it from the portal container directly: `docker exec -ti -u root harbor-portal rm /usr/share/nginx/html/swagger.json` This will make the Swagger API Center unavailable

Okay, I just gave it a try and it's okay. Thank you very much

**Comment by dioguerra** [comment]
You can also create an ingress rule to drop /swagger. json requests.
