### ISSUE TITLE
harbor Set specified warehouse http/https/sock5 proxy

### ISSUE THREAD

**Issue by mcck** [goharbor/harbor#18604]
When creating a project again, choose proxy caching and cannot set the http/https/sock5 proxy. Some warehouses require VPN access, but others do not. I hope to set up an HTTP/https/sock5 proxy for a project

**Comment by MinerYang** [comment]
1. proxy cache https://goharbor.io/docs/2.8.0/administration/configure-proxy-cache/
2. set http proxy  for components https://goharbor.io/docs/2.8.0/install-config/configure-yml-file/
