### ISSUE TITLE
X-Forwarded-For for client requests

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#18614]
Hi all,

In our environments we detected a strange behaviour in the `proxy.log` in regards to X-Forwarded-For and the source IP.

When a user make a request via CLI (e.g. `docker pull`/`docker push`) we can see the request in the `proxy.log` and the source IP, because X-Forwarded-For in enabled on the Load Balancer.
But this is not working, if the user is within the portal.

Does anyone know if this is an known issue or how we can fix that?

Thank you in advance!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Vad1mo** [comment]
what is your exact setup and version? Given the provided information, I would say, it depends.

**Comment by wy65701436** [comment]
To provide you with better assistance, I would appreciate it if you could provide me with more information about the issue you are experiencing. 

- Can you please let me know what version of Harbor you are using? 
- Also, could you tell me more about how you installed Harbor? 
- Additionally, I would like to know more about your nginx configuration. Did you make any customizations to the default configuration?
