### ISSUE TITLE
Reverse Proxy crashing

### ISSUE THREAD

**Issue by vsubram95** [goharbor/harbor#18626]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Currently not able to pull images from the dockerhub through harbor(when it is configured as reverse proxy cache)

**Steps to reproduce the problem:**
Just create a new version of the harbor with dockerhub connection.
**Versions:**

Please specify the versions of following systems.

image:
repository: goharbor/harbor-core
tag: v2.8.0-rc2

**Additional context:**
Log Files
2023-05-02T00:12:50Z [ERROR] [/common/utils/utils.go:108]: failed to connect to tcp://harbor-registry-latest-helm-harbor-database:5432, retry after 2 seconds :dial tcp :5432: i/o timeout
2023-05-02T00:12:54Z [ERROR] [/common/utils/utils.go:108]: failed to connect to tcp://harbor-registry-latest-helm-harbor-database:5432, retry after 2 seconds :dial tcp :5432: i/o timeout
2023-05-02T00:13:00Z [ERROR] [/common/utils/utils.go:108]: failed to connect to tcp://harbor-registry-latest-helm-harbor-database:5432, retry after 2 seconds :dial tcp :5432: i/o timeout
2023-05-02T00:13:10Z [ERROR] [/common/utils/utils.go:108]: failed to connect to tcp://harbor-registry-latest-helm-harbor-database:5432, retry after 2 seconds :dial tcp :5432: i/o timeout
2023-05-02T00:13:28Z [ERROR] [/common/utils/utils.go:108]: failed to connect to tcp://harbor-registry-latest-helm-harbor-database:5432, retry after 2 seconds :dial tcp :5432: i/o timeout
2023-05-02T00:13:37Z [ERROR] [/pkg/audit/forward.go:44]: failed to create audit log, error dial tcp: missing address
2023/05/02 00:13:38.169 [I] [server.go:281]  http server Running on http://:8080
2023/05/02 00:49:41 httputil: ReverseProxy read error during body copy: unexpected EOF
2023/05/02 00:49:41.232 [C] [config.go:500]  the request url is  /v2/public/library/node/blobs/sha256:9280a10caf40b31effb3fd770e9eeef6ef656dd7ccd7b8bb93005a589dc55369
2023/05/02 00:49:41.232 [C] [config.go:501]  Handler crashed with error net/http: abort Handler
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/runtime/panic.go:884
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/httputil/reverseproxy.go:519
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:76
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/repoproxy/proxy.go:52
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/metric/metric.go:77
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/v2auth/auth.go:170
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/router/router.go:92
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/router.go:1149
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/filter.go:83
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/vendor/github.com/beego/beego/v2/server/web/router.go:1002
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/security/security.go:75
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/security/security.go:62
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/artifactinfo/artifact_info.go:97
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/notification/notification.go:31
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/orm/orm.go:54
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.232 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:52
2023/05/02 00:49:41.232 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/session/session.go:35
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/log/log.go:33
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/requestid/requestid.go:46
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/metric/metric.go:48
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/trace/trace.go:28
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/mergeslash/mergeslash.go:17
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/url/parse.go:22
2023/05/02 00:49:41.233 [C] [config.go:507]  /harbor/src/server/middleware/middleware.go:57
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2122
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:2936
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/net/http/server.go:1995
2023/05/02 00:49:41.233 [C] [config.go:507]  /usr/local/go/src/runtime/asm_amd64.s:1598
2023/05/02 00:49:42 httputil: ReverseProxy read error during body copy: unexpected EOF
2023/05/02 00:49:42.791 [C] [config.go:500]  the request url is  /v2/public/library/node/blobs/sha256:8f993d5b17f32f4b8a535c25e182e5d8412625beee450e513ca57036e8fdd6dc
2023/05/02 00:49:42.791 [C] [config.go:501]  Handler crashed with error net/http: abort Handler

**Comment by wy65701436** [comment]
did you check the status of DB? it seems that harbor-core cannot connect database successfully.

**Comment by vsubram95** [comment]
Hi @wy65701436 after fixing the DB issue. Current it throws
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2023/05/04 05:10:36.072 [D]  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
2023-05-04T05:10:36Z [ERROR] [/pkg/audit/forward.go:44]: failed to create audit log, error dial tcp: missing address
2023/05/04 05:10:37.066 [I] [server.go:281]  http server Running on http://:8080
2023-05-04T08:03:41Z [ERROR] [/controller/proxy/manifestcache.go:86]: error when push manifest list to local :manifest list doesn't contain any pushed manifest

**Comment by stonezdj** [comment]
What is the installation type of your Harbor instance? docker-compose or helm-chart? Is it work as a normal registry, such as push and pull image  to this Harbor?

**Comment by vsubram95** [comment]
Hi @stonezdj, I am currently trying to install this setup using the official helm chart provided by harbor. The main function of this is to work as a proxy cache.

**Comment by stonezdj** [comment]
The panic might be caused by the client-side timeout setting when pulling image.
