### ISSUE TITLE
Replication is failing between geos

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#18627]
Hello,

Harbor VM 2
Scalable VM 2
Database(Postgres) VM 2
Redis VM 3(Master-Slave-Slave)
Harbor Version v2.7.0
Docker version 19.0.0
docker-compose version 1.26

We could see that the replcation is failing sometime between europe and japan regions with below error

artifact ds-tomee:8.0.14 pulled
May  1 00:06:39 ip-172-22-0-1.eu-west-1.compute.internal jobservice[13283]: 2023-05-01T00:06:39Z [INFO] [/controller/replication/transfer/image/transfer.go:473]: the manifest of artifact ds-operations:2.0.5_20211122134956267 pulled
May  1 00:06:39 ip-172-22-0-1.eu-west-1.compute.internal jobservice[13283]: 2023-05-01T00:06:39Z [INFO] [/controller/replication/transfer/image/transfer.go:473]: the manifest of artifact ds-mariadb:0.1.14_20220401141333792 pulled
May  1 00:06:39 ip-172-22-0-1.eu-west-1.compute.internal jobservice[13283]: 2023-05-01T00:06:39Z [INFO] [/controller/replication/transfer/image/transfer.go:473]: the manifest of artifact ds-centos:4.0.0_20210722173037422 pulled
May  1 00:06:39 ip-172-22-0-1.eu-west-1.compute.internal jobservice[13283]: 2023-05-01T00:06:39Z [ERROR] [/controller/replication/transfer/image/transfer.go:335]: failed to check the existence of blob sha256:d5fd17ec1767521cf97f61568096bfc9a7cd9c2d149576a7b43930c5a97062b0 on the destination registry: Head "https://aws.com/registry-123456789-usw/Registry_a8dpVxP1SRq7Hl4HS7UTQA/docker/registry/v2/blobs/sha256/d5/d5fd17ec1767521cf97f61568096bfc9/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q7P87QHXMO9KLOLAZFDE%2F20230501%2Fus-west-1%2Fs3%2Faws4_request&X-Amz-Date=20230501T000639Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=62108152b489ef2f6392c598fab2f26a91ab0237f079fe135a6a8684b": EOF

Thanks,
Ayush

**Comment by wy65701436** [comment]
Please ensure that the request timeout between the registry and AWS has not been exceeded. 

To check the time cost for the head request, please check the proxy log of your source harbor. If the head request took more than 60 seconds, it is recommended that you investigate potential network issues.
