### ISSUE TITLE
Replication does not delete empty project

### ISSUE THREAD

**Issue by Lima118** [goharbor/harbor#18629]
Hi!

I came across an interesting issue with Replication between two Harbor Instances.
Everything works fine regarding the image replication, however.

How I imagine it working:
I use Replication between two Harbor Instances, where the replication creates the destination Project based on the source Harbor structure. I enable the deletion of the images if it is deleted on the source Instance.
When I delete an image in the source Instance it deletes the image in the destination Instance too, just like it should.
The issue comes up, when I delete all images and after that I delete the source Project too. I would like it if would have deleted the Project on the destination Instance too, especially when It was created by the Replication rule.

How it works in reality:
In reality if I delete an empty Project in the source it does not delete the empty Project in the destination Project even tho it was created with the Replication rule.
It leaves an empty Project without Images, that will not be filled up in the future, because it was deleted on the source Instance.
If I want to delete the Project on the destination too, I have to do it manually.

I would like to ask if it is possible to follow up the Project deletion too with a Replication rule between Harbor Instances.

Thanks,
Lima

**Comment by wy65701436** [comment]
yes, it's a by-design behavior. 
From a replication perspective, it should only handle the creation and deletion of artifacts. In your specific case, it appears to be more of a data synchronization or project synchronization capability, rather than a replication capability.

**Comment by Lima118** [comment]
Yes, I undestand.

I will keep this in mind in the future, when managing replication between the two instances.
Thanks for the fast reply and the clarification.
