### ISSUE TITLE
Robot accounts with limited permissions can create accounts with full permissions

### ISSUE THREAD

**Issue by irrandon** [goharbor/harbor#18636]
It is possible to create a robot account with all permissions by using a robot account that only has permissions to create other robot accounts. This creates a security vulnerability in the system.

**Expected behavior**

A robot account with limited permissions to create other robot accounts and limited permissions to access certain resources should not be able to create another robot account with more permissions than itself.

**Steps to reproduce the problem**

+ Create a robot account with only permissions to create other robot accounts .
+ Use the limited robot account to create another robot account with all permissions.

**Versions**

Harbor version: 2.8.0
Docker engine version: 23.0.5
Docker-compose version: 2.17.3

**Additional context**

This issue was encountered in the use case of automatically creating robot accounts for customers. The issue was tested on a fresh install with default settings.

**Comment by wy65701436** [comment]
@irrandon if you find any potential security issue, please follow this [process](https://github.com/goharbor/harbor#reporting-security-vulnerabilities) to report.
