### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jepson66** [goharbor/harbor#18640]
My system is macos m1 virtual machine ubuntu20.04, and the installed harbor is v2.2.2. After the self-signed certificate, docker pull is fine, but kubectl run deploys the pod, but it prompts x509: certificate signed by unknown authority. I toss for 4 days ok, can someone help me?

![image](https://user-images.githubusercontent.com/108441697/236374322-d4bb3e7f-8b5c-4e8a-b688-cebda5d8369b.png)

**Comment by MinerYang** [comment]
This is not a Harbor related issue.
It is about how to using/ configuring a private registry within you Kubernetes cluster.
Maybe these doc would help you 
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry

**Comment by jepson66** [comment]
ok，thanks，I‘ll triing it

**Comment by jepson66** [comment]
@MinerYang ,Or not
![image](https://user-images.githubusercontent.com/108441697/236596444-d35d0897-9fd1-4274-bef8-0b52d132dd52.png)
![image](https://user-images.githubusercontent.com/108441697/236596686-75733fa5-b55f-4ade-828b-cf56a0f824a0.png)
![image](https://user-images.githubusercontent.com/108441697/236596729-d4f38f21-60be-4304-a75d-4acf70a48292.png)

**Comment by MinerYang** [comment]
It also needs to [configuring-nodes-to-authenticate-to-a-private-registry](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry).
And it is really depends on what kind of Kubernetes cluster/ provider you are using.
For example, if you are using kind, you could refer to [this doc](https://kind.sigs.k8s.io/docs/user/private-registries/#use-a-certificate)

I am afraid you need to figure this out yourself , close by this is irrelevant to harbor

**Comment by jepson66** [comment]
@MinerYang I used the microk8s tool to install it, and I found a solution, which is different from the regular configuration file location. thank you
