### ISSUE TITLE
Integrate Notary v2(notation) with Harbor

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#18645]
Supply chain security is getting more important for users and industry field now and in the future. As a widely used trusted private registry, Harbor, we would like to provide more tools like [notary v2](https://github.com/notaryproject/notation) to help you build security into your  supply chain and make a community collaboration with signature been integrated with [OCI image specifivation v1.1](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc3/image-index.md).

**Comment by wy65701436** [comment]
closed by https://github.com/goharbor/harbor/pull/18909
