### ISSUE TITLE
Helm push chart to harbor (oci)  unauthorized 401

### ISSUE THREAD

**Issue by lklkxcxc** [goharbor/harbor#18656]
helm version: v3.11.3
harbor version: 2.1.0

helm login harbor success :
```shell
helm registry login -u admin harbor.xxx.cn
Login Succeeded
```
but push  error，use helm cm-push successed by chartsumseum mode:
```shell
helm push gpu-operator.tgz oci://harbor.xxx.cn/chartrepo/charts
Error: unexpected status from HEAD request to https://harbor.xxx.cn/v2/chartrepo/charts/gpu-operator/blobs/sha256:e0e5c0c37037fee94b40dffef2da1ca3eddd5cd924408d0ffd2f6f11a7ad634d: 401 Unauthorized

```

reference：https://helm.sh/zh/docs/topics/registries/

**Comment by stonezdj** [comment]
Target is wrong: it should be `oci://harbor.xxx.cn/<project_name>`
see
https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

**Comment by Labman4** [comment]
use offical push,  helm-push have been rename as cm-push after v0.10.0

**Comment by Labman4** [comment]
> use offical push, helm-push have been rename as cm-push after v0.10.0
here is link https://helm.sh/zh/docs/topics/registries/
