### ISSUE TITLE
The admin menu is displayed when a general user logs in.

### ISSUE THREAD

**Issue by woogeee** [goharbor/harbor#18651]
Our security team found some bug.
When a general user logs in, and they run request intercept like flowing image.

![image](https://user-images.githubusercontent.com/11792491/236765690-d973068c-1ca6-4962-8489-479da32e27b0.png)

Then, The admin menu is displayed.

![image](https://user-images.githubusercontent.com/11792491/236765820-d6664586-1654-496c-b118-67e279ff242e.png)

Harber version : Version v2.2.3-74ecf354

**Comment by MinerYang** [comment]
Hi @woogeee , Next time if there's any security issue ,please follow this [process](https://github.com/goharbor/harbor#reporting-security-vulnerabilities) to report.

**Comment by AllForNothing** [comment]
@woogeee Harbor UI is a SPA, so you can get all the static files (CSS, js HTML) without auth, it means you can visit any UI page in the hack way like this.  But this is not a security issue, because, without APIs, you can not see any protected data

**Comment by MinerYang** [comment]
Like @AllForNothing explained, it is only a UI behavior and it still follow the RBAC means even with that admin menu, nothing could be done other than showing the static view. We don't consider this as an issue, and would like to close this one this time.

**Comment by woogeee** [comment]
Hi @MinerYang @AllForNothing, in this case, almost menu not working. But, "Groups" menu is working. Please check again.

![image](https://github.com/goharbor/harbor/assets/11792491/f902a837-b76c-48d7-9fa5-2002a3e520ce)
Groups Button is working.

![image](https://github.com/goharbor/harbor/assets/11792491/43127c41-9356-4ffb-8fb5-afdc025fa763)
Other Menu is not working.

**Comment by wy65701436** [comment]
@woogeee if you find any potential security issue, please follow this [process](https://github.com/goharbor/harbor#security), and discuss any detail with us using email.

**Comment by AllForNothing** [comment]
@woogeee Does your user have `project admin` role for a certain project. If so, this is the expected behavior.
For Harbor version < 2.4.x,  `project admins` have the permission to list usergroups.

**Comment by woogeee** [comment]
Hi @AllForNothing, Thank for your answer.
Upgrading Harbor to 2.4.x or later disables the "groups menu" for project admin?

**Comment by AllForNothing** [comment]
@woogeee Yes. Recommend upgrading to the latest version(2.8.1)

**Comment by woogeee** [comment]
@AllForNothing 
In the same situation, the "Labels" menu is also activated. Does version 2.8.1 solve this problem as well?

**Comment by AllForNothing** [comment]
@woogeee No need to solve this as everyone can list global labels(Only system admins can create and delete)
