### ISSUE TITLE
Time to time push image error: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by Razniak** [goharbor/harbor#18663]
**Issue description:**
Hi, our environment is running on docker (2 separate hosts clustered), behind the f5 address that directs traffic to 2 Harbor instances. We copy images to the application using skopeo, and we have storage configured on s3, from time to time when copying images to the application we get:
time="2023-05-10T07:25:05Z" level=fatal msg="reading blob sha256:fad5e4647414c73776ca4c404786edf4acc70f59529db509bd19fdaf5ba4d852: Get \"***/v2/image/blobs/sha256:fad5e 4647414c73776ca4c404786edf4acc70f59529db509bd19fdaf5ba4d852\": net/http: TLS handshake timeout"

Are we able to somehow improve our nginxia so that TLS handshake timeout does not occur?

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.8.0
- docker engine version: [23.0.3]
- docker-compose version: [1.29.2]

**Comment by stonezdj** [comment]
Is the storage s3 compatible? or AWS s3 service?
Maybe there is no common TLS cipher suite between teh server side and the client side.
Another option is to disable redirect in the harbor.yml
```
storage_service:
  redirect:
    disable: false
```

**Comment by chlins** [comment]
Could you also debug the debug log of skopeo and observe the time interval between reading the blob from the beginning to the occurrence of the problem?

**Comment by jobcespedes** [comment]
Same issue here using Harbor with buildx and building multiple architectures. The errors say:
```
ERROR: failed to push <harbor_server_url> failed to do request: Head "<minio_server_url>": net/http: TLS handshake timeout
exporting to image:
error: failed to solve: failed to push <harbor_server_url>: failed to do request: Head "<minio_server_url>": net/http: TLS handshake timeout
```

**Comment by stonezdj** [comment]
@jobcespedes did you try this workaround: https://github.com/goharbor/harbor/issues/18663#issuecomment-1543622422 ?

**Comment by jobcespedes** [comment]
Yes. Disabling did it, using `true` instead of `false`:
```
storage_service:
  redirect:
    disable: true
```
Sorry for not sharing before and thanks.
