### ISSUE TITLE
Cannot create new account on the demo website

### ISSUE THREAD

**Issue by csseow** [goharbor/harbor#18665]
Hi,

There is no 'sign up new account' button on the website.

Thanks.
![Screenshot 2023-05-11 at 10 43 22 AM](https://github.com/goharbor/harbor/assets/82497675/bd78b45f-5f2e-4a23-aa46-bc9d4cdbc5de)

**Comment by chlins** [comment]
This website is just a demo environment for users to explore Harbor, and there is no account registration function. The default username and password is `admin/Harbor12345`.
