### ISSUE TITLE
Replication support for helm charts from Harbor to JFrog Artifactory

### ISSUE THREAD

**Issue by krrishkishore** [goharbor/harbor#18670]
Is this feature available already ? If yes, I am unable to use please help me in resolving this.

I am trying to replicate helm charts from Harbor v2.6.1 and below are the logs what I see in the failed scenario.

2023-05-09T17:49:59Z [INFO] [/controller/replication/transfer/chart/transfer.go:92]: client for source registry [type: harbor, URL: https://harbor-core:443, insecure: false] created
2023-05-09T17:49:59Z [ERROR] [/controller/replication/transfer/chart/transfer.go:98]: failed to create client for destination registry: the adapter doesn't implement the "ChartRegistry" interface

**Comment by dioguerra** [comment]
You should move away from legacy and into OCI charts

**Comment by chlins** [comment]
The chartmuseum was deprecated and removed since v2.8, recommend migrating to OCI chart which support replication as container images. A guide for migration: https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

**Comment by krrishkishore** [comment]
If I am using helm chart based installation of Harbor and if I am upgrading from 2.7 to 2.8 is the migration is going to happen internally or is this something we have to take care of as stated in Question 3 of https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor#questions ?

**Comment by chlins** [comment]
> If I am using helm chart based installation of Harbor and if I am upgrading from 2.7 to 2.8 is the migration is going to happen internally or is this something we have to take care of as stated in Question 3 of https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor#questions ?

The migration will not be executed internally, you should do it by self before upgrade harbor.
