### ISSUE TITLE
Maybe a issue about gc: repeatly delete link file in revisions folder

### ISSUE THREAD

**Issue by obitolyz** [goharbor/harbor#18678]
```golang
// src/jobservice/job/impl/gc/garbage_collection.go

// via /v2/manifest api
if err := v2DeleteManifest(gc.logger, art.RepositoryName, blob.Digest); err != nil {
  // ...
}

// harbor implement
err := gc.registryCtlClient.DeleteManifest(art.RepositoryName, blob.Digest)
```
thx for the job. 
I have a question about gc. when delete manifest via `/v2/manifest` api, registry backend will delete its correponding tag folder and link file in revisions folder. 
But `gc.registryCtlClient.DeleteManifest` also deletes the link file in revisions folder. Is it **repeated**?

thx for any help for this question.

**Comment by wy65701436** [comment]
**v2DeleteManifest** targets to remove the tags that are attached to the artifact, and **DeleteManifest** targets to remove revisions folder of each repository.
