### ISSUE TITLE
some module directory disappears

### ISSUE THREAD

**Issue by obitolyz** [goharbor/harbor#18674]
```golang
// src/server/v2.0/handler/gc.go
import (
	"github.com/goharbor/harbor/src/server/v2.0/models"
	operation "github.com/goharbor/harbor/src/server/v2.0/restapi/operations/gc"
)
```
I cannot find models and restapi folder.
thx for any help.

**Comment by chlins** [comment]
You should run `make gen_apis` to generate these codes by go-swagger, refer to https://github.com/goharbor/harbor/blob/main/CONTRIBUTING.md for more development guides(something may outdated, contribution is welcome~).

**Comment by obitolyz** [comment]
> You should run `make gen_apis` to generate these codes by go-swagger, refer to https://github.com/goharbor/harbor/blob/main/CONTRIBUTING.md for more development guides(something may outdated, contribution is welcome~).

thx~
