### ISSUE TITLE
Upgrade migrate binary to v4.15.2

### ISSUE THREAD

**Issue by beltran-rubo** [goharbor/harbor#18698]
The migrate go-lang binary from https://github.com/golang-migrate/migrate is included in Harbor and have several CVEs related to go-lang libraries.

The version specified into the `Makefile` is 4.11.0 from 2020 but the latest version available in the official repo is 4.15.2. Is there any plans to upgrade this binary for Harbor project?

**Comment by chlins** [comment]
The migrate version specified in the `Makefile` is only for `notary`, and `notary` has been deprecated and will be removed in the v2.9, so there's no plan to upgrade the migrate version for `notary`, but harbor upgrade also replies on the `go-migrate`(currently used 4.15.1 which defined in the go.mod), we can take a look on upgrade this to latest version.
