### ISSUE TITLE
Clarifying the action of button "GC NOW"

### ISSUE THREAD

**Issue by tostt** [goharbor/harbor#18692]
**Is your feature request related to a problem? Please describe.**
It is not obvious that the "GC NOW" button on the "Clean up" page does not free disk space for all images. This is especially disconcerting when Quotas are activated because users can see that there is some disk space still being used, even after GC. This is most obvious when you delete all images in Harbor. I think most new users expect to see 0 bytes used after GC on an empty project.

**Describe the solution you'd like**
I suggest adding some text next to the "GC NOW" buttton. This text could be "Note : Any garbage collection operation (including the dry run) only covers images that were not uploaded within the previous two hours." This text is directly copied from paragraph [Handling Images That Are Still Uploading](https://container-registry.com/docs/administration-manual/terminal-deletion-of-images/)
In the case CG ignored some images, they could be mentionned in the log with something like "GC ignored the following images : ..."

**Comment by wy65701436** [comment]
thanks @tostt we could add a tooltip to describe the time window of GC.
