### ISSUE TITLE
Slow pushing of images, but fast pulling

### ISSUE THREAD

**Issue by edwardcookemacu** [goharbor/harbor#18706]
We're struggling with getting our harbor instance running in Kubernetes to push images quickly.
When we push them, it caps out at 100Mbps (almost exactly 100).
When we pull, it pulls at 700Mbps.

Is there any caps or limits that are available in Harbor that we could look at, we went through the settings and didn't see anything. Any other tricks we could try?

We deployed it to our K8s cluster with pretty close to defaults (just changed the persistent storage to true) with helm.

It's not the storage because that thing is blazing fast.
It's not the networking or ingress, pulling a static file pulls at 1Gbps (the max we have).
We're down to Harbor itself.

Some things we've tried:

push to an instance of harbor on the local machine-> same results, max push at right around 100Mbps
Disabled gzip -> same results
Disabled trivvy and notary in the core configmap -> same results

**Comment by chlins** [comment]
Is your upstream and downstream bandwidth on the network both 1G? You can try deploying a simple file server and attempt to upload a file to see the upload speed.

**Comment by chlins** [comment]
> push to an instance of harbor on the local machine-> same results, max push at right around 100Mbps

Could you create a simple file server and test upload/download on the local to check the speed?

**Comment by edwardcookemacu** [comment]
Just following up here, is there anywhere I can look to see if there is any bottlenecks anywhere?

**Comment by edwardcookemacu** [comment]
We think we actually figured out what it is, it's related to the single layer of the big image and the docker engine (maybe) compressing it during the push. When we broke it up in to many smaller images it pushed to Harbor much, much faster. I'm closing this since we found the problem to not be related Harbor.

**Comment by danielheimburg** [comment]
We have the exact same problem and its also related to a single huge layer, we cannot do anything about it though and despite the number of hardware we throw at this the push never goes above 100Mbit. We know layers arent supposed to be this big but we have a special use case for it and Im wondering if there is anything we can do to improve this in harbor?

**Comment by ecooke-macu** [comment]
We actually found it being the client as the problem, not Harbor itself. And it's single threaded per layer I believe, so I suspect the only thing to do to increase the speed would be to throw a faster CPU at it, not necessarily more cores. What we noticed is that on the large layer only a single core was getting used and the others weren't being used very much at all. I could also be mistaken, it was over a year ago that we were working on this problem.

What I don't know is if there is a way to disable compression in the Docker client during pushing. We never got that far into the problem and just went with multiple layer approach. Disabling compression may speed up the push if that's even a thing.

**Comment by danielheimburg** [comment]
Yes, definitly some layer issue and single core is probably true as well. I just dont understand why it would be so slow <100Mbit. Problem is when you have a large file that cant be split and I would assume some developer databases are this making docker very slow.

I know some docker clients can disable compression when sending but havent been able to make them work inside our CICD

**Comment by ecooke-macu** [comment]
I went diving through all of the docker cli code and found that it's hardcoded to use GO's default level of compression so using the docker cli there's no way to disable it. Which is unfortunate.

The reason it's 100Mb is that is just what it comes out to. A slower computer would have a lower rate. A faster computer should have a faster one. That's what we found anyways.
