### ISSUE TITLE
user_group to user relation

### ISSUE THREAD

**Issue by dmitry-g** [goharbor/harbor#18700]
Hello, could anyone please point where the relation of users to their groups is stored in database? I am trying to figure out if there is an issue with Harbor or I am missing something in configuration when project permissions (via groups) don't work in my case.

Let's say, a user signs in with OIDC:
1. General user info is saved to `harbor_user` table
2. OIDC info is saved to `oidc_user` table
3. Groups are saved to `user_group` table

As I see, common [user model has `groupIDs`](https://github.com/goharbor/harbor/blob/main/src/common/models/user.go#L40) field, but I cannot figure out how the user to groups relation is implemented. `groupIDs` field is not stored in the table either.

For example, when a group permission is set for a project using `project_member` table, how does Harbor match the groups of the user against the permission? In my case permissions work fine when they are set on user basis. Also, when a user is a member of `OIDC Admin Group`. But when they are a member of a regular group, they have guest permissions. So I am trying to pinpoint where this behavior occurs. Thank you in advance

**Comment by stonezdj** [comment]
The group and user relationship is mapped when user login, there is a group attribute for current OIDC user. it will map to the groupIDs ID in the user model.

You could check the "Group Filter" configuration is correct, see https://goharbor.io/docs/edge/administration/configure-authentication/oidc-auth/#configure-an-oidc-provider-in-harbor

**Comment by dmitry-g** [comment]
Hi @stonezdj maybe you've had a chance to take a look at this issue?

**Comment by dmitry-g** [comment]
Bumping the issue so it does not close

**Comment by stonezdj** [comment]
> groups

The groupIds field (https://github.com/goharbor/harbor/blob/06715af3038991e68f0f4819a7a51a0ab5f824e1/src/common/models/user.go#L40 )links the group information after the user login.
There is no limitation in the group count for a single user.
