### ISSUE TITLE
The target repository connection failed

### ISSUE THREAD

**Issue by pptfz** [goharbor/harbor#18713]
harbor version: v1.10.5-c35ef7d9

Problem description
![iShot_2023-05-22_17 20 32](https://github.com/goharbor/harbor/assets/44946546/a7326396-7e37-4493-9dc6-63df5b35e792)

Create a new remote repository and click Test connection to get an error
1. Ensure that the user name and password are correct
2. A test container running on the host where the harbor resides can connect to the target harbor host. Ports 80 and 443 are connected to the target harbor network
Which log should be checked to troubleshoot the problem

**Comment by chlins** [comment]
Is the version of target harbor is same with the source? The replication is recommended to used between the same version, and also your harbor version is out of support, please consider upgrading to new version.

**Comment by AllForNothing** [comment]
You need to uncheck the `verify remote cert` option if you use a self-signed cert
