### ISSUE TITLE
OIDC Authentication failed to verify connection

### ISSUE THREAD

**Issue by luandrea** [goharbor/harbor#18714]
I tryed to configure OIDC authentication on a new Harbor installation (Version v2.8.1-48a2061d) but when I test it, I'm getting:
* failed to verify connection

In core.log I find : 
May 22 10:25:02 ubuntu-bionic core[6216]: 2023-05-22T10:25:02Z [ERROR] [/server/v2.0/handler/oidc.go:33]: Failed to verify connection: {URL:https://login.microsoftonline.com/f2d7d6c5-...-71d/v2.0/.well-known/openid-configuration VerifyCert:true}, err: 404 Not Found:

- harbor version: v2.8.1-48a2061d
- docker engine version: Docker version 24.0.1, build 6802122
- docker-compose version: docker-compose version 1.17.1

**Comment by stonezdj** [comment]
What is your OIDC configuration, esp OIDC endpoint?

**Comment by luandrea** [comment]
Hi @stonezdj,
the OIDC endpoint is like this:

- https://login.microsoftonline.com/f2d7d-ABC-ce71d/v2.0/.well-known/openid-configuration

If I make a curl to it I get the configuration json correctly from the same server where Harbor is installed.

**Comment by luandrea** [comment]
Hi @dioguerra ,
I checked your issue, but I don't see any similar error message ad mine, for example a 404 Not Foud in core.log.

Can I look somewhere else for more detailed error? Could I put log in debug mode to see more?

**Comment by stonezdj** [comment]
Please remove the `.well-known/openid-configuration` suffix from the OIDC endpoint , because Harbor will append this suffix again and it result in the 404 error.

**Comment by luandrea** [comment]
Yes, this resolved the issue. Thank you very much. 

Maybe a better error message it would help.

**Comment by kevinetore** [comment]
@stonezdj The spec https://datatracker.ietf.org/doc/html/draft-ietf-oauth-discovery-10#section-3 mentions that the `well-known` metadata can be specified on different endpoints, for instance, for Openshift it's served under: https://openshift.default.svc/.well-known/oauth-authorization-server.

Is it possible to configure the suffix? As `.well-known/openid-configuration` doesn't return the needed endpoints.
