### ISSUE TITLE
With OIDC integrated with Azure AD, user information in Harbor user profile not updated with AD when user change name and mail address

### ISSUE THREAD

**Issue by googer-zhang** [goharbor/harbor#18715]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
harbor integrate with Azure AD through OIDC。
When user change his user name and mail address in AD, user profile in harbor still keeps the old value, not updated
should be updated , and has the same values in AD

**Steps to reproduce the problem:**
Harbor integrated with Azure AD through OIDC,
one user had already login harbor with AD account successfully, the user name and mail address in user profile is same with those in AD. 
but when user changes his name and mail address in AD, the user could use his name and password to login Harbor successfully
but those information (username ,mail address) in user profile in harbor still kept the old value , not updated automatically with those same values (user name, and mail address) in Azure AD,
**Versions:**
Please specify the versions of following systems.

- harbor version: [2.6.4]

**Comment by googer-zhang** [comment]
any one ever encountered with this issue?

**Comment by AllForNothing** [comment]
This is expected behavior.
Harbor stores the OIDC user info in DB. So you can remove this user in Harbor, then login to Harbor again

**Comment by geoger** [comment]
There will be issues in practice. Usually the user is not alone. he/she will be added into members of some project.
Then remove/delete the user directly will caused the user lost permission to access som projects.

**Comment by googer-zhang** [comment]
> This is expected behavior. Harbor stores the OIDC user info in DB. So you can remove this user in Harbor, then login to Harbor again

Just remove the user will cause some issues in practice. Usually the user had already been added to members of some projects, so, when the user removed/deleted, and after he/she login again,  he/she lost accessing permission of those projects . In practice, he/she even had forgotten what projects which he/she ever had permissions

**Comment by AllForNothing** [comment]
@googer-zhang The key point is that Harbor does not have a synchronization function now, if you don't mind, you can open a new issue(share the scenarios) as a feature requirement.
