### ISSUE TITLE
`helm repo add library https://core.harbor.domain/library` Error

### ISSUE THREAD

**Issue by openstep** [goharbor/harbor#18720]
I try to add my harbor to helm, but getting the below error:

```
Error: looks like "https://core.harbor.domain/library" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
```
I also tried with oci://core.harbor.domain/library but getting the same error.

How to add the harbor repo ro local helm?

harbor 2.8
helm v3.11.1 but same error with v3.8.0

I can however push, pull to/from the repo 
`helm push package-1.12.1.tgz oci://core.harbor.domain/library`

**Comment by openstep** [comment]
How do you create the `chartrepo/library`? On my installation there isn't a tab for chart repos, only a single repositories tab:
![image](https://github.com/goharbor/harbor/assets/3678404/14b36054-7d52-4b52-b320-28fd95f8223d)

**Comment by openstep** [comment]
No, it is not working either:
chartrepo/library" is not a valid chart repository or cannot be reached: failed to fetch https://core.harbor.domain/chartrepo/library/index.yaml : 404 Not Found

**Comment by ccgurley** [comment]
Also trying to use harbor as my helm repo. With chartmuseum support gone in 2.8, how do we go about adding our harbor instance as a helm repo? I'm getting the same errors as OP.
Thanks!

**Comment by AllForNothing** [comment]
Please refer this <wiki>(https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor), since chart has been removed in 2.8

**Comment by ccgurley** [comment]
Possibly a dumb question but I installed 2.8 as my initial install so I don't need to do any migrations I just need to be able to "helm repo add harbor harbor.domain.tld" it seams the /chartrepo/ does not exist as a fixed path anymore. so what path do I use as the URL to add my chart repo.

Apologies if I've missed something.

**Comment by stonezdj** [comment]
You can not add any oci chart repo because `helm pull oci://harbor.domain.tld/charts/pgo ...` don't require to add repo.

**Comment by ccgurley** [comment]
Ahh, thanks! got everything figured out now.

**Comment by abh** [comment]
On 2.7.0 (and previously) we had integration we had https://artifacthub.io pull the index.yaml file. Does the new version generate an index.yaml file from the helm artifacts in a project?

**Comment by stonezdj** [comment]
> On 2.7.0 (and previously) we had integration we had https://artifacthub.io pull the index.yaml file. Does the new version generate an index.yaml file from the helm artifacts in a project?

No, the index.yaml file is not available in OCI registry.
