### ISSUE TITLE
Harbor OIDC Admin Group Permission Problem

### ISSUE THREAD

**Issue by Tim-herbie** [goharbor/harbor#18730]
We are running Harbor in Kubernetes and using the OIDC Provider for Authentication. We defined a OIDC Admin Group in the Authentication Configuration. My OIDC User is Member of the Admin Group

When I try to access some specific resources via API/Curl with my OIDC User that is in the Admin Group, I get the message `unauthorized ` back. But with my OIDC User, I can do everything in the harbor application (GUI). 

I opened a issue in the harbor terraform provider before: https://github.com/goharbor/terraform-provider-harbor/issues/328

Curl:
```
curl -X 'GET' \
  'https://harbor.domain.de/api/v2.0/retentions/39' \
  -H 'accept: application/json' \
  -H 'authorization: Basic my-generated-authorization-token'
```

Response:
```
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}
```

**Expected behavior and actual behavior:**
I expected that the OIDC Admin User with the CLI Secret has the equal permissions like the local admin user that I can use it with the API or for the Terraform harbor provider.
That my OIDC Admin User get a valid response via API/Curl.

**Steps to reproduce the problem:**
1. First, I used the CLI Secret from my user profile in harbor and put the CLI Secret and my username in the the "Authorize" field in the swagger API Page to get autorized.
2. Choose the API Call `GET /retentions/{id}` and put in a existing retention policy id.
3. Copy the generated Curl Command, paste it in your terminal and execute it

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.8.0-89ef156d

**Comment by stonezdj** [comment]
Could you try this?
```
curl -X 'GET' \
  'https://harbor.de-cix.net/api/v2.0/retentions/39' \
  -H 'accept: application/json' \
  -u '<harbor_username>:<cli secret>'
```

**Comment by Tim-herbie** [comment]
Yeah sure. When I execute your Call command with my username and cli secret, I get the same message:
`{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}`

When I replace the values with the local admin user, it works.

**Comment by YangJiao0817** [comment]
For OIDC user calling API, please refer to https://github.com/goharbor/harbor/wiki/Harbor-FAQs#api, but the best way to call API under OIDC authentication is to create a system-level robot account and use the robot account to call API.

**Comment by Tim-herbie** [comment]
I created already a system-level robot account like described here https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533, but when I e.g. call the terraform harbor api with the username and secret of the robot-account, it does not work. I get `UNAUTHORIZED` and `Resource not found` Messages back.

**Comment by AllForNothing** [comment]
@Tim-herbie That API did you call?  The API should  be within the scope of the robot account's permission

**Comment by Tim-herbie** [comment]
I created the system-robot account and like described above and put the credentials in the terraform harbor provider. After that I run `terraform plan` and got the unauthorized and resource not found messages. The error messages are e.g. by retention policies or project_members

This is the json output from the robot-account:
`[{"creation_time":"2023-05-31T06:32:31.419Z","description":"test","disable":false,"duration":30,"editable":true,"expires_at":1688106751,"id":33921,"level":"system","name":"robot$test","permissions":[{"access":[{"action":"create","resource":"project"}],"kind":"system","namespace":"/"}],"update_time":"2023-05-31T06:32:31.419Z"}]`


At the moment, we are using the local admin account for the terraform api. But we would like to use a separate account like the robot-account or a oidc user, but both does not work at the moment.

**Comment by AllForNothing** [comment]
@Tim-herbie Looks like that your robot account does not contain `retention policies or project_members` permissions
Please refer (this)<https://github.com/goharbor/harbor/blob/main/src/common/rbac/const.go> to annually add the permissions you want (You may need to update the permission by API call, Harbor UI only displays some key permissions)

**Comment by Tim-herbie** [comment]
@AllForNothing  Okay, than I understood it wrong before.

When I look at your file, I would expect, that this should work, because `*` should match any resource types and also actions. Or have I to add permissions also for each project?

``` bash
curl -X 'POST' \
  'https://harbor.domain.de/api/v2.0/robots' \
  -H 'accept: application/json' \
  -H 'authorization: Basic Tokenishere' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: AnotherTokenishere \
  -d '{
  "secret": "mySuperTestSecret1!",
  "disable": false,
  "name": "test",
  "level": "system",
  "duration": 0,
  "description": "test",
  "permissions": [
    {
      "access": [
        {
          "action": "*",
          "resource": "*"
        }
      ],
      "kind": "system",
      "namespace": "/"
    }
  ]
}'
```

This Curl creates the Robot Account, but It does not change the errors when I call the API via Terraform with the credentials of the robot account:

```
harbor_username = "robot$test"
harbor_password = "mySuperTestSecret1!"
```

**Comment by AllForNothing** [comment]
Seems `kind` and `namespace` properties are wrong,  Can you update them as below then try again?
<img width="848" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/16318479-d503-434e-8394-cc79053c6073">

**Comment by AllForNothing** [comment]
And  also the "duration" should not be 0,   you should set an integer or -1 for never expires

**Comment by Tim-herbie** [comment]
I changed that. Know it looks a little bit better. I can e.g. list projects or retention policies and the terraform plan has errors.

Is the robot account currently able to also create robot accounts? Either he is not able or the permission for that is missing. I am still looking for that.

**Comment by Tim-herbie** [comment]
Okay, now it is a little bit weird for me :)

With that, I can e.g. list all projects, all registries, all robot-accounts, all retention-policies, but I can´t list one specific project with that command:
```
curl -X 'GET' \
  'https://harbor.de-cix.net/api/v2.0/projects/6' \
  -H 'accept: application/json' \
  -u 'robot$test:hereisthesecret'
```

Here is the currently Curl with the permissions to create the robot-account:
```
...
  -d '{
  "secret": "mySuperTestSecret1!",
  "disable": false,
  "name": "test",
  "level": "system",
  "duration": 0,
  "description": "test",
  "permissions": [
    {
      "access": [
        {
          "action": "*",
          "resource": "*"
        }
      ],
      "kind": "project",
      "namespace": "*"
    },
    {
      "access": [
        {
          "action": "*",
          "resource": "*"
        }
      ],
      "kind": "system",
      "namespace": "/"
    }
  ]
}'
```

**Comment by Tim-herbie** [comment]
Okay... Now it will much more weird.

When I call the Curl command withaut any of authentication, exactly the code under here, then I get the right response:

```
curl -X 'GET' \
  'https://harbor.de-cix.net/api/v2.0/projects/6' \
  -H 'accept: application/json'
```

I don't think this should work, but it does.

**Comment by AllForNothing** [comment]
@Tim-herbie 
`Is the robot account currently able to also create robot accounts?  can´t also list registries at the moment.`

Yes, robots can create robots.

`I can´t also list registries at the moment`:

 `{
          "action": "*",
          "resource": "*"
   }` ,   does not mean all permissions, and we have not tested it.  

`When I call the Curl command withaut any of authentication, exactly the code under here, then I get the right response:`

Is it a public project? for a public project, no auth is required for this API

**Comment by Tim-herbie** [comment]
@AllForNothing Yes, we have only public projects.
I added all permissions for projects, robots and repositories:

```
{
  "secret": "",
  "disable": false,
  "name": "test",
  "level": "system",
  "duration": -1,
  "description": "test",
  "permissions": [
    {
      "access": [
        {
          "action": "list",
          "resource": "member"
        },
        {
          "action": "read",
          "resource": "member"
        },
        {
          "action": "create",
          "resource": "member"
        },
        {
          "action": "delete",
          "resource": "member"
        },
        {
          "action": "update",
          "resource": "member"
        },
        {
          "action": "list",
          "resource": "repository"
        },
        {
          "action": "read",
          "resource": "repository"
        },
        {
          "action": "delete",
          "resource": "repository"
        },
        {
          "action": "update",
          "resource": "repository"
        },
        {
          "action": "pull",
          "resource": "repository"
        },
        {
          "action": "push",
          "resource": "repository"
        },
        {
          "action": "list",
          "resource": "robot"
        },
        {
          "action": "read",
          "resource": "robot"
        },
        {
          "action": "create",
          "resource": "robot"
        },
        {
          "action": "delete",
          "resource": "robot"
        },
        {
          "action": "update",
          "resource": "robot"
        },
        {
          "action": "list",
          "resource": "project"
        },
        {
          "action": "read",
          "resource": "project"
        },
        {
          "action": "create",
          "resource": "project"
        },
        {
          "action": "delete",
          "resource": "project"
        },
        {
          "action": "update",
          "resource": "project"
        }
      ],
      "kind": "project",
      "namespace": "*"
    },
    {
      "access": [
        {
          "action": "list",
          "resource": "registry"
        },
        {
          "action": "read",
          "resource": "registry"
        },
        {
          "action": "create",
          "resource": "registry"
        },
        {
          "action": "delete",
          "resource": "registry"
        },
        {
          "action": "update",
          "resource": "registry"
        },
        {
          "action": "list",
          "resource": "project"
        },
        {
          "action": "create",
          "resource": "project"
        }
      ],
      "kind": "system",
      "namespace": "/"
    }
  ]
}'
```

When I try the curl again, it does not work. It works without authentication, but when I add them it does not work anymore.

```
curl -X 'GET' \ 
  'https://harbor.de-cix.net/api/v2.0/projects/6' \
  -H 'accept: application/json' \
  -u 'robot$test:ibV7px0DzzGEwFGsvoJb3NP8cfVcBXe5'
{"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}
```

**Comment by Tim-herbie** [comment]
@AllForNothing ping

**Comment by Tim-herbie** [comment]
@AllForNothing I can also create the robot account, but the robot has not permissions to list the projects. When I only add the permissions for the kind project, it works.

It seems not to work to assign project and system level permissions to the robot account. That could be the problem. This happens also to me: [https://github.com/goharbor/harbor/issues/14145#issuecomment-825465502](url)

**Comment by AllForNothing** [comment]
I'm closing this issue, as it's not a bug currently. If needed, please open another issue as the feature request.
Here is a [PR](#18724) from the community, you can refer to this.
And we have added the enhancement for the robot account to the plan for v2.10

**Comment by Tim-herbie** [comment]
Okay, I saw that here is a existing merge request [https://github.com/goharbor/harbor/pull/18724](url), that hopefully provide the full permissions to the robot account.

But I will create a feature request that the CLI Secret from a OIDC User have the same permissions as the OIDC User itself.
