### ISSUE TITLE
External Trivy v0.30.11 with Harbor 2.2

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#18734]
Hi, I wanted to ask if it's possible to stand up an external Trivy instance of version 0.30.11 and add it in Harbor v2.2.0 as an interrogation service.

The reason we are trying to do this is because the integrated trivy is stuck 0.16.0 and right now we don't have plans to upgrade Harbor to a newer version. 

Please let us know if this plan is valid or not.

**Comment by wy65701436** [comment]
We do not recommend updating the Trivy version separately from the Harbor code. 
Additionally, the v2.2 version is no longer within the supported scope. We kindly request that you test your issue on the v2.6 or a newer version. If the problem persists, please reopen the issue.
