### ISSUE TITLE
prepare script preprocessing bug

### ISSUE THREAD

**Issue by vndroid** [goharbor/harbor#18733]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

```
# docker compose ps
NAME                IMAGE                                COMMAND                  SERVICE             CREATED             STATUS                          PORTS
harbor-core         goharbor/harbor-core:v2.8.1          "/harbor/entrypoint.…"   core                13 minutes ago      Up 10 minutes (healthy)         
harbor-db           goharbor/harbor-db:v2.8.1            "/docker-entrypoint.…"   postgresql          13 minutes ago      Up 10 minutes (healthy)         
harbor-jobservice   goharbor/harbor-jobservice:v2.8.1    "/harbor/entrypoint.…"   jobservice          13 minutes ago      Restarting (2) 33 seconds ago   
harbor-log          goharbor/harbor-log:v2.8.1           "/bin/sh -c /usr/loc…"   log                 13 minutes ago      Up 10 minutes (healthy)         127.0.0.1:1514->10514/tcp
harbor-portal       goharbor/harbor-portal:v2.8.1        "nginx -g 'daemon of…"   portal              13 minutes ago      Up 10 minutes (healthy)         
nginx               goharbor/nginx-photon:v2.8.1         "nginx -g 'daemon of…"   proxy               13 minutes ago      Restarting (1) 34 seconds ago   
redis               goharbor/redis-photon:v2.8.1         "redis-server /etc/r…"   redis               13 minutes ago      Up 10 minutes (healthy)         
registry            goharbor/registry-photon:v2.8.1      "/home/harbor/entryp…"   registry            13 minutes ago      Up 10 minutes (healthy)         
registryctl         goharbor/harbor-registryctl:v2.8.1   "/home/harbor/start.…"   registryctl         13 minutes ago      Up 10 minutes (healthy)
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.8.1]
- docker engine version: [24.0.1]
- docker-compose version: [2.18.1]

**Steps to reproduce the problem:**

I enabled the `internal_tls` config in `harbor.yml`, like this:

```
internal_tls:
  enabled: true
  dir: /data/mystack/etc/harbor/tls/internal
```

Relevant certificates have been produced according to the manual, then use docker-compose to start the services.

the harbor-jobservice and nginx container can not be started. Error is `x509: certificate signed by unknown authority`

After checking, it was found that the auto-configured certificate file is empty.

```bash
kane@harbor:/home/kane/harbor/common/config/shared/trust-certificates$ ll
total 0
-rwxr-xr-x 1 root root 0 May 25 02:11 core.crt
```

At the same time, I also found an issue that encountered the same failure [jobs container can not start, report x509: certificate signed by unknown authority](https://github.com/goharbor/harbor/issues/17679)

Referring to his method, manually copy a correct certificate file to restart the job service, and it can be started.

The container nginx also can not be started, the error is a lot of the same info.

```
nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
2023/05/24 18:33:27 [emerg] 1#0: SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
2023/05/24 18:34:18 [emerg] 1#0: SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
```

Please check this problem.

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by vndroid** [comment]
This indicates a serious problem with the prepare script, which cannot automatically determine and replicate certificates and cannot automatically add parameters to container mounts.

**Comment by MinerYang** [comment]
Please refer to this doc you could either use prepare tool `gencert` or manually make sure all the necessary certs for all the component are being included in the internal tls directory
https://goharbor.io/docs/2.8.0/install-config/configure-internal-tls/

**Comment by vndroid** [comment]
> Please refer to this doc you could either use prepare tool `gencert` or manually make sure the necessary certs for all the component are being included in the internal tls directory https://goharbor.io/docs/2.8.0/install-config/configure-internal-tls/

Sure, I have already done it, but the problem remains.

**Comment by MinerYang** [comment]
If `internal_tls` is enabled , the working process is :
Assume your  `data_volume` defined in the `harbor.yml` is `/data`
1. you specified the `internal_tls.dir: /internal` and correctly put all the [necessary component internal certs]( https://goharbor.io/docs/2.8.0/install-config/configure-internal-tls/) inside the directory. 
2. prepare will copy the files inside the `/internal` dir to the `/data/secret/tls`.
3. our docker compose jinja file, would specify the mount mount path for each crt and key to the containers , e.g.`/etc/harbor/tls/xxx.crt`

- Do not using `{harbor-path}/common/config/shared/trust-certificates` as your internal tls path, as it for would be cleaned up every time running install or prepare.

So, not recommend to modifying the docker-compose.yml file directly. Every time you re-configuring harbor, e.g. update the dir in harbor.yml, please restart harbor as a whole service by using `sudo ./prepare` and `sudo docker compose up -d`
https://goharbor.io/docs/2.8.0/install-config/reconfigure-manage-lifecycle/

**Comment by vndroid** [comment]
> If `internal_tls` is enabled , the working process is : Assume your `data_volume` defined in the `harbor.yml` is `/data`
> 
> 1. you specified the `internal_tls.dir: /internal` and correctly put all the [necessary component internal certs](https://goharbor.io/docs/2.8.0/install-config/configure-internal-tls/) inside the directory.
> 2. prepare will copy the files inside the `/internal` dir to the `/data/secret/tls`.
> 3. our docker compose jinja file, would specify the mount mount path for each crt and key to the containers , e.g.`/etc/harbor/tls/xxx.crt`
> 
> * Do not using `{harbor-path}/common/config/shared/trust-certificates` as your internal tls path, as it for would be cleaned up every time running install or prepare.
> * So, not recommend to modifying the docker-compose.yml file directly. Every time you re-configuring harbor, e.g. update the dir in harbor.yml, please restart harbor as a whole service by using `sudo ./prepare` and `sudo docker compose up -d`
>   https://goharbor.io/docs/2.8.0/install-config/reconfigure-manage-lifecycle/

I am not using `{harbor-path}/common/config/shared/trust-certificates` as my internal tls path, In the yaml. it is:

```yaml
# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 8080

# https related config
https:
  # https port for harbor, default is 443
  port: 8443
  # The path of cert and key files for nginx
  certificate: /data/mystack/services/harbor/harborCert/tls/private/example.com.crt
  private_key: /data/mystack/services/harbor/harborCert/tls/private/example.com.key

# Uncomment following will enable tls communication between all harbor components
internal_tls:
  # set enabled to true means internal tls is enabled
  enabled: true
  # put your cert and key files on dir
  dir: /data/mystack/services/harbor/harborCert/tls/internal
  # enable strong ssl ciphers (default: false)
  strong_ssl_ciphers: false
```

And I am not modifying the docker-compose.yml file directly. It can not work well. I copy the tls file to the trust-certificates manually.

The problem with the preparation program now is that the certificates configured in yaml cannot be moved correctly into the final product tls directory.

**Comment by MinerYang** [comment]
Will the certificate you put inside the ` /data/mystack/services/harbor/harborCert/tls/internal` be successfully copy to `/data/secret/tls` ?

**Comment by vndroid** [comment]
> Will the certificate you put inside the ` /data/mystack/services/harbor/harborCert/tls/internal` be successfully copied to `/data/secret/tls` ?

No, It doesn't work. `prepare` program can not copy it to `.../shared/trust-certificates`, And of course, the program won't start properly and will report an error.

Every time I update the Harbor version, I need to manually copy the certificate file to the target folder once, and restart the container, and it works fine.

**Comment by MinerYang** [comment]
> > Will the certificate you put inside the ` /data/mystack/services/harbor/harborCert/tls/internal` be successfully copied to `/data/secret/tls` ?
> 
> No, It doesn't work. `prepare` program can not copy it to `.../shared/trust-certificates`, And of course, the program won't start properly and will report an error.
> 
> Every time I update the Harbor version, I need to manually copy the certificate file to the target folder once, and restart the container, and it works fine.

What's your `data_volume`? As I explain above, prepare would only copy the `internal_tls.dir` to `{data_volume}/secret/tls`

**Comment by vndroid** [comment]
> > > Will the certificate you put inside the ` /data/mystack/services/harbor/harborCert/tls/internal` be successfully copied to `/data/secret/tls` ?
> > 
> > 
> > No, It doesn't work. `prepare` program can not copy it to `.../shared/trust-certificates`, And of course, the program won't start properly and will report an error.
> > Every time I update the Harbor version, I need to manually copy the certificate file to the target folder once, and restart the container, and it works fine.
> 
> What's your `data_volume`? As I explain above, prepare would only copy the `internal_tls.dir` to `{data_volume}/secret/tls`

```yaml
data_volume: /data/mystack/services/harbor/harborVolume
```

Yap, I see. But before `prepare` and `compose up`, the container report the error is `shared/trust-certificates` cert file not found.

**Comment by vndroid** [comment]
That's why I'll manually copy it once.

**Comment by MinerYang** [comment]
> That's why I'll manually copy it once. So what can I do to make the program work properly in case I customize data_volume?

Hi @vndroid ,

There's might be something wrong with the copy the certificate into shared files on your end platform. I have view a few of history issues, have a question here, are you using arm or ararch64 something other than amd64/x86_64 ?

**Comment by vndroid** [comment]
> > That's why I'll manually copy it once. So what can I do to make the program work properly in case I customize data_volume?
> 
> Hi @vndroid ,
> 
> There's might be something behavior different of copy the certificate into shared file with different filesystem. I have view a few of history issues, have a question here, are you using arm or ararch64 something other than amd64/x86_64 ?

No, It's regular amd64 arch. file system is ext4, OS is Debian 11.

**Comment by vndroid** [comment]
...

**Comment by MUSS-Davs** [comment]
Hello, i'm doing this tutorial: https://goharbor.io/docs/2.9.0/install-config/configure-internal-tls/ 
This generate the necesary crts and keys files, how can i configure the harbor.yml for copy this files to the containers.
This is the .yml file: 

```
hostname: harbor.local.ec

http:
  port: 80

https:
  port: 443
  certificate: ./data/cert/harbor.local.ec.crt
  private_key: ./data/cert/harbor.local.ec.key

internal_tls:
  enabled: true
  dir: ./data/cert
  strong_ssl_ciphers: false

harbor_admin_password: Harbor12345
```

All the necesary files are in data/cert
This are the state of the containers:
![imagen](https://github.com/goharbor/harbor/assets/107563158/9a4fae96-d556-4668-bf2d-3f5b64c20000)

And i get this error on goharbor/nginx-photon:v2.9.4 :

```
nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
2024/05/30 22:25:55 [emerg] 1#0: SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/harbor_cust_cert/harbor_internal_ca.crt, r) error:10000080:BIO routines::no such file error:05880002:x509 certificate routines::system lib)
```

Note: I change the prepare file with this: https://github.com/goharbor/harbor/issues/13465#issuecomment-839963247
and i get this:

```
docker run --rm -v $input_dir:/input \
                    -v $data_path:/data \
                    -v $harbor_prepare_path:/compose_location \
                    -v $config_dir:/config \
                    -v ./data/cert:/hostfs/data/cert \
                    --privileged \
                    goharbor/prepare:v2.9.4 prepare $@
```
