### ISSUE TITLE
confirm to writing pattern of component clair_adapter and harbor db

### ISSUE THREAD

**Issue by bingo4933** [goharbor/harbor#18740]
I'd like to make relevant certificate of clair_adapter and harborDB, however, I'm not sure the correct writing pattern in `openssl` command for example like :
1. clair_adapter
```bash
$ openssl req -sha512 -new \
-subj "/C=CN/ST=Beijing/L=Beijing/O=example/OU=Personal/CN=clair-adapter" \
-key clair_adapter.key \
-out clair_adapter.csr
```
2. DB
```bash
$ openssl req -sha512 -new \
-subj "/C=CN/ST=Beijing/L=Beijing/O=example/OU=Personal/CN=harbor_db" \
-key harbor_db.key \
-out harbor_db.csr
```

the `clair_adapter` 
- which is correct that  I should provide `CN=clair-adapter` or `CN=clair_adapter` ?

the same with `harbor_db`
- which one is correct, `CN=harbor-db` or `CN=harbor_db` ?

could you guys please help to confirm that?
thanks a lot.

Regards,

**Comment by bingo4933** [comment]
I know that seem like there are constraints with `CN` in harbor internal tls communication in [here](https://goharbor.io/docs/2.8.0/install-config/configure-internal-tls/)

but, those above component didn't mention in the table.

please help to confirm that.

**Comment by zyyw** [comment]
@bingo4933 it should be `CN=harbor_db`
Please navigate to the following page for more details:
* https://github.com/goharbor/harbor/blob/main/make/photon/prepare/scripts/gencert.sh#L101

**Comment by bingo4933** [comment]
hello @zyyw 
noted, thanks for help

**Comment by zyyw** [comment]
np. @bingo4933 may I know which Harbor version you are using? Currently, Trivy is the official scanner shipped with Harbor. Curious to know why you are using clair?

**Comment by bingo4933** [comment]
hi, @zyyw 
I've picked the latest version(current v2.8.1) of Harbor, I just followed some guy's blog which introduced deployment harbor before. So, I tried also to deploy clair in the harbor
