### ISSUE TITLE
Reduce head request send to the upstream registry in proxy cache

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#18752]
Sometimes there are lots of pull request will send too many head request to the upstream registry server like dockhub, and it will return 429 to the client, in order to serve the pull request to proxy cache, it is better to cache some head request to avoid 429. add  an option for the proxy cache project allow user to select how long it will refresh the digest for a single tag, hourly, daily or weekly.

**Comment by lusu007** [comment]
This issue is not stale at all...

**Comment by lusu007** [comment]
This isnt a stale issue...

**Comment by lusu007** [comment]
This isn't a stale issue. Is it possible to add a label to prevent further stale markings?
