### ISSUE TITLE
Is there a way to disable the admin user or limit the number of login attempts?

### ISSUE THREAD

**Issue by woogeee** [goharbor/harbor#18762]
Our security team pointed out a possible brute force attack on the admin user.
Is there a way to disable the admin user or limit the number of login attempts (repeated password entry)?
Our Harbor version : Version v2.2.3-74ecf354

**Comment by stonezdj** [comment]
There is a freeze time (1.5 sec) for a failed login, so it hard to brute force.

**Comment by AllForNothing** [comment]
Closing it as it is not security issue
