### ISSUE TITLE
Is NFS supported for HA outside of K8s?

### ISSUE THREAD

**Issue by eringet** [goharbor/harbor#18771]
We want to keep our harbor installation outside out K8s clusters, as we do not want to get into a dependency cycle, with k8s relying on images from harbor, and harbor running on k8s.  So we are looking at an HA cluster design basically as described in Solution 1 here - https://github.com/goharbor/harbor/issues/3582 

We have external database, redis and a shared /data which is NFS storage, shared between two harbor servers.  We are currently using harbor 2.4.0.

This  configuration works for a time, then pushes break.  The UI, pulls, and docker logins continue to work, but pushes fail.  Despite re-doing the docker login, all pushes start failing with minimal info, eg. 

`docker push myharbor-url.example.com/myproj/testimg:test2
The push refers to repository [myharbor-url.example.com/myproj/testimg]
d12b434cc431: Pushing [==================================================>]  29.44MB
ef8da9755495: Layer already exists
5f092f812712: Layer already exists
d73184360a99: Preparing
92740bab716b: Layer already exists
f555d719d9bb: Waiting
5bc340f6d4f5: Layer already exists
unauthorized: authentication required
`
I cannot find ANY relevant logs for the push attempt on either harbor server.   

I do find that if I turn harbor off on one of my 2 servers, I cannot replicate this problem.   

I am trying to determine if perhaps I should not even be trying to use NFS as the shared storage.  I see there were some issues using NFS a while back, in 2.1.0, and a custom patched image goharbor/registry-photon:v2.1.0-nfs was created.  I am assuming the fixes in this image are also in newer harbor versions?  

Thank you for any guidance on NFS usage.

**Comment by rknightion** [comment]
I think "solution 1" was made back in 2017 before Harbor was refactored into Microservices designed to run on k8s. 

We worked around the dependency cycle issue by running Harbor in a dedicated cluster just for harbor in its own separate account/region/datacenter, backed by object storage (NFS support has always been a problem for us). For a while we even had harbor running in 2 different k8s clusters (pointing to a shared RDS database & Elasticache cluster). The object storage element was key for us (but ultimately we found a single cluster in HA mode reliable enough for hundreds of prod clusters for us)

**Comment by AllForNothing** [comment]
Can you provide the log from the registry container?   Looks like it it a issue from NFS side

**Comment by eringet** [comment]
I'm betting it is related to NFS too..  I have my second server on, and am trying to get it to break again for me.  It is not performing on queue, unfortunately!  I will post logs, if there are any, as soon as I can get it in the bad state again.
