### ISSUE TITLE
Duplicate Layer From Multiple Users Requires Push

### ISSUE THREAD

**Issue by isugimpy** [goharbor/harbor#18791]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When building images with deterministic layers from separate users, we're finding that users can build the same layer with an identical sha, but are both required to push those layers to Harbor.  User A builds an image, pushing it to Harbor.  User B checks out the same commit, builds the same image, other than the tag.  It is confirmed that the layers have the same hash.  User B attempts to push.  Layers with the same sha256 checksum must be uploaded by User B.  If User B cancels the upload and tries again, the same behavior is observed.  However, if User B pulls User A's image which includes the same layers, User B then deletes the image locally, and then User B attempts to build and push their own afterward, User B no longer must push the duplicate layers.

The expected behavior would be that User B does not have to push a layer which already exists on the Harbor instance, because it is confirmed as already present, as in the case after the pull has happened in testing.

Further testing shows that if User A builds and pushes, User B pulls, and User C builds another deterministic copy, User C must still push the layers.

I'm certainly open to upgrading to attempt to resolve the problem, but nothing I've seen in any of the release notes between 2.5.1 and current releases suggests that this is a problem which was fixed in any known release.  I'd also point out that I believe it's entirely possible that this has been a long-standing issue, as I recognize it's unusual that two human users would build the same image and push to the same registry.  This is only rearing its head because we're running into this with some layers that are particularly large and take a while to upload.

**Steps to reproduce the problem:**
1. Build an image with deterministic layers.  It may be helpful to use a large, static file in one layer to ensure that the push takes a long enough time to observe.  A sample Dockerfile might be
```
FROM ubuntu:mantic-20230520

COPY <large-file> /<large-file>
```
2. Push the image to Harbor.
3. On a separate machine, with a separate user account, build and push the same.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.1
- docker engine version: User A (23.0.5), User B (24.0.0), User C (24.0.2)

**Comment by chlins** [comment]
If user A and user B push the same layer at the same time, and the layer has not yet landed, then this behavior is reasonable because only when the layer has landed, will it not be pushed repeatedly.

**Comment by isugimpy** [comment]
I agree that would be reasonable.  This isn't happening at the same time.  Apologies, I should have specified.  We were actively coordinating and leaving spans of at least 2 minutes between the completion of the push by User A before User B's push started.  In one case of our testing, User A pushed several days earlier, on a Friday and the behavior still occurred when User B pushed on the following Monday.

**Comment by chlins** [comment]
Hi, I tried to reproduce the issue in my environment, I prepared Dockerfile similar with yours and copy a same big file then user A build and push the image with big:v1, after it pushed successfully then I build the image to big:v2 with the same Dockerfile then push by user B, then the command line shows the layer existed which not push the duplicate layer.

User A push big:v1
<img width="687" alt="image" src="https://github.com/goharbor/harbor/assets/31262637/30bf66b5-4078-44fe-9202-446d1477f108">

User B push big:v2 after User A pushed successfully
<img width="699" alt="image" src="https://github.com/goharbor/harbor/assets/31262637/19ed5737-aed7-4e81-8c4e-5d63f99d2d02">

**Comment by isugimpy** [comment]
I haven't been able to reduplicate this with further testing, so I'm chalking it up to a weird behavior on our end.
