### ISSUE TITLE
ScannerRegistration.properties.url-format is wrong

### ISSUE THREAD

**Issue by liubin** [goharbor/harbor#18798]
When running `make compile_core`,  I got these error:

```
 8191:18    error  oas2-valid-definition-example       `example` property should match format `url`                   definitions.ScannerRegistration.properties.url.example
 8191:18    error  oas2-valid-response-schema-example  `example` property should match format `url`                   definitions.ScannerRegistration.properties.url.example
```

The `format` is wrong for ScannerRegistration object.

```diff

grep -A3 -B2 "format: ur" api/v2.0/swagger.yaml 
      url:
        type: string
        format: url
        description: A base URL of the scanner adapter
        example: http://harbor-scanner-trivy:8080
      disabled:
--
      url:
        type: string
        format: uri
        description: A base URL of the scanner adapter.
        example: http://harbor-scanner-trivy:8080
      auth:
--
      url:
        type: string
        format: uri
        description: A base URL of the scanner adapter.
        example: http://harbor-scanner-trivy:8080
      auth:
```

Referencing to `ScannerRegistrationReq` and `ScannerRegistrationSettings`, I think the right format should be `uri` but not `url`.

**Comment by wy65701436** [comment]
@zyyw can you ensure why the swagger lint cannot cover this failure? https://github.com/goharbor/harbor/blob/main/Makefile#L289

**Comment by zyyw** [comment]
Hi @liubin, thanks for reporting this issue. It seems that I can run `make compile_core` successfully against the latest main branch (commit 1d2624eefcdd75aec6013a85fde3383d154ed35b) of goharbor/harbor project on ubuntu(20.04 amd64) env.

Some information about the environment the `` is running:
```
ubuntu@sc1:~/go-workspace/src/github.com/goharbor/harbor$ docker images
REPOSITORY          TAG       IMAGE ID       CREATED         SIZE
goharbor/swagger    v0.25.0   3bd0711574b4   3 minutes ago   794MB
goharbor/spectral   v6.1.0    a44f77af1f19   3 minutes ago   837MB
golang              1.20.4    6a90a37099af   5 weeks ago     777MB
ubuntu@sc1:~/go-workspace/src/github.com/goharbor/harbor$ docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by zyyw** [comment]
Also found this:
https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L8183-L8187

https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L8263-L8267

https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L8302-L8306

**Comment by zyyw** [comment]
there are quit a few urls in the `swagger.yaml` that do not specify any `format`, for example:
https://github.com/goharbor/harbor/blob/1d2624eefcdd75aec6013a85fde3383d154ed35b/api/v2.0/swagger.yaml#L7251-L7253
https://github.com/goharbor/harbor/blob/1d2624eefcdd75aec6013a85fde3383d154ed35b/api/v2.0/swagger.yaml#L7290-L7293

I am thinking about removing the `format: uri` or `format: url` of `ScannerRegistration`, `ScannerRegistrationReq` and `ScannerRegistrationSettings` so that they are all consistent without `format`.

@wy65701436 How do you think of it?

**Comment by zyyw** [comment]
@liubin could you please share you were running `make compile_core` against which commit (main branch? I suppose) when you encounter the following error?
```
 8191:18    error  oas2-valid-definition-example       `example` property should match format `url`                   definitions.ScannerRegistration.properties.url.example
 8191:18    error  oas2-valid-response-schema-example  `example` property should match format `url`   
```

Also would you mind share with us the output of the following command:
```
docker images | grep -E 'swagger|spectral'
```

**Comment by liubin** [comment]
@zyyw here is the output:

```
goharbor/swagger    v0.25.0   9b5f01651bc7   3 weeks ago     811MB
goharbor/spectral   v6.1.0    62ef103b0ab7   3 weeks ago     891MB

```
