### ISSUE TITLE
Proxy Cache, not act as transparent docker mirror

### ISSUE THREAD

**Issue by Faarhad** [goharbor/harbor#18807]
I've tested Version v2.8.0-89ef156d and I realized that from v2.1 there is a proxy cache in Harbor.
I configured it as explained in the documentation, but I need to use a command like:
`docker pull nginx`
and I need a direct answer from the harbor. I did the below steps.
1-configure harbor in a local_IP
2- set it as a registry mirror in daemon.json in the second VM.
3-create docker hub registry
4-create project with a name library and use it as cache (I deleted the auto-generated library project)
when I try to use docker pull it will go through docker.io not the Harbor.
I'll appreciate any help and idea.

**Comment by wy65701436** [comment]
did you follow this tutorial to configure your proxy cache project? https://goharbor.io/docs/2.8.0/administration/configure-proxy-cache/

**Comment by ChristianCiach** [comment]
This question pops up again and again. Short answer: No, you **cannot** use Harbor as a transparent mirror for Docker hub when using the Docker daemon.

A common workaround is to deploy a (request re-writing) reverse proxy in front of Harbor. See https://github.com/moby/moby/pull/34319#issuecomment-720606627 and the following comments.

**Comment by Faarhad** [comment]
@wy65701436 
Apologies for the delayed response.
Yes Sir, I did exactly the documentation, when I use for example:

`docker pull 192.168.111.53/library/hello-world`

it works correctly, but I need just the simple command like 

`docker pull hello-world`
