### ISSUE TITLE
harbor 2.6.0在安装过程中，harbor组件一直处于starting状态，无法正常拉起

### ISSUE THREAD

**Issue by nsdsb123** [goharbor/harbor#18833]
harbor 2.6.0在安装过程中，harbor组件除了harbor-log，一直处于starting状态，无法正常拉起，查看其他组件的信息，都是报错failed to create task for container: failed to initialize logging driver: dial tcp [::1]:1514: connect: no route to host，请问要如何解决

**Comment by wy65701436** [comment]
hi, could you please provide more information on how to configure the installation?

**Comment by zyyw** [comment]
Hi @nsdsb123 have you tried this:
https://www.cnblogs.com/heyongboke/p/14085945.html
