### ISSUE TITLE
Upgrading from PostgreSQL 9.6 to PostgreSQL 13 is not supported in the current Harbor release. You should upgrade to previous Harbor firstly, then upgrade to current release.

### ISSUE THREAD

**Issue by AtaraxiaRun** [goharbor/harbor#18839]
Same problem as this one #18252 
I had this problem today too:
Upgrading from PostgreSQL 9.6 to PostgreSQL 13 is not supported in the current Harbor release.
You should upgrade to previous Harbor firstly, then upgrade to current release.

As a result, I repeatedly restarted goharbor/harbor-db:v2.8.2 and goharbor/harbor-jobservice:v2.8.2

[root@rabbitmq-node2 harbor]# docker images
REPOSITORY TAG IMAGE ID CREATED SIZE
goharbor/redis-photon v2.8.2 6f4498a430ca 2 weeks ago 121MB
goharbor/harbor-registryctl v2.8.2 fa61a236a6d6 2 weeks ago 142MB
goharbor/registry-photon v2.8.2 f80e71363231 2 weeks ago 79.3MB
goharbor/nginx-photon v2.8.2 3d009028f260 2 weeks ago 120MB
goharbor/harbor-log v2.8.2 2914d282d9bf 2 weeks ago 127MB
goharbor/harbor-jobservice v2.8.2 40118f1568a8 2 weeks ago 141MB
goharbor/harbor-core v2.8.2 0bbbd1f379fc 2 weeks ago 165MB
goharbor/harbor-portal v2.8.2 3e74e0758aa4 2 weeks ago 127MB
goharbor/harbor-db v2.8.2 5126635ae9f0 2 weeks ago 174MB
goharbor/prepare v2.8.2 eb3cf3cdd17a 2 weeks ago 163MB
[root@rabbitmq-node2 harbor]# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
86bd43d71778 goharbor/nginx-photon:v2.8.2 "nginx -g 'daemon of…" 5 minutes ago Up 5 minutes (healthy) 0.0.0.0:80->8080/tcp, :::80->8080/tcp nginx
be05c0f23e76 goharbor/harbor-jobservice:v2.8.2 "/harbor/entrypoint.…" 5 minutes ago Restarting (2) 54 seconds ago harbor-jobservice
77f3506ed591 goharbor/harbor-core:v2.8.2 "/harbor/entrypoint.…" 5 minutes ago Up 45 seconds (health: starting) harbor-core
8830d56cd4af goharbor/redis-photon:v2.8.2 "redis-server /etc/r…" 6 minutes ago Up 5 minutes (healthy) redis
45ce70eeed50 goharbor/harbor-portal:v2.8.2 "nginx -g 'daemon of…" 6 minutes ago Up 5 minutes (healthy) harbor-portal
8be4ba84d050 goharbor/registry-photon:v2.8.2 "/home/harbor/entryp…" 6 minutes ago Up 5 minutes (healthy) registry
602733c7460c goharbor/harbor-registryctl:v2.8.2 "/home/harbor/start.…" 6 minutes ago Up 5 minutes (healthy) registryctl
13c53362ba64 goharbor/harbor-db:v2.8.2 "/docker-entrypoint.…" 6 minutes ago Restarting (1) 56 seconds ago harbor-db
e4e9282d449d goharbor/harbor-log:v2.8.2 "/bin/sh -c /usr/loc…" 6 minutes ago Up 5 minutes (healthy) 127.0.0.1:1514->10514/tcp harbor-log

**Comment by AtaraxiaRun** [comment]
I installed this first

Wget HTTP: / / https://github.com/goharbor/harbor/releases/download/v2.0.0/harbor-online-installer-v2.0.0.tgz



Install this again (this is the version that indicates PostgreSQL 9.6 to PostgreSQL 13 error)

Wget HTTP: / / https://github.com/goharbor/harbor/releases/download/v2.8.2/harbor-online-installer-v2.8.2.tgz

**Comment by YangJiao0817** [comment]
Upgrading from v2.0.0 to v2.8.2 is not supported, you should upgrade according to this policy https://github.com/goharbor/harbor/blob/main/RELEASES.md#upgrade-path-and-support-policy
