### ISSUE TITLE
Replication from harbor to amazon ecr via private link

### ISSUE THREAD

**Issue by samul69** [goharbor/harbor#18845]
Hi,
in all the documents I found as the endpoint url for replication with amazon ecr is used:
- https://api.ecr.eu-central-1.amazonaws.com
- https://account_id.dkr.ecr.eu-central-1.amazonaws.com
and with iam access and secret it works without any problems. 

But with this configuration we use public link. To use private connection i created dedicated vpc with private endpoints ecr.dkr & ecr.api (https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html), also setup vpn between my dc where is harbor located and aws vpc. 
Netcat show that it can connect:
nc -v vpce-0734a471bd2c1559e-1111111.dkr.ecr.eu-central-1.vpce.amazonaws.com 443
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 172.17.X.X:443.

When i provide mentioned url to harbor i got:
gui - Failed to ping endpoint. 
logs -  [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: bad aws url"}]}

No problems with dns resolution when i provide ip i got the same error.

For test purpose access to private endpoints is:
- not limited via access policy, 
- on security groups ports  TCP/80 and TCP/443 are open, 
- IAM user have full access to ecr service.

I use harbor in version v2.4.0-d4affc2e
i checked release notes for new versions but didn't found anything similar to my problem.

Does the described problem occur in newer versions? 
Is it possible to configure harbor to use a private endpoints?
is it just a url validation problem or is it more complicated?

**Comment by kingkye** [comment]
The private ECR's URL pattern does not fit.
I think the code below should be modified.
https://github.com/goharbor/harbor/blob/46f1fb0fd32a6372ff5bd4472dbf8740e9c82ff1/src/pkg/reg/adapter/awsecr/adapter.go#L32C3-L32C3
`ecrPattern = "https://(?:api|(\\d+)\\.dkr)\\.ecr\\.([\\w\\-]+)\\.amazonaws\\.com"`
