### ISSUE TITLE
Migrate Harbor instance from Filesystem/Block storage to Object Storage

### ISSUE THREAD

**Issue by lusu007** [goharbor/harbor#18843]
I currently have a Harbor instance running in my Kubernetes cluster, and I'm interested in transitioning the storage backend from block storage to object storage (specifically, S3). I'm wondering if there's an easy and straightforward way or a specific feature within Harbor that can facilitate this migration process to S3.

**Comment by stonezdj** [comment]
You could do it by replication.

**Comment by CoderTH** [comment]
> You could do it by replication.

We have the same problem. If replication is used, configurations related to mirror retention will be lost and need to be manually configured again (just one of them). What I want to do is migrate the entire harbor to another cluster and change the storage to s3. Or can replication solve this problem as well?

**Comment by lusu007** [comment]
Luckily, I successfully replicated the images from my previous registry, allowing me to fully redeploy Harbor and replicate all the data once more.

Implementing an automated migration to different storage types would greatly enhance the practicality of the process.

**Comment by CoderTH** [comment]
> Luckily, I successfully replicated the images from my previous registry, allowing me to fully redeploy Harbor and replicate all the data once more.
> 
> Implementing an automated migration to different storage types would greatly enhance the practicality of the process.

Is it convenient to ask how you operate, can the data other than the mirror be migrated?

**Comment by lusu007** [comment]
> Is it convenient to ask how you operate, can the data other than the mirror be migrated?

I don't know if I understand your question correctly, but I'll try to answer it.

I deployed Harbor via ArgoCD into my production cluster using the Bitnami Helm Chart. A migration from Harbor directly would only be possible if I were to deploy another instance of Harbor at the same time. Then I could utilize the replication feature of Harbor.

However, I believe a storage migration should be possible without deploying a second Harbor instance...

**Comment by stonezdj** [comment]
> > You could do it by replication.
> 
> We have the same problem. If replication is used, configurations related to mirror retention will be lost and need to be manually configured again (just one of them). What I want to do is migrate the entire harbor to another cluster and change the storage to s3. Or can replication solve this problem as well?

the configuration and retention policy is not replicated. you need to setup manually

**Comment by CoderTH** [comment]
> > > You could do it by replication.
> > 
> > 
> > We have the same problem. If replication is used, configurations related to mirror retention will be lost and need to be manually configured again (just one of them). What I want to do is migrate the entire harbor to another cluster and change the storage to s3. Or can replication solve this problem as well?
> 
> the configuration and retention policy is not replicated. you need to setup manually

The configuration related to image retention can be manually configured, but some configuration items are not easy to do, for example, we now have a lot of robot accounts used by a lot of ci cd pipelines, if the migration is carried out in this way, these accounts need to be manually set, which is a big cost

**Comment by CoderTH** [comment]
> > > You could do it by replication.
> > 
> > 
> > We have the same problem. If replication is used, configurations related to mirror retention will be lost and need to be manually configured again (just one of them). What I want to do is migrate the entire harbor to another cluster and change the storage to s3. Or can replication solve this problem as well?
> 
> the configuration and retention policy is not replicated. you need to setup manually

Is there a solution to move the harbor completely? Has anyone done this before?

**Comment by pkalemba** [comment]
We have all projects /replications /registry /retention configs in terrafrom code . So change of instance is not a big pain.

**Comment by lusu007** [comment]
> We have all projects /replications /registry /retention configs in terrafrom code . So change of instance is not a big pain.

I have effectively configured my settings using Terraform. However, the challenge lies not in the configuration migration, but rather in the migration of existing images. Currently, it is not feasible to perform a storage migration without creating a new instance and replicating the existing one. Nevertheless, I believe there should be a way to switch storage without necessitating the creation of a new instance.

**Comment by lusu007** [comment]
This isn't stale.

**Comment by lusu007** [comment]
This isn't stale.

**Comment by lusu007** [comment]
This issue isn't stale. Is it possible to add a label to prevent further stale markings? @stonezdj

**Comment by lusu007** [comment]
This issue isn't stale. Is it possible to add a label to prevent further stale markings? @stonezdj

**Comment by lusu007** [comment]
This issue isn't stale. Is it possible to add a label to prevent further stale markings? @stonezdj

**Comment by jhdxr** [comment]
It's not stale. There is no progress on this issue from the dev team yet.
