### ISSUE TITLE
Unable to sign image with notary due to colon (Windows colon is not allowed)

### ISSUE THREAD

**Issue by psandeep09** [goharbor/harbor#18847]
Signing and pushing trust metadata
error establishing connection to trust repository: mkdir C:\Users\praveen\.docker\trust\tuf\containers.xxxx.com:5000: The directory name is invalid.

unable to create folder due to colon in windows 
Do we have any workaround?

**Comment by stonezdj** [comment]
Does notary v1 support windows? could you open this issue in notary github repository?
BTW: we are going  to deprecate the notary v1 in harbor 2.9. please use consign instead.

**Comment by psandeep09** [comment]
@stonezdj is the harbor going to drop support for notary v1 and v2?

consign  is working fine, the only problem is the transparency log, client doesn't want to push logs to the public.

**Comment by wy65701436** [comment]
yes, Harbor will drop notary v1 integration since v2.9, and we suggest use to use cosign as a alternative. 

I will close this issue as we no longer provide support on notary v1, thanks.
