### ISSUE TITLE
GC Errors: column t0.subject_artifact_id does not exist

### ISSUE THREAD

**Issue by aydinseven7** [goharbor/harbor#18842]
Hello,

we are running Harbor (non-HA) via an almost default Helm install on EKS with autoscaling activated with it scaling down the node every night (at 20:00 UTC) to 0 (thus draining all pods) and then scaling up to 1 again in the morning (at 05:00 UTC). In the process Harbor keeps its pvc and pv, however after scheduling the pods on the node once again (at least that is when we noticed these errors), we get the following errors, which prevent us from doing any GC:

Logs for harbor-database-0:
[database_error.log](https://github.com/goharbor/harbor/files/11799305/database_error.log)

Logs for harbor-core:
[core_error.log](https://github.com/goharbor/harbor/files/11799304/core_error.log)

Logs for Garbage Collection run:
[GC_error.log](https://github.com/goharbor/harbor/files/11799759/GC_error.log)

I guess adding a column called subject_artifact_id would solve that, but what specifics does that have and where do I create that column? Do I have to populate that column first too or should Harbor fill it itself, if needed?
I am not sure whether a helm uninstall would even help, since the database should be stored in a pv that does not get deleted and dropping all the data and settings would not be ideal either.

**Comment by stonezdj** [comment]
What is your Harbor version? did you upgrade it from an older version?

**Comment by wy65701436** [comment]
did you modify the data base scheme manually?

**Comment by lordvader89a** [comment]
> did you modify the data base scheme manually?

No, we deployed it via the Helm chart in goharbor/harbor-helm, with everything default. It did work normally up until about 2 weeks ago.

> What is your Harbor version? did you upgrade it from an older version?
We are running Version v2.9.0-46f1fb0f, I can't remember doing an update explicitely, especially not since the values.yaml does not offer that option.

**Comment by lordvader89a** [comment]
Update: the error not only prevents Garbage Collection, but also Cosign. 
Logs for that from harbor-core:
[cosign_error.log](https://github.com/goharbor/harbor/files/11880972/cosign_error.log)


Also why autoscaling on EKS might be an issue: When we first activated it, we used the wrong template and this caused the storage shrink too much. Harbor then had too little space to allow any new artifacts to be uploaded. Could this have corrupted the database somehow?

**Comment by Vad1mo** [comment]
please check the DB according to the log errors. check also the DB schema version.

**Comment by lordvader89a** [comment]
> please check the DB according to the log errors. check also the DB schema version.

DB version is PostgreSQL 14.5, used the bitnami helm-chart for postgresql


We are resetting the Harbor instance now already anyway, hopefully that issue does not appear again.
