### ISSUE TITLE
Whether harbor can retain chartmuseum plugin

### ISSUE THREAD

**Issue by cyxinda** [goharbor/harbor#18858]
I saw that after version 2.8, harbor canceled the chartmuseum plugin  .
 It is not good to build a chartmuseum alonely. 
So I suggest  the community can retain this plugin.
the chartmuseum plugin can be used as an option,like the versions of 2.7 .
thanks.

**Comment by wy65701436** [comment]
hi, thanks for your feedback. However, Harbor already decided to move to support OCI compatible charts, and no longer have chartmuseum as a component.  You can get details from [here](https://github.com/goharbor/harbor/issues/18573#issuecomment-1519862808). And how to migrate the charts, https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor
