### ISSUE TITLE
Error in documentation about retention rules

### ISSUE THREAD

**Issue by tostt** [goharbor/harbor#18852]
The documentation about Retention Rules appears to be incorrect.

Page [Create Tag Retention Rules](https://goharbor.io/docs/2.8.0/working-with-projects/working-with-images/create-tag-retention-rules/) states at paragraph "How Tag Retention Rules Work" :
`You define tag retention rules on repositories, not on projects. This allows for greater granularity when defining your retention rules. As the name suggests, when you define a retention rule for a repository, you are identifying which tags to retain. `

It appears that is it the other way around. I also suggest removing the sentence on granularity, changing the above text with something such as;
`You define tag retention rules on projects, not repositories. As the name suggests, when you define a retention rule for a project, you are identifying which repositories and tags to retain. `

**Comment by stonezdj** [comment]
`You define tag retention rules on repositories, not on projects.` should be `The tag retention rules are defined on projects, but it applied to each repository in the project, ` the other should keep it was.
