### ISSUE TITLE
Pushes to s3 storage Minio with self signed certificate fail with 500 error even with skipverify true

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor#18868]
**Expected behavior and actual behavior:**

By configuring an s3 Minio bucket in https as an image repo we receive the following error from "registry" container when pushing an image despite the skipverify directive being active:

`caused by: Put "https://myminio.domain.com/mybucket/docker/registry/v2/repositories/mybucket/busybox/_uploads/1c5c3119-2fc7-4bd9-95b8-30f9ea8716d1/startedat": tls: failed to verify certificate: x509: certificate signed by unknown authority"`

**Values configuration for s3 Minio**

 `s3:
      # Set an existing secret for S3 accesskey and secretkey
      # keys in the secret should be REGISTRY_STORAGE_S3_ACCESSKEY and REGISTRY_STORAGE_S3_SECRETKEY for registry
      #existingSecret: ""
     
      region: minio
      bucket: mybucket
      accesskey: "minio"
      secretkey: "minio"
      regionendpoint: https://myminio.domain.com
      skipverify: true
      rootdirectory: /
`

To solve the problem we had to add the following directive in addiction to **skipverify** :

`secure: true`

even from documentation **secure: true** is the default parameter:

https://github.com/docker/docs/blob/main/registry/storage-drivers/s3.md

**Versions:**

`apiVersion: v1
appVersion: 2.8.1
description: An open source trusted cloud native registry that stores, signs, and scans content
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
keywords:
- docker
- registry
- harbor
maintainers:
- email: yinw@vmware.com
  name: Wenkai Yin
- email: hweiwei@vmware.com
  name: Weiwei He
- email: yshengwen@vmware.com
  name: Shengwen Yu
name: harbor
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
version: 1.12.1`

Do you have any suggestion?

Regards,
Gabriele

 .

**Comment by stonezdj** [comment]
Harbor 2.8.0 use the registry 2.8.0, it may not have this option yet.

**Comment by gabrilabs75** [comment]
Hi,
here you can find the file content requested:


`version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  s3:
    region: minio
    bucket: my_bucket
    regionendpoint: https://my_minio@mydomain.com:8443
    secure: true
    skipverify: true
    rootdirectory: /
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
  delete:
    enabled: true
  redirect:
    disable: true
redis:
  addr: harbor-redis:6379
  db: 2
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  pool:
    maxidle: 100
    maxactive: 500
    idletimeout: 60s
http:
  addr: :5000
  relativeurls: false
  # set via environment variable
  # secret: placeholder
  debug:
    addr: localhost:5001
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true`

I don't undestand what do you mean with:
_Is it a distribution/distribution issue?_
