### ISSUE TITLE
3.5GB image push is failing with error unauthorized: unauthorized to access repository

### ISSUE THREAD

**Issue by gouravsw** [goharbor/harbor#18860]
Harbor Version v2.5.2-66882717

As per harbor docs, Currently Harbor does not support layer above 10GB.

I am facing the intermittent issue when pushing the docker image of 3.5GB size.

After taking a huge time to upload image to harbor, it fails with the following error - 
unauthorized: unauthorized to access repository: project/repo, action: push: unauthorized to access repository: 

I have tried the provided suggestion like `docker login <harbor-registry>` and `docker logout <harbor-registry>`. But this intermittent issue persists.

Could someone help  here?

**Comment by Vad1mo** [comment]
please increase the **Token Expiration (Minutes)**  in your configuration. default is 30 min.

**Comment by gouravsw** [comment]
@Vad1mo Token Expiration in already configured to 60 mins.  But still it's failing
