### ISSUE TITLE
Replicating harbor with harbor not working

### ISSUE THREAD

**Issue by ffppmm** [goharbor/harbor#18862]
Hi,

we like harbor so we did a little testing. harbor Version v2.6.2-498e7e21.

We created 2 harbor instances, and wanted to set up a replication. Harbor1 is the source registry with an user with the following permissions:
```json
    "permissions": [
        {
            "access": [
                {
                    "action": "list",
                    "resource": "repository"
                },
                {
                    "action": "pull",
                    "resource": "repository"
                }
            ],
            "kind": "project",
            "namespace": "*"
        },
        {
            "access": [
                {
                    "action": "read",
                    "resource": "catalog"
                }
            ],
            "kind": "system",
            "namespace": "/"
        }
    ]
```
Harbor2 should replicate from Harbor1 acting as a Docker registry. Everytime we replicate we see the following error in the proxy logs:

> Jun 28 14:07:15 172.19.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /service/token?scope=registry%3Acatalog%3A%2A&service=harbor-registry HTTP/1.1" 200 963 "-" "Go-http-client/1.1" 0.014 0.013 .
> Jun 28 14:07:15 172.19.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /v2/_catalog?n=1000 HTTP/1.1" 401 108 "-" "harbor-registry-client" 0.001 0.001 .

401 Unauthorized 😞 

We want to give every customer the possibility to replicate from our registry, so we choose "docker registry" for the source registry (Harbor1), we don't know what registry or replications our customers are using, so that's the reason for the "generic one", everybody can talk to, except harbor itself. 

Can you tell us the correct permissions so this will work?

Maybe everything is fine if we just update to 2.8?

Of course we could tell every customer to use harbor (harbor registry works as Source Harbor1) 😉 but that's not a solution for us,
Regards Philipp

**Comment by chlins** [comment]
Could you also provide the replication rule? If you used the wildcards in the name pattern, harbor needs to list all the repositories for the filtering, as the catalog API only opened for system admin, so you got the 401 unauthorized error returned.

**Comment by ffppmm** [comment]
Hi,

thanks for your answer. We have tried the following replication rules:

- PROJECTNAME/**
- PROJECTNAME/*
- {PROJECTNAME1,PROJECTNAME2}/**
- {PROJECTNAME1,PROJECTNAME2}/*
- /PROJECTNAME/**
- /PROJECTNAME/*
- /{PROJECTNAME1,PROJECTNAME2}/**
- /{PROJECTNAME1,PROJECTNAME2}/*

We just want to avoid the /v2/_catalog call from Harbor1 to Harbor2. The Robot has list repository permissions. How can we just list the repository somehow?

Is there a plan to implement the functionality getting /v2/_catalog "projects" based on the rights of a robot account?

Regards Philipp

**Comment by chlins** [comment]
Currently, no plan for implementing the permission of /v2/_catalog for robot account, but we can mark this issue to requirement if you want. I think the workaround is using admin account or using the complete repository name instead of contains `*` which like `library/nginx`, so that harbor will not call /v2/_catalog in this case.

**Comment by ffppmm** [comment]
Hi,
ok understood. Giving every Customer an admin account, is not possible. Complete repository name also not possible, because we have nearly 50 repositories that would lead to 50 replication rules, and still growing.

So If there is no other solution, I would kindly ask you to mark this as an requirement.

Regards Philipp

**Comment by YangJiao0817** [comment]
@ffppmm  Your payload is wrong, bot accounts cannot be system and project level, what level of bot account do you want?

your payload:
```
    "permissions": [
        {
            "access": [
                {
                    "action": "list",
                    "resource": "repository"
                },
                {
                    "action": "pull",
                    "resource": "repository"
                }
            ],
            "kind": "project",
            "namespace": "*"
        },
        {
            "access": [
                {
                    "action": "read",
                    "resource": "catalog"
                }
            ],
            "kind": "system",
            "namespace": "/"
        }
    ]
```

**Comment by ffppmm** [comment]
Hi,
maybe I should describe in more detail what we try to a achieve.

- we want to provide robot accounts, 1 (maybe we need 2) per customer, to replicate our harbor repository with any other registry (docker, harbor, jfrog, ...)
- we need replication as a docker repository
- we **don't** want a public registry
- the robot account should, beside replication, be able to pull artifacts from our registry
- the robot account may not be sysadmin because only pulling artifacts should be possible and nothing else

The system part payload was just a guess because I didn't find a fine grained doc for the needed rights, maybe I missed something, sorry.

Any help is ofc appreciated,
regard Philipp

**Comment by ffppmm** [comment]
Hi,
OK, and this account will be able to read the /v2/_catalog ? Because this is the Main Problem we are facing if we replicate with the above replication rules.

> PROJECTNAME/*
> {PROJECTNAME1,PROJECTNAME2}/*

Regards Philipp

**Comment by YangJiao0817** [comment]
You can refer to this [comment](https://github.com/goharbor/harbor/issues/16159#issuecomment-1301705809) to add /v2/_catalog permissions to your robot account.

**Comment by ffppmm** [comment]
Hi,

thanks for your help, I will give it a try a little bit later and send you feedback,

Regards Philipp

**Comment by ffppmm** [comment]
Hello,
but I can't use 2 Users for replication. I need a robot with permissions that can replicate Harbor1 (Harbor1 acting as Docker registry) <= Harbor2 . 

We don't know what registry our customers use. The Issue persists if you use wildcards :( pls help

Regards Philipp

**Comment by YangJiao0817** [comment]
You can add all the permissions you need to your robot account by calling the API.
API you can refer to the API center page in Harbor

**Comment by ffppmm** [comment]
Hi,

so the correct permissions would be:
```
    "permissions": [
        {
            "access": [
                {
                    "action": "list",
                    "resource": "repository"
                },
                {
                    "action": "pull",
                    "resource": "repository"
                },
                {
                    "action": "read",
                    "resource": "artifact"
                },
                {
                    "action": "list",
                    "resource": "artifact"
                },
                {
                    "action": "list",
                    "resource": "tag"
                }
            ],
            "kind": "project",
            "namespace": "*"
        },
        {
            "kind": "system",
            "namespace": "/",
            "access": [
                {
                    "resource": "catalog",
                    "action": "read"
                }
            ]
        }
    ]
```
Regards Philipp

**Comment by YangJiao0817** [comment]
```
{
  "creation_time": "2023-07-07T09:40:23.863Z",
  "disable": false,
  "duration": 30,
  "editable": true,
  "expires_at": 1691314823,
  "id": 5,
  "level": "system",
  "name": "robot$sys",
  "permissions": [
    {
      "access": [
        {
          "action": "list",
          "resource": "repository"
        },
        {
          "action": "pull",
          "resource": "repository"
        },
        {
          "action": "read",
          "resource": "artifact"
        },
        {
          "action": "list",
          "resource": "artifact"
        },
        {
          "action": "list",
          "resource": "tag"
        },
        {
          "action": "read",
          "resource": "catalog"
        }
      ],
      "kind": "project",
      "namespace": "*"
    }
  ],
  "update_time": "2023-07-07T09:42:55.288Z"
}
```

**Comment by ffppmm** [comment]
Hi,

I was on holiday, sry for the late answer. We testet with the above permissions and I still get "401 Unauthorized", so listing the _catalog still doesn't work 😞 

Command:
```bash
cat harbor.txt | curl -k -K - --request GET  --url "https://registry_fqdn/api/v2.0/robots/11"  | python -m json.tool
```
Output:
```json

{
    "creation_time": "2023-06-13T07:13:56.812Z",
    "description": "System Robot Account for Tests",
    "disable": false,
    "duration": -1,
    "editable": true,
    "expires_at": -1,
    "id": 11,
    "level": "system",
    "name": "somename_modified",
    "permissions": [
        {
            "access": [
                {
                    "action": "list",
                    "resource": "repository"
                },
                {
                    "action": "pull",
                    "resource": "repository"
                },
                {
                    "action": "read",
                    "resource": "artifact"
                },
                {
                    "action": "list",
                    "resource": "artifact"
                },
                {
                    "action": "list",
                    "resource": "tag"
                },
                {
                    "action": "read",
                    "resource": "catalog"
                }
            ],
            "kind": "project",
            "namespace": "*"
        }
    ],
    "update_time": "2023-07-08T08:39:46.200Z"
}
```

proxy logs (only replaced IPs):
```
Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /v2/ HTTP/1.1" 401 76 "-" "Go-http-client/1.1" 0.002 0.001 .
Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /service/token?scope=registry%3Acatalog%3A%2A&service=harbor-registry HTTP/1.1" 200 967 "-" "Go-http-client/1.1" 0.016 0.017 .
Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /v2/_catalog?n=1000 HTTP/1.1" 401 108 "-" "harbor-registry-client" 0.003 0.003 .
Jul 28 09:08:42 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /api/version HTTP/1.1" 200 19 "-" "Go-http-client/1.1" 0.004 0.003 .
```

Can you help,
regards Philipp
