### ISSUE TITLE
Harbour Web UI does not remember the selected page size

### ISSUE THREAD

**Issue by eero-t** [goharbor/harbor#18877]
Harbor UI defaults to ridiculously small 15 item page size, and if one changes it to more reasonable 50 items, it will immediately forget the setting and reset back to measly 15 items if one does *anything* with the UI.

This is exacerbated by Harbour not allowing opening of e.g. repo links to other Browser tabs, so that one could have reasonable sized repo listing in one tab, and open their image lists to further tabs.

Having option for the default page size would also help, as would there being **much** larger page sizes (e.g. 200 items).

PS. If it was unclear, this issue makes the Web UI **really** annoying to use.

**Comment by eero-t** [comment]
This is with a bit older Harbour versions `v2.2.1-b0d63082`, and `v2.5.5-b09a690e`, but I haven't see any mention of this being fixed in the issues, discussion or release notes for the later versions.

**Comment by AllForNothing** [comment]
@eero-t 
For page size selection, we have added it to Harbor in v2.6, see #16030

And for allowing opening of e.g. repo links to other Browser tabs， see #15893

**Comment by eero-t** [comment]
@AllForNothing Wow, great, thanks!   I'll ask our v2.2 Harbour install to be updated immediately...

Btw. While right click support went to 2.5, and does work in Projects & Repos views (which are more important), it does not seem to be working in artifacts view.  Was that fixed in a later release?

**Comment by AllForNothing** [comment]
`it does not seem to be working in artifacts view. Was that fixed in a later release?`

For artifacts list, currently not supported as it has extra logic(it means it 's more than a hyperlink). We may consider improving this in the future. Of cause, you can open a new issue as a feature request if you want

**Comment by eero-t** [comment]
With these other things fixed, artifact view is not really a problem.  Thanks!
