### ISSUE TITLE
building harbor V2.1.3 sourceCode for offlinepackage  failed ，need help !!!!!

### ISSUE THREAD

**Issue by blacby** [goharbor/harbor#18889]
when i building code  harbor:v2.1.3 and run  :   make build -e DEVFLAG=false COMPILETAG=compile_golangimage VERSIONTAG=v2.1.3 is going wrong.

problem here:
1. my network is healthy (i can ping the host storage.gooleapi....   and i can curl  https://storage.googleapis.com)
2. when i try to view "https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.7.1-patch-2819-2553-redis/registry" seems like binary file about harbor-registry is disappeared.
![image](https://github.com/goharbor/harbor/assets/46959712/63044981-3af6-4c53-aff4-66c4805cf3b6)

**Comment by blacby** [comment]
when i try to view "https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.7.1-patch-2819-2553-redis/registry" on my **Google browse**r  seems like binary file about harbor-registry is disappeared.

**Comment by blacby** [comment]
when i try to view "https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.7.1-patch-2819-2553-redis/registry" on my **Google browse**r  seems like binary file about harbor-registry is disappeared.

**Comment by iced-duck** [comment]
You can use "make build  BUILDBIN=true" command to build the registry binary.

**Comment by blacby** [comment]
> You can use "make build BUILDBIN=true" command to build the registry binary.

thanks， i will try it

**Comment by blacby** [comment]
@iced-duck it works ，thank you man ！
