### ISSUE TITLE
Pull command failed with unauthorized error

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor#18895]
Hi all,
performing a pull of an image previously brought to a _**private**_  project via a push I encounter the following problem:

`
ERRO[2023-07-05T11:23:44.212764900+02:00] Handler for POST /v1.41/images/create returned error: unauthorized: unauthorized to access repository: myrepo/myimage, action: pull
`

If I change the repo definition from **_private_** to **_public_** the pull request works correctly,

Here you can find the Chart and app version:

`The procedure of docker login on my Harbor registry works correctly
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
harbor  my-namespace      11           2023-06-29 16:06:22.4901469 +0200 CEST     deployed        harbor-1.12.1         2.8.1
`

Also the procedure of docker login on my Harbor registry works correctly, so I don't understand what I'm doing wrong.
Any suggestion?

Regards,
Gabriele

**Comment by MinerYang** [comment]
Please see https://goharbor.io/docs/2.8.0/administration/managing-users/
for private project, only users who are members of the project can pull images

**Comment by gabrilabs75** [comment]
Hi,
the user that I tested for the pull request is member of the project but the pull requests still fails.

**Comment by zyyw** [comment]
Hi @gabrilabs75 , this log
```
ERRO[2023-07-05T11:23:44.212764900+02:00] Handler for POST /v1.41/images/create returned error: unauthorized: unauthorized to access repository: myrepo/myimage, action: pull
```
looks odd to me. If it's a `docker pull` (I'm assuming you are using docker CLI to pull/push images from/to Harbor registry), there shouldn't be any `POST` of that request.

Would you mind creating a new user under `Administration > Users` and add this new user to the project as a **project member**? Then `docker logout YOUR_HARBOR_ENDPOINT` && `docker login YOUR_HARBOR_ENDPOINT` with the new user and it's password. Then retry `docker pull` against the repository of the project where the new user is a member of.

**Comment by gabrilabs75** [comment]
Hi @zyyw, 

I've just created a new user member of the project where I previously pushed an image.
The result is the same:

`$ docker pull myregistry.mydomain.com/user2/busybox:latest
Error response from daemon: unauthorized: unauthorized to access repository: user2/busybox, action: pull: unauthorized to access repository: user2/busybox, action: pull`

It seems very strange cause the push action works without error (on my **private** project).

Have you further suggestion?
Regards,
Gabriele

**Comment by gabrilabs75** [comment]
Hi guys,
any news about this case?

Regards,
Gabriele

**Comment by LiuShuaiyi** [comment]
Any logs from harbor-core pods related to this error?
