### ISSUE TITLE
GC is not actually removing artifacts from S3 Minio storage

### ISSUE THREAD

**Issue by rbreekveldt** [goharbor/harbor#18896]
We noticed that even when Harbor Garbage Collection runs successfully and show blobs and manifests and actual freed up space. The artifacts will still remain present in Minio and no space is freed up at all. 

Any idea on what might go wrong? We have no versioning or object-locking enabled on the registry bucket in Minio.

**Comment by MinerYang** [comment]
You might refer to this issue https://github.com/goharbor/harbor/issues/17251 and rollout is that a s3 bucket problem?

**Comment by zyyw** [comment]
@rbreekveldt would you please share with us which Harbor version you are using? Thanks

**Comment by rbreekveldt** [comment]
I was also able to reproduce this issue locally in a Kind cluster. It seems that manifests do actually get deleted but not the blob artifacts storage.

**Comment by bellomimarc** [comment]
I notifce the same issue on Harbor and storage filesystem.

**Step to reproduce**
1. Upload blobs with /v2/<name>/blobs/upload APIs
2. Avoid calling the PUT /v2/<name>/manifests/<reference>
3. Check in the project quota that some quota was consumed
4. Run GC
5. Check in the project quota that some quota was released
6. In the registry pod, I went to /storage/docker/registry/v2/blobs/sha256 and I'll find the blob previously loaded.
NB: each time I execute this test I create a new blob

**Software versions:**
Minikube: v1.30.1
K8s: v1.26.3
Chart from: https://helm.goharbor.io, v1.12.1
Harbor: v.2.8.1

**Comment by rbreekveldt** [comment]
Not stale issue is still present and even hit by other users. If there is any additional info you need, please let me know.

**Comment by boers001** [comment]
Please give this issue the proper attention

**Comment by rbreekveldt** [comment]
We've upgraded Harbor to version 2.9.0 and are not able to replicate the issue.

**Comment by 4volodin** [comment]
I confirm the problem exists in 2.9.1 (yandex s3) and in 2.9.1 garbage collection doesn't see deleted images (in 2.7.3 GC have seen deleted images)

**Comment by 4volodin** [comment]
I am deleting artifact image and then trying to DRY RUN in garbage collector and I am getting "0 blob(s) and 0 manifest(s) could be deleted, 0 space could be freed up"
