### ISSUE TITLE
Can I transfer my robot account to another harbor in Harbor v2.0.0

### ISSUE THREAD

**Issue by Louse-luo** [goharbor/harbor#18899]
Can I transfer my robot account to another harbor in Harbor v2.0.0

**Comment by zyyw** [comment]
Hi @Louse-luo, what do you mean by transfer your robot account to another Harbor?
Do you mean you create a robot account on Harbor instance 1, and want to somehow use the robot account credentials on Harbor instance 2?
In that case, may I know the reason that prevent you from creating a new robot account on Harbor instance 2?

**Comment by zyyw** [comment]
You may create a robot account with the same username and password.
