### ISSUE TITLE
Unable to login or sign up in demo.goharbor.io

### ISSUE THREAD

**Issue by ovelindstrom** [goharbor/harbor#18891]
Hi,

Currently, there is no way to login with created accounts in the demo environment (could be expected if there has been a cleanup) but there also is no signup link/button on the current demo (v2.8.0-89ef156d).

KR,

Ove

**Comment by MinerYang** [comment]
demo.goharbor.io will be refresh installed every two days. I could access demo.goharbor.io successfully. Please have another try

**Comment by zyyw** [comment]
@ovelindstrom, I can login demo.goharbor.io as well. Please give it a second try.

**Comment by ovelindstrom** [comment]
Yes, now it is back to normal. Sign-up and login possible again.
