### ISSUE TITLE
The core component will import some table data to pgsql during initialization. If there is an exception in the middle, the service will not be restored.

### ISSUE THREAD

**Issue by zzzyuan0** [goharbor/harbor#18901]
harbor vsersion： 2.6.4
By viewing the relevant code of core import table data，I found that if there is an exception in the middle, the version in the `schema_migrations`  table will be greater than 0 but may be less than `schemaVersionV1_10_0`, At this time, the error 'please upgrade to version 1.10 first' will always be reported
And I found that there is no judgment in the statement to create the table
```
create table access (
 access_id SERIAL PRIMARY KEY NOT NULL,
 access_code char(1),
 comment varchar (30)
);
```
It may report an error when reimporting the table with an exception

**Comment by zyyw** [comment]
Are you trying to upgrade from 1.10.x to 2.6.4? If so, then this upgrade path is not allowed. You can upgrade from 1.10.x to 2.0.0 and then upgrade every 2 minor version, such as to 2.2.0, then 2.4.0 then 2.6.0

**Comment by zzzyuan0** [comment]
I did not perform the upgrade operation. What I mean is that your table import code does not have a reentrant strategy. If a component fails during the table import process, it will never be recovered.
