### ISSUE TITLE
ailed to check the existence of the manifest of artifact on the destination registry: http status code: 401, 

### ISSUE THREAD

**Issue by ugurmendi** [goharbor/harbor#18910]
I am trying push base replication between two harbor instances (one in stand alone other is in rke2 cluster),There was an error occured during the process ailed to check the existence of the manifest of artifact on the destination registry: http status code: 401.
I can  docker login and push image via cli both my local and between server but when I try  to replicate I face with that error.

**Comment by Duanzhiwei** [comment]
Has the problem been solved? I encountered the same problem

**Comment by ugurmendi** [comment]
> Has the problem been solved? I encountered the same problem

hello Duanzhiwei I managed the solve the I had problem with the labels during the replication I put everywhere as star because of that it cannot communicate between two replicas.
