### ISSUE TITLE
K8S can't pull image from harbor

### ISSUE THREAD

**Issue by dhcn** [goharbor/harbor#18926]
After I add docker-registry  secret for k8s, k8s still can't pull image from harbor

**Comment by MinerYang** [comment]
it is really depends on your Kubernetes cluster variations, such as the runtime type and the way to load images to nodes.
Not a related to harbor

**Comment by dhcn** [comment]
> it is really depends on your Kubernetes cluster variations, such as the runtime type and the way to load images to nodes. Not related to harbor

Many Thanks

**Comment by dhcn** [comment]
> 

Node1 seems to have no Docker

**Comment by dhcn** [comment]
> it is really depends on your Kubernetes cluster variations, such as the runtime type and the way to load images to nodes. Not related to harbor

Node1 seems to have no Docker
