### ISSUE TITLE
YAML serialisation issue

### ISSUE THREAD

**Issue by balnbibarbi** [goharbor/harbor#18938]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behaviour: the passwords that the user specifies when deploying Harbor from an OVA should be used.

Actual behaviour: the firstboot.sh script shipped with the official Harbor OVA generates a YAML configuration file for Harbor that contains an incorrect value for the password. The value is wrong in two different ways: 1. It is HTML entity escaped, which it should not be in a YAML file, and it is not quoted, which arbitrary user-configurable strings in YAML files must be, in case they contain characters that are special to YAML.

If the user's chosen passwords contains a YAML special character, firstboot.sh generates an invalid YAML file, so Harbor initialisation fails.

If the user's chosen password contains no YAML special characters but does contain an HTML special character such as an ampersand, less than or greater than, the password value generated in the YAML is the HTML entity-escaped version of the password. So Harbor uses a password other than the password that the user specified.

If the user's chosen password contains no characters that are special to either YAML or HTML, installation and configuration succeed.

**Steps to reproduce the problem:**

1. Follow VMware's documentation to deploy Harbor from an OVA.
When promoted to choose a password, enter a password that contains an HTML or a YAML special character or both.
2. Observe one of the outcomes specified above, depending on password value chosen.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by zyyw** [comment]
Harbor OVA issue is out of the scope of Harbor OSS community project. closing it now.
