### ISSUE TITLE
Harbor api 404 not found

### ISSUE THREAD

**Issue by EldinEgrlic** [goharbor/harbor#18935]
Hello,

when I try to access Harbor API using https://<harbor_ip>/devcenter I get 404 Not found. Harbor UI works fine, but this /devcenter is not accessible. What could be the reason? Thanks

**Comment by Vad1mo** [comment]
It should work in the normal setup.

Some more info would be helpful to track down the problem. 

What version are your running? 
What is your setup Helm/compose/installer?

how does you config look like? ingress or nginx setup?

**Comment by zyyw** [comment]
@EldinEgrlic would you mind sharing with us your harbor version? For Harbor v2.8.2, it is `https://<harbor_ip>/devcenter-api-2.0`

**Comment by wy65701436** [comment]
what's the harbor version and how did you deploy it?

**Comment by EldinEgrlic** [comment]
@zyyw  @wy65701436 
Version is v2.7.1 and it is deployed as an image on a kubernetes cluster (not through helm)

**Comment by RyanW8** [comment]
We're also seeing this. We've upgraded from Harbor v2.4.0 to v2.8.0. Installed using Helm (although it's a custom chart not the official one). From what I can see the requests are correctly being routed to the Portal component but we're still presented with a 404 in the UI. 

Even when port forwarding to the portal service and trying to access `/devcenter-api-2.0` URI it still returns a 404

**Comment by EldinEgrlic** [comment]
@RyanW8 

I used actually this version:  https://artifacthub.io/packages/helm/bitnami/harbor/16.4.0

Solution - swagger UI is located at:
http://<harbor-ip>/swagger-ui-index.html


Not /devcenter or other URLs. Itis ridiculous that it is not documented anywhere.

**Comment by RyanW8** [comment]
> swagger-ui-index.html

Yeah that works for us but the Portal redirects `/devcenter-api-2.0` to /swagger-ui-index.html` so it should work regardless. https://github.com/goharbor/harbor-helm/blob/master/templates/portal/configmap.yaml#L57

**Comment by EldinEgrlic** [comment]
In my case redirect doesn't happen...why or how.. no idea, not worth debugging it since this way is OK for us at the moment. Thanks for the better insight  @RyanW8

**Comment by AllForNothing** [comment]
since 2.7, swagger UI was separated from Harbor UI by https://github.com/goharbor/harbor/pull/17428.
So a new location was added to the nginx config of the Habor Portal container.
Please check the nginx.conf of the Portal container.
I suspect that these helm repo forgot to synchronize the changes of nginx.conf

**Comment by EldinEgrlic** [comment]
@AllForNothing  that makes sense, thanks for the information
