### ISSUE TITLE
Can Harbor upload findings from image scans to AWS Security Hub?

### ISSUE THREAD

**Issue by jrbeilke** [goharbor/harbor#18945]
How can we help you?
Tried to search through the docs and other GH issues, but I'm not having any luck (except for a new Harbor UI feature named `securityhub` which seems unrelated).

Is it possible to have Harbor upload findings from image scans to AWS Security Hub?

I know this is possible with Trivy ie.
https://aquasecurity.github.io/trivy/v0.43/tutorials/integrations/aws-security-hub/

But I'm not seeing anything in Harbor to support this

**Comment by zyyw** [comment]
Can you have a try on this 
```
$ AWS_REGION=us-west-1 AWS_ACCOUNT_ID=123456789012 trivy image --format template --template "@contrib/asff.tpl" -o report.asff <harbor-ip>/library/golang:1.12-alpine
```
Currently, we have no plan for this.
