### ISSUE TITLE
API: Cannot find robot by exact name match

### ISSUE THREAD

**Issue by victor-tsykanov** [goharbor/harbor#18940]
There is project-level robot with name "access-registry+test". When I'm trying to find it with API request by specifying query with exact name match, it returns no result. URL looks like this: /api/v2.0/projects/registry/robots?page=1&page_size=15&q=name%3Daccess-registry%2Btest
Harbor version: 2.6.2-498e7e21.

**Comment by YangJiao0817** [comment]
@victor-tsykanov How do you create a robot  named `access-registry+test`? Harbor does not allow `+` in robot names.

**Comment by victor-tsykanov** [comment]
I've created it from UI. I only set  "test" as name, the rest is added by Harbor: "registry" is project name and "access-" is robot name prefix form Configuration / System settings.
![image](https://github.com/goharbor/harbor/assets/2721308/88f47b5f-1a53-4b1b-9c93-e1b56077fac2)
![image](https://github.com/goharbor/harbor/assets/2721308/bcd62682-2a26-4ea5-a98e-3acff47ca06f)

**Comment by YangJiao0817** [comment]
Search by name(without prefix).
<img width="1416" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/5352862b-a305-47a3-938c-15e9610735f7">

<img width="1399" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/c1af307e-b0f2-4cba-8cbc-42bdfc7044e1">

<img width="1392" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/db7f5c3c-06c5-4c71-abb1-594fd48be353">
