### ISSUE TITLE
Docker Login error to Harbor

### ISSUE THREAD

**Issue by jacobpoly73** [goharbor/harbor#18958]
I have a Harbor Instance which has OIDC enabled. I can log into the harbor portal just fine. But when I try to do a docker login from a prompt I get the below error. 

docker login https://myharborurl -u 'myname@mycompany.com'
password: 
_Error response from daemon: Get "https://myharborurl/v2/": unauthorized: authentication required_ 

When I go through core,log I see these messages

Jul 19 16:42:41 xxxxxxxx core[2104879]: 2023-07-19T16:42:41Z [ERROR] [/server/middleware/security/oidc_cli.go:62][requestID="1fc3f9c5-b2e3-4e0c-9c31-a6bee346b741"]: failed to verify secret, username: 'myname@mycompany.com', **error: failed to get oidc user info, error: <QuerySeter> no row found**
Jul 19 16:42:41 xxxxxxxx core[2104879]: 2023-07-19T16:42:41Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="10.91.17.18" requestID="1fc3f9c5-b2e3-4e0c-9c31-a6bee346b741" user agent="docker/24.0.2 go/go1.20.4 git-commit/659604f kernel/5.10.102.1-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.2 \(windows\))"]: **failed to authenticate user:'myname@mycompany.com', error:not supported**

Any idea what is off?

**Comment by MinerYang** [comment]
please kindly refer to this [issue](https://github.com/goharbor/harbor/issues/18772)
