### ISSUE TITLE
docker pull without <harbor_address> does not work

### ISSUE THREAD

**Issue by yfPanne** [goharbor/harbor#18967]
Hi there:

Firstly,  i have logined to my harbor use ``` docker login ```,
and i can pull image using cmd like this:
```
docker pull <harbor_address>/library/admin-api:0.1.20
```
but it not work when i remove ```<harbor_address>```
```
docker pull library/admin-api:0.1.20
```
the error shows:
```
Error response from daemon: pull access denied for library/admin-api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

And also, i have set the harbor address in ```/et/docker/daemon.json``` like this:
```
{
        "registry-mirrors":["https://myharbor.app"],
        "mtu": 1450
}
```
My harbor version is ```v2.8.2```
docker version:
```
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:55 2023
 OS/Arch:           linux/amd64
 Context:           default
``` 
---
In my case, i need the image-path without repository address in my docker compose file.
Does someone can help?

**Comment by MinerYang** [comment]
The first time you request an image from your local registry mirror, it pulls the image from the public Docker registry and stores it locally before handing it back to you. On subsequent requests, the local registry mirror is able to serve the image from its own storage.

**Comment by yfPanne** [comment]
> The first time you request an image from your local registry mirror, it pulls the image from the public Docker registry and stores it locally before handing it back to you. On subsequent requests, the local registry mirror is able to serve the image from its own storage.

**Thanks for reply. But it is a different scenarios. The image i am using is private.**

---
I see some logs from docker daemon:(when i use ```docker pull gallics/gallics-server/admin-api:0.1.31```)
```
level=debug msg="Calling HEAD /_ping"
level=debug msg="Calling POST /v1.43/images/create?fromImage=gallics%2Fgallics-server%2Fadmin-api&tag=0.1.31"
level=debug msg="hostDir: /etc/docker/certs.d/harbor.gallics.app"
level=debug msg="Trying to pull gallics/gallics-server/admin-api from https://harbor.gallics.app/"
level=info msg="Attempting next endpoint for pull after error: unauthorized: unauthorized to access repository: gallics/gallics-…api, action: pull"
```
(my real repository address shows  here)
log is different from when i use ```docker pull harbor.gallics.app/gallics/gallics-server/admin-api:0.1.31```:
```
level=debug msg="Calling HEAD /_ping"
level=debug msg="Calling POST /v1.43/images/create?fromImage=harbor.gallics.app%2Fgallics%2Fgallics-server%2Fadmin-api&tag=0.1.31"
level=debug msg="hostDir: /etc/docker/certs.d/harbor.gallics.app"
level=debug msg="Trying to pull harbor.gallics.app/gallics/gallics-server/admin-api from https://harbor.gallics.app"
```
The focus is on the fourth line, it shows the different, and it above proves that both command point to the correct repository address
For now, i remember the command to push the image to the repository:
```docker push harbor.gallics.app/gallics/gallics-server/admin-api:0.1.31```
It is also with the address as prefix, and the prefix is must needed for using ```docker push``` to push image to my own repository.

**So, i am considering if that means the address prefix is a must for harbor when pull image from harbor, because harbor can not recognize the image without address prefix?**

**Comment by staerion** [comment]
We are also looking for a solid way to use harbor as a transparent mirror-registry without the need to add the harbor url and project in the image name. I've seen some solutions using nginx as a proxy in between harbor and the docker client, but I'd much rather avoid going that route.
