### ISSUE TITLE
Harbor replicating harbor-core cause  bearer token is not valid yet error  in helm installation

### ISSUE THREAD

**Issue by ugurmendi** [goharbor/harbor#18971]
Hello when we deploy harbor registry with helm , we set  the replica number to two,after that in another harbor instance (outside of the kubernetes cluster,) we try push base replication the error is 401 unauthorized access,and remote  harbor registry state became unhealty after when we examined both harbor-core pods one of them is working fine in other pod the error occured "bearer token is not valid yet"

**Comment by MinerYang** [comment]
https://github.com/goharbor/harbor/issues/18880

**Comment by ugurmendi** [comment]
Yes same isssue with that ticket  id   for values.yaml I only changes the areas which ares shown blow:
certSource: secret
ingress:
    hosts: "foo"
      core: "foo"
      notary: "foo.bar.notary"
externalURL: "https://foo"
core:
  image:
    repository: goharbor/harbor-core
    tag: v2.8.2
  # set the service account to be used, default if left empty
  serviceAccountName: ""
  # mount the service account token
  automountServiceAccountToken: false
  replicas: 2  when I sett the replicas to two error starting to occured in core 
  revisionHistoryLimit: 10
  ## Startup probe values
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
-------------------------------------------
These are my pods 
![Screenshot from 2023-07-24 11-24-00](https://github.com/goharbor/harbor/assets/57142531/8078b940-a9d3-4fae-af77-7b2ddc4635af)
-------------------------------------------
harbor-param-core-5fb6788d94-2h2lk error which causing the situation 
23/07/24 08:20:25.740 [I] [server.go:281]  http server Running on http://:8080
2023-07-24T08:22:06Z [INFO] [/controller/registry/controller.go:222]: Start regular health check for registries with interval 5m0s
2023-07-24T08:22:12Z [ERROR] [/pkg/token/token.go:68]: parse token error, token is not valid yet
2023-07-24T08:22:12Z [WARNING] [/server/middleware/security/v2_token.go:53][requestID="090875cdcc40c534cf970459b8173d45"]: failed to decode bearer token: token is not valid yet
--------------------------------------------------------------------------
harbor-param-core-5fb6788d94-2zgpb other core pod logs:
2023/07/24 08:20:20.630 [I] [server.go:281]  http server Running on http://:8080
2023-07-24T08:20:33Z [INFO] [/controller/registry/controller.go:222]: Start regular health check for registries with interval 5m0s
----
For other harbor it is working just fine  there is no problem in both harbor instance unless I set the replica count to 2 for harbor-core

**Comment by ugurmendi** [comment]
up

**Comment by shapirus** [comment]
FWIW, I'm no longer seeing this issue after changing from a harbor-operator managed instance of harbor v2.5.4 to harbor v2.9.0 deployed via the helm chart. Can now run more than one replica of harbor-core without getting authentication errors.

**Comment by shapirus** [comment]
duplicate of #18971 btw.

**Comment by shapirus** [comment]
duplicate of https://github.com/goharbor/harbor/issues/18880 btw.
