### ISSUE TITLE
GAR Replication 

### ISSUE THREAD

**Issue by srveerla** [goharbor/harbor#18981]
How can we help you?

we are looking for GAR replication (Push and Pull) over Harbor, used with GCR and connection was successful, however replication doesnot happen, no image to replicate is what it says.

Thanks,
SRV

**Comment by MinerYang** [comment]
Please provide your replication policy

**Comment by srveerla** [comment]
Endpoint URL configured in Registry: https://us-docker.pkg.dev (this is on us-central)
Harbor replication rule: ${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/**

**Comment by srveerla** [comment]
Any help would be appreciated, we are getting the error "no resources needs to be replicated"

**Comment by norman-zon** [comment]
I read #16973 carefully and got push-replication working.
But pull-replication still "succeeds" with `no resources needs to be replicated`.

My setup looks like this:

<img width="613" alt="image" src="https://github.com/goharbor/harbor/assets/85173861/a3415a0d-bd2a-415e-a428-2adfdb3366d4">

<img width="1622" alt="image" src="https://github.com/goharbor/harbor/assets/85173861/1603092c-2713-4def-9e8f-50e38f15cb78">

<img width="1573" alt="image" src="https://github.com/goharbor/harbor/assets/85173861/7c7047d1-3e44-474b-afdc-28fa7770e3fd">

I would expect it to check if there are any images in `<GOOGLE_PROJECT>/<REPO>` that are missing in my local `gar` project and download them. But that's what i get:

<img width="579" alt="image" src="https://github.com/goharbor/harbor/assets/85173861/c84f22ea-d5f8-464b-b474-2bac2de60dc6">

**Comment by norman-zon** [comment]
Turns out it works when specifying the whole image path as resource filter. For example:

`<GOOGLE_PROJECT>/<REPO>/<MY_IMAGE>`. Naturally this only replicates this single image.
So my guess is something with listing the remote images when using wildcard is the issue?

**Comment by mrbuk** [comment]
@norman-zon it should work with `${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/**` or even with _blank_ or `**`.

If it does not work for you I have a suspicion: you are using a dedicated service account with only Artifact Registry permissions (e.g. Reader / Writer) but you are missing the **resourcemanager.projects.get** permission. Typically this permission is something that basic roles like `Viewer` have.

The way to validate my suspicion is to use the following command to validate that the `/v2/_catalog` returns something.

```
export JSON_KEY_B64=$(base64 < my-secret-key.json)
curl -u _json_key_base64:$JSON_KEY_B64 https://europe-west3-docker.pkg.dev/v2/_catalog
```

So if the command returns: `{"repositories":[]}` although you have repositories you are most likely missing the **resourcemanager.projects.get** permission. It is unfortunate that the API returns in that case a 200 OK but this might be in spec/desired behaviour.

If adding the **resourcemanager.projects.get** permission solves it for you as well let me know I will raise an issue with the Artifact Registry team to document this.

**Comment by norman-zon** [comment]
Thanks @mrbuk!
Indeed giving the SA **resourcemanager.projects.get** permission fixed it.

Interesting that the API returns 200 in case the SA has no permission to actually list anything.

**Comment by srveerla** [comment]
worked like a Charm....thanks @mrbuk

**Comment by srveerla** [comment]
Closing this as issue is resolved.

**Comment by norman-zon** [comment]
@srveerla which IAM role did you end up using?

**Comment by schedin** [comment]
Thanks for the hint about using the `resourcemanager.projects.get` permission to be able to use wildcards in Harbor replication rule for Google Artifact Registry! Since I wanted minimal permission needed on my service account, I created a custom role for the permission and then assigned it to my service account:

```
gcloud iam roles create ProjectMetadataGetter \
  --project=XXXXXXXXXXXX-cf3f4d7 \
  --title="Project Metadata Getter" \
  --description="Custom role with resourcemanager.projects.get permission. Used to list meta data of a project." \
  --permissions="resourcemanager.projects.get" \
  --stage="GA"
  
gcloud projects add-iam-policy-binding XXXXXXXXXXXX-cf3f4d7 \
  --member="serviceAccount:YYYYYYYYY@XXXXXXXXXXXX-cf3f4d7.iam.gserviceaccount.com" \
  --role="projects/XXXXXXXXXXXX-cf3f4d7/roles/ProjectMetadataGetter"
```
