### ISSUE TITLE
Deleting replications results in a timeout

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#18988]
### Discussed in https://github.com/goharbor/harbor/discussions/18969

<div type='discussions-op-text'>

<sup>Originally posted by **niklasweimann** July 21, 2023</sup>
Hey 👋 
i want to remove several replications which we used to push images to docker hub for about an year. So the Replication got executed quite often. When i try to delete the replication i always got a timeout for the request so i updated the ingress with in Timeout of 3600s which is fine, but the delete request still never succeeded.

Next i checked the code and found out that the request first looks up all executions for this policy than all tasks for the execution and fails as soon as any of the executions is not in a final state. But i checked this condition in the database and all executions where in a final state. So i counted the executions and there were about 50k tasks that should be deleted.
``` SQL
select count(*) from execution e left join task t on e.id = t.execution_id where e.vendor_id = 14 and e.vendor_type = 'REPLICATION';
```

I guess that the deletion process is taking too much time so that the request never succeeds. Is there a way to improve the speed? I would prefer not to delete the entries from the database by hand.</div>

**Comment by chlins** [comment]
Hi, currently the deletion of replication is like you mentioned it needs to look out all the executions and tasks then check status and delete them one by one, which will have a bad performance in case of large executions under the policy, but in fact harbor should have a background logic to clean up the executions(by default should only retain latest 50 executions with final state), in your case it seems there are too many obsoleted executions not be deleted, so you can delete these executions manually and delete the policy again as workaround, and also we should investigate the issue and improve the performance or mechanism, thanks.

**Comment by chlins** [comment]
We may need a mechanism that when a resource is deleted, automatically asynchronously cleans up other associated resources so as not to block the current deletion, move it out 2.10 for further discussion.
