### ISSUE TITLE
Image Pull Degredation

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#18989]
### Discussed in https://github.com/goharbor/harbor/discussions/18974

<div type='discussions-op-text'>

<sup>Originally posted by **capps-b** July 22, 2023</sup>
Hi, 

We are running a harbor cluster managed by helm. The first few pulls are fine, but after several pulls the speed becomes extremely slow. I've also noticed that registry-photon pods are consistently growing in memory usage regardless of traffic and never seems to let that memory go (unless the pod is killed/restarted).
1. What is it cacheing?
2. Is there some memory leak going on? Is it something we misconfigured that is common?
3. Why does it hold onto memory after connections have (presumably) closed?

I want to better understand what the registry pod actually does and how it communicates with the rest of them. Could it be that connections are not getting closed out after the pull is done?</div>

**Comment by chlins** [comment]
Hi, could you please provide the memory trending screenshot of the registry? Sometimes the memory seen is not the real active usage but also contains the cache operated by the system, the operating system may use some memory as cache when write/read files from the disk to improve the performance.

**Comment by capps-b** [comment]
Hi @chlins upon further inspection it looks like ingress was throttling, not registry or core.
