### ISSUE TITLE
gc log not job_id

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#18999]
When I want to get the `jobid` in the gc log, I can only query it in the database, which is very inconvenient. I hope to add a log that prints the jobid in the log.

**Comment by chlins** [comment]
@lengrongfu The job ID is the internal id for jobservice to track and manage the jobs, for the harbor user they can just use the execution and task id to track the status and logs. Can you describe why you need this job id in the log, and what you subsequently use this id for?

**Comment by lengrongfu** [comment]
I want to enter the jobserver to view a small amount of incremental logs through tail -f logfile;

At present, when viewing the gc log from the UI, the entire log file needs to be loaded back. The log file has a lot of content and it takes a long time to load, and you can’t just view the incremental content, which is inconvenient to use.

Adding jobid to the log will also be convenient for developers to troubleshoot problems.

**Comment by chlins** [comment]
Understood your scenario, the job id may be helpful for developer to troubleshoot, but I think we should expose the job id in the GC task API response which is more compliant and universal.

**Comment by lengrongfu** [comment]
Agree to add job_id to GC task API response.

In addition, I have another proposal, can the current UI view the job log achieve the effect of tail -f, and only view the incremental content.
