### ISSUE TITLE
Docker push not working - host 'core' not found

### ISSUE THREAD

**Issue by Skoucail** [goharbor/harbor#19005]
I just setup harbor on a docker machine with the install.sh script.
After creating a project "test" i tried to push a random docker. This fails!

Getting dummy image to push
`docker pull renovate/renovate`
`docker image tag renovate/renovate <harbor_hostname>/test/renovate`
Logging in to harbor repo (with the admin account)
`docker login http://<harbor_hostname>`
Pushing to harbor
`docker push <harbor_hostname>/test/renovate`

Error in shell pushing to docker:
`dialing core:443 with direct connection: resolving host core: lookup core: no such host`

Extra info:
Harbor internally is running with HTTP.
And a HTTPS offload is set infront of harbor.
In harbor external_url is set to https://<harbor_hostname>
And the nginx config has been updated to comment out headers Host and X-Forwarded-Proto and the map $http_x_forwarded_proto

Anyone can help me figure out what i'm doing wrong or what config is missing/wrong?

**Comment by Skoucail** [comment]
The one thing i notice is that the response of the call POST /v2/test/renovate/blobs/uploads/ HTTP/1.1 returns a Location header with a url starting with https://core/v2/....

`Location: https://core/v2/test/renovate/blobs/uploads/7f58888c-569e-4fc5-a627-04f8de8e868c?_state=JyYi6B0rWOOOj9lK1qX-4FN1LngGBAimNVWR10LKJ2B7Ik5hbWUiOiJ0ZXN0L2RvY2tlcndlYmFwaSIsIlVVSUQiOiI3ZjU4ODg4Yy01NjllLTRmYzUtYTYyNy0wNGY4ZGU4ZTg2OGMiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMDctMjZUMDc6Mzg6NDQuNTM2NjI5ODE0WiJ9`

I tried setting relativeurls: true in harbor.yml and reran the prepare script followed with docker compose up -d.
But still getting same behaviour.

**Comment by MinerYang** [comment]
Have you map your harbor host name  in /etc/resolv.conf correctly?

**Comment by Skoucail** [comment]
> Have you map your harbor host name in /etc/resolv.conf correctly?

On what machine should i change the /etc/resolv.conf? On the host that runs harbor?
I'm receiving the error on the machine i'm trying to push from. (in this case a windows machine).
