### ISSUE TITLE
Harbor 1.75 部署的时候core组件一直处于 Restarting

### ISSUE THREAD

**Issue by Nick956** [goharbor/harbor#19008]
harbor-core    | 2023-07-26T03:01:09Z [INFO] Config path: /etc/core/app.conf
harbor-core    | 2023-07-26T03:01:09Z [INFO] initializing configurations...
harbor-core    | 2023-07-26T03:01:09Z [INFO] key path: /etc/core/key
harbor-core    | 2023-07-26T03:01:09Z [INFO] initializing client for adminserver http://adminserver:8080 ...
harbor-core    | 2023-07-26T03:01:09Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp 172.20.0.4:8080: getsockopt: connection refused
harbor-core    | 2023-07-26T03:01:11Z [INFO] initializing the project manager based on local database...
harbor-core    | 2023-07-26T03:01:11Z [INFO] configurations initialization completed
harbor-core    | 2023-07-26T03:01:11Z [INFO] Registering database: type-PostgreSQL host-  port- databse-registry sslmode-"disable"
harbor-core    | [ORM]2023/07/26 03:01:12 Detect DB timezone: Asia/Shanghai open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
harbor-core    | 2023-07-26T03:01:12Z [INFO] Register database completed
harbor-core    | 2023-07-26T03:01:12Z [INFO] User id: 1 already has its encrypted password.
harbor-core    | 2023-07-26T03:01:12Z [INFO] Because SYNC_REGISTRY set false , no need to sync registry 
harbor-core    | 2023-07-26T03:01:12Z [INFO] Init proxy
harbor-core    | panic: ERR illegal address
harbor-core    | 
harbor-core    | goroutine 1 [running]:
harbor-core    | github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
harbor-core    |        /go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
harbor-core    | github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
harbor-core    |        /go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
harbor-core    | main.main()
harbor-core    |        /go/src/github.com/goharbor/harbor/src/core/main.go:156 +0x877
harbor-core    | 2023-07-26T03:01:12Z [INFO] Config path: /etc/core/app.conf
harbor-core    | 2023-07-26T03:01:12Z [INFO] initializing configurations...
harbor-core    | 2023-07-26T03:01:12Z [INFO] key path: /etc/core/key
harbor-core    | 2023-07-26T03:01:12Z [INFO] initializing client for adminserver http://adminserver:8080 ...
harbor-core    | 2023-07-26T03:01:12Z [INFO] initializing the project manager based on local database...
harbor-core    | 2023-07-26T03:01:12Z [INFO] configurations initialization completed
harbor-core    | 2023-07-26T03:01:12Z [INFO] Registering database: type-PostgreSQL host-  port- databse-registry sslmode-"disable"
harbor-core    | [ORM]2023/07/26 03:01:12 Detect DB timezone: Asia/Shanghai open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
harbor-core    | 2023-07-26T03:01:12Z [INFO] Register database completed
harbor-core    | 2023-07-26T03:01:12Z [INFO] User id: 1 already has its encrypted password.
harbor-core    | 2023-07-26T03:01:12Z [INFO] Because SYNC_REGISTRY set false , no need to sync registry 
harbor-core    | 2023-07-26T03:01:12Z [INFO] Init proxy
harbor-core    | panic: ERR illegal address
harbor-core    | 
harbor-core    | goroutine 1 [running]:
harbor-core    | github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
harbor-core    |        /go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
harbor-core    | github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
harbor-core    |        /go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
harbor-core    | main.main()
harbor-core    |        /go/src/github.com/goharbor/harbor/src/core/main.go:156 +0x877
harbor-core    | 2023-07-26T03:01:13Z [INFO] Config path: /etc/core/app.conf
harbor-core    | 2023-07-26T03:01:13Z [INFO] initializing configurations...

**Comment by MinerYang** [comment]
Please update to the latest harbor version
ref: https://github.com/goharbor/harbor/issues/8314

**Comment by MinerYang** [comment]
close by above comment. Harbor 1.75 is not supported anymore
