### ISSUE TITLE
Duplicate CVE ID filter when jump from top CVEs

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#19015]
How can we help you?

Duplicate filter CVE ID will appear when jumping from the top 5 dangerous CVEs.

<img width="1578" alt="image" src="https://github.com/goharbor/harbor/assets/31262637/2eeb51dd-e6ba-4d34-a2af-87c1b838037e">

**Comment by YangJiao0817** [comment]
Maybe it's a class issue, Filter is missing CVE ID and Severity and CVSS3 when jumping from Top 5 Most Dangerous Artifacts
<img width="1381" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/606804a5-09ef-47d1-9b8f-a08d660e40dc">
