### ISSUE TITLE
I get empty search reaults with Most Dangerous CVE ID

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#19028]
<img width="1343" alt="image" src="https://github.com/goharbor/harbor/assets/2841473/6b44650b-a224-4291-aceb-a7699b2de351">

**Comment by AllForNothing** [comment]
I can also reproduce the issue:
1. Push an image then scan it
2. Delete the image
3. The vul records will be deleted but `the top 5 most dangerous CVE` still exist

**Comment by stonezdj** [comment]
closed
