### ISSUE TITLE
OIDC: failed to create user record user or email already exists (after changing client_id)

### ISSUE THREAD

**Issue by lknite** [goharbor/harbor#19029]
I had to set a new client_id in my Identity Server.

After updating the client id in the helm chart I now get an error when I login:
``{"errors":[{"code":"UNKNOWN","message":"failed to create user record: user lknite or email lknite@home.net already exists"}]}``

kubetail:
```
[harbor-core-5b7566bd94-bljps] 2023-07-26T18:35:09Z [DEBUG] [/core/controllers/oidc.go:228]: User created: lknite
[harbor-postgresql-0] 2023-07-26 18:35:09.538 GMT [837] ERROR:  duplicate key value violates unique constraint "harbor_user_username_key"
[harbor-core-5b7566bd94-bljps] 2023-07-26T18:35:09Z [DEBUG] [/lib/http/error.go:62]: {"errors":[{"code":"UNKNOWN","message":"failed to create user record: user lknite or email lknite@home.net already exists"}]}
[harbor-postgresql-0] 2023-07-26 18:35:09.538 GMT [837] DETAIL:  Key (username)=(lknite) already exists.
[harbor-core-5b7566bd94-bljps] 2023-07-26T18:35:09Z [ERROR] [/core/controllers/oidc.go:163]: User not onboarded
[harbor-postgresql-0] 2023-07-26 18:35:09.538 GMT [837] STATEMENT:  INSERT INTO "harbor_user" ("username", "email", "password", "password_version", "realname", "comment", "deleted", "sysadmin_flag", "reset_uuid", "salt", "creation_time", "update_time") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "user_id"
```

kubernetes: v1.25.9
app version: 2.8.2
helm chart: 16.7.2
helm repo: https://charts.bitnami.com/bitnami

.
## work around ##
see posting below for work around

**Comment by lknite** [comment]
Ok here's the work around ... (recording here so other folks can use it)

1. watch the log of the 'harbor-core' pod, try to log in via oidc
2. copy the 'Raw ID token for verification' token from the log into jwt.io
3. copy the value from 'sub' field which appears at jwt.io now that you have pasted the token there
4. 'k exec' into the 'harbor-postgres' pod
5. access postgres (you will need a password) using:  psql -U postgres -d registry
6. search the oidc_user table with: select * from oidc_user;
7. you need to find the 'subiss' value
8. the 'subiss' needs to be the 'sub' value you found in step 3, concatenated with the oidc issuer
9. update the subiss with something similar to: update oidc_user set subiss='\<sub\>\<oidc_issuer\>' where id = 1;

Now you should be able to login.

thanks to @stonezdj on this issue https://github.com/goharbor/harbor/issues/16558 which helped me to figure this out

...
going to leave this open cause this feels like a bug that the client_id can't be changed

**Comment by lknite** [comment]
leaving this open cause this feels like a bug that the client_id can't be changed

**Comment by hv15** [comment]
Thanks @lknite for sharing the workaround! To add, for anyone using KeyCloak, you can avoid having to capture the RAW ID (by setting `LOG_LEVEL=debug` in the Harbor Core config) and instead get the `sub` ID directly from KeyCloak.

The Harbor `user_id` can get found using the RESTful API, with `https://<harbor-url>/api/v2.0/users`.

![keycloak-user-account](https://github.com/goharbor/harbor/assets/2742854/acd93118-aa5c-4ead-8318-b2e489401432)

**Comment by stonezdj** [comment]
> leaving this open cause this feels like a bug that the client_id can't be changed

It works as designed because the sub+issuer is the identify of the OIDC user, if the OIDC client_id is changed,  there is no way to coordinate the previous user with the current user, because OIDC username can be changed/customized when the user first onboard.

When the OIDC client_id is changed, the workaround is to delete all existing OIDC users and try login OIDC user again.
<img width="636" alt="Screenshot 2023-08-23 at 17 10 11" src="https://github.com/goharbor/harbor/assets/2696760/006da1a8-8ee7-464f-b23e-b991211ca0b0">

**Comment by lknite** [comment]
Ok then.
