### ISSUE TITLE
icon and default tag behavior not consistent between cosign and notation

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#19039]
`image 0`
<img width="1413" alt="Screenshot 2023-07-27 at 15 08 01" src="https://github.com/goharbor/harbor/assets/6709992/3ff90d51-a698-4a1e-834a-6ca677263720">

When you click the link of `rectangle 1`, it will go to `image 1` as below:
<img width="386" alt="Screenshot 2023-07-27 at 15 13 11" src="https://github.com/goharbor/harbor/assets/6709992/e77405e3-bc16-4dea-b93f-acdd18c87229">
And when you click the link of `rectangle 2`, it will go to `image 2` as below:
<img width="356" alt="Screenshot 2023-07-27 at 15 10 59" src="https://github.com/goharbor/harbor/assets/6709992/565ef99e-0ab0-4ac2-b340-ca1c80dbe16e">

There are two observation here:
1. the icon are not consistent in `image 1` and `image 2` and neither of them shows icon displayed in `image 0`
2. there is no default tag for `image 1`, while there is a default tag for `image 2`. Is this behavior by design or should them be consistent.

**Comment by AllForNothing** [comment]
On the artifact detail page, the icon stands for the media type.
Cosign is regarded as `image` and notation is regarded as `other`

**Comment by AllForNothing** [comment]
Closing it as above comment

**Comment by zyyw** [comment]
How about the tag? The notation accessary has no default tag, while the cosign accessory has a default tag. Is this by design?
