### ISSUE TITLE
"How to identify the completion of image transmission with a specific tag within a webhook?"

### ISSUE THREAD

**Issue by menglong21** [goharbor/harbor#19035]
Hi, I have configured the replication of an image with a specific tag between two Harbor instances. Is there any way to identify the completion of this image transmission and specifically recognize the name of the image tag within a webhook?
webhooks now: 
{"type":"REPLICATION","occur_at":1690428883,"operator":"MANUAL","event_data":{"replication":{"harbor_hostname":"10.18.7.7","job_status":"Success","artifact_type":"artifact","authentication_type":"basic","override_mode":true,"trigger_type":"MANUAL","policy_creator":"admin","execution_timestamp":1690428878,"src_resource":{"registry_type":"harbor","endpoint":"http://10.18.7.7:5000","namespace":"test"},"dest_resource":{"registry_name":"总中心","registry_type":"harbor","endpoint":"https://10.18.7.1:5000","namespace":"test"},"successful_artifact":[{"type":"artifact","status":"Success","name_tag":"test10g [2 item(s) in total]"}]}}}

**Comment by chlins** [comment]
Add a new field `references` into the webhook payload, which is a string list contains the tags or digests if no tag of the artifact, retain the old `name_tag` as summary info to not bring any break change.

e.g.
```json
{
  "type": "REPLICATION",
  "occur_at": 1696924365,
  "operator": "admin",
  "event_data": {
    "replication": {
      "harbor_hostname": "192.168.8.107",
      "job_status": "Success",
      "artifact_type": "artifact",
      "authentication_type": "basic",
      "override_mode": true,
      "trigger_type": "MANUAL",
      "policy_creator": "admin",
      "execution_timestamp": 1696924334,
      "src_resource": {
        "registry_type": "harbor",
        "endpoint": "http://192.168.8.107",
        "namespace": "library"
      },
      "dest_resource": {
        "registry_name": "demo",
        "registry_type": "harbor",
        "endpoint": "https://demo.goharbor.io",
        "namespace": "library"
      },
      "successful_artifact": [
        {
          "type": "artifact",
          "status": "Success",
          "name_tag": "harbor-core [7 item(s) in total]",
          "references": [
            "v2.7.1-dev",
            "v2.6.0",
            "v2.5.3",
            "sha256:ceb3af5a41675524ab9e05ced7c879f1f5296eaaaae65b761a06feab2b819ce4",
            "sha256:1c0efb866fba0d4377e0dc8d449c7c2b51c075c5e109be984ea545b6e44729e2",
            "sha256:d96bd7f1d0d02f90449293d314b4a4f5edc0de1db84cc7ff125b5cfa48ab3e0b",
            "sha256:5a909af45c03907a5392ced76b4b7d255937b55e5330410b9b1a9608bf39865d"
          ]
        }
      ]
    }
  }
}
```
