### ISSUE TITLE
Accessories will not be GCed when GCing an artifact

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#19041]
When GCing an artifact, its accessories will not be GCed(deleted). Then its accessories become dirty data.

Steps to reproduce:
1. Push an image to Habor, eg: `library/redis:latest`
2. Sign the image with cosign or notation
3. Delete the latest tag of the image, then run GC after the GC time window.
4. The image will be GCed but the accessory will not

**Comment by YangJiao0817** [comment]
The same issue #16418 was fixed in 2.5.0, but reported again in 2.6.0.
