### ISSUE TITLE
arbitrary namespace hardcoded in jobservice-cm

### ISSUE THREAD

**Issue by Brice187** [goharbor/harbor#19042]
https://github.com/goharbor/harbor-helm/blob/cb55d35bfc3c7cac8972b5768dd191605368e17f/templates/jobservice/jobservice-cm.yaml#L22

this should be templateable in values.yaml

**Comment by MinerYang** [comment]
To be more clearly, it is the redis namespace, not for harbor containers. Would you elaborate more what's the benefit or  purpose by using a redis namespace rather than a default one?

**Comment by Brice187** [comment]
i don't know what the benefit of this is and don't use the specific hardcoded namespace at all ;)
IMHO this could be removed, but I don't know if this will break running deployments

**Comment by MinerYang** [comment]
closed by above comment
