### ISSUE TITLE
Dry Run GC does not show Details

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19040]
<img width="1395" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/71eb8841-627c-49e6-a681-254078293c60">

<img width="1630" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/059996d8-6c6b-4ff2-af5c-9c166b5b67c1">

**Comment by AllForNothing** [comment]
duplicated with #19038

**Comment by wy65701436** [comment]
It's by designed.
