### ISSUE TITLE
harbor为什么不提供arm64的离线包？

### ISSUE THREAD

**Issue by javasunCN** [goharbor/harbor#19047]
经历了一周的努力 arm64编译失败，有没有提供arm64安装包的镜像地址？

**Comment by MinerYang** [comment]
we have a independent ARM working repository here
https://github.com/goharbor/harbor-arm

**Comment by MinerYang** [comment]
close by above comment

**Comment by zero-wsh** [comment]
> 经历了一周的努力 arm64编译失败，有没有提供arm64安装包的镜像地址？

请问arm离线包找到了吗？麻烦分享一下

**Comment by git-lishixian** [comment]
找到一个第三方维护的arm版本harbor
https://github.com/wise2c-devops/build-harbor-aarch64
