### ISSUE TITLE
For calls without authentication systeminfo should not return banner_message

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19052]
<img width="1244" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/5e1f9434-90e9-4f4f-9fa6-978db1083264">

<img width="1187" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/08e697de-67b5-4e2b-8da5-e8f972ccbebd">

**Comment by AllForNothing** [comment]
It's by design.   Any user(Including anonymous users) can view the banner message

**Comment by YangJiao0817** [comment]
We should show it on the login page.
https://github.com/goharbor/harbor/issues/19076
