### ISSUE TITLE
Admin users reported with an `Unknown` state

### ISSUE THREAD

**Issue by xoanmi** [goharbor/harbor#19051]
**Expected behaviour and actual behaviour:**
When OIDC Auth is configured and `oidc_admin_group` is provided, we expect that in the _Administration >> Users_ menu the admin users are reported correctly. However, they are reported with an `Unknown` state although the mapping between the admin group and users works correctly.:

<img width="1860" alt="image" src="https://github.com/goharbor/harbor/assets/17291695/f4a921f8-28cf-4b16-bc0e-81098b42c357">

**Versions:**
Please specify the versions of the following systems.

- harbor version: v2.8.2-d4c34dcc
- harbor helm chart: v1.12.2
- Kubernetes: v1.27

**Comment by AllForNothing** [comment]
@xoanmi Thanks for the info.
For the OIDC users, Harbor does not store the info if they are admins.
Only when logging in to Harbor, Harbor can know if an OIDC user is an admin.

**Comment by xoanmi** [comment]
> @xoanmi Thanks for the info. This is a function limitation. For the OIDC users, Harbor does not store the info if they are admins. Only when logging in to Harbor, Harbor can know if an OIDC user is an admin.

That's fine. When a user login into the harbor, then we could know if it is an admin or not because the system is performing a lookup on the groups returned from the OIDC and the group is defined as an `oidc_admin_group` in the configuration, isn't it? So, why we are not storing that value on the DB alongside the rest of the info of the user?

The `Unknown` tag is quite annoying when it is pretty clear that harbor knows on every login if the user is admin or not.
