### ISSUE TITLE
When using ali slb proxy harbor, docker push return unknown blob

### ISSUE THREAD

**Issue by Lu-Lucifer** [goharbor/harbor#19064]
harbor version:2.8.2
docker version:24.0.5

When using ali slb proxy harbor, docker push return unknown blob, docker push ip:port/REPOSITORY[:TAG] is successed

i change nginx.conf # proxy_set_header X-Forwarded-Proto $x_forwarded_proto, but always return unknown blob

the nginx.conf  how to edit can make this work

**Comment by chlins** [comment]
Could you please provide the harbor.yml? It should be the configuration related issue If the push works well by `ip:port`.
