### ISSUE TITLE
p2p preheat policy cannot update to `None` for scheduled trigger

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#19070]
I created a p2p preheat policy from harbor portal and scheduled it to run weekly. This can be set successfully.
However, when I was trying to update the schedule to `None`, the `SAVE` button is gray-colored and is not clickable.
<img width="580" alt="Screenshot 2023-08-01 at 17 01 11" src="https://github.com/goharbor/harbor/assets/6709992/7e77935f-8729-44f3-bf1f-f298cefad9b2">

**Comment by AllForNothing** [comment]
@zyyw This is by designed behavoir. you must set a cron string if you select `Scheduled`.  for None, you need to select `Manual`
