### ISSUE TITLE
any patch plan for 2.7 release and what's its lifecycle?

### ISSUE THREAD

**Issue by danielzhanghl** [goharbor/harbor#19075]
hi Harbor team, 
we are using 2.7.2 release currently as there is significant change on 2.8 release which remove chartmuseum.

and we would like to know **what is the end of 2.7 release** and is there any recent plan to issue patch above that, like 2.7.3?
thanks.

**Comment by chlins** [comment]
Normally the maintain policy is N-2 which means if the working branch(main) is corresponds to 2.9 then the 2.7.x and 2.8.x will be in the support lists. Recently team is working on the 2.9 release, we may consider to patch the 2.7.x after it.

**Comment by danielzhanghl** [comment]
thanks for the information.
