### ISSUE TITLE
Optimize requests sent from list artifacts page

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19077]
list artifacts sends too many requests.
For example, 10 artifacts will send 41 requests.
(cosign + notation + accessories + with_signature) *  artifact count + list artifact.

We should merge some requests and not send so many.

**Comment by chlins** [comment]
Although we can enable the `with_tag` and `with_accessory` in the artifacts lists API to reduce the separate query requests for each artifact, but if the number of the tag or accessory for artifact is large, which will leads to the response size too large, need to discuss further more about this part.
