### ISSUE TITLE
Otel failed to send traces

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#19084]
Hello Team,

Invalid configuration in sample of  harbor.yml for OTEL
timeout: 10s, it has to only "10" without "s".

Error: [ERROR] [/pkg/config/manager.go:66]: LoadSystemConfigFromEnv failed, config item, key: trace_otel_timeout, err: invalid int string: 10s

Thank You,
Ayush

**Comment by chlins** [comment]
Thanks, it seems the incorrect sample configuration for otel, the value should be int type and the backend unit is seconds.
