### ISSUE TITLE
Unable to proxy helm charts in OCI registry

### ISSUE THREAD

**Issue by reddy9694** [goharbor/harbor#19086]
We have a harbor instance in one region and we pushed couple of helm charts to OCI registry using following commands.
helm registry login <harbor-url>
helm push <.tgz file> oci://harbor-url/project
and also able to download the same using helm pull oci://harbor-url/project/chart --version < version>

Now we have created the a proxy cache project in another region harbor instance, which is using the above harbor instance as Proxy Cache Endpoint.
I tried the same helm pull with the following.
helm pull oci:// harbor-url/source-project/remote-project/chart --version < version>

**Comment by chlins** [comment]
Could you please provide more context such as screenshot and harbor logs?
