### ISSUE TITLE
How to Configure storage_service ?

### ISSUE THREAD

**Issue by syslabtech** [goharbor/harbor#19099]
Hello Team,

In official document of harbor 
https://goharbor.io/docs/2.8.0/install-config/configure-yml-file/
configuration of harbor yaml file.

mention to disable data_volume and enable storage_service. but when I comment on data_volume and comment out on storage_service but given me error, I have mention below 
docker: invalid spec: :/data: empty section between colons.

Can you please help me here?

**Comment by chlins** [comment]
Could you please paste the harbor yaml file after applied your changes?

**Comment by chlins** [comment]
The `data_volume` section cannot be disabled as the storage service only stores the distribution data, there are some other data such as db and jobservice data which will be stored in the data volume.
