### ISSUE TITLE
Delete an accessory cannot trigger Event based replication

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19098]
<img width="633" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/8658da95-80a9-42d7-9c39-322541e7e3fd">

<img width="1409" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/758c898b-62ee-4a2a-aa6d-aa6da6b799d3">

Harbor version: v2.9.0-cdd3f267

**Comment by chlins** [comment]
Caused by the disappearance of a synchronized deleted checkbox on the UI.

<img width="644" alt="image" src="https://github.com/goharbor/harbor/assets/31262637/b48a713d-8424-499e-8f29-c016d72864c0">
