### ISSUE TITLE
Multiple use of cosign sign the same artifact, cosign signature tag issue

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19096]
![image](https://github.com/goharbor/harbor/assets/72076317/3b261c41-4fd6-48df-b742-ce2318d5a947)
![image](https://github.com/goharbor/harbor/assets/72076317/9a930b82-af2b-4b6e-9546-3767f2822224)
![image](https://github.com/goharbor/harbor/assets/72076317/e35e53b3-90c2-44fb-890b-d6d9e9752792)

The first sign cosign signature tag is missing and will tag on the second sign cosign signature.

**Comment by ShouEnHsiao** [comment]
This would cause an issue when replication. The accessory without a tag will became unsigned manifest in destination registry. I am not sure if this is cosign's responsibility to dedupe the signature (afaik, cosign sign has a way to dedupe but this could still happen when public key different) or harbor's responsibility to maintain the accessory relation after replication.
