### ISSUE TITLE
Can't login to registry via "docker login <harbor-IP>"

### ISSUE THREAD

**Issue by tbartschat** [goharbor/harbor#19115]
Hi all,

I'm desperate with my harbor setup. After installation the UI is reachable vi any browser, but I can't login to registry via shell. 

Getting always an error message when I want to login into registry. Trying to login from the same vm where the harbor installation is running. 

docker login < harbor-IP > 

Error response from daemon: Get "http://x.x.x.x/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

The error messages shell output shows always "HTTP" instead of "HTTPS" but i can see in the logs that "HTTPS" was tried and is failing, too.

msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://x.x.x.x/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

But the registry is running, I can curl the registry from the same host where "docker login" is not working.

tbartschat@harbor-registry:/etc/harbor$ curl -k https://x.x.x.x/v2/_catalog -u xxxxx
Enter host password for user 'xxxxxx':
{"repositories":[]}
tbartschat@harbor-registry:/etc/harbor$

I already checked docker daemon file and tried a lot of different settings there without success, this is the inital daemon config file.

{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "insecure-registries" : ["x.x.x.x:443", "x.x.x.x:80", "0.0.0.0/0"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
} 

Can one of you please help me ? 

Without login to the registry, I can't push images to it and without doing this the harbor installation is not useable as registry at all. 

Thanks in advance!!!

**Comment by chlins** [comment]
How did you install harbor and whether https is enabled? Please provide and check the configuration of harbor yaml.

**Comment by tbartschat** [comment]
Hi @chlins,

thanks for your response. I already checked harbor.yaml and https was enabled. 

I solve this issue for some hours ago, the issue was the IP address of my harbor installation, I had a private IP from Class C subnet 192.168.123.0/24 as harbor Interface in the harbor.yml. But via any IP from 192.168.x.x/24 subnet docker login not working at all. Looks like that routing from Docker Network to these private Class C IP is not working. Anyway after changing IP to 100.x.x.x/24 in harbor.yaml and generate new certs for https to match new IP all works as expected.
