### ISSUE TITLE
Pushing from GitLab to Harbor

### ISSUE THREAD

**Issue by d-scott-mmath** [goharbor/harbor#19113]
I am looking to push a Docker Container from GitLab to Harbor.

I have followed the GitLab Harbor integration guide, found here, [Harbor | GitLab](https://docs.gitlab.com/ee/user/project/integrations/harbor.html)

When I Test settings I get the "Connection successful message".

I'm looking to now push from GitLab to Harbor, using the GitLab CI/CD

The code is as follows

test_harbor_push:
  stage: test_harbor_push
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug  
    entrypoint: [""]
  script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"location_of_harbor_instance\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
      - cat /kaniko/.docker/config.json
      - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
        --destination "${HARBOR_HOST}/${HARBOR_PROJECT}/"repository_name":${CI_COMMIT_BRANCH}"
  when: manual
  rules:
      - if: $CI_COMMIT_TAG # Do not run this job when a tag is created manually
        when: never   
      - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH" 

However I get the error message: 

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "location_of_harbor_instance/project_name/repository:CI_COMMIT_BRANCH": POST location_of_harbor_instance/v2/project_name/repository/blobs/uploads/: UNAUTHORIZED: unauthorized to access repository: project_name/repository, action: push: unauthorized to access repository: project_name/repository, action: push

Do you have any advice? One thing I note is that I am a project admin for this specific project, with Access Level Private, but am not an admin for the Harbor instance.

**Comment by chlins** [comment]
Could you please provide the harbor core and registry logs? The project admin should have the permission for pushing images.

**Comment by d-scott-mmath** [comment]
Hi again,
It turned out the issue was with the harbor_username.
Once I added an escape character (/) to the front of the username the pushworked as expected
