### ISSUE TITLE
change "Job ID" to "Task ID"

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#19126]
Currently on the Clean Up web page, the gc task id is displayed using job_id, which is different from the real job_id. We should use Task ID to display it in unison with other pages (replications info page).

- replications info page
<img width="1169" alt="image" src="https://github.com/goharbor/harbor/assets/15009201/7454a3a5-ef31-4a59-a1a9-e7e05c6786b7">

- Clean Up info page
<img width="1160" alt="image" src="https://github.com/goharbor/harbor/assets/15009201/c554ea0f-bb47-45a6-a7f9-d4851b8273f4">

**Comment by AllForNothing** [comment]
Maybe， we need to check all the places and change them together:
purge history:
<img width="1404" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/f4dd426d-9839-486e-b36d-89f5acd0bda1">
replication tasks:
<img width="1392" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/da7e97f3-c2f3-4fb9-9be1-566a0fb8a302">
Retention:
<img width="1246" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/bf997341-533e-440d-9a0e-cb4a385e6a38">
Webhook:
<img width="1422" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/e2533d60-14fa-453e-a61e-3b73ee94f4e3">

**Comment by AllForNothing** [comment]
@lengrongfu Please also apply your change to the purge history datagrid
