### ISSUE TITLE
certificate error 

### ISSUE THREAD

**Issue by sumakuma2006** [goharbor/harbor#19128]
How can we help you?
Error response from daemon: Get "https://192.168.189.144/v2/": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.189.144 because it doesn't contain any IP SANs

**Comment by sumakuma2006** [comment]
without certificate also i tried but getting error ....core service not available

**Comment by lengrongfu** [comment]
Maybe what you want to ask is this:
https://docs.docker.com/registry/insecure/

**Comment by sumakuma2006** [comment]
could you pls share exact installation steps on ubuntu 20.04 , now i am getting postgressql error

**Comment by sumakuma2006** [comment]
> could you pls share exact installation steps on ubuntu 20.04 , now i am getting postgressql error

**Comment by chlins** [comment]
> could you pls share exact installation steps on ubuntu 20.04 , now i am getting postgressql error

Please provide the error message and harbor logs.

**Comment by sumakuma2006** [comment]
> > could you pls share exact installation steps on ubuntu 20.04 , now i am getting postgressql error
> 
> Please provide the error message and harbor logs.

postgressql connectivity error, core service is not available, certificate error so such errors i am getting , pls share exact harbor setup steps on ubuntu 20.04

**Comment by sumakuma2006** [comment]
> Error response from daemon: Get "https://192.168.189.144/v2/": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.189.144 because it doesn't contain any IP SANs

**Comment by zyyw** [comment]
@sumakuma2006 as for the following error:
> Error response from daemon: Get "https://192.168.189.144/v2/": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.189.144 because it doesn't contain any IP SANs

Please try this method to generate the server.crt, server.key and ca.crt for your Harbor instance. Read the following section: `How to generate server.crt, server.key and ca.crt using OpenSSL?`
