### ISSUE TITLE
How to configure a project to use Ali ACR as a proxy cache

### ISSUE THREAD

**Issue by yuexian1234** [goharbor/harbor#19125]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I create a project, and I can select a pre-configured Ali ACR proxy cache

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1. configure a registry endpoint use ali acr,and the endpoint is healthy.
2. create a project,and use cache
3. but i can`t choose the the above endpoint 
- harbor version: 2.8.3
- docker engine version: 18.06
- docker-compose version: 2.20.2

<img width="975" alt="image" src="https://github.com/goharbor/harbor/assets/14341344/3b3415d6-0dd5-4fa2-b3f8-2aa618307414">

in the picture,i create two registry endpoint
but when i create project and to choose ,i just see one endpoint
<img width="544" alt="image" src="https://github.com/goharbor/harbor/assets/14341344/d77c901e-6807-4660-8ced-f7bebfcde363">

**Comment by stonezdj** [comment]
Ali ACR is not officially supported as a proxy cache, you could create a proxy cache project use the dockerhub first, then update the proxy cache with the registry_id of the ali ACR.
```
select * from registry -- get the registry id of Ali ACR
select * from project where registry_id is not null -- get the project_id of the new created proxy cache project
update project set registry_id = <registry_id> where project_id = <project_id> --- update to registry_id to Ali ACR
```

**Comment by yuexian1234** [comment]
> Ali ACR is not officially supported as a proxy cache, you could create a proxy cache project use the dockerhub first, then update the proxy cache with the registry_id of the ali ACR.
> 
> ```
> select * from registry -- get the registry id of Ali ACR
> select * from project where registry_id is not null -- get the project_id of the new created proxy cache project
> update project set registry_id = <registry_id> where project_id = <project_id> --- update to registry_id to Ali ACR
> ```

thanks. it can work correctly

**Comment by chlins** [comment]
@yuexian1234 Would you like to add the support in the UI when you test fully and no issue found?
