### ISSUE TITLE
Mirror synchronization uses a port other than 443

### ISSUE THREAD

**Issue by long1318737396** [goharbor/harbor#19139]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
My A harbor is using a port other than 443，i can see core containers log

failed to ping registry https://harbor.xxx.com:4430: Get "https://harbor.xxx.com/service/token?service=harbor-registry": tls: failed to verify certificate: x509

So the root cause is that my target warehouse uses port 4430, but it uses port 443 during detection, which causes me to fail to connect all the time. How to solve this situation? Can only port 443 be used?
**Versions:**
Please specify the versions of following systems.

- harbor version: v2.8.2
- docker engine version: 24.0.2
- docker-compose version: v2.18.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
Harbor should support other ports other than 443, could you check the configuration yaml for your target harbor? the `externalURL` should be configured to `https://harbor.xxx.com:4430` in your case.

**Comment by long1318737396** [comment]
There are two nginx proxies in front of my harbor. The first layer is https proxy to https port 443, and the last layer is non-https 443 port, which uses 4430. For this scenario, whether to return the address when the client requests token The port that can carry the first proxy request

**Comment by chlins** [comment]
I think currently Harbor may not support using two proxies simultaneously, and the value of externalURL is fixed and can only be set to one.
