### ISSUE TITLE
fetch oauth token timeout

### ISSUE THREAD

**Issue by waney316** [goharbor/harbor#19142]
How can we help you?

I have two Harbor servers configured for high availability, and the application is pulling images using a domain name. Recently, there have been frequent errors of this type. What could be the reason and how to fix it ?

- harbor version： v2.4.1-c4b06d79

Failed to pull image "harbor.xxx.com/xxxxxxx": rpc error: code = Unknown desc = failed to pull and unpack image "harbor.xxx.com/xxxxxxx": failed to copy: httpReaderSeeker: failed open: failed to authorize: failed to fetch oauth token: Post "https://harbor.xxxxx.cn/service/token": net/http: TLS handshake timeout

**Comment by chlins** [comment]
Could you also please provide the harbor core and registry logs?
