### ISSUE TITLE
DB init error: popen failure: Cannot allocate memory

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19141]
This is caused by a low version of docker. Upgrading the docker version to >= 20.10.10 will fix this problem.

error.log
```
init DB, DB version:14
popen failure: Cannot allocate memory
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/pgsql/14/bin/initdb".
Check your installation.
```

**Comment by wy65701436** [comment]
@MinerYang and @zyyw Please update the release notes of Harbor offline/online and Helm to include the minimum required version of containerD for Photon5. Additionally, please ensure that the background, steps to resolve, and impact are properly documented.
