### ISSUE TITLE
LDAPS with client certificate

### ISSUE THREAD

**Issue by JqckB** [goharbor/harbor#19154]
**Expected behavior and actual behavior:**
I'm into a Google Secure LDAP environment and to plug LDAPS server with Harbor, I need to be able to give client certificate into the LDAPS configuration.

It is not possible at the moment, can you look into implementing this? 

**Versions:**
- harbor version: 2.8.2

**Comment by stonezdj** [comment]
see: https://github.com/goharbor/harbor/wiki/Harbor-FAQs
```
How to add a CA cert for the LDAP server or other Harbor server?

[A] After installed the Harbor, there is a directory under common/config/shared/trust-certificates Copy the LDAP certificate, for example, ldap_ca.crt to this directory and restart the Harbor, The certificate is added to the trust store of the core container, and then you could enable “Verify Cert” in the LDAP configuration.
```

**Comment by JqckB** [comment]
It isn’t my request, the server certificate of Google LDAPS is trusted as it is a public certificate.

My request is to send client certificate authentification when connecting, here is an exemple on openldap client : https://support.google.com/a/answer/9089736?hl=en#zippy=%2Copenldapldapsearch-linux

Can you look into adding client cert/client private key into LDAPS configuration ?
