### ISSUE TITLE
Be able to affect users to groups manually while using in OIDC authentication

### ISSUE THREAD

**Issue by hart1dechu** [goharbor/harbor#19153]
Hello everyone !

**Is your feature request related to a problem? Please describe.**
I'm using OIDC Authentication with Google, but they don't give any informations about groups. While all my users are automatically onboarded, none of them are automatically affected to a group. Furthermore, there is no way to affect manually an user to a group. I then cannot use groups althought it is a main feature of OIDC/LDAP.

**Describe the solution you'd like**
Be able to manually affect users to groups

Thank you in advance

**Versions**

- Harbor 2.8.2

**Comment by stonezdj** [comment]
Could you please check your OIDC configuration: `Group Claim Name`?

```
Group Claim Name: The name of a custom group claim that you have configured in your OIDC provider, that includes the groups to add to Harbor.

```

**Comment by stonezdj** [comment]
If the goolge doesn't provide it, then you can't retrieve it

**Comment by hart1dechu** [comment]
Exactly, that's the whole reason i am suggesting you a workaround for using OIDC with Google, being able to either 
- asign oidc user to oidc groups manually
- create another group type, like a basic one, and asign users in it

Because for the moment, there is no way to manually affect users to any type of groups

**Comment by hart1dechu** [comment]
Hello,

any updates about this issue ?
