### ISSUE TITLE
How can I use Harbor api on the server command line?

### ISSUE THREAD

**Issue by xiaobai2il** [goharbor/harbor#19155]
I have already installed the harbor on my ubuntu VM and set up replication rules for my harbor on the UI on the webpage, and I would like to be able to directly call the harbor api on my Ubuntu terminal instead of using the UI to modify the replication rule. I checked harbor website for the instruction for using api https://goharbor.io/docs/2.7.0/working-with-projects/using-api-explorer/, and following the steps, I authorize a basic authorization and am able to call the api on the swagger page https://my harbor ip address/devcenter-api-2.0. 

When I'm trying to call the api that I have tested on swagger page on my ubuntu terminal, it will say "curl: (60) SSL certificate problem: unable to get local issuer certificate", and I tried to include the ca.crt but still not work. The only way for the api to work is to add "-k" in my command to get pass SSL, which I don't want. How can I configure the SSL certificate to enable calling api securely on ubuntu server?

**Comment by chlins** [comment]
The issue may not about to harbor, you can search how to add the self-signed cert for curl on ubuntu, some related solutions: https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list, https://leehblue.com/add-self-signed-cert-curl/
