### ISSUE TITLE
Support configure the separate redis db 

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#19169]
As the core redis db(0 by default) stores many kinds of keys, such as session, cache layer and some harbor business cache, the db size will be huge in the large scale environment, the redis may hang out when execute some commands, so we should support to configure the redis db for different business.

**Comment by Vad1mo** [comment]
Can you elaborate on what you mean with configure? What would you like to configure? 
Which database will grow, we use multiple databases.
What is huge, can you quantify it?

A lot of the problems can be easily mitigated with bigger Redis instances or shorter TTLs

> An empty instance uses ~ 3MB of memory. 1 Million small Keys -> String Value pairs use ~ 85MB of memory. 1 Million Keys -> Hash value, representing an object with 5 fields, use ~ 160 MB of memory.


Before coding something, we should use the natural capabilities of Redis to reduce memory consumption.
e.g. https://docs.redis.com/latest/ri/memory-optimizations/
 
 
 There are also some Redis protocol compatible solutions out there that we could recommend first e.g.
 
 https://github.com/apache/kvrocks or https://github.com/Snapchat/KeyDB

**Comment by chlins** [comment]
Apart from sessions, Harbor currently stores some other business-related items in the same db 0 as sessions. In this case, the requests to harbor will generate a session(TTL 3600s), when the number of requests to Harbor exceeds 10 millions per hour, the business code will incur high costs when querying for matching keys from this db. Using the 'keys' command directly will block Redis (it takes 5 seconds to return for 10 millions of keys), leading to subsequent request anomalies. Although using 'scan' can alleviate this issue, it's still a significant cost to scan through such a large number of keys each time. Therefore, splitting the db can allow users in scenarios with a large number of keys like this, to switch to different dbs and reduce the problem of having too many keys in a single db.
