### ISSUE TITLE
task for the scan report ${report_uid} not found

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19166]
1. Push artifact to project a
2. Scan the artifact
3. Copy the artifact to the project library
4. Delete the artifact in project a
5. View artifact in library

<img width="1411" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/5535cbc0-3ae6-4873-9816-08842cb0bd98">
<img width="1415" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/9b67ed5e-328b-4540-96cc-5a3afcc0d206">
error.log

```
2023-08-14T06:44:30Z [WARNING] [/controller/scan/base_controller.go:1071][requestID="589e1770-6e87-46b6-8f7a-654f71ee4e11"]: task for the scan report 709ef4db-606b-47a4-a028-441e6f3f2079 not found
```

Harbor version: v2.9.0-rc1

**Comment by canarie** [comment]
we see the same issue too.

**Comment by stonezdj** [comment]
The backend API should fallback the not found error in query task to another logic, it could query the scan_report table, if there is a  scan_report or vuln in the database, the status should be complete and keep other unknown field empty
