### ISSUE TITLE
helm repository option is not available in Harbor Repository after upgrade

### ISSUE THREAD

**Issue by premsgr6** [goharbor/harbor#19171]
Helm repository option is not available in Harbor repository after upgrade, I have installed harbor repository in EKS using HELM chart version 1.12.0 and after installation there is no option for HELM repository and previsouly it was there.
![image](https://github.com/goharbor/harbor/assets/46933846/1aa781f8-6076-482f-90b2-479219fef5cb)

**Comment by Vad1mo** [comment]
Charmuseum was removed with 2.8

See release notes https://github.com/goharbor/harbor/releases/tag/v2.8.0 and discusssion around it  https://github.com/goharbor/harbor/discussions/15057

**Comment by premsgr6** [comment]
> Charmuseum was removed with 2.8
> 
> See release notes https://github.com/goharbor/harbor/releases/tag/v2.8.0 and discusssion around it #15057

thanks for confirmation, seems missed the documentation, so to clarify Harbor has removed separate tab for helm from UI and same repository will serve for helm as well.
