### ISSUE TITLE
ERROR: column t0.subject_artifact_repo does not exist

### ISSUE THREAD

**Issue by Brice187** [goharbor/harbor#19185]
**Expected behavior and actual behavior:**

I want to delete a containerimage in the WebUI 

expected: Deletion successful

actual: Internal Server Error

**Steps to reproduce the problem:**

Mark **image:tag** in WebUI and use the Delete Button

**Versions:**
Please specify the versions of following systems.

* Kubernetes 1.27.3
* Helm Chart 1.12.3
* goharbor/harbor-core:v2.8.3 
* containerimage stored in S3 (Minio)
* External PostgreSQL 15.3

**Additional context:**

- **Log files:** You can get them by package the `/var/log/harbor/` .

```
2023-08-15T07:07:46Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERROR: column t0.subject_artifact_repo does not exist (SQLSTATE 42703)"}]} 
```

**Comment by stonezdj** [comment]
Login to the Harbor db and execute the following SQL
```
update schema_migrations set version = 100, dirty=false where 1 = 1;
```
Restart all harbor-core pod, it will return the upgrade SQL after restart.

**Comment by AllForNothing** [comment]
is Harbor newly-installed or upgraded from an old one? and can you provide your DB schema?

**Comment by es-x** [comment]
> 

Hello, yep it's work for me, thx

**Comment by es-x** [comment]
up need
