### ISSUE TITLE
Beego session

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#19192]
Because the underlying framework of Harbor's web is based on Beego, each request generates a session, which is stored in Redis. Although these sessions have expiration times, they can still accumulate significantly during high-concurrency scenarios. Additionally, some APIs might not require sessions. Further investigation is needed to determine whether it's possible to selectively enable or disable sessions for certain APIs.

**Comment by liubin** [comment]
In our case, it can be enabled/disabled by the role of core component:
- as a parts of portal(we deploy portal and core in one pod), it needs session
- as an API server(for list/create/.. projects/repos from other services/clients) that use robot/basic auth/... it does not need a session
- as registry API(for docker login/pull/push), it does not need to maintain sessions too.

We can use an ENV to set the role of core, and only enable session by modifying these files:
- src/server/middleware/security/security.go
- src/server/middleware/security/security.go
- `web.BConfig.WebConfig.Session.SessionOn = false` in src/core/main.go
