### ISSUE TITLE
failed to update 2.2.3 to 2.6.4, err: Dirty database version 80. Fix and force version.

### ISSUE THREAD

**Issue by kycheng** [goharbor/harbor#19214]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I hope the upgrade will be successful, but an error is reported when the core links to the database:
```
2023-08-20 2023-08-20T13:11:18Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-harbor-demo1-chart-harbor-harbor-database port-5432 database-registry sslmode-"disable"
2023-08-20 2023-08-20T13:11:18Z [INFO] [/common/dao/base.go:72]: Register database completed
2023-08-20 2023-08-20T13:11:18Z [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
2023-08-20 2023-08-20T13:11:18Z [ERROR] [/common/dao/pgsql.go:136]: Failed to upgrade schema, error: "Dirty database version 80. Fix and force version."
2023-08-20 2023-08-20T13:11:18Z [FATAL] [/core/main.go:177]: failed to migrate the database, error: Dirty database version 80. Fix and force version.
```

**Steps to reproduce the problem:**
2.2.3 update to 2.6.4

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.6.4]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

I found out that the problem was caused by a database upgrade failure of a certain version. , similar to [this](https://github.com/goharbor/harbor/issues/15088) question.

I tried to step through the pre-2.2.3 to 2.6.4 database change scripts, but an error was encountered while executing the 0080_2.5.0_schema.up.sql script:

```
registry=# ALTER SEQUENCE vulnerability_record_id_seq AS BIGINT;
ALTER SEQUENCE
registry=# ALTER TABLE report_vulnerability_record ALTER COLUMN id TYPE BIGINT;
ERROR:  could not create unique index "report_vulnerability_record_report_uuid_vuln_record_id_key"
DETAIL:  Key (report_uuid, vuln_record_id)=(2dd361d4-5e3a-4380-b36d-4e375cf2e686, 447) is duplicated.
registry=# select count(*) from report_vulnerability_record;
 count  
--------
 176124
(1 row)

registry=# select max(id) from report_vulnerability_record;
   max    
----------
 36412599
(1 row)

registry=# select * from report_vulnerability_record where report_uuid = '2dd361d4-5e3a-4380-b36d-4e375cf2e686';
 id | report_uuid | vuln_record_id 
----+-------------+----------------
(0 rows)
```

I understand that duplicate data should not exist. How should I fix this problem?

**Comment by kycheng** [comment]
According to the instructions in this [article](https://stackoverflow.com/questions/45315510/postgres-could-not-create-unique-index-key-is-duplicated), I did find duplicate data. Can I deduplicate data before making changes? What is the impact if deduplication occurs?
```
registry=# BEGIN;
SET LOCAL enable_indexscan = off;
SET LOCAL enable_bitmapscan = off;
SET LOCAL enable_indexonlyscan = off; 
SELECT * FROM report_vulnerability_record WHERE report_uuid = '2dd361d4-5e3a-4380-b36d-4e375cf2e686' and vuln_record_id = 447;
ROLLBACK;
BEGIN
SET
SET
SET
   id    |             report_uuid              | vuln_record_id 
---------+--------------------------------------+----------------
 4613788 | 2dd361d4-5e3a-4380-b36d-4e375cf2e686 |            447
 4616963 | 2dd361d4-5e3a-4380-b36d-4e375cf2e686 |            447
(2 rows)

ROLLBACK
registry=#
```

**Comment by kycheng** [comment]
Just deleting duplicate data should have no effect on the overall structure.

I deduplicated the data and the table can be modified normally afterwards.

Find duplicates:
```
BEGIN;
SET LOCAL enable_indexscan = off;
SET LOCAL enable_bitmapscan = off;
SET LOCAL enable_indexonlyscan = off; 
select report_uuid, vuln_record_id FROM report_vulnerability_record GROUP BY  report_uuid, vuln_record_id having count(*) > 1;
ROLLBACK;

 2dd361d4-5e3a-4380-b36d-4e375cf2e686 |            447
 fa452fea-e771-492f-9e97-220847e26fef |           8850
 d62f82b8-0b60-4281-bad4-6273087a8cdf |           8850
 6a0f74e5-c860-4ffb-8d70-f72895549fa7 |           8850
 2064e464-035a-4bfb-8b3c-c38a43f2f9ac |            447
 4f00051a-26e4-4769-ac81-d43ff640d51c |          10067

// find id
BEGIN;
SET LOCAL enable_indexscan = off;
SET LOCAL enable_bitmapscan = off;
SET LOCAL enable_indexonlyscan = off; 
select * FROM report_vulnerability_record WHERE report_uuid = '4f00051a-26e4-4769-ac81-d43ff640d51c' and vuln_record_id = 10067;
ROLLBACK;
   id    |             report_uuid              | vuln_record_id 
---------+--------------------------------------+----------------
 4617041 | 4f00051a-26e4-4769-ac81-d43ff640d51c |          10067
 4619252 | 4f00051a-26e4-4769-ac81-d43ff640d51c |          10067
(2 rows)
// delete data
registry=# BEGIN;
SET LOCAL enable_indexscan = off;
SET LOCAL enable_bitmapscan = off;
SET LOCAL enable_indexonlyscan = off; 
DELETE FROM report_vulnerability_record WHERE  id = 4619252;
COMMIT;
BEGIN
SET
SET
SET
DELETE 1
COMMIT
// alter teble
ALTER TABLE report_vulnerability_record ALTER COLUMN id TYPE BIGINT;
```

**Comment by kycheng** [comment]
When executing 0090_2.6.0_schema.up.sql, a new error is encountered:

```
registry=# CREATE INDEX IF NOT EXISTS idx_execution_vendor_type_vendor_id ON execution (vendor_type, vendor_id);
ERROR:  failed to find parent tuple for heap-only tuple at (0,60) in table "execution"
registry=# 
```

Similar to the previous problem, it can be solved in the same way.

It wasn't the best way to fix it at the time. We should try to reimport the database, to fix it. As this blog puts it: https://dba.stackexchange.com/questions/62819/what-does-error-failed-to-find-parent-tuple-for-heap-only-tuple-at-1192248-5

**Comment by AllForNothing** [comment]
Harbor only supports upgrading cross less the 2 versions, so you need to upgrade Harbor to 2.4 first then 2.6:
2.2.x => 2.4.x =>2.6.4

**Comment by danielzhanghl** [comment]
if that is k8s, you could enable enableMigrateHelmHook, that will migrate the DB before upgrade first.

**Comment by kycheng** [comment]
> Harbor only supports upgrading cross less the 2 versions, so you need to upgrade Harbor to 2.4 first then 2.6: 2.2.x => 2.4.x =>2.6.4

I have confirmed by backing up the data before the upgrade that there is duplicate key data in the database before the upgrade, and this problem is not caused by the upgrade.

Thanks Reply.

**Comment by kycheng** [comment]
> if that is k8s, you could enable enableMigrateHelmHook, that will migrate the DB before upgrade first.

Yes, deployed in k8s, I will optimize this problem.

**Comment by kycheng** [comment]
> if that is k8s, you could enable enableMigrateHelmHook, that will migrate the DB before upgrade first.

sorry, I have a question, what are the design of enableMigrateHelmHook and the advantages of running Migrate in harbor-core?
