### ISSUE TITLE
when I use crictl pull image，the task will be failed

### ISSUE THREAD

**Issue by hiddletian** [goharbor/harbor#19225]
when I use crictl pull image from harbor，this task will be failed. I want to know why?

The log is "failed to copy: read tcp 192.168.10.1:35964--> 10.0.1.2:80: read: connection reset by peer

-----------------------------------------------------------------------------------------------------
when I use nerdctl pull image from harbor，this task will be success

**Comment by wy65701436** [comment]
please provide the incremental core log when you're pulling with crictl
