### ISSUE TITLE
Can not upgrade harborcluster  "admission webhook "vharborcluster.kb.io" denied the request:"

### ISSUE THREAD

**Issue by adcsikos** [goharbor/harbor#19223]
Dear All,

Harbor version: 2.6.4
K8s version: 1.23
Argocd version: 2.8.0

Can someone help me about this issue.:

We use harbor (deployed with argocd) and iI would like to upgrade the version. But whenever i tried it i got the following error message:

This is the error message from argocd:

"one or more objects failed to apply, reason: admission webhook "vharborcluster.kb.io" denied the request: HarborCluster.goharbor.io "harbor-server" is invalid: spec.version: Invalid value: "2.7.2": unknown version 2.7.2."

This Version is available for harbor, so i do not know why the admission webhook do not accept this.

Thank you!
Adam

**Comment by lengrongfu** [comment]
you can to https://github.com/goharbor/harbor-operator ask this issue.

**Comment by adcsikos** [comment]
@lengrongfu THank you, than I will close this issue here!
