### ISSUE TITLE
Clarify the scheduled replication job format

### ISSUE THREAD

**Issue by j-zimnowoda** [goharbor/harbor#19221]
How can we help you?

In Harbor replications, you can create a scheduled Replication Rule. Unfortunately the correct format of the scheduled trigger mode is not clear. 
From the screenshot an example and description suggest that there are 6 entries `* * * * * *` but this is not cron format - The cron job has only 5 entries. Similary the Harbor documentation is talking about cron job: 
> Scheduled: Replicate the resources periodically by defining a cron job. 

Which format is correct?

https://goharbor.io/docs/2.2.0/administration/configuring-replication/create-replication-rules/ 

<img width="387" alt="image" src="https://github.com/goharbor/harbor/assets/17126497/08909681-058a-4be6-b41e-4c5ce14ab85d">

**Comment by chlins** [comment]
The mentioned cron might differ from the cron expression used in Linux. Please refer to the tooltip displayed on the Harbor UI for the correct format.

**Comment by AllForNothing** [comment]
@j-zimnowoda Since 2.9.x, the first filed is fxied to `0`.  We don't want users to set too frequent scheduled tasks

**Comment by j-zimnowoda** [comment]
Thanks for clarification. Good idea with not allowing cron jobs every second.
