### ISSUE TITLE
Feature Request: Allow Robot Accounts to manage labels

### ISSUE THREAD

**Issue by mmckeen** [goharbor/harbor#19235]
Right now, it doesn't seem that Robot Accounts have full API permissions.  In particular, it doesn't seem like they are able to create/delete labels at the global scope.

Would this be possible to add?

As a possible workaround, are Robot Accounts allowed to manage labels at the project scope?

**Comment by mmckeen** [comment]
Looks like this is possible via https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533

**Comment by mmckeen** [comment]
This may be possible via? https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533

**Comment by wy65701436** [comment]
you can add comment to this [issue](https://github.com/goharbor/harbor/issues/8723), and we will use that issue to track robot permissions problem.

**Comment by Vad1mo** [comment]
duplicate of #14145
