### ISSUE TITLE
Warning message found after upgrading to version 2.8.4 and enabling the cache feature

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor#19236]
Hi, I upgraded my harbor to version 2.8.4 and enabled the cache feature utilizing redis provided by harbor to improve speed.
Since then, harbor is working fine, but I'm seeing a lot of warning logs in harbor-core.
Do you have any idea what is causing the logs and how to resolve the warnings?

`[WARNING] [/server/registry/manifest.go:96]: failed to get manifest from cache, error: key not found:redis: nil`

My information is as follows
Installed and using harbor helm.
redis is using aws elasticache. (Engine version: 6.0.5)

Let me know if there is any additional information I need to debug.

**Comment by chlins** [comment]
The log just indicates that the cache missed for the first time then will fallback to registry and cache it in redis, so you can ignore it currently, and we have improved the log level to debug in the v2.9 to reduce the noise.

**Comment by wy65701436** [comment]
close it bases on the above comments.

**Comment by derekcha** [comment]
Thanks for the answer
