### ISSUE TITLE
The number of replication tasks is limited to 100

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#19237]
harbor version:  v2.4.0
![image](https://github.com/goharbor/harbor/assets/31399968/fb300988-3071-4164-b855-0e7220a54852)

Copy 100 tasks at a time, many images can not be downloaded, how to lift the limit?
Thinks!!

**Comment by wy65701436** [comment]
We have addressed various performance issues related to replication, particularly when dealing with a large number of candidates. We recommend upgrading your Harbor to the latest version and reopening it to see if the problem persists.
