### ISSUE TITLE
How to enable persistence when using Azure storage account with Harbor?

### ISSUE THREAD

**Issue by mohamedFaris47** [goharbor/harbor#19248]
Hi,
I have Harbor registry linked to and Azure storage account for storing the images. Its working fine, and I can pull and push images. However, if I delete the Harbor deployment and redeploy again connecting it to the same storage account it doesn't detect already present images and projects, and Harbor is deployed empty.
The question is, can Harbor detect these already created images and restore them after the fresh install, or this is not gonna work?

Thanks.

**Comment by stonezdj** [comment]
You might have to backup both image and database data to restore the previous Harbor instance. or you can setup a standalone distribution registry point to the same storage location and replicate it to the existing harbor instance. but it can restore previous images only.

**Comment by mohamedFaris47** [comment]
Thanks for the reply.
You mean if I backup the images in another storage account for example and then I deploy harbor and copy the images form the backup storage account to the harbor storage account it should work and Harbor can detect them, right?
