### ISSUE TITLE
Replicating harbor with harbor not working #2

### ISSUE THREAD

**Issue by ffppmm** [goharbor/harbor#19244]
Hallo,

as mentioned here https://github.com/goharbor/harbor/issues/18862 we have Problems replicating harbor as docker repository.

We followed all your recommendations and still aren't able to replicate. Here my last comment about this issue:
> Hi,
> 
> I was on holiday, sry for the late answer. We testet with the above permissions and I still get "401 Unauthorized", so listing the _catalog still doesn't work 😞
> 
> Command:
> 
> ```shell
> cat harbor.txt | curl -k -K - --request GET  --url "https://registry_fqdn/api/v2.0/robots/11"  | python -m json.tool
> ```
> 
> Output:
> 
> ```json
> {
>     "creation_time": "2023-06-13T07:13:56.812Z",
>     "description": "System Robot Account for Tests",
>     "disable": false,
>     "duration": -1,
>     "editable": true,
>     "expires_at": -1,
>     "id": 11,
>     "level": "system",
>     "name": "somename_modified",
>     "permissions": [
>         {
>             "access": [
>                 {
>                     "action": "list",
>                     "resource": "repository"
>                 },
>                 {
>                     "action": "pull",
>                     "resource": "repository"
>                 },
>                 {
>                     "action": "read",
>                     "resource": "artifact"
>                 },
>                 {
>                     "action": "list",
>                     "resource": "artifact"
>                 },
>                 {
>                     "action": "list",
>                     "resource": "tag"
>                 },
>                 {
>                     "action": "read",
>                     "resource": "catalog"
>                 }
>             ],
>             "kind": "project",
>             "namespace": "*"
>         }
>     ],
>     "update_time": "2023-07-08T08:39:46.200Z"
> }
> ```
> 
> proxy logs (only replaced IPs):
> 
> ```
> Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /v2/ HTTP/1.1" 401 76 "-" "Go-http-client/1.1" 0.002 0.001 .
> Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /service/token?scope=registry%3Acatalog%3A%2A&service=harbor-registry HTTP/1.1" 200 967 "-" "Go-http-client/1.1" 0.016 0.017 .
> Jul 28 09:08:17 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /v2/_catalog?n=1000 HTTP/1.1" 401 108 "-" "harbor-registry-client" 0.003 0.003 .
> Jul 28 09:08:42 172.21.0.1 proxy[1292]: XXX.XXX.XXX.XXX - "GET /api/version HTTP/1.1" 200 19 "-" "Go-http-client/1.1" 0.004 0.003 .
> ```
> 
> Can you help, regards Philipp

Can you please help,
regards Philipp

**Comment by chlins** [comment]
Could you provide the registry instance configuration, did you choose the registry to Harbor when add the registry?

**Comment by ffppmm** [comment]
Hello,

as discussed here (https://github.com/goharbor/harbor/issues/18862) we want harbor to act like a "normal" Docker registry, because we don't know which registry our customers will use for replication. So we are setting up a second harbor to test this.

We try to replicate a 2 projects {PROJECTNAME1,PROJECTNAME2}/* and when adding the 1 harbor registry we use as source "Docker Registry".

About your questions:

> did you choose the registry type to Harbor when add the registry?
No we wan't to use "Docker Registry"
> please also provide more logs when replicated error occurs
What logs to you need, all containers?

regards Philipp

**Comment by chlins** [comment]
@YangJiao0817 Please help to give a correct example payload for creating a robot account with catalog permission, thanks!

**Comment by YangJiao0817** [comment]
@chlins Please confirm if this case is supported? I am using admin user and still not able to replication.

**Comment by ffppmm** [comment]
Hi,
could you please give us information on and when you are planning to support listing of the _catalog as non admin user?
If not, or not soon, we are forced to change to a different registry solution - although we would like stay with harbor!

regards Philipp

**Comment by chlins** [comment]
I've tried to figure out the root cause, if the user chooses the registry type to 'Docker Registry' then the replication will use the basic auth to exchange the token for authorization, but currently design the token seems no way to access the catalog API because the backend bypass this API for v2 token auth, so whatever admin or non-admin user uses the 'Docker Registry' to replicate from Harbor instance will fail on the catalog API with 401 unauthorized.

**Comment by ffppmm** [comment]
Hi,

thanks for your answer, is there any solution, for this?

regards Philipp

**Comment by ffppmm** [comment]
Hi,
> so whatever admin or non-admin user uses the 'Docker Registry' to replicate from Harbor instance will fail on the catalog API with 401 unauthorized.

any news on this? If its correct understood using harbor as a docker registry is currently broken 😞 

Any plans to fix this?
regards Philipp

**Comment by chlins** [comment]
> Hi,
> 
> > so whatever admin or non-admin user uses the 'Docker Registry' to replicate from Harbor instance will fail on the catalog API with 401 unauthorized.
> 
> any news on this? If its correct understood using harbor as a docker registry is currently broken 😞
> 
> Or is the replication in this corner case broken, if you use harbor to harbor replication with the source harbor registry acting as a Docker registry?
> 
> Any plans to fix this? regards Philipp

That's currently why there are two registry type, one for harbor and one for docker registry, the docker registry is a common native v2 registry client, it may work for some registries such as harbor, but suggests using the determinate registry type as they are designed for handling the corner case correctly for adapter.

**Comment by chlins** [comment]
The issue you encountered actually belong to the design limitation, that's the v2 token in harbor cannot list the catalog API, open here for more discussions.

**Comment by ffppmm** [comment]
Hi,

thanks for your answer. So to clarify "things" for me.

It is a design limitation of harbor that the v2 token cannot list the catalog API?

regards Philipp

**Comment by ffppmm** [comment]
Hi,

any News, we still want to use harbor acting as Docker registry 😄 

regards Philipp
