### ISSUE TITLE
no task found for execution: SYSTEM_ARTIFACT_CLEANUP:10237

### ISSUE THREAD

**Issue by rekha-prakash-maersk** [goharbor/harbor#19253]
Noticing this error when the system artifact cleanup job starts and it seems to be auto recovering, but I could not find the actual cause of this error - `no task found for execution: SYSTEM_ARTIFACT_CLEANUP:10237`

Error thrown from job service -https://github.com/goharbor/harbor/blob/main/src/jobservice/sync/schedule.go#L392

PR of system artifact cleanup feature - https://github.com/goharbor/harbor/pull/16879

<table><tr><td>
2023-08-22T09:00:01Z [INFO] [/pkg/task/sweep_job.go:180]: [SYSTEM_ARTIFACT_CLEANUP] end to sweep, 0 executions were deleted in total, elapsed time: 1.052451ms  </td></tr>
<tr><td> 2023-08-22T09:00:01Z [INFO] [/pkg/task/sweep_job.go:160]: [SYSTEM_ARTIFACT_CLEANUP] listed 0 candidate executions for sweep</td></tr>
<tr><td> 2023-08-22T09:00:01Z [INFO] [/pkg/task/sweep_job.go:150]: [SYSTEM_ARTIFACT_CLEANUP] start to sweep, retain latest 50 executions </td>  </tr>
<tr><td> 2023-08-22T08:32:24Z [ERROR] [/jobservice/sync/schedule.go:238]: no task found for execution: SYSTEM_ARTIFACT_CLEANUP:10237 </td></tr>
<tr><td>  2023-08-22T08:31:23Z [ERROR] [/jobservice/sync/schedule.go:238]: no task found for execution: SYSTEM_ARTIFACT_CLEANUP:10237 </td></tr>
<tr><td> 2023-08-22T08:31:23Z [INFO] [/jobservice/worker/cworker/c_worker.go:445]: Register job *systemartifact.Cleanup with name SYSTEM_ARTIFACT_CLEANUP</td></tr> </table>

**Comment by chlins** [comment]
Which harbor version do you use?

**Comment by rekha-prakash-maersk** [comment]
@chlins I am using v2.8.3

**Comment by chlins** [comment]
Is your harbor a fresh install instance or upgrade from lower version?

**Comment by rekha-prakash-maersk** [comment]
@chlins its an upgarde from 27.0 to 2.8.3, but noticed this behaviour in both versions

**Comment by chlins** [comment]
Please try to execute the following SQLs in the harbor database and paste the outputs.
```sql
select * from schedule where vendor_type='SYSTEM_ARTIFACT_CLEANUP';
```
```sql
select * from execution where vendor_type='SYSTEM_ARTIFACT_CLEANUP';
```
```sql
select * from task where vendor_type='SYSTEM_ARTIFACT_CLEANUP';
```
