### ISSUE TITLE
Harbor proxy cache fails pull instead of returning locally cached copy when upstream returns 429

### ISSUE THREAD

**Issue by soapiestwaffles** [goharbor/harbor#19257]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Expected behavior would be: if an error occurs with the upstream, including getting an HTTP 429 from rate limiting, Harbor should still return the locally cached version of the image on the pull. Actual behavior is Harbor will return an error and your pull will fail. 

As our case, DockerHub is returning HTTP 429, Harbor will fail the pull with the error `429 Too Many Requests - Server message: unknown: too many requests to upstream registry`.

**Steps to reproduce the problem:**
Try and pull an old, long-time existing image through a proxy cache to Dockerhub where the image has already been cached locally but its call to Dockerhub returns an HTTP 429.

**Versions:**

- harbor version: [v2.8.2-f8282a56]

**Comment by wy65701436** [comment]
By design, harbor will serve the local cached artifact if it has. And could you please double confirm whether this image has a tag or is it purged by the default retention policy of proxy cache project?
