### ISSUE TITLE
Error level logging for OPTIONS method without auth header

### ISSUE THREAD

**Issue by rekha-prakash-maersk** [goharbor/harbor#19254]
Noticing the OPTIONS method also required to have authentication token , but can it be added to whitelist [here](https://github.com/goharbor/harbor/blob/main/src/jobservice/api/router.go#L74-L82) or changed to WARNING instead of ERROR level log.

`2023-08-22T08:24:56Z [ERROR] [/jobservice/api/router.go:82]: Serve http request 'OPTIONS /' failed with error: {"code":10011,"message":"unauthorized","details":"header 'Authorization' missing"}`

**Comment by wy65701436** [comment]
which endpoint are you pointing to? Is it the rest api of jobservice?

**Comment by rekha-prakash-maersk** [comment]
@wy65701436 Observed this error in the logs, but not finding the actual route information in logs.
