### ISSUE TITLE
Docker push results in 403 forbidden error

### ISSUE THREAD

**Issue by suprita23** [goharbor/harbor#19291]
I have Harbor Version v2.7.0-864aca34

When I build a new image and push it to goharbor, I get 403 forbidden error.
The user I use to push is an admin user. It had all the rights.

Here are the logs
>> ╰─➤ docker build -t reg2-edge.dragonfly-dev.com/dragonfly/sritest:1.0.0 .                                                                                                   125 ↵
[+] Building 0.6s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                          0.2s
 => => transferring dockerfile: 70B                                                                                                                                           0.1s
 => [internal] load .dockerignore                                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                               0.1s
 => [internal] load metadata for docker.io/library/busybox:latest                                                                                                             0.4s
 => [1/2] FROM docker.io/library/busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79                                                              0.0s
 => CACHED [2/2] RUN echo "Test"                                                                                                                                              0.0s
 => exporting to image                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                       0.0s
 => => writing image sha256:d40424a4a4471e232a20b7411e030e0f096ec91268c9875b01f9c8992ecf0b4f                                                                                  0.0s
 => => naming to reg2-edge.dragonfly-dev.com/dragonfly/sritest:1.0.0                                                                                                          0.0s

>>╰─➤  docker push reg2-edge.dragonfly-dev.com/dragonfly/sritest:1.0.0
The push refers to repository [reg2-edge.dragonfly-dev.com/dragonfly/sritest]
6fbd455003f7: Pushing  3.584kB
3d24ee258efc: Pushing [==================================================>]  4.492MB
error parsing HTTP 403 response body: unexpected end of JSON input: ""

**Comment by wy65701436** [comment]
did you perform the docker login? and can you share the core log?
