### ISSUE TITLE
Harbor OIDC Error v.2.7.2

### ISSUE THREAD

**Issue by DudeCalledBro** [goharbor/harbor#19290]
Hello! We freshly installed a new Harbor Instance with S3 Storage Service. We are using DexIdP for User-Authentication.

Unfortunately we ran into a strange Issue. The Authentication works and you can create Projects, but as soon as you want to view further Details (click on the Project) we get an Error-Code.

```
chartmuseum        | {"L":"ERROR","T":"2023-09-01T13:13:51.815Z","M":"[54] Request served","path":"/library/index.yaml","comment":"","clientIP":"{}","method":"GET","statusCode":500,"latency":"12.847206ms","reqID":"xyz"}
chartmuseum        | {"L":"ERROR","T":"2023-09-01T13:13:51.815Z","M":"[56] InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: xyz, host id: ","repo":"test","reqID":"xyz"}
``` 

Thank you! :)

**Comment by DudeCalledBro** [comment]
Update: We have testet Version 2.9.0 and the problem does not occur anymore. Unfortunately we are unable to upgrade because of the chartmuseum.

**Comment by wy65701436** [comment]
since the chartmuseum is not in the support scope, we suggest you to migrate your charts to the OCI compatible charts, and please refer to this [page](https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor).
