### ISSUE TITLE
What user should I use for harbor container registry login with bearer token?

### ISSUE THREAD

**Issue by PSKP-95** [goharbor/harbor#19297]
I want to get a temporary scoped token for a repository for the harbor. Previously we were using ACR with  `00000000-0000-0000-0000-000000000000` as username with JWT as password.

I want to get a temporary scoped token for a repository for the harbor. Previously we were using ACR. With ACR, we were using 00000000-0000-0000-0000-000000000000 as username with JWT as password.

```
curl --location 'https://example.com/service/token?service=harbor-registry&scope=repository%3Adevlpc1%2Fnginx%3Apush' \
--header 'Authorization: Basic aGFyYmFkbWluOmFzZHNld2ZlZkAyMzJB'
```

I can use that JWT as a bearer token in Postman and get a 2xx response. like below

```
curl --location 'https://example.com/v2/' --header 'Authorization: Bearer <jwt>'
```

But don't know what user should I use for logging to docker cli with this JWT as a password.

```
docker login -u <what_user_here> -p <JWT> <harbor_host>
```

**Comment by stonezdj** [comment]
No username and password required for temporary user to get the service token.

**Comment by PSKP-95** [comment]
@stonezdj So how will I use docker cli with JWT which I got from /service/token endpoint?
