### ISSUE TITLE
Wrong scope/access in JWT token when token created with /service/token end point

### ISSUE THREAD

**Issue by PSKP-95** [goharbor/harbor#19298]
**Expected behavior & Actual behavior**
When I run the following curl, I should get JWT with the correct access scope.

```
curl --location 'https://example.com/service/token?service=harbor-registry&scope=repository%3Adevlpc1%2Fnginx%3Apush' \
--header 'Authorization: Basic <base64_username_password>' \
```

But when I checked in jwt.io, it has excessive scope.

Expired JWT,

```
eyJhbGciOiJSUzI1NiIsImtpZCI6IlpSQ1k6S0lRMzpKV1pFOllEWU86T1hBTTpXSEpGOlEyVFA6UldTSzpLWU02OkJGM0c6QkMyNTpBR0Q0IiwidHlwIjoiSldUIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE2OTM3NTI1NTMsIm5iZiI6MTY5Mzc1MDc1MywiaWF0IjoxNjkzNzUwNzUzLCJqdGkiOiJya2xQUTBWeE15M0RKdmdwIiwiYWNjZXNzIjpbeyJ0eXBlIjoicmVwb3NpdG9yeSIsIm5hbWUiOiJkZXZscGMxL25naW54IiwiYWN0aW9ucyI6WyJkZWxldGUiLCJwdWxsIiwicHVzaCIsIioiXX1dfQ.IDIqEUGyQQCvksMCiQAIaixO_WecBh9Uh4J5c8FFdrapWbLejwkLoBzUnt1iEhm2VjPPAk9fYYMbIHHGAzUqEXQfvjjxibCBnYeT_3Zz0JFTGKQuJuhqoCF9s9OQGdf64mIluF4rMwQjzIMoocr1uRrwJnLwdt5qJBoI85b6QDND2ipaXK45Fi9hNs96JxV9soAsI1N2FfjZ7g1CdXSBR0x2NUw8kneR4e_X3kZpq8zGJy-ZTo9LAT1b7poJ67FSWl6zTrp4XJ1EOcz7RvnrMGj9ffKCX_Rj_s3w2jUasfR6n4BVt2AZl2xhY-6dtPpUqA2wgPILW19OzPahon_Oyw
```

![image](https://github.com/goharbor/harbor/assets/35999328/af768144-e2cc-43f0-b2bd-a61da04434f9)

**Steps to reproduce the problem:**

- Use `/service/token?service=harbor-registry&scope=repository:devlpc1/nginx:push` for creating JWT
- Go to jwt.io and check the access scope.

**Versions:**

This harbor is running in rancher. I don't know much about it. But adding image versions.
- goharbor/harbor-core:v2.8.2
- goharbor/harbor-db:v2.8.2
- goharbor/harbor-jobservice:v2.8.2
- goharbor/notary-server-photon:v2.8.2
- goharbor/notary-signer-photon:v2.8.2
- goharbor/harbor-portal:v2.8.2
- goharbor/registry-photon:v2.8.2
- goharbor/redis-photon:v2.8.2
- goharbor/trivy-adapter-photon:v2.8.2

**Additional context:**

**Comment by wy65701436** [comment]
what's your account type, is it an project admin or system admin?
