### ISSUE TITLE
used quota is incorrect

### ISSUE THREAD

**Issue by shusley244** [goharbor/harbor#19295]
When I push an image, I receive a notification saying that there is insufficient space quota and the push fails. 

`denied: adding 510.7 MiB of storage resource, which when updated to current usage of 10.0 GiB will exceed the configured upper limit of 10.0 GiB.`

Before I push the image, the project used space is not reached the quota limit, But now the push fails and the used space is reached the limit.

However, the project used space quota does not get restored even after performing garbage cleanup.
![image](https://github.com/goharbor/harbor/assets/35093945/95e60f22-8c2a-45b1-a25e-e8355dbf75dd)

Harbor version is v2.8.0.  The project used quota statistics are incorrect，how can i restore it？

**Comment by stonezdj** [comment]
Because GC has a time window for 2 hours, you need to wait for more than 2 hours to run the GC again.

**Comment by shusley244** [comment]
ok, thank you
