### ISSUE TITLE
Security Hub for non Admins

### ISSUE THREAD

**Issue by Lima118** [goharbor/harbor#19309]
Hi!

It would be a useful feature for us if not only Admins could access the Security Hub.
Our security team at out company would like to monitor the CVEs in Harbor. Right now our only solution is to give them Developer permission on all Projects to export CVEs and then they make reports out of them.

It would be easier if they could look at the Security Hub and filter the Projects based on Severity. Get a more visual and comprehensive look.

We use LDAP integration. Maybe a suitable solution would be to create a new field for LDAP Group Security DN.
Thoso who are member of the defined group would get access to Security Hub.

Thanks,
Lima

**Comment by AllForNothing** [comment]
We will expose the permissions of the Security Hub for the system robot accounts on the UI in 2.10.

in 2.9, you can create a system robot account with below permissions by API call:
`{
    "disable": false,
    "duration": -1,
    "editable": true,
    "expires_at": -1,
    "level": "system",
    "name": "somename_modified",
    "permissions": [
        {
            "access": [
                {
                    "action": "security-hub",
                    "resource": "read"
                },
                {
                    "action": "security-hub",
                    "resource": "list"
                },
            ],
            "kind": "system",
            "namespace": "/"
        }
    ]
}`

**Comment by Lima118** [comment]
Unfortunate, but understandable.
Thank you for the fast reply. Gonna look into the API call, see if we can use it in an automated reporting logic.

Best,
Lima

**Comment by dmaggo** [comment]
Hello, 
we would appreciate this feature also. Is it planned for future version? 
In general it would be nice to have different levels for administrative view. At least a read only partially. 

> Hi!
> 
> It would be a useful feature for us if not only Admins could access the Security Hub. Our security team at out company would like to monitor the CVEs in Harbor. Right now our only solution is to give them Developer permission on all Projects to export CVEs and then they make reports out of them.
> 
> It would be easier if they could look at the Security Hub and filter the Projects based on Severity. Get a more visual and comprehensive look.
> 
> We use LDAP integration. Maybe a suitable solution would be to create a new field for LDAP Group Security DN. Thoso who are member of the defined group would get access to Security Hub.
> 
> Thanks, Lima
