### ISSUE TITLE
Harbor registry audit_log table's "id" field overflow after integer limit reach

### ISSUE THREAD

**Issue by jhasu** [goharbor/harbor#19302]
audit_log table logs which logs user activity on the registry has below schema.
registry=> \d audit_log
                                          Table "public.audit_log"
    Column     |            Type             | Collation | Nullable |                Default
---------------+-----------------------------+-----------+----------+---------------------------------------
 id            | integer                     |           | not null | nextval('audit_log_id_seq'::regclass)
 project_id    | integer                     |           | not null |
 operation     | character varying(20)       |           | not null |
 resource_type | character varying(255)      |           | not null |
 resource      | character varying(1024)     |           | not null |
 username      | character varying(255)      |           | not null |
 op_time       | timestamp without time zone |           |          | now()
Indexes:
    "audit_log_pkey" PRIMARY KEY, btree (id)
    "idx_audit_log_op_time" btree (op_time)

As the "id" field in the table is a sequence (integer type), it overflows after the value reaches the integer limit (2^31). We recently faced this issue in our Harbor instance.
Altering this table by updating this column "id" to higher capacity type (e.g. bigint) would solve the issue, but we are worried about the future Harbor upgrade scenario. This alteration would put us at risk of upgrade failures.
What is your recommendation or suggestion here? Is there a better way to handle this considering above.

**Comment by stonezdj** [comment]
It should be bigint

**Comment by lengrongfu** [comment]
this maybe is beego orm bug, beego orm current default use `serial` type, serial max values is `2147483647`,  this should is `bigserial`.

https://github.com/beego/beego/issues/5398

**Comment by lengrongfu** [comment]
i can do it.

/assign

**Comment by jhasu** [comment]
Can you also put your view on the Harbor upgrade kind of scenario? Will the changes make it backward incompatible?

**Comment by stonezdj** [comment]
You could manually update it with this SQL
```
DO
$$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'audit_log'
              AND column_name = 'id'
              AND data_type = 'integer'
        ) THEN

            CREATE TABLE audit_log_backup
            (
                id             BIGSERIAL PRIMARY KEY NOT NULL,
                project_id     int NOT NULL,
                operation      varchar(20) NOT NULL,
                resource_type  varchar(255) NOT NULL,
                resource       varchar(1024) NOT NULL,
                username       varchar(255) NOT NULL,
                op_time        timestamp default CURRENT_TIMESTAMP
            );

            INSERT INTO audit_log_backup (project_id, operation, resource_type, resource, username, op_time)
            SELECT project_id, operation, resource_type, resource, username, op_time
            FROM audit_log;

            DROP TABLE audit_log;
            ALTER TABLE audit_log_backup RENAME TO audit_log;

            CREATE INDEX IF NOT EXISTS idx_audit_log_op_time ON audit_log (op_time);
            CREATE INDEX IF NOT EXISTS idx_audit_log_op_time ON audit_log (op_time);
            CREATE INDEX IF NOT EXISTS idx_audit_log_project_id_optime ON audit_log (project_id, op_time);

        END IF;
    END;
$$
```

**Comment by stonezdj** [comment]
Because the amount of audit logs is huge in typical user env, it takes a long time to migrate the previous ID to new ID,  we should avoid doing it in the migrate script. so provide the current workaround only.

**Comment by MinerYang** [comment]
closed by fix.
