### ISSUE TITLE
Configuration of harbor database upgrade and db health check time during k8s deployment.

### ISSUE THREAD

**Issue by kycheng** [goharbor/harbor#19300]
Harbor uses the following method to upgrade the database：

https://github.com/goharbor/harbor/blob/d381185908a1e369d6946597748fb214f87c0251/make/photon/db/upgrade.sh#L31-L37

I have a little concern about this, when I deploy in k8s, the health check of db-pod configuration:

https://github.com/goharbor/harbor-helm/blob/86dd759ac03e9c781c25a6c0d71ec8d95368fb32/templates/database/database-ss.yaml#L79-L95

When our database is large enough, the harbor upgrade cannot complete the upgrade within the health check cycle, will it cause the db to restart continuously. We had to manually intervene to complete the upgrade.

Do we have data to illustrate the relationship between database size and health check time configuration?

Should we consider putting the database upgrade into a job or an init container?

**Comment by stonezdj** [comment]
Maybe you have to update the liveness probe when it takes a long time to migrate the database. 
```
initialDelaySeconds: 300
```
Do we have data to illustrate the relationship between database size and health check time configuration? -- no, it maybe depends on your env and the data file size.

**Comment by kycheng** [comment]
> Maybe you have to update the liveness probe when it takes a long time to migrate the database.
> 
> ```
> initialDelaySeconds: 300
> ```
> 
> Do we have data to illustrate the relationship between database size and health check time configuration? -- no, it maybe depends on your env and the data file size.

Thanks for the reply. 

I think configuring the survival probe is a temporary solution. I don’t know how long it will take to upgrade the database before the upgrade. If the upgrade takes longer than the time I set, I will need a manual intervention to continue the upgrade. Is it possible to have a permanent solution?
