### ISSUE TITLE
What versions of postgresql does harbor 2.9.0 support

### ISSUE THREAD

**Issue by nbjohnson** [goharbor/harbor#19318]
I am using an external postgresql server and when attempting to upgrade to 2.9.0 I get a `failed to upgrade schema` and `failed to migrate the database`. Taking a look at the sql migration script here: https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_2.9.0_schema.up.sql I see it uses `jsonb_path_exists` on line 5 which from what I can see in the postgres docs was introduced in postgres 12

The only info on supported postgres versions I can find is in the harbor upgrade guide: https://goharbor.io/docs/2.9.0/administration/upgrade/ which states that in v2.5 and newer you need at least postgres 10. I am running postgres 11 and my upgrade failed.

What is the official supported list of postgres versions for harbor? And unless I am just missing it can that information be published in an easily findable location?

**Comment by wy65701436** [comment]
Good catch @nbjohnson , we will have an update in the release notes to mention the supported pg version. And now in the v2.9.0, the default the pg version is 14.5.

**Comment by wy65701436** [comment]
Close it by updating the release notes.

**Comment by viceice** [comment]
you should also update the upgrade guide docs mentioned in issue description

**Comment by nbjohnson** [comment]
@wy65701436 Thanks for the info of postgres 12 being the new minimum version. A second question, I do see that in 2.9.0 postgres 14 is now the bundled version, but does harbor support a newer version than the bundled version? such as postgres 15?
