### ISSUE TITLE
Migration from swift

### ISSUE THREAD

**Issue by viktor-f** [goharbor/harbor#19317]
According to [this PR](https://github.com/distribution/distribution/pull/3982) it seems like registry is dropping the support for swift.

We currently use the swift support for some of our harbor installations and will then need to migrate to using s3 instead. I'm first of all wondering if you will provide any migration path for harbor installations that need to move from swift to s3.

I did some quick tests and I noticed that one difference is that the swift version will keep some files in the object storage under `/files/docker/` while the s3 version keeps it in `/docker/`. So to migrate one would at least need to move those files. In my test I moved those files, changed registry config to use s3 and could then at least pull an image from harbor. Do you know of any other difference between how the files are stored?
We have earlier noticed that copying files from a harbor object storage bucket with rclone using the s3 api leads to some problems if harbor have used the swift api. So I'm a bit afraid that just moving the files in the same bucket and changing the registry config will lead to some other problems later on, simply because some files were created with swift.

Any other thoughts related to this topic would also be appreciated. Let me know if I should elaborate on anything as well.

**Comment by wy65701436** [comment]
As for the migration, I figure that you can copy all files from swift to S3. The key point is ensuring that the structure of files and directories remains consistent.

It is crucial to avoid making any changes to your database, whether it is internal or external, as part of the migration.

The changes in the upstream will be implemented in v3.0, but this update is not expected to occur in the near future.

**Comment by viktor-f** [comment]
Thanks for the reply.
Since I found at least one thing that was different in the file structure/naming in object storage between Harbor that is using swift and Harbor that is using s3 I was wondering if there was any other differences that would be important to keep in mind. Do you know of anything else?
