### ISSUE TITLE
Harbor processes are running as root

### ISSUE THREAD

**Issue by hmahmood** [goharbor/harbor#1933]
All the harbor containers/processes seem to be running as root and not as a non-privileged user.

**Comment by sigsbee** [comment]
you can add a user to docker group and install harbor as non-privileged user, remember to modify harbor.cfg to avoid some permission issue.(you can simply change the owner of /data to the user that you want to install  harbor)

**Comment by reasonerjt** [comment]
This has been fixed after we deprivilege user in Harbor's images.
