### ISSUE TITLE
Fix string in swagger.yaml

### ISSUE THREAD

**Issue by alexandre-k** [goharbor/harbor#19333]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The URL encoding in swagger.yaml for "/" should be "%2F" but is set to "%252F". "%252F" is actually the URL encoding for "%2F". 

**Steps to reproduce the problem:**
Search for "%252F" [here](https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml)

**Versions:**
Please specify the versions of following systems.

Not applicable

**Additional context:**
String found in branch with tag 2.9.0 and main.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Pull request:**
#19332

**Comment by wy65701436** [comment]
We took this step because both Beego and Swagger decode the URL. Therefore, the double encode is needed.

**Comment by Vad1mo** [comment]
@wy65701436 this sound like even a bigger bug? There is also no explanation for the user in the docs on why he has to do it.
