### ISSUE TITLE
Using the same S3 bucket for UAT Testing

### ISSUE THREAD

**Issue by Entropy70** [goharbor/harbor#19344]
Hi, I was wondering if it would be possible to conduct a UAT for next version of Harbor using the same S3 bucket. 
The plan is to create a read replica of current production database, point the new version harbor to this read replica and run it in read only mode while being connected to the same s3 bucket as the production Harbor.

Is this plan feasible or Harbor changes things internally in S3 buckets, requiring a replicated S3 bucket instead of using the same one?
Our upgrade path is v2.2.0 to v2.3.5

Thanks

**Comment by stonezdj** [comment]
If the UAT env is read-only mode, and replicate the current database, Use the same s3 bucket should work.  don't forget to sync the following files if harbor is installed with docker-compose, 
```
/data/secret/core/private_key.pem
/data/secret/registry/root.crt
/data/secret/keys/secretkey
```
and keep the same CSRF_KEY in /common/config/core/env file 
If the harbor installed with harbor-helm, you should sync the configmap

**Comment by Entropy70** [comment]
Hi @stonezdj , thanks for the answer. 

Yes it would be a read only env and plan to use a replica of production database. 
We are deploying harbor using Helm. So we should sync the configmaps for all pods or just the core and registry pod would be enough.

Also, there won't be any updates made to audit log (Like no of image pulls) of production harbor right? If we use a replica rds and the same bucket, that is.
