### ISSUE TITLE
Intermittently we are getting error when pull image from dockerhub proxy project

### ISSUE THREAD

**Issue by jangjunho7** [goharbor/harbor#19359]
**Expected behavior and actual behavior:**
Have to success all proxy pull request.

**Steps to reproduce the problem:**

1. setup dockerhub project with proxy
2. while :; do docker pull ${DOMAIN}/dockerhub/tonistiigi/binfmt:qemu-v6.2.0; docker system prune --all -f; sleep 1; done

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.8.3

**Additional context:**

**Error on clients**
```
Error response from daemon: unknown: artifact dockerhub/tonistiigi/binfmt@sha256:5bf63a53ad6222538112b5ced0f1afb8509132773ea6dd3991a197464962854e not found
Total reclaimed space: 0B
```

**Error on server(core)**
```
[ERROR] [/server/middleware/repoproxy/proxy.go:121]: failed to proxy manifest, fallback to local, request uri: /v2/dockerhub/tonistiigi/binfmt/manifests/qemu-v6.2.0, error: login to dockerhub error: Post "https://hub.docker.com/v2/users/login/": EOF
```

**Comment by stonezdj** [comment]
It is the docker hub return EOF when posting a login request to `/v2/users/login`
