### ISSUE TITLE
How to automatically delete the unneeded artifacts during pull-based replication?

### ISSUE THREAD

**Issue by xiaobai2il** [goharbor/harbor#19358]
I'm trying to set up a pull-based replication rule to a source registry, but I noticed that when the source registry delete some artifacts, my local harbor could not delete those artifacts as well locally. As a result, there will be lots of unnecessary artifacts that's taking up the disk space in local harbor for the long term.

Is there a way to enable automatic deletion for the unneeded artifacts during the pull-based replication? I would really want my harbor to contain the same exact artifacts as the source registry without using extra space for those unneeded artifacts. Thanks!

**Comment by stonezdj** [comment]
Only event based replication(push mode) support it. see https://goharbor.io/docs/2.1.0/administration/configuring-replication/create-replication-rules/

**Comment by stonezdj** [comment]
There is a risk to delete all your local images if your replication rule doesn't include any valid images.
