### ISSUE TITLE
Harbor should lock out user for at least 15 minutes after 5 invalid password attempts

### ISSUE THREAD

**Issue by lubronzhan** [goharbor/harbor#1935]
According to Security testing criteria,
Accounts should lock out for at least 15 minutes after 5 invalid password attempts
But Harbor don't lock out user for any failed password attempts

**Comment by reasonerjt** [comment]
We have a lock mechanism, if a login failure happens the user can't be logged in 5 seconds, so brutal force won't work.  This is also suggested in the guide line.

**Comment by reasonerjt** [comment]
Also for VIC 1.2， given we're moving to LW for user/credentials management, I'm leaving this issue as open just for tracking.

**Comment by xaleeks** [comment]
this is covered here https://github.com/goharbor/harbor/issues/1572
