### ISSUE TITLE
Harbor Default passwords should be required to be changed at first logon

### ISSUE THREAD

**Issue by lubronzhan** [goharbor/harbor#1937]
According to Security testing criteria,
`Default passwords are required to be changed at first logon`
Since the admin password is stored in config file in system in plain text.

**Comment by reasonerjt** [comment]
This is a valid request, but for VIC 1.2， given we're moving to LW for user/credentials management, I'm leaving this issue as open just for tracking.

**Comment by xaleeks** [comment]
inactive for too long, I'm closing.  Feel free to re-open if there's still a need
