### ISSUE TITLE
Update documentation about robot account permissions

### ISSUE THREAD

**Issue by jowko** [goharbor/harbor#19379]
Robot account documentation pages are lacking the descriptions of some permissions which can be assigned to project/system level robot accounts:
https://goharbor.io/docs/2.9.0/working-with-projects/project-configuration/create-robot-accounts/
https://goharbor.io/docs/2.9.0/administration/robot-accounts/
Some of the permissions names are descriptive (for example `pull/push repository`), but others are unknow to some users (at least me). For example what `Read Artifact` really means? The name is not descriptive enough (what is artifact in this case and how it differs from `Pull Repository` permission)?
As an admin of Harbor installation I try to grant the users least permissions possible for users using Harbor but in some cases I do not know what permissions means and I do not know if I should grant them or not. And I risk that something will not work correctly for the users later which is not good.

I think that it would be beneficial for admins to have the description for each of this permissions to know what actions user can make when assigning these permissions.

**Comment by zyyw** [comment]
Hi, users may need go through the swagger API (endpoint) to gain more details of the permissions in addition to the two documents:
* https://goharbor.io/docs/2.9.0/working-with-projects/project-configuration/create-robot-accounts/
* https://goharbor.io/docs/2.9.0/administration/robot-accounts/

The API defined all available endpoints of Harbor. And the permissions are HTTP requests to a portion of these API endpoints.
* https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml

**Comment by 7h3-3mp7y-m4n** [comment]
can I start working on this ?

**Comment by Vad1mo** [comment]
@7h3-3mp7y-m4n sure go ahead!

**Comment by AryanParashar24** [comment]
hey can i work on it 😃

**Comment by 7h3-3mp7y-m4n** [comment]
hey @AryanParashar24  you can take this
