### ISSUE TITLE
Proxy feature - verify signed images and then pull then

### ISSUE THREAD

**Issue by sfine01** [goharbor/harbor#19378]
Im working in edge cluster environment we are using proxy, but we want to pull only signed and verified images.

I would like to see a button  while creating a proxy project that gives you an option to add signature verification and to add the public key.  currently the versification only applys to deployment and not for proxy pulls. 

front end - a button or an option while creating proxy project that gives you the a ability to check if you want to test each image if its signed before pulling,  with place, maybe in the project configuration to put the pub key.

back end - while using proxy each pull the harbor makes from the target registry first it will try to verify the sinecure if it is matching with the pub key.
in addition to speed up the validation preprocess the validation and the pulling of verified images will happen at the same time.   

Seems like it will be a mile stone towards more secure edge clusters, didn't see any other good solution to this problem

**Comment by zyyw** [comment]
Maybe you should leverage the cosign and Harbor `Configuration > Deployment security` feature to enforce deploying only verified images.
<img width="1491" alt="Screenshot 2023-09-22 at 09 55 52" src="https://github.com/goharbor/harbor/assets/6709992/d7d0f3f5-07fc-4f9e-99d6-9862ccc3608f">

**Comment by sfine01** [comment]
Hey,

Thank you for your response,
I have Noticed the Deployment security - cosign feature.
But it doest solves the problem, was the problem clear? or should I
rephrase it?

You mentioned leveraging it, how can it be done?

Waiting to hear from you,
Shay

**Comment by zyyw** [comment]
Is this issue related to the you idea:
* https://github.com/goharbor/harbor/issues/18808

**Comment by sfine01** [comment]
Hey, 
I have read the feature Request and Its not exactly it, It refers only for the deployment.
In my use case its about adding a feature to the proxy ability.
 I have added a simple diagram of the environment .

![Screenshot from 2023-10-05 17-39-04](https://github.com/goharbor/harbor/assets/125459940/8345499b-db30-4a11-9fd3-3832fda570e8)

_**Current status:**_
Edge cluster - Is configured  to only  pull signed , verified against the pub key images configured throw /etc/containers/policy.
 Edge Harbor- configured to as a proxy with the main registry as the end point.
**outcome** - once I make any pull request to the Edge Harbor, all the images regarding the signature and the verification are pulled to the edge harbor and only the verified one will be pull to the edge cluster.

**required state**
Edge cluster - isn't relevant to the harbor feature.
Edge Harbor - Part of the project configurations and the proxy checkbox, you will have the ability to add a  public key that every time you will make a pull request from the edge cluster to the edge harbor the edge harbor will do the verification of the images that are located in the main registry. 
**outcome** - once you make a pull from the edge harbor the harbor will do the signature  verification and in case it does match the image wont be pull to the edge harbor.   

I hope this makes things a bit more clear.
