### ISSUE TITLE
parallel push to Harbor fails

### ISSUE THREAD

**Issue by anupy023** [goharbor/harbor#19389]
### Discussed in https://github.com/goharbor/harbor/discussions/19388

<div type='discussions-op-text'>

<sup>Originally posted by **anupy023** September 21, 2023</sup>
Hi, I am facing an issue in pushing images to harbor registry.It fails everytime to push few image and on re-run it pushes those image.
I have installed harbor using helm chart on kubernetes cluster version 1.26.5 .
Images are pushed parallel.
`
NAME                                                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
harbor                                                  harbor                  1               2023-09-13 14:59:31.460996745 +0300 IDT deployed        harbor-16.4.7                           2.7.1
`
Error :
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://core.harbor.local/v2/sm-infra/reports-legacy/blobs/uploads/b1ff73b0-90a9-4a9f-8cb5-7ae9fd8859c4?_state=fUFlZx-UVjskMvI7dLXqwmPtLGDIJM-Bx3ACcBqI-Cx7Ik5hbWUiOiJzbS1pbmZyYS9yZXBvcnRzLWxlZ2FjeSIsIlVVSUQiOiJiMWZmNzNiMC05MGE5LTRhOWYtOGNiNS03YWU5ZmQ4ODU5YzQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjMtMDktMjFUMTQ6MzU6MjcuNzgxMTE1NloifQ%3D%3D&digest=sha256%3A69c432aa4ad08131ea774411f306ba769f9a478ab2419c712d968a3d70059325`
</div>

**Comment by wy65701436** [comment]
can you share the core and registry log regarding the failure? Which client do you use to push images?

**Comment by anupy023** [comment]
Using Nerdctl to push the images.
[harbor-core-68fb98db84-wks28.log](https://githu
[registry_logs.txt](https://github.com/goharbor/harbor/files/12714568/registry_logs.txt)
b.com/goharbor/harbor/files/12714564/harbor-core-68fb98db84-wks28.log)

**Comment by anupy023** [comment]
[harbor-core-68fb98db84-wks28.log](https://github.com/goharbor/harbor/files/12714596/harbor-core-68fb98db84-wks28.log)
[registry_logs.txt](https://github.com/goharbor/harbor/files/12714600/registry_logs.txt)
using nerdctl to push the images.
