### ISSUE TITLE
Harbor with external redis 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [goharbor/harbor#19387]
Hello, fellow developers in _harbor_
I am trying to install harbor with helm chart v 1.13.0, when it comes to the redis: external, 
the harbor values file says  _**If using existingSecret, the key must be REDIS_PASSWORD**_
![image](https://github.com/goharbor/harbor/assets/48629246/35f95099-942a-4dd8-b766-f54141babceb)

but when I install the redis using helm chart (_from bitnami_) version 18.0.4 (_appVersion: 7.2.1_) the secret name is **_redis_** and its key is **_redis-password_**, not **_REDIS_PASSWORD_**.  Can you please look into this team.

For the time being I have manually edited the helm chart of redis to change the key name of the secret to **_REDIS_PASSWORD_** and installed the harbor.

here is the below issue I am facing 
![image](https://github.com/goharbor/harbor/assets/48629246/f133d2aa-983d-439b-9de0-e6bbbfa2d452)

**Steps to reproduce the problem:**
Install harbor helm chart version 1.13.0
install redis helm chart version 18.0.4 (from bitnami)
change the redis type: external

**Comment by zyyw** [comment]
Hi @rakeshreddyrg09 , when installing Harbor via harbor-helm with existingSecret for external redis, the key of the existingSecret of external redis must be `REDIS_PASSWORD`, regard less of how the external redis is installed.

As for the error of `NOAUTH Authentication required`, it seems that, after you change the key name of the existingSecret of external redis to `REDIS_PASSWORD`, Harbor can talk to the redis but likely the auth credentials is not correct. Could you please double check whether you can `PING` the redis-server via `redis-cli` with the auth credentials specified in `REDIS_PASSWORD`?

**Comment by MinerYang** [comment]
Hi @rakeshreddyrg09 ,
Could you please verify a few things
1. as shengwen mentioned above, could you use the `redis-cli -h <hostname> -a <pasword>` to check if the password is correct.
2. how do you create the secret ? Is it under same namespace with harbor instance? Could you also kindly provide the secret manifest ?
3. could you provide the redis url that is been rendered? such as `kubectl get cm <harbor-core-cm> -o yaml | grep _REDIS_URL_CORE`

**Comment by rakeshreddyrg09** [comment]
Hi @MinerYang, Sorry for the late response
1. I checked the password, it is correct.
2. Yes it is in the same namespace harbor.  the below is crated my me, referring redis secret.
![image](https://github.com/goharbor/harbor/assets/48629246/ec2d7ece-508d-44e4-bf6d-c19042781310)
redis secret:
![image](https://github.com/goharbor/harbor/assets/48629246/4febc06b-aaa7-4908-8f3e-492b1e2bc66a)
3. 
![image](https://github.com/goharbor/harbor/assets/48629246/97017888-e5fb-4e92-aee9-f02b727549c3)

**Comment by rakeshreddyrg09** [comment]
> Hi @rakeshreddyrg09 , when installing Harbor via harbor-helm with existingSecret for external redis, the key of the existingSecret of external redis must be `REDIS_PASSWORD`, regard less of how the external redis is installed.
> 
> As for the error of `NOAUTH Authentication required`, it seems that, after you change the key name of the existingSecret of external redis to `REDIS_PASSWORD`, Harbor can talk to the redis but likely the auth credentials is not correct. Could you please double check whether you can `PING` the redis-server via `redis-cli` with the auth credentials specified in `REDIS_PASSWORD`?

this time i didn't change the redis secret, i create a new secret with same value. still i am getting the same error

**Comment by MinerYang** [comment]
Hi @rakeshreddyrg09 ,
the reids url you attached seems wrong , it should be rendered like this `redis://:<password>@<redis-server-host>:6379/0?idle_timeout_seconds=30`
there's a `:<password>` miss.. I will look into it and fix in next release.

Instead could you try to use password instead of existingSecret instead?

**Comment by rakeshreddyrg09** [comment]
Thank you so much @MinerYang

**Comment by Kajot-dev** [comment]
I believe this is the same as [#1352](https://github.com/goharbor/harbor-helm/issues/1352) and your PR fixes it as well
