### ISSUE TITLE
Issue upgrading Harbor from 2.8.4 to 2.9.0 via Helm (from 1.12.4 chart to 1.13.0).

### ISSUE THREAD

**Issue by cparadal** [goharbor/harbor#19398]
harbor-core pods are crashing when trying to upgrade the Harbor Helm chart (we use ArgoCD to manage Helm applications).

```
harbor-core-55cc8c9847-8b8vk         1/1     Running            0                6h52m
harbor-core-55cc8c9847-hg2jz         1/1     Running            0                6h56m
harbor-core-55cc8c9847-zdrkm         1/1     Running            0                6h56m
harbor-core-5d85bb9489-whj6m         0/1     CrashLoopBackOff   35 (3m17s ago)   157m
```

```
2023-09-26T17:33:56Z [INFO] [/common/dao/pgsql.go:135]: Upgrading schema for pgsql ...
2023-09-26T17:33:56Z [ERROR] [/common/dao/pgsql.go:140]: Failed to upgrade schema, error: "Dirty database version 120. Fix and force version."
2023-09-26T17:33:56Z [FATAL] [/core/main.go:192]: failed to migrate the database, error: Dirty database version 120. Fix and force version.
```

I can see the [known issue](https://github.com/goharbor/harbor/releases/tag/v2.9.0) in the 2.9.0 release notes but we don't run any manual migration scripts, we just rely on Helm (ArgoCD) upgrades. This has been working for us for years now.

Is there something that can be done here to recover this, without having to rollback the database (we use an RDS instance)? Downgrade to 2.8.4 doesn't seem to work.

**Comment by MinerYang** [comment]
Are you using external database? Which version of your postgres db is?

**Comment by cparadal** [comment]
> Are you using external database? Which version of your postgres db is?

That was the issue, our RDS Postgres database was still on version 11, and we missed the upgrade notes indicating that minimum version was 12. All fixed now.

Thanks!

**Comment by kingnarmer** [comment]
I got same error. I don't use external database. The installed postgress with harbor is postgresql-12.10.0. Any help appreciated.

**Comment by MinerYang** [comment]
> I got same error. I don't use external database. The installed postgress with harbor is postgresql-12.10.0. Any help appreciated.

Could you help to open an githubissue and provide more details? such as how do your deploy your harbor instance of which version?
