### ISSUE TITLE
Replication index Incorrect accessory

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19392]
**Steps to reproduce the problem:**
1. Push image_a to Harbor A
2. Push image_b to Harbor A
3. Create index
```
docker manifest create ${harbor_a}/project/index:v1 ${harbor_a}/project/imageb:latest ${harbor_a}/project/imagea:lates
```
4. Push index to Harbor A
```
docker manifest push ${harbor_a}/project/index:v1
```
5. Cosign sign the image_a
<img width="733" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/789450af-bbb0-4e12-b335-2d513f394a17">

6. Cosign sign the image_b
<img width="726" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/1663fb94-1729-4f78-8310-ff8582651a3f">

7. Cosign sign the index
<img width="731" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/7e4f7115-0f18-4c84-8260-89f36b6b7a03">

8. Cosign sign the sub-image of index
<img width="767" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/7ba3b114-2f6f-4e05-8c98-67e3c289c1be">

9. Create replication rules and trigger
<img width="648" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/4930b87d-9ae5-4c00-983c-074113573e67">

10. Compare this with step 8, where the signature of the index in Harbor B is incorrect
<img width="1407" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/eb15fae7-be7b-4b89-87e7-cdcc613dc379">

**Versions:**
Please specify the versions of following systems.

- harbor version: main

**Comment by wy65701436** [comment]
fixed by https://github.com/goharbor/harbor/pull/19661
