### ISSUE TITLE
Harbor CVE prevent HEAD requests

### ISSUE THREAD

**Issue by arnaudclerc** [goharbor/harbor#19408]
### Expected behavior and actual behavior:
Harbor registry configured to block images with vulnerabilities.
![image](https://github.com/goharbor/harbor/assets/23419677/1525c89b-2ff2-4169-86f9-9320dcbc9f33)

Being able to override an image with vulnerabilities

It is impossible to push an image, to fix its vulnerabilities for example, with this setting enabled

Docker desktop succeeds but the problem appears inside a Gitlab CI/CD (using kubernetes runner with kaniko or crane)
<img width="496" alt="image" src="https://github.com/goharbor/harbor/assets/23419677/dc4dfb40-4f51-40e1-8694-32f62dca7ad8">

### **Steps to reproduce the problem:**
- in a gitlab CI
- Push image with vulnerabilities to registry
- Private registry configured to prevent images with vulnerabilities to work
- push a second time the image (image content doesn't affect behavior)
- Unable to push (412 precondition failed) (unable to fix CVE)

**other solution failed**
- Push image with CVE to registry
- retrieve image's digest `crane digest "${HARBOR_URL}/container-registry/${CI_PROJECT_NAME}:${TAG}"`
- Unable to get digest (412 precondition failed) (unable to delete image using digest to fix initial problem)

**Versions:**
- harbor: Version v2.9.0
- Kaniko builder: gcr.io/kaniko-project/executor:v1.16-debug 
or 
- gcr.io/go-containerregistry/crane:debug

### **Error Example**
- crane
<img width="462" alt="image" src="https://github.com/goharbor/harbor/assets/23419677/f352c365-6201-475d-a04a-3ceace2d7392">

```
crane digest --insecure localhost:8443/container-registry/frontend:0.1-dev
2023/09/29 17:57:27 HEAD request failed, falling back on GET: HEAD https://localhost:8443/v2/container-registry/frontend/manifests/0.1-dev: unexpected status code 412 Precondition Failed (HEAD responses have no body, use GET for details)
Error: GET https://localhost:8443/v2/container-registry/frontend/manifests/0.1-dev: PROJECTPOLICYVIOLATION: current image with 3 vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "High" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist.
```

- kaniko
<img width="481" alt="image" src="https://github.com/goharbor/harbor/assets/23419677/92802d88-cb71-4108-a2ea-79755fc8c286">

```
INFO[0003] Pushing image to core-harbor.[MASKED]/container-registry/frontend:0.2.0-dev 
error pushing image: failed to push to destination core-harbor.[MASKED]/container-registry/frontend:0.2.0-dev: HEAD https://core-harbor.[masked]/v2/container-registry/frontend/manifests/0.2.0-dev: unexpected status code 412 Precondition Failed (HEAD responses have no body, use GET for details)
```

harbor-core side, we can see the HEAD request directly  on the manifest, triggers the 412

```
2023-09-29T16:03:49Z [DEBUG] [/core/service/token/authutils.go:102]: user: robot__manager, access: &{repository  container-registry/frontend [pull push delete]}


2023-09-29T16:03:49Z [DEBUG] [/server/middleware/log/log.go:31]: attach request id cce6ce0ac67374cf83320a1549d4973d to the logger for the request HEAD /v2/container-registry/frontend/manifests/0.1-dev


2023-09-29T16:03:49Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:55]: In artifact info middleware, url: /v2/container-registry/frontend/manifests/0.1-dev


2023-09-29T16:03:49Z [DEBUG] [/lib/http/error.go:62]: {"errors":[{"code":"PROJECTPOLICYVIOLATION","message":"current image with 3 vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of \"High\" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist."}]}
```

The paremeter to block images with vulnerabilities should only prevent GET request, not HEAD, as some tools use this method to push images.

**Comment by funkypenguin** [comment]
I confirm the same issue affects Concourse CI using the [registry image resource](https://github.com/concourse/registry-image-resource), and to my recollection, it only happened after upgrading Harbor to v2.9.0

The consequence for us is that it's not possible to push a CVE fix to a tag like `stable` or `latest`, since the resource will first do a HEAD on that tag before pushing.

**Comment by arnaudclerc** [comment]
the only tool i could find working with our stack (Gitlab runner over kubernetes) is [Buildah](https://buildah.io).
Issue still blocking for all other tools

**Comment by hoerup** [comment]
I just ran into this - using harbor 2.7.2 and kaniko

**Comment by arnaudclerc** [comment]
here is a job that works for pushing images to Harbor without issues

```yaml
container-build:
    image: "quay.io/buildah/stable:v1.31.0"
    variables:
        STORAGE_DRIVER: vfs
        BUILDAH_FORMAT: docker
    script:
        - echo "${HARBOR_CONTAINER_TOKEN}" | buildah login -u "${HARBOR_CONTAINER_LOGIN}" --password-stdin "${HARBOR_URL}"
        - echo -e "[registries.search]\nregistries = ['docker.io']" > /etc/containers/registries.conf
        - buildah bud
            --file "${CI_PROJECT_DIR}/Dockerfile"
            --tag "${HARBOR_URL}/${REGISTRY}/${CI_PROJECT_NAME}:${TAG}"
        - buildah push "${HARBOR_URL}/${REGISTRY}/${CI_PROJECT_NAME}:${TAG}"
```

you also need this annotation in your gitlab runner helm
```yaml
[runners.kubernetes.pod_annotations]
          "container.apparmor.security.beta.kubernetes.io/build" = "unconfined"
```

**Comment by devahariharan** [comment]
Ran into this issue in Harbor v2.7.4 when pushing images from Concourse CI with same tags which has vulnerability.
@funkypenguin Can you please confirm if you were able to fix this?

**Comment by funkypenguin** [comment]
Nope, we never fixed this. We ended up disabling the blocking of pulls for vulnerabilities, since there were so many production-affecting issues that cropped up when new CVEs were added to the database.

We now alert on exceptions (using Kyverno), but the Harbor implementation became unusable.

D
