### ISSUE TITLE
Harbor registry proxying not working with proxy.replicated.com

### ISSUE THREAD

**Issue by haiwu** [goharbor/harbor#19407]
**Expected behavior and actual behavior:**
Harbor registry proxying not working with proxy.replicated.com. When trying to set it up via Harbor UI, Harbor keeps saying it can't ping. Even after inputting 'access id' and 'access secret', still got the same error. 

Error message from '/var/log/harbor/core.log':
Sep 28 11:53:20 192.168.32.1 core[60139]: 2023-09-28T15:53:20Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry https://proxy.replicated.com/: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"Invalid credentials"}]}

**Steps to reproduce the problem:**
Go to Harbor UI -> Registries -> NEW ENDPOINT -> Pick 'Docker Registry' as Provider, give it a name, and 'https://proxy.replicated.com' as 'Endpoint URL'. Click 'TEST CONNECTION'. 

It fails with 'Failed to ping endpoint.' error message. Same thing after putting 'Access ID' and 'Access Secret'. 

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.0
- docker engine version: 24.0.2
- docker-compose version: 2.2.3

**Additional context:**
N/A

**Comment by chlins** [comment]
The different vendor relies on the different adapter, what is the backend of the `https://proxy.replicated.com/`? If you choose the `Docker Registry` as adapter, please confirm that your registry is compatible with the distribution spec.

**Comment by OrlinVasilev** [comment]
@haiwu is your issue resolved? if not can you please provide a bit more information as @chlins requested? thank you :)
