### ISSUE TITLE
Error connecting to redis

### ISSUE THREAD

**Issue by sdcxzx-tester** [goharbor/harbor#19403]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version:2.7.3
- docker engine version:24.0.5
- docker-compose version: 2.22.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

setp1. docker-compose down
setp2. sudo ./install.sh --with-trivy

 Error message:failed to ping redis://172.16.10.22:16379?idle_timeout_seconds=60, retry after 566.3927ms : read tcp 172.19.0.7:38066->172.16.10.22:16379: i/o timeout

**Comment by MinerYang** [comment]
Could you provide more details?
1. make sure your redis server  address `172.16.10.22:16379`is pingable with correct pwd, such as `redis-cli -h 172.16.10.22:16379 -a <requirepass> ` then run `ping`
2. provide your external redis configuration
3. `sudo cat harbor/common/config/core/env | grep redis` to get your redis url

**Comment by sdcxzx-tester** [comment]
I can use [Another Redis Desktop Manager] to connect.

**Comment by sdcxzx-tester** [comment]
There is no problem with telnet on the host.

**Comment by sdcxzx-tester** [comment]
no pwd

**Comment by MinerYang** [comment]
have you disable protected-mode at your redis service side?

**Comment by sdcxzx-tester** [comment]
Not only redis, but also others are the same.

**Comment by MinerYang** [comment]
What exactly meaning of `Not only redis, but also others are the same`, could you give an example?

**Comment by sdcxzx-tester** [comment]
The database cannot be accessed.
I guess it's a docker problem. I'm ready to uninstall and reinstall.

**Comment by MinerYang** [comment]
make sure the ip address used for your external redis service, harbor hostname or external db  is accessible to external clients.  `172.16.10.22` seems not like an external one.

**Comment by sdcxzx-tester** [comment]
The server where harbor is located can be accessed.

**Comment by sdcxzx-tester** [comment]
The universal restart has been solved.
