### ISSUE TITLE
OIDC OnBoarding - Group Filter not working

### ISSUE THREAD

**Issue by heresie** [goharbor/harbor#19419]
*Harbor Helm Chart Version: 1.12.4*
*Harbor Docker Image Tag: v2.8.4*
*Note: all sensitive datas have been replaced by `[REDACTED]`.*

---

Hello!

I'm currently configuring a Harbor instance, with delegated OIDC Authentication. This instance is deployed through the official Helm Chart on a Kubernetes Cluster. The tests exposed in this issue were made after a fresh install.

I would like to allow user onboarding only for OIDC users belonging to certain groups.

The current OIDC looks like that: 

| Configuration Key    | Value                                       |
| -------------------- | ------------------------------------------- |
| OIDC Provider Name   | `[REDACTED]`                                |
| OIDC Endpoint        | `https://[REDACTED]/auth/realms/[REDACTED]` |
| OIDC Client ID       | `[REDACTED]`                                |
| OIDC Client Secret   | `[REDACTED]`                                |
| OIDC Group Filter    | `registry-docker-(access\|admin)`           |
| Group Claim Name     | `groups`                                    |
| OIDC Admin Group     | `registry-docker-admin`                     |
| OIDC Scope           | `openid,profile,roles`                      |
| Automatic onboarding | ✅                                          |
| Username Claim       | `preferred_username`                        |

Currently, all users authenticated on the OIDC Server can onboard to Harbor, regardless to the OIDC groups they belong, like the OIDC Group Filter was ignored.

The Admin role is correctly granted to users belonging to `registry-docker-admin` OIDC group.

Here is a log of an onboarding user: 

```
2023-10-06T14:06:51Z [DEBUG] [/pkg/oidc/helper.go:201]: Raw ID token for verification: [REDACTED]
2023-10-06T14:06:51Z [DEBUG] [/core/controllers/oidc.go:155]: Doing automatic onboarding
2023-10-06T14:06:51Z [DEBUG] [/pkg/oidc/helper.go:418]: populateGroupsDB, group filter registry-docker-(access|admin)
2023-10-06T14:06:51Z [DEBUG] [/pkg/oidc/helper.go:438]: filter is registry-docker-(access|admin), result is []
2023-10-06T14:06:51Z [DEBUG] [/core/controllers/oidc.go:228]: User created: [REDACTED]
2023-10-06T14:06:51Z [DEBUG] [/core/controllers/oidc.go:166]: User automatically onboarded
2023-10-06T14:06:51Z [DEBUG] [/pkg/oidc/helper.go:418]: populateGroupsDB, group filter registry-docker-(access|admin)
2023-10-06T14:06:51Z [DEBUG] [/pkg/oidc/helper.go:438]: filter is registry-docker-(access|admin), result is []
```

Here is the user's decoded JWT Token Payload:

```json
{
  "exp": 1696603011,
  "iat": 1696601211,
  "auth_time": 1696601211,
  "jti": "[REDACTED]",
  "iss": "https://[REDACTED]/auth/realms/[REDACTED]",
  "aud": "[REDACTED]",
  "sub": "[REDACTED]",
  "typ": "ID",
  "azp": "[REDACTED]",
  "session_state": "[REDACTED]",
  "at_hash": "[REDACTED]",
  "acr": "1",
  "sid": "[REDACTED]",
  "email_verified": [REDACTED],
  "name": "[REDACTED]",
  "groups": [
    "[REDACTED]-CIN",
    "[REDACTED]-SCI",
    "[REDACTED]-SER",
    "[REDACTED]-ARS",
    "[REDACTED]-pages",
    "[REDACTED]-admin",
    "[REDACTED]-[REDACTED]-editor",
    "[REDACTED]-user",
    "[REDACTED].[REDACTED]-DOR",
    "[REDACTED]-corporate-editor",
    "[REDACTED]",
    "[REDACTED]-DEC",
    "[REDACTED]-CPO",
    "[REDACTED]-HOME",
    "[REDACTED]-ACT",
    "[REDACTED].[REDACTED]-EMI",
    "[REDACTED]-HIS",
    "[REDACTED]-access"
  ],
  "preferred_username": "[REDACTED]",
  "family_name": "[REDACTED]",
  "email": "[REDACTED]"
}
```

This user does not belong to groups `registry-docker-admin` and `registry-docker-access`.

Can somebody tell me if I'm misconfiguring Harbor, or if it can be a bug ?

**Comment by stonezdj** [comment]
The current OIDC group filter is only used to filter the group onboard to Harbor, not filter the login user which is not belong to the group. it is confusing, and we will update the document and add tips for it.

**Comment by Freydiere** [comment]
I encountered the same problem on my installation. Do you think you could change this and forbid users whose roles don't match the filter? Do you intend to change this in a later release?

**Comment by heresie** [comment]
Hello @stonezdj ! Thank you for your feedback.
You are right, the documentation needs to be updated :)
