### ISSUE TITLE
minio: docker: invalid spec: :/data: empty section between colons.

### ISSUE THREAD

**Issue by super-vip** [goharbor/harbor#19410]
harbor-offline-installer-v2.9.0.tgz

./install.sh

[Step 3]: preparing environment ...

[Step 4]: preparing harbor configs ...
prepare base dir is set to /apps/harbor
docker: invalid spec: :/data: empty section between colons.
See 'docker run --help'.

[root@harbor harbor]# cat harbor.yml
hostname: r.k8s.lan
http:
  port: 80
https:
  port: 443
  certificate: /data/harbor/certs/r.k8s.lan.crt
  private_key: /data/harbor/certs/r.k8s.lan.key
harbor_admin_password: i4Seeyon
database:
  password: root123
  max_idle_conns: 100
  max_open_conns: 900
  conn_max_lifetime: 5m
  conn_max_idle_time: 0
# data_volume: /data/harbor
storage_service:
  # ca_bundle:
  s3:
    accesskey: xxx
    secretkey: xxx
    region: gz-gy-by-1
    regionendpoint: http://m.k8s.lan:9000
    bucket: harbor
    encrypt: false
    secure: false
    v4auth: false
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
    rootdirectory: /
  redirect:
    disable: true
......

**Comment by stonezdj** [comment]
Could you please provide more detail of the issue?
