### ISSUE TITLE
Can't push large image if the process takes more then 30 min - unauthorized to access repository

### ISSUE THREAD

**Issue by devopskupryk** [goharbor/harbor#19413]
I use harbor version v2.8.3-19d69635 installed by helm chart into my k8s doks cluster v.1.25.12

Have specified REGISTRY_HTTP_CLIENT_TIMEOUT=180 for core and jobservice but it looks like default 30min limit hasn't been increased.

I pushed the same image twice:
<img width="1248" alt="image" src="https://github.com/goharbor/harbor/assets/105593788/b4c82cd7-9b8e-4866-86f8-06c6923e3d74">

As you can see, the first attempt took more then 30 min and failed, but the second attempt took less then 30 min and succeed.

What should I do to increase default 30 min limit?

PS. Also I've specified next annotations in harbor ingress:
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '10800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '10800'

**Comment by devopskupryk** [comment]
Problem was with token expiration.
I increased default value (30 min) to 180 and large image was pushed successfully
<img width="604" alt="image" src="https://github.com/goharbor/harbor/assets/105593788/472f7281-12c4-4fe9-9575-cb9f5d7b7997">

**Comment by Vad1mo** [comment]
these are the wrong settings.

```
nginx.ingress.kubernetes.io/proxy-body-size: 10000m
nginx.ingress.kubernetes.io/proxy-read-timeout: '10800'
nginx.ingress.kubernetes.io/proxy-send-timeout: '10800'
```

The way to go is:

```
 nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/proxy-body-size: "0"
  ingress.kubernetes.io/proxy-body-size: "0"
  nginx.ingress.kubernetes.io/proxy-buffering: "off"
  nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
``` 

See
