### ISSUE TITLE
Fixed: LDAP not working - now locked out of instance, even as "admin"

### ISSUE THREAD

**Issue by module0x90** [goharbor/harbor#19411]
Hi,

don't let your session timeout when you're setting up LDAP - and LDAP isn't working for one reason or another.

Can you please add

update properties set v = 'db_auth' where id=5;

into your FAQ please, so that this doesn't happen to others?

Cheers

Tom

**Comment by stonezdj** [comment]
Could you please provide more detail of the issue?

**Comment by module0x90** [comment]
Hi,

I had setup Harbor and logged in via the prepopulated admin account.
I tried setting up LDAP in an AD environment - and I couldn't get it to work.
I left the http session and went for lunch.

When I came back my http session expired and I couldn't login via the admin account anymore.

I figured the above SQL command disables my non-working LDAP config again and I was able to login via the local "admin" user again.


Cheers

Tom

**Comment by Vad1mo** [comment]
From your description, I see the correct behavior. You can always log in as admin and for whatever reason, your IDP config is wrong and needs to be changed.

**Comment by module0x90** [comment]
Your documentation clearly states, you cannot login login as (local) admin anymore when you have configured LDAP/AD.

Whether LDAP/AD works or not, as soon you have configured parts of it, Harbor assumes it is working perfectly and denies local admin logins.

I only wanted to share the experience I had when configuring Harbor and LDAP. Would it be possible to have it not to switch to LDAP immediately, but after a username/password test against LDAP succeeds? Only then it should switch the authentication to LDAP.
Otherwise it would always lock out users.

All in all, the team I have installed Harbor for is very pleased with it, many thanks.
