### ISSUE TITLE
Harboor upgrade failed due to failed to get config manager 

### ISSUE THREAD

**Issue by neha-live** [goharbor/harbor#19440]
I am trying to upgrade harbor from 2.5.4 to 2.6.2 using helm charts but everytime it is failing with below error. I tried deploying harbor 2.6.1 as well but getting same error. core and jobservice have same error. Please note I am not using any external database. 

Appending internal tls trust CA to ca-bundle ...
--
Thu, Oct 12 2023 10:33:59 am | find: '/etc/harbor/ssl': No such file or directory
Thu, Oct 12 2023 10:33:59 am | Internal tls trust CA appending is Done.
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/pkg/registry/client.go:83]: Failed to parse REGISTRY_HTTP_CLIENT_TIMEOUT: strconv.ParseInt: parsing "": invalid syntax, use default value: 30m0s
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.wasm.config.v1+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:30]: the factory for adapter ali-acr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:29]: Factory for adapter azure-acr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:18]: the factory for adapter gitlab registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:37]: the factory for adapter google-gcr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:40]: the factory of Huawei adapter was registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:43]: the factory of jfrog artifactory adapter was registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/core/controllers/base.go:153]: Config path: /etc/core/app.conf
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/core/main.go:136]: initializing cache ...
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/core/main.go:146]: initializing configurations...
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/lib/config/systemconfig.go:198]: key path: /etc/core/key
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/lib/config/config.go:92]: init secret store
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/core/main.go:148]: configurations initialization completed
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-harbor-v262-database port-5432 database-registry sslmode-"disable"
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/common/dao/base.go:72]: Register database completed
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [ERROR] [/common/dao/pgsql.go:136]: Failed to upgrade schema, error: "Dirty database version 90. Fix and force version."
Thu, Oct 12 2023 10:33:59 am | 2023-10-11T23:33:59Z [FATAL] [/core/main.go:177]: failed to migrate the database, error: Dirty database version 90. Fix and force

**Comment by chlins** [comment]
Replied in https://cloud-native.slack.com/archives/CC1E09J6S/p1697068640886819.
