### ISSUE TITLE
Robot Account has security issue. 

### ISSUE THREAD

**Issue by geoger** [goharbor/harbor#19441]
After enable OIDC feature. Since user has to do MFA. So, for those script using Harbor has to use Robot Account
And Robot Account is bind to specific Project. not bind to specific user.  This may cause security Issue.
suppose some one leave the project, and he/she know the robot account and password.  even project admin had removed the person from the access list of the project, he/she could also use the project Robot account and password to read, event write over the image of the project.  So robot account is really not a perfect idea. Should be replaced with better method , like , for example, token system of user, user could generated a token , and the token has same permission of the user.

**Comment by Vad1mo** [comment]
Robot accounts are decoupled from users on purpose. For CI/CD, automation, deployments etc. 

User should use CLI secrets. Those are bound to IDP lifecycle of the user
