### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by suprita23** [goharbor/harbor#19450]
I keep getting 403 forbidden during user management operation even when I am logged in as Admin.
Here are a few scenarios I tried:
1. Delete user from Administration > Users > Select user and select delete from drop-down
2. Delete user from Projects> <Project name> > Members > Select User and Remove from drop-down
3. Reset Password for a user from Administration > Users > Select User and Reset Password from drop-down

About configuration. I have database backed user setup.
I have multiple admin access level users as well as a generic admin user. 
I get same errors with every Admin user.

**Comment by MinerYang** [comment]
Could you provide logs while having 403 errors? And what is your auth mode and harbor version?

**Comment by suprita23** [comment]
Thanks for your reply @MinerYang .
I looked through the logs and found that the WAF was blocking the requests.
Once I fixed the rules, the requests started passing.
