### ISSUE TITLE
Programm language API Client SDK support

### ISSUE THREAD

**Issue by huhouhua** [goharbor/harbor#19467]
**Is your feature request related to a problem? Please describe.**
Provide different programm languages API interface Client SDK 

**Describe the solution you'd like**

**Describe the main design/architecture of your solution**
For example, you need to write a Client SDK to call the http API directly now, if provide an API Client SDK for different programm languages, so that more users, do not have to care about the API problem, directly use the Client SDK, which can simplify their development workload.

**Describe the development plan you've considered**
Priority is given to SDKS for major programm languages, but I can be responsible for implement Client SDKS for Java, Ruby, C# if needed.

**Comment by chlins** [comment]
Harbor utilizes the [swagger.yaml](https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml) to manage API documentations. By leveraging [swagger-codegen](https://github.com/swagger-api/swagger-codegen), you can generate a client SDK for your desired programming language.
