### ISSUE TITLE
Upgrade from 2.8.4 to 2.9.0 get failed to migrate the database, error: Dirty database version 120. Fix and force version

### ISSUE THREAD

**Issue by rakkenes** [goharbor/harbor#19469]
I have been running upgrades, and I am trying to get from 2.3.3 to 2.9.0
- I have had some issues with this before, which is why I have been stuck with such an old version. but now I have made a duplicate copy of my live server, so that I can try and troubleshoot this... so far I have done this:
2.3.3 -> 2.4.0 ok
2.4.0 -> 2.5.0 ok
2.5.0 -> 2.6.0 ok
2.6.0->2.7.0 ok
2.7.0->2.8.0 ok
2.8.0 ->2.8.4 ok
2.8.4 -> 2.9.0 nok ok.
-
2023-10-19T11:34:31Z [DEBUG] [/pkg/config/db/manager.go:36]: create DB config manager with cache enabled
2023-10-19T11:34:31Z [INFO] [/core/main.go:163]: initializing configurations...
2023-10-19T11:34:31Z [INFO] [/lib/config/systemconfig.go:173]: key path: /etc/core/key
2023-10-19T11:34:31Z [INFO] [/lib/config/config.go:92]: init secret store
2023-10-19T11:34:31Z [INFO] [/core/main.go:165]: configurations initialization completed
2023-10-19T11:34:31Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
2023-10-19T11:34:31Z [INFO] [/common/dao/base.go:72]: Register database completed
2023-10-19T11:34:31Z [DEBUG] [/migration/migration.go:37]: current database schema version: 120
2023-10-19T11:34:31Z [INFO] [/common/dao/pgsql.go:135]: Upgrading schema for pgsql ...
2023-10-19T11:34:31Z [ERROR] [/common/dao/pgsql.go:140]: Failed to upgrade schema, error: "Dirty database version 120. Fix and force version."
2023-10-19T11:34:31Z [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:199]: Closing source and database
2023-10-19T11:34:31Z [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:199]: Closing source and database
2023-10-19T11:34:31Z [FATAL] [/core/main.go:194]: failed to migrate the database, error: Dirty database version 120. Fix and force version.
-
Above is the tail of the log in the core container

I am aware of this issue:  https://github.com/goharbor/harbor/issues/19320
and I have tried to follow the hints there, but no help.

I have tried many things, and many times. I have in the past tried to upgrade in bigger chunks, but since that has failed, that is why I have taken such baby-steps above. 

if there are any files that you need to see to better troubleshoot, of if I can do anything to test something let me know.

**Comment by chlins** [comment]
It seems that error occurred when running the migration SQLs from 2.8.4 to 2.9.0, could you try to execute the SQL manually  in the Postgres?

**Comment by rakkenes** [comment]
> It seems that error occurred when running the migration SQLs from 2.8.4 to 2.9.0, could you try to execute the [SQLs](https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_2.9.0_schema.up.sql) manually in the Postgres?

do you have a procedure for doing that?

**Comment by stonezdj** [comment]
Before execute SQLs, please update the dirty to false
```
update schema_migrations set version = 80, dirty=false where 1 = 1
```

**Comment by chlins** [comment]
> > It seems that error occurred when running the migration SQLs from 2.8.4 to 2.9.0, could you try to execute the [SQLs](https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_2.9.0_schema.up.sql) manually in the Postgres?
> 
> do you have a procedure for doing that?

@rakkenes Exec into harbor-db container and running the commands. 
e.g. 
```bash
$ psql
$ \c registry;
$ ENTER the SQLs
```

**Comment by rakkenes** [comment]
thanks for the input, I will try that, but I have a couple questions:

1) these SQLs where do I find them?

and 

2) in the procedure for upgrading from one version to the next there is a script that is run like this: "docker run -it --rm -v /:/hostfs goharbor/prepare:[tag] migrate -i ${path to harbor.yml}" and that seems to convert the harbor.yml file from the older to the newer version... (which is fine). but. does it do anything else? or does it only convert to the later yaml format? (e.g does it do anything to the database or such... or does it only one thing, edit the yaml file?)

**Comment by chlins** [comment]
1. https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_2.9.0_schema.up.sql
2. the prepare script will convert the old harbor.yml to the new one(which may contains the new configuration introduced in the new version).

**Comment by rakkenes** [comment]
I just wanted to step back to this case and thank eveyrone for helping me, I have used the help above on several upgrades from 2.3.3 ... in steps up to 2.8.4...  some minor notes:

when I came accross an "error: Dirty database version XXX. Fix and force version" I opened a shell in the container like this:

docker exec -it XXxxXXxx bash
psql
\c registry;
update schema_migrations set version = XXX, dirty=false where 1 = 1; 
- then I entered the SQLs from the links https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_XXX_schema.up.sql

this works: I think that maybe the automagical running of this code should be made more robust, OR documentation could mention this.. 

I still have an issue between 2.8.0 and 2.9.0 but this will be a separate case.

**Comment by TomHellier** [comment]
I got this on a recent helm upgrade, running the postgres migration manually in the db pod worked for me.

**Comment by jan-from-meiro** [comment]
Got the same issue between 2.7.3 and 2.9.1. Manual SQLs execution fixed it as well for me.

**Comment by LennartTimmers** [comment]
My team also ran into this issue while upgrading, just wondering did you guys put your harbor instance in read only mode? We didn't and I wonder if this issue would've still occurred in that case.

<img width="402" alt="image" src="https://github.com/goharbor/harbor/assets/26593383/e6415093-dfb2-45f9-bfa5-e64051d5c30a">

**Comment by Vad1mo** [comment]
The schema migration fails in this case because probably the DB does not have the right capability (version <12) 

When applying the migration script manually you'll see the exact error.

**Comment by TomHellier** [comment]
> I got this on a recent helm upgrade, running the postgres migration manually in the db pod worked for me.

I've had this again for version 140 :(
