### ISSUE TITLE
Automatic Latest tag ?

### ISSUE THREAD

**Issue by EvgenPavlyuchek** [goharbor/harbor#19473]
Is it possible to automatic the "latest" tag?
I thought it was elementary thing, but it is not mentioned anywhere

send some images with different tag versions and get the latest of them with date or number pulling image:latest

**Comment by OrlinVasilev** [comment]
can you elaborate a bit more what are you trying to achieve here thank you

**Comment by Vad1mo** [comment]
the `latest` tag is attached if you push an image without any tags  (or a tag named `latest`) 
latest is not automatically added to the latest pushed image by default. This is not the case for Harbor or any other registry.
