### ISSUE TITLE
Harbor UI not stable 

### ISSUE THREAD

**Issue by xiaobai2il** [goharbor/harbor#19480]
We have set up harbor with Traefik load balancer and router in front of harbor on both EC2 instance and actual machine. I'm not sure if it's because of the proxy in front of harbor, but I'm noticing that the harbor UI webpage is working but very unstable. Sometimes, it works perfectly fine, but other times, it will be stuck at the log in page and some other times, when doing some operations on the harbor webpage, it will just crash and go back to the log in page. Is there anyone experiencing similar behavior? How can I make the UI more stable?
![MicrosoftTeams-image](https://github.com/goharbor/harbor/assets/93493482/8a10d1ce-1aea-42b5-9b8b-046cb2ff2c3c)

**Comment by chlins** [comment]
Please also provide more information of the proxy or lb configuration.

**Comment by xiaobai2il** [comment]
> Please also provide more information of the proxy or lb configuration.
Basically, it's just using mTLS and route all requests from harbor url to harbor nginx proxy.
![image](https://github.com/goharbor/harbor/assets/93493482/fcf55575-d221-4201-b4ab-55f9d9fec79a)
![image](https://github.com/goharbor/harbor/assets/93493482/01bbfcda-a7c2-440a-a054-8b09a1f64d12)

**Comment by Vad1mo** [comment]
check the console logs, to discover the issues.

**Comment by anhnmt** [comment]
i had the same issue
