### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by FalkWinkler** [goharbor/harbor#19496]
hi, 

i have a proxy to  ghcr. If i pulling a image than i have a tls error.

 docker pull reg.f-wi.com/proxy-ghcr.io/siderolabs/kubelet
Using default tag: latest
Error response from daemon: Get "https://reg.f-wi.com/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by chlins** [comment]
Is your harbor instance deployed with the self-signed certificate? if so you need to configure your certificate in docker config.

**Comment by FalkWinkler** [comment]
No, it's a letsenypt certificate.  All other proxy working, only the ghcr proxy not working.

**Comment by FalkWinkler** [comment]
It's working now.  I had from certbot the cert.pem and not the fullchain.pem used.
