### ISSUE TITLE
GAR deletion fails when image with tag is deleted from Harbor

### ISSUE THREAD

**Issue by chandlerlow** [goharbor/harbor#19495]
**Expected behavior and actual behavior:**

Expected: Deletion of an image with a tag should also remove replicated image in GAR (Google Artifact Registry) with delete remote resources enabled on the replication rule.

Actual: Deletion fails, with image being removed from Harbor but remaining in GAR.

Note this behaviour does work for GCR replication.

**Steps to reproduce the problem:**

1. Set up replication rule to from harbor to GAR 
2. Set trigger mode to be event based and turn on "delete remote resources when deleted locally"
3. Delete image with tag, that has been replicated in GAR, from Harbor
4. Replication rule should show execution failed

with error 
`http status code: 400, body: {"errors":[{"code":"GOOGLE_MANIFEST_DANGLING_TAG","message":"Manifest is still referenced by one or more tags"}]}`

**Versions:**

- harbor version: 2.9.0

**Comment by chlins** [comment]
It seems the manifest still has other tag reference to it in GAR, so harbor failed to delete it, could you check it from the GAR?

**Comment by chandlerlow** [comment]
The only tag reference to the manifest on the GAR side is the same tag as the manifest deleted from Harbor.

**Comment by chandlerlow** [comment]
The remote deletion works for manifests without tags
