### ISSUE TITLE
"CSRF token invalid" error

### ISSUE THREAD

**Issue by zcourts** [goharbor/harbor#19502]
We're looking at migrating from directly using registry to harbor.
We have a Java based proxy in front of harbor. Needed for rate limiting and other organisational controls. 
Customers won't have access to harbor.
The proxy implements auth as described in https://distribution.github.io/distribution/spec/auth/token
Initial requests are allowed to hit /v2 and when the www-authenticate response is returned, we automatically send another request to authenticate and get a token.

The whole process appears to work, some blob uploads even appear to be successful...but at some point, one of the manifest requests fails with the "CSRF token invalid" error message.

I tracked this down to the gorilla package here https://github.com/gorilla/csrf/blob/94b5a9efbc27ce51c4ac1b1287c964e8f13013ca/csrf.go#L51 but not being familiar with the harbor source (or being a go developer for that matter), it was a hard to find why it fails.

In the requests, there's a _gorilla_csrf cookie in the response.

I don't have a link but also tracked down the harbor code and found there is an exception made for `/v2` and `/service/token`. 

Hence, me wondering if this is a bug or if we're sending (or not sending) some header and it is treating our proxy requests as if they're coming from a browser.

The question is how do we either disable the CSRF check (its internal and not expose to the internet so not an issue) or get it to accept our requests

(Saw https://github.com/goharbor/harbor/issues/12676 from 2020 but the `EnableXSRF = true` option doesn't seem to exist anymore to be turned off)

FYI harbor is deployed in k8s with https://github.com/goharbor/harbor-helm

**Comment by chlins** [comment]
Currently there is no option to support disable the CSRF check, but you can refer to the internal nginx configuration for proxy.
