### ISSUE TITLE
Harbor Postgres 15

### ISSUE THREAD

**Issue by brothercalifornia1** [goharbor/harbor#19512]
Hi, in the 2.9 version of documentation it is described that the Harbor configuration is available for Postgres 13. Is Postgres 15 supported? If it is described somewhere in the documentation, please link it

**Comment by chlins** [comment]
We have not yet verified the pg15, the latest verified pg version is 14.

**Comment by brothercalifornia1** [comment]
Hi, when will pg 15 be verified? Because we would like to upgrade the version and we would like to have confirmation whether everything will be OK

**Comment by brothercalifornia1** [comment]
So if I understood corectly you will check it in new version of docuemntation? Can you tell me when can I expect a resolve of my question?

**Comment by YangJiao0817** [comment]
Plan to upgrade to PG15 in v2.11.0 .
