### ISSUE TITLE
Selfsigned CA not working in core

### ISSUE THREAD

**Issue by mverleun** [goharbor/harbor#19515]
We've deployed Habor using a helm chart that is bundled with Rancher.
The version deployed is version 2.8.4

We;ve created a secret with our own CA's which is mounted inside the core container at `/etc/core/ca/ca.crt`

At boot time a script is executed to append this certificate to `/etc/pki/tls/certs/ca-bundle.crt`, see the link below.
https://github.com/goharbor/harbor/blob/f75a2f9407cb6ef9093030950b94eff8e41e05b0/make/photon/common/install_cert.sh#L20
Unfortunate an attempt is made to copy the `ca.crt` file from `/etc/harbor/ssl` which does not exist.

Either the helm chart mounts the secret at the wrong location or the script is wrong.

As a result any outbound connections to upstream registies with selfsigned CA will fail unless the SSL check is disabled.

**Comment by chlins** [comment]
Did you use the harbor official helm chart? if not please check the container image and helm resources, it may have difference between them then break this issue, the official image should work for cert copy.
