### ISSUE TITLE
Replication Failing between Harbor and Quay when using wildcards

### ISSUE THREAD

**Issue by hordrisstheconfuser** [goharbor/harbor#19516]
Bit of an odd one. I'm trying to configure harbor to replicate with an on prem Quay instance. Harbor is 2.8.2 and Quay is 3.9.0

I'm finding if I put the entire name to an artifact e.g org/artifact the replication job succeeds but if I use organization then wildcards e.g. org/** I get error "failed to fetch artifacts: http status code: 403, body:"

Can't find any reference to the 403 in any of the logs in /var/log/harbor/ or in any of the container logs. 

Am a bit stuck as the upstream repo I want to replicate has 400+ artifacts and don't really want to create a replication per artifact.

**Comment by chlins** [comment]
Did you configure the credential for the quay registry?

**Comment by hordrisstheconfuser** [comment]
I'm using credentials to access the project that contains the artifacts and without them if I use the full path it doesn't work so the credentials are working. It seems to be unable to retrieve the list of artifacts whenever I use a wildcard.

I'm guessing this is done via an api call but can't see in logs what this would be to test with curl?

**Comment by chlins** [comment]
For the wildcard, harbor needs to call the `/v2/_catalog` API to retrieve the lists of the artifacts, so you may check the response for this endpoint.

**Comment by hordrisstheconfuser** [comment]
I can access the above endpoint from harbor but it returns an empty list of repositories BUT that might be because I haven't authenticated via the curl and not 100% sure how to do this.

**Comment by chlins** [comment]
Could you paste the response header when you request to `https://quayurl/v2/_catalog`? Normally it will include the auth info.

**Comment by hordrisstheconfuser** [comment]
It returns an empty json with repositories. There are public repositories so I'm guessing this shouldn't be empty? Or is authentication mandatory? If so what url needs to be passed so I can check e.g. does it pass https://quayurl/v2/_catalog?access_token=.... when I run a replication?
