### ISSUE TITLE
upgrade from 2.8.0 -> 2.9.0 database is upgraded from pg13 -> pg14 resulting in files not found

### ISSUE THREAD

**Issue by rakkenes** [goharbor/harbor#19522]
so, I have recently tried to upgrade from 2.8.0 -> 2.9.0

I noticed that when I looked in my projects, all my projects where there, but when I open a project I could see the list of all the repositories, but when opening them, they were all empty.. 

then when I looked at the database I could se that there were now two folders pg13 (same as before) but also pg14.. and the pg14 folder was much smaller than the pg13. 

I could not see anything in the logs that pointed at anything.. and since I have had harbor down for many hours now, I rolled back, and wen to to 2.8.4 and left this for another day... but any hints would be nice thanks.

**Comment by chlins** [comment]
Could you please provide the logs of harbor-db during upgrade from 2.8.0 to 2.9.0?

**Comment by ronaldshaooo** [comment]
@rakkenes 
I have same issue from 2.8.2 to 2.10.0
Delete the 'var' folder and restart services then issue gone.
