### ISSUE TITLE
when *Configuring Storage Backend*  as s3 don't support virtual host access

### ISSUE THREAD

**Issue by charlesgogo01** [goharbor/harbor#19526]
when *Configuring Storage Backend*  as s3 don't support virtual host access

after configured storage_server as s3, then the access style is s3.us-east-1.amz.com/bucket/obejct. 
We expect it to be bucket.s3.us-east-1.amz.com/obejct.

**Comment by chlins** [comment]
The storage related configuration is exposed by upstream project [distribution](https://github.com/distribution/distribution), so you may need to search the solution from upstream.
