### ISSUE TITLE
single level repositories 

### ISSUE THREAD

**Issue by babumiriyala** [goharbor/harbor#19521]
401 for single level repositories 
**Expected behavior and actual behavior:**
 failed to pull and unpack image "<harbor_server_name>/<proxy_project_name>/bitnami/kubectl:1.12.3": failed to resolve reference "<harbor_server_name>/<proxy_project_name>/bitnami/kubectl:1.12.3": pulling from <harbor_server_name> failed with status code [manifests 1.12.3]: 401 Unauthorized

`      - name: kubectl
        image: bitnami/kubectl:1.12.3`

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
`      - name: kubectl
        image: bitnami/kubectl:1.12.3`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.8.4

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
`harbor-core-c65d458-tjq72 core 2023-11-01T08:49:38Z [ERROR] [/server/middleware/repoproxy/proxy.go:121]: failed to proxy manifest, fallback to local, request uri: /v2/dockerhub-proxy/library/prom/statsd-exporter/manifests/v0.22.4, error: http status code: 401, body:`

and I use the mutating webhook rule from this repo https://github.com/indeedeng-alpha/harbor-container-webhook/blob/main/deploy/charts/harbor-container-webhook/values.yaml
`rules:
  - name: 'docker.io rewrite rule'
    matches:
      - '^docker.io'
    excludes:
      - '.*goharbor.*'            
    replace: '<harbor_server_name>/<proxy_project_name>'
    checkUpstream: false
`

**Comment by chlins** [comment]
The `bitnami/kubectl:1.12.3` is not the single level, `bitnami` is the namespace, please check the credential used for the registry, and is your proxy cache project set to public?
