### ISSUE TITLE
trivy cannot parse redis url

### ISSUE THREAD

**Issue by MinpuKang** [goharbor/harbor#19568]
Hello Expert

Is there any comment for below error of trivy pod with crash status?
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2023-11-12T12:26:34Z","version":"dev"}
{"level":"fatal","msg":"Error: constructing connection pool: invalid redis URL: parse \"redis://harbor-redis:6379/%!s(\u003cnil\u003e)?idle_timeout_seconds=30\": invalid URL escape \"%!s\"","time":"2023-11-12T12:26:34Z"}

Thank you
BRs/Minpu

**Comment by AllForNothing** [comment]
Can provide more context?
1. When does it happen?  In an installation?
2. What's your Harbor version?

**Comment by zyyw** [comment]
@MinpuKang you may need to change the `trivyAdapterIndex` to `"5"` in string format, instead of using integer `5`.

**Comment by MinerYang** [comment]
you probably add  character like `<>` in your value.yaml
