### ISSUE TITLE
Harbor Version v2.9.0-44f5702 doesn't tag the last pushed image as latest

### ISSUE THREAD

**Issue by rajbaratht** [goharbor/harbor#19574]
How can we help you?

Hello - We upgraded harbor from Version v2.8.2-d4c34dc to v2.9.0-44f5702 and we noticed that the last pushed images are no longer automatically tagged as latest.  We usually remove the tag latest and push the new images and the image would be tagged as latest. However, it's no longer working. Is this expected behaviour ? I checked the release notes and didn't find anything related to this. Can you please advise ?

![image](https://github.com/goharbor/harbor/assets/73351998/324268d4-c628-4f31-ac23-90c4864bca3a)

**Comment by AllForNothing** [comment]
@rajbaratht 
Harbor won't automatically tag an image according to the push time.
Please check your push process/pipeline to see if there is a step that will tag the images
