### ISSUE TITLE
主从备份配置失败

### ISSUE THREAD

**Issue by BruceShi2006** [goharbor/harbor#19589]
配置harbor主从备份的时候，主配置成功，从失败，
下面是错误信息：

Nov 18 15:15:37 172.18.0.1 core[8362]: 2023-11-18T07:15:37Z [INFO] [/pkg/notifier/notifier.go:205]: Handle notification with Handler 'AuditLog' on topic 'CREATE_PROJECT': ID-2 Name-baseimages Operator-admin OccurAt-2023-11-18 07:15:37
Nov 18 15:52:40 172.18.0.1 core[8362]: 2023-11-18T07:52:40Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:52:43 172.18.0.1 core[8362]: 2023-11-18T07:52:43Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:52:45 172.18.0.1 core[8362]: 2023-11-18T07:52:45Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:54:19 172.18.0.1 core[8362]: 2023-11-18T07:54:19Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:55:39 172.18.0.1 core[8362]: 2023-11-18T07:55:39Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:55:44 172.18.0.1 core[8362]: 2023-11-18T07:55:44Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 15:57:00 172.18.0.1 core[8362]: 2023-11-18T07:57:00Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 16:03:49 172.18.0.1 core[8362]: 2023-11-18T08:03:49Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token
Nov 18 16:04:15 172.18.0.1 core[8362]: 2023-11-18T08:04:15Z [ERROR] [/pkg/reg/adapter/native/adapter.go:126]: failed to ping registry http://192.168.178.142: json: cannot unmarshal number into Go value of type bearer.token

**Comment by AllForNothing** [comment]
What's your Harbor version? Can you provide more context for this?
