### ISSUE TITLE
Unable to change `read_only` to false via API as administrator

### ISSUE THREAD

**Issue by jimsmith** [goharbor/harbor#19585]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

In relation to backups: https://github.com/goharbor/website/blob/release-2.9.0/docs/administration/backup-restore/_index.md#backup-harbor-instance-1

We want to be able to do this programmatically so backups are ran via pipeline and not by humans. 

- When logged into API as `admin` credentials  I am able to set `read_only` to `true` 
- When logged into API as `admin` credentials  I am **unable** to set `read_only` to `false`

Expect `read_only` to be set to `false` so harbor is once again usable after backup has completed.

**Steps to reproduce the problem:**

```
$ curl -k -u "${USERNAME}:${PASSWORD}" -X POST "${HARBOR_API_ENDPOINT_URL}/configurations" -H "Content-Type: application/json" -d '{
  "read_only": false,
  "banner_message": ""
  }
}'
{"errors":[{"code":"DENIED","message":"The system is in read only mode. Any modification is prohibited."}]}
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.9.0 (latest)] Helm Charts

**Comment by stonezdj** [comment]
Method should be PUT
https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml#L247

**Comment by jimsmith** [comment]
Hey thanks, an oversight on my part due to reusing most of the same curl command when creating a registry.

:)
