### ISSUE TITLE
Harbor OIDC with ADFS integration

### ISSUE THREAD

**Issue by kasper0811** [goharbor/harbor#19587]
Hi, everyone.
I'm trying integrate Harbor with ADFS openid.
I have setup ADFS:
Name - Harbor_adfs
Endpoint - https://adfs.domain/adfs
Client ID - harbor
Client Secret - generated secret
Relying Party Identifier - harbor
Redirect URI -  https://harbor.domain/c/oidc/callback
LDAP Claim - sAMAccountName -> Username
group claim - send all groups

Harbor OIDC settings:
OIDC Provider Name - Harbor_adfs
OIDC Endpoint - https://adfs.domain/adfs
OIDC Client ID - harbor
OIDC Client Secret - generated secret
Group Claim Name - group
OIDC Admin Group -  harbor_admin
OIDC Scope - openid,email,profile,offline_access,group
Automatic onboarding Unchecked, because with Checked Automatic onboarding I get "Server Error"
But with Unchecked onboarding I'm creating username like AD sAMAccountName and don't get admin privileges, and I do not get any ID token (trying to find ID token in browser Dev tools F12)
I would appreciate any information about what I'm doing wrong.

**Comment by stonezdj** [comment]
You should check the harbor-core log to get the detail log when you get the "Server Error".
Don't get admin privileges, you should check the `group name claim` is configured correctly and the current user is in the harbor_admin group.

The ID token is not returned after the user login to the OIDC provider, the OIDC provider just return a code to the application and the application could request token through the code.

**Comment by kasper0811** [comment]
[stonezdj](https://github.com/stonezdj) tnx for your answer.
I've checked the harbor-core log and I'm getting warnings below:
OIDC. Failed to recover Username from claim. Claim 'upn' is invalid or not a string
2023-11-20T09:58:32Z [WARNING] [/pkg/oidc/helper.go:394]: Unable to get groups from claims, claims: map[sub:mzYw47+TQELxoy5W5GjR6D35hpAB3MQDAJNJ5ZVdLes=], groups claims key: harbor_admin
and the same for groups claims key: group
On ADFS side configuration:
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", Issuer == "AD AUTHORITY"]
 => add(store = "Active Directory", types = ("http://schemas.xmlsoap.org/claims/Group"), query = ";tokenGroups;{0}", param = c.Value);

**Comment by kasper0811** [comment]
Found solution about OIDC AFDS integration here:
[here](https://stackoverflow.com/questions/55494354/user-groups-as-claims-through-openid-connect-over-adfs)
Thanks for everyone
