### ISSUE TITLE
Does any Harbor component trigger blob deletion requests

### ISSUE THREAD

**Issue by djdongjin** [goharbor/harbor#19583]
We have harbor running on Azure (blob). We noticed there are object deletion requests on Azure blob (from cloud provider metrics). However,

1. we didn't enable GC;
2. we didn't delete images (at least from harbor core/registry metrics we didn't observe any DELETE requests).

We're still looking into if it's caused by cloud provider or there are unexpected image deletion on our side. Meanwhile curious given 1 and 2, is there any other Harbor component that may send requests to delete blob objects (e.g., even some metadata).

Thanks!

**Comment by Vad1mo** [comment]
can be reports, that can be stored as OCI artifacts. Or it might be deletion of failed multipart file uploads.

**Comment by AllForNothing** [comment]
Is there any Push-based replication rule targeted to Azure in your Harbor?
<img width="649" alt="Screenshot 2023-11-20 at 13 06 18" src="https://github.com/goharbor/harbor/assets/30999793/7027de31-7db9-4932-980d-e0d949791892">

**Comment by djdongjin** [comment]
@AllForNothing thanks for the info. Yeah we do have another harbor endpoint that has a push-based replication rule targeting this Azure harbor (and enabled the `Delete remote ...` box).

So this will cause delete operations on the blob storage of target harbor? Can you help explain what this feature does? My understanding is if there is an image deletion on source harbor, it will also be replicated to dst harbor, causing the deletion there as well? (Sorry I could find the "explanation" icon on my harbor UI 😅)

Thanks!

**Comment by AllForNothing** [comment]
@djdongjin Can you provide the detail content of the deletion requests?

**Comment by djdongjin** [comment]
We didn't enable azure blob access log so couldn't find the exact deleted content (e.g., filename, etc). I'll update here if I could find some details from other sources. thanks!

**Comment by AllForNothing** [comment]
> So this will cause delete operations on the blob storage of target harbor? Can you help explain what this feature does? My understanding is if there is an image deletion on source harbor, it will also be replicated to dst harbor, causing the deletion there as well? (Sorry I could find the "explanation" icon on my harbor UI 😅)

You can refer to the doc https://goharbor.io/docs/2.9.0/administration/configuring-replication/create-replication-rules/

If you delete an image in your Harbor, then your Harbor will send a delete request to the remote registry(Harbor doesn't care how the remote registry handles this request).

the "explanation" icon was added in version 2.10.0

You can set such a replication rule, delete an image in your Harbor, and see if there is a corresponding deletion request in your Azure registry.

Except for the replication rule, Harbor will not trigger the deletion of the remote registry in any component.

**Comment by djdongjin** [comment]
@AllForNothing sorry for the late reply!

Actually I found the deletion events also happen in our leader Harbor on AWS (S3), i.e., no any registries replicating TO this harbor. And we don't delete any images (only 1 delete log from long ago).

<img width="1071" alt="image" src="https://github.com/goharbor/harbor/assets/28295179/c95daff7-b146-4535-b7c7-7d585e9a213f">

So I guess these blob deletion events are not related to replication or image deletion.

Actually, if we retag an image and let the tag point to a different image manifest, will that trigger a deletion? (delete the existing tag, recreate the same new tag pointing to the new image manifest)?
