### ISSUE TITLE
whether to consider supporting same tag name different platform container ?

### ISSUE THREAD

**Issue by nAnderYang** [goharbor/harbor#19580]
whether to consider supporting same tag name different platform container ?

one docker container like
`F.Q.D.N/pj/somesvc.latest`

Multi-platform container in the tag. 
For example: `x86` `arm64`  `riscv64` `mips64` `s390x`.

now i use different  tag name temporary solution the problem
`F.Q.D.N/pj/somesvc-x86:latest`
`F.Q.D.N/pj/somesvc-aarch64:latest`

thanks.

**Comment by Vad1mo** [comment]
interesting can you elaborate more? Did you see is somewhere elase and what is the purpose of this. How should the logic look like, cean you describe?

**Comment by AllForNothing** [comment]
@nAnderYang 
Does the image index meet your requirements?

**Comment by nAnderYang** [comment]
i have use docker buildx build multi platform container, but the tag name same.
 now a container needs to be build multiple times and given different tag names.

example:

original container:
harbor.mydomain.com/project/api-x86 arm64 riscv64 mips64 s390x:latest
harbor.mydomain.com/project/api-x86 arm64 riscv64 mips64 s390x:latest
harbor.mydomain.com/project/api-x86 arm64 riscv64 mips64 s390x:latest


the container like harbor.mydomain.com/project/api:latest

**Comment by nAnderYang** [comment]
thanks flow, i update harbor to new version, the muitl arch already supported.
