### ISSUE TITLE
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule

### ISSUE THREAD

**Issue by lijie123bes** [goharbor/harbor#19591]
[root@k8s-master harbor]# ./install.sh    //执行Harbor安装脚本
[Step 0]: checking if docker is installed ...
Note: docker version: 19.03.13
[Step 1]: checking docker-compose is installed ...
Note: docker-compose version: 1.18.0
[Step 2]: loading Harbor images ...
103076ba7411: Loading layer [==================================================>]  121.2MB/121.2MB
fde3b64438e3: Loading layer [==================================================>]  3.072kB/3.072kB
249a34ecfbe2: Loading layer [==================================================>]   59.9kB/59.9kB
35783e12f32a: Loading layer [==================================================>]  61.95kB/61.95kB
Loaded image: goharbor/redis-photon:v2.3.2
7301dee185fe: Loading layer [==================================================>]  8.746MB/8.746MB
Loaded image: goharbor/nginx-photon:v2.3.2
...
...
loaded secret from file: /data/secret/keys/secretkey
Generated configuration file: /compose_location/docker-compose.yml
Clean up the input dir
[Step 5]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-9803204bb769 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))

**Comment by AllForNothing** [comment]
@lijie123bes This should be a network issue from the docker side.  You can restart your docker client, and then reinstall harbor.

And it seems you are using version 2.3.2, which is out of maintenance,  please try the latest version if possible

**Comment by lijie1010** [comment]
thank you!

**Comment by lijie123bes** [comment]
thank you!
