### ISSUE TITLE
The robot account permission check box is not aligned

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19615]
<img width="957" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/d7c76c18-c130-46eb-9707-dd361eedbf53">

<img width="968" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/8e05f4f9-57d8-4098-a0e5-38131d94dcb4">

**Comment by AllForNothing** [comment]
If we use the same width for each column, there will not be enough space for all the columns, so keep the current style
