### ISSUE TITLE
Replication failed with system level robot account

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#19622]
1. Install 2 Harbor instances A and B
2. Create system level robot account in Harbor A and create a system robot account with all system level permission and all project level permissions.
3. Create a registry in HarborB, create a replication rule to replicate images from library/** to B's library project.
4. Run the Replication rule, it failed with 403 error.
<img width="1015" alt="Screenshot 2023-11-27 at 15 18 47" src="https://github.com/goharbor/harbor/assets/2696760/ed441147-a789-4a5c-a95f-63640a2471c5">

It failed to access the API (403)
`
GET /api/v2.0/projects/library/repositories 
`
The robot account has permission to list repository 

<img width="689" alt="Screenshot 2023-11-27 at 15 21 59" src="https://github.com/goharbor/harbor/assets/2696760/21a551b9-2ef7-4de4-b2ef-f4e387fb4ce5">

If replace the system level robot account with project level robot account, it works

**Comment by AllForNothing** [comment]
@wy65701436 The root cause is that a system permission will invalidate all the project permissions
