### ISSUE TITLE
Guest navigation on public projects

### ISSUE THREAD

**Issue by jprmachado** [goharbor/harbor#19630]
How can we help you?

When browsing public projects 
![Screenshot from 2023-11-27 09-59-15](https://github.com/goharbor/harbor/assets/4732041/013c95a0-2a7b-4271-90c4-4693fadd1d87)

If someone tries to click on the breadcrumb to navigate to project is prompt to login.

![Screenshot from 2023-11-27 09-59-27](https://github.com/goharbor/harbor/assets/4732041/8e5fa59a-25c3-4d09-a776-e396f73efe64)

Then is not possible to return to the previous page neither it shows the list of public projects. Is this intentional?

**Comment by AllForNothing** [comment]
@jprmachado Thanks for the info.
This is currently a UI navigation limitation, we are considering enhancing it in 2.11
