### ISSUE TITLE
Add Automaxprocs to go code as we mostly run in containers

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#19643]
**Is your feature request related to a problem? Please describe.**
When the Go runtime starts it creates an OS thread for each CPU core. This means if you have a 16 core machine the Go runtime will create 16 OS threads - regardless of any CGroup CPU Limits. The Go runtime then uses these OS threads to schedule goroutines.

The problem is that the Go runtime is not aware of the CGroup CPU limits and will happily schedule goroutines on all 16 OS threads. This means that the Go runtime will expect to be able to use 16 seconds of CPU time every second.

Long stop the world durations arise from the Go runtime needing to stop Goroutine on threads that it’s waiting for the Linux Scheduler to schedule. These threads will not be scheduled once the container has used it’s CPU quota.

**Describe the solution you'd like**
Go allows you to limit the number of CPU threads that the runtime will create using the GOMAXPROCS environment variable. This time I used the following command to start the container

`docker run --cpus=4 -e GOMAXPROCS=4 -p 8080:8080 $(ko build -L main.go)`

This can be done manually, but why should it if a good out of the box solution is so easy to implement.

[A clear and concise description of what you want to happen.](https://github.com/uber-go/automaxprocs)

**Describe the development plan you've considered**

```go
import _ "go.uber.org/automaxprocs"

func main() {
  // Your application logic here.
}
```

**Additional context**
Here is an excellent explanation of the background of the problem.

https://www.riverphillips.dev/blog/go-cfs/

**Comment by philippw** [comment]
Prometheus has this implemented and exposes it as [`--auto-gomaxprocs`](https://prometheus.io/docs/prometheus/latest/command-line/prometheus/).

If you use Kubernetes CPU limits, setting this to the same value, is essential for good performance. Would be nice to have this implemented by default!

The same holds true for `GOMEMLIMIT` BTW, which is important to set if you use memory limits.
Of course, you can work around it using `extraEnvVars`, like so:
```
  extraEnvVars:
    - name: GOMEMLIMIT
      value: "${jobservice.gomemlimit}"
```

But that's ugly and should be handled in the go code instead.
