### ISSUE TITLE
Can't get data with /search api v2 with robot account from private projects

### ISSUE THREAD

**Issue by elysiumHL** [goharbor/harbor#19657]
- harbor version: [2.6.4,2.7.4,2.9.1]
- docker client engine version: [20.10.2]
- docker server engine version: [24.10.7]
- docker-compose version: [1.29.2]

**Additional context:**

- I have a project robot account with all privilege in this project
![image](https://github.com/goharbor/harbor/assets/17973558/6d5e0715-5892-4b62-a048-c863f22fc344)

- when use search api with this robot account, I can't get any infomation with the private project 
![image](https://github.com/goharbor/harbor/assets/17973558/f0900d48-ea86-402d-80a5-e131a962f7c2)

- but when use the normal user, all seems pretty good
![image](https://github.com/goharbor/harbor/assets/17973558/efb021cd-67e8-435b-9806-74e30eaa92c1)

- I think these issues are same to minie
https://github.com/goharbor/harbor/issues/17218
https://github.com/goharbor/harbor/issues/18628

**Comment by wy65701436** [comment]
As it stands, robots are intentionally unable to access the search API.
