### ISSUE TITLE
Database password error on fresh install

### ISSUE THREAD

**Issue by batusekerci** [goharbor/harbor#19653]
Hello,
When I installed 2.9.1 version with offline installer and used default harbor.yml file(only change is hostname) I suspected that my jobservice and core containers are always restarting . Then when I looked the postgre.sql.log I encounter with the error:

```
postgresql[2020]: LOG:  database system is ready to accept connections
postgresql[2020]: FATAL:  password authentication failed for user "postgres"
postgresql[2020]: DETAIL:  Connection matched pg_hba.conf line 100: "host all all all md5"
``` 

In core.log:

```
register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres"
``` 

I changed the default password from yml file and run the install.sh again but same result.

System:
Ubuntu 22.04 
Docker Compose v2.21.0
Docker 24.0.6

**Comment by MinerYang** [comment]
try to connect your database manually if it is a external one, probably need to set the `pg_hba.conf` file of pg server like bellowing  
```
# IPv4 local connections:
host    all             all             all              password
```

**Comment by wy65701436** [comment]
can you clean your data directory and then re-install it?

**Comment by remkolems** [comment]
Unfortunately, I encountered the exact same error and was therefore unable to log into harbor (or anything actually).

harbor-core
```
2024-01-03T11:44:23Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
[ORM]2024/01/03 11:44:23 register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
2024-01-03T11:44:23Z [FATAL] [/core/main.go:184]: failed to initialize database: register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

harbor-db
```
2024-01-03 11:45:02.674 UTC [637] FATAL:  password authentication failed for user "postgres"
2024-01-03 11:45:02.674 UTC [637] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all md5"
```

Details
- docker Compose version v2.21.0
- docker version 24.0.7
- Ubuntu 22.04
- Harbor installed via harbor-online-installer-v2.10.0.tgz

**Comment by MinerYang** [comment]
Are you using external database?

**Comment by remkolems** [comment]
I'm not using any external database.

I used the online installer V2.10.0 from release (that includes the database) on my Ubuntu node.

Thank you for your reply.

**Comment by dasantonym** [comment]
I just ran an upgrade to the most recent Helm Chart version (1.14.0) and suddenly also lost connection to the database with the exact same error. I have checked the secrets and successfully used the credentials to log in via psql. I don't have the option to drop the database and now basically broke the install so this would be quite urgent to get fixed.

**Comment by dasantonym** [comment]
I saved myself for now by deactivating the password for `harbor-database` in `pg_hba.conf`, but a fix this is not...

**Comment by MinerYang** [comment]
for offline-installer,  I have noticed that you mentioned you were install harbor 2.9 but provided `Harbor installed via harbor-online-installer-v2.10.0.tgz`. There's might be some legacy data remained and been corrupted. Please back up your `data_volume` directory and try to delete the `/<data_volume>/database/*`, default to be `/data/database` .
As it for harbor-helm, please make sure your defined the same database password or any other  secrets/password be consistent with previous instance in values.yaml.

**Comment by dasantonym** [comment]
Just FYI: apparently, my specific issue seems to be related to the Helm Chart and might already be covered by this: https://github.com/goharbor/harbor-helm/issues/1674

**Comment by ps245** [comment]
This still seems to be an issue, Using docker-ce 28.3.2 on Debian 12.

```
[INFO] [/core/controllers/base.go:187]: Config path: /etc/core/app.conf
[INFO] [/core/main.go:148]: initializing cache ...
[INFO] [/core/main.go:167]: initializing configurations...
[INFO] [/lib/config/systemconfig.go:178]: key path: /etc/core/key
[INFO] [/lib/config/config.go:92]: init secret store
[INFO] [/core/main.go:169]: configurations initialization completed
[INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
[ORM] Register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
[FATAL] [/core/main.go:190]: failed to initialize database: Register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

Is what i see in my logs. Correct passwords are set in `./common/config/db/env` and `./common/config/core/env` by the installer.

**Comment by 3c905** [comment]
I have  the same issue ,  docker-ce 26 on  centos8    


I  from harbor-2.8.4 upgrade to  2.9.0 2.9.5  2.10.0 2.10.3   totral is fail ， only upgade 2.8.6 is successful

Harbor installed via harbor-online-installer-v2.9.0.tgz
Harbor installed via harbor-online-installer-v2.10.0.tgz

Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/pkg/reg/adapter/quay/adapter.go:53]: the factory of Quay adapter was registered
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:55]: the factory for adapter tencent-tcr registered
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/core/controllers/base.go:159]: Config path: /etc/core/app.conf
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/core/main.go:142]: initializing cache ...
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/core/main.go:161]: initializing configurations...
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/lib/config/systemconfig.go:178]: key path: /etc/core/key
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/lib/config/config.go:92]: init secret store
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/core/main.go:163]: configurations initialization completed
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
Oct 16 10:55:53 172.18.0.1 core[26076]: [ORM]2025/10/16 02:55:53 register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
Oct 16 10:55:53 172.18.0.1 core[26076]: 2025-10-16T02:55:53Z [FATAL] [/core/main.go:184]: failed to initialize database: register db Ping `default`, failed to connect to `host=postgresql user=postgres database=registry`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
Oct 16 10:55:53 172.18.0.1 core[26076]: Appending internal tls trust CA to ca-bundle ...
Oct 16 10:55:53 172.18.0.1 core[26076]: find: '/etc/harbor/ssl': No such file or directory
Oct 16 10:55:53 172.18.0.1 core[26076]: Internal tls trust CA appending is Done.
