### ISSUE TITLE
Harbor is powered off. postgres reports an error

### ISSUE THREAD

**Issue by lijie123bes** [goharbor/harbor#19652]
Harbor is powered off. postgres reports an error: could not locate a valid checkpoint record

```
Oct 21 15:07:40 172.26.0.1 postgresql[46146]: PANIC:  could not locate a valid checkpoint record
Oct 21 15:07:40 172.26.0.1 postgresql[46146]: LOG:  incomplete startup packet
Oct 21 15:07:40 172.26
```

**Comment by wy65701436** [comment]
it would be helpful if you could provide us with more details, like your Harbor version, and the steps to reproduce the issue.
