### ISSUE TITLE
Stuck on queued at vulnerability scan

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor#19655]
hi 
I ran a scan for vulnerability lookup while using harbor and it is stuck in queue and not progressing.
<img width="2040" alt="스크린샷 2023-11-30 오후 8 58 00" src="https://github.com/goharbor/harbor/assets/62255222/cef8faa8-3bc9-459f-a214-5e1500abe215">

When I checked the related DB table, the job is still in the pending state and it doesn't seem to be progressing.

```
registry=> select * from task where status != 'Success' and status != 'Stopped';
   id   | execution_id |          job_id          | status  | status_code | status_revision | status_message | run_count |                                                                        extra_attrs                                                                         |       creation_time        | start_time |        update_time         | end_time | vendor_type 
--------+--------------+--------------------------+---------+-------------+-----------------+----------------+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+------------+----------------------------+----------+-------------
 307257 |       164617 | d318c1b17dff242a33f02544 | Pending |           0 |               0 |                |         0 | {"artifact_id":244533,"artifact_tag":"ab7c041014073fb535b192d7c30ef02ae63bf123","report_uuids":["69402bfb-0e44-45be-8b14-d3306614aadc"],"robot_id":273794} | 2023-11-30 11:53:48.588734 |            | 2023-11-30 11:53:48.588734 |          | IMAGE_SCAN
(1 row)
```

I am using harbor by installing it through helm. The chart version is 1.13.0 (app version: 2.9.0), and the kubernetes version is 1.28.
And I'm using trivy, which belongs to harbor helm, as a scanner.

Please let me know how I can resolve this situation.
Let me know if there's anything else I need to know

**Comment by derekcha** [comment]
Additionally, I also looked up the table below today.
Hope this helps

```
registry=> select * from job_queue_status ;
id | job_type | paused | update_time
----+------------+--------+-------------------------------
4 | IMAGE_SCAN | t | 2023-12-01 02:10:03.496704+00
5 | SCHEDULER | t | 2023-12-01 02:10:03.49915+00
```

**Comment by zyyw** [comment]
<img width="1710" alt="Screenshot 2023-12-04 at 10 28 30" src="https://github.com/goharbor/harbor/assets/6709992/c7463796-a939-4611-b984-7c9ffc4415a9">
Maybe you can go to the `Job Service Dashboard` and check if the `Pending Count` for `IMAGE_SCAN` is 1, and then you can try to click the `RESUME` button to resume the image_scan job.
