### ISSUE TITLE
Export CVEs is not available for Robot nor Guest Accounts

### ISSUE THREAD

**Issue by Mai-Khattab** [goharbor/harbor#19650]
Hello,

I have a Harbor installation on v2.6.4, and observed that GUEST users are not allowed to export the CVEs list for the projects they have access to.
While trying to automate this using Harbor Robot accounts, I found that this permission is not of the available permissions for Robot Account (Only Scan create, stop and read).
Any idea if there is a workaround to fulfill that using Robot or Guest accounts, or if we can add the CVEs export to allowed operations?

Thanks,

**Comment by wy65701436** [comment]
Currently, it is by designed, and I will mark it as a feature request.

**Comment by pfarikrispy** [comment]
We are looking that same functionality, an automated way to export the found CVEs for an image in a repo.

Is this perhaps something that can be accomplished with the Security Hub and users who have that level of access?
