### ISSUE TITLE
Can we configure registry and webhook as Code (and via Helm)

### ISSUE THREAD

**Issue by sebglon** [goharbor/harbor#19673]
How can we help you?

We mana many registries and webhook.
And we want to source control all our configuration and deploy them with Helm.

I have found this old issue: https://github.com/goharbor/harbor/issues/2448#issuecomment-430108197
but i don't find any trace to the config on the repo.

**Comment by stonezdj** [comment]
Not sure if it meets your requirement,  https://goharbor.io/docs/2.9.0/install-config/configure-system-settings-cli/
```
Set Configuration Items Using An Environment Variable
Introduced in 2.3.0 is the ability to use an environment variable, CONFIG_OVERWRITE_JSON, in the core container to set the configuration. Once the CONFIG_OVERWRITE_JSON variable is set, you can only update or remove the configuration by updating the CONFIG_OVERWRITE_JSON and restarting the container. You will not be able to update the configuration in the Harbor interface or in the commandline.

Example CONFIG_OVERWRITE_JSON configuration:

CONFIG_OVERWRITE_JSON={"ldap_verify_cert":"false", "auth_mode":"ldap_auth","ldap_base_dn":"dc=example,dc=com", "ldap_search_dn":"cn=admin,dc=example,dc=com","ldap_search_password":"admin","ldap_url":"myldap.example.com", "ldap_scope":2}
```

**Comment by nmcostello** [comment]
@stonezdj I am running into a similar issue to the one above. We already have harbor deployed and running, is there a way to deploy the operator to only handle the Day 2 operations? I am actively searching in the repo for an answer.
