### ISSUE TITLE
Error when docker login Harbor

### ISSUE THREAD

**Issue by tsukiazuma** [goharbor/harbor#19674]
Hi,

I can't login with docker to Harbor with error like: Error response from daemon: Get "http://harbor.com.vn/v2/": EOF

How can I do to fix it.

Thank you

**Comment by stonezdj** [comment]
please check the harbor.com.vn is a reachable address. it is usually configured in the harbor.yml before installation.

**Comment by stonezdj** [comment]
How did you install the Harbor, through docker-compose or harbor-helm? please check the external_url env in harbor core container.

**Comment by abhijeetGithu** [comment]
Double-check your Docker registry configurations; a misconfiguration might be causing the issue

**Comment by BCI83** [comment]
For me, it was a mismatch in the ports specified in the harbor.yml and the portal ports in the docker-compose.yml as I was moving/migrating to a different server.
