### ISSUE TITLE
Install harbor using containerd instead of docker.

### ISSUE THREAD

**Issue by wangzhao123456** [goharbor/harbor#19672]
Hi, everone.  I created k8s cluster using sealos with container runtime being containerd. Now I want to install Harbor on one of k8s nodes. But installation of Harbor need to install docker first, and I don't want to install two kinds of container runtimes.  I wonder how to install Harbor using containerd instead of docker.
Thanks in advance.

**Comment by stonezdj** [comment]
Because you have a k8s cluster already,  you can install harbor via helm chart: https://github.com/goharbor/harbor-helm

**Comment by wangzhao123456** [comment]
> Because you have a k8s cluster already, you can install harbor via helm chart: https://github.com/goharbor/harbor-helm

Thanks for your reply. I noticed that installing harbor on k8s using helm chart is feasible. But it seems a little complicated. Is there any solutions to install harbor using containerd without docker？
