### ISSUE TITLE
internal server error when trying to log in using OIDC

### ISSUE THREAD

**Issue by berthevin** [goharbor/harbor#19694]
Hello,

We are using Harbor v2.9.1-5cbb1b0.

The configuration of OIDC parameters is shown in the capture below :

![oidc_config](https://github.com/goharbor/harbor/assets/153496881/e46c7378-91bd-4607-b609-d54e240d760f)

The OIDC connection test is working fine.

When we then try to log in using OIDC, we are correctly redirected to "login.microsoftonline.com" where a app registration has been made.

Once logged in to Microsoft, we're back to Harbor "Set OIDC Username" as shown in the capture below :

![set_oidc_username](https://github.com/goharbor/harbor/assets/153496881/8d83e7e8-2b18-4686-94e9-9e92d9dc4b07)

However, once we click "SAVE" button, we get an internal server error, as shown below :

![internal_server_error](https://github.com/goharbor/harbor/assets/153496881/800903d9-9e23-458a-a09d-bde5eae3b352)

Taken from the core log, we can see the following :

`2023-12-11T09:11:14Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"crypto/aes: invalid key size 64"}]}`

Is there a way I can fix that "crypto/aes" key size issue ?

Many thanks in advance.

Kind regards,
Berthevin

**Comment by stonezdj** [comment]
Please consider referring https://github.com/goharbor/harbor/issues/12158 for further exploration.

**Comment by berthevin** [comment]
Many thanks for the pointer.

I was able to fix the issue
