### ISSUE TITLE
System-level robot accounts can create and list projects even if they don't have Create and List Projects permissions

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#19704]
<img width="603" alt="图片" src="https://github.com/goharbor/harbor/assets/72076317/c90c474a-63b7-41b5-97de-96ea6c2d5c4a">

**Comment by wy65701436** [comment]
Since we should enable the capability of replicating images with a robot, by default, harbor grants the project creation permission for any system-level robot.
