### ISSUE TITLE
Setting up new registry end point error

### ISSUE THREAD

**Issue by pakkua80** [goharbor/harbor#19717]
I just setup a new harbor and trying out to setup a new endpoint registries. I selected dockerhub, key in the access ID, access secret. Click TEST CONNECTION, Connection Tested successfully. but when I click ok. it says internal server error.

I check on the docker logs harbor-core, the error came out as below.

![image](https://github.com/goharbor/harbor/assets/2527115/dde08cdb-d453-4b78-a287-4f7ec97ded4e)

Please do enlighten me if I miss out something. Thanks.

**Comment by stonezdj** [comment]
What is the Harbor version?

**Comment by pakkua80** [comment]
Version v2.9.0-44f5702

**Comment by stonezdj** [comment]
Please consider referring https://github.com/goharbor/harbor/issues/12158 for further exploration.
