### ISSUE TITLE
When updating password of mail server or other services on configuration part ,the password sent in the payload of PUT request shows as  cleartext

### ISSUE THREAD

**Issue by SoaadMahmoud** [goharbor/harbor#19720]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
when updating password of mail server or other services on configuration part ,the payload sent on PUT request mustn't be clear text and should be like "********"

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1- login into harbor with admin user 
2- go to configuration part on mail server tab 
3- open developer tools in browser
4- add an additional character to already existing password 
5-  you will able to see the password as a clear text on payload request 

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.6.4
- docker engine version: 1.13.1
- docker-compose version: 1.22.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by stonezdj** [comment]
the mail server configuration is removed from harbor, it is not a valid configure item.
