### ISSUE TITLE
sync aws ecr through interface vpc endpoint aws privalelink 

### ISSUE THREAD

**Issue by drouthier** [goharbor/harbor#19743]
We tried to configure a repository sync with aws ecr service on our aws accounts, using privatelink for security purpose without sucess.

We found that in this file https://github.com/goharbor/harbor/blob/main/src/pkg/reg/adapter/awsecr/adapter.go, a regexp expression is used to check service url :
    ecrPattern = "https://(?:api|(\\d+)\\.dkr)\\.ecr\\.([\\w\\-]+)\\.amazonaws\\.com"

and our privatelink ecr url is like https://vpce-xxxxxxxxxxxxxxxxx-xxxxxxxx.api.ecr.eu-west-1.vpce.amazonaws.com

Can you confirm our problem analysis ?

Is there any way to configure our aws ecr with privatelink url ?

**Comment by zyyw** [comment]
Dup of:
* https://github.com/goharbor/harbor/issues/18845

Currently, the private ecr url is not supported yet.
