### ISSUE TITLE
The project's "Quota used" is displayed incorrectly

### ISSUE THREAD

**Issue by cuonghqRose** [goharbor/harbor#19748]
I have a project with the displayed "Quota used" being 158.65MiB
![image](https://github.com/goharbor/harbor/assets/120639675/2fa6df15-40ef-4b93-b28e-5243bac6c3d6)

and I have 2 repositories as shown in the image above, this is the size of the artifacts in those repositories
![image](https://github.com/goharbor/harbor/assets/120639675/1cab0154-c117-41b2-8072-84af2bd7483c)
![image](https://github.com/goharbor/harbor/assets/120639675/31fef8bc-66fa-4128-95ef-dc2cfa0cdd03)

As everyone can see, the sizes of the above two artifacts are "42.65MiB" and "131.37MiB" respectively. If I add up the total size of those two artifacts, the "Quota used" should be "174.02MiB". However, the "Quota used" on the project's screen is "158.65MiB".

This is a completely new project and I have not deleted any artifacts, so GC is not necessary in my opinion.

Is this a problem or not?, I look forward to receiving your help.

harbor version 2.8.0

**Comment by a1zaza** [comment]
I guess whether it's possible that two images used the same layers, for instance, both using Alpine.

**Comment by cuonghqRose** [comment]
> I guess whether it's possible that two images used the same layers, for instance, both using Alpine.



> I guess whether it's possible that two images used the same layers, for instance, both using Alpine.

No, those are completely two different images with different layers
