### ISSUE TITLE
Use something else than Docker Hub for container images

### ISSUE THREAD

**Issue by berendt** [goharbor/harbor#19750]
The container images of Harbor are currently hosted on Docker Hub. We are currently running there regularly in rate limits. Yes, we now have a cache in between or mirror them when we upgrade our Harbor services. I still think it would be better to have them somewhere else initially.

If there is already an official mirror, I was not aware of it. The Helm charts should then also be switched to this by default if necessary.

**Comment by zyyw** [comment]
Users can `--set imagePullSecrets[0].name=dockerhub-cred` to bypass the rate limit issue when installing harbor via harbor-helm, where `dockerhub-cred` is created by command like this:
```
kubectl create secret docker-registry dockerhub-cred --docker-username=<your-docker-username> --docker-password=<your-docker-password> --docker-email=<your-docker-email>
```

**Comment by zyyw** [comment]
alternative you may also try ghcr:
* https://github.com/goharbor/harbor/pkgs/container/harbor-core

**Comment by rhizoet** [comment]
Is it possible, that some of the containers are not on ghcr? I've found out, that

- `nginx-photon`
- `harbor-db`
- `redis-photon`

are not on ghcr and I get an 404. Why these containers not on ghcr? Or do they have another name?
