### ISSUE TITLE
How to get the summary overview of vulnerabilties number using Harbor API

### ISSUE THREAD

**Issue by JackLehman** [goharbor/harbor#19768]
I would like to get the high level summary of the number of vulenrabilties reported by Trivy as it is shown in the UI but using the Harbor API
like:
Critical: X 
High: Y
I am using the latest release

This endpoint does not return the scan summary:
`/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/vulnerabilities`

**Comment by zyyw** [comment]
Maybe you can try the `Security Hub` api:
```
<harbor-endpoint>/api/v2.0/security/summary?with_dangerous_cve=true&with_dangerous_artifact=true
```
