### ISSUE TITLE
Access always unauthorized to robot account using curl

### ISSUE THREAD

**Issue by JackLehman** [goharbor/harbor#19769]
```
curl -X 'GET' \
  'https://example.com/api/v2.0/projects/test/repositories/test/artifacts/2.0/additions/vulnerabilities' \
  -H 'accept: application/json' \
  -H 'X-Request-Id: 12123124123' \
  -H 'X-Accept-Vulnerabilities: application/vnd.security.vulnerability.report; version=1.1'
```
The above request works on the swager UI but not using curl 
it shows: 
`{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}`

I have activated all permissions for all projects for the robot account.

I really don't understand this beahavior.

**Comment by zyyw** [comment]
You may need to pass the credential of the robot about to the curl API request with `-u "<robot-account-name>:<robot-account-secret>"`
