### ISSUE TITLE
Garbage collector should delete orphaned repositories

### ISSUE THREAD

**Issue by rgarcia89** [goharbor/harbor#19771]
**Is your feature request related to a problem? Please describe.**
Currently a repository begins to exists once an artifact belonging to it is downloaded. However, the reverse is not the case. This leads to many orphaned repositories in which there are no artifacts, because they have been removed by retention policies such as the one below.

![image](https://github.com/goharbor/harbor/assets/4134730/ee4263ec-6cee-419c-911b-ac95f5adb01a)

**Describe the solution you'd like**
Garbage collector should remove orphaned repositories.

**Comment by zyyw** [comment]
Hi @rgarcia89 , 
Could you please elaborate this sentence:
> Currently a repository begins to exists once an artifact belonging to it is downloaded. However, the reverse is not the case.

My understanding to this issue you created is:
After running tag retention, there are repositories with `0` artifacts and you wanna remove it after GC, but currently GC does  not delete these orphaned repositories, right?
<img width="1515" alt="Screenshot 2024-01-02 at 07 21 28" src="https://github.com/goharbor/harbor/assets/6709992/7fda181b-68e2-4ec0-8bfe-b240e36c76a7">

**Comment by zyyw** [comment]
Dup of:
* https://github.com/goharbor/harbor/issues/18313

**Comment by rgarcia89** [comment]
@zyyw true. Thanks for linking to the other issue ticket.
