### ISSUE TITLE
Pull Command Column is not showing in repo

### ISSUE THREAD

**Issue by Tahooralisyed** [goharbor/harbor#19776]
I have setup in harbor repo version 2.9.0 but after configuration when i check in projects tab for images. but there no pull command tab in that
![harbor](https://github.com/goharbor/harbor/assets/24992834/1823ba07-4eae-4376-9e49-75982fec8322)

**Comment by zyyw** [comment]
Please select the `checkbox` of an artifact, and the select the `COPY PULL COMMAND` drop-down menu.

**Comment by Tahooralisyed** [comment]
it not showing pull command option in drop down
![harbor2](https://github.com/goharbor/harbor/assets/24992834/77923b70-cbfe-4fa1-b086-bae5e8537da1)
![Uploading harbor1.PNG…]()

**Comment by Tahooralisyed** [comment]
Dear @zyyw also i tried check with artificates but there is not option
![Uploading harbor2.PNG…]()

**Comment by zyyw** [comment]
<img width="895" alt="Screenshot 2024-01-08 at 17 54 32" src="https://github.com/goharbor/harbor/assets/6709992/0289c678-a40c-4b63-b208-9ca61881cef3">

**Comment by Tahooralisyed** [comment]
thanks for help @zyyw
