### ISSUE TITLE
Harbor Replication not replicating user/group permissions.

### ISSUE THREAD

**Issue by SamuelBizon** [goharbor/harbor#19775]
I am currently trying to use 2 harbor instances, each one of them is helm installation. However, when replicating images from one harbor registry to another, it does not include the information about which users and groups have access to this images/projects.

Is this the intended behavior ? Is it necessary to use an external database for each instance and set up the replication to get this exact data replicated as well ? Is there any possible workarounds ?

**Comment by zyyw** [comment]
This is by design. Image replication only replicates image between two registries. 
You'll need to create users with the correct permission to access these images being replicated. Alternatively, you can use `admin` to access these images.
