### ISSUE TITLE
I can't add https://helm.goharbor.io for get helm chart 

### ISSUE THREAD

**Issue by AndreCbrera** [goharbor/harbor#19770]
Hello there !

Rigth now I want to use harbor from helm chart using a https://helm.goharbor.io url but I can't add the repository:

![image](https://github.com/goharbor/harbor/assets/38178990/8fea73d6-0823-48a0-932c-c3e958c09d71)

Actually I can add other repositories but this one is imposible and teh web page is empty:

![image](https://github.com/goharbor/harbor/assets/38178990/cc027d64-05b3-4135-a125-435f51979d77)

Is my problem ? what I'm doing wrong ?

thanks :^)

**Comment by Tchoupinax** [comment]
Hey,
I find weird you cannot use it as I use it to deploy my harbor (I just upgraded). I tested the command and it works on my side. Did you meet a temporary issue?
```
あ→ helm repo add harbor https://helm.goharbor.io
"harbor" has been added to your repositories
````

**Comment by AndreCbrera** [comment]
In my case I want to use in argocd but is imposible to add teh repository from argocd dashboard.

![image](https://github.com/goharbor/harbor/assets/38178990/feb15faf-e7ee-4837-b02a-b1aff7d05d25)

**Comment by zyyw** [comment]
The harbor chart artifacts are hosted here:
* https://artifacthub.io/packages/helm/harbor/harbor

Please try to `helm repo add harbor https://helm.goharbor.io` again, I can add repo without problem.
```
> helm repo add harbor https://helm.goharbor.io
"harbor" has been added to your repositories
```

**Comment by AndreCbrera** [comment]
Morning,

Sorry about that, I pissed up I'm a new hire in this company and I don't know that they have a proxy. I configured a proxy variables inside the pods and argocd for get access to the chart repositories.

Thanks for help me
