### ISSUE TITLE
Harbor v2.10.0 with Helm 3.13.x repo add error

### ISSUE THREAD

**Issue by ming-ddtechcg** [goharbor/harbor#19797]
Hi,

I would like to confirm that Harbor v2.8+ is no longer supported Helm repo add feature due to chartmuseum was removed, is it correct?

There is my environment information and error message:
Harbor version: [v.2.10.0]
Helm Version: [v3.13.3]
Docker Compose: [v2.23.3]
Docker Engine: [20.10.24]

Error message: [
$ helm repo add --username=admin --password=Harbor12345 [myharbor.com](http://myharbor.com/) https://myharbor.com:5001/helmchart

Error: looks like "https://myharbor.com:5001/helmchart" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
]

Based on the following issue, the newer version of Harbor release does not support index.yaml:
https://github.com/goharbor/harbor/issues/18720#issuecomment-1691038418

**Comment by MinerYang** [comment]
chartmuseum has been deprecated and removed since harbor 2.8, and index.yaml file is not available in OCI registry.

**Comment by ming-ddtechcg** [comment]
@MinerYang , thanks for the confirmation. 

Can I say that Harbor is no longer to support the Helm repository add feature?  Just would like to confirm it.

Thanks.

**Comment by MinerYang** [comment]
Yes, closed by https://github.com/goharbor/harbor/issues/18720#issuecomment-1691038418
