### ISSUE TITLE
Setting Duration to Zero Results in Unexpected 30-Day Expiry

### ISSUE THREAD

**Issue by goutham1012** [goharbor/harbor#19794]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Set Duration to 0 for Robot Account Creation, Expected No Expiry, However UI Displays 30 Days. See Attached Snapshots for Review.

**Steps to reproduce the problem:**
Attached the snapshot
![create-robot-account](https://github.com/goharbor/harbor/assets/155647831/7c339a90-0001-4590-93b4-47e183a1fbfa)
![response-body](https://github.com/goharbor/harbor/assets/155647831/e2679dd7-7d59-499c-bdee-416ebdf7dbaa)

**Versions:**
Please specify the versions of following systems.

- harbor version:v2.9.1-5cbb1b01
- docker engine version:  4.4.1

**Comment by MinerYang** [comment]
For never been expired, please set as  -1

**Comment by goutham1012** [comment]
@MinerYang -- Thank you for your assistance. Could you kindly share any documentation that explains where these values are represented?
