### ISSUE TITLE
The system requires the cron expression to contain six fields when creating a Garbage Collection (GC) schedule.

### ISSUE THREAD

**Issue by goutham1012** [goharbor/harbor#19798]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
While attempting to create a Garbage Collection schedule in Harbor, I provided a cron expression containing five fields. However, the system requires a cron expression with six fields. Please assist by providing the appropriate cron expression format that accommodates six fields for Harbor's scheduling system.

Regarding the parameters section, what specific details or configurations are permissible or recommended to be updated within the "additionalProp1," "additionalProp2," and "additionalProp3" fields?

I've noticed that the Garbage Collection (GC) gets created successfully only when I provide the "next_scheduled_time" value as "YYYY-MM-DDTHH:MM:SS.sssZ".

Could you please provide the Harbor documentation section that covers this topic?

**Steps to reproduce the problem:**
{
  "schedule": {
    "type": "Hourly",
    "cron": "53 5 * * *"
  },
  "parameters": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  }
}

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.9.1-5cbb1b01
- docker engine version: 4.4.1
![Create-GC](https://github.com/goharbor/harbor/assets/155647831/c2b64b32-1102-47c4-bb6b-54ebbe957f5d)
![response-body1](https://github.com/goharbor/harbor/assets/155647831/8159a34a-02a7-4c54-8034-0d9b28028121)

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MinerYang** [comment]
The first fields for GC cron  schedule is `Seconds` and need set to be `0`. e.g. `0 53 5 * * *`. BTW, the type would be `Custom` if you specify your own cron

**Comment by goutham1012** [comment]
@MinerYang  -- I appreciate your help with the previous query. Can you also assist me with the remaining questions or concerns I have?

**Comment by MinerYang** [comment]
For Q2:
you could use as below to set `delete_untagged`
```
"parameters": {
    "delete_untagged" : true
  }
```
