### ISSUE TITLE
Harbor error: Mirror metadata lost

### ISSUE THREAD

**Issue by CCTV-six** [goharbor/harbor#19793]
**ExpectedBehavior:**
Diagnose whether the root cause of the problem is a network issue, configuration error, or other reasons

**CurrentBehavior**
Error: Failed to retrieve image metadata from registry: Get [http://localhost:5000/xxx/yyy: net/http: TLS handshake timeout]

**Comment by MinerYang** [comment]
The registry service must be accessible to external clients, so do not specify localhost, 127.0.0.1, or 0.0.0.0 as the hostname.
