### ISSUE TITLE
【Urgent】Does Harbor not support pushing images like "xxx.com/my_project:my_tag"?

### ISSUE THREAD

**Issue by jerryqzhang** [goharbor/harbor#19814]
Does Harbor not support pushing images like "xxx.com/my_project:my_tag"?

```
docker push xxx.com/my_project:my_tag
```

This mechanism will hinder the migration of images from Nexus to Harbor.
If you push a image like the sample, you will receive a bug phenomenon like this:
![image](https://github.com/goharbor/harbor/assets/30404657/e03da2fa-83f8-4564-a3d1-2a45ad47fd08)

**Comment by stonezdj** [comment]
Harbor always require a project name, it should be <hostname>/<projectname>/<repository>:<tag>
