### ISSUE TITLE
Failed to push a singularity image to the harbor registry

### ISSUE THREAD

**Issue by JackLehman** [goharbor/harbor#19827]
Steps to reproduce:
`$ singularity pull docker://alpine`

`$ ls ~/.singularity/cache`
alpine_latest.sif library  net  oci  oci-tmp  oras  shub

`$ export SINGULARITY_DOCKER_USERNAME=XXXX`
`$ export SINGULARITY_DOCKER_PASSWORD=XXXX`

`$ singularity push alpine_latest.sif oras://xxx.xxx.com/public/alpine_latest.sif`

**INFO:    No tag or digest found, using default: latest
FATAL:   Unable to push image to oci registry: unable to push: failed commit on ref "manifest-sha256:2ff94df6b4632da7653370b68fb59ce7af6f3ec8acbeaa8499b751c32be3e580": unexpected status: 500 Internal Server Error**

Harbor version: `Harbor v2.10`
`singularity version 3.5.2+ds1`
Installation: Standard Docker Compose Installation with the given default configuration

**Comment by MinerYang** [comment]
What kind of storage your are using ? S3 or filesystem?
Could you provide your related registry log?
