### ISSUE TITLE
How can I install Trivy after the installation of Harbor?

### ISSUE THREAD

**Issue by intrapus** [goharbor/harbor#19820]
How can I install Trivy after the installation of Harbor?

**Comment by MinerYang** [comment]
If you wish to use your own scanner service, ref to this https://goharbor.io/docs/main/administration/vulnerability-scanning/pluggable-scanners/
Otherwise, for offline installer, running install as 'sudo ./install --with-trivy'

**Comment by intrapus** [comment]
The article is missing information on how to install Trivy as a service.
Currently, I installed Harbor without Trivy. Will the above command reinstall Harbor or install Trivy only?

**Comment by Suppi123** [comment]
you can simply run the installation script again with the flag --with-trivy. This should not change anything in your current harbor and install the trivy component to it
