### ISSUE TITLE
Link on Config Harbor YML file page

### ISSUE THREAD

**Issue by DaanSelen** [goharbor/harbor#19830]
Hello Harbor Team,

Quick tip, the link on the page: https://goharbor.io/docs/2.3.0/install-config/configure-yml-file/ at the bottom with the text: "[Registry Configuration Reference](https://docs.docker.com/registry/configuration/#storage)"

Does no longer work, I receive an Error 404 on the docker page. So maybe update this link in the documentation?

Kind regards.

**Comment by MinerYang** [comment]
Thanks @DaanSelen  for reporting this issue and we will update ASAP

**Comment by YangJiao0817** [comment]
Those PRs have merged.
https://github.com/goharbor/website/pull/535
https://github.com/goharbor/website/pull/534
https://github.com/goharbor/website/pull/533
