### ISSUE TITLE
Scheduled replication suddenly stops working

### ISSUE THREAD

**Issue by dan-m8t** [goharbor/harbor#19831]
**Expected behavior and actual behavior:**
Expected behavior is a working scheduled replication. Actual behavior: I got somewhat like 40 replication rules, all of these replicates from another Harbor. Recently we migrated our configuration to the harbor terraform provider, since then some of the replication rules just stopped working:

![grafik](https://github.com/goharbor/harbor/assets/48068660/4c2f29d9-1831-405c-ac12-c07e5990f33a)
![grafik](https://github.com/goharbor/harbor/assets/48068660/5efe1603-bdde-4391-91a0-f2f099130f79)

Only workarounds I know are either disabling/enabling the rule - this doesn't work for all rules or delete and re-add the rule.
I cannot see any useful logs in jobservice.log because the schedule is not running, though no log entries are written as far as I can see.

As my workaround doesn't work I saw after I disabled and re-enabled a replication rule the `update_time` field in  the replication_policy does not get updated:

```
 id |  name   | dest_registry_id | enabled | description | deleted |                              trigger                              |                                                 filters                                                  | replic
ate_deletion | start_time |       creation_time        |        update_time         | creator | src_registry_id | dest_namespace | override | dest_namespace_replace_count | speed_kb | copy_by_chunk
----+---------+------------------+---------+-------------+---------+-------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+-------
-------------+------------+----------------------------+----------------------------+---------+-----------------+----------------+----------+------------------------------+----------+---------------
 57 | MY-PROJECT |                0 | t       |             | f       | {"type":"scheduled","trigger_settings":{"cron":"0 */15 * * * *"}} | [{"type":"name","value":"MY-PROJECT/**"},{"type":"tag","value":"{latest,*debug*}","decoration":"excludes"}] | f
             |            | 2022-09-23 12:08:17.111835 | 2023-12-20 09:18:17.935006 |         |               2 |                | t        |     
```

The `update_time` field is from our migration to terraform, we imported all the replication rules to our state but I do not think this has something to do with terraform in particular.

**Steps to reproduce the problem:**
None

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.9.0
- docker engine version: 24.0.6
- docker-compose version: 1.18.0

**Additional context:**

**Comment by dan-m8t** [comment]
Not sure why but the replication rule from the example above does work again. The `update_time` field is still untouched and it just started scheduling without any intervention. Is there any hint where to look?

**Comment by MinerYang** [comment]
Could you sharing the specific replication rules(full screen shot would be preferred) and each audit log of failed replication task via UI?

**Comment by dan-m8t** [comment]
Of course but I do not think this will give any hint though.
![replicationrule](https://github.com/goharbor/harbor/assets/48068660/b76d6314-10bf-4fbd-934a-cdf581c40f50)

Not sure what you mean with audit log, I guess the "Executions" section on the replications rules site? As I said, there was no replication between 20th of December and my manual intervention last week (see screenshot above), so no entries here.

**Comment by dan-m8t** [comment]
The problem still persists but I got the non-running (but scheduled) replications running again with a restart of all the containers (docker-compose setup). Not sure which component is needed to restart but I'd guess harbor-jobservice or harbor-core container - Next time I will try to only restart the jobservice container and see if this helps to get it to work again. It is weird because this only affects randomly chosen replication jobs and not all the jobs.
