### ISSUE TITLE
Add Korean tlansration

### ISSUE THREAD

**Issue by yj-yoo** [goharbor/harbor#19842]
I would like to translate the following item into Korean.
* README
* i18n/lang/

**Comment by wy65701436** [comment]
@OrlinVasilev Could we find someone within the community who is familiar with Korean to assist us?

**Comment by yj-yoo** [comment]
@wy65701436 @OrlinVasilev 
Actually, that's my concern. Korean developers are interested in Harbor, so I am trying to translate it, but I think it will be difficult to get help within the community.

**Comment by wy65701436** [comment]
@yj-yoo I think you can go ahead to open pull request for this, and we'll explore if there's anyone within the community who can offer assistance. 

At the moment, the maintainers are primarily knowledgeable in Chinese, English, and Spanish.
