### ISSUE TITLE
When pulling image from harbor-registry through harbor-proxy, pulled count and pulled time do not change

### ISSUE THREAD

**Issue by kbabuadze-pd** [goharbor/harbor#19854]
**Expected behavior and actual behavior:**
When pulling image from harbor-registry via harbor-proxy image pull count and pull time does not get update. Although everything works as expected when directly pulling from harbor-registry project. 

This causes two problems: 
1. We don't have pull stats for the registry
2. Since pull time is not updated we can not apply retention policy by pull time. 

**Steps to reproduce the problem:**
Setup harbor registry and harbor proxy (which pull from the registry) 

Try to pull image from harbor registry you will see that Pulls counter increases and pull time changes 
<img width="1573" alt="image" src="https://github.com/goharbor/harbor/assets/104766110/b89d8907-e77e-4cb4-b817-d268f7d98609">

If you try to do the same through proxy this doesn't happen.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.9.0]
- docker engine version: [24.0.5]

**Comment by ChristianCiach** [comment]
I wonder if this is working as intended. A proxy-cache is a cache, right? So I would expect that hitting the cache does *not* increase the pulls of the underlying repo. Or maybe there is a misunderstanding.

**Comment by kbabuadze-pd** [comment]
I wonder if at list pull time can be somehow updated. When you are using proxy-cache in front of harbor-registry you never see pull time updated for the image, therefore you can not apply pull based retention policy.
