### ISSUE TITLE
Appending Changes in Robot Account Settings During PUT Operation

### ISSUE THREAD

**Issue by goutham1012** [goharbor/harbor#19858]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Hi Team,

I'm trying to create a Robot account with "repository" as the resource and "push" and "pull" as the actions. Afterward, I want to update the Robot account, adding "artifact" as the resource and "list" and "read" as the actions. Currently, it seems that both the resource and actions are being overwritten. Is there a way to append these changes during the PUT operation?

Create Robot Account:
{
  "name": "test2",
  "description": "string",
  "level": "system",
  "disable": false,
  "duration": 0,
  "permissions": [
    {
      "kind": "project",
      "namespace": "cal-operator-index",
      "access": [
        {
          "resource": "repository",
          "action": "pull"
        },
        {
          "resource": "repository",
          "action": "push"
        }
      ]
    }
  ]
}

Update Robot Account:
{
  "id": 38,
  "name": "robot$test2",
  "description": "string",
  "level": "system",
  "duration": 0,
  "editable": true,
  "disable": false,
  "expires_at": 0,
  "permissions": [
    {
      "kind": "project",
      "namespace": "cal-operator-index",
      "access": [
        {
          "resource": "artifact",
          "action": "read"
        },
        {
          "resource": "artifact",
          "action": "list"
        }
      ]
    }
  ],
  "creation_time": "2024-01-18T10:50:01.511Z",
  "update_time": "2024-01-18T10:50:01.511Z"
}

**Versions:**
Please specify the versions of following systems.

harbor version:v2.9.1-5cbb1b01
docker engine version: 4.4.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
Hi, the feature has been implemented in version v2.10. Please give it a try, and if the issue persists, feel free to reopen it.
