### ISSUE TITLE
huawei swr replicate images in pull mode can not Source resource filter

### ISSUE THREAD

**Issue by xudingjun3131** [goharbor/harbor#19856]
huawei swr replicate images in pull mode can not Source resource filter

i had config some filter 
but it cannot work, it always pull all images.
![image](https://github.com/goharbor/harbor/assets/16241230/f037b072-87fb-4e31-8853-26a8a82f934a)
![image](https://github.com/goharbor/harbor/assets/16241230/9d284d5a-84ba-425f-9aae-b9e6dea88fa1)

**Comment by wy65701436** [comment]
do you add the swr as a kind of v2 registry? Since harbor doesn't support swr registry, do you have a env to us for debugging?

**Comment by xudingjun3131** [comment]
@wy65701436 
I don't have an environment to provide。
how do i confim  the huawei swr as a kind of v2 registry?

**Comment by xudingjun3131** [comment]
看上去在2.0.2版本有修改过这个问题。
![image](https://github.com/goharbor/harbor/assets/16241230/3d3306f3-ea3f-4755-9b98-fb29052002f4)

![image](https://github.com/goharbor/harbor/assets/16241230/2bf5a8c1-7575-4bb9-837a-5984c4944213)
