### ISSUE TITLE
IPv6 connection to Harbor Web GUI not working properly

### ISSUE THREAD

**Issue by REHICode** [goharbor/harbor#19865]
**Expected behavior and actual behavior:**
If you try to connect to harbor web gui from a ipv6 only machine, it will not work.
```
user@v6host:~$ curl -vk https://ebnhbr01
*   Trying aaaa:aaaa:10a:c884:ac20:22ff:aaaa:aaaa:443...
* TCP_NODELAY set
* connect to aaaa:aaaa:10a:c884:ac20:22ff:aaaa:aaaa port 443 failed: Connection refused
*   Trying 100.200.123.123:443...
* TCP_NODELAY set
* Connected to ebnhbr01 (100.200.123.123) port 443 (#0)
```

**Solution to the problem:**
The nginx container only listens on v4 port 8443. Make it listen to v6 (see workaround)

**My current workaround:**
```
root@ebnhbr01:~# docker exec -u 0 nginx /bin/sh -c "chown nginx /etc/nginx/"
root@ebnhbr01:~# docker exec -u nginx nginx /bin/sh -c "sed -i 's/listen 8443 ssl;/listen 8443 ssl;\n    listen [::]:8443 ssl;/' /etc/nginx/nginx.conf"
```
and restart harbor

**Versions:**
- OS: Ubuntu 22.04 LTS
- harbor version: [2.9.1] - offline installer in airgapped environment
- docker engine version: [5:24.0.7-1~ubuntu.22.04~jammy]
- docker-compose version: [1.29.2-1]

**Comment by chrisongthb** [comment]
+1

**Comment by MinerYang** [comment]
Hi @REHICode ,

Appreciate for the report, will fix by https://github.com/goharbor/harbor/pull/19868

**Comment by REHICode** [comment]
Perfect,

thx for your quick reply and your work.

**Comment by MinerYang** [comment]
Hi @REHICode ,

Having a following question here, how do you set up your docker network when enabling ipv6? Could you share the output of harbor network and the docker-compose file?
```
docker network inspect harbor_harbor
```
