### ISSUE TITLE
Redis password change issue

### ISSUE THREAD

**Issue by 0xj0el** [goharbor/harbor#19866]
This is not a bug or issue.But the problem is our  user have redis password change facility
So once the redis password is changed , harbor which is already configured with old password starts to go down. Is there a way we can handle this.

**Comment by MinerYang** [comment]
you probably need to have a script do change the password in harbor.yml or values.yaml then restart/update harbor instance automatically. 
If your are using external Redis, Harbor only read the password  from what you set.
