### ISSUE TITLE
Dokcer image push fail Retrying 

### ISSUE THREAD

**Issue by cwangg897** [goharbor/harbor#19863]
I was able to push the docker image to the harbor successfully before, but when I changed the code and pushed it again, it didn't go up. 
It just retries like the picture below 
One thing I would like to debug is where can I look at the log files to find the cause?

![image](https://github.com/goharbor/harbor/assets/79621675/96ef9915-ff84-4718-9a13-4abe0cf5837c)

**Comment by Kajot-dev** [comment]
Harbor is self-hosted, so you can look into the logs on the server/k8s that the harbor is running on (it depends on how it is deployed). You should contact administrators of your harbor instance

**Comment by cwangg897** [comment]
@Kajot-dev  I downloaded it to docker and am running it on an instance.  
Please Help me

**Comment by Kajot-dev** [comment]
You are running it as a docker-compose I suppose? You can attach to a running container with docker attach (see https://docs.docker.com/engine/reference/commandline/attach/)

**Comment by cwangg897** [comment]
> You are running it as a docker-compose I suppose? You can attach to a running container with docker attach (see https://docs.docker.com/engine/reference/commandline/attach/)

Okay I'll try it

**Comment by chlins** [comment]
Please check the harbor core and registry logs.

**Comment by wy65701436** [comment]
what version is using?
