### ISSUE TITLE
Run garbage collection but this didn't clean porject and registry from /data folder

### ISSUE THREAD

**Issue by mgcsc** [goharbor/harbor#19860]
Hi,

I am running Harbor 2.10.0 on VM and using /data folder to store container data.  I run load test which is created 100 peojects and images. I deleted all the project from UI and ran garbage collection. 
Logs shows blob deleted but project and repository still exist in /data/registry/docker/registry/v2/repositories/ folder.

Is there any solution if deleting project from UI , that should be deleted from storage also.

Thanks
Manoj

**Comment by wy65701436** [comment]
`To avoid damaging the uploading artifact, the garbage collection introduces a time windows(2 hours) to reserve the recent uploaded layers. Garbage collection does not sweep the manifest & blob files that have a timestamp in the time window. Harbor runs garbage collection without interrupting your ability to continue use Harbor, for example you are able to push, pull, or delete artifacts while garbage collection is running.`

Reference: https://goharbor.io/docs/2.10.0/administration/garbage-collection/#run-garbage-collection
