### ISSUE TITLE
Harbor does not adhere to the OCI distribution spec when returning descriptors of manifest referrers

### ISSUE THREAD

**Issue by nathan-joslin** [goharbor/harbor#19867]
## Summary

When filtering referrers of a manifest by `artifactType` Harbor does not adhere to the oci distribution specification.

### OCI Distribution Specification

The OCI distribution spec states the following under [listing-referrers](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) 
> Upon success, the response MUST be a JSON body with an image index containing a list of descriptors. The Content-Type header MUST be set to application/vnd.oci.image.index.v1+json. Each descriptor is of an image manifest or index in the same <name> namespace with a subject field that specifies the value of <digest>. The descriptors MUST include an artifactType field that is set to the value of the artifactType in the image manifest or index, if present. If the artifactType is empty or missing in the image manifest, the value of artifactType MUST be set to the config descriptor mediaType value.

### Harbor's Implementation

Currently, Harbor directly gets the `mediaType` from the manifest config regardless whether or not an `artifactType` exists in the manifest. According to the OCI distribution spec, this behavior should be the fallback should the manifest not include an `artifactType`. This can be found in [harbor/src/server/registry/referrers.go](https://github.com/goharbor/harbor/blob/main/src/server/registry/referrers.go#L106) :
```go
		// filter by the artifactType since the artifactType is actually the config media type of the artifact.
		if at != "" {
			if accArt.MediaType == at {
				mfs = append(mfs, mf)
			}
		} else {
			mfs = append(mfs, mf)
		}
	}
```

### Example 

The following examples utilize `oras discover` which discovers referrers of a manifest and displays each manifest's `artifactType`. The referring manifest used to demonstrate this behavior has an empty config and includes an `artifactType` in the manifest. As such, it is expected to return the `artifactType` in the manifest and not the `mediaType` in the config.

Redacted information has been replaced with informative generics.

### Unexpected Behavior Seen on Harbor Registry

```console
$ oras discover HARBOR_TAG_REFERENCE
Discovered 1 artifact referencing TAGGED_MANIFEST
Digest: sha256:339523ba39b2f9a98847190fb642be7a526de1916624bbec3bcfd3158d095d2d

Artifact Type                       Digest
application/vnd.oci.empty.v1+json   sha256:bf9c8c5e1c50a90a0cbd33d4801f9e000914bb88c67828e270819f59992efdba
```

### Expected Behavior Seen on Zot Registry

```console
$ oras discover ZOT_TAG_REFERENCE
Discovered 1 artifact referencing TAGGED_MANIFEST
Digest: sha256:ca9fa55cda02fd7e43f030ff09a9355d28984d7dd836128661c4e9be7b91a828

Artifact Type                                   Digest
EXPECTED_ARTIFACT_TYPE   sha256:5f3bfdeb2e16e576ed77f8324b6a93aec3dc5be24c79f717ff272675148aa5d4
```

**Comment by MinerYang** [comment]
Hi @nathan-joslin ,

Thanks for contact with us, we are aware of this issue, will update until oci-spec 1.1 GA
https://github.com/goharbor/harbor/issues/19261
