### ISSUE TITLE
When trying to update the password in the Change Password form, the frontend does not accept spaces

### ISSUE THREAD

**Issue by oEscal** [goharbor/harbor#19885]
**Expected behavior and actual behavior:**
When trying to update the current user password, I tried typing a new password with spaces between characters, the frontend blocked me, with the default error for password size and password constraints (see image below). On the other hand, I tried to update the password in the same way, but by manually doing the POST request, and the backend accepted it.
![image](https://github.com/goharbor/harbor/assets/40316784/e97ef195-91e0-4059-9c2e-516a120a051b)

Although this is not a serious problem, it should be fixed inclusively because, according to the [NIST SP 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html), any printable ASCII character, including spaces, should be accepted in passwords.

**Versions:**

- harbor version: 2.4.1

**Comment by MinerYang** [comment]
Hi @oEscal , 
Thanks for reporting. In latest version 2.10, we have same behavior for front end and  the backend.
```
{
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "the password or secret must be 8-128, inclusively, characters long with at least 1 uppercase letter, 1 lowercase letter and 1 number"
    }
  ]
}
```
We will take this [NIST SP 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html) into consideration,
And btw, v2.4 is out of maintenance, please update to recent versions if it's possible
