### ISSUE TITLE
Monitor for stuck scans

### ISSUE THREAD

**Issue by AndreasPelzer** [goharbor/harbor#19884]
**Is your feature request related to a problem? Please describe.**
A recent security scan got stuck. The image could no longer be pulled until the scan was aborted.
Error response from daemon: unknown: current image with "Running" status of vulnerability scanning cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "Critical" or higher from running.' To continue with pull, please contact your project administrator for help.

**Describe the solution you'd like**
Provide the possibility to monitor scanning actions, so that too long running scans can be identified and alerted.
Extend the api by e.g. "get current scans" including project, repository, artifact, scanning status, duration of scan.

The duration of the scan can then give a hint to stuck scan.

**Comment by chlins** [comment]
Duplicate with https://github.com/goharbor/harbor/issues/19486.

**Comment by wy65701436** [comment]
close as dup.
