### ISSUE TITLE
[EPIC] Adopt Harbor with distribution/distribution v3

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#19882]
Monitoring upstream [distribution/distribution - v3.0.0-alpha.1](https://github.com/distribution/distribution/tree/v3.0.0-alpha.1) updates and deprecation, adopt Harbor with it and running regression tests.
Will have test against branch [distribution_v3_test](https://github.com/goharbor/harbor/tree/distribution_v3_test)

blocked by upstream distribution
 - https://github.com/goharbor/harbor/issues/16490
 - https://github.com/goharbor/harbor/issues/13223

**Comment by a-sudarsanan** [comment]
@wy65701436 , Is there any planned timeline for the 2.11 release? We are eagerrly waiting for the s3 assume role support in the harbor.

**Comment by stonezdj** [comment]
Because the distribution v3 might be released later than Harbor v2.11.0, remove it from v2.11.0
