### ISSUE TITLE
Deleting artifacts, but the storage capacity is not decreasing.

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor#19892]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I manage images by connecting an S3 bucket to harbor.
And recently, in order to use the s3 bucket efficiently, I am periodically cleaning up image artifacts by calling the delete artifact API through an automated script.
However, my s3 bucket usage does not decrease at all. What is wrong?

**Steps to reproduce the problem:**
Many artifacts are being cleaned up periodically through the delete artifact API, but the s3 bucket usage is not decreasing at all.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.9.1
- kubernetese version: 1.28

Please let me know if you need any additional information

**Comment by chlins** [comment]
The artifact deletion API only removes linkages and data from the database, you should execute the garbage collection to free the storage space after deleting artifacts.

**Comment by derekcha** [comment]
@chlins I see! Thanks for the reply
