### ISSUE TITLE
Creating label id zero is ignored in API calls

### ISSUE THREAD

**Issue by alireza-mht** [goharbor/harbor#19907]
**Expected behavior and actual behavior:**
Actual: Using id equal to zero we can create lots of labels with different name without having any error (returned 201). But when listing the labels, the id is not zero anymore.

Expected: getting error that the id zero is not available instead of creating the label with different random id.

**Steps to reproduce the problem:**
Request below returns 201
```
curl -X 'POST' \
  'https://demo.goharbor.io/api/v2.0/labels' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Harbor-CSRF-Token: ' \
  -d '{
  "id": 0,
  "name": "test",
  "description": "test",
  "color": "#000000",
  "scope": "p",
  "project_id": 31,
  "creation_time": "2024-01-24T21:26:36.297Z",
  "update_time": "2024-01-24T21:26:36.297Z"
}'
```
When listing the label using the below call:
``` 
curl -X 'GET' \
  'https://demo.goharbor.io/api/v2.0/labels?page=1&page_size=10&scope=p&project_id=31' \
  -H 'accept: application/json'
```

returned:
``` 
[
  {
    "color": "#000000",
    "creation_time": "2024-01-24T21:26:36.297Z",
    "description": "test",
    "id": 15,
    "name": "test",
    "project_id": 31,
    "scope": "p",
    "update_time": "2024-01-24T21:26:36.297Z"
  }
]
 ```

While the id defined in the request was zero.

**Versions:**
Tested on https://demo.goharbor.io/

- harbor version: [v2.0]
- harbor api: [v2.0]

**Comment by MinerYang** [comment]
Hi @alireza-mht ,

'label.id' is not a necessary user input param when create the a label, it is an auto-increment  field for db.

You could just ignore it when you send the POST request.

**Comment by alireza-mht** [comment]
@MinerYang Thanks for the response. If I create a label without any id and want to add it to some artifacts, how can I get access to the id of created label? Plus most of the label API calls (Delete, Get, and Put) is according to the id and not getting that when creating it seems not a good idea.  Would that make sense to return the actual new created id of the label when there is a POST call? 
Thanks for your help!
