### ISSUE TITLE
Is there a limit for the length of docker tags?

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#19917]
### Discussed in https://github.com/goharbor/harbor/discussions/19908

<div type='discussions-op-text'>

<sup>Originally posted by **jorisjumanne** January 25, 2024</sup>
I seem to have found a limit for the length of tags of docker images to be shown in Harbor. A very long tag name of around 70 characters doesn't show up in the harbor UI, where a tag length of 15 characters does. 

Does a limit apply and, if so, what is this limit? I can then take it into account while settings tags for my images and no longer have tagless images in Harbor.</div>

**Comment by MinerYang** [comment]
<img width="1138" alt="Screenshot 2024-01-29 at 17 36 05" src="https://github.com/goharbor/harbor/assets/44956229/b217bfbc-7c64-4f18-b753-5f653d7703ee">
https://github.com/goharbor/harbor/blob/522f96b5cf1c56ec5a4a1a1fabe97255e8d5841e/src/controller/tag/controller.go#L38
Actually it is limited with 128 characters.

**Comment by wy65701436** [comment]
Just tried with demo.goharbor.io, no issue was found.
![image](https://github.com/goharbor/harbor/assets/2841473/9cb5129e-3485-4b17-89bc-046cc0275a27)

**Comment by MinerYang** [comment]
Will close this for now. Feel free to reopen if there's still's any concerns
