### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/input/harbor.yml'

### ISSUE THREAD

**Issue by davidgyongyosi** [goharbor/harbor#19919]
The error I get when I try to run install.sh:

prepare base dir is set to /c/Users/myadmin/Downloads/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/commands/prepare.py", line 33, in prepare
    config_dict = parse_yaml_config(conf, with_trivy=with_trivy)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/utils/configs.py", line 106, in parse_yaml_config
    with open(config_file_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/input/harbor.yml'

Why does it not seem to find input/harbor.yml. I can see in the file explorer that it is surely creating and copying it.

Can anyone help with this issue?

**Comment by zyyw** [comment]
Hi @davidgyongyosi which Harbor version were you trying to install? And btw, what is the os and arch of the env where you were trying to install the Harbor service?

According to your description of this issue, it says "prepare base dir is set to **/c/Users/myadmin/Downloads/harbor**", while it also reports "FileNotFoundError: [Errno 2] No such file or directory: '**/input/harbor.yml**'".
* **/c/Users/myadmin/Downloads/harbor** and **/input/harbor.yml** looks like odd folders path to me.

The `harbor-offline-installer` should be able to work fine on ubuntu amd64 platform?

**Comment by davidgyongyosi** [comment]
The host OS is windows, and yes I have read it in the docs that it is not supported, I am just experimenting with it, but the main issue is that the install.sh script creates the folder and places the harbor.yml file in it. It is strange for me that it says that there is no such file or directory

**Comment by amundead** [comment]
same with me.
Ubuntu 22 LTS

`FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/harbor/harbor.yml'`
