### ISSUE TITLE
INSTALLATION FAILED: template: harbor/templates/registry/registry-secret.yaml error during installation on k8s 

### ISSUE THREAD

**Issue by tamilselvan-lws** [goharbor/harbor#19916]
Error: INSTALLATION FAILED: template: harbor/templates/registry/registry-secret.yaml:11:62: executing "harbor/templates/registry/registry-secret.yaml" at <include "harbor.secretKeyHelper" (dict "key" "REGISTRY_HTTP_SECRET" "data" $existingSecret.data)>: error calling include: template: harbor/templates/_helpers.tpl:44:41: executing "harbor.secretKeyHelper" at <.data>: wrong type for value; expected map[string]interface {}; got interface {}

**Comment by tamilselvan-lws** [comment]
![Screenshot from 2024-01-27 15-35-41](https://github.com/goharbor/harbor/assets/139841363/deb09366-c57d-434e-954f-05fdd45cfba4)

**Comment by zyyw** [comment]
Please check this PR:
* https://github.com/goharbor/harbor-helm/issues/1671

And the release note of:
* https://github.com/goharbor/harbor-helm/releases/tag/v1.14.0

Essentially, please use `helm` version >= 3.10.0, when deploying harbor-helm v1.14.0 and onwards.
