### ISSUE TITLE
Why is there such a big gap between pull artifacts from the same project and different projects

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#19918]
### Discussed in https://github.com/goharbor/harbor/discussions/19903

<div type='discussions-op-text'>

<sup>Originally posted by **microyahoo** January 24, 2024</sup>
Why is there such a big gap between pull artifacts from the same project and different projects? Just due to db lock?

```console
~/go/src/github.com/goharbor/perf (main ✗) cat outputs.500/pull-artifacts-from-same-project.summary.json| jq      
{
  "timestamp": 1706025980701,
  "description": "pull-artifacts-from-same-project",
  "avg": "110.8s",
  "min": "1.24s",
  "med": "104.15s",
  "max": "260.32s",
  "p90": "208.89s",
  "p95": "233.16s",
  "successRate": "100%",
  "iterationsRate": "3.79/s"
}
~/go/src/github.com/goharbor/perf (main ✗) cat outputs.500/pull-artifacts-from-different-projects.summary.json| jq
{
  "timestamp": 1706025715365,
  "description": "pull-artifacts-from-different-projects",
  "avg": "7.19s",
  "min": "1.04s",
  "med": "6.12s",
  "max": "18.96s",
  "p90": "14.34s",
  "p95": "15.34s",
  "successRate": "100%",
  "iterationsRate": "3.58/s"
}
```</div>

**Comment by microyahoo** [comment]
Thanks for your quick response, I am not sure whether this issue has related with https://github.com/goharbor/harbor/issues/19902.
harbor version: `v2.10.0`

1. apply the env variables
```
export HARBOR_ROOT=/mnt/cephfs
export HARBOR_REPORT=true
export HARBOR_VUS=500
export HARBOR_URL=https://user:password@url
```
2. then run the `go run mage.go run pull-artifacts-from-different-projects` and `go run mage.go run pull-artifacts-from-same-project`
[pull-artifacts-from-different-projects](https://github.com/goharbor/perf/blob/main/scripts/test/pull-artifacts-from-different-projects.js)
[pull-artifacts-from-same-project](https://github.com/goharbor/perf/blob/main/scripts/test/pull-artifacts-from-same-project.js)

**Comment by justinharringa** [comment]
Yikes... an alternative would be to `INSERT` to a new `artifact_pull_time` table and just keep that clean over time.

**Comment by justinharringa** [comment]
Aha there is an `artifactPullAsyncFlushDuration` in the Helm chart that sets `ARTIFACT_PULL_ASYNC_FLUSH_DURATION`. The variable that's resolved defaults to 10 seconds if it's not set (https://github.com/goharbor/harbor/blob/v2.11.0/src/controller/event/handler/internal/artifact.go#L57C28-L57C62). We'll investigate using this.
