### ISSUE TITLE
Banner warning massage:Certain jobs have been pending for execution for over 24 hours.

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#19923]
### Discussed in https://github.com/goharbor/harbor/discussions/19905

<div type='discussions-op-text'>

<sup>Originally posted by **viceice** January 24, 2024</sup>
I'm seeing the message `Certain jobs have been pending for execution for over 24 hours. Please check the job service dashboard.
For more details, please refer to the Wiki.` on my limited account.
When i login with an admin account i don't see that message and also no pending jobs.

How can i find the pending jobs?</div>

I'm using v2.10.0-6abb4ea and there is no pending job when logging in as administrator. the normal user get's the message but going to the dashboard isn't allowed.

**Comment by MinerYang** [comment]
<img width="1295" alt="Screenshot 2024-01-30 at 13 05 13" src="https://github.com/goharbor/harbor/assets/44956229/44dc37dc-a402-4c7e-9522-1a54e1cfcf93">

**Comment by HammerNL89** [comment]
We observe the same issue. When a normal user visits the Harbor UI, there is no yellow banner, but if you leave a harbor browser tab open for a while, the yellow banner (pending jobs) will show after 'a while' . 
If you then login as a admin, and look at the job service dashboard, there are no pending jobs visible. We haven't been able the track down the issue. 

![image](https://github.com/goharbor/harbor/assets/6350295/c18fe38e-5897-4bc4-bbe0-66f09116ea2b)

This is on Harbor version `v2.9.1-5cbb1b01` 
If you need more information, please let me know

**Comment by nmcostello** [comment]
We are also seeing this in Version v2.9.0-6d1ad65c. It doesn't seem to affect anything.

**Comment by xl204431** [comment]
+1

**Comment by ivoistaken** [comment]
Issue still present in 2.11.0

**Comment by ivoistaken** [comment]
The issue happens only for non-admins, it might be connected with the following:
GET /api/v2.0/jobservice/queues
200 + json for admins
403 for non-admins - may be this triggers the yellow warning?

**Comment by luidoc** [comment]
+1 version 2.10.2

**Comment by blankdots** [comment]
@MinerYang can this issue be re-opened?
