### ISSUE TITLE
Chart push to goHarbor v2.7.0 times out

### ISSUE THREAD

**Issue by suprita23** [goharbor/harbor#19922]
Hi, I am using goHarbor v2.7.0.
We see the chart push erroring out with timeout issue.. Is there a way to increase the timeouts?

I see this error message all over the chartmuseum pod's logs -
2024/01/29 22:40:07 [Recovery] 2024/01/29 - 22:40:07 panic recovered:
write tcp 10.0.0.228:9999->10.0.64.188:40654: i/o timeout
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:928 (0x1c1de71)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:1017 (0x26a2c04)
/go/src_code/pkg/chartmuseum/server/multitenant/handlers.go:105 (0x26a2b75)
/go/src_code/pkg/chartmuseum/router/router.go:249 (0x1c8dc1d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1c8a5d4)
/go/pkg/mod/github.com/zsais/go-gin-prometheus@v0.1.0/middleware.go:364 (0x1c8a5b5)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1c46309)
/go/pkg/mod/github.com/gin-contrib/size@v0.0.0-20220102055520-f75bacbc2df3/size.go:88 (0x1c462f1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1c8c0a5)
/go/src_code/pkg/chartmuseum/router/middleware.go:48 (0x1c8c082)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1c27221)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x1c2720c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1c2532c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:591 (0x1c25315)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:584 (0x1c25064)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x1c249f1)
/usr/local/go/src/net/http/server.go:2947 (0x11ffbcb)
/usr/local/go/src/net/http/server.go:1991 (0x11fa906)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0xf46ba0)

Chartmuseum connection to harbor-core is timing out.

**Comment by suprita23** [comment]
Can we look into the timeout issue..
We are getting context deadline exceeded error for every helm push of a chart

**Comment by wy65701436** [comment]
ChartMuseum has been deprecated since version 2.8, and as version 2.7 is no longer supported, please upgrade to the latest version. 

Instead of using ChartMuseum, we recommend leveraging OCI charts for your needs.
