### ISSUE TITLE
Harbor nginx container fail to start when install with docker-compose

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#19932]
The nginx container log：
```
nginx: [emerg] socket() [::]:8443 failed (97: Address family not supported by protocol)
```

After update the common/config/nginx

```
  server {
    listen 8443 ssl;
    listen [::]:8443 ssl;
#    server_name harbordomain.com;
    server_tokens off;
```
to remove the line `listen [::]:8443 ssl;`, then the nginx container can start.

Root cause: When IPv6 is disabled, the [::]:8443 will be considered a invalid address and failed to start nginx.

**Comment by MinerYang** [comment]
workaround
- step1 stop harbor containers
```
sudo docker compose down -v
```
- step2 edit the`/common/config/nginx/nginx.conf ` file, if internal_tls is enabled please also edit`/common/config/portal/nginx.conf ` as well
```
## remove this line 
listen [::]:8443 ssl; 

## save file
```

- step3 restart harbor
```
sudo docker compose up -d
```

**Comment by stonezdj** [comment]
All prs merged, close it
