### ISSUE TITLE
Harbor does not start all containers on boot

### ISSUE THREAD

**Issue by XANi** [goharbor/harbor#19933]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Worsks after server reboot

**Steps to reproduce the problem:**
Standard install, only changes were adding proxy, external database and redis

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.9.2
- docker engine version: 25.0.1
- docker-compose version: 1.29

**Additional context:**

`./install.sh --with-trivy` works fine and presents with a list of running containers:
```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                   PORTS                                                                                                                       NAMES
496c06e6ff77   goharbor/harbor-jobservice:v2.9.2      "/harbor/entrypoint.…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                                               harbor-jobservice
c86402dfa8ba   goharbor/harbor-exporter:v2.9.2        "/harbor/entrypoint.…"   3 minutes ago   Up 2 minutes                                                                                                                                         harbor-exporter
b34b7d6770dd   goharbor/nginx-photon:v2.9.2           "nginx -g 'daemon of…"   3 minutes ago   Up 2 minutes (healthy)   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   nginx
fe1f634209d6   goharbor/harbor-core:v2.9.2            "/harbor/entrypoint.…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                                               harbor-core
69896a6ff655   goharbor/harbor-portal:v2.9.2          "nginx -g 'daemon of…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                                               harbor-portal
5d87cd9b8a19   goharbor/registry-photon:v2.9.2        "/home/harbor/entryp…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                                               registry
0e8df1280517   goharbor/harbor-registryctl:v2.9.2     "/home/harbor/start.…"   3 minutes ago   Up 2 minutes (healthy)                                                                                                                               registryctl
73a2bf5de957   goharbor/trivy-adapter-photon:v2.9.2   "/home/scanner/entry…"   3 minutes ago   Up 3 minutes (healthy)                                                                                                                               trivy-adapter
803faffa7e6e   goharbor/harbor-log:v2.9.2             "/bin/sh -c /usr/loc…"   3 minutes ago   Up 3 minutes (healthy)   127.0.0.1:1514->10514/tcp                                                                                                   harbor-log
```

but after reboot:

```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                   PORTS                       NAMES
69896a6ff655   goharbor/harbor-portal:v2.9.2          "nginx -g 'daemon of…"   7 minutes ago   Up 4 minutes (healthy)                               harbor-portal
5d87cd9b8a19   goharbor/registry-photon:v2.9.2        "/home/harbor/entryp…"   7 minutes ago   Up 4 minutes (healthy)                               registry
73a2bf5de957   goharbor/trivy-adapter-photon:v2.9.2   "/home/scanner/entry…"   7 minutes ago   Up 4 minutes (healthy)                               trivy-adapter
803faffa7e6e   goharbor/harbor-log:v2.9.2             "/bin/sh -c /usr/loc…"   7 minutes ago   Up 4 minutes (healthy)   127.0.0.1:1514->10514/tcp   harbor-log
```
and it does not auto-start half of them

**Comment by MinerYang** [comment]
When you say reboot? do you mean restart docker service?

**Comment by XANi** [comment]
I mean VM reboot. It's a clean Debian 12 install

**Comment by zyyw** [comment]
@XANi please run `sudo docker-compose down` and then reboot the VM, and then `sudo docker-compose up -d` afterwards.

**Comment by XANi** [comment]
@zyyw It works, thanks. Is there a reason some containers are up after reboot and some are not ?

Seems a bit unintuitive, if it is not supposed to start on its own without docker compose it shouldn't run after reboot

**Comment by zyyw** [comment]
The reason why some contains are up while the others are not is still unknown to me :_)

**Comment by XANi** [comment]
@zyyw when I was testing it today I actually got them all up after first restart.. but the next one had only few of them up. Either way it should probably have some info in the docs for those not really familiar with docker composer

I think I will just do a systemd service that will run docker compose at system start and stop

**Comment by michellabbe** [comment]
We've had this issue for years and honestly I'm amazed this never got fixed yet.

Whenever the docker host is restarted (most of the time following `unattended-upgrades`) harbor repository is down until we restart some containers manually.  I never took time to dig into it much, but I suspect it's caused by dependencies.

When starting with a `docker compose up`, I think the containers are started in the order defined in the compose file, while during a reboot, the containers start order is most likely pretty random.

If some containers must be started in a specific order (e.g. database must be up before some other service start), it should be defined in the compose file (e.g. `depends_on`).

See [Control startup and shutdown order in Compose](https://docs.docker.com/compose/startup-order/)

**Comment by wy65701436** [comment]
Please refer to https://github.com/goharbor/harbor/issues/18704#issuecomment-1556764459

**Comment by dleske** [comment]
I submitted [a PR for this issue](https://github.com/goharbor/harbor/pull/19030) as I was experiencing the same but it was rejected.  I haven't come back to Harbor since last summer but plan to come back to it soon and looks like I'll have to keep applying [this patch](https://gist.github.com/dleske/7a42485d582149480b8fd46fe833848e).  If somebody on this thread tries it out and it doesn't work, let me know--I'll probably have to update it anyway so am happy to help out if I can.

**Comment by allexistence** [comment]
https://github.com/goharbor/harbor/blob/main/tools/systemd/harbor.service
