### ISSUE TITLE
Connecting harbor to postgres via pgpool. 

### ISSUE THREAD

**Issue by snoop2048** [goharbor/harbor#19942]
We have built harbor in a k8s cluster with external postgres, s3. 

However there appears to be no way to connect harbor to pgpool to use the HA of the postgres cluster. Can harbor only take a single IP for postgres connection? psql uses 2, so pgpool ensures the active DB is used. If we can only use a single IP must we manually repoint harbor if the DB switches its active node?

Ta

**Comment by MinerYang** [comment]
Hi @snoop2048 ,

Thanks for connecting with us, and yes,  we are currently only support single Postgres server.
`If we can only use a single IP must we manually repoint harbor if the DB switches its active node?`
I am not recommend to do so even you have tools  to handle this 'ip'  changes. Since there's might be some concerned with the data inconsistent during the transit.

But if you have handy experience on this, welcome to sharing with the community!

**Comment by snoop2048** [comment]
So harbor does not support any sort of HA Postgres backend?

**Comment by MinerYang** [comment]
Not exactly, I will take a look later

**Comment by MinerYang** [comment]
I am not sure how your `pgpool` is configured.  But theoretically, if you set up a `load balancer` in front of your pg service, I think one single hostname fro pg is enough. And you don't need to worry about fail over handle and synchronization of the db.

**Comment by snoop2048** [comment]
Hey, thanks for coming back to me. pgpool negates the need to an external LB for the postgres cluster as it handles loadbalancing itself (amongst other things).  Adding another LB (HAproxy or whatever) in front of is probably going to just cause issues. Admittedly getting slightly out of my depth here given I am not a DB engineer but I will try and get one to comment.

**Comment by MinerYang** [comment]
Thanks @snoop2048 ,

I am not familiar with the pgpool usage as well. All this `LB` things is  just based on my assumption.
So If you have any progress or experience here, please leave a comment for any users with the same doubt.
I will keep this issue for further discussion and references.

Best,
Miner

**Comment by Kajot-dev** [comment]
In terms of HA, I'm running Postgresql in HA with Patroni (using k8s operator) with no issues for the past year

**Comment by prima101112** [comment]
@snoop2048 

Regarding High Availability (HA), pgpool appears to function similarly to other PostgreSQL balancers such as pgbouncer. It's recommended to deploy a standalone pgpool for managing multiple databases. Clients can then connect to a single pgpool instance, which distributes the load across all databases it serves.

You might find valuable insights in this discussion: [Postgres with pgpool Architecture](https://dba.stackexchange.com/questions/125662/postgres-with-pgpool-architecture).

Thanks.
