### ISSUE TITLE
docker login doesn't work when running on Kubernetes

### ISSUE THREAD

**Issue by itl91290** [goharbor/harbor#1994]
I'm running Harbor on Kubernetes as described in [this document](https://github.com/vmware/harbor/blob/master/docs/kubernetes_deployment.md). The idea is to use Harbor as Kubernetes registry.

I've modified the nginx.svc.yaml file in order to expose the nginx service outside the cluster:

```
$ cat nginx.svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443
  selector:
    name: nginx-apps
  type: NodePort
```
I've also defined a DNS alias named `kube-harbor` which points to the K8S Master node.
In order to have something to pull, I'm trying to push a couple of images from a workstation (not part of the K8S cluster), but when logging in I get the following error:

```
~ $ docker login -u admin -p Harbor12345 https://kube-harbor:30443
Error response from daemon: Get https://kube-harbor:30443/v2/: Get https://kube-harbor/service/token?account=admin&client_id=docker&offline_token=true&service=token-service: dial tcp 10.134.100.168:443: getsockopt: connection refused
```
where 10.134.100.168 is the IP address of the Master, but no one is listening on port 443 on this IP. The only 443 listener is the nginx service, but on the servce IP:

```
$ kubectl get svc -o wide
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE       SELECTOR
jobservice   10.104.245.66    <none>        80/TCP                       1d        name=jobservice-apps
mysql        10.109.82.58     <none>        3306/TCP                     1d        name=mysql-apps
nginx        10.107.226.35    <nodes>       80:30080/TCP,443:30443/TCP   1d        name=nginx-apps
registry     10.106.101.213   <none>        5000/TCP,5001/TCP            1d        name=registry-apps
ui           10.103.125.226   <none>        80/TCP                       1d        name=ui-apps
```
I actually don't know if it's a real issue, or something missing on my configuration, but at least the docs for Kubernetes installation must be updated.

I'm running Kubernetes v.1.6.1 and Docker 1.12.6 on Centos 7.3
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by reasonerjt** [comment]
so what is kube-harbor in this case?

**Comment by itl91290** [comment]
As I've written:

> I've also defined a DNS alias named **kube-harbor** which points to the K8S Master node.

It's a CNAME record in my DNS system, which is resolved with the FQDN of the Master node.

I don't know if it's clear from the description, but what I'm **not** expecting here is that a call to `https://kube-harbor:30443` is re-directed to `https://10.134.100.168:443` (mainly because no one is listening on port 443 on 10.134.100.168)

**Comment by deerjoe** [comment]
i have same issue like this.so i built up harbor without k8s.than i found out there some differences   between both nginx config

have you edit harbor.cfg ?


> #The protocol for accessing the UI and token/notification service, by default it is http.
> #It can be set to https if ssl is enabled on nginx.
> ui_url_protocol = https

**Comment by reasonerjt** [comment]
The helm chart is the recommended way to deploy Harbor on k8s cluster.  Closing.
