### ISSUE TITLE
Inconsistent behaviour when creating/deleting retentionPolicies via API

### ISSUE THREAD

**Issue by sergimrz** [goharbor/harbor#19961]
**Actual behavior**
Currently when you create a retentionPolicy via api with the [POST] /retentions the api is automatically adding the reference of the newly created policy ID to the project metadata [here](https://github.com/goharbor/harbor/blob/f910c5654baf64a090f5b423ee6990d9f9adbc61/src/server/v2.0/handler/retention.go#L203C1-L206C3): 
```go
if err := r.proMetaMgr.Add(ctx, p.Scope.Reference,
	map[string]string{"retention_id": strconv.FormatInt(id, 10)}); err != nil {
	return r.SendError(ctx, err)
}
``` 

The problem comes when the [delete](https://github.com/goharbor/harbor/blob/f910c5654baf64a090f5b423ee6990d9f9adbc61/src/server/v2.0/handler/retention.go#L250) action is not doing the same behaviour of removing this reference. Because of this, if you just create and then remove a retentionPolicy the reference to the removed policy on the project will remain, and when you go to the retention policy section on the UI you will get an Internal Server Error because Harbor is trying to get the removed policy.

If you want to get rid of this errors after removing the retentionPolicy you need to call the [DELETE] /projects/?/metadatas/retention_id, but this is not consistent to the creation as initially you don't need to do that when creating the retention policy.

**Expected behavior**
The expectation is that the [DELETE] /retentions api call also removes the metadata retention_id with the reference of the retentionPolicy to the project.

**Comment by ramkrish12** [comment]
is there any schedule to get this issue fixed ?

without this fix, we have to perform image pruning manually.
