### ISSUE TITLE
EXT_ENDPOINT

### ISSUE THREAD

**Issue by kolesaev** [goharbor/harbor#19969]
Is _EXT_ENDPOINT_ always set as system hostname in installation time or is it configurable somehow? 
Our _external_url_ is set to the right url, but _EXT_ENDPOINT_ in core env file seems to be set from system hostname.

**Comment by stonezdj** [comment]
What is your installation type? docker-compose or helm

After updated the external_url in harbor.yml, reinstallation or rerun`./prepare --with-trivy ` and restart Harbor are required.

**Comment by kolesaev** [comment]
> What is your installation type? docker-compose or helm
> 
> After updated the external_url in harbor.yml, reinstallation or rerun`./prepare --with-trivy ` and restart Harbor are required.

Thanks for your reply.

We use docker-compose installation and did absolutely as you described above, but EXT_ENDPOINT wasn't updated, that's why our oidc test were redirecting us to a wrong url (https://<hostname>/<path>, e.g https://my-new-host-1/<path>). To resolve it we updated a hostname to a right fqdn and did installation again.

As far as i remember i double checked it, but will do additional tests tomorrow
