### ISSUE TITLE
Harbor does not cleanup s3 and shows wrong quota size

### ISSUE THREAD

**Issue by MukhachevDima** [goharbor/harbor#19973]
Hi!
Our harbor installation do not delete data from s3. 
On UI it shows less than 2 TB, but our S3 provider shows us 17 TB
![image](https://github.com/goharbor/harbor/assets/47418673/1cf06ace-5a0f-47f0-8e57-c3a004a9292a)
![image](https://github.com/goharbor/harbor/assets/47418673/b1e4780d-4de0-4d8a-bbb8-00266c03d616)

GC works fine and without errors
![image](https://github.com/goharbor/harbor/assets/47418673/950328f2-593d-4cbd-b417-659027cee238)

Example log from GC
```
2024-02-12T00:18:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:424]: [6c6b9ed2-5844-49b0-8d1b-bd1a5e449d57][1/424] delete blob from storage: sha256:7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab
2024-02-12T00:18:40Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:453]: [6c6b9ed2-5844-49b0-8d1b-bd1a5e449d57][1/424] delete blob record from database: 677143, sha256:7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab
```
And in S3 it's not deleted:
![image](https://github.com/goharbor/harbor/assets/47418673/f96fb1eb-7ec0-4246-8ea3-a740b91b421c)

**Expected behavior and actual behavior:**
Expected: Unused blobs are deleted from S3
Actual: They are not.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
0. Configure s3 as storage
1. Untag docker image
2. Run GC
3. Blob is not deleted from S3

**Versions:**
Please specify the versions of following systems.

- harbor version: [Version v2.9.0-44f5702]
- docker engine version: [23.0.1]
- docker-compose version: [1.24.0]

- **Docker-compose registry settings:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.

  registry:
    restart: always
    image: docker.io/bitnami/harbor-registry:2
    environment:
      - REGISTRY_HTTP_SECRET=SECRET
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=ACCESS
      - REGISTRY_STORAGE_S3_SECRETKEY=SECRET
      - REGISTRY_STORAGE_S3_REGIONENDPOINT="https://s3.storage.selcloud.ru"
      - REGISTRY_STORAGE_S3_BUCKET=harbor-registry
      - REGISTRY_STORAGE_S3_SECURE=false
      - REGISTRY_STORAGE_S3_SKIPVERIFY=true
      - REGISTRY_STORAGE_S3_region=ru-1
      - REGISTRY_STORAGE_S3_MULTIPARTCOPYTHRESHOLDSIZE=53687091200
      - REGISTRY_STORAGE_DELETE_ENABLED=true

**Comment by stonezdj** [comment]
Because the s3 is an s3 compatible storage, the behavior differs from the standard s3.
Could you please verify if you could use the s3 cli client to delete the blob from the s3 storage manually?`sha256:7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab`

**Comment by MukhachevDima** [comment]
```
aws s3 ls --endpoint-url https://s3.storage.selcloud.ru s3://harbor-registry/docker/registry/v2/blobs/sha256/78/7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab/data                                         
2024-02-11 03:00:59       7153 data
~ ❯ aws s3 rm --endpoint-url https://s3.storage.selcloud.ru s3://harbor-registry/docker/registry/v2/blobs/sha256/78/7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab/data
delete: s3://harbor-registry/docker/registry/v2/blobs/sha256/78/7811e8838410dcedac02d8f2ebff1386619b8b0b55fc101c3556553d3946a2ab/data
```
Yep, it's gone.
![image](https://github.com/goharbor/harbor/assets/47418673/62a73d98-ffe2-40c4-a792-44b0fb442de7)

So you think I should ask S3-compatible provider's support about this bug?

**Comment by MukhachevDima** [comment]
Issue is not resolved.
