### ISSUE TITLE
migrating harbor image store from filesystem to s3

### ISSUE THREAD

**Issue by strelok899** [goharbor/harbor#19970]
i deployed harbor as filesystem and all working really good but now i have pvc of 600GB (which is way more than planned initially) 

i want to migrate existing deployment to s3 backend, which is minio running on big storage servers with plenty of storage and bandwidth.

how can i make the migration? i can't find anywhere in the documentation how to migrate from filesystem to s3

**Comment by mway-niels** [comment]
Hey @strelok899, same issue here.

Would you mind sharing the steps you performed to complete the migration?

**Comment by strelok899** [comment]
Spinning up another harbor, replicated from filesystem one to s3 one and that's how it worked
