### ISSUE TITLE
Gitlab with Harbor integration [untagged artifacts]

### ISSUE THREAD

**Issue by reddare** [goharbor/harbor#19974]
Hello! Perhaps the topic is not entirely correct but I would like to ask the Harbor community.

I have integration configured with Gitlab.
And if there is an artifact without a tag in the Harbor project, then the integration breaks and displays an error.

![harbor](https://imgur.com/3hQNWeE.png)

![gitlab](https://i.imgur.com/ZzTEYbf.png)

If all artifacts without a tag are removed, then the integration works fine.

Is it possible to do something with the Harbor settings to change this behavior?

Untagged artifacts appear when, for example, an image with the same tag is pushed, unfortunately I cannot avoid such behavior.

I would be grateful for any advice. Thank you!

**Comment by tostt** [comment]
Although it does not solve the root problem, one thing you can do to mitigate this risk is to setup a cleanup task that is scheduled as often as you want via a cron expression. This can delete untagged artifacts. This is done in the "Clean up" section. Make sure you activate the option "Allow garbage collection on untagged artifacts".

**Comment by stonezdj** [comment]
Could you please describe your integration scenario so that we could reproduce this issue?

**Comment by reddare** [comment]
> Could you please describe your integration scenario so that we could reproduce this issue?

Hello, I have configured the Clenup Policy and also set up GC to remove untagged artifacts. I did this in the first place.
The problem is that they are scheduled to run, they can also be done by cron, but this does not exclude the appearance of my problem. I also don't want to run GC or Cleanup jobs too often, I have a lot of projects and new artifacts appear quite frequently.

To reproduce the problem, you need to take the following actions:

1. Set up GitLab integration with Harbor
2. Push any tagged image to Harbor project registry
3. Push the same tagged image but with a different SHA
4. Remove a tag from any of the artifacts in Harbor project

**Comment by reddare** [comment]
Anyone?

**Comment by psydok** [comment]
Same problem. Please tell me, has anyone solved it?
