### ISSUE TITLE
Pushing OCI image list fails with "unknown: artifact"

### ISSUE THREAD

**Issue by SQUIDwarrior** [goharbor/harbor#19977]
**Expected behavior and actual behavior:**
I am attempting to copy an OCI image list from a public repo into Harbor. I am using [skopeo](https://github.com/containers/skopeo) to copy the entire image list, including the attestation data, into Harbor so that we can use the multiple architectures (x86 and ARM) in our environment. 

However every time I try the copy, it fails with this error:
```
time="2024-02-15T05:11:12Z" level=fatal msg="Uploading manifest list failed, attempted the following formats: application/vnd.oci.image.index.v1+json(uploading manifest 1.8.7 to demo.goharbor.io/test/spiffe/spire-server: unknown: artifact test/spiffe/spire-server@sha256:ce3d81259b090eb1863d9f3caa106ecca418b19832d7e876abbe9be57cb4f0e7 not found), application/vnd.docker.distribution.manifest.list.v2+json(uploading manifest 1.8.7 to demo.goharbor.io/test/spiffe/spire-server: unknown: artifact test/spiffe/spire-server@sha256:f06facda1b4d90677661f5c8ba1c7b4dd6964eeefcbf10143e27cfe82242936f not found)"
```
I have confirmed the image is valid. I can use the same `skopeo` command to copy the image into an AWS ECR registry without error.

I see this problem with our own deployment of Harbor (2.7.2) and `demo.goharbor.io` (2.10.0). The image in particular is `ghcr.io/spiffe/spire-server:1.8.7` from the [Spire](https://github.com/spiffe/spire) Github repo, but the problem seems to be there for every image in this repo.

Using the built-in image replication in Harbor also fails.

**Steps to reproduce the problem:**
1. Install skopeo on your local system.
2. Login into `demo.goharbor.io` and create a new `test` project.
3. Authenticate Docker to `demo.goharbor.io`.
4. Run `skopeo copy --all docker://ghcr.io/spiffe/spire-server:1.8.7  docker://demo.goharbor.io/test/spiffe/spire-server:1.8.7`
5. Command will fail with the error mentioned above.

**Versions:**

- harbor version: 2.7.2 and 2.10.0
- docker engine version: 24.0.9
- skopeo version: 1.12.0

**Additional context:**
[skopeo_copy.log](https://github.com/goharbor/harbor/files/14291843/skopeo_copy.log)

I also tested this with `crane` and it failed with the same error.

**Comment by Vad1mo** [comment]
@SQUIDwarrior do you think this is related to https://github.com/goharbor/harbor/issues/19988

**Comment by SQUIDwarrior** [comment]
@Vad1mo Could be. Though I am not deleting anything. I am trying to use `skopeo` to copy an image for the first time and its failing the first time.
