### ISSUE TITLE
Documentation Request: Redis Password Change and Rotation in Harbor

### ISSUE THREAD

**Issue by goutham1012** [goharbor/harbor#19979]
Hi Team,

I'm seeking documentation or information on changing the Redis password in Harbor for a password rotation requirement. Any guidance or links would be appreciated.

**Comment by goutham1012** [comment]
Team, any update?

**Comment by stonezdj** [comment]
What is the redis type, is it an external redis used by Harbor?
If yes, you just need to update the password in harbor.yml and rerun `./prepare --with-trivy` and restart harbor.
