### ISSUE TITLE
Tag immutability of helm charts

### ISSUE THREAD

**Issue by joerocklin** [goharbor/harbor#19987]
There was mention in https://github.com/goharbor/harbor/issues/11730#issuecomment-623228259 about tag immutability rules applying to helm charts, and the issue closed. However, it doesn't seem to be working. Since that issue is still closed, I'm opening this with the information from testing I did.

I tried uploading (as a project admin) the same chart version with different contents on harbor v2.6.4-77903faf with all tags marked as immutable. There were no errors using the helm cm-push command and the updated contents were present for the 'old' version.

I thought "maybe this is because I put the immutability rules in place after uploading the original version?" So I repeated the experiment with a new helm chart put in place after the rules were set up. Same issue.

Immutability does not seem to be working on helm charts.

**Comment by Vad1mo** [comment]
I think we can close this one too. since 2.8 Harbor supports only OCI charts. So immutability on Chart Museum charts is not relveant anymore.

**Comment by joerocklin** [comment]
Help me understand: does your statement mean that OCI charts have immutable tags by default or that it is impossible to have immutable tags?

**Comment by stonezdj** [comment]
If you are storing helm charts as OCI artifacts. tag immutable feature should work with them.
