### ISSUE TITLE
Replication rule failed due to internal proxy authentication error

### ISSUE THREAD

**Issue by mesenger** [goharbor/harbor#19986]
Hi all,

Thank you for this great product.

I have Harbour configured with Docker hub registry and also Proxy cache. Getting to Docker hub is specifically permitted on internal company proxy. This works well.

Then I create replication rule, pull-based, using this Docker-hub registry as source, to pull 1 specific image, rancher/hello-world:latest.
This replication fails due to internal proxy not allowing this. 

How is it possible to Proxy cache method works, but replication does not?

Which Harbor container is actually running replication rules?

Thanks

**Comment by stonezdj** [comment]
It is the jobservice container which runs the replication rules, can you please check and compare the https_proxy env settings in harbor core container and jobservice container?
