### ISSUE TITLE
Replication between two harbor fails (UNAUTHORIZED error)

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor#19992]
I'm running two harbors for different purposes, and I need to replicate a specific image.
When I first configured this replication, it worked fine, but now it's not working well with an UNAUTHORIZED error.
Of course, I checked the permission of the robot account used to connect to the registry, and it failed as robot account, so I tried it as admin. It also failed.
I also checked that if I create a Public project on the replication recipient side, it succeeds without error.
However, I must have a private project.
Can anyone help me?

If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Successfully replicating a specific image between two harbors

**Steps to reproduce the problem:**
Failed replication attempts between two harbors.(UNAUTHORIZED error)

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.9.1]
- kubernetes version: 1.28.5

**error log**
```
2024-02-19T05:37:39Z [INFO] [/controller/replication/transfer/image/transfer.go:289]: copying the blob sha256:8ed16180acc1763e7d8b861093722b52c8f5e3c1d71e8f9f209e3a9928076ca9(the 1th running)...
2024-02-19T05:37:39Z [ERROR] [/controller/replication/transfer/image/transfer.go:395]: failed to pushing the blob sha256:8ed16180acc1763e7d8b861093722b52c8f5e3c1d71e8f9f209e3a9928076ca9, size 167: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to access repository: op-platform.backoffice/ditto-auth-test, action: push: unauthorized to access repository: op-platform.backoffice/ditto-auth-test, action: push"}]}
```

**Comment by stonezdj** [comment]
Is there any configuration recently? 
Could you please try to push/pull image with the same robot and admin account respectively via cli?

**Comment by derekcha** [comment]
@stonezdj 
First, thank you for your response.
I checked both image push and pull after logging in as robot and admin, and it worked fine.
Also, of course, test connection when registering harbor registries succeeded without any problem.

<img width="575" alt="스크린샷 2024-02-26 오전 11 16 09" src="https://github.com/goharbor/harbor/assets/62255222/4470f305-75a4-45d9-8d7b-7eca3b5d556b">

**Comment by Aslan-Liu** [comment]
I have the same issue. Espically when syncing many images (> 100) from A to B in one replication task.

Harbor
Version v2.5.1-b0506782

**Comment by Joseph94m** [comment]
We are facing the same issue where the replication intermittently fails either with 401 or 403. 

![image](https://github.com/goharbor/harbor/assets/40126230/1b5a7bc4-6f5d-48e9-ba2b-011392f1b589)
![image](https://github.com/goharbor/harbor/assets/40126230/88f02489-ee37-4339-9052-9d2fdece2e94)

**Comment by DeMaBo** [comment]
> I have the same issue. Espically when syncing many images (> 100) from A to B in one replication task.
> 
> Harbor Version v2.5.1-b0506782

I have the same issue with the Harbor version v2.10.2-1a741cb7. I can't replicate all the images from one harbor instance to another.

**Comment by Joseph94m** [comment]
For us, the solution was to correctly set the `max_open_conns`.
The value was simply too high, which was saturating the DB.

**Comment by dloxterm** [comment]
I run into the same issue.
For some reason, it works if I first do a docker push. Then the replication will always work again. As if the repository is not created by replication but by docker push.

@Joseph94m may I ask to what value you set max_open_conns?

**Comment by dloxterm** [comment]
Thanks!

In the meanwhile I figured out that it was not the max_open_conns but the fact that I made a typo in the protocol, I used http instead of https for the remote registry. After fixing that it started to work.

Odd that the connection test and pushing deleted images worked, but I guess that would be part of another issue.

**Comment by cloudzhongtian** [comment]
I also encountered this problem, how was it ultimately resolved?
