### ISSUE TITLE
Docker login error: Error response from daemon: Get "https://harbor.com.vn/v2/": EOF

### ISSUE THREAD

**Issue by tsukiazuma** [goharbor/harbor#19995]
Hi,

I can't docker login Harbor when use proxy:
- use command line: `docker login harbor.com.vn -u user`
- get error: `Error response from daemon: Get "https://harbor.com.vn/v2/": EOF`
- Docker version 20.10.17, build 100c701
- Harbor version v2.10.0-6abb4eab

**Comment by zyyw** [comment]
@tsukiazuma will you be able to login via the Harbor portal web UI?
Maybe you wanna try to set the `external_url` https://github.com/goharbor/harbor/blob/main/make/harbor.yml.tmpl#L41

Please let us know if this works.

**Comment by tsukiazuma** [comment]
Yeah, I can login via web UI.
If not use proxy, I still docker login. But when I add proxy, can;t docker login

**Comment by zyyw** [comment]
@tsukiazuma Are you still not able to `docker login` under proxy added even with the `external_url` being set?

**Comment by tsukiazuma** [comment]
@zyyw Yeah I try external_url in harbor.yml and harbor.yml.tmpl, but it not work

**Comment by zyyw** [comment]
Could you please also share with us what Proxy you are using?
* Traefik
* haproxy
* Nginx

**Comment by zyyw** [comment]
For customization deployment of Harbor behind a Proxy, community help and sharing are welcome and appreciated!

**Comment by tsukiazuma** [comment]
> Could you please also share with us what Proxy you are using?
> 
> * Traefik
> * haproxy
> * Nginx
> 
> some issue related to installing Harbor behind a proxy:
> 
> * [Harbor 2.0 without HTTPS - Issue to authenticate (htpasswd)  behind a reverse proxy  #12364](https://github.com/goharbor/harbor/issues/12364)
> * [docker login failed, unauthorized: authentication required #9429](https://github.com/goharbor/harbor/issues/9429)
> 
> BTW, after setting `external_url`, you will also need to re-install it or re-run the prepare script to make it take effect to the system.

Yeah, I use Nginx.
Hope the problem will be resolved soon
