### ISSUE TITLE
Getting unauthorized: unauthorized to access repository :

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#19999]
Hi Team,

The user is getting "unauthorized: unauthorized to access repository:" while pushing the image on the harbor registry. Repo is owned by the user, but  still getting this error. After some time, they re-ran the build and were able to push an image. 

Has anybody faced a similar issue?

Harbor Version : v2.3.0

**Comment by zyyw** [comment]
That's odd. Please try to upgrade your Harbor instance to newer version. Harbor v2.3.0 is out of support.
