### ISSUE TITLE
In clean up we have facing issue in harbor

### ISSUE THREAD

**Issue by syslabtech** [goharbor/harbor#20011]
In the UI Harbor cleanup section we have seen when we enable the toggle button **Allow garbage collection on untagged artifacts**
and then we refresh the page it does not work toggle goes back to the default state.

we have installed the latest version of Harbor 2.10
![Screenshot from 2024-02-06 13-53-04](https://github.com/goharbor/harbor-helm/assets/134613532/2419a59a-236d-4a12-9b8e-289fca6a43ee)

**Comment by chlins** [comment]
I think this option here is just a parameter every time gc is triggered rather than a persistent configuration.
