### ISSUE TITLE
In job service dashboard we have facing issue.

### ISSUE THREAD

**Issue by syslabtech** [goharbor/harbor#20012]
In harbor web UI we have seen on job type  **EXECUTION_SWEEP**  latency is very high and this job is the default job of Habor. also, we don't know what is the purpose of this job.

We have used the latest Harbor 2.10 with external Postgres and internal Redis configuration.

How to fix this issue on Harbor?
![Screenshot from 2024-02-06 14-43-23](https://github.com/goharbor/harbor-helm/assets/134613532/69f61d62-bad6-4e6b-9c3b-89f2664ced45)

![Screenshot from 2024-02-06 15-09-47](https://github.com/goharbor/harbor-helm/assets/134613532/db8a39c4-bc5c-4be0-a640-4b5699e92b0f)

**Comment by zyyw** [comment]
Hi @stonezdj, could you please help to provide some insight on this?

**Comment by ivoistaken** [comment]
The issue happens only for non-admins, it might be connected with the following:
GET /api/v2.0/jobservice/queues
200 + json for admins
403 for non-admins - may be this triggers the yellow warning?
