### ISSUE TITLE
Error when running Garbage Collection (Logs: object is not found, using s3)

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor#20029]
I ran Clean Up, Garbage Collection to clean up the repository (aws s3) while using harbor, but it failed to run with an error.
I tried to click Logs to find out the cause, but the only message is like below.
`{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"log entity: 3374b652710f236be44037b1\"}"}]}`

As I said above, I am using aws s3 for storage, and the current size of s3 is about 73TB. When I check the Job Service Dashboard, the GARBAGE_COLLECTION Job seems to be stuck in Pending status, can you tell me the cause and solution?
Please let me know if there are any logs in debugging

<img width="2404" alt="스크린샷 2024-02-26 오전 11 06 30" src="https://github.com/goharbor/harbor/assets/62255222/63e5edd2-d59c-4f08-bb55-ea854f36cb04">

<img width="2405" alt="스크린샷 2024-02-26 오전 11 06 14" src="https://github.com/goharbor/harbor/assets/62255222/b43ec3d6-4f3e-44bc-9825-af8e3128d524">

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.9.1]
- kubernetes version: 1.28.5

**Comment by zyyw** [comment]
@derekcha , could you please try to set the `Workers` to `5`? And then retry GC.

**Comment by derekcha** [comment]
@zyyw 
Do you have any additional advice?

**Comment by linpanru** [comment]
what state  about your  Garbage Collection   task  display  on web page when you click stop button to stop a running gc task ?   it is still running  ,is ok or  bug ?
