### ISSUE TITLE
Regarding Duplicate Repositories

### ISSUE THREAD

**Issue by SunilDD** [goharbor/harbor#20026]
I encountered the same issue after upgrading from Harbor version **v2.8.2-d4c34dcc to v2.8.4-ad3e767d** regarding image repository management.

Before the upgrade, I had several images pushed with different repository names, **some containing underscores ('_') and hyphens ('-'). For instance, repositories like go_admin_task/image:1.0, go-admin-task/image:1.0, before-upgrade:1.0, and before_upgrade:2.0 were present.**

After the upgrade, I noticed that images from repositories with **names differing only in the use of underscores or hyphens were unexpectedly deleted**. **Specifically, repositories with names like go_admin_task/image:1.0 and go-admin-task/image:1.0, as well as before-upgrade:1.0 and before_upgrade:2.0, were affected. Interestingly, repositories without such naming discrepancies, like temp_admin/image:1.0 and temp_admin/image:2.0, remained intact.**

Furthermore, **attempts to push images to repositories containing underscores or hyphens post-upgrade resulted in the creation of duplicate repositories. This behavior was not observed prior to the upgrade.**

I believe this issue warrants attention from the Harbor community as it impacts repository management consistency and may lead to unintended data loss or duplication. Any assistance or insights into resolving this matter would be greatly appreciated.

Steps to Reproduce the issue:

**Before Upgrade: Version -> v2.8.2-d4c34dcc**

1. Uploaded images to repositories with similar names like go_admin_task and go-admin-task, differing only in the use of '-' and '_'.
2. Uploaded images to a single repository, either temp_admin or temp-admin, containing either '-' or '_'.

**After Upgrade: Version -> v2.8.4-ad3e767d**

1. Upon attempting to access images from repositories like go_admin_task and go-admin-task, images were found to be deleted, despite being present before the upgrade.
2. Images in the temp_admin repository were still accessible post-upgrade.
3. Trying to push images to repositories with names like go_admin_task and go-admin-task resulted in the creation of duplicate repositories.

These observations suggest a discrepancy in repository management post-upgrade, specifically regarding repositories with similar names distinguished only by the use of '-' and '_'. 

Thank you,
Sunil

**Comment by SunilDD** [comment]
Yes, that thread was closed somehow, I thought of raising it again with proper steps of reproducing the issue.

**Comment by zyyw** [comment]
please try the workaround in the dup issue. closing this issue now.

**Comment by SunilDD** [comment]
Can you able to reproduce the issue ?
