### ISSUE TITLE
Harbor logic backup metadata, import error is the only index error

### ISSUE THREAD

**Issue by smallemployees** [goharbor/harbor#20044]
error:
![1709028261216](https://github.com/goharbor/harbor/assets/150658327/d52fcb77-cdd5-43aa-8294-9b8251987dfe)
backup:
pg_dump -h 127.0.0.1 -U postgres -p 5432 -d registry --inserts > registry.sql
import:
psql registry -U postgres < /tmp/registry.sql

**Comment by MinerYang** [comment]
could you provide your table `robot` sort by id?
