### ISSUE TITLE
what is best practice regarding mult-strcuture images

### ISSUE THREAD

**Issue by nanyi545** [goharbor/harbor#20043]
does any one know, what is the best practice regarding mult-strcuture(arm64, amd64) image management in harbor?

should i use one image name for different strcutures, or different image names?  

it seems on docker hub, you can have different OS/ARCH for one image name, does harbor support this?

thanks in advance!!

**Comment by wy65701436** [comment]
you can try with the index, which is defined in the image spec and harbor already supported it.

**Comment by nanyi545** [comment]
> you can try with the index, which is defined in the image spec and harbor already supported it.

could you kindly elaborate this a bit further or give a link in the doc?

I tried to find "index" in harbor web-ui and in harbor api, but i could not.
