### ISSUE TITLE
Project_blob表，主键ID不连续，导致serial类型快速耗尽，push镜像失败

### ISSUE THREAD

**Issue by pioneerlfn** [goharbor/harbor#20054]
观察project_blob表，id不连续，出现很多跳几十个ID的洞，serial类型的sequence耗尽
![image (3)](https://github.com/goharbor/harbor/assets/37978533/bf96b1bf-8b87-4ba5-99d2-2a65d62e4dce)

**Comment by pioneerlfn** [comment]
![Uploading image (3).png…]()

**Comment by wy65701436** [comment]
how many records are there in the table project_blob? The inconsistent IDs are due to some of them being removed in alignment with the deletion of an artifact.

Can you share the failure log on pushing?
