### ISSUE TITLE
[SBOM] Update existing scan job service, add support to generate SBOM for an artifact

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#20065]
Update existing scan job service, add support to generate SBOM for an artifact

Because it requires the scanner to be updated to meet the requirement of pluggable scanner spec v1.2, the job service should include the API change of spec v1.2

**Comment by Vivekgaddigi** [comment]
@stonezdj Would Like to work on this

**Comment by Vivekgaddigi** [comment]
@stonezdj Are there any other SBOM Issues that i can work on ?
