### ISSUE TITLE
[SBOM] display generate SBOM status when it is not complete, if it complete, display the link to the SBOM detail

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#20064]
In the list artifact table, if there is sbom_enabled (systeminfo API), it will display the SBOM status if it is not complete. if complete display the link to the SBOM detail

**Comment by stonezdj** [comment]
Depends on 
- https://github.com/goharbor/harbor/issues/20057

**Comment by xuelichao** [comment]
I think this issue has already been fixed, we can reopen it if encounter it again.
