### ISSUE TITLE
Proxy-cache image deletion still served by SHA

### ISSUE THREAD

**Issue by Hapshanko** [goharbor/harbor#20079]
Hello team,
Does a harbor proxy-cache project delete an image only by TAG when deleted in the target repository?

I read in the documentation that `If the image is no longer in the target registry, no image is served.` but was not sure if this is exactly what it means.

Asking this to clarify because, when the image is deleted I seem to notice pulling it by a TAG (from the proxy-cache) indeed does not work anymore, but if I pull the same image by SHA, it still works.. 
so it seems to me as its not fully deleted?

Would like to know more about this process!

Another unexpected behavior on my client:
For some reason after the image is deleted from the target repository and proxy-cache no longer serves it by TAG, my machine that still HAS the image locally, upon a docker pull by TAG still tried to pull it from the proxy-cache(which results in a not found error) instead of using the image locally!
Which it has! Any idea how this could happen? 
It really impacted our production stability, and goes against what I knew about images.

**Comment by stonezdj** [comment]
could you please check the proxy.log when it is pulling image from proxy cache project? the first request could be a HEAD request to the proxy-cache with tag, when the client knows the digest of the tag, then the second request is a GET request to the proxy-cache with digest.

**Comment by MinerYang** [comment]
Could you describe what is `delete an image only by TAG `?

**Comment by Hapshanko** [comment]
> Could you describe what is `delete an image only by TAG `?

What I mean is exactly my question, I noticed that when an image is deleted in the target repository, the proxy cache no longer serves that image specifically by TAG, but if I try to pull it by SHA it still serves it, hence I am trying to understand what goes on in the background.

**Comment by Hapshanko** [comment]
> could you please check the proxy.log when it is pulling image from proxy cache project? the first request could be a HEAD request to the proxy-cache with tag, when the client knows the digest of the tag, then the second request is a GET request to the proxy-cache with digest. 

Where is this file located? We are deploying harbor on k8s.

The only log we saw in the stdout of the container was a warning log for when an image is not found when pulled by TAG that doesnt exist/was deleted from target repository

**Comment by Hapshanko** [comment]
Any updates?

**Comment by MinerYang** [comment]
cc @stonezdj
