### ISSUE TITLE
when does harbor support ARM?

### ISSUE THREAD

**Issue by chimisu** [goharbor/harbor#20074]
**Is your feature request related to a problem? Please describe.**
As a CNCF project,Habor hasn't a official ARM support,is it very hard for harbor team?I cant understand,there are many people need a official ARM release.

And there aren't any update in harbor-arm repo.

**Describe the solution you'd like**
Release a official ARM verison.

**Describe the main design/architecture of your solution**
Release a official ARM verison.

**Describe the development plan you've considered**
Release a official ARM verison.

**Additional context**

**Comment by Vivekgaddigi** [comment]
make this a discussion

**Comment by zyyw** [comment]
please discuss Harbor on ARM in this repository:
* https://github.com/goharbor/harbor-arm

**Comment by MinerYang** [comment]
However, no one is working on this .
Welcome to contribute in this project https://github.com/goharbor/harbor-arm

**Comment by chimisu** [comment]
> please discuss Harbor on ARM in this repository:
> 
> * https://github.com/goharbor/harbor-arm

No update anymore.

**Comment by chimisu** [comment]
Does Harbor team has plan or roadmap on ARM release?

**Comment by wy65701436** [comment]
There is no plan or roadmap for harbor on ARM because of the limited resource from the maintainer group. And we're open for any contribution from the community, if anything that want to be discussed, please join the community meeting to discuss with the maintainer directly.

**Comment by Satur6ay** [comment]
I found a arm copy
https://github.com/wise2c-devops/build-harbor-aarch64

**Comment by monotek** [comment]
The harbor-arm repo seems unmaintained.
Any chance this will be implemented in this repo?
