### ISSUE TITLE
Harbor doesn't replicate all image tags

### ISSUE THREAD

**Issue by petr202261** [goharbor/harbor#20086]
If you are reporting a problem, please make sure the following information is provided:

**Expected behavior and actual behavior:**
I push images from my pipeline to the harbor repo with such command:
`docker push --all-tags "$domain/$image_name"`

the image is created in the Harbor repo with all tags correctly. Then I have a replication policy to push an image to ECR or ACR, like this
![image](https://github.com/goharbor/harbor/assets/162141909/36e10e9e-0d9b-4039-9c81-e4a3390e5b5d)

actual behavior: 
image in harbor has three tags (e.g. feb5, default-290487, 290487 )
replicated image to ACR has only two tags: feb5, default-290487
NOTE: this issue happens from time to time

expected behavior:
all image tags are replicated to ECR or ACR.

**Steps to reproduce the problem:**
1. create a docker image with tag 290487
2. add two additional tags with commands
`docker tag "$image_name:290487" "$domain/$image_name:default-290487"`
`docker tag "$image_name:290487" "$domain/$image_name:feb5"`
3. push images to harbor
`docker push --all-tags "$domain/$image_name"`
4. Harbor replicate images
5. Check image tags in target harbor cloud repositories: ECR or ACR

- harbor version: [2.9.1]
- docker engine version: [24.0.6-dind]

**Comment by Vad1mo** [comment]
Error messages in the logs, jobsservice etc?

**Comment by Vad1mo** [comment]
Anything that would help us replicate the problem?

**Comment by petr202261** [comment]
I checked logs - there are logs on how harbor replicated two tags and no at all logs that contain the third tag - "290487"

**Comment by petr202261** [comment]
also I could not find any errors in logs

**Comment by MinerYang** [comment]
Could you check the specific replication task log via Harbor UI?

**Comment by petr202261** [comment]
I found out that it was an incorrect combination of label and tag patterns in our replication rules. I've fixed our harbor replication rules.
Thank you for your response.

**Comment by riyas-rawther** [comment]
@petr202261 we have a similar issue.
When we add additional tags to an image, the replication not adding the tag alias to the destination Harbor.

Could please explain more, how did you solves this?
