### ISSUE TITLE
Harbor can't connect to external redis using TLS connection 

### ISSUE THREAD

**Issue by SoaadMahmoud** [goharbor/harbor#20109]
We we tried to setup elasticache cluster "redis" on aws and tried to connect harbor to it we got timeout as harbor doesn't support TLS connection so Is it possible to have this functionality to have additional attribute in harbor.yml for external redis for TLS enable

**Comment by Vivekgaddigi** [comment]
@Vad1mo

**Comment by MinerYang** [comment]
Hi @SoaadMahmoud ,

Please see progress of this feature:
https://github.com/goharbor/harbor/issues/13223#issuecomment-1960778516
