### ISSUE TITLE
Feature Request: Allow Robot Accounts to manage Robots!

### ISSUE THREAD

**Issue by pmeyer34** [goharbor/harbor#20110]
Hi,

I would like to create a "super" robot that can create/update/list robots.

i've seen this [comment](https://github.com/goharbor/harbor/issues/14145#issuecomment-781006533) but the robot resources seems to be missing.

if i try this payload when creating a new robot : 

```json 
{
  "name": "test-robot",
  "duration": 30,
  "description": "test",
  "disable": false,
  "level": "system",
  "permissions": [
    {
      "kind": "system",
      "namespace": "/",
      "access": [{ "resource": "robot", "action": "*" }]
    }
  ]
}
``` 

i have this error :
```json
{
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "bad request permission: robot:*"
    }
  ]
}
```

**Comment by MinerYang** [comment]
Hi @pmeyer34 ,

Please refer to this comment on robot account usage in harbor
https://github.com/goharbor/harbor/issues/20076#issuecomment-1982721136

**Comment by pmeyer34** [comment]
hello, thanks i haven't seen this issue.
I have exactly the same use case of #20076 so i can close this one and follow up the other one.
