### ISSUE TITLE
Can't validate the project_metadata

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#20117]
Send the following request to Harbor
```
PUT /api/v2.0/projects/<project_id>
```
Payload
```
{"metadata":{"public":"123"}
```

It seems that the backend API doesn't validate the public data type should be boolean, and the public metadata is updated to `123`

**Comment by stonezdj** [comment]
Send the following request to Harbor
```
PUT /api/v2.0/projects/<project_id>/metadatas/public
```
Payload
```
{
    "public": "true"
}
```
Got HTTP 400 error
```
{
    "errors": [
        {
            "code": "BAD_REQUEST",
            "message": "invalid key: "
        }
    ]
}
```

**Comment by zyyw** [comment]
> Send the following request to Harbor
> 
> ```
> PUT /api/v2.0/projects/<project_id>/metadatas/public
> ```
> 
> Payload
> 
> ```
> {
>     "public": "true"
> }
> ```
> 
> Got HTTP 400 error
> 
> ```
> {
>     "errors": [
>         {
>             "code": "BAD_REQUEST",
>             "message": "invalid key: "
>         }
>     ]
> }
> ```

This part is tracking in this issue: 
* https://github.com/goharbor/harbor/issues/20120
