### ISSUE TITLE
How to manage a harbor via an API using the command line?

### ISSUE THREAD

**Issue by SterhLight** [goharbor/harbor#20123]
I apologize for a possibly stupid question. But I can’t get information through the API using the command line and using curl.
I haven’t read any manual and tried all the commands. The result is zero. I read that you need to get a token, but you can’t get it either. Help me! I'm stumped!
The installation method was docker-compose.

**Comment by reasonerjt** [comment]
What's the authentication mechanism you are using for your Harbor instance?

**Comment by SterhLight** [comment]
> What's the authentication mechanism you are using for your Harbor instance?

OIDC

**Comment by stonezdj** [comment]
You could create a robot account with required permission and access the REST API with robot account (basic auth)

**Comment by reasonerjt** [comment]
As per the design for OIDC integration, if User A is on boarded to Harbor via OIDC flow, the credential that is usable to Harbor will be the ID token.

Depending on the OIDC provider it can be difficult to get the ID token, the robot account approach mentioned by @stonezdj  is a workaround.

In addition, we used to think about providing "API secret" mechanism for users to call the API, but as of now, it's not a priority.

**Comment by SterhLight** [comment]
Thank you. I figured out how to use API

**Comment by reasonerjt** [comment]
Thanks, I'm resolving this issue.
