### ISSUE TITLE
Tag retention rules for multiple repos with slashes crashes the backend

### ISSUE THREAD

**Issue by gboor** [goharbor/harbor#20129]
I found more references to this issue; #14510 and #14259 and #196, but those tickets are old and closed and it seems this issue was never actually resolved.

I am running Harbor 2.10.0 on Kubernetes and I have some retention policies in place that I want to run on all repos except 2 specific ones.

These repos have names like `nsA/nsB/nsC/project1` and `nsA/nsB/nsD/nsE/project2`. If I add those as an excluding rule (as `nsA/nsB/nsC/project1,nsA/nsB/nsD/nsE/project2`), it saves just fine, but doing a run (dry or real) of the rule literally crashes the harbor-core container with the following message;

```
[ERROR] [/jobservice/logger/service.go:99]: failed to launch the retention jobs, err: launcher: syntax error in pattern
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x103b190]

goroutine 9686 [running]:
github.com/goharbor/harbor/src/controller/retention.(*defaultController).TriggerRetentionExec.func1()
	/harbor/src/controller/retention/controller.go:287 +0x570
created by github.com/goharbor/harbor/src/controller/retention.(*defaultController).TriggerRetentionExec in goroutine 230
	/harbor/src/controller/retention/controller.go:261 +0x2e5
```

It then takes half a minute to restart before things are running again.

I think it's pretty bad that a malformed rule can crash the backend like that, but apart from that, I also have no idea how to exclude these 2 repos from the policy...

Is there a syntax that works here at all? Or a workaround of some sort?

If someone can point me to the relevant function(s) in the source, I also don't mind having a look myself.

**Comment by chlins** [comment]
@gboor The error syntax should not crash the backend, it should be a bug included in https://github.com/goharbor/harbor/pull/19533, will fix it.

**Comment by gboor** [comment]
@chlins thanks for following up and good to hear that the crash is being resolved, but that doesn't fix my original problem; how do I phrase these rules so they work properly? Is it possible at all?
