### ISSUE TITLE
Projects Endpoint can be accessed without Authentication

### ISSUE THREAD

**Issue by aydinnyunus** [goharbor/harbor#20136]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Expected Behavior: Unauthenticated users should not see the all projects and username info.
Actual Behavior: Unauthenticated users can see the all projects and username info.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

Go to following endpoint:

- https://demo.goharbor.io/api/v2.0/projects?page=1&page_size=15

**Versions:**
Please specify the versions of following systems.

demo server

**Comment by stonezdj** [comment]
It works as designed, it is a public project.

**Comment by aydinnyunus** [comment]
Hi @stonezdj 

The demo page serves as an example. Even if sign-up functionality is disabled, an unauthenticated attacker can access the public projects and usernames through this API endpoint, resulting in a leakage of usernames and project names."

**Comment by stonezdj** [comment]
It is a public project already. if the admin doesn't want display this information, change it to private.
