### ISSUE TITLE
How to install Harbor on RedHat using podman ?

### ISSUE THREAD

**Issue by olistu** [goharbor/harbor#20146]
Hi,

I want to install Harbor on my RedHat server using Podman. But the install.sh file give some error with the compatibility Podman.

See the error below : 
[root@svx-lab-03m harbor]# ./install.sh

[Step 0]: checking if docker is installed ...
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

Note: docker version: 4.6.1
✖ Need to upgrade docker package to 17.06.0+.
[root@svx-lab-03m harbor]#

The install.sh file made a check with the version docker but docker is not installed on this server. This is podman

I need help
Regards
Olivier

**Comment by stonezdj** [comment]
Harbor doesn't support podman so far.

**Comment by olistu** [comment]
Finally, I have install Docker on my RedHat server. And now I'm able to install Harbor.
