### ISSUE TITLE
OIDC integration via Helm charts

### ISSUE THREAD

**Issue by avibellapu** [goharbor/harbor#20142]
I am installing and setting up Harbor using Helm on my openshift cluster. However, setting up the OIDC has been a manual setup for me once I installed Harbor using Helm charts.

I want to get a solution to integrate this into my helm charts, so the installation and setup with OIDC would be automated out of the box for me.

**Comment by stonezdj** [comment]
see https://goharbor.io/docs/2.10.0/install-config/configure-system-settings-cli/


Set Configuration Items Using An Environment Variable
Introduced in 2.3.0 is the ability to use an environment variable, CONFIG_OVERWRITE_JSON, in the core container to set the configuration. Once the CONFIG_OVERWRITE_JSON variable is set, you can only update or remove the configuration by updating the CONFIG_OVERWRITE_JSON and restarting the container. You will not be able to update the configuration in the Harbor interface or in the commandline.

Example CONFIG_OVERWRITE_JSON configuration:
```
CONFIG_OVERWRITE_JSON={"ldap_verify_cert":"false", "auth_mode":"ldap_auth","ldap_base_dn":"dc=example,dc=com", "ldap_search_dn":"cn=admin,dc=example,dc=com","ldap_search_password":"admin","ldap_url":"myldap.example.com", "ldap_scope":2}
```
See the [Harbor Configuration Items](https://goharbor.io/docs/2.10.0/install-config/configure-system-settings-cli/#harbor-configuration-items) table below for more information about available inputs for CONFIG_OVERWRITE_JSON.

**Comment by stonezdj** [comment]
see: https://github.com/goharbor/harbor-helm/blob/cc7016a5ee4de7c7212a1814770582ae0498ff17/values.yaml#L584C3-L584C24
