### ISSUE TITLE
How to configure Harbor to use signed certificate

### ISSUE THREAD

**Issue by olistu** [goharbor/harbor#20151]
Hi,

I want to use the company signed certificate but not the self signed as describe in the documentation.

I need help to use my signed certificate.

Regards
Olivier

**Comment by MinerYang** [comment]
https://github.com/goharbor/harbor/blob/69fc957d7e8745474169f9a2df78d869be8d4650/make/harbor.yml.tmpl#L12

**Comment by stonezdj** [comment]
https://goharbor.io
