### ISSUE TITLE
Retention policy not replicated 2.8.2 --> 2.10.1

### ISSUE THREAD

**Issue by kingnarmer** [goharbor/harbor#20160]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Replication task doesn't replicate "Retention polices" .  The "retention policies" used to be replicated from 2.8.2 --> 2.8.2

**Steps to reproduce the problem:**
Create replication policy to replicate all source harbor(2.8.2)  to destination harbor (2.10.1).

**Versions:**
Please specify the versions of following systems.

- harbor version: SRC 2.8.2 , DST 2.10.1
- k8s engine version: SRC k8s 1.28 , DST: 1.29

**Comment by stonezdj** [comment]
Only the image is replicated to the target, the retention policy isn't replicated

**Comment by kingnarmer** [comment]
@stonezdj  Actually what started this is that images deleted on source harbor weren't deleted on remote harbor. I have "event based" replication with "delete remote resources when locally deleted" . Do I open new issue or reopen this one. Thanks
