### ISSUE TITLE
Unable to update registry_id in a proxy-cache project 

### ISSUE THREAD

**Issue by nice2be** [goharbor/harbor#20176]
**Expected behavior and actual behavior:**

The registry_id needs to be updated in a proxy-cache project in order to switch to another (working) registry.  

Currently, the update properties operation (PUT /api/v2.0/projects/{project_name_or_id}) returns HTTP/2 200, but the registry_id is not updated. 

**Steps to reproduce the problem:**

	- List the registries

$ curl -s -k -u "admin:\<password\>" -H "Content-Type: application/json" -X GET "https://\<harbor0-fqdn\>:30003/api/v2.0/registries"  | jq
[
  {
    "creation_time": "2024-03-26T22:11:08.666Z",
    "credential": {
      "access_key": "admin",
      "access_secret": "*****",
      "type": "basic"
    },
    **"id": 7,**
    "insecure": true,
    "name": "test-registry1",
    "status": "healthy",
    "type": "harbor",
    "update_time": "2024-03-26T22:11:08.666Z",
    "url": "https://\<harbor1-fqdn\>"
  },
  {
    "creation_time": "2024-03-26T22:12:41.798Z",
    "credential": {
      "access_key": "admin",
      "access_secret": "\*****",
      "type": "basic"
    },
    **"id": 8,**
    "insecure": true,
    "name": "test-registry2",
    "status": "healthy",
    "type": "harbor",
    "update_time": "2024-03-26T22:12:41.798Z",
    "url": "https://\<harbor2-fqdn\>"
  }
]

	- Create a proxy cache project
	
$ vi ./proxy-cache/test-project.json
{
  "project_name": "proxy-cache",
  "metadata": {
    "public": "true"
  },
  **"registry_id": 7**
}

$ curl -i -k -u "admin:\<password\>" -H "Content-Type: application/json" -X POST 'https://\<harbor0-fqdn\>:30003/api/v2.0/projects' -d @./proxy-cache/test-project.json
HTTP/2 201

	- List the projects
	
$ curl -s -k -u "admin:\<password\>" -H "Content-Type: application/json" -X GET "https://\<harbor0-fqdn\>:30003/api/v2.0/projects"  | jq '.[] | select(.name=="proxy-cache")'
{
  "chart_count": 0,
  "creation_time": "2024-03-26T22:18:45.773Z",
  "current_user_role_id": 1,
  "current_user_role_ids": [
    1
  ],
  "cve_allowlist": {
    "creation_time": "0001-01-01T00:00:00.000Z",
    "id": 22,
    "items": [],
    "project_id": 22,
    "update_time": "0001-01-01T00:00:00.000Z"
  },
  "metadata": {
    "public": "true",
    "retention_id": "6"
  },
  "name": "proxy-cache",
  "owner_id": 1,
  "owner_name": "admin",
  "project_id": 22,
  **"registry_id": 7,**
  "repo_count": 0,
  "update_time": "2024-03-26T22:18:45.773Z"
}

	- Update properties (registry_id) for a proxy cache project

$ vi ./proxy-cache/update-test-project.json 
{
  "project_name": "proxy-cache",
  "metadata": {
    "public": "true"
  },
  **"registry_id": 8**
}

$ curl -i -k -u "admin:\<password\>" -H "Content-Type: application/json" -X PUT 'https://\<harbor0-fqdn\>:30003/api/v2.0/projects/22' --data @./proxy-cache/update-test-project.json
HTTP/2 200

$ curl -s -k -u "admin:\<password\>" -H "Content-Type: application/json" -X GET "https://\<harbor0-fqdn\>:30003/api/v2.0/projects"  | jq '.[] | select(.name=="proxy-cache")'
{
  "chart_count": 0,
  "creation_time": "2024-03-26T22:18:45.773Z",
  "current_user_role_id": 1,
  "current_user_role_ids": [
    1
  ],
  "cve_allowlist": {
    "creation_time": "0001-01-01T00:00:00.000Z",
    "id": 22,
    "items": [],
    "project_id": 22,
    "update_time": "0001-01-01T00:00:00.000Z"
  },
  "metadata": {
    "public": "true",
    "retention_id": "6"
  },
  "name": "proxy-cache",
  "owner_id": 1,
  "owner_name": "admin",
  "project_id": 22,
  **"registry_id": 7,**
  "repo_count": 0,
  "update_time": "2024-03-26T22:18:45.773Z"
}

**Versions:**
- harbor version: v2.5.0-3fcdf8e4
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Comment by stonezdj** [comment]
You could update it in the database, it should work. 
As a requirement, it doesn't have high priority in the queue.

**Comment by nice2be** [comment]
Updating the **registry_id** in the database might be a workaround, but we need the rest API ( /api/v2.0/projects/{project_name_or_id}) to be fixed to handle proxy-cache project changes.
