### ISSUE TITLE
Using Harbor as the source for Azure/AWS pull through cache.

### ISSUE THREAD

**Issue by ncrmro** [goharbor/harbor#20174]
I understand this is not an issue with Harbor per say but wondering if there is any guidance or work arounds currently. 

Context being we distribute images and some of our private install clients would like to pull our images into their registries.

```
➜  ~ aws --profile us-prod ecr create-pull-through-cache-rule \
     --ecr-repository-prefix harbor \
     --upstream-registry-url harbor.example.com \
     --region us-east-1

An error occurred (UnsupportedUpstreamRegistryException) when calling the CreatePullThroughCacheRule operation: The upstream registry URL harbor.example.com is invalid. Specify a valid upstream registry URL and try again
```

Azure ACR has an [issue for this](https://github.com/Azure/acr/issues/682) and mentioned it was in the works but it's closed because it's stale.

```
➜  ~ az acr cache create -r example -n example-harbor -s harbor.example.com -t example-images
(UpstreamNotSupported) Unsupported upstream or login server 'harbor.example.com' provided. Supported upstreams or login servers are: docker.io, mcr.microsoft.com, quay.io, public.ecr.aws, ghcr.io, nvcr.io, registry.k8s.io, gcr.io.
Code: UpstreamNotSupported
Message: Unsupported upstream or login server 'harbor.example.com' provided. Supported upstreams or login servers are: docker.io, mcr.microsoft.com, quay.io, public.ecr.aws, ghcr.io, nvcr.io, registry.k8s.io, gcr.io.
```

**Comment by wy65701436** [comment]
Just have a quick through about https://docs.aws.amazon.com/cli/latest/reference/ecr/create-pull-through-cache-rule.html, it seems that harbor is not an supported as the source for the pull through cache rule.

You should file an feature request on the ACR.
