### ISSUE TITLE
helm 怎么使用http方式推送chart包到harbor仓库，默认使用https方式

### ISSUE THREAD

**Issue by llylhz** [goharbor/harbor#20180]
![image](https://github.com/goharbor/harbor/assets/42568584/7e40b0eb-c6d3-4a7a-b8f6-8f31ab38215b)

**Comment by linpanru** [comment]
先升级helm 客户端 ，再通过--insecure 参数

**Comment by wy65701436** [comment]
it is not a harbor issue, please try the above method, if you still see the problem, then file an issue on the helm repository.

**Comment by llylhz** [comment]
helm v3.11.0，harbor v2.92 ，登录有这个参数，但是推送和拉取没这个参数，没找到方案，最后还是选择了证书，谢谢楼上。
