### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by geet-h17** [goharbor/harbor#20185]
Yes the document does mention that HTTP setup If your installation of Harbor uses HTTP rather than HTTPS, you must add the option --insecure-registry to your client’s Docker daemon. By default, the daemon file is located at /etc/docker/daemon.json.

But there is no /daemon.json in my system. The **/etc/docker** repo is there but it is **empty.**

<img width="1680" alt="Screenshot 2024-03-28 at 7 39 26 PM" src="https://github.com/goharbor/website/assets/78034266/c2e46378-6a9a-4c28-93aa-6edec77e5a26">

Also i have tried multiple solutions i have found here like adding **DOCKER_OPTS="--config-file=/etc/docker/daemon.json"** to 

/default/docker file and all but still i am unable to login to my repo using :

`docker login <ip>`  is giving <ip>::443: connect: connection refused
so tried `docker login <ip>:80` its giving 80: connect: connection refused
tried ` docker login http://<ip>:80` its giving http: server gave HTTP response to HTTPS client

Using **Debian GNU/Linux 11 (bullseye)**
**Docker version 26.0.0, build 2ae903e**

**Comment by wy65701436** [comment]
if you have no issue when setting up harbor with http, then you should file issue on the docker side to clarify on how to connect with an http registry.
