### ISSUE TITLE
Cosign artifacts are not clean by garbage collector

### ISSUE THREAD

**Issue by gaglimax** [goharbor/harbor#20184]
Hi,

I have a replication rule created images from a remote Harbor. Remote images are signed by cosign, so the signature artifact is also replicated : 
![image](https://github.com/goharbor/harbor/assets/32092271/af8b3059-6fa5-4540-b0ac-4b086f2d8a3d)

When the digest of the remote image changes (so the signature as well), it is replicated in local Harbor and the old image became untagged. The Garbage Collector clean the old image because I ticked "Allow garbage collection on untagged artifacts".

In the UI, when the old image is cleaned, I only see the new image with is associated signature.

The problem is if we check in database, the old artifact doesn't exist as expected but the old signature artifact is still present (as an orphaned artifact).

This could result to storage useless utilization.

**Comment by MinerYang** [comment]
Hi @gaglimax ,

What's your source and target harbor version?

**Comment by flbla** [comment]
Hi @MinerYang,
@gaglimax is one of my colleague 

the source version is : v2.9.3-f65d2380
and the target version is : v2.10.0-6abb4eab

it's a "Pull-based" replication

**Comment by MinerYang** [comment]
I can not manually reproduce this issue with same versions .Could provide bellowing info?
 - the specific GC task logs via UI
 - the replication rule and GC schedule settings via UI.
 - check the `artifact_trash` table with old artifact digest
```
psql -d registry
select * from artifact_trash where digest='<old artifact digest>';
select * from artifact_trash where digest='<old signature digest>';

```
