### ISSUE TITLE
Trivy scanner in air-gapped environment

### ISSUE THREAD

**Issue by samratdgreat** [goharbor/harbor#20193]
i have an init and main container inside a pod for trivy. Init container will download the trivy db from s3 and mount it to /home/scanner/.cache/trivy dir
i have realized that everyday /home/scanner/.cache/trivy/db dir is generated automatically and have both metadata.json and trivy.db inside it.
is it creating this db -> /home/scanner/.cache/trivy/db/trivy.db based out of /home/scanner/.cache/trivy/trivy.db?

**Comment by zyyw** [comment]
To use Trivy scanner with Harbor in an air-gapped environment, please refer to this doc:
* https://github.com/goharbor/harbor/wiki/Harbor-FAQs#trivy-in-air-gapped-environment
Please also set `skip_java_db_update` to `true`, if your harbor version >= 2.10.1 (or >= v2.9.3)
