### ISSUE TITLE
Harbor Can not connect to external sentinel redis 

### ISSUE THREAD

**Issue by SoaadMahmoud** [goharbor/harbor#20191]
I got the below error in core.log when configuring harbor to use external redis setinel i am not sure why it resolving mymaster to localhost ip
Note that redis is installed in seperate vms but in the same subnet of harbor vm 
What is this value should be for sentinel_master_set ?

**core[9214]: redis: 2024/03/29 13:00:47 sentinel.go:661: sentinel: new master="mymaster" addr="127.0.0.1:6379"
Mar 29 13:00:47l core[9214]: 2024-03-29T13:00:47Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis+sentinel://:xxxxx@10.2.7.100:26379,10.2.7.101:26379,10.2.7.102:26379/mymaster?idle_timeout_seconds=30, retry after 500ms : dial tcp 127.0.0.1:6379: connect: connection refused
Here is the config in harbor.yml**

external_redis:
    host: 10.2.7.100:26379,10.2.7.101:26379,10.2.7.102:26379
    sentinel_master_set: mymaster 
    password: password
    registry_db_index: 1
    jobservice_db_index: 2
    chartmuseum_db_index: 3
    trivy_db_index: 5
    idle_timeout_seconds: 30

**Comment by MinerYang** [comment]
It is about your sentinel conf, which ip address mapping to `mymaster` is not set properly.

**Comment by wy65701436** [comment]
@SoaadMahmoud please follow the above comments to revise your settings, and reopen if it is still existing.
