### ISSUE TITLE
`cannot redirect to other site` with OIDC login and empty `redirect_url` parameter

### ISSUE THREAD

**Issue by pborn-ionos** [goharbor/harbor#20226]
PR #20025 broke Harbor for us.

We have OIDC enabled and the user is on `/account/sign-in`, the login button for OIDC points to `/c/oidc/login?redirect_url=` and an empty `redirect_url` errors out with

```json
{
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "cannot redirect to other site"
    }
  ]
}
```

**Comment by Vad1mo** [comment]
Ok, do I understand you correctly that you want that `redirect_url=""` is supported?

**Comment by stonezdj** [comment]
Because the default value for redirect_url is `/harbor/projects/`when click the OIDC login button, How did you set the redirect_url to empty string?
![Screenshot 2024-04-08 at 12 35 14](https://github.com/goharbor/harbor/assets/2696760/7aa18ccd-62ea-426e-8a51-a90a981922c8)
