### ISSUE TITLE
Change location for internal storage

### ISSUE THREAD

**Issue by AlexZeitler** [goharbor/harbor#2023]
Docs say 
```
By default, registry data is persisted in the target host's /data/ directory. 
This data remains unchanged even when Harbor's containers are removed and/or recreated.
```
How/where can I change that location?

**Comment by reasonerjt** [comment]
@AlexZeitler To change the default data volume you need to make update the "volumes" of different containers io docker-compose.yml before deploying Harbor.

**Comment by davidmaitland** [comment]
If anyone else is looking for this, you also need to change `DATA_VOL` in the `./prepare` script.

**Comment by jelovac** [comment]
IMHO this should be added to harbor.cfg so we can choose different location and not hack the prepare script.
