### ISSUE TITLE
Add search in the tags for docker image

### ISSUE THREAD

**Issue by hugosxm** [goharbor/harbor#20233]
**Is your feature request related to a problem? Please describe.**

Hi, when I use the search feature in a project containing docker images, I can filter by labels, type, and tagged or not image. But I can not really search for a specific tag.

**Describe the solution you'd like**

I would like to be able to actually search for a tag, like typing "dev-1" and it would output all images tagged with a tag containing "dev-1" like  :

dev-1.0.0
dev-1
dev-1.1.1

etc...

**Comment by wy65701436** [comment]
@hugosxm I can search with tag, see the screenshot.

![image](https://github.com/goharbor/harbor/assets/2841473/897ab54b-4cea-4c16-bca2-eb83a9935513)

**Comment by hugosxm** [comment]
@wy65701436 I'm sorry, I changed browser and it worked, I went back to brave and cleared all cache, now I am able to type in the search form ! Sorry for the inconvenience...
