### ISSUE TITLE
invalid image reference format in Logs Portal

### ISSUE THREAD

**Issue by networkhermit** [goharbor/harbor#20230]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

In the Logs tab of Harbor UI, I found that some image references in the Resource column are invalid:

```console
❯ sudo k3s crictl pull ghcr.io/fluxcd/source-controller:sha256:b3012918b3da04aee9ebd6cc5c297eff41b26161b7bd06b3910b7ccff6d8b9e1
E0404 22:22:07.111820   37628 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to parse image r
eference \"ghcr.io/fluxcd/source-controller:sha256:b3012918b3da04aee9ebd6cc5c297eff41b26161b7bd06b3910b7ccff6d8b9e1\": invalid reference format" image
="ghcr.io/fluxcd/source-controller:sha256:b3012918b3da04aee9ebd6cc5c297eff41b26161b7bd06b3910b7ccff6d8b9e1"
FATA[0000] pulling image: failed to parse image reference "ghcr.io/fluxcd/source-controller:sha256:b3012918b3da04aee9ebd6cc5c297eff41b26161b7bd06b3910
b7ccff6d8b9e1": invalid reference format
```

The correct format is `@sha256` instead of `:sha256`:
```console
❯ sudo k3s crictl pull ghcr.io/fluxcd/source-controller@sha256:b3012918b3da04aee9ebd6cc5c297eff41b26161b7bd06b3910b7ccff6d8b9e1
Image is up to date for sha256:82045e6750545003bc94ed4affab3f9f9c47aa162a93fb9f6b0711b9cc37986a
```

**Steps to reproduce the problem:**

1. In Harbor UI, choose some image to pull and `COPY PULL COMMAND` (it should be in the `*@sha256sum:*` form)
2. Running the pull command in your terminal
3. Wait for the access logs appears in Harbor Logs
4. Verify the image reference in Resource column is `*:sha256sum:*` form, which is invalid

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.10.1-b7b88476
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
hi, I cannot reproduce your problem, can you try with the demo.goharbor.io. I've validated your scenario, the digest format is  correct(*@sha256sum:*).

**Comment by networkhermit** [comment]
> hi, I cannot reproduce your problem, can you try with the demo.goharbor.io. I've validated your scenario, the digest format is correct(_@sha256sum:_).

I just tried demo.goharbor.io, the image reference `dockerhub/library/busybox:sha256:4be429a5fbb2e71ae7958bfa558bc637cf3a61baf40a708cb8fff532b39e52d0` is invalid.

<img width="1127" alt="image" src="https://github.com/goharbor/harbor/assets/13472805/86fa51a6-e571-478e-8d48-f4f71b0d48bb">

**Comment by zyyw** [comment]
Reproduced this issue in Harbor v2.10.1, it may have something to do with this code snippet - line191:
https://github.com/goharbor/harbor/blob/b7b884760ae72ea246b6fdc23f2a8fd5c68610ef/src/controller/event/topic.go#L182-L206
