### ISSUE TITLE
Tag RC-versions with pre-release

### ISSUE THREAD

**Issue by SebastianThorn** [goharbor/harbor#20248]
This would make the notifications that GitHub sends better.

![image](https://github.com/goharbor/harbor/assets/409816/bb9ace52-3d42-496a-b775-eb733326e053)

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/release-it/release-it/blob/main/docs/pre-releases.md

**Comment by zyyw** [comment]
Thanks for this. updated the release.
