### ISSUE TITLE
Harbor UI fails to render readme & values for charts in OCI

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#20265]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
This is the same issue that was reported in https://github.com/goharbor/harbor/issues/16387 which we still encounter, and based on recent reports in that issue, we're not the only ones.

When accessing a Helm chart sored in OCI the README & Values won't render and we see a `Unknown errors have occurred. Please try again later.` error.

This is affecting a large percentage of the charts, but not all of them, they are all pushed using Helm v3.11.1 CLI and then signed with cosign.

Pull the chart works fine.

**Steps to reproduce the problem:**
Repro steps can be found here: https://github.com/goharbor/harbor/issues/16387#issuecomment-2036482522

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7.1
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

```
harbor-core-7bb45668c-gmd4h core 2024-04-11T14:49:49Z [ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: gzip: invalid header"}]}
```

**Comment by mcoreix** [comment]
[#20252](https://github.com/goharbor/harbor/issues/20252)

**Comment by zyyw** [comment]
dup of https://github.com/goharbor/harbor/issues/20252. Let's track it there. Closing this issue now.
