### ISSUE TITLE
After upgrade v2.10.0, No default scanner

### ISSUE THREAD

**Issue by tsukiazuma** [goharbor/harbor#20284]
On old version harbor, I deploy with scanner Trivy
But after upgrade, I check again and not found default scanner in Interrogation Services
How can I do to add Trivy scanner?

**Comment by wy65701436** [comment]
how did you install harbor, as well as upgrade?

**Comment by zyyw** [comment]
@tsukiazuma if you installed harbor in docker-compose way, please try to follow this doc to upgrade your Harbor service:
* https://goharbor.io/docs/2.10.0/administration/upgrade/

Please also be noted that upgrading your Harbor service within `n-2` version.

**Comment by tsukiazuma** [comment]
Yeah, I follow it - https://goharbor.io/docs/2.10.0/administration/upgrade/ to upgrade

**Comment by tsukiazuma** [comment]
> how did you install harbor, as well as upgrade?

I install harbor with: `./install.sh --with-trivy` in old version.
And upgrade with: `./install.sh`

**Comment by zyyw** [comment]
> > how did you install harbor, as well as upgrade?
> 
> I install harbor with: `./install.sh --with-trivy` in old version. And upgrade with: `./install.sh`

In this doc: https://goharbor.io/docs/2.10.0/administration/upgrade/, at step 7, you will need to run `./install.sh --with-trivy` to have the default scanner enabled after upgrading.
