### ISSUE TITLE
Does harbor support using external postgres DB version 16 ?

### ISSUE THREAD

**Issue by SoaadMahmoud** [goharbor/harbor#20296]
Does harbor support using external postgres DB version 16 ?

**Comment by wy65701436** [comment]
we haven't tested that yet.

**Comment by zyyw** [comment]
@SoaadMahmoud the latest tested PG in a released Harbor version is PG 14:
* https://github.com/goharbor/harbor/blob/release-2.10.0/make/photon/db/Dockerfile

while in Harbor main branch the latest PG version we have is PG 15.

Please try to use PG 14 or PG 15 as PG 16 is not tested yet.

**Comment by XiaooHu2002** [comment]
https://github.com/goharbor/harbor/issues/20355
16的应该可以用，因为我按照harbor的时候，harbor是能连接外部 postgres DB ，但是就是我遇到的问题就是，第一次安装，在harbor登入页面我用admin登入账号显示我密码错误。不明白为啥。
