### ISSUE TITLE
After delete SBOM accessory, SBOM details tab still clickable with Unknown error

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#20319]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
After delete SBOM accessory dependently, the SBOM details should grey out or without errors

**Steps to reproduce the problem:**
step1 push image with auto generate SBOM config
step2 delete SBOM accessory manually
step3 click SBOM details, it still view-able but with bellowing error.

<img width="2024" alt="Screenshot 2024-04-23 at 13 22 06" src="https://github.com/goharbor/harbor/assets/44956229/f954287c-db62-4f8d-a73f-1a13a0293167">

- harbor version: v2.11.0-b7d4bf0d

**Additional context:**
```
GET | https://xxx.xxxx.xx.xx/api/v2.0/projects/library/repositories/harbor-db/artifacts/sha256:1e9b0faa3ccbfffc6f6ea8abcabf29c7259f566a0e4e964db09eaefdf06c9865/additions/sbom
Status
404
Not Found

```

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by xuelichao** [comment]
As design stage, we have discussed and make a agreement that the digest in the sbom_overview will be deleted after the accessory  got deleted. However, out test result shows that the the digest in the sbom_overview is still there. 

<img width="1661" alt="Screenshot 2024-04-25 at 16 09 26" src="https://github.com/goharbor/harbor/assets/68891670/8f5b4b83-4f16-4ad1-bf49-b5e1f4541833">

@stonezdj Could you recheck the codes to fix it?

**Comment by stonezdj** [comment]
I will fix this issue, BTW. UI should handle the 404 error instead of Unknown Error
