### ISSUE TITLE
The SBOM details has something that doesn't make sense.

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20324]
reproduce steps:
1. select the checkbox of library project to "Automatically generate SBOM on push"
2. docker push <harbor-endpoint>/library/alpine:3.15.5
3. there will be an SBOM generated, but the SBOM details have something that doesn't make sense.

<img width="1273" alt="Screenshot 2024-04-23 at 1 54 34 PM" src="https://github.com/goharbor/harbor/assets/6709992/d53c256e-657d-4309-a778-a96c44857555">

**Comment by stonezdj** [comment]
It is the scanner generate the output. other scanner keep the image layer information in the SBOM

**Comment by wy65701436** [comment]
The first package was returned by the scanner, mark this issue as by designed.
