### ISSUE TITLE
replicating an image with built-in SBOM attached to another Harbor project with SBOM auto-gen configured results to two SBOMs

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20329]
Reproduce steps:
1. enable SBOM auto-gen config in Harbor1 library project
2. push image1 to Harbor1 library project. Image is uploaded successfully and SBOM1 is auto generated successfully
3. enable SBOM auto-gen config in Harbor2 library project
4. configure a push-based replication rule from harbor1 library/image1 to harbor2 
5. replications completed successfully. BUT there are two SBOMs associated with library/image1 in harbor2. Is the by design? How to scan SBOM for vulnerabilities in the future?
<img width="1520" alt="Screenshot 2024-04-23 at 3 09 06 PM" src="https://github.com/goharbor/harbor/assets/6709992/a414eb0e-7fba-4fb1-90a2-c22e40891b7a">

**Comment by stonezdj** [comment]
Work as designed
