### ISSUE TITLE
Stop `GENERATE SBOM` stuck at `Queued`

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20333]
When trying to test `STOP` manually generating SBOM, the Harbor portal stuck at `Queued` and cannot STOP it. I have to use jobservice dashboard to free this SBOM generation worker.
<img width="1765" alt="Screenshot 2024-04-23 at 4 16 50 PM" src="https://github.com/goharbor/harbor/assets/6709992/02ebd90c-8a60-4b4e-9edd-2b0d1b0e4a53">

when I refresh the webpage, and try to re-generate SBOM manually or STOP SBOM generation, it display something like this:
<img width="1761" alt="Screenshot 2024-04-23 at 4 24 11 PM" src="https://github.com/goharbor/harbor/assets/6709992/0762a21b-198f-4a82-a66a-76eccab8f1f7">

STOP scan for vulnerability works fine though:
<img width="1756" alt="Screenshot 2024-04-23 at 4 26 47 PM" src="https://github.com/goharbor/harbor/assets/6709992/2aba76e0-17b7-4472-8c96-1f42958115e0">

**Comment by stonezdj** [comment]
With the pr https://github.com/goharbor/harbor/pull/20358 merged, it could display the scan_status
