### ISSUE TITLE
Unable to trigger stop sbom 

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#20330]
Click the generate SBOM, but even the status shows as queued, I still cannot click the stop sbom button

![image](https://github.com/goharbor/harbor/assets/2841473/fabe9f72-e17a-46f3-8338-5aee8a45eac4)

**Comment by xuelichao** [comment]
the job is actually not started when it is in queued status. At least for vulnerability, it is not allowed to trigger stop.
