### ISSUE TITLE
Metric harbor_artifact_pulled should be Counter type, not Gauge

### ISSUE THREAD

**Issue by Gypsying** [goharbor/harbor#20334]
- harbor version: [2.5.3]

**Comment by phin1x** [comment]
the definition of a counter (from https://prometheus.io/docs/concepts/metric_types/#counter):
A counter is a cumulative metric that represents a single [monotonically increasing counter](https://en.wikipedia.org/wiki/Monotonic_function) whose value can only increase or be reset to zero on restart. For example, you can use a counter to represent the number of requests served, tasks completed, or errors.

the pulled values never goes down (why should it), so counter is the correct type. mabye you missing the rate or irate function.

**Comment by Gypsying** [comment]
> the definition of a counter (from https://prometheus.io/docs/concepts/metric_types/#counter): A counter is a cumulative metric that represents a single [monotonically increasing counter](https://en.wikipedia.org/wiki/Monotonic_function) whose value can only increase or be reset to zero on restart. For example, you can use a counter to represent the number of requests served, tasks completed, or errors.
> 
> the pulled values never goes down (why should it), so counter is the correct type. mabye you missing the rate or irate function.

Of course, harbor_artifact_pulled should be counter type, 
but the metric harbor exposed is **Gauge**, [code definition](https://github.com/goharbor/harbor/blob/2af02f3b256de2825887f03d9d82e966019bc315/src/pkg/exporter/project_collector.go#L77)

**Comment by chlins** [comment]
You may notice that the `harbor_artifact_pulled` is a metric crawled by the harbor exporter component, so the value is fetched from the database query, and the `Counter` type we should call the `Inc()` method if the artifact to be pulled each time, here the scenario is not that case, as the value in fact is a momentary value queried from database, so here this type we used the `Guage` type.
