### ISSUE TITLE
It needs to show the sbom link for the replicated artifacts which has the accessory of sbom

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#20335]
![image](https://github.com/goharbor/harbor/assets/2841473/19bf196c-607b-408f-a7e3-9653b6066501)

**Comment by xuelichao** [comment]
Currently, UI display 'not generated' when sbom_overview or sbom_overview.scan_status is missing(or not return from backend)
It seems for some reasons, the sbom_overview or sbom_overview.scan_status is deleted from artifact object?

Backend should figure out when the sbom_overview and bom_overview.scan_status got deleted.

Here the new check steps from UI side:
   UI try to find digest from sbom_overview and accessory:
       1. found, show 'SBOM Detail'
       2. Not found, show 'Not generated'
