### ISSUE TITLE
The image reference is invalid when pushing image

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#20336]
After pushing image to Harbor repository, the image digest is still invalid
![Screenshot 2024-04-23 at 16 54 54](https://github.com/goharbor/harbor/assets/2696760/b90863e8-76b5-45b8-9ecf-69250315b3f0)

**Comment by zyyw** [comment]
This should be fixed by this PR:
* https://github.com/goharbor/harbor/pull/20348
