### ISSUE TITLE
why it generates a separate record when signing with notation as the below image?

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20345]
How can we help you?
<img width="1499" alt="Screenshot 2024-04-23 at 6 17 06 PM" src="https://github.com/goharbor/harbor/assets/6709992/cfa6d88a-501d-4797-a3d5-57a5be637177">

**Comment by MinerYang** [comment]
It is notation v1.1.0 current behavior. We will discuss with them

**Comment by wy65701436** [comment]
It is not a harbor issue, we will discuss this with notation team to know more details in the cycle of v2.12.
