### ISSUE TITLE
got 401 when issues a generate SBOM request with a system level robot account

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#20343]
POST https://10.206.88.128/api/v2.0/projects/redis/repositories/haproxy/artifacts/sha256:82df32a691e11f467c83c2576670498c733907a6cd6722151a77c6580c735dd4/scan 

{
    "scan_type":"sbom"
}

{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "unauthorized"
        }
    ]
}

![image](https://github.com/goharbor/harbor/assets/2841473/fb458471-90f1-4c5e-aa82-305eb76447f8)

**Comment by stonezdj** [comment]
cannot reproduced
