### ISSUE TITLE
Should this be `Unsupported` either for SBOM?

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20346]
How can we help you?
<img width="1773" alt="Screenshot 2024-04-23 at 6 23 48 PM" src="https://github.com/goharbor/harbor/assets/6709992/d0ef2eea-f3e3-4d90-b2ac-caf0edf7fbbb">

**Comment by xuelichao** [comment]
The identify status is different due to the SBOM implementation is not same as Vulnerability.
1. Vulnerability:
    Display 'Not supported' when artifact.addition_links[ADDITIONS.VULNERABILITIES] is not found
    This implementation is there before i touch the codes, i do not modify the logic for vulnerability.
    
2. SBOM: There is addition_links for SBOM.(confirmed with Stone before last GA)
    Display 'Not supported' when project.scanner.capabilities.support_sbom is false
    
    Leave your Comments once there is any updates on this.
