### ISSUE TITLE
intermittent slow download for some layer of docker image

### ISSUE THREAD

**Issue by anantsaraswat** [goharbor/harbor#20357]
Our harbor setup has been running fine for the last few years, now from last week we have been facing an issue where the download of some docker layers is very very slow, and the docker pull is taking 30-40 minutes compared to 50-55 seconds. I tried to check system logs and found nothing, I have restarted the server without any luck, Can you please guide me on how can I find the bottleneck here, and if there is any tuning guide for the same?

Harbor Version v2.3.2-6b6c21da  ( running using the docker-compose )

**Comment by wy65701436** [comment]
since harbor v2.3.2 is out of supporting, please upgrade your harbor to v2.9+  and reopen it if you still encounter this issue.
