### ISSUE TITLE
project robot account permission should be "Sbom" or "SBOM", instead of "sbom". Same for system robot account

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20351]
How can we help you?
![Screenshot 2024-04-24 at 7 20 59 PM](https://github.com/goharbor/harbor/assets/6709992/3bf622dd-e121-480b-a9e2-a82c9e686efa)

**Comment by stonezdj** [comment]
It will call the api /api/v2.0/permissions to get all permission
```
        {
            "action": "create",
            "resource": "sbom"
        },
        {
            "action": "stop",
            "resource": "sbom"
        },
        {
            "action": "read",
            "resource": "sbom"
        }
```

After upperca
![Screenshot 2024-04-25 at 16 18 02](https://github.com/goharbor/harbor/assets/2696760/136ee5fa-5aaf-461c-8e83-153b790e17c8)
se the SBOM, it seems that the UI can't handle it correctly.
