### ISSUE TITLE
删除复制规则报错

### ISSUE THREAD

**Issue by gzwxh** [goharbor/harbor#20371]
由于之前配置问题，导致每次同步都异常，当手动删除复制任务之后，再次删除复制规则就报错了
contains executions that aren't in final status, stop the execution first
![图片](https://github.com/goharbor/harbor/assets/38306098/8ba8a355-aadf-46dd-ba73-c0eeb9b61f6a)

**Comment by chlins** [comment]
Do you have any pending or running executions under this replication policy?

**Comment by wy65701436** [comment]
What version of harbor are you using?

**Comment by gzwxh** [comment]
里面没有任何再执行的任务，目前已经升级到harbor.v2.10.2.tar.gz
