### ISSUE TITLE
GС schedule causes errors

### ISSUE THREAD

**Issue by sivsoft** [goharbor/harbor#20384]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I have a schedule set up to clean up Garbage Collection. However, it is not working. I can manually execute "GC Now" with no problem. But the automatic schedule causes errors.

![sy-harbor_jobservice_GC_error_001](https://github.com/goharbor/harbor/assets/106741284/7c244a11-310c-49f8-ae1a-c6d8d9ddca67)

**Here is the error in the jobservice.log**
May 1 03:00:01 172.26.0.1 jobservice[931]: 2024-05-01-01T00:00:01Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'GARBAGE_COLLECTION:0d2d09b7da4adcf767d0dee8' exit with error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 51 [running]:

Harbor was updated sequentially from 2.3.1 to 2.4.0, then to 2.6.0 and finally to 2.8.3, this is not a new install.

**Versions:**
- harbor version: [2.8.3]
- docker engine version: [24.0.5, build ced0996]
- docker-compose version: [2.19.1]

**Comment by MinerYang** [comment]
Hi @sivsoft ,

Are you using internal or external Redis ?
Could you give us more contexts if your jobservice logs?

ref: https://github.com/goharbor/harbor/issues/15850
