### ISSUE TITLE
Is there a way to synchronize images in Harbor and the Upstream registry AWS ECR.

### ISSUE THREAD

**Issue by Leela-SR** [goharbor/harbor#20381]
We plan to have a Harbor local container registry in our Onprem Cluster. The local container registry will be populated from AWS ECR through Replication. We would like to know that any synchronization option is avaialble to populate the local container registry with the latest images in ECR.

**Comment by MinerYang** [comment]
You could do replications in the Harbor as well.
- using pull-base mode when pulling image from remote registry(ECR)
- using push-base mode when pushing image to remote registry(ECR)

ref: https://goharbor.io/docs/2.10.0/administration/configuring-replication/create-replication-rules/

**Comment by Leela-SR** [comment]
Thanks MinerYang
