### ISSUE TITLE
Can the official document provide a simplified and complete compose.yaml file?

### ISSUE THREAD

**Issue by wang3develop** [goharbor/harbor#20380]
The install.sh file only supports Docker Compose to install Harbor！

What I installed here is podman-compose。However, the script restricts aliases!

**Comment by MinerYang** [comment]
Hi @wang3develop ,

- docker compose file would be rendered base on your config when execute `./prepare` or `./install.sh`. No need to provided it yourself
- We do not support podman compose officially, so there might be limitations when you use it. Will appreciate if your having any experience to share with us

Best,
Miner

**Comment by zodiac182** [comment]
I tried with podman and podman-compose, seems it works.
Procedure:
1. install podman and podman-compose.
2. modify `prepare` file, add following lines.
```
    sed -i 's/driver: "syslog"/driver: "journald"/g' docker-compose.yml
    sed -i '/syslog-address: "tcp:\/\/localhost:1514"/d' docker-compose.yml
```
3. modify `install.sh`
```diff
    - DOCKER_COMPOSE=docker-compose
    + DOCKER_COMPOSE="podman compose"

    # if you do not want to skip this step, 
    # you could modify those functions in common file
    - check_docker
    + # check_docker
    - check_dockercompose
    + # check_dockercompose
```
4. do ```bash install.sh --with-trivy```

However, this solution has a drawback. Podman does not support logging-driver=syslog, so I use journald in this case.     
The log configuration for each pod would be changed. And logs could not be delivered to `harbor-log` any more.
Additionally, seems that it may also have some impact on harbor-jobservice. 
@MinerYang
