### ISSUE TITLE
Harbor does not differentiate tags between images and OCI Charts within same repository

### ISSUE THREAD

**Issue by PoudNL** [goharbor/harbor#20383]
**Expected behavior and actual behavior:**
When we push an OCI helm chart with (for example) version v5.2.1 to a repository that already contains an docker image with tag v5.2.1, the tag is removed from the docker image and applied to the OCI helm chart.
It also happens vice versa, when you already have an OCI Helm chart and push a docker image with the same version, the tag is removed from the Helm Chart.

What I expect is that Harbor differentiates between an OCI Helm chart and a Docker image when it comes to tagging. Now it is not possible to have the helm chart and the docker image in the same repository withing Harbor.

**Steps to reproduce the problem:**
- Push a docker image to a project with (for example) tag v1.0
- Check if the image has the tag within the project
- Push a Helm chart (OCI) that has the same name as the image and version defined in the Chart.yaml
- Check in harbor the tags of both objects and you will see that the tag is removed from docker image and placed on helm chart

**Versions:**
- harbor version: v2.10.0-6abb4eab
- docker engine version: 20.10.23 (docker desktop)
- helm version: v3.13.2

**Comment by MinerYang** [comment]
It is all fundamentally stored as artifact in the db since it's all OCI-compatible products. We prefer you use  tags to do the differentiation.

**Comment by PoudNL** [comment]
The problem is that I cannot do any differentiation because the charts ánd images are sharing the same tag and they are not owned / build by me. Those are charts that are from online repositories and are saved in a local harbor environment. So I am not in control of the tags that come along as long. Do I do not find this issue closed/completed.

**Comment by wy65701436** [comment]
Hi @PoudNL, I understand your concern. 

However, in the registry, the combination of repository and tag serves as the unique identifier for any individual OCI artifact. You cannot share the same tag between different types of artifacts, such as charts and images.

This structure is fundamental in the OCI registry, and I believe others follow the same principle, as mentioned in the [ECR documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-using-tags.html): "For each repository, each tag key must be unique, and each tag key can have only one value."

I suggest using different projects or tags to distinguish them in Harbor

**Comment by PoudNL** [comment]
I am not very familiar with any other registries and did not test it in others. But now we have to workaround this issue by creating different projects for charts and images since Chartmuseum is deprecated.

**Comment by paullaffitte** [comment]
Hi @PoudNL!
 
This is not something related to harbor but rather related to the OCI distribution specification. As stated in this specification: 

> To pull a manifest, perform a GET request to a URL in the following form: /v2/\<name\>/manifests/\<reference\>
> https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests

There is no mention of the type of the artifact in this url, only the name and the reference. Thus it is not possible to implement this feature while staying OCI-compliant. I suggest that you open an issue on the [opencontainers/distribution-spec](https://github.com/opencontainers/distribution-spec) repository.
