### ISSUE TITLE
Setting up google OIDC

### ISSUE THREAD

**Issue by aqeelat** [goharbor/harbor#20389]
I'm using a managed harbor 2.6.4 instance provided by ovh

I'm trying to setup OIDC with google cloud, but harbor is giving me trouble.

I followed the first part here: https://docs.openshift.com/acs/3.66/operating/manage-user-access/configure-google-workspace-identity.html and I got this config from google:
```json
{
  "web": {
    "client_id": "xxxx-xxxxx.apps.googleusercontent.com",
    "project_id": "xxxx",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "xxxx",
    "redirect_uris": [
      "https://[path-to-registry].container-registry.ovh.net/"
    ]
  }
}
```
and I followed https://help.ovhcloud.com/csm/en-public-cloud-private-registry-configure-oidc-provider-authentication?id=kb_article_view&sysparm_article=KB0059373

and I used this harbor config:
```json
{
  "deleteUsers": false,
  "provider": {
    "clientId": "xxxx-xxxxx.apps.googleusercontent.com",
    "clientSecret": "xxxx",
    "endpoint": "https://accounts.google.com/o/oauth2/auth",
    "name": "google",
    "scope": "openid,profile,email,offline_access",
    "verifyCert": true
  }
}
```
However, I'm getting this message:
```json
{
  "class": "Client::BadRequest",
  "message": "Invalid parameter(s): endpoint and/or verifyCert"
}
```

I tried using `"verifyCert": false` and I tried removing it. I also tried all three urls in the google json config, but nothing worked.

Questions:
1. what should I do?
2. is my redirect uri correct? I couldn't find any reference on what it might be.

**Comment by MinerYang** [comment]
Hi @aqeelat ,

Could you try to refer this doc https://goharbor.io/docs/2.10/administration/configure-authentication/oidc-auth/ OR by calling the correct API via dev center API test https://goharbor.io/docs/2.10.0/working-with-projects/using-api-explorer/

**Comment by Vad1mo** [comment]
here is also a step by step guide for google and harbor 
https://container-registry.com/docs/user-guide/oidc-configuration-for-google-workspaces/

**Comment by aqeelat** [comment]
Update: I fixed it by using `https://accounts.google.com` as the endpoint.
Thank you @Vad1mo. The tutorial really helped.
