### ISSUE TITLE
How to disable OIDC authentication for Harbor

### ISSUE THREAD

**Issue by smallemployees** [goharbor/harbor#20391]
How can we help you?
I disabled the authentication of OIDC, but found that there is still a lot of data in the database tables that has not been cleaned up

Will uncleaned data and environmental variables affect the normal use of authentication

**Comment by MinerYang** [comment]
Please clean up the users in the user table then you could switch to other auth mode.
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
