### ISSUE TITLE
Timeout when getting metadata from Trivy endpoint in Core.

### ISSUE THREAD

**Issue by shrinedogg** [goharbor/harbor#20406]
We are experiencing an error when attempting to access the scanner in Harbor using the [BigBang helmchart.](https://docs-bigbang.dso.mil/latest/packages/harbor/)

After a brief ~10-15 second load at our URL of `harbor/projects/1/scanner`, the Trivy scanner endpoint shows Unhealthy, although the container appears to be working/healthy otherwise.

![image](https://github.com/goharbor/harbor/assets/53411346/612fa8ec-ebd9-4cea-b25f-67bbf8955bba)

When attempting, the logging process for Core captures the following error relating to Trivy:

`[ERROR] [/controller/scanner/base_controller.go:299][error="v1 client: get metadata: Get "http://harbor-harbor-trivy:8080/api/v1/metadata": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" requestID="5e861cfc-348f-966a-9e38-675f932328a0"]: failed to ping scanner`

The containers are hosted in a kubernetes cluster, so we attempted to curl the same Trivy endpoint directly from within the Core pod, which also appears to work just fine.

```
 curl -vvv http://harbor-harbor-trivy:8080/api/v1/metadata
* Uses proxy env variable NO_PROXY == 'harbor-harbor-core,harbor-harbor-jobservice,harbor-harbor-database,harbor-harbor-registry,harbor-harbor-portal,harbor-harbor-trivy,harbor-harbor-exporter,127.0.0.1,localhost,.local,.internal'
*   Trying {PODIP}:8080...
* Connected to harbor-harbor-trivy ({PODIP}) port 8080 (#0)
> GET /api/v1/metadata HTTP/1.1
> Host: harbor-harbor-trivy:8080
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/vnd.scanner.adapter.metadata+json; version=1.0
< Date: Wed, 08 May 2024 14:13:58 GMT
< Content-Length: 952
<
{"scanner":{"name":"Trivy","vendor":"Aqua Security","version":"Unknown"},"capabilities":[{"consumes_mime_types":["application/vnd.oci.image.manifest.v1+json","application/vnd.docker.distribution.manifest.v2+json"],"produces_mime_types":["application/vnd.security.vulnerability.report; version=1.1"]}],"properties":{"env.SCANNER_TRIVY_DEBUG_MODE":"false","env.SCANNER_TRIVY_IGNORE_UNFIXED":"false","env.SCANNER_TRIVY_INSECURE":"false","env.SCANNER_TRIVY_OFFLINE_SCAN":"false","env.SCANNER_TRIVY_SECURITY_CHECKS":"vuln","env.SCANNER_TRIVY_SEVERITY":"UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL","env.SCANNER_TRIVY_SKIP_UPDATE":"false","env.SCANNER_TRIVY_TIMEOUT":"5m0s","env.SCANNER_TRIVY_VULN_TYPE":"os,library","harbor.scanner-adapter/scanner-type":"os-package-vulnerability","org.label-schema.build-date":"unknown","org.label-schema.vcs":"https://github.com/aquasecurity/harbor-scanner-trivy","org.label-schema.vcs-ref":"none","org.label-schema.version":"dev"}}
* Connection #0 to host harbor-harbor-trivy left intact
```

I can't seem to find a way to adjust this timeout; is there a way to bypass this issue?

**Comment by wy65701436** [comment]
Hi, please try using the harbor official chart, we do not support any third-party harbor charts.
