### ISSUE TITLE
Create 0B csv File when using the Export

### ISSUE THREAD

**Issue by seanlee0923** [goharbor/harbor#20402]
Hello.
I wrote an issue because I had a problem while trying to use Harbour.

I'm currently using Haber 2.6.0 version on Ubuntu 22.04.
![스크린샷 2024-05-08 10-32-14](https://github.com/goharbor/harbor/assets/98005271/e0b6f06c-a4c9-4dcb-8e5c-aa8047ec4592)

I would like to change the server that I used to use Harbor to a new server computer and move the existing image to a new server.

Servers that will run new Harbour will also use Ubuntu 22.04 version and update Harbour's version to 2.8.6.
If you select one of the project check boxes and use the Export feature, only csv files of 0B are created.

![image](https://github.com/goharbor/harbor/assets/98005271/ed060fcb-26d7-4a51-9c94-82c6c8916439)

May I know the reason??

I have about 120GB of images, should I pull them one by one and push them to a new server?

**Comment by wy65701436** [comment]
did you perform the CVE scanning before export the data?

**Comment by seanlee0923** [comment]
The export function is a function of exporting as a CVE file, not an image file.
I'll have to find out about the cloning of artifacts. Thanks to you, it's been helpful
