### ISSUE TITLE
docker-compose: not all containers start after a server reboot.

### ISSUE THREAD

**Issue by SterhLight** [goharbor/harbor#20419]
**Expected behavior:**  
All containers launched via Docker-compos start after the server is rebooted.
**Actual behavior:**  
Some containers launched via Docker-compos do not start after a server reboot.

![03](https://github.com/goharbor/harbor/assets/122260062/d779fd18-9097-4468-a8d8-842f46a00ae9)

**Steps to reproduce the problem:**  
1) Install Harbor via docker-compose
2) Reboot the server

**Versions of the following systems.**  
- harbor version: [2.10.0]
- docker engine version: [24.0.7]
- docker-compose version: [2.21.0]

**Comment by MinerYang** [comment]
Hi @SterhLight ,

Please refer to https://github.com/goharbor/harbor/issues/18704#issuecomment-1556764459
