### ISSUE TITLE
Docker-compose: access to the Harbor via two URLs

### ISSUE THREAD

**Issue by SterhLight** [goharbor/harbor#20420]
Is it possible in the harbor.yml file to assign a harbor to 2 hostnames at once, so that you can access the harbor using these different links?
And if not, are there any plans to add this functionality? It is required to reserve access to the service.

**Comment by wy65701436** [comment]
No, we do not have the plan for this. But, you might can leverage K8s to simulate it. Which kind of scenario that requires two hostnames for one harbor instance?

**Comment by SterhLight** [comment]
> Which kind of scenario that requires two hostnames for one harbor instance?

it's simple. We have two servers, the first is the main one, the second is the backup one. The backup server is replicated with the main one. When the main one breaks down, we will assign its DNS name to the IP address of the backup server. For this you need two URLs. One is replicated, and the second matches the URL of the main server. I really hope I was able to explain it clearly.
