### ISSUE TITLE
I can't see configuration for auto_gen_sbom to enable auto generate SBOM on image push #20060

### ISSUE THREAD

**Issue by grandeon** [goharbor/harbor#20428]
How can we help you?

Related with issue #20060 and with its resolution in #20069, I can't see the configuration option in Harbor: 

![image](https://github.com/goharbor/harbor/assets/25952673/8a35c049-2af2-4d70-82bf-4e6708789b7d)

I understand that I would have to see an option that says:
**"Automatically generate SBOM on push"**

I'm running the helm deploy option with chart version 1.14.2 and app version 2.10.2

What is the mistake I have made?

Thank you very much for your help

**Comment by DevSecOps-Isotrol** [comment]
Is there any documentation that explains how to enable it or what depends on whether or not it appears in the graphical interface?

I recently attended this event, but it is not clear to me if I need to use another scanner or how to achieve this functionality:

[Leveraging OCI 1.1 for Enhanced SBOM Integration and Vulnerability Scanning in Harbor](https://www.youtube.com/watch?v=ABbds5-zSqk)

**Comment by grandeon** [comment]
Is there any documentation that explains how to enable it or what depends on whether or not it appears in the graphical interface?

I recently attended this event, but it is not clear to me if I need to use another scanner or how to achieve this functionality:

[Leveraging OCI 1.1 for Enhanced SBOM Integration and Vulnerability Scanning in Harbor](https://www.youtube.com/watch?v=ABbds5-zSqk)

**Comment by wy65701436** [comment]
The SBOM generation will be available in the upcoming release v2.11. Please keep an eye on the release tag, it will be ready soon for you to try. Thanks.

**Comment by grandeon** [comment]
Thank you very much for your reply!!
