### ISSUE TITLE
Toggle for registryctl access log

### ISSUE THREAD

**Issue by Patrick-Clausen** [goharbor/harbor#20439]
**Is your feature request related to a problem? Please describe.**
I am trying to reduce unneeded logging inside my kubernetes cluster, and one of the offenders is registryctl which emits a log messages any time Kubernetes performs a health check:
```
IP.IP.IP.IP - - [16/May/2024:12:23:12 +0000] "GET /api/health HTTP/1.1" 200 9
IP.IP.IP.IP - - [16/May/2024:12:23:12 +0000] "GET /api/health HTTP/1.1" 200 9
IP.IP.IP.IP - - [16/May/2024:12:23:19 +0000] "GET /api/health HTTP/1.1" 200 9
IP.IP.IP.IP - - [16/May/2024:12:23:22 +0000] "GET /api/health HTTP/1.1" 200 9
```

**Describe the solution you'd like**
A configuration option for registryctl's configuration file to disable the access log:
```
log:
  accesslog:
    enabled: false
  level: debug
```
backwards compatible alternative:
```
log_level: debug
access_log_enabled: false
```

**Describe the main design/architecture of your solution**
Upgrade the Configuration model https://github.com/goharbor/harbor/blob/main/src/registryctl/config/config.go#L33 to one of the models above, use boolean to decide whether the LoggingHandler should be added: https://github.com/goharbor/harbor/blob/main/src/registryctl/handlers/handler.go#L40

**Describe the development plan you've considered**
It seems to be a small change, although I'm unfamiliar with the project, so not sure how relevant it is. I am open to contributing with it myself.

**Additional context**
N/A

**Comment by z0rc** [comment]
Not stale. https://x.com/BenTheElder/status/1407774856033181696
