### ISSUE TITLE
Harbor synchronous mirror occasional write connection timeout

### ISSUE THREAD

**Issue by smallemployees** [goharbor/harbor#20434]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
How will I change the timeout time
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
failed to pushing the blob write: connection timed out
**Versions:**
Please specify the versions of following systems.
v2.2.1
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
Please upgrade your harbor instance since v2.2 is out of support, then rerun the scenario. If you still have the same problem, please provide the core and registry log.

**Comment by smallemployees** [comment]
![image](https://github.com/goharbor/harbor/assets/150658327/a13a072f-cb55-42fe-a89d-49712985e0c1)
![image](https://github.com/goharbor/harbor/assets/150658327/2691138d-e26a-46ad-9990-9c5fd9dd3765)

**Comment by smallemployees** [comment]
Is there a way to address this issue without upgrading the version? What is the main root cause? Due to architecture reasons, I am unable to upgrade in the short term. Is there any way to alleviate this problem

**Comment by wy65701436** [comment]
since we apply the n-2 support strategy, the code case has changed a lot since 2.2. The problems that most likely already resolved in the latest release.
