### ISSUE TITLE
Not able to pull 'helm chart' from Harbor

### ISSUE THREAD

**Issue by rajeev-cs** [goharbor/harbor#20447]
Hi,

I pushed the helm chart to Harbor but I am unable to pull it. I am getting below error.

helm pull oci://xyz.com/abc-helmcharts/mychart --version 1.4.3  (command used) 
                                                     
Error: failed commit on ref "": unexpected commit digest sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, expected sha256:fdea341faa6d680f01ba9cf61975f8c59dfc5f4a97cc3c37ce510a5024ea6c99: failed precondition

Verisons I am using:

 helm version                                                                                                                                              ─╯
version.BuildInfo{Version:"v3.14.1"

Harbor
Version v2.10.0-6abb4eab

**Comment by wy65701436** [comment]
did you see any error in the core or registry log?

**Comment by zyyw** [comment]
Hi @rajeev-cs , please refer to this [PR](https://github.com/goharbor/website/pull/513/files) on how to work with OCI helm chart.
