### ISSUE TITLE
v2.11.0-rc1 prepare file docker tag error promble

### ISSUE THREAD

**Issue by 9Bakabaka** [goharbor/harbor#20446]
When i was running the harbor v2.11.0-rc1 installtion. I run the prepare script and get an error.

```bash
Unable to find image 'goharbor/prepare:v2.11.0' locally
docker: Error response from daemon: manifest for goharbor/prepare:v2.11.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```
When i go to the docker-hub and search the image. I notice that the goharbor/prepare tag was v2.11.0-dev. However, In the prepare script, it was the goharbor/prepare:v2.11.0

- harbor version: [2.11.0-rc1]

**Comment by wy65701436** [comment]
How did you install harbor? Did you perform the `./install.sh` command? 

Before GA, we will not publish the tag of GA to the docker hub.
