### ISSUE TITLE
request: extend robot permissions to update individual project quotas

### ISSUE THREAD

**Issue by blancadesal** [goharbor/harbor#20463]
This would allow us to automate user quota management in a multi-tenant scenario with thousands of users.

Currently, only regular user accounts can do this, if granted admin permissions, but this is not best-practice from a security standpoint.

In addition to enabling us to set individual quotas, this would also allow updating existing projects to a new default project quota. Changes to the default quota do not apply to existing projects, so having some means to update individual projects is necessary here too.

**Comment by Vad1mo** [comment]
duplicate of  https://github.com/goharbor/harbor/issues/20076
