### ISSUE TITLE
REST Api contains repo_name returns NOT_FOUND

### ISSUE THREAD

**Issue by arifeng** [goharbor/harbor#20467]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I upgraded harbor from v1.10.0 to 2.6.2，and found some REST Api not worked. e.g. `/api/v2.0/repositories/top` returns `{"errors":[{"code":"NOT_FOUND","message":"path /api/v2.0/repositories/top was not found"}]}`, and `/api/v2.0/repositories/xxx%2Fyyy/tags` returns `path /api/v2.0/repositories/xxx/yyy/tags was not found `, xxx/yyy was quoted in param. 

**Steps to reproduce the problem:**

upgrade path is 1.10.0 -> 2.1.6  -> 2.3.5 -> 2.6.2 following the official docs.

**Versions:**

- harbor version: [v2.6.2]
- docker engine version: [24.0.7]
- docker-compose version: [1.24.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by MinerYang** [comment]
It should be like for v2.0 to list tags
```
/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/tags
```
Please refer https://<harbor-hostname>/devcenter-api-2.0 to get more about v2.0 API details

**Comment by arifeng** [comment]
It looks like a browser cache issue, the api doc was not updated after upgrade until a hard refresh! Thanks!
