### ISSUE TITLE
How to limit Trivy space, trivy grow without control

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor#20470]
Trivy Version: 2.7.1

It happen in several environments 

docker space of trivy grow a lot more than 8Gb , How to  limit space?

I need control grow because trivy fill my Filesystem

Could you help me with it?

**Comment by zyyw** [comment]
Hi @jorgemansillacriado , by stating that `docker space of trivy grow a lot more than 8Gb`, could you please share with us how you get this observation? Thanks

**Comment by zyyw** [comment]
BTW, are you experiencing Trivy consuming 8Gb during an image scanning process or without scanning images?

**Comment by jorgemansillacriado** [comment]
I have stopped trivy but I have a lot files in overlay2*/diff/tmp 

Could I remove it files with trivy stop?
