### ISSUE TITLE
Replication and Registry created  not visible in UI


### ISSUE THREAD

**Issue by 0xj0el** [goharbor/harbor#20477]
Replication and Registry created using curl command is not visible in UI but can list it with api call

**Comment by stonezdj** [comment]
Can you please describe the detail steps to reproduce it?

**Comment by 0xj0el** [comment]
I am not sure if this is reproducible. We are having a automated workflow which installs harbor and sets up the registry and replication policy. Even I can list it in harbor db.This seems like a sporadic bug. But not sure how to reproduce or provide evidence. Let me know if any particular log is needed during the time of registry and policy creation.

**Comment by 0xj0el** [comment]
Let me analyse this... I think it's a issue with the setup of DR site. I think the southbound IP is pointing to the recovery site. And UI i am seeing is of the recovery site.

Probably this issue can be ignored.

**Comment by stonezdj** [comment]
Maybe the API request is sent to the DR site.
