### ISSUE TITLE
Should we rename the butto of Stop Scan to Stop Vulnerability

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#20499]
Since we call the triggers as Scan Vulnerability and Generate SBOM
![image](https://github.com/goharbor/harbor/assets/2841473/2138dcb1-014f-44ee-b2b6-32829a6238eb)

**Comment by xuelichao** [comment]
After this fix the new text for the two buttons will be:
STOP VULNERABILITY
STOP GENERSTE SBOM

**Comment by xuelichao** [comment]
Maybe we should update to STOP SCAN VULNERABILITY
