### ISSUE TITLE
Is there any parameter which restricts thenumber of connection to harbor ?

### ISSUE THREAD

**Issue by kavyavvv** [goharbor/harbor#20523]
Is there any parameter which restricts thenumber of connection to harbor ?
How to finetune harbor for handling 1200 parellel pulls ?

**Comment by wy65701436** [comment]
what connection do you mean? Did you notice any bottle neck for your concurrence pulling?

**Comment by kavyavvv** [comment]
yes , 
we are getting some errors like connection reset by peer , sometimes 502 gateway error and few TLS handshake errors as well

**Comment by wy65701436** [comment]
several points that we need to check, 

1. cpu/memory usage of core, db, registry
2. database connection
3. the connection reset happens at which phase, it's closed by nginx, distribution or storage.

**Comment by kavyavvv** [comment]
![image](https://github.com/goharbor/harbor/assets/160131105/e7dfa63e-b7e7-48bb-926f-95d1a3fcda15)

**Comment by kavyavvv** [comment]
we are setting such limits to the containers and sometimes CPU and mem for registry will be 100 percent with above restriction

**Comment by stonezdj** [comment]
Do you have any log information shows that `connection reset happens between registry and core`?
The connect reset /tls handshake errors should occur in Nginx side

**Comment by kavyavvv** [comment]
when we try for 1200 parellel pulls , registry is restarting

**Comment by dusmeyenlabut** [comment]
Hello is there any update on this, we had same issue around 4800 pull requests come to harbor and we need a limitation on harbor itself.

**Comment by Vad1mo** [comment]
My recommendation is to set those limits on your ingress!
