### ISSUE TITLE
`No SBOM` logic between SBOM deleted and literally no SBOM generation should be the same

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20529]
How to reproduce?
1. deploy a harbor instance with the latest source code
2. replicate redis:latest from dockerhub to harbor
3. select all artifacts of the redis artifacts replicated, and click `GENERATE SBOM`
4. delete the first SBOM generated
5. the `No SBOM` between SBOM deleted and literally no SBOM generation is not the same regarding layout and hover message
<img width="1528" alt="Screenshot 2024-05-31 at 4 16 48 PM" src="https://github.com/goharbor/harbor/assets/6709992/a9585fbf-55ce-461c-b17f-362a8473ea81">

**Comment by zyyw** [comment]
This might be due to red rectangle having `sbom_overview` of something like below:
```
  "sbom_overview": {
    "duration": 16,
    "end_time": "2024-05-31T08:11:23.000Z",
    "scan_status": "Success",
    "start_time": "2024-05-31T08:11:06.808Z"
  }
```

**Comment by stonezdj** [comment]
this issue https://github.com/goharbor/harbor/issues/20320  requires the sbom_overview to return a status to stop refresh
