### ISSUE TITLE
Pull through cache with image list options and retention policy oriented to long term.

### ISSUE THREAD

**Issue by dada216** [goharbor/harbor#20577]
I am searching for a pull through cache where I can keep publicly available images from many registries long term, think enterprise applications with a long life (10 years) built on top of public container images.

Basically a pull through cache with the ability to list which images have been cached from the public registries, flag images and tags as long term storage/part or a release and choose a retention policy for images, so that I can just backup the harbor instance and be able to rebuild my application when they become legacy applications and the original images are not available anymore.

there's many ways to achieve this by just saving the docker images, having the ability to do it in the pull through cache would be beneficial I believe

**Comment by zyyw** [comment]
Maybe this can be achieved by applying both the proxy-cache feature and tag retention policy functionality separately.
