### ISSUE TITLE
[feature request] Add a Section Named "Repositories" Below "Projects" on the Left Sidebar

### ISSUE THREAD

**Issue by BrettDean** [goharbor/harbor#20586]
# Add a Section Named "Repositories" Below "Projects" on the Left Sidebar

In the "Repositories" tab, all visible repositories like "name/repo" will be displayed, 

making it convenient to find and search for specific repos.

![image](https://github.com/goharbor/harbor/assets/36684698/c9bda6a5-f852-4a0c-810f-68138003ebd9)

**Comment by zyyw** [comment]
In Harbor, we have the concept of `project` and every artifact is under a project (namespace). Users can always search for a project first to narrow down their target and then search for an artifact within a specific project to locate their searching target. This seems good enough to me though.

**Comment by zyyw** [comment]
You can search repository in `Search Harbor` search box at the top middle.
