### ISSUE TITLE
failed to do the prepare work for pushing/uploading resources: http error: code 401

### ISSUE THREAD

**Issue by zhuzhenfan** [goharbor/harbor#20583]
Both my habor versions are v2.4.3- 85ef1409 .
Occasionally when copying mirrors from A-harbor to B-harbor, the following error occurs: failed to do the prepare work for pushing/uploading resources: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized"}]}

My configured harbor account and password are correct.

I adjusted the logging to debug level and did not see a valid message.

**Comment by zyyw** [comment]
Hi, replication from one Harbor to another Harbor is recommended to having them with the same version.
BTW, Harbor v2.4.3 is out of the support scope. Please try to upgrade it (with n-2 version, 2.4 -> 2.6 -> 2.8 ...).
