### ISSUE TITLE
GC failed with a error: "failed to delete untagged:315 artifact in DB, error, sql: transaction has already been committed or rolled back"

### ISSUE THREAD

**Issue by wenwutang1** [goharbor/harbor#20582]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

task run GC failed，found some error in log
![image](https://github.com/goharbor/harbor/assets/45817987/6ca234b3-a397-48b2-ab09-48d93e4bf18a)
![image](https://github.com/goharbor/harbor/assets/45817987/179b548d-1ea3-4474-bc55-94d2c0ce3646)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

1. run GC failed
2. manual dry-run is ok

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.6.4]
- docker engine version: [20.10.7~3]
- docker-compose version: [2.1.1]

**Comment by wy65701436** [comment]
please check the your database status, and ensure it can accept connections. And you can upgrade your harbor to the supported version, which is higher than v2.9.0. 

Please reopen this issue if you still see it after the upgrade.
