### ISSUE TITLE
Harbor Registry endpoint is redirecting to hardcoded URL

### ISSUE THREAD

**Issue by abhishek-anand-hpe** [goharbor/harbor#20594]
**Expected behavior and actual behavior:**
I have two harbor instances

- harbor-lb.cgw-hpe.net (let's say, harbor1)
- harbor.stxxx.cgw-hpe.net (let's say, harbor2)

I am trying to create a replication policy on harbor2 to replicate some artifacts from harbor1.
To create replication policy first I am trying to create a registry endpoint (pointing to harbor1)

**Steps to reproduce the problem:**
I am running below curl command from my setup where both harbor1 and harbor2 are reachable

```
curl -X 'POST'  https://harbor.stxxx.cgw-hpe.net/api/v2.0/registries  -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "credential": {
    "access_key": "admin",
    "access_secret": "xxxxx",
    "type": "basic"
  },
  "name": "test",
  "url": "https://harbor-lb.cgw-hpe.net",
  "insecure": true,
  "type": "harbor",
  "description": "test"
}' -k -u "admin:xxxxx"
```
It is giving me 504 or 400 error.
When I check the logs of harbor-core pod, I get below error
![MicrosoftTeams-image (6)](https://github.com/goharbor/harbor/assets/137749654/1a93723c-85dd-49a3-9532-b2e76e695de8)

From the error it looks like it is redirecting the request from 'https://harbor-lb.cgw-hpe.net' to 'https://harbor.cgw-hpe.net', and that is strange as we are not explicitly harcoding or specifying "harbor" instead of "harbor-lb" anywhere in our code.

**Versions:**

- harbor version: [2.7.1]

**Comment by zyyw** [comment]
Are you able to create the registry endpoint pointing to Harbor1 from the Harbor portal of Harbor 2 ?

**Comment by divya-prakash2** [comment]
same issue faced when trying to create a registry endpoint from Harbor portal as well @zyyw . Looking at the logs from harbor-core pod we have seen that it is trying to point to a different URL ( harbor.cgw-hpe.net instead of harbor-lb.cgw-hpe.net )

**Comment by zyyw** [comment]
could you please try to set `externalURL` to  harbor-lb.cgw-hpe.net (for harbor1)?
