### ISSUE TITLE
go mod tidy fails

### ISSUE THREAD

**Issue by duyawen8** [goharbor/harbor#20590]
harbor version: v2.3.1-fd80757d 

golang version: go1.15 darwin/amd64

when I run go mod tidy, it fails: 

github.com/goharbor/harbor/src/server/v2.0/handler imports
        github.com/goharbor/harbor/src/server/v2.0/models: module github.com/goharbor/harbor@latest found (v2.11.0+incompatible, replaced by ../), but does not contain package github.com/goharbor/harbor/src/server/v2.0/models
github.com/goharbor/harbor/src/server/v2.0/handler imports
        github.com/goharbor/harbor/src/server/v2.0/restapi: module github.com/goharbor/harbor@latest found (v2.11.0+incompatible, replaced by ../), but does not contain package github.com/goharbor/harbor/src/server/v2.0/restapi
github.com/goharbor/harbor/src/server/v2.0/handler imports
        github.com/goharbor/harbor/src/server/v2.0/restapi/operations/artifact: module github.com/goharbor/harbor@latest found (v2.11.0+incompatible, replaced by ../), but does not contain package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/artifact
github.com/goharbor/harbor/src/server/v2.0/handler imports
        github.com/goharbor/harbor/src/server/v2.0/restapi/operations/auditlog: module github.com/goharbor/harbor@latest found (v2.11.0+incompatible, replaced by ../), but does not contain package github.com/goharbor/harbor/src/server/v2.0/restapi/operations/auditlog

**Comment by zyyw** [comment]
Hi, Harbor version of v2.3.1 is out of support scope, please try to use a relative update-to-date Harbor version.
Regarding your questions, please try to run `make gen_apis` before `go mod tidy`.
