### ISSUE TITLE
[Bug Report] The banner message is causing the search bar to be obscured.

### ISSUE THREAD

**Issue by BrettDean** [goharbor/harbor#20608]
**Expected behavior and actual behavior:**

- Expected behavior: After searching, if there is a banner message at the top of the page, it `will not` causing the search bar to be obscured.

- Actual behavior: After searching, if there is a banner message at the top of the page, it `will` causing the search bar to be obscured.
![image](https://github.com/goharbor/harbor/assets/36684698/7fd56719-518b-4265-873e-65d67a999798)

```bash
body > harbor-app > harbor-shell > clr-main-container > div > div > search-result > div
```

**Steps to reproduce the problem:**
Search anything when there's a `banner message` on the top
reproduce video: 

https://github.com/BrettDean/temp/raw/main/20240624/output.mp4

<video controls>
  <source src="https://github.com/BrettDean/temp/raw/main/20240624/output.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

This issue can be reproduced on macOS Sonoma 14.5 in the following browsers:

- Safari 17.5 (19618.2.12.11.6)
- Firefox 127.0
- Chrome 125.0.6422.176

**Versions:**

- harbor version: v2.11.0
- docker engine version: Docker version 26.1.4, build 5650f9b
- docker-compose version: Docker Compose version v2.27.0

**Comment by MinerYang** [comment]
Hi @BrettDean ,

Are you interested in to help us to resolve this UI issue ? 

Best,
Miner

**Comment by kunal-511** [comment]
@BrettDean How did you get the banner on top?
