### ISSUE TITLE
Errors found when upgrading Harbor & migrating the database: 'ERROR:  function jsonb_path_exists(jsonb, unknown) does not exist' 

### ISSUE THREAD

**Issue by sicko583** [goharbor/harbor#20614]
Hi team,

I am running on Harbor v2.8.6 now and trying to upgrade Harbor to newer version v2.9.4 then v2.10.2 with helm-charts. But I get some errors when upgrading:

2024-06-18T02:47:16Z [ERROR] [/common/dao/pgsql.go:140]: Failed to upgrade schema, error: "Dirty database version 120. Fix and force version."

I followed the guide at : https://github.com/goharbor/harbor/wiki/Harbor-FAQs#upgrade, to reset the dirty to false and roll back to the previous version, then run sqls manually at https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0120_2.9.0_schema.up.sql, but I still get some errors:

registry=> \e
NOTICE:  relation "idx_task_extra_attrs_report_uuids" already exists, skipping
CREATE INDEX
ERROR:  function jsonb_path_exists(jsonb, unknown) does not exist
LINE 3: WHERE jsonb_path_exists(extra_attrs::jsonb, '$.artifact.id')
              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ERROR:  function jsonb_path_exists(jsonb, unknown) does not exist
LINE 3:         WHERE jsonb_path_exists(vendor_attributes::jsonb, '$...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  UPDATE vulnerability_record
        SET cvss_score_v3 = (vendor_attributes->'CVSS'->'nvd'->>'V3Score')::double precision
        WHERE jsonb_path_exists(vendor_attributes::jsonb, '$.CVSS.nvd.V3Score')
CONTEXT:  PL/pgSQL function inline_code_block line 4 at SQL statement
NOTICE:  relation "idx_report_vulnerability_record_vuln_record_id" already exists, skipping
CREATE INDEX

I also turn on the migration job with enableMigrateHelmHook=true, but similar errors found in harbor-core logs (error attached).

I notice that function is supported on postgresql v9.3+, and I use external RDS with engine version 11.21 which is supported. Any ideas on how to fix the issue? Thanks for your time and help here.
[migration job error.txt](https://github.com/user-attachments/files/15879942/migration.job.error.txt)

**Comment by chlins** [comment]
Please refer to the release notes of v2.9(https://github.com/goharbor/harbor/releases/v2.9.0), one breaking change that was pointed out was that **PostgreSQL >= 12** is required for external databases.

**Comment by sicko583** [comment]
> Please refer to the release notes of v2.9(https://github.com/goharbor/harbor/releases/v2.9.0), one breaking change that was pointed out was that **PostgreSQL >= 12** is required for external databases.

I'm sorry that I missed the notes here. I will have my RDS upgraded first then upgrade harbor. Thanks for your help.
