### ISSUE TITLE
loggerSweeperDuration does not clean the /var/log/jobs files.

### ISSUE THREAD

**Issue by riyas-rawther** [goharbor/harbor#20618]
We have enabled[ jobservice.jobLoggers](https://artifacthub.io/packages/helm/harbor/harbor?modal=values&path=jobservice.jobLoggers) ti file and jobservice.loggerSweeperDuration ti 1 day. Unfortunately, the sweep is not working. /var/log/jobs logs and flooded with empty file which causing inod issues. 

We also tried Garbage Collection and Log Rotation, it does not help either.

Chart Version: 1.14.0

**Comment by MinerYang** [comment]
- Please provide the config.yml in the jobservice pod. 
 - And more logs for harbor-jobservice and harbor-core to check if any errors 
```
kubectl exec  -it <jobservice-pod>  -- cat /etc/jobservice/config.yml
```
