### ISSUE TITLE
use nginx proxy

### ISSUE THREAD

**Issue by weiailmy** [goharbor/harbor#20626]
We used an external nginx proxy, but the proxy path for the harpor was not '/' but '/harbor', which caused the UI to not display properly. Using external_URL: xxx. domain. com/harpor is also incorrect. I would like to ask how to solve this problem.

location /harbor/ {

            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://10.1.1.10:31000/;
		
        }

**Comment by MinerYang** [comment]
Hi @weiailmy ,

There's no route for `/harbor`. Please refer to the internal one for details. Or try to install an internal one and to leverage how to meet your requirements.
https://github.com/goharbor/harbor/blob/main/make/photon/prepare/templates/nginx/nginx.https.conf.jinja
