### ISSUE TITLE
Harbor replication task throw error : read tcp src_ip:port->dest_ip:port-: read: connection timed out

### ISSUE THREAD

**Issue by helongwen** [goharbor/harbor#20649]
Harbor verion: 2.3.4
Issue: 
I create replicate task on harbor Replications menu,  some images sync successfully to target image reposity. but some images sync failed, the error log display as bellow:
[/controller/replication/transfer/image/transfer.go:322]: failed to pushing the blob sha256:xxxxxx, size 324122020: Put "https://xxxx/v2/{repo}/{image}/blobs/uploads/fb86ff9b-6c00-4b8d-8463-63ea491467e3?_state=0000000100000001963AC936A914C8FF14C3ED432B4D3451E8A72618ABA0346F33BF46BAF018441E131576D2BCD18A2A5F2B90172A226256EE3D1068FE4C5577A7505F8FF0236B0CEAC5B93C87895DA3564A6796161BBB01&digest=sha256%3Afa02336d667550214be474476526a3c62053d7a293598f385e93dccffca93809": read tcp 192.168.15.22:36030->172.24.31.252:443: read: connection timed out

what is the solution for the above issue?

**Comment by MinerYang** [comment]
Hi @helongwen ,
 - this is a network problem that you may need identify it yourself. e.g. could you manually pushing image correctly or adjust your timeout settings for proxy etc..
 - Harbor v2.3.4 is out of support. please upgrade to the latest ones.
