### ISSUE TITLE
Referral failure with LDAP auth

### ISSUE THREAD

**Issue by ilsaloving** [goharbor/harbor#20641]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expectation: Successful authentication of AD user
Actual: Login failure

**Steps to reproduce the problem:**
Deploy Harbor and configure LDAP/AD authentication

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.11.0
- docker engine version: 24.0.7, build 24.0.7-0ubuntu4
- docker-compose version: [2.24.6+ds1-0ubuntu2

**Additional context:**

The logs contain:
```
[/core/controllers/base.go:101]: Error occurred in UserLogin: LDAP Result Code 10 "Referral": 0000202B: RefErr: DSID-0310084B, data 0, 1 access points
	ref 1: 'myldapdomain.com'
```

Looks like you either need to enable Referrals in the code, or expose the setting for users to modify.

**Comment by MinerYang** [comment]
Could you check your LDAP server log to identify the issue?

**Comment by dajose** [comment]
> Could you check your LDAP server log to identify the issue?

I can't, the server is not under my control.

I am thinking maybe the latest version dropped support for some ciphers, but I am not sure on what to check to see that

**Comment by ilsaloving** [comment]
I just took a quick look and realized there was a typo in my Base DN.  >_< After I corrected that, authentication worked.
