### ISSUE TITLE
Can Harbour synchronous mirror control block size

### ISSUE THREAD

**Issue by smallemployees** [goharbor/harbor#20668]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
failed to pushing the blob sha256:ba0a04d86f34b0e73b16fcbeda014337dbf7bbd1d9c9554742f312e9f502aa2a, size 152588325: Put  readfrom tcp 172.19.0.10:34510->10.99.69.159:1121: write tcp 172.19.0.10:34510->10.99.69.159:1121: write: connection timed out
Can I configure the synchronized block size myself to alleviate the pressure on the network layer
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
v.2.2.1

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
The replication introduces `Copy by chunk` since the harbor v2.7, you can also configure the chunk size by the ENV but by default is 10MB, see more details here: https://goharbor.io/docs/2.7.0/administration/configuring-replication/create-replication-rules/

**Comment by MinerYang** [comment]
Please upgrade to the latest version
