### ISSUE TITLE
The image replication task fails 20 seconds after it is started.

### ISSUE THREAD

**Issue by helongwen** [goharbor/harbor#20667]
I config a replication task from one harbor to another harbor,  when I start the replication job, it always  fail  20s after one image layer begin to be replicated.   (not one image layer ,  many image layers  getting this 20s timeout error.)
Is there any parameter related to 20s? for example , when the data transfer too slow,  harbor stop the image layer sync task 20 seconds later? 
May I configure 20 seconds  to longer time , because my network is not so fast

**Comment by MinerYang** [comment]
what's your harbor version? And please kindly provide your replication logs
