### ISSUE TITLE
Using Docker Compose to build, after about half an hour, the Harbor Core suddenly closed

### ISSUE THREAD

**Issue by RogueCultivators** [goharbor/harbor#20674]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I experienced a shutdown of the Harbor core about half an hour after installing the Harbor program, and the Docker's automatic restart failed
﻿

**Steps to reproduce the problem:**
install harbor 

**Versions:**

- harbor version: [2.9.4]
- docker engine version: [27.0.1]
- docker-compose version: [v2.28.1]

**Additional context:**
- harbor-core logs:
![image](https://github.com/goharbor/harbor/assets/49176713/c444408e-2137-4fda-b6f4-d0c118f3b3a8)

- registryctl logs:
![image](https://github.com/goharbor/harbor/assets/49176713/7a40fa66-4e7a-48ee-be63-03e18887d836)

**Comment by RogueCultivators** [comment]
Unable to restart
![image](https://github.com/goharbor/harbor/assets/49176713/4f64c81c-431c-41be-b93f-6b0f631b5df2)

**Comment by MinerYang** [comment]
Have you restart your docker service or reboot system?

**Comment by RogueCultivators** [comment]
> Have you restart your docker service or reboot system?

No other actions were taken. After discovering this issue, I wrote a script to check if the Harbor was working properly. If it was not working properly, I would restart it using Compose
