### ISSUE TITLE
Creating robot accoun in project by ActiveDirectory AD User in a group permissions empty

### ISSUE THREAD

**Issue by n1teb** [goharbor/harbor#20689]
**Expected behavior and actual behavior:**
I want to create a robot account in a project. I`m Active Directory user and I`m a project owner. 

When the user is added as a user in project i can create the robot account properly
When the permission to the project is added via a group (AD) and the permissions is project owner. When i create new robot account the permissions are empty. 

Please specify the versions of following systems.

- Version v2.10.0-6abb4eab
- deployed on Rancher via helm

**Comment by wy65701436** [comment]
This issue was fixed in the v2.11.0, please try with that release.
