### ISSUE TITLE
Questions about Get method of blob controller

### ISSUE THREAD

**Issue by pendoragon** [goharbor/harbor#20690]
I was looking at harbor code and get a bit confused by the code below:
https://github.com/goharbor/harbor/blob/27e06ac6099d5da4421b2e1b1b0a24985c2a1392/src/controller/blob/controller.go#L228-L247

The Get method supports options like `ArtifactDigest` and `ProjectID`. These options gets converted to query keywords. 
Under the hood, it calls `List` method of blob manager, which just queries table `blob` of the database
https://github.com/goharbor/harbor/blob/27e06ac6099d5da4421b2e1b1b0a24985c2a1392/src/pkg/blob/dao/dao.go#L227-L237

However, the `blob` table has no `projectID` or `artifactDigest` column. Am i missing something?

**Comment by wy65701436** [comment]
it's used the blob model at https://github.com/goharbor/harbor/blob/main/src/pkg/blob/models/blob.go#L126.
Harbor defines some specific query and used by orm at https://github.com/goharbor/harbor/blob/main/src/lib/orm/metadata.go#L60
