### ISSUE TITLE
Making a robot via /projects/{project_name_or_id}/robots is broken

### ISSUE THREAD

**Issue by Kajot-dev** [goharbor/harbor#20692]
This endpoint does not parse permissions correctly:
Try to create a robot in your project via `/projects/{project_name_or_id}/robots` with this payload:
```json
{
  "name": "puller",
  "description": "Project puller. Created automatically.",
  "expires_at": -1,
  "access": [
    {
      "resource": "repository",
      "action": "pull",
      "effect": null
    }
  ]
}
```

This returns 400 with `pull action of repository resource not exist in project <project_name>`

However creating exactly the same robot via `/robots` endpoint works perfectly. Working payload:

```json
{
  "name": "puller",
  "description": "Project puller. Created automatically.",
  "level": "project",
  "duration": -1,
  "permissions": [
    {
      "access": [
        {
          "resource": "repository",
          "action": "pull",
          "effect": null
        }
      ],
      "kind": "project",
      "namespace": "<project_name>"
    }
  ]
}
```

**Comment by wy65701436** [comment]
can you clarify the problem? It seems that the creation was successfully with the correct payload.

**Comment by Kajot-dev** [comment]
Payload is correct in **both** examples (it is different since it uses different api ednpoints). But endpoint `/robots` works, but `/projects/{project_name_or_id}/robots` does not.

It should succeed in both examples.

**Comment by Kajot-dev** [comment]
To reproduce just try to create a robot via `/projects/{project_name_or_id}/robots` (a one which haves some permissions) - it's not possible from my testing

**Comment by dmakeienko** [comment]
I've encountered same problem along with the inability to create project robot accounts under non-admin user (user has Project Admin privilege)
