### ISSUE TITLE
Backup and restore project/images

### ISSUE THREAD

**Issue by tnubeo1111** [goharbor/harbor#20703]
Hello, can I ask if version v2.11 can now backup and restore projects or images? Because sometimes I will accidentally delete those projects and I want to restore them. So if you have a solution, please suggest me.

At the same time, I currently install Harbor using Helm and my images are also connected to external s3

**Comment by wy65701436** [comment]
No, we don't support this use case. And do wanna restore an empty project? Why cannot your re-create an project with the same name?

**Comment by Kajot-dev** [comment]
@tnubeo1111 Best thing to do would be to setup a second registry and replicate your images there. And Harbor only allows to delete projects that are empty, so how can you accidentally delete a project?

**Comment by tnubeo1111** [comment]
Maybe I'm not clear, what I mean is that I accidentally deleted the images and then deleted the project, but after a while I wanted to reuse the images of the deleted project and there was no way to restore it.

**Comment by tnubeo1111** [comment]
I have come up with a new solution which is to use **skopeo** and combine writing bash. So I would like to close this ticket. Thank you everyone for your interest.
