### ISSUE TITLE
trivy fanal.db is too much

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#20702]
Hello,

The size of   /data/trivy-adapter/trivy/fanal/fanal.db in 32G and still increasing.
Currently it is on root volume.

harbor version: v2.9.2

[root@ip-10-0-233-58 trivy]# tree -h 
. 
├── [ 43] db 
│ ├── [ 153] metadata.json 
│ └── [ 474M] trivy.db 
├── [ 22] fanal 
│ └── [ 34G] fanal.db 
└── [ 48] java-db 
 ├── [ 153] metadata.json 
 └── [1010M] trivy-java.db 
 
3 directories, 5 files 

Could you please help on this.

Thank You,
Ayush

**Comment by knqyf263** [comment]
Duplicate of https://github.com/goharbor/harbor/issues/16606. A related issue is https://github.com/aquasecurity/harbor-scanner-trivy/issues/234.

As documented here, the cache keeps growing.
https://aquasecurity.github.io/trivy/v0.53/docs/references/troubleshooting/#running-out-of-space-during-image-scans

The easiest workaround for now is restarting a Trivy Pod.
