### ISSUE TITLE
When we delete an artifact, will the data associated with it also be deleted?

### ISSUE THREAD

**Issue by yexia553** [goharbor/harbor#20700]
Dear harbor team,

I want to get help from you that, if we delete an artifact(docker image), will the data associated with it also be deleted?
for example, the vulnerability data, audit logs.

looking forward to your reply.
thank you

**Comment by wy65701436** [comment]
To understand this question clearly and correctly, you can go through the source code of artifact controller.

Generally, some data with be removed align with the deletion of an artifact, and others are removed by garbage collection.

**Comment by yexia553** [comment]
Hi @wy65701436 , thank you for your suggestion, I am a new comer of golang and harbor source code, but I will dive into that help make it out.
currently, we got some issue when we upgrade harbor from 2.7.x to 2.8.x and 2.9.x, we have more the 330000000 rows in the report_vulnerability_record table, and it always cause DB migration failed, could you help give us some suggestion for that ?

Best Regards
Thanks

**Comment by chlins** [comment]
Do you enable automatic scanning upon push? The table is intended to record the artifacts' vulnerabilities. Could you also provide the total number of artifacts?
