### ISSUE TITLE
update harbor `2.6.2` to `2.10.3` succ. but  `Helm Charts` disappeared

### ISSUE THREAD

**Issue by nAnderYang** [goharbor/harbor#20727]
hi there

mirror the old vm to new vm
update harbor
```
v2.6.2 -> v2.8.6 -> v2.9.5 -v2.10.3
```

update no error output

now , i can't find `charts` in project
the old version
![image](https://github.com/goharbor/harbor/assets/28423384/2f99d5c3-6f4d-4832-975b-c65eabce344c)

the new version
![image](https://github.com/goharbor/harbor/assets/28423384/19d51a59-1c6a-4afc-bd10-a8335e745a2a)

how do fix it?!

**Comment by stonezdj** [comment]
Chat museum is deprecated in v2.7.0. see: https://github.com/goharbor/harbor/releases/v2.7.0
Follow this guide to migrate it: https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

**Comment by nAnderYang** [comment]
> Chat museum is deprecated in v2.7.0. see: https://github.com/goharbor/harbor/releases/v2.7.0 Follow this guide to migrate it: https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor

OK , thanks~
