### ISSUE TITLE
Docker Login failed with status: 401 Unauthorized - Secret Mismatch

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [goharbor/harbor#20729]
### Outline

Hey all, I'm trying to log into harbor using the docker CLI using the secret value from Harbor + OIDC:

```sh
docker login <DOMAIN>
```

### Issue

I am getting the following error after providing the username and secret:

```sh
Error response from daemon: login attempt to <DOMAIN> failed with status: 401 Unauthorized
```

This is running in K8s behind traefik, so we have the following:

Client --> Traefik (SSL) --> Harbor NGINX (NO SSL) --> Harbor

The logs are showing that it is able to make a connection, it is attempting to validate the secret, and is claiming that the secret is invalid. 

```
[/server/middleware/security/oidc_cli.go:68][requestID="******"]: failed to verify secret, username: <USERNAME>, error: failed to verify the secret: secret mismatch, username: <USERNAME>

[ERROR] [/server/middleware/security/basic_auth.go:72][client IP="***" requestID="***" user agent="***"]: failed to authenticate user:<USER> error:not supported
```

This doesn't make sense to me considering that I pulled the secret right from Harbor? Looks like the second error is the original error floating up?

### Other notes

I am able to log in using the OIDC provider without an issue, the username is correct and is in sync. I cannot log in as non OIDC with a password (default deployed user).

Any ideas would be greatly appreciated! Thanks!

**Comment by stonezdj** [comment]
The docker login username/secret is different with the OIDC username/password.
see https://goharbor.io/docs/2.10.0/administration/configure-authentication/oidc-auth/

**Comment by Nathan-Nesbitt** [comment]
> The docker login username/secret is different with the OIDC username/password.
> see https://goharbor.io/docs/2.10.0/administration/configure-authentication/oidc-auth/

Thanks for your reply, I read through the document attached and I am doing those steps as indicated.

Specifically the secrets logic via the CLI, providing the username + secret is what is resulting in the error.

I'm thinking either the token isn't being passed through in the header properly (trafik is stripping it, although I don't think this is the case as I have other apps that also use headers and they are passing through) or there is something going on with the validation? 

Any ideas? :) thanks!
