### ISSUE TITLE
Error response from daemon: Get "https://harbor-xxxx": dial tcp: lookup harbor-labnum.aphp.fr on xx.XXX.XX:53: no such host

### ISSUE THREAD

**Issue by YoussefAphp** [goharbor/harbor#20739]
0

i have installed harbor registring with docker compose and it works as expected.

but when i rtry to do docker login https://harbor-domain-name it gives me this error :

`Error response from daemon: Get "https://harbor-domain-name/v2/": dial tcp: lookup harbor-domain-name on xx.XX.XX:53: no such host`

could you help please ?

**Comment by stonezdj** [comment]
It is an issue related to name resolving, the `harbor-domain-name` can't be resolved.
