### ISSUE TITLE
Response 401 Unauthorized when deleting tag from registry using robot account

### ISSUE THREAD

**Issue by aweng-aria** [goharbor/harbor#20738]
**Expected behavior and actual behavior:**
Deleting a tag from an image results in 401 Unauthorized response.

**Steps to reproduce the problem:**
`curl -X DELETE https://<myharbor>/api/v2.0/projects/<project>/repositories/<image>/artifacts/<tag>/tags/<tag>
   -H 'Content-Type: application/json'
   -H 'Authorization: Bearer <robot token>'`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.11.0-70255684
- docker engine version: n/a
- docker-compose version: n/a

**Additional context:**

Other commands to list and retrieve data are successful
Robot account has full permissions

**Comment by wy65701436** [comment]
you should use the basic auth of your robot to issue the request above. Please reopen it if it still exists.
