### ISSUE TITLE
Authorize bot to list global labels

### ISSUE THREAD

**Issue by jboulmier** [goharbor/harbor#20730]
**Is your feature request related to a problem? Please describe.**

I'm trying to write a script filtering artifacts by a label.
The list artifacts endpoint accept filtering by label id (and not name).
The input of my script is using the label name (more convenient for end users).

However, it is impossible to request the `/labels` endpoint to get the ID from the name for a label with the global 

**Describe the solution you'd like**

- Add the label list system permission
- Allow access to the `/labels` endpoint for global label if the robot account has the label list permission.

**Comment by wy65701436** [comment]
it's doable in the harbor v2.10+, what's the version of harbor are you using? Can you share your script or the specific API that you're using to list labels? And the permission set of you robot.



<img width="1061" alt="image" src="https://github.com/user-attachments/assets/57c4f1f7-cc53-4ce5-af29-1a021ba87ae3">
