### ISSUE TITLE
Does the Harbor support HTTPS bidirectional authentication?

### ISSUE THREAD

**Issue by carefree666** [goharbor/harbor#20747]
Now I use the Nginx proxy Harbor and use Nginx for HTTPS two-way authentication.

**Comment by carefree666** [comment]
In the directory '/etc/docker/certs.d/hostname/' put 'ca.crt、client.cert、 client.key' has no effect

**Comment by MinerYang** [comment]
No we don't. We don't validate client CA.

**Comment by carefree666** [comment]
> No we don't. We don't validate client CA.

Is there a support plan

**Comment by zyyw** [comment]
Unfortunately, there is currently no plan to support this feature.

**Comment by carefree666** [comment]
> Unfortunately, there is currently no plan to support this feature.

okay, thank you
