### ISSUE TITLE
Harbor Database cleanup doesn't work

### ISSUE THREAD

**Issue by petr202261** [goharbor/harbor#20741]
My Harbor garbage collection doesn't work. Harbor is running in EKS, its database is AWS RDS and images are stored in S3. The images are not cleaned from S3 at all. It is already 29 TiB. I see logs with errors from RDS (in attachment)
The workaround that was suggested doesn't help - https://github.com/goharbor/harbor/issues/19494#issuecomment-1803750308

Please, help to fix it. I have no idea how to force Harbor to clean images
[postgresql_2024-07-11-1300.txt](https://github.com/user-attachments/files/16227878/postgresql_2024-07-11-1300.txt)

**Comment by wy65701436** [comment]
Let me clarify, it is not the an issue of GC. And the problem will be fixed in the next harbor patch releases. 

PR: https://github.com/goharbor/harbor/pull/20603

**Comment by petr202261** [comment]
@wy65701436 when this patch will be released? Do I need to clean my db before moving Harbor to a new version? I understood that Harbor replicates data during the version upgrade. So I am concerned that with a big data amount, my Harbor can get stuck.

**Comment by petr202261** [comment]
Do you have a script to clean old Harbor data, so I can run it in my DB?
