### ISSUE TITLE
dose pull/push request support to read/write to storage directly?

### ISSUE THREAD

**Issue by z7658329** [goharbor/harbor#20750]
i have deploy harbor(version 2.7.3), and config oss as storage, my question is :  dose pull/push request support to read/write from storage directly? rather than use harbor as proxy

**Comment by zyyw** [comment]
https://github.com/goharbor/harbor/blob/v2.7.3/make/harbor.yml.tmpl#L68

maybe set the `redirect.disabled` to be `true`
