### ISSUE TITLE
Harbor Metrics ServiceMonitor(Prometheus/Victoriametrics)

### ISSUE THREAD

**Issue by Twisterrr** [goharbor/harbor#20759]
Hi,

I want to monitor my Harbor kubernetes (v2.9.1) instance but I got an issue. I use a Victoriametrics agent (similar propertiers as prometheus operator) with a VMServiceScrape (similar as ServiceMonitor) yaml file : 
`apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: harbor
  namespace: harbor
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: harbor
`
And I have an issue on my Harbor services (Core, Jobservice, Registry and Exporter) who are using a "https-metrics" name of port 8001 instead of "metrics" which working when I change manually.

With "https-metrics" = not working :
![image](https://github.com/user-attachments/assets/db385f83-3942-44b5-b0d5-3650003f35dd)

With "metrics" = working : 
![image](https://github.com/user-attachments/assets/6bb5b6c8-680e-4c56-9b54-ed534429d206)

How can I change it in values.yaml files ?

**Comment by MinerYang** [comment]
the metrics path by default is `/metrics`, if you need to specify them please modify at [metrics fields](https://github.com/goharbor/harbor-helm/blob/15695360541841fe07b7293a66d8495d6ff95ec5/values.yaml#L390)
```
metrics:
  enabled: false
  ...
  exporter:
    path: /metrics
    port: 8001
```

**Comment by Twisterrr** [comment]
sorry for the long return, basically in the deployment of harbor, the name of the default ports are "https-metrics". And to modify that for the moment I am obliged to modify hard in the yaml file directly on Rancher in this case.

Even by putting in my scrape service "https-metrics", prometheus does not retrieve the metrics.

**Comment by Hela98** [comment]
Hello, this issue is exactly what I'm dealing with. I see it's closed, but I’d love to know how it was resolved. If anyone could share insights or a final solution, it would be really helpful. Thanks in advance!
