### ISSUE TITLE
Error 401 Unauthorized deleting repository using REST API

### ISSUE THREAD

**Issue by aria-ml** [goharbor/harbor#20753]
**Expected behavior and actual behavior:**
Expected: Deleting repository via REST API as described in https://harbor.jatic.net/#/repository/deleteRepository should work.
Actual: Error 401 Unauthorized

**Steps to reproduce the problem:**
User is project owner
Token created using `echo -n <user>:<cli_secret>` | base64
`curl -X DELETE https://<server>/api/v2.0/projects/<project>/repositories/<repository> -H 'accept: application/json' -H 'Authorization: Basic <token>'

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.11
- docker engine version: n/a
- docker-compose version: n/a

**Comment by Kajot-dev** [comment]
What kind of user did you use? Admin? Robot account? Regular user? Do you use OIDC as auth provider?

**Comment by aweng-aria** [comment]
I used a 'Project Admin' account.  We login using GitLab credentials, and I used my username + CLI secret from the web UI.

**Comment by zyyw** [comment]
> We login using GitLab credentials, and I used my username + CLI secret from the web UI.
Could you please elaborate a little bit on this? 

Also could you please also try to run the following command:
```
curl -k -X GET <harbor-endpoint>/api/v2.0/projects/<your_project>/summary -H 'accept: application/json' -H 'Authorization: Basic <your_token>'
```
if the output is like below:
```
{"repo_count":1}
```
then the `Project Admin` you are using might not being set up properly. When a project admin is set up properly, it should be something like this:
```
{"project_admin_count":2,"quota":{"hard":{"storage":-1},"used":{"storage":2808536}},"repo_count":1}
```
There will be more details of the response to the <project>/summary request.

**Comment by zyyw** [comment]
If I understand correctly, you are using `Gitlab` as the OIDC provider. Please refer this page to access harbor api:
* https://github.com/goharbor/harbor/wiki/Harbor-FAQs

search `My Harbor is configured to use OIDC for authentication, how do I access Harbor's API?`
