### ISSUE TITLE
添加复制规则报错

### ISSUE THREAD

**Issue by fighting-123456** [goharbor/harbor#20767]
页面报internal server error
接口/api/v2.0/registries/0/info 返回500
core日志中报[{"code":"UNKNOWN","message":"unknown: invalid character '\u003c' looking for beginning of value"}]

**Comment by fighting-123456** [comment]
镜像同步失败：failed create adapter for destination registry http://10.33.9.2:8180 invaid character '>' looking for beginning of value

**Comment by chlins** [comment]
Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?

**Comment by fighting-123456** [comment]
> Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?

adapter type is harbor

**Comment by fighting-123456** [comment]
> > Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?
> 
> adapter type is harbor

jobservice有报错trigger hook event error: Post "http://core:8080/service/notifications/tasks/2": dial tcp: lookup core on 10.32.192.2:53: no such host
但是我已经在jobservice的env中改了CORE_URL变量，感觉jobservice没有读这个变量

**Comment by MinerYang** [comment]
1. Which version of the src and target harbor registry?
2. id=0 is the local registry, not the one you created for replication, please try id=1 as well 
```
curl -u '<admin>:<password>'  http://<src-harbor registry>/api/v2.0/registries/1
```
3. Please copy paste whole harbor-core logs... will appreciate is if it's not typing by yourself(typo there)

**Comment by MinerYang** [comment]
> > > Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?
> > 
> > 
> > adapter type is harbor
> 
> jobservice有报错trigger hook event error: Post "http://core:8080/service/notifications/tasks/2": dial tcp: lookup core on 10.32.192.2:53: no such host 但是我已经在jobservice的env中改了CORE_URL变量，感觉jobservice没有读这个变量

Please set external_url if you want to enable external proxy

**Comment by fighting-123456** [comment]
> make sure all the harbor pods is healthy and if issue still exist **Please copy paste whole related harbor-core logs** ... will appreciate if it's not typing by yourself(typo there)

Sorry, my English is not very good. I will do my best
The states of the harbor components are all healthy
harbor-core logs :[/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: invalid character '\u003c' looking for beginning of value"}]}

**Comment by zyyw** [comment]
> > > Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?
> > 
> > 
> > adapter type is harbor
> 
> jobservice有报错trigger hook event error: Post "http://core:8080/service/notifications/tasks/2": dial tcp: lookup core on 10.32.192.2:53: no such host 但是我已经在jobservice的env中改了CORE_URL变量，感觉jobservice没有读这个变量

May I kindly ask how you update the CORE_URL in jobservice env? normally we don't need to update this `CORE_URL` manually. If you are pretty sure of updating it, maybe you need to restart harbor after doing so to make it take effect.

**Comment by fighting-123456** [comment]
> > > > Is the target registry `http://10.33.9.2:8180/` accessible and what is the adapter type of your registry?
> > > 
> > > 
> > > adapter type is harbor
> > 
> > 
> > jobservice有报错trigger hook event error: Post "http://core:8080/service/notifications/tasks/2": dial tcp: lookup core on 10.32.192.2:53: no such host 但是我已经在jobservice的env中改了CORE_URL变量，感觉jobservice没有读这个变量
> 
> May I kindly ask how you update the CORE_URL in jobservice env? normally we don't need to update this `CORE_URL` manually. If you are pretty sure of updating it, maybe you need to restart harbor after doing so to make it take effect.

Let me explain the deployment background:

Deploying offline, version 2.8.6. Due to issues with our Docker environment, when using bridged network mode, the container cannot communicate with the host network. Therefore, after executing install.sh, I manually changed docker-compose.yaml, changed the container network to host mode, and also changed the listening ports and addresses of all components. Finally, I executed docker-compose down and docker-compose up
