### ISSUE TITLE
Harbor initialization startup error

### ISSUE THREAD

**Issue by carefree666** [goharbor/harbor#20762]
Environmental information：
  Operating system：Centos7   
  Kernel version：3.10.0-1160.71.1.el7.x86_64
  Docker version: 20.10.10
  Harbor version：v2.9.0
Error message：
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/d49c3374-e99f-4e6a-8bcb-8cd61e8cf50d">

Error log：
(1)docker logs --tail 100 harbor-jobservice

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f25afd9eb2c
stack: frame={sp:0x7ffdc4d4b000, fp:0x0} stack=[0x7ffdc454c480,0x7ffdc4d4b490)
0x00007ffdc4d4af00:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af10:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af20:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af30:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af40:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af50:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af60:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af70:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af80:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af90:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afa0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afb0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afc0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afd0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afe0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4aff0:  0x0000000000000000  0x00007f25afd9eb1e 
0x00007ffdc4d4b000: <0x0000000000000000  0xf2cb5a5496f18e00 
0x00007ffdc4d4b010:  0x0000000000000006  0x00007f25afd11740 
0x00007ffdc4d4b020:  0x00007ffdc4d4b2d0  0x000000000000002c 
0x00007ffdc4d4b030:  0x00000000021f0d80  0x00007f25afd4fef2 
0x00007ffdc4d4b040:  0x00007f25afee7e70  0x00007f25afd3a472 
0x00007ffdc4d4b050:  0x0000000000000020  0x0000000000000000 
0x00007ffdc4d4b060:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b070:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b080:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b090:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0a0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0b0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0c0:  0x00007f25afee7680  0x000000000000000a 
0x00007ffdc4d4b0d0:  0x00007f25afd11740  0x00007f25afd9166a 
0x00007ffdc4d4b0e0:  0x00007f25afee7840  0xf2cb5a5496f18e00 
0x00007ffdc4d4b0f0:  0x00007f25afee7840  0x00007f25afee7840 
runtime: g 0: unknown pc 0x7f25afd9eb2c
stack: frame={sp:0x7ffdc4d4b000, fp:0x0} stack=[0x7ffdc454c480,0x7ffdc4d4b490)
0x00007ffdc4d4af00:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af10:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af20:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af30:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af40:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af50:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af60:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af70:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af80:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4af90:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afa0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afb0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afc0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afd0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4afe0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4aff0:  0x0000000000000000  0x00007f25afd9eb1e 
0x00007ffdc4d4b000: <0x0000000000000000  0xf2cb5a5496f18e00 
0x00007ffdc4d4b010:  0x0000000000000006  0x00007f25afd11740 
0x00007ffdc4d4b020:  0x00007ffdc4d4b2d0  0x000000000000002c 
0x00007ffdc4d4b030:  0x00000000021f0d80  0x00007f25afd4fef2 
0x00007ffdc4d4b040:  0x00007f25afee7e70  0x00007f25afd3a472 
0x00007ffdc4d4b050:  0x0000000000000020  0x0000000000000000 
0x00007ffdc4d4b060:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b070:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b080:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b090:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0a0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0b0:  0x0000000000000000  0x0000000000000000 
0x00007ffdc4d4b0c0:  0x00007f25afee7680  0x000000000000000a 
0x00007ffdc4d4b0d0:  0x00007f25afd11740  0x00007f25afd9166a 
0x00007ffdc4d4b0e0:  0x00007f25afee7840  0xf2cb5a5496f18e00 
0x00007ffdc4d4b0f0:  0x00007f25afee7840  0x00007f25afee7840 

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:463 fp=0xc000066780 sp=0xc000066778 pc=0x46b9a0
runtime.main()
        /usr/local/go/src/runtime/proc.go:170 +0x6d fp=0xc0000667e0 sp=0xc000066780 pc=0x43c3ed
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x46dbc1

rax    0x0
rbx    0x1
rcx    0x7f25afd9eb2c
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x7f25afd11740
rsp    0x7ffdc4d4b000
r8     0x0
r9     0x73
r10    0x8
r11    0x246
r12    0x6
r13    0x2c
r14    0x21f0d80
r15    0x1
rip    0x7f25afd9eb2c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

(2)The registryctl and harbor-core  log content is similar to harbor-jobservice

(3) docker logs --tail 100 harbor-db
upgrade DB from 13 to 14
popen failure: Cannot allocate memory
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/pgsql/14/bin/initdb".
Check your installation.

(4)docker logs --tail 100 redis
1:C 22 Jul 2024 11:35:58.109 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 22 Jul 2024 11:35:58.109 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 22 Jul 2024 11:35:58.109 # Configuration loaded
1:M 22 Jul 2024 11:35:58.110 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.12 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 22 Jul 2024 11:35:58.110 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 22 Jul 2024 11:35:58.110 # Server initialized
1:M 22 Jul 2024 11:35:58.110 # Fatal: Can't initialize Background Jobs.

What causes this？

**Comment by zyyw** [comment]
Please refer to this issue:
* https://github.com/goharbor/harbor/issues/19141

As you are using `Operating system：Centos7` and `Docker version: 20.10.10` and `Harbor version：v2.9.0`, maybe try to `Upgrading docker-ce to the latest version`, according to this [comment](https://github.com/goharbor/harbor/issues/19599#issuecomment-1838724695).

**Comment by carefree666** [comment]
> Please refer to this issue:
> 
> * [DB init error: popen failure: Cannot allocate memory #19141](https://github.com/goharbor/harbor/issues/19141)
> 
> As you are using `Operating system：Centos7` and `Docker version: 20.10.10` and `Harbor version：v2.9.0`, maybe try to `Upgrading docker-ce to the latest version`, according to this [comment](https://github.com/goharbor/harbor/issues/19599#issuecomment-1838724695).

I tried to upgrade the docker version, but it didn't work
docker verison 27.1.1

**Comment by zyyw** [comment]
> > Please refer to this issue:
> > 
> > * [DB init error: popen failure: Cannot allocate memory #19141](https://github.com/goharbor/harbor/issues/19141)
> > 
> > As you are using `Operating system：Centos7` and `Docker version: 20.10.10` and `Harbor version：v2.9.0`, maybe try to `Upgrading docker-ce to the latest version`, according to this [comment](https://github.com/goharbor/harbor/issues/19599#issuecomment-1838724695).
> 
> I tried to upgrade the docker version, but it didn't work docker verison 27.1.1

Could you please share with us the output of `docker version`?
Additionally, how about try to upgrade to the latest version of 2.10.x, per this [comment](https://github.com/goharbor/harbor/issues/19680#issuecomment-1851677149) ?

**Comment by zyyw** [comment]
please also refer this issue:
* https://github.com/timescale/timescaledb-docker-ha/issues/260

It may have something to do with your runc version as well.

**Comment by zyyw** [comment]
btw, the jobservice log and redis log may related to the CentOS, we mainly tested it on ubuntu.

**Comment by carefree666** [comment]
> please also refer this issue:
> 
> * [Docker image fails during initdb timescale/timescaledb-docker-ha#260](https://github.com/timescale/timescaledb-docker-ha/issues/260)
> 
> It may have something to do with your runc version as well.

runc 版本从 1.0.0 升级到 1.2.0 解决了 感谢

**Comment by carefree666** [comment]
> please also refer this issue:
> 
> * [Docker image fails during initdb timescale/timescaledb-docker-ha#260](https://github.com/timescale/timescaledb-docker-ha/issues/260)
> 
> It may have something to do with your runc version as well.

runc version upgrade from 1.0.0 to 1.2.0 solved thanks

**Comment by carefree666** [comment]
> please also refer this issue:
> 
> * [Docker image fails during initdb timescale/timescaledb-docker-ha#260](https://github.com/timescale/timescaledb-docker-ha/issues/260)
> 
> It may have something to do with your runc version as well.

runc version upgrade from 1.0.0 to 1.2.0 solved thanks
