### ISSUE TITLE
Helm + Kustomize - Harbor components redeploys with other components 

### ISSUE THREAD

**Issue by rajatrj16** [goharbor/harbor#20770]
I have multiple replicas of harbor components. manually scale any component up and down(Test), it also terminates/restarts core and registry pods.

I tried locally with `helm + kustomize` and able to reproduce this issue. (We're using kustomize for argocd and patches)

Prereq: Have a local minikube/kind cluster

**Step 1:** Create a `kustomization.yaml` [kustomization.txt](https://github.com/user-attachments/files/16361794/kustomization.txt) rename `.txt -> .yaml`

**Step 2:** Apply the manifest to cluster - Keep the kustomize file on the root on the folder and run below command
```
kustomize build --enable-helm  | kubectl apply -f -
```
This will deploy harbor locally wait 5-7 mins for running status for all components

**Step 3:** Make changes to replicas for any component i.e. updates jobservice replica to 5
```    
jobservice:
    replicas: 2 --> 5
```      
**Step 4:** Run apply again 
```
kustomize build --enable-helm  | kubectl apply -f -
```
**This will deploy new changes and `configured` other `deployment components`**
» kustomize build --enable-helm  | kubectl apply -f -

> configmap/harbor-registry-core unchanged
> configmap/harbor-registry-exporter-env unchanged
> configmap/harbor-registry-jobservice unchanged
> configmap/harbor-registry-jobservice-env unchanged
> configmap/harbor-registry-portal unchanged
> configmap/harbor-registry-registry unchanged
> configmap/harbor-registry-registryctl configured
> secret/harbor-registry-core configured
> secret/harbor-registry-database unchanged
> secret/harbor-registry-exporter unchanged
> secret/harbor-registry-ingress configured
> secret/harbor-registry-jobservice configured
> secret/harbor-registry-registry configured
> secret/harbor-registry-registry-htpasswd configured
> secret/harbor-registry-registryctl configured
> secret/harbor-registry-trivy unchanged
> service/harbor-registry-core unchanged
> service/harbor-registry-database unchanged
> service/harbor-registry-exporter unchanged
> service/harbor-registry-jobservice unchanged
> service/harbor-registry-portal unchanged
> service/harbor-registry-redis unchanged
> service/harbor-registry-registry unchanged
> service/harbor-registry-trivy unchanged
> persistentvolumeclaim/harbor-registry-jobservice unchanged
> persistentvolumeclaim/harbor-registry-registry unchanged
> deployment.apps/harbor-registry-core configured
> deployment.apps/harbor-registry-exporter configured
> deployment.apps/harbor-registry-jobservice configured
> deployment.apps/harbor-registry-portal unchanged
> deployment.apps/harbor-registry-registry configured
> statefulset.apps/harbor-registry-database configured
> statefulset.apps/harbor-registry-redis configured
> statefulset.apps/harbor-registry-trivy configured
> ingress.networking.k8s.io/harbor-registry-ingress unchanged

![image](https://github.com/user-attachments/assets/447c1c05-59c1-482e-b6f1-5bc6cc7bb787)
![image](https://github.com/user-attachments/assets/2fab28a1-2eba-47ab-84fb-23140f188184)

**Comment by Kajot-dev** [comment]
This will happen, because there are some secret values that need to be set. Helm chart generates them if there are none and tries to reuse them by using `lookup` - but `lookup` does not work with kustomize. Please properly configure all secret values in `values.yaml` (`core.secretKey`, db password, etc).

And this issue probably should be in https://github.com/goharbor/harbor-helm
