### ISSUE TITLE
Not able to assign roles and users to the groups

### ISSUE THREAD

**Issue by ujala-singh** [goharbor/harbor#20780]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
1. I want to assign roles to groups that I have created on harbor but I am not able to do it, I can just create Users.
2. I want to assign users to groups that I have created on harbor but I am not able to do it, I can just create Users.

**Versions:**
v2.11.0

- harbor version: [v2.11.0]

**Additional context:**
<img width="1500" alt="Screenshot 2024-07-26 at 10 11 21 PM" src="https://github.com/user-attachments/assets/8bfff9d8-d243-48bf-8624-fdc98f30fa4b">

**Comment by Kajot-dev** [comment]
You assign roles to groups on the project level, in the "members" tab, not here

**Comment by ujala-singh** [comment]
And how can I assign users to the groups?

**Comment by Kajot-dev** [comment]
I see you are using OIDC, this is done via groups claim which can be configured in OIDC settings. Groupa must be set on the OIDC provider side. Groups will be created and assigned to users autpmatically as they log in

**Comment by ujala-singh** [comment]
@Kajot-dev I tried to do that via OIDC server, but it's failing. I have raised an issue for that as well here https://github.com/goharbor/harbor/issues/20779

**Comment by zyyw** [comment]
let's we use this issue to track it:
* https://github.com/goharbor/harbor/issues/20779
