### ISSUE TITLE
Expose harbor under two different urls

### ISSUE THREAD

**Issue by emagiz** [goharbor/harbor#20782]
**Problem description**
We are trying to expose harbor under two different urls which does not seem possible to do in the chart.

**Feature request**
I would like to be able to include two urls under the ingress hosts in the values file and have it create the ingress rules using both hosts

Example of how it could look like in the values file:
`  ingress:
     hosts
      core: url1
      core_other: url2`

**Comment by stonezdj** [comment]
current Harbor doesn't support it
