### ISSUE TITLE
LFX Mentorship - Term 03 - 2024 September - October

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#20790]
The Harbor Satellite Project is again looking for a mentee for the Harbor CLI project.

Timeline: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/03-Sep-Nov

mentee applications open | Jul 31 - Aug 13 5:00 PM PDT

## Scope
Build and develop new features for Harbor Satellite.
Releasing first usable version

**Comment by kunal-511** [comment]
Hi @Vad1mo , I came across your project idea for LFX and found it truly captivating. I'd love to learn more about it and explore ways to contribute. Additionally, I'm considering applying for the LFX program for term 3, with the goal of working on this project. Could you please share some insights and details about the project, such as its objectives, requirements, and expected outcomes? I'm excited about the possibility of collaborating with you and the team!

**Comment by Shruti78** [comment]
hi @Vad1mo , I gone through your repository and quite interested in contributing in your project. It would be great if you could share some information and necessity required to work for this repo.

**Comment by ayu-ch** [comment]
Hey @Vad1mo this project aligns perfectly with my interests, and I’m eager to contribute. I would greatly appreciate it if you could share any relevant resources to help me get started.
