### ISSUE TITLE
Trivy scanner is unhealthy

### ISSUE THREAD

**Issue by HamzaZoubair** [goharbor/harbor#20792]
We are using bitnami harbor helm chart https://github.com/bitnami/charts/blob/main/bitnami/harbor/values.yaml version 22.0.8. 
The status of Trivy scanner is unhealthy, and scan of artifacts can not be launched. 
On Trivy pod we can't see any error. 

- harbor version: 2.11.0

**Comment by stonezdj** [comment]
We didn't maintain the bitnami Harbor helm chart.
Did you try to reproduce the same issue with harbor-helm? https://github.com/goharbor/harbor-helm
