### ISSUE TITLE
harbor nginx-photon container constantly restarting

### ISSUE THREAD

**Issue by lyanwaltz** [goharbor/harbor#20796]
AWS instance - rocky linux8
Docker v20.10.7
Harbor v2.2.1

I installed harbor but it can't get connected.
harbor nginx-photon container constantly restarting.
This is the docker logs below

2024/07/31 09:04:46 [emerg] 1#0: host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
2024/07/31 09:05:46 [emerg] 1#0: host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
2024/07/31 09:06:47 [emerg] 1#0: host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
2024/07/31 09:07:47 [emerg] 1#0: host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23
nginx: [emerg] host not found in upstream "core:8080" in /etc/nginx/nginx.conf:23

somebody know about this issue?

#harbor
#rockylinux
#docker

**Comment by stonezdj** [comment]
The latest Harbor version is 2.11.0, please try the latest.

**Comment by wy65701436** [comment]
close as v2.2 is out of support.
