### ISSUE TITLE
Can harbor support specifying the container "time zone"?

### ISSUE THREAD

**Issue by skycyan** [goharbor/harbor#20807]
The docker-compose.override.yml file is a feature of Docker Compose that allows you to add to or override configuration in docker-compose.yml and is automatically loaded when you run the docker-compose command.
I use "docker-compose.override.yml" to implement external time zone. In the end, only harbor-core, harbor-jobservice, and harbor-exporter containers support changing time zone from /etc/localtime. Other containers do not have tzdate service and do not support changing time zone by /etc/localtime.
Can harbor support tzdate in the provided image? Or use other methods to support changing time zone for harbor?

`
# cat docker-compose.override.yml 
version: '2.3'
services:
  log:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  registry:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  registryctl:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  postgresql:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  core:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  portal:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  jobservice:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  redis:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  proxy:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
  exporter:
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
`

**Comment by stonezdj** [comment]
What is the purpose of changing the time zone settings of the container? Harbor stores the time in UTC in the database. and it displays the time with the local timezone.
