### ISSUE TITLE
Scan button for an image is continuously spinning when no scanner is added to the harbor registry

### ISSUE THREAD

**Issue by mehulgogri** [goharbor/harbor#20805]
Upgraded harbor to the latest v2.11.0-70255684 release. I had deleted all the scanners from the Interrogation service before doing the upgrade. Navigated to the repository image page and the scan button was continuously spinning for the image.

![image](https://github.com/user-attachments/assets/8953c7c5-be01-475a-958d-2045385b0b5f)

**Comment by zyyw** [comment]
dup of https://github.com/goharbor/harbor/issues/20615
