### ISSUE TITLE
Harbor stuck in infinite loading

### ISSUE THREAD

**Issue by theeexavier** [goharbor/harbor#20813]
**Expected behavior**
Harbor startup without any issues and URL is reachable.

**Actual behavior:**
After Harbor startup, we're stuck in an infinite loading screen. We also have an error on the scripts js file.
![HarborIssue](https://github.com/user-attachments/assets/569e45ff-da6e-47d5-aa93-0dcbb2a78281)

**Steps to reproduce the problem:**
This is random at startup, usually when a new Node comes up.

**Versions:**
- harbor version: v2.12.0-e0b94aa7
- Chart version 1.13.0

**Additional context:**
Currently no log files as this was an incident and we had to terminate the node so a new one was generated.

**Comment by zyyw** [comment]
Hi @theeexavier , the version info from this issue's description seems to be inconsistent.
Harbor  version v2.12.0 is not released yet, and it's branch in both goharbor/harbor and goharbor/harbor-helm is `main` branch.
The corresponding Harbor version of Harbor-helm version 1.13.0 is v2.9.5. Could you please double check this info?

**Comment by theeexavier** [comment]
Hello, from the about page I can see the following:
![imagem](https://github.com/user-attachments/assets/dd3b4694-c5f5-46bc-935f-9118271f49e1)
 Harbor
Version v2.12.0-eb5193e0

**Comment by DaanSelen** [comment]
I also have this issue.
![image](https://github.com/user-attachments/assets/aae0882b-f1f2-4194-99e3-8b255d60d065)

It reports a succesfull start

**Comment by w0112w** [comment]
I have this same issue. all services start successfully，but we're stuck in an infinite loading screen，such a long time。 URL is reachable.
harbor version: v2.11.1
