### ISSUE TITLE
proxy-cache bandwidth limit UI change

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20811]
Issue https://github.com/goharbor/harbor/issues/20589 will provide the feature of bandwidth limit for proxy-cache. This current issue is to discuss the UI change of configuring proxy-cache speed limit:

- configuring proxy-cache speed limit in the proxy-cache creation page
<img width="587" alt="Screenshot 2024-08-06 at 1 54 20 PM" src="https://github.com/user-attachments/assets/1d1a8703-6f06-4542-a1cb-69783cda5463">

- configuring proxy-cache speed limit in the project configuration page (like: auto_scan)
<img width="1030" alt="Screenshot 2024-08-06 at 1 56 17 PM" src="https://github.com/user-attachments/assets/1b71b3e9-c588-4433-a8d5-ae80c976bd23">

**Comment by kunal-511** [comment]
@zyyw @wy65701436  Can you please elaborate more on what UI changes needs to done in this??

**Comment by zyyw** [comment]
> @zyyw @wy65701436 Can you please elaborate more on what UI changes needs to done in this??

Essentially, we would like the page of creating ProxyCache project be able to set bandwidth limit like what have in the replication rule page (the first image in the description of this issue). 
<img width="1516" alt="Screenshot 2024-08-19 at 10 16 20 AM" src="https://github.com/user-attachments/assets/839dacb0-dd03-4d46-bf6f-02238516cbdc">

And also in the project configuration page, users are able to update the proxycache bandwidth limit if it is set.
<img width="1780" alt="Screenshot 2024-08-19 at 10 19 42 AM" src="https://github.com/user-attachments/assets/7870250c-669d-4f44-960d-9af1c4885b66">

@kunal-511 We really appreciate your help on this UI change! Please feel free to ping me on slack. `Cloud Native Computing Foundation` workspace, `#harbor` slack channel:
link: https://cloud-native.slack.com/archives/CC1E09J6S
slack channel member: Shengwen Yu  (https://cloud-native.slack.com/archives/D022C27PVS6)

**Comment by kunal-511** [comment]
Ok, I understood the UI changes. I will be working on this.

**Comment by kunal-511** [comment]
@zyyw 

Is this fine?    
![image](https://github.com/user-attachments/assets/9b751588-34d7-4752-8a7e-a75d9f3672f4)

**Comment by kofj** [comment]
backend change of bandwidth limit #20812 , great.
