### ISSUE TITLE
【建议】可以为代理的项目设置独立域名

### ISSUE THREAD

**Issue by xzxiaoshan** [goharbor/harbor#20829]
建议可以为代理的项目设置独立域名。

设置独立域名的项目，使用独立域名取代项目名称后缀。

例如：demo.harbor.com/dockerhub_proxy/nginx:latest 使用独立域名后  dockerproxy.harbor.com/nginx:latest

已经有开发者给出了使用 nginx 的配置方法，建议官方可以置入到默认版本中。

https://github.com/moby/moby/pull/34319#issuecomment-720606627

![image](https://github.com/user-attachments/assets/4c94adc9-1b24-489f-a52f-9fd940d7fd81)

**Comment by stonezdj** [comment]
It is not feasible to implement. because Harbor only support one FQDN so far.

**Comment by xzxiaoshan** [comment]
@stonezdj 自己新增nginx 配置可以实现。并总结了帖子：[https://blog.csdn.net/catoop/article/details/141125757](https://blog.csdn.net/catoop/article/details/141125757?spm=1001.2014.3001.5501)

如果 harbor 官方提供配置，通过修改配置同步nginx 配置就更好了。

虽然 harbor 的 FQDN 只有一个，但是如果域名证书是子域名通配符的，可以允许 下级子域名访问啊，用户只需要自己配置一下 dns 映射即可。

子域名可以固定格式，不需要用户填写。例如 harbor.test.com 为harbor 的 FFQDN，则项目 dockerhub-proxy 项目自动为 dockerhub-proxy.harbor.test.com，这样既能解决证书问题，也不用用户填入域名。

**Comment by xzxiaoshan** [comment]
只所以提出这个问题，并给出方法建议。
1、一方面是issue 中有更多人提出，大家自己想办法变通应用了，例如使用 nginx。  
2、另外一方面在 k8s 中，可以自定义私服 FQDN，但是有些版本不允许配置 harbor.test.com/dockerhub-proxy ，因为它不是一个 FQDN 规范。而如果不带 dockerhub-proxy 这一段，又会导致从默认镜像库 docker.io 等代理的镜像不能被正常下载，实际地址变成 harbor.test.com/rancher/xxxx:latest

结论：某些 k8s 应用场景中，必须使用独立域名的私服，harbor 目前不具备这个条件。特提出harbor为项目分配子域名的方案。

**Comment by xzxiaoshan** [comment]
@stonezdj 所以，我认为能自动为 harbor 的项目，自动基于 harbor 的主 FQDN 自动以项目名称作为子域名，是一个不错的想法，期待实现。谢谢。

**Comment by xzxiaoshan** [comment]
I have submitted a formal proposal.

https://github.com/goharbor/harbor/issues/20849
