### ISSUE TITLE
配置mysql8，不生效

### ISSUE THREAD

**Issue by wenlicheng** [goharbor/harbor#20836]
我想把plsql，变成mysql8，具体怎末实现

**Comment by wy65701436** [comment]
Basically, you have to add a new DB implementation for each of the DAO interface.

**Comment by wenlicheng** [comment]
> 基本上，您必须为每个 DAO 接口添加一个新的 DB 实现。
具体该如何实现？？
大神请帮，拜托拜托

**Comment by chlins** [comment]
A previous draft PR for supporting mysql: https://github.com/goharbor/harbor/pull/16615
