### ISSUE TITLE
Add customizable `look and feel` for portal

### ISSUE THREAD

**Issue by baldarn** [goharbor/harbor#20847]
**Is your feature request related to a problem? Please describe.**
I would like to customize the `docker-compose` with the `install.sh` script. 

I would like to customize the UI via docker compose for my instance of Harbor

I would like also to customize this parameters with the `harbor.yml` file

**Describe the solution you'd like**
Add configurations to `harbor.yml` file, then to be used from the `docker-compose.yml` and the `helm` system

**Describe the main design/architecture of your solution**
Using the current architecture of the system

**Describe the development plan you've considered**
ND

**Additional context**

**Comment by MinerYang** [comment]
You could fork the repo do the customization

**Comment by baldarn** [comment]
> You could fork the repo do the customization

this pr should allow everyone to easily customize UI with the installer script.

later we could also update the docs with such function
