### ISSUE TITLE
 How to get harbor logs

### ISSUE THREAD

**Issue by tnubeo1111** [goharbor/harbor#20859]
Hello Team,

Currently I have built Harbor with version 2.10 using Helm.

My wish is if there are any options to get Harbor's logs out.

![image](https://github.com/user-attachments/assets/0dc72dea-9a5a-4704-9239-c448ba9fe037)

**Comment by kofj** [comment]
Access log?

**Comment by tnubeo1111** [comment]
I need audit log

**Comment by tnubeo1111** [comment]
Can you tell me where the harbor's logs file is saved? I'm using helm but don't want to use kubectl logs to read logs. Please can you tell me where the logs file is located?
