### ISSUE TITLE
[Documentation] demo.goharbor.io: could not create an account

### ISSUE THREAD

**Issue by antmak** [goharbor/harbor#20860]
I tried to fellow https://goharbor.io/docs/2.11.0/install-config/demo-server/  **"Access the Demo Server"** but blocked  with creating a test account. The Sign Up form doesn't allow me to continue because of the validation fields

![image](https://github.com/user-attachments/assets/1ce9360e-9819-4f70-997e-278cf2fe9a84)

Any other USERNMAE and EMAIL are not acceptable

**Comment by tuxpeople** [comment]
@antmak They had an issue yesterday with the demo instance. It's healthy now and I was able to register an account. Could you try again?

**Comment by antmak** [comment]
thanks, it works for me now
