### ISSUE TITLE
Access ID and Secret for replication to another harbor instance

### ISSUE THREAD

**Issue by cwrx777** [goharbor/harbor#20874]
What should be the Access ID and Secret for replicating to another harbor instance?

Reference:
https://goharbor.io/docs/2.11.0/administration/configuring-replication/create-replication-endpoints/#access-id-and-secret-configuration

I have configured with the username and password of an existing account in the other harbor instance, and the account is a 'maintainer', but the UI keep showing 'Failed to ping to endpoint'.

In the other instance, I have also added a registry endpoint with the endpoint URL is its own instance, and it's still failed to ping.
the account can be used to login to portal. 

error message in the core module:
```
failed to ping registry https://url: http status code: 401, body:
```

if I purposely use wrong credentials: the body will contain
```json
{ "errors": [{ "code": "UNAUTHORIZED", "message": "unauthorized: unauthorized" }]}
```

**Comment by JeanRessouche** [comment]
Use a password with 12 characters max, without special characters and it should work.
