### ISSUE TITLE
REST API response typo

### ISSUE THREAD

**Issue by starkodder** [goharbor/harbor#20889]
The REST API endpoint `/api/v2.0/users` returns `{"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorize"}]}`, but message should be "UnAuthorized" which the other enpoints returns, not "UnAuthorize".

**Comment by wy65701436** [comment]
hi @starkodder can you share the version of harbor that you're using?

**Comment by starkodder** [comment]
Version v2.2.1-b0d63082, I sent a GET to `https://registry.hafas.de/api/v2.0/users`, the other enpoints are working.
