### ISSUE TITLE
https://goharbor.io/docs/2.11.0/install-config/run-installer-script/ not synced with REPO

### ISSUE THREAD

**Issue by lekpamartin** [goharbor/harbor#20895]
For exemple 

In the website 
Stop Harbor.
docker-compose down -v

In the REPO
Stop Harbor.
docker compose down -v

If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
can you point me the location of repo where you see the `docker compose down -v `?

**Comment by lekpamartin** [comment]
This is a mistake on my part. I thought I saw this in the repo

But it is a good idea to to use "docker compose" instead of "docker-compose"
