### ISSUE TITLE
harbor on vsphere

### ISSUE THREAD

**Issue by lidoror** [goharbor/harbor#20890]
Hi,
I just installed the virutal integrated container and tried logging into harbor but all the login combination I tried are resulting in invalid user and password
what can I do?
what are the default user and password for harbor on vic?

**Comment by MinerYang** [comment]
Have you hade a chance try `admin`? password would be specified in your `harbor.yml`

**Comment by lidoror** [comment]
If I am using the default install from the ova of the Vic the value still in the yaml?
And if yes what's the default location of the yaml?
Also it's worth mentioning that I used ssh to login into the Vic ova and i didn't find Kubectl but i did saw docker installed and harbor containers running.

**Comment by wy65701436** [comment]
@lidoror as I know, the vic product is not of support now, and you can try to open issue at their repository. And this repository is the harbor OSS issue, if you don't mind, I will close it.
