### ISSUE TITLE
https.certificate/private_key set in harbor.yml, but missing in docker-compose.py

### ISSUE THREAD

**Issue by dev-zero** [goharbor/harbor#20899]
**Expected behavior and actual behavior:**

When setting `https.certificate` and `https.private_key` in `harbor.yml`, `prepare` should write corresponding mount configuration in `docker-compose.yml`, but it does not.

**Steps to reproduce the problem:**

Enable `https` and set `certificate` and `private_key` to a path on the local filesystem

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.11.1
- docker engine version: -
- docker-compose version: -

**Additional context:**

Relevant code part in `utils/docker_compose.py`: https://github.com/goharbor/harbor/blob/108fa9e1016f98bc6ab2f63d0b5c928ac0c0ccbd/make/photon/prepare/utils/docker_compose.py#L38-L42

And the matching template section where those vars are **not** used: https://github.com/goharbor/harbor/blob/108fa9e1016f98bc6ab2f63d0b5c928ac0c0ccbd/make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja#L288-L334

**Comment by wy65701436** [comment]
can you clarify the statement?
