### ISSUE TITLE
replication get a lot of 401 errors, when two harbor instances are using the same redis

### ISSUE THREAD

**Issue by 601431194** [goharbor/harbor#20908]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We built a harbor primary and backup cluster (v2.11.0) based on docker-compose, using shared storage、external redis and postgres. userd to replace older versions of non-highly available harbor clusters (v2.2.2); But when we try to copy the mirrored data from the original repository by replication，we get a lot of 401 error:
When the primary and backup instances are using different redis, this issue does not come up again, what confuses me is that in the helm deployment scenario, the harbor cluster is using the same redis, so should we have each harbor instance using a different redis? Is this going to be a problem
![image](https://github.com/user-attachments/assets/933fb120-8c43-4040-ba62-1baf132d018f)
![image](https://github.com/user-attachments/assets/0e6a7ad0-ebfd-4639-8917-bdd386fb98e0)

**Steps to reproduce the problem:**
harbor primary and backup cluster use same redis cluster,  Then configure the replication rules to replicate the mirrored data from the external harbor
The deployment architecture is similar to the following diagram
![image](https://github.com/user-attachments/assets/fc5727cc-5c07-4ac0-b503-b6705fdd4479)

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.11.0
- docker engine version: v25.0.3
- docker-compose version: v2.29.2
- redis: 7.2.5
- postgre: 14.13
--

**Additional context:**
error log of jobserver
![image](https://github.com/user-attachments/assets/a167c803-6172-4fae-95b3-052db05bb3c6)

**Comment by 601431194** [comment]
Supplement:

**Comment by stonezdj** [comment]
The 401 error indicates authorization, you should check the harbor core.log if the same user is trying to login Harbor with wrong password.

**Comment by 601431194** [comment]
> The 401 error indicates authorization, you should check the harbor core.log if the same user is trying to login Harbor with wrong password.

Thanks for the reply, I don't think the problem is with wrong password, since I changed the configuration to use a different jobservice_db_index for the two instances, there was no problem again. But I don't know why,

**Comment by Vad1mo** [comment]
I suspect the config of your two harbor instances is not correct. maybe not the same secrets.. Resulting in one instance can't read what the other wrote.

**Comment by 601431194** [comment]
> I suspect the config of your two harbor instances is not correct. maybe not the same secrets.. Resulting in one instance can't read what the other wrote.

I compared the configuration files of the two examples and they are identical

**Comment by 601431194** [comment]
> I suspect the config of your two harbor instances is not correct. maybe not the same secrets.. Resulting in one instance can't read what the other wrote.

Thanks, You are right, I checked the in-container environment variables and found that even though the harbor.yml is the same for both instances, the in-container environment variables are not the same (JOBSERVICE_SECRET, CORE_SECRET, etc.).
After we built the replica based on the common folder of the master node, the issue did not recur. So the cause of the problem is that we should not execute install.sh for each instance.
Note: It is important to note that you need to keep the owner when copying the common folder, otherwise it will cause docker-compose up execution to fail

**Comment by 601431194** [comment]
Building a standby node based on the common folder of the master node solves the problem, so close this issue
