### ISSUE TITLE
Image push to Harbor registry takes a minimum of 30min and can go upto 45min also

### ISSUE THREAD

**Issue by nanarun13** [goharbor/harbor#20904]
We have a Harbor registry setup using bitnami charts in our Kubernetes cluster. It uses Traefik as the ingress controller.

As per the traefik documentation, we have configured the ingress values.yaml. 

Initially for bigger images, when our Jenkins builds were executed, the stage where we run the image push to Harbor registry took a lot of time to do a docker push action and eventually would result in a timeout or throwing a "HTTP 499 Client Closed Request" error. After following a number of technical issues reported on similar issues in the internet, we made the below configuration changes to our ingress controller values.yaml file:

traefik:
-----------------
some code here
-----------------
  ports:
    web:
      address: ":80"
      forwardedHeaders:
        insecure: true
      http:
        redirections:
          entrypoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      forwardedHeaders:
        insecure: true
      transport:
        respondingTimeouts:
          readTimeout: 0s
          writeTimeout: 0s
          idleTimeout: 0s
-------------------------
some code here
-------------------------

WIth the above configuration, the frequent timeouts/http error 499 seems to have considerably reduced, making the image push action also successful, but unfortunately with a huge time duration( approx 30min-45min), which is way too high!!

Also, we do not see any errors in the postgresql DB pod logs or any of the other Harbor pods (registry, job service, exporter, etc)

Could you please help us in this regard? Any other configuration changes either in traefik or Harbor part required?

**Comment by wy65701436** [comment]
hi @nanarun13 please open issue to the bitnami chart repo to triage the ingress and network problem. If you ensure this question is caused inside the harbor application, then reopen it.
