### ISSUE TITLE
Harbor chart warehouse container reports panic null pointer

### ISSUE THREAD

**Issue by smallemployees** [goharbor/harbor#20917]
If you are reporting a problem, please make sure the following information are provided:
failed to check the existence of chart on the destination registry
**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
Do we need to clear cache information
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
v2.5.4
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by chlins** [comment]
The chartmuseum component has been deprecated and removed in the recent harbor releases, please consider migrating your charts to OCI compatible charts.  FYI: https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor
