### ISSUE TITLE
Change: Roadmap -> Project Board

### ISSUE THREAD

**Issue by Chr1s70ph** [goharbor/harbor#20924]
The main [Wiki page](https://github.com/goharbor/harbor/wiki) links to an outdated [Roadmap](https://github.com/goharbor/harbor/blob/major/ROADMAP.md) Page. It should be changed to the new [Roadmap](https://github.com/goharbor/harbor/blob/main/ROADMAP.md).

Also the main [Website](https://goharbor.io/community/) links to a [project board](https://github.com/orgs/goharbor/projects/1) which no longer exists.

And I'm sure there are more links throughout the project :)

**Comment by reasonerjt** [comment]
Thanks for the issue, we should clean it up.
