### ISSUE TITLE
Upgrading from 2.11.1 to 2.12.0 leads to Database Schema mismatch causing Internal Server Error on Robot Account Listing and Creation

### ISSUE THREAD

**Issue by shodanwashere** [goharbor/harbor#20945]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
- Expected: To be able to list and create robot accounts for projects on Harbor
- Actual: Robot accounts are not listed, with a warning for an "internal server error" showing up. Creating a robot account also results in an internal server error.

**Steps to reproduce the problem:**
Upgrading from 2.11.1 to 2.12.0, which has not been officially released yet. This happened due to not pinning the version for the chart being used, using the `latest` tag.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.12.0]
- kubernetes version: [1.30.1]

**Additional context:**

Upon inspecting logs on the core container, we saw these error messages:
```
2024-09-19T09:12:24.660262377Z 2024-09-19T09:12:24Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERROR: column t0.creator_ref does not exist (SQLSTATE 42703)"}]} 
2024-09-19T09:13:44.860329858Z 2024-09-19T09:13:44Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERROR: column \"creator_ref\" of relation \"robot\" does not exist (SQLSTATE 42703)"}]}
```

**Comment by stonezdj** [comment]
apply this change should work:

https://github.com/goharbor/harbor/blob/main/make/migrations/postgresql/0150_2.12.0_schema.up.sql

**Comment by shodanwashere** [comment]
Thank you @stonezdj! This worked!
