### ISSUE TITLE
can't cache big image ?

### ISSUE THREAD

**Issue by owanio1992** [goharbor/harbor#20940]
**Expected behavior and actual behavior:**
exec pull command, should see harbor cache have this image

```
docker pull harbor-local.timber.zndev.link/proxy-docker-hub/scylladb/scylla:5.2
```

**Versions:**

- harbor version: [v2.10.3]
- docker engine version: [27.2.1]

**Comment by chlins** [comment]
Please clarify your question and provide the harbor core logs.
