### ISSUE TITLE
When I do a docker push to a harbor exposed by a reverse proxy, the upload proceeds and a 403 error occurs.

### ISSUE THREAD

**Issue by uaysk** [goharbor/harbor#20950]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I expected the image to be uploaded via docker push, but a 403 error occurred after some layers were uploaded.

**Steps to reproduce the problem:**
After installing harbor via docker, expose it as a reverse proxy via nginx, and set external_url in harbor.yml.

The following output occurs (logged in to harbor as an admin account using docker login)

```
uaysk@ubuntu-1:~$ docker push harbor.mydomain/studynode/my-nodejs-app:1
The push refers to repository [harbor.mydomain/studynode/my-nodejs-app]
02650b0e0af6: Layer already exists 
145d894e9eef: Layer already exists 
2bce46cb0310: Layer already exists 
ed676bdad00f: Layer already exists 
820ae550c85c: Layer already exists 
adcdaae72f66: Layer already exists 
cee8a376a9a8: Pushing [==================================================>]  181.2MB
9d53c06a7e68: Layer already exists 
3a8081ce85fa: Pushing [===============>                                   ]    184MB/587.5MB
045d8b74bf0d: Pushing [=============================================>     ]  159.5MB/176.7MB
25879f85bbb0: Pushing [==================================================>]  49.61MB
6abe10f2f601: Pushing [==================================================>]  121.3MB
denied: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>NPMplus</center>
</body>
</html>
```

**Versions:**

- harbor version: [2.11.0]
- docker engine version: [27.0.3]
- docker-compose version: [2.28.1]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by stonezdj** [comment]
Can you please upload the proxy.log when pushing image?

**Comment by uaysk** [comment]
> Can you please upload the proxy.log when pushing image?

Thanks for the reply. It looks like it was a problem with the reverse proxy, not harbor. I was using nginx as a reverse proxy and had modsecurity enabled, disabling modsecurity fixed the problem.
