### ISSUE TITLE
Rate-limit github trivy java db

### ISSUE THREAD

**Issue by dan-m8t** [goharbor/harbor#20961]
Hey!

I am not sure why but I am running into github rate-limiting while trivy tries to scan artifacts.

For example:

```
2024-09-24T08:01:46Z	INFO	Java DB Repository	repository=ghcr.io/aquasecurity/trivy-java-db:1
2024-09-24T08:01:46Z	INFO	Downloading the Java DB...
2024-09-24T08:01:47Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:824a6e803d0ebe2f5d324553646132a59642acf01992b21e4799c9bf4218238a): post analysis error: post analysis error: Unable to initialize the Java DB: Java DB update failed: DB download error: OCI repository error: 2 errors occurred:
	* GET https://ghcr.io/token?scope=repository%3Aaquasecurity%2Ftrivy-java-db%3Apull&service=ghcr.io: DENIED: denied
	* GET https://ghcr.io/v2/aquasecurity/trivy-java-db/manifests/1: TOOMANYREQUESTS: retry-after: 496.655Âµs, allowed: 44000/minute
```

When I restart the trivy-adapter container manually it works again. Afaik the harbor.yml file states that trivy downloas the vuln db every 12 hours. I checked with our network team that the requests increased alot lately. 
This is my trivy config (pretty basic):

```
SCANNER_LOG_LEVEL=info
SCANNER_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_STORE_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_STORE_REDIS_NAMESPACE=harbor.scanner.trivy:store
SCANNER_JOB_QUEUE_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_JOB_QUEUE_REDIS_NAMESPACE=harbor.scanner.trivy:job-queue
SCANNER_TRIVY_CACHE_DIR=/home/scanner/.cache/trivy
SCANNER_TRIVY_REPORTS_DIR=/home/scanner/.cache/reports
SCANNER_TRIVY_VULN_TYPE=os,library
SCANNER_TRIVY_SEVERITY=UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
SCANNER_TRIVY_IGNORE_UNFIXED=False
SCANNER_TRIVY_SKIP_UPDATE=False
SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE=False
SCANNER_TRIVY_OFFLINE_SCAN=False
SCANNER_TRIVY_SECURITY_CHECKS=vuln
SCANNER_TRIVY_GITHUB_TOKEN=
SCANNER_TRIVY_INSECURE=False
SCANNER_TRIVY_TIMEOUT=5m0s
```

Harbor version is 2.11.0

Any hints besides adding a github token? This should not be neccessary imho.

thanks

**Comment by MinerYang** [comment]
Hi @dan-m8t ,
It is true that you are encounter the rate limit issue of ghcr. The trivy db should be downloaded every 12 hours. you could check the job by so:
```
kubectl exec -it <trivy-pod> /bin/bash

$ cat db/metadata.json 
{"Version":2,"NextUpdate":"2024-08-20T18:12:31.545773429Z","UpdatedAt":"2024-08-20T12:12:31.54577381Z","DownloadedAt":"2024-08-20T13:47:21.505746951Z"}

scanner [ ~/.cache/trivy ]$ cat java-db/metadata.json 
{"Version":1,"NextUpdate":"2024-08-23T01:05:23.967238833Z","UpdatedAt":"2024-08-20T01:05:23.967239003Z","DownloadedAt":"2024-08-20T13:47:48.12190157Z"}
```

If the reqeusting behavior different from what you got above, or it is trying to downloading the db every time scanning,  you should open an issue for trivy side
ref: - https://github.com/goharbor/harbor/issues/20961

**Comment by dan-m8t** [comment]
Thanks for your reply, this looks indeed weird to me:

```
scanner [ ~/.cache/trivy/db ]$ cat metadata.json
{"Version":2,"NextUpdate":"2024-09-25T12:15:38.238977725Z","UpdatedAt":"2024-09-25T06:15:38.238978116Z","DownloadedAt":"2024-09-25T06:21:07.805284628Z"}

scanner [ ~/.cache/trivy ]$ cat java-db/metadata.json
{"Version":1,"NextUpdate":"2024-09-23T01:06:28.762321626Z","UpdatedAt":"2024-09-20T01:06:28.762321776Z","DownloadedAt":"2024-09-25T11:30:09.6668578Z"}
```

java-db says next update on the 23.09 but today is 25.09. Trivy db looks like every 6 hours thus stated different in `harbor.yml` to update every 12 hours.

Could it be a probable solution to delete the cache/docker volume of trivy-adapter ? As I said I cannot remember to change any of these settings, see env above. 

To me this looks like java-db is outdated and it tries to fetch the new java-db? Maybe I will try it with the air-gapped solution as a workaround.

**Comment by wy65701436** [comment]
> Thanks for your reply, this looks indeed weird to me:
> 
> ```
> scanner [ ~/.cache/trivy/db ]$ cat metadata.json
> {"Version":2,"NextUpdate":"2024-09-25T12:15:38.238977725Z","UpdatedAt":"2024-09-25T06:15:38.238978116Z","DownloadedAt":"2024-09-25T06:21:07.805284628Z"}
> 
> scanner [ ~/.cache/trivy ]$ cat java-db/metadata.json
> {"Version":1,"NextUpdate":"2024-09-23T01:06:28.762321626Z","UpdatedAt":"2024-09-20T01:06:28.762321776Z","DownloadedAt":"2024-09-25T11:30:09.6668578Z"}
> ```
> 
> java-db says next update on the 23.09 but today is 25.09. Trivy db looks like every 6 hours thus stated different in `harbor.yml` to update every 12 hours.
> 
> Could it be a probable solution to delete the cache/docker volume of trivy-adapter ? As I said I cannot remember to change any of these settings, see env above.
> 
> To me this looks like java-db is outdated and it tries to fetch the new java-db? Maybe I will try it with the air-gapped solution as a workaround.

As for the details of trivy in terms of downloading db, can you open issue in the trivy side? Yes, to import the db manually is a workaround, but not the permanent solution.

**Comment by dan-m8t** [comment]
I tried with deleteting trivy-adapter container and volume. java-db pulled fine.

```
cat java-db/metadata.json
{"Version":1,"NextUpdate":"2024-09-29T00:19:52.416989567Z","UpdatedAt":"2024-09-26T00:19:52.416989828Z","DownloadedAt":"2024-09-26T00:54:32.314856278Z"}
```

We will see what will happen on 29th of September, if it will run into the rate-limit again or outdates I will open a issue at trivy, probably just some hiccup on my machine.

**Comment by madoe** [comment]
@dan-m8t Definitely not just a hiccup on your machine, we experienced the same problem. 

The download counter for [trivy-java-db](https://github.com/aquasecurity/trivy-java-db/pkgs/container/trivy-java-db) indicates an more widespread problem, downloads spiked the last three days:
![image](https://github.com/user-attachments/assets/08fae2f4-2f57-41b2-8236-7c437147379e)

It seems "NextUpdate" ist calculated from "UpdatedAt", not from "DownloadedAt". But "UpdatedAt" is the timestamp of the last trivy-java-db release. As trivy-java-db is only released weekly I expect the problem to return.

The guys at aquasecurity are already [aware of the problem](https://github.com/aquasecurity/trivy/discussions/7591).

**Comment by dan-m8t** [comment]
Thanks for pointing me into that direction. As this is not a trivy-adapter/harbor issue I will close it. Thank you all!
