### ISSUE TITLE
How to support configuring multiple IP addresses in hostname in harbor.yml

### ISSUE THREAD

**Issue by BigCousin-z** [goharbor/harbor#20960]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
A clear and concise description of the plan to make the solution ready. It can include a development timeline, resource estimation, and other related things.

**Additional context**

**Comment by wy65701436** [comment]
currently, we do not support the multiple ip address for one single harbor instance. Can you let us know more details about your request? It's better for us to provide help.
