### ISSUE TITLE
Harbor repoDigest not changing for a project

### ISSUE THREAD

**Issue by rajbaratht** [goharbor/harbor#20964]
Hello - For a project we found that the repoDigest is not changing when we do a docker push. For example: 
![image](https://github.com/user-attachments/assets/a89a509b-138b-45f1-887b-0e0fe3c0c98e)

If you see the above, these are multiple docker builds but the repoDigest didn't change. The expected behavior is to have repoDigest change for each docker push. I'm not sure if this is a bug or If I'm missing something. Kindly advise.

**Comment by chlins** [comment]
The digest serves as a unique identifier for an image, rather than a tag. Therefore, if multiple tags are associated with the same digest, it indicates that they refer to the same image.

**Comment by wy65701436** [comment]
The digest change is not controlled by Harbor; it depends on how the image was built and pushed. If you simply add a new tag to an existing image, the image itself won’t change, only the tag will be updated.

You can easily check the digest locally before pushing the image to Harbor. If you notice the digest has changed locally but remains the same in Harbor, please reopen the issue.
