### ISSUE TITLE
We‘re missing the support metrix document for dragonfly and harbor

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#20970]
The Dragonfly project has archived its 1.x version, and the latest release is now v2.1.59. 

Starting from Harbor v2.12, only Dragonfly 2.0+ is supported, and compatibility with Dragonfly 1.x has been discontinued. We should document this change and provide a migration solution.

**Comment by stonezdj** [comment]
@chlins  Is there any impact on existing users who are using old version of dragonfly with the previous configure after upgrade Harbor to 2.12.0 release?
