### ISSUE TITLE
Reported vulnerabilities on the Microsoft .NET SDK 8 image

### ISSUE THREAD

**Issue by Roel84** [goharbor/harbor#20975]
Not sure if this is a bug or if I'm missing something.
Harbor reports several vulnerabilities on the official Microsoft .NET SDK 8 image:

![image](https://github.com/user-attachments/assets/03a67c1f-4958-4201-9bbe-9697de369684)

We're using `8.0-windowsservercore-ltsc2022` which is 'latest' but the SHA is the same as `8.0.401-windowsservercore-ltsc2022`. According to Harbor these vulnerabilities should be resolved in 8.0.1, so I don't understand why these are still detected for 8.0.401?

![image](https://github.com/user-attachments/assets/56c2fc14-9701-412d-a012-0d8e68564983)
https://mcr.microsoft.com/product/dotnet/sdk/tags

Harbor version: v2.11.0-70255684

**Comment by EdKingscote** [comment]
The reported vulnerabilities and fixed versions are related to individual packages inside the container, and these packages are versioned independently of the main container itself. You can see the current versions of these packages to the left of your box highlighting the fixed versions.

**Comment by wy65701436** [comment]
Please verify whether the Microsoft .NET SDK 8 image contains the reported vulnerable packages. Since Harbor uses Trivy as its CVE scanner, if you confirm that the image does not include these packages, kindly file an issue in the Trivy repository. I will also notify the Trivy maintainer to review the matter.

**Comment by Roel84** [comment]
Thanks for the explanation. 

I searched for the packages but I couldn't find the mentioned versions:

```
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.8\ref\net8.0\System.Formats.Asn1.dll 8.0.824.36612
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.8\ref\net8.0\System.Text.Json.dll    8.0.824.36612
C:\Program Files\dotnet\sdk\8.0.402\Containers\tasks\net472\System.Text.Json.dll                 8.0.724.31311
...
```

However, there are still several `*.deps.json` files that contain references to the older packages:

```
C:\Program Files\dotnet\sdk\8.0.402\dotnet.deps.json      757                "System.Formats.Asn1/8.0.0": {},
C:\Program Files\dotnet\sdk\8.0.402\dotnet.deps.json      884                "System.Formats.Asn1": "8.0.0"
C:\Program Files\dotnet\sdk\8.0.402\MSBuild.deps.json   3057              "System.Formats.Asn1/8.0.0": {
...
```

It seems that the packages are updated but not the dependency manifest files so I guess Trivy is correct to report this. 
I think this is rather an SDK issue then. I found a similar issue in the .Net SDK repo: https://github.com/dotnet/sdk/issues/42378
