### ISSUE TITLE
Docker compose - Enable metrics

### ISSUE THREAD

**Issue by psimms-cs** [goharbor/harbor#20974]
I am trying to enable metrics for a docker compose deployment

From what I understand I need to uncomment the below metric block and switch to true
https://github.com/goharbor/harbor/blob/main/make/harbor.yml.tmpl#L247

Then re run the prepare script which will then amend the docker compose file with the new updates like below and various other updates in the templates
https://github.com/goharbor/harbor/blob/main/make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja#L375

However this does not seem to be updating the compose file for me (or other templates) I have confirmed that enabling external_redis works as expected so I am not sure why metric is not working

Do I need to do anything else to enable metrics for a docker compose deployment? Am I missing something?

Any help would be appreciated - thank you

Harbor version - v1.10.19

**Comment by wy65701436** [comment]
Please try using the latest release of Harbor v2.11.1 with the same procedures, and feel free to reopen the issue if it still persists.

**Comment by psimms-cs** [comment]
Confirmed this worked for v2.11.1 - thank you
