### ISSUE TITLE
Metrics for network activity per project

### ISSUE THREAD

**Issue by jeicoo** [goharbor/harbor#20988]
Please create a metrics that will give insight on network activity(bytes sent, received) with project name as label. 

We would like to monitor harbor network traffic base on project and I think it would help administrators track which projects are using most of the bandwidth,

**Comment by Vad1mo** [comment]
This is difficult to do right and for many use cases depending on how Harbor is configured, artifacts pulls or pushes might no come from harbor but from object store directly, resulting in zero metric.  

If you are using and monitoring e.g. nginx ingress or any other powerful ingress, together with artifact file storage, you can gather those metrics already.
