### ISSUE TITLE
Replication to new AWS ECR is missing immutability tag.

### ISSUE THREAD

**Issue by knowacki23** [goharbor/harbor#20994]
**How can we help you?**
When we replicate from Harbor to a AWS ECR that does not exists, the ECR is created without the immutability tag, without taking in consideration the configuration on the Harbor side.

Harbor project has immutability rules in place, but when we are replicating images from that project to AWS ECR a replicated image is set to mutable in AWS ECR.

We would like to have it set to immutable since that's how it is set in Harbor.

**Comment by Vad1mo** [comment]
This is not related to Harbor, as it is fully related to the implementation of AWS ECR, which does not know about the concept of tag immutability.

**Comment by bittrance** [comment]
@Vad1mo Arrived here because I had the same question as OP. I'm not sure what you mean? From the CLI docs of `aws ecr create-repository`
```
       --image-tag-mutability (string)
          The  tag mutability setting for the repository. If this parameter is
          omitted, the default setting of MUTABLE will be used which will  al-
          low image tags to be overwritten. If IMMUTABLE is specified, all im-
          age  tags within the repository will be immutable which will prevent
          them from being overwritten.
```
I'm fairly sure this is what OP is referring to.
