### ISSUE TITLE
Harbor proxy cache loses image tag when remote image is deleted

### ISSUE THREAD

**Issue by sincorchetes** [goharbor/harbor#20997]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Remote registries delete the image by the retention policy.
Harbor does have the layer cached but the tag is deleted.

**Steps to reproduce the problem:**
	1.	Go to the remote registry.
	2.	Build and push an image.
	3.	Deploy the image using your Harbor Registry URI.
	4.	Harbor detects that the image is not saved locally and downloads it.
	5.	The deployment is successful.
	6.	Remove the image from the remote registry.
	7.	Try to redeploy the image.
	8.	The deployment fails.

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.11.1-6b7ecba1
- docker engine version: [y.y.y] (Kubernetes)
- docker-compose version: [z.z.z] (Kubernetes)

**Additional context:**
The image is storage but with **sha256** not with **tag** (🤷)

**Comment by stonezdj** [comment]
It is work as designed, when the remote server delete the image, the image should be be served.

**Comment by sincorchetes** [comment]
> It is work as designed, when the remote server deletes the image, the image should be served.

But why doesn’t it delete the entire image? Why save the image as a sha256 hash instead of deleting it? Is it not possible to configure this behavior manually? Perhaps I’m interested in saving the tag until I perform a cleanup because if it wrongly deletes the image from the remote server, we won’t be able to pull it again.

**Comment by MinerYang** [comment]
Please run GC for clean the manifest cache

**Comment by sincorchetes** [comment]
If it’s not possible, define a policy to save the cache or delete it manually.

**Comment by sincorchetes** [comment]
I'll open a proposal.
