### ISSUE TITLE
Issue with LDAP group resolving 

### ISSUE THREAD

**Issue by Jean-Daniel** [goharbor/harbor#20992]
If you are reporting a problem, please make sure the following information are provided:

This is a follow up of #20038 which has been closed while still present.

**Expected behavior and actual behavior:**

LDAP group are not found because the  query  built by Harbor is invalid.

This is the debug log:

```
2024-10-01T21:11:58Z [DEBUG] [/pkg/ldap/ldap.go:347]: Groupname: , groupDN: cn=developers,ou=Groups,dc=example,dc=com
2024-10-01T21:11:59Z [DEBUG] [/pkg/ldap/ldap.go:259]: Search ldap with filter:(&(objectclass=groupOfNames)(cn=*))
```

For whatever reason, Harbor is building all group resolving query passing `cn=*` instead of keeping the real group DN, making the query returning 0 entries.

The LDAP record in OpenLDAP looks like this:

```
dn: cn=developers,ou=Groups,dc=example,dc=com
structuralObjectClass: groupOfNames
entryUUID: e426aa3a-acd2-1036-8978-df31319679d5
creatorsName: cn=admin,dc=example,dc=com
cn: developers
objectClass: groupOfNames
```

**Versions:**
Please specify the versions of following systems.

- harbor version:  2.11

**Comment by stonezdj** [comment]
will change the log level from warning to debug.

**Comment by Jean-Daniel** [comment]
My bad, I messed up the LDAP bug numbers. This issue is not related directly to #20038 but is a group resolving issue.

The log is legit in my case, but harbor fails to resolve any LDAP group.
