### ISSUE TITLE
Migrating Harbor Registry from one server to another

### ISSUE THREAD

**Issue by saivd** [goharbor/harbor#20993]
I am currently experiencing an issue when trying to migrate harbor registry from one server to another.
I already setup a new harbor instance on the new server and tried to migrate the postgresql database by simply copy-pasting the files and also by setting up the database using a backup of the source database.
In both cases most data got migrated successfully, but the harbor-users where missing.
As I don't have access to the users password, I cannot create the users manually after the fact.
Is there a way to migrate all of harbors data to a new server, including user data?
Thank you very much!

**Comment by Vad1mo** [comment]
your should backup your db, using your favorite postgreSQL too. 
make sure your new and old instance is using the same secrets to encrypt the the data, otherwise your new instance won't be able to read them. 

this is all it takes.

**Comment by reasonerjt** [comment]
Closing as the question is answered.
