### ISSUE TITLE
Bump up trivy adapter

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#21011]
It should consume trivy v0.56.x and be shipped with Harbor v2.12.0

**Comment by dan-m8t** [comment]
Is there an ETA for 2.12 and this change? I got the issue with java-db download quite frequently and would like to use the new trivy version.

**Comment by reasonerjt** [comment]
@dan-m8t 
Harbor v2.12 is targeting early November:
https://github.com/goharbor/harbor/wiki/Release-plans

Before that you may verify using the RC of trivy adapter:
https://github.com/goharbor/harbor-scanner-trivy/releases/tag/v0.32.0-rc.1

And let me know if you see any issues.

**Comment by reasonerjt** [comment]
I'll keep this open till the trivy-adapter is GAed.

**Comment by reasonerjt** [comment]
Closing as trivy adapter v0.32.0 has released:
https://github.com/goharbor/harbor-scanner-trivy/releases/tag/v0.32.0
