### ISSUE TITLE
Robot account update robot account without creator might cause privilege escalation

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#21026]
Steps to reproduce:
1. Create a robot account A(project level), and grant permission robot (create/delete/update/list)
2. Use the robot account A to create robot account B, B has permission robot (create/delete/update/list)
3. Use the robot account B to create robot account C, C has permission  robot (create/delete/update/list)
4. Delete robot account B, then robot account A can update robot account C. and grant account C with excessive permission, such as accessory list

When the robot account's creator is removed, the update operation should be limited or disabled.

**Comment by wy65701436** [comment]
close it as fixed by https://github.com/goharbor/harbor/pull/21028
