### ISSUE TITLE
Unable to view the speed limit for proxy cache project

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#21021]
I can set the speed limit when creating the proxy cache project, but I have nowhere to view and update it afterward.

It returned from the backend, and we should add it into the configuration page,

```
{
    "creation_time": "2024-10-10T07:13:26.723Z",
    "current_user_role_id": 1,
    "current_user_role_ids": [
        1
    ],
    "cve_allowlist": {
        "creation_time": "0001-01-01T00:00:00.000Z",
        "id": 2,
        "items": [],
        "project_id": 2,
        "update_time": "0001-01-01T00:00:00.000Z"
    },
    "metadata": {
        "proxy_speed_kb": "-1",
        "public": "false",
        "retention_id": "1"
    },
    "name": "proxy",
    "owner_id": 1,
    "owner_name": "admin",
    "project_id": 2,
    "registry_id": 1,
    "repo_count": 1,
    "update_time": "2024-10-10T07:13:26.723Z"
}
```

It should provide an way to the project admin to do this.

![image](https://github.com/user-attachments/assets/245fddf3-93dd-4bcf-81f1-30d1ff1f3250)

**Comment by xuelichao** [comment]
Should we support to update proxy cache?

**Comment by stonezdj** [comment]
No update, just display the value

**Comment by bupd** [comment]
We currently have the ability to edit replication and robot accounts, etc., but projects, once created, cannot be edited via the UI. I was wondering if we could add an option to edit projects. Do you think this would be the right approach?

Additionally, if we need to view and update the bandwidth of the proxy cache for a project, I propose placing this option under the Configuration tab of the project, specifically after the public checkbox. This seems like the most appropriate place for managing project-level settings.

I personally prefer approach 1, which introduces an edit option for projects, but I’m unsure. I’d appreciate your feedback on whether this approach makes sense.
