### ISSUE TITLE
the proxy_speed_kb doesn't affect the update

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#21024]
I’ve created a proxy project with a speed setting of 1, and it works as expected.

However, if I update the speed to -1 through the API, it doesn’t affect the latest change.

```
PUT https://{harbor_ip}/api/v2.0/projects/4
{"metadata":{"proxy_speed_kb":"-1"}}
```

**Comment by stonezdj** [comment]
Can't reproduce the issue.
