### ISSUE TITLE
Create Robot account without expire time

### ISSUE THREAD

**Issue by linuxmail** [goharbor/harbor#21031]
Hi, 

on our older Harbor, it was possible to create a robot account, which does not expire. With the latest version, it's always 1 month. I've tried to create via API and used `duration: 0`  or `expires_at: -1` (from what I found here under issues).

What is the correct way .. or isn't it anymore ?

cu denny

**Comment by bupd** [comment]
## Creating a Robot Account that Never Expires:

In the **UI**: Use the dropdown and select "Never".

![](https://github.com/user-attachments/assets/ca21d1df-2b33-492f-b4e9-3834f915dad4)

Using the **API**: Set the `duration` to `-1`.

![robotNotExpireAPI](https://github.com/user-attachments/assets/646ade95-b457-4572-9d8d-33959a373d88)


Hope this helps.

**Comment by wy65701436** [comment]
@linuxmail did it work for you as mentioned by @bupd ?

**Comment by linuxmail** [comment]
hi,

sorry for wasting time. I was so unfocused, that I downloaded the 1.x version instead of the 2.x. I used before the Bitnami created stack and switched now.

Realy Sorry. Closing.
