### ISSUE TITLE
Upgrade from v1.10.10 to v2.11.1 - Can no longer docker login

### ISSUE THREAD

**Issue by psimms-cs** [goharbor/harbor#21057]
How can we help you?

We have harbor running via docker-compose and setup using the harbor-online-installer

I upgraded us to the latest  and all looks ok and can login to the ui and everything is in tact

However we can no longer docker login to harbor with our username/password which we use to login to the ui and worked before

It looks like we now have to use basic authentication? How do we set this up in a docker-compose environment or better yet how can we just use the username/password that we setup in the ui for docker logins

```
Error response from daemon: login attempt to https://harbor.domain/v2/ failed with status: 401 Unauthorized
```

```
time="2024-10-17T10:47:32.916991206Z" level=error msg="error authenticating user "harbor_registry_user": authentication failure" go.version=go1.22.6 http.request.host=harbor.domain http.request.id=b7b4fe08-79b7-43a6-aed4-b92b8392421f http.request.method=GET http.request.remoteaddr=10.1.1.1 http.request.uri="/v2/" http.request.useragent="docker/26.1.3 go/go1.22.5 git-commit/8e96db1c328d0467b015768e42a62c0f834970bb kernel/6.6.41-0-virt os/linux arch/arm64 UpstreamClient(Docker-Client/27.1.1-rd \(darwin\))"
time="2024-10-17T10:47:32.917090404Z" level=warning msg="error authorizing context: basic authentication challenge for realm "harbor-registry-basic-realm": authentication failure" go.version=go1.22.6 http.request.host=harbor.domain http.request.id=b7b4fe08-79b7-43a6-aed4-b92b8392421f http.request.method=GET http.request.remoteaddr=10.1.1.1 http.request.uri="/v2/" http.request.useragent="docker/26.1.3 go/go1.22.5 git-commit/8e96db1c328d0467b015768e42a62c0f834970bb kernel/6.6.41-0-virt os/linux arch/arm64 UpstreamClient(Docker-Client/27.1.1-rd \(darwin\))"
172.18.0.3 - - [17/Oct/2024:10:47:32 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/26.1.3 go/go1.22.5 git-commit/8e96db1c328d0467b015768e42a62c0f834970bb kernel/6.6.41-0-virt os/linux arch/arm64 UpstreamClient(Docker-Client/27.1.1-rd \\(darwin\\))
```

**Comment by Vad1mo** [comment]
please follow https://goharbor.io/docs/2.11.0/administration/upgrade/ and read the FAQ: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#upgrade

There is no support from upgrading from 1.10 to 2.11. one have to upgrade one minor version after the other.

**Comment by psimms-cs** [comment]
> please follow https://goharbor.io/docs/2.11.0/administration/upgrade/ and read the FAQ: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#upgrade
> 
> There is no support from upgrading from 1.10 to 2.11. one have to upgrade one minor version after the other.

I am not sure why you closed this, that is not related, I went through the small jumps to get to v2.11.1

The issue here is not to be with the upgrade but rather issues with logging in via docker

**Comment by Vad1mo** [comment]
you didn't mention that in the first place!

**Comment by psimms-cs** [comment]
> you didn't mention that in the first place!

I did
