### ISSUE TITLE
Documentation: Where is Job Service type "EXECUTION SWEEP" described (harbor 2.10)

### ISSUE THREAD

**Issue by mdavid01** [goharbor/harbor#21058]
Ref #21051, Thanks for the update. We are testing 2.11 now. Please clarify response 'see if it still exists'. Which **"it"**? -- See if the 'EXECUTION SWEEP' job exists? Or see if the performance issue exists. 

If the 'EXECUTION SWEEP' job still exists, then the original questions were, 'Where can we find documentation describing the 'EXECUTION SWEEP' job function and what artifacts it impacts? What will 'break' if we stop all the 'EXECUTION SWEEP' pending jobs?'

Thx.
Michael

**Comment by wy65701436** [comment]
The 'EXECUTION SWEEP' job is an internal backend process used to clean outdated execution records for all jobs defined by Harbor, including scan, gc, replication, and etc.

This job does not affect any artifacts; it only cleans up the records.

While you can stop this job, I do not recommend doing so, as it helps maintain a clean environment and improves overall Harbor performance.

**Comment by chlins** [comment]
If the execution sweep of the historical backlog contains a large number of jobs, you can opt to pause and clean up all jobs of that type using the jobservice dashboard. This action will not impact the system in the short term; however, in the long run, it is recommended to allow the job to continue running to prevent the continuous growth of the database's execution.
