### ISSUE TITLE
Documentation:  Where is Job Service type "EXECUTION SWEEP" described (harbor 2.10)

### ISSUE THREAD

**Issue by mdavid01** [goharbor/harbor#21051]
Hi team:  When investigating Harbor 2.10 performance issues with Image Scanning jobs (3,500 backlogged), we noticed a job type on the Job Service Dashboard called 'EXECUTION SWEEP' that shows pending of 2124 jobs and latency of 2115+ hours.  Where can we find documentation describing the 'EXECUTION SWEEP' job function and what artifacts it impacts?  What will 'break' if we stop all the 'EXECUTION SWEEP' pending jobs?

FYI:  We use Postgresql + S3 type storage for our images.   

Thanks.

**Comment by wy65701436** [comment]
this has been fixed in the v2.11 by https://github.com/goharbor/harbor/pull/20601, please upgrade to the v2.11.1 and see if it still exists in your environment.

**Comment by mdavid01** [comment]
Thanks for the update.  We are testing 2.11 now.  Please clarify response _'see if **_it_** still exists'_.  Which "it"? -- the 'EXECUTION SWEEP' job?  Or the performance issue.  If the 'EXECUTION SWEEP' job still exists, then the original questions were, 'Where can we find documentation describing the 'EXECUTION SWEEP' job function and what artifacts it impacts? What will 'break' if we stop all the 'EXECUTION SWEEP' pending jobs?'
