### ISSUE TITLE
Execution sweep time is reported incorrectly

### ISSUE THREAD

**Issue by another-novelty** [goharbor/harbor#21067]
**Expected behavior and actual behavior:**
The execution sweep time should be reported correctly.

**Steps to reproduce the problem:**

1. Install harbor through helm
2. Go to the Job Service Dashboard
3. Go to the schedules (`/harbor/job-service-dashboard/schedules`)
4. See the wrong Schedule for `EXECUTION_SWEEP`

**Versions:**

- harbor version: 2.11.1
- kubernetes Server Version: v1.30.5
- harbor-helm version: 1.15.1

**Additional context:**

- https://github.com/goharbor/harbor/pull/20601#issuecomment-2416133682
  Execution sweep time should have been set to once daily ( cronspec "0 0 0 * * *" ) but the frontend still reports it as once per hour ( "0 0 * * * *" ). We also see an accumulation of pending jobs, which the above pull request should have fixed. It seems as though the reported value is the actual value used, instead of the new one.

**Comment by chlins** [comment]
After double confirm with the code, it is still `"0 0 * * * *"` in the v2.11.1(https://github.com/goharbor/harbor/blob/6b7ecba1b15a90cb8d1ff090dd9aaffe168ede4e/src/controller/task/sweep.go#L45), but main branch has been changed to `"0 0 0 * * *" `, so it will be carried within v2.12.0.

**Comment by wy65701436** [comment]
@another-novelty please check it out in the v2.12, and reopen it if you still see it after upgrading.
