### ISSUE TITLE
Harbor not properly sharing CSRF tokens/sessions across scaled deployment in k8s

### ISSUE THREAD

**Issue by ianseyer** [goharbor/harbor#21060]
When using the UI, I will sporadically see "CSRF token invalid" errors when performing actions when harbor-core is scaled to >1.

1. Scale up harbor-core to 3 replicas
2. Create several projects
3. attempt to delete them one by one
4. you will see "CSRF token invalid" errors sporadically

This was confirmed by scaling harbor-core down to 1, and then deletions worked consistently without issue.

On Harbor 2.11.0

**Comment by MinerYang** [comment]
Hi @ianseyer ,

Could your check following settings?
 - Please verify that env `CSRF_KEY` in each of the core pod are the same
 - Please check if each of the node this running harbor-core pod are with same machine time
 - Please kindly check if there's any debug logs you could provide while error happened.

**Comment by MinerYang** [comment]
True, you need to make sure the key be 32characters
