### ISSUE TITLE
demo.goharbor.io Instance Not Working

### ISSUE THREAD

**Issue by bupd** [goharbor/harbor#21077]
How can we help you?
I'm not sure is it expected but just let you know that the https://demo.goharbor.io/ is not accessible and giving HTTP 401 Unauthorized. Can't login via API or UI.

![demofailed](https://github.com/user-attachments/assets/8384bc8a-b247-467b-a86e-8dea644ce29c)

**Comment by Vad1mo** [comment]
resolved now
