### ISSUE TITLE
Can proxy project and normal project share same layer for image?

### ISSUE THREAD

**Issue by yimiaoxiehou** [goharbor/harbor#21116]
## why question ?
i have a proxy project "docker.io" proxy to dockerhub and a common project "local"

first i have try pull a large image from dockerhub direct and push it to "local" project.
then i try pull this image over proxy project "docker.io" it look like not use local cache. it also slowly.

## env:
harbor version: 2.8.4

**Comment by stonezdj** [comment]
Yes, they share same layer for same image, we need to look into the detail request and find out which request is slow. for example proxy.log
