### ISSUE TITLE
Help me pull images from docker like nginx or postgres without (/imagename)

### ISSUE THREAD

**Issue by lehakatana** [goharbor/harbor#21139]
### Discussed in https://github.com/goharbor/harbor/discussions/21137

<div type='discussions-op-text'>

<sup>Originally posted by **lehakatana** November  5, 2024</sup>
Hello, i pulled easily image from docker hub goharbor/harbor-core with tag dev
command for this is: docker pull goharbor/harbor-core:dev 
with this settings:
![image](https://github.com/user-attachments/assets/ae984468-f850-4670-ab5d-de7238d4fab8)

But i can't get image postgres with tag 17-alpine, for this image command is 
docker pull nginx:17-alpine
link : [https://hub.docker.com/_/postgres ](url)

seems harbor can't take image from "account name" without image name, help pls, i tried many options, nothing downloaded

</div>

**Comment by MinerYang** [comment]
could you try to using `library/postgres`

**Comment by lehakatana** [comment]
I tried. It's finished with status "Succeded" but nothing downloaded
![image](https://github.com/user-attachments/assets/517918e2-d9b4-436e-a9e5-bd820aa9233b)

![image](https://github.com/user-attachments/assets/aa83439a-a879-4694-a0fa-1968180e4979)

**Comment by stonezdj** [comment]
`library/postgres`

**Comment by lehakatana** [comment]
Sorry for the wrong configuration, surprisingly I was using backslash. 

So it worked, thanks!
