### ISSUE TITLE
An error occurred when deploying PieCloudDB

### ISSUE THREAD

**Issue by lijie123bes** [goharbor/harbor#21142]
During the deployment of PieCloudDB, after executing sudo ./install.sh --with-chartmuseum, when starting the Harbor service, I encountered an error:

Error response from daemon: manifest for goharbor/harbor-core:dev-arm not found: manifest unknown: manifest unknown.

I don`t know what's causing this issue.

**Comment by MinerYang** [comment]
Hi @lijie123bes ,
Thanks for reaching out to us,

- We are only supporting official Postgres DB with Harbor compatible version
- Chartmuseum has been deprecated, Please upgrade to latest harbor version
- arm build is also out of our current support.
If you are having customized harbor build, please make sure all the images building successful.
