### ISSUE TITLE
an unexpected error occurred

### ISSUE THREAD

**Issue by lijie123bes** [goharbor/harbor#21147]
26DB7CAB-F6C0-4D75-A9DE-AAB5F94BC31B20241107012254
![QQ截图20241107092240](https://github.com/user-attachments/assets/ef0631e1-54b5-49c4-8533-3d505000b313)

**Comment by wy65701436** [comment]
It seems that you're reporting an issue of docker, please file issue at their side. If you have any Harbor specific issue, feel free.
