### ISSUE TITLE
Garbage Collection 'workers' not functioning as expected

### ISSUE THREAD

**Issue by mdavid01** [goharbor/harbor#21176]
When running Garbage Collection 5 workers is selected but only one worker is running.
![image](https://github.com/user-attachments/assets/eefea57c-b065-4ae9-b956-f1a64f760d14)

This behavior is similar to issue 'https://github.com/goharbor/harbor/issues/19991".  It's Tuesday, 11/12, 8:30am ET.  Garbage collection has been running since Friday (11/8) morning.  AWS support sees no evidence of s3 throttling.  GC began with 235k blobs to delete and are now at ~2k blobs.  On Saturday (11/9) I began tracking progress.  We're seeing about 6 blob deletions every minute.  tracking file is attached.
[gcstats.xlsx](https://github.com/user-attachments/files/17717189/gcstats.xlsx)

```
  ... Our jobservice pods run 10 workers each, but exactly one garbage collection task is running at any given time.
```
============================================================

If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When running Garbage Collection, actual or dry run, 5 workers are selected but only 1 worker ever runs.  
Expected behavior is that 5 workers are running Garbage Collection or that # of workers is not an input requirement.

**Steps to reproduce the problem:**

1. go to Garbage Collection page
2. run Garbage Collection with no worker selected. The response indicates a workers entry is required.
3. run Garbage Collection with 5 workers selected.  The dashboard shows 1 worker and the workers tab only finds 1 worker running Garbage Collection.  

**Versions:**
Please specify the versions of following systems.

- harbor version: [version v2.10.1-b7b88476]
- docker engine version: [y.y.y] 
->Not sure where this is set by customer
- docker-compose version: [z.z.z] 
-> Not sure where this is set by customer

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
->What pod contains the /var/log/harbor directory?

**Comment by chlins** [comment]
The concept of the worker selected on GC is not the same as the worker concept of jobservice, but rather the number of goroutines in parallel to delete storage during the sweep phase of the GC execution.
