### ISSUE TITLE
Docker push denied error.

### ISSUE THREAD

**Issue by creeram** [goharbor/harbor#21179]
docker login harbor.domain.com works.
docker push harbor.domain.com/project/domo:latest  (denied:)

I'm using an admin user to push the docker image.

helm push works well without any error.

There are no error logs in the registry pod.

helm chart version: 1.15.1

Pvc is disabled for all pods and I'm using s3 object storage for docker images and helm charts.

**Comment by harshguptaserver** [comment]
I am also facing the same issue after upgrading from 2.11 to 2.12

docker pull is also failing if i pass in the tag, docker push is also failing (as login is not working from docker while from web-ui login is working):
```
username101@username101machine:~/$ docker login container-registry.example.com
Username: username101
Password: 
Error response from daemon: login attempt to https://container-registry.example.com/v2/ failed with status: 502 Bad Gateway


username101@username101machine:~/$ docker push container-registry.example.com/library/alpine:3.20
The push refers to repository [container-registry.example.com/library/alpine]
75654b8eeebd: Preparing 
unauthorized: unauthorized to access repository: library/alpine, action: push: unauthorized to access repository: library/alpine, action: push
username101@username101machine:~/$ docker pull container-registry.example.com/library/alpine:3.20
Error response from daemon: received unexpected HTTP status: 502 Bad Gateway
```

Also, here are the nginx logs: 
```
nginx              | 192.168.88.227 - "HEAD /v2/library/alpine/manifests/3.20 HTTP/1.1" 502 0 "-" "docker/27.3.1 go/go1.22.7 git-commit/41ca978 kernel/6.9.3-76060903-generic os/linux arch/amd64 UpstreamClient(Docker-Client/27.3.1 \x5C(linux\x5C))" 0.031 0.031 .
nginx              | 192.168.88.227 - "GET /v2/library/alpine/manifests/3.20 HTTP/1.1" 502 0 "-" "docker/27.3.1 go/go1.22.7 git-commit/41ca978 kernel/6.9.3-76060903-generic os/linux arch/amd64 UpstreamClient(Docker-Client/27.3.1 \x5C(linux\x5C))" 0.021 0.022 .
```

**Comment by harshguptaserver** [comment]
Also, i tried rolling back to previous version 2.11.1 and that container keeps on crashing now ... ( sudo install.sh  for 2.11.1 offline installer ). So i am at severe block as the registry is down and the data needs to be preserved.

**Comment by harshguptaserver** [comment]
Everything was healthy. As a preventive measure i deleted and re-installed 2.11.1 that gave me error, then i reinstalled  2.12.0 offline installer and that worked. 

- the issue here is why was it throwing 502 error when all pods were healthy. 

For now everything is healthy and i was able to save my precious data and bring the server up  after re-installing old, then new version again.

**Comment by MinerYang** [comment]
Do you still have the issue now? If everything is fine, I will close the issue now.
