### ISSUE TITLE
replication with label source resource filter is not deleting images

### ISSUE THREAD

**Issue by AharonIsraelCohen** [goharbor/harbor#21213]
We are adding label to our images at some point on our ci-cd flow, then we are adding some tag to the image.
At this point the replication (both ACR and ECR ) are replicating the new image tag to the registries.

But what happened when image is deleted?

Expected behavior:
New replication executions should raised and delete the image from remote

Actual behavior:
Nothing happened, the image is deleted from harbor only.

The expected behavior is working when there is no label resource filter in the replication!!

**Versions:**
- harbor version: 2.11.1

**Comment by chlins** [comment]
So you enabled the `Deletion` option in the replication policy, and it worked only when no label resource filter?

**Comment by AharonIsraelCohen** [comment]
> So you enabled the `Deletion` option in the replication policy, and it worked only when no label resource filter?

Exactly
