### ISSUE TITLE
speed limit only takes effect on the client that pulls the image from harbor, not on the remote repository pulled by harbor

### ISSUE THREAD

**Issue by weak-fox** [goharbor/harbor#21226]
Hello ,

When I set the project to enable proxy cache and set the bandwidth to 5Mbps, the speed limit only takes effect when pulling images, and only takes effect on the client that pulls the image  from harbor, not on the remote repository pulled by harbor.

This is a screenshot of the bandwidth usage of the virtual machine where I deployed harbor.It takes up all my public network bandwidth 1.2MB/s(10Mbps).But the speed passed to the client pulling the image from harbor is limited to 600KB/s(≈5Mbps)

<img width="385" alt="image" src="https://github.com/user-attachments/assets/b3b18744-898f-4778-b454-dd1373c59566">

When the proxy cache is finished, I use another machine to pull, the client is not limited in speed, reaching 170MB/s +

<img width="383" alt="image" src="https://github.com/user-attachments/assets/b635ae95-b18f-4ff1-8918-6e93bffcfebc">

This is my configuration in the project

<img width="364" alt="image" src="https://github.com/user-attachments/assets/e379d2c6-e86e-46b8-b9fc-dc146e24f323">

**Comment by weak-fox** [comment]
Repeat steps：
1. Create new Registry Endpoint and set url to another harbor registry, and fill in the relevant access parameters.
2. Create new Project, set Access Level public, set Project quota limits 100G, enable Proxy cache, and set bandwidth limits.
3. Use the docker client to pull the uncached image of this project.
4. Check the bandwidth usage of the VM where the harbor is located.

**Comment by stonezdj** [comment]
The bandwidth limit can not limit the bandwidth accurrately.
only take effect on goroutine level, when you set the 5Mbps limit, maybe are several goroutines run, it could be >10Mbps.

**Comment by stonezdj** [comment]
The bandwidth in the VM level includes traffic to the client and traffic to the upstream registry. off cause it > 5Mbps.

**Comment by weak-fox** [comment]
@stonezdj Thank you for your answer

> The bandwidth limit can not limit the bandwidth accurrately. only take effect on goroutine level, when you set the 5Mbps limit, maybe are several goroutines run, it could be >10Mbps.

In this case, speed limit will behave differently in different situations. How do I need to set it up to prevent it from filling up my bandwidth, such as my bandwidth of 10Mbps?


> The bandwidth in the VM level includes traffic to the client and traffic to the upstream registry. off cause it > 5Mbps.

This may not be right. 

The client is hosted on another VM (which does not have Harbor deployed). The VM with Harbor deployed utilizes its downstream bandwidth for pulling images from the public internet. On the firewall connected to the public network, I observed that the VM with Harbor was consuming 10 Mbps of bandwidth.
