### ISSUE TITLE
bump needed for trivy to v0.57.1 in harbor-scanner-trivy

### ISSUE THREAD

**Issue by stgdns** [goharbor/harbor#21223]
Hello everyone,

I'm proposing that trivy is updated to v0.57.1 in harbor-scanner-trivy.

Reason: trivy scanner is not usable since quite a while because the vuln-db download constantly fails, because of github rate-limiting at the organization level ("aquasecurity"), see:
https://github.com/aquasecurity/trivy/issues/7938

fixed in version: trivy to v0.57.1

If this is not possible, then maybe the PR https://github.com/goharbor/harbor-scanner-trivy/pull/7 could be merged and the helm chart at https://helm.goharbor.io updated, to allow setting the vuln-db URLs manually.

PS: since recently the new home of harbor-scanner-trivy is:
https://github.com/goharbor/harbor-scanner-trivy

**Comment by reasonerjt** [comment]
@dan-m8t I think the answer is yes.

**Comment by reasonerjt** [comment]
We'll resolve this one after trivy adapter's GAed, reopening...
