### ISSUE TITLE
Problem with multiple Tags using Event Based Replication

### ISSUE THREAD

**Issue by dloxterm** [goharbor/harbor#21245]
**Expected behavior and actual behavior:**
We're using 2 Harbor instances with Event Based Push Replication, let's call them harbor1 and harbor2

When an image is built and pushed using multiple tags, e.g. similar to this
```
docker buildx build --tag harbor1.example.com/tag-test/harbor-test:0.0.1 --tag harbor1.example.com/tag-test/harbor-test:mytest --tag harbor1.example.com/tag-test/harbor-test:latest --push .
```

All tags are visible for the artifact on harbor1, but after replication to harbor2 there's only the first tag replicated (`0.0.1`)

- When I run the same replication rule manually from the WebUI, I can see all three tags in the harbor2.
- Also, when I add a new Tag from the WebUI to the artifact, it is replicated automatically.
- When I use docker build with one tag, and then just docker tag and docker push from my computer, the problems also occurs.

When I check the logs for the `docker build --tag a --tag b` I only see that tag a was created in harbor, the asdasd is my test from the WebUI.

![image](https://github.com/user-attachments/assets/ad1eae70-7c41-46ff-a6c5-2aeb682a6a61)

However in the artifact display the tags and times are correct:

![image](https://github.com/user-attachments/assets/a2363eb0-01b7-4a9e-86c4-9c25cbacfde5)

For now, we will try to just add an API call at the end of the pipeline to trigger the replication.
However it would be greatly appreciated to understand if this is wanted behavior or a bug, and in case it's wanted to document it somewhere (or make it more obvious because I could not find it).

**Steps to reproduce the problem:**
Set up a Replication rule with these settings:

![image](https://github.com/user-attachments/assets/9f1658e3-1ce9-4a6b-9dcf-1c23461f7fc7)

And try to push an image with multiple tags (e.g. `docker buildx build --tag harbor1.example.com/tag-test/harbor-test:0.0.1 --tag harbor1.example.com/tag-test/harbor-test:mytest --tag harbor1.example.com/tag-test/harbor-test:latest --push .`)

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.12.0 (also happens in 2.11.1)
- Docker version 27.3.1, build ce12230
- Docker Compose version v2.29.7

**Comment by chlins** [comment]
It seems same with https://github.com/goharbor/harbor/issues/20897.

**Comment by dloxterm** [comment]
Indeed, my search did not find this but I'm also not familiar with the github search syntax so I just missed it.

@chlins this can be closed from my side, no need to track two issues for the same problem right?

**Comment by wy65701436** [comment]
> Indeed, my search did not find this but I'm also not familiar with the github search syntax so I just missed it.
> 
> @chlins this can be closed from my side, no need to track two issues for the same problem right?

sure, let's use https://github.com/goharbor/harbor/issues/20897 to track it.
