### ISSUE TITLE
The digest field in the blob table contains duplicate values

### ISSUE THREAD

**Issue by devopslyf** [goharbor/harbor#21242]
table structure:
![image](https://github.com/user-attachments/assets/acb9869c-accb-4cc1-b17d-892cbcca7f35)

duplicate data:
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/31e1456b-6502-4d9d-aa8a-103d0706a47d">

harbor version: v2.4.2

postgresql version: 11.13.0

**Comment by devopslyf** [comment]
Can I delete one of them, and if so, how can I determine which one to delete?

**Comment by stonezdj** [comment]
It looks similar to this issue: https://github.com/goharbor/harbor/issues/17544,
You can refer the wiki: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#duplicate-repository-name-in-the-same-project

**Comment by devopslyf** [comment]
@stonezdj Is the reindex operation indispensable?

**Comment by stonezdj** [comment]
Yes, because previous index file is corrupted, you need to rebuild it by reindex.
