### ISSUE TITLE
Issue with URL encoding (%2F vs /) causing 404 error after logout in Harbor

### ISSUE THREAD

**Issue by SterhLight** [goharbor/harbor#21254]
# Description
## Steps to Reproduce
1. Log in to Harbor and navigate to a page with a URL containing %2F (e.g., artifacts or repositories).
Example:
```
https://<your-harbor-url>/harbor/projects/11/repositories/redis-cr-template%2Fcharts%2Fredis-cr-template/artifacts-tab
```
2. Log out from this page.
3. Log back in.
## Expected Behavior
After re-login, the user should return to the same page without errors.

##Actual Behavior
After re-login, the following error is displayed:
```
404 Page not found
Redirecting to main page in 5 seconds...
```
The path changes from:
```
.../redis-cr-template%2Fcharts%2Fredis-cr-template/...
```
to:
```
.../redis-cr-template/charts/redis-cr-template/...
```
Additional Context
- Harbor Version: v2.9.0 & v2.10.0
- Deployment Method: Kubernetes / Docker-compose / Offline installer

# Labels
Bug, UI/Redirects, Authentication

# Why this issue is important
This issue impacts user experience, as it prevents users from smoothly navigating back to their previous location after logging out and re-login. It also suggests inconsistent handling of URL encoding within Harbor. And it also spams the monitoring system, the mood for reaction to errors of the response code different from 200.

**Comment by SterhLight** [comment]
> `https://harbor.local/harbor/projects/1/repositories/example%2Fsample%2Fnginx/artifacts-tab` works well in my local env (v2.12.0), can you please try it in the latest Harbor? My browser is chrome.

I will definitely update, but I'm not sure it will help. I should have added to the issue that a similar problem began to be observed after the garbage collector worked. but it could have been a coincidence.

**Comment by stonezdj** [comment]
Please reopen if you can reproduce it in a latest version in future.
