### ISSUE TITLE
Not able to logout properly from the harbor ui after enabling keycloak oidc as authentication

### ISSUE THREAD

**Issue by shaiksaif279** [goharbor/harbor#21257]
Hi,
After integrating the keycloak in harbor, we are not able to logout the user session from keycloak when we click the logout button in harbor.
  
1. While configuring, I have set keycloak oidc as primary authentication enabled.
2. Able to see keycloak login page as default when we try to enter harbor UI.
  
![image](https://github.com/user-attachments/assets/f8cc201c-e40f-4e37-bc95-cf9e46c17b4d)

3. The login process is working fine.
4. When we click on the logout button, the user will be redirected to this page.
   
![image](https://github.com/user-attachments/assets/a791fbe8-7c0e-46f3-8c13-3869a0c45d40)
5. When the user clicks on login with the OIDC provider button, it will redirect again to the previous user active  session

Expected Behaviour:

1. When the user clicks on the logout button in the HarborUI, the user needs to logout and needs to redirect to Keycloak login without showing the default login page of Harbor.

harbor version : v2.9.1-5cbb1b01

**Comment by stonezdj** [comment]
Duplicate with the known issue: https://github.com/goharbor/harbor/issues/12634
