### ISSUE TITLE
GC - Artifacts uploaded in the past 2 hours NOT are excluded

### ISSUE THREAD

**Issue by antoinesax** [goharbor/harbor#21266]
**Expected behavior and actual behavior:**
We are running shceduled GC every 1h, as per documentation `Artifacts uploaded in the past 2 hours(the default window) are excluded from garbage collection`. But actually, they are not excluded.

**Steps to reproduce the problem:**
Push an untagged image to the registry.
Perform GC just after this, it will delete the image

**Versions:**
Harbor, Version v2.10.2-1a741cb7, running in a K3s cluster.

**Comment by Jellyfrog** [comment]
Same with 2.12.0

**Comment by chlins** [comment]
Could you check the environment variable `GC_TIME_WINDOW_HOURS` in the core container?

**Comment by antoinesax** [comment]
```harbor [ /harbor ]$ env | grep GC_TIME_WINDOW_HOURS
harbor [ /harbor ]$ ```
It's not present

**Comment by stonezdj** [comment]
It is designed, the untagged image will be removed when the GC option of `Delete untagged image` is enabled.
