### ISSUE TITLE
Authorized members of LDAP groups not able to view private projects

### ISSUE THREAD

**Issue by anokun7** [goharbor/harbor#21286]
LDAP authentication with Active Directory (AD) is enabled, and users can successfully log in. I've established a group linked to an AD group containing several members and assigned it Project Admin rights to a **private** project. Despite this, group members can't access the private project; they can only see public ones. However, when I add these members individually as users to the project, they gain access to the private project and are able to view it appropriately. Please note that the group is a regular group and not a nested group.

**Expected behavior and actual behavior:**
Expected: Members of authorized LDAP group should be able to view private projects to which the group has been assigned to.

Actual: When members list the projects, they are able to see only public projects and none of the private projects they have been assigned through their group membership show up.

**Steps to reproduce the problem:**
1. Create a group and enter the Ldap Group DN and name. Let's call this `VCPSEngr` backed by the ldap group: `cn=vcpsengr,ou=groups,ou=iso,dc=acme,dc=com`
2. Create a private project. Let's call it `bgalapon`
3. In the members tab, add a new group member and enter `VCPSEngr` and assign `Project Admin` role.
4. Logout and log back in with a user that is a member of the LDAP group `cn=vcpsengr,ou=groups,ou=iso,dc=acme,dc=com`.
5. Click on `Projects` and the private project `bgalapon` is not visible.
6. If you add the user directly as a member of the private project, then the project is visible.

Attaching [debug logs](https://github.com/user-attachments/files/18011583/ldap_core_logs.txt) from harbor-core. From the logs, it seems the LDAP group is not being checked before authorizing view access to private projects. 
The private project has id `4` with the Group backed by the LDAP group `cn=vcpsengr,ou=groups,ou=iso,dc=acme,dc=com` granted Project Admin access.
The user in question is `anookuma` who is a member of the group `cn=vcpsengr,ou=groups,ou=iso,dc=acme,dc=com` as confirmed from the logs too (line 259). It is not a nested group either, just a simple group with members inside. We use AD, fyi.
However, in line 786 in the logs `Request: anookuma, /project/4, read ---> false`
I cant see in the debug logs where the group membership is being checked. I also can't seem to make sense of lines 775 - 784 in the debug log.
![image](https://github.com/user-attachments/assets/012cef58-ec61-414c-beee-662a82b2400b)
![image](https://github.com/user-attachments/assets/b2e189bd-58cd-40f0-b6d8-ec514e663edc)

**Comment by stonezdj** [comment]
Did you configured the field:  LDAP group filter ? 

> LDAP Group Filter: The filter to search for LDAP/AD groups. for OpenLDAP: objectclass=groupOfNames. for Active Directory: objectclass=group. This field cannot be empty when LDAP group feature is enabled.

**Comment by anokun7** [comment]
@stonezdj Thanks. That was what I was missing!
