### ISSUE TITLE
Proposal - Build K8S deployment registry into harbor

### ISSUE THREAD

**Issue by vmtocloud** [goharbor/harbor#2128]
Basically build https://github.com/helm/monocular into harbor

**Comment by steven-zou** [comment]
@vmtocloud 

Harbor supports Helm Chart repository based on ChartMeseum from the release version https://github.com/goharbor/harbor/releases/tag/v1.6.0

Match your expectation?

**Comment by vmtocloud** [comment]
👍 Nice! Yes!
Kind Regards,

Ryan Kelly, VCP-NV, vExpert
Staff Systems Engineer – VMware Cloud on AWS  SET Team – Cloud Native Apps SME
Member of the CTO Ambassadors Program
rkelly@VMware.com @vmtocloud www.vmtocloud.com
510.846.7875



[cid:A664B3F0-A31E-432F-A9F1-D81D17E1ECD0]

**Comment by steven-zou** [comment]
@vmtocloud 

  Got it, thanks! And welcome feedback.

**Comment by steven-zou** [comment]
Close this issue as our current chart management match the expectations of our community user.
