### ISSUE TITLE
2.12.0 not tagged at latest release

### ISSUE THREAD

**Issue by SebastianThorn** [goharbor/harbor#21303]
2.12.0 not tagged at latest release.
I'm assuming that 2.12.0 should be considered latest.

**v2.12.0**
![image](https://github.com/user-attachments/assets/554c57e1-9d8f-46f3-a035-f4217896701e)

**v2.11.2**
![image](https://github.com/user-attachments/assets/97841fe6-9703-4f93-ab39-6a94e6928733)

**Comment by Vad1mo** [comment]
It is moderately confusing; however, it is important to note that the latest release is not necessarily the highest version.

**Comment by SebastianThorn** [comment]
> It is moderately confusing; however, it is important to note that the latest release is not necessarily the highest version.

Why would this not be the desired case, I'm I missing something?
Is there some other place where I fetch the greatest version?

We are using the github-api to get the latest version of several applications, programs and components.

Br
Sebastian Thörn

**Comment by SebastianThorn** [comment]
Using this: https://endoflife.date/harbor and https://endoflife.date/api/harbor.json
