### ISSUE TITLE
I would like to ask a question. Harbor is configured with LDAP mode. Can I use OIDC to log in without changing the configured LDAP mode?

### ISSUE THREAD

**Issue by kevinwang6** [goharbor/harbor#21328]
Hello, I would like to ask a question. Harbor is configured with LDAP mode. Can I use OIDC to log in without changing the configured LDAP mode? Thank you.

**Comment by Vad1mo** [comment]
no

**Comment by kevinwang6** [comment]
> 不

Hello, I would like to ask a question. Harbor is currently connected to LDAP and is already used by a large number of users. Now we need to add a single sign-on (SSO) unified login method based on the original LDAP. Is it possible? Thank you.
