### ISSUE TITLE
Consultation on Harbor single sign-on

### ISSUE THREAD

**Issue by kevinwang6** [goharbor/harbor#21332]
Hello, I would like to ask a question. Harbor is currently connected to LDAP and is already used by a large number of users. Now we need to add a single sign-on (SSO) unified login method based on the original LDAP. Is it possible? Thank you.

**Comment by Aizhangwq** [comment]
同样的问题Ldap切换到oidc认证模式，ldap怎么清理
1.数据库修改project 的归宿为admin
2.数据库harbor_user只保留admin用户
但是admin登录时报错，因为还存在ldap认证模式
应该怎么做啊

**Comment by stonezdj** [comment]
If your SSO support OIDC, then you can switch from LDAP to OIDC auth. 
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication

```
When LDAP UID setting is changed, some LDAP user can not login

[A] Because the LDAP user have logged in with different UID, some user information is cached in the Harbor DB. you can clean up the user information and try login again.

docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user;
 delete from harbor_user where user_id > 2;
```
After that you can switch auth mode to oidc_auth.
