### ISSUE TITLE
Is it possible to configure authMode: oidc in Harbor using values.yaml

### ISSUE THREAD

**Issue by hkhan-apporto** [goharbor/harbor#21334]
**Context**
I am trying to set up authentication for Harbor using Azure Active Directory (Azure AD) with OpenID Connect (OIDC). I would like to configure this integration using the values.yaml file while deploying Harbor via Helm.

**My Current Approach**
Here is the relevant portion of my values.yaml:
> harbor:
>>   authMode: oidc
>>  oidc:
>>>     providerName: "Azure AD"
>>>     providerEndpoint: "https://login.microsoftonline.com/<tenantId>/v2.0"
>>>     clientId: "<appClientId>"
>>>     clientSecret: "<clientSecret>"
>>>     scope: "openid,profile,email,groups"
>>>     verifyCert: true
>>>     groupClaimName: "groups"
>>>     autoOnboard: true
>>>     usernameClaim: "preferred_username"

   
Additionally, I plan to map specific Azure AD groups to Harbor roles, such as:

  `userGroups:
    - groupName: "<azure-ad-group-id>"
      role: "projectAdmin"`
      
   **Question:**

1. Is this configuration valid for enabling authMode: oidc in Harbor?
2. Are there any specific requirements or additional steps I need to follow for this to work (e.g., special settings in Azure AD or Harbor)?
3. If group-based RBAC mapping (userGroups) is supported in values.yaml, how should it be structured?

**What I Have Tried:**
I referred to the Harbor documentation for OIDC authentication, but I am unclear if all these configurations can be managed via values.yaml.

**Environment Details:**
  Harbor Version: <your harbor version>
  Deployment: Helm Chart
  OIDC Provider: Azure AD

**Expected Outcome**
  Enable authMode: oidc with Azure AD.

**Comment by Vad1mo** [comment]
Please read about `CONFIG_OVERWRITE_JSON` in  https://goharbor.io/docs/2.12.0/install-config/configure-system-settings-cli/

**Comment by hkhan-apporto** [comment]
@Vad1mo Thanks
this is the PR what I needed: [harbor-helm/pull/1826](https://github.com/goharbor/harbor-helm/pull/1826)

Now the issue is that I need a way to map a group from Azure AD to a Role in Harbor
**Example**: I want that 
1. Harbor-Admins from AzureAD are assigned the role of HarborAdmins 
2. Docker-Experts from AzureAD are are assigned the role of Harbor Maintainer
3. Developers from AzureAD are assigned the role of Developer in Harbor 

Can you suggest some stuff on this as I;m unable to find
