### ISSUE TITLE
Harbor 认证模式修改

### ISSUE THREAD

**Issue by Aizhangwq** [goharbor/harbor#21333]
ldap认证模式切换到oidc认证模式，ldap怎么清理？
我的以下操作：
1.数据库修改owner_id为admin
UPDATE project SET owner_id = <admin_id> WHERE owner_id = XXX;
2.数据库harbor_user只保留admin用户
DELETE FROM harbor_user WHERE user_id <> 1;

但是admin登录时报错，因为目前还是ldap认证模式这个问题要怎么解决啊

**Comment by stonezdj** [comment]
You should  strictly follow this wiki: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#ldap

**Comment by Aizhangwq** [comment]
> 你应该严格遵循这个 wiki：[https ://github.com/goharbor/harbor/wiki/Harbor-FAQs#ldap](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#ldap)
我执行的是：
UPDATE harbor_user SET password = md5('Harbor12345') WHERE username = 'admin';
文档中给出的是：
update harbor_user set salt='', password='' where user_id = 1; 
是否是因为我未修改salt=null  导致的登录报错
![Uploading screenshot-20241219-160938.png…]()

**Comment by Aizhangwq** [comment]
@stonezdj
