### ISSUE TITLE
Error response from daemon: Get "https://harbor-xxxx": dial tcp: lookup harbor-labnum.aphp.fr on xx.XXX.XX:53: no such host

### ISSUE THREAD

**Issue by lijie123bes** [goharbor/harbor#21336]
i have installed harbor registring with docker compose and it works as expected.
but when i rtry to do docker login https://harbor-domain-name it gives me this error :
Error response from daemon: Get "https://harbor-domain-name/v2/": dial tcp: lookup harbor-domain-name on xx.XX.XX:53: no such host

**Comment by chlins** [comment]
You need to ensure that the domain name provided during Harbor installation can be resolved by DNS.
