### ISSUE TITLE
Modify value of secretkey_path in harbor.cfg doesn't work.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#2134]

**Comment by reasonerjt** [comment]
Maybe we should consider allow user to dynamically update "/data" during prepare.

**Comment by ywk253100** [comment]
@reasonerjt Agree. #2284 also describes the need.

**Comment by ywk253100** [comment]
The API GET /api/systeminfo/capacity should calculate the capacity of directory configured by user as mentioned in #2399 .

**Comment by tedli** [comment]
because the mount path in `docker-compose.yml` is hard coded as

```yaml
volumes:
  - /data/config/:/etc/adminserver/config/:z
  - /data/secretkey:/etc/adminserver/key:z
  - /data/:/data/:z
```

i altered the path to the correct place i've specified in harbor.cfg and all services run.

**Comment by ykfq** [comment]
I faced the same issue, but I still changed the path of harbor by doing this:
```
vim docker-compose.yml
:%s/\- \/data/\- \/data\/harbor/g  #replace "- /data" whit "- /data/harbor"

vim harbor.cfg
secretkey_path = /data/harbor  #change secretkey_path to the new path

docker-compose down  #remove all harbor containers

./prepare  #generate new config files 

docker-compose up -d  #start new harbor 

#optional
docker network create --driver bridge harbor_harbor --subnet 10.0.0.0/24  #create harbor network with specified sebnet instead of using the default value 172.17.0.0/16, which conflic with my office network.
```

**Comment by jmarceli** [comment]
How about creating **.env** file with **./prepare** script and then using variables inside **docker-compose.yml** (instead of hardcoded values)?
https://docs.docker.com/compose/env-file/
It should be easy to implement.

**Comment by ArcticSnowman** [comment]
The setting in the config file does not seem to be used...  `prepare` loads it but does not write it out anywhere..

**Comment by ArgonQQ** [comment]
Anything new here? Would be highly appreciated to be able to configure the storage endpoint on the file system.
