### ISSUE TITLE
Data not deleted from object storage (s3)

### ISSUE THREAD

**Issue by arezvani** [goharbor/harbor#21348]
Hi
I have installed Harbor and set my backend storage to S3. I tested it with both Ceph and Swift. The problem I'm facing is that when I delete an image from Harbor, it still remains in the object storage and is not deleted. 
Where is the issue? 
I have also set disableredirect to true, but the problem persists.

**Comment by wy65701436** [comment]
have you ever executed the GC after you remove the image from harbor UI?

**Comment by arezvani** [comment]
Yes sometimes it works. sometimes not works.
But don't you think this is a problem? I delete my image from Harbor, but it doesn't get removed from the object storage, and I have to manually or periodically run GC. If the number of images being pushed and deleted at the same time is large, and the images are not removed before that interval, my storage gets filled up.

**Comment by Vad1mo** [comment]
You will hit the physical limitations, if you push more than you have storage available. This doesn't have anything to do with Harbor. 


One note about the GC: Harbor only considers images for GC that have been pushed more than 2h ago. 
So pushing image, removing image and running GC will not free up the space on the storage. If you run GC again in 2h it will

**Comment by arezvani** [comment]
Can this time (2h) configured to a shorter value?
I delete my image so I want to delete that also from object storage to free up the space.
Why doesn't Harbor delete images from object storage automatically?
