### ISSUE TITLE
Description feature to repositories

### ISSUE THREAD

**Issue by szabobar** [goharbor/harbor#2228]
Dear Harbor team,

Thanks for the great UI, but I missed an important feature: description part to each repository.

If you see the hub.docker.com, there is a full description part in UI in every repository. This is useful, because you can read instantly the documentation to every repository.

Thanks

**Comment by timiil** [comment]
+1 
very useful

**Comment by yayuntian** [comment]
Hope to achieve early

**Comment by wphe** [comment]
Any update on this?

**Comment by LoLei** [comment]
Seems like this is working now, although it is only plaintext and does not parse Markdown or HTML.

**Comment by reasonerjt** [comment]
Description to a repository is supported now, closing.
