### ISSUE TITLE
On Photon OS - questions on network.

### ISSUE THREAD

**Issue by steveschofield** [goharbor/harbor#2230]
Not sure if this is a photon or docker issue....starting here.  I've setup custom docker network because our internal networking already uses 172.x.  I used 192.168.3.0/24, when I run docker network inspect bridge, the 192.168.3.0/24 network shows up.  When I run ifconfig, this is shown for docker.

docker0   Link encap:Ethernet  HWaddr 26:70:b7:6e:86:a1  
          inet addr:192.168.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::2470:b7ff:fe6e:86a1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:24 errors:0 dropped:0 overruns:0 frame:0
          TX packets:79 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1608 (1.6 KB)  TX bytes:6330 (6.3 KB)

When I start docker....I get another entry when typing ifconfig

veth09cafd1 Link encap:Ethernet  HWaddr 82:8b:17:7e:9e:bf  
          inet6 addr: fe80::808b:17ff:fe7e:9ebf/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19 errors:0 dropped:0 overruns:0 frame:0
          TX packets:111 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1815 (1.8 KB)  TX bytes:9887 (9.8 KB)

When I install harbor, I get another network when typing ifconfig.  Notice 172.17.0.1 network. 

br-87c3ade6f313 Link encap:Ethernet  HWaddr 02:42:1b:59:a0:d4  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:1bff:fe59:a0d4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:186 errors:0 dropped:0 overruns:0 frame:0
          TX packets:172 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:9014 (9.0 KB)  TX bytes:33519 (33.5 KB)

if you want the raw output from ifconfig, let me know....

Looking to run photon within our environment as container hosts.

**Comment by steveschofield** [comment]
Update - I installed the latest Docker Engine 17.04 and still same behavior, it's like Harbor ignores custom networks setup on Docker engine and uses default.

**Comment by hainingzhang** [comment]
As I mentioned in the Slack channel:

After a reboot of the VM, you need to bring up Harbor manually. You can run the command under Harbor's directory:   docker-compose up -d

You can also put Harbor into the system bootstrap process so that it can automatically start Harbor for every reboot.

**Comment by steveschofield** [comment]
I've made progress.  Here is what I do, I upload offline install to /tmp/harbor.   I run install.sh, things work except for testing our internal email.  When I restart, I'm not sure what you mean by "Harbor's" directory.  Can you explain or point me to the docs?

Here is the stats
root@server [ /tmp/harbor/common/config ]# docker-compose up -d
ERROR: Couldn't find env file: /tmp/harbor/common/config/adminserver/env

Results
root@server  [ /tmp/harbor/common/config ]# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                          PORTS                     NAMES
1abebab4d902        vmware/nginx:1.11.5-patched            "nginx -g 'daemon ..."   About an hour ago   Restarting (1) 55 seconds ago                             nginx
c9a49735e301        vmware/harbor-jobservice:v1.1.1-rc3    "/harbor/harbor_jo..."   About an hour ago   Exited (127) 22 minutes ago                               harbor-jobservice
aa96f59b1b5a        vmware/harbor-ui:v1.1.1-rc3            "/harbor/harbor_ui"      About an hour ago   Exited (127) 22 minutes ago                               harbor-ui
a38e41dc0bee        vmware/registry:photon-2.6.0           "/entrypoint.sh se..."   About an hour ago   Restarting (1) 53 seconds ago                             registry
53af5e0b95f0        vmware/harbor-db:v1.1.1-rc3            "docker-entrypoint..."   About an hour ago   Up 20 minutes                   3306/tcp                  harbor-db
78c39b7597a0        vmware/harbor-adminserver:v1.1.1-rc3   "/harbor/harbor_ad..."   About an hour ago   Up 20 minutes                                             harbor-adminserver
2c7a384a5b98        vmware/harbor-log:v1.1.1-rc3           "/bin/sh -c 'crond..."   About an hour ago   Up 20 minutes                   127.0.0.1:1514->514/tcp   harbor-log

**Comment by steveschofield** [comment]
Is this documented somewhere?

"You can also put Harbor into the system bootstrap process so that it can automatically start Harbor for every reboot."

**Comment by steveschofield** [comment]
Here are steps I'm using. 

Summary to get latest Docker engine
============================================
1) deploy photon minimal (either set static or DHCP)
2) tdnf update
3) reboot
============================================

#Remove docker on photon 1.0
tdnf erase -y docker

#Add TAR and GZIP packages
tdnf install -y tar gzip

============================================
#Download latest version
#
curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz && tar --strip-components=1 -xvzf docker-17.04.0-ce.tgz -C /usr/bin
tdnf install -y tar gzip

============================================

groupadd -r docker

============================================

echo '[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -H fd:// -s overlay2 
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Delegate=yes
KillMode=process

[Install]
WantedBy=multi-user.target
' > /etc/systemd/system/docker.service

============================================

echo '[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
' > /etc/systemd/system/docker.socket

systemctl enable docker
systemctl start docker

#download offline installer
upload /tmp/harbor
chmod -R 777 /tmp/harbor

config the harbor.cfg
run ./install.sh

Reboot and see what you see.  I'd rather not post logs, if someone from vmware wants them, I can open a case or email.

**Comment by reasonerjt** [comment]
Closing as this issue seems fixed.

However a better way is to set the IPAM of the network in docker compose template.
