### ISSUE TITLE
[Feature Request] Multi-signed images

### ISSUE THREAD

**Issue by cavemandaveman** [goharbor/harbor#2324]
Similar to the workflow descibed in [this blog post](https://blog.docker.com/2016/11/image-signing-policy-docker-datacenter/) for Docker Trusted Registry, it would be nice to be able to allow multiple signatures on an image.

Also, if we can define the amount of _required_ signatures and combine that with #2323, we can set up a workflow just like in Docker Trusted Registry. This would be great help towards integrating Harbor into a more complete CI/CD process.

**Comment by reasonerjt** [comment]
After reading the originally blog post, we may want to look into this and investigate the possibility when there's requirement to more complicated checking regarding signatures.

But I don't recall there's a good way to figure out who signed the image.

**Comment by xaleeks** [comment]
multi keys is being investigated by notary v2 atm
