### ISSUE TITLE
Need more code checking in CI.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#2338]
We need to enhance it,
such as space .vs. tab, line ending of src code and .md files...

@wy65701436 let's discuss and improve it.

**Comment by wdhif** [comment]
Hi @reasonerjt

I just wanted to give an update about this. I'm currenlty working on the image hardening of the Harbor images (#3061) and i've noticed a lot of line endings and trailing spaces problems.

I've run those commands to get rid of the windows lines endings and trailing spaces.

- `find . -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 perl -pi -e 's/ +$//'` for the trailing whitespaces.
- `find . -type f -print0 | xargs -0 dos2unix` for the line endings.

I got 359 files modified, you can check the modifications here : https://github.com/wdhif/harbor/tree/clean

**Comment by reasonerjt** [comment]
We'll re-plan enhanement in CI, closing this one.
