### ISSUE TITLE
cache tags in db

### ISSUE THREAD

**Issue by dongxiaojiehit** [goharbor/harbor#2352]
cache repository in present harbor, Will cache tags information in db in future?

**Comment by reasonerjt** [comment]
Perhaps not in very near future, if you need enhancement in this part, could you elaborate your scenario and why you think it's necessary.

**Comment by nanpuyue** [comment]
仅用作mirror的时候，显示仓库列表都十分缓慢，tag甚至几乎不能显示出来，api/repositories/xxx/xxx/tags?detail=1从来都是504……

**Comment by reasonerjt** [comment]
I believe the perf has improved after we retrieve the tag details in parallel so as for now we won't cache tag details.
