### ISSUE TITLE
1.1.1 traces in DEBUG mode

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#2354]
In version 1.1.1 lot of traces are in DEBUG mode, how can I configure the log in INFO/ERROR mode ? any idea ?

**Comment by roldancer** [comment]
Looking at the ui container, there is a LOG_LEVEL env variable, may I change that env variable to info ?


# docker exec -ti harbor-ui /bin/bash
root [ /harbor ]# 
root [ /harbor ]# 
root [ /harbor ]# 
root [ /harbor ]# 
root [ /harbor ]# env
HOSTNAME=e441hhhc2bb80
UI_SECRET=........
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/harbor
JOBSERVICE_SECRET=.........
CONFIG_PATH=/etc/ui/app.conf
SHLVL=1
HOME=/root
**LOG_LEVEL=debug**
GODEBUG=netdns=cgo
_=/usr/bin/env

**Comment by ywk253100** [comment]
You can change the log level in common/config/ui/env file and restart Harbor after that.

**Comment by reasonerjt** [comment]
Maybe we could add that to admin server also?  @ywk253100

**Comment by roldancer** [comment]
Hi, The following container's have the LOG_LEVEL env variable:

harbor-jobservice
harbor-ui
harbor-adminserver
