### ISSUE TITLE
change tag list order

### ISSUE THREAD

**Issue by coolaxie** [goharbor/harbor#2544]
Tag list is ordered by time asc.
but I want the latest tag show in first?

**Comment by srm912** [comment]
I would like to work on this, if nobody else has taken it up.

**Comment by srm912** [comment]
This tag list display works in a very peculiar way. 
As you mentioned, the tag list is ordered by the creation times. See, tags 2.0 and 1.0
<img width="1036" alt="screen shot 2017-07-26 at 11 43 41 pm" src="https://user-images.githubusercontent.com/8758225/28657694-11e4f4ac-725d-11e7-862a-09b418caa43d.png">

But if there are subsequent updates to the tags, the list still appears in the same order as before, even though the creation time column in the UI is updated.
<img width="1015" alt="screen shot 2017-07-26 at 11 47 44 pm" src="https://user-images.githubusercontent.com/8758225/28657693-11e1a568-725d-11e7-8e4c-e2e53f3c7284.png">

**Comment by clouderati** [comment]
Hi @srm09 – thanks for taking the time to look at this. Can you confirm this is an issue with the latest build? We're happy to help you wade through the codebase if there's a fix needed.
