### ISSUE TITLE
Password reset asks user to fill the email, which is confusing considering security.

### ISSUE THREAD

**Issue by blanet** [goharbor/harbor#2609]
I am attempting to use harbor in my team and tried harbor's functionality recently. 
Harbor allows users to reset their pass, but I'm confused by the mechanism harbor used. There's a popup for user to enter their email, and then harbor sends a link to the email (without checking whether the email belongs to the user). 
I know a "wrong" email will not reset user's pass successfully, but during the whole process harbor always alerts success info.
I think the pass reset mechanism should not popup a window and asking user to enter email (at least harbor should check the email before sending the pass reset link).

**Comment by reasonerjt** [comment]
>I know a "wrong" email will not reset user's pass successfully, but during the whole process harbor always alerts success info.
I think the pass reset mechanism should not popup a window and asking user to enter email (at least harbor should check the email before sending the pass reset link).

Hi, Are you suggesting before sending the Email Harbor should also ask for user's username?  And the username and Email will have to match?

**Comment by Planet2010** [comment]
Yes, current mechanism seems strange and probably unsafe. 
Require both username and the matching email will be UI friendly(at least the user knows harbor is taking to himself) and prevent trigger annoying reset pwd email by others.

**Comment by clouderati** [comment]
I agree that we can probably make this interaction a bit better. @lweitzman – do you have any workflows that you can share around this particular (common) mechanism?

@xingx-xx – thanks for bringing this up. We'd appreciate contributions to make this workflow better. 😉

**Comment by xaleeks** [comment]
this will be deprecated in 2.0 fyi
