### ISSUE TITLE
Default Bridge network overlaps with internal subnet

### ISSUE THREAD

**Issue by timgriffiths** [goharbor/harbor#2634]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.11.2, build dfed245

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
not required
3)Log files, you can get them by package the /var/log/harbor/ .
not required

Problem:
By default harbor creates it's own bridge network 
```
networks:
  harbor:
    external: false
```
the problem is i can't tell the docker daemon which subnet to create start from (https://github.com/moby/moby/issues/21776) and unfortunately i am unlucky enough that the subnet chosen overlaps with one of our internal subnets.

I can simply hack up the compose file and fix this but won't be very portable though upgrades.

Happy to look at implementing a new config option if someone points me in the right direction

**Comment by reasonerjt** [comment]
I'm afraid currently you have to do the hack, but this is a valid request we'll consider it.

**Comment by moooofly** [comment]
solved by

- step 1: `docker-compose down -v`
- step 2: modify `docker-compose.yml`
```
...
networks:
  harbor:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
```
- step 3: `docker-compose up -d`

**Comment by clouderati** [comment]
Thanks @moooofly – appreciate the feedback and workaround. @reasonerjt does it make sense for @moooofly to document this in our wiki as a workaround?

**Comment by FengyunPan2** [comment]
I met it too, thx
