### ISSUE TITLE
Permission on the replication functionality

### ISSUE THREAD

**Issue by It4lik** [goharbor/harbor#2661]
Hi, 
I was wondering if is there any plan to extend Harbor's configuration on this point. 

Only the system administrator can currently create new replication endpoints, and replication policy.

Two questions from there : 

- as a sysadmin, I'd like to setup Harbor with some replication endpoints preconfigured (need for repeatability), is there anyway to do this (other that manually inject data in mariadb?)
- is there any way to give the ProjectAdmin the right to choose to replicate his own projects ? I mean, I got to manually connect on the WebUI and create a new replication rule, for each projects, for each users who wants this feature enabled ? Mmmh

Regards, 
it4

**Comment by reasonerjt** [comment]
Thanks @It4lik  for the suggestion, we'll consider to make the change in future release.

**Comment by clouderati** [comment]
@It4lik – thanks for bringing this up; certainly reasonable feedback. We love code contributions for things like this. 😄 

I shivered a bit at the idea of injecting data into the database; have you looked at potentially using our API to address some of your concerns?

I'll leave this open awaiting your feedback @It4lik.
