### ISSUE TITLE
delete a tag of repo but all tags are removed

### ISSUE THREAD

**Issue by fffffreedom** [goharbor/harbor#2663]
[root@localhost harbor]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64
[root@localhost harbor]# docker-compose -version
docker-compose version 1.14.0, build c7bdf9e

hi
 i want to delete a tag using curl cmd, but it turns out that all tags will be deleted,

[root@localhost harbor]# curl -u admin:Harbor12345 -X GET http://registry.vivo.com/api/repositories/test/busybox/tags
[
  "v1",
  "v10",
  "v2"
][root@localhost harbor]#  
[root@localhost harbor]# curl -u admin:Harbor12345 -X DELETE http://registry.vivo.com/api/repositories/test/busybox/tags/v10
[root@localhost harbor]# curl -u admin:Harbor12345 -X GET http://registry.vivo.com/api/repositories/test/busybox/tags
[][root@localhost harbor]# 

thanks

**Comment by reasonerjt** [comment]
This is a limitation, registry only accepts using digest to DELETE tag

In your case, I believe all the tags are having same digest

**Comment by fffffreedom** [comment]
yes, they do have the same digest. thanks!
but what does "registry only accepts using digest to DELETE tag" means?
i can remove the tag from the harbor web。
@reasonerjt

**Comment by reasonerjt** [comment]
Harbor calls the registry's API to delete the tag of image.

https://docs.docker.com/registry/spec/api/

**Comment by KeithTt** [comment]
@reasonerjt  In my case, images with same digest will be removed though whether UI or CURL.

But I only want to remove the tag which I passed in the url...

**Comment by lycclsltt** [comment]
In my case, images with same digest will be removed though whether UI or CURL.

**Comment by lycclsltt** [comment]
How to solve this problem? I want to delete tag A bug A, B all were be removed?

**Comment by lycclsltt** [comment]
> @reasonerjt In my case, images with same digest will be removed though whether UI or CURL.
> 
> But I only want to remove the tag which I passed in the url...

How do you solve this problem ?

**Comment by xaleeks** [comment]
we're working on a solution for this, please ping me to share requirements and use cases. xalex@vmware.com

**Comment by renmaosheng** [comment]
this impacts the tag retention results as well, reopening and tracking it for future versions.

**Comment by xaleeks** [comment]
Yep, the solution right now is if there's even a single tag that should be retained due to retention policy configured, all tags pointing to the same digest are also retained.  So it's really performing 'digest retention'.  This is unsolvable unless we solve deleting tags independently of other tags first.

**Comment by xaleeks** [comment]
we will tackle this in upcoming 1.11 release so you can delete a tag without deleting all the other tags referenced by this underlying manifest.

**Comment by xaleeks** [comment]
https://docs.google.com/document/d/11-F2llO3Hm0xjxfHj9maq9X6WYbZDk-ZZPbLfVai-YI/edit

prd here, ping me for access

**Comment by pgkulkarn** [comment]
@xaleeks Thank you! where can I find the release schedule? What is the release date for 1.11?

**Comment by bitsf** [comment]
target release 2.0, maybe no 1.11 any more

**Comment by pgkulkarn** [comment]
Ok, thanks @bitsf

**Comment by tianon** [comment]
I think it's probably worth pointing to the (relevant) discussions happening over in the OCI at https://github.com/opencontainers/distribution-spec/issues/102 around this topic :smile: :+1:

**Comment by reasonerjt** [comment]
Fixed in master as the tag can be managed in 2.0

**Comment by SathishSuresh-opex** [comment]
Any updates on this issue?

**Comment by gunboe** [comment]
Same problem here harbor v1.10.2

**Comment by raarceoml** [comment]
Will this fix be ported to v1 ?
