### ISSUE TITLE
[Discussion] Harbor HA feature design

### ISSUE THREAD

**Issue by m-masataka** [goharbor/harbor#2691]
I want to build and set up a High availability Harbor cluster.
Supporting HA deployment is written in ROADMAP but there is few implementation and issue/discussions become old #327 . 
Let's discuss about HA  scenario/solutions.

My scene is:
I have two datacenter. I want to deploy harbor to each datacenter in Active/Active cluster. 
In my scene, we have to implement 
- Synchronize harbor-db
- Synchronize registry backend storage or caching each other storage(see [registry issue](https://github.com/docker/distribution/issues/1431))
- develop cluster management system

For your reference, my first implementation is there #2621

**Comment by clouderati** [comment]
Hi @m-masataka – thanks for bringing this up.

Can I ask you to please elaborate on your second and third point (specifically: sync backend storage / create cluster management system)? Would love to better understand your ideas.

Would you be willing to hop on our community call next week? This is a common ask and I think deserves a lengthy conversation.

**Comment by m-masataka** [comment]
Hi @clouderati .
thank you for your reply.

I think second point ( sync backend storage) is now solved by registry mirror ( see [here](https://github.com/moby/moby/pull/34319)).
Third point, requirement of cluster management is also satisfied by Integration with k8s.
But if we develop scale-out systems, we need to integrate with database clustering system on k8s ( such as [Vitess](https://vitess.io/) ).

I'm interested in the conversation. What is the main topic? and when will the community call  be held?
