### ISSUE TITLE
update make/kubernetes/* to adapt to current compoments

### ISSUE THREAD

**Issue by thomassun** [goharbor/harbor#2739]
the files in make/kubernetes is outdated, for example, there is no config for adminserver, 
please update.

**Comment by xmavrck** [comment]
+1

**Comment by goindwalia** [comment]
+1

**Comment by gensmusic** [comment]
+1

**Comment by arthaslll** [comment]
+1

**Comment by jenningsloy318** [comment]
+1

**Comment by reasonerjt** [comment]
Please refer to the helm chart:
https://github.com/goharbor/harbor-helm
It's now the maintained approach for deployment onto k8s.
