### ISSUE TITLE
建议增加镜像的描述信息，如dockerfile，run的启动脚本等。

### ISSUE THREAD

**Issue by muercy** [goharbor/harbor#2746]
查看镜像时，如果有dockerfile和启动方面信息展示，就太好了，方便镜像的内部传播和使用，减少沟通成本，更方便管理

**Comment by reasonerjt** [comment]
the issue is, we don't have a build engine, so there's no way to  ensure the consistency between image and docker file.

**Comment by whulyx** [comment]
哈哈我也觉得有个Dockerfile会效果更好。

**Comment by wangycc** [comment]
cool

**Comment by reasonerjt** [comment]
This should be mitigated after introducing the "history" of an image.

**Comment by reasonerjt** [comment]
Without further a due I'm closing this issue given user can see "history" of an image from UI.
