### ISSUE TITLE
we should isolate the storage used by registry from other harbor services

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#2781]
Currently storage in harbor is shared between registry and other services. When put large number of images to registry and used out all the spaces, other services will failed.

ideally we should isolate storage used by registry and other services

**Comment by reasonerjt** [comment]
I believe this can be achieved by mounting a volume to /data/registry?

**Comment by clouderati** [comment]
Agreed – this is likely something that can (should?) be addressed by the underlying Linux system. @yixingjia and thoughts, or should we close this out?
