### ISSUE TITLE
Full registry replication

### ISSUE THREAD

**Issue by tschwaller** [goharbor/harbor#2842]
As an administrator I would like to enable full registry replication in addition to the more fine granular replication available in Harbor today. This is useful for Harbor HA scenarios and also for registries with a lot of projects & images. It is one of the feature requests I hear most often from customers. One could also tag projects with a priority tag so their images get replicated with higher priority.

**Comment by clouderati** [comment]
Hi @tschwaller – thanks for the feedback. Simone should give you some cycles to contribute this new feature. 😄
