### ISSUE TITLE
Popular repositories should be optional

### ISSUE THREAD

**Issue by jlk** [goharbor/harbor#2844]
Folks - we have a use case where we want registries to be public, but not necessarily listed on the login screen. For immediate use we're going to pull the "Popular Repositories" code from the login screen and remove the API call. Would there be interest in having that as a feature, configurable via harbor.cfg?

**Comment by steven-zou** [comment]
@lweitzman @tonycgil 

  Please provide comments for this requirement. Thanks.

**Comment by lweitzman** [comment]
hi  - i would like to understand your use case a little better. could you explain why its different than hub.docker.com where you can see popular repos without logging in. that would be helpful - thanks.

**Comment by jlk** [comment]
We're setting up a public version of Harbor to distribute images to customers. For things like private betas, I'd like to be able to point a user at a non-published repository to grab the private beta version. It's not sensitive enough where I want to create and manage a login to access that repository, and I don't want users to have to worry about `docker login,` or that login timing out when they go to get a new image.

So a public repository works for this, but with the "Popular repositories" UI and API, anybody who hits the homepage can see the semi-private URL.

**Comment by jlk** [comment]
Just in case it's not clear from comment 1 above - I'm writing this, will host it in a public github repo. Only question is if you guys would be interested in a pull request for this functionality.

**Comment by lweitzman** [comment]
yes, lets make content on the login page (popular repos)  optional

**Comment by clouderati** [comment]
Love it @jlk. 'preciate the issue and idea.

PR would be very much welcomed. 😄

**Comment by jlk** [comment]
OK - we've been using it internally since last summer, will rebase and get a PR in hopefully within the week.

**Comment by steven-zou** [comment]
@jlk Welcome and thanks.

**Comment by clouderati** [comment]
Hi @jlk – are you still interested in contributing the patch? Happy to help if needed.

**Comment by jlk** [comment]
Yes! Sorry...I seem to be under constant severe time crunches. :/

I'm away for the weekend, but let me see what I can do next week. We have the code and are running it - still just need to rebase and clean up a little. Setting calendar reminder for mid next week...
