### ISSUE TITLE
Log should use consistent time and timezone

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#2859]
Currently, there are two datetimes with different timezones in the log files

Jul 25 08:00:24 172.18.0.1 ui[869]: 2017-07-25T00:00:24Z [DEBUG]

**Comment by aurthurxlc** [comment]
Timezone can also be modified in the harbor.cfg

**Comment by Hokwang** [comment]
I can't find timezone setting in harbor.cfg.
