### ISSUE TITLE
Docker Swarm Deployment

### ISSUE THREAD

**Issue by marcellodesales** [goharbor/harbor#2868]
I noticed you guys have `docker-compose.yml` files for deploying this solution in a single host. Have anyone spent time to deploy this in a docker swarm cluster using docker-compose v3?

**Comment by bweston92** [comment]
Any update on this?

**Comment by rroblik** [comment]
+1 : interested in an "official" answer :) 

I'm working on it with traefik[https://traefik.io] but I'm not able to successfully deploy it in my swarm stack ...

**Comment by clouderati** [comment]
We've not done any work on supporting Harbor on Swarm. Would appreciate contributions, however!

I'll close this out, but if there is interest in submitting a PR to make this work please comment and we can re-open and work together to make it happen.

**Comment by Power2All** [comment]
> I noticed you guys have `docker-compose.yml` files for deploying this solution in a single host. Have anyone spent time to deploy this in a docker swarm cluster using docker-compose v3?

Where is this docker-compose.yml file exactly ?
I might be able to get it working, since I converted a lot of single-system setups, using Portainer.

**Comment by FlySkyPie** [comment]
I put my attempt here: 
https://github.com/FlySkyPie/harbor-docker-swarm
Some secret would put in yaml, I didn't investigate further if harbor can read them from file to replace environment variable approach.

And this is version of docker compose:
https://github.com/FlySkyPie/harbor-docker-compose
