### ISSUE TITLE
[Request] User should know whether my daily scan job was executed or not. No way/log to check.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#2914]

**Comment by reasonerjt** [comment]
Isn't there log for the scheduler?

**Comment by wy65701436** [comment]
No scheduler log from UI.

**Comment by reasonerjt** [comment]
Well, so wthis won't be fixed until we provide some "scan all" jobs, so not possible in current approach.

**Comment by wy65701436** [comment]
It should show that my daily job was executed at 12:00AM at least. 
Otherwise, user may feel it's totally lost control.

**Comment by reasonerjt** [comment]
OK it should be easier if the scheduler can track the last execution based on policy, but let's see this as a UX enhancement.
