### ISSUE TITLE
API for logging into harbor for session credentials using LDAP?

### ISSUE THREAD

**Issue by cpeel** [goharbor/harbor#2963]
In 52f9e5f1, the `/login` URL was removed for LDAP-connected harbor instances. This appears to be the only URL available to programmatically authenticate into harbor to obtain session credentials for using other APIs, like `/api/projects` (or the other myriad APIs that require an authenticated user).

How are SDKs suppose to authenticate against LDAP-connected harbor instances to obtain session credentials?

**Comment by reasonerjt** [comment]
@cpeel You can use Basic authentication to call Harbor's API.

**Comment by cpeel** [comment]
Great. Is it safe to assume that applies to all the RESTful endpoints in both LDAP-connected and standalone modes, and not just the `/api/*` URLs?

**Comment by reasonerjt** [comment]
It is not.  But what endpoints are your particularly interested in?

**Comment by cpeel** [comment]
I'm trying to fix harbor-py such that it works for auth-required URLs for LDAP-attached instances. harbor-py queries a variety of `/api/*` URLs. After looking at `src/ui/router.go` I've already figured out that a few of them aren't available in LDAP-attached instances, which is fine. If the non-LDAP URLs in that file are the ones that need beegosessionID cookies vs basic auth that's a pretty easy delineation.

**Comment by clouderati** [comment]
Thanks @cpeel – from the sounds of it basic auth will work in your situation. Will close this out, but please re-open if needed.
