### ISSUE TITLE
prepare file didn't support python3.5+

### ISSUE THREAD

**Issue by Folyd** [goharbor/harbor#2968]
Raised SyntaxError when I run `sudo ./install.sh`, my python version is **3.5**, here is the error log:
```
[Step 1]: preparing environment ...
  File "./prepare", line 60
    os.makedirs(folder, mode=0600)
                                ^
SyntaxError: invalid token
```

Please fix this, thanks :)

**Comment by wy65701436** [comment]
@Folyd, thanks for pointing this issue. 

The prepare is now only support Python2, appreciate if you can contribute a PR to fix it.

**Comment by clouderati** [comment]
Hi @Folyd – happy to help walk you through the contribution process if you're interested. Else I'll keep this open and we'll do our best to get to it soon.
