### ISSUE TITLE
[Feature Enhancements] Image replication service

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#2984]
###  _Just some draft thoughts about image replication:_

Image replication service should be running as a separate service to easily support LB and HA.
Image replication should not be bound as internal service of one project.
Image replication should be driven by policy/rule

**Multiple sources of replication rule should be supported:**
  - User can select more than one projects for one replication rule
  - User can select repos/tags from the selected projects for one replication rule
  - Selection based on properties can be supported
  - Wildcard or regexp should be supported
  - Selection based on label can be supported

**Kinds of replication targets structure can be supported:**
  - Multiple targets
  - Targets in multiple levels
  - Replication source-target relationship chart displayed in UI with related real metrics data

**The replication executions should support precondition chains/filters:**
  - Timestamps/Period/Duration
  - Status checking
  - Stats change
  - Properties change
  - Limited counts of execution

 **Followup actions can be supported:**
  - Remove/delete source repo/images
  - Labeled repo/tags
  - Send notifications/reports
  - Update metrics stats

**Lifecycle management of replication:**
  - Queue
  - Dequeue
  - Start
  - Running (status report)
  - Cancel
  - Stop
  - Error
  - Re-queue

**Integrate with 3rd registries:**
  - Provide integration driver mechanism for integrating 3rd registries
  - Support replicate images (pull images) to Harbor
  - Provide related IDM capability for 3rd registries

**Comment by clouderati** [comment]
Thanks @steven-zou – very well thought out.

For those in the community heavily leveraging replication, would love some input as we enhance this feature.

**Comment by xkrt** [comment]
In my work, I use replication already with one master Harbor and two replicas in two DCs.
I interesting in following features:
* User can select repos/tags from the selected projects for one replication rule
* Selection based on label can be supported
* Send notifications/reports
* Re-queue

**Comment by Moumoutaru** [comment]
I would love to have replication span multiple projects. Say supporting wildcards or replicate based off of labels which span multiple projects.

**Comment by clouderati** [comment]
Hi @xkrt – what do you mean by re-queue?

@Moumoutaru – is your proposal that replication rules are not strictly bound to projects but can be configured based on metadata (e.g., labels) instead?

Please keep the comments coming everyone!

**Comment by xkrt** [comment]
@clouderati repeat failed replication job. maybe this already implemented, not sure.

**Comment by vgavrilenko** [comment]
Our project requires following 2 improvements:
* User can select more than one projects for one replication rule
* Send notifications/reports

**Comment by steven-zou** [comment]
@xkrt @Moumoutaru @vgavrilenko 

Replication improvement is working on and will be delivered in V1.8, please stay tuned!

**Comment by steven-zou** [comment]
For the implementation progress, please check the epic #6798.

**Comment by reasonerjt** [comment]
Closing this issue as the Replication NG has been delivered in v1.8, and further improvement is tracked by #7974
