### ISSUE TITLE
role table should set name/role_code as unique key

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#3007]
Feedback from user:
"In harbor mysql databse, the role_id column in role table is auto incremental, but when set ，auto-increment-increment=3 the id of the default role will change to 1,4,7 which result cannot assign "developer", "guest" roles.

create table role (
 role_id int NOT NULL AUTO_INCREMENT,
 role_mask int DEFAULT 0 NOT NULL,
 role_code varchar(20),
 name varchar (20),
 primary key (role_id)
);

**Comment by srm912** [comment]
On the top of my head, rather keeping the values of the roles constant, we can load these values from the DB on startup and make them available globally.

In 2 minds, as to whether it is a good idea. On one hand, we are decoupling the database values with the actual coding logic. On the other, how frequently will we come across this usecase.
