### ISSUE TITLE
image scanning error with Harbor 1.2.0.RC1

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#3031]
Hi All, I'm testing the Harbor 1.2.0.RC1, if I click in "Scan" I get the following error, any idea ?

Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:167","Time":"2017-08-10 21:32:14.260593"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:213","Time":"2017-08-10 21:32:14.260683"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2017-08-10 21:32:14.260806","packa
ge":"Alpine"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2017-08-10 21:32:14.261542","pack
age":"Oracle Linux"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2017-08-10 21:32:14.261823","packa
ge":"Debian"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2017-08-10 21:32:14.262493","package
":"RHEL"}
Aug 10 23:32:14 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:88","Time":"2017-08-10 21:32:14.262653","packa
ge":"Ubuntu"}
Aug 10 23:32:19 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"finished fetching","Level":"info","Location":"updater.go:227","Time":"2017-08-10 21:32:19.140819","updater name":"a
lpine"}
Aug 10 23:34:13 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"finished fetching","Level":"info","Location":"updater.go:227","Time":"2017-08-10 21:34:13.892969","updater name":"d
ebian"}
Aug 10 23:38:39 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2017-08-10 21:38:39.993296","e
rror":"tarutil: could not extract the archive","layer":"23d3085bc2780b78b4fb2a816f1cd81d53ef3c4d60de5481a20ca9445b3265a5","path":"http://registry:5000/v2/prueba/shellinabox/blobs/sha256:6
6afbec41e5301d8163eaf9541735670ab4b49b9a4a9f4c2ab386326084c5aa0"}
Aug 10 23:38:39 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-08-10 21:38:39.995727","elapsed time":1
8062503,"method":"POST","remote addr":"172.26.0.6:54891","request uri":"/v1/layers","status":"422"}
Aug 10 23:41:46 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2017-08-10 21:41:46.559695","e
rror":"tarutil: could not extract the archive","layer":"385abb0cd83a1b3839ffcb2b97db108c322325c45cb70ec43990ba6f39cd3998","path":"http://registry:5000/v2/prueba/javase/blobs/sha256:a812cd
d86d75f50d6788be6456b344ed3164a5021ab732565890191c5504cbe2"}
Aug 10 23:41:46 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-08-10 21:41:46.563343","elapsed time":2
35607848,"method":"POST","remote addr":"172.26.0.6:55199","request uri":"/v1/layers","status":"422"}
Aug 10 23:42:38 HP-ProBook-430-G1 docker/clair[3540]: {"Event":"finished fetching","Level":"info","Location":"updater.go:227","Time":"2017-08-10 21:42:38.111558","updater name":"u
buntu"}

**Comment by wy65701436** [comment]
thanks @roldancerl, can you help to package all the logs?

**Comment by yixingjia** [comment]
@roldancer  it failed to untar the docker layer 23d3085bc2780b78b4fb2a816f1cd81d53ef3c4d60de5481a20ca9445b3265a5. 

Can you please manually download the layer blob and untar it by the follow command?
Assume the tag for the prueba/shellinabox is "xxxxxxxx"

Please change xxxxxxxx to the correct tag when you issue the command
1 $> curl -i -k -u harboruser:harborpassword https://yourharborip/service/token?account=harboruser\&service=harbor-registry\&scope=repository:prueba/shellinabox/xxxxxxxx:pull,push

you will get a token.

replace the toke get from step 1 in the follow command.
2> curl -k -v -H "Content-Type: application/json" -H "Authorization:  Bearer $token“ -X GET https://youharborip/v2/prueba/shellinabox/blobs/sha256:6
6afbec41e5301d8163eaf9541735670ab4b49b9a4a9f4c2ab386326084c5aa0  > layer.tar

3> try to untar the layer.tar

By the way if it is possible can you please share the image and we can take further check.

**Comment by reasonerjt** [comment]
1)Please provide the log of scan job, you can get it from UI.
2)If this image is pushed by some very old version of docker (<= 1.9) it will not be supported because the whole scan feature of Harbor is based on V2 manifest.

**Comment by roldancer** [comment]
Hi, I was using an old docker image, in my last test I have used a docker image 1.12.X, but I still get the same error message:


curl -v -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5ENEY6VjdGVjpXSzZPOlc1SFc6VzJOUzozNEZMOkNWNUk6QlVONTpXWE81Ok1OUlM6SFFESTo2VUI3In0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1MDI0ODM1NDgsIm5iZiI6MTUwMjQ4MTc0OCwiaWF0IjoxNTAyNDgxNzQ4LCJqdGkiOiIyemJmSE1OendWR1Nia0tEIiwiYWNjZXNzIjpbeyJ0eXBlIjoicmVwb3NpdG9yeSIsIm5hbWUiOiJwcnVlYmEvaGFyYm9yLWxvZyIsImFjdGlvbnMiOlsicHVzaCIsIioiLCJwdWxsIl19XX0.osKQ14wq2y4CflPodIG3btCy-8fp83yDZQXJPPytWLQTWgliACG56K5ik574FxrnNFXAyzwQSo7t4FtIJbs82pB--d6qTRD-reUgrIzVXfLRsPrDaJg1rnIbHyEXk5YaO8GNc_5uioEWojFca-ISSsj2M9QsgoISxZJ8bnJzzbhO0Ymv6I8sil3W7q83evRsLHzDMJgOO7Q9PvKKhbnZ_iDDru6R63IebcOswtSiS11Y67Vmmw-1iDdGYENm0Q0DSd1ChWhBv3HO6lb2H6X3Ak6j7pRWHXKTnpsOchR2Gj1YhOwjzP-ZRHcBTVn8hvjc3b7nfxCxiXlvENQuBUiObu7ceVNXSTRDhu9brW10SrIxAiVP10wwdhaT2sfGNhprqHjhedDBFzrme4LXe6QSq0HS10V-fck6DMGTkIraWRQAcUjS_aN2bmNMIJf38fj0CqC2axkulrjD9k7yS_IEJkMz0-AiWvz-wLOa6L3Pn48llPD0dBcHUQVBb5hc7lgtxZgRa5-ZQYfg2K9M7ovhxkZr2gjZ3dIiB6RKvTGPA1yRGFXuWc9F4ZYYnl8limGD7KrPy-FVxBeOomygsjdggNB4ULbI9xN7yPO4wS4MzKnBcbxOez0epP4DOzfr8VpkFjLfYW4ScNsupUqIe95pateEr_dF60OmwTIUDe5vIcg“ -X GET "http://registry:5000/v2/prueba/harbor-log/blobs/sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67"


* Connected to registry (172.26.0.2) port 5000 (#0)
> GET /v2/prueba/harbor-log/blobs/sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67 HTTP/1.1
> Host: registry:5000
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5ENEY6VjdGVjpXSzZPOlc1SFc6VzJOUzozNEZMOkNWNUk6QlVONTpXWE81Ok1OUlM6SFFESTo2VUI3In0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1MDI0ODM1NDgsIm5iZiI6MTUwMjQ4MTc0OCwiaWF0IjoxNTAyNDgxNzQ4LCJqdGkiOiIyemJmSE1OendWR1Nia0tEIiwiYWNjZXNzIjpbeyJ0eXBlIjoicmVwb3NpdG9yeSIsIm5hbWUiOiJwcnVlYmEvaGFyYm9yLWxvZyIsImFjdGlvbnMiOlsicHVzaCIsIioiLCJwdWxsIl19XX0.osKQ14wq2y4CflPodIG3btCy-8fp83yDZQXJPPytWLQTWgliACG56K5ik574FxrnNFXAyzwQSo7t4FtIJbs82pB--d6qTRD-reUgrIzVXfLRsPrDaJg1rnIbHyEXk5YaO8GNc_5uioEWojFca-ISSsj2M9QsgoISxZJ8bnJzzbhO0Ymv6I8sil3W7q83evRsLHzDMJgOO7Q9PvKKhbnZ_iDDru6R63IebcOswtSiS11Y67Vmmw-1iDdGYENm0Q0DSd1ChWhBv3HO6lb2H6X3Ak6j7pRWHXKTnpsOchR2Gj1YhOwjzP-ZRHcBTVn8hvjc3b7nfxCxiXlvENQuBUiObu7ceVNXSTRDhu9brW10SrIxAiVP10wwdhaT2sfGNhprqHjhedDBFzrme4LXe6QSq0HS10V-fck6DMGTkIraWRQAcUjS_aN2bmNMIJf38fj0CqC2axkulrjD9k7yS_IEJkMz0-AiWvz-wLOa6L3Pn48llPD0dBcHUQVBb5hc7lgtxZgRa5-ZQYfg2K9M7ovhxkZr2gjZ3dIiB6RKvTGPA1yRGFXuWc9F4ZYYnl8limGD7KrPy-FVxBeOomygsjdggNB4ULbI9xN7yPO4wS4MzKnBcbxOez0epP4DOzfr8VpkFjLfYW4ScNsupUqIe95pateEr_dF60OmwTIUDe5vIcg
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: max-age=31536000
< Content-Length: 3628
< Content-Type: application/octet-stream
< Docker-Content-Digest: sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67"
< Date: Fri, 11 Aug 2017 20:09:30 GMT
< 
{"architecture":"amd64","config":{"Hostname":"e1f0cb806a1b","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"514/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","crond \u0026\u0026 rm -f /var/run/rsyslogd.pid \u0026\u0026 rsyslogd -n"],"ArgsEscaped":true,"Image":"sha256:61ee4dd5285bb972b4cac1ce8785cdc82201b5488e24298fbb2ff22a11e1a1c6","Volumes":{"/var/log/docker/":{}},"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{}},"container":"276a61acf5daf84143d38a5af119bb07cde6b546e5bdf519630e249ec1d3396c","container_config":{"Hostname":"e1f0cb806a1b","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"514/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ","CMD [\"/bin/sh\" \"-c\" \"crond \u0026\u0026 rm -f /var/run/rsyslogd.pid \u0026\u0026 rsyslogd -n\"]"],"ArgsEscaped":true,"Image":"sha256:61ee4dd5285bb972b4cac1ce8785cdc82201b5488e24298fbb2ff22a11e1a1c6","Volumes":{"/var/log/docker/":{}},"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{}},"created":"2017-08-10T09:58:52.832899786Z","docker_version":"1.12.1","history":[{"created":"2016-06-08T16:42:57.639291921Z","author":"Fabio Rapposelli \u003cfabio@vmware.com\u003e","created_by":"/bin/sh -c #(nop) MAINTAINER Fabio Rapposelli \u003cfabio@vmware.com\u003e","empty_layer":true},{"created":"2016-06-27T16:55:48.989019489Z","author":"Fabio Rapposelli \u003cfabio@vmware.com\u003e","created_by":"/bin/sh -c #(nop) ADD file:268c8f4f739643c12366829954a5287f5ad4ef868c87d5aa77485accf1d8c214 in /"},{"created":"2016-06-27T16:55:51.498156946Z","author":"Fabio Rapposelli \u003cfabio@vmware.com\u003e","created_by":"/bin/sh -c #(nop) CMD [\"/bin/bash\"]","empty_layer":true},{"created":"2017-06-30T15:44:11.352892155Z","created_by":"/bin/sh -c tdnf install -y cronie rsyslog shadow tar gzip \t\u0026\u0026 mkdir /etc/rsyslog.d/     \u0026\u0026 mkdir /var/spool/rsyslog     \u0026\u0026 groupadd syslog     \u0026\u0026 useradd -g syslog syslog"},{"created":"2017-08-10T09:58:51.521652262Z","created_by":"/bin/sh -c #(nop) ADD file:1d9d2bfd4c35bd4dc591f5b9be5d8831e5cb35f610b0c3bb10388b90edf54fb8 in /etc/rsyslog.conf "},{"created":"2017-08-10T09:58:51.729720458Z","created_by":"/bin/sh -c #(nop) ADD file:0c1347129a0d7c5f94a3aa7473c7c63b30d8649458d40820cead8532395a036c in /etc/cron.weekly/rotate "},{"created":"2017-08-10T09:58:51.987577558Z","created_by":"/bin/sh -c #(nop) ADD file:988d05d6d33cc123c5433cb2e22a696986cb9f4c3277620c293ea8b4fa6ad058 in /etc/rsyslog.d/ "},{"created":"2017-08-10T09:58:52.618518647Z","created_by":"/bin/sh -c #(nop)  VOLUME [/var/log/docker/]","empty_layer":true},{"created":"2017-08-10T09:58:52.71670616Z","created_by":"/bin/sh -c #(nop)  EXPOSE 514/tcp","empty_layer":true},{"created":"2017-08-10T09:58:52.832899786Z","created_by":"/bin/sh -* Connection #0 to host registry left intact
c #(nop)  CMD [\"/bin/sh\" \"-c\" \"crond \u0026\u0026 rm -f /var/run/rsyslogd.pid \u0026\u0026 rsyslogd -n\"]","empty_layer":true}],"os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:dd60b611baaa9504bc1705eb1928b65b6b1e3f2e0af6c9d0f844b7c1a3900d72","sha256:9463fb85297094c729e4b3ef5e7804f8db09e0dcba10f2f55748a165cbcc9ad1","sha256:d42f2f440ecf1ed0c17f8401a9fe8d5b0406c1990723ea10286238533ea0e750","sha256:fa9f841efa45be9e421192fd474d3d337d42078578bafb462966f630472d97b9","sha256:f97fd69092c0b422ed26a10387a5ad4cc00312f4d58e793f3a6e58b467876207"]}}root <T 'http://registry:5000/v2/prueba/harbor-log/blobs/sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67'                         



docker inspect vmware/harbor-log:v1.2.0-rc1
[
    {
        "Id": "sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67",
        "RepoTags": [
            "hola.com/prueba/harbor-log:v1.2.0-rc1",
            "vmware/harbor-log:v1.2.0-rc1"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "",
        "Created": "2017-08-10T09:58:52.832899786Z",
        "Container": "276a61acf5daf84143d38a5af119bb07cde6b546e5bdf519630e249ec1d3396c",
        "ContainerConfig": {
            "Hostname": "e1f0cb806a1b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "514/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/sh\" \"-c\" \"crond \u0026\u0026 rm -f /var/run/rsyslogd.pid \u0026\u0026 rsyslogd -n\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:61ee4dd5285bb972b4cac1ce8785cdc82201b5488e24298fbb2ff22a11e1a1c6",
            "Volumes": {
                "/var/log/docker/": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.1",
        "Author": "",
        "Config": {
            "Hostname": "e1f0cb806a1b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "514/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "crond \u0026\u0026 rm -f /var/run/rsyslogd.pid \u0026\u0026 rsyslogd -n"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:61ee4dd5285bb972b4cac1ce8785cdc82201b5488e24298fbb2ff22a11e1a1c6",
            "Volumes": {
                "/var/log/docker/": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 199884905,
        "VirtualSize": 199884905,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        }
    }
]

**Comment by roldancer** [comment]
logs
[logs.zip](https://github.com/vmware/harbor/files/1219009/logs.zip)

**Comment by reasonerjt** [comment]
@roldancer which image are you using in your second test?  There are some docker images cannot be handled by Clair.
As for a scan error, you should see a link on UI to show the log of the particular "scan job"

<img width="1084" alt="screen shot 2017-08-14 at 3 20 40 pm" src="https://user-images.githubusercontent.com/2390463/29262136-b256a168-8105-11e7-9378-f43a5d4dbdc8.png">

**Comment by roldancer** [comment]
Hi @reasonerjt I'm trying to test this image "vmware/harbor-log:v1.2.0-rc1". I have create a tag for my Harbor environment hola.com/prueba/harbor-log:v1.2.0-rc1

Thanks.

**Comment by reasonerjt** [comment]
Yep, the image "vmware/harbor-log:v1.2.0-rc1" is based on photonOS and can't be handled by Clair, it's a known limitation, however it should fail with a different error, we'll try to reproduce in our own env and keep you updated.
Thanks @roldancer

**Comment by roldancer** [comment]
@reasonerjt oki thanks, I will try it with another docker image.

**Comment by reasonerjt** [comment]
@roldancer I tried the vmware/harbor-log:v1.2.0-rc1 on my env it failed expectedly on a different error: "worker: OS and/or package manager are not supported"

Another question, do you keep seeing same error on same image?  If the answer is yes, please let us know the image, would be better if you could push the image to docker hub so we can pull and verify.

**Comment by roldancer** [comment]
Hi @reasonerjt I get the same error if I use the dockerhub centos:latest image.

2017-08-15T17:39:18Z [INFO] Entered scan initializer
2017-08-15T17:39:18Z [INFO] Image: myimages/centos:latest, digest: sha256:2402eae3e932cdb953ab0905aad34d46bb44d95a1a9e5735fedc2aa3ce905614
2017-08-15T17:39:18Z [INFO] Entered scan layer handler, current: 0, layer name: 14bfb3767eb6dd33468ec148f37432437b57d036123089520a4011892b1df70e, layer path: http://registry:5000/v2/myimages/centos/blobs/sha256:328edcd84f1bbf868bc88e4ae37afe421ef19be71890f59b4b2d8ba48414b84d
2017-08-15T17:39:18Z [ERROR] [handlers.go:110]: Unexpected error: Unexpected status code: 422, text: {"Error":{"Message":"tarutil: could not extract the archive"}}


docker inspect hola.com/myimages/centos:latest

...
...
       "DockerVersion": "17.03.2-ce",
...
...


Harbor is running on this version of Docker:

docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

**Comment by reasonerjt** [comment]
@roldancer 
I just verified centos:latest can be scanned on my env without any problem.

I checked the logs in logs.zip again, see these lines in clair.log:
```
Aug 11 20:35:53 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"could not unmarshal Debian's JSON","Level":"error","Location":"debian.go:109","Time":"2017-08-11 18:35:53.015020","error":"read tcp 172.26.0.5:43610-\u003e128.31.0.67:443: read: connection reset by peer"}
Aug 11 20:35:53 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2017-08-11 18:35:53.015267","error":"updater/fetchers: could not parse","updater name":"debian"}
Aug 11 21:55:10 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2017-08-11 19:55:10.674825","error":"tarutil: could not extract the archive","layer":"b419fd87d5c70e4f93d57524144a1efb5080bde1d7be3b848f42024e6bddcf87","path":"http://registry:5000/v2/prueba/harbor-log/blobs/sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67"}
Aug 11 21:55:10 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-08-11 19:55:10.676774","elapsed time":165186676,"method":"POST","remote addr":"172.26.0.6:41186","request uri":"/v1/layers","status":"422"}
Aug 11 22:15:14 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2017-08-11 20:15:14.655405","error":"tarutil: could not extract the archive","layer":"b419fd87d5c70e4f93d57524144a1efb5080bde1d7be3b848f42024e6bddcf87","path":"http://registry:5000/v2/prueba/harbor-log/blobs/sha256:bdc5f7b9d0a68861415917e8b79a7c8df24b220077f1438c2dc1de4bca454f67"}
```

Note that there's a `connection reset` error before the `failed to extract` error.

Another question, do you see this error while scanning **every**  image?  Or does this error happen intermittently?

**Comment by roldancer** [comment]
Hi @reasonerjt this error "128.31.0.67:443: read: connection reset by peer" happen because my pc was not connected to internet, I think clair try to download files from this address 128.31.0.67:443

Bye.

**Comment by reasonerjt** [comment]
@roldancer 
I see, so did you trigger the scan after Cliar initialized the Vuln DB from internet?  Based on #3040 I guess the Vuln DB has been initialized.

Did you install the RC build and have it running in an env with internet connection and later the internet connection was gone?
And how about my second question?  Does the error happen to every image?

In that part Clair will pull from the :5000 port of registry and try to extract files via the data stream from the response, and the log from clair provide very limited information about the detail of the error, so without making change to Clair's code to print more log, I can only guess.

I also noticed you are playing it on the notebook with docker 1.10, when you have time could you try to deploy the Harbor RC build on an env with higher version of docker?

**Comment by roldancer** [comment]
Hi @reasonerjt About your questions

Does the error happen to every image? 
>>> YES always the same error message.

 could you try to deploy the Harbor RC build on an env with higher version of docker?
>>> I'm going to try.

**Comment by roldancer** [comment]
Hi @reasonerjt , NOW IS WORKING, I did the following three things:

1 - Update docker to the latest available version for ubuntu

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

2 - Delete all /data directory.

3 - ./install.sh --with-clair

Thanks for your help

**Comment by reasonerjt** [comment]
Thanks @roldancer for the update, we'll investigate the root cause before closing, but good to know that this is not a bug in our code

**Comment by ywk253100** [comment]
I deployed Harbor with docker 1.10.3 and docker-compose 1.7.0 and scaned the centos:latest image, everything worked well and did not reproduce the issue.

**Comment by hickeng** [comment]
Same issue with rhel:6.9 image and other images based on it:
```
2017-09-14T08:17:09Z [INFO] Entered scan initializer
2017-09-14T08:17:09Z [INFO] Image: ittmx301/rhel6.9:88, digest: sha256:6c25dc7778ed63ba6585dbf1ee2d561a2e3cdec018f5ba4e228179806edda530
2017-09-14T08:17:09Z [INFO] Entered scan layer handler, current: 0, layer name: a5b8b323b889571e635ccda72f9c7498d349c80f2d66c3a62430a4c263adc96b, layer path: http://registry:5000/v2/ittmx301/rhel6.9/blobs/sha256:6d959342767fc90f6e2551bd33a9936d934239a1cef257c8f64805e47bfca943
2017-09-14T08:17:09Z [ERROR] [handlers.go:110]: Unexpected error: Unexpected status code: 422, text: {"Error":{"Message":"tarutil: could not extract the archive"}}
```

Of note is that this deployment is also not connected to the internet, which is an item of commonality with https://github.com/vmware/harbor/issues/3031#issuecomment-323002970

**Comment by wutongjie23hao** [comment]
@ywk253100 @reasonerjt it's not the issue of version.
