### ISSUE TITLE
Harbor 1.2.0.RC1  Administration - Configuration - Vulnerability : RHEL is not available

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#3040]
Hi, RHEL is not available in Harbor's console in Administration-Configuration-Vulnerability, any idea why?

![selection_312](https://user-images.githubusercontent.com/5012200/29242827-2b50aa46-7f94-11e7-9b6f-4fe2148bacc0.jpg)

The last clair logs about RHEL it seems that RHEL is availably.

Aug 11 20:32:47 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2017-08-11 18:32:47.820536","package":"RHEL"}
Aug 11 20:32:49 -HP-ProBook-430-G1 docker/clair[3540]: {"Event":"finished fetching","Level":"info","Location":"updater.go:227","Time":"2017-08-11 18:32:49.187112","updater name":"rhel"}

Any idea?

**Comment by reasonerjt** [comment]
Hi, this is expected behavior as centos and rhel share the same "namespace" in Clair. 

This issue make me think we should probably hide the details @steven-zou

**Comment by roldancer** [comment]
Hi @reasonerjt, which detail do you want to hide? 

If rhel and centos share the same namespace I think the label should be "centos/RHEL" in the administration console.

Thanks.

**Comment by reasonerjt** [comment]
@roldancer  We're thinking the hide the detailed list under DB timestamp,  I don't think it's appropriate the update the namespace because it's from Clair's API/notification.

**Comment by roldancer** [comment]
Hi @reasonerjt  From the end user perspective I think it is very useful two have things:

1 - The timestamp when clair vulnerability db was updated.
2 - The list of linux distros that are supported for image scanning.

Thanks.

**Comment by reasonerjt** [comment]
@roldancer thanks, but for 2), by showing the data from Clair, it's proved to be confusing, that's why this issue is opened.

**Comment by roldancer** [comment]
Hi @reasonerjt, I agree with you about this ticket, but to hide info something could be even more confuse. I think it could be more useful to change the label "centos" by "centos/RHEL" instead of removing the linux distros detail.

**Comment by steven-zou** [comment]
@reasonerjt 
  Have we already reached agreement about how to improve the namespace info?

**Comment by reasonerjt** [comment]
@steven-zou let me do some investigation next wk.

**Comment by reasonerjt** [comment]
This is no longer valid as we've decided not to show the namespace of the timestamps.
