### ISSUE TITLE
Unclear documentation 

### ISSUE THREAD

**Issue by etsangsplk** [goharbor/harbor#3066]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

Documentation of what Habor is very vague. It only lists a bullet point set of features but 
not clear if harbor can be integrated with AWS ECR other registry, where a lot of enterprises already may have put their images into, and if any of their current system like AD/LDAP can be used to talk to Habor.

**Comment by clouderati** [comment]
Hi @etsangsplk – thanks for reaching out. What sort of integration between Harbor and ECR are you interested in?

There a few other open issues re: integration with vanilla Docker registry and potentially proxying images from "upstream" repos. Would love to better understand your use case(s).

Also, a PR to clarify our docs would be super helpful, too!
