### ISSUE TITLE
harbor jobservice daemon panic when start replication task with one image at one time on two harbor nodes for each

### ISSUE THREAD

**Issue by skilledno1** [goharbor/harbor#3075]
[harbor.tar.gz](https://github.com/vmware/harbor/files/1231167/harbor.tar.gz)

1)Version of docker engine and docker-compose.

[root@cent7-1 harbor]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Fri Apr 14 13:46:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Fri Apr 14 13:46:13 2017
 OS/Arch:         linux/amd64

[root@cent7-1 harbor]# docker-compose version
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
[root@cent7-1 harbor]# 

harbor版本： 1.1.1

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same 

use default config except the parameter hostname，

3)Log files, you can get them by package the /var/log/harbor/ .

see the attached file, there is a panic in jobservice.log，the jobservice docker instance become restarting 
[harbor.tar.gz](https://github.com/vmware/harbor/files/1231165/harbor.tar.gz)

Aug 17 14:49:45 172.17.0.1 jobservice[16981]: goroutine 25 [running]:
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: panic(0x9c6d60, 0xc42000c060)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/replication.(*Checker).enter(0xc420022b58, 0xf2bca0, 0x414f50, 0xc420043a50, 0x590bd032)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/replication/transfer.go:195 +0x19d
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/replication.(*Checker).Enter(0xc420022b58, 0xc4203a86f0, 0xa57f84, 0x5, 0xc42034eab8)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/replication/transfer.go:179 +0x2f
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/job.(*SM).EnterState(0xc420338070, 0xa57f84, 0x5, 0x2, 0x2, 0x0, 0x0)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/job/statemachine.go:80 +0x321
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/job.(*SM).Start(0xc420338070, 0xa5aa5d, 0x7)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/job/statemachine.go:117 +0x23a
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/job.(*Worker).handleRepJob(0xc420315ae0, 0x9)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/job/workerpool.go:96 +0x206
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: github.com/vmware/harbor/src/jobservice/job.(*Worker).Start.func1(0xc420315ae0)
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/job/workerpool.go:63 +0x204
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: created by github.com/vmware/harbor/src/jobservice/job.(*Worker).Start
Aug 17 14:49:45 172.17.0.1 jobservice[16981]: #011/go/src/github.com/vmware/harbor/src/jobservice/job/workerpool.go:71 +0x3f

**Comment by reasonerjt** [comment]
@skilledno1 This should have been fixed in 1.2-rc1, at least the panic won't restart could you retry?

**Comment by skilledno1** [comment]
@reasonerjt  thanks for your quick reply , can this bug to be fixed to 1.1.2 version as updated harbor is not easy on our environment?

**Comment by reasonerjt** [comment]
Sorry for the late response.

But we won't make any update to 1.1.x

Closing.
