### ISSUE TITLE
Duplicate access logs are recorded when pulling image with VIC

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#3104]
As described in https://github.com/vmware/vic/issues/5950, VIC pulls image manifest twice for every image, this causes two records in the access log.

**Comment by reasonerjt** [comment]
We don't have good solution for this issue with reasonable effort, until VIC behaves same way as vanilla docker.

**Comment by stuclem** [comment]
Added as a Known Issue in https://github.com/vmware/harbor/releases/tag/v1.2.0#knownissues

**Comment by reasonerjt** [comment]
The work for VIC Engine is tracked by https://github.com/vmware/vic/issues/5963
