### ISSUE TITLE
Running Harbor with HTTP behind a HTTPS Reverse Proxy (nginx)

### ISSUE THREAD

**Issue by Flipez** [goharbor/harbor#3114]
I've tried to get harbor running behind (another) nginx reverse proxy.

So the first setup looked like this:

nginx (host,ssl) -> harbor-nginx(non-ssl) -> harbor

If I setup the first nginx with ssl redirect it basically works but the docker client send the first try in plain which I do not want.

I tried different settings but none of them works because something inside harbor seems to redirect the requests to port 80. So if I stop exposing port 80 on the host the login fails with a connection refused even if I submit `domain:443` or `https://domain`.

Are there any guidelines for this scenario?

The simple reason is that I do not want to maintain neither the SSL settings nor the cert within the container. This is globally handled by ansible.

Please let me know if any config of the current or previous setup would be useful.

```
# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by Flipez** [comment]
I also mentioned this in https://github.com/moby/moby/issues/34621 because I think this affects the `docker login` as well.

**Comment by totojack** [comment]
+1

**Comment by mdgreenwald** [comment]
+1

**Comment by jsumners** [comment]
This is just the issue I was looking for prior to installing for the first time. In my organization we use HAProxy for SSL termination. I currently have `docker-distribution` running while I research VMWare's solution. With `docker-distribution` this sort of configuration can be tricky (https://github.com/docker/distribution/issues/2225), so I expected to find such an issue for Harbor.

This is a configuration that needs to be supported.

**Comment by spark8103** [comment]
Jan  4 17:26:35 172.19.0.1 registry[22654]: time="2018-01-04T09:26:35.950809267Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:9ec141d7a6d669ded82f1d0977abf28eb71ae48f767babaa4651dcb9474dcb4f err.message="blob unknown to registry" go.version=go1.7.3 http.request.host=reg.sparkknow.com http.request.id=4761d537-1500-4009-9ddb-96ca993422cf http.request.method=HEAD http.request.remoteaddr=172.31.128.101 http.request.uri="/v2/library/alpine/blobs/sha256:9ec141d7a6d669ded82f1d0977abf28eb71ae48f767babaa4651dcb9474dcb4f" http.request.useragent="docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/3.10.0-693.11.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.729592ms http.response.status=404 http.response.written=157 instance.id=6a311010-3363-437c-b3e4-8c88eb62dfdf service=registry vars.digest="sha256:9ec141d7a6d669ded82f1d0977abf28eb71ae48f767babaa4651dcb9474dcb4f" vars.name="library/alpine" version=v2.6.2

I have error too.

**Comment by ROleP** [comment]
Probably it can be used as https behind https proxy.

Somehow I got it running with following:
traefik (https, letsencrypt) <-> harbor (nginx, https, self-signed certs) <-> harbor

Actually, thought it will be complete ssl-passthrough to harbor-nginx, but the result is more convenient, as users see letsencrypt cert.
Traefik auto-generates letsencrypt cert (for a bundle of names), InsecureSkipVerify = true to disable cert check for backends. Also have traefik.frontend.passTLSCert=true (because of it thought it will pass-through) and traefik.protocol=https.

Certs are self-signed by local CA. In harbor.cfg selected https, path to cert.key and bundle-cert.pem.
Also using them for token service (off-topic: how to actually use/generate tokens for docker login?).

**Comment by wangycc** [comment]
+1

**Comment by ensean** [comment]
An extra section for using external nginx would be great.

**Comment by ensean** [comment]
@lxkaka  here goes my nginx1 conf
```

upstream harbor {
  server harbor_proxy_ip:8080;
}

server {
    listen 443 ssl;
    server_name harbor.mycomp.com;

    ssl_certificate      /etc/nginx/conf.d/mycomp.com.crt;
    ssl_certificate_key  /etc/nginx/conf.d/mycomp.com.key;

    client_max_body_size 0;
    chunked_transfer_encoding on;

    location / {
        proxy_pass http://harbor/;
        proxy_set_header  Host              $http_host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;
    }
}
```

**Comment by k7** [comment]
After a struggle, I have fixed it. 

I have the service like this:

```
nginx (host,ssl) -> harbor-nginx(non-ssl) -> harbor
```

First, I emulate login via curl, it was good.

```bash
curl -u admin:passwd123 "https://my.registry.company.com/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry"

{
  "token": "xxxxxx",
  "expires_in": 1800,
  "issued_at": "2018-09-27T03:42:27Z"
}
```
it means there was other things error.

Via tcpdump, I found `docker login` will make a http request `https://my.registry.company.com/v2/` first.
```bash
curl -X GET -I "https://my.registry.company.com/v2/"

HTTP/1.1 401 Unauthorized
Server: nginx/1.12.2
Date: Thu, 27 Sep 2018 07:20:58 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: beegosessionID=75df8e3e78eacf5848a83877908ca96; Path=/; HttpOnly
Www-Authenticate: Bearer realm="http://my.registry.company.com/v2//service/token",service="harbor-registry"
```
now, I found the problem. `realm="http://my.registry.company.com/v2//service/token"`. it was `http`, not `https`.

so I edit common/config/registry/config.yml，and fixed it.

```yaml
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://my.registry.company.com/service/token
    rootcertbundle: /some/root.crt
    service: harbor-registry
```

Great, It works.

**Comment by rruu** [comment]
and you can changes prepare script with and reinstall
-  public_url = protocol + "://" + hostname
+ public_url = "https" + "://" + hostname

**Comment by shinebayar-g** [comment]
Hey @k7 Thank you very much for the explanation. Without changing that particular config, I was getting 
```
Error response from daemon: Get https://goharbor.mydomain.com/v2/: unauthorized: authentication required
``` error when trying to login. After changing that it works! However if I run install.sh script it overrides that changed settings. So I just restarted all docker process instead of re-install.

**Comment by jakirpatel** [comment]
I faced a similar issue while running Harbor with HTTP behind an HTTPS Reverse Proxy. 
I did the following changes: 
**In harbor,cfg:** 
1. Make sure the **hostname** points to the VIP. (In my case its reverse proxy https load balancer nginx) 
2. ` customize_crt = off `( As external source that means https nginx will do this) 
------------------------------------------------------------------------------------------------------------------------------------------
3. In config of nginx common
`    /common/templates/nginx/nginx.http.conf`
Comment this line: `proxy_set_header X-Forwarded-Proto $$scheme;`
Make sure to comment it `/ , /v2/ and /service/ `
4. Prepare your harbor with ./prepare. 
After preparation in `common/config/registryconfig.yml` make realm https. 

```
auth:
  token:
    issuer: harbor-token-issuer
    realm: **https**://vip-address/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
```

This solved my problem.

**Comment by CrystalMethod** [comment]
I can confirm that Harbor works behind an HTTPS reverse proxy (Synology NAS/Nginx) with SSL termination. In addition there is Traefik as another proxy in between - however, this only has the task of routing to different Docker based services. All communication uses port 80 of Harbor Proxy.

**Comment by nicholasamorim** [comment]
I can confirm it runs with the modifications that are shown in here _but_ `docker login` always returns me `400 Bad Request`. Everything else works fine and emulating login via curl works fine too.

The funny thing is that if I enter the incorrect login/password, the behaviour works as expected, telling me I'm unauthorized.

**Comment by mxplusb** [comment]
I had the same problem here as most folks, I wanted to run Harbor behind a reverse proxy (I'm using Nginx), but I also wanted Clair, Chart Museum, and Notary, which means HTTPS all the way. Here is what I did, thanks to @jakirpatel for the initial work.

1. If Harbor with Notary, Clair, and Chart Museum is running, run `docker-compose -f ./docker-compose.yml -f ./docker-compose.notary.yml -f ./docker-compose.clair.yml -f ./docker-compose.chartmuseum.yml down -v`
1. Generate your self-signed HTTPS certificates from the Harbor instructions.
1. In `harbor.cfg`, set your hostname to the external VIP, so `vip.domain.com`.
1. In `harbor.cfg`, set `customize_cert = on`
1. In the nginx HTTPS config, `/common/templates/nginx/nginx.https.conf`, comment out all instances of `proxy_set_header X-Forwarded-Proto $$scheme;`
1. Run `./prepare --with-notary --with-clair --with-chartmuseum`
1. Start everything back up with `docker-compose -f ./docker-compose.yml -f ./docker-compose.notary.yml -f ./docker-compose.clair.yml -f ./docker-compose.chartmuseum.yml up -d`
1. On your reverse proxy server (I'm using Nginx as an example since that's what I use), create the `harbor.conf` file.
1. Populate it with this:
```
# this block is to redirect 80 to 443, i.e. HTTP to HTTPS
server {
        listen 80;
        server_name vip.domain.com;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443;
        server_name     vip.domain.com;
        add_header      Strict-Transport-Security "max-age=31536000" always;
        # your certs, I'm using let's encrypt domain wildcards.
        ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
        ssl_stapling on;
        ssl_stapling_verify on;

        location / {
                client_max_body_size 2000m;
                proxy_buffering off;
                proxy_ssl_verify off;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass https://harbor.internal.domain.com;
    }
}
```
10. Profit.

**Comment by DiegoSouzaPW** [comment]
> Edit: I'm still working through the Notary configs. I've never used Notary before so I only partially understand it. If I get it working, I'll update here.

No News for Notary?, i try without success too

**Comment by soosap** [comment]
@k7 pointed me into the right direction. I was experiencing 401 Unauthorized for `docker login myco.registry.com -u admin`. I solved this by setting the value of `auth.token.issuer` to `issuer: harbor-token-issuer` inside the registry config. Somehow I believed I could choose a random value there. 🤯

**Comment by slzzz** [comment]
> +1
> traefik (https, letsencrypt) <-> harbor (nginx, https, self-signed certs) <-> harbor
> 
> traefik(443) <-> harbor(nginx,443,self-signed certs),insecureSkipVerify = true
> 
> harbor self-signed:
> https://github.com/vmware/harbor/blob/master/docs/configure_https.md
404

**Comment by thechubbypanda** [comment]
Everything in here is kinda out of date, I'm getting the following error in core: `register db Ping `default`, missing "=" after "1" in connection info string"`.

I'm using caddy-reverse-proxy and harbor v2.4.0. Anyone seen this before?

I'm trying to achieve ```caddy (host,ssl) -> harbor-nginx(non-ssl) -> harbor```

**Comment by Rizary** [comment]
> Everything in here is kinda out of date, I'm getting the following error in core:
> 
> > register db Ping `default`, missing "=" after "1" in connection info string"
> 
> I'm using caddy-reverse-proxy and harbor v2.4.0. Anyone seen this before?
> 
> I'm trying to achieve
> 
> ```
> caddy (host,ssl) -> harbor-nginx(non-ssl) -> harbor
> ```

Just find this issue and your comment. Have you achieved the caddy -> harbor thing?

**Comment by thechubbypanda** [comment]
@Rizary gave up on harbor long ago

**Comment by Stinosko** [comment]
For anyone that is still facing issues I managed to get it to work with Traefik, I found a good guide that works for me (so far):
[https://medium.com/@joelkoussawo/installing-harbor-container-registry-behind-traefik-reverse-proxy-with-lets-encrypt-certificate-8ab1733daa1](https://medium.com/@joelkoussawo/installing-harbor-container-registry-behind-traefik-reverse-proxy-with-lets-encrypt-certificate-8ab1733daa1)

Note 1 for future me: 
In the Traefik harbor.yml config don't add an entrypoint or add both `web` and `websecure`. 
From habbit I added only the websecure I could not pull images, when adding `web` it worked without an issue.

Note 1 for future me:
When performing a hard reset without preserving the present data, don't forget to delete the data_volume as configured in the harbor config file.

**Comment by umfaccess** [comment]
Here's what I managed to do : `LoadBalancer with SSL termination (ssl) -> NGINX Ingress (non-ssl) -> Harbor (non-ssl)`

For me with Harbor deployed using Helm via Terraform, the right combination was a ConfigMap with `"X-Forwarded-Proto" = "http"` assigned to my Ingress using the annotation `"nginx.ingress.kubernetes.io/proxy-set-headers" = "harbor/harbor-nginx-headers"`. This allowed me to achieve a result close to commenting out the line :  `proxy_set_header X-Forwarded-Proto $scheme;`.

But the thing that made everything work together is really the `registry.relativeurls: true` option that fixed all my "Retrying" and "EOF" errors when pushing images.

Here is my custom Ingress config (since I expose harbor with ClusterIP) : 

```
# ConfigMap for the proxy_set_header X-Forwarded-Proto issue, I force http instead of $scheme
resource "kubernetes_config_map" "harbor_nginx_headers" {
    metadata {
        name      = "harbor-nginx-headers"
        namespace = kubernetes_namespace.harbor.metadata[0].name
    }

    data = {
        "X-Forwarded-For" = "$proxy_add_x_forwarded_for"
        "X-Forwarded-Proto" = "http"
        "X-Real-IP" = "$remote_addr"
    }
}

# ConfigMap is applied using "nginx.ingress.kubernetes.io/proxy-set-headers" = "harbor/harbor-nginx-headers" annotation
resource "kubernetes_ingress_v1" "harbor_ingress" {
	metadata {
		name      = "harbor-ingress"
		namespace = kubernetes_namespace.harbor.metadata[0].name
		annotations = {
				"kubernetes.io/ingress.class"                           = "nginx"
				"ingress.kubernetes.io/ssl-redirect"                    = "false"
				"ingress.kubernetes.io/proxy-body-size"                 = "0"
				"nginx.ingress.kubernetes.io/ssl-redirect"              = "false"
				"nginx.ingress.kubernetes.io/proxy-body-size"           = "0"
				"nginx.ingress.kubernetes.io/proxy-read-timeout"        = "900"
				"nginx.ingress.kubernetes.io/proxy-send-timeout"        = "900"
				"nginx.ingress.kubernetes.io/proxy-request-buffering"   = "off"
				"nginx.ingress.kubernetes.io/enable-real-ip"       	    = "true"
				"nginx.ingress.kubernetes.io/whitelist-source-range"    = "0.0.0.0/0"

				"nginx.ingress.kubernetes.io/proxy-set-headers"         = "harbor/harbor-nginx-headers"
		}
	}

	spec {
		ingress_class_name = "nginx"
		rule {
			host = "my.harbor.domain"
			http {
				# Docker Registry API endpoints
				path {
					path      = "/v2/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-core"
							port {
								number = 80
							}
						}
					}
				}
				path {
					path      = "/api/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-core"
							port {
								number = 80
							}
						}
					}
				}
				path {
					path      = "/service/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-core"
							port {
								number = 80
							}
						}
					}
				}
				path {
					path      = "/chartrepo/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-core"
							port {
								number = 80
							}
						}
					}
				}
				path {
					path      = "/c/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-core"
							port {
								number = 80
							}
						}
					}
				}
				# Harbor UI
				path {
					path      = "/"
					path_type = "Prefix"
					backend {
						service {
							name = "harbor-portal"
							port {
								number = 80
							}
						}
					}
				}
			}
		}
	}
}
```

And here is the most important part of my Harbor config : 
```
expose:
  type: clusterIP
  clusterIP:
    name: "harbor"
    ports:
      httpPort: 80
  tls:
    enabled: false

externalURL: "https://my.harbor.domain"

registry:
  relativeurls: true
```
