### ISSUE TITLE
[VIC] Downloading the harbor certs from UI is unavailable for Developers and Project Admins

### ISSUE THREAD

**Issue by sergiosagu** [goharbor/harbor#3117]
Currently the Certificate download link is available only for Cloud Admins, because they are the only ones seeing the Administration > Configuration section, see:

![cloudadmin](https://user-images.githubusercontent.com/2034419/29702616-b29377aa-897a-11e7-8b87-e49221937bf4.png)

But according to https://github.com/vmware/admiral/issues/159#issuecomment-323383691 the same link should be available to Developers and Project Admins, which means that most probably the link needs to be added somehow to the following component:

![developer](https://user-images.githubusercontent.com/2034419/29702615-b292896c-897a-11e7-9195-e85c52c7199b.png)

cc @steven-zou @reasonerjt @karthik-narayan @martin-borisov @andrewtchin @angel-ivanov @shadjiiski @lweitzman

**Comment by reasonerjt** [comment]
Thanks @sergiosagu but sys-admin can download ca cert is the design for previous releases.
And I believe there's some discussion ongoing between Steven and Louie from UX perspective.

**Comment by steven-zou** [comment]
Yes, I'm discussing the link placement with @lweitzman .

**Comment by reasonerjt** [comment]
@karthik-narayan downloading CA is restricted to sys admin since v1.0, I don't think we have plan to change it for 1.2.
So this is not a bug, if needed we can work on it in future.

**Comment by lweitzman** [comment]
i think that a separate button on the project repositories page seems reasonable. 
but i think it should be a separate action button just to the left of the “Push Image” action.

**Comment by karthik-narayan** [comment]
@reasonerjt Can you walk me through the workflow where a developer needs to push an image into a Harbor instance deployed as a part of vSphere Integrated Containers? Assume that they are using self-signed certs and it becomes apparent that the developer needs access to the certs. 

Now that we do have a place to download the certs, I'm okay with deferring it. That said, I expect a number of people to hit this issue.

**Comment by reasonerjt** [comment]
@karthik-narayan 
We discussed it in VIC 1.0, the sys admin will distribute the CA to different users.
I don't have preference in regards who will have permission to download it.  My concern is solely for effort and time.  
Making it a stretch goal for 1.2.  If the effort is minimal we'll make the update.

**Comment by reasonerjt** [comment]
After discussion with Matt, for meeting the GA date. defer this issue.

**Comment by stuclem** [comment]
Having just documented this, it looks really silly that we tell DevOps and Developers that they must ask the Cloud admin for the Registry CA cert. This should be made available to all roles from Developer upwards.

**Comment by lweitzman** [comment]
Updated mockup to show link to download registry root certificate on project repositories page
https://vmware.invisionapp.com/share/ZVF75AZAW#/271907735_Projects_-_Repositories_-_List_V1-4

**Comment by zhoumeina** [comment]
Please refer to : system-setting-component.html
