### ISSUE TITLE
get the error 'ConfigParser.NoOptionError' when run install.sh

### ISSUE THREAD

**Issue by hzfeng87** [goharbor/harbor#3128]
1)
docker version：1.12.6
docker-compose：1.12.0
harbor version：1.2.0-rc2
2)
I just modified these sections in harbor.cfg and the other sections are by default.

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = 172.28.217.57

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#The password for the root user of mysql db, change this before any production use.
db_password = 123456
 
3)
Error:"ConfigParser.NoOptionError: No option u'clair_db_password' in section: u'configuration'"

./install.sh 

[Step 0]: checking installation environment ...

Note: docker version: 1.12.6

Note: docker-compose version: 1.12.0

[Step 1]: loading Harbor images ...
Loaded image: vmware/harbor-adminserver:v1.2.0-rc2
Loaded image: photon:1.0
Loaded image: vmware/postgresql:9.6.4-photon
Loaded image: vmware/registry:2.6.2-photon
Loaded image: vmware/notary-photon:server-0.5.0
Loaded image: vmware/notary-photon:signer-0.5.0
Loaded image: vmware/harbor-ui:v1.2.0-rc2
Loaded image: vmware/harbor-log:v1.2.0-rc2
Loaded image: vmware/harbor-db:v1.2.0-rc2
Loaded image: vmware/harbor-jobservice:v1.2.0-rc2
Loaded image: vmware/nginx-photon:1.11.13
Loaded image: vmware/harbor-notary-db:mariadb-10.1.10
Loaded image: vmware/clair:v2.0.1-photon

[Step 2]: preparing environment ...
Traceback (most recent call last):
  File "./prepare", line 156, in <module>
    pg_password = rcp.get("configuration", "clair_db_password")
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'clair_db_password' in section: u'configuration'

**Comment by reasonerjt** [comment]
Are you using an old version of harbor.cfg?

**Comment by hzfeng87** [comment]
no,  I was copying an old harbor.cfg for 1.1rc3 here,  I hit the problem. Then I cleaned the directory and extracted the tar ball again. While I modified the configuration and rerun install.sh, the problem is the same.

**Comment by reasonerjt** [comment]
That's why I say it's old version, see:
https://github.com/vmware/harbor/blob/master/make/harbor.cfg#L35

@wy65701436 let's revise the upgrade guide to mitigate such situation..

**Comment by hzfeng87** [comment]
wow,I uncomment the parameter 'clair_db_password',it is resolved. I thought it may bring negative effects at that moment since I don't deploy with clair.
Thanks a lot!!

**Comment by wy65701436** [comment]
For the OVA, we can handle it in the upgrade script but not for standalone.

**Comment by reasonerjt** [comment]
@hzfeng87 thanks for letting us know this issue, we should improve that but we are too close to official release, so the fix will be deferred.
