### ISSUE TITLE
Harbor v1.2.0  does not support adminserver and clair in the kubernetes.

### ISSUE THREAD

**Issue by singhwang** [goharbor/harbor#3222]
I want to deploy harbor v1.2.0 in the k8s environment.

**Comment by vasartori** [comment]
@SchindlerWang I made way do deploy, is not "magic" but works. Take a look in: https://github.com/vasartori/harbor-kubernetes

**Comment by SchindlerWang** [comment]
Your project has a small problem, but most of it works.I remember there was a template that was a little bit problem,  it was an indentation problem. For those who have the basics, you can use them just by a small adjustment. Thank you very much for your help.

**Comment by SchindlerWang** [comment]
I would like to ask why the community hasn't updated the deployment capabilities of kubernetes for a long time.Will it continue to be updated？
