### ISSUE TITLE
migrate docker compose templates to V3.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#3226]
Leverage the new elements such as "healthcheck", "secret",etc.

**Comment by wdhif** [comment]
https://github.com/vmware/harbor/pull/3123

**Comment by reasonerjt** [comment]
Ah, thanks @wdhif

**Comment by mdubya66** [comment]
This has implications on the VCH. @sflxn

**Comment by reasonerjt** [comment]
Removing the target as confirmed with Pietro this is a low priority.

**Comment by reasonerjt** [comment]
-
