### ISSUE TITLE
Harbor HA feature design proposal/discussion

### ISSUE THREAD

**Issue by hainingzhang** [goharbor/harbor#327]
**High availability(HA)** is a feature required by most production system. Currently, Harbor does not support a HA deployment. We are creating this thread to track any discussion and proposal of HA. Welcome input from anyone. 

**Key requirements:**
1. Harbor's registry should have multiple instances to provide service. Failure of any individual instance doesn't interrupt the service. 
2. Image storage should have redundancy and shareable by multiple registry instances. 
3. MySQL database should have high availability.

**Help wanted:**
If you can help with testing some of the storage backend of Harbor, please let us know. Currently, we are looking various options like Ceph, NFS, MooseFS, GlusterFS, swift. If you have tried any of these or even something not on the list, feel free to share the result with us.

**Comment by kingljl** [comment]
How to do these questions.
More details, thank you.
ceph、nfs、swift..

**Comment by xiaods** [comment]
proposal way for 2. Image storage should have redundancy and shareable by multiple registry instances. 

Solution 1:  Filesystem Storage Driver + MooseFS
![moose](https://cloud.githubusercontent.com/assets/37678/15996700/8239aabe-315d-11e6-97f9-05deb3aec49b.PNG)

**Comment by xiaods** [comment]
Solution 2: Cloud option, 
* s3: A driver storing objects in an Amazon Simple Storage Solution (S3) bucket.
* azure: A driver storing objects in Microsoft Azure Blob Storage.
* oss: A driver storing objects in Aliyun OSS.
* gcs: A driver storing objects in a Google Cloud Storage bucket.

in china, OSS is current option.

**Comment by xiaods** [comment]
Solution 3: private Cloud option,
* swift: A driver storing objects in Openstack Swift.

Ceph is not mentioned in recent registry storage proposal, so swift is current option.

**Comment by xiaods** [comment]
Because the Harbor is active like as a proxy, so we can reference the proxy ha solution, such as haproxy.

reference: HAProxy/Keepalived on linux

https://www.howtoforge.com/setting-up-a-high-availability-load-balancer-with-haproxy-keepalived-on-debian-lenny

**Comment by hainingzhang** [comment]
Thanks for your input. @xiaods We can look into these options and may perform some testing before we can decide which one is better fit for the use case.

**Comment by elianka** [comment]
1. harbor didn't use the proxy(cache) solution in registry. and i think its a very useful feature.
2. harbor cluster could also be considered 
![image](https://cloud.githubusercontent.com/assets/4158830/16510222/bdf5d98e-3f76-11e6-80d5-2e7ab626b854.png)

**Comment by hainingzhang** [comment]
Did you mean mirroring of a registry? Currently, there is limitation that the registry can only mirror images on dockerhub. 

Maybe you can take a look at our new feature of replicating images between Harbor instances. It may help in your scenario. @elianka

**Comment by elianka** [comment]
Thanks for your reply. not mirror, but pull through cache. mirror has the limitation,however, pull through cache is ok for private registry(public images), and have problem on private images. 

yes, i got the message about the new feature, and i had talked with you this afternoon at kubernetes meetup i think. Thanks for your information, and glad to talk to you.

**Comment by joeyjy** [comment]
@hainingzhang Hi Zhang, does Harbor support using an out-container database to deploy for now? I want to deposit the database to our DBA department, is it possible? :)

**Comment by reasonerjt** [comment]
It is, you need to properly modify the docker-compose.yml, make sure the DB is accessible from the containers, and make sure the username/password of the DB in env files is correct.

**Comment by joeyjy** [comment]
@reasonerjt Thanks so much!

**Comment by joeyjy** [comment]
@reasonerjt Sorry to disturb you again. How can I config the docker-compose.yaml? If it means I should represent the external mysql server logically inside the mysql container as a service? here's the template in docker-compose.yaml, can you kindly show me how to do this?

mysql:
    image: harbor_mysql:0.4.1
    restart: always
    volumes:
      - /data/database:/var/lib/mysql
    env_file:
      - ./config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"

**Comment by betazep** [comment]
Has there been any movement in the HA discussion/approach?  We need HA service models. (non-kube, non-cloud)  If we deploy two instances of harbor on separate compute, how do we maintain:

1. Metadata sync (db mirror)? 
2. Image availability (cross replica/shared storage e.g. nfs)?
3. Logged-on session state?
4. Load balancing? (less important)
5. etc

Even an Active/Passive configuration would be beneficial.

**Comment by reasonerjt** [comment]
HA deployment will always be env dependent.

In short term the HA deployment will be depending on helm chart:
https://github.com/goharbor/harbor-helm
