### ISSUE TITLE
How to report when scan is reporting vulnerabilities

### ISSUE THREAD

**Issue by andrewtchin** [goharbor/harbor#3402]
@lgayatri commented on [Thu Oct 05 2017](https://github.com/vmware/vic-product/issues/909)

![image](https://user-images.githubusercontent.com/25006749/31222708-b543f340-a9e5-11e7-9bcf-5fd3db88df3c.png)
![image](https://user-images.githubusercontent.com/25006749/31223578-68414c34-a9e8-11e7-96e9-eeab10f8f12e.png)
I do not see an option to download the vulnerability scan report. How  to interpret this output?

---

@gigawhitlocks commented on [Fri Oct 13 2017](https://github.com/vmware/vic-product/issues/909#issuecomment-336571192)

Labelled this as both a bug and an enhancement due to this being sort of a bug-by-omission

**Comment by reasonerjt** [comment]
@lgayatri To interpret the output you can click the link to view detail of the tag, it has more details of the vulnerabilities.

For report download, this is not a bug but a new feature, I'll adjust the label to mark it a feature request.

**Comment by HaveFun83** [comment]
The get some kind of global report for all images will be also helpful.

**Comment by xaleeks** [comment]
@HaveFun83 There is ticket open in our backlog related global reporting of all CVEs as opposed to drilling into each project.  please track progress here: https://github.com/goharbor/harbor/issues/10496
