### ISSUE TITLE
image name template to restrict the format of image names

### ISSUE THREAD

**Issue by ligc** [goharbor/harbor#3422]
We are setting up our enterprise docker registry solution using Harbor,  one requirement is to restrict the format of the image names, for example, the following image name is considered as legal and the other formats are considered as illegal:

<R&DCenterName>_<DepartmentName>_<ApplicationName>:<Version>

beijing_system1_testapp:v0.1

Is there any way in Harbor to restrict the names of the image?  Your responses will be appreciated.

**Comment by wy65701436** [comment]
What do you mean by 'legal'? Anyone cannot push image if the name is unacceptable? Is it a Project level requirement? Or System level?

**Comment by ligc** [comment]
@wy65701436 Standardizing the images naming is part of the DevOps transformation effort we are working on.  We would like to prevent any user to upload the image which does not conform to the images naming convention, we have been struggling with the non-standardized-naming images in the repository.  Project level setup should be good enough for now.

**Comment by wy65701436** [comment]
Thanks @ligc, I will add one community requirement and keep this issue opening to track.

**Comment by wy65701436** [comment]
Thanks @ligc, this requirement is too specific so far for Harbor. It may not be put into the backlog, I suggest you to modify source code directly, and we can discuss details in this issue.
