### ISSUE TITLE
Something needs to clarify in docs/user_guide.md

### ISSUE THREAD

**Issue by moooofly** [goharbor/harbor#3462]
At [pulling-and-pushing-images-using-docker-client](https://github.com/vmware/harbor/blob/0383c3fb8b9c60eb9a3f571e385a1873d1448204/docs/user_guide.md#pulling-and-pushing-images-using-docker-client), there is something need to clarify.

> add '--insecure-registry' option to `/etc/default/docker` (ubuntu) or `/etc/sysconfig/docker` (centos) and restart Docker

These settings are fit for systems using **Upstart** and **SysVinit**, not **Systemd**, Taking ubuntu system for example, I need to edit `/lib/systemd/system/docker.service` , and add `–insecure-registry xx.xx.xx.xx`  to ExecStart under [Service].

It is nice to illustrate this detail for people who reading this doc.

**Comment by wy65701436** [comment]
That's right, the configuration is not fit for Ubuntu 16 as you mentioned. It's better to add a link that points to the docker official document.
