### ISSUE TITLE
Enhance Harbor to support quota management

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#3570]
Currently Harbor don't support quota management.
This epic will be used to summary the requirement and  define the scopes for quota related issues.

Some requirement we currently have:

Limit the number of pull/push requests a user can do per day/week/month.
Limit the amount of GB a user can pull/push per day/week/month.
Limit the image size (in GB) a user push to a registry.
Limit the number of image layers a user can use per image.
Limit the total amount of GB a user can use for all his images in a certain project/all projects.
Restrict the bandwidth for pull/push requests. Give certain users and projects (e.g. production) higher priority.

**Comment by yixingjia** [comment]
#3419 Limit activities and resource consumption
#3523 Add column / info about used storage

**Comment by tschwaller** [comment]
Nice. The Mockup looks good and simple. We just need to implement it ;-) Next step: some dashboards about total Quota consumption.

**Comment by ArjonBu** [comment]
Cool feature indeed.

**Comment by wy65701436** [comment]
Close it as Harbor has already introduced quota management.
