### ISSUE TITLE
Harbor HA solution proposals

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#3582]
We will use this Page to discuss the Harbor HA solution proposals.  
Harbor will plan to release some script to help make the HA setup easily. 

Please feel free give out comments/suggestions/questions. We will adjust the proposal according to your feedback. So your voice are valuable to Harbor. 

**Harbor HA solutions proposals**

This document will cover the follow four solutions which provide different severity of Harbor HA. each solution will have it's cons and pros. We need to  balance them and choose the one which is most fit the use scenario. 

**Solution 1: Active-Active with scale out ability**
![ha_active_active](https://user-images.githubusercontent.com/1715683/32586942-a92aa8da-c540-11e7-9af7-db03fc467451.png)
As seen in the figure, components involved in the architecture are:

**VIP:** Virtual IP. The Harbor user will access Harbor through this VIP address. This VIP will only active on one load balancer node at the same time. It will automatically switch to the other node if the active loadbalancer node is down.

**LoadBalancer01 and 02:** They together compose as a group which avoid single point failure of load balancer nodes. Keepalived is installed on both load balancer nodes. The two Keepalived instance will form a VRRP group to provide the VIP and ensure the VIP only shows on one node at the same time. The LVS component in Keepalived is responsible for router the requests between different Harbor servers according to the routing algorithm. 

**Harbor server 1..n:** These are the running Harbor instances. They are in active-active mode. User can setup multiple nodes according to their workload.

**DB cluster:** The MariaDB is used by Harbor to store user authentication information, image metadata information and so on. User should follow its best practice to make it HA protect.

**Shared Storage:** The shared storage is used for storing Docker Volumes used by Harbor. Images pushed by users are actually stored in this shared storage. The shared storage makes sure that multiple Harbor instances have consistent storage backend. Shared Storages can be Swift, NFS, S3, azure, GCS or OSS. User should follow its best practice to make it HA protect.

**Redis:** The purpose of having Redis is to store UI session data and store the registry metadata cache. When one Harbor instance fails or the load balancer routes a user request to another Harbor instance, any Harbor instance can query the Redis to retrieve session information to make sure an end-user has a continued session. User should follow the best practice of Redis to make it HA protect. 

**Limitation**
Currently it doesn’t support Clair and Notary.

**Setup**
**Prerequisites**

1. MariaDB cluster

2. Shared Storage 
3. Redis cluster 
Item 1,2,3 are considered external components to Harbor. Before configuring Harbor HA, we assume these components are present and all of them are HA protected. Otherwise, any of these components can be a single point of failure.
4.	2 VMs for Load balancer 
5.	n VMs for Harbor instances (n >=2)
6.	n+1 static IPs (1 for VIP and the other n IPs will be used by harbor servers)

**Solution 2 Classical Active-Standby solution**
![ha_active_standby](https://user-images.githubusercontent.com/1715683/32590156-d88e6568-c553-11e7-9188-07eebbe207c7.png)

This solution is ideal for situations when the workload is not very high, this is the classical two node HA solution. The different compare with solution 1 is that it doen’t need the two extra loadblancer nodes and only need 1 static IP address. This solution doesn’t support scale out.

**Keepalived: **The Keepalived will be installed both on VM1 and VM2, the two Keepalived will form a VRRP group to provide the VIP. 

**VIP:** User will access the harbor cluster by the VIP. Only the server that hold the VIP will provide the service. 

**Harbor instance1,2:** The harbor instance will share the VM1,2 with the Keepalived.

**DB Cluster:** Same as the DB cluster in solution1

**Shared storage:** Same as the shared storage in solution 1

**Redis cluster:** Same as the Redis cluster in solution 1

**Setup**

**Prerequisites**

1.	Standalone MariaDB (cluster) is needed 
2.	Shared storage for registry is needed
3.	Redis (cluster) for Harbor session and registry metadata cache is needed.
4.	2 Ubuntu16.04 VMs
5.	1 Static IP address (used as VIP)

**Solution 3**
Since the above two solution both require shared storage. For some scenario that don’t have shared storage but has some kind of HA requirement. We can use images replication.

![ha_master_slave](https://user-images.githubusercontent.com/1715683/32590229-485dd112-c554-11e7-80ca-59308f63885d.png)

Set up a harbor as the master Harbor instance. All the images will be pushed to this Harbor instance. In the meanwhile, there are a group of read-only harbors, which serve the pull request from Docker hosts.

This solution is easy to implement and can met the requirement of load-balance and scale out. 

**Solution 4:**

This is another solution that use the replication to achieve low level “HA”, same as solution 3, no need for shared storage external database cluster and Redis cluster. This solution can make the images under protection of single node failure.

![ha_master_master](https://user-images.githubusercontent.com/1715683/32590250-6f937f02-c554-11e7-849a-fa0d03ddd606.png)

As the figure shows it only need to setup a fully replication between two harbor nodes. This use case is more suitable for Geographically distributed team.

**Comment by rockwyc992** [comment]
I think it should a way to deploy Harbor into microservice.

That would let us to deploy harbor into Kubernetes more easily 
(just change a replicas size greater than 1). 

Kubernetes also provide a great ecosystem for HA and self-healing.

**Comment by yixingjia** [comment]
@rockwyc992  Thanks for the suggestions. 

We are currently try to refactor harbor to make most of the components stateless. Then it will be easy to deploy harbor to k8s.

**Comment by YaweiWu** [comment]
@yixingjia For solution 1, "Currently it doesn’t support Clair and Notary.". Cloud you explain that please?

**Comment by moooofly** [comment]
My key requirement is: **More than 50 services need to pull images of 2G+ size at the same time, causing a substantially large bandwidth consumption (maybe unacceptable)**.

IMO, solution 1 and 2 may not meet my requirements. Solution 3 is the best fit one, but need more mannul configuration to distribute images to a "suitable" place(s), in the mean while, the services must be clever enough to pick a "right" endpoint to pull image. Solution 4 may not meet my requirements too.

So actually, I need a design providing 

- the metadata of images distribution for pulling action
- a CLI tool or Web UI for easy customizing and managing the metadata of images distribution

tks

**Comment by yixingjia** [comment]
@YaweiWu  
We are currently support Clair in HA for Harbor in next release. 

We are still woking on notray. 

But you can alway setup and external Notary for the HA setup of Harbor.

**Comment by jcmartins** [comment]
Maybe it's to late but  why not change mariadb and redis to etcd or consul.io?

**Comment by jcmartins** [comment]
Maybe it's to late but  why not change mariadb and redis to etcd or consul.io?
Etcd or consul.io can be used to job schedule too.

**Comment by jahentao** [comment]
So, What's the current HA solution?

**Comment by reasonerjt** [comment]
@jahentao 
https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md

**Comment by consoleKEC** [comment]
> **Solution 1: Active-Active with scale out ability**
@yixingjia 
I use this plan to deploy a harbor cluster with two instances, but when I create harbor replication jobs, it is likely to going failed https://github.com/goharbor/harbor/issues/13000, when I use single harbor instance, the replication jobs runs successfully.

**Comment by odorT** [comment]
As the thread is closed, I guess Solution 4 will not work. Have anyone tried that? We have a situation where geolocations of datacenters are problematic

**Comment by ravik9853** [comment]
Hi yixingjia,

Could you please provide the steps to implement a Harbor solution on my own Kubernetes cluster running on bare metal? The goal is to set up the entire Harbor solution with an external database and an image scanner. 
Could you please help us the commands and steps .
Thanks
