### ISSUE TITLE
RESR-API: issue with the GET /projects?name=xxxx

### ISSUE THREAD

**Issue by ligc** [goharbor/harbor#3698]
I am using the Harbor REST APIs to automate a lot of activities with Harbor registries, one issue was found with the API "GET /projects?name=<project_name>", it does not do exact match with the project_name, it matches all the projects starts with the project_name, for example, I have three projects harbor1, harbor10 and harbor100, if I use "GET /api/projects?name=harbor1", it will return all the three projects that starts with "harbor1", i.e., harbor1, harbor10 and harbor100.

```
[root@ligc ~]# curl -X GET x1.clusters.com/api/projects?name=harbor1
[
  {
    "project_id": 1003,
    "owner_id": 1,
    "name": "harbor1",
    "creation_time": "2017-11-27T18:45:14Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2017-11-27T18:45:14Z",
    "current_user_role_id": 0,
    "repo_count": 0,
    "enable_content_trust": false,
    "prevent_vulnerable_images_from_running": false,
    "prevent_vulnerable_images_from_running_severity": "",
    "automatically_scan_images_on_push": false
  },
  {
    "project_id": 1004,
    "owner_id": 1,
    "name": "harbor10",
    "creation_time": "2017-11-27T18:45:21Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2017-11-27T18:45:21Z",
    "current_user_role_id": 0,
    "repo_count": 0,
    "enable_content_trust": false,
    "prevent_vulnerable_images_from_running": false,
    "prevent_vulnerable_images_from_running_severity": "",
    "automatically_scan_images_on_push": false
  },
  {
    "project_id": 1005,
    "owner_id": 1,
    "name": "harbor100",
    "creation_time": "2017-11-27T18:45:28Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2017-11-27T18:45:28Z",
    "current_user_role_id": 0,
    "repo_count": 0,
    "enable_content_trust": false,
    "prevent_vulnerable_images_from_running": false,
    "prevent_vulnerable_images_from_running_severity": "",
    "automatically_scan_images_on_push": false
  }
][root@ligc ~]#


[root@ligc ~]# curl -X GET x1.clusters.com/api/projects?name=harbor1 2>/dev/null | jq '.[].name'
"harbor1"
"harbor10"
"harbor100"
[root@ligc ~]#

```

**Comment by reasonerjt** [comment]
This is the expected behavior.

**Comment by ligc** [comment]
I am not sure if I agree, the argument is "name=xxx", name equals xxx, if we want to use this for regular expression, something like "name=~xxx" or "name=xxx*" will make more sense. 

Back to my scenario, I need to get the project_id through this API call, some of the project names do have overlap like department1, department11, any idea on how should I get the project id with name "department1"? I could use scripts to filter the output from the API call to get the exact "deparment1", but it does not seem graceful from the API call filtering perspective.

This is not a blocking issue, but does seem to be a "flaw" in the all amazing Harbor APIs, I have been enjoying the Harbor APIs in our production environment.

**Comment by ligc** [comment]
any update on this? We have been struggling with this issue in the last a few months... Thanks.

**Comment by ywk253100** [comment]
Work in progress...

**Comment by ywk253100** [comment]
Maybe we should introduce a unified filter rule for API.

**Comment by balonik** [comment]
Any update on this?
