### ISSUE TITLE
When to support P2P in image distribution?

### ISSUE THREAD

**Issue by lifubang** [goharbor/harbor#3769]
When to support P2P in image distribution? I need this feature as soon as possible. Thx.

**Comment by reasonerjt** [comment]
I don't think p2p distribution is within Harbor's scope.  I seems to require some other tool.

I'm interested to know the problem you are trying to solve.

**Comment by moooofly** [comment]
> Dragonfly is an intelligent P2P based file distribution system. It resolved issues like low-efficiency，low-success rate，waste of network bandwidth you faced in large-scale file distribution scenarios such as application deployment, large-scale cache file distribution, data file distribution, images distribution etc. In Alibaba, the system transferred 2 billion times and distributed 3.4PB data every month, it becomes one of the most important infrastructure in Alibaba. The reliability is up to 99.9999%.
>
> DevOps takes a lot of benefits from container technologies . but at the same time, it also bring a lot of challenges: the efficiency of image distribution, especially when you have a lot of applications and require image distribution at the same time. Dragonfly works extremely well with both Docker and Pouch, and actually we compatible with any other container technologies without any modifications of container engine.
>
> It delivers up to 57 times the throughput of native docker and saved up to 99.5% the out bandwidth of registry.

The above info from [alibaba/Dragonfly](https://github.com/alibaba/Dragonfly), that is why we need p2p ~~

**Comment by lifubang** [comment]
Yes, it's the reason why I need p2p in image distribution. @moooofly 
I need to send a 6G image to 100 servers. The registry server will be done when the 100 servers pulling the image at the same time.
But I can't deploy the dragonfly success because there are lack of docs.  https://github.com/alibaba/Dragonfly/issues/16

**Comment by moooofly** [comment]
@lifubang I did some research on alibaba/Dragonfly recently, and met the same problem as you.

**Comment by lifubang** [comment]
@moooofly , do you have any solutions to deal with this problem?

**Comment by moooofly** [comment]
@lifubang not found yet, maybe Solution 3 in [#3582](https://github.com/vmware/harbor/issues/3582) can help, but need some more manual working.

By the way, I'am still looking forward to P2P functionality in images distribution.
