### ISSUE TITLE
registry start take too long

### ISSUE THREAD

**Issue by qianmoke** [goharbor/harbor#3816]
when registry restart, it take long time. I found it stuck on:
root [ / ]# sh -x entrypoint.sh /etc/registry/config.yml 
+ set -e
+ '[' -d /etc/registry ']'
+ chown 10000:10000 -R /etc/registry
+ '[' -d /var/lib/registry ']'
+ chown 10000:10000 -R /var/lib/registry
+ '[' -d /storage ']'
+ chown 10000:10000 -R /storage

in my storage path which contain 6000+ images, about 800GB. I think there too many file in storage to consume mang time to change file mode.

**Comment by wy65701436** [comment]
Good catch @qianmoke, please help to upload Harbor log.

**Comment by wy65701436** [comment]
any updates? @qianmoke

**Comment by qianmoke** [comment]
in registry image entrypoint.sh, there are a command "chown 10000:10000 -R /var/lib/registry", when registry restart, always stuck on this chown. by the way, my storage backend is glusterfs.

**Comment by reasonerjt** [comment]
is it possible you help us disable glusterfs?  
I'm not expert in glusterfs but I feel it's maybe due to misconfiguration.

**Comment by qianmoke** [comment]
there are many files in the directory, when change the owner recursively, it took long time.
actually, we do not need execute the command "chown 10000:10000 -R /storage" every start. can we check the owner first?

**Comment by nlowe** [comment]
Can we please add an option to the entrypoint (or hell, even `harbor.cfg`) to skip the chown? Our instance has thousands of tags and about 1.7TB of data and takes about 35 minutes to startup. The data is on a windows share so the chown does nothing anyways.

I would make a patched image but then I have to edit the compose files each release.

**Comment by clouderati** [comment]
> * set -e
> * '[' -d /etc/registry ']'
> * chown 10000:10000 -R /etc/registry
> * '[' -d /var/lib/registry ']'
> * chown 10000:10000 -R /var/lib/registry
> * '[' -d /storage ']'
> * chown 10000:10000 -R /storage

Thanks for reporting this. IMHO this is a pretty shotgun approach to fixing a potential permission issue. Perhaps a better way of addressing this is to run a background job / daemon that identifies misconfigured permissions and either (a) warns the user or (b) if possible corrects the permissions.

**Comment by nlowe** [comment]
Still a problem for us on 1.7.x. @clouderati Has any additional thought been put into this? Our registry has grown to 2TB. I'm in the middle of an upgrade and it's been `chown`'ing for the last 25 minutes.

**Comment by wy65701436** [comment]
@nlowe this issue will be resolved in v1.8.0. It's a big change, so the fix will not in v1.7.x.

If you want to bypass the problem in v1.7.x, I think you can build a registry image and replace it with your env.

**How**

1. Remove the line to chown in the https://github.com/goharbor/harbor/blob/release-1.7.0/make/photon/registry/entrypoint.sh.
2. Build a registry image with docker file(https://github.com/goharbor/harbor/blob/release-1.7.0/make/photon/registry/Dockerfile).
Get registry binary from: https://storage.googleapis.com/harbor-builds/bin/registry
3. Replace the registry image in the docker-compose.yml file of your installer.

**Comment by wy65701436** [comment]
@ninjadq any updates?
