### ISSUE TITLE
Garbage collection: misleading README

### ISSUE THREAD

**Issue by Vanuan** [goharbor/harbor#3883]
There's this line in README:

> Image deletion & garbage collection: Images can be deleted and their space can be recycled.

Apparently, harbor doesn't have this feature. This should probably be moved to ROADMAP

**Comment by Vanuan** [comment]
There's a corresponding user guide option: https://github.com/vmware/harbor/blob/master/docs/user_guide.md#deleting-repositories

But it doesn't refer to Harbor, it refers to the docker registry CLI.

BTW, why documentation doesn't link to https://github.com/docker/distribution
Which modifications are made to docker distribution? Are they closed source?

Suggestions:

- put a link to https://github.com/docker/distribution in README
- open source or mainline patches to docker distribution server
- remove the line about garbage collection or make it clear that this is only about web UI to delete repos, there's no automation of CLI commands.

**Comment by wy65701436** [comment]
Thanks @Vanuan for your suggestion, as GC is under implementation and the document will be updated.

I'll close this issue and update the user guide about GC once it's enabled.
