### ISSUE TITLE
Job log should be saved to a centralized place

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#3919]
Job log should be saved to a centralized place

Issue

Replication/Scan job logs are stored in local filesystem.
In multiple instances scenario user will not be able to view replication/scan logs when a request redirect to the jobservices that don’t have the log file

Requirement

All the replication/scan job logs should be saved to a centralized place. All the jobservice instances should be able to access the job logs

Effort estimate

2 week/p
Currently, job logs are stored on local file system. 

Scope:
•1>Support save to redis( Prefered P0)
•2>Import a log system/library (need to investigation) P1
•3>Support save to NFS(Already support)

**Comment by steven-zou** [comment]
@yixingjia Can be try session-sticky solution？

**Comment by yixingjia** [comment]
It's not related with session-sticky.

User can logout and  login after somtime.

**Comment by yixingjia** [comment]
Per the discussion. In harbor 1.5 the Job history will saved to a shared storage. This will not need any extra works but only some environment preparations.  

Move this issue to post Harbor1.5

Save to DB and Redis will not an option according to the discussion.

**Comment by Freakin** [comment]
Was this implemented in 1.5.0?

**Comment by reasonerjt** [comment]
@Freakin no it's not.
