### ISSUE TITLE
BOSH release for Harbor HA deployment

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#3944]
Use this epic to track the development efforts of creating bosh release for Harbor HA deployment.

Possible scope:
### Harbor bosh release
[Option1] Add bosh jobs for the Harbor components:
* UI
* Jobservices
* Adminserver
* Syslog
* Harbor database
* Clair and clair db
* Notary and Notary db
* Nginx
* Keep alive/Haproxy

[Option2] Use docker-boshrelease?

### Create harbor tile
* [Option1] With bosh release based on the above release
* [Option2] Directly use 'docker' job type in tile

**Comment by steven-zou** [comment]
@stonezdj 

Transfer this task to you. If you think it's unnecessary as we have no plan to do it, you can directly close it then.

**Comment by stonezdj** [comment]
Close, because the HA is solved by harbor-helm
