### ISSUE TITLE
This file has a little wrong【https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md】

### ISSUE THREAD

**Issue by BonnieTang** [goharbor/harbor#3975]
This file has a little wrong: https://github.com/vmware/harbor/blob/master/docs/configure_swagger.md

[original text]:
Add two lines to the file docker-compose.yml under the section ui.volumes.
...
ui:
  ... 
  volumes:
    - ./common/config/ui/app.conf:/etc/ui/app.conf:z
    - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
    - /data/secretkey:/etc/ui/key:z
    - /data/ca_download/:/etc/ui/ca/:z
    ## add two lines as below ##
    **- ../src/ui/static/vendors/swagger-ui-2.1.4/dist:/harbor/static/vendors/swagger
    - ../src/ui/static/resources/yaml/swagger.yaml:/harbor/static/resources/yaml/swagger.yaml**
    ...

[Modified version]
It should be modified to this（.. to .）：
  **- ./src/ui/static/vendors/swagger-ui-2.1.4/dist:/harbor/static/vendors/swagger
  - ./src/ui/static/resources/yaml/swagger.yaml:/harbor/static/resources/yaml/swagger.yaml**

because  prepare-swagger.sh and swagger.yaml under the docs directory to your local Harbor directory, eg /app/harbor/docs , so after  ./prepare-swagger.sh , the swagger file under /app/harbor/src

**Comment by clouderati** [comment]
Hi Bonnie – thanks for raising this issue.

Would love a PR to fix this – let us know if you need help with the nuts and bolts on how to accomplish this.
