### ISSUE TITLE
Unable to delete Harbor repos

### ISSUE THREAD

**Issue by tirumaraiselvan** [goharbor/harbor#4023]
Hi, I am trying to delete a project from the admin UI. The project has a repo, so I first delete the repo which gives a successful message. Even the log says 200:

```
Jan 15 06:43:47 172.18.0.1 proxy[1389]: 27.59.8.178 - "DELETE /api/repositories/cassava35/cassava35-cassava35-user.bot-bot HTTP/1.1" 200 0 "https://registry.xxxx.io/harbor/projects/1080/repositories" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" 0.862 0.862 .
```
But the repo doesn't get deleted. It just stays there and I am unable to delete the project. How can I debug this? Please help.

Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.17.1, build 6d101fb

**Comment by ywk253100** [comment]
What is the version of Harbor? 
And please upload all logs under directory `/var/log/harbor`.

**Comment by tirumaraiselvan** [comment]
@ywk253100 Sorry for getting back so late. Here is the info you requested. This is happening repeatedly for certain repos.

Harbor version: 1.2.2

Attached are the logs for one day where we were retrying to delete the repo `books40/books40-books40-user.mydfhook-app`
[5.tar.gz](https://github.com/vmware/harbor/files/1694629/5.tar.gz)

**Comment by tirumaraiselvan** [comment]
@ywk253100 Hey! Any help on this would be appreciated!

**Comment by ywk253100** [comment]
This happens for all images or just some special images?

**Comment by tirumaraiselvan** [comment]
Few images. Although all random images, nothing specific. I tried to pull one of these images (aforementioned) to see if there was anything special there but got this error:

```
$ docker pull registry.harbor.hasura-app.io/books40/books40-books40-user.mydfhook-app:c18f4925101231e03ea94d5ea2fea847f3e565ff
Error response from daemon: manifest for registry.harbor.hasura-app.io/books40/books40-books40-user.mydfhook-app:c18f4925101231e03ea94d5ea2fea847f3e565ff not found
```

**Comment by tirumaraiselvan** [comment]
Yes, it exists:
 `docker/registry/v2/blobs/sha256/3d/3dee44e846de9584268358b72a96300fb331bf5a6cb8afa30d6386ed8bfa0516/data`

Here are the contents:

[blobs-data.txt](https://github.com/vmware/harbor/files/1772020/blobs-data.txt)
