### ISSUE TITLE
Date time picker should switch to Chinese format

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#4093]
After switching language to Chinese, the datetime picker should display Chinese.

**Comment by stonezdj** [comment]
<img width="1333" alt="screen shot 2018-01-22 at 5 16 20 pm" src="https://user-images.githubusercontent.com/2696760/35213371-5a82a916-ff98-11e7-8bd6-42a74c13435b.png">

**Comment by ninjadq** [comment]
data picker widget no longer exist.
