### ISSUE TITLE
Zero downtime backup

### ISSUE THREAD

**Issue by sl4dy** [goharbor/harbor#4101]
Currently, it is possible to do only downtime backup regarding the doc. However, zero downtime backup is very desirable for production use.

**Comment by clouderati** [comment]
Can you share a bit more detail around what you see as an ideal scenario for backup? Are you talking about backing up the non-image data (replication rules, users, RBAC configuration, etc.)? Or are you envisioning a backup of the images, too?

**Comment by kyrogue** [comment]
Any suggestions on how would /data be backed up?

**Comment by sl4dy** [comment]
I am talking about the harbor-db backup. From the docs available there is a backup section in Migration guide which suggest running migrator image and this is a downtime procedure.

However to perform regular ~daily backups something like this:
```
$ docker ps  -f name=harbor-db 
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS               NAMES
2faf202a7721        vmware/harbor-db:v1.5.2   "/usr/local/bin/do..."   2 days ago          Up 14 minutes (healthy)   3306/tcp            harbor-db

$ docker exec -t 2faf202a7721 /usr/bin/mysqldump --user root -proot123 registry > bkp.sql
```
is enough and it can be done online.
