### ISSUE TITLE
email clair scan report

### ISSUE THREAD

**Issue by andrewtchin** [goharbor/harbor#4144]
@malikkal commented on [Tue Jan 23 2018](https://github.com/vmware/vic-product/issues/1324)

Can we have a configuration option to email alert the DevOps admin the results of clair emage scan, please? Alternatively, we could configure a list of email addresses per repository that would receive the html scan report. Thanks.

**Comment by GDixon7623** [comment]
+1 this would be great to notify if the scan finds any vulnerabilities

**Comment by matthiasgrewe** [comment]
+1 I also think this would be a useful feature

**Comment by pier4r** [comment]
+1 mee too.

**Comment by rainerlischetzki** [comment]
+1

**Comment by HT43-bqxFqB** [comment]
+1

**Comment by jfrantzius** [comment]
+1

**Comment by stevenfricke** [comment]
+1

**Comment by moveaperto** [comment]
+1

**Comment by Tobrek** [comment]
+1

**Comment by niconeumann** [comment]
+1

**Comment by bomb2777** [comment]
+1

**Comment by oshamin** [comment]
+1

**Comment by saarktim** [comment]
+1 this would be definitely a useful feature

**Comment by heartbeatispringsolutions** [comment]
+1

**Comment by catchups** [comment]
+1

**Comment by kyberorg** [comment]
It would be really nice to have. It should improve security.

**Comment by wy65701436** [comment]
@kyberorg for the latest harbor, you can export the CVE report to a csv file. Have you tried that?

**Comment by kyberorg** [comment]
@wy65701436 no, but I will.

**Comment by wy65701436** [comment]
sure, let me close it since harbor already supports the cve export and deprecates the email capability.

**Comment by lclc** [comment]
It's a pity this got closed.   So there are no plans at all now to inform admins/users about insecure images?
