### ISSUE TITLE
Harbor not compatible with upstream default "library" namespace

### ISSUE THREAD

**Issue by braddeicide** [goharbor/harbor#4208]
When using Harbor as a registry mirror using single word namespaces such as

pull ubuntu
and 
from ubuntu

Do not work and must be changed to library/ubuntu

Not a massive hassle, but it means previously working Dockerfiles and scripts break.

**Comment by steven-zou** [comment]
Seems it makes sense, the none-prefix image should be automatically pointed to the default project 'library'. @hainingzhang @grantsunny @reasonerjt

**Comment by reasonerjt** [comment]
@steven-zou I believe the issue decribed in OP is the behavior of docker's vanilla registry.

**Comment by 8ear** [comment]
Hi,
is there any news about this issue?
