### ISSUE TITLE
Configure_https.md should have the steps in Configuration and Installation paragraph

### ISSUE THREAD

**Issue by jeffweilee** [goharbor/harbor#4258]
In the document ["configure_https.md"](https://github.com/vmware/harbor/blob/master/docs/configure_https.md), I believe it is necessary to add a paragraph in "Configuration and Installation"

> If you have a self-signed certificate, after generating yourdomain.com.crt and yourdomain.com.key, you should also copy "ca.crt" to docker client  ```/etc/docker/certs.d/yourdomain.com``` so that docker client (also browser client) will not refuse the connection, e.g. x509: certificate signed by unknown authority (also NET::ERR_INVALID_CERT through browser).
Otherwise, you will be refused to visit through docker request as well as browser!

**Comment by reasonerjt** [comment]
Could you submit a PR to help us improve?

**Comment by jeffweilee** [comment]
Sure, I have submitted a PR to refine Configure_https.md. Please refer to PR  #4279 
Thanks.
https://github.com/vmware/harbor/pull/4279
