### ISSUE TITLE
Outdated harbor-py on pypi

### ISSUE THREAD

**Issue by ochedru** [goharbor/harbor#4273]
The latest version of harbor-py (1.2.0) available on [pypi](https://pypi.python.org/pypi/harbor-py/) is from a [2-year-old repository](https://github.com/tobegit3hub/harbor-py) and is not fully compatible with more recent versions of harbor.
For example, `get_repository_tags()` will always fail.
Please upgrade package harbor-py to version 1.4.0.

**Comment by reasonerjt** [comment]
The `harbor-py` is contributed by community user, would you like to help to fix it?

**Comment by ochedru** [comment]
Sure. How do I proceed?

**Comment by reasonerjt** [comment]
I was thinking you could help by contributing the code. 
But after CNCF donation we decided to associate external projects in a different way so I will remove it from this repo.
