### ISSUE TITLE
Error on startup of MariaDB if host is in fips mode

### ISSUE THREAD

**Issue by sdpippin** [goharbor/harbor#4276]
On harbor-db startup with new MariaDB engine I see the following error in the mysql.log file when fips mode is enabled:

NOTE: If fips mode is disabled everything works fine.

Feb 15 13:19:55 drprog.mtctrains.com mysql[5051]: Version: '10.2.10-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Source distribution
Feb 15 13:19:55 drprog.mtctrains.com mysql[5051]: 2018-02-15 20:19:55 140633972913920 [Note] InnoDB: Buffer pool(s) load completed at 180215 20:19:55
Feb 15 13:19:56 drprog.mtctrains.com mysql[5051]: sha_locl.h(128): OpenSSL internal error, assertion failed: Low level API call to digest SHA1 forbidden in FIPS mode!
Feb 15 13:19:56 drprog.mtctrains.com mysql[5051]: 180215 20:19:56 [ERROR] mysqld got signal 6 ;

 - docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Thu Nov 16 15:19:17 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Thu Nov 16 15:19:17 2017
 OS/Arch:         linux/amd64

 - docker-compose version
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

 - OpenSSL version
OpenSSL 1.0.2k-fips  26 Jan 2017

[adminserver.log](https://github.com/vmware/harbor/files/1729418/adminserver.log)
[jobservice.log](https://github.com/vmware/harbor/files/1729419/jobservice.log)
[mysql.log](https://github.com/vmware/harbor/files/1729420/mysql.log)
[registry.log](https://github.com/vmware/harbor/files/1729421/registry.log)
[ui.log](https://github.com/vmware/harbor/files/1729422/ui.log)
[docker-compose.txt](https://github.com/vmware/harbor/files/1729425/docker-compose.txt)
[harbor.txt](https://github.com/vmware/harbor/files/1729426/harbor.txt)

**Comment by reasonerjt** [comment]
This seems due to 
https://jira.mariadb.org/browse/MDEV-14567?workflowName=MariaDB+v3&stepId=9

We'll need to wait for a new version MariaDB in our internal repo to include the fix.

**Comment by yilmi** [comment]
Just for the record, I provided more details about this issue on the Jira tracker of the MariaDB project: https://jira.mariadb.org/browse/MDEV-20260
