### ISSUE TITLE
need more option on 'Deployment security'

### ISSUE THREAD

**Issue by ziozzang** [goharbor/harbor#4280]
I love this feature but it has an issue with ubuntu/debian images.

need option blocking download for
- not only "Prevent images with vulnerability serverity of 'LEVEL of SERVERITY'  and above from being deployed."
- but also "Prevent images download only when not patched (patch exist but not patched)"

The reason of this option is....
debian and ubuntu has wired policy about CVE. they registered and marked all even not affected issue.

**Comment by reasonerjt** [comment]
@clouderati @grantsunny 
thoughts?
