### ISSUE TITLE
how to clear useless blobs automatically ?

### ISSUE THREAD

**Issue by russellgao** [goharbor/harbor#4292]
how to clear useless blobs automatically, like maintenance.uploadpurging .  if a image repeatly push more times , which will generate some useless blobs .

**Comment by reasonerjt** [comment]
You need to manually run GC.

**Comment by russellgao** [comment]
yes , manually run GC that is useful ,but that also can like maintenance.uploadpurging , provide a configure to clear useless blobs automatically .

**Comment by reasonerjt** [comment]
That will be a requirement of docker registry, there are a few limitations for implementing it on Harbor due to current design of the registry.
