### ISSUE TITLE
Name of the MariaDB database should be configurable

### ISSUE THREAD

**Issue by ArcticSnowman** [goharbor/harbor#4304]
At present the MariaDB/MySQLDB used is 'registry',  However  when you use this with an external DB this name is too generic and could clash with others.   This name should be configurable so that when an external database is set up the name can be altered to fit better.  
`harbor-registry` for instance.

**Comment by geosword** [comment]
100% agree with this. is the database name hardcoded?

**Comment by geosword** [comment]
unfortunately, setting the environment variable makes no difference.

this insanity is why:
```
$ cat make/photon/db/initial-registry.sql; echo
CREATE DATABASE registry ENCODING 'UTF8';
\c registry;

CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
```
