### ISSUE TITLE
Use go-uaac as UAA client in Harbor BOSH release.

### ISSUE THREAD

**Issue by jessehu** [goharbor/harbor#4313]
Better to use rubygem 'cf-uaac' to create/delete Harbor UAA client, rather than using 'curl' call to UAA REST API. cf-uaac is the official UAA CLI for managing UAA for the best usability and compatibility. @frodenas shared several appoarches of how to package rubygems into a bosh release.

    1) Using the ruby vendor package and storing vendored gems at the github repo: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/tree/master/packages/bosh_aws_cpi
    2) Using its own ruby package and using a pre_packaging script to vendor gems: https://gitlab.eng.vmware.com/PKS/pks-vrli-release/tree/master/packages/fluentd  
    3) Similar to the above, but packaging uaac: https://github.com/cloudfoundry-community/admin-ui-boshrelease/tree/master/packages/uaac

**Comment by steven-zou** [comment]
@jessehu Why this refactor is blocker of 1.1? I did not get it. I know we should refine it in 1.1, but seems current api calling will not cause 1.1 failed to run. Confusing.

**Comment by jessehu** [comment]
This is not a blocker for 1.1, just an enhancement user story/task planned for pks 1.1 release. This story belongs to the PKS 1.1 Epic, not blocks it. The term 'blocking'/'blocked' used by Zenhub is confusing us.

**Comment by steven-zou** [comment]
Move to SP 30 to complete.

**Comment by steven-zou** [comment]
As a nice to have feature, move to next SP 32 to find a proper time slot to complete.

**Comment by jessehu** [comment]
Discussed with Steven. Move this task out of 1.5.0 release.

**Comment by steven-zou** [comment]
@stonezdj '

Transfer bosh related work to you.

**Comment by stonezdj** [comment]
Because it doesn't add any feature and current tile works fine, we keep the previous form.
