### ISSUE TITLE
/data/config/config.json isn't updated during a ./install.sh or ./prepare

### ISSUE THREAD

**Issue by Moumoutaru** [goharbor/harbor#4325]
docker-compose version: 1.9.0, build 258387
docker version: 17.05.0-ce, build 89658be
harbor version: 1.3

When updating harbors configuration, LDAP settings don't appear to be updated for the application. I updated the LDAP search password to something bogus, brought harbor back up and was able to successfully login when I shouldn't have been able to. Upon further investigation it would appear `/data/config/config.json` doesn't get updated when you run ./prepare or when you run ./install.sh. As far as I can tell harbor uses the config.json file for the bulk of it's active settings. This file needs to be updated or deleted and recreated during a ./prepare and ./install.sh or the documentation needs updated to reflect that this file needs deleted to successfully updated configuration.

For reference the below steps to reproduce are taken from: https://github.com/vmware/harbor/blob/master/docs/installation_guide.md

Steps to reproduce:
```
$ sudo docker-compose down -v
$ vim harbor.cfg (update ldap search password from something that works to something that doesn't)
$ sudo prepare
$ sudo docker-compose up -d

**Comment by reasonerjt** [comment]
@Moumoutaru 
As the backend for storing the configuration varies, it can be in config.json or user DB, etc. It is by design that some configurations have to be modified via UI/API after initial bootstrap.

**Comment by Moumoutaru** [comment]
Is there a specific reason that some configurations would have to be modified via the UI/API after initial bootstrap? Take Ansible for example, I want to be able to update configurations, bring the containers down, run prepare, and bring them back up to have configs updated without having to interact with the UI.  If everything in the config is configurable via the API then I could see the case for it. For now I guess I'll just delete the config file to force the prepare script to regenerate it with any chances that might have took place.

**Comment by reasonerjt** [comment]
I believe this is no longer an issue after we rework the adminserver and the way the configuration is propagated.

**Comment by louyiping** [comment]
got the same issue.I hope we can still change the conf by modify the conf file not only by UI/API.
