### ISSUE TITLE
Pull images error when the harbor as a mirror register

### ISSUE THREAD

**Issue by cjk87927** [goharbor/harbor#4337]
When I pull the official image,the result is success:
`docker pull tomcat:8`

When I pull the public image,the result is fail:
`docker pull bitnami/memcached:latest`
Error response from daemon: pull access denied for bitnami/memcached, repository does not exist or may require 'docker login'

common/config/registry/config.yml:
`version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://docker-hub-mirror.d17.cc/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://ui:8080/service/notifications
        timeout: 3000ms
        threshold: 5
        backoff: 1s

proxy:
  remoteurl: https://registry-1.docker.io`

registry.log:
`Mar  3 16:24:46 172.18.0.1 registry[2417]: time="2018-03-03T08:24:46.680104871Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=23ae9c7b-ea03-4e6e-aedf-ad6b400b251e http.request.method=HEAD http.request.remoteaddr="172.18.0.6:56610" http.request.uri="/v2/bitnami/memcached/manifests/latest" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=10.450233872s http.response.status=200 http.response.written=2414 instance.id=1f45dd09-d4e1-4b02-8f50-3e1e4ed60b21 service=registry version=v2.6.2 
Mar  3 16:24:46 172.18.0.1 registry[2417]: 172.18.0.6 - - [03/Mar/2018:08:24:36 +0000] "HEAD /v2/bitnami/memcached/manifests/latest HTTP/1.1" 200 2414 "" "Go-http-client/1.1"
Mar  3 16:24:46 172.18.0.1 registry[2417]: time="2018-03-03T08:24:46.687040753Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.3 http.request.host=docker-hub-mirror.d17.cc http.request.id=c08486d3-bdf0-45c6-82b4-02ede1f38c32 http.request.method=GET http.request.remoteaddr=192.168.2.207 http.request.uri="/v2/bitnami/memcached/manifests/latest" http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.4.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(linux\\))" instance.id=1f45dd09-d4e1-4b02-8f50-3e1e4ed60b21 service=registry vars.name="bitnami/memcached" vars.reference=latest version=v2.6.2 
Mar  3 16:24:46 172.18.0.1 registry[2417]: 172.18.0.6 - - [03/Mar/2018:08:24:46 +0000] "GET /v2/bitnami/memcached/manifests/latest HTTP/1.1" 401 160 "" "docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.4.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(linux\\))"`

docker version
    17.09.1-ce

docker-compose version
    1.18.0

harbor version
    1.3.0

**Comment by reasonerjt** [comment]
This is expected behavior, harbor enabled auth in the registry and when there is `docker pull` it tries to query local DB for the authority, which will fail in the case when you configure the registry as pull through cache.

**Comment by cjk87927** [comment]
@reasonerjt 
Thank you for your answer.
Can I change it? When the library is not exist, the register can create it automatically
If possible, which file should I modify

**Comment by reasonerjt** [comment]
@cjk87927 You can try, but I don't have a clear answer for that.
Harbor is not supported to be set as a cache, but maybe some hack can workaround various limitations.
