### ISSUE TITLE
Delete old data from replication_jobs table

### ISSUE THREAD

**Issue by cbarzu** [goharbor/harbor#4341]
Hi guys,

I have the next problem in Harbor 1.3, I don't know if the problem is solved in 1.4.

When I want to see the project replication rule it doesn't load:
https://registry.com/harbor/projects/2/replications

Why? Because our  replication_jobs table is very huge, with more than 2.000.000 entrys. 

Checking the database we see that a big query is beeing made which takes a lot of time:

```
select rp.id, rp.project_id, rp.target_id, rt.name as target_name, rp.name, rp.enabled, rp.description, rp.cron_str, rp.start_time, rp.creation_time, rp.update_time, count(rj.status) as error_job_count
from replication_policy rp left join replication_target rt
	on rp.target_id=rt.id left join replication_job rj
	on rp.id=rj.policy_id
	and (rj.status="error" or rj.status="retrying")
where rp.deleted = 0
group by rp.id
order by rp.creation_time
```
It needs up to 1 min 4.70 sec to do the query.

Solution: 

Create an index:

```
create index idx_replication_job_policy_id on replication_job(policy_id,status);
```

Now the need time is 0.91 sec:

```
select rp.id, rp.project_id, rp.target_id, rt.name as target_name, rp.name, rp.enabled, rp.description, rp.cron_str, rp.start_time, rp.creation_time, rp.update_time, count(rj.status) as error_job_count
from replication_policy rp left join replication_target rt
	on rp.target_id=rt.id left join replication_job rj
	on rp.id=rj.policy_id
	and (rj.status="error" or rj.status="retrying")
where rp.deleted = 0
group by rp.id
```

Can you add that index by default ? Or can you delete old that from the table replication_jobs. For me "old data" means everything older than 30 days. Or can you only save last 100 entryes for each project or something like that ?

If this is solved in 1.4 you can close this ticket.

Thank you,

Claudiu

**Comment by reasonerjt** [comment]
@cbarzu thanks a lot raising this issue.

We still have this issue in 1.4

We'll add the index and open another issue for doing regular clean up to the job data.

Could you kindly provide more information to understand your scenario, to help us understand how it reached millions of jobs?

**Comment by cbarzu** [comment]
To monitor if harbor works as expected, we pull and push an image every minute. By mistake we set the repository to replicate to other 5 harbores we have, and now we have a lot of replication logs in that table. I am not sure if I can delete safely the data from that table ( only the data related to that repository) so I created the index.

**Comment by xaleeks** [comment]
what's the status on this? @reasonerjt

**Comment by reasonerjt** [comment]
This can be closed as reworked the replication.
