### ISSUE TITLE
How to limit the number of replication job logs

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#4343]
Hi All, We have more than 2M replication job logs, is the any configuration property to limit the number of replication logs to keep in the filesystem?

Thanks.

**Comment by reasonerjt** [comment]
Currently not, you'll have to remove the log manually from the filesystem, we'll think about how to better support large-scale usage, but it's a systematic work so will need some time to design.

**Comment by reasonerjt** [comment]
Yep

**Comment by reasonerjt** [comment]
@roldancer in the next version the job logs will be swept regularly, but that means after that the log will be gone, I assume that's acceptable?
