### ISSUE TITLE
Can Harbor show layer information (SHA) of an image?

### ISSUE THREAD

**Issue by jeffweilee** [goharbor/harbor#4352]
Being a container image registry with vulnerability scan function, it should be important for Harbor to display layer information for each image with search and filter features. Tracking vulnerability issues in a layer across images and managing ancestry layer of an image all rely on the feature. For now, it is not able to know the layer composition of an image on Harbor UI.

Is there any existing plugins or plans in the future to support 
 - Displaying the layer information (SHA) of an image on Harbor UI
 - Search or filter layer information across images in Harbor registry
 - Vulnerability dashboard from image layer's point of view

**Comment by clouderati** [comment]
No support currently, but I agree this would be a useful feature to add. PRs are welcomed, else we'll add this to our backlog. 👍

**Comment by mpostelnicu** [comment]
this would be really useful. is this planned?
