### ISSUE TITLE
The About dialog needs to be reworked.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#4357]
@lweitzman commented on [Tue Mar 06 2018](https://github.com/vmware/harbor-planning/issues/39)

The About dialog should be more graphic as seen here.

![Screen Shot 2018-03-06 at 10.35.57 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/dd92a0fc-58fb-4b23-bb1e-bf635011f266)

**Comment by zhoumeina** [comment]
@lweitzman , currently the about dialog looks quite similar as this design. The only difference is it does not have the picture in the left part. Could you please give me the design pickture in the left part?

**Comment by lweitzman** [comment]
Given the move to CNCF and removal of VMware branding we should do something more like this.
https://vmware.invisionapp.com/share/6HN0EZMVC5M#/309241785_Branding_-_About_Dialog
its not clear to me when all trademarks etc are also removed. check with PM

**Comment by zhoumeina** [comment]
@lweitzman , do you know where "End User Licence Agreement" link for? Currently, we don't have this link.

**Comment by zhoumeina** [comment]
@lweitzman , another question about the logo. We don't have the logo pure black. Do you need to give us one? Or it can use the current colorful one.

**Comment by zhoumeina** [comment]
fixed by pr #5556
