### ISSUE TITLE
The admin profile allows switching username to admin@harbor.local with confusing interaction

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#4358]
The ability to change the admin's ID to one with @harbor.local is very confusing.
This needs to be redesigned and the language needs to be fixed as well.

![screen shot 2018-03-07 at 8 48 00 am](https://user-images.githubusercontent.com/626032/37097805-59a66b12-21ea-11e8-9319-ce66fa7d926f.png)

![screen shot 2018-03-07 at 8 51 20 am](https://user-images.githubusercontent.com/626032/37097808-5c571262-21ea-11e8-90c8-7dd0524afc78.png)

**Comment by steven-zou** [comment]
@lweitzman, please help to redesign. @ninjadq will help to fix it,

**Comment by lweitzman** [comment]
@ninjadq please look at https://vmware.invisionapp.com/share/2WG9HU34YVJ#/284141143_User_Profile to understand new design of switching admin to admin@harbor.local. please contact me if you have any questions.

**Comment by sigsbee** [comment]
when user use ldap auth mode, there maybe a ldap user named admin can not login for the user name admin is used
