### ISSUE TITLE
Data too long for column 'tags' 

### ISSUE THREAD

**Issue by tkatkov** [goharbor/harbor#4382]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

1) Irrelevant
2) Irrelevant
3) from ui.log:
`
Mar  8 18:30:55 172.18.0.1 ui[15409]: 2018-03-08T18:30:55Z [DEBUG] [controller.go:312]: submiting replication job to jobservice: &{79 library/php transfer [5-alpine 5-apache 5-cli 5-fpm-alpine 5-fpm 5-zts-alpine 5-zts 5.3-apache 5.3-cli 5.3.29-apache 5.3.29-cli 5.3.29 5.3 5.4-apache 5.4-cli 5.4-fpm 5.4.32-apache 5.4.32-cli 5.4.33-apache 5.4.33-cli 5.4.33 5.4.34-apache 5.4.34-cli 5.4.34 5.4.35-apache 5.4.35-cli 5.4.35-fpm 5.4.35 5.4.36-apache 5.4.36-cli 5.4.36-fpm 5.4.36 5.4.37-apache 5.4.37-cli 5.4.37-fpm 5.4.37 5.4.38-apache 5.4.38-cli 5.4.38-fpm 5.4.38 5.4.39-apache 5.4.39-cli 5.4.39-fpm 5.4.39 5.4.40-apache 5.4.40-cli 5.4.40-fpm 5.4.40 5.4.41-apache 5.4.41-cli 5.4.41-fpm 5.4.41 5.4.42-apache 5.4.42-cli 5.4.42-fpm 5.4.42 5.4.43-apache 5.4.43-cli 5.4.43-fpm 5.4.43 5.4.44-apache 5.4.44-cli 5.4.44-fpm 5.4.44 5.4.45-apache 5.4.45-cli 5.4.45-fpm 5.4.45 5.4 5.5-alpine 5.5-apache 5.5-cli 5.5-fpm-alpine 5.5-fpm 5.5-zts-alpine 5.5-zts 5.5.16-apache 5.5.16-cli 5.5.17-apache 5.5.17-cli 5.5.17 5.5.18-apache 5.5.18-cli 5.5.18 5.5.19-apache 5.5.19-cli 5.5.19-fpm 5.5.19 5.5.20-apache 5.5.20-cli 5.5.20-fpm 5.5.20 5.5.21-apache 5.5.21-cli 5.5.21-fpm 5.5.21 5.5.22-apache 5.5.22-cli 5.5.22-fpm 5.5.22 5.5.23-apache 5.5.23-cli 5.5.23-fpm 5.5.23 5.5.24-apache 5.5.24-cli 5.5.24-fpm 5.5.24 5.5.25-apache 5.5.25-cli 5.5.25-fpm 5.5.25 5.5.26-apache 5.5.26-cli 5.5.26-fpm 5.5.26 5.5.27-apache 5.5.27-cli 5.5.27-fpm 5.5.27 5.5.28-apache 5.5.28-cli 5.5.28-fpm 5.5.28 5.5.29-apache 5.5.29-cli 5.5.29-fpm 5.5.29 5.5.30-apache 5.5.30-cli 5.5.30-fpm 5.5.30 5.5.31-apache 5.5.31-cli 5.5.31-fpm 5.5.31-zts 5.5.31 5.5.32-apache 5.5.32-cli 5.5.32-fpm 5.5.32-zts 5.5.32 5.5.33-alpine 5.5.33-apache 5.5.33-cli 5.5.33-fpm-alpine 5.5.33-fpm 5.5.33-zts-alpine 5.5.33-zts 5.5.33 5.5.34-alpine 5.5.34-apache 5.5.34-cli 5.5.34-fpm-alpine 5.5.34-fpm 5.5 5.5.34-zts-alpine 5.5.34-zts 5.5.34 5.5.35-alpine 5.5.35-apache 5.5.35-cli 5.5.35-fpm-alpine 5.5.35-fpm 5.5.35-zts-alpine 5.5.35-zts 5.5.35 5.5.36-alpine 5.5.36-apache 5.5.36-cli 5.5.36-fpm-alpine 5.5.36-fpm 5.5.36-zts-alpine 5.5.36-zts 5.5.36 5.5.37-alpine 5.5.37-apache 5.5.37-cli 5.5.37-fpm-alpine 5.5.37-fpm 5.5.37-zts-alpine 5.5.37-zts 5.5.37 5.5.38-alpine 5.5.38-apache 5.5.38-cli 5.5.38-fpm-alpine 5.5.38-fpm 5.5.38-zts-alpine 5.5.38-zts 5.5.38 5.6-alpine 5.6-apache 5.6-cli 5.6-fpm-alpine 5.6-fpm 5.6-zts-alpine 5.6-zts 5.6.0-apache 5.6.0-cli 5.6.1-apache 5.6.1-cli 5.6.1 5.6.10-apache 5.6.10-cli 5.6.10-fpm 5.6.10 5.6.11-apache 5.6.11-cli 5.6.11-fpm 5.6.11 5.6.12-apache 5.6.12-cli 5.6.12-fpm 5.6.12 5.6.13-apache 5.6.13-cli 5.6.13-fpm 5.6.13 5.6.14-apache 5.6.14-cli 5.6.14-fpm 5.6.14 5.6.15-apache 5.6.15-cli 5.6.15-fpm 5.6.15 5.6.16-apache 5.6.16-cli 5.6.16-fpm 5.6.16 5.6.17-apache 5.6.17-cli 5.6.17-fpm 5.6.17-zts 5.6.17 5.6.18-apache 5.6.18-cli 5.6.18-fpm 5.6.18-zts 5.6.18 5.6.19-alpine 5.6.19-apache 5.6.19-cli 5.6.19-fpm-alpine 5.6.19-fpm 5.6.19-zts-alpine 5.6.19-zts 5.6.19 5.6.2-apache 5.6.2-cli 5.6.2 5.6.20-alpine 5.6.20-apache 5.6.20-cli 5.6.20-fpm-alpine 5.6.20-fpm 5.6.20-zts-alpine 5.6.20-zts 5.6.20 5.6.21-alpine 5.6.21-apache 5.6.21-cli 5.6.21-fpm-alpine 5.6.21-fpm 5.6.21-zts-alpine 5.6.21-zts 5.6.21 5.6.22-alpine 5.6.22-apache 5.6.22-cli 5.6.22-fpm-alpine 5.6.22-fpm 5.6.22-zts-alpine 5.6.22-zts 5.6.22 5.6.23-alpine 5.6.23-apache 5.6.23-cli 5.6.23-fpm-alpine 5.6.23-fpm 5.6.23-zts-alpine 5.6.23-zts 5.6.23 5.6.24-alpine 5.6.24-apache 5.6.24-cli 5.6.24-fpm-alpine 5.6.24-fpm 5.6.24-zts-alpine 5.6.24-zts 5.6.24 5.6.25-alpine 5.6.25-apache 5.6.25-cli 5.6.25-fpm-alpine 5.6.25-fpm 5.6.25-zts-alpine 5.6.25-zts 5.6.25 5.6.26-alpine 5.6.26-apache 5.6.26-cli 5.6.26-fpm-alpine 5.6.26-fpm 5.6.26-zts-alpine 5.6.26-zts 5.6.26 5.6.27-alpine 5.6.27-apache 5.6.27-cli 5.6.27-fpm-alpine 5.6.27-fpm 5.6.27-zts-alpine 5.6.27-zts 5.6.27 5.6.28-alpine 5.6.28-apache 5.6.28-cli 5.6.28-fpm-alpine 5.6.28-fpm 5.6.28-zts-alpine 5.6.28-zts 5.6.28 5.6.29-alpine 5.6.29-apache 5.6.29-cli 5.6.29-fpm-alpine 5.6.29-fpm 5.6.29-zts-alpine 5.6.29-zts 5.6.29 5.6.3-apache 5.6.3-cli 5.6.3-fpm 5.6.3 5.6.30-alpine 5.6.30-apache 5.6.30-cli 5.6.30-fpm-alpine 5.6.30-fpm 5.6.30-zts-alpine 5.6.30-zts 5.6.30 5.6.4-apache 5.6.4-cli 5.6.4-fpm 5.6.4 5.6.5-apache 5.6.5-cli 5.6.5-fpm 5.6.5 5.6.6-apache 5.6.6-cli 5.6.6-fpm 5.6.6 5.6.7-apache 5.6.7-cli 5.6.7-fpm 5.6.7 5.6.8-apache 5.6.8-cli 5.6.8-fpm 5.6.8 5.6.9-apache 5.6.9-cli 5.6.9-fpm 5.6.9 5.6 5 7-alpine 7-apache 7-cli 7-fpm-alpine 7-fpm 7-zts-alpine 7-zts 7.0-alpine 7.0-apache 7.0-cli 7.0-fpm-alpine 7.0-fpm 7.0-zts-alpine 7.0-zts 7.0.0-apache 7.0.0-cli 7.0.0-fpm 7.0.0 7.0.0RC1-apache 7.0.0RC1-cli 7.0.0RC1-fpm 7.0.0RC1 7.0.0RC2-apache 7.0.0RC2-cli 7.0.0RC2-fpm 7.0.0RC2 7.0.0RC3-apache 7.0.0RC3-cli 7.0.0RC3-fpm 7.0.0RC3 7.0.0RC4-apache 7.0.0RC4-cli 7.0.0RC4-fpm 7.0.0RC4 7.0.0RC5-apache 7.0.0RC5-cli 7.0.0RC5-fpm 7.0.0RC5 7.0.0RC6-apache 7.0.0RC6-cli 7.0.0RC6-fpm 7.0.0RC6 7.0.0RC7-apache 7.0.0RC7-cli 7.0.0RC7-fpm 7.0.0RC7 7.0.0RC8-apache 7.0.0RC8-cli 7.0.0RC8-fpm 7.0.0RC8 7.0.0beta1-apache 7.0.0beta1-cli 7.0.0beta1-fpm 7.0.0beta1 7.0.0beta2-apache 7.0.0beta2-cli 7.0.0beta2-fpm 7.0.0beta2 7.0.0beta3-apache 7.0.0beta3-cli 7.0.0beta3-fpm 7.0.0beta3 7.0.1-apache 7.0.1-cli 7.0.1-fpm 7.0.1 7.0.10-alpine 7.0.10-apache 7.0.10-cli 7.0.10-fpm-alpine 7.0.10-fpm 7.0.10-zts-alpine 7.0.10-zts 7.0.10 7.0.11-alpine 7.0.11-apache 7.0.11-cli 7.0.11-fpm-alpine 7.0.11-fpm 7.0.11-zts-alpine 7.0.11-zts 7.0.11 7.0.12-alpine 7.0.12-apache 7.0.12-cli 7.0.12-fpm-alpine 7.0.12-fpm 7.0.12-zts-alpine 7.0.12-zts 7.0.12 7.0.13-cli 7.0.13-alpine 7.0.13-apache 7.0.13-fpm-alpine 7.0.13-fpm 7.0.13-zts-alpine 7.0.13-zts 7.0.13 7.0.14-alpine 7.0.14-apache 7.0.14-cli 7.0.14-fpm-alpine 7.0.14-fpm 7.0.14-zts-alpine 7.0.14-zts 7.0.14 7.0.15-alpine 7.0.15-apache 7.0.15-cli 7.0.15-fpm-alpine 7.0.15-fpm 7.0.15-zts-alpine 7.0.15-zts 7.0.15 7.0.16-alpine 7.0.16-apache 7.0.16-cli 7.0.16-fpm-alpine 7.0.16-fpm 7.0.16-zts-alpine 7.0.16-zts 7.0.16 7.0.17-alpine 7.0.17-apache 7.0.17-cli 7.0.17-fpm-alpine 7.0.17-fpm 7.0.17-zts-alpine 7.0.17-zts 7.0.17 7.0.18-alpine 7.0.18-apache 7.0.18-cli 7.0.18-fpm-alpine 7.0.18-fpm 7.0.18-zts-alpine 7.0.18-zts 7.0.18 7.0.19-alpine 7.0.19-apache 7.0.19-cli 7.0.19-fpm-alpine 7.0.19-fpm 7.0.19-zts-alpine 7.0.19-zts 7.0.19 7.0.2-apache 7.0.2-cli 7.0.2-fpm 7.0.2-zts 7.0.2 7.0.3-apache 7.0.3-cli 7.0.3-fpm 7.0.3-zts 7.0.3 7.0.4-alpine 7.0.4-apache 7.0.4-cli 7.0.4-fpm-alpine 7.0.4-fpm 7.0.4-zts-alpine 7.0.4-zts 7.0.4 7.0.5-alpine 7.0.5-apache 7.0.5-cli 7.0.5-fpm-alpine 7.0.5-fpm 7.0.5-zts-alpine 7.0.5-zts 7.0.5 7.0.6-alpine 7.0.6-apache 7.0.6-cli 7.0.6-fpm-alpine 7.0.6-fpm 7.0.6-zts-alpine 7.0.6-zts 7.0.6 7.0.7-alpine 7.0.7-apache 7.0.7-cli 7.0.7-fpm-alpine 7.0.7-fpm 7.0.7-zts-alpine 7.0.7-zts 7.0.7 7.0.8-alpine 7.0.8-apache 7.0.8-cli 7.0.8-fpm-alpine 7.0.8-fpm 7.0.8-zts-alpine 7.0.8-zts 7.0.8 7.0.9-alpine 7.0.9-apache 7.0.9-cli 7.0.9-fpm-alpine 7.0.9-fpm 7.0.9-zts-alpine 7.0.9-zts 7.0.9 7.0 7.1-alpine 7.1-apache 7.1-cli 7.1-fpm-alpine 7.1-fpm 7.1-rc-alpine 7.1-rc-apache 7.1-rc-cli 7.1-rc-fpm-alpine 7.1-rc-fpm 7.1-rc-zts-alpine 7.1-rc-zts 7.1-rc 7.1-zts-alpine 7.1-zts 7.1.0-alpine 7.1.0-apache 7.1.0-cli 7.1.0-fpm-alpine 7.1.0-fpm 7.1.0-zts-alpine 7.1.0-zts 7.1.0 7.1.0RC1-alpine 7.1.0RC1-apache 7.1.0RC1-cli 7.1.0RC1-fpm-alpine 7.1.0RC1-fpm 7.1.0RC1-zts-alpine 7.1.0RC1-zts 7.1.0RC1 7.1.0RC2-alpine 7.1.0RC2-apache 7.1.0RC2-cli 7.1.0RC2-fpm-alpine 7.1.0RC2-fpm 7.1.0RC2-zts-alpine 7.1 7.1.0RC2-zts 7.1.0RC2 7.1.0RC3-alpine 7.1.0RC3-apache 7.1.0RC3-cli 7.1.0RC3-fpm-alpine 7.1.0RC3-fpm 7.1.0RC3-zts-alpine 7.1.0RC3-zts 7.1.0RC3 7.1.0RC4-alpine 7.1.0RC4-apache 7.1.0RC4-cli 7.1.0RC4-fpm-alpine 7.1.0RC4-fpm 7.1.0RC4-zts-alpine 7.1.0RC4-zts 7.1.0RC4 7.1.0RC5-alpine 7.1.0RC5-apache 7.1.0RC5-cli 7.1.0RC5-fpm-alpine 7.1.0RC5-fpm 7.1.0RC5-zts-alpine 7.1.0RC5-zts 7.1.0RC5 7.1.0RC6-alpine 7.1.0RC6-apache 7.1.0RC6-cli 7.1.0RC6-fpm-alpine 7.1.0RC6-fpm 7.1.0RC6-zts-alpine 7.1.0RC6-zts 7.1.0RC6 7.1.1-alpine 7.1.1-apache 7.1.1-cli 7.1.1-fpm-alpine 7.1.1-fpm 7.1.1-zts-alpine 7.1.1-zts 7.1.1 7.1.2-alpine 7.1.2-apache 7.1.2-cli 7.1.2-fpm-alpine 7.1.2-fpm 7.1.2-zts-alpine 7.1.2-zts 7.1.2 7.1.3-alpine 7.1
Mar  8 18:30:55 172.18.0.1 ui[15409]: -alpine 7.2.1-cli-alpine3.6 7.2.1-zts-alpine3.7 7.2.1-fpm-alpine3.7 7.2.1-alpine3.7 7.2.1-cli-alpine3.7 5.6.33-zts-jessie 5.6.33-zts 5.6.33-fpm-jessie 5.6.33-fpm 5.6.33-apache-jessie 5.6.33-apache 5.6.33-cli-jessie 5.6.33-cli 5.6.33 5.6.33-jessie 7.0.27-zts-jessie 7.0.27-zts 7.0.27-fpm-jessie 7.0.27-fpm 7.0.27-apache-jessie 7.0.27-apache 7.0.27-cli-jessie 7.0.27-cli 7.0.27-jessie 7.0.27 7.1.13-zts-jessie 7.1.13-zts 7.1.13-fpm-jessie 7.1.13-fpm 7.1.13-apache-jessie 7.1.13-apache 7.1.13-cli-jessie 7.1.13-cli 7.1.13 7.1.13-jessie 7.2.1-zts-stretch 7.2.1-zts 7.2.1-fpm-stretch 7.2.1-fpm 7.2.1-apache 7.2.1-apache-stretch 7.2.1-cli 7.2.1 7.2.1-cli-stretch 7.2.1-stretch 7.1.14-zts-alpine 7.1.14-zts-alpine3.4 7.1.14-fpm-alpine 7.1.14-fpm-alpine3.4 7.1.14-alpine 7.1.14-alpine3.4 7.1.14-cli-alpine 7.1.14-cli-alpine3.4 7.1.14-zts-jessie 7.1.14-zts 7.1.14-apache 7.1.14-fpm-jessie 7.1.14-fpm 7.1.14-apache-jessie 7.1.14-cli 7.1.14 7.1.14-cli-jessie 7.1.14-jessie 7.2.2-zts-alpine 7.2.2-zts-alpine3.6 7.2.2-fpm-alpine 7.2.2-fpm-alpine3.6 7.2.2-alpine 7.2.2-alpine3.6 7.2.2-cli-alpine 7.2.2-cli-alpine3.6 7.2.2-zts-alpine3.7 7.2.2-fpm-alpine3.7 7.2.2-alpine3.7 7.2.2-cli-alpine3.7 7.2.2-fpm-stretch 7.2.2-fpm 7.2.2-apache-stretch 7.2.2-apache 7.2.2-cli-stretch 7.2.2-cli 7.2.2-stretch 7.2.2 7.2.2-zts-stretch 7.2.2-zts 5.6.34-zts-alpine 5.6.34-zts-alpine3.4 5.6.34-fpm-alpine 5.6.34-fpm-alpine3.4 5.6.34-alpine 5.6.34-alpine3.4 5.6.34-cli-alpine 5.6.34-cli-alpine3.4 5.6.34-zts 5.6.34-zts-jessie 5.6.34-fpm 5.6.34-fpm-jessie 5.6.34-apache 5.6.34-apache-jessie 5.6.34 5.6.34-cli 5.6.34-cli-jessie 5.6.34-jessie 7.0.28-zts-alpine 7.0.28-zts-alpine3.4 7.0.28-fpm-alpine 7.0.28-fpm-alpine3.4 7.0.28-alpine 7.0.28-alpine3.4 7.0.28-cli-alpine 7.0.28-cli-alpine3.4 7.0.28-zts 7.0.28-zts-jessie 7.0.28-fpm 7.0.28-fpm-jessie 7.0.28-apache 7.0.28-apache-jessie 7.0.28 7.0.28-cli 7.0.28-cli-jessie 7.0.28-jessie 7.1.15-zts-alpine 7.1.15-zts-alpine3.4 7.1.15-fpm-alpine 7.1.15-fpm-alpine3.4 7.1.15-zts 7.1.15-zts-jessie 7.1.15-fpm 7.1.15-fpm-jessie 7.1.15-apache 7.1.15-apache-jessie 7.1.15 7.1.15-cli 7.1.15-cli-jessie 7.1.15-jessie 7.2.3-zts-alpine 7.2.3-zts-alpine3.6 7.2.3-fpm-alpine 7.2.3-fpm-alpine3.6 7.2.3-alpine 7.2.3-alpine3.6 7.2.3-cli-alpine 7.2.3-cli-alpine3.6 7.2.3-zts-alpine3.7 7.2.3-fpm-alpine3.7 7.2.3-alpine3.7 7.2.3-cli-alpine3.7 7.2.3-zts 7.2.3-zts-stretch 7.2.3-fpm 7.2.3-fpm-stretch 7.2.3-apache 7.2.3-apache-stretch 7.2.3 7.2.3-cli 7.2.3-cli-stretch 7.2.3-stretch 7.1.15-alpine 7.1.15-alpine3.4 7.1.15-cli-alpine 7.1.15-cli-alpine3.4]}
Mar  8 18:30:55 172.18.0.1 ui[15409]: 2018-03-08T18:30:55Z [ERROR] [notifier.go:202]: Error occurred when triggering handler *event.StartReplicationHandler of topic StartReplication: http error: code 500, message Error 1406: Data too long for column 'tags' at row 1
`

**Comment by ywk253100** [comment]
Fixed.
