### ISSUE TITLE
Link to the Dockerfile in the UI 

### ISSUE THREAD

**Issue by nvpnathan** [goharbor/harbor#4428]
Add the ability to view the Dockerfile for the container image in the UI. If this is possible we could highlight the vulnerable packages from the scanning with Clair. Use different colors based upon the severity of the vulnerability found.

**Comment by reasonerjt** [comment]
@nvpnathan thanks for raising the issue.

However, one gap here is there's no support of `building` image in Harbor, so if we allow user to upload the dockerfile as a metadata of the image, there maybe inconsistencies we can't detect.

**Comment by odg0318** [comment]
I desire this feature.
Git repository is good way instead of uploading Dockerfile.
