### ISSUE TITLE
harbor(1.2.2) image is not displayed on the UI page

### ISSUE THREAD

**Issue by happyshui** [goharbor/harbor#4431]
docker version: 17.09.0-ce
kubernetes version: v1.8.4
Using kubernetes deployment harbor, harbor started successfully, all pods in running state, client push image, ui page is not displayed, only when ui pod is restarted can show success.

**Comment by moshucong** [comment]
+1

**Comment by steven-zou** [comment]
Seems same issue with #3825

**Comment by reasonerjt** [comment]
#3825 is closed shall we keep this open?

**Comment by reasonerjt** [comment]
Closing due to in-activity.
