### ISSUE TITLE
Can't setup replication between harbor and an ECS registry

### ISSUE THREAD

**Issue by arthurlogilab** [goharbor/harbor#4451]
We're trying to setup a replication between our harbor installation and and ECS registry. 

ECS registry comes with a predefined password that you can get through `aws cli` with `aws ecr get-login --no-include-email --region eu-west-1` the user is AWS and the password is pretty long (in this case 1916 characters long), I don't think there is a way to change it since it's generated by AWS. 

When using the "test connection" button we get a " Failed to ping endpoint." error message on the web interface. "failed to ping target" from the API. 

When we remove the https:// from the URL I think it tries in http and times out (which probably leaked the above password over clear text communication - or not if port 80 is not listening which seems to be the case for AWS ECS - this is probably another issue). 

Then when we try to save the endpoint anyway we get " Invalid endpoint name. " in the web interface. We tried to understand what was wrong with the name (but it was a simple string "ECS"). Looking at the API response we see "password max length is 48".  https://github.com/vmware/harbor/blob/64cc71ea12acff7d0f5179bcbd0c346a0aa256a6/src/common/models/replication_job.go#L103-L107 seems to be the culprit. 

So this in my opinion is a double bug : 

* displayed error is wrong
* can't replicate with a registry that has a long password

**Comment by steven-zou** [comment]
@arthurlogilab 

So far, harbor does not support replicating images to any harbor instance.

**Comment by clouderati** [comment]
Agreed – "integration" with other registries is something we've definitely talked about and there have been a few issues where similar topics have been discussed.

@arthurlogilab Can you share your use case here? Are you simply hoping to replication to / from an external registry, or is there something else you're hoping to accomplish?

**Comment by arthurlogilab** [comment]
@clouderati yes it's pretty simple, we have a jenkins building docker images, pushing to harbor and we would like harbor to push to ECS to have a mirror of that registry to be used by applications on AWS, the application also runs nearer to harbor which is in a different zone.

**Comment by clouderati** [comment]
Thanks @arthurlogilab – totally reasonable use case. Let's keep this open to track this request.

PRs welcomed. 😄

**Comment by arthurlogilab** [comment]
We still have this problem, thanks for not marking it as stale.

**Comment by PatelParas** [comment]
+1

**Comment by tschwaller** [comment]
When we get Web Hooks (#6676) in Harbor, one could use this mechanisms as intermediate solution to trigger a push of the image to an ECS registry. Either by pulling it from Harbor using a Transit VM or by directly pushing it from the Harbor VM.

**Comment by wzcwts521** [comment]
+1, Pretty much the same use case as arthurlogilab mentioned.
It would be great to have plugin(s) for multiple cloud registry. etc, Azure, google could. 

Thanks.

**Comment by reasonerjt** [comment]
@ywk253100 Since we target this in 1.9, please either reference it in the Epic or dup it to a new issue to track the work.

**Comment by ywk253100** [comment]
Track the work in #7977, closing this one.
