### ISSUE TITLE
push images retry

### ISSUE THREAD

**Issue by duanyifei1937** [goharbor/harbor#4476]
# Problem description：
i login harbor is sucess, but, push images layer retry.
i think push layer to ks3(like aliyun storate service),but no received complete information, to make retry push.
1. $ docker -v
Docker version 17.12.1-ce, build 7390fc6
$ docker-compose  -v
docker-compose version 1.19.0, build 9e633ef

2. harbor.conf: 
`## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = harbor.xxx.com

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#Maximum number of job workers in job service
max_job_workers = 5

#Determine whether or not to generate certificate for the registry's token.
#If the value is on, the prepare script creates new root cert and private key
#for generating token to access the registry. If the value is off the default key/cert will be used.
#This flag also controls the creation of the notary signer's cert.
customize_crt = on

#The path of cert and key files for nginx, they are applied only the protocol is set to https
#ssl_cert = /data/cert/server.crt
#ssl_cert_key = /data/cert/server.key
ssl_cert = /root/cert/xxx.net.crt
ssl_cert_key = /root/cert/xxx.net.key

#The path of secretkey storage
secretkey_path = /data/

#Admiral's url, comment this attribute, or set its value to NA when Harbor is standalone
admiral_url = NA

#Log files are rotated log_rotate_count times before being removed. If count is 0, old versions are removed rather than rotated.
log_rotate_count = 10
#Log files are rotated only if they grow bigger than log_rotate_size bytes. If size is followed by k, the size is assumed to be in kilobytes.
#If the M is used, the size is in megabytes, and if G is used, the size is in gigabytes. So size 100, size 100k, size 100M and size 100G
#are all valid.
log_rotate_size = 200M

#NOTES: The properties between BEGIN INITIAL PROPERTIES and END INITIAL PROPERTIES
#only take effect in the first boot, the subsequent changes of these properties
#should be performed on web ui

#************************BEGIN INITIAL PROPERTIES************************

#Email account settings for sending out password resetting emails.

#Email server uses the given username and password to authenticate on TLS connections to host and act as identity.
#Identity left blank to act as username.
email_identity =

email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
email_insecure = false

##The initial password of Harbor admin, only works for the first time when Harbor starts.
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#A user's DN who has the permission to search the LDAP/AD server.
#If your LDAP/AD server does not support anonymous search, you should configure this DN and ldap_search_pwd.
#ldap_searchdn = uid=searchuser,ou=people,dc=mydomain,dc=com

#the password of the ldap_searchdn
#ldap_search_pwd = password

#The base DN from which to look up a user in LDAP/AD
ldap_basedn = ou=people,dc=mydomain,dc=com

#Search filter for LDAP/AD, make sure the syntax of the filter is correct.
#ldap_filter = (objectClass=person)

# The attribute used in a search to match a user, it could be uid, cn, email, sAMAccountName or other attributes depending on your LDAP/AD
ldap_uid = uid

#the scope to search for users, 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
ldap_scope = 2

#Timeout (in seconds)  when connecting to an LDAP Server. The default value (and most reasonable) is 5 seconds.
ldap_timeout = 5

#Verify certificate from LDAP server
ldap_verify_cert = true

#Turn on or off the self-registration feature
self_registration = on

#The expiration time (in minute) of token created by token service, default is 30 minutes
token_expiration = 30

#The flag to control what users have permission to create projects
#The default value "everyone" allows everyone to creates a project.
#Set to "adminonly" so that only admin user can create project.
project_creation_restriction = everyone

#************************END INITIAL PROPERTIES************************

#######Harbor DB configuration section#######

#The address of the Harbor database. Only need to change when using external db.
db_host = mysql

#The password for the root user of Harbor DB. Change this before any production use.
db_password = root123

#The port of Harbor database host
db_port = 3306

#The user name of Harbor database
db_user = root

##### End of Harbor DB configuration#######

#The redis server address. Only needed in HA installation.
redis_url =

##########Clair DB configuration############

#Clair DB host address. Only change it when using an exteral DB.
clair_db_host = postgres

#The password of the Clair's postgres database. Only effective when Harbor is deployed with Clair.
#Please update it before deployment. Subsequent update will cause Clair's API server and Harbor unable to access Clair's database.
clair_db_password = password

#Clair DB connect port
clair_db_port = 5432

#Clair DB username
clair_db_username = postgres

#Clair default database
clair_db = postgres

##########End of Clair DB configuration############

#The following attributes only need to be set when auth mode is uaa_auth
uaa_endpoint = uaa.mydomain.org
uaa_clientid = id
uaa_clientsecret = secret
uaa_verify_cert = true
uaa_ca_cert = /path/to/ca.pem
`

### Docker Registry setting ###
#registry_storage_provider can be: filesystem, s3, gcs, azure, etc.
#registry_storage_provider_name = filesystem
registry_storage_provider_name = ks3
#registry_storage_provider_config is a comma separated "key: value" pairs, e.g. "key1: value, key2: value2".
#Refer to https://docs.docker.com/registry/configuration/#storage for all available configuration.
registry_storage_provider_config =`
3) error log:
`Mar 25 19:09:09 172.18.0.1 registry[20632]: time="2018-03-25T11:09:09.466481575Z" level=error msg="response completed with error" auth.user.name=work err.code="blob unknown" err.detail=sha256:23a6960fe4a9c3e7eef587883882c351af2d8488f97ab4c42e03111ad267 err.message="blob unknown to registry" go.version=go1.6.3 http.request.host=harbor.xxx.net http.request.id=b016b9ad-10b6-42b7-90e6-85fc2c42923f http.request.method=HEAD http.request.remoteaddr=172.16.16.22 http.request.uri="/v2/redash/redash/blobs/sha256:23a6960fe4a9c3e7eef587883882c351af2d8488f97ab4c42e03111ad26741e9" http.request.useragent="docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/3.10.0-693.11.6.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=31.472064ms http.response.status=404 http.response.written=157 instance.id=c6ae88f4-9e31-4a18-8f16-26f9287a7c95 service=registry vars.digest="sha256:23a6960fe4a9c3e7eef587883882c351af2d8488f97ab4c42e03111ad2674" vars.name="redash/redash" version=fc5eca8
`

**Comment by duanyifei1937** [comment]
the master is : 
`level=error msg="response completed with error" auth.user.name=work err.code="blob unknown" err.detail=sha256:23a6960fe4a9c3e7eef587883882c351af2d8488f97ab4c42e03111ad26741e9 err.message="blob unknown to registry"`

**Comment by duanyifei1937** [comment]
$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS                                                              NAMES
a66c51638312        vmware/nginx-photon:v1.4.0         "nginx -g 'daemon of…"   27 minutes ago      Up 27 minutes             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
93eb0ccf42f0        vmware/harbor-jobservice:v1.4.0    "/harbor/start.sh"       27 minutes ago      Up 27 minutes (healthy)                                                                      harbor-jobservice
22eb41a3e101        vmware/harbor-ui:v1.4.0            "/harbor/start.sh"       27 minutes ago      Up 27 minutes (healthy)                                                                      harbor-ui
55f5a9eec39e        ksyun/registry:latest              "registry serve /etc…"   27 minutes ago      Up 27 minutes             5000/tcp                                                           registry
0acae93c9a56        vmware/harbor-adminserver:v1.4.0   "/harbor/start.sh"       27 minutes ago      Up 27 minutes (healthy)                                                                      harbor-adminserver
9eaf5a0f0f13        vmware/harbor-db:v1.4.0            "/usr/local/bin/dock…"   27 minutes ago      Up 27 minutes (healthy)   3306/tcp                                                           harbor-db
e8cd68642d55        vmware/harbor-log:v1.4.0           "/bin/sh -c /usr/loc…"   27 minutes ago      Up 27 minutes (healthy)   127.0.0.1:1514->10514/tcp                                          harbor-log

**Comment by JunkaiLee** [comment]
err.detail="filesystem: mkdir /mnt/mycephfs: permission denied"

我是用的ceph，我检查了ceph的服务器，防火墙是关闭的，这个错误也是导致我无法push镜像，不知道为什么
