### ISSUE TITLE
`/etc/adminserver/key` file is empty after rebuild the image

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#4525]
WeChat Group user Young Lee rebuild an image through administrator base image. But the `/etc/adminserver/key` is empty

**Comment by ninjadq** [comment]
Docker file 
```
From xxx/harbor/adminserver:v1
COPY key /etc/adminserver/key
```

**Comment by LiYoungYoung** [comment]
I wonder if this key  is related to the environment variable?

**Comment by reasonerjt** [comment]
@LiYoungYoung how did you start the container? 
the key was mounted via docker-compose in the default deployment approach.

**Comment by LiYoungYoung** [comment]
@reasonerjt  I rebuilt the image of the adminserver, UI, and jobservice , first start the log, registry, the db container and then start the adminserver, then  error occurs.

Dockerfile content as follows
From 10.124.142.41/harbor/adminserver:v1
COPY  key /etc/adminserver/key

errors as follow
2018-03-29T06:36:48Z [INFO] initializing system configurations...
2018-03-29T06:36:48Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
2018-03-29T06:36:48Z [INFO] initializing database: type-MySQL host-10.124.142.116 port-6033 user-root database-registry
2018-03-29T06:36:56Z [INFO] initialize database completed
2018-03-29T06:36:56Z [FATAL] [main.go:46]: failed to initialize the system: strconv.Atoi: parsing "": invalid syntax

**Comment by reasonerjt** [comment]
@LiYoungYoung Are you sure this particular error
```
2018-03-29T06:36:56Z [FATAL] [main.go:46]: failed to initialize the system: strconv.Atoi: parsing "": invalid syntax
```
was due to empty key file?

I mean the key file should not be empty but this error looks like incorrect setting.  
By default you need to set a lot of env vars to adminserver when starting the container, for details see
```
https://github.com/vmware/harbor/blob/master/make/common/templates/adminserver/env
```
You need to make sure all these variables are set correctly.

If you are not sure, please install via an offline installer and use `docker inspect` to check.

**Comment by LiYoungYoung** [comment]
@reasonerjt  Now , I can make sure the key is not empty in the container  by executing the following command.
docker run -ti --entrypoint=bash ******/devp/adminserver:v1
Now,I want to know which environment variable of adminserver is related to key.My adminserver env file as follows.
 PORT=8080
 LOG_LEVEL=debug
 EXT_ENDPOINT=http://172.16.138.111
 AUTH_MODE=db_auth
 SELF_REGISTRATION=on
 LDAP_URL=ldaps://ldap.mydomain.com
 LDAP_SEARCH_DN=
 LDAP_SEARCH_PWD=
 LDAP_BASE_DN=ou=people,dc=mydomain,dc=com
 LDAP_FILTER=
 LDAP_UID=uid
 LDAP_SCOPE=2
 LDAP_TIMEOUT=5
 LDAP_VERIFY_CERT=true
 DATABASE_TYPE=mysql
 MYSQL_HOST=172.16.138.111
 MYSQL_PORT=6033
 MYSQL_USR=root
 MYSQL_PWD=root123
 MYSQL_DATABASE=registry
 REGISTRY_URL=http://172.16.138.111:6055
 TOKEN_SERVICE_URL=http://ui/service/token
 EMAIL_HOST=smtp.mydomain.com
 EMAIL_PORT=25
 EMAIL_USR=sample_admin@mydomain.com
 EMAIL_PWD=abc
 EMAIL_SSL=false
 EMAIL_FROM=admin <sample_admin@mydomain.com>
 EMAIL_IDENTITY=
 EMAIL_INSECURE=false
 HARBOR_ADMIN_PASSWORD=Harbor54321
 PROJECT_CREATION_RESTRICTION=everyone
 MAX_JOB_WORKERS=3
 UI_SECRET=V9L5eWkuJaSC0vQz
 JOBSERVICE_SECRET=pUBSQkfsFBY28d4N
 TOKEN_EXPIRATION=30
 CFG_EXPIRATION=5
 GODEBUG=netdns=cgo
 ADMIRAL_URL=NA
 WITH_NOTARY=False
 WITH_CLAIR=False
 CLAIR_DB_PASSWORD=password
 CLAIR_DB_HOST=postgres
 CLAIR_DB_PORT=5432
 CLAIR_DB_USERNAME=postgres
 CLAIR_DB=postgres
 RESET=true
 UAA_ENDPOINT=uaa.mydomain.org
 UAA_CLIENTID=id
 UAA_CLIENTSECRET=secret
 UAA_VERIFY_CERT=true
 UI_URL=http://172.16.138.111:8083
 JOBSERVICE_URL=http://172.16.138.111:8084
 REGISTRY_STORAGE_PROVIDER_NAME=filesystem

**Comment by reasonerjt** [comment]
https://github.com/vmware/harbor/blob/master/src/adminserver/systemcfg/systemcfg.go#L46

**Comment by LiYoungYoung** [comment]
@reasonerjt Now，I want to know the meaning of the environment variable！Thanks！

**Comment by reasonerjt** [comment]
@LiYoungYoung   
Which vars are you curious about?
The env vars are to be transparent to end user, so quite a few of them are not documented.

**Comment by LiYoungYoung** [comment]
@reasonerjt  the function of env of ”SHLVL=1”?
