### ISSUE TITLE
The adminserver can't not start  in k8s

### ISSUE THREAD

**Issue by rootdeep** [goharbor/harbor#4543]
I deployed the harbor service in k8s with harbor v1.4, but the adminserver can't start due to some missed parameters. The error output show bellow: 

Error from server (BadRequest): container "harbor-adminserver-app" in pod "harbor-adminserver-2972198455-z09nh" is waiting to start: Couldn't find key CLAIR_DB_PORT in ConfigMap kube-system/harbor-adminserver-config

I  find the reason and try to resolve it in a branch.

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
This should no longer a problem in helm chart deployment.
