### ISSUE TITLE
Rest API: Unable to get details of a single repository

### ISSUE THREAD

**Issue by RothAndrew** [goharbor/harbor#4554]
Harbor v1.4

As far as I can tell, there is no rest api endpoint to get the details of a single repository.

I can run GET `/api/repositories?project_id=1&q=myrepository` but if I have two repositories with very similar names, say, "myrepository" and "myrepositorytest", it will return both of them.

There is no endpoint GET `/api/repositories/{repository_name}`

Edit: An even better endpoint would be GET `/api/repositories/{repository_id}`.

**Comment by ywk253100** [comment]
`GET /projects/{project_name}/repositories/{repository_name}` is already supported in v2.0
