### ISSUE TITLE
Harbor should expose metrics.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#4557]
This helpful for user who host Harbor as a service.

> Harbor does not expose any metrics.  As the registry will be a crucial piece of our pipeline (and offering) it will be subjected to an SLA and we'll need some internal metrics published over Prometheus (our monitoring solution).  We must be able to quickly diagnose problems and eventually page SRE engineers.

**Comment by jnovack** [comment]
I'm pretty sure Prometheus-compatible metrics exposure is almost a requirement in 2018 for project adoption.  🤔

**Comment by jcmartins** [comment]
+1

**Comment by jakirpatel** [comment]
+1 
This will be really helpful if harbor expose the metrics which will give insights of the harbor. @reasonerjt

**Comment by jakirpatel** [comment]
any update for this in roadmap activities..?

**Comment by clouderati** [comment]
Definitely on our roadmap and we hope to get to it as soon as possible. If anyone is interested in contributing please let me know. :smile:

**Comment by aylei** [comment]
@clouderati I would love to help with this issue.😁

**Comment by aylei** [comment]
Hi, is there any update on this issue? I think we can introduce the prometheus format metrics to harbor as the first step, and add nessary

**Comment by salkin** [comment]
A good start would be amount of pulls / push with error codes to get more insight about unauthorized pulls.

**Comment by darkl0rd** [comment]
You can effectively get this for "free" these days, as Docker Distribution provides Prometheus metrics since v2.7.1 (See https://github.com/docker/distribution/commit/e3c37a46e2529305ad6f5648abd6ab68c777820a and for docs: https://github.com/docker/distribution/blob/master/docs/configuration.md)

To adopt, this would imply:

a) updating the version of docker distribution (currently 2.6.4) to 2.7.1 or later.
b) an adjustment to the registry/config.yml (see linked docs)
c) updating nginx.conf (to expose the endpoint).

**Comment by YakirShriker** [comment]
> A good start would be amount of pulls / push with error codes to get more insight about unauthorized pulls.

does anyone know how can I query harbor(api) for pull and push operations?

**Comment by armandorvila** [comment]
+1

**Comment by secret104278** [comment]
+1

**Comment by HaveFun83** [comment]
+1

**Comment by KarstenSiemer** [comment]
+1

**Comment by hairyhenderson** [comment]
I'm pretty sure the `+1` messages are unhelpful and only serve to frustrate maintainers - use reactions (like 👍) instead to indicate that you're in support of this 😉

**Comment by hairyhenderson** [comment]
> You can effectively get this for "free" these days, as Docker Distribution provides Prometheus metrics since v2.7.1

Seems that since #8003 the `go.mod` pulls in `docker/distribution` 2.7.1+, so at least part of the work is done - is anyone working on the remaining pieces?

**Comment by xaleeks** [comment]
If anyone wants to work on this issue please reach out.

**Comment by MartinForReal** [comment]
I would like to work on this issue. Thanks!

**Comment by huzhengchuan** [comment]
+1

**Comment by Hokwang** [comment]
looking forward this issue adding in 2.0 commitments.

**Comment by lianghuiyuan** [comment]
+1

**Comment by kadzu** [comment]
+1

**Comment by rafis** [comment]
+1

**Comment by mawl** [comment]
+1

**Comment by hrak** [comment]
I subscribed to this issue to stay informed on the developments of this feature, not to be emailed every day with another useless "+1" response kthx.

**Comment by Okabe-Kurisu** [comment]
> I subscribed to this issue to stay informed on the developments of this feature, not to be emailed every day with another useless "+1" response kthx.

+1

**Comment by c4po** [comment]
I'm building a `harbor-exporter` https://github.com/c4po/harbor_exporter to dump the data from harbor API to prometheus format. All suggestions are welcome.

**Comment by Pruthvi08** [comment]
I face issues while using https://github.com/c4po/harbor_exporter. 

Issue: 
level=error ts=2020-03-17T13:58:20.891Z caller=harbor_exporter.go:111 msg="error gathering metrics:8 error(s) occurred:\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"hard\" > gauge:<value:-1 > } was collected before with the same name and label values\n* collected metric \"harbor_quotas_count_total\" { label:<name:\"repo_id\" value:\"0\" > label:<name:\"repo_name\" value:\"\" > label:<name:\"type\" value:\"used\" > gauge:<value:0 > } was collected before with the same name and label values\n* collected metric

**Comment by hrak** [comment]
@Pruthvi08 then open an issue [there](https://github.com/c4po/harbor_exporter.) 🤷🏼‍♂️

**Comment by Hokwang** [comment]
@xaleeks I am concerned that this issue is still in the backlog. Does that mean that this issue cannot be resolved until version 2.2?

**Comment by Okabe-Kurisu** [comment]
it means "maybe never"

**Comment by xaleeks** [comment]
@Hokwang We are still in planning stage and it didn't make it into the 2.1 release hopper unfortunately.  To have a better chance of delivering this in 2.2, we need be finalizing some high level design pretty soon.  Do you have some bandwidth to contribute to this as well?

**Comment by standup-jb** [comment]
+1 
Hope provide the promethes exporter metrics

**Comment by unixzen** [comment]
+1

**Comment by bitsf** [comment]
I just saw a related article.
https://sysdig.com/blog/monitor-harbor-registry/
https://github.com/c4po/harbor_exporter

**Comment by addozhang** [comment]
+1

**Comment by DesistDaydream** [comment]
I prefer the official to provide metrics directly, rather than through exporter

**Comment by xaleeks** [comment]
Everyone please feel free to chime in with your requirements, we're working on a functional spec right now.  Will share more on the next community meeting, or perhaps the one after that

**Comment by fredgate** [comment]
Some great metrics would be the results of the scans. So we could have alerts when vulnerabilties are found.

**Comment by xaleeks** [comment]
updated proposal is here
https://github.com/goharbor/community/pull/147

**Comment by kong62** [comment]
+1

**Comment by dongjiang1989** [comment]
+1

**Comment by amaters-easy** [comment]
> metrics that will be captured in next v2.2 release are here
> 
> https://docs.google.com/document/d/1J_jiJVdV4AOB9lf9PtN5T1LoqHlHF8SjLjI2KL17b0o/edit

this document shows that the following metrics will be implemented:
Scan status 				labels: scan job id
Total vulnerabilities(p2)			labels: project id

Maybe I can't find them or they are still in development?

**Comment by ninjadq** [comment]
@amaters-easy The vulnerabilities are based on artifacts. So it can become a huge number.  So it isn't a good practice to expose them. It will be added in a future releases if we find a proper way.

**Comment by cparadal** [comment]
@ninjadq what about replication policy status metrics? They're also in the document but i can't see them in Prometheus. Is that something that's planned to be relased in further releases? I'm especially interestered in knowing when scheduled replication rules stop triggering (something that happens a lot after Harbor version upgrades).

Thanks!

**Comment by ninjadq** [comment]
@cparadal  replication jobs are run by Job service also. you can find replication related job status with job services' metrics

**Comment by cparadal** [comment]
> @cparadal replication jobs are run by Job service also. you can find replication related job status with job services' metrics

Thanks for your reply!

These are the `jobservice` related metrics I can see on Prometheus:

![image](https://user-images.githubusercontent.com/11683485/124611726-02d3b900-de72-11eb-8fd0-4ab2fab76452.png)

I guess I could alert if the below count doesn't increase:
```
harbor_jobservice_task_process_time_seconds_count{status="success",type="SCHEDULER"} 157
```

... even though it applies to all scheduled replications, can't see a way to get metrics for specific ones.

**Comment by reasonerjt** [comment]
@xaleeks Shall we close this one and open new issues, I believe adding/adjusting the metrics for Harbor will be a continuous effort.

**Comment by withlin** [comment]
any update?

**Comment by reasonerjt** [comment]
As per https://github.com/goharbor/harbor/issues/4557#issuecomment-875318639 I'm closing this one.

Please open new issues when you want new metrics to be collected or make adjustment to the existing ones.
