### ISSUE TITLE
[FEATURE] - Choosing multiple projects to replicate in 1 rule

### ISSUE THREAD

**Issue by vielktus** [goharbor/harbor#4583]
Can I choose multiple projects to replicate in 1 rule?

At the moment, I can only choose 1 project per rule to replicate. So if I have many projects, I have to define many rules. This is taking time.

Screenshot:
![image](https://user-images.githubusercontent.com/12691265/38293040-393ab1bc-3810-11e8-8387-1c28c0954357.png)

**Comment by jessehu** [comment]
Currently you can select a single project. We will change 'Source projects' to  'Source project', and discuss how to support multi projects.
/cc @steven-zou @ywk253100

**Comment by steven-zou** [comment]
@vielktus Working on to deliver it in v1.8

**Comment by ywk253100** [comment]
Completed in the master branch, you can try it.
