### ISSUE TITLE
Support for General SSO is needed...

### ISSUE THREAD

**Issue by ArcticSnowman** [goharbor/harbor#4616]
While Harbor has ability to use LDAP and the very specific CloudFoundry/UAA for remote authentication, it is highly desirable that a more general SSO/OAuth framework be added to allow use of different SSO providers. 

We are looking to use Harbor in our company and would like to have it accept our enterprise wide SSO.  (We can use LDAP for now, but we want to as many of our apps to use SSO).

Would also allow use of Google,Github, etc.

**Comment by clouderati** [comment]
Hi @ArcticSnowman – completely agree. This is something we've had our eye on for a while and is on our roadmap of features to implement.

Anyone willing to help implement this feature? Would love some help in this area and we're happy to help as you wade through the codebase.

**Comment by balu7771** [comment]
I am also looking to customize the auth and auth we have in our organization. Is there a easy way to disable all the current auth/auth modes and use our org' auth/auth framework.? Any wiki or pointers please.

**Comment by reasonerjt** [comment]
@balu7771 so far there is no way to do it, in v1.8.0 we plan to support OIDC, so admin can set an OIDC provider and user can be redirect to the endpoint for SSO via oauth flow.

**Comment by reasonerjt** [comment]
closing as this OIDC integration is covered in #6616
