### ISSUE TITLE
Card view - title wraps and overlaps other content, infinite scrolling problemmatic

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#4618]
the card view needs to truncate the title if it wraps more than 2 lines. leaving room for the IP address to not overflow passed the horizontal rule. 
the content (title and description and other content) should left align

also, infinite scrolling doesnt work.  hangs with a indeterminate spinner. 
Can the infinite scrolling not use scroll bars and just use a larger viewport (different from the datagrid view)?

also, the label "Tags" is used twice ... it should be "Images" and "Pulls"

![Screen Shot 2018-04-10 at 11.47.27 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/bf57c347-ecc4-47b7-a5d7-3cc01a7008f8)

![Screen Shot 2018-04-10 at 11.47.16 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/4b769237-ef6a-47d6-9ee0-6243099e5d69)

**Comment by ninjadq** [comment]
Fixed on #4696

**Comment by lweitzman** [comment]
pending-ux-review should be added when its moved into verify stage
