### ISSUE TITLE
New Replication Rule dialog should be wider to accommodate trigger mode (scheduled + weekly)

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#4621]
the New replication rule dialog should be a bit wider so the scheduled + weekly trigger mode fits on one line. also, all drop down menus for under trigger mode show scroll bar and should not (on Safari).

![Screen Shot 2018-04-10 at 1.55.55 PM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/8b6cab5c-6f5d-4dd7-a0cd-ff2ca0218741)

**Comment by steven-zou** [comment]
assigned to @pengpengshui

**Comment by pengpengshui** [comment]
![image](https://user-images.githubusercontent.com/29880301/39693134-950ec77a-5215-11e8-80f6-4a7855fd5026.png)
@lweitzman   I just adjust the layout about 'Trigger Mode' to fit on one line,  It looks like the dialog's width is too larger to unharmonize for other elements.

**Comment by lweitzman** [comment]
@pengpengshui not sure what you're asking. is there an environment where i can check out the latest build?

**Comment by pengpengshui** [comment]
It just a demo, I mean if I put  scheduled + weekly on one line , the dialog is too wider for other inputs

**Comment by pengpengshui** [comment]
![image](https://user-images.githubusercontent.com/29880301/39733931-94e9a372-52a7-11e8-8092-c4a7c6774568.png)
this is the behavior in recent build,  (window+ chrome)， maybe just need adjust the layout in Safari.

**Comment by lweitzman** [comment]
this is the behavior in safari with the latest build.
notice also the menu has a scroll bar.
![screen shot 2018-05-08 at 9 11 35 am](https://user-images.githubusercontent.com/626032/39759171-f3ae7e26-529f-11e8-97c3-924d74d3e076.png)

**Comment by pureshine** [comment]
fixed by pr:#5890
