### ISSUE TITLE
Harbor should consider replace the redis client in Beego

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#4641]
Currently the redis client in beego only support configure 1 server address. Also it has some issue with redis cluster. We should consider to replace this redis client with a more robust one.

**Comment by reasonerjt** [comment]
The impact is that in beego you can't configure to db index other than 0.

**Comment by reasonerjt** [comment]
Move this to 1.7 as we need to verify how external HA redis with Harbor will work with the helm chart.

**Comment by reasonerjt** [comment]
We may explore the possibility to customize the session manager.
We need to determine what scope should be supported.

**Comment by jakirpatel** [comment]
Related #6075 

Not sure if any progress on this.

**Comment by DerrickMartinez** [comment]
Any progress or updates on this?
