### ISSUE TITLE
Label management UI has color picker issues on Mac Chrome

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#4653]
Color picker is not working:
<img width="372" alt="screen shot 2018-04-13 at 15 58 43" src="https://user-images.githubusercontent.com/5753287/38723450-b267c186-3f33-11e8-9d9b-48ed5ffdc0eb.png">

Lable filter is not working:
<img width="368" alt="screen shot 2018-04-13 at 15 58 11" src="https://user-images.githubusercontent.com/5753287/38723452-b421f726-3f33-11e8-9357-9a0480fe2c73.png">

Browser version:
<img width="702" alt="screen shot 2018-04-13 at 16 03 02" src="https://user-images.githubusercontent.com/5753287/38723595-2aafeef2-3f34-11e8-81fd-1a42666fe425.png">

**Comment by reasonerjt** [comment]
A work around is to zoom in/out the browser, and the color will be shown.

**Comment by pengpengshui** [comment]
may be need change the code to disappear the color menu when mouseout the menu.

**Comment by lweitzman** [comment]
also, after selecting a color, the menu doesn’t go away.

**Comment by reasonerjt** [comment]
Let's use #4833 to track the all display issues in color picker.

**Comment by lweitzman** [comment]
on the mac the dropdown still has issues with a border around the white option. also the default (when no color is specified) is white and its presented with no border
![screen shot 2018-05-31 at 10 18 59 am](https://user-images.githubusercontent.com/626032/40788200-7e77a288-64bd-11e8-8daf-1599d601b2c7.png)
