### ISSUE TITLE
Adding project members: unknown who I could add

### ISSUE THREAD

**Issue by bergtwvd** [goharbor/harbor#4732]
As Project admin I can add project members. But the UI does not show me the user accounts available, so I have no way of knowing who I can add.

Thus the UI should offer me a list of users that I can select from.

Harbor version 1.4.0

**Comment by lweitzman** [comment]
this is related to #4364 
redesigned Add New Member dialog
![screen shot 2018-05-10 at 11 45 21 am](https://user-images.githubusercontent.com/626032/39878982-afc3b858-5447-11e8-90ba-43154b0820aa.png)
from https://vmware.invisionapp.com/share/F4GMUV05W8D#/295698160_Groups_-_Project

**Comment by zhoumeina** [comment]
@lweitzman , currently, if user input something in "add user" input, frontend will send a api to get all the members can be added in it. so we don't need to redesign this. Louis. Let's have a talk about this.

**Comment by zhoumeina** [comment]
@lweitzman ,feel free to reopen it if you think reasonable.
