### ISSUE TITLE
Can not automation clean old images and can not setup clean policy?

### ISSUE THREAD

**Issue by jinghuaz** [goharbor/harbor#4753]
now docker images more and more, but i can not automation clean old images and automation GC, we can setup police to do this, crontab or other.

this is very urgent!

**Comment by steven-zou** [comment]
@jinghuaz 

Please refer the issue https://github.com/goharbor/harbor/issues/5420 for tag cleaning.
Please refer epic https://github.com/goharbor/harbor/issues/4949 for online GC


I'll close this issue now.
