### ISSUE TITLE
test connection of remote registries fails

### ISSUE THREAD

**Issue by supereagle** [goharbor/harbor#4761]
#Harbor: v1.4.0

When update the remote registries, test connection of remote registries fails, but replication still can correctly work.
Have to update the password, then the test connection can success.

![image](https://user-images.githubusercontent.com/3390333/39092616-b38e814a-4644-11e8-88ea-fc6a2e42630b.png)

**Comment by reasonerjt** [comment]
If you updated the password then the test connection succeeded, it means your password was incorrect?

**Comment by supereagle** [comment]
I'am sure the password is correct, as replication still can correctly work.
Maybe because the returned password is encrypted, it is not decrypted when used for connection test.

**Comment by supereagle** [comment]
ui.log:
```
Apr 28 07:38:57 172.18.0.1 ui[827]: 2018/04/27 23:38:57 #033[1;34m[router.go:829][D] | GET        | /api/systeminfo                          | 3.50613ms        | match      | /api/systeminfo                          | #033[0m
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018-04-27T23:39:09Z [DEBUG] [security.go:231]: got user information from session
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018-04-27T23:39:09Z [DEBUG] [security.go:240]: using local database project manager
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018-04-27T23:39:09Z [DEBUG] [security.go:242]: creating local database security context...
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018-04-27T23:39:09Z [DEBUG] [tokenauthorizer.go:197]: scopses parsed from request:
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018-04-27T23:39:09Z [ERROR] [target.go:65]: failed to ping target: 401 {"reason":"ReasonRequest","message":"Unauthorized"}
Apr 28 07:39:09 172.18.0.1 ui[827]: 2018/04/27 23:39:09 #033[1;34m[router.go:829][D] | POST       | /api/targets/ping                        | 25.777457ms      | match      | /api/targets/ping                        | #033[0m
```

**Comment by supereagle** [comment]
I have found the root cause: When update the remote registry, the returned password is encrypted, it can not be directly used for ping. 

There is a solution: Only pass the new password in `ping` api when users update the password. When users don't update the password, there is no need to pass it, the backend will use the stored one.

**Comment by ywk253100** [comment]
The password isn't returned by API for security reason.

I still not understand what you mean. Are you using web UI or calling API? Is there any problem that you think is the bug of Harbor?

**Comment by supereagle** [comment]
> The password isn't returned by API for security reason.

Yeah. But will pass the password when test connection.

![image](https://user-images.githubusercontent.com/3390333/39507103-04d06772-4e0f-11e8-9c37-ff6b4c3fe266.png)

> Are you using web UI or calling API?

I meet this problem when use web UI, and this can be reproduced.

**Comment by ywk253100** [comment]
Could you provide the exact version of Harbor? You can find it by clicking the login username->About on the top right of web page.

**Comment by supereagle** [comment]
Harbor v1.4.0

**Comment by clouderati** [comment]
Thanks @supereagle – we'll take a look.
