### ISSUE TITLE
Enhance nightly test cases

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#4785]
1, Add UI checking in read only case.
2, Add UI checking in notary cases.
3, Update the coverage document accordingly.
4, Add test case for https://github.com/vmware/harbor/issues/4795
5, Add test case for https://github.com/vmware/harbor/issues/4801
6, Add test case for https://github.com/vmware/harbor/issues/4804
7, Add test case for https://github.com/vmware/harbor/issues/4819
8, Leverage DB cases with LDAP
9, Add more label test cases
10, Add test case for https://github.com/vmware/harbor/issues/4971

**Comment by wy65701436** [comment]
@sigsbee  could you help to split this task as 2 is hard to track status?

**Comment by wy65701436** [comment]
8,9 was done.

**Comment by reasonerjt** [comment]
@wy65701436  please prioritise and assign to different owners
