### ISSUE TITLE
The severity of Vulnerability in Harbor does not differentiate "High" and "Critical" vuln in Clair.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#4793]
As was raised in #4776 
Harbor now doesn't differentiate "high" and "critical" vuln from Clair. 

This is not consistent with CVSS 3.0 spec:
https://www.first.org/cvss/specification-document

We should consider introduce "critical" level of vuln.

This impacts UI, project policy and Clair utility code.

**Comment by clouderati** [comment]
How much work to introduce the critical level? I suspect adding this to the Clair utility will remain tech debt in perpetuity?

**Comment by reasonerjt** [comment]
@clouderati Introducing the `critical` level should be small for backend and Clair utility, but we need to handle UI and migration carefully.

It is more complicated if we consider VIC.

**Comment by jeffweilee** [comment]
How about directly display both ```CVSS score``` and ```severity``` on UI?

In present situation, severity is the only criteria for user to judge whether the docker image is too risky to deploy. What bothers us is that, **severity high** is so common (many docker image has high severity vulnerability) that it is **not suitable** to be the criteria to prevent docker image from deployed.

By displaying and disclosing CVSS score (via UI and API), deployment security criteria can be more meticulous and clear. Users can also judge by CVSS score on their own.

**Comment by reasonerjt** [comment]
@jeffweilee thanks for the suggestion, without updating the

**Comment by reasonerjt** [comment]
This should be considered as we refactor the scanning framework to support pluggable scanner.

**Comment by prahaladdarkin** [comment]
I have implemented a framework that can be used to:
1.  build pluggable scanner support
2. provide a uniform representation of vulnerabilities in a scanner agnostic way.
The implementation currently works with Anchore, however it would be easy to add support for a new type of scanner. Still under works but the code and project structure are present. I plan to make it public within second or third week of Nov. We can evaluate that for introducing the pluggable scanner in Harbor

**Comment by prahaladdarkin** [comment]
@jeffweilee How would  CVSS score be calculated?

**Comment by reasonerjt** [comment]
@prahaladdarkin thanks for chiming in, could you open another issue or create a PR for proposal in the repo goharbor/community?  As for this issue I'm gonna close it, as we have updated the severity level of policy to "critical, high, medium, low, none"
