### ISSUE TITLE
Installation fails if harbor.cfg has two hostname entries (one commented out)

### ISSUE THREAD

**Issue by rajboruah** [goharbor/harbor#4814]
harbor version: v1.4.0 & v1.3.0
Issue:
harbor.cfg:
..
..
#hostname = reg.mydomain.com
hostname = mydomain.com
..
..

Now run installer:

$sudo ./install.sh
➜ Please set hostname and other necessary attributes in harbor.cfg first. DO NOT use localhost or 127.0.0.1 for hostname, because Harbor needs to be accessed by external clients.
Please set --with-notary if needs enable Notary in Harbor, and set ui_url_protocol/ssl_cert/ssl_cert_key in harbor.cfg bacause notary must run under https.
Please set --with-clair if needs enable Clair in Harbor

Solution:

Remove the commented out hostname above. That is, keep only one entry in harbor.cfg:
..
..
hostname = mydomain.com
..
..

Now, installer will run without any issue.

**Comment by david-cloud** [comment]
thanks

**Comment by wy65701436** [comment]
close it as fixed.
