### ISSUE TITLE
Harbor UI can not correctly display the registry story capacity

### ISSUE THREAD

**Issue by Coyote5** [goharbor/harbor#4837]
I deploy the Harbor on k8s. No matter how much my actual storage is, Harbor UI always displays 10GB. But on VM, it can display the correct value.

**Comment by Coyote5** [comment]
No

**Comment by reasonerjt** [comment]
Please use helm chart to deploy Harbor on k8s.

**Comment by Coyote5** [comment]
@reasonerjt My Harbor has been online. Can I solve this problem by modifying configuration? Thank you.
