### ISSUE TITLE
Investigate "docker-compose down" error in Drone CI

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#4853]
Currently, we found several failures on stop harbor in CI, it needs to investigate the root cause.

One failure log: https://storage.googleapis.com/harbor-ci-logs/integration_logs_4194_8032fde3055a05de959d1654c4d11873853057be.tar.gz

**Comment by reasonerjt** [comment]
The timeout issue seems a problem in docker daemon after long run.
