### ISSUE TITLE
combine tags for same image in repository view

### ISSUE THREAD

**Issue by robkooper** [goharbor/harbor#4868]
A lot of software uses multiple tags per image, for example postgres. If you look at the description page it will list the different tags, but shows them so it is easy to see what tags are pointing to the same image. For example it has right now:
- 10.3, 10, latest
- 10.3-alpine, 10-alpine, alpine
- 9.6.8, 9.6, 9
- 9.6.8-alpine, 9.6-alpine, 9-alpine

This is nice to see since I now know that latest is the same as 10 which is right now at version 10.3. This would be nice to show in the repository view (and would minimize the number of rows). Not sure if harbor already stores the sha for each tag, if that is done it could be used to combine multiple tags into a single row of the repository.

**Comment by jessehu** [comment]
We will add this into our dev plan.

**Comment by robkooper** [comment]
Do I need to do anything to prevent this from being marked as stake?

**Comment by fyqls** [comment]
if i want to delete one tag image , what will happen?  will it delete the image and all tags ?

**Comment by robkooper** [comment]
I imagine it will just delete that tag, but leave all the other tags, same as what would happen when you delete an image in docker but other tags still exist that point to the same layers.

**Comment by knoppiks** [comment]
Hi, I'd like to reopen discussion on this. Has anyone knowledge and time to address the problem or are there any other plans to mitigate the issue?

We currently set up harbor and are moving to from our old registry. The issue of multiple images being deleted if one wants to delete a specific tag just came up. (#6994)

**Comment by xaleeks** [comment]
we're working on a solution for this, please ping me to share requirements and use cases. xalex@vmware.com

**Comment by i5okie** [comment]
Any update on this?

**Comment by xaleeks** [comment]
we will fix this in next 1.11 release, please follow progress on https://github.com/goharbor/harbor/issues/2663.  closing this ticket.
