### ISSUE TITLE
Database migration does not support remote host.

### ISSUE THREAD

**Issue by vasartori** [goharbor/harbor#4878]
When we try use the database migration container we don't find any option to run it on a remote host. If you use a HA setup with a database replication (or a simple remote host) it is a problem.

**Comment by ninjadq** [comment]
Yes, the address in the DB migration container is hardcoded to localhost. You can easily change it by yourself, the template file is [here](https://github.com/vmware/harbor/blob/master/tools/migration/db/alembic.tpl#L33), in your container, there is a config file generated by this template.

**Comment by ninjadq** [comment]
@vasartori sorry for delayed reply, we have huge changes on DB migration. Thank you for your PR, but it already out of date. But we will solve your problem in near future release.

**Comment by vasartori** [comment]
Cool!
On 1.6 the PR time frame still open? Maybe I can fix it using the same thing I do on 1.5. What do you think?

**Comment by steven-zou** [comment]
@vasartori 

Thanks for willing to do contributions to harbor. Welcome! Would you please raise a `proposal` issue to describe what the solution will be? Thanks!

**Comment by vasartori** [comment]
@steven-zou Sure!
Can I use master branch to do it?

**Comment by vasartori** [comment]
The new environment variables are added to turn on remote database migration:

|Environment Variable|Description|Default Value|Required|
|---|---|---|---|
USEREMOTEDB|Trigger to enable remote database migration|false|Yes for this purpose|
MY_DB_HOST|Set the remote mysql server|Empty|Yes|
MY_DB_PORT|Set the remote port of mysql server|3306|No|
PG_DB_HOST|Set the remote postgresql server|Empty|Yes|
PG_DB_PORT|Set the remote port of postgresql server|5432|No|
POSTGRES_USERNAME|The username used to connect on postgres server|postgres|No|
POSTGRES_PASSWORD|The password used to connect on postgres server|If not set, the value of environment variable DB_PWD is used|Yes|

The default behaviour was preserved.
@steven-zou would be nice if you can help on validations.

**Comment by chamhaw** [comment]
> The new environment variables are added to turn on remote database migration:
> 
> Environment Variable	Description	Default Value	Required
> USEREMOTEDB	Trigger to enable remote database migration	false	Yes for this purpose
> MY_DB_HOST	Set the remote mysql server	Empty	Yes
> MY_DB_PORT	Set the remote port of mysql server	3306	No
> PG_DB_HOST	Set the remote postgresql server	Empty	Yes
> PG_DB_PORT	Set the remote port of postgresql server	5432	No
> POSTGRES_USERNAME	The username used to connect on postgres server	postgres	No
> POSTGRES_PASSWORD	The password used to connect on postgres server	If not set, the value of environment variable DB_PWD is used	Yes
> The default behaviour was preserved.
> @steven-zou would be nice if you can help on validations.

Is POSTGRES_USERNAME right?
`sqlalchemy.url = postgresql://$PGSQL_USR:$DB_PWD@$PG_DB_HOST:$PG_DB_PORT/registry`
