### ISSUE TITLE
[HELM] StatefulSet prevent update after version bump

### ISSUE THREAD

**Issue by draeron** [goharbor/harbor#4902]
There is a design flaw in the current helm chart, should you change the chart version, the `volumeClaimTemplates` in the mysql statefulSet (`mysql-ss.yaml`) will have different labels which is not allowed.

This will prevent the deployment upgrade through helm.

Suggestions : 
- move mysql to it's own chart with a fixed version (just like postgresql dependencies)
- or use the `stable/mysql` chart 
- or remove the chart version from the `volumeClaimTemplates`  labels

**Comment by draeron** [comment]
on a sidenote: specifying `mysql.host` (external db) should disable the StatefulSet creation altogether

**Comment by jessehu** [comment]
Thanks @draeron for the valuable suggestions.
For the quick solution, we can "remove the chart version from the volumeClaimTemplates labels", actually remove chart version from labels of all resources.

Agree on "specifying mysql.host (external db) should disable the StatefulSet creation altogether". I will make a PR for it.

**Comment by jessehu** [comment]
@draeron Would you like to submit a PR for the label ralated helm upgrade issue ?

**Comment by reasonerjt** [comment]
Upgrade of helm chart is out of the scope of this release.

**Comment by clouderati** [comment]
Lifecycle management is coming down the pipe, but might be a bit. Contributions welcome!

**Comment by ywk253100** [comment]
Fixed.
