### ISSUE TITLE
failed to initialize the system: Error 1406: Data too long for column 'v' at row 1

### ISSUE THREAD

**Issue by WillSkates** [goharbor/harbor#4926]
**Docker Version**: 18.03.1-ce
**Docker Compose Version**: 1.9.0
**OS/Kernel Version**: Centos7/3.10.0-693.21.1.el7.x86_64

harbor.cfg changes:
1. Set the protocol to https.
2. Set the correct hostname.
3. Changed the path to my TLS certificates.
4. Set the passwords for clair and harbor databases.

I then ran ```./install.sh --with-clair```. Using the off-line installer for v.1.5.0.

Result:
Adminserver fails to start with:
[FATAL] [main.go:46]: failed to initialize the system: Error 1406: Data too long for column 'v' at row 1

**Comment by kumy** [comment]
@WillSkates got it today too. In my case, one of the configuration value was larger than 128 characters https://github.com/vmware/harbor/blob/8f9e2644075744e091b91d7a5fdab73973c28b50/make/photon/db/registry_sqlite.sql#L238-L243

I had to truncate my LDAP_FILTER, it's a problem for us. I think I have to alter the database later to allow longer values. @wy65701436 , what about using a free length filed type such as `TEXT` ?

**Comment by lsolberg** [comment]
This bit me today as well.. The issue was the ldap filter

**Comment by wy65701436** [comment]
https://github.com/goharbor/harbor/pull/5761
