### ISSUE TITLE
Online Garbage Collection

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#4949]
1, Add http server to control registry lifecycle.
2, Add API to start/stop/enable GC for registry.
3, Add periodicity GC job into job service, consider how to show GS logs for users.
4, UI support for GC.
5, Add auto test cases.
6, Document.

**Comment by reasonerjt** [comment]
We don't think we can incorporate this in 1.6 release.
Let's clarify the scope of this story in 1.6 timeframe.

**Comment by reasonerjt** [comment]
In 1.6, we'll make verify E2E via API and remove the API from routers.

**Comment by cd1989** [comment]
After GC, do we need to restart registry ?

**Comment by wy65701436** [comment]
E2E has not ready yet, move it to sprint 45 as 44 is almost on holiday.

**Comment by wy65701436** [comment]
all work done.
