### ISSUE TITLE
[UI] for online GC

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#4956]
1, the UI should give one button to trigger the gc, like "scan now"
2, the UI should give option to set schedule for GC.

**Comment by clouderati** [comment]
Do we have mockups for this @lweitzman?

**Comment by zhoumeina** [comment]
@lweitzman , I did a little bit modification of your mockup design, I think the edit button is far from the schedule input box, I move it close to the select box. Here is the implementation screenshot, feel free to give some comments. This feature is almost done. 
![image](https://user-images.githubusercontent.com/4946616/45726894-eea46b80-bbf3-11e8-8ffa-9b5f6b0c9588.png)
