### ISSUE TITLE
[HELM] Enable custom docker registry custom configuration

### ISSUE THREAD

**Issue by draeron** [goharbor/harbor#4969]
There should be a way to specify the docker registry configuration without modify the helm chart. For example, for settings the registry as readonly or for activating the upload purge.

Chart version : 0.1.2
App version : 1.4.0

Suggestion: adding a `.Values.registry.extraConfigs` field which get inserted in the `registry-cm.yaml`

**Comment by jessehu** [comment]
Good suggestion!
