### ISSUE TITLE
CI check fail if $SKIP_CHECK_MEMBERSHIP is empty

### ISSUE THREAD

**Issue by int32bit** [goharbor/harbor#4973]
4 days ago I  created a PR but CI always built fail https://github.com/vmware/harbor/pull/4921, and the detail log as follows:

```
+ echo int32bit
int32bit

+ echo $SKIP_CHECK_MEMBERSHIP

+ if $SKIP_CHECK_MEMBERSHIP == true; then echo 'check-org-membership step skipped'; else /bin/bash -c '[[ ! $(curl --silent "https://api.github.com/orgs/vmware/members/int32bit?access_token=$GITHUB_AUTOMATION_API_KEY") ]]'; fi
/bin/sh: 23: ==: not found
```
We can sure that `$SKIP_CHECK_MEMBERSHIP` is empty or undefined as  `echo` command output empty in trace log. 

We  can modify  `if` expression to `if [ x$SKIP_CHECK_MEMBERSHIP == xtrue` to avoid this case.
 
https://github.com/vmware/harbor/blob/43a1c2060ff35cf6361b93e8bd3bbd9987e6a190/.drone.yml#L25

**Comment by reasonerjt** [comment]
It's expected behavior, as the CI runs in internal infrastructure, so there's a check added to prevent running malicious code.  We will manually trigger the CI again setting the flag `$SKIP_CHECK_MEMBERSHIP`.

The process is a bit tedious but it is how things work currently...
