### ISSUE TITLE
Investigation on storage usage tracking.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5009]
There has been requirement asking for quota by storage or track freed space after GC.

Before we make commitment in those areas we need a good approach in regards to measuring the space a repo/image takes, taking into account that layers are shared across different repo/images.

More details to be added.

**Comment by akutz** [comment]
Hooza whatsit now?

**Comment by reasonerjt** [comment]
@akutz it's a mistake, sorry.
