### ISSUE TITLE
Support assigning project roles to UAA group.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5027]
When Harbor is configured using UAA as authentication backend, project admin can add a UAA group as a member of a project.

After that if a user is a member of this group, he will have the role permission as the group without having to be added as a user member in the project.

**Comment by renmaosheng** [comment]
@stonezdj  is this still needed or already done? thanks.

**Comment by xaleeks** [comment]
closing this because I recently heard our PCF users are moving away from UAA for managing their users, everything will be manageable by Dex.  Can always re-open if this is not the case.
