### ISSUE TITLE
Add a Project Description field

### ISSUE THREAD

**Issue by dgutierr27** [goharbor/harbor#5037]
This would allow customers to enter important information related to Project creation requests (Requester Name/Team Name, Support Ticket #, Date/Time, etc.)

**Comment by clouderati** [comment]
@dgutierr27 – thanks for opening this issue.

@reasonerjt – can we please scope this? @lweitzman, can you please update our mockups to include a short description for projects and, in the future, folders?

Thanks!

**Comment by lweitzman** [comment]
we already had a description for projects 
https://vmware.invisionapp.com/share/BMFBJ0DGFH6#/273227831_Harbor_-_Projects_-_New 
![screen shot 2018-05-25 at 11 38 12 am](https://user-images.githubusercontent.com/626032/40553312-385d2946-6010-11e8-9343-8a3861eda81c.png)

will make sure its added to folders

**Comment by dgutierr27** [comment]
Is this roadmap, or in which version is this available?  We’re running v1.5.0-rc2-1847e2f7 and don’t have a Description field.

**Comment by lweitzman** [comment]
right, it was in the mockups but hasn't been implemented yet.

**Comment by reasonerjt** [comment]
@dgutierr27 we don't have a eta yet, I'll put this in backlog and prioritize in future planning.

**Comment by clouderati** [comment]
@dgutierr27 – we love contributions if you have the time and willingness. 👍
