### ISSUE TITLE
Deploy when no "latest" tag exists should put up a dialog to choose image

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#5058]
The simple solution to trigger an "add info" event has been done to fix the failure when there is no "latest" tag. but the better solution is to put up a dialog to allow the user to easily select a different image without having to go thru the complexities of the "add info" workflow. 
![screen shot 2018-05-30 at 8 33 33 am](https://user-images.githubusercontent.com/626032/40720659-7449415a-63e5-11e8-89ca-70dfda01b047.png)

Not all columns are necessary if it is too compute intensive to get all the information.
Mockups are here: https://vmware.invisionapp.com/share/ZVF75AZAW#/271907734_Projects_-_Repositories_-_Card_V1-4

**Comment by zhoumeina** [comment]
@lweitzman ， may be I did not quite understand this issue, this should be fixed in Admiral. isn't it?

**Comment by zhoumeina** [comment]
This issue will be tracked with : 
https://github.com/vmware/admiral/issues/289
