### ISSUE TITLE
Deleting repository from harbor registry GUI, does not completely remove repository in registry.

### ISSUE THREAD

**Issue by DavidRodHub** [goharbor/harbor#5061]
From the Harbor removed repo "test-repo"

The repository on the disk still has "test-repo" listed under repositories.
  - /data/registry/v2/repositories/library/test-repo

Ran garbage collect and it does not remove the deleted repo.

**Comment by QuSongtao** [comment]
I got the same problem.
when we deleting the tags from registry GUI, harbor should to delete the relative manifest files and blobs files on the disk, that is we want.

**Comment by wy65701436** [comment]
GC in v1.7.0 could resolve this issue, close it as fix.
