### ISSUE TITLE
Unnecessary warning when image has not been scanned.

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#5077]
I'm not exactly sure why this error message is being displayed but we should avoid a situation where there is no object. Or is this saying there is no image tag? if thats the case then the repo page shouldn't list any images. 
Warning message: "Your request cannot be completed because the object does not exist"

![Untitled 2.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/7e8060fb-2fa8-436e-b0eb-0abde8763959)

**Comment by ywk253100** [comment]
@lweitzman How can we reproduce this error? Or could you provide the env that we can check what happened?

**Comment by steven-zou** [comment]
@ywk253100 

The error will be occurred if the Clair is not installed

**Comment by lweitzman** [comment]
we should disable the scan action if Clair is not installed

**Comment by zhoumeina** [comment]
Please verify it in night environment.

**Comment by clouderati** [comment]
Hi @lweitzman – can you check in the nightly build testbed and let us know if you still run into the issue?

**Comment by zhoumeina** [comment]
Now, scan button is disabled if clair is not installed.
