### ISSUE TITLE
需求：页面增加镜像tag批量管理

### ISSUE THREAD

**Issue by qinwei1314ai** [goharbor/harbor#5086]
遇到问题：
生产中harbor中的镜像个数过多。导致管理镜像tag不方便。有个新需求：harbor中可以指定某个镜像的tag数量，比如设置保留5个tag，每次harbor中就只会保留最新的5个tag，多余的会自动删除；还有基于时间的tag控制，根据每个tag的时间戳，可以删除指定日期之前的镜像tag。这样镜像仓库管理起来比较方便。英文水平有限，只能中文提issues了，见笑了。

**Comment by reasonerjt** [comment]
您好，谢谢提出意见
从您的描述来看，设置规则，定期删除tag应该就可以解决您的问题吧？

**Comment by ywk253100** [comment]
A similar request mentioned in #5085.

**Comment by qinwei1314ai** [comment]
是的，新版本有这个功能了么？我的还是1.2.2

**Comment by reasonerjt** [comment]
Let's track this requirement via #5882
