### ISSUE TITLE
Can create duplicate replication rule

### ISSUE THREAD

**Issue by sigsbee** [goharbor/harbor#5102]
Version v1.5.0-bf6192f3

Can create two same replication rules

steps: create a replication rule (for example: a), then create a new with the same name, then will a hint name exist, then click cancel and click yes to cancel it, create replication rule with the same name again

![replication](https://user-images.githubusercontent.com/23101283/41023907-4724b810-69a0-11e8-92e2-a1084c8f13b6.PNG)

**Comment by steven-zou** [comment]
@ywk253100 

Any constraints at API side?
