### ISSUE TITLE
Actions in user datagrid should use the actions drop down for last 2 actions

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#5105]
the buttons above the users datagrid should be reduced so "Reset password" and "Delete" are put into an "Actions" dropdown. we don't want to have too many button actions above the datagrid.

![Screen Shot 2018-06-06 at 8.26.22 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/cf3c4b3c-82c9-4b43-a033-f0f7d9a4414b)

**Comment by zhoumeina** [comment]
already fixed.
