### ISSUE TITLE
When removing a member a project, use the term "Remove" not "Delete" 

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#5130]
when removing a user from a project don't use the term "Delete" In this dialog its used 3 times.
The title should probably say "Confirm removal of project members"

![Screen Shot 2018-06-12 at 8.35.49 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/7e0669af-742b-44da-a5a0-bbdccb94964d)

**Comment by reasonerjt** [comment]
@zhoumeina should this go into 1.7?
