### ISSUE TITLE
The secret and secret key should be generated automatically in helm chart

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5140]
The `secret` and `secret key` are hardcoded in value.yaml, if users don't modify them by themselves, all Harbor instances deployed from chart will use the same values.

**Comment by reasonerjt** [comment]
Seems to me OK to defer.

**Comment by ywk253100** [comment]
The `secret key` cannot be generated automatically for now, moving it out of 1.7

**Comment by ywk253100** [comment]
The `secret_key` cannot be generated automatically as it is used to encrypt/decrypt the passwords and must keep the same after upgrading.
