### ISSUE TITLE
500 internal error when 'project' is not define during docker pull

### ISSUE THREAD

**Issue by aladjadj** [goharbor/harbor#5143]
Harbor return a HTTP status 500 Internal Server error when we pull an image without 'project' like library
example : myregistry.domain.com/issue_test:latest

Normaly the default project is 'library', the same comportment to tag 'latest'

docker: 17.12.0-ce
docker-compose: 1.21.2
harbor: 1.4

Logs:
user@harbor:/var/log/harbor$ sudo tail -f *.log | grep 'issue_test'
Jun 13 15:41:02 172.20.0.1 ui[30781]: 2018-06-13T13:41:02Z [DEBUG] [token.go:35]: URL for token request: /service/token?account=email%40company.com&scope=repository%3Aissue_test%3Apull&service=harbor-registry
Jun 13 15:41:02 172.20.0.1 ui[30781]: 2018-06-13T13:41:02Z [DEBUG] [creator.go:200]: scopes: [repository:issue_test:pull]
Jun 13 15:41:02 172.20.0.1 ui[30781]: 2018-06-13T13:41:02Z [DEBUG] [authutils.go:47]: scopes: [repository:issue_test:pull]
Jun 13 15:41:02 172.20.0.1 ui[30781]: 2018-06-13T13:41:02Z [DEBUG] [authutils.go:94]: user: email@company.com, access: &{repository  issue_test [pull]}
Jun 13 15:41:02 172.20.0.1 ui[30781]: 2018-06-13T13:41:02Z [ERROR] [token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: issue_test
Jun 13 15:41:02 172.20.0.1 proxy[30781]: 10.3.50.17 - "GET /service/token?account=email%40company.com&scope=repository%3Aissue_test%3Apull&service=harbor-registry HTTP/1.1" 500 0 "-" "docker/18.03.0-ce go/go1.9.4 git-commit/0520e24 kernel/4.13.0-43-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.0-ce \x5C(linux\x5C))" 0.017 0.017 .

**Comment by reasonerjt** [comment]
An improvement is to return `401` rather than `500` in this case.  But I don't think we'll add `library` for your command, because it's added by docker client.

**Comment by aladjadj** [comment]
I'm not sure than 'library' added by docker client because in another docker registry we have image on top of  path ( without library ), and logs proved inverse.

**Comment by reasonerjt** [comment]
@aladjadj 
let me clarify, do you mean on another docker registry you issue 
`docker pull x.x.x.x/image:tag`
and the image `x.x.x.x/library/image:tag` will be pulled?

What registry were you using?  Is it OSS registry?

**Comment by aladjadj** [comment]
With official private docker registry, if we push without library, it stored without library.

But with harbor, the push && pull doesn't work because no 'project' is declared

**Comment by reasonerjt** [comment]
@aladjadj Yes and that's the design ...

**Comment by aladjadj** [comment]
Ok it's actually the design in Harbor, but if we want to match with official dockerhub practice, maybe it's a good idea to implement a default value 'library' if namespace has no project

I will propose PR when i can

`➜ docker pull blabla
Using default tag: latest
Error response from daemon: pull access denied for blabla, repository does not exist or may require 'docker login'
➜ docker pull redis
Using default tag: latest
latest: Pulling from library/redis
be8881be8156: Pull complete 
d6f5ea773ca3: Pull complete 
735cc65c0db4: Pull complete 
ff89c30e4d8c: Pull complete 
59bf782a86b3: Pull complete 
ce8aaa9fe90a: Pull complete 
Digest: sha256:096cff9e6024603decb2915ea3e501c63c5bb241e1b56830a52acfd488873843
Status: Downloaded newer image for redis:latest
`
