### ISSUE TITLE
LDAP 模式下无法删除用户

### ISSUE THREAD

**Issue by shayulei** [goharbor/harbor#5146]
If you are reporting a problem, please make sure the following information are provided:
1) v1.5.0-chart-patch-90c0936f  and k8s 1.10.1
1. 通过LDAP登录后，废用的用户管理员无法删除
2. 建议在项目中显示LDAP的显示名，而不是登录名，更能让人理解。
3.在项目中设置成员时，有下拉列表会更方便。
4. 在LDAP下，用户不能自己修改邮箱地址。

**Comment by stonezdj** [comment]
Will provide an option to clean existing imported user when current auth_mode is not db_auth

**Comment by stonezdj** [comment]
You can docker exec to the DB container to delete these user manually
