### ISSUE TITLE
Publish fresh harbor-py to PyPI

### ISSUE THREAD

**Issue by xkrt** [goharbor/harbor#5148]
[harbor-py on PyPI](https://pypi.org/project/harbor-py/) is very old, "Last released: Jul 25, 2016".
Please, publish fresh version.

**Comment by drduker** [comment]
I agree, please update this!  Either this or update the swagger doc to be compatible with 1.5.0.

**Comment by steven-zou** [comment]
This python client is never supported by official. We're trying to contact the owner and transfer the ownership to the community contributor. We'll provide a link to the project after the ownership transfer.

@wy65701436 Please help to follow up.

**Comment by reasonerjt** [comment]
It will be removed from this repo.

**Comment by reasonerjt** [comment]
Removed in #5865
