### ISSUE TITLE
should give remind info when delete a label which referenced by a filter 

### ISSUE THREAD

**Issue by pengpengshui** [goharbor/harbor#5155]

**Comment by farhaanbukhsh** [comment]
Hey I would love to start contributing to this project how can I start?

**Comment by zhoumeina** [comment]
@farhaanbukhsh , I am very glad if you want to contribute this. I think you need to clone harbor repo. 

run : npm install in harbor/src/ui_ng
run : npm run build
run: npm start
then you can debug it in browser console. If you have any questions, please contact me.I am not sure why I can not assign this to you. However, I can wait for your great pr.

**Comment by farhaanbukhsh** [comment]
Hey @zhoumeina thanks for replying :) I will set it up and get back it you. :)

Also I think you need to add me to the organisation to assign me to the issue.

**Comment by farhaanbukhsh** [comment]
Also how do I reproduce the issue?

**Comment by farhaanbukhsh** [comment]
Hey what is the node version are you guys using? My npm run build is failing with `Can't bind to 'projectId' since it isn't a known property of 'hbr-helm-chart'.`
