### ISSUE TITLE
GDPR and OVA Package

### ISSUE THREAD

**Issue by pculka** [goharbor/harbor#5161]
Hi, on http://ec2-13-58-73-107.us-east-2.compute.amazonaws.com/?v=v1.5.0 you are hosting an OVA link, which gathers personal information. The transfer of that personal data is via unsecured channel.

Should I really, according to EULA on that page, ask VMWare Legal in Palo Alto to address this issue? A bit nonsensical distribution of open source I'd say ...

**Comment by yixingjia** [comment]
@pculka  Hi Peter, Thanks a lot for report your concerns.  We will try to address this issue as soon as we get approved for the certificate.   Meanwhile you can use the standalone version of Harbor if you have concerns on the OVA version. 

Thanks again for using Harbor and welcome more feedbacks in the future.

**Comment by reasonerjt** [comment]
Closing as we've dropped the support of standalone OVA as a deployment approach.
