### ISSUE TITLE
harbor HA: why need to change iptables?

### ISSUE THREAD

**Issue by kulong0105** [goharbor/harbor#5169]
I read the article `Harbor High Availability Guide`, and get the info:

```
11> Change iptables

Important

You need to change 192.168.1.220 to your VIP address before issue the follow command, if you just use http for Harbor, then you don't need run the second command.

#>iptables -t nat -A PREROUTING -p tcp -d 192.168.1.220 --dport 80 -j REDIRECT
#>iptables -t nat -A PREROUTING -p tcp -d 192.168.1.220 --dport 443 -j REDIRECT
```

i cannot understand this rule's meaning, and this way looks be not a common case.

i also google some info, like below:
- https://serverfault.com/questions/179200/difference-beetween-dnat-and-redirect-in-iptables
- https://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/

and check man manual:
```
   REDIRECT
       This  target  is  only valid in the nat table, in the PREROUTING and OUTPUT chains, and user-defined chains which are only called from those chains.  It redirects the packet to the machine itself by
       changing the destination IP to the primary address of the incoming interface (locally-generated packets are mapped to the localhost address, 127.0.0.1 for IPv4 and ::1 for IPv6).

       --to-ports port[-port]
              This specifies a destination port or range of ports to use: without this, the destination port is never altered.  This is only valid if the rule also specifies one of the following protocols:
              tcp, udp, dccp or sctp.

       --random
              If option --random is used then port mapping will be randomized (kernel >= 2.6.22).

       IPv6 support available starting Linux kernels >= 3.7.
```

from my original view, the `REDIRECT` should be used to forward local port, but this article does not use `--to-ports` option,  i cannot understand the purpose, anyone can explain this iptables rule? thanks in advance.

**Comment by steven-zou** [comment]
@yixingjia please help to clarify the concern. Thanks

**Comment by yixingjia** [comment]
@kulong0105 

Hi  Allen,
Thank you for this question. We find that in Ubuntu OS without the above rules, the traffic package will not be able to come back to client.  From the node you can use tcpdump to watch that you did receive the package.

Mean while we are not expert on this network domain, and you are highly appreciated if you can do some investigation on how to make it works without this workaround.  Then we can discuss how to update the document with your experiment result.

Regards,
Yixing.


.

**Comment by kulong0105** [comment]
@yixingjia 

Hi Yixing, 

Thanks for your reply.  you are right, i use tcpdump to capture the package, and find the package cannot be sent to client, unless set the iptables rule.

BTW: this situation not only appear on Ubuntu OS, but also happen on CentOS, i guess this issue should be not related to the kind of OS.

i try to dig the details,  and find this should be relevant to the strategy of load-balancing of keepalived，it uses “DR” as “lb_kind” in this example(https://github.com/vmware/harbor/blob/release-1.5.0/make/ha/sample/active_active/keepalived_active_active.conf)

Maybe use "NAT" as "lb_kind" can avoid to use the iptables rule(http://www.keepalived.org/doc/load_balancing_techniques.html)

i would like to use Nginx/Haproxy  as LoadBalancer, they both have no need to set the iptables rule, and it looks be more general, also easy to configure.

for nginx, the configuration looks like below:
{code}
# cat /etc/nginx/nginx.conf
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
}

stream {
    upstream apiserver {
        server IP1:80 weight=5 max_fails=3 fail_timeout=30s;
        server IP2:80 weight=5 max_fails=3 fail_timeout=30s;
        server IP2:6443 weight=5 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 80;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        proxy_pass apiserver;
    }
}
{code}


for haproxy, the configuration looks like below:
{code}
# cat /etc/haproxy/haproxy.cfg
...
#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main *:80
    acl url_static       path_beg       -i /static /images /javascript /stylesheets
    acl url_static       path_end       -i .jpg .gif .png .css .js

    use_backend static          if url_static
    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------
backend static
    balance     roundrobin
    server      static 127.0.0.1:80 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
    server  app1 IP1:80 check
    server  app2 IP2:80 check
    server  app3 IP3:80 check
{code}

**Comment by yixingjia** [comment]
If we change to NAT it also have other issue and some performance concerns. 

instead of use nginx+ haroxy I would recommend you to use keepalived+haproxy 

Let the keepalived to provide the VIP and haproxy to provide the load balancing. 

So that your lb nodes are also under HA protection. 

Since for your solution, if the nginx turn down, your HA will broken. 

We use Keepalived here to provide both VIP and loadbalance role because it is easy to configure.

**Comment by kulong0105** [comment]
@yixingjia 

I mean keepalived+nginx  or  keepalived + haproxy to implement HA and load balancing
