### ISSUE TITLE
The ingress rule only works in kubernetes with nginx ingress controller

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5189]
The annotation `nginx.ingress.kubernetes.io/rewrite-target` is used in ingress rule of Harbor. 
Target rewriting is not supported by all ingress controllers(such as GCE), and for the controllers that support it the annotation is different: nginx is using `nginx.ingress.kubernetes.io/rewrite-target` but F5 GIG-IP is using `virtual-server.f5.com/rewrite-target-url`.

**Comment by jkroepke** [comment]
Listen the UI on /v2 instead /registryproxy/v2 isn't a option? It would be reduce the complexity from 
 Kubernetes side.

**Comment by reasonerjt** [comment]
It is potentially an option, and we will revisit it.
Current goal is to make helm work with a released version and ensure it passes all the test cases in our jenkins.

**Comment by jkroepke** [comment]
Didn't know that a current needed feature. Since we are not using a nginx controller I would hit this problem now.

An other solution would be to create a separate nginx to container that logic. This can be optional and I would create a pull request for it if its an acceptable solution for you.

**Comment by reasonerjt** [comment]
@jkroepke 
I'd prefer not to introduce extra component, what's your LB?

**Comment by jkroepke** [comment]
HAProxy from Openshift. Technically HAProxy support rewrite / redirect but Openshift has no option to define such properties.

**Comment by jkroepke** [comment]
As you write above there exists a lot of LBs that doesn't support rewriting. There a 2 options:

You implement the rewriting into the UI component which requires a new release or you add a optional component that handle the special rewrite handling.

Helm supports optional dependencies. Standard kubernetes users wouldn't need to use the extra component.

**Comment by reasonerjt** [comment]
@jkroepke Thanks for the analysis, I think you can try to add an optional component to fix your problem and after that, submit a PR if you would like.

**Comment by jkroepke** [comment]
Hopefully its good enough to get upstream ;)

**Comment by ywk253100** [comment]
The `rewrite-target` isn't needed anymore, closing the issue.
