### ISSUE TITLE
Helm: Automatically Roll Deployments When ConfigMaps or Secrets change

### ISSUE THREAD

**Issue by jkroepke** [goharbor/harbor#5193]
Hi,

I learned the helm deployment is currently under heavy development. 

For upcoming release it possible that there are changes to configmaps or secrets. Normally Kubernetes won't detected changes like this so you may need run helm upgrade with `--recreate-pods` or add a hash of the config map as annotations.

See https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change for more informations.

**Comment by jkroepke** [comment]
@reasonerjt What does mean the community tag?

So I'm able to provide PR. But before I want to know if its wanted by the team.

**Comment by clouderati** [comment]
Hi @jkroepke – can you please clarify so that I'm sure I understand? Are you commenting on your desire for our Helm chart automatically roll Harbor if secrets are changed?

**Comment by jkroepke** [comment]
Instead patching own Chart, I always want to improve Charts upstream.

Anyway, its not only for secrets. For example most of your configs based on config maps instead define environment variables inside the deployment. If some of the environment has to be changed for example the MAIL Host on the admin server or the app.conf for the harbor-ui, the related deployment should be trigger a deployment. 

Without this changes inside cm oder secrets are not detected by k8s deployment and I had some manual steps after a helm upgrade which should be avoid.

**Comment by ywk253100** [comment]
@jkroepke Sorry for the late reply. Any interest to contribute this part? We have moved the Harbor chart to a separated repository https://github.com/goharbor/harbor-helm.

**Comment by ywk253100** [comment]
Done https://github.com/goharbor/harbor-helm/pull/96
