### ISSUE TITLE
Docker mirror migration failed

### ISSUE THREAD

**Issue by zhijiansd** [goharbor/harbor#5219]
I upgraded from 1.2 to 1.5, but only the project after the upgrade is completed, the docker image has not been migrated to 1.5, I hope to get help, thank you!

**Comment by ninjadq** [comment]
hi @zhijiansd ,
Can you provide the logs in migrating?

**Comment by zhijiansd** [comment]
@ninjadq ,I'm not sure if this is the case.
# tail -n 5 /var/log/harbor/mysql.log 
Jul  1 13:34:12 172.18.0.1 mysql[69842]: 2018-07-01  5:34:12 140316996990720 [Warning] Aborted connection 1762 to db: 'registry' user: 'root' host: 'harbor-ui.harbor_harbor' (Got timeout reading communication packets)
Jul  1 13:47:38 172.18.0.1 mysql[69842]: 2018-07-01  5:47:38 140316996687616 [Warning] Aborted connection 1793 to db: 'registry' user: 'root' host: 'harbor-ui.harbor_harbor' (Got timeout reading communication packets)
Jul  1 13:47:38 172.18.0.1 mysql[69842]: 2018-07-01  5:47:38 140316996990720 [Warning] Aborted connection 1794 to db: 'registry' user: 'root' host: 'harbor-ui.harbor_harbor' (Got timeout reading communication packets)
Jul  1 20:13:52 172.18.0.1 mysql[69842]: 2018-07-01 12:13:52 140316997596928 [Warning] Aborted connection 2553 to db: 'registry' user: 'root' host: 'harbor-ui.harbor_harbor' (Got timeout reading communication packets)
Jul  1 20:13:52 172.18.0.1 mysql[69842]: 2018-07-01 12:13:52 140316996687616 [Warning] Aborted connection 2554 to db: 'registry' user: 'root' host: 'harbor-ui.harbor_harbor' (Got timeout reading communication packets)
# tail -n 5 /var/log/harbor/notary-db.log 
Jun 30 10:30:36 172.18.0.1 notary-db[30945]: 2018-06-30  2:30:36 140628302792448 [Warning] Aborted connection 9 to db: 'notarysigner' user: 'signer' host: 'notary-signer.harbor_notary-mdb' (Got an error reading communication packets)
Jun 30 10:30:36 172.18.0.1 notary-db[30945]: 2018-06-30  2:30:36 140628302792448 [Warning] Aborted connection 11 to db: 'notarysigner' user: 'signer' host: 'notary-signer.harbor_notary-mdb' (Got an error reading communication packets)
Jun 30 10:30:36 172.18.0.1 notary-db[30945]: 2018-06-30  2:30:36 140628302792448 [Warning] Aborted connection 12 to db: 'notaryserver' user: 'server' host: 'notary-server.harbor_notary-mdb' (Got an error reading communication packets)
Jun 30 10:30:36 172.18.0.1 notary-db[30945]: 2018-06-30  2:30:36 140628302792448 [Warning] Aborted connection 13 to db: 'notaryserver' user: 'server' host: 'notary-server.harbor_notary-mdb' (Got an error reading communication packets)
Jun 30 10:30:37 172.18.0.1 notary-db[30945]: 2018-06-30  2:30:37 140628302792448 [Warning] Aborted connection 15 to db: 'notaryserver' user: 'server' host: 'notary-server.harbor_notary-mdb' (Got an error reading communication packets)

**Comment by reasonerjt** [comment]
@zhijiansd I believe @ninjadq was asking for the `migration log`

Could you provide and do you still seeing problems?

**Comment by zhijiansd** [comment]
@reasonerjt Thank you, I have reinstalled the latest version because I have not been answered for a long time, so I can't get the corresponding log information now.
