### ISSUE TITLE
Push events wont work with custom client

### ISSUE THREAD

**Issue by jkroepke** [goharbor/harbor#5222]
Hi,

i'm trying to interact with custom clients to the harbor registry.

After some debugging I figured out that repositories or clair push events are only triggered if I use the docker-ce client.

On the source code I found that the harbor emits events depends on the User-Agent from the HTTP call.

https://github.com/vmware/harbor/blob/8f9e2644075744e091b91d7a5fdab73973c28b50/src/ui/service/notifications/registry/handler.go#L162

Any reasons why there are such limitations? If yes a blacklist should preffered.

**Comment by reasonerjt** [comment]
I don't think we want a blacklist, instead maybe we can tweak it such that if the request contains certain header we treat it as a regular pull/push action.

**Comment by Delphinator** [comment]
I've just been bitten by this as well. This behavior is very unexpected. After changing the user agent of my custom client to something starting with `docker` push events work as expected and newly created images show up in the UI.

+1 for a blacklist-based approach. Filtering out events generated from internal components / processes results in less surprises.

**Comment by jkroepke** [comment]
Still an issue.

**Comment by clouderati** [comment]
I like @reasonerjt's idea here. Any objections to using a specific header to support this functionality?

Also, any takers on contributing this? :smile: Happy to help walk someone through the process.
