### ISSUE TITLE
Clair fails to fetch debain data.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#5267]
Catched it by nighly test, see the log. 

Could we think about to improve the UX about "Scan on push"? It's confuse user that it doesn't work as clair data is not fully ready. 

Jul  7 08:43:59 172.18.0.1 clair[1466]: {"Event":"could not download Debian's update","Level":"error","Location":"debian.go:68","Time":"2018-07-07 15:43:59.014945","error":"Get https://security-tracker.debian.org/tracker/data/json: dial tcp 128.31.0.67:443: i/o timeout"}
Jul  7 08:43:59 172.18.0.1 clair[1466]: {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:235","Time":"2018-07-07 15:43:59.015022","error":"could not download requested resource","updater name":"debian"}

**Comment by reasonerjt** [comment]
Looks like a intermittent error of debian tracker site.
