### ISSUE TITLE
Harbor OVA signed by invalid cert

### ISSUE THREAD

**Issue by LinAnt** [goharbor/harbor#5276]
The harbor 1.5.0 OVA is packed with an invalid cert. It is not possible to deploy it through vSphere at the moment.

https://www.dropbox.com/s/6vjw6a8d1h1tpq9/Screenshot%202018-07-09%2015.38.08.png?dl=0
https://www.dropbox.com/s/bkkwje8puoisjsj/Screenshot%202018-07-09%2015.40.41.png?dl=0

**Comment by LinAnt** [comment]
Is there a temporary fix for this issue?

**Comment by reasonerjt** [comment]
@LinAnt I'd suggest using the offline installer, instead of the .ova, we are considering to drop the support of .ova

**Comment by kacole2** [comment]
@LinAnt I was able to get the OVA to deploy after downloading the [VMware OVF tool](https://code.vmware.com/tool/ovf/4.1.0)

I removed the cert using the following command and it deployed
```
kendrickc-m01:VMware OVF Tool kendrickc$ ./ovftool --skipManifestCheck /Users/kendrickc/Desktop/harbor-v1.5.0.ova /Users/kendrickc/Desktop/harbor-v1.5.0-nocert.ova
Opening OVA source: /Users/kendrickc/Desktop/harbor-v1.5.0.ova
The manifest does not validate
Opening OVA target: /Users/kendrickc/Desktop/harbor-v1.5.0-nocert.ova
Writing OVA package: /Users/kendrickc/Desktop/harbor-v1.5.0-nocert.ova
Transfer Completed
Completed successfully
```

**Comment by LinAnt** [comment]
I just installed it like reasonerjt suggested, thank you for the information. It might come in handy in the future 👍
