### ISSUE TITLE
HA documentation causes confusing

### ISSUE THREAD

**Issue by mailzyok** [goharbor/harbor#5279]
Hi, 

In HA document, https://github.com/vmware/harbor/blob/master/docs/high_availability_installation_guide.md,
MariaDB is used as harbor database,

But in readme.md and also the helm charts, Mysql is used.

Does it mean, if harbor to support HA, mariaDB need to be used, not Mysql DB?

Thanks,
Darcy

**Comment by clouderati** [comment]
The HA guide needs to be updated; as of the latest release we're solely leveraging PostgreSQL.
