### ISSUE TITLE
Why is this pending state when I delete the image?

### ISSUE THREAD

**Issue by youngwah** [goharbor/harbor#5299]
![1531387930 1](https://user-images.githubusercontent.com/18633334/42625462-6887b2c0-85fa-11e8-88ec-05b7853b0b77.png)

Why is this pending state when I delete the image? 
I can delete it, is this status displayed correctly?

**Comment by youngwah** [comment]
os: CentOS 7.3
harbor version：v1.5.1-8bbd84ea

`Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018-07-15T07:14:12Z [INFO] delete tag: go/tomcat:latest
Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018-07-15T07:14:12Z [INFO] Handle notification with topic 'OnDeletion': notification.OnDeletionNotification{Image:"go/tomcat:latest"}
Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |     172.18.0.9|#033[42m 200 #033[0m|  27.558699ms|   match|#033[46m POST    #033[0m /service/notifications   r:/service/
notifications#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m| 101.057459ms|   match|#033[41m DELETE  #033[0m /api/repositories/go/tomcat   r:/api
/repositories/*#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m|   3.954116ms|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositor
ies#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m|   3.115085ms|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositor
ies#033[0mJul 15 15:14:16 172.18.0.1 ui[4546]: 2018/07/15 07:14:16 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.228737ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:14:28 172.18.0.1 ui[4546]: 2018/07/15 07:14:28 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   6.982821ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jul 15 15:14:46 172.18.0.1 ui[4546]: 2018/07/15 07:14:46 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.250631ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:14:58 172.18.0.1 ui[4546]: 2018/07/15 07:14:58 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.867251ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jul 15 15:15:16 172.18.0.1 ui[4546]: 2018/07/15 07:15:16 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    2.68916ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:15:28 172.18.0.1 ui[4546]: 2018/07/15 07:15:28 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.952554ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jul 15 15:15:46 172.18.0.1 ui[4546]: 2018/07/15 07:15:46 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.444737ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:15:58 172.18.0.1 ui[4546]: 2018/07/15 07:15:58 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.871133ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jul 15 15:16:16 172.18.0.1 ui[4546]: 2018/07/15 07:16:16 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.875192ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:16:29 172.18.0.1 ui[4546]: 2018/07/15 07:16:29 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.255502ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
`
registry.log
`Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "HEAD /v2/go/tomcat/manifests/latest HTTP/1.1" 200 2836 "" "Go-http-client/1.1"
Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.348291854Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=17fd102d-c976-4939-9a34-
787ea402f150 http.request.method=DELETE http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/manifests/sha256:1c39cc2e882b41691998886186bb932f7abcfc9a6e9526f4d04e7d8332289174" http.request.useragent="Go-http-client/1.1" http.response.duration=3.257592ms http.response.status=202 http.response.written=0 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "DELETE /v2/go/tomcat/manifests/sha256:1c39cc2e882b41691998886186bb932f7abcfc9a6e9526f4d04e7d8332289174 HTTP/1.1" 202 0 "" 
"Go-http-client/1.1"Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.352409879Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=e515259e-77a6-4f2d-bbb8-
56265774388f http.request.method=GET http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/tags/list" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.711635ms http.response.status=200 http.response.written=33 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "GET /v2/go/tomcat/tags/list HTTP/1.1" 200 33 "" "Go-http-client/1.1"
`
[root@Server-0hmnyy harbor]# docker-compose ps
       Name                     Command                  State                                    Ports                              
-------------------------------------------------------------------------------------------------------------------------------------
harbor-adminserver   /harbor/start.sh                 Up (healthy)                                                                   
harbor-db            /usr/local/bin/docker-entr ...   Up (healthy)   3306/tcp                                                        
harbor-jobservice    /harbor/start.sh                 Up                                                                             
harbor-log           /bin/sh -c /usr/local/bin/ ...   Up (healthy)   127.0.0.1:1514->10514/tcp                                       
harbor-ui            /harbor/start.sh                 Up (healthy)                                                                   
nginx                nginx -g daemon off;             Up (healthy)   0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp, 0.0.0.0:80->80/tcp
redis                docker-entrypoint.sh redis ...   Up             6379/tcp                                                        
registry             /entrypoint.sh serve /etc/ ...   Up (healthy)   5000/tcp   
registry             /entrypoint.sh serve /etc/ ...   Up (healthy)   5000/tcp

**Comment by youngwah** [comment]
harver version: v1.5.1-8bbd84ea

ui.log
```
Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018-07-15T07:14:12Z [INFO] delete tag: go/tomcat:latest
Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018-07-15T07:14:12Z [INFO] Handle notification with topic 'OnDeletion': notification.OnDeletionNotification{Image:"go/tomcat:latest"}
Jul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |     172.18.0.9|#033[42m 200 #033[0m|  27.558699ms|   match|#033[46m POST    #033[0m /service/notifications   r:/service/
notifications#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m| 101.057459ms|   match|#033[41m DELETE  #033[0m /api/repositories/go/tomcat   r:/api
/repositories/*#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m|   3.954116ms|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositor
ies#033[0mJul 15 15:14:12 172.18.0.1 ui[4546]: 2018/07/15 07:14:12 #033[1;44m[D] [server.go:2619] |   192.168.1.53|#033[42m 200 #033[0m|   3.115085ms|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositor
ies#033[0mJul 15 15:14:16 172.18.0.1 ui[4546]: 2018/07/15 07:14:16 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.228737ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Jul 15 15:14:28 172.18.0.1 ui[4546]: 2018/07/15 07:14:28 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   6.982821ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jul 15 15:14:46 172.18.0.1 ui[4546]: 2018/07/15 07:14:46 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.250631ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
```

registry.log

```
Jul 15 15:14:09 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:09 +0000] "GET /v2/go/tomcat/blobs/sha256:2d084b11164d1d05bfe0a28afc966153e43efa6760dd2b4707b5764395def4f7 HTTP/1.1" 200 16049 "" "Go
-http-client/1.1"Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.313165147Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=6d572938-a213-4ae5-b271-
548916b6a8b0 http.request.method=GET http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/tags/list" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.902137ms http.response.status=200 http.response.written=39 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "GET /v2/go/tomcat/tags/list HTTP/1.1" 200 39 "" "Go-http-client/1.1"
Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.31964847Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=f06e2105-4bb2-4a35-83ad-e
75d77d30e8b http.request.method=HEAD http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/manifests/latest" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=5.123149ms http.response.status=200 http.response.written=2836 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "HEAD /v2/go/tomcat/manifests/latest HTTP/1.1" 200 2836 "" "Go-http-client/1.1"
Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.348291854Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=17fd102d-c976-4939-9a34-
787ea402f150 http.request.method=DELETE http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/manifests/sha256:1c39cc2e882b41691998886186bb932f7abcfc9a6e9526f4d04e7d8332289174" http.request.useragent="Go-http-client/1.1" http.response.duration=3.257592ms http.response.status=202 http.response.written=0 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "DELETE /v2/go/tomcat/manifests/sha256:1c39cc2e882b41691998886186bb932f7abcfc9a6e9526f4d04e7d8332289174 HTTP/1.1" 202 0 "" 
"Go-http-client/1.1"Jul 15 15:14:12 172.18.0.1 registry[4546]: time="2018-07-15T07:14:12.352409879Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=e515259e-77a6-4f2d-bbb8-
56265774388f http.request.method=GET http.request.remoteaddr="172.18.0.7:36526" http.request.uri="/v2/go/tomcat/tags/list" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.711635ms http.response.status=200 http.response.written=33 instance.id=b811ad7f-b51e-4eef-ae32-89d68ca36b93 service=registry version=v2.6.2 Jul 15 15:14:12 172.18.0.1 registry[4546]: 172.18.0.7 - - [15/Jul/2018:07:14:12 +0000] "GET /v2/go/tomcat/tags/list HTTP/1.1" 200 33 "" "Go-http-client/1.1"
Jul 15 15:14:28 172.18.0.1 registry[4546]: 127.0.0.1 - - [15/Jul/2018:07:14:28 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
```

```
[root@Server-0hmnyy harbor]# docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                    PORTS                                                              NAMES
94f1aedd6233        vmware/harbor-jobservice:v1.5.1        "/harbor/start.sh"       34 minutes ago      Up 30 minutes                                                                                harbor-jobser
vicea1c46700bb27        vmware/nginx-photon:v1.5.1             "nginx -g 'daemon of…"   34 minutes ago      Up 31 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
2108118dc133        vmware/harbor-ui:v1.5.1                "/harbor/start.sh"       34 minutes ago      Up 30 minutes (healthy)                                                                      harbor-ui
09f8d0fe6682        vmware/clair-photon:v2.0.1-v1.5.1      "/docker-entrypoint.…"   34 minutes ago      Up 34 minutes (healthy)   6060-6061/tcp                                                      clair
88f9d866728f        vmware/registry-photon:v2.6.2-v1.5.1   "/entrypoint.sh serv…"   34 minutes ago      Up 30 minutes (healthy)   5000/tcp                                                           registry
6773c294ac7b        vmware/harbor-db:v1.5.1                "/usr/local/bin/dock…"   34 minutes ago      Up 31 minutes (healthy)   3306/tcp                                                           harbor-db
3cbcdbbeb656        vmware/redis-photon:v1.5.1             "docker-entrypoint.s…"   34 minutes ago      Up 31 minutes             6379/tcp                                                           redis
c6799d226236        vmware/harbor-adminserver:v1.5.1       "/harbor/start.sh"       34 minutes ago      Up 30 minutes (healthy)                                                                      harbor-admins
erver9165ecdc075d        vmware/postgresql-photon:v1.5.1        "/entrypoint.sh post…"   34 minutes ago      Up 34 minutes (healthy)   5432/tcp                                                           clair-db
05b8799bec60        vmware/harbor-log:v1.5.1               "/bin/sh -c /usr/loc…"   34 minutes ago      Up 30 minutes (healthy)   127.0.0.1:1514->10514/tcp                                          harbor-log
```
thanks

**Comment by ywk253100** [comment]
@youngwah Yes, it's correct and by design in v1.5.1.
