### ISSUE TITLE
how to upgrade v1.1.2 to v1.5.1?

### ISSUE THREAD

**Issue by MQluna** [goharbor/harbor#5352]
Harbor upgrade and database migration guide says From v1.5.0 on, the migration tool add support for the harbor.cfg migration, which supports upgrade from v1.2.x, v1.3.x and v1.4.x.

Can I upgrade harbor from v1.1.2 to v1.2 and then from v1.2 to v1.5.1?

**Comment by ywk253100** [comment]
Yes, you can upgrade in that way.

**Comment by MQimp** [comment]
@ywk253100 
thx~ but how to upgrade v1.1.2 to v1.2.0?/
i can not found harnbor-migratpr:v1.2.0
