### ISSUE TITLE
Dex for authentication

### ISSUE THREAD

**Issue by helgi** [goharbor/harbor#5358]
Would be interesting if http://github.com/coreos/dex could be used for authentication to offer more ways to source authentication information from. LDAP, OIDC, Github, OAuth2 and more 

It's been getting some more traction lately, for example with https://github.com/concourse/concourse/

**Comment by silenceshell** [comment]
I have implement this feature lately. App can call harbor API with Authorization Header like "Authorization: Bearer $token", and harbor will call dex api to verify this token.
It works like k8s apiserver way.
Does anyone still need this? Maybe I coud make a PR.

**Comment by reasonerjt** [comment]
@silenceshell Could you consider write a proposal by opening a PR to 
https://github.com/goharbor/community ?

**Comment by silenceshell** [comment]
ok, I will write it these days.

**Comment by silenceshell** [comment]
@hbajaj2 Code is [here](https://github.com/silenceshell/harbor/commit/75dc9a93f26a82eaa70f00e1d357ca6483e7c927), it is based on the lastest master (maybe not the newest).

`dex.example.com`  is the hostname of dex server, shoule be set according to your env.

Harbor use OIDC authentication as [Kubernetes authentication through dex](https://github.com/dexidp/dex/blob/master/Documentation/kubernetes.md), you could set up by referencing to this doc, it needs an example-app to generate token.

**Comment by jmlcv** [comment]
> I have implement this feature lately. App can call harbor API with Authorization Header like "Authorization: Bearer $token", and harbor will call dex api to verify this token.
> It works like k8s apiserver way.
> Does anyone still need this? Maybe I coud make a PR.

Just found it about this issue. I am interested in this feature. Hope it makes to Harbor 1.8!

**Comment by reasonerjt** [comment]
I'll dup it to #6616, when it's done Harbor will support OIDC authentication and `dex` will be supported as an OIDC provider.
