### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by guoyujian111** [goharbor/harbor#5365]
os:Centos7.5
harbor:1.5.0
docker:18.03
I'm want to login the harbor registry with http, but it's Error response from daemon: Get https://harbor.dksou.com:5000/v2/: dial tcp 192.168.10.29:5000: getsockopt: connection refused

**Comment by stonezdj** [comment]
What is the hostname in your harbor.cfg, if you need to use harbor.dksou.com to login, you should generate cert and configure hostname=harbor.dksou.com
