### ISSUE TITLE
如何修改registry的默认的存储位置

### ISSUE THREAD

**Issue by guoyujian111** [goharbor/harbor#5375]
harbor安装完成后，默认的registry路径为/data/registry,但是我的主机/data空间不大，想修改/home/harbor/data目录，查询相关文档后修改了docker-compose.yml,但是没有生效，打开页面还是显示容量20G，请问是什么原因，还需要修改哪些配置

**Comment by wy65701436** [comment]
For the registry storage, please update the path at https://github.com/goharbor/harbor/blob/release-1.5.0/make/docker-compose.tpl#L19, replace /data/registry with your path.

For the storage usage: https://github.com/goharbor/harbor/blob/release-1.5.0/make/docker-compose.tpl#L60, replace your path with /data, the adminserver only can show the usage of /data, this is an design limitation.
