### ISSUE TITLE
Getting error while deploying the latest Bosh harbor release and see below 

### ISSUE THREAD

**Issue by goprasad** [goharbor/harbor#5388]
21:24:43 | Updating instance harbor-app: harbor-app/54ef00a2-4f54-49e2-9e61-77bbd0940e44 (0) (canary) (00:05:07)
L Error: Action Failed get_task: Task 2b5c7659-8861-4f55-4fff-6886ae81fda6 result: 2 of 2 pre-start scripts failed. Failed Jobs: enable-bosh-dns, harbor.

21:29:50 | Error: Action Failed get_task: Task 2b5c7659-8861-4f55-4fff-6886ae81fda6 result: 2 of 2 pre-start scripts failed. Failed Jobs: enable-bosh-dns, harbor.

Started Tue Jul 24 21:15:24 UTC 2018
Finished Tue Jul 24 21:29:50 UTC 2018
Duration 00:14:26

Task 35 error

Updating deployment:
Expected task '35' to succeed but state is 'error'

Exit code 1

**Comment by reasonerjt** [comment]
Please package the log under `/var/vcap/logs/harbor` and upload to the issue.

**Comment by goprasad** [comment]
Appreciate your help in this regards and providing you the request info below.
@reasonerjt  @stonezdj 
Stemcell version:
    bosh-vsphere-esxi-ubuntu-trusty-go_agent  3468.54*  ubuntu-trusty

Release version:
   harbor-container-registry  1.5.1-build.7*  non-git

logs:
 logs are packaged from this folder '/var/vcap/sys/log' and attached the logs.tar.gz
manifest used:
       harbor.yml.txt file attached

[logs.tar.gz](https://github.com/vmware/harbor/files/2232467/logs.tar.gz)

[harbor.yml.txt](https://github.com/vmware/harbor/files/2232472/harbor.yml.txt)

**Comment by clouderati** [comment]
Thanks @goprasad – we'll take a look at the logs and get back to you soon!

**Comment by reasonerjt** [comment]
We're investigating.
Let's keep this issue open, we'll provide update in this one.

**Comment by stonezdj** [comment]
Original issue closed
