### ISSUE TITLE
Harbor and LDAP integration

### ISSUE THREAD

**Issue by mramanathan** [goharbor/harbor#5404]
Am not reporting any issue but seeking inputs on configuring LDAP in Harbor (fresh setup).

1) Frankly, there are too many related fields in `harbor.cfg` that's baffling me - not sure what is must (with the exception of ldap url) and what can be left as is ?

2) I will be installing binding Harbor v1.5.0 with enterprise AD -- so, in this scenario, what fields / values are mandatory and what can be skipped ?

**Comment by mramanathan** [comment]
So, I decided to bite the bullet and setup LDAP. Changed two parameters in `harbor.cfg` and followed the steps to restart containers after re-running `prepare`.

Initial observations are:

1. I cannot use AD login creds to access Harbor.

2. I can use default id and password to access Harbor.

3. In the config section, I see `Auth Mode` is set to `Database` and that field is greyed out.

Any pointers are welcome.

**Comment by stonezdj** [comment]
The problem might be caused by the previous installed harbor, the database data file may store in /data/database, you should clean up this directory before reinstall. or you can not change db_auth to ldap_auth.

**Comment by mramanathan** [comment]
@stonezdj It wasn't previous installation of Harbor that caused the problem. I was missing correct LDAP settings, like, OU details, LDAP search username, et al. With the help of local IT folks, I was able to successfully integrate Harbor with enterprise LDAP.

**Comment by shapeofarchitect** [comment]
> @stonezdj It wasn't previous installation of Harbor that caused the problem. I was missing correct LDAP settings, like, OU details, LDAP search username, et al. With the help of local IT folks, I was able to successfully integrate Harbor with enterprise LDAP.

I have done the same details and I verified the ldap connection , but I am still not able to login using my ldap credentials to harbor UI. what am I missing here ?
