### ISSUE TITLE
TLS handshake timeout when trying to push to Harbor Registry

### ISSUE THREAD

**Issue by cwelde** [goharbor/harbor#5405]
[info.zip](https://github.com/vmware/harbor/files/2232771/info.zip)

Hi, I'm getting this error when I try to push an image (in this case, the hello-world image) to a Harbor Registry I set up, self signed. 
docker push hello-world 10.228.65.138/demo/hello-world
The error: Get https://10.228.65.138/v2/: net/http: TLS handshake timeout
I'm able to pull images from DockerHub. I'm able to curl/wget the docker webpage. I can basically do everything except push to my Harbor Registry.

Client:
 Version: 17.09.0-ce
 OS/Arch: linux/amd64

Server:
 Version 17.09.0-ce
OS/Arch: linux/amd64

i'm at a loss for what the problem could be. Googling this issue doesn't lead to much information
harbor.cfg and logs located in the zip

**Comment by reasonerjt** [comment]
Do you keep seeing this issue?  
could you docker login?

**Comment by cwelde** [comment]
Hi, yes I still have this issue. I can’t login via the command docker login 10.228.65.138, but docker login works.

**Comment by reasonerjt** [comment]
So it seems to me there's some networking issue between your docker host and 10.228.65.138

**Comment by cwelde** [comment]
Hey there, sorry for the late response - turns out this was a corp network issue and not something with Harbor. Thanks for all your help.
