### ISSUE TITLE
Harbor Ha Question

### ISSUE THREAD

**Issue by wekube** [goharbor/harbor#5406]
since harbor-ui & harbor-adminserver &harbor-jobserver & docker-registry can be stateless, could we use this method:
multi lb ---> multi ui ---> multi adminserver ---> multi registry

instead of:
multi lb ----> multi harbor ---> multi registry

can or cannot? is there any problem i shoud take care?
thanks for explaining.

**Comment by reasonerjt** [comment]
Yes we are trying to do this way:
 multi ui ---> multi adminserver ---> multi registry

in helm chart deployment.
