### ISSUE TITLE
ldap integretion for another TYPE ldap usage.

### ISSUE THREAD

**Issue by wekube** [goharbor/harbor#5407]
as config and code show, now harbor use memberOf to find groups that user belong to.
BUT in my ldap env, we use another method to mapping user and group using group attr memberUid.
is there any plan to support it ?
thanks.

**Comment by clouderati** [comment]
Hi @wekube – thanks for raising this issue. Does `memberUid` return a list of groups that the member is part of like `memberOf` does?

**Comment by wsbmilk** [comment]
use search filter to determine, for example: &((group=posixGroup)(memberUid=%s)), %s is the placeholder for username

**Comment by XANi** [comment]
@wsbmilk could you elaborate how the rest of the settings should look like for it to work ?
![image](https://github.com/goharbor/harbor/assets/147394/bb6ab3b1-f273-43fc-8a82-ff4784d62ae5)
it just doesn't seem to want to get any groups at all

we just have a bunch of `posixGroup` where `memberUid` points to user's `uid`/login
