### ISSUE TITLE
Wrong arm64 image of vmware/harbor-ui on dockerhub

### ISSUE THREAD

**Issue by liangchenye** [goharbor/harbor#5418]
Dear maintainer,

The 'vmware/harbor-ui' image was pulled successfully on my arm64 system.
But when I start to run it, I got an error message from docker:
`exec user process caused "exec format error"`. 
The reason is this image was built on x86.

If there was no arm64 version on dockerhub, there will be an error  like this:
`no matching manifest for linux/arm64 in the manifest list entries`.
So I wondering if any maintainer pushed the x86 image from arm64 by mistake.

**Comment by carlosedp** [comment]
@liangchenye The image is not a manifest list, is a image. This is why the ARM platform pulled it without complaining:

```
Image: vmware/harbor-ui
 * Manifest List: No
 * Supports: amd64/linux
```
 I will try to build Harbor images on ARM64.

**Comment by zhanglu0704** [comment]
@liangchenye I have the same needs for a few days ago.Then, I build the images and offline packages to install docker harbor in ARM64.I used the code from https://github.com/goharbor/harbor, and made some modify. You can done load the image from my docker Hub:https://hub.docker.com/r/frankzhang0803/registry-photon/

**Comment by carlosedp** [comment]
Hi @zhanglu0704 , would you share the modifications and files you used to build it?

Thanks!

**Comment by zhanglu0704** [comment]
With pleasure @carlosedp I uploaded the code to the GitHub 
 https://github.com/zhanglu0704/harbor-arm64/tree/develop. Actually, I didn't do anything, because I just used the docker image of arm64 to build on the hardware of the ARM64 architecture. I also got a lot of help in your article. 
Thanks to you too.

**Comment by zhanglu0704** [comment]
@carlosedp By the way, the docker image photon supports arm64 at 3.0 after,So I modified the all Dockerfiles "From photon:2.0" to"From photon:3.0",and modified the  "BUILDBIN=ture" in the main Makefile for building registry binary.
