### ISSUE TITLE
删除一个tag整个镜像所有tag都被删除了，/api/repositories/library/alpine/tags/v1

### ISSUE THREAD

**Issue by forging2012** [goharbor/harbor#5421]
URL：/api/repositories/library/alpine/tags/v1

harbor 1.5.0

curl 'https://192.168.2.204/api/repositories/library/alpine/tags/v1' -X DELETE -H 'Pragma: no-cache' -H 'Origin: https://192.168.2.204' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,fy;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: https://192.168.2.204/harbor/projects/1/repositories/library%2Falpine' -H 'Cookie: rem-username=admin; beegosessionID=8f92939d02d6b2cd7e11371ec90b01a8' -H 'Connection: keep-alive' -H 'Content-Length: 0' --compressed --insecure

**Comment by forging2012** [comment]
相同内容的镜像，不同tag，如果一个被删除，其他的tag也会被删除

**Comment by reasonerjt** [comment]
This is a limitation as we'll call registry's API to delete tag via sha256, and identical images will have identical sha256

**Comment by forging2012** [comment]
Look like this case:
I tag the latest images : latest and  v1.
When I delete latest tag , The v1 images also was deleted.
This is will be a inconvenience or misunderstand.

**Comment by xaleeks** [comment]
fyi, we are fixing this on https://github.com/goharbor/harbor/issues/2663 @forging2012
