### ISSUE TITLE
Unable to scan image on push, logging pg relation "keyvalue" does not exist

### ISSUE THREAD

**Issue by francotseng** [goharbor/harbor#5451]
I deploy harbor with clair and enable "Automatically scan images on push" option on my project's configuraion. When I push a image to the registry project, it's ```Vulnerability``` property is ```Not Scanned```, instead of ```Queued```. Harbor UI's log ```/var/log/harbor/ui.log``` reports:
```
Jul 31 18:49:07 172.18.0.1 ui[8651]: 2018-07-31T10:49:07Z [DEBUG] [handler.go:119]: the on push topic for resource scm/nginx:1.13.5 published
Jul 31 18:49:07 172.18.0.1 ui[8651]: 2018-07-31T10:49:07Z [DEBUG] [on_push_handler.go:67]: no replication should be triggered for resource scm/nginx:1.13.5, operation transfer, skip
Jul 31 18:49:07 172.18.0.1 ui[8651]: 2018-07-31T10:49:07Z [INFO] Handle notification with topic 'OnPush': notification.OnPushNotification{Image:"scm/nginx:1.13.5"}
Jul 31 18:49:07 172.18.0.1 ui[8651]: 2018-07-31T10:49:07Z [DEBUG] [handler.go:100]: Add repository scm/nginx into DB.
Jul 31 18:49:07 172.18.0.1 ui[8651]: 2018/07/31 10:49:07 #033[1;44m[D] [server.go:2619] |  10.204.94.181|#033[42m 201 #033[0m|  53.839805ms|   match|#033[43m PUT     #033[0m /v2/scm/nginx/manifests/1.13.5   r:/registryproxy/*#033[0m
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [security.go:286]: user information is nil
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [security.go:300]: using local database project manager
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [security.go:302]: creating local database security context...
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [interceptors.go:120]: in url handler, path: /registryproxy/v2/zuche/gpsweb/manifests/0.1
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [tokenauthorizer.go:197]: scopses parsed from request: repository:zuche/gpsweb:pull
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [transport.go:51]: 404 | HEAD http://registry:5000/v2/zuche/gpsweb/manifests/0.1
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018-07-31T10:49:13Z [DEBUG] [interceptors.go:150]: image info of the request: proxy.imageInfo{repository:"zuche/gpsweb", reference:"0.1", projectName:"zuche", digest:""}
Jul 31 18:49:13 172.18.0.1 ui[8651]: 2018/07/31 10:49:13 #033[1;44m[D] [server.go:2619] |  10.204.94.182|#033[43m 401 #033[0m|  41.737022ms|   match|#033[44m GET     #033[0m /v2/zuche/gpsweb/manifests/0.1   r:/registryproxy/*#033[0m
Jul 31 18:49:19 172.18.0.1 ui[8651]: 2018-07-31T10:49:19Z [DEBUG] [security.go:231]: got user information from session
Jul 31 18:49:19 172.18.0.1 ui[8651]: 2018-07-31T10:49:19Z [DEBUG] [security.go:240]: using local database project manager
Jul 31 18:49:19 172.18.0.1 ui[8651]: 2018-07-31T10:49:19Z [DEBUG] [security.go:242]: creating local database security context...
Jul 31 18:49:19 172.18.0.1 ui[8651]: 2018-07-31T10:49:19Z [ERROR] [systeminfo.go:209]: Failed to get last update from Clair DB, error: pq: relation "keyvalue" does not exist
```
I dug into the source code and found the error is logged at [getClairVulnStatus](https://github.com/vmware/harbor/blob/d557ec89d70d54ead5f9be89b005062447cce62e/src/ui/api/systeminfo.go#L211) and arose at [GetLastUpdate](https://github.com/vmware/harbor/blob/d557ec89d70d54ead5f9be89b005062447cce62e/src/common/dao/clair/base.go#L53). This sql causes PostgreSQL error:
```
num, err := GetOrmer().Raw("SELECT value from keyvalue where key=?", updaterLast).ValuesFlat(&list)
```
The error shows that table "keyvalue" does not exist, however, it does exist:
```
# psql -U registry -W        
Password for user registry: 
psql (10.4, server 9.6.9)
Type "help" for help.

registry=> \dt
                        List of relations
 Schema |                 Name                 | Type  |  Owner   
--------+--------------------------------------+-------+----------
 public | feature                              | table | registry
 public | featureversion                       | table | registry
 public | keyvalue                             | table | registry
 public | layer                                | table | registry
 public | layer_diff_featureversion            | table | registry
 public | lock                                 | table | registry
 public | namespace                            | table | registry
 public | schema_migrations                    | table | registry
 public | vulnerability                        | table | registry
 public | vulnerability_affects_featureversion | table | registry
 public | vulnerability_fixedin_feature        | table | registry
 public | vulnerability_notification           | table | registry
(12 rows)

registry=> SELECT value from keyvalue where key='updater/last';
   value    
------------
 1533021722
(1 row)
```
I can also get the correct result in a test code which calling the [GetLastUpdate](https://github.com/vmware/harbor/blob/d557ec89d70d54ead5f9be89b005062447cce62e/src/common/dao/clair/base.go#L53) function. It's really annoying, why harbor can't find the "keyvalue" table?

**Comment by steven-zou** [comment]
@reasonerjt 

  Would you please take a look at it?

**Comment by takuan-osho** [comment]
I'm also waiting for the fix of this issue. I'm annoyed at this issue.

**Comment by reasonerjt** [comment]
@takuan-osho @francotseng Could you clarify how did you install Harbor?  Does this issue remain in the latest version? (1.6.1)?

**Comment by takuan-osho** [comment]
@reasonerjt I met this issue when the Harbor v1.6.0-rc2. I'll try Harbor v1.6.1. Thanks.

**Comment by reasonerjt** [comment]
@takuan-osho did you use offline installer?  Did you customize anything in configuration?  Such as DB username, etc?

**Comment by francotseng** [comment]
@reasonerjt I used offline installer, of Harbor v1.5.2. And I did customize the DB host, DB name, username and password of Clair DB. BTW, I am using an external PostgreSQL.

**Comment by goidor** [comment]
Any update about this bug? Thanks you.

**Comment by wuming333666** [comment]
check properties table , if the clair_db key is correct with it's value ;

**Comment by doctori** [comment]
quick update on this issue,  
the thing is that the clair database name isn't properly set in the property table.
you can pass something like : 
`CLAIR_DB: harbor-clair`  
in the env  
but the property is recorded as :  
```
harbor-registry=# select * from properties WHERE k LIKE 'clair%';
 id |         k         |                          v                           
----+-------------------+------------------------------------------------------
 63 | clair_db_sslmode  | disable
 47 | clair_db_username | harbor
 38 | clair_db_host     | my-pg-host
 44 | clair_db          | postgres
 42 | clair_db_port     | 5432
 51 | clair_url         | http://harbor-harbor-clair:6060
 24 | clair_db_password | <enc-v1>xxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
```
you'll need to update the value of the clair_db property to the right value : 
` UPDATE properties SET v='harbor-clair' WHERE k='clair_db';` 

and it'll unlock the situation

**Comment by francotseng** [comment]
> quick update on this issue,
> the thing is that the clair database name isn't properly set in the property table.
> you can pass something like :
> `CLAIR_DB: harbor-clair`
> in the env
> but the property is recorded as :
> 
> ```
> harbor-registry=# select * from properties WHERE k LIKE 'clair%';
>  id |         k         |                          v                           
> ----+-------------------+------------------------------------------------------
>  63 | clair_db_sslmode  | disable
>  47 | clair_db_username | harbor
>  38 | clair_db_host     | my-pg-host
>  44 | clair_db          | postgres
>  42 | clair_db_port     | 5432
>  51 | clair_url         | http://harbor-harbor-clair:6060
>  24 | clair_db_password | <enc-v1>xxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
> ```
> 
> you'll need to update the value of the clair_db property to the right value :
> ` UPDATE properties SET v='harbor-clair' WHERE k='clair_db';`
> 
> and it'll unlock the situation

May I ask what version are you on? I'm using harbor v1.5.2 and there is no `properties` table in my database, but a `keyvalue` table. And the following statement returns nothing:
```
registry=> select * from keyvalue where key like 'clair%';
 id | key | value 
----+-----+-------
(0 rows)
```
