### ISSUE TITLE
可以提供一个群出来吗

### ISSUE THREAD

**Issue by yinbucheng** [goharbor/harbor#5455]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by stonezdj** [comment]
目前解决问题主要是靠github.com开issue
