### ISSUE TITLE
Author details can overlap with Architecture field

### ISSUE THREAD

**Issue by hickeng** [goharbor/harbor#5462]
@hickeng commented on [Tue Jul 31 2018](https://github.com/vmware/admiral/issues/283)

Observed in a customer environment (VIC 1.4.2)

The `Author` field for an image in the `Built-in Repository`, speculating at either wrapping or that it somehow contained a newline.

The name of the author was in the expected location, however the email of the author overlaid the `Architecture` value (which was `amd64`), rendering mixed text.

---

@lazarin commented on [Wed Aug 01 2018](https://github.com/vmware/admiral/issues/283#issuecomment-409505121)

@hickeng I guess it's about the page in the attached screen : 
![screenshot at 2018-08-01-11-55-44](https://user-images.githubusercontent.com/676880/43511781-fd57ce1c-9581-11e8-9c40-3206e2300ce2.png)

This is coming from Harbor, and I am not sure if I'll be able to move it via ZenHub to the right project.
cc: @reasonerjt

**Comment by reasonerjt** [comment]
The screenshot by Lazo seems correct, @hickeng is there a screenshot in reflect the problem mentioned in the description?

**Comment by zhoumeina** [comment]
@hickeng , it may have this case, I think I have fixed it in harbor 1.6. I am not sure if it is ok to fix it in vic 1.5. Because vic 1.5 will bump up harbor 1.7 which includes my fix in.

**Comment by zhoumeina** [comment]
@pureshine , please check if this issue still exsit in vic 1.5 ova.

**Comment by pureshine** [comment]
I deployed a 1.5 ova and tested it, it looks good，no overlap of authors and Architecture
