### ISSUE TITLE
Issues on the table view of helm chart registry.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5467]
Build: Version v1.6.0-c5a79fb5
![image](https://user-images.githubusercontent.com/2390463/43565887-0e8f4e84-965f-11e8-9d5b-1080fc1ed374.png)

1.  The header `versions` should be `Version
2.  The message `No Item` is not consistent with other tabs, such as replication/repositories.
3.  The bottom of the table, when there's not charts, it should be `0 items` instead of `0-15 of 0 charts`

**Comment by reasonerjt** [comment]
4. the search field does not work.

**Comment by ninjadq** [comment]
fixed in #5459

**Comment by ywk253100** [comment]
The third one is still there.

**Comment by ninjadq** [comment]
Fixed in https://github.com/goharbor/harbor/pull/5663
