### ISSUE TITLE
the buttons in replication rule page are still enabled even no rule item is selected

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5469]
<img width="1180" alt="screen shot 2018-08-02 at 14 24 38" src="https://user-images.githubusercontent.com/5753287/43566155-09cd26c2-9660-11e8-9657-bd1d8c819700.png">

**click the 'replicate' button:**
<img width="946" alt="screen shot 2018-08-02 at 14 27 30" src="https://user-images.githubusercontent.com/5753287/43566213-46059520-9660-11e8-8257-4d264cf8fd80.png">

**Comment by zhoumeina** [comment]
@pureshine , please check if this issue stil exsit, if not just close it.

**Comment by pureshine** [comment]
![20180919132905](https://user-images.githubusercontent.com/40712758/45732747-523c9200-bc10-11e8-8556-ece2911d27ff.png)
the buttons in replication rule page are not enabled when no rule item is selected.
