### ISSUE TITLE
The 'save' button is still disabled even the label filter is removed

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5470]
The replication rule with label filter:
<img width="588" alt="screen shot 2018-08-02 at 14 33 45" src="https://user-images.githubusercontent.com/5753287/43566513-3cad142a-9661-11e8-9536-8c6f1611cd95.png">

Remove the label filter, the `save` button is still disabled:
<img width="575" alt="screen shot 2018-08-02 at 14 34 00" src="https://user-images.githubusercontent.com/5753287/43566532-4c4addea-9661-11e8-8bc1-b2e39eeb67b5.png">

**Comment by zhoumeina** [comment]
@steven-zou Can you help to reproduce? In your screenshot, the filter is still there.

**Comment by zhoumeina** [comment]
fixed by #5483
