### ISSUE TITLE
Set a min interval (3s-5s) for the notification center to auto close if it is opened by the system itself

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5471]
<img width="356" alt="screen shot 2018-08-02 at 14 46 23" src="https://user-images.githubusercontent.com/5753287/43567009-fa0b240c-9662-11e8-9e9c-b382f1263415.png">

**Comment by zhoumeina** [comment]
This requirement is not reasonable, it will interrupt user if close it automatically.
