### ISSUE TITLE
Rename the "Repositories" tab to "Images"?

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5494]
After the supporting of chart repository, maybe we should rename it to "Images"?
<img width="1320" alt="repository" src="https://user-images.githubusercontent.com/5835782/43577827-93d01716-967f-11e8-9327-a63342b222d7.png">

**Comment by lweitzman** [comment]
i think we should keep the repositories tab. when we drill into a repository, we see tabs for "info" and "images" (references to "tags" instead of images should be removed #4620 )
mockups can be seen here https://vmware.invisionapp.com/share/6HN0EZMVC5M#/288710626_Project

**Comment by steven-zou** [comment]
Let's close this issue. If the users have comments, we reopen it then.
