### ISSUE TITLE
Pass CII Best Practices Badge Program

### ISSUE THREAD

**Issue by caniszczyk** [goharbor/harbor#5503]
Per CNCF requirements, please work on passing the CII best practices badging program and adding it to your README: https://bestpractices.coreinfrastructure.org/en

**Comment by clouderati** [comment]
Thanks @caniszczyk – will def start working on this.

**Comment by clouderati** [comment]
Added badge in https://github.com/goharbor/harbor/commit/8cb90d6e2acf2d85b89bf51b4df36ed763a79277; will work on improving the number. 😄

**Comment by reasonerjt** [comment]
Resolving this as we now have silver badge.
