### ISSUE TITLE
Add FOSSA license scanning

### ISSUE THREAD

**Issue by caniszczyk** [goharbor/harbor#5505]
CNCF has this as a free service for CNCF projects: http://fossa.io/

However, we will wait to do this until you transfer the github repo to the new org

**Comment by clouderati** [comment]
sgtm – thanks @caniszczyk

**Comment by clouderati** [comment]
ping @steven-zou

**Comment by caniszczyk** [comment]
ping @steven-zou

**Comment by caniszczyk** [comment]
friendly ping
