### ISSUE TITLE
Update Code of Conduct to the CNCF one

### ISSUE THREAD

**Issue by caniszczyk** [goharbor/harbor#5506]
https://github.com/vmware/harbor/blob/master/code-of-conduct.md

to

https://github.com/cncf/foundation/blob/master/code-of-conduct.md

**Comment by clouderati** [comment]
@steven-zou is reviewing PR that references CNCF code of conduct.

**Comment by clouderati** [comment]
Fixed in https://github.com/goharbor/harbor/commit/f83f2f4bab39e9f56db81f70da30116cff06097e.
