### ISSUE TITLE
Move to DCO from CLA

### ISSUE THREAD

**Issue by caniszczyk** [goharbor/harbor#5507]
A CLA isn't required in CNCF and is optional.

We recommend removing your VMWare CLA and moving to the DCO

GitHub has an app that makes it easy to enable DCO checking on PRs:
https://github.com/probot/dco

**Comment by clouderati** [comment]
@steven-zou is removing CLA requirement / bot

**Comment by reasonerjt** [comment]
Can we do this after migrating the repo?

**Comment by clouderati** [comment]
I think that's reasonable @reasonerjt; @caniszczyk, is that ok?

**Comment by caniszczyk** [comment]
SGTM, it's very easy to enable

**Comment by steven-zou** [comment]
DCO enabled now!

**Comment by clouderati** [comment]
Great @steven-zou!
