### ISSUE TITLE
Can we support pull direction replication?

### ISSUE THREAD

**Issue by nkwangleiGIT** [goharbor/harbor#5528]
New requirement:
Current deployment architecture:
1) Dev/Test harbor instance
2) Prod harbor instance

Some users want to configure replication policy from Dev/Test to Prod, but don't want to do this in their Dev/Test side, as Dev/Test should not have the permission to replicate images to Prod.
So they want to only allow users login to Prod harbor instance, configure replication policy on Prod side, and then pull(replicate) the images from Dev/Test harbor instance.

Can we support this requirement?

Thanks!

**Comment by clouderati** [comment]
Yes, agreed. We have this on our roadmap. If you're willing to contribute this feature we'd be more than happy to help you through the process. 👍

**Comment by tobad357** [comment]
@clouderati is this being worked on and if not are there any design docs around it available?
This would be very useful for us for exactly the same reason as above

**Comment by tobad357** [comment]
@clouderati not sure why you got unassigned, very sorry about that

**Comment by ywk253100** [comment]
This has been implemented in v1.8, closing the issue.
