### ISSUE TITLE
Documentations : Using UAA with Gitlab

### ISSUE THREAD

**Issue by katyucha** [goharbor/harbor#5533]
Hi
I want to connect UAA with my personal Gitlab 

I don't find informations in the doc about the redirect url ? 

I will make a PR for it but,  I still need the informations before :) 

Thanks

**Comment by steven-zou** [comment]
@katyucha 

Could you please give us more background about your use case/scenario?

So far, we do not support UAA with OAuth way yet and then there is no document about that.

**Comment by katyucha** [comment]
Hi

I want to use Harbor with the oauth2 gitlab server
My developpers use an internal gitlab and we want to deploy a registry with many features like Harbor
But how to manage authentification and authorization ? For Jenkins, mattermost and lot of our application around gitlab ,  we use the oauth2 gitlab provider  ( https://docs.gitlab.com/ee/integration/oauth_provider.html ) . 
Many reason : One provider to authentification , On provider for group of developpers...etc 

Can we configure the UAA with the oauth2 provider or is this incompatible ?

**Comment by clouderati** [comment]
Keeping tabs on this particular feature request in https://github.com/goharbor/harbor/issues/4616. Let's move all future conversation there.
