### ISSUE TITLE
Unable To Get Notary Working Properly

### ISSUE THREAD

**Issue by kacole2** [goharbor/harbor#5540]
I'm writing an automation script that will install Harbor with Notary and Clair using Self-Signed certs. I've followed the directions to [Configure Harbor with HTTPS Access](https://github.com/vmware/harbor/blob/master/docs/configure_https.md).  

After completing the installation, I can successfully login and push images
```
[kcoleman@harbor01 ~]$ sudo docker login harbor01.vsphere.local
Username: admin
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

However, when I try to the Docker Content Trust to use Notary, I'm never given a prompt to enter a password. And the `test` bucket has the content trust enabled.
```
[kcoleman@harbor01 ~]$ export DOCKER_CONTENT_TRUST_SERVER=https://harbor01.vsphere.local:4443
[kcoleman@harbor01 ~]$ export DOCKER_CONTENT_TRUST=1
[kcoleman@harbor01 ~]$ sudo docker tag nginx:latest harbor01.vsphere.local/test/nginx:V1
[kcoleman@harbor01 ~]$ sudo docker push harbor01.vsphere.local/test/nginx:V1
The push refers to repository [harbor01.vsphere.local/test/nginx]
08d25fa0442e: Pushed
a8c4aeeaa045: Pushed
cdb3f9544e4c: Pushed
V1: digest: sha256:4ffd9758ea9ea360fd87d0cee7a2d1cf9dba630bb57ca36b3108dcd3708dc189 size: 948
```

And the UI still shows an X where it says signed.

Please take a look at my [Gist](https://gist.github.com/kacole2/29690512a1b213cb210ccace687b78bc)
https://gist.github.com/kacole2/29690512a1b213cb210ccace687b78bc

If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
```
[kcoleman@harbor01 ~]$ sudo docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
[kcoleman@harbor01 ~]$ docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

the only things changed from the standard `harbor.cfg` is:
```
sed -i "s|hostname = reg.mydomain.com|hostname = $HOSTNAME|g" harbor.cfg
sed -i "s|ui_url_protocol = http|ui_url_protocol = https|g" harbor.cfg
sed -i "s|ssl_cert = /data/cert/server.crt|ssl_cert = /root/cert/$FQDN.crt|g" harbor.cfg
sed -i "s|ssl_cert_key = /data/cert/server.key|ssl_cert_key = /root/cert/$FQDN.key|g" harbor.cfg
```

3)Log files, you can get them by package the /var/log/harbor/ .

**Comment by reasonerjt** [comment]
@kacole2 When you run `sudo docker push` the env you set will not take effect.

**Comment by kacole2** [comment]
@reasonerjt ahhh. you're right! it was there in front of my face the entire time. I've updated my [gist](https://gist.github.com/kacole2/29690512a1b213cb210ccace687b78bc) and also created a [blog post](http://kendrickcoleman.com/index.php/Tech-Blog/how-to-install-harbor-on-centos-7-using-bash.html) on it. Thanks for the help!
