### ISSUE TITLE
Possible to display IP address in log?

### ISSUE THREAD

**Issue by LoLei** [goharbor/harbor#5561]
**Is it possible to display the IP address of the machine from which actions are done in the web UI activity log?**

E.g. instead of just showing that `username` `admin` did `operation` `pull` on `op_time` `<timestamp>` for some repo, show the IP that was used to issue that operation in addition?

I have different machines logged in as the same user, and would like to differentiate between those machine based on their IP. Otherwise they all show up as the same user in the log, with no way to tell which machine actually did the logged operation.

Is it possible to do this, or does Harbor not even receive the IP, i.e. the technology is not there yet?

**Comment by steven-zou** [comment]
@LoLei 

  Thanks for submitting the idea. From the technical perspective, I don't think there is block issue to support that requirement. But we need to review and discuss if it is a reasonable scenario from both tech and privacy protection perspectives.

**Comment by LoLei** [comment]
If it's a privacy issue, it might be a good idea to either let SysAdmin users toggle the IP display in the web UI configuration, or add a setting somewhere else, e.g. 'harbor.cfg'.

In any case, make it optional.

**Comment by LoLei** [comment]
@clouderati Unfortunately I won't be available for a few weeks after today, so I'd rather not commit to anything. I'm glad my idea is taken into consideration though!

**Comment by clouderati** [comment]
No worries @LoLei – very much appreciate your input. Hope to see you on a community call sometime soon. 😄

**Comment by steven-zou** [comment]
@LoLei 
Please refer https://github.com/goharbor/community/pull/10 for more info
