### ISSUE TITLE
The "UPLOAD" button in "Helm Charts" tab is disabled when login as a developer

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5597]

**Comment by ywk253100** [comment]
<img width="1675" alt="upload01" src="https://user-images.githubusercontent.com/5835782/44073982-63267d14-9fc9-11e8-8abe-45cdc654599b.png">

<img width="1676" alt="upload02" src="https://user-images.githubusercontent.com/5835782/44073990-69b654f6-9fc9-11e8-90e8-bdc99f02d232.png">

**Comment by ninjadq** [comment]
Fixed in https://github.com/goharbor/harbor/pull/5663
