### ISSUE TITLE
The detail page of a scanned image has overlap of text fields.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5600]
Build: v1.6.0-6fb07c60

After scanning an image I clicked the link of the tag and there are overlaps of text fields:

<img width="1022" alt="screen shot 2018-08-14 at 2 08 10 pm" src="https://user-images.githubusercontent.com/2390463/44074528-7fa147bc-9f88-11e8-9857-a7d35f177750.png">

**Comment by zhoumeina** [comment]
fix issue helmchart layout related issues #5652
