### ISSUE TITLE
Create group dialog ignores the error from backend

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5602]
Build: Version v1.6.0-6fb07c60

1. Login as admin
2. Go to Administration-> Groups click New Group
3. Input invalid group DN, such as:`asdfg`, and click OK
4. Backend API returns 404 but UI is not displaying any error.

Additionally, seems the UI doesn't handle any error from backend when creating a group.

**Comment by zhoumeina** [comment]
fix issue helmchart layout related issues #5652
