### ISSUE TITLE
Misc issues for chart repo card view

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5603]
1. The card is larger when containing more than one versions:
<img width="1677" alt="card01" src="https://user-images.githubusercontent.com/5835782/44075166-3ea584f8-9fce-11e8-8c45-29c5ca88933b.png">
2. Wrong version:
<img width="1676" alt="card02" src="https://user-images.githubusercontent.com/5835782/44075197-5c049480-9fce-11e8-9ebd-fef2a0313f08.png">

The coressponding list view is as follow:
<img width="1676" alt="list01" src="https://user-images.githubusercontent.com/5835782/44075230-85cbbd0c-9fce-11e8-8452-25f38a6ff047.png">
3.  The icon is missing after clicking the refresh button:
<img width="1678" alt="card03" src="https://user-images.githubusercontent.com/5835782/44075238-964b07d2-9fce-11e8-8cb9-6001f76559c6.png">

**Comment by ywk253100** [comment]
For item 2, the `Version` showed is `App Version`, not the `Chart Version`.

**Comment by zhoumeina** [comment]
fixed by fix issue helmchart layout related issues #5652
