### ISSUE TITLE
The name of LDAP group should be required and validate by both UI and API

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5605]
<img width="684" alt="screen shot 2018-08-14 at 14 39 38" src="https://user-images.githubusercontent.com/5753287/44075618-fe5ecf4c-9fcf-11e8-9826-84c0f34805f3.png">

**Comment by stonezdj** [comment]
API validation added in #5619

**Comment by ninjadq** [comment]
UI added validation on pr https://github.com/goharbor/harbor/pull/5663
