### ISSUE TITLE
The "Version" on "Overview" should be renamed to "APP Version"

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#5606]
<img width="1672" alt="appversion" src="https://user-images.githubusercontent.com/5835782/44075545-b6ca0e9e-9fcf-11e8-911a-4339889e428f.png">

**Comment by ywk253100** [comment]
There are two versions: `chart version` and `app version`. We should distinguish them.

**Comment by ninjadq** [comment]
Fixed in https://github.com/goharbor/harbor/pull/5663
