### ISSUE TITLE
API:api/projects?name=xxx is  fuzzy queries,need an exact query

### ISSUE THREAD

**Issue by foxwang** [goharbor/harbor#5607]
api/projects?name=public

now:
[
  {
    "project_id": 9,
    "owner_id": 1,
    "name": "apublic",
    "creation_time": "2018-08-13T09:53:48Z",
    "update_time": "2018-08-13T09:53:48Z",
    "deleted": 0,
    "owner_name": "",
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 0,
    "metadata": {
      "public": "false"
    }
  },
  {
    "project_id": 5,
    "owner_id": 1,
    "name": "public",
    "creation_time": "2018-08-13T08:51:27Z",
    "update_time": "2018-08-13T08:51:27Z",
    "deleted": 0,
    "owner_name": "",
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 4,
    "metadata": {
      "public": "true"
    }
  },
  {
    "project_id": 6,
    "owner_id": 1,
    "name": "public0",
    "creation_time": "2018-08-13T09:04:27Z",
    "update_time": "2018-08-13T09:04:27Z",
    "deleted": 0,
    "owner_name": "",
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 0,
    "metadata": {
      "public": "true"
    }
  }
]

want:
[
 {
    "project_id": 5,
    "owner_id": 1,
    "name": "public",
    "creation_time": "2018-08-13T08:51:27Z",
    "update_time": "2018-08-13T08:51:27Z",
    "deleted": 0,
    "owner_name": "",
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 4,
    "metadata": {
      "public": "true"
    }
  }
]
3Q

**Comment by wutongjie23hao** [comment]
pull request has committed.
https://github.com/goharbor/harbor/pull/5627
