### ISSUE TITLE
After setting the admin group DN, the user still appear to be a normal one.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5608]
Build: v1.6.0-6fb07c60
`mike02` is a member of group of a certain DN

Login as admin and set this DN as `LDAP Group Admin DN`.
`mike02` has the permission to push image to any project, but when I login as `mike02` the tabs for admin do not show up.

Root cause: The response of `GET /api/users/current` doesn't set `has_admin_role` correctly.

**Comment by stonezdj** [comment]
Fixed in #5613
