### ISSUE TITLE
Incorrect UI views when logging in with a user in the group assigned with proper role

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5610]
<img width="1185" alt="screen shot 2018-08-14 at 16 27 20" src="https://user-images.githubusercontent.com/5753287/44080699-69129fc6-9fdf-11e8-8c05-d9b1e5249256.png">

Also, role name is mising in the project detail page

**Comment by ninjadq** [comment]
Fixed in https://github.com/goharbor/harbor/pull/5663
