### ISSUE TITLE
Build harbor image on different base OS

### ISSUE THREAD

**Issue by starzha** [goharbor/harbor#5615]
Hi,

Is it possible to build harbor ui, jobservice on other linux OS, for example, SUSE, CentOS?

Thanks,
starz

**Comment by steven-zou** [comment]
@starzha 

  I think the answer is YES, but we'll not provide those distributions because of resource limitations. If you have a strong requirement, maybe you can have a try and then contribute them back to the community. We encourage community users to participate more. What do you think?

**Comment by starzha** [comment]
@steven-zou Thanks for the feedback.

Sure. I will have a try and contibute it back. I haven't done it before, any guideline for me to reference? 

Thanks,
starz
