### ISSUE TITLE
replication error，Test connection success，V1.5.2

### ISSUE THREAD

**Issue by FlyingheartCN** [goharbor/harbor#5631]
I installed VMWare Harbor using harbor-offline to 2 machine, which is 192.168.1.4 and 192.168.1.3
I set replication rule from 192.168.1.3 to 192.168.1.4 , test connection success. And add dns h.dr.z=192.168.1.3, But replication error

In jobservice.log

Job 'IMAGE TRANSFER:b454f9e6579faf3fa12a76a50' exit with error: Get http://h.dr.z/api/projects?name=library: dial tcp 192.168.1.3:80 getsockopt: no route to host

**Comment by ninjadq** [comment]
hi, FlyingheartCN please check your firewall rules. Is everything ok?

**Comment by FlyingheartCN** [comment]
@ninjadq the firewalld is default set, I tried "curl 192.168.1.4" in 192.168.1.3 harbor-ui docker , and it normal. But "curl 192.168.1.3" in 192.168.1.3 's harbor-ui docker is abnormal.
I add a host to it , set h.dr.z to docker nginx's ip, and it is success to replication
