### ISSUE TITLE
Scan by Clair not work after upgrade to 1.5.2 

### ISSUE THREAD

**Issue by dma-vitch** [goharbor/harbor#5638]
After upgrade from version 1.5.0 to 1.5.2. Scan by clair didn't work.
Additional info  
1)Version of docker engine  18.03.1-ce and docker-compose 1.21.2
3) Logs : 
Aug 15 21:53:26 test-harbor clair[16153]: {"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2018-08-15 18:53:26.284873","port":6061}
Aug 15 21:53:26 test-harbor clair[16153]: {"Event":"updater service started","Level":"info","Location":"updater.go:81","Time":"2018-08-15 18:53:26.284991","lock identifier":"665279a5-d908-4e76-b942-068f8b7ee10f"}
Aug 15 21:56:14 test-harbor clair[16153]: {"Event":"failed to extract data from path","Level":"error","Location":"worker.go:122","Time":"2018-08-15 18:56:14.215811","error":"tarutil: could not extract the archive","layer":"75cc1c26f128eb75853d44d480804216f055b7574761917b8a449d59fe0377bb","path":"http://registry:5000/v2/test/tgenie-base/blobs/sha256:e6faa08065edd437a989f5afa3efec256305ca8d83dd87a0b30ad55b31c276a3"}
Aug 15 21:56:14 test-harbor clair[16153]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2018-08-15 18:56:14.217742","elapsed time":2014992902,"method":"POST","remote addr":"172.19.0.6:35540","request uri":"/v1/layers","status":"422"}

But on old version of clair scaning work is good.
It happen for all images

**Comment by dma-vitch** [comment]
@reasonerjt Yes, it is happens to all images in registry.
I am trying fresh install now. And will check this bug is
reproduced.

**Comment by reasonerjt** [comment]
thank you @dma-vitch please let us know

**Comment by dma-vitch** [comment]
I'm surprised on fresh install error is reproduced. 
I don't understand what happened.

**Comment by reasonerjt** [comment]
@dma-vitch  
By fresh install, did you use offline installer?  Did you install it on a clean env? i.e. no any images exist on the env?

What's your OS distro?

**Comment by dma-vitch** [comment]
Yes, I did used offline installer. Previous version of Harbor has been destroyed. Env was been clean only new images version in environment. But I haven't tried install on new virtual machine, yet. 
My distro Ubuntu 18.04.

**Comment by dma-vitch** [comment]
I'm installed on new clean VM and this error is reproduced.

**Comment by reasonerjt** [comment]
@dma-vitch we'll try to reproduce in this week.

**Comment by wy65701436** [comment]
@dma-vitch  I tried to reproduce it on my 18.04, all things are fine.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/2841473/44383189-6ecea700-a54a-11e8-96b7-bf8c34c94dc6.png">

Could you try to clean your image and restart harbor? and try to scan an official docker image, like Redis. 

If you still encounter the issue? Please upload the full log of Harbor.

**Comment by dma-vitch** [comment]
i'm sorry my bad.
I forgot to add registry to no_proxy for claim.
But I'm checking offline installer and by default this string not contrains registry.
see
```no_proxy = 127.0.0.1,localhost,ui ```
but this string like look as
```no_proxy = 127.0.0.1,localhost,ui,registry```
