### ISSUE TITLE
Helm Chart upload dialog needs redesign

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#5646]
the current upload dialog is 
![Screen Shot 2018-08-16 at 8.42.05 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/c47f3cbc-7d0a-4bb1-8f71-69cfb46736e9)

It should be this
![Screen Shot 2018-08-16 at 9.21.27 AM.png](https://images.zenhubusercontent.com/56afa7c46caf56c9d38c1f12/d3fb17ce-b3f5-4193-a535-96f2e297084b)

In particular:
input lines of files should precede the browse button
label, input field and button should align vertically
action buttons should be "Cancel and "Upload" in the lower right corner of the dialog

mockup: https://vmware.invisionapp.com/share/6HN0EZMVC5M#/314796399_Helm_Chart_-_Content_Libraries_-_Helm_Charts_-_Upload

**Comment by ninjadq** [comment]
Fixed in https://github.com/goharbor/harbor/pull/5663
