### ISSUE TITLE
error parsing HTTP 403 response body: unexpected end of JSON input: ""

### ISSUE THREAD

**Issue by katelynwang** [goharbor/harbor#5656]
Docker info:
![info](https://user-images.githubusercontent.com/12420005/44260449-fc5a8000-a246-11e8-836f-b82a595b8517.PNG)

docker version and docker-compose version:
![version](https://user-images.githubusercontent.com/12420005/44260463-07151500-a247-11e8-92a4-ba8692cd613a.PNG)

registry log:
![registry](https://user-images.githubusercontent.com/12420005/44260482-172cf480-a247-11e8-8371-9ec539f690e1.PNG)

jobservice log:
![jobservice](https://user-images.githubusercontent.com/12420005/44260495-21e78980-a247-11e8-8a67-80c8d93f314c.PNG)

I developed a new storage driver for a backend storage based on docker registry on github.com, built it as a new image and renamed it as vmware/registry-photon:v2.6.2-v1.5.2. Then I started harbor. 
I tried to push the hello-world image to the backend storage, it uploaded successfully, cuz I was able to see it on the storage bucket, but i couldnt see it on harbor page. 
It said [error parsing HTTP 403 response body: unexpected end of JSON input: ""]

Anyone can help me with this?
Thanks a lot

PS I ran harbor on a cloud server, cant do copy paste. Sorry for the inconvenience.

**Comment by reasonerjt** [comment]
@katelynwang We need to understand which API caused this error.  
Could you open the `Developer Tools` and check the responses from server side?

**Comment by katelynwang** [comment]
![error](https://user-images.githubusercontent.com/12420005/44317894-05756800-a466-11e8-8ef1-2d69c5dc49e2.PNG)
@reasonerjt these are the errors ive got, I dont understand why i got these tho, the image has been pushed to the cloud successfully, and I made the bucket public already

**Comment by reasonerjt** [comment]
@katelynwang 
These errors are for the requests sent from browser and it has nothing to do with `docker push`
From the network tab, you can see which requests are getting such errors.  
Seems you are using incorrect credentials trying to sign in from UI

**Comment by katelynwang** [comment]
@reasonerjt 
1. looks like current is getting 401
![401](https://user-images.githubusercontent.com/12420005/44324469-56965380-a488-11e8-9f8b-018761d1ba7d.PNG)

2. But if the credentials are wrong, how come the image's pushed successfully to the storage?
I modified storage info in both harbor.cfg and common/template/registry/config.yml, I still get this error, can you please tell me what to do?

**Comment by reasonerjt** [comment]
Could you login to Harbor UI using the credentials you used for "docker login"?
Where did you see the error msg on UI could you provide a screenshot?
Please reproduce the issue, and package the log files under /var/log/harbor and attach to the issue.

**Comment by katelynwang** [comment]
@reasonerjt 
Yes i can login to UI, too.
If I login with "docker login xx.xx.xx.xx" and push the image, I get the error from the title
![error](https://user-images.githubusercontent.com/12420005/44326474-6749c800-a48e-11e8-9421-3dc49e92fc38.PNG)

errors in UI are attached before (https://github.com/goharbor/harbor/issues/5656#issuecomment-414214409)
screenshots for logs is are above (https://github.com/goharbor/harbor/issues/5656#issue-351534043)

**Comment by reasonerjt** [comment]
Please provide the log files instead of the screenshot?  
If you need us help you debug please package all log files and attach to the issue.

**Comment by katelynwang** [comment]
@reasonerjt 
I cant upload files directly due to company confidential regulations, i put them in a repo instead (https://github.com/katelynwang/harbor_logs).
error occurred around 17:43 on Aug 17 if it helps
Thanks

**Comment by cd1989** [comment]
Is your Harbor deployed in HA pattern ? I once encountered the same problem, it's because my redis service is not function well. @katelynwang

**Comment by katelynwang** [comment]
@cd1989 ummm what's HA pattern? I didn't change anything of redis tho

**Comment by cd1989** [comment]
@katelynwang HA means High Availability, then your problem should have nothing to do with this.

**Comment by katelynwang** [comment]
Problem solved by adding "redirect disable: false" in config.yml, so im gonna close this

**Comment by supermanisme** [comment]
i get the same Problem,backend use S3 storage. 
regionendpoint : http://XX.XX.XX.XX:PORT 
Problem solved by removeing PORT.
regionendpoint : http://XX.XX.XX.XX

**Comment by microyahoo** [comment]
The registry sends backs redirect URL back to the docker client. If redirects are disabled in the registry configuration, pushing works.
```yaml
redirect:                                                                                                                              
     disable: true 
```
refer link: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/19356
