### ISSUE TITLE
Build harbor errors

### ISSUE THREAD

**Issue by starzha** [goharbor/harbor#5660]
Hi,

I tried to build harbor, but met errors:

STEP1: on ubuntu OS, i download harbar 1.5.2 tar.gz

STEP2:  extract 1.5.2.tar.gz, and go into harbor-1.5.2 directory

STEP3: use golang image to compile

> make compile_golangimage -e GOBUILDIMAGE=golang:1.9.2 -e CLARITYIMAGE=goharbor/harbor-clarity-ui-builder:1.6.0

Here is the output and in the bottom of the logs indicating an error:

compiling binary for clarity ui...
Unable to find image 'goharbor/harbor-clarity-ui-builder:1.6.0' locally
1.6.0: Pulling from goharbor/harbor-clarity-ui-builder
d660b1f15b9b: Pull complete 
46dde23c37b3: Pull complete 
6ebaeb074589: Pull complete 
e7428f935583: Pull complete 
eda527043444: Pull complete 
f3088daa8887: Pull complete 
80e2dc61b67d: Pull complete 
26d4b3db26a2: Pull complete 
3a49dc786348: Pull complete 
738a59f547e1: Pull complete 
232017881dc5: Pull complete 
8c26b98aeeb8: Pull complete 
717215e8ace3: Pull complete 
b5f09b6d5afe: Pull complete 
ac538f2f74bd: Pull complete 
72d44d5539cb: Pull complete 
06f46a76b4be: Pull complete 
Digest: sha256:1600679b5bab5256020a3a74a694c835a419d73fcb4cfea89b658249558e2b8e
Status: Downloaded newer image for goharbor/harbor-clarity-ui-builder:1.6.0
{
    "name": "harbor",
    "version": "1.3.0",
    "description": "Harbor UI with Clarity",
    "angular-cli": {},
    "scripts": {
        "start": "ng serve --ssl 1 --ssl-key ssl/server.key --ssl-cert ssl/server.crt --host 0.0.0.0 --proxy-config proxy.config.json",
        "lint": "tslint \"src/**/*.ts\"",
        "test": "ng test --single-run",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor",
        "build": "ngc -p tsconfig-aot.json"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^4.3.0",
        "@angular/common": "^4.3.0",
        "@angular/compiler": "^4.3.0",
        "@angular/core": "^4.3.0",
        "@angular/forms": "^4.3.0",
        "@angular/http": "^4.3.0",
        "@angular/platform-browser": "^4.3.0",
        "@angular/platform-browser-dynamic": "^4.3.0",
        "@angular/router": "^4.3.0",
        "@ngx-translate/core": "^6.0.0",
        "@ngx-translate/http-loader": "0.0.3",
        "@types/jquery": "^2.0.41",
        "@webcomponents/custom-elements": "^1.0.0",
        "clarity-angular": "^0.10.27",
        "clarity-icons": "^0.10.27",
        "clarity-ui": "^0.10.27",
        "core-js": "^2.4.1",
        "harbor-ui": "0.6.99",
        "intl": "^1.2.5",
        "mutationobserver-shim": "^0.3.2",
        "ngx-cookie": "^1.0.0",
        "rxjs": "^5.0.1",
        "ts-helpers": "^1.1.1",
        "web-animations-js": "^2.2.1",
        "zone.js": "0.8.19"
    },
    "devDependencies": {
        "@angular/cli": "^1.0.0",
        "@angular/compiler-cli": "^4.3.0",
        "@types/core-js": "^0.9.34",
        "@types/jasmine": "~2.2.30",
        "@types/node": "^6.0.42",
        "bootstrap": "4.0.0-alpha.5",
        "codelyzer": "~2.0.0-beta.4",
        "enhanced-resolve": "^3.0.0",
        "jasmine-core": "2.4.1",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-mocha-reporter": "^2.2.1",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "4.0.9",
        "rollup": "^0.41.6",
        "rollup-plugin-commonjs": "^8.0.2",
        "rollup-plugin-node-resolve": "^3.0.0",
        "rollup-plugin-uglify": "^1.0.1",
        "ts-node": "1.2.1",
        "tslint": "^4.1.1",
        "typescript": "~2.2.0",
        "typings": "^1.4.0",
        "webdriver-manager": "10.2.5"
    }
}

**Comment by steven-zou** [comment]
@ninjadq 

Please help to take a look at this issue.

**Comment by ninjadq** [comment]
hi @starzha , plz using `vmware/harbor-clarity-ui-builder:1.4.1` instead when you build harbor.

**Comment by starzha** [comment]
@ninjadq  Thanks.

The previous errors are solved, however there are new errors:

npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.5.0
npm info attempt registry request try #1 at 6:44:57 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/fsevents
npm info lifecycle harbor@1.3.0~preinstall: harbor@1.3.0
npm info linkStuff harbor@1.3.0
npm info lifecycle harbor@1.3.0~install: harbor@1.3.0
npm info lifecycle harbor@1.3.0~postinstall: harbor@1.3.0
npm info lifecycle harbor@1.3.0~prepublish: harbor@1.3.0
npm info lifecycle harbor@1.3.0~prepare: harbor@1.3.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm info ok 


'default' is not exported by 'node_modules/rxjs/add/operator/toPromise.js'
cp: cannot stat './src/styles.scss': No such file or directory
Makefile:253: recipe for target 'compile_clarity' failed
make: *** [compile_clarity] Error 1

**Comment by ninjadq** [comment]
@starzha oh, sorry, try to using `1.4.0` instead

**Comment by starzha** [comment]
@ninjadq Thanks. It is working now.
