### ISSUE TITLE
After image been pushed successfully, nothing can found in Harbor UI, but I can pull it

### ISSUE THREAD

**Issue by satomic** [goharbor/harbor#5664]
my tried harbor version is `v1.6.0-rc1`, I can install it successfully. but after image been pushed successfully, nothing can found in Harbor UI, it's empty in the project. 
but I can pull the image from harbor although I can't see it in UI.
btw, I can see the registry file in path: `/data/registry/docker/registry/v2/repositories`, so some thing must be wrong with the UI. but I don't know the reason.

1)Version of docker engine and docker-compose.
docker version: `17.03.2-ce`
docker-compose version: 
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
---
2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
I have change 3 files in the directory
(1) `harbor.cfg` in line 7
```
3 #This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
  4 _version = 1.6.0
  5 #The IP address or hostname to access admin UI and registry service.
  6 #DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
  7 hostname = 52.80.222.2:8080
```
(2) `docker-compose.yml` in line 136
```
127   proxy:
128     image: goharbor/nginx-photon:v1.6.0
129     container_name: nginx
130     restart: always
131     volumes:
132       - ./common/config/nginx:/etc/nginx:z
133     networks:
134       - harbor
135     ports:
136       - 8080:80
137       - 443:443
138       - 4443:4443
```
(3) `common/templates/registry/config.yml` in line 34
```
 30 notifications:
 31   endpoints:
 32   - name: harbor
 33     disabled: false
 34     url: $ui_url:8080/service/notifications
 35     timeout: 3000ms
 36     threshold: 5
 37     backoff: 1s
```

3)Log files, you can get them by package the /var/log/harbor/ .
all files there are compressed as a harbor-logs.tar file, you can download it here: https://pan.baidu.com/s/1g9FV0j6a3zFcSGu1Vqr8bw

thanks!

**Comment by satomic** [comment]
@reasonerjt I tried it, the first two steps were run without problems, but after the last commond, the console stopped at this condition
```
ubuntu@rancher-harbor-001:~/rancher/harbor/harbor$ sudo docker-compose up
Creating network "harbor_harbor" with the default driver
Creating harbor-log ... done
Creating redis              ... done
Creating registry           ... done
Creating harbor-adminserver ... done
Creating harbor-db          ... done
Creating harbor-ui          ... done
Creating nginx              ... done
Creating harbor-jobservice  ... done
Attaching to harbor-log, redis, harbor-db, harbor-adminserver, registry, harbor-ui, harbor-jobservice, nginx
redis          | WARNING: no logs are available with the 'syslog' log driver
harbor-db      | WARNING: no logs are available with the 'syslog' log driver
harbor-adminserver | WARNING: no logs are available with the 'syslog' log driver
registry       | WARNING: no logs are available with the 'syslog' log driver
harbor-ui      | WARNING: no logs are available with the 'syslog' log driver
harbor-jobservice | WARNING: no logs are available with the 'syslog' log driver
nginx          | WARNING: no logs are available with the 'syslog' log driver
```
and the harbor UI can't be access with error `Service Unavailable`

**Comment by reasonerjt** [comment]
use `docker-compose up -d`
But the error `Service Unavailable` should be caused by some container not in running state please check the logs under `/var/log/harbor` or use `docker ps -a` to figure out.

**Comment by reasonerjt** [comment]
1) You can push again
2) There is a flag, but that's for internal use:
https://github.com/goharbor/harbor/blob/master/make/common/templates/ui/env#L9
Set it to `true` and images will be sync to DB when Harbor's started.

**Comment by satomic** [comment]
@reasonerjt thanks, GJ
