### ISSUE TITLE
why i can't install with clair?

### ISSUE THREAD

**Issue by 1412904892** [goharbor/harbor#5665]
./install.sh --with-clair
Note: Please set hostname and other necessary attributes in harbor.cfg first. DO NOT use localhost or 127.0.0.1 for hostname, because Harbor needs to be accessed by external clients.

I have set hostname and others in harbor.cfg.

**Comment by reasonerjt** [comment]
@1412904892 
The code that prints the message looks like this:
```
# The hostname in harbor.cfg has not been modified
if grep 'hostname = reg.mydomain.com' &> /dev/null harbor.cfg
then
	warn "$usage"
	exit 1
fi
```

**Comment by reasonerjt** [comment]
@1412904892 
Without we being able to access your env and debug for you.  You have to do the debug and try to figure out ...

**Comment by 1412904892** [comment]
![image](https://user-images.githubusercontent.com/16586723/44328228-96af0380-a493-11e8-9878-e6dbced7b70f.png)
you see, I have set hostname.
![image](https://user-images.githubusercontent.com/16586723/44328304-ce1db000-a493-11e8-8ada-84923030d60e.png)

**Comment by reasonerjt** [comment]
1. Make sure there's only one `harbor.cfg` on your host.
2. Run `grep 'hostname = reg.mydomain.com' harbor.cfg`

**Comment by reasonerjt** [comment]
@1412904892 Is that all the output of install.sh?  What build are you using?

**Comment by wy65701436** [comment]
@1412904892 can you upload the harbor.cfg?

**Comment by cd1989** [comment]
Also https is required ?

**Comment by reasonerjt** [comment]
@cd1989 For Clair it's not required to setup with https
