### ISSUE TITLE
admin update user password api

### ISSUE THREAD

**Issue by slash-l** [goharbor/harbor#5676]
admin update user password api is:
put /users/{user_id}/password
the old password is required, but admin can't know user's old password, so the api is not avalible. I think the old password input param is not required.
thanks!

**Comment by reasonerjt** [comment]
It's not required when admin is updating other user's password.

I'll update the doc to clarify.

**Comment by reasonerjt** [comment]
Updated the doc in #5877

**Comment by slash-l** [comment]
![image](https://user-images.githubusercontent.com/12329604/45669450-c890a580-bae5-11e8-853d-8eedd08efd42.png)

I use version 1.5+, but still require old_password.
which version should I use? 
Thank you!
