### ISSUE TITLE
v1.6.0 用户管理中用户信息不能修改，不能显示注释

### ISSUE THREAD

**Issue by Debris2017** [goharbor/harbor#5687]
当前版本： v1.6.0-40f058fa
问题描述：
1、在用户管理模块中，创建用户有注释这个字段，但创建保存后没有显示出来。
2、创建好的用户无法修改邮件地址，只能操作'重置密码'跟删除

**Comment by reasonerjt** [comment]
@Debris2017 User can update the profile of himself.
The issue is admin cannot update it?

**Comment by reasonerjt** [comment]
It's the design that admin can not update other user's profile.
