### ISSUE TITLE
‘复制管理’中的复制功能无用

### ISSUE THREAD

**Issue by bluespanda** [goharbor/harbor#5688]
当前版本： v1.6.0-40f058fa
问题描述：
1、在复制管理模块中，复制了一条规则后没有了后续，没有粘贴之类的
2、在新建好的规则中，选中一条规则后，当前选中状态无法取消。仓库管理中的选中状态是可以取消的。

**Comment by reasonerjt** [comment]
您好，从描述中不太理解您的问题是什么能否详细说明一下？

**Comment by ywk253100** [comment]
It's `Replicate` not `Copy`, for more information please refer to the user guide https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#starting-a-replication-manually.

**Comment by Debris2017** [comment]
好吧，中文歧义。建议改个名称吧

**Comment by Debris2017** [comment]
在新建好的规则中，选中一条规则后，当前选中状态无法取消。仓库管理中的选中状态是可以取消的。
这个问题但是是存在的

**Comment by cd1989** [comment]
@Debris2017 Why you want to cancel the selection state, any special reason ? . In my opinion, this page is mainly used to display replication policies and replication jobs, so it's reasonable to make one replication policy selected and display its related replication jobs in the following table.

**Comment by ywk253100** [comment]
Agree.
