### ISSUE TITLE
notary-server not working with harbor-v1.6.0-rc1

### ISSUE THREAD

**Issue by openxlab** [goharbor/harbor#5692]
1)Version of docker engine and docker-compose.
# docker --version
Docker version 18.06.1-ce, build e68fc7a
# docker-compose --version
docker-compose version 1.22.0, build f46880fe

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
[harbor.cfg.zip](https://github.com/goharbor/harbor/files/2308865/harbor.cfg.zip)

3)Log files, you can get them by package the /var/log/harbor/ .
[harbor.log.zip](https://github.com/goharbor/harbor/files/2308864/harbor.log.zip)

openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout ca.key \
  -x509 -days 365 -out ca.crt -subj "/emailAddress=admin@openxlab.com/C=CN/ST=JiangSu/L=NanJing/O=openxlab/OU=Dev/CN=harbor.openxlab.com"
openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout harbor.openxlab.com.key \
  -out harbor.openxlab.com.csr -subj "/emailAddress=admin@openxlab.com/C=CN/ST=JiangSu/L=NanJing/O=openxlab/OU=Dev/CN=harbor.openxlab.com"
openssl x509 -req -days 365 -in harbor.openxlab.com.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out harbor.openxlab.com.crt

./install.sh --with-notary --with-clair --with-chartmuseum

The notary-serve can not running
# cat /var/log/harbor/notary-server.log
Aug 22 11:34:43 172.18.0.1 notary-server[1431]: waiting for postgres://server:password@postgresql:5432/notaryserver?sslmode=disable to come up.
Aug 22 11:38:59 172.18.0.1 notary-server[1431]: waiting for postgres://server:password@postgresql:5432/notaryserver?sslmode=disable to come up.

**Comment by clouderati** [comment]
@openxlab do you happen to know if postgres starts (and perhaps relevant logs)?

**Comment by wy65701436** [comment]
as confirmed with @openxlab, it's an os specific issue(centos).

**Comment by wy65701436** [comment]
close.
