### ISSUE TITLE
Build ha harbor-registry, adminserver initialize fail , can not connect to aws rds

### ISSUE THREAD

**Issue by lxkaka** [goharbor/harbor#5698]
I built ha harbot-registry with two nodes, and I use aws rds to as my harbor db. The service run failed.
below is the detail

* docker version 18.06.0-ce, build 0ffa825
* docker-compose version 1.22.0, build f46880fe  

db conf in harbor.cfg shows:
```
#######Harbor DB configuration section#######

#The address of the Harbor database. Only need to change when using external db.
db_host = xxxxxxx.amazonaws.com.cn

#The password for the root user of Harbor DB. Change this before any production use.
db_password = xxxxx

#The port of Harbor database host
db_port = 3306

#The user name of Harbor database
db_user = xxxx

##### End of Harbor DB configuration#######
```
The adminserver log shows:
```
Aug 22 18:46:22 ip-xxxxx.cn-north-1.compute.internal adminserver[1051]: 2018-08-22T10:46:22Z [INFO] initializing system configurations...
Aug 22 18:46:22 ip-xxxxx.cn-north-1.compute.internal adminserver[1051]: 2018-08-22T10:46:22Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Aug 22 18:46:22 ip-1xxxxx.cn-north-1.compute.internal adminserver[1051]: 2018-08-22T10:46:22Z [INFO] initializing database: type-MySQL host-xxxxxx.rds.cn-north-1.amazonaws.com.cn port-3306 user-xxx database-registry
Aug 22 18:46:22 ip-xxxx.cn-north-1.compute.internal adminserver[1051]: 2018-08-22T10:46:22Z [FATAL] [main.go:46]: failed to initialize the system: Error 1146: Table 'registry.alembic_version' doesn't exist
```
How should I handle this problem ? thanks in advance

**Comment by reasonerjt** [comment]
@lxkaka was it fixed?

**Comment by lxkaka** [comment]
@reasonerjt yes, the db problem was fixed.
I have two harbor server and in front of them is the load balancer and the two nodes run well.
 docker login failed when the login request distribute in the two nodes. If I stop one of the two nodes, docker login success.
I know login process includes 3 requests
the first request (return 401) in node 1
```
Aug 23 11:16:32 xxxxx.compute.internal proxy[1099]: xxxxx- "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.007 0.007 .
``` 
the second request(return 200) in node 2
```
Aug 23 11:16:33 xxxxx.compute.internal proxy[1051]: xxxxx - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 893 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.035 0.035 .
```
the third request(return 401) in node 1, this request aleady has the auth token.
```
Aug 23 11:16:33 xxxx.compute.internal proxy[1099]: xxxx - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.003 0.003 .
```
When this process happen in the same node, login has no problem.
Is there any other auth data stored in local ?

**Comment by lxkaka** [comment]
@reasonerjt thank you! I also found the problem. The reason is what you said, the key and cert is different.

**Comment by reasonerjt** [comment]
@lxkaka any further problems?  Since the problem described in this issue has been fixed, I suggest you open a new one to cover the new problem you are seeing.

**Comment by xuejipeng** [comment]
which version fix it? i'am harbor 1.5.2 is  still.

**Comment by Leiyy1234** [comment]
> @reasonerjt yes, the db problem was fixed.
> I have two harbor server and in front of them is the load balancer and the two nodes run well.
> docker login failed when the login request distribute in the two nodes. If I stop one of the two nodes, docker login success.
> I know login process includes 3 requests
> the first request (return 401) in node 1
> 
> ```
> Aug 23 11:16:32 xxxxx.compute.internal proxy[1099]: xxxxx- "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.007 0.007 .
> ```
> 
> the second request(return 200) in node 2
> 
> ```
> Aug 23 11:16:33 xxxxx.compute.internal proxy[1051]: xxxxx - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 893 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.035 0.035 .
> ```
> 
> the third request(return 401) in node 1, this request aleady has the auth token.
> 
> ```
> Aug 23 11:16:33 xxxx.compute.internal proxy[1099]: xxxx - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.003 0.003 .
> ```
> 
> When this process happen in the same node, login has no problem.
> Has any other auth data stored in local ?

how did you solve this aws-rds error? I got this problem either...

**Comment by Leiyy1234** [comment]
> @reasonerjt yes, the db problem was fixed.
> I have two harbor server and in front of them is the load balancer and the two nodes run well.
> docker login failed when the login request distribute in the two nodes. If I stop one of the two nodes, docker login success.
> I know login process includes 3 requests
> the first request (return 401) in node 1
> 
> ```
> Aug 23 11:16:32 xxxxx.compute.internal proxy[1099]: xxxxx- "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.007 0.007 .
> ```
> 
> the second request(return 200) in node 2
> 
> ```
> Aug 23 11:16:33 xxxxx.compute.internal proxy[1051]: xxxxx - "GET /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 200 893 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.035 0.035 .
> ```
> 
> the third request(return 401) in node 1, this request aleady has the auth token.
> 
> ```
> Aug 23 11:16:33 xxxx.compute.internal proxy[1099]: xxxx - "GET /v2/ HTTP/1.1" 401 87 "-" "docker/18.06.0-ce go/go1.10.3 git-commit/0ffa825 kernel/4.9.93-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.0-ce \x5C(darwin\x5C))" 0.003 0.003 .
> ```
> 
> When this process happen in the same node, login has no problem.
> Has any other auth data stored in local ?

how did you solve this aws-rds error? I got this either
[main.go:46]: failed to initialize the system: Error 1146: Table 'harbor_registry.alembic_version' doesn't exist
@lxkaka
