### ISSUE TITLE
Delete image signed and 

### ISSUE THREAD

**Issue by robrosillo** [goharbor/harbor#5699]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.
Client Version:         1.12.6
Server Version:         1.12.6

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.
3)Log files, you can get them by package the /var/log/harbor/ .

I have deleted a tag called repo/java:1.8.RELEASE signed from a repository in harbor. After that, I have deleted the key root from my computer. After that, I have decided to push and signed again the same tag in the project/repository repo/java using docker command  and when I run "docker push repo/java:1.8.RELEASE" it shows me a error message. It needs the same keys as the previous one. I suppossed that i could create a new key root, etc for this tag.

Signing and pushing trust metadata
ERRO[0000] couldn't add target to targets: could not find necessary signing keys, at least one of these keys must be available: 88bddab31b0bbe7e95f177e00e5def13b77c8c42c7ac240c22a91f8cd4ff6754 
Failed to sign "registry.harbor.corp/produban/javase":1.8.RELEASE - could not find necessary signing keys, at least one of these keys must be available: 88bddab31b0bbe7e95f177e00e5def13b77c8c42c7ac240c22a91f8cd4ff6754
Error: could not find signing keys for remote repository registry.harbor.corp/produban/javase, or could not decrypt signing key: could not find necessary signing keys, at least one of these keys must be available: 88bddab31b0bbe7e95f177e00e5def13b77c8c42c7ac240c22a91f8cd4ff675

If I don't have that  signing keys what could I do?

**Comment by reasonerjt** [comment]
This  seems a design issue of notary, a GUN (repo) maps to a private key. 
So in your case maybe some "key delegation" would work, but I suggest you reach out to notary's repo and doc for confirmation.

**Comment by robrosillo** [comment]
Hi,
o.k. then. I will try it.
