### ISSUE TITLE
Enhancement of replication

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#5704]
For the moment, replication replicate images to remote registry with same project name and same tag. ( correct me if I'm wrong)

There are user scenarios that:

- replicate images to to another project in target registry
- retag images during replication. For example, `app:v1.0-stg --> app:v1.0`

So I propose that:

1. Support replicate to another project in target registry
2. Provide advance configure when create replication policy, allow user to configure retag pattern.

**Comment by steven-zou** [comment]
@cd1989 

  We're considering some improvements of replication. Please stay tuned.

**Comment by kokarn** [comment]
Now with the improved replication stuff like this would be very helpful. Is it better to keep this closed and open a new ticket or re-open this one?
