### ISSUE TITLE
Clair updaters stuck in a loop due to change of alpine URL.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5710]
Caused by: https://github.com/coreos/clair/issues/593
To mitigate the impact to CI we disabled the updaters in configuration, need to fix it before 1.6 release, either by a new release of Clair or we patch it in our build.

Also re-enable the updaters in configuration file.

**Comment by magerx** [comment]
### sad

**Comment by fenghui2013** [comment]
@reasonerjt  clair v2.0.5 has been released and fixed it. When does harbor fix it?

**Comment by reasonerjt** [comment]
Fixed in #5783 #5785 #5787
