### ISSUE TITLE
network harbor_harbor not found

### ISSUE THREAD

**Issue by fatg1988** [goharbor/harbor#5715]
[Step 4]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
Creating harbor-log ...
Creating harbor-db ...
Creating registry ...
Creating redis ...
Creating harbor-adminserver ...

ERROR: for registry  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for harbor-adminserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for harbor-db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mysql  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for registry  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

journalctl docker

dockerd-current[27002]: time="2018-08-23T15:09:29.034263695+08:00" level=warning msg="0f28cdfe89888b4a8c78b4b43087d338b81806ca01b819309f9294c31ff5f42c cleanup: failed to unmount secrets: invalid argument"
dockerd-current[27002]: time="2018-08-23T15:09:29.734595635+08:00" level=error msg="Handler for GET /v1.22/networks/harbor_harbor returned error: network harbor_harbor not found"
dockerd-current[27002]: time="2018-08-23T15:09:30+08:00" level=info msg="Firewalld running: false"
oci-systemd-hook[11281]: systemdhook <debug>: 4750d44eb6a5: Skipping as container command is /bin/sh, not init or systemd
oci-umount[11282]: umounthook <debug>: prestart container_id:4750d44eb6a5 rootfs:/data9/lib/docker/overlay/42f9b4171449a93e6d25996c2e612bf5fc09daaaade152f1eb144cc223a67746/merged

docker info

Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: systemd
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64

**Comment by reasonerjt** [comment]
this is due to the inresponsiveness of your docker daemon, try restart it.

And you may want to upgrade dockerd to a later version.

**Comment by reasonerjt** [comment]
@fatg1988 any update?

**Comment by Szpark** [comment]
I have `docker-ce-cli-20.10.1` and still bumping into `Error response from daemon: network harbor_harbor not found`. Restarting docker didn't help

```
% sudo docker-compose up -d
[+] Running 17/18
 ⠿ Network harbor_harbor-clair        Created                                                                                                         0.2s
 ⠿ Network harbor_notary-sig          Created                                                                                                         0.2s
 ⠿ Network harbor_harbor-notary       Created                                                                                                         0.2s
 ⠿ Network harbor_harbor-chartmuseum  Created                                                                                                         0.2s
 ⠿ Container harbor-log               Starting                                                                                                        0.5s
 ⠿ Container registryctl              Created                                                                                                         0.1s
 ⠿ Container redis                    Created                                                                                                         0.1s
 ⠿ Container harbor-portal            Created                                                                                                         0.1s
 ⠿ Container registry                 Created                                                                                                         0.1s
 ⠿ Container harbor-db                Created                                                                                                         0.1s
 ⠿ Container chartmuseum              Created                                                                                                         0.1s
 ⠿ Container clair                    Created                                                                                                         0.1s
 ⠿ Container notary-signer            Created                                                                                                         0.1s
 ⠿ Container harbor-core              Created                                                                                                         0.1s
 ⠿ Container clair-adapter            Created                                                                                                         0.1s
 ⠿ Container notary-server            Created                                                                                                         0.1s
 ⠿ Container harbor-jobservice        Created                                                                                                         0.1s
 ⠿ Container nginx                    Created                                                                                                         0.1s
Error response from daemon: network harbor_harbor not found
```
