### ISSUE TITLE
helm install harbor docs 404

### ISSUE THREAD

**Issue by mancosun** [goharbor/harbor#5719]
helm install harbor docs 404

**Comment by reasonerjt** [comment]
@mancosun  which link?

**Comment by mancosun** [comment]
**<https://github.com/goharbor/harbor/tree/master/contrib/helm/harbor>**
k8s install harbor  use helm,link in "https://github.com/goharbor/harbor/blob/master/docs/kubernetes_deployment.md":

**Comment by ywk253100** [comment]
The Harbor chart has moved to a new repository https://github.com/goharbor/harbor-helm. The link in the doc should be updated.

**Comment by ywk253100** [comment]
Fixed in #5728.
