### ISSUE TITLE
Chartmuseum can not connect to customized s3 storage

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#5725]
Install harbor with --with-chartmuseum option
Create and delete a project in harbor 
Got the error
{“error”:“NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors”}

Need to refer https://github.com/goharbor/harbor/pull/5644/files to add ca to the container of chartmuseum

**Comment by steven-zou** [comment]
Code merged in PR https://github.com/goharbor/harbor/pull/5740
