### ISSUE TITLE
[Question] clair - update definitions

### ISSUE THREAD

**Issue by choman** [goharbor/harbor#5726]
I remember at one time there was a doc on how to update the definitions for clair.

Can someone point me to the documentation that explains this

**Comment by abhishiktvv** [comment]
https://github.com/goharbor/harbor/blob/master/docs/import_vulnerability_data.md

**Comment by reasonerjt** [comment]
Thanks @abhishiktvv 
@choman I'm closing the issue as it's answered.

**Comment by choman** [comment]
awesome thanks.   however I was trying to dig into this but I am getting lost.  

This document, while very descriptive does not point to where to get the "sql" files to import.  
Researching clair's github page: https://github.com/coreos/clair/blob/master/Documentation/drivers-and-data-sources.md point to site that use xml files.   I cannot find
