### ISSUE TITLE
Can Harbor HA use MySQL 5.5 cluster instead of MariaDB?

### ISSUE THREAD

**Issue by zoiezy** [goharbor/harbor#5741]
The latest version of Harbor HA use MariaDB 10.2.10.
Can I  use MySQL 5.5 database docking harbor? 
Thank you.

**Comment by wy65701436** [comment]
from harbor v1.6.0, we have migrated DB to Postgresql.

**Comment by reasonerjt** [comment]
It's not tested @zoiezy

**Comment by zoiezy** [comment]
which version of MySQL does Harbor 1.5 use before?

**Comment by zoiezy** [comment]
And according to the document here: https://github.com/goharbor/harbor/blob/master/docs/high_availability_installation_guide.md#prerequisites
HA cluster still use harbor 1.5, right?

**Comment by reasonerjt** [comment]
That document is deprecated.  And it was a reference, you can only rely on community for support if you choose that path.

**Comment by reasonerjt** [comment]
Closing the issue as it's answered question.
