### ISSUE TITLE
Failed to ping endpoint.

### ISSUE THREAD

**Issue by xiaodeer** [goharbor/harbor#5747]
I create 2 registry,  one is 70, anther is 71, but when I create new Endpoint, it test connection failed.
I use http as the login. Harbor version is 1.5, docker version is 17.03, docker-compose version is 1.21.2.
![harborendpoint](https://user-images.githubusercontent.com/13516560/44709570-8bd02080-aadc-11e8-8698-6e5ec5425040.png)

**Comment by xiaodeer** [comment]
UI log is:
Aug 28 16:08:44 bogon ui[100688]: 2018-08-28T08:08:44Z [ERROR] [target.go:65]: failed to ping target: Head http://x.x.x.71/v2/: Get http://dk-repo.xxx.com.cn/service/token?service=harbor-registry: dial tcp: lookup dk-repo.xxx.com.cn: no such host

**Comment by cd1989** [comment]
Does host name `dk-repo.xxx.com.cn` resolvable from UI container ?

**Comment by xiaodeer** [comment]
I add the dk-repo.xxx.com.cn in host, not in UI container. Should I add it in UI container by myself?

**Comment by ywk253100** [comment]
Yes, you should make sure the domain name can be resolved inside the container.

**Comment by xiaodeer** [comment]
How to add the domain name. the UI container have not vi/vim/sed command.

**Comment by cd1989** [comment]
`echo "127.0.0.1 foo.bar" >> /etc/hosts`

**Comment by xiaodeer** [comment]
Thanks! I used the ip-adress instead of hostname. It work now. Please close the issue.

**Comment by itsecforu** [comment]
what to do with the same issue on k8s? wich one pod need to set up via hosts file and how to become root to do that?
