### ISSUE TITLE
Failed to ping email server - unrecognized authentication type

### ISSUE THREAD

**Issue by gischethans** [goharbor/harbor#5757]
I am unable to send a test email from my new Harbor instance. We have an SMTP server that requires no authentication and does not use SSL.

**Expected behaviour and actual behaviour:**
Expected: Email test succeeds
Actual Behaviour: Error message (both in UI and ui.log) - failed to ping email server: 504 5.7.4 Unrecognized authentication type

**Versions:**
- harbor version: 1.5.2-8e61deae
- docker engine version: 18.06.1-ce, build e68fc7a
- docker-compose version: 1.22.0, build f46880fe

**Comment by reasonerjt** [comment]
Please let us know what Email server you are using and attach all the log files.

**Comment by gischethans** [comment]
I am not sure what is the email server - guess it's some Microsoft solution, could be a legacy one.

I will share the log files once I review them - do you need all the log files or specific ones? Little concerned about how to anonymize content in those log files.

**Comment by reasonerjt** [comment]
proxy.log and ui.log should be all we need, thanks.
We don't have bandwidth to verify against all Email servers, so it's expected that the community help us in that area.

**Comment by gischethans** [comment]
I have attached the log files by redacting machine name and IP addresses. Please let me know if you need any more info. I will also reply back if I find the exact mail server that is being used.

[proxy.log](https://github.com/goharbor/harbor/files/2331861/proxy.log)
[ui.log](https://github.com/goharbor/harbor/files/2331862/ui.log)

**Comment by gischethans** [comment]
I approached our IT Department to know the email server details and got this reply - 

> The SMTP servers behind <mail server> are currently running Exchange 2010 SP3. 
> 
> The servers themselves support implicit SSL/TLS and explicit SSL/TLS, but some software confuses the two and only gives one setting and doesn't tell what it is trying to use. You may also see explicit called StartTLS. You will need to make sure they support TLS v1.2 as all others are deprecated. 
> 
> You may be limited to StartTLS through <mail server> over port 25. Authentication is not required for StartTLS typically.

**Comment by gischethans** [comment]
@reasonerjt, while the Harbor teams work on a possible fix, could you suggest any other email server software/configuration that might work?

**Comment by clouderati** [comment]
Postfix is a good starting point, but is far more complex to configure than Exchange 2010. Do you have any experience configuring an MTA?

**Comment by gischethans** [comment]
Thanks, for the suggestion @clouderati. I am not familiar with the email server configuration - our IT department handles that. Also, since we now use LDAP authentication for Harbor, until email alerts for various actions are available in Harbor, we don't have a reason to get it to work. However, I would suggest that this issue is kept open since a fix could help other Harbor users.

**Comment by clouderati** [comment]
@gischethans – definitely reasonable until we can confirm that StartTLS works (or doesn't). Thanks for reporting the issue.

**Comment by v1k0d3n** [comment]
any status on this issue? i seem to be running into the same (or similar?) issue when using office365. it seems that office365 is a reasonably sized solution to have working with Harbor, but no matter what combination i use...it just doesn't seem to work. if settings are correct, according to MS, I get the error `Failed to verify mail server with error: failed to ping email server .`. not sure where to start with this one, because a dig through the logs show nothing, and when accessing the containers i can properly curl and get an icmp echo response from `outlook.office365.com`.

**Comment by alvisisme** [comment]
I use [hmailserver 5.6.7](hMailServer) to setup my mail server(requires no smpt authentication and does not use SSL), working well with mircosoft outlook.
When I config the harbor, it shows **"failed to ping email server"**.
The harbor core log shows：
> "failed to ping email server: 504 Authentication mechainism not supported."

The hMailServer log shows：
> "RECEIVED: AUTH CRAM-MD5"
> "SENT: 504 Authentication mechanism not supported."
> "RECEIVED: *"
> "SENT: 503 Bad sequence of commands"

It seems like that harbor default smtp authentication mechanism is  CRAM-MD5(?),  which is not supported by hMailServer.

Is there any way to change the harbor smtp authentication mechanism or disable it?

Tested with 
* Harbor version 1.5 and 1.7
* hMailServerversion v5.6.7

**Comment by EmteZogaf** [comment]
This issue is still not fixed. We get the same errors:
```
==> /var/log/harbor/core.log <==
[ERROR] [/common/config/manager.go:192]: failed to get key email_password, error: the configure value is not set
[ERROR] [/common/config/manager.go:192]: failed to get key email_identity, error: the configure value is not set

[ERROR] [/core/api/email.go:113]: failed to ping email server: 535 5.7.0 Authentication failed
[ERROR] [/common/api/base.go:69]: POST /api/email/ping failed with error: {"code":400,"message":"failed to ping email server"}
```

Please reopen!

**Comment by tiger5226** [comment]
I am also still seeing the same error in my harbor logs. Please reopen.
```
Sep 11 07:26:31 ag-pvd-core.infra.dsone.3ds.com core[113671]: 2019-09-11T11:26:31Z [ERROR] [/core/api/email.go:113]: failed to ping email server: 504 5.7.4 Unrecognized authentication type
Sep 11 07:26:31 ag-pvd-core.infra.dsone.3ds.com core[113671]: 2019-09-11T11:26:31Z [ERROR] [/common/api/base.go:68]: POST /api/email/ping failed with error: {"code":400,"message":"failed to ping email server"}
Sep 11 07:26:31 ag-pvd-core.infra.dsone.3ds.com core[113671]: 2019/09/11 11:26:31 #033[1;44m[D] [server.go:2619] |  10.101.209.35|#033[43m 400 #033[0m|  12.581326ms|   match|#033[46m POST    #033[0m /api/email/ping   r:/api/email/ping#033[0m
```

**Comment by JerryCurl** [comment]
same issue here

**Comment by MScuti** [comment]
same issue when use office365

**Comment by SpeedBlack** [comment]
Hi,

Same issue when use Exchange.
Do you have any idea ?

Thansk !

**Comment by tiger5226** [comment]
No, this still needs to be reopened by the go-harbor team.

**Comment by zhangxpp** [comment]
same issue for QQ mail. 
![image](https://user-images.githubusercontent.com/18004694/70301201-b444df80-1834-11ea-9ed6-899592952a8b.png)
![image](https://user-images.githubusercontent.com/18004694/70301305-f837e480-1834-11ea-8815-f53fd194df3e.png)

harbor on k8s . Version v1.9.3-c80751b8

**Comment by tiger5226** [comment]
@heww anyway we can get this reopened?

**Comment by dishuihengxin** [comment]
the same issue when use office365.

**Comment by Eric-Fontana-Bose** [comment]
Why don't you support basic auth ? Then you would get all mail servers.

**Comment by tannnk** [comment]
Please reopen this issue.
I use an email server with no encryption and no authentication.

**Comment by xiak** [comment]
same issue

**Comment by fredbcode** [comment]
Same here

**Comment by glego** [comment]
Office 365 with starttls not working

**Comment by jeferson-ls-ribeiro** [comment]
Same here.

**Comment by Roia5** [comment]
Same for Exchange!

**Comment by fcmxmk** [comment]
Same here.
