### ISSUE TITLE
Harbor Ignore V2 v1Compatibility field

### ISSUE THREAD

**Issue by tunnyblock** [goharbor/harbor#576]
##### 1.下面是我直接用原生的API获取的manifests，里面有个v1Compatibility属性

![default](https://cloud.githubusercontent.com/assets/9509758/17010058/1c6fa8ac-4f33-11e6-9bf0-a1ebd3089406.png)
##### 2.我看api/repository.go里也有在解析这个属性的逻辑，应该是model/repo.go RepoItem没有相应的字段去接收这些属性引起的，不过GO语言不熟悉，我目前的修改方法是加个V1Compatibility字段直接去接收这个字符串，不作任何JSON解析！

![2](https://cloud.githubusercontent.com/assets/9509758/17010061/1f45d588-4f33-11e6-8c68-fe48a9443df7.png)

/

**Comment by reasonerjt** [comment]
@tunnyblock 对你个人的需求来说，你需要在UI上显示相关属性还是只需要API 返回V1的值

**Comment by tunnyblock** [comment]
@reasonerjt  我只需要API返回V1的值就行！
