### ISSUE TITLE
When does the online GC feature provide?

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#5760]
When does the online GC feature provide?

Thanks.

**Comment by wy65701436** [comment]
it's planed in the next release.

**Comment by Iverson-lena** [comment]
What version and when will it be released?

**Comment by clouderati** [comment]
Should land in v1.6, which we hope to release in the next few weeks. There's a release candidate available for testing, too.

**Comment by reasonerjt** [comment]
@Iverson-lena We have done some work in 1.6 timeframe and current plan is to provide it in 1.7
