### ISSUE TITLE
Switchun auth from db to ldap result in 500 when saving settings (1.6.0-rc2)

### ISSUE THREAD

**Issue by babs** [goharbor/harbor#5769]
**Expected behavior and actual behavior:**

When changing from db auth to ldap auth through web interface, test work bu save fails with a 500

**Steps to reproduce the problem:**
- Create a harbor install with default auth
- Log in and change auth settings to ldap, fill the infomation, save

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.6.0-rc2
- docker engine version: 18.06.1-ce
- docker-compose version: 1.22.0

**Additional context:**
```
==> /var/log/harbor/postgresql.log <==
Aug 30 12:16:31 postgresql[3872]: ERROR:  invalid byte sequence for encoding "UTF8": 0x00
Aug 30 12:16:31 postgresql[3872]: STATEMENT:  UPDATE "properties" SET "v" = $1 WHERE "id" = $2

==> /var/log/harbor/adminserver.log <==
Aug 30 12:16:31 adminserver[3872]: 2018-08-30T10:16:31Z [ERROR] [cfg.go:56]: failed to update system configurations: pq: invalid byte sequence for encoding "UTF8": 0x00
Aug 30 12:16:31 adminserver[3872]: 172.16.0.7 - - [30/Aug/2018:10:16:31 +0000] "PUT /api/configurations HTTP/1.1" 500 22
```

**Comment by clouderati** [comment]
Hi @babs – was this switch from local to LDAP auth performed on a fresh install of v1.6rc2, or an existing environment?

**Comment by wy65701436** [comment]
@babs I cannot reproduce it on my side.

Is it a fresh install or upgrade from the previous version?

**Comment by babs** [comment]
you're right, fresh install.
Install is done with default auth, then switched to ldap through web interface.

Side question but kind of related, is it possible to provide the CA for LDAP anyhow ?

**Comment by babs** [comment]
I updated the harbor.cfg to make harbor use ldap by `prepare` and filled `LDAP Group Admin DN` I can update fields.

That said `ldap_group_admin_dn` is missing from harbord.cfg template

**Comment by wy65701436** [comment]
@babs please update the ldap_group_admin_dn in UI(Configuration), it cannot be set in the harbor.cfg.

Did you resolve the DB issue?

**Comment by babs** [comment]
@wy65701436 it can, that's how I reconfigured my sandbox instance, I just added it to the harbor.cfg, prepared and restared the containers. (I looked at prepare, adminserver/env, html template and so on to find the clue about it)
Thing is when this field was empty, I had a 500. Once filed by prepare, submitting the conf was ok.
Even if it's not taken into consideration by the conf at start, as it's present in the ui html, it might have been saved when I submited the for to test once containers were restarted.
If it's the case, it can mean something I didn't try: emptying the field and resubmit, see if I still get a 500. If it's the case, it would mean that the field should either be mandatory or its emptyness have a small issue

**Comment by babs** [comment]
Update: I can now empty this field and save without 500.
I'll try to take a closer look after erasing completely my current sandbox

**Comment by steven-zou** [comment]
@babs 
  Thanks a lot for doing contributions to Harbor. We're calling more contributors/maintainers and I'm wondering if you're willing to be one of them?

**Comment by wy65701436** [comment]
close.
