### ISSUE TITLE
harbor web can not delete image? 

### ISSUE THREAD

**Issue by lxkaka** [goharbor/harbor#5770]
I tried to delete some images in harbo web, return 405
`{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}`

Is this action unsupported?

**Comment by clouderati** [comment]
Hi @lxkaka – deleting images from the UI is definitely supported. Can you please share the Harbor logs so we can take a look at what's going on?

**Comment by lxkaka** [comment]
@clouderati Thans for the reply. 
In the ui.log I found below:
`Aug 31 10:42:29 ip-xxxxx.cn-north-1.compute.internal ui[1051]: 2018-08-31T02:42:29Z [INFO] unauthorized`
In the proxy.log shows:
`Aug 31 10:42:29 ip-xxxx.cn-north-1.compute.internal proxy[1051]: xxxxx - "DELETE /api/repositories/zaihui/jaeger-agent HTTP/1.0" 401 1 "http://xxxx.com/harbor/projects/2/repositories" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" 0.007 0.007 .`
perhaps the unauthorized from aws s3?

**Comment by lxkaka** [comment]
@clouderati . I have found the problem, it is for lack of `delete` configuration.

**Comment by reasonerjt** [comment]
@lxkaka 

Let me clarify, so the root cause is a misconfiguration in you LB?

**Comment by lxkaka** [comment]
@reasonerjt Yes, deployed in AWS. The root cause is a misconfiguration in harbor config, that is storage conf miss `delete`.

**Comment by reasonerjt** [comment]
Is it in `config.yml` of the registry?

**Comment by lxkaka** [comment]
@reasonerjt  yep, the conf in the `config_ha.yml`(our harbor is ha).

**Comment by reasonerjt** [comment]
@lxkaka I'd suggest do not use the `config_ha.yml` as it will be deprecated.

It is possible to deploy HA based on docker-compose but we won't officially support it, you need to modify and mantain your docker-compose template files based on your env and requirement.
