### ISSUE TITLE
about replication rule

### ISSUE THREAD

**Issue by mikeweiwei** [goharbor/harbor#5775]
hi，bro
When adding a replication rule, it contains filter conditions, tag and repository. And then. When I add rules next time, filter conditions cannot be selected.

**Comment by mikeweiwei** [comment]
It seems to be a bug.

**Comment by ywk253100** [comment]
Which version are you using? Can this issue be reproduced every time?

**Comment by mikeweiwei** [comment]
the version is v1.5.1. Repeat every time.

**Comment by ywk253100** [comment]
Can you try v1.5.2 or v1.6.0-rc2?

**Comment by mikeweiwei** [comment]
ok，After test on the v1.6.0-rc2,  have't  Repeat.
Thanks for your reply.
