### ISSUE TITLE
Image retag function

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#5778]
**Is your feature request related to a problem? Please describe.**

For the moment, if I want to retag an image in Harbor with another tag, the only way seem to executing:

- docker pull ...
- docker tag ...
- docker push ...

This is very insufficient to pull a large image, it's more reasonable to achieve retag within the Harbor.

There are several scenarios when user may want to retag an image:

1. Retag fully tested images from `stage` project to `product` project
2. Retag a latest dated tag to `latest`, for example,  _app:201809011830_ --> _app:latest_
3. ...

**Describe the solution you'd like**

Harbor can provide an API to support retag an image, and may also to support it in UI. Then user can:

- Create new tag for an image
- Move images across projects within Harbor

**Describe the main design/architecture of your solution**

`POST /api/retag`
```
{
    "src_image": "stage/app:v1.0",
    "dest_image": "product/app:v1.0"
}
``` 

User can retag images to other project, or repo as long as it's permitted

For retag, there is no layer data transfer, so it should be efficient enough.

**Describe the development plan you've considered**

I'd like this can be achieved in v1.6.0. I will make a PR soon if it's accepted.

**Additional context**

**Comment by reasonerjt** [comment]
@cd1989 thanks a lot for the proposal.

1. For more flexibility and simplicity, how about provide an API to `PUT` a tag with given SHA256? 

2. It may be better to put the url of the target tag in the url of the API so it'd easier for auth checking based on url.  In future we may introduce a layer for auth checking

**Comment by cd1989** [comment]
@reasonerjt thanks for the suggestions.

> For more flexibility and simplicity, how about provide an API to PUT a tag with given SHA256?
I'm not clear of this, can this tag to another repo or project.

> It may be better to put the url of the target tag in the url of the API so it'd easier for auth checking based on url. In future we may introduce a layer for that.
You means API like:

`POST /api/repositories/<target-repo>/retag`
```
{
  "from":"stage/app:v1.0",
  "to": "v1.0",
}
```
or 

`POST /api/repositories/<target-repo>/tags/<target-tag>?from=<source-image>`
e.g. `/api/repositories/product/app/tags/v1.0?from=stage/app:v1.0`

**Comment by cd1989** [comment]
@reasonerjt Thank you for the details.

> `PUT /api/repositories/<target-repo>/tags/<target-tag>`

`PUT` is commonly used to update something, here it's tag. But what the API want to do is to create, so I think `POST` is better.

About the `gap` problem, I agree it's a problem and digest is better.

**Comment by cd1989** [comment]
So how about:

```
POST /api/repositories/<target-repo>/tags/<target-tag>
{
	"repo": "stage/app",
	"digest": "sha256:9e2c9d5f44efbb6ee83aecd17a120c513047d289d142ec5738c9f02f9b24ad07",
}
```

**Comment by steven-zou** [comment]
@cd1989 

If the operation is creating a new tag of the repo, I think it should be
```
POST /api/repositories/<target-repo>/tags
{
	"src_repo": "stage/app",
	"src_digest": "sha256:9e2c9d5f44efbb6ee83aecd17a120c513047d289d142ec5738c9f02f9b24ad07",
      "tag: <target-tag>
}
```

**Comment by steven-zou** [comment]
@cd1989 

As you're doing the implementation of this feature, I'll assign you as the owner of this proposal.

**Comment by cd1989** [comment]
> I don't think it's necessary to include the src_repo in the request.
What I want to achieve is to retag an image to:
- a new tag in the same repo
- a tag in a new repo

To retag across repos, it's necessary to specify the source repo

**Comment by cd1989** [comment]
In 09/05's community conf call, most people prefer the following API, so the latest API would look like:

```
POST /api/repositories/<repo-name>/tags

{
    "tag": "v1.0",
    "src_image": "stage/app:sha256...",
}
```

Also there is voice to add a `override` parameter to control whether to override the target image if already exists. So another option is:

```
POST /api/repositories/<repo-name>/tags

{
    "tag": "v1.0",
    "src_image": "stage/app:sha256...",
    "override": true
}
```

**Comment by cd1989** [comment]
How can we sign the new tag with Notary in the retag function ? Can we achieve this, I don't know enough about Notary in Harbor yet, anyone have any idea ?

**Comment by reasonerjt** [comment]
We can't as the private key has to be stored offline, and I think we can leave it for future.

**Comment by cd1989** [comment]
![image](https://user-images.githubusercontent.com/16573984/46817324-7b84b400-cdb1-11e8-9856-2f969d92b495.png)

![image](https://user-images.githubusercontent.com/16573984/46817273-66a82080-cdb1-11e8-87b7-5051a5c7d468.png)

**Comment by steven-zou** [comment]
@lweitzman 

Please review the UI design for the retag function. Thanks!

**Comment by reasonerjt** [comment]
This has been fixed, closing.
