### ISSUE TITLE
How to make adminserver use customed database name rathe than registry?

### ISSUE THREAD

**Issue by ctriple** [goharbor/harbor#5796]
I try to modify like this, but it not work (my version is 1.5.2, so the config line is mysql)

file: common/templates/adminserver/env

POSTGRESQL_DATABASE=registry

**Comment by cd1989** [comment]
The `registry` database is created in the db image by default. You should create another custom db manually.

https://github.com/goharbor/harbor/blob/v1.5.2/make/photon/db/registry.sql#L2

**Comment by ctriple** [comment]
thanks, it worked.
