### ISSUE TITLE
Proposal: a way to inject enterprise root CA for ldap binding

### ISSUE THREAD

**Issue by babs** [goharbor/harbor#5797]
**Is your feature request related to a problem? Please describe.**
I didn't found a way in the doc to inject corporate CA into ldap related container to be able to keep check certificate option checked.

**Describe the solution you'd like**
Maybe a folder used as volume to easily embed corporate root CA in the ldap related 
(or all) containers, or kind like the way custom certificate are provided for https activation, specifying a file path in harbor.cfg

**Comment by babs** [comment]
According to https://golang.org/src/crypto/x509/root_linux.go
it might be a matter of appending the provided file at the right place, or adding it to the proper folder and recreating the ca-bundle (depending on the underlying linux distro's way of managing CAs)

**Comment by steven-zou** [comment]
@babs 
Thanks for submitting a proposal to Harbor. I think it's a good one. Are you willing to implement it and contribute back to the community?

**Comment by babs** [comment]
@steven-zou why not, I'll take a look, I first need to get the build up and running and understand how it's setup.

**Comment by roccoq** [comment]
@babs How do you plan implementing? To me it seems one would need to generate new docker images with the certificates and hashed sym links installed using this method, Perhaps its possible to /etc/ssl/certs as a volume for each docker image and use the prepare.sh script to copy and sym link additional enterprise CA certs in that volume.

**Comment by babs** [comment]
I have no idea right know on the implementation to take (time taken by another task :/)
