### ISSUE TITLE
Synchronize with external registries

### ISSUE THREAD

**Issue by Erkak** [goharbor/harbor#580]
Hello,

What about the feature that could allow to synchronize/replicate images FROM external registries like DockerHub? Is it under consideration? Will it be implemented in future?

**Comment by reasonerjt** [comment]
It should be easy, just a batch operation
But other registry can not trigger webhook on Harbor so when the image is updated, Harbor will not be notified.
Will this be helpful?

**Comment by Erkak** [comment]
> But other registry can not trigger webhook on Harbor so when the image is updated, Harbor will not be notified.
I think it could be solved by regular checks whether image is updated via some kind of job of scheduler implemented in Harbor. What do you think about it?

**Comment by hainingzhang** [comment]
Hi Erkak, in the case of sync from docker hub, it is mostly like a cache for local users. Is there any other use case for this feature? We can consider putting this into our roadmap if the requirement is more general. @Erkak

**Comment by reasonerjt** [comment]
This issue essentially asks for support for pull-based replication, it's a valid requirement, but we are not ready to provide it in near future.

**Comment by ptone** [comment]
A relevant proposal for those finding this issue
https://github.com/goharbor/community/blob/master/proposals/Content-Replication-ng.md

**Comment by ywk253100** [comment]
Completed. You can try it with the maser branch.
