### ISSUE TITLE
http://xxx/api/repositories/xxx/xxx/tags?detail=1 sometime very slowly

### ISSUE THREAD

**Issue by QinXiao2017** [goharbor/harbor#5818]
http://xxx/api/repositories/xxx/repo_name/tags?detail=1, sometime very slowly.
sometime it can response in 1s, but sometimes, it needs 8s or  10s.
with different repo_name, this api spend time is differ greatly, with 1s and 10s.

**Versions:**
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
0bd512411c14        vmware/nginx-photon:v1.4.0                      "nginx -g 'daemon off"   5 days ago          Up 5 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
37e32f1a427d        vmware/harbor-jobservice:v1.4.0                 "/harbor/start.sh"       5 days ago          Up 5 days                                                                              harbor-jobservice
e99c66f0b13b        vmware/harbor-db:v1.4.0                         "/usr/local/bin/docke"   5 days ago          Up 5 days           3306/tcp                                                           harbor-db
ef811657810d        vmware/harbor-ui:v1.4.0                         "/harbor/start.sh"       5 days ago          Up 5 days                                                                              harbor-ui
91d2217c5b0e        vmware/registry-photon:v2.6.2-v1.4.0            "/entrypoint.sh serve"   5 days ago          Up 5 days           5000/tcp                                                           registry
85ef0ff7925d        vmware/harbor-adminserver:v1.4.0                "/harbor/start.sh"       5 days ago          Up 5 days                                                                              harbor-adminserver
9405511f513d        vmware/harbor-log:v1.4.0                        "/bin/sh -c /usr/loca"   5 days ago          Up 14 hours         127.0.0.1:1514->10514/tcp

**Comment by reasonerjt** [comment]
@QinXiao2017 which version of Harbor are you seeing this issue?

**Comment by ywk253100** [comment]
Try the latest version of Harbor, the performance of this API has been optimized.
