### ISSUE TITLE
How long is the harbour clair database updated?

### ISSUE THREAD

**Issue by wanshaoyuan** [goharbor/harbor#5821]
I don't know how long the harbor's clair database will be automatically updated, and whether there is a way to manually trigger the update？

Thank you！！！

**Comment by jw-s** [comment]
If you're using the helm chart: it can be configured here - https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L247 or clair default being https://github.com/coreos/clair/blob/master/cmd/clair/config.go#L63

**Comment by wanshaoyuan** [comment]
@jw-s Thank you 。
