### ISSUE TITLE
docker login got unauthorized with Docker-Client/18.06.1-ce

### ISSUE THREAD

**Issue by VinceCOT** [goharbor/harbor#5831]
I've setup a fresh install of Harbor with clair on my server (Debian 9) with the following docker version :

  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Docker stack :

clair                /docker-entrypoint.sh            Up      6060/tcp, 6061/tcp        
clair-db             /entrypoint.sh postgres          Up      5432/tcp                  
harbor-adminserver   /harbor/start.sh                 Up                                
harbor-db            /usr/local/bin/docker-entr ...   Up      3306/tcp                  
harbor-jobservice    /harbor/start.sh                 Up                                
harbor-log           /bin/sh -c /usr/local/bin/ ...   Up      127.0.0.1:1514->10514/tcp 
harbor-ui            /harbor/start.sh                 Up                                
nginx                nginx -g daemon off;             Up      0.0.0.0:8081->80/tcp      
redis                docker-entrypoint.sh redis ...   Up      6379/tcp                  
registry             /entrypoint.sh serve /etc/ ...   Up      5000/tcp    

I use a reverse nginx proxy for SSL and forward http requests to harbor-proxy through the port 8081 with the following configuration :

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate /etc/letsencrypt/live/reg.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/reg.mydomain.com/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA384';
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=31536000";

    client_max_body_size 0
    server_name     reg.mydomain.com;
    location / {
        proxy_pass      http://localhost:8081;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name reg.mydomain.com;
    return 301 https://$server_name$request_uri;
}
```

I can access to the web ui and log in without any problem.
I've tried to login with docker client 18.03 and push an image and everything works fine too.
Then, I've upgraded my docker client to 18.06.1 and now I can't log in anymore.

docker login -u admin -p Harbor12345 reg.mydomain.com
Error response from daemon: Get https://reg.mydomain.com/v2/: unauthorized: authentication required

When I look on the harbor logs files I've not been able to get more information than the registry.log :

Sep  5 14:27:23 172.26.0.1 registry[656]: time="2018-09-05T12:27:23.874162152Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host="localhost:8081" http.request.id=e58bb065-ea6f-4e8c-b843-27a7f03961f9 http.request.method=GET http.request.remoteaddr=172.26.0.1 http.request.uri="/v2/" http.request.useragent="docker/18.06.1-ce go/go1.10.3 git-commit/e68fc7a kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.1-ce \\(linux\\))" instance.id=6e4f4231-006b-48fd-8dec-b4fd210a3d9a service=registry version=v2.6.2 
Sep  5 14:27:23 172.26.0.1 registry[656]: 172.26.0.7 - - [05/Sep/2018:12:27:23 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.06.1-ce go/go1.10.3 git-commit/e68fc7a kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.1-ce \\(linux\\))"

I got 401 from the registry but it seems good for the others logs files so I don't know where this cause my authentification error especially when everything working good on 18.03.

If anybody has information to work around my issue it would be great.

Thanks in advance

**Comment by cd1989** [comment]
Please check also the harbor ui log, access token is issued there.

**Comment by VinceCOT** [comment]
@cd1989 Thank you for your quick reply but I've finally found the problem by looking on the registry config located at common/config/registry/config.yml.

The auth token parameter name _realm_ was set with http://reg.mydomain.com/service/token.
I've changed to https:// and it solve my issue but I don't really understand because my reverse nginx server configuration has http -> https redirection so it should worked...
Maybe it doesn't like 301 redirection

**Comment by reasonerjt** [comment]
It's the docker client to access the URL to fetch the token, so maybe this warrants an issue in docker's repo.

**Comment by VinceCOT** [comment]
@reasonerjt You're right it concerns the docker client and that's why I didn't have this issue when I was using the previous version 18.03.
