### ISSUE TITLE
I tried ·LDAP Group GID· to use cn, gid, dn, userid, uid, etc., all failed

### ISSUE THREAD

**Issue by paddy235** [goharbor/harbor#5838]
What can we help you?

我想设置ldap组成员为管理员，但是怎么设置都不对，是什么匹配规则？

首先 用户通过ldap可以正常登陆的。

I tried ·LDAP Group GID· to use cn, gid, dn, userid, uid, etc., all failed

What is the configuration rule?

harbor src code:
```
//Retrieve ldap related info in login to avoid too many traffic with LDAP server.
	//Get group admin dn
	groupCfg, err := config.LDAPGroupConf()
	groupAdminDN := strings.TrimSpace(groupCfg.LdapGroupAdminDN)
	//Attach user group
	for _, groupDN := range ldapUsers[0].GroupDNList {

		if len(groupAdminDN) > 0 && groupAdminDN == groupDN {
			u.HasAdminRole = true
		}

		userGroupQuery := models.UserGroup{
			GroupType:   1,
			LdapGroupDN: groupDN,
		}
		userGroupList, err := group.QueryUserGroup(userGroupQuery)
		if err != nil {
			continue
		}
		if len(userGroupList) == 0 {
			continue
		}
		userGroups = append(userGroups, userGroupList[0])
	}
	u.GroupList = userGroups
```

* harbor version:
`1.6.0.rc2`
* ldap server: 
[389 Directory Server](http://www.port389.org/)

* ldap group DN
`cn=harbor admin,ou=groups,dc=eccl,dc=app`

* ldap group member

![harbor-01](https://user-images.githubusercontent.com/19899767/45136450-c588e180-b1d6-11e8-8eeb-5967010e3dcd.png)

![harbor-02](https://user-images.githubusercontent.com/19899767/45136452-c9b4ff00-b1d6-11e8-8dcb-1ebbe47e56be.png)

**Comment by stonezdj** [comment]
Please try the latest version of harbor, we have fixed some bug
#5776  LDAP Group Admin DN case is treated case sensitively
It might be related to the issue
