### ISSUE TITLE
initdb: directory "/var/lib/postgresql/data" exists but is not empty

### ISSUE THREAD

**Issue by adomenech73** [goharbor/harbor#5841]
**Expected behavior and actual behavior:**
When installing harbor on Debian 9 some of the related containers (harbor-db, harbor-ui, clair) are restarting constantly with exit state `Exit 137`, I was expecting them to start only once without any problem. When checking logs of postgresql service I can see `initdb: directory "/var/lib/postgresql/data" exists but is not empty` message.

**Steps to reproduce the problem:**
Install harbor on Debian 9 and check the status of the containers with `docker-compose ps`

**Versions:**
Please specify the versions of following systems.
- harbor version: [v1.6.0-rc2]
- docker engine version: [18.06.1-ce, build e68fc7a]
- docker-compose version: [1.22.0, build f46880fe]

**Additional context:**
* **Workarround:** Everything seems to work fine if I add `PGDATA=/tmp` as environment variable for postgresql service
* **Log files:** Only redis log file is created and doesn't seems to be significative.
* **Installation command:** `./install.sh --with-notary --with-clair --with-chartmuseum`

**Comment by cd1989** [comment]
Have you tried cleanup the directory mounted to `/var/lib/postgresql/data` and reinstall, it's `/data/database` by default.

**Comment by adomenech73** [comment]
That did the trick thanks @cd1989

**Comment by AndreBritoKD** [comment]
that workaround worked fine, thanks @adomenech73
