### ISSUE TITLE
i can login from ui,but when use docker login,i got this message,Error response from daemon: 

### ISSUE THREAD

**Issue by laoliang330** [goharbor/harbor#5845]
docker login -u admin -p Harbor12345 https://127.0.0.1:81

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get http://127.0.0.1:81/v2/: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"

------------------------------------------------------
harbor version v1.5.2
docker version & docker swarm mode 
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by AgoodMITer** [comment]
try   docker login 127.0.0.1:81   and type in your account and password

**Comment by laoliang330** [comment]
seem result,
Error response from daemon: Get http://127.0.0.1:81/v2/: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"

**Comment by reasonerjt** [comment]
@laoliang330 looks like this is due to incomplete configuration when you try to customize the port.

Please refer to: https://github.com/goharbor/harbor/wiki/Harbor-FAQs
