### ISSUE TITLE
Add more api tests

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#5857]
Bases on the API test framework that introduced by @stonezdj, we need to add more API tests into travis to cover more functionalities.

1, User management
2, Project management
3, Clair/Notary
4, Label management
5, RBAC
6, Configuration
7, LDAP/LDAP group/UAA
8, Replication

**Comment by wy65701436** [comment]
Let's add these tests firstly.

1, add a new user.
2, add a new project.
3, delete a repo from the project.
4, sign an image.
5, scan an image.
6, scan all.
7, garbage collection.
8, Edit Project Creation.
9, add a label to repo.
10, add a new replication rule.
11, Project Level Policy Content Trust
12, Manage Project Member
13, Assign Sys Admin
14, List Helm Charts
15, User View Logs

**Comment by danfengliu** [comment]
**Progress:**
1, add a new user. ................................................(√)
2, add a new project. ...........................................(√)
3, delete a repo from the project.................... (√)
4, sign an image.
5, scan an image.
6, scan all.
7, garbage collection.
8, Edit Project Creation.
9, add a label to repo............................................(√)
10, add a new replication rule. .........................(√)
11, Project Level Policy Content Trust
12, Manage Project Member
13, Assign Sys Admin
14, List Helm Charts
15, User View Logs

**Comment by danfengliu** [comment]
16 test case have been added into API-DB test, because No.1 and No.2 were achieved in other test scripts, and sign image case was on-hold, so total test scrips in API-DB test is 13.

**Comment by wy65701436** [comment]
close it as done.
