### ISSUE TITLE
How to set proxy for replication?

### ISSUE THREAD

**Issue by zhoujianhui** [goharbor/harbor#5864]
I want replicate docker images from Harbor A to Harbor B through proxy. But I have not found any config to do it. I have try two method:
1、set HTTP_PROXY env - fail
2、set docker config.json proxies. It will auto set any container using proxy fail
So I want something like Clair's proxy config.

Thanks

**Comment by kmlxk** [comment]
I also want to use Harbor as a mirror server behind HTTP_PROXY. 
But it seems not work.
Then I checked log file ( vi /var/log/harbor/registry.log) and got this error :

Jun 13 15:41:53 172.19.0.1 registry[6598]: panic: Get http://xxx.m.daocloud.io/v2/: dial tcp 52.80.133.128:80: i/o timeout

version: Harbor 1.8.0 
CentOS 7.1 x64
Docker version 18.09.6, build 481bc77156
docker-compose version 1.24.0, build 0aa59064
