### ISSUE TITLE
Investigate how travis keeps the security informations 

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#5867]
Needs figure out how to handle sensitive keys in the travis.

**Comment by reasonerjt** [comment]
The change in PR https://github.com/goharbor/harbor/pull/5949 
has to be revoked due to security restriction in travis, for details see:
https://travis-ci.org/goharbor/harbor/jobs/433914281

https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by wy65701436** [comment]
Close it
