### ISSUE TITLE
How to push image to Harbor using Harbor API？

### ISSUE THREAD

**Issue by fighterhit** [goharbor/harbor#5876]
Now I want to push my image to harbor or pull image from Harbor using Harbor API rather than using
 CLI  `docker pull/push xxx` , But I'm not sure how to use these Restful APIs.Can u give me some more examples? Thx!

**Comment by stonezdj** [comment]
Harbor API doesn't include the push/pull images, for other AP please refer docs/swagger.yaml

**Comment by iamNoah1** [comment]
Hei there, does the API still not support pushing/pulling images? 

Cheers 
Noah

**Comment by ojasgupta** [comment]
Hi, 
I have the same question, is it supported now or are you planning to add this anytime soon?

Thanks,
Ojas

**Comment by tinarooot** [comment]
hello , is it supported now?

**Comment by farhadkh000** [comment]
hi ,is it supported now?

**Comment by neottil** [comment]
Hello, is it supported now? In the swagger there isn't this API, will this issue be considered?

**Comment by plc-dev** [comment]
@stonezdj 
Are there any plans on supporting this operation? Is Harbor open for pull request on this issue?

Thank you for your response in advance.

**Comment by tinarooot** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Shanwu404** [comment]
> hi ,is it supported now? I really need this and I think this feature is really important as a product in this field

same question.

**Comment by tinarooot** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
