### ISSUE TITLE
Update CONTRIBUTING.md with new URLs and code dependency links

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#5879]
The current https://github.com/goharbor/harbor/blob/master/CONTRIBUTING.md document talks about VMware-specific things like CLAs, community links, and code dependencies.

This issue could be an umbrella issue for things related to updating the document with correct information.

- [ ] Remove CLA
- [ ] Update community links
- [ ] Update code links
- [ ] Update links to dependencies
- [ ] Correct links to images

If there's anything else that should be on this checklist, please let me know.

**Comment by clouderati** [comment]
Issue fixed via PR #5880.
