### ISSUE TITLE
how to change date format to Europe

### ISSUE THREAD

**Issue by abououdine** [goharbor/harbor#5881]
What can we help you?
is is possible to change the date format to Europe? Thanks

**Comment by steven-zou** [comment]
@ninjadq 

Please help to confirm if the date format can be changed automatically depends on the locations. I remember we use a 'local' format to format the date str based on the localization.

**Comment by ninjadq** [comment]
Yes, the date format depends on the language you select

**Comment by Sylordis** [comment]
Unfortunately, "English" language seems to be the American English, not actual English with European date format (for example). Is there a way to change that?

**Comment by dioguerra** [comment]
Comments here please?

**Comment by antoniodellelce** [comment]
@ninjadq I changed language to others including your local format (of the team) all use different format than the American, but the date format stays unchanged

**Comment by ninjadq** [comment]
hi @dioguerra @antoniodellelce, what version of harbor are you running on?

**Comment by dioguerra** [comment]
We are using Harbor v2.2.0. I plan to test perf with the latest version. I will give it a go and report back.

**Comment by Tux** [comment]
1. Dutch is not a UI option
2. Even if it were, I'd still use English, but I *hate* the stupid US date format.
3. Make ISO date formats selectable for *all* locales: YYYY-MM-DD HH:MM:SS

**Comment by SimonAlling** [comment]
@Tux: As mentioned by @robdewit, #16796 added an option to force ISO 8601 formatting. It’s included in [v2.6.0](https://github.com/goharbor/harbor/releases/tag/v2.6.0). 😊
