### ISSUE TITLE
Tooltip is not shown for "Repository Read Only"

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5883]
**Steps to reproduce the problem:**
Login as admin and go to Configuration page select `System Settings` tab.
Hover on the `i` icon besides `Repository Read Only`, see the message label instead of message.
![image](https://user-images.githubusercontent.com/2390463/45463855-6bd96780-b740-11e8-8213-afd7f4634716.png)

**Versions:**
Please specify the versions of following systems.
- harbor version: Version v1.6.0-8cdd2d29
- docker engine version: irrelevant
- docker-compose version: irrelevant

**Comment by zhoumeina** [comment]
@wy65701436, what about show in tooltip
Users can not do any operations to the images in this mode.
