### ISSUE TITLE
The space between the button and tab section is inconsistent for different tabs

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5886]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When select different tabs the space should be same.

**Steps to reproduce the problem:**
When I select "Repositories", "Helm Charts", "Members", "Replication" tabs under a project

The space between the button and the tab section changes, for example:

![image](https://user-images.githubusercontent.com/2390463/45470738-7526fc00-b761-11e8-8227-5d691e487d1b.png)

![image](https://user-images.githubusercontent.com/2390463/45470767-94258e00-b761-11e8-805b-13ee6ebb3723.png)

**Versions:**
Please specify the versions of following systems.
- harbor version: Version v1.6.0-8cdd2d29
- docker engine version: irrelevant
- docker-compose version: irrelevant

**Comment by pureshine** [comment]
fixed bt py: #5899

**Comment by pureshine** [comment]
fixed bt py: #5899
