### ISSUE TITLE
Changing values in the UI configuration dialog does not enable the "save" button

### ISSUE THREAD

**Issue by jonbrenner** [goharbor/harbor#5894]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Changing values in the UI configuration dialog does not enable the "save" button. I can use browser dev tools to remove the "disabled" attribute from the button tag and the save function works properly.

**Steps to reproduce the problem:**
New instance. I configured ldap_auth and set verify_cert to true before the initial install. 

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.6.0-66709daa
- docker engine version: 18.06.1-ce
- docker-compose version: 1.21.2

**Comment by zhoumeina** [comment]
this is a know issue,track this issue with issue:
Enable/Disable status of buttons in configuration page should be based on the current tab section #4295
