### ISSUE TITLE
Display time of mirror warehouse container creation time

### ISSUE THREAD

**Issue by XiaoMuYi** [goharbor/harbor#5906]
**Versions:**
Please specify the versions of following systems.
- harbor version: v1.5.2
- docker engine version: 1.13.1
- docker-compose version: 1.21.2

标签                    大小                  创建时间
c251a4cb        44.33KB          1/1/1 上午8:05
6d4a7098       47.20KB           1/1/1 上午8:05
e776d7e9        47.31KB            1/1/1 上午8:05 

problem description:
As shown above, the creation time of the container is always displayed as the same. help me ？

**Comment by HelenaZheng** [comment]
I have the same proble, anynone help me?

**Comment by HelenaZheng** [comment]
1.9.0 21.19KB 1/1/1 上午8:05
1.8.0 21.20KB  1/1/1 上午8:05
1.8.1 28.10KB 1/1/1 上午8:05
