### ISSUE TITLE
how to use s3 for storage

### ISSUE THREAD

**Issue by lpf190** [goharbor/harbor#5907]
the prefile is:
common/template/registry/config.yml
![image](https://user-images.githubusercontent.com/25947971/45620352-2bb31580-baaf-11e8-97ef-09225527600b.png)

harbor.cfg
![image](https://user-images.githubusercontent.com/25947971/45620491-b431b600-baaf-11e8-9377-b7164063ef8c.png)

but it didn't occured
![image](https://user-images.githubusercontent.com/25947971/45620689-476aeb80-bab0-11e8-9972-099136b05ac7.png)

i am also define a prefile in harbor folder s3.yml
![image](https://user-images.githubusercontent.com/25947971/45620858-c95b1480-bab0-11e8-9e8b-03e86e9f0cfc.png)

it didn't occured to.

what error for me and how to use s3 for storage? hope to your help

**Comment by lpf190** [comment]
@reasonerjt yes, i had read this,but i didn't understand how to use either; could you give me a example?

**Comment by lpf190** [comment]
@reasonerjt  this failed either
![image](https://user-images.githubusercontent.com/25947971/45667481-f0b2ef80-bb4b-11e8-935d-b0346bf2fcc6.png)

**Comment by reasonerjt** [comment]
Please provide the log and configuration files as suggested in the template.

**Comment by lpf190** [comment]
@reasonerjt 
harbor.cfg i only change:
```
hostname = IP
customize_crt = off
registry_storage_provider_name = s3
registry_storage_provider_config = "accesskey: xxxxxxxxxxx, secretkey: yyyyyyyyyyy, region: ap-northeast-2, bucket: kops-k8s-demo-00.k8s.local-state"
```
then docker run state
```
root@ip-172-20-4-49:/var/log/harbor# docker ps --all
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                         PORTS                                                              NAMES
4c0ad3d0d899        goharbor/nginx-photon:v1.6.0             "nginx -g 'daemon of…"   37 seconds ago      Up 36 seconds (healthy)        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
ccf9644d8fd0        goharbor/harbor-jobservice:v1.6.0        "/harbor/start.sh"       37 seconds ago      Up 36 seconds                                                                                     harbor-jobservice
5f9d8b605731        goharbor/harbor-ui:v1.6.0                "/harbor/start.sh"       39 seconds ago      Up 37 seconds (healthy)                                                                           harbor-ui
9f6789f96acc        goharbor/redis-photon:v1.6.0             "docker-entrypoint.s…"   39 seconds ago      Up 37 seconds                  6379/tcp                                                           redis
992fb1bbce5c        goharbor/registry-photon:v2.6.2-v1.6.0   "/entrypoint.sh /etc…"   39 seconds ago      Restarting (1) 8 seconds ago                                                                      registry
a118f21c51aa        goharbor/harbor-db:v1.6.0                "/entrypoint.sh post…"   39 seconds ago      Up 38 seconds (healthy)        5432/tcp                                                           harbor-db
9cb99f20aa22        goharbor/harbor-adminserver:v1.6.0       "/harbor/start.sh"       39 seconds ago      Up 38 seconds (healthy)                                                                           harbor-adminserver
999cb67bfc53        goharbor/harbor-log:v1.6.0               "/bin/sh -c /usr/loc…"   40 seconds ago      Up 39 seconds (healthy)        127.0.0.1:1514->10514/tcp                                          harbor-log
```
the log(i had clean all before)
[log.tag.gz](https://github.com/goharbor/harbor/files/2391619/log.tag.gz)

**Comment by reasonerjt** [comment]
There are following errors in `registry.log`:
```
Sep 18 07:26:10 ip-172-30-0-1.ap-northeast-2.compute.internal registry[11271]: configuration error: error parsing /etc/registry/config.yml: yaml: unmarshal errors:
Sep 18 07:26:10 ip-172-30-0-1.ap-northeast-2.compute.internal registry[11271]:   line 7: cannot unmarshal !!map into string
Sep 18 07:26:10 ip-172-30-0-1.ap-northeast-2.compute.internal registry[11271]: 
```
so it seems the `config.yml` is malformed.
please check `harbor/common/config/registry/config.yml` on your VM.

**Comment by lpf190** [comment]
@reasonerjt yes, i find this to; becase the harbor.cfg 
```
registry_storage_provider_config =  "xxxxxx"
```
when ` ./prepare`
the ` common/config/registry/config.yml`  will content like
```
registry_storage_provider_config =  "xxxxxx"   #=the double quotes also include
```

**Comment by lpf190** [comment]
@reasonerjt 
thanks,
becase the ` harbor/common/config/registry/config.yml` became:
```
storage:
  cache:
    layerinfo: redis
  s3:
    "accesskey:  xxxxxxxx
    secretkey: yyyyyyyyyyyyyy
    region: ap-northeast-2
    bucket: kops-k8s-demo-00.k8s.local-state"
```
so in `harbor.cfg` need like:[not add double quotes]
```
registry_storage_provider_config = accesskey: xxxxxxxxxxxx, secretkey: yyyyyyyyyyyyyyy, region: ap-northeast-2, bucket: kops-k8s-demo-00.k8s.local-state
```

**Comment by DavidRodHub** [comment]
Just install Harbor 1.9.0 and a host in AWS.  I installs and runs great if the "/data" is on the local system.   Having trouble setting it up so that the harbor reside on an S3 bucket mounted on the host.  The documentation is not clear.   So what i did was add  following to the harbor.yml  and was not successful.  What is the proper way to do this.

storage:
  filesystem:
    rootdirectory: /regS3Bucket
    maxthreads: 100
  s3:
    accesskey: **************
    secretkey: **************
    region: us-west-1
    regionendpoint: https://s3-us-west-1.amazonaws.com
    bucket: company-docker-registry    `

**Comment by Kali-lightsaber** [comment]
Why is this issue closed?

**Comment by paulliss** [comment]
+ 1
Why is it closed?
What permissions "owner:group" does the mount S3 bucket need to be set to so that Harbor will install successfully?
