### ISSUE TITLE
新建目标错误

### ISSUE THREAD

**Issue by liyongzhezz** [goharbor/harbor#5909]
在 <新建目标>时报错：
![image](https://user-images.githubusercontent.com/30651051/45661260-475e0080-bb2f-11e8-8abc-bee4acb68068.png)

这个可能是哪里的问题？

**Comment by liyongzhezz** [comment]
给ui这个容器添加extra_host可以解决，但是同步的时候提示 no route to host，在jobservice容器中无法连通80端口，这个如何解决

**Comment by ywk253100** [comment]
Describe your problem in detail, which version of Harbor did you install? The jobservice can not connect to source or destination? Any logs?

**Comment by liyongzhezz** [comment]
I have already solve this problem, thank you
