### ISSUE TITLE
about docker image goharbor/harbor-db:v1.6.0

### ISSUE THREAD

**Issue by weeeeeee** [goharbor/harbor#5926]
when I deploy harbor 1.6.0 in K8S, adminserver container reported crashloopBackoff. The log of adminserver container said: [FATAL] [main.go:46]: failed to initialize the system: invalid database: mysql. Then I entered a container named "msyql-xxx-xxx", I only found a dir related to mysql "/var/lib/mysql", but most files related to postgresql, also the main process of this container was "su - postgres -c postgres -D /var/lib/postgresql/data". The docker image of container "mysql-xxx-xxx" is harbor-db:v1.6.0. It confuses me a lot.

**Comment by ywk253100** [comment]
Seems the adminserver read some data of old version. 
As Harbor chart doesn't support upgrade for now, you need to delete all PVCs used by Harbor before installation if you have installed an old version Harbor chart.

**Comment by weeeeeee** [comment]
> Seems the adminserver read some data of old version.
> As Harbor chart doesn't support upgrade for now, you need to delete all PVCs used by Harbor before installation if you have installed an old version Harbor chart.

thanks. But I am sure I have deleted all pvc. I used nfs as a storageClass and pvc was created in the storageClass.

**Comment by clouderati** [comment]
@weeeeeee did you upgrade to get to v1.6, or was this a fresh deployment?

**Comment by weeeeeee** [comment]
> @weeeeeee did you upgrade to get to v1.6, or was this a fresh deployment?

A fresh deployment.

**Comment by ywk253100** [comment]
Which chart are you using? Is this one https://github.com/goharbor/harbor-helm?

**Comment by weeeeeee** [comment]
> Which chart are you using? Is this one https://github.com/goharbor/harbor-helm?

I didn't use helm but "make/kubernetes/k8s-prepare" to deploy. Now I changed to harbor-1.5.3, and didn't met the same problem.
