### ISSUE TITLE
Is it impossible to upgrade harbor from version 0.5?

### ISSUE THREAD

**Issue by liyongzhezz** [goharbor/harbor#5943]
I want to upgrade harbor from 0.5 to 1.5, but vmware/migratorharbor-db-migrator has already been remove from docker hub， so i cannot migrate data.

Does it means that users of version 0.5 have been abandoned and cannot migrate data?

**Comment by steven-zou** [comment]
@liyongzhezz 
It's supported but not verified officially yet. You can have a try.

**Comment by liyongzhezz** [comment]
I also tried to use harbor-migrator and harbor-db-migrator, but failed.

Is there any other way to migrate  user data?

**Comment by wy65701436** [comment]
@liyongzhezz I think you could upgrade to v1.0 firstly, and then to upgrade to v1.5, this path should be workable. 

But, please follow the guide on the specific branch, not on master.
