### ISSUE TITLE
Image Scan Error :failed to initialize job logger

### ISSUE THREAD

**Issue by aurthurxlc** [goharbor/harbor#5952]
**Versions:**
- harbor version: [1.6.0]
- docker engine version: [18.04.0-ce]
- docker-compose version: [1.20.0]

When I start a image scan job, jobservice.log get some error info
```bash
Sep 26 16:34:30 172.18.0.1 jobservice[930]: 2018-09-26T08:34:30Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"e7fef6c505c10f2d7bc4eb7b", "hook_url":"http://ui:8080/service/notifications/jobs/scan/51"}
Sep 26 16:34:30 172.18.0.1 jobservice[930]: 2018-09-26T08:34:30Z [INFO] Job incoming: IMAGE_SCAN:e7fef6c505c10f2d7bc4eb7b
Sep 26 16:34:30 172.18.0.1 jobservice[930]: 2018-09-26T08:34:30Z [ERROR] [service_logger.go:63]: Job 'IMAGE_SCAN:e7fef6c505c10f2d7bc4eb7b' exit with error: failed to initialize job logger
```
![2018-09-26 16 40 34](https://user-images.githubusercontent.com/13117745/46068215-43735380-c1ab-11e8-86bf-e87498bb8560.png)
![2018-09-26 16 42 21](https://user-images.githubusercontent.com/13117745/46068246-5be36e00-c1ab-11e8-93b6-e412776b4265.png)

**Comment by reasonerjt** [comment]
Please check on your docker host, what's the `umask`?
Try to run `chmod +r /data/job_logs` and see if the problem remains.

**Comment by aurthurxlc** [comment]
Oh , thanks!

The original  ```umask``` of folder ```/data/job_logs``` is ```drwxr-xr-x  2 root root   42 9月  27 07:35 job_logs```

 I tried to run this command ``` chown 10000:10000 -R /data/job_logs```, It works!!
