### ISSUE TITLE
[gc]gc backend api minor issues

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#5953]
1 post schedule and put schedule should be merged to 1 api. Frontend does not have the accurate knowledge of schedule exist or not. 

2 post schedule and put schedule response  type should be json, and contains the current schedule in the response body.

**Comment by wy65701436** [comment]
This is not happening on GC API only, almost all the put/post will not return JSON.

**Comment by zhoumeina** [comment]
true, so I think we should refactor this to json @reasonerjt

**Comment by zhoumeina** [comment]
As most of the single page applications returns json by default. We have no special reasons to use text for data exchange.

**Comment by wy65701436** [comment]
for #2, it depends on https://github.com/goharbor/harbor/issues/6967, use that issue to track status.
