### ISSUE TITLE
Not able to see clair and signed 

### ISSUE THREAD

**Issue by leeadh** [goharbor/harbor#5959]
![image](https://user-images.githubusercontent.com/15122358/46089820-eba40f00-c1e1-11e8-8985-da7cf7b2712e.png)

![image](https://user-images.githubusercontent.com/15122358/46089949-39207c00-c1e2-11e8-9f8e-cd2c82890183.png)

I enabled the clair , notary but i cant see it in my project configuration setting?

Is this a bug

**Comment by reasonerjt** [comment]
@leeadh please read the user guide regarding how to use clair/notary. 
And i believe #5955 can be closed since you have successfully installed Harbor with clair?

**Comment by leeadh** [comment]
Hi reasonerjt, I followed the guide but vulnerability scanning can't be seen when I did the installation on my VM.

**Comment by reasonerjt** [comment]
You first need to push some image, secondly you need to scan it.

**Comment by steven-zou** [comment]
@leeadh 

You also need to make sure the Clair CVE DB is totally ready (Once ready the warning message will be gone).
