### ISSUE TITLE
Some issues in current GC job API

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5960]
1) When there are multiple entries of periodic GC job in admin table the API will return 500, but the case will happen when jobservice is down, considering the code insert an entry in DB then call jobservice API.
2) The uuid is set by notification handler, there seems a gap when jobservice sends the web hook after the job is submitted, this will cause issue when user frequently update the schedule of GC job, the code will try to cancel the job before the uuid is set to the DB, so the job will not be canceled by jobservice.

**Comment by wy65701436** [comment]
#2 is a known issue, my original thought is to fix it in the PR to fix issue #5933
