### ISSUE TITLE
[xss report] XSS report for Security about bootstrap 4.0.0-alpha.

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#5961]
There is XSS risk in github security report about bootstrap 4.0.0-alpha. This is caused by Clarity dependency on bootstrap.

**Comment by zhoumeina** [comment]
There is a issue in Clarity team:
https://github.com/vmware/clarity/issues/2686

**Comment by zhoumeina** [comment]
Harbor team does not introduce any javascript of bootstrap. So this is just a alert, will not cause any bad affect in UI security.

**Comment by gnomeontherun** [comment]
Clarity depends on Bootstrap internally and marks it as an `optionalDependency`. Only if you build the theme yourself do you need to install Bootstrap, and Harbor does not do this. So there is no reason for Bootstrap to be installed as a dependency of your project.

I've made a PR to resolve this for you now. https://github.com/goharbor/harbor/pull/5967
