### ISSUE TITLE
The GC job start time/end time is confusing  in pending state

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#5969]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A pending job should not have startime/endtime, because it does not start.

**Steps to reproduce the problem:**
1.Schedule the GC job to 2:00PM 
2.Check the job status
3.The job status is pending, but it has a start time/end time

**Versions:**
- harbor version: [1.6.0]

**Comment by clouderati** [comment]
Should we not have a "scheduled time" to keep tabs on when jobs were originally created?

**Comment by wy65701436** [comment]
this is as designed, close it as won't fix.
