### ISSUE TITLE
GC Job start time and end time is incorrect after job complete

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#5970]
Change the GC job schedule from 2:00PM to 2:40
Delete some images in harbor 
After the job is complete, check the job list
Start time is 2:03PM  it is not correct,
The actual start time should be 2:40PM.

**Comment by stonezdj** [comment]
![screen shot 2018-09-28 at 3 13 16 pm](https://user-images.githubusercontent.com/2696760/46193544-1d77bb80-c331-11e8-8e2d-c845057a8357.png)

**Comment by wy65701436** [comment]
The time now in UI is the admin job attribute, not the stant time actually.

**Comment by Ghostbaby** [comment]
which harbor release were you use?

**Comment by scaat** [comment]
Now, the start time corresponds to the job creation time, and the end time corresponds to the job status update time. @stonezdj 
Has there been a plan to amend it ? @wy65701436 
If not, I want to deal with this.

**Comment by wy65701436** [comment]
@scaat PR is welcome, would you like to share your idea firstly?
