### ISSUE TITLE
No helm charts displayed under projects->library

### ISSUE THREAD

**Issue by kingsmithhuang** [goharbor/harbor#5973]
I didn't find helm charts displayed under projects->library, whatever I installed the online or the offline v1.6.0 package. I'm wondering if there're some configurations I missed. 
![image](https://user-images.githubusercontent.com/40188259/46201384-97ff0600-c346-11e8-84ce-76908332c053.png)

**Comment by wy65701436** [comment]
Did you install harbor with chartmuseum? If not, please follow the installation guide

**Comment by babyb00n** [comment]
Hi, 
I've got the same issue deploying harbor via the offline installer. The "--with-chartmuseum"-Option was definitely provided, and we also tried a clean install with no luck. Is there any config file for Harbor itself where the chartmuseum integration is configured?
Thanks and kind regards

**Comment by babyb00n** [comment]
I have the solution, there is no problem with harbor, you need to delete your browser cache, then it will show. There seemed to be some leftovers
