### ISSUE TITLE
LDAD config - fields restricted to 128 chars

### ISSUE THREAD

**Issue by nagonzalez** [goharbor/harbor#5974]
**Expected behavior and actual behavior:**
Configure LDAP Search DN. My DN > 128 chars which is blocking me from saving the config.

**Steps to reproduce the problem:**
Tried to configure LDAP Search DN with a string > 128 chars. I get a 500 error in GUI 

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.6.0-66709daa
- OpenShift: 3.10

**Additional context:**
* **Log files:** 
```
10.128.2.1 - - [28/Sep/2018:19:52:40 +0000] "PUT /api/configurations HTTP/1.1" 500 22
2018-09-28T19:52:40Z [ERROR] [cfg.go:56]: failed to update system configurations: pq: value too long for type character varying(128)
ERROR:  value too long for type character varying(128)
2018-09-28T19:52:40Z [ERROR] [config.go:101]: failed to upload configurations: http error: code 500, message Internal Server Error
```

**Comment by wy65701436** [comment]
The issue has been fixed in the master branch, and will be ready in the next release.

**Comment by nagonzalez** [comment]
thanks!
