### ISSUE TITLE
About restful APIs for  job services

### ISSUE THREAD

**Issue by Ghostbaby** [goharbor/harbor#5976]
What can we help you?
https://github.com/goharbor/harbor/issues/3945
Is there a doc for that restful APIs?

I want to post some job to job services server, 
so, I need to know post what kind of data.

**Comment by clouderati** [comment]
Hi @Ghostbaby – not sure that we've documented the job service API. Might be helpful to understand precisely what it is that you're trying to accomplish.

The API implementation was completed over a number of GitHub issues:

#3747 – Investigate and design the final job service architecture
#3937 – Scheduler manager Task sync
#3938 – Add task precondition check for Workers
#3945 – Implement restful APIs for job services
#4012 – The running jobs can not be stopped correctly in HA environment
#4327 – Implement the bootstrap part of job service
#4328 – Implement the core interface (controller) of job services
#4329 – Implement scheduler to fire Periodic job
#4330 – Implement data handler to handle the backend data
#4331 – Migrate scan job to new job services
#4332 – Migrate replication job to new job service
#4333 – Implement the monitor to cover the lifecycle status of jobs
#4334 – Implement job group to execute jobs in parallel
#4434 – Support status hook function in the new job service.
#4435 – Build the container image for the new job service
#4436 – Add UT cases for the new job service
#4437 – Build the job execution context for replication can scan jobs
#4497 – Integrate redis container into docker compose template and default installer
#4546 – Job service should validate the access secret located in "Authorization"

Depending on what it is that you're trying to do it might make sense to take a look through these issues to get a better idea of how to interact with the job service.

/cc @steven-zou

**Comment by clouderati** [comment]
Thanks @reasonerjt. Would be helpful to understand what the use case is; perhaps there's a better way to address it. Let us know @Ghostbaby.

**Comment by Ghostbaby** [comment]
@clouderati @reasonerjt Thank you for your replay!
In our use case, we completed CICD and use Harbor to storage docker image, we have three env(DEV, QA, PROD), and need to replicate single tag from DEV Harbor to another env Harbor.

**Comment by Ghostbaby** [comment]
So, we try to post some format data to job service API.

Post the json data to job server 
`{"job":{"name":"IMAGE_TRANSFER","parameters":{"dst_registry_insecure":false,"dst_registry_password":"SGFyYm9yMTIzNDUK","dst_registry_url":"http://192.168.191.157","dst_registry_username":"admin","repository":"library/rust","src_registry_insecure":true,"src_registry_url":"http://192.168.191.156","tags":"aa5551d785"},"metadata":{"kind":"Generic","unique":false},"status_hook":"test"}}`

job server response the data

`{"job":{"id":"3613fa8b32655b179a1f2f7d","status":"Pending","name":"IMAGE_TRANSFER","kind":"Generic","unique":false,"ref_link":"/api/v1/jobs/3613fa8b32655b179a1f2f7d","enqueue_time":1538408243,"update_time":1538408243,"hook_status":"activated"}}`

job server log is 

`Oct  1 23:37:25 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:25Z [INFO] Job incoming: IMAGE_TRANSFER:3613fa8b32655b179a1f2f7d
Oct  1 23:37:25 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:25Z [ERROR] [service_logger.go:63]: Job 'IMAGE_TRANSFER:3613fa8b32655b179a1f2f7d' exit with error: Runtime error: interface conversion: interface {} is string, not []interface {}
Oct  1 23:37:25 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:25Z [WARNING] Failed to process 'report_status' request with error: Post test: unsupported protocol scheme ""
Oct  1 23:37:25 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:25Z [WARNING] Failed to process 'report_status' request with error: Post test: unsupported protocol scheme ""
Oct  1 23:37:27 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:27Z [WARNING] Failed to process 'mark_die_at' request with error: seems 3613fa8b32655b179a1f2f7d is not a dead job
Oct  1 23:37:29 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:29Z [WARNING] Failed to process 'report_status' request with error: Post test: unsupported protocol scheme ""
Oct  1 23:37:29 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:29Z [WARNING] Failed to process 'mark_die_at' request with error: seems 3613fa8b32655b179a1f2f7d is not a dead job
Oct  1 23:37:30 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:30Z [WARNING] Failed to process 'report_status' request with error: Post test: unsupported protocol scheme ""
Oct  1 23:37:39 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:39Z [ERROR] [service_logger.go:63]: Failed to process 'report_status' request with error: Post test: unsupported protocol scheme "" (3 times tried)
Oct  1 23:37:42 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:42Z [ERROR] [service_logger.go:63]: Failed to process 'report_status' request with error: Post test: unsupported protocol scheme "" (3 times tried)
Oct  1 23:37:42 172.18.0.1 jobservice[23019]: 2018-10-01T15:37:42Z [ERROR] [service_logger.go:63]: Failed to process 'mark_die_at' request with error: seems 3613fa8b32655b179a1f2f7d is not a dead job (3 times tried)`

**Comment by clouderati** [comment]
Just so that I understand, is the goal here to replicate only specific _tags_ from `Registry A` to `Registry B`?

**Comment by Ghostbaby** [comment]
@clouderati 
Correct!
Test Engineer needs to build many docker image tags to `Registry DEV`, these images can be deployed to DEV K8S cluster.
When a tag completes the test, it will be deployed to the QA K8S environment, so we need to replicate only specific tags from  `Registry DEV` to `Registry QA`.

**Comment by Ghostbaby** [comment]
tags need an array type.
