### ISSUE TITLE
Export an image via REST API?

### ISSUE THREAD

**Issue by johnsonru** [goharbor/harbor#5977]
Hi,
I'm looking for a way to download via a REST API an export of a docker image from a remote Harbor repository.
For example http://<harbor ip & port>/v1.37/library/redis:latest would provide an octet stream of the request tar file.

It appears the Docker engine supports the capability as described at:
https://docs.docker.com/engine/api/v1.37/#operation/ImageGet

Does the capability exist for Harbor and/or any guidance?  
I am unable to use the Docker CLI to pull the image due to requirement that my "business logic server" which needs to pull the image is not allowed to have the Docker CLI installed.

**Comment by johnsonru** [comment]
I was able to find that Harbor exposes the "v2" of the docker registry at http://<harbor ip & port>/v2/*
which is documented at https://docs.docker.com/registry/ .
Using that, I can extract the content I need for the layers.

**Comment by jiayongpeng** [comment]
@johnsonru The docker registry API does return images layers from Harbor, but the layer format and digest is different from what the 'docker pull' command gets. Did you notice this and how have you resolved this?
