### ISSUE TITLE
Narrow privileges on ADD LABEL operation

### ISSUE THREAD

**Issue by dosmanak** [goharbor/harbor#5979]
**Is your feature request related to a problem? Please describe.**
Since it is possible to create replication rule based on labels, it would be great to distinguish privileges on ADD LABELS operation. Currently the developer can push images and add labels. In case of replication, there is not a way how to deny developer to add label "production" to the image which has not been tested.
[adding-labels-toremove-labels-from-images](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#adding-labels-toremove-labels-from-images)

**Describe the solution you'd like**

Currently the user guide claims: 
"Users who have system administrator, project administrator or project developer role can click the ADD LABELS button to add labels to or remove labels from images."
I would like the following behavior: 
"Users who have system administrator or project administrator role can click the ADD LABELS button to add labels to or remove labels from images."
For the developer role pushing privilege should suffice.

**Describe the main design/architecture of your solution**
Setup replication rule based on label.
Only system administrator or project administrator can decide what image should be replicated to the next registry.

**Describe the development plan you've considered**
harbor/src/ui/api/label.go +88:
insert: 
```
    if !l.SecurityCtx.IsProjectAdmin() {
      l.HandleForbidden(l.SecurityCtx.GetUsername())
       return
    }
```
And implement SecurityCtx.IsProjectAdmin function in 
/src/harbor/src/common/security/admiral/authcontext/authcontext.go +67:
```
// IsProjectAdmin ...
func (a *AuthContext) IsProjectAdmin() bool {
	for _, role := range a.Roles {
		if role == projectAdminRole {
			return true
		}
	}
	return false
}
```

**Comment by dosmanak** [comment]
harbor/src/ui/api/label.go is wrong place since it defines creation of label not using it.
The correct place might be src/ui/api/repository_label.go +35
function addLabel.

**Comment by clouderati** [comment]
Thanks @dosmanak – I think this is a great idea. Is this something you're willing to contribute? Else we'll definitely keep this in our backlog of work to do.

Happy to help you through the process if you want to contribute this feature.

/cc @lweitzman and @zhoumeina – might need some UI changes if something like this is implemented, no?
