### ISSUE TITLE
Ability to create local service accounts when LDAP authentication is enabled

### ISSUE THREAD

**Issue by fwdIT** [goharbor/harbor#6002]
Problem:
As soon as we enable LDAP authentication, Harbor expects all accounts which want to authenticate to exist in LDAP.
We have, however, external services with service accounts. For instance, a Jenkins job which wants to push images to a certain project.
We don't want to create such service accounts in our LDAP user base DN because we only prefer named accounts there. We also want to avoid adding extra complexity on the LDAP side (for instance a different ou as base DN which increases the user scope and then extra rights for the Harbor LDAP search user to block the unwanted ou's because this can impact other applications linking with the LDAP which don't expect new ou's with such service accounts etc)
It seems that as soon as LDAP is enabled, the local user management in our current Harbor version is disabled.

Solution:
It would be useful to keep the possibility to create local accounts next to LDAP accounts. Or an additional section specifically for service accounts if this is easier to implement.

Additional:
In the same sense as above, it would also be useful to be able to have LDAP accounts combined with local groups instead of only LDAP groups as soon as LDAP is enabled. So, in general, the suggestion is to keep both LDAP and local user and group management available at the same time.

**Comment by kauedg** [comment]
The authentication method priority (sequence) could be set by the admin in the "Administration > Configuration > Authentication > Auth Mode", modified to show a sortable list with the enabled methods.

**Comment by trunet** [comment]
Or to create "application login credentials" tied to user and/or group.

**Comment by fajran** [comment]
I think the solution that @trunet mentioned is quite common approach to handle use case from @fwdIT. For example in Jenkins, user has a way to generate authentication token for API access.

**Comment by pdhung** [comment]
@trunet @fajran would you mind elaborating your point please? Does it mean that the user need to create a middleware to handle login / generate token and Harbor to consume it?

**Comment by hasonhai** [comment]
I think token solves only one part of the issue. If users deploy their apps in Kubernetes, they will need a service account instead of a token. Kubernetes stores the credential to pull image in a secret, so if Harbor is setup with LDAP, users in a shared namespace can reveal other user's LDAP password in that case. We're also having the problem like this, even though we do like to use LDAP a lot, but we have to fall back to use the local account.

**Comment by Thoro** [comment]
I agree and it would be great to have the service accounts part working.

**Comment by stonezdj** [comment]
After 1.8.0, harbor have robot account feature, it can be used under LDAP authentication
