### ISSUE TITLE
Is it possible to migrate from 1.5.1 to 1.6.0 version

### ISSUE THREAD

**Issue by RobertoRosillo** [goharbor/harbor#6004]
I am looking for the steps to upgrade Harbor from 1.5.1 version to 1.6.0 version, but I didn't find. Also, I have readed in your "Harbor upgrade and database migration guide" document that I could use "goharbor/harbor-migrator:[tag]" image to do it, but that image cann't be found.

I suspect that the migration between these versions are not certificated if it is possible. Please, could you give me some ideas?

Thanks in advance.

**Comment by ninjadq** [comment]
hi @RobertoRosillo , you can use `goharbor/harbor-migrator:v1.6.0` to migrate from 1.5.1 to 1.6.0

**Comment by RobertoRosillo** [comment]
Thank you.
