### ISSUE TITLE
Publish metadata as part of pushing the image to the registry ?

### ISSUE THREAD

**Issue by mramanathan** [goharbor/harbor#6012]
[Artifactory, via plugin for Jenkins](https://www.jfrog.com/confluence/display/RTF/Setting+Up+Docker+Build-info), allows for publishing metadata (build related info). This is accomplished as per the procedure outlined in the link above, and it is handled using a set of Jenkins' pipeline DSL commands (exposed by the plugin) while the Docker image is pushed to the registry (hosted in artifactory).

I would like to know if such build info can be published in Harbor when the image is built and pushed from an automated environment i.e. Jenkins or TeamCity ?

**Comment by steven-zou** [comment]
@mramanathan 

  We have discussed such a topic before as an innovative idea, but it's not put into backlog yet. Do you have any willings to work on such feature and make contributions to Harbor community?

**Comment by clouderati** [comment]
Agreed, this would be an awesome feature to have @mramanathan. Let us know if you have the cycles to contribute; we'd love to help walk you through the process. :+1:

**Comment by mramanathan** [comment]
@steven-zou, @clouderati 
I presume, I can spare few cycles but would like to know or discuss few details before I sign up for this. What say ?

**Comment by steven-zou** [comment]
@mramanathan 

We're drafting proposal about resource metadata mechanism and planning to raise a PR later. Once it's ready, will let you know and you can participate in the discussions via PR at that time.

**Comment by mramanathan** [comment]
@steven-zou 

Thank you for sharing the status. I believe code contribution will involve deliveries using Go programming language ?

**Comment by steven-zou** [comment]
> @steven-zou
> 
> Thank you for sharing the status. I believe code contribution will involve deliveries using Go programming language ?

@mramanathan 

Correct!

**Comment by steven-zou** [comment]
@mramanathan 

Let's use the [metadata proposal](https://github.com/goharbor/community/pull/19) to continue the discussion. Welcome comments on the metadata proposal. Thanks!

**Comment by steven-zou** [comment]
Close this issue now.
