### ISSUE TITLE
Harbor with external HA postgres

### ISSUE THREAD

**Issue by jakirpatel** [goharbor/harbor#6027]
I am trying to deploy the harbor with external postgres HA cluster. However I am not sure if I am doing the right steps. 

I have created the HA Postgres cluster. Then I have created the database registry with 

`CREATE DATABASE registry ENCODING 'UTF8';`

For this setup I am including chart , notary and clair. 

However I got the following error with the adminserver:

```
Oct 12 08:05:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:05:41Z [INFO] Registering database: type-PostgreSQL host-hostname port-5432 databse-registry sslmode-"disable"
Oct 12 08:05:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:05:41Z [FATAL] [main.go:46]: failed to initialize the system: pq: relation "alembic_version" does not exist
Oct 12 08:06:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:06:41Z [INFO] initializing system configurations...
Oct 12 08:06:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:06:41Z [INFO] Upgrading schema for pgsql ...
Oct 12 08:06:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:06:41Z [INFO] No change in schema, skip.
Oct 12 08:06:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:06:41Z [INFO] Registering database: type-PostgreSQL host-hostname port-5432 databse-registry sslmode-"disable"
Oct 12 08:06:41 172.27.0.1 adminserver[18362]: 2018-10-12T08:06:41Z [FATAL] [main.go:46]: failed to initialize the system: pq: relation "alembic_version" does not exist
```

For external DB setup  I think so it would be really helpful if you provide the initial setup for the postgres. The same as the entrypoint.sh in harbor-db container. 

Also could you please provide the steps that how I can solve this issue?

**Comment by reasonerjt** [comment]
@jakirpatel could you check if anything created in the DB registry of you external DB?

**Comment by jakirpatel** [comment]
Sorry for the late reply @reasonerjt. 

Here are the details : 

**DB registry:** 

```
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 registry  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
```
Postgres Version : 
`
**9.2**
`
**Admin server tag :** goharbor/harbor-adminserver:v1.6.0  

Currently I have deployed the harbor with shared storage. **But to achieve the HA I need to have HA Postgres and HA redis.** 

Is it possible to have some templates to bootstrap the external DB? Also, I am planning to use Notary and Clair so I think so script should be flexible for bootstrapping the dependent components.

**Comment by reasonerjt** [comment]
@jakirpatel this is weird that the error says `relation "alembic_version" does not exist`, because as you see the table `alembic_version` does exist.  
So could it be some problem in your HA postgres setup?

**Comment by jakirpatel** [comment]
@reasonerjt 
Thank you for your reply. The version upgrade of postgres from` 9.2 to 10.2` solved my issue. But I cant confirm that was the problem. 

Going forward I think it is very important to know the compatibility of components with the harbor. Specially postgres , redis. 
The document should support minimum version supported for specific component. I would like to hear your thoughts on this too.

**Comment by reasonerjt** [comment]
It's a good and valid suggestion, but due to limited bandwidth so far we can only guarantee the ones we provided in the offline installer work together.

Could you share us how did you setup the HA postgres?

**Comment by jakirpatel** [comment]
@reasonerjt  Any idea of my question ? If not please let me know .

**Comment by reasonerjt** [comment]
@jakirpatel I was distracted and sorry for the late response.

Harbor relies on 3rd party library to connect to the DB instance.  I just verified both trust and md5 method work in standalone installation.

Are you seeing any issue for any particular method?

**Comment by jakirpatel** [comment]
@reasonerjt can you reproduce the issue with keeping the password blank and using the md5 as the method?

**Comment by jakirpatel** [comment]
I think if you put the blank as the Postgres password the issue seems occurred with trust method. Also if both methods are allowed like md5 and trust with Postgres how the Harbor decides the right one? This may be the question where you allow some CIDR to have the md5 and trust as well. @reasonerjt
