### ISSUE TITLE
Deletion based on image labels and image update time. 

### ISSUE THREAD

**Issue by jakirpatel** [goharbor/harbor#6035]
**Problem.**

Image deletion based on the labels and last update time of the image:tag (Depend on when it is pulled or pushed). HA Harbor is used here for all environments. **And the environments are differentiated by labels.** 

**Describe the solution you'd like**
Currently, labels are playing a very important role in our environments. We do have the **release** and **snapshot** two labels. 

**What we want?** 

We want continuous deletion of the **snapshot** label tagged images based on last access time in days. 
The **release** tag images are not meant to be deleted. Even the deletion should be enough intelligent. If there is SHA conflict in label based images then all the images with the same SHA should be skipped from deletion. 

Two images can have the same SHA but can be tagged differently with different labels. As the current problem with deletion of tags is: if we deleted the particular SHA (image:tag) then all other relevant tag of the images (image:tag) will get deleted. This is a potential risk for images which are used in **production**. 

**Describe the development plan you've considered**
Implementation of the worker:

1. Image labels which are considered to be safe to delete.
2. The input of a number of days since image:tag is not accessed. 
3. Running gc job after soft deletion. (Optional)

**Comment by steven-zou** [comment]
@jakirpatel 

Maybe you can this requirement can be merged with this PR: https://github.com/goharbor/community/pull/4 . You can attend the discussion through that PR.
