### ISSUE TITLE
how to reset dababase?

### ISSUE THREAD

**Issue by xiaochenluo** [goharbor/harbor#6038]
I choose OSS as storage first, then I found its performance unsatisfactory. So I changed storge to filesystem.
But, I met a problem.
To detect the push speed between OSS and Filesystem, I have deleted all the data  in OSS dashboard(some log files and some image layer files which from an unsuccessful push). Then I pushed the same image to harbor(filesystem), and I received 500 error. After check logs, I found harbor attempt to search the data pushed before which have been deleted. So, how to reset the registry database? Or , the only choice to me is reinstall the harbor? Or, is there an API to delete layers which is come from failed push?

**Comment by reasonerjt** [comment]
For your case, so far you'll have to manually remove all data in the DB.

**Comment by xiaochenluo** [comment]
I can't find these data in harbor-db. There are four databases: information_schema, mysql, performance_schema, registry. Nothing find in registry. Where to find the image layer file data?

**Comment by reasonerjt** [comment]
@xiaochenluo Could you confirm you just want to remove the data about repository?  If that's the case, here's a internal used env var you can try:
https://github.com/goharbor/harbor/blob/master/make/common/templates/core/env#L9

After setting it to true Harbor will call registry's API and sync the data to repository table during restart.
