### ISSUE TITLE
MOVE `src/portal` to the root of harbor repo

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#6040]
MOVE `src/portal` to the root of harbor repo to make the 'src' more clear (only go related things)

**Comment by zhoumeina** [comment]
@why need to move it to root? portal is not kind of src code?

**Comment by zhoumeina** [comment]
@steven-zou , what is the purpose of doing this?

**Comment by steven-zou** [comment]
@zhoumeina 

src is the backend go code src. Referring to the best practices of other projects, the UI/CLI on top of backend API will be put into a separate folder if it's co-located with backend code.

**Comment by zhoumeina** [comment]
@steven-zou , could you please provide an example we can refer to?
