### ISSUE TITLE
JobService will be hung after the Network recovered from a Net disaster

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#6047]
as the title, the JobService will be hung in a abnormal network scenario.
reproduce this case following below steps,
prepare: harbor1 in Node1 and harbor2 in Node2, we will do a replication from harbor1 to harbor2.
1. create a project in harbor1 and push 100 tags into.
2. create a replication task, type is manual.
3. run the task.
4. disable the network between harbors when task is running using command like: iptables -A OUTPUT -p tcp -d XXX.XXX.XXX.XXX -j REJECT
5. run the replacation task again.
6. recover the network using commend "iptables -D OUTPUT -p tcp -d XXX.XXX.XXX.XXX -j REJECT"
7. check the task, all task is hung, and erorr occured when geting the RUNNING Job log.
8. check JobService log as following,
`Oct 12 08:01:24 172.18.0.1 jobservice[1673]: 2018-10-12T00:01:24Z [ERROR] [client.go:83]: Unexpected error: Unexpected status code: 504, text: <html>#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: <head><title>504 Gateway Time-out</title></head>#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: <body bgcolor="white">#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: <center><h1>504 Gateway Time-out</h1></center>#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: <hr><center>nginx/1.15.3</center>#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: </body>#015
Oct 12 08:01:24 172.18.0.1 jobservice[1673]: </html>#015`

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.6.0 RC3]

normal case can run successfully. and everything is OK after i restart the JobService.
log seems that scan Image task also failed, and clair can not access. but actually other service is all OK.

**Comment by steven-zou** [comment]
@mmpei 

 As @reasonerjt said, please provide the full log files of jobservice for debugging.

**Comment by mmpei** [comment]
closed, could not reproduced.
