### ISSUE TITLE
 difficult  to push big image with OSS storage

### ISSUE THREAD

**Issue by xiaochenluo** [goharbor/harbor#6050]
Lots of out images are over 3.5G  include big layers(500M~2G).
 I choose Aliyun OSS as storage first. Push always failed(504 error).  After adjusting the configuration（increase the chunk-size and Nginx read_timeout ), I found those big layers are bottleneck.
 In client, it looks like:
60207ef79218: Pushing [==================================================>] 830.4 MB
then, it changed to pushed after a long time(>30min) or can't pushed in the end.

After, I changed to use file system as storage. It took only 5 minutes to push the same image. 

In docker manuals , there  are only a few configurations about oss storage. Is there some recommendations for OSS optimization to solve the problem? Or this is the docker bottleneck that can't resolve now?

Sorry to ask you this question, I know this is probably the Docker's issue.  I searched the relevant questions and found no answer in Docker's issue and found their reply is very slowly. Thank you very much if you give me some tips.

**Comment by reasonerjt** [comment]
@xiaochenluo I feel this has something to do with the OSS driver, and setting, maybe you can try to reach out to Aliyun?

**Comment by xiaochenluo** [comment]
@reasonerjt thank you. I will contact tech support of Aliyun

**Comment by reasonerjt** [comment]
Thanks @xiaochenluo I'm closing this issue for now.
