### ISSUE TITLE
Pulls number stays at 0?

### ISSUE THREAD

**Issue by shinebayar-g** [goharbor/harbor#6052]
I've just setup my harbor deployment successfully. However my *Pulls* numbers stays at 0.
How can I get it working?

**Comment by reasonerjt** [comment]
Please provide more information, what version are you using, what installer, did you pull with docker or other tools, etc,etc..

**Comment by shinebayar-g** [comment]
Hi, sure.
Version: harbor-online-installer-v1.6.0
I've used docker pull command to pull images to test Pulls counter.

**Comment by clouderati** [comment]
Did you upgrade from a previous version? I can't reproduce in my environment.

**Comment by shinebayar-g** [comment]
Ok, I've reviewed my installation. Issues seems should be resolved. I was misconfigured my config.yml file. (Using wrong yaml syntax).

**Comment by jakirpatel** [comment]
Umm I am facing same issue 
But not sure how you resolved? Could you please give more info?

**Comment by shinebayar-g** [comment]
First of all don't mess with default configs, try it and see it works or not. Then you can add your configs one by one. In my case, I was trying to add second notification endpoint. But I had type error in config.yaml file.
