### ISSUE TITLE
如何省略library

### ISSUE THREAD

**Issue by bo8888** [goharbor/harbor#6055]
现在只有tag 成172.16.8.8/library/aaa:1.10
才能push
能不能设置成  172.16.8.8/aaa:1.10 可以push
或者172.16.8.8/aaa:1.10 在push的时候自动push成172.16.8.8/library/aaa:1.10

谢谢。

**Comment by reasonerjt** [comment]
No, there's no way to that right now, and we don't plan to support it.

**Comment by iwin4aids** [comment]
This is very needed.....I use Habor as my private registry to be used by rancher/k8s..etc
The offline installer will only add the private registry address to image prefix like : 10.20.112.172/registry:2, but this image name can not push to Harbor, how can resolve this ?
