### ISSUE TITLE
Jobservice logging in Kubernetes

### ISSUE THREAD

**Issue by stevenewey** [goharbor/harbor#6056]
We use a modified version of the Helm chart at goharbor/harbor-helm to run Harbor in a Kubernetes cluster. We have an EFK stack used to gather stdout/stderr logs from all the containers running our services, as is pretty common.

It would be useful to be able to surface the per-job logging up through the stdout of the parent `harbor_jobservice` so that these logs could be collected via our normal process.

Is this possible to achieve at present? Looking at the logging configuration, it didn't seem to be. If not, would it be something you'd consider as a feature for the future?

**Comment by reasonerjt** [comment]
Currently there's no way to do that, you'll need to implement the interface:
https://github.com/goharbor/harbor/blob/master/src/jobservice/logger/interface.go#L6

To provide it as a feature require more consideration, currently we support user to download log of a job  via UI/API, redirect it to stdout may break this feature, maybe we can implement a logger to send message to multi-channel.

If you are interested in going deeper, feel free to open a proposal and we can discuss to find a solution.

**Comment by reasonerjt** [comment]
Let's use #6149 to track the resolution of this issue.

**Comment by steven-zou** [comment]
@stevenewey 
 STD logger is supported now. Refer to #6149.
