### ISSUE TITLE
[API-Test] [Auto] : Data type mismatch between implement and document in changing user role as sysadmin

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6066]
When I scripting API test of change-user-role-to-admin according to swagger code, there is a data type mismatch between implement and swagger document.

**Expected behavior and actual behavior:**
According to swagger document, HasAdminRole is integer , but the actual type is bool.
    HasAdminRole
    { 
        has_admin_role	integer  1-has admin, 0-not.
    }

**Steps to reproduce the problem:**
1. When set value is 1, got response of "Invalid json request"
{
	"has_admin_role": 1
}
2. When set value is true, got response of "200 OK"
{
	"has_admin_role": true
}
**Versions:**
Please specify the versions of following systems.
- harbor version: [Version v1.6.0-a69f8605]

**Comment by reasonerjt** [comment]
Thanks @danfengliu !

**Comment by wy65701436** [comment]
Done for PR https://github.com/goharbor/harbor/pull/6102
