### ISSUE TITLE
The project image repository description information supports Markdown syntax

### ISSUE THREAD

**Issue by duanhaiquan1** [goharbor/harbor#6076]
Installing harbor1.6 requires writing description information to the image. I prefer to use markdown syntax to describe, and I wonder if the author can make the system support markdown syntax

**Comment by zhoumeina** [comment]
@lweitzman , could you please make a mock picture for this project description?

**Comment by zhoumeina** [comment]
mockup link:
https://vmware.invisionapp.com/share/RKOJ1Q83XNS#/screens/327956758

**Comment by lweitzman** [comment]
@zhoumeina the link you provided now has the hint that markdown is supported.
