### ISSUE TITLE
global search returns 502 when input "re"

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#6081]
![image](https://user-images.githubusercontent.com/4946616/47193104-c4290800-d383-11e8-9cee-4b564f0ec89f.png)
![image](https://user-images.githubusercontent.com/4946616/47193109-cab77f80-d383-11e8-8011-06e631772f81.png)

**Comment by reasonerjt** [comment]
I think this is because some container is not running, could you check?

**Comment by zhoumeina** [comment]
Problems of the environment. Close it.
