### ISSUE TITLE
scan can not execute successfully

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#6084]
1 Login harbor with a normal user. 
2 Click into the details of the image. 
3 Click "scan" button. 
the scan api returns 403 

![image](https://user-images.githubusercontent.com/4946616/47194211-1587c600-d389-11e8-9ee7-4f32f6a5d346.png)
Here is the payload. 
![image](https://user-images.githubusercontent.com/4946616/47194240-2b958680-d389-11e8-8905-97c966d82bc2.png)

**Comment by reasonerjt** [comment]
This is an issue in UI after triage.

**Comment by zhoumeina** [comment]
fixed by #6112.
