### ISSUE TITLE
Could length of user name be longer

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#6086]
we use harbor as a docker registry and everyone in our system will have a harbor account.
but there is a conflict in the length of account, harbor has a restriction of max length 20 characters.
and in general 20 characters is too small to an account name when i use my email as account sometimes.
could this length be longer, like 64 characters?

**Comment by wy65701436** [comment]
@mmpei what's your harbor version?

**Comment by wy65701436** [comment]
The DB schema has already extended to 255, but the UI still validate max as 20 characters. It needs to align with backend. @ninjadq

**Comment by mmpei** [comment]
i  also fixed this issue. please check https://github.com/goharbor/harbor/pull/5873
