### ISSUE TITLE
Chinese translation of 'replication' and 'retag'

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#6089]
Currently, `replication` and `retag` in harbor are all translated as `复制` in harbor.

We should use other Chinese terms form them, one suggestion is:

`replication` --> `同步`, for example,  _镜像同步_
`retag`  --> `复制`, for example, _镜像复制_

One related issue: https://github.com/goharbor/harbor/issues/5688

Please give your suggestions here.

**Comment by wy65701436** [comment]
@steven-zou any thoughts?

**Comment by steven-zou** [comment]
+1
