### ISSUE TITLE
when redis_url config with dns name and redis passwd, jobservcice can't connect to redis server

### ISSUE THREAD

**Issue by KylanZhang** [goharbor/harbor#6090]
harbor.cfg:
#The redis server address. Only needed in HA installation.
#address:port[,weight,password,db_index]
#redis_url = redis:6379
redis_url =harbor.redis.cache.chinacloudapi.cn:6379,100,passwd,0

tail -200f /var/log/harbor/jobservice.log 
Oct 19 16:34:02 ip-172-18-0-1.cn-north-1.compute.internal jobservice[820]: 2018-10-19T08:34:02Z [FATAL] [service_logger.go:73]: Failed to load and run worker pool: connect to redis server timeout: dial tcp: lookup tcp/6379,100,passwd,0: Servname not supported for ai_socktype

**Comment by KylanZhang** [comment]
when use ip instead of dns name, it works.
when set redis without passwd and use dns mane, it works too.

**Comment by wy65701436** [comment]
@steven-zou please have a look.

**Comment by KylanZhang** [comment]
the registry has the same issue
