### ISSUE TITLE
Access control list.

### ISSUE THREAD

**Issue by SkazochnikZlodey** [goharbor/harbor#6091]
**Is your feature request related to a problem? Please describe.**

I have dev harbor qa harbor and prod harbor. 
on dev harbor i can setup access to AD users and disable public access. 
on qa harbor and prod harbor i also can setup access to AD users and disable public access but in this scenario qa docker swarm and prod docker swarm i`m  not sure that they will have access.

 **Describe the solution you'd like**

Will be nice to have possibility to setup trusted ips and trusted networks for:
1. synchronization (from dev hardor to qa harbor (one way) ; qa harbor can be only RO but dev harbor(s) still be able to push images(synchronization job ) and rest of allowed ips or networks can pull only as guest or with user credentials)
2. from allowed ips or networks dockers can pull images as guest or with user credentials 
may be nice to have private networks/ips and public is rest

But Grate job !!! Excellent product.

**Comment by reasonerjt** [comment]
I think you can setup different LDAP filters on different Harbor instances so that different users can access different instances.

For IP based filtering, I don't think it's in Harbor's scope, you may need to setup firewall to filter certain requests.

**Comment by SkazochnikZlodey** [comment]
Hello. Thanks for replay.
About your proposal.
1. different LDAP may be a solution. But will be nice to have competently  RO  registry with possibility to push images from trusted  servers 
2.  Some times servers with Harbor still have to allow special traffic from from server network (like monitoring) and disable traffic from/to monitoring server is a bad idea. So please find possibility to make changes in apache/nginx  config files from harbor to allow access only from special networks.

**Comment by clouderati** [comment]
Hi @SkazochnikZlodey – thanks for reaching out.

I do agree with @reasonerjt about scope here; we have to be careful not to try to boil the ocean. I suspect this is something we _could_ do but it might open a can of worms.

Is your idea to limit `push` / `pull` only? How about the UI? API access?

We'll have to think about this some more. Certainly not an unreasonable request, however, and we love community feedback. :smile: Looking forward to hearing some more of your thoughts on this.

**Comment by SkazochnikZlodey** [comment]
Hello @clouderati

My idea about push / pull only. Want split DEV QA and PROD images for containers. Sync between servers can can be allowed even push or poll is disabled .

**Comment by reasonerjt** [comment]
Per discussion with other maintainers the requirement can be met via setup firewalls to filter requests based on source.

Closing as won't fix.
