### ISSUE TITLE
Registries--Failed to ping endpoint.

### ISSUE THREAD

**Issue by smilesheep** [goharbor/harbor#6104]
I am using harbor :1.6.0 on the server 192.168.1.148 and 192.168.1.149
When I add NEW ENDPOINT to Registries on the server 192.168.1.148, after clicking TEST CONNECTION, I got the error "Failed to ping endpoint".
And what is shown in the log is :
"Oct 22 18:14:36 172.18.0.1 ui[9772]: 2018-10-22T10:14:36Z [ERROR] [target.go:65]: failed to ping target: Head http://192.168.1.149/v2/: Get http://192.168.1.149/v2/: dial tcp 192.168.1.149:80: getsockopt: no route to host"
What should I do ?

**Comment by wy65701436** [comment]
@smilesheep please provide details logs under /var/log/harbor

**Comment by smilesheep** [comment]
==> adminserver.log <==
Oct 23 10:37:44 172.18.0.1 adminserver[9772]: 172.18.0.7 - - [23/Oct/2018:02:37:44 +0000] "GET /api/configurations HTTP/1.1" 200 1751

==> proxy.log <==
Oct 23 10:37:45 172.18.0.1 proxy[9772]: 172.18.0.1 - "POST /api/targets/ping HTTP/1.1" 400 22 "http://192.168.1.148/harbor/registries" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.33 Safari/537.36" 1.019 1.019 .
Oct 23 10:37:48 172.18.0.1 proxy[9772]: 127.0.0.1 - "GET / HTTP/1.1" 200 1022 "-" "curl/7.59.0" 0.001 0.001 .

==> ui.log <==
Oct 23 10:37:18 172.18.0.1 ui[9772]: 2018/10/23 02:37:18 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    622.439µs|   match|#033[44m GET     #033[0m /     r:/#033[0m
**Oct 23 10:37:45 172.18.0.1 ui[9772]: 2018-10-23T02:37:45Z [ERROR] [target.go:65]: failed to ping target: Head http://192.168.1.149/v2/: Get http://192.168.1.149/v2/: dial tcp 192.168.1.149:80: getsockopt: no route to host**
Oct 23 10:37:45 172.18.0.1 ui[9772]: 2018/10/23 02:37:45 #033[1;44m[D] [server.go:2619] |     172.18.0.1|#033[43m 400 #033[0m| 1.018094297s|   match|#033[46m POST    #033[0m /api/targets/ping   r:/api/targets/ping#033[0m
Oct 23 10:37:48 172.18.0.1 ui[9772]: 2018/10/23 02:37:48 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    427.361µs|   match|#033[44m GET     #033[0m /     r:/#033[0m

==> adminserver.log <==
Oct 23 10:37:48 172.18.0.1 adminserver[9772]: 127.0.0.1 - - [23/Oct/2018:02:37:48 +0000] "GET /api/ping HTTP/1.1" 200 6

==> ui.log <==
Oct 23 10:37:48 172.18.0.1 ui[9772]: 2018/10/23 02:37:48 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    171.755µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m

**Comment by reasonerjt** [comment]
looks like a networking issue in your env.
