### ISSUE TITLE
[API-Test] [Auto] : 4 issues in swagger doc.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6105]
Here are 4 issues in swagger doc:

**1. Project metadata item definition in swagger is not corresponding with the implementation.**

**Steps to reproduce the problem:**
Call API: /projects/{project_id} GET

**Expected behavior and actual behavior:**

Expected behavior is:

    _"metadata": {
               "auto_scan": "true",
               "enable_content_trust": "true",
               "prevent_vul": "false",
               "public": "false",
               "severity": "low"
           }_
Actual behavior is:

    _"metadata": {
      "public": "string",
      "enable_content_trust": "string",
      "prevent_vulnerable_images_from_running": "string",
      "prevent_vulnerable_images_from_running_severity": "string",
      "automatically_scan_images_on_push": "string"
    }_

**2. When getting a certain user by id, API didn't return data value.**

**Steps to reproduce the problem:**
Call API: /users/{user_id} GET

**Expected behavior and actual behavior:**

Expected behavior is:

    _{
    "user_id": 5,
    "username": "user003",
    "email": "Luca@vmvare.com",
    "password": "",
    "realname": "Luca",
    "comment": "",
    "deleted": false,
    "role_name": "",
    "role_id": 0,
    "has_admin_role": false,
    "reset_uuid": "",
    "creation_time": "2018-10-16T02:43:23Z",
    "update_time": "2018-10-16T02:43:23Z"
    }_

Actual behavior is:

    _NULL_

**3. When update project info, the giving body include project name, but it's not editable indeed.**

**Steps to reproduce the problem:**
Call API: /projects/{project_id} PUT

**Expected behavior and actual behavior:**

Expected behavior is:

    _{
    "metadata": {
    "public": "string",
    "enable_content_trust": "string",
    "prevent_vulnerable_images_from_running": "string",
    "prevent_vulnerable_images_from_running_severity": "string",
    "automatically_scan_images_on_push": "string"
    }
    }_
Actual behavior is:

    _{
    "project_name": "string",
    "metadata": {
    "public": "string",
    "enable_content_trust": "string",
    "prevent_vulnerable_images_from_running": "string",
    "prevent_vulnerable_images_from_running_severity": "string",
    "automatically_scan_images_on_push": "string"
    }
    }_

**4. Attribute "owner_name" in project has not been used, it should be removed from swagger .**
      Note: This issue has been fixed in #6103.

**Steps to reproduce the problem:**
Call API: /projects/{project_id} GET

**Expected behavior and actual behavior:**

Expected behavior is:

    _{
    "project_id": 2,
    "owner_id": 1,
    "name": "project_dan",
    "creation_time": "2018-10-15T10:14:06Z",
    "update_time": "2018-10-15T10:14:06Z",
    "deleted": false,
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 0,
    "chart_count": 0,
    "metadata": {
        "public": "false"
    }
    }_
Actual behavior is:

    _{
    "project_id": 2,
    "owner_id": 1,
    "name": "project_dan",
    "creation_time": "2018-10-15T10:14:06Z",
    "update_time": "2018-10-15T10:14:06Z",
    "deleted": false,
    "owner_name": "",
    "togglable": true,
    "current_user_role_id": 1,
    "repo_count": 0,
    "chart_count": 0,
    "metadata": {
        "public": "false"
    }
    }_

**Versions:**
Version v1.6.0-2891ab28

**Comment by wy65701436** [comment]
thanks @danfengliu
