### ISSUE TITLE
Failed to ping endpoint. 

### ISSUE THREAD

**Issue by jinjie2088** [goharbor/harbor#6111]
I change the nginx default port 80, i cannt add endpoint. "Failed to ping endpoint."

Request URL: http://10.0.251.178/api/targets/ping
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 10.0.251.178:80
Referrer Policy: no-referrer-when-downgrade

{endpoint: "http://xx.xx.xx.xx:8888", name: "", username: "admin", password: "xxxxxx", type: 0}
endpoint: "http://xx.xx.xx.xx:8888"
name: ""
password: "xxxxxxxx"
type: 0
username: "admin"

Version  1.2.0

**Comment by jinjie2088** [comment]
> please help to provide logs under /var/log/harbor

which one?

**Comment by jinjie2088** [comment]
in proxy.log
Oct 23 14:56:17 172.18.0.1 proxy[21080]: 192.168.7.149 - "POST /api/targets/ping HTTP/1.1" 500 199 "http://10.0.251.178/harbor/replications/endpoints" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36" 0.029 0.029 .

**Comment by wy65701436** [comment]
@jinjie2088 all of them would be helpful.

**Comment by jinjie2088** [comment]
endpoint log
[2018-10-23.tar.gz](https://github.com/goharbor/harbor/files/2504897/2018-10-23.tar.gz)

**Comment by clouderati** [comment]
@jinjie2088 can you please clarify how / why you changed the port? Is the protocol set to `http` in `harbor.cfg`?

**Comment by jinjie2088** [comment]
no,i only channged the map port. e.g: - 8888:80

**Comment by clouderati** [comment]
Can you be a bit more specific? I'm still a bit confused. 😦  You changed the port mapping on which container? Was the mapping changed via the `docker-compose` config?
