### ISSUE TITLE
test connection success,but replication error

### ISSUE THREAD

**Issue by watchmen1992** [goharbor/harbor#6120]
The Error information ：

2018-10-23T14:16:21Z [INFO] initializing: repository: apps/hello-world, tags: [latest], source URL: http://registry:5000, destination URL: https://harbor2.wxh.com, insecure: true, destination user: admin
2018-10-23T14:16:21Z [INFO] initialization completed: project: apps, repository: apps/hello-world, tags: [latest], source URL: http://registry:5000, destination URL: https://harbor2.wxh.com, insecure: true, destination user: admin
2018-10-23T14:16:37Z [ERROR] [transfer.go:205]: an error occurred while creating project apps on https://harbor2.wxh.com with user admin : Post https://harbor2.wxh.com/api/projects/: EOF
2018-10-23T14:16:37Z [INFO] waiting for retrying...

base info:
1. the version of the harbor is 1.4.0 （two sides are the same configuration.）
2. I have unchecked Verify Remote Cert. The connection to the endpoint is successful when testing

**Comment by watchmen1992** [comment]
what should i do?

**Comment by clouderati** [comment]
Hi @watchmen1992 – can you confirm there aren't any other relevant logs?

**Comment by watchmen1992** [comment]
> Hi @watchmen1992 – can you confirm there aren't any other relevant logs?

> Hi @watchmen1992 – can you confirm there aren't any other relevant logs?

the log directory:
[root@harbar harbor]# pwd;ls
/var/log/harbor
adminserver.log  jobservice.log  mysql.log  proxy.log  registry.log  ui.log

I can't find any other useful logs.
which logs do you want，I can get it to you
What kind of log do you want,  I can think of a way to give it to you

you can also contact me directly.  my wechat id:    xh568100840

**Comment by watchmen1992** [comment]
@clouderati 

the log directory:
[root@harbar harbor]# pwd;ls
/var/log/harbor
adminserver.log  jobservice.log  mysql.log  proxy.log  registry.log  ui.log

I can't find any other useful logs.
which logs do you want，I can get it to you
What kind of log do you want,  I can think of a way to give it to you

you can also contact me directly.  my wechat id:    xh568100840

**Comment by watchmen1992** [comment]
@clouderati 

the log directory:
[root@harbar harbor]# pwd;ls
/var/log/harbor
adminserver.log jobservice.log mysql.log proxy.log registry.log ui.log

I can't find any other useful logs.
What kind of log do you want, I can think of a way to give it to you

you can also contact me directly. my wechat id: xh568100840

**Comment by cd1989** [comment]
Can you share log of harbor ui in target harbor (harbor2 in your case)

**Comment by moooofly** [comment]
hi, @watchmen1992 

Is there any progress on this issue?

**Comment by watchmen1992** [comment]
it Solved. I have problems with configuration.
set up  unchecked Verify Remote Cert is not enough

please create this file and restart docker 

[root@harbor2 ~]# cat /etc/docker/daemon.json
{
  "insecure-registries" : ["harbor2.wxh.com","harbor.wxh.com"]
}
