### ISSUE TITLE
automatically check for / execute updates

### ISSUE THREAD

**Issue by clouderati** [goharbor/harbor#6121]
Harbor should automatically check for updates and notify the user if a new(er) release is available.

Some other things we should consider in the future (post-MVP):
* Multiple "channels" such that a user can run {alpha,beta}-ish versions if desired
* The ability to update with one click via UI
* The ability to update via a single API call
* The ability to update via a `harborctl` command

Breaking this down, the first thing to start working on is pinging an API endpoint for updates. I'll keep this issue open to track work and check work items off as needed.

**Comment by reasonerjt** [comment]
@clouderati what deployment should this feature target?

This seems requires external tool to manage the lifecycle of Harbor, rather than enabling it from within Harbor UI.

**Comment by clouderati** [comment]
Was just brainstorming when I opened this. Will give this some more thought and open proposal to further discuss.

**Comment by upics** [comment]
Any update on this ?
