### ISSUE TITLE
Harbor should allow configure storage options through UI (S3,GCP,Azure)

### ISSUE THREAD

**Issue by jakirpatel** [goharbor/harbor#6123]
**Is your feature request related to a problem? Please describe.**
Currently, the Harbor UI does not allow the configuration of storage options with the UI. 

**Describe the solution you'd like**
Harbor should call API and get the details of the S3, GCP and Azure bucket related details. It will not only configure the storage but will help admin to check the details of the storage. 

Like: Bucket name, Region of the bucket, Storage used, Tagging the bucket with a different environment (Dev / QA / Prod). 

**Additional context**
It is really important to have the details related with storage to be displayed to admin.

**Comment by reasonerjt** [comment]
One gap here is that Harbor does not manage the lifecycle of itself, and the storage settings are for other containers, such as registry/chartmuseum.   So it may not be "configurable" on Harbor UI.

**Comment by jakirpatel** [comment]
@reasonerjt 

Thank you for your reply. If the lifecycle is not managed by the harbor for storage then I think I am okay with configuration file itself.

**Comment by clouderati** [comment]
Hi @jakirpatel – I like the idea of surfacing some of this information via UI / API.

@goharbor/all-maintainers any objections in doing so?
