### ISSUE TITLE
Web hook doesn't work on periodic job in JS

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6128]
The scheduled job cannot have staus updated by web hook. 

The url of web hook is dropped by job service, this should be fixed as a high priority.

![image](https://user-images.githubusercontent.com/2841473/47422950-731b7880-d7b6-11e8-9440-c798c9619a4b.png)

Harbor Version: Version v1.6.0-13023538

**Comment by steven-zou** [comment]
Enhance webhook in PR #6174. Close it now.
