### ISSUE TITLE
YAML syntax issue in registry storage config, unused declared variable

### ISSUE THREAD

**Issue by johnrkriter** [goharbor/harbor#6137]
**Steps to reproduce the problem:**
During the installation of 1.6.1 from offline installer, we changed the default configuration for the registry(@ common/templates/registry/config.yml) contains the following lines

```storage:
  cache:
    layerinfo: redis
  $storage_provider_info
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
```

When changing this to use an S3 backend, the following code was modified
```storage:
  s3:
    accesskey: NICE TRY
    secretkey: NO HACKS FOR YOU
    region: ap-southeast-1
    bucket: real-bucket.s3  
  cache:
    layerinfo: redis
  $storage_provider_info
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
```

**Expected behavior and actual behavior:**
Expected: the registry service to start and store items in the S3

Actual: container restarts continuously, giving the below error.
```Oct 25 04:41:22 ip-172-18-0-1.ap-southeast-1.compute.internal registry[4219]:
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]: configuration error: error parsing /etc/registry/config.yml: Must provide exactly one storage type. Provided: [s3 filesystem]
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]:
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]: Usage:
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]:   registry serve <config> [flags]
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]: Flags:
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]:   -h, --help=false: help for serve
Oct 25 04:43:57 ip-172-21-0-1.ap-southeast-1.compute.internal registry[4219]:
```
After removing this one line ` $storage_provider_info` the tool started fine with what appears to be no issue.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.6.1]
- docker engine version: [18.06.1-ce, build e68fc7a]
- docker-compose version: [1.22.0, build f46880f]
- OS: Amazon Linux

**Comment by wy65701436** [comment]
did you execute the prepare after the modification?

**Comment by ywk253100** [comment]
Remove the `$storage_provider_info` line.

**Comment by ywk253100** [comment]
You can find the final version which is rendered in the directory `common/config/registry/config.yml`

**Comment by johnrkriter** [comment]
> You can find the final version which is rendered in the directory `common/config/registry/config.yml`

@ywk253100 Is this line removed by the install or prepare process? Because OOB its there in the template. I found that after a clean install this line is still in the generated config.yml

**Comment by ywk253100** [comment]
The files in directory `common/templates` are the templates, the `prepare` script will render them into the directory `common/config`. The `$storage_provider_info` line will be replaced by the real configuration.

Btw, you can configure the storage in `harbor.cfg` by `registry_storage_provider` section.

**Comment by ywk253100** [comment]
Run `prepare` script is necessary when re-configuring.
