### ISSUE TITLE
1.6.1 psuh images 到仓库报错The push refers to repositoryreceived unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by duanzhanling** [goharbor/harbor#6141]
1.6.1 psuh images 到仓库报错
docker push docker.ilanni.com/alpine:latest The push refers to repository [docker.ilanni.com/alpine] df64d3292fd6: Retrying in 1 second  received unexpected HTTP status: 500 Internal Server Error

**Comment by wy65701436** [comment]
please provide more details and logs.

**Comment by duanzhanling** [comment]
@wy65701436 如何查看日志？提供哪些日志？

**Comment by duanzhanling** [comment]
此issue关闭，发现原来是因为没有创建项目导致。
