### ISSUE TITLE
connect api failed after restart docker

### ISSUE THREAD

**Issue by daixiang0** [goharbor/harbor#6143]
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

Config docker daemon "live-restore" as true, then restart docker.

Harbor container is healthy but api can not connect.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.5
- docker engine version: 18.03.1-ce
- docker-compose version: 1.16.1

**Comment by daixiang0** [comment]
@ywk253100 Please take a look at this issue, thanks

**Comment by beeeeeeenny** [comment]
@daixiang0 I also encountered this problem, how can you solve it?

**Comment by daixiang0** [comment]
remove  "live-restore"  in docker daemon config is a workround.

**Comment by daixiang0** [comment]
@ywk253100 @reasonerjt hi, any input?

**Comment by beeeeeeenny** [comment]
In addition to connecting API fails after restart docker daemon, I execute **docker exec** command, I get an error: 

```shell
$> docker exec -it harbor-db bash
invalid container: dec8c4e261f4dc79d3bb7c80959e065efbb36a38b282521bd3b0bf11a6ceb873
```

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
update
