### ISSUE TITLE
Strore logs of JobService into DB, and make js stateless

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#6144]
Logs of JobService is still stored in local filesystem in V1.6, and this makes JS statefull.
Could these logs be stored in postgres? and if that deploying a HA environment will become more simple.
What's the official plan of this feature? and is storing logs in DB feasible?
I would like to do some distribution to this festure.

**Comment by steven-zou** [comment]
stdout and stderr can be used.

**Comment by mmpei** [comment]
i mean the job logs in directory /data/job_logs. move these files into DB and no need to NFS when deploy JobService.

**Comment by clouderati** [comment]
Not sure about storing logs in DB. Agreed with @steven-zou that `stdout` and `stderr` can be used for now.

@mmpei – what precisely are you trying to accomplish?

**Comment by steven-zou** [comment]
@mmpei 

If you want to store logs in the db, now you can start the work. Please refer to https://github.com/goharbor/harbor/tree/master/src/jobservice

**Comment by mmpei** [comment]
closed
