### ISSUE TITLE
[1.4.0] How to achieve one target URL copy multiple projects

### ISSUE THREAD

**Issue by watchmen1992** [goharbor/harbor#6145]
A target URL can only create one project
When I add second iproject, I make a mistake.
How can i achieve it

![repl-error](http://picture.watchmen.xin/harbor/repl-error.jpeg)

**Comment by watchmen1992** [comment]
![image](https://user-images.githubusercontent.com/28006018/47501412-0a0c3180-d898-11e8-99db-8c312a281b0b.png)

**Comment by watchmen1992** [comment]
When I add the second project, I show this error.

**Comment by watchmen1992** [comment]
When I add the second project, I show this error. 
The target URL is the same as before config

**Comment by wy65701436** [comment]
This is not supported yet.

**Comment by watchmen1992** [comment]
> You should create multiple replication rules which reference the same target.

how to create it? can you show your web page.
in my case[1.4.0]，i cann't create the rules that you say
