### ISSUE TITLE
LDAP group support for Oracle LDAP

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#6156]
Is there any plan to support Oracle LDAP? group membership for Harbor 1.6.0 is not compatible with Oracle LDAP.

Thanks.

**Comment by roldancer** [comment]
We use Oracle Directory Server Sun-Directory-Server/11.1, for group membership Oracle uses the virtual attribute "isMemberOf" by default.

I was looking at the Harbor's source code, the "memberOf" virtual attribute is hardcoded, If the group membership attribute were a Harbor's parameter it would be much more compatible with other LDAP's providers.

**Comment by roldancer** [comment]
Pull request sent https://github.com/goharbor/harbor/pull/6161

**Comment by clouderati** [comment]
Discussing implementation details in https://github.com/goharbor/harbor/pull/6161.

**Comment by stonezdj** [comment]
Because the configuration framework is refactored, this should be a user setting and need to configured in web ui, defer to 1.8 release
