### ISSUE TITLE
lose image tag data after database migration 

### ISSUE THREAD

**Issue by justinmjc** [goharbor/harbor#6157]
the offical migration  tool is not suit for HA architecture，so I use the migration  tool manual

 I just migrate  mysql data from harbor1.5.0 to pgsql 1.6.1,after I migrated,the data is normal except image tag ,all image tag is zero 

I want to figure out where the data of image tag store .

tks!

**Comment by wy65701436** [comment]
as confirmed with @justinmjc , it's not a DB issue. 

@justinmjc please debug on the regsitry API call, if still encounter any issue, feel free to file another issue.

**Comment by justinmjc** [comment]
Thanks to yan @wy65701436 
the root case is  the wrong configuration of registry which at  harbor/common/config/registry/config.yml 
after I correct it ,Harbor runs well.
