### ISSUE TITLE
Retag should not be allowed for Guest role

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6168]
Steps to reproduce:
1, Log in as a guest.
2, Go into the library -- public project.
3, Retag is enable for me.

Expected:
Retag should be disabled for the guest user.

**Comment by reasonerjt** [comment]
@wy65701436 Does the API blocks `guest`?

**Comment by cd1989** [comment]
The API blocks guest, but the portal UI didn't.

**Comment by steven-zou** [comment]
@cd1989 

Seems the API does not block the request fired by a user with a guest role.
