### ISSUE TITLE
Dead loop redis event after fired demo job

### ISSUE THREAD

**Issue by Colstuwjx** [goharbor/harbor#6178]
**Expected behavior and actual behavior:**
expect job service could receive cancel job event, and do CancelJob at once.

**Steps to reproduce the problem:**
```
POST /api/v1/jobs/a5fe27325fbfb9a5df7f9e2a
{
    "action": "stop"
}
```

**Versions:**
- job service: [v.1.6.1]

**Additional context:**
I'm running the raw job service, and want to use it as back service just sth like celery, and I found that there is dead loop events while do canceljob or stopjob.

steps are:
1. we fired job operations, and redis pool received at [here](https://github.com/goharbor/harbor/blob/v1.6.1/src/jobservice/pool/redis_pool.go#L135);
2. gcwp do [`SendCommand`](https://github.com/goharbor/harbor/blob/v1.6.1/src/jobservice/pool/redis_pool.go#L606);
3. at redis stats mgr, we `fired` msg at [here](https://github.com/goharbor/harbor/blob/v1.6.1/src/jobservice/opm/redis_job_stats_mgr.go#L221), and it [published to redis channel](https://github.com/goharbor/harbor/blob/v1.6.1/src/jobservice/opm/op_commands.go#L90)
4. and redis pool received msg again...

so why we need to fire this again and again? or there is something which i misunderstand?
Thanks.

**Comment by steven-zou** [comment]
It's a bug, fixed in this PR https://github.com/goharbor/harbor/pull/6174
