### ISSUE TITLE
[HA] Scan now could multiple click

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6180]
The "Scan Now" is designed by a single click within a period of time, but in HA scenario, it could multiple click.

![image](https://user-images.githubusercontent.com/2841473/47768105-83c97280-dd11-11e8-9af3-a750cab9406d.png)

**Comment by reasonerjt** [comment]
The time for next valid scan all is currently stored in memory, which causes issue in HA deployment, I'll see if that can be stored in DB.

**Comment by reasonerjt** [comment]
Per discussion we decide to remove the restriction to disable the button, instead let job service control the uniqueness of such job, for details see #6194

**Comment by reasonerjt** [comment]
Fixed in #6399 and #6460
