### ISSUE TITLE
[API-Test] [Auto] : When calling POST API of <add label to a image> by an unauthorised user, the error message is not readable for end user. 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6185]
Steps to reproduce the problem:
Call API: /repositories/{repo_name}/tags/{tag}/labels POST

Expected behavior is:

    _"User XXX was not authorized to perform this operation."_

Actual behavior is:

    _"{"error":"user001"}"_

Versions:
Version v1.6.0-2891ab28

**Comment by danfengliu** [comment]
Another issue in this API,  which is that parameter "label" was passed to harbor as form of json structure, but this json data is useless except the label_id item, and also if I passed an invalid json data, the return value is not readable for end user too:

**Steps to reproduce the problem:**
Call API: /repositories/{repo_name}/tags/{tag}/labels POST
POST Data Body: 

    _{
       "a":1
    }

**Expected behavior is:**

    _"Invalid request parameters"_

**Actual behavior is:**

    _"{"error":"not found: label '0'"}"_

**Versions:
Version v1.6.0-2891ab28**

**Comment by bansalrajat** [comment]
Any Solution on adding the label via api ?
