### ISSUE TITLE
Harbor through Proxy and  Vulnerability database might not be fully ready! 

### ISSUE THREAD

**Issue by egnidina** [goharbor/harbor#6199]
Hi all! 
We use Harbor with PKS. I make this settings 
![image](https://user-images.githubusercontent.com/42407450/47873892-72708b00-de23-11e8-94d5-9b461b8c011a.png)

And list for access:

Ubuntu | https://launchpad.net/ubuntu-cve-tracker
Red Hat Enterprise Linux | https://www.redhat.com/security
Oracle | https://linux.oracle.com/oval
Debian | https://security-tracker.debian.org
Alpine | https://git.alpinelinux.org
National Vulnerability Database | http://static.nvd.nist.gov
CVE information | https://cve.mitre.org/

But I see this error "Vulnerability database might not be fully ready!"

**Comment by reasonerjt** [comment]
Hi, for questions regarding Harbor tile please reach out the support channel, this repo is for OSS project.

**Comment by clouderati** [comment]
Closing issue as per @reasonerjt's comment.
