### ISSUE TITLE
Search API  cat not get repo infomation.

### ISSUE THREAD

**Issue by mr1way** [goharbor/harbor#6204]
My harbor upgrade from 1.1.1 to 1.3.0 .
Curl api with following command:
  curl http://xx.xx.xx/api/search?q=ths/website-datacenter-back
The result:
 {
  "project": [],
  "repository": []
}
The project is public and my login user is admin.
Some other projects can get correct result.

**Comment by clouderati** [comment]
Hi @mr1way – so the search only fails on _some_ projects? Did this work before the upgrade?

**Comment by mr1way** [comment]
@clouderati Yeah!Only fails on some projects.But I am not sure if it works before the upgrade.
