### ISSUE TITLE
Contributing version matrix out of date

### ISSUE THREAD

**Issue by SDBrett** [goharbor/harbor#6208]
The CONTRIBUTING.md file has version matrixes for Habour and GO and Web which only go up to Harbor 1.4. 

Can these be updating to include newer versions?

Snippets below.

#### Go

|  Harbor  |  Requires Go  |
|----------|---------------|
|   1.1    |    1.7.3      |
|   1.2    |    1.7.3      |
|   1.3    |    1.9.2      |
|   1.4    |    1.9.2      |

#### Web

|  Harbor  |  Requires Angular  |  Requires Clarity  |
|----------|--------------------|--------------------|
|   1.1    |      2.4.1         |       0.8.7        |
|   1.2    |      4.1.3         |       0.9.8        |
|   1.3    |      4.3.0         |       0.10.17      |
|   1.4    |                    |                    |

**Comment by steven-zou** [comment]
Already under working, please refer to PR https://github.com/goharbor/harbor/pull/6133.

This issue will be closed.
