### ISSUE TITLE
No definition for delete action of policy-replication in swagger doc.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6210]
Steps to reproduce the problem:

Looking for <Delete /policies/replication/{id}>, but it's not in swagger doc.

Versions:
Version v1.6.0-2891ab28

**Comment by moooofly** [comment]
Find the same issue and mark it [here](https://github.com/moooofly/harborctl/issues/32) (test by `harborctl`)

**Comment by wy65701436** [comment]
close as fixed.
