### ISSUE TITLE
镜像同步问题

### ISSUE THREAD

**Issue by sumeng001** [goharbor/harbor#6211]
老仓库空间满了（1.6T）使用gc清空了300G空间后剩余1.3T空间，然后同步新仓库（新仓库为全新的）；同步完成后新仓库使用空间为400G。
对比差异：
老仓库1.3T
新仓库400G
同步方式：
使用harbor自带同步方式
版本：
v1.4.0

**Comment by Ghostbaby** [comment]
1.检查下job有没有失败，
2.检查镜像数量是否一致，
3.检查镜像是否可用。

这几个步骤都检查没有问题，那就放线上跑两天，如果有报错再切回去。

**Comment by sumeng001** [comment]
1.job没有失败
2.镜像数量一致
3.镜像可用
我怀疑是gc没有清理干净哈希码，所以导致老仓库数据量还是很高的缘故；希望可以给一个答案

**Comment by Ghostbaby** [comment]
确实有这个问题，gc不干净。
清理策略也是个很重要的环节。
最好保留最小镜像数量，再确保线上环节正常使用情况下。
我的方案是增加归档节点，归档节点保留尽可能多的镜像。
