### ISSUE TITLE
Is there a way to put the volumes on another machine?

### ISSUE THREAD

**Issue by stevenyslins** [goharbor/harbor#6213]
Dear all,

If I have two machine and the setting as following:
A_machine : 192.168.2.100
B_machine : 192.168.2.101

Is there a way that the harbor service run on machine_A and the volumes put on B_machine ?
Because machine_A has very little storage space, so that I need to put the docker images on another space.

Thank you for your help.

**Comment by clouderati** [comment]
I suppose you could try NFS, though I'm not sure that we've tested it. @reasonerjt is this something we've tested at any point? (I suspect not)
