### ISSUE TITLE
harbor should be able to replicate images to other registries

### ISSUE THREAD

**Issue by yuanshuhan** [goharbor/harbor#6226]
**Is your feature request related to a problem? Please describe.**
In hybrid cloud scenario, we may need to synchronize harbor images to public cloud. However it is impossible to replicate harbor images to a different kind of registry.

**Describe the solution you'd like**
It will be great, if harbor can replicate images to other registries. 

**Describe the main design/architecture of your solution**
When harbor user submit an replicate job, it should be able to input a project as destination, for different registries may have different structure.
Harbor should public the interface standard, for those repositories who need to support harbor image replication service. 

**Describe the development plan you've considered**
tbd

**Additional context**
N/A

**Comment by clouderati** [comment]
Hi @yuanshuhan – this is on my todo list. Hopefully something I can get around to by the end of the year. If you're interested in contributing please let me know and I'm happy to help you through the process.

**Comment by steven-zou** [comment]
@clouderati 

  I have discussed such topic with @yuanshuhan team before. Currently, we're talking about the potential cooperation way in future. I'm proposing to build a sub-workgroup composed of teams who have strong requirements on the replica feature. The workgroup will focus on improving and promoting the replica feature. @yuanshuhan team (from huawei) may be the core part of this group.

**Comment by clouderati** [comment]
Sounds great, thanks @steven-zou. Does it make sense to spin up a discussion in `goharbor/community` and use that as a forum to discuss the various concrete use cases and implementation details?

Excited to see this ball rolling.

**Comment by steven-zou** [comment]
@clouderati 

  They're preparing to submit a MD proposal to `goharbor/community`.
