### ISSUE TITLE
Wrong image scan report after updating the clair CVE DB

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#6230]
My harbor version is release-1.6.0-rc2.
First, i setup my harbor evironment, and there are some problems with clair CVE repositry Initilization.
So all images don't have any vulnerability after scaning.
i set the clair Updater config parameter to 2h as following,
`updater:
    interval: 2h`.
after more then 2 hours, i found that the scan_overview in tag seems no vulnerability, but the vulnerability/details inspecify that there are some vulnerabilitys. see the picture below:
![default](https://user-images.githubusercontent.com/30788120/48066981-0a96b780-e20a-11e8-9072-86c68b07f2b2.png)

config:
autoScan : false
![default](https://user-images.githubusercontent.com/30788120/48067059-43369100-e20a-11e8-890e-617d52c1be66.png)

**Comment by reasonerjt** [comment]
The reason to this issue may be that Harbor's scan job handler will calculate the scan result to generate an "overview" data object.  When the vuln data is not ready on Clair there's no data when generating the "overview".   On the other hand the detail data from Clair API, so after the vuln data update you see several vulnerabilities in the details page.

After Clair's updater retrieve the vuln data from internet, it sends a webhook and Harbor will refresh the "overview".  However, I suspect Clair may not send webhook in its "first" update, if so, this may be a limitation.

**Comment by mmpei** [comment]
if Scaning image not triggered, why these vulnerability details show and related to a certain image?

**Comment by reasonerjt** [comment]
Because the details is stored in Clair's DB, so it shows as the Clair updates vuln data, and associate the vuln to the packages incrementally.

However the overview ,i.e. the number of each level of vuln is calculated when the image is scanned, in your issue it happened when there's no data in Clair. 
So you'll need to rescan to let it recalculate.

**Comment by mmpei** [comment]
OK. i have known the work flow of clair CVE DB update. and this is maybe caused by the failed clair notification, and root cause is network error or some wrong configuration.
i will retrigger the scan. and  thank you @reasonerjt
