### ISSUE TITLE
Helm Chart auto sync from git

### ISSUE THREAD

**Issue by whybeyoung** [goharbor/harbor#6232]
**Is your feature request related to a problem? Please describe.**
when we developing the chart , we always manage the chart as code in git, but when we use it to harbor, we should upload it to harbor, and we should do it by hand.  usually during the development, chart is always change without stable, we may use diffrent version , it's very unconvienient.

**Describe the solution you'd like**
When we develop chart and manage it with git, for example, gogs or gitlab.
we can add a webhook to call the harbor api which implement the version 
synchronization . If we change the chart itself with the same chart version, harbor could update the change and use the git commit id to idenfify the chart version, if we change chart's version, harbor can add new version chart from the git....
all in all, we should have a way to sync the chart ,otherwise , we may be confused about managing chart with harbor and git..

**Comment by steven-zou** [comment]
@berlinsaint 

I think it's really a good idea. We can think more together. And a quick question, is it possible for you or your team to work on such a good idea and do contributions to Harbor community? If yes, that would be great. You can write a MD proposal and raise PR to the [goharbor/community](https://github.com/goharbor/community) repo. Looking forward to hearing more. Thanks.

**Comment by steven-zou** [comment]
Transfer all the requirements to @xaleeks for tracking.

**Comment by shashank-k** [comment]
Is there any update on this?

**Comment by basil1120** [comment]
Is there any update on this. Am not able to SYNC my helm charts from Azure (ACR) to harbor. On the replication menu its only allowing me to sync / replicate images alone the charts is grayed out

**Comment by wy65701436** [comment]
hi @basil1120 harbor doesn't support oci compitable chart replication, and the chartmuseum is planned to be removed from v2.8. 

We suggestion you can use the helm v3.7+ to manage the  oci compitable chart rather than the chartmuseum chart.
