### ISSUE TITLE
Creating Autamation Build

### ISSUE THREAD

**Issue by abhilash07** [goharbor/harbor#6235]
hi everyone, harbor is been a great enterprise grade opensource for managing docker images. 

As per my knowledge there is know any docker image automation build in harbor.

Now i am thinking about if harbor have automation docker images build same like docker hub, is it possible ?.

Are is there any  reference for this feature. 

Thanks in advance

**Comment by stonezdj** [comment]
Harbor does not include any docker build related feature so far.  it is possible to extend harbor with this feature.

**Comment by xaleeks** [comment]
The build phase of the container delivery ecosystem is not in our focus right now so closing this for now.  On this front, we are instead looking to build better integrations with github and gitlab through build triggers. @abhilash07
