### ISSUE TITLE
environment variables for configuring docker-compose files

### ISSUE THREAD

**Issue by kyrogue** [goharbor/harbor#6243]
Hi, is it possible to implement the ability to pass in environment variables to the docker-compose.yml file to configure the volumes directories for the containers? This is mainly to provide the option to use another volume instead of /data/ 

I am thinking of https://docs.docker.com/compose/environment-variables/

**Comment by stonezdj** [comment]
Yes, it is possible

**Comment by kyrogue** [comment]
i think it would make more sense to also move the configuration into harbor.cfg, for defining the directory for /data and /logs, this way we would have one central location (harbor.cfg) to configure the docker-compose files.

**Comment by reasonerjt** [comment]
This should be covered in the WIP for prepare refactory.  
After that there will be more flexibility in configuration.
@ninjadq please dup this requirement.

**Comment by ninjadq** [comment]
dup to #6620
