### ISSUE TITLE
python bug

### ISSUE THREAD

**Issue by fengzhao** [goharbor/harbor#6244]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.5.4]
- docker engine version: [18.09.0]
- docker-compose version: [1.18.0]
- python:[ 3.6.7]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

it seems a python  bugs ! 

root@followme:/tmp/harbor# ./install.sh 

[Step 0]: checking installation environment ...

Note: docker version: 18.09.0

Note: docker-compose version: 1.18.0

[Step 1]: loading Harbor images ...
Loaded image: vmware/harbor-jobservice:v1.5.4
Loaded image: vmware/harbor-adminserver:v1.5.4
Loaded image: vmware/harbor-db:v1.5.4
Loaded image: vmware/redis-photon:v1.5.4
Loaded image: vmware/nginx-photon:v1.5.4
Loaded image: vmware/clair-photon:v2.0.6-v1.5.4
Loaded image: vmware/harbor-ui:v1.5.4
Loaded image: photon:1.0
Loaded image: vmware/notary-server-photon:v0.5.1-v1.5.4
Loaded image: vmware/mariadb-photon:v1.5.4
Loaded image: vmware/harbor-log:v1.5.4
Loaded image: vmware/registry-photon:v2.6.2-v1.5.4
Loaded image: vmware/notary-signer-photon:v0.5.1-v1.5.4
Loaded image: vmware/postgresql-photon:v1.5.4
Loaded image: vmware/harbor-migrator:v1.5.0

[Step 2]: preparing environment ...
Clearing the configuration file: ./common/config/nginx/nginx.conf
Clearing the configuration file: ./common/config/adminserver/env
Clearing the configuration file: ./common/config/ui/env
loaded secret from file: /data/secretkey
Generated configuration file: ./common/config/nginx/nginx.conf
Generated configuration file: ./common/config/adminserver/env
Generated configuration file: ./common/config/ui/env
Traceback (most recent call last):
  File "./prepare", line 406, in <module>
    [storage_provider_name + ':'] + map(string.strip() , storage_provider_config.split(",")))
AttributeError: module 'string' has no attribute 'strip'

**Comment by stonezdj** [comment]
Please use python 2, not python 3.

**Comment by wy65701436** [comment]
this was fixed in release 1.6.0, see the PR. https://github.com/goharbor/harbor/issues/5053
Please try with version > v1.5.0 or change to python2 to run prepare v1.5.4

**Comment by fengzhao** [comment]
> Please use python 2, not python 3.
你可以看看这个文档
https://wiki.python.org/moin/Python2orPython3

**Comment by fengzhao** [comment]
demo
