### ISSUE TITLE
Swagger generate wrong tag scan definition

### ISSUE THREAD

**Issue by Nefelim4ag** [goharbor/harbor#6252]
Your backend, expects that header in POST request to image scan endpoint:
```
Content-Type: application/json
```

I've try fix swagger definition, but it looks like swagger 2.0 can't do that at all.

So just for bug tracking where swagger generated API client have not working API call.

Thanks.

P.S.
(I have harbor 1.5.0, i don't think what with new harbor something changed with backend).

**Comment by moooofly** [comment]
Hi, @Nefelim4ag  

I find the same issue and mark it [here](https://github.com/moooofly/harborctl/issues/18).
