### ISSUE TITLE
How open harbor v1 api version？

### ISSUE THREAD

**Issue by shibd** [goharbor/harbor#6256]
docker search harbor.xxx.com/phoenix/phoenix-monitor:master
`Error response from daemon: Unexpected status code 404`
I know that `docker search` is the v1 version of the api.
How open harbor v1 api version?

**Comment by zhoumeina** [comment]
@shibd , what do you mean v1? Can you provide the exact release version? For example:v1.6.

**Comment by zhoumeina** [comment]
Also, you need to provide the docker and docker compose version, so that we can help you to triage you question.

**Comment by Ghostbaby** [comment]
harbor 1.6 api

**Comment by Ghostbaby** [comment]
harbor 1.6 API http://editor.swagger.io

**Comment by ninjadq** [comment]
@shibd we do not support harbor v1 API, please using v2 API instead to your requirement.

**Comment by clouderati** [comment]
Please let us know if you need help with anything else. :smile:
