### ISSUE TITLE
Button icons are missing in Firefox in Harbor v1.6.1

### ISSUE THREAD

**Issue by GMTA** [goharbor/harbor#6259]
**Expected behavior and actual behavior:**
Next to the captions of buttons in the UI, an icon is usually displayed. This is the case for e.g. "New Project", "Delete", etc.

In Firefox 63.0.1 on Mac, none of the button's icons are displayed (cache was cleared). When I visit the same instance with Chrome, the icons are displayed.

**Steps to reproduce the problem:**
1. Login
2. Take a look at the icons next to the button's captions

**Versions:**
- harbor version: v1.6.1
- docker engine version: 18.09.0
- docker-compose version: 1.21.2

**Other**
There seems to be some CSS translation error:

![image](https://user-images.githubusercontent.com/3210731/48333557-3249ad80-e658-11e8-9a3c-f59c6d7abef7.png)

**Comment by zhoumeina** [comment]
@GMTA, I checked this icon in my Firefox, it looks good. Could you please try to upgrade your browser version and try. My version is: v1.6.0-a69f8605

**Comment by GMTA** [comment]
@zhoumeina I'm running the latest stable Firefox on Mac, version 63.0.1.

**Comment by pureshine** [comment]
@GMTA I checked this icon in Firefox 63.0.1 and the latest version 63.0.3，the icons are displayed normally.Could you please try uninstall and reinstall the latest version of Firefox Browser to try.
The harbor version I tested is ：v1.6.0-b59a06a

**Comment by GMTA** [comment]
@zhoumeina @pureshine You tested on v1.6.0, my report is on v1.6.1. You don't have the issue on v1.6.1?

**Comment by pureshine** [comment]
@GMTA I tested the version of Firefox Browser and the version of Harbor that you mentioned, and found no problem. This issue is temporarily closed. If you have any problems, you can restart it.
![image](https://user-images.githubusercontent.com/40712758/49775448-363e1d80-fd33-11e8-98ac-6fdea7127b82.png)

**Comment by GMTA** [comment]
FYI: this issue is no longer present v1.7.1.
