### ISSUE TITLE
i also encountered this problem, so i upgrade harbor to 1.6.1, but this problem still  exists,  how can to use gc, thanks @wy65701436

### ISSUE THREAD

**Issue by lmdkfs** [goharbor/harbor#6262]
_Originally posted by @lmdkfs https://github.com/goharbor/harbor/issues/5078

**Comment by lmdkfs** [comment]
I thought harbor1.6.1had fixed the problem .  So I used 1.6.1 the problem still existed about after gc redis cache issues.When 1.7 will be release . Thanks

**Comment by Fortuneaaa** [comment]
> @lmdkfs what's your problem? Please give more details.
> 
> If you are mentioning #5078, just use the workaround listed in the issue, and the online GC will be ready in v1.7.0

@wy65701436 Could you tell me when v1.7.0 will release? Thanks.
