### ISSUE TITLE
harbor不能自动拉镜像

### ISSUE THREAD

**Issue by qwwfxl** [goharbor/harbor#6264]
英语不太好，请允许我用中文描述下：
    编写的compose文件，启动时(docker stack deploy方式启动，swarm网络)，不能自动拉镜像，每次启动前都需要手动拉镜像，不知道是什么问题？help,thanks!
![default](https://user-images.githubusercontent.com/17565026/48341423-f3dbdf00-e6a7-11e8-99d3-b3343d46257a.png)
![default](https://user-images.githubusercontent.com/17565026/48341467-11a94400-e6a8-11e8-9a17-0286b912a07c.png)
![default](https://user-images.githubusercontent.com/17565026/48341482-1a9a1580-e6a8-11e8-9ced-6190a88c2194.png)

**Comment by zhoumeina** [comment]
@qwwfxl , please describe the docker version, docker-compose version and harbor version. By the way, I can see nothing in the second picture. 
第二张图片看不到文字，请把版本号描述一下。

**Comment by qwwfxl** [comment]
第二张图片提示没有镜像，需要手动执行docker  pull ......之后方能启动，已登录，pull时不需要重新登录，用的是swarm,compose是version 3

**Comment by qwwfxl** [comment]
@zhoumeina  harbor version:v1.4.0-rc1    compose version:1.14.0

**Comment by qwwfxl** [comment]
@zhoumeina harbor version:v1.4.0-rc1 compose version:1.14.0 18.03.0-ce-rc1
the second picture tips:no images
so i need to execute command:docker pull ....image name ,and then it can start successful.
I hope it can pull images automatically by docker stack deploy -c ****.yml names

**Comment by arvingre** [comment]
yes , I  get the same case also . Then  I solve this by add  " --with-registry-auth "   For example   " docker stack deploy -c agent-stack.yml agent  --with-registry-auth "  when you  have done  docker  login your <Harbor-host>
