### ISSUE TITLE
Feature Request: Predictable  URLs

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6275]
**Is your feature request related to a problem? Please describe.**
URLs to projects, images, and tags aren't predictable.

**Describe the solution you'd like**
The docker hub [allows you to browse images and tags for a project](https://hub.docker.com/r/goharbor/harbor-ui/tags/) by going to `https://hub.docker.com/r/<project>`, `.../r/<project>/<image>`, and `.../r/<project>/<image>/tags`. I'd love to be able to do this for harbor (even if it's a redirect to the current URL scheme) so that I can link to artifacts we push from our build system without having to talk to the harbor API to get the project ID.

**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
I feel like this is a relatively simple change that can be implemented by adding a redirect from `://<harbor>/harbor/r/<project>` (as well as `<project>/<image>`, `<project>/<image>/tags`, and `<project>/<image>/tags/<tag>`) to the existing routes or implementing the new routes as an alias and deprecating the old routes. I envision this as a purely cosmetic change, I don't see the need to change API routes since you'd already have access to project ID's if you're interacting with the API

If this needs to be drafted as a proper [proposal](https://github.com/goharbor/community/blob/master/proposals/TEMPLATE.md) I can draft something, just let me know.

**Comment by clouderati** [comment]
This is an awesome idea. I suspect it'll be quite a bit of work, though.

@reasonerjt can you please comment on the level of effort for something like this?

(@nlowe – are you on Slack? If so can you ping me?)
