### ISSUE TITLE
arm64: build fails in photon:2.0, "no supported platform found in manifest list"

### ISSUE THREAD

**Issue by vielmetti** [goharbor/harbor#6277]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Expected: on an arm64 system, "make all" creates a working `harbor`.

Actual: error message "no supported platform found in manifest list" for photon.

```
make[1]: Entering directory '/home/ed/src/github.com/goharbor/harbor'
building db container for photon...
Sending build context to Docker daemon 250.7 MB
Step 1/15 : FROM photon:2.0
2.0: Pulling from library/photon
no supported platform found in manifest list
/home/ed/src/github.com/goharbor/harbor/make/photon/Makefile:104: recipe for target '_build_db' failed
```

**Steps to reproduce the problem:**

Log into arm64 system (in my case a Packet c1.large.arm), clone git archive, type `make all`. System is running Ubuntu 16.04.

**Versions:**

- harbor version: master
- docker engine version: 17.03.2
- docker-compose version: 1.8.0

**Additional context:**

Related to #3505 .

**Comment by vielmetti** [comment]
The blocking issue is https://github.com/vmware/photon-docker-image/issues/7 , arm64 support for Photon.

**Comment by odidev** [comment]
Hi @vielmetti 

```arm64v8``` is supported in ```photon:3.0``` version.
I can see that your Harbor image is using ```photon:2.0```, which is actually not supported for ```arm64v8```.

Please modify it to ```photon:3.0``` and then check if it works for you.

Regards,

**Comment by vielmetti** [comment]
Checking right now!  I modified all of the Dockerfiles to point to `photon:3.0` , and now have these apparently non-fatal errors:

```
Step 2/8 : RUN tdnf install -y sudo >> /dev/null     && tdnf clean all     && groupadd -r -g 10000 harbor && useradd --no-log-init -r -g 10000 -u 10000 harbor     && mkdir /harbor/
 ---> Running in 4959d6fd6c76
Error: 404 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_aarch64'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
using empty dict to provide pw_dict
Error: 404 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_aarch64'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
Refreshing metadata for: 'VMware Photon Extras 3.0(aarch64)'
Disabling Repo: 'VMware Photon Extras 3.0(aarch64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64) Updates'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64) Updates'
Cleaning repos: photon
Cleaning up everything
```

Still in progress, though, I'll update.

**Comment by vielmetti** [comment]
Noting that https://github.com/sass/node-sass/pull/2253 references a dependency in the UI (node-sass) which doesn't have an `arm64` binary yet, which slows down the build a bit. Still in progress.

**Comment by zhoumeina** [comment]
@vielmetti , currently, harbor does not support photon 3.0 actually.

**Comment by zhoumeina** [comment]
@reasonerjt , @ywk253100 , please triange when harbor need to support photon 3.0 for arm64.

**Comment by vielmetti** [comment]
Thanks @zhoumeina - are you aware of any issues with photon 3.0 that I might anticipate? 

I will note that the Dockerfile for the make target "_build_portal" has this line

```
Step 14/18 : COPY --from=0 /build_dir/dist /usr/share/nginx/html
```

which is a feature in Docker 17.05; I'll be updating my Docker engine (it's at 17.03.2 right now) to make more progress.

**Comment by vielmetti** [comment]
There is a "db migrator container", which currently depends on photon:1.0. When I bring that forward to photon:3.0 I get this error

```
1. package sed-4.5-1.ph3.aarch64 conflicts with toybox provided by toybox-0.7.7-1.ph3.aarch64
```

which looks the same as https://github.com/vmware/photon/issues/747 . I'm attempting to solve that with the same technique from that issue of doing `tdnf erase toybox` before installing utilities.

**Comment by vielmetti** [comment]
Now I'm stuck at this in the "db migrator container":

```
Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz (90kB)
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
```

Going to press onwards because I think I don't need this container to have things actually test.

**Comment by vielmetti** [comment]
For some reason the "registry-photon" container includes an x86 binary after I build it.

```
ed@ed-2a-bcc-llvm:~/src/github.com/goharbor/harbor$ docker run --rm -it goharbor/registry-photon:v2.6.2-dev bash
bash: /root/.bashrc: Permission denied
harbor [ / ]$ file /usr/bin/registry
/usr/bin/registry: ELF executable, 64-bit LSB x86-64, dynamic (/lib64/ld-linux-x86-64.so.2), not stripped
```

**Comment by vielmetti** [comment]
yeah, there are a lot of dependencies that are copied from x86 components. this is going to be a bit harder to port than it looks like at first glance.

```
ed@ed-2a-bcc-llvm:~/src/github.com/goharbor/harbor/make/photon$ grep "_get_binary" Makefile
                        $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/clair/release2.0-$(CLAIRVERSION)/clair, $(DOCKERFILEPATH_CLAIR)/binary/clair); \
                        $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/chartm, $(DOCKERFILEPATH_CHART_SERVER)/binary/chartm); \
                        $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-signer, $(DOCKERFILEPATH_NOTARY)/binary/notary-signer) && \
                        $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-server, $(DOCKERFILEPATH_NOTARY)/binary/notary-server) ; \
                $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-migrate-postgresql.tgz, $(DOCKERFILEPATH_NOTARY)/binary/notary-migrate.tgz); \
                $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/registry, $(DOCKERFILEPATH_REG)/binary/registry); \
```

**Comment by reasonerjt** [comment]
@vielmetti those binaries are built previously and uploaded to google storage, that's why they are x86 based.
To workaround this, you'll need to build the binaries on arm and update the Makefile to consume them instead the ones on google storage.

**Comment by zhanglu0704** [comment]
Hi @vielmetti  If you want to build the binary for ARM64 ,you need to let BUILDBIN=ture in the main Makefile.

**Comment by congweitao** [comment]
@vielmetti 

> yeah, there are a lot of dependencies that are copied from x86 components. this is going to be a bit harder to port than it looks like at first glance.
> 
> ```
> ed@ed-2a-bcc-llvm:~/src/github.com/goharbor/harbor/make/photon$ grep "_get_binary" Makefile
>                         $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/clair/release2.0-$(CLAIRVERSION)/clair, $(DOCKERFILEPATH_CLAIR)/binary/clair); \
>                         $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/chartm, $(DOCKERFILEPATH_CHART_SERVER)/binary/chartm); \
>                         $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-signer, $(DOCKERFILEPATH_NOTARY)/binary/notary-signer) && \
>                         $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-server, $(DOCKERFILEPATH_NOTARY)/binary/notary-server) ; \
>                 $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/notary/release-$(NOTARYVERSION)/notary-migrate-postgresql.tgz, $(DOCKERFILEPATH_NOTARY)/binary/notary-migrate.tgz); \
>                 $(call _get_binary, https://storage.googleapis.com/harbor-builds/bin/registry, $(DOCKERFILEPATH_REG)/binary/registry); \
> ```

I set BUILDBIN=ture , but 

> Hi @vielmetti If you want to build the binary for ARM64 ,you need to let BUILDBIN=ture in the main Makefile.

I set BUILDBIN=true，but it prints out "fatal: Remote branch v2.7.1-patch-2819 not found in upstream origin". Which version should I set for REGISTRY_VERSION ? Thanks!
