### ISSUE TITLE
The document is not up to date

### ISSUE THREAD

**Issue by silenceper** [goharbor/harbor#6283]
What can we help you?
The documentation is not up to date, the latest version is 1.6。

example:
https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md

In this document, still use mysql as an example.

**Comment by zhoumeina** [comment]
@silenceper , could you describe which document  in which branch is not up to date?

**Comment by fengzhao** [comment]
虽然目前的发行版还是harbor 1.5.4 ，不过文档确实需要更新，harbor 1.6.0 的数据库已经是postgresql了，文档还是写的mysql，还有，请发布中文文档。谢谢

**Comment by reasonerjt** [comment]
The issue in installation.md will be tracked by #6148 
@kyrogue could you submit a PR to update the upgrade guide?

**Comment by kyrogue** [comment]
yes, will work on it

**Comment by clouderati** [comment]
Thanks @kyrogue – please feel free to reply to #6148 and open PR when ready.
