### ISSUE TITLE
harbor对于项目中的镜像管理是否支持不同用户只能下载不同的镜像功能

### ISSUE THREAD

**Issue by skyroot** [goharbor/harbor#6286]
**Is your feature request related to a problem? Please describe.**
即我在一个项目中维护了大量的镜像，但是只希望挑选一部分镜像（如通过定义tag），然后允许某个用户只能看到并下载这些tag的镜像？
**Describe the solution you'd like**

**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
A clear and concise description of the plan to make the solution ready. It can include a development timeline, resource estimation, and other related things.

**Additional context**

**Comment by reasonerjt** [comment]
so far you can only use project for isolation.

**Comment by xaleeks** [comment]
@skyroot Hi, we're trying to understand this requirement a little better.  You are talking about limiting visibility to certain images based on tags within a project?  Otherwise, to achieve the same kind of isolation would result in creating too many projects?  Am I understanding this correctly?
