### ISSUE TITLE
Too long to listing image list in project

### ISSUE THREAD

**Issue by myguddy** [goharbor/harbor#6287]
Version v1.5.0-chart-patch-90c0936f

I use harbor under kubernetes as private registry.

We have more than 700 images in one project.
when I list image list it takes too long even if one page is shown.

I checked chrome inspetor and found out, in the actual response return all images information.
I think it could be enhanced.

What do you think....?

Anyway thanks for harbor contributor~~

**Comment by clouderati** [comment]
Hi @zhoumeina – any thoughts on how we can improve?

@myguddy – any code contributions would be greatly appreciated. 😄

**Comment by myguddy** [comment]
I love to do so.....@clouderati.
I will look for the build process and architecture of habor.

I think the listing could change to page instead of pulling whole listing
in the ui, there is a pagination.

I am not sure of data schema of this.
Understand my humble opinion......
