### ISSUE TITLE
Push a provenance file to helm chart

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor#6293]
This is a question not an issue about signed charts. From the document I know I can upload a provenance from the GUI but since Helm push command does not support pushing a prov file of a signed chart yet, can I achieve the same using CLI?

**Comment by steven-zou** [comment]
@shen3lu4 

`push` is a helm [plugin](https://github.com/chartmuseum/helm-push) now, not a formal helm sub command. As far as I know, that `push` does not support push chart together with 'prov' file so far.

**Comment by steven-zou** [comment]
Answered and then close it. Thanks

**Comment by shen3lu4** [comment]
Is there anyway to push prov file using CLI or chartmuseum API? This is needed for CI/CD.

**Comment by shen3lu4** [comment]
Found a way to upload both helm charts and provence file to chartmuseum in Harbor:

curl -F "chart=@&lt;chart name&gt;.tgz" -F "prov=@&lt;chart name&gt;.tgz.prov" https://&lt;user name&gt;:&lt;password&gt;@&lt;Harbor URL&gt;/api/chartrepo/&lt;Harbor project name&gt;/charts
