### ISSUE TITLE
How do I force certificate reload

### ISSUE THREAD

**Issue by Mambix** [goharbor/harbor#6295]
I'm using let's encrypt certificates and it worked when it was a fresh installation.

But now I renewed my certificate because they expire every 3 months and I can't make it work with my harbor installation. I replaced the files in /data/cert folder and tried to restart/recreate/rebuild the containers but it still uses the old cert.

How can I fix this?

**Comment by Mambix** [comment]
Figured it out and it's weird. 

I had to replace certificates in my harbor folder under `common/config/nginx/cert`
I assumed the certificates are pulled from /data/cert folder

**Comment by steven-zou** [comment]
@Mambix 

You should execute the `prepare` script to reconfig the env after putting the new certs into the `/data/cert`.

**Comment by reasonerjt** [comment]
@Mambix 
As @steven-zou pointed out the `prepare` script will copy the certificate to the folder that can be accessed by nginx container.

**Comment by Mambix** [comment]
will close it as it is resolved :+1:

**Comment by frankcorneliusmartin** [comment]
How would this work automatically? E.g. when we use auto renewal? Do we really have to run the prepare script every time? That is a bit annoying 🙉

**Comment by zyitingftnt** [comment]
@frankcorneliusmartin have you figured out a solution? I am asking the same question here.

**Comment by frankcorneliusmartin** [comment]
No sorry i dont have a proper solution.. I wrote a little script that i run as a cron job to do it dirty:

```bash
docker-compose down
certbot renew --nginx
./prepare --with-notary --with-clair --with-chartmuseum
docker-compose up -d
```

**Comment by zyitingftnt** [comment]
@frankcorneliusmartin I see, thanks for the reply, appreciated!

**Comment by Gainutdinov** [comment]
cause clair replaced with trivy you should use: 
```
docker-compose down
certbot renew --nginx
./prepare --with-notary --with-trivy --with-chartmuseum
docker-compose up -d
```
