### ISSUE TITLE
Use personal token to push images

### ISSUE THREAD

**Issue by ephracis** [goharbor/harbor#6305]
I have successfully deployed Harbor and connected it to LDAP and I can push images to it by doing:

```
docker login ... # enter ldap creds
docker push ...
```

Now I want my CI pipeline to do the same. But I don't want to save my LDAP-password anywhere. Instead I would like to generate a token and use that in CI to push images.

is this possible?

**Comment by steven-zou** [comment]
@ephracis 

  Unfortunately, we don't have token/robot account to well support CI/CD pipeline at present. But we have started to consider to enhance the supporting of the DevOps process now.

**Comment by nlowe** [comment]
Possible duplicate of #4591

**Comment by reasonerjt** [comment]
This should be covered by the `robot account` which is targeted for 1.8.0

**Comment by reasonerjt** [comment]
Closing as this requirement is addressed by robot account, which has been delivered in v1.8
