### ISSUE TITLE
Chartmuseum on Azure Storage does not like quotes in harbor.cfg

### ISSUE THREAD

**Issue by jacekd81** [goharbor/harbor#6310]
**Expected behavior and actual behavior:**
I've installed Harbor with "--with-chartmuseum --with-clair" options. Everything seems fine & peachy, the install.sh script completes successfully, however chartmuseum-photon:v0.7.1-v1.6.0 container keeps restarting. 

```
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                       PORTS               NAMES
bd21c97965c9        goharbor/chartmuseum-photon:v0.7.1-v1.6.0   "/docker-entrypoin..."   17 hours ago        Restarting (2) 3 hours ago                       chartmuseum
```

Curious what's happening I've checked /var/log/harbor/chartmuseum.log and found this:
```
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: panic: azure: account name is not valid: it must be between 3 and 24 characters, and only may contain numbers and lowercase letters: "<edited>"
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]:
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: goroutine 1 [running]:
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: github.com/helm/chartmuseum/vendor/github.com/kubernetes-helm/chartmuseum/pkg/storage.NewMicrosoftBlobBackend(0xc42001a07c, 0x10, 0xc42001a019, 0x14, 0x14)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/vendor/github.com/kubernetes-helm/chartmuseum/pkg/storage/microsoft.go:30 +0x3b9
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: main.microsoftBackendFromConfig(0xc420202030, 0x9, 0xc4200140a8)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:140 +0xef
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: main.backendFromConfig(0xc420202030, 0xc420364000, 0x0)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:96 +0x32c
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: main.cliHandler(0xc420364000)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:46 +0xed
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: github.com/helm/chartmuseum/vendor/github.com/urfave/cli.HandleAction(0xf32b00, 0x1178e50, 0xc420364000, 0xc4201f82a0, 0x0)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:492 +0x7c
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: github.com/helm/chartmuseum/vendor/github.com/urfave/cli.(*App).Run(0xc4201fe1a0, 0xc4200101a0, 0x1, 0x1, 0x0, 0x0)
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/vendor/github.com/urfave/cli/app.go:264 +0x635
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: main.main()
Nov 20 06:07:17 172.18.0.1 chartmuseum[114913]: #011/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:36 +0x1ef
```
However:
1) the name of azure blob storage I've used is lowercase letters + digits
2) exists in Azure - so it has passed Azure Storage Account name vanity check
3) is fine for Harbor - I am able to push/pull container images, Harbor does not complain, all containers are up and running etc.
4) the name of Azure Storage Account specified in harbor.cfg is in quotes 

So, it seems to me Chartmuseum Azure Storage Account name verification routine is different than Harbor. 

**Steps to reproduce the problem:**
Download, unpack Harbor, modify harbor.cfg. 
Setup Harbor storage on Azure Storage Account:
`registry_storage_provider_name = azure`
and
`registry_storage_provider_config = accountname: "<azure_storage_account_name>" ...`
Make sure you enclose registry_storage_provider_config parameters in quotes. 

Run "install.sh --with-chartmuseum --with-clair" 
Harbor will run fine, however Chartserver container will fail/continue to restart. 

**Steps to fix the problem:**
Make sure that there are no quotes in registry_storage_provider_config property in harbor.cfg:
`registry_storage_provider_config = accountname: <azure_storage_account_name> ...`
Harbor and Chartserver will run fine.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.6
- docker engine version: 1.13.1
- docker-compose version: 1.18.0

**Comment by steven-zou** [comment]
@jacekd81 

Thanks for reporting bugs and providing such good details. I think the reason you guessed is probably right, registry and chart museum has different verification logic. I'll deep dive it and find a solution to fix it. Thanks!
