### ISSUE TITLE
如何把harbor管理的镜像全部复制一份到阿里云提供的仓库

### ISSUE THREAD

**Issue by YMingZeng** [goharbor/harbor#6311]
请问怎么把harbor的镜像同步到阿里云提供的registry上面？

**Comment by steven-zou** [comment]
@YMingZeng 

We do not support replicate harbor images to the non-harbor registry. But we have started some discussions about how to improve replication to support different registries. You can attend the discussions and comment on the [PR thread](https://github.com/goharbor/community/pull/21).

Meanwhile, I'm wondering if you can do contributions on the aliyun registry part? Looking forward to your reply. Thanks!

**Comment by steven-zou** [comment]
The replication between Harbor and Ali container registry is in the coming V1.9 release. I'll close this issue as it's tracked by the replication Epic. Code is merged by the PR https://github.com/goharbor/harbor/pull/8435 .
