### ISSUE TITLE
Slow tag listing for large repos in UI when using remote registry storage (such as s3).

### ISSUE THREAD

**Issue by eripa** [goharbor/harbor#6314]
When Harbor is setup in HA, where you have the Registry storage on a remote location the UI becomes quite slow to list large projects with many repos, or large repos with many tags.

During my investigation this is caused by the fact that the registry is queried to get all repos/tags for the UI web requests, so the registry much list and gather all data from the remote storage. Ideally the database should be used for these kinds of requests.

Example: A repo with ~3000 tags takes around 5 minutes to fetch from a local Minio cluster. This cluster is able to sustain around 1Gbps of transfer speeds and is fairly performant. In order to avoid failing on the client side I had to increase the nginx `proxy_read_timeout` to take this into account.

Let me know if I can help by gathering some more specific data or benchmarks. Thanks.

**Comment by eripa** [comment]
Thanks @clouderati. FWIW I also have redis running in the hope that it would help with this (configured in the registry `config.yml`), but it didn't seem to do anything to help in this regard. So I think caching it on the Harbor UI side is the way to go.

Another way would be to have a background registry←→db sync worker running to keep the state between the two, but that might be more involved and cause discrepancy in user experience (i.e. user pushes an image to the registry expecting it to be in the UI, but the sync hasn't run/completed yet).

**Comment by eripa** [comment]
FWIW this is still an issue for us. Just want to avoid the issue being closed.

**Comment by jegger** [comment]
We are in the exact same situation. Even tough we have not as nearly as much tags in a repo yet, it is slow. The same load-time seems to be appearing when we upload a new image to the repo (at the end of the push) - but I am not sure if that is really related...
