### ISSUE TITLE
Integrate with registry v2.7.1

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6322]
As registry has released v2.7.0, we need to try to integrate it into Harbor and do a full regression.

**Comment by clouderati** [comment]
Does it make sense to wait for the GA release in lieu of the release candidate? (honest question; don't know the answer myself)

**Comment by wy65701436** [comment]
Update to v2.7.1 as it fixes a regression bug.

**Comment by wy65701436** [comment]
Done.
