### ISSUE TITLE
Retag kicks user back to login when the user doesn't have sufficient permission.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#6327]
**Expected behavior and actual behavior:**
When user does not have permission to the target project of the retag action, it should fail the action and display a meaningful error.

But now it tries to kick user back to login screen:
![image](https://user-images.githubusercontent.com/2390463/48892440-08bf2c00-ee79-11e8-97cb-bbcf0270c00f.png)

**Steps to reproduce the problem:**
1. push an image to project `library`
2.Create a user "tester"
3.Create a project "testproject", and add "tester" as a `guest`
4.Login as tester and try to retag the image in `library` project to an image in `testproject` project.
**Versions:**
Please specify the versions of following systems.
- harbor version: v1.6.0-ad77098a (built by master code around 20th Nov)

Seems the root cause is the API is returning a 401 and UI thinks the user has to re-login.

**Comment by reasonerjt** [comment]
@cd1989 Could you make sure this can be fixed before 3rd Dec?

**Comment by cd1989** [comment]
I will investicate it

**Comment by zhoumeina** [comment]
@reasonerjt ， if the user is guest, the retag button will be disabled. I am not sure how this happened. I tried to reproduced it in my local. Everything works fine.

**Comment by cd1989** [comment]
Thanks for @zhoumeina  @reasonerjt  Cause of the problem is: Retag returns 401 status code for project permission not allowed, but the correct value should be 403.
