### ISSUE TITLE
docker login need more than 15s to establish connection when use aws internal lb or azure lb proxy.

### ISSUE THREAD

**Issue by KylanZhang** [goharbor/harbor#6328]
use aws internal lb or azure lb 
![image](https://user-images.githubusercontent.com/19925721/48895599-715dd700-ee80-11e8-84ca-4ad02b775349.png)

**Comment by KylanZhang** [comment]
version: 1.5.4 , 1.4.0

**Comment by reasonerjt** [comment]
If the time is spent in establishing connection, it's non relevant to the application.

**Comment by KylanZhang** [comment]
It works well at 1.2.2

**Comment by KylanZhang** [comment]
![image](https://user-images.githubusercontent.com/19925721/48926321-dc062580-ef07-11e8-99f8-0b8cc24dbfa4.png)
registry.log get error log but still login successful.

**Comment by KylanZhang** [comment]
I think it is relevant to sys env

**Comment by KylanZhang** [comment]
I  relevant to TCP type lb.
