### ISSUE TITLE
Harbor Version v1.6.1-98bcac6c - AD Group DN not found 

### ISSUE THREAD

**Issue by arjunm183** [goharbor/harbor#6329]
Hello Team,

We use harbor version v1.6.1 and we have configured AD Authentication. 
We were succeeded with User DN Authentication, However when we configured Harbor to fetch info via Group  it throws error ( Group DN: AGSC_MHC_Users not found )

ERROR from ui.log as is below.

Nov 22 15:51:39 172.18.0.1 ui[19732]: 2018-11-22T10:21:39Z [WARNING] failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Nov 22 15:51:39 172.18.0.1 ui[19732]: 2018/11/22 10:21:39 #033[1;44m[D] [server.go:2619] |  43.243.254.50|#033[42m 200 #033[0m|   3.543463ms|   match|#033[44m GET     #033[0m /api/usergroups   r:/api/usergroups/?:ugid([0-9]+)#033[0m
Nov 22 15:51:51 172.18.0.1 ui[19732]: 2018-11-22T10:21:51Z [WARNING] failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax
Nov 22 15:51:51 172.18.0.1 ui[19732]: 2018-11-22T10:21:51Z [INFO] LDAP Group DN is not found: DN:AGSC_MHC_Users

Configuration is attached in the below link.

![image](https://user-images.githubusercontent.com/5314336/48902433-94878700-ee7e-11e8-8fa8-933bc8cf6028.png)

Can someone help us what is the mistake we do in the configuration. Is it a bug. Because we see the code (/src/core/api/usergroup.go) from harbor which says the error DN: not found appears when the LDAP Server is offline.

// User can not add ldap group when the ldap server is offline
	ldapGroup, err := auth.SearchGroup(userGroup.LdapGroupDN)
	if err == ldap.ErrNotFound || ldapGroup == nil {
		uga.HandleNotFound(fmt.Sprintf("LDAP Group DN is not found: DN:%v", userGroup.LdapGroupDN))
		return

Thanks and Regards,
Arjun.M

**Comment by clouderati** [comment]
Hi @arjunm183 – sorry for the delayed response. Can you share your full base DN string? The first line of the UI logs point to a potential issue, possibly on Harbor's end:

> Nov 22 15:51:39 172.18.0.1 ui[19732]: 2018-11-22T10:21:39Z [WARNING] failed to parse user group id, error: strconv.ParseInt: parsing "": invalid syntax

Might also be a good idea to see if traffic hits the server with a quick packet capture and / or `netstat`. Let me know.

**Comment by Ash1994** [comment]
Hi @clouderati - the full base DN string is 
CN=eedc_s_dhcregp,OU=UsersAdministrative,OU=_GlobalResources,OU=EEDC,dc=emea12,dc=corpodir2,dc=net

The LDAP server is getting connected to the app server.

**Comment by sh3tb3rd** [comment]
Any news on this? Harbor v. 1.8.1 seems to have the exact same issue.

**Comment by hrmmmwhynot** [comment]
@sh3tb3rd try to specify a "ldap group filter" because the default objectclass group filter is wrong (objectclass=groupOfNames)

ldap group filter: objectclass=group
then you can use full dn to add new group. This worked for me.

**Comment by Hunlogo** [comment]
Hello all, 

I have something similar issue. Users Can login to harbor based on the Group but I cannot add permission based on group. so In project I cannot handle the permissions from AD. Any idea?

**Comment by Hunlogo** [comment]
Failed to get pmid from path, error strconv.ParseInt: parsing "": invalid syntax
I see this error. Users can login using ldap but they don't get the proper permission

**Comment by Hunlogo** [comment]
problem solved. with memberof . thanks

**Comment by renjithkm86** [comment]
Thanks! that helped.
