### ISSUE TITLE
Replication stop working after v1.4.x

### ISSUE THREAD

**Issue by Poil** [goharbor/harbor#6330]
**Expected behavior and actual behavior:**
When trying to replicate to another Harbor instance I have this error on v1.5.0+
```
==> jobservice.log <==
Nov 22 14:58:48 172.18.0.1 jobservice[1069]: 2018-11-22T13:58:48Z [ERROR] [service_logger.go:63]: Job 'IMAGE_TRANSFER:5d52f52f381dc56d36750ddd' exit with error: Get https://harbor.eng/api/projects?name=mobile: dial tcp 22.0.4.7:443: getsockopt: no route to host
Nov 22 14:58:48 172.18.0.1 jobservice[1069]: 2018-11-22T13:58:48Z [ERROR] [service_logger.go:63]: Job 'IMAGE_TRANSFER:bbe15ca956cc3660c3fd302b' exit with error: Get https://harbor.eng/api/projects?name=mobile: dial tcp 22.0.4.7:443: getsockopt: no route to host
```
Harbor.eng is my docker host (22.0.4.7)
It seems like harbor try to get himself but not via the docker network (the container IP)
Before, in 1.4 the request was done on the docker networks (172.16....)

Note: We replicate to another host named harbor.vs (the registry test is OK)

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.6.4
- docker engine version: 2018.03.0-ce
- docker-compose version: 1.20.0, build ca8d3c6

**Comment by Poil** [comment]
I've stop docker, flush all iptables rules, rename /etc/sysconfig/iptables, restart docker, compose down, compose up, it's working again

**Comment by reasonerjt** [comment]
Looks like a env issue, closing since it's gone.
