### ISSUE TITLE
Panic inside registry container on image push 

### ISSUE THREAD

**Issue by adeesent** [goharbor/harbor#6332]
**Expected behavior and actual behavior:**
Successful push without any errors

**Steps to reproduce the problem:**
Really hard, it happens only with one image.

**Versions:**
Running inside Kubernetes

- harbor version: v1.6.2
- docker version: 18.03.1-ce
- docker client version: 18.09
- k8s version: 1.11.3

**Additional context:**
* **Log files:** 
```
 10.100.227.71 - - [22/Nov/2018:14:34:22 +0000] "PATCH /v2/xxxxx/xxxx/blobs/uploads/981f049c-061c-4c2e-bc0a-07e6136de9c2?_state=2URPNr5pl_wg-JOFTFeGvFWMy-S1lcrII0iL24s48757Ik5hbWUiOiJ3b3JraS9jaGF0IiwiVVVJRCI6Ijk4MWYwNDljLTA2MWMtNGMyZS1iYzBhLTA3ZTYxMzZkZTljMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0xMS0yMlQxNDozNDoxOC4xMDg0MzU2NVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/18.09.0 go/go1.10.4 git-commit/4d60db4 kernel/4.15.0-39-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.0 \\(linux\\))"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a8122]
goroutine 1255 [running]:
panic(0xb97100, 0xc4200180e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy.func1(0xc42034ee40, 0x0, 0xc42033ef80, 0x1067aa0, 0xc420548100, 0xc420363140, 0x5e, 0xc42011b260, 0x69, 0xc4200142d0, ...)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:742 +0x592
created by github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).copy
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:748 +0x6aa 
```

**Comment by clouderati** [comment]
I can tell this is going to be a fun one. 😄 

Can you clarify what you mean "one image"? Do you have a specific image that causes this panic? Or you try any image repeatedly and Harbor will eventually panic?

Quick glance at the trace gives me the impression that the issue is in the distribution code.

**Comment by adeesent** [comment]
Thank you for response! Yeah, I understand it is unclear and not very informative. We tried to use Harbor as private registry, but unfortunately one image push (specific one) always fails - last layer push shows retries and eventually exits with error. Rest of the images works fine.

One of the reason maybe fact, that we don't use AWS S3, but Openstack one (with compatible API).

**Comment by adeesent** [comment]
I'm sorry but no :(

**Comment by adeesent** [comment]
If you could provide some guidance to debug the issue, it would be great!
