### ISSUE TITLE
Incorrect command in the detail page of a chart

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#6333]
In the "Command" section of the detail page of a helm chart, the command looks like:

`helm repo add --ca-file <ca file> --cert-file <cert file> --key-file <key file>     --username <username> --password <password> <repo name> ${this.repoURL}/chartrepo/${this.projectName}`

Seems the code failed to evaluate `this.repoURL` and `this.projectName`

- harbor version: v1.6.0-ad77098a

**Comment by steven-zou** [comment]
@zhoumeina 

Suggest remove `--cert-file <cert file> --key-file` options
