### ISSUE TITLE
Global search fails on 502 without helm chart installed

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6336]
**Expected behavior and actual behavior:**
Global should not search charts if the user does not install harbor with helm chart.

**Steps to reproduce the problem:**
User global search to search project, like "library".

**Versions:**
Version v1.7.0-b59a06aa

**Additional context:**
ov 22 20:49:03 172.18.0.1 core[15991]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 22 20:49:03 172.18.0.1 core[15991]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa254e0]
Nov 22 20:49:03 172.18.0.1 core[15991]: 
Nov 22 20:49:03 172.18.0.1 core[15991]: goroutine 787 [running]:
Nov 22 20:49:03 172.18.0.1 core[15991]: github.com/goharbor/harbor/src/chartserver.(*Controller).getIndexYamlWithNS(0x0, 0xc42037a670, 0x10, 0xc4203a24e0, 0xc420161f40, 0xc42038a328)
Nov 22 20:49:03 172.18.0.1 core[15991]: #011/go/src/github.com/goharbor/harbor/src/chartserver/handler_repo.go:164 +0xb0
Nov 22 20:49:03 172.18.0.1 core[15991]: github.com/goharbor/harbor/src/chartserver.(*Controller).getIndexYaml.func2(0xc42037bda0, 0xc4203a24e0, 0x0, 0xc42008c8a0, 0xc42008c720, 0xc42037a670, 0x10)
Nov 22 20:49:03 172.18.0.1 core[15991]: #011/go/src/github.com/goharbor/harbor/src/chartserver/handler_repo.go:110 +0x7d
Nov 22 20:49:03 172.18.0.1 core[15991]: created by github.com/goharbor/harbor/src/chartserver.(*Controller).getIndexYaml
Nov 22 20:49:03 172.18.0.1 core[15991]: #011/go/src/github.com/goharbor/harbor/src/chartserver/handler_repo.go:103 +0x380

**Comment by steven-zou** [comment]
Code delivered into PR https://github.com/goharbor/harbor/pull/6375. Close this issue now.
