### ISSUE TITLE
Clair failed to load configuration

### ISSUE THREAD

**Issue by Statemood** [goharbor/harbor#6337]
HA 模式下，clair 会报错，信息 Nov 23 13:50:08 172.18.0.1 clair[20955]: time="2018-11-23T05:50:08Z" level=fatal msg="failed to load configuration" error="open /etc/clair/config.yaml: no such file or directory"

Version: Version v1.6.0-66709daa

需要修改 ha/docker-compose.clair.yml:24

- ./common/config/clair:/config

为 
- ./common/config/clair:/etc/clair

之后 clair 即可正常启动

**Comment by reasonerjt** [comment]
Sorry but the `docker-compose` HA deployment has been deprecated.
