### ISSUE TITLE
where's the image: vmware/harbor-core:v1.2.0?

### ISSUE THREAD

**Issue by nicklv** [goharbor/harbor#6341]
What can we help you?
vmware/harbor-core:v1.2.0 cant be found in hub.docker.com. where can download it?

**Comment by clouderati** [comment]
The images should now be in the `goharbor` namespace, right @reasonerjt?

**Comment by ninjadq** [comment]
maybe this is caused by the older version of helm chart.
you can try using this chart https://github.com/goharbor/harbor-helm

**Comment by reasonerjt** [comment]
I assume this is fixed, closing.

Please reopen if you need further help.
