### ISSUE TITLE
Names of json data in  GET charts API response body should all be in lowercase

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6354]
When calling get charts API , the first letter of some names in response json data are uppercase, but they should be all in lowercase :

Steps to reproduce the problem:
Call API: /chartrepo/{repo}/charts GET

Expected response data format is:

    _"[
      {
        "name": "mariadb",
        "total_versions": 1,
        "latest_version": "4.3.1",
        "created": "2018-11-26T06:25:05.966719842Z",
        "updated": "0001-01-01T00:00:00Z",
        "icon": "https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png",
        "home": "https://mariadb.org",
        "deprecated": false
      }
    ]"_

Actual behavior is:

    _"[
    {
        "Name": "mariadb",
        "total_versions": 1,
        "latest_version": "4.3.1",
        "Created": "2018-11-26T06:25:05.966719842Z",
        "Updated": "0001-01-01T00:00:00Z",
        "Icon": "https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png",
        "Home": "https://mariadb.org",
        "Deprecated": false
      }
    ]"-

Versions:
Version v1.6.0-2891ab28

**Comment by steven-zou** [comment]
Issue fixed in PR https://github.com/goharbor/harbor/pull/6374. Close
