### ISSUE TITLE
Integration with existing Docker registry AWS S3 bucket

### ISSUE THREAD

**Issue by kaivanov** [goharbor/harbor#6359]
I see that Harbor supports S3 as a back-end image store. I already have an existing docker registry S3 bucket containing multiple docker images and was wondering if it is possible/safe to point that to a fresh Harbor deployment. Any issues I should be aware of ?

**Comment by reasonerjt** [comment]
The images may not be shown in Harbor's UI, because the projects don't exist in Harbor's DB.  
To make that work you need to manually create project with the same name as the namespace of your images.

**Comment by reasonerjt** [comment]
I'm closing this issue for now as there seems no further questions.

**Comment by dntosas** [comment]
@reasonerjt hello man

I did what you suggested without results ^^

Pointed Harbor to existing S3 bucket with existing docker registry and then create as Harbor projects the corresponding existing registry namespaces.

Some Details:
- Harbor version: 1.10
- S3 Bucket path: /docker/registry/v2/repositories/test
- Harbor Project: test

Is there any more specific way to create that mapping ?

**Comment by LunaticZorr** [comment]
@reasonerjt @dntosas 

I've had the same scenario. A previous HARBOR registry stored on S3. I've launched a new harbor deployment and it uses the same S3 setup, but existing images, even after creating a project with the same name, do not show... 

Is there any way of importing the images?

**Comment by alieunang** [comment]
Same problem in 2021, want to build stateless harbor on k8s with s3 backend , but when i rebuilt harbor with the same s3 registry backend , same projet name, do not show images on harbor ui.

how could build stateless harbor with s3 backend ?
