### ISSUE TITLE
Provide the ability to switch between dark and light modes

### ISSUE THREAD

**Issue by lweitzman** [goharbor/harbor#6367]
Provide the ability to switch between dark and light mode. Provide a toggle at the bottom of the left navigation to switch between the 2 modes.

**Comment by lweitzman** [comment]
Here is an example of dark mode for the folders page
https://vmware.invisionapp.com/share/RKOJ1Q83XNS#/333669696_Folders_-_Collection_-_Dark 
link at the bottom of the nav toggles between dark and light modes.

**Comment by clouderati** [comment]
😄  Can't wait to support dark mode!

**Comment by clouderati** [comment]
😄  Can't wait to support dark mode!

**Comment by xaleeks** [comment]
This will be possible in v2.0!
