### ISSUE TITLE
Request to include details on the operating system for windows images

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#6369]
As Harbor is adding Windows container support, the OS version of the image is very important since it has a strict set of compatibility rules for the operating system of the container host. Would it be possible to include the OS version in the Harbor image details

The manifest for containers contains the following two fields which are relevant for windows:
os: windows
os.version: 10.0.14393.2608
Manifest spec: https://docs.docker.com/registry/spec/manifest-v2-2/

**Comment by reasonerjt** [comment]
Let's see if such info is returned in the API and make it shown on the UI.

**Comment by reasonerjt** [comment]
Re-open to make sure the fix is included in 1.7.5
