### ISSUE TITLE
Scan on push doesn't work well with azure blob storage

### ISSUE THREAD

**Issue by deuch** [goharbor/harbor#6380]
Hello,

I'm using the 1.6.2 version of Harbor on a VM in Azure. I'm using Azure Blob Storage and i've issue with the Scan on Push features.

Simply, it doesn't scan on push, i've to do it manually every time in the UI. With a local storage it seems better 95% of the time (there are some images not scanned).

With the azure blob storage, it's 100% of failure. Images are never scanned. There are in the storage and i can pull.push them without issues.

In the log i do not have error. Job service submit to clair the layers to scan, clair seems to scan it but i'm not sure that the notification to the ui, from clair or other, is sent to say that it's OK. Calling clair API with the image name and tag result in a empty array of vulnerabilities ...

Any idea ?

**Comment by reasonerjt** [comment]
@deuch does it work if you switch to local storage?

I'm trying to clarify if the root cause is Azure blob storage.

**Comment by reasonerjt** [comment]
Could it be the dup of https://github.com/goharbor/harbor/issues/5166 ?
Could you check the log to verify?
