### ISSUE TITLE
 Get https://registry.chamc.intra/v2/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by eagle2016** [goharbor/harbor#6383]
I have installed a cluster of openshift,when I have execute:
 oc new-app --docker-image=registry.chamc.intra/techfin/tomcat:v1
result as follows:

W1129 14:33:55.215696   26805 dockerimagelookup.go:233] Docker registry lookup failed: Get https://registry.chamc.intra/v2/: x509: certificate signed by unknown authority
error: unable to locate any local docker images with name "registry.chamc.intra/techfin/tomcat:v1"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
----------------------------------------------------------------------------------
I can pull images normally. and PUSH some images normally.
I have configured ca and key in my cluster。
anyone help me??

**Comment by reasonerjt** [comment]
I assume you are using Harbor.

essentially the issue like 
```
x509: certificate signed by unknown authority
```
happens when the client doesn't trust the certificate, you need to figure out how openshift works, and how to inject certificate to the worker node of openshift, if you cannot please open an issue to openshift, we cannot help you debug the setup of openshift.
