### ISSUE TITLE
API returns incorrect labels

### ISSUE THREAD

**Issue by lwqcz** [goharbor/harbor#6390]
**Expected behavior and actual behavior:**

When I use API endpoint of `/api/repositories/library/debian/labels` I get an empty return with HTTP 200 header.
But image with tag `stretch` in this repository have attached labels `dev-upload` (global label) and `approved` (private label).

Should these labels be returned via endpoint specified above?

I can get these labels when using endpoint `/api/repositories/library/debian/tags`:
````{
    "digest": "sha256:3ffe8f...39",
    "name": "stretch",
    "size": 72764400,
    "architecture": "amd64",
    "os": "linux",
    "docker_version": "1.12.3",
    "author": "...",
    "created": "2018-11-06T01:10:10.371533687Z",
    "config": {
      "labels": {}
    },
    "signature": null,
    "labels": [
      {
        "id": 3,
        "name": "dev-upload",
        "description": "Will be uploaded to production registry!",
        "color": "#1D5100",
        "scope": "g",
        "project_id": 0,
        "creation_time": "2018-11-15T13:29:33.774515Z",
        "update_time": "2018-11-15T13:29:43.714212Z",
        "deleted": false
      },
      {
        "id": 4,
        "name": "approved",
        "description": "Approved image.",
        "color": "#FFDC0B",
        "scope": "p",
        "project_id": 1,
        "creation_time": "2018-11-15T13:39:54.502469Z",
        "update_time": "2018-11-15T13:39:54.502469Z",
        "deleted": false
      }
    ]
  }
````

**Steps to reproduce the problem:**
Just attach a label to an image in repository and try to obtain that label via API endpoint.

**Versions:**
- harbor version: 1.6.0
- docker engine version: 18.06.1-ce
- docker-compose version: 1.8.0

**Additional context:**

**registry.log** record (when I used /labels endpoint and then /tags):
````
Nov 29 14:47:50 172.18.0.1 registry[11002]: time="2018-11-29T13:47:50.047408006Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=0f25020e-280c-437b-bd33-0ac38064b542 http.request.method=GET http.request.remoteaddr="172.18.0.7:48476" http.request.uri="/v2/library/debian/blobs/sha256:ed02cea194f448e0fe95a0f7878fca77818e94fc684e90d062e8f75509cab5fa" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/octet-stream" http.response.duration=10.833684ms http.response.status=307 http.response.written=517 instance.id=3cd1bced-4f87-4c58-a31c-58a1ac88f177 service=registry version=v2.6.2 
````

````
Nov 29 14:47:50 172.18.0.1 registry[11002]: time="2018-11-29T13:47:50.051743942Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="registry:5000" http.request.id=608f674e-81f4-4044-ad59-4b4091460f17 http.request.method=GET http.request.remoteaddr="172.18.0.7:48480" http.request.uri="/v2/library/debian/blobs/sha256:36bc24c273393d895a291e0506a7ca4f450ea9f41a977cb9a52c334d7897beb3" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/octet-stream" http.response.duration=8.256863ms http.response.status=307 http.response.written=517 instance.id=3cd1bced-4f87-4c58-a31c-58a1ac88f177 service=registry version=v2.6.2
````

Am I doing something wrong? Thank you. 😉

**Comment by reasonerjt** [comment]
This should be the design, as the tag and repo are considered different kinds of resourced.

**Comment by lwqcz** [comment]
@reasonerjt Can you explain those different kinds of data in each endpoint?

**Comment by ywk253100** [comment]
You should use `GET /api/repositories/library/debian/tags/stretch/labels` to get the labels of one specific tag.

**Comment by lwqcz** [comment]
@ywk253100 Thnx. Yes I can use that but how can I obtain data for a whole entity like /api/repositories/library/debian ?

**Comment by ywk253100** [comment]
Just like what @reasonerjt said, the `repository` and `tag` are two different resources, you can add/get labels to/from repositories through API, but the labels got from a repository don't contain the ones of tags'.
Btw, why do you want the repository API return the labels of its tags?

**Comment by lwqcz** [comment]
@ywk253100 I just would like to get a list of all tags labels, for instance containing a string like "upload" to get data which tags are ready to be uploaded to the production environment.

**Comment by ywk253100** [comment]
The API `GET /api/repositories/library/debian/tags` should be what you want, it returns the tag list and each entry contains the tag name and its labels.
