### ISSUE TITLE
Grant repository, image delete and image scan privileges to project member with developer role

### ISSUE THREAD

**Issue by anvivi99** [goharbor/harbor#6391]
**Is your feature request related to a problem? Please describe.**
For now only harbor system admin or project admin could delete repository or images in a project. Project member with developer role can only pull or push images. This becomes a  barrier for project member with developer role to maintain project repository and images, since every time they will have to bug system or project admin for "delete" operation. A side effect of this proposal will be  one developer could delete an image pushed by another developer in the project, which sounds like reasonable compromise.

**Describe the solution you'd like**
Grant repository, image delete and image scan privileges to project member with developer role.

**Describe the main design/architecture of your solution**
N/A

**Describe the development plan you've considered**
N/A

**Additional context**
N/A

**Comment by reasonerjt** [comment]
There's concern that it breaks existing model after user performs upgrade, so potentially we may provide a new role and keep developer role's permission as is.

**Comment by heww** [comment]
And more issues about the epic

Add HasProjectPerm method to security.Context interface #6637
Use HasProjectPerm of security.Context to protect API of project and related resources #6638
Remove HasReadPerm, HasWritePerm, HasAllPerm of security.Context #6639
New /users/:id/permissions API #6640
Update permission checking in Portal using /users/:id/permissions API #6641
Document for project roles and permissions #6642

**Comment by heww** [comment]
Master role with these permissions was introduced now in master branch.
