### ISSUE TITLE
Image scanning service account permissions

### ISSUE THREAD

**Issue by mehmetcodes** [goharbor/harbor#6401]
**Problem**

An image scanner (such as twistlock or coreos/clair) needs to pull each project and at times get metadata from the image repository.  I propose there should be a way to perform this activity in terms of account permissions.

**Solution**

Service account permissions for tools like this that allow global scanning of image repositories (can pull from all projects, can not push to any projects).

**Describe the main design/architecture of your solution**

I think the way to implement such permissions is best investigated by the harbor team

**Comment by clouderati** [comment]
Completely reasonable idea. The concept of service accounts / tokens has been raised in #6305, #4591, #698, and #1323. Any objections to closing and tracking in one of these existing issues?

**Comment by reasonerjt** [comment]
The way Clair works does not require service account as you can provide the Authorization header to it when calling Clair's API.

So I don't think this is necessary at least for Clair.

**Comment by reasonerjt** [comment]
So you are asking for an account to pull images, not a general service account for other API calls correct?
And to solve your problem there's another gap, we need to better decouple Harbor from Clair, see #6234

**Comment by xaleeks** [comment]
Robot accounts can achieve this and robot accounts scoped to system level is tracked on ticket https://github.com/goharbor/harbor/issues/10774
