### ISSUE TITLE
Add repository into DB dealy

### ISSUE THREAD

**Issue by xuejipeng** [goharbor/harbor#6403]
**Expected behavior and actual behavior:**
I pushed a image for three hours before I saw it in the UI.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**

- harbor version: [1.5.0]
- docker engine version: [ 17.03.1-ce]
build on k8s

* **Log files:** You can get them by package the `/var/log/harbor/` .
![image](https://user-images.githubusercontent.com/18901031/49329428-b2a96180-f5b9-11e8-9739-ae57ca9b639b.png)

**Comment by xuejipeng** [comment]
In the beginning, there was no such problem. Now we have about 3T images. As long as it is a new image repository, it will have this problem.

**Comment by reasonerjt** [comment]
The log message you highlighted did you see it 3 hours after your successfully push the image?

**Comment by xuejipeng** [comment]
Sorry to reply so late, I did not receive a reminder email。
Yes, there is a timestamp in front，I am not very familiar with golang，I want to know what happened to the UI during this period. Is there a message queue inside?

**Comment by xuejipeng** [comment]
I changed Redis and MySQL to  native, and there's no such problem.
