### ISSUE TITLE
Running Harbor with HTTP behind a HTTPS Proxy (haproxy) 

### ISSUE THREAD

**Issue by gogeof** [goharbor/harbor#6405]
Running Harbor with HTTP behind a HTTPS Proxy (haproxy) 
I've tried to get harbor running behind haproxy proxy.

So the first setup looked like this:
haproxy/F5 (host,ssl) -> harbor-nginx(non-ssl) -> harbor

pull is working, but push failed, really strange.

Are there any guidelines for this scenario?
The simple reason is that I do not want to maintain neither the SSL settings nor the cert within the harbor, because we manage the cert in the harpoxy/f5 nodes.

Please let me know if any config of the current or previous setup would be useful.

### Client Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)

### Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)

### Haproxy Config:
global
  daemon
  log  127.0.0.1 local0 info
  tune.ssl.default-dh-param 2048
  maxconn  20000
  pidfile  /app/haproxy/run/haproxy.pid
  stats  socket /app/haproxy/lib/haproxy/stats
  tune.bufsize  131072
  user mwop
  group mwop
  tune.ssl.default-dh-param 2048

defaults
  log  global
  maxconn  10000
  mode  http
  option  dontlog-normal
  option  http-server-close
  retries  3
  stats  enable
  timeout  http-request 10s
  timeout  queue 1m
  timeout  connect 10s
  timeout  client 1m
  timeout  server 30m
  timeout  check 10s

listen Stats
  bind 0.0.0.0:10000
  mode http
  stats enable
  stats uri /
  stats refresh 5s
  stats show-node
  stats show-legends
  stats hide-version

frontend https_frontend
 bind *:80
 acl is_harbor hdr_beg(host) harbor.xx.xx.com
 redirect scheme https if !{ ssl_fc }
 bind *:443 ssl crt /app/haproxy/cert/xx.xx.com.pem
 mode http
 option httpclose
 option forwardfor
 reqadd X-Forwarded-Proto:\ https
 default_backend web_server

backend web_server
  balance  source
  cookie SERVERID insert indirect nocache
  mode http
  option  tcp-check
  option  httplog
  option  httpclose
  rspidel  ^Set-cookie:\ IP=
  server mslb1 100.xx.xx.45:80 check port 80 inter 10s fastinter 2s downinter 3s rise 3 fall 3

### Here is what I see（***string*** is one private repo）
![image](https://user-images.githubusercontent.com/13129099/49341453-76910200-f688-11e8-84fb-e624bdf58f0c.png)

**Comment by ywk253100** [comment]
Did all push actions fail? Can you upload the logs of Harbor?

**Comment by gogeof** [comment]
Today, I had retried, but got "unauthorized: authentication required" when login, really strange.

And syslog has nothing.

![image](https://user-images.githubusercontent.com/13129099/49415522-02527d80-f7b2-11e8-9c6e-bb62799da3c4.png)

**Comment by gogeof** [comment]
Login failed when docker different with the one where harbor installed.

And if the version is the same, push failed of all the image I have tried.

here is the log:
![image](https://user-images.githubusercontent.com/13129099/49417444-b5be7080-f7b8-11e8-9389-a844b8db5dac.png)

Dec  4 11:28:48 172.19.0.1 registry[7855]: time="2018-12-04T03:28:48.359728252Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:8414a5c485b96c3fe519525d2a155f8500e346fe48b5e28886b7925c56c78d88 err.message="blob unknown to registry" go.version=go1.7.3 http.request.host=harbor.xxx.xxx.com http.request.id=c1625713-7b31-4a9e-abe6-8899679a4a8f http.request.method=HEAD http.request.remoteaddr=100.69.xxx.133 http.request.uri="/v2/test/harbor-log/blobs/sha256:8414a5c485b96c3fe519525d2a155f8500e346fe48b5e28886b7925c56c78d88" http.request.useragent="docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=44.159375ms http.response.status=404 http.response.written=157 instance.id=5cc076e3-d11f-495c-8791-9070d4d3cda9 service=registry vars.digest="sha256:8414a5c485b96c3fe519525d2a155f8500e346fe48b5e28886b7925c56c78d88" vars.name="test/harbor-log" version=v2.6.2
Dec  4 11:28:48 172.19.0.1 registry[7855]: 172.19.0.7 - - [04/Dec/2018:03:28:48 +0000] "HEAD /v2/test/harbor-log/blobs/sha256:8414a5c485b96c3fe519525d2a155f8500e346fe48b5e28886b7925c56c78d88 HTTP/1.1" 404 157 "" "docker/1.13.1 go/go1.9.4 kernel/3.10.0-862.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"

**Comment by gogeof** [comment]
It seems docker client will trying to modify some image info when pushing image to registry. 
and registry seems unkown redirect means.

docker client(100.69.224.45) -> haproxy(100.69.224.142) -> registry

![image](https://user-images.githubusercontent.com/13129099/49484300-7b64da00-f871-11e8-81b7-8bd3dfc01863.png)

**Comment by gogeof** [comment]
1. docker client ask for image blob, and registry return not content (201)
2. docker client try to put image blob info to registry (using port 80, but why?)
3. haproxy tall docker client to use port 443
4. docker client seems unkown what is redrect, and keep trying

docker client(100.69.224.45) -> haproxy(100.69.224.142) -> registry(100.69.224.133)

![image](https://user-images.githubusercontent.com/13129099/49485141-b0bef700-f874-11e8-9d80-69beb4c92150.png)

**Comment by gogeof** [comment]
也许，这个就是问题的根本原因：

![image](https://user-images.githubusercontent.com/13129099/49498843-58edb380-f8a7-11e8-9083-d5b14c1c7cbf.png)

**Comment by gogeof** [comment]
When I follow this document to remove the proxy_set_header X-Forwarded-Proto $$scheme option in harbor nginx config. It works.

https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#troubleshooting

![image](https://user-images.githubusercontent.com/13129099/49526049-f7026d80-f8e9-11e8-8d5b-ebb6288648a1.png)

Here is My haproxy config:

```yaml
global
  daemon
  log  127.0.0.1 local0 info
  tune.ssl.default-dh-param 2048
  maxconn  20000
  pidfile  /app/haproxy/run/haproxy.pid
  stats  socket /app/haproxy/lib/haproxy/stats
  tune.bufsize  131072
  user mwop
  group mwop
  tune.ssl.default-dh-param 2048

defaults
  log  global
  maxconn  10000
  mode  http
  option  dontlog-normal
  option  http-server-close
  retries  3
  stats  enable
  timeout  http-request 10s
  timeout  queue 1m
  timeout  connect 10s
  timeout  client 1m
  timeout  server 30m
  timeout  check 10s

listen Stats
  bind 0.0.0.0:10000
  mode http
  stats enable
  stats uri /
  stats refresh 5s
  stats show-node
  stats show-legends
  stats hide-version

frontend https_frontend
  bind *:80
  bind *:443 ssl crt  /app/haproxy/cert/sit.xxx.com.pem
  acl secure dst_port eq 443
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  redirect scheme https if !{ ssl_fc }
  rspadd Strict-Transport-Security:\ max-age=31536000;\ includeSubDomains;\ preload
  rsprep ^Set-Cookie:\ (.*) Set-Cookie:\ \1;\ Secure if secure
  option httpclose
  default_backend web_server

backend web_server
  mode http
  balance roundrobin
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  cookie SERVERID insert indirect nocache
  server s1 100.xxx.xxx.133:80 check cookie s1
```

**Comment by tigerwolfs** [comment]
Hi, I have similar issue but https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#troubleshooting doesnt exist anymore, maybe you remember how was the Harbor configuration (values.yml) and what to modify
