### ISSUE TITLE
config.yml permissions issue

### ISSUE THREAD

**Issue by SDBrett** [goharbor/harbor#6412]
Harbor release 1.6.2

I've been attempting to install Harbor on a fresh photon 2.0 installation and have been running into issues with several of the containers getting stuck in a 'restarting' state.

Logs for registry, ui, and jobserver showed permission errors for the config.yml.

```
Dec  3 21:30:46 172.18.0.1 registry[286]: configuration error: open /etc/registry/config.yml: permission denied
Dec  3 21:30:46 172.18.0.1 registry[286]:
Dec  3 21:30:46 172.18.0.1 registry[286]: Usage:
Dec  3 21:30:46 172.18.0.1 registry[286]:   registry serve <config> [flags]
Dec  3 21:30:46 172.18.0.1 registry[286]: Flags:
Dec  3 21:30:46 172.18.0.1 registry[286]:   -h, --help=false: help for serve
```

After changing the directory and file permissions to 666 on the docker host, the containers started on the next reboot cycle. The exception was the registry container where the permissions needed to be 777 before it would start.

I am running the docker host as root as I've just been testing around so the owner and group of the files was root:root. 

It appears that the containers that I've been having issues with are those which use the user account harbor.

**Comment by SDBrett** [comment]
After looking at this further, it appears that the install.sh script is not properly configuring the 0644 mask to the config.yml files. This causes that containers to restart and fail. Due to them not running before the proxy service the proxy container enters the state UP unhealthy.

**Comment by SDBrett** [comment]
I build a Ubuntu VM and tested the process without changes to the files retrieved from git and it worked.

Previously I had an issue with the docker cmd used within the Makefile (pr https://github.com/goharbor/harbor/pull/6414) but even that update was not required.

There are application version differences between PhotonOS and Ubuntu worth pointing out.

Ubuntu:
	Docker: Docker version 18.09.0, build 4d60db4
	Docker-Compose: docker-compose version 1.23.1, build b02f1306
	Go:  go version go1.10.4 linux/amd64
	Python: Python 2.7.15rc1

Photon:
	Docker: Docker version 17.06.0-ce, build 02c1d87
	Docker-Compose: docker-compose version 1.23.1, build b02f1306
	Go:  go version go1.10.3 linux/amd64
	Python: Python 2.7.15

**Comment by SDBrett** [comment]
Tested on Ubuntu 16.04 with Docker 17.06.0-ce and was able to compile without issue. 
Doesn't appear to be related to docker version.

**Comment by rbkaspr** [comment]
@SDBrett Assuming we're talking about the issues I'm seeing in 1.7 where the generated config files are not accessible to the Docker containers, my workaround has been to modify the install.sh script to add a command to chown everything in the common/config directory to uid/gid **10000** (which the container processes run as), after the config generation step, make setup work as intended.

Not sure if that's the correct fix, but it's the one I've found.

**Comment by reasonerjt** [comment]
Are you still seeing this issue? @SDBrett

**Comment by SDBrett** [comment]
Changed OS away from Photon to Ubuntu and no longer experiencing the issue

**Comment by guogyh** [comment]
when i use harbor v1.7.1 in centeros 7.5, i still seeing this issue@SDBrett

**Comment by guogyh** [comment]
when i use harbor v1.7.1 in centeros 7.5, i still seeing this issue @SDBrett

**Comment by QiuToo** [comment]
我也遇到了这个问题，幸运的 是我对照其它实例的权限解决了
