### ISSUE TITLE
Unknown errors have occurred when adding a nonexistence user to the project

### ISSUE THREAD

**Issue by luwang-vmware** [goharbor/harbor#6422]
Steps:
1. Login Harbor and pick a project and click the Members tab and click button of '+USER'
2. I typed in non-existence username here and click OK.
3. It showed as 'Unknown errors have occurred' and detail response as below.
Request URL: https://***/api/projects/3/members
Request Method: POST
Status Code: 404 Not Found
Remote Address: ***:3128
Referrer Policy: no-referrer-when-downgrade

Is it possible to give clear information that the member does not exist?

**Comment by hanoisteve** [comment]
I am still seeing this error
