### ISSUE TITLE
Cannot enter into the public projects in the global search result page without login

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6435]
Steps to reproduce the issue:
1. Logout
2. Global search "library"
3. Click the "library" in the search result page

Expected: Enter into the project and get repository list
Got: Login page

**Comment by zhoumeina** [comment]
Because get current user api returns 401, and the routergateway helps to redirect to login page. @ninjadq , could you please take a look?

**Comment by ywk253100** [comment]
The same issue to the chart got in the search result page.

**Comment by ninjadq** [comment]
This is by design, I remember you said that user without logged in cannot visit any content is the right behavior @reasonerjt

**Comment by dnovvak** [comment]
Hello,
@reasonerjt Public projects from definition should be available without authentication I think. Compare DockerHUB approach.

Now I can see inconsistency between UI/REST and native registry interface. It is possible to pull images from public projects but it is impossible to view/search public projects in the UI/REST.

It would be great to have the issue fixed soon.

**Comment by reasonerjt** [comment]
This is a bug from UI but we consider for private registry user the impact is low.
We're considering to change the design so even for public project user has to login to view.
We'll revisit it after v1.8.0

**Comment by jwangyangls** [comment]
Requires a backend to provide a list of permissions without user login

**Comment by kirbyzhou** [comment]
This feature is very useful for us.
Please fix it.

**Comment by reasonerjt** [comment]
To fix this the `permission` API should return empty permission list rather than 401.

**Comment by stefanvangastel** [comment]
Could this get a reboot? Really need access to public projects for non-logged in users. Using LDAP/AD auth for specific groups so all other Guest / Anonymous users should be able to see public project contents.

**Comment by virgo47** [comment]
This would really be helpful, I was very surprised it doesn't work. There are some workarounds such as `publicAndNotLogged=yes` to browse a public repo, but that's not ideal experience. We either have to have two separate Harbors to offere this experience - and the public one can't be integrated with any OIDC anyway, so it seems.

**Comment by ebuildy** [comment]
I am available to help on this one!
