### ISSUE TITLE
Prompt 'Unknown errors' when perform reset password while actual error reason is "the new password can not be same with the old one"

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6438]
Go to Administrator->Users, perform "Reset Password" action, when I input a password which is the same with the old one, the error message is 'Unknown errors' while the actual reason is "the new password can not be same with the old one". GUI should prompt the accurate reason for operator.
![image](https://user-images.githubusercontent.com/44018302/49489859-e9b49700-f887-11e8-98f7-6ffe0baae724.png)

![image](https://user-images.githubusercontent.com/44018302/49489970-7a8b7280-f888-11e8-9be6-40444777c665.png)

**Comment by pureshine** [comment]
fixed by pr #6456
