### ISSUE TITLE
Incorrect user credential can search/fetch the helm chart package

### ISSUE THREAD

**Issue by luwang-vmware** [goharbor/harbor#6439]
Steps:
1. Install helm 2.11 in my env
2. helm repo add --ca-file /etc/docker/certs.d/A.B.C.D/ca.crt --username luwang_2 --password Luwang124 repo_lu_abc2 https://A.B.C.D/chartrepo/lu_abc (**username/password are not correct, but repo add operation can succeed, Is it as expected**)
3. helm repo list can show that new added chart repo as below
helm repo list
NAME        	URL                                   
repo_lu_abc2	https://A.B.C.D/chartrepo/lu_abc
4.  search/fetch opearation also can work
root@localhost:/home/helm_chart/aa# helm search -l
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                
repo_lu_abc2/lu_chart_1	0.4.0        	1.0        	A Helm chart for Kubernetes
repo_lu_abc2/lu_chart_1	0.1.0        	1.0        	A Helm chart for Kubernetes
root@localhost:/home/helm_chart/aa# helm fetch repo_lu_abc2/lu_chart_1
root@localhost:/home/helm_chart/aa# ls
lu_chart_1-0.4.0.tgz

**Comment by reasonerjt** [comment]
It may be helpful if we can verify the password and return an error.

**Comment by ninjadq** [comment]
It seems that the repo add is public. I tried private repo in my env. And the wrong password will cause 401
