### ISSUE TITLE
Harbor offline installer 1.6.2 can access the ui ,but can't use "docker login" command to login.

### ISSUE THREAD

**Issue by huahouye** [goharbor/harbor#6441]
According to this doc [https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md](https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md) and this [https://github.com/goharbor/harbor/blob/master/docs/configure_https.md](https://github.com/goharbor/harbor/blob/master/docs/configure_https.md) I deploy harbor-offline-installer-v1.6.2 in my VirtualBox.

```
Ubuntu Server 18.04.1
Docker 18.06.1-ce
Docker-compose 1.22.0
harbor-offline-installer-v1.6.2
```

### Here is what i did.

* Step 1:

wget https://storage.googleapis.com/harbor-releases/release-1.6.0/harbor-offline-installer-v1.6.2.tgz && \\
tar zxf harbor-offline-installer-v1.6.2.tgz && \\
cd harbor && \\
mkdir cert && \\
cd cert

* Step 2

cat > v3.ext <<-EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth 
subjectAltName = IP:20.10.31.243
EOF

openssl genrsa -out ca.key 4096 && \\
openssl req -x509 -new -nodes -sha512 -days 3650 \
    -subj "/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243" \
    -key ca.key \
    -out ca.crt && \\
openssl genrsa -out 20.10.31.243.key 4096 && \\
openssl req -sha512 -new \
    -subj "/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243" \
    -key 20.10.31.243.key \
    -out 20.10.31.243.csr && \\
openssl x509 -req -sha512 -days 3650 \
    -extfile v3.ext \
    -CA ca.crt -CAkey ca.key -CAcreateserial \
    -in 20.10.31.243.csr \
    -out 20.10.31.243.crt && \\
openssl x509 -inform PEM -in 20.10.31.243.crt -out 20.10.31.243.cert

sudo mkdir -p /data/cert/ && \\
sudo chmod -R 777 /data/cert/ && \\
cp 20.10.31.243.crt 20.10.31.243.key /data/cert/ && \\
ls -al /data/cert/

sudo rm -fr /etc/docker/certs.d/20.10.31.243/ && \\
sudo mkdir -p /etc/docker/certs.d/20.10.31.243/ && \\
sudo cp 20.10.31.243.cert 20.10.31.243.key ca.crt /etc/docker/certs.d/20.10.31.243/ && \\
sudo ls -al /etc/docker/certs.d/20.10.31.243/ && \\
sudo systemctl restart docker

sudo cp ca.crt 20.10.31.243.crt /usr/local/share/ca-certificates/ && \\
sudo update-ca-certificates

* Step 3

cd ..

vi harbor.cfg

```
## change those four options
hostname = 20.10.31.243
ui_url_protocol = https
ssl_cert = /data/cert/20.10.31.243.crt
ssl_cert_key = /data/cert/20.10.31.243.key
## other options use default value
##
## maybe there are some options need to be changed ?
```

* Step 4

sudo apt install -y python-minimal && \\
sudo ./install.sh --with-notary --with-clair

openssl s_client -connect 20.10.31.243:443

```
CONNECTED(00000003)
depth=1 C = TW, ST = Taipei, L = Taipei, O = example, OU = Personal, CN = 20.10.31.243
verify return:1
depth=0 C = TW, ST = Taipei, L = Taipei, O = example, OU = Personal, CN = 20.10.31.243
verify return:1
---
Certificate chain
 0 s:/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243
   i:/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFujCCA6KgAwIBAgIJAMBj
... some stuff
TojhWC+LuRqNCbTQqXR9l1/tEC1+j4jkLd0Ld0v
jTaB+07Hu4UY5rTs6caXyDt51I+m0PjlV7soBzSd
-----END CERTIFICATE-----
subject=/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243
issuer=/C=TW/ST=Taipei/L=Taipei/O=example/OU=Personal/CN=20.10.31.243
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2396 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 80EC027C2600C15F4F2FAB5BA60A316F2A3021774D8CAA4D52FDF500E92B9B2B
    ... some stuff
    00a0 - 41 27 3e 67 e7 9a bd 64-ba c1 68 cb 5b 8d 43 f2   A'>g...d..h.[.C.

    Start Time: 1543984344
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
^C
```

open https://20.10.31.243 in browser outside the VirtualBox everything just fine.
but "docker login 20.10.31.243" responses like this

```
huahouye@vb-u18041:~/harbor$ docker login  20.10.31.243
Username: admin
Password:
Error response from daemon: Get https://20.10.31.243/v2/: unable to decode token response: invalid character '<' looking for beginning of value
```

I think you can change IP address or domain and follow Step 1-4 and reproduct this issus.

please help, Thanks in advance.

**Comment by heimuya** [comment]
I have reproducted the same error, can not login through docker-cli

**Comment by heimuya** [comment]
find the solution. Should change the docker config file /lib/systemd/system/docker.service, and set ExecStart=/usr/bin/dockerd -H unix:// --insecure-registry [your IP address or hostname]
