### ISSUE TITLE
a non-admin privilege user can not add harbor repo with helm

### ISSUE THREAD

**Issue by luwang-vmware** [goharbor/harbor#6444]
Steps：
1. Admin User create a non-admin user account as luwang_2
2. using the helm cli to add repo as below and show 403 forbidden error
root@localhost:/home# helm repo add test --ca-file /etc/docker/certs.d/a.b.c.d/ca.crt  https://a.b.c.d/chartrepo --username luwang_2 --password Luwang123
Error: Looks like "https://a.b.c.d/chartrepo" is not a valid chart repository or cannot be reached: Failed to fetch https://a.b.c.d/chartrepo/index.yaml : 403 Forbidden
3. within the admin account, everything groot@localhost:/home# helm repo add test_admin --ca-file /etc/docker/certs.d/a.b.c.d/ca.crt  https://a.b.c.d/chartrepo --username admin --password Harbor12345
"test_admin" has been added to your repositories
oes well.

**Comment by steven-zou** [comment]
@luwang-vmware 

The root index can only be added by the admin role user.

A common user can only add the namespace index `/chartrepo/:repo`. That's the design for current implementation.

As work as designed, I'll close this issue.
