### ISSUE TITLE
Image label filter should consistent with charts

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6447]
The charts cannot be filtered by labels, but the images can.

**Comment by steven-zou** [comment]
I'll check and see if we can meet the 1.7 time window.

**Comment by zhoumeina** [comment]
@ywk253100 , I tested in my local. It works.

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/49624150-4f7d5c00-fa0b-11e8-97c2-420e78a38268.png)
This is a functional support for helm chart. Actually, not a bug. It is a enhancement.

**Comment by reasonerjt** [comment]
@zhoumeina Does it work or not???

**Comment by ninjadq** [comment]
Filter chart by label is already in UI, but based on the convention of clarity, You should click filter icon in the right of label header to open the filter dialog.
![image](https://user-images.githubusercontent.com/1069785/49715420-426ea000-fc8b-11e8-840d-c0b4675ccdfa.png)

**Comment by ninjadq** [comment]
We need to refactor the image's label filter to make them consistent.
