### ISSUE TITLE
Test LDAP server error without save configuration

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6450]
[Steps]
1, admin - configuration
2, change auth to LDAP, and set up the ldap server.
3, test it with error response.
4, save it, test it with success response

![image](https://user-images.githubusercontent.com/2841473/49501209-4d04f000-f8ad-11e8-8837-d66d9ea1fc38.png)

[Root cause]
the ladp search password is missed in the payload of the request.

**Comment by reasonerjt** [comment]
Let's keep this open until the PR is merged.

**Comment by reasonerjt** [comment]
And I don't think this has to be a high priority, if it requires more effort than estimated earlier, we can defer it.

**Comment by stonezdj** [comment]
fixed #7328
