### ISSUE TITLE
Null error display when changing password

### ISSUE THREAD

**Issue by pureshine** [goharbor/harbor#6454]
Steps:
  1、Modify the current user password
![image](https://user-images.githubusercontent.com/40712758/49505182-2d25fa00-f8b6-11e8-8474-f832470d039d.png)

2、Current password input error，the error is empty.
![image](https://user-images.githubusercontent.com/40712758/49505052-e33d1400-f8b5-11e8-99f2-2bd461c1c298.png)

Request URL: https://***/api/users/1/password
Request Method: PUT
Status Code: 403
response: "↵"

**Comment by ywk253100** [comment]
Fixed.
