### ISSUE TITLE
REBUILDCLARITYFLAG param spelled wrong in Makefile

### ISSUE THREAD

**Issue by balu7771** [goharbor/harbor#6459]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I tried to use param : REBUILDCLARITYFLAG so as to build the image with proxy setting, but I found that param had different spelling as REBUILDCLIATRYFLAG down the code in Makefile (v1.6.2).

https://github.com/goharbor/harbor/blob/v1.6.2/Makefile#L390 

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.6.2]

**Comment by ninjadq** [comment]
refresh clarity is no longer needed in the current, and these codes are already removed in the master branch.

**Comment by reasonerjt** [comment]
I see, I'm closing this issue.

Thanks for reporting @balu7771
