### ISSUE TITLE
LDAP integration cannot get group info from LDAP

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor#6461]
I was able to set up LDAP integration and get authentication working. However, Harbor is not able to get the group info for the logged in user from LDAP. After looking into the LDAP logs, we found that Harbor is expecting the groups to be returned in a "memberof" field. However, our LDAP has no memberof attribute in user profile. It expects two transactions, one asking user and another asking for group:

#search for users
base="ou=xxx,ou=people,dc=xxx,dc=com" scope=sub filter="(&(objectClass=inetOrgPerson)(mail=xxxxxx@xxx.com))" attrs="mail,displayName,labeledUri" 

#search for group
base="ou=xxx,ou=groups,ou=People,dc=xxx,dc=com" scope=one filter="(&(objectClass=groupOfUniqueNames)(&(cn=*)(uniqueMember=uid=xxx,ou=2756,ou=xxx,ou=People,dc=xxx,dc=com)))" attrs="cn"

Can this be supported?

**Comment by shen3lu4** [comment]
Can the application check for both "memberOf" and "isMemberOf" attributes for group info since isMemberOf is the LDAP default?
Or another way is to allow a custom attribute to be chosen for the group info in configuration?

**Comment by stonezdj** [comment]
The PR seems to fix the memberOf and isMemberOf issue #6161

**Comment by stonezdj** [comment]
Fixed by PR #6599
