### ISSUE TITLE
Unable to sign images using notary after upgrading to 1.6

### ISSUE THREAD

**Issue by srinivasa-vasu** [goharbor/harbor#6465]
When I try to sign the images, on the client side I am getting the following exception,

`2c178a8093fd: Layer already exists
12c374f8270a: Layer already exists
0c3170905795: Layer already exists
df64d3292fd6: Layer already exists
Signing and pushing trust metadata
unable to reach trust server at this time: 500.`

On the server side, if I look at the logs, I could see some DB related issues,
`Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #015
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #033[35m(pq: permission denied for sequence private_keys_id_seq)#033[0m
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #033[33m[2018-12-05 16:32:36]#033[0m #033[31;1m #033[0m
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #015
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #033[35m(pq: permission denied for sequence private_keys_id_seq)#033[0m
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: #033[33m[2018-12-05 16:32:36]#033[0m #033[31;1m #033[0m
Dec  5 16:32:36 172.18.0.1 notary-signer[2515]: {"go.version":"go1.7.3","level":"error","msg":"CreateKey: failed to create key: failed to store key: failed to add private key to database: 07de3a0f172bc9a068fe76f1eb0287017962c9cf17ee1d808623e2009f2e9347","time":"2018-12-05T16:32:36Z"}`

**Harbor version: 1.6.x**

**Comment by srinivasa-vasu** [comment]
Not a fresh install. Upgraded

`Dec  6 04:17:06 172.18.0.1 notary-server[2515]: {"go.version":"go1.7.3","masked.domain.com/spring/spring-music:blue":"gun","http.request.host":"masked.domain.com:4443","http.request.id":"bb526810-0254-4652-9398-719fceb472b7","http.request.method":"GET","http.request.remoteaddr":"106.51.26.84","http.request.uri":"/v2/masked.domain.com/spring/spring-music:blue/_trust/tuf/timestamp.key","http.request.useragent":"Go-http-client/1.1","level":"error","msg":"500 GET timestamp key: rpc error: code = 13 desc = Key creation failed","time":"2018-12-06T04:17:06Z"}
Dec  6 04:17:06 172.18.0.1 notary-server[2515]: {"go.version":"go1.7.3","http.request.host":"masked.domain.com:4443","http.request.id":"bb526810-0254-4652-9398-719fceb472b7","http.request.method":"GET","http.request.remoteaddr":"106.51.26.84","http.request.uri":"/v2/masked.domain.com/spring/spring-music:blue/_trust/tuf/timestamp.key","http.request.useragent":"Go-http-client/1.1","level":"error","msg":"unknown: unknown error: rpc error: code = 13 desc = Key creation failed","time":"2018-12-06T04:17:06Z"}
Dec  6 04:17:06 172.18.0.1 notary-server[2515]: {"go.version":"go1.7.3","http.request.host":"masked.domain.com:4443","http.request.id":"bb526810-0254-4652-9398-719fceb472b7","http.request.method":"GET","http.request.remoteaddr":"106.51.26.84","http.request.uri":"/v2/masked.domain.com/spring/spring-music:blue/_trust/tuf/timestamp.key","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"36.178044ms","http.response.status":500,"http.response.written":70,"level":"info","msg":"response completed","time":"2018-12-06T04:17:06Z"}`

**Comment by wy65701436** [comment]
@srinivasa-vasu thank you for raising this bug, it an issue of DB migrator.

Notary uses the user(signer/server) to operate the tables. But after the migration, the owner of these tables changed to Postgres, that's why you got the permission denied for the log.

We will provide a fix soon, thanks.

**Comment by srinivasa-vasu** [comment]
@wy65701436 - any workaround that you can suggest?

**Comment by wy65701436** [comment]
@srinivasa-vasu you can execute the followings sqls in your harbor DB container.

 ```
\c notaryserver

ALTER TABLE tuf_files OWNER TO server;
ALTER SEQUENCE tuf_files_id_seq OWNER TO server;
ALTER TABLE change_category OWNER TO server;
ALTER TABLE changefeed OWNER TO server;
ALTER SEQUENCE changefeed_id_seq OWNER TO server;
ALTER TABLE schema_migrations OWNER TO server;
SELECT setval('changefeed_id_seq', max(id)) FROM changefeed;
ALTER TABLE "changefeed" ALTER COLUMN "id" SET default nextval('changefeed_id_seq');

\c notarysigner

ALTER TABLE private_keys OWNER TO signer;
ALTER SEQUENCE private_keys_id_seq OWNER TO signer;
ALTER TABLE schema_migrations OWNER TO signer;
```

**Comment by srinivasa-vasu** [comment]
Thanks. This workaround helped.

**Comment by wy65701436** [comment]
close it as code has been merge into master, and will provide a new migrator with tag v1.6.1 and update document.
