### ISSUE TITLE
Return message in API response

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6467]
Currently, the response body of some APIs only contains an enter char, this makes the UI difficult to render the page. Need to return messages to the frontend.

**Comment by wy65701436** [comment]
the root cause is to set the parameter to "" in RenderError(), this function eventually calls doPrintln() to write an "\n".

**Comment by ywk253100** [comment]
Move it out of sprint 49 as we'll provide a unified error struct in the response.

**Comment by ywk253100** [comment]
Will be done in #6957.
