### ISSUE TITLE
Should involve ux in the release plan meeting, so the feature design should be finished in advance

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#6477]
Current process, only developers are involved in the release plan, ux may miss some important message and information about features and the priority. 

We need to deliver these information to ux designers as soon as possible. So the design can be finished before developers start to design the architecture and coding. 

Furthermore, leave enough time for designers to change the design and provide good design for harbor community.

**Comment by reasonerjt** [comment]
How'bout add that as a part in the proposal, but I don't think it should block the approval of a proposal if the UI design is not fully agreed on.

We can start discussion regarding UI design while writing proposal, and reference it in the proposal when it's ready.

Thoughts?  @steven-zou

**Comment by reasonerjt** [comment]
cc @clouderati
