### ISSUE TITLE
国内镜像复制到海外 aws 镜像仓库出现 getsockopt: connection timed

### ISSUE THREAD

**Issue by yeruisen** [goharbor/harbor#6490]
国内阿里云上海搭建了一个 harbor,使用 oss 存储。
国外在 aws 欧洲也搭建一个 harbor，使用 s3 。
国内镜像同步到国外时，出现如下错误：
![image](https://user-images.githubusercontent.com/12295648/49683535-c85edf80-fb01-11e8-9719-68e3027ea9cf.png)

看日志好像是，国内 harbor 会去 s3 上 check blob 是否存在。但是在访问 s3 时，出现网络问题；
请问我是否支持可以配置 http proxy 。

这种问题经常出现，我想这种问题应该会很正常，在差的网络下。是否考虑增加可以配置 http proxy.

**Comment by ywk253100** [comment]
目前并不支持配置proxy

**Comment by yeruisen** [comment]
如果要解决跨海外稳定复制镜像的问题，是否考虑能配置 proxy 的功能，或者目前能给什么好的建议吗?

**Comment by ywk253100** [comment]
有个PR要fix这个：https://github.com/goharbor/harbor/pull/3474

**Comment by yeruisen** [comment]
ok ,谢谢

**Comment by ywk253100** [comment]
Fixed by #6541.
