### ISSUE TITLE
how to disable img scan_all job?

### ISSUE THREAD

**Issue by xuejipeng** [goharbor/harbor#6492]
I didn't install Clair，but the img scan job still tigger，how do i shut the job down?
There's a lot of error in my Img_scan_job table.

**Comment by wy65701436** [comment]
Just set the schedule of scan to None in the configuration page.

**Comment by xuejipeng** [comment]
I use the version 1.5.2，there is no such option，can I configure it in the configuration file?

**Comment by xuejipeng** [comment]
@wy65701436

**Comment by wy65701436** [comment]
@xuejipeng did you install harbor with clair?

**Comment by xuejipeng** [comment]
No Clair installed

**Comment by wy65701436** [comment]
@reasonerjt can you help to answer?

**Comment by reasonerjt** [comment]
@xuejipeng 
Let me clarify.
If Clair was not installed, how come the scheduled scan was enabled?
Did you firstly installed Clair, enabled weekly/daily "Scan All images", then remove Clair during the upgrade?

**Comment by xuejipeng** [comment]
I installed a new harbor and then imported the old harbor MySQL data into the new harbor , the new harbor not install Clair, the old harbor has been installed Clair and remove in the old harbor

**Comment by xuejipeng** [comment]
@reasonerjt  Can i stop the scan?

**Comment by reasonerjt** [comment]
Yes, the scheduled scan is stored in DB, so when you migrate the data the schedule was carried to your new instance.
You can remove it from your DB manually.
You'll need something like:
https://github.com/goharbor/harbor/blob/master/make/migrations/postgresql/0002_1.7.0_schema.up.sql#L2

**Comment by xuejipeng** [comment]
I'm using MySQL DB only and i can't find any data related to this SQL.

**Comment by xuejipeng** [comment]
@reasonerjt 
when i restart harbor, the scan_all_policy will triger too, and will wait more then 10 min to start it, it's painful.  
![image](https://user-images.githubusercontent.com/18901031/50628413-f4d81100-0f72-11e9-91d6-75746695a4bf.png)

**Comment by reasonerjt** [comment]
@xuejipeng sorry for the late response, could you check if there's a file `config.json` on your docker host where Harbor is running?  By default it should be in `/data/` directory, if the configuration is not in DB it's in this .json file and you should do a similar change to the .json file and restart Harbor and the `scan all` job will not be triggered.

**Comment by xuejipeng** [comment]
my harbor version was 1.5.2 and i can't find the config.json too.

in the data dir
![image](https://user-images.githubusercontent.com/18901031/51172758-e54fb500-18ee-11e9-8546-8c8c492796d5.png)
in the harbor install dir
![image](https://user-images.githubusercontent.com/18901031/51172875-2d6ed780-18ef-11e9-8523-0177eccce17e.png)

**Comment by xuejipeng** [comment]
@reasonerjt

**Comment by reasonerjt** [comment]
@xuejipeng Did you have a chance to check the database? it should be in the `properties` table under database `registry`

**Comment by xuejipeng** [comment]
yes ,this is all fields,i don't know which field I need to modify.
![image](https://user-images.githubusercontent.com/18901031/55534368-cd662100-56e6-11e9-80af-cf1cb0e873f5.png)
![image](https://user-images.githubusercontent.com/18901031/55534403-ec64b300-56e6-11e9-93d2-1f4b3cc49727.png)

**Comment by reasonerjt** [comment]
I belive the scan_all should be disabled already, if you restart it won't be triggered anymore.

**Comment by xuejipeng** [comment]
@reasonerjt  No, I've restarted this profile many times, but this problem has always existed.

**Comment by xuejipeng** [comment]
@reasonerjt  Do you have any other suggestions? It took me one hours to restart for the last time.

**Comment by xuejipeng** [comment]
@reasonerjt I solved the problem. `insert into properties (k,v) values ("scan_all_policy",'{"type":"none"}');`

**Comment by yourmoonlight** [comment]
> @reasonerjt I solved the problem,thanks ! `insert into properties (k,v) values ("scan_all_policy",'{"type":"none"}');`

您好，请问插入这条记录之后，重启harbor就生效了吗？
