### ISSUE TITLE
Compatibility testing with docker registry v2.7.0

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6514]
Needs to consider the test the compatibility on following components.

1, docker client, 17/18 ...
2, docker registry, v2.6.2/v2.7.0 ...
3, notary 0.6.0?

**Comment by mmpei** [comment]
it will be a wonderful upgrade for harbor.

**Comment by wy65701436** [comment]
passed on docker client 17+/notary 0.6.0/clair 2.0.7
