### ISSUE TITLE
Multiple not replicated Harbor registries sharing the same S3 bucket

### ISSUE THREAD

**Issue by kaivanov** [goharbor/harbor#6517]
I have two Harbor registries sharing the same S3 bucket. Only one of the instances see the project and images however (the one they were originally created and uploaded from). I tried creating the same project on the second harbor instance (this was suggested in a different issue thread) in order for the back-end database to be able to see it, but that did not help. I realize that this should probably be setup using replication, but unfortunately both Harbor instances cannot directly communicate. Is there anything else that can be done for multiple Harbor instances to share the same S3 bucket and their UI's to be in-sync ?

**Comment by ywk253100** [comment]
I think the replication is the right way to sync images between the Harbor instances, so is there any solution to fix the communication issue in your env? 

Or you can try to share the database between the instances, but I can see some issues for this solution, such as image signatures, and we don't test it.

**Comment by clouderati** [comment]
Not to minimize the importance of the issue that you're having, but I'm curious what is preventing the communication between Harbor instances. Is this a policy (e.g., company security policy) that prevents the two nodes from reaching each other?

@ywk253100 is correct – replication is probably your best bet here.

**Comment by kaivanov** [comment]
I see, that's too bad really, considering that the S3 bucket can be shared. It would be nice to be able to save some metadata on the S3 bucket as well so multiple Harbor instance can read from it and be in-sync, but I understand that the UI depends on a local datastore.

In our setup, we have an environment in a separate VPC than the rest of the environments and we don't want to allow communication between them (I know we can do VPC peering with security groups to minimize exposure etc). In this setup we use multiple Docker registries per environment and they all share the same S3 bucket, so they are all in-sync when new images are pushed by the CI pipeline. I was hoping we can use Harbor in the same way. Thank you for the quick response btw !
