### ISSUE TITLE
Upgrade from v1.3.0-rc4  to v1.6.3 fails

### ISSUE THREAD

**Issue by PushpalathaT** [goharbor/harbor#6523]
I am trying to upgrade from v1.3.0-rc4  to v1.6.3 fails.  Please let me know how to resolve the issue.

Took backup successfully.
docker run -it  --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /backup:/harbor-migration/backup goharbor/harbor-db-migrator:1.3 backup

Upgrade fails with below error:
=========================
docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.6.3 up

Unable to find image 'goharbor/harbor-migrator:v1.6.3' locally
v1.6.3: Pulling from goharbor/harbor-migrator
5d3b3b8376c7: Pull complete
f4c8f88bac52: Pull complete
ae7262289b8a: Pull complete
e39f809a25ec: Pull complete
Digest: sha256:a22b5c3f9ea495230a7ed3a084c77258c72021de5999c8b77d1944454d99ad14
Status: Downloaded newer image for goharbor/harbor-migrator:v1.6.3
Please backup before upgrade,
Enter y to continue updating or n to abort: y
Traceback (most recent call last):
  File "./migrator.py", line 232, in <module>
    main()
  File "./migrator.py", line 178, in main
    db_migrator = DBMigrator(commandline_input.target_version)
  File "./migrator.py", line 34, in __init__
    conf.write(open(path).read())
IOError: [Errno 21] Is a directory: '/harbor-migration/harbor-cfg/harbor.cfg'

Thanks in Advance

**Comment by wy65701436** [comment]
can you check whether /root/harbor/harbor.cfg is a file or a directory?

**Comment by PushpalathaT** [comment]
Thank you . It’s a directory. 

I am getting below issue fails at step7
I have followed below steps .https://github.com/goharbor/harbor/blob/release-1.5.0/docs/migration_guide.md
Can you Please suggest where i went wrong?

1.cd /root/harbor
  docker-compose down

2.Copied /root/harbor to apps/datascience/my_backup_dir/harbor

3.docker pull goharbor/harbor-db-migrator:1.3

4.docker run -it  --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /backup:/harbor-migration/backup goharbor/harbor-db-migrator:1.3 backup

6. docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg  goharbor/harbor-migrator:v1.6.3 up

7. ./install.sh  fails
[Step 1]: preparing environment ...
Clearing the configuration file: ./common/config/adminserver/env
Clearing the configuration file: ./common/config/ui/env
Clearing the configuration file: ./common/config/ui/app.conf
Clearing the configuration file: ./common/config/ui/private_key.pem
Clearing the configuration file: ./common/config/db/env
Clearing the configuration file: ./common/config/jobservice/env
Clearing the configuration file: ./common/config/jobservice/app.conf
Clearing the configuration file: ./common/config/registry/config.yml
Clearing the configuration file: ./common/config/registry/root.crt
Clearing the configuration file: ./common/config/nginx/nginx.conf
Clearing the configuration file: ./common/config/log/logrotate.conf
Traceback (most recent call last):
  File "./prepare", line 163, in <module>
    uaa_ca_root = rcp.get("configuration", "uaa_ca_root")
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'uaa_ca_root' in section: u'configuration'

Thanks in Advance

**Comment by wy65701436** [comment]
By default, the harbor.cfg used by the install.sh is the one in the offline installer, please either to modify it or to replace it with upgraded one.

**Comment by PushpalathaT** [comment]
By default, the harbor.cfg used by the install.sh is the one in the offline installer, please either to modify it or to replace it with upgraded one.

Under /root/harbor it has the upgraded harbor.cfg i.e with postgres DB details  and some extra configuration like Clair DB configuration and 
Redis server configuration. 

Under /data/database it has postgres

 I am not sure why ./install.sh is failing 

Thanks

**Comment by wy65701436** [comment]
did you move the updated cfg into your installer directory? If not, please do it. If so, can you try to execute the prepare script in the installer directory？

And make sure your installer version is v1.6.3.

**Comment by PushpalathaT** [comment]
Thanks for the update.

Below docker run has updated /root/harbor/harbor.cfg (with New postgres Db details instead of mysql). 
In the same harbor dir install.sh exits

docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.6.3 up

snippet of docker run output.
========================================================
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
input version: 1.3.0, migrator chain: ['1.5.0', '1.6.0', '1.7.0']
migrating to version 1.5.0
migrating to version 1.6.0
migrating to version 1.7.0
Written new values to /harbor-migration/harbor-cfg/harbor.cfg
===========================================================

Prepare.sh fails with same error.

harbor]# ./prepare
Traceback (most recent call last):
  File "./prepare", line 163, in <module>
    uaa_ca_root = rcp.get("configuration", "uaa_ca_root")
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'uaa_ca_root' in section: u'configuration'

**Comment by wy65701436** [comment]
That’s should be an issue of migrator of v1.6.3, I will have a update. Did you backup your cfg? Or you can manual copy all of modified settings to the new harbor.cfg as your DB has already succes migrated.

**Comment by PushpalathaT** [comment]
Thanks for the update. Looking forward for your update on "issue of migrator of v1.6.3"
I have the backup of v1.3.0-rc4 and v1.6.3 harbor.cfg and also made necessary configuration changes in harbor.cfg(v1.6.3).

**Comment by wy65701436** [comment]
I have updated the migrator of v1.6.3, you can just try it with --cfg up.

**Comment by PushpalathaT** [comment]
I am getting below error. Can you suggest what need to be done here?

docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.6.3 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
Version of input harbor.cfg is identical to target 1.7.0, no need to upgrade

Thanks,
Pushpa

**Comment by wy65701436** [comment]
can you check the version of you /root/harbor/harbor.cfg? It's in the header of this file.

Let me clarify if you have executed the migrator once, the /root/harbor/harbor.cfg has already upgraded to the latest version v1.7.0(But as I mentioned above, the v1.6.3 has one issue, the latest version should be v1.6.0.).

If you want to execute the command again with the latest v1.6.3 you have to use the backup cfg file rather than the updated one.

**Comment by PushpalathaT** [comment]
Again I have executed below command  with the old v1.3.0-rc4 harbor.cfg file but still install.sh fails with the same error.
Please let me know how to fix this issue

# docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.6.3 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
input version: 1.3.0, migrator chain: ['1.5.0', '1.6.0', '1.7.0']
migrating to version 1.5.0
migrating to version 1.6.0
migrating to version 1.7.0
Written new values to /harbor-migration/harbor-cfg/harbor.cfg
=======================================

./install.sh fails with same error.
[Step 1]: preparing environment ...
Traceback (most recent call last):
  File "./prepare", line 163, in <module>
    uaa_ca_root = rcp.get("configuration", "uaa_ca_root")
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'uaa_ca_root' in section: u'configuration'
[root@dstk8sdev06 harbor]#


Thanks in advance

**Comment by PushpalathaT** [comment]
On a new  harbor setup(v1.3.0-rc4) I have tried upgrading from  v1.3.0-rc4 to v1.6.3 . 
Below shows "migrating to version 1.6.0" and new harbor.cfg shows _version = 1.6.0  but still install.sh fails with same error.
Please let me know how to resolve this.

docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /home/dstadmin/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.6.3 up
============================================================================
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1.5.0 -> 1.6.0, 1.5.0 to 1.6.0
/usr/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
1.6.0 (head)
Upgrade performed.
No directory, logging in with HOME=/
waiting for server to shut down....LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
input version: 1.3.0, migrator chain: ['1.5.0', '1.6.0']
migrating to version 1.5.0
migrating to version 1.6.0
Written new values to /harbor-migration/harbor-cfg/harbor.cfg

./install.sh
===================================================================
[Step 1]: preparing environment ...
Traceback (most recent call last):
  File "./prepare", line 163, in <module>
    uaa_ca_root = rcp.get("configuration", "uaa_ca_root")
  File "/usr/lib64/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option u'uaa_ca_root' in section: u'configuration'

Thanks

**Comment by wy65701436** [comment]
can you confirm the version of your installer? It seems that it's not a v1.6.3

**Comment by wy65701436** [comment]
can you share the /home/dstadmin/harbor/harbor.cfg?

**Comment by PushpalathaT** [comment]
[harbor.zip](https://github.com/goharbor/harbor/files/2679374/harbor.zip)

**Comment by wy65701436** [comment]
The error is because you are using the wrong prepare script.

could you please use the one in the v1.6.3 installer?

Please use the install.sh in the v1.6.3 offline installer, it seems you are using the one in the v1.3.0

**Comment by PushpalathaT** [comment]
Thanks .I will try and update the result

**Comment by PushpalathaT** [comment]
Thanks I could update and Harbor UI version show (Version v1.6.3-1d50f9f2).

1.But ldap is not working after upgrade. Can you please suggest what changes are required in configuration with respect to upgraded harbor version.

In v1.3.0-rc4 with below ldap configuration I was able to login successfully. But after upgrade I am not able to .
auth_mode = ldap_auth
ldap_url = ldap://xxx.aaa.bbb.com:3268
ldap_searchdn = CN=sss,OU=Service Accounts,dc=aaa,dc=bbb,dc=com
ldap_search_pwd = xxxxx
ldap_basedn = DC=bbb,DC=com
#ldap_filter = (objectClass=person)
ldap_uid = sAMAccountName
ldap_scope = 2

In latest harbor.cfg there are few new ldap setting. Is this mandatory or can be commented?
ldap_verify_cert = true
ldap_group_basedn = ou=group,dc=mydomain,dc=com
ldap_group_filter = objectclass=group
ldap_group_gid = cn
ldap_group_scope = 2

2.If I want to upgrade from v1.3.0-rc4 to v1.7.0-rc1 under goharbor/harbor-migrator/tags/  I can’t see v1.7.0-rc1.
So I have to use v1.6.3  migrator and instead of v1.6.3 offline installer need to use v1.7.0-rc1 offline installer ?

Thanks in Advance
