### ISSUE TITLE
Helm repository proxy

### ISSUE THREAD

**Issue by mumrau** [goharbor/harbor#6526]
**Is your feature request related to a problem? Please describe.**
I would like to manage in my company helm charts as we proceed with everything else that looks like or is an artifact. In that sense, we would like to have the possibility of configuring a proxy repository for helm/stable.

**Describe the solution you'd like**
I would like the possibility to configure helm repository mirror/proxy solution in harbor.

**Describe the main design/architecture of your solution**
To be determined. Depends on chartmuseum I believe. I know the sonatype helm "solution" (which is extremely unstable) has this kind of behavior.

**Describe the development plan you've considered**
I don't have any idea yet, as I'm just approaching harbor since a few days. I suspect the implementation isn't that hard but might be tricky. Somebody else can probably answer this part better.

**Additional context**
Empty.

**Comment by steven-zou** [comment]
@mumrau 

  Thanks for reaching us and sharing your scenario. So far, Harbor can not support mirror/proxy to upstream chart repos, but we're doing some work to improve the replication service to support covering helm charts. In future, maybe you can create replication rule to let harbor automatically pull images from the specified upstream chart repos you specified. Please stay tuned.

**Comment by mumrau** [comment]
I will.
We're switching to harbor in our staging and dev environments already, so we'll be pretty much tuned to the updates.

**Comment by steven-zou** [comment]
@ninjadq 

  You can take care of this issue. We can consider if we can leverage the replication to support chart repo mirror in the future release.

**Comment by tookko** [comment]
Any update on the future release to support this?

**Comment by xaleeks** [comment]
@mumrau  I would encourage you to share your usage and track progress here https://github.com/goharbor/harbor/issues/8082 and I'd like to close this one so we consolidate all the requirements down to a single place.  Harbor 2.0 supports OCI fully which means helm charts can now reside in the docker registry alongside container images as opposed to hosting them separately in chartmuseum.  This means we will probably deprecate chartmuseum at some point in the future and so any proxy cache mechanism for helm charts should be explored as part of a larger story to support all OCI artifacts, hence the ticket I linked.
