### ISSUE TITLE
 ReverseProxy read error during body copy: unexpected EOF

### ISSUE THREAD

**Issue by xuejipeng** [goharbor/harbor#6527]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
dockr pull some image  end with 'received unexpected HTTP status: 500 Internal Server Error'
only part of the mirror has this problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.5.2]
- docker engine version: [17.03]
- docker-compose version: [1.23.2]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
ui.log
![image](https://user-images.githubusercontent.com/18901031/49933482-b4065280-ff06-11e8-8d83-feb31d47e03a.png)
pull log 
![image](https://user-images.githubusercontent.com/18901031/49933514-c8e2e600-ff06-11e8-89db-ec8dee695be7.png)

**Comment by ywk253100** [comment]
Provide the logs of registry and check if any errors in it.

**Comment by reasonerjt** [comment]
@xuejipeng looks like an env issue, I'm closing it due to inactivity, please re-open if you are seeing this after upgrading.

**Comment by cyberwave** [comment]
I got the same problem, the log output below:"
httputil: ReverseProxy read error during body copy: unexpected EOF


2019/09/17 17:12:53 [Recovery] 2019/09/17 - 17:12:53 panic recovered:
POST /v2/web/image/upload HTTP/1.1
Host: baas-network.jd.com
Connection: close
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close
Content-Length: 51047
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXadrBpwB2HD6UTRn
...
"
anyone have idea about it?
