### ISSUE TITLE
where I can get goharbor/harbor-db-migrator:1.6.3 as per release-1.6.0/docs/migration_guide.md

### ISSUE THREAD

**Issue by moooofly** [goharbor/harbor#6528]
by https://github.com/goharbor/harbor/blob/release-1.6.0/docs/migration_guide.md 

> Please use `goharbor/harbor-db-migrator:1.6.3` instead if you're performing migration...

But Can not find tag 1.6.3 from either https://hub.docker.com/r/vmware/harbor-db-migrator/tags/ or https://hub.docker.com/r/goharbor/harbor-db-migrator/tags/

So where can I find it? thanks.

**Comment by moooofly** [comment]
get it from https://hub.docker.com/r/goharbor/harbor-migrator/tags/ , the docs of harbor really need to be updated.

**Comment by moooofly** [comment]
> below is my own conclusions for your reference

## the changing history on Docker Hub

- https://hub.docker.com/r/vmware/harbor-db-migrator/tags/ -- almost deprecated, but can work well in some cases, not suggest to use. It is a hub keeping migrator tools before harbor entering into CNCF. Tags involved:
    - 0.4.5
    - 1.2
    - 1.3
    - 1.4
- https://hub.docker.com/r/goharbor/harbor-db-migrator/tags/ -- This hub is used to keep migrator tools after harbor entering into CNCF, as you can see, the contents are almost the same as above. So it is just a copy. Tags involved:
    - 1.2
    - 1.3
    - 1.4
- https://hub.docker.com/r/goharbor/harbor-migrator/tags/ -- This hub keeps the most recently migrator tools.  Tags involved:
    - v1.5.0
    - v1.6.0
    - v1.6.1
    - v1.6.3

**Comment by wy65701436** [comment]
thanks @moooofly, please use the goharbor/harbor-migrator:v1.6.3 in hub.docker.com, 

here is the PR to fix the document. 

https://github.com/goharbor/harbor/pull/6529

**Comment by moooofly** [comment]
FYI, doc https://github.com/goharbor/harbor/blob/release-1.5.0/docs/migration_guide.md has the same issue as above. @wy65701436

**Comment by moooofly** [comment]
one more question: Is my conclusion of https://hub.docker.com/r/vmware/harbor-db-migrator hub right? Should I avoid using this one (use https://hub.docker.com/r/goharbor/harbor-db-migrator/ instead)?

**Comment by wy65701436** [comment]
the migration guide on v.1.5.0 should not be impacted as the v1.6.3 was introduced from v1.6.0.
