### ISSUE TITLE
SMTP configuration

### ISSUE THREAD

**Issue by bdshibly** [goharbor/harbor#6533]
Hi, 

I am trying to integrate an internal MS Exchange server with Harbor. But I am not getting any email from Harbor even not getting any logs. I tried to packet snip too and also not getting anything related to SMTP. Here are the configuration of harbor.cfg

```
email_identity =

email_server = qasmtp1.internal.com
email_server_port = 25
email_username =
email_password =
email_from = devops <devops@internaldomain.com>
email_ssl = false
email_insecure = false
```

Here is the output of telnet

```
telnet qasmtp1.internal.com 25
Trying 10.10.1.136...
Connected to qasmtp1.internal.com.
Escape character is '^]'.
220 ********************************************************************************************************************
ehlo localhost
250-qasmtp1.internal.com Hello [10.14.138.140]
250-XXXA
250-SIZE 20971520
250-ETRN
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-8bitmime
250-BINARYMIME
250-XXXXXXXB
250-VRFY
250 XC
```

```
tcpdump -nn -x -X port 25
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on docker0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel

```

I like to mention that harbor.cfg changes don't reflect on Harbor UI. Could you help me to resolve this issu? 

Ferdous Shibly

**Comment by ywk253100** [comment]
The email server settings can be configured on web portal if you login as system admin. 
The server is used to reset the user's password if he forgetting it, provide all logs when you trying to reset the password.

**Comment by bdshibly** [comment]
Is Harbor not going to send an email to the project owners with the report after scanning a docker image? Is SMTP integration only for retrieving password?

**Comment by ywk253100** [comment]
It is only used to reset the password.

**Comment by abdennour** [comment]
same issue.. when use the insecure port and without password, it does not work : 
![image](https://user-images.githubusercontent.com/1788384/122629670-6ebecf00-d0c7-11eb-9d2a-2ceaf476419a.png)

**Comment by jmlms** [comment]
Also in need of this feature
