### ISSUE TITLE
Webhook for integrating with CI/CD tools

### ISSUE THREAD

**Issue by bdshibly** [goharbor/harbor#6538]
I am trying to integrate Harbor with CI/CD tools like Jenkins. I could properly push docker images to Harbor but it would be great if I could get the following quires from Harbor in Jenkins.

- Whether the image has been pushed to Harbor properly or not.
- Whether clair has been started scanning Harbor or not.
- What is the result of scan?

We require a Webhook in Harbor which we can integrate with Jenkins.

**Comment by steven-zou** [comment]
@bdshibly 

  Thanks for reaching us and raising the requirement to us.  Actually, some community contributors are considering to implement such a feature. If there are any changes, will update to you. Additionally, if you're willing to do contributions to this feature, that will be definitely welcomed!

**Comment by nlowe** [comment]
Yeah there's a few open issues requesting this. The furthest along issue that I see is #6676, although a formal proposal is still pending. @bdshibly Please take a quick look at #6676 and leave a comment if you think there are features / use cases missing from that issue.
