### ISSUE TITLE
LDAP issue after upgrade

### ISSUE THREAD

**Issue by PushpalathaT** [goharbor/harbor#6539]
I could update from v1.3.0-rc4 to v1.6.3 and Harbor UI version show (Version v1.6.3-1d50f9f2).

1.But ldap is not working after upgrade can see below error in log. Can you please suggest what changes are required in configuration with respect to upgraded harbor version.

1.1
In v1.3.0-rc4 with below ldap configuration I was able to login successfully. But after upgrade I am not able to login.
auth_mode = ldap_auth
ldap_url = ldap://xxx.aaa.bbb.com:3268
ldap_searchdn = CN=sss,OU=Service Accounts,dc=aaa,dc=bbb,dc=com
ldap_search_pwd = xxxxx
ldap_basedn = DC=bbb,DC=com
#ldap_filter = (objectClass=person)
ldap_uid = sAMAccountName
ldap_scope = 2

In latest(upgraded) harbor.cfg there are few new ldap setting as mentioned below. 
ldap_verify_cert = true
ldap_group_basedn = ou=group,dc=mydomain,dc=com
ldap_group_filter = objectclass=group
ldap_group_gid = cn
ldap_group_scope = 2

Fails to connect and see below in logs.
Dec 17 00:45:46 172.25.0.1 ui[5673]: 2018-12-17T05:45:46Z [ERROR] [base.go:94]: LDAP connect fail, error: LDAP Result Code 200 "": dial tcp: i/o timeout

1.2 if i comment ldap group details install.sh fails 

1.3 If i modify as below also it fails to connect using LDAP.
ldap_verify_cert = true
ldap_group_basedn = ou=group,dc=aaa,dc=com
ldap_group_filter = objectclass=group
ldap_group_gid = cn
ldap_group_scope = 2

1.3 Tried testing Ldap connection from Harbor UI->Configuration getting "Failed to verify LDAP server with error: ."

2.If I want to upgrade from v1.3.0-rc4 to v1.7.0-rc1 under goharbor/harbor-migrator/tags/ I can’t see v1.7.0-rc1.
So I have to use v1.6.3 migrator and instead of v1.6.3 offline installer need to use v1.7.0-rc1 offline installer ?

Thanks in Advance

**Comment by stonezdj** [comment]
What is your LDAP server type? AD or openLDAP. 
Can you please upload more logs?

The v1.7.0 will be released soon

**Comment by PushpalathaT** [comment]
Thanks of the update.

LDAP server type is AD.  ui.log output as below

Dec 17 04:04:27 172.26.0.1 ui[5673]: 2018/12/17 09:04:27 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.117027ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Dec 17 04:04:28 172.26.0.1 ui[5673]: 2018/12/17 09:04:28 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    989.676Âµs|   match|#033[44m GET     #033[0m /     r:/#033[0m
Dec 17 04:04:58 172.26.0.1 ui[5673]: 2018/12/17 09:04:58 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   4.245605ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Dec 17 04:04:59 172.26.0.1 ui[5673]: 2018/12/17 09:04:59 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    990.014Âµs|   match|#033[44m GET     #033[0m /     r:/#033[0m
Dec 17 04:05:28 172.26.0.1 ui[5673]: 2018/12/17 09:05:28 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.344958ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Dec 17 04:05:29 172.26.0.1 ui[5673]: 2018/12/17 09:05:29 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.004068ms|   match|#033[44m GET     #033[0m /     r:/#033[0m
Dec 17 04:05:38 172.26.0.1 ui[5673]: 2018-12-17T09:05:38Z [WARNING] ldap connection fail: LDAP Result Code 200 "": dial tcp: lookup xxx.aaa.bbb.com: Temporary failure in name resolution
Dec 17 04:05:38 172.26.0.1 ui[5673]: 2018-12-17T09:05:38Z [ERROR] [base.go:65]: Error occurred in UserLogin: LDAP Result Code 200 "": dial tcp: lookup xxx.aaa.bbb.com: Temporary failure in name resolution
Dec 17 04:05:58 172.26.0.1 ui[5673]: 2018/12/17 09:05:58 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   5.304943ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m

Thanks
