### ISSUE TITLE
Wrong url in developer center page after operation

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#6545]
when entering the developer center page the URL is 
![image](https://user-images.githubusercontent.com/1069785/50132257-30ab7f00-02c1-11e9-8597-e895b2e19551.png)

But after an operation, for example, click an API item, the prefix of `devcenter` disappeared.
![image](https://user-images.githubusercontent.com/1069785/50132346-a31c5f00-02c1-11e9-8128-c5c59ce32400.png)

**Comment by zhoumeina** [comment]
currently, we don't have proper way to handle this. Because this is auto integrated by swagger ui. This library does not provide way to deal with this issue.
