### ISSUE TITLE
How can I set automatic pruning for old images 

### ISSUE THREAD

**Issue by anargund1979** [goharbor/harbor#6549]
How can we prune old images automatically.
Lets say I have 20 images and I want to keep latest 10.

thanks ...

**Comment by zhoumeina** [comment]
I think currently we don't have this feature, however, you can delete the image you don't need and run gc manually .

**Comment by lwqcz** [comment]
@zhoumeina - can you consider to support some mechanism to support rules for deleting images automatically. Even the support as some API kind ...
