### ISSUE TITLE
Stabilize the nightly testing cases

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6563]
Currently, the cases of our nightly testing are fragile, this is caused by:
1. The misuse of `Sleep` instruction. Use `Wait Until...` instead 
2. The failure of DNS resolve for docker hub when pulling images. May be we can pull the images from an internal registry?

As the task may be very huge, we need to open more issues and add them into this epic to track the progress.

**Comment by danfengliu** [comment]
It's done already.
