### ISSUE TITLE
[Issue][Encryption] Cloning Database from one env to another causing some trouble with LDAP encrypted password

### ISSUE THREAD

**Issue by rfjg** [goharbor/harbor#6570]
Hello,
I am using the Harbor latest release v1.7.0.
I have 2 differents configured environments, one for production and one for preprod.

During the initial setup, I configured 2 differents secretKey, root.crt and privatekey.pem.
Both env are configured to connect with LDAP.
Each morning, my harbor production database is cloned to the harbor preprod database.

The issue is that on preprod, i need to connect as admin each morning after the database is cloned on preprod to edit the LDAP Search Password on UI to make LDAP connection working again.

I even tried to put on preprod configuration same root.crt, privatekey.pem and secretKey than production, but even this way, it doesn't work and LDAP doesn't work until i connect as admin to edit the LDAP Search Pasword on UI.

My question is the following: 
Is it possible to let the preprod postgres database accept the encrypted password from production database ?

Thank you.

**Comment by stonezdj** [comment]
Try to copy /data/secretkey from product to preprod?

**Comment by rfjg** [comment]
The problem is solved.
We just put the same secretKey on config and waited for the next cloning between production and preprod, and then it worked well.

It didn't work before because we've made this change manually on the database.
