### ISSUE TITLE
Garbage collector may not working properly.

### ISSUE THREAD

**Issue by shinebayar-g** [goharbor/harbor#6571]
**Expected behavior and actual behavior:**
I've been waiting 1.7.0 version's online garbage collector function cuz I was running out of space.
Today I've updated my goharbor installation and run the garbage collector function. But it didn't clear out any space. Basically no difference. my /data/registry folder still has tons of GBs data.

**Steps to reproduce the problem:**
Update 1.6.1 -> 1.7.0
Run garbage collector from web interface.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.0]
- docker engine version: [17.03.2-ce]
- docker-compose version: [1.22.0]

**Comment by wy65701436** [comment]
Did you see the log of GC? Did you delete any of repository?

**Comment by shinebayar-g** [comment]
Hi, no I didn't do anything. I just moved current harbor installation folder to somewhere and downloaded and extracted 1.7.0 version and setup harbor.cfg and started everything as normally. How can I check those logs?

**Comment by wy65701436** [comment]
In the history table, there is an button named details, you can view the Gc log by clicking it.

And GC could only free space for the deleted repository.

**Comment by shinebayar-g** [comment]
Ah logs:

```
2018-12-19T14:50:34Z [INFO] the readonly request has been sent successfully
2018-12-19T14:50:34Z [INFO] start to run gc in job.
2018-12-19T14:51:39Z [INFO] GC results: status: true, message: admin/cm
admin/cm: marking manifest sha256:8116879fa779f563de6ea4d787c6f73e936aa4e53a8621dcbd54c16316b84bdf 
admin/cm: marking blob sha256:71c60e015b9051eabe0ed2ba16174bf8f7e85c66e629f8fe58faef8e7797b48a
...
tons of this, looks like all of my images are getting marked as expected.
...
4310 blobs marked, 672 blobs eligible for deletion
blob eligible for deletion: sha256:9ff4b347990de0a1df2a791a49f552ad31f03bdf2ab8bda3ee9889939a86a473
time="2018-12-19T14:51:35.910890252Z" level=info msg="Deleting blob: /docker/registry/v2/blobs/sha256/9f/9ff4b347990de0a1df2a791a49f552ad31f03bdf2ab8bda3ee9889939a86a473" go.version=go1.7.3 instance.id=2358b77f-32a1-4193-b1f4-45bcd3e0c2d3 service=registry 
blob eligible for deletion: sha256:b1bc7797efdd01f08a14c9a984d344e0d8ced7c488a22ff3ba893cca76054f51
time="2018-12-19T14:51:35.933732974Z" level=info msg="Deleting blob: /docker/registry/v2/blobs/sha256/b1/b1bc7797efdd01f08a14c9a984d344e0d8ced7c488a22ff3ba893cca76054f51" go.version=go1.7.3 instance.id=2358b77f-32a1-4193-b1f4-45bcd3e0c2d3 service=registry 
...
, start: 2018-12-19 14:50:34.170767959 +0000 UTC, end: 2018-12-19 14:51:38.819635587 +0000 UTC.
2018-12-19T14:51:39Z [INFO] success to run gc in job.
2018-12-19T14:51:39Z [INFO] the readonly request has been sent successfully
```

>GC could only free space for the deleted repository.

What does that mean? I've  30 repositories and 30 images total of 2GB only. But registry garbage date uses 66GB. What should I do?

**Comment by wy65701436** [comment]
From the log, nothing wrong on GC. There were 672 blobs deleted from registry.

If you want to know details of GC and how it works, please refer to the docker official document.

**Comment by shinebayar-g** [comment]
I see, so in order to host 2GB of image, I have to spend 60GB+ space?
