### ISSUE TITLE
Get internal server error when getting the count of chart if create a project named "api"

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6596]
Related issue: https://github.com/goharbor/harbor-helm/issues/128

**Comment by steven-zou** [comment]
Let's fix it in 1.7.1

**Comment by steven-zou** [comment]
Linked to the issue of upstream project https://github.com/helm/chartmuseum/issues/201

**Comment by steven-zou** [comment]
Let's wait for the fix from chartmeseum team.

**Comment by steven-zou** [comment]
No solution from chartmuseum side, let's move this issue out of the SP.

**Comment by petvaa01** [comment]
All project names prefixed with "api" are affected with this.

**Comment by steven-zou** [comment]
@ninjadq 

Reassign this issue to you

**Comment by reasonerjt** [comment]
@steven-zou @ninjadq 
I tried it and it seems pretty severe, that any project prefixed by `api` will break the functionality, we should consider fix this earlier.

**Comment by anairinac** [comment]
This issue is still affecting projects being created with version 1.8. It would be at least useful to forbid names with "api-" prefix, to avoid any problems.
