### ISSUE TITLE
Cannot save LDAP settings

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#6597]
Cannot save LDAP settings if `LDAP Scope` is `Base`.
Steps to reproduce:
1. Change `Auth Mode` to `LDAP`, set `LDAP Scope` with `Base` and fill other necessary properties, save it. The setttings can be saved.
2. Keep the `LDAP Scope` as `Base` and change any other properties, try to save it, got error `ldap_scope is missing`. 

This may be caused by that the value of `Base` is `0`.

**Comment by stonezdj** [comment]
config.go
```
		if ldapConf.LdapScope == 0 {
			if _, ok := numMap[common.LDAPScope]; !ok {
				return false, fmt.Errorf("%s is missing", common.LDAPScope)
			}
		}
```
Check is incorrect

**Comment by stonezdj** [comment]
It is already fixed after admin server refactor
