### ISSUE TITLE
clair error

### ISSUE THREAD

**Issue by timchenxiaoyu** [goharbor/harbor#6600]
harbor 1.5.2

(1).image had push to habor one week and scan every day
[ERROR] [base.go:88]: Failed to get scan details from Clair, error: Unexpected status code: 404, text: {"Error":{"Message":"the resource cannot be found"}}
![image](https://user-images.githubusercontent.com/9782796/50349078-a50e4880-0575-11e9-8287-3393b853d52c.png)

(2)no scan status
![image](https://user-images.githubusercontent.com/9782796/50349175-ea327a80-0575-11e9-8cc4-12bd0074fe8b.png)

**Comment by steven-zou** [comment]
@timchenxiaoyu 

Clair is installed with --with-clair flag in your installation?

**Comment by timchenxiaoyu** [comment]
sure， some of scan  error，not all image error

**Comment by steven-zou** [comment]
@zhoumeina 

From the error, it seems a UI error. Reading property from null value. Please check it first.

**Comment by zhoumeina** [comment]
@pureshine , could you please take a look?

**Comment by pureshine** [comment]
@timchenxiaoyu Is there still a problem with upgrading to the latest harbor?

**Comment by jwangyangls** [comment]
@timchenxiaoyu I recommend that you upgrade harbor and use the new version because it's very old.
