### ISSUE TITLE
Can't find garbage collector

### ISSUE THREAD

**Issue by mdasgit** [goharbor/harbor#6602]
What can we help you?
Just deployed harbor, everything is fine, except the GC feature. Can't find it in the ui. Not sure how to run it from CLI if this is possible. Please provide a link to any documentation that can help on this.

**Comment by steven-zou** [comment]
@mdasgit 

Please confirm which version you installed first.

Next, upload a screenshot of `Administration`->`Configurations`. We need those materials to locate where the problem is.

**Comment by mdasgit** [comment]
HI Steven, 
the version is 1.6.2 
![image](https://user-images.githubusercontent.com/46070532/50399658-06692e00-07a7-11e9-8fdf-3e64149e3898.png)

**Comment by wy65701436** [comment]
@mdasgit this feature is introduced from v1.7.0, please upgrade to this version and refer the guide https://github.com/goharbor/harbor/blob/release-1.7.0/docs/user_guide.md#online-garbage-collection

**Comment by mdasgit** [comment]
Thank you @wy65701436
