### ISSUE TITLE
Download link REGISTRY CERTIFICATE in UI (api/systeminfo/getcert) return - No certificate found.

### ISSUE THREAD

**Issue by rlagutinhub** [goharbor/harbor#6603]
What can we help you?
Download link REGISTRY CERTIFICATE in UI (api/systeminfo/getcert) return - **No certificate found.**

my env
harbor 1.7.0 offline installer (--with-chartmuseum)

i created certs and configured harbor as in https://github.com/goharbor/harbor/blob/master/docs/configure_https.md

![image](https://user-images.githubusercontent.com/30324030/50381525-6f16b480-069a-11e9-92dd-d33bdf76d800.png)
![image](https://user-images.githubusercontent.com/30324030/50381537-9cfbf900-069a-11e9-8bdd-3fa0ab198b8e.png)
![image](https://user-images.githubusercontent.com/30324030/50381530-89509280-069a-11e9-9aa5-beceb8984e2e.png)
![image](https://user-images.githubusercontent.com/30324030/50381545-c3219900-069a-11e9-8bc8-b8010c3558cb.png)

**Comment by steven-zou** [comment]
@rlagutinhub 

Please try to `cp` the ca file to /data/ca_download folder to fix the problem.

**Comment by rlagutinhub** [comment]
Thanks, it works

#### pls, add to https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#download-the-harbor-certs

```
ll /data/cert/; ll /data/ca_download/
ln -s /data/cert/harbor.crt /data/ca_download/ca.crt
ll /data/ca_download/
```
---

![image](https://user-images.githubusercontent.com/30324030/50404989-5d7afd00-07bf-11e9-9b06-d50e699404b7.png)
![image](https://user-images.githubusercontent.com/30324030/50404991-64a20b00-07bf-11e9-83ed-a1c68d810db2.png)
![image](https://user-images.githubusercontent.com/30324030/50404995-6f5ca000-07bf-11e9-9151-c59bfb88e5e3.png)
