### ISSUE TITLE
Group members are not able to see the Projects

### ISSUE THREAD

**Issue by mdasgit** [goharbor/harbor#6608]
We have given project admin permission to the AD groups on PROJECTS in harbor, however whenever any group member logs in to harbor, he/she is unable to see the assigned projects. Is this a known issue or are we missing something ? Please advise.

Version - 1.7.0

**Comment by zhoumeina** [comment]
@mdasgit , I tested this case with 1.7 kit. It is working. Please check the role in the project. If admin assign the role to a user, the user should can see the project.

**Comment by mdasgit** [comment]
Hi Mia, let me explain this more accurately. The groups are LDAP based. I don't want to create separate groups in Harbor. Say we provided a group 'A' (AD group) project admin role. Now who ever is under that group is not able to see the assigned projects.  But this works when we are assigning project roles individually to an user, but doesn't work when the AD user is under group A. Hope this helps. Does this have anything to do with UPPERCASE letters in group DN's ?

**Comment by stonezdj** [comment]
Please verify the LDAP users memberof attribute points to the LDAP group's DN

**Comment by mdasgit** [comment]
Yes it does. The AD users are able to login to harbor. LDAP works fine. Let me assure you, we have verified everything related LDAP from our end. Please let me know if you need any other information.

**Comment by stonezdj** [comment]
Please confirm two questions?
1. Is this AD DN is case sensitive
2.Is the ldap group membership is indicated by attribute "memberof" or "ismemberof"
