### ISSUE TITLE
Support Harbor in Rancher Catalog

### ISSUE THREAD

**Issue by loganhz** [goharbor/harbor#6617]
As a Rancher user, I would like to deploy Harbor as a catalog application in Rancher 2.0

Now we can add `https://github.com/goharbor/harbor-helm` into Rancher.
We can deploy Harbor in Rancher with one click.

![image](https://user-images.githubusercontent.com/21168270/50414579-60263280-0851-11e9-8527-1ccdab86f76e.png)
![image](https://user-images.githubusercontent.com/21168270/50414584-6e744e80-0851-11e9-9bab-2451e7f5595f.png)
![image](https://user-images.githubusercontent.com/21168270/50414625-9bc0fc80-0851-11e9-9bef-c566886008ee.png)
![image](https://user-images.githubusercontent.com/21168270/50414598-7af8a700-0851-11e9-9cc7-d175f18246de.png)
![image](https://user-images.githubusercontent.com/21168270/50414608-88ae2c80-0851-11e9-82db-e606849d3b19.png)

What we need to do to make it better is following:

1. Submit a PR to https://github.com/rancher/charts to add Harbor as the default applications in Rancher. 

2. Add `question.yaml` file which is an enhancement from Rancher. It will help Rancher to generate dynamic UI inputs to make the user experience better. So users can just input and select fields instead of config it in YAML.

Here is an example for questions.yaml https://github.com/rancher/charts/blob/master/charts/wordpress/v1.0.5/questions.yml

There is more information you can find via https://rancher.com/docs/rancher/v2.x/en/catalog/custom/

![image](https://user-images.githubusercontent.com/21168270/50414749-3b7e8a80-0852-11e9-946f-204406bf24f2.png)

**Comment by reasonerjt** [comment]
Please feel free to open PR to rancher.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/17227

**Comment by steven-zou** [comment]
@ywk253100 / @loganhz 

Let's work out what configuration options can be put into the questionable list first. Then sync the followup actions.

**Comment by loganhz** [comment]
We are not going to add `question.yml` file in https://github.com/goharbor/harbor-helm

**Comment by reasonerjt** [comment]
Based on the discussion seems there's no code change required in this repo.

@loganhz Do you think we need to keep this issue open?

**Comment by loganhz** [comment]
Could you provide the list of important fields which we can add into Rancher question.yml file, please?

**Comment by ywk253100** [comment]
If Harbor chart is deployed in the K8S cluster which enables ingress controller and dynamic volume provision already, the only values that users need to configure are as follows:
`expose.ingress.hosts.core`, `expose.ingress.hosts.notary` and `externalURL`.

**Comment by loganhz** [comment]
thanks. We will work it on Rancher
