### ISSUE TITLE
cherry pick retag feature backend returns error as html to 1.7.0 branch

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#6629]
What can we help you?

**Comment by zhoumeina** [comment]
done

**Comment by reasonerjt** [comment]
Re-opening as the PR to fix the issue:
https://github.com/goharbor/harbor/pull/6547
has just merged to `master` and the commit is not cherry picked to `1.7` branch

**Comment by wy65701436** [comment]
close it as v1.7.1 released.
