### ISSUE TITLE
why the harbor automatic restart?

### ISSUE THREAD

**Issue by Jaywoods2** [goharbor/harbor#6631]
I installed the harbor with harbor-helm (https://github.com/goharbor/harbor-helm/tree/0.3.0),
but recently, I find it always restarts automatically. why?
 
![image](https://user-images.githubusercontent.com/18679696/50429711-09753300-08fb-11e9-8f94-c94d3a6b2a0c.png)

**Comment by reasonerjt** [comment]
Does it always happen to the same pod?  It's possible something's wrong with your k8s cluster.

**Comment by Jaywoods2** [comment]
We are use tencent cloud CFS storage,could the slow speed of network transmission cause the container to restart?

**Comment by ywk253100** [comment]
It's related with your docker daemon
