### ISSUE TITLE
New master role to project

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#6636]
See more https://github.com/goharbor/community/pull/32

**Comment by ericvmw** [comment]
I noticed in the current version (https://github.com/goharbor/community/pull/32), the master role has the following permissions, which means the master role will be able to add new user to the project, but cannot change or delete:
                                                                    project admin                master role
New Project Member                   | :heavy_check_mark: | :heavy_check_mark: |                    |  |
Edit Project Member                     | :heavy_check_mark: |  |  |
Delete Project Member                | :heavy_check_mark: |  |  |
I think that is confusing, and it would be better not to allow master role to have any modification permissions to project members.
