### ISSUE TITLE
Healthcheck in harbor-log

### ISSUE THREAD

**Issue by overdogwatch** [goharbor/harbor#6643]
Hello,
In harbor v1.7.0, health check of harbor-log container is: 
HEALTHCHECK CMD netstat -ltu|grep 10514
I guess that the purpose of this check is to verify that the container is listening on port 10514. Healthcheck default timeout is 30 sec. In places where the DNS resolver is not working properly, this check could take more than 30 sec, which leads to decide that the container health is unhealthy. I advise you to add to your check the option n, which prevents netstat trying to determine the symbolic host. 

HEALTHCHECK CMD netstat -ltun|grep 10514

**Comment by reasonerjt** [comment]
Thanks @overdogwatch for pointing it out, would you open a PR to refine this?

**Comment by overdogwatch** [comment]
> Thanks @overdogwatch for pointing it out, would you open a PR to refine this?

yep 
https://github.com/goharbor/harbor/pull/6647

**Comment by ywk253100** [comment]
PR merged.
