### ISSUE TITLE
Confirm scan complete from the API

### ISSUE THREAD

**Issue by rlegrand** [goharbor/harbor#6648]
Hello,

I need a way to check from the API if an image contains vulnerabilities.
I have checked with:
` /repositories/{repo_name}/tags/{tag}/vulnerability/details`
But it doesn't allow to distinguish a scan without CVE from no scan at all ( in both cases, the answer seems to be an empty array ).

Moreover, the process I'm trying to implement is something like:
* If the image doesn't contain vulnerabilities, do something.

Even if you choose to send a specific status for unscanned images from the call to ` /repositories/{repo_name}/tags/{tag}/vulnerability/details` , it's not easy to implement the previous process.

I could probably try something like:
```
scan(image)
while(image not scanned) 
    wait_some_time (how much? what is the max delay to wait for a scan when the job is created)
do_something()
```
But I would prefer a lot a blocking call to scan(image) which answers with details when the scan is done, so I can:
`scan(image) && do_something()`

Is it possible to implement that ?
I found a way to do that by myself, either by checking the clair db, either by using https://github.com/jgsqware/clairctl , but we would prefer a lot this feature to be available from the API (seems more clean).

Thanks and Regards.

**Comment by mathislgs** [comment]
Any news on that ? I would need such a feature too, for the same scenario.

**Comment by Filirom1** [comment]
Hello,

I am in the same situation. I need to know if the scan is completed without CVE or is not yet finished.

Do you find a viable solution?

**Comment by reasonerjt** [comment]
You can call the API to check the scan status of a tag:
```
#curl -u "admin:Harbor12345" https://10.192.58.8/api/repositories/library/redis/tags/5.0 -k
{
  "digest": "sha256:478392fbb4f132b36b8ead3435087553ee7e6f0395b3d64987ae195268d13493",
  "name": "5.0",
  "size": 35229504,
  "architecture": "amd64",
  "os": "linux",
  "docker_version": "18.06.1-ce",
  "author": "",
  "created": "2019-03-27T00:49:00.123917534Z",
  "config": {
    "labels": null
  },
  "signature": null,
  "scan_overview": {
    "image_digest": "sha256:478392fbb4f132b36b8ead3435087553ee7e6f0395b3d64987ae195268d13493",
    "scan_status": "finished",                             <--------HERE
    "job_id": 1,
    "severity": 5,
    "components": {
      "total": 51,
      "summary": [
        {
          "severity": 5,
          "count": 4
        },
        {
          "severity": 4,
          "count": 1
        },
        {
          "severity": 3,
          "count": 3
        },
        {
          "severity": 1,
          "count": 43
        }
      ]
    },
    "details_key": "51ac3607963c65b67213fe866bc45dcfeec91fa4cf0130778ab073b45b430d48",
    "creation_time": "2019-04-29T05:50:32Z",
    "update_time": "2019-04-29T05:50:34Z"
  },
  "labels": []
}
```
