### ISSUE TITLE
MD5 does not match on harbor-offline-installer-v1.7.0.tgz

### ISSUE THREAD

**Issue by jwalkins2017** [goharbor/harbor#6649]
What can we help you?
I have downloaded https://storage.googleapis.com/harbor-releases/release-1.7.0/harbor-offline-installer-v1.7.0.tgz and the md5sum is:
b9abd3fb7007ce1deee81d8e7ad6fa67

Which is the same for https://storage.googleapis.com/harbor-releases/release-1.7.0/harbor-offline-installer-v1.7.0-rc2.tgz

Should the md5sum for the https://storage.googleapis.com/harbor-releases/release-1.7.0/harbor-offline-installer-v1.7.0.tgz be b9abd3fb7007ce1deee81d8e7ad6fa67 or 38f1272f471d90a98c0a8c7a288fcd2e (from: https://github.com/goharbor/harbor/releases/tag/v1.7.0)?

**Comment by BalaBalaYi** [comment]
+1.   https://storage.googleapis.com/harbor-releases/release-1.7.0/harbor-offline-installer-v1.7.0.tgz 's md5 is：b9abd3fb7007ce1deee81d8e7ad6fa67
