### ISSUE TITLE
Tag Retention: Boilerplate

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6655]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Create the initial types and interfaces for the [Tag Retention Policies](https://github.com/goharbor/community/blob/master/proposals/5882-Tag-Retention-Policies.md) feature.

**Comment by nlowe** [comment]
@steven-zou cross-posting here since I didn't have any luck asking in slack

In looking over the source, is there a reason the types returned by the API are not exported? I'd like to have the tag retention filters have access to all of the data you can get from the API (Specifically, I'm looking at the `tagResp` struct in `core/api/repository.go`. Should I make this struct public? Is there another way to access this data?

**Comment by nlowe** [comment]
This is stuck until the merge window for 1.9 opens. I'm going to continue with the assumption that the boilerplate is mostly good and start prepping some of the other issues for the merge window. If things need chang d I'll address it then.

**Comment by nlowe** [comment]
@steven-zou With the updated boilerplate in `feature/tag_retention` I'm good to count this as done if you are.

**Comment by steven-zou** [comment]
@nlowe 

Yes, right. As all code merged into the [feature branch](https://github.com/goharbor/harbor/tree/feature/tag_retention), we can mark it done!
