### ISSUE TITLE
Tag Retention: Filter Group Builder implementation

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6656]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Implement the Filter Chain Builder outlined in the proposal.

Given a set of filters and their configuration, construct a filter chain to process tags on a project.

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by nlowe** [comment]
Initial iteration available in https://github.com/nlowe/harbor/tree/feat/retention/GH-6656-filter-chain-builder. I'll open a PR when the merge window for 1.9 opens.

**Comment by steven-zou** [comment]
Mapping the work of builder and processor

**Comment by steven-zou** [comment]
Rule builder and processor are supported in the[ feature branch](https://github.com/goharbor/harbor/tree/feature/tag_retention), mark this issue done!
