### ISSUE TITLE
Tag Retention: Filter Implementation: Retain the most recently pulled # images

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6659]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Implement the `Retain the most recently pulled # images` filter

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by nlowe** [comment]
This is the only filter I'm not sure of. I don't think harbor has this data, we might have to check the backing distribution registry to see if we can get information like that.

**Comment by alexvmw** [comment]
What does downloaded mean here?

**Comment by nlowe** [comment]
A `docker pull` on the tag was what I had in mind.
