### ISSUE TITLE
Tag Retention: Filter Implementation: Retain tags no older than n days

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6661]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Implement the "Delete tags older than `n` days" filter

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by nlowe** [comment]
Initial iteration available in https://github.com/nlowe/harbor/tree/feat/retention/GH-6661-delete-older-than-n-days. I'll open a PR when the merge window for 1.9 opens.

**Comment by steven-zou** [comment]
Per our discussion, @nlowe will cover the implementation of this task
