### ISSUE TITLE
Tag Retention: API: CRUD

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6662]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Add CRUD operations for tag retention policies

* Create / Update / Delete a policy server wide / on a project / on a repo
* Add / Update / Remove filters from a policy

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by bitsf** [comment]
done
