### ISSUE TITLE
Tag Retention: API: Get Logs for Execution

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6663]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

For a given tag retention execution (or the latest one if none is specified), return the logs from the execution

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by steven-zou** [comment]
@ywk253100 

Mapping to the retention execution work.

**Comment by ywk253100** [comment]
Done
