### ISSUE TITLE
Tag Retention: API: Trigger Execution of a Retention Policy

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6664]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Trigger the execution of a specified retention policy

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by steven-zou** [comment]
Launch the retention @ywk253100

**Comment by ywk253100** [comment]
Done
