### ISSUE TITLE
Tag Retention: Schedule Exeuction of Retention Policy

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#6665]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Retention policies should be able to execute on a periodic interval / schedule.

**Comment by nlowe** [comment]
/remove-lifecycle stale

I still have every intention of completing this. The PR to merge some of the boilerplate has stalled out, hoping to have that merged soon so progress can continue.

**Comment by steven-zou** [comment]
@ywk253100 

Mapping to the scheduler work

**Comment by ywk253100** [comment]
Done
