### ISSUE TITLE
How to use RESTful api to login?

### ISSUE THREAD

**Issue by ggosa** [goharbor/harbor#6667]
At version 1.5, I can use api to login, like"/api/login",which is POST method,and the parameters are principal and password.BUT,at the version 1.7,this api does not work well,and returns 405 Please tell me how to solve it, Thank you very much~~~

**Comment by louyiping** [comment]
@ggosa you can use basic auth.
In golang, I use it like below:
`req, err := http.NewRequest("GET", url, nil)
req.SetBasicAuth("admin", "hardBORD1712")
resp, err := httpClient.Do(req)`

**Comment by steven-zou** [comment]
@louyiping 

Thanks again for answering questions. 

@ggosa 

You can follow what @louyiping side, thanks!

ps: As you have got the answer to the question, I'll close this issue. Thanks!

**Comment by ggosa** [comment]
Thank you so mauch!!!!!!!

**Comment by bihongfly** [comment]
> Thank you so mauch!!!!!!!

Hi ,would you tell me how to do it?
