### ISSUE TITLE
parallel replication in harbor

### ISSUE THREAD

**Issue by orenam** [goharbor/harbor#6668]
What can we help you?
Hi,
I see that only 3 replications can run in parallel.
is there any intent to change it?

**Comment by louyiping** [comment]
@orenam you can change it in harbor.cfg and it's the item named "max_job_workers"

**Comment by steven-zou** [comment]
@louyiping 

 Thanks for answering. @orenam right, you can set `max_job_workers` to change the concurrent threads of replication. The default value should be `10` (Version >=1.5).

**Comment by steven-zou** [comment]
@orenam 

As we have got the answer to your question, I'll close this one. Thanks.
