### ISSUE TITLE
[1.7.0] Missing Helm tab in Harbor UI 

### ISSUE THREAD

**Issue by webup** [goharbor/harbor#6670]
What can we help you?
Just upgraded from Harbor 1.6 to **v1.7.0-3b3311b4**, and tried in vain to spot "Helm" tab in harbor web interface as below figure indicates, could anybody help to take a further look, not quite sure whether it is a regression bug in harbor ui or any configuration item missed?

![image](https://user-images.githubusercontent.com/2936504/50579499-5d929100-0e80-11e9-987e-668bc5fe1fb6.png)

**Comment by steven-zou** [comment]
@webup 

Could you provide info about how did you install harbor?  Have you appended an extra parameter to install chart repo feature which is an optional feature?

**Comment by ming12713** [comment]
@steven 
webup and i are from same team ,we upgrade harbor from 1.6 to v1.7.0 follow as this guide  https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md  
upgrade use harbor-offline-installer-v1.7.0.tgz package with default harbor.cfg

**Comment by webup** [comment]
@steven-zou 

Finally we found the "optional" feature indicator @ https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#installation-with-chart-repository-service，problem resolved, and hopefully the installation guide could better highlight this change when upgrading to 1.7, thanks.

**Comment by MoeidHeidari** [comment]
chartmuseum is disabled by default. To install this service with Harbor you need to run the installer with chartmuseum enabled.
`./install.sh --with-chartmuseum`

**Comment by premsgr6** [comment]
I used helm chart version 1.12.0 to deploy harbor repository and in YAML file option for chartmuseum is not available.
