### ISSUE TITLE
Online Garbage Collection Overwritten tags will not be GCed

### ISSUE THREAD

**Issue by xjr100419** [goharbor/harbor#6677]
描述如下
https://github.com/goharbor/harbor/issues/3344

**Comment by steven-zou** [comment]
@wy65701436 
Please take a look at that is there any progress of fixing the registry issue described in #3344?

**Comment by wy65701436** [comment]
We will bump up the registry to v2.7.0 which has the capability to clean the untagged manifests.

**Comment by wy65701436** [comment]
PR(https://github.com/goharbor/harbor/pull/7170) has been merged into master, close it as fixed.
