### ISSUE TITLE
call /api/repositories/{repo}/tags sometimes takes too long 

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#6681]
I have set the timeout to 600 second in client and server side and it is still timeout when the number of tags in repo reach 500+ .
And sometimtes it is will be okay in 10 second with the same api and the same repo.

**Comment by louyiping** [comment]
my env：
harbor： 1.6.0
docker： 1.13

**Comment by steven-zou** [comment]
@louyiping 

It's a known issue, we have started to think how to improve it.

**Comment by louyiping** [comment]
@steven-zou look forward to it :)

**Comment by reasonerjt** [comment]
If it takes 600 sec to retrieve 500+ tags it's definitely a bug, @louyiping could you reproduce and provide the complete logs?  What storage are you using?

**Comment by reasonerjt** [comment]
@ywk253100 Could you check if the async approach is in 1.6.0

**Comment by louyiping** [comment]
@reasonerjt  I have four  harbor environment . "takes 600 sec to retrieve 500+ tags" —— this environment uses Ceph RBD. And I found this is ok in another environment using aliyun 云盘. So I think maybe it's a bug indeed.
