### ISSUE TITLE
UI render issue after clarity upgrade

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6691]
![image](https://user-images.githubusercontent.com/2841473/50671842-47670b00-100f-11e9-8513-70c9d5629040.png)

![image](https://user-images.githubusercontent.com/2841473/50671846-51890980-100f-11e9-9e12-b1f49339b3ed.png)

![image](https://user-images.githubusercontent.com/2841473/50671853-62397f80-100f-11e9-9d11-02dda61130f9.png)

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/50678924-f15c8c80-103b-11e9-8a59-ee5c656e6b5f.png)

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/50678988-50220600-103c-11e9-96b3-9c6a3908d213.png)

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/50679802-fa4f5d00-103f-11e9-92a9-5a1ff600ab42.png)
should add right side
