### ISSUE TITLE
Proposal: Harbor images naming scheme

### ISSUE THREAD

**Issue by CrystalMethod** [goharbor/harbor#6697]
**Describe the solution you'd like**
Unify the naming schema of Harbor images to ``goharbor/<subproject>:<version>-<flavour>``, e.g. ``goharbor/chartmuseum:v0.7.1-v1.7.0-photon``: make the flavour (base image in this case) part of the version tag. Currently it looks like ``goharbor/chartmuseum-photon:v0.7.1-v1.7.0``

**Comment by reasonerjt** [comment]
I don't think we want to fix this until there's a rule we need to follow.
