### ISSUE TITLE
Vulnerability database might not be fully ready!

### ISSUE THREAD

**Issue by D-PENG** [goharbor/harbor#6700]
There is a warning `Vulnerability database might not be fully ready! 0 items` in the lower right corner of `Projects/library`，and refresh the page will appear：
>```
> {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
>```
Install the chart
>```
>kubectl create secret tls harbor-cert --key=tls.key --cert=tls.crt
>helm install  --debug --name harbor --set externalDomain=lhharbor.xxxx.co,persistence.enabled=true,expose.tls.secretName=harbor-cert .
>```
The version of harbor is v1.7.0
>```
>[root@kubeadm harbor-helm]# kubectl get ing
>NAME                    HOSTS                                           ADDRESS   PORTS     AGE
>harbor-harbor-ingress   lhharbor.xxxx.co,lhharbor.xxxx.co             80, 443   27m
>[root@kubeadm harbor-helm]#
>```

**Comment by ywk253100** [comment]
The logs of `core` not the `notary server`.

**Comment by ywk253100** [comment]
Closing as inactivity.

**Comment by willzhang** [comment]
the same error! 
Vulnerability database might not be fully ready! 1 - 15 of 30 items
