### ISSUE TITLE
Can't create replication rule with the name which is deleted before

### ISSUE THREAD

**Issue by jeremyxu2010** [goharbor/harbor#6703]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: can create replication rule with the name which is deleted before
Actual: can not

**Steps to reproduce the problem:**
1. create a replication rule with the name `test`
2. delete the replication rule with the name `test`
3. recreate  a replication rule with the name `test`, the page shows `We are unable to perform your action because internal server errors have occurred.` error.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.0]
- docker engine version: [1.13.1]
- docker-compose version: []

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

`kubectl -n registry logs -f registry-harbor-core-686b745d-kxlz2` output:

```
2019-01-07T09:55:23Z [INFO] replication signal for policy 1 sent
2019-01-07T09:55:23Z [INFO] Handle notification with topic 'StartReplication': notification.StartReplicationNotification{PolicyID:1, Metadata:map[string]interface {}{"op_uuid":"4f1634ef48a64dfda266d8f7d88b45d8"}}
2019-01-07T09:55:39Z [ERROR] [base.go:94]: failed to create policy: pq: duplicate key value violates unique constraint "unique_policy_name"
```

`select * from replication_policy;` output:

```sql
registry=# select * from replication_policy;
 id | name | project_id | target_id | enabled | description | deleted |                  cron_str                  | filters | replicate_deletion
| start_time |    creation_time    |        update_time
----+------+------------+-----------+---------+-------------+---------+--------------------------------------------+---------+--------------------
+------------+---------------------+----------------------------
  1 | test |         17 |         1 | t       |             | t       | {"kind":"Immediate","schedule_param":null} |         | f
|            | 2019-01-07 09:55:23 | 2019-01-07 09:55:31.027222
(1 row)
```

**Comment by jeremyxu2010** [comment]
i guess the reason of this problem:
In step 2 `delete replication rule`， just mark replication_policy's `deleted` flag.  In step 3，`recreate replication rule`, db will report the name had already been used.

**Comment by wy65701436** [comment]
dup with #6698

**Comment by ywk253100** [comment]
Closing this one as it's a dup.
