### ISSUE TITLE
Missed dir make/kubernetes/ui/

### ISSUE THREAD

**Issue by gongzili456** [goharbor/harbor#6704]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Should has `make/kubernetes/ui/` dir.

**Steps to reproduce the problem:**

**Versions:**
master branch

**Comment by ninjadq** [comment]
hi @gongzili456 , can you provide more detailed information?

**Comment by gongzili456** [comment]
At master branch, `docs/kubernetes_deployment.md` said to run `python make/kubernetes/k8s-prepare`, it will gen a `make/kubernetes/ui.cm.yaml` file, but missed dir `make/kubernetes/ui`

**Comment by reasonerjt** [comment]
The key issue is that `kubernetes_deployment.md` is outdated to deploy Harbor to K8S you should use the helm chart.
See https://github.com/goharbor/harbor-helm

**Comment by reasonerjt** [comment]
Closing as won't fix.
