### ISSUE TITLE
About Harbor integrated with Clair,  How long does it take to complete？

### ISSUE THREAD

**Issue by arrowfeng** [goharbor/harbor#6711]
![image](https://user-images.githubusercontent.com/20623365/50819550-47477200-1365-11e9-8181-c11d4015dacf.png)

How to see the pull progress？

**Comment by mathislgs** [comment]
You can't see the progress directly, but you will find some additionnal info in the log files (/var/log/harbor/clair.log by default).

**Comment by arrowfeng** [comment]
thanks, it has alrealy finished.
another question, How can I view  scan logs of images on web ui? it looks like  have not option.

**Comment by CrystalMethod** [comment]
.. and there is a feature request to export results afterwards, see #6683

**Comment by arrowfeng** [comment]
thanks.
