### ISSUE TITLE
when i install harbor1.6.0 and i create a project,but i can not see helm-chart in harbor UI

### ISSUE THREAD

**Issue by antzjm** [goharbor/harbor#6718]
What can we help you?
when i install harbor1.6.0 and i create a project,but i can not see helm-chart in harbor UI.
I just want to use harbor to make a helm repo.

**Comment by louyiping** [comment]
Neither can I.

**Comment by louyiping** [comment]
oh，I found it. @antzjm 
You should install harbor with flag "--with-chartmuseum". You can check it in file "install.sh".
