### ISSUE TITLE
timed task of gc can not indicate the precise hour

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#6720]
Our env is fully containerization. If engineers can not push image, it will be greatly affected. So I must execute the online gc in the small hour.
But the timed task of gc can not indicate the precise hour, I dare not use it.

**Comment by wy65701436** [comment]
the cron task proposal on v1.8.0 is drafting, please monitor proposal list in the https://github.com/goharbor/community/pulls.

In the v1.7.0, you have to do it manually.

**Comment by louyiping** [comment]
@wy65701436  ok,thanks.

**Comment by reasonerjt** [comment]
Closing as this is addressed in `master` branch.
