### ISSUE TITLE
Clair docker container tag for dev

### ISSUE THREAD

**Issue by SDBrett** [goharbor/harbor#6722]
#### Issue
Running `./install.sh --with-clair` uses an incorrect docker container tag.

#### Steps
- Clone harbor repo
- Run command `sudo ./install --with-clair`

Expected result is that install process for clair looks for the container goharbor/clair-photon:v2.0.7-v1.7.1-dev.

#### Cause

Line 245 in ./Makefile: `DOCKERSAVE_PARA+= goharbor/clair-photon:$(CLAIRVERSION)-$(VERSIONTAG)` is not comparable outside of a stable release.

#### Resolution

Fixing the issue is straight forward, but I need some input from the Harbor team as to the preferred approach.

There is a clair-photon tag 'dev' and I can add an if statement to the Makefile that uses the tag 'dev' when $VERSIONTAG = dev. This will always use dev, but doesn't work if the desired outcome is to have a dev container for a specific version.

The other option is more is for the backend Harbor dev / release process. When pushing the clair-photon container for a release add an additional tag with suffix of 'dev'. This resolves the above issue and adds a development container for each release version.

Let me know which direction that you would like to take, if option 1 I'll get the PR ready.

Brett

**Comment by wy65701436** [comment]
@SDBrett , the script doesn't support installation with source code.

**Comment by reasonerjt** [comment]
Closing as won't fix
