### ISSUE TITLE
failed to pull images from harbor backend is S3

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#6730]
hi 
i get some error when push or pull from harbor,the backend is S3
![image](https://user-images.githubusercontent.com/1812254/50957146-70e4d280-14f8-11e9-9234-15618dfbcbe6.png)

**Comment by reasonerjt** [comment]
The problem is in your client that it times out to access S3.... 

I don't think Harbor can fix it given its scope.

**Comment by ninjadq** [comment]
@sinycn plz provide more information like error log and your enviroment

**Comment by sinycn** [comment]
@ninjadq  i finally find the reason: our proxy https inspect function cause this issue

**Comment by reasonerjt** [comment]
@sinycn  thanks for the update, let me close this one...
