### ISSUE TITLE
Integration with  Mesosphere DC/OS

### ISSUE THREAD

**Issue by GavinBF** [goharbor/harbor#6731]
What can we help you?
Harbor can publish and store packages in the  Mesosphere DC/OS Universe repository, The links are as follows:
https://github.com/mesosphere/universe
https://mesosphere.com/service-catalog

**Comment by harryge00** [comment]
SDK Developer Guide: https://mesosphere.github.io/dcos-commons/developer-guide/
dcos-commons:  https://github.com/mesosphere/dcos-commons

**Comment by steven-zou** [comment]
Transfer all the requirements to @xaleeks for tracking.

**Comment by xaleeks** [comment]
This is going to be no-go, sorry guys
