### ISSUE TITLE
Add docs for configuring with open-source CF and UAA

### ISSUE THREAD

**Issue by mogul** [goharbor/harbor#6732]
It looks like UAA authentication support was explicitly added in 1.4.0, but the only documentation I could find about how to configure this is in the Pivotal website. Can you add [documentation on this configuration](https://github.com/goharbor/harbor/blob/481bdb01a275bbbe172a8f30ee451615808380af/tools/migration/cfg/migrator_1_7_0/harbor.cfg.tpl#L181-L186) for users of open-source Cloud Foundry/UAA?

In particular, [here](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#user-account) and [here](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#managing-authentication).

**Comment by reasonerjt** [comment]
@mogul 
The UAA support was added for Harbor tile only.  We don't actively test it against in OSS Harbor so it's deliberately not documented.

**Comment by reasonerjt** [comment]
As I explained this is for tile user only, ops-man will handle that, and in 1.8 we will support OIDC auth mode, so alternatively you should be able to configure UAA as a OIDC provider and enable SSO.
The proposal please refer to:
https://github.com/goharbor/community/pull/64
