### ISSUE TITLE
Search function on top of main frame is not effective

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6738]
This issue was found by nightly migrate automation test script.

**Description:**
After input existing project name in search input box, there's no any result shown since then.

**Product steps:**
1. Sign into harbor;
2. There are existing projects already;
3. Input an existing project name;
4. We expect to see the project in result page, but nothing.

**Versions:**
- harbor version: [Version v1.8.0-a1d4bfd3]

**Comment by ywk253100** [comment]
The `Search` function doesn't work when installing Harbor without `chartmuseum` enabled.

**Comment by ninjadq** [comment]
fixed in #7059
