### ISSUE TITLE
Chart should be removed in /api/search response when chart repository not enabled

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#6740]
Chart should be removed in /api/search response when chart repository not enabled.

With ChartMuseum disable, response should be 
```json
{
    "project": [],
    "repository": []
}
```

With ChartMuseum enable, response will be
```json
{
    "project": [],
    "repository": [],
    "chart": []
}
```

**Comment by ninjadq** [comment]
fixed on #7059
