### ISSUE TITLE
后台增加关闭注册功能

### ISSUE THREAD

**Issue by rockpanda** [goharbor/harbor#6741]
Harbor版本：1.7
希望后面能够在后台增加一个"开启/关闭"自助注册功能的按钮，目前任意用户访问就都能够去注册，这样还是有一点麻烦，希望能够考虑，谢谢。

**Comment by reasonerjt** [comment]
This may be a regression as these is a configuration item to restrict creating user to admin only.

**Comment by wy65701436** [comment]
There is a configuration item in the admin authentication page, and I tried with the latest master code, it works as design.

**Comment by rockpanda** [comment]
1.7.1 配置管理中有“允许自注册”
