### ISSUE TITLE
Chart count should not be displayed without chartmuseum installed.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6753]
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/2841473/51164293-6f8c1f00-18d7-11e9-99a0-26b5d965556c.png">

**Comment by zhoumeina** [comment]
@ninjadq , could you please take care of this?

**Comment by reasonerjt** [comment]
This is probably fixed already, please check.

**Comment by ninjadq** [comment]
fixed in #7059

**Comment by reasonerjt** [comment]
Re-open to target in 1.7.5
