### ISSUE TITLE
Bump the chartmuseum version to latest V0.8.1

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#6754]
Fix a security bug described [here](https://helm.sh/blog/chartmuseum-security-notice-2019/index.html)

[V0.8.1](https://github.com/helm/chartmuseum/releases/tag/v0.8.1)

**Comment by steven-zou** [comment]
Assign the task to @ninjadq to do the actual work.

**Comment by reasonerjt** [comment]
@ninjadq Please make sure the Makefile is updated accordingly

**Comment by ninjadq** [comment]
Fixed in #6961
