### ISSUE TITLE
Add pipeline to test Harbor with chartmuseum disabled

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6762]
As there is an issue #6738 which was found out by accident, CI harbor_nightly_migrate should expend coverage by deploy harbor without chart feature.

**Comment by reasonerjt** [comment]
Per discussion, we'll create a pipeline to verify functionalities when chartmuseum is not installed

1.  Create the pipeline, make sure the chart museum is not enabled.
2.  Move the cases about helm chart out of `common.robot` to `helm.robot` and make sure cases in these 2 files are executed.

**Comment by danfengliu** [comment]
It's done, please reference PR #8398.
