### ISSUE TITLE
Search local DB first when adding a project member with username.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#6767]
In 
https://github.com/goharbor/harbor/blob/master/src/core/api/projectmember.go#L196

When request only has username, it's incorrect to assume the user is not onboard, this breaks when the authenticator does not have the capability of searching a user.

Same issue exists when adding a group member.

So it should search the local DB first in case the username is already onboarded.

**Comment by stonezdj** [comment]
Closed
