### ISSUE TITLE
In Project view, sorting by column values only sorts projects visible on the current page

### ISSUE THREAD

**Issue by mfornaro** [goharbor/harbor#6769]
In Project view, sorting by column values only sorts projects visible on the current page. It should be sorting all the projects on the instance, not just the ones currently visible on the page. This occurs when sorting by any column value. 

- harbor version:  v1.6.2-8065de70

**Comment by jwangyangls** [comment]
This looks more like clarity's fixed sort, so no modifications are recommended.

**Comment by YLzone** [comment]
This feature is necessary and is available in v1.2.2.

**Comment by CoaxVex** [comment]
This still exists in 2.0.0.

**Comment by balonik** [comment]
Sorting all items (projects, repositories, tags) have been working in the 1.10.x. Now after upgrade to 2.0.2 it is broken again.

**Comment by xaleeks** [comment]
@AllForNothing  please investigate this

**Comment by xaleeks** [comment]
and see if we can squeeze the fix into 2.2

**Comment by AllForNothing** [comment]
From 2.0.0, list projects api has started using backend pagination. It only returns some projects based on the current page and page size.  And filters of datagird column  are only effective for those projects returned.

 Please use top-rigtht filter to sort from all projects:
![image](https://user-images.githubusercontent.com/30999793/100186757-9bd84400-2f21-11eb-995a-85f340465bf8.png)
