### ISSUE TITLE
docker login - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jcmartins** [goharbor/harbor#6774]
I can acess harbor in web browser without problem and my certicate is ok but I **have error on docker login**

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.1]
- docker engine version: [18.06.1-ce]
- docker-compose version: [1.23.2]
- Linux AMAZON AMI: [ ami-09e634f7b62baee65]

sudo amazon-linux-extras enable docker
sudo amazon-linux-extras install docker -y

**Additional context:**
no error in logs

docker login my.intranet.com
Username: admin
Password: Harbor12345
**Error response from daemon: Get https://my.intranet.com/v2/: x509: certificate signed by unknown authority**

**Comment by reasonerjt** [comment]
This means your docker client does not trust the certificate of "my.intranet.com"

**Comment by clouderati** [comment]
Closing this one out @jcmartins – please don't hesitate to ping us if you have any more questions. Happy to re-open if needed.

**Comment by tirelibirefe** [comment]
@jcmartins 
were you able to find a workaround? 
I have the same problem.

**Comment by udautkarsh** [comment]
Does any one know, how this was fixed?
I followed this link: https://docs.docker.com/engine/security/certificates/ but it does not work at all.

**Comment by soulawaker** [comment]
Did you try to restart docker.service in client? First of all, install your Harbor private CA certificate in client machine. Then, restart docker in that `client` machine also. For instance, in Ubuntu 18.04:

```shell
scp harborhost:/harbor/cert/path/ca.crt /usr/local/share/ca-certificate/ca.crt
sudo update-ca-certificates
sudo systemctl restart docker.service
```

I think that harbor document should supplement this in https://goharbor.io/docs/2.0.0/install-config/configure-https/ or https://goharbor.io/docs/2.0.0/install-config/troubleshoot-installation#https.

**Comment by Codasip** [comment]
You can simply solve it when you add to harbor.yml config file before installation in _certificate_ option path to intermediate certificate file which contents server certificate and CA certificate afterwards. After installation this certs are copied somewhere to _<hrabor_data_dir>/secret/cert/_ but I am not sure if this is only one location for them.

**Comment by xjuric29** [comment]
You can simply solve it when you add to harbor.yml config file before installation in certificate option path to intermediate certificate file which contents server certificate and CA certificate afterwards. After installation this certs are copied somewhere to <hrabor_data_dir>/secret/cert/ but I am not sure if this is only one location for them.

**Comment by Mtze** [comment]
Also a common mistake (ask me how I know): You have to configure the full certificate-chain in the configuration file, not only the "last" one. See http://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by sturem** [comment]
> Also a common mistake (ask me how I know): You have to configure the full certificate-chain in the configuration file, not only the "last" one. See http://nginx.org/en/docs/http/configuring_https_servers.html

True, and an easy and non-obvious trap to fall into!
When the server side is configured, the server certificate should *also* include the whole chain of intermediate certificates (the root certificate should be set separately, in trusted certificates on the client).

SSL validation on the client checks the server cert presented in the cert chain sent back by the server side, determines the certificate the server cert was signed with (the issuer), checks that issuer intermediate cert (if it can find it: that intermediate cert should be next in the file configured on the server; some software can handle out-of-order certs or even figure out missing intermediate certs, but some needs intermediate certs to appear in the list sent back by the server in the exact order it tries to check them); the client determines then the signer of that intermediate cert (probably a root certificate, but you can have multiple levels of intermediate certificate). This continues until it finds a root certificate, which will be self-signed by the CA. The client checks the signing root certificate against it's list of trusted certificates. Iff all OK the SSL connection can be permitted; you get connection denied and "certificate signed by unknown authority" if an intermediate certificate is not supplied, or the final root certificate is unknown (note, the error message does not necessarily tell you *which* certificate it distrusts; it just indicates that there's an issue somewhere in the whole chain).

**Comment by lungmussDev** [comment]
````
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
````

I have this very same issue:

````
docker login <FQDN>
Username: john.doe
Password:
Error response from daemon: Get "https://<FQDN>/v2/": x509: certificate signed by unknown authority
````

However if I use ```curl``` or the http client in Rider or the https://<FQDN>/devcenter-api-2.0, for that matter, all is fine. Credentials are checked and I am logged in.

The certificate I use is a valid, commercial certificate. The browser interface is running fine.

A curl example:

````
curl -X 'GET' \
  'https://<FQDN>/api/v2.0/users/current' \
  -H 'accept: application/json' \
  -H 'authorization: Basic <authentication>'
```` 

and I get a valid response:

````
{
  "admin_role_in_auth": false,
  "creation_time": "2022-08-31T12:13:48.151Z",
  "email": "john.doe@<FQDN>",
  "realname": "John Doe",
  "sysadmin_flag": false,
  "update_time": "2022-08-31T12:13:48.151Z",
  "user_id": 3,
  "username": "john.doe"
}
```` 

This is driving me up the wall ;-)

Does anyone have a clue on how I can debug this. Can I force ````docker login```` to spit out the certificate checked?

Does ```docker login``` use a different certificate store than the default Windows 11 certificate store?
What certificate is used on the backend for the ```docker login```

Any help would be appreciated. I am running out of ideas.

Thanks.

![grafik](https://user-images.githubusercontent.com/106751209/187702880-168ee69f-8d2a-48bb-9003-a215b30dfdf2.png)

**Comment by lungmussDev** [comment]
Using this website (```https://www.ssllabs.com/ssltest/analyze.html```) analyzing the certificate, it showed the certificate chain was broken. This did not bother the webbrowser, however ```docker login``` threw the aformentioned error.

I concatenated all certificates in the ```data/secret/cert/server.crt``` file and now all is working fine.

**Comment by christiansicari** [comment]
I solved in this way.
I have Harbor in K3s instance exposed in NodePort on the Port 30003.
in the values.yaml I have
```
...
expose.type: nodePort
externalURL: https://harbor.my.org:30003 # put there the port also
...
tls:
  auto:
      commonName: harbor.my.org
    certSource: auto
...
```
Then I logged in Harbor, from the project page I clicked on "Registry Certificate", then I stored it my client path at /etc/ssl/certs
Finally:
```
sudo update-ca-certificates
sudo systemctl restart docker.service
```

**Comment by samratdgreat** [comment]
I am planning to use robot account to push the image and made sure that the account has push access. When I provide those credentials in jenkins pipeline, i am getting:
Error response from daemon: Get "https://<harbor url>/v2/" : x509: certificate signed by unknown authority.

However, i am able to login with that username and password " docker login <url> - u <robot-username> -p <robot-password>

Do i still need to provide the certificate to docker client?

**Comment by fwx5618177** [comment]
> I am planning to use robot account to push the image and made sure that the account has push access. When I provide those credentials in jenkins pipeline, i am getting: Error response from daemon: Get "https:///v2/" : x509: certificate signed by unknown authority.
> 
> However, i am able to login with that username and password " docker login - u -p
> 
> Do i still need to provide the certificate to docker client?

Sure, you need to provide this in your client
