### ISSUE TITLE
Upgrade & migration guide for Kubernetes install

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor#6775]
I see there is an upgrade guide for a docker installation. Is there a upgrade & migration guide for a Kubernetes installation? 
1. Do I need to download a new chart or simply change the image tags in values.yaml (I don't like to use the default tag dev. I always use a specific tag so I know which version is installed) of the old chart?
2. If I reuse the existing pvcs for an upgrade, will the upgrade take care of any changes necessary inside especially database changes?

**Comment by heww** [comment]
The 1.0.0 tag in harbor-helm using the 1.7.0 version of harbor, you can have a try.

Btw, @ywk253100 should we tag and release harbor-helm with the same version with harbor?

**Comment by ywk253100** [comment]
@shen3lu4 
1. Use the chart on the specific branch(such as 1.0.0) rather than master, it uses a specific version of Harbor.
2. Yes, the application will upgrade the database automatically when starting up.

**Comment by reasonerjt** [comment]
@shen3lu4 If no further questions I'll close this issue.
