### ISSUE TITLE
Registry disk usage

### ISSUE THREAD

**Issue by aviratna** [goharbor/harbor#6778]
Is there a option to monitor the Registry Disk usage through harbor UI.

We have come across an issue where registry will be down because disk is full.

This feature will be very helpful, it will help us to monitor the registry disk usage and take the action /increase the capacity before registry service is down.

**Comment by shinebayar-g** [comment]
It already has.
![image](https://user-images.githubusercontent.com/3091558/51512079-1116f180-1e3f-11e9-8d22-396d5fc4862a.png)

**Comment by clouderati** [comment]
Closing this one out; let us know if you have any other questions!

**Comment by zevaks** [comment]
Hello, @shinebayar-g any advises why this storage metrics can be missing?
![harbor](https://user-images.githubusercontent.com/37455849/67486582-9ba9ad00-f66c-11e9-85e5-cf726402b50b.PNG)

Using filesystem type storage witch custom /storage rootdirectory.

Thank you in advance.
