### ISSUE TITLE
Users must be Harbor admins to query docker registry catalog (v2/_catalog)

### ISSUE THREAD

**Issue by darend** [goharbor/harbor#6784]
## request

Allow a harbor user to query docker registry `v2/_catalog` endpoint without being a Harbor admin

## issue

We want to integrate Harbor with external tools that benefit from the `v2/_catalog` API (such as [Spinnaker](https://www.spinnaker.io/setup/install/providers/docker-registry/#other-registries) ). Without the catalog endpoint, configuring these tools requires manually enumerating all images. 

While Harbor supports the endpoint, testing has shown that a user must be a Harbor admin (not project admin) to access it. This is unfortunate as it requires us to promote these tool accounts.

**Comment by darend** [comment]
@coolpalani yes we have it working with some caveats...

1) The user that spinnaker logs in as must be a Harbor admin
2) Harbor configures chart museum to return relative URLs for charts. Currently, spinnaker assumes that the catalog has absolute URLs and will fail to parse it. Updating harbor to support use of absolute URLs is discussed in https://github.com/goharbor/harbor/issues/6572 and https://github.com/goharbor/harbor-helm/issues/149. Im not aware of a Spinnaker issue to support relative URLs.

Here is the command we use to add Harbor.
```
cat $HARBOR_PASSWORD | hal config artifact helm account add harbor --username "$HARBOR_USERNAME" --repository "$HARBOR_ADDRESS/chartrepo/$HARBORREPOSITORY" --password
```

**Comment by shashank-k** [comment]
Is there any update on this, We would like to integrate with Spinnaker. 
Also is it possible for project admin to query  `v2/_catalog` which lists only the images/charts for his specific project.

**Comment by yusiwen** [comment]
Any updates?

We use Visual Studio Code docker extensions to access the remote harbor registry, it's not safe to give anyone admin access just to list the catalog

**Comment by sidewinder12s** [comment]
This has also bitten us a lot for users coming from GCR or ECR, both of which support listing tags for images.

**Comment by darend** [comment]
The system level robot accounts introduced in 2.2 fixes the limitation: https://goharbor.io/docs/2.2.0/administration/robot-accounts/

**Comment by kirrmann** [comment]
I'm still not able to query `v2/_catalog` with system robot accounts in 2.2

`{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to list catalog: unauthorized to list catalog"}]}`

Anything that I'm missing here?

**Comment by gnanderson** [comment]
> The system level robot accounts introduced in 2.2 fixes the limitation: https://goharbor.io/docs/2.2.0/administration/robot-accounts/

It appears not - just as @kirrmann stated system level robot account still fail to list the catalog - we really don't want to be using admin credentials :(

**Comment by sidewinder12s** [comment]
Another issue my team ran into was if you used System level permissions and Project level permissions within the same RBAC policy, the project permissions would get dropped at evaluation time and you'd effectively only have the system permissions. We had to setup 2 robot accounts for our integration, one for system and one for project to fully use the API. There are a bunch of issues around RBAC/System Robot accounts after 2.2 that I had found though.

https://github.com/goharbor/harbor/issues/14512#issuecomment-827062680

**Comment by whysi** [comment]
> Any updates?
> 
> We use Visual Studio Code docker extensions to access the remote harbor registry, it's not safe to give everyone the admin access privilege just for listing the catalog

Same problem here. We are trying to use VS Code docker extension to access Harbor as a remote registry with specific users account, as non-admins and with mantainer role on some projects. The fact that only admins can call the catalog API is quite limiting and it's stopping us from using VS Code with Harbor. 
We also tried to use robot accounts, since it could be a viable alternate solution, but it fails (even with 2.4.0).

A nice addition would be to permit the catalog API to all users or create a new global role to enable user to call the API.

Is this something that can be put on roadmap? I'll be more than happy to give you detailed information about our configuration or to test out this feature in a beta version of Harbor.

**Comment by Geethree** [comment]
I just hit this today as well. In particular, we are trying to use harbor with spinnaker robot users... and robot users cannot hit v1/_catalog as the parent states.

Hitting the endpoint with curl..
```
sh robot_endpoints.sh 
Using robot$spinnaker
{"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to list catalog: unauthorized to list catalog"}]}
Using oidc user
{"repositories":[REDACTED but totally worked]}
```

## As a "now" work around
Unfortunately, when using OIDC auth we cannot create local users.. so I had to set the spinnaker user to be my administrator user and was able to let spinnaker use harbor.

This feels incredibly subpar, but would love to help solve this if possible!

**Comment by wy65701436** [comment]
Harbor(v2.4+) supports to use robot account to call catalog API but it's not exposed in UI, so you have to create the robot with API.

```
{
   "name":"test",
   "duration":30,
   "description":"test",
   "disable":false,
   "level":"system",
   "permissions":[
      {
         "kind":"system",
         "namespace":"/",
         "access":[
            {
               "resource":"catalog",
               "action":"read"
            }
         ]
      }
   ]
}
```

**Comment by whysi** [comment]
I tested the solution with the permission catalog read to a robot account, now I'm able to browse the first level of all the projects but I cannot browse of even pull any of the projects. I gave all the required permissions to a project to test it out but no luck, this is the error that I receive with VS Code:
![image](https://user-images.githubusercontent.com/93594835/167672809-d2271498-1d09-4019-808f-a5500ca6d264.png)

When I try a pull:
`Error response from daemon: unauthorized: unauthorized to access repository: myproject/myrepo, action: pull: unauthorized to access repository: myproject/myrepo, action: pull`

This is my robot account configuration:
```
{
    "creation_time": "redacted_for_privacy",
    "disable": false,
    "duration": -1,
    "editable": true,
    "expires_at": -1,
    "id": "redacted_for_privacy",
    "level": "system",
    "name": "redacted_for_privacy",
    "permissions": [
      {
        "access": [
          {
            "action": "push",
            "resource": "repository"
          },
          {
            "action": "pull",
            "resource": "repository"
          },
          {
            "action": "delete",
            "resource": "artifact"
          },
          {
            "action": "read",
            "resource": "helm-chart"
          },
          {
            "action": "create",
            "resource": "helm-chart-version"
          },
          {
            "action": "delete",
            "resource": "helm-chart-version"
          },
          {
            "action": "create",
            "resource": "tag"
          },
          {
            "action": "delete",
            "resource": "tag"
          },
          {
            "action": "create",
            "resource": "artifact-label"
          },
          {
            "action": "create",
            "resource": "scan"
          },
          {
            "action": "stop",
            "resource": "scan"
          },
          {
            "action": "list",
            "resource": "artifact"
          },
          {
            "action": "list",
            "resource": "repository"
          }
        ],
        "kind": "project",
        "namespace": "redacted_for_privacy"
      },
      {
        "access": [
          {
            "action": "read",
            "resource": "catalog"
          }
        ],
        "kind": "system",
        "namespace": "/"
      }
    ],
    "update_time": "2022-05-10T15:36:42.643Z"
```
  
Is this maybe related to issue #14145 ?

**Comment by whysi** [comment]
just to add after a few more tests: I can confirm what supposed on the reply https://github.com/goharbor/harbor/issues/14145#issuecomment-825593691 of issue #14145. After configuring the system permissions to read the catalog the project permissions doesn't work anymore. I get an access denied when trying to pull an image on a project where the robot account has all the grants. After editing the robot account removing the system/catalog read permission I am able to use the account to pull the same image from the same repository.
It seems that the mixing of system and project ACLs breaks the project permissions evaluation. Really disappointing since the addition of the catalog read grant via the API was a really nice step forward in the integration of an external tool like VS Code, without the need to use an admin account.

**Comment by texano00** [comment]
I have exactly the same problem described by @whysi using Harbor v2.5.3.
It seems that "project" and "system" permissions does not work well together. 😭
Unfortunately this behavior cannot permit external tools integration that use Docker HTTP API v2. 
I described my use case here  --> https://github.com/goharbor/harbor/issues/13653#issuecomment-1205438111

**Comment by ezh** [comment]
Hey everyone, I applied a simple workaround, and now my environment has full access to /v2/_catalog
1. create a dedicated robot account only with catalog access
2. spin up Nginx reverse proxy -> harbor-core with hardcoded `Authorization "Basic cm9ib...`
3. point ingress /v2/_catalog to reverse proxy
It works like a charm 🎉 

Ingress block to reverse proxy
```
...
            path: /service/
            pathType: Prefix
          - backend:
              service:
                name: hardor-registry-fix
                port:
                  number: 80
            path: /v2/_catalog
            pathType: Prefix
          - backend:
              service:
                name: harbor-core
                port:
                  number: 80
            path: /v2/
            pathType: Prefix
          - backend:
...
```

Nginx configuration
```
server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;

    location / {
        proxy_pass http://harbor-core;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization "Basic cm9...";
    }
}
```

Part of `nginx-catalog-deployment.yaml`
```
    spec:
      containers:
        - image: nginx:1-alpine-slim
          name: nginx
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/nginx/conf.d
```
