### ISSUE TITLE
Replication NG (next generation) support

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#6798]
For the details of replication NG, please refer to the design [proposal](https://github.com/goharbor/community/pull/40).

We may have total story points 42 (full time, 10 weeks).
Most of the members are part-time, so count the total with a ratio 4 * 10 *1/4 + 1 * 10 + 2 =  22 points

**Comment by thatsk** [comment]
in which version we are going to support helm chat replication?

**Comment by steven-zou** [comment]
@thatsk 

Next one: v1.8
