### ISSUE TITLE
[UI] Enhance the registry management ui to reflect the new changes

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#6806]
For more details, please refer to https://github.com/goharbor/community/blob/master/proposals/Content-Replication-ng.md#registry-management-1

**Comment by zhoumeina** [comment]
What does this mean?@steven-zou

**Comment by steven-zou** [comment]
> What does this mean?@steven-zou

Please refer to https://github.com/goharbor/community/blob/master/proposals/Content-Replication-ng.md#registry-management-1

**Comment by pureshine** [comment]
done as pr #7179
