### ISSUE TITLE
Search not working on v1.7.1

### ISSUE THREAD

**Issue by nvacelet** [goharbor/harbor#6810]
Hello,

According to last install based on v1.7.1, installation has been successfully installed, pull push as well. However UI search is not working : no result / output for project or repository.

**Comment by heww** [comment]
Do you install the chartmuseum component?  If not installed, the search is broken, we will fix it in the next release.

**Comment by nvacelet** [comment]
No, I did not installed chartmuseum component.

**Comment by nvacelet** [comment]
Search is working fine wirh "--with-chartmuseum "

**Comment by nlowe** [comment]
@heww Is there an issue tracking that? I upgraded to 1.7.1 on Friday without knowing about that.
