### ISSUE TITLE
Images built with Kaniko dont show up in the portal

### ISSUE THREAD

**Issue by kminhc** [goharbor/harbor#6811]
Hey, just wanted to report that images built with Kaniko dont show up in the Harbor UI, but are in fact pushed to the Registry and pullable. I don't know if fixing this is in scope.

Harbor Version: v1.7.0-3b3311b4
Kaniko used in container with: gcr.io/kaniko-project/executor:debug

kind regards

**Comment by clouderati** [comment]
Interesting; we've not tested this yet. The image was created by Kaniko; what about the client that you used to push the image to Harbor?

**Comment by kminhc** [comment]
I used kaniko to push directly to the registry. It appears that after repushing the same image with the docker client, all the following images built with kaniko are displayed correctly in the UI. Maybe this needs further testing.

**Comment by vaxinate** [comment]
Hello, friends! I am also experiencing this problem! There is another github user who posted a similar issue over on the kaniko repository https://github.com/GoogleContainerTools/kaniko/issues/539

**Comment by shanesiebken** [comment]
I don't know how Harbor ingests the webhooks from Docker registry (I'm assuming that's how you populate your database), but Kaniko uses the [go-containerregistry](https://github.com/google/go-containerregistry) library to push images to registries. ITT that package streams images up in such a way that the registry Notifications output is different than when pushing with a Docker client. I have seen the same issue with Portus (another registry front-end out of OpenSUSE) and was seeing it drop a lot of notifications on the floor in its logs. I haven't dug into Harbor, but I wouldn't be surprised if this were a similar issue.

**Comment by vaxinate** [comment]
Hmmm. Thanks for the insight. I don't know Go too well, but I guess I'll see if I can confirm/deny your idea. I'll update if I manage to figure anything out.

**Comment by shanesiebken** [comment]
I actually have some cycles today to take a look at this today, I think. I will dig in and see what I can find out!

**Comment by vaxinate** [comment]
I haven't really had time to try and figure out why this doesn't work, but I was trying to dig around in the code just with the info that @shanesiebken suggested and landed on [this chunk of code](https://github.com/goharbor/harbor/blob/master/src/core/service/notifications/registry/handler.go#L94). I'm doing some a healthy amount of guessing, but this may be the location of the problem? It may also be useless, but I figured I'd drop a breadcrumb here. I would like to figure out how to run Harbor for development so I can test and try to fix it, but my time is limited. I'll keep checking back and updating when I have new developments.

**Comment by reasonerjt** [comment]
after #6689 is merged this should be fixed. 
I'm closing it, please re-open if you are still seeting the problem.
