### ISSUE TITLE
LDAP Groups: DN is case sensitive and Project Members View auto-casing DN input.

### ISSUE THREAD

**Issue by DevOpsCow** [goharbor/harbor#6812]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A. When adding LDAP groups into Harbor, I should be able to copy/paste the full DN, without case sensitivity. However right now I can only add lower-case DNs as an Admin in the Groups section of the left menu
B. When I add a group on the Project Members Tab, choosing "Add a group from LDAP to project member" the View is modifying the case of the group DN, and I end up with a non-working group. This is a different behavior if I do it from the left menu->groups section.

**Steps to reproduce the problem:**
1. Go into a project, select Add Group, choose the second option "Add a group from LDAP to project member"
2. Enter a lower-case LDAP DN `cn=my-team,ou=groups,dc=americas,dc=corp,dc=contoso,dc=com` (and a name and role), click Save
3. As an admin, go to the left side bar, into "Groups" view. You will notice "my-team" DN was modified by Harbor UI to have capitalized `CN`, `OU` and `DC`
4. The user is unable to access the project, since Harbor is being case sensitive to the DN

Work-around:
5. As an admin, go into Groups section of left hand menu.
6. Delete "my team"
7. Re-add "my-team" with a lower case DN" `cn=my-team,ou=groups,dc=americas,dc=corp,dc=contoso,dc=com`
8. Now the GUI show the DN fully in lower case. The capitalization occurs only in the Project-Members Tab when adding a group there..
9. Proceed to grant "my-team" access to the project
10. done, user has access.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.6.0-66709daa
- docker engine version: 17.9.1
- docker-compose version: n/a using your Helm chart in Kubernetes 1.11.5

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
@stonezdj please help triage whether this is an issue in UI or the backend code?

**Comment by stonezdj** [comment]
Refer the PR: https://github.com/goharbor/harbor/pull/5896
In the current implementation, all ldap_group_dn is always lowercased, it can't be uppercased.
The fact that ```You will notice "my-team" DN was modified by Harbor UI to have capitalized CN, OU and DC```  is it correct?
Or your LDAP server is case sensitive?

**Comment by stonezdj** [comment]
Will fix this issue by revert #5985

**Comment by stonezdj** [comment]
What is the type your LDAP server? OpenLDAP, Active Directory or Oracle LDAP?

**Comment by reasonerjt** [comment]
It's very likely fixed already, please try in latest build.  
If you reproduce it, add comment I'll re-open.
