### ISSUE TITLE
make the affection of failover of redis less

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#6828]
Harbor doesn't support redis well due to the framework beego. This makes harbor HA more complex.
So we can bring down the affection of failover of redis if upgrading framework is difficult.
Due to the operation from docker is token authorized, so can we make docker login/pull/push still work after redis is down?

**Comment by clouderati** [comment]
I'm going to throw out a controversial 2¢: we shouldn't be using Redis at all. Why not something like NATS that we can build directly into the core of Harbor?

**Comment by mmpei** [comment]
but redis doesn't support HA well in harbor.  and could not use redis cluster or redis sentinel.(beego doesn't support configing multi addresses).
so how to resolved this? could we do something to make redis not so important if making redis HA is difficult.
any idea or plan? @reasonerjt @clouderati

**Comment by clouderati** [comment]
Yes, I'm aware of why we rely on it. I've done some initial brainstorming on the topic and I'm absolutely certain there are other ways of doing this. I'll open a proposal to track my thoughts a bit later.

@mmpei I'll CC you on my proposal / thoughts when I've fleshed them out.

**Comment by reasonerjt** [comment]
@mmpei I believe `docker pull/push/login` does work if you are using db or ldap auth and redis is down?

**Comment by mmpei** [comment]
core will crash and try to connect to redis if redis is down. and all API will get a 500 error code.

**Comment by shahbazn** [comment]
Is there any progress on this issue? I am trying to use redis HA behind HAproxy so that at he end I only have to configure one endpoint with harbor. But it still does not seem to work.

**Comment by mmpei** [comment]
not yet. Now we use the redis HA with HAproxy too. and it works well.
see [here](https://community.pivotal.io/s/article/How-to-setup-HAProxy-and-Redis-Sentinel-for-automatic-failover-between-Redis-Master-and-Slave-servers). it is also recommended by harbor.
and now i think making harbor to support redis sentinel or redis cluster is a finnal resolvation.

**Comment by KarstenSiemer** [comment]
be sure to deploy your redis cluster with a HAProxy in front of it and configure the timeout values like this:
```
timeout:
    connect: 30s
    server: 3600s
    client: 3600s
```
You have to use the jobservice in at least version 1.9.0 . But go to the latest release if you can.
You have to configure the timeout in HAProxy because the timeout in jobservice are hardcoded.
