### ISSUE TITLE
Retry pull image operation when it failed

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6835]
In case "Project Level Image Serverity Policy", there is a pull image operation, it fails accsionally due to network flash breaks or other reasons.

**Comment by clouderati** [comment]
This is an issue specific against our CI environment, correct?

**Comment by danfengliu** [comment]
yes, this issue is only for robot test cases, when we run nightly tests in Jenkins, we found out that pull image operation failed occasionally, it may be caused by network issue, so add retry is necessary.

**Comment by danfengliu** [comment]
It's fixed.
