### ISSUE TITLE
Harbor as a pull cache and private registry

### ISSUE THREAD

**Issue by rbkaspr** [goharbor/harbor#6863]
We're looking to use Harbor as a private registry and would like it to also serve as a pull-through cache for the official Docker registry.
This feature is desirable for our use case because our Kubernetes cluster nodes have limited public ingress/egress points, and we'd like to be able to cache official Docker images locally to reduce the load on our public network devices, while still maintaining the ability to push our custom images to the same Harbor instance from our CI environment.

**Comment by clouderati** [comment]
Hi @rbkaspr – there's a proposal to enable this functionality defined [here](https://github.com/goharbor/community/pull/40). So coming soon. :smile:

Please let us know if you want to help, including testing the feature as we get closer to developing it.

**Comment by rbkaspr** [comment]
@clouderati I'd be happy to help any way I can with this feature, especially testing. I don't have any substantial Go experience, but I have a couple high-level thoughts about how this could be implemented based on your current deployment model(unless you already have an implementation in mind).

**Comment by clouderati** [comment]
Testing is super helpful! I'll ping you when the feature gets closer to release and perhaps you can give it a whirl and share your 2¢. 😄 Thanks!

**Comment by rbkaspr** [comment]
Awesome! Looking forward to hearing more and trying it out once it's ready :smile:

**Comment by d2dyno** [comment]
I really like this idea! any progress?

**Comment by cedvan** [comment]
duplicate with https://github.com/goharbor/harbor/issues/6894 ?

**Comment by xaleeks** [comment]
#8082

**Comment by xaleeks** [comment]
I'm closing this please refer to 8082 above
