### ISSUE TITLE
Missing LDAP_GROUP_ADMIN_DN variable description in install doc

### ISSUE THREAD

**Issue by tux-00** [goharbor/harbor#6864]
Here : https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#optional-parameters

**Comment by clouderati** [comment]
Thanks @tux-00 – really appreciate the report. Are you hoping to submit a PR to update the docs? If not happy to take care of it on this end.

**Comment by stonezdj** [comment]
Will fix it in #7324
