### ISSUE TITLE
Harbor UI

### ISSUE THREAD

**Issue by asadrao11** [goharbor/harbor#6866]
Hi, i think i am repeating the same issue related UI which some of users reported before, but i am facing a bit different, may be i am doing some mistakes in deployment. I have deployed harbor in openshift environment and facing these errors i am adding the screenshots for that.
![screen shot 2562-01-31 at 08 44 21](https://user-images.githubusercontent.com/29106050/52025085-b6178580-2535-11e9-8d27-50547bf789cc.png)
![screen shot 2562-01-28 at 11 37 56](https://user-images.githubusercontent.com/29106050/52025114-d34c5400-2535-11e9-88bb-08616fde47a3.png)

**Comment by asadrao11** [comment]
These are the routes which i have created.
![screen shot 2562-01-30 at 22 26 00](https://user-images.githubusercontent.com/29106050/52025173-068ee300-2536-11e9-89c5-b952e60af5a0.png)

**Comment by wy65701436** [comment]
Can you provide logs?

**Comment by asadrao11** [comment]
yes sure, for what container ?

**Comment by asadrao11** [comment]
Actually i want to tell you that my router is not exposing port:80 and the routes which i have created of container "harbor-core" have service port with 80 and i have created secure routes with https.

**Comment by asadrao11** [comment]
![screen shot 2562-01-31 at 09 45 13](https://user-images.githubusercontent.com/29106050/52027174-fb8b8100-253c-11e9-8ae6-fd34a8278fcf.png)

**Comment by asadrao11** [comment]
I have these containers, redis and postgres are externally connected.
![screen shot 2562-01-31 at 09 46 53](https://user-images.githubusercontent.com/29106050/52027242-3e4d5900-253d-11e9-9856-d18441523333.png)

**Comment by ywk253100** [comment]
@asadrao11 Sorry for the late reply. Can you first describe what your issue is? You cannot login on portal or got errors when visiting some specific pages? How about docker login? And please refer to https://github.com/goharbor/harbor-helm/issues/75#issuecomment-441604089 to check your env.

**Comment by asadrao11** [comment]
Hi, you have done a bit late, i was not able to deliver the project at time
and i was on probation. My manager fired me due to bad performance. I tried
to explain him i have opened case please give me some time. But he said we
have decided. Now i am jobeless i am going my country back.
Thanks and Kind Regards,
Asad

**Comment by ywk253100** [comment]
I'm so sorry for that. Hope everything goes well with you.

**Comment by asadrao11** [comment]
Thanks for your nice words.
