### ISSUE TITLE
Is there some tutorial to harbor HA other than helm chart.

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#6867]
As enterprise registry, HA is very important.
I found some ariticle on the internet, But they are a little messy.
I hope harbor could give an official guide to build HA. Thanks.

**Comment by louyiping** [comment]
@wy65701436  I also meet problem and Can't deploy harbor inside K8S.
 Our K8S deploy with kubeadm needs the private registry because of the GWF. And the private registry also needs K8S if I deploy harbor in K8S.
So I must guarantee the stablity of Harbor outside kubernetes cluster.

**Comment by clouderati** [comment]
This really goes to the core of something I've been championing a long while now. The user experience for Harbor needs some serious discussion and brainstorming. We shouldn't be forcing users to leverage K8s + Helm to deploy Harbor easily.

I've already started drafting a proposal for `goharbor/community` and will respond to this thread when I'm done so that folks can share their 2¢ on how we can better support a truly distributed, highly-available story.

**Comment by mmpei** [comment]
@lijianfeng1993  what conflict with network you meet?
i think making harbor HA more simple including dependencies and deploying outof k8s (maybe in static pod) is meanfull for harbor in production usage.

**Comment by Purushotham233** [comment]
Is not a image registry a pre-req for K8S cluster setup? If so , there is a clear need for Harbor outside k8s. Can we prioritise it accordingly?
Meanwhile, please share the recommended way for HA setup outside k8s.

**Comment by roldancer** [comment]
Openshift 3.11 control plane is 80% docker, it means that I need an existing internal docker registry, the registry and monitoring solution are both structural/critical components, I don't feel safe  deploying structural components on K8S/Openshift (being both consumer of structural/critical components) ... we would like to have a document that describes step by step how to deploy Harbor in High Availability outside any k8s distribution....

**Comment by Brice187** [comment]
Any news on this item?

**Comment by lwabish** [comment]
> @lijianfeng1993 what conflict with network you meet? i think making harbor HA more simple including dependencies and deploying outof k8s (maybe in static pod) is meanfull for harbor in production usage.

Is there any implements about deploying harbor with k8s static pods? Didn't find much information about this.
