### ISSUE TITLE
Harbor issues with clair enabled

### ISSUE THREAD

**Issue by kgrvamsi** [goharbor/harbor#6868]
When the make file is changed to enable the clair and run make all it results in the following issue
loading harbor images...
Pulling clair (goharbor/clair-photon:v2.0.7-dev)...
ERROR: manifest for goharbor/clair-photon:v2.0.7-dev not found
Makefile:443: recipe for target 'start' failed
make: *** [start] Error 1

**Comment by reasonerjt** [comment]
Let me dup this to #6722
