### ISSUE TITLE
Change disk size failed in harbor tile

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#6870]
Change the deployed harbor tile instances disk size failed with error message: 'umount: /var/vcap/store: target is busy
(In some cases useful info about processes that
use the device is found by lsof(8) or fuser(1).)

Need to reference docker bosh release to change the ctl script of dockerd job, umount the docker file system when stop dockerd.

https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/master/jobs/docker/templates/bin/ctl#L111

**Comment by clouderati** [comment]
Doesn't this belong in the `bosh-release` repo @stonezdj? I'd like to see tile-related work out of the upstream repo since the tile is not really a focus of the core project.

Thoughts @goharbor/all-maintainers?

**Comment by clouderati** [comment]
Haven't heard anything back, so I'll assume everyone is ok with this. Please move to the appropriate VMware-focused BOSH release repo so that we can keep `goharbor/harbor` purely vendor-neutral.
