### ISSUE TITLE
v1.7.0 : tags listing => 504 gateway timeout

### ISSUE THREAD

**Issue by nvacelet** [goharbor/harbor#6876]
I have large amount of tags related to one image (tags > 100). Problem is I am getting "504 Gateway Time-out" when I try to list tags from UI or from API. 

How can I increase timeout ? Or please can you add timeout setting update in new version ? 
Thx

**Comment by clouderati** [comment]
My first instinct is that this has something to do with the LB configuration. Will have to investigate.

**Comment by oxygenxo** [comment]
We have quite a big repositories (hundreds of tags, we're using them in CI) and we're unable to fetch them even just to delete them :) Not only on v1.7.0 though, can confirm that v1.6.0 is affected too.
Is there a way to increase request timeout?

**Comment by oxygenxo** [comment]
Interesting behavior. We're using Harbor.Tagd to clean old images from Harbor. When it tries to fetch all tags it raises exception with '504 Gateway Timeout', but subsequent runs went fine. It took 10-15 runs for me to retrieve all tags from all repositories. May be some cache involved?

**Comment by reasonerjt** [comment]
@nvacelet @oxygenxo what version of Harbor are you using?

**Comment by oxygenxo** [comment]
Hi @reasonerjt , I've experienced this on v1.6.0 and then when I've upgraded to v1.7.4 too

**Comment by lf1029698952** [comment]
same issue
+1

**Comment by lf1029698952** [comment]
I try add timeout options in nginx.conf
```
      proxy_connect_timeout 900s;
      proxy_send_timeout 900s;
      proxy_read_timeout 900s;
```
but It seems useless.
when get repo tags > 100,  the harbor api server will  spend a long time until timeout

![image](https://user-images.githubusercontent.com/11751263/56415023-fda0e880-62be-11e9-8268-ef2d90d147b8.png)

**Comment by cd1989** [comment]
There is a `detail` parameter, but doesn't take effect actually.

https://xxx/api/repositories/release/patroni/tags?detail=0

For tagd to work, maybe no need to fetch details.

**Comment by pgkulk** [comment]
I was getting similar error for repository having around 9000 tags. 
Adding proxy_send_timeout and proxy_read_timeout to /api/ block in nginx.conf resolved the issues.

location /api/ {
      proxy_pass http://core/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_cookie_path / "/; Secure";

      proxy_buffering off;
      proxy_request_buffering off;

      **proxy_send_timeout 900;
      proxy_read_timeout 900;**
    }
