### ISSUE TITLE
GetProjectRoles of secret.SecurityContext need refactor

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#6882]
Maybe return empty roles for secret.SecurityContext ?

**Comment by reasonerjt** [comment]
This is a refactor work, no impact in functionality.
Mark it as `defer-candidate`

**Comment by reasonerjt** [comment]
This is no longer needed as `GetProjectRoles ` is removed from the interface via 
https://github.com/goharbor/harbor/pull/11382
