### ISSUE TITLE
advise to add privilege for projectadmin to configure replication policy

### ISSUE THREAD

**Issue by elianka** [goharbor/harbor#689]
as the title. 
Now only admin could do the configuration for replication policy. its very hard for admin to do all the operation for replications.
 So in my opinion, we could let projectadmin to decide whether and which peer registry their project wanna do replication.

**Comment by walkamongus** [comment]
#2333 makes the same request

**Comment by walkamongus** [comment]
is this still a potential feature? or are there no plans to implement?
