### ISSUE TITLE
Support Bittorrent-like replication

### ISSUE THREAD

**Issue by luisdavim** [goharbor/harbor#6890]
If we have a lot of geographically distributed harbor instances it would be nice to have support for Bittorrent to synchronise images across them so that we could push an image to one of the instances and it would start seeding that image to the other instances, each instance that has that image becomes a seeder for it.

**Comment by clouderati** [comment]
There is work being done to integrate Dragonfly + Harbor (see [this](https://github.com/goharbor/community/pull/13) for more details). @steven-zou can provide some more context.

**Comment by luisdavim** [comment]
That seems related to image pulling, not registry replication. Am I wrong?

**Comment by steven-zou** [comment]
@luisdavim 

Right, that integration covers the image distributions via P2P protocol. For pushing case, the Harbor image replication can help to geographically sync images among different registry instances on top of normal way. Not support p2p way yet. Do you have some good idea of supporting the p2p way in image replication?

**Comment by luisdavim** [comment]
The scenario that I'm thinking about is one where we'd have many k8s clusrters and an Harbor instance on each of them, I would like to be able to push my images to one central Harbor instance, that could be used as a torrent tracker and the other ones would sync using p2p.

**Comment by steven-zou** [comment]
> The scenario that I'm thinking about is one where we'd have many k8s clusrters and an Harbor instance on each of them, I would like to be able to push my images to one central Harbor instance, that could be used as a torrent tracker and the other ones would sync using p2p.

@luisdavim 

The scenario you mentioned can be covered by the image replication feature of Harbor now. The replication feature is built on top of registry API, not by a P2P way.

For the P2P approach in the image sync/replication feature, do you have a good idea and are you willing to do some contributions on that feature?

**Comment by steven-zou** [comment]
Transfer all the requirements to @xaleeks for tracking.

**Comment by xaleeks** [comment]
@luisdavim  reviving this, we are tackling it in the upcoming release and have several community members engaged.  Ping us here if you are interested in discussing or contributing.

**Comment by xaleeks** [comment]
we're tracking that work here https://github.com/goharbor/harbor/issues/10875
