### ISSUE TITLE
LDAP Group DN is not found

### ISSUE THREAD

**Issue by vatrik** [goharbor/harbor#6891]
Hi all.
Have some problems with adding groups from AD in Harbor 1.7.1
Configuration is:
![image](https://user-images.githubusercontent.com/46010082/52260984-e34ea400-2938-11e9-8683-72fef689b342.png)
When i try to add group, which located in this OU, i receive an error:
![image](https://user-images.githubusercontent.com/46010082/52261041-0ed18e80-2939-11e9-9231-715546dd6170.png)
btw, LDAP Group Admin DN works fine, also users can easly authorize through LDAP. Could you help me with that problem ?

**Comment by vatrik** [comment]
> @vatrik LDAP Group DN must be the full DN of the group.
> I've just faced the same problem and went through the code in order to find out the solution.
> 
> Another issue (maybe I'll open another one) is that when you add a ldap group, the ldap group scope is completely ignored because it use always the ldap scope (user one):
> 
> [harbor/src/common/utils/ldap/ldap.go](https://github.com/goharbor/harbor/blob/98ab7f5644d691c34824d790697a8c240f3aaf8d/src/common/utils/ldap/ldap.go#L306)
> 
> Line 306 in [98ab7f5](/goharbor/harbor/commit/98ab7f5644d691c34824d790697a8c240f3aaf8d)
> 
>  session.ldapConfig.LdapScope, 
> So, in my case I had to set also Subtree in LDAP Scope prop (was one level) and finally I was able to add groups.

Thanks for the reply. I use LDAP Group DN such as : cn=testgroup1,ou=HARBOR_ACL's,dc=mycompany,dc=local and everything works fine for me.

Thanks alot!

**Comment by rimantasbutkus92** [comment]
Hi All, I understand this is closed but would it be possible not to use full DN for adding a group? In settings there's a specific Group Base DN, it's possible to add Group Filter and the Group GID also using subtree scope should be enough to identify the group.

I think it would be great improvement if it worked with let's say only CN of the group when adding it.
