### ISSUE TITLE
Configuration settings web UI 1.7.1 - unable to edit settings

### ISSUE THREAD

**Issue by cwelde** [goharbor/harbor#6893]
The dropdown to configure settings greyed out ~10 minutes ago. I was able to select the different options about an hour ago. I wanted to configure LDAP settings in the web UI, now I can't. Any reason for this happening?

![aaa](https://user-images.githubusercontent.com/28943926/52297682-278c7500-2936-11e9-900b-3e97a3de4487.PNG)

Edit: Someone manually created a user in that timeframe, could this be the reason?

**Comment by wy65701436** [comment]
It’s as designed, the auth mode cannot be changed to ldap if you register user in DB mode.

If you want to update it, please clean your data and relaunch harbor.

**Comment by clouderati** [comment]
@wy65701436 is right, the auth mode can't be changed _ex post facto._ This is a major issue / weakness, IMHO, in the project at the moment. Contributions to fix are welcome. :smile:

**Comment by cwelde** [comment]
> @wy65701436 is right, the auth mode can't be changed _ex post facto._ This is a major issue / weakness, IMHO, in the project at the moment. Contributions to fix are welcome. 😄

I agree, there should, at the very least, be some sort warning produced by the Web UI if you're about manually register a user. I was going to configure LDAP at a later time and wanted to verify that the machine I'm running push commands on was properly configured.
