### ISSUE TITLE
Logrotate i log service failing

### ISSUE THREAD

**Issue by ThomasRasmussen** [goharbor/harbor#6895]
We running the prebuilt image of Harbor and noticed that logfiles located in /var/log/harbor on host OS does not rotate. 

In harbor.cfg we have the following setting:
log_rotate_count = 5
log_rotate_size = 20M

When logging into the harbor-log container and manually run the logrotate command, it fails:
```
root [ / ]# logrotate -f /etc/logrotate.conf
error: error setting mode of /var/log/docker/adminserver.log.1: Operation not permitted
error: error setting mode of /var/log/docker/clair.log.1: Operation not permitted
error: error setting mode of /var/log/docker/core.log.1: Operation not permitted
error: error setting mode of /var/log/docker/jobservice.log.1: Operation not permitted
error: error setting mode of /var/log/docker/notary-server.log.1: Operation not permitted
error: error setting mode of /var/log/docker/notary-signer.log.1: Operation not permitted
error: error setting mode of /var/log/docker/portal.log.1: Operation not permitted
error: error setting mode of /var/log/docker/postgresql.log.1: Operation not permitted
error: error setting mode of /var/log/docker/proxy.log.1: Operation not permitted
error: error setting mode of /var/log/docker/redis.log.1: Operation not permitted
error: error setting mode of /var/log/docker/registry.log.1: Operation not permitted
error: error setting mode of /var/log/docker/registryctl.log.1: Operation not permitted
```

I expect that logfiles are rotated and compressed as the /etc/logrotate.d/logrotate.conf specifies:

```
/var/log/docker/*.log {
        rotate 5
        size 20M
        copytruncate
        compress
        missingok
        nodateext
}
```

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.1
- docker engine version: Docker version 18.06.1-ce, build e68fc7a
- docker-compose version: docker-compose version 1.17.1, build unknown
- Host VM: Ubuntu 18.04 LTS

**Comment by ThomasRasmussen** [comment]
Investigating the issue, I noticed that the docker-compose.yml specifies this for the log service:
```
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
```

Adding `FOWNER` to the cap_add section and redeploying the log service, then logrotate will rotate and compress logs.

**Comment by ThomasRasmussen** [comment]
Noticed another error in logrotate, the conf file (harbor/common/config/log/logrotate.conf) is rewritten by the prepare script and ends up with owner and group set to 10000:10000 

Logrotate will not include a file not owned by root, so one need to change ownership of the file on host OS to root:root. 

This change to the prepare script will fix that issue:

```
--- prepare.backup	2019-02-07 10:55:33.175982981 +0100
+++ prepare	2019-02-07 10:56:34.623687651 +0100
@@ -469,8 +469,8 @@

 render(os.path.join(templates_dir, "log", "logrotate.conf"),
         log_rotate_config,
-        uid=DEFAULT_UID,
-        gid=DEFAULT_GID,
+        uid=0,
+        gid=0,
         log_rotate_count=log_rotate_count,
 		log_rotate_size=log_rotate_size)
```

**Comment by ywk253100** [comment]
@ThomasRasmussen Thanks for reporting the issue, I fix it by running logrotate as user 10000 in PR #6895.
