### ISSUE TITLE
k8s image pull steps invalid for pks users

### ISSUE THREAD

**Issue by afewell** [goharbor/harbor#6907]
Hi team, I realize the harbor docs are not specific to pks, but the documented steps for pulling images for k8s are for generic k8s and could be confusing to PKS users. 

specifically in /docs/user_guide.md#pull-image-from-harbor-in-kubernetes, step #1 is not needed, proper, or even possible to do in pks, where client cert installation should be automated via bosh trusted certificates. 

The bosh trusted configuration is already documented in pks docs both in bosh install and again in in pks/harbor integration docs per the link below, so it does not need to be documented here.

If possible could you add a note that said something like "Step 1 is not valid for PKS,  for PKS deployments, [please follow the instructions to enable the bosh trusted certificate feature for pks here](https://docs.pivotal.io/partners/vmware-harbor/integrating-pks.html#provide-harbor-cert). PKS users do need to complete step 2 as documented below" as a suggestion, or really anything that could help pks users from getting confused by this step. 

Thank you!

**Comment by reasonerjt** [comment]
For PKS users please refer to the logs of Harbor tile.
