### ISSUE TITLE
API parameter name is not in lower case

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6925]
In below API, disable parameter was written as "Disable", please correct this to lower case as "disable".

    API:
        PUT /projects/{project_id}/robots/{robot_id}

![image](https://user-images.githubusercontent.com/44018302/52770151-4fce4f00-306d-11e9-86b7-55d5d60828fc.png)

**Comment by wy65701436** [comment]
Close it as done per PR https://github.com/goharbor/harbor/pull/7398
