### ISSUE TITLE
can't stop harbor in version 1.7.1 COMPOSE_HTTP_TIMEOUT

### ISSUE THREAD

**Issue by QuSongtao** [goharbor/harbor#6943]
hi: 

**Expected behavior and actual behavior:**
I intsall harbor success by this commad:
./install.sh --with-clair --with-chartmuseum

**Steps to reproduce the problem:**
![image](https://user-images.githubusercontent.com/15939134/52842734-f59bbf80-313a-11e9-8412-591805a8694b.png)

I can't stop the container of harbor-log
by the way,  harbor application looks like attack my dns server, firewall log like this,
![image](https://user-images.githubusercontent.com/15939134/52843189-6099c600-313c-11e9-9ae6-3d7cb80b6953.png)

 I hava to stop it and check. when I stop harbor ,attack is stop soon, who can tell me why?

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.1
- docker engine version:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
- docker-compose version: version 1.23.2, build 1110ad01

**Comment by leeningli** [comment]
1.7.4 have the same promble

**Comment by reasonerjt** [comment]
it's known that some times rsyslog stops slowly, do you see the issue when you increase the `COMPOSE_HTTP_TIMEOUT`?

**Comment by fshadid96** [comment]
is there any update on this? I am on 2.1.2 and still running into the same issue
