### ISSUE TITLE
Need help in setting up swagger for harbor-release-1.7.1

### ISSUE THREAD

**Issue by abhishek-kumar0409** [goharbor/harbor#6948]
Team,
Not sure if it's a duplicate issue.  I need some inputs to in set-up the Swagger in my environment. 

I have successfully installed the harbor by following the offline-installation instructions. The services are working fine. To set up swagger, I followed the instruction as mentioned in this [https://github.com/goharbor/harbor/blob/master/docs/configure_swagger.md](url). As per the instruction, two lines needs to be added to the docker-compose file. However, I don't find any section with the name "ui" in docker-compose.yml file(of v1.7.1 binary release).  Can someone suggest how do I proceed further? Is this an editorial issue in the documentation ?

Got the below error when I placed "ui" configuration object(key-value pairs) under the services section of the docker-compose.yml file. Not sure if its  the right approach, I couldn't find  that from the documentation.

**ERROR: The Compose file is invalid because:
Service ui has neither an image nor a build context specified. At least one must be provided.**

version: '2'
services:
   ...
   ui:
    volumes:
      - ./common/config/ui/app.conf:/etc/core/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/core/private_key.pem:z
      - /data/secretkey:/etc/core/key:z
      - /data/ca_download/:/etc/core/ca/:z
      ## add two lines as below ##
      - ../src/ui/static/vendors/swagger-ui-2.1.4/dist:/harbor/static/vendors/swagger
      - ../src/ui/static/resources/yaml/swagger.yaml:/harbor/static/resources/yaml/swagger.yaml

**Comment by Seally10** [comment]
I  add the two lines to the file docker-compose.yml under the section portal, and it works。
The src directory is under the harbor directory。

**portal:**
    image: goharbor/harbor-portal:v1.7.1
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    **volumes:
      - ./src/ui/static/vendors/swagger-ui-2.1.4/dist:/usr/share/nginx/html/static/vendors/swagger
      - ./src/ui/static/resources/yaml/swagger.yaml:/usr/share/nginx/html/static/resources/yaml/swagger.yaml**

**Comment by abhishek-kumar0409** [comment]
HI @Seally10 ,

Thanks much for your reply. I tried your solution but I am getting 404 while accessing the URL  **http://<HARBOR_SERVER>/static/vendors/swagger/index.html**. And, after sometime, the web server automatically redirects to homepage(dashboard) of the Harbor. Could you please suggest..

**Comment by abhishek-kumar0409** [comment]
**Stopped the running instance of the harbor:**
root@kmaster:/home/abhishek/goharbor/harbor# docker-compose -f docker-compose.yml -f docker-compose.clair.yml -f docker-compose.chartmuseum.yml down
Stopping nginx              ... done
Stopping harbor-portal      ... done
Stopping harbor-jobservice  ... done
Stopping clair              ... done
Stopping chartmuseum        ... done
Stopping harbor-core        ... done
Stopping registry           ... done
Stopping registryctl        ... done
Stopping harbor-db          ... done
Stopping harbor-adminserver ... done
Stopping redis              ... done
Stopping harbor-log         ... done
Removing nginx              ... done
Removing harbor-portal      ... done
Removing harbor-jobservice  ... done
Removing clair              ... done
Removing chartmuseum        ... done
Removing harbor-core        ... done
Removing registry           ... done
Removing registryctl        ... done
Removing harbor-db          ... done
Removing harbor-adminserver ... done
Removing redis              ... done
Removing harbor-log         ... done
Removing network harbor_harbor
Removing network harbor_harbor-clair
Removing network harbor_harbor-chartmuseum
root@kmaster:/home/abhishek/goharbor/harbor# ls -lrth
total 577M
-rwxr-xr-x 1 root root 5.7K Jan  4 16:53 install.sh
-rwxr-xr-x 1 root root  36K Jan  4 16:53 prepare
-rw-r--r-- 1 root root 731K Jan  4 16:53 open_source_license
-rw-r--r-- 1 root root  12K Jan  4 16:53 LICENSE
-rw-r--r-- 1 root root 5.5K Jan  4 16:53 docker-compose.yml
-rw-r--r-- 1 root root 1.5K Jan  4 16:53 docker-compose.notary.yml
-rw-r--r-- 1 root root  975 Jan  4 16:53 docker-compose.clair.yml
-rw-r--r-- 1 root root  939 Jan  4 16:53 docker-compose.chartmuseum.yml
-rw-r--r-- 1 root root 576M Jan  4 16:54 harbor.v1.7.1.tar.gz
drwxr-xr-x 4 root root 4.0K Feb 21 13:44 common
-rw-r--r-- 1 root root 7.9K Feb 21 14:27 harbor.cfg
**#Copied the contents of prepare-swagger.sh and swagger.yaml from docs**
root@kmaster:/home/abhishek/goharbor/harbor# vim prepare-swagger.sh
root@kmaster:/home/abhishek/goharbor/harbor# vim swagger.yaml
#CHANGED THE DOMAIN name to my VM IP
root@kmaster:/home/abhishek/goharbor/harbor# vim prepare-swagger.sh 
root@kmaster:/home/abhishek/goharbor/harbor# vim harbor.cfg 
root@kmaster:/home/abhishek/goharbor/harbor# vim prepare-swagger.sh 
root@kmaster:/home/abhishek/goharbor/harbor# 
root@kmaster:/home/abhishek/goharbor/harbor# 
# Grant privileges to the script
root@kmaster:/home/abhishek/goharbor/harbor# chmod 777 prepare-swagger.sh 
root@kmaster:/home/abhishek/goharbor/harbor# ./prepare-swagger.sh 
Doing some clean up...
Downloading Swagger UI release package...
--2019-02-23 16:03:29--  https://github.com/swagger-api/swagger-ui/archive/v2.1.4.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/swagger-api/swagger-ui/tar.gz/v2.1.4 [following]
--2019-02-23 16:03:30--  https://codeload.github.com/swagger-api/swagger-ui/tar.gz/v2.1.4
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘swagger.tar.gz’

1. swagger.tar.gz                                         [         <=>                                                                                                     ]   1012K   562KB/s    in 1.8s    

2019-02-23 16:03:36 (562 KB/s) - ‘swagger.tar.gz’ saved [1036338]

**#Untarring Swagger UI package to the static file path...**
Executing some processes...
Finish preparation for the Swagger UI.
# A directory with the name “src” was created in the parent directory. 
root@kmaster:/home/abhishek/goharbor/harbor# ls -ltrh
total 2.0M
-rwxr-xr-x 1 root root  5.7K Jan  4 16:53 install.sh
-rwxr-xr-x 1 root root   36K Jan  4 16:53 prepare
-rw-r--r-- 1 root root  731K Jan  4 16:53 open_source_license
-rw-r--r-- 1 root root   12K Jan  4 16:53 LICENSE
-rw-r--r-- 1 root root  5.5K Jan  4 16:53 docker-compose.yml
-rw-r--r-- 1 root root  1.5K Jan  4 16:53 docker-compose.notary.yml
-rw-r--r-- 1 root root   975 Jan  4 16:53 docker-compose.clair.yml
-rw-r--r-- 1 root root   939 Jan  4 16:53 docker-compose.chartmuseum.yml
drwxr-xr-x 4 root root  4.0K Feb 21 13:44 common
-rw-r--r-- 1 root root  7.9K Feb 21 14:27 harbor.cfg
-rw-r--r-- 1 root root  148K Feb 23 16:02 swagger.yaml
-rwxrwxrwx 1 root root  1.1K Feb 23 16:03 prepare-swagger.sh
-rw-r--r-- 1 root root 1013K Feb 23 16:03 swagger.tar.gz
root@kmaster:/home/abhishek/goharbor/harbor# cd ..
root@kmaster:/home/abhishek/goharbor# ls -lrth
Creating harbor-log ... done
-rw-r--r-- 1 root root 571M Jan  7 11:17 harbor-offline-installer-v1.7.1.tgz
drwxr-xr-x 3 root root 4.0K Feb 23 16:03 harbor
drwxr-xr-x 3 root root 4.0K Feb 23 16:03 src
root@kmaster:/home/abhishek/goharbor# cd -
Creating harbor-db ... done
Creating redis ... done
Creating registry ... done
Creating harbor-core ... done
Creating network "harbor_harbor-clair" with the default driver
Creating harbor-portal ... done
Creating harbor-jobservice ... done
Creating harbor-db ... 
Creating redis ... 
Creating harbor-adminserver ... 
Creating registryctl ... 
Creating registry ... 
Creating clair ... 
Creating chartmuseum ... 
Creating harbor-core ... 
Creating harbor-portal ... 
Creating harbor-jobservice ... 
Creating nginx ...

**Comment by abhishek-kumar0409** [comment]
These are the steps that I followed again in a fresh VM to setup the instance of harbor.However, I'm getting the same 404 error.

**Comment by abhishek-kumar0409** [comment]
@Seally10 : It will be of great help if you can share the config files or point me to the right config files.

**Comment by Seally10** [comment]
[docker-compose.zip](https://github.com/goharbor/harbor/files/2908728/docker-compose.zip)
if the directory “src” was created in the parent directory,i think the two lines should be configured as follows：
volumes:
      - ../src/ui/static/vendors/swagger-ui-2.1.4/dist:/usr/share/nginx/html/static/vendors/swagger
      - ../src/ui/static/resources/yaml/swagger.yaml:/usr/share/nginx/html/static/resources/yaml/swagger.yaml

 And you can  check the configuration according to the following steps：
1、**docker ps | grep -E 'harbor-portal|nginx ' | awk '{print $2, $NF}'**
goharbor/nginx-photon:v1.7.1 nginx
goharbor/harbor-portal:v1.7.1 harbor-portal

2、**docker exec -ti nginx /bin/bash**
root [ / ]# ps -ef|grep nginx 
root             1     0 0 04:49:10 ?     00:00:00 nginx: master process nginx -g daemon off;
nobody           7     1 0 04:49:10 ?     00:00:09 nginx: worker process
nobody           8     1 0 04:49:10 ?     00:00:33 nginx: worker process
nobody           9     1 0 04:49:10 ?     00:00:48 nginx: worker process
nobody          10     1 0 04:49:10 ?     00:01:18 nginx: worker process
nobody          11     1 0 04:49:10 ?     00:02:38 nginx: worker process
nobody          12     1 0 04:49:10 ?     00:02:44 nginx: worker process
nobody          13     1 0 04:49:10 ?     00:04:16 nginx: worker process
nobody          14     1 0 04:49:10 ?     00:04:38 nginx: worker process
root         22429 22420 0 05:51:04 pts/1 00:00:00 grep nginx
root [ / ]# **nginx  -V**
nginx version: nginx/1.13.8
built by gcc 6.3.0 (GCC) 
built with OpenSSL 1.0.2p-fips  14 Aug 2018 (running with OpenSSL 1.0.2q-fips  20 Nov 2018)
TLS SNI support enabled
configure arguments: --prefix=/etc//nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --error-log-path=/var/l
og/nginx/error.log --http-log-path=/var/log/nginx/access.log --add-module=../nginx-njs/njs-0.2.1/nginx --with-http_ssl_module --with-pcre --with-ipv6 --with-stream --with-http_auth_request_module --with-http_sub_module


root [ / ]# **cat /etc/nginx/nginx.conf**
......
upstream portal {
    server portal:80;
  }

......
location / {
      proxy_pass http://portal/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      # Add Secure flag when serving HTTPS
      proxy_cookie_path / "/; secure";

      proxy_buffering off;
      proxy_request_buffering off;
    }

......

**Based on the above information， i think  i should  add the two lines to the file docker-compose.yml under the section portal**

3、**docker exec -ti harbor-portal /bin/bash**
root [ / ]# ps -ef|grep nginx 
root             1     0 0 49:02 ?        00:00:00 nginx: master process nginx -g daemon off;
nobody           7     1 0 49:03 ?        00:00:05 nginx: worker process
root         22543 22534 0 56:39 pts/1    00:00:00 grep nginx
root [ / ]# **nginx -V**
nginx version: nginx/1.13.8
built by gcc 6.3.0 (GCC) 
built with OpenSSL 1.0.2p-fips  14 Aug 2018 (running with OpenSSL 1.0.2q-fips  20 Nov 2018)
TLS SNI support enabled
configure arguments: --prefix=/etc//nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --error-log-path=/var/l
og/nginx/error.log --http-log-path=/var/log/nginx/access.log --add-module=../nginx-njs/njs-0.2.1/nginx --with-http_ssl_module --with-pcre --with-ipv6 --with-stream --with-http_auth_request_module --with-http_sub_moduleroot [ / ]# **cat /etc/nginx/nginx.conf**

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}

root [ / ]# **ls -l  /usr/share/nginx/html/static/**
total 0
drwxr-xr-x 3 root root 17 2019-02-21 04:49 resources
drwxr-xr-x 3 root root 20 2019-02-21 04:49 vendors

if you can see the directory "static"  , it should be ok
Hope useful.

**Comment by abhishek-kumar0409** [comment]
Thanks much. I will test and update my progress.

**Comment by abhishek-kumar0409** [comment]
Hi @Seally10 ,

Thanks for your help. I was able to get the swagger-ui. The "src" directory was present in the parent directory of my offline installer. So, I had used `"../src/ui/static"` in the docker-compose.yml to refer the `src` directory. But, that didn't work for some reason. After copying the `src` directory to the present working directory(harbor). I was able to get the swagger-ui page... :+1:

**Comment by abhishek-kumar0409** [comment]
Please close this issue

**Comment by Seally10** [comment]
close #6948

**Comment by Seally10** [comment]
#6948
