### ISSUE TITLE
When adding a member by user with role of "Project Admin", there is no hint user list. 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#6951]
When adding a member by user with role of "Project Admin", there is no hint user list, but we still can add a member if we've known the full name of  it. This function should be there.

**Comment by zhoumeina** [comment]
After investigated, the get users api returns 403 in after the role refactor. 
![image](https://user-images.githubusercontent.com/4946616/53222507-00110880-36a9-11e9-9457-73d028ff4803.png)

**Comment by jwangyangls** [comment]
fix it
