### ISSUE TITLE
harbor已经使用nginx做反向代理，为什么还在core中实现了一个proxy？

### ISSUE THREAD

**Issue by Coyote5** [goharbor/harbor#6958]
有个问题请教各位大神，harbor已经使用nginx在前面做反向代理，为什么还在core中实现了一个proxy？搞不明白其中原理，望指点，谢谢！

**Comment by heww** [comment]
The proxy in core will do some check before send traffic to registry.

It will do the following things.

1. when harbor is read only mode will prevent user push image to registry.

2. `/v2/_catalog` api will only returns repositories which exist in harbor.

3. when notary is enabled and project is trust enabled but digest mismatched will prevent user pull image.

4. when clair is enabled and project vulnerable is enabled but the image severity is higher than project setting will prevent user pull image.


The more detail see the following code
https://github.com/goharbor/harbor/blob/c8c0ee623dc233dc4e191dd6eb2def7846a99c96/src/core/proxy/proxy.go#L41

**Comment by Coyote5** [comment]
@heww 谢谢!

**Comment by Coyote5** [comment]
@heww 上述这些功能，是否可以在registry向/service/auth申请鉴权时处理，这样registry的流量就可以不经过harbor_core。
