### ISSUE TITLE
docker registry not supporting GCS

### ISSUE THREAD

**Issue by paulczar** [goharbor/harbor#6959]
Expected: Docker registry should support GCS as a storage option.

Actual:
time="2019-02-18T16:37:52.076033578Z" level=info msg="debug server listening localhost:5001" 
panic: StorageDriver not registered: gcs

This is using the dev images.  with a bit of digging I think the wrong environment variables are being used to pass the build details to incude GCS.

In the docker registry [makefile](https://github.com/docker/distribution/blob/master/Makefile#L32) it has:
```
GO_TAGS=$(if $(BUILDTAGS),-tags "$(BUILDTAGS)",)
```

in the build scripts in [harbor](https://github.com/goharbor/harbor/blob/cd57f70f2f090136223a5ac52ee4c30e29240686/make/photon/registry/Dockerfile.binary#L4):

```
ENV DOCKER_BUILDTAGS include_oss include_gcs
```

I believe the latter needs to be set to `ENV BUILDTAGS include_oss include_gcs`

**Comment by reasonerjt** [comment]
@paulczar Are you using Harbor tile?  Could you let us know the version?

@wy65701436 I believe we tested it?  Could you double check?

**Comment by stonezdj** [comment]
The docker registry used by harbor tile 1.6.0 is v2.6.2, in branch release/2.6, [makefile](https://github.com/docker/distribution/blob/release/2.6/Makefile#L46): the env for build flag is still DOCKER_BUILDTAGS. 

I manually verified upload images to harbor tile instance with gcs storage, and can not reproduce this issue.

**Comment by stonezdj** [comment]
@paulczar the log is from the dev image of registry? not the image
```46245b5ebbcd        goharbor/registry-photon:v2.6.2-v1.6.0```

**Comment by wy65701436** [comment]
@paulczar it's a bug of registry v2.7.1, it will be fixed in v2.7.2. 

We'll bump up to v2.7.2 once it's released, just keep this issue open.

**Comment by paulczar** [comment]
Thanks, Sorry for the long delay.  This is trying to use the Helm Charts rather than the tile.

**Comment by paulczar** [comment]
I can confirm when I switch the image tags in helm chart from `dev` to `v1.7.1` this started working again.

**Comment by wy65701436** [comment]
I have updated the registry binary to v2.7.1-path-2819, which contains the fix of GCS storage driver issue.
