### ISSUE TITLE
Harbor with PKS UAA - does not find users

### ISSUE THREAD

**Issue by avasseur-pivotal** [goharbor/harbor#6960]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Using Harbor auth with UAA (from PKS UAA)
I have users in my UAA
```
uaac users | grep -4 tmp
      lastmodified: 2018-11-30T22:50:44.000Z
    name
    emails:
    -
      value: XXX
      primary: false
    groups:
    -
      value: 99a22f9f-9ed5-4829-bb5f-13d7d6089212
--
    active: true
    verified: true
    origin: uaa
    schemas: urn:scim:schemas:core:1.0
    username: XXX
    zoneid: uaa
    passwordlastmodified: 2018-11-30T22:50:44.000Z
  -
    id: 7d05a830-a652-48e2-aa1a-89ffa3830e2f
```

but then cannot add user to a project
(image)
![image](https://user-images.githubusercontent.com/5575656/52979708-23049980-33d7-11e9-9aed-78aee0e6c6d1.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.2 (Harbor tile)
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

I observe this message:
```
Feb 18 22:44:10 172.18.0.1 core[10285]: 2019/02/18 22:44:10 #033[1;44m[D] [server.go:2619] |  92.170.133.84|#033[42m 200 #033[0m|   5.944447ms|   match|#033[44m GET     #033[0m /api/projects/2/members   r:/api/projects/:pid([0-9]+)/members/?:pmid([0-9]+)#033[0m
Feb 18 22:44:13 172.18.0.1 core[10285]: 2019-02-18T22:44:13Z [WARNING] Failed to get pmid from path, error strconv.ParseInt: parsing "": invalid syntax
Feb 18 22:44:13 172.18.0.1 core[10285]: 2019-02-18T22:44:13Z [INFO] Failed to add project member, error: User does not exist
```

**Comment by reasonerjt** [comment]
It would be helpful if you can attach the harbor.cfg and log bundle.

Could you verify if you can login using the credential of users in the UAA instance?

**Comment by avasseur-pivotal** [comment]
```
harbor-app/04749678-83ae-4163-b9dd-e1d3d6b8e1f6:/var/vcap/jobs/harbor/bin# more alex.sh
#!/usr/bin/env bash
JOB_NAME=harbor
HARBOR_JOB_DIR=/var/vcap/jobs/$JOB_NAME
source /var/vcap/packages/common/utils.sh
source $HARBOR_JOB_DIR/bin/properties.sh
source $HARBOR_JOB_DIR/bin/uaa.sh
register_harbor_uaa_client
```
[Tue Feb 19 08:37:41 UTC 2019] Harbor UAA client 'harbor' is successfully registered!

and harbor.cfg:
```
auth_mode = uaa_auth

#The following attributes only need to be set when auth mode is uaa_auth
uaa_endpoint = https://api.x:8443
uaa_clientid = harbor
uaa_clientsecret= x
uaa_verify_cert = true
uaa_ca_cert = /data/cert/uaa_ca.crt
```

would there be some debug log I could turn on?

**Comment by reasonerjt** [comment]
@avasseur-pivotal Are you using a published Harbor tile?  If the answer is yes it is suggested on open a ticket in jira.

**Comment by reasonerjt** [comment]
Close due to inactivity.
