### ISSUE TITLE
does harbor use db postgres in postgresql?

### ISSUE THREAD

**Issue by yifanyou** [goharbor/harbor#6964]
I find there are some tables in postgres.public. don't know they come from.

I want to migrate harbor dbs to other places, can I only migrate registry, notaryserver,notarysigner? 

![image](https://user-images.githubusercontent.com/8372481/53006713-b3db8380-3470-11e9-9e84-efa6358d0ec8.png)

**Comment by stonezdj** [comment]
Need to migrate postgres, it is used by clair

**Comment by yifanyou** [comment]
> Need to migrate postgres, it is used by clair

I saw values.yaml in harbor 0.3.2, clairDatabase default value is clair. So, if install harbor 0.3.2, i can migrate db postgres.public to db clair.public?

**Comment by reasonerjt** [comment]
You need to migrate everything otherwise the API may break.
