### ISSUE TITLE
Consistent error handling for API

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6967]
So far, we have two sets of functions to handle http error.
1, https://github.com/goharbor/harbor/blob/master/src/common/api/base.go
2, https://github.com/goharbor/harbor/blob/master/src/core/api/base.go

We should merge them, and unify the error message format with json.

**Comment by SDBrett** [comment]
The admin server base API has it's own error handling as well. Does this fall in scope of your issue?

https://github.com/goharbor/harbor/blob/master/src/adminserver/api/base.go

**Comment by wy65701436** [comment]
As the new APIs of replication has been introduced by code refactor, the PR needs to be updated.

**Comment by wy65701436** [comment]
close it as code complete.
