### ISSUE TITLE
Configure LDAP Group Admin DN -- doc needed.

### ISSUE THREAD

**Issue by Mr-iX** [goharbor/harbor#6976]
Is it possible to configure the "LDAP Group Admin DN" field in the harbor.cfg file instead of the webui?
I cannot find this option in the harbor.cfg file

**Comment by stonezdj** [comment]
Yes, by "ldap_group_admin_dn", but it belongs to user settings, we are going to move all user settings to web ui and can not be configed by harbor.cfg in the future release.

**Comment by Mr-iX** [comment]
Ok thanks, but how can I automate the installation in the future, when these settings can only be configured in the web ui?

**Comment by obeyler** [comment]
I agree with Mr-iX if you remove it from harbor.cfg we will not able anymore to automate the install
please don't do that

**Comment by reasonerjt** [comment]
@Mr-iX @obeyler 
In upgrade the configurations remain.
In fresh install, you can automatically install and call the configurations API to set the configurations.

**Comment by obeyler** [comment]
Could you explain more how to do with "call the configurations API to set the configurations" in fresh install
/reopen

**Comment by reasonerjt** [comment]
We'll add more doc and FaQ before 1.8 is released.

**Comment by stonezdj** [comment]
Fixed in PR #7479

**Comment by obeyler** [comment]
Sorry @stonezdj , I still don't understand why LDAP Group Admin DN is a user setting...
if this parameter allows (as I understand) to define the group of admin in LDAP, user should not be allowed to set it.
If it was, simple user can simply set his own group to automatically becomes admin.

**Comment by guidopatanella** [comment]
I agree with @obeyler . @stonezdj , please clarify. All LDAP related settings are to be on harbor.cfg. BTW, the default harbor.cfg does not show the "ldap_group_admin_dn" as part of the configuration, so it should be added at least in commented-out form.
