### ISSUE TITLE
Proposal: support LDAP together with bot accounts

### ISSUE THREAD

**Issue by quickwind** [goharbor/harbor#698]
首先我们想我们的成员能够通过LDAP进行authenticate，但是我们的平台也需要公共账号能够进行image拉取和管理，毕竟我们的员工账号密码比较敏感而且每2个月就要强制修改，能否在LDAP的auth_mode的基础上也支持建立bot account来方便系统的集成？Bot account应该只能由项目管理员权限的用户创建和删除 （以及修改密码）。

如果能实现这样的功能，必将对企业用户非常有用。多谢！

**Comment by reasonerjt** [comment]
The default admin is not authenticated via LDAP, could you use this account for such purpose?

**Comment by quickwind** [comment]
@reasonerjt 理论上可以，但是不安全，我们想要的是分项目创建bot account，这样不同的bot account只有具体项目的具体权限，比如bot account 1只有read权限到projectA，但是有R/W权限到projectB

**Comment by reasonerjt** [comment]
I see your point, we'll consider to implement this, but currently there's ETA for this.

**Comment by quickwind** [comment]
@reasonerjt we may consider implementing this ourselves, but I am new to Go, what tools used in your development? maybe  a developer guide would be good...

**Comment by reasonerjt** [comment]
I use vim-go as the editor.
For the feature you asked you can make update to **auth/ldap/ldap.go** 

But details you may need to figure out by looking at the code...

**Comment by quickwind** [comment]
@reasonerjt I finished coding and testing of this feature, simply added a flag in user model to indicate whether it is a service account or regular user, and for service account its email address can be empty and no check for uniqueness. Also service account can be created in LDAP mode. working fine. 

Is it possible for me to create a PR for this?

**Comment by bstevenson** [comment]
Any plans to support service accounts or merge this effort into master https://github.com/vmware/harbor/commit/182d65f79e51b139459f3c20ea433b8827d92710 ?
It'd be great to use ldap for real users, but manage service accounts programmatically in the harbor db.

**Comment by reasonerjt** [comment]
@wy65701436  could you triage? seems after we deliver robot account this can be closed?

**Comment by renmaosheng** [comment]
@quickwind we have implemented the robot account in 1.8, it can support your case, please have a try.

**Comment by reasonerjt** [comment]
I'm closing this one as the robot account is implemented in 1.8
