### ISSUE TITLE
Ipv6 registry?

### ISSUE THREAD

**Issue by symgryph** [goharbor/harbor#6982]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I cannot use ipv6 registries, I have to revert to ipv4 to use docker login.

**Describe the solution you'd like**
Working ipv6 would be terribly nice. I would be happy to beta-test.

**Describe the main design/architecture of your solution**
Ipv6 is the future, and we don't need evil things like nat or running out of addresses. 

**Describe the development plan you've considered**
Not too much on this, just working ipv6 within docker registry.

**Additional context**

**Comment by symgryph** [comment]
Good to talk to you on the meeting today. I had setup a ipv6 only stack with redhat 7.6 runnning docker CE version Docker version 18.09.2, build 6247962.  Relatively new to docker and ipv6, but was trying since I have a /64/s worth of ipv6 addresses and only 5 public ipv4 addresses.

**Comment by symgryph** [comment]
The webserver worked fine, just couldn't get images from theregistry.

**Comment by renmaosheng** [comment]
Hi Symgryph,
       could you please upload the related logs? /var/log/harbor/*  thanks.

**Comment by steven-zou** [comment]
Transfer all the requirements to @xaleeks for tracking.

**Comment by supereagle** [comment]
@steven-zou Does Harbor have any plan to support IPv6?

**Comment by xaleeks** [comment]
We will look into this for the next release

**Comment by yakbulut** [comment]
Hi all,

V6 support for Harbor would be a great feature. Just wondering if it is currently in a roadmap and targeted for a release ? Thank you.

**Comment by vhosakot** [comment]
I deployed harbor with IPv6 on k8s using helm today and see it's not working - seeing following mis-configurations in harbor `1.3.1` tag with IPv6:

1. `EXT_ENDPOINT` in configmap should be
    `https://[2001:420:293:246d:f816:3eff:fedd:6570]` for IPv6.

    ```
    $ kubectl get cm -n=harbor harbor-core -o yaml | grep EXT_ENDPOINT
      EXT_ENDPOINT: https://2001:420:293:246d:f816:3eff:fedd:6570
    ```
    https://github.com/goharbor/harbor-helm/blob/v1.3.1/templates/core/core-cm.yaml#L30

2. Auth token's `realm` in configmap should be
    `realm: "https://[2001:420:293:246d:f816:3eff:fedd:6570]/service/token` for IPv6.
    ```
    $ kubectl get cm -n=harbor harbor-registry -o yaml 
    ...
        auth:
          token:
            issuer: harbor-token-issuer
            realm: "https://2001:420:293:246d:f816:3eff:fedd:6570/service/token"
    ...
    ```
    https://github.com/goharbor/harbor-helm/blob/v1.3.1/conf/notary-server.json#L22

3. `/etc/nginx/nginx.conf` in `harbor-portal` pod should have `listen [::]:8080` for IPv6.

    ```
    $ kubectl exec harbor-portal-5bf5d9b858-4p84f -n=harbor -- grep 8080 /etc/nginx/nginx.conf
    ...
            listen 8080;
    ...
    ```
    https://github.com/goharbor/harbor-helm/blob/v1.3.1/templates/nginx/configmap-http.yaml#L46

    https://github.com/goharbor/harbor-helm/blob/v1.3.1/templates/nginx/configmap-https.yaml#L207

@yakbulut (who commented here in https://github.com/goharbor/harbor/issues/6982#issuecomment-598506376) and I would like to help add IPv6 support in harbor - what is the process to do it?

**Comment by Frankkkkk** [comment]
Hi
we managed getting it to work (proxy-mode) by changing both helm's configmaps:
```diff
--- a/templates/portal/configmap.yaml
+++ b/templates/portal/configmap.yaml
@@ -19,7 +19,7 @@ data:
         scgi_temp_path /tmp/scgi_temp;
         server {
     {{- if .Values.internalTLS.enabled }}
-            listen {{ template "harbor.portal.containerPort" . }} ssl;
+            listen [::]:{{ template "harbor.portal.containerPort" . }} ssl;
             # SSL
             ssl_certificate /etc/harbor/ssl/portal/tls.crt;
             ssl_certificate_key /etc/harbor/ssl/portal/tls.key;
@@ -30,7 +30,7 @@ data:
             ssl_prefer_server_ciphers on;
             ssl_session_cache shared:SSL:10m;
     {{- else }}
-            listen {{ template "harbor.portal.containerPort" . }};
+            listen [::]:{{ template "harbor.portal.containerPort" . }};
     {{- end }}
             server_name  localhost;
             root   /usr/share/nginx/html;

```

**Comment by lindhe** [comment]
Seems related to  #11399

**Comment by Frankkkkk** [comment]
unstale
