### ISSUE TITLE
Harbor-Ldap connection issue

### ISSUE THREAD

**Issue by jojo123678** [goharbor/harbor#6984]
Can not able to establish Ldap connection in my test server and it has configured same as production server.
For production server its working fine.

Below are the configuration details:

LDAP URL
ldap://10.3.32.11
LDAP Search DN=CN=svc harbor,CN=Users,DC=VPN,DC=Local
LDAP Base DN=ou=vpnusers,dc=vpn,dc=local
LDAP Filter=(&(objectCategory=user)(memberOf=CN=appHarbor,ou=vpnusers,dc=vpn,dc=local))
LDAP UID=sAMAccountName

Kindly help me to resolve this issue.
_Thanks.

**Comment by zhoumeina** [comment]
@stonezdj , could you please help on this?

**Comment by stonezdj** [comment]
If the test server and product server use identical configure, please retype the LDAP admin password when you test connection.

**Comment by jojo123678** [comment]
Thanks for the reply :) its working now..


-Jyoti
