### ISSUE TITLE
Windows image pushing failed in harbor of master branch

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#6987]
Windows image pushing failed in harbor of master branch but success in 1.7.1 version.

After download registry from 2.7.1 to 2.6.2, Windows image pushing works.

Here is the log of registry 2.7.1 [container.log](https://github.com/goharbor/harbor/files/2888329/container.log)

**Comment by reasonerjt** [comment]
@heww Could you clarify what cli tool did you use to push the image?  Is it docker?  What error did you see from the cli?

**Comment by heww** [comment]
There is an issue about it [docker/distribution#2795](https://github.com/docker/distribution/issues/2795), this can be fixed by disable validation in registry config.

PR for harbor-helm #168 opened.

**Comment by reasonerjt** [comment]
@heww it's a wrong link for the PR.  You need to use the complete URL as it's in a different repo...

**Comment by heww** [comment]
@reasonerjt The link above is fixed. And PR fixed to harbor opened at #6993
