### ISSUE TITLE
harbor1.3.0重启时，发现ui组件加载大量数据导致超时，且ui组件不断重启。

### ISSUE THREAD

**Issue by piliwen** [goharbor/harbor#6989]
压测harbor1.3.0版本，推送10000个镜像。在数据量较多的情况下重启harbor时，docker service ls 查看运行组件状态，发现ui 组件一直显示 0/1未启动，且组件不断重启中。查看/var/log/harbor/ui.log显示：[INFO] start  syncing repositories from registry to DB ... 另外一行显示[DEBUG] [tokenautorizer.go:197] :scopses parsed from request :repository:catalog:*

**Comment by heww** [comment]
Can you share the script of push 10000 images to harbor with us?

**Comment by piliwen** [comment]
#!/bin/bash  

#此块作用为控制Dockerfile层数  
function rand(){  
    min=$1 #获取第一个参数 
    max=$(($2-$min+1))  #取第二个参数减去最小值加1
    num=$(date +%s%N)  #时间戳微秒
    echo $(($num%$max+$min))  
}  
  
#rnd=$(rand 1 5)  #传递2个参数1和5

docker login $1 

for((v=1;v<="$4";v++));
do
rnd=$(rand 1 5)
#判断是否传参，此处暂不对传参做限制
	if [ -z $1 ]; then
		#不带参数提示,脚本结束
		echo "脚本后必须带参数，镜像仓库地址，私仓名，镜像名称，镜像个数，上传并发数；如：push.sh  ys-beta.eptok.com:80  test01 100000"
	#带参数执行下面内容
	else
		dksve=/usr/lib/systemd/system/docker.service
	
		grep "$1" $dksve >> /dev/null
		#判断$dksve这个文件内是否存在参数1的镜像仓库地址
		if [ $? -eq 0 ]; then
			#有即直接提示
			echo "仓库地址已添加信任"
		#没有即执行以下操作
		else
			#将镜像仓库地址添加到$dksve文件的ExecStart这行末
			sed -i "/^ExecStart=.*$/s// & --insecure-registry $1 /g" $dksve 
			systemctl daemon-reload
			systemctl restart docker
		fi
	
		mkdir pushdir
	
		pr="./pushdir"
		pd="./pushdir/Dockerfile"
		#以下几行为写Dockerfile文件
		echo "FROM busybox"  >> $pd
		
		for((i=1;i<="$rnd";i++));
		do
			#通过dd命令生成50M文件
			echo "RUN dd if=/dev/zero of=file$i bs=1024k count=50" >> $pd
		done
		#登录仓库
	
		docker build -t $1/$2/$3:v$v ./pushdir
	
		docker push $1/$2/$3:v$v
		docker rmi $1/$2/$3:v$v
	       
		rm -rf $pr
		fi
done

**Comment by piliwen** [comment]
并发推送暂未调试，可以通过多次脚本执行实现并发

**Comment by piliwen** [comment]
![image](https://user-images.githubusercontent.com/20899895/53312505-4906ce00-38f0-11e9-8401-063bd5f3d51e.png)
![image](https://user-images.githubusercontent.com/20899895/53312537-60de5200-38f0-11e9-85a3-6814db636c34.png)
页面展示时非常慢。ecrpush2仓库显示镜像2000个，5个仓库10000个镜像

**Comment by piliwen** [comment]
已解决！因harbor ui 容器设置了健康检查（2分钟），健康检查时间内syncing数据同步不完，导致ui容器不断重启。经修改健康检查时间，最终数据同步完成，ui 容器运行正常。

**Comment by reasonerjt** [comment]
Thanks, closing.
