### ISSUE TITLE
Deleting tag deletes multiple tags instead of one

### ISSUE THREAD

**Issue by vasicvuk** [goharbor/harbor#6994]
**Expected behavior and actual behavior:**

If i have two tags that have same layers and delete one other one is deleted too.

This is a critical issue since you can tag your tested Development image as Production one. Then after you want to delete Development image it will also delete the one that is needed for Production.

**Steps to reproduce the problem:**

Push image to Harbor. Push the same image with the different tag. Go in Harbor admin panel. Remove one tag and the other tag will be removed too.

**Versions:**
- harbor version: 1.7.1
- docker engine version: 18.06.1-ce
- docker-compose version: 1.17.1

I can see that the issue was discussed here https://github.com/goharbor/harbor/issues/2663 
I think this explanation is not good enough since the other registries have ability to kill only one tag such as: Docker Trusted Registry and Nexus OSS without affecting other tags

If there is no ability to implement this then removing Tag from UI should be removed also.

**Comment by zhoumeina** [comment]
@wy65701436 @ywk253100 ， who can take some time to take care of this?

**Comment by reasonerjt** [comment]
This seems a limitation of upstream registry that when 2 tags have same `sha256` digest.
#4868 suggest a improvement in UI to help user understand the impact.

**Comment by vasicvuk** [comment]
So you are limiting your solution to something that  is not good ?

**Comment by xaleeks** [comment]
we're working on a solution for this, please ping me to share requirements and use cases. xalex@vmware.com

**Comment by xaleeks** [comment]
> So you are limiting your solution to something that is not good ?

No, it's a limitation / inherent behavior of the docker distribution, we are of course aiming to improve the solution by transposing another layer on it.

**Comment by vasicvuk** [comment]
@xaleeks That is great :) i will send you an email with our use cases
