### ISSUE TITLE
Issues in Makefile 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7000]
1. We should not use robot to package and publish build
2. Some vars don't seem to be used, such as `COMPILETAG`, `MAKEDEVPATH`, `UIVERSIONTAG`
3. There are duplicated variables in `/Makefile` and `/make/photon/Makefile` seems the `/make/photon/Makefile` can only be called from `Makefile` so such duplication is not needed.
4. When there's failure in `/make/photon/Makefile` in target `build:` in `/Makefile` the process should be stopped.

**Comment by QiuToo** [comment]
[root@harbor-code harbor-2.3.5]# ls  -l  /usr/bin/spectral
-rwxr-xr-x. 1 root root 57043724 12月  7 07:45 /usr/bin/spectral
[root@harbor-code harbor-2.3.5]# make  package_offline  SPECTRAL_VERSION=v5.9.1
fatal: Needed a single revision
substitute the prepare version tag in prepare file...

Note: golang version: 1.17.5

Note: docker version: 19.03.8

Note: docker-compose version: 2.2.3
Sending build context to Docker daemon  74.66MB
Step 1/6 : ARG GOLANG
Step 2/6 : FROM ${GOLANG}
 ---> e5b4455acc93
Step 3/6 : ARG SPECTRAL_VERSION
 ---> Using cache
 ---> b6cd24873446
Step 4/6 : RUN curl -fsSL -o /usr/bin/spectral https://github.com/stoplightio/spectral/releases/download/$SPECTRAL_VERSION/spectral-linux && chmod +x /usr/bin/spectral
 ---> Running in 8a0a5153abae
==================
我在源码编译安装harborv2.3.5版本时，一直处于step 4/6这里，我根据Makefile中SPECTRAL_VERSION=v5.9.1
手动下载spectral放到/usr/bin/spectral，并给予可执行权限，这个问题一直困扰着我！
