### ISSUE TITLE
pull strategy for replication

### ISSUE THREAD

**Issue by Shraa** [goharbor/harbor#7005]
I need to place one harbor in the DMZ, and the second in a protected area. Internet access is possible from the DMZ only. The connection between DMZ and protected area can be initiated from protected area only. I need to replicate from DMZ to protected area this types of data: docker images, chartmuseum's data, Clair security base and Notary signature database.

In the user guide, I don't see how to do it.

Do you plan to implement a pull strategy for replication all this data between two harbor nodes?

**Comment by zhoumeina** [comment]
@ywk253100 , is the replication NG can meet this requirement? @Shraa , pull based replication is under developing target 1.8.

**Comment by ywk253100** [comment]
The pull mode replication for images and charts are described in the proposal: https://github.com/goharbor/community/blob/master/proposals/Content-Replication-ng.md. 
And the development is in progress.

But the Clair security database and Notary signature database are not included.

**Comment by renmaosheng** [comment]
@Shraa have you got time to read the proposal? would this satisfy your requirements? comments are appreciated.

**Comment by Shraa** [comment]
@renmaosheng I need clair security base and notary signature database also, but not docker images and chartmuseum data only

**Comment by coolacid** [comment]
I'd also like to voice my request for this. I also would like to see Clair support for pulled repos.

My use case includes using images from docker-hub, my goal is to do timed check/pulls from docker hub registry into a local harbor instance, preform the clair checks on the image for reporting and make it available on our internal network. 

This solves a few things for us:
1. Allows us to monitor vulnerability issues with upstream images
2. Provides a local cache of images so we don't need to reach out to the internet for every instance
3. Hopefully identify when upstream images are released (via a nightly report of pulls?) for process management.

**Comment by coolacid** [comment]
Looks like Harbor 1.9.0 has scheduled pull based replication. I just played with it and does almost everything I need.

**Comment by renmaosheng** [comment]
@coolacid Thanks for the feedback!

**Comment by xaleeks** [comment]
Seems everything requested here is covered by latest version of Harbor
