### ISSUE TITLE
Unable to configure scan time for vulnerability

### ISSUE THREAD

**Issue by pureshine** [goharbor/harbor#7006]
harbor version: dev 
affect: Timepicker cannot be displayed when daily is selected
![image](https://user-images.githubusercontent.com/40712758/53235778-a111ba80-36cd-11e9-8575-cd60aa33f18f.png)
and should be
![image](https://user-images.githubusercontent.com/40712758/53235740-85a6af80-36cd-11e9-9984-797fe78c3574.png)

Get the value of scan_all_policy in the configuration is null
![image](https://user-images.githubusercontent.com/40712758/53235484-e1246d80-36cc-11e9-8c7c-472c64f71b98.png)
and should be
![image](https://user-images.githubusercontent.com/40712758/53235497-eb466c00-36cc-11e9-9c70-8f5449838364.png)

**Comment by zhoumeina** [comment]
@pureshine, could you please triage, and fix it if possible.

**Comment by stonezdj** [comment]
Discussed with @wy65701436 , this config setting is going to be removed. 
close
