### ISSUE TITLE
Clair scan loop

### ISSUE THREAD

**Issue by kumy** [goharbor/harbor#7028]
Since we have upgraded from harbor 1.5.2 to 1.7.1, we have a problem with clair lopping over the same docker image and layers, that finally full postgres database with connexions and reach `max_connexion`.

**Expected behavior and actual behavior:**
We expect clair to not scan the same set of layers in an infinite loop.

**Steps to reproduce the problem:**
Quite difficult to provide a reproducible context as it comes from a long harbor run, upgraded to follow newer versions :/

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.1]
- docker engine version: [18.09.2]
- docker-compose version: none - deployed on swarm

**Additional context:**
Some logs extract that repeat infinitely:
* https://gist.github.com/kumy/6053baab5c2235114abc5a83ca491d7c
* https://gist.github.com/kumy/508d1648082bbf13dce0eb8856a1ad82
* https://gist.github.com/kumy/eb180469169963fbb2c789a58f73c192
* https://gist.github.com/kumy/c5df37e00a6d55f402ae276c4f55836c

Where should I look (database/files/etc) to stop this infinite loop?

**Comment by kumy** [comment]
I have updated the `properties` table and set `with_clair` to false, then restarted the whole stack, but clair is still processings layers in loop.

**Comment by reasonerjt** [comment]
@kumy Was it fixed?

**Comment by kumy** [comment]
@reasonerjt At first I thought it was fixed, but problem started again the next day. At the moment we have stopped the `clair` container :( didn't took time to look at it closer.

**Comment by reasonerjt** [comment]
@kumy please chime in #7316
