### ISSUE TITLE
Miscellaneous improvements on robot account get API

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#7029]
A couple of improvement suggestions on the robot account GET API result:

1. rename the “expiresat” as “expires_at” in the robot account info
2. in general it would be good to include the robot account access info as part of the robot account info

  {
    "id": 1,
    "name": "robot$robot-test",
    "description": "robot account test",
    "project_id": 2,
    "expiresat": 1553718775,
    "disabled": false,
    "creation_time": "2019-02-25T20:32:55.874353Z",
    "update_time": "2019-02-25T20:32:55.874353Z"
  }

**Comment by reasonerjt** [comment]
@ericvmw  for `2`, I agree it's do-able.  But it's different from `expire_at` and we may not really have to do it.

Access info is encoded in the token and it doesn't require user to take any action, it cannot by updated.  If user wanna know it he can decode the token and see, or he can add this info in the description while creating robot account

**Comment by ericvmw** [comment]
@reasonerjt we don't necessarily require 2 for our case since we don't expect different access rights, I just feel it would be more friendly for user to know what the robot account can do, without having to track how it was created or knowing how to decode the token.

**Comment by wy65701436** [comment]
#1 is fixed.
#2, keep the current solution.
Feel free to reopen it if still have the concern on #2.
