### ISSUE TITLE
Missing metadata item "verify_remote_cert" when putting it by api/configurations

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7038]
When perform putting data by api/configurations, metadata item "verify_remote_cert" can't be pushed, error is as below:
    configure item is not defined in metadata, item name: verify_remote_cert

Body is:

{
"email_ssl": true, 
"email_identity": "string", 
"auth_mode": "db_auth", 
"email_username": "emailuser", 
"self_registration": false, 
"scan_all_policy": 
{"parameter": 
{"daily_time": 0}, 
"type": "none"}, 
"verify_remote_cert": false, 
"read_only": false, 
"token_expiration": 40.0, 
"project_creation_restriction": "everyone", 
"email_port": 2220.0, 
"email_host": "emailserver", 
"email_from": "emailfrom", 
"email_insecure": true
}

**Harbor Version: Version v1.8.0-34057707**

**Comment by reasonerjt** [comment]
I think this can be discovered in UT?

**Comment by stonezdj** [comment]
Discuss it with wenkai, this configure option is not required.
