### ISSUE TITLE
Hard coded string in config item definition

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7040]
Take LDAP URL as an example.

When reading it it's using a const:
https://github.com/goharbor/harbor/blob/master/src/core/config/config.go#L196
But here it's hard coded:
https://github.com/goharbor/harbor/blob/master/src/common/config/metadata/metadatalist.go#L101

Let's fix it to avoid future inconsistency.

Additionally, how about move the const of config item names into package `common/config`?

**Comment by stonezdj** [comment]
fixed #7495
