### ISSUE TITLE
jobservice transfer PullManifest get wrong digest, not latest digest but last one

### ISSUE THREAD

**Issue by tangxiaodon89** [goharbor/harbor#7041]
I want use jobservice transfer newest images to other habor immediately.
But the image of the transmission is the last one, not the latest one.
harbor version v1.6.0
docker version 18.03.1-ce

this is my test case
![image](https://user-images.githubusercontent.com/11000963/53552295-f6d6de80-3b75-11e9-9de5-ce0b590f0178.png)

first transfer log.
![image](https://user-images.githubusercontent.com/11000963/53552333-0ce49f00-3b76-11e9-92de-42138e1252af.png)

second transfer log.
![image](https://user-images.githubusercontent.com/11000963/53552362-20900580-3b76-11e9-8c4d-3675bdf06e88.png)

 in source harbor the degist is new
![image](https://user-images.githubusercontent.com/11000963/53552398-38678980-3b76-11e9-8981-cfa5c586dbac.png)

in target harbor the degist is last one
![image](https://user-images.githubusercontent.com/11000963/53552622-b0ce4a80-3b76-11e9-8221-017678a0a00b.png)

The docker registry manifest may not update immediately, and so the method pullManifest get result of last time.
![image](https://user-images.githubusercontent.com/11000963/53552692-dbb89e80-3b76-11e9-8b61-bd11faeaa513.png)

**Comment by reasonerjt** [comment]
@tangxiaodon89 what kind of trigger are you using when you reproduce this?
Let's check if this is a known issue in upstream registry?

**Comment by tangxiaodon89** [comment]
Trigger model is immediate.
![image](https://user-images.githubusercontent.com/11000963/53859800-d4334280-4019-11e9-84fb-4851a13aaa5a.png)

The image was create at 3/5/2019, 10:52 AM
Degist is sha256:7cf7e30db4202121b6c740b4c8de9ce8d53917386d96d4abf830006596541460
![image](https://user-images.githubusercontent.com/11000963/53860031-95ea5300-401a-11e9-9321-113183a02947.png)

The tag staging was pushed once at 3/5/2019, 4:36 PM
Got Degist sha256:27408f9413f0518bc2dc38ae67015ee5543bfeb59ff52e0b62bdbe92d78d707b  from source registry, this time is wrong.
![image](https://user-images.githubusercontent.com/11000963/53860158-0a24f680-401b-11e9-8668-210f71169378.png)

The same tag staging was pushed twice at 3/5/2019, 4:40 PM
Got Degist sha256:7cf7e30db4202121b6c740b4c8de9ce8d53917386d96d4abf830006596541460from source registry, and this time was right.
![image](https://user-images.githubusercontent.com/11000963/53860251-5c661780-401b-11e9-96e5-19308bfebbe8.png)

The same image pushed twice, the first time transfer the old degist, the secret time transfer the current degist.

**Comment by koulq** [comment]
@reasonerjt Hello, has this problem been solved in the recently released version 1.8?

The storage medium of docker registry is “ceph”
