### ISSUE TITLE
Need Harbor online installer for 1.7.3

### ISSUE THREAD

**Issue by trisberg** [goharbor/harbor#7056]
Where can I find the Harbor online installer for versions 1.7.2 and 1.7.3?

**Comment by trisberg** [comment]
actually, I need a release that contains the #6689 fix

**Comment by wy65701436** [comment]
The fix will be included in v1.8.0. Hopefully, in May, we can reach the release.

**Comment by trisberg** [comment]
Thanks for the info, although that's a long time to wait for a fix ;)

**Comment by reasonerjt** [comment]
@trisberg as an update based on the feedback of community this commit is cherry picked to 1.7 branch and will be released in v1.7.5 this week if things go well.
Stay tuned

**Comment by trisberg** [comment]
@reasonerjt Excellent, thank you!
