### ISSUE TITLE
manifest for goharbor/harbor-registryctl:v1.7.4 not found

### ISSUE THREAD

**Issue by giabar** [goharbor/harbor#7067]
Hi all,

I'm trying to run Harbor 1.7.4 but the harbor-registryctl:v1.7.4 is missing from Docker Hub.
It seems that only the following tags are present:

dev
v1.7.0
v1.7.1

**Comment by nicoherbigde** [comment]
Same to me

**Comment by wy65701436** [comment]
@giabar thanks for pointing, I have fixed it. Please retry to install the v1.7.4.
