### ISSUE TITLE
VIC appliance upgrade 1.3.1 to 1.5.0 fails because database hasn't been mounted for migration

### ISSUE THREAD

**Issue by jitinkumar2018** [goharbor/harbor#7074]
vCenter Server version: 6.5 p03
Embedded or external PSC: No
Filename of the OVAs you deployed: vic-v1.3.1-3409-132fb13d.ova , vic-v1.5.0-6915-e18e6647.ova
How was the OVA deployed? ovftool
Does the VIC appliance receive configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application, Upgrade

**Expected behavior and actual behavior:**
Appliance should have upgraded from VIC 1.3.1 to VIC 1.5.0 but it failed

**Steps to reproduce the problem:**
Reached Scale on VIC 1.3.1 (50 VCH's deployed with 50 containers each). Created 50 projects and added all VCH's to 'project-p01'.
Then deployed VIC 1.5.0 and ran upgrade script once it initialized. 
- Detected old appliance's version correctly
- Migration of disks was successful
- Appliance registration was successful
- VIC UI plugin upgrade failed
- Admiral restarted successfully
- Harbor Upgrade Fails 
`No database has been mounted for the migration. Use '-v' to set it in 'docker run'.
Fail to validate: please make sure your DB auth is correct`

/etc/vmware/version:
appliance=v1.5.0-6915-e18e6647
harbor=harbor-offline-installer-v1.7.1.tgz
engine=vic_v1.5.0.tar.gz
admiral=vmware/admiral:vic_v1.5.0 33a6598a5c0d
vic-machine-server=gcr.io/eminent-nation-87317/vic-machine-server:v1.5.0 b52893e49ff8

**Additional context:**

* **Upgrade Log :** 
[upgrade.log](https://github.com/goharbor/harbor/files/2929408/upgrade.log)
Appliance Logs: 
[vic_appliance_logs_2019-03-05-05-22-47.tar.gz](https://github.com/goharbor/harbor/files/2929409/vic_appliance_logs_2019-03-05-05-22-47.tar.gz)

I shall send the environment details on slack

@renmaosheng @luwang-vmware

**Comment by DanielXiao** [comment]
Database folder is empty but upgrade log show it was migrated successfully.
```
ls -la /storage/db/harbor/database/
total 8
drwxr-xr-x 2 root root 4096 Mar  4 19:50 .
drwxr-xr-x 3 root root 4096 Mar  4 19:50 ..
```

**Comment by luwang-vmware** [comment]
@jitinkumar2018  Would you please share how you do upgrade?

I checked that  in 1.5.0 the upgrade path from vic1.3.1 --> vic1.5.0 is PASS in our testing. https://vic-jenkins.eng.vmware.com/view/Scenario/job/vic-product-release-scenario-test/56/robot/report/log.html#s1-s4-s3

**Comment by jitinkumar2018** [comment]
I have followed the steps in https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/upgrade_appliance.html.
Deploy new appliance, wait until initialization completes and then run /etc/vmware/upgrade/upgrade.sh.

**Comment by DanielXiao** [comment]
There are data loss after disk migration, below is from old appliance:
```
root@vic-st-h2-132 [ ~ ]# du -sh /storage/log
2.6M	/storage/log
root@vic-st-h2-132 [ ~ ]# du -sh /storage/data
124M	/storage/data
root@vic-st-h2-132 [ ~ ]# du -sh /storage/db
445M	/storage/db
```
And below are volume sizes on new appliance:
```
root@vic-st-h2-183 [ ~ ]# du -sh /storage/log
636K	/storage/log
root@vic-st-h2-183 [ ~ ]# du -sh /storage/data
104M	/storage/data
root@vic-st-h2-183 [ ~ ]# du -sh /storage/db
28K	/storage/db
```
I manually copied the same vmdk from old appliance through both vSphere web client and govc command, the new vmdk sizes are smaller than original ones and the new appliance can not detect these new attached block devices. I am not sure if it is a vSphere issue for copying vmdk.

**Comment by reasonerjt** [comment]
Closing as this has been fixed.
