### ISSUE TITLE
Upgrade issue v1.7.1 to v1.7.4

### ISSUE THREAD

**Issue by tanimraja1** [goharbor/harbor#7081]
I am trying to upgrade Harbor v1.7.1 to v1.7.4 and I am following the official harbor migration [guide.](https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md)
I am getting the following error while docker run-
`docker run -it --rm -v harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.7.4 --cfg up`
`Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Traceback (most recent call last):
  File "./migrator.py", line 232, in <module>
    main()
  File "./migrator.py", line 178, in main
    db_migrator = DBMigrator(commandline_input.target_version)
  File "./migrator.py", line 34, in __init__
    conf.write(open(path).read())
IOError: [Errno 21] Is a directory: '/harbor-migration/harbor-cfg/harbor.cfg'`

Can anyone please help me on this?

**Comment by tanimraja1** [comment]
Still waiting for some sort of help

**Comment by reasonerjt** [comment]
@tanimraja1  something wrong here:
`[Errno 21] Is a directory: '/harbor-migration/harbor-cfg/harbor.cfg'`
Does the `harbor.cfg` exist where you execute the docker command?

**Comment by tanimraja1** [comment]
Yes, the file exists where I am executing docker run. I think the issue is with `'/harbor-migration/harbor-cfg/harbor.cfg'` path inside goharbor/harbor-migrator:v1.7.4 image

**Comment by reasonerjt** [comment]
I don't think so could you rerun the docker command with absolute path of the file?

**Comment by thatsk** [comment]
i am also facing issue 1.7.4

**Comment by thatsk** [comment]
but i get different message
docker run -it --rm -v /opt/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.7.4 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
No migrator for version: 1.7.4

**Comment by thatsk** [comment]
can anyone help on this.

**Comment by thatsk** [comment]
> 
> 
> I am trying to upgrade Harbor v1.7.1 to v1.7.4 and I am following the official harbor migration [guide.](https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md)
> I am getting the following error while docker run-
> `docker run -it --rm -v harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.7.4 --cfg up`
> `Please backup before upgrade, Enter y to continue updating or n to abort: y Traceback (most recent call last): File "./migrator.py", line 232, in <module> main() File "./migrator.py", line 178, in main db_migrator = DBMigrator(commandline_input.target_version) File "./migrator.py", line 34, in __init__ conf.write(open(path).read()) IOError: [Errno 21] Is a directory: '/harbor-migration/harbor-cfg/harbor.cfg'`
> 
> Can anyone please help me on this?

have you edited your harbor.cfg file of 1.7.4 its still poining to 1.7.0

**Comment by thatsk** [comment]
When we set to 1.7.0 it says below meesage
docker run -it --rm -v /opt/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.7.4 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
Version of input harbor.cfg is identical to target 1.7.0, no need to upgrade

**Comment by thatsk** [comment]
@reasonerjt can anyone help on this

**Comment by thatsk** [comment]
@ninjadq

**Comment by thatsk** [comment]
@tanimraja1 you did not need to edit version of harbor.cfg file
because from 1.7.1 all schema are same for 1.7.5 correct me if i am wrong @ninjadq @reasonerjt .
So i have skipped that migrator steps and proceed for next step which is install.sh with additional component.
and i am able to upgrade without no issues.
{code}
cat harbor.cfg
## Configuration file of Harbor

#This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
_version = 1.7.0
{code}

**Comment by thatsk** [comment]
community itself using 1.7.0 in harbor 1.7.5 i think so

**Comment by thatsk** [comment]
![image](https://user-images.githubusercontent.com/15324013/55460140-d1bf0b00-560e-11e9-804a-f2b3cbee9d46.png)

**Comment by thatsk** [comment]
i am able to upgrade with skipping migrator part

**Comment by ninjadq** [comment]
@tanimraja1 @thatsk  yes, the scheme in 1.7.1 is the same as 1.7.4. no need to upgrade harbor.cfg

**Comment by reasonerjt** [comment]
This is what I suspected the path you run `docker run` does not have the `host.cfg` file.
