### ISSUE TITLE
 request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by descof** [goharbor/harbor#7082]
Hello everyone,
Probably a newbie issue but i get this error message when i try docker login:

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://x.x.x.x:80/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

i dont use or set any certificates or https config...

To reproduce:
Run tar xvf harbor-offline-installer-v1.7.x.tgz
Go to the extracted harbor folder and edit 'harbor.cfg' file
Change "hostname" to IP that is accessible
Run "install.sh" script
browse the harbor portal
Add the insecure registry to docker: /etc/docker/daemon.json:
{ "insecure-registries":["x.x.x.x:80"] }
docker login x.x.x.x

get the error message..

What is the step i'm missing ?

Thanks !

**Comment by ninjadq** [comment]
are you run prepare script before install?

**Comment by descof** [comment]
I just run what i wrote as "Reproduce step"

**Comment by ninjadq** [comment]
I spot that the IP address is `https://x.x.x.x:80/v2/`. It seems that you did not set the certs for https, but you access an https enabled

**Comment by reasonerjt** [comment]
Closing as this is a usage error.

**Comment by descof** [comment]
Thanks for the update. At the end, it was just a config error in my harbor.cfg. I put the wrong ip address in the field "hostname"
