### ISSUE TITLE
Harbor Upgrade failed while upgrading  VIC OVA 1.5.0 to 1.5.2 RC2

### ISSUE THREAD

**Issue by jitinkumar2018** [goharbor/harbor#7085]
@lgayatri @renmaosheng @luwang-vmware

Builds used :

1.5.0 GA - vic-v1.5.0-6915-e18e6647.ova
1.5.2 RC2 - vic-dev-v1.5.2-rc2-7100-4d2bd5d6.ova
VC : 6.7U1 (10374178)
OVA has been upgraded from 1.5.0 to 1.5.2 using https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/upgrade_appliance.html

Upgrade Log: 
[upgrade.log](https://github.com/goharbor/harbor/files/2934713/upgrade.log)

Starting Harbor Upgrade 2019-03-06 06:01:00 +0000 UTC

2019-03-06 06:09:06 [=] Back up harbor data to : /storage/data/harbor_backup
tar: Removing leading `/' from member names
tar: /storage/db/harbor/database/base/12406/16581: file changed as we read it
tar: /storage/db/harbor/database/base/12406/pg_internal.init: File removed before we read it
tar: /storage/db/harbor/database/base/12406: file changed as we read it
tar: /storage/db/harbor/database/base/16388: file changed as we read it
tar: /storage/db/harbor/database/base: file changed as we read it
tar: /storage/db/harbor/database: file changed as we read it
2019-03-06 06:09:39 [=]
2019-03-06 06:09:39 [=] -------------------------
2019-03-06 06:09:39 [=] Upgrade failed.
2019-03-06 06:09:39 [=] Please save /var/log/vmware/upgrade.log and contact VMware support.
2019-03-06 06:09:39 [=] -------------------------
2019-03-06 06:09:39 [=]

Both old and new VIC vms are present on NFS datastores that are reported as healthy by VC.
Will send environment credentials on Slack

**Comment by steven-zou** [comment]
@wy65701436 

Please take a look at the Harbor upgrading failure. Thanks!

**Comment by luwang-vmware** [comment]
@jitinkumar2018  This issue should be fixed in vic 1.5.2 rc5 ova. Please use the latest ova to retry.

**Comment by wy65701436** [comment]
close it as @luwang-vmware 's comments.
