### ISSUE TITLE
notary-server and notary-signer cannot start after upgrading to 1.7.4 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7091]
the log of notary-server container:
```
Mar  7 06:52:25 172.18.0.1 notary-server[5654]: 2019/03/07 06:52:25 Updating database.
Mar  7 06:52:25 172.18.0.1 notary-server[5654]: 2019/03/07 06:52:25 Done updating database.
Mar  7 06:52:25 172.18.0.1 notary-server[5654]: error: file does not exist
Mar  7 06:52:25 172.18.0.1 notary-server[5654]: waiting for postgres://server:password@postgresql:5432/notaryserver?sslmode=disable to come up.
Mar  7 06:52:26 172.18.0.1 notary-server[5654]: error: file does not exist
Mar  7 06:52:26 172.18.0.1 notary-server[5654]: waiting for postgres://server:password@postgresql:5432/notaryserver?sslmode=disable to come up. 
```
The ` file does not exist ` error was due to an inconsistecy introduced in migration that switch Harbor DB from mysql/mariadb to postgresql

There's no good way to fix it easily, a quick fix is to drop all tables of the `notaryserver` and `notarysigner` databases, and re-sign the images that were signed previously.
A better workaround involve some manual work is in progress.

**Comment by RRAlex** [comment]
Upgraded from 1.4.0 -> 1.6.3 without issue, was about to upgrade to 1.7.4 but saw the warning...
Does the bug manifests itself with previous 1.7.x?
Or is upgrading to 1.7.3, until 1.7.5 arrives, a safe move?
Cheers!

**Comment by wy65701436** [comment]
@RRAlex it happens on v1.7.4 forward, and we will provide a manual workaround, you have to run a script at your end to fix it.

**Comment by wy65701436** [comment]
Just run the script(https://github.com/goharbor/harbor/blob/master/tools/notary-migration-fix.sh) to fix notary DB before launching Harbor.

**Comment by Madic-** [comment]
I've upgraded from 1.6.0 to 1.8.1 and came accross the same issue and did run the notary-migration-fix.sh script but still get the "file does not exist" error. Any idea?

**Comment by apallier** [comment]
Hi, I have the same issue and same behavior as @Madic- when I run the script on a 1.8.2 upgrade.
Should I run this script when Harbor is running or stopped ?

**Comment by Madic-** [comment]
"Fixed" the problem by dropping and then re-creating the databases notaryserver and notarysigner.
