### ISSUE TITLE
time shown for scheduled scanning is incorrect.

### ISSUE THREAD

**Issue by paulczar** [goharbor/harbor#7093]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

When setting the Clair scanning time to Daily at 6:00pm and saving it should show that time as `6:00 pm` or `18:00`.  Instead it shows it as `18:00 am` which is not a real time.

![harbor-1600am](https://user-images.githubusercontent.com/2488346/53974782-fdf77280-40c8-11e9-8c79-50811d292196.png)

**Steps to reproduce the problem:**

install harbor, set schedule scan time in harbor to 6pm daily.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.x and dev

**Comment by steven-zou** [comment]
@zhoumeina 

Please take a look at this issue. Thanks!

**Comment by zhoumeina** [comment]
@lweitzman , Louis. Should we remove all "am"?

**Comment by lweitzman** [comment]
I think we should not show the 24 hr time and instead show "6:00 pm" (= 18:00) or 6:00 am when appropriate.

**Comment by AllForNothing** [comment]
fixed
