### ISSUE TITLE
Add "harbor_nightly_executor" task into "harbor_nightly_migrate_offline" and "harbor_nightly_migrate_offline_1.6"

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7095]
Currently, upgrade tests only cover data migrate part, not including function tests, so please add function tests in upgrade tests.
In jenkins, please add "harbor_nightly_executor" task into "harbor_nightly_migrate_offline" and "harbor_nightly_migrate_offline_1.6".

**Comment by danfengliu** [comment]
This solution was not chosen anymore, as discussion with wangyan, we should modify CI-Project to identify an upgrade task, then run the corresponding test cases.

**Comment by reasonerjt** [comment]
closing as won't fix.
