### ISSUE TITLE
ERROR: for harbor-log  Cannot start service log: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 17\""

### ISSUE THREAD

**Issue by jcops** [goharbor/harbor#7104]
The startup harbr reported the following error, which is problematic. Does anyone know why
![image](https://user-images.githubusercontent.com/24266098/54024548-076d0180-41d3-11e9-9f68-078dd899f6ee.png)

ERROR: for harbor-log  Cannot start service log: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 17\""

ERROR: for log  Cannot start service log: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 17\""
ERROR: Encountered errors while bringing up the project.

**Comment by ninjadq** [comment]
Hi, can you provide the docker version and docker version and your environment?

**Comment by jcops** [comment]
> Hi, can you provide the docker version and docker version and your environment?

Thank you, I upgrade the kernel after the normal work

**Comment by reasonerjt** [comment]
@jcops so is it fixed?

**Comment by jcops** [comment]
@reasonerjt Sorry for taking so long to reply，No, I can work on other servers.
