### ISSUE TITLE
harbor1.6.1安装成功后，有三个容器一直重启

### ISSUE THREAD

**Issue by zgz0412** [goharbor/harbor#7109]
容器报错日志：1、configuration error: open /etc/registry/config.yml: permission denied
2、Failed to load configurations with error: open /etc/jobservice/config.yml: permission denied
3、[ERROR] [base.go:248]: failed to load app config: open /etc/ui/app.conf: permission denied

**Comment by ninjadq** [comment]
cannot reproduce in local, please provide more info, like your environment, installing steps, and more logs

**Comment by ninjadq** [comment]
It seems a permission issue, are you tried installing it using root user?

**Comment by goywzl** [comment]
> It seems a permission issue, are you tried installing it using root user?

I also have this problem. I'm using a normal user installation.

**Comment by goywzl** [comment]
chmod -R o+r common/config

**Comment by ninjadq** [comment]
@goywzl You should use root user. Because there are a lot of operations need high privilege.

**Comment by zgz0412** [comment]
chmod -R 777 common/
之后重启nginx容器
