### ISSUE TITLE
Setting "None" in scanning for vulnerability schedule is not working

### ISSUE THREAD

**Issue by gunboe** [goharbor/harbor#7117]
I've set a Daily Scan at 02:00 and this work fine. After that, I set "None" to do NOT scanning for vulnerability but this dont work, Harbor maintains Scanning for vulnerability everydays at 02:00.
Jobservice Log do not show any changing when I set to "None" and continue scan the last schedule setted.
- harbor version: 1.7.1 (Upgraded since harbor 1.2 and 1.5)

**Comment by zhoumeina** [comment]
@gunboe , If you refresh the page， does it change to "none" for the scanning job?

**Comment by steven-zou** [comment]
job service refactor is done, @reasonerjt please check if the schedule change is work for scanning.

https://github.com/goharbor/harbor/pull/7452

**Comment by wy65701436** [comment]
it's fixed in the master branch, will be in v1.8.0
