### ISSUE TITLE
About the registry api bug

### ISSUE THREAD

**Issue by pureshine** [goharbor/harbor#7128]
1、GET    "/api/registries"  
Cannot enter access ID and access Secret when create, otherwise  will not get data.
Occasionally, an empty string is returned when the state is obtained, and it returns normally after a few seconds.
There is no password entered when create, but will return access_secret: "*****"
2、PUT    "/api/registries/:id([0-9]+)"
Description does not support modification

**Comment by cd1989** [comment]
I can't catch what the problem is, can you make it clear.

**Comment by ywk253100** [comment]
1. Got error when calling `GET /api/registries` if the list contains registry whose credential isn't null
2. The update API cannot update the description

**Comment by ywk253100** [comment]
@cd1989 The `description` and `access_key` cannot be updated, please take a look.

**Comment by cd1989** [comment]
@ywk253100 I will fix it today.

**Comment by cd1989** [comment]
Resolved.

**Comment by pureshine** [comment]
done as pr #7291 #7290
