### ISSUE TITLE
helm

### ISSUE THREAD

**Issue by ypyaaa** [goharbor/harbor#7131]
使用harbor管理helmchart，添加helm仓库地址为harbor时 报错 x509: certificate signed by unknown authority

**Comment by ninjadq** [comment]
What command are you using for add repo? Do you specify the ca files?

**Comment by ypyaaa** [comment]
add ca file. new question 
is not a valid chart repository or cannot be reached: Failed to fetch http://10.10.102.91/chartrepo/helmrepo/index.yaml : 401 Unauthorized

**Comment by ypyaaa** [comment]
replace https://10.10.102.91/chartrepo/helmrepo/index.yaml can resolve this question
