### ISSUE TITLE
Harbor as a local registry mirror doesn't show image on ui

### ISSUE THREAD

**Issue by thebe2** [goharbor/harbor#7156]
I use Harbor as a local registry mirror , then run `docker pull busybox:1.30.0` .

In harbor ui ,  `library` project has nothing.

But can find `busybox` in `data/registry/docker/registry/v2/repositories/library/` folder 

The versions of following systems:
- docker version: 17.03.1
- docker-compose version: 1.23.2
- harbor:v1.7.4

**Comment by ninjadq** [comment]
you should add project namespace before your image name like `xxx.xxx.xxx/library/busybox:1.30.0`

**Comment by thebe2** [comment]
> you should add project namespace before your image name like `xxx.xxx.xxx/library/busybox:1.30.0`

Use the command like that,

but in harbor ui , `library/repositories` view  always has nothing and in `Logs` View can find the pull image record.

**Comment by reasonerjt** [comment]
Harbor does not support being used as a proxy, and it's never tested.

Now for you particular issue, I believe this is because when an image is pulled from docker hub the notification is not triggered to update the database.
