### ISSUE TITLE
Disk size released by GC jobs

### ISSUE THREAD

**Issue by supereagle** [goharbor/harbor#7157]
It would be better to show released disk size by each GC job in history list.

![image](https://user-images.githubusercontent.com/3390333/54420764-d8f8a480-4745-11e9-9dd2-5a14a57eb506.png)

**Comment by supereagle** [comment]
@ninjadq  Which version will support this?

**Comment by wy65701436** [comment]
@supereagle as the limitation of docker registry, it's hard for harbor to get the data. It's not in the plan so far.

**Comment by supereagle** [comment]
Harbor already has APIs to get the storage size, I think we can count the released size for GC jobs.

**Comment by wy65701436** [comment]
Use the issue to track requirement and dev work, but bases on the GC implement, it's hard for harbor to get the details of a GC execution and parse them.

**Comment by xaleeks** [comment]
This should be considered when designing our enhanced GC, these numbers can now be captured right? @wy65701436

**Comment by wy65701436** [comment]
this could be covered by https://github.com/goharbor/harbor/issues/10197

**Comment by xaleeks** [comment]
ok closing then, please follow that ticket @supereagle
