### ISSUE TITLE
harbor image replication is incremental?

### ISSUE THREAD

**Issue by huzhengchuan** [goharbor/harbor#7161]
docker image  is use image layers to manage. when two images container the same image layers, that will only contain one image layers in registry. 
when doing image replication, if one image layers is already exists in mirror habor, it will not need to translate the image layer again in replication.  but i check the logs of habror replication, it is not right.

test-step 
1. on image  a.cargo.test2.com/hzc/test00:01 push to harbor-A, and replicate to the mirror harbor-B.
2. and rename the same image to a.cargo.test2.com/hzc/hzc00:01, push to habror-A, and do replicate to the harbor-B
3. the print log in step-2, like translate datas again to habor-B

I want to know why, and how to improve the process?

**Comment by huzhengchuan** [comment]
ping @steven-zou   @ywk253100

**Comment by huzhengchuan** [comment]
ping @steven-zou  @ywk253100  
the code src/jobservice/job/impl/replication/transfer.go  transferLayers()
<pre>
		digest := blob.Digest.String()
		exist, err := t.dstRegistry.BlobExist(digest)
		if err != nil {
			t.logger.Errorf("an error occurred while checking existence of blob %s of %s:%s on destination registry: %v",
				digest, repository, tag, err)
			return err
		}
		if exist {
			t.logger.Infof("blob %s of %s:%s already exists on the destination registry, skip",
				digest, repository, tag)
			continue
		}
</pre>

this code is only check whether the blob exist in the same repo.

**Comment by huzhengchuan** [comment]
the problem fixed [Proposal: Cross repository push](https://github.com/docker/distribution/issues/634), I think harbor do replication image like docker, always check blob in others repo.

**Comment by ywk253100** [comment]
There is no API to check whether the layer exists in any other repository.

**Comment by huzhengchuan** [comment]
yes, i agree, first need a api in docker.
