### ISSUE TITLE
Harbor High Availability Guide 高可用部署官方文档返回404， 链接：  https://github.com/goharbor/harbor/blob/master/docs/high_availability_installation_guide.md    新的HA官方文档地址是多少

### ISSUE THREAD

**Issue by dengyong89** [goharbor/harbor#7162]
Harbor High Availability Guide 高可用部署官方文档返回404， 链接：  https://github.com/goharbor/harbor/blob/master/docs/high_availability_installation_guide.md    新的HA官方文档地址是多少

**Comment by ninjadq** [comment]
this doc is outdated. you can try k8s and harbor-helm to build a ha harbor.

**Comment by reasonerjt** [comment]
Closing as the question is answered.
