### ISSUE TITLE
harbor  v1.7.4 email  set  test fail

### ISSUE THREAD

**Issue by Jawenba** [goharbor/harbor#7180]
# Hello, the harbor fail  screenshot like this.
![图片](https://user-images.githubusercontent.com/47962033/54665959-7af00680-4b23-11e9-898d-b8a14e6352ec.png)

### checked the core.log and  showed this info
`[ERROR] [email.go:109]: failed to ping email server: dial tcp: lookup smtp.qiye.163.com: Temporary failure in name resolution`
### checked ping smtp.qiye.163.com on node system was  OK:
```
PING smtp.qiye.163.com (220.181.97.157) 56(84) bytes of data.
64 bytes from m97157.mail.qiye.163.com (220.181.97.157): icmp_seq=1 ttl=53 time=40.8 ms
64 bytes from m97157.mail.qiye.163.com (220.181.97.157): icmp_seq=2 ttl=53 time=44.0 ms
```

### My  email is ok, but  it  fail .Does the container harbor-core need to be seted http_proxy also？

harbor.cfg:
```
http_proxy = http://xxx.xxx.xxx.xxx:8888
https_proxy = http://xxx.xxx.xxx.xxx:8888
no_proxy = 127.0.0.1,localhost,core,registry
```

Versions:
    ubuntu version: Ubuntu 18.04.2 LTS
    harbor version: [1.7.4]
    docker engine version: [18.06.1-ce]
   docker-compose version 1.23.2, build 1110ad01
   docker-py version: 3.6.0
   CPython version: 3.6.7
   OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by reasonerjt** [comment]
I don't think setting http proxy may solve your problem as the error happens in name resolution.

How did you deploy Harbor?
And I believe your dns did some trick when resolving the hostname `smtp.qiye.163.com`
On my desktop this hostname is resolved to another IP:
```
~$ ping smtp.qiye.163.com
PING smtp.qiye.163.com (123.125.50.11): 56 data bytes
64 bytes from 123.125.50.11: icmp_seq=0 ttl=56 time=1.678 ms
64 bytes from 123.125.50.11: icmp_seq=1 ttl=56 time=1.718 ms
64 bytes from 123.125.50.11: icmp_seq=2 ttl=56 time=2.055 ms
64 bytes from 123.125.50.11: icmp_seq=3 ttl=56 time=1.876 ms
```
You have to work with your IT admin to make sure the dns setting is applied to the container of Harbor.

**Comment by Jawenba** [comment]
### @reasonerjt think you! I deploy harhor following the install guide, and now  I find the solution for this issue.
### checked :
`sudo  vi /etc/resolv.conf`

nameserver 127.0.0.53
options edns0

That's the problem.


### Reference resources
 [https://www.cnblogs.com/breezey/p/9155988.html](https://www.cnblogs.com/breezey/p/9155988.html) 

### this I done:
sudo systemctl stop systemd-resolved.service
sudo systemctl disable systemd-resolved.service
sudo  vi /etc/resolv.conf

#nameserver 127.0.0.53
#options edns0
nameserver 114.114.114.114

### then restart harbor 
![图片](https://user-images.githubusercontent.com/47962033/54729508-f2bf3f00-4bbe-11e9-9a23-f6931b91bf58.png)
