### ISSUE TITLE
Update the CHANGELOG to include current version

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#7185]
The [CHANGELOG.md](https://github.com/goharbor/harbor/blob/master/CHANGELOG.md) needs to be updated to include the current version.

Perhaps we can take a look at the tool proposed here?
https://github.com/goharbor/harbor/issues/4630

**Comment by reasonerjt** [comment]
Fixed in #7315 
I'll investigate the tool that was proposed, some concern is that it will list all issues, which will make the log too long
