### ISSUE TITLE
The "Architecture overview of Harbor" wiki entry needs to be updated

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#7187]
The current [Architecture overview of Harbor](https://github.com/goharbor/harbor/wiki/Architecture-Overview-of-Harbor) wiki entry hasn't been updated since September 2016, and should be updated to reflect the current status of the architecture.

**Comment by stuclem** [comment]
@reasonerjt is this an developer task or a documentation task? My guess is that it's a developer task, but I can certainly provide editorial assistance.

**Comment by xaleeks** [comment]
Hi Stuart, we can update the architecture and maybe you can help with finalizing the presentation.  @stuclem

**Comment by xaleeks** [comment]
Who will be responsible for this? I actually prefer we move this out of target/1.10 and into 1.11 maybe the first branch release @reasonerjt

**Comment by steven-zou** [comment]
Done, check https://github.com/goharbor/harbor/wiki/Architecture-Overview-of-Harbor
