### ISSUE TITLE
Expected user for Nginx?

### ISSUE THREAD

**Issue by nicholasamorim** [goharbor/harbor#7188]
I'm creating an ansible playbook for Harbor and so far I'm doing pretty well. However, I've been running into certain permissions problems. More specifically, once the services are restarted via docker-compose the registry and the nginx have permission problems.

To get around that I set the `common` and all its contents to:

owner: uid 10000
mode: 0750 
group: 10000 or `docker`(tried both)

But nginx proxy keeps complaining (the only one):

`nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)`

What should be the permissions for the nginx folder then?

**Comment by reasonerjt** [comment]
you don't need to change the owner of nginx.conf
because in 1.7.x the process of nginx is started by root

**Comment by reasonerjt** [comment]
@nicholasamorim is your problem fixed?

**Comment by nicholasamorim** [comment]
As a good practice in the ansible playbook, I change the permissions on the `common` folder to be owned by UID 10000 and group `docker` mode `0750`, this is enough for everything except nginx.

So I'll just keep the nginx configuration folder  as `root` then. Then it's fixed, yes.

**Comment by qzwlinux** [comment]
> As a good practice in the ansible playbook, I change the permissions on the `common` folder to be owned by UID 10000 and group `docker` mode `0750`, this is enough for everything except nginx.
> 
> So I'll just keep the nginx configuration folder as `root` then. Then it's fixed, yes.

```
chown -R 10000:10000 common 
```
