### ISSUE TITLE
Harbor v1.7.4 : authorization token required

### ISSUE THREAD

**Issue by wphe** [goharbor/harbor#7197]
What can we help you?

I have installed Harbor v1.7.4 but I got this error (error authorizing context: authorization token required) in the registry.log. I don't have any issue for pulling/pushing images.

How to solve this?

registry.log

`Mar 21 09:54:44 172.27.0.1 registry[24913]: time="2019-03-21T16:54:44.000310592Z" level=info msg="response completed" go.version=go1.11.5 http.request.host="registry:5000" http.request.id=39d1b808-3ae2-4f6e-b600-40a03ddbdabe http.request.method=GET http.request.remoteaddr="172.27.0.7:42628" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="74.138µs" http.response.status=301 http.response.written=39
Mar 21 09:54:44 172.27.0.1 registry[24913]: time="2019-03-21T16:54:44.001503857Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.5 http.request.host="registry:5000" http.request.id=cbd1c013-85a9-42eb-8d8b-e3f29a7fc607 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="172.27.0.7:42628" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
Mar 21 09:54:44 172.27.0.1 registry[24913]: 172.27.0.7 - - [21/Mar/2019:16:54:44 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Mar 21 09:54:44 172.27.0.1 registry[24913]: 172.27.0.7 - - [21/Mar/2019:16:54:44 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
Mar 21 09:54:53 172.27.0.1 registry[24913]: 127.0.0.1 - - [21/Mar/2019:16:54:53 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Mar 21 09:54:54 172.27.0.1 registry[24913]: time="2019-03-21T16:54:54.000759231Z" level=info msg="response completed" go.version=go1.11.5 http.request.host="registry:5000" http.request.id=828b21d8-dac7-4046-aecb-4c1ac62a83d5 http.request.method=GET http.request.remoteaddr="172.27.0.7:42644" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="85.913µs" http.response.status=301 http.response.written=39
Mar 21 09:54:54 172.27.0.1 registry[24913]: time="2019-03-21T16:54:54.002119052Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.5 http.request.host="registry:5000" http.request.id=6dd41eb8-ad3e-4bcd-b2f8-fb96a8353a3c http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="172.27.0.7:42644" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
Mar 21 09:54:54 172.27.0.1 registry[24913]: 172.27.0.7 - - [21/Mar/2019:16:54:54 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Mar 21 09:54:54 172.27.0.1 registry[24913]: 172.27.0.7 - - [21/Mar/2019:16:54:54 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
`

**Comment by reasonerjt** [comment]
If things work as expected, you can ignore this error it happens when docker cli access registry to get the endpoint for token.  
For details refer to:
https://docs.docker.com/registry/spec/auth/token/
