### ISSUE TITLE
我想使用在 AWS上用外网 访问harbor镜像仓储但是出现了以下问题 ，请问怎么解决呢？

### ISSUE THREAD

**Issue by light2cloud** [goharbor/harbor#7198]
Error response from daemon: Get http://harbor.xxxx.test/v2/: Get http://10.0.0.209/service/token?account=xxxx&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by reasonerjt** [comment]
Your client cannot connect to the endpoint  `http://10.0.0.209/`

**Comment by light2cloud** [comment]
是的，我的AWS 内网 IP 是   10.0.0.209 但是我通过 AWS  外网 IP 没办法访问harbor，请问有啥办法可以让我直接通过 外网IP访问我的镜像仓储吗？

**Comment by reasonerjt** [comment]
It depends on you to expose Harbor on a public IP

**Comment by light2cloud** [comment]
是的，是离线安装的，也更改了 hostname 为域名，然后 使用 docker-compose stop 和 docker-compose start 重启了服务但是还是会出现上边的错误

**Comment by reasonerjt** [comment]
Like I said you need to  **re-run prepare and re-deploy.**

**Comment by bear280** [comment]
我遇到同样的问题 Error response from daemon: Get http://harbor.zjmiec.cn/v2/: Get http://172.16.10.12/service/token?account=admin&client_id=docker&offline_
token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by bear280** [comment]
我遇到了同样的问题：Error response from daemon: Get http://harbor.xxxx.cn/v2/: Get http://172.16.10.12/service/token?account=admin&client_id=docker&offline_
token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by bear280** [comment]
我的模式是自建nginx(公网IP)-->内网（172.16.10.12）,内网使用docker login 172.16.10.12 正常[root@zjmieczdxjoms harbor]# docker login 172.16.10.12
Username: admin
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
外网使用docker login harbor.xxx.cn出现以下错误：
[root@zjmiecTestWMS ~]# docker login harbor.xxx.cn
Username: admin
Password: 
Error response from daemon: Get http://harbor.xxxx.cn/v2/: Get http://172.16.10.12/service/token?account=admin&client_id=docker&offline_
token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)
