### ISSUE TITLE
delete Helm-version show error

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#7201]
When I delete helm-version, the page displays error and the API returns 500.

![image](https://user-images.githubusercontent.com/29826789/54812082-37cd9900-4cc5-11e9-8136-c26f9fef6dcd.png)
![image](https://user-images.githubusercontent.com/29826789/54812100-41ef9780-4cc5-11e9-8f29-23bf1af85f1b.png)

![image](https://user-images.githubusercontent.com/29826789/54812017-11a7f900-4cc5-11e9-9188-27c5a39bfd61.png)

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by steven-zou** [comment]
@ninjadq 

Please take the cover of this issue and check if it should be fixed within 1.8

**Comment by wy65701436** [comment]
close it as pr merged. https://github.com/goharbor/harbor/pull/7497
