### ISSUE TITLE
Replication : Failed to ping endpoint

### ISSUE THREAD

**Issue by wphe** [goharbor/harbor#7205]
What can we help you?

Hi,
I have 2 harbors (v1.7.4). Before the migration from v1.6.2 to v1.7.4, the replication work well but since the migration, it's not working anymore.

When I tried to add Harbor B to Harbor A, I got this message "Failed to ping endpoint".
Any ideas?

core.log on HarborA
`Mar 22 11:46:41 172.19.0.1 core[13397]: 2019-03-22T10:46:41Z [ERROR] [target.go:65]: failed to ping target: Head https://HarborB.com/v2/: Get https://HarborB/v2/: dial tcp: lookup HarborB.com on 127.0.0.11:53: read udp 127.0.0.1:50092->127.0.0.11:53: i/o timeout
Mar 22 11:46:41 172.19.0.1 core[13397]: 2019/03/22 10:46:41 #033[1;44m[D] [server.go:2741] |  10.128.12.228|#033[43m 400 #033[0m|10.001399861s|   match|#033[46m POST    #033[0m /api/targets/ping   r:/api/targets/ping#033[0m
Mar 22 11:46:49 172.19.0.1 core[13397]: 2019/03/22 10:46:49 #033[1;44m[D] [server.go:2741] |      127.0.0.1|#033[42m 200 #033[0m|    267.261µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
`

**Comment by wphe** [comment]
**Solved:** I just added the ip and hostname (/etc/hosts ) in the harbor-core container.

**Comment by aminellouz** [comment]
> **Solved:** I just added the ip and hostname (/etc/hosts ) in the harbor-core container.

does the 2 harbors located in different networks ? if yes did you specify the ip and hostname in both or juste in harbor A

**Comment by wphe** [comment]
Yes they are on a different network.
You can also modify the docker-compose file and add these lines at the same level as ports for example:
extra_hosts:
 - "somehost:162.242.195.82"
 - "otherhost:50.31.209.229"
