### ISSUE TITLE
Vulnerabilities don't show "negligible" and Prevent images from running settings do

### ISSUE THREAD

**Issue by SK360** [goharbor/harbor#7207]
I have a project that is built using an older version of openjdk:8-jre-alpine.  It shows up in Harbor as having 5 Unknown Vulnerabilities.  I updated the image to the latest version of openjdk:8-jre-alpine and pushed it to Harbor.  The Clair scan reports 0 Vulnerabilities and shows all green with 0 vulnerabilities in the details of the tag for the new version.  I was hoping to be able to prevent the older "Unknown" one from being deployed but allow the new one to go out since it showed all green.

I noticed in the "Prevent images from running" settings for the project there are only settings for High/Medium/Low/Negligible.  Since the page with details on the tag only lists 4 Vulnerability levels (High/Medium/Low/Unknown) I figured that Negligible = Unknown.  However when I implemented it I discovered Negligible and Unknown were indeed different.  

The UI makes no mention of Negligible outside of the "Prevent images from running" drop down so I had no idea the newer image was in this category.

Older image
> Error response from daemon: unknown: The severity of vulnerability of the image: "unknown" is equal or higher than the threshold in project setting: "negligible                                                                             ".

Newer image
> Error response from daemon: unknown: The severity of vulnerability of the image: "negligible" is equal or higher than the threshold in project setting: "negligi                                                                             ble".

**Comment by reasonerjt** [comment]
@SK360 could you kindly let me know what version of Harbor are you using?
Is the docker image you scanned pullable from docker hub?

**Comment by SK360** [comment]
> @SK360 could you kindly let me know what version of Harbor are you using?
> Is the docker image you scanned pullable from docker hub?

Version v1.7.4-ce6a6237

Unfortunately no it's not on dockerhub... It is a project we are building using the openjdk:8-jre-alpine image and the Google Jib maven plugin for building the container and pushing to Harbor.  I will try to push just the public OpenJDK image to it and see if we get the same results.

**Comment by SK360** [comment]
> @SK360 could you kindly let me know what version of Harbor are you using?
> Is the docker image you scanned pullable from docker hub?

Ok so now I pulled the latest openjdk:8-jre-alpine

```
[SK360@server docker]$ docker pull openjdk:8-jre-alpine
8-jre-alpine: Pulling from library/openjdk
8e402f1a9c57: Pull complete
4866c822999c: Pull complete
205f26e90552: Pull complete
Digest: sha256:f7ea122d42799223ea01231d2661fd95a2695d6085ba57d6378b68463247011d
Status: Downloaded newer image for openjdk:8-jre-alpine

[SK360@server docker]$ docker tag openjdk:8-jre-alpine harborserver/base_images/openjdk8jre:latest

[SK360@server docker]$ docker push harborserver/base_images/openjdk8jre:latest
The push refers to repository [harborserver/base_images/openjdk8jre]
925523484e00: Pushed
344fb4b275b7: Pushed
bcf2f368fe23: Pushed
```

The scan shows all green.. nothing that would make you think there are going to be issues with the project config I have set.

![image](https://user-images.githubusercontent.com/6358878/55002593-4958be80-4fad-11e9-8600-ae56668fb533.png)

![image](https://user-images.githubusercontent.com/6358878/55002542-30e8a400-4fad-11e9-829e-660b740a75d7.png)

My Project settings are
![image](https://user-images.githubusercontent.com/6358878/55002684-6f7e5e80-4fad-11e9-8bbc-7a1ccf10a841.png)

But when I actually go to pull...
```
[SK360@server docker]$ docker pull harborserver/base_images/openjdk8jre:latest
Error response from daemon: unknown: The severity of vulnerability of the image: "negligible" is equal or higher than the threshold in project setting: "negligible".
```

I think the problem is that Negligible doesn't show at all on the image status page, only High/Med/Low/Unknown so you wouldn't know about it.  But then the dropdown in the project settings doesn't include Unknown (which at least in my opinion should be above Negligible in severity).

**Comment by reasonerjt** [comment]
@SK360 have you tried to rescan this image?

I see there's mismatch in the severity in tag details and the project policy.
We may need to defer this as https://github.com/goharbor/harbor/issues/6999 we may refine this part.

I'll double check and see what we can do to mitigate such confusion.

**Comment by reasonerjt** [comment]
Root cause is the code consider negligible will be mapped to "none" in terms of severity, we should probably remove it from UI.

i.e. Harbor will not block pulling an image with "negligible" severity

**Comment by reasonerjt** [comment]
Closing as fixed
