### ISSUE TITLE
BUG : Endpoint - Long password (50 Chars) error

### ISSUE THREAD

**Issue by Poil** [goharbor/harbor#7208]
Hi,

When setting a very long password, more than 49 characters, I have this error : "Invalid endpoint name. "

I can't change the password, it's given by my cloud provider (Flexible Engine/Huawei cloud)

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.7.1
- docker engine version: 18.03.0-ce

Best regards,

**Comment by ywk253100** [comment]
There is a limit for the length of password in 1.7 and we will extend it in 1.8

**Comment by ywk253100** [comment]
Fixed.
