### ISSUE TITLE
Build history

### ISSUE THREAD

**Issue by wphe** [goharbor/harbor#7219]
What can we help you?
I have installed Harbor v1.7.4 but I don't see the build history features. The user documentation is not enough detailed about how to enable/activate it (https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#build-history).

How can I enable it?

**Comment by reasonerjt** [comment]
I believe this is a pure UI function to show build history, 
@kofj  could you kindly help?

**Comment by kofj** [comment]
> What can we help you?
> I have installed Harbor v1.7.4 but I don't see the build history features. The user documentation is not enough detailed about how to enable/activate it (https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#build-history).
> 
> How can I enable it?

Build history need not enable by default, but there is a bug now: the page's link only show when you **ENABLE CLAIR**, I's fix it later.

You can enable clair when you execute the `install.sh` with **--with-clair**.

And then, you can see the link.

![image](https://user-images.githubusercontent.com/3346673/55402432-0cc92c00-5586-11e9-8f29-015a52043e4b.png)

**Comment by reasonerjt** [comment]
Thanks @kofj let me label it to target 1.8.0 if you have risk to deliver the fix within the timeframe please add a comment to let us know.
