### ISSUE TITLE
LDAP unknown error instead of invalid credentials

### ISSUE THREAD

**Issue by wToad** [goharbor/harbor#7221]
Hello,

**Expected behavior and actual behavior:**
I'm configuring the LDAP connection, and I expect the interface to reject me with a message saying that my LDAP credentials are wrong when it happens. But this is not the case, instead I can see an unknown error, as on this screenshot:

![screenshot](https://framapic.org/P8L8l793lGN3/PzKcOKU1nV3o.png)

When I'm checking the logs, I can clearly see that is a credentials issue (cf. joined logs)

**Steps to reproduce the problem:**
Make sure you have a wrong password for the LDAP connection and that everything else is correct. Trigger the "Test LDAP server" button and here it is.

**Versions:**
- harbor version: [1.7.4]
- docker engine version: [18.09.3]
- docker-compose version: [1.23.2]

**Additional context:**
* **Log files:**
```
==> core.log <==
Mar 25 14:49:24 192.168.64.1 core[843]: 2019-03-25T14:49:24Z [ERROR] [base.go:94]: LDAP connect fail, error: LDAP Result Code 49 "Invalid Credentials": 
```

When I set the correct password, everything is going well of course.

**Comment by lifeblood** [comment]
same here

**Comment by reasonerjt** [comment]
@stonezdj please triage

**Comment by stonezdj** [comment]
This issue is caused by security scan in our code, we can not expose the error from LDAP server to client directly,  and it is not reliable to check the returned message to verify if it is a invalid credentials error, because there are lots of ldap server with different messages.

**Comment by wToad** [comment]
You do not plan to make it possible to expose the error from LDAP connection failure?

I do believe it would be reliable to check the returned message with a simple `grep`-like stuff on `login/credentials`. Because, in our case, if the administrator of Harbor can not tell what is wrong, he need to ask to technician. If the issue is not about credentials, it would be another person in charge so we are going to mobilize people unnecessarily.

But if that does not fit into your use cases, so be it. Thank you for answering the issue.
