### ISSUE TITLE
Unsetting Scheduled GC via the UI does not remove it from redis

### ISSUE THREAD

**Issue by guillaumelfv** [goharbor/harbor#7229]
I work at a company based in Thailand named Agoda. We use Harbor in production for few month now. 

We use harbor v1.7.1 in HA with external redis server/postgresql cluster and CEPH as filestorage.

**Unsetting a GC schedule from the UI does not remove the schedule from redis and the GC keep running on the schedule removed from UI.**

Impact is pretty major for us as the GC put harbor into read only mode every night at 1 AM and take a long time as we have 14 Tb of data and a lot of layer. Images are pushed even at night and this make publishing images impossible.

1) On 18 March we set a scheduled GC to daily at 1 AM (bangkok time UTC+7).

2) On 19 March the next day we removed the GC schedule

Even if we removed the GC schedule GC keep running everyday at 1 AM since 18 March !

> Mar 22 00:56:40 172.30.0.1 jobservice[20220]: 2019-03-21T17:56:40Z [INFO] Schedule job IMAGE_GC:d78d05373f70440d6e11ce96 for policy 11929dd6daa68b42a0f807e3 at 1553191200 by enqueuer 06057064e74c0bf280ca82dc
Mar 24 00:56:30 172.30.0.1 jobservice[20220]: 2019-03-23T17:56:30Z [INFO] Schedule job IMAGE_GC:d5ddb5a7123b9d77f58ffd8a for policy 11929dd6daa68b42a0f807e3 at 1553364000 by enqueuer 06057064e74c0bf280ca82dc
Mar 25 09:03:12 192.168.0.1 jobservice[20220]: 2019-03-25T02:03:12Z [INFO] Register job *gc.GarbageCollector with name IMAGE_GC
Mar 25 09:03:12 192.168.0.1 jobservice[20220]: 2019-03-25T02:03:12Z [INFO] Load periodic job policy 11929dd6daa68b42a0f807e3 for job IMAGE_GC: 0 0 18 * * *
Mar 26 00:57:46 192.168.0.1 jobservice[20220]: 2019-03-25T17:57:46Z [INFO] Schedule job IMAGE_GC:da79fd2d57ff0ca8d0dd0014 for policy 11929dd6daa68b42a0f807e3 at 1553536800 by enqueuer 57c09d44e2aebe709e530548
Mar 26 01:00:00 192.168.0.1 jobservice[20220]: 2019-03-25T18:00:00Z [INFO] Job incoming: IMAGE_GC:da79fd2d57ff0ca8d0dd0014
Mar 26 05:49:21 192.168.0.1 jobservice[20220]: 2019-03-25T22:49:21Z [INFO] Job 'IMAGE_GC:da79fd2d57ff0ca8d0dd0014' exit with success

3) We checked then directly into the database and saw many IMAGE_GC job with status pending marked as deleted but still in the database. https://ibb.co/yftFNsP

4) We removed all database entries for these IMAGE_GC jobs. But the GC ran the next night at 1 AM anyway.

5) We finally looked into the redis and delete the following key : 

> ZRANGE {harbor_job_service_namespace}:period:policies 0 100
> 1) "{\"job_name\":\"IMAGE_GC\",\"job_params\":{\"redis_url_reg\":\"redis://anonymous:*****@*****:6379/1\"},\"cron_spec\":\"0 0 18 * * *\"}"

We do not now if removing the key from redis will finally solve the issue, I will keep you updated tomorrow.

**Comment by wy65701436** [comment]
@guillaumelfv can you provide the log of harbor-core? And can you try to set a new schedule and then to delete it? and please capture the request/response with the developer tool.

**Comment by guillaumelfv** [comment]
Close because this was caused by this issue #7237

**Comment by steven-zou** [comment]
The issue will be fixed in the PR https://github.com/goharbor/harbor/pull/7452 and delivered through V1.8. (Master code now has the fix already)
