### ISSUE TITLE
LDAP Groups With Admin Privilege

### ISSUE THREAD

**Issue by obeyler** [goharbor/harbor#7230]
What can we help you?
I don't see "LDAP Groups With Admin Privilege" as parameter inside doc (https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md), could you add it ?
I suppose it should exist as  https://github.com/goharbor/harbor/issues/5226 is solved
https://github.com/goharbor/harbor/issues/6976 and same question/remark if you plan to remove it from harbor.cfg we not be able to install it automatically anymore

**Comment by stonezdj** [comment]
Will fix it in #7324
