### ISSUE TITLE
Harbor not redirecting to expected URL after logging in when following a link

### ISSUE THREAD

**Issue by CYarmock** [goharbor/harbor#7231]
Steps to reproduce the issue:

    * Be logged out
    * Click a link to a harbor repo. Ex: https://harbor.io/harbor/projects/123/repo/abc
    * Notice login page and sign in
    * Notice you are redirected to "https://harbor.io/harbor/projects" instead of the URL above

Expected: Be redirected to the actual URL you clicked on/navigated to after logging in if you weren't already logged in.
Got: Login page then default project page view/listing.

**Possibly helpful info**:
In Fiddler, the last request before logging in is `/api/systeminfo`. The request header shows the **Referer** as: https://harbor.io/harbor/sign-in?**redirect_url=%2Fharbor%2Fprojects**

**Comment by zhoumeina** [comment]
@CYarmock Let me clarify to make sure we are on the same page. So you want a feature to keep the same page if you login again. Is it right? currently, harbor does not support this feature. Since the effort is not big. We can consider to do it in 1.9.0.

**Comment by CYarmock** [comment]
> 
> 
> @CYarmock Let me clarify to make sure we are on the same page. So you want a feature to keep the same page if you login again. Is it right? currently, harbor does not support this feature. Since the effort is not big. We can consider to do it in 1.9.0.

Correct. 

In my original example I click a link meant for `https://harbor.io/harbor/projects/123/repo/abc`, but after logging in I get sent to `https://harbor.io/harbor/projects`. 
I would like for Harbor to send me to my original location after login.

**Comment by jwangyangls** [comment]
fix in pull Request #7336 Change the login module

**Comment by DonAndrey** [comment]
> fix in pull Request #7336 Change the login module

Is this fix included in a particular harbor release?
