### ISSUE TITLE
Migrate the schedule of scan all

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7233]
As scan all api changed in master,  we need to handle the schedule of scan all in the migrator tool. In the previous release, the schedule is in the configuration, but after code refactor, the schedule has been moved to DB.

**Comment by reasonerjt** [comment]
Please make sure this is documented if we decide not to do the migration, and the data in `property` table is removed.

**Comment by wy65701436** [comment]
close as fixed.
