### ISSUE TITLE
helm-charts tab will disappear unpredictable.

### ISSUE THREAD

**Issue by hctac** [goharbor/harbor#7239]
I have already installed the harbor, chartmuseum by "Harbor on Kubernetes" version.
As the title, the helm-charts tab will disappear when a while..., the interesting thing is while I re-login or type the url (harbor/projects/2/helm-charts/) it still can show the page.....

**Versions:**
- harbor version: 1.7.4 (harbor-offline-installer-v1.7.4.tgz)
- docker engine version: 1.13.1
- helm version: 2.12.0

After login (re-login) or type the correct url
![image](https://user-images.githubusercontent.com/5327011/55063315-af7b3980-50b2-11e9-92ee-408cb9195e7e.png)

After refresh the page
![image](https://user-images.githubusercontent.com/5327011/55063417-e4878c00-50b2-11e9-9835-34aec4ed1ab1.png)

**Comment by jwangyangls** [comment]
I can't reproduce this problem in the Harbor 1.7.4 environment.
