### ISSUE TITLE
No option to use an external database

### ISSUE THREAD

**Issue by biolounge** [goharbor/harbor#724]
We don't see an option to configure Harbor to use an external databases (eg: RDS or MySQL running on a different VM).

**Comment by reasonerjt** [comment]
Currently not, you'll have to update the docker-compose template and environment variables.  And by the way, we haven't verified Harbor against other DB yet.

**Comment by biolounge** [comment]
Thanks for the reply.
Is there any plan to add support for external DB in the coming releases of Harbor?

**Comment by reasonerjt** [comment]
We have plan to tailor it, but there may not be a version with all other features and an external DB.  Actually it supports external DB NOW, it's just not in the install process, not fully integrated in docker-compose template.

**Comment by biolounge** [comment]
Is it possible to add external DB as an option to the Harbor install process soon? I think its really important to run a production harbor DB on an external DB for high availability.

**Comment by joeyjy** [comment]
@biolounge @reasonerjt So in this moment if we want to use an external Mysql database, the only way is to change config/ui/env and config/jobservice/env after installation? I mean these keys in env file:
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_USR=root
MYSQL_PWD=root123

**Comment by biolounge** [comment]
@joeyjy Thanks for the tip. I will try it.

**Comment by erancx** [comment]
@joeyjy, @reasonerjt, Just an update, I dumped all the registry database to a file, created an AWS RDS instance and pointed the above env files to the instance. Seems to be working great!
Now, what are the downsides using this method? Except that it's not really supported by you..

Thanks!

**Comment by joeyjy** [comment]
@erancx I think only harbor ui needs connection to database. I haven't look into the source code of docker registry but I guess registry is stateless, once I tried to run two registry containers in two different VMs using same storage backend, same root.crt file and same notification address, they seem to work well. I'm not sure if this is a reliable way to do HA of registry layer, want to ask @reasonerjt 's advice.

By the way, with regard to the HA of ui, I set the env var _REDIS_URL in order to make sure two ui were using same session backend, but unfortunately it didn't work, I think it needs to modify source code to achieve ui HA

**Comment by Paul-Michaud** [comment]
Hello, I know I might be late but you can now configure an external db in harbor.cfg : 

```
#The address of the Harbor database. Only need to change when using external db.
db_host = 10.10.10.10

#The password for the root user of Harbor DB. Change this before any production use.
db_password = root123

#The port of Harbor database host
db_port = 3306

#The user name of Harbor database
db_user = root
```
I loaded the [the Harbor DB Schema](https://github.com/vmware/harbor/blob/release-1.5.0/make/photon/db/registry.sql) in the database and it worked

Version of mysql : 
```
# mysql --version
mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by clouderati** [comment]
Thanks @Paul-Michaud – much appreciated. v1.6 will actually leverage PostgreSQL so not sure that loading the schema will work.

**Comment by reasonerjt** [comment]
In 1.6 we have moved the initialization to harbor-core container, so as long as the empty DB are created, Harbor will automaticly initialize the schema.

**Comment by Wang-Kai** [comment]
> Hello, I know I might be late but you can now configure an external db in harbor.cfg :
> 
> ```
> #The address of the Harbor database. Only need to change when using external db.
> db_host = 10.10.10.10
> 
> #The password for the root user of Harbor DB. Change this before any production use.
> db_password = root123
> 
> #The port of Harbor database host
> db_port = 3306
> 
> #The user name of Harbor database
> db_user = root
> ```
> I loaded the [the Harbor DB Schema](https://github.com/vmware/harbor/blob/release-1.5.0/make/photon/db/registry.sql) in the database and it worked
> 
> Version of mysql :
> 
> ```
> # mysql --version
> mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for Linux (x86_64) using readline 5.1
> ```

I use harbor of 1.7.4 version, and connect to a external db by setting `harbor.cfg`. But after running install.sh, there are still harbor-db container, how do you solve it ? I want to remove `harbor-db` container.
