### ISSUE TITLE
(Re)Installing Helm and Clair

### ISSUE THREAD

**Issue by sbirl** [goharbor/harbor#7249]
**New user to harbor**.  Pulled down harbor-online-installer-v1.7.4.tgz to an Ubuntu 18.04.2.
Ran the installer with Clair and Helm additions using a self-signed cert.  Couple of people created projects and one user uploaded Helm charts.
Days later I ~~replaced~~ clobbered the self-signed cert with a valid GlobalSign cert; executed `docker-compose down -v` and `docker-compose up -d`.  Found out that Clair has disappeared; no option to Scan, no vulnerabilities shown ... nothing.  Also Helm has disappeared too; similar to https://github.com/goharbor/harbor/issues/7239 I can browse to project's helm-chart URL, but there are no charts to be found.
So how do I go about re-installing (re-activating) Clair and Helm?  I found the online docs (https://github.com/goharbor/harbor/blob/master/docs/user_guide.md) lacking this information.

**Expected behavior and actual behavior:**
I would expect that Clair and Helm would remain active when swapping certificates, or at least throw a notice as to why they were deactivated.  

**Steps to reproduce the problem:**
* Create self-signed cert
* Install Harbor from tarball
* Add some projects, repos, etc.
* Wait a couple of days
* Install valid certificate; clobbering the self-signed files.
* docker-compose down -v
* docker-compose up -d
* Go back to website and find features missing.

**Versions:**
- harbor version: 1.7.4
- docker engine version: 18.09.3, build 774a1f4
- docker-compose version: 1.17.1

**Comment by hctac** [comment]
The interesting thing is when you re-login, they come back for a while......

**Comment by sbirl** [comment]
Sadly, not in my case.

**Comment by sbirl** [comment]
Re-running `sudo ./install.sh --with-notary --with-clair --with-chartmuseum` to completely re-install harbor has, at least, brought back Clair.  I still dont see Helm.  Good thing is the projects look to be intact.

**Comment by sbirl** [comment]
Finally found Helm along with the uploaded charts.
