### ISSUE TITLE
Is possible recover a Harbor without Database backup and only with repository images in Filesystem?

### ISSUE THREAD

**Issue by gunboe** [goharbor/harbor#7250]
Hi,
I lost the Harbor database ("/data/databse"), but I still have the images stored in the Filesystem ("/data/registry").
Is it possible to rebuild the Harbor without the Database but with the images stored in the Filesystem?

Tks,
Gunther

**Comment by heww** [comment]
Current harbor support sync images from the docker distribution, the only limit is that projects should be created before sync.

If all projects created in the new database, then set `SYNC_REGISTRY` to `true` and restart the harbor, the images in the distribution will sync to harbor.

**Comment by gunboe** [comment]
Thanks for your answer, but Would you know why this feature is not setup by default?
And would not be better If the Project automatically would be created when SYNC_REGISTRY=true?
Is there some issue about it?

**Comment by wy65701436** [comment]
@gunboe it's possible to sync data with registry using `SYNC_REGISTRY`. But I don't think this could resolve your problem cause `SYNC_REGISTRY` depends on DB schema.

I think you can build a docker registry with your data volume, and call the API to list all of the repositories, and then to push them into a new Harbor instance.

**Comment by gunboe** [comment]
Thanks all

**Comment by gunboe** [comment]
Just to reg... `SYNC_REGISTRY` is stored in:
./common/config/core/env

**Comment by gunboe** [comment]
https://github.com/goharbor/harbor/issues/6836#issuecomment-481506641

**Comment by ABHISHARMAV** [comment]
hi all,
If we are set SYNC_REGISTRY to true, then only library project data will restoring from bucket or restoring another project data also which project created by admin?

thank you..

**Comment by heww** [comment]
Yes, you need to create the projects manually before sync.

**Comment by ABHISHARMAV** [comment]
Thank you @heww 

But it's not working for this harbor helm-chart code  https://github.com/goharbor/harbor-helm
or here we need to add extra thing in helm-chart code. Like we set SYNC_REGISTRY to true.

thnaks

**Comment by gauravmeena83** [comment]
added SYNC_REGISTRY=true in commom/config/core/env (as a last line) .. not working. using the latest harbor 2.2.1, docker 19.03, on centos 7.

Is there a method to manully get all the images from data/registry to current harbor?
