### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by k9990009** [goharbor/harbor#7252]
[Step 4]: starting Harbor ...
Creating harbor-log ... error

ERROR: for harbor-log  Cannot start service log: b'oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \\"Cannot set property TasksAccounting, or unknown property.\\""'

use CentOS Linux release 7.2.1511 (Core)。

**Comment by wy65701436** [comment]
@k9990009 can you do some investigation on docker runtime? It should not an issue of Harbor, some related issues that I googled you can refer.

https://github.com/opencontainers/runc/pull/1683
