### ISSUE TITLE
Refactor harbor config file

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#7259]
- [x] remove reload_config
- [x] customize_crt removed
- [x] admiral removed it should added by vic team
- [x] external clair db removed 
- [x] uaa config removed
- [x] remove auth_mode
- [x] remove email_setting
- [x] remove ldap_url
- [x] remove harbor_admin_password
- [x] redis item name change
- [x] internal database can only change password
- [x] add external db
- [x] add info level
- [x] add external_url
- [x] storage format changed 
- [x] secretkey_path migrate
- [x] config default value
- [x] pass ci
- [x] migrating script

**Comment by reasonerjt** [comment]
Closing as fixed.
