### ISSUE TITLE
403 Forbidden create user by api with token

### ISSUE THREAD

**Issue by jcmartins** [goharbor/harbor#7276]
**Docker images**
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
goharbor/chartmuseum-photon     v0.8.1-v1.7.4       7e2272c02339        4 weeks ago         113MB
goharbor/harbor-migrator        v1.7.4              968c31d07d2f        4 weeks ago         678MB
goharbor/redis-photon           v1.7.4              611d1ead0a28        4 weeks ago         99.7MB
goharbor/clair-photon           v2.0.7-v1.7.4       01090529ab14        4 weeks ago         165MB
goharbor/notary-server-photon   v0.6.1-v1.7.4       737518b1b943        4 weeks ago         135MB
goharbor/notary-signer-photon   v0.6.1-v1.7.4       495dc3326120        4 weeks ago         132MB
goharbor/harbor-registryctl     v1.7.4              723aed7bbf8d        4 weeks ago         102MB
goharbor/registry-photon        v2.6.2-v1.7.4       f4743bd7b0d9        4 weeks ago         86.7MB
goharbor/nginx-photon           v1.7.4              dda34e6afafe        4 weeks ago         35.9MB
goharbor/harbor-log             v1.7.4              bf4916eef530        4 weeks ago         81.4MB
goharbor/harbor-jobservice      v1.7.4              1b6a0445ae9c        4 weeks ago         84.1MB
goharbor/harbor-core            v1.7.4              e603b8750d26        4 weeks ago         95.6MB
goharbor/harbor-portal          v1.7.4              2ca1d845cafa        4 weeks ago         40.6MB
goharbor/harbor-adminserver     v1.7.4              5706c65d65dc        4 weeks ago         72.3MB
goharbor/harbor-db              v1.7.4              08d163f732f3        4 weeks ago         136MB

**To get Beaer Token**
curl  -v -k -u "admin:Harbor12345" https://xpto.com/service/token?service=harbor-registry
 Server auth using Basic with user 'admin'
> GET /service/token?service=harbor-registry HTTP/1.1
> Host: xpto.com
> Authorization: Basic YWRtaW46SGFyYm9yMTIzNDU=
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 02 Apr 2019 13:00:37 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 1100
< Connection: keep-alive
< Set-Cookie: sid=1a0719ca147dc7380daf48f64109d94c; Path=/; HttpOnly
< 
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjczSU46NEhSNjpaQkVYOjZOWE46MjNGSDoyWktEOkdQRFM6S1RPSzpZNVZPOjdJSFM6UFJWSzpIR0dHIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1NTQyMTE4MzcsIm5iZiI6MTU1NDIxMDAzNywiaWF0IjoxNTU0MjEwMDM3LCJqdGkiOiJCaFZsTjFnNDhraW9lUWRKIiwiYWNjZXNzIjpudWxsfQ.Wzcn1wq3Z3_NFz3F_o7LFm1SpPpUsQhK_o22fMMN2SlrmTd5e0MufFrOz2LUE5yMzCq34bKG8i8L3NkvQExCgttsZ7RJGRkgLn2QgM52ilRpqXBcT390o_CTtRQaho6tYop5eR6WV1FT8tMINzZ9WzNKyOqbA3XwkjBYkmT_oCB_pZVfOC1sKNatuikI4cgDbcyyXjOTAVey6ktQc61NM6lITHq-_siCbih7zOfL5nH0CWB3vak5f-kHlahW6tTuEFV8PB19PIc0O65RaAE8BSsubMW034P_OyZxwAQ4Omuo6y1Ductj_o3Qs8RwsX1nAuj-YOHSAOQ0EZx_gB29UT5T3kSAxY7mi6atic0p456_VGDfnudl48TeBnarkh56VYDtJalDiTa3_JyeC4LctkZJMFtIvvM9QNXOTgkmxk0XJ_v80SN6VRP6ORMx4-giOuXqxuyBJ0lQV5RpsaJLWDEeBCSBmfMEMLExKOZJXdm0rp-n_jp6JJ6hWzIP7Q-b11GPsseohv8FcBfZPq-nAjsJgj9zZg7Qg3pwGWcXOV_07numyoQuBKDLOAjDiHeRoZHhUUHQqfEwtk9Nm27Q0cruPj_HT8TxOPxS6EQPnOQ0iqLukZY_dQ7bxV9lkgJZ8RUHJWBcd05Vz-b4muixpzm7IrPlLqHt3RiXp68ELYQ",
  "expires_in": 1800,
  "issued_at": "2019-04-02T13:00:37Z"

**Using Beaer token to create a new user**
curl -v -k -X POST https://xpto.com/api/users -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjczSU46NEhSNjpaQkVYOjZOWE46MjNGSDoyWktEOkdQRFM6S1RPSzpZNVZPOjdJSFM6UFJWSzpIR0dHIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1NTQyMTE1MDUsIm5iZiI6MTU1NDIwOTcwNSwiaWF0IjoxNTU0MjA5NzA1LCJqdGkiOiJ5QlZ3WHNkOGJEaTVIaVBaIiwiYWNjZXNzIjpudWxsfQ.jOLTkf8uZEjyQ8cv7xC01jiE3pVUSP0IQX-sltFflD8QBaJLKims-i9jBwbG0BRgMI7QJYbJX33Iso3oGkjUvEBVWOtA0SHDYEUYsQejWWLJCyInlwVnTwlFNZ7zyNVYvTyU6mZqoZlz8jpNqVETktMkgAkbBCqkl3KLy0iT08tfritprsWcKUJg93e32pA7Aw758fbQ4R4XA9ZgKYEBgMFkFuwMZKMUE04zxv0cvsdsGV-HMR6uho5flMB5f1-rTIosezuKya28V4pW9g2SnMeXZEcr_jklI5NesxfYKM_Y_DnK0TI9OhOTa2Iw5-3o0WYSZ4uqQik42GOH9gJij4BlXUdHGmqSq1GJU9oP3bqYb6-pyVGub6aj1kXSK1G5UrwDIJJdJvRe433ZTXzRWsIQ79qPpqU6xQj4x7DS-rzkdTsN8sKVl2u2IfPmWpA3fsHehCLtW0NSTw0Raetacvpn16dQdcszGekUmVyddiIz24dxu5L8qib0-OpE7HDTUDrTP5fAKZMIvnsOoe90k04Vm79rzlZzwx0fMIQb6onO2HpdrebfjwNpPPSXPISc3OEsCySFfV_yo8mDS2kqgcpNwwR__gdOfnsnNgk9pZ3FuaVJoQwYobXR2r-RudK4sEeIE8NYbzC5_nfSLYhcHzajrVPsCDQe4YROjxM9zg0" -D "{"username": "teste", "email": "teste@xpto.com", "password": "test12345", "realname": "test user", "role_name": "", "role_id": 0, "has_admin_role": false}"

 POST /api/users HTTP/1.1
> Host: xpto.com
> User-Agent: curl/7.61.0
> accept: application/json
> Content-Type: application/json
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjczSU46NEhSNjpaQkVYOjZOWE46MjNGSDoyWktEOkdQRFM6S1RPSzpZNVZPOjdJSFM6UFJWSzpIR0dHIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1NTQyMTE4MzcsIm5iZiI6MTU1NDIxMDAzNywiaWF0IjoxNTU0MjEwMDM3LCJqdGkiOiJCaFZsTjFnNDhraW9lUWRKIiwiYWNjZXNzIjpudWxsfQ.Wzcn1wq3Z3_NFz3F_o7LFm1SpPpUsQhK_o22fMMN2SlrmTd5e0MufFrOz2LUE5yMzCq34bKG8i8L3NkvQExCgttsZ7RJGRkgLn2QgM52ilRpqXBcT390o_CTtRQaho6tYop5eR6WV1FT8tMINzZ9WzNKyOqbA3XwkjBYkmT_oCB_pZVfOC1sKNatuikI4cgDbcyyXjOTAVey6ktQc61NM6lITHq-_siCbih7zOfL5nH0CWB3vak5f-kHlahW6tTuEFV8PB19PIc0O65RaAE8BSsubMW034P_OyZxwAQ4Omuo6y1Ductj_o3Qs8RwsX1nAuj-YOHSAOQ0EZx_gB29UT5T3kSAxY7mi6atic0p456_VGDfnudl48TeBnarkh56VYDtJalDiTa3_JyeC4LctkZJMFtIvvM9QNXOTgkmxk0XJ_v80SN6VRP6ORMx4-giOuXqxuyBJ0lQV5RpsaJLWDEeBCSBmfMEMLExKOZJXdm0rp-n_jp6JJ6hWzIP7Q-b11GPsseohv8FcBfZPq-nAjsJgj9zZg7Qg3pwGWcXOV_07numyoQuBKDLOAjDiHeRoZHhUUHQqfEwtk9Nm27Q0cruPj_HT8TxOPxS6EQPnOQ0iqLukZY_dQ7bxV9lkgJZ8RUHJWBcd05Vz-b4muixpzm7IrPlLqHt3RiXp68ELYQ
>
> POST /api/users HTTP/1.1
> Host: xpto.com
> User-Agent: curl/7.61.0
> accept: application/json
> Content-Type: application/json
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjczSU46NEhSNjpaQkVYOjZOWE46MjNGSDoyWktEOkdQRFM6S1RPSzpZNVZPOjdJSFM6UFJWSzpIR0dHIn0.eyJpc3MiOiJoYXJib3ItdG9rZW4taXNzdWVyIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJoYXJib3ItcmVnaXN0cnkiLCJleHAiOjE1NTQyMTE4MzcsIm5iZiI6MTU1NDIxMDAzNywiaWF0IjoxNTU0MjEwMDM3LCJqdGkiOiJCaFZsTjFnNDhraW9lUWRKIiwiYWNjZXNzIjpudWxsfQ.Wzcn1wq3Z3_NFz3F_o7LFm1SpPpUsQhK_o22fMMN2SlrmTd5e0MufFrOz2LUE5yMzCq34bKG8i8L3NkvQExCgttsZ7RJGRkgLn2QgM52ilRpqXBcT390o_CTtRQaho6tYop5eR6WV1FT8tMINzZ9WzNKyOqbA3XwkjBYkmT_oCB_pZVfOC1sKNatuikI4cgDbcyyXjOTAVey6ktQc61NM6lITHq-_siCbih7zOfL5nH0CWB3vak5f-kHlahW6tTuEFV8PB19PIc0O65RaAE8BSsubMW034P_OyZxwAQ4Omuo6y1Ductj_o3Qs8RwsX1nAuj-YOHSAOQ0EZx_gB29UT5T3kSAxY7mi6atic0p456_VGDfnudl48TeBnarkh56VYDtJalDiTa3_JyeC4LctkZJMFtIvvM9QNXOTgkmxk0XJ_v80SN6VRP6ORMx4-giOuXqxuyBJ0lQV5RpsaJLWDEeBCSBmfMEMLExKOZJXdm0rp-n_jp6JJ6hWzIP7Q-b11GPsseohv8FcBfZPq-nAjsJgj9zZg7Qg3pwGWcXOV_07numyoQuBKDLOAjDiHeRoZHhUUHQqfEwtk9Nm27Q0cruPj_HT8TxOPxS6EQPnOQ0iqLukZY_dQ7bxV9lkgJZ8RUHJWBcd05Vz-b4muixpzm7IrPlLqHt3RiXp68ELYQ
> 
< **HTTP/1.1 403 Forbidden**
< Server: nginx
< Date: Tue, 02 Apr 2019 13:06:31 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: sid=d022e8cd96911f33db263037b64d34fe; Path=/; HttpOnly
<

**Comment by wy65701436** [comment]
@jcmartins what's your harbor auth mode? Can you track the status of 'Allow Self-Registration' in the configuration page?

To create a user, 
if Self-Registration is on, you can just the post request to create a new user without authn.
if Self-Registration is off, you have to use the system admin to post your request. 

Harbor does't support to create with token, BTW the token is used for communicating with registry v2.

**Comment by jcmartins** [comment]
I tried created user by Api because my user button is disable how you can see in the picture below

My harbor version **now** is: Version v1.7.4-ce6a6237 I upgrade 1.4 -> 1.6 - 1.7 

If I'm not mistake my problem occurred when I upgrade from 1.6 to 1.7

My auth mode is LDAP and I can login but my new user button is disable.

![users](https://user-images.githubusercontent.com/326909/55478929-484e0f80-55f3-11e9-8784-92174e2e1fb3.png)

**Comment by wy65701436** [comment]
in ldap mode, it doesn’t support creating new user.

**Comment by jcmartins** [comment]
but how to add a new user to a project in ldap mode?

**Comment by reasonerjt** [comment]
@jcmartins user will be onboarded if he's added to a project or login to Harbor using his username/passwod in LDAP

**Comment by stonezdj** [comment]
Work as designed
