### ISSUE TITLE
Missing description/translation after upgrading to v1.7.5

### ISSUE THREAD

**Issue by darkl0rd** [goharbor/harbor#7278]
After upgrading my Harbor instance from v1.6.0 to v1.7.5, I've noticed that the newly added items (such as garbage collect and retag) are missing their descriptive labels in the UI. Instead I am seeing "CONFIG.GC", "GC.CURRENT_SCHEDULE", etc. and "REPOSITORY.RETAG".

I have a clean installation of v1.7.2 running elsewhere which does show the descriptive texts correctly.
Any help/hints/advise would be greatly appreciated!

**Comment by wy65701436** [comment]
please try to clean your browser cache. @darkl0rd

**Comment by zhoumeina** [comment]
1 Please try to hard reload your browser to avoid any cache in it. 
2 If this not working, please check browser console if any api returns 404 or other error. 
3 Please check the portal container works well in your host.

**Comment by darkl0rd** [comment]
confirmed working after clearing browser cache.

I'm not entirely sure why this came out of the cache though - I already accessed a registry in which the description did correctly show & the environment that was upgraded was a re-deployment, which should have theoretically resulted in invalidating the browser cache.
