### ISSUE TITLE
Ping registry error message disappeared 

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#7285]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The error message showing the registry is not reachable disappeared.

![add-registry-error](https://user-images.githubusercontent.com/16573984/55465840-8c133a00-5630-11e9-91d7-91794cb6592e.gif)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: `replication_ng`
- docker engine version: 18.03.0-ce
- docker-compose version: 1.20.1
- OS: MacOS

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by pureshine** [comment]
fixed by #7302
