### ISSUE TITLE
harbor 1.7.4  aliyun oss  chartmuseum 500

### ISSUE THREAD

**Issue by Ethan-2017** [goharbor/harbor#7288]
Apr  3 15:28:33 172.18.0.1 chartmuseum[6116]: {"L":"ERROR","T":"2019-04-03T07:28:33.045Z","M":"[8] Request served","path":"/library/index.yaml","comment":"","latency":"1.683178ms","clientIP":"172.22.0.4","method":"GET","statusCode":500,"reqID":"*************"}
Apr  3 15:29:52 172.18.0.1 chartmuseum[6116]: {"L":"ERROR","T":"2019-04-03T07:29:52.250Z","M":"[11] oss: service returned error: StatusCode=400, ErrorCode=InvalidBucketName, ErrorMessage=The specified bucket is not valid., RequestId=***********","repo":"cloud","reqID":"********************"}

**Comment by Ethan-2017** [comment]
if I not use chartmuseum ,the harbor is fine

**Comment by steven-zou** [comment]
@Ethan-2017 

Only the chart server has a problem when using OSS storage? Image registry will work well, right?

We'll take a look at it.

@ninjadq 

Please have a look, thanks!

**Comment by Ethan-2017** [comment]
@steven-zou Image registry also not work

**Comment by Ethan-2017** [comment]
@steven-zou if i not install chartmuseum with harbor,the registry is well with  using oss。

**Comment by Ethan-2017** [comment]
@ninjadq Only the chart server has a problem when using OSS storage,Image registry  work well,  the ui cannot  display the imges  ,harbor can push and pull the image.

**Comment by Ethan-2017** [comment]
@ninjadq  harbor.cfg  registry_storage_provider_config = accesskeyid: ********************, accesskeysecret: ********************, region: oss-cn-zhangjiakou, endpoint: ********************.oss-cn-zhangjiakou-internal.aliyuncs.com, bucket: ********************, internal: true

**Comment by Ethan-2017** [comment]
@steven-zou How is it going?
