### ISSUE TITLE
UAA cert file problem caused by remove uaa setting from harbor.yml 

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#7295]
In the previous version, if uaa related settings are set. prepare script will copy cert file to proper location.
But now all uaa related settings are user level settings and removed from config file. 
These will influence the tile migration. We need to solve it in harbor 1.8 release

**Comment by reasonerjt** [comment]
@ninjadq this is not configurable via configurations API, we may need to update the docker-compose yaml and mount the cert into `core` container.

**Comment by reasonerjt** [comment]
A new chunk like `UAA -> CA certificate` will be added to harbor.yml

**Comment by reasonerjt** [comment]
Fixed in #7652
