### ISSUE TITLE
unable to delete helm charts

### ISSUE THREAD

**Issue by mdasgit** [goharbor/harbor#7308]
When we are trying to delete any chart, it just gets stuck there. Please refer the screenshot. 
Harbor version : 1.7.0 
Operating System: CentOS Linux 7 (Core)
Docker Engine :   18.09.0

![image](https://user-images.githubusercontent.com/46070532/55590593-eefbf280-5750-11e9-84c3-4dcf4071ed8c.png)

**Comment by mdasgit** [comment]
And after a while "less than 1 minute" turns to 17990 days ago . 

![image](https://user-images.githubusercontent.com/46070532/55590794-86f9dc00-5751-11e9-916c-b816e5e61ee4.png)

**Comment by reasonerjt** [comment]
Looks like an issue in UI, but @mdasgit could you provide the complete log files while you are reproducing this error?

**Comment by mdasgit** [comment]
Hello. Yeah I could. But I am not sure which one is the correct log file for this.

**Comment by reasonerjt** [comment]
Please package all of them and attach to this thread.

**Comment by mdasgit** [comment]
[logs.zip](https://github.com/goharbor/harbor/files/3051820/logs.zip)

**Comment by mdasgit** [comment]
@reasonerjt  those logs were captured while I was trying to delete charts from UI. Meanwhile, if you could help me on how can I remove charts using CLI, That would be a huge help. Please know that Harbor and its components are running as containers. Thank you.

**Comment by pureshine** [comment]
Did not reproduce this issue in harbor1.7.0

**Comment by mdasgit** [comment]
so what's next ? any other suggestions.

**Comment by mdasgit** [comment]
FYI, I have upgraded harbor to 1.7.5 . still no luck.

**Comment by mdasgit** [comment]
Team, any advise here ?

**Comment by ninjadq** [comment]
@mdasgit sorry, I cannot reproduce your issue on my own environment. it seems that your chart file is already deleted. But I have no idea why it still exists on your chart list. Maybe you can try clear Redis cache and sync system time

**Comment by cafeliker** [comment]
I am seeing the same problem, the deleting action is hanged.

**Comment by ninjadq** [comment]
this is a limitation of chartmuseum because your project name contains hyphen and followed by a digit. Chartmuseum can not guess the actual file name of your chart. A workaround is to disable chartmuseum's state file and cache.

**Comment by ylvmw** [comment]
Could you give detailed steps of the workaround to delete the hanged chart?

**Comment by ninjadq** [comment]
@ylvmw you need to
1. stop harbor
2. delete cache both in Redis
3. delete cache in chart data storage
4. start harbor

This issue seems resolved by the chart museum. will upgrade it in future harbor release.

**Comment by ylvmw** [comment]
It worked after deleting the related items in /data/chart_storage/{project}/index-cache.yaml and the files in /data/redis/. Thanks!
