### ISSUE TITLE
Add ability for users to choose a "homepage"

### ISSUE THREAD

**Issue by prbsparx** [goharbor/harbor#7309]
**Is your feature request related to a problem? Please describe.**
Every time I sign in to Harbor I have to search for my specific project, and click on it to get to my repositories.

**Describe the solution you'd like**
I'd like a user profile preference that allows me to choose a "homepage"

**Describe the main design/architecture of your solution**
"Homepage" attribute should be under the **username** menu > **User Profile**
The preference key should be "Homepage"
The value should be a dropdown with at least these values:
- All Projects
- Public Projects
- Private Projects
- Specific Project
- Specific Repository

By default, the value would be set to "All Projects", if the user changes it, then when the user signs in, it will take the user to the item selected in the profile.

**Describe the development plan you've considered**
Asking as a potential future feature if others think it's beneficial as well. I don't have the necessary skillset to develop this functionality

**Comment by xaleeks** [comment]
@prbsparx  Hi, to be completely transparent we will not be doing this anytime in the foreseeable future, it's a bit exotic and can introduce unintended behavior.  I just don't see the utility of this for most users.
