### ISSUE TITLE
Multi-master Replication

### ISSUE THREAD

**Issue by DJAyth** [goharbor/harbor#7311]
I've been working on a test case for Harbor for my employer, and so far liking what I'm seeing, the replication specifically gives some HA capabilities.

I have a question around the replication I've been unable to get answered as of yet. Is it possible to setup two instances of Harbor to replicate to each other. For example:

Instance 1 configured to replicate to Instance 2.
Instance 2 configured to replicate to instance 1.

I am thinking of placing these instances behind a load balancer, and as such a push to the load balancer will send it to one of the backend servers, thereby possibly meaning an image is one one server or another. If I can replicate them between each other than it works. I understand there could be some brief time when one of the instances won't have an image, but that shouldn't be a problem.

What I don't want to have happen is an image get replicated from instance 1 to instance 2, then have instance 2 try to replicate that back to instance 1.

Any help you can give is appreciated!

**Comment by ywk253100** [comment]
Yes, you can. The one instance will do some checking before the replication, if it find that the image already exists on the other instance, it will do nothing.
