### ISSUE TITLE
Error during compiling harbor

### ISSUE THREAD

**Issue by dorukhanguloz** [goharbor/harbor#7312]
I have a problem with compiling and running harbor. 
- docker pull golang:1.11.2
- make install GOBUILDIMAGE=golang:1.11.2 COMPILETAG=compile_golangimage
after that building portal container for photon...: I got an error

harbor@1.7.1 release /build_dir
ng build --prod

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! harbor@1.7.1 release: `ng build --prod`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the harbor@1.7.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-05T21_00_19_248Z-debug.log
The command '/bin/sh -c /entrypoint.sh' returned a non-zero code: 137
make[1]: *** [_build_portal] Error 137
make: *** [build] Error 2

- harbor version: [1.7.1]
- docker engine version: [18.09.2]
- docker-compose version: [1.23.2]

**Comment by ninjadq** [comment]
can you provide your system's information? and check if the container network settings are correct.
