### ISSUE TITLE
Modify secretkey path in docker-compose files by prepare shell script

### ISSUE THREAD

**Issue by Wang-Kai** [goharbor/harbor#7313]
**Is your feature request related to a problem? Please describe.**

I change `secretkey_path` from **/data** to **/home**, and run `prepare` script. The script generates `secertkey` file at `/home`, it is OK. But while i running `install.sh`, the `core` and `adminserver` containers both can't find `secertkey` file.  Due to the docker still mount /data/secretkey to `/etc/adminserver/key`, so the `adminserver` can't find key and not work.

**Describe the solution you'd like**

Modify `docker-compose` files while running `prepare` script, and set the correct mount path according `secretkey_path` in `harbor.cfg` .

**Comment by ninjadq** [comment]
In the previous version, there is an issue in user-customized `secretkey`.
And `secretkey` is removed in the master branch. Also we introduced a new config item `data_volume`. you can specify where you wanna store harbor data. And the `secretkey` will be generated into the data volume automatically.

**Comment by Wang-Kai** [comment]
Does the new config item `data_volume` is workable ? 

I can't find this field in `harbor.conf`.

**Comment by ninjadq** [comment]
@Wang-Kai , you can try the data_volume on code of master branch.
And the config file is `harbor.yml` now

**Comment by reasonerjt** [comment]
@Wang-Kai Any comments on the new implementation?

**Comment by Wang-Kai** [comment]
I am looking forward to the new implementation can be released as soon as possible.
