### ISSUE TITLE
我配置oss存储时镜像仓库服务不能起来。一直重启状态

### ISSUE THREAD

**Issue by alonemen** [goharbor/harbor#7314]
What can we help you?
谁可以告诉我正确的配置harbor为oss镜像存储。

我目前的配置如下（增加了oss部分）：(/usr/local/harbor/common/templates/registry/config.yml)
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  oss:
    accesskeyid: LTAIGThwkdxxx
    accesskeysecret: kjP9qiP64Umxxxx
    region: oss-cn-hangzhou
    endpoint: harbor-caosx.oss-cn-hangzhou.aliyuncs.com
    bucket: harbor-caosx
    secure: false
    internal: true
  cache:
    layerinfo: redis
  $storage_provider_info
  maintenance:
    uploadpurging:
      enabled: false
重启harbor的状态：
       Name                   Command                State                 Ports          
------------------------------------------------------------------------------------------
harbor-adminserver   /harbor/start.sh             Up (healthy)                            
harbor-core          /harbor/start.sh             Up (healthy)                            
harbor-db            /entrypoint.sh postgres      Up (healthy)   5432/tcp                 
harbor-jobservice    /harbor/start.sh             Up                                      
harbor-log           /bin/sh -c /usr/local/bin/   Up (healthy)   127.0.0.1:1514->10514/tcp
                     ...                                                                  
harbor-portal        nginx -g daemon off;         Up (healthy)   80/tcp                   
nginx                nginx -g daemon off;         Up (healthy)   0.0.0.0:443->443/tcp,    
                                                                 0.0.0.0:4443->4443/tcp,  
                                                                 0.0.0.0:80->80/tcp       
redis                docker-entrypoint.sh redis   Up             6379/tcp                 
                     ...                                                                  
registry             /entrypoint.sh /etc/regist   Restarting                              
                     ...                                                                  
registryctl          /harbor/start.sh             Up (healthy)

查看registry的日志，报错信息：(/var/log/harbor/registry.log）
Apr  6 22:22:14 172.19.0.1 registry[1090]: configuration error: error parsing /etc/registry/config.yml: Must provide exactly one storage type. Provided: [filesystem oss]
Apr  6 22:22:14 172.19.0.1 registry[1090]: 
Apr  6 22:22:14 172.19.0.1 registry[1090]: Usage: 
Apr  6 22:22:14 172.19.0.1 registry[1090]:   registry serve <config> [flags]
Apr  6 22:22:14 172.19.0.1 registry[1090]: Flags:
Apr  6 22:22:14 172.19.0.1 registry[1090]:   -h, --help=false: help for serve
Apr  6 22:22:14 172.19.0.1 registry[1090]: 
Apr  6 22:22:14 172.19.0.1 registry[1090]: 
Apr  6 22:22:14 172.19.0.1 registry[1090]: Additional help topics:
Apr  6 22:22:14 172.19.0.1 registry[1090]:

**Comment by reasonerjt** [comment]
Please make update to fix the error:
```
Apr 6 22:22:14 172.19.0.1 registry[1090]: configuration error: error parsing /etc/registry/config.yml: Must provide exactly one storage type. Provided: [filesystem oss]

```
