### ISSUE TITLE
Registry support for S3 region ca-central-1

### ISSUE THREAD

**Issue by DJAyth** [goharbor/harbor#7319]
**Expected behavior and actual behavior:**
Attempting to setup the registry to use S3 for storage and set the region to ca-central-1 the Canada region.

**Steps to reproduce the problem:**
Set region in config.yml to ca-central-1

**Versions:**
- harbor version: [1.7.5]

Log detail from registry.log:
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: github.com/docker/distribution/registry/handlers.NewApp(0x1067820, 0xc42034a8a0, 0xc4201f1500, 0x1067820)
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: github.com/docker/distribution/registry.NewRegistry(0x7ff15ad06198, 0xc42034a8a0, 0xc4201f1500, 0xe, 0x0, 0x0)
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: github.com/docker/distribution/registry.glob..func1(0x108f1a0, 0xc42033c2f0, 0x1, 0x1)
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108f1a0, 0xc42033c2a0, 0x1, 0x1, 0x108f1a0, 0xc42033c2a0)
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108f340, 0xc4201a5f40, 0xc4200001a0)
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: main.main()
Apr  8 18:12:16 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: #011/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
Apr  8 18:12:42 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]: panic: Invalid region provided: ca-central-1
Apr  8 18:12:42 ip-192-168-16-1.ca-central-1.compute.internal registry[3207]:

**Comment by DJAyth** [comment]
Total novice but I think that docker distribution 2.7.0 totally eliminated the dependency on hard coded aws regions and used the aws sdk to verify details: https://github.com/docker/distribution/releases/tag/v2.7.0

**Comment by ywk253100** [comment]
We have bumped up the registry version to 2.7.1 in master branch, this will be available in release 1.8.

**Comment by sruziev** [comment]
Having same invalid region with  me-central-1 
`panic: Invalid region provided: me-central-1`
Any suggestions?

Harbor version `Version v2.2.3`
