### ISSUE TITLE
How can I make image pull/push as default to the library project?

### ISSUE THREAD

**Issue by ken-zheng** [goharbor/harbor#7332]
How can I make image pull/push as default to the library project?
This setup is similar to docker.io.
e.g.
$ docker  pull mysql:5.6
it will try pull from library/mysql:5.6.
and 
$ docker push mysql:5.6
it will try push to library/mysql:5.6.

**Comment by ywk253100** [comment]
Just specify the `library` in your push/push command:
```
docker push/pull harbor.local/library/mysql:5.6
```

**Comment by ken-zheng** [comment]
It's more related to the docker client CLI. Not quite related to harbor.

**Comment by mrmm** [comment]
Hello @ken-zheng,  did you find a way to make this work as mentioned in your first issue ?
