### ISSUE TITLE
API /health returns 404

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#7348]
**Expected behavior and actual behavior:**
curl -k -u admin:Harbor12345 https://localhost/api/health returns HTTP200 with some JSON
The /health should be working according to the swagger file.

**Steps to reproduce the problem:**
Install Harbor 1.7.4 or 1.7.5 (haven't tried in older versions)
run: curl -k -u admin:Harbor12345 https://localhost/api/health

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.5]
- docker engine version: [1.13.1]
- docker-compose version: [1.18.0]

**Additional context:**
* **Harbor config files:**
* **Log files:**
$ sudo tail /var/log/harbor/proxy.log
Apr 11 11:52:15 172.18.0.1 proxy[79247]: 127.0.0.1 - "GET / HTTP/1.1" 308 188 "-" "curl/7.59.0" 0.000 - .
Apr 11 11:52:30 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.011 0.011 .
Apr 11 11:52:45 172.18.0.1 proxy[79247]: 127.0.0.1 - "GET / HTTP/1.1" 308 188 "-" "curl/7.59.0" 0.000 - .
Apr 11 11:52:57 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.008 0.008 .
Apr 11 11:53:15 172.18.0.1 proxy[79247]: 127.0.0.1 - "GET / HTTP/1.1" 308 188 "-" "curl/7.59.0" 0.000 - .
Apr 11 11:53:45 172.18.0.1 proxy[79247]: 127.0.0.1 - "GET / HTTP/1.1" 308 188 "-" "curl/7.59.0" 0.000 - .
Apr 11 11:54:01 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.010 0.010 .
Apr 11 11:54:01 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.006 0.007 .
Apr 11 11:54:02 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.007 0.007 .
Apr 11 11:54:02 172.18.0.1 proxy[79247]: 172.18.0.1 - "GET /api/health HTTP/1.1" 404 1090 "-" "curl/7.29.0" 0.006 0.007 .

**Comment by reasonerjt** [comment]
there's no such api in `v1.7.5`

**Comment by balonik** [comment]
@reasonerjt according to this there is
https://github.com/goharbor/harbor/blob/master/docs/swagger.yaml

**Comment by reasonerjt** [comment]
That is master branch...
