### ISSUE TITLE
ConvertResourceMetadata failed for one resource would fail the whole execution

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#7361]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

When ConvertResourceMetadata failed for one resource, all other resources will lose the chance to be processed, resulting the whole execution failed, without any tasks created.

![image](https://user-images.githubusercontent.com/16573984/56034509-05f6a200-5d5a-11e9-8bea-ad6d22cdbf84.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ywk253100** [comment]
The method `ConvertResourceMetadata` is removed, and if the registry doesn't support one specific image format, the task will fail.
