### ISSUE TITLE
PrepareForPush will result to too many namespace creation requests

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#7362]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

`PrepareForPush` is called for every resource, and will try to create namespace in target registry. This will result to too many namespace creation requests sent to registry.

`PrepareForPush([]*model.Resource)` should be better, and we can get the namespace set before sent requests.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by kofj** [comment]
mark

**Comment by ywk253100** [comment]
Fixed by #7403 .
