### ISSUE TITLE
The health check for registry should only check the connection

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7367]
Currently, the health check for registry will check both the connection and the credential if it is provided. This may be weird: if I provide a wrong credential, the health check fails, but if I provide no credential, it successes.

And even though I provide a wrong credential, the registry can be used in pull mode if the images are public. So the connection is required but the credential isn't.

Maybe we can add a button `Check credential` on UI for users to check the credential if needed.

**Comment by cd1989** [comment]
I suggest to provide a `Anonymous Access` switch in frontend, if it's selected, the credential inputs should be hidden, in this case, user cares no credential, and we only checks the connection.

If user provide credential, we should check the credential.
