### ISSUE TITLE
定期删除镜像策略

### ISSUE THREAD

**Issue by lx308033262** [goharbor/harbor#737]
想提个小的需求 应该也会有很多人有 
随着我们仓库的越来越大  存储的镜像也越来越多 但是有很多镜像我们一段时间后就不用了
所以 是否可以新增一个镜像定期删除策略 由用户自定义保留多久以前的镜像
建议策略 粒度越小 优先级越高 
比如项目定义保留30天以内的镜像
某个仓库保留60天 就保留60天

**Comment by quickwind** [comment]
+1 This would be great feature to have, especially our development harbor is growing with more frequent SNAPSHOT images, defining a cleanup policy so that SNAPSHOT images will only be kept for no more than a period is great for maintenance.

**Comment by quickwind** [comment]
Any feedback on this? Anybody?

**Comment by reasonerjt** [comment]
We need to think about it, to provide a policy that is smart enough

**Comment by moooofly** [comment]
+1
from `swagger.yaml`, I find `GET /repositories/top` API to get public repositories which are accessed most.

And I need such a feature that getting public repositories which are accessed least. So I can delete them manually at least.

tks in advance.

**Comment by reasonerjt** [comment]
Let's track this issue via #5882
