### ISSUE TITLE
Wrong error message is shown to users when creating registries

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7372]
The error message and the real error don't match.
<img width="1488" alt="create_registry" src="https://user-images.githubusercontent.com/5835782/56074310-7943f680-5de2-11e9-9741-73b5e3cf3fb1.png">

**Comment by cd1989** [comment]
For DockerHub type, shouldn't display URL input. And frontend add the `https://hub.docker.com` automatically.

**Comment by pureshine** [comment]
done as pr #7393
