### ISSUE TITLE
Support proxy when replication

### ISSUE THREAD

**Issue by kofj** [goharbor/harbor#7378]
**Is your feature request related to a problem? Please describe.**
At some network environment, maybe cannot connect to remote registry like grc.io/quay.io.

**Describe the solution you'd like**
Let the replication task use a proxy.

**Describe the main design/architecture of your solution**

**Describe the development plan you've considered**

**Additional context**

**Comment by watchmen1992** [comment]
this is my design/architecture
![image](https://user-images.githubusercontent.com/28006018/56340458-9282e380-61e4-11e9-9f30-165669da30e8.png)


The endpoints for mirror replication of regionA and B are both configurable domain names, but now the replication and deletion functions are not available.

**Comment by watchmen1992** [comment]
My harbor version is 1.7.4. Does the current version support this approach?

**Comment by ywk253100** [comment]
@kofj  Double checked, the proxy is supported already.

@watchmen1992 Please open another new issue to describe your issue
