### ISSUE TITLE
can't startup if not config tls

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#7389]
I'm building master branch.
After run "make all", can't start up.

Error message:
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.proxy.ports is invalid: Port ranges don't match in length

The docker-compose.yml is not correct rendered.

**Comment by ninjadq** [comment]
hi @bitsf you can remove https configs if you don't wanna https

**Comment by ninjadq** [comment]
fixed in #7612 
set default to http
