### ISSUE TITLE
Robot account password

### ISSUE THREAD

**Issue by dnmgns** [goharbor/harbor#7394]
The documentation mentions a password (Thepasswordgeneratedbyprojectadmin ) at https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#authenticate-with-a-robot-account but it's not possible to generate any password.

This raises some questions:
1) It's not possible to create a password?
2) This feature is not implemented yet?
3) "The password" is actually the Account token? (I guess not, as it can't be used for docker login)

**Comment by wy65701436** [comment]
@dnmgns, it's actually using the token to docker login, named `password` in the user guide. The feature has already done and merged into the master branch, it will be introduced in the coming release.

**Comment by dnmgns** [comment]
@wy65701436 - Thanks for the information. 

I suggest that you only use the phrase "password" or "token" in the user guide.

I've realised that it's not possible to use robot accounts when using LDAP as authentication source - I'd thought that failed LDAP authentication could/would fallback to local authentication when failed (or simply that local authentication would be used when the username was in the format of robot$username). Instead, harbor makes an LDAP search for user 'robot'.
