### ISSUE TITLE
Show execution message.

### ISSUE THREAD

**Issue by kofj** [goharbor/harbor#7395]
**Is your feature request related to a problem? Please describe.**
When a execution failed, there no any useful information tell user why it failed at the executions list.

**Describe the solution you'd like**
Show status message.

**Describe the main design/architecture of your solution**
executions list api result example:
``` json
[{
    "id": 90,
    "policy_id": 6,
    "status": "Failed",
    "status_text": "failed to fetch repository: http error: code 401, message {\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"no/test/alpine\",\"Action\":\"pull\"}]}]}\n",
    "total": 0,
    "failed": 0,
    "succeed": 0,
    "in_progress": 0,
    "stopped": 0,
    "trigger": "manual",
    "start_time": "2019-04-15T09:52:00.258955Z",
    "end_time": "0001-01-01T00:00:00Z"
  }]
```
The executions list api has give the `status_text` filed, show it to user.

**Comment by ywk253100** [comment]
It is already implemented:
![tip](https://user-images.githubusercontent.com/5835782/56712567-87d6ca00-6761-11e9-8a89-d738b9d0e1e7.png)
