### ISSUE TITLE
Scan task never ends in UI

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7402]
Nightly CI test case "Manual Scan All" failed, according to robot log, it seems like it was scanning for a long and unacceptable time. And then I test this case manually, it's indeed that "Scanning" status was there all the time.

![image](https://user-images.githubusercontent.com/44018302/56194721-21b5bd00-6066-11e9-882d-cb882a1b5726.png)

**Comment by pureshine** [comment]
It's a configuration of project (Automatically scan images on push).

**Comment by danfengliu** [comment]
I've reproduced this issue, and captured network packages, it looks like UI get tag information only for one time no mater what scan status it was.

![image](https://user-images.githubusercontent.com/44018302/56333940-d2d46880-61c8-11e9-852c-c827ec197964.png)
