### ISSUE TITLE
Can harbor v1.7.4 use with redis cluster?

### ISSUE THREAD

**Issue by shitou1992** [goharbor/harbor#7409]
when i use harbor v 1.7.4 with redis cluster(3 master and 3 slave);
the harbor-jobservice always restart ,there are some errors in log:
Failed to load and run work pool: connect to redis  server  timeout: ERR SELECT is not allowed in cluster mode

**Comment by jpsmoura** [comment]
@shitou1992 I'm getting the same behaviour. Was it fixed in the end?

**Comment by mfmessaoudi** [comment]
I'm facing the same issue
@jpsmoura  did you find a fix
thanks
