### ISSUE TITLE
Add Custom Endpoint Capacity for replication adapter.

### ISSUE THREAD

**Issue by kofj** [goharbor/harbor#7411]
**Is your feature request related to a problem? Please describe.**
Some adapter not support custom endpoint, like docker hub. Now, frontend hidden custom endpoint UI element if adapter is docker hub.

**Describe the solution you'd like**
Hidden custom endpoint UI element if adapter not support it according the Custom Endpoint Capacity info in the registry list api.

**Describe the main design/architecture of your solution**
Add Custom Endpoint Capacity.

**Comment by ywk253100** [comment]
As there are some details that need to be considered, we implement this in UI in version 1.8.
Move this out of the 1.8 scope.

**Comment by kofj** [comment]
> As there are some details that need to be considered, we implement this in UI in version 1.8.
> Move this out of the 1.8 scope.

OK, what's plan? I think we need not delay to 1.9.
