### ISSUE TITLE
Does Harbor already offer webhook ?

### ISSUE THREAD

**Issue by charles1503** [goharbor/harbor#7416]
I use Harbor as Docker Repoitry and Jenkins CI/CD , I hope to trigger some other businesses through webhook by listening to the image push event. Is there webhook in Harbor?

**Comment by wy65701436** [comment]
not yet, and it will not be in the coming release（v1.8.0). But, it's already in the roadmap, and the proposal has already drafted and discussed. https://github.com/goharbor/community/pull/36

**Comment by wy65701436** [comment]
@charles1503 you can keep monitoring the proposal, let's close this issue.
