### ISSUE TITLE
Vulnerable database updates occupy high computing resources

### ISSUE THREAD

**Issue by justinmjc** [goharbor/harbor#7425]
harbor version: v1.6.1-98bcac6c
db ： aliyun PostgreSQL 9.4   pg.x8.medium.2

Vulnerable database updates occupy high computing resources
how can i set the time to update Vulnerable database?
occupy high computing resources when pdate Vulnerable database seems like not normal

![image](https://user-images.githubusercontent.com/16958022/56333663-a9ffa380-61c7-11e9-80d6-0cbbc192cefc.png)
![image](https://user-images.githubusercontent.com/16958022/56333676-b552cf00-61c7-11e9-9ba1-0a9bf246d9e2.png)

**Comment by wy65701436** [comment]
you can increase the value of clair_updaters_interval in the harbor.cfg.

**Comment by justinmjc** [comment]
> you can increase the value of clair_updaters_interval in the harbor.cfg.

there has 2 harbor instance , I try to set clair_updaters_interval =0 for one of that 2 instances

**Comment by reasonerjt** [comment]
@justinmjc that's the expected status as it involves extracting data from the internet, does it keep the high load of CPU for very long?

You can tweak the `cpu_shares` and other parameter to lower the usage of CPU.

**Comment by justinmjc** [comment]
@reasonerjt thanks  for you replying .  it usually take 2 hours ,I am strange why it take so long . I have set clair_updaters_interval =0 for one of that 2 instances and improved the  cpu to that pgsql . now the problem is no longer reappear

**Comment by reasonerjt** [comment]
@justinmjc let me clarify, did you see high CPU consumption on which container?  the `clair` or `pgsql`?

**Comment by justinmjc** [comment]
> let me clarify, did you see high CPU consumption on which container? the `clair` or `pgsql`?

pgsql

**Comment by reasonerjt** [comment]
@justinmjc 
That happens because during the initialization of clair DB, clair process will insert hundreds of thousands of records into DB, so the pgsql process may require more CPU than usual operations.

I recall when one process is doing the insert it will lock the DB, and we don't see this problem when we are testing the HA scenario.  Did you observe the high CPU load only when you setup multiple clair instances?

**Comment by flixgithub** [comment]
i also meet this kind of issue by deploy two harbors behind a loadbalance, then set clair.updaters_interval: 0 in harbor.yml file of one node , it will decrease the PostgreSQL CPU usage
