### ISSUE TITLE
Can not find Helm Charts and Vulnerability scan in free harbor 1.7.0

### ISSUE THREAD

**Issue by HelenaZheng** [goharbor/harbor#7427]
I installed habor 1.7.0 through the tar files from https://github.com/goharbor/harbor/releases.

When I read the user guid in github, but I can not find the Vulnerability scan or Helm Charts  in harbor UI.

Does the free version not have the two function? If not, how can i find and use the two?

**Comment by zhoumeina** [comment]
@HelenaZheng , if you want to see vulnerability and helm chart tab. You need to install harbor with --with-clair --with-chartmuseum options.
