### ISSUE TITLE
Needs tool tips for creating replication rule

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7428]
When I try to create a new replication rule, I don't know how to add filter and what's the meaning of override, and etc.

![image](https://user-images.githubusercontent.com/2841473/56341023-5badcd00-61e6-11e9-962e-cb4654bce54a.png)

**Comment by ywk253100** [comment]
`Push-based`: Push the resources from the current Harbor to the remote registry 把资源由当前Harbor推送到远端仓库
`Pull-based`: Pull the resources from the remote registry to the current Harbor 把资源由远端仓库拉取到当前Harbor

`Name filter`: Filter the name part of the resources. Leaving empty or "**" matches all; "library/**" only matches the resources under "library". For more patterns please refer to the user guide. 过滤资源的名字。不填或者“**”匹配所有资源；“library/**”只匹配“library”下的资源。更多的匹配模式请参考用户手册。

`Tag filter`: Filter the tag/version part of the resources. Leaving empty or "**" matches all; "1.0*" only matches the tags that starts with "1.0". For more patterns please refer to the user guide. 过滤资源的tag/version。不填或者“**”匹配所有；“1.0*”只匹配以“1.0”开头的tag/version。

`Resource filter`: Filter the type of the resources. 过滤资源的类型。

`Destination namespace`: Specify the destination namespaces. The resources will be put under the same namespace with the source if it is empty. 指定目的端名称空间。如果不填，资源会被放到和源相同的名称空间下。

`Override`: Specify whether override the resources if the same name resources found on the destination registry. 指定如果目的端仓库中已有同名的资源是否覆盖。
