### ISSUE TITLE
'Event Based' should be disabled in pull mode

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7438]
We need to disable the trigger of event base when the user creates a pull mode replication rule.

![image](https://user-images.githubusercontent.com/2841473/56349123-7be78700-61fa-11e9-825a-a6655335c329.png)

**Comment by zhoumeina** [comment]
I think this supported_trigger type should be removed from get registry info api. So frontend does not need to deal with it.

**Comment by ywk253100** [comment]
Fixed.
