### ISSUE TITLE
add user function hard to find 

### ISSUE THREAD

**Issue by tronicum** [goharbor/harbor#744]
0.3.5-rc from hub.docker.com

It took a while to find the add user dialog. all other resources can be added by "+add [destnation|projects|new policy|etc.]". I would wish to have a "+add user" button on the "users" tab to make the UI consistent.

**Comment by bergtwvd** [comment]
Maybe this can be addressed in combination with https://github.com/vmware/harbor/issues/779.

**Comment by lwh** [comment]
Where do you find it exactly?

**Comment by reasonerjt** [comment]
I believe this is no longer an issue after UI rework.
