### ISSUE TITLE
push image to s3 timeout

### ISSUE THREAD

**Issue by Chinaxiang** [goharbor/harbor#7440]
When I use harbor to push image to S3, I meet an error.

Apr 18 18:33:44 172.18.0.1 proxy[28102]: 2019/04/18 10:33:44 [error] 9#0: *971 upstream timed out (110: Connection timed out) while sending request to upstream, client: 192.168.23.9, server: , request: "PATCH /v2/library/vmware/registry-photon/blobs/uploads/feb2aac1-8d18-4cda-b58c-ce113cc2f03c?_state=0E-LLBFPa2n45l30klphg-cMtnyhJgKeJO0DpZJ10YZ7Ik5hbWUiOiJsaWJyYXJ5L3Ztd2FyZS9yZWdpc3RyeS1waG90b24iLCJVVUlEIjoiZmViMmFhYzEtOGQxOC00Y2RhLWI1OGMtY2UxMTNjYzJmMDNjIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE5LTA0LTE4VDEwOjMyOjE1Ljk1NDA4MTk5OFoifQ%3D%3D HTTP/1.1", upstream: "http://172.18.0.5:8080/registryproxy/v2/library/vmware/registry-photon/blobs/uploads/feb2aac1-8d18-4cda-b58c-ce113cc2f03c?_state=0E-LLBFPa2n45l30klphg-cMtnyhJgKeJO0DpZJ10YZ7Ik5hbWUiOiJsaWJyYXJ5L3Ztd2FyZS9yZWdpc3RyeS1waG90b24iLCJVVUlEIjoiZmViMmFhYzEtOGQxOC00Y2RhLWI1OGMtY2UxMTNjYzJmMDNjIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE5LTA0LTE4VDEwOjMyOjE1Ljk1NDA4MTk5OFoifQ%3D%3D", host: "192.168.83.124:81"

**Comment by Chinaxiang** [comment]
```
docker push 192.168.83.124:81/library/vmware/registry-photon:v2.6.2-v1.5.1
The push refers to repository [192.168.83.124:81/library/vmware/registry-photon]
f02b4f30a9ac: Layer already exists 
557669a074de: Layer already exists 
cb5d493833cc: Layer already exists 
bd3ac235b209: Layer already exists 
5fa6889b9a6d: Layer already exists 
9bd5c7468774: Layer already exists 
52ef9064d2e4: Pushing [==================================================>]    130MB/130MB
received unexpected HTTP status: 504 Gateway Time-out
```

How can I improve it?

**Comment by lf1029698952** [comment]
you can add timeout setting in nginx.conf
#3446
