### ISSUE TITLE
unable to login with docker: unauthorized

### ISSUE THREAD

**Issue by dneuge** [goharbor/harbor#7464]
I am unable to log in to Harbor using docker. Web-UI is working fine, an account is set up as admin and I can log in to the web frontend using the same credentials as on command line. However, every attempt to log in on CLI fails with:

  `Error response from daemon: Get https://xyz.mydomain.net:1234/v2/: unauthorized: authentication required`

There are no helpful log messages anywhere; no error messages are logged.

Previous reports of this issue (all without solution but closed?) stated that older Docker releases could successfully login. I tried with 18.06.2, 18.09.4 and 18.09.5, all yield the same result.

I have to assume Harbor in its latest version is currently broken and not ready for deployment. A stable release would be appreciated.

## What I tried:

1. Installed a new Ubuntu Server 18.04 LTS VM with Docker CE from Docker's RPM repository, installed Python 2.7, installed acmetool and registered a Let's Encrypt certificate.
2. Downloaded the online installation package for Harbor.
3. Configured harbor.cfg with custom passwords and using the Let's Encrypt certificate.
4. Installed Harbor with Clair and Notary.
5. Forwarded an alternate port of the host machine to the VM's HTTPS port using NAT. Default ports for HTTP and HTTPS on host proxy server redirect to alternate VM port using 307 status code to instruct clients to restart their request.

Item 5 resulted from an earlier failed attempt to simply proxy HTTPS from host to VM; at that time I thought Apache on the host would remove credentials while forwarding the request but the error message remained the same after moving Harbor to a dedicated port with a dedicated certificate.

## What works:

- logging in on web frontend as admin
- configuring Harbor through web frontend
- adding a new user
- logging in as the new user
- setting up a new project

## What does not work:

- `docker login xyz.mydomain.net`
- `docker login xyz.mydomain.net:1234`
- `docker login xyz.mydomain.net:1234/myproject`
- `docker push xyz.mydomain.net/myproject/myimage:mytag`
- `docker push xyz.mydomain.net:1234/myproject/myimage:mytag`

## Observed:

- Docker CLI quits with an error message:

  `Error response from daemon: Get https://xyz.mydomain.net:1234/v2/: unauthorized: authentication required`

- Attempting to push an image to Harbor fails with an error message:

  `denied: requested access to the resource is denied`

- All containers are up and healthy according to `docker ps`.

- There are no error messages in Harbor's logs.

**Comment by stonezdj** [comment]
Add item to /etc/docker/daemon.json 
	`"insecure-registries": ["0.0.0.0/0"]`
and restart docker daemon and try again?

**Comment by dneuge** [comment]
I just tried to configure that option in multiple places, global config, user config and service parameter. I also tried the exact IP address and port number. Unfortunately it doesn't help.

I would have been surprised if it did as I see the SSL certificate has been correctly installed when accessing the same port through a web browser. Let's Encrypt is also trusted outside the browser by the system's SSL chain, so I don't think SSL can be the issue here?

**Comment by reasonerjt** [comment]
could you reproduce and provide the logs?  is it possible you are using some character in the password such as "$" and the command in shell mis-interpreted it?

**Comment by dneuge** [comment]
Supplying login credentials through command-line parameters is highly insecure, so I used the interactive mode instead. Just to rule out any mistake, I created a new test user with a very simple password and supplied it via command line. It still yields the same result: "unauthorized: authentication required"

I removed any special characters from my regular user's password: No effect.

It also does not matter if the user is an admin or an unprivileged user.

Authentication works fine to other Docker registries, such as Nexus 3, so I am fairly certain I can rule out any client-side issues.

Logs are attached (personal data removed): [190430_issue7464_logs.tar.gz](https://github.com/goharbor/harbor/files/3132406/190430_issue7464_logs.tar.gz)

Login attempt was at 17:05:52 UTC / 19:05:52 CEST.

What I see is directly related to my requests:

core.log
```
Apr 30 19:05:53 172.26.0.1 core[916]: 2019/04/30 17:05:53 #033[1;44m[D] [server.go:2619] |  111.222.33.44|#033[43m 401 #033[0m|   4.015243ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
```

proxy.log
```
Apr 30 19:05:53 172.26.0.1 proxy[916]: 111.222.33.44 - "GET /v2/ HTTP/1.1" 401 87 "https://xyz.mydomain.net/v2/" "docker/18.09.4 go/go1.12.1 git-commit/d14af54 kernel/4.19.27-gentoo-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \x5C(linux\x5C))" 0.005 0.004 .
Apr 30 19:05:53 172.26.0.1 proxy[916]: 111.222.33.44 - "GET /service/token?account=mytestuser&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.1" 401 0 "https://xyz.mydomain.net/service/token?account=mytestuser&client_id=docker&offline_token=true&service=harbor-registry" "docker/18.09.4 go/go1.12.1 git-commit/d14af54 kernel/4.19.27-gentoo-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \x5C(linux\x5C))" 0.000 0.000 .
```

registry.log
```
Apr 30 19:05:53 172.26.0.1 registry[916]: time="2019-04-30T17:05:53.157904077Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host="xyz.mydomain.net:8123" http.request.id=4a5665de-8e77-4a7a-adf9-3f444f892055 http.request.method=GET http.request.referer="https://xyz.mydomain.net/v2/" http.request.remoteaddr=111.222.33.44 http.request.uri="/v2/" http.request.useragent="docker/18.09.4 go/go1.12.1 git-commit/d14af54 kernel/4.19.27-gentoo-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \\(linux\\))" instance.id=35412453-7fe0-4211-8ef1-8ca007275e92 service=registry version=v2.6.2 
Apr 30 19:05:53 172.26.0.1 registry[916]: 172.26.0.8 - - [30/Apr/2019:17:05:53 +0000] "GET /v2/ HTTP/1.1" 401 87 "https://xyz.mydomain.net/v2/" "docker/18.09.4 go/go1.12.1 git-commit/d14af54 kernel/4.19.27-gentoo-r1 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \\(linux\\))"
```

Additionally, there are messages in notary-server.log about Notary not knowing Let's Encrypt? (`transport: x509: certificate signed by unknown authority`) However, I am far from accessing Notary without having a working login first; so this may be another issue for later and not relevant yet...

**Comment by Zebradil** [comment]
I'm experiencing the same issue. However, I don't own the registry and can't provide additional information.

**Comment by reasonerjt** [comment]
@dneuge 
Sorry for the late response, but it does seem you provided wrong credentials,
my guess is that in there's some special chars in your credentials that should be escaped.

So could you clarify that this error only happens to some particular users?

**Comment by immanuelfodor** [comment]
For anyone in the future who bumps into this, my problem was the same, docker couldn't login. In my case, Harbor was installed with Helm, and I was formatting the helm install command with bash with a pre-calculated htpassword value:

```bash
cat <<EOF
helm install harbor harbor/harbor \\
...
--set registry.credentials.htpasswd="$registrycredentialshtpasswd" \\
...
EOF
```

It substituted the htpass fine, the output was nice and all, but as I used double quotes and the generated pass contained $ signs, these became another variable substitutions on the Helm install run, and as these small variables never existed, the generated pass was not saved into the k8s secret as it should but became shorter. Hence, docker couldn't login as the login credentials were fine but the core couldn't communicate with the registry through its htpass.

What gave away the problem was getting the registry pod's logs, and there were the `msg="error authenticating user "htpass_username": authentication failure"` lines.

I used the `base64` CLI utility to recalculate the valid htpass content's encoded version, then substituted this in the `harbor-harbor-registry` secret, then deleted the registry pod which was recreated immediately by k8s. Now docker could login fine. 

If you use cat to template the Helm install command, you can just use single quotes here as cat will substitute the variable anyways, and so you'll get the Helm install command output fine with no more variable substitution over the password:

```bash
cat <<EOF
helm install harbor harbor/harbor \\
...
--set registry.credentials.htpasswd='$registrycredentialshtpasswd' \\
...
EOF
```

Such a tiny mistake, facepalm :D

**Comment by osaffer** [comment]
Hi,

Is anyone found the solution?
For me documentation is really not clear.
I did installation with helm, and in values file, we can set user and password for registry.
Like this, we can login with that only user.

But what for the users we create in Harbor through the WebUI ?

Of course with user created in WebUI I cannot login with docker login, I can push image only with user defined in values file, BUT, the image is not visible into the UI.

Is it possible to have a clear configuration ?

Regards,

**Comment by th3walkingdud3** [comment]
This topic is a little old but I will put the solution I found here for future use:
When doing a docker login, the username is the harbor username found in the UI, top lefthand corner.  The password is the cli token found in the user profile pane, not your harbor password.

**Comment by Parsonswy** [comment]
For anyone having trouble with robot account logins that finds this issue, [these docs](https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/create-robot-accounts/#legacy-robot-accounts) on logging in with service accounts might be useful. For robot accounts that have access to all projects you do not need to put the project name in the username string.

Our install also came with the robot prefix set to `robot$`. After some debugging we found that Docker was eating the `$` and part of the username that followed it. The docs linked above use `@` a separator and we were able to get our SA logins working doing the same. The setting is in Harbor->Administrator->Configuration.

**Comment by fwt11** [comment]
I get this problem every day. I can not find any clue from the container logs. but if i run 
```
docker-compose down
docker-compose up -d
```
everything is ok again.

but 
```
docker-compose restart 
```
does not solve the problem

**Comment by Gainutdinov** [comment]
> I get this problem every day. I can not find any clue from the container logs. but if i run
> 
> ```
> docker-compose down
> docker-compose up -d
> ```
> 
> everything is ok again.
> 
> but
> 
> ```
> docker-compose restart 
> ```
> 
> does not solve the problem

Face the same issue, did you find any solution besides restarting?

**Comment by paulliss** [comment]
Hello. 
Unfortunately, got same trouble.

Harbor:  Version v2.10.2-1a741cb7

My dev Harbor previously worked fine more then a year and one day my pipeline crashed.

I wonder what it might be and found out the same error:
       could not login from cli with:  `echo ${HARBOR_PASSWORD} | docker login my.harbor.int --username ${HARBOR_USER} --password-stdin `
       error text: `Error response from daemon: login attempt to https://my.harbor.int/v2/ failed with status: 401 Unauthorized`

I also found out errors:

- in the component: **core** 
`[ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="..........."]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found`

- in the component: **registry**
```
"GET /v2/ HTTP/1.1" 401 87 "" "docker/24.0.7 go/go1.20.10 git-commit/311b9ff kernel/5.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.7 \\(linux\\))"

time="2025-10-09..........Z" 
level=error 
msg="error authenticating user "harbor_registry_user": authentication failure" go.version=go1.21.8 http.request.host=my.harbor.int 
http.request.id=70d7446f-ec34-48cb-9127-83b36490c326 
http.request.method=GET 
http.request.remoteaddr=10.x.x.73 
http.request.uri="/v2/" 
http.request.useragent="docker/24.0.7 go/go1.20.10 git-commit/311b9ff kernel/5.15.0-52-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.7 \(linux\))"
```

I could login into Harbor with my local  ${HARBOR_USER} through WebUI, 
also could login with another user through my OIDC system.


Could you please tell me the right way to search ?

Thank you in advance.


Up: Found out a solution: 
             https://github.com/goharbor/harbor/issues/14605

Thanks
