### ISSUE TITLE
How to disable authentication in Harbor

### ISSUE THREAD

**Issue by PushpalathaT** [goharbor/harbor#7471]
Hi ,
Is there any way to disable authentication i.e. connecting to harbor without docker credentials  authentication.
http://<registry_hostname>:<port>/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}

As i am trying to pull this image in CDSW and it fails .
And as per Cloudera Data Science Workbench they do not support pulling images from registries that require Docker credentials.

Thanks in Advance.

**Comment by reasonerjt** [comment]
you can push the image to a `public` project.

**Comment by PushpalathaT** [comment]
Image is under project having access level public . Can we configure harbor without docker crendentials?

Thanks

**Comment by reasonerjt** [comment]
If you want to bypass it, you can just create one user, assign him as admin and let everyone know his password.
