### ISSUE TITLE
Harbor database Corruption state

### ISSUE THREAD

**Issue by gmadu123** [goharbor/harbor#7486]
I tried to upgrade from 1.5.2 to 1.7.4 bosh harbor deployment. It failed and i try to restore back to old version. now i see it got back to fresh install without data. I see db_backup folder in side /data folder. Need to know how to recover data first so that we can be healthy on 1.5.2 and then need help to upgrade to latest version(1.7.4)

drwxr-xr-x 2 10000 10000 4096 Aug 23 2018 ca_download
-rw------- 1 10000 10000 16 Aug 23 2018 secretkey
-rw------- 1 10000 10000 8 Aug 23 2018 defaultalias
drwxr-xr-x 2 999 root 4096 Aug 23 2018 redis
drwxr-xr-x 2 10000 10000 4096 Aug 23 2018 config
drwxr-xr-x 2 10000 10000 4096 Aug 23 2018 psc
drwxr-xr-x 3 10000 10000 4096 Aug 23 2018 registry
drwxr-xr-x 2 root root 4096 Apr 19 01:57 cert
-rw-r--r-- 1 root root 6 Apr 22 17:23 harbor_version
drwxr-xr-x 2 10000 10000 77824 Apr 22 17:29 job_logs
drwx------ 19 999 admin 4096 Apr 22 17:40 clair-db
drwxr-xr-x 6 10000 10000 4096 Apr 22 17:40 notary-db
drwx------ 22 10000 10000 4096 Apr 22 17:40 database
drwxr-xr-x 2 root root 4096 Apr 22 17:59 db_backup

**Comment by reasonerjt** [comment]
@stonezdj could you take a look?

@gmadu123 let me clarify, are you using bosh release only, or use it via Harbor tile?

**Comment by gmadu123** [comment]
I am using bosh release only

**Comment by stonezdj** [comment]
1.Backup the following files and directory
```
/data/db_backup/registry.sql 
/data/registry/
/data/secretkey
```

2.Install harbor boshrelease 1.5 (fresh install) with same configuration, and copy these files to the previous locations.

```
/data/db_backup/registry.sql 
/data/registry/
/data/secretkey
```

3. Get registry db root password
```
cat /var/vcap/jobs/harbor/packages/harbor-app/common/config/adminserver |grep MYSQL_PWD
```
4. Copy backup sql file to db container and execute it.
```
docker cp /data/db_backup/registry.sql <db_containerid>:/
docker exec -it harbor-db bash
mysql -u root -p
<type password>
use registry
source registry.sql
```

5. Restart harbor
```
monit stop harbor
monit start harbor
```

6. Login into harbor and check data is correct.

**Comment by gmadu123** [comment]
Hi stonezdj , Thank you so much for these steps. it worked. I will close this and open new ticket for how to upgrade bosh release from 1.5.2 to 1.7.4

**Comment by gmadu123** [comment]
Here is new ticket info

https://github.com/goharbor/harbor/issues/7499
