### ISSUE TITLE
关于goharbor/redis-photon:v1.7.0 权限问题

### ISSUE THREAD

**Issue by ak47007** [goharbor/harbor#7488]
还是昨天无法登录问题，无法登录Portal，因为reids报错没有权限，赋值权限成功登录，因此不知道是我的redis image 版本不对，还是没有做权限控制。
Failed opening the RDB file dump.rdb (in server root dir /var/lib/redis) for saving: Permission denied
8:M 23 Apr 01:28:32.146 # Background saving error
8:M 23 Apr 01:28:38.054 * 1 changes in 900 seconds. Saving...
8:M 23 Apr 01:28:38.055 * Background saving started by pid 9426
直接赋予这个文件夹 777权限，可以成功登录，否则每隔一段时间就会不予许登录。
赋权后日志：
:M 23 Apr 01:31:26.197 # Background saving error
8:M 23 Apr 01:31:32.007 * 1 changes in 900 seconds. Saving...
8:M 23 Apr 01:31:32.008 * Background saving started by pid 9467
9467:C 23 Apr 01:31:32.022 * DB saved on disk
9467:C 23 Apr 01:31:32.022 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 01:31:32.108 * Background saving terminated with success

**Comment by stonezdj** [comment]
Could you upload all log files in /var/log/harbor ?

**Comment by ak47007** [comment]
我是部署在k8s 在哪里查看？

**Comment by ak47007** [comment]
如果在镜像 goharbor/redis-photon:v1.7.0 中给 /var/lib/redis 赋值了777权限，现在一切正常，之前我是靠重启恢复正常的。
9469:C 23 Apr 01:41:34.092 * DB saved on disk
9469:C 23 Apr 01:41:34.093 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 01:41:34.172 * Background saving terminated with success
8:M 23 Apr 01:46:35.081 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 01:46:35.082 * Background saving started by pid 9470
9470:C 23 Apr 01:46:35.094 * DB saved on disk
9470:C 23 Apr 01:46:35.094 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 01:46:35.182 * Background saving terminated with success
8:M 23 Apr 01:51:36.075 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 01:51:36.077 * Background saving started by pid 9471
9471:C 23 Apr 01:51:36.093 * DB saved on disk
9471:C 23 Apr 01:51:36.094 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 01:51:36.179 * Background saving terminated with success
8:M 23 Apr 01:56:37.065 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 01:56:37.067 * Background saving started by pid 9472
9472:C 23 Apr 01:56:37.071 * DB saved on disk
9472:C 23 Apr 01:56:37.072 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 01:56:37.168 * Background saving terminated with success
8:M 23 Apr 02:01:38.065 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 02:01:38.067 * Background saving started by pid 9473
9473:C 23 Apr 02:01:38.072 * DB saved on disk
9473:C 23 Apr 02:01:38.073 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 02:01:38.167 * Background saving terminated with success
8:M 23 Apr 02:06:39.047 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 02:06:39.049 * Background saving started by pid 9474
9474:C 23 Apr 02:06:39.054 * DB saved on disk
9474:C 23 Apr 02:06:39.054 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 02:06:39.150 * Background saving terminated with success
8:M 23 Apr 02:11:40.034 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 02:11:40.035 * Background saving started by pid 9475
9475:C 23 Apr 02:11:40.055 * DB saved on disk
9475:C 23 Apr 02:11:40.055 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 02:11:40.135 * Background saving terminated with success
8:M 23 Apr 02:16:41.096 * 10 changes in 300 seconds. Saving...
8:M 23 Apr 02:16:41.097 * Background saving started by pid 9476
9476:C 23 Apr 02:16:41.103 * DB saved on disk
9476:C 23 Apr 02:16:41.103 * RDB: 6 MB of memory used by copy-on-write
8:M 23 Apr 02:16:41.198 * Background saving terminated with success
