### ISSUE TITLE
OIDC callback returns error 

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#7492]
after configure the OIDC with PF8.4.2, it passed the initialize, but returns error after callback. 
1. first call:
GET https://login-itg.xxxxxxxxxxxxx/as/authorization.oauth2?client_id=harbor&redirect_uri=**https%3A%2F%2F172.20.226.191%2Fc%2Foidc%2Fcallback&response_type=code&scope=openid&state=yxxad4nshquyp6ztl7hue4rauufy0ixb** HTTP/1.1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3

HTTP/1.1 302 Found
Date: Tue, 23 Apr 2019 02:00:49 GMT
Content-Security-Policy: referrer origin
Cache-Control: no-cache, no-store
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: text/html;charset=utf-8
Location: https://login-itg.xxxxxxxxxxxxx:4443/as/xh7CU/resume/as/authorization.ping
Content-Length: 0

parameters :
GET
client_id: harbor
redirect_uri: https://172.20.226.191/c/oidc/callback
response_type: code
scope: openid
state: yxxad4nshquyp6ztl7hue4rauufy0ixb

2nd call:
GET https://172.20.226.191/c/oidc/callback?code=f_KHIsFB6NWEph3rOKc6gJ7cTFWNYKNX3Q5n7QAD&state=yxxad4nshquyp6ztl7hue4rauufy0ixb HTTP/1.1
Origin: https://login-itg.xxxxxxxxxxx:4443
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3

parameters 
GET
code: f_KHIsFB6NWEph3rOKc6gJ7cTFWNYKNX3Q5n7QAD
state: yxxad4nshquyp6ztl7hue4rauufy0ixb

page shows below:

This site can’t be reached The webpage at https://172.20.226.191/c/oidc/callback?code=f_KHIsFB6NWEph3rOKc6gJ7cTFWNYKNX3Q5n7QAD&state=yxxad4nshquyp6ztl7hue4rauufy0ixb might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

not sure if it is configure issue on harbor side or something else. 

for the initial call, harbor auto generate request with uri : harbor.local/c/oidc/callback
as/authorization.oauth2?client_id=harbor&redirect_uri=https%3A%2F%2F**harbor.local**%2Fc%2Foidc%2Fcallback&response_type=code&scope=openid&state=yxxad4nshquyp6ztl7hue4rauufy0ixb 

if this is from the DNS name parameter? just want to check if any API can help me to handle this value ... 

thanks

**Comment by reasonerjt** [comment]
turns out Harbor is hosted on 80 port via http only, closing.
