### ISSUE TITLE
upgrade harbor bosh release from 1.5.2 to 1.7.4

### ISSUE THREAD

**Issue by gmadu123** [goharbor/harbor#7499]
Can you please let me know steps for upgrading harbor bosh release from 1.5.2 to 1.7.4?

**Comment by stonezdj** [comment]
1.Backup the following files and directory
```
/data/db_backup/registry.sql 
/data/registry/
/data/secretkey
```

2.Install harbor boshrelease 1.5 (fresh install) with same configuration, and copy these files to the previous locations.

```
/data/db_backup/registry.sql 
/data/registry/
/data/secretkey
```

3. Get registry db root password
```
cat /var/vcap/jobs/harbor/packages/harbor-app/common/config/adminserver |grep MYSQL_PWD
```
4. Copy backup sql file to db container and execute it.
```
docker cp /data/db_backup/registry.sql <db_containerid>:/
docker exec -it harbor-db bash
mysql -u root -p
<type password>
use registry
source ./registry.sql
```

5. Restart harbor
```
monit stop harbor
monit start harbor
```

6. Login into harbor and check data is correct.
