### ISSUE TITLE
Create security disclosure process

### ISSUE THREAD

**Issue by caniszczyk** [goharbor/harbor#7501]
Look at Envoy as an example:

https://github.com/envoyproxy/envoy/blob/master/SECURITY_RELEASE_PROCESS.md

**Comment by alexvmw** [comment]
> Look at Envoy as an example:
> 
> https://github.com/envoyproxy/envoy/blob/master/SECURITY_RELEASE_PROCESS.md

Hi Chris, is there an official spec from CNCF around which this doc was created?

**Comment by caniszczyk** [comment]
@xaleeks no official spec, it's custom for each project

GitHub has a new security.md feature which you should take advantage of https://github.com/goharbor/harbor/security/policy

**Comment by michmike** [comment]
@xaleeks  want to close this since this is complete?
https://github.com/goharbor/harbor/blob/master/SECURITY.md

**Comment by michmike** [comment]
@caniszczyk  we finalized our Harbor security policy if you can please take a look as well.
https://github.com/goharbor/harbor/security/policy

**Comment by caniszczyk** [comment]
Awesome thank you
