### ISSUE TITLE
API to returns whether storage redirect enabled

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#7505]
Maybe provide these info in system configurations?

**Comment by reasonerjt** [comment]
@heww we can only show this info rather than allowing user to make update as it requries restarting other containers to make it effective.

Do you need it for replication?

**Comment by heww** [comment]
@reasonerjt yes, only need get the info no need to update it. 

I will use these info to decide whether support the harbor instance customer provided in our product.

**Comment by heww** [comment]
Closed for this requirement not needed now.
