### ISSUE TITLE
Replication Improvements Story

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#7509]
High level improvements
* P2P image distribution [future focus]
* replication on WAN networks (high latency low bandwidth) 
* scheduled replication [completed in 1.8]
* replication provider for cloud providers like AWS, GCP, Azure, Ali-ACR [focus for 1.9]

**Comment by steven-zou** [comment]
@michmike 

`scheduled replication` is already supported.

**Comment by michmike** [comment]
@steven-zou yes, i am aware :)  there are a few enhancements i might propose on that, but overall it is really good already

**Comment by rafaelcaviquioli** [comment]
Azure ACR replication is already supported for Docker images, but it looks like Helm Charts still is not supported.

**Comment by wy65701436** [comment]
As for Harbor v2.5, all the above are supproted, close it.
