### ISSUE TITLE
The database connection information shouldn't be logged 

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7510]
The database connection information(including the password) is logged when doing the migration for notary:
https://github.com/theupdateframework/notary/blob/master/migrations/migrate.sh#L20

**Comment by ywk253100** [comment]
https://github.com/goharbor/harbor-helm/issues/111#issuecomment-456590192

**Comment by reasonerjt** [comment]
That piece of code is from notary's repo
