### ISSUE TITLE
login not happened after navigate to callback URL

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#7515]
After configure OIDC, it seems goes to callback URL with data, but no login navigation... just display the return data on the webpage...
 
![image](https://user-images.githubusercontent.com/13995442/56717593-9926d300-676f-11e9-843a-b6b1dea5fadd.png)

any idea?

**Comment by reasonerjt** [comment]
@MaGaoju what build are you using, this was the result we displayed in a previous development build when e2e didn't work completely.

If you are using the latest build you should not see this.
If you are using the offline installer, could you let me know the tags of the images?
