### ISSUE TITLE
error 404: Curl on /api/registries

### ISSUE THREAD

**Issue by woozy1234** [goharbor/harbor#7518]
Hello,
I'm facing a issue/bug, i don't know... :)
When I want to use the API to manage registries, I have a 404 not found error.

`#curl -k -H "Content-Type: application/json" -X GET -u admin:xxxxxxxx https://xxxxxxxx/api/registries
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>`

The api works good for others entries like projects etc...

Do you have an idea about this problem ?

Thank you in advance.

**Comment by woozy1234** [comment]
More information, in core.log, i have this 

`Apr 25 14:35:43 172.18.0.1 core[18836]: 2019/04/25 12:35:43 #033[1;44m[D] [server.go:2619] |   172.26.177.1|#033[43m 404 #033[0m|   6.919506ms| nomatch|#033[44m GET     #033[0m /api/registries#033[0m
`
And the probleme is also present for /api/replications/policies

**Comment by ctodea** [comment]
Could you please add to the description the version you are using? `/api/systeminfo`

Anyway I've tried in v1.7.5-a8f6543a (I believe 1.7.5 is the latest release) and I'm still getting 404's to `/api/regiestries` and `/api/replication/policies` and even `/api/health`

**Comment by ctodea** [comment]
Check out the router for the APIs: https://github.com/goharbor/harbor/blob/release-1.7.0/src/core/router.go
the endpoints on the tag 1.7 the routes don't match the ones defined in swagger. 

e.g.: `/api/replication/policies` responds a 404 
but `/api/policies/replication` works fine

As the tag to previous versions, like 1.6 is broken cant tell exactly when this changed.

**Comment by reasonerjt** [comment]
@ywk253100 could you double check if the latest API doc is accurate?

**Comment by ywk253100** [comment]
Make sure you are using the same version API with your Harbor installation
