### ISSUE TITLE
Security Audit

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#7519]
Perform security audit of Harbor by 3rd party. CNCF will help us address this

This will include security testing, penetration testing, hardening. CNCF will hire a vendor to do this. michmike talked to caniszczyk about this and will queue up the process

Security Audit SOW signed by CNCF and C53. Audit to start on October 7th 2019.

**Comment by caniszczyk** [comment]
@michmike can you post the harbor security audit :)?

**Comment by m1ch41** [comment]
@michmike Can you tell me what is the status of security audit ?

**Comment by xaleeks** [comment]
> @michmike Can you tell me what is the status of security audit ?

this is done and report is publicly viewable. Check out details here: https://github.com/goharbor/harbor/pull/10112

**Comment by michmike** [comment]
ticket can now be closed
/close
