### ISSUE TITLE
install successful, but can not visit harbor

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#7526]
Reproduce step:
1 use harbor.yml to config setting. Just modify host name, and then run install.sh to install harbor. Leave http and https both in the config yml file. 
2 in the log console, it reported : "----Harbor has been installed and started successfully.----"
but still can not visit harbor . 
problem triage : 
1 run docker ps, it shows the nginx container always restart. 
This case does not config server cert.

**Comment by ninjadq** [comment]
dup #7389
