### ISSUE TITLE
No tooltip on Cron String 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#7533]
<img width="617" alt="Screen Shot 2019-04-26 at 2 52 23 PM" src="https://user-images.githubusercontent.com/2696760/56788831-16674c00-6833-11e9-9183-6a5a4bca66fc.png">

**Comment by steven-zou** [comment]
show the following table in the tooltip

Field name   | Mandatory? | Allowed values  | Allowed special characters
----------   | ---------- | --------------  | --------------------------
Seconds      | Yes        | 0-59            | * / , -
Minutes      | Yes        | 0-59            | * / , -
Hours        | Yes        | 0-23            | * / , -
Day of month | Yes        | 1-31            | * / , - ?
Month        | Yes        | 1-12 or JAN-DEC | * / , -
Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?

**Comment by steven-zou** [comment]
<pre><code>
Field name   | Mandatory? | Allowed values  | Allowed special characters
----------   | ---------- | --------------  | --------------------------
Seconds      | Yes        | 0-59            | * / , -
Minutes      | Yes        | 0-59            | * / , -
Hours        | Yes        | 0-23            | * / , -
Day of month | Yes        | 1-31            | * / , - ?
Month        | Yes        | 1-12 or JAN-DEC | * / , -
Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?
</code></pre>

**Comment by steven-zou** [comment]
Pattern description for cron '* * * * * *':

**Comment by stonezdj** [comment]
0 */10 * * * * is run every 10 minute,but failed to validate
