### ISSUE TITLE
OIDC mode should not show if install harbor in http mode. 

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#7536]
1 OIDC selection should be disabled in http mode. 
2 Should block user to install harbor in http mode if configuration is OIDC mode.

**Comment by reasonerjt** [comment]
Why not?

**Comment by reasonerjt** [comment]
As long as the `http://` endpoint is registered as `redirect-uri` on the OIDC provider, the E2E OIDC flow works.  
I'm closing this issue as this is a misunderstanding.
