### ISSUE TITLE
docker build workdir should be inner folder

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#7540]
currently all components's docker build workdir is the root harbor dir, this will cause slow build, and rebuild. We should switch to each inner folder before each docker build, and fix relative path in Dockerfile.

eg.
jobservice/Dockerfile
   current: COPY ./make/photon/jobservice/start.sh ./make/photon/jobservice/harbor_jobservice /harbor/
  change to: COPY start.sh harbor_jobservice /harbor/

and use pushd/popd command to switch begin work dir and origin dir

**Comment by reasonerjt** [comment]
@bitsf I think this can be deferred?
