### ISSUE TITLE
Failed to deploy harbor with prepare with custom data directory

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7543]
Please reference harbor.yml as below screenshot:

![image](https://user-images.githubusercontent.com/44018302/56789405-5a0e8580-6834-11e9-875c-08aa1f712bef.png)

![image](https://user-images.githubusercontent.com/44018302/56789504-9a6e0380-6834-11e9-9225-ea3dbf709bb0.png)

![image](https://user-images.githubusercontent.com/44018302/56789542-b5407800-6834-11e9-9831-3e3c59594e6d.png)

![image](https://user-images.githubusercontent.com/44018302/56790022-f4bb9400-6835-11e9-977b-d48236ece6bb.png)

**Comment by ninjadq** [comment]
custom data dir in my env is working fine.

It seems that your error is caused by the cert files not prepared correctly

**Comment by ninjadq** [comment]
dup #7389
