### ISSUE TITLE
install.sh should check existence of https cert and key

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7549]
In the install.sh should check the  existence of https cert and key

[steps]
1, config my https cert and key, but I forget to generate all of these files.
2, install with the shell script. 
3, Got the error following.

`
ERROR: for nginx  Cannot start service proxy: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/data/cert/server.key\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/a7a5656a4363a1292355a6775e01e54dd1ba98bed4613614d27ae5c7b34052ab/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/a7a5656a4363a1292355a6775e01e54dd1ba98bed4613614d27ae5c7b34052ab/merged/etc/nginx/cert/server.key\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'

ERROR: for proxy  Cannot start service proxy: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/data/cert/server.key\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/a7a5656a4363a1292355a6775e01e54dd1ba98bed4613614d27ae5c7b34052ab/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/a7a5656a4363a1292355a6775e01e54dd1ba98bed4613614d27ae5c7b34052ab/merged/etc/nginx/cert/server.key\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host pa`

[note]
After got the error, I tried to put these files into the configured path, and re-install. But the installation is struck by the error.

[workaround]
remove the folder ./common/config/nginx/cert/*, and re-install

**Comment by ninjadq** [comment]
dup #7389
