### ISSUE TITLE
The dialog of after robot account creation is closed after the copy icon was clicked.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7556]
I'd suggest we add an icon to close the dialog.
Just in case the user click the copy icon accidentally, it doesn't mean he wants to close the dialog.

**Comment by reasonerjt** [comment]
@wy65701436 please help t triage.

**Comment by wy65701436** [comment]
But if user click the close icon accidentally without get the token, there is no way to get it.

**Comment by reasonerjt** [comment]
Yep fair enough, we can keep it as is.
