### ISSUE TITLE
Use valid robot account user to curl API, get unexpected response.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7562]
If I created a robot account `tester` and issue a curl command:

```
curl 'robot$tester:xxxx' https://hostname/api/confiugrations
```
I expect to see a 401 but it returns 403
```
curl 'robot$tester:xxxx' https://hostname/api/users
```
I expect to see a 401 but it returns a nil pointer issue.
The nil pointer may be a dup to https://github.com/goharbor/harbor/issues/7478
but the code path should not be there, I think we should treat the robot account username/password as invalid when  the request is sent to api?

**Comment by wy65701436** [comment]
It's currently designing, not a bug. As the robot info can pass the basic auth, and the security context will treat it as pass, that's why API won't return 401.

**Comment by wy65701436** [comment]
It could be understood as `I'm requesting an out of scope resource with an validate robot account. `

**Comment by reasonerjt** [comment]
We may condier this is a `wont fix` ?

**Comment by reasonerjt** [comment]
Closing as we will redesign this API in v2.2.0
