### ISSUE TITLE
robot account can not configured as the credential of registry

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#7564]
Create a robot account in host test6 
username: robot$sample
password: xxxxxx

In test5 server, create a registry with robot account,  test connection passed, but when save this repository, it returned 500 error.

<img width="573" alt="Screen Shot 2019-04-26 at 6 16 41 PM" src="https://user-images.githubusercontent.com/2696760/56801524-33f6de80-6850-11e9-8ed0-8e6eee8904c3.png">

**Comment by reasonerjt** [comment]
Good catch!

**Comment by wy65701436** [comment]
Nice bug, I never thought about this scenario, but do we really need to use robot account to do replication?

**Comment by heww** [comment]
Robot account only has permissions to pull and push images, no permissions to call APIs.

Replications using robot account may not work for some APIs permissions missing.

**Comment by reasonerjt** [comment]
Can we fail the test connection?

**Comment by arvan-pritchard** [comment]
Event-based push replication from 1.7.5 to a 1.8.0-rc1 robot account appears to work. I've not tried 1.8 to 1.8 but would like to use this.
