### ISSUE TITLE
Caught failure when deploy harbor with  external_db and external_redis

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7565]
Deploy Harbor Test Steps:
    
    setup a pgsql  docker run -d postgres:alpine -e POSTGRES_PASSWORD=fred -p 5432:5432
    setup a redis docker run -d -p 6379:6379 redis
    edit http
    edit harbor.yml uncomment the external_db and external_redis
    ./install.sh --with-notary --with-clair --with-chartmuseum

    
![image](https://user-images.githubusercontent.com/44018302/56801679-9e0f8380-6850-11e9-8c08-16da33bbbabf.png)

**Comment by ninjadq** [comment]
dup #7531
