### ISSUE TITLE
Cannot specify the time to run the vulnerability scanning or gc when choosing "Hourly","Daily" or "Weekly"

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7570]
Cannot specify the time to run the vulnerability scanning or gc when choosing "Hourly","Daily" or "Weekly":
![cron](https://user-images.githubusercontent.com/5835782/56857476-abd41e80-69a0-11e9-8ab6-d2039b0e31ce.png)

Maybe we should keep only the cron string input text and provide some examples in the tooltip if we can not provide an easy way to specify the time.

**Comment by wy65701436** [comment]
close it as fixer per https://github.com/goharbor/harbor/pull/7530
