### ISSUE TITLE
'Source resource filter' can't be edit in the 'New replication rule'

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#7575]
using the build from testing day (4/26), the 'Source resource filter' can't be edit in the 'New replication rule', if click 'push based' 'pull based' button for several times. The browser I am using is Firefox.
![Screen Shot 2019-04-28 at 11 36 16 AM](https://user-images.githubusercontent.com/14900967/56858298-4e44cf80-69aa-11e9-9956-9a70947ed52e.png)

**Comment by ywk253100** [comment]
It's caused by the network issue, closing this one.
