### ISSUE TITLE
Test connection for harbor registry success when endpoint is non-harbor registry

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#7576]
New harbor registry for replication, the endpoint of harbor registry is https://www.baidu.com, then click the test connection button, the result is success, but www.baidu.com is not a harbor registry.

![WX20190428-132709](https://user-images.githubusercontent.com/5634205/56859144-607a3a00-69b9-11e9-97ed-8aafee395b46.png)

**Comment by ywk253100** [comment]
Test connection calls the `GET /v2` API and checks its response code. If the code is 2xx or 3xx, the operation is succeed.
