### ISSUE TITLE
Get 502 on my docker hub pull based rule

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7577]
My replication rule is as following, but every time I got 502 when to trigger it.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/2841473/56860158-cff62680-69c5-11e9-9000-ce6fc97d89aa.png">

**Comment by wy65701436** [comment]
Is it possible to list repo parallel?

**Comment by ywk253100** [comment]
Should have been fixed already.
