### ISSUE TITLE
Jenkins nodes storage shortage due to increasing of job log files

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7582]
Jenkins nodes has running of storage for one time, the reason is caused by increasing log files in /harbor/result_publisher, for now this folder has been cleared up, but for long term, it should at least reserve log files for a certain time, for example, the recent 7 days.

**Comment by reasonerjt** [comment]
We should create a cron job to clean the log files.

**Comment by danfengliu** [comment]
I've fixed it by using NFS server.
