### ISSUE TITLE
Change install.sh and prepare for tile

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#7587]
In tile install, we have to call the script in this way:
```
docker() {
     ${DOCKER_PACKAGE_DIR}/bin/docker -H $DOCKER_HOST $*
}
docker-compose() {
     ${PACKAGE_DIR}/docker-compose/bin/docker-compose -H $DOCKER_HOST  $*
}
source ${HARBOR_PACKAGE_DIR}/install.sh ${PREPARE_OPTS}
unset -f docker
unset -f docker-compose
```

After tile reconfigure, we have to call the prepare
```
source <path_to_prepare>/prepare PREPARE_OPTS
```
Issues:
1. Should not use current directory, or make it configurable parameter
https://github.com/goharbor/harbor/blob/master/make/install.sh#L153

2. Call it with source so that it pass env and function to the prepare
https://github.com/goharbor/harbor/blob/master/make/install.sh#L179

3.  Make the harbor_prepare_path configurable parameter
https://github.com/goharbor/harbor/blob/master/make/prepare#L6

4. Create an option to install harbor without start the harbor

And check if anything depends on current directory If I missed to list here.

**Comment by ninjadq** [comment]
fixed in #7624
