### ISSUE TITLE
Automatically copy a mirror to a remote warehouse, not the latest mirror in the past

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#7588]
What can we help you?
Hello, copy the image to the remote warehouse automatically, and the remote warehouse receives the image of the previous tag, not the latest. Mirrored storage uses cephfs. There was no problem before cephfs was used.

**Comment by koulq** [comment]
![image](https://user-images.githubusercontent.com/18571340/56951865-7891bb00-6b6b-11e9-8231-c714dc64d348.png)
This place according to the tag query of the Manifest may be obtained, is it appropriate to change to get according to digest?

**Comment by reasonerjt** [comment]
@koulq Could you elaborate the steps to reproduce the problem?

I don't understand based on your description.
