### ISSUE TITLE
cannot push images due to 500 Internal Server Error

### ISSUE THREAD

**Issue by caocharlie1989** [goharbor/harbor#7592]
cannot push images due to 500 Internal Server Error:
I have the same problem with @victorvli ,but i checked the config.yml and docker-compose.yml
registry.log:
Apr 29 12:11:33 172.18.0.1 registry[12289]: time="2019-04-29T04:11:33.967668749Z" level=error msg="unknown error completing upload: filesystem: stat /storage/docker/registry/v2/blobs/sha256/4a/4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40/data: permission denied" auth.user.name=k007te go.version=go1.7.3 http.request.host=harbor.xiaoxixi.com http.request.id=c1e4cf16-b774-42fe-ba8c-e2152f35f1f6 http.request.method=PUT http.request.remoteaddr=192.168.40.240 http.request.uri="/v2/k007te/te-bi-service/blobs/uploads/ad685069-6df9-4a64-a387-8d8306aaa6d8?_state=BbdVpwZKI22RjDmMd3GZQVX9_Inxj8nGBEauMFGU1457Ik5hbWUiOiJrMDA3dGUvdGUtYmktc2VydmljZSIsIlVVSUQiOiJhZDY4NTA2OS02ZGY5LTRhNjQtYTM4Ny04ZDgzMDZhYWE2ZDgiLCJPZmZzZXQiOjgyMjQsIlN0YXJ0ZWRBdCI6IjIwMTktMDQtMjlUMDQ6MTE6MzNaIn0%3D&digest=sha256%3A4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40" http.request.useragent="docker/1.13.1 go/go1.9.4 kernel/3.10.0-514.ky3.kb3.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" instance.id=4b5eefe3-8d22-4ba6-a4cc-d77d6bccb846 service=registry vars.name="k007te/te-bi-service" vars.uuid=ad685069-6df9-4a64-a387-8d8306aaa6d8 version=v2.6.2
Apr 29 12:11:33 172.18.0.1 registry[12289]: time="2019-04-29T04:11:33.967735164Z" level=error msg="error canceling upload after error: already closed" auth.user.name=k007te go.version=go1.7.3 http.request.host=harbor.xiaoxixi.com http.request.id=c1e4cf16-b774-42fe-ba8c-e2152f35f1f6 http.request.method=PUT http.request.remoteaddr=192.168.40.240 http.request.uri="/v2/k007te/te-bi-service/blobs/uploads/ad685069-6df9-4a64-a387-8d8306aaa6d8?_state=BbdVpwZKI22RjDmMd3GZQVX9_Inxj8nGBEauMFGU1457Ik5hbWUiOiJrMDA3dGUvdGUtYmktc2VydmljZSIsIlVVSUQiOiJhZDY4NTA2OS02ZGY5LTRhNjQtYTM4Ny04ZDgzMDZhYWE2ZDgiLCJPZmZzZXQiOjgyMjQsIlN0YXJ0ZWRBdCI6IjIwMTktMDQtMjlUMDQ6MTE6MzNaIn0%3D&digest=sha256%3A4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40" http.request.useragent="docker/1.13.1 go/go1.9.4 kernel/3.10.0-514.ky3.kb3.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" instance.id=4b5eefe3-8d22-4ba6-a4cc-d77d6bccb846 service=registry vars.name="k007te/te-bi-service" vars.uuid=ad685069-6df9-4a64-a387-8d8306aaa6d8 version=v2.6.2
Apr 29 12:11:33 172.18.0.1 registry[12289]: time="2019-04-29T04:11:33.968237449Z" level=error msg="response completed with error" auth.user.name=k007te err.code=unknown err.detail="filesystem: stat /storage/docker/registry/v2/blobs/sha256/4a/4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40/data: permission denied" err.message="unknown error" go.version=go1.7.3 http.request.host=harbor.xiaoxixi.com http.request.id=c1e4cf16-b774-42fe-ba8c-e2152f35f1f6 http.request.method=PUT http.request.remoteaddr=192.168.40.240 http.request.uri="/v2/k007te/te-bi-service/blobs/uploads/ad685069-6df9-4a64-a387-8d8306aaa6d8?_state=BbdVpwZKI22RjDmMd3GZQVX9_Inxj8nGBEauMFGU1457Ik5hbWUiOiJrMDA3dGUvdGUtYmktc2VydmljZSIsIlVVSUQiOiJhZDY4NTA2OS02ZGY5LTRhNjQtYTM4Ny04ZDgzMDZhYWE2ZDgiLCJPZmZzZXQiOjgyMjQsIlN0YXJ0ZWRBdCI6IjIwMTktMDQtMjlUMDQ6MTE6MzNaIn0%3D&digest=sha256%3A4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40" http.request.useragent="docker/1.13.1 go/go1.9.4 kernel/3.10.0-514.ky3.kb3.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.75678ms http.response.status=500 http.response.written=252 instance.id=4b5eefe3-8d22-4ba6-a4cc-d77d6bccb846 service=registry vars.name="k007te/te-bi-service" vars.uuid=ad685069-6df9-4a64-a387-8d8306aaa6d8 version=v2.6.2
Apr 29 12:11:33 172.18.0.1 registry[12289]: 172.18.0.1 - - [29/Apr/2019:04:11:33 +0000] "PUT /v2/k007te/te-bi-service/blobs/uploads/ad685069-6df9-4a64-a387-8d8306aaa6d8?_state=BbdVpwZKI22RjDmMd3GZQVX9_Inxj8nGBEauMFGU1457Ik5hbWUiOiJrMDA3dGUvdGUtYmktc2VydmljZSIsIlVVSUQiOiJhZDY4NTA2OS02ZGY5LTRhNjQtYTM4Ny04ZDgzMDZhYWE2ZDgiLCJPZmZzZXQiOjgyMjQsIlN0YXJ0ZWRBdCI6IjIwMTktMDQtMjlUMDQ6MTE6MzNaIn0%3D&digest=sha256%3A4a93653f6394ae37e26b4e976536aa8c78f6e9730366cf637c0907e0600a9b40 HTTP/1.1" 500 252 "" "docker/1.13.1 go/go1.9.4 kernel/3.10.0-514.ky3.kb3.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))"

I have the same problem with victorvli,but i checked the config.yml and docker-compose.yml
here is config.yml:
root [ /etc/registry ]# cat config.yml
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: inmemory
  filesystem:
    rootdirectory: /storage
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: http://harbor.xiaoxixi.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: http://ui:8080/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s

and here is docker-compose.yml:
 registry:
    image: vmware/registry-photon:v2.6.2-dev
    container_name: registry
    restart: always
    volumes:
      - /data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"

**Comment by reasonerjt** [comment]
Is it intermittent or reproducible?
What user did you use to install Harbor?
