### ISSUE TITLE
Pushing manifest list to Harbor should be blocked.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7597]
Currently there's a limitation in Harbor that the manifest list is not supported, many APIs will break, and potentially there may be inconsistency in data.

We'll support manifest list in future release, but for 1.8.0 we have to block pushing such artifact to Harbor.

**Comment by wy65701436** [comment]
close it as PR https://github.com/goharbor/harbor/pull/7666 merged.
