### ISSUE TITLE
Harbor启用chart修改参数后 无法使用web页面下载chart

### ISSUE THREAD

**Issue by syzhshch** [goharbor/harbor#7598]
在启用Harbor的Chartmuseum以后，index.yaml文件的url是相对路径。

查询Chartmuseum手册后，在/common/config/chartserver/env的CHART_URL添加了路径http://xxxxxxx.xx/chartrepo。

重启后index.yaml中了可以下载的路径，但是在Harbor的WEB端中进入helm chart无法根据版本号下载。点击下载后通过抓包发现下载的请求路径多了http://xxxxxxx.xx/chartrepo/library/
变成了了http://xxxxxxx.xx/chartrepo/library/http://xxxxxxx.xx/chartrepo/library/charts/xxx.tgz

Harbor版本为v1.7.5-a8f6543a

请问各位这个怎么能解决呢？

**Comment by zhihuicRepo** [comment]
i hava the same problem;
when i mod  '/common/config/chartserver/env' 'CHART_URL=http://harbor.today36524.td/chartrepo'
i can not download charts detail version (the url duplicate) like you;
harbor version v1.7.5-a8f6543a

**Comment by steven-zou** [comment]
@ninjadq 

Could you check if this issue has been fixed already and comment which version contains the fix patch.
