### ISSUE TITLE
Get images sizes using Harbor API

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#7603]
How can I get info about repository images sizes using Harbor API?
I can see the data in the UI but could not find any API returning this data.
Thanks.

**Comment by YakirShriker** [comment]
Found the data
/repositories/{repo_name}/tags

**Comment by jcdelarosa7** [comment]
Tried this and dont work anymore

**Comment by jcdelarosa7** [comment]
can you confirm if this is still working? need to get image size via API
