### ISSUE TITLE
Allow Robot users to upload Helm Charts

### ISSUE THREAD

**Issue by BeryJu** [goharbor/harbor#7604]
**Is your feature request related to a problem? Please describe.**
I've integrated Harbor into my CI workflow, and automatically push Images via the Robot user. I also create Helm charts in CI, but to upload those, I have to have a second user with another set of credentials, etc.

**Describe the solution you'd like**
An option to allow a Robot user to upload Helm Charts.

**Describe the main design/architecture of your solution**
A simple mockup: 
![image](https://user-images.githubusercontent.com/1932513/56902701-1e292980-6a9b-11e9-959b-673687938365.png)

**Comment by wy65701436** [comment]
@BeryJu are you using the master build now? For the design of Robot account, it's doable, but probably not in the coming release.

**Comment by BeryJu** [comment]
I am currently using 1.7.0, installed from the Helm Chart.

**Comment by wy65701436** [comment]
The Robot account will be in v1.8.0 with the scope of docker pull and push. Let's keep this issue open, and I will put it into 1.9.0 candidate.

**Comment by BeryJu** [comment]
Actually I might be on a newer version then since I already have the Robot user with docker push/pull available. I will check more closely in a second.

**Comment by wy65701436** [comment]
That's definitely a master build with tag `dev`, and the master branch may be in an unstable or even broken state during development.

**Comment by BeryJu** [comment]
Yep, just checked, I'm running on the `dev` tag.

**Comment by wy65701436** [comment]
I did some investigation on this, based on the current solvation of robot account model, it just needs to append the create and read in the access scope when to issue a new robot account. 

For example,
`    {
      "resource": "/project/library/helm-chart-version",
      "action": "create"
    },
    {
      "resource": "/project/library/helm-chart",
      "action": "read"
    }
`

After that, the robot account has permission to do `helm push` and `helm fetch`. So, this should be a UI work.

**Comment by jwangyangls** [comment]
fix it pr #7876

**Comment by code-pablo2** [comment]
I solve this problem with this URL
[goharbor/docs](https://goharbor.io/docs/1.10/working-with-projects/project-configuration/create-robot-accounts/)
`
TOKEN=eyJh~~~~~ && helm repo add --username='robot$account' --password="$TOKEN" myhelm https://myhelm.com/chartrepo/projectname
`
