### ISSUE TITLE
In replication, when pullling library/* from dockerhub, task list never refresh

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7608]
In replication, right after creating a rule which will pull library/* from docker-hub, click "Replication" button, there is a task list appeared and this list should be refreshed in period, but it's not refreshed.

**Comment by pureshine** [comment]
This problem is because the api/replication/executions api does not return a result, so the execution list will not be refreshed.

**Comment by pureshine** [comment]
If the api returns 201 state will refresh the list, otherwise it will not, this problem is not reproduced temporarily, please confirm the api return status
