### ISSUE TITLE
login harbor-ui failed,with 502 bad gateway

### ISSUE THREAD

**Issue by IrisHan** [goharbor/harbor#7609]
I first tried to install the harbor, I installed docker docker-compose, downloaded harborv1.7.5, and only modified the configuration harbor.cfg, hostname line,
---
_version = 1.7.0
#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
#DO NOT comment out this line, modify the value of "hostname" directly, or the installation will fail.
hostname = 10.89.127.28
----
I use ./prepare ./install.sh to start . I use docker-compose ps to see everything is healthy., but core is starting
but when i use password admin/Harbor12345 login http://10.89.127.28/harbor/sign-in ,response is 502

then i check  /var/log/harbor the Error log is
tail -f core.log
Apr 30 11:19:54 172.18.0.1 core[152835]: 2019-04-30T03:19:54Z [INFO] Config path: /etc/core/app.conf
Apr 30 11:19:54 172.18.0.1 core[152835]: 2019-04-30T03:19:54Z [INFO] initializing configurations...
Apr 30 11:19:54 172.18.0.1 core[152835]: 2019-04-30T03:19:54Z [INFO] key path: /etc/core/key
Apr 30 11:19:54 172.18.0.1 core[152835]: 2019-04-30T03:19:54Z [INFO] initializing client for adminserver http://adminserver:8080 ...
Apr 30 11:19:54 172.18.0.1 core[152835]: 2019-04-30T03:19:54Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 127.0.0.11:53: no such host

then i check adminserver.log
tail -f adminserver.log
Apr 30 11:15:39 172.18.0.1 adminserver[152835]: [ORM]2019/04/30 03:15:39 register db Ping `default`, pq: password authentication failed for user "postgres"
Apr 30 11:15:39 172.18.0.1 adminserver[152835]: 2019-04-30T03:15:39Z [FATAL] [main.go:45]: failed to initialize the system: register db Ping `default`, pq: password authentication failed for user "postgres"
Apr 30 11:17:21 172.18.0.1 adminserver[152835]: 2019-04-30T03:17:21Z [INFO] initializing system configurations...
Apr 30 11:17:21 172.18.0.1 adminserver[152835]: 2019-04-30T03:17:21Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Apr 30 11:17:21 172.18.0.1 adminserver[152835]: [ORM]2019/04/30 03:17:21 register db Ping `default`, pq: password authentication failed for user "postgres"
Apr 30 11:17:21 172.18.0.1 adminserver[152835]: 2019-04-30T03:17:21Z [FATAL] [main.go:45]: failed to initialize the system: register db Ping `default`, pq: password authentication failed for user "postgres"

then i check sql log
tail -f postgresql.log
Apr 30 11:15:39 172.18.0.1 postgresql[152835]: DETAIL:  Password does not match for user "postgres".
Apr 30 11:15:39 172.18.0.1 postgresql[152835]: #011Connection matched pg_hba.conf line 95: "host all all all md5"
Apr 30 11:17:21 172.18.0.1 postgresql[152835]: LOG:  incomplete startup packet
Apr 30 11:17:21 172.18.0.1 postgresql[152835]: FATAL:  password authentication failed for user "postgres"
Apr 30 11:17:21 172.18.0.1 postgresql[152835]: DETAIL:  Password does not match for user "postgres".
Apr 30 11:17:21 172.18.0.1 postgresql[152835]: #011Connection matched pg_hba.conf line 95: "host all all all md5"
Apr 30 11:20:46 172.18.0.1 postgresql[152835]: LOG:  incomplete startup packet
Apr 30 11:20:46 172.18.0.1 postgresql[152835]: FATAL:  password authentication failed for user "postgres"
Apr 30 11:20:46 172.18.0.1 postgresql[152835]: DETAIL:  Password does not match for user "postgres".
Apr 30 11:20:46 172.18.0.1 postgresql[152835]: #011Connection matched pg_hba.conf line 95: "host all all all md5"

I really don't know what to do with it.  how to configure or check postgresql in my host?

**Comment by IrisHan** [comment]
最后发现/data/cert/ 路径不存在 创建了个路径 就好了，什么呀。。。气疯。。。
at last,I found that /data/cert/  is not exist, I created it, then all worked. I don't know why the logs gived me the wrong guidlines.

**Comment by IrisHan** [comment]
其实我还做了件事情，进入harbor-db的容器 调用了以下命令
su - postgres
psql
alter role postgres with password 'root123';
然后我又创建了上面那个路径，再harbor-compose重启了 然后就好了，我后来又关闭删了 /data/cert/ 又好了，真不知道是什么动作影响了结果。

I really dont know whether ‘mkdir /data/cert/ ’ or 'enter container && alter role postgres with password 'root123'; ' finnaly make system work

**Comment by reasonerjt** [comment]
Closing as the problem is fixed per latest comment.

**Comment by frankcorneliusmartin** [comment]
Encoutered the same... a more usefull error would be a nice to have
