### ISSUE TITLE
Chartmuseum container can not start when configure registry storage to gcs

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#7614]
After configure GCP storage in harbor.yml
The registry container can work, but chartmuseum container is always restart.

When GCP is enabled, should add a configuration these files 
docker-compose.yml
```
chartmuseum:
   volumes:
   - <path_to_gcs_key_file>:/etc/chartserver/gcs.key
```
common/config/chartserver/env
```
GOOGLE_APPLICATION_CREDENTIALS=/etc/chartserver/gcs.key
```

Verified the S3 storage

Same issue is found that when s3 storage is enabled, but the chartmuseum still storage data in /data/chart_storage, It need to be fixed too.

**Comment by ninjadq** [comment]
fixed in #7639
