### ISSUE TITLE
Upgrade From Harbor:v1.6.1-98bcac6c To Harbor:v1.7.5 With AliYun OSS storage Failed

### ISSUE THREAD

**Issue by robinwangrubin** [goharbor/harbor#7627]
Hi,
I followed your instruction (below Link) to upgrade my harbor from v1.6.1 to v1.7.5; But I failed.

The link is 
`https://github.com/goharbor/harbor/blob/release-1.7.0/docs/migration_guide.md`

Error Log:
there's no any Error Log

What i do:
`docker ps`
checked all containers are healthy

What i see:
When i browse the web, I found i can't see any my container image.

By the way:
I use AliYun OSS storage

**Comment by wy65701436** [comment]
please provide harbor logs and the harbor.cfg.

**Comment by robinwangrubin** [comment]
I found out the reason. It's because my container can not resolve my OSS's hostname.
