### ISSUE TITLE
Update the default harbor.cfg settings for email and ldap

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#7629]
Currently, the harbor.cfg has the following settings as defaults:

```
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
email_insecure = false
```

Same with `ldap_url = ldaps://ldap.mydomain.com` etc.

Since `mydomain.com` is an actual valid domain, and they actually have an SMTP server at that address, can we change these defaults to something else?

Perhaps `smtp.goharbor.io` which is not being used for anything?

I understand that these settings are shows as examples, but I still think we should change these.

**Comment by ninjadq** [comment]
these configs are user level config and all removed from 1.8.0
