### ISSUE TITLE
Vulnerability resultbar shown only the green color

### ISSUE THREAD

**Issue by aladjadj** [goharbor/harbor#7630]
the vulnerability status bar not showing with good colors ( green and sylver only visible )

**Steps to reproduce the problem:**
Google Chrome
Firefox

**Versions:**
Harbor 1.7.5

![ImageBoard](https://user-images.githubusercontent.com/1840440/57080194-4bbbe000-6cf2-11e9-832c-16a2e3e23602.png)
![ListingBoard](https://user-images.githubusercontent.com/1840440/57080597-1bc10c80-6cf3-11e9-8740-743907c7b7ac.png)

**Comment by reasonerjt** [comment]
We may need certain combination of different level of vulnerabilities to reproduce this issue.
@aladjadj is this image pull-able from the internet?

**Comment by aladjadj** [comment]
My point is that the sum of width is not good 

![image](https://user-images.githubusercontent.com/1840440/57307748-68d32300-70e5-11e9-983c-79d86dbb5d6f.png)

I identify one strange property 

`.tip-block[_ngcontent-c20] {
     margin-left: -3px; 
}`

an other tip: 
the colors are calculated in [result-tip.component.ts](https://github.com/goharbor/harbor/blob/master/src/portal/lib/src/vulnerability-scanning/result-tip.component.ts):
normally the sum of color is MAX_TIP_WIDTH == 100 but sometimes the result is greater or less than 100px

Sorry is a private image :/

**Comment by jwangyangls** [comment]
Yes, we have found that this problem does exist. You'd better upgrade your harbor. This problem has been modified in the new version.

**Comment by zhoumeina** [comment]
@aladjadj , please use harbor 1.8. This is fixed.

**Comment by scopev24** [comment]
Hi,
I'm still seing this issue with v1.8.0-25bb24ca - using Chrome 75.0.3770.80 on Windows 10.

If I remove the "margin-left: -3px;" style the red portion of the bar becomes visible.

Apart from that: I suffer from a color blindness - that small red bar alongside the long green bar is barely recognizable for me...
Could you add some kind of text or an alert sign if any vulnerabilities are found?
E.g. the registry from quay uses some text like "passed" in green, or "4 high" in red.
