### ISSUE TITLE
removing the '*' from filed "First and last name" on the OIDC->user profile page. 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#7634]
removing the '*' from filed "First and last name" on the OIDC->user profile page. 
it seems this is an optional field. 
![Screen Shot 2019-05-05 at 2 01 23 PM](https://user-images.githubusercontent.com/14900967/57189240-87e38080-6f3e-11e9-8d27-750551f5fe71.png)

**Comment by jwangyangls** [comment]
fix it in  pull request #7654
