### ISSUE TITLE
/api/systeminfo cannot return 500 when DB is down.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7637]
[steps]
1, Down Harbor DB
2, Call /api/systeminfo
3, Get the error as below.

![image](https://user-images.githubusercontent.com/2841473/57190980-34c7f880-6f53-11e9-945e-19623a0d765e.png)

[root cause]
GetSystemCfg() eats the error.
https://github.com/goharbor/harbor/blob/master/src/core/config/config.go#L171

**Comment by stonezdj** [comment]
Fixed in #7650
