### ISSUE TITLE
Delete the actual files of the repository 

### ISSUE THREAD

**Issue by weiwendi** [goharbor/harbor#7658]
Deleting the data in the registry container, must the path to the config.yal file be in the /etc/registry/ directory?

When I delete the data of the harbor registry, I specify the config.yml file and prompt me "no such file or directory"
$ docker run -it --name gc --rm --volumes-from registry vmware/registry-photon:v2.6.2-v1.5.1 garbage-collect --dry-run  common/config/registry/config.yml 
configuration error: open common/config/registry/config.yml: no such file or directory
$ ls common/config/registry/config.yml 
common/config/registry/config.yml

I need to create the registry directory in /etc/, copy the config.yml file to /etc/registry/config.yml, and execute the above command:
$ docker run -it --name gc --rm --volumes-from registry vmware/registry-photon:v2.6.2-v1.5.1 garbage-collect --dry-run  /etc/registry/config.yml

**Comment by reasonerjt** [comment]
because the config.yml is read inside the container so you can't specify a path on the host.
