### ISSUE TITLE
Change the domain name,but the original domain name is still in the web console "Pull Command"

### ISSUE THREAD

**Issue by Yeefoner** [goharbor/harbor#7659]
Change the domain name,but the original domain name is still in the web console "Pull Command"
version:1.7.5

**Comment by jwangyangls** [comment]
@reasonerjt  the original domain come from API ：   api/systeminfo, I think the problem is that the return data of this interface is not refreshed.

**Comment by reasonerjt** [comment]
@Yeefoner please make sure you update the hostname in the configuration file rerun `prepare` and use `docker-compose` to restart Harbor.
The domain name will be populate to different components so rerun `prepare` is a must.

**Comment by reasonerjt** [comment]
Closing this issue, please refer to my latest comment to make the update take effect.

**Comment by MrAmbiG** [comment]
The issue still persists @reasonerjt as of today
