### ISSUE TITLE
Display name of labels in Chrome is incorrect.

### ISSUE THREAD

**Issue by rajboruah** [goharbor/harbor#7665]
**Expected behavior and actual behavior:**

Expected behavior:

Helm-Chart tab should be named: 'Helm Charts'
Labels should be named as : 'Labels' 
Fields should be as 'Name', 'Status', 'Versions', 'Created Time'

Actual behaviour:

Helm-Chart tab is displayed as: PROJECT_DETAIL.HELMCHART
Labels is named as : PROJECT_DETAIL.LABELS
Fields are being displayed as '
HELM_CHART.NAME', 'HELM_CHART.STATUS', 'HELM_CHART.CHARTVERSIONS
', 'HELM_CHART.CREATED'

**Steps to reproduce the problem:**
Installed 1.7.5
Use Chrome Browser to access harbor. (Browser version: Version 72.0.3626.121 (Official Build) (64-bit))
Goto helm-charts tab. 

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.5]
- docker engine version: [18.06.2-ce]
- docker-compose version: [docker-compose version 1.18.0, build 8dd22a9]

**Comment by DevilMayCrySamsara** [comment]
![image](https://user-images.githubusercontent.com/20835804/57904033-b00aa200-78a3-11e9-99cd-76c059c51693.png)
i have the same problem  
What's wrong with i18n?
