### ISSUE TITLE
The cfg migrator thinks I'm using external DB when I'm not

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7681]
Migration from v1.6.0 -> v1.8.0

I'm using local DB, but after migration the `external_database` and `external_redis` are enabled in `harbor.yml`

**Comment by reasonerjt** [comment]
Attaching the `harbor.cfg` 
[harbor.cfg.txt](https://github.com/goharbor/harbor/files/3151550/harbor.cfg.txt)

**Comment by ninjadq** [comment]
fixed in #7728
