### ISSUE TITLE
OIDC User login scenario should be revised

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7687]
It confuses user to login OIDC user in the home page.

The proposed way should be:
1, user input the username
2, harbor redirects to the login page
3, user input the password, and login success
4, jump back to harbor.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/2841473/57284432-bc447180-70e3-11e9-88ee-587380c5406c.png">

**Comment by reasonerjt** [comment]
For 1.8 Let's try to redirect when user click the "login" button.  

After delivering the fix I'll write another issue to track the ux refinement.

**Comment by reasonerjt** [comment]
@jwangyangls Please help to handle `302` by login controller in UI.

**Comment by reasonerjt** [comment]
We may defer it as there's some issue in angular v7 interceptor implementation, we may not be able to handle the redirection from UI as designed.

**Comment by reasonerjt** [comment]
We update the `login` uri to make it return `403` with redirect uri in the response.
Such that UI can handle it.
