### ISSUE TITLE
Uncheck pull for the robot account generation, pull permission is still assigned

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#7689]
Actually,
<img width="562" alt="Screen Shot 2019-05-07 at 16 28 44" src="https://user-images.githubusercontent.com/5753287/57285262-67a1f600-70e5-11e9-8579-5b6393ee2c60.png">
 it should not assign the unchecked permissions to the robot account

**Comment by wy65701436** [comment]
It's designed by docker distribution, it issues a token with access scope of "pull and push" for authorized push request.

What we can do, I think, is to modify UI string to let the user know this.

**Comment by reasonerjt** [comment]
Let's update the label on UI to "Permission for Pull/Push"
