### ISSUE TITLE
health check API return a html page instead of json result

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#7691]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
expecting health API always return json format.  
**Steps to reproduce the problem:**
1. stop the redis container
2. curl -X GET "https://10.155.21.231/api/health" -H "accept: application/json" -k 
**Versions:**
1.8.0 internal testing build.

**Comment by reasonerjt** [comment]
The root cause is that all API in core component relies on redis for checking the request.
We may need to change the architecture to fix this situation.

**Comment by reasonerjt** [comment]
This looks like a implementation issue in beego, can we think of a way to handle the outage more gracefully?

**Comment by xiaokugua250** [comment]
when i use 'curl -k -X GET "https://172.16.23.34/api/health" -H "accept: application/json" -H "authorization: Basic YWRtaW46QUkmYmlnZGF0YTIwMTk="' comman it return 404 page not found ,it seems /api/health not right in harbor 1.7.5
![image](https://user-images.githubusercontent.com/4617763/58082725-24b64700-7bea-11e9-9af0-52b3fa101885.png)
![image](https://user-images.githubusercontent.com/4617763/58082745-2e3faf00-7bea-11e9-884c-8bccbc7e987f.png)

**Comment by wy65701436** [comment]
This feature is not ready on v1.7.5, please try with v1.8.0

**Comment by xiaokugua250** [comment]
ok,thank you
