### ISSUE TITLE
export robot account to file

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#7698]
Current ROBOT account implementation will generate a long string and users need to copy the name and the secret to a file manually, It would be nice if harbor can support exporting it to file.

**Comment by zhoumeina** [comment]
@renmaosheng , do you mean the token string?

**Comment by lweitzman** [comment]
there is already a design to copy the token ... do we also want to write a file locally?
but this is still waiting for feedback from the development team
https://vmware.invisionapp.com/share/RKOJ1Q83XNS#/364608935_v1-8_-_Robot_Accounts_Creation_Successful_Copy

**Comment by jwangyangls** [comment]
We need to add a button to this page to download token to a local file.

![image](https://user-images.githubusercontent.com/29826789/61931988-d2602080-afb4-11e9-8e83-29d4022391a6.png)
