### ISSUE TITLE
The color of notification in UI has changed after upgraded to v1.8.0

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7706]
For example when Harbor was set to read-only mode, there should be a red banner with a warning sign telling user Harbor is in read-only mode.

After I upgrade to v1.8.0 from v1.7.0 the read-only mode persists but the banner is blue.

I also noticed some green/red notification for success and failure all turn blue after upgrading.

I guess it's due to some attributes of component in clarity were changed after upgrade, the code should change accordingly.

**Comment by jwangyangls** [comment]
fix it in  pr #7714
