### ISSUE TITLE
[Proposal] make image preheat functions towards Dragonfly GA

### ISSUE THREAD

**Issue by allencloud** [goharbor/harbor#7722]
**Is your feature request related to a problem? Please describe.**
This is not an existing problem of Harbor, but an enhancement for the integration of Harbor and [Dragonfly](https://github.com/dragonflyoss/Dragonfly), which are both hosted in CNCF.

Last year, Harbor and Dragonfly team had a proposal in Dragonfly community: [Proposal: Integrate trusted cloud-native registry Harbor with Dragonfly to provide a joint image management and distribution solution to support containerized environments](https://github.com/dragonflyoss/Dragonfly/issues/108).

This proposal made efficient image distribution possible for Harbor. This integration definitely shorten the time for user to pull images at scales.

Actually we had a successful cooperation with @steven-zou and we have a session at KubeCon Seattle 2018 - [Fly Your Containerized Environments by Joint Work of Harbor and Dragonfly](https://kccna18.sched.com/event/GrYh/fly-your-containerized-environments-by-joint-work-of-harbor-and-dragonfly-jia-zou-vmware-allen-sun-alibaba?iframe=no). Here is a video of the presentation: https://www.youtube.com/watch?v=kskWZsf_7oE

Now, lots of users of Dragonfly requested to use the image distribution within the combination of Harbor and Dragonfly.

I am wondering if we could make this move on to meet the community's demand.

And there is already a proposal of this in repo community: https://github.com/goharbor/community/pull/13.

**Describe the solution you'd like**
none

**Describe the main design/architecture of your solution**
![image](https://user-images.githubusercontent.com/9465626/57357647-fc6c2880-71a5-11e9-8c98-d17602f42f6e.png)

**Describe the development plan you've considered**
I think @steven-zou is an expert on this. Please help to input more.

**Additional context**
none. Please feel free to ask me if I missed something. Thanks.

**Comment by alexvmw** [comment]
we would like a discussion around this, can you ping me to setup a meeting based on your availability @allencloud

**Comment by allencloud** [comment]
I would attend harbor's community bi-week meeting. @alex

**Comment by xaleeks** [comment]
This has been delivered in our latest v2.1 GA release
