### ISSUE TITLE
Authentication not working with LDAP Microsoft AD

### ISSUE THREAD

**Issue by joshisagar92** [goharbor/harbor#7729]
Test LDAP server from configuration UI is giving **Connection to LDAP server is verified.**.But we are not able to login through AD credential. I am able to login through admin/Harbor12345.

Note : we are using ldap:// protocol with static IP to get connect.

We are getting below errors in /var/logs/Harbor/core.logs while trying to login through AD credentials.

May  8 18:40:34 172.29.0.1 core[4872]: 2019-05-08T13:10:34Z [WARNING] Not found an entry.
May  8 18:40:35 172.29.0.1 core[4872]: 2019-05-08T13:10:35Z [ERROR] [base.go:65]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Not found an entry'
May  8 18:40:42 172.29.0.1 core[4872]: 2019/05/08 13:10:42 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.139157ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
May  8 18:40:49 172.29.0.1 core[4872]: 2019-05-08T13:10:49Z [WARNING] Not found an entry.
May  8 18:40:50 172.29.0.1 core[4872]: 2019-05-08T13:10:50Z [ERROR] [base.go:65]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Not found an entry'

**Comment by stonezdj** [comment]
You need to check if there is any search filter configured?  if yes, please remove it to verify, and also check the LDAP UID is configured correct?

**Comment by joshisagar92** [comment]
I have checked that no search filter configured.
UID is configured correctly because it connect with ldap server successfully from UI.

**Comment by joshisagar92** [comment]
One more question,
Can you please let me know for ldap authentication administrator user / service account is required?

**Comment by joshisagar92** [comment]
Hi @stonezdj ,
We have searched ldap using command line and found that we do not have uid configured in ldap for any user and we are thinking this is the reason we are not able to login in to Harbor through ldap.

We have CN available, Is there any way to configure harbor which enable searching through CN instead of uid?

**Comment by joshisagar92** [comment]
It worked. 

We were giving wrong value for uid.
