### ISSUE TITLE
Provide a generic policy-based preheat feature to cover both Dragonfly and Kraken

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#7730]
Dragonfly and Kraken are both P2P image content distributors to accelerate the image distribution process. Integrate with those P2P distributors will definitely improve the distribution performance of the registry itself.

User can define a policy to decide which images are published to the content cache of P2P distributors for runtimes pullings under what conditions.

**Comment by steven-zou** [comment]
Related with #7722

**Comment by xaleeks** [comment]
This has been delivered in our latest v2.1 GA release
