### ISSUE TITLE
Access harbor display error  502

### ISSUE THREAD

**Issue by Candyient** [goharbor/harbor#7741]
Access harbor display error 502.I checked the status of the container.
![image](https://user-images.githubusercontent.com/32630577/57431965-06099500-7267-11e9-87bd-369cd73c7d37.png)
  harbor-adminserver   are always restarted.so I checked its log.
![image](https://user-images.githubusercontent.com/32630577/57432031-3c471480-7267-11e9-959e-c39e306ac402.png)
then  i checked the logs of  db.
![image](https://user-images.githubusercontent.com/32630577/57432069-5aad1000-7267-11e9-806a-b867fb677722.png)
But I don't know how to solve it. Please help me. Thank you.

**Comment by reasonerjt** [comment]
Hi, 
Looks like the DB schema is incorrect.

Is it a fresh install or upgrade?

What version of harbor are you using?

**Comment by Candyient** [comment]
I deployed it with harbor-offline-installer-v1.4.0.tgz .It worked normally before.

**Comment by Candyient** [comment]
> 嗨，
> 看起来数据库架构不正确。
> 
> 它是全新安装还是升级？
> 
> 你用的是什么版本的港湾？

Suddenly one day it was abnormal.
