### ISSUE TITLE
The label filter in replication policies will be lost after upgrade to version 1.8

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7762]
As the label filter isn't supported in the replication of version 1.8, after upgrade the label filter will be lost.

**Comment by sungjunyoung** [comment]
@ywk253100 We're using a label filter to make sure that the image is secured. Is this functionality not being developed anymore?

**Comment by ywk253100** [comment]
What's your scenario when using label filters? And which level label are you using? System or project level?
We get some difficulties when supporting label filter in replication of version 1.8. As  the replication rule doesn't belong to a single project anymore, it can cross multiple projects, the project level labels cannot be used in the replication rule as a filter easily.
 Your feedback is important for us to make decision about the supporting of label filter in the future.

**Comment by sungjunyoung** [comment]
@ywk253100 We're using system labels for replication rules to ISOLATE the secured checked registry by replicating only images that have the "Promoted" label. It's a key feature that we use, and we really want to be developed.

**Comment by sungjunyoung** [comment]
@ywk253100 Is there any news?

**Comment by ywk253100** [comment]
We are working on that and will take the system level label filter back in 1.9.

**Comment by sungjunyoung** [comment]
Sounds great :)

**Comment by mumrau** [comment]
I am managing multiple endpoints in multiple environments, and I only want a subset of my images to be replicated on certain environment, only the ones that are going, for a fact, to be deployed on that environment.
I was waiting for the non-harbor registries feature to apply this, which landed, and the label is ogne, I searched for it through the entire interface.

Just saying that this feature is crucial for many use cases and I appreciate this feature being put back in 1.9.0, I would even be down for earlier though.

**Comment by reasonerjt** [comment]
@ywk253100
I believe the label filter has been enabled in master branch.
 please dup it to an existing issue.

**Comment by megantexo** [comment]
We also need to replicate a subset of images based on image label. We'd like to label images intended for promotion, and replicate based on that label.
