### ISSUE TITLE
Discuss on updating 'appendonly' to yes in redis.conf

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7764]
Currently, we're using `appendonly no` as the value of redis.conf.

[Note]
This may cause migration issue, needs to figure out how to migration dump.db to appendonly.aof

[More info]
http://oldblog.antirez.com/post/redis-persistence-demystified.html

**Comment by reasonerjt** [comment]
As we move data from redis to DB, we probably do not need to worry about migrating the data of Redis.

**Comment by reasonerjt** [comment]
Let's keep as is until we see performance issue.
