### ISSUE TITLE
in v1.6.0 -> v1.8.0 migration the scan_all policy is not migrated correctly

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7772]
1.Install v1.6.0, set scan all policy to "daily: 9:00AM"
2.perform migration, install v1.8.0, 

verified other data objects are migrated correctly but the scan all is `NONE`

**Comment by wy65701436** [comment]
this because in 0002, the policy was removed. 

I tried the script 0004 individually, the part on migrating scan all policy worked fine.

**Comment by reasonerjt** [comment]
So it is expected behavior.
Let's make sure this is documented.
