### ISSUE TITLE
Support for alternative media types?

### ISSUE THREAD

**Issue by jdolitsky** [goharbor/harbor#7773]
Hello. I'm currently doing some work on the Helm CLI related to repos/registries. The next generation of Helm charts will be distributed via OCI-compliant registries.

Since it looks like Harbor is built atop Docker Distribution 2.7+, this should be possible to add support in Harbor (or you might already support it?)

The manifest media type for Docker specifically is the following:
```
application/vnd.docker.distribution.manifest.v2+json
```

The Helm media type is going to look something like the following (still TBD):
```
application/vnd.cncf.helm.chart.config.v3+json
```

This opens the door for additional future package types as well (not just Helm).

Maybe Harbor can implement a whitelist for well-known media types, then in the UI distinguish between the different types with logos etc? You can find a list of the alternative media types currently recognized by Azure Container Registry here: https://github.com/Azure/acr/blob/master/docs/artifact-media-types.json

Let me know if this is something Harbor is interested in supporting and we can discuss further :)

**Comment by reasonerjt** [comment]
@jdolitsky 
Yes we do.  
And use Harbor to serve other cloud native artifacts is in our future plan, I'll reach out to you via Email for more discussion.

**Comment by jdolitsky** [comment]
Closing this and continuing discussion at https://github.com/goharbor/community/issues/79
