### ISSUE TITLE
"robot account" tab missing in v1.7.5

### ISSUE THREAD

**Issue by tujian** [goharbor/harbor#7774]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
There used to be a "robot account" tab in project view.  Now it is missing in v1.7.5.

Below is a snapshot of v1.7.5.

![image](https://user-images.githubusercontent.com/4289812/57577204-836e1900-74a4-11e9-9bdf-3276bfa3b6d1.png)

**Steps to reproduce the problem:**
```
git clone https://github.com/goharbor/harbor-helm
cd harbor-helm
git checkout 1.0.1
helm install --name my-release .
```

**Versions:**
Please specify the versions of following systems.
- harbor-helm version: [1.0.1]
- harbor version: [1.7.5]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
The feature is in the v1.8.0.

**Comment by tujian** [comment]
It seems that I thought I installed harbor-helm v1.0.0, but in fact it was the master branch, whose harbor version was 'dev'.
