### ISSUE TITLE
when i install the app，it wrong，what happen？

### ISSUE THREAD

**Issue by ppamos** [goharbor/harbor#7775]
![1557720763](https://user-images.githubusercontent.com/48974977/57595577-80445d00-7578-11e9-88ec-13ba83e3db45.png)

**Comment by reasonerjt** [comment]
@ppamos what version of Harbor were you using?

**Comment by ppamos** [comment]
> @ppamos what version of Harbor were you using?

v 1.7.5

**Comment by reasonerjt** [comment]
If you can remove everything from `/data` and re-run `install.sh`, it should succeed.

**Comment by ppamos** [comment]
> If you can remove everything from `/data` and re-run `install.sh`, it should succeed.

it ok！ thanks
