### ISSUE TITLE
Repository description should support markdown format.

### ISSUE THREAD

**Issue by xiaosadexiaohai** [goharbor/harbor#778]
Upload images, yourself can go in editing instructions on the use of the mirror, I think that would be good

**Comment by ywk253100** [comment]
Adding description for repositories is in progress and will be available soon.

**Comment by It4lik** [comment]
It can be great if these descriptions (that are editable from the WebUI) could be written in something like markdown (like DockerHub do or Portus). In our case, this will hold the image README.md

**Comment by reasonerjt** [comment]
Use this issue to track future enhancement to support markdown.
