### ISSUE TITLE
v1.8.0 every 10 second log error authorizing context: authorization token required

### ISSUE THREAD

**Issue by gladmo** [goharbor/harbor#7780]
when i reset harbor,  i got some warning from `registry.log`.

is my `harbor.yml` error?

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.0
- docker engine version: 18.06.0
- docker-compose version: 1.23.2

```
May 13 15:52:28 192.168.16.1 registry[1142]: 192.168.16.8 - - [13/May/2019:07:52:28 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
May 13 15:52:28 192.168.16.1 registry[1142]: time="2019-05-13T07:52:28.430928035Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=685ec060-3f90-475e-ba92-58fd1150cc44 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.16.8:47966" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
May 13 15:52:28 192.168.16.1 registry[1142]: 192.168.16.8 - - [13/May/2019:07:52:28 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
May 13 15:52:38 192.168.16.1 registry[1142]: 192.168.16.8 - - [13/May/2019:07:52:38 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
May 13 15:52:38 192.168.16.1 registry[1142]: time="2019-05-13T07:52:38.427419977Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=b4551cf2-ecfa-43a6-966d-b0b6b938302b http.request.method=GET http.request.remoteaddr="192.168.16.8:47974" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="332.167µs" http.response.status=301 http.response.written=39
May 13 15:52:38 192.168.16.1 registry[1142]: 192.168.16.8 - - [13/May/2019:07:52:38 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
May 13 15:52:38 192.168.16.1 registry[1142]: time="2019-05-13T07:52:38.430329599Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=2e80f2cb-ad4c-4e4d-b2c0-00382aae1882 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.16.8:47974" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
```

here is my harbor.yml:
```
hostname: 192.168.0.203

http:
  port: 7777

harbor_admin_password: Harbor123

database:
  password: Harbor123

data_volume: /data/harbor

clair:
  updaters_interval: 12

  http_proxy:
  https_proxy:
  no_proxy: 127.0.0.1,localhost,core,registry

jobservice:
  max_job_workers: 10

log:
  level: info
  rotate_count: 50
  rotate_size: 200M
  location: /data/harbor/harbor-log

_version: 1.8.0
```

**Comment by reasonerjt** [comment]
This is expected, as whenever the client needs to access registry it will ping the `v2` uri and as registry is configured with token based authorization, it returns a 401 to redirect the client to the token service

**Comment by reasonerjt** [comment]
Without further a due I'm closing this issue, let me know if you want to re-open it.

**Comment by Geek3carl** [comment]
@reasonerjt My harbor can`t login with docker CLI,but is normal in web.The harbor version is 1.8.0，and return error like this:
Error response from daemon: Get https://registry.aiqbg.com/v2/: Get https://registry.xxxx.com:4433/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

In core.log output #033[1;44m[D] [server.go:2619] |   xxxx|#033[43m 401 #033[0m|   3.169005ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m

My English is very pool, and I really need to shoot this trouble. Could you help me?

**Comment by Henry78** [comment]
@reasonerjt 
> ... let me know if you want to re-open it.

This clutters the logs, so any way to get rid of this? (low prio)

**Comment by rstefanache** [comment]
The chain is:
- Healthcheck on the core service (/api/ping)
- The core service will check the registry on /v2 (https://github.com/goharbor/harbor/blob/v1.8.2/src/core/api/health.go#L218)
- Get a lot of errors in the log as @Henry78 said

Can we get rid of this ? :-)
