### ISSUE TITLE
OIDC onboarded user cannot update his profile

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#7787]
![image](https://user-images.githubusercontent.com/29826789/57669609-3756dc00-763e-11e9-8959-129aa16e13db.png)
![image](https://user-images.githubusercontent.com/29826789/57669686-9157a180-763e-11e9-8701-203b7f60409f.png)

![image](https://user-images.githubusercontent.com/29826789/57669660-7b49e100-763e-11e9-9a8c-76db92496723.png)
![image](https://user-images.githubusercontent.com/29826789/57669672-843ab280-763e-11e9-9dd1-59b1cb07736e.png)

**Comment by reasonerjt** [comment]
According to the design only Local DB user can update his profile.

I see there maybe requirement from user to update his profile but we cannot allow him to update the comment, as is the only flag that the user is onboarded via OIDC.

In 1.8.0, we'll keep it as is and make adjustment based on user's feedback.

**Comment by reasonerjt** [comment]
Per discussion we should disable the update via UI.

**Comment by jwangyangls** [comment]
We can't disable this button for the time being，because this would be inconsistent with other patterns of behavior.
