### ISSUE TITLE
There is a problem deploying the harbor1.8 version

### ISSUE THREAD

**Issue by herrywen-nanj** [goharbor/harbor#7788]
![image](https://user-images.githubusercontent.com/33476935/57672890-8efc4400-764c-11e9-9243-05a3218ab079.png)

How to solve? thank you very much

**Comment by ninjadq** [comment]
This error occurred during parse the harbor.yml. Please check you harbor.yml file is correct

**Comment by herrywen-nanj** [comment]
yeah,I think so.l check my harbor.yml file, found the following error,But what can be done with hostname and https, I can run it in other versions.
![image](https://user-images.githubusercontent.com/33476935/57674850-ec938f00-7652-11e9-8fd0-2a4ad00e5e2f.png)
![image](https://user-images.githubusercontent.com/33476935/57674880-01702280-7653-11e9-8240-4d95affd9ac6.png)

**Comment by ninjadq** [comment]
From line 13 to 18. There is one extra space in the head of the line.

**Comment by herrywen-nanj** [comment]
Thank you very much, it really is this problem.
