### ISSUE TITLE
Reset password when not using a mail server

### ISSUE THREAD

**Issue by bergtwvd** [goharbor/harbor#779]
I see no option (for the admin) to reset the password of a user  (when not using LDAP, and not using a mail server).  How can this be done?

Docker version 1.11.2, build b9f10c9
docker-compose version 1.7.1, build 0a9ab35

**Comment by bergtwvd** [comment]
This is related to https://github.com/vmware/harbor/issues/234

**Comment by reasonerjt** [comment]
Yep this seems a gap, will consider to fix it, what about sys admin can update password for any regular user?

**Comment by bergtwvd** [comment]
Yes, that sounds fine. I appreciate if this can be added.
Thanks!

**Comment by reasonerjt** [comment]
Due to security compliance, we need to defer this feature.

**Comment by reasonerjt** [comment]
This is fixed as we now support sys admin to update user's password
