### ISSUE TITLE
ldap server test always return ok

### ISSUE THREAD

**Issue by kawais** [goharbor/harbor#7793]
version: 1.8.0-rc1

whatever ldap url test always ok
![image](https://user-images.githubusercontent.com/8424926/57677978-bb1ec180-765a-11e9-983d-ddc72327bbf3.png)

ps, Add a username and password input box for better testing, like jenkins
![image](https://user-images.githubusercontent.com/8424926/57678219-544dd800-765b-11e9-84ec-fb9941c2ff07.png)

**Comment by stonezdj** [comment]
fixed with #7795, #7797

**Comment by wy65701436** [comment]
close it as PR merged.
