### ISSUE TITLE
document for defination of Replicating resources 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#7809]
![image](https://user-images.githubusercontent.com/44018302/57755595-defa0a00-7723-11e9-85c3-422e602f219c.png)

Is it better to say that "Replication allows users to replicate resources(images/charts) from Harbor itself to Harbors or non-Harbor registries"

**Comment by danfengliu** [comment]
In Replicating resources part, doc does not prompt user to add registry before add a replication rule.

**Comment by danfengliu** [comment]
“If there is no endpoint available in the list, you need to create one”

    It's better to have a link there to guide user how to create a registry.

**Comment by danfengliu** [comment]
![image](https://user-images.githubusercontent.com/44018302/57760300-da3a5380-772d-11e9-8722-f1f196ee0795.png)

Grammar for "once" is not right here?  It's better to use "summary of one of executions of the rule"

**Comment by stuclem** [comment]
> ![image](https://user-images.githubusercontent.com/44018302/57755595-defa0a00-7723-11e9-85c3-422e602f219c.png)
> 
> Is it better to say that "Replication allows users to replicate resources(images/charts) from Harbor itself to Harbors or non-Harbor registries"

Actually, the current text is grammatically accurate.

> 

> “If there is no endpoint available in the list, you need to create one”
> 
> ```
> It's better to have a link there to guide user how to create a registry.
> ```

Added link to the installation guide.

> ![image](https://user-images.githubusercontent.com/44018302/57760300-da3a5380-772d-11e9-8722-f1f196ee0795.png)
> 
> Grammar for "once" is not right here? It's better to use "summary of one of executions of the rule"

Correct. Fixed.

**Comment by stuclem** [comment]
PR #8821 updates the docs in `master`. PR #8822 updates the docs in `release-1.8.0`.

@reasonerjt do we need to update 1.7 too?
