### ISSUE TITLE
The password for robot account is too long.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#7812]
We're using the jwt token with RS256 alg for signature as the password of robot account.  And the length of that token sometimes is close to 1KB.

This may cause the header of a request too long, and potentially be problematic for certain router settings with limitation of the length of the request header.

Let's investigate if there's a way to make it shorter.

**Comment by wy65701436** [comment]
@arsulesandy there is no decision yet. @xaleeks any comments?

**Comment by xaleeks** [comment]
I don't believe you can change the behavior of rs256 or shorten the generated jwt via post-processing without removing some claims information.  It is definitely the safe choice but jwt are much larger than cookie based approach but even at 1kb and 10k requests, that's only 10mb of data.  I would put this as very low priority request.

**Comment by lclc** [comment]
This seems to be fixed now, with the new robot accounts.

**Comment by wy65701436** [comment]
@lclc yap, as robot is now moved to v2, close it as fixed.
