### ISSUE TITLE
ldap groupOfUniqueNames

### ISSUE THREAD

**Issue by zlingqu** [goharbor/harbor#7813]
harbor use ldap 
ldap中的group，objectclass:groupOfUniqueNames
发现组的权限，组内成员无法继承。

而使用
bojectclass:groupOfNames
都正常。

ldap_group_filter未配置。

**Comment by wy65701436** [comment]
@zlingqu what version are you using?

**Comment by zlingqu** [comment]
harbor 1.17.5
openldap:2.4.44
docker-ce:18.9.6

**Comment by stonezdj** [comment]
Can you please describe your issue in detail? 
How to reproduce? what is the error? and what is the expected result?

**Comment by zlingqu** [comment]
1、我的harbor已经使用了ldap进行认证，ldap里面的用户都可以正常登录
2、我在harbor上新建了一个项目，并尝试对不同的ldap用户设置不同的角色
3、使用ldap user进行角色配置，都是生效的，这是预期目标，没有问题
4、使用ldap group进行角色配置，当group中，bojectclass=groupOfNames时，我设置组为项目管理员，组内成员继承了组的权限，即是项目管理员，这是预期目标，没有问题
5、使用ldap group进行角色配置，当group中，bojectclass=groupOfUniqueNames时，虽然我设置的该组为项目管理员，使用组内成员登录时，发现没有任何权限

**Comment by zlingqu** [comment]
已经开启了 memberof overlay
配置如下：
  : olcOverlay={0}memberof
▽bjectClass: olcMemberOf
objectClass: olcOverlayConfig
objectClass: top
olcOverlay: {0}memberof
olcMemberOfDangling: ignore
olcMemberOfRefInt: TRUE
olcMemberOfGroupOC: groupOfUniqueNames
olcMemberOfMemberAD: uniqueMember
olcMemberOfMemberOfAD: memberOf
structuralObjectClass: olcMemberOf
entryUUID: f92d002a-0a61-1039-800e-49fe763c178b
creatorsName: cn=config
createTimestamp: 20190514070225Z
entryCSN: 20190514070225.608877Z#000000#000#000000
modifiersName: cn=config
modifyTimestamp: 20190514070225Z

**Comment by zlingqu** [comment]
比如一个用户tom同时位于group A、group B 、group C
1、只设置group A为访客，tom角色是访客，生效
2、只设置group B 为访客，tom无任何权限

**Comment by zlingqu** [comment]
I have found the reason, because the index of all groups under one ou is invalid, so I cannot verify that the user is in these groups.Thank you for your attention

**Comment by stonezdj** [comment]
Is it resolved?
