### ISSUE TITLE
harbor  1.8.0-rc1  oss  registry unhealthy aliyun api error

### ISSUE THREAD

**Issue by Ethan-2017** [goharbor/harbor#7820]
**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0-rc1]
- docker engine version: [18.09.3]
- docker-compose version: [1.23.2]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same 

storage_service:
  oss:
    accesskeyid: XXXXXXXXXXXX
    accesskeysecret: XXXXXXXXXXXX
    region: oss-cn-zhangjiakou
    endpoint: oss-cn-zhangjiakou-internal.aliyuncs.com
    bucket: xxxxxxxxxxxx
    internal: true
  ca_bundle: /etc/ssl/certs/
directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .
/api/healthy
{
  "status": "unhealthy",
  "components": [
    {
      "name": "database",
      "status": "healthy"
    },
    {
      "name": "redis",
      "status": "healthy"
    },
    {
      "name": "chartmuseum",
      "status": "healthy"
    },
    {
      "name": "clair",
      "status": "healthy"
    },
    {
      "name": "core",
      "status": "healthy"
    },
    {
      "name": "portal",
      "status": "healthy"
    },
    {
      "name": "registryctl",
      "status": "healthy"
    },
    {
      "name": "jobservice",
      "status": "healthy"
    },
    {
      "name": "registry",
      "status": "unhealthy",
      "error": "failed to check health: Get http://registry:5000/v2: dial tcp: lookup registry: no such host"
    }
  ]
}

/var/lib/harbor/
May 16 13:42:33 172.18.0.1 registry[550]:
May 16 13:42:33 172.18.0.1 registry[550]: goroutine 1 [running]:
May 16 13:42:33 172.18.0.1 registry[550]: github.com/docker/distribution/registry/handlers.NewApp(0xff4ac0, 0xc000430300, 0xc0003e8a80, 0x0)
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2fbb
May 16 13:42:33 172.18.0.1 registry[550]: github.com/docker/distribution/registry.NewRegistry(0xff4ac0, 0xc000430300, 0xc0003e8a80, 0xe, 0x0, 0x0)
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
May 16 13:42:33 172.18.0.1 registry[550]: github.com/docker/distribution/registry.glob..func1(0x171ee40, 0xc000404170, 0x1, 0x1)
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
May 16 13:42:33 172.18.0.1 registry[550]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171ee40, 0xc000404130, 0x1, 0x1, 0x171ee40, 0xc000404130)
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
May 16 13:42:33 172.18.0.1 registry[550]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171efe0, 0xc0001c1f88, 0xc00007a058)
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
May 16 13:42:33 172.18.0.1 registry[550]: main.main()
May 16 13:42:33 172.18.0.1 registry[550]: #011/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
May 16 13:43:34 172.18.0.1 registry[550]: time="2019-05-16T05:43:34.281332578Z" level=info msg="debug server listening localhost:5001"
May 16 13:43:34 172.18.0.1 registry[550]: 2019/05/16 05:43:34 GET https://oss-cn-zhangjiakou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix= ...
May 16 13:43:34 172.18.0.1 registry[550]: panic: Aliyun API Error: RequestId: 5CDCF88686XXXXXXX Status Code: 403 Code: SignatureDoesNotMatch Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.

this error cause harbor canot login and  push the images to  registry

**Comment by ninjadq** [comment]
hi @Ethan-2017 the error message seems that your accesskeyid or accesskeysecret is not correct

**Comment by Ethan-2017** [comment]
@ywk253100  I'M sure this accesskeyid or accesskeysecret is correct 。

**Comment by Ethan-2017** [comment]
when I  add the bucket name to the endpoint ,the registry is health ,but chart is not health

**Comment by Ethan-2017** [comment]
I want to both registry and chart  running at the same time in using aliyun oss。

**Comment by Ethan-2017** [comment]
https://github.com/goharbor/harbor/pull/7750

**Comment by ywk253100** [comment]
#7750 is merged and will be cherry picked into 1.8 branch. You can try the 1.8 RC2 build later.

**Comment by Ethan-2017** [comment]
@ywk253100  Today I install the  versions of 1.8 RC2 ,the same error happening? the chart is ok and it can push chart to the helmcharts ,but  cannot push the image  to the registry in the same time .

**Comment by ninjadq** [comment]
@Ethan-2017 what is the error message in the registry?

**Comment by Ethan-2017** [comment]
@ninjadq May 16 13:43:34 172.18.0.1 registry[550]: 2019/05/16 05:43:34 GET https://oss-cn-zhangjiakou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix= ...
May 16 13:43:34 172.18.0.1 registry[550]: panic: Aliyun API Error: RequestId: 5CDCF88686XXXXXXX Status Code: 403 Code: SignatureDoesNotMatch Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by Ethan-2017** [comment]
May 17 13:57:53 172.21.0.1 registry[11279]:
May 17 13:57:53 172.21.0.1 registry[11279]: goroutine 1 [running]:
May 17 13:57:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry/handlers.NewApp(0xff4ac0, 0xc000458180, 0xc00040b880, 0x0)
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2fbb
May 17 13:57:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry.NewRegistry(0xff4ac0, 0xc000458180, 0xc00040b880, 0xe, 0x0, 0x0)
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
May 17 13:57:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry.glob..func1(0x171ee40, 0xc00037b240, 0x1, 0x1)
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
May 17 13:57:53 172.21.0.1 registry[11279]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171ee40, 0xc00037b200, 0x1, 0x1, 0x171ee40, 0xc00037b200)
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
May 17 13:57:53 172.21.0.1 registry[11279]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171efe0, 0xc0001f3f88, 0xc00007a058)
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
May 17 13:57:53 172.21.0.1 registry[11279]: main.main()
May 17 13:57:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
May 17 13:58:53 172.21.0.1 registry[11279]: time="2019-05-17T05:58:53.600657603Z" level=info msg="debug server listening localhost:5001"
May 17 13:58:53 172.21.0.1 registry[11279]: 2019/05/17 05:58:53 GET https://oss-cn-zhangjiakou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix= ...
May 17 13:58:53 172.21.0.1 registry[11279]: panic: Aliyun API Error: RequestId: 5CDE4D9D273DD8537B1B2762 Status Code: 403 Code: SignatureDoesNotMatch Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.
May 17 13:58:53 172.21.0.1 registry[11279]:
May 17 13:58:53 172.21.0.1 registry[11279]: goroutine 1 [running]:
May 17 13:58:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry/handlers.NewApp(0xff4ac0, 0xc00043a870, 0xc000409500, 0x0)
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2fbb
May 17 13:58:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry.NewRegistry(0xff4ac0, 0xc00043a870, 0xc000409500, 0xe, 0x0, 0x0)
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
May 17 13:58:53 172.21.0.1 registry[11279]: github.com/docker/distribution/registry.glob..func1(0x171ee40, 0xc000390d80, 0x1, 0x1)
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
May 17 13:58:53 172.21.0.1 registry[11279]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171ee40, 0xc000390d40, 0x1, 0x1, 0x171ee40, 0xc000390d40)
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
May 17 13:58:53 172.21.0.1 registry[11279]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171efe0, 0xc0001f1f88, 0xc00007a058)
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
May 17 13:58:53 172.21.0.1 registry[11279]: main.main()
May 17 13:58:53 172.21.0.1 registry[11279]: #011/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
May 17 13:59:54 172.21.0.1 registry[11279]: time="2019-05-17T05:59:54.221384702Z" level=info msg="debug server listening localhost:5001"
May 17 13:59:54 172.21.0.1 registry[11279]: 2019/05/17 05:59:54 GET https://oss-cn-zhangjiakou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix= ...
May 17 13:59:54 172.21.0.1 registry[11279]: panic: Aliyun API Error: RequestId: 5CDE4DDAFD1ACEEC413089EE Status Code: 403 Code: SignatureDoesNotMatch Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by liqiang-fit2cloud** [comment]
> when I add the bucket name to the endpoint ,the registry is health ,but chart is not health

@Ethan-2017 You need to set the endpoint prefixed by your bucket name in harbor.cfg, then  https://github.com/goharbor/harbor/pull/7750 will make sure your chart is ok.

**Comment by Ethan-2017** [comment]
@liqiang-fit2cloud when I  set the endpoint prefixed by my bucket name in harbor.yml  ,both chart and  registry  is ok 。 thank you everybody !
