### ISSUE TITLE
provide an offline clair db data in psql format

### ISSUE THREAD

**Issue by rootdeep** [goharbor/harbor#7828]
After I installed  harbor with clair,  clair can not update the CVE info from Internet for network restriction. I tried to use several  psql data of clair db from Internet, some different errors occurred, it might be the table schema are different between  harbor-db and other clair dbs.
  
In my opinion, it will be more friendly for the users if  harbor is published with psql data which is matched with the harbor-db's version . 

An example as reference:  https://github.com/Dimple-Wmj/clair-vulnerabilities-db
Note: the above data is not available for harbor-db due to different table schema.

**Comment by reasonerjt** [comment]
I don't think we can provide it due to legal reason.
