### ISSUE TITLE
need 2 endpoints to create replication in 1.8.0-rc1 using Safari, Edge or Internet Explorer

### ISSUE THREAD

**Issue by arvan-pritchard** [goharbor/harbor#7829]
**Expected behavior and actual behavior:**
I expect the Save button to be enabled once all the required fields are filled in on the Mew Replication Rule Dialog, but it is not until I have explicitly selected a destination registry, and I can only make that selection if I have more than one available/

**Steps to reproduce the problem:**
Fresh install of 1.8.0-rc1 on Ubuntu 18.04
Access the UI via Safari 12.1
Create a single endpoint
Try to create a replication rule - I have found no way to enable the save button on the New Replication Rule dialog
Note that the Destination registry field is pre-populated with the only endpoint.

Now create a second endpoint
Try again - this time the save button can be enabled by providing a Name and selecting the 2nd endpoint from the drop-down at "Destination registry".
It remains enabled after re-selecting the first entry on that list.

Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.0-rc1
- docker engine version: 18.09.6
- docker-compose version: 1.24.

**Additional context:**
[harbor.config.tar.gz](https://github.com/goharbor/harbor/files/3187355/harbor.config.tar.gz)
[harbor.logs.tar.gz](https://github.com/goharbor/harbor/files/3187356/harbor.logs.tar.gz)

**Comment by wy65701436** [comment]
@arvan-pritchard can you help to check the scenario on chrome?

**Comment by wy65701436** [comment]
@arvan-pritchard can you help to check the scenario on chrome?

**Comment by arvan-pritchard** [comment]
On Chrome (74.0.3729.121) the Destination registry field is not refilled, so I can populate it from the dropdown whether I have one or two endpoints defined, this is also the case for Firefox (66.0.5)

Internet Explorer (11.706.17134.0) and Microsoft Edge (42.17134.1.0) both suffer from the same problem as Safari

I don't have any other browsers to hand to test.

**Comment by wy65701436** [comment]
Thanks for the details, it should be a browser specific issue. We recommend user to use chrome or Firefox to access Harbor.
