### ISSUE TITLE
Exclude postgres password from configmaps

### ISSUE THREAD

**Issue by fentas** [goharbor/harbor#7830]
**env:**
- kubernetes 1.14
- rendered helm chart; applied with kustomize

---

I want to use harbor with an external database. The necessary credentials are stored within a Secret.

The problem is that these credentials are generated at runtime.
So what I tried was to apply them as a kustomize variable which fails because base64 encrypted (https://github.com/kubernetes-sigs/kustomize/issues/499).

Applying them as secretRef will also fail because the credentials are written all over the place
- configmap harbor-clair - mounted as yaml file
- configmap harbor-notary-server - mounted as json file
- deployment notary-server
- deployment notary-signer

This is a bit frustrating especially that ConfigMaps are not for storing credentials (also pointed out by kustomize sig). 
For now, to be able to integrate it within our pipeline I am forced to move the Postgres credentials also to a configmap.

**Comment by reasonerjt** [comment]
Thanks for pointing it out, the root cause seems to me is that the software are referencing the data you want to store in a secret in a configmap as plaintext.

The only way to fix this seems to store the whole config file as secret, it solves the problem but doesn't seem a very good fix.

Do you have any proposal to fix it more properly?

**Comment by fentas** [comment]
Hm, the best solution would be to have it similar to mongodb, postgers, ... helm charts which gives the option to set an `existingSecret`.

I guess the hard part IMHO is to get it consistent because harbor has it somewhat scattered plus in different forms (as plain password; as secret, then as Postgres URL and finally as Postgres URL is written within a configmap mounted as file - excluding the possibility to set the password as env right away).

I would suggest using the `core/secret` as the starting point. From there, secrets are mounted either as a file or as ENV per `secretRef`.
As for harbor-clair cm and cm harbor-notary-server needs to extend their entry point to check for Postgres credential and mend their needed config.

But whatever way we would use the main goals should be
- no credentials saved within a ConfigMap
- potentially a single secret file*

*) _example helm config:_ \
```
clair.database.existingSecret = "postgres-credentials"
notary.database.existingSecret = "postgres-credentials"
core.database.existingSecret = "ha-postgres-credentials"
```
_or just_
```
database.external.existingSecret = "postgres-credentials"
```
The latter would be good enough I guess.

**Comment by reasonerjt** [comment]
I agree that whatever config file containing password in plaintext should be treated as `secret`

Let's track it via 
https://github.com/goharbor/harbor-helm/issues/111
