### ISSUE TITLE
Can't find migrator for upgrade to/between rc builds

### ISSUE THREAD

**Issue by arvan-pritchard** [goharbor/harbor#7831]
I am trying out the 1.8.0 rc builds, but can't find the migrator which https://github.com/goharbor/harbor/blob/release-1.8.0/docs/migration_guide.md implies I need for migrating to or between them.

the v1.7.5 migrator is in the expected place:

```
$ sudo docker pull goharbor/harbor-migrator:v1.7.5
v1.7.5: Pulling from goharbor/harbor-migrator
f366967fbec6: Pull complete 
b2d2923e54e6: Pull complete 
cc5222fa353a: Pull complete 
1f63450d1f1f: Pull complete 
Digest: sha256:4c229bcc14553b180b2ed8161d95a77d9cb012964a861e8d9c8635ba23aa0cf4
Status: Downloaded newer image for goharbor/harbor-migrator:v1.7.5
$ sudo docker pull goharbor/harbor-migrator:v1.8  
Error response from daemon: manifest for goharbor/harbor-migrator:v1.8 not found
$ sudo docker pull goharbor/harbor-migrator:v1.8.0
Error response from daemon: manifest for goharbor/harbor-migrator:v1.8.0 not found
$ sudo docker pull goharbor/harbor-migrator:v1.8.0-rc1
Error response from daemon: manifest for goharbor/harbor-migrator:v1.8.0-rc1 not found
$ sudo docker pull goharbor/harbor-migrator:v1.8.0-rc2
Error response from daemon: manifest for goharbor/harbor-migrator:v1.8.0-rc2 not found
$ sudo docker pull goharbor/harbor-migrator           
Using default tag: latest
Error response from daemon: manifest for goharbor/harbor-migrator:latest not found
```

**Comment by wy65701436** [comment]
you can get it from the offline installer

**Comment by wy65701436** [comment]
We will push all of the images to docker-hub once get them released.

**Comment by arvan-pritchard** [comment]
Presumably it is always in the offline installer, so adding that to the instructions would be useful for anyone needing to use the offline installer with production builds.

**Comment by arvan-pritchard** [comment]
It is possible to load the harbor-migrator image with
```
$ docker load -i harbor.*.tar.gz
```
in the folder where you have unpacked the offline installer.

There may be a way to load just that image rather than all the images - but the others will all be loaded when you run install.sh so there is probably no point.

**Comment by wy65701436** [comment]
Per design, migrator image is only in the offline with RC builds and will be pushed in the docker-hub once get released.

@arvan-pritchard thanks for point this, would you mind to raise a PR to update the doc for this? 
And Let me close the issue as no blocker here.
