### ISSUE TITLE
Cannot install harbor using install.sh

### ISSUE THREAD

**Issue by miracle152004** [goharbor/harbor#7832]
Hi,
I am trying to install harbor v1.7.5 using the guide at https://github.com/goharbor/harbor/blob/release-1.7.0/docs/installation_guide.md (offline and online installer both) and getting the following exception:

[Step 3]: checking existing instance of Harbor ...
ERROR: .IOError: [Errno 2] No such file or directory: './docker-compose.yml'

The installation environment is the following:
[Step 0]: checking installation environment ...
Note: docker version: 18.09.2
Note: docker-compose version: 1.22.0

Do I do something wrong?
Thanks for the help.

Best regards
Christopher Black

**Comment by miracle152004** [comment]
Ok.
It worked after installing the latest version of docker-compose.
So maybe the version should be changed in the installation guide.

**Comment by reasonerjt** [comment]
I don't think it has anything to do with the docker-compose version.

It is just because you are running `install.sh` from other directory.
@ninjadq please see if there any possible improvement.
