### ISSUE TITLE
robot account creation doesn't return robot account ID

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#7840]
**Expected behavior and actual behavior:**
Create a robot account for a project via REST API, and then try to get robot account info. Since other robot account APIs requires robot account ID, I would expect the robot account creation returns the robot account ID.

expected behavior: robot account ID is in the creation response
actual behavior: only the robot account name and token are in the creation response

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
Call project robot account create API to create a robot account.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8]

**Comment by reasonerjt** [comment]
@ericvmw 
You can get the ID of the robot account from the `Location` header in the response.
We can add the ID to response body, but it will introduce in consistency to other APIs, so I think we should stay as-is.

**Comment by reasonerjt** [comment]
We've made decision not to fix it.
