### ISSUE TITLE
http_auth always onboard configuration doesn't work as expected

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#7841]
The configuration "always onboard" for authentication mode http_auth should allow users to be added automatically when adding users as project members, even though the user has not logined yet.

**Expected behavior and actual behavior:**
expected behavior: a user can be added as a project member even if the user has not logined in for the first time and if the "always onboard" configuration is true.
actual behavior: a user cannot be added as a project member if he has not logined in for the first time, though the "always onboard" configuration is true, the following logs is shown in harbor-core:

2019-05-20T16:54:39Z [WARNING] [/core/api/projectmember.go:80]: Failed to get pmid from path, error strconv.ParseInt: parsing "": invalid syntax
2019/05/20 16:54:39 [D] [server.go:2619] |     10.246.3.0| 200 |   6.484725ms|   match| GET      /api/users/search   r:/api/users/search
2019-05-20T16:54:39Z [DEBUG] [/common/dao/project/projectmember.go:147]: Query sql: select pm.id, pm.project_id, 
	               u.username as entity_name, 
	               r.name as rolename,
			       pm.role, pm.entity_id, pm.entity_type 
			  from project_member pm
         left join harbor_user u on pm.entity_id = u.user_id and pm.entity_type = 'u'
		 left join role r on pm.role = r.role_id
			 where u.deleted = false and pm.project_id = ? and u.username like ? 
			union
		   select pm.id, pm.project_id, 
			       ug.group_name as entity_name, 
				   r.name as rolename,
				   pm.role, pm.entity_id, pm.entity_type 
		      from project_member pm
	     left join user_group ug on pm.entity_id = ug.id and pm.entity_type = 'g'
	     left join role r on pm.role = r.role_id
			 where pm.project_id = ? and ug.group_name like ? 
			 order by entity_name  
2019/05/20 16:54:39 [D] [server.go:2619] |     10.246.3.0| 200 |  15.775958ms|   match| GET      /api/projects/2/members   r:/api/projects/:pid([0-9]+)/members/?:pmid([0-9]+)
2019-05-20T16:54:41Z [DEBUG] [/core/filter/security.go:233]: OIDC CLI modifer only handles request by docker CLI or helm CLI
2019-05-20T16:54:41Z [DEBUG] [/core/filter/security.go:308]: Auth proxy modifier only handles docker login request.
2019-05-20T16:54:41Z [DEBUG] [/core/filter/security.go:491]: can not get user information from session
2019-05-20T16:54:41Z [DEBUG] [/core/filter/security.go:560]: user information is nil

**Steps to reproduce the problem:**
1. login to Harbor as a system admin or project admin on Harbor UI
2. try to add a project member as master for a user who has not logined yet.
3. the member add will fail

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8] - the latest harbor helm chart (dev images in master branch)

**Comment by ericvmw** [comment]
The "always onboard" configuration used to work, this should be a regression.

**Comment by wy65701436** [comment]
close it as fixed.
