### ISSUE TITLE
replication job failed,but do not re-scheduled

### ISSUE THREAD

**Issue by dantianji** [goharbor/harbor#7842]
when the replication job failed,it doesn't  be re-scheduled a few minutes later.
2019-05-08T15:01:22Z [INFO] initialization completed: repository: 20000000240/dq-yhqmanage, tags: [20190508225913177407807], source registry: URL-https://172.78.225.35 insecure-true, destination registry: URL-https://172.78.225.30 insecure-true
2019-05-08T15:01:22Z [ERROR] [job_logger.go:81]: an error occurred while creating project 20000000240 on destination registry: Post https://172.78.225.30/api/projects/: dial tcp 10.70.62.230:443: getsockopt: connection refused

**Comment by heww** [comment]
@dantianji Can you confirm that the cron string is correct?

I tested that replication job will scheduled even one job failed.

![WX20190522-173155](https://user-images.githubusercontent.com/5634205/58164244-07e84500-7cb8-11e9-8439-651dac01bb5f.png)


Can you provide more detail info?

**Comment by 541013515** [comment]
I met same errors， like this：
![11](https://user-images.githubusercontent.com/10428409/59603243-827f7580-913b-11e9-8a67-20ae398ce09d.PNG)
![44](https://user-images.githubusercontent.com/10428409/59603245-83180c00-913b-11e9-90cf-a173fe8a52e9.PNG)
![33](https://user-images.githubusercontent.com/10428409/59603264-94f9af00-913b-11e9-9c29-e8c64283254f.PNG)
![22](https://user-images.githubusercontent.com/10428409/59603304-aa6ed900-913b-11e9-934f-80ec9a306c1e.PNG)

did two jobs trigger image replication to same destination at same time causing this problem？

**Comment by steven-zou** [comment]
@dantianji 

Is it a periodic job with a pre-defined schedule or is just a once-running job?  Failed jobs will be retried if it does not reach the top ceil. Moreover, which Harbor version are you using? If it is 1.8.x, job retrying may have a bug which is referred in the issue https://github.com/goharbor/harbor/issues/8745.
