### ISSUE TITLE
1.7.0版本部署，docker login error ：502

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#7843]
core访问registry的5000端口被拒绝怎么回事？（Core access to the 5000 port of the registry is denied. ）

**Comment by heww** [comment]
Which method used to install harbor, installer or helm chart ?

**Comment by ZZYhho** [comment]
core 容器里面的env 应该没有no_proxy=registry,modify ~/.docker/config.json
"noProxy": "127.0.0.1,localhost,harbor-core,harbor-db,harbor-jobservice,harbor-log,harbor-portal,nginx,redis,registry,registryctl" it set noproxy=registry in harbor-core env

**Comment by koulq** [comment]
@ZZYhho This problem has been solved. There is something wrong with upgrading docker.
