### ISSUE TITLE
The reboot time is too long, because chown changes the directory permissions.  

### ISSUE THREAD

**Issue by mingzhuyang** [goharbor/harbor#7846]
**Is your feature request related to a problem? Please describe.**
My mirror repository currently stores an 80T docker image, which takes 1-2 hours to restart the harbor each time. The investigation found that it was caused by the [chown 10000:10000 command](https://github.com/goharbor/harbor/blob/ae007c2a49ec39aa05e6a21fb8676e7959c7ee71/make/photon/registry/entrypoint.sh)
**Describe the solution you'd like**
Is it possible to provide a configurable parameter, execute chown 10000:10000 at install time, and skip the chown command when restart.
**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
A clear and concise description of the plan to make the solution ready. It can include a development timeline, resource estimation, and other related things.

**Additional context**

**Comment by reasonerjt** [comment]
@ninjadq we discussed this.
I think ideally, we should move this to `prepare` phase.

And for the perf issue I can think of 2 options:
1) check the ownship before running `chown`
2) add a flag in the env vars to control it, and by default do not run `chown`

**Comment by ninjadq** [comment]
I think this issue is already fixed in a newer version. And chow logic will move to prepare when refactoring non-root container of the registry.
