### ISSUE TITLE
docker login error due to key format on centos7/rhel7 when deployed via docker-compose

### ISSUE THREAD

**Issue by Chris-Lauer** [goharbor/harbor#7849]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: docker login to the harbor registry succeeds after an install of harbor on a rhel7 machine using the docker-compose install method and a valid SSL key/certificate in either pkcs#1 or pkcs#8 format.

Actual behavior: docker login fails with error 500, core.log contains the message: "[ERROR] [token.go:48]: Unexpected error when creating the token, error: unable to decode private key PEM: unable to get PrivateKey from PEM type: PRIVATE KEY", when installed on a rhel7 host via docker-compose.

**Steps to reproduce the problem:**
Install harbor via docker-compose on a rhel7 (or probably centos7 machine). Enable SSL, and provide a private key in either pkcs#1 or pkcs#8 format.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.7.5-a8f6543a
- docker engine version: 17.05.0-ce
- docker-compose version: 1.24.0

**Additional context:**
The registry (apparently) wants a pkcs#1 key for SSL. All the openssl commands that should generate an RSA key in pkcs#1 format or convert pkcs#8 to pkcs#1 return a pkcs#8 key on my rhel7 and centos7 hosts. The workaround I found was to convert my pkcs#8 key to pkcs#1 on a centos6 vm and set "customize_crt = off" in harbor.cfg.

**Comment by reasonerjt** [comment]
@xaleeks I see that we need a plan for what OS distro will be supported, we will also need to control the effort for complicated test matrix.

**Comment by Chris-Lauer** [comment]
Seems to work in 1.10.1!

**Comment by Chris-Lauer** [comment]
Some of it was fixed,

**Comment by Chris-Lauer** [comment]
Some of it was fixed, but I discovered the TLS certificate generated for the handshake between core and registry still wasn't working. I had to generate and exchange that certificate pair manually.

**Comment by Shalrath** [comment]
> Some of it was fixed, but I discovered the TLS certificate generated for the handshake between core and registry still wasn't working. I had to generate and exchange that certificate pair manually.

Could you detail which certs you had to replace?  Also, I'm using a wildcard cert for the domain this resides in, so I'm wondering if that can just be dropped in.

**Comment by wadeholler** [comment]
@Chris-Lauer - could you explain a bit more ?  I don't understand from the above how to fix my fresh 2.0.0 harbor installation on centos7

**Comment by Vermillionaire** [comment]
This is what I did to fix the issue:
```
# Bring harbor down
sudo docker-compose down -v
# Make a backup of private key
cp /data/secret/core/private_key.pem /data/secret/core/private_key.pem.bak
 
# Copy file to non-RHEL machine
scp /data/secret/core/private_key.pem <your_machine>
# Convert Private key
openssl rsa -in private_key.pem -out private_key.pem
# Replace old private key with new generated key
# The top of the key should say:
# -----BEGIN RSA PRIVATE KEY-----
# instead of
# -----BEGIN PRIVATE KEY-----
 
# Fix any permissions that got messed up
chown -R 10000:10000 /data/secret/core/
chmod -R  600 /data/secret/core
```

**Comment by wadeholler** [comment]
thank you @Vermillionaire !!!

**Comment by wy65701436** [comment]
Per this PR, https://github.com/goharbor/harbor/commit/9ef7e22e8e375b5cd6834efc21e778fb2623d2eb, suppoes that Harbor supports it now. Please try with v2.3.5+.
