### ISSUE TITLE
harbor Core : failed to get metadata, key:ui_url, error:<nil>, skip to load item

### ISSUE THREAD

**Issue by bansalrajat** [goharbor/harbor#7852]
What can we help you?

I am getting below warnings  in core.log when installing harbor v1.8.0-rc2 .how can i resolve these warnings .Can i ignore them?

May 21 11:34:21 172.18.0.1 core[3660]: 2019-05-21T10:34:21Z [WARNING] [/common/config/store/driver/db.go:43]: failed to get metadata, key:ui_url, error:<nil>, skip to load item
May 21 11:34:21 172.18.0.1 core[3660]: 2019-05-21T10:34:21Z [WARNING] [/common/config/store/driver/db.go:43]: failed to get metadata, key:reload_key, error:<nil>, skip to load item
May 21 11:34:21 172.18.0.1 core[3660]: 2019-05-21T10:34:21Z [WARNING] [/common/config/store/driver/db.go:43]: failed to get metadata, key:cfg_expiration, error:<nil>, skip to load item

**Comment by Poil** [comment]
Hi,
Same here

**Comment by stonezdj** [comment]
They are staled configure items.

Remove these unused key in postgres
```
docker exec -it harbor-db bash
```
Execute commands in container console
```
psql -U postgres
\c registry
delete from properties where k in ('ui_ur', 'reload_key', 'cfg_expiration');
```

**Comment by Poil** [comment]
Thanks,
I had to do that
```
delete from properties where k in ('ui_url', 'reload_key', 'cfg_expiration');
delete from properties where k like 'mysql_%';
delete from properties where k = 'sqlite_file';
```

**Comment by petvaa01** [comment]
We had somewhat similar issue after upgrading Harbor from 1.7.4 to 1.8.2. Excessive amount of logs were constantly being produced peaking well over 1M/h. 

```bash
2019-09-03T12:59:59Z [WARNING] [/common/config/store/driver/db.go:43]: failed to get metadata, key:reload_key, error:<nil>, skip to load item
2019-09-03T12:59:59Z [WARNING] [/common/config/store/driver/db.go:43]: failed to get metadata, key:cfg_expiration, error:<nil>, skip to load item
2019-09-03T12:59:59Z [ERROR] [/common/config/store/store.go:67]: error when loading data item, key ldap_base_dn, value , error the configure value can not be empty
2019-09-03T12:59:59Z [ERROR] [/common/config/store/store.go:67]: error when loading data item, key ldap_url, value , error the configure value can not be empty
```

Deleting `reload_key`, `cfg_expiration` `ldap_url` and `ldap_base_dn` keys fixed the issue.

Anyway I think this issue should be reopened and Harbor should handle empty values more gracefully.
