### ISSUE TITLE
unsupported media type: application/octet-stream

### ISSUE THREAD

**Issue by wzcwts521** [goharbor/harbor#7854]
A replication rule has been set to pull images while is being used for migration images from unsecured docker registry to harbor container registry. About half of the repositories with following error
```unsupported media type: application/octet-stream```

**Comment by ywk253100** [comment]
What's the version of the docker registry you are using? And for the failed images, do you know the version of docker client used to push them into the docker registry?

**Comment by wzcwts521** [comment]
Thanks @ywk253100  
Unfortunately, I don't have to way to track, I guess some of the images were build/push from docker 1.10

Closing this ticket. I suppose this is not an issue for the newer images, since we have upgrade our "build host" with "newer" version of docker
