### ISSUE TITLE
HTTPS configure forbidden: User "system:anonymous" cannot get path "/"

### ISSUE THREAD

**Issue by jahentao** [goharbor/harbor#7863]
I follow the [configure_https guide](https://github.com/goharbor/harbor/blob/master/docs/configure_https.md), but found it is not updated in time, such as the `harbor.cfg` not the `harbor.yml`, so the update details may be the reason leads to my error. 

**Expected behavior and actual behavior:**

I expected to use https to browser harbor, it seems that I have no permission.

After my configuration, and when I use https to browser, I got the 'Forbidden' error.

```json
{
kind: "Status",
apiVersion: "v1",
metadata:{},
status: "Failure",
message: "forbidden: User "system:anonymous" cannot get path "/"",
reason: "Forbidden",
details:{},
code: 403
}
```

**Steps to reproduce the problem:**

Follow the [configure_https guide](https://github.com/goharbor/harbor/blob/master/docs/configure_https.md), replace the `yourdomain.com` with actual ip, such as `35.194.117.80` in releated steps.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.0
- docker engine version: 18.09.6
- docker-compose version: 1.23.1

**Additional context:**
* **Harbor config files:** 
[harbor.yml.tar.gz](https://github.com/goharbor/harbor/files/3206074/harbor.yml.tar.gz)
* **Log files:** You can get them by package the `/var/log/harbor/` .
[harbor.tar.gz](https://github.com/goharbor/harbor/files/3206076/harbor.tar.gz)

**Comment by heww** [comment]
@ninjadq configure_https doc needed to be updated to match version 1.8

**Comment by heww** [comment]
@jahentao unarchive the harbor.yml.tar.gz got 000000 harbor.yml file. Can you confirm that there is no problem with the file?

**Comment by jahentao** [comment]
@heww  I'm sorry for that. Here is the `harbor.yml` content.
```sh
$ cat harbor/harbor.yml| grep -v '#' | sed '/^$/d'
hostname: 35.194.177.80
https:
  port: 443
  certificate: /data/cert/35.194.177.80.crt
  private_key: /data/cert/35.194.177.80.key
harbor_admin_password: Harbor12345
database:
  password: root123
data_volume: /data
clair:
  updaters_interval: 12
  http_proxy:
  https_proxy:
  no_proxy: 127.0.0.1,localhost,core,registry
jobservice:
  max_job_workers: 10
chart:
  absolute_url: disabled
log:
  level: info
  rotate_count: 50
  rotate_size: 200M
  location: /var/log/harbor
_version: 1.8.0
```

**Comment by jahentao** [comment]
I have fix the problem, and I will add an IP demo, and update the config file to `harbor.yml`.
