### ISSUE TITLE
Default admin with password Harbor12345 not work,login failed

### ISSUE THREAD

**Issue by whmzsu** [goharbor/harbor#7866]
Problem : Default admin with password Harbor12345 not work,login failed
Setup config : Nothing  but only change  http port from 80 to 8080

Harbor version: 1.8.0
docker version 
Server: Docker Engine - Community
Engine:
Version:          18.09.6

docker-compose
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

**Comment by whmzsu** [comment]
After 10 minutes or more  waiting, now I can login to the web UI, so I will close the issue right now !

**Comment by wmullen0** [comment]
you simply had to wait 10 mins for the admin credentials to work?

**Comment by eXtrem0us** [comment]
I have the same issue and I can not login with the default password

**Comment by obeyler** [comment]
same
