### ISSUE TITLE
Language drop-down label and user name getting overlapped

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#7870]
Can we please align switch language drop-down label and user name label properly? As of now they are getting overlapped.

![image](https://user-images.githubusercontent.com/8274052/58169790-3f062880-7caf-11e9-8102-b6438d5a46b9.png)

**Comment by zhoumeina** [comment]
fixed by :#7916

**Comment by arsulesandy** [comment]
Thank You @zhoumeina
