### ISSUE TITLE
How to limit the network traffic when  replicate images between two harbor in the first time.

### ISSUE THREAD

**Issue by HelenaZheng** [goharbor/harbor#7873]
I set replication rules with trigger mode: now and copy all images now. So all the images in the replicated project will be copy from the harbor to another harbor. At the same time, I find the all the network traffic has been owned and other application can not communicate with outside with network. 
So I need to know how to limit the network traffic when replicate images between two harbor in the first time.

我在两个harbor的首次镜像同步中选择触发模式：“即刻”，同时复制所有的镜像，这时候镜像同步就会占有所有的网络带宽。我如何限制这个同步的流量？

**Comment by heww** [comment]
Hi @HelenaZheng , we suggest that there are two options to deal with this problem.

1. Reduce the `max_job_workers` of `jobservice` , eg change it from 10 to 5

2. Limit the traffic at  VM/Container level
