### ISSUE TITLE
Problems with LDAP configuration

### ISSUE THREAD

**Issue by killdaemon** [goharbor/harbor#7874]
Hi, I was testing the new released 1.8 version because I have the same issue with the LDAP integration that is mentioned in the [PR#6161](https://github.com/goharbor/harbor/pull/6599/files). This one refers to the **memberof** parameter harcoded. 

This parameter is available to be configured in th 1.8.0.

The problem comes when you try to configure this parameter. The LDAP section is not available anymore in the installation configuration (the change from 1.7.5 harbor.cfg to 1.8.0 harbor.yml), and from the UI this field is not available as a paremeter in the LDAP section.

So, how we can configurethis parameter (LdapGroupMembershipAttribute)?

Thanks!

**Comment by stonezdj** [comment]
Please refer https://github.com/goharbor/harbor/blob/master/docs/configure_user_settings.md
The param is ldap_group_membership_attribute.
