### ISSUE TITLE
Add AWS $ GCS pipeline for harbor offline nightly test

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7879]
We need to enable a pipeline to test push/pull to GCS.

**Comment by reasonerjt** [comment]
So far we don't verify the push/pull to S3 either.
Lower the priority.
Let's engage @xaleeks about the priority and support matrix.

**Comment by danfengliu** [comment]
Both AWS and GCS pipeline were added into Jenkins nightly test, AWS passed all test cases and it was added into nightly kick-off pipeline, but in GCS pipeline, there's 2 product issues was caught (#9453 and GC Error issue), so it will be added into nightly kick-off pipeline right after issues were fixed.
