### ISSUE TITLE
本机非root用户可以部署harbor吗？

### ISSUE THREAD

**Issue by chuck6** [goharbor/harbor#7882]
What can we help you?
打算用普通的docker权限的用户部署harbor ，目前用户docker可以执行docker命令，进行创建docker容器，在执行./install.sh的时候，在启动各个容器的就开始报错，看到目录下面的docker-compose,yml怎么都是root 权限了，手动改了docker-compose,yml用户权限，手动去启动docker-compose中的各个容器，发现jobserver/core/nginx还是报错，查看各个日志发现是由于读容器内的各个文件没有权限。
我有点疑问了难道部署harbor的时候需要root用户才能部署吗？是否只有root才能去创建和容器内对应的用户ID的用户来适配，否则还是会有问题的。
盼望得到各个大佬的解释，谢谢！

**Comment by chuck6** [comment]
使用的是最新的版本harbor V1.8.0

**Comment by heww** [comment]
@chuck6 Sorry, currently v1.8.0 can not be installed by no-root user. We will fix this problem.

**Comment by reasonerjt** [comment]
@heww I think you have to use root to run `prepare`?

**Comment by kkfinkkfin** [comment]
Is it possible to install Harbor which the latest version is 1.10.1  using non-root now？

**Comment by voctex** [comment]
Is it possible to install Harbor which the latest version is 2.1.1 using non-root user now？

**Comment by MinerYang** [comment]
dup with https://github.com/goharbor/harbor/issues/17494
