### ISSUE TITLE
harbor-migration cannot properly recognize cfg vs yaml file

### ISSUE THREAD

**Issue by balonik** [goharbor/harbor#7883]
**Expected behavior and actual behavior:**
Changes to the `tools/migration/cfg/utils.py` in https://github.com/goharbor/harbor/commit/64b16c891587dbb3aeec251d4e24294a48a5f0e6 are causing TypeError Exception in case when `harbor.cfg` does not contain comments.
The expected YAML exception is not raised, because the harbor.cfg is in valid YAML format.
In such case the content of `harbor.cfg` is loaded as YAML single string:
`"_version = 1.7.0 hostname = harbor.example.com ui_url_protocol = https max_job_workers = 10 customize_crt = off ..."`

```
Please backup before upgrade,
Enter y to continue updating or n to abort: y
Command for config file migration: python ./cfg/run.py --input /harbor-migration/harbor-cfg/harbor.cfg --output /harbor-migration/harbor-cfg-out/harbor.yml
Traceback (most recent call last):
  File "./cfg/run.py", line 70, in <module>
    main()
  File "./cfg/run.py", line 24, in main
    input_version = utils.get_conf_version(args.input_path)
  File "/harbor-migration/cfg/utils.py", line 41, in get_conf_version
    return d["_version"]
TypeError: string indices must be integers, not str
```

**Steps to reproduce the problem:**
1. create `harbor.cfg` without any comments
```
_version = 1.7.5
hostname = harbor.example.com
ui_url_protocol = https
max_job_workers = 10
customize_crt = off
...
```
2. run the migration docker image
`docker run -it --rm -v /root/harbor-1.7.5/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /root/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.8.0 --cfg up`
3. TypeError exception

**Versions:**
N/A

**Additional context:**
N/A

**Comment by reasonerjt** [comment]
@ninjadq could you double check if this has been fixed?

**Comment by ninjadq** [comment]
Cannot reproduce in the current version. I think it's already fixed
