### ISSUE TITLE
Incorrect Email (placeholder) is shown when using Gitlab as OIDC provider

### ISSUE THREAD

**Issue by konstantinpae** [goharbor/harbor#7885]
**Docker Version**
Docker version 18.09.6, build 481bc77
**Docker Compose Version**
docker-compose version 1.23.2, build 1110ad01
**Harbor Version**
1.8.0
**Gitlab Version**
11.9.7-ee (782806f)

The signup process itself using Gitlab as OIDC Provider is working without any issues. However, when a user is logging in a user account is created but the associated email address is of the format
`5eea2h6bzid4qgh95enqpbjfo8f9497x@placeholder.com`
**Scopes set in Gitlab**
![image](https://user-images.githubusercontent.com/7922974/58249438-29e8d280-7d5f-11e9-8c73-15608556156a.png)
**Configuration in Harbor**
![image](https://user-images.githubusercontent.com/7922974/58249565-86e48880-7d5f-11e9-8f67-022cce866b25.png)

**Comment by Doublemine** [comment]
> The signup process itself using Gitlab as OIDC Provider is working without any issues. However, when a user is logging in a user account is created but the associated email address is of the format
> `5eea2h6bzid4qgh95enqpbjfo8f9497x@placeholder.com`
> **Scopes set in Gitlab**
> ![image](https://user-images.githubusercontent.com/7922974/58249438-29e8d280-7d5f-11e9-8c73-15608556156a.png)
> **Configuration in Harbor**
> ![image](https://user-images.githubusercontent.com/7922974/58249565-86e48880-7d5f-11e9-8f67-022cce866b25.png)

I have same problem, install env as follow:
**Gitlab Version**: `11.11.3`
**Helm Version**: `v2.13.1`
**Chart Version**: `harbor-1.1.0`
**APP Version**: `1.8.0`

**Comment by jsimomaa** [comment]
We are also experiencing this issue with GitLab OIDC. I tried to grep the log files but could not find anything related to this.

**Comment by kurbar** [comment]
Same issue occurs when using OIDC with Office365. Seems to be a general issue. Trying to see if I can dig up anything else.

**Comment by Doublemine** [comment]
I solved this problem by [dex](https://github.com/dexidp/dex/). Maybe you can try it.

**Comment by kurbar** [comment]
I did some debugging with https://openidconnect.net/ and Microsoft does respond with the email and looking at dex, the object syntaxes are correct for both so there should not be any issues for the email to be fetched. I checked the controllers/oidc.go source and the interface for marshalling looks correct as well but for some reason the email just comes up empty.
