### ISSUE TITLE
从registry源拉取镜像到harbor中报错

### ISSUE THREAD

**Issue by chuck6** [goharbor/harbor#7886]
点击同步按钮，发现该job只同步了79%，任务报failed 。
查看jobservice的日志，有如下报错。还请专家指点一下，特别在于“blob unknown to registry”
May 23 19:58:19 172.21.0.1 jobservice[101852]: 2019-05-23T11:58:19Z [ERROR] [/replication/transfer/image/transfer.go:216]: failed to pulling the blob sha256:e6fae9294c3500622ea5f401c07be6bc8d2e5dcbb74431c0e4aec037002b52c3: http error: code 404, message {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:e6fae9294c3500622ea5f401c07be6bc8d2e5dcbb74431c0e4aec037002b52c3"}]}
May 23 19:58:19 172.21.0.1 jobservice[101852]: 2019-05-23T11:58:19Z [ERROR] [/replication/transfer/image/transfer.go:81]: http error: code 404, message {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:e6fae9294c3500622ea5f401c07be6bc8d2e5dcbb74431c0e4aec037002b52c3"}]}
May 23 19:58:19 172.21.0.1 jobservice[101852]: 2019-05-23T11:58:19Z [ERROR] [/jobservice/runner/redis.go:63]: |@_@| Job 'REPLICATION:cbd8eb75b4cdfbc1328a0b8a' exit with error: http error: code 404, message {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:e6fae9294c3500622ea5f401c07be6bc8d2e5dcbb74431c0e4aec037002b52c3"}]}

**Comment by heww** [comment]
Can you provide the source filters used to match images of the registry (hub.docker.com, right) ?
