### ISSUE TITLE
Refreshing the UI results in "authentication required"

### ISSUE THREAD

**Issue by krausexb** [goharbor/harbor#7887]
I installed a Harbor instance, based on the Helm Charts(Branch 1.1.0) and used Ingress to expose the Service. The instance is working fine and I dont retrieve error messages. The only thing which seems kinda weird to me is the following szenario.

Calling the UI from https://fqdn/ works fine.
But refreshing the page always results in the following error.

My ingress configuration:
![grafik](https://user-images.githubusercontent.com/50952100/58251655-6ff46500-7d64-11e9-9fef-2c8ff032dc9b.png)

The Error:
![grafik](https://user-images.githubusercontent.com/50952100/58251386-c614d880-7d63-11e9-95b1-cfd337e3277e.png)

**Comment by heww** [comment]
Which auth mode used by the harbor instance, db, ldap or oidc ? 

Which page will cause this problem? Or all pages will cause this problem ?

**Comment by krausexb** [comment]
Ich fixed the bug by my self. The Problems were caused by the Traefik Ingress Controller. As soon a I switched to NGINX everything was working fine.
