### ISSUE TITLE
Tagging problem with alternative container engine

### ISSUE THREAD

**Issue by hardoverflow** [goharbor/harbor#7897]
**Description:**
Images created using docker alternatives (in this case podman as well as buildah) are not properly displayed in the Harbor GUI. The image tagged "test" was created using podman. Note the missing "Creation Date" and "Docker Version" entries. Also the "Size" entry is displayed as being 0B. "latest" and "7" where created using docker. These are correctly displayed.

**Expected behavior and actual behavior:**
Expected behaviour: Harbor should display various images attributes (Tag, Size, Creation Date, Docker Version) for the images in a repository Actual Behaviour: For images that not created using docker, the images attributes (with the exception of "Tag") are either not displayed or the displayed values are incorrect.

**Steps to reproduce the problem:**
Use either podman or buildah to create an image and push this image to Harbor. Examine the image attributes in the Harbor GUI.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.8.0
- podman: v0.12.1.2
- buildah: v1.7.1

**Additional context:**
```{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI manifest found, but accept header does not support OCI manifest"}]}```

**Screenshot:**
![2019-05-24 09_47_43-Harbor_Podman_tags](https://user-images.githubusercontent.com/4113231/58323147-6ed63d00-7e23-11e9-915d-08ebcc68c6c1.png)

![2019-05-24 09_42_40-Harbor_Podman](https://user-images.githubusercontent.com/4113231/58323350-fe7beb80-7e23-11e9-9aba-f7fcb2fbe351.png)

**Comment by wy65701436** [comment]
thanks @hardoverflow, we do not have harbor tested on podman, which may lead to some unknown issues. 

Is it possible that file an requirement to support manage images created by podman?

**Comment by cfrantsen** [comment]
We have this issue as well. Pushing a new updated image built with buildah/podman "on top" of an existing image that has been built with docker results in the error seen in the screenshot. If we push a completely new image nothing appears in the UI at all, although this image can still be pulled.

**Comment by Logibox** [comment]
I found this happens when using Skopeo too. The funny thing is the images can still be pulled after upload and work fine, they just don't show up in the GUI. Perhaps the harbor GUI does not support OCI images, despite the registry working fine with them.

**Comment by Logibox** [comment]
A workaround that I use is the `--format=v2s2` for skopeo and everything works fine. I think the problem here is the registry used by harbor advertises OCI support but the rest of the services in harbor do not support it.

**Comment by Kruemelmann** [comment]
Hi Is there any plan for the future to make OCI images 'visible' on the harbor ui.

**Comment by ywk253100** [comment]
The issue should already be fixed in v2.0 which supports OCI artifacts, closing it
