### ISSUE TITLE
rancher新版本拉取新版本的harbor1.8的chartrepo可以启动，但是不能部署成功

### ISSUE THREAD

**Issue by fengshunli** [goharbor/harbor#7899]
rancher测试1.6版本以及1.7版本都是一样的效果
![image](https://user-images.githubusercontent.com/18587688/58367385-26954880-7f11-11e9-801b-89f51f4a358d.png)

**Comment by heww** [comment]
Set `chart.absolute_url` config to `enabled` will fix this problem.

See more info https://github.com/rancher/rancher/issues/18535#issuecomment-494036451

**Comment by heww** [comment]
@steven-zou  @ywk253100 @ninjadq how about enable the absolute url for chart as default config ?
