### ISSUE TITLE
how to configure DSN to support the insecure old password authentication

### ISSUE THREAD

**Issue by iluoxw** [goharbor/harbor#7900]
### The Error Log:
`May 25 11:46:31 172.20.0.1 jobservice[785]: 2019-05-25T03:46:31Z [FATAL] [main.go:41]: failed to initialize database: register db Ping `default`, This server only supports the insecure old password authentication. If you still want to use it, please add 'allowOldPasswords=1' to your DSN. See also https://github.com/go-sql-driver/mysql/wiki/old_passwords
May 25 11:46:31 172.20.0.1 jobservice[785]: [ORM]register db Ping `default`, This server only supports the insecure old password authentication. If you still want to use it, please add 'allowOldPasswords=1' to your DSN. See also https://github.com/go-sql-driver/mysql/wiki/old_passwords`

**Comment by wy65701436** [comment]
hi @iluoxw , harbor has been migrated DB to postgresql from v1.6.0. 

MySQL was dropped in the current release, please upgrade to the latest version to get support.
