### ISSUE TITLE
How to disable self-registration in harbor 1.8.0?

### ISSUE THREAD

**Issue by Hotege** [goharbor/harbor#7901]
harbor.cfg includes setting self_registration while harbor.yml not.

**Comment by wy65701436** [comment]
you can find it in the configuration page when to login as a system admin.

**Comment by lexkwan** [comment]
![image](https://user-images.githubusercontent.com/30421936/58405114-4a839600-8099-11e9-9b5d-ac850414cc31.png)

**Comment by Hotege** [comment]
i see. i've forgot it.
