### ISSUE TITLE
minutely cron replication inconsistent

### ISSUE THREAD

**Issue by d2dyno** [goharbor/harbor#7902]
**Expected behavior and actual behavior:**
Expected:
Setting a cron string for replication, should replicate the source registry on time, every time. For example, every minute.

Actual:
Setting the cron string to `*/59 * * * * *`, will not run every minute, and there doesn't seem to be a rhyme or reason as to why. In the screenshot below, this can be seen.
![Harbor (2)](https://user-images.githubusercontent.com/2421939/58399697-9f35fb00-801e-11e9-946a-a2642656e44c.png)

**Steps to reproduce the problem:**
Set up a docker-registry provider, with basic authentication and verify remote cert=true.
Set up replication of above registry (pull-based), with trigger mode set to scheduled, and the cron to be `*/59 * * * * *`. Override=true; enable=true

**Versions:**
- harbor version: 1.8.0
- docker engine version: 18.09.6
- docker-compose version: 1.24.0

**Comment by wy65701436** [comment]
please provide core.log and jobservice.log

**Comment by d2dyno** [comment]
[logs.zip](https://github.com/goharbor/harbor/files/3222595/logs.zip)

**Comment by ywk253100** [comment]
Is there any other tasks running? If no available job workers for the tasks to run, they will be put in a queue and pending for workers.

**Comment by GDixon7623** [comment]
We are seeing the same issue, We setup to run every 10 minutes and in the past hour it ran at 12:00, 12:20, 12:50, 13:00 no other tasks running.

**Comment by ywk253100** [comment]
@GDixon7623 How many tasks it produces for each running? Could you provide more detail information for us so that we can find out what happened? Upload all the logs maybe helpful.

**Comment by d2dyno** [comment]
Probably closed with https://github.com/goharbor/harbor/issues/8145

**Comment by steven-zou** [comment]
Fixed, Close

**Comment by steven-zou** [comment]
Patch is contained in V1.8.2
