### ISSUE TITLE
documentation: harbor.cfg references

### ISSUE THREAD

**Issue by maxfunke** [goharbor/harbor#7907]
The docs almost always refere to **harbor.cfg** file. However I'd say it should be /make/**harbor.yml**

![harbor-cfg](https://user-images.githubusercontent.com/1723053/58419452-eeb21080-808a-11e9-91e4-5d2de11126f4.jpg)

**Comment by wy65701436** [comment]
thanks @maxfunke

**Comment by reasonerjt** [comment]
@ninjadq can you fix it?
