### ISSUE TITLE
[GC] Running GC without stopping Harbor services

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#7910]
Harbor Version:1.6.0
Currently, we are running GC using bash script(with crontab):
#!/bin/bash
puppet agent --disable
cd /liveperson/harbor
/usr/local/bin/docker-compose stop
docker run -i --name gc --rm --volumes-from registry goharbor/registry-photon:v2.6.2-v1.6.0 garbage-collect  /etc/registry/config.yml
/usr/local/bin/docker-compose start
puppet agent --enable

As you see, We are fully stopping Harbor while performing GC. 
I'm looking for a way to perform GC without taking down Harbor.
Is the read-only option exist in 1.6.0? and how can I automatically enable and disable read-only mode while GC is running?

Also, What is the difference between how is GC working on 1.6.0 and 1.8?

**Comment by wy65701436** [comment]
it's already in from v1.6.0, just find it in the UI.

**Comment by YakirShriker** [comment]
I don't see any GC option in UI.
Only read-only. 
But can't find any automation for enabling read-only using API.
