### ISSUE TITLE
harbor database CrashLoopBackOff after restart all harbor pods by k8s

### ISSUE THREAD

**Issue by NanXuejiao** [goharbor/harbor#7912]
I got [adminserver, clair, core, database] CrashLoopBackOff after restart all harbor pods by k8s. And log of these pods point it's database caused, the following is database log, but I don't known how to fix it?
```
LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.auto.conf"
postgres: could not find the database system
Expected to find it in the directory "/var/lib/postgresql/data",
but could not open file "/var/lib/postgresql/data/global/pg_control": No such file or directory
```

**Comment by Ghostbaby** [comment]
are you use PVC to storage the pg database file?

**Comment by NanXuejiao** [comment]
> are you use PVC to storage the pg database file?

Yes.
 I got this eroor, and then delete pvc,pv and restart all pods, also have this error

**Comment by reasonerjt** [comment]
@NanXuejiao If you are still experiencing this error could you open an issue to the repo goharbor/harbor-helm?

**Comment by NanXuejiao** [comment]
> @NanXuejiao If you are still experiencing this error could you open an issue to the repo goharbor/harbor-helm?

Oh, I didn't notice repo `goharbor/harbor-helm`.
Thank you, I'll close this issue and then open issues to `harbor-helm` when I have issues.
