### ISSUE TITLE
how to change default registry port 5000

### ISSUE THREAD

**Issue by GitHubStevenLiu** [goharbor/harbor#7917]
harbo:v1.8.0
 I change harbor ui default port 80 in harbor.yml , but i do not know how to change default registry port  5000 .

I add port: 50001:5000  in docker-compose.yml 's registry ,but after install , It was reset.

I guess that i should change in  harbor.yml , but how ?

**Comment by ywk253100** [comment]
Harbor exposes the registry service and portal on the same port (80 by default). You can pull/push images with the port directly
