### ISSUE TITLE
Helm authentication without admin

### ISSUE THREAD

**Issue by mmellin** [goharbor/harbor#7920]
In the Harbor documentation (https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#manage-helm-charts) it mentions using Harbor admin credentials for adding a Helm repo, or using a Helm repo.  While this seems to work, I don't want to give out admin credentials to all developers.  

Is there a way to make this work with the developers' own credentials?  Currently we are using LDAP at the moment.  I cannot get this work work, even though my own user is a "project admin".

**Comment by heww** [comment]
Hi, there are two options to add helm repo.

1. Add Harbor as a unified single index entry point (eg, `http://192.168.1.100/chartrepo`) require system admin's credentials

2. Add Harbor project as separate index entry point (eg, `http://192.168.1.100/chartrepo/library`) require project member's credentials or any user's credentials when project is public.

**Comment by mmellin** [comment]
Thanks @heww .  Step #2 does not work for me with credentials other than admin.  Both steps seems to work with admin credentials however.  Is there some configuration I may be missing?

```
user1@mbp $ helm repo add --ca-file registry-prod.ca-bundle --username user1   --password <mypassword> repo1 https://registry-prod.mydomain.net/chartrepo/project1
Error: Looks like "https://registry-prod.mydomain.net/chartrepo/project1" is not a valid chart repository or cannot be reached: Failed to fetch https://registry-prod.mydomain.net/chartrepo/project1/index.yaml : 401 Unauthorized

user1@mbp $ helm repo add --ca-file registry-prod.ca-bundle --username admin --password <password> repo1 https://registry-prod.mydomain.net/chartrepo/project1
"repo1" has been added to your repositories
```

**Comment by heww** [comment]
```
user1@mbp $ helm repo add --ca-file registry-prod.ca-bundle --username user1   --password <mypassword> repo1 https://registry-prod.mydomain.net/chartrepo/project1
Error: Looks like "https://registry-prod.mydomain.net/chartrepo/project1" is not a valid chart repository or cannot be reached: Failed to fetch https://registry-prod.mydomain.net/chartrepo/project1/index.yaml : 401 Unauthorized
```
The error info indicate that the password for the user1 maybe wrong. 

If it is the permission issue, the response code will be 403. 

So please check the password argument, especially some characters needed to be escaped in shell.

**Comment by mmellin** [comment]
@heww Looks like you are correct.  I needed to escape a character ("$") in my password - like `--password mypa\$\$word`

Thanks, option #2 now works (eg, `http://192.168.1.100/chartrepo/library`)
