### ISSUE TITLE
The size are 0 images always in the registry.

### ISSUE THREAD

**Issue by ygqygq2** [goharbor/harbor#7924]
The images have been deleted, but them always in the registry.`v1.7.4` and `v1.8.0` are the same.

![image](https://user-images.githubusercontent.com/17672440/58535033-66b13f80-821f-11e9-8c40-f592bdb33dc4.png)

**Comment by nisc-acooper** [comment]
we see similar in our instance, running 1.7.4
![image](https://user-images.githubusercontent.com/1648514/58738339-fba46c00-83ca-11e9-843b-1984c91f0779.png)
The date is always the same and old.  when attempting to look at a tag, you get a MANIFEST_UNKNOWN error.   seems to be possible out-of-sync between docker registry and harbor?

**Comment by ygqygq2** [comment]
@nisc-acooper I had fixed this problem. 
eg.
`mv /data/registry/docker/registry/v2/repositories/pub/catering-service/_manifests/tags/1.0.15-SNAPSHOT /tmp/`

**Comment by louyiping** [comment]
@nisc-acooper My solution is pushing an image with the same tag name for those "problem" tags. And then delete them one by one.
