### ISSUE TITLE
Getting error while pushing trusted image to harbor

### ISSUE THREAD

**Issue by lordcf** [goharbor/harbor#7928]
What can we help you?
Error: error contacting notary server: x509: certificate signed by unknown authority

**Comment by lordcf** [comment]
Error: error contacting notary server: x509: certificate signed by unknown authority

**Comment by reasonerjt** [comment]
You need extra steps to make docker communicate with notary with self-signed cert, see:
https://github.com/goharbor/harbor/blob/master/docs/use_notary.md

**Comment by lyoumar** [comment]
When i try to push the image with DOCKER_CONTENT_TRUST=1, i am getting this same issue:
Signing and pushing trust metadata
Error: error contacting notary server: x509: certificate signed by unknown authority.

I make a test connection between the nginx and notary-server:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
sh-4.4$ openssl s_client -connect notary-server:4443 -CAfile /etc/nginx/cert/ca.crt -no_ssl3 -no_ssl2
CONNECTED(00000003)
140032502251136:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 307 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1615988377
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
