### ISSUE TITLE
docker push 时出错Preparing error parsing HTTP 404 response body: unexpected end of JSON input: "" 

### ISSUE THREAD

**Issue by bear280** [goharbor/harbor#7930]
docker push harbor.xxx.cn/test/centos:7 
报如下错误码：
 [root@zTestWMS ~]# docker login harbor.xxx.cn 
Authenticating with existing credentials... WARNING! Your password will be stored unencrypted in /root/.docker/config.json. Configure a credential helper to remove this warning. See https://docs.docker.com/engine/reference/commandline/login/#credentials-store  Login Succeeded [root@zTestWMS ~]# docker push harbor.xxx.cn/test/centos:7 
The push refers to repository [harbor.xxxcn/test/centos] d69483a6face: 
Preparing error parsing HTTP 404 response body: unexpected end of JSON input: "" 
 其中架构为：公网IP（nginx）->私网IP（harbor）

**Comment by bear280** [comment]
其中架构为：域名（harbor.xxx.cn）-->公网IP（nginx）->私网IP（harbor）
harbor.yml中hostname=harbor.xxx.cn

**Comment by Ghostbaby** [comment]
nginx 做的是tcp转发吗？

**Comment by bear280** [comment]
location / {
                    proxy_redirect off;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    #proxy_set_header X-Forwarded-Proto $scheme;
                    fastcgi_connect_timeout 1800s;
                    fastcgi_send_timeout 1800s;
                    fastcgi_read_timeout 1800s;
                    fastcgi_buffer_size 1024k;
                    fastcgi_buffers 32 1024k;
                    fastcgi_busy_buffers_size 2048k;
                    fastcgi_temp_file_write_size 2048k;
                    client_max_body_size 0;
                    client_body_buffer_size 0;
                    proxy_connect_timeout 1800;
                    proxy_send_timeout 1800;
                    proxy_read_timeout 1800;
                    proxy_buffer_size 1024k;
                    proxy_buffers 32 1024k;
                    proxy_busy_buffers_size 2048k;
                    proxy_temp_file_write_size 2048k;
                    #add_header X-Cache $upstream_cache_status;
                    proxy_pass http://172.16.10.12;
        }

**Comment by bear280** [comment]
> nginx 做的是tcp转发吗？

        location / {
                    proxy_redirect off;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    #proxy_set_header X-Forwarded-Proto $scheme;
                    fastcgi_connect_timeout 1800s;
                    fastcgi_send_timeout 1800s;
                    fastcgi_read_timeout 1800s;
                    fastcgi_buffer_size 1024k;
                    fastcgi_buffers 32 1024k;
                    fastcgi_busy_buffers_size 2048k;
                    fastcgi_temp_file_write_size 2048k;
                    client_max_body_size 0;
                    client_body_buffer_size 0;
                    proxy_connect_timeout 1800;
                    proxy_send_timeout 1800;
                    proxy_read_timeout 1800;
                    proxy_buffer_size 1024k;
                    proxy_buffers 32 1024k;
                    proxy_busy_buffers_size 2048k;
                    proxy_temp_file_write_size 2048k;
                    #add_header X-Cache $upstream_cache_status;
                    proxy_pass http://172.16.10.12;
                    #proxy_pass http://localhost:9980;
        }

**Comment by Ghostbaby** [comment]
另外添加一个443的转发试试

**Comment by bear280** [comment]
我在内网就是用http协议，内网使用docker login 172.16.10.12    正常
docker push 172.16.10.12/test/centos:7 也是正常的。

**Comment by proutek** [comment]
Add to your server block.

client_max_body_size 0;
chunked_transfer_encoding on;

**Comment by reasonerjt** [comment]
hi @bear280 is it fixed?
