### ISSUE TITLE
Tag Retention: Database Persistence

### ISSUE THREAD

**Issue by nlowe** [goharbor/harbor#7933]
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Store retention policies in the database

**Comment by nlowe** [comment]
Initial iteration available in https://github.com/nlowe/harbor/tree/feat/retention/GH-7933-database-persistence. I'll open a PR when the merge window for 1.9 opens.

**Comment by nlowe** [comment]
Hmm, the way database tests are run on travis appear different from how I was running them locally. I get this weird failure in Travis:

```txt
2019-06-10T23:24:53Z [INFO] POSTGRES_HOST: 10.20.3.234, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD: root123
2019-06-10T23:24:53Z [INFO] initializing database: type-PostgreSQL host-10.20.3.234 port-5432 databse-registry sslmode-"disable"
2019-06-10T23:24:53Z [INFO] Upgrading schema for pgsql ...
2019-06-10T23:24:53Z [INFO] No change in schema, skip.
--- FAIL: TestAddPolicy (0.02s)
    --- FAIL: TestAddPolicy/Repo (0.00s)
        <autogenerated>:1: 
            	Error Trace:	policy_test.go:78
            	Error:      	Received unexpected error:
            	            	pq: insert or update on table "retention_policy" violates foreign key constraint "retention_policy_repository_id_fkey"
            	Test:       	TestAddPolicy/Repo
--- FAIL: TestGetRepoPolicy (0.00s)
    <autogenerated>:1: 
        	Error Trace:	policy_test.go:211
        	            				policy_test.go:123
        	Error:      	Expected value not to be nil.
        	Test:       	TestGetRepoPolicy
--- FAIL: TestUpdatePolicy (0.02s)
    --- FAIL: TestUpdatePolicy/Repo_Policy (0.00s)
        <autogenerated>:1: 
            	Error Trace:	policy_test.go:154
            	Error:      	Received unexpected error:
            	            	pq: insert or update on table "retention_filter_metadata" violates foreign key constraint "retention_filter_metadata_policy_fkey"
            	Test:       	TestUpdatePolicy/Repo_Policy
FAIL
coverage: 11.1% of statements in github.com/goharbor/harbor/src/retention/dao, github.com/goharbor/harbor/src/common/dao, github.com/goharbor/harbor/src/retention/dao/models
Exec sql:DELETE FROM "retention_filter_metadata"; ALTER SEQUENCE retention_filter_metadata_id_seq RESTART;
Exec sql:DELETE FROM "retention_policy"; ALTER SEQUENCE retention_policy_id_seq RESTART;
Exec sql:DELETE FROM repository; ALTER SEQUENCE repository_repository_id_seq RESTART;
FAIL	github.com/goharbor/harbor/src/retention/dao	0.112s
The command "if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh $IP; fi" exited with 1.
```

but the tests pass locally against `postgres:9.6` and `postgres:10`.

**Comment by wy65701436** [comment]
did you commit the scheme into migration?

**Comment by nlowe** [comment]
[yup](https://github.com/nlowe/harbor/blob/feat/retention/GH-7933-database-persistence/make/migrations/postgresql/0005_retention_policies.up.sql)

**Comment by wy65701436** [comment]
can you let me know the PR?

**Comment by nlowe** [comment]
I don't have a pull request open yet, as we're still not 100% certain we're going to land this in 1.9. The best I can do is the [feature branch](https://github.com/nlowe/harbor/tree/feat/retention/GH-7933-database-persistence) and the [tracking branch with all of the work I've done so far](https://github.com/nlowe/harbor/tree/feat/retention/tracking).

**Comment by steven-zou** [comment]
@nlowe 

About the DAO code, is it adapting to the model proposed in the patch proposal PR? @bitsf will help to implement this part.

**Comment by bitsf** [comment]
I draft the DAO struct here.


type RetentionPolicy struct {
	ID int64
	// 'system', 'project' and 'repository'
	ScopeLevel string
	ScopeReference int64
	TriggerKind string
	TriggerSettings string
	// json format, include algorithm, rules, exclusions
	Data string
	CreateTime time.Time
	UpdateTime time.Time
}

type RetentionExecution struct {
	ID int64
	PolicyID int 64
	Status string
	StatusText string
	Dry bool
	// manual, scheduled
	Trigger string
	Total int
	Succeed int
	Failed int
	InProgress int
	Stopped int
	StartTime time.Time
	EndTime time.Time
}

type RetentionTask struct {
	ID int64
	ExecutionID int64
	// image, chart
	ResourceType string
	Resource string
	Status string
	StartTime time.Time
	EndTime time.Time
}

type RetentionScheduleJob struct {
	ID int64
	Status string
	PolicyID int64
	JobID int64
	CreateTime time.Time
	UpdateTime time.Time
}

**Comment by nlowe** [comment]
@steven-zou All of the code I have worked on so far was written before the proposal update was a thing, so it'll need some work but can probably serve as a good starting point.

**Comment by bitsf** [comment]
done
