### ISSUE TITLE
Using legit SSL certificate returns an error

### ISSUE THREAD

**Issue by ZeDeXBG** [goharbor/harbor#7937]
The cert I'm using is *.something.tech and my domain is test-repo.something.tech.
When I use the browser UI everything looks perfect it is https and the browser says the certificate is valid but when I try to push an image I get an error "..x509: certificate signed by unknown authority"
The VM is secure so I really dont need to be using certificate but it is required, if anybody can tell me how to disble it would work as well as resolving the problem which is in the first place and that is why the browser says everyting is fine but "docker push.." says the opposite.
Let me know if additional info is required I will gladly provide it.

Thanks in advance!

**Comment by reasonerjt** [comment]
browser doesn't says everything is fine, you explicitly allowed the untrusted cert.
you can add `--insecure-registry` to your docker daemon to by pass the check.
https://docs.docker.com/registry/insecure/
