### ISSUE TITLE
retention policy (TTL) for images per project

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#7941]
Policies to meet compliance needs and to avoid excessive storage needs for Harbor

Number of days old 
Number of tags per repository (keep N latest images)
Policies do not have to be mutually exclusive
Exceptions to policies
1. Don't delete the last remaining image
2. Exclude from policies images with label(s) XYZ

Only administrators can enforce/change this policy. Ensure we log every time we delete an image and the reason why it was deleted.
related to https://github.com/goharbor/harbor/issues/6654

When we evaluate retention policies, we need to make sure we have logging that illustrates which policies apply when we delete an image.

**Comment by michmike** [comment]
Nate's write is at https://gist.github.com/nlowe/ee8172fcfbdf301cb09a8ce97089536c

**Comment by steven-zou** [comment]
Tracked in the EPIC https://github.com/goharbor/harbor/issues/6654

**Comment by steven-zou** [comment]
As is a requirement, transfer it to @xaleeks for tracking.

**Comment by reasonerjt** [comment]
Closing as we commit this is part of 1.9 tracked via #6654
