### ISSUE TITLE
Support white list in CVE 

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#7942]
1. Allow you define a global list of CVEs that can be whitelisted (ignored) across all projects
2. On a per project, you can either inherit the global whitelist of CVEs (default option), or you can define your own for this specific project
3. Policy to disable pulling of images that have not had a clean scan by Clair yet (per project policy) -> already supported. 

Any time a CVE is ignored due to a whitelist, we need to make sure we log it in the logs. This should happen at scan time and at image pull time to indicate that both a CVE was discovered but also an image was allowed to be pulled even though it had a CVE because the CVE was in the whitelist

Related items:
https://github.com/goharbor/harbor/issues/6887
https://github.com/goharbor/harbor/issues/6999

**Comment by reasonerjt** [comment]
Closing this epic as all planned work is done.
