### ISSUE TITLE
for pushing signed image where is the config of passphrase for root key

### ISSUE THREAD

**Issue by gnavgire** [goharbor/harbor#7947]
What can we help you?
I am using Harbor 1.8.0 , after enabling content trust env variables, the signed image push is asking for "passphrase for root key".  No passwords from the harbor.yml file is acknowledged for the same. Where can i get the passphrase for the root key ?

**Comment by wy65701436** [comment]
Please refer the notary doc, you have to input the rootkey in the console, harbor doesn't hold this.
