### ISSUE TITLE
Admin users should be allowed to override deployment security policy

### ISSUE THREAD

**Issue by jtackaberry** [goharbor/harbor#7949]
Currently admin users can't pull images if they violate the Deployment Security policy ("prevent images with vulnerability severity of X and above from being deployed").  There should be some mechanism (either a system setting or a default behavior) to allow admin users to pull any image.

Our use-case is integrating a third party container security tool such as Aqua or Twistlock with Harbor.  We still want to prevent non-admin users from being able to pull insecure images, but also want them to be scanned by the third party tool.

**Comment by reasonerjt** [comment]
I understand the problem you are seeing.
We are working on to allow Harbor integrate 3rd party scanner, we'll provide a solution in that effort.

https://github.com/goharbor/community/pull/90

**Comment by xaleeks** [comment]
You can use CVE whitelist to pull images violating any deployment policy around CVEs.  Aqua (and any other scanner really) is now also supported through out pluggable interrogation services framework.  Feel free to ping me if I'm misunderstanding or you need something else beyond what we have now
