### ISSUE TITLE
Container naming with docker-compose.yml, possible conflicting names in redis/nginx

### ISSUE THREAD

**Issue by titpetric** [goharbor/harbor#7958]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

All containers should be prefixed with `harbor` and/or not set `container_name`.

When installing the standalone release, the docker-compose has `container_name` filled out for all services. All services are already reachable by the friendly service name, and extra container_name settings are undesirable, especially when naming containers just `redis` or `nginx`. While I didn't have a conflict, it is bad practice to do it like that, especially considering that harbor might not be running alone on the docker host.

**Comment by reasonerjt** [comment]
I don't think it's a very high priority I don't think most users run another nginx on the docker host of Harbor and it's easy to workaround

**Comment by titpetric** [comment]
Also an easy fix: remove “container_name” settings from docker compose and done. You shouldn’t have to chose between good practice and low priority

**Comment by reasonerjt** [comment]
@titpetric 
Please update the docker-compose.yml to workaround this.
Changing the container name is potentially a break change.
For example user may write a script referencing the container name.

**Comment by wilinz** [comment]
use shell script
```shell
#!/bin/bash

if [ ! -f docker-compose.yml ]; then
  echo "docker-compose.yml file not found! "
  exit 1
fi

temp_file=$(mktemp)

while IFS= read -r line; do
  if [[ $line =~ ^([[:space:]]*container_name:[[:space:]]*)\"?(.*)\"?$ ]]; then
    indent=${BASH_REMATCH[1]}
    container_name=${BASH_REMATCH[2]}
    if [[ $container_name != harbor-* ]]; then
      line="${indent}\"harbor-${container_name}\""
    fi
  fi
  echo "$line" >> "$temp_file"
done < docker-compose.yml

mv docker-compose.yml docker-compose.yml.bak
mv "$temp_file" docker-compose.yml

echo "Rename successfully! backup file: docker-compose.yml.bak"
```
