### ISSUE TITLE
list projects api is not working | 500 && giving garbage response 

### ISSUE THREAD

**Issue by bansalrajat** [goharbor/harbor#7959]
What can we help you?

I am receiving 500 Error and Garbage response when i am trying to  get the project list from "/ai/projects" . 
This is happening from devcenter as well as browser and command line . 

![image](https://user-images.githubusercontent.com/8680661/59755295-97652180-927f-11e9-84b3-23fbeea1c893.png)

**Comment by lmdkfs** [comment]
i had the same problem

**Comment by lmdkfs** [comment]
i had the same problem

**Comment by bansalrajat** [comment]
yeah..i have used that .thanks .
