### ISSUE TITLE
Projects are missing from ui after migration from v1.6.1 to v1.8.0 

### ISSUE THREAD

**Issue by bansalrajat** [goharbor/harbor#7962]
What can we help you?
Projects are missing from UI after migration from v1.6.1 to v1.8.0.

Jun  3 10:53:08 172.23.0.1 core[1310]: 2019-06-03T09:53:08Z [ERROR] [/core/api/project.go:440]: Failed to get total of charts under project apiconnect: http error: code 404, message not found
Jun  3 10:53:08 172.23.0.1 core[1310]: 2019-06-03T09:53:08Z [ERROR] [/common/api/base.go:229]:
Jun  3 10:53:08 172.23.0.1 core[1310]: 2019-06-03T09:53:08Z [ERROR] [/common/api/base.go:69]: GET /api/projects/28 failed with error: {"code":500,"message":"Internal Server Error"}

**Comment by bansalrajat** [comment]
any update on it ..I am getting below error in core.log
Jun  4 21:39:21 172.23.0.1 core[1310]: 2019/06/04 20:39:21 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|     953.36µs|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/core/api/project.go:440]: Failed to get total of charts under project apie: http error: code 404, message not found
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/common/api/base.go:229]:
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/common/api/base.go:69]: GET /api/projects?page=3&page_size=15 failed with error: {"code":500,"message":"Internal Server Error"}
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/core/api/project.go:440]: Failed to get total of charts under project apiconnect: http error: code 404, message not found
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/common/api/base.go:229]:
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019-06-04T20:39:22Z [ERROR] [/common/api/base.go:69]: GET /api/projects?page=3&page_size=15 failed with error: {"code":500,"message":"Internal Server Error"}
Jun  4 21:39:22 172.23.0.1 core[1310]: 2019/06/04 20:39:22 #033[1;44m[D] [server.go:2619] |  172.16.155.35|#033[41m 500 #033[0m|  74.742867ms|   match|#033[44m GET

**Comment by wphe** [comment]
It's a known issue [https://github.com/goharbor/harbor/issues/7068](url)

**Comment by wy65701436** [comment]
@bansalrajat can you please provide the full log?

**Comment by bansalrajat** [comment]
Issue is resolved now after using the latest release.
