### ISSUE TITLE
pull/push from harbor with "too many connections" error

### ISSUE THREAD

**Issue by lethe3000** [goharbor/harbor#7963]
We have a CI server and runs parallel docker pull/push operations.
when the number of parallel operations is sometimes big, docker cli will report errors like
```
Error response from daemon: pull access denied for xxx.com/compile/maven, repository does not exist or may require 'docker login'

Error response from daemon: Get https://xxx.com/v2/compile/maven/manifests/3-jdk-8: received unexpected HTTP status: 500 Internal Server Error
```

and harbor log as below:
```
registry.log: Jun  3 17:52:28 172.18.0.1 registry[1781]: time="2019-06-03T09:52:28.03314396Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host=xxx.com http.request.id=4be42441-af32-49a1-8d35-03430de8048a http.request.method=GET http.request.remoteaddr=10.6.1.35 http.request.uri="/v2/" http.request.useragent="docker/17.09.0-ce go/go1.8.3 git-commit/afdb6d4 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.0-ce \\(linux\\))" instance.id=205f05dc-4b99-4890-8058-9e7d58182991 service=registry version=v2.6.2
ui.log:Jun  3 17:52:28 172.18.0.1 ui[1781]: 2019-06-03T09:52:28Z [ERROR] [token.go:48]: Unexpected error when creating the token, error: Error 1040: Too many connections
ui.log:Jun  3 17:52:28 172.18.0.1 ui[1781]: 2019-06-03T09:52:28Z [ERROR] [token.go:48]: Unexpected error when creating the token, error: Error 1040: Too many connections
```

docker version: `17.09.0-ce`
harbor version: `Version v1.7.1-c3806525`
harbor cfg(launch with docker-compose):
```
max_job_workers = 10
db_host = postgresql
```

So how to fix this issue, as I think "access denied" should not be reported.

**Comment by reasonerjt** [comment]
@lethe3000 
Could you let us know how many parallel commands are run when you encounter this error?
My current guess is that this error may be from database.

Please package all log files and attach to the issue, so we can correlate the error.

**Comment by lethe3000** [comment]
> @lethe3000
> Could you let us know how many parallel commands are run when you encounter this error?
> My current guess is that this error may be from database.
> 
> Please package all log files and attach to the issue, so we can correlate the error.

the number of parallel commands running on production CI server may be around `10`.
and I'll collect logs later for you, thank you.

**Comment by reasonerjt** [comment]
@heww 
I don't think 10 concurrent connections will cause such problem?
