### ISSUE TITLE
harbor 1.8 often can't login use docker login

### ISSUE THREAD

**Issue by ilanni2460** [goharbor/harbor#7966]
narbor upgrde 1.8 afer，harbor 1.8 often can't login use docker login。

if restart harbor，it work。but the next day harbor Still can't login

**Comment by ywk253100** [comment]
Provide the logs of `core` and `registry` when you cannot login via docker client.

**Comment by ilanni2460** [comment]
@ywk253100 ok
this is core.log:

Jun  5 14:43:30 172.22.0.1 core[11921]: 2019-06-05T06:43:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
Jun  5 14:43:30 172.22.0.1 core[11921]: 2019/06/05 06:43:30 #033[1;44m[D] [server.go:2619] |  192.168.0.109|#033[42m 200 #033[0m|  49.489266ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Jun  5 14:43:30 172.22.0.1 core[11921]: 2019/06/05 06:43:30 #033[1;44m[D] [server.go:2619] |  192.168.0.109|#033[42m 200 #033[0m|   2.900851ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Jun  5 14:43:32 172.22.0.1 core[11921]: 2019/06/05 06:43:32 #033[1;44m[D] [server.go:2619] |  192.168.0.109|#033[43m 401 #033[0m|   2.596803ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m


i use ldap for auth. this is  ldap config:

https://ws3.sinaimg.cn/large/005BYqpgly1g3qopzaxelj30gh0i7t9z.jpg

**Comment by ilanni2460** [comment]
I have solved this problem and it is caused by our ldap server dns parsing.

@ywk253100 tks
