### ISSUE TITLE
Robot account : cannot authenticate via token when using LDAP authentication

### ISSUE THREAD

**Issue by sbressey** [goharbor/harbor#7969]
It is not possible to login via robot account token when LDAP authentication is enabled.
I get the following error in core.log : 

`
[/core/auth/ldap/ldap.go:70]: Not found an entry.
[ERROR] [/core/filter/security.go:471]: failed to authenticate xxx: Failed to authenticate user, due to error 'Not found an entry'
`

I think it would be very useful to be able to use both robot token authentication and LDAP authentication, for CI/CD jobs for example.

**Comment by reasonerjt** [comment]
Hi,

robot account is designed to work when auth backend is set to LDAP.

Please refer to #7944 make sure the username and password are referenced correctly in your command

**Comment by sbressey** [comment]
Hi, 

Indeed, it works when qutoting username and password in the one line command.
Thank you for your help.

Might be a good idea to update the documentation and give an example of a one line command with quotes ?

**Comment by wToad** [comment]
Hi,

When you have a `$` symbol in a command-line and you're working a bit with any shells, you suppose to know it should be with quotes not to interpret it as an environment variable.
