### ISSUE TITLE
Support replication between Harbor and ECR(Amazon Elastic Container Registry) 

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7977]

**Comment by bitsf** [comment]
https://github.com/goharbor/harbor/pull/7915

**Comment by ywk253100** [comment]
Done

**Comment by tvvignesh** [comment]
@ywk253100 May I know when this would be available as a release? Looking to use this feature. Thanks in advance.

Or is it possible to build harbor from source?

**Comment by ywk253100** [comment]
It is available in Harbor 1.9 which will released at early of Sep if everything goes well

**Comment by tolleiv** [comment]
As this seems to be the entrypoint for related Google Searches. Here's the deeplink into the documentation for the feature released with Harbor 1.9: https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#replicating-resources for details
