### ISSUE TITLE
Support replication between Harbor and ACR(Azure Container Registry)

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#7978]

**Comment by s-spindler** [comment]
I would very much like to see this. Is any work being done on this already?

**Comment by mumrau** [comment]
I am wondering whether ACR is that different from a "normal" v2 docker registry?
I tried the feature and got fairly disappointed in the end, the log finishing on an error code...which is... 200.

**Comment by cd1989** [comment]
Auth of ACR is different from normal v2 docker registry. By normal registry, /v2 requests always got 401 without token, but with ACR, if basic auth provided, /v2 requests will work fine.

Replication of Harbor relies on 401 status code to get token.

**Comment by ywk253100** [comment]
Done
