### ISSUE TITLE
LDAP user can see assigned projects but cannot navigate to them

### ISSUE THREAD

**Issue by drleq** [goharbor/harbor#7984]
**Expected behavior**
LDAP users can be assigned to a project, allowing them to see the project in the main page and to see repositories it contains.

**Actual behavior:**
LDAP user is assigned to a project, can see the project in the main page but receives a `403 Forbidden` when navigating to the project page itself.

**Steps to reproduce the problem:**
1. Install Harbor from clean, including Notary and Clair (overview of config below)
1. Login as default admin/Harbor12345.  Change password
1. Go to Administration -> Configuration -> Authentication
1. Change Auth Mode to LDAP
1. Fill in details to allow user lookup (overview of config below)
1. Save LDAP configuration and use Test LDAP Server to verify
1. Create private project and add LDAP UserX as Project Admin
1. Open Chrome in incognito mode and log in as LDAP UserX
1. Observe that login is successful and private project is listed in main view
1. Click the private project to try and navigate to it

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0]
- docker engine version: [18.09.6]
- docker-compose version: [1.18.0]

**Additional context:**
harbor.yml changes:
- Set hostname
- Set HTTP port to 7080
- Set HTTPS port to 7443
- Use self-signed certificates for HTTPS
- Set database password
- Set data_volume to be an NFS share
- All over fields are at their default values

LDAP config:
- Set LDAP URL and Base DN
- LDAP UID is left as `cn`
- Provided LDAP Search DN and Password
- All other fields are at their default values

Output from core.log:
`Jun  5 17:58:08 172.18.0.1 core[7060]: 2019-06-05T16:58:08Z [WARNING] [/core/api/projectmember.go:80]: Failed to get pmid from path, error strconv.ParseInt: parsing "": invalid syntax
Jun  5 17:58:08 172.18.0.1 core[7060]: 2019-06-05T16:58:08Z [ERROR] [/common/api/base.go:69]: GET /api/projects/2/members failed with error: {"code":403,"message":"Condie, Andrew"}
Jun  5 17:58:08 172.18.0.1 core[7060]: 2019/06/05 16:58:08 #033[1;44m[D] [server.go:2619] |   10.105.11.63|#033[43m 403 #033[0m|   5.937137ms|   match|#033[44m GET     #033[0m /api/projects/2/members   r:/api/projects/:pid([0-9]+)/members/?:pmid([0-9]+)#033[0m
Jun  5 17:58:08 172.18.0.1 core[7060]: 2019-06-05T16:58:08Z [ERROR] [/common/api/base.go:69]: GET /api/projects/2 failed with error: {"code":403,"message":"Condie, Andrew"}
Jun  5 17:58:08 172.18.0.1 core[7060]: 2019/06/05 16:58:08 #033[1;44m[D] [server.go:2619] |   10.105.11.63|#033[43m 403 #033[0m|   5.486064ms|   match|#033[44m GET     #033[0m /api/projects/2   r:/api/projects/:id([0-9]+)#033[0m`

**Comment by reasonerjt** [comment]
@drleq 
Is it only reproducible in `incognito mode` ?

**Comment by drleq** [comment]
> @drleq
> Is it only reproducible in `incognito mode` ?

@reasonerjt No, this happens without incognito mode as well.  I only use it to ensure there are no cookies hanging around.

I've attached two screenshots of the problem as seen from the Harbor main page.  Clicking the `andy_private` project results in the two 403 errors in the network log.  The second image is the return from the swagger `/users/current/permissions` end-point, which returns an empty array.

![harbor_project_403](https://user-images.githubusercontent.com/46029766/59020372-c1f7b900-8841-11e9-83d5-80ca91e290cd.png)
![harbor_swagger_user_permissions](https://user-images.githubusercontent.com/46029766/59020379-c623d680-8841-11e9-89b4-c519902c7854.png)

**Comment by heww** [comment]
@drleq can you provide the `/users/current/permissions` response which use `scope=/project/3`?

**Comment by drleq** [comment]
@heww Sorry, I misunderstood the scope.  The project id is 2 and the user id is 3.  The current users permissions for `/project/2` still returns an empty array.

*Further details*
We have discovered that switching LDAP authentication to use `samaccountname` instead of `cn` does not cause this issue.  This could be related to how our `cn` names are structured, e.g. `<surname>, <first name>`.  The log in itself works but subsequent operations fail.  The `samaccountname` is a simple lowercase word.

With the `samaccountname` the current user permissions for `/project/1` and `/project/2` return correctly.
