### ISSUE TITLE
[FEATURE REQUEST] Proxy Pulling From External Registry Behavior

### ISSUE THREAD

**Issue by kacole2** [goharbor/harbor#7987]
**Is your feature request related to a problem? Please describe.**
This is not a problem but is a feature request that extends on the idea of #7986 

Today, the native docker client defaults pulling containers from DockerHub. In Kubernetes instances there is also the gcr.io registry that is called out using the FQDN when specifying the container. For example: `image: k8s.gcr.io/echoserver:1.4`. If there was an image that needed to pull from Harbor it would look like `image: demo.goharbor.io/library/nginx:latest`

If the default registry is pointed to Harbor (instead of DockerHub), and Harbor doesn't have that image or an image with a specific tag, Harbor should go fetch the image from DockerHub. 

Once Harbor fetches the image from DockerHub it will be added to the default project `library`. The image will now follow the policy set on the Project. For instance, if the Project is set to scan for vulnerabilities on push then Harbor will scan that image before it's returned to the user.

In this instance, if the scan comes back clean and passes the policies set on the Project, the user or system that invoked the pull will be returned with the image layer as usual. If it doesn't pass the policies set then it returns an error message explaining what failed. 

**Describe the solution you'd like**
To summarize:
  1. the docker client or Kubernetes system is set to use Harbor as the default registry. 
  2. the docker client or Kubernetes system will request an image like `docker pull nginx`
  3. If Harbor does not have the `nginx:latest` image, it will pull that image from DockerHub.
  4. Once the pull is complete, the image will have to pass the policies set by the Project configuration like scan for vulnerabilities on push.
  5. If image passes policy, it will return the layers back to the requesting client
  6. If image does not pass, it will return error message explaining what failed
  7. Harbor will now have an option to configure replication and syncing of the image to DockerHub. 

**Describe the main design/architecture of your solution**
None

**Describe the development plan you've considered**
None. Suggesting a Feature

**Additional context**
None

**Comment by xaleeks** [comment]
delivered in our Proxy Cache Feature in v2.1
