### ISSUE TITLE
Intermittent 502 Bad Gateway in Nginx pods with requests made to the `/v2/` endpoint

### ISSUE THREAD

**Issue by burdzwastaken** [goharbor/harbor#7989]
**Expected behavior and actual behavior:**
Actual: Our deployment tool makes requests to the `/v2/` to determine if the registry supports it. We are seeing intermittent failures to this route which results in a Bad Gateway from Nginx. The chain of calls as a result of the failure is harbor-nginx -> harbor-core -> harbor-registry; in failure cases, the error message above is visible in the harbor-core pod logs:
```
2019/04/24 00:48:31 http: proxy error: dial tcp: lookup harbor-registry on 10.244.51.1:53: dial udp 10.244.51.1:53: operation was canceled
```

Expected: Handle all requests to the `/v2/` endpoint

**Steps to reproduce the problem:**
We have written this tool to reproduce the issue: https://github.com/mulesoft-labs/harbor-error-repro

example:
```
# run without issue
$ go run main.go https://harbor.domain.com 100
running 100 pings to https://harbor.domain.com
5 done
10 done
15 done
20 done
25 done
30 done
35 done
40 done
45 done
50 done
55 done
60 done
65 done
70 done
75 done
80 done
85 done
90 done
95 done
100 done
ALL GOOD
# run with issue
$ go run main.go https://harbor.domain.com 100
running 100 pings to https://harbor.domain.com
5 done
10 done
15 done
20 done
25 done
unexpected code 502; body: ""
unexpected code 502; body: ""
unexpected code 502; body: ""
unexpected code 502; body: ""
30 done
unexpected code 502; body: ""
unexpected code 502; body: ""
35 done
40 done
unexpected code 502; body: ""
45 done
50 done
unexpected code 502; body: ""
unexpected code 502; body: ""
55 done
unexpected code 502; body: ""
60 done
65 done
unexpected code 502; body: ""
70 done
75 done
80 done
85 done
90 done
95 done
100 done
exit status 1
```

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.7.5
- docker engine version: [18.06.2-ce]
- kubernetes version: [1.13.4]

**Additional context:**
We are deploying Harbor through [harbor-helm](https://github.com/goharbor/harbor-helm/tree/1.0.0). Harbor is deployed behind an ELB within AWS terminating SSL. Additional logs and configuration can be supplied from our setup if required.

**Comment by reasonerjt** [comment]
That failure looks like due to connection issue to the DNS?

**Comment by burdzwastaken** [comment]
our CoreDNS logs show no errors while performing the internal DNS lookups. while I don't think we can rule out it being DNS issue the error we are getting getting isn't necessarily a DNS error, it's a context cancelled error that occurs while it's doing DNS lookup. I will do a packet capture on the flannel interface to confirm that it is not a bug within our setup.

**Comment by bitsf** [comment]
the DNS request should not be throw to 10.244.51.1 which I think is an external DNS server, it should use docker inner dns service. Maybe your CoreDNS is something conflict with the internal DNS, you can try disable it and test whether it can reproduce

**Comment by burdzwastaken** [comment]
@bitsf thanks for the update, I will definitely give this a go and report back here.

**Comment by reasonerjt** [comment]
@burdzwastaken any update?

**Comment by burdzwastaken** [comment]
@reasonerjt @bitsf Sorry for the late response. After doing some investigating our current version for of Kubernetes (we work with gravitational) in this current release runs coredns on the host as a systemd service. 10.244.51.1 is within the docker0 network. 

```
ip-kube:/$ ip a show docker0
3: docker0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:2e:44:44:65 brd ff:ff:ff:ff:ff:ff
    inet 10.244.95.1/24 brd 10.244.95.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2eff:fe44:4465/64 scope link 
       valid_lft forever preferred_lft forever
```

here is our coredns configuration
```
import /etc/coredns/configmaps/*

.:53 {
  reload
  bind 127.0.0.2
  errors
  hosts /etc/coredns/coredns.hosts {
    fallthrough
  }
  kubernetes cluster.local in-addr.arpa ip6.arpa {
    endpoint https://leader.local:6443
    tls /var/state/coredns.cert /var/state/coredns.key /var/state/root.cert
    pods verified
    fallthrough in-addr.arpa ip6.arpa
  }
  forward . 10.97.0.2 {
    policy sequential
    health_check 0
  }
}
```

In the following releases they are running it in a pod.

**Comment by burdzwastaken** [comment]
We are no longer seeing this issue in the latest release. Thank you for your time.
