### ISSUE TITLE
Auth_mode menu disabled

### ISSUE THREAD

**Issue by DemenkovK** [goharbor/harbor#7992]
Hello! I need to change auth_mode to LDAP, but somewhy menu is inactive. I use admin account, ofcause. What can i do to solve my issue?

**Comment by DoctahPopp871** [comment]
I am having a similar issue. Looking to change auth mode from built in database to OIDC. I understand that you can only change auth mode when the only user present is Admin. I removed all previously created users, but the Auth_Mode value is still greyed out. 

What do I need to do in order to change my auth mode ? Do I need to re-install with a new user-database ?

**Comment by stonezdj** [comment]
You can clean the user created in database and try again.
```
docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user
delete from harbor_user where user_id = xxx 
```
Then change the configuration in web console.

**Comment by DoctahPopp871** [comment]
Removed all users from web console. Let me check the DB, thanks.

**Comment by DemenkovK** [comment]
> 
> 
> How did you remove all users? You can clean users created in database and try again.
> 
> ```
> docker exec -it harbor-db bash
> psql -U postgres
> \c registry
> select * from harbor_user
> delete from harbor_user where user_id = xxx 
> ```
> 
> Then change the configuration in web console.

It works! Can you advice, how can i troubleshoot connection string to ldap? There is no any useful messages in harbor log-directory, ldap test connection success, but i still cant you ldap-auth. Which harbor container make ldap connection for auth?

**Comment by DemenkovK** [comment]
Answer to my own question:
1. Set debug level to debug in harbor.yml and reinstall harbor with new param.
2. Look into core.log. There i have found incorrect ldap request, then change "LDAP Filter" and "LDAP UID" values and it's work now.

**Comment by DoctahPopp871** [comment]
@stonezdj I removed all users except admin directly from the db. ( there were some users there not present in the ui), but am still unable to change the auth setting from both the UI and API. 

attempt to set the auth_mode to editable from API :
`curl -X PUT "https://harbor.ogilvy-digital.com/api/configurations" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"auth_mode\": { \"value\": \"db_auth\", \"editable\": true }}"`

Returns:
`{"code":400,"message":"auth_mode can not be modified as new users have been inserted into database"}`

I only have 1 user in my user databae (Admin)

`curl -X GET "https://harbor.ogilvy-digital.com/api/users/current" -H "accept: application/json"
`

{
  "user_id": 1,
  "username": "admin",
  "email": "admin@example.com",
  "password": "",
  "realname": "system admin",
  "comment": "admin user",
  "deleted": false,
  "role_name": "",
  "role_id": 0,
  "has_admin_role": true,
  "reset_uuid": "",
  "creation_time": "2019-05-16T05:04:36.229076Z",
  "update_time": "2019-05-16T05:04:36.954239Z"
}

**Comment by stonezdj** [comment]
You might removed the anonymous user, try to add it
```
insert into harbor_user (username, email, password, realname, comment, deleted, sysadmin_flag, creation_time, update_time) values 
('anonymous', 'anonymous@example.com', '', 'anonymous user', 'anonymous user', true, false, NOW(), NOW());
```

**Comment by DoctahPopp871** [comment]
The anonymous user did the trick, thanks!
