### ISSUE TITLE
How to configure LDAP in harbor.yml

### ISSUE THREAD

**Issue by jahentao** [goharbor/harbor#7999]
reference [manage_role_by_ldap_group.md](https://github.com/goharbor/harbor/blob/76e0b40b71d1e645be977c52dc90a29a62598f28/docs/manage_role_by_ldap_group.md) is out-of-date.

**Comment by stonezdj** [comment]
Please refer the document: https://github.com/goharbor/harbor/blob/master/docs/configure_user_settings.md

**Comment by stonezdj** [comment]
Document added

**Comment by lazzio7** [comment]
good morning,,

link : https://github.com/goharbor/harbor/blob/master/docs/1.10/index.md.

points to: 404 not found... 

any hint?

thanks ;)

**Comment by mephmanx** [comment]
Is there a way to setup LDAP auth in harbor.yml so that it is configured at startup?
