### ISSUE TITLE
The response time is too long for /api/repositories?project_id=21

### ISSUE THREAD

**Issue by yehaifeng** [goharbor/harbor#8000]
I want get some from https://harbor.test.com/api/repositories?project_id=21, but it use 9s for response. Is there any way to optimize it?

The ui log:
Jun 10 10:30:57 172.18.0.1 ui[1393283]: 2019/06/10 02:30:57 #033[1;44m[D] [server.go:2619] |    10.11.66.12|#033[42m 200 #033[0m| **9.390258381s**|   match|#033[44m GET     #033[0m /api/repositories   r:/api/repositories#033[0m
Jun 10 10:30:57 172.18.0.1 ui[1393283]: 2019/06/10 02:30:57 #033[1;44m[D] [server.go:2619] |    10.11.66.12|#033[42m 200 #033[0m|171.026µs|   match|#033[44m GET     #033[0m /favicon.ico#033[0m

**Comment by yehaifeng** [comment]
Version _version = 1.5.0

**Comment by stonezdj** [comment]
The latest version 1.8.0, the backend database already switched from mysql to postgresql, could you please verify the issue in latest version (1.8.0)

**Comment by reasonerjt** [comment]
@heww let's run some test against latest build and figure out the bottle neck.
