### ISSUE TITLE
Save option unavailable for Replication Rule if only one Registry endpoint is defined

### ISSUE THREAD

**Issue by phenixblue** [goharbor/harbor#8004]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The save option is unavailable when trying to create a replication rule and I only have one Registry endpoint configured for Harbor. The save button should be available if all required fields are completed.

**Steps to reproduce the problem:**
- Install 2 instances (harbor1 and harbor2) of Harbor 1.8.0 via Helm
- Define `harbor2` as registry endpoint on `harbor1`
- Try and add replication rule for push or pull on `harbor1`
- Save option is unavailable

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.0
- docker engine version: 18.6.3
- docker-compose version: NA

**Additional context:**

- kubernetes version: 1.12.7

I did notice that adding a second registry endpoint (even the local harbor instance itself), and toggling between the 2 registry endpoints in the replication rule window would allow the save button to be available

**Comment by reasonerjt** [comment]
@jwangyangls Could you check if this is reproducible?

**Comment by AllForNothing** [comment]
@phenixblue  This is the same issue with #7829.  Fixed in 1.8.2 and subsequent version.
