### ISSUE TITLE
v1.8.0使用nginx代理harbor

### ISSUE THREAD

**Issue by deqyiyt** [goharbor/harbor#8005]
What can we help you?
harbor的nginx端口配置为2280
使用自建的nginx代理2280，并且用域名转发
出现问题：
使用域名访问无法创建项目，提示：项目名称已存在
使用ip:2280访问，创建项目成功

**Comment by ninjadq** [comment]
hi @deqyiyt did you configured the external URL in your `harbor.yml`

**Comment by bitsf** [comment]
是不是域名指向错误了，跑到其他harbor上了，否则也不该报已存在

**Comment by guoliangdi** [comment]
@deqyiyt ,我也遇到同样的问题。升级了1.8.2-rc版还是会出现这个问题。
不知道你解决了没有？

**Comment by guoliangdi** [comment]
ip + port 访问是可以的。域名就不行。就提示：项目名称已存在。

而且不是@bitsf说的那样。跑到其它harbor服务上了。因为你写什么名字都提示。

**Comment by bitsf** [comment]
@guoliangdi ip + port 访问正常，证明harbor 自身没有问题，使用自建域名时却报错，这个看起来还是域名解析相关的问题。
你可以先看看 /var/log/harbor 中的日志，比如 proxy.log 中是否有对应的请求
看看是否有其他的发现

**Comment by ninjadq** [comment]
@guoliangdi you should try set the external_url in `harbor.yml`

**Comment by FreeLoopC** [comment]
外部nginx默认会将head请求转换为get再发送到harbor的nginx中, 导致harbor一直返回200状态码

harbor根据200状态码认为项目存在, 所以不管输入什么总是提示项目已经存在了

解决办法: 外部nginx添加proxy_cache_convert_head off;

禁用head请求自动转换之后,  harbor就可以正常添加项目了
