### ISSUE TITLE
Scalability of Harbor

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8007]
[] 500 projects
[] 20 users per project
[] 200 images per project (100,000 images under management)
[] 50 concurrent pulls/push per node
[] 50 concurrent replications
[] 50 concurrent image scans

**Comment by reasonerjt** [comment]
We should create re-usable code and infrastructure for perf testing.

After that provide a report and try to fix blocking issues in 1.9 timeframe.

**Comment by reasonerjt** [comment]
We have verified the criterias in OP but let's leave it open for more metrics.
