### ISSUE TITLE
sysLog endpoint for log shipping

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8008]
requirements
* Syslog endpoint
* date format in logs conforms to RFC 3339 as well as RFC 5424 and ISO 8601. (example 2019-01-16T17:08:08.909Z in UTC time)

We need to test with fluentbit and vmware log insight for compatibility

**Comment by ninjadq** [comment]
code merged in #8301

**Comment by michmike** [comment]
Great work!!
