### ISSUE TITLE
core doesn't have idle timeout set for redis connection pool

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#8011]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Beego version used by harbor core doesn't have idle timeout set for redis connection pool. It uses a deprecated method to create the pool.

```
// NewPool creates a new pool.
//
// Deprecated: Initialize the Pool directory as shown in the example.
func NewPool(newFn func() (Conn, error), maxIdle int) *Pool {
	return &Pool{Dial: newFn, MaxIdle: maxIdle}
}
```

The problem when idle timeout not set is:

When Redis service is served by a proxy like HAProxy that have read/write timeout set. For example, timeout set for HAProxy

```
defaults REDIS
    mode tcp
    log global
    timeout connect  4s
    timeout server  30s
    timeout client 30s
```

Connections in the connection pool will be closed by the proxy due to the timeout. If the connection pool itself has no idle timeout set, closed connection would be used and raise error.

The result is harbor session would be lost regularly, and guide user to re-authenticate. In portal, user need to re-login, with docker cli, retry may happen.

To solve this problem, to upgrade beego version is a good choice.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by cd1989** [comment]
A workaround for the problem is, configure your proxy (like HAProxy) to set a longer timeout. For example,

```
    defaults REDIS
    mode tcp
    timeout connect 3s
    timeout server 6h
    timeout client 6h
```

**Comment by reasonerjt** [comment]
We cannot upgrade beego in 1.10 as it's too close to GA.

**Comment by cd1989** [comment]
It's OK to upgrade in 1.11
