### ISSUE TITLE
Does harbor Support ARM Architecture?

### ISSUE THREAD

**Issue by YanLemon** [goharbor/harbor#8014]
What can we help you?

**Comment by stonezdj** [comment]
Not sure what is your requirement, if you need to install harbor on ARM arch OS, the current offline installer doesn't support this. you have to compile the source code and change all base images. if you just need to store ARM architecture images, it support to store ARM images.

**Comment by YanLemon** [comment]
thank you .      how to compile the source code? I want to intall harbor on ARM.

**Comment by YanLemon** [comment]
@stonezdj  thank you . how to compile the source code? I want to intall harbor on ARM.
