### ISSUE TITLE
when use oidc auth, which claim do you use?

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#8018]
Hi,

When I login with oidc, I can see my profile.
![image](https://user-images.githubusercontent.com/1247030/59282438-e8837d00-8ca3-11e9-9402-e4d6e75ea8c3.png)

I guess harbor only cares username, email, full name for now,
and I think username means id.
I am currently in the situation with same username and full name.

Which claim do you use for username and full name ? Please let me know.
email is fine.

Thanks.

**Comment by reasonerjt** [comment]
The full name in a use's profile is set based on `name` in the token claims.
And the username in a user's profile is set in the onboard dialog, and the default value is `name` in the token claims.

**Comment by Hokwang** [comment]
@reasonerjt Thanks for your reply.
Oh, you use same claim.
How about change it ? (to username or preferred_username, or whatever and let users know.)
Or please refer to #8017 , how about provide that admin can input claim for these values?

**Comment by reasonerjt** [comment]
@Hokwang 
Could you clarify which claim you think should be changed, and why?

**Comment by Hokwang** [comment]
@reasonerjt 
First of all,
Please check this,
I think
Username == user ID
First and last name == user name
is this right?

**Comment by Hokwang** [comment]
@reasonerjt 
I think there is not single correct answer.
But in Jenkins or other tool's case,
claim "name" for full name. (many cases show name for full name in my googling)
claim "username" for username(ID). (actually I am not sure)
I think you can select the claim name you want and then let users know.

**Comment by reasonerjt** [comment]
@Hokwang 
In the onboard process we always allow user to set his `username` the use of the claim `name` is just a default behavior.

As long as we allow user to update the username, I don't think we want to introduce setting like `claim_for_username` which may just confuse more users.

**Comment by Hokwang** [comment]
@reasonerjt 
Please think about this.
User can edit his/her information (full name, email, or whatever)(ok, now just two, full name and email) on harbor's profile page.
This means you save/store information in DB, 
I think you don't need to do that. Just getting from oidc every time,
or if you have db, update from oidc, you don't provide user edit function.

Anyway, now user who login first time should edit their full name because full name is same with their ID basically.
The improvement for this is "use other specific claim or let admin edit custom claim(jenkins case)".

Thanks.

**Comment by reasonerjt** [comment]
@Hokwang 
Please clarify does this PR fix your problem?

**Comment by Hokwang** [comment]
@reasonerjt Yes. many thanks for your effort!!

**Comment by reasonerjt** [comment]
Closing this issue as #9311 has been merged.
