### ISSUE TITLE
compile harbor-1.5.1 got stuck

### ISSUE THREAD

**Issue by ahnselina** [goharbor/harbor#8029]
execute"make package_offline GOBUILDIMAGE=golang:1.9.2 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.3.0"
"
....
npm info lifecycle harbor@1.3.0~prepare: harbor@1.3.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm info ok 
/entrypoint.sh: line 29:    17 Killed                  ./node_modules/.bin/ngc -p tsconfig-aot.json
"
then got stuck, how to deal with this issue ?

**Comment by ahnselina** [comment]
make package_offline GOBUILDIMAGE=golang:1.9.2 COMPILETAG=compile_golangimage CLARITYIMAGE=vmware/harbor-clarity-ui-builder:1.3.0
➜ No golang package in your enviroment. You should use golang docker image build binary.

Note: docker version: 18.03.0

Note: docker-compose version: 1.24.0
compiling binary for clarity ui...
Unable to find image 'vmware/harbor-clarity-ui-builder:1.3.0' locally
1.3.0: Pulling from vmware/harbor-clarity-ui-builder
5040bd298390: Pull complete
fce5728aad85: Pull complete
76610ec20bf5: Pull complete
9c1bc3c30371: Pull complete
33d67d70af20: Pull complete
1ddfaaf1b6a6: Pull complete
4edad2411bbf: Pull complete
a845ee4dc541: Pull complete
8e17e3658b62: Pull complete
642153e47e25: Pull complete
87e779b7c967: Pull complete
77ce4595e93c: Pull complete
8f2d48df50c5: Pull complete
52695ad6a670: Pull complete
cc6cc5add3d2: Pull complete
Digest: sha256:567e4d59496ace2fec6051fd5a2705a9033eab6e1d002c4c8ed12a4faaef4f67
Status: Downloaded newer image for vmware/harbor-clarity-ui-builder:1.3.0
{
    "name": "harbor",
    "version": "1.3.0",
    "description": "Harbor UI with Clarity",
    "angular-cli": {},
    "scripts": {
        "start": "ng serve --ssl 1 --ssl-key ssl/server.key --ssl-cert ssl/server.crt --host 0.0.0.0 --proxy-config proxy.config.json",
        "lint": "tslint \"src/**/*.ts\"",
        "test": "ng test --single-run",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor",
        "build": "ngc -p tsconfig-aot.json"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^4.3.0",
        "@angular/common": "^4.3.0",
        "@angular/compiler": "^4.3.0",
        "@angular/core": "^4.3.0",
        "@angular/forms": "^4.3.0",
        "@angular/http": "^4.3.0",
        "@angular/platform-browser": "^4.3.0",
        "@angular/platform-browser-dynamic": "^4.3.0",
        "@angular/router": "^4.3.0",
        "@ngx-translate/core": "^6.0.0",
        "@ngx-translate/http-loader": "0.0.3",
        "@types/jquery": "^2.0.41",
        "@webcomponents/custom-elements": "^1.0.0",
        "clarity-angular": "^0.10.27",
        "clarity-icons": "^0.10.27",
        "clarity-ui": "^0.10.27",
        "core-js": "^2.4.1",
        "harbor-ui": "0.6.99",
        "intl": "^1.2.5",
        "mutationobserver-shim": "^0.3.2",
        "ngx-cookie": "^1.0.0",
        "rxjs": "^5.0.1",
        "ts-helpers": "^1.1.1",
        "web-animations-js": "^2.2.1",
        "zone.js": "0.8.19"
    },
    "devDependencies": {
        "@angular/cli": "^1.0.0",
        "@angular/compiler-cli": "^4.3.0",
        "@types/core-js": "^0.9.34",
        "@types/jasmine": "~2.2.30",
        "@types/node": "^6.0.42",
        "bootstrap": "4.0.0-alpha.5",
        "codelyzer": "~2.0.0-beta.4",
        "enhanced-resolve": "^3.0.0",
        "jasmine-core": "2.4.1",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-mocha-reporter": "^2.2.1",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "4.0.9",
        "rollup": "^0.41.6",
        "rollup-plugin-commonjs": "^8.0.2",
        "rollup-plugin-node-resolve": "^3.0.0",
        "rollup-plugin-uglify": "^1.0.1",
        "ts-node": "1.2.1",
        "tslint": "^4.1.1",
        "typescript": "~2.2.0",
        "typings": "^1.4.0",
        "webdriver-manager": "10.2.5"
    }
}
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.5.0
npm info attempt registry request try #1 at 3:44:53 PM
npm http request GET https://registry.npmjs.org/clarity-icons
npm info attempt registry request try #1 at 3:44:53 PM
npm http request GET https://registry.npmjs.org/clarity-angular
npm info attempt registry request try #1 at 3:44:53 PM
npm http request GET https://registry.npmjs.org/clarity-ui
npm info attempt registry request try #1 at 3:44:53 PM
npm http request GET https://registry.npmjs.org/harbor-ui
npm http 200 https://registry.npmjs.org/clarity-angular
npm http 200 https://registry.npmjs.org/clarity-icons
npm http 200 https://registry.npmjs.org/clarity-ui
npm info addNameTag [ 'clarity-angular', 'latest' ]
npm WARN deprecated clarity-angular@0.10.28: clarity-angular has moved to scope packages under @clr/angular
npm info retry fetch attempt 1 at 3:44:54 PM
npm info attempt registry request try #1 at 3:44:54 PM
npm http fetch GET https://registry.npmjs.org/clarity-angular/-/clarity-angular-0.10.28.tgz
npm info addNameTag [ 'clarity-icons', 'latest' ]
npm WARN deprecated clarity-icons@0.10.28: clarity-angular has moved to scope packages under @clr/icons
npm info retry fetch attempt 1 at 3:44:54 PM
npm info attempt registry request try #1 at 3:44:54 PM
npm http fetch GET https://registry.npmjs.org/clarity-icons/-/clarity-icons-0.10.28.tgz
npm info addNameTag [ 'clarity-ui', 'latest' ]
npm WARN deprecated clarity-ui@0.10.28: clarity-angular has moved to scope packages under @clr/ui
npm info retry fetch attempt 1 at 3:44:54 PM
npm info attempt registry request try #1 at 3:44:54 PM
npm http fetch GET https://registry.npmjs.org/clarity-ui/-/clarity-ui-0.10.28.tgz
npm http fetch 200 https://registry.npmjs.org/clarity-icons/-/clarity-icons-0.10.28.tgz
npm http fetch 200 https://registry.npmjs.org/clarity-ui/-/clarity-ui-0.10.28.tgz
npm http fetch 200 https://registry.npmjs.org/clarity-angular/-/clarity-angular-0.10.28.tgz
npm http 200 https://registry.npmjs.org/harbor-ui
npm info retry fetch attempt 1 at 3:44:55 PM
npm info attempt registry request try #1 at 3:44:55 PM
npm http fetch GET https://registry.npmjs.org/harbor-ui/-/harbor-ui-0.6.99.tgz
npm http fetch 200 https://registry.npmjs.org/harbor-ui/-/harbor-ui-0.6.99.tgz
npm info attempt registry request try #1 at 3:44:57 PM
npm http request GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/fsevents
npm info lifecycle harbor@1.3.0~preinstall: harbor@1.3.0
npm info lifecycle clarity-angular@0.10.28~preinstall: clarity-angular@0.10.28
npm info lifecycle clarity-icons@0.10.28~preinstall: clarity-icons@0.10.28
npm info lifecycle clarity-ui@0.10.28~preinstall: clarity-ui@0.10.28
npm info lifecycle harbor-ui@0.6.99~preinstall: harbor-ui@0.6.99
npm info lifecycle harbor-ui@0.6.6-dev.0~preuninstall: harbor-ui@0.6.6-dev.0
npm info lifecycle harbor-ui@0.6.6-dev.0~uninstall: harbor-ui@0.6.6-dev.0
npm info lifecycle harbor-ui@0.6.6-dev.0~postuninstall: harbor-ui@0.6.6-dev.0
npm info lifecycle clarity-ui@0.10.20~preuninstall: clarity-ui@0.10.20
npm info lifecycle clarity-ui@0.10.20~uninstall: clarity-ui@0.10.20
npm info lifecycle clarity-ui@0.10.20~postuninstall: clarity-ui@0.10.20
npm info lifecycle clarity-icons@0.10.20~preuninstall: clarity-icons@0.10.20
npm info lifecycle clarity-icons@0.10.20~uninstall: clarity-icons@0.10.20
npm info lifecycle clarity-icons@0.10.20~postuninstall: clarity-icons@0.10.20
npm info lifecycle clarity-angular@0.10.20~preuninstall: clarity-angular@0.10.20
npm info lifecycle clarity-angular@0.10.20~uninstall: clarity-angular@0.10.20
npm info lifecycle clarity-angular@0.10.20~postuninstall: clarity-angular@0.10.20
npm info linkStuff clarity-angular@0.10.28
npm info linkStuff clarity-icons@0.10.28
npm info linkStuff clarity-ui@0.10.28
npm info linkStuff harbor-ui@0.6.99
npm info lifecycle clarity-angular@0.10.28~install: clarity-angular@0.10.28
npm info lifecycle clarity-icons@0.10.28~install: clarity-icons@0.10.28
npm info lifecycle clarity-ui@0.10.28~install: clarity-ui@0.10.28
npm info lifecycle harbor-ui@0.6.99~install: harbor-ui@0.6.99
npm info lifecycle clarity-angular@0.10.28~postinstall: clarity-angular@0.10.28
npm info lifecycle clarity-icons@0.10.28~postinstall: clarity-icons@0.10.28
npm info lifecycle clarity-ui@0.10.28~postinstall: clarity-ui@0.10.28
npm info lifecycle harbor-ui@0.6.99~postinstall: harbor-ui@0.6.99
npm info linkStuff harbor@1.3.0
npm info lifecycle harbor@1.3.0~install: harbor@1.3.0
npm info lifecycle harbor@1.3.0~postinstall: harbor@1.3.0
npm info lifecycle harbor@1.3.0~prepublish: harbor@1.3.0
npm info lifecycle harbor@1.3.0~prepare: harbor@1.3.0
harbor@1.3.0 /harbor_src/ui_ng
+-- clarity-angular@0.10.28
+-- clarity-icons@0.10.28
+-- clarity-ui@0.10.28
`-- harbor-ui@0.6.99

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm info ok
/entrypoint.sh: line 29:    18 Killed                  ./node_modules/.bin/ngc -p tsconfig-aot.json
make: *** [compile_clarity] Error 137

**Comment by stonezdj** [comment]
Please try Harbor 1.8.0, Harbor 1.5.1 is out maintenance

**Comment by ahnselina** [comment]
OK,  I try compile this on many machines, then I found that maybe the configuration of machine result to the failure. I compile successfully on  a higher conf machine.
