### ISSUE TITLE
some of harbor components hang after running a long time

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#8031]
we deployed harbor v1.6 in our product enviroment using docker compose. and it runs a long time.
we find that one of harbor containers becomes suspended sometime and harbor is out of duty.
log of suspended harbor component is stoped too.
we check logs in docker daemon and find,
```
Jun 11 11:44:36 harbor-test dockerd[27729]: time="2019-06-11T11:44:36.462835537+08:00" level=error msg="Failed to restore container fb81383e3da5b3e11742bb2f5b8fb43f4612b3530f2cdf0e40b0427a6a748cd5 with containerd: error getting containerd task for container: failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused"
Jun 11 11:44:36 harbor-test dockerd[27729]: time="2019-06-11T11:44:36.463688758+08:00" level=error msg="Failed to restore container 565992f2330b3f4efa50cac51b092bd92764005a1943eade56e2fee8fa8cbdef with containerd: error getting containerd task for container: failed to initialize logging driver: dial tcp 127.0.0.1:1514: getsockopt: connection refused"
```
we set live-restore to true in docker daemon to make containers alive when docker stopped.
this case could be reproduced when restarting dockerd. the reason is that harbor-log depends on docker-proxy to expose 1514 port. and when docker restarts it will read the container dictionary and take charge of running containers. there is a race condition between harbor-log and the components that depend on harbor-log.
is harbor-log necessary in harbor? it will cause harbor depended on docker.

**Comment by reasonerjt** [comment]
@mmpei 
Right now this is a limitation, I think you have to remove `harbor-log` and the log settings from `docker-compose.yml` to work around it.

We are considering to make the logging endpoint configurable in v1.9 timeframe, we'll consider this case, but by default I think we'll leverage `harbor-log` for collecting logs.

**Comment by ninjadq** [comment]
dup to #7008
