### ISSUE TITLE
Harbor 1.8.0: Robot account with pull and push permissions can't get tags from API

### ISSUE THREAD

**Issue by casperfrx** [goharbor/harbor#8035]
**Expected behavior and actual behavior:**
I have a robot account with full pull and push permissions. It is already automatically pushing and pulling images as we speak. However I would like to trigger another robot account based on newer tags being pushed to my repository by fetching the tags using the API.

*Expected*
Get a list of all the available tags of a specific repository with the right permissions set

*Actual*
Above expected result  does not seem possible and instead the API always returns a 403 Forbidden.

**Steps to reproduce the problem:**
1) Create project.
2) Add robot account with full push and pull permissions.
3) Use robot account to successfully push an image to this repository, resulting in both a check on the correct permissions as well as having at least one image with a tag registered in this repository.
4) Use the API with the same robot account both in a manual curl command as well as via the swagger API using the /repositories/{repo_name}/tags endpoint with a GET, obviously using the correct repo name as defined in the project.
5) Get a 403, regardless.

**Versions:**
- harbor version: 1.8.0

**Additional context:**
*Edit*:
More on this issue: a normal user account with the "guest" role to the project, is allowed to see all tags of the repositories. Seems counteruitive.

I would expect a robot account to be able to list all tags once this account even has only pull action. Since pulling every image would pretty much result in the same result.

This is a pretty useful robot endpoint to poll and automate on new pushed images to the Harbor registry.

**Comment by Szauka** [comment]
The same issue happens with the `/repositories?project_id=3` endpoint when a project is specified.
The robot account has access to the specified project but returns `{"code":403,"message":"robot$test"}`

**Comment by balonik** [comment]
As reported for
`/repositories/{repo_name}/tags`
same also applies to
`/repositories/{repo_name}/tags/{tag}`
and all paths under
`/repositories/{repo_name}/tags/{tag}/`

**Comment by balonik** [comment]
Hi, any progress in here?

**Comment by wy65701436** [comment]
@balonik for this issue, you can try with the robot v2, it has the tag access option on creating.
