### ISSUE TITLE
failed to get project "xxx" from source registry: project ""not found

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#8041]
Hello, when using the harbor1.6 version for remote replication, there are some tasks that report errors:failed to get project "xxx" from source registry: project ""not found,However, this project exists.

**Comment by steven-zou** [comment]
More details of the replication?

harbor 1.6 -> harbor 1.6?

**Comment by steven-zou** [comment]
@ywk253100 

Could you please take a look? Thanks!

**Comment by Gypsying** [comment]
harbor 1.5.3 -> 1.5.3 and 2.5.3 have the same issues
@koulq @ywk253100 any methods to solve this problem?
