### ISSUE TITLE
OIDC Login Failed to get OAuth configuration

### ISSUE THREAD

**Issue by DoctahPopp871** [goharbor/harbor#8043]
I need some assistance with setting up the OIDC auth. I have the auth enabled and all fields populated in the UI, but clicking on the login button "login via oidc provider" redirects me to https://harbor.ogilvy-digital.com/c/oidc/login which fails with a 500, rendering the following in the browser : 

`{"code":500,"message":"Internal Server Error"}`

The errors generated on the core server are below.

```
Jun 13 20:14:15 ip-192-168-112-1.us-east-2.compute.internal core[3202]: 2019-06-13T20:14:15Z [ERROR] [/common/utils/oidc/helper.go:148]: Failed to get OAuth configuration, error: failed to create OIDC provider, error: 404 Not Found:
Jun 13 20:14:15 ip-192-168-112-1.us-east-2.compute.internal core[3202]: 2019-06-13T20:14:15Z [ERROR] [/common/api/base.go:229]: failed to create OIDC provider, error: 404 Not Found:
Jun 13 20:14:15 ip-192-168-112-1.us-east-2.compute.internal core[3202]: 2019-06-13T20:14:15Z [ERROR] [/common/api/base.go:69]: GET /c/oidc/login failed with error: {"code":500,"message":"Internal Server Error"}
```

Any advice ?

**Comment by reasonerjt** [comment]
@DoctahPopp871 Thanks for trying out OIDC support.
Please make sure the OIDC endpoint is valid in your setting.  
More details refer to:
https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#managing-authentication

```
OIDC Provider Endpoint: The URL of the endpoint of the OIDC provider(a.k.a the Authorization Server in OAuth's terminology), which must service the "well-known" URI for its configuration, more details please refer to https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest
```

**Comment by reasonerjt** [comment]
@DoctahPopp871 any update?

**Comment by DoctahPopp871** [comment]
Hi There, 

Thanks for your help, and forwarding the documentation. I needed to modify my oidc endpoint so the well-known uri/manifest could be served. Something like this :
`https://login.microsoftonline.com/my-guid-here/v2.0` where the well-known config lives here :
`https://login.microsoftonline.com/my-guid-here/v2.0/.well-known/openid-configuration/`

OIDC login is now working with great success and justice. Thanks!

**Comment by yaron** [comment]
I got the same error. The problem for me was that the url should also not end with a /.

**Comment by qww-ygg** [comment]
@reasonerjt Hello, I am currently unable to log in to the Harbor repository due to an issue with the migration of the Odic server. What can I do to modify the configuration of the OID authentication without going through the UI? The error message is as follows

<img width="2139" height="414" alt="Image" src="https://github.com/user-attachments/assets/278ddaed-40cd-4ead-a135-29cbbebe6053" />
