### ISSUE TITLE
2019-06-14T00:50:17Z [ERROR] [job_logger.go:81]: an error occurred while pulling manifest of library/gitaly:v1.27.1 from source registry: 401 {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/gitaly","Action":"pull"}]}]

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#8046]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
2019-06-14T00:50:17Z [ERROR] [job_logger.go:81]: an error occurred while pulling manifest of library/gitaly:v1.27.1 from source registry: 401 {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/gitaly","Action":"pull"}]}]

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.6.2]
- docker engine version: [17.03.2-ce]
- docker-compose version: [1.14.0]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
I'm closing this one.
Please respect the template and refine your issue to make it more readable to human
