### ISSUE TITLE
harbor service is failing

### ISSUE THREAD

**Issue by ranjithfd** [goharbor/harbor#8053]
harbor service is failing after the new bosh cert has been updated. Please find the below log. 

What can we help  Experimental: false
[Fri Jun 14 14:10:23 UTC 2019] Docker daemon is running
[Fri Jun 14 14:10:23 UTC 2019] Remove dead docker containers if exist
[Fri Jun 14 14:10:23 UTC 2019] Launching 'docker-compose up' ...
process already running.
[Fri Jun 14 14:10:28 UTC 2019] Waiting for Harbor Service to be ready ...
[Fri Jun 14 14:10:28 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:33 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:39 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:44 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:49 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:54 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:10:59 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:11:04 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:11:09 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:08:00 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:08:06 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:08:11 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:08:16 UTC 2019] Harbor service is not ready. Waiting for 5 seconds then check again.
[Fri Jun 14 14:08:21 UTC 2019] Error: Harbor Service failed to start in 180 seconds.
[Fri Jun 14 14:10:23 UTC 2019] Starting Harbor 1.5.2 at 
you?

**Comment by stonezdj** [comment]
Could you please upload the logs collected by  `bosh logs` ?
