### ISSUE TITLE
Robot user not working with OIDC authentication

### ISSUE THREAD

**Issue by rofafor** [goharbor/harbor#8054]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Robot users can't login if the OIDC authentication mode is enabled:

```
Jun 14 18:50:46 172.27.0.1 core[26877]: 2019-06-14T15:50:46Z [ERROR] [/core/filter/security.go:471]: failed to authenticate robot: Unrecognized auth_mode: oidc_auth
```

**Steps to reproduce the problem:**
1. Enable OIDC authentication mode
2. Create a robot user and store generated token
3. Use docker-cli to login into harbor with the credentials (name & token)

```
% echo <token> | docker login --password-stdin -u robot$<name> harbor.at.my.domain
Error response from daemon: Get https://harbor.at.my.domain/v2/: unauthorized: authentication required
```

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0]
- docker engine version: [18.09.6]
- docker-compose version: [1.24.0-rc3]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
try this? 
https://github.com/goharbor/harbor/issues/7944#issuecomment-498725403

**Comment by rofafor** [comment]
Yes, that was it!

I found the `$` delimiter in username as a bad choice as shells are interpreting it by default. A note about this in in the documentation would be a good start.

```
% docker login harbor.at.my.domain-u 'robot$<name>' -p '<token>'
Login Succeeded
% cat token.txt | docker login -u 'robot$<name>' --password-stdin harbor.at.my.domain
Login Succeeded
% cat token.txt | docker login -u robot\$<name> --password-stdin harbor.at.my.domain
Login Succeeded
% cat token.txt | docker login -u "robot$<name>" --password-stdin harbor.at.my.domain
Error response from daemon: Get https://harbor.at.my.domain/v2/: unauthorized: authentication required
```

**Comment by kenperkins** [comment]
I've tried quoted and unquoted with the robot using kubernetes image pull secrets and have not gotten it to work. Can anyone help me understand how to do this correctly with 1.8.x and K8s?

**Comment by ilyesAj** [comment]
@kenperkins i'm having the same issue, did found any solution for that ?

**Comment by stop-coding** [comment]
i'm having the same issue, did found any solution for that ? only with OIDC authentication mode
