### ISSUE TITLE
When configured to GCS storage chartmuseum failed to start

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8055]
After configured to gcs storage, chartmuseum failed to start
with error message: open /etc/chartserver/gcs.key: no such file or directory
docker-compose.yml.jinja line 419
```
{% if gcs_keyfile %}
      - type: bind
        source: {{gcs_keyfile}}
        target: /etc/registry/gcs.key
{% endif %}
```
It should be mounted to /etc/chartserver/gcs.key

**Comment by ninjadq** [comment]
fixed in #8056 by @stonezdj
