### ISSUE TITLE
设置chart的name参数后questions.yml配置选项不起作用

### ISSUE THREAD

**Issue by fengshunli** [goharbor/harbor#8059]
配置chart的name为mongodb,然后拉取仓库现实配置选项正常
![image](https://user-images.githubusercontent.com/18587688/59586383-6b2d9180-9115-11e9-9609-fb1150c49ce1.png)
改变chart的name为mongodb-88,然后拉取仓库现实配置选项不起作用
![image](https://user-images.githubusercontent.com/18587688/59586422-83051580-9115-11e9-9acd-285a0961dc3e.png)
是不是对questions.yml这个文件做了什么限制

**Comment by steven-zou** [comment]
@Juvenile

From your screenshot, you configured the Harbor chart repository as backend repo of k8s platform and then deploy a selected chart with the wizard? The issue occurred when changing the name?

As far as I know, Harbor does not do any modification to the question.yaml.

**Comment by fengshunli** [comment]
修改过的name,rancher从github拉取的仓库是可以用的,但是从harbor上传拉取的就不可以

**Comment by fengshunli** [comment]
![image](https://user-images.githubusercontent.com/18587688/59652893-480ceb80-91c2-11e9-84d9-6448d735ffdd.png)

商店地址 https://github.com/fengshunli/mongodb
效果展示
![image](https://user-images.githubusercontent.com/18587688/59652915-64108d00-91c2-11e9-8312-eb1782ec9aaf.png)
同样的chart文件,通过harbor打包传进去的展示不出来

**Comment by reasonerjt** [comment]
@fengshunli could you narrow down the scope, for example, what's the expected/actual behavior without Rancher?  Could you reproduce it by calling the API of Harbor?

**Comment by fengshunli** [comment]
就是调用harbor的上传接口,上传成功后,拉取的是不可以用的

**Comment by fengshunli** [comment]
发现修改chart包的name后上传的tag包在rancher上面没办法部署,报错提示
![image](https://user-images.githubusercontent.com/18587688/59743888-e45aef00-92a3-11e9-938f-827641920212.png)

**Comment by heww** [comment]
This problem was happened when change the in `Chart.yaml` but the package dir extract from tgz still the old name so rancher can not file the chart content by chart name.

You should use `helm package CHART_PATH` the make the package.

**Comment by reasonerjt** [comment]
Thanks @heww 
Closing the issue @fengshunli  feel free to re-open if you are still seeing the problem
