### ISSUE TITLE
gotharbor/prepare:v1.8.1 is not published

### ISSUE THREAD

**Issue by k0da** [goharbor/harbor#8067]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
running install.sh from 1.8.1 release fails

preparing environment ...
 prepare base dir is set to /etc/harbor
 Unable to find image 'goharbor/prepare:v1.8.1' locally
 docker: Error response from daemon: manifest for goharbor/prepare:v1.8.1 not found.
 See 'docker run --help'.

**Steps to reproduce the problem:**
docker pull goharbor/prepare:v1.8.1
Error response from daemon: manifest for goharbor/prepare:v1.8.1 not found

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.1
- docker engine version: 18.06
- docker-compose version: docker-compose-1.18.0

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment]
@k0da just try it again.

**Comment by k0da** [comment]
@wy65701436 it got published now, thx
