### ISSUE TITLE
1.8版本harbor向1.6版本harbor同步镜像，1.6版本页面上看不到

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#8068]
What can we help you?
你好，我刚部署了一个1.8版本的harbor，创建了1个同步，目标仓库是1.6版本的harbor，但是在1.6版本harbor页面上看不到同步过来镜像，但是1.8版本的harbor显示同步成功。

看了1.6版本harbor的日志，确定是ui没有接收到事件，看registry.log，报如下错误：
Jun 18 16:56:49 172.18.0.1 registry[17619]: time="2019-06-18T08:56:49.24287695Z" level=error msg="response completed with error" auth.user.name=xxxx err.code="manifest unknown" err.detail="unknown tag=v0.5.1" err.message="manifest unknown" go.version=go1.7.3 http.request.host="xxxx" http.request.id=ecb0faa4-cd14-4b38-bda9-235254082782 http.request.method=HEAD http.request.remoteaddr=xxxxxx http.request.uri="/v2/sync-test/chartmuseum/chartmuseum/manifests/v0.5.1" http.request.useragent=harbor-replication-service http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.371282ms http.response.status=404 http.response.written=96 instance.id=99606678-86ba-4aa1-8a96-a66af5ae5c2a service=registry vars.name="sync-test/chartmuseum/chartmuseum" vars.reference=v0.5.1 version=v2.6.2 。是1.8版本的registry和1.6版本registry版本不一致的问题吗？

**Comment by koulq** [comment]
@reasonerjt This problem is more urgent. Can you show it?，I deployed another 1.8 version in another environment, and mirror replication between two 1.8 versions is fine.

**Comment by reasonerjt** [comment]
I don't think we fully support replication between Harbor instances with different versions.

But the `manifest unknown` error may not caused by different version.

**Comment by koulq** [comment]
@reasonerjt @ywk253100 
1.8 harbor ：The display is ok
![image](https://user-images.githubusercontent.com/18571340/59734613-c0d47c00-9284-11e9-849b-5d7c58cbc90d.png)
![image](https://user-images.githubusercontent.com/18571340/59734655-e1043b00-9284-11e9-9741-93ab57248fbf.png)
![image](https://user-images.githubusercontent.com/18571340/59734688-05601780-9285-11e9-9cc9-2c6d0ca5a8ec.png)

1.6 harbor：No mirror image on the page
![image](https://user-images.githubusercontent.com/18571340/59734746-33455c00-9285-11e9-880b-42d42dde129c.png)
registry.log：
![image](https://user-images.githubusercontent.com/18571340/59734919-f2017c00-9285-11e9-8f24-6979a0dffa6b.png)

**Comment by ywk253100** [comment]
首先确认下在1.6的Harbor的存储中是否有这个image（image的存储路径缺省在/data/registry），然后尝试用docker直接向Harbor push这个镜像，查看是否可以成功。

**Comment by koulq** [comment]
@ywk253100 查了1.6下的harbor，是有这个image的
![image](https://user-images.githubusercontent.com/18571340/59900752-b56f8500-942b-11e9-8ec1-f6f46c6b8242.png)

**Comment by ywk253100** [comment]
`link`这个文件中记录了manifest对应的sha256的值，确定下在`/registry/docker/registry/v2/blobs`下是否有对应的文件。

**Comment by koulq** [comment]
@ywk253100  有的
![image](https://user-images.githubusercontent.com/18571340/59901914-501d9300-942f-11e9-919e-47743d96362f.png)
![image](https://user-images.githubusercontent.com/18571340/59901928-590e6480-942f-11e9-9810-08f298fd80ff.png)

**Comment by ywk253100** [comment]
尝试用docker client直接向1.6push这两个镜像，看是否可以成功push上去并在ui上显示出来。

**Comment by koulq** [comment]
> 尝试用docker client直接向1.6push这两个镜像，看是否可以成功push上去并在ui上显示出来。

使用客户端是可以的，如下图：
![image](https://user-images.githubusercontent.com/18571340/60322977-6b4e4c80-99b3-11e9-8517-108fa2ec5c94.png)
![image](https://user-images.githubusercontent.com/18571340/60323002-7903d200-99b3-11e9-9fcc-732888f09e35.png)

**Comment by koulq** [comment]
这个1.6环境之前一直是用着的，包括1.6和1.6同步都是没问题的

**Comment by koulq** [comment]
我今天又试了一下1.6向1.8同步，目标仓库ping都不通
![QQ截图20190628145259](https://user-images.githubusercontent.com/18571340/60323483-cf254500-99b4-11e9-9cb9-d8e96a58b9b8.png)

**Comment by koulq** [comment]
@reasonerjt @ywk253100 同步的问题有解了吗？

**Comment by ywk253100** [comment]
@koulq Please package all logs of the source(1.8) and destination(1.6) Harbor instances and upload them.
Maybe it is related with https://github.com/docker/distribution/issues/2625. We need to check the logs first

**Comment by ywk253100** [comment]
Closing it as inactivity
