### ISSUE TITLE
How to cancel cron gc job

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#8070]
**Expected behavior and actual behavior:**
I create a daily cron gc job at 5 AM few days ago, and the second day I canceled it by setting cron to None. But I found  the gc job still execute everyday.And I check it in th db and found its status is error.
![image](https://user-images.githubusercontent.com/9589048/59737064-c59e2d80-928e-11e9-99be-ea8a301eb615.png)

**Steps to reproduce the problem:**
create a daily cron job , and set cron gc job to None. The gc job will still execute from then on everyday.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.1
- docker engine version: 1.12.6
- docker-compose version: 1.13.0

**Comment by steven-zou** [comment]
@louyiping 

Known issue. You can try clear the redis db under /data/redis and restart

**Comment by louyiping** [comment]
@steven-zou Hello, do you mean just execute "rm -rf /data/redis/" ?

**Comment by steven-zou** [comment]
@louyiping 

Yes. Please pay attention here, backup that dum.rdb file before clearing in case some bad things happened.

**Comment by louyiping** [comment]
@steven-zou Thanks. Solve my problem. Close the issue.
