### ISSUE TITLE
LDAP Authentication: Internal Server Error 500 (v. 1.8.0)

### ISSUE THREAD

**Issue by sh3tb3rd** [goharbor/harbor#8071]
When trying to establish an LDAP authentification with our AD, it always results in an server error 500. Using the previous version, there are no issues at all using the exact same information. 

Anyone else with this issue? Is there something I am missing? 

I've noticed that with v. 1.8.x there is no more harbor.cfg file to configure, instead, there is now a harbor.yml file which is working just fine, but has no options for configuring LDAP whatsoever.

**Comment by justinhauer** [comment]
What was the resolution to this?
