### ISSUE TITLE
Repository beyond images and helm charts

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8079]
we would like to expand harbor to be a repository beyond   images and helm charts. In a cloud native world, there are needs for scripts, operators, CNAB bundles, RPMs, Jar files, etc. The IoT community even asked if we can support host device firmware since there aren't many hosting solutions or repos in the IoT edge

main drivers: CNAB bundles, repository for operators
Administrators can control file extensions supported.
Will need to changes to the UI to create a new folder that includes all artifacts (images, helm charts, anything else we support)

How to control ACLs/RBAC on push/pull since you can't use the docker client? possibly use the git client/interface. Another option is to look at the OCI registry spec for additional file support.

git support
* RBAC using OIDC
* push/pull content
* large file size support
* no branching support
* no directory support
* disable all git capabilities beyond login/logout/push/pull

**Comment by xaleeks** [comment]
Hey Michael, detailed proposal for this supporting this will be tracked here:https://github.com/goharbor/community/pull/111/files

I'm closing this to clean up the swimlanes

**Comment by Hokwang** [comment]
@xaleeks I am interested in this feature. You marked this completed, but I can't find files in community/proposal repo.
And I just wonder this issue does not lead to add/change your code in harbor repo?

**Comment by michmike** [comment]
@Hokwang we will deliver this with Harbor 2.0 in late April 2020.

**Comment by michmike** [comment]
and to be specific, we will enable Harbor to be OCI compliant. so you can push/pull any oci compliant image into Harbor. all the rest of the Harbor capabilities will work for OCI files (quota, retention, etc). Scanning will work for the OCI artifacts that scanners supports today (for example images and potentially cnab bundles)

**Comment by paroque28** [comment]
Hi all, How would you upload an RPM with these newly merged changes?

**Comment by pashcan** [comment]
@paroque28 Or jar files for that matter.

**Comment by zooks1138** [comment]
Any news on supporting RPMs and other blobs in Harbor? From what I've seen on OCI I'm not confident that it will work for arbitrary files. Freely admit my noob status in this area, though.
