### ISSUE TITLE
Proxy cache

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8082]
enable proxy cache for Harbor.

This is very useful in situations of intermittent network connectivity where you still need access to local images. the expectation is that the network will go off in ROBO or IoT scenarios

Of course, the standard use case of reducing redundant image pulls across the network applies here

**Comment by alexvmw** [comment]
@michmike Is this referring to deploying a worker instance close to the edge nodes functioning specifically as a local registry mirror for a central Harbor and have the edge daemons pointing to it for local pulls? or is Harbor being used as proxy cache to pull from other registries like Docker hub and such?  I mean is this this linking Harbor instances or w/ rest of the registry ecosystem.

somethings to think about
- once pulled, how does long is it kept in cache for other clients before cleaned, there should be some LRU (least recently used) algorithm for determination
- 'subsequent' pulls of any particular image can be based on just the image manifest
- user pulling image needs to be properly authenticated and authorization checked before redirected to the local cache
- will this be able to work w/ rbac
- when to use this vs deploying another harbor cluster and relying on regular replication

**Comment by salcinad** [comment]
@michmike 
are you referring to the: https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md

our need is that we don't pull Images from "registry-1.docker.io" (from docker hub in Internet) but from internal Harbor Register which will act as Proxy/Cache ( for example this Option is avaiable in Nexus 3), which will Cache and if not cached pull Images from docker hub and provide to user.

**Comment by michmike** [comment]
proxy cache is a feature of registry v2. this is what i meant  - https://mtijhof.wordpress.com/2018/07/23/using-nexus-oss-as-a-proxy-cache-for-docker-images/

**Comment by michmike** [comment]
we of course don't have to restrict the Harbor capabilities, so it could pull images as a cache from any type of replication target we can support

**Comment by stonezdj** [comment]
> proxy cache is a feature of registry v2. this is what i meant - https://mtijhof.wordpress.com/2018/07/23/using-nexus-oss-as-a-proxy-cache-for-docker-images/

The pull through proxy only works for docker hub, it doesn't work for other registry repository.

**Comment by xaleeks** [comment]
@stonezdj yes it seems the docker registry's own proxy mechanism still only works for docker hub.  There's a pr on supporting other self hosted registries but still unmerged after 2 years 
https://github.com/moby/moby/pull/34319

**Comment by xaleeks** [comment]
PRD: 
https://docs.google.com/document/d/15CRHZuxfw9cm3booRVIToZrkc3Emqi-6Z26-AlmAWuE/edit
ping me for access

**Comment by sadoMasupilami** [comment]
As docker hub is soon enforcing strict image pull limits this feature is very important I think.

https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

**Comment by gregsidelinger** [comment]
Is there anyway to configure harbor 2.1 as a transparent docker hub mirror?  I can only make 2.1 pull from the upstream by doing things like this `docker pull mycache/library/tomcat:latest`. I was hoping I could make it work like this  `docker pull tomcat:latest` by pointing my registry-mirror setting to my harbor install.

**Comment by xaleeks** [comment]
This is delivered in the 2.1 release now

@gregsidelinger  not at this time, we looked at using a mutating webhook or something similar but we couldn't find a good enough solution in 2.1, but this requirement is known to us.

**Comment by ChristianCiach** [comment]
@gregsidelinger You can use an nginx reverse proxy that rewrites and forwards all requests of the docker-daemon to Harbor to effectively use Harbor as a **transparent** proxy for docker-hub. Please see my solution here: https://github.com/moby/moby/pull/34319#issuecomment-720606627

**Comment by jgallucci32** [comment]
@xaleeks @gregsidelinger Using the example from @ChristianCiach I was able to get Harbor to act as both a transparent proxy for Docker Hub and a Private Registry. It involves 4 steps:
1. Create a Proxy Cache project (i.e. `docker.io`) as pull-through cache to Docker Hub
2. Create DNS alias (i.e. `docker-mirror.domain.local`) which points to the DNS name of Harbor
3. Modify the `nginx.conf` file for the harbor-nginx pod to rewrite the URLs for `/v2` and `/service` when using the DNS alias
4. Configure Docker daemon to use DNS alias as registry-mirror

Modifications to `nginx.conf`
```
#   location /v2/ {
      if ($host = 'docker-mirror.domain.local') {
        rewrite ^/v2/((?!docker.io).+)$ /v2/docker.io/$1 last;
      }
...
#   location /service/ {
      if ($args ~* (.*scope=repository%3A)((?!docker.io).*)) {
        set $args $1docker.io%2F$2;
      }
      if ($host = 'docker-mirror.domain.local') {
        rewrite ^(.*)$ $1;
      }
...
```
I am thinking this really needs to be its own pod within Harbor so it can be decoupled from the primary service. Since this issue is closed out I will work on creating a new one with this information.

**Comment by bagel-dawg** [comment]
> @xaleeks @gregsidelinger Using the example from @ChristianCiach I was able to get Harbor to act as both a transparent proxy for Docker Hub and a Private Registry. It involves 4 steps:
> 
>     1. Create a Proxy Cache project (i.e. `docker.io`) as pull-through cache to Docker Hub
> 
>     2. Create DNS alias (i.e. `docker-mirror.domain.local`) which points to the DNS name of Harbor
> 
>     3. Modify the `nginx.conf` file for the harbor-nginx pod to rewrite the URLs for `/v2` and `/service` when using the DNS alias
> 
>     4. Configure Docker daemon to use DNS alias as registry-mirror
> 
> 
> Modifications to `nginx.conf`
> 
>     1. Put in `http {` block
> 
> 
> ```
>   # Map for proxy cache
>   map $upstream_http_www_authenticate $new_header {
>     ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$host$suffix1;
>   }
>   map $args $new_args {
>     ~^(?<prefix2>.*scope=repository%3A)(?<suffix2>(?!docker.io).*)$     ${prefix2}docker.io%2F$suffix2;
>   }
> ```
> 
>     1. Put in second `server {` block
> 
> 
> ```
>     # Rewrite for proxy cache
>     if ($host = 'docker-mirror.domain.local') {
>       rewrite ^/v2/((?!docker.io).+)$ /v2/docker.io/$1 last;
>       set $args $new_args;
>     }
> ```
> 
>     1. Put in `location /v2/ {` block
> 
> 
> ```
>       # Modify headers for proxy cache
>       proxy_hide_header Www-Authenticate;
>       add_header Www-Authenticate $new_header always;
> ```
> 
> I am thinking this really needs to be its own pod within Harbor so it can be decoupled from the primary service. Since this issue is closed out I will work on creating a new one with this information.
> 
> UPDATE: I made changes based on some research and testing where `map` tables are better than multiple `if` blocks

Could you provide a more-complete example of this? I am trying to attempt this patch but I am unable to get my nginx.conf to work right. I'm also a bit confused because your transparent proxy also seems to be named `docker.io` so I am unsure of what needs to be `docker.io` literally and what needs to be `$MY_HARBOR_PROJECT_NAME`

**Comment by jgallucci32** [comment]
@bagel-dawg The name of the Harbor project is literally `docker.io`, though it can be anything you like (you will need to rename anything that says `docker.io` in my changes to the actual name of the project you chose if different). I prefer to name it the first part of the upstream repository to make it easy to remember where the cached images come from. I will grab the full copy of nginx.conf, but what I posted above are the only changes made to nginx.conf after deploy 2.1.1 of Harbor.

**Comment by bagel-dawg** [comment]
@jgallucci32 Thanks, I actually got it working. It seemed that I was running [into this issue with the Host header.](https://stackoverflow.com/questions/32362396/nginx-reverse-proxy-causing-infinite-loop)

The redirect kept occurring over and over again until it failed, and then docker would failback to the the non-mirror address.

**Comment by hwchiu** [comment]
@bagel-dawg @jgallucci32 
I tried the steps shown above but it didn't work, I checked the proxy.log from the Harbor but didn't see any error, do you have any preferred way to debug this issue? how do I ensure my Nginx works as I expect?

For example, I tried to pull the busybox image from my docker side and I can see HTTP requests in Harbor's proxy.log. so I think the registry-mirror setting in docker-client is correct.
Following is the log message from the proxy.log but I don't know how to debug it.
```
GET /v2/ HTTP/1.1" 401 76 "-" "docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(linux\x5C))" 0.002 0.000 .

GET /service/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=harbor-registry HTTP/1.1" 200 948 "-" "docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(linux\x5C))" 0.020 0.020 .

GET /v2/library/busybox/manifests/latest HTTP/1.1" 404 83 "-" "docker/19.03.5 go/go1.12.12 git-commit/633a0ea838 kernel/4.15.0-72-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.13 \x5C(linux\x5C))" 0.005 0.000 .
```

Thanks

**Comment by jgallucci32** [comment]
@hwchiu The first 2 lines look correct. You get HTTP/401 for `/v2` which then redirects to get the bearer token which returns HTTP/200. The third request is HTTP/404 meaning URL is not found.

You will need to first verify your proxy cache is working by attempting a pull-through request like this
```
docker pull harbor.domain.local/docker.io/library/busybox:latest
```
If that is successful, then try to get the manifest directly using a web browser with the DNS alias you use for the mirror
```
https://harbor-mirror.domain.local/docker.io/library/busybox/manifests/latest
```
This will test if you can get to the image in the proxy cache using the DNS alias with the full path to the image.  Unfortunately nginx logging in K8s is not very good (or at least I haven't figured out how to get good debugging yet)

**Comment by hwchiu** [comment]
@jgallucci32 
Thanks for your help, I follow your steps to verify the function, yes, I can pull the image in step (1) and I can see the image is created in the Harbor's UI.
However, when I open the URL on the second step, it shows the 404 Page not found.
but, at least I have a new way to test my nginx config.
Thanks for your help.

**Comment by hwchiu** [comment]
@jgallucci32 
Fixed, I put the config in the wrong server section. 
Thanks for your help again.

**Comment by jgallucci32** [comment]
@hwchiu @bagel-dawg I did some refactoring to use map variables to make it more clear what you need to set and reduces the changes made. I also added an improvement where the DNS suffix can be used in the form of `<harbor_project>.harbor-mirror.domain.local` so you only have to modify nginx.conf once and can configure it for X number of projects (this is very helpful with deployments with containerd which can support multiple mirrors)


Harbor can act as both a transparent proxy and Private Registry for multiple repositories:
1. Create a Proxy Cache project (i.e. `docker.io`) as pull-through cache to Docker Hub
2. Create DNS alias (i.e. `docker-mirror.domain.local`) which points to the DNS name of Harbor
3. Create wildcard DNS alias (i.e. `*.docker-mirror.domainlocal`) which points to the DNS name of Harbor
3. Modify the `nginx.conf` file for the harbor-nginx pod to rewrite the URLs for `/v2` and `/service` when using the DNS alias
4. Configure Docker daemon to use DNS alias as registry-mirror (or use DNS subdomain of Harbor project) (NOTE: You must specify "insecure-registries" if your SSL cert is not configured for wildcard DNS subdomains)

Modifications to `nginx.conf`

1. Put in `http {` block
```
  # Map for proxy cache
  map $host $harbor_project {
    default 0;
    ~^docker-mirror.domain.local$ docker.io;
    ~^(?<project>.+).docker-mirror.domain.local$ $project;
  }
  map $request_uri $new_uri {
    ~^/v2/(.+)$ /v2/$harbor_project/$1;
  }
  map $args $new_args {
    ~^(?<prefix2>.*scope=repository%3A)(?<suffix2>.*)$     ${prefix2}${harbor_project}%2F$suffix2;
  }
  map $upstream_http_www_authenticate $new_header {
    ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$host$suffix1;
  }
```
2. Put in second `server {` block
```
    # Rewrite for proxy cache
    if ($harbor_project != 0) {
      rewrite ^/v2/(.+)$ $new_uri;
      set $args $new_args;
    }
```
3. Put in `location /v2/ {` block
```
      # Modify headers for proxy cache
      proxy_hide_header Www-Authenticate;
      add_header Www-Authenticate $new_header always;
```
Please test this out and let me know if you run into any issues.

**Comment by jgallucci32** [comment]
@hwchiu @bagel-dawg I created a new issue (feature request) to track this and plan to work this into a PR for review https://github.com/goharbor/harbor/issues/13579

**Comment by hwchiu** [comment]
> @hwchiu @bagel-dawg I did some refactoring to use map variables to make it more clear what you need to set and reduces the changes made. I also added an improvement where the DNS suffix can be used in the form of `<harbor_project>.harbor-mirror.domain.local` so you only have to modify nginx.conf once and can configure it for X number of projects (this is very helpful with deployments with containerd which can support multiple mirrors)
> 
> Harbor can act as both a transparent proxy and Private Registry for multiple repositories:
> 
> 1. Create a Proxy Cache project (i.e. `docker.io`) as pull-through cache to Docker Hub
> 2. Create DNS alias (i.e. `docker-mirror.domain.local`) which points to the DNS name of Harbor
> 3. Create wildcard DNS alias (i.e. `*.docker-mirror.domainlocal`) which points to the DNS name of Harbor
> 4. Modify the `nginx.conf` file for the harbor-nginx pod to rewrite the URLs for `/v2` and `/service` when using the DNS alias
> 5. Configure Docker daemon to use DNS alias as registry-mirror (or use DNS subdomain of Harbor project) (NOTE: You must specify "insecure-registries" if your SSL cert is not configured for wildcard DNS subdomains)
> 
> Modifications to `nginx.conf`
> 
> 1. Put in `http {` block
> 
> ```
>   # Map for proxy cache
>   map $host $harbor_project {
>     default 0;
>     ~^docker-mirror.domain.local$ docker.io;
>     ~^(?<project>.+).docker-mirror.domain.local$ $project;
>   }
>   map $request_uri $new_uri {
>     ~^/v2/(.+)$ /v2/$harbor_project/$1;
>   }
>   map $args $new_args {
>     ~^(?<prefix2>.*scope=repository%3A)(?<suffix2>.*)$     ${prefix2}${harbor_project}%2F$suffix2;
>   }
>   map $upstream_http_www_authenticate $new_header {
>     ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$host$suffix1;
>   }
> ```
> 
> 1. Put in second `server {` block
> 
> ```
>     # Rewrite for proxy cache
>     if ($harbor_project != 0) {
>       rewrite ^/v2/(.+)$ $new_uri;
>       set $args $new_args;
>     }
> ```
> 
> 1. Put in `location /v2/ {` block
> 
> ```
>       # Modify headers for proxy cache
>       proxy_hide_header Www-Authenticate;
>       add_header Www-Authenticate $new_header always;
> ```
> 
> Please test this out and let me know if you run into any issues.

Thanks for your help, I will run it again when I have the time and let you know if I have any issues.

**Comment by ChristianCiach** [comment]
As shown by @jgallucci32, you could rewrite the "Www-authenticate" like this:

```
  # Map for proxy cache
  map $upstream_http_www_authenticate $new_header {
    ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$host$suffix1;
  }
  ```

But this could fail if your nginx reverse proxy runs on a different port than the docker client uses to connect to it. In my example, my nginx runs at port 443 inside the container, but the port is mapped to 5000 on the host (`-p 5000:443`). In this case, the port (5000 in my case) will be missing from the `Www-authenticate` header, which causes the docker client to connect to the `/service`-endpoint using the wrong port (443 by default).

To fix this, we can just use the variable `$http_host` instead of `$host`, which will include the port of the request:

```
map $upstream_http_www_authenticate $new_header {
    ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$http_host$suffix1;
}
```

**Comment by aSauerwein** [comment]
I've tried so setup a transparent registry with Harbor 2.3.2 and editing the nginx.conf but it does not work. I always get this error message
```
Error response from daemon: unauthorized: authorize header needed to send HEAD to repository: authorize header needed to send HEAD to repository
```
my modified nginx.conf: https://gist.github.com/aSauerwein/424ac58e13c7aadd619b3c75461e555f

debugging with curl shows me that the  `Www-Authenticate`header is missing when using my docker-mirror instead of harbor directly

**Comment by ricardojdsilva87** [comment]
Hello all, just an update with the code for nginx that enabled us to use Harbor as a dockerproxy with containerd and docker.

We are using NGINX helm chart, and added the following in the http:
```
    http-snippet: |
      # Map for docker.io proxy cache
      map $host $harbor_project {
        default 0;
        ~^dockerproxy.cicd.(.*)intra.oneweb.mercedes-benz.io$ proxy;
      }
      map $request_uri $new_harbor_uri {
        ~^/v2/(.+)$ /v2/$harbor_project/$1;
      }
      map $new_harbor_uri $new_containerd_uri {
        default $new_harbor_uri;
        ~^/v2/(.+)\?ns=docker\.io(.*)$ /v2/$1$2;
      }
      map $args $new_harbor_args {
        ~^(?<prefix2>.*scope=repository%3A)(?<suffix2>.*)$     ${prefix2}${harbor_project}%2F$suffix2;
      }
      map $upstream_http_www_authenticate $new_harbor_header {
        ~^(?<prefix1>.*https://).*(?<suffix1>/service/token.*)$     $prefix1$http_host$suffix1;
      }
```

Added after the following annotations on the proxy ingress:
```
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      # Rewrite for docker.io proxy cache
      if ($harbor_project != 0) {
        rewrite ^/v2/(.+)$ $new_harbor_uri;
        rewrite ^/v2/(.+)$ $new_containerd_uri;
        set $args $new_harbor_args;
      }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Modify headers for proxy cache  
      proxy_hide_header Www-Authenticate;
      add_header Www-Authenticate $new_harbor_header always;
```

Hope it helps

**Comment by wolfganghuse** [comment]
I am also seeing 401 unauth when trying to use docker-io.docker-registry.mydomain.local like described above.
https is configured and Cert is valid. 
Harbor is 2.4.1 offline install running with docker-compose.

**Comment by hiddenmarten** [comment]
If anybody has issues with their non-nginx-based ingress controller, welcome to this [simple chart](https://github.com/hiddenmarten/harbor-project-proxy).

Thanks for the inspiration:
@pedroosorio, @jgallucci32 and @ricardojdsilva87

**Comment by asdorsey** [comment]
The following is a further modification of @pedroosorio 's [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-1683724182) that adds the capability to bypass the mapping and rewriting process for certain domains.  

I needed both transparent proxy caches and the ability to upload to other projects, but I had issues with the `/blobs/uploads` map pattern applying multiple times (probably because of a redirect somewhere), so I'd end up with the project name in the URI multiple times.  With this change, I can instead exclude one of the domain names pointing to this Harbor instance, so when using that excluded domain, Harbor acts normally (without the rewrites and stuff for the transparent proxy cache).

Unfortunately I did have to use an `if` for the `rewrite` in the `location /v2/` block to get this to work.  Someone better at NGINX than me could probably eliminate that `if`.

1. Add to http{ block:

```
  map $host $harbor_project {
    default 0;
    ~^harbor.example.com$ 0;        # this is how to specify a domain name to exclude from processing
    ~^(?<project>.+).example.com$ $project;
  }

  map "$harbor_project#$request_uri" $harbor_registry_uri {
    default $request_uri;
    "~^0#.*$" $request_uri;
    "~^.+#/v2/_catalog.*$" $request_uri;
    "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
    "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
    "~^.+#/v2/([^/]+)(.*)$" /v2/$harbor_project/library/$1$2;
    "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
  }
  
  map "$harbor_project#$args" $harbor_args {
    default $args;
    "~^0#.*$" $args;
    "~^.+#(?<arg_prefix>.*scope=repository%3A)(?<arg_suffix>.*)$" $arg_prefix$harbor_project%2F$arg_suffix;
  }
  
  map "$harbor_project#$upstream_http_www_authenticate" $harbor_authenticate_header {
    default $upstream_http_www_authenticate;
    "~^0#.*$" $upstream_http_www_authenticate;
    "~^.+#(?<header_prefix>.*http.+//).*(?<header_suffix>/service/token.*)$" $header_prefix$http_host$header_suffix;
  }
```

2. Add to location /v2/ block:

```
      if ($harbor_project) {
        rewrite ^/v2/(.+)$ $harbor_registry_uri break;
      }
      proxy_hide_header Www-Authenticate;
      add_header Www-Authenticate $harbor_authenticate_header always;

```

3. Add to location /service/ block:

```
    set $args $harbor_args;
```

**Comment by kvaps** [comment]
Hi all, I experimented with this today, and found that this configuration working to me:

1. Add to `http{` block:

```
map $host $harbor_project {
  default 0;
  ~^harbor.example.com$ 0;
  ~^(?<project>.+).example.com$ $project;
}

map "$harbor_project#$request_uri" $harbor_registry_uri {
  default $request_uri;
  "~^0#.*$" $request_uri;
  "~^.+#/v2/_catalog.*$" $request_uri;
  "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/([^/]+)(.*)$" /v2/$harbor_project/library/$1$2;
  "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
}

map $args $harbor_args{
  default $args;
  ~^(?<arg_prefix>.*scope=repository%3A)(?<arg_suffix>.*)$ $arg_prefix$harbor_project%2F$arg_suffix;
}

map $upstream_http_www_authenticate $harbor_authenticate_header {
  default $upstream_http_www_authenticate;
  ~^(?<header_prefix>.*http.+//).*(?<header_suffix>/service/token.*)$ $header_prefix$http_host$header_suffix;
}
```

2. Add to location `/v2/` block in the bottom:

```
rewrite ^/v2/(.+)$ $harbor_registry_uri break;
proxy_hide_header Www-Authenticate;
add_header Www-Authenticate $harbor_authenticate_header always;
```

3. Add to location `/service/` block in the bottom:

```
set $args $harbor_args;

    Adds support for http and https installations
    Does not use if's
    Supports docker, podman and containerd
    Removes query parameters when they are not expected - https://docs.docker.com/registry/spec/api/

How to use:

    Do this changes to nginx.conf
    Create a registry to the given target registry
    Create a project (proxy-cache type) using the registry named 'xyz'
    In the machines using Harbor as the proxy, add an host 'xyz.harbor.local' pointing to the harbor IP
    Repeat 2,3 and 4 for each registry to be mirrored
```

If 'harbor.local' is not a good suffix for you, make sure you change it in the hosts file as well as in the nginx configuration at map $host $harbor_project

Many thanks to you folks for provided snipets


1. Add to `http{` block:

```
map $host $harbor_project {
  default 0;
  ~^harbor.example.com$ 0;
  ~^(?<project>.+).example.com$ $project;
}

map "$harbor_project#$request_uri" $harbor_registry_uri {
  default $request_uri;
  "~^0#.*$" $request_uri;
  "~^.+#/v2/_catalog.*$" $request_uri;
  "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/([^/]+)(.*)$" /v2/$harbor_project/library/$1$2;
  "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
}

map $args $harbor_args{
  default $args;
  ~^(?<arg_prefix>.*scope=repository%3A)(?<arg_suffix>.*)$ $arg_prefix$harbor_project%2F$arg_suffix;
}

map $upstream_http_www_authenticate $harbor_authenticate_header {
  default $upstream_http_www_authenticate;
  ~^(?<header_prefix>.*http.+//).*(?<header_suffix>/service/token.*)$ $header_prefix$http_host$header_suffix;
}
```

2. Add to location `/v2/` block in the bottom:

```
rewrite ^/v2/(.+)$ $harbor_registry_uri break;
proxy_hide_header Www-Authenticate;
add_header Www-Authenticate $harbor_authenticate_header always;
```

3. Add to location `/service/` block in the bottom:

```
set $args $harbor_args;
```

many thanks to you folks for provided snippets! <3

**Comment by upics** [comment]
> The following is a further modification of @pedroosorio 's [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-1683724182) that adds the capability to bypass the mapping and rewriting process for certain domains.
> 
> I needed both transparent proxy caches and the ability to upload to other projects, but I had issues with the `/blobs/uploads` map pattern applying multiple times (probably because of a redirect somewhere), so I'd end up with the project name in the URI multiple times. With this change, I can instead exclude one of the domain names pointing to this Harbor instance, so when using that excluded domain, Harbor acts normally (without the rewrites and stuff for the transparent proxy cache).
> 
> Unfortunately I did have to use an `if` for the `rewrite` in the `location /v2/` block to get this to work. Someone better at NGINX than me could probably eliminate that `if`.
> 
> 1. Add to http{ block:
> 
> ```
>   map $host $harbor_project {
>     default 0;
>     ~^harbor.example.com$ 0;        # this is how to specify a domain name to exclude from processing
>     ~^(?<project>.+).example.com$ $project;
>   }
> 
>   map "$harbor_project#$request_uri" $harbor_registry_uri {
>     default $request_uri;
>     "~^0#.*$" $request_uri;
>     "~^.+#/v2/_catalog.*$" $request_uri;
>     "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
>     "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
>     "~^.+#/v2/([^/]+)(.*)$" /v2/$harbor_project/library/$1$2;
>     "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
>   }
>   
>   map "$harbor_project#$args" $harbor_args {
>     default $args;
>     "~^0#.*$" $args;
>     "~^.+#(?<arg_prefix>.*scope=repository%3A)(?<arg_suffix>.*)$" $arg_prefix$harbor_project%2F$arg_suffix;
>   }
>   
>   map "$harbor_project#$upstream_http_www_authenticate" $harbor_authenticate_header {
>     default $upstream_http_www_authenticate;
>     "~^0#.*$" $upstream_http_www_authenticate;
>     "~^.+#(?<header_prefix>.*http.+//).*(?<header_suffix>/service/token.*)$" $header_prefix$http_host$header_suffix;
>   }
> ```
> 
> 2. Add to location /v2/ block:
> 
> ```
>       if ($harbor_project) {
>         rewrite ^/v2/(.+)$ $harbor_registry_uri break;
>       }
>       proxy_hide_header Www-Authenticate;
>       add_header Www-Authenticate $harbor_authenticate_header always;
> ```
> 
> 3. Add to location /service/ block:
> 
> ```
>     set $args $harbor_args;
> ```

I have encountered the same problem as him. If you want to push to a non-proxy cache project using project.domain.example, something with /blob/uploads dont work. Anyone has resolved this issue ?

**Comment by yashid-mohamed** [comment]
Hi All, I am trying to setup NGINX reverse proxy which supports pulls for both docker images with the `library` prefix such as python, ubuntu etc and those images without at the same time. 

I tried the [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-2258660093) provided by @asdorsey and @kvaps. This works for docker images have the `library` prefix (default project) such python, ubuntu etc. However fails for images which belong to other projects, for example -  `grafana/loki` or `kumahq/kuma-dp` since the rules rewrite the uri with `library/`

```
$ docker pull dockerhub-proxy.example.com/grafana/loki
Using default tag: latest
Error response from daemon: unknown: repository dockerhub-proxy/**library**/grafana/loki not found
```

If I use the [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-1683724182) provided by @pedroosorio , this only works for images that do not have the `library` prefix such as `grafana/loki` but fails to work for those that do like `ubuntu` or `python`.

```
$ docker pull dockerhub-proxy.example.com/nginx:latest
Error response from daemon: unknown: repository dockerhub-proxy/**dockerhub-proxy**/library/nginx not found
```

Has anyone managed to get a working solution which supports pulling of both these types of images?

**Comment by yashid-mohamed** [comment]
Managed to get it working for both with @pedroosorio's [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-1683724182) by updating the second map as follows.

Note: replace `dockerhub-proxy` in the map with the name of your harbor project.

```
map "$harbor_project#$request_uri" $harbor_registry_uri {
  default $request_uri;
  "~^0#.*$" $request_uri;
  "~^.+#/v2/dockerhub-proxy/([^?]+)(.*)$" $request_uri;
  "~^.+#/v2/_catalog.*$" $request_uri;
  "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
  "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
}
```

> Hi All,
> 
> I am trying to setup NGINX reverse proxy which supports pulls for both types of docker images at the same time
> 
> 1. Images with the `library` prefix such as python, ubuntu etc.
> 2. Images which do not have the `library` prefix i.e. that belong to other projects, such as `grafana/loki` .
> 
> The [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-2258660093) provided by [@asdorsey](https://github.com/asdorsey) and [@kvaps](https://github.com/kvaps) works fine for docker images having the `library` prefix such as nginx, python, ubuntu etc. However it fails for images which belong to other projects, for example - `grafana/loki` or `kumahq/kuma-dp` since the rules rewrite the uri with `library/`
> 
> ```
> $ docker pull dockerhub-proxy.example.com/grafana/loki
> Using default tag: latest
> Error response from daemon: unknown: repository dockerhub-proxy/library/grafana/loki not found
> ```
> 
> The [solution](https://github.com/goharbor/harbor/issues/8082#issuecomment-1683724182) provided by [@pedroosorio](https://github.com/pedroosorio) , only works for images that do not have the `library` prefix such as `grafana/loki` but fails to work for images that do, like `nginx`,`python` etc.
> 
> ```
> $ docker pull dockerhub-proxy.example.com/nginx:latest
> Error response from daemon: unknown: repository dockerhub-proxy/dockerhub-proxy/library/nginx not found
> ```
> 
> Has anyone managed to get a working solution which supports pulling of both these types of images or can provide any hints to update the rules to support this?
> 
> Thanks!

**Comment by dhpagani** [comment]
Thank you all for your snippets!

I have several projects on Harbor, one of which is a DockerHub cache. This requires authentication for pulling and pushing private containers while allowing public pulls from dockerhub-cache.

The solution provided by @pedroosorio, along with @yashid-mohamed's consideration, made the registry mirror work. However, I still couldn't push and pull for other projects. Since the approach used here relies on two DNS entries, I duplicated the Nginx configuration—copying the entire server{} block. One block uses the server_name of the first domain, while the other is assigned to the second DNS entry.

From Nginx's perspective, this results in two separate services with distinct domains and configurations, preventing them from overlapping and eliminating the need for multiple conditional statements inside the Nginx config.

I'm sure that someone with a deeper understanding of Nginx could make it work with a single server{} entry! :-)

**Comment by zzswang** [comment]
> If anybody has issues with their non-nginx-based ingress controller, welcome to this [simple chart](https://github.com/hiddenmarten/harbor-project-proxy).
> 
> Thanks for the inspiration: [@pedroosorio](https://github.com/pedroosorio), [@jgallucci32](https://github.com/jgallucci32) and [@ricardojdsilva87](https://github.com/ricardojdsilva87)

It works!

**Comment by kugarocks** [comment]
To support the following styles:

```bash
docker pull redis
docker pull library/redis
docker pull fluent/fluent-bit
docker pull harbor.example.com/redis
docker pull harbor.example.com/library/redis
docker pull harbor.example.com/fluent/fluent-bit
```

Try this:

```nginx
  map "$harbor_project#$request_uri" $harbor_registry_uri {
    default $request_uri;
    "~^0#.*$" $request_uri;
    "~^.+#/v2/_catalog.*$" $request_uri;
    "~^.+#/v2/(.+)(/tags/list.*)$" /v2/$harbor_project/$1$2;
    "~^.+#/v2/(.+)(/blobs/uploads.*)$" /v2/$harbor_project/$1$2;
    "~^.+#/v2/([^/]+)(/manifests/.*)$" /v2/$harbor_project/library/$1$2;
    "~^.+#/v2/([^?]+)(.*)$" /v2/$harbor_project/$1;
  }
```

**Comment by ricardojdsilva87** [comment]
Hello everyone,
We relied on an heavy nginx configuration like the ones mentioned above to proxy the requests correctly since Harbor needs to have the `/v2/proxycacheprojectname` in the requested URL and the docker.io requests don't have that.
By just modifying the containerd configuration to have the entire URL with those additions we can remove the nginx as the middle man and just rely on the containerd configuration.
The original post is here:
https://github.com/goharbor/harbor/issues/21342#issuecomment-3581730511
