### ISSUE TITLE
UI Modification: When New Robot

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#8083]
When we add some permissions to the new robot Account, we can get the following pages by communicating with the design.

![image](https://user-images.githubusercontent.com/29826789/59814608-7a485580-9348-11e9-9f24-3ffb00a86967.png)

**Comment by AllForNothing** [comment]
There is some modification for creating robot account UI.
New mockups : <https://vmware.invisionapp.com/share/RKOJ1Q83XNS#/340476661_v1-8_-_Robot_Accounts>
