### ISSUE TITLE
unable to docker login harbor

### ISSUE THREAD

**Issue by bonniechen1119** [goharbor/harbor#8088]
1.install harbor in aws cloud, and then can login in web however when docker login, it fail
when I try login harbor.miotech.com:5000, it return 401
docker login harbor.miotech.com:5000
Username: admin
Password:
Error response from daemon: login attempt to https://harbor.miotech.com:5000/v2/ failed with status: 401 Unauthorized

when I try login harbor.miotech.com, it return TLS timeout
docker login harbor.miotech.com
Username: admin
Password:
Error response from daemon: Get https://harbor.miotech.com/v2/: net/http: TLS handshake timeout

And when I check server registry log, it display:
Jun 20 09:45:39 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: time="2019-06-20T09:45:39.007995097Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=7787a749-0b4f-4473-8481-32d709f4d270 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.48.7:57178" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
Jun 20 09:45:49 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: 192.168.48.7 - - [20/Jun/2019:09:45:49 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Jun 20 09:45:49 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: time="2019-06-20T09:45:49.006510685Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=19682172-d990-403b-b959-4dacead39ad1 http.request.method=GET http.request.remoteaddr="192.168.48.7:57190" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="103.442µs" http.response.status=301 http.response.written=39
Jun 20 09:45:49 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: 192.168.48.7 - - [20/Jun/2019:09:45:49 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
Jun 20 09:45:49 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: time="2019-06-20T09:45:49.00817418Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=d8349b54-3da8-4748-86f3-693ba1cafab1 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.48.7:57190" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
Jun 20 09:45:58 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: 127.0.0.1 - - [20/Jun/2019:09:45:58 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Jun 20 09:45:59 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: 192.168.48.7 - - [20/Jun/2019:09:45:59 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Jun 20 09:45:59 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: time="2019-06-20T09:45:59.006596719Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=c4f31168-6ffd-4f37-8159-577c6e2e09f7 http.request.method=GET http.request.remoteaddr="192.168.48.7:57206" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="75.539µs" http.response.status=301 http.response.written=39
Jun 20 09:45:59 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: time="2019-06-20T09:45:59.007690709Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=f0844af7-2504-4769-b510-fff2f7092699 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.48.7:57206" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
Jun 20 09:45:59 ip-192-168-48-1.ap-east-1.compute.internal registry[2887]: 192.168.48.7 - - [20/Jun/2019:09:45:59 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"

**Comment by bitsf** [comment]
@bonniechen1119  This seems strange. Can this be reproduced?
How did you install the harbor?
Which version?
What did you change in harbor.yml?
What OS are you using?

**Comment by bonniechen1119** [comment]
Already solve this issue

**Comment by catchups** [comment]
> Already solve this issue

I have same problem. How did you sovle?

**Comment by sakshirathorebgw** [comment]
> Already solve this issue

HOw did you solve this issue ?

**Comment by zsyubo** [comment]
I also encountered this problem, which was solved by redeploying harbor, using the install
