### ISSUE TITLE
delete replication occur error and pending

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#8089]
**Expected behavior and actual behavior:**
I run a script to delete old images on the master harbor instance and the slave instance will execute delete replication. But a strange thing often occur at some time: the delete replication pending from one moment until I restart the job-service container on the master harbor. I think maybe it is related to the issue https://github.com/goharbor/harbor/issues/6515.
![image](https://user-images.githubusercontent.com/9589048/59840410-dc26b080-9384-11e9-9033-320d650dc5a9.png)

**Steps to reproduce the problem:**
Not very clear. It is not occur everytime.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.1
- docker engine version: 1.12.6
- docker-compose version: 1.13.0

Here is the log that I think maybe useful.
the jobservice.log on the master harbor, many 500 error:
![image](https://user-images.githubusercontent.com/9589048/59840156-63bfef80-9384-11e9-9f4a-b589d8556050.png)

the registry.log on the slave harbor for the same tag above, seems normal:
![image](https://user-images.githubusercontent.com/9589048/59840237-881bcc00-9384-11e9-8512-2a734fb6478f.png)

**Comment by louyiping** [comment]
Could someone help me please? @reasonerjt  Let me known if the information is not enough, thanks.

**Comment by bitsf** [comment]
@louyiping Can you have a try on 1.8.1?

**Comment by ywk253100** [comment]
The `pending` issue is fixed in 1.8. Please upgrade your Harbor to the latest version.

**Comment by louyiping** [comment]
Okay. Thanks.
