### ISSUE TITLE
Distributed tracing should be supported

### ISSUE THREAD

**Issue by hzpfly** [goharbor/harbor#8092]
# What can we help you?
Can we add Distributed tracing feature to harbor?
# Distributed tracing
Distributed tracing, also called distributed request tracing, is a method used to profile and monitor applications, especially those built using a microservices architecture. Distributed tracing helps pinpoint where failures occur and what causes poor performance.
# OpenTracing
OpenTracing is comprised of an API specification, frameworks and libraries that have implemented the specification, and documentation for the project. OpenTracing allows developers to add instrumentation to their application code using APIs that do not lock them into any one particular product or vendor.
# CNCF Jaeger
Jaeger \ˈyā-gər\ is a distributed tracing system, originally open sourced by Uber Technologies. It provides distributed context propagation, distributed transaction monitoring, root cause analysis, service dependency analysis, and performance / latency optimization. Built with OpenTracing support from inception, Jaeger includes OpenTracing client libraries in several languages, including Java, Go, Python, Node.js, C++ and C#. It is a Cloud Native Computing Foundation member project.
# References:
1. [What is tracing](https://opentracing.io/docs/overview/what-is-tracing/)

**Comment by steven-zou** [comment]
@hzpfly 

Thank you for raising the requirement to Habor. We have already known your requirement and put it into our backlog. Let's see if we can plan it in the future. Please keep tuned.

**Comment by finkr** [comment]
For the record (and googlers), there was two competing standards (OpenCensus and OpenTracing) which are now [merged](https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289) as [opentelemetry.io](http://opentelemetry.io)

**Comment by tianon** [comment]
For any folks looking to follow along, this has an official proposal over in https://github.com/goharbor/community/pull/171.
