### ISSUE TITLE
v1.8.1 磁盘使用容量监控面板显示错误

### ISSUE THREAD

**Issue by YLzone** [goharbor/harbor#8125]
harbor UI 右上角容量剩余显示不准确。
![image](https://user-images.githubusercontent.com/17042217/59958620-4e5dd900-94dc-11e9-9991-3cac7a595edb.png)

**Comment by Ghostbaby** [comment]
这个指标只有使用本地存储才显示，数据存储分区的容量使用情况，可以df看下是不是信息一致，或者提供下df的信息。

**Comment by YLzone** [comment]
问题已经解决，是我理解有误。我开始以为这53是百分比，实际它是53GiB。
