### ISSUE TITLE
how to compile harbor source code for ARM arch OS?

### ISSUE THREAD

**Issue by YanLemon** [goharbor/harbor#8127]
What can we help you?

**Comment by bitsf** [comment]
We haven't tried that, and don't have such device yet, maybe community can give some brief help on how to bootstrap

**Comment by YanLemon** [comment]
@stonezdj thank you . how to compile the source code? I want to intall harbor on ARM.

**Comment by bitsf** [comment]
install golang environment, and docker docker-compose, and edit hostname to your ip in make/harbor.yaml
run make all
if all good, it will start up a harbor service.

I'm not sure whether anything else need to install on ARM yet, maybe build-essential.

You can give more log later.

**Comment by YanLemon** [comment]
@bitsf Thank you. My OS is ARM. I can install docker-compose using pip on ARM OS. When I try make harbor on ARM ,I'll give you logs.     I want to compile the harbor code to make a harbor install package.

**Comment by bitsf** [comment]
@YanLemon how about this going, succeed or no?

**Comment by Liu-Richard** [comment]
I am tring  compile  harbor source code on ARM64 （CentOS7.6）,  connect error occures when I  make all , I set the /etc/sysconfig/proxy and /etc/resolv.conf  correctly. any suggestion? thanks

[root@ceph1 harbor]# make all

Note: golang version: 1.11.5

Note: docker version: 18.03.1

Note: docker-compose version: 1.25.0
compiling binary for core (golang image)...
/harbor
Done.
compiling binary for jobservice (golang image)...
Done.
compiling binary for harbor registry controller (golang image)...
Done.
compiling binary for migrate patch (golang image)...
Done.
make -f /harbor/make/photon/Makefile build -e DEVFLAG=true \
 -e REGISTRYVERSION=v2.7.1-patch-2819 -e NGINXVERSION=dev -e NOTARYVERSION=v0.6.1 -e NOTARYMIGRATEVERSION=v3.5.4 \
 -e CLAIRVERSION=v2.0.8 -e CLAIRDBVERSION=dev -e VERSIONTAG=dev \
 -e BUILDBIN=false -e REDISVERSION=dev -e MIGRATORVERSION=dev \
 -e CHARTMUSEUMVERSION=v0.8.1 -e DOCKERIMAGENAME_CHART_SERVER=goharbor/chartmuseum-photon
make[1]: Entering directory `/*****/bigdata/harbor'
building prepare container for photon...
Sending build context to Docker daemon  274.1MB
Step 1/10 : FROM photon:3.0
3.0: Pulling from library/photon
Digest: sha256:d8216007ea3f36c28e9cbb7df8b576a3ceadff9a31a9dc583abe0d24afb4e098
Status: Image is up to date for photon:3.0
 ---> 0cf1ed9d6e3b
Step 2/10 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> ab7617cc1f53
Step 3/10 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 5b250d0f7f5c
Step 4/10 : RUN mkdir -p /harbor_make
 ---> Using cache
 ---> f4540abef573
Step 5/10 : RUN tdnf install -y python3     && tdnf install -y python3-pip
 ---> Running in c55dd85cd240
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_aarch64'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_aarch64'
Error(1011) : No matching packages
Refreshing metadata for: 'VMware Photon Extras 3.0(aarch64)'
Disabling Repo: 'VMware Photon Extras 3.0(aarch64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64) Updates'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64) Updates'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64)'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64)'
No package python3 available
The command '/bin/sh -c tdnf install -y python3     && tdnf install -y python3-pip' returned a non-zero code: 243
make[1]: *** [_build_prepare] Error 243
make[1]: Leaving directory `/***/harbor'
make: *** [build] Error 2

**Comment by bitsf** [comment]
This error seems just a network problem, can you try to 'ping dl.bintray.com' or 'curl -L https://dl.bintray.com/vmware/photon_extras_3.0_aarch64 -O' from your device to see if this url can be downloaded.

BTW, the compile for harbor source are successful now. I think it almost can be startup now.

**Comment by Liu-Richard** [comment]
It was solved by setting ENV http_proxy in Dockerfile.thanks

**Comment by congweitao** [comment]
My aarch64 platform has 64K system page size, and it seems redis does not support this size of system parameter. How can I change the settings of redis before compiling harbor? Actually. I  am a newer to Harbor,

**Comment by bitsf** [comment]
we're just use the redis release, not sure if this file can help
make/photon/redis/Dockerfile
maybe you can try directly use redis from dockerhub
