### ISSUE TITLE
Unable to install Harbor with Docker SELinux enabled

### ISSUE THREAD

**Issue by rvanbutselaar** [goharbor/harbor#8129]
**Expected behavior and actual behavior:**
Unable to install Harbor with Docker SELinux enabled

**Steps to reproduce the problem:**

1. Enable Docker SELinux `/usr/bin/dockerd --selinux-enabled=true -H fd:// --containerd=/run/containerd/containerd.sock`
2. Restart docker
3. Run installer
```
[root@harbor1 harbor]# ./install.sh

[Step 0]: checking installation environment ...

Note: docker-compose version: 1.24.0

Note: docker version: 18.09.6


[Step 1]: preparing environment ...
prepare base dir is set to /data/harbor-install/harbor
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 30, in main
    delfile(config_dir)
  File "/usr/src/app/utils/misc.py", line 96, in delfile
    for item in os.listdir(src):
PermissionError: [Errno 13] Permission denied: '/config'
```

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.1
- docker engine version: 18.09.6
- docker-compose version: 1.24.0

**Additional context:**

Can be fixed by adding `:z` at the end of each volume mount inside the `prepare` bash script:

```
docker run --rm -v $input_dir:/input:z \
                    -v $harbor_prepare_path:/compose_location:z \
                    -v $config_dir:/config:z \
                    -v $secret_dir:/secret:z \
                    goharbor/prepare:v1.8.1 $@
```

**Comment by bitsf** [comment]
I didn't reproduce this on Ubuntu 18.04.2, maybe SELinux is not same.
@rvanbutselaar what OS are you using

**Comment by rvanbutselaar** [comment]
I'm using RHEL 7.6. SELinux is probably not enabled for Docker on Ubuntu. You should be able to verify this with: `sudo docker info | grep selinux`

**Comment by bitsf** [comment]
yes, selinux is not enabled in my box.
And this fix is no problem on my ubuntu.

@rvanbutselaar  Would you like submit a PR with this patch to fix file "make/prepare"?

**Comment by rvanbutselaar** [comment]
Created the PR: #8171
