### ISSUE TITLE
Failed to add chart repository with helm when OIDC is enabled (bug still active)

### ISSUE THREAD

**Issue by loosi** [goharbor/harbor#8130]
following up on #7625 

**Expected behavior and actual behavior:**
Helm push should work with OIDC Cli Secret

**Steps to reproduce the problem:**
helm push redmine-9.1.0.tgz https://mru:4b01foduqa.....@registry.company/chartrepo/library

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.1]
- docker engine version: [18.09.3]
- docker-compose version: [1.24.0]

**Additional context:**
Docker login with cli secret works
```
echo 4b01foduqa..... | docker login --username mru --password-stdin https://registry.company
Login Succeeded
```
helm push with cli secret won't work
```
helm push redmine-9.1.0.tgz https://mr:4b01foduqa.....@registry.company/chartrepo/library
Error: 401: could not properly parse response JSON: {"code":401,"message":"Unauthorized"}
[ERROR] [/core/filter/security.go:471]: failed to authenticate mru: Unrecognized auth_mode: oidc_auth
[ERROR] [/common/api/base.go:69]: POST /api/chartrepo/library/charts failed with error: {"code":401,"message":"Unauthorized"}
```

Anything else to do with Helm push here? I've tried using helm push following the manual (https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#working-with-helm-cli), but no matter what method : always 401

**Comment by reasonerjt** [comment]
should it be `mru` in your helm command?

**Comment by loosi** [comment]
It is the same username, its just shortened to hide it here

**Comment by cafeliker** [comment]
I got the same 401 error with OIDC enabled.

**Comment by reasonerjt** [comment]
Thanks for reporting @loosi @cafeliker 

Root cause is that the `helm push` is using a different api prefix from `helm fetch` so the OIDC filter skipped the request of uploading a chart.

Sorry for the inconvenient, for now please workaround by using the UI to upload the chart

**Comment by lassehoj** [comment]
Hi, when can we expect a release with this fix included?

**Comment by reasonerjt** [comment]
@lassehoj we'll try to tag a release before end of July

**Comment by cafeliker** [comment]
@reasonerjt I tested with the fix, but the issue was still there, pls see the attached log file.

Thanks
ye 
[chartmuseum.zip](https://github.com/goharbor/harbor/files/3395708/chartmuseum.zip)

**Comment by lassehoj** [comment]
@reasonerjt sounds good. I'm not sure if the fix will be enough for us, though.

Our use case is distributing ImagePullSecrets into various clusters. Since robot account tokens expire after 30 days we need an automatic way to issue new tokens, or alternatively create robot accounts via the API. We went for the last approach, but OIDC users cannot create robot accounts via the API - only via the UI which seems to be an arbitrary limitation.

So ideally we would need OIDC user to be able to use *all* of /api/ and not just chartrepo and docker registry.

Thanks,
Lasse

**Comment by cafeliker** [comment]
@reasonerjt it's our fault, our engineer didn't deploy the right version. After redeploy the fix version, it pass my tests on helm push.

Thanks again
ye

**Comment by Sushama-pan** [comment]
I am still getting Error: 401: could not properly parse response JSON: {"code":401,"message":"UnAuthorized"} while helm push.
helm version:3
push plugin version:0.8.1

Thanks,
Sushama
