### ISSUE TITLE
allow setting different s3 bucket for chartserver

### ISSUE THREAD

**Issue by k0da** [goharbor/harbor#8136]
It would be nice to to have a chartmuseum bucket separated from registry storage config, that would allow us to ease migration  already existing chart storage into harbor's chart museum.

Thanks

**Comment by bitsf** [comment]
This seems a good idea.

**Comment by wy65701436** [comment]
hi, since the chartmuseum is planned to be removed from v2.8, please try with oci compatible charts which will share the storage with other kinds of artifact.
