### ISSUE TITLE
User in LDAP group not able to pull/push

### ISSUE THREAD

**Issue by joshisagar92** [goharbor/harbor#8138]
We have added a LDAP group with certain number of users in Harbor group.
Then added a group in member section of project with permission Admin.

When I tried to pull an image from the project, after login, with user which is already exist in added group.
It throws following error.

> Error response from daemon: pull access denied for  ip/***/**, repository does not exist or may require 'docker login'.

If I add specific users as a member of project it will work but with only group it is not working.

Can you please assist us?
Thanks.

**Comment by stonezdj** [comment]
Please check memberof overlay is enabled in your LDAP server.
https://github.com/goharbor/harbor/blob/fb28b113017a66996d7539e0815a1f3c89908c72/docs/manage_role_by_ldap_group.md

**Comment by reasonerjt** [comment]
any update?

**Comment by stonezdj** [comment]
Closed because of no response

**Comment by yuan1238y** [comment]
Hello. I found out the same issue.
My LDAP server is Windows AD. I affirm memberof overlay is enabled.
