### ISSUE TITLE
pushing an image to repository does not update update_time

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#8140]
pushing an image to repository does not update update_time
Harbor version: 1.8.0
while pushing a new image to a repository the update_time of the repository is not updated.
wondering if its a bug or that's how it works.
if not, which operation does update the update_time?

[
    {
        "id": 16233,
        "name": "test/test1",
        "project_id": 6,
        "description": "",
        "pull_count": 25,
        "star_count": 0,
        "tags_count": 3,
        "labels": [],
        "creation_time": "2019-01-15T16:21:17.457472Z",
        **"update_time": "2019-06-24T20:46:13.725868Z"**
    },

**Comment by bitsf** [comment]
This seems reasonable to update the update_time.
But I'm not sure whether this is easy to implement, because
1. docker push operation is directly contact with backend registry, we need to intercept the request
2. docker push may failed, while we should just intercept the succeed operation
