### ISSUE TITLE
User can not login when they are switching from different ldap_uid field

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8142]
In LDAP there is an user with ldap_uid=uid0001,cn=mike,email=mike@example.com
When I configure to use ldap_uid field to cn
and login with username: mike
Then I switch to ldap_uid field to email or uid.
and login with uid
uid0001
It failed to login with the uid0001, because there is a user existing in harbor_user with email mike@example.com.
We need to find a way to cleanup the imported users when configuration is changed.

**Comment by reasonerjt** [comment]
Is there a workaround for this?  I don't think there's a quick solution maybe we need a table for each backend like we did for OIDC.

**Comment by reasonerjt** [comment]
Generally speaking, if we onboard a few users with one ldap setting, and switch to another, similar problem may happen.

**Comment by stonezdj** [comment]
The workaround: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication

**Comment by stonezdj** [comment]
We could delete current user in Harbor and login again
