### ISSUE TITLE
Harbor does not show "Creation Time" in Portuguese

### ISSUE THREAD

**Issue by paulohleal** [goharbor/harbor#8143]
**Expected behavior and actual behavior:**
When I change the language to "Português do Brasil" the field "Data de criação" ("Creation Time" in English) is empty. When I turn back to English it comes filled.
It happens on Projects screen and Repositories screen. 

**Steps to reproduce the problem:**
Change the language to "Português do Brasil"

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0]
- docker engine version: [18.09.6]
- docker-compose version: [1.23.2]
![image](https://user-images.githubusercontent.com/23530311/60119173-309aa900-9754-11e9-8214-94cb1c308f51.png)
![image](https://user-images.githubusercontent.com/23530311/60119223-4ad48700-9754-11e9-8423-862cb77785e1.png)

![image](https://user-images.githubusercontent.com/23530311/60119247-5aec6680-9754-11e9-97d8-73b32a9c2de9.png)
![image](https://user-images.githubusercontent.com/23530311/60119275-6cce0980-9754-11e9-8f01-ff7951e524c4.png)

**Comment by paulohleal** [comment]
Just checked that the Logs, User and Garbage Collection´s History screens have the same problem showing dates.

**Comment by reasonerjt** [comment]
non-english labels are maintained by community, any help is welcome.

**Comment by bitsf** [comment]
In environment I didn't see anything error with language "Português do Brasil"
![image](https://user-images.githubusercontent.com/188115/60158433-b20d3c80-9823-11e9-920b-8459976e2940.png)

@paulohleal what browser are you using? And can you try to refresh your browser cache? And if you are using Chrome, you can also check the Dev Tool whether there's anything wrong in Console.
![image](https://user-images.githubusercontent.com/188115/60158838-758e1080-9824-11e9-99ac-b69befbc5a08.png)

And you can also provide the network data, that we can see if it's related to a particular time.
![image](https://user-images.githubusercontent.com/188115/60158999-c7369b00-9824-11e9-99a9-b2d0e201c6f8.png)

**Comment by paulohleal** [comment]
I am running on chrome. On console I´ve found an error:
![image](https://user-images.githubusercontent.com/23530311/60192925-25578400-980d-11e9-86e9-34a3021319e8.png)

**Comment by bitsf** [comment]
@jwangyangls @AllForNothing Do you know about this ui error

**Comment by bitsf** [comment]
@paulohleal Does other non-english language have similar problem?

**Comment by paulohleal** [comment]
Every other language works fine.

**Comment by bitsf** [comment]
@paulohleal What's the version of your Chrome? What OS are you using? And what language of the OS are you using?
Have you tried clean the browser cache? it seems some web page is not fully loaded.

**Comment by paulohleal** [comment]
Chrome version: 73.0.3683.75 (32 bits)
Browser os -> Windows 7
Harbor OS -> "Oracle Linux Server" 7.5
Windows language -> Portuguese (Brazil)
Linux language -> English (US)

I have cleaned the cache. It also happens on others computers.

**Comment by AllForNothing** [comment]
@paulohleal Thanks for you feedback. We've solved this problem at the subsequent version. Please wait for the new harbor version. If needed, update yours.
