### ISSUE TITLE
Harbor scheduled replication not run as plan

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8145]
**Expected behavior and actual behavior:**
We want to run replication job every 5 minutes, but the job is randomly delayed too much.

**Steps to reproduce the problem:**
1. create a replication job with cron schedule "0 */5 * * * *"

**Versions:**
- harbor version: [1.8.1]
- docker engine version: [18.09.2]
- docker-compose version: [1.21.0]

**Additional context:**
![image](https://user-images.githubusercontent.com/188115/60145804-cfc5ac00-97f9-11e9-97e7-38cc3ad3460f.png)
![image](https://user-images.githubusercontent.com/188115/60145819-d5bb8d00-97f9-11e9-9a20-8267d600681b.png)

**Comment by steven-zou** [comment]
Code merged, close the issue.
