### ISSUE TITLE
Latest log missed in harbor log files

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8147]
Sometimes the harbor doesn't dump the latest log to the log files, we noticed that when user login failed, there is no latest log for today, just saw the log in 1 day before. It is difficult to diagnostic when there is no latest log dumped. 
Because both the core.log and proxy.log were not updated with latest log entry,  it could be an issue related to harbor-log container.

**Comment by bitsf** [comment]
Does anyone else have similar problems?

**Comment by reasonerjt** [comment]
Last time I saw a similar issue is due to disk shortage, let's keep this open and see if we can see this happen again.

**Comment by stonezdj** [comment]
Close, did not see it again
