### ISSUE TITLE
能否提供下各版本数据库中存的元数据信息

### ISSUE THREAD

**Issue by fyqls** [goharbor/harbor#8148]
我想将v1.1.1升级到v1.8.1． docker镜像本身我们自己搞定．
能否提供v1.1.1的数据库表信息和v1.8.1的数据库表信息．我这边手动将用户信息和project信息迁移

**Comment by bitsf** [comment]
make/migrations/postgresql/中包含了升级时执行的sql

**Comment by fyqls** [comment]
感谢，已经手动迁移用户表和权限表，以及project表了
