### ISSUE TITLE
Harbor with this error  "filesystem layer verification failed for digest " 

### ISSUE THREAD

**Issue by zhaowencheng1991** [goharbor/harbor#8149]
When I pull a image，I can get this error "filesystem layer verification failed for digest" randomly, I try to search this error with google and get some solutions to this  problem
1. delete this image 
2.rebuild with --no-cache
3.repush 
4.pull again  -- ok 

But what is the real reason for this problem?  registry  ceph  network or the "build client"

versions:
1. harbor v1.7.1
2.registry v2.6.2 
3.ceph version 13.2.4

Who can  help me ,Thanks

**Comment by bitsf** [comment]
This seems some kind of bug of docker registry or storage.
Maybe the file is not synced on disk.
We may not give an answer here.

Has anyone else come across this case?

**Comment by zhaowencheng1991** [comment]
@bitsf  Thank you
