### ISSUE TITLE
Proper issue handling on Bad Request

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#8153]
What can we help you?

Dear Team
Can you please handle and show proper message on Bad Request from API?

Harbor Version : 1.8.0
Use Case : Add a non-existing user to existing project.
API Response :  **{"code":400,"message":"Failed to add project member, error: User does not exist"}**
UI Response :  
![image](https://user-images.githubusercontent.com/8274052/60177409-7891fc80-9836-11e9-923d-eba3c3a95ac7.png)

I guess there should not be a 400 if user does not present in the system.

Thanks & Regards
Sandeep Arsule

**Comment by arsulesandy** [comment]
The same happen with wrong helm chart upload request.

![image](https://user-images.githubusercontent.com/8274052/60177547-c870c380-9836-11e9-82ae-1a8f89402b7c.png)

**Comment by jwangyangls** [comment]
@arsulesandy   We have fixed it in branch master. and the scope of inclusion is so big, together with a technology stack update, you can use the master branch code.

**Comment by arsulesandy** [comment]
@jwangyangls thank you for quick information. Could you please give some hint as from where can I start contributing on such UI related topics.

**Comment by jwangyangls** [comment]
@arsulesandy add-member.component, helm-chart.component
