### ISSUE TITLE
Error when working in mirror mode

### ISSUE THREAD

**Issue by SaymonPhoenix** [goharbor/harbor#8160]
When operating the harbor in mirror mode, customers can download images of the following type:
docker pull hello-world
Using default tag: latest
latest: Pulling from library / hello-world
1b930d010525: Pull complete
Digest: sha256: 41a65640635299bab090f783209c1e3a3f11934cf7756b09cb2f1e02147c6ed8
Status: Downloaded newer image for hello-world: latest

But when you try to download from the public registry download does not occur.
docker pull goharbor/chartmuseum-photon: v0.8.1-v1.8.1
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 197.4.7.7.7:53: no such host

docker v18.09.6
docker-compose v1.24.0
harbor v1.8.1

**Comment by SaymonPhoenix** [comment]
update
Until a project is created goharbor, you can't do 
docker pull goharbor/chartmuseum-photon: v0.8.1-v1.8.1

**Comment by reasonerjt** [comment]
This is expected, Harbor does not support running in mirror mode.
