### ISSUE TITLE
nginx bind() to 0.0.0.0:80 failed

### ISSUE THREAD

**Issue by zhaoshibao** [goharbor/harbor#8163]

**Comment by zhaoshibao** [comment]
![123](https://user-images.githubusercontent.com/52303327/60311146-8bb4e180-9988-11e9-984c-4ac65efd46aa.png)
![456](https://user-images.githubusercontent.com/52303327/60311180-b3a44500-9988-11e9-8d3b-afde5c7dcd8a.png)

**Comment by reasonerjt** [comment]
There should be another process bound the 80 port.

**Comment by zhaoshibao** [comment]
thank you






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"stale[bot]"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 中午11:37
收件人:&nbsp;"goharbor/harbor"<harbor@noreply.github.com&gt;;
抄送:&nbsp;"501348474"<501348474@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goharbor/harbor] nginx bind() to 0.0.0.0:80 failed (#8163)



Closed #8163.
