### ISSUE TITLE
Support SAML in Harbor

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8164]

**Comment by reasonerjt** [comment]
@michmike are you talking about supporting SAML via UAA?

**Comment by michmike** [comment]
@reasonerjt  that's one option (UAA with SAML). the other is supporting UAA via OIDC and seeing if that works. what do you think is the best approach?

**Comment by reasonerjt** [comment]
I think the better approach is:
Harbor <-> OIDC <-> SAML
And I believe this is already supported.

The work in Harbor tile is for configuring UAA as a standard OIDC endpoint when it's connected with SAML.

**Comment by michmike** [comment]
got it. i will close this request @reasonerjt
