### ISSUE TITLE
Order by tag does not sort properly

### ISSUE THREAD

**Issue by mxplusb** [goharbor/harbor#8166]
**Expected behavior and actual behavior:**

I expect ordering to sort properly. The sort order should be:

* latest
* v0.0.106
* v0.0.103
* v0.0.91
* etc

![image](https://user-images.githubusercontent.com/7537841/60316699-eae30980-9928-11e9-9d32-153baee89f69.png)

**Steps to reproduce the problem:**

Create a mixed variant of string and numerical tags, then click the "Tag" button to order them.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.8.1-16b59c41
- docker engine version: 18.09.3
- docker-compose version: 1.23.2, build 1110ad01

**Additional context:**

None, mostly UI related.

**Comment by reasonerjt** [comment]
I believe the sort is based on string

**Comment by zhoumeina** [comment]
@mxplusb , this is sort by string. Please use 0.0.106 and 0.0.107. It will be correct. thanks.

**Comment by mxplusb** [comment]
> Please use 0.0.106 and 0.0.107. It will be correct. thanks.

No, I don't think I will. Proper semantic versions as is widely accepted by the industry leverages the `v` prefix. Telling your user to change the way they follow an industry standard because you aren't interested in leveling up your sorting methodology isn't a great user experience.

**Comment by reasonerjt** [comment]
@mxplusb 
Could you give us an example (project or product) that sorts column as you described so we can talk to the upstream UI library developer to change the behavior?

**Comment by reasonerjt** [comment]
Let's enable the sorting based on "push time" that should solve user's real problem.

**Comment by jwangyangls** [comment]
I have it fix it in harbor 1.9.0(Increased sorting by pull time, push time, create time)
