### ISSUE TITLE
API tag search by lable not works

### ISSUE THREAD

**Issue by Kirill-SDS** [goharbor/harbor#8170]
Hello, 
I try to filter ropositories tags by labels
here is examples of my requests
`curl` -X GET "https://hub.example.com/api/repositories/plant-v1/tags?label_ids=1" `

and also with multiple labels
`curl -X GET "https://hub.example.com/api/repositories/plant-v1/tags?label_ids=1%2C2%2C3" `

All labels set in a global level

Unfortuntately  i receive response with tags which have any label, not only requested as expected

Harbor Version v1.8.1-16b59c41

**Comment by bitsf** [comment]
try use label_id
