### ISSUE TITLE
OIDC user login Harbor failed, Harbor returned HTTP 500 error, Dex returned keys rotated.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8177]
In nightly UI test, OIDC test case “OIDC User Sign In” failed occasionally, harbor return HTTP 500 error.

![image](https://user-images.githubusercontent.com/44018302/60415940-2fafbe80-9c0f-11e9-81a9-325e9208d1e5.png)
 
![image](https://user-images.githubusercontent.com/44018302/60415660-55889380-9c0e-11e9-90a5-3cec9a532c45.png)

**Log from  Harbor:**
    Jun 30 13:46:25 172.18.0.1 core[6748]: 2019-06-30T20:46:25Z [ERROR] [/common/api/base.go:229]: failed to verify signature: failed to verify id token signature
Jun 30 13:46:25 172.18.0.1 core[6748]: 2019-06-30T20:46:25Z [ERROR] [/common/api/base.go:69]: GET /c/oidc/callback?code=xp6vzqddsuppqltuxm6ls5hri&state=jwq6xxghxmal9u8t1zvxfoc3e8w6cgfc failed with error: {"code":500,"message":"Internal Server Error"}
Jun 30 13:46:25 172.18.0.1 core[6748]: 2019/06/30 20:46:25 #033[1;44m[D] [server.go:2774] |     172.18.0.1|#033[41m 500 #033[0m|  32.747036ms|   match|#033[44m GET     #033[0m /c/oidc/callback   r:/c/oidc/callback#033[0m
J

**Log from  Dex:**
Jun 30 13:45:43 harborci-oidc-dex dex[3541]: time="2019-06-30T20:45:43Z" level=info msg="keys rotated, next rotation: 2019-07-01 02:45:43.899839156 +0000 UTC"
Jun 30 13:45:43 harborci-oidc-dex dex[3541]: time="2019-06-30T20:45:43Z" level=info msg="keys expired, rotating"
Jun 30 13:45:42 harborci-oidc-dex dex[3541]: time="2019-06-30T20:45:42Z" level=info msg="login successful: connector \"local\", username=\"test7\", email=\"test7@example.com\", groups=[]"

**Comment by reasonerjt** [comment]
After initialization, the OIDC provider will only refresh upon the configuration is changed, so when the key rotate the provider may be using a expired key to verify the token which results the problem.

**Comment by reasonerjt** [comment]
Fixed by #8291
