### ISSUE TITLE
Deployment Vs Stateful for some resources [k8s]

### ISSUE THREAD

**Issue by mumrau** [goharbor/harbor#8181]
Hi,

This issue is for a kubernetes usage of Harbor.
I am really curious about the reasons behind stuff are `Deployment` and not `StatefulSets`.
It is stated in #5032 that these workloads are stateless, which might be true from the client-side,
But on the other hand, these workloads uses `PersistenVolumes`, which for _most_ cases are `ReadWriteOnce` (chartmuseum, registry, jobservice).
As a result, harbor cannot rollout a deployment, because the old pod will still be mounted and won't release the lock for the new pod from the new replicaset.
The only solution is to manually delete the old replicaset, which can be quite a burden, especially when modifications (sidecars for instance) are made programatically.

My solution would be to, at least, give the possibility to deploy theses resources as a `StatefulSet`, the API is extremely similar and I doubt many changes are necessary.

Nonetheless, I'm still up to debate the reasons for this being implemented this way in the first place before making any change.

**Comment by ywk253100** [comment]
You can set the access mode when installing Harbor chart and the volume can be mounted to multiple pods or not is determined by the volume provider.
