### ISSUE TITLE
replication  failed to update the execution pq: invalid byte sequence for encoding "UTF8

### ISSUE THREAD

**Issue by lmdkfs** [goharbor/harbor#8188]
harbor info:
version: v1.8.1
i have two harbor server:
1.  10.10.104.41
2.  10.10.46.165
i create replication role on 1 server, test ok .The following error occurred while performing manual synchronization:
```
Jul  1 17:43:23 172.22.0.1 core[26647]: 2019-07-01T17:43:23+08:00 [ERROR] [/replication/operation/controller.go:100]: failed to update the execution 2: pq: invalid byte sequence for encoding "UTF8": 0x8b

Jul  1 17:43:23 172.22.0.1 core[26647]: 2019-07-01T17:43:23+08:00 [ERROR] [/replication/operation/controller.go:102]: the execution 2 failed: failed to fetch image: http error: code 500, message {"code":500,"message":"Internal Server Error"}
```

**Comment by lmdkfs** [comment]
How to solve

**Comment by steven-zou** [comment]
@ywk253100 

Could u take a look at it?

**Comment by steven-zou** [comment]
Seems something related with the database schema

**Comment by ywk253100** [comment]
@lmdkfs Does this error occur for every replication operation? Is it can be reproduced in your environment?

**Comment by reasonerjt** [comment]
@lmdkfs are you using internal DB?
@ywk253100 
Let's double check the internal DB does not think UTF as invalid.
