### ISSUE TITLE
Harbor auth reset from LDAP to Database

### ISSUE THREAD

**Issue by chipzoller** [goharbor/harbor#8193]
**v1.7.5 (Enterprise PKS)**

When setting up LDAP auth in Harbor directly, some event occurred which saw that reset back to Database. After deleting all users, the auth mechanism cannot be changed back to LDAP. How can auth be reset without redeploying Harbor? Docs have no information on this that I can find.

**Comment by reasonerjt** [comment]
Could you try the approach described in the FAQ?
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication

**Comment by chipzoller** [comment]
Thanks, I did not see that FAQ but already redeployed Harbor. I'll keep this in mind for next time. It seems there's a bug in this version of Harbor whereby LDAP auth is getting reset to Database if it can't contact the LDAP server specified.

**Comment by reasonerjt** [comment]
For issue in Harbor tile shipped with PKS please use channel of vmware.

I'm closing this one as the original question has been answered.
