### ISSUE TITLE
delete operations from UI not sensitive to case, eg delete of "v1" also deletes "V1" in v1.7.5-a8f6543a

### ISSUE THREAD

**Issue by afewell** [goharbor/harbor#8194]
If you are reporting a problem, please make sure the following information are provided:

In harbor v1.7.5-a8f6543a if you upload some image with image tag "v1", and also upload an additional copy of that same image with tag "V1", and then attempt to delete either one of the images, both images are deleted, indicating the delete function here is not properly recognizing case, and it should be case sensitive such that a delete operation for a tag "v1" would not also delete the image tagged "V1"

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by vasicvuk** [comment]
We are also facing this bug. But it was already posted here and the response was that the Docker Registry API does not support Deleting by Tag but only but sha so that is the reason why both tags are deleted.

I would like to have this working properly in Harbor since it works on Docker Trusted Registry, Alibaba Container Registry, Google Container Registry and Azure Container Registry.

**Comment by wy65701436** [comment]
thanks @vasicvuk for the details, 
yes, so far it is a limitation as the deleting is implemented by digest, the tags share the digest will be removed all.
