### ISSUE TITLE
Just wonder the storage location of Harbor of a pushed image

### ISSUE THREAD

**Issue by cailiangliang765** [goharbor/harbor#8195]
Just wonder the storage location of Harbor of a pushed image? Many thanks !

**Comment by louyiping** [comment]
Default location is /data/registry .

**Comment by ninjadq** [comment]
@cailiangliang765 you can also change the location of /data on `harbor.yml`

**Comment by cailiangliang765** [comment]
> @cailiangliang765 you can also change the location of /data on `harbor.yml`

Many thanks for your information.
