### ISSUE TITLE
POST /projects/{project_id}/robots response content-type header is "text/plain" but should be "application/json"

### ISSUE THREAD

**Issue by ercanyahsi** [goharbor/harbor#8197]
We are using harbor API 1.8. POST /projects/{project_id}/robots endpoint returns json with "content-type" : "text/plain; charset=UTF8" response header. I assume "content-type" response header needs to be be "application/json".

**Comment by ercanyahsi** [comment]
is there any progress ?

**Comment by wy65701436** [comment]
thanks @ercanyahsi, it should be an issue. But you PR is trying to modify this base method, I think we need to update the robot API only instead.

**Comment by ercanyahsi** [comment]
@wy65701436 couldn't get exactly what you mean. But we faced up with this problem during robot account creation. Other API which we have used so far seems to be ok.

**Comment by gklp** [comment]
> thanks @ercanyahsi, it should be an issue. But you PR is trying to modify this base method, I think we need to update the robot API only instead. What's your thought?
> 
> `r.Ctx.ResponseWriter.Header().Set("Content-Type", "application/json") `

@wy65701436 

Every redirection requests behind of apis has this problem. This pr can be general solution. For example :
```
func (r *RobotAPI) Post() {
 ....
 r.Redirect(http.StatusCreated, strconv.FormatInt(id, 10)) 
....
}
```
**r.Redirect** which uses in api code causes problem for all endpoints.

**Comment by wy65701436** [comment]
yes, @gklp. But, not all of apis need to return a json header. 

Modify the base method impact all of apis, for this issue, I believe we can just modify the POST method of robot account api. @ercanyahsi
