### ISSUE TITLE
Swagger /internal/syncregistry error 415

### ISSUE THREAD

**Issue by lmdkfs** [goharbor/harbor#8200]
harbor info: version: 1.8.1

When I used swagger to call /internal/syncregistry interface, I got an error of 415, but used postman to call ok. and found that there was no header content-type: application/json, only "accept: application/json" , it solved. hope to fix this issue

**Comment by reasonerjt** [comment]
It is a by design that you have to add the header, to mitigate the risk for XSRF attack.

**Comment by reasonerjt** [comment]
Closing as it is by design.
