### ISSUE TITLE
private registry - error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "\n\n\n 

### ISSUE THREAD

**Issue by nshaik99** [goharbor/harbor#8203]
This is working:
I have created harbor with clair , can successfully push the images directly using backend node name.

THIS IS NOT WORKING:
I have created harbor with clair
a)docker-compose down
b) updated hostname with nginx url name
c) commented proxy_set_header X-Forwarded-Proto $scheme;
from common/config/nginx/nginx.conf
d) docker-compose up -d

docker login
Username : username
Password:
Login Succeeded

IMAGE PUSH FAILING

docker push /hello-world:latest
The push refers to repository [repository name/hello-world]
af0b15c8625b: Preparing
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\n\n\t\t\n\n\t\t\n\t\t\t<title></title>\n\t\t\t<meta content="1; url=/c" http-equiv="refresh" />\n\t\t\n\n\t\t<body onload="javascript:location.replace('/c')">\n\n\t\t\n\n\t\t\n\t\n\t\n\n\n\n\n"

please help us

**Comment by ninjadq** [comment]
is backend node name an IP address? and you want to use another nginx in front of harbor as an LB? If you are in this scenario,  you can try to set the `exeternal_url` in `harbor.yml`

**Comment by nshaik99** [comment]
Thank you for the response.

these steps I followed
1)# docker-compose down
2) updated harbor.yml   with    external_url: http://<external nginx url name>
I left hostname: <external nginx hostname>
3)docker-compose up -d

still the same issue:
a) UI still works  with  external nginx url  
b) docker login with external nginx url   success

but  docker push failed
docker push <external nginx url>/hello-world:latest
The push refers to repository [<external nginx url>/hello-world]
af0b15c8625b: Preparing
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<html>\n\n\n\t\n\n\t\t\n\n\t\t<head>\n\t\t\t<title></title>\n\t\t\t<meta content=\"1; url=/c\" http-equiv=\"refresh\" />\n\t\t</head>\n\n\t\t<body onload=\"javascript:location.replace('/c')\">\n\n\t\t\n\n\t\t</body>\n\t\n\t\n\n\n</html>\n\n"

**Comment by nshaik99** [comment]
tried other way  using  netscalar vip got different issue

configured netscalar  vip  infront of  harbor node real IP.

everything works with harbor node real IP.

with vip,  URL open the harbour login page but not going anywhere after entering credentials, no error .. nothing.

**Comment by ninjadq** [comment]
@nshaik99 after you chang the config file, you need run prepare script beween `docker-compose down` and `up`
