### ISSUE TITLE
Harbor Certificate download missing in UI

### ISSUE THREAD

**Issue by sudhakarau1** [goharbor/harbor#8205]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#pulling-and-pushing-images-using-docker-client shows a screenshot with a Download Certificate link which I can'f find in the UI in 1.8.1

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.1]

**Comment by MaGaoju** [comment]
please try : put the ca.crt to data/ca_download manually.

**Comment by ninjadq** [comment]
you need put ca file to `$DATA_VOLUMN/ca_download` directory
