### ISSUE TITLE
Sonatype Nexus3 Registry support

### ISSUE THREAD

**Issue by josephlim75** [goharbor/harbor#8215]
In our company, we store all our artifacts in `SonaType Nexus3 OSS` including docker images.  I have tried configuring `goharbor` replication to `Nexus3 Docker` registry but it is giving `ping` error.  When I look at the registry adapter, I only see the following support:

- huawei
- awsecr
- azurecr
- dockerhub
- googlegcr
- harbor
- native

Is there any plan to support registry replication adapter for `SonaType Nexus3` ?

**Comment by jcmartins** [comment]
+1

**Comment by steven-zou** [comment]
@josephlim75 

You can implement this driver by yourself, it's very easy, just several interface methods. You can also use the existing drivers as examples.

Btw, per the limitations of resource, we can not support all kinds of registry drivers, most of those d drivers really need help from the community. Welcome to do contributions!

**Comment by chlins** [comment]
@josephlim75 
Maybe you need active Docker Bearer Token Realm in nexus3, and when configure repositories you should provide right username and password, nexus3 docker registry can be worked well in my environment(harbor 1.8).

**Comment by josephlim75** [comment]
Thanks chlins.  I will give it a try.

**Comment by josephlim75** [comment]
@chlins 
I have tested nexus3 (Docker Bearer Token) with provider (docker-registry), it works !!!
You can close this issue
