### ISSUE TITLE
Unable to get HELM_CHART.NO_DETAIL and helm fetch and helm install when install harbors after LB

### ISSUE THREAD

**Issue by bonniechen1119** [goharbor/harbor#8222]
What can we help you?
1.We install two Harbor 1.8 with share db and redis and file, and for example the two server private ip is 1.1.1.1 and 1.1.1.2
2.And setup nginx to LB to access those two Harbor registry
3.We can pull and push images to Harbor successfully and also we can helm push and helm repo update successfully
4.However when we do helm fetch or helm install it meets error ,
the error is :Get http://1.1.1.1:8080/cahrtrepo/xxxx/charts/xxxx: dial tcp 1.1.1.1:8080:connect:connection timed out 
5.And when we docker-compose down 1.1.1.1 server, it still have error the error is :Get http://1.1.1.1:8080/cahrtrepo/xxxx/charts/xxxx: dial tcp 1.1.1.1:8080:connetc:connection timed out 
Another problem is when we click helm chart details in web, it meet error and check log in chartmuseum.log, it display:{"L":"WARN","T":"2019-07-04T08:37:55.655Z","M":"[255] Request served","path":"/http://1.1.1.1:8080/chartrepo/miotech-helm/charts/miotech-test-0.1.0.tgz","comment":"","latency":"24.488µs","clientIP":"xxxxxxx","method":"GET","statusCode":404,"reqID":"a0328925-7b1b-40f9-a333-4c59cd0e505e"}
And also close 1.1.1.1 server the error is same
Can u help figure out which config we setup error?

**Comment by bonniechen1119** [comment]
Any update?

**Comment by ninjadq** [comment]
@bonniechen1119  did you set the `external_url` in `harbor.yml`

**Comment by bonniechen1119** [comment]
> @bonniechen1119 did you set the `external_url` in `harbor.yml`

yup....docker login or docker pull or docker push work fine, and helm push also work fine...only helm install not work

**Comment by HaveFun83** [comment]
> I have almost the same problem except I can pull/install chart but I cannot see details through portal.
> 
> I'm using external_url and 1.9.0 Harbor.
> 
> GET /api/chartrepo/charts-helper/charts/helper/0.1.0 HTTP/1.1" 404
> 
> I have project named charts-helper and chart named helper with version 0.1.0
> 
> I've found this in chartmuseum.log
> 
> chartmuseum[1375]: {"L":"WARN","T":"2019-09-24T15:33:48.339Z","M":"[42930] Request served","path":"/https://registry...
> 
> There is / in a front of https://
> 
> **Update:**
> 
> After research, I've found that CHART_URL is causing this issue. I've set absolute_url for charts to false, remove CHART_URL variable from chartmuseum env file, flush redis cache and restart all services.
> 
> Now, Rancher will not show helm charts as it requires absolute url for helm chart.

We was facing the same issue. 
After setting `external_url` and the `chart.absolute_url: enabled` than  flushing the redis cache and restart the harbor services. The charts are working now. 
Can you check your chart index under:
`<harbor_data-volume>/chart_storage/public/index-cache.yaml` 
the charts `urls:` should match your external_url value

**Comment by strainovic** [comment]
@HaveFun83 Thanks! I also tried to change default /chartrepo path to /helm as I looks much better but it is hardcoded all over the Harbor and it requires large refactoring.

With default /chartrepo path, it works.

**Comment by finkr** [comment]
Please document that changing `external_url` usually require changing `absolute_url` for docker-compose users.

As explained by @strainovic in post from [24 Sep](https://github.com/goharbor/harbor/issues/8222#issuecomment-534615406), I had to :
- edit harbor.yml, and set `absolute_url: enable` in the `chart:`section
- re-run the `prepare` command
- restart harbor (docker-compose down ; docker-compose up)
- purge redis cache (`docker exec -ti redis redis-cli    FLUSHALL`)
- upload a new chart

**Comment by dingzhixue** [comment]
Unable to get HELM_CHART.NO_DETAIL and helm fetch and helm install when install harbors
