### ISSUE TITLE
replicate image error

### ISSUE THREAD

**Issue by liyongzhezz** [goharbor/harbor#8225]
hi，I got an error when I replicate image from another harbor server
`
[ERROR] [transfer.go:204]: an error occurred while creating project basic_platform on http://test.harbor.com with user admin : failed to create project basic_platform on http://test.harbor.com with user admin: 301 
`

both harbor are v1.2.2, and have already created project `basic_platform`
replicate from harbor A(https) to harbor test.harbor.com(http)

how to fix this problem?

Thank you

**Comment by ninjadq** [comment]
hi, @liyongzhezz can you use the latest stable version of harbor? your Issue may be solved

**Comment by liyongzhezz** [comment]
@ninjadq Harbor does NOT support replicate between different version, so I can not use the latest version.

**Comment by reasonerjt** [comment]
@liyongzhezz Please set the the replication endpoint with `https`.
