### ISSUE TITLE
Unable to add registry endpoint

### ISSUE THREAD

**Issue by yahirun** [goharbor/harbor#8228]
Docker version        :18.09.7  
docker-compose version:1.24.1  
harbor version        :1.8.1  

I failed to add new registry endpoint(https://hub.docker.com).  
![faild_to_ping_endpoint](https://user-images.githubusercontent.com/40496721/60703696-67837280-9f3d-11e9-8f43-4a97b0e6f9bb.png)

・core.log  
```
Jul  5 06:11:03 172.18.0.1 core[774]: 2019-07-05T06:11:03Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry https://registry-1.docker.io: Head https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: dial tcp 34.232.31.24:443: getsockopt: no route to host
Jul  5 06:11:03 172.18.0.1 core[774]: 2019-07-05T06:11:03Z [ERROR] [/common/api/base.go:69]: POST /api/registries failed with error: {"code":400,"message":"registry https://hub.docker.com is unhealthy: unhealthy"}
```

How can I solve this?  

I confirmed the following.  
・docker proxy setting
```
[root@harbor ~]# cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://xxx@xxx:8080" "HTTPS_PROXY=http://xxx@xxx:8080" "NO_PROXY=localhost"
```
Docker pull from Docker Hub is working.
```
[root@harbor ~]# docker pull centos
Using default tag: latest
latest: Pulling from library/centos
8ba884070f61: Pull complete
Digest: sha256:a799dd8a2ded4a83484bbae769d97655392b3f86533ceb7dd96bbac929809f3c
Status: Downloaded newer image for centos:latest
```
・environment proxy setting
```
[root@harbor ~]# env | grep -i http
http_proxy=http://xxx@xxx:8080
HTTPS_PROXY=http://xxx@xxx:8080
https_proxy=http://xxx@xxx:8080
HTTP_PROXY=http://xxx@xxx:8080
```
wget is working.
```
[root@harbor ~]# wget hub.docker.com
--2019-07-05 05:44:03--  http://hub.docker.com/
Resolving XXX... xxx.xxx.xxx.xxx
Connecting to XXX|xxx.xxx.xxx.xxx|:8080... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://hub.docker.com/ [following]
--2019-07-05 05:44:03--  https://hub.docker.com/
Connecting to XXX|xxx.xxx.xxx.xxx|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3635 (3.5K) [text/html]
Saving to: ‘index.html’

100%[===================================================================================================================================================>] 3,635       --.-K/s   in 0s

2019-07-05 05:44:04 (593 MB/s) - ‘index.html’ saved [3635/3635]
```

**Comment by ninjadq** [comment]
did you fill in the `Access ID` and  `secret` field?

**Comment by ywk253100** [comment]
The proxy configured for docker daemon doesn't work for containers, you need to configure it for container itself.
Currently, the replication  service doesn't pick up the proxy configurations, and we have opened an issue https://github.com/goharbor/harbor/issues/7981 to track the work, it should be supported in 1.9.

**Comment by yahirun** [comment]
@ywk253100 
Thank you for your reply.  
I configured the proxy in the following way.
```
echo "http_proxy=http://xxx@xxx:8080" >> common/config/core/env
echo "https_proxy=http://xxx@xxx:8080" >> common/config/core/env
docker-compose down -v
docker-compose up -d
```
As a result, I could add registry endpoint.

Thanks.

**Comment by Henry78** [comment]
> did you fill in the `Access ID` and `secret` field?
This isn't neccessary!

> I configured the proxy in the following way.
> [...]
> ```
> echo "http_proxy=http://xxx@xxx:8080" >> common/config/core/env
> echo "https_proxy=http://xxx@xxx:8080" >> common/config/core/env

If I add proxy env variables, as @yahirun suggests, I'm no longer able to change the vulnerablity scan interval, because `core` tries to connect to the `jobrunner` container via proxy.  This is logged:
```
2019-07-17T13:06:40Z [ERROR] [/common/api/base.go:69]: PUT /api/system/scanAll/schedule failed with error: {"code":500,"message":"Internal Server Error"}
```
