### ISSUE TITLE
Add Image Tag BlackList And WhiteList

### ISSUE THREAD

**Issue by fyqls** [goharbor/harbor#8232]
push image tag has not been checked,  manager clean image very tired

**Comment by reasonerjt** [comment]
The work in tag retention may help the manager to clean images?
https://github.com/goharbor/community/pull/89

I don't understand how blacklist and whitelist is used to help manager clean image.

**Comment by fyqls** [comment]
dev push image which tag is random，i want to define a  standard tag-name which used whitelist to constraint　dev

**Comment by reasonerjt** [comment]
But if you setup tag retention to remove the tags automatically, it's the same result?
The requirement you mentioned is do-able, but I don't think it's that valuable to most of the users.
