### ISSUE TITLE
Replication from us-west-2 harbor to us-east-1 harbor failed with items

### ISSUE THREAD

**Issue by kenneyhe-snapdocs** [goharbor/harbor#8233]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expect harbor to harbor using admin account works with public library or private repo using manual trigger.  Although 0 item replications works from west harbor to east harbor, that is it.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1) create west to east replication using public library with nothing there.
2) hit replicate button
3) succeeds (see succeed.txt)
4) add a helm chart to library to west
5) hit replicate
6) fails (see log2.txt from west's harbor core pod)

**Versions:**
Please specify the versions of following systems.
- harbor version: [Version v1.9.0-174cfd5d]
    repository: goharbor/harbor-core
    tag: dev
  
    repository: goharbor/harbor-jobservice
    tag: dev

      repository: goharbor/registry-photon
      tag: dev

      repository: goharbor/harbor-registryctl
      tag: v1.8.1

    repository: goharbor/chartmuseum-photon
    tag: v0.8.1-v1.8.1

    repository: goharbor/clair-photon
    tag: v2.0.8-v1.8.1

    repository: goharbor/nginx-photon
    tag: v1.8.1

    repository: goharbor/harbor-portal
    tag: v1.8.1

**Additional context:**
[succeed.txt](https://github.com/goharbor/harbor/files/3365278/succeed.txt)
[log2.txt](https://github.com/goharbor/harbor/files/3365279/log2.txt)

**Comment by ywk253100** [comment]
@kenneyhe-snapdocs The dev images are under development and not stable, please use the release version instead.

**Comment by kenneyhe-snapdocs** [comment]
fixed after downgrade to:
    repository: goharbor/harbor-core
    tag: v1.8.1

    repository: goharbor/harbor-jobservice
    tag: v1.8.1

    repository: goharbor/registry-photon
    tag: v2.7.1-patch-2819-v1.8.1

please test stability issue in future release for replication. closing it for now.
