### ISSUE TITLE
Unable to edit replicaiton rule, "Source" downlist is empty, but there should be a drop down list with item image and chart

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8236]
**Reproduce Steps:**

1. Add a replication rule with dockerhub registry;
2. Edit this rule by switch dockerhub registry to another harbor source registry;
3. Then "Source" drop down list is empty, there should be a drop down list with item image and chart

![image](https://user-images.githubusercontent.com/44018302/60787185-8e36e880-a18b-11e9-88b2-22713ff73241.png)

**Harbor  Version:** v1.9.0-c296f0dd

**Comment by jwangyangls** [comment]
fix it in #8241
