### ISSUE TITLE
LDAP authentification - server error 500 (v.1.8.1)

### ISSUE THREAD

**Issue by sh3tb3rd** [goharbor/harbor#8242]
Harbor Version: 1.8.1
Docker Version: 18.09.7
Docker Compose Version: 1.24.0

When trying to establish a LDAP authentification with the current version, I always get another server error 500. This issue is not present when using Harbor version 1.7.5. 

These are the Harbor core logs:

> Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_url, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_dn, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_password, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_base_dn, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_base_dn, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_search_filter, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_attribute_name, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_admin_dn, error: the configure value is not set
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/api/base.go:229]: LDAP connect fail, error: Failed to load system ldap config
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019-07-08T11:52:30Z [ERROR] [/common/api/base.go:69]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}
Jul  8 13:52:30 172.22.0.1 core[3241]: 2019/07/08 11:52:30 #033[1;44m[D] [server.go:2619] |192.168.178.101|#033[41m 500 #033[0m|   1.538778ms|   match|#033[46m POST    #033[0m /api/ldap/ping   r:/api/ldap/ping#033[0m
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_url, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_dn, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_password, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_base_dn, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_base_dn, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_search_filter, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_attribute_name, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_admin_dn, error: the configure value is not set
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/api/base.go:229]: LDAP connect fail, error: Failed to load system ldap config
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019-07-08T11:52:34Z [ERROR] [/common/api/base.go:69]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}
Jul  8 13:52:34 172.22.0.1 core[3241]: 2019/07/08 11:52:34 #033[1;44m[D] [server.go:2619] |192.168.178.101|#033[41m 500 #033[0m|   1.553022ms|   match|#033[46m POST    #033[0m /api/ldap/ping   r:/api/ldap/ping#033[0m
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_url, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_dn, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_search_password, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_base_dn, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_base_dn, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_search_filter, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_attribute_name, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_admin_dn, error: the configure value is not set
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/api/base.go:229]: LDAP connect fail, error: Failed to load system ldap config
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/api/base.go:69]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}
Jul  8 13:52:35 172.22.0.1 core[3241]: 2019/07/08 11:52:35 #033[1;44m[D] [server.go:2619] |192.168.178.101|#033[41m 500 #033[0m|   1.626853ms|   match|#033[46m POST    #033[0m /api/ldap/ping   r:/api/ldap/ping#033[0m

**Comment by thegasmann** [comment]
Looks like the problem resides in the UI.

When you enter the ldap connection data and hit [TEST LDAP SERVER] immediately it fails (I've seen Error 500 and Error 401). When you first hit [SAVE] and then [TEST LDAP SERVER] it works.

**Comment by reasonerjt** [comment]
```
Jul 8 13:52:35 172.22.0.1 core[3241]: 2019-07-08T11:52:35Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_search_filter, error: the configure value is not set
```

Looks like the setting is not saved?

**Comment by sh3tb3rd** [comment]
> Looks like the problem resides in the UI.
> 
> When you enter the ldap connection data and hit [TEST LDAP SERVER] immediately it fails (I've seen Error 500 and Error 401). When you first hit [SAVE] and then [TEST LDAP SERVER] it works.

Thank your, this solved my problem. Closing the issue now.

**Comment by thegasmann** [comment]
I'd not not close the issue.
I believe it should be fixed so that the UI works as expected where [SAVE] saves the data and [TEST LDAP SERVER] tests the connection (but does not save data since we might overwrite sth which did work, right?)

**Comment by stonezdj** [comment]
@sh3tb3rd  did you input the LDAP search password before click "Test LDAP connection "?
I can reproduce this issue when I did not input the password.
It seems the UI doesn't handle HTTP 500 error. and this interface confused the user, for LDAP connection test, if the password is not input, it will ping LDAP server from system settings, and there is no password setting in the system, that is the ping failed.
 `failed to get key ldap_search_password, error: the configure value is not set`

**Comment by stonezdj** [comment]
Both the rest api and UI should be changed to support some error code other than 500.
