### ISSUE TITLE
unable to delete image with notary install but not enabled

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#8247]
Harbor version 1.8.0 
steps:
1. push an un-signed image to existing harbor project
2. select this image and click delete on the web UI.
3. UI shows delete success, but image still exist. 
![image](https://user-images.githubusercontent.com/13995442/60867262-03262300-a25d-11e9-8657-88c7209f8be1.png)

4. check log it shows:
Jul  9 03:04:41 172.25.0.1 core[1215]: 2019-07-09T03:04:41Z [ERROR] [/common/utils/notary/helper.go:100]: Repository not exist, repo: harbor-dev.corp.hpicloud.net/maggierepo/hello-world, error: notary-server:4443 does not have trust data for harbor-dev.corp.hpicloud.net/maggierepo/hello-world, returning empty signature

project config as below: 
![image](https://user-images.githubusercontent.com/13995442/60866908-256b7100-a25c-11e9-9bac-15a35bee9a53.png)

**Comment by MaGaoju** [comment]
looks like once I install notary, when I delete un-signed image, it will check the Signatures. I think the logic should be if enable content trust checked on UI, it will check Signatures.  correct me if my understanding was wrong. 

src/core/api/repository.go   
func (ra *RepositoryAPI) Delete() { 
..................
	if config.WithNotary() {
		signedTags, err := getSignatures(ra.SecurityCtx.GetUsername(), repoName)
		if err != nil {
			ra.SendInternalServerError(fmt.Errorf(
				"failed to get signatures for repository %s: %v", repoName, err))
			return
		}
............................

additionally, if UI should show error if there is back-end error any how. 

Thanks

**Comment by reasonerjt** [comment]
The code you paste does not print the log message in the description.
I'll try to reproduce the issue in next couple of days.

**Comment by MaGaoju** [comment]
thanks for correct me, just trying to understand it. any update on this? or let me know if u meed more information.

**Comment by reasonerjt** [comment]
@MaGaoju 

I setup an env with 1.8.0 build, there's no any issue deleting images.
Does it happen to all projects and all images?

**Comment by MaGaoju** [comment]
Not for all, I have re-build the server and deploy 1.8.1, issue seems gone. I guess some docker setting impact this. but didn't find which one. thanks for check this, and I will close this issue for now, will re-open if happened again. thanks again!
