### ISSUE TITLE
Allow robot account to delete images in a project

### ISSUE THREAD

**Issue by IliaGershenzon** [goharbor/harbor#8248]
We need the ability to allow the robot account to delete images.
The user guide states that robot account can only push or pull, we use the lifecycle of the images with this robot account, and it can't delete the images it pushed :(

**Comment by stuclem** [comment]
Created https://github.com/goharbor/harbor/issues/9576 to track the doc update, so removing `doc-impact` from this one.

**Comment by xaleeks** [comment]
let's think about this, I think it makes sense @wy65701436 @reasonerjt

**Comment by xaleeks** [comment]
this will be addressed by https://github.com/goharbor/community/pull/148

**Comment by xaleeks** [comment]
please track progress on https://github.com/goharbor/harbor/issues/8723, closing
