### ISSUE TITLE
根据label_id查询仓库tags返回结果中包含了不符合条件的tag

### ISSUE THREAD

**Issue by schzrj** [goharbor/harbor#8249]
![image](https://user-images.githubusercontent.com/8553420/60875364-46d45900-a26c-11e9-89d3-34d6778123b2.png)
1、在该段代码逻辑中，查询所有镜像类型的resource，然后对于类型为‘g’的label，会存在不同仓库下的镜像关联同样id的label，导致查询到的resource_label数据不只是当前指定仓库的数据
2、基于1的结果，做循环获取tag时，包含了不是该仓库下的镜像tag，最终根据label过滤当前仓库下镜像tag的数据不准确

是否应该在循环时根据resource_name只过滤当前仓库的tag?

**Comment by reasonerjt** [comment]
@schzrj what was the api?

**Comment by schzrj** [comment]
@reasonerjt  /api/repositories/*/tags?label_id=%s
