### ISSUE TITLE
 can't create a new project

### ISSUE THREAD

**Issue by Cloudzp** [goharbor/harbor#8250]
If you are reporting a problem, please make sure the following information are provided:
 i can't create a new project in portal or swagger api!
**Expected behavior and actual behavior:**
![image](https://user-images.githubusercontent.com/25190767/60875613-cfeb9000-a26c-11e9-9a45-47a5677ece59.png)
**Use api create project**
![image](https://user-images.githubusercontent.com/25190767/60875683-f1e51280-a26c-11e9-874c-498ee31ae6be.png)

**The api has no return value and always loading：**
![image](https://user-images.githubusercontent.com/25190767/60875724-09bc9680-a26d-11e9-8f06-0a9178e469df.png)

**Steps to reproduce the problem:**
- 1. install harbor use helm
```
helm install --name frm-harbor harbor/harbor --namespace=harbor --set expose.tls.enabled=true \
--set expose.ingress.hosts.core=repository.parkingwang.com --set expose.ingress.hosts.notary=notary.irains.com.cn \
--set externalURL=https://repository.parkingwang.com  \
--set expose.tls.secretName=tls-secret \
--set persistence.persistentVolumeClaim.registry.storageClass=rook-ceph-block \
--set persistence.persistentVolumeClaim.chartmuseum.storageClass=rook-ceph-block \
--set persistence.persistentVolumeClaim.jobservice.storageClass=rook-ceph-block \
--set persistence.persistentVolumeClaim.database.storageClass=rook-ceph-block \
--set persistence.persistentVolumeClaim.redis.storageClass=rook-ceph-block    \
--set harborAdminPassword=test
```
-  2. login and create a new project 'test'

**Versions:**
Please specify the versions of following systems.
- harbor version:  latest
- docker engine version: [18.09.7]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
@Cloudzp 

Did you deploy Harbor using helm chart?  This maybe a problem in your k8s cluster.

Could you `curl` and see what's the error.  If it's timeout please debug and see if the request reached the pod.
