### ISSUE TITLE
Nginx 80 conflicts

### ISSUE THREAD

**Issue by fwhezfwhez** [goharbor/harbor#8254]
My cloud linux has already configured nginx using 80. When I try to install harbor, I find it has an image `goharbor/nginx-photon:v1.8.1` and conflict on port 80.

How to fix it

**Comment by reasonerjt** [comment]
You can shutdown the nginx on your linux, or bind to other port in by updating `harbor.yml`

**Comment by fwhezfwhez** [comment]
3q, I change harbor.yml http port and fix it.
