### ISSUE TITLE
[Issue] always retrying when push image

### ISSUE THREAD

**Issue by edenbuaa** [goharbor/harbor#8270]
step to reproduce:
1. tag a image : docker tag centos:1.0 myhub.com/centos:1.0
2. push to harbor: docker push myhub.com/centos:1.0

then the push process will run into retrying all the time.
my problem is how to push a image without creating a project ?
thanks for any suggestion.

**Comment by reasonerjt** [comment]
I cannot push an image without project, 
as for always retrying, it's the behavior of client, the server returns 500, need to check the log for root cause.
