### ISSUE TITLE
1.7.5 Wrong user or password

### ISSUE THREAD

**Issue by packyzbq** [goharbor/harbor#8271]
Hi, I got a problem when I used docker-compose to setup harbor.  At first, I setup harbor normally, and then execute `reboot` .  After the node power on and all components running,  I cannot use admin login with my costumed password, also the default password "Harbor12345".

I have encountered this situation several times，but it cannot be reproduced reproducibly. I don't know if there's a bug.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.5]
- docker engine version: [18.09.0]
- docker-compose version: [1.23.2]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
could you use `docker-compose down` to shutdown all containers and `docker-compose up -d` to restart Harbor and see if the problem persists?

Simply poweron may not be very reli-able if you want Harbor be running after reboot, please consider wrap Harbor as a service in `systemd`

**Comment by packyzbq** [comment]
Thanks for reply. It did works for me. It is that some components cannot be restarted after a reboot?

**Comment by reasonerjt** [comment]
I didn't spend much time to investigate.
In my personal experience, I recall it's that the timing of start of containers breaks the dependency.
You should not rely on docker daemon to handle the reboot case.
