### ISSUE TITLE
Robot Accounts for several projects

### ISSUE THREAD

**Issue by wToad** [goharbor/harbor#8272]
Hello,

**Is your feature request related to a problem? Please describe.**
I wanted to create a robot account for some clients, but this account need to access at least two projects. I could create an account in our LDAP but it would mean to give them a web UI access as well (which I don't want).

**Describe the solution you'd like**
I would like to create a robot account working for several projects.

**Describe the main design/architecture of your solution**
I don't know exactly how to describe it, but I was thinking of a dedicated space under the **Administration** -> **Users** space to display these robot accounts.

**Describe the development plan you've considered**
None

**Additional context**
I found out that it's already possible to do it but not through the web UI. The token created with the robot account is a JWT token that describe, as an array, the permission of the account, so I've generated my own array, adding a second project permission as below:

```
{
  "name": "product-snapshots-and-releases",
  "access": [
    {
      "resource": "/project/12/repository",
      "action": "pull"
    },
    {
      "resource": "/project/product-releases/repository",
      "action": "pull"
    },
    {
      "Resource": "/project/14/repository",
      "Action": "pull",
      "Effect": ""
    },
    {
      "Resource": "/project/product-snapshots/repository",
      "Action": "pull",
      "Effect": ""
    }
  ]
}
```

This is successful and the robot account appears on project I used as trigger on the API, but not on the second project. Anyway, the token is working for both! I successfully pulled images with it.

What I would like now is to have the web UI working the same way.

**Comment by reasonerjt** [comment]
We add such flexibility while implementing it but from UI you the scope of a robot account is within a project.

**Comment by wToad** [comment]
Thank you for replying. I understand it well, I was just checking it because I would prefer the capability to have robot account for many project. I hope it will be something about it in the next versions of Harbor. :smiley:

**Comment by michmike** [comment]
@xaleeks isn't this a perfect scenario for the limited guest account we are trying to do for Harbor 1.10?

**Comment by wToad** [comment]
I'm curious where it's explained, I couldn't find information about it on https://github.com/goharbor/harbor/wiki/Harbor-Roadmap
Because if it does, I'll prepare the update ASAP

**Comment by michmike** [comment]
ping me on slack please, m2 is my alias

**Comment by michmike** [comment]
hi @wToad , i wanted to bring to your attention the Harbor advisory https://github.com/goharbor/harbor/security/advisories/GHSA-x2r2-w9c7-h624 that was released a few days ago. We patched the issue of being able to use the API to create robot accounts that span projects because that was deemed a critical vulnerability in Harbor. sorry...

**Comment by wToad** [comment]
hi @michmike , first of all sorry for not replying the first message. It's good news that guest account will appear.

About the robot account patch, thank you for the notification! I'll handle it by creating many account until the release of 1.10 and that should be fine

**Comment by bymarshall** [comment]
Hi @michmike, is there an alternative solution for a robot account to access more than one project? In any environment where robot accounts are used to automate the image creation process, this feature is really necessary. It is very common to try to use other private images as base images. If your base images are in a private port project and the robot account used to automate the process cannot access them, it makes the robot accounts unusable in these cases. Please consider adding more specific access control for robot accounts and projects, thanks.

**Comment by xaleeks** [comment]
@bymarshall Hi, this is being worked on, please see response here - https://github.com/goharbor/harbor/issues/10774
