### ISSUE TITLE
Filter project (research) has no focus

### ISSUE THREAD

**Issue by wToad** [goharbor/harbor#8278]
Hello,

**Expected behavior and actual behavior:**
When I am on the projects page, I can see all my projects, with multiple pages. To find a project, it's easier to filter projects by name, so I click on the magnifying glass to launch a search. The search field appears but the pointer is not in it, I have to click in this field to be able to write my text.

I expect the focus to be put in the search bar when it appears after clicking on the magnifying glass.

**Steps to reproduce the problem:**
Nothing particular, simply do a research.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.1]
- docker engine version: [18.09.3]
- docker-compose version: [1.23.2]

**Additional context:**
I don't think my harbor.yml file is required for this or any logs :smiley:

**Comment by jwangyangls** [comment]
Thank you very much for your request. We will complete it in the upcoming Harbor 1.9.0 release.

**Comment by Thoro** [comment]
@jwangyangls This issue still persists with Harbor v2.1.0
