### ISSUE TITLE
Replication failed: value too long for type character varying(256)

### ISSUE THREAD

**Issue by bovy89** [goharbor/harbor#8281]
**Actual behavior:**
Replication failed: value too long for type character varying(256)

**Steps to reproduce the problem:**

Configure a new replication rule:
  - Source resource filter name: `**`
  - Example image: `sysinfo_paas_base_stage/s2i-tomcat:8a72ab6611e787d24a7e9fd9ad51ab38caee69a9-centos-openjdk11-tomcat8`

**Versions:**
- harbor version: 1.8.1
- docker engine version: 18.09.7
- docker-compose version: 1.23.2, build 1110ad01

**Log files:**

```
==> core.log <==
Jul 10 16:22:55 172.18.0.1 core[57435]: 2019-07-10T14:22:55Z [ERROR] [/replication/operation/controller.go:102]: the execution 3 failed: failed to create task records for the execution 3: pq: value too long for type character varying(256)

```

**Comment by Mangosniper** [comment]
If its of any interest. I fixed the issue temporarily for me with docker exec into the harbor_db container, connecting to the postgres dpb with psql and user postgres and altering the two entries in the table "replication_task" of the database "registry" to support 512 characters.

![image](https://user-images.githubusercontent.com/42478588/62209048-cc918300-b398-11e9-8786-dd3788e1e95e.png)

SQL Statements I executed are:

ALTER TABLE replication_task ALTER COLUMN src_resource TYPE character varying(512);
ALTER TABLE replication_task ALTER COLUMN dst_resource TYPE character varying(512);

I gurantee no long time stability ;)
