### ISSUE TITLE
Change admin username/password

### ISSUE THREAD

**Issue by faisalchishtii** [goharbor/harbor#8286]
Person who was admin has left the org. We do not have the admin username and password. My user is just a normal user. I have root access to the server. How do I change the username password?

**Comment by reasonerjt** [comment]
This is a hack, assuming you can access the DB and execute sql statement, you can check the records in `harbor_user` table and update the hash and salt of admin user of the another user whose password you know.
After the update you can use the same password with admin user.

**Comment by reasonerjt** [comment]
Closing this issue, let me know if there's further question.
