### ISSUE TITLE
Unable to authenticate with PKS UAA due to PKS Cert not trusted

### ISSUE THREAD

**Issue by brutester** [goharbor/harbor#8295]
**Expected behavior and actual behavior:**
When using PKS UAA "docker login" command is expected to work, but it shows "unauthorized: authentication required".

**Steps to reproduce the problem:**
1. Generate a new self-signed CA cert. Generate 3 certificates signed by it that will be set for OpsManager, PKS and Harbor.
2. Install OpsManager (2.5.9) and change it's certificate.
3. Under Bosh Config -> Security set "Trusted Certificates" to the generated root CA. Do not check "Include OpsManager Root CA in Trusted Certs"
4. Add PKS (1.4.1) and under "PKS API" set the custom generated certificate.
5. Add Harbor (1.7.5) and under Certificate set the last generated certificate. Update the "Certificate Authority" with the root CA.
6. Under Harbor -> Authentication set "Harbor Authentication Mode" to "UAA in Pivotal Container Service"
7. Apply pending changes
8. Test with "docker login <hostname>"

**Versions:**
Harbor version: 1.7.5

**Workaround:**
I have found two workarounds that kind of work:

A) Break the trust chain by disabling "UAA Verify Cert" under Harbor UI -> Administration -> Configuration -> Authentication

B) login to harbor VM over ssh and replace the content of /var/vcap/data/packages/harbor-app/*/common/config/core/certificates/uaa_ca.pem with the custom generated cert. Reboot the VM.

In both cases the result is: "Login Succeeded"

**Comment by paulczar** [comment]
You can add the CA cert via the helm chart here 

https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L100-L105

then you can finish setting up UAA auth via the web ui or config api

**Comment by brutester** [comment]
Another workaround I've found is to use the BOSH tool on Ops Manager. First configure and login with the tool (use Director Credentials from BOSH in OpsManager). List deployments.
```
bosh alias-env pks -e $your_ip --ca-cert /var/tempest/workspaces/default/root_ca_certificate
bosh -e pks log-in
bosh -e pks deployments
```

Get the harbor deployment ID from the list and fetch the installation manifest:
``bosh -e pks -d $harbour_deployment_id manifest > harbor.manifest``

Edit the setting under  "properties: -> uaa: -> ca_cert:  " and change to your root CA
``bosh -e pks -d $harbour_deployment_id deploy harbor.manifest --recreate``

**Comment by stonezdj** [comment]
It seems that the PKS and Harbor using different root ca? if they are using different ca, how do you solve the problem that the PKS worker node can not pull images from Harbor?

**Comment by brutester** [comment]
@stonezdj The certificate applied during installation of Harbor and PKS is signed by same, external CA. The issue is that OpsManager applies it's self-generated CA as an UAA trust certificate, instead of the one provided in PKS settings.

**Comment by reasonerjt** [comment]
@brutester if you are a tile user please contact VMware for support, this repo is for Harbor OSS only.

Closing.
