### ISSUE TITLE
Ability to run containers as non-root

### ISSUE THREAD

**Issue by ephracis** [goharbor/harbor#8300]
Since [Containers don't contain](https://opensource.com/article/18/3/just-say-no-root-containers) it is important to not run as root inside the container.

In fact, the default configuration on OpenShift is to prevent any containers running as root. It would be great if Harbor could support this security measure so we don't have to disable it just to get Harbor running on OpenShift.

When I tried to run Harbor I got this error:

```
$ oc logs harbor-chbr-harbor-registry-b775c4cbf-x6b6q -c registry
chown: '/var/lib/registry' to '10000:10000': Operation not permitted

$ oc logs harbor-chbr-harbor-adminserver-6bdf4bcc74-zv4l9
sudo: unknown uid 1000350000: who are you?
```

There might be more issues.

**Comment by reasonerjt** [comment]
This is a WIP 
@ninjadq could you provide more insight and what potential tech difficulty is there?

**Comment by cadnce** [comment]
I think as of 1.9 this can be closed?

**Comment by verwilst** [comment]
Not really, kubernetes gives us "Error: container has runAsNonRoot and image has non-numeric user (harbor), cannot verify user is non-root". Please use USER <id> instead of USER harbor in the Dockerfiles.

**Comment by xaleeks** [comment]
closing this, this is now possible in 1.9

**Comment by verwilst** [comment]
Well, as i stated in my comment above, it's 90% OK, but using a userid instead of a username would have been more correct.

**Comment by titou10titou10** [comment]
So, what is the procedure to deploy Harbor on Openshift 4.x?

**Comment by artbegolli** [comment]
> So, what is the procedure to deploy Harbor on Openshift 4.x?

You manage to figure this out?

**Comment by dejwsz** [comment]
Anyone managed to deploy it in openshift?

**Comment by djjudas21** [comment]
Not yet, but my team and I are working on it

**Comment by djjudas21** [comment]
This command worked for us with v2.2.0
```
oc adm policy add-scc-to-user anyuid system:serviceaccount:harbor:default
```

**Comment by dejwsz** [comment]
OK but this is relaxing the security - it would be good to have it working using pre-allocated UID for the namespace/project.

**Comment by djjudas21** [comment]
Agreed. Our instance is only for internal use so this relaxation is acceptable for now.

**Comment by titou10titou10** [comment]
@dejwsz  yes
Use harbor helm chart + images fron bitnami: 

- https://github.com/bitnami/charts/tree/master/bitnami/harbor
- https://bitnami.com/stack/harbor/containers
- https://hub.docker.com/search?q=bitnami%2Fharbor&type=image

Bitnami provides tons of "rootless" images for popular products, including the latest version of harbor
