### ISSUE TITLE
Replicate Signing capabilities of images with standard Harbor replication

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8303]
we need to make sure that when images are signed, there is a way for replication to honor the signed component of the images.

**Comment by reasonerjt** [comment]
We leverage docker content trust and notary for signing the image, last time I checked the signature is tied to `GUN` which is the uri of the image, so when you replicate the uri of the image changed, it should be considered a different resource in notary, and has to be signed again.

This is the biggest gap I can think about right now, we may need to think about other signing solution if we want to support this.

**Comment by phenixblue** [comment]
Ditto to the above. We would like to see this feature to allow for a simpler HA setup of Harboring bi-directional replication between 2 or more Harbor instances and still allow for proper signing and policy enforcement post replication

**Comment by michmike** [comment]
Hi Daniel, what if we enabled customers to.provide their own vanity URL for a project that's also behind a Load Balancer. two projects that are geodistributed and replicated can have the same URL and the LB can dictate where requests go. Would that be able to ensure signing is replicated?

**Comment by michmike** [comment]
Cc: @alexvmw

**Comment by xaleeks** [comment]
This seems difficult if we go through notary since the hostname is part of the GUN Daniel referenced. as confirmed here: https://github.com/theupdateframework/notary/issues/1023

**Comment by xaleeks** [comment]
we will be following progress that docker is making on https://cloud-native.slack.com/archives/CQUH8U287

**Comment by axi92** [comment]
Sry to dig this up, but is there any further information how to deal with that problem?

**Comment by brackend** [comment]
Hi,  can/does Harbor verify the source signature of the incoming image.  Although the signature does not transit along with the image because of gun, it should still verify the source signature on reception.

**Comment by wy65701436** [comment]
Since Harbor v2.5 is GAed, the it provides the cosign as the image sign solution. As for cosign, you can refer to the goharbor.io, and especial for this [PR](https://github.com/goharbor/website/pull/301)

**Comment by brackend** [comment]
Thank you Yan!   
Linked https://github.com/goharbor/harbor/issues/16679 to this
