### ISSUE TITLE
LDAP账户修改账户后无法登录

### ISSUE THREAD

**Issue by shayulei** [goharbor/harbor#8304]
版本：
       v1.8.0-25bb24ca
配置：
      开启LDAP
      LDAP用户UID：sAMAccountName
现象：
      当修改了AD中的sAMAccountName 的ID后，harbor无法使用此ID登录。报用户名或密码出错。

**Comment by stonezdj** [comment]
Please refer the workaround in FAQ: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
```
docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user
delete from harbor_user where user_id > 2
```

**Comment by shayulei** [comment]
root [ / ]# psql -U postgres
psql (9.6.10)
Type "help" for help.

postgres=# \c registry
You are now connected to database "registry" as user "postgres".
registry=# select * from harbor_user
registry-#

**Comment by stonezdj** [comment]
You should add `;` after each SQL query

**Comment by stonezdj** [comment]
Duplicated with #8142

**Comment by aducoin** [comment]
> Please refer the workaround in FAQ: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
> 
> ```
> docker exec -it harbor-db bash
> psql -U postgres
> \c registry
> select * from harbor_user
> delete from harbor_user where user_id > 2
> ```

I try this but i get this message: "DETAIL:  Key (user_id)=(3) is still referenced from table "project"." 
And that's logic.
So, I deleted the project associated with the user, reboot and try to delete just the user but i got the same error.

**Comment by apallier** [comment]
Hi,
I tried the same workaround through API (user deletion) and it didn't work neither.
For me the workaround had been to update the concerned user with his new username:

```
docker exec -it harbor-db bash
psql -U postgres
\c registry
update harbor_user set username = 'new_user_name' where user_id = 12345;
```

**Comment by KeithTt** [comment]
@apallier Thanks a lot, you really save my day.
