### ISSUE TITLE
Replicating images from Docker Hub

### ISSUE THREAD

**Issue by damozhiying** [goharbor/harbor#8305]
i want to sync docker hub image to local harbor ,but it not take effect
![2019-07-17 13-52-31屏幕截图](https://user-images.githubusercontent.com/10277950/61350500-53733580-a89a-11e9-9756-891ed248d943.png)
![2019-07-17 13-53-00屏幕截图](https://user-images.githubusercontent.com/10277950/61350501-53733580-a89a-11e9-9e1f-b2eaa9d8c8d4.png)
![2019-07-17 13-55-41屏幕截图](https://user-images.githubusercontent.com/10277950/61350580-9af9c180-a89a-11e9-8827-d084523e88f7.png)

**Comment by heww** [comment]
The name of the source resource filter should be `goharbor/*`, `goharbor` may not work.

**Comment by damozhiying** [comment]
@heww how to set ,source resource filter is this damozhiying/,this also can't sync

**Comment by heww** [comment]
change it from `damozhiying/` to `damozhiying/*`

**Comment by ywk253100** [comment]
@damozhiying Please refer to the user guide https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#resource-filter

**Comment by damozhiying** [comment]
@ywk253100  thanks a lot,
now i have one problem,docker not pull image from private mirror but from docker.io,
![image](https://user-images.githubusercontent.com/10277950/61506078-8db41280-aa13-11e9-8404-0deff31dec5b.png)
![image](https://user-images.githubusercontent.com/10277950/61506088-97d61100-aa13-11e9-99e8-7cce9f06acb1.png)
![image](https://user-images.githubusercontent.com/10277950/61506100-a3293c80-aa13-11e9-9a72-2ab128999cf3.png)

**Comment by damozhiying** [comment]
@heww @ywk253100 
how to change the default docker registry from docker.io to my private registry?
i had config daemon.json or docker.service, not take effect,   the harbor port is 7080,
