### ISSUE TITLE
Support oAuth2

### ISSUE THREAD

**Issue by annProg** [goharbor/harbor#8320]
Github and gitlab, gitea, gogs, etc. all implement the oAuth2 provider, hope that harbor can implement oAuth2 login to integrate the above software.

**Comment by reasonerjt** [comment]
Harbor supports OIDC, you can figure out how to use OIDC to connect or configure those services as OIDC provider.

**Comment by Purushotham233** [comment]
Look for the OAuth2 support. Has some started working on this? Else I can start and raise a PR on this.

**Comment by annProg** [comment]
@Purushotham233  Now I am using [dex](https://github.com/dexidp/dex) as oidc provider. Since dex can adapt many idp, such as github, gitlab, google, and it is easy to add customized idp connector, I think use dex is a better choice.

**Comment by Purushotham233** [comment]
@annProg , 
Came across [keycloak](https://github.com/keycloak/keycloak) which seem to be solving the same concern but couldn't find comparison analysis. Any idea about that?

**Comment by annProg** [comment]
> @annProg ,
> Came across [keycloak](https://github.com/keycloak/keycloak) which seem to be solving the same concern but couldn't find comparison analysis. Any idea about that?

Seem `keycloak` is a `identity provider`.  According to my understanding, `dex`  is a proxy to transform various of identity provider to perform as oidc provider. So if use dex, soft do not need to realize such as github, gitlab, microsoft etc any more, oidc is enough. For me, there already have a `identity provider` but it is not a oidc provider, I write a `dex connector` to make it perform as `oidc provider`.

```
+--------+
|keycloak+=-------+
+--------+        |
                  |
+--------+        |
|ldap    +=-------+
+--------+        |
                  |
+--------+        |
|github  +=-------+
+--------+        |
                  |
+--------+        |   +----+   +-------------+
|google  +=-------+-->+dex +-->|oidc provider|
+--------+        |   +----+   +-------------+
                  |
+--------+        |
|gitlab  +=-------+
+--------+        |
                  |
+--------+        |
|custom  +=-------+
+--------+        |
                  |
+--------+        |
|oidc    +=-------+
+--------+
```
