### ISSUE TITLE
sylabs singularity sif artifact support in harbor

### ISSUE THREAD

**Issue by asmi10** [goharbor/harbor#8330]
**Is your feature request related to a problem? Please describe.**
Currently we are using singularity & docker both in our organization, and having different registry solution for storing images. We are looking for some common platform where singularity & docker images could be stored. 

**Describe the solution you'd like**
Enable singularity sif artifact support in harbor registry.
 
**Describe the main design/architecture of your solution**
A clear and concise description of what does your solution look like. Rich text and diagrams are preferred.

**Describe the development plan you've considered**
I was going through the code in order to understand the different artifact types added in harbor, i.e helm charts, but I observed multiple dependency and got lost there. Can anyone help me to understand from where I should start?

**Additional context**

**Comment by xaleeks** [comment]
@asmi10 Can you try this with harbor 2.0 now?  you should be able to push singularity artifacts now

**Comment by SunMinghui19** [comment]
> @asmi10 Can you try this with harbor 2.0 now? you should be able to push singularity artifacts now
Is that ok now?

**Comment by wy65701436** [comment]
@asmi10 Since Harbor v2.0, it supports all OCI-compatible artifacts, so you can try it out and reopen it if you have any problems.
