### ISSUE TITLE
Harbor 1.8.x prepare script does not generate self-signed certificate for Notary

### ISSUE THREAD

**Issue by DooDleWilk** [goharbor/harbor#8334]
I deployed Harbor 1.8.x (Tried with 1.8.0 and 1.8.1 with same results) with Notary, using the offline bundle.
I set up HTTPS for Harbor (https://github.com/goharbor/harbor/blob/master/docs/configure_https.md) as requested for Notary (https://github.com/goharbor/harbor/blob/master/docs/use_notary.md).
When running the `prepare` command, it does create the `common/config/notary` folder structure, and generate the config files it needs, but the certificates are missing.

```
-rw-r----- 1 10000 10000 641 Jul 17 06:54 server-config.postgres.json
-rw-r----- 1 root  root  123 Jul 17 06:54 server_env
-rw-r----- 1 10000 10000 345 Jul 17 06:54 signer-config.postgres.json
-rw-r----- 1 root  root  159 Jul 17 06:54 signer_env
```

If I run the `install.sh` command, all the services start, and the `common/config/notary` folder looks like this :

```
-rwxr-xr-x 1 root  root    0 Jul 17 06:55 notary-signer-ca.crt
-rwxr-xr-x 1 root  root    0 Jul 17 06:55 notary-signer.crt
-rwxr-xr-x 1 root  root    0 Jul 17 06:55 notary-signer.key
-rwxr-xr-x 1 root  root    0 Jul 17 06:55 root.crt
-rw-r----- 1 10000 10000 641 Jul 17 06:54 server-config.postgres.json
-rw-r----- 1 root  root  123 Jul 17 06:54 server_env
-rw-r----- 1 10000 10000 345 Jul 17 06:54 signer-config.postgres.json
-rw-r----- 1 root  root  159 Jul 17 06:54 signer_env
```

All the certificate files are created, but all are empty!

I reverted to Harbor 1.7.5 and performed the very same operation, the content of the `common/config/notary` folder looks like this after the `prepare` command :

```
-rw------- 1 10000 10000 2069 Jul 17 07:16 notary-signer-ca.crt
-rw------- 1 10000 10000 1935 Jul 17 07:16 notary-signer.crt
-rw------- 1 10000 10000 3272 Jul 17 07:16 notary-signer.key
-rw------- 1 10000 10000 1732 Jul 17 07:16 root.crt
-rw-r----- 1 10000 10000  641 Jul 17 07:16 server-config.postgres.json
-rw-r--r-- 1 root  root   124 Mar 31 21:07 server_env
-rw-r----- 1 10000 10000  347 Jul 17 07:16 signer-config.postgres.json
-rw-r----- 1 root  root   160 Jul 17 07:16 signer_env
```

As a workaround, I stopped the Harbor 1.8.x instance (`docker-compose down -v`) and copied the certificate files from one to the other, and brought the instance back up (`docker-compose up -d`).

I can now sign the images with Harbor 1.8.x, like I could do in 1.7.5.

I cannot find if this is a missing documentation, or an issue with 1.8.x.
The 2 prepare files are very different in size and content.

Am I missing something here, or is this the "new" normal behaviour..?
And if so, what would be the process to generate the correct certificates..?

**Comment by ninjadq** [comment]
cert file in 1.8.x are moved to `secret/notary` under your data dir

**Comment by oscarlofwenhamn** [comment]
I think I am facing the same problem; I can't sign images, and the notary certificates are looking like this:
```
-rwxr-xr-x 1 root  root    0 Aug 15 08:38 notary-signer-ca.crt
-rwxr-xr-x 1 root  root    0 Aug 15 08:38 notary-signer.crt
-rwxr-xr-x 1 root  root    0 Aug 15 08:38 notary-signer.key
-rwxr-xr-x 1 root  root    0 Aug 15 08:38 root.crt
```

I found the certificates in the `secret/notary` directory, but the root.crt is not there. Otherwise, should they be copied from there and replace the empty certificates, or is Notary set to look under `secret/notary` and thus is finding the correct ones?

**Comment by ninjadq** [comment]
root.crt is in `secret/registry` dir

**Comment by oscarlofwenhamn** [comment]
Then why are there still empty certificates getting generated to `common/config/notary`? 
Are we supposed to copy the certificates from the data dir and put them under `config/notary` as described in the issue post, is this working as intended?
