### ISSUE TITLE
Can you please let me know Process & steps for upgrading harbor standalone bosh release from 1.5.2 to 1.6.x?

### ISSUE THREAD

**Issue by vinodh19** [goharbor/harbor#8336]
What can we help you?

**Comment by vinodh19** [comment]
Can you please let me know Process & steps for upgrading harbor standlone bosh release from 1.5.2 to 1.6.x? Mysql migration as well

**Comment by reasonerjt** [comment]
@vinodh19 let me clarify, are you using bosh standalone or tile?

**Comment by vinodh19** [comment]
Hi , Bosh standalone.
