### ISSUE TITLE
Webhook Task: Test cases trace

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#8346]

**Comment by reasonerjt** [comment]
For tracking the API test case based on python.

**Comment by reasonerjt** [comment]
@wy65701436 please confirm this will be covered in 2.0.0 or not

**Comment by renmaosheng** [comment]
@mmpei could you please add the tests? this is a requirement for each new API introduced. please share the ETA of when this can be done. thanks.

**Comment by mmpei** [comment]
we have add some cases in release 2.0.0
