### ISSUE TITLE
pull images permission

### ISSUE THREAD

**Issue by damozhiying** [goharbor/harbor#8363]
xstore project,the user lxf role is developer
![2019-07-22 14-32-28屏幕截图](https://user-images.githubusercontent.com/10277950/61611126-90ba3780-ac8d-11e9-801b-67394e1d7f25.png)

![2019-07-22 14-36-29屏幕截图](https://user-images.githubusercontent.com/10277950/61611347-22c24000-ac8e-11e9-9bd0-e8452db42238.png)

![2019-07-22 14-34-07屏幕截图](https://user-images.githubusercontent.com/10277950/61611218-daa31d80-ac8d-11e9-973e-e043f17735ac.png)

![2019-07-22 14-35-06屏幕截图](https://user-images.githubusercontent.com/10277950/61611257-ef7fb100-ac8d-11e9-9cc8-d56b1016c014.png)

![2019-07-22 14-35-58屏幕截图](https://user-images.githubusercontent.com/10277950/61611326-1807ab00-ac8e-11e9-8408-295babf19153.png)

lxf can't pull images,when i change the project to public ,lxf can pull images success,why?
@ywk253100

@heww

**Comment by damozhiying** [comment]
change xstore project to public
![2019-07-22 14-41-55屏幕截图](https://user-images.githubusercontent.com/10277950/61611634-e2af8d00-ac8e-11e9-981f-a16f49966de4.png)


![2019-07-22 14-42-36屏幕截图](https://user-images.githubusercontent.com/10277950/61611672-fbb83e00-ac8e-11e9-9b1d-7011200b4762.png)


![2019-07-22 14-43-00屏幕截图](https://user-images.githubusercontent.com/10277950/61611688-08d52d00-ac8f-11e9-9a33-e03f96da0b6f.png)

xstore project  log show anonymous user pull ,why? ,it should show lxf pull

**Comment by damozhiying** [comment]
![2019-07-22 14-45-41屏幕截图](https://user-images.githubusercontent.com/10277950/61611820-68333d00-ac8f-11e9-99fe-f6243bcd7f00.png)

![2019-07-22 14-46-55屏幕截图](https://user-images.githubusercontent.com/10277950/61611902-a29cda00-ac8f-11e9-9571-243448d26416.png)

**Comment by damozhiying** [comment]
from the log info , if the project is public ,such as  docker pull xstore/docker-istio success ,if the project is private,docker pull xstore/docker-istio can't pull ,must be docker pull 192.168.30.56:7080/xstore/docker-istio,   why  project is  private, must input the hostname or ip:port  to pull images

**Comment by damozhiying** [comment]
in lan network,pull images usual don't input ip or hostname,   if dont't input,the harbor project is public,  this is not permiss control

**Comment by damozhiying** [comment]
![2019-07-24 14-12-44屏幕截图](https://user-images.githubusercontent.com/10277950/61769517-1fa98a00-ae1d-11e9-8a1c-a998c8b6a5b8.png)

docker-compose.yml contain the restart policy ,restart: always,why if i restart docker, the docker-compose.yml contain service not restart

**Comment by reasonerjt** [comment]
@damozhiying the second pull was issued against dockerhub, I'm closing. 

Please retry and pay attention.
