### ISSUE TITLE
Build registryctl?

### ISSUE THREAD

**Issue by MrMEEE** [goharbor/harbor#8373]
Hi

How do I build the binary for registryctl??? There is no build script in the make/photon/registryctl folder??

Regards

**Comment by wy65701436** [comment]
please refer to the make file at (https://github.com/goharbor/harbor/blob/master/make/photon/Makefile#L190)

**Comment by MrMEEE** [comment]
Thanks, but that is how to build the registryctl image..

How do I build the binary?

**Comment by wy65701436** [comment]
here it is. https://github.com/goharbor/harbor/blob/master/Makefile#L282

**Comment by MrMEEE** [comment]
Thanks.. don't know why I overlooked it :)
