### ISSUE TITLE
JobServices api calls 404 Not found

### ISSUE THREAD

**Issue by SweeXordious** [goharbor/harbor#8379]
Ive been experimenting with Harbor for the past days and tried to interact with the [JobServices](https://github.com/goharbor/harbor/tree/master/src/jobservice) using the API calls specified in the documentation.

I first start by changing the `Core_Secret` key before building Harbor from source and print it in the logs to be sure it has been changed. 

I make the changes on the `harbor/make/photon/prepare/utils/configs.py` and change the line `config_dict['core_secret'] = generate_random_string(16)` with `config_dict['core_secret'] = new_key`. Also to the source files that contain the method `GetUIAuthSecret()` to print it to be sure i have the right one.

So, i end up with my new key being defined and printed on the logs. However, i still cant interact with the working pool using the API calls. 

I use curl : 
>curl -X POST "http://.../api/v1/jobs" -H "Authorization : Harbor-Secret new_key" -d '{
>     "job": {
>         "name": "demo",
>         "parameters": {
>             "p1": "just a demo"
>         ...
>} -v

I get the following results:

>*   Trying 192.168.252.144...
>* Connected to 192.168.252.144 (192.168.252.144) port 80 (#0)
> POST /api/v1/jobs HTTP/1.1
> Host: 192.168.252.144
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization : Harbor-Secret new_key
> Content-Length: 106
> Content-Type: application/x-www-form-urlencoded
> 
>* upload completely sent off: 106 out of 106 bytes
> HTTP/1.1 415 Unsupported Media Type
> Server: nginx
> Date: Tue, 23 Jul 2019 16:21:17 GMT
> Content-Length: 0
> Connection: keep-alive
> Set-Cookie: sid=07fe0d7aca056535495ea49914ceb962; Path=/; HttpOnly
> 
>* Connection #0 to host 192.168.252.144 left intact

and also:
> Jul 23 09:33:21 172.24.0.1 core[7648]: 2019/07/23 16:33:21 #033[1;44m[D] [server.go:2774] |192.168.252.144|#033[43m 415 #033[0m|    764.358µs| nomatch|#033[46m POST    #033[0m /api/v1/jobs#033[0m

 in the `core` logs and no changes on the other logs except `proxy` but it only redirects the request..

And when i send a `get` request to `GET /api/v1/stats` for example, i end up with a 404 not found ...

**Comment by steven-zou** [comment]
@SweeXordious 

So far, the job service is used as an internal component. Its related APIs are not exposed in Harbor API collections. If you call job service API with harbor endpoint/hostname, 404 will be returned.

If you want to directly interact with job service, a workaround is exposing the HTTP port of job service and then use host:port to call the APIs.

**Comment by SweeXordious** [comment]
Thank you @steven-zou , i managed to make it work as follows:
- started Harbor like usual.
- `docker container ps`  to get the running containers and be sure that `harbor-jobservices` is running.
- run `docker exec harbor-jobservices env` to get the `Core_Secret` variable needed for the authorization like specified in the [documentation](https://github.com/goharbor/harbor/tree/master/src/jobservice) (API calls part).
- Send API requests using curl using 
`docker exec harbor-jobservices curl -X POST address/api/v1/...  -H "Authorization: Harbor-Secret Core_Secret" -d '{"job": { // request from documentation"'`

The `address` can be taken from `docker exec harbor-jobservices ifconfig`.
