### ISSUE TITLE
ERROR InnoDB Unable to lock ./ibdata1 error:11

### ISSUE THREAD

**Issue by ldd91** [goharbor/harbor#8381]
What can we help you?
I use harbor.v1.1.1-rc3.tar.gz offline installed by docker-compose which version is 1.18.0,I only change the hostname ib harbor.cfg and run ./install.sh,however the harbor-db container is always restarting,when i check the log in /var/log/harbor/mysql.log it shows:
ERROR InnoDB Unable to lock ./ibdata1 error:11
[Note] InnoDB:check that you do not already have another mysqld process using the same InnoDB data or log files.
I check docker ps -a there was only one harbor-db container and i exec lsof -i:3306 only one process

**Comment by wy65701436** [comment]
hi @ldd91, can you please upgrade to the latest version as harbor has already migrated to Postgres from v1.6.0.

**Comment by ldd91** [comment]
Hi it was caused by /harbor-data
