### ISSUE TITLE
启动ldap在配置命令行的时候反馈403

### ISSUE THREAD

**Issue by RorschachChan** [goharbor/harbor#8388]
我的harbor是1.8版本的，想启动ldap认证，但是效仿https://github.com/goharbor/harbor/blob/master/docs/configure_user_settings.md 里的步骤，在执行
curl -X PUT -u "用户名:密码" -H "Content-Type: application/json" -ki https://域名/api/configurations -d'{"auth_mode":"ldap_auth"}'

的时候，返回的是403

HTTP/1.1 403 Forbidden
Server: nginx
Date: Wed, 24 Jul 2019 09:45:32 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 34
Connection: keep-alive
Set-Cookie: sid=e5d5e7ae6e3b56c8a80b71ef3ae4aff5; Path=/; HttpOnly
X-Content-Type-Options: nosniff

{"code":403,"message":"用户名"}

请问这是为什么？

**Comment by RorschachChan** [comment]
我已经把 admin的初始密码更改了，使用新的密码去执行，反馈400

curl -X PUT -u "admin:新的密码" -H "Content-Type: application/json" -ki https://域名/api/configurations -d'{"auth_mode":"ldap_auth"}'
HTTP/1.1 400 Bad Request
Date: Wed, 24 Jul 2019 11:40:21 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 101
Connection: keep-alive
Set-Cookie: sid=5e503cfa58ace6fc117a5faf6dd0bf0f; Path=/; HttpOnly
X-Content-Type-Options: nosniff

{"code":400,"message":"auth_mode can not be modified as new users have been inserted into database"}

**Comment by RorschachChan** [comment]
我想可能是因为我自己手动添加了一个用户的缘故，导致ldap无法启动。

于是我在web页面里将这个用户删除了，但是发现依旧是400。

**Comment by TechCatOther** [comment]
You need to remove all users of LDAP auth and remove deps of owned projects

**Comment by stonezdj** [comment]
Please refer the FAQ to remove the LDAP user in harbor DB: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication
