### ISSUE TITLE
Replication pattern '**

### ISSUE THREAD

**Issue by Henry78** [goharbor/harbor#8390]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Tried to replicat whole projects (organization in DTR-speech) by using the pattern `$repo/**`

**Steps to reproduce the problem:**
Add new Registry 
Add new replication rule with a pattern like `$repository/**`

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.9.1]
- docker engine version: [18.09.7]
- docker-compose version: [1.18.0]

**Additional context:**
If i use the double-astrisk filter on a projekt on Docker Hub, it pulls all repos as expected!

**Comment by cd1989** [comment]
I don't get what's the problem.

**Comment by reasonerjt** [comment]
@Henry78 Could you elaborate?

**Comment by Henry78** [comment]
> I don't get what's the problem.

As I don't have access to the system an more I'm unable to reproduce it now.

I think the problem was that replicating all repos of a project/organization from internal registry using the double asterisk didn't pull all of them. As opposed to replicating the project/organization from docker hub pulled all repos as expected. 

As I'm unable to reproduce this atm, I'll close this issue.
