### ISSUE TITLE
why harbor do not support high availability from 1.7

### ISSUE THREAD

**Issue by hellowordczy** [goharbor/harbor#8393]
I can find doc about high availability  information in version 1.6，but i cannot find it in version 1.7 on.i wonld like to know if high availability is canceled from 1.7 on,and how i can use harbor with high availability from 1.7

**Comment by wy65701436** [comment]
As from v1,7, the high availability solution for Harbor moved to chart  you can try with https://github.com/goharbor/harbor-helm

**Comment by hellowordczy** [comment]
GET IT,thx

**Comment by reasonerjt** [comment]
@hellowordczy you can do it by customizing Harbor according to you environment, but it will not be supported.

**Comment by bjethwan** [comment]
@reasonerjt 
I think you should reconsider, as k8s require upgrade done more often. And there are always cases where the upgrade fails and we have run into other runtime issues too. We were happy running the image registry, the old way.

-Thanks
