### ISSUE TITLE
Error while building portal

### ISSUE THREAD

**Issue by qinluyao761** [goharbor/harbor#8394]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1.cd harbor
2.make all
3.while compiling portal, error always occurs:

Step 11/24 : RUN npm install &&     chmod u+x /entrypoint.sh
 ---> Running in 41e3c33d501c
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-24T21_33_59_252Z-debug.log
The command '/bin/sh -c npm install &&     chmod u+x /entrypoint.sh' returned a non-zero code: 1

please help to investigate the issue and feedback with solutions, Thanks.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.1]
- docker engine version: [18.03.1]
- docker-compose version: [1.25.0]

**Additional context:**
* **Harbor config files:** You can get them by packaging `harbor.cfg` and files in the same directory, including subdirectory.
* **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by qinluyao761** [comment]
Step 11/24 : RUN npm install && chmod u+x /entrypoint.sh
---> Running in 41e3c33d501c
### npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! https://npm.community

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-07-24T21_33_59_252Z-debug.log
The command '/bin/sh -c npm install && chmod u+x /entrypoint.sh' returned a non-zero code: 1

i guess that some arguments should be followed by npm install, but i don't what the arguments are.

**Comment by qinluyao761** [comment]
If i remove the npm install command and continue to build, there is another error while execute entrypoint.sh:
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNREFUSED: request to https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz failed, reason: connect ECONNREFUSED 192.168.33.234:8080
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-24T22_14_14_420Z-debug.log

**Comment by qinluyao761** [comment]
Can anyone help me please?

**Comment by qinluyao761** [comment]
@ninjadq

**Comment by reasonerjt** [comment]
@qinluyao761 
```
ECONNREFUSED: request to https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz failed, reason: connect ECONNREFUSED 192.168.33.234:8080
```

**Comment by qinluyao761** [comment]
please analyze this message:
Step 11/24 : RUN npm install && chmod u+x /entrypoint.sh
---> Running in 41e3c33d501c

npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! https://npm.community

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-07-24T21_33_59_252Z-debug.log
The command '/bin/sh -c npm install && chmod u+x /entrypoint.sh' returned a non-zero code: 1

**Comment by ninjadq** [comment]
@qinluyao761 can not reproduce in my env, can you delete `node_module` dir inside portal dir and try again
