### ISSUE TITLE
v1.7版本无法在互联网访问

### ISSUE THREAD

**Issue by linyx-7** [goharbor/harbor#8403]
What can we help you?
公司内网部署了harbor1.7版本，地址192.168.*.*，通过防火墙的端口映射到互联网。在阿里云服务器上可以通过curl访问到页面，但是通过docker login http://*.*.*.*：****，在输入用户名和密码后，报超时断开。
Error response from daemon: Get http://*.*.*.*:****/v2/: Get http://192.168.32.14/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)

**Comment by reasonerjt** [comment]
You need to update hostname in harbor.cfg, as the hostname is propagated to different containers.
