### ISSUE TITLE
Allow robot token expiration to be disabled

### ISSUE THREAD

**Issue by kyrogue** [goharbor/harbor#8405]
**Is your feature request related to a problem? Please describe.**
There is no ability to refresh/renew a token when it is approaching expiration.

**Describe the solution you'd like**
Allow option to set whether a robot account token should have expiration date or not.

**Comment by leosunmo** [comment]
I agree completely with this. All robot accounts I've been using are used internally as part of CI/CD and by Kubernetes itself as imagePullSecrets. Having them expire without me realising will mean downtime as containers (if they re-pull the image) will not be able to spin up. I don't know what the majority use-case/environment is for Robot accounts, but for me the token expiry seems unnecessary. Having it as an option is fine.

Alternatively if the wider community decides that a default expiry is critical, we at least need an easy and quick way to refresh the token (_NOT_ recreate the user, that doesn't solve the issue as I'd still have to update my CI and imagePullSecrets) using the API.

**Comment by xaleeks** [comment]
> I agree completely with this. All robot accounts I've been using are used internally as part of CI/CD and by Kubernetes itself as imagePullSecrets. Having them expire without me realising will mean downtime as containers (if they re-pull the image) will not be able to spin up. I don't know what the majority use-case/environment is for Robot accounts, but for me the token expiry seems unnecessary. Having it as an option is fine.
> 
> Alternatively if the wider community decides that a default expiry is critical, we at least need an easy and quick way to refresh the token (_NOT_ recreate the user, that doesn't solve the issue as I'd still have to update my CI and imagePullSecrets) using the API.

I don't see an issue with adding a token regeneration but I didn't understand the 'expire without me realising will mean downtime', why not just set a near infinity large token expiration time?

**Comment by leosunmo** [comment]
The maximum expiration time is 365~ days, which in my experience is actually worse than a forced short expiry. With a short expiry you are forced to exercise your token management system/regeneration script. A year is a dangerous duration, just enough for me to forget about it :P

**Comment by kyrogue** [comment]
Correct, also the expiration time limit issue is filed here #8416

**Comment by wy65701436** [comment]
I will have a debug on this, thanks @leosunmo @kyrogue

**Comment by xaleeks** [comment]
We are adding token regeneration ability, and fixing the current expiry issue. already moved this into next release commitments (v1.10)

**Comment by moolen** [comment]
I'm curious how this regeneration will look like. Did you write a spec for it yet by any chance?

I'm having the same use-case as @leosunmo and simply regenerating or overriding the password in not enough i think. Consumers (k8s, $CLOUD services, CI/CD..) need to be re-configured which will take some time.

One option would be to introduce some sort of grace period which allows logging in with the "old" password for a certain amount of time.

**Comment by reasonerjt** [comment]
@wy65701436 shall we open an issue to track dev work?

**Comment by wy65701436** [comment]
@xaleeks, can you confirm whether it is a `must-have `item in 1.10, as https://github.com/goharbor/harbor/issues/8416#issuecomment-541005938, user can set a `9999` days duration for a robot account.

**Comment by xaleeks** [comment]
Since there's no bug right now, I'm dropping this out of 1.10 since there are more urgent features that need to be shored up.  This is still going to be done, just on next release.

**Comment by xaleeks** [comment]
you will be able to on the next release, we are adding this capability to robot so you can define expiration date on creation and allow setting it to infinity which is equivalent to disabling it

**Comment by xaleeks** [comment]
https://docs.google.com/document/d/1B4946mkMuNuezqj_9OmQLEveUgXHTKOAdifnqMRCOBI/edit#

prd here, ping me for access

**Comment by wy65701436** [comment]
close it as PR merged. https://github.com/goharbor/harbor/pull/10973
