### ISSUE TITLE
新建任何项目显示已经存在

### ISSUE THREAD

**Issue by caipengtao** [goharbor/harbor#8408]
<img width="1392" alt="WeChatf2dbfa30b8c0386a9adc27cb861f0b83" src="https://user-images.githubusercontent.com/19907364/61871537-ac367400-af13-11e9-97e0-c47406d0b2e3.png">

使用aliyun oss作为存储，新建项目时显示项目已经存在，然后没有任何项目，请问是什么问题呢？

**Comment by wy65701436** [comment]
hi @caipengtao, please let us know the harbor version and the configuration that you did.

And the logs are necessary for us to have a debug.

**Comment by caipengtao** [comment]
version：1.8.1
I know the problem,but i don't know how to slove it.
I want to use external proxy nginx , when I use it, it tells me the project exists.
I check the external proxy nginx log,I found 'HEAD /api/projects/?project_name=sdfsdf HTTP/1.1" 200 0', but I check the harbor nginx I found 'GET /api/projects/?project_name=asdfsf HTTP/1.0'.
And I also set #proxy_set_header X-Forwarded-Proto $scheme; in  common/config/nginx/nginx.conf ,and the docker login is ok,and I also set https.
The external proxy nginx conf is
```
upstream harbor {
  server 172.19.8.112:9443;
}

server {
    listen 443 ssl;
    server_name reg.test.com;
    access_log /data/nginxlog/reg.log;
    ssl_certificate /usr/local/nginx/ssl/reg.pem;
    ssl_certificate_key /usr/local/nginx/ssl/reg.key;

    client_max_body_size 0;
    chunked_transfer_encoding on;

    location / {
        proxy_pass https://harbor/;
        proxy_set_header  Host              $http_host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;
    }
}
```
Maybe you can give me some good ideas.

**Comment by qengli** [comment]
+1

**Comment by codinl** [comment]
+1 v2.0

**Comment by FreeLoopC** [comment]
外部nginx默认会将head请求转换为get再发送到harbor的nginx中, 导致harbor一直返回200状态码

harbor根据200状态码认为项目存在, 所以不管输入什么总是提示项目已经存在了

解决办法: 外部nginx添加proxy_cache_convert_head off;

禁用head请求自动转换之后,  harbor就可以正常添加项目了
