### ISSUE TITLE
Update configuration files of Kubernetes setup

### ISSUE THREAD

**Issue by KarstenSiemer** [goharbor/harbor#8409]
The helm chart was created by templating the yaml files for the kubernetes  from this repository
e.g: [config](https://raw.githubusercontent.com/goharbor/harbor/e51d6cc707c83e9eea36ece0d2f9d66b1a71fac8/make/kubernetes/templates/registry.cm.yaml)
or from the helm chart: [config.yml](https://raw.githubusercontent.com/goharbor/harbor-helm/master/templates/registry/registry-cm.yaml)

This file is 2 years old, is still compatible with newer versions of harbor but it is unclear what settings can be made.
For example i wanted to use a s3 backend for storing the images and configure a self signed certificate. The helm chart has no notion of such a possibility. 
But the offical [config guide](https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md) has.
It is written to edit this part of config:
```
storage_service:
  ca_bundle:
```
but the  key storage_service is not available in the config.yml used by the helm chart.
There is only the storage key.
The config.yml gets consumed by the registry container from the directory of `/etc/registry/config.yml`
This is also very confusing since the config file gets called `harbor.yml` all over the documentation.

Is there a reason for this?
If wanted, i'll create a pull request here and in the helm repo to fix all of these issues.

Inside `install_cert.sh` i found that if a ca-bundle is mounted under `/harbor_cust_cert/custom-ca-bundle.crt` it will be appended.
So i mounted a secret with the self signed ca under this directory inside both cotainers of the registry pod (registry & registryctl) and got the success-message inside the logs that it worked:
```
Appending custom ca bundle ...
Done.
```
Then I also add the certificate into the pod of clair, chartmuseum and core.
I am using kustomize to overlay the helm-chart.
Would be great to update the documentation and configuration

For readers of this issue who have the same problem, you also have to disable the redirection call made after a layer is uploaded to be able to push to a storage backend (e.g s3) with a self signed certificate or you have to place the ca into your docker ca directory for the url you are using for harbor.
You can do this via the disableredirect in the helm-chart set to true

**Comment by ywk253100** [comment]
Fixed
