### ISSUE TITLE
Robot account Token Expiration Days can only be a certain range

### ISSUE THREAD

**Issue by kyrogue** [goharbor/harbor#8416]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected:
If we set 3650 ( 10 years ) for the robot expiration, it should be applied successfully

Actual:
We get " strconv.Atoi: parsing "5.256e+06": invalid syntax, item name: robot_token_duration"

**Steps to reproduce the problem:**
Go to System Settings, Set Robot Token Expiration (Days) to 9999 or 3650
We get "strconv.Atoi: parsing "1.439856e+07": invalid syntax, item name: robot_token_duration"

**Versions:**
Please specify the versions of following systems.
- harbor version:  v1.8.1-16b59c41
- docker engine version: GKE
- docker-compose version: GKE

**Comment by balonik** [comment]
While the UI will generate an error you can set any value via API. You can use the Harbor API Explorer to set it or use curl for example.
If  you set 3650 days the Expiration column in the Robot (as well as API call) will show expiration +10 years. But following errors will start appearing in `jobservice.log`:
```
Aug  9 08:45:03 172.18.0.1 jobservice[9700]: 2019-08-09T06:45:03Z [ERROR] [/common/config/store/store.go:67]: error when loading data item, key robot_token_duration, value 5.256e+06, error strconv.Atoi: parsing "5.256e+06": invalid syntax
```

**Comment by wy65701436** [comment]
Hi @kyrogue and @balonik, I have tested on my env, I can create a robot account with 9999 days duration.
 
Also, could use it to do docker login/push/pull, what problem did you face? The error of `strconv.Atoi: parsing "5.256e+06"` won't impact the pull/push workflow.

**Comment by xaleeks** [comment]
But is it actually effective for 9999 days? Is there any way to confirm this like running the time forward

**Comment by xaleeks** [comment]
potentially a doc impact

**Comment by wy65701436** [comment]
I have double confirmed the token string, the duration is `9999` days.

**Comment by xaleeks** [comment]
@kyrogue  Hi please double check this again since engineering confirmed that this is not a bug.

**Comment by bclermont** [comment]
I broke a few things by manually changed DB expirations:

```
2020-04-23T00:00:01Z [ERROR] [/common/config/store/store.go:67]: error when loading data item, key robot_token_duration, value 4.32e+07, error strconv.Atoi: parsing "4.32e+07": invalid syntax
```
