### ISSUE TITLE
harbor1.8 can't login

### ISSUE THREAD

**Issue by 28441585** [goharbor/harbor#8419]
harbor1.8 server is ok, 40+person can login,but only one can't.
### 2.registry.log.A can't login, but B is ok.
_can't login by remoteaddr=10.157.193.115_
Jul 25 16:32:50 172.30.0.1 registry[13521]: time="2019-07-25T08:32:50.289757377Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="10.144.15.219:5000" http.request.id=616d4a68-4938-47e8-ad99-37be92dd3705 http.request.method=GET **_http.request.remoteaddr=10.157.193.115_** http.request.uri="/v2/" http.request.useragent="docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \(linux\))" 
Jul 25 16:32:50 172.30.0.1 registry[13521]: 172.30.0.7 - - [25/Jul/2019:08:32:50 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Jul 25 16:32:50 172.30.0.1 registry[13521]: time="2019-07-25T08:32:50.747846971Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=989a32fe-3081-4318-8bc8-8c8c1cda3e55 http.request.method=GET http.request.remoteaddr="172.30.0.7:49360" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="73.452µs" http.response.status=301 http.response.written=39 
Jul 25 16:32:50 172.30.0.1 registry[13521]: time="2019-07-25T08:32:50.7490102Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=6f01d7d2-d9b1-43b9-b7c5-2563fbc1b7a6 http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="172.30.0.7:49360" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" 

_can login_ 
Jul 26 10:13:22 172.30.0.1 registry[13521]: time="2019-07-26T02:13:22.075767772Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="10.144.15.219:5000" http.request.id=d8d7f6b7-22a3-4027-b652-79de2e756ea8 http.request.method=GET **_http.request.remoteaddr=10.173.9.32_** http.request.uri="/v2/" http.request.useragent="docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \(linux\))" 
Jul 26 10:13:22 172.30.0.1 registry[13521]: 172.30.0.7 - - [26/Jul/2019:02:13:22 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \\(linux\\))"
Jul 26 10:13:22 172.30.0.1 registry[13521]: time="2019-07-26T02:13:22.584550662Z" level=info msg="authorized request" go.version=go1.11.8 http.request.host="10.144.15.219:5000" http.request.id=3d009d49-6cba-4f38-97b2-fe08c82f7c19 http.request.method=GET http.request.remoteaddr=10.173.9.32 http.request.uri="/v2/" http.request.useragent="docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \(linux\))" 
Jul 26 10:13:22 172.30.0.1 registry[13521]: time="2019-07-26T02:13:22.584606901Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="10.144.15.219:5000" http.request.id=3d009d49-6cba-4f38-97b2-fe08c82f7c19 http.request.method=GET http.request.remoteaddr=10.173.9.32 http.request.uri="/v2/" http.request.useragent="docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.475906ms http.response.status=200 http.response.written=2 
Jul 26 10:13:22 172.30.0.1 registry[13521]: 172.30.0.7 - - [26/Jul/2019:02:13:22 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.13.1-cs5 go/go1.7.5 git-commit/21c42d8 kernel/3.10.0-514.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1-cs5 \\(linux\\))"
Jul 26 10:13:24 172.30.0.1 registry[13521]: time="2019-07-26T02:13:24.897422789Z" level=info msg="authorized request" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=8efa3e01-2498-41fd-99c6-981c0a5ab9ee http.request.method=HEAD http.request.remoteaddr="172.30.0.7:43824" http.request.uri="/v2/mcsas/transmission-maintenance-computing/manifests/R1.18.0.7" http.request.useragent=harbor-registry-client vars.name="mcsas/transmission-maintenance-computing" vars.reference=R1.18.0.7 

### **3. daemon.json,**
{
        "insecure-registries": ["registry:5000","192.168.0.102:5000","192.168.0.122:5000"],
        "registry-mirrors": ["http://192.168.0.102:5000"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "10"
        }
}

**Comment by ywk253100** [comment]
Seems it's related with your environment according to the error `read :connection reset by peer`. Closing it.
