### ISSUE TITLE
problems in detail image page

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#8423]
Hi,

Please see below capture.
![image](https://user-images.githubusercontent.com/1247030/61931701-510c8c00-afbc-11e9-8808-e276b9c3ff40.png)

This is based on centos 7.6.

I will write enhancement requests.
1. OS : the page just shows linux, but how about show centos if possible ? 
2. OS Version : shows 7.6 if possible also
3. summary shows 4 high items but it is not. I think this is a bug.
4. click one of the vulnerability items goes through https://access.redhat.com/errata/RHSA-2017:0372 for example, but that shows 404.
5. when click the dropdown button one of the vulnerability items,
there comes two scroll bars like below capture,
![image](https://user-images.githubusercontent.com/1247030/61932145-93829880-afbd-11e9-8c14-69cf588e312e.png)

(I am using Chrome browser.) I can move inside scroll bar using mouse left click, but I can not move outside scroll bar using mouse left click. mouse wheel is OK.

**Comment by Hokwang** [comment]
@ninjadq is this not a bug?

**Comment by Hokwang** [comment]
@wy65701436 Please check 3, 4, 5. These are bug, not enhancement request.

**Comment by reasonerjt** [comment]
`3` is not a bug because there are 4 packages, but there are packages that each of them has more than one vulnerability.
I need to double check `4` but it maybe the data from RHEL is incorrect.

For `5` one scroll bar is for the datagrid and the other one is for the overall pane.

**Comment by Hokwang** [comment]
@reasonerjt Thanks for your reply.
3. This is not a bug, right, I misunderstood.
5. I am using Chrome browser and I can not grab scroll bar for overall pane and also can not move up and down.

**Comment by reasonerjt** [comment]
@Hokwang 
For 4, I believe it's the redhat removed the entry from their website so there's nothing we can do.
For 5 I reproduced the issue, I'll use this issue to track the work to fix item 5

**Comment by reasonerjt** [comment]
@AllForNothing Please fix the problem on UI described in item 5.

**Comment by AllForNothing** [comment]
@reasonerjt @Hokwang

For item 5,it was designed to work like this. Please use mouse wheel to move the overall pane, and use the mouse click to move the datagrid.
