### ISSUE TITLE
helm push with robot account failed

### ISSUE THREAD

**Issue by cafeliker** [goharbor/harbor#8427]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A robot account with helm push permission should be able to successfully perform the activity; but it's failed with the message:
Error: 403: could not properly parse response JSON: {"code":403,"message":"robot$helm-test"}
Error: plugin "push" exited with error

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
I created a robot account with helm create permission through API as below:
{
  "name": "helm-test",
  "description": "helm test account",
  "access": [
    {
      "resource": "project/4/repository",
      "action": "push"
    },
    {
      "resource": "project/4/helm-chart",
      "action": "read"
    },
    {
      "resource": "project/4/helm-chart-version",
      "action": "create"
    }
  ]
}

The account was successfully created, but helm push failed.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.2-rc1 (about page shows v1.8.2-b24a0e33)
- docker engine version: 18.06.1-ce
- docker-compose version: 1.24.0, build 0aa59064

**Comment by MaGaoju** [comment]
[chartmuseum.log](https://github.com/goharbor/harbor/files/3435102/chartmuseum.log)

[core.log](https://github.com/goharbor/harbor/files/3435118/core.log)
core and chartmuseum log attached

**Comment by wy65701436** [comment]
please let me know the exact steps that you did at the helm client.

**Comment by cafeliker** [comment]
I ran the command:
helm push --username 'robot$helm-test' --password 'xxxxx' ./harbor-helm/ rnd-it-helm-repo

**Comment by reasonerjt** [comment]
Verified this is fixed.

**Comment by verwilst** [comment]
I'm running into the same issue. Where/when exactly is this fixed?

**Comment by lfdominguez** [comment]
I having exactly this issue....

**Comment by megantexo** [comment]
I have this issue as well, with robot accounts. What was the solution?

**Comment by TomHellier** [comment]
I'm also having this issue @reasonerjt do you remember how this was working? I'm deploying harbor using the helm chart, and when I created a robot account in the helm repository, it was just giving Unauthorized back.

Also, for some reason, I can only helm push with an administrator account.
