### ISSUE TITLE
installed failed

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#8431]
when I installed harbor by source code，followed the developer doc :
 Step 1: Prepare for a build environment for Harbor;
Step 2: Getting the source code;
Step 3: Building and installing Harbor:
            1、docker pull golang:1.12.5；
            2、make install GOBUILDIMAGE=golang:1.12.5 COMPILETAG=compile_golangimage。
then, it report error as following:
error:      Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.160.80|:443... failed: Connection refused.

I opened the network proxy to access the extranet, but it also didn't work...

so, have some address else?

**Comment by wy65701436** [comment]
it should be a network issue at your end, you have to figure it out.  Also, you can go through the code https://github.com/goharbor/harbor/blob/master/make/photon/Makefile, to build from locally if you can download the binary manually.

**Comment by tongying123456** [comment]
> it should be a network issue at your end, you have to figure it out. Also, you can go through the code https://github.com/goharbor/harbor/blob/master/make/photon/Makefile, to build from locally if you can download the binary manually.

**Comment by tongying123456** [comment]
> it should be a network issue at your end, you have to figure it out. Also, you can go through the code https://github.com/goharbor/harbor/blob/master/make/photon/Makefile, to build from locally if you can download the binary manually.

I tried download the binary in my local $(CURDIR)/bin/registry，then I edit the https://github.com/goharbor/harbor/blob/master/make/photon/Makefile as follow:
$(mv) $(CURDIR)/bin/registry $(DOCKERFILEPATH_REG)/binary/registry ; \
but when I make , it reported  as follow:
/bin/bash: line 2: /home/yy/Desktop/harbor-1.7.0/make/photon/bin/registry: Permission denied

**Comment by tongying123456** [comment]
I tried put the binary in the hithub, it can resolve...
but, i have another error:
recipe for target '_build_migrator' failed.

**Comment by tongying123456** [comment]
> it should be a network issue at your end, you have to figure it out. Also, you can go through the code https://github.com/goharbor/harbor/blob/master/make/photon/Makefile, to build from locally if you can download the binary manually.

thanks, it's a good idea
