### ISSUE TITLE
group role not honored for user group support in http auth mode - overwritten by user role

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#8432]
**Expected behavior and actual behavior:**
Expected: 
if a user with guest role in a project belongs to a project member group that has master role, the user should be able to push images since its user group has the role
Actual:
if a user with guest role in a project belongs to a project member group that has master role, the project member group role is not honor and the user is not able to push images

**Steps to reproduce the problem:**
0. assign user A to user group B on the identity provider side
1. create a Harbor project
2. assign guest role to user A in the project
3. assign master role to group B in the project
4. docker login as user A, and try to tag and push an image to the project

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.2]

**Configurations**
Harbor auth is configured with http_auth mode

**Comment by reasonerjt** [comment]
The PRs fixed #8433 , reopening this issue

**Comment by reasonerjt** [comment]
@ericvmw 
Currently the design is that if a user is added to a project as a user member, his role overwrites the the role of the group he is in.

I think what you expect is also reasonable but changing this will introduce some sort of break, I hope we can have some time to discuss and decide.

**Comment by xaleeks** [comment]
> @ericvmw
> Currently the design is that if a user is added to a project as a user member, his role overwrites the the role of the group he is in.
> 
> I think what you expect is also reasonable but changing this will introduce some sort of break, I hope we can have some time to discuss and decide.

This is not consistent with the resolution of #8433 right? where we take the higher privilege of the two.  

I think the deciding question is can the user do anything to override the permissions set for him by someone of higher privilege in order to gain additional access to a project that was not originally intended for him

**Comment by reasonerjt** [comment]
@xaleeks I think either the user cannot gain additional access.  But yes this does not look consistent with #8433 

Currently I'm thinking we can have it fixed in 1.8.2 and write a release note to point it out.

**Comment by reasonerjt** [comment]
Fixed in #8557 and #8560 
Closing.

**Comment by xaleeks** [comment]
https://github.com/goharbor/harbor/blob/master/docs/manage_role_by_ldap_group.md
hey Daniel, you already changed the last section there but maybe can provide some more details on how they are merged?
