### ISSUE TITLE
not all group roles are honored for user group support in http_auth mode

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#8433]
**Expected behavior and actual behavior:**
Expected:
if a user belongs to group A (that has guest role in project 1) and group B (that has master role in project 1), the user should be able to push images to project 1 since its user group B has master role in the project (a common practice)
Actual: 
if a user belongs to group A (that has guest role in project 1) and group B (that has master role in project 1), the user is not able to push images to project 1. It looks the auth takes the group role with lower privilege.

**Steps to reproduce the problem:**
0. add user to group A and group B on identity provider side
1. create a project 1
2. add group A to project 1 as a guest member
3. add group B to project 1 as a master member
4. user to tag and push images to project 1

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.2]

**Additional context:**
Harbor auth is configured with http_auth mode

**Comment by reasonerjt** [comment]
fixed by #8446 and #8447
