### ISSUE TITLE
Enable manual update for clair database

### ISSUE THREAD

**Issue by shashank-k** [goharbor/harbor#8452]
**Is your feature request related to a problem? Please describe.**
The clair database always seems to be outdated

**Describe the solution you'd like**
Can we have a way to manually pull the latest vulnerabilty database with out going through the steps mentioned in this [link](https://github.com/goharbor/harbor/blob/master/docs/import_vulnerability_data.md) even when the host has internet access

**Comment by reasonerjt** [comment]
The updater of Clair can only be triggered by a scheduler.  as for your issue we need to understand what's the reason the updater is not triggered as scheduled.

**Comment by shashank-k** [comment]
I have opened another issue #8468 which describes the same. Can you please look into it and let me know where the issue is. If required this can be closed.

**Comment by shashank-k** [comment]
As per the previous comment closing this.
