### ISSUE TITLE
installed by source code, why no need make?

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#8471]
when i installed harbor by source code, why make install directly no need make first?
after i modified the code, then make install, it had not changed, It is still the previously loaded harbor ?
what should i do to run my modified code?

**Comment by reasonerjt** [comment]
A shortcut is to compile the code and replace it in the container.

@wy65701436 could you check why `make install` does not take updated code into account.

**Comment by wy65701436** [comment]
`make install` will always compile, build with the modified code from local, and there is no cache. @tongying123456 I do not clearly understand your question, can you explain more?
