### ISSUE TITLE
Guest Users should not be able to view members

### ISSUE THREAD

**Issue by jkjell** [goharbor/harbor#8473]
**Is your feature request related to a problem? Please describe.**
Our instance of Harbor is integrated with UAA.  In this case the UAA usernames are the email address of the user.  A guest user, can then see the email addresses of all members of a project but, we do not want them to see that information.

**Describe the solution you'd like**
Don't allow guest users to view all members of a project.

It seems as though it could be easy to remove these permissions by removing the two lines [here](https://github.com/goharbor/harbor/blob/master/src/common/rbac/project/visitor_role.go#L241).

**Additional context**
I'm also not even sure of the value of allowing guest role users to view all members?  What is the intent of that feature?  Knowing this will allow us to determine the impact of removing that functionality from all current Harbor users.

**Comment by xaleeks** [comment]
what was the original intent behind allowing guest to view other members? @reasonerjt @steven-zou

**Comment by xaleeks** [comment]
This is now possible with the 'limited guest' role , see commit here https://github.com/goharbor/harbor/commit/558ac7763066f7716089d3d188c45df78824f61d
