### ISSUE TITLE
Clair /tmp consuming large amounts of disk space

### ISSUE THREAD

**Issue by troy256** [goharbor/harbor#8474]
**Expected behavior and actual behavior:**
The /tmp directory inside the clair container is 100 GB in size on our Harbor v1.8.1 system.  It is mainly ubuntu-cve-tracker* dirs, nvd-data* dirs and nvd-data-*.xml files.  As far as I can tell the /tmp directory continues to grow and is not automatically cleaned.  We had to manually remove some of the older files and dirs from /tmp to keep the Dockerhost from running out of disk space.  I would expect clair to manage /tmp automatically or possibly a setting in common/config/clair to enable automatic cleanup or otherwise limit disk consumption.

**Steps to reproduce the problem:**
Deploy Harbor v1.8.1 with vulnerability scanning and monitor the size of /tmp inside clair.

**Comment by reasonerjt** [comment]
@troy256 
May I know how long have you been running this Harbor instance and it consumes 100GB in `/tmp`?
Conventionally if you restart the `/tmp` is removed.  It's the behavior of OS, not Clair.

**Comment by troy256** [comment]
It was running for about 90 days.  Is it OK to schedule periodic restarts of the clair container via cron/systemd by doing a "docker-compose stop/start clair"?

**Comment by reasonerjt** [comment]
I haven't tried the particular command but if the Clair is not scanning image or pulling data from internet, it should be fine.

I wish to suggest you open an issue on clair's repo for more information.  
There has been some issue opened:
https://github.com/coreos/clair/issues/208

I'll also double check the code of Clair when I have time.  There seems to be something that can be approved on Clair side.

**Comment by reasonerjt** [comment]
We may consider mount the /tmp to some directory in host, so that user can remove files more easily without having to restart the containers.

**Comment by jegger** [comment]
We have the same issue. We have available local disk space of 50GB and it gets filled up very quickly (once a week). I recently updated to the newest harbor version and I do not recall experience that issue before. However we have more images in harbor which could also be a factor (I do not know how claire works). Mounting the /tmp folder would be a good option for us. I don't like killing the container by crone. 

I am surprised no one other is running into this. I wonder if it could be a configuration issue on our side?

**Comment by RezaBabapour** [comment]
I have same issue and this is output of `docker ps --size` :
```
56f419570cfb        goharbor/clair-photon:v2.1.0-v1.9.3                      "/docker-entrypoint.…"   34 hours ago        Up 14 minutes (healthy)   60
60-6061/tcp                                                         clair               72.7GB (virtual 72.9GB) 
```

**Comment by nisc-acooper** [comment]
I can confirm we see this issue as well with 1.10.0.   the OS sees about 60GB used in /var/lib/docker, inside the clair container we see about 30GB used in /tmp.  The container has been up about 1 month.

docker ps --size
```
887faf6a23de        goharbor/clair-photon:v2.1.1-v1.10.0                      "./docker-entrypoint…"   4 weeks ago         Up 4 weeks (healthy)   6060-6061/tcp                                 clair               30.3GB (virtual 30.5GB)
```

/tmp in clair
```
716K	./alpine-secdb041623600
716K	./alpine-secdb086834661
716K	./alpine-secdb099923055
716K	./alpine-secdb128458670
716K	./alpine-secdb152664093
716K	./alpine-secdb202333565
716K	./alpine-secdb248575706
716K	./alpine-secdb289564192
716K	./alpine-secdb314325520
716K	./alpine-secdb364040359
716K	./alpine-secdb387565066
716K	./alpine-secdb534221030
716K	./alpine-secdb572559276
716K	./alpine-secdb574234525
716K	./alpine-secdb665696640
716K	./alpine-secdb670460851
724K	./alpine-secdb817369566
716K	./alpine-secdb922902567
1.5G	./nvd-data063224182
1.5G	./nvd-data077594081
1.5G	./nvd-data202524418
1.5G	./nvd-data222197426
1.5G	./nvd-data225711330
1.5G	./nvd-data238256437
1.5G	./nvd-data318808152
1.5G	./nvd-data325668607
248M	./nvd-data329061797
1.5G	./nvd-data473705144
1.5G	./nvd-data521506417
1.5G	./nvd-data553708827
1.5G	./nvd-data582552623
1.5G	./nvd-data666013146
1.5G	./nvd-data681771736
1.5G	./nvd-data834835725
1.5G	./nvd-data943592960
1.5G	./nvd-data945611610
281M	./ubuntu-cve-tracker103219766
281M	./ubuntu-cve-tracker145817886
281M	./ubuntu-cve-tracker183976675
281M	./ubuntu-cve-tracker204497232
281M	./ubuntu-cve-tracker252951959
281M	./ubuntu-cve-tracker337771496
281M	./ubuntu-cve-tracker380873654
281M	./ubuntu-cve-tracker419242447
281M	./ubuntu-cve-tracker510970591
281M	./ubuntu-cve-tracker560913541
281M	./ubuntu-cve-tracker613507862
281M	./ubuntu-cve-tracker682430273
281M	./ubuntu-cve-tracker742174824
281M	./ubuntu-cve-tracker833735221
281M	./ubuntu-cve-tracker885850827
281M	./ubuntu-cve-tracker889807271
281M	./ubuntu-cve-tracker972320932
```

**Comment by piengeng** [comment]
Anyone looking into this issue? I'm facing the same issue, harbor is not doing nothing much, (basically idling), with a few small images, yet, it's taking up so much space in /tmp

```
clair [ /tmp ]$ du -sh *
828K    alpine-secdb110958158
820K    alpine-secdb217594680
828K    alpine-secdb236746604
820K    alpine-secdb441134341
820K    alpine-secdb703130833
1.5G    nvd-data275543548
1.5G    nvd-data484585947
1.5G    nvd-data493531808
1.5G    nvd-data738180784
1.5G    nvd-data875560759
283M    ubuntu-cve-tracker102511101
286M    ubuntu-cve-tracker206254421
285M    ubuntu-cve-tracker207365306
285M    ubuntu-cve-tracker409336321
284M    ubuntu-cve-tracker729552062 
```

**Comment by piengeng** [comment]
There's no one looking into this, for everyone else that reached this page during research, just want to share my workaround using bash+crontab on the harbor's host. I'm forcefully deleting folders in /tmp with below upper limit (2500000). 

```bash
#!/bin/bash
# this file ~/cleantmp.sh
# 0 * * * * bash ~/cleantmp.sh
dcFile=~/harbor/docker-compose.yml
tmpSize=$(sudo /usr/local/bin/docker-compose -f $dcFile exec -T clair bash -c "du -s /tmp" | awk '{print $1}' | tr -d '[:space:]')
limit=2500000
if [ "$tmpSize" -gt "$limit" ]; then
  sudo /usr/local/bin/docker-compose -f $dcFile exec -T clair bash -c "find /tmp -maxdepth 1 -type d -mmin +1080 ! -path /tmp | xargs rm -r"
  echo `date --rfc-3339=seconds` "$tmpSize (kB) over $limit, cleaning up." > /tmp/cleaned.log
else
  echo `date --rfc-3339=seconds` "$tmpSize (kB) below $limit, do nothing." > /tmp/checked.log
fi
```
Taking above 100GB case, I highly doubt during scanning, clair will be taking 100GB and use it to scan each and every images with this 100GB data. It'd be too slow to be processed. Convention says to be fast, 100GB has to be loaded into memory, not sure everyone is setting up harbor+clair with machine installed this amount of RAM.

**Comment by PedroJurado** [comment]
I have the same problem with version 1.10.3, clair container take almost all the space available. We have other versions installed and can't see this problem.

Production 1.9.4 No problem
Staging 1.10.3 Too much space
Test 2.0.0 No problem

I would say this is problem related to the 1.10.X version as others do not show any issues. If this is not solve we will be forced to upgrade directly to version 2.0.X

**Comment by AstraLuma** [comment]
It looks like the upstream issue was closed before this was ever opened.

It was clearly not fixed.

**Comment by AstraLuma** [comment]
shush stalebot

**Comment by Gui13** [comment]
We also have the problem. This is not too dramatic but we have 10's of GBs of /tmp idling there.

**Comment by reasonerjt** [comment]
it's safe to remove the data in `/tmp` 
As we have dropped the support of Clair since v2.2.

I will close this issue as this requires change in the upstream clair's code to fix the problem, and we're not likely to do anything about it in future.

**Comment by leofang94** [comment]
I have the same problem in harbor 1.10.1 with goharbor/clair-photon:v2.1.1-v1.10.1
Refer to some suggestions above, I mount tmp directory in host machine.
1. Use /var/lib/docker/tmp as mount dir
![image](https://user-images.githubusercontent.com/25113486/162191926-0ae6f858-352f-4628-b0b7-b6fda158b924.png)
chmod host mount dir for data-writing in container: chmod 1777 /var/lib/docker/tmp

2. Config volumes mount in docker-compose.yaml
![image](https://user-images.githubusercontent.com/25113486/162192686-69eef525-fe65-4cb7-a37d-ed649ec16bec.png)

3. Stop and remove all harbor containers

4. Clean up data in /var/lib/docker/overlay2

5. Clean up data in /var/lib/docker/image/overlay2/layerdb/sha256

6. Restart docker service

7. Reinstall harbor 

Finally, data will be write in host
![image](https://user-images.githubusercontent.com/25113486/162193580-5aae83aa-e2c8-4df3-b0e5-88b19c3e3579.png)

Tips:
Some harbor install script as bellow, before docker-compose install harbor, it will prepare some necessary file.  
![image](https://user-images.githubusercontent.com/25113486/162193805-d3f7165a-6224-4e8b-90a4-572232ddc717.png)

prepare will generate docker-compose.yaml as bellow directory, if docker-compose.yaml existed already, so you can change generate directory to avoid overwriting it.
![image](https://user-images.githubusercontent.com/25113486/162195325-4a9340ce-4ded-4354-95bd-abd970e87adf.png)

**Comment by leofang94** [comment]
> **Expected behavior and actual behavior:** The /tmp directory inside the clair container is 100 GB in size on our Harbor v1.8.1 system. It is mainly ubuntu-cve-tracker* dirs, nvd-data* dirs and nvd-data-*.xml files. As far as I can tell the /tmp directory continues to grow and is not automatically cleaned. We had to manually remove some of the older files and dirs from /tmp to keep the Dockerhost from running out of disk space. I would expect clair to manage /tmp automatically or possibly a setting in common/config/clair to enable automatic cleanup or otherwise limit disk consumption.
> 
> **Steps to reproduce the problem:** Deploy Harbor v1.8.1 with vulnerability scanning and monitor the size of /tmp inside clair.

https://github.com/goharbor/harbor/issues/8474#issuecomment-1091659082

**Comment by reasonerjt** [comment]
We have shifted away from using Clair as the default image scanner.  Therefore, I don't think there's anything we'll do to fix Clair-related issues on Harbor's end.

I'm closing this issue.
