### ISSUE TITLE
chart的name参数定义带数字后删除不了

### ISSUE THREAD

**Issue by fengshunli** [goharbor/harbor#8477]
![image](https://user-images.githubusercontent.com/18587688/62094521-0c307000-b2b0-11e9-934d-c83355075526.png)

**Comment by ninjadq** [comment]
This is caused by a [bug](https://github.com/helm/chartmuseum/issues/261) from chartmuseum
currently no better solution to solve this, you can change your chart's name pattern. ep. `fengshunli-mongodb_89`

**Comment by fengshunli** [comment]
No - just write fengshunli-mongodb89 is ok

**Comment by ninjadq** [comment]
@fengshunli because there is no`-` between the `mongodb` and `89`
