### ISSUE TITLE
往1.8版本升级应该保留认证模式为可选

### ISSUE THREAD

**Issue by ali94s** [goharbor/harbor#8479]
如果默认是数据库的认证模式，则低版本升级时不能修改认证模式，需要删除数据库中的用户，但是ldap的用户和项目是有关联的，所以低版本使用ldap的很难升级到1.8并且保留原有的ldap

**Comment by ywk253100** [comment]
意思是如果低版本Harbor使用的是LDAP的认证模式，升级到1.8后会变成数据库认证模式吗？

**Comment by lijianfeng1993** [comment]
如果低版本用的ldap认证模式，升级到harbor1.8后，会自动配置好ldap配置的。我从1.7升到1.8，没有问题

**Comment by reasonerjt** [comment]
@ali94s please answer @ywk253100 's question

**Comment by ali94s** [comment]
不好意思，可能是我操作问题，现在已经解决这个问题了

**Comment by ali94s** [comment]
我们之前是1.3版本，现在升级到了1.8版本，没有完全按照github上的文档，但是基本是按照文档中的逻辑，因为我们的存储都是单独出来的，所以之前
升级的时候我是把数据库数据导出来一份，在升级的环境中对数据库升级到Postgresql，然后启动了一个1.8的数据库容器，将数据库数据导出，最后把升级后的数据库数据导入到我们的数据库中。
	在本地验证这个升级方案的时候，遇到了ldap问题，因为数据库数据是从生产环境导出的一份，在按照上面的方式升级到1.8之后，用户认证模式是数据库，但是用户管理可以看到我所有的ldap用户，这也让我很困惑。升级线上的时候为了保险，我中途开了一个1.7的版本，因为1.6以上用的都是postgresql数据，我在启动的时候在配置文件中配置了ldap，启动harbor访问，用户认证是ldap，然后我直接导出数据库数据到线上，完成了我的升级。
	在升级后我又在本地验证了这个问题，定位当时的原因可能是我本地测试方案的时候，启动了一个1.3版本的harbor，并没有配置ldap，但是我导入了我们的数据库，并且对数据库进行了升级，然后导入了1.8版本，导致认证模式有问题。
	第一时间以为harbor的升级存在这样的问题，后面验证是操作的问题，非常抱歉

**Comment by stonezdj** [comment]
如果升级过程中没有认证模式没有被修改，那么升级完之后不应该是可选的
