### ISSUE TITLE
镜像不能删除，镜像记录存在，并且大小显示为0

### ISSUE THREAD

**Issue by heidsoft** [goharbor/harbor#8481]
手动删除了镜像，但是还在。
![image](https://user-images.githubusercontent.com/1329974/62103995-d8197700-b2d0-11e9-99b4-1e767238485e.png)

**Comment by reasonerjt** [comment]
@heidsoft

This is known issue for upstream registry project.

@wy65701436 
Please help dup the issues and provide suggestions to work around.

**Comment by heidsoft** [comment]
@reasonerjt thanks
