### ISSUE TITLE
Owner is always empty in quota page.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8493]
Cannot know what is it for? admin? creator?

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/2841473/63341596-270c7680-c37c-11e9-9a8f-24cfbd28c462.png">

**Comment by jwangyangls** [comment]
@wy65701436 @heww ,If the creater exists，I think it should be creater ,else it should be admin.
Do you need to consult an image designer in this area?

**Comment by wy65701436** [comment]
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/2841473/63341575-178d2d80-c37c-11e9-98b1-28d710777cca.png">
