### ISSUE TITLE
Unable to run tagd harbor v.1.8.1 with oidc

### ISSUE THREAD

**Issue by Andreiaotto** [goharbor/harbor#8496]
Hi, I'm trying to use tagd on harbor v.1.8.1, auth OIDC with Azure AD in kubernetes, using tagd:1.7.2. 

We already tried multiple things, but always the same issue, with or without https:
`[11:13:10 WRN] Ignoring Certificate Errors`
`[11:13:10 INF] Loading rules using Harbor.Tagd.Rules.FilesystemRuleProvider`
`[11:13:10 WRN] Not running in report-only mode. Tags will be deleted`
`[11:13:10 INF] Connecting to https://mydomain.com as harboruser`

`[11:13:10 WRN] Tags will be deleted when matched!`
`[11:13:10 FTL] An Error was encountered while processing tags`
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 `(Forbidden).`
  ` at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()`
 `  at Harbor.Tagd.API.HarborClient.<Login>d__13.MoveNext() in` `/home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/API/HarborClient.cs:line 80`
`--- End of stack trace from previous location where exception was thrown ---`
 `  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`
 `  at` `System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task `task)`
 `  at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in` `/home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 64`
`--- End of stack trace from previous location where exception was thrown ---`
  ` at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`
 `  at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in` `/home/travis/build/HylandSoftware/Harbor.Tagd/src/HarborTagd/TagEngine.cs:line 99`
`--- End of stack trace from previous location where exception was thrown ---`
  ` at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`
  ` at Harbor.Tagd.TagEngine.<Process>d__9.MoveNext() in` `/home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/TagEngine.cs:line 106`
`--- End of stack trace from previous location where exception was thrown ---`
   `at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`
  ` at ``System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`
`   at Harbor.Tagd.Program.<DoClean>d__3.MoveNext() in /home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 128
--- End of stack trace from previous location where exception was thrown ---`
`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ``System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`
  ` at Harbor.Tagd.Program.<Main>d__2.MoveNext() in` `/home/travis/build/HylandSoftware/Harbor.Tagd/src/Harbor.Tagd/Program.cs:line 98`

On harbor core pod logs I see `403 |  match| POST     /c/login   r:/c/login`
 
I'm using the CLI secret from the UI -> user profile to connect from tagd, docker login works from my machine, but no success to run tagd.

Any idea?

If this is not the right place to post it, please let me know where it should be.

Thank you!

**Comment by Andreiaotto** [comment]
It's also failing with the same log for the admin (local) user, that should have nothing with the oidc integration.
Any idea to have more logs to better troubleshoot?

Thank you!

**Comment by reasonerjt** [comment]
I'm not very sure how Tagd is implemented as it's a project maintained by community user.

But I guess in your setting tagd is trying to access Harbor's API using CLI secret, that won't work because the CLI secret is from docker and helm cli only to access API in OIDC mode you need to use the id token.

**Comment by Andreiaotto** [comment]
Hi @reasonerjt looks like tagd doesn't support this scenario with current implementation, as you said some code need to be updated.
I tested harbor dev version and it has quotas and tag retention policy per project, do you know when this features will be released?

Thank you!

**Comment by Andreiaotto** [comment]
It turns out to work only with the admin local user in harbor. For now, not supported with oidc users.
