### ISSUE TITLE
Enable UAA Authorization Bearer capability

### ISSUE THREAD

**Issue by joeeltgroth** [goharbor/harbor#8497]
**Expected behavior and actual behavior:**
When Harbor is configured to use UAA as the authentication mechanism, the UAA
api provides an access token (id_token) for a user. This token should be usable as an "Authorization bearer" header when making requests to Harbor API. 

We want to follow the OAuth2 pattern that avoids using basic authentication.  Access tokens have a validity period (they expire). 

**Steps to reproduce the problem:**
1) Create a user in UAA. 
2) Fetch the id_token for that user: 

curl -s https://<uaa-endpoint>/oauth/token -d 'client_id=<id>&client_secret=<secret>&grant_type=password&username=<username>&password=<password>&token_format=opaque' -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded'

3) Use that token to make calls to the Harbor api.  For example: 
curl -X GET https://<harbor-endpoint>/api/users/current -H "Authorization: Bearer <token>”

But, the response is "{"code":401,"message":"UnAuthorize"}"

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.1]

**Comment by reasonerjt** [comment]
@joeeltgroth may I know are you a user of harbor tile?

**Comment by joeeltgroth** [comment]
No, we are using the Helm install of Harbor. 

Can you point us to some documentation that shows how UAA should be configured as an OIDC provider for acceptable use in Harbor?

**Comment by joeeltgroth** [comment]
With the OIDC suggestion, we were able to accomplish this.  Thanks!  The issue can be closed.  Here's how we did it. 

### Create a UAA client with:

curl 'https://<uaa_host>/oauth/clients' -i -X POST \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer <bearer token of admin uaa client>' \
    -d '{
  "scope" : [ "openid", "profile", "offline_access", "email" ],
  "client_id" : "<client_id>",
  "client_secret" : "<client_secret>",
  "resource_ids" : [ ],
  "authorized_grant_types" : [ "client_credentials", "password", "authorization_code", "refresh_token" ],
  "redirect_uri" : [ "http://<harbor_host>/c/oidc/callback" ],
  "authorities" : [ "openid", "profile", "offline_access", "email" ],
  "token_salt" : "<anysalt>",
  "name" : "<client_name>"
}'


### On Harbor, Administration > Configuration > Authentication

Set Auth Mode to OIDC
OIDC Provider Name: <client_name>
OIDC Endpoint: https://<uaa_host>/oauth/token
OIDC Client ID: <client_id>
OIDC Client Secret: <client_secret>
OIDC Scope: openid,profile,email,offline_access
Verify Certificate: true


### To get the bearer tokens used to call harbor apis:

curl -s https://<uaa_host>/oauth/token -d 'client_id=<client_id>&client_secret=<client_secret>&grant_type=password&username=<user_username>&password=<user_password>&token_format=opaque' -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded'

### Sample Harbor api call: 
curl -X GET "http://<harbor_host>/api/projects" -H "accept: application/json" -H "Authorization: Bearer <id_token>"

**Comment by reasonerjt** [comment]
Thanks @joeeltgroth
