### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by RorschachChan** [goharbor/harbor#8512]
I found a strange phenomenon: i can use username:password to login the Harbor Web console successfully

But i when i use that in "docker -D login domain.com",the result is "unauthorized: authentication required".

Help me,plz and thank u.

**Comment by AntonTsaberyaby** [comment]
I have same issue

**Comment by jcmartins** [comment]
Verify if your certificate SSL is valid.

**Comment by RorschachChan** [comment]
> 
> 
> Verify if your certificate SSL is valid.

thank u, i forgot to use https and 443 in _harbor.yml_,when i fix that,it works!
