### ISSUE TITLE
Update to cron v3

### ISSUE THREAD

**Issue by robfig** [goharbor/harbor#8513]
I see you use the robfig/cron package, and I don't see any go.mod file that pins you to a specific version. I'm not sure if you have some other mechanism to get a specific revision, but I wanted to alert you that if you use "go get", I'm planning to push a backwards incompatible change, to bump the default version from v1 to v3. 

Ref:
https://groups.google.com/forum/m/#!topic/golang-nuts/elraGIpy52Q

Happy to hear feedback on the issue:
https://github.com/robfig/cron/issues/213

Thanks

**Comment by reasonerjt** [comment]
@robfig  thanks for the heads up.
We actually pin to v1:
https://github.com/goharbor/harbor/blob/master/src/go.mod#L66

**Comment by reasonerjt** [comment]
@wy65701436 
Could you evaluate whether we should bump to v3?
By a quick look I think we should?

**Comment by wy65701436** [comment]
it will cause incompatibility problem, @steven-zou we need to discuss it more in details, and what's the benefit we can get.

**Comment by reasonerjt** [comment]
We've pinned to v1 and update to v3 may introduce break-change.
