### ISSUE TITLE
通过api接口删除了镜像,并且定时执行gc任务，但是磁盘空间没有完全释放

### ISSUE THREAD

**Issue by heidsoft** [goharbor/harbor#8518]
迁移前的状态-老的harbor仓库
![图片](https://user-images.githubusercontent.com/1329974/62260475-a1646d80-b444-11e9-8e07-16ddceab2a96.png)

迁移后的状态-新的harbor仓库
![图片](https://user-images.githubusercontent.com/1329974/62260491-acb79900-b444-11e9-9be0-798df262f1fc.png)

前后对比，迁移所有仓库，在新harbor上的磁盘空间占比，远小于老的harbor仓库。

**Comment by renmaosheng** [comment]
迁移是指replication吗？

**Comment by heidsoft** [comment]
对，使用复制管理功能同步的

**Comment by renmaosheng** [comment]
Add Yan to check whether GC cleaned the disk or not.

**Comment by wy65701436** [comment]
@heidsoft can you please provide the GC log at your original harbor node? and what's your harbor version?

**Comment by heidsoft** [comment]
@wy65701436 暂时没这个日志，下次碰到在提下，我先关了
