### ISSUE TITLE
The persisted data of redis becomes huge in some environment.  The mem usage is also huge.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8537]
In a debug session I noticed the size of `/data/redis` folder in a user's env is more than 2GB.

This user has more than 1TB image data and thousands of images.  After a few upgrades.

We need to investigate the reason, the current suspicion is that js is not removing the job data frequently enough, but we will have to get more info from user to better debug.

**Comment by cudneys** [comment]
I believe this is related to an issue that we're seeing with Redis memory & disk usage.

We have a Harbor v1.8.1 instance running with a few thousand containers that consume about 92G.  The Redis data directory is 8.6G, and that space is used as follows:
```
7.3G    dump.rdb
512M    temp-224.rdb
1.3G    temp-3163.rdb
```
What's more concerning than the persistent data is the memory utilization.  Redis is gobbling up 19.82G of RAM and it's only going up.  We've purged about two thousand containers from the system to see if that affects this, and it appears as though it does not.  

I've attached a graph showing the memory utilization over the last 10 days.  The drop toward the right of the graph is a server reboot.  

![image](https://user-images.githubusercontent.com/756878/62368563-f95dab80-b4fa-11e9-96ff-0a22b49ab9ce.png)

**Comment by reasonerjt** [comment]
@cudneys
Thanks for chiming in.  Generally speaking I believe it's due to the excessive data in redis.

Could you please let us verify on your env:
1.  Have you setup a lot of `replication` and `scan all` jobs?
2.  As for the tempxxx.rdb files, do they disappear after a few mins?
3.  If you don't have strong concerns could you share us the `dump.rdb` file via gcs or some other cloud storage.
4.  If `3` is not possible could you use `redis-cli` to check the info of db `1`,`2` and `3` respectively?  You can run `select 1` and `info` in redis console.

Your help is appreciated!

**Comment by reasonerjt** [comment]
@cudneys 
Could you provide the information needed for further debugging?

**Comment by cudneys** [comment]
I’m really sorry about the delay!  I’ll have that info to you today

**Comment by cudneys** [comment]
**Have you setup a lot of replication and scan all jobs?**

We have 13 replications set up (all pull-based), and they're set to run manually.
Scan jobs run every 2 hours (0 */2 * * * *)

**As for the tempxxx.rdb files, do they disappear after a few mins?**

They do disappear.  The only file in my redis store is dump.rdb and it's 12GB

**If you don't have strong concerns could you share us the dump.rdb file via gcs or some other cloud storage.**

I don't have any concerns, but my security department may.  I'll have to check with them and see what can be done.
    
**If 3 is not possible could you use redis-cli to check the info of db 1,2 and 3 respectively? For example, you can run info in redis console, and let us know the output.**

The output from "info" is:

`127.0.0.1:6379> info
# Server
redis_version:4.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4dcacd25361b6020
redis_mode:standalone
os:Linux 4.15.0-58-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:9
run_id:c1a96851316a585f2b3ebb305aed652e8137ee91
tcp_port:6379
uptime_in_seconds:84716
uptime_in_days:0
hz:10
lru_clock:6129915
executable:/var/lib/redis/redis-server
config_file:/etc/redis.conf

# Clients
connected_clients:23
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:31532369200
used_memory_human:29.37G
used_memory_rss:32359702528
used_memory_rss_human:30.14G
used_memory_peak:31532435312
used_memory_peak_human:29.37G
used_memory_peak_perc:100.00%
used_memory_overhead:1973351354
used_memory_startup:786528
used_memory_dataset:29559017846
used_memory_dataset_perc:93.74%
total_system_memory:33726189568
total_system_memory_human:31.41G
used_memory_lua:77824
used_memory_lua_human:76.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.03
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:169549
rdb_bgsave_in_progress:1
rdb_last_save_time:1566410896
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:275
rdb_current_bgsave_time_sec:46
rdb_last_cow_size:87011328
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1095858
total_commands_processed:34147509
instantaneous_ops_per_sec:991
total_net_input_bytes:4759360501
total_net_output_bytes:883532677
instantaneous_input_kbps:130.84
instantaneous_output_kbps:27.25
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:4886340
expired_stale_perc:3.96
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:8424350
keyspace_misses:8853033
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:487995
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:a83ee2e29dee18a716fb5f346db8304eeada8331
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:1058.52
used_cpu_user:829.47
used_cpu_sys_children:5421.65
used_cpu_user_children:53111.98

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=253907,expires=253906,avg_ttl=1904762
db1:keys=7549,expires=0,avg_ttl=0
db2:keys=22033372,expires=22033323,avg_ttl=13485830904
db3:keys=31,expires=0,avg_ttl=0
127.0.0.1:6379>
`
Memory Stats:

`
127.0.0.1:6379> memory stats
 1) "peak.allocated"
 2) (integer) 31535691504
 3) "total.allocated"
 4) (integer) 31535516096
 5) "startup.allocated"
 6) (integer) 786528
 7) "replication.backlog"
 8) (integer) 0
 9) "clients.slaves"
10) (integer) 0
11) "clients.normal"
12) (integer) 584366
13) "aof.buffer"
14) (integer) 0
15) "db.0"
16) 1) "overhead.hashtable.main"
    2) (integer) 14784104
    3) "overhead.hashtable.expires"
    4) (integer) 10548160
17) "db.1"
18) 1) "overhead.hashtable.main"
    2) (integer) 367496
    3) "overhead.hashtable.expires"
    4) (integer) 32
19) "db.2"
20) 1) "overhead.hashtable.main"
    2) (integer) 1149828216
    3) "overhead.hashtable.expires"
    4) (integer) 797269936
21) "db.3"
22) 1) "overhead.hashtable.main"
    2) (integer) 1496
    3) "overhead.hashtable.expires"
    4) (integer) 32
23) "overhead.total"
24) (integer) 1974170366
25) "keys.count"
26) (integer) 22307144
27) "keys.bytes-per-key"
28) (integer) 1413
29) "dataset.bytes"
30) (integer) 29561345730
31) "dataset.percentage"
32) "93.742195129394531"
33) "peak.percentage"
34) "99.999443054199219"
35) "fragmentation"
36) "1.026200532913208"
127.0.0.1:6379>
`

**Comment by reasonerjt** [comment]
@cudneys 
Thanks a lot for the response, it's extremely helpful.

It seems that the root cause is db2 in redis:
`db2:keys=22033372,expires=22033323,avg_ttl=13485830904`
There are more than 20M records.  If each record is 0.5KB it will take 10GB.

The db2 in redis is for job execution records, in your case, you trigger "scan all" every 2 hours, each time you trigger "scan all", we'll launch a job for each of your images.  
Could you let us know approximately how many images are there in your Harbor instance?  Is it really necessary to run "scan all" every 2 hours?


@steven-zou 

I think we should handle the execution records more properly so some of them can be cleaned up more quickly.
And for this case, shall we provide some re-usable commands to help user to clean up the unimportant data?  (such as execution of successful scan/replication job)

**Comment by steven-zou** [comment]
For the improvement,

- reduce the job stats data expire time from 180 days to 7days
- discard all the dead (no more retries anymore) jobs
- all the stats data of successful jobs can be discarded immediately


For workaround,

  You may need to connect to the Redis server and execute `{harbor_job_service_namespace}:job_stats` to clear all the job stats when `no running jobs`. This may cause failures of retrying some errored jobs.

**Comment by steven-zou** [comment]
Fix solution is delivered to both main and patch branches, so I'll close this issue. If you have any other issues, you can reopen this issue or open a new one.

@cudneys
