### ISSUE TITLE
DAO test cased should be independent and handle the errors correctly

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#854]
1. Cases should be independent.
2. Handle error correctly.
   t.Fatal should be called to stop the case  to continue if the error is not nil, or nil pointer error will occur when call accessLogs[0].RepoName

```
accessLogs, err := GetAccessLogs(queryAccessLog, 1000, 0)
    if err != nil {
        t.Errorf("Error occurred in GetAccessLog: %v", err)
    }
    if len(accessLogs) != 1 {
        t.Errorf("The length of accesslog list should be 1, actual: %d", len(accessLogs))
    }
    if accessLogs[0].RepoName != projectName+"/" {
        t.Errorf("The project name does not match, expected: %s, actual: %s", projectName+"/", accessLogs[0].RepoName)
    }
```

**Comment by reasonerjt** [comment]
The new UT in `dao` pkg is taking care of clearing historical data and it's been pretty stable now.

We do have some discussion to re-write the database access layer at some point, but it'll be tracked in different issue.

I'm closing this one.
