### ISSUE TITLE
Removal of leading white space prior to reaching out to registry

### ISSUE THREAD

**Issue by IAmATeaPot418** [goharbor/harbor#8547]
If a user copy-pastes an image tag or image when pulling using a replication rule and leading white space is part of one of those names than a 404 error is thrown. While this is an obvious and expected response, it would be useful to help prevent user error by removing the leading white space.

Documenting in case someone else has this but I think I'll be able to submit a pull request for this.

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

When a leading space is set with a registry replication rule for the namespace or image tag of an image then the replication rule will fail with a 404 error. The expectation would be to remove this white space and still reach out to the correct image location. Instead this fails.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

Create a replication rule and add a space in front of the tag or name in the source resource filter when trying to pull from a registry. This will result in a 404 error.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.8.2-rc1

**Comment by AllForNothing** [comment]
@IAmATeaPot418 Will fix it in v1.9.0 , thanks for your comment.
