### ISSUE TITLE
online GC schedule not working

### ISSUE THREAD

**Issue by YakirShriker** [goharbor/harbor#8550]
Harbor version: 1.8.0-1
When creating daily GC schedule it suddenly stopped working.
Example:
Created Daily GC schedule and the last time it was running was at Jul 29.
What can cause it to stop running?
![image](https://user-images.githubusercontent.com/38837459/62421792-328b4c80-b6b0-11e9-87ae-9425ef6bb648.png)

**Comment by balonik** [comment]
I have issues with Daily GC with version 1.8.0 and 1.8.1 as well.
Daily GC stopped working after upgrade from 1.7.5 to 1.8.0. So I tried to set it again via API and GUI as well (remove schedule / set schedule).
Now it is pending forever. No related errors in `core.log` or `jobservice.log`. In `jobservice.log` I can see that daily job for 'Scan All' option is running fine.
```
{
  "schedule": {
    "type": "Daily",
    "cron": "0 0 0 * * *"
  },
  "id": 6,
  "job_name": "IMAGE_GC",
  "job_kind": "Periodic",
  "job_status": "pending",
  "deleted": false,
  "creation_time": "2019-07-31T07:39:39Z",
  "update_time": "2019-07-31T07:39:39.10525Z"
}
```

**Comment by YakirShriker** [comment]
Anyone got an idea of what we can do?
Right now I'm manually triggering the GC and I'm looking for a solution

**Comment by wy65701436** [comment]
@YakirShriker harbor will update the GC job with the same id, can you check the finish time of your daily job? If the time is keeping update, the schedule works.

Is it a fresh install or upgrade from the previous version? Please provide us the core and jobservice log.

**Comment by YakirShriker** [comment]
Hi,
I know harbor updating the same ID, but this case is different.
It's like the GC running once and never again.
I'm running 1.8.0 which was upgraded from 1.6.0
Here is an example:
Weekly GC that triggered once on 14/7, now on pending mode but never ran since then.
![image](https://user-images.githubusercontent.com/38837459/63250888-54223180-c275-11e9-870f-e57d967fd18b.png)


Uploading logs:
https://drive.google.com/open?id=1OQDEdHKZMVsRKXJfl2Bi57q7VeCr4yu8 (jobservice.log)
https://drive.google.com/open?id=1H6ngqNdC70k0aBiBo-Qf7A-yzOd7jahX (core.log)

**Comment by wy65701436** [comment]
thanks @YakirShriker  we will have a triage.

**Comment by reasonerjt** [comment]
@steven-zou is it fixed in master? or 1.8.x?

**Comment by steven-zou** [comment]
> @steven-zou is it fixed in master? or 1.8.x?

I can not identify the root cause of this issue based on the current info. So I'm still NOT sure if it has been fixed already.

**Comment by steven-zou** [comment]
@YakirShriker 

Is it possible for you to connect to the Redis DB and check the keys `{harbor_job_service_namespace}:period:policies` & `{harbor_job_service_namespace}:scheduled` have any values?

**Comment by YakirShriker** [comment]
@steven-zou 
sh-4.4# redis-cli get {harbor_job_service_namespace}:period:policies
(nil)
sh-4.4# redis-cli get {harbor_job_service_namespace}:scheduled
(nil)
