### ISSUE TITLE
Excessive refresh requests in History tab of GC UI

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8564]
![image](https://user-images.githubusercontent.com/2390463/62479427-0b339d00-b7e0-11e9-991f-35c54ab72e67.png)

In this page above, I found the UI is refreshing every second.

This is not necessary, I don't see why we need different refresh strategy than repository page.
Let's review why such decision is made, and fix it to make things consistent with other parts of the UI.

**Comment by jwangyangls** [comment]
fix it in #8623
