### ISSUE TITLE
Move the redundancy CVE whitelist log to debug

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8572]
The core.log repeats to log the following infor, please move them into debug level.

Aug  5 20:13:04 192.168.144.1 core[1619]: 2019-08-06T03:13:04Z [INFO] [/common/dao/cve_whitelist.go:61]: No CVE whitelist found for project 1, returning empty list.

**Comment by reasonerjt** [comment]
In #8713 it's been lowered to debug level.
