### ISSUE TITLE
CNCF TOC issue - Add proposal to archive Notary project

### ISSUE THREAD

**Issue by markpeek** [goharbor/harbor#8583]
Cross-posting this CNCF TOC issue for tracking as Notary is used in Harbor:

[Add proposal to archive Notary project](https://github.com/cncf/toc/issues/272)

**Comment by reasonerjt** [comment]
@markpeek Thanks for the heads up.

**Comment by lizrice** [comment]
The fact that Harbor uses Notary is just one argument for not archiving it

**Comment by michmike** [comment]
@lizrice agreed. We have actually gotten into a snag with notary and replicating Harbor projects that include signed images and our Harbor team will get more involved with notary to brainstorm solutions. we may end up starting to contribute to notary as well
