### ISSUE TITLE
Both in nightly UAA and LDAP pipelines, there was one user failed to login harbor

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8600]
![image](https://user-images.githubusercontent.com/44018302/62672153-12b79980-b9cc-11e9-9b5e-183ce48a9f01.png)

![image](https://user-images.githubusercontent.com/44018302/62673225-2d8c0d00-b9d0-11e9-8764-d4cf0f243217.png)

![image](https://user-images.githubusercontent.com/44018302/62672144-07646e00-b9cc-11e9-8e97-943c644c844e.png)

![image](https://user-images.githubusercontent.com/44018302/62672131-fca9d900-b9cb-11e9-992e-01b9ca92b1eb.png)

**Comment by danfengliu** [comment]
LDAP Pipeline Core.log:
![image](https://user-images.githubusercontent.com/44018302/62683026-1d842580-b9f0-11e9-99d7-7b0b3b352099.png)

**Comment by stonezdj** [comment]
This error message doesn't relate to the login failed issue, I can login with the same error log.

**Comment by reasonerjt** [comment]
Closing as the pipeline are now all green.
