### ISSUE TITLE
Excuse me, how to use the robot account

### ISSUE THREAD

**Issue by pog2g** [goharbor/harbor#8601]
What can we help you?
Excuse me, how to use the robot account

**Comment by stonezdj** [comment]
https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#robot-account

**Comment by pog2g** [comment]
thank you

在 2019年8月8日，15:41，stonezdj(Daojun Zhang) <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #8601<https://github.com/goharbor/harbor/issues/8601>.
