### ISSUE TITLE
The core can not connect to postgresql in Ubuntu18.04

### ISSUE THREAD

**Issue by rmrfself** [goharbor/harbor#8611]
**log output:**
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/main.go:92]: initializing configurations...
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/config/config.go:98]: key path: /etc/core/key
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/config/config.go:71]: init secret store
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/config/config.go:74]: init project manager based on deploy mode
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/core/main.go:96]: configurations initialization completed
Aug  8 17:44:51 172.19.0.1 core[12079]: 2019-08-08T09:44:51Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Aug  8 17:44:52 172.19.0.1 core[12079]: 2019-08-08T09:44:52Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.19.0.5:5432: i/o timeout
Aug  8 17:44:56 172.19.0.1 core[12079]: 2019-08-08T09:44:56Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.19.0.5:5432: i/o timeout
Aug  8 17:45:02 172.19.0.1 core[12079]: 2019-08-08T09:45:02Z [ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.19.0.5:5432: i/o timeout

**Comment by reasonerjt** [comment]
Please provide more details,

What version are you using and how do you install (offline installer? helm chart?)
