### ISSUE TITLE
Question updating Harbor.

### ISSUE THREAD

**Issue by jarduini** [goharbor/harbor#8615]
What can we help you?
I would like to know the best way to update Harbor 1.5.x to Harbor 1.8.x.
Thanks in Advance.
Javier

**Comment by stonezdj** [comment]
You can refer the upgrade guide for 1.6.0 
https://github.com/goharbor/harbor/blob/release-1.6.0/docs/migration_guide.md
to migrate the 1.5.x to 1.6.0
Then refer the latest upgrade guide to 1.8.x
https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md

**Comment by jarduini** [comment]
Thank you for you answer @stonezdj
