### ISSUE TITLE
refresh Logs failed

### ISSUE THREAD

**Issue by YangQing1989** [goharbor/harbor#8619]
OS: Centos 7.6
Harbor: V1.8.1
Browser: Firefox 68.0.1 (64 Bit)

**Click the refresh log button on the home page, no response**
![screenshot-taobishi club-2019 08 09-15_06_01](https://user-images.githubusercontent.com/26144773/62760753-4b806d00-bab7-11e9-836a-3ec4cce2df36.png)

**Comment by jwangyangls** [comment]
Ok  I will fix it in harbor 1.9.0
