### ISSUE TITLE
docker-compose version is not checked correctly in checkenv.sh

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8622]
docker-compose version should above 1.18, while 1.17 is still can bypass the check.
Should fix in checkenv.sh

**Comment by reasonerjt** [comment]
@bitsf I did not have a chance to try but the `docker-compose` template version is `2.3` so 1.17 should work.

Are you seeing any error using docker-compose 1.17?

**Comment by reasonerjt** [comment]
Sorry I was thinking `install.sh`

I'll make update the ensure `install.sh` and `checkenv.sh` share the code the checking the dependencies.
