### ISSUE TITLE
container harbor-db is still being created when using an external database

### ISSUE THREAD

**Issue by hvancamp** [goharbor/harbor#8625]
I installed Harbor v1.8.1 with the external_database option in harbor.yml for Harbor and Clair.
I was surprised to see that the generated docker-compose.yml still contained a service called postgresql and so I had a container harbor-db up and running on my Harbor server. 

After stopping this harbor-db container manually, Harbor still seems to work fine so I believe this container should be removed form the docker-compose file when using an external database?

**Comment by reasonerjt** [comment]
@ninjadq 
Can we fix it in 1.9?

**Comment by reasonerjt** [comment]
Closing as #8837 has been merged.
