### ISSUE TITLE
Image lock

### ISSUE THREAD

**Issue by iainsproat** [goharbor/harbor#8626]
**Is your feature request related to a problem? Please describe.**
Image tags are mutable and can be moved to point to different image digests.  Both repositories and image tags can also be deleted.  This may not be appropriate for a subset of images where greater guarantees or immutability are required.

Even when permissions to update and delete repositories or tags are restricted to certain users, these actions can be accidentally done.  Current permissions may not be sufficient to ensure an elevated level of expected immutability.

**Describe the solution you'd like**
Introducing additional friction can reduce the probability of a repository or an image tag being updated or deleted.
One mechanism for introducing additional friction is to have a "locking" feature.  This locking feature can be applied to specified tags in repositories. Permissions for locking & unlocking can be assigned to certain users.
The Azure container registry product provides this feature: https://docs.microsoft.com/en-gb/azure/container-registry/container-registry-image-lock

**Additional context**
This was an issue discussed with @michmike in a call with @Deskana

This is similar to a previous issue #4210

**Comment by xaleeks** [comment]
This is covered in https://github.com/goharbor/harbor/issues/3413
