### ISSUE TITLE
Show untagged images in UI

### ISSUE THREAD

**Issue by iainsproat** [goharbor/harbor#8627]
**Is your feature request related to a problem? Please describe.**
When an image is updated (and an existing tag moved to that new image) it is no longer possible to see the image which previously had that tag.  However that previous image continues to exist and can be pulled by referencing its digest. Visibility in the UI is key to an admin or user knowing what images exist, and to enable the deletion or restriction of untagged images as necessary (assuming automated cleanup of untagged images is not enabled)

**Describe the solution you'd like**
All images, whether tagged or untagged, should be shown in the UI for a repository.
The image should be displayed with its digest until it is deleted.

**Additional context**
This was an issue discussed with @michmike in a call with @Deskana

**Comment by reasonerjt** [comment]
The tag list is retrieved by calling API of registry, and the blobs of untagged images will be GCed.

Given such approach there's probably no quick fix

**Comment by xaleeks** [comment]
Will investigate, moving to 1.11 feature hopper

**Comment by xaleeks** [comment]
I agree with this, these need to be retrievable and viewable somehow, and maybe should be shown to user before GC is run, maybe add this to capability of the dry run for running online gc.  @wy65701436 

@lweitzman  please think about design here

**Comment by xaleeks** [comment]
part of the https://github.com/goharbor/harbor/issues/10167

**Comment by michmike** [comment]
@xaleeks  Harbor 2.0 will solve this right? since now we show all images with or without tags as long as the image was not deleted yet

**Comment by xaleeks** [comment]
This will be solved in 2.0.  There will be a toggle to display / hide all untagged images.  @michmike @iainsproat

**Comment by jwangyangls** [comment]
fix in #11007
