### ISSUE TITLE
Pulls against library don't work as expected

### ISSUE THREAD

**Issue by rbkaspr** [goharbor/harbor#8629]
**Issue**
Pulling images from Harbor without specifying a project returns a 500 error. Pushing to library displays similar behavior if the library project is not specified.

**Expected Behavior**
When pulling from Docker Hub, running the commands  
``docker image pull alpine``  and
``docker image pull library/alpine``  both result in the correct image being pulled.  

**Observed Behavior**
In Harbor, the ```library``` path must be specified, or else an error is returned
```docker image pull harbor.example.com/alpine```  returns
```Error response from daemon: Get https://harbor.example.com/v2/alpine/manifests/latest: received unexpected HTTP status: 500 Internal Server Error```

**Steps to reproduce the problem:**
Add an image to the library project in Harbor  
```docker image push harbor.example.com/library/alpine```
Attempt to pull that image using the Harbor FQDN and image name without specifying the library project
```docker image pull harbor.example.com/alpine```

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.7.0
- docker engine version: 18.09.6
- docker-compose version: 1.18.0

**Comment by rbkaspr** [comment]
Replicated the same behavior in Harbor 1.8.0

**Comment by reasonerjt** [comment]
The `library` is added by docker client and only works for pulliing image from dockerhub.

Closing as won't fix
