### ISSUE TITLE
v1.8.2-rc1版本中项目名为数字，该项目的成员无法获得项目中镜像信息，只有harbor管理员可以看到镜像

### ISSUE THREAD

**Issue by ali94s** [goharbor/harbor#8635]
问题复现：
1.以harbor管理员的帐号登录，创建一个测试项目，项目名为123（整型数即可）。
2.以harbor管理员的帐号推送一个测试镜像，并且添加一个成员给这个项目，角色为项目管理员。
3.切换为添加的这个帐号，查看项目下的镜像，发现无法查看。
代码版本：* （头指针分离于 v1.8.2-rc1） ddc119a15 Merge pull request #8342 from wy65701436/release-1.8.0
通过日志和源码发现：
common/security/local/context.go:109 报错，没有找到project，通过查看Get函数，core/promgr/pmsdriver/local/local.go:41，定位utils.ParseProjectIDOrName(projectIDOrName)函数，common/utils/utils.go:154,这部分代码对非harbor管理员时查找project的逻辑是否有问题？如果传入的参数是一个name为整型的参数是否会导致我目前遇到的问题？
请各位给出宝贵的意见，或者我的代码定位是否有误，请指出，期待各位的帮助，谢谢

**Comment by reasonerjt** [comment]
Root cause is that the namespace used to create the Resource and the namespace parsed by Resource is not the same.

A quick fix is to make the `id` looks different such as `:123` when it's a string, so that the Resource won't think it's an ID when parsing it.

**Comment by ali94s** [comment]
> Root cause is that the namespace used to create the Resource and the namespace parsed by Resource is not the same.
> 
> And this was introduced in 1.8.0, not 1.8.2
> 
> A quick fix is to make the `name` looks different such as `:123` when it's a number, so that the Resource won't think it's an `id` when parsing it.

谢谢你的说明，这让我了解到了这个问题产生的真正原因，修改项目名称，使整型数和数字在字面值可以区分可以解决我的问题，但是我并不打算这样做，因为我们的业务依赖与项目名，我们的线上自动发布使用的账号使harbor管理员，因此不会影响我们的业务。我希望这个问题可以在数据结构设计的时候就得以规避，将整型和字符串在传入的时候便能识别应该是好的办法。

**Comment by reasonerjt** [comment]
> > Root cause is that the namespace used to create the Resource and the namespace parsed by Resource is not the same.
> > 
> > And this was introduced in 1.8.0, not 1.8.2
> > 
> > A quick fix is to make the `name` looks different such as `:123` when it's a number, so that the Resource won't think it's an `id` when parsing it.
> 
> 谢谢你的说明，这让我了解到了这个问题产生的真正原因，修改项目名称，使整型数和数字在字面值可以区分可以解决我的问题，但是我并不打算这样做，因为我们的业务依赖与项目名，我们的线上自动发布使用的账号使harbor管理员，因此不会影响我们的业务。我希望这个问题可以在数据结构设计的时候就得以规避，将project_id和project_name在传入的时候便能识别应该是好的办法。

我的意思是说在代码里让他们区分

**Comment by ali94s** [comment]
你好，下个发布版本会包含本次更改吗？
我们的使用场景中现在有这方面造成的不方便。
谢谢。

**Comment by ywk253100** [comment]
The fixed will be available in release 1.9

**Comment by reasonerjt** [comment]
Reopen to make sure the fix is cherry picked to 1.8.3
