### ISSUE TITLE
AWS S3 Iam role

### ISSUE THREAD

**Issue by Jean-PhilippeGouin** [goharbor/harbor#8641]
Hi,

Is it possible to use iam role for s3 configuration access instead of access key and secret key ?

Thanks,
Jean-Philippe

**Comment by steven-zou** [comment]
@Jean-PhilippeGouin 

So far, I don't think so. I'll treat this issue as a requirement and check if we can support it in the next release.

**Comment by Jean-PhilippeGouin** [comment]
Ok great !

**Comment by KISStian** [comment]
We are running Harbor in K8s and I just wanted to point out that we were able to accomplish this by using the [kiam](https://github.com/uswitch/kiam) project.  By setting up a role in AWS and then adding the role to pod annotations, we were able to assume roles other than the underlying EC2 instance profile.

**Comment by reasonerjt** [comment]
@KISStian thanks for chiming in. 
I'm a rookie in AWS but based on my understanding under the hood kiam transform the IAM role to AK/SK?
@Jean-PhilippeGouin Please clarify in which use case you are expecting to use IAM role to replace AK/SK.

**Comment by Jean-PhilippeGouin** [comment]
In fact it's working , since harbor is using the docker registry and it's supported.
By not setting the access key and secret key the fallback for the aws driver is to use the iam role of the EC2 where is running the Pod.
Chartmuseum has the same behavior.

The solution of @KISStian allows to use a role that is declared inside AWS but not bind to the EC2 instance.

**Comment by dntosas** [comment]
@KISStian we also added the role via kiam pod annotation but we still got this error:

`NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors`

what values did you provide on aws config for credentials? null?
