### ISSUE TITLE
Provide an unified mechanism for the management of all tasks(replication/scan/GC/retention)

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8644]
Currently, the different features(replication, scan, GC, webhook and retention) have their own modules to manage the tasks. We should provide an unified mechanism for all of them to avoid duplicated works. And the mechanism should be able to handle the task status updating hook in concurrency, about the detail please refer to #8202 and #8606. 

Besides, the statuses of replication tasks and Jobservice jobs aren't consistent, we should refactor the replication part either.

**Comment by reasonerjt** [comment]
Let's triage and see if this can be contained in 1.10

**Comment by ywk253100** [comment]
We can introduce a TaskManager to handle all the operations related with Jobservice jobs, including submitting, stopping, especially the status updating.

For the status updating, it should be able to handle the sequence of statuses and job retrying(currently we use status code and status revision to resolve the issue:  https://github.com/goharbor/harbor/pull/8794)

**Comment by ywk253100** [comment]
The data migration could be the difficult part for this work

**Comment by ywk253100** [comment]
Done by https://github.com/goharbor/harbor/pull/12280
