### ISSUE TITLE
dockerhub replication always failed

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8658]
Recently dockerhub Replication adapter can't be used, always report "UNAUTHORIZED"

![image](https://user-images.githubusercontent.com/188115/63001208-acd48180-bea5-11e9-9874-4f17e5860553.png)

branch:master
commit:81f4b64b45837a9bddc7aa7d6c5ce9c5ed55d820

**Comment by ywk253100** [comment]
Fixed
