### ISSUE TITLE
support multiple queue for replication

### ISSUE THREAD

**Issue by IrisHan** [goharbor/harbor#8665]
What can we help you?
An image is copied to multiple harbors, but each harbor has different network bandwidth. Since all tasks are stored in one queue, Low bandwidth harbor will affect the synchronization of other harbors.
I hope community distinguish the channels of various synchronization strategies. replication strategies have priority settings。
I hope commnuty support "user could chose  image to replicate"

**Comment by xaleeks** [comment]
A 'bandwidth limit' configurable by time window could be useful,  feel free to list the specific use cases you have in mind @IrisHan

**Comment by xaleeks** [comment]
I don't foresee something like this in the near future.
