### ISSUE TITLE
[harbor-core][kibana]  Parsing logs with color give grokparsefailure tag error on Kibana

### ISSUE THREAD

**Issue by JordanGoasdoue** [goharbor/harbor#8667]
**Is your feature request related to a problem? Please describe.**
On Kibana, when we want to parse harbor-core logs, we always have the tags `_grokparsefailure` because it doesn't interprete correctly the following message with bash colors inside : `2019/08/14 14:46:58 [1;44m[D] [server.go:2774] | x.x.x.x|[42m] 200 [0m] | 2.019981ms| match|[44m] GET [0m] /api/ping r:/api/ping[0m]`

**Describe the solution you'd like**
Is it possible to disable the colors from logs when we don't look at them interactively, to let them be parsed by Kibana without having error tags ?

Thank you

**Comment by reasonerjt** [comment]
@ninjadq please check if there's a way to disable that in beego.

**Comment by ninjadq** [comment]
will fix some of this issue in  #9530
