### ISSUE TITLE
UI should disable non-project admin updating the project CVE whitelist

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8668]
Build: v1.9.0-bf58c6ad

I added a user to project as Guest 
He can edit the CVE whitelist widgets while other check boxes under "configuration" tab of this project are disabled.

Another issue, when this user clicks "save" button, the backend API returns 403 error, but UI does not show anything, we need to make sure the error is displayed on UI when backend returns error.

**Comment by jwangyangls** [comment]
I tried to click the save button.but I can see the error message!
![image](https://user-images.githubusercontent.com/29826789/63074007-ea94e100-bf5d-11e9-870a-32dac2739bd4.png)

**Comment by jwangyangls** [comment]
Yes, I alse found the information on this page cannot be modified by Guest;
and 
@AllForNothing  you can modify it according to the'update'field of'configration' in the permission list;

**Comment by AllForNothing** [comment]
will fix it

**Comment by AllForNothing** [comment]
fix in #8716
