### ISSUE TITLE
Replication doesn't work for previous version to v1.9.0

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8673]
As quota management is introduced from v1.9.0, and the replication request(PUT blob) used in the previous Harbor doesn't meet the OCI spec of the registry, which is only accepted by quota middlewares now. 

Thus, it will break the replication task from an older version Harbor to v1.9.0 Harbor, and you may see the error in the log like:

`2019-08-15T02:22:31Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 500, message {"errors":[{"code":"InternalError","message":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 01cf72d0-2fbf-4722-a0f5-fc91ad48d317, error: redigo: nil returned","detail":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 01cf72d0-2fbf-4722-a0f5-fc91ad48d317, error: redigo: nil returned"}]}`

[Resolve]
Upgrade all of the harbor nodes to v1.9.0.

**Comment by huyifanstar** [comment]
All docker engines must be upgraded to 19.03 to use 1.9（Harbor）?

**Comment by wy65701436** [comment]
@huyifanstar 18+ is OK.

**Comment by huyifanstar** [comment]
Is there any other way to migrate from 1.5 to 1.9(docker image)?
Do not use copy/rsync

**Comment by wy65701436** [comment]
he exactly path should be: `1.5 -> 1.6 -> 1.8 -> 1.9`.

In case of any error, please upgrade version by version and use the migration guide of `release-1.*`

**Comment by huyifanstar** [comment]
If I want to migrate the images(docker images) in the 1.5 repository to the 1.9 repository，How should I do
Thanks You！

**Comment by xaleeks** [comment]
you are talking about migrating an image sitting on harbor 1.5 instance  to another harbor 1.9 instance correct? @huyifanstar

**Comment by wy65701436** [comment]
@huyifanstar this is no way to migrate images from 1.5 to 1.9. 

Two options to workaround this:


- Upgrade the source node to 1.9, and the replication images between the 1.9 nodes.
- Call Harbor v1.9.0 API to create projects(and maybe users as well), and do docker pull form v1.5, then do push to Harbor v1.9.0. This could only "migrate" images, and other data will be lost.

**Comment by xaleeks** [comment]
as @wy65701436 stated, replication btw different versions of harbor is not supported as of right now

**Comment by huyifanstar** [comment]
> 如@ wy65701436所述，目前不支持不同版本的Harbor复制

Then I can only use：

 docker save   < image
 docker load  <  images
Backup /  recovery ？

**Comment by xaleeks** [comment]
if you are looking to do this for series of isolated images, maybe the quickest way is to just pull them down and then push them to your new instance.  This isn't a target scenario of the backup script we have right now although a more complete solution is coming soon.

**Comment by huyifanstar** [comment]
> if you are looking to do this for series of isolated images, maybe the quickest way is to just pull them down and then push them to your new instance. This isn't a target scenario of the backup script we have right now although a more complete solution is coming soon.

If not the best, is there any better?

**Comment by huyifanstar** [comment]
Is there a bulk export script?
Harbor has a lot of projects, I want to export all.
shell / python ？

**Comment by MaGaoju** [comment]
I have the same issue from 1.8.2 (v1.8.2-b24a0e33)--> 1.9.0(Version v1.9.0-d13cf448) ....  

below is the error message 

2019-10-12T07:42:47Z [ERROR] [/replication/transfer/image/transfer.go:249]: failed to pushing the blob sha256:dd59fdb172771f3dc2e4b0d7e3052dce2dea7fce3c35ebf423d6b6d8804e0bba: http error: code 500, message {"errors":[{"code":"InternalError","message":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 5cce90da-005f-48e6-a88c-eee66fea0fe1, error: redigo: nil returned","detail":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 5cce90da-005f-48e6-a88c-eee66fea0fe1, error: redigo: nil returned"}]}
2019-10-12T07:42:47Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 500, message {"errors":[{"code":"InternalError","message":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 5cce90da-005f-48e6-a88c-eee66fea0fe1, error: redigo: nil returned","detail":"Error occurred when to handle request in size quota handler: failed to get content length of blob upload 5cce90da-005f-48e6-a88c-eee66fea0fe1, error: redigo: nil returned"}]}

any solution ?

**Comment by lf1029698952** [comment]
you can for each pull every one images and push it to new harbor.
