### ISSUE TITLE
[tag retention] get rule conflict error, but the id is not correct

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8679]
1, add a rule A.
2, add a rule B.
3, repeat step 2.

Got the error message "rule2 is conflict rule 0", but actually, the rule2 is conflict rule 0.

{id: 2, algorithm: "or", rules: [{disabled: false, action: "retain", params: {latestPushedK: 3},…},…],…}
algorithm: "or"
cap: 0
id: 2
rules: [{disabled: false, action: "retain", params: {latestPushedK: 3},…},…]
0: {disabled: false, action: "retain", params: {latestPushedK: 3},…}
action: "retain"
disabled: false
params: {latestPushedK: 3}
scope_selectors: {repository: [{kind: "doublestar", decoration: "repoMatches", pattern: "**"}]}
tag_selectors: [{kind: "doublestar", decoration: "matches", pattern: "latest"},…]
template: "latestPushedK"
1: {disabled: false, action: "retain", params: {},…}
action: "retain"
disabled: false
params: {}
scope_selectors: {repository: [{kind: "doublestar", decoration: "repoMatches", pattern: "**"}]}
tag_selectors: [{kind: "doublestar", decoration: "matches", pattern: "**"},…]
template: "nothing"
2: {disabled: false, action: "retain", params: {},…}
action: "retain"
disabled: false
params: {}
scope_selectors: {repository: [{kind: "doublestar", decoration: "repoMatches", pattern: "**"}]}
tag_selectors: [{kind: "doublestar", decoration: "matches", pattern: "**"},…]
template: "nothing"
scope: {level: "project", ref: 1}
trigger: {kind: "Schedule", settings: {cron: "0 0 * * * *"}, references: {job_id: 6}}

**Comment by bitsf** [comment]
fixed by https://github.com/goharbor/harbor/pull/8708
