### ISSUE TITLE
The error message is confusing when updating the default quota

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8680]
I tried to set the count quota to "0" 

The error message is "The upper limit of Count Quota should be integers".

1) It should not be plural
2) If we don't allow it being "0" the error message should be clear.

![image](https://user-images.githubusercontent.com/2390463/63076813-05208780-bf69-11e9-8efd-51108069746c.png)

**Comment by jwangyangls** [comment]
fix it  in #8720
