### ISSUE TITLE
Failed to delete image from repo when count exceed quota

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8681]
1.Create a project and push 5 images to the project
2.Set the count quota to 2
3.Delete image in the project 

<img width="712" alt="Screen Shot 2019-08-15 at 2 29 17 PM" src="https://user-images.githubusercontent.com/2696760/63076972-6ba5a580-bf69-11e9-8579-615af61d1ba8.png">

**Comment by stonezdj** [comment]
There is a typo in the error message.   hard -> has?

**Comment by wy65701436** [comment]
thanks @stonezdj , @heww will update the login on substracting usage.
