### ISSUE TITLE
[tag retention] my images are all removed with a wrong label input

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8682]
I have several images without label, but I just create a rule with label with "a", all of them are removed. 

**_It's dangerous_** if I input a wrong label name.  

![image](https://user-images.githubusercontent.com/2841473/63077146-e8388400-bf69-11e9-814f-28db01ee83c4.png)

**Comment by bitsf** [comment]
Yes, but this is by design now.
You could dry run first, and you should know what you input.

**Comment by reasonerjt** [comment]
Per discussion, this is working as design, we expect admin to setup the policy very carefully.
There is an explicit warning when user saving the policy.
