### ISSUE TITLE
The "Test Endpoint" button isn't consistent with others(e.g. replication)

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8684]
Test endpoint successfully, the “✔️” isn't consistent with other test connections:
![image](https://user-images.githubusercontent.com/5835782/63077185-04d4bc00-bf6a-11e9-93aa-ac9984702b50.png)

If failed, the error message is under the dialog:
![image](https://user-images.githubusercontent.com/5835782/63077218-1e760380-bf6a-11e9-98a3-56b5c39e8a97.png)

**Comment by mmpei** [comment]
fixed.
