### ISSUE TITLE
harbor-ui username in harbor log

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8686]
1. Push a image to project library
2. Create a project sample
3. Retag the pushed image to sample.
4. Check the log in harbor web console. found harbor-ui in the username. 

<img width="1003" alt="Screen Shot 2019-08-15 at 2 44 20 PM" src="https://user-images.githubusercontent.com/2696760/63077638-955fcc00-bf6b-11e9-986c-cc99e8a9d310.png">

**Comment by reasonerjt** [comment]
This `harbor-ui` is a `service-account`, but is there a more systematic way the inject the actual user into such server action?

**Comment by ywk253100** [comment]
The `retag` has been removed in v2.0, closing the issue
