### ISSUE TITLE
There is a datagrid flash by when setting the webhook first time

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8687]
![image](https://user-images.githubusercontent.com/5835782/63077394-bffd5500-bf6a-11e9-905c-033fa2917c78.png)

![image](https://user-images.githubusercontent.com/5835782/63077423-db686000-bf6a-11e9-9eb0-7620a531cefd.png)

**Comment by AllForNothing** [comment]
fixed in #8730
