### ISSUE TITLE
The webhook doesn't re-send when the first-send failed

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8691]
I mocked a HTTP server and returned HTTP status code 500 to the hook request, but I didn't see any retry for the hook

**Comment by lightof410** [comment]
When webhook first-send failed, webhook job return an err,  following is the log:
`Aug 16 21:09:17 172.19.0.1 jobservice[4168]: 2019-08-16T13:09:17Z [ERROR] [/jobservice/runner/redis.go:63]: |@_@| Job 'WEBHOOK:9bb0d5c85697d74bbdd8df25' exit with error: webhook job(target: http://59.111.92.135:48081/ccr/test/webhook/500) response code is 500`
And then retry job comes after a while, log is
`Aug 16 21:10:32 172.19.0.1 jobservice[4168]: 2019-08-16T13:10:32Z [INFO] [/jobservice/worker/cworker/c_worker.go:73]: Job incoming: {"name":"WEBHOOK","id":"9bb0d5c85697d74bbdd8df25","t":1565961029,"args":null,"fails":1,"err":"webhook job(target: http://59.111.92.135:48081/ccr/test/webhook/500) response code is 500","failed_at":1565960957}`
But this job seems to be discarded. 
 I set MaxFails is 10 and ShouldRetry is true, @steven-zou is there any problem here?

**Comment by steven-zou** [comment]
Refer to https://github.com/goharbor/harbor/issues/8745

**Comment by steven-zou** [comment]
Fixed, check #8745 .
