### ISSUE TITLE
The lock in quota doesn't support redis HA mode 

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8692]

**Comment by reasonerjt** [comment]
@wy65701436 Please elaborate the root cause and the impact of this problem, this may have to be put as a release note.

**Comment by wy65701436** [comment]
As the redis locker(https://github.com/goharbor/harbor/blob/master/src/common/utils/redis/helper.go) that we're using for quota is for a single node, and it may not work for redis HA mode. The same thing may happen at job service.
