### ISSUE TITLE
Tag Retention modify cron Internet Error 500

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#8694]
![image](https://user-images.githubusercontent.com/29826789/63079376-c2fb4400-bf70-11e9-9d23-f96845723aef.png)
![image](https://user-images.githubusercontent.com/29826789/63079472-fb9b1d80-bf70-11e9-8dbf-a78a3dcb6275.png)

**Comment by ywk253100** [comment]
Cannot reproduce it, but we can do some enhancement to skip the error and continue the work flow if the schedule record not found

**Comment by ywk253100** [comment]
Done
