### ISSUE TITLE
The non-member users can see the member number and quota information in the project summary page

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8697]
![image](https://user-images.githubusercontent.com/5835782/63079993-76186d00-bf72-11e9-8e96-e24a4e0c50a7.png)

**Comment by reasonerjt** [comment]
@ywk253100 you should mention this is a public project.
I think we should fix this
@xaleeks @wy65701436 please triage.

**Comment by xaleeks** [comment]
Yes quota and member information should be hidden to non-members even for public project.  Adding this to to-do
