### ISSUE TITLE
CVE whitelist doesn't take effective when none of "System whitelist" or "Project whitelist" is selected

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8698]
Steps to reproduce:
docker pull redis:5
Retag and push this image to library and scan this image
Set the vulnerability to prevent pull image with "medium" level 
Pull image hostname/library/redis:5 in local, it will prevent to pull image
Add CVE whitelist to by click the "Add", and input all CVE ID with medium
But it is failed to pull image after all medium CVE ID in the CVE whitelist.
<img width="576" alt="Screen Shot 2019-08-15 at 3 38 06 PM" src="https://user-images.githubusercontent.com/2696760/63080104-c8f22480-bf72-11e9-8ede-707663ad9d6d.png">

**Comment by stonezdj** [comment]
rootcause: by default is system CVE white list, but there is no clue to indicate this after adding a project level CVE whitelist.

**Comment by reasonerjt** [comment]
@AllForNothing how about we select "Project whitelist" when user adds items to the list on UI?

**Comment by AllForNothing** [comment]
Will fix it.

**Comment by AllForNothing** [comment]
fixed in #8716
