### ISSUE TITLE
artifact count is not updated after deleting a chart

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8701]
1. Upload a chart a project via UI
2. On project summary page the count increased by 1
3. Delete the chart via UI
4. On project summary page the artifact size remain unchanged.

**Comment by wy65701436** [comment]
will revise the computerResource func.

**Comment by ywk253100** [comment]
Found the same issue for the chart acs-engine-autoscaler-1.0.0.tgz

**Comment by wy65701436** [comment]
close as fixed.
