### ISSUE TITLE
System level CVE whitelist disappear after create another new project

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8702]
1. Add a CVE whitelist to system level.
2. Create another project named sample3
3. Check the system CVE whitelist, found that system level CVE whitelist is empty.

**Comment by reasonerjt** [comment]
root cause is that when creating a project, the  code used the wrong variable, where the project ID is empty i.e. `0` to `InsterOrUpdate` the list, and this accident overwrites the list with an empty one.
