### ISSUE TITLE
Failed to load Amazon replication rule info, it's empty

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8705]
**Error Information:**

![image](https://user-images.githubusercontent.com/44018302/63087274-52f6b900-bf84-11e9-984e-f87e9b2bcacb.png)

![image](https://user-images.githubusercontent.com/44018302/63087370-994c1800-bf84-11e9-84ee-82b222a92bfd.png)

**Harbor Version:**
![image](https://user-images.githubusercontent.com/44018302/63087501-f1831a00-bf84-11e9-9cec-7759736a13f6.png)

**Comment by jwangyangls** [comment]
fix it #8720
