### ISSUE TITLE
Could i create a token for all repository via API.

### ISSUE THREAD

**Issue by anemptyair** [goharbor/harbor#8707]
I can create a token via :
curl -i -k -u admin:Harbor12345 https://10.192.212.107/service/token?service=harbor-registry\&scope=repository:library/mysql/5.6.35:pull,push

Could i create a token for all repository via API.
curl -i -k -u admin:Harbor12345 https://10.192.212.107/service/token?service=harbor-registry\&scope=repository:*:pull,push

**Comment by bitsf** [comment]
Can docker hub or docker registry do this?
