### ISSUE TITLE
Tag Retention: unwanted deletion behavior

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#8717]
There's an issue with the current retention policy implementation (due to native docker tag deletion behavior) where if you have multiple tags referring to the same sha digest and a subset of the tags are deleted due to a configured retention policy, all remaining tags will also get wiped out which in turn violates the retention policy
eg.
imagine following tags (listed by order of push time) all refer to the same digest

harbor-1.8,  		pushed 8/14/2019 12:00am
harbor-release, 	pushed 8/14/2019 03:00am
harbor-nightly, 	pushed 8/14/2019 06:00am
harbor-latest,		pushed 8/14/2019 09:00am

And there's retention policy configured to retain latest 2 tags matching 'harbor-*', so that 'harbor-rc' and 'harbor-latest' will be deleted, which triggers the deletion the other 2 tags 'harbor-1.8' and 'harbor-release' as well

This is due to the underlying issue highlighted here:
https://github.com/goharbor/harbor/issues/4868
https://github.com/goharbor/harbor/issues/6994

I don't characterize this as a bug (of tag retention feature) but it's definitely an unwanted side effect.  There's a soft solution in ignoring the deletion altogether in this case but that's also not what the user wanted.

**Comment by yusuf-gunaydin** [comment]
A solution might be overwriting the given tag with a dummy image and then deleting the digest of that dummy image. I have used this workaround in the past quite a few times.

Unfortunately Docker team does not want to solve this issue as its open for years.

**Comment by xaleeks** [comment]
We either need to implement a simple workaround like @yusuf-gunaydin  suggested or a full blown solution of deletable Harbor tags in the next release 1.11.  If we go with the workaround, need to think about where this dummy manifest sits as to minimize the overhead associated with each delete operation, all deletes can leverage this single lightweight dummy manifest.  @steven-zou @wy65701436 

In the meantime, I'm already working with @stuclem to address this in the docs for tag retention.

**Comment by MartinEmrich** [comment]
This one just bit me hard... I expected a behaviour similar to Linux/UNIX hard links. This breaks our current cleanup procedure for older images/tags.
And I could almost swear that the behaviour with harbor < 1.8 was different?

**Comment by xaleeks** [comment]
@MartinEmrich this will be fixed in upcoming release 1.11 since we will solve the underlying issue of being able to delete image tags

**Comment by xaleeks** [comment]
need to make some changes to tag retention once we add the new docker tag data structure, so should be matching via new docker tag, not image tag @steven-zou

**Comment by xaleeks** [comment]
will be fixed via https://github.com/goharbor/harbor/issues/2663
