### ISSUE TITLE
Return HTTP 500 Error when project count quota exceed

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8718]
Steps to reproduce:
1. Create a project sample and project count quota set 1
2. Push a image to sample project
3. Retag a existing image in library to sample project, quota exceeds, it return HTTP 500 error.
![Screen Shot 2019-08-16 at 2 59 31 PM](https://user-images.githubusercontent.com/2696760/63149467-da046980-c036-11e9-9b2e-c20155ea2ba1.png)

It is inappropriate to return 500 code in this case, should return 4xx instead. and should display the project quota exceed prompt so that user can take action.

**Comment by wy65701436** [comment]
close as dup with https://github.com/goharbor/harbor/issues/8688
