### ISSUE TITLE
Make DB connections limits configurable

### ISSUE THREAD

**Issue by thcdrt** [goharbor/harbor#8721]
Hello,

We currently reach our DB max connections limit.

We would like to configure the max number of opened and idled connection on the DB.

We found 2 functions that seems to do the job on the harbor orm: [SetMaxIdleConns](https://beego.me/docs/mvc/model/orm.md#setmaxidleconns) and [SetMaxOpenConns](https://beego.me/docs/mvc/model/orm.md#setmaxopenconns).

Is that possible to expose the 2 values in configuration ?

Thomas,
OVH

**Comment by heww** [comment]
Harbor 1.9 will support these configurations, see more #8616
