### ISSUE TITLE
harbor core report error: Failed to get digest for reference: latest, error: Head http://registry:5000/v2/middleware/mysql/manifests/latest: dial tcp 172.18.0.5:5000: getsockopt: connection refused

### ISSUE THREAD

**Issue by sunyao5588** [goharbor/harbor#8724]
What can we help you?
---------------------------------------------------------------------------------------------------------------------------------------
current status of all harbor containers
> docker-compose ps
harbor-adminserver   /harbor/start.sh                 Up (healthy)
harbor-core          /harbor/start.sh                 Up (healthy)
harbor-db            /entrypoint.sh postgres          Up (healthy)     5432/tcp
harbor-jobservice    /harbor/start.sh                 Up
harbor-log           /bin/sh -c /usr/local/bin/ ...   Up (healthy)     127.0.0.1:1514->10514/tcp
harbor-portal        nginx -g daemon off;             Up (healthy)     80/tcp
nginx                nginx -g daemon off;             Up (healthy)     0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp, 0.0.0.0:80->80/tcp
redis                docker-entrypoint.sh redis ...   Up               6379/tcp
registry             /entrypoint.sh /etc/regist ...   Up (unhealthy)   5000/tcp
registryctl          /harbor/start.sh                 Up (unhealthy)
---------------------------------------------------------------------------------------------------------------------------------------
what I expected?
after kernel update and server reboot , harbor is able to use. 
---------------------------------------------------------------------------------------------------------------------------------------
What about the issue?
Now harbor is not able to use, cause of no tags are shown and core logs reports: 
---------------------------------------------------------------------------------------------------------------------------------------
tail -f /var/log/harbor/core.log
Aug 17 14:11:26 172.18.0.1 core[1308]: 2019/08/17 06:11:26 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.446612ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:11:30 172.18.0.1 core[1308]: 2019/08/17 06:11:30 http: proxy error: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:11:30 172.18.0.1 core[1308]: 2019/08/17 06:11:30 #033[1;44m[D] [server.go:2619] |  10.150.130.30|#033[41m 502 #033[0m|   1.711708ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Aug 17 14:11:30 172.18.0.1 core[1308]: 2019-08-17T06:11:30Z [ERROR] [interceptors.go:137]: Failed to get digest for reference: latest, error: Head http://registry:5000/v2/middleware/mysql/manifests/latest: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:11:30 172.18.0.1 core[1308]: 2019/08/17 06:11:30 #033[1;44m[D] [server.go:2619] |  10.150.130.30|#033[41m 500 #033[0m|  21.934802ms|   match|#033[44m GET     #033[0m /v2/middleware/mysql/manifests/latest   r:/v2/*#033[0m
Aug 17 14:11:41 172.18.0.1 core[1308]: 2019/08/17 06:11:41 #033[1;44m[D] [server.go:2619] |  10.150.130.45|#033[41m 502 #033[0m|    4.20672ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Aug 17 14:11:41 172.18.0.1 core[1308]: 2019/08/17 06:11:41 http: proxy error: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:11:41 172.18.0.1 core[1308]: 2019-08-17T06:11:41Z [ERROR] [interceptors.go:137]: Failed to get digest for reference: latest, error: Head http://registry:5000/v2/middleware/mysql/manifests/latest: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:11:41 172.18.0.1 core[1308]: 2019/08/17 06:11:41 #033[1;44m[D] [server.go:2619] |  10.150.130.45|#033[41m 500 #033[0m|  20.959899ms|   match|#033[44m GET     #033[0m /v2/middleware/mysql/manifests/latest   r:/v2/*#033[0m
Aug 17 14:11:56 172.18.0.1 core[1308]: 2019/08/17 06:11:56 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.747409ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:12:26 172.18.0.1 core[1308]: 2019/08/17 06:12:26 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|    2.07911ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:12:57 172.18.0.1 core[1308]: 2019/08/17 06:12:57 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.836518ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:13:27 172.18.0.1 core[1308]: 2019/08/17 06:13:27 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.908209ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:13:57 172.18.0.1 core[1308]: 2019/08/17 06:13:57 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.905019ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:14:27 172.18.0.1 core[1308]: 2019/08/17 06:14:27 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.758708ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:14:57 172.18.0.1 core[1308]: 2019/08/17 06:14:57 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.914319ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:15:27 172.18.0.1 core[1308]: 2019/08/17 06:15:27 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   1.767101ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:15:57 172.18.0.1 core[1308]: 2019/08/17 06:15:57 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   4.209902ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:16:27 172.18.0.1 core[1308]: 2019/08/17 06:16:27 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|     1.7966ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Aug 17 14:16:38 172.18.0.1 core[1308]: 2019/08/17 06:16:38 http: proxy error: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:16:38 172.18.0.1 core[1308]: 2019/08/17 06:16:38 #033[1;44m[D] [server.go:2619] |  10.150.130.30|#033[41m 502 #033[0m|   2.906001ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Aug 17 14:16:38 172.18.0.1 core[1308]: 2019-08-17T06:16:38Z [ERROR] [interceptors.go:137]: Failed to get digest for reference: latest, error: Head http://registry:5000/v2/middleware/mysql/manifests/latest: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:16:38 172.18.0.1 core[1308]: 2019/08/17 06:16:38 #033[1;44m[D] [server.go:2619] |  10.150.130.30|#033[41m 500 #033[0m|  22.270306ms|   match|#033[44m GET     #033[0m /v2/middleware/mysql/manifests/latest   r:/v2/*#033[0m
Aug 17 14:16:43 172.18.0.1 core[1308]: 2019/08/17 06:16:43 #033[1;44m[D] [server.go:2619] |  10.150.130.45|#033[41m 502 #033[0m|   3.416801ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Aug 17 14:16:43 172.18.0.1 core[1308]: 2019/08/17 06:16:43 http: proxy error: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:16:43 172.18.0.1 core[1308]: 2019-08-17T06:16:43Z [ERROR] [interceptors.go:137]: Failed to get digest for reference: latest, error: Head http://registry:5000/v2/middleware/mysql/manifests/latest: dial tcp 172.18.0.5:5000: getsockopt: connection refused
Aug 17 14:16:43 172.18.0.1 core[1308]: 2019/08/17 06:16:43 #033[1;44m[D] [server.go:2619] |  10.150.130.45|#033[41m 500 #033[0m|  22.069405ms|   match|#033[44m GET     #033[0m /v2/middleware/mysql/manifests/latest   r:/v2/*#033[0m
Aug 17 14:16:58 172.18.0.1 core[1308]: 2019/08/17 06:16:58 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|     2.8084ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
---------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/29512072/63207542-9ecb6e80-c0fa-11e9-8bb0-d11dd1f1b68c.png)

**Comment by louyiping** [comment]
I've met this error once.Maybe the root cause is docker embedded dns has something wrong.
And I solve it by restart docker service.

**Comment by bitsf** [comment]
This seems the docker registry is crashed, not relative harbor itself problem.
And next time if you meet the problem, you should paste registry.log which may give more help.
