### ISSUE TITLE
when retag a  content untrust image, harbor return 500 instead of a readable warning message.

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8729]
![image](https://user-images.githubusercontent.com/44018302/63241600-e41ca700-c286-11e9-9ad6-07de7abe7b93.png)

**Comment by wy65701436** [comment]
@cd1989, can you have a look?

**Comment by wy65701436** [comment]
More infor for you:

[Steps to reproduce]
1, add a project and push/sign an image.
2, enable content trust
3, retag the signed image to another project.

The retag tries to pull manifest, it may faile by the content trust interceptor.

**Comment by cd1989** [comment]
I have tried, but didn't reproduce the problem you mentioned. @wy65701436 

![image](https://user-images.githubusercontent.com/16573984/68728086-41fc2900-0601-11ea-9a72-9f97c6ad0f25.png)

**Comment by danfengliu** [comment]
It's fixed already, now it returns Error-412.
