### ISSUE TITLE
No default selection of CVE while list radio button in project configuration page

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8732]
I think "Project Whitelist" should be a default selection.

![image](https://user-images.githubusercontent.com/44018302/63247411-8cd30280-c297-11e9-93a0-18c20fd227e3.png)

**Comment by reasonerjt** [comment]
@AllForNothing  this can be dupped?

**Comment by AllForNothing** [comment]
fixed in PR #8716. And "System whitelist" is default value.
