### ISSUE TITLE
CVE whitelist UI improvement

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#8740]
on the project config page, please change
"Use the system whitelist as is or select “Project whitelist” to create a new whitelist."
to
"You can either use the default whitelist configured at the system level or click on 'Project whitelist' to create a new whitelist"

& please change 
"Merge the system whitelist into this project, add individual CVE IDs"
to
"Add individual CVE IDs before clicking 'ADD SYSTEM' to add system whitelist as well

**Comment by AllForNothing** [comment]
fixed in PR #8739
