### ISSUE TITLE
Question about updating Harbor from version 1.5.1 to 1.6.3

### ISSUE THREAD

**Issue by jarduini** [goharbor/harbor#8741]
Hi, we have in production a Harbor version 1.5.1 and we want to update it to 1.6.3.
The thing is that we are using as harbor-db mysql (https://hub.docker.com/r/vmware/harbor-db/tags), and when i try to update, the docker compose file try to use an image of harbor-db based on postgresql (https://hub.docker.com/r/goharbor/harbor-db/tags). 
Is there any way to migrate from one version to the other one using mysql? 
Thanks in advance!
Javier

**Comment by bitsf** [comment]
We haven't do plan to support mysql back yet, maybe community can help test what would be the problem if using mysql and give feedback that we can measure the cost to do it.

**Comment by jarduini** [comment]
> 
> 
> We haven't do plan to support mysql back yet, maybe community can help test what would be the problem if using mysql and give feedback that we can measure the cost to do it.

Hi @bitsf what i would like to know if i have a way of migrating from mysql to postgresql (harbor-db).
because when I upgrade from version 1.5.1 to 1.6.3, the docker-compose.yml try to run the new image of harbor-db with postgresql.

**Comment by bitsf** [comment]
@ninjadq Could you help on this

**Comment by xaleeks** [comment]
There is not, and that db migration is not supported, we only support pgsql now, due to clair requirements essentially.  We have another ticket to explore pluggable support for various databases so we can support mysql again.  Please track that progress here https://github.com/goharbor/harbor/issues/6534.
