### ISSUE TITLE
nginx: [emerg] mkdir() "/etc//nginx/client_body_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by ruanshudong** [goharbor/harbor#8742]
why?

**Comment by reasonerjt** [comment]
@ruanshudong 
Please clarify what version and bundle are you using.
On what OS are you running Harbor.
When do you see such error.

**Comment by ruanshudong** [comment]
os: centos 7
harbor version: 1.8.2 and set https.
i found a bug, in harbor.yaml, cert and key must be named server.crt and server.key(i use domain as name, like this xx.xx.com.crt), otherwise nginx can't start, in /var/log/harbor/proxy.log:  can't  open server.crt. 
when i modify name to server.crt and server.key, nginx logs show:
nginx: [emerg] mkdir() "/etc//nginx/client_body_temp" failed (13: Permission denied) 

registry also can't be started, log in /var/log/harbor/registry.log:
Aug 19 22:28:59 172.21.0.1 registry[21490]: panic: unable to configure authorization (token): unable to open token auth root certificate bundle file "/etc/registry/root.crt": open /etc/registry/root.crt:
 permission denied

**Comment by ninjadq** [comment]
I think this issue is already fixed in the master branch

**Comment by bitsf** [comment]
@ninjadq what's the workaround for 1.8.x ? Will the fix be in 1.8.3 ?

**Comment by ninjadq** [comment]
@bitsf This is caused that nginx user does not have write permission in that dir
