### ISSUE TITLE
no "Registry Certificate" displaying in UI

### ISSUE THREAD

**Issue by afewell** [goharbor/harbor#8748]
Hi I setup and installed the certificate per the instructions, I prepped a client and it worked. 

Today I went to setup and went to the UI rather than the cli to find the cert, I go to the library project page and there is no "Registry Certificate" link shown at all, which is different from the documentation. 

I am running Harbor version v1.8.1-16b59c41

Any ideas why I have no link?

Here is a screenshot:

![image](https://user-images.githubusercontent.com/17549071/63321416-819ec780-c2d5-11e9-8dae-4d4c07f3fa77.png)

**Comment by bitsf** [comment]
Which document do you mean? Maybe it's outdate

**Comment by stonezdj** [comment]
You have to manually copy the root ca to /data/ca_download/ca.crt to enable this download link.
![Screen Shot 2019-08-23 at 11 11 06 AM](https://user-images.githubusercontent.com/2696760/63564315-387d9a80-c597-11e9-9f7f-98510faf7ef3.png)
