### ISSUE TITLE
When over 3 clients to visit all the tags of the repo, one of the clients will be failed by connect over time

### ISSUE THREAD

**Issue by HelenaZheng** [goharbor/harbor#8768]
When over 3 clients to visit all the tags of the repo at same time, one of the clients will be failed by connect over time.The tags in the repo is over 100. When i reduce the tags, all the client can visit ok. Whic param can make efferct on this problem?

**Comment by heww** [comment]
Do you visit all the tags of the repo by portal (harbor ui)  or API?

**Comment by bitsf** [comment]
Which version of harbor?
How many times do you meet this problem?

**Comment by HelenaZheng** [comment]
version:1.7.0

about 10 times, then I delete the tags of the repo. This problem disapper

**Comment by bitsf** [comment]
Do you mean you delete all the 100 tags, then it fixed, or you just delete some one tag?
Can it be reproduced if you add 100 tags again?

**Comment by HelenaZheng** [comment]
before had 170 tags, after 90 tags

**Comment by bitsf** [comment]
tried 500 images/tags in one repo, using 3 browsers to see the same repository images, not reproduce the problem.

version:1.9.0

**Comment by bitsf** [comment]
@HelenaZheng so you are running 3 "docker pull" command to download a same image among 500 images, and 1 would failed because of connection timeout with harbor 1.7.0.

**Comment by HelenaZheng** [comment]
why timeout? I think harbor can support multi clients access at same time in design发自我的华为手机-------- 原始邮件 --------发件人： Ziming <notifications@github.com>日期： 2019年10月8日周二 下午3:42收件人： goharbor/harbor <harbor@noreply.github.com>抄送： Helena <haiyan_zhe@163.com>, Mention <mention@noreply.github.com>主    题： Re: [goharbor/harbor] When over 3 clients to visit all the tags of the repo, one of the clients will be failed by connect over time (#8768)@HelenaZheng so you are running 3 "docker pull" command to download a same image among 500 images, and 1 would failed because of connection timeout with harbor 1.7.0.

**Comment by bitsf** [comment]
yes, actually docker pull process is almost directly contact with the upstream docker registry, only some token check is relative to harbor, so if docker registry itself support it, we should also support it.
@HelenaZheng What's the backend storage are you using? Have you ever created a lot of images and then deleted? Because registry didn't deleted folder, it may be slow to recursion of directories.
