### ISSUE TITLE
How can I stop the pending task of repelication?

### ISSUE THREAD

**Issue by HelenaZheng** [goharbor/harbor#8769]
Since more and more pending task will be keep in memory,  then the right task will also pending without memory.How can I stop and clean the pending task of repelication?

Aug 21 13:59:40 172.18.0.1 jobservice[21084]: 2019-08-21T05:59:40Z [ERROR] [handler.go:253]: Serve http request 'POST /api/v1/jobs/3d278055d4a5a0c9eaf5a004' error: 404 {"code":10013,"message":"object is not found","details":"job '3d278055d4a5a0c9eaf5a004'"}
Aug 21 13:59:40 172.18.0.1 jobservice[21084]: 2019-08-21T05:59:40Z [ERROR] [handler.go:253]: Serve http request 'POST /api/v1/jobs/3caf7b30ecdb2b8a5cdd8f3a' error: 404 {"code":10013,"message":"object is not found","details":"job '3caf7b30ecdb2b8a5cdd8f3a'"}

**Comment by steven-zou** [comment]
> Since more and more pending task will be keep in memory, then the right task will also pending without memory.How can I stop and clean the pending task of repelication?
> 
> Aug 21 13:59:40 172.18.0.1 jobservice[21084]: 2019-08-21T05:59:40Z [ERROR] [handler.go:253]: Serve http request 'POST /api/v1/jobs/3d278055d4a5a0c9eaf5a004' error: 404 {"code":10013,"message":"object is not found","details":"job '3d278055d4a5a0c9eaf5a004'"}
> Aug 21 13:59:40 172.18.0.1 jobservice[21084]: 2019-08-21T05:59:40Z [ERROR] [handler.go:253]: Serve http request 'POST /api/v1/jobs/3caf7b30ecdb2b8a5cdd8f3a' error: 404 {"code":10013,"message":"object is not found","details":"job '3caf7b30ecdb2b8a5cdd8f3a'"}

The pending jobs are kept in Redis, not in memory. The running ones will consume memory.

Can you give us more details about the problem? Like what's the Harbor version, how many job workers you set? Is it possible to provide the job service log?

**Comment by HelenaZheng** [comment]
harbor version：1.7.0
job workers ：max_job_workers = 3
grep "error: 404"  ./jobservice.log | wc -l
333

which I can found the error log is like 
Aug 21 15:53:28 172.18.0.1 jobservice[21084]: 2019-08-21T07:53:28Z [ERROR] [handler.go:253]: Serve http request 'GET /api/v1/jobs/644b6cc4f43825b388da81c3/log' error: 404 {"code":10013,"message":"object is not found","details":"644b6cc4f43825b388da81c3"}

The thing I see is that before I restart harbor memory used 99.5%， after just 15%

**Comment by steven-zou** [comment]
@HelenaZheng 

`404 Not Found` error occurred when calling `stop` job? That means the job stats info may be expired/removed in the Redis DB. 

  For this case, you need to update the related job status in admin job /scan job tables of the harbor database to fix the issue as a workaround.
