### ISSUE TITLE
More information about Consumer Data

### ISSUE THREAD

**Issue by jcmartins** [goharbor/harbor#8776]
**Is your feature request related to a problem? Please describe.**
My harbor is huge so I would like knows how project consume more disk and how tags is the big.

**Describe the solution you'd like**
A API endpoint to List space disk consumer per project and per tags 

**Describe the main design/architecture of your solution**
{
    "id": 1917,
    "name": "project_name",
    "project_id": 219,
    "description": "",
    "pull_count": 9796,
    "star_count": 0,
    "tags_count": 23,
    "containers_count": 50,
    "creation_time": "2019-03-27T20:50:49Z",
    "update_time": "2019-06-14T15:57:46Z",
    "consumer_storage": "25000000000"
  }

{
    "id": 1917,
    "name": "project_name/container_name",
    "project_id": 219,
    "description": "",
    "pull_count": 9796,
    "star_count": 0,
    "tags_count": 23,
    "creation_time": "2019-03-27T20:50:49Z",
    "update_time": "2019-06-14T15:57:46Z",
    "consumer_storage": "10000000"
  }

**Describe the development plan you've considered**
1 week

**Additional context**

**Comment by bitsf** [comment]
In harbor release 1.9.0 which coming soon, there will be a new function Quota per project, which will show disk consume info.
You can have a look first.

**Comment by jcmartins** [comment]
great!

**Comment by bitsf** [comment]
I close this first, and if you have other idea or requirement you can talk
