### ISSUE TITLE
How to reset lost admin password

### ISSUE THREAD

**Issue by jwalkins2017** [goharbor/harbor#8778]
What is the process to reset a lost admin password? The admin account is the only account that exist

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/63483146-f50b2980-c4cd-11e9-8e18-4d78eefde2ff.png)
I think you can update postgres db directly. The password here is Harbor12345. Then you can change to other after you login

**Comment by GYICN** [comment]
The password is encrypted based on the salt value, and a new password can be generated to replace the existing password based on the encryption algorithm and the salt value.

**Comment by bitsf** [comment]
Yes, but the simplest way I think is just copy other's value, if you don't know the detail encrypt algorithm.

**Comment by jwalkins2017** [comment]
@bitsf that worked for me, thank you for the help

**Comment by ryandotclair** [comment]
For folks who stumble on this thread as I did, it has changed (at least it's different on mine). Here's how you reset the password to Harbor12345:

update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830' where user_id = 1;

**Comment by jbonet** [comment]
> For folks who stumble on this thread as I did, it has changed (at least it's different on mine). Here's how you reset the password to Harbor12345:
> 
> update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830' where user_id = 1;

This is not working for me

**Comment by ryandotclair** [comment]
My advice to you @jbonet is to spin up a new harbor instance (same version as one you have) and set admin password to the default. Then check what the salt/pw values are in the DB and use that. That’s how I figured out for mine.

**Comment by lmigo** [comment]
This was working for me:
- within psql shell connect to registry db -` \c registry`
- `update harbor_user set salt='', password='' where user_id = 1;`
- restart psql
- login with admin:Harbor12345

**Comment by kebyn** [comment]
```python
from hashlib import pbkdf2_hmac

salt = "J6Duybf2UcRhKchR06VbJWimv31xrlnN"
plain_text_password = "Harbor12345"

# plain_text_password "plain text password"
# salt "salt field in database"
# password "password field in database"
# hash_name "password_version field in database"
# iterations "fixed value 4096 in code"
# dklen "fixed value 16 in code"
# https://github.com/goharbor/harbor/blob/release-2.11.0/src/common/utils/encrypt.go#L49
hash = pbkdf2_hmac(
    hash_name="sha256",
    password=plain_text_password.encode("utf-8"),
    salt=salt.encode("utf-8"),
    iterations=4096,
    dklen=16,
)
print(
    f"update harbor_user set salt='{salt}', password='{hash.hex()}' where user_id = 1;"
)
```

You can modify the appropriate `salt` and `plain_text_password`, calculate the `salt` and `password` fields of the database, and then use
`update harbor_user set salt='your_salt', password='your_password' where user_id = 1; `
to update the corresponding account password

**Comment by caicaicai** [comment]
`
your_host_hell# docker exec -it psql_container_id /bin/bash
container_shell# psql -U postgres
psql_shell# \c registry
psql_shell#update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830' where user_id = 1;
`


Now your harbor password has been successfully changed to Harbor12345

**Comment by crazyelectron-io** [comment]
I did a fresh install of Harbor and somehow neither the default password (Harbor12345) nor the explicitly defined password in a secret as specified in the Helm values.yaml file worked.
I tried to reset the password using @caicaicai 's commands and clearing the browser cache as mentioned by @TCNOco but I still get invalid password. I'm clueless how to fix this but for now I'll try the install without specifying a password secret and see if at least that works.

**Comment by mlwxxx** [comment]
> 我重新安装了 Harbor，但不知何故，默认密码 (Harbor12345) 和 Helm values.yaml 文件中指定的 secret 中明确定义的密码都不起作用。 我尝试使用[@caicaicai](https://github.com/caicaicai)的命令并清除浏览器缓存[@TCNOco](https://github.com/TCNOco)但我仍然得到无效密码。我不知道如何解决这个问题，但现在我将尝试在不指定密码的情况下进行安装，看看是否至少可行。

Restart the harbor-core pod after updating the harbor_user table.

**Comment by mlwxxx** [comment]
> I did a fresh install of Harbor and somehow neither the default password (Harbor12345) nor the explicitly defined password in a secret as specified in the Helm values.yaml file worked. I tried to reset the password using [@caicaicai](https://github.com/caicaicai) 's commands and clearing the browser cache as mentioned by [@TCNOco](https://github.com/TCNOco) but I still get invalid password. I'm clueless how to fix this but for now I'll try the install without specifying a password secret and see if at least that works.

Restart the harbor-core pod after updating the harbor_user table.

**Comment by vijayendra8080** [comment]
Worked for me .. 👍🤞❤️🥳

Stoped all the running containers of harbor i.e (harbor-trivy harbor-ui-nginx harbor-core harbor-registry harbor-redis harbor-db)

Created a new data directory.

Commented the password i was trying to provide while installing.

Started the script to up all the containers.

Ran, the following cmd:

```
docker exec -it harbor-db bash
psql -U postgres registry
update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830' where user_id = 1;
```

Now login to your harbor portal, with creds: 
`admin: Harbor12345`


Finally, change the admin password from UI.

**Comment by glebtv** [comment]
Since this is the top search result, and no answers from above seem to work now, here's an updated script that works for new Harbor with password_version column:

```python
#!/usr/bin/env python3
"""Reset a Harbor local DB user's password (Harbor >= 2.12 scheme).

Harbor v2.15 hashes passwords with PBKDF2-HMAC-SHA256, 600000 iterations,
16-byte derived key, and stores password_version='pbkdf2_sha256'
(see src/common/utils/encrypt.go). The old "reset to Harbor12345" SQL from
the wiki only works for the legacy 'sha256' version (4096 iterations) and
fails silently if password_version is 'pbkdf2_sha256' -> "Invalid credentials".

Usage:
    ./reset_password.py [username] [--password PASS] [--print-sql-only]

Defaults: username=admin, password is prompted interactively if not given.
Applies the UPDATE via `docker exec harbor-db psql`.
"""

import argparse
import getpass
import secrets
import string
import subprocess
import sys
from hashlib import pbkdf2_hmac

# Parameters matching src/common/utils/encrypt.go (Harbor v2.15)
HASH_NAME = "sha256"
ITERATIONS = 600000  # pbkdf2Iterations for PBKDF2SHA256 version
DKLEN = 16           # fixed key length in code -> 32 hex chars (fits varchar(40))
PASSWORD_VERSION = "pbkdf2_sha256"

DB_CONTAINER = "harbor-db"
DB_NAME = "registry"
DB_USER = "postgres"

SALT_ALPHABET = string.ascii_letters + string.digits
SALT_LEN = 32


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("username", nargs="?", default="admin", help="Harbor username (default: admin)")
    parser.add_argument("--password", help="New password (prompted if omitted)")
    parser.add_argument("--print-sql-only", action="store_true", help="Only print the SQL, do not apply it")
    args = parser.parse_args()

    password = args.password or getpass.getpass(f"New password for {args.username!r}: ")
    if not password:
        print("error: empty password", file=sys.stderr)
        return 1

    salt = "".join(secrets.choice(SALT_ALPHABET) for _ in range(SALT_LEN))
    digest = pbkdf2_hmac(
        hash_name=HASH_NAME,
        password=password.encode("utf-8"),
        salt=salt.encode("utf-8"),
        iterations=ITERATIONS,
        dklen=DKLEN,
    ).hex()

    username = args.username.replace("'", "''")
    sql = (
        f"UPDATE harbor_user SET salt='{salt}', password='{digest}', "
        f"password_version='{PASSWORD_VERSION}' WHERE username='{username}';"
    )

    if args.print_sql_only:
        print(sql)
        return 0

    result = subprocess.run(
        ["docker", "exec", DB_CONTAINER, "psql", "-U", DB_USER, "-d", DB_NAME, "-c", sql],
        capture_output=True,
        text=True,
    )
    print(result.stdout, end="")
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr, end="")
        return result.returncode
    if "UPDATE 1" not in result.stdout:
        print(f"error: user {args.username!r} not updated (not found?)", file=sys.stderr)
        return 1

    print(f"Password for {args.username!r} reset successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
```

**Comment by ryandotclair** [comment]
Ngl, I love how folks have been contributing to this "oops" over the years/releases. Thanks y'all.

**Comment by mkl262** [comment]
You should also verify that you set the `password_version` to sha256, using this query (password is still harbor12345):
```
update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830', password_version='sha256' where user_id = 1;
```
