### ISSUE TITLE
beego library should be upgrade

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8785]
We are using beego v1.9.0, which has some critical bug, such as the validation framework not function well (https://github.com/astaxie/beego/pull/3046).
Suggest to upgrade

**Comment by reasonerjt** [comment]
Thanks @bitsf

**Comment by ywk253100** [comment]
`RunWithMiddleWares` is introduced in the new versions of beego, let's upgrade it to the latest one @heww

**Comment by heww** [comment]
Done
