### ISSUE TITLE
soft deletion of project metadata will cause failure of re-adding the metadata with the same key again

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#8791]
Delete should be hard action

**Comment by wy65701436** [comment]
get the same issue on build: harbor-offline-installer-v1.9.0-build.2007.tgz, UI shows the internal error, and I got the pg error in my core.log

`Aug 22 23:34:07 192.168.176.1 core[1619]: 2019-08-23T06:34:07Z [ERROR] [/common/api/base.go:228]: pq: duplicate key value violates unique constraint “unique_project_id_and_name”`

**Comment by ywk253100** [comment]
Fixed by #8856
