### ISSUE TITLE
Delete image fail, showing quota relatived error

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8793]
harbor dev branch
commit: f930786050a239271b4229c406901a86390cc3ed

After delete some image successful, suddenly it failed, and can never succeed on this repo. Other repo's image can still be deleted

![image](https://user-images.githubusercontent.com/188115/63507656-ca8b9180-c50a-11e9-9650-e1fc21962fb1.png)

**Comment by wy65701436** [comment]
did some investigation, this issue is duplicate with #8888
