### ISSUE TITLE
Tag Retention By image count or number of days should has limited days

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#8803]
1.When a large number of values are input, the values are first turned into scientific counts and then cleared.
2. save error
![image](https://user-images.githubusercontent.com/29826789/63572364-4c37f980-c5b5-11e9-8e0f-e9c111bfca9b.png)
![image](https://user-images.githubusercontent.com/29826789/63572637-e435e300-c5b5-11e9-8e0f-d60fc9b63e31.png)

![image](https://user-images.githubusercontent.com/29826789/63572392-56f28e80-c5b5-11e9-8d41-68b09372c463.png)

**Comment by jwangyangls** [comment]
After discussion, it is considered that the maximum setting of 20190904 is more appropriate.

**Comment by AllForNothing** [comment]
fixed in PR #8834

**Comment by bitsf** [comment]
fixed by https://github.com/goharbor/harbor/pull/8846
