### ISSUE TITLE
Tag Retention :the madel should not close,and it should be show the error message in  current page  when save error

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#8805]
![image](https://user-images.githubusercontent.com/29826789/63573108-13991f80-c5b7-11e9-91f8-e8d607c19622.png)
![image](https://user-images.githubusercontent.com/29826789/63573440-eef17780-c5b7-11e9-9d69-cd21d73bc3af.png)

**Comment by bitsf** [comment]
fixed by https://github.com/goharbor/harbor/pull/8812

**Comment by jwangyangls** [comment]
After discussion, it is considered that the maximum setting of 20190904 is more appropriate.

**Comment by AllForNothing** [comment]
fixed in PR #8834
