### ISSUE TITLE
Chart count is not calculated into the count quota of project

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#8806]
<img width="1189" alt="Screen Shot 2019-08-23 at 15 00 57" src="https://user-images.githubusercontent.com/5753287/63573068-f82e1480-c5b6-11e9-96b6-6d9592aabc3f.png">

`1+3 = 4 <> 1`

**Comment by steven-zou** [comment]
Quota bar is not effective for chart uploading neither.

**Comment by heww** [comment]
The regex issue for match chart upload and delete url.

**Comment by wy65701436** [comment]
close it as dup with #8701
