### ISSUE TITLE
no meaningful error message returned when action like retag etc. exceeding the quota

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#8807]
<img width="1191" alt="Screen Shot 2019-08-23 at 15 26 12" src="https://user-images.githubusercontent.com/5753287/63574510-82c44300-c5ba-11e9-87c6-d67ef5bb6111.png">

**Comment by wy65701436** [comment]
will be updated to : 
![image](https://user-images.githubusercontent.com/2841473/63674217-a4bb0100-c818-11e9-953e-cd0759eeb515.png)

**Comment by reasonerjt** [comment]
Given the payload of the response is structured this way to make it recognizable.  And the text in the JSON is readable to end user in UI.

I don't see it very high priority to prettify this error.

**Comment by danfengliu** [comment]
I found a very similar issue in latest version:

**Test Descrition**
        Retag a image to a project with not sufficient storage size and sufficient image count, then "Internal Error" occurred.

![image](https://user-images.githubusercontent.com/44018302/63930071-3333ba80-ca85-11e9-963d-fdc29f59a34e.png)

![image](https://user-images.githubusercontent.com/44018302/63930040-22834480-ca85-11e9-9fc5-5c402ce3bf8f.png)

![image](https://user-images.githubusercontent.com/44018302/63929977-fb2c7780-ca84-11e9-9bcc-bc97b19b39fc.png)
