### ISSUE TITLE
[tag retention] The conflict rules can be created by "Edit"

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8811]
[Steps]
1, create Rule A in UI, with retain always.
2, create Rule B in UI, with different options.
3, edit Rule B, make it exactly the same as Rule A.

After that, I get the two same rules, but not 409 in the log.

BTW, If I try to create the same rule with one the existing, the UI can index me the conflict error.

**Comment by bitsf** [comment]
Not reproduced

**Comment by AllForNothing** [comment]
fixed in PR #8834
