### ISSUE TITLE
Quota doesn't work as expected after running GC

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8815]
The steps to reproduce the issue:
1. Prepare a totally fresh Harbor instance without any data
2. Create a project called `yinw` and set storage quota to `200M`
3. Push `golang:1.11.2`(280M) to `yinw`, failed and 160M blobs are pushed, the usage is changed to 160M
4. Run GC, the usage is changed to 0
5. Push again, success and the usage is changed to 120M

**Comment by wy65701436** [comment]
@ywk253100  Good catch, the root cause is that the GC job doesn't clean the untagged blobs in table project_blob. 

I will have a fix.
