### ISSUE TITLE
Tag retention rule should not created when repo exclude all

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor#8816]
When rule's repo part is `exclude **` it is not affected to any repo. 
![image](https://user-images.githubusercontent.com/1069785/63583274-42ba8b80-c5cd-11e9-8695-2027c162999c.png)
Suggest restricting the user to create a rule like this.

**Comment by bitsf** [comment]
This is actually harmless, why we have to check this, I don't think we have to challenge user for this.

**Comment by AllForNothing** [comment]
fixed in PR #8834
