### ISSUE TITLE
The most recently pushed 3 images with tags matching ** rule failed

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#8817]
1.Create a rule in library
For the repositories matching **, retain the most recently pushed 3 images with tags matching **
2. Schedule this rule with */3 * * * * *
3. Push image  hello-world:build1, hello-world:build2,  hello-world:build3,  hello-world:build4,  hello-world:build5.
4. Only found the first 3 tags, not the latest pushed tags.
<img width="1005" alt="Screen Shot 2019-08-23 at 6 00 58 PM" src="https://user-images.githubusercontent.com/2696760/63584908-8367d400-c5d0-11e9-98de-d9ebaf670d6c.png">

**Comment by reasonerjt** [comment]
@stonezdj please verify if this has been fixed.

**Comment by stonezdj** [comment]
fixed
