### ISSUE TITLE
Harbor API image scan not successful

### ISSUE THREAD

**Issue by megantexo** [goharbor/harbor#8827]
**Expected behavior and actual behavior:**
When I open the swagger page for the Harbor API Explorer, and when I execute the POST command to scan an image, I get a 415 error: Unsupported Media Type.

**Steps to reproduce the problem:**
1. Load the Harbor API Explorer.
2. Add a "repository name" and "tag" to the POST command 
​/repositories​/{repo_name}​/tags​/{tag}​/scan
3. Execute the POST command.
`curl -X POST "https://<harbor_url>/api/repositories/<image>/tags/<tag>/scan" -H "accept: application/json"`
4. In response, I get 415: Error: Unsupported Media Type.
` connection: keep-alive 
 content-length: 0 
 content-type: text/plain; charset=utf-8 
 date: Fri, 23 Aug 2019 21:37:02 GMT 
 server: nginx `
I can, for example, use the same repo name and tag to get a list of the vulnerabilities in the image. It seems to be only the scan that's failing.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.8.1-16b59c41 (though the swagger page says 1.8.0)

**Comment by chlins** [comment]
@megantexo Maybe due to headers, in the harbor swagger explorer, use "accept: application/json", it will return 415 error, when i try to use "Content-Type: application/json", it's 200 ok.

**Comment by megantexo** [comment]
Ah, you're right, I had to run it outside of the swagger explorer, and add the "Content-Type: application/json", thank you very much. Looking around the explorer, most of the other POST commands have the option "Parameter content type." Is this something that can be added to the scan API for clarity?
