### ISSUE TITLE
The migrator should accept yml file as input configuration file

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8838]
1)Currently I have to run the following command to perform migration of harbor.yml for 1.8 -> 1.9 upgrade:
`# docker run -it --rm -v ~/harbor-v1.8/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.cfg -v ~/harbor-latest/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:dev`

It is super counter-intuitive that user has to mount a `.yml` file as a `.cfg` file.  Let's introduce some fallback mechanism if the `.yml` file does not exist, look for a `.cfg` file so the compatibility is not broken.

2)The migration guide should be updated accordingly.

**Comment by ninjadq** [comment]
the docker will update in #8850

**Comment by reasonerjt** [comment]
Closing as this is fixed.
