### ISSUE TITLE
Fail to upgrade due to quota initialization 

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8839]
I tried to migrate the data when upgrading from 1.8 -> 1.9 
The env has around thousand of images and consume 200+GB of storage. 

While syncing the data for quota usage there's error:

```
Aug 26 10:40:13 172.30.0.1 core[2686]: 2019-08-26T10:40:13Z [ERROR] [/core/api/quota/registry/registry.go:244]: pq: value "4069985900" is out of range for type integer
Aug 26 10:40:13 172.30.0.1 core[2686]: 2019-08-26T10:40:13Z [ERROR] [/core/main.go:102]: Fail to sync quota data, pq: value "4069985900" is out of range for type integer
Aug 26 10:40:13 172.30.0.1 core[2686]: 2019-08-26T10:40:13Z [FATAL] [/core/main.go:242]: quota migration error, pq: value "4069985900" is out of range for type integer
```

**Comment by wy65701436** [comment]
It's because we use `int` as the type of blob size, but the maximum of int in PG is `-2147483648 to +2147483647`.

I will change it to bigint, which maximum is  `-9223372036854775808 to 9223372036854775807` and it could satisfy the big blog size.
