### ISSUE TITLE
Upgrade harbor from 1.8.1 to 1.8.2 steps?

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#8840]

**Comment by dbenduga** [comment]
Can someone please help with harbor up-gradation process?

**Comment by reasonerjt** [comment]
@dbenduga what error are you seeing?
You should not need any extra steps for 1.8.1 -> 1.8.2 upgrade.

**Comment by dbenduga** [comment]
I have not started yet.. just need upgradation steps .

**Comment by dbenduga** [comment]
f any one has upgraded harbor from 1.8.1 to 1.8.2. Please share steps... Thanks

**Comment by dbenduga** [comment]
if any one has upgraded harbor from 1.8.1 to 1.8.2. Please share steps... Thanks
