### ISSUE TITLE
Harbor does not sync users / permissions

### ISSUE THREAD

**Issue by dgabrysch** [goharbor/harbor#8847]
I am using Harbor with docker-compose and use the replication for backing up the primary one. Replicating the Repositories is working perfectly, but I noticed that neither users that have logged in ( I am using LDAP for auth) nor their permissions are synced, so when the primary Harbor instance goes down I have all the data, but pulling / pushing won’t work.

Is there a plan for implementing this functionality in Harbor, or is it just like this?

**Comment by Drew-Jay** [comment]
I find this question **too** ! how do you handle this problem

**Comment by charnet1019** [comment]
Same issue

**Comment by liabio** [comment]
Same issue
