### ISSUE TITLE
Harbor 1.8.2 deployment in HA

### ISSUE THREAD

**Issue by roldancer** [goharbor/harbor#8848]
Hi All, Is there any documentation about Harbor 1.8.X deployment in HA ? 

I remember that for Harbor 1.5.X there was a specific official document about Harbor 1.5.X deployment in HA, is there something similar for 1.8.X ?

Many thanks.

**Comment by roldancer** [comment]
Hi, It means that if I want to deploy Harbor 1.8.X in HA I must have a Kubernetes infrastructure, right ?

Bye.

**Comment by roldancer** [comment]
Hi @thyarles  the synchronization options works for the entire Harbor? can the synchronization service synchronize users/role in every project ?

Thanks

**Comment by thyarles** [comment]
Hi @roldancer, good point... I used to sync only few projects (production only), never be in my mind synchronize everything. If you discover the answer by yourself, please. let us know!

Thanks.
