### ISSUE TITLE
ldap_group_admin_dn doesn't work

### ISSUE THREAD

**Issue by obeyler** [goharbor/harbor#8849]
this issue was previouly open on harbor bosh release but they say that is related to harbor
 https://github.com/vmware/harbor-boshrelease/issues/49

Even with the ldap_group_admin_dn set to a group, an user from this group is not declare as admin in harbor
extract from openldap ui: 
![image](https://user-images.githubusercontent.com/23224162/56030339-e7be8100-5d1c-11e9-9668-ed412aa1b1a8.png)
extract from harbor ui: 
![image](https://user-images.githubusercontent.com/23224162/56030410-10df1180-5d1d-11e9-8f4a-02c071007647.png)

![image](https://user-images.githubusercontent.com/23224162/56030510-4ab01800-5d1d-11e9-8581-c7baed1bbefa.png)
note that user obeyler belong to the admin group 
it is not oracle ldap server, it's open ldap
the group membership is memberOf

**Comment by alexdodson** [comment]
Hello,

Do you have the memberof overlay schema in your OpenLDAP config? I am seeing similar issues but I don't have memberof overlay because sycnrepl and memberof arent compatible. Is there any other work around to this?

**Comment by stonezdj** [comment]
@alexdodson there is no work around for this.

**Comment by stonezdj** [comment]
@obeyler  Please check your LDAP have enabled the memberof overlay
https://technicalnotes.wordpress.com/2014/04/19/openldap-setup-with-memberof-overlay/
