### ISSUE TITLE
Unable to configure external database in harbor 1.8

### ISSUE THREAD

**Issue by cmpmohan** [goharbor/harbor#8851]
What can we help you?

We are trying to install harbor 1.8 with external postgresql database. when we are trying to run installer script its saying below error

=========================================

[Step 2]: preparing environment ...
prepare base dir is set to /root/harbor
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 39, in main
    prepare_db(config_dict)
  File "/usr/src/app/utils/db.py", line 17, in prepare_db
    harbor_db_password=config_dict['harbor_db_password'])
KeyError: 'harbor_db_password'
================================================

We have configured external database as below two steps. lets know 1.8 is supported to external database. please help us to fix issue.

1) comment the harbor internal DB 
# Harbor DB configuration
#database:
  # The password for the root user of Harbor DB. Change this before any production use.
#  password: <password>

2) uncomment the external DB as below
# Uncomment external_database if using external database.
external_database:
harbor:
        host: <DB_host_name>
        port: 5432
        db_name: <DB_name>
        username: <DB_user_name>
        password: <password>
#     ssl_mode: disable

**Comment by reasonerjt** [comment]
@cmpmohan did you leave the `password` attribute empty?

**Comment by cmpmohan** [comment]
Hi reason..

there was identical syntax error in yaml.. issue fixed now

Thanks
