### ISSUE TITLE
docker manifest broken after upgrade to 1.8.2 from 1.6.0

### ISSUE THREAD

**Issue by davidgtmp** [goharbor/harbor#8855]
Prior to v1.8.2 (in my case, it was 1.6.0), I could push manifest lists. After the upgrade to v1.8.2, an error is thrown when trying to push a manifest list, effectively breaking all our multi-arch images, which previously worked.

Using manifest-tool (worked on 1.6.0), I get this error:
`manifest-tool push from-spec manifest.yml`
`FATA[0000] Registry push unsuccessful: response 415: 415 Unsupported Media Type`

Using docker manifest (never tried on 1.6.0), I get this error:
`docker manifest push harbor_reg/image:tag`
`failed to put manifest harbor_reg/image:tag: unknown: Manifest.list is not supported.`

**Comment by reasonerjt** [comment]
@davidgtmp 
This is working as design, that Harbor does not support manifest list.  So we intentionally blocked it to prevent further inconsistent errors.

**Comment by fanyangyang** [comment]
@reasonerjt so that, i can't query manifest list to confirm an image exists or not ? 

and another question

does further version of harbor support manifest list ?
