### ISSUE TITLE
tag retention only filter the first input tag though multiple tags filled.

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#8861]
**Expected behavior and actual behavior:**
if users input multiple tags, the retention should make sure all tags filled are remained. 

**Steps to reproduce the problem:**
configuring multiple tags like below:
For the repositories matching **, retain always with tags matching dev, v1.8.1*,v1.8.2*,
do a dry-run to check the remaining images, only 'dev' tagged images kept, others tags are ignored. 

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.9.0 latest dev build

**Comment by bitsf** [comment]
This is because a spare space is added to the tag selector, so it's not matched

**Comment by bitsf** [comment]
@AllForNothing We can limit what user input here, not allow input space

**Comment by bitsf** [comment]
fixed by https://github.com/goharbor/harbor/pull/8864
