### ISSUE TITLE
tag retention should keep the retained tag which has same digest with another tag

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#8866]
If one digest associate with two tags, and one tag is config to be retain, another to be delete, currently the final result is to delete both.
This is more dangerous, we should prefer keep both.
Note: currently docker registry api doesn't support delete special tag only

**Comment by bitsf** [comment]
fixed by pr https://github.com/goharbor/harbor/pull/8867

**Comment by xaleeks** [comment]
just a quick correction, this is not really a fix but more like a compromise.  real fix coming on https://github.com/goharbor/harbor/issues/2663
