### ISSUE TITLE
Tooltip in Webhooks view talks about image replication

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#8868]
This tooltip doesn't seem like it's correct:

![webhooks-replication-message.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/e166fb0b-d2ca-4270-b786-28ec901355c1)

Found in Version v1.9.0-8e5ea7bd

**Comment by xaleeks** [comment]
This is definitely a typo.  @mmpei
