### ISSUE TITLE
Support for symbolic links in the repository data file storage

### ISSUE THREAD

**Issue by jcambronero** [goharbor/harbor#8870]
Hello, as our utilization of Harbor keeps on increasing, we have found the need to start splitting the repository data file storage into multiple file storage back ends (NFS volumes).
We started with a single NFS volume and that has worked great so far, but that volume has grown beyond what is manageable and we would like to start creating smaller dedicated volumes for specific repositories.
We tested our approach by manually creating directories with the right permissions inside the NFS volume before creating the repository in Harbor, and ensuring that everything works as expected.

We then tested the approach of using symbolic links (instead of manually created folders) but it's failing claiming that the "file exists". It seems to us that Harbor (or Golang) won't recognize the symbolic links as existing folders and therefore attempts to recreate them, generating this "file exists" error.

Here's what our repository data NFS volume looks like:
```
server:/nfs-path/docker/registry/v2/repositories# ls -lat
drwxrwxrwx 18 caasnfs user    4096 Aug 22 14:13 .
lrwxrwxrwx  1 nobody  nogroup   45 Aug 22 13:44 new-test -> /nfs-path/test_area_3/
drwxr-xr-x  4 nobody  nogroup 4096 Aug 22 13:39 abc
drwxr-xr-x  3 nobody  nogroup 4096 Aug 22 13:37 def
drwxrwxrwx  4 caasnfs user    4096 Oct 16  2018 ..
```
The "abc" and "def" folders we created manually and are able to push/pull images just fine.
The "new-test" is a symbolic link to a different NFS volume and that's the one failing with the "file exists" error.

Here's the full error log:
```
time="2019-08-28T20:26:39.779276303Z" level=error msg="response completed with error" auth.user.name="user01" err.code=unknown err.detail="filesystem: mkdir /storage/docker/registry/v2/repositories/new-test: file exists" err.message="unknown error" go.version=go1.11.8 http.request.host=my-registry.com http.request.id=f5f06b22-6f0d-4c33-85b5-b0adc1657313 http.request.method=POST http.request.remoteaddr=10.3.58.228 http.request.uri="/v2/new-test/gitlab-runner/blobs/uploads/" http.request.useragent="docker/17.09.1-ce go/go1.8.7 git-commit/f4ffd2511ce9 kernel/4.4.121-92.104-default os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.511379ms http.response.status=500 http.response.written=189 vars.name="new-test/gitlab-runner"
10.42.0.104 - - [28/Aug/2019:20:26:39 +0000] "POST /v2/new-test/gitlab-runner/blobs/uploads/ HTTP/1.1" 500 189 "" "docker/17.09.1-ce go/go1.8.7 git-commit/f4ffd2511ce9 kernel/4.4.121-92.104-default os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(linux\\))"
time="2019-08-28T20:26:39.803383034Z" level=error msg="response completed with error" auth.user.name="user01" err.code=unknown err.detail="filesystem: mkdir /storage/docker/registry/v2/repositories/new-test: file exists" err.message="unknown error" go.version=go1.11.8 http.request.host=my-registry.com http.request.id=b1624ab0-6b03-4281-8395-8e8258a6eed7 http.request.method=POST http.request.remoteaddr=10.3.58.228 http.request.uri="/v2/new-test/gitlab-runner/blobs/uploads/" http.request.useragent="docker/17.09.1-ce go/go1.8.7 git-commit/f4ffd2511ce9 kernel/4.4.121-92.104-default os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.495027ms http.response.status=500 http.response.written=189 vars.name="new-test/gitlab-runner"
```

Will it be possible to enable support for symbolic links so that our NFS volumes become more manageable?

Thanks for your help,
Jose

**Comment by memory-yancy** [comment]
Same issues, looking forward to this features!  :+1: 

Our scenario is similar with yours @jcambronero , it contains 10G+ `registry` in Ceph(HA Harbor). In order to testing Harbor install, we have tried to use soft link to provide `registry`, but it failed while using `docker pull` or `docker push`
```
$ harbor_registry_dir="/pkg/registry"
$ harbor_installed_dir="/target/dir"
$ ln -sf $harbor_registry_dir/docker $harbor_installed_dir/registry/docker
```

Aftering debug, see error log in `harbor-goharbor-registry-7f848fd977-7l7rk` pod log, use `rsync` or `cp` data to target directory is successful!

**Comment by sacashgit** [comment]
This will be indeed **very helpful** so we have way for distributing our storage in smaller volumes which would in turn help in taking back up, snapshots as well as scale the storage (per project or set of projects).
