### ISSUE TITLE
[Tag retention] UI error message should give the hint about what's wrong

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8878]
Please give a reasonable error to index which attribute is wrong. 

And actually, the validation is not depended on API's response but done by UI.  Is it make sense?

![image](https://user-images.githubusercontent.com/2841473/63916336-ca3f4900-ca6a-11e9-9cbb-10fcce20fe3b.png)

**Comment by AllForNothing** [comment]
fixed in PR #8890
