### ISSUE TITLE
[Tag retention] It should provide a column to index the execution type (Schedule or Manual)

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8880]
I cannot know the execution of retention is triggered by manual or by the timer.

![image](https://user-images.githubusercontent.com/2841473/63918910-425c3d80-ca70-11e9-91ef-375358b5985e.png)

**Comment by AllForNothing** [comment]
will add new column "Execution Type" to the datagrid

**Comment by AllForNothing** [comment]
fixed by PR #8890 and #8898
