### ISSUE TITLE
[Web hook] The error message is not clear to understand

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8881]
[Steps]
1, login as a user with a `master` role
2, Type a wrong endpoint.

The UI gives me an error message with `User`, I cannot get the root cause from the prompt.
![image](https://user-images.githubusercontent.com/2841473/63919412-49d01680-ca71-11e9-94e9-cda9cf568bea.png)

### Request:
POST
./api/projects/1/webhook/policies/test

### Response
{"code":403,"message":"user"}

**Comment by tedgxt** [comment]
@BeHappyF UI should adapt the API response rather than displaying the response body info on the UI directly.

**Comment by wy65701436** [comment]
my fault, buddy. Close it not a bug.
