### ISSUE TITLE
The foreign layers should not be taken into account during migration "docker push"

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8886]
Some images, esp. the ones based on windows, have foreign layers, those layers are referenced in manifest of the image, but do not really take space on registry.

When calculating the storage usage of a project, we should not calculate the foreign layers.

1. During migration or re-sync we should not populate foreign layers into `project_blob` tabel.
2. Please make sure the foreign layers are not intercepted during `docker push`

**Comment by wy65701436** [comment]
close it as pr https://github.com/goharbor/harbor/pull/8887
