### ISSUE TITLE
Project quotas statistic data decreased when one of this project images retagged to other project and retagged image was delete and then perform GC

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8888]
**Test Step**
1. Create project bb and set quota to 8 images and 1G;
2. Push 2 images wordpress:latest and logstash:7.3.1 to project bb;
2. Create project cc and set quota to 2 images and 500M;
3. Go into project bb and retag image logstash:7.3.1 to project cc;
4. Delete image logstash:7.3.1 in project cc;
5. Perform GC;
6. Check project quotas statistic data;

**Expected**
    1. Project cc storage size decrease to 0;
    2. Project bb storage size stay the same;

**Result**
    1. Project cc storage size decrease to 0;
    2. Project bb storage size decrease 350M, it's size of image logstash:7.3.1.

![image](https://user-images.githubusercontent.com/44018302/63929037-4ba2d580-ca83-11e9-8346-0426805530fa.png)

**Comment by wy65701436** [comment]
thanks @danfengliu,  the root cause of this issue is, the image has two blobs with same digest id, which causes the artifact&blob cannot be inserted successfully by unique limitation.
