### ISSUE TITLE
Quota disk space edit should be more intelligent for carry bit

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8892]
Quota disk space edit should be more intelligent 

![image](https://user-images.githubusercontent.com/44018302/63933296-8a3c8e00-ca8b-11e9-937c-3ebbe274f926.png)
![image](https://user-images.githubusercontent.com/44018302/63933406-be17b380-ca8b-11e9-8f0c-a68d087f9e5f.png)

**Comment by AllForNothing** [comment]
modified css only. Closing.
![image](https://user-images.githubusercontent.com/30999793/63995601-b7407d80-cb2b-11e9-8e2c-da2675710b24.png)
