### ISSUE TITLE
Size difference

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#8906]
I am replicating repo's from old harbor (1.5.0) to new harbor (1.8.1).  after replication i see huge size difference. Old harbor has around 5.9 TB data and on new harbor data size is showing only 2.7TB.

I have matched repo counts and tag counts, don't find any difference.

 Want to know why this much size difference between old harbor and new harbor.
Note: In our environment user delete images regularly. We run garbage collection once in a month.

GC process we follow on 1.5.0 :  we stop harbor and then run below command  gc
docker run -it --name gc --rm --volumes-from registry goharbor/registry:2.6.2-photon garbage-collect /etc/registry/config.yml 

Please verify this process is correct or not..

NOTE: This is very very urgent we planning to move to new harbor  however due to size difference we are in question mark why this much size difference is there

**Comment by mapleflow** [comment]
in document, replication not support different version.

**Comment by jcmartins** [comment]
The repo size difference is normal.
But you need migrate the database too to have the user permissions and it's a little bit more complicated.

**Comment by dbenduga** [comment]
Hi Carlos,

Is there any specific reason for size difference??
