### ISSUE TITLE
Improve Frontend Unit Test coverage 

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#8911]
Currently, we have few frontend unit test, to make sure some of the main features will not be easily break. We need to add some useful unit test for the core functionality.

**Comment by jwangyangls** [comment]
Until now, the test coverage of the front end is:
part1：
![image](https://user-images.githubusercontent.com/29826789/68106561-f1a80b80-ff1c-11e9-8f6e-038fca6c856f.png)
part2：
![image](https://user-images.githubusercontent.com/29826789/68106583-04224500-ff1d-11e9-9da9-b058e1f87979.png)

**Comment by AllForNothing** [comment]
Will continue the work for the next version 1.11.0 .    Close this one.
