### ISSUE TITLE
provide a single all-in-one docker image please

### ISSUE THREAD

**Issue by Emeryao** [goharbor/harbor#8915]
Hi Team

**Is your feature request related to a problem? Please describe.**
No.
Currently, I feel it a little complex to install harbor with the installer provided on the release tab for some reason
  * the installer requires docker-compose
  * too many containers after installation
  * a lot of networks are created after installation and sometimes they are often not connected with the containers

**Describe the solution you'd like**
Provide a single all-in-one docker image with all the dependencies within like nginx postgres so it would be easy to start a harbor instance out of the box with a single `docker run` command or even further to a cluster like docker swarm

Thanks
---
sorry for my poor English

**Comment by reasonerjt** [comment]
Considering Harbor requires multiple services and components, some of which are 3rd party, I don't think providing an all-in-one image makes any sense.

There are many containers because there are that many components to support all the features.

**Comment by reasonerjt** [comment]
I'm closing as a won't fix.

If you need a all-in-one image, you can try to build one and we can reference it in case other users need it.

**Comment by seanmmitchell** [comment]
Very Unfortunate 😢
