### ISSUE TITLE
Question importing users from LDAP.

### ISSUE THREAD

**Issue by jarduini** [goharbor/harbor#8921]
Hi, I’m importing users via API using Swagger from OpenLdap and when I get 500 users, the user 501 is not created on harbor.
Harbor has a limit of 500 users? How can I solve this?

Harbor version: v1.8.2
I’m using this curl to import users:
curl -X POST "http://localhost/api/ldap/users/import" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"ldap_uid_list\": [ \"string\" ]}"

**Comment by stonezdj** [comment]
Can you please upload the error log,  it locate in  /var/log/harbor/core.log

**Comment by stonezdj** [comment]
There is no need to import user explicitly, the user is imported in background when required, for example login to Harbor, add this user to a project member. etc.

**Comment by jarduini** [comment]
hi @stonezdj I’m importing the users from an older harbor (version 1.5.2) to a new installation (v1.8.2) via harbor API. I already created a script to read all projects, users, members per projects and permissions via API from the old harbor and created all the same structure in the new harbor. I realize yesterday entering on the postgresql database, that the users are created inside the database. So, the problem is the harbor portal (v1.8.2) that in users only shows 500 elements. Is this a bug?

**Comment by stonezdj** [comment]
Yes, it is a bug that the UI doesn't passed the pagination in Harbor 1.8 or 1.7, the backend query will query 500 rows without pagation parameters, it is already fixed in 1.9
