### ISSUE TITLE
Migrating to 1.9 take a few minutes before API is callable due to Quota

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8935]
On an env with more than 1TB image data, 70k+ blobs and thousands of images.

When I migrate from 1.8 to 1.9, it took ~6 mins to finish the migration as the `core` will walkthrough all blobs and populate data to DB with information of layers and artifacts.

**Comment by dbenduga** [comment]
@reasonerjt .. Could you please share migration steps? I am using 1.8.1 and want to migrate to 1.9.

**Comment by petvaa01** [comment]
Leaving my experience here, just in case it's helps somebody.

We have around 20k tags with 1TB data using S3 as storage backend. Migration took about 1h in total. I had to start migration few times increasing initialDelaySeconds for core deployment livenessProbe (5m -> 15m -> 60m). Main bottleneck was probably network to S3 as CPU and memory usage wasn't too high and adding more didn't speed up the migration.
