### ISSUE TITLE
permissions.md need update for CVE whitelist, web hook and tag retention

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#8940]
What can we help you?

**Comment by reasonerjt** [comment]
This file should be updated:
https://github.com/goharbor/harbor/blob/master/docs/permissions.md

To reflect what roles can perform the actions against the resources mentioned in the title of the issue.

**Comment by renmaosheng** [comment]
weiwei, could you please submit a PR for this?

**Comment by xaleeks** [comment]
I’m working on this already.

Best,
alex

**Comment by xaleeks** [comment]
done here
https://github.com/goharbor/harbor/pull/9058

**Comment by xaleeks** [comment]
please merge pr and then close this @heww
