### ISSUE TITLE
First push into auto-scanning project results fails with "Cannot get the image severity"

### ISSUE THREAD

**Issue by funkypenguin** [goharbor/harbor#8958]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Attempting to push an image should either succeed, or fail because vulnerabilities are found

**Steps to reproduce the problem:**
Install harbor using helm chart. Configure a project with scan-on-push, and deny any pushes with a _high_ vulnerability. Build a docker image using the following Dockerfile:

```
FROM nginx:alpine
```

Attempt to push the image into the registry. Intermittently, the push will fail with

```
failed to extract image: PROJECT_POLICY_VIOLATION: "Cannot get the image severity."
```

Attempt a second time, and the push will succeed.

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.8.2
- docker engine version: Containerd runtime
- docker-compose version: Kubernetes 1.14.1

**Comment by reasonerjt** [comment]
@funkypenguin How do you deny **push** for vulnerable images?  Harbor only supports denying **pull**

**Comment by funkypenguin** [comment]
Aah, that'd explain it. I'm using ConcourseCI's registry image resource (https://github.com/concourse/registry-image-resource) into Harbor. I hadn't realized, but perhaps the resource pushes the image, and then immediately pulls it again (maybe to validate it). If it pulls it too fast for the scan to have completed, that'd explain the intermittent issue.
