### ISSUE TITLE
Replication job timestamp has wrong timezone

### ISSUE THREAD

**Issue by cd1989** [goharbor/harbor#8962]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

In Harbor v1.8.2, **when I set timezone to harbor core, for example Asia/shanghai**,

I will get replication jobs with wrong timestamp: creationTime and updateTime of jobs are 8 hours behind the execution creation time.

![image](https://user-images.githubusercontent.com/16573984/64338698-faf82300-d014-11e9-9449-d3dd248e54d0.png)

---

It's caused by using `*time.Time` instead of `time.Time` in `Task` model.

```
type Task struct {
	ID           int64     `orm:"pk;auto;column(id)" json:"id"`
	ExecutionID  int64     `orm:"column(execution_id)" json:"execution_id"`
	ResourceType string    `orm:"column(resource_type)" json:"resource_type"`
	SrcResource  string    `orm:"column(src_resource)" json:"src_resource"`
	DstResource  string    `orm:"column(dst_resource)" json:"dst_resource"`
	Operation    string    `orm:"column(operation)" json:"operation"`
	JobID        string    `orm:"column(job_id)" json:"job_id"`
	Status       string    `orm:"column(status)" json:"status"`
	StartTime    *time.Time `orm:"column(start_time)" json:"start_time"`
	EndTime      *time.Time `orm:"column(end_time)" json:"end_time,omitempty"`
}
```

As Beego ORM doesn't process `*time.Time`, https://github.com/astaxie/beego/blob/develop/orm/db.go#L180

```
case TypeTimeField, TypeDateField, TypeDateTimeField:
	value = field.Interface()
	if t, ok := value.(time.Time); ok {
		d.ins.TimeToDB(&t, tz)
		if t.IsZero() {
			value = nil
		} else {
			value = t
		}
	}
default:
  . . .
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ywk253100** [comment]
I think this is a common issue, not only for replication. Is there any fix that can workaround it in the framework level? Or all variables points to Time should be replaced by Time

**Comment by cd1989** [comment]
I found there is  no other ones. On the other hand, I have already make a PR to Beego, but it takes time for it to be merged.
