### ISSUE TITLE
Harbor core does not work with custom CA

### ISSUE THREAD

**Issue by rbkaspr** [goharbor/harbor#8964]
**Is your feature request related to a problem? Please describe.**
Currently, Harbor Core does not support any injection of custom certificate authorities (CAs) to verify TLS connections to systems using certificates signed by custom authorities. In general, the way to get around this issue is to turn off certificate verification, which is insecure. In addition, I've found that pull-base replication rules for Docker Hub seem to ignore the direction to not verify the server certificate (we have a corporate mirror signed with a custom CA), which I'll be reporting as a separate issue.

Based on this photon issue (https://github.com/vmware/photon/issues/592), it's possible in Photon to add custom authorities using the openssl c_rehash command. Unfortunately, the Harbor images do not ship with this package installed and cannot be installed in an offline environment. I also can't appear to add things to the target directory (/etc/ssl/certs) as the root user (permission denied).

**Describe the solution you'd like**
I propose the following changes:

1. Add the openssl c_rehash binary to the base images
2. Add a flag to the SSL configuration for Harbor to allow administrators to set a path for a custom CA cert or bundle
3. Add logic to the prepare and startup scripts to move the cert to an appropriate place on install, then mount and run c_rehash on startup.

**Describe the main design/architecture of your solution**
1. Add tdnf install -y openssl-c_rehash to the relevant Dockerfiles
2. Add a field to harbor.yml to support a custom CA (or else extend the one that's currently there for storage interactions for the registry and chart components to also apply to core)
3. Update the prepare and setup scripts/containers to stage the CA for core
4. Update the entrypoint for core to run rehash_ca_certificates.sh prior to starting the core binary (we can set an environment variable in the compose so we don't run this command if no custom CAs are provided).

**Describe the development plan you've considered**
This should require very few (if any) code changes, as most of the components affected are script or Dockerfile related.

**Comment by reasonerjt** [comment]
@rbkaspr I think those are different issues, 
1) There's no options for dockerhub replication skip cert verification.
2) There's no way to inject custom root cert so the process can trust it.
For 2) we do have a pattern to support such requirement in other containers, such as:
https://github.com/goharbor/harbor/blob/master/make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja#L82

**Comment by rbkaspr** [comment]
@reasonerjt 
I've opened an issue for 1 (#8965), and for number 2, if there's already a pattern for injecting custom CAs into some containers in Harbor, it should be available in all of them (or at least all those that potentially reach out to external services).

Any movement on this issue yet, by the way?

**Comment by konstruktoid** [comment]
Hi @rbkaspr,
I had the issue with `clair` not updating the database so I did the following.

Running Harbor in Docker on a Ubuntu 18.04, using internal certificates and MITM web proxy.

First update the `harbor/docker-compose.yml ` to include the host directories containing the certificates:

```
$ sudo diff -uNr docker-compose.yml.org harbor/docker-compose.yml 
--- docker-compose.yml.org	2020-01-21 15:33:39.244851105 +0100
+++ harbor/docker-compose.yml	2020-01-22 11:07:11.186240354 +0100
@@ -265,6 +265,15 @@
       - type: bind
         source: ./common/config/clair/config.yaml
         target: /etc/clair/config.yaml
+      - type: bind
+        source: /etc/ssl/certs/
+        target: /etc/ssl/certs/
+      - type: bind
+        source: /usr/share/ca-certificates/
+        target: /usr/share/ca-certificates/
+      - type: bind
+        source: /usr/local/share/ca-certificates/
+        target: /usr/local/share/ca-certificates/
     logging:
       driver: "syslog"
       options:
```

Then update `common/config/clair/clair_env` with any env variables you need, and restart Harbor.

```
$ sudo docker-compose down -v
$ sudo docker-compose up -d
```

Access the `clair` container, use `http` repositories to skip failing certificates and install `openssl-c_rehash`, then switch back to `https`.

```
$ sudo docker exec -ti clair /bin/bash
# sed -i 's/=https:/=http:/g' /etc/yum.repos.d/photon*
# tdnf -y update
# tdnf -y install openssl-c_rehash
# rehash_ca_certificates.sh
# sed -i 's/=http:/=https:/g' /etc/yum.repos.d/photon*
# tdnf -y update
# tdnf clean all
# exit
```

Monitor the logs:

```
$ sudo docker exec -ti harbor-log tail -f /var/log/docker/clair.log
```
