### ISSUE TITLE
Replicating images without verifying cert does not work for Docker Hub

### ISSUE THREAD

**Issue by rbkaspr** [goharbor/harbor#8965]
We have a corporate mirror of Docker Hub which presents a cert signed by a company CA. This is also the case for our LDAP infrastructure. Since Harbor doesn't currently support custom CAs (#8964), we typically turn off certificate validation (leaving the box unchecked).

When I try to replicate images from the Hub mirror to Harbor (to build a local cache), the replication always fails with "x509: certificate signed by unknown authority". I've double checked the registry settings in Harbor, certificate verification is checked for the server I'm pointing at, and the provider type is docker-hub. Leaving that box unchecked should behave consistently across all fields that use it.

**Comment by ywk253100** [comment]
This works as design. The certificate is verified when replicating with Docker Hub. You can try to use the `docker-registry` provider.

**Comment by reasonerjt** [comment]
I think this can be dupped to #8964

**Comment by rbkaspr** [comment]
The thing is, when you're setting up Docker Hub as a registry in the UI,
the check box for whether or not to verify the server certificate is still
present in the form, it just doesn't work like it does for everything else.

Either that check box needs to vanish when the type is set to Docker Hub,
or it needs to have the same effect it does everywhere else
