### ISSUE TITLE
Save button not working in Safari

### ISSUE THREAD

**Issue by davidcorbin** [goharbor/harbor#8968]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The save button for the add replication rule modal is not activating when it should. This could also be true for other modals.

**Steps to reproduce the problem:**
<img width="1676" alt="Screen Shot 2019-09-05 at 11 13 04 AM" src="https://user-images.githubusercontent.com/5752872/64355052-84d0cd80-cfce-11e9-8014-6e51b3123bca.png">

**Versions:**

- harbor version: 1.8.2
- docker engine version: 19.03.2
- docker-compose version: 1.24.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by zhoumeina** [comment]
@davidcorbin , yes. Harbor UI has this issue in 1.8. We have fixed it in 1.9. You can upgrade to 1.9 to solve this problem.
