### ISSUE TITLE
[HELM] labels not reflected after assigning to a helm chart version, we need to manualy refresh it

### ISSUE THREAD

**Issue by arsulesandy** [goharbor/harbor#8973]
After adding a lable to helm chart version, they are not automatically reflecting on the ui.

**Comment by reasonerjt** [comment]
@zhoumeina please help us triage this.

**Comment by arsulesandy** [comment]
labels are working for image tags. Also for helm charts this is a very minor issue

**Comment by jwangyangls** [comment]
After adding the tags to the helmet chart version, they are automatically reflected on the ui, but it takes about 0.5 seconds.
