### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by cuprumpea** [goharbor/harbor#8975]
Harbor1.8.1. If the project name is a number, push images can only be used through admin account;
How to solve？ thanks .

**Comment by reasonerjt** [comment]
@ywk253100  I believe this is fixed in `v1.8.2`? Could you confirm?

**Comment by ywk253100** [comment]
The fix is merged into 1.8 branch https://github.com/goharbor/harbor/pull/8922, and will be available in 1.8.3

**Comment by reasonerjt** [comment]
Thanks, I'm closing this one.

**Comment by cuprumpea** [comment]
thanks
