### ISSUE TITLE
1.8.2 using 1.9.0 configuration

### ISSUE THREAD

**Issue by A-SOM** [goharbor/harbor#8977]
Hello. I am download latest release habor and configure harbor.yml
But, my install fail.
- harbor version: [1.8.2]
- docker engine version: [19.03.2]
- docker-compose version: [1.24.1]

First launch:
'webhook_job_max_retry'
I am added it from 1.9 harbor.yml
Second launch:
KeyError: 'log_location'
I add, from 1.9 local and make tabs for config, how in configuration 1.9

third and latest, after how i fix it all:
[Step 2]: starting Harbor ...
Creating network "make_harbor" with the default driver
Pulling log (goharbor/harbor-log:v1.9.0-build.2119)...
ERROR: manifest for goharbor/harbor-log:v1.9.0-build.2119 not found: manifest unknown: manifest unknown

What i can make, for use your product?

**Comment by reasonerjt** [comment]
You should run migration to migrate `harbor.yml`:
https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md
