### ISSUE TITLE
LDAP connect fail

### ISSUE THREAD

**Issue by YeonSeoMom** [goharbor/harbor#8978]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
harbor connect ldap server(AD).

I can login with my ldap authentication.

**Steps to reproduce the problem:**

After I set the ldap info on web ui.

I got error.

I can ldapsearch with that info on shell.

I guess ldap(AD) connection timeout is too short.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.8.2]
- docker engine version: [18.09.7]
- docker-compose version: [1.18.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.

- /var/log/harbor/core.log shows 
Sep  6 17:43:38 192.168.96.1 core[21932]: 2019-09-06T08:43:38Z [ERROR] [/common/api/base.go:228]: LDAP connect fail, error: LDAP Result Code 200 "": dial tcp 10.40.29.172:389: i/o timeout
Sep  6 17:43:38 192.168.96.1 core[21932]: 2019-09-06T08:43:38Z [ERROR] [/common/api/base.go:68]: POST /api/ldap/ping failed with error: {"code":500,"message":"Internal Server Error"}

**Comment by reasonerjt** [comment]
Networking issue:
```
dial tcp 10.40.29.172:389: i/o timeout
```

**Comment by unbreakabl3** [comment]
Have the same issue on 1.8.4:
[ERROR] [/common/api/base.go:228]: LDAP connect fail, error: LDAP Result Code 200 "": dial tcp: i/o timeout

For sure there is no any network connectivity issue.
