### ISSUE TITLE
Migrate the legacy Clair scanner to the new framework 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#8998]
Final goal:

- Keep same experience with the previous one (--with-clair)
- Besides installing Clair (still only one db), an extra clair adapter should be also installed
- Considering the access entry point of the cliar adapter because it needs to pull content with harbor hostname path
- Automatically insert the installed Clair adapter entry point into the scanner list which is persisted in the DB

**Comment by reasonerjt** [comment]
We should leverage the existing `harbor-db` container serves as the DB of Clair.
We will not handle the migration of scan result of Clair, user may have to rescan all image to generate the scan report based on new data model.
