### ISSUE TITLE
[Immutable Tag] UI Implement for Immutable tag

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#8999]
Basically, it will be a new tag in the project view, like tag retention and rules management.

**Comment by xaleeks** [comment]
This is UI specifically for creating a immutable tag rule/policy?   @wy65701436 

fyi, @stuclem

**Comment by stuclem** [comment]
Created https://github.com/goharbor/harbor/issues/9572 to track the doc update, so removing `doc-impact` from this one.

**Comment by reasonerjt** [comment]
Closing as this is delivered in `master` branch.
