### ISSUE TITLE
Immutable Tag Story

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#9003]
What can we help you?

**Comment by reasonerjt** [comment]
Can we add a issue to extract the resource/artifact selector?

**Comment by wy65701436** [comment]
let's use https://github.com/goharbor/harbor/issues/8997 to track it.

**Comment by stuclem** [comment]
Created https://github.com/goharbor/harbor/issues/9572 to track the doc update, so removing `doc-impact` from this one.
