### ISSUE TITLE
Useless error message in browser console when creating project

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9009]
When creating project, typing name, there will be an ajax request periedly to check whether the name conflicted, however the error message is not caught carefully, this is not nice

![image](https://user-images.githubusercontent.com/188115/64499438-90343980-d2eb-11e9-9cf4-927eee8e0221.png)

**Comment by AllForNothing** [comment]
![image](https://user-images.githubusercontent.com/30999793/64577584-693f3b80-d3af-11e9-8edf-51196f76dfa6.png)
if project name is not existed , backend api return code 404.   Won't fix.
