### ISSUE TITLE
Replicating images from Harbor to GCR

### ISSUE THREAD

**Issue by Shriyut** [goharbor/harbor#9016]
I'm trying to send my Harbor images to my GCR registry for back up but I'm not able to configure this set-up. How do I provide my GCR's HTTPS endpoint, the google-gcr endpoint option only accepts gcr.io as endpoint url and not the project id. Also, I'm not sure about the JSON secret although I created a service account with container analysis admin role and endpoint admin role. How do I fix this?

**Comment by bitsf** [comment]
add project id in namespace
