### ISSUE TITLE
/api/users/current/permissions very slow when CPU high

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#9020]
When CPU usage is high in the machine of the core, API `/api/users/current/permissions` will be very slow.

Currently, `/api/users/current/permissions` will get all the permission policies of the project and check the policy one by one through the security context to compute permissions the user owned. 

Two db queries will request when check one policy in security context, and now there are 85 policies so at least 170 queries will request in this API.

Maybe an improved approach to fix this is that to use rbac pkg to check the policies directly rather than to use the security context which will reduce the number of the db queries to 2.

**Comment by reasonerjt** [comment]
@heww 
The api I issued was:
`GET /api/users/current/permissions?scope=/project/1&relative=true`

**Comment by iboonox** [comment]
Any update about this issue please ? same behavior even with a normal CPU usage.

**Comment by heww** [comment]
@iboonox Two PR will be created in version 1.10 and the problem will be alleviated.
