### ISSUE TITLE
Failed to replicate images

### ISSUE THREAD

**Issue by jiangsir-7765** [goharbor/harbor#9029]
What can we help you?
Expected behavior and actual behavior:
Expected: succeeded to replicate images
Actual: failed to replicate images

Steps to reproduce the problem:

create remote harbor
create replication rule and click trigger immediately
check logs
Versions:
Please specify the versions of following systems.

harbor version: [1.7.4]
docker engine version: [18.09.0]
docker-compose version: [1.23.1]
Additional context:
Backend Storage: Hitachi Content Platform
I can push images to the target Harbor manually successfully.

Log files:
root@i-nikvcsiy:/var/log/harbor# tail -n 100 job.log
Sep  6 10:23:43 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:23:43 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:23:43 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:23:43 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:23:43 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:23:43 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:24:13 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:24:13 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:24:13 10.***.***.34 job.core[827]: 2019/09/06 02:24:13 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   8.527302ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:24:13 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:24:13 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:24:13 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:24:13 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:24:13 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:24:13 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:24:43 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:24:43 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:24:43 10.***.***.34 job.core[827]: 2019/09/06 02:24:43 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.270044ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:24:43 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:24:43 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:24:43 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:24:43 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:24:43 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:24:43 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:25:13 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:25:13 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:25:13 10.***.***.34 job.core[827]: 2019/09/06 02:25:13 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.678213ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:25:13 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:25:13 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:25:13 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:25:13 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:25:14 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:25:14 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:25:43 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:25:43 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:25:43 10.***.***.34 job.core[827]: 2019/09/06 02:25:43 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.826051ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:25:43 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:25:43 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:25:44 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:25:44 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:25:44 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:25:44 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:26:13 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:26:13 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:26:13 10.***.***.34 job.core[827]: 2019/09/06 02:26:13 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.639815ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:26:13 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:26:13 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:26:14 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:26:14 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:26:14 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:26:14 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:26:43 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:26:43 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:26:43 10.***.***.34 job.core[827]: 2019/09/06 02:26:43 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.925126ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:26:44 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:26:44 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:26:44 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:26:44 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:26:44 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:26:44 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:27:14 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:27:14 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:27:14 10.***.***.34 job.core[827]: 2019/09/06 02:27:14 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.811146ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:27:14 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:27:14 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:27:14 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:27:14 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:27:14 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:27:14 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:27:44 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:27:44 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:27:44 10.***.***.34 job.core[827]: 2019/09/06 02:27:44 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   4.045447ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:27:44 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:27:44 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:27:44 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:27:44 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:27:44 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:27:44 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:28:14 10.***.***.34 job.core[827]: 2019/09/06 02:28:14 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.088708ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:28:14 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:28:14 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:28:14 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:28:14 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:28:14 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:28:14 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:28:15 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:28:15 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:28:44 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:28:44 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:28:44 10.***.***.34 job.core[827]: 2019/09/06 02:28:44 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.356817ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:28:44 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:28:44 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:28:45 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:28:45 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:28:45 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:28:45 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:29:14 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:29:14 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:29:14 10.***.***.34 job.core[827]: 2019/09/06 02:29:14 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   3.074247ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:29:15 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:29:15 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:29:15 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:29:15 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:29:15 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:29:15 +0000] "GET /api/health HTTP/1.1" 200 9
Sep  6 10:29:22 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:22Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"d688ee635********2f57e17", "hook_url":"http://core:8080/service/notifications/jobs/replication/17"}
Sep  6 10:29:22 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:22Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"eea38bbad********2d42310", "hook_url":"http://core:8080/service/notifications/jobs/replication/18"}
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [INFO] Job incoming: IMAGE_TRANSFER:eea38bbad********2d42310
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [INFO] Job incoming: IMAGE_TRANSFER:d688ee635********2f57e17
Sep  6 10:29:23 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:29:23 10.***.***.34 job.adminserver[827]: message repeated 2 times: [ 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /api/configs HTTP/1.1" 200 1797]
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   3.963035ms|   match|#033[44m GET     #033[0m /api/configs   r:/api/configs#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   4.547807ms|   match|#033[44m GET     #033[0m /api/configs   r:/api/configs#033[0m
Sep  6 10:29:23 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [INFO] initialization completed: repository: devops/verify, tags: [ large-test latest], source registry: URL-http://core:8080 insecure-false, destination registry: URL-https://harborbj.picclife.com insecure-false
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [INFO] initialization completed: repository: devops/alpine, tags: [ 3.9 latest], source registry: URL-http://core:8080 insecure-false, destination registry: URL-https://harborbj.picclife.com insecure-false
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   3.070464ms|   match|#033[44m GET     #033[0m /api/projects   r:/api/projects/#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|    5.75828ms|   match|#033[44m GET     #033[0m /api/projects   r:/api/projects/#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   4.026986ms|   match|#033[46m POST    #033[0m /service/notifications/jobs/replication/17   r:/service/notifications/jobs/replication/:id([0-9]+)#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   8.612699ms|   match|#033[46m POST    #033[0m /service/notifications/jobs/replication/18   r:/service/notifications/jobs/replication/:id([0-9]+)#033[0m
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [WARNING] the status code is 409 when creating project devops on destination registry, try to do next step
Sep  6 10:29:23 10.***.***.34 job.registry[827]: time="2019-09-06T02:29:23.73442233Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host="core:8080" http.request.id=b1dc7303-2d41-****-****-5cdac2e3f7b4 http.request.method=GET http.request.remoteaddr=172.***.***.6 http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=72d4b71f-9b6e-****-****-b66685ab302e service=registry version=v2.6.2
Sep  6 10:29:23 10.***.***.34 job.registry[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[43m 401 #033[0m|   3.587632ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [WARNING] the status code is 409 when creating project devops on destination registry, try to do next step
Sep  6 10:29:23 10.***.***.34 job.registry[827]: time="2019-09-06T02:29:23.752077595Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.3 http.request.host="core:8080" http.request.id=92266a0e-580d-****-****-4ccdf1819f48 http.request.method=GET http.request.remoteaddr=172.***.***.6 http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=72d4b71f-9b6e-****-****-b66685ab302e service=registry version=v2.6.2
Sep  6 10:29:23 10.***.***.34 job.registry[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[43m 401 #033[0m|   1.964824ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|  24.343588ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Sep  6 10:29:23 10.***.***.34 job.registry[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /v2/devops/alpine/manifests/ HTTP/1.1" 404 19 "" "harbor-registry-client"
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[43m 404 #033[0m|   1.039796ms|   match|#033[44m GET     #033[0m /v2/devops/alpine/manifests/   r:/v2/*#033[0m
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [ERROR] [transfer.go:86]: an error occurred while pulling manifest of devops/alpine: from source registry: 404 404 page not found
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [ERROR] [redis_job_wrapper.go:70]: Job 'IMAGE_TRANSFER:d688ee635********2f57e17' exit with error: 404 404 page not found
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]:
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   1.959569ms|   match|#033[46m POST    #033[0m /service/notifications/jobs/replication/17   r:/service/notifications/jobs/replication/:id([0-9]+)#033[0m
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|  22.875607ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Sep  6 10:29:23 10.***.***.34 job.registry[827]: 172.***.***.5 - - [06/Sep/2019:02:29:23 +0000] "GET /v2/devops/verify/manifests/ HTTP/1.1" 404 19 "" "harbor-registry-client"
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[43m 404 #033[0m|   1.365669ms|   match|#033[44m GET     #033[0m /v2/devops/verify/manifests/   r:/v2/*#033[0m
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [ERROR] [transfer.go:86]: an error occurred while pulling manifest of devops/verify: from source registry: 404 404 page not found
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]: 2019-09-06T02:29:23Z [ERROR] [redis_job_wrapper.go:70]: Job 'IMAGE_TRANSFER:eea38bbad********2d42310' exit with error: 404 404 page not found
Sep  6 10:29:23 10.***.***.34 job.jobservice[827]:
Sep  6 10:29:23 10.***.***.34 job.core[827]: 2019/09/06 02:29:23 #033[1;44m[D] [server.go:2619] |     172.***.***.6|#033[42m 200 #033[0m|   1.585365ms|   match|#033[46m POST    #033[0m /service/notifications/jobs/replication/18   r:/service/notifications/jobs/replication/:id([0-9]+)#033[0m
Sep  6 10:29:44 10.***.***.34 job.adminserver[827]: 172.***.***.5 - - [06/Sep/2019:02:29:44 +0000] "GET /api/configs HTTP/1.1" 200 1797
Sep  6 10:29:44 10.***.***.34 job.core[827]: 2019/09/06 02:29:44 #033[1;44m[D] [server.go:2619] |      127.0.0.1|#033[42m 200 #033[0m|   2.721492ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Sep  6 10:29:45 10.***.***.34 job.adminserver[827]: 127.0.0.1 - - [06/Sep/2019:02:29:45 +0000] "GET /api/ping HTTP/1.1" 200 6
Sep  6 10:29:45 10.***.***.34 job.registry[827]: 127.0.0.1 - - [06/Sep/2019:02:29:45 +0000] "GET / HTTP/1.1" 200 0 "" "curl/7.59.0"
Sep  6 10:29:45 10.***.***.34 job.registryctl[827]: 127.0.0.1 - - [06/Sep/2019:02:29:45 +0000] "GET /api/health HTTP/1.1" 200 9
root@i-nikvcsiy:/var/log/harbor#

![1](https://user-images.githubusercontent.com/55071435/64514637-9b07c200-d31d-11e9-9ea5-8aec9c5e4f71.png)
![2](https://user-images.githubusercontent.com/55071435/64514644-a0650c80-d31d-11e9-98dc-a78760e9bf7b.png)
![3](https://user-images.githubusercontent.com/55071435/64514655-a4912a00-d31d-11e9-92a3-bce4bb859c73.png)
![4](https://user-images.githubusercontent.com/55071435/64514672-a9ee7480-d31d-11e9-9d7d-39d6992cd7d5.png)
![5](https://user-images.githubusercontent.com/55071435/64514690-b2df4600-d31d-11e9-9a87-907227e94ae1.png)

**Comment by ywk253100** [comment]
According to the log 
```
Sep 6 10:29:23 10...34 job.jobservice[827]: 2019-09-06T02:29:23Z [INFO] initialization completed: repository: devops/verify, tags: [ large-test latest], source registry: URL-http://core:8080 insecure-false, destination registry: URL-https://harborbj.picclife.com insecure-false
```
Seems the first element in the tag list `tags: [ large-test latest]` is null, but I'm not sure why this happened. Could you show me all the tags of repository `devops/verify`?

**Comment by jiangsir-7765** [comment]
![微信图片_20190911112628](https://user-images.githubusercontent.com/55071435/64670540-11303400-d498-11e9-8a1f-e6f2e7ef33ea.png)

**Comment by klj890** [comment]
Hi，is there a conclusion to this question?
