### ISSUE TITLE
_uploads folder too big

### ISSUE THREAD

**Issue by Belyenochi** [goharbor/harbor#9030]
What can we help you?
I am trying back up a image, and I find a _uploads folder had thousands of layer, I don't know what happened and I want to know when to write in _uploads folder and when to delete.(harbor version 0.4.0)

**Comment by wy65701436** [comment]
hi @Belyenochi can you please upgrade to the latest version. and the`_upload` deletion, just refer to the document of the registry, you can config it in the registry.yml.
