### ISSUE TITLE
Project name with `api` at the begining creates 500 HTTP responses upon search API requests

### ISSUE THREAD

**Issue by fivezerosix** [goharbor/harbor#9034]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Through the UI we get a message saying that internal server errors have occurred when searching for `api` after creating a project starting with `api` in the name. Anything matching that project name will get us the same result. The chrome console returns a 500 error and bunch of weird characters. see attached the core logs:

Expected
Any project matching `api` at the begining should be added successfully without affecting the platform. 

**Steps to reproduce the problem:**
- Create a project with name `api-something` (this step can return the error right away) 
- Search for the project 
- Should receive the 500 HTTP errror. 

**Versions:**
Please specify the versions of following systems.

- Harbor version: 1.8.0
- Harbor helm:  1.1.0

**Additional context:**
Core Logs
```
2019-09-06T21:18:15Z [ERROR] [/core/api/project.go:440]: Failed to get total of charts under project api : http error: code 404, message not found
9/6/2019 3:18:15 PM 2019-09-06T21:18:15Z [ERROR] [/common/api/base.go:229]:
9/6/2019 3:18:15 PM 2019-09-06T21:18:15Z [ERROR] [/common/api/base.go:69]: GET /api/projects?page=1&page_size=15&name=api failed with error: {"code":500,"message":"Internal Server Error"}
9/6/2019 3:18:15 PM 2019/09/06 21:18:15 [D] [server.go:2619] | 10.3.58.228| 500 | 115.069656ms| match| GET /api/projects r:/api/projects/   
```

** Temporal Fix **
We are still investigating what the root cause is. Our fix was to log in to the Core DB and find the project ID of the project causing the issue.
Then we would send the DELETE api request for that id. We saw this same behavior in 3 different Harbor instances all occurring after adding the `api...` project.

Hope this helps and hopefully someone can take look.

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/6596
