### ISSUE TITLE
A never fail push action can be supported based on quota, tag retention and GC

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9037]
**Is your feature request related to a problem? Please describe.**

When the quota is full, the user can not push images to Harbor. It will influence the productivity of the developers.

**Describe the solution you'd like**

If the `never fail` is activated, when the user pushing images to Harbor and the quota is full, the pre-defined tag retention rules can be triggered and may be followed by a GC action to free the space and make sure the push operation will not fail.

**Describe the main design/architecture of your solution**

The quota full can be sent out as a signal and trigger the pre-defined tag retention rules.

**Describe the development plan you've considered**

n/a

**Additional context**

Proposed by Brad M

**Comment by xaleeks** [comment]
My concern with this is that any guest or developer can push which can trigger GC and retention, but the retention feature is only exposed to project admin and GC is only exposed to system admin.  He is essentially elevating his privileges using this. Also what retention policy is triggered by this exactly?  And there is no concept of a partial GC, as in restricted to his namespace.  So he can essentially kick off a GC whenever he wants?

**Comment by steven-zou** [comment]
Agree. This is a very heavy action.
