### ISSUE TITLE
harbor-adminserver is always restart

### ISSUE THREAD

**Issue by danielye77** [goharbor/harbor#9040]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
3e4a51317256        goharbor/harbor-adminserver:v1.6.3       "/harbor/start.sh"       11 minutes ago      Restarting (1) 23 seconds ago                                                                         harbor-adminserver

**Steps to reproduce the problem:**
upgrade from 1.4.0 to 1.6.3
then docker-compose up

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.6.3
- docker engine version:  17.03.3-ce
- docker-compose version: 1.7.1

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] initializing system configurations...
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] Upgrading schema for pgsql ...
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] No change in schema, skip.
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] Register database completed
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [INFO] the path of key used by key provider: /etc/adminserver/key
Sep 10 16:31:01 172.18.0.1 adminserver[886]: 2019-09-10T08:31:01Z [FATAL] [main.go:46]: failed to initialize the system: pq: null value in column "id" violates not-null constraint
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] initializing system configurations...
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] Upgrading schema for pgsql ...
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] No change in schema, skip.
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] Register database completed
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] the path of json configuration storage: /etc/adminserver/config/config.json
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [INFO] the path of key used by key provider: /etc/adminserver/key
Sep 10 16:32:44 172.18.0.1 adminserver[886]: 2019-09-10T08:32:44Z [FATAL] [main.go:46]: failed to initialize the system: pq: null value in column "id" violates not-null constraint

**Comment by bitsf** [comment]
@danielye77 I think you should upgrade from 1.4.x to 1.5.x first. That version is changing database from mysql to postgres.

**Comment by danielye77** [comment]
it's realy mistake of database.I fix it manual then harbor OK

**Comment by liy516** [comment]
> it's realy mistake of database.I fix it manual then harbor OK

how did you fix it manually? thanks

**Comment by FirstEncounter** [comment]
Hello, i meet the same problem. Could you tell me how to fix it?

**Comment by timgriffiths** [comment]
This looks very similar to https://github.com/goharbor/harbor/issues/10641 ... with equally useful closures
