### ISSUE TITLE
Suggestion: Mount existing docker registry

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9049]
**Is your feature request related to a problem? Please describe.**
Sometime we may already has a docker native registry or other registry with lot of data. We may want to use harbor instead. But import or replicate images may be a big cost. How about we reuse it.

**Describe the solution you'd like**
We can analyse the data in the existing registry, and directly import to the harbor.

**Describe the main design/architecture of your solution**
Use registry v2 api to list all images in the registry, save it as data.yml. Stop origin registry. Configure harbor installer to use origin registry backend and install harbor. Import data, we can write database directly, or enhance harbor api that can use v2 api to import and bypass the storage backend.

**Describe the development plan you've considered**

**Additional context**

**Comment by reasonerjt** [comment]
I think it's do-able now, with some environment, so Harbor will try to sync the registry data to DB. 
But this is not really appropriate to be exposed as a feature, then we'll need more considerations like storage settings of the registry, and some pre-req like the Harbor has to be empty etc etc..

**Comment by bcg62** [comment]
+1 for this. I have a very large existing docker registry which i’d like to migrate to harbor.

if there’s no way to do this it’s not feasible to use it

**Comment by zhipengzuo** [comment]
+1.actually we need it. But we need to have a whole view of the configuration and the situation.

**Comment by bitsf** [comment]
@xaleeks please consider whether we need such feature.

**Comment by bitsf** [comment]
there's already an environment "SYNC_REGISTRY", that can make harbor sync from backend registry.
but current behavior is odd, user need to create project first
