### ISSUE TITLE
Log getting cluttered with warning messages

### ISSUE THREAD

**Issue by radu-stefanache** [goharbor/harbor#9061]
I'm running Harbor `v1.8.2` on Kubernetes and I get roughly 1000+ warning messages/hour related to the default registry healthcheck.

The warning that keeps popping up:
`level=warning msg="error authorizing context: authorization token required"`

The chain of events:
1. Healthcheck triggered on the core service (`/api/ping`)
2. The core service then healthchecks the registry on [/v2](https://github.com/goharbor/harbor/blob/v1.8.2/src/core/api/health.go#L215)
3. Because the registry has authentication enabled (obviously) the warning message will be written to the logs

I understand that `/v2` is the way to healtcheck the registry but this was developed with the idea in mind that the registry will not have authentication enabled.

Would it make sense to change the healthcheck target to `/` or have any suggestions ?

Thank you

**Comment by wy65701436** [comment]
@ywk253100 could you please have a look?

**Comment by ywk253100** [comment]
This has already been fixed by https://github.com/goharbor/harbor/pull/8154
