### ISSUE TITLE
Removal of job service certificates from repo

### ISSUE THREAD

**Issue by SDBrett** [goharbor/harbor#9072]
The `jobservice` contains 3 certificate files, possibly generated by `generateCerts.sh` during a test / build process.

Are these certificate files required within the repo or can we clean up the directory by removing the files?

**Comment by wy65701436** [comment]
@SDBrett can you point me what cert files do you mean?

**Comment by SDBrett** [comment]
The files in question are:
src/jobservice/server.crt
src/jobservice/server.key
src/jobservice/ca.crt
