### ISSUE TITLE
Tag retention's operate privilege defined but never used

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9074]
Defined in 
https://github.com/goharbor/harbor/blob/master/src/common/rbac/project/visitor_role.go#L69

Expected to use

https://github.com/goharbor/harbor/blob/master/src/core/api/retention.go#L307

And the ActionDelete is defined but never used.
```
{Resource: rbac.ResourceImmutableTag, Action: rbac.ActionDelete}
```

**Comment by bitsf** [comment]
OperateRetentionExec permission is same as TriggerRetentionExec, they both update the retention status.
We don't support delete action for a retention job now, so it is just defined but not used.
ResourceImmutableTag rbac is not used by tag retention
