### ISSUE TITLE
Epic: CII badging remaining to-do tasks

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9076]
> This is an `epic` tracking all remaining tasks required for attaining cii badging

detailed list of requirements and motivation as well as  current lvl of fulfillment by Harbor latest version are listed here:
https://docs.google.com/spreadsheets/d/1pS2kJMQVuHVN-xfla8Ogex9CqrAKDNo5xLco5ebgaLg/edit#gid=1728595366

**Comment by reasonerjt** [comment]
No task remains.  Closing.
