### ISSUE TITLE
Task: CII badging req - subscribe to CVE alerts

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9077]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The release notes MUST identify every publicly known vulnerability with a CVE assignment or similar that is fixed in each new release, unless users typically cannot practically update the software themselves. If there are no release notes or there have been no publicly known vulnerabilities, choose "not applicable" (N/A).

Sol: Add appcheck(or something similar) for Harbor to get alerts about CVEs for all components that Harbor currently leverages.

**Comment by reasonerjt** [comment]
Considering Harbor packages software packages installed in photon OS.

Can we narrow down what software packages to which we should subscribe CVE?

**Comment by xaleeks** [comment]
This is now met, we will disclose publicly known vulnerabilities in release notes and Harbor team will create a CVSS using CVSS Calculator (https://www.first.org/cvss/calculator/3.0) for each vulnerability discovered.

**Comment by reasonerjt** [comment]
I don't think the comment in 
https://github.com/goharbor/harbor/issues/9077#issuecomment-532144987
is fully addressed/clarified by the disclosure process.

**Comment by xaleeks** [comment]
> I don't think the comment in
> [#9077 (comment)](https://github.com/goharbor/harbor/issues/9077#issuecomment-532144987)
> is fully addressed/clarified by the disclosure process.

I think your comment is more applicable to https://github.com/goharbor/harbor/issues/9087.  This issue is about identifying Harbor's CVEs in Harbor's release notes.  The original issue description included something about appcheck to monitor CVEs of external dependencies, that was my bad.
