### ISSUE TITLE
Task: CII badging req - default keylengths min requirements

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9078]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The security mechanisms within the software produced by the project MUST use default keylengths that at least meet the NIST minimum requirements through the year 2030 (as stated in 2012). It MUST be possible to configure the software so that smaller keylengths are completely disabled

**Comment by reasonerjt** [comment]
I'll double check what's the requirement and update in this issue.

**Comment by reasonerjt** [comment]
In the case of symmetric encryption our key length is 128 bit and is not configurable.
so I believe this is met.  Resolving.

**Comment by xaleeks** [comment]
Thanks Daniel, marking as met
