### ISSUE TITLE
Task: CII badging req - security and assurance documentation

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9079]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The project MUST document what the user can and cannot expect in terms of security from the software produced by the project. The project MUST identify the security requirements that the software is intended to meet and an assurance case that justifies why these requirements are met. The assurance case MUST include: a description of the threat model, clear identification of trust boundaries, and evidence that common security weaknesses have been countered.

**Comment by reasonerjt** [comment]
Is there a sample for such document?

**Comment by xaleeks** [comment]
this has been added to https://github.com/goharbor/harbor/security/policy
