### ISSUE TITLE
Task: CII badging req - coding style documentation

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9080]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The project MUST identify the specific coding style guides for the primary languages it uses, and require that contributions generally comply with it.

**Comment by reasonerjt** [comment]
We have enforced the coding style check by integrating `golint` in the CI.
I assume we met the req?

**Comment by xaleeks** [comment]
> We have enforced the coding style check by integrating `golint` in the CI.
> I assume we met the req?

I think that qualifies

**Comment by xaleeks** [comment]
@wy65701436 Wang yan, please explicitly state that we are enforcing standards set by golint and link the coding guidelines on the repo doc.
