### ISSUE TITLE
Task: CII badging req - makefile for native binaries

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9081]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: Build systems for native binaries MUST honor the relevant compiler and linker (environment) variables passed in to them (e.g., CC, CFLAGS, CXX, CXXFLAGS, and LDFLAGS) and pass them to compiler and linker invocations. A build system MAY extend them with additional flags; it MUST NOT simply replace provided values with its own. [build_standard_variables]

**Comment by wy65701436** [comment]
PR: https://github.com/goharbor/harbor/pull/9649

**Comment by wy65701436** [comment]
close as PR is merged.
