### ISSUE TITLE
Task: CII badging req - preserve debugging information if requested in flags

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9082]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The build and installation system SHOULD preserve debugging information if they are requested in the relevant flags (e.g., "install -s" is not used). If there is no build or installation system (e.g., typical JavaScript libraries), this is N/A. [

**Comment by reasonerjt** [comment]
seems a dup to #9081

**Comment by xaleeks** [comment]
this is a SHOULD and not a MUST requirement for badging

**Comment by xaleeks** [comment]
how much effort would this take? @wy65701436

**Comment by wy65701436** [comment]
won't fix.
