### ISSUE TITLE
Task: CII badging req - build consistency across source code

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9083]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req:  The project MUST be able to repeat the process of generating information from source files and get exactly the same bit-for-bit result. If no building occurs (e.g., scripting languages where the source code is used directly instead of being compiled), select "N/A".

current issue: Source code -> executable file is reproducible, however in the packaging phase we pull packages from bintray to install software in the photon image, and this phase is not completely reproducible because the tool `tdnf` will pull latest package.  I don't know if this is enough, need to find out

**Comment by reasonerjt** [comment]
We can pull the certain version of bintray repo to a mirror env and pin to that version before releasing

**Comment by wy65701436** [comment]
PR: https://github.com/goharbor/harbor/pull/9761

**Comment by wy65701436** [comment]
close it as PR merged.

**Comment by wy65701436** [comment]
PR to fix this issue is: https://github.com/goharbor/harbor/pull/9828
