### ISSUE TITLE
Task: CII badging req - standard convention for location of build artifacts

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9084]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The installation system for end-users MUST honor standard conventions for selecting the location where built artifacts are written to at installation time. For example, if it installs files on a POSIX system it MUST honor the DESTDIR environment variable. If there is no installation system or no standard convention, select "N/A".

**Comment by reasonerjt** [comment]
Considering we build docker image, we may not follow this rule?
@wy65701436 let's check what other projects do.  I highly suspect this is not applicable to us.

**Comment by xaleeks** [comment]
we ship docker images so just follow docker conventions for building

**Comment by xaleeks** [comment]
@wy65701436 Wang yan, please add what we discussed to the docs and close this out.

**Comment by wy65701436** [comment]
As we ship docker images, and leverage the docker to handle the images. The user does not need to specify the installation path, only needs to care about the configuration file, it's required for the 
 data migration. So, I believe that we can select "N/A".
