### ISSUE TITLE
Task: CII badging req - verify inputs from untrusted sources

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9085]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req: The project results MUST check all inputs from potentially untrusted sources to ensure they are valid (a whitelist), and reject invalid inputs, if there are any restrictions on the data at all.

**Comment by reasonerjt** [comment]
If the inputs means parameters input by user we are checking them.
@xaleeks please clarify.

**Comment by xaleeks** [comment]
can think of docker login, web console login, cve whitelist, 
docker push etc.  all these qualify as 'input‘

**Comment by reasonerjt** [comment]
What's the status?

**Comment by xaleeks** [comment]
This is satisfied
