### ISSUE TITLE
Task: CII badging req - sign all releases with crypto signature

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9086]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req:  The project MUST cryptographically sign releases of the project results intended for widespread use, and there MUST be a documented process explaining to users how they can obtain the public signing keys and verify the signature(s). The private key for these signature(s) MUST NOT be on site(s) used to directly distribute the software to the public.

issue: we currently don't sign releases

**Comment by reasonerjt** [comment]
I don't see other projects in CNCF signing the release, additionally we ship docker images, there's no conventionally service/tool for signing the images.

This may depend on CNCF

**Comment by xaleeks** [comment]
I'm checking with CNCF on this

**Comment by xaleeks** [comment]
Per discussion, we will sign all future releases and include key for verification as part of our github release.  Please briefly document pgp client tools used and any other requirements here and we will add it to docs.  You can include something about how we prevent data from being comprised but nothing about generation of private key on server side is needed @bitsf @reasonerjt 

@stuclem FYI

**Comment by stuclem** [comment]
Created https://github.com/goharbor/harbor/issues/9568 to track the doc update, so removing `doc-impact` from this one.

**Comment by xaleeks** [comment]
build signing has been added thru https://github.com/goharbor/harbor/pull/9551
