### ISSUE TITLE
Custom images for Portal look & feel loaded from wrong directory

### ISSUE THREAD

**Issue by embik** [goharbor/harbor#9090]
**Expected behavior and actual behavior:**
If you modify `src/portal/src/setting.json` (following [the look & feel doc](https://github.com/goharbor/harbor/blob/master/docs/customize_look%26feel_guide.md)) and add custom images to the folder `src/portal/src/images` (as advised in the document), building a custom portal image will result in the web interface being broken because the custom images are loaded from `/static/images/<Image Name>` instead of `/images/` (where the `src/portal/src/images` folder is located in the final image).

**Steps to reproduce the problem:**
- Customize the portal via `setting.json` by adding a custom image to the `images` folder and referencing it in the config file.
- Rebuild the portal image.
- Open it in a browser => custom background and logo images will be broken.
- Bonus: Replace `/static/images` with `/images` (e.g. with browser dev tools) and see that the images have been indeed included in the custom container image.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.0-rc2
- docker engine version: 17.12.1-ce
- docker-compose version: -

**Additional context:**

- Seems to be related to these two lines:
    - https://github.com/goharbor/harbor/blob/v1.9.0-rc2/src/portal/src/app/sign-in/sign-in.component.html#L5
    - https://github.com/goharbor/harbor/blob/v1.9.0-rc2/src/portal/src/app/base/navigator/navigator.component.html#L6

**Comment by wy65701436** [comment]
hi @ninjadq and @zhoumeina , can you help?

**Comment by jwangyangls** [comment]
it has fixed it in #9332
