### ISSUE TITLE
LDAP authentication failed (invalid characters)

### ISSUE THREAD

**Issue by lukwgnd** [goharbor/harbor#9092]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I can not log into Harbor using LDAP as a provider. I receive the error message "Invalid user name or password". The same LDAP configuration works with Harbor 1.8.

**Steps to reproduce the problem:**

- update / install harbor 1.9.0rc2 and configure ldap authentication.
- try to log-in with ad-credentials

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.0rc2
- docker engine version: 19.03.1
- docker-compose version: 1.24.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
```
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
[WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
[ERROR] [/core/controllers/base.go:107]: Error occurred in UserLogin: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
```

**Comment by wy65701436** [comment]
hi @lukwgnd, is it fresh install or upgrade from the previous harbor?

**Comment by lukwgnd** [comment]
Hey @wy65701436 , I tried both. Can I help with more information?

**Comment by stonezdj** [comment]
Is there any special character in the username? such as space or ` * ( ) \`

**Comment by lukwgnd** [comment]
@stonezdj: no special character in the username. 

LDAP Filter: empty
LDAP Group Filter: objectClass=group

This works in harbor 1.8.2.

**Comment by lukwgnd** [comment]
Similar / same problem as in https://github.com/goharbor/harbor/issues/9110

**Comment by stonezdj** [comment]
The #9110 ldap return code is 12, and in your case is 201, 
Could you please update the common/config/core/env 
LOG_LEVEL=debug
and restart harbor
and retry login with ldap user, and upload the detail trace log?

**Comment by Szauka** [comment]
Hi @stonezdj 

I also see the same issue.

key  | Value
---- | ------
LDAP Filter | "objectClass=*" or "blank"
LDAP Group Filter | objectclass=group

Harbor
Version v1.9.0-d13cf448

This are the logs:
```
[DEBUG] [/common/utils/ldap/ldap.go:224]: Searching for nested groups
[DEBUG] [/common/utils/ldap/ldap.go:299]: Membership attribute: memberof
[DEBUG] [/common/utils/ldap/ldap.go:315]: Search ldap with filter:(&(objectClass=group)(member:1.2.840.113556.1.4.1941:=CN=Surname\, Name,OU=TEST Test,DC=local,DC=test,DC=com))
[DEBUG] [/common/utils/ldap/ldap.go:332]: No entries
[DEBUG] [/common/utils/ldap/ldap.go:336]: LDAP search errorLDAP Result Code 201 "": ldap: invalid characters for escape in filter
[WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
[ERROR] [/core/controllers/base.go:107]: Error occurred in UserLogin: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
[DEBUG] [/core/filter/security.go:227]: OIDC CLI modifier only handles request by docker CLI or helm CLI
[DEBUG] [/core/filter/security.go:442]: can not get user information from session
[DEBUG] [/core/filter/security.go:511]: user information is nil
[DEBUG] [/core/filter/security.go:525]: using local database project manager
[DEBUG] [/core/filter/security.go:527]: creating local database security context...
```

Do you have any idea what could be the issue?

**Comment by drleq** [comment]
This could be an issue with the \ character not being properly escaped.  See https://stackoverflow.com/questions/39794550/how-should-i-escape-commas-in-active-directory-filters for details.

**Comment by dgabrysch** [comment]
Hi,

is there a possibility to workaround this bug?

**Comment by Szauka** [comment]
@dgabrysch we ended up having to downgrade to v1.8.

**Comment by dgabrysch** [comment]
@Szauka - thank you for your answer, we downgraded too :)

**Comment by Madic-** [comment]
We're having the same problem.

| key | value |
| --- | --- |
| LDAP Filter | (&(objectclass=user)(mail=*)(givenName=*)(sn=*)(!(userAccountControl=514))) |

> [WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
> [ERROR] [/core/controllers/base.go:110]: Error occurred in UserLogin: LDAP Result Code 201 "": ldap: invalid characters for escape in filter

**Comment by lz006** [comment]
same issue here when pw contains a **!**
....
``` bash
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_filter, error: the configure value is not set
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_base_dn, error: the configure value is not set
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_search_filter, error: the configure value is not set
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_attribute_name, error: the configure value is not set
[ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_admin_dn, error: the configure value is not set
[WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: LDAP Result Code 201 "": ldap: invalid characters for escape in filter
[ERROR] [/core/controllers/base.go:110]: Error occurred in UserLogin: LDAP Result Code 201 "": ldap: invalid characters for escape in filter


```
