### ISSUE TITLE
Error on Harbor as Docker Hub proxy when "Prevent Vulnerable Images" is enabled

### ISSUE THREAD

**Issue by brunoaraujoclaro** [goharbor/harbor#9094]
I am using Harbor as Docker Hub Proxy, where the docker daemon was configure to point for this registry. This part is working ok.

But, I find a problem when I enable the option "Prevent Vulnerable Images" following the image below to the "library" project.

![Harbor dashboard](https://i.ibb.co/fDZKWN1/harbor.png)

If this options is checked, the docker pull command don't work, showing the error below, but if is unchecked, the command work ok.

![Harbor error](https://i.ibb.co/D9cMCXQ/error.png)

- harbor version: v1.8.2 (online)
- docker engine version: 18.06.1-ce
- docker-compose version: 1.24.1

**Comment by wy65701436** [comment]
@brunoaraujoclaro can you please provide core.log?

**Comment by ywk253100** [comment]
@steven-zou This isn't related with replication, I removed the `replication` label

@brunoaraujoclaro I don't think Harbor fully support the registry proxy/mirror already, you can refer to https://github.com/goharbor/harbor/issues/8082 for more information

**Comment by reasonerjt** [comment]
That;s correct, currrently you cannot setup harbor as proxy cache of docker hub and expect the functionalities work as when it's setup as a standalone registry.

closing as won't fix.
