### ISSUE TITLE
support TLS for internal communication between harbor pods

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#9095]
As a general security practice, it is recommended to have TLS enabled on all HTTP communication. Currently the communication between harbor pods are on plain HTTP, this would make it vulnerable for network traffic sniffing if the communication goes across nodes in certain environment. It'll be greatly helpful if Harbor can provide a config that can enable TLS for internal communication among Harbor pods for Harbor running in a k8s cluster.

**Comment by reasonerjt** [comment]
depends on #9054

**Comment by xaleeks** [comment]
@ninjadq This is completed correct? can you link merged PR here?

**Comment by ninjadq** [comment]
it's done in this PR https://github.com/goharbor/harbor/pull/10706

**Comment by ywk253100** [comment]
Done
