### ISSUE TITLE
docker push return 400

### ISSUE THREAD

**Issue by tiger-regit** [goharbor/harbor#9098]
docker image push return 400

**Steps to reproduce the problem:**
![image](https://user-images.githubusercontent.com/6560524/64925680-f3135c80-d826-11e9-856e-bd72536d0e64.png)

I push image host docker info:

![image](https://user-images.githubusercontent.com/6560524/64925724-a419f700-d827-11e9-97dd-a37884d4754c.png)

I use the http proxy, is this related?

**Versions:**
- harbor version: 1.8.2
- docker engine version: 19.03.2
- docker-compose version: [1.24.1]

- **Log files:** You can get them by package the `/var/log/harbor/` .
![image](https://user-images.githubusercontent.com/6560524/64925690-3077ea00-d827-11e9-97e3-b350d4108967.png)

**Comment by ywk253100** [comment]
@tiger-regit I'm not sure whether it is related. Could you remove the proxy settings and try again? If you get the 400 error again, you can set the log level of docker client to debug and check the logs

**Comment by tiger-regit** [comment]
@ywk253100 
Sorry, because the target machine has a whitelist limit, if I don't use a specific IP access, I can't access it.
I suspect the basis of this problem is because I also used the same version of the harbor on another machine, but did not use the proxy to push. Everything is normal.
