### ISSUE TITLE
password cryptoperiod  for robot account

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#9100]
as  we know windows local password cryptoperiod is 90 days, when i promote robot account of harbor in our organization, many users ask me to add password cryptoperiod for robot account,  could you add this feature ?

**Comment by ywk253100** [comment]
I think this is already implemented: https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#robot-account.
Feel free to reopen it if it doesn't.
