### ISSUE TITLE
Correct documented configuration file

### ISSUE THREAD

**Issue by delanym** [goharbor/harbor#9102]
The installation instructions talk about a **harbor.yml** file
https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md

while the file harbor-offline-installer-v1.7.0-rc1.tgz
contains a **harbor.cfg** file.

**Comment by ywk253100** [comment]
The documents on master branch is the latest version. Switch to 1.7 branch for the specified version: https://github.com/goharbor/harbor/blob/release-1.7.0/docs/installation_guide.md
