### ISSUE TITLE
Enhance the robot account to support extra scope with an unified interface

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9103]
provide a general pluggable decoded handler framework to decode the given token and pass it through the HTTP request for next stage

**Comment by steven-zou** [comment]
As we decided to use a robot account to pull content and bypass the policy, @wy65701436 can help to do enhancements to the robot account.

**Comment by wy65701436** [comment]
PR: https://github.com/goharbor/harbor/pull/9506
