### ISSUE TITLE
OIDC group support for auth0

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9112]
OIDC group support needs to be verified for auth0, just like we've done for dex and keycloak.

requirement explained in detail here:
https://github.com/goharbor/harbor/issues/8017

**Comment by xaleeks** [comment]
tracking this here so we don't forget @reasonerjt

**Comment by reasonerjt** [comment]
Verified against auth0, getting group list into id token is trick on auth0 side.  Once the group list is added to the ID token things work.

Opened this issue on UI:
https://github.com/goharbor/harbor/issues/9380
