### ISSUE TITLE
Remove  images issue in harbor 1.8.1

### ISSUE THREAD

**Issue by cuprumpea** [goharbor/harbor#9121]
After deleting the images, the display is successful, but the tag of the images does not disappear, only the size shows 0B. 
What's the problem? how to resolve ?

**Comment by ywk253100** [comment]
What does the `mirror` mean? Is it just an image? Can you provide the stops to reproduce the issue? Can you reproduce it always?

**Comment by cuprumpea** [comment]
![3YGJMMVFP~WFEV3OM2(RD W](https://user-images.githubusercontent.com/37996644/65297501-a9b26c80-db9a-11e9-8fc2-a7317ee0bd7e.png)

**Comment by cuprumpea** [comment]
thanks ,it resolve .

**Comment by zhaowencheng1991** [comment]
@cuprumpea   how to resolve this issue ?  thanks

**Comment by gunboe** [comment]
I've discovered this issue a long time ago, I think is a registry problem. You can remove the specifc tags directory manualy or simply docker push any image with the same name and tag (overwrite that one), and then remove it again.
