### ISSUE TITLE
How to migrate the Redhat quay registry to Harbor registry

### ISSUE THREAD

**Issue by cmpmohan** [goharbor/harbor#9138]
What can we help you?
Currently we are using redhat quay registry to store our container images. its storing data on S3 bucket and related metadata on postgresql database. can any one share documents to migrate the data's from quay registry to harbor

**Comment by wy65701436** [comment]
The quay adapter for replication is still under development. So far, I think you can write a script to call harbor API to create project & push images.

**Comment by cmpmohan** [comment]
Is there any database schema compatibility between  quay registry and harbor?

**Comment by steven-zou** [comment]
@cmpmohan 

Check https://github.com/goharbor/harbor/pull/8556

Please stay tuned on the new release.

**Comment by steven-zou** [comment]
I think this issue can be safely closed.
