### ISSUE TITLE
The sql to add column `password_version` breaks migration

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9140]
Currently it's in `0010_1.9.0_schema.up.sql`.  This will not be executed when user upgrades from `1.9.0` and will break the login for existing users.

Let's move it to `0011_add_password_version.sql`  

And cherrypick it to branch `1.9.x`

**Comment by renmaosheng** [comment]
@ninjadq could you please share the estimation when can we fix this? thanks.

**Comment by ninjadq** [comment]
fixed  of https://github.com/goharbor/harbor/pull/9248
