### ISSUE TITLE
systeminfo API may show less info when it's triggered by anonymous(unauthenticated) user

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9149]
The example of response of GET /api/systeminfo
```
{
  "with_notary": false,
  "with_clair": false,
  "with_admiral": false,
  "admiral_endpoint": "",
  "auth_mode": "oidc_auth",
  "registry_url": "jt-dev.local.goharbor.io",
  "external_url": "https://jt-dev.local.goharbor.io",
  "project_creation_restriction": "everyone",
  "self_registration": false,
  "has_ca_root": false,
  "harbor_version": "v1.9.0-6dd2ae90",
  "registry_storage_provider_name": "filesystem",
  "read_only": false,
  "with_chartmuseum": false,
}
```

some of the data, such as `registry_storage_provider_name` `project_creation_restriction` is not necessary to be included when the requester is not authenticated.

So from security's perspective, we may consider return extra data only when user is authenitcated or have proper permission.

**Comment by paulczar** [comment]
This unauthenticated endpoint exposes too much information about the harbor install, information that could help an attacker determine the attack service of harbor and its dependencies.

here's the output from my recent install.   An attacker would find out I have notary disabled, that I'm using db authentication, self registration is disabled, when my last clair vulnerability updates happened, and that I'm using s3 for storage. There's no reason an anonymous user should ever know this data.

```
{
  "with_notary": false,
  "with_clair": true,
  "with_admiral": false,
  "admiral_endpoint": "NA",
  "auth_mode": "db_auth",
  "registry_url": "harbor:8443",
  "external_url": "https://harbor:8443",
  "project_creation_restriction": "everyone",
  "self_registration": false,
  "has_ca_root": true,
  "harbor_version": "v1.9.3-c80751b8",
  "clair_vulnerability_status": {
    "overall_last_update": 1575578301,
    "details": [
      {
        "namespace": "amzn",
        "last_update": 1575578301
      },
      {
        "namespace": "debian",
        "last_update": 1575578301
      },
      {
        "namespace": "centos",
        "last_update": 1575578301
      },
      {
        "namespace": "ubuntu",
        "last_update": 1575578301
      },
      {
        "namespace": "oracle",
        "last_update": 1575578301
      },
      {
        "namespace": "alpine",
        "last_update": 1575578301
      }
    ]
  },
  "registry_storage_provider_name": "s3",
  "read_only": false,
  "with_chartmuseum": true,
  "notification_enable": true
}
```

**Comment by weaktyper** [comment]
There's quite a few pararmeters that should not be here:

At least:

- `"self_registration"` 
- `"auth_mode"`

**Comment by sluetze** [comment]
It should also not show the `version` of any of the components.

**Comment by stonezdj** [comment]
Remove the following
"self_registration"
"auth_mode"
The version of any component

**Comment by reasonerjt** [comment]
@sluetze the auth_mode and self_registration is needed for UI to render the login dialog.

What information is sensitive to you?  I agree we may consider adjusting the data in response.

**Comment by sluetze** [comment]
I understand auth_mode and self_registration is needed to render the Login-UI.
I would classify the following information as sensitive:
* project_creation_restriction
* harbor_version
* read_only
* with_chartmuseum
* registry_storage_provider_name

as all of this can help an adversary to identify attack vectors

generally i would remove every info from an unauthenticated endpoint that is not required.

```json
{
  "with_notary": true, #sensitive
  "auth_mode": "ldap_auth", #needed
  "registry_url": "harbor.example.com", #not_sensitive
  "external_url": "https://harbor.example.com", #not_sensitive
  "project_creation_restriction": "adminonly", #sensitive
  "self_registration": true, #needed
  "has_ca_root": true, #not_sure
  "harbor_version": "v2.x....", #sensitive
  "registry_storage_provider_name": "filesystem", #sensitive
  "read_only": false, #sensitive
  "with_chartmuseum": true, #sensitive
  "notification_enable": true #not_sure
}
```

**Comment by reasonerjt** [comment]
@sluetze 
Thanks for the reply, I think it's do-able to drop some information if the request is not authenticated.

I'll check the code and get back to you with detailed response for confirmation.

**Comment by AllForNothing** [comment]
@reasonerjt From UI perspective， there will be no breaking changes on UI, if below info is returned when the request is not authenticated:
{
  "auth_mode": "ldap_auth", #needed
  "self_registration": true, #needed
  "harbor_version": "v2.x....", #sensitive
}

**Comment by reasonerjt** [comment]
To summarize, for unauthenticated request:
```
# curl https://jt-dev.local.goharbor.io/api/v2.0/systeminfo -k|jq .
{
  "auth_mode": "db_auth",
  "harbor_version": "-",
  "self_registration": false
}
```
for authenticated request:
```
# curl -u "admin:Harbor12345" https://jt-dev.local.goharbor.io/api/v2.0/systeminfo -k|jq .
{
  "auth_mode": "db_auth",
  "external_url": "https://jt-dev.local.goharbor.io",
  "harbor_version": "-",
  "has_ca_root": false,
  "notification_enable": true,
  "project_creation_restriction": "everyone",
  "read_only": false,
  "registry_storage_provider_name": "filesystem",
  "registry_url": "jt-dev.local.goharbor.io",
  "self_registration": false,
  "with_chartmuseum": false,
  "with_notary": false
}
```

**Comment by sluetze** [comment]
Thanks a ton, looks great!
