### ISSUE TITLE
Does the interface of Harbor have a limit parameter?

### ISSUE THREAD

**Issue by dotbalo** [goharbor/harbor#9152]
What can we help you?

I use the harbor interface to get a mirror tag in the project, but the mirror is too much, resulting in very slow return data. Does the interface have a limit parameter to limit the number of returns? For example? limit=50?

**Comment by wy65701436** [comment]
Which API are you calling? Harbor API does support pagination.

**Comment by dotbalo** [comment]
@wy65701436 像这样的API，获取tags的https://xxx.com.cn/api/repositories/xxx%2Fxxx/tags，tag过多返回的时间有点长。
