### ISSUE TITLE
Unable to modify ChartMuseum CHART_URL within Helm configuration

### ISSUE THREAD

**Issue by Wykiki** [goharbor/harbor#9153]
Hello !

Related to #6572, with the latest release 1.1.3, I am still unable to configure ChartMuseum to use a full URL in the `index.yaml`.

The changes are available in `master` since February 2019, but not in `1.1.3` released yesterday.

Is there a workaround for this, using the Helm chart ? (I already did manual setup of pods to bypass this problem)

Thanks !

**Comment by ywk253100** [comment]
Use the Harbor chart 1.2.0
