### ISSUE TITLE
migrate from 1.8.0 to 1.9.0

### ISSUE THREAD

**Issue by SaymonPhoenix** [goharbor/harbor#9159]
Hi.
For migration, is it enough to launch new images indicating volumes or additional steps are needed?

**Comment by Poil** [comment]
no, and it's look like it's missing something, 1.7 to 1.9 is OK via migrator but not 1.8 to 1.9

**Comment by ywk253100** [comment]
Please follow the migration guide

**Comment by Poil** [comment]
This one ? https://github.com/goharbor/harbor/blob/release-1.9.0/docs/migration_guide.md
Sorry nothing for 1.8 to 1.9 in the point 5

**Comment by SaymonPhoenix** [comment]
If not difficult, explain in detail 5 point.
I read and can’t understand why there are 2 times -v. I have only one harbor.yml.
Sorry for the stupid questions.

**Comment by ywk253100** [comment]
@ninjadq Please update the upgrade documentation

**Comment by renmaosheng** [comment]
https://github.com/goharbor/harbor/pull/9229 should address the issue.
