### ISSUE TITLE
1.8.3 upgread to 1.9.0 : FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/x.pf.abc.com.key'

### ISSUE THREAD

**Issue by zhaowencheng1991** [goharbor/harbor#9160]
HI
    I get some errs when I upgread harbor from 1.8.3 to 1.9.0 : 

[Step 2]: preparing environment ...
prepare base dir is set to /home/work/app/harbortest/harbor
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 36, in main
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/x.pf.abc.com.key'

Is  there something be missed in the upgread process & documentation 

Thank you

**Comment by reasonerjt** [comment]
Where did you put this file 
` x.pf.abc.com.key`

**Comment by zhaowencheng1991** [comment]
I put this file : "/data/cert/x.pf.abc.com.key" , And the file ”harbor.yml“ is transformed form version 1.8.3。

**Comment by ninjadq** [comment]
is any dir in your path is symbal link?

**Comment by alchatti** [comment]
We had similar issue on **RHEL7** and the solution was to modifiy the file `prepare` **line:53** from 

```bash
-v /:/hostfs:z \
```
to
```bash
-v $cert_dir:/hostfs:z \
```
Where `$cert_dir` is the directory that contain the SSL certificates

and for `harbor.yml` the https certificate path is set to `/`

```bash
certificate: /server.cer
private_key: /server.key
```

So far it is working for us

**Comment by zhaowencheng1991** [comment]
@alchatti  thanks 
@ninjadq   yes . The dir "/data/cert/"  is a symbal link . I change the harbor.yml  from 

/data/cert/x.pf.abc.com.crt

to

/home/work/data/cert/x.pf.xiaomi.com.crt

and it working for us. 

thanks

**Comment by sahramelissa** [comment]
Hi guys :) I had the same Problem and we still have 2 issue opened

https://github.com/goharbor/harbor/issues/13461
https://github.com/goharbor/harbor/issues/13465

If you look at prepare script you will see

docker run --rm -v $input_dir:/input
-v $data_path:/data
-v $harbor_prepare_path:/compose_location
-v $config_dir:/config
-v /pathOfYourCert/certs:/hostfs
--privileged
goharbor/prepare:v2.1.5 prepare $@

That will fix the problem for now

**Comment by DominicReuter-FIT** [comment]
Tried to set the path manually and modified my harbor.yml.

-v /data/cert:/hostfs

and in harbor.yml

certificate: /filename.crt
private_key: /filename.key

It will end up in a file or directory not exists error.

FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/filename.key'
make: *** [Makefile:410: prepare] Error 1

If i go with the original prepare (-v /:/hostfs) and modified the path in harbor.yml: 

certificate: /data/cert/filename.crt
private_key: /data/cert/filename.key

It will end up with the following error.

FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/htpasswd': '/usr/bin/htpasswd'
make: *** [Makefile:410: prepare] Error 1

Hope you can help me with this one.

thanks

**Comment by qklx** [comment]
> What fixed the FileNotFoundError for me was copying the TLS files instead of symlinking them.

It's work!  real file > instead of symlinking them
thx

**Comment by coopwilliams** [comment]
> > What fixed the FileNotFoundError for me was copying the TLS files instead of symlinking them.
> 
> It's work! real file > instead of symlinking them thx

Be aware that while this "works", you will still have to periodically bring down the application to renew the Cert, due to the way Docker accesses the cert.

`cd harbor`
`docker-compose down`
`certbot renew`
`docker-compose up` or `./install.sh`

**Comment by Hongten** [comment]
> We had similar issue on **RHEL7** and the solution was to modifiy the file `prepare` **line:53** from
> 
> ```shell
> -v /:/hostfs:z \
> ```
> 
> to
> 
> ```shell
> -v $cert_dir:/hostfs:z \
> ```
> 
> Where `$cert_dir` is the directory that contain the SSL certificates
> 
> and for `harbor.yml` the https certificate path is set to `/`
> 
> ```shell
> certificate: /server.cer
> private_key: /server.key
> ```
> 
> So far it is working for us

It works for me!!!
Thanks.

**Comment by hyorch** [comment]
Same issue on Rocky Linux 9.1 using /etc/ssl/certs/ for certification storage. As this folder is a symlink fails.
Solution: move certificates to a non symlink folder.

**Comment by alen-z** [comment]
This worked.

Use `/data/cert` on host and in HTTPS configuration state:
```
https:
  certificate: /data/cert/server.crt
  private_key: /data/cert/privkey.pem
data_volume: /data
```

**Comment by bennyzx** [comment]
Hi guys, same errors occurred in my macOS Catalina. 
I tried several ways above, but it doesn't still work for me.

Error message, as follows: 

➜  harbor ./prepare  
prepare base dir is set to /Users/zhouxuan/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/portal/nginx.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 45, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/harbor.example.com.key'

Can anybody help me out?

**Comment by mattv8** [comment]
2025 and I'm still stuck on this step for last 2 hours. Same error regardless of what path I use for the certs:
`FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/server.key'`
