### ISSUE TITLE
nginx pod can't start with error : mkdir() "/etc//nginx/client_body_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by MaGaoju** [goharbor/harbor#9172]
install harbor 1.9  via helm chart failed, keep getting nginx re-create with error :

[emerg] 1#0: mkdir() "/etc//nginx/client_body_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/etc//nginx/client_body_temp" failed (13: Permission denied)

anyone can help me on this? thx

**Comment by ywk253100** [comment]
In official Harbor chart the directory points to `/tmp/client_body_temp` https://github.com/goharbor/harbor-helm/blob/master/templates/nginx/configmap-https.yaml#L20

**Comment by MaGaoju** [comment]
@ywk253100 thx. I got the package from helm repo, helm fetch harbor/harbor, and unzip the package 1.1.2. just compare the files from this package and code repo, seems different. change the directory path works for me. thanks again.

**Comment by ywk253100** [comment]
The corresponding version of Harbor chart for 1.9.0 is 1.2.0 not the 1.1.2.
