### ISSUE TITLE
Use lazy router in harbor frontend router. 

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#9181]
To improve the page load speed. We can investigate how faster lazy loader can provide us.

**Comment by AllForNothing** [comment]
First loading time(with lazy loading modules):
![image](https://user-images.githubusercontent.com/30999793/106850515-9b151880-66ef-11eb-9474-5965fc880f24.png)

**Comment by AllForNothing** [comment]
First loading time (without lazy loading modules)
![image](https://user-images.githubusercontent.com/30999793/106850602-cb5cb700-66ef-11eb-9018-627a16316a1c.png)

**Comment by AllForNothing** [comment]
loading time changes  from  4.1.0s  to  2.5.2
