### ISSUE TITLE
Documentation change for OIDC group support

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9183]
1. Document the change in OIDC setting page
2. Document how the group is populated via ID Token
3. Document how to add group when Harbor is configured against OIDC provider for AuthN

**Comment by xaleeks** [comment]
@stuclem  Hey Stu, here's the PRD to help with explaining the feature.  https://docs.google.com/document/d/1ZkYYB24Y4xBfhMlskWFimVtUnn0vRUbmK4G7H11q2x4/edit

**Comment by xaleeks** [comment]
@stuclem btw going forward I think you can just watch for tickets that have these two tags for all release notes docs, target/ver + area/doc.  We'll make sure all features have a standalone pr for docs

**Comment by stuclem** [comment]
@xaleeks that works for me. Thanks!

**Comment by stuclem** [comment]
Added OIDC groups and rewrote the OIDC section in https://github.com/goharbor/harbor/pull/10029/commits/aca5d8071f2fde8def8888988cf531cf2b32a649. 

@xaleeks and @reasonerjt can you please review? This is part of a general overhaul of all of the authentication docs.

**Comment by stuclem** [comment]
@reasonerjt the OIDC docs could definitely do with a review, even if https://github.com/goharbor/harbor/pull/10029 is merged already. Thanks!
