### ISSUE TITLE
Error on vulnerabilities update - could not parse package version related with ubuntu

### ISSUE THREAD

**Issue by sfoxdev** [goharbor/harbor#9187]
Looks that the issue was solved here https://github.com/coreos/clair/issues/802
I've installed `goharbor/clair-photon:v2.0.9-v1.9.0` but still getting the error:
```
{
"Event":"could not parse package version. skipping",
"Level":"warning",
"Location":"ubuntu.go:316",
"Time":"2019-09-20 20:37:57.075979",
"error":"invalid version",
"version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"
}
```
Should have been fixed in 2.0.9 here https://github.com/coreos/clair/commit/e4f71d5644adde0499ec3b2bbddee7303fbf7e07#diff-209d24465a2688f8893f3d383eb03851

How can I solve it by myself or should we wait for a new image?

**Comment by ggilley** [comment]
I'm seeing the same issue.
