### ISSUE TITLE
Clair pod failing to start

### ISSUE THREAD

**Issue by eroji** [goharbor/harbor#9188]
I am running Harbor 1.9.0 in Kubernetes using the Helm chart deployment. The deployment was an upgrade from the previous chart available. After the upgrade, the Clair database did not seem to have upgraded correctly. In Harbor, the vulnerability section never showed a timestamp on when the database was successfully updated.

![image](https://user-images.githubusercontent.com/13228540/65362129-1e959e80-dbbb-11e9-9f29-d7a17791b98a.png)

I tried following this guide (https://github.com/goharbor/harbor/blob/master/docs/import_vulnerability_data.md) to hopefully reset the Clair database but after attempt to do so, the pod no longer starts up.

    {"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2019-09-20 22:26:23.329516"}
    {"Event":"pgsql: an error occured while running migrations: migration 2 failed: pq: type \"modification\" already exists","Level":"fatal","Location":"main.go:97","Time":"2019-09-20 22:26:23.368849"}

**Comment by ywk253100** [comment]
You can try to set the proxy for Clair to accelerate the vulnerability downloading

**Comment by donovanmuller** [comment]
I'm having a similar issue on a fresh 1.9.0 install via the Helm chart. All Pods are running and Clair seems to kick off the update:

```
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2019-09-28 21:04:43.563112"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:223","Time":"2019-09-28 21:04:43.577641"}
{"Event":"sender configured","Level":"info","Location":"notifier.go:66","Time":"2019-09-28 21:04:43.577989","sender name":"webhook"}
{"Event":"notifier service started","Level":"info","Location":"notifier.go:82","Time":"2019-09-28 21:04:43.578063","lock identifier":"e963f83a-edde-4880-8957-86a3ba45e14b"}
{"Event":"starting main API","Level":"info","Location":"api.go:52","Time":"2019-09-28 21:04:43.578165","port":6060}
{"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2019-09-28 21:04:43.578447","port":6061}
{"Event":"updater service started","Level":"info","Location":"updater.go:83","Time":"2019-09-28 21:04:43.579893","lock identifier":"4b1c8a5a-890a-414e-af33-81609017c39a"}
{"Event":"attempting to obtain update lock","Level":"debug","Location":"updater.go:102","Time":"2019-09-28 21:04:43.591783"}
{"Event":"update lock is already taken","Level":"debug","Location":"updater.go:152","Time":"2019-09-28 21:04:43.597785","lock expiration":"2019-09-28T21:09:25.845837Z","lock owner":"e1480a28-c9fc-4bef-a687-0670e5166311"}
{"Event":"updater sleeping","Level":"debug","Location":"updater.go:178","Time":"2019-09-28 21:04:43.597913","scheduled time":"2019-09-28T21:09:25.845837Z"}
...
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2019-09-28 21:09:25.851825"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2019-09-28 21:09:25.851884"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2019-09-28 21:09:25.851932","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2019-09-28 21:09:25.851982","package":"Amazon Linux 2"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2019-09-28 21:09:25.852154","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2019-09-28 21:09:25.852116","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2019-09-28 21:09:25.852953","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2019-09-28 21:09:25.853076","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2019-09-28 21:09:25.854174","package":"Amazon Linux 2018.03"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-09-28 21:09:26.483097","updater name":"alpine"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-09-28 21:09:26.828842","updater name":"amzn2"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-09-28 21:09:27.619166","updater name":"amzn1"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2019-09-28 21:09:27.941438","updater name":"debian"}
```

However, I still see the ⚠️ next to _Database updated on_ despite the fact that repositories are being scanned successfully.

![Screenshot 2019-09-28 at 23 16 04](https://user-images.githubusercontent.com/1175891/65822534-41bcef80-e246-11e9-88ff-bd12e9629885.png)

**Comment by krausexb** [comment]
Hey @donovanmuller, for me it seems that your Clair instance can't fetch all vulnerability information, Clair only acks the download of 4 vulnerability information but started fetching 8 different vulnerability information.

I had the same problem and fixed it by adding the following URLs into the whitelist of my proxy:
alas.aws.amazon.com
nvd.nist.gov
.suse.com
linux.oracle.com
.debian.org

**Comment by yuansmin** [comment]
you have to stop clair first, and then execute clear.sql and vulnerability.sql.

**Comment by catchups** [comment]
Is the environment running Clair DB Pod available on the Internet?

**Comment by xaleeks** [comment]
it seems this has been root caused
