### ISSUE TITLE
Get https://192.168.0.1/v2/: x509: cannot validate certificate for 192.168.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by hanalice** [goharbor/harbor#9190]
192.168.0.1 is where docker daemon runs on. I can visit harbor pages successfully. 
But when I push images to 192.168.0.1 from another docker client, such as 192.168.0.2, it throws  "x509: cannot validate certificate for 192.168.0.1 because it doesn't contain any IP SANs" error. 

 I configured the harbor https connect exactly same as [official guide](https://github.com/goharbor/harbor/blob/master/docs/configure_https.md) 

 anyone can help?

**Comment by ninjadq** [comment]
Can you provide more specifically steps of creating certs? do you place the ca files on you 192.168.0.2 's machine?

**Comment by hanalice** [comment]
> Can you provide more specifically steps of creating certs? do you place the ca files on you 192.168.0.2 's machine?

Thanks for help, it works afther copying three ca files( mydomain.cert, mydomainkey, ca.crt) into 192.168.0.2's machine.

**Comment by hanalice** [comment]
> Can you provide more specifically steps of creating certs? do you place the ca files on you 192.168.0.2 's machine?

Thanks for help, it works afther copying three ca files( mydomain.cert, mydomainkey, ca.crt) into 192.168.0.2's machine.

**Comment by MrAmbiG** [comment]
can anyone please inform others where to place the certificates ?? In windows you can access the gui and download ca.cert and right click and install but on linux how ? harbor documentation says nothing about it.

**Comment by hanalice** [comment]
@MrAmbiG you can refer to https://goharbor.io/docs/1.10/install-config/configure-https/, it usually is put under /etc/docker/certs.d/.
