### ISSUE TITLE
api-swagger define error

### ISSUE THREAD

**Issue by xiaokugua250** [goharbor/harbor#9205]
use swagger to generate go-client api, it reports redeclared bug,
 1. `api_products.go:41:6: ChartrepoChartsPostOpts redeclared in this block`
 2. `api_products.go:877:6: ChartrepoRepoChartsPostOpts redeclared in this block` 
 3. ` harbor-client\api_system.go:125:12: undefined: optional`

**Comment by nonetheless** [comment]
How could I generate a harbor golang client.

**Comment by danfengliu** [comment]
@stonezdj Is there any request still?
