### ISSUE TITLE
remove regex support for tag retention

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9206]
tag retention features on harbor UI claims support for regex, please get rid of this since we don't

**Comment by renmaosheng** [comment]
@AllForNothing could we get this done by today? thanks.

**Comment by AllForNothing** [comment]
@renmaosheng #9268 merged into branch release-1.9.0. Removing label "target/1.9.1"

**Comment by renmaosheng** [comment]
please close the issue once you check in the code in future, thanks  a lot ! @AllForNothing

**Comment by renmaosheng** [comment]
by the way, you mean merged into 1.10.0？ right? if this is a simple change, I would recommend to change it in 1.9.1

**Comment by AllForNothing** [comment]
Fixed in PR  #9282. Closing
