### ISSUE TITLE
get rid of 'enable rule' on replication rule creation

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9207]
The 'enable rule' checkbox at the end of replication rule creation seems unnecessary.  A creation most likely means the rule should be enabled.  This makes the 'enable rule' difficult to understand for 1st time users.  If user wants to create it but keep it deactivated, he must click 'disable' after it is created.  That's my feeling.  @wy65701436

**Comment by wy65701436** [comment]
But, do we need to do the migration? As we change the behavior, should we update `disabled` in the previous to `enabled`?

**Comment by xaleeks** [comment]
hmm, do the migration? What are you referring to?

**Comment by ywk253100** [comment]
We can just remove the checkbox on UI

**Comment by ywk253100** [comment]
Confirmed with @xaleeks, @jwangyangls please remove the checkbox on UI and set enabled as the default value
