### ISSUE TITLE
Adding new Registry Endpoint (docker-hub) results in `Failed to ping endpoint` error on Photon OS 3.0

### ISSUE THREAD

**Issue by nielsvz** [goharbor/harbor#9218]
**Expected behavior and actual behavior:**
Adding Docker Hub as avnew Registry Endpoint should be successful when running Harbor on Photon OS 3.0.

Instead, Harbor throws an error: `Failed to ping endpoint.`

core.log:
```
Sep 23 16:58:07 172.18.0.1 core[308]: 2019-09-23T16:58:07Z [ERROR] [/replication/adapter/native/adapter.go:143]: failed to ping registry https://registry-1.docker.io: Head https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:41081->127.0.0.11:53: i/o timeout
```

cURL does not work either in the harbor-core container:
```
$ docker exec -it harbor-core curl --head https://registry-1.docker.io/v2/
curl: (6) Could not resolve host: registry-1.docker.io
```

cURL works okay if using the harbor-core image without docker-compose:
```
$ docker run --rm -it --network harbor_harbor --entrypoint bash goharbor/harbor-core:v1.9.0 
$ curl --head https://registry-1.docker.io/v2/
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
Date: Mon, 23 Sep 2019 17:42:55 GMT
Content-Length: 87
Strict-Transport-Security: max-age=31536000
```

**Steps to reproduce the problem:**
1. Install Photon OS 3.0 from OVA
2. `tdnf install docker tar gawk`
3. Install docker-compose
4. Install Harbor using the online installer from the releases page on GitHub
5. Add a new Registry Endpoint using the docker-hub provider
6. Error shows up in the GUI and in core.log

**Versions:**
- harbor version: 1.8.3 and 1.9.0
- docker engine version: 18.06.2-ce
- docker-compose version: 1.24.1

[core.log](https://github.com/goharbor/harbor/files/3643430/core.log)
[harbor.yml.txt](https://github.com/goharbor/harbor/files/3643432/harbor.yml.txt)

**Comment by KocsistemCloud** [comment]
Any workarounds for this case?

**Comment by nielsvz** [comment]
As a workaround I've disabled the DNS stub listener (see `/etc/systemd/resolved.conf`):

```
sed -i "s/^#DNSStubListener=udp$/DNSStubListener=no/g" /etc/systemd/resolved.conf
ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf
systemctl restart systemd-resolved
```

**Comment by xaleeks** [comment]
@bitsf  Hi Ziming, please see if you have time to look into this

**Comment by bitsf** [comment]
This is not harbor's issue, I think something wrong with the system DNS.
And I think you can not even ping registry-1.docker.io from the host machine.

**Comment by bitsf** [comment]
I can reproduce now.
And if I run 
"docker run --rm --dns-search . -it --net harbor_harbor --entrypoint bash goharbor/harbor",
curl registry-1.docker.io will fail

**Comment by bitsf** [comment]
I can't find the reason why this not work now, maybe need some OS team's investigation.

And another workaround is you can just delete "dns_search: ." line in harbor/docker-compose.yml

I can't directly change this in code now, as I'm not sure the influence, currently no other one report such problem on other OS.

**Comment by bitsf** [comment]
And I also tested on Photon 2.0, it works OK. So there must be something changed in 3.0.

**Comment by nielsvz** [comment]
It looks like this is caused by `systemd-resolved`. Docker 18.09.0 and up support this by checking the appropriate `resolv.conf` if it detects `systemd-resolved`

https://github.com/moby/moby/pull/37485

Was able to verify this on Ubuntu 18.04.4:  
* `snap install docker` installs Docker 18.06 and reproduces the issue
* `apt-get install docker.io` installs Docker 18.09 and fails to reproduce the issue

**Comment by bitsf** [comment]
@nielsvz I can't reproduce this with docker 18.09 in ubuntu 18.10.

![image](https://user-images.githubusercontent.com/188115/66885769-f0637d00-f007-11e9-8ac1-87b2192ec564.png)

**Comment by nielsvz** [comment]
> @nielsvz I can't reproduce this with docker 18.09 in ubuntu 18.10.

I installed Docker on Ubuntu 18.04 (LTS) using snap and am able to reproduce this by running the command added to https://github.com/vmware/photon/issues/941:

<img width="800" alt="Screenshot 2019-10-16 08 45 23" src="https://user-images.githubusercontent.com/81711/66894770-8b049180-eff1-11e9-8859-bf7384499e33.png">

If I repeat the same with the docker.io package through apt it works fine:

<img width="800" alt="Screenshot 2019-10-16 08 50 21" src="https://user-images.githubusercontent.com/81711/66894964-0403e900-eff2-11e9-9623-2e03ef789b25.png">

**Comment by bitsf** [comment]
I have asked some other guy, that harbor use this dns_search param is to resolve other env issues. So I think you can just manually remove this in core and jobservice containers, it you still want to use Photon 3 now.

**Comment by Shkarface** [comment]
I have the same issue on harbor v2.2.1, it seems like you cannot ping hub.docker.com (even on my machine)

**Comment by kartikdc** [comment]
> As a workaround I've disabled the DNS stub listener (see `/etc/systemd/resolved.conf`):
> 
> ```
> sed -i "s/^#DNSStubListener=udp$/DNSStubListener=no/g" /etc/systemd/resolved.conf
> ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf
> systemctl restart systemd-resolved
> ```

Had to do this on Ubuntu 20.10 Groovy. Without this Harbor wasn't able to communicate with any online service for some reason.

**Comment by Fasten90** [comment]
> As a workaround I've disabled the DNS stub listener (see `/etc/systemd/resolved.conf`):
> 
> ```
> sed -i "s/^#DNSStubListener=udp$/DNSStubListener=no/g" /etc/systemd/resolved.conf
> ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf
> systemctl restart systemd-resolved
> ```

This helped to us also + restart (docker/compose). Thank you your workaround!
