### ISSUE TITLE
 Can tag cleanup rules be synchronized to the mirror server?

### ISSUE THREAD

**Issue by R1hug0** [goharbor/harbor#9227]
Can the tag cleaning rules  to the mirror machine when replicate images, at v1.9.0 i tried it  failed, is there anyway ?

**Comment by stonezdj** [comment]
No, these information stored in database, these information is not synchronized.

**Comment by steven-zou** [comment]
@R1hug0 

So far, the case you mentioned is not supported.

@xaleeks 

Any thoughts?

**Comment by xaleeks** [comment]
This is unsupported right now but we have a larger story to replicate harbor instance metadata info such as tag retention rules.  Please stay tuned for more developments on this @R1hug0

**Comment by xaleeks** [comment]
tracking as part of a larger story in https://github.com/goharbor/harbor/issues/7993
