### ISSUE TITLE
[Immutable Tag] Generate webhook when tag retention fails to delete immutable tag

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#9230]
As discussed with @xaleeks , it needs to throw an event if tag retention fails to delete a immutable tag.

**Comment by xaleeks** [comment]
Btw, I think tag retention failure to delete due to this should also throw a Webhook.  https://github.com/goharbor/harbor/issues/8717

**Comment by xaleeks** [comment]
so the webhook json payload should clearly show the reason for failure to delete, ie 1)immutability or 2)sharing digest with other tags

**Comment by xaleeks** [comment]
This should also be in doc, I will forward you the webhooks 2.0 prd for 1.10 that has this information @stuclem

**Comment by stuclem** [comment]
Created https://github.com/goharbor/harbor/issues/9570 to track the doc update, so removing `doc-impact` from this one.

**Comment by bitsf** [comment]
pr #10982 add webhook for deleted artifacts
