### ISSUE TITLE
harbor1.2版本，重启之后，registry一直处于unhealthy状态

### ISSUE THREAD

**Issue by yourmoonlight** [goharbor/harbor#9232]
执行的操作，
```
docker-compose stop
docker-compose up -d

```

出现的情况：
Registry启动失败
![image](https://user-images.githubusercontent.com/6244271/65494351-40f32900-dee7-11e9-8f40-563630f884ed.png)

**failed to connect registry**
> Sep 24 15:57:10 172.18.0.1 ui[25603]: 2019-09-24T07:57:10Z [ERROR] [utils.go:102]: failed to connect to tcp://registry:5000, retry after 2 seconds :dial tcp 172.18.0.4:5000: getsockopt: connection refused

请问这种情况，应该如何解决？
谢谢。

**Comment by stonezdj** [comment]
Please upload the harbor logs, and because 1.2.0 is out of maintain now, suggest to upgrade to latest version

**Comment by yourmoonlight** [comment]
> Please upload the harbor logs, and because 1.2.0 is out of maintain now, suggest to upgrade to latest version

我们的镜像文件大约有10T，Registry一直unhealthy，5000端口没起来，Registry容器无日志。

Harbor UI 容器的log已贴在上面，还需要提供哪些日志？

**Comment by yourmoonlight** [comment]
> Please upload the harbor logs, and because 1.2.0 is out of maintain now, suggest to upgrade to latest version

考虑升级，但是1.2之后的版本把DB换成了PG，升级可能会带来比较大的成本，在评估中。

**Comment by hyy0322** [comment]
hello, I have the same issue. Harbor version 1.4 .
After I restart the registry container, the status of the container remain unhealthy, the port 5000 is not up and the registry container doesn't output new log.
