### ISSUE TITLE
fix Harbor version for Admiral

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9236]
Use fixed version 1.7.x for Admiral and retire admiral-related code from Harbor code base starting with v1.10 so do not get flooded with  admiral logs for non-admiral based deployments.

**Comment by reasonerjt** [comment]
@renmaosheng Does it mean we want to remove admiral related code from Harbor in 1.10?

**Comment by renmaosheng** [comment]
Yes, if time allows, let's remove it in v1.10.

**Comment by michmike** [comment]
added this to 1.10 backlog

**Comment by reasonerjt** [comment]
This involves both backend and UI code, we'll target to 1.11 to deliver the complete removal.

**Comment by xaleeks** [comment]
please make sure this is done in 2.0, in first patch release if possible @reasonerjt

**Comment by reasonerjt** [comment]
Fixed by https://github.com/goharbor/harbor/pull/10034 (in master)

We also have downgrade the log-level of some admiral related message in the 1.10 and 1.9 patch releases.

Closing.
