### ISSUE TITLE
Cannot whitelist an RHSA vulnerability

### ISSUE THREAD

**Issue by funkypenguin** [goharbor/harbor#9242]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I expect to be able to whitelist any detected vulnerability. However, while most images have a vulnerability starting with `CVE`, some have a vulnerability starting with `RHSA` (`rook/ceph:v1.0.5` for example). 

This behaviour is preventing me from using the feature which prevents vulnerable images from being pulled (I want to whitelist harmless vulnerbilities). For now, I'm forced to turn off vulnerability scanning on pull, since I can't pull images with RHSA vulnerabilities, even if they're harmless.

**Steps to reproduce the problem:**

Attempt to whitelist `RHSA-2019:2237` via the or the API. In the UI, the `Add` button is not clickable. Via the API, the error looks like this:

```
harbor_core.1.j2fv8msssaei@cn1    | 2019-09-24T11:40:29Z [ERROR] [/common/api/base.go:195]: failed to update project 1: invalid CVE ID: RHSA-2019:2099
harbor_core.1.j2fv8msssaei@cn1    | 2019-09-24T11:40:29Z [ERROR] [/common/api/base.go:228]:
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.0
- docker engine version: `Docker version 19.03.2, build 6a30dfc`
- docker-compose version: N/A, using swarm

**Comment by xaleeks** [comment]
RHSAs are not covered by Clair so these should be getting picked up right now, so you shouldn't even have to whitelist those.  Are you saying that these rhsa are showing up as CVEs when done scanning in harbor?

**Comment by funkypenguin** [comment]
@xaleeks that's right - see screenshot below ;)

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1524686/65543295-fdd79b00-df64-11e9-97c7-6e3ab37f619f.png">

**Comment by xaleeks** [comment]
OK, let me look into this.  I didn't even know these were getting picked up..

**Comment by xaleeks** [comment]
I'm putting this up into backlog so these get picked up soon

**Comment by xaleeks** [comment]
@reasonerjt we need to pick these up in the whitelisting mechanism as well since the scanner is clearly seeing these.

**Comment by xaleeks** [comment]
this will be fixed in 1.9.2

**Comment by AllForNothing** [comment]
@funkypenguin There is a CVE format check in UI. You can call related api directly to add your white list temporarily.

**Comment by reasonerjt** [comment]
We'll walk through what distro-specific vulnerabilities doesn't match the "CVE-xxx-xxxx" and update the patterns

**Comment by reasonerjt** [comment]
per discussion with friends from Aqua, we've decided to remove the pattern checking for items in CVE whitelist as there are too much variation in  terms of the format of the vulnerability.

**Comment by AllForNothing** [comment]
Fixed in UI  for both branches master and release-1.9.0
