### ISSUE TITLE
doc issue on adding a new scanner

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#9259]
when adding a new scanner to harbor 1.10, please update this text
![image](https://user-images.githubusercontent.com/6655749/65604347-ea303280-df6c-11e9-8f8d-09fc2a9842ad.png)

please update "skip certificate verify" to "Skip Certificate Verification"

**Comment by xaleeks** [comment]
@steven-zou please fix this

**Comment by steven-zou** [comment]
@AllForNothing 

Please help to fix this issue. Thanks!

**Comment by AllForNothing** [comment]
Fixed in PR #9361
