### ISSUE TITLE
migrate harbor V1.8 to V1.9

### ISSUE THREAD

**Issue by zyriuse75** [goharbor/harbor#9270]
Hi folks 

i wollowing step by step the tutorial you wrote on how to[ migrating data ](https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md)

Under my new directory  **./harbor-v.1.9.0**  and running the script **./install.sh** everything seems doing well .

However when i go to the harbor interface i can't find anymore my project ( panic on board :) )

Is it normal that after the installation of v1.9.0 there are many less directory? 
https://gist.github.com/zyriuse75/1efa03d8c6d0b90357691254a70a9083

**Comment by smbambling** [comment]
Hopefully this will at least help point you in the correct path, here are the steps that I ran to upgrade from 1.8.2 to 1.9.0.  With my setup harbor is installed in /opt/harbor and I just make a copy then perform the steps

```cd /opt/harbor

docker-compose down

docker-compose ps (verify that containers are down)

cd /opt
cp -R harbor harbor-1.8.2 ( make a backup the previous harbor data/configs )

cd /opt/harbor

rm harbor.v1.8.2.tar.gz offline-installer1.8.2.tgz ( remove old files )

wget https://storage.googleapis.com/harbor-releases/release-1.9.0/harbor-offline-installer-v1.9.0.tgz

tar --strip-components=1 --show-stored-names -zxvf harbor-offline-installer-v1.9.0.tgz

cp ../harbor-1.8.2/harbor.yml . ( Copy old harbor file back in place that the tar overwrote )

docker run -it --rm -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up ( Run the harbor migrator )```

**Comment by zyriuse75** [comment]
did you change the value on docker-compose.yml 
 currently i've 
```
image: goharbor/registry-photon:v2.7.1-patch-2819-v1.8.1
image: goharbor/harbor-registryctl:v1.8.1
```

do i've to switch it to 
```
image: goharbor/registry-photon:v2.7.1-patch-2819-v1.9.0
image: goharbor/harbor-registryctl:v1.9.0
```

**Comment by zyriuse75** [comment]
i found the solution 
so after running 

`docker run -it --rm -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up ( Run the harbor migrator )`

I must to run `./install.sh --with-notary --with-clair --with-chartmuseum`

[information about](https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md) why to run ./install with or without the parameters

**Comment by zyriuse75** [comment]
thanks for your help

**Comment by gravcat** [comment]
> i couldn't upgrade directly to 1.90 so i upgrade to 1.8.3 .
> my biggest issue was i couldn't login with ldap user :(

Hi @zyriuse75, did you upgrade beyond 1.8.3 yet? We also found an issue with LDAPS connection to our SSO provider upon attempting to go 1.9.x, and are thus stuck at 1.8.3 for now as well.
