### ISSUE TITLE
nexus docker registry endpoint

### ISSUE THREAD

**Issue by adityanmishra** [goharbor/harbor#9275]
What can we help you?
HI we are currently exploring to use harbor for its better project control and clair support. Currently we are using sonatype nexus docker registry. To migrate all the images thought of using replication with endpoints.
When i look at the documentation for end point sonatype is not there. Will it work if we just add it as a docker registry ? 
Or we have to wait for an enhancement.

**Comment by stonezdj** [comment]
We didn't verify the replication with nexus docker registry endpoint

**Comment by reasonerjt** [comment]
@adityanmishra Have you tried the native docker registry adapter?

**Comment by KarstenSiemer** [comment]
I have the same problem.
Just using the native registry adapter doesn't work for me.
Reason being that the core component tries to always postfix the URL with '/v2'
But nexus does not like that.
The URL for getting the json of available images would for example be `https://someurl.de/repository/mydock/v2/_catalog`
But core is then trying to do this:
```
harbor-core-5d86585b4b-jfvd7 core 2019-11-19T14:55:25Z [DEBUG] [/common/utils/registry/auth/tokenauthorizer.go:73]: the request https://someurl.de/repository/mydock/v2/_catalog/v2/ is not sent to registry, skip
harbor-core-5d86585b4b-jfvd7 core 2019-11-19T14:55:25Z [DEBUG] [/common/utils/registry/transport.go:51]: 404 | HEAD https://someurl.de/repository/mydock/v2/_catalog/v2/
harbor-core-5d86585b4b-jfvd7 core 2019-11-19T14:55:25Z [ERROR] [/replication/adapter/native/adapter.go:143]: failed to ping registry https://someurl.de/repository/mydock/v2/_catalog: http error: code 404, message 
```
neither skipping `v2/_catalog` nor '_catalog' helps with this

**Comment by reasonerjt** [comment]
@KarstenSiemer Glad to know it's fixed!

So could you confirm that `native registry` DOES work for replicating nexus registry?

**Comment by KarstenSiemer** [comment]
@reasonerjt yes that works easily. The only problem that i had was that, since I am going for replacing the nexus registry with harbor, there were literally thousands of  references in our git of the nexus registry. And I wanted to pull all images from it and make them available under harbor with the exact same URL, so that the switch can be made more easily. I thought to disable pushing via that URL and everyone who wants to deploy new images now has to use the new URL. 
This didn't work because of the structure with the repositories used in harbor.
I replicated the nexus registry into into the harbor repository "old-registry". Anyone who wants to pull images from there has to reference this repo in his request.
I solved that by deploying an additional HAProxy instance in front of harbor which is rewriting the requests.
This is the config snipped i used to do that:
```
      acl p_path_correct       path_beg /v2/old-registry/
      acl p_pull_image         path_reg ^\/v2\/[^.*]+
      http-request             set-path /v2/old-registry/%[path,regsub(^/v2/?,,)] if p_pull_image !p_path_correct
      http-request set-header  Host harbor.svc.y6b.de
      reqrep ^(.*)scope=repository%3A(.*) \1\scope=repository:old-registry/\2
```

**Comment by wesmiles** [comment]
@KarstenSiemer - I am also using a Nexus 3 Docker Registry and pointing a Harbor Endpoint at it using the docker-registry provider. Did you get yours working with a hosted Nexus 3 Docker Registry or proxy or group?  I would like to use a group but I don't have a _catalog json file.

But just wondered what your settings were when configuring the endpoint.  I too am using HAProxy to front Nexus and letting it access based on the harbor user agent.

Any help is greatly appreciated.

**Comment by adityanmishra** [comment]
It works with nexus registry. The only trick i found is the url should be below
https://username:password@nexusurl//repository/{dockerimagereponame}/  
and keeping the accessid and password blank

**Comment by posteingang** [comment]
With the newest Helm version (1.4.1) and harbor 2.0.1 it is not possible anymore to replicate with this provided solution. :disappointed:

**Comment by yelmir** [comment]
> losed this as [completed](/goharbor/harbor/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [on 7 Jan 2020](#event-2928804072)

not worked for me, still give me an error that harbor doesn't authorized to do the request

**Comment by T0LED0** [comment]
@KarstenSiemer Do you know if your configuration with HAProxy is valid for Harbor v2?
