### ISSUE TITLE
v1.9.0 loadSystemConfigFromEnv failed, config item, key: clair_db_port

### ISSUE THREAD

**Issue by DavidRodHub** [goharbor/harbor#9277]
Installed harbor-1.9.0 on AWS EC2 instance  and after copying repos using 'skopeo" from an AWS-docker-registry to the new harbor-registry,  containers "harbor-core" and habor-jobservice never comes back up.  The core.log  has the following error.
 
**ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax**

NOTE:  With harbor version 1.3.0, performed the same steps and it copied successfully and I was able to see the image in the Harbor UI

**Steps to reproduce the problem:**
1. Installed harbor 1.9.0 on new AWS EC2 instance: Passed
2. Create 1 project-A  on harbor and users with developer permission: Passed
3. Tested pushing 1 image to harbor: Passed
3. Copied all repos from  AWS-Docker-registry/project-A  to harbor/project-A
    **Total of 321 repos, 2642 tags**

NOTE: Harbor-core and job-service remain in the "Up (health: starting)" for over 3 hours.
**docker-compose ps**
**harbor-core         /harbor/harbor_core              Up (health: starting)**                                              
harbor-db           /docker-entrypoint.sh            Up (healthy)            5432/tcp                                   
**harbor-jobservice   /harbor/harbor_jobservice  ...   Up (health: starting)**                                              
harbor-log          /bin/sh -c /usr/local/bin/ ...   Up (healthy)            127.0.0.1:1514->10514/tcp                  
harbor-portal       nginx -g daemon off;             Up (healthy)            8080/tcp                                   
nginx               nginx -g daemon off;             Up (healthy)            0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp
redis               redis-server /etc/redis.conf     Up (healthy)            6379/tcp                                   
registry            /entrypoint.sh /etc/regist ...   Up (healthy)            5000/tcp                                   
registryctl         /harbor/start.sh                 Up (healthy)  

**Clip out of the core.log**
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/config/config.go:98]: key path: /etc/core/key
**Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax**
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/config/config.go:71]: init secret store
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/config/config.go:74]: init project manager based on deploy mode
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/main.go:173]: configurations initialization completed
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/common/dao/base.go:89]: Register database completed
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/common/dao/pgsql.go:122]: No change in schema, skip.
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/common/config/encrypt/encrypt.go:60]: the path of key used by key provider: /etc/core/key
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/main.go:80]: User id: 1 already has its encrypted password.
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/main.go:221]: initializing notification...
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/pkg/notification/notification.go:50]: notification initialization completed
Sep 26 23:28:09 192.168.208.1 core[13115]: 2019-09-26T23:28:09Z [INFO] [/core/main.go:243]: Because SYNC_REGISTRY set false , no need to sync registry 

 

Attached files.
[harbor.tar.gz](https://github.com/goharbor/harbor/files/3660344/harbor.tar.gz)
[harbor-logs.tar.gz](https://github.com/goharbor/harbor/files/3660349/harbor-logs.tar.gz)

**Comment by DavidRodHub** [comment]
Upgraded to 1.9.1 and still have the same issue.

Found a work around recommended in another without having to re-install from scratch.  It worked.

**TYPE**:  docker exec -ti harbor-db psql
      . psql (9.6.14)
      .    Type "help" for help.
      . postgres=#         
      .           postgres=# 

**TYPE**: \c registry
      . You are now connected to database "registry" as user "postgres".

**TYPE**: \c registry
**TYPE**: TRUNCATE TABLE project_blob
**TYPE**: ;
      . TRUNCATE TABLE
**TYPE**: \q  (exit postgres)

VERIFY:  core.log file to get process status:
  - tail -f /var/log/harbor/core.log

After doing the above,  and doing the following caused harbor to crash again with the same problem reported in the issue.

  -  docker-compose stop
  -  docker-compose start

**Comment by DavidRodHub** [comment]
FYI:  Did the following today without using the replication feature  to sync registry.  Used skopeo to sync that works with harbor 1.3.0 and still got the ERROR: invalid user when trying to log-in as admin.

1. Re-installed harbor 1.9.1 from scratch.
2. Created project X
3. Created 2 new users.
4. Assigned users to project X
5. Ran skopeo script to copy all images from other registry
6. Ran:   docker-compose stop
7. Ran:   docker-compose start
8. Attempted log-in as admin.
9. Got Error :  Invalid username or password.

**Comment by stonezdj** [comment]
We didn't verify if Harbor can work with the skopeo, when you login failed, you need to check all container especially harbor-db is running.

**Comment by stonezdj** [comment]
for the issue loadSystemConfigFromEnv  failed, config item, key: clair_db_port, it could be something wrong with your harbor.yml, it will generate a file : common/config/core/env,  there is a env key: 
`CLAIR_DB_PORT=5432 `
It seems that this key is set to empty.
`CLAIR_DB_PORT= `

**Comment by relovely** [comment]
> for the issue loadSystemConfigFromEnv failed, config item, key: clair_db_port, it could be something wrong with your harbor.yml, it will generate a file : common/config/core/env, there is a env key:
> `CLAIR_DB_PORT=5432 `
> It seems that this key is set to empty.
> `CLAIR_DB_PORT= `

Great! It works for me, thx~
