### ISSUE TITLE
1.9.0 Failed to start GC: 500

### ISSUE THREAD

**Issue by liuxu623** [goharbor/harbor#9283]
```
2019-09-26T17:00:00Z [INFO] [/jobservice/job/impl/gc/job.go:86]: start to run gc in job.
2019-09-26T17:12:00Z [ERROR] [/jobservice/job/impl/gc/job.go:89]: failed to get gc result: Failed to start GC: 500
```
```
registry garbage-collect -d /etc/registry/config.yml

DEBU[0325] swift.Walk("/docker/registry/v2/blobs")       go.version=go1.11.8 instance.id=aebb6994-18d2-438a-a548-4d2b1c864d26 service=registry trace.duration=42.285913041s trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk" trace.id=fdf9ffb0-90e4-4dee-bda7-3b18bc3d3bcd trace.line=232
failed to garbage collect: error enumerating blobs: swift: Timeout expired while waiting for segments of /docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/data to show up
```
```
swift list --lh registry -p files/docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/
   0 2019-09-26 13:03:02 application/octet-stream files/docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/data
   0
```

**Comment by liuxu623** [comment]
https://github.com/docker/distribution/issues/2188

**Comment by odeng888** [comment]
I have the same problem. When can we solve it？

**Comment by liuxu623** [comment]
> I have the same problem. When can we solve it？

I delete empty file in swift and GC start success, but I found another problem, GC is very very slow when use swift or s3.

**Comment by odeng888** [comment]
> > I have the same problem. When can we solve it？
> 
> I delete empty file in swift and GC start success, but I found another problem, GC is very very slow when use swift or s3.

How to make sure it's an empty file？

**Comment by odeng888** [comment]
@liuxu623

**Comment by shcherbak** [comment]
We are still suffering of this problem. If you need any details, please refer, i will provide information you need to fix this.
We have intensively used registry setup with swift backend and unable to clean it properly

**Comment by shcherbak** [comment]
We have large and intensively used registry, for example there is repositories with more then 500 tags. We investigated that garbage collect hangs when need to remove many (apx more then 1000 blobs). When we did garbage collecting with custom script, native garbage collect starts working fine

**Comment by shcherbak** [comment]
@wy65701436 IMHO we need to reopen this issue
