### ISSUE TITLE
REST API: the endpoint /projects?name=test returns null when user not authenticated

### ISSUE THREAD

**Issue by Szauka** [goharbor/harbor#9293]
**Expected behavior:**
The endpoint should return the response that is specified in the documentation. In this case the endpoint ~/projects should return "401 User need to log in first." as I'm trying to access the information trough the endpoint and filter by name.

**Actual behavior:**
The ~/projects?name=test endpoint returns null when the user isn't authenticated. This can cause confusion because if I log in I do get the projects information but if I haven't logged in, I could wrongly assume that the projects isn't there.

**Steps to reproduce the problem:**
Try accessing the ~/projects?name=name_of_existing_project without specifying the Authorization header.

**Versions:**
Please specify the versions of following systems.

- harbor version: v1.8.0-25bb24ca
- docker engine version:  18.09.7, build 2d0083d
- docker-compose version: 1.24.1, build 4667896

**Comment by reasonerjt** [comment]
This was done this way b/c there's "public" projects which by design can be accessed by user that is not authenticated.

**Comment by Szauka** [comment]
@reasonerjt I understand that, but in that case shouldn't the endpoint return an empty array "[]" instead of "null"?
If we get an empty array then it would be easier to understand that there are no "public" projects.
