### ISSUE TITLE
failed to fetch image: FetchImages error when collect tags for repos

### ISSUE THREAD

**Issue by d2dyno** [goharbor/harbor#9295]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: Connecting to a gitlab-based docker registry, will allow replication of any namespace images.

Actual: Error when running replication for `name/*-docker`: 
`failed to fetch image: FetchImages error when collect tags for repos`

**Steps to reproduce the problem:**
Connect Gitlab registry as Docker Registry.
Create replication of gitlab registry.
Run replication.

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.0
- docker engine version: 19.03.2
- docker-compose version: 1.24.0

**Additional context:**

Was working in 1.8.x just fine. Upgrade to 1.9.x is when issue occurs. I tried creating a new access token in gitlab, and adding this as a new registry to Harbor, but encountered the same issue.

```
Sep 27 20:56:24 172.22.0.1 core[43811]: 2019-09-28T01:56:24Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'somename/ffmpeg-docker' error: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"somename/ffmpeg-docker","Action":"pull"}]}]}
Sep 27 20:56:24 172.22.0.1 core[43811]: 2019-09-28T01:56:24Z [ERROR] [/replication/operation/controller.go:108]: the execution 502736 failed: failed to fetch image: FetchImages error when collect tags for repos
```

```
Sep 27 20:56:03 172.22.0.1 jobservice[43811]: 2019-09-28T01:56:03Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'REPLICATION:127ea46d2ae4b0748606fb28' exit with error: {"code":10010,"message":"object is not found","details":"127ea46d2ae4b0748606fb28"}
```

**Comment by d2dyno** [comment]
Still an issue in 1.9.1

**Comment by Mangosniper** [comment]
I have the same issue on 1.9.1. Had 1.8.0 before. I am replicating from a 1.9.1 Harbor to another 1.9.1 Harbor-Instance.

Harbor-Version: 1.9.1
Docker-Engine-Version: 18.09.6
Docker-Compose-Version: 1.24.0

**Comment by d2dyno** [comment]
Still an issue in 1.9.2

**Comment by learn0208** [comment]
+1

**Comment by jiangyanfeng** [comment]
+1

**Comment by d2dyno** [comment]
still an issue in 1.10.0-rc1

**Comment by d2dyno** [comment]
@ywk253100 can we get an update on this?

**Comment by romain-rossi** [comment]
+1

**Comment by QCU266** [comment]
+1

**Comment by fxiang21** [comment]
same problem +1

**Comment by d2dyno** [comment]
@ywk253100 can we get an update on this?

**Comment by bitsf** [comment]
I think this issue maybe similar with #9874 , need further investigate how gitlab do authentication.
And in harbor 1.10.0, there's a gitlab replication adapter contributed from community, you can have a try.

**Comment by d2dyno** [comment]
The gitlab replication doesn't work for my private gitlab instance.

**Comment by eringet** [comment]
I am receiving this error replicating harbor to harbor as well.  The harbor servers are running version 1.9.2-17.  The replication job, whether run manually or scheduled, fails with this error 95% of the time.  We replicate several projects.  The smaller projects replicate fine, but the larger project that nearly always fails has 184 repositories (each with an average of 50 images).

**Comment by bitsf** [comment]
@d2dyno What you mean not work for private gitlab instance ? Are you saying gitlab adapter in 1.10 not worked

**Comment by bitsf** [comment]
@eringet which error do you mean? "UNAUTHORIZED" or "object is not found"
Can these job recovery if run again ?

**Comment by d2dyno** [comment]
@bitsf yes. I think it was designed for gitlab.com, not for self-hosted. Idk, but it doesn't work.

**Comment by d2dyno** [comment]
Any movement on this?

**Comment by cslanjian** [comment]
i got this when i was replicated from 1.9.4 to 1.9.4.
and just one respositry has this problem
really confused me
how to config out?

**Comment by ywk253100** [comment]
PR #10389 is merged, closing this issue
