### ISSUE TITLE
getting error in jobservice log

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#9308]
Oct  1 15:42:30 172.19.0.1 jobservice[6800]: 2019-10-01T10:12:30Z [ERROR] [/common/config/store/store.go:67]: error when loading data item, key storage_per_project, value 1.073741824e+11, error strconv.ParseInt: parsing "1.073741824e+11": invalid syntax

**Comment by heww** [comment]
What is default disk space per project value in the configuration?

![WX20191010-093355](https://user-images.githubusercontent.com/5634205/66532210-205edc00-eb41-11e9-9ef1-c780a7ac64ad.png)
