### ISSUE TITLE
Clarify "Event Based" replication mode

### ISSUE THREAD

**Issue by mumrau** [goharbor/harbor#9316]
Hello,

I was looking forward to harbor 1.9, and it fulfills my expectation, label based replication is back for the good, and I am already making great use of this.
I am somehow frustrated and quite curious about something, I expected the "event based" mode to take in consideration labelling, i.e I expected my image to be replicated through the replication rule when I effectively label the image.

It made me realise that the documentation is quite vague, it also does not precise whether the retagging of an app triggers the replication rule.

I don't know if it should be implemented, even though I think it would make perfect sense to activate the rule whenever a label used upon replication is added to any image.

Looking forward to debating this.

**Comment by xaleeks** [comment]
@mumrau Labels are not in play for event-based because you add the harbor labels after they are pushed to harbor, not prior.  Since event-based replication refers to the events of pushing and retagging to Harbor, the images always arrive with no labels.  We will do a better job explaining this on the docs.  We've discussed event-based labelling, ie adding labels as soon as images are pushed to Harbor but that's for the future.

@stuclem Hi Stuart, can you look into clarifying this on the user guide? Thanks.

**Comment by xaleeks** [comment]
I'm adding this to backlog as a potential to-do

**Comment by stuclem** [comment]
Assigning this one to myself as it's purely a doc effort.

**Comment by stuclem** [comment]
@xaleeks and @mumrau I attempted to address this in https://github.com/goharbor/harbor/pull/10029/commits/9c17508ac301e72e2db577748629875b83377a47. Can you please take a look? Thanks!

**Comment by xaleeks** [comment]
> @xaleeks and @mumrau I attempted to address this in [9c17508](https://github.com/goharbor/harbor/commit/9c17508ac301e72e2db577748629875b83377a47). Can you please take a look? Thanks!

this is exactly right

**Comment by stuclem** [comment]
Thanks @xaleeks. Closing as fixed.

**Comment by mumrau** [comment]
(I'm too late but yep it fixes the documentation.)

I do believe though that labelling events really make sense for many use cases:like during the deployment of an app t

**Comment by mumrau** [comment]
(I'm too late but yep it fixes the documentation.)

I do believe though that labelling events really make sense for many use cases. For instance, labelling an image during the deployment of the image to a target environment, with a target registry, having the image replicated at that time would be quite awesome. 
Should I create another issue to discuss and track this?
