### ISSUE TITLE
Unable to add group in 1.9.0 

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#9319]
Unable to add group DN in 1.9.0 however same DN is working in 1.8.1

**Comment by krausexb** [comment]
Cant confirm this. Im also running on 1.9 and have no problems adding AD Groups via DN.
Can you check the Logs and give more Information about your setup?
@dbenduga

**Comment by stonezdj** [comment]
can you please provide more detail information on how to reproduce this issue?

**Comment by dbenduga** [comment]
Nov  5 03:44:49 10.104.1.1 core[6470]: 2019-11-05T09:44:49Z [ERROR] [/common/api/base.go:68]: POST /api/usergroups failed with error: {"code":400,"message":"LDAP Group DN is not found: DN:CN=Cloud Infrastructure,OU=Distribution Groups,OU=Security,DC=adprod,DC=bmc,DC=comCN=Cloud Infrastructure,OU=Distribution Groups,OU=Security,DC=adprod,DC=bmc,DC=com"}
Nov  5 03:47:14 10.104.1.1 core[6470]: 2019-11-05T09:47:14Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_attribute_name, error: the configure value is not set
Nov  5 03:47:14 10.104.1.1 core[6470]: 2019-11-05T09:47:14Z [ERROR] [/common/config/manager.go:192]: failed to get key ldap_group_admin_dn, error: the configure value is not set

**Comment by stonezdj** [comment]
you have to configure LDAP group configuration before using LDAP group related feature.
