### ISSUE TITLE
can't stop harbor by docker-compose

### ISSUE THREAD

**Issue by jiaminxu** [goharbor/harbor#9322]
can't stop harbor by docker-compose

**Expected behavior and actual behavior:**
Expected behavior:  restart harbor by docker-compose 
actual behavior:  Restart failed

**Steps to reproduce the problem:**
1 reboot ECS server without stop harbor
2 start ECS server and run command :dock ps -a (result:pic1)
![image](https://user-images.githubusercontent.com/20829899/66189513-80c2c900-e6bc-11e9-9b57-53ae067c0399.png)

3 run command: docker-compose stop && docker-compose up -d 
Report an error (pic2) 
![image](https://user-images.githubusercontent.com/20829899/66189763-18281c00-e6bd-11e9-9540-33f4c773a489.png)

4 no logs of  harbor-log 
![image](https://user-images.githubusercontent.com/20829899/66189968-8a006580-e6bd-11e9-915b-050a0290e208.png)

5 can't restart by docker-compose restart  ;systemcetl restart docker

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.8.2]
- docker engine version: [18.06.1-ce]
- docker-compose version: [1.22.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
Please use `docker-compose down -v` to shut down harbor.
