### ISSUE TITLE
Job Service in crashloopbackoff, causing internal server errors

### ISSUE THREAD

**Issue by akathimi** [goharbor/harbor#9324]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected: job service always running / runs when its pod is deleted
Actual: crashloopbackoff, due to restarting the service, the problem is caused because of the chown command for the logs directory(pvc-> /var/logs/jobs) contents in the entrypoint (start.sh)(chown -R 10000:10000 /var/log/jobs/), when you have too much log data (my case was 2.7GB), the chown command took too long that the liveness probe restarted the pod.

**Steps to reproduce the problem:**
1- deploy on k8s
2- fill the job service log with data (the number of files is what causes the issue not the size of the file)
3- restart the pod
**Versions:**
Please specify the versions of following systems.

- harbor version:  v1.8.2
- kubernetes version 1.13.7 chart-version 1.1.2

**Additional context:**

**Comment by reasonerjt** [comment]
Could you open issue to goharbor/harbor-helm repo?

btw, we are considering to make the `initialDelay` of liveness probe configurable.
