### ISSUE TITLE
delete repository from the UI, files are not all cleaned on disk

### ISSUE THREAD

**Issue by grozan** [goharbor/harbor#9325]
**Expected behavior and actual behavior:**
if I delete a repository from the UI, I expect all the files to be deleted on disk.
In my case `/data/registry/docker/registry/v2/blobs` is cleaned, but `/data/registry/docker/registry/v2/repositories` is not.

I see another bug report #5061 had been opened for the same thing, and closed. The problem seems to still be there, though.

**Steps to reproduce the problem:**
create a repository, and upload an image
delete the repository from the UI
inspect the content of /data/registry/docker/registry/v2

Example with my fresh install of 1.9.0

I create a `test1` project. In there, I upload the `test1/centos` image
I delete the `centos` repository from the UI

Result: the `/data/registry/docker/registry/v2/blobs` directory is clean. That's good. In my case, the following content for example was gone after garbage collection
```
./docker/registry/v2/blobs/sha256/a8/a8c7037c15e94b26d3a3ac6930d536a224172f0ff4dab9090a8a24c345717ce3
./docker/registry/v2/blobs/sha256/a8/a8c7037c15e94b26d3a3ac6930d536a224172f0ff4dab9090a8a24c345717ce3/data
./docker/registry/v2/blobs/sha256/9a/9aec5c5fe4ba9cf7a8d2a50713dd197c3b0cbd5f5fcd03babe4c1d65c455dabf
./docker/registry/v2/blobs/sha256/9a/9aec5c5fe4ba9cf7a8d2a50713dd197c3b0cbd5f5fcd03babe4c1d65c455dabf/data
```

BUT the `/data/registry/docker/registry/v2/repositories` folder is NOT clean. I still can see those files/folders

```
./docker/registry/v2/repositories/test1/centos
./docker/registry/v2/repositories/test1/centos/_uploads
./docker/registry/v2/repositories/test1/centos/_layers
./docker/registry/v2/repositories/test1/centos/_layers/sha256
./docker/registry/v2/repositories/test1/centos/_layers/sha256/a8c7037c15e94b26d3a3ac6930d536a224172f0ff4dab9090a8a24c345717ce3
./docker/registry/v2/repositories/test1/centos/_layers/sha256/a8c7037c15e94b26d3a3ac6930d536a224172f0ff4dab9090a8a24c345717ce3/link
./docker/registry/v2/repositories/test1/centos/_layers/sha256/9aec5c5fe4ba9cf7a8d2a50713dd197c3b0cbd5f5fcd03babe4c1d65c455dabf
./docker/registry/v2/repositories/test1/centos/_layers/sha256/9aec5c5fe4ba9cf7a8d2a50713dd197c3b0cbd5f5fcd03babe4c1d65c455dabf/link
./docker/registry/v2/repositories/test1/centos/_manifests
./docker/registry/v2/repositories/test1/centos/_manifests/revisions
./docker/registry/v2/repositories/test1/centos/_manifests/revisions/sha256
./docker/registry/v2/repositories/test1/centos/_manifests/revisions/sha256/4516078f48ca34907ed8f874005473059dc29d46745d139c7cea85e3d474f4fb
./docker/registry/v2/repositories/test1/centos/_manifests/tags
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.9.0
- docker engine version: 19.03.2
- docker-compose version: 1.24.1, build 4667896b

**Comment by krausexb** [comment]
Hey @grozan, did you run the so called "Garbage Collection". As I understand this finally deletes unneeded Data from your disk.

The Garbage Collection takes some time, while it is running the registry is in pull only mode.

**Comment by grozan** [comment]
yes, multiple times, manually, since the repo was deleted yesterday evening.
GC is now set to hourly

**Comment by grozan** [comment]
couldn't it be included in the GC process?

As-is, it leaves quite a mess behind on disk.
With containers I really like that nothing is left on the host after they are deleted.
I wish it was the same for the container registry

**Comment by xaleeks** [comment]
closing this as its part of the docker distribution design.
