### ISSUE TITLE
Broken Harbor UI Version v1.9.0

### ISSUE THREAD

**Issue by krausexb** [goharbor/harbor#9327]
After updating Harbor from 1.8 to 1.9 the UI seems to be broken on some Browsers. The Installation is working fine but the UI doesn't.

**Behavior when using firefox:**
Everything looks fine.
![Bildschirmfoto 2019-10-07 um 14 33 34](https://user-images.githubusercontent.com/50952100/66311743-7fd5a580-e90f-11e9-8ea1-b3fafaedd6ec.png)

**Behavior when using chrome, safari:**
It looks like the css styling is broken.
![Bildschirmfoto 2019-10-07 um 14 32 04](https://user-images.githubusercontent.com/50952100/66311677-4866f900-e90f-11e9-839c-953b6673763d.png)

**Versions and further Information:**
Harbor Version: Version v1.9.0-d13cf448
Running on K8s
Installed with harbor-helm
Firefox Version: 67.0.4 (64-Bit)
Chrome Version: Version 77.0.3865.90 (Offizieller Build) (64-Bit)
Safari Version: Version 12.1.2 (14607.3.9)

**Comment by AllForNothing** [comment]
@krausexb Please clear up the browser cache. It should fix the issue.
