### ISSUE TITLE
Document PG version requirements better

### ISSUE THREAD

**Issue by jacekn** [goharbor/harbor#9333]
**Description:**

[Documentation](https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#harbor-components) is not clear with regards to supported PG versions.

PG "9.6.10-1.ph2" is quoted as harbor "component" but it's not obvious what versions are supported when using external database.

Ubuntu 16.04 ships with PG is 9.5.19 and Ubuntu 18.04 ships with PG 10.10. Are any of them supported?

It's not clear whether all 9.6.X versions are supported or Harbor depends on very specific version 9.6.10-1.ph2.

**Comment by reasonerjt** [comment]
I think officially we only support the one packaged with Harbor as it's tested.
I don't think we have bandwidth to test other versions.

**Comment by jacekn** [comment]
> I think officially we only support the one packaged with Harbor as it's tested.

Most projects I know don't require very specific PG revision, they only specify major versions because functionality does not change between patchlevels.

The reason it's important is security patches. If users are expected to use the version you package then they might expect it's security patched. Something like this should be clarified in the docs I think.

> I don't think we have bandwidth to test other versions.

It's completely understandable. You're doing an amazing job but I'm sure your resources are limited.
Maybe it's possible for harbor develoepers to check if there is anything that would require the very specific version you provide? I suspect there is no hard requirement other than lack of time to test. In that case the documentation could then say something like:

_Our releases are tested against and shipped with postgres 9.6.10. Other postgres 9.6 revisions should work but they are not tested nor supported by the development team_

**Comment by jacekn** [comment]
For your consideration I posted some info about operation difficulties that very specific PG version poses here: https://github.com/goharbor/harbor/issues/9031#issuecomment-542621102 

Also FYI I deployed harbor with PG 10.10 and so far it seems absolutely fine.
