### ISSUE TITLE
Only at most 500 sub tasks can be seen in tag retention GUI

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9337]
In harbor 1.9.1

Only 500 sub tasks can be seen that actually 2000 tasks
![image](https://user-images.githubusercontent.com/188115/66446045-70736b00-ea7b-11e9-9b5f-94f67d0954c3.png)

**Comment by bitsf** [comment]
This is because UI doesn't use param page_size and page, that backend will use default value page_size=500 page=1

**Comment by AllForNothing** [comment]
Fixed for both master and release-1.9.0  with PR  #9449 and #9442
