### ISSUE TITLE
harbor upgrade from 1.8.1 to 1.9.0 - getting error in core log

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#9344]
Oct  9 15:53:14 172.19.0.1 core[7087]: 2019-10-09T10:23:14Z [INFO] [/core/api/quota/migrator.go:101]: [Quota-Sync]:: fail to dump data from server ... [registry], quit sync ...
Oct  9 15:53:14 172.19.0.1 core[7087]: 2019-10-09T10:23:14Z [ERROR] [/core/main.go:104]: Fail to sync quota data, quota sync error on getting info of project: quota sync error on getting info of repo: http error: code 404, message {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"SmartIT_Automation_1908"}}]}
Oct  9 15:53:14 172.19.0.1 core[7087]: 2019-10-09T10:23:14Z [FATAL] [/core/main.go:252]: quota migration error, quota sync error on getting info of project: quota sync error on getting info of repo: http error: code 404, message {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"SmartIT_Automation_1908"}}]}

"SmartIT_Automation_1908" this images size is 0B, Unable to delete image 
How to remove 0B images?

**Comment by reasonerjt** [comment]
@dbenduga I don't think the 0 size issue is related to the migration.

Normally it's a bug in upstream registry, to workaround you push the image with same tag again and then it can be deleted.

@wy65701436 could you check the error in migration?

**Comment by dbenduga** [comment]
@reasonerjt .. Thanks for quick response,

I have followed below process to upgrade from 1.8.1 to 1.9.0
1)  down harbor instance #docker-compose down
2) take backup of harbor and database dir
3) untar 1.9.0 installer
4) edit harbor.yml file
5) installation - ./install.sh --with-clair

Could you please validate process and let me know if i missing something...... thanks

**Comment by dbenduga** [comment]
@reasonerjt .. one more thing.. Currently my 1.8.1 harbor is having almost 6TB data... does anybody face any issue while upgrade and how much time upgrade takes for such huge data

**Comment by barryz** [comment]
I have same problem when upgrading harbor from 1.7.6 to 1.9.0.

My workaround is push a new image to cover zero-size image.  If you have a large size (TB+) registry storage, I suggest you check and cover zero-size image before upgrading.

**Comment by wy65701436** [comment]
close it as the fix is in v1.9.2-rc1, all of the size 0 image are ignores during migration.
