### ISSUE TITLE
Harbor OIDC trust CA -  509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bilaloslo92** [goharbor/harbor#9347]
In Harbor 1.9.0 when configuring up OIDC authenticating and then selecting "verify certificate" the error given in the core.log is
```
Oct  9 14:28:05 192.168.32.1 core[16978]: 2019-10-09T12:28:05Z [ERROR] [/core/api/oidc.go:52]: Failed to verify connection: {URL:https://dex.domain.no VerifyCert:true}, err: Get https://dex.domain.no/.well-known/openid-configuration: x509: certificate signed by unknown authority
``` 
How can you configure trust to an certificate authority for the `harbor-core` container in the `harbor.yaml`?

**Comment by reasonerjt** [comment]
@bilaloslo92 there's a configuration in OIDC setting to skip the TLS verification while connecting to the oidc endpoint.

Given Harbor is packaged in docker image, currently there's no way to inject arbitrary cert into the truststore without rebuilding the image.

**Comment by bilaloslo92** [comment]
Hi @reasonerjt, It should be a option like it's for UAA authentication to point to a ca_bundle. Since encryption is very important for us, especially related to authenticating. Is this something that is going to be supported in the near future? We do not want to run without TLS with OIDC.

`harbor.yml`
``` 
# uaa:
#   ca_file: /path/to/ca
```

**Comment by reasonerjt** [comment]
Yes we do have plan to refine the configuration process to inject ca to all Harbor containers, but that's definitely not in the scope of 1.10

If you are extremely serious of TLS, why not use a valid CA to sign it :)

**Comment by DisasteR** [comment]
@reasonerjt are you going to address this issue now that we have passed v2 ?

**Comment by jdblack** [comment]
I'm sorry, but I'm a little confused about why this was closed  I've been doing through the docs and I can't find where  to provide a  cert for a private ca
