### ISSUE TITLE
Update the pull policy in project configuration to make it work with pluggable scanner

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9348]
Along with the work in pluggable scanner the severity in the scan report has changed, both in value and data type, we'll need to make sure the settings in the security policy in the project configuration still works.

And we will also need to consider the migration, that the policy set in previous versions has to work after migration to 1.10

**Comment by steven-zou** [comment]
I'd like to provide an interface method to get the severity with a compatible way.

**Comment by steven-zou** [comment]
Code merged, work has been done, close it.
