### ISSUE TITLE
Does it support multi-architecture images?

### ISSUE THREAD

**Issue by Iverson-lena** [goharbor/harbor#9353]
Does Harbor support the following dokcker commands:
**docker manifest inspect
docker manifest create
docker manifest push**

**Comment by xaleeks** [comment]
We have ongoing discussions to add support for this.

**Comment by xiaobing395845388** [comment]
which version will support  this?

**Comment by liuyunshu** [comment]
`
// ServeHTTP The handler is responsible for blocking request to upload manifest list by docker client,which is not supported so far by Harbor.
`
Why is this feature not supported?  Web portal is the reason?
