### ISSUE TITLE
Quota info in db may not deleted when project removed

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#9373]
What can we help you?

**Comment by reasonerjt** [comment]
we can introduce a tx in project deletion.

**Comment by reasonerjt** [comment]
To remove all such issues we may have to rework the data access layer and introduce an abstraction layer from DB.

**Comment by wy65701436** [comment]
@heww is it still exist in Harbor v2.0.0, and can you add some background about it? Like, at what kind of situation, the quote cannot be removed? And do we have any workaround for user to manual delete these quotas?

**Comment by heww** [comment]
Closed by #12707
