### ISSUE TITLE
LDAPS should be supported, and avoid cleartext password in api request

### ISSUE THREAD

**Issue by maxfunke** [goharbor/harbor#9379]
when setting up LDAP configuration, the api returns a 500 response code, when protocol prefix before the LDAP-server URL is `ldaps://`. Adding ldaps-port postfix `:636` also fails.

So I chose `ldap://myldapserver.tld`.

But then on login, my credentials (username, password) are sent in clear text (Request-FormData).

So it would be nice to have ldaps. And probably kind of hashing credentials in general.

**Comment by reasonerjt** [comment]
I believe we do support ldaps? @stonezdj

**Comment by maxfunke** [comment]
We retested it. A different cert did the job.
Thank you.
