### ISSUE TITLE
failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

### ISSUE THREAD

**Issue by wang-qiang** [goharbor/harbor#9382]
When I unzip harbor-offline-installer-v1.8.1.tgz package and run ./install.sh get this error:
failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

root@xxx#docker logs -f harbor-log
**sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
sudo: fatal error, unable to load plugins**
....

I searched everywhere for help still failed to solve the problem. Would you please help me fix this problem.
Thanks in Advance

The entire message as below:
#./install.sh 

[Step 0]: checking installation environment ...

Note: docker version: 19.03.2

Note: docker-compose version: 1.24.1

[Step 1]: loading Harbor images ...
Loaded image: goharbor/harbor-core:v1.8.1
Loaded image: goharbor/harbor-registryctl:v1.8.1
Loaded image: goharbor/redis-photon:v1.8.1
Loaded image: goharbor/notary-server-photon:v0.6.1-v1.8.1
Loaded image: goharbor/chartmuseum-photon:v0.8.1-v1.8.1
Loaded image: goharbor/harbor-db:v1.8.1
Loaded image: goharbor/harbor-jobservice:v1.8.1
Loaded image: goharbor/nginx-photon:v1.8.1
Loaded image: goharbor/registry-photon:v2.7.1-patch-2819-v1.8.1
Loaded image: goharbor/harbor-migrator:v1.8.1
Loaded image: goharbor/prepare:v1.8.1
Loaded image: goharbor/harbor-portal:v1.8.1
Loaded image: goharbor/harbor-log:v1.8.1
Loaded image: goharbor/notary-signer-photon:v0.6.1-v1.8.1
Loaded image: goharbor/clair-photon:v2.0.8-v1.8.1

[Step 2]: preparing environment ...
prepare base dir is set to /work/harbor-offline/harbor
Clearing the configuration file: /config/registry/config.yml
Clearing the configuration file: /config/db/env
Clearing the configuration file: /config/registryctl/env
Clearing the configuration file: /config/registryctl/config.yml
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/jobservice/env
Clearing the configuration file: /config/jobservice/config.yml
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/core/app.conf
Clearing the configuration file: /config/core/env
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Generated configuration file: /config/db/env
Generated configuration file: /config/jobservice/env
Generated configuration file: /config/jobservice/config.yml
loaded secret from file: /secret/keys/secretkey
Generated configuration file: /compose_location/docker-compose.yml
Clean up the input dir

[Step 3]: starting Harbor ...
Creating network "harbor_harbor" with the default driver
Creating harbor-log ... done
Creating harbor-db   ... done
Creating redis       ... done
Creating registry    ... done
Creating registryctl ... done
Creating harbor-core ... done
Creating harbor-portal     ... error
Creating harbor-jobservice ... 

Creating harbor-jobservice ... error

ERROR: for harbor-jobservice  Cannot start service jobservice: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for portal  Cannot start service portal: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused

ERROR: for jobservice  Cannot start service jobservice: failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused
ERROR: Encountered errors while bringing up the project.

# docker logs -f harbor-log
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
sudo: fatal error, unable to load plugins
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
sudo: fatal error, unable to load plugins
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
sudo: fatal error, unable to load plugins
...

**Comment by sunlianqiang** [comment]
execuate this can help 
```
sudo docker-compose restart 
````

**Comment by chendashu001** [comment]
@wang-qiang Have you solved it?

**Comment by studylin** [comment]
Have you changed the permission of /var/lib/docker? Try ' chmod -R 755 /var/lib/docker '.

**Comment by Levvy055** [comment]
Having same problem when restarting VS machine

**Comment by tomlankhorst** [comment]
Same issue: Ubuntu 18.04 with 5.3.18, Docker 19.03.6, compose 1.25.4. 

`docker-compose ps` shows that `harbor-log` is not started, it's _restarting_ instead.
`docker-compose logs log` shows a few errors.

1) sudo: setrlimit(RLIMIT_CORE): Operation not permitted
solved by adding the `SYS_RESOURCE` capability to the log service.
That didn't solve the issue though. 

2) `rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.1910.0 try https://www.rsyslog.com/e/2103 ]; rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)`
This issue boiled down to the log container having no read permission to the `common/config/log` files. Solved by `chowning`.

**Comment by islinwb** [comment]
@wang-qiang

**Comment by islinwb** [comment]
Had a similar issue. Check the file `/usr/lib/sudo/sudoers.so` in the docker images. `docker rmi` and reload images if the file's permission is not correct. It works in my case.

**Comment by gaocegege** [comment]
Had a similar issue. Solved by https://github.com/goharbor/harbor/issues/9382#issuecomment-611915390

**Comment by hp-caoy** [comment]
In my issue, I solved it by [this](https://kb.vmware.com/s/article/79497).
Just change the harbor-log image tag to goharbor/harbor-log:v1.10.3-dev

**Comment by inspur007** [comment]
使用docker logs -f harbor-log查看harbor-log日志：
WARNING: Error loading config file: /opt/platform/.docker/config.json: open /opt/platform/.docker/config.json: permission denied
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
rsyslogd: error writing pid file (creation stage)
: Permission denied
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)



solution：

# 导出harbor-log容器
mkdir -p /tmp/harbor-log
cd /tmp/harbor-log
docker export harbor-log -o harbor-log.tar

# 解压tar包
tar xvfp harbor-log.tar

# 修改shadow文件的值
sed -i 's/:90:/:99999:/g' /tmp/harbor-log/etc/shadow

# 将修改后的shadow文件挂载到harbor-log容器内
mkdir -p /opt/harbor-log-etc/
cp /tmp/harbor-log/etc/shadow /opt/harbor-log-etc/shadow

# 修改docker-composr.yml文件，harbor-log容器的volumes配置，增加以下配置
      - type: bind
        source: /opt/harbor-log-etc/shadow
        target: /etc/shadow
# 重启harbor即可
docker-compose down
docker-compose up -d

**Comment by LuChenjing** [comment]
> - type: bind
>     source: /opt/harbor-log-etc/shadow
>     target: /etc/shadow

按照这个操作但是还是没成功哎。

**Comment by xyzzen** [comment]
没成功 版本2.0

**Comment by pxvp2008** [comment]
> 没成功 版本2.0

`docker rmi <harbor>`，删掉所有镜像，然后 `docker-compose up -d`即可

**Comment by denganliang** [comment]
> 问题一：我的情况发生是这样子的，我的docker目录日志写满了，所以我更换了一下目录，然后重启后提示错误。 [failed to initialize logging driver: dial tcp 127.0.0.1:1514: connect: connection refused] 我的解决方法是，删除所有harbor镜像，重新拉取最新镜像即可解决上面问题。
> 
> 问题二：重启后发现还是有些容器一直在重启，restarting，错误提示均与权限有关系，这时候就需要看你的register目录里是不是目录权限设置有问题，是不是都是root权限？如果是请参照如下设置。
> 
> 还原后的数据一定要与备份时保持一致。许多用户在恢复数据后无法启动Harbor，而且日志里同时会有文件权限相关的错误信息，这极有可能就是备份数据的文件权限不正确导致的。 比如以下文件夹要设置成对应用户所属权限。
> 
> chown -R 10000:10000 ca_download chown -R 10000:10000 job_logs chown -R 10000:10000 registry chown -R systemd-bus-proxy:ssh_keys database chown -R systemd-bus-proxy:ssh_keys redis chown -R 10000:10000 chart_storage chown -R 10000:10000 secret/cert/
> 
> $ ll total 0 drwxr-xr-x 2 10000 10000 10 Jun 7 01:20 ca_download drwxr-xr-x 2 10000 10000 10 Jun 7 01:20 chart_storage drwx------ 3 systemd-bus-proxy ssh_keys 25 Jun 7 01:20 database drwxr-xr-x 2 10000 10000 10 Jun 7 01:20 job_logs drwxr-xr-x 2 systemd-bus-proxy ssh_keys 29 Sep 28 17:25 redis drwxr-xr-x 3 10000 10000 27 Jun 7 01:49 registry drwxr-xr-x 7 root root 91 Jun 7 01:20 secret drwxr-xr-x 4 root root 44 Jun 7 01:20 trivy-adapter
> 
> 参考链接：https://blog.51cto.com/lidabai/5275200

同样的情况，解决了，感谢

**Comment by freemankevin** [comment]
Caused by changes in the permissions of the logs path, it has been resolved.
```shell
cd $harbor_path
docker-compose down 
./prepare --with-trivy
./install.sh   --with-trivy
```

**Comment by fuomag9** [comment]
Still having this issue

**Comment by wenzhucjy** [comment]
cd harbor  && sudo find common/ -type f -exec chmod 0755 \{\} \;
