### ISSUE TITLE
Plug Custom Docker Authentication and Authorization Server to Harbor

### ISSUE THREAD

**Issue by chirangaalwis** [goharbor/harbor#9385]
**Description**:
We are currently evaluating how we can use Harbor as a private Docker registry.

As of now, we have custom, organization specific authentication and authorization logic, which has been plugged to the Docker Registry, which we are using. Please see [1] an informative guide written by @ThilinaManamgoda, on this topic.

Can we plug such a custom Docker Authentication and Authorization extension to Harbor? If yes, we would be grateful if you can provide use with appropriate documentation and guidelines to follow.

[1]: [Authorization for Private Docker Registry](https://medium.com/@maanadev/authorization-for-private-docker-registry-d1f6bf74552f)

**Comment by xaleeks** [comment]
Please describe on this ticket how you want to plug your custom authentication extension (and what it is) into Harbor.  @chirangaalwis

**Comment by ThilinaManamgoda** [comment]
@xaleeks Does the Habor Docker registry adhere to the Docker registry Token Authentication Specification[1]?

[1]https://docs.docker.com/registry/spec/auth/token/
