### ISSUE TITLE
Add webhook on repo level

### ISSUE THREAD

**Issue by cafeliker** [goharbor/harbor#9391]
In Harbor 1.9, it released a nice feature of webhook, and the existing webhook is on the project level; is it possible to add the webhook on repo level as well?

It will be more flexible, the different repo can point to the different webhook endpoint.

Thanks
ye

**Comment by xaleeks** [comment]
This was discussed during the design for Webhooks but we settled on project level as a good balance between granularity and complexity, and to be consistent with other features that are set at project level.  I'm curious, what is the organization or tenancy model that would have different endpoints for different repos like you described.
