### ISSUE TITLE
Enable LTS verify when the LDAP server using custom CA

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9396]
Current the LDAP server only trusted the LDAPS with trusted certificate,  need to provide a way to enable LDAP Verify Certificate when the LDAP using a customer cert.
Because there is an option in harbor.yml to install trusted_certificates in registry, clair, jobservice,  we need to insstall cert on core container too.
```
storage_service:
  ca_bundle: /<path of cert>/trusted_certificates.crt
```

BTW, to enable https proxy also requires to install certificate on the containers requires a proxy.

--------

We should move the trusted certificate config param to a general category other than storage_service

**Comment by stonezdj** [comment]
Once the core container add the certificate to trusted store, then it can be authenticated with LDAPS with Verify Cert enabled.

**Comment by anmo13** [comment]
@stonezdj Is there any planned release for this? we seem to be stuck at this requirement with our implementation of ldaps and harbor

**Comment by Drewster727** [comment]
@stonezdj  how do we get around this? I have a custom CA cert I need added so LDAP will work...
