### ISSUE TITLE
Harbor core fails to come up due to false upgrade check

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#9406]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Sometimes deploying harbor helm chart in k8s cluster may fail because Harbor core couldn't be ready due to false database upgrade check failure, and the core pod restarts when this happens.
Since this is a fresh Harbor install, the upgrade logic in harbor core shouldn't be triggered 

**Steps to reproduce the problem:**
Deploy Harbor helm chart with persistence as true in a k8s cluster

**Versions:**
Harbor v1.8.2

**Additional context:**
Relevant logs in Harbor core pod:

2019-10-11T22:32:32Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-harbor-452780493-harbor-database port-5432 databse-registry sslmode-"disable"
2019-10-11T22:32:32Z [INFO] [/common/dao/base.go:89]: Register database completed
2019-10-11T22:32:32Z [INFO] [/common/dao/pgsql.go:107]: Upgrading schema for pgsql ...
2019-10-11T22:32:32Z [ERROR] [/common/dao/pgsql.go:112]: Failed to upgrade schema, error: "Dirty database version 1. Fix and force version."
2019-10-11T22:32:32Z [FATAL] [/core/main.go:103]: failed to initialize database: Dirty database version 1. Fix and force version.

This happens intermittently, but when this happens, the harbor deployment could stuck there forever. Restarting the Harbor core pod or db pod doesn't seems to help probably because PVC stays the same with persistence set as true.

**Comment by reasonerjt** [comment]
Per investgation I believe this is b/c the `core` pod was restarted in the middle of migration, the latest release of helm chart extends the initialDelaySeconds of livenessProbe of core, which should mitigate such problem.

**Comment by jmf0526** [comment]
> Per investgation I believe this is b/c the `core` pod was restarted in the middle of migration, the latest release of helm chart extends the initialDelaySeconds of livenessProbe of core, which should mitigate such problem.

I also experienced this issue, the direct cause was that core container somehow got killed/restarted in the middle of migration. It doesn't happen very often in my env, and in dev environment I can just reinstall harbor from scratch.
I was wondering is there any official workaround, since we can not clear reinstall harbor if it happened in a production env.
