### ISSUE TITLE
Use robbot account for "harbor registry endpoint" to realize a replication

### ISSUE THREAD

**Issue by deschmih** [goharbor/harbor#9412]
### **Freature request:**
At the moment it's not possible to use a robot account from a harbor endpoint to replicate in a second harbor instance.

**More in detail:**
I use two harbor instances A and B. I want to realize a replication from instance A into instance B via a robot account form instance A.

see also:
https://cloud-native.slack.com/archives/CC1E09J6S/p1571032692025800

**Comment by burdzwastaken** [comment]
we are still seeing this issue when using a robot account:
```
2020-06-10T08:59:14Z [ERROR] [/replication/operation/controller.go:108]: the execution 60809 failed: failed to do the prepare work for pushing/uploading resources: http error: code 403, message {"code":403,"message":"Only system admin can create project"}
```
the above is when we try to replicate from `harbor.local0` > `harbor.local1` using the same project `test`.

**Comment by stranljip** [comment]
I am also having this problem. Is this simply not possible and the advised way is to use a technical user for this or is there something else to be observed?

**Comment by deschmih** [comment]
It is still not implemented. Feel free to join slack https://cloud-native.slack.com/archives/CC1E09J6S or contact @wy65701436 directly to propagate this feature request.
