### ISSUE TITLE
what is the password of harbor chartmuseum? admin Harbor12345 does not work

### ISSUE THREAD

**Issue by 13567436138** [goharbor/harbor#9417]
what is the password of harbor chartmuseum? admin Harbor12345 does not work

**Comment by 13567436138** [comment]
![image](https://user-images.githubusercontent.com/31508490/66817866-fce7c700-ef6e-11e9-9980-daef125e0616.png)

**Comment by 13567436138** [comment]
solved

**Comment by itsecforu** [comment]
how u solve it?
