### ISSUE TITLE
Task: CII badging req - safe transmission of crypto hash

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9421]
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req:  A cryptographic hash (e.g., a sha1sum) MUST NOT be retrieved over http and used without checking for a cryptographic signature.  

issue: does image digest qualify for this hash. Checking with CNCF right now.

**Comment by xaleeks** [comment]
discussing interpretation here: https://github.com/coreinfrastructure/best-practices-badge/issues/1346

**Comment by xaleeks** [comment]
in light of discussion in above thread, I propose we enforce https only in official Harbor installation and user guide. @reasonerjt @wy65701436 @steven-zou @ywk253100

**Comment by xaleeks** [comment]
after discussion CNCF members, we are tracking some changes to documentation here https://github.com/goharbor/harbor/pull/9508 to better reflect that we are already in compliance with this requirement.

**Comment by xaleeks** [comment]
Per discussion, we are making https the default mode for Harbor deployments and http as an alternate path after disclosing potential risks to user.

**Comment by reasonerjt** [comment]
will fix this in https://github.com/goharbor/harbor/issues/9525
