### ISSUE TITLE
Need document the proxy settings

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9422]
The previous proxy setting document should be updated
https://github.com/goharbor/harbor/blob/0f4cf892536af2ec473fd62643800f654dc02c66/docs/installation_guide.md

```
 no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair
 components:
    - core
    - jobservice
    - clair
```

The no_proxy, components are confusing to user. one is comma separated,  another is yaml list. 
Actually, the no_proxy is the target need to bypass the proxy. 
components is the container that should use the proxy (source)

**Comment by ruruiye** [comment]
this need to be reopend
