### ISSUE TITLE
Task: CII badging req - safe number generation

### ISSUE THREAD

**Issue by xaleeks** [goharbor/harbor#9423]
What can we help you?
> This issue is a sub-task of the CII badging to-do tasks epic (#9076)

Req:  The security mechanisms within the software produced by the project MUST generate all cryptographic keys and nonces using a cryptographically secure random number generator, and MUST NOT do so using generators that are cryptographically insecure

**Comment by xaleeks** [comment]
please check this @wy65701436

**Comment by xaleeks** [comment]
per discussion, there's no unsafe random number generation anywhere in harbor binary.  Exists only in UT tests.  Please double check this and then you can close this @wy65701436

**Comment by wy65701436** [comment]
I have checked the source code, we're using the cryptographically secure random number generator(golang and python official `rand` library). 

And for the UT test, we won't ship testing code in binary, so it can be ignored.

**Comment by xaleeks** [comment]
awesome thank you!
