### ISSUE TITLE
Configure email settings without user/password

### ISSUE THREAD

**Issue by AnatomicJC** [goharbor/harbor#9424]
Hi,

I deployed harbor in a private kubernetes cluster thanks to helm chart. I have a Google GSuite account for my company and mails are sent via `smtp-relay.gmail.com:587` without the need to use a user and password.
I set in GSuite admin an IP whitelist allowed to send mails.

It seems harbor try to authenticate with a user and password unless I left the settings blank, here is an extract from the core pod:

```
2019-10-15T11:46:10Z [ERROR] [/core/api/email.go:113]: failed to ping email server: 535 5.7.8 Username and Password not accepted. Learn more at 
[harbor-harbor-core-bc6b7b58c-c4kdd] 5.7.8  https://support.google.com/mail/?p=BadCredentials o34sm319515edd.8 - gsmtp
```

Can you help ?

Thanks,

**Comment by jmlms** [comment]
Duplicate of #6533 but still not addressed so far.
