### ISSUE TITLE
number of vulns increases each time clicking "SCAN" button

### ISSUE THREAD

**Issue by AkihiroSuda** [goharbor/harbor#9425]
**Expected behavior and actual behavior:**

The number of vulnerabilities increases each time clicking "SCAN" button: 3 (correct) -> 6 (wrong) -> 9...

![image](https://user-images.githubusercontent.com/9248427/66830810-552fc080-ef91-11e9-9cb4-256a91818bd7.png)

**Steps to reproduce the problem:**
Click SCAN button multiple times

**Versions:**

- harbor version: 1.9.1
- Chrome version: 77.0.3865.120

**Comment by AllForNothing** [comment]
@AkihiroSuda Please refresh the page to avoid this issue provisionally. It will be fixed in version 1.10.0. I'm closing it.
