### ISSUE TITLE
Edit project quota dialog label text dislocation

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9430]
In configuration -> Project Quota -> Edit 
![Screen Shot 2019-10-16 at 2 55 18 PM](https://user-images.githubusercontent.com/2696760/66895385-3b3fbd80-f025-11e9-9599-8850ac8a19d5.png)
It seems the count and storage are dislocated

**Comment by jwangyangls** [comment]
I can't reproduce the problem
