### ISSUE TITLE
Make sure the Artifact struct is moved out of /pkg/scan/...

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9433]
Currently it sits in `src/pkg/scan/rest/v1`

We should try our best to make the Artifact struct a core data structure shared accross the code base.

**Comment by ywk253100** [comment]
@heww Let's use the new `Artifact` model to replace it

**Comment by ywk253100** [comment]
The work can be covered by https://github.com/goharbor/harbor/issues/10068

**Comment by heww** [comment]
`v1.Artifact` will be retained, it will be used by core to submit scan job to job service.

I will change the scan controller so that `v1.Artifact` not appeared in it.

**Comment by heww** [comment]
Closed by #11001
