### ISSUE TITLE
Project list can't be loaded under GCS storage

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#9453]
When harbor registry storage is GCS,  after logging into harbor, project list can't be loaded, it's waiting all along.
  
![image](https://user-images.githubusercontent.com/44018302/66987268-09952800-f0f3-11e9-9c0c-24c560689bf9.png)

**Harbor Version**

![image](https://user-images.githubusercontent.com/44018302/66987637-bc658600-f0f3-11e9-97da-7f98607479ca.png)

**Comment by jwangyangls** [comment]
it has been  fixed
