### ISSUE TITLE
missing useful error for broken retention rule patterns 

### ISSUE THREAD

**Issue by rmalchow** [goharbor/harbor#9463]
**Expected behavior and actual behavior:**
when entering incorrect patterns in my retention rules, and then performing a dry run, i see a halfway decent error message ("syntax error in pattern") in the logs, however, in the UI, i only see an "internal server error" ... this i unnecessarily confusing. it is probably easy to display the actual error, and it would make for a mucher smoother user experience :)

**Steps to reproduce the problem:**
enter a garbage pattern in the retention rule "repo" pattern (in our case, we had the project name included, as in:   project/image ... 

**Versions:**
Please specify the versions of following systems.

- harbor version: goharbor/harbor-core:v1.9.0 - v1.9.0-d13cf448

**Comment by bitsf** [comment]
hi @rmalchow , sorry for late reply.
But I just didn't get what your test case is.
Do you mean you input something like this?
![image](https://user-images.githubusercontent.com/188115/68761259-aee9e000-064e-11ea-8f8d-3a9963a41182.png)
But I don't see any error.

**Comment by rmalchow** [comment]
@bitsf hi. yes. correct. but i am also unable to reproduce it now. basically, it did allow saving of broken rules, then during the dry run, it would abort. i checked our internal discussion, retried with the same settings (that reproducably failed before) and now it's fine. thank you, and sorry wasting your time.
