### ISSUE TITLE
Registry Endpoint - Test Connection not using credentials

### ISSUE THREAD

**Issue by joekohut** [goharbor/harbor#9464]
**Expected behavior and actual behavior:**
Expecting endpoint [Test Connection] to use provided credentials for harbor-replication-service ping test, but that does not appear to be the case. It appears credentials are not being used. Please advise.

>>> Credentials are supplied:

USING HARBOR ENDPOINT - TEST CONNECTION - "Failed to ping endpoint."
ACCESS ID: test
ACCESS SECRET: ******

REGISTRY NGINX PROXY LOG on Target Registry "pier" appears to show no credentials being passed:
2019/10/17 14:07:24 [info] 6#6: *14 **no user/password was provided for basic authentication**, client: x.x.201.48, server: pier.domain.com, request: "GET /v2/ HTTP/1.1", host: "pier.domain.com"
x.x.201.48 - - [17/Oct/2019:14:07:24 +0000] "GET /v2/ HTTP/1.1" 401 179 "-" "Go-http-client/1.1" "-" "-" "-" "-""pier.domain.com"
2019/10/17 14:07:24 [info] 6#6: *14 client x.x.201.48 closed keepalive connection
2019/10/17 14:07:24 [info] 6#6: *15 no user/password was provided for basic authentication, client: x.x.201.48, server: pier.domain.com, request: "HEAD /v2/ HTTP/1.1", host: "pier.domain.com"
x.x.201.48 - - [17/Oct/2019:14:07:24 +0000] "HEAD /v2/ HTTP/1.1" 401 0 "-" "harbor-replication-service" "-" "-" "-" "-""pier.domain.com"

>>> Using curl to test same endpoint with NO credentials shows same behavior:

curl -vk -X HEAD https://pier.domain.com/v2/
> HEAD /v2/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: pier.domain.com
> Accept: */*
>
< HTTP/1.1 401 Unauthorized

REGISTRY NGINX PROXY LOG:
2019/10/17 14:04:54 [info] 6#6: *11 no user/password was provided for basic authentication, client: x.x.201.48, server: pier.domain.com, request: "HEAD /v2/ HTTP/1.1", host: "pier.domain.com"

>>> Using curl WITH same ACCESS ID and ACCESS SECRET works, as shown, "**test**" account is being used:

curl -vk -X HEAD -u **test** https://pier000.dcextawssnd.massmutual.com/v2/

Enter host password for user 'test':
> HEAD /v2/ HTTP/1.1
> Authorization: Basic dGVzdDpkb2N...
> User-Agent: curl/7.29.0
> Host: pier.domain.com
> Accept: */*
>
< HTTP/1.1 200 OK

REGISTRY NGINX PROXY LOG:
x.x.201.48 - **test** [17/Oct/2019:14:06:30 +0000] "HEAD /v2/ HTTP/1.1" 200 0 "-" "curl/7.29.0" "-" "-" "Basic dGVzdDpkb2..." "-""pier.domain.com"

**Steps to reproduce the problem:**
Please verify credentials are being passed.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.0]
- docker engine version: [18.06.3-ce]
- docker-compose version: [1.23.2]

**Comment by joekohut** [comment]
Can someone verify this issue?

**Comment by joekohut** [comment]
still an open issue ... can anyone else please confirm issue - Harbor is not using credentials to test private Docker registry and therefore Replication does not work between Harbor and private registry

**Comment by ywk253100** [comment]
@joekohut Please check https://github.com/goharbor/harbor/issues/8211
