### ISSUE TITLE
Unable to use case-insensitive usernames in Harbor with external auth

### ISSUE THREAD

**Issue by pk89** [goharbor/harbor#9466]
If Harbor is configured to use external authentication source which is case-insensitive for usernames, Harbor does not recognize the case-insensitivity.

In typical usage, this issue manifests in the following way:
step 1) Add access on project for a user with username - admin@domain
step 2) login using Harbor UI with username - Admin@domain (different case)
login succeeds but no projects are visible.

**Comment by shreyasdarkin** [comment]
In my setup, Harbor is able to recognize case-insensitivity and listing all the projects related to it.

My Setup:-
- Configured LDAP to Harbor
- Gave access to many projects for a particular user with username - admin@domain
- Logged in using username - ADMIN@domain
- and able to see all the projects listed.

Can you give more details about your setup?

<img width="1680" alt="Screenshot 2019-10-23 at 3 24 50 PM" src="https://user-images.githubusercontent.com/53904384/67381821-27a6d080-f5aa-11e9-8bf5-c579ee3c7c97.png">
<img width="1679" alt="Screenshot 2019-10-23 at 3 25 04 PM" src="https://user-images.githubusercontent.com/53904384/67381823-27a6d080-f5aa-11e9-97f1-465827d4bad0.png">

**Comment by ericvmw** [comment]
This is reproducible with http_auth, might not be with LDAPm @shreyasdarkin

**Comment by reasonerjt** [comment]
Fixed in #9860 and #9746
