### ISSUE TITLE
duplicate CVESet in src/pkg/scan/ and src/common/models

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9471]
The CVESet in 
https://github.com/goharbor/harbor/blob/master/src/pkg/scan/report/summary.go#L28

duplicates with:
https://github.com/goharbor/harbor/blob/master/src/common/models/cve_whitelist.go#L41

Especially exporting it in `scan/report` package will cause future confusion.

**Comment by steven-zou** [comment]
@heww 

Please check if we can resolve this CVESet duplication definition in 2.0 as you're doing some refactor work now.
