### ISSUE TITLE
[doc-impact]immutable tag rule scenario on shared digest

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#9472]
As harbor deleted a tag by digest, it will delete all of tags with same digest.

We should document the following scenario:

1. set an immutable rule to match hello-world:v1 
2. retag hello-world:v1 to hello-world:v2, then to docker push to the same project
3. delete hello-world:v2 in the harbor

The v2 cannot be deleted as it shares digest with v1, which is an immutable tag matched by rules set by #1.

**Comment by xaleeks** [comment]
So just to be clear from a documentation POV, the end result is that none of the tags sharing a common digest will be deleted if only a single tag is configured as immutable.

**Comment by xaleeks** [comment]
this successfully made it into the 1.10 release

**Comment by stuclem** [comment]
Added this in https://github.com/goharbor/harbor/pull/10029/commits/e2278520fb54fae691dff52e33276325b5d043e9. 

@wy65701436 can you please take a look? Thanks!

**Comment by stuclem** [comment]
Approved by @wy65701436 via Slack
