### ISSUE TITLE
harbor return http code 502 When there are a large number of node call api

### ISSUE THREAD

**Issue by hellowordczy** [goharbor/harbor#9476]
**Versions**
### docker engine version:
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/amd64
 Experimental:    false
Git commit: c97c6d6
Built: Wed Dec 27 20:12:46 2017
OS/Arch: linux/amd64
Experimental: false

**Problem**
When k8s 100 nodes get tags of certain projects through api of /v2/{projectname}/tag/list from harbor  in the same time , i encounter problem that harbor return http code 502  in small amount.

See logs in below :

**log**
[ui.log]
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.194|#033[42m 200 #033[0m| 128.580885ms|   match|#033[44m GET     #033[0m /v2/release/Aproject/tags/list   r:/v2/*#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.188|#033[42m 200 #033[0m| 105.263315ms|   match|#033[44m GET     #033[0m /v2/release/Bproject/tags/list   r:/v2/*#033[0m
**Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 http: proxy error: dial tcp: lookup registry on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled
Oct 17 16:40:57 172.18.0.1 ui[32363]: message repeated 3 times: [ 2019/10/17 08:40:57 http: proxy error: dial tcp: lookup registry on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled]**
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.117.18|#033[42m 200 #033[0m|  770.23457ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |   10.0.87.92|#033[42m 200 #033[0m| 674.224692ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.155|#033[42m 200 #033[0m| 507.200641ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.156|#033[42m 200 #033[0m| 773.356643ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |    10.0.79.1|#033[41m 502 #033[0m|  34.122137ms|   match|#033[44m GET     #033[0m /v2/release/Cproject/tags/list   r:/v2/*#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.87.182|#033[41m 502 #033[0m|  89.225124ms|   match|#033[44m GET     #033[0m /v2/release/Cproject/tags/list   r:/v2/*#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.181|#033[41m 502 #033[0m|  68.314014ms|   match|#033[44m GET     #033[0m /v2/release/Bproject/tags/list   r:/v2/*#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.161|#033[41m 502 #033[0m|  68.099917ms|   match|#033[44m GET     #033[0m /v2/release/Cproject/tags/list   r:/v2/*#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.85.209|#033[42m 200 #033[0m| 419.911284ms|   match|#033[44m GET     #033[0m /service/token   r:/service/token#033[0m
Oct 17 16:40:57 172.18.0.1 ui[32363]: 2019/10/17 08:40:57 #033[1;44m[D] [server.go:2619] |  10.0.79.189|#033[42m 200 #033[0m|  71.759593ms|   match|#033[44m GET     #033[0m /v2/release/Bproject/tags/list   r:/v2/*#033[0m

[proxy.log]
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.87.197 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Cproject:pull,push HTTP/1.1" 200 1218 "-" "curl/7.29.0" 0.715 0.715 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.34 - "GET /v2/release/Bproject/tags/list HTTP/1.1" 200 72 "-" "curl/7.29.0" 0.178 0.178 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.188 - "GET /v2/release/Bproject/tags/list HTTP/1.1" 200 72 "-" "curl/7.29.0" 0.187 0.187 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.117.18 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Bproject:pull,push HTTP/1.1" 200 1212 "-" "curl/7.29.0" 0.827 0.827 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.85.209 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Cproject:pull,push HTTP/1.1" 200 1218 "-" "curl/7.29.0" 0.538 0.538 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.156 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Bproject:pull,push HTTP/1.1" 200 1212 "-" "curl/7.29.0" 0.836 0.836 .
****Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.1 - "GET /v2/release/Cproject/tags/list HTTP/1.1" _502_ 0 "-" "curl/7.29.0" 0.094 0.094 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.181 - "GET /v2/release/Bproject/tags/list HTTP/1.1" _502_ 0 "-" "curl/7.29.0" 0.101 0.101 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.161 - "GET /v2/release/Cproject/tags/list HTTP/1.1" _502_ 0 "-" "curl/7.29.0" 0.108 0.108 .**
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.87.92 - "GET /service/token?**account=admin&service=harbor-registry&scope=repository:release/Bproject:pull,push HTTP/1.1" 200 1212 "-" "curl/7.29.0" 0.715 0.715 .
**Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.87.182 - "GET /v2/release/Cproject/tags/list HTTP/1.1" _502_ 0 "-" "curl/7.29.0" 0.162 0.162 .**
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.155 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Bproject:pull,push HTTP/1.1" 200 1212 "-" "curl/7.29.0" 0.596 0.596 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.189 - "GET /v2/release/Bproject/tags/list HTTP/1.1" 200 72 "-" "curl/7.29.0" 0.220 0.220 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.85.228 - "GET /v2/release/Cproject/tags/list HTTP/1.1" 200 77 "-" "curl/7.29.0" 0.141 0.141 .
Oct 17 16:40:57 172.18.0.1 proxy[32363]: 10.0.79.28 - "GET /service/token?account=admin&service=harbor-registry&scope=repository:release/Cproject:pull,push HTTP/1.1" 200 1218 "-" "curl/7.29.0" 0.906 0.906 .

**Comment by reasonerjt** [comment]
Although you are using a pretty old build, I think there may be issues when Harbor handles certain number of current API calls which depending on registry API response.

**Comment by hellowordczy** [comment]
@reasonerjt Thanks for helping，we did following tests：
1 , Let ui component expose certain port (like 82) , thus we can bypass proxy component and use above method to call api of /v2/{projectname}/tags/list on port 82. We get error ui log  **same as above** , but do not get any error on registy.log ;
2 , Let registry component expose certain port (like 5000), thus we can bypass proxy and ui component and use above method to call api of /v2/{projectname}/tags/list on port 5000, we don`t get error log on registry.log
