### ISSUE TITLE
OIDC config cannot be reverted in gui after save. OIDC provisioned local accounts cannot be deleted from GUI

### ISSUE THREAD

**Issue by pks-ninja-labs-rw** [goharbor/harbor#9485]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

After I login with an OIDC user, Harbor creates a local user account for the OIDC client, as expected. 

Even logged in as admin, I cannot delete the OIDC provisioned user account, the option is grayed out. 

Also after saving the Configuration.Authentication.Auth_Mode as OIDC, the pulldown selector becomes grayed out, and I can no longer change the auth mode. 

You should be able to change these values or delete the OIDC account cache from the GUI. As a temporary workaround, is there a way to delete this user account or reset my auth-mode back to local database through the shell?

One specific problem the above limitations are causing for me is, I had to make a change to my OIDC provider, but harbor appears to attempt to log me into the OIDC provider using the old config which I suspect gets cached in harbor somewhere. So after updating my OIDC provider, I can no longer log in via OIDC, even though I was able to login via OIDC before. 

I am running Harbor 1.9

Thanks!

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ssimonek** [comment]
I have the same issue with harbor Version v1.9.3-c80751b8.
I don't use OIDC but LDAP provider. 
 - I can't delete users from gui even with admin account
 - I can't change the provider anymore

**Comment by J4lf** [comment]
I have the same issue as well with Version v1.10.0-6b84b62f

I can't change the provider anymore. When I upgrade my provider, the user is not recognized as the same user and Harbor is launching the onboarding process again.

**Comment by gunboe** [comment]
I have used LDAP, but I'd like to change for OIDC. Unfortally Auth Mode DropBox is Gray and I can not change from LDAP to any other.

What happen? How can I change the Auth Mode to others adapters to login en Harbor?

I use Harbor 1.9.4
