### ISSUE TITLE
Webhook events should include the URL of the repository in the Harbor portal

### ISSUE THREAD

**Issue by chgl** [goharbor/harbor#9487]
**Is your feature request related to a problem? Please describe.**
I am working on a Webhook integration for Zulip (see https://github.com/zulip/zulip/pull/13302). Currently, it is not possible to link back to the repository of a scanned/pushed/pulled/etc. image in the Harbor portal based on just the information in the Webhook event.

**Describe the solution you'd like**
Besides providing the `resource_url`, also provide a full `portal_url` as part of the event data.

**Describe the main design/architecture of your solution**
The Webhook data should be extended to include "human-clickable" links to both the repository and the resource.
```json
{
    "type": "deleteImage",
    "occur_at": 1571334977,
    "event_data": {
        "resources": [
            {
                "tag": "latest",
                "resource_url": "harbor.example.com/example/test:latest",
                "portal_url": "harbor.example.com/harbor/projects/2/repositories/example%2Ftest/tags/latest"
            }
        ],
        "repository": {
            "date_created": 1571333978,
            "name": "test",
            "namespace": "example",
            "repo_full_name": "example/test",
            "repo_type": "private",
            "portal_url": "harbor.example.com/harbor/projects/2/repositories/example%2Ftest"
        }
    },
    "operator": "admin"
}
```

**Comment by chgl** [comment]
Alternatively, opening the repository URL `harbor.example.com/example/test:latest` should redirect to the project's page. Thoughts?

**Comment by timabbott** [comment]
This issue is definitely still something that could be improved in Harbor's webhooks system.
