### ISSUE TITLE
Failed to upgrade schema, error : "Dirty database version 10. Fix and force version"

### ISSUE THREAD

**Issue by wphe** [goharbor/harbor#9509]
I'm trying to upgrade from version v1.8.0 to v1.9.0/v1.9.1 without success.
I have compiled my version following the documentation as usual but at the end of the compilation, core image is always restarting.

/var/log/harbor/core.log
`Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/native/adapter.go:44]: the factory for adapter docker-registry registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/harbor/adapter.go:42]: the factory for adapter harbor registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/googlegcr/adapter.go:31]: the factory for adapter google-gcr registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/awsecr/adapter.go:49]: the factory for adapter aws-ecr registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/aliacr/adapter.go:28]: the factory for adapter ali-acr registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/quayio/adapter.go:36]: the factory of Quay.io adapter was registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/helmhub/adapter.go:31]: the factory for adapter helm-hub registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/replication/adapter/gitlab/adapter.go:21]: the factory for adapter gitlab registered
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/controllers/base.go:289]: Config path: /etc/core/app.conf
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/main.go:177]: initializing configurations...
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/config/config.go:97]: key path: /etc/core/key
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/config/config.go:70]: init secret store
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/config/config.go:73]: init project manager based on deploy mode
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/config/config.go:142]: initializing the project manager based on local database...
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/core/main.go:181]: configurations initialization completed
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/common/dao/base.go:89]: Register database completed
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [ERROR] [/common/dao/pgsql.go:124]: Failed to upgrade schema, error: "Dirty database version 10. Fix and force version."
Oct 21 15:13:49 192.168.112.1 core[5868]: 2019-10-21T13:13:49Z [FATAL] [/core/main.go:188]: failed to initialize database: Dirty database version 10. Fix and force version.
Oct 21 15:13:52 192.168.112.1 core[5868]: 2019-10-21T13:13:52Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
`

Any idea how to solve this?

**Comment by reasonerjt** [comment]
was your 1.8.x env a fresh install?

**Comment by wphe** [comment]
No it's an upgrade from v1.7.4

**Comment by wphe** [comment]
I have upgraded to v1.8.4

**Comment by wphe** [comment]
Well I tried to upgrade from v1.8.4 to v1.9.1 but I still got a fatal error on the core container.
`Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/main.go:169]: initializing configurations...
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/config/config.go:98]: key path: /etc/core/key
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/config/config.go:71]: init secret store
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/config/config.go:74]: init project manager based on deploy mode
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/core/main.go:173]: configurations initialization completed
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/common/dao/base.go:89]: Register database completed
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [ERROR] [/common/dao/pgsql.go:124]: Failed to upgrade schema, error: "Dirty database version 10. Fix and force version."
Oct 24 14:39:06 192.168.48.1 core[4200]: 2019-10-24T12:39:06Z [FATAL] [/core/main.go:180]: failed to initialize database: Dirty database version 10. Fix and force version.
Oct 24 14:39:14 192.168.48.1 core[4200]: 2019-10-24T12:39:14Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
`

**Comment by jmf0526** [comment]
@wphe I got the same problem, did you solve it?

**Comment by wphe** [comment]
@jmf0526 I have done a fresh install and migrate the database to this new install. I haven't been able to find a solution.
