### ISSUE TITLE
adding ldap users into a project in Harbor workflow is not intuitive

### ISSUE THREAD

**Issue by mobla** [goharbor/harbor#954]
1)Version of docker engine and docker-compose - Harbor OVA 0.4.1.0
2)Config files of harbor, you can get them by packaging "Deploy/config" directory - attached
3)Log files, you can get them by the /var/log/harbor/ - attached

Live Harbor: 10.139.23.220 (ssh enabled), 
SSH: creds: root/VMware123!
UI: admin/Harbor12345

I have tried configuring with 2 or 3 LDAP servers and always I see this in docker_ui.log
"Current AUTH_MODE is db_auth". Not sure what am doing wrong!

Logs:
[2016-20-27.tar.gz](https://github.com/vmware/harbor/files/554742/2016-20-27.tar.gz)
[2016-20-26.tar.gz](https://github.com/vmware/harbor/files/554743/2016-20-26.tar.gz)

Config: [config.tar.gz](https://github.com/vmware/harbor/files/554737/config.tar.gz)

Attached the screenshot of LDAP configs.
![harbor-ldap](https://cloud.githubusercontent.com/assets/3538999/19750706/54fbc108-9ba8-11e6-9509-b360d7dab2e7.png)

**Comment by reasonerjt** [comment]
@mobla, so it seems the configuration didn't take effect, could you also provide /var/log/harbor/firstboot.log and /var/log/harbor/subsequentboot.log?

**Comment by ywk253100** [comment]
I have checked your environment, it works well. The user "admin" is reserved for managing Harbor and his authentication is done using database whether the auth_mode is db or ldap. So if you login with a LDAP user, you will get the "ldap_auth" in the logs.

**Comment by mobla** [comment]
I have to login admin and add AD/LDAP user to the project right?

**Comment by reasonerjt** [comment]
As we discussed, you need to first use the ldap user to login and then you can use admin to add that user.  I agree this workflow is not intuitive for now.

**Comment by mobla** [comment]
Workflow is little confusing to me. Let;s check with others and can improve..
1. Deploy Harbor OVA - during ovf deploy, configure LDAP auth (with ldap info)
At this point, my assumption was Harbor is configured with LDAP_Auth and not DB_Auth :-)
2. Post deployment, powered in (DHCP IP)
3. Login using seed admin (local db user) to create project and add LDAP - I thought so! 
4. But if we login as admin (local db user), system uses DB_Auth and doesn't let add LDAP users
5. Learnt that I have to login as say AD/LDAP admin user to add other Ldap users under a project in Harbor!

**Comment by reasonerjt** [comment]
This is no longer valid as the standalone .ova will not be supported.
