### ISSUE TITLE
Unable to deploy Harbor images in GKE  cluster

### ISSUE THREAD

**Issue by Shriyut** [goharbor/harbor#9557]
I'm trying to create a jenkins pipeline which will push an image to Harbor and deploy that image in GKE. The pipeline executes but as soon as I connect to the cluster and try out 'kubectl get pods' each pod of the deployment is stuck at imagePullBackOff error. I'm unable to understand how to fix this. I tried creating a secret file and attaching it to the yaml file but that didn't help either. I'm currently stuck at this part of my project and can't figure out how to troubleshoot this issue.

**Comment by Shriyut** [comment]
I configured Harbor in HTTP

**Comment by xaleeks** [comment]
did you resolve this issue following stone's advice?
