### ISSUE TITLE
The project related settings are exposed to the users with role <project admin 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9561]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

The project-related settings should not be exposed to the users with role <project admin 

**Steps to reproduce the problem:**

Login with guest role, check the settings

**Versions:**
Please specify the versions of the following systems.

- harbor version: [1.10]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**
 <NONE>

<img width="1013" alt="Screen Shot 2019-10-24 at 13 35 07" src="https://user-images.githubusercontent.com/5753287/67456380-1ff73280-f663-11e9-8b02-9df8be1a5e24.png">

**Comment by steven-zou** [comment]
@xaleeks 

Any thoughts?

**Comment by reasonerjt** [comment]
Let's see how does it block 1.10, I believe it has been working this way since 1.2
