### ISSUE TITLE
error when installing harbor1.9

### ISSUE THREAD

**Issue by situjianxiong** [goharbor/harbor#9562]
I'm trying to install harbor1.9, but there are errors happened.And I want someone can help me.
I untar the package and modifed harbor.yml.
**harbor.yml:**
certificate: /data1.9/cert/harbor.crt
private_key: /data1.9/cert/harbor.key
**file check**
[root@master harbor1.9]# ls -l /data1.9/cert/
total 16
-rw-r--r-- 1 root root   34 Oct 24 02:02 extfile.cnf
-rw-r--r-- 1 root root 1135 Oct 24 02:02 harbor.crt
-rw-r--r-- 1 root root  952 Oct 24 02:01 harbor.csr
-rw-r--r-- 1 root root 1679 Oct 24 02:01 harbor.key
[root@master harbor1.9]# 
**Here is what happened:**
[root@master harbor1.9]# ./prepare 
prepare base dir is set to /root/harbor1.9
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 32, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 91, in parse_yaml_config
    config_dict['cert_path'] = https_config["certificate"]
KeyError: 'certificate'

**Comment by situjianxiong** [comment]
i get it.

**Comment by LotteO** [comment]
What was the solution?

**Comment by githubzsy** [comment]
@situjianxiong 
我也遇到了这个问题，兄弟你是怎么解决的？

**Comment by githubzsy** [comment]
> @situjianxiong
> 我也遇到了这个问题，兄弟你是怎么解决的？

换到1.9.3版本，好了，可能是兼容问题？

**Comment by githubzsy** [comment]
> What was the solution?

change to version 1.9.3
