### ISSUE TITLE
permission scope of robot account is not at repository level

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9565]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

permission scope of robot account should be at the repository level

**Steps to reproduce the problem:**

At any project, navigate to the robot account tab, generate one, use it pull content

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by xaleeks** [comment]
why should it be at the repository level? @steven-zou

**Comment by xaleeks** [comment]
we had project level robots, and now we are adding system level robots. That will be all for now
