### ISSUE TITLE
Document that all releases include the tgz.asc key

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9568]
Per https://github.com/goharbor/harbor/pull/9551

**Comment by stuclem** [comment]
See also https://github.com/goharbor/harbor/issues/9086

**Comment by xaleeks** [comment]
This has been successfully incorporated into our release procedure

**Comment by stuclem** [comment]
An attempt to document this is in https://github.com/goharbor/harbor/pull/10029/commits/1aba0723bea5eca3dcce02d89982d01aa402b857. @wy65701436 can you please take a look? Thanks!

**Comment by stuclem** [comment]
Updated version is at https://github.com/goharbor/harbor/blob/sclements-1.10-doc-updates/docs/installation_guide.md#download-and-unpack-the-installer. 

@wy65701436 and @bitsf can you please take a look?

**Comment by stuclem** [comment]
Approved by @wy65701436 in https://github.com/goharbor/harbor/pull/10029.
