### ISSUE TITLE
Document limited guest role

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9569]
Per https://github.com/goharbor/harbor/issues/8632.

**Comment by stuclem** [comment]
Updated doc and screencaps in https://github.com/goharbor/harbor/pull/10029/commits/558ac7763066f7716089d3d188c45df78824f61d.

**Comment by xaleeks** [comment]
This did successfully make it into 1.10 release

**Comment by stuclem** [comment]
Doc update has been reviewed in https://github.com/goharbor/harbor/pull/10029. Closing as fixed.
