### ISSUE TITLE
Document that self registration is not enabled by default any more

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9570]
Per https://github.com/goharbor/harbor/issues/9392.

**Comment by xaleeks** [comment]
this still needs doc

**Comment by stuclem** [comment]
@xaleeks this is now documented in https://github.com/goharbor/harbor/pull/10029/commits/a0172707d5d0b58ade3efeabc65e15234d3951e8.

**Comment by xaleeks** [comment]
This looks right , please also help review @stonezdj

**Comment by stuclem** [comment]
Doc updated merged in https://github.com/goharbor/harbor/pull/10029.
