### ISSUE TITLE
Document immutable repositories

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9572]
Per https://github.com/goharbor/harbor/issues/3413.

**Comment by stuclem** [comment]
See also https://github.com/goharbor/harbor/issues/9230

**Comment by xaleeks** [comment]
this did make it into the 1.10, I already saw this section in the user guide PR

**Comment by stuclem** [comment]
Reviewed by @wy65701436 in https://github.com/goharbor/harbor/pull/10029
