### ISSUE TITLE
Document that Harbor will not block pulling an image with "negligible" severity

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9573]
Per https://github.com/goharbor/harbor/issues/7207

**Comment by xaleeks** [comment]
this was successfully implemented in 1.10

**Comment by stuclem** [comment]
@xaleeks I added this in https://github.com/goharbor/harbor/pull/10029/commits/c3d23dc5470cbdf7de224a9d5d7e83554acbdc7c

**Comment by xaleeks** [comment]
lgtm!

**Comment by stuclem** [comment]
Thanks @xaleeks. Closing as fixed.
