### ISSUE TITLE
Document that you can use 'memberOf' key like LDAP when using OIDC

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9574]
Per https://github.com/goharbor/harbor/issues/8017

**Comment by xaleeks** [comment]
We have successfully added group support

**Comment by stuclem** [comment]
Attempted to document something about this in https://github.com/goharbor/harbor/pull/10029/commits/23744796dc712582b1856e1e49b70132c95b1e42, by copying the `memberof` info from LDAP to OIDC. I am pretty sure that this is not sufficient. 

@xaleeks  @reasonerjt can you please take a look?

**Comment by stuclem** [comment]
@reasonerjt the OIDC docs definitely need a review, even if https://github.com/goharbor/harbor/pull/10029 is already merged.

https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#configure-your-oidc-provider
