### ISSUE TITLE
Document that robot account can delete images in a project

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9576]
Per https://github.com/goharbor/harbor/issues/8248

**Comment by xaleeks** [comment]
@stuclem fyi this did not make it into our 1.10 release, you can close this

**Comment by stuclem** [comment]
Thanks @xaleeks - will it come back in a future release?

**Comment by xaleeks** [comment]
I need to verify, most likely yes

**Comment by stuclem** [comment]
OK, in that case I'll leave it in backlog.
