### ISSUE TITLE
Document that user can create and submit their own CLI secret

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9577]
Per https://github.com/goharbor/harbor/issues/7932

**Comment by xaleeks** [comment]
This was successfully implemented in 1.10, I didn't see documentation on this yet in the user guide @stuclem

**Comment by stuclem** [comment]
Fixed in https://github.com/goharbor/harbor/pull/10029/commits/436686d819903be03b1dd95ec78221be3723c8cb.

@reasonerjt can you please take a look?

**Comment by stuclem** [comment]
Doc update is in #10029.
