### ISSUE TITLE
How to use Harbor both inside and outside of Kubernetes

### ISSUE THREAD

**Issue by qianzhangxa** [goharbor/harbor#9582]
**Expected behavior and actual behavior:**
I am running Kubernetes v1.15.5 cluster and I deployed Harbor 1.9.1 in the cluster via https://github.com/goharbor/harbor-helm, Harbor is exposed as an ingress. Now I can successfully push images from a host outside the Kubernetes cluster to Harbor (`core.harbor.domain`) via the Harbor ingress. But how can I push and pull image to Harbor from a pod (e.g., [Kaniko](https://github.com/GoogleContainerTools/kaniko)) inside the Kubernetes cluster? The Harbor ingress domain `core.harbor.domain` cannot be resolved in any pods, so I tried to launch a pod to directly push an image to the `harbor-core` service which is of clusterIP type:

```
$ kubectl get service
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
harbor-harbor-core            ClusterIP   10.255.244.199   <none>        80/TCP                    4h29m
...
```
But it still failed because the token service is still `core.harbor.domain` which cannot be resolved in the pod. And actually even it worked this is still not a desired solution because there is no TLS enabled for the `harbor-core` service (it only serves on 80 port).

So is there a way to use Harbor both inside and outside of Kubernetes cluster?

**Comment by neo502721** [comment]
Hi, maybe you can use HostAliases add a DNS record to your pod.
like this
`apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "xx.xx.xx.xx"    
    hostnames:
    - "core.harbor.domain"
  containers:
  - name: cat-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"`

ref: https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by qianzhangxa** [comment]
Thanks @neo502721! Actually I thought about it before, but I think there may be two issues with your solution.
1. I need to update the spec of all my pods which may not be desirable.
2. IIUC correctly, the `hostAliases.ip` is the IP address of Harbor ingress, but if it is possible the IP address is changed in the runtime, that means I need to update all my pods which may not be possible.

**Comment by reasonerjt** [comment]
@qianzhangxa you should update hostnames in values.yaml, actually the chart will propagate that value to different components.

BTW if you are reporting chart specific issue, please open issue on the repo goharbor/harbor-helm.

**Comment by qianzhangxa** [comment]
Although I used https://github.com/goharbor/harbor-helm to install Harbor, I think this is a generic requirement for Harbor, because building and pushing image to registry in container and pulling the image to start container on the worker node is a pretty common use case for CI/CD.

**Comment by ywk253100** [comment]
Actually it's the capability of your underlying infrastructure, it isn't related with Harbor, you have to make sure the ingress domain is a resolvable domain name. 
A few options:
1. Add the ingress domain to your own DNS
2. Use the public DNS service, such as xip.io, but it isn't stable
3. Expose Harbor service with node port

**Comment by qianzhangxa** [comment]
@ywk253100 Thanks for your suggestion.

Actually I have already added the ingress domain `core.harbor.domain` to the `/etc/hosts` file on each of my worker nodes, so the worker node can now push and pull image. But for the pods launched in my Kubernetes cluster, it cannot resolve `core.harbor.domain` since `core.harbor.domain` will not handled by CoreDNS. Did you mean I need to somehow make CoreDNS can handle `core.harbor.domain`?

**Comment by ywk253100** [comment]
No, not the `CoreDNS`, it's the DNS server in your internal network. 
If you cannot solve it in your own DNS server, I suggest you to use the option 3:  Expose Harbor service with node port.

As I mentioned it's the capability of your underlying infrastructure, I'm closing this issue.
