### ISSUE TITLE
1.9.1 Always prompt password user name error

### ISSUE THREAD

**Issue by xiaosige-facai** [goharbor/harbor#9597]
After installing 1.9.1, log in to the web page with admin, the user name or password is always displayed incorrectly, but I did not change the original password (Harbor12345). How to solve this problem?

**Comment by wy65701436** [comment]
is it a fresh install or upgrade from previous?

**Comment by demobin8** [comment]
> is it a fresh install or upgrade from previous?
same issue here, fresh install
