### ISSUE TITLE
Update docs for Enterprise PKS Tile for Harbor 1.9.x

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9598]
Some options have moved around in the tile, and new ones have been added, so this requires a bit of rewriting of the install and upgrade docs:

https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-harbor-registry/GUID-installing.html
https://docs.vmware.com/en/VMware-Enterprise-PKS/1.5/vmware-harbor-registry/GUID-upgrading.html

**Comment by stuclem** [comment]
@xaleeks @reasonerjt I have a question about the new Logging section in the Harbor tile. Do we need to do anything on the vRealize Log Insight side after configuring the vRLI server in the tile? Do we need to copy any certs or anything into vRLI? Thanks!

**Comment by xaleeks** [comment]
@ninjadq Hi Deng qiang, please help test integration with vRealize Log Insight.

**Comment by xaleeks** [comment]
We added support for syslog but did we ever test integration with log insight on tile? @stonezdj

**Comment by ninjadq** [comment]
I am not sure if there is an agent id in harbor tile env. I'll test wavefront integration of harbor tile

**Comment by stuclem** [comment]
Moved this issue to https://github.com/vmware/harbor-tile/issues/53, per request from @stonezdj. Closing this one.
