### ISSUE TITLE
[OIDC] Conflict in username, the user with same username has been onboarded.

### ISSUE THREAD

**Issue by annProg** [goharbor/harbor#9600]
**Expected behavior and actual behavior:**
Second user login with oidc will see `Conflict in username, the user with same username has been onboarded.`

harbor-core log:

```
2019-10-25T09:51:21Z [DEBUG] [/core/controllers/oidc.go:178]: User info string: {"iss":"https://oidc.scloud.xx.com","sub":"CgRoZWFuEglsZWNvbW1vbnM","name":"john","email":""}
2019-10-25T09:51:21Z [ERROR] [/common/dao/oidc_user.go:135]: fail to insert user, pq: duplicate key value violates unique constraint "harbor_user_email_key"
2019/10/25 09:51:21 [D] [server.go:2774] |   10.58.102.45| 409 |    6.83201ms|   match| POST     /c/oidc/onboard   r:/c/oidc/onboard
2019-10-25T09:51:25Z [DEBUG] [/core/filter/security.go:227]: OIDC CLI modifier only handles request by docker CLI or helm CLI
2019-10-25T09:51:25Z [DEBUG] [/core/filter/security.go:442]: can not get user information from session
2019-10-25T09:51:25Z [DEBUG] [/core/filter/security.go:511]: user information is nil
2019-10-25T09:51:25Z [DEBUG] [/core/filter/security.go:525]: using local database project manager
2019-10-25T09:51:25Z [DEBUG] [/core/filter/security.go:527]: creating local database security context...
```

It say `duplicate key value violates unique constraint "harbor_user_email_key"`, and the email of first user login with oidc is empty. （Second user's email is empty too: `User info string: {"iss":"https://oidc.scloud.xx.com","sub":"CgRoZWFuEglsZWNvbW1vbnM","name":"john","email":""}` )

oidc claims with email address

```
Claims:

{
  "iss": "https://oidc.scloud.xx.com",
  "sub": "CgRoZWFuEglsZWNvbW1vbnM",
  "aud": "example-app",
  "exp": 1572085737,
  "iat": 1571999337,
  "at_hash": "B3Ipt0n9usQscDA4d-jjZw",
  "email": "john@qq.com",
  "email_verified": true,
  "name": "john"
}
```

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by annProg** [comment]
Solved it myself.

OIDC Scope should be  `openid,offline_access,profile,email`

**Comment by annProg** [comment]
Maybe we can consider always sending `profile` and `email` scope

**Comment by jsimomaa** [comment]
I'm experiencing the same situation - when OIDC user is onboarded from GitLab the email address is empty (`""`). When another user tries to onboard the following error message is shown:

![image](https://user-images.githubusercontent.com/4503494/67701228-3fba8d80-f9b8-11e9-8a87-325dff73bdc7.png)

**Comment by morganatkinspa** [comment]
I think this issue will be fixed in #9820

**Comment by aminealaouiecherif** [comment]
I occur the same issue on harbor while onboarding users

**Comment by jbviout** [comment]
Same issue on harbor 1.9.3.

**Comment by RyuBAI** [comment]
Same here in 1.10

**Comment by yue-wen** [comment]
### Get this error, when change OIDC domain.
Error message:
"Conflict in username, the user with same username has been onboarded."

**Step to reproduce**:
* set up OIDC config with endpoint example: https://auth.oidc-old-domain.com/auth/realms/registry
* login some user via OIDC
* change oidc domain, example: https://auth.oidc-new-domain.com/auth/realms/registry
* update OIDC config with new endpoint
* re-login same user of step 2  

**Workaround to fix this case**
* Connect to harbor database `registry`
* find table `oidc_user` 
* change old OIDC endpoint of row `subiss` to new endpoint
