### ISSUE TITLE
 Unorganized error warning --test   immutable

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#9603]
I have created an immutable-tag ,and push images,  when delete an image that has contact with immutable tag , it can not delete  this image, it is right ,but  the error message is wrong

![image](https://user-images.githubusercontent.com/29826789/67648669-5689c180-f971-11e9-96fb-fcadccb31d0d.png)

**Comment by wy65701436** [comment]
UI has to handle this kind of error format at it's for docker client, which returned by immutable middleware.
