### ISSUE TITLE
Can you please merge this commit to release-1.8

### ISSUE THREAD

**Issue by hyy0322** [goharbor/harbor#9616]
https://github.com/goharbor/harbor/issues/9455
Hello, can you merge this commit to release-1.8?
As you know, most harbor user don't use the newest version.There are lots of users using old version such as 1.4 1.7 1.8 in product environment.Due to complicated reasons,it is not easy to upgrade the harbor version in product environment.

**Comment by ywk253100** [comment]
@hyy0322 We'll cherry pick the fix into 1.8

**Comment by hyy0322** [comment]
thanks

**Comment by ywk253100** [comment]
Done by https://github.com/goharbor/harbor/pull/9656
