### ISSUE TITLE
busybox not support internal image repository

### ISSUE THREAD

**Issue by bottlelee** [goharbor/harbor#9617]
**Expected behavior and actual behavior:**
Expected: pull busybox image from internal repository
Actual: Could not defined in chart values file

**Versions:**
- harbor version: [1.2.0+]

**Additional context:**
In the 'database/database-ss.yaml' file, busybox image url is a static value.
It should like the others, use 
`{{ .Values.busybox.internal.image.repository }}:{{ .Values.busybox.internal.image.tag }}`

**Comment by ywk253100** [comment]
There is already a PR https://github.com/goharbor/harbor-helm/pull/412 try to fix this issue, but the solution provided isn't a correct one. As I mentioned in the comment of the PR, we can provide some configuration items in `values.yaml` for the init container. Any interests to submit a fix for this?
