### ISSUE TITLE
oidc auth setup unsuccessful

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor#9630]
Installed Harbor using helm chart version 1.2.1 and was able to login as admin successfully. Tried to set up oidc auth mode. Entered all the required info from our OIDC provider. When clicking on "TEST OIDC SERVER", the UI says "failed to verify connection" and in core container log it says:

Failed to verify connection: {URL:https://xxxx/affwebservices/CASSO/oidc/harbor VerifyCert:false}, err: 404 Not Found: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body>HTTP Status 404 – Not Found<p><b>Type</b> Status Report</p><p><b>Message</b> Bad request.</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p></body></html>
2019-10-28T19:35:18Z [ERROR] [/common/api/base.go:68]: POST /api/system/oidc/ping failed with error: {"code":400,"message":"failed to verify connection"}

And the OIDC server never gets the request. If going from the browser using the same end point URL plus additional parameters required, it actually redirects the user to the SSO login page as expected.

**Comment by shen3lu4** [comment]
issue with our OIDC server setting. not a Harbor issue.

**Comment by TarikDjebien** [comment]
Hi @shen3lu4 
I'm facing exactly same error, what did you do on your OIDC server setting to make it works ?
Thanks for feedbacks

**Comment by shen3lu4** [comment]
On SSO side,  there is a configuration option called  "well known URL" . That needs to be enabled.
