### ISSUE TITLE
EOF error occurred when submitting scan request to scanner

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9635]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Submit scan requests in the scan job may meet `EOF` error but it should not.

>Oct 28 15:50:37 192.168.176.1 jobservice[1185]: 2019-10-28T15:50:37Z [ERROR] [/pkg/scan/job.go:138]: scan job: submit scan request: v1 client: submit scan: Post http://clair-adapter:8080/api/v1/scan: EOF
Oct 28 15:50:37 192.168.176.1 jobservice[1185]: 2019-10-28T15:50:37Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'IMAGE_SCAN:bf9e2cdcf5447a5e92c6d378' exit with error: scan job: submit scan request: v1 client: submit scan: Post http://clair-adapter:8080/api/v1/scan: EO

**Steps to reproduce the problem:**

Trigger scan action with a fresh installation.

**Versions:**
Please specify the versions of the following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

A possible reason may be some configurations of the HTTP client/server, e.g: ilde timeout.

**Comment by steven-zou** [comment]
Check issue at Clair adapter repo: https://github.com/goharbor/harbor-scanner-clair/issues/7

**Comment by steven-zou** [comment]
PR is submitted for review: https://github.com/goharbor/harbor-scanner-clair/pull/8

MV to SP73

**Comment by heww** [comment]
Closed by https://github.com/goharbor/harbor/pull/9847
