### ISSUE TITLE
The Projects page doesn't response when project API response time = 11s 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9638]
After replicate some docker images from docker Hub, total size about 1.2T, the project API response time is about 11 seconds, then the "Projects" page doesn't have any response. this issue can be reproduced in Harbor 1.8, 1.9
![Screen Shot 2019-10-29 at 1 18 28 PM](https://user-images.githubusercontent.com/2696760/67743502-d723ed00-fa59-11e9-8bae-5a7fa0036060.png)

**Comment by reasonerjt** [comment]
Let's check if it's because the backend is s3

**Comment by heww** [comment]
It is very complex for this issue, in one word this is the limited of chartmuseum.

In the `/api/projects` API, harbor will request the API `/{repo}/index.yaml` of chartmuseum to get charts count of the project when chartmuseum was installed with harbor.

Everything will be ok except that there is a project named `docker` in harbor and `S3` was selected as storage. 

In this case,  when request `/docker/index.yaml` of chartmuseum, chartmuseum will list all objects in S3 bucket at prefix `/docker` to compute its charts in the repo.  

But, unfortunately, `{rootdirectory}/docker/registry/v2` was used by `distribution` to store images, the more images exist in harbor, the slower to request `/docker/index.yaml` of chartmuseum. 

It will take about 60 seconds to list objects at prefix `/docker` when the total size of `/docker` is 1.1 TiB. The timeout in harbor to request APIs of chartmuseum is 10 seconds, so the `/api/projects` API of harbor is about 11 seconds as mentioned in this issue.

Maybe to fix this issue, we need to let chartmuseum use different directory (storage)  than `distribution`  as we do in the local storage service.
