### ISSUE TITLE
Support retaining some tags while deleting others

### ISSUE THREAD

**Issue by moshloop** [goharbor/harbor#9642]
As per the docs 

> WARNING: Due to native Docker tag deletion behavior, there is an issue with the current 
> retention policy implementation. If you have multiple tags that refer to the same SHA digest, 
> and if a subset of these tags are marked for deletion by a configured retention policy, all of the 
> remaining tags would also be deleted. This violates the retention policy, so in this case all of 
> the tags are retained. This issue will be addressed in a future update release, so that tag 
> retention policies can delete tags without deleting the digest and other shared tags.

**Comment by steven-zou** [comment]
It will be fixed in the upcoming V2.0 as we have already decoupled the digest and its related tags in 2.0.

@moshloop 

Please stay tuned on 2.0.

I'll close this issue to avoid duplicate things.
