### ISSUE TITLE
Override option is not working in retag API

### ISSUE THREAD

**Issue by saravanan30erd** [goharbor/harbor#9645]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior**
`/repositories/{repo_name}/tags - Retag an image
{
  "tag": "test1",
  "src_image": "test",
  "override": true
}

It should override the `test` tag, then it will be single tag `test1` for the image.

**Current behavior**
Even if we set override option to true, it is not working and its keeping the old tag `test`

- harbor version: [1.7.2]

**Comment by neo502721** [comment]
hi, your src_image format is wrong，it should be  "{repo_name}:tag", 
e.g.
```
{
  "override": true,
  "src_image": "test/test:v1.1.10",
  "tag": "test"
}
```
this will be change  images test/test's tag from v1.1.10 to test

**Comment by saravanan30erd** [comment]
@neo502721  actually I was using `{repo_name}:tag` format only, just didn't mention that in above example.  `override` option is not working and it keeps the old tag `test` and creates new tag `test1`.

**Comment by saravanan30erd** [comment]
Since override option keeps old tag, we can't even delete the old tag because if you remove the old tag then it removes both old and new tag.
