### ISSUE TITLE
Harbor Scanning is reporting many vulnerabilities unknown when they should be high or medium

### ISSUE THREAD

**Issue by tmojlupo** [goharbor/harbor#9651]
I have 2 instances of Harbor that were originally built off of the same helm chart (1.1.2, but then updated images to 1.8.3).  One properly scans and categorizes the vulnerabilities and the other does not.  I have attempted to update the one that isn't working to the 1.2.1 helm chart running Harbor 1.9.1, but the issue still exists.  As you can see, these are the same image in the 2 different instances.  Both see the same number of packages, but one is not categorizing properly.

<img width="1090" alt="good-harbor" src="https://user-images.githubusercontent.com/37086489/67815417-4232eb00-fa7d-11e9-9e92-dd76d544a9a6.png">
<img width="983" alt="bad-harbor" src="https://user-images.githubusercontent.com/37086489/67815419-42cb8180-fa7d-11e9-8f89-939cdd6a1723.png">

**Comment by reasonerjt** [comment]
@tmojlupo this is related to #9677

**Comment by reasonerjt** [comment]
Closing as my PR in Clair is merged this will be fixed after bumping up Clair, and that part of work will be tracked by #9677
