### ISSUE TITLE
Blob Unknown in Harbor version 1.9 , where push Fails

### ISSUE THREAD

**Issue by ksantoshpink** [goharbor/harbor#9667]
Harbor Push Fails with the blob unknown, below is the errors which has been found with the logs of the registry.

 level=error msg="response completed with error" auth.user.name=shayada err.code="blob unknown" err.detail=sha256:fcafeb17551f25567ba0a40c53103f3fbfb8fcc97a72929c05c1be994819903f err.message="blob unknown to registry" go.version=go1.11.8 http.request.host=registry.com http.request.id=9011cca9-87a1-47ca-b57e-7563025463ed http.request.method=HEAD http.request.remoteaddr=5.12.1.2 http.request.uri="/v2/test/harbor-log/blobs/sha256:fcafeb17551f25567ba0a40c53103f3fbfb8fcc97a72929c05c1be994819903f" http.request.useragent="docker/18.09.7 go/go1.10.7 git-commit/2d0083d657f8 kernel/4.4.180-94.100-default os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.7 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9.911257ms http.response.status=404 http.response.written=157 vars.digest="sha256:fcafeb17551f25567ba0a40c53103f3fbfb8fcc97a72929c05c1be994819903f" vars.name="test/harbor-log"

**Comment by ksantoshpink** [comment]
our production environment is behind the ELB, where its been configured with https. where above logs i see it sends back the http request to the registry.com
i have configured the external_url

**Comment by ksantoshpink** [comment]
a91a6294fd28: Pushed 
5e3bf5471bbd: Pushed 
f297a88236e6: Pushing [==================================================>]   49.1MB/49.1MB
b80136ee24a4: Pushing [==================================================>]  33.45MB/33.45MB
unknown blob

**Comment by ninjadq** [comment]
What is your load balance policy in your ELB?
