### ISSUE TITLE
Allow using multiple Scanners

### ISSUE THREAD

**Issue by l0nax** [goharbor/harbor#9687]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Since #6234 the User can an additional Scanner (eg _anchore_), but it would be nice to choose if the User wants only _one_ Scanner or multiple Scanners to use, eg. using _Clair_ **and** _Anchore_.
This is because – sometimes – one Image-Scanner has more Data-Feeds available so it can detect more Vulnerable Packages in an Image than another Scanner.

**Describe the main design/architecture of your solution**
After all Scanners are finished with Scanning, Harbor can merge the (JSON?) Scanning-Results into one final "Report". So this will end up in a more accurate Scan Result because multiple Scanners are used which may differ in their Results.

**Describe the development plan you've considered**
–

**Additional context**

Related to #6234

**Comment by wernerb** [comment]
Hi this is quite a nice feature. I am not sure why it does not get any traction.
We'd like to have multiple scanners have a go at finding vulnerabilities and possibly have linters like Dockle running.
