### ISSUE TITLE
Inconsistent error handling

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9704]
As we move to `go 1.13` with introduction of change in `errors` package, we should refine the error handling in the code

Some problems that are observed:
1. The package `github.com/goharbor/harbor/src/pkg/scan/errs` has overlaps and should be replaced by the new `errors` package
2. Usage of Error in `github.com/goharbor/harbor/src/common/http` in lower level is confusing.
3. Usage of `Wrap()` in `github.com/pkg/errors`, this can also be replaced by `errors` package.

**Comment by steven-zou** [comment]
As we discussed, let's use the error package src/internal/errors to replace the old error packages after adding the following methods to new errors for compatibilities

- `errors.Wrap(error,message)`
- `errors.New(message)`
- `errors.Errorf(format, args ...)`

**Comment by reasonerjt** [comment]
Will only cover item 1 and 2 in 2.0.0
