### ISSUE TITLE
"excluding x**" rule was not allowed in both Immutability rule and tag retention rule edition 

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#9706]
In edition of Immutability rule or tag retention rule, when decorator is excluding, rule edition should be allowed to be inputted as " x**".

![image](https://user-images.githubusercontent.com/44018302/68007213-d38ca200-fcb5-11e9-8e53-1ca282226839.png)

**Comment by wy65701436** [comment]
It’s by design, excluding all repositories is meaningless? Why do we need this kind of rule?
