### ISSUE TITLE
The sort of immutable tag rules should stay the same for all operations 

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#9713]
The first rule goes to the bottom of the list after a update operation:
 1. Disable the first rule
![image](https://user-images.githubusercontent.com/30999793/68010518-cffe1880-fcbf-11e9-871d-f61bc822baa3.png)
2. It goes to the bottom
![image](https://user-images.githubusercontent.com/30999793/68010690-3d11ae00-fcc0-11e9-9d2c-a5e514b13cf5.png)

**Comment by wy65701436** [comment]
fixed as PR merged. https://github.com/goharbor/harbor/pull/9799
