### ISSUE TITLE
delete shared immutable tag may timeout fail

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9714]
1. create immutable rule latest
2. delete the tag latest, it will return fail soon and correctly
3. delete the other tag 30.0 which has same digest with latest, it will always show deleting circle on UI, and refresh UI will get error "operation been interrupted"
4. delete tag 30.0 again will successful

![image](https://user-images.githubusercontent.com/188115/68010691-3daa4480-fcc0-11e9-8678-3ee80920ca96.png)

**Comment by bitsf** [comment]
This issue maybe relative to https://github.com/goharbor/harbor/issues/9715, which is actually a concurrent thread problem.

**Comment by wy65701436** [comment]
It should be the issue of parallel deleting tag.

**Comment by jwangyangls** [comment]
This problem is caused by the same problem as #9720 ；
