### ISSUE TITLE
Build history return HTTP 500 error when backend storage is mino storage with custom cert

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#9717]
1. Install Harbor with backend minio storage, the storage is https with a custom cert.
2. Push images to Harbor 
3. Click the "Build History" of the images, returns HTTP 500 error.
check the core.log
```
Nov  1 08:33:15 172.18.0.1 core[8304]: 2019-11-01T08:33:15Z [ERROR] [/common/api/base.go:195]: error occurred while getting manifest of library/cassandra:latest: Get https://10.161.48.188/zdjtest/folder185/docker/registry/v2/blobs/sha256/2a/2a4f39f7e8050697cb23aaa37b6f10982f2cda70accef7fb594811b2d31e7858/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191101%2Fgeneric%2Fs3%2Faws4_request&X-Amz-Date=20191101T083315Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=126e1cb50f6032f9e8a2300943b86b5b5b2a320b74d9a232fd05ad9aa03ca8a5: x509: certificate signed by unknown authority

```
The problem is caused by trusted certificated is not installed in core container.

**Comment by stonezdj** [comment]
this problem should be resolved when trusted_certificated is installed on core container

**Comment by stonezdj** [comment]
After Harbor Release 2.0.0, a trusted certificate (CA) could be installed to each container.  the self signed certificate can be trusted. so it is closed after release 2.0.0.

**Comment by stonezdj** [comment]
Verified on harbor-offline-installer-v2.0.0-rc1.tgz, it can not work with the minio storage.

**Comment by reasonerjt** [comment]
So that for the containers which we want to inject certificates, we should put all the certs in one directory in `prepare` and mount the whole directory into `/harbor_cust_cert`.

In docker-compose template, it will look like this:
```
      - type: bind
        source: ./common/config/shared/trust-certificates/
        target: /harbor_cust_cert/
```

**Comment by renmaosheng** [comment]
do we support minio now? I thought we need to perform more work to support it for the standalone HA storage solution.

**Comment by reasonerjt** [comment]
minio is S3-compatbile, so it works, the issue reveals a more general issue that when the backend storage service is running with self-signed certificate.  This one should be fixed.

**Comment by renmaosheng** [comment]
thanks Daniel!

**Comment by stonezdj** [comment]
verified
