### ISSUE TITLE
Syntax error in the error message got from docker client when trying to push an immutable image

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#9718]
Got the error message:
`denied: Failed to process request, due to 'hello-world:latest' is a immutable tag.`
Should be `an immutable tag` rather than `a immutable tag`

**Comment by ywk253100** [comment]
```shell
root@ubuntu16:~/harbor# docker push 10.193.11.7/yinw/hello-world:latest
The push refers to repository [10.193.11.7/yinw/hello-world]
0d315111b484: Pushed
denied: Failed to process request, due to 'hello-world:latest' is a immutable tag.
```
Besides, the image I'm pushing is `yinw/hello-world:latest`, but the image in the error message is `hello-world:latest`. And seems `is an immutable image` is better as the `yinw/hello-world:latest` is an image rather than just a tag

**Comment by wy65701436** [comment]
the error format has been updated to `Failed to process request due to 'busybox:latest' configured as immutable`. For the second issue you mentioned, let's keep it in 1.10 and use https://github.com/goharbor/harbor/issues/9711 to track it.
