### ISSUE TITLE
The slow reloading Harbor UI stuck our service more than 1 hour.

### ISSUE THREAD

**Issue by lileitongxue** [goharbor/harbor#9719]
When the Harbor UI restarted, it started to load very long time, even more than 1 hour.  I have checked our docker images data was over 17T size. Anyone knows the reason of the very slow UI reloading and how to optimize it? We are very confusing about the long period of loading time.

**Comment by SaigyoujiYuyuko233** [comment]
Same problem, I only store 6-8 images. The UI and docker push/pull get very slow.
