### ISSUE TITLE
sync_quota flag should not control the initialization of quota setting of projects.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9725]
**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.2]

**Additional context:**

When I set `SYNC_QUOTA` to `false` when upgrading from 1.8 to 1.9
The process worked as expected that the sync was skipped.

Then I logged in to UI I saw the project quotas as follow
![image](https://user-images.githubusercontent.com/2390463/68018144-625be780-fcd3-11e9-930d-97653f1b1515.png)

After I removed a tag from the project, the hard limit of the quota appeared as `unlimited`
![image](https://user-images.githubusercontent.com/2390463/68018186-815a7980-fcd3-11e9-94b3-07d42980d775.png)

Ideally the flag should only skip sync, but not skip the hard limit of the quota of projects.

**Comment by wy65701436** [comment]
The flag is only for system admin to bypass the quota sync step. For the issue you mentioned above, the system admin can call the `/api/internal/syncquota` to fix it.
