### ISSUE TITLE
robot account name containing "$" will cause bug in gitlab CI

### ISSUE THREAD

**Issue by iWangJiaxiang** [goharbor/harbor#9732]
Hello

I found the robot account in harbor has a name pattern like `robot$XXX`, which contains `$`. 

In gitlab ci, I set a env variable to store robot user name but the `$` symbol broke the user name.

Would u consider to change this pattern?

**Comment by lixianyang** [comment]
You can use $$ in project's runner env setting.

**Comment by iWangJiaxiang** [comment]
@lixianyang Indeed, that will work!

Thank you

**Comment by rimantoro** [comment]
hi,

I have gitlab-runner on my local ubuntu, and want to use this username as env, but never success.
Did anyone here have tried this on gitlab-runner local ?

**Comment by iWangJiaxiang** [comment]
@rimantoro 

Set CI/CD parameters like below

![image](https://user-images.githubusercontent.com/19409802/84010222-f3501b00-a9a6-11ea-8c4e-eed9fd83f6a9.png)

**Comment by rimantoro** [comment]
> @rimantoro
> 
> Set CI/CD parameters like below
> 
> ![image](https://user-images.githubusercontent.com/19409802/84010222-f3501b00-a9a6-11ea-8c4e-eed9fd83f6a9.png)

Nope. I'm running from my local shell with this command

```
gitlab-runner exec docker \
--env ....
--env MYUSERNAME=robot$$xxxx \
"StageName"
```

MYUSERNAME is not correctlly print inside the runner. I didn't know, are this gitlab-runner issue or harbour.

**Comment by iWangJiaxiang** [comment]
> > @rimantoro
> > Set CI/CD parameters like below
> > ![image](https://user-images.githubusercontent.com/19409802/84010222-f3501b00-a9a6-11ea-8c4e-eed9fd83f6a9.png)
> 
> Nope. I'm running from my local shell with this command
> 
> ```
> gitlab-runner exec docker \
> --env ....
> --env MYUSERNAME=robot$$xxxx \
> "StageName"
> ```
> 
> MYUSERNAME is not correctlly print inside the runner. I didn't know, are this gitlab-runner issue or harbour.

Use `robot\$xxxx` for shell environment

**Comment by rimantoro** [comment]
> > > @rimantoro
> > > Set CI/CD parameters like below
> > > ![image](https://user-images.githubusercontent.com/19409802/84010222-f3501b00-a9a6-11ea-8c4e-eed9fd83f6a9.png)
> > 
> > 
> > Nope. I'm running from my local shell with this command
> > ```
> > gitlab-runner exec docker \
> > --env ....
> > --env MYUSERNAME=robot$$xxxx \
> > "StageName"
> > ```
> > 
> > 
> > MYUSERNAME is not correctlly print inside the runner. I didn't know, are this gitlab-runner issue or harbour.
> 
> Use `robot\$xxxx` for shell environment

Nope, still not work. Have tried all escaping method for $, but didn't find any solution yet.

**Comment by QuentinLeloire** [comment]
Hi, I've tried same escaping methods but doesn't work, anyone found a fix ?

**Comment by cardin** [comment]
> EDIT: Ignore what I said in the bottom section. It didn't work. I've added another workaround in its place.

In the end, I decided to authenticate locally on my dev machine to get the credentials cached in my `~/.docker/config.json`. Then I base64-encoded the file contents and used it in GitLab CI.

1. Run `docker login` on your local machine
2. Check credentials are inside `~/.docker/config.json`
3. Encode it `cat ~/.docker/config.json | base64 -w 0`
4. Add it as a GitLab CI variable (type: variable, not file!)
5. In your `.gitlab-ci.yml`, add this:
```yml
- mkdir -p ~/.docker
- echo "$DOCKER_AUTH_CONFIG" | base64 -d > ~/.docker/config.json
```

That way, you don't have to deal with `$` at all in your GitLab CI.

-------------------------
### (OLD, NOT WORKING VERSION)
I found this worked for me.

Double `$$` in the CICD settings panel, with `Expand Variable Reference` enabled.
![Image](https://github.com/user-attachments/assets/ab897850-ffb9-463d-b24a-5e22eab0ad02)
![Image](https://github.com/user-attachments/assets/eff229c9-d4b3-40ed-995f-1b352f739e70)

And using quotation marks in the script command.
![Image](https://github.com/user-attachments/assets/614cd522-9483-437e-a0c9-7f02a8b390c0)
