### ISSUE TITLE
use config variable instead of hardcore local url in Replication adapter

### ISSUE THREAD

**Issue by DanielQujun** [goharbor/harbor#9740]
Replication got "500 Internal Server error" when harbor-core listening on  a non-default httpPort, This was Related to  [#7718](https://github.com/goharbor/harbor/pull/7718)

```
// when the adapter is created for local Harbor, returns the "http://127.0.0.1:8080"
// as URL to avoid issue https://github.com/goharbor/harbor-helm/issues/222
// when harbor is deployed on Kubernetes
func (a *adapter) getURL() string {
	if a.registry.Type == model.RegistryTypeHarbor && a.registry.Name == "Local" {
		return "http://127.0.0.1:8080"
	}
	return a.url
}
```

Since we already have "CORE_LOCAL_URL"  environment variable, "http://127.0.0.1:8080"  should  replace by "config.LocalCoreURL()"

**Comment by DanielQujun** [comment]
@ywk253100

**Comment by ywk253100** [comment]
@DanielQujun The port of core is used internally, it cannot be configured. The port can be configured in `harbor.yml` is for the nginx. 

The `127.0.0.1` is used to fix issue https://github.com/goharbor/harbor-helm/issues/222, it cannot be replaced by `config.LocalCoreURL()`

**Comment by DanielQujun** [comment]
Sorry for  misunderstood `config.LocalCoreURL()` , but to fix kubernetes hairpin mode disabled no need have to be  "127.0.0.1", any ip configured in that pod will work. that why I thought  `config.LocalCoreURL()` would be useful.

In my case ,8080 is used by another service, and I  edited httpport section in `app.conf` the configure file of core. It worked well except replication  error as I post above.

The  8080 port is used very common , I suggest the port of core should be configured.

**Comment by ywk253100** [comment]
Could you explain more about `but to fix kubernetes hairpin mode disabled no need have to be "127.0.0.1", any ip configured in that pod will work`?

For `In my case ,8080 is used by another service`, I didn't get your point why you have to change the default port

**Comment by DanielQujun** [comment]
[ #7718](https://github.com/goharbor/harbor/pull/7718): Fix issue: replication cannot work when Harbor is deployed on Kubernetes whose hairpin mode is disabled

As far as I know , A Pod cannot reach itself via Service IP when Kubernetes is disabled hairpin mode. I guest #7718 is committed to deal with this situation, If I am wrong , pls correct me . but even though haipin mode is disabled ,A Pod  can reach itself  ip as long as its ip was  actually configured on its nic.

`In my case ,8080 is used by another service`: A runnning httpSever is using 8080 port  on the host that I try to start harbor core
