### ISSUE TITLE
Certificate refresh isn't working without restarting nginx pod

### ISSUE THREAD

**Issue by ruzickap** [goharbor/harbor#9745]
Hello.

I'm using `cert-manager` to take care about my SSL certificates used by Harbor and keep them valid.

Here is the description how to use `cert-manager` with harbor:

https://blogs.vmware.com/cloudnative/2019/06/12/demonstrating-certificate-management-by-deploying-harbor-with-an-ssl-endpoint/

The problem is that every month `cert-manager` is renewing the certificates and store them into secret (In helm chart it's `expose.tls.secretName` parameter).

Unfortunately Harbor's nginx pod can not "reload/refresh" the secret with new certificate and must be **manually restarted** to get updated certificates. 

Wouldn't it be better solution not to use "internal harbor's nginx" and let ingress/istio to take care about the certificates and ssl connections?

Thank you...

**Comment by bdowling** [comment]
fwiw, we came across this same issue, we had a mix of old and restarted harbor-nginx pods and the cert expirations were coming back with different timestamps..  also renewed by cert-manager... We're probably going to swtich to using an ingress, but it might be useful for those using goharbor-nginx to implement a copy of this script to reload on cert changes...

https://github.com/rosskukulinski/nginx-kubernetes-reload/blob/master/nginx-reload.sh
