### ISSUE TITLE
The "Scanner" tab should be hidden for developer and guest

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#9770]
`user01` is the developer of project `yinw`:
<img width="1665" alt="scan01" src="https://user-images.githubusercontent.com/5835782/68367800-755a3600-0171-11ea-900a-4b81b4ff172f.png">

**Comment by AllForNothing** [comment]
@steven-zou to hide scanner tab , should remove below permission from permisson API
![image](https://user-images.githubusercontent.com/30999793/68460065-e1a46a80-0241-11ea-8a8e-154a99fd6d3b.png)

**Comment by xaleeks** [comment]
This has been fixed
