### ISSUE TITLE
Project member role display not match the real permissions for users have multi groups in OIDC 

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#9771]
**Steps to reproduce the problem:**
1. Set OIDC as auth mode
2. Create two member groups `group1` and `group2` in library project, group1 as guest role, group2 as master role
3. Login harbor with `user1` which have `group1` and `group2` in OIDC

**Expected behavior and actual behavior:**
The role for `user1` in library project should be master, but actual is guest.

**Comment by reasonerjt** [comment]
This is not introduced by oidc, actually earlier we made decision that a user may have multiple roles in a project, this makes sense b/c we are moving towards a more customizable role model that roles may or may not overlaps.  So it seems to me that this API should be changed.  In the response the value of attribute `current_user_role_id` should be a list.
https://github.com/goharbor/harbor/blob/master/API/harbor/swagger.yaml#L4872

I'll add `current_user_role_id_list` and check the impact on UI if the attribute `current_user_role_id` is removed.

**Comment by jwangyangls** [comment]
In some cases, “current_user_role_id” needs to be displayed on the page.

**Comment by jwangyangls** [comment]
![image](https://user-images.githubusercontent.com/29826789/68460912-eec25900-0243-11ea-870e-911cbeeda39d.png)

**Comment by jwangyangls** [comment]
![image](https://user-images.githubusercontent.com/29826789/68460948-0ef21800-0244-11ea-9c44-8221cb4ce57d.png)

**Comment by reasonerjt** [comment]
I'll add `current_user_role_id_list` to the response and update the value of `current_user_role_id` so that it shows the highest role.
