### ISSUE TITLE
permissions.md needed update for Tag immutability and Scanner

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#9773]
What can we help you?

**Comment by stuclem** [comment]
I have added the scanners in https://github.com/goharbor/harbor/pull/10029/commits/805e88db3bac34abac601e5ef1277af5eb176d44 and tag immutability in https://github.com/goharbor/harbor/commit/081fd5f152428583e46d5e7ea3d9c8e5daefc1b6#diff-4430a66689a53c6aac7daa90145191b8.

@xaleeks @reasonerjt can you please review? Thanks!
