### ISSUE TITLE
Tag保留require redis lock failed问题

### ISSUE THREAD

**Issue by kerven88** [goharbor/harbor#9781]
harbor版本：V1.9.2
Tag保留，新增规则后，手动触发tag删除发现有部分失败了，查看日志有如下Error：
Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned

![image](https://user-images.githubusercontent.com/51351006/68370838-5ad78b00-0178-11ea-81c4-5ba783c9cff9.png)
![image](https://user-images.githubusercontent.com/51351006/68370846-5f03a880-0178-11ea-9497-2895cf5a6979.png)
![image](https://user-images.githubusercontent.com/51351006/68442145-134e0f00-020b-11ea-8b6e-b5c457d8e6bc.png)

查看core.log:
![image](https://user-images.githubusercontent.com/51351006/68370953-940ffb00-0178-11ea-8d72-3c2f395a5d4f.png)

**Comment by reasonerjt** [comment]
这种错误应该是并发删除时发生的错误。应该可以忽略的。
请问失败后，tag删掉了吗？

**Comment by heww** [comment]
Will be closed because the new quota implementation will not use lock in redis to process the concurrency pushing.

**Comment by heww** [comment]
Closed by #10907 , see more #11020 .
