### ISSUE TITLE
镜像同步504 Gateway Time-out问题

### ISSUE THREAD

**Issue by kerven88** [goharbor/harbor#9782]
harbor版本：V1.9.2
有部分deletion操作的同步失败，日志如下：
2019-11-07T04:22:58Z [ERROR] [/replication/transfer/image/transfer.go:367]: failed to delete the manifest of image finance/sscf-service-provider:72086 on the destination registry: http error: code 504, message <html>

![image](https://user-images.githubusercontent.com/51351006/68371122-f36e0b00-0178-11ea-8b21-55bc4a1060de.png)
![image](https://user-images.githubusercontent.com/51351006/68441901-886d1480-020a-11ea-96d0-555693d8eda3.png)

![image](https://user-images.githubusercontent.com/51351006/68371127-f7019200-0178-11ea-93ab-965eee8ece76.png)

查看jobservice日志：
![image](https://user-images.githubusercontent.com/51351006/68371215-2c0de480-0179-11ea-8d8c-82a4151e54a2.png)

**Comment by cd1989** [comment]
有 core 的异常日志吗？

**Comment by kerven88** [comment]
> 有 core 的异常日志吗？目标仓库的

这个tag仓库core日志：
![image](https://user-images.githubusercontent.com/51351006/68829851-05a1f900-06e5-11ea-9cf7-3e5b1f17c33f.png)

**Comment by cd1989** [comment]
@wy65701436 Is this the same problem to https://github.com/goharbor/harbor/issues/8673 ?

**Comment by kerven88** [comment]
> @wy65701436 Is this the same problem to #8673 ?

好像不是同一个问题，两个都是1.9.2版本之间的同步。

**Comment by reasonerjt** [comment]
is it reproducible?  What's the log on the other side?

**Comment by bitsf** [comment]
@kerven88 这个问题升级后解决了吗？

**Comment by kerven88** [comment]
> @kerven88 这个问题升级后解决了吗？

好像没有出现了

**Comment by zhangqingwen** [comment]
@kerven88  docker ce 18.09 ，docker-compose 1.24.1 ，harbor 1.9.2 还是会有同样的问题

请教下你升级了什么解决的？

**Comment by zming** [comment]
@kerven88 请问你是如何解决这个问题，我的故障现象和你一模一样

**Comment by zhouya2010** [comment]
2.2.0 仍然有同样的问题
