### ISSUE TITLE
[Scanner] Unhealthy Scanner still be listed in the project scanner list.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#9788]
Get internal error when to switch to an unhealthy in the project.

Please give a reasonable message as the project admin could not know the scanner is unhealthy.

**Comment by steven-zou** [comment]
@AllForNothing 

Before adding to the project, check the health of the selected scanner. If failed, print error message at top of the adding wizard

**Comment by steven-zou** [comment]
@AllForNothing 

As there might be unhealthy ones in the candidate list, we can let the user choose and set it as the project level scanner. However, if the scanner is unhealthy, we should alert the user with a warning message.
