### ISSUE TITLE
Migrator should not  throw code error when http was not configed in harbor.yml

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#9789]
![image](https://user-images.githubusercontent.com/44018302/68374609-2c5dae00-0180-11ea-8580-7bd804517db9.png)

   
![image](https://user-images.githubusercontent.com/44018302/68374488-f4ef0180-017f-11ea-9555-ddb57acb090f.png)

**Comment by reasonerjt** [comment]
will be closed by  #9800

**Comment by reasonerjt** [comment]
Fixed by #9800
