### ISSUE TITLE
Chart replication fails between two Harbors - 404 not found. Image succeeds.

### ISSUE THREAD

**Issue by glenwperry** [goharbor/harbor#9798]
**Expected behavior and actual behavior:**
When Manual or Event-Based replication is kicked off, Harbor primary should replicate both image and chart to mirror.

Instead, image successfully replicates to the mirror instance, but helm chart replication errors out with 404 "not found". 

Seems like either it's getting tripped up on lack of .prov file, or it's simply looking at the wrong path.

**Steps to reproduce the problem:**
Setup two Harbors in two different kubernetes clusters. Attempt to replicate from one to another. Storage is backed by S3 and images/helm charts are present in the primary bucket (as expected).

**Versions:**
Please specify the versions of following systems.

- harbor version: Version v1.9.1-c90c264f
- docker engine version: 18.09.0
- kubernetes version: 1.15.5

**Additional context:**
JOB SERVICE POD
2019-11-07T20:27:53Z [ERROR] [/jobservice/runner/redis.go:64]: |@_@| Job 'REPLICATION:4bb9a672f2ad72ff293b98dd' exit with error: failed to download the chart http://harbor-harbor-core/chartrepo/infrastructure/charts/service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present-0-a814.tgz: 404 {"error":"object not found"}

HARBOR CORE POD
2019/11/07 20:28:56 [D] [server.go:2774] |     10.42.3.62| 404 |  20.102223ms|   match| GET      /chartrepo/infrastructure/charts/service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present-0-a814.tgz   r:/chartrepo/:repo/charts/:filename

CHART MUSEUM POD
{"L":"DEBUG","T":"2019-11-07T20:28:56.319Z","M":"[16741] Incoming request: /api/infrastructure/charts/service-mesh/0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814","reqID":"a8097013-2424-439d-a09d-99e023102202"}     
{"L":"DEBUG","T":"2019-11-07T20:28:56.319Z","M":"[16741] Entry found in cache store","repo":"infrastructure","reqID":"a8097013-2424-439d-a09d-99e023102202"}                                                                      
{"L":"DEBUG","T":"2019-11-07T20:28:56.319Z","M":"[16741] Fetching chart list from storage","repo":"infrastructure","reqID":"a8097013-2424-439d-a09d-99e023102202"}                                                                    
{"L":"DEBUG","T":"2019-11-07T20:28:56.346Z","M":"[16741] No change detected between cache and storage","repo":"infrastructure","reqID":"a8097013-2424-439d-a09d-99e023102202"}                                                            
{"L":"INFO","T":"2019-11-07T20:28:56.346Z","M":"[16741] Request served","path":"/api/infrastructure/charts/service-mesh/0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814","comment":"","latency":"27.462039ms","clientIP":"10.42.3.61","method":"GET","statusCode":200,"reqID":"a8097013-2424-439d-a09d-99e023102202"}                                            
{"L":"DEBUG","T":"2019-11-07T20:28:56.348Z","M":"[16742] Incoming request: /infrastructure/charts/service-mesh-0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814.tgz.prov","reqID":"66554e2c-c7b9-4ed0-89b3-3be5d69a6b92"}
{"L":"WARN","T":"2019-11-07T20:28:56.365Z","M":"[16742] NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 3A864EF8FC9D5052, host id: uBwaYkJ7Yo6AcWSdZduQalyhktn9nlUf9HW7PkGT9sCAp7QpAVZOvHCIz7cv4qB/LV9R2K8aSbo=","repo":"infrastructure","filename":"service-mesh-0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814.tgz.prov","reqID":"66554e2c-c7b9-4ed0-89b3-3be5d69a6b92"}                                                         
{"L":"WARN","T":"2019-11-07T20:28:56.365Z","M":"[16742] Request served","path":"/infrastructure/charts/service-mesh-0.5.5-feature-SRE-229-image-pull-if-not-present0a814.tgz.prov","comment":"","latency":"17.066903ms","clientIP":"10.42.3.61","method":"GET","statusCode":404,"reqID":"66554e2c-c7b9-4ed0-89b3-3be5d69a6b92"}                                       
{"L":"DEBUG","T":"2019-11-07T20:28:56.374Z","M":"[16743] Incoming request: /infrastructure/charts/service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present-0-a814.tgz","reqID":"8716507c-6370-40bb-9ff5-cb32039c56f9"}     
{"L":"WARN","T":"2019-11-07T20:28:56.389Z","M":"[16743] NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: C2747074778D4CEB, host id: 1T5zXtJaEgTwaZ0hFL7FmqfcNXGUX9vte85Gl3sjTcFaNekZa14RzyPBW4CS4C9tiSVpWPYdjmw=","repo":"infrastructure","filename":"service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present-0-a814.tgz","reqID":"8716507c-6370-40bb-9ff5-cb32039c56f9"}                                                              
{"L":"WARN","T":"2019-11-07T20:28:56.390Z","M":"[16743] Request served","path":"/infrastructure/charts/service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present0a814.tgz","comment":"","latency":"15.460744ms","clientIP":"10.42.3.62","method":"GET","statusCode":404,"reqID":"8716507c-6370-40bb-9ff5-cb32039c56f9"}

LOGS FROM REPLICATION JOB 
2019-11-07T20:30:43Z [INFO] [/replication/transfer/chart/transfer.go:88]: client for source registry [type: harbor, URL: http://harbor-harbor-core, insecure: true] created
2019-11-07T20:30:43Z [INFO] [/replication/transfer/chart/transfer.go:98]: client for destination registry [type: harbor, URL: https://harbor.mgmt.syn.am/, insecure: false] created
2019-11-07T20:30:43Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying infrastructure/service-mesh:0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814(source registry) to infrastructure/service-mesh:0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814(destination registry)...
2019-11-07T20:30:43Z [ERROR] [/replication/transfer/chart/transfer.go:156]: failed to download the chart infrastructure/service-mesh:0.5.5-feature-SRE-229-image-pull-if-not-present-0-a814: failed to download the chart http://harbor-harbor-core/chartrepo/infrastructure/charts/service-mesh-0.5.5-feature-sre-229-image-pull-if-not-present-0-a814.tgz: 404 {"error":"object not found"}

**Comment by cregev** [comment]
@glenwperry  did you find any workaround for chart replication?

**Comment by binnythomas-1989** [comment]
I have the same issue too. We get these errors on the core logs

**Comment by Volkimd** [comment]
I have the same problem.

```
2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:88]: client for source registry [type: harbor, URL: https://core.****.de, insecure: true] created
2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:98]: client for destination registry [type: harbor, URL: http://harbor2-harbor-core:80, insecure: true] created
2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying library/harbor:1.3.2-TEST(source registry) to library/harbor:1.3.2-TEST(destination registry)...
2020-06-11T14:15:37Z [ERROR] [/replication/transfer/chart/transfer.go:156]: failed to download the chart library/harbor:1.3.2-TEST: failed to download the chart https://core.****.de/chartrepo/library/charts/harbor-1.3.2-test.tgz: 404 {"error":"object not found"}
```
real chart tgz harbor-1.3.2-**TEST**.tgz
wrong URL https://core.****.de/chartrepo/library/charts/harbor-1.3.2-test.tgz

The URL in the Error Message is not correct. The whole url would be set toLower(download function in [chart_registry](https://github.com/goharbor/harbor/blob/master/src/replication/adapter/helmhub/chart_registry.go ) but the real URL includes capital letters.

if I try https://core.****.de/chartrepo/library/charts/harbor-1.3.2-TEST.tgz object is existing.

**Comment by chrishoerl** [comment]
I have the same problem on Harbor Version v2.1.0-a3eca103
The URL is set to lowercase causing problems when a chart name contains upper case letters.

**Comment by chrishoerl** [comment]
> I have the same problem.
> 
> ```
> 2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:88]: client for source registry [type: harbor, URL: https://core.****.de, insecure: true] created
> 2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:98]: client for destination registry [type: harbor, URL: http://harbor2-harbor-core:80, insecure: true] created
> 2020-06-11T14:15:37Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying library/harbor:1.3.2-TEST(source registry) to library/harbor:1.3.2-TEST(destination registry)...
> 2020-06-11T14:15:37Z [ERROR] [/replication/transfer/chart/transfer.go:156]: failed to download the chart library/harbor:1.3.2-TEST: failed to download the chart https://core.****.de/chartrepo/library/charts/harbor-1.3.2-test.tgz: 404 {"error":"object not found"}
> ```
> 
> real chart tgz harbor-1.3.2-**TEST**.tgz
> wrong URL https://core.****.de/chartrepo/library/charts/harbor-1.3.2-test.tgz
> 
> The URL in the Error Message is not correct. The whole url would be set toLower(download function in [chart_registry](https://github.com/goharbor/harbor/blob/master/src/replication/adapter/helmhub/chart_registry.go) but the real URL includes capital letters.
> 
> if I try https://core.****.de/chartrepo/library/charts/harbor-1.3.2-TEST.tgz object is existing.

What about a pull request? I can't code golang.

**Comment by chrishoerl** [comment]
Hopefully here is more progress #13187
