### ISSUE TITLE
My harbor can't  start because:ERROR: Couldn't find env file: /usr/local/harbor/common/config/registryctl/env

### ISSUE THREAD

**Issue by XianglongLuo** [goharbor/harbor#9808]
What result to this outcome?
What should I do to deal with this problem?
<img width="405" alt="捕获" src="https://user-images.githubusercontent.com/37337250/68463629-0c92bc80-024a-11ea-84bc-075906c92069.PNG">

**Comment by aladjadj** [comment]
Maybe run install.sh ?
