### ISSUE TITLE
images copy is 401   This error occurs 9 out of 10 copies

### ISSUE THREAD

**Issue by ddy4633** [goharbor/harbor#9822]
After changing the Admin password on all Harbors and updating the registries(all healthy), Once in a while, I got replication failed due to 401 unauthorized, it happens randomly and could not understand what exactly the issue.This error occurs 9 out of 10 copies

Harbor version: 1.9.1

2019-11-11T06:42:04Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"devops/devops_ziya_web","Action":"pull"}]}]}

![](https://i.imgur.com/cUT9PIv.png)

![](https://i.imgur.com/DXpUzdG.png)

**Comment by ddy4633** [comment]
this  is  jobserver logs

**Comment by ywk253100** [comment]
@ddy4633 Could you upload the logs of both the source and target Harbor?

**Comment by ddy4633** [comment]
> @ ddy4633您可以上传源和目标Harbor的日志吗？

jobservice log? Is there anything else

**Comment by ywk253100** [comment]
All logs are better

**Comment by ddy4633** [comment]
http://bk.poph163.com:666/   all logs download 


> All logs are better

**Comment by ywk253100** [comment]
Access Denied for url

**Comment by ddy4633** [comment]
> 无法访问提供的URL：访问被拒绝

client -> nginx 443 -> docker nginx 443 
Can you confirm that it is caused by nginx forwarding?

**Comment by ywk253100** [comment]
Could package the logs and upload them?
