### ISSUE TITLE
Unable to switch auth mode from Database to OIDC 

### ISSUE THREAD

**Issue by cmpmohan** [goharbor/harbor#9823]
What can we help you?

We have configured harbor with database auth mode which is working fine. now our client want to integrate the same harbor with OIDC. we are not able to change the auth mode as OIDC in harbor URL. looks like drop-down button is disabled.  please help us to fix issue.
![auth_mode](https://user-images.githubusercontent.com/12935715/68567214-74314d80-047e-11ea-940c-8af589087d49.PNG)

**Comment by ddy4633** [comment]
1. Clear out all users except admin/anonymous. If there is any foreign key association, it is also necessary to remove the association
2. https://github.com/goharbor/harbor/wiki/harbor-faqs#authentication

**Comment by reasonerjt** [comment]
@cmpmohan let us know if the problem remains

**Comment by reasonerjt** [comment]
Based on #9830 I believe you successfully reconfigured following the wiki.

I'm closing it, please let us know if you want me to reopen.
