### ISSUE TITLE
offline installer script should failed if missing images

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9826]
I create an offline installer, but without building chart, and install harbor with chart, however this will still be successful, because it will download from docker hub.
We should block the download or fail the install when using offline installer, in case install a wrong version by mistake.

**Comment by MinerYang** [comment]
if the `with-chartmuseum`not being set by user,  docker compose file would not to load/pull the images unless you happen to have the image locally with same tags or digest.
https://github.com/goharbor/harbor/blob/49d73fa57dd74766ae7cd1083b53d50ed6624489/make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja#L190
https://docs.docker.com/compose/compose-file/compose-file-v2/#image.

I would like to close this issue for now.
