### ISSUE TITLE
user onboard has issue via OIDC login

### ISSUE THREAD

**Issue by cmpmohan** [goharbor/harbor#9830]
What can we help you?

We had no issue for first new user onboard which works fine. but when we are trying to on-board second new user via OIDC login. we are getting error user conflict   even though same user is not in harbor URL and also DB end. please have screen shot and help us to fix issue.

NOTE:
 its new user what we are trying to onboard.

![onboard_error](https://user-images.githubusercontent.com/12935715/68595750-0efe4c00-04c0-11ea-9ce4-ae22c7d65498.PNG)

**Comment by reasonerjt** [comment]
Does your ID token have claim of Email?  Adding `email` to the scope of the OIDC setting may solve this problem.
There may be issue in handling the Emails when onboarding user it is not in the token.  I'll try to reproduce this week.

**Comment by xaleeks** [comment]
I'm not sure if this is indeed an issue on harbor side, but if we pull the username from claim like in the https://github.com/goharbor/harbor/pull/9311, then we don't need to worry about these name collisions, it's up to user to resolve these on their OIDC side. @reasonerjt

**Comment by reasonerjt** [comment]
There will be more tricky issue when the OIDC provider returns same value in the preset claim for different user.

**Comment by MischaPanch** [comment]
Hi. I am having the same problem, are there any news on that?

**Comment by reasonerjt** [comment]
@MischaPanch could you reproduce the issue and provide the logs of `harbor-core` component?

**Comment by cmpmohan** [comment]
looks issue got resolved by adding email ID  in scope

**Comment by MischaPanch** [comment]
> @MischaPanch could you reproduce the issue and provide the logs of `harbor-core` component?

The issue was indeed caused by an empty email field that mistakenly was set up by one of our admins. However, the error message is highly confusing and could be improved, maybe it's worth to keep this issue open until this is done?
