### ISSUE TITLE
DB ERROR log:  duplicate key value violates unique constraint "unique_artifact_blob"

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9832]
In release v1.9.2

After testing replication, there's an error log which seems meaningless.

ERROR:  duplicate key value violates unique constraint "unique_artifact_blob"

![image](https://user-images.githubusercontent.com/188115/68633289-44d91a00-052c-11ea-8e3c-1235db40f2f2.png)

**Comment by reasonerjt** [comment]
This error is from pg process, we intentionally eat some errors so won't fix.
