### ISSUE TITLE
All image tag disappear in 1.9.2

### ISSUE THREAD

**Issue by lixianyang** [goharbor/harbor#9836]
**Expected behavior and actual behavior:**

I pushed 5 image artifact in harbor, and then manually sync a official python replication job.

expected to happen:
Harbor ui show correct image tags.

actual behavior:
All tags disappear.

**Steps to reproduce the problem:**

Not sure.

**Versions:**

- harbor version: [1.9.2]
- docker engine version: [18.09.6]
- docker-compose version: [z.z.z]

In kubernetes.

![harbor-bug1](https://user-images.githubusercontent.com/6286227/68638620-1f084100-053d-11ea-8580-3f6715a965f9.png)

![harbor-bug2](https://user-images.githubusercontent.com/6286227/68638609-1283e880-053d-11ea-8690-959f7c639bc4.png)

**Data in PG**
```shell
registry=# select * from artifact;
 id | project_id |        repo         |  tag   |                                 digest                                  |     kind     |       creation_time        | pull_time |         push_time          
----+------------+---------------------+--------+-------------------------------------------------------------------------+--------------+----------------------------+-----------+----------------------------
 19 |         35 | hello-world/ci-demo | v1.0.2 | sha256:f3199457d5bec9fca3349d4c8a706d4b3ee9d9ab0fd333412c345aa3bee77dee | Docker-Image | 2019-11-11 08:10:00.788528 |           | 2019-11-11 08:10:00.788528
 20 |         35 | hello-world/ci-demo | v1.0.3 | sha256:8e68f9441da6c5f53052238b94a87e01d51afe6492e7f2847948aecb7ea52423 | Docker-Image | 2019-11-11 08:11:16.114053 |           | 2019-11-11 08:11:16.114053
 21 |         35 | hello-world/ci-demo | v1.0.4 | sha256:e816f2b5197d2ce118e1dc7e69101b7692dd7b96fb95b8a7df65af3215665543 | Docker-Image | 2019-11-11 08:29:22.045275 |           | 2019-11-11 08:29:22.045275
 22 |         35 | hello-world/ci-demo | v1.0.5 | sha256:a77bd90c49488c4524ff57fe33a5384b52e4c64aeac366c673779e9aa2dc4444 | Docker-Image | 2019-11-11 08:29:26.775979 |           | 2019-11-11 08:29:26.775979
 23 |         35 | hello-world/ci-demo | v1.0.6 | sha256:836c5d18d7543c9f27f603efee88ca4223ea87124503f0c2fb2f25916d6fe83c | Docker-Image | 2019-11-11 08:29:28.956727 |           | 2019-11-11 08:29:28.956727
(5 rows)
```

**Comment by wy65701436** [comment]
what's your storage? can you see the `tags` after go into tag detail page?

**Comment by lixianyang** [comment]
@wy65701436 

database: postgres
registry storage: file
redis: haproxy redis ha

tag detail page:

![harbor-bug3](https://user-images.githubusercontent.com/6286227/68643892-30a61480-054e-11ea-9a6e-8075c408036d.png)

where is the data come from? postgres or redis ?

**Comment by wy65701436** [comment]
the tags are the results of GET v2/manifest , please check the core and registry.log.

**Comment by lixianyang** [comment]
All tags appear after restart core service.

core log shows tag/list api 404, but curl is ok in registry. 

I delete core and registry pod simultaneously. After all pod ready, tags disappear again. I restart core service(delete core pod), then everything is ok. It's strange
