### ISSUE TITLE
Configuring External Postgre with Harbor

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#9855]
I am configuring external database PostgreSQL with Harbor. I have some doubts:
I have provided the external DB details in the harbor.yml but when i deployed the application then i was facing issue of invalid credentials while login the Harbor UI.

I have also installed Harbor on VM1 and PostgreSql on VM2.
Do i need to install the postgre on VM 1 also which has Harbor or it will build the connection through the harbor.yml

 Please help.

Thanks,
Ayush

**Comment by ninjadq** [comment]
can you provide harbor logs?
