### ISSUE TITLE
UI should redirect to login page

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9863]
When session timeout, click on some page, it will fail with 401, and show a login button, and page can still be see and navigate.
It is better to redirect to login page directly.

![image](https://user-images.githubusercontent.com/188115/68757446-eb194280-0646-11ea-8d39-1f5850e144ce.png)

**Comment by jwangyangls** [comment]
Let's discuss if we need to do this

**Comment by xaleeks** [comment]
I'm tagging it 2.0.1 so we don't forget to discuss on next meeting
