### ISSUE TITLE
Oauth functionality breaks with "Harbor:interface conversion: interface {} is nil, not string"

### ISSUE THREAD

**Issue by stoimendhristov** [goharbor/harbor#9877]
**What can we help you?**
After having changed to newest version of harbor-portal, when OIDC is used for user login the following error message pops out upon authentication:
**Harbor:interface conversion: interface {} is nil, not string**
![harbor-error](https://user-images.githubusercontent.com/12200532/68838665-ba2d2200-06c7-11ea-9e44-f23ee13d2bcf.jpeg)

I had to upgrade the harbor-portal to version 1.9.2 in order to be able to use the latest fixes regarding copy-paste functionality. Beforehand it was buggy (copy button would turn "green" but nothing would be copied to clipboard) as it is a feature our developers would use.

**Version of docker engine**:
`docker -v
Docker version 18.06.2-ce, build 6d37f41`

**Version of kubernetes**:
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}`

**Version of helm**:
`helm version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}`

**Configuration files of Harbor**:
I am using the latest helm chart obtained from this repo:
https://github.com/goharbor/harbor-helm
with the sole modification of:
```
portal:
  image:
    repository: goharbor/harbor-portal
    tag: v1.9.2
```
The general tag is **dev**. However deployments with this tag won't have the "copy-paste" functionality working
 
**Log from pods**:
`kubectl logs predev-harbor-harbor-portal-665d779746-jsgqc -n harbor -f
10.244.1.120 - - [14/Nov/2019:08:08:00 +0000] "GET /harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs HTTP/1.1" 200 693 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"`

`kubectl logs predev-harbor-harbor-nginx-596b5f7dd9-p97rc -n harbor -f
10.244.1.1 - "GET /harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs HTTP/1.1" 200 693 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 0.000 0.001 .
10.244.1.1 - "GET /api/systeminfo HTTP/1.1" 200 444 "https://predev-harbor.2j43-rddpub.aws.airbus-v.cloud/harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 0.007 0.008 .
10.244.1.1 - "GET /c/log_out HTTP/1.1" 200 0 "https://predev-harbor.2j43-rddpub.aws.airbus-v.cloud/harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 0.001 0.001 .
10.244.1.1 - "GET / HTTP/1.1" 200 693 "-" "kube-probe/1.14" 0.000 0.000 .
10.244.1.1 - "GET /api/systeminfo HTTP/1.1" 200 443 "https://predev-harbor.2j43-rddpub.aws.airbus-v.cloud/harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 0.010 0.010 .
10.244.1.1 - "GET /c/oidc/login HTTP/1.1" 302 349 "https://predev-harbor.2j43-rddpub.aws.airbus-v.cloud/harbor/sign-in?signout=true&redirect_url=%2Fharbor%2Fconfigs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" 0.178 0.178 .`

Are there any other logs that might be of help to the community?

Thanks for the help, guys!

**Comment by reasonerjt** [comment]
@stoimendhristov 

It seems the provider is not returning `id_token`.  Could you share your settings of OIDC provider in Harbor?

The code could be refined to provide better error.

**Comment by stoimendhristov** [comment]
@reasonerjt 

OIDC Endpoint: _publicly available (over HTTPS) Oauth provider_
OIDC Client ID: _the client's ID generated by the Oauth provider_
OIDC Client Secret: _the client's secret generated by the Oauth provider_
OIDC scope: offline_access,openid,email,profile

Test server returns **Connection to OIDC server is verified.** with verify certificate checked.

On Oauth provider side `token_id` is being generated and `/oauth/token` returns 200.

Strangely with an earlier version of harbor portal we didn't get the above mentioned error whereas now we do and we don't get more verbosity to give us an indication what could be causing it.

**Comment by stoimendhristov** [comment]
Hm, 

We've tried to simulate the Oauth functionality with Postman and we're being returned a `token_id`. I though the same was happening with Harbor.

However, with Harbor we do not get a `token_id` sent back.

Any ideas?

**Comment by reasonerjt** [comment]
@stoimendhristov 
Sorry for the late response, I was at kubecon.

Could you please clarify is it token_id or id_token?
Could you paste more details steps how you used postman to  verify the issue?  In detail, what requests did you send and what response did you get from the OIDC provider?
