### ISSUE TITLE
The project name overlap other columns when the name is long

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#9886]
<img width="1678" alt="langname" src="https://user-images.githubusercontent.com/5835782/68913901-d39d9f00-0797-11ea-9de2-ac80415ec136.png">

**Comment by ywk253100** [comment]
@jwangyangls Seems this is already fixed in master, let's cherry pick the fix into 1.9

**Comment by jwangyangls** [comment]
fix it in #9914
