### ISSUE TITLE
[Scanner] error message is unclear on pushing image without scanner but with policy enabled.

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#9894]
1, install harbor without clair
2, push image and enable vul policy check
3, pull the image

Got
`Error response from daemon: unknown: middleware: vulnerable handler: error: 10412(Precondition failed) : no scanner registration configured for project: 2`

**Comment by steven-zou** [comment]
Let's see if the users report it as an issue. So far, keep it as it is now.

**Comment by farons** [comment]
配置中取消阻止潜在的漏洞镜像

**Comment by devgig** [comment]
Getting the same error just recently.
```
Error response from daemon: unknown: middleware: vulnerable handler: error: 10412(Precondition failed) : no scanner registration configured for project: 53
```
