### ISSUE TITLE
offline install script need checkpoints

### ISSUE THREAD

**Issue by silenceshell** [goharbor/harbor#9895]
When installing harbor in offline environment, if I want to rerun install.sh, the script always runs from the top, which will cost some time especially when loading images.

If we add checkpoints for successful steps , we could skip them and run directly to the former failed step. This may be convenient in some scenarios.

**Comment by bitsf** [comment]
loading images is usually very quickly if the same images already imported. And this is required to upgrade harbor.

**Comment by silenceshell** [comment]
> loading images is usually very quickly if the same images already imported. And this is required to upgrade harbor.

Well it still needs about 1 minutes on my kvm server(4c8G).

**Comment by reasonerjt** [comment]
The time spent was for docker to load the tgz, before doing some untar there's no way to know if there are any changes in the tar file.

I don't think we should add the checkpoint as it's extremely fragile error prone, if it is a normal practice for you to install Harbor again and again, I don't think it is, you can add a checkpoint yourself by modifying the script.  I don't think we want to add this mechanism.

**Comment by silenceshell** [comment]
It is a **NORMAL** practice.

I came across this problem when I set s3 as storage_service, the parameter is not quite clear(for example, should I set redirect to true or not?), so I tried several times to get the answer.

EVERY time, I have to load the tgz file again and again. I do could modify the script myself, but why not make the script better?
