### ISSUE TITLE
Document that you need to restart docker and Harbor after you change daemon.json

### ISSUE THREAD

**Issue by stuclem** [goharbor/harbor#9901]
You need to restart docker after you change daemon.json, which means you need to restart harbor as well.

From @xaleeks

**Comment by xaleeks** [comment]
edit daemon.json by adding ip to the list of insecure registries

{
  "insecure-registries" : ["myregistrydomain.com:5000", "0.0.0.0"]
}

now restart docker engine with
systemctl restart docker

now you need to down harbor, and restart harbor with
docker-compose down -v
docker-compose up -d

**Comment by xaleeks** [comment]
Hey Stuart, can you move this into the installation guide, it's in the user guide right now

**Comment by stuclem** [comment]
@xaleeks the only mention of daemon.json in the docs is in relation to Kubernetes. Is that what you are talking about? Thanks!

**Comment by xaleeks** [comment]
it's in here https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry

**Comment by stuclem** [comment]
Thanks @xaleeks. So this would have to be referenced in the section of the user guide on registries as well as in the install guide?

**Comment by xaleeks** [comment]
I think putting it in both is fine but definitely should be in the installation guide

**Comment by stuclem** [comment]
Documented in https://github.com/goharbor/harbor/commit/ceb8ec7a3d21e680bdcb1cdafa48b079c425b907.

@xaleeks can you please take a look?

**Comment by stuclem** [comment]
Doc update is in https://github.com/goharbor/harbor/pull/10029. Reviewed by @xaleeks via slack.
