### ISSUE TITLE
Unexpected error when creating the token, error: Unable to parse image from string

### ISSUE THREAD

**Issue by ajizkai** [goharbor/harbor#9905]
what happen with my harbor, when i push my image, i found this errors

> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin
> Nov 17 06:29:04 172.19.0.1 core[1183]: 2019-11-17T06:29:04Z [ERROR] [/core/service/token/token.go:48]: Unexpected error when creating the token, error: Unable to parse image from string: verifikasipenjamin

**Comment by ajizkai** [comment]
this is just wrong in the naming, I have to give the name harbor_url/project/repository format

**Comment by kcsplcompusoft** [comment]
@ajizkai thanks, It's working with naming
