### ISSUE TITLE
Tag清理策略没生效问题

### ISSUE THREAD

**Issue by kerven88** [goharbor/harbor#9906]
harbor版本：V1.9.2

1）配置项目tag保留策略如图：
![image](https://user-images.githubusercontent.com/51351006/69037167-533e9e80-0a22-11ea-96b2-7288dfecf9c7.png)

2）查看项目下的仓库，image数量并没有清理，没生效，项目也有记录时间push time：
![image](https://user-images.githubusercontent.com/51351006/69037225-7406f400-0a22-11ea-8747-2892544a39b9.png)
![image](https://user-images.githubusercontent.com/51351006/69038795-846c9e00-0a25-11ea-91f3-6fa47e0da9b2.png)

3）查看schedule，“保留数”并没有按规则生效
![image](https://user-images.githubusercontent.com/51351006/69037372-bc261680-0a22-11ea-96c9-e1311267614d.png)
![image](https://user-images.githubusercontent.com/51351006/69037526-08715680-0a23-11ea-9706-a6c4421a9775.png)
点“日志”进去：{"code":500,"message":"Internal Server Error"}
![image](https://user-images.githubusercontent.com/51351006/69037432-d95ae500-0a22-11ea-82c2-dae3d322e59b.png)

4）查看jobserver.log：
![image](https://user-images.githubusercontent.com/51351006/69038739-656e0c00-0a25-11ea-9254-5b0596202847.png)

![image](https://user-images.githubusercontent.com/51351006/69038625-28097e80-0a25-11ea-8fa8-4a9f8faa369a.png)
![image](https://user-images.githubusercontent.com/51351006/69038640-33f54080-0a25-11ea-9cc4-c17145984245.png)

5）另外我单独把这个项目配置tag策略，手工执行任务是可以成功清理的：
![image](https://user-images.githubusercontent.com/51351006/69040765-525d3b00-0a29-11ea-8be8-0bf943be0354.png)
![image](https://user-images.githubusercontent.com/51351006/69040779-5721ef00-0a29-11ea-8e64-092d92c04933.png)

**Comment by bitsf** [comment]
如果匹配到需保留的tag的digest相同，也会被保留下来，在即将发布的1.10 版本中会把digest信息打在log中，便于查看。暂时无法通过你提供的截图确认是不是这个情况。

那个500的错误之前我也看到过，一直还没查出原因，可能是高并发下jobservice的日志没有成功写下来，但并不会影响job本身的执行。

**Comment by kerven88** [comment]
> 如果匹配到需保留的tag的digest相同，也会被保留下来，在即将发布的1.10 版本中会把digest信息打在log中，便于查看。暂时无法通过你提供的截图确认是不是这个情况。
> 
> 那个500的错误之前我也看到过，一直还没查出原因，可能是高并发下jobservice的日志没有成功写下来，但并不会影响job本身的执行。


另外，那个gc日志也报错，是什么情况：
![image](https://user-images.githubusercontent.com/51351006/69105847-955df380-0aa7-11ea-8321-ebcf9a3b1796.png)
![image](https://user-images.githubusercontent.com/51351006/69105828-870fd780-0aa7-11ea-91a3-6c60746d7bb4.png)
![image](https://user-images.githubusercontent.com/51351006/69105820-8119f680-0aa7-11ea-9045-701f0685d561.png)

**Comment by bitsf** [comment]
@steven-zou 抽空看一下，jobservice 日志错误，看起来也不像你之前说的redis 中没有及时存下来的问题

**Comment by steven-zou** [comment]
The log text stream is from the log file which will only be kept for a while (7 days).
