### ISSUE TITLE
If I deploy simple harbor, which services need to deploy? I want to deploy simple harbor and don't want to deploy all services

### ISSUE THREAD

**Issue by hegphegp** [goharbor/harbor#9907]
* If I deploy simple harbor, which services need to deploy? I want to deploy simple harbor and don't want to deploy all services

**Comment by ywk253100** [comment]
Running `install.sh` without `--with-clair`, `--with-notary` and `--with-chartmuseum`, the clair, notary and chartmuseum will not be deployed.

**Comment by reasonerjt** [comment]
@hegphegp  How do you define a simple Harbor and you wanna use this simple Harbor for what purpose?
