### ISSUE TITLE
HA Configuration for Harbor

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#9908]
Hi,

I am trying to configure Harbor for Active-Active architecture.
ScalableLB = Active-Active
Harbor VM = Active-Active
DB VM = Active(External PostgreSQL)

The service is deployed successfully but i am getting error while connecting through docker login.
Sometimes it succeeded but sometimes it fails.

I am unable to understand the scenario. Can anyone help me?

**Comment by bjethwan** [comment]
@AyushCloud 
What's the error you get when it fails?

**Comment by AyushCloud** [comment]
It is resolved.
