### ISSUE TITLE
Broken doc link in goharbor.io/docs for "Python SDK (by community)"

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#9913]
The link provided in goharbor.io/docs for "Python SDK (by community)" is not working.
It's pointed to https://github.com/goharbor/harbor/tree/master/contrib/sdk/harbor-py
which gives a 404 page not found error.

**Comment by sunlianqiang** [comment]
> The link provided in goharbor.io/docs for "Python SDK (by community)" is not working.
> It's pointed to https://github.com/goharbor/harbor/tree/master/contrib/sdk/harbor-py
> which gives a 404 page not found error.

@bjethwan  I also want to use the Python SDK, and found it's  in https://github.com/sunlianqiang/harbor/tree/master/contrib/registryapi, but unfortunately it has some bugs and didn't work well.
I have been fixed these bugs and will make a PR later.
