### ISSUE TITLE
arbor.cfg not found, WITH_ADMIRAL will not be set to true Skip cfg up as no harbor.cfg in the path.

### ISSUE THREAD

**Issue by Ezuka** [goharbor/harbor#9915]
when  i upgrade harbor from  1.7.0  to  1.9.3, , i follow this step:
cd harbor 
docker-compose down
mv harbor /my_backup_dir/harbor
cp -r /data/database /my_backup_dir/
docker pull goharbor/harbor-migrator:v1.6.0
and  then :
docker run -it --rm -v  /my_backup_dir/harbor/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.yml -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.6.0 --cfg up

this happen some errors ，harbor.cfg not found, WITH_ADMIRAL will not be set to true
Skip cfg up as no harbor.cfg in the path.
hown to fix  this issue , tks  !

**Comment by ninjadq** [comment]
You should use `goharbor/harbor-migrator:v1.9.0` if you wanna upgrade to 1.9.x
