### ISSUE TITLE
db_auth vs ldap_auth - how would Habor differentiate, username does not take domain name

### ISSUE THREAD

**Issue by mobla** [goharbor/harbor#992]
Steps:
1. Deploy Harbor OVA v0.4.5 with default options (db_auth)
2. Login as admin (db_user) and create a project and push some images from docker client
3. Now, reconfigure harbor to use ldap_auth using OVF properties and reboot the Harbor appliance
4. Login using admin (ldap_user) to add other user's to the project
5. admin user login uses db_auth and couldn't perform LDAP user/change role

Is this a limitation or how would customers use db_auth vs ldap_auth. Is it mutually exclusive (one or the other)?

Thanks,
Murali

**Comment by reasonerjt** [comment]
For now, it is, we'll document that.

**Comment by reasonerjt** [comment]
Closing as we will no longer support standalone ova
