### ISSUE TITLE
The header name "start time" is confusing.

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9926]
The GC log is not sorted by id or time

![image](https://user-images.githubusercontent.com/188115/69140657-e4367800-0afd-11ea-8649-d597dd5c70b0.png)

version:1.9.1

**Comment by wy65701436** [comment]
It's as designed, as any operation like configure schedule will create a new admin job.

The history tab only include the executed job.

**Comment by bitsf** [comment]
I think the word "Start Time" is not accurate, I just though it is the time the job run.
It may be something like "Create Time"

**Comment by xaleeks** [comment]
update time is the same thing as finished time? I think it should be configured by finished time, not start time.  @jwangyangls 

why should it be create time instead of start time? @bitsf

**Comment by bitsf** [comment]
it is the time that this job first created, and the job will run regularly, "start time" may be mistaken by user as the time of the current job.
update time is the actually time that latest job runs or finishes.

**Comment by reasonerjt** [comment]
Let's rename "start time" to "creation time"
