### ISSUE TITLE
Having the Notary issue with harbor 1.9.0 while configuring in the production

### ISSUE THREAD

**Issue by ksantoshpink** [goharbor/harbor#9927]
Hi,  @xaleeks  
we have a harbor notary issue while configuring for the production environment, where we configured and have a problem when we do the push,

DEBU[0000] received HTTP status 404 when requesting root.
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] No yubikey found, using alternative key storage: no library found
Enter passphrase for root key with ID f342833:
DEBU[0006] generated ECDSA key with keyID: bbeca25d5cd342a7ee826d6a46065d16da86c455e7d690de93561508ef30df54
DEBU[0006] generated new ecdsa key for role: targets and keyID: bbeca25d5cd342a7ee826d6a46065d16da86c455e7d690de93561508ef30df54
Enter passphrase for new repository key with ID bbeca25:
Repeat passphrase for new repository key with ID bbeca25:
Error: trust data missing for remote repository reg-harbor.net/test2/nginx or remote repository not found: timestamp key trust data unavailable.  Has a notary repository been initialized?

we have our production environment behind the GLB, and we are using the ca cert and key of the GLB for the https configuration for the Harbor.

Can you please help us on this.

**Comment by bitsf** [comment]
hi @ksantoshpink  I heard you have discussed with @wy65701436 , can you summary more about the architecture that we can try if this can be reproduced

**Comment by bitsf** [comment]
fixed by wy
