### ISSUE TITLE
Container goharbor/harbor-log keep on restarting

### ISSUE THREAD

**Issue by hopefulwalker** [goharbor/harbor#9928]
I can't find the root cause for this.  and I don't know how to check this 。

**Expected behavior and actual behavior:**
The goharbor/harbor-log container should up, but it keep on restarting

**Steps to reproduce the problem:**
1. install docker & docker-compose
2. download harbor offline installler.
3. update hostname in harbor.yml to the ip address.
4. running: sudo ./install.sh

**Versions:**
VM: vagrant 2.2.6 + VirtualBox 6.0.8 + bento-ubuntu-18.04-v201906.18.0-virtualbox
OS:  Ubuntu 18.04.2 LTS
Kernal: Linux center 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- harbor version: [1.9.3]
- docker engine version: [18.09.9]
- docker-compose version: [1.24.1]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
The container logs：
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.1910.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.1910.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.1910.0 try https://www.rsyslog.com/e/2103 ]
....

**Comment by hopefulwalker** [comment]
I find the cause。
Because the directory mounted in vm, the docker has no right to access.
But why there is no obvious error for permission denied.

**Comment by tongying123456** [comment]
> I find the cause。
> Because the directory mounted in vm, the docker has no right to access.
> But why there is no obvious error for permission denied.

Have you resolved it?

**Comment by dashcory** [comment]
how to resolve it ? In addition, my direcotry exists in the physical computer
