### ISSUE TITLE
can't find the download certificate button

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#9930]
I've installed harbor with https, and have provided the certificates path for https, but after the installation is done, I can not see the 'download certificate' button' in the repository view.

**Comment by stonezdj** [comment]
Copy the ca certificate to /data/ca_download/ca.crt, then this download link is visible in web console. add to [FAQ](https://github.com/goharbor/harbor/wiki/Harbor-FAQs)

**Comment by reasonerjt** [comment]
@renmaosheng how did you configure the ca cert?  The generate cert script is for testing only so it is not involved in the installation/bootstrap workflow.

**Comment by renmaosheng** [comment]
I've generated the certs by myself.
Can the 'copy step' be done automatically?
