### ISSUE TITLE
Create projects failed!

### ISSUE THREAD

**Issue by anhnt094** [goharbor/harbor#9931]
I can't find the root cause for this. and I don't know how to check this.

When I create new project, I got a problem:

![image](https://user-images.githubusercontent.com/34936548/69207545-bc3d2800-0b82-11ea-81b5-f6b8ed98206b.png)

"new-project" has not been created yet, but I still got message "Project name already exists.".

**Steps to reproduce the problem:**

1. install docker & docker-compose
2. download harbor online installler and extract.
3. update hostname and port in harbor.yml.
4. running: sudo ./install.sh

**Versions:**

- harbor version: [1.9.3]
- docker engine version: [18.09.9]
- docker-compose version: [1.24.1]

Here is /var/log/harbor/core.log when I write new Project Name:

`Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/core/filter/sessionchecker.go:22]: Mark the request as no-session
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/core/filter/security.go:229]: OIDC CLI modifier only handles request by docker CLI or helm CLI
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/core/filter/security.go:447]: got user information from session
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/core/filter/security.go:453]: using local database project manager
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/core/filter/security.go:455]: creating local database security context...
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/common/dao/project.go:199]: query sql:select count(1)  from project as p where p.deleted=false
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/common/dao/project.go:175]: query sql:select distinct p.project_id, p.name, p.owner_id, 
Nov 20 10:02:12 172.24.0.1 core[1285]: #011#011#011#011p.creation_time, p.update_time  from project as p where p.deleted=false order by name
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/pkg/scan/whitelist/manager.go:67]: No CVE whitelist found for project 1, returning empty list.
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019-11-20T03:02:12Z [DEBUG] [/pkg/scan/whitelist/manager.go:67]: No CVE whitelist found for project 1, returning empty list.
Nov 20 10:02:12 172.24.0.1 core[1285]: 2019/11/20 03:02:12 #033[1;44m[D] [server.go:2774] |   172.30.27.96|#033[42m 200 #033[0m|  12.623264ms|   match|#033[44m GET     #033[0m /api/projects/   r:/api/projects/#033[0m`

Here is project table in PostgreSQL database:
` project_id |  name   | owner_id |       creation_time        |        update_time         
------------+---------+----------+----------------------------+----------------------------
           1 | library |        1 | 2019-11-20 02:31:18.200941 | 2019-11-20 02:31:18.200941
(1 row)`

Could you tell me how to fix this issues? Thank you in advance!

**Comment by reasonerjt** [comment]
If you remove the `-` do you still see the error?

**Comment by anhnt094** [comment]
> If you remove the `-` do you still see the error?

Hi @reasonerjt. Yes, I still see the error.

**Comment by wy65701436** [comment]
can you share the output of brower DevTools Console when to create the project?

**Comment by xaleeks** [comment]
closing this since no replies

**Comment by softmarch** [comment]
+1
