### ISSUE TITLE
ui layout issue, some form input length are not consistent

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#9934]
This seems a regression. 
![image](https://user-images.githubusercontent.com/4946616/69214523-26b19080-0ba2-11ea-9eb6-6175e09bc63d.png)

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/69217209-105b0300-0ba9-11ea-95ce-b5f4c66b24d2.png)

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/69217716-3a60f500-0baa-11ea-9b20-2233b3353bde.png)

**Comment by jwangyangls** [comment]
The length of the input has been modified, and the reconstruction of the tab has been submitted.
