### ISSUE TITLE
Can't switch OIDC user when logout

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9941]
Step:
1. login in as user A
2. click logout
3. if in short time, click "login via oidc provider" again, it will be login as user A directly
4. if after long time, click "login via oidc provider" again, it allow input user name, but will fail login
![image](https://user-images.githubusercontent.com/188115/69224882-42c02c80-0bb8-11ea-92ef-fa67b7880896.png)
5. refresh ui, login will also fail
![image](https://user-images.githubusercontent.com/188115/69224906-4eabee80-0bb8-11ea-8712-a6a3c8546ee0.png)
6. workaround need clean browser storage

**Comment by reasonerjt** [comment]
step 3 is working as design by keycloak.
step 4 Looks like something wrong at keycloak which as out of our control.
step 5 This is probably working as expected, b/c after failover of keycloak, it switch the url and the state sent from UI is lost, and it's possible generated a new state. which mismatches the state stored in UI session before you are redirected to keycloak

This is just my theory, could you let me now how reproducible it is?  Or does it happen to other oidc provider?

You don't need to clear browser cache, refreshing at the login page will generate the new session.

I'm keeping this open but it's not a high priority to me.

**Comment by bitsf** [comment]
hi, I think OIDC have logout process
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout
And we should call it when logout from harbor

Refresh page is not help, and actually just clean harbor session not help too, so that's quit troublesome, I have to clear all browser cookie. Or at lease we can add another button to trigger this logout from OIDC.

**Comment by reasonerjt** [comment]
@bitsf 
I'm aware of this piece, but this is still a `draft`, I also checked, keycloak seems to support that, but auth0, dex, google... do not.  I wish to suggest we wait till this process more widely adopted and verified.  

Additionally I would hope the upstream library support that,  (there's a PR but not merged for some reason)

As for troublesome issue, seems you can constantly reproduce?  I'll spend some time to produce also.

**Comment by reasonerjt** [comment]
@bitsf As for the timeout issue, I tried twice and didn't see any error.

After logging in to keycloak I  logged out from Harbor and waited for >1.5 hrs to wait for the session on keycloak to expire.

I click the "LOGIN VIA OIDC..." button and the login window on keycloak pop-up as expected, I think it maybe intermittent error happened on keycloak in your case, which is highly un-reproducible.

I'll leave this issue here for reference but stop trying to reproduce it.

**Comment by Maw1395** [comment]
Auth 0 now has a logout endpoint : https://auth0.com/docs/api/authentication#logout
