### ISSUE TITLE
The same project webhook cannot support multiple services

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#9942]

**Comment by jwangyangls** [comment]
This is a suggestion

**Comment by reasonerjt** [comment]
@jwangyangls please specify with a concrete use-case

**Comment by jwangyangls** [comment]
Multiple servers want to get information about item 1 in the harbour, at this time we are considering expanding the endpoints in the webhook to multiple

**Comment by xaleeks** [comment]
multiple services? is this referring to multiple endpoints for receiving webhooks? @jwangyangls

**Comment by jwangyangls** [comment]
yeach @xaleeks

**Comment by jwangyangls** [comment]
for example, harbor webhook can send messages to WeChat and Slack server at the same time

**Comment by xaleeks** [comment]
I think it'd be good to at the very least be able to set up multiple endpoints to receive webhooks like registry endpoints.  Can then choose one default for all webhooks or extend to use different endpoints for different webhooks, or different endpoints if we scope this to projects for other types of multitenant deployments.  Any comments? not in scope for the 2.0 however.  @mmpei @wy65701436

**Comment by xaleeks** [comment]
This is now supported
