### ISSUE TITLE
Harbor project name length

### ISSUE THREAD

**Issue by anvivi99** [goharbor/harbor#9946]
**Is your feature request related to a problem? Please describe.**
Harbor project name requirement is as below, one char project name is not allowed
const projectNameMaxLen int = 255
const projectNameMinLen int = 2
const restrictedNameChars = `[a-z0-9]+(?:[._-][a-z0-9]+)*`

**Describe the solution you'd like**
One char namespace is allowed in K8. In case there is one to one mapping between namespace and Harbor project, this will result in project creation failure. So if it is possible, we propose to allow one char project name

**Describe the main design/architecture of your solution**
One to one mapping between K8 namespace and Harbor project

**Describe the development plan you've considered**
const projectNameMinLen int = 1

**Additional context**

**Comment by reasonerjt** [comment]
re-open till the commit is cherry-picked
