### ISSUE TITLE
Garbage collection run is not marking the registry as "Readonly"

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#9947]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I had too many large images in harbor (over aws s3), I deleted all the repositories in harbor.
I triggered GC.
People in the team were still able to push images.
We tried to find the logs around "read-only" but nither core, registry or job-service pods had any log info around registry being marked as read-only and then reverted back 

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
k8s 1.14.6
`$ helm list
NAME         	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE  
harbor1      	1       	Wed Nov 20 10:37:11 2019	DEPLOYED	harbor-1.2.3        	1.9.3      	harbor1   `

- harbor version: [1.9.3]
- docker engine version: [19.03.5]
k8s 1.14.6

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by xaleeks** [comment]
can you look into this ? @wy65701436

**Comment by wy65701436** [comment]
@bjethwan can you provide the GC log?
