### ISSUE TITLE
Upgrade to version 1.9 with a mirror size of 0B

### ISSUE THREAD

**Issue by shehuiwu** [goharbor/harbor#9949]
Hello, I upgraded from 1.4 to 1.6 and then upgraded to 1.9, but there are still some images in my mirror repository that are 0B size. Is this a problem with my upgrade process? I also can't understand the repository. After the deleted repository still exists, I can't delete the image at all.
![harbor-bug](https://user-images.githubusercontent.com/18510901/69301892-adbe4180-0c52-11ea-9955-9f33e3a94785.jpg)

**Comment by wy65701436** [comment]
hi, the size 0 issue is actually a bug of upstream, you can find several issues point on this. The upgrade would not fix it but do the data migration. BTW, the size 0 image will be counted into the project quota usage.
We will try to do some enhancement about it, but not in v1.9.0.

**Comment by shehuiwu** [comment]
Thank you very much for your answer.
