### ISSUE TITLE
tag pull time has not been recorded when scan

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#9953]
When I actively scan a tag, there is already a pull operation. In the record of the repository, the number of pulls is increased by one, but the pull time in the same tag is not recorded.
![image](https://user-images.githubusercontent.com/29826789/69313947-e4558580-0c6d-11ea-873d-3a654c51b0c0.png)
![image](https://user-images.githubusercontent.com/29826789/69314015-0c44e900-0c6e-11ea-953c-4ee5942e682b.png)
![image](https://user-images.githubusercontent.com/29826789/69314408-0dc2e100-0c6f-11ea-9c73-e40bc22d8f36.png)

**Comment by wy65701436** [comment]
it's because the `pull time` is updated per tag, not digest.

**Comment by reasonerjt** [comment]
Why we show the pull time?  can we remove it?  Think `ls` ....

But in the screen shot the creation time does not seem correct....

**Comment by flixgithub** [comment]
![image](https://user-images.githubusercontent.com/6768036/69608444-6c6acf00-1062-11ea-8c91-3ba5f9bbb7fe.png)

![image](https://user-images.githubusercontent.com/6768036/69607989-658f8c80-1061-11ea-99f5-4e375655cc65.png)

![image](https://user-images.githubusercontent.com/6768036/69608040-82c45b00-1061-11ea-897d-cd2e84ea506f.png)

@wy65701436 @reasonerjt @jessehu @edevil 
i also meet this kind of problem, pull time is not set, i don't know why
my tag retetion policy is based on rules pulled within last #days, i think if pull time is not set, this rule will not be effective
please help thanks a lot
