### ISSUE TITLE
docker push error in HA architecture

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#9955]
I am getting 500 internal error while pushing an Image with docker push from Registry VM.
Architecture.
Service VM_0, VM_1(Active)
Scalable VM_0,_1(Active)
Database VM_0

Is there any certificate configuration needs to be done to get them in sync on both the VMs?

With single Service VM the docker push is working fine.

Please help

**Comment by AyushCloud** [comment]
The push refers to repository [pod5-104-96-32.3dx-staging.3ds.com:443/test/ubuntu]
e0b3afb09dc3: Pushed
6c01b5a53aac: Pushed
2c6ac8e5063e: Pushed
cc967c529ced: Pushed
received unexpected HTTP status: 500 Internal Server Error

**Comment by christopherdraper** [comment]
Same issue, in the logs I noticed a permissions error when the registry was trying to `mkdir /storage/docker`

If you exec into the container: 
```shell
harbor [ / ]$ mkdir /storage/test
mkdir: '/storage/test': Permission denied
```

**Comment by aladjadj** [comment]
Hi, do you have same secrets in /data/secrets ?

**Comment by AyushCloud** [comment]
i have changed for registry and core only. do i change for others also
