### ISSUE TITLE
optimization: vulnerability scans tied to image IDs instead of tags

### ISSUE THREAD

**Issue by hostalp** [goharbor/harbor#9956]
**Is your feature request related to a problem? Please describe.**
Currently, if there are multi-tagged images (image with multiple tags), the vulnerability scan has to be performed for each image tag individually - resulting in the need to scan the same image multiple times. This is suboptimal.

**Describe the solution you'd like**
Use the actual image ID instead of the tag, perform the scan once and reuse & display the same results for all image tags of the same actual image.

**Comment by heww** [comment]
Harbor 1.10 will scan the image by digest of the image.

eg, here are three images `library/redis:5.0`, `library/redis:latest`, `private/foo:latest`,  the digests of these three images are same. If we scan `library/redis:5.0` then `library/redis:latest` and `private/foo:latest` will display the results of `library/redis:5.0`.
