### ISSUE TITLE
about downloding

### ISSUE THREAD

**Issue by kinbod** [goharbor/harbor#9958]
Hi, dear manager
     First of all, thanks for making so nice app. I met an problem that I'm living in eastern hemisphere,but our sweet github lives in western. so sometimes it's hard to download our latest release version of cute harbor with reasons for network speed. so I hope we can provide an offline installation package download address other than GitHub，thanks。

**Comment by xaleeks** [comment]
most likely don't have resource for this right now but where would you like this? @kinbod

**Comment by kinbod** [comment]
> most likely don't have resource for this right now but where would you like this? @kinbod

I use offline intallation to resolve this problem. pull down the relative images then save them and push them to my private registry.
