### ISSUE TITLE
robot account token unlimited expiration

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#9966]
Hello.

This is short question.

Can I set Robot Token Expiration : -1 for unlimited expiration ?

I am using v1.8.1.

Many thanks.

**Comment by Hokwang** [comment]
@xaleeks
Please consider this requirement.

**Comment by xaleeks** [comment]
not yet, but you will be able to on the next release, we are adding this capability to robot so you can define expiration date on creation and allow setting it to infinity @Hokwang

**Comment by xaleeks** [comment]
I'm going to close this one and you can follow this ticket instead: https://github.com/goharbor/harbor/issues/8405
