### ISSUE TITLE
How can I push chart to harbor when using helm3 in cli mode

### ISSUE THREAD

**Issue by JiaoZhengYa** [goharbor/harbor#9975]
as the user guide says , i have installed helm push plugin and do helm push, but it doesn't work:

`Error: Couldn't load repositories file (/home/XXX/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "push" exited with error`

but helm3 has removed both tiller and helm init cmd, so is there any idea for me?
harbor version 1.8.2  helm version 3.0.0

**Comment by wy65701436** [comment]
refer to https://github.com/goharbor/harbor/issues/9954

**Comment by JiaoZhengYa** [comment]
> 
> 
> refer to #9954

it works

**Comment by LinuxArchitects** [comment]
This is a quickfix until the push pluging comes with support for helm3 
You may need to declare your repositories at two different place : 

# hotfix for push pluging
`helm repo add harbor-staging --username=${HARBOR_USER} --password=${HARBOR_PASSWORD}  ${HARBOR_HELMCHART_PROJECT}    --repository-config=/$HOME/.helm/repository/repositories.yaml
`
with a tiny modification

`
'sed -i -e "s/apiVersion: ""/apiVersion: v1/g" /$HOME/.helm/repository/repositories.yaml'
`
# add the repos to the standart file
`helm repo add harbor-staging --username=${HARBOR_USER} --password=${HARBOR_PASSWORD}  ${HARBOR_HELMCHART_PROJECT}`
