### ISSUE TITLE
containers restarting

### ISSUE THREAD

**Issue by tongying123456** [goharbor/harbor#9977]
why i make the sourcecode completed，the container eg:core、adminservice is restarting，so i can't login in the harbor

**Comment by reasonerjt** [comment]
did you check the log?

And what version of source code are you using?  Admin service has been removed from all versions that are maintained.

**Comment by tongying123456** [comment]
> did you check the log?
> 
> And what version of source code are you using? Admin service has been removed from all versions that are maintained.

1.7.0

**Comment by reasonerjt** [comment]
1.7.0 is no longer maintained, I don't think we have bandwidth to provide help...

**Comment by reasonerjt** [comment]
I think you can attach the log files and see if anyone in community can provide help.
