### ISSUE TITLE
How can I change the mysql's password?  Thanks!

### ISSUE THREAD

**Issue by okgoba** [goharbor/harbor#9979]
I'm using Harbor V1.5, and I want to upgrade the version to V1.6
Now , I meet a error when running the commond 
"docker run -it --rm -e DB_USR=root -e DB_PWD=Sh3m%oMk -v /app/harbor_1.5/data/database/:/var/lib/mysql -v /app/harbor_1.5/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /app/cfg_bak:/harbor-migration/backup goharbor/harbor-migrator:v1.6.3 up "

It caused by the password "Sh3m%oMk" , so I need to change it in Harbor V1.5.
I've tried to update harbor.cfg  -> prepare and also change data/database/mysql/user.* , buy  failed. Pls  help me to slove it. thanks!

**Comment by reasonerjt** [comment]
@okgoba The value you set in `harbor.cfg` is the initial password of mysql, so updating it won't help.

If you wanna change the password, I think you need to `docker exec` into your mysql container while v1.5 is running and change it.

The version is quite old that I don't have an env, so I can't provide more detailed steps.

**Comment by okgoba** [comment]
@reasonerjt  ok ,thanks, I have fixed this problem.
