### ISSUE TITLE
CLI Secret missing for LDAP user

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#9991]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
User Profile > CLI Secret option is missing when logged in as LDAP user.
![selection (1)](https://user-images.githubusercontent.com/5045325/69532418-c6549180-0f9b-11ea-9d11-a3174026f58e.png)

**Steps to reproduce the problem:**
Harbor running on k8s using harbor-helm chart
Configure LDAP authentication.
Login as LDAP user on harbor portal (successful)
User Profile > CLI Secret option is missing. 

**Versions:**
Kubernetes: v1.14.6
Harbor: v1.9.2-17aba8be

**Additional context:**
CLI Secret is working fine for google or OIDC authentication.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by reasonerjt** [comment]
@bjethwan This is working as design, CLI secret is for OIDC user only because there's no good way for handling SSO via docker CLI.

For LDAP you can use the password of LDAP for `docker login`

**Comment by bjethwan** [comment]
Thanks @reasonerjt .
I tried and it works !!!
Thanks once again.
