### ISSUE TITLE
QUESTION: Harbor DRC replication

### ISSUE THREAD

**Issue by zdenekvicar** [goharbor/harbor#9994]
Hello Harbor community, I would like to raise a question about recommended DRC solution for Harbor.

Description of a problem:
Harbor is running in Kubernetes cluster (current version 1.6.0). We need to introduce some DR failover option, therefore we are building new K8s cluster in DRC where Harbor will be deployed as well.
However, I need to somehow solve replication of Harbor data ... and by data, I mean all the data. So far when I was searching how replication works (even on newer versions 1.8.x and 1.9.x) I found its able to replicate images themselves - but I need to replicate also settings (LDAP connection, user privileges, projects, etc.)

Is something like that supported (on in a roadmap) on Harbor application layer ? Or do I need to solve this on lower layers (e.g. storage replication + Postgre replication between those 2 instances).

**Comment by reasonerjt** [comment]
It's definitely not on the roadmap of Harbor to replicate other data to other Harbor instance.  It would be another project or 3rd party tool.

I would suggest that you should solve it on lower layer.

**Comment by xaleeks** [comment]
this is being considered and maybe solved through our operator deployment of harbor to capture all metadata including configurations and policies like the ones you mentioned and more.  But it will not be part of the next release Harbor 2.0.  Feel free to ping me some specifics and reasons, xalex on slack @zdenekvicar
