### ISSUE TITLE
Harbor prompting to set username for OIDC first login

### ISSUE THREAD

**Issue by adityanmishra** [goharbor/harbor#9995]
What can we help you?
We are a big enterprise with more than 10000 users and many tools where user has to login. It is not feasible to for an user to keep remembering usernames for different tools. For this we are trying to use OIDC. But on first login through OIDC harbor prompts for setting an username which causes lot and lot of trouble later.

**Describe the solution you'd like**
Keep the username same as OIDC or give a admin configuration option not to prompt the username set dialog

**Comment by reasonerjt** [comment]
Could you elaborate why it causes lot of troubles and what is ideal workflow in your opinion?

If we bypass the usage and use a claim in id_token as username, because the OIDC provider is external we cannot guarantee there's no collision.  When collision happens the failure will make user more confused.

**Comment by danielzhanghl** [comment]
hi, it's not convenience for user to enter the name again if using oidc, if there are lot of users in the oidc system.
if there is option to just use the user name form oidc, it will be great. who choose this configuration could be ware of any collision.

**Comment by adityanmishra** [comment]
Sorry for late reply. Currently in our company the auth tools like openldap and atlassian crowd is used along with Microsoft Active Directory. All these tools are connected to company **active directory** for user authentication. The advantage for all tools like jira, bitbucket, confluence, jenkins, Sonatype nexus3, VMs and lot others username and password is same through out. We are in process of integrating keycloak with backend authentication for active directory as it will solve many kubernetes auth problems. But as you see the username password still is going to be same. 
So if any harbor also same happens to be using the same username the end user experience will be really good and as username cannot be modified from UI by admin so it is desirable to have same username from OIDC.

**Comment by wmgroot** [comment]
We would also like the option to enforce that the user's Harbor username is identical to their oidc username. It's currently a very manual process to correct a misconfigured username.

**Comment by wmgroot** [comment]
Looks like this request is in progress with a PR here: https://github.com/goharbor/harbor/issues/8422

**Comment by xaleeks** [comment]
This will be taken care of by this PR https://github.com/goharbor/harbor/pull/9311, please watch progress there, we are very close to merging it
