### ISSUE TITLE
Should 'STORAGE' on first page shows disk usage of /data/registry ?

### ISSUE THREAD

**Issue by anyuan95** [goharbor/harbor#9997]
I'm using the directory '/data' as data_volume, mount another disk to directory '/data/registry'.
As follows:
```
[root@platform4 harbor1.8]# df -h /data
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root   99G   74G   21G  79% /
[root@platform4 harbor1.8]# df -h /data/registry/
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1  1.5T  634G  857G  43% /data/registry
```
And now, harbor first page shows STORAGE: '98GB Limit', '78GB Used'.
**I think, should we show the usage of REGISTRY VOLUME on the first page?**
Because I think other components only take up very little storage, in fact we always just need pay attention to the usage of REGISTRY VOLUME.

By the way, Have you considered HOW TO SHOW THE STORAGE on first page while using multiple different disks in the data_volume directory?

PS. The harbor version I'm using is 1.8.0.

**Comment by balonik** [comment]
Hi,
can this get some attention please?
I think it is common to have separate mount point for harbor/registry.
The Harbor front page should show the size and occupied space of the registry and not root dir.
